### ISSUE TITLE
Add rowCount() to Query to simplify code.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10008]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: Apache2, Ubuntu, MySQL, PHP 7.1

### What you did

Working with queries like DELETE/UPDATE creates extra work for the developer to simply verify the modified row count.

```
   $statement = $this->find()
           ->update()
           ->where([.....])
           ->execute();

   try {
         return $statement->rowCount();
   } finally {
         $statement->closeCursor();
   }
```

It's recommended to close the cursor when you're done with the statement. 

### What happened

You can do the same above, but skip closing the cursor.

```
   return $this->find()
           ->update()
           ->where([.....])
           ->execute()
           ->rowCount();
```

This leaves the cursor to be handled by gc..

### What you expected to happen

I think we could add a `rowCount()` method to the Query object to simplify this for people who want to always close the cursor.

```
   return $this->find()
           ->update()
           ->where([.....])
           ->rowCount();
```

The above would execute the query, return the count and close the statement.

**Comment by ADmad** [comment]
> The above would execute the query, return the count and close the statement.

That would be hidden magic IMO.

**Comment by lorenzo** [comment]
The closing of the cursor is actually reason number one I did not expose that method

**Comment by thinkingmedia** [comment]
@ADmad @lorenzo please post code samples that explain the problems my recommendation would introduce.

**Comment by lorenzo** [comment]
@thinkingmedia with automatic closing of the cursor:

```php
$statement = ...->where([.....])->execute();
$count = $statement->rowCount(); // Your proposal is to close automatically here
$first = $statement->fetch(); // Error, the statement is closed
```

**Comment by thinkingmedia** [comment]
@lorenzo thanks for clarifying. That's not what I was proposing.

```
$count = $this->find()->update()->set(...)->where([...])->rowCount(); // closes here. it's a new method to Query.
```

**Comment by ADmad** [comment]
@thinkingmedia  You seem to be missing the point. Having `rowCount()` close the cursor too would be non-intuitive. Most users won't realize that the method closes the cursor too and may try to use another query class method after calling `rowCount()`.

**Comment by thinkingmedia** [comment]
@ADmad no, that's not a problem. The cursor belongs to a prepared statement that is executed. The user never gets a reference to the statement. They only get the row count result from executing the query. The query does not keep a reference to the statement.

I guess this just proves that it would be confusing.

What is we renamed the new method to `executeAndClose()` and have it return `int` instead of `Statement`?

**Comment by ADmad** [comment]
A more intuitive name hinting what the method does works for me.

**Comment by thinkingmedia** [comment]
PR is up now
