### ISSUE TITLE
Cannot disable verbose on shell tasks

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10001]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: Bash on Windows 10, Apache2, PHP 7.1, Mysql

### What you did

Created a shell that uses a task. Call logging methods to output debug message.

```
class WorkerShell extends Shell {
    public $tasks = ['Foo'];

   public function command() {
         Log::debug('Debug from Worker');
         $this->Foo->main();
   }
}

class FooTask extends Shell {
       public function main() {
           Log::debug('Debug from Foo');
       }
}
```

Execute without verbose shows debug message from `FooTask`

```
bin/cake worker command
Debug from Foo
```

Execute with verbose shows debug from both

```
bin/cake worker command -v
Debug from Worker
Debug from Foo
```

### What happened

It looks like the verbose flag is only respected by the first `Shell` class. When the shell is dispatched the `Shell::runCommand` is execute which setups up the correct output settings, but when the `FooTask` is loaded there is no setup done on the logger. So all output levels are enabled.

### What you expected to happen

There should only be one `ConsoleIO` object created and configured for logging, and then other tasks should use that IO, but instead multiple `ConsoleIO` objects are being created.

Debugging also shows that the logger is configured multiple times before a Shell finally executes. This should be more efficient.

**Comment by markstory** [comment]
Would passing the root shell's ConsoleIo instance into the tasks help here?

**Comment by thinkingmedia** [comment]
@markstory I don't think so, because the `Shell` constructor resets the logger.

I think if that is removed from the constructor it'll fix the problem. As the logger is configured via the runCommand on Dispatcher. Shell's constructor then replaces the logger.

**Comment by markstory** [comment]
> I think if that is removed from the constructor it'll fix the problem. As the logger is configured via the runCommand on Dispatcher.

Yeah not sure why that is there. I'll take a further look.
