### ISSUE TITLE
Collection::every works unexpected on empty collections 

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#10002]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: 3.1.11

I'd like to use this issue as a fresh start for discussion on #8670 and #8632, because it has just bitten me again, and I still deeply believe that this is a bug in Cake.

The current behaviour of `Collection::every` is to return `false`, when the collection is empty. This is contrary to **every single** other implementation I know of and also contrary to the mathematical definition of an empty set (a empty set [fulfils every predicate](https://en.wikipedia.org/wiki/Vacuous_truth)).

``` java
//Java
Arrays.stream(new int[] {1}).allMatch(x -> false); //false
Arrays.stream(new int[] {}).allMatch(x -> false); //true
```

``` csharp
//C#
new int[]{1}.All(x => false); //false
new int[]{}.All(x => false); //true
```

``` python
#Python
all([False for x in [1]]) #false
all([False for x in []]) #true
```

``` php
//CakePHP
collection([1])->every(function() {return false;}) //false
collection([])->every(function() {return false;}) //false
```
(Many more examples can be found)

This is not just an irrelevant edge case: I just wrote a rule that should ensure that a project can only be made public if every course in the project has been checked. (Simplified example from my current work)

```php
$rules->addUpdate(function ($entity) {
    return !$entity->isPublic() || collection($entity->courses)->every(function ($e) {
        return $e->isChecked();
    });
});
```

This works, but only, if the project has at least a single course. If not, the condition fails, because `every` returns false. But clearly "every course has been checked", because there is no course that is not checked (there is, in fact not a single course at all, but this does not matter). So after finding this bug, I had to extend the condition to this:

```php
$rules->addUpdate(function ($entity) {
    return !$entity->isPublic() || count($entity->courses) === 0 || collection($entity->courses)->every(function ($e) {
        return $e->isChecked();
    });
});
```

This is more code, just required by Cake crazy implementation of `every`. I simply can come up with a case, where the current implementation would be better... In fact, I would even simplify the code of `every` because returning `true` for an empty set "is just the natural thing".

I'm very open for discussing on this topic. I just believe that this is a serious bug in CakePHP and should be fixed.

**Comment by markstory** [comment]
I'm guessing your [comment here](https://github.com/cakephp/cakephp/issues/8632#issuecomment-210142630) was part of the reason that the logic was flipped in #8670. I'm ok with changing it back. But its the kind of subtle change that will create issues for other folks.

**Comment by nrother** [comment]
Yes, that comment went kind of wrong. I wanted to achieve the exact opposite... (changing `Hash::contains` instead of changing `Collection::contains`). 👍 For changing (at least) `Collection::every` back.

**Comment by markstory** [comment]
We could do this in a minor release like 3.4 where behavior changes are easier to communicate.

**Comment by markstory** [comment]
Closing as a pull request for 3.4 is up.
