### ISSUE TITLE
Generated lft/rght values by tree behavior not what expected and cause the whole tree not work.

### ISSUE THREAD

**Issue by kiang** [cakephp/cakephp#10005]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 2.9.2
* Platform and Target: Apache/2.4.10, mysql  Ver 14.14 Distrib 5.6.28, PHP 5.6.4-4ubuntu6.4 / Ubuntu 15.04 with latest stack

### What you did
To recursively save a complete ACO tree with code like below.
```
public $actsAs = array('Tree');
public function completeTreeSave($tree, $parent_id = null)
    {
        if ($parent_id === null) {
            $this->truncate();
        }
        foreach ($tree as $aro => $tre) {
            $this->create();
            $this->save(array(
                'parent_id' => $parent_id,
                'alias' => $aro
            ));
            if (is_array($tre)) {
                $this->completeTreeSave($tre, $this->id);
            }
        }
    }
```

### What happened
The generated lft/rght values not what expected and cause the whole tree not work.

### What you expected to happen
I just copied the old ( cakephp 2.5.4 ) tree behavior to replace the new one and everything works as before.

**Comment by josegonzalez** [comment]
@kiang what was is the correct behavior and what is the incorrect behavior? Better stated, what records does the 2.9.2 TreeBehavior create vs the 2.5.3 TreeBehavior?

**Comment by kiang** [comment]
correct behavior:
![right](https://cloud.githubusercontent.com/assets/47844/21797775/f9070846-d74b-11e6-9fda-513e176ca783.png)

incorrect behavior:
![wrong](https://cloud.githubusercontent.com/assets/47844/21797784/0429cd58-d74c-11e6-82e9-dfb09d2ea017.png)

The node 'app' is the root node of the whole tree. I haven't looked deeper to see what happened.

**Comment by josegonzalez** [comment]
Do you also have the incoming values for `tree` and `parent_id`?

**Comment by kiang** [comment]
Incoming values like
```
$this->completeTreeSave(array(
    'app' =>
    array(
        'GroupPermissions' =>
        array(
            'admin_add' => 0,
            'admin_delete' => 1,
            'admin_edit' => 2,
            'admin_group' => 3,
            'admin_index' => 4,
        ),
        'Groups' =>
        array(
            'admin_acos' => 0,
            'admin_add' => 1,
            'admin_delete' => 2,
            'admin_edit' => 3,
            'admin_index' => 4,
        ),
        'Members' =>
        array(
            'admin_acos' => 0,
            'admin_add' => 1,
            'admin_delete' => 2,
            'admin_edit' => 3,
            'admin_index' => 4,
            'admin_test' => 5,
            'admin_view' => 6,
            'login' => 7,
            'logout' => 8,
            'setup' => 9,
        ),
    ),
));
```

full source:
https://github.com/kiang/drugs/blob/master/Plugin/Permissible/Model/PermissibleAco.php

**Comment by markstory** [comment]
I cna take a look.

**Comment by markstory** [comment]
I wasn't able to reproduce the incorrectly built tree. I put together [this gist](https://gist.github.com/markstory/34c250f7045f0fe9698366c0063c9bb6) of what I tried.
