### ISSUE TITLE
DateTime validation triggers warning on expression.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10017]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: Apache2, MySQL, PHP 7.1, Ubuntu on Windows

### What you did

Assign `dateTime()` validation rule to a field.

```
    public function validationDefault(Validator $validator)
    {
        $validator->dateTime('status_next');
        return $validator;
    }
```

Use an expression to assign `NOW()` to the field.

```
     $query = $table->find();
     $entity = $table->newEntity([
        'status_next'=>$query->func()->now()
     ]);
     $table->save($entity);
```

### What happened

Triggers PHP warning about `explode()`

```
2017-01-11 19:36:01 Warning: Warning (2): explode() expects parameter 2 to be string, object given in [/mnt/c/work/tags/web/vendor/cakephp/cakephp/src/Validation/Validation.php, line 464]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
explode - [internal], line ??
Cake\Validation\Validation::datetime() - CORE/src/Validation/Validation.php, line 464
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE/src/Validation/RulesProvider.php, line 72
Cake\Validation\ValidationRule::process() - CORE/src/Validation/ValidationRule.php, line 138
Cake\Validation\Validator::_processRules() - CORE/src/Validation/Validator.php, line 1756
Cake\Validation\Validator::errors() - CORE/src/Validation/Validator.php, line 137
Cake\ORM\Marshaller::_validate() - CORE/src/ORM/Marshaller.php, line 244
Cake\ORM\Marshaller::one() - CORE/src/ORM/Marshaller.php, line 177
Cake\ORM\Table::newEntity() - CORE/src/ORM/Table.php, line 2157
```

### What you expected to happen

Should allow validation to be successful on values that are expressions.

**Comment by thinkingmedia** [comment]
Maybe this is by design. I'm starting to think you can't use expressions at all with `newEntity()`?

**Comment by lorenzo** [comment]
no, you can't do that... but maybe we it should check that it is an array before doing the explode

**Comment by thinkingmedia** [comment]
@lorenzo don't both, if I remove the rule it still fails badly.

ORM tries to type convert from the expression to DateTime type and dies.

A simple test to see if the value is an expression and throw an error saying it's not supported might be helpful.

**Comment by ADmad** [comment]
> ORM tries to type convert from the expression to DateTime type and dies.

No, that's not what's happening. It is trying to use the expression instance in `explode()` as evident from the error message and line number.

**Comment by thinkingmedia** [comment]
> No, that's not what's happening. The validation method is trying to use the expression instance in explode() as evident from the error message and line number.

@ADmad You misread my post. I said "if I remove the rule it still fails" as it will try to type convert the expression to DateTime type.

**Comment by markstory** [comment]
I've put a pull request up to fix the validation. I'm not sure it is a good idea to set precedent and accept DB expression objects as entity property values. I feel like we'll be opening a pretty big can of worms if we do.

**Comment by ADmad** [comment]
@thinkingmedia Yes sorry, I didn't co-relate the 1st and 2nd statement.

>  I'm not sure it is a good idea to set precedent and accept DB expression objects as entity property values. I feel like we'll be opening a pretty big can of worms if we do.

Absolutely, entities should not accept DB expressions.

**Comment by ADmad** [comment]
#10021 takes care of gracefully handling the issue in validation method. In don't think anything more needs to be done here.
