### ISSUE TITLE
Resource routes to accept alphanumeric parameters.

### ISSUE THREAD

**Issue by mbryja** [cakephp/cakephp#10016]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: API

### What you did
I'm trying to use alphanumeric parameter for resource route's map:

```php
    $routes->resources('Products', [
        'map' => [
            'sku/:sku' => [
                'action' => 'viewBySku',
                'method' => 'GET',
            ]
        ]
    ]);

    public function viewBySku($sku) {
        die($sku);
    }
```

### What happened
Missing argument 1 warning, but the sku still has been passed to the router

### What you expected to happen
I want to avoid the following

```php
    public function viewBySku() {
        if (!$sku = $this->request->param('sku')) {
            throw new BadRequestException("Sku is missing");
        }

        die($sku);
    }
```

**Comment by ADmad** [comment]
Route element `sku` won't automatically get passed to action as parameter. You need to use the `pass` option when setting up route. Please check the manual for details.

**Comment by mbryja** [comment]
Documentation didn't help me a lot but looking into the source code did. Thank you for letting me know that there is an alternative approach.

```php
    $routes->resources('Products', [
        'map' => [
            'sku/:sku' => [
                'action' => 'viewBySku',
                'method' => 'GET',
            ]
        ],
        'connectOptions' => [
            'sku' => '[a-zA-Z0-9\-]{2,10}',
            'pass' => ['sku', 'id']
        ]
    ]);
```
