### ISSUE TITLE
Missing typehinting for Query

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#10014]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0-beta4
* Platform and Target: PhpStorm 9.0.2

### What you did
Typing

```
$user = $this->Users->find('all')
            ->where(['api_admin' => 1])
            ->toArray();
```

### What happened
`toArray()` is not recognised. 

(just as many other functions like first, last, filter, etc.)
### What you expected to happen
I expected typehinting showing me what options I have, but also which functions are available after the first part of my query construction.

### What I found out

When using `$this->find()->toArray()`, I noticed typehinting is working, but it links to https://github.com/cakephp/cakephp/blob/master/src/ORM/Query.php#L59, because `ORM\Table::find()` returns a query of the type `Cake\ORM\Query`.

When I check what the `where()` part is returning, it is returns an instance of `Cake\Database\Query`, where the earlier mentioned functions are not added in the docblock.

**Comment by JelmerD** [comment]
Not entirely sure if these kind of "bugs" are bugs or enhancements.

**Comment by markstory** [comment]
The code 'works', its only IDE autocompletion that isn't working. I see this as something that makes using the framework better/nicer/easier and is something folks like @dereuromark and @thinkingmedia care about and making good progress on.

**Comment by antograssiot** [comment]
moving https://github.com/cakephp/cakephp/blob/master/src/ORM/Query.php#L34-L67 to `Cake\Database\Query` would do the trick but I don't think that it would not be correct, right ?

**Comment by thinkingmedia** [comment]
It's a limitation of the version of PhpStorm you're using.

Upgrade to `2016..2.1` and it'll work.

**Comment by antograssiot** [comment]
@thinkingmedia strange enough that I was able to reproduce it with PHPStorm 2016.3.2 then

**Comment by thinkingmedia** [comment]
@antograssiot PhpStorm's use of this particular part of type-hinting is often flaky. It requires the IDE to handle infer the `CollectionInterface` type, the `Query` type and also infer type from `@return $this`.

So you can have a call chain that uses all 3 of the above on the same object instance.

I seen PhpStorm struggle with the usage of `@return $this` and how PHPStorm infers typing. While `@return $this` is perfectly valid PHPDoc the handling of it by PHPStorm is poor. It's further complicated when a lower derived class uses it and expect the auto-completion from the higher extended class. When there are multiple classes extending the base class the IDE gets confused.

With that said, the `toArray` on Query is working for me, but maybe there are cases where it breaks.

![image](https://cloud.githubusercontent.com/assets/551022/21855918/1495fce6-d7ee-11e6-8f12-f2a470cf2f7c.png)

Here's the problem

```
abstract class A {
     /* @return $this */
     public function Foo() { }
}

class B extends A {
      public Bar() {}
}

class C extends A {
     public Car() {}
}

$a = new B();
$a->Foo()->Bar();  // IDE can get confused by $this. Is Foo() returning B or C?
```

**Comment by ndm2** [comment]
@thinkingmedia It will return `B`, and PhpStorm gets it correct, at least in terms of auto-completion and jumping to declarations :wink: (the info tooltip will display that it returns `A` though, which is a bug).

The actual problem here is https://github.com/cakephp/cakephp/pull/9893. Could it be that you are testing this against the master branch?

**Comment by dereuromark** [comment]
We can fix up the self to $this and hopefully this will resolve almost all issues now that we use the separate setter and getter calls (which previously didnt work with $this).

**Comment by antograssiot** [comment]
I tested against 3.next

**Comment by ADmad** [comment]
I have started to get the feeling as if we have assimilated phpstorm's issues tracker into cakephp's tracker :P

**Comment by dereuromark** [comment]
Actually, with a lot of these issues any IDE would have similar introspection problems. It is sure to the benefit of all, if we get those resolved piece by piece.
Some also reveal wrong interface usage, which are also a valid error to be pointed out.
Apart from the obvious IDE bugs many of those "yellow markups" in the core code are valid concerns that the framework should address in future versions.

**Comment by thinkingmedia** [comment]
@ADmad resistance is futile.

![1hgzi6](https://cloud.githubusercontent.com/assets/551022/21858592/af1e2e2e-d7f7-11e6-91e6-e6347aeb5519.jpg)

**Comment by dereuromark** [comment]
Make sure the annotations are all up to date, e.g. using https://github.com/dereuromark/cakephp-ide-helper/ , then this will work in a recent version of PHPStorm as probably with all supporting others.
