### ISSUE TITLE
Authentication Customizing Find Query

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/cakephp#10011]
Hello Bakers !!
I have a plugin that it only serves to do authentication and user control.

However I have the following problem, when trying to make a finder => 'Auth' it returns when trying to log "Unknown finder method auth"

Plugin \ AppController

'Authenticate' => 'Form' => ['userModel' => 'Users', 'finder' => 'auth', 'fields' => ['username' => 'login']]]

I've used the auth component inside the plugin appcontroller and also inside the normal application app controller, however what I believe is happening is that it is going in the "normal" application to look for the method, when it was for it to go fetch inside the plugin .

How do I solve this?

Thank you!

**Comment by inoas** [comment]
Without looking at the docs try 'userModel' => 'PluginName.Users' aka plugin dot notation.

For anything else, unless you can isolate it as a bug, please consider using irc, slack, discussion forums, stackoverflow as this is not a support forum.

**Comment by alexsmonte** [comment]
I had forgotten this important detail, it worked!
