### ISSUE TITLE
"Undefined class Response" in IDE - FormAuthenticate::authenticate()

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#10013]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0-beta4
* Platform and Target: PhpStorm 9.0.2

### What you did
Extending the default `Cake\Auth\FormAuthenticate` with a custom `AdminFormAuthenticate`.

The goal is to overwrite the `authenticate()` method as I don't want the password as is, but I need to "pre-hash" the password before using `_findUser` because of how our API works.

### What happened
```
use Cake\Auth\FormAuthenticate;
use Cake\Network\Response;
use Cake\Http\ServerRequest;

class AdminFormAuthenticate extends FormAuthenticate
{
    /**
     * {@inheritDoc}
     */
    public function authenticate(ServerRequest $request, Response $response) {}
}
```

Give me the following message in the IDE:

> Undefined class Response

### What you expected to happen
Not this message, as [FormAuthenticate.php#L66](https://github.com/cakephp/cakephp/blob/3.next/src/Auth/FormAuthenticate.php#L66) states that `Cake\Network\Response` is the object to use.

But https://github.com/cakephp/cakephp/blob/3.next/src/Network/Response.php is deprecated in 3.4.0.

Shouldn't `FormAuthenticate` be using `Cake\Http\Response` instead? Because now PhpStorm won't autocomplete, as it doesn't forward `class_alias` apparently.

**Maybe it will in a newer PhpStorm version, but it's a simple thing to fix I guess.**

**Comment by markstory** [comment]
Yes we _could_ change the type hints, but it will cause existing plugins/implementations to fail because the types are 'different'.

**Comment by JelmerD** [comment]
Will they actually fail, or will they get a notice saying they aren't using the correct class?

Because shouldn't the main app be failing as well then, because it doesn't use the correct class.

*I might have to dig into this matter in order to fully understand how this behaves.*

**Comment by markstory** [comment]
> Will they actually fail, or will they get a notice saying they aren't using the correct class?

It will be an `E_STRICT` warning which will cause phpunit test suites to fail. Historically we've tried to avoid these situations as they make upgrading hard.

**Comment by dereuromark** [comment]
@markstory arent those the Same classes when using class_alias()? We used it in other places, too.

**Comment by markstory** [comment]
Yes and no. The classes resolve to the same class through aliases. But PHP checks the exact class name when emitting strict errors.

**Comment by ADmad** [comment]
Given that the typehint cannot be changed without generation `E_STRICT` error I don't think anything any be done here. IDE users will just have to live with it until next major release.

**Comment by dereuromark** [comment]
One can safely change the doc Block types already if one wants.
