### ISSUE TITLE
Creating events with data objects no longer works in 3.4

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#10027]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0

### What you did

```php
$data = new ArrayObject(['foo' => 'bar']);
$event = new Event('foo', $this, $data);
```

### What happened

Constructor definition has been changed to:
```php
public function __construct($name, $subject = null, array $data = null)
...
```

so there's a type error:
`Argument 3 passed to Cake\\Event\\Event::__construct() must be of the type array or null, object given`

### What you expected to happen

I expect it to work as it used to. There's type casting being done in an `Event` constructor `$this->_data = (array)$data;` so I don't hink there's need for a type hint (yet - at least not before PHP7 is required).

This change breaks https://github.com/josegonzalez/cakephp-version . It's an easy fix, but I think that it may get worse for somebody.

**Comment by dereuromark** [comment]
You are right, the typehint addition of https://github.com/cakephp/cakephp/commit/fbc134356ab534b1cdc0b0ee7b70f1a90a3e665e has to be reverted, and the doc block should be corrected to append `|\ArrayObject`.

**Comment by josegonzalez** [comment]
Don't forget to add tests! :P

Note that in 7.1, they add the `iterable` typehint that handles both of these.

**Comment by robertpustulka** [comment]
@josegonzalez nah, iterable is an "alias" for `array|\Traversable`. We need `array|\ArrayAccess` here.

**Comment by ADmad** [comment]
@robertpustulka Would you mind submitting a fix removing the type hint.

**Comment by robertpustulka** [comment]
PR is open
