### ISSUE TITLE
Add function isLinked in class Class BelongsToMany

### ISSUE THREAD

**Issue by ozee31** [cakephp/cakephp#10022]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.11

### What I wanted to do
I would checked if an entity is linked with an other with BelongsToMany relationship.

It's possible to create a function isLinked in BelongsToMany's class ?

**Comment by markstory** [comment]
> It's possible to create a function isLinked in BelongsToMany's class ?

Yes, how do you see the method being used?

**Comment by ozee31** [comment]
```php
public function isLinked(EntityInterface $sourceEntity, EntityInterface $targetEntity) 
{
    return (bool) $this->_collectJointEntities($sourceEntity, [$targetEntity]);
}
```

**Comment by markstory** [comment]
Is there a reason you can't use the existing eager loding features and check for the target entity in the loaded data?

**Comment by ozee31** [comment]
Yes we could also use `matching`  for test isLinked
