### ISSUE TITLE
Configure::read('App.imageBaseUrl')

### ISSUE THREAD

**Issue by romanjanowczyk** [cakephp/cakephp#10020]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4
* Platform and Target: WIN10

### What you did
In core.php I set up: Configure::write('App.imageBaseUrl', 'http://img.domain.com/img/');

### What happened
When using $this->Html->image('image.jpg',  array('fullBase' => true)) I got url to my main domain http://domain.com/img/

### What you expected to happen
It should be checked if I set up variable App.imageBaseUrl and give me http://img.domain.com/img/image.jpg not http://domain.com/img/image.jpg

**Comment by dereuromark** [comment]
There is an existing test:
```php
		$previousConfig = Configure::read('App.imageBaseUrl');
		Configure::write('App.imageBaseUrl', '//cdn.cakephp.org/img/');
		$result = $this->Html->image('test.gif');
		$this->assertTags($result, array('img' => array('src' => '//cdn.cakephp.org/img/test.gif', 'alt' => '')));
		Configure::write('App.imageBaseUrl', $previousConfig);
```

Maybe it is the fullBase which makes it fail? What happens without fullBase true?

**Comment by romanjanowczyk** [comment]
that's the case if you switch on fullBase than you get main domain not cdn.

**Comment by dereuromark** [comment]
I just tested it:
```php
Configure::write('App.imageBaseUrl', '//cdn.cakephp.org/img/');
$result = $this->Html->image('test.gif', array('fullBase' => true));
// Result: <img src="//cdn.cakephp.org/img/test.gif" alt=""/>
```
It looks all as expected.

**Comment by romanjanowczyk** [comment]
strange

**Comment by dereuromark** [comment]
I tested in on 2.x branch.
