### ISSUE TITLE
Pagination: field names with `order` and `sortWhitelist`

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10028]
I need some clarification for pagination, using models that have associations and a custom query.

Example: I'm paginating posts. Posts belongs to posts categories, belongs to users and have many tags. Posts and users have the `created` field.

Code:

```
$query = $this->Posts->find()->contain([
    'Categories' => function ($q) {
        return $q->select(['id', 'title']);
    },
    'Tags' => function ($q) {
        return $q->order(['tag' => 'ASC']);
    },
    'Users' => function ($q) {
        return $q->select(['id', 'first_name', 'last_name']);
    },
]);

$this->paginate['order'] = ['created' => 'DESC'];
$this->paginate['sortWhitelist'] = ['id', 'title', 'Categories.title', 'Users.first_name', 'priority', 'created'];

$posts = $this->paginate($query);

$this->set(compact('posts'));
```

What happens:
- opening the view, the records are sorted correctly (`created` `DESC`);
- on the first page, I can sort by any field set in `sortWhitelist`;
- the second page **only works** for `Categories.title` and `Users.first_name` fields. Other fields **do not work** because the query string adds the name of the model.

Example. On the first page, sorting by title, this is the url (and it works):
`http://localhost/mirkopagliai/admin?sort=title&direction=asc`  
Clicking on the second page, this is the url (and it doesn't work):
`http://localhost/mirkopagliai/admin?page=2&sort=Posts.title&direction=asc`  
And pagination breaks.

Changing the code (I added the name of the model to the `title` field):
```
$this->paginate['order'] = ['created' => 'DESC'];
$this->paginate['sortWhitelist'] = ['id', 'Posts.title', 'Categories.title', 'Users.first_name', 'priority', 'created'];
```

What happens:
- opening the view, the records are sorted correctly (`created` `DESC`);
- on the first page, **I can't sort** anything;
- the other pages **do not work** under any circumstances.

Changing the code (I added the name of the model to the `created` field, on `order` and `sortWhitelist` options):
```
$this->paginate['order'] = ['Posts.created' => 'DESC'];
$this->paginate['sortWhitelist'] = ['id', 'title', 'Categories.title', 'Users.first_name', 'priority', 'Posts.created'];
```

What happens:
- opening the view, the records are sorted correctly (`created` `DESC`);
- on the first page, I can sort by any field set in `sortWhitelist`;
- the second page **only works** for `Categories.title`, `Users.first_name` and `Posts.created` fields.

Changing the code (I removed `sortWhitelist`):
```
$this->paginate['order'] = ['created' => 'DESC'];
```

What happens:
- opening the view, the records are sorted correctly (`created` `DESC`);
- all `Posts` fields work. The fields of the other models obviously do not work.

**Comment by markstory** [comment]
Have you looked into why the sort fields are being ignored on the second page? I do know that `sotWhitelist` requires an exact match for the fields to be sortable.

**Comment by mirko-pagliai** [comment]
1. With `title` on `sortWhitelist`:
first page (works):
http://localhost/mirkopagliai/admin?sort=title&direction=asc
second page (**doesn't work**):
http://localhost/mirkopagliai/admin?page=2&sort=Posts.title&direction=asc

2. With `Posts.title` on `sortWhitelist`:
first page (**doesn't work**):
http://localhost/mirkopagliai/admin?sort=title&direction=asc
second page (**doesn't work**, it removes all query):
http://localhost/mirkopagliai/admin?page=2
Trying manually (**doesn't work**):
http://localhost/mirkopagliai/admin?page=2&sort=title&direction=asc
Trying manually (**doesn't work** again):
http://localhost/mirkopagliai/admin?page=2&sort=Post.title&direction=asc

**Comment by markstory** [comment]
I meant have you looked at why your sort key is being dropped in the [PaginatorComponent method](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L356-L364). I think you'll need both `title` and `Posts.title` in the whitelist.

**Comment by mirko-pagliai** [comment]
> I meant have you looked at why your sort key is being dropped in the PaginatorComponent method
Ok, today I'll do some thorough test

>  I think you'll need both title and Posts.title in the whitelist.
Yes, I confirm, so it works. But now I am forced to declare 2 times every field in the whitelist.

Question: why the whitelist is essential when using models associated fields?
Is there no way to make it entirely optional? I find it uncomfortable and I do not need.

**Comment by mirko-pagliai** [comment]
Ok, I think that maybe the problem is:

- `$this->Paginator->sort()` creates a url for the `title` field, and this works correctly, because it is in the white list;
- `$this->Paginator->prev()`, `next()` and `number()` add the model name, so they create urls for the `Posts.title` field and it is not in the white list.

So if I am to this address:
`http://localhost/mirkopagliai/admin?sort=title&direction=asc`  
the link generated by `next()` is:
`http://localhost/mirkopagliai/admin?page=2&sort=Posts.title&direction=asc`  
and this breaks the pagination.

**Comment by mirko-pagliai** [comment]
In fact, there is only one way for it to work: add `Posts.title` on the white list and using the model name also with the `sort()` method:

`$this->Paginator->sort('Posts.title');`

**Comment by ADmad** [comment]
The prefixing of model alias to field name when not explicitly asked for sounds wrong and should be fixed. It might be cause due to the addition of multiple pagination feature.

**Comment by mirko-pagliai** [comment]
> The prefixing of model alias to field name when not explicitly asked for sounds wrong and should be fixed

Yes, I agree.

But I also think that there should be the option to not use precisely the whitelist.

Also because I feel that it makes little sense: usually paging always works. If I use associated records, I have to specify all records in the whitelist, including those of the original model.

**Comment by mirko-pagliai** [comment]
This raises two questions for me:

1. as said by @ADmad:
> The prefixing of model alias to field name when not explicitly asked for sounds wrong and should be fixed

In other words, if I use the method:
`$this->Paginator->sort('title');`
And the query string **correctly** contains:
`?sort=title&direction=asc` 
I do not understand why other methods (`number()`, `prev()`, `next()` and so on) generate a query string that contains
`?sort=Posts.title&direction=asc` 

2. for me the whitelist should be optional. The control should be implemented only if the whitelist is specified.  
Or we should find a way to bypass the whitelist, for example:

`$this->paginate['sortWhitelist'] = '*';`

It also seems a little foolish that the whitelist can be specified (optional) if I make the paging no associations, and must be specified (obligatorily) if I do pagination with associations.

For now, a method to bypass the whitelist within the controller (it's bad, but it works):

        if($this->request->query('sort') && empty($this->paginate['sortWhitelist'])) {
            $this->paginate['sortWhitelist'] = [$this->request->query('sort')];
        }

**Comment by markstory** [comment]
> But I also think that there should be the option to not use precisely the whitelist

I disagree with this. Whitelists should be strict. When they are not strict, developers need additional controls to enforce strictness as it is required in some scenarios.

I agree that if possibke the other methods should omit the model alias. Detecting when to add the alias might be tricky but could be part if the metadata the component creates?

**Comment by mirko-pagliai** [comment]
> I disagree with this. Whitelists should be strict. When they are not strict, developers need additional controls to enforce strictness as it is required in some scenarios.

It is one thing not to implement the whitelist. Another thing to allow to use it when necessary.
In my case, for example, in the administration panel, why should I use the whitelist?
Why not allow such a thing?

```
if($this->request->isAdmin()) {
    $this->paginate['sortWhitelist'] = '*';
}
```

**Comment by dereuromark** [comment]
Guys, the main problem is the whitelist idea itself, I think it is a broken design.
What we should use instead, would be a mapping.

So with a mapping it would by default assign all primary model fields to the non aliased form:
```
'PrimaryModel.title' => 'title',
'SecondaryModel.title' => 'SecondaryModel.title', // or sth like 'secondary-model-title'
```
Only "title" without any prefix will ever be used in the frontend to work with the primary model.

We can then completely remove the static whitelisting, and just transform the query strings via this mapping - forward and backward - with ease.
This would be consistent and transparent as to what key does what.

It also allows for more complex use cases that have come up a few times before, e.g. combination of fields: 'prio' then could internally be mapped to several fields like `prio DESC, subprio DESC` etc.
All that is super easy when you use a mapping that allows for automated and manual mapping.

**Comment by markstory** [comment]
> Guys, the main problem is the whitelist idea itself, I think it is a broken design.

If whitelists are broken, why are you proposing another whitelist? Or is it more that the current implementation is the problem?

Your proposed mapping is flawed in that multiple columns could resolve to the same sort 'key' and finding the column for a given sort key is an O(N) operation. Wouldn't it be simpler/better to have a map of sort 'keys' and the columns they are for?

```php
$sortMap = [
  // Map to a single field both directions allow
  'title' => 'Articles.title',
  // Multiple fields both directions allowed
  'multi' => ['Articles.title', 'Articles.published'],
  // Complex fields with baked in sort directions. URL would only support 'asc'
  'thinger' => ['Articles.title' => 'desc, 'Articles.published' => 'asc']
]
```

The above implementation makes look ups easier, and allows sort keys to map to multiple concrete fields, and provides a whitelist which can be made safe as well.

**Comment by dereuromark** [comment]
@markstory Same idea but better and more concrete implementation. Thats What I meant.

**Comment by markstory** [comment]
I think we could possibly implement an improved sort mapping adjacent to the existing `sortWhitelist` feature.

**Comment by bravo-kernel** [comment]
Sorting on multiple fields is required by [JSON API sorting]( http://jsonapi.org/format/#fetching-sorting) so this feature would be most welcome. Crud issue #522.

**Comment by ADmad** [comment]
Fixed in #11741.

**Comment by dereuromark** [comment]
Almost - maybe the part about what I wrote about the config map could be extracted into its own 4.x ticket at some point. To allow more complex searches without the typical issues currently occurring then.

**Comment by ADmad** [comment]
Yup but it would be better to discuss the map feature in a new issue/PR.
