### ISSUE TITLE
syntax error in php 5.5.9  ( unexpected '.', expecting '&' or variable )

### ISSUE THREAD

**Issue by GaneshKandu** [cakephp/cakephp#10035]
# Getting  Syntax Error on PHP 5.5.9
**Parse error**: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in **vendor/cakephp/cakephp/src/I18n/functions.php** on line **26**

* CakePHP Version: 3.3.12  9e41f11
* Platform and Target: Apache/2.2.31, PHP 5.5.9

### What happened
Getting  Syntax Error on PHP 5.5.9
**Parse error**: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in **vendor/cakephp/cakephp/src/I18n/functions.php** on line **26**

Cakephp using Variadic functions Which is introduced in PHP 5.6 and Not Supported in PHP 5.5
[http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list)

**Comment by dakota** [comment]
That file in 3.3.12 (https://github.com/cakephp/cakephp/blob/3.3.12/src/I18n/functions.php#L26) does not use varidacs. In the 3.4 beta it does, check that you have not installed 3.4 be accident.

**Comment by GaneshKandu** [comment]
i have Downloaded from Github [https://github.com/cakephp/cakephp/releases/download/3.3.12/cakephp-3-3-12.zip](https://github.com/cakephp/cakephp/releases/download/3.3.12/cakephp-3-3-12.zip)

![332](https://cloud.githubusercontent.com/assets/12833130/21953158/b6d3d97e-da55-11e6-8fe1-876fc0825e61.png)

I have Confirmed its 3.3.12

**Comment by GaneshKandu** [comment]
Tested on 5.6 also but Getting Warnings

[error-5.6.txt](https://github.com/cakephp/cakephp/files/705805/error-5.6.txt)

**Comment by josegonzalez** [comment]
@markstory it looks like the 3.3.12 release is actually `3.4.0-beta4`. I'm going to delete the zip for now and let you fix it in the morning (I would but am not sure what the process is).

**Comment by GaneshKandu** [comment]
What is the PHP Required version of next Stable version

**Comment by ADmad** [comment]
CakePHP 3.4 requires PHP 5.6+

**Comment by ADmad** [comment]
I reopened the issue since the incorrect version being packaged is a valid problem.

**Comment by josegonzalez** [comment]
I have updated the `cakephp-3-3-12.zip` attached to our release [here](https://github.com/cakephp/cakephp/releases/tag/3.3.12) and verified it contains the correct code. Sorry about that!

**Comment by GaneshKandu** [comment]
**Thanks a Lot Working Fine now**

**Comment by markstory** [comment]
@josegonzalez Not sure how that happened. The release script is a single make command. Perhaps the constraints in cakephp/app are off?

**Comment by markstory** [comment]
```
Installing app dependencies with composer
# Install deps with composer
cd build/app && php ../../composer.phar install
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "../../composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Set Folder Permissions ? (Default to Y) [Y,n]? y
No Security.salt placeholder to replace.
# Copy the current cakephp libs up so we don't have to wait
# for packagist to refresh.
rm -rf build/app/vendor/cakephp/cakephp
cp -r build/cakephp build/app/vendor/cakephp/cakephp
# Make a zipball of all the files that are not in .git dirs
# Including .git will make zip balls huge, and the zipball is
# intended for quick start non-git, non-cli users
Building zipball for 3.3.12
cd build/app && find . -not -path '*.git*' | zip ../../dist/cakephp-3-3-12.zip -@
```
is the build output from the 3.3.12 release I did last night.
