### ISSUE TITLE
Error displaying default home page - New instllation

### ISSUE THREAD

**Issue by bvictor** [cakephp/cakephp#10030]
I have installed the latest cakephp 3.3 using composer on windows 7/Php 7.0.8. the installation is successful however when i try to open the default home page i get the following error:

Fatal error: Uncaught Error: Call to undefined method Cake\Network\Response::getBody() in C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\ToolbarService.php:213 Stack trace: #0 C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\Routing\Filter\DebugBarFilter.php(144): DebugKit\ToolbarService->injectScripts(Object(DebugKit\Model\Entity\Request), Object(Cake\Network\Response)) #1 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventManager.php(426): DebugKit\Routing\Filter\DebugBarFilter->afterDispatch(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response)) #2 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventManager.php(391): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event)) #3 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event)) #4 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(383): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.afte...', Array in C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\ToolbarService.php on line 213

Fatal error: Uncaught Error: Call to undefined method Cake\Network\Response::getBody() in C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\ToolbarService.php:213 Stack trace: #0 C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\Routing\Filter\DebugBarFilter.php(144): DebugKit\ToolbarService->injectScripts(Object(DebugKit\Model\Entity\Request), Object(Cake\Network\Response)) #1 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventManager.php(426): DebugKit\Routing\Filter\DebugBarFilter->afterDispatch(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response)) #2 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventManager.php(391): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event)) #3 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event)) #4 C:\xampp\htdocs\wp\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(383): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.afte...', Array in C:\xampp\htdocs\wp\vendor\cakephp\debug_kit\src\ToolbarService.php on line 213

What could be the issus?

**Comment by antograssiot** [comment]
duplicated of cakephp/debug_kit#471
You can either disable DebugKit or pin to an older version while it is fixed.
