### ISSUE TITLE
[x] 2.9.4 Xml::build() fails to load large XML file

### ISSUE THREAD

**Issue by underhiller** [cakephp/cakephp#10031]
* CakePHP Version: 2.9.4
* Platform and Target: Ubuntu 16.04.1 LTS Server, PHP 7.0.13, libxml 2.9.3

### What you did
I've tried to load large (about 30MB) XML file by using Xml::build($large_file_contents); command in Console script. There is no memory_limit for CLI.

### What happened
Cake throwed XmlException: "Xml cannot be read."

### What you expected to happen
Read the file successfully...

### "quickfix" to get it running in my case.
file and line : /lib/Cake/Utility/Xml.php:140

changed from:
$xml = new SimpleXMLElement($input, LIBXML_NOCDATA);
changed to: 
$xml = new SimpleXMLElement($input, LIBXML_PARSEHUGE|LIBXML_NOCDATA);

**Comment by markstory** [comment]
Pull request up to add an option for enabling huge XML support.
