### ISSUE TITLE
Test Fixtures - Datetime Format in Postgres & Default Value

### ISSUE THREAD

**Issue by ajquick** [cakephp/cakephp#10040]
This is a bug.

- CakePHP Version: 3.3.10
- Platform and Target: Travis-CI (PHP 5.5 / 5.6 / 7 / 7.1 / HHVM)
  - MySQL 5.6
  - SQLite
  - MariaDB 10.1
  - Postgres 9.4

### Setup

I have a fixture that calls for the following (among other) databases tables to be created:

```php
public $fields = [
        'created_at' => ['type' => 'datetime', 'default' => 'CURRENT_TIMESTAMP', 'null' => false],
        'updated_at' => ['type' => 'datetime', 'default' => 'CURRENT_TIMESTAMP', 'null' => false]
];
```

### Result

**MySQL 5.6:** Errors out as expected. The command would not be valid until MySQL 5.7.
**SQLite:** Works without problems.
**MariaDB 10.1:** Works perfectly. (MariaDB is a more advanced MySQL like code base like MySQL 5.7)
**Postgres 9.4:** Failing.'Datetime' is not a valid Postgres field type. Database Schema converts to Timestamp, 'CURRENT' depreciated in version 7.2.

https://www.postgresql.org/docs/7.2/static/datatype-datetime.html#AEN3257

### Postgres Error

```
PHP Warning:  Fixture creation for "table" failed "SQLSTATE[0A000]: Feature not supported: 7 ERROR:  date/time value "current" is no longer supported" 
```

### Expected Behavior

I believe when faced with 'CURRENT' or 'CURRENT_TIMESTAMP', Postgres will need to convert to 'now'. Or something else entirely is happening that I cannot see for certain.

**Comment by ajquick** [comment]
Highlighting relevant code from [Cake\Database\Schema\PostgresSchema](https://github.com/cakephp/cakephp/blob/9e41f111f68ef646bcf8b03b9b4885598e4d9de3/src/Database/Schema/PostgresSchema.php).

```php
        if (isset($data['null']) && $data['null'] === true && $data['type'] === 'timestamp') {
            $out .= ' DEFAULT NULL';
            unset($data['default']);
        }
        if (isset($data['default']) && $data['type'] !== 'timestamp') {
            $defaultValue = $data['default'];
            if ($data['type'] === 'boolean') {
                $defaultValue = (bool)$defaultValue;
            }
            $out .= ' DEFAULT ' . $this->_driver->schemaValue($defaultValue);
        }
```

Basically, there is no condition where $data['type'] === 'timestamp' and $data['null'] === false. And in any case the $data['default'] is always ignored when used with a Timestamp. I'm not really sure where the  _ERROR:  date/time value "current" is no longer supported _ came from. Perhaps that is a default response when no default is defined, and no 'NULL' has been set.

I will temporarily fix my code by adding a NULL true condition, but I would like to make sure that Postgres has the correct 'CURRENT_TIMESTAMP' behavior by default. I know very little about Postgres at this point, but I believe adding another condition would be easy. If I can come up with a solution, I will initiate a pull request.

**Comment by ajquick** [comment]
Upon further review, datetime is not handled correctly by the PostgresSchema. I took a look at the MySQL and ServerSQL schema (which also does not support datetime), and it appears a few bits of code were overlooked in relation to datetime in Postgres.

I will be working on a patch shortly.

**Comment by markstory** [comment]
Closing as a pull request is open now.
