### ISSUE TITLE
Mailer doesn't reset after Transport exception

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#10059]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11

I haven't checked this yet but by looking at the code it seems obvious that an exception thrown by the Transport in the ```send``` method will prevent the reset of the Mailer.

https://github.com/cakephp/cakephp/blob/master/src/Mailer/Mailer.php#L250

I think the reset call should be done inside a ```finally``` block, like this:

```php
try {
    $result = $this->_email->send();
} finally {
    $this->reset();
}
```

I plan on using the Mailer on a CLI task that sends email batches and I want it to continue sending emails even after a transport error on some of them. I guess that using the same Mailer after a Transport exception would use any parameter set by the previous attempt that is not overridden later.

**Comment by markstory** [comment]
Would you be willing to put together a pull request with the change you have in mind?

**Comment by berarma** [comment]
No problem.

**Comment by berarma** [comment]
PR up. I've decided to wrap all the method inside the try block. I don't know how this could break other peoples code. Some guidance on other ways to reset the Mailer other than creating a new instance would be welcome.

**Comment by markstory** [comment]
Closing as a pull request is up now.
