### ISSUE TITLE
Router::url in 3.4.0-beta4

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10057]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0-beta4
* Platform and Target: php5.6+apache2.4
### What you did
```
    $routes->connect('/users/login', ['controller'=>'Users', 'action'=>'login'], [
        '_name'=>'supplierUser.login',
        '_host' => 'supplier.domain.com'
    ]);

    debug(Router::url(['_name'=>'supplierUser.login'], true));
```
### What happened
print:
http://www.domain.com/users/login

### What you expected to happen
print:
http://supplier.domain.com/users/login

You know, this route require host "supplier.domain.com", when generate full url, required host should replace current host

**Comment by markstory** [comment]
I totally forgot about the URL generation side, I'll get that fixed.

**Comment by markstory** [comment]
How would this work if the `_host` option contains wildcards? For example the route:

```php
        $route = new Route(
            '/fallback',
            ['controller' => 'Articles', 'action' => 'index'],
            ['_host' => '*.example.com']
        );
```

**Comment by markstory** [comment]
I've put up a pull request with an implementation that I think makes sense. Could you take a look @slince

**Comment by slince** [comment]
Ok, I have a solution for the problem with wildcards
```
//1. provide requirement argument, when generate url
$route = new Route(
    '/fallback',
    ['controller' => 'Articles', 'action' => 'index'],
    [
        '_host' => ':subdomain.example.com',
        '_name' => 'article.index'
        'subdomain' => '*+',  //add a regex requirement
    ]
);

Router::url([
    '_name'=>'article.index',
    'subdomain' => 'foo' //provide argument for subdomain
], true);

//or give default 

$route = new Route(
    '/fallback',
    ['controller' => 'Articles', 'action' => 'index', 'subdomain'=>'foo'], //add a default argument
    [
        '_host' => ':subdomain.example.com',
        '_name' => 'article.index'
        'subdomain' => '*+',  //add a regex requirement
    ]
);

Router::url([
    '_name'=>'article.index',
    // 'subdomain' => 'foo' // Optional， if provide， replace default
], true);
```

 ps: I think Route argument  “options ” are ambiguous, should be separated into requirements and options
```
$route = new Route(
    '/articles/:id', //path
    ['controller' => 'Articles', 'action' => 'show', id => 1, subdomain=>'bar'],  //defaults
    [id => '\d+', 'subdomain' => '*+']  //requirements (optional)
    ['_host' => ':subdomain.example.com', '_name' => 'article.index', 'pass'=>['id',  'subdomain']] //options, (optional)
);
```
I think options "pass" can be ommited, it should be automatically injected into the action if action have same name variable.

**Comment by slince** [comment]
ok, i will try

**Comment by markstory** [comment]
> I think options "pass" can be ommited, it should be automatically injected into the action if action have same name variable.

I agree this would be nice, but I worry about breaking backwards compatibility and the overhead that reflection/pattern matching arguments will have.

I solved the wildcard domain issue a bit differently than you did. Instead of adding a `subdomain` key, routes with wildcard hosts, will require the `_host` option to be set to correctly match the host based route.
