### ISSUE TITLE
Threaded find, with formatResults afterwards fails because of wrong object type

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#10064]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0-RC2
* Platform and Target: Vagrant bento/debian-8.6 and PHP7.1

### What you did
I tried to format my threaded resultset as I need to contain some additional data for every single child.

```php
$query = $this->Events->find('threaded');
$query->formatResults(function (ResultSetInterface $results) {
    return $results;
});
dd($query->toArray());
```

### What happened
Output:

```json
{
  "message": "Argument 1 passed to PlanningModule\\Controller\\EventsController::PlanningModule\\Controller\\{closure}() must implement interface Cake\\Datasource\\ResultSetInterface, instance of Cake\\Collection\\Iterator\\ReplaceIterator given, called in /var/www/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php on line 500",
  "url": "/planning/events/1/tree",
  "code": 500
}
```

Summary:

[QueryTrait.php#L500](https://github.com/cakephp/cakephp/blob/3.4.0-beta4/src/Datasource/QueryTrait.php#L500) expects `Cake\Datasource\ResultSetInterface` but for some reason `Cake\Collection\Iterator\ReplaceIterator ` is given.

### What you expected to happen

I expected it to give me the ability to loop over all the data.

First I thought I had the wrong object selected by myself, but that is not the case, as the code below works (only changed the finder):

```php
$query = $this->Events->find('all');
$query->formatResults(function (ResultSetInterface $results) {
    return $results;
});
dd($query->toArray());
```

Ps. A normal threaded find works just fine. So it really has something to do with the formatResults part.

**Comment by JelmerD** [comment]
Edit: original issue on 3.4.0-beta4, but the bug still exists on 3.4.0-RC2

**Comment by markstory** [comment]
I suspect this issue exists in 3.3 as well. The source is likely [this nest() operation](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1126-L1128) which does the nesting of the threaded results. Have you tried removing the typehint in your closure?

**Comment by JelmerD** [comment]
@markstory 

```php
$query = $this->Events->find('threaded');
$query->formatResults(function ($results) {
    return $results;
});
dd($query->toArray());
```

Works as it should. Why I didn't try that... I see you marked it for the 3.4.0 milestone, I wish I knew how to fix it myself so I could send a PR, but I have no idea. Tnx :)

**Comment by ADmad** [comment]
There is nothing to fix, you used the wrong type hint in your closure. Once the nesting operation is performed the result is no longer instance of `ResultSetInterface`.
