### ISSUE TITLE
2.x: Built-in server displays blank page for base path with query string parameters (/?page=2)

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#10067]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 7ba160bf95abdc417e31abbbb526d1c272d748e4

### What you did

Start built-in server:
```Console/cake server -p 8888```

Point browser to: http://localhost:8888/?page=2

### What happened
Blank page.

### What you expected to happen
The same page I would get by browsing to: http://localhost:8888

**Comment by markstory** [comment]
Closing as there is a pull request up. I'll verify the fix tonight and port it to 3.x as well.

**Comment by ravage84** [comment]
@markstory could you port this fix to 3.x? I don't see a reference in this PR.

**Comment by markstory** [comment]
@ravage84 I didn't need to. 3.x already worked.
