### ISSUE TITLE
BeforeSave inside the Behavoir tree does not seem to be working

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/cakephp#10061]
I confess that I researched a lot before coming here and not be a mistake but misuse.

So I have two controllers
1. Categorias
2. Ccustos (this one has a Behavoir Tree)

Within the Categorias controller I have:

```
$ DataPlano = ['parent_id' => 1, 'name' => 'Pharmacy'];
$ Ccustos = $ this-> Categorias-> Ccustos-> criarPlano ($ dataPlano);
```

Within CcustosTable I have

```
Public function criarPlano ($data)
{
         $ccustosTable = TableRegistry :: get ('Ccustos');
         $custos = $ ccustosTable-> newEntity ();

         $ CcustosEntity = $ ccustosTable-> patchEntity ($custos, $data);

         Return $ccustosTable-> save ($ CcustosEntity);
}
```

When saving with criarPlano it not the fields lft and rght, I realized that it may be that it is not running beforeSave inside TreeBehavoir.php however I tried to configure my Xdebug to track it but it did not work :(

**Comment by berarma** [comment]
This is confusing because:
- A controller can't have a Behavior.
- You're calling ```save``` on the Costs model from your Ccustos model. It doesn't make much sense the way is done.
- I don't know where the TreeBehavior would be involved. Which model?

I think you may want to do some more reading, the official book has lots of examples, and ask questions on IRC.

**Comment by alexsmonte** [comment]
It was a typo so I was confused.

Ccustos is who has the behavoir I'm just calling the function that is inside the CcustosTable.php and saves and works.

But it does not generate the lft and rgth fields that would be executed inside the BeforeSave if I was running inside the controller Ccustos, but I'm not, that function is being called inside CategoriasController.php

**Comment by markstory** [comment]
Right now it is difficult for me to see how I could reproduce the issue you're having. Is there a way you could put together a gist of the relevant Table class code and save code that you're having issues with?

**Comment by alexsmonte** [comment]
I'll generate an example here and post the files.

**Comment by alexsmonte** [comment]
I finally got: D

I installed a version of the cake and created the plugins.

I noticed that it tries to get something in the main application ie in the main categories and because it does not exist it does not create, how did I find out? I left a model categoriesTable.php within src / Model / Table and it worked but it can not fetch it inside the plugin.

[https://github.com/alexsmonte/test](https://github.com/alexsmonte/test/)

**Comment by markstory** [comment]
If you are getting generated table instances instead of the ones you defined, your associations are likely defined wrong. In ` Btest\Controller\TestsController` you should try `debug($this->Tests->Categories->getTarget())` and ensure that you are getting the correct class name.

**Comment by alexsmonte** [comment]
I believe that there is no namespace error, as it saves normal it only does not execute beforeSave.

debug($this->Tests->Categories->getTarget());
Unknown method "getTarget" 

debug($this->Tests);
```
object(Btest\Model\Table\TestsTable) {
	'registryAlias' => 'Btest.Tests',
	'table' => 'tests',
	'alias' => 'Tests',
	'entityClass' => 'Btest\Model\Entity\Test',
	'associations' => [
		(int) 0 => 'categories'
	],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'
}

```

debug($this->Tests->Categories);
```

object(Cake\ORM\Association\BelongsTo) {
	[protected] _validStrategies => [
		(int) 0 => 'join',
		(int) 1 => 'select'
	]
	[protected] _name => 'Categories'
	[protected] _className => 'Atest.Categories'
	[protected] _bindingKey => null
	[protected] _foreignKey => 'category_id'
	[protected] _conditions => []
	[protected] _dependent => false
	[protected] _cascadeCallbacks => false
	[protected] _sourceTable => object(Btest\Model\Table\TestsTable) {

		'registryAlias' => 'Btest.Tests',
		'table' => 'tests',
		'alias' => 'Tests',
		'entityClass' => 'Btest\Model\Entity\Test',
		'associations' => [
			(int) 0 => 'categories'
		],
		'behaviors' => [],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	}
	[protected] _targetTable => null
	[protected] _joinType => 'INNER'
	[protected] _propertyName => null
	[protected] _strategy => 'join'
	[protected] _finder => 'all'
	[protected] _tableLocator => null
}
```

**Comment by markstory** [comment]
Sorry, `getTarget()` should be `target()`. I looking at the 3.4.0 code when I replied. The debug you have in your last comment doesn't show the `Categories` table, which is where the problem might be hiding.

**Comment by alexsmonte** [comment]
debug($this->Tests->Categories->target());

```
object(Atest\Model\Table\CategoriesTable) {
	'registryAlias' => 'Atest.Categories',
	'table' => 'categories',
	'alias' => 'Categories',
	'entityClass' => 'Atest\Model\Entity\Category',
	'associations' => [
		(int) 0 => 'parentcategories',
		(int) 1 => 'childcategories',
		(int) 2 => 'tests'
	],
	'behaviors' => [
		(int) 0 => 'Tree'
	],
	'defaultConnection' => 'default',
	'connectionName' => 'default'
}
```

**Comment by robertpustulka** [comment]
@alexsmonte 

[Here](https://github.com/alexsmonte/test/blob/master/plugins/Atest/src/Model/Table/CategoriesTable.php) you are getting a new `CategoriesTable` instance (notice no plugin dot notation) while inside your table scope.

Why don't you call methods on `$this`?

```php
    public function criarPlano($data)
    {
        $entity =   $this->newEntity($data);
        return $this->save($entity);
    }
```

**Comment by alexsmonte** [comment]
@robertpustulka 

It worked!

What is the explanation for this?

**Comment by markstory** [comment]
You asked the ORM to give you a Categories table mapper from the app. Since one didn't exist, the ORM generated a class for you, which does not have the TreeBehavior attached.
