### ISSUE TITLE
ability to overidden controller Or add Router::controller()

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10078]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
ability to overidden controller Or add Router::controller()

### What happened

`You cannot define routes that conflict with the scope`

### What you expected to happen
ability to overidden controller
```

Router::scope('/',['controller' => 'Pages'], function (RouteBuilder $routes) {
    $routes->connect('/1', [ 'action' => 'action1']);
    $routes->connect('/2', [ 'action' => 'action2']);
    $routes->connect('/3', ['controller' => 'Other', 'action' => 'action1']);
    $routes->connect('/4', ['controller' => 'Other', 'action' => 'action2']);
    $routes->connect('/5', ['controller' => 'Other', 'action' => 'action3']);
});
```
or add Router::controller()
```
Router::scope('/',['controller' => 'Pages'], function (RouteBuilder $routes) {
    $routes->connect('/1', [ 'action' => 'action1']);
    $routes->connect('/2', [ 'action' => 'action2']);
       $routes->controller('Other', function ($routes) {
             $routes->connect('/3', [ 'action' => 'action1']);
             $routes->connect('/4', ['action' => 'action2']);
             $routes->connect('/5', ['action' => 'action3']);
      });
});
```
instead of
```
Router::scope('/',['controller' => 'Pages'], function (RouteBuilder $routes) {
    $routes->connect('/1', [ 'action' => 'action1']);
    $routes->connect('/2', [ 'action' => 'action2']);
       $routes->scope('/',['controller' => 'Other'], function ($routes) {
             $routes->connect('/3', ['action' => 'action1']);
             $routes->connect('/4', [ 'action' => 'action2']);
             $routes->connect('/5', ['action' => 'action3']);
      });
});
```

I don,t understand the reason of this exceptions https://github.com/cakephp/cakephp/pull/3825/commits/41a97c2165871bfcbc279ae195859fdc54e5fabc

**Comment by jippi** [comment]
I guess its `In addition it will defeat optimizations for reverse routing.` :)

**Comment by markstory** [comment]
I'm not entirely sure replacing defaults will defeat the optimizations now. That may have been true back then, but I'm not sure its true anymore. The reverse routing maps are generated after the route is constructed and only reflect the defaults in the route object. 

While I still generally agree with my previous comment on conflicting parameters being a mistake they might not be as well.

Instead of using nested scopes you could do two adjacent scopes

```php
Router::scope('/',['controller' => 'Pages'], function (RouteBuilder $routes) {
    $routes->connect('/1', [ 'action' => 'action1']);
    $routes->connect('/2', [ 'action' => 'action2']);
});

Router::scope('/', ['controller' => 'Other'], function ($routes) {
    $routes->connect('/3', ['action' => 'action1']);
    $routes->connect('/4', ['action' => 'action2']);
    $routes->connect('/5', ['action' => 'action3']);
});
```

Depending on the number of actions you're connecting you could end up saving typing work :smile:

**Comment by saeideng** [comment]
can we implement controller() alias ? instead of using nested scope('/',['controller'=>name]) ?
we have not always nested '/' name , above samples is just sample :smile:

**Comment by saeideng** [comment]
gor example scope('page',.....use default pages controller)
And use some action use this controller
but some of that needs to use another controller but within this scope

**Comment by markstory** [comment]
>  can we implement controller() alias ? instead of using nested scope('/',['controller'=>name]) ?

I'm hesitant to add more scope builders until I understand the use-cases better.

**Comment by saeideng** [comment]
I close it  because this can be makes confuse .
