### ISSUE TITLE
Creating Mailers without needing a trait

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#10071]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

I think it's a PITA having to use the ```MailAwareTrait``` every time I want to create a ```Mailer``` in a different class in my code. I think there should be a static method in the ```Mailer``` class that creates a ```Mailer``` instance.

**Comment by lorenzo** [comment]
Why is adding a single line a PITA?

**Comment by berarma** [comment]
Because it's double the lines that are needed.

**Comment by berarma** [comment]
Solved by directly calling the Mailer constructor.
