### ISSUE TITLE
CounterCache behavior and capitalize letter

### ISSUE THREAD

**Issue by Airmime** [cakephp/cakephp#10076]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.6
* Platform and Target: Apache, MySQL

### What you did
I have an issue when i use the CounterCache behavior. The problem is on the name of the table, who has the first letter in capitalize :
`
$this->addBehavior('CounterCache', [
'Websites' => [
                'nb_unread' => [
                    'conditions' => ['Posts.reading' => 0]
                ]
            ]
        ]);
`

### What happened
If i remove the capitalize letter, this Controller send me an error who say "Unknown column 'posts.reading'" :

`public function reload(){

        /* LOADING : POST MODELS */
        $this->loadModel('Posts');

        /* DATA : WEBSITES */
        $websites = $this->Websites->find('all', [
            'conditions' => array('Websites.active' => 1)
        ]);

        /* BROWSE WEBSITE/RSS FEEDS ASSOCIATE */
        foreach($websites as $website){

            // INIT : BREAK VARIABLE
            $i = 0;

            try{
                /* NEW : HTTP CLIENT */
                try{
                    $http = new Client();
                    $response = $http->get($website->rssfeed);

                    /* BUILD : RSS FEEDS */
                    $xml = Xml::build($response->body());
                }catch (Exception $e){
                    echo $e;
                }

                echo "$website->title OK <br/>";

                /* BROWSE RSS FEED */
                foreach ($xml->channel->item as $item) {

                    /* DATE : FORMAT DATE */
                    try {
                        $date = date('Y-m-d H:i:s', strtotime($item->pubDate));
                        $less_one_month = mktime(0, 0, 0, date("m") - 12, date("d"), date("Y"));
                        if (strtotime($date) > strtotime(date('Y-m-d H:i:s')) || strtotime($date) < $less_one_month) {
                            $date = date('Y-m-d H:i:s');
                        }
                    } catch (Exception $e) {
                        $date = date('Y-m-d H:i:s');
                    }

                    /* PICTURE : PICTURE DATE */
                    try {
                        ini_set('max_execution_time', 300);
                        set_time_limit(0);

                        if (isset($item->enclosure['url'])) {
                            try {
                                if (exif_imagetype($item->enclosure['url']) == IMAGETYPE_JPEG || exif_imagetype($item->enclosure['url']) == IMAGETYPE_PNG || exif_imagetype($item->enclosure['url']) == IMAGETYPE_GIF) {

                                    $width = getimagesize($item->enclosure['url']);
                                    if ($width[0] >= 150) {

                                        $picture = $item->enclosure['url'];
                                    } else {
                                        $picture = null;
                                    }

                                } else {
                                    $picture = null;
                                }
                            } catch (Exception $e) {
                                echo $e;
                            }
                        } else {
                            $picture = null;
                        }
                    } catch (Exception $e) {
                        $picture = null;
                    }

                    /* DATA : INSERT POST */
                    $query = $this->Posts->find('all', array('conditions' => array('Posts.uuid' => md5(substr('' . $website->id . date('y') . '' . $item->link . '', 0, 127)))));
                    $counter = $query->count();

                    if ($counter == 0) {
                        $articlesTable = TableRegistry::get('posts');
                        $article = $articlesTable->newEntity();

                        $article->title = strip_tags($item->title);
                        $article->url = $item->link;
                        $article->created = $date;
                        $article->uuid = md5(substr('' . $website->id . date('y') . '' . $item->link . '', 0, 127));
                        $article->text = strip_tags($item->description);
                        $article->picture = $picture;
                        $article->websites_id = $website->id;

                        $articlesTable->save($article);
                    }

                    /* STOP : BREAK LOOP */
                    if($i>4) break;
                    $i++;
                }
            }catch (\Exception $e){
                echo $e;
                continue;
            }
        }
    }`

And, if i keep the capitalize letter, it's an other action in ajax who have an issue : "Unknown column 'posts.reading'".

`public function read(){

        /* LOADING : OTHERS MODELS */
        $this->loadModel('Websites');
        $this->loadModel('Categories');

        /* AJAX : RECEIPT */
        if($this->request->is('ajax') && $this->request->is('post') && $this->request->data['all']=='all')
        {
            /* DATA : SET ALL UNREAD POST TO 1 */
            $this->Posts->updateAll(
                array('Posts.reading' => 1)
            );

            /* DATA : SET ALL UNREAD COUNTER WEBSITE POST TO 0 */
            $this->Websites->updateAll(
                array('Websites.nb_unread' => 0)
            );
        }
        elseif($this->request->is('ajax') && $this->request->is('post') && $this->request->data['id'] != null){

            /* INIT : ID FOR REQUEST */
            $id = $this->request->data['id'];

            /* DATA : FIND THE POST WITH ID */
            $postsTable = TableRegistry::get('Posts');
            $post = $postsTable->get($id);

            /* DATA : CHANGE VALUE */
            $post->reading = 1;

            /* DATA : DONE */
            $postsTable->save($post);
        }elseif($this->request->is('ajax') && $this->request->is('post') && $this->request->data['websites'] != null){

            /* DATA : SET ALL UNREAD POST TO 1 */
            $this->Posts->updateAll(
                array('Posts.reading' => 1),
                array('Posts.websites_id' => $this->request->data['websites'])
            );

            /* DATA : SET ALL UNREAD COUNTER WEBSITE POST TO 0 */
            $this->Websites->updateAll(
                array('Websites.nb_unread' => 0),
                array('Websites.id' => $this->request->data['websites'])
            );

        }elseif($this->request->is('ajax') && $this->request->is('post') && $this->request->data['category'] != null){

            /* DATA : POSTS */
            $posts = $this->Posts->find('all', [
                    'contain' => 'Websites',
                    'conditions' => [
                        'Websites.categories_id' => $this->request->data['category'],
                        'Posts.reading' => 0],
                    'order' => array('Posts.created' => 'desc')]
            );

            $postsTable = TableRegistry::get('Posts');

            /* DATA : SET UNREAD POST TO 1 */
            foreach($posts as $po){

                $po = $postsTable->get($po->id);
                $po->reading = 1;

                /* DATA : DONE */
                $postsTable->save($po);

                /* DATA : SET ALL UNREAD COUNTER WEBSITE POST TO 0 */
                $this->Websites->updateAll(
                    array('Websites.nb_unread' => 0),
                    array('Websites.id' => $po->websites_id)
                );
            }

        }else{
            die;
            // TODO : EXCEPTION
        }

        $this->autoRender = false;
    }`

You can see all sources here : https://github.com/Airmime/ReaDAT

Thanks.

**Comment by markstory** [comment]
Why do you want to remove the capital letter in the alias? It sounds like your database has case-sensitive identifiers enabled and you need to have the alias correctly cased.

**Comment by Airmime** [comment]
I want to remove the capital letter in the alias because without, my CounterCache works. And with i have this issue : 

> Unknown column 'Posts.reading'

**Comment by markstory** [comment]
Have you tried `'reading' => 0` as your condition? It sounds like you might be missing a join when the count() query is created, as the `find()` operation should set aliases. If you cannot get the correct count() query generated through `conditions` you might want to consider using a [custom finder](https://book.cakephp.org/3.0/en/orm/behaviors/counter-cache.html#advanced-usage).

**Comment by Airmime** [comment]
That's works ! Thanks @markstory !
