### ISSUE TITLE
IdentifierExpression should not be internal.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10085]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12
* Platform and Target: Apache2, MySQL 5.7, PHP 7.1

### What you did

You have to use `IdentifierExpression` object in custom expressions if you're referencing a column name.

```
$query->newExpr()->lt('counter', new IdentifierExpression('max_value'))
```

### What happened

`IdentifierExpression` gets IDE warning of invalid usage because it's marked as an `@internal` class to CakePHP.

### What you expected to happen

Can we remove this phpdoc annotation?

**Comment by markstory** [comment]
Would having a method to build the correct identifier object be preferrable? Something like ``$query->newIdentifier('max_value')` or `$query->newExpr()->newIdentifier('max_value')` work?

**Comment by thinkingmedia** [comment]
@markstory that's a great idea. Maybe just call it `identifier(..)`

**Comment by ndm2** [comment]
I'm wondering what the actual intention is to hide expression package classes? I'm using them a lot, mostly `IdentifierExpression`, `TupleComparison`, and `FieldTrait`/`FieldInterface`.

**Comment by markstory** [comment]
@ndm Internal classes have no backwards compatibility promised on them. We use them as a way to limit the scope of the 'public' API we offer, and to reserve the right to change potentially unstable features.

**Comment by thinkingmedia** [comment]
PR is up now.
