### ISSUE TITLE
Use of __('text {0}', $value)

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10087]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12
* Platform and Target: PHP 7.1

### What you did
I used 
echo __('text {0}', $value), $value = null (as reported in debug_kit)

### What happened
I got "text {0}" printed

### What you expected to happen
To get "text " printed

**Comment by ADmad** [comment]
You have to type case `$value` to string when calling `__()`. Given that the default value of second argument of `__()` is null there's no way to differentiate between no argument passed versus argument with null value.

**Comment by dereuromark** [comment]
Well, there would be a way to determin that, right? The func_get_args count.

**Comment by ADmad** [comment]
Another way is using array for second argument.

**Comment by dereuromark** [comment]
Yes, both might be applicable as BC way. We should investigate that IMO.

**Comment by siran** [comment]
I think that also, if {0} is part of $text, it should at least not be returned if func_get_args count > 0

**Comment by ADmad** [comment]
When 2 arguments are passed the 2nd already gets [typecast to array](https://github.com/cakephp/cakephp/blob/master/src/I18n/functions.php#L32), so the problem isn't with `__()` function but it seems translators don't handle `null`.

**Comment by dereuromark** [comment]
Can we foreach cast all `null` internally here to fix this bug as a quickfix?

**Comment by markstory** [comment]
@ADmad The issue is more that array casting `null` results in `[]`

```php
php > var_dump((array)null);
array(0) {
}
php >
```

**Comment by markstory** [comment]
Pull request open now.
