### ISSUE TITLE
Event data converted to String?!!

### ISSUE THREAD

**Issue by nilsonpena** [cakephp/cakephp#10084]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12
* Platform and Target: LINUX APACHE, MySQL.

### What you did
I'd like to throw an Event from my AvatarController with an associative array at data Event, according the code bellow:
//at AvatarController
```php
$event = new Event('Controller.Avatar.saveAvatar', $this, [
                'name' => $this->request->session()->read('Auth.User.username'),
                'file' => $this->request->session()->read('Auth.User.avatar')]);
$this->eventManager()->dispatch($event);
```

//at AvatarListener class
```php
namespace App\Event;

use Cake\Log\Log;
use Cake\Event\EventListenerInterface;

class AvatarListener implements EventListenerInterface {
    public function implementedEvents() {
        return [
            'Controller.Avatar.saveAvatar' => 'avatarCriado',
        ];
    }
    public function avatarCriado($event, array $dados) {
        Log::write('info', "Avatar {$dados['file']} salvo por {$dados['name']}");
    }
} 
```

### What happened
When access de data Event in my AvatarListener get an Warning:

`Illegal string offset 'name' [APP/Event/AvatarListener.php, line 17]`

So, tried: 
Log::write('info', "Avatar {$dados['0']} salvo por {$dados['1']}");
... It writes in my log only the first letter of the user name... So I think the data array get converted to an STRING.

### What you expected to happen
I´d like to access the data array at AvatarListener 

P.S. : You guys rock! Thank you, but take a look at Events documentation. It is not clear enough as the other parts of Cake Documentations

**Comment by ADmad** [comment]
Well [this](https://book.cakephp.org/3.0/en/core-libraries/events.html#getting-event-data-as-function-parameters) example in the book shows how the event data is passed to callback methods. The data array values are passed individual arguments. So your method signature should be
`avatarCriado($event, $name, $file)`.

**Comment by nilsonpena** [comment]
Thank you!
