### ISSUE TITLE
CollectionInterface return typehint for reduce method is void instead of mixed

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#10099]
The doc block for `\Cake\Collection\CollectionInterface::reduce()` reads as follows:

```php
    /**
     * Folds the values in this collection to a single value, as the result of
     * applying the callback function to all elements. $zero is the initial state
     * of the reduction, and each successive step of it should be returned
     * by the callback function.
     * If $zero is omitted the first value of the collection will be used in its place
     * and reduction will start from the second item.
     *
     * @param callable $c The callback function to be called
     * @param mixed $zero The state of reduction
     * @return void
     */
    public function reduce(callable $c, $zero = null);
```

The return type-hint is `void`. A correct reduce implementation will return the result of the reduction. Indeed, the implementation in `\Cake\Collection\CollectionTrait` returns a value. Therefore, the type-hint in this docblock should be `mixed`.

I'm happy to submit a PR for this but I wanted to post an issue first to check if there was some other reason for the type-hint being set to void.

**Comment by lorenzo** [comment]
Please submit a PR
