### ISSUE TITLE
cakephp:3.4.0-RC3 aura/intl version error

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#10109]
Tried to upgrade from cakephp:3.4.0-RC2 to cakephp:3.4.0-RC3
but errors out:

    site@www:~/0/public$ composer require "cakephp/cakephp:3.4.0-RC3"
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for cakephp/cakephp 3.4.0-RC3 -> satisfiable by cakephp/cakephp[3.4.0-RC3].
        - Conclusion: remove aura/intl 1.1.1
        - Conclusion: don't install aura/intl 1.1.1
        - cakephp/cakephp 3.4.0-RC3 requires aura/intl ^3.0.0 -> satisfiable by aura/intl[3.0.0, 3.0.0-beta1].
        - Can only install one of: aura/intl[3.0.0, 1.1.1].
        - Can only install one of: aura/intl[3.0.0-beta1, 1.1.1].
        - Installation request for aura/intl == 1.1.1.0 -> satisfiable by aura/intl[1.1.1].

    Installation failed, reverting ./composer.json to its original content.
    site@www:~/0/public$

**Comment by ADmad** [comment]
Did you try first removing `cakephp/cakephp` and then required new version?

**Comment by markstory** [comment]
Do you have other dependencies that require `aura/intl`?

**Comment by andraskende** [comment]
no dependencies, for testing now I tried a fresh install as

    composer create-project --prefer-dist cakephp/app public
    cd public 
    composer remove cakephp/cakephp 
    composer update
    composer require "cakephp/cakephp:3.4.0-RC3"




    > App\Console\Installer::postInstall
    Created `config/app.php` file
    Set Folder Permissions ? (Default to Y) [Y,n]? 
    Permissions set on /home/site/0/public/tmp/cache
    Permissions set on /home/site/0/public/tmp/cache/models
    Permissions set on /home/site/0/public/tmp/cache/persistent
    Permissions set on /home/site/0/public/tmp/cache/views
    Permissions set on /home/site/0/public/tmp/sessions
    Permissions set on /home/site/0/public/tmp/tests
    Permissions set on /home/site/0/public/tmp
    Permissions set on /home/site/0/public/logs
    Updated Security.salt value in config/app.php
    site@www:~/0$ 
    site@www:~/0$ 
    site@www:~/0$ 
    site@www:~/0$ 
    site@www:~/0$ cd public 
    site@www:~/0/public$ composer remove cakephp/cakephp 
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Nothing to install or update
    Writing lock file
    Generating autoload files
    > Cake\Composer\Installer\PluginInstaller::postAutoloadDump
    site@www:~/0/public$ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Nothing to install or update
    Generating autoload files
    > Cake\Composer\Installer\PluginInstaller::postAutoloadDump
    site@www:~/0/public$ composer require "cakephp/cakephp:3.4.0-RC3"
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Can only install one of: aura/intl[3.0.0, 1.1.1].
        - Can only install one of: aura/intl[3.0.0, 1.1.1].
        - Can only install one of: aura/intl[3.0.0, 1.1.1].
        - cakephp/cakephp 3.4.0-RC3 requires aura/intl ^3.0.0 -> satisfiable by aura/intl[3.0.0].
        - Installation request for cakephp/cakephp 3.4.0-RC3 -> satisfiable by cakephp/cakephp[3.4.0-RC3].
        - Installation request for aura/intl == 1.1.1.0 -> satisfiable by aura/intl[1.1.1].


    Installation failed, reverting ./composer.json to its original content.
    site@www:~/0/public$

**Comment by andraskende** [comment]
made it work 

    composer create-project --prefer-dist cakephp/app public
    cd public 
    composer remove cakephp/cakephp 
    rm -rf vendor/aura/intl/
    rm composer.lock
    composer require "cakephp/cakephp:3.4.0-RC3"

**Comment by dereuromark** [comment]
The `Installation request for aura/intl == 1.1.1.0` hints the blocking and is because of the already present lock file.
Composer when running require on a single package will probably in this case not attempt to major any other dependencies of it automatically, so you will have to manually confirm it as:

    composer require "cakephp/cakephp:3.4.0-RC3" "aura/intl:^3.0.0"
