### ISSUE TITLE
Add Validator::custom()

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#10107]
The `Validator` class has all kind of useful methods like `Validator::boolean()` as a shortcut for `->add(['field', 'name', ['rule' => 'boolean']]})`. As far as I can see there is no such method for the "custom" rule that allows you to specify a custom regex. Is there a reason for this or was it merely missed? (Maybe `Validator::regex` might be a less confusing name.)

A more general approach might be to add a `__call` method to `Validator` that works for all the default rules automatically (just based on the name).

**Comment by markstory** [comment]
`regex` or `pattern` is probably a better name than `custom`.

**Comment by inoas** [comment]
👍 for `regex()` over `custom()`

**Comment by cleptric** [comment]
PR is open
