### ISSUE TITLE
Table::validateUnique on none scalar values

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#10104]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.12

This came up in #10094 

When you're calling `Table::validateUnique` on a none scalar value, the method will always return `false`.
In my opinion, this is a unexpected behaviour (As pointed out before).
As we allow the user to validate a none scalar value, we maybe should throw an exception in this case.
The docblock describes `@return bool true if the value is unique` which is simply not true in this edge case.

**Comment by ravage84** [comment]
Throwing an exception is a bit going overboard with it, for me.

I guess, [fixing it in Bake](https://github.com/cakephp/bake/issues/299) mitigates this a bit but improving the API documentation could help, too.
So, I created a PR #10110 for that
