### ISSUE TITLE
Call to protected method of fallback translator Aura\Intl\Translator::getMessage()

### ISSUE THREAD

**Issue by JoepRoebroek** [cakephp/cakephp#10115]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12
* Platform and Target: Nginx, MySQL, Ubuntu 14.04.

### What you did
Updated from 3.3.11 to 3.3.12. 

### What happened
Got the following error on most pages:
```
Fatal error: Uncaught Error: Call to protected method Aura\Intl\Translator::getMessage() from context 'Cake\I18n\Translator' in /var/www/site/vendor/cakephp/cakephp/src/I18n/Translator.php on line 97
```

### What you expected to happen
No error.

### Possible fix

https://github.com/cakephp/cakephp/blob/master/src/I18n/Translator.php#L95 tries to execute protected method on fallback class. `getMessage` should either be replaced by `translate` or the fallback should be moved to the translate function, which is more neat I guess.

**Comment by markstory** [comment]
What version of aura/intl do you have? I don't get the same error with aura/intl 1.1.1. Are you customizing the fallback loader at all?

**Comment by JoepRoebroek** [comment]
Version 1.1.1, installed via composer. Did not customize the fallback loader. But I think it's a bug in their code as well, since `$this->fallback` should adhere to `TranslatorInterface` which does not specify `getMessage` only `translate`.

**Comment by raul338** [comment]
I had the same bug only in production. Somehow it solved by nuking vendor directory and reinstalling via `composer install`

**Comment by JoepRoebroek** [comment]
@raul338 tried your suggestion, but did not solve the problem for me. If I have time this weekend I'll check if I can create a small project that reproduces the problem consistently.

**Comment by markstory** [comment]
@JoepRoebroek I double checked that the tests do hit the fallback loader (they do). I'm not sure why we don't see the protected method errors in our own test harness.

**Comment by JoepRoebroek** [comment]
@markstory ok, probably it's environment specific. I'll try and see if I can figure it out over the weekend. For now, maybe it's good to check php versions, mine is at:
`PHP 7.0.15-1+deb.sury.org~trusty+1`
Forgot to mention this in the original report.

**Comment by markstory** [comment]
Could you try clearing out the translation cache, and possibly deleting and reinstalling aura/intl?

**Comment by JoepRoebroek** [comment]
@markstory Thanks, today, on my dev environment, I flushed my Redis cache and then the problem disappears. So it's a caching issue. From here, I need to check how I can reproduce the error once again.

**Comment by JoepRoebroek** [comment]
@markstory Ok, so I figured out that, apparently, PHP approves when instances with the same classname call protected methods of each other. So that explains why it has never thrown an error, even in the test harnesses. The default translator retrieved from the registry is cached in `_cake_core_`. Which in .11 is Aura, but now is Cake's own I18n Translator. Therefore, it occurs that we get this:
```
object(Cake\I18n\Translator) {
	[protected] fallback => object(Aura\Intl\Translator) {
```
Though, I still need to figure out why the Cake Translator is initialized with a fallback on Aura.

Besides figuring out the exact cause, I also advocate that the TranslatorInterface in Aura should be adjusted, such that there is a public interface in which the translator instances can fallback on each other.

**Comment by JoepRoebroek** [comment]
Ok, so the following goes wrong:
- There is `PackageLocator` in Aura with a cached registry
- There is `TranslatorLocator` in Aura with a cached registry
- There is `TranslatorFactory` which is extended and modified in CakePHP such that the translators are factores with the `Cake\I18n\Translator` class.

If the PackageLocator can retrieve its translator from cache, but TranslatorLocator cannot, the error occurs. Since the fallback comes from PackageLocator and in cache this is Aura, and the main instance comes from TranslatorLocator and this is the Cake Translator.

Personally, I think adjusting the public interface of the TranslatorInterface is the best way to go. But I can imagine that checking if the instance classnames match and throwing a descriptive exception is also a good way to go as a quick fix. From the exception people could learn they should try and clear their `_cake_core_` cache.

**Comment by markstory** [comment]
>  I also advocate that the TranslatorInterface in Aura should be adjusted, such that there is a public interface in which the translator instances can fallback on each other.

You are welcome to take that up with the Aura folks. :smile:

**Comment by markstory** [comment]
> But I can imagine that checking if the instance classnames match and throwing a descriptive exception is also a good way to go as a quick fix. From the exception people could learn they should try and clear their _cake_core_ cache.

Would you be willing to put together a pull request with this new warning/error?

**Comment by JoepRoebroek** [comment]
> Would you be willing to put together a pull request with this new warning/error? 

:+1: no problem, I'll have time to do this tomorrow

**Comment by markstory** [comment]
Closing as there is a pull request open to add the suggested error message.

**Comment by mamchenkov** [comment]
We've just seen this issue after updating from CakePHP v3.3.15 to v3.4.2 (which brings aura 3.0.0).  Running the unit tests errors half of the test suite with:

```
203) OurTestClass::testOurMethod
Error: Call to a member function getMessage() on null

vendor/cakephp/cakephp/src/I18n/Translator.php:90
vendor/cakephp/cakephp/src/I18n/Translator.php:121
vendor/cakephp/cakephp/src/I18n/functions.php:35
the rest of our own call stack
```

There was no message suggesting to clear the cache.  Thankfully, we found this ticket. :smile: 
Running `./bin/cake cache clear_all` solves the problem.
