### ISSUE TITLE
Sort is not applied to find queries on association objects.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10119]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12
* Platform and Target: Apache2, PHP 7.1.1, MySQL

### What you did

```
class Sources extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->belongsToMany('Tags', [
            'strategy' => Association::STRATEGY_SELECT,
            'sort' => ['title' => 'ASC']
        ]);
    }
}

$assoc = $this->loadModel('Sources')->association('Tags')->find()->all();
dd($assoc->toArray());
```

In the above example I used the association object so that it would proxy the find call, and did a basic find all.

### What happened

Looks like the association would add conditions but not sorting.

### What you expected to happen

`Tags` should be sorted by `title`.

Is this a bug or enhancement? I could not decide.

**Comment by markstory** [comment]
> Is this a bug or enhancement? I could not decide.

I don't think we ever implemented that, so maybe a bit of both :smile:

**Comment by thinkingmedia** [comment]
PR is up now
