### ISSUE TITLE
Associated finds with map/reduce don't work

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#10118]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.12
* Platform and Target: PHP 5.6.25, MySQL 5.6.28, Mac OS 10.12.2

### What you did
```
// Controller
$items = TableRegistry::get('Items')
    ->find()
    ->contain(['Tags' => ['finder' => 'groupedByName']])
    ->all();

// ItemsTable
$this->hasMany('Tags');

// TagsTable
public function findGroupedByName(Query $query, array $options = [])
{
    $mapper = function ($tag, $key, $mapReduce) {
        $mapReduce->emitIntermediate($tag, $tag->name);
    };
    $reducer = function ($results, $name, $mapReduce) {
        $mapReduce->emit($results[0], $name);
    };
    $query->mapReduce($mapper, $reducer);
    return $query;
}
```

### What happened
The item was returned with tags indexed as if the map/reduce didn't happen
```
Array
(
    [0] => Cake\ORM\Entity Object
        (
            [id] => 8
            [name] => item-name
            [tags] => Array
                (
                    [0] => Cake\ORM\Entity Object
                        (
                            [id] => 1
                            [name] => top
```

### What you expected to happen
I'd expect that the tags in that resultset would be indexed by the tag name. If I do a direct find for Tags with the same finder I get what you'd expect.

```
$tags = TableRegistry::get('Tags')
    ->find('groupedByName')
    ->all();
Array
(
    [tag-name] => Cake\ORM\Entity Object
        (
            [id] => 1
            [name] => top
        )
)
```

It seems like I *should* be able to map/reduce on an association and have the results grouped with whatever the map/reduce dictates. Not sure if anyone else has run into this situation yet.

Thanks

**Comment by lorenzo** [comment]
Have you tried using `formatResults` instead?

**Comment by patrickconroy** [comment]
Hm, that actually fails with
```
Notice: Undefined index: foreign_key in cakephp/cakephp/src/ORM/Association/ExternalAssociationTrait.php on line 119
```
Assuming you're talking about something like this..
```
public function findGroupedByName(Query $query, array $options = [])
{
    $query->formatResults(function ($_results) {
        $results = [];
        foreach ($_results as $result) {
            $results[$result->name][] = $result;
        }
        return $results;
    });
    return $query;
}
```

When not external, the results come back as expected.

**Comment by patrickconroy** [comment]
Digging into that method, when there are neither `formatResults` or a `mapReduce`, `$fetchQuery->all()` is a  `Cake\ORM\ResultSet`. If either of those exist, `$fetchQuery->all()` is a  `Cake\Datasource\ResultSetDecorator`. `toArray()`ing on that doesn't give you the entities in a single array that function expects them to be.

**Comment by patrickconroy** [comment]
Hi @lorenzo, do you think this is a fixable thing? Or should I assume it's not possible to contain tables which format results in a non-normal way?

**Comment by lorenzo** [comment]
I don't think it is possible, since the "join" done in php needs to look for something lo link the rows together.

**Comment by patrickconroy** [comment]
Messing around, this returns the results as expected, but I don't know if there's something else that could make it happen. That is_array is there because it needed to check where the `formatResults` or `mapReduce` put the entities.

```
protected function _buildResultMap($fetchQuery, $options)
{
    $resultMap = [];
    $key = (array)$options['foreignKey'];

    $results = $fetchQuery->all();
    if ($results instanceof \Cake\Datasource\ResultSetDecorator) {
        foreach ($results as $resultGroup => $resultsInGroup) {
            if (!is_array($resultsInGroup)) {
                $values = [];
                foreach ($key as $k) {
                    $values[] = $resultsInGroup[$k];
                }
                $resultMap[implode(';', $values)][$resultGroup] = $resultsInGroup;
                continue;
            }
            foreach ($resultsInGroup as $result) {
                $values = [];
                foreach ($key as $k) {
                    $values[] = $result[$k];
                }
                $resultMap[implode(';', $values)][$resultGroup][] = $result;
            }
        }
        return $resultMap;
    }

    foreach ($results as $result) {
        $values = [];
        foreach ($key as $k) {
            $values[] = $result[$k];
        }
        $resultMap[implode(';', $values)][] = $result;
    }

    return $resultMap;
}
```

**Comment by patrickconroy** [comment]
Hey guys. I know this is going on two years old, but I just ran into it again.
Should the core allow associated results being grouped in whatever way the user wants? Right now `ExternalAssociationTrait::_buildResultMap` is just blindly assuming that there's a flat array of data, when I'm attempting to group based on the results themselves.

**Comment by markstory** [comment]
> Should the core allow associated results being grouped in whatever way the user wants?

Yes and no. In order to stitch association data together the ORM needs to be able to access the binding/foreignkey columns without having to traverse additional arrays.
