### ISSUE TITLE
3.4 RC4: debug(['test']) Notice (8): Array to string conversion

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10123]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4 RC4
* Platform and Target: PHP 7.1

### What you did

```php
<?= debug(['test'])  ?>
```

### What happened

```
Notice (8): Array to string conversion [APP/Template/Layout/default.ctp, line 59]
```

**Comment by ADmad** [comment]
`debug()` returns the values passed to it as argument. So you are effectively doing `echo ['test'];` in which case the error is expected.

**Comment by markstory** [comment]
Closing as this is an intentional behavior change in 3.3.12
