### ISSUE TITLE
RFC - Internal Usage of deprecated methods

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10128]
A big part of 3.4 has been to deprecate the combined getter/setter methods and replace those with separate `getX`, `setX` methods. The benefits of these new methods are:

1.  We will be able to more easily add strict typing in the future as each method has fewer possible return values.
2. Methods are simpler, have fewer parameters and modes which in theory leads to fewer issues due to reduced complexity.
3. IDEs can provide better auto-completion support.

While talking with @chinpei215 he brought up the fact that we should fully migrate internal usage of CakePHP to use the new un-deprecated methods *before* releasing 3.4.0. Doing this internal migration now would help ensure that any issues with the new methods are found earlier, and that users would only have to check their deprecated method usage once when they first upgrade, instead of at each release in 3.4.x

### Benefits of doing the work now

1. We can have simpler upgrade guidelines. We can recommend that users must update any deprecated methods that they have overloaded to use the new methods instead. Doing so will ensure that their code continues to work.
2. We can save work in the future as we won't have a large block of work when deprecations become runtime errors (tentatively planned for 3.6.0)

### Drawbacks of doing the work now

1. Will delay the release of 3.4.0 by a week or two.
2. We'll need to stick to the immediate internal upgrades for all future deprecations.

I'm looking to get some consensus on whether we want to finish the usage of undeprecated methods now, or in future 3.4.x releases.

#### Related issues

* #10086 
* #9978

**Comment by chinpei215** [comment]
I vote we do the work now. Also I lend some hands.

**Comment by markstory** [comment]
@chinpei215 I've started with `config()`, I'll have the pull request up tonight.

**Comment by antograssiot** [comment]
I too think that we should upgrade them before the release. The reason is that we don't add tests for the methods and just implicitly rely on the old existing method tests to still pass but I remember that I found a/some issue with the new methods while upgrading some core code.

I can also help, what else do we have  except the configuration you are working on ?

On a side note, I like the idea of having a last 3.x serie release that will start trigger errors but I definitely prefer that we would have throw USER_DEPRECATED errors all the way like we did in 3.1 with the viewBuilder and add again a note in the migration guide to tell users how to hide those.  It would then allow us to provide a deprecated errors section in debug_kit for example and help users to upgrade their app gradually. I understand that this is too late for 3.4 though but that's something we can stick with for the 4.x serie...

**Comment by ADmad** [comment]
We should add trigger_error() for deprecated usages only in the last 3.x release. Doing it earlier would be a big annoyance given the extend of changes. Test suite for all apps and plugins will break.

**Comment by burzum** [comment]
+1 on on doing it now. I don't think the drawbacks are really drawbacks.

> Will delay the release of 3.4.0 by a week or two.

Who pushes us to release it this week? :) I prefer the better choice over getting it out quickly.

> We'll need to stick to the immediate internal upgrades for all future deprecations.

To me this sounds like a benefit? :)

**Comment by chinpei215** [comment]
@burzum As an example, if users are overriding `FormHelper::input()` and they are calling `FormHelper::inputs()`, their application would break as `inputs()` no longer calls `input()` internally.

**Comment by markstory** [comment]
>  I definitely prefer that we would have throw USER_DEPRECATED errors all the way like we did in 3.1 with the viewBuilder and add again a note in the migration guide to tell users how to hide those. 

@antograssiot I totally agree, and what you described is the exact process I wanted to use/follow.

**Comment by markstory** [comment]
> Who pushes us to release it this week?

@burzum I was pushing us to release. In the RC announcements I promised a stable release 'within a week if there were no major issues found'. However, this feels like a major issue that _should_ block the release. :smil

**Comment by inoas** [comment]
This is great and warrants even a longer wait. It is like s 2nd test suite where it is made sure that the bew style getters/setters actually work.

**Comment by markstory** [comment]
Closing as the known work for this has been completed.
