### ISSUE TITLE
Getting Blank Screen ( Cakephp 3.3.13 )

### ISSUE THREAD

**Issue by GaneshKandu** [cakephp/cakephp#10129]
Hi,

I am Trying to Install Cakephp 3.3.13

Commit #17e96e1 
Downloaded from [https://github.com/cakephp/cakephp/releases/download/3.3.13/cakephp-3-3-13.zip](https://github.com/cakephp/cakephp/releases/download/3.3.13/cakephp-3-3-13.zip)

it seems that you committed 3.4.0-beta4

**Comment by josegonzalez** [comment]
The zipfile asset has been replaced with 3.3.13.

**Comment by GaneshKandu** [comment]
Thanks ! @josegonzalez

**Comment by markstory** [comment]
Blerg. Sorry about that. The app requirements need to be updated clearly.

**Comment by GaneshKandu** [comment]
**No Problem**
