### ISSUE TITLE
BufferResults is coupled together with MySQL and ResultSet

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10135]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.13
* Platform and Target: MySQL 5.7, PHP 7.1.1, Apache2, Ubuntu 14.

### What you did

Disabling buffered queries should disable the memory caching of entities in `ResultSet`.

Example:

```
   $resultSet = $this->Modal->find()->bufferResults(false)->all();
   $resultSet->rewind(); /// will throw error because the iterator is not caching
```

### What happened

It doesn't appear to be working. One of the issues is that any PDOException will leave the MySQL server with buffering disabled. Here's the `MysqlStatement.php` file with the problem.

```
    public function execute($params = null)
    {
        $this->_driver->connection()->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, $this->_bufferResults);
        $result = $this->_statement->execute($params);
        $this->_driver->connection()->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);

        return $result;
    }
```

If the `execute($params)` throws an exception, then buffering is not restored. If you have persistent connection enabled, then the next web request is going to fail with a bunch of MySQL errors about unbuffered queries with the type of fetch you make with PDO.

### What you expected to happen

I was expecting this to **only** change the ResultSet handling of entities while iterating the records. I didn't expect this to alter the state of MySQL.

This setting is coupled together to do two very different things.

Please discuss why. Thanks

**Comment by markstory** [comment]
If we don't disable MySQL Result buffering, then the MySQL driver will buffer the entire result set at the PDO driver level defeating the point of turning off buffering in the ORM/Database layers. We should probably use `finally` here to ensure that the buffering attribute is reverted. That wasn't an option when this code was written though :smile:

**Comment by markstory** [comment]
Closing as a pull request is open now.
