### ISSUE TITLE
pagination with caching goes wrong

### ISSUE THREAD

**Issue by ChristianYeah** [cakephp/cakephp#10133]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.0-RC3
* Platform and Target: windows 10/ php7.1 with redis/ mariadb

### What you did
I was planning to caching paginated data. 
1. The code below has one problem, when there's no cached data in redis, everything goes fine. But if you refresh the browser, it will notice you that 
```php
$articles = Cache::remember($cacheKey, function () use ($that, $tag) {
                $query = $that->Articles->find()->select(['title','description','created_at'])->matching('Tags', function (\Cake\ORM\Query $query) use ($tag) {
                    return $query->where(['Tags.name' => $tag]);
                });
                return $that->paginate($query);
            }, 'redis');
```
```php
Notice (8): Undefined index: pageCount [CORE\src\View\Helper\PaginatorHelper.php, line 679]
Notice (8): Undefined index: count [CORE\src\View\Helper\PaginatorHelper.php, line 683]
Notice (8): Undefined index: perPage [CORE\src\View\Helper\PaginatorHelper.php, line 686]
Notice (8): Undefined index: count [CORE\src\View\Helper\PaginatorHelper.php, line 687]
Notice (8): Undefined index: count [CORE\src\View\Helper\PaginatorHelper.php, line 688]
Notice (8): Undefined index: page [CORE\src\View\Helper\PaginatorHelper.php, line 701]
Notice (8): Undefined index: current [CORE\src\View\Helper\PaginatorHelper.php, line 703]
Notice (8): Undefined index: count [CORE\src\View\Helper\PaginatorHelper.php, line 704]
```
2. using function ```$this->paginate()``` will goes wrong cuz it only accept query builder or Table instance. Am I right?

3. Then, I read the doc and it said I can use ```$articles = $this->Paginator->paginate($articles);``` alternatively. But it still not working 
```Call to a member function paginate() on boolean```
### What happened
1. using ```$this->paginate()`` the very first time you visit the site has no problem. but if its the second time you visit it. it goes wrong like

2.using 
```php
$articles = Cache::remember($cacheKey, function () use ($that, $tag) {
                $query = $that->Articles->find()->select(['title','description','created_at'])->matching('Tags', function (\Cake\ORM\Query $query) use ($tag) {
                    return $query->where(['Tags.name' => $tag]);
                });
                return $query->toArray();
//                return $that->paginate($query);
            }, 'redis');
$this->Paginator->paginate($articles);
``` 
leads to an error```Call to a member function paginate() on boolean```

**Comment by thinkingmedia** [comment]
You need to include the paging parameters in the cache results.

```
list($articles,$paging) = Cache::remember($cacheKey, function () use ($that, $tag) {
                $query = $that->Articles->find()->select(['title','description','created_at'])->matching('Tags', function (\Cake\ORM\Query $query) use ($tag) {
                    return $query->where(['Tags.name' => $tag]);
                });
                return [$that->paginate($query),$that->request['paging']];
            }, 'redis');
$this->request['paging'] = $paging;
```

**Comment by ChristianYeah** [comment]
@thinkingmedia $paging is the current page number?  I think it doesnt work for me at the moment

**Comment by thinkingmedia** [comment]
It's an array of values needed by the pagination helper.

Maybe there is more you have to do then my code example.

**Comment by thinkingmedia** [comment]
Maybe you can't directly assign request parameters. Try this instead.

```
$that->request->addParams(['paging'=>$paging]);
```

**Comment by markstory** [comment]
Closing as this doesn't look like an issue with CakePHP but more how you are using it.

**Comment by ChristianYeah** [comment]
@thinkingmedia now its right. thanks
