### ISSUE TITLE
transpose method bug

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#10137]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: ~3.3

### What you did

$items = [
   ['Products', '2012', '2013', '2014'],
   ['Product A', '200', '100', '50'],
   ['Product B', '300', '200', '100'],
   ['Product C', '400', '300', '200'],
   ['Product D', '500', '400', '300'],
]
$transpose = (new Collection($items))->transpose()->toList();

### What happened
// Returns
[
    ['Products', 'Product A', 'Product B', 'Product C'],
    ['2012', '200', '300', '400'],
    ['2013', '100', '200', '300'],
    ['2014', '50', '100', '200'],
    [ ]
]

### What you expected to happen
// Returns
[
    ['Products', 'Product A', 'Product B', 'Product C, 'Product D'],
    ['2012', '200', '300', '400', '500'],
    ['2013', '100', '200', '300', '400'],
    ['2014', '50', '100', '200', '300'],
]

@markstory is it possible to assign it to me to fix in advanced.

**Comment by lorenzo** [comment]
@dilab you can submit a pull request with your fix if you already have one
