### ISSUE TITLE
More explicit error message when plugin files are not found

### ISSUE THREAD

**Issue by be-mohand** [cakephp/cakephp#10141]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
Just create a new plugin

### What happened
I've created all needed folders and files, but I got the message: "Missing Controller. Create the files xxxController in ....". The files was already created.

### What you expected to happen
I didn't add my namespace in the autoloader. So my files were not found.

I think it could be very interesting to add more explicit error message when files are not found, especially when it concerns plugins. Maybe something like: "Don't forget to update your composer.json or to use "autoload" => true in your bootstrap.php".

**Comment by markstory** [comment]
Where would you expect to see that error?

**Comment by lorenzo** [comment]
The tricky part about a good error message here is to detect that you actually intended to use a plugin

**Comment by burzum** [comment]
@lorenzo just word the error message accordingly: 

> In the case you tried to access a plugin controller make sure you added it to your composer file or you use the autoload option for a plugin.

Most simple solution? :)

**Comment by markstory** [comment]
Sounds like an improvement @burzum. Could you put together a pull request together for that change?

**Comment by markstory** [comment]
Closing as the related pull request has been merged.
