### ISSUE TITLE
[RFC] Custom registryAlias for target table in Association.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#10140]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.0

Currently associations use their name as a registry alias for target table. 
I was wondering if we could allow configuring custom alias for table locator. It's OK while working with a small number of tables, but if the application grows and there are many models with similar associations architecture working with associations can become very verbose.

An example:

```php
//FooCategoriesTable
$table->hasMany('ChildFooCategories');

//BarCategoriesTable
$table->hasMany('ChildBarCategories');

$this->FooCategories->ChildFooCategories->find();
$this->BarCategories->ChildBarCategories->find();
```

It may become very tedious and hard to remember all those complex association names. All association names need to have unique names even across tables just becase of registry alias.

What I propose is something like this:
```php
//FooCategoriesTable
$table->hasMany('Children', [
    'registryAlias' => 'ChildFooCategories'
]);

//BarCategoriesTable
$table->hasMany('Children', [
    'registryAlias' => 'ChildBarCategories'
]);

$this->FooCategories->Children->getTarget(); //FooCategoriesTable
$this->BarCategories->Children->getTarget() //BarCategoriesTable
```

Notice both tables have a `Children` association but in each of them it points to a different table in the registry.
Currently it is impossible to do even using `className`:

```php
//FooCategoriesTable
$table->hasMany('Children', [
    'className' => 'ChildFooCategories'
]);

//BarCategoriesTable
$table->hasMany('Children', [
    'className' => 'ChildBarCategories'
]);

$this->FooCategories->Children->getTarget(); //FooCategoriesTable
$this->BarCategories->Children->getTarget() //FooCategoriesTable !!!
```

**Comment by lorenzo** [comment]
Don't the use the alias name instead of the table name?

In any case, the challenge to solve is to be able to re-use instances when building associations, that is the reason we don't allow repeated aliases for different tables.

How do you see this could work?

**Comment by robertpustulka** [comment]
Of course if we want to use the same instance of the same table it is OK. But I want to use different tables in different places but with the same association name. Coupling association name with table registry alias is the issue here.

I'm not sure if something as simple as that would work:

```php
    // Cake\ORM\Association
    public function getRegistryAlias()
    {
        if (!$this->_registryAlias) {
            if (strpos($this->_className, '.')) {
                list($plugin) = pluginSplit($this->_className, true);
                $this->_registryAlias = $plugin . $this->_name;
            } else {
                $this->_registryAlias = $this->_name;
            }
        }

        return $this->_registryAlias;
    }

    public function setRegistryAlias($alias)
    {
        $this->_registryAlias = $alias;

        return $this;
    }

    public function getTarget()
    {
        if (!$this->_targetTable) {
            $registryAlias = $this->getRegistryAlias();
            $tableLocator = $this->tableLocator();

            $config = [];
            if (!$tableLocator->exists($registryAlias)) {
                $config = ['className' => $this->_className];
            }
            $this->_targetTable = $tableLocator->get($registryAlias, $config);
        }

        return $this->_targetTable;
    }
```

**Comment by lorenzo** [comment]
@robertpustulka I'm aware of the issue and the restriction. Another challenge that I just remembered is that aliases should be unique because of joins, if you use the same alias in the same query, then you get unexpected errors.

**Comment by lorenzo** [comment]
@robertpustulka Try submitting that as a pull request with a few tests, I may be able to help you move this idea forward

**Comment by inoas** [comment]
The last example @robertpustulka looks very troublesome and unexpected. 
- Is this documented yet? On https://book.cakephp.org/3.0/en/orm/associations.html I searched for `"unique"` and only found one instance.
- Could we do something like throwing Exceptions here the moment the 2nd association definition is being initialized?
- Do you plan on `registryAlias` to be used for creating SQL query aliases? How would one make sure that those aliases then are unique across the system (again, exception time?)

**Comment by robertpustulka** [comment]
@lorenzo If I understand correctly loaders use table alias and not association name, so theoretically it wouldn't be a problem.

In current situation we could as well create associations and a query that would potentially break:

```php
$this->Foo->belongsTo('Bar');
$this->Foo->belongsTo('Baz');
$this->Foo->Bar->belongsTo('Bar');

$this->Foo->find()->contain(['Baz, 'Foo.Baz']);
```

In any case this could be temporarily fixed by changing a strategy.

I'll put this code into a PR and we'll see if it works. To be honest I'm expecting unexpected here...

**Comment by robertpustulka** [comment]
I've noticed something else which that change could fix:

```php
$table->belongsTo('Foo');
$table->Foo->setName('Bar');

$table->find()->contain('Bar'); //as you would expect
```
Exception is thrown:
`InvalidArgumentException: You have contained 'Bar' but that association was bound as 'Foo'.`

Another issue is that changing association name does not change it's key in a registry what may cause further confusion.

**Comment by robertpustulka** [comment]
PR is open
