### ISSUE TITLE
BelongsToMany link

### ISSUE THREAD

**Issue by gi-jones** [cakephp/cakephp#10152]
This is a: Bug

* CakePHP Version: 3.3.13
* Platform and Target: Apache, MySQL

### What you did
For some reason the link() method on belongsToMany associactions fail and returns an error, when called directly from the controller. Calling it through an association however works. I'm sorry if my vocabulary is wrong here, but I think this examples shows what I mean:

```
$image = $this->Parts->Images->get($image_id)
$parts = $this->Parts->findById($part_id)->toArray();

$this->Parts->link($image, $parts);	//This returns an error

$this->Parts->Images->Parts->link($image, $parts); //This works
```

Link to docs on the method is here, but does not mention anything:
https://api.cakephp.org/3.2/class-Cake.ORM.Association.HasMany.html#_link

### What happened
The first link with the direct call gives me an fatal error:
Unknown method "link"
BadMethodCallException

### What you expected to happen
The last line works like a charm and links the to entries as expected.

**Comment by robertpustulka** [comment]
`$this->Parts->link($image, $parts);	//This returns an error` - here you are calling `PartsTable::link()` method which does not exist.

`$this->Parts->Images->Parts->link($image, $parts); //This works` Here `$this->Parts->Images->Parts` is a `BelongsToMany` association instance not the `PartsTable` instance, so this call works.

I think that should be documented somewhere that the old way of getting `$this->Foo->Bar` is actually an association and not the table.

**Comment by gi-jones** [comment]
Ok, I see what you're saying.
It does seem a roundabout way to do it though.

**Comment by lorenzo** [comment]
Closing as it seems to be a problem with understanding how it works, and moving as a possible enhancement to docs
