### ISSUE TITLE
IntegrationTestCase::_sendRequest doesn't handle errors anymore

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#10157]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.13

### What you did
I wrote some Integration test cases. Some of them trigger a method in my component which throws an `UnauthorizedException`.

### What happened
The exceptions are catched by the `ErrorHandlerMiddleware` and printed out to `stderr`.

### What you expected to happen
As a workaround, I did 
```
Configure::write([
    'Error' => [
        'skipLog' => ['Cake\Network\Exception\UnauthorizedException']
    ],
]);
```
inside my `tests\bootstrap.php`.
I would expect that these exceptions are not printed out while running `phpunit`

**Comment by markstory** [comment]
I think we'd need to remove the ErrorMiddleware from the application, or figure out a way to have the middleware re-raise exceptions in testing. Not sure how to do either of those though.

**Comment by markstory** [comment]
A possible implementation for this came up during @viraj-khatavkar 's talk where he replaced `Error.exceptionRenderer` with a stub that re-throws the exception. This could be packaged up into an `disableErrorMiddleware()` helper function in the IntegrationTestCase to make debugging easier.

**Comment by ravage84** [comment]
Isn't the ErrorMiddleware aware of any state we could check for and act differently? Not that I like the idea...

**Comment by markstory** [comment]
@ravage84 Yes another approach could be to replace the ErrorHandlerMiddleware with a stub that re throws.

**Comment by cleptric** [comment]
PR open 🙂
