### ISSUE TITLE
in bake all, bake models first

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10173]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.13
* Platform and Target: not important

### What you did
cake bake all

### What happened
cake baked all, model by model

### What you expected to happen
Since the baked views depend on the relationships baked on the models, all models should be baked first and then bake everything else.
I currently have to execute 'bake all' twice, so that the views get baked correctly.
A common bug that happens because of this is that on the index view, instead of showing a nice displayField (such as 'name') of an associated-and-not-yet-baked model shows as the primarykey 'id'.
(I believe this is a general issue, and not caused because I use a custom bake theme because my displayFields are not called 'name' but 'nombre', for example.)

**Comment by inoas** [comment]
Can you open the issue over here (just copy the body and title) and close this one? https://github.com/cakephp/bake

**Comment by ADmad** [comment]
This issue was moved to cakephp/bake#304
