### ISSUE TITLE
Change the order of template files

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10179]
Premise: I have developed a CMS as a plugin. The CMS works "out of the box", in fact contains a complete frontend and a complete backend, included templates.

Now I wish that things would work a little on the contrary: for example, if I don't like a template provided by the CMS (so, the plugin...), I override it through the app (normally plugins extend the app, not vice versa).

This is not possible, because the templates are searched in this order: theme, plugin, app.
While I wish I was: theme, app, plugin (of course this should **only** happen with the view of my cms).

If I understand correctly, this happens here (`View::_paths()`): https://api.cakephp.org/3.3/source-class-Cake.View.View.html#1287

What I want to know is whether it is possible to introduce the possibility to change this order. For example (as with many other things of CakePHP) to pass an option to the constructor of View and, if absent, set the default order (which must be the current one, of course).

Something like this (the code is **only explanatory**, ie only to understand what I mean):

    public function __construct(
        Request $request = null,
        Response $response = null,
        EventManager $eventManager = null,
        array $viewOptions = []
    ) {
        // ...code

        if (empty($viewOptions['orderForPaths'])) {
            $viewOptions['orderForPaths'] = ['theme', 'plugins', 'app'];
        }

        // ...code
    }

and then adapt the `View::_paths()` method accordingly.

What do you think about it?

**Comment by markstory** [comment]
> What I want to know is whether it is possible to introduce the possibility to change this order. For example (as with many other things of CakePHP) to pass an option to the constructor of View and, if absent, set the default order (which must be the current one, of course).

I'd rather not take on more complexity. It sounds like what you want is a custom view class.

**Comment by robertpustulka** [comment]
AFAIR you can overwrite plugin/theme templates in your app under `src/Template/Plugin/PluginName/...`

**Comment by ADmad** [comment]
I agree with @markstory. I too don't want to add additional complexity. If the current behavior doesn't suite your needs use a custom view class.

>  AFAIR you can overwrite plugin/theme templates in your app under src/Template/Plugin/PluginName/...

Correct.

**Comment by mirko-pagliai** [comment]
> I'd rather not take on more complexity
Ok, it seems reasonable for me :-) thanks anyway

@robertpustulka good indication, I did not know it!
