### ISSUE TITLE
Assets files on theme plugins not loaded when set base URLs

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#10172]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.13.
* Platform and Target: Apache/2.4.23 , 10.1.16-MariaDB, AND PHP 5.5.38.

### What you did
`app.php` file
```php
        'imageBaseUrl' => 'http://cdn.domain.com/img/',
        'cssBaseUrl' => 'http://cdn.domain.com/css/',
        'jsBaseUrl' => 'http://cdn.domain.com/js/',
```
`bootstrap.php` file
```php
Plugin::load('CustomTheme', ['ignoreMissing' => true, 'bootstrap' => true, 'routes' => true]);
```
`AppController.php` file
```php
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event);
        $this->viewBuilder()->theme('CustomTheme');
    }
```
`src/Template/Layout/default.ctp` file
```php
<?= $this->Html->css('app'); ?>
```
### What happened
The CSS file path is not loaded from the plugin although the app.css file located in the plugin as you can see below
```html
<link rel="stylesheet" href="http://cdn.domain.com/css/app.css"/>
```
### What you expected to happen
The css file should be loaded from the plugin as the following
```html
<link rel="stylesheet" href="http://cdn.domain.com/custom_theme/css/app.css"/>
```
**This issue only happens when setting imageBaseUrl, cssBaseUrl & jsBaseUrl**

**Comment by markstory** [comment]
Is the problem that the app version's of `app.css` was used instead of the theme/plugin's `app.css`?

**Comment by BassemN** [comment]
@markstory Yes, that's it.

**Comment by BassemN** [comment]
@markstory Please note that this only happens when setting imageBaseUrl, cssBaseUrl & jsBaseUrl.

**Comment by markstory** [comment]
I took a look into this. Because your `cssBaseUrl` configuration values include `://` the helpers cannot easily manipulate the URLs as they don't understand the context of the the baseUrl.  In order to automatically set the theme prefix the UrlHelper uses `file_exists()` when CDNs are involved, `file_exists()` is likely to not work. Even if we ignore the `file_exists()` limitations, based on your `cssBaseUrl` value of `http://cdn.domain.com/css` it is impossible for the helpers to create a URL of `http://cdn.domain.com/custom_theme/css/app.css` instead the best we could ever do is `http://cdn.domain.com/css/custom_theme/css/app.css` which is a differently wrong.

I'm not sure this can be fixed without creating different issues for other users. For example, I'm pretty confident that someone somewhere has a deploy process that copies all their application assets into S3 in a flat directory structure. Fixing this issue as you've outlined would break those use cases.

**Comment by BassemN** [comment]
Thank you for your detailed reply!
I think to fix this issue the `imageBaseUrl`, `cssBaseUrl` & `jsBaseUrl` should map to the directory name as you did [here](https://github.com/cakephp/app/blob/3.3.6/config/app.default.php#L49-L51) and add a new  variable called `assetsBaseUrl` which will work like the `fullBaseUrl` but only for the assets files so if someone sets the `assetsBaseUrl` to `http://cdn.domain.com/` then the generated path will be `assetsBaseUrl + cssBaseUrl = http://cdn.domain.com/css/`  else `fullBaseUrl + cssBaseUrl = http://domain.com/css/`

**Comment by markstory** [comment]
There is no `assetsBaseUrl` presently. I'm guessing that is something we'd need to add support for.

**Comment by BassemN** [comment]
Yes, assetsBaseUrl is a new variable

**Comment by tersmitten** [comment]
I think we hit the same problem, with `DebugKit`

![screenshot from 2017-12-13 08-52-48](https://user-images.githubusercontent.com/3392962/33927563-1a53fa2c-dfe3-11e7-8b49-91337e5278a9.png)

When we set:

```
        'imageBaseUrl' => 'https://foo.bar.dev/img/',
        'cssBaseUrl' => 'https://foo.bar.dev/css/',
        'jsBaseUrl' => 'https://foo.bar.dev/js/',
```

assets are not found.

Any updates on this issues, or something I / we can do?

**Comment by markstory** [comment]
> Any updates on this issues, or something I / we can do?

No updates yet. Url strings are still hard to work with as we don't know where to insert plugin directories.

**Comment by tersmitten** [comment]
Any suggestions on fixes this issue (in our application)?

Overrides over `Helper` methods?

**Comment by markstory** [comment]
You could override parts of `UrlHelper::assetUrl()` as it is the method that does plugin path insertion.

**Comment by markstory** [comment]
I was thinking about this a bit, and how feasible would it be for base urls to have a `{plugin}` placeholder in them? This placeholder/template value could be replaced with the actual plugin value or `''` for non-plugin paths.

**Comment by tersmitten** [comment]
I'll look into overriding asset URL.

**Comment by tersmitten** [comment]
I do not fully understand your last comment. Do do you mean at app.php file level?

**Comment by BassemN** [comment]
@tersmitten Until @markstory finds a way to support CDN URL, I created a new helper called `AssetsHelper` to replace current `HTTP_HOST` with new CDN domain as the following:

```php
<?php
namespace App\View\Helper;

use Cake\View\Helper;

class AssetsHelper extends Helper
{
    public $helpers = ['Html', 'Url'];

    public $assets_cdn_url = 'cdn.domain.com';

    public function css($url)
    {
        $css = $this->Html->css($url, ['fullBase' => true]);

        if (!empty($this->assets_cdn_url)) {
            $css = str_replace($_SERVER['HTTP_HOST'], $this->assets_cdn_url, $css);
        }

        return $css;
    }

    public function script($url)
    {
        $script = $this->Html->script($url, ['fullBase' => true]);

        if (!empty($this->assets_cdn_url)) {
            $script = str_replace($_SERVER['HTTP_HOST'], $this->assets_cdn_url, $script);
        }

        return $script;
    }

    public function url($url)
    {
        $url = $this->Url->build($url, ['fullBase' => true]);

        if (!empty($this->assets_cdn_url)) {
            $url = str_replace($_SERVER['HTTP_HOST'], $this->assets_cdn_url, $url);
        }

        return $url;
    }

    public function favicon()
    {
        $url = get_option('favicon_url', '/favicon.ico');
        $url = $this->Url->build($url, ['fullBase' => true]);

        if (!empty($this->assets_cdn_url)) {
            $url = str_replace($_SERVER['HTTP_HOST'], $this->assets_cdn_url, $url);
        }

        return "<link href='$url' type='image/x-icon' rel='icon'/>".
            "<link href='$url' type='image/x-icon' rel='shortcut icon'/>";
    }
}

```

**Comment by tersmitten** [comment]
@BassemN Thanks for posting that

**Comment by markstory** [comment]
@tersmitten My suggestion was that the application's baseUrl would be set to something like `https://cdn.example.com/assets/{plugin}css/`. For non plugin assets the `{plugin}` placeholder would be replaced with `''` while for plugin assets it would be replace with `plugin_name/`

**Comment by tersmitten** [comment]
@markstory And substitution would take place in the `UrlHelper`, right?

**Comment by tersmitten** [comment]
Or the `Router`

**Comment by markstory** [comment]
@tersmitten I would think that substitution would happen in urlhelper. I haven't fully thought this Idea through though.

**Comment by ADmad** [comment]
Fixed in 4.x
