### ISSUE TITLE
3.4 Add more control about multiple displayField output

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10175]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4

### What you did
Using multi-column primary keys and thatfor multiple column displayFields.

### What you expected
Looking for something like this: 

```php
// What you can do about it currently:
$this->setDisplayField(['name', 'user_id']); // Renders as 'foo;5'

// Proposed feature interface:
$this->setDisplayField([ // Renders as 'foo Record Name / Created By User ID: 5'
        'name' => __('%s Record Name'),
        'user_id' => __('Created By User: %s'),
    ], ['separator' => ' / ']);
````

Would be for instance picked up automatically by `->find('list')`.

Do you think this would be worth to add?

**Edit 1: Adopted @dereuromark 's suggestion to use sprintf instead of implicit concat.**

**Comment by dereuromark** [comment]
Why is foo appended automatically?
I would expect to have `__('Record Name: %s')` and the %s placeholder is then replaced, that would allow also for  `__('%s Record Name')` etc.

As for the array for setDisplayField(): That is not supported and documented yet afaik.
It currently only supports a basic string.
If it was expected to be supporting arrays, we need to adjust the doc blocks here.

As for your enhancement:
I think this could be a valuable "localization" feature.
If this was PRed, I don't think there would be too much against having it.

**Comment by inoas** [comment]
I still have some unfinished PRs open, so again I cannot promise. I ll try to get to it sometimes this year.

**Comment by dereuromark** [comment]
We could also allow closures to format it any specific way.
Just a small note I wanted to add.

**Comment by inoas** [comment]
I had the same thought. I'd do one closure per setDisplayField/s call instead of one closure per field though.

**Comment by ADmad** [comment]
I don't think the extra complications in dealing with display field are necessary. You can just set 'displayField' to a virtual field `foo` and do whatever customization you want in `YourEntity::_getFoo()`.

**Comment by inoas** [comment]
I think you are right @ADmad. If you think otherwise @dereuromark let me know and I will reopen.

**Comment by ibrahima4477** [comment]
What about displayField with associated models?
