### ISSUE TITLE
customizable displayFields

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10174]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.13
* Platform and Target: not relevant

### What you did
-

### What happened
-

### What you expected to happen
There should be an easier way to configure alternate 'displayField' names, and not have them hard coded as 'name', 'title' or 'description'.

**Comment by ADmad** [comment]
You can already configure the display field using `Table:: displayField()`, what other alternative do you want?

**Comment by inoas** [comment]
s_he probably means the auto detection preferences through cake bake.

Related: I have been using `identifer` as a unique non-translated fields to identify records, however also having `title` alongside overwrite the auto detection even if identifer was set to be the primary key.

Reason is this:

```php
    public function displayField($key = null)
    {
        if ($key !== null) {
            $this->_displayField = $key;
        }
        if ($this->_displayField === null) {
            $schema = $this->schema();
            $primary = (array)$this->primaryKey();
            $this->_displayField = array_shift($primary);
            if ($schema->column('title')) {
                $this->_displayField = 'title';
            }
            if ($schema->column('name')) {
                $this->_displayField = 'name';
            }
        }
```

Ref: https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L543-L547

So the core still assumes a lot about display fields which it imho should not, or it should be configurable via `Configure::` / `app.php`

**Comment by dakota** [comment]
> So the core still assumes a lot about display fields which it imho should not, or it should be configurable 

I think the core is right to assume things. CakePHP is convention over configuration framework, and as such it expects and should expect certain conventions to be followed by the application. It still provides the ability to override the convention at any time.

**Comment by ADmad** [comment]
If you expect bake to ask the user display field name then please open an new issues on cakephp/bake. Closes as nothing needs to be done in the core.
