### ISSUE TITLE
How can i create foreign key in cakephp use migration?

### ISSUE THREAD

**Issue by at-tienpd** [cakephp/cakephp#10178]

**Comment by at-tienpd** [comment]
i work with cakephp 3.0

**Comment by markstory** [comment]
The [phinx documentation](http://docs.phinx.org/en/latest/migrations.html#working-with-foreign-keys) has an example of how to create a foreign key.

**Comment by at-tienpd** [comment]
i follow this document https://book.cakephp.org/3.0/en/migrations.html but i not found where is foreign key?

**Comment by markstory** [comment]
I linked you to the specific section in the phinx documentation. We don't reproduce the phinx docs as they would get out of date.
