### ISSUE TITLE
Add support for postgres foreign tables

### ISSUE THREAD

**Issue by plalanne** [cakephp/cakephp#10182]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.14
* Platform and Target: apache, Postgres 9.5.

### What you did
I try to use 2 differents postgres databases
on my server
```
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

CREATE SERVER new_server
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host 'localhost', port '5432', dbname 'db2');

CREATE USER MAPPING FOR user
    SERVER new_server
    OPTIONS (user 'user', password 'password');

CREATE FOREIGN TABLE new_series (
              id serial NOT NULL,
              nom character varying(200) NOT NULL
            )
            SERVER new_server
            OPTIONS (schema_name 'public', table_name 'series');
```

after this in pgadmin console, if i write 
```
select * from new_series; 
```
i have the result of the request with the data from db2

in cakephp, in my model series
`$this->table('new_series');`

### What happened
in th view series/index i have this error message
Cannot describe new_series. It has 0 columns. 

### What you expected to happen
i should have the list of the series

**Comment by markstory** [comment]
We don't support foreign tables right now.

**Comment by plalanne** [comment]
What a pity.
Ok i'm going to try to find another solution
Thanks

**Comment by lorenzo** [comment]
Interesting, the only reason you would get that message is because cake does not know how to reflect the schema by finding the table in `information_schema`. I wonder if that is easy to do
