### ISSUE TITLE
Cache.viewPrefix problem - always refreshes cache when you use Cache.viewPrefix in controller

### ISSUE THREAD

**Issue by romanjanowczyk** [cakephp/cakephp#10185]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4, 2.9.5
* Platform and Target: WIN10, Linux Ubuntu 16LTS
### What you did
I am trying to switch on cache on views (I have two themes: default and mobile and want to switch between them). 

### What happened
In controller after I set: Configure::write('Cache.viewPrefix', 'mobile'); I see that the view cache is always regenerated (see timestamp and cachetime inside the file). If I remove Configure::write('Cache.viewPrefix', 'mobile'); then the cache is stable.

```php
<?php
App::uses('AppController', 'Controller');
class RomansController extends AppController {
	public $helpers = array('Cache');	
	public $cacheAction = array(
		'index' => 86400*365
	);

	public function index() {
		$this->layout = 'ajax';
//		Configure::write('Cache.viewPrefix', 'mobile');
	}
}
```

View:
```php
<?php
echo date('Y-m-d H:i:s');
?>
```
### What you expected to happen
the cache will not be regenerated if I set Cache.viewPrefix dynamically.

**Comment by dereuromark** [comment]
Isn't the controller a bit too late?
I think if you want to set it dynamically, you will have to do it earlier, otherwise it won't be able to pick up the cache file as it doesn't know which prefix to use etc.
Are you using the CacheDispatcher or what will render the cached version out?

**Comment by romanjanowczyk** [comment]
The code I show is only example how to get the error. Generally I have to check which theme to switch on and only one place is beforeRender in AppController (because user can enter the page using different urls). I check if the request is from mobile if yes then I use the prefix for mobile if not than desktop. There is also different way to switch between themes via link (get with theme=mobile/desktop). I don't see any other place to do it. 

I use default CacheDispatcher:
```php
Configure::write('Dispatcher.filters',
	array(
	 'AssetDispatcher',
	 'CacheDispatcher'
));
```

**Comment by dereuromark** [comment]
Yeah, my point is: If you don't set up the prefix before the dispatcher is invoked it is only logical that the dispatcher cannot return the desired cache file, as without the prefix known it cannot find the file. 
Correct me if I am wrong, but since I was one the people implementing the prefix back in 1.3 days, I am fairly certain that was the catch using such a prefix.

**Comment by romanjanowczyk** [comment]
how to set up the prefix when I need to check first the device ? how to set the prefix when the user is switching theme it via url ? What in your opinion would be the best place ? 

What I see is cake writes cache for view but it doesn't check if it exists and if cachetime is in the feature.

**Comment by dereuromark** [comment]
I used the domain (e.g. prefix per subdomain or TLD), that way you can do it in a dispatcher filter before the Cache one. Either way, based on the URL schema sounds like it would be most appropriate.
But this is not a bug ticket IMO, and this should rather be part of IRC chat or forum discussion.

**Comment by markstory** [comment]
I'm with @dereuromark You are setting the prefix too late for it to be applied in the dispatch filter. You'll need to set it in either an earlier dispatch filter or as part of your bootstrap logic.
