### ISSUE TITLE
Marshalling belongsTo with null value returns error

### ISSUE THREAD

**Issue by Code-Working** [cakephp/cakephp#10184]
* CakePHP Version: 3.3.14
* Platform and Target: Ubuntu 16.04, MariaDB 10.0.29, PHP 7.0.13

This issue is similar to #7786.
I'm not sure if this is a bug or not. Maybe I understand something wrong here.

My model structure is like this:

    class AddressesTable extends Table {
        public function initialize(array $config) {
            $this->belongsTo('States', [
                'foreignKey' => 'state_id'
            ]);
            $this->belongsTo('Countries', [
                'foreignKey' => 'country_id'
            ]);
        }
    }

As you can imagine, not every country has states. Thus, `state_id` and also the respective association `state` can be null.

When I have an address in the USA, I'll have a state.  
However, when I'm changing the address to another Country where I don't have states (like Germany), I do the following (which is the same as loading another address from the database and do ->toArray() on it):

    $this->Addresses->patchEntity($address, [
            'country_id' => 1234,
            'country' => [
                'id' => 1234,
                'name' => 'Germany'
            ],
            'state_id' => null,
            'state' => null
        ], [
            'associated' => [
                'Countries' => [
                    'accessibleFields' => [
                        'id' => true
                    ]
                ],
                'States' => [
                    'accessibleFields' => [
                        'id' => true
                    ]
                ]
            ]
        ]);

With this code, CakePHP throws the error:

> Argument 2 passed to Cake\ORM\Marshaller::merge() must be of the type array

I followed through the code to check where the error happens and it seems to me that in [src/ORM/Marshaller.php, line 706](https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php#L706) the `$value` parameter is just passed through and not transformed into an array.

However, since `(array)$value` would create an empty array and therefore not remove the entity, I would add the code into the Marshaller::_mergeAssociation method:

    if ($value === null) {
        return $value;
    }

For me, this solution works. But, as I said before, I'm not sure if this is a bug or I'm just too stupid to update entities ;-)

**Comment by markstory** [comment]
I agree that the marshaller shouldn't emit an error in this situation. I'm not sure `null` will ever come across as post data, but `''` will and could cause similar issues.

**Comment by Code-Working** [comment]
The `null` will come across when you make a select box in the view, load an entity by it's ID  in the controller and patch this into another entity. Or simply hardcode it. Doesn't matter, it surely will come across ;-)

**Comment by robertpustulka** [comment]
I'm not sure that patching one entity by another entity is a good way to go. These entity factories are used to feed entities with user data and making sure the data is valid etc. Existing entities can as well be just set. Also you don't need to set FK and a property while saving associated records.

ie:
```php
$germany = $countries->get(1234);
$address->set('country', $germany);
$address->set('state', null);
```

IMO that is a correct way to go and the following issue is just a misuse of `patchEntity()` method.

**Comment by markstory** [comment]
@robertpustulka I think the marshaller shouldn't emit an error when it encounters a string/null where an association is expected though.

**Comment by markstory** [comment]
Pull request open.
