### ISSUE TITLE
Unexpected behaviour between Cache::clearGroup and cache sessions

### ISSUE THREAD

**Issue by irongomme** [cakephp/cakephp#10183]
This is a :

* [x] bug (or not ... ?)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.5
* Platform and Target: nginx/0.7.67, php 5.3.29, debian

I'm using CacheEngine for sessions (Redis backend) and memcached for website cache. When i call  Cache::clearGroup('mygroup') , it kills sessions. But when i call Cache::clearGroup('mygroup', 'nondefaultconfig'), it works as expected, sessions are not killed.

Is there anything to do to make it works without killing sessions ?

Here are my cache configs :

```
Cache::config('default', array(
    'engine' => 'Memcached',
    'servers' => array('127.0.0.1:11211'),
    'duration' => '+1 hour',
    'prefix' => 'default_',
    'groups' => array(Configure::read('Website.subdomain')),
));

Cache::config('sessions', array(
    'engine' => 'Redis',
    'duration' => '+1 day',
    'prefix' => 'sess_'
));
```

And my sessions config:

```
Configure::write('Session', array(
        'defaults' => 'cache',
        'handler' => array(
            'engine' => 'CacheSession',
            'model' => 'Session',
            'cache' => 'sessions',
        ),
        'cookie' => 'SESSID',
        'timeout' => 86400,
        'start' => true,
        'autoRegenerate' => false,
        'checkAgent' => false,
        'ini' => array(
            'session.use_cookies' => 1,
            'session.use_trans_sid' => 0
        )
    ));
```

**Comment by markstory** [comment]
That is not expected behavior at all. What do your session keys in redis look like?

You should also check that `sessions` is not in the output of `Cache::groupConfigs('mygroup')`

**Comment by irongomme** [comment]
Output of  ```Cache::groupConfigs('mygroup')``` give me : 

```
array(
	'mygroup' => array(
		(int) 0 => 'default',
		(int) 1 => 'long',
		(int) 2 => 'medium',
		(int) 3 => 'micro',
		(int) 4 => 'short',
		(int) 5 => 'tiny'
	)
)
```

So everything's normal that side.

But, after browsing the Model/Datasource/Session/CacheSession.php, I've found i was wrong in my Session config. Because it must be ```Session.handler.config``` instead of ```Session.handler.cache```.
With that fix applied in my config, everything is OK !
