### ISSUE TITLE
Form postLink is not working on latest chrome and firefox

### ISSUE THREAD

**Issue by johnlanz** [cakephp/cakephp#10189]
Hi,

I can't delete the record anymore on the latest chrome and firefox.
This is the error on browser console: TypeError: document.post_589c1f5bc029c823966334.submit is not a function

For immediate fix I've extend the Form Helper and change this line:
$onClick = 'document.' . $formName . '.submit();'; to
$onClick = 'document.forms["' . $formName . '"].submit();';
this will generate: document.forms[formname].submit()

But it will be great if you use id instead of name and generate something like this: document.getElementById("myForm").submit();

Thanks

**Comment by markstory** [comment]
I didn't see errors in Firefox 51 or Chrome 56 on OSX. While I'm not against changing the code, I'm not able to reproduce this issue.

**Comment by johnlanz** [comment]
You're right sorry for that. It only happens to me since I'm using stacktable.js. The Form get's duplicated that is why document.formname.submit is not working.

**Comment by allanmcarvalho** [comment]
I had this same problem when using Chrome - 68.0.3440.106, but only on Windows 10.. On OS X it works. I'm using they on ajax response with many postLinks.
