### ISSUE TITLE
Hash::get throws an exception with empty $path argument

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10196]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.5
* Platform and Target: Linux, Apache, MySQL.

### What you did
After the update from 2.8.9 to 2.9.5 we started to get exceptions when `$this->Auth->logout();` is called:
```
InvalidArgumentException: Invalid Parameter , should be dot separated path or array.

/.../Cake/Utility/Hash.php:53
/.../Cake/Model/Datasource/CakeSession.php:240
/.../Cake/Model/Datasource/CakeSession.php:275
/.../Cake/Controller/Component/SessionComponent.php:82
/.../Cake/Controller/Component/AuthComponent.php:648
/.../Controller/Component/MyComponent.php:373
```

### What happened
Exceptions in unit tests.

### What you expected to happen
Logout without any exceptions.

**Comment by markstory** [comment]
Previously the code did the wrong thing, and stricter parameter validation was added in way back in 2.6.0 (#3754). I'm not sure why you're starting to see this now.

**Comment by bancer** [comment]
It seems that this [commit](https://github.com/cakephp/cakephp/commit/816801902eb30d5a44ca1580e17df7f27acb30d4#diff-7241922c6a7f81443699ebbafb34e9d6) is related. It seems that removing `empty($data)` check allows not only an empty string to be the session key but `false` value too. And there is no check against `false` in Hash::get(). F.ex., `CakeSession::write(false, 'some value');` succeeds but `Hash::get(array(false => 'somevalue'), false);` throws an exception.

**Comment by markstory** [comment]
Cool, I'll see what I can uncover from there.

**Comment by markstory** [comment]
Closing as a pull request is open now.
