### ISSUE TITLE
[RFC] Make EventManager chainable.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#10195]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.0

Currently `EventManager::on()`, `::off()` methods return `void`.

I think it would be nice to have these methods chainable.
```php
$foo->eventManager()
    ->on('foo', function(){})
    ->off($bar)
    ->on($baz);

**Comment by lorenzo** [comment]
makes sense to me

**Comment by robertpustulka** [comment]
I can handle a PR.

**Comment by HavokInspiration** [comment]
@robertpustulka You can self-assign :)

**Comment by dereuromark** [comment]
Or just consider yourself assigned :)

**Comment by robertpustulka** [comment]
@HavokInspiration I'm afraid I don't have the ability to assign users, milestones etc.

**Comment by markstory** [comment]
Moving to 3.5. as I plan on doing the 3.4 release this weekend if all goes well.

**Comment by robertpustulka** [comment]
PR is open
