### ISSUE TITLE
Unit tests fail after upgrade to 3.4.0 due to strict classname check in associations

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#10208]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0
* Platform and Target: Travis, see https://travis-ci.org/CakeDC/users/jobs/201098181

### What you did
Upgrade to CakePHP 3.4.0

### What happened
Associations require classname matching exactly, making unit tests to fail when a mocked table is used, for example here https://travis-ci.org/CakeDC/users/jobs/201098181#L383 with the following error "Invalid Table retrieved from a registry. Requested: CakeDC\Users\Model\Table\UsersTable, got: Mock_UsersTable_5871e7e3"

### What you expected to happen
Associations retrieved correctly for the matching table class AND mock objects / extending classes

**Comment by robertpustulka** [comment]
@steinkel Can you manually set target table to the mock in that test?

**Comment by steinkel** [comment]
Yes I can fix it re-binding the associations to match the mock classes, but it feels wrong to me if we need to do it per test to allow mocked tables work...

**Comment by stefanniedermaier** [comment]
i get the same error in a Shell
````
$this->Videos = TableRegistry::get('Plugin.Videos');
...
$item = $this->Videos->newEntity($data);
$this->Videos->save($item)
````
while patchEntity() works well, the save operation throws an exception
````
Exception: Invalid Table retrieved from a registry. Requested: Plugin\Model\Table\videosTable, got: MusicRadar\Model\Table\VideosTable in [.../vendor/cakephp/cakephp/src/ORM/Association.php, line 418]
````

**Comment by robertpustulka** [comment]
@stefanniedermaier does your `MusicRadar\Model\Table\VideosTable` extend `Plugin\Model\Table\videosTable` ?


I was somewhat expecting this to happen. The issue should come from incorrectly configured associations, so it's the first thing to look for. Another thing is the issue with mocks. I'm wondering if we should make this check less strict (`instanceof` instead of `===`).

**Comment by stefanniedermaier** [comment]
Sorry, forgot to change the Plugin-Name to "Plugin" in this place, it's one and the same Class except "v" and "V"

**Comment by robertpustulka** [comment]
@stefanniedermaier OK thanks. I can fix that issue. PHP classes are case insensitive.

I'm still not sure what to do with extended classes. If you specifically tell an association to get `Foo.Bar` it shouldn't use it's parent or a descendant IMO.

**Comment by markstory** [comment]
This looks like it was caused by #10154

**Comment by robertpustulka** [comment]
@markstory right, but still I believe that emitting this error early is a good thing and I wouldn't like to revert that change. I'm just thinking about making it less strict and allow descendants to be retrieved from a locator.

**Comment by markstory** [comment]
Including descendants makes sense.

**Comment by robertpustulka** [comment]
@steinkel please check if #10231 has fixed your issue.

**Comment by steinkel** [comment]
yes, it fixed the issue with the mocks, thank you @robertpustulka
