### ISSUE TITLE
CSRF token not generated when i just upgrading to v3.3.15 

### ISSUE THREAD

**Issue by okaprinarjaya** [cakephp/cakephp#10206]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.15.
* Platform and Target: Apache 2, MySQL, PHP 5.6, Linux CentOS 6

### What you did
Upgrading to 3.3.15 , from 3.3.14

### What happened
I use Csrf component, but, CSRF token cannot generated when build form using Form helper `$this->Form->create()` . Hidden input field that contain csrf token value is token

### What you expected to happen
I want CSRF token can be generated again

**Comment by markstory** [comment]
How can someone reproduce the issue you're seeing? What does your form look like? What does the effected controller action look like?
