### ISSUE TITLE
missing   Cake\ORM\Association\BelongsToMany::setJoinTable($joinTable)

### ISSUE THREAD

**Issue by arusinowski** [cakephp/cakephp#10209]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0.
* Platform and Target: php 7.0.11

### What you did
I tried to use `Cake\ORM\Association\BelongsToMany::setJoinTable($joinTable)` when defining BelongsToMany association.

### What happened
There is no `setJoinTable` method in `Cake\ORM\Association\BelongsToMany` class. Cake book suggest [here](https://book.cakephp.org/3.0/en/orm/associations.html#belongstomany-associations) that i can define relationship 
```php
// In src/Model/Table/ArticlesTable.php
class ArticlesTable extends Table
{

    public function initialize(array $config)
    {
        $this->belongsToMany('Tags')
            ->setJoinTable('articles_tags');
    }
}
```

There is also no `Cake\ORM\Association\BelongsToMany::getJoinTable()`.

### What you expected to happen
I expected to have properly defined relationship (belongs to many).

**Comment by markstory** [comment]
The documentation is incorrect, there is no `setJoinTable` method in 3.4.0. I'll get the documentation updated.

**Comment by inoas** [comment]
For 3.4.1 there could be? When there is `setForeignKey` and `setBindingKey` etc.

**Comment by markstory** [comment]
@inoas Probably more like 3.5.0, as that is when we'd merge in another round of ORM deprecations.

**Comment by markstory** [comment]
Documentation pull request up now.
