### ISSUE TITLE
continuous memory increase (until crash) while foreach'ing over a find()

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10214]
This is a (multiple allowed):

* [x] bug ?
* [x] enhancement ?
* [x] feature-discussion (RFC) ?

* CakePHP Version: 3.3.14
* Platform and Target: not relevant

### What you did

    $myfind = $table->find();
    foreach($myfind as $row) {
        //...
    }

(debug off, debugkit off)

### What happened

On every iteration the amount of memory used increased (as reported by `memory_get_usage(true)`. The behavior ended by crashing the app (after ~30k records)

### What you expected to happen

A stable memory usage.

I ended up doing `find()->limit()->offset()`, so as to process al the records in bunches. This stabilized the memory usage.

I don't know if its possible incorporate this behavior directly in the iterator (?).

Maybe a test on a `while( pg_fetch_row() )` (or alike) could shed light if increasing memory usage should be expected...

**Comment by lorenzo** [comment]
This is expected, the results are kept in memory until they are iterated in their entirety. That's the purpose of `$query->bufferResults(false)`, to only keep one row in memory as you iterate over the results.

If I remember correctly, the problem is worse with postgres, as there is no way to avoid php buffering all results in memory, even when using `bufferResults(false)`.

**Comment by lorenzo** [comment]
You are welcome to try wit `bufferResults(false)` and report whether this fixes your problem in postgres or not, at least what it will do is to not keep a cache of the results in the cake memory as you iterate, so the memory consumption should definitely be lower

**Comment by robertpustulka** [comment]
AFAIR `bufferResults` does not work with joins (or only with "many" joins).

I've been working on a behavior that split queries into many queries with configurable amount of records and return "streamable" result set. That would lower the memory consuption. 

I may release it as a plugin as I'm about to revisit that behavior while working on my current project.

**Comment by lorenzo** [comment]
It does work with joins, but it does not work with associations that requires doing a second select (hasMany, belongsToMany).

There is a somewhat easy way to workaround that issue, which is configuring associations that use a second database connection.
