### ISSUE TITLE
3.4 Responses not working, possibly Middleware-related

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#10210]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: PHP 5.6.25

### What you did
A script I have that uses a custom CorsMiddleware, which looks like this, is suddenly as of 3.4 throwing an error.
```
$cakeRequest = RequestTransformer::toCake($request);
$cakeResponse = ResponseTransformer::toCake($response);

$origin = $request->getHeaderLine('Origin');
if (!$origin) {
    return $next($request, $response);
}
$cors = $cakeResponse
    ->cors($cakeRequest)
    ->allowOrigin(['http://' . env('HTTP_HOST'), 'https://' . env('HTTP_HOST')])
    ->allowMethods(['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS'])
    ->allowHeaders([
        'x-csrf-token',
        'Keep-Alive',
        'User-Agent',
        'X-Requested-With',
        'If-Modified-Since',
        'Cache-Control',
        'Content-Type',
        'Accept',
        'Authorization',
    ])
    ->allowCredentials();
if ($cakeRequest->is('options')) {
    $cors->maxAge(172800);
}
$cors->build();
$response = ResponseTransformer::toPsr($cakeResponse);

if ($cakeRequest->is('options')) {
    return $response;
}
return $next($request, $response);
```

### What happened
``
Catchable fatal error: Argument 2 passed to Cake\Http\ActionDispatcher::dispatch() must be an instance of Cake\Http\Response, instance of Zend\Diactoros\Response given, called in /vendor/cakephp/cakephp/src/Http/BaseApplication.php on line 78 and defined in /vendor/cakephp/cakephp/src/Http/ActionDispatcher.php on line 73
``

### What you expected to happen
I'm downgrading to 3.3 for now, but what's wrong with my script? I was looking in the docs and I can't see any obvious changes to the CorsBuilder or Middleware. Without CORS the response is fine (although obviously the site doesn't work without CORS - just that the normal response returns what it should).

Thanks

**Comment by markstory** [comment]
You shouldn't need to use the `ResponseTransformer` anymore. It was always an internal class that was not intended to be used.

**Comment by patrickconroy** [comment]
Hm, does that mean Middleware classes shouldn't do stuff like my CorsMiddleware? Does my `__invoke` have to create a new CakeRequest, use the CorsBuilder on that, extract the headers and apply them to the Psr/ResponseInterface? I have a few other classes that do stuff like this immediately in `__invoke` so I can do stuff within the framework e.g.
```
$cakeRequest = RequestTransformer::toCake($request);
$cakeRequest->addDetector(
    'ssl',
    function ($cakeRequest) {
        return strtolower(env('https')) === 'on';
    }
);
```
Am I just using Middleware wrong?

**Comment by markstory** [comment]
No your middleware is fine. The problem is that you are using old CakePHP internal bits that convert Cake responses into Diactoros implementations which is no longer necessary. As of 3.4.0, the transformers are no longer necessary/used, and they shouldn't have been used by userland code in the past either as they were 'internal' classes.

If you remove usage of both transformers, I would expect your code to work. In 3.4.0, the CakePHP request/response *are* PSR-7 implementations.

**Comment by patrickconroy** [comment]
Ah thanks that makes sense. I removed those references and this is working as expected now.
