### ISSUE TITLE
3.4.0 changed the way ExceptionRenderer behaves in some circumnstances

### ISSUE THREAD

**Issue by fquffio** [cakephp/cakephp#10217]
This is a (multiple allowed):

* bug

* CakePHP Version: 3.4.0.
* Platform and Target: PHP versions 5.6.28, 7.0.13 and 7.1.0, CLI environment (unit tests).

### What you did
If a layout path is set for Error controller's view, it is not reset in the `Cake\Error\ExceptionRenderer::_outputMessageSafe()` method as it used to be before CakePHP v. 3.4.0. In a project that uses CakePHP we have this unit test that used to pass before upgrading to 3.4:

```php
$renderer = new ExceptionRenderer(new NotFoundException('test html'));
$renderer->controller->request->env('HTTP_ACCEPT', 'text/html');

$renderer->controller->eventManager()->on('Controller.beforeRender', function (Event $event) {
    // force missing layout exception
    $event->getSubject()->viewBuilder()->setLayout('find_me_if_you_can');
});

$response = $renderer->render();

static::assertEquals('', $renderer->controller->viewBuilder()->getLayout());
```

### What happened
An exception is thrown with message: `Layout file "Layout/find_me_if_you_can/html.ctp" is missing.` This is because `ExceptionRenderer::_outputMessageSafe()` doesn't reset `layoutPath` anymore.

### What you expected to happen
Things continue to work as before.

### Additional notes
This is probably a (very minor) regression introduced by 56200bb (to be specific, [this line](https://github.com/cakephp/cakephp/commit/56200bb5933d743c6103f78a755f50faa117a96a#diff-a4e786a969380a71b2863878c6d7512fR355)) when massively updating from old combined getter/setters to new distinct methods.

**Comment by ADmad** [comment]
Closing as related PR is open.
