### ISSUE TITLE
jsonSerialize() and JSON.parse()

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10212]
This is a (multiple allowed):

* [x] bug ?
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.14
* Platform and Target: Firefox Developer (though uninportant)

### What you did
in the controller:

    $myArray = $Model->find()->....->jsonSerialize();
    $this->set(compact('myArray'))

in the view:

    <script>
    var myArray = JSON.parse('<?= json_encode($myArray) ?>');
    </script>

### What happened

Sometimes it works, BUT if the array has an apostrophe character it fails with the error:

    SyntaxError: missing ) after argument list

So to fix the error, in the view I do:

    ....
    <script>
    var myArray = JSON.parse('<?= str_replace("'",'\u0027', json_encode($myArray)) ?>');
    </script>
   

### What you expected to happen

That with jsonSerialize() I would obtain a parseable array

**Comment by markstory** [comment]
You're not supposed to directly call `jsonSerialize()`. Instead PHP invokes it for you when an object is passed into `json_encode()`.

**Comment by siran** [comment]
The same thing happens when it is invoked directly by cakephp: the issue here is that `'` is not being encoded as `\u0027`, so JSON.parse() complains... 

For example, cakephp does encode `Á` as `\u00c1`, why doesn't it encode the `'` ?

Or equivalently, why does JSON.parse() work perfectly when I explicitly replace `str_replace("'",'\u0027', json_encode($myArray))`  ($myArray is a cakephp find()) ?

**Comment by markstory** [comment]
If you `json_encode(['key' => "'"])` do you get the expected results?

**Comment by siran** [comment]
No. Firefox complains Firefox complains giving me `SyntaxError: missing ) after argument list`. Also Chrome.

I tried your suggestion in my view: `var test = JSON.parse('<?= json_encode(["'test string'"]);?>');`

**Comment by markstory** [comment]
> Are there any downsides to encoding the quotations ?

Not in an HTML context, but in `jsonSerialize()` is also used when making JSON responses. Thus we cannot escape quotes by default. You are missing an `h()` call in your HTML/javascript code.
