### ISSUE TITLE
Fixtures and UUID primary key bug

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#10225]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0

### What you did
Fixture 'plugin.data.postal_codes' and
```php
	public function testBasicSave() {
		$entity = $this->PostalCodes->newEntity(['code' => '81222']);
		$this->assertEmpty($entity->errors());
		$result = $this->PostalCodes->save($entity);
		$this->assertNotEmpty($result);
	}
```

And fixture is:
```php
	public $fields = [
		'id' => ['type' => 'string', 'null' => false, 'default' => null, 'length' => 36],
		'code' => ['type' => 'string', 'null' => false, 'default' => null, 'length' => 5],
		'created' => ['type' => 'datetime', 'null' => true, 'default' => null, 'collate' => null],
		'modified' => ['type' => 'datetime', 'null' => true, 'default' => null, 'collate' => null],
		'_constraints' => ['primary' => ['type' => 'primary', 'columns' => ['id']]],
		'_options' => []
	];
```

### What happened
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: postal_codes.id

### What you expected to happen
A save like this should insert a primary key here, and no exception should happen.

**Comment by markstory** [comment]
The type in your fixture's 'id' field should be `uuid` not `string`.

**Comment by dereuromark** [comment]
Darn, that was stupid of me not to think of this. Thanks.
