### ISSUE TITLE
Prefixed route not matched in unit tests after upgrade to 3.4.0 

### ISSUE THREAD

**Issue by DanielPenkov** [cakephp/cakephp#10220]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0

### What you did
Updated from Cake 3.3.14 to 3.4.

### What happened
Prefixed route not matched in unit test when using `InflectedRoute`

### Additional information

After updating from Cake 3.3.14 to 3.4. have a problem with using prefixed routes inside unit tests. If I debug Router::routes() in the test case I can see the correct route, but it is not matched. If I change default route class from `InflectedRoute ` to `DashedRoute` everything works fine.  

routes and testCase class : https://gist.github.com/DanielPenkov/0760e2ffa1aa75664003d6c7e781ebf9

**Comment by markstory** [comment]
Thanks for the test case, I'll take a look.

**Comment by markstory** [comment]
Closing as a pull request is open now.
