### ISSUE TITLE
ORM cannot describe Postgresql's Materialized View 

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#10238]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.3.14.
* Platform and Target: Postgresql 9.4.

I have a huge database that is basically read-only and I have some complex queries that I execute a lot. Because of that, I created materialized views with those queries, since I don't have to update the view (since database is almost read only).

The thing is that while Cakephp's ORM works fine with a common view, it doesn't work on a materialized view.

It can be worked around by creating a view of the materialized view, since postgresql will use the materialized view's indexes anyway.

**Comment by lorenzo** [comment]
Would you like helping to get this done? I would love to have this feature as well

**Comment by markstory** [comment]
Related to #10182

**Comment by alysson-azevedo** [comment]
I think I can help. This weekend i'll check the source code.

**Comment by lorenzo** [comment]
@alysson-azevedo thanks! let me know if you need help navigating the source code

**Comment by alysson-azevedo** [comment]
So, I think this can't be fixed, since Schema\Collection rely on the `information_schema.columns` view to describe things.

See [this thread](https://www.postgresql.org/message-id/3794.1412980686%40sss.pgh.pa.us):

> > I've been testing out some of the new materialized view functionality
> > in 9.4 and noticed that they don't show up in the information_schema
> > data dictionary views, specifically information_schema.tables or
> > information_schema.views (sample output is below and it's the same for
> > 9.3 as well).

> > Is this on purpose or just an oversight?

> It's on purpose.  The information_schema can only show objects that
> exist in the SQL standard.

I don't think it's worth to change the way things work now.
What do you guys think?

**Comment by ADmad** [comment]
You could explicitly specify the schema info using `Table::_initializeSchema()` ?

**Comment by alysson-azevedo** [comment]
Maybe. But what I did was create a view of the materialized view. 
information_schema works fine with standard views.
