### ISSUE TITLE
Extend available TLS encrypt methods in CakeSocket

### ISSUE THREAD

**Issue by m-stramek** [cakephp/cakephp#10230]
* [x ] enhancement

* CakePHP Version: aa8d708b9ad6e699d705c586d68dcd012245d759

The list of available encryption methods should be extended with two new ones: TLSv1_1 and TLSv1_2. Moreover there should be possibility to choose custom TLS version by config option.

**Comment by markstory** [comment]
Closing as a pull request is open now.
