### ISSUE TITLE
RadioWidget Label attributes should indicate which button is selected.

### ISSUE THREAD

**Issue by dwightnetzango** [cakephp/cakephp#10235]
The Radio widget renders multiple label - inputs for each field.  One for each of the options.

In the RadioWidget->_renderInput method, it identifies if each individual input should be having the active value, however, there is nothing to tell the label that that label is for a an input that is the current value.

This is a very easy, one line fix which allows radio boxes to be rendered as pretty boxes using 
   Button.prototype.toggle inside bootstrap.js 
```
        if (isset($data['val']) && (string)$data['val'] === (string)$radio['value']) {
            $radio['checked'] = true;
            $radio['templateVars']['activeClass'] = "active";// new line
        }

```

**Comment by dereuromark** [comment]
@dwightnetzango Are you able to provide a PR with your suggested enhancements?

**Comment by markstory** [comment]
Closing as there is a pull request open now.
