### ISSUE TITLE
Remove belongsTo query limitation

### ISSUE THREAD

**Issue by fheider** [cakephp/cakephp#10249]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0

https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#eager-loading-associations
> For BelongsTo and HasOne associations only the where and select clauses are used when loading the associated records. For the rest of the association types you can use every clause that the query object provides.

I don't know why you had this limition, but it would be great to remove this. I want to use an additional join and couldn't use it. But the selected fields were selected. So there is an error, because the join table is missing.

E.g.
orders and order positions

```
// OrdersTable.php

[...]

public function findAll (Query $query, array $options)
    {
        $query
            ->join([
                'o' => [
                    'table' => TableRegistry::get('OrderPositions')
                        ->find()
                        ->select([
                            'id' => 'OrderPositions.order_id',
                            'grand_total' => 'SUM(price)'
                        ])
                        ->group([
                            'OrderPositions.order_id'
                        ]),
                    'type' => 'LEFT',
                    'conditions' => 'Orders.id = o.id'
                ]
            ])
            ->select([
                $this->getAlias() . '__grand_total' => 'IFNULL(o.grand_total, 0)'
            ])
            ->enableAutoFields(true);
        return $query;
    }

[...]

```

```
// OrderPositionsTable.php

[...]
$this->belongsTo('Orders');
[...]

```

`TableRegistry::get('Orders')->find()->first()->grand_total`

No problem, grand_total is selected.

`TableRegistry::get('OrderPositions')->find()->contain(['Orders'])->first()->order->grand_total;`

Error: o.grand_total not found (cause of the missing join)

In SQL this isn't a problem. It's only the limitation of cakephp. A virtual property isn't a possibility, because i can't use it in any having clause, e.g. find all orders with grand_total > 20.

**Comment by lorenzo** [comment]
There are 2 ways you can remove this limitation yourself. The first one is using the `select` strategy for the association.

The second solution is to load more associations instead of doing a manual join. The restriction needs to be there, as it is quite difficult to manage joins when using the `join` strategy for those 2 types of associations.

Give that the limitation only exists for one of the strategies, and that there is a simple way to achieve what you need, I'm closing this ticket. Please report back if you need clarification on this comment or if you still think there is something that needs to be changed in the core.

**Comment by fheider** [comment]
The solution with a subquery is inefficient and i can't filter (price <> grand_total e.g.).
I don't think so, that this restriction is neccessary or making something difficult for belongsTo associations because it's only another join to the belongsTo-join.
