### ISSUE TITLE
$options['association'] in beforeMarshal

### ISSUE THREAD

**Issue by andrej-griniuk** [cakephp/cakephp#10247]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.0

Looks like $options['association'] is not getting passed to berforeMarshal since ~3.2. Couldn't find any mentions of it in changelogs. Am I missing something or it's quite a big and breaking change?

**Comment by markstory** [comment]
Where did this key used to come from? I don't recall it ever being an option we intentionally passed.

**Comment by andrej-griniuk** [comment]
https://github.com/cakephp/cakephp/commit/4d1e37cefedba333507a34a73a8d8d44d461fecf#diff-5f10932ebc4aec6360e17657419d5e66L79

And below in this commit

**Comment by markstory** [comment]
Thank you. That is indeed a mistake. I'll get that fixed.

**Comment by markstory** [comment]
Pull request up now.
