### ISSUE TITLE
debug() doesn't shows white spaces inside strings

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#10245]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.15

### What you did
Used `debug()` on a variable witch was a `string ' ' (length=1)`

### What happened
debug showed `''`

### What you expected to happen
debug shows `' '`

I admit that this is a very strong edge case, but it drove me nuts today, when I was debugging some stuff.
Can we change line 461 `Debugger::_export()` to:

```
if (trim($var) === '' && ctype_space($var) === false) {
     return "''";
}
```

**Comment by thinkingmedia** [comment]
What browser were you using?

**Comment by cleptric** [comment]
Chrome, Safari and Firefox on macOS 10.12

**Comment by cleptric** [comment]
Can also confirm this on Windows, too.

**Comment by markstory** [comment]
Could you put together a pull request with the change you think should be made.
