### ISSUE TITLE
Request::getQuery() cannot get full query.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10256]
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.0
* Platform and Target: Apache2, MySQL 5,7, PHP 7.1.1

### What you did

In 3.3 you could get the entire request query.

```
   var_dump($this->request->query());
```

### What happened

Doing the same in 3.4 yields `null`

```
   var_dump($this->request->getQuery());
```

Looks like there was some oversight on updating to getters and setters.

- ServerRequest::query() is deprecated, but it did not follow the pattern of duel getter/setter arguments for the other deprecated methods (i.e. you can not set values with this method)
- ServerRequest::query(null) returns the enture query.
- ServerRequest::getQuery() does not support null parameter.
- some deprecated messages refer to setQuery and withQuery, but those methods do not exist.

If this RFC is valid, then let me know and I'll open a PR to fix the above.

**Comment by markstory** [comment]
You are supposed to use `getQueryParams()` to get all the query data.

**Comment by chinpei215** [comment]
@markstory Feels asymmetrical to me. Since the `getQueryParams()` allows people to retrieve all query parameters, the `getQuery()` doesn't do that. I understand that now. However, despite of the fact that the `getParsedBody()` allows people o retrieve all posted data, the `getData()` also does that.

**Comment by markstory** [comment]
@chinpei215 Good point. I can change getQuery() to match getData().

**Comment by chinpei215** [comment]
@markstory Thank you.

**Comment by thinkingmedia** [comment]
@markstory if you're busy I can do it.

**Comment by markstory** [comment]
@thinkingmedia Thanks! if you can take care of this that would be great.

**Comment by thinkingmedia** [comment]
@markstory I see what happen `getQueryParam()` is part of the PSR-7 interface for requests, and we had `getQuery` which supports our dot string lookup using hash. This creates a little confusion for developers who see two different methods.

Anyway, I'll fix getData to return all data and add notes to the comments to explain what's going on.

**Comment by dereuromark** [comment]
> getData to return all data and add notes

was't the issue the other way around? "can change getQuery() to match getData()."
Meaning getQuery() should be able to return all with null argument.

**Comment by thinkingmedia** [comment]
@dereuromark sorry, that was a type-o

Yeah, this is a very small fix. Mostly I'm updating the comments. PR will be up soon.
