### ISSUE TITLE
CakePHP 3.4.1 new installation model bake showing derecated method

### ISSUE THREAD

**Issue by mdmamunhasan** [cakephp/cakephp#10258]
$this->table('users');
$this->displayField('name');
$this->primaryKey('id');

**Comment by dereuromark** [comment]
These kind of tickets should be opened in https://github.com/cakephp/bake instead.

**Comment by inoas** [comment]
I think there is a lot that can be done for the default bake templates and layout such as new setters/getters, schema constraint detection, schema foreign key/assoc detection, singular/plural convention switching for tablenames and foreign keys, frontend content and presentation decoupling, div/class soup clearing, mobile first, async js belongsTo lookup, unobstrusive xhr delete confirms, etc... to improve it as a RAD/XP tool before adding search to it, but thats just my 2 cents

**Comment by markstory** [comment]
This issue was moved to cakephp/bake#310
