### ISSUE TITLE
Please add search form with grid view to compete with Yii framework when bake 

### ISSUE THREAD

**Issue by mdmamunhasan** [cakephp/cakephp#10259]
Please add search form with grid view to compete with Yii framework when bake. This is an awesome feature.

**Comment by eather009** [comment]
I am actually working for search form for one of my project. Hope it will be given with Cake when bake or may be we can do it for Cakephp :)

**Comment by dereuromark** [comment]
Please see https://github.com/FriendsOfCake/search for a perfectly fine solution as opt-in already.

**Comment by inoas** [comment]
I think there is a lot that can be done for the default bake templates and layout such as new setters/getters, schema constraint detection, schema foreign key/assoc detection, singular/plural convention switching for tablenames and foreign keys, frontend content and presentation decoupling, div/class soup clearing, mobile first, async js belongsTo lookup, unobstrusive xhr delete confirms, etc... to improve it as a RAD/XP tool before adding search to it, but thats just my 2 cents

**Comment by thinkingmedia** [comment]
It is not clear what the RFC is about. Please refrain from using issues for broad discussions. We have a template for opening RFCs.
