### ISSUE TITLE
[RFC] BaseAuthenticate updates

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#10263]
This is a:
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.1
* Platform and Target: PHP 7.0.15, Nginx 1.10.3, MySQL 5.7.17

# Creating custom authenticators
I created my own authentication class by extending the `BaseAuthenticate` class.

# PSR7 confusion
Why do the methods in this class have mixed request and response object instances?
[The best method example is here](https://github.com/cakephp/cakephp/blob/master/src/Auth/BaseAuthenticate.php#L222-L228).

```php
 /*
 * // etc
 * @param \Cake\Http\ServerRequest $request A request object.
 * @param \Cake\Network\Response $response A response object.
 * @return void
 */
public function unauthenticated(ServerRequest $request, Response $response)
{
}
```

This method now takes a PSR7 compatible request and a Cake network response object, instead of a PSR7 response.

# Respect the D
Another thing I noticed is that this class doesn't [respect the D in SOLID](https://en.wikipedia.org/wiki/Dependency_inversion_principle). By this I mean that this class should be type hinting against request and response interfaces `Psr\Http\Message\ServerRequestInterface` and `Psr\Http\Message\ResponseInterface`, rather than relying on a concrete implementation of the CakePHP Request and/or Response class.

# RFC
I'd like to get thoughts and comments on these two proposals to see which parts can be updated through a pull request.

Additionally to get input on if there are any potential backwards compatibility breaks which might occur if this proposed RFC was actioned.

Thanks for reading :gift_heart:

**Comment by dereuromark** [comment]
Isn't that solved with https://github.com/cakephp/authentication for future CakePHP versions?
To me the Base class and others here you mentioned seem to be deprecated then anyway.

**Comment by ADmad** [comment]
As pointed out cakephp/authentication is meant to be the successor of existing AuthComponent and it's related classes. So modifying those classes at this point is not worth the effort.

**Comment by davidyell** [comment]
Ah yes, I had forgotten about that package. I wasn't aware it had reached a release yet though. I'll check it out.
