### ISSUE TITLE
Need to update readme.md (ORM) file

### ISSUE THREAD

**Issue by sohelrana820** [cakephp/cakephp#10265]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0
* Platform and Target: Apache2, MySQL 5,7, PHP 7.1.1

### What you did
I was trying to use only CakePHP ORM. But I found, config() method of ConnectionManager is deprecated in CakePHP 3.4.0.

### What happened
Getting deprecated warning, when I try to use ConnectionManager's config() method

### What you expected to happen
Need to modify the ORM's readme.md file. Accodding to CakePHP 3.4.0, need to replace ConnectionManager::config() with ConnectionManager::setConfig() in readme.md file

**Comment by ADmad** [comment]
Seems you have already updated the readme on your fork. Would you mind making a pull request for it?

**Comment by sohelrana820** [comment]
Sure, I am sending a pull request.
