### ISSUE TITLE
CakePHP 3.4.1 breaks test runs with PHPUnit 5.7

### ISSUE THREAD

**Issue by mamchenkov** [cakephp/cakephp#10260]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.1
* Platform and Target: TravisCI, PHPUnit 5.7.14, PHP 5.6, PHP 7.

### What you did

Triggered TravisCI test run of a project that is based on CakePHP v3.4.1 and uses PHPUnit 5.7.14.

### What happened

* CakePHP 3.4.1 allows for PHPUnit v5.7 or v6.0 to be used ([composer.json](https://github.com/cakephp/cakephp/blame/3.4.1/composer.json#L34)).
* PHPUnit 6 is a major upgrade, requiring PHP 7 ([composer.json](https://github.com/sebastianbergmann/phpunit/blob/6.0.0/composer.json#L23)), as well as a few other changes to the test suite.
* Our test suite has not yet been migrated to PHPUnit 6, so we locked it down to PHPUnit 5.
* With CakePHP 3.4.1 and PHPUnit 5.7.14 our test run fails.  See, for example, [this TravisCI run](https://travis-ci.org/QoboLtd/project-template-cakephp/jobs/203393983).  Particularly, lines [1599](https://travis-ci.org/QoboLtd/project-template-cakephp/jobs/203393983#L1599) and [1617](https://travis-ci.org/QoboLtd/project-template-cakephp/jobs/203393983#L1617).  We also have a few plugins which have the same issue, when requiring latest version of CakePHP 3 and PHPUnit 5 ([example](https://travis-ci.org/QoboLtd/cakephp-csv-migrations/jobs/203383013)).

The following error occurs (abbreviated for readability):

```
Exception: Argument 2 passed to Cake\TestSuite\Fixture\FixtureInjector::addWarning() 
must be an instance of PHPUnit\Framework\Warning, 
instance of PHPUnit_Framework_Warning given, 
called in vendor/phpunit/phpunit/src/Framework/TestResult.php on line 293 in
[vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php, line 108]
```

### What you expected to happen

The test suite run should finish normally, as before CakePHP 3.4.1.

### Notes

There is also PR #10257, aimed for CakePHP 3.4.2, which will help with troubleshooting.  But that's more of a debug information than an actual fix for the problem.  Also, it triggers for PHPUnit < 5.7, while the problem appears with PHPUnit 5.7.14.

As a temporary fix, locking CakePHP to v3.3+ helps.

**Comment by lorenzo** [comment]
Does the troubleshooting information help with fixing the problem?

**Comment by mamchenkov** [comment]
@lorenzo not really, as we run PHP 5.7.14, and the troubleshooting error from PR #10257 only triggers if the PHPUnit < 5.7 is used.  So for us it doesn't appear.

**Comment by mamchenkov** [comment]
Regardless, I think that if PHPUnit 5.7 is allowed, than it should work, which it currently doesn't.  PHPUnit 6 is the future, but with PHP 7 requirement, it should probably be pushed into CakePHP 4.

**Comment by lorenzo** [comment]
@mamchenkov yeah, our intention is to make it work with the two versions... still trying to get there, thanks for reporting that the other PR will not work correctly. /cc @antograssiot

**Comment by antograssiot** [comment]
@mamchenkov did you actually tried the branch because you should not hit the error... We are probably missing one alias here ?

**Comment by mamchenkov** [comment]
@antograssiot excellent point actually!  I haven't tried the branch itself, cause I saw the code snippet in the PR description.  But now that I look at the diff, the implementation is different.  We'll try the branch and let you know if it works (will update you in an hour or so).  Thanks!

**Comment by mamchenkov** [comment]
@antograssiot we tried the `phpunit` branch now and the error is still happening.  I think there is a missing class alias for `PHPUnit\Framework\Warning` on the `PHPUnit_Framework_Warning`.

**Comment by antograssiot** [comment]
@mamchenkov I've pushed another commit on top of the branch and I hope it will solve your issue.
Would you please give an another try to the phpunit branch. That would be awesome.

**Comment by thinkingmedia** [comment]
@mamchenkov I was getting the `PHPUnit\Framework\Warning` problem when I had a test file with no tests in it. Once I added test methods phpunit started working again.

**Comment by antograssiot** [comment]
awesome @thinkingmedia Thanks forgiving me a way to reproduce.
I've been able to check that #10257 did solve it.
Thanks for reporting @mamchenkov

**Comment by mamchenkov** [comment]
Hey guys, just to confirm, the updated phpunit branch works just fine (we tried with commit 53a575b9fa8f4698df8783a7b645b6132373c577).  Thanks a lot!  Hope to see v3.4.2 tagged soon :)
