### ISSUE TITLE
How to get data type date from database?

### ISSUE THREAD

**Issue by at-tienpham** [cakephp/cakephp#10268]
I have table Birthdays.
Birthdays fields: id | user_id | birthday (type date: y-m-d)
Data from url $_GET['date']  is '1991-09-10'
In BirthdaysController i have a query
`$arrayDate = $this->Birthday->find()->where(['birthday' => $_GET['date'] ])->all();`
but i want to find by format '1991-09'. 
Any help would be greatly appreciated.
Please help me!

**Comment by lorenzo** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
