### ISSUE TITLE
Extension validation not work with ServerRequest

### ISSUE THREAD

**Issue by dario86** [cakephp/cakephp#10267]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.1

I am using the extensions validation's rule but it seems that at the first element there is the "tmp_name" not the real "name" so the rule cannot read the extension. 
I noticed that the field order is changed here: https://github.com/cakephp/cakephp/blob/aed66faf38c6878b67878114901d129b336e4da8/src/Http/ServerRequest.php#L440-L449

**Comment by markstory** [comment]
How can someone reproduce the issue you're having?

**Comment by chronon** [comment]
I'm seeing this issue too after updating from v3.3.15 to v3.4.2, with `tmp_name` getting passed to `Validation::extension()` as the `$check` arg causing validation to fail. Quick and dirty way to reproduce: add a `debug($check)` [here](https://github.com/cakephp/cakephp/blob/3.4.2/src/Validation/Validation.php#L693) and upload a file with the rule enabled.

**Comment by markstory** [comment]
I gather that you are using the extension rule as a validator on a file upload field then? Assuming the first key will be the filename seems like a fragile assumption. I will make the method more robust.

**Comment by chronon** [comment]
Yes, on a file upload field as I did assume that was the intent of the validation rule (without really confirming though). I would think others would assume the same, and it did work as expected for file fields in 3.3.x. Thanks for looking into this.

**Comment by markstory** [comment]
Pull request up now.
