### ISSUE TITLE
3.X autoFields should not overwrite previously overwritten fields

### ISSUE THREAD

**Issue by elboletaire** [cakephp/cakephp#10279]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: >= 3.3.15
* Platform and Target: ORM

### What you did

For this case I've two tables: Centers->belongsTo->Cities. I've created a custom finder which returns the centers with the city code whenever it's present. This finder overwrites the `Centers.name` field, so instead of having names like `Balmes` now I have names like `(BCN) Balmes`.

To achieve this, what I've done is a custom expression in a finder:

~~~php
public function findWithCityCode(Query $query, array $options = [])
{
    $expression = $query->func()->if([
        $query->func()->length(['Cities.code' => 'identifier']),
        $query->func()->concat([
            '(',
            'Cities.code' => 'identifier',
            ')',
            ' ',
            'Centers.name' => 'identifier'
        ]),
        'Centers.name' => 'identifier'
    ]);
    return $query->contain(['Cities'])->select(['name' => $expression]);
}
~~~

### What happened

Everything works fine, but due to the `select` with just one field (`name`) the results come with just that field. Adding `autoFields(true)` before or after the `select(['name' => $expression])` re-rewrites the field and sets the `name` field to its default param.

### What you expected to happen

Discuss about adding an additional param to `autoFields` to avoid rewriting previously rewritten fields, or directly not rewrite previously rewritten fields (without any extra param).

**Comment by markstory** [comment]
How would you ideally want to express autoFields + custom fields to the orm?

**Comment by elboletaire** [comment]
I don't really know all the internals of the ORM, so I'm not sure if I'm gonna say something stupid.

Could it be possible to store changes to fields (like the one I've made with the expression in the `select`) so we can then not rewrite these fields using `autoFields`?

I mean, save something like an array of the field names saving if they have been modified or not, imagine something like:

~~~php
[
    'name' => false,
    'description' => false,
    [...]
]
~~~

for an entity. If we then use `select(['name' => 'whatever'])` change the flag to `true` as it has been modified:

~~~php
[
    'name' => true,
    'description' => false,
    [...]
]
~~~

Then autofields could ignore overwriting that field, as it has been previously flagged as changed.

As said, I'm not still very aware on how the ORM works, so I could be saying something stupid.
