### ISSUE TITLE
Allow newline in Confirm Messages was fixed uncorrectly

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#10274]
* [x] bug

* CakePHP Version: 3.4

Please check issue #8038 or better my comments for commit 9a8b0ec

https://github.com/cakephp/cakephp/commit/9a8b0eccc0fa6bff21ca3e28cb1e32269e21e108

**Comment by cleptric** [comment]
@Manuel1948 Could you please open a PR with your suggested changes?

**Comment by ADmad** [comment]
@Manuel1948 For future reference please avoid posting comments on commits and instead explain the problem in issue itself.

**Comment by Manuel1948** [comment]
I tried to create a PR, but I think I did some silly thing. I don't know how to best create a PR with changes to a file. This is my first time I have to do with github. Can someone explain how to do it?

**Comment by dereuromark** [comment]
Try to open the PR from your fork (create PR).

**Comment by Manuel1948** [comment]
Now I managed it 😀
