### ISSUE TITLE
Headers already Sent on Debugger.php

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#10273]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.14
* Platform and Target: AWS Server + Mysql Database.

### What you did
Using the platform randomly while on AWS (Couldn't reproduce on local). Can't see what action makes it log, only seeing it since we use CloudWatch.

### What happened
Warning: Headers already sent in /var/app/current/vendor/cakephp/cakephp/src/Error/Debugger.php:754

### What you expected to happen
No error being shown

**Comment by markstory** [comment]
Sounds like your application is running in debug mode and has errors. Check your logs for the other errors.

This isn't a defect with CakePHP, as your application has runtime errors that are being emitted which forces headers to be sent.
