### ISSUE TITLE
3.4.2 BTM targetBindingKey

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10288]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.4.2

### What you did

I want to setup a BTM association that targets part of the foreign tables composite primary key.

#### Use Case: Documents BTM Elements (both revision-ed)

- documents:
  - id
  - revision_id
  - title
  - is_published (UNIQUE per revision_id, e.g. 1 or NULL)

- documents_elements
  - document_id
  - document_revision_id
  - element_id

- elements
  - id
  - revision_id
  - body
  - is_published (UNIQUE per revision_id, e.g. 1 or NULL)

As you can see the join table only has a partial of the primary key of the elements.
This is because by default every document will associated with the element having element.id + element.is_published = true.

This is the same example just with Articles and Tags (because that's used in the book).

```php
<?php
//...
class ArticlesTable extends Table
{                  
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->primaryKey(['id', 'revision_id']);
        $this->belongsToMany('Tags', [
            'bindingKey' => [
                'id',
                'revision_id',
            ],
            'foreignKey' => [
                'article_id',
                'article_revision_id'
            ],
            'targetForeignKey' => [
                'tag_id',
                // 'tag_revision_id'
            ],
            'joinTable' => 'articles_tags'
        ]);
    }
}

<?php
//...
class TagsTable extends Table
{
    function initialize(array $config)
    {
        parent::initialize($config);
        $this->primaryKey(['id', 'revision_id']);
        // Another Candidate/PrimaryKey is id + is_published
        $this->belongsToMany('Articles', [
            'bindingKey' => [
                'id',
            ],
            'foreignKey' => [
                'tag_id',
                // 'tag_revision_id'
            ],
            'targetForeignKey' => [
                'article_id',
                'article_revision_id'
            ],
            'joinTable' => 'articles_tags'
        ]);
    }
```

### What happened
Running a save while having tag_revision_id in the join table and the association setup works fine.
Running a save without having a tag_revision_id in the join table AND the association setup yields this error:

```
Warning (2): array_combine(): Both parameters should have an equal number of elements [CORE/src/ORM/Association/BelongsToMany.php, line 813]
```

That's this line:
```php
$targetKeys = array_combine($assocForeignKey, $e->extract($targetPrimaryKey));
```

**$assocForeignKey**
```
Array
(
    [0] => Array
        (
            [0] => tag_id
        )
)
```

**$e->extract($targetPrimaryKey)**
```
Array
(
    [0] => Array
        (
            [id] => 86fdfa7f-71bb-4d02-a6cc-e19c089f576f
            [revision_id] => 7b044aa3-10f7-4243-a537-2051fa5602bc
        )
)
```

### What you expected to happen

Which does obviously not work. Here the value from id should be combined with the key of tag_id.

Wouldn't something like this solve the problem, aka having a targetBindingKey for BTM?
```php
$targetKeys = array_combine($assocForeignKey, $e->extract($targetBindingKey));
```

**Comment by robertpustulka** [comment]
PR is open
