### ISSUE TITLE
3.4.2 EntityTrait::getDirty()

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10292]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.2

### What you did
Trying to get all fields that are dirty from the Entity.

### What happened
`$entity->isDirty()` will return boolean if any properties are dirty.
`$entity->isDirty('fieldname')` will return boolean if the given property is dirty.

### What you expected to happen
A way to get a list of all dirty properties.

**Comment by inoas** [comment]
Would this be a welcome change to EntityTrait (working but no unit tests yet)?

```php
<?php
namespace App\Model\Entity\Traits;

/**
 * Loads core fix for BelongsToMany until https://github.com/cakephp/cakephp/issues/10292 hits.
 */
trait EntityCoreBugfixTrait
{

    /**
     * Gets dirty fields from the entity.
     * @param array List of properties. If empty or null gets all dirty properties.
     * @return array List of all dirty properties.
     */
    public function getDirty(array $properties = null)
    {
        if ($properties === [] || $properties === null) {
            return $this->_dirty;
        }
        return array_combine($properties, $this->_dirty);
    }
}
```

**Comment by dereuromark** [comment]
Besides setDirty() and isDirty() a third getDirty() makes sense to me :+1:

**Comment by markstory** [comment]
Why would getDirty() need a parameter? If you want to get all dirty fields that sounds like a method with no parameters.

**Comment by inoas** [comment]
@markstory well I'd say either we add `getAllDirty()` which would never take an argument, or we would add `getDirty()` which can take an optional argument to get the dirty properties of all the properties you supply (current proposal).

Which one would you prefer? `getDirty()` is much more flexible and also in line with isDirty and setDirty insofar that you can supply a single field if you want to (I can make it take a string and cast it to array)?

**Comment by dereuromark** [comment]
Wouldnt a simple 

    getDirty(field = null) 

suffice?
Either null = all or field = specific one.
Anything else is not needed IMO - and would also be inline with all the other getter methods and how they usually work with array content: one specific or all by default.

**Comment by inoas** [comment]
Yes, I can do that.

**Comment by markstory** [comment]
How is `getDirty('field')` different than `isDirty()` though? It sounds like we'd have two methods that do the exact same thing.

**Comment by dereuromark** [comment]
@markstory the one without argument would be the one returning all dirty fields as Array list. The one With Argument returns the specific field or null I assume?

**Comment by markstory** [comment]
I made a mistake in my previous comment. With a property argument `getDirty()` would be doing the same thing as `isDirty()`. The original ask was to get _all_ dirty properties.

**Comment by inoas** [comment]
We could have `getDirtyProperties()` and then you can supply nothing to get all or a filter to get only those intersecting? or `getAllDirty()`

**Comment by dereuromark** [comment]
Why notjust getDirty() as suggested to get all and this should be fine?

**Comment by inoas** [comment]
`getDirty()` together with `isDirty()` and `setDirty()` would make me thing it takes a `$property`.
getDirtyProperties() or getAllDirty() would not.

**Comment by cleptric** [comment]
What about handling this like `EntityTrait::getOriginalValues` and name it `EntityTrait::getDirtyValues()`?

**Comment by dereuromark** [comment]
@cleptric but here it is not about the values nur the keys I thought.

**Comment by inoas** [comment]
`array_keys($entity->getDirtyValues())` can be a small performance drop vs just `$entity->getDirtyProperties()`.

**Comment by cleptric** [comment]
@dereuromark Yes, makes no sense then.

Looking into `EntityTrait` shows that we have `EntityTrait::getHidden()`, which returns all `hidden` properties or get `EntityTrait::getVirtual()`, but on the other hand, we have `EntityTrait::getOriginal()`, which wants a parameter.
So I'm 👍  with `EntityTrait::getDirty()` with no parameter.

**Comment by cleptric** [comment]
PR is open.

**Comment by nilsonpena** [comment]
Did getDirty() get included in 3.4.2?
I'm experimenting undefined method at afterSave:
Error: Call to undefined method Cake\Datasource\EntityTrait::getDirty()

**Comment by inoas** [comment]
No it is obviously not as 3.4.2 has already been released and the docs PR above say version added 3.4.3 - It will probably be in 3.4.3.

**Comment by nilsonpena** [comment]
My bad. I read about this method  on 3.x book https://book.cakephp.org/3.0/en/orm/entities.html#checking-if-an-entity-has-been-modified
Sorry!

**Comment by inoas** [comment]
@markstory @ravage84 I think putting the version annotations below the feature cause the problem here (see comment above)
Ref: https://github.com/cakephp/docs/pull/4796#discussion_r104701320
