### ISSUE TITLE
CakePHP refuses to select bigint from microsoft sqlserver

### ISSUE THREAD

**Issue by k2nsloos** [cakephp/cakephp#10295]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2
* PHP Version: 7.0.16
* Platform and Target: Windows 10 + IIS + Microsoft SQL Server 2016

### What you did
Using the following sql table:
```
CREATE TABLE records (
	id int NOT NULL,
	entry bigint NOT NULL,

	PRIMARY KEY (id)
);

INSERT INTO  records (id, entry) VALUES
	(1, 2147483647), (2, 2147483649)
;
```

And the following controller code on a scaffolded table and view:
```
<?php
namespace App\Controller;
use App\Controller\AppController;

class RecordsController extends AppController
{
    public function index()
    {
        $magic_num = 2147483649;
        $records = $this->Records->findByEntry($magic_num);

        $this->paginate($records);
        $this->set(compact('records'));
    }
}
?>
```

### What happened
The problem is that no records are retrieved here, even though there's still one in the database.
Selecting the other record 2147483647 does work.

### What you expected to happen
I expected it to return the row in the data base. Note that 2147483647 = 2^31 - 1 and 2147483649 = 2^31+1. I think this may have something to do with it.

Furthermore using a prepared statement directly DOES work, eg:
```
$conn = ConnectionManager::get('default');
		
$stmt = $conn->prepare("SELECT * FROM records WHERE entry=?");
$stmt->bindValue(1, $magic_num);
$stmt->execute();
		
$records = $stmt->fetchAll('assoc');
```

**Comment by thinkingmedia** [comment]
The max value of an integer in PHP is `2,147,483,647`

**Comment by josegonzalez** [comment]
That might need to be a string before you make the query. Does bigint map to a string in our ORM though?

**Comment by k2nsloos** [comment]
From http://php.net/manual/en/language.types.integer.php
> The size of an integer is platform-dependent, although a maximum value of about two billion is the usual value (that's 32 bits signed). 64-bit platforms usually have a maximum value of about 9E18, except on Windows prior to PHP 7, where it was always 32 bit. PHP does not support unsigned integers. Integer size can be determined using the constant PHP_INT_SIZE, maximum value using the constant PHP_INT_MAX since PHP 5.0.5, and minimum value using the constant PHP_INT_MIN since PHP 7.0.0. 

Since I'm using a 64-bit platform and php7 I concluded that my integers are 64-bit. Am I wrong? And how do I check?

**Comment by k2nsloos** [comment]
I checked this on linux with mysql and the problem does not occur. So it's either windows specific or mssql specific. I'll try to figure out which...

**Comment by markstory** [comment]
Make sure you are using a 64bit version of PHP as well. Windows often ends up with 32 bit php.

**Comment by thinkingmedia** [comment]
@k2nsloos you're really risking bugs if you try to use BIGINT in PHP this is an issue that dates back several years. Just google "bigint mysql php" and see all the problems people have had.

You could tell Cake to handle the column as a string, but this introduces bugs when doing comparisons in SQL. (i.e. `entry` < "12345" isn't the same as `entry` < 12345).

You will also have issues binding BIGINT values elsewhere in PHP to the logic.

If `entry` is an identifier maybe you could just use VARCHAR and just store the value.

You might be tempted to solve this using floats in PHP. I wouldn't recommend it.

https://www.percona.com/blog/2008/01/10/php-vs-bigint-vs-float-conversion-caveat/

Also, keep in mind that PHP does some stupid things. For example; if you're on 32-bit PHP and read a BIGINT value from SQL as STRING and trigger dynamic conversion it gets converted to FLOAT and not INT, but on 64-bit it will get converted to INT. When you go to save any changes made to the SQL and PHP converts the FLOAT to STRING you could get precision indicators added to the string.

If this makes you feel sad.... I feel your pain.

http://phpsadness.com/
