### ISSUE TITLE
3.4 Regression on Cake\Http\Response::withBody(string)

### ISSUE THREAD

**Issue by szel** [cakephp/cakephp#10290]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:3.4.2.

### Context
Trying to upgrade CakePHP 3.3 project to 3.4 using new immutable Request/Response objects:
https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html

### In CakePHP 3.3 controller:
```php
public function index()
{
    $this->response->disableCache();
    $this->response->type('application/json');
    $this->response->body(json_encode('TEST'));
    return $this->response;
}
```
Result: OK - JSON response with string.

### In CakePHP 3.4 controller:
```php
public function index()
{
    return $this->response
        ->withDisabledCache()
        ->withType('application/json')
        ->withBody(json_encode('TEST'));
}
```

Result: Fatal error
```
Fatal Error
Cake\Error\FatalErrorException

Argument 1 passed to Cake\Http\Response::withBody() must implement interface Psr\Http\Message\StreamInterface, string given
```

**Comment by dereuromark** [comment]
You are usig it wrong, as the message suggest. You cannot pass a simple string.
body() in psr7 doesnt mean body() as in CakePHP so far.
See https://github.com/dereuromark/cakephp-cache/blob/master/src/Routing/Middleware/CacheMiddleware.php#L205-L207

So you need to extract the old body, place the content into it and then pass this object into the withBody() method.

**Comment by szel** [comment]
Thank you for the quick fix but I stand by my report that this is an issue.

Migration guideline says:
```
Response::body() is deprecated. Use Response::withBody() instead.
```

Since it was working with CakePHP 3.3, it should be working with 3.4 or be properly documented.

Also, objectively compare the ease of use in CakePHP 3.3:
```
 $this->response->body('TEST');
```

vs CakePHP 3.4:
```
		$body = $response->getBody();
		$body->write('TEST');
		$response = $response->withBody($body);
```

My motivation behind this report is to keep CakePHP rapid development friendly. Small things matter.

**Comment by dereuromark** [comment]
You are absolutely right, we should improve the migration docs here.
Are you able to provide a PR to clarify things? That would be awesome!

**Comment by szel** [comment]
PR to docs or framework?

**Comment by dereuromark** [comment]
Docs https://github.com/cakephp/docs

**Comment by szel** [comment]
I'm getting the feeling that once it's documented this issue won't be solved.

So, please consider:

If Body is a component of Response class (it is logical reasoning from developer standpoint - I am the caller, I'm operating on Response class - not on inner Body class), then whether Body is immutable or not, the implementation details should be contained within withBody() method and I shouldn't be concerned about inner details.

It was like that in CakePHP 3.3:
```
    public function body($content = null)
   {
        if ($content === null) {
            if ($this->stream->isSeekable()) {
                $this->stream->rewind();
            }
            $result = $this->stream->getContents();
            if (strlen($result) === 0) {
                return null;
            }

            return $result;
        }

        // Compatibility with closure/streaming responses
        if (is_callable($content)) {
            $this->stream = new CallbackStream($content);
        } else {
            $this->_createStream();
            $this->stream->write($content);
        }

        return $content;
    }
```

The reason why this is so important is that this class will be used everywhere to generate HTTP responses and current usage is just bad.

Ask yourself - should this much code be needed for rapid development framework to just generate 'HELLO WORLD' without rendering view?

In my case, I'm using CakePHP as HTTP framework to proxy some business services using standard Cake models and there is a lot of code that just renders responses (web services).

I always can ease myself and create helper method somewhere but I would rather get to the source and fix it there so other people won't have to stumble onto this.

So, regarding possible solutions and an open discussion (I hope).

In CakePHP 3.4 there is:
```php
    public function withBody(StreamInterface $body)
    {
        $new = clone $this;
        $new->stream = $body;

        return $new;
    }
```

To fix this I'm proposing:
1. Fix withBody() method, lose type hinting and update tests.
2. Provide alternative method with new name that will accept a string.

I'm long time CakePHP user (since 1.1) and a big believer into project mission so if I can help on this - please advice.

**Comment by ADmad** [comment]
> Fix withBody() method, lose type hinting and update tests.

This method is part of PSR7's `ResponseInterface` so we can't change it's typehint or how it behaves.

**Comment by szel** [comment]
Thank you @ADmad.

How about option 2? There is a ```withFile($path, $options)``` already that does something similar for files.

Could it be something like ```withString($content, $type)```?

**Comment by ADmad** [comment]
A convenience method `withString()` sounds good to me.

**Comment by dereuromark** [comment]
I like it too, but it wouldn't be part of the interface then, would it? Maybe we should make FIG fix it :)

**Comment by davidyell** [comment]
I don't think moving away from the PSR7 interfaces is a good idea. I do understand that in your use-case, which is an edge-case in my opinion, this is frustrating, but that is how the standard works.

I don't see any issue here really, other than just a few extra lines of code. If anything you could implement your own wrapping method in an extending class for this across your whole application.

**Comment by markstory** [comment]
I can see how the migration guide's terseness was misleading. In this situation I would prefer to update the documentation over adding more methods. For this specific scenario you could also use

```php
$response->getBody()->write('TEST');
```

Which feels like a non-obtrusive amount of code to write.

**Comment by szel** [comment]
@davidyell For me it doesn't feel like moving away from PSR7 interfaces. PSR7 is a good initiative to make things better but CakePHP is rapid development framework. It implements the interface but CakePHP is not the PSR7 interface itself. Also it seems that CakePHP Response class already holds a lot of convenience methods ```withFile($path, $options)```, ```withType($contentType)``` or ```withDisabledCache()``` that I cannot find in ```ResponseInterface``` nor ```MessageInterface``` from http://www.php-fig.org/psr/psr-7/ .

@davidyell I also found this quote on PSR7 page:
> StreamInterface is used in order to hide the implementation details when a stream of data is read from or written to. For situations where a string would be an appropriate message implementation, built-in streams such as php://memory and php://temp may be used.

@davidyell I don't see how creating HTTP responses from string is edge-case scenario. Is there a better way to create HTTP responses for web services? Is there anything more simpler than ```json_encode($data)```?

@markstory - First of all, thank you for taking a voice on this issue personally and thank you for all of your work over the years! I'm a big fan!

@markstory - This is a very sound advice for now but I think some thought and discussion could follow.

I was given the impression from migration guide that the way to "talk" to Response object is immutable way, thus making the transition from mutable code consistent.

Breaking the fluid/immutable interface is fine for me and I have a lot of respect for you guys and I realise that there might be more pressing issues to work on.

It just feels like it's starting to reveal some design issues - we have convenience methods to set Content-Type and disable HTTP cache but there is no method to provide HTTP body?

Now, working solution for CakePHP 3.4.2:
```php
public function index()
{
    // immutable Response
    $response = $this->response
        ->withDisabledCache()
        ->withType('application/json');
    // mutable inner Body
    $bytes = $response->getBody()->write('TEST');
   // immutable Response
    return $response;
}
```

With convenience method (not existing yet):
```php
public function index()
{
    return $this->response
        ->withDisabledCache()
        ->withType('application/json')
        ->withString(json_encode('TEST'));
}
```

**Comment by lorenzo** [comment]
I Iike the idea of adding more convenience methods. I would name it `withStringBody()` though

**Comment by markstory** [comment]
@szel Those are good points. I'm onboard with adding a convenience wrapper for setting a string body too :+1:

**Comment by cleptric** [comment]
If no one else wants to do this, I'll take care of it :)

**Comment by cleptric** [comment]
PR is open
