### ISSUE TITLE
Wrong (combined) form inputs values if populating text inputs with array data from query string

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10299]
This is a (multiple allowed):

* [x] bug 
* [ ] enhancement
* [ ] feature-discussion (RFC)

cakephp/bake                          1.3.0   Bake plugin for CakePHP 3.0
cakephp/cakephp                       3.4.2   The CakePHP framework
cakephp/chronos                       1.1.0   A simple API extension for DateTime.
cakephp/debug_kit                     3.9.0   CakePHP Debug Kit
cakephp/migrations                    1.6.7   Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer              0.0.15  A composer installer for CakePHP 3.0+ plugins.

I have situation where I have 2 text input vields mapped as array value like this:
```
<input name="applicant[creationDate][]" class="form-control datepicker" label="Applicant creation date" value=" " type="daterange"><span class="input-group-addon">to</span><input name="applicant[creationDate][]" class="form-control datepicker" label="Applicant creation date" value=" " type="daterange">
```

This results in query string with example data as follows:
```
?applicant[creationDate][]=24-02-2017&applicant[creationDate][]=26-02-2017
```

Now if I try to repopulate the form like that
```php
echo $this->Form->create(null, ['valueSources' => ["query"],....
```

with the with query string generated with
```php
echo $this->Html->link("Refine search",["action" => "index", "?" => $this->request->getQueryParams()]);
```

that looks like this
```
applicant[creationDate][0]=24-02-2017&applicant[creationDate][1]=26-02-2017
```

this is what will happen
```
<input name="applicant[creationDate][]" class="form-control datepicker" label="Applicant creation date" value="24-02-2017 26-02-2017" type="daterange"><span class="input-group-addon">to</span><input name="applicant[creationDate][]" class="form-control datepicker" label="Applicant creation date" value="24-02-2017 26-02-2017" type="daterange">
```

is resulting in putting combined values of two fields into both of them. Removing indexes from populating query string changes nothing.

**Comment by markstory** [comment]
How are you defining your input elements?

**Comment by Antoniossss** [comment]
It came out that somewhere deep in the application we are using custom widget element to generate related intputs and it is a bug in that widget as it didnt handle values properly (add was passing whole array to each of the inputs). Sorry for the trouble and false repor.
