### ISSUE TITLE
RFC - Middleware 'pipelines' as part of Routing

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10308]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.0

PSR-7 Middleware makes it simple to compose application logic together as separate layers that are composed together wrapping an application. What is lacking is a way to apply middleware to only specific routes. When this was last brought up @lorenzo  wanted middleware integrated into routing. I originally thought this might be really hard, and it still might be, but here is a rough idea of what the API could be:

* The `Cake\Routing\Middleware\RoutingMiddleware` class would take an `Application` as a parameter. If that parameter is provided, the middleware will invoke the `routing` hook method on the application.
* The `Application::routing()` method would provide an object wrapper for `config/routes.php`  like `Application::bootstrap()` provides for `config/bootstrap.php`. Inside this method routes could be connected, much as they are today.

By default the `routing` hook would simply include `config/routes.php`, but it could be overridden as well.

An example of the routing hook and the routing middleware in action would be:

```php
function routing($routes)
{
    // Register middleware, for use in routing scopes
    $routes->registerMiddleware('auth', new AuthenticationMiddleware(...))
        ->registerMiddleware('cookies', new EncryptedCookieMiddleware(...))
        ->registerMiddleware('csrf', new CsrfMiddleware(...));
        ->registerMiddleware('cors', new CorsMiddleware(...));

    // Create a routing scope (as you do today)
    $routes->scope('/api', function ($routes) {
        // Enable middleware
        $routes->middleware('csrf', 'cors', 'auth');
        $routes->connect('/ping', ['controller' => 'Pings']);
    });

    $routes->scope('/bookmarks', function ($routes) {
        // Enable middleware
        $routes->middleware('csrf', 'cookies', 'auth');
        $routes->connect('/bookmarks/:action', ['controller' => 'Bookmarks']);
    });
}
```

## Detailed Steps

* `RouteBuilder` would be updated to have new methods for registering middleware into the `RouteCollection`.
* After routes are matched, `RoutingMiddleware` could fetch the middleware for a given URL similar to how we do scope matching today. `$next = Router::getMiddlewareForRequest($request, $next);`
* Middleware would be matched by the registered scopes.
* Once found, middleware objects would be added to a new `MiddlewareQueue` object.
* The `$next` parameter of `RoutingMiddleware` would be appended to the `MiddlewareQueue` containing route specific middleware.
* A new `Http\Runner` would be created to run the new queue.
* `RoutingMiddleware` would invoke the new queue.

### Related issues

* #9089

**Comment by inoas** [comment]
So how is the current flow? FrontController -> Middleware -> Router -> Controllers? Wouldn't that allow for loops?

**Comment by saeideng** [comment]
enabling `middleware` just for/within `scope` ?
like use in 
`$routes->connect('/ping', ['controller' => 'Pings'])->addMiddleware('csrf', 'cors', 'auth');`

**Comment by markstory** [comment]
@saeideng I had only planned on allowing middleware to be enabled per scope. Do you have scenarios where you would want middleware in a single route only?

**Comment by fquffio** [comment]
@markstory I think that an example of a middleware that should be attached to a single route could probably be some sort of "Single Sign On" middleware, that should apply to the `/myScope/login` route only. However, one could probably reach the same result by creating a "fake" scope with a single route in it, right? Something like:

```php
// This...
$routes->connect('/login', ['controller' => 'Users', 'action' => 'login']);
// ...would become this...
$routes->scope('/login', function ($routes) {
    $routes->middleware('ssp'); // Attach my SSO middleware.
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
});
```

**Comment by chrisShick** [comment]
@markstory Any idea what release this will be implemented in? It would definitely be a benefit to a project I am working on.

**Comment by markstory** [comment]
@chrisShick It will be part of 3.5.0

**Comment by chrisShick** [comment]
@marketing AHHH I just now saw it in the opening post. Well, I look forward to seeing it in action. In the mean time, is there a way for me to implement a work around?

**Comment by markstory** [comment]
You'd have to put URL conditions in each of your middleware objects. I plan on starting this after the work on cookie objects is wrapped up.

**Comment by markstory** [comment]
Closing as the features described here have been implemented.
