### ISSUE TITLE
3.4.2 app configure setting to disable auto-tables

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10302]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.2

### What you did
Spend 2 hours debugging why timestamps would not get set despite `$this->addBehavior('Timestamp');` and realized `'className' => 'PluginPrefix.TableName',` was missing from one association definition.

### What happened
Auto-tables took over.

### What you expected to happen
A way to globally disable auto-tables in app.php as it can sometimes hurt more than it helps.

**Comment by markstory** [comment]
This could be a setting that is enabled on the locator or TableRegistry. I'm not sure this is the kind of thing we'd enable by default out of the box.

**Comment by inoas** [comment]
I don't follow? It is already enabled by default?
You mean you don't want it to be configurable on app level?

**Comment by markstory** [comment]
I mean I don't think this would be an option that is defined in `config/app.php`.  While auto-tables can occasionally cause issues they are generally helpful as they remove toil when getting started with CakePHP or working on small applications.

With that said I can see how a strict mode can be useful for larger applications.

**Comment by inoas** [comment]
I'd love something like that. Cake bake generally would not work without it as far as I understood. But we could re-enable it there even for strict mode?

**Comment by lorenzo** [comment]
You can also check the SQL panel in DebugKit to know which auto tables are being used

**Comment by inoas** [comment]
I am however currently working on json api's only and DebugKit has not console output.

**Comment by inoas** [comment]
Can I for now just add something like this to the book?

```php
use Cake\Event\EventManager;
use Cake\Network\Exception\InternalErrorException;
// Disable Auto-Tables
EventManager::instance()->on('Model.initialize', function($event) {
    if (get_class($event->getSubject()) === 'Cake\ORM\Table') {
        throw new InternalErrorException(sprintf('Missing or miss-referenced table class for database table %s.', $event->getSubject()->getTable()));
    }
});
```

If I can figure out how to detect if the framework stack call came from cake bake, I can exclude this condition.

Anything better?

**Comment by inoas** [comment]
If you want to do that in 4.x it'd be great.
The workaround ln bootstrap that I documented works good enough.
