### ISSUE TITLE
Add Tags to the repo

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10309]
See: https://github.com/symfony/symfony has framework, php, symfony, symfony-bundle, bundle, psr-3, psr-11, psr-6, psr-16

So could we add the PSR levels as tags?

More inspires:
https://github.com/angular/angular
https://github.com/rails/rails
(also checked spring, laravel, express, etc.)

some suggestions:
mvc, web, web-framework, webservice, orm, web-performance, composer, rest, html, json, xml, composer, mit

Ref: https://help.github.com/articles/working-with-tags/

**Comment by saeideng** [comment]
see/click on the `php` tag in https://github.com/cakephp/cakephp
https://github.com/search?q=topic%3Aphp+org%3Acakephp&type=Repositories
that is not useful

**Comment by inoas** [comment]
topic:orm org:cakephp 0 hits.
that aside the tags are also for the global search
https://github.com/search?utf8=%E2%9C%93&q=topic%3Aphp&type=Repositories&ref=searchresults

**Comment by saeideng** [comment]
oh! you are right

**Comment by markstory** [comment]
I added psr-7 and orm as tags.

**Comment by inoas** [comment]
Could we add more?

`mvc, web, webservice, composer, form builder, validation, rest, html, json, xml, composer, mit`

I mean this is a full fledged framework (which has its drawbacks) so we should highlight that there is a lot offered through tags, imho.

The sub packages could also get some more tags.

p.s.: If you are happy with the current state, feel free to close this.

**Comment by markstory** [comment]
I added a bunch more. Thanks for the suggestions :+1:

**Comment by Oxicode** [comment]
remove tag "php" and "hmtl"

**Comment by dereuromark** [comment]
I also find "xml" and "json" totally wrong there.
We should focus on the relevant PHP framework ones IMO.

**Comment by markstory** [comment]
@Oxicode I've left `php` but removed `hmtl` as that was a mistake.

**Comment by inoas** [comment]
@dereuromark okay, but what about adding php7 :)?

**Comment by josegonzalez** [comment]
@inoas I think we're set on tags. We can revisit this in 3-6 months once we see the impact of adding our current tags. Thanks for the suggestions.
