### ISSUE TITLE
While Installing a Cakephp 3.4 showing this error in terminal 

### ISSUE THREAD

**Issue by Dheeraj89** [cakephp/cakephp#10311]
**Installing cakephp 3.4 in ubuntu.**

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].

**Comment by antograssiot** [comment]
The error message clearly states what the problem is.
Your environment has lib-icu < 4.8, so update your environment.
