### ISSUE TITLE
[Windows] cakephp/cakephp 3.4.* requires lib-icu >=4.8

### ISSUE THREAD

**Issue by khunemz** [cakephp/cakephp#10310]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.*
* Platform and Target: Windows 10

### What you did
1. composer self-update && composer create-project --prefer-dist cakephp/app app
2. Xampp && IIS Express: in php.ini uncommented and saved
 2.1 extension=php_intl.dll
 2.2 [intl]
intl.default_locale = en_utf8
intl.error_level = E_WARNING

### What happened
**Command Prompt :**
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2]. Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].

### What you expected to happen
Create new CakePHP project without Warning Message and Ready to use in Xampp (or with bin/cake serve -p 8888)

**Comment by antograssiot** [comment]
Did you restart the server after updating your intl configuration ?
Anyway it is likely related to your confirmation and not to CAKEPHP itself.
I think that MAMP worked well

**Comment by ADmad** [comment]
The error message clearly states what the problem. Your environment has `lib-icu` < 4.8, so update your environment.

Alternatively run the `composer create-project` command with `--ignore-platform-reqs` to continue installation ignore the environment requirement.

**Comment by khunemz** [comment]
@ADmad **composer self-update && composer create-project --prefer-dist cakephp/app my_app_name  --ignore-platform-reqs** Works !! Should we improve docs ?

**Comment by ADmad** [comment]
No, this is a workaround not a solution. Not having the right ICU version will cause you problems when using features which rely on it.

**Comment by lma1216** [comment]
@ADmad how do you update your environment i have the same problem can´t fix please help tks

**Comment by antograssiot** [comment]
@lma1216 you can target the master branch and wait for the next release if you don't know how to update.

**Comment by KingGeneral** [comment]
hi finally guys i resolve this issue, this simple as that unknown update : 

here try my solution :  (me using xampp as the example)

- look for your **php.ini**
![image](https://cloud.githubusercontent.com/assets/9468485/23978252/96470dac-0a25-11e7-99f0-519b3f8c18ad.png)
- uncomment the extension. `extension=php_intl.dll`
![image](https://cloud.githubusercontent.com/assets/9468485/23978333/0ca8f348-0a26-11e7-8faa-bce26b095c75.png)
- Restart your server (xampp) - done.

references : 👍 
http://php.net/manual/en/intl.installation.php
