### ISSUE TITLE
3.4.2 hasMany/bindingKey

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10325]
This is a (multiple allowed):

* [x] bug
* [x] rfc

* CakePHP Version: 3.4.2

### What you did
Looking to implement `targetBindingKey`. Checked occurences of `getPrimaryKey()`?

### What happened
Stumbled onto this:

`Cake\ORM\Association\HasMany::unlink(EntityInterface $sourceEntity, array $targetEntities, $options = [])`

`$targetPrimaryKey = array_merge((array)$target->getPrimaryKey(), $foreignKey);`

Ref: https://github.com/cakephp/cakephp/blob/28ea54b6a89c17dd9e30aa390e4d6b35a7c3daee/src/ORM/Association/HasMany.php#L337

`Cake\ORM\Association\HasMany::_unlinkAssociated(array $properties, EntityInterface $entity, Table $target, array $remainingEntities = [], array $options = [])`

`$primaryKey = (array)$target->getPrimaryKey();`

Ref: https://github.com/cakephp/cakephp/blob/28ea54b6a89c17dd9e30aa390e4d6b35a7c3daee/src/ORM/Association/HasMany.php#L440

**Is this usage correct or should it be `$this->getBindingKey()`?**

Ref: https://github.com/cakephp/cakephp/pull/10289#issuecomment-282570740

**Comment by markstory** [comment]
I'm pretty sure those usages are correct. My understanding of bindingKey is that it contains columns from the 'owning' side that allow for matches on the target table. Those operations both appear to be working on the target table so using bindingKey would not be correct. @lorenzo would know better than I though.

**Comment by lorenzo** [comment]
As @markstory points out, bindingKey for hasMany associations refer to columns in the source side of the relationship

**Comment by inoas** [comment]
Closing just wanted to make sure!
