### ISSUE TITLE
Add test coverage for Wincache and Xcache

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10326]
This is a (multiple allowed):

* [0] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.1
* Platform and Target: Apache2, MySQL 5.7, PHP 7.1.2

### What you did

There currently is no coverage of Wincache and Xcache in the unit tests.

### What happened

Need to add unit tests that cover these cache engines.

### What you expected to happen

I expect that interfaces will have to be added for both Wincache and XCache to make mocking of the services easier for testing. Each cache engine will have to use a global getter function to gain access to each interface.

Here is an example;

```
interface ICakeWinCache {
    public function wincache_ucache_set();
    public function wincache_ucache_get();
    // plus other methods...
}

class CakeWincacheProvider() {
     static $winCache = null;
     public static function getWinCache() {
            //..... returns static ref to interface
     }
     public static function setWinCache(ICakeWinCache $cache) {
           //...... sets static ref
     }
}
```

The above can now be used by the `WincacheEngine` to access the global wincache APIs. This allows for mocking of the win cache service and therefore code coverage of said service.

**Comment by thinkingmedia** [comment]
I think I have a better idea that requires fewer introductions of interfaces and global stuff.

If I add a kind of proxy method to the `WincacheEngine` class for each Wincache function, then I'll be able to mock just those methods.

Something like this.

```
    /**
     * Write data for key into cache
     *
     * @param string $key Identifier for the data
     * @param mixed $value Data to be cached
     * @return bool True if the data was successfully cached, false on failure
     */
    public function write($key, $value)
    {
        $key = $this->_key($key);

        $duration = $this->_config['duration'];
        $expires = time() + $duration;

        $data = [
            $key . '_expires' => $expires,
            $key => $value
        ];
        $result = $this->winCacheUcacheSet($data, null, $duration);

        return empty($result);
    }

    /**
      * Allows mocking during unit tests.
      */
    public function winCacheUcacheSet($key, $value , $ttl) {
          return wincache_ucache_set($key, $value , $ttl);
    }
```

Now I can mock the `winCacheUcacheSet` methods during the unit tests.

**Comment by antograssiot** [comment]
I've added wincache to the appveyor build recently so even if we don't generate coverage from there, at least the tests are played in one of the CI build which wasn't the case before.

**Comment by markstory** [comment]
We could deprecate xcache. I am not sure it is maintained any more as the last release was almost 2 years ago and there is not a PHP 7 compatible extension.

**Comment by antograssiot** [comment]
@thinkingmedia on a side note, unit tests for Xcache [exists already](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Cache/Engine/XcacheEngineTest.php), they are just skipped in both CI but would still be useful to users that needs to ensure that it work on their system.

**Comment by thinkingmedia** [comment]
So it sounds like this is tested but just isn't in the coverage reports.

We should remove xcache if we're not going to be verifying it works. I think we can just relocate it to a plugin.

**Comment by ADmad** [comment]
> So it sounds like this is tested but just isn't in the coverage reports.

You can try to update `.travis.yml` to install `xcache`.

> We should remove xcache if we're not going to be verifying it works. I think we can just relocate it to a plugin.

Can't remove it until `4.0`.

**Comment by antograssiot** [comment]
Even updating travis won't add coverage as only php5.6 can use xcache and the coverage report is run on php7.0 for perf

**Comment by ADmad** [comment]
True coverage won't increase but at least having the tests running on 5.6 would ensure the xcache engine works as expected.

**Comment by antograssiot** [comment]
PR is open to add Xcache on PHP 5.6 build
