### ISSUE TITLE
3.4.* - Table::get() modify query after finder.

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#10327]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

```bash
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
cakephp/bake                1.2.14             Bake plugin for CakePHP 3.0
cakephp/cakephp             3.4.2              The CakePHP framework
cakephp/cakephp-codesniffer dev-master 12b4b41 CakePHP CodeSniffer Standards
cakephp/chronos             1.1.0              A simple API extension for DateTime.
cakephp/debug_kit           3.8.0              CakePHP Debug Kit
cakephp/migrations          1.6.7              Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    0.0.15             A composer installer for CakePHP 3.0+ plugins.
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.0.15-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
sdustinh@sdustinh:~/github/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
```

### What you did
```php
public function findRecord(Query $query, array $options = [])
{
    return $query
        ->where([$this->aliasField('id') => $options['id']])
        ->orWhere([$this->aliasField('uuid') => $options['id']])
        ->orWhere([$this->aliasField('label') => $options['id']]);
}

public function get($primaryKey, $options = [])
{
    $options += ['finder' => 'record', 'id' => $primaryKey];

    return parent::get($primaryKey, $options);
}
```

### What happened
`Cake\Datasource\Exception\RecordNotFoundException` was thrown.

### What you expected to happen
`Cake\Datasource\Exception\RecordNotFoundException` to be thrown.

The problem I am having is here: https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1418

Nothing is broken, but because of the way this is structured I have no way to alter the query in my custom finder to prevent that exception. It would be great if it was something like...

```php
$query = $this->find('all', compact('conditions'))->find($finder, $options);
```

...so that I could traverse the query object and potentially remove the expression. Anything to modify it would be great. As it stands now I have to copy/paste the actual source and rebuild the whole thing.

**Comment by markstory** [comment]
What you are expecting and what happened are the same. Am I missing something?

**Comment by sdustinh** [comment]
I was expecting it to throw an exception. This is a feature add request. Because the `where` conditions are added after the initial finder is called i can't modify those conditions. Through out my application I use the `get` method but I would like to support getting records with uuid as well as the primary key. I can update my routes to support this and overload the method to default to the custom finder but it breaks down when the conditions are added after the finder runs. So to support primary key or uuid lookup without having to update all references I basically have to rewrite the entire method when all that would be needed is to move the conditions before the custom finder call. 

Sorry if this isn't clear. I'm mobile and won't be at my desktop for a while.

**Comment by ADmad** [comment]
> Because the where conditions are added after the initial finder is called i can't modify those conditions.

You can override existing conditions by setting 3rd param of `Query::where()` to true.

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
