### ISSUE TITLE
[3.4.2] Translate behaviour: 'allowEmptyTranslations' set to false gives a Duplicate entry error

### ISSUE THREAD

**Issue by kaliel86** [cakephp/cakephp#10323]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2

### What you did
Here is how my TranslateBehavior is setup 

```
$this->addBehavior('Translate', [
  'fields' => ['title', 'description'],
  'allowEmptyTranslations' => false,
  'onlyTranslated' => true
]);
```

### What happened
I have a form to edit both original entity and Spanish translation. When i edit a first time with nothing in translation inputs, the `i18n` table initialize the fields with empty strings.

Coming back to that edit form, the retrieved entity has an empty `_translations` , which is ok.

But when i fill translation inputs, ORM is making and INSERT instead of UPDATE because the form helper don't initialize translation input with empty string.

### What you expected to happen
Maybe we can't initialize i18n table with empty strings when entity doens't have value on that fields.

**Comment by cleptric** [comment]
Can you provide us with some snippets of your view and controller files?

**Comment by cleptric** [comment]
Relates to #7531

**Comment by markstory** [comment]
Closing as a pull request is up now.
