### ISSUE TITLE
Is the source code of "http://discourse.cakephp.org/"   open source?

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10338]
I want to create a Chinese cakephp forum.

**Comment by inoas** [comment]
I think it is a paid service.
http://www.discourse.org/

**Comment by lorenzo** [comment]
They offer a free service for open source projects

**Comment by ravage84** [comment]
So, could we create a sub forum (category?) for our Chinese users?

http://discourse.cakephp.org/categories

**Comment by slince** [comment]
@ravage84   That sounds good, but it's very difficult to visit "http://discourse.cakephp.org" because of
some Chinese network policy.

**Comment by slince** [comment]
@lorenzo  php forum, ruby to achieve, this a bit ironic.  If you can, cakephp official can achieve a forum system, just can also be a case study。

**Comment by josegonzalez** [comment]
@slince We do not have any official plans to make a CakePHP-centric forum built in CakePHP. It is a massive distraction to the core team, who are focused on bug fixing, feature implementation, maintenance of existing sites, and the plugin/tooling ecosystem. What we have works for the majority of our userbase.

Is there a similar service that is accessible in China? I would prefer it if we could at least promote such a thing, as we would avoid similar networking issues in China.

**Comment by slince** [comment]
@josegonzalez Yeah, there is a Integrated it forum called [SegmentFault](https://segmentfault.com/)  similar to StackOverFlow in China. But not how many posts are about cakephp. Chinese PHPer prefer laravel  and create a laravel forum called [Laravel-China](https://laravel-china.org) .

I often met some developers who begin learning cakephp, they often complain to me that there is no special cakephp forum in China, there is no complete cakephp open source project for their reference, the official Chinese document is also very bad. 

oops!  a learning case is really important

**Comment by ravage84** [comment]
Discourse is actually open source:

http://www.discourse.org/about/

If there is no inofficial CakePHP forum for the Chinese audience yet, somebody could open one...
@slince how about you try to get some Chinese speaking CakePHP developers together and you setup something yourself?

https://cakephp.org/pages/get-involved#marketing

If you need help building up a local user group, you might want to talk to @Megslalk, the CakePHP community manager. 

https://www.facebook.com/megan.kleyweg
megan.lalk@cakephp.org

**Comment by littleylv** [comment]
@slince We have a QQ group(62815048) which has 300+ members.

I prefer official forum [http://discourse.cakephp.org](http://discourse.cakephp.org) personally but a local community like [Laravel-China](https://laravel-china.org/) is much better for marketing in China. I like CakePHP and would like to share this framework to Chinese developers.

**Comment by Megslalk** [comment]
@littleylv is that QQ group specifically for CakePHP? (Is it active?)
Would Slack be something to look into? (we have created a Chinese slack channel cakesf.herokuapp.com)?
We are busy chatting about options for an official platform but would be great to have a user based in China to help out with knowledge about the country and local users :)

**Comment by littleylv** [comment]
@Megslalk It's specifically for CakePHP, but not 'very' active. Actually there are only 10 (more or less) active members 😞  :(
