### ISSUE TITLE
No baseUrl with Router::url and named route

### ISSUE THREAD

**Issue by dario86** [cakephp/cakephp#10333]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Php Version: 7.0.13

I have this named route configured in main **routes.php**

```
Router::connect(
        '/:slug',
        ['controller' => 'Pages', 'action' => 'scheda'],
        ['_name' => 'scheda', 'routeClass' => 'CompanyRoute']
);
```

If i write this

```
\Cake\Routing\Router::url([
    '_full' => true,
    '_base' => \Cake\Core\Configure::read('App.base'),
    '_name' => 'scheda',
    '_ssl' => true,
    'slug' => 'foxers'
    'utm_source' => 'prova',
    'utm_medium' => 'try',
    'utm_campaign' => ($segment > 0) ? "premium$segment" : 'free',
    'tr' => 3,
    'ts' => $ts
], true)
```

returns 
`https:///foxers?utm_source=prova&utm_medium=try&utm_campaign=premium2&tr=3&ts=38-20170224`

Withouth base url.

**Comment by dereuromark** [comment]
What is the value of \Cake\Core\Configure::read('App.base')?

**Comment by dario86** [comment]
Value of App.base is null. But i tried also to change it with my baseurl and nothing change.

Now i tried to delete '_ssl' param and url generated is correct!

**Comment by markstory** [comment]
If `App.base` is `null` the URL will never generate in the way you expect. Have you tried setting the `_host` key? `_base` is not used for setting host names.

**Comment by markstory** [comment]
Your route doesn't generate correctly because you're using the wrong parameters. I pasted your route into a sandbox app I have, and was able to generate the desired URL using the `routes` CLI tool

```bash
$ bin/cake routes generate _name:scheda slug:foxers _ssl:1 _host:my.domain.org

Welcome to CakePHP v3.4.0 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 7.1.0
---------------------------------------------------------------
> https://my.domain.org/foxers
```

(there is currently a small issue with bool parameters in the CLI tool but I'll get that fixed).
