### ISSUE TITLE
MySQL smallint(6) to schema.php to int(6)?

### ISSUE THREAD

**Issue by sebastienbarre** [cakephp/cakephp#10336]
This is a (multiple allowed):

* [x] bug (possibly)

* CakePHP Version: 2.9.5
* Platform and Target: Apache/2.2.31 (OSX/Homebrew), MySQL 5.7.17 (OSX/Homebrew) , PHP 7.0.15 

### What you did

- I exported my database schema using phpMyAdmin to `schema.sql`,
- I exported my database schema using CakePHP's `./Console/cake schema generate -f`,
- I dropped my database schema using phpMyAdmin,
- I re-created my database schema using CakePHP's `./Console/cake schema create`,
- I exported my database schema using phpMyAdmin to `schema2.sql`,
- I compared both `schema.sql` and `schema.sql2`.

The goal was to see if we could leverage CakePHP's `./Console/cake schema` to import/export our schema instead of doing so manually using phpMyAdmin. In that respect, we expected both SQL files to be the same.

There were a few differences, the main ones being:
- all our `smallint(6)` turned into `int(6)`,
- all our `tinyint(4)` turned into `int(4)`,
- all our `tinyint(2)` turned into `int(2)`.

Is this intentional? 

With some of our tables holding 1.5+ millions rows, I would rather avoid having multiple columns switch from 1 byte to 4 bytes...

### What happened

Not sure.

### What you expected to happen

- `smallint` would stay `smallint`
- `tinyint` would stay `tinyint`

**Comment by markstory** [comment]
> Is this intentional?

Yes. The various flavours of integers are not supported by the schema abstractions. If you need to preserve those values you'll need to use database vendor specific tools.

**Comment by sebastienbarre** [comment]
I see. Could this maybe be alleviated by storing a `'native_type' => 'smallint'` alongside `'type' => 'integer'`, which would be leveraged when the back-end supports it?

**Comment by markstory** [comment]
That could work but it would require someone with the time and interest to make it happen. At this point my position is that 2.x is in the hands of the community as most of the core team has limited time and wants to focus on 3.x.

**Comment by sebastienbarre** [comment]
OK I think I'll submit a PR if you don't mind. Instead of `native_type` I'll add a `storage_requirement` field to the meta description that will store how many bytes are used for that type (or not provide that field entirely for data sources that can't be bothered, like SQLite, or types that don't have such requirements). That way the proper data source (here, MySQL) can match that size and provide a better type (here, `smallint` instead of `int`). I think something along those lines won't be too complicated or intrusive.

**Comment by sebastienbarre** [comment]
@markstory would certainly appreciate if you could check #10347
