### ISSUE TITLE
[RFC] Nested transaction might be rolled back unexpectedly

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#10348]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.2

### What you did

A simple test code:
```php
$this->loadModel('Bookmarks');
$this->Bookmarks->connection()->transactional(function(){
    $this->Bookmarks->findOrCreate(['user_id' => -1]);
    $this->Bookmarks->Users->findOrCreate(['id' => null]);
    return false;
});
```

### What happened

A user has been persisted.

### What you expected to happen

It should be rolled back.

### Why this happens

Since `findOrCreate()` uses `transactional()` internally, two transactions will be nested in the example above. The first one will be failed as an invalid `users_id` is passed. The second one will be succeeded as there is no such ID matching NULL. Also, note that the example code returns `false` whatever happens.

You may think the nested transaction will be like the following:
```sql
# transactional()
BEGIN

    # findOrCreate()
    (BEGIN)
    (ROLLBACK)

    # findOrCreate()
    (BEGIN)
    (COMMIT)

ROLLBACK
```

However, in fact it becomes like the following:
```sql
# transactional()
BEGIN

    # findOrCreate()
    (BEGIN)
ROLLBACK

# findOrCreate()
BEGIN
COMMIT

(ROLLBACK)
```
Because one `rollback()` call [kills all nested transactions](https://github.com/cakephp/cakephp/blob/9fff233e7d38e0f30dd55377af637775f7f98104/src/Database/Connection.php#L493-L494) if savepoint is disabled - it means `by default`.

As a result, the second `findOrCreate()` ends up persisting a user because there is no longer nested transactions.

### Solution

I was thinking about throwing an exception if some nested transaction has been rolled back. As for the example above, the first `findOrCreate()` should throw an exception instead of executing a ROLLBACK query:
```sql
# transactional()
BEGIN

    # findOrCreate()
    (BEGIN)
    (ROLLBACK) 
    # throw new NestedTransactionRollbackException
```

I would like to discuss some concerns about throwing an new exception here.

### Acknowledgment

Originally, this issue has been reported by **icchii** in #japanese channel on our Slack. Thank you again.
After that, I have investigated and found out a simple code that causes this issue. And now I am reporting it.

**Comment by lorenzo** [comment]
For this case, can't the user enable real nested transactions?

We already discussed the problems of throwing exceptions, and in the context of the ORM they could potentially cause more harm than it would help.

**Comment by chinpei215** [comment]
> For this case, can't the user enable real nested transactions?

Not all databases support nested transactions.

> We already discussed the problems of throwing exceptions, and in the context of the ORM they could potentially cause more harm than it would help.

I would like to hear that. What it the harm?

**Comment by markstory** [comment]
For databases that don't support nested transactions it doesn't look like we can easily emulate nested transactions either. We don't have many options other than an exception at that point.

**Comment by lorenzo** [comment]
The harm of exception is that they leave inconsistent state behind when not caught. We have many places during the save process where we don't catch exceptions. In those places, we would need to catch this new exception in order to keep operating as usual.

**Comment by inoas** [comment]
A database record being persisted despite that you would assume it should not due to transactions sounds very harmful. When using `->transactional(function() {})` I would assume that either everything inside works or fails and not something in between.

**Comment by chinpei215** [comment]
Thank you for your comments.
@markstory Sure. I would like to an exception simply.
@lorenzo Sorry, I don't understand your concern. When an exception is thrown, it means *unusual*. So we shouldn't continue usual operation silently. Even now, ORM may get some PDOException. What is the difference between thrown a NestedTransactionRollbackException and that? 
@ionas Agreed. I think almost all people would except it.

**Comment by lorenzo** [comment]
But a rollback is not unusual, it is something you can expect. A PDO error is something that is out of your control. As I said in the slack channel, we only need to make sure to catch the exception in the methods that are invoked by the save process. The will make things work the same as before, but people can still have the exception if they need it.

**Comment by chinpei215** [comment]
@lorenzo I may understand your concern a little bit. Then I have another approach and now I think this idea might be better.

```sql
// Allowed nest types
BEGIN
    (BEGIN)
    (COMMIT)
COMMIT

BEGIN
   (BEGIN)
   (COMMIT)
ROLLBACK

BEGIN
   (BEGIN)
   (ROLLBACK)
ROLLBACK

// Not allowed nest type
BEGIN
   (BEGIN)
   (ROLLBACK)
COMMIT // Error. Throw an exception.
```
In this idea, the `rollback()` call of the last type doesn't throw an exception really, but marks the transaction as it should be failed. And if people call `commit()` after that, then it throws NestedTransactionRollbackException. However, if people call `rollback()` as failure operation, like the third example, it doesn't throw anything.

What do you think about this idea?

**Comment by lorenzo** [comment]
@chinpei215 I like the idea! While it does not solve the problem, it will at least inform the user during the testing phase that there is something wrong with their logic.

A complete solution to this problem would require a very different design of the ORM, but I think we can mitigate it with different strategies.

**Comment by lorenzo** [comment]
Another strategy we can use after implementing you idea is to keep some state in the connection that can be used by the ORM to know when it was expecting to be inside a transaction and where it does not. This way, we can prevent calls to `insert()` `update()` or `delete()` if we can detect that the ORM was expecting to be inside a transaction but in reality it was closed.

**Comment by chinpei215** [comment]
@lorenzo Thank you. I should have show you this idea first. I think now we have some consensus for fixing the issue. As a first step, we could throw a new exception when the most outer transaction was closed, if some inconsistent operation - `commit()` after `rollback()`, was done in it. And, as the second step, we can improve the ORM to suppress `insert()`, `update()` or `delete()` calls if the transaction should be failed. I can do the first enhancement. I would like to put it on the top of my todo list.

The latest MySQL and SQLite also seem to support the SAVEPOINT statement. Maybe, we can change `Connection::$_useSavePoints` to `true` by default in future release? Personally, I have never used the statement though.

**Comment by inoas** [comment]
Semi-OT
> Fortunately this is not a problem for postgres users :)

Means it keeps record on the transaction stat and would not allow out of order statments?

**Comment by chinpei215** [comment]
Pull request up now.

**Comment by lorenzo** [comment]
> Maybe, we can change Connection::$_useSavePoints to true by default in future release? Personally, I have never used the statement though.

@chinpei215 I learned the hard way how bad it is to have that setting always enabled. It caused massive deadlocks in my database, so I rather have people opt-in to te feature if they actually need it.

**Comment by chinpei215** [comment]
@lorenzo Thank you for letting me know your experience. Since I have never used SAVEPOINT statements, I didn't know any side-effects of that. I'll tell it to japanese users.
