### ISSUE TITLE
[RFC] Allow use of ::class to pass classes as well as a string

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#10343]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: `3.4.2`
* Platform and Target: PHP `7.1.2`, MySQL `5.7.17`, Nginx `1.10.3`

### What you did
```php
$this->belongsToMany('Attributes', [
    'joinTable' => 'attributes_broadbands',
    'through' => AttributesBroadbandsTable::class
]);
```

### What happened
```
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'App\Model\Table\AttributesBroadbandsTable.broadband_id' in 'field list'
```

### What you expected to happen
I would expect that the class would resolve to it's name and the query would be executed.

### Not just in queries
I personally feel this is a much better way of passing classes around an application rather than a string, as it ensures that the class actually exists, and allows development tooling to actually detect the class properly. It'll also help to prevent typos in with a decent enough IDE.

A few other instances I can think of are in the `loadHelper()` options array where it takes a `className`. Plugin class names would just be the plugin namespace, so it solves that easily without the need to call `pluginSplit()`.

The real nice one might be in `loadModel()`, so that it can be called as `loadModel(ExamplesTable::class)`. Which leads to `TableRegistry::get(ExamplesTable::class)`.

I'm sure there are some other places as well.

### Downsides
It's quite a big change for what could be considered to be little benefit. I don't agree with that though, for the reasons above.

It's quite a far ranging change, which will potentially affect multiple layers of the framework. Yep, true.

Impact on the Object Registry. Yeah, this one I don't know much about, except that Cake uses the Service Locator pattern to store instances keyed under a string alias. So there might be an issue here converting the qualified name into something which can be used as an array key. Do let me know if I've misunderstood this though.

### What do you think?
I'm interested to hear peoples thoughts on this and if a pull request to make this 'functionality' available across the framework would be worthwhile.

#### What the heck is `::class`?
If you happen to have not seen this before, it's a nice PHP 5.5 feature.
http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name

#### What's a qualified name vs fully qualified?
http://php.net/manual/en/language.namespaces.rules.php

**Comment by dereuromark** [comment]
Are you Sure this is class and Not an alias Herr? Looks to me Like latter.

**Comment by ADmad** [comment]
All `load*` methods and the `through` option takes an alias not class name. Class name is specified using the `className` key in options, you can very well use `Foo::class` there if you want.

I am don't think any change is needed.

**Comment by davidyell** [comment]
So this might be solved with an update to the documentation?

**Comment by lorenzo** [comment]
Pro tip: `Foo::class` is actually a string. PHP replaces that with `$namespace . Foo` at compile time
