### ISSUE TITLE
Allows empty string for foreign keys

### ISSUE THREAD

**Issue by Mistermasque** [cakephp/cakephp#10340]
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Linux lamp php 5.5.20 MySQL 5.1.73

### The problem
In my application I have french identification of cities (INSEE code). This code is a primary key as Varchar(6)
I have different tables linked belongs to cities with this INSEE code as foreign key.
This foreign key can be empty.
But in cakephp empty strings are stored as '' value not as null value which creates SQL error with foreign keys.

### My solution
The solution for me is to create a NullableStringType class in my src/Database/Type application folder 

```
<?php
namespace App\Database\Type;

use Cake\Database\Type\StringType;
use Cake\Database\Driver;

class NullableStringType extends StringType {
	/**
	 * Convert string data into the database format.
	 * Overwrite String Type to return null if value is ''
	 *
	 * @param mixed $value The value to convert.
	 * @param \Cake\Database\Driver $driver The driver instance to convert with.
	 * @return string|null
	 */
   public function toDatabase($value, Driver $driver) {
		if ($value === '')
			$value = null;

		return parent::toDatabase($value, $driver);
	}

	/**
	 * Marshalls request data into PHP strings.
	 * Overwrite String Type to return null if value is ''
	 *
	 * @param mixed $value The value to convert.
	 * @return string|null Converted value.
	 */
	public function marshal($value) {
		if ($value === '')
			$value = null;

		return parent::marshal($value);
	}
}
```
And then I modified schema for each foreign keys in Tables classes

```
protected function _initializeSchema(Schema $schema)
	{
		$schema->columnType('city_insee_code', 'nullableString');
		return $schema;
	}
```

**Comment by dereuromark** [comment]
This sounds like a reoccurring issue that plays into the data consistency when patching in form data etc.
The [Nullable](https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Behavior/NullableBehavior.php) behavior aims to workaround the issue for the time being, until the core can find a more native approach on the subject.
I can't find the related tickets here right now, though.

**Comment by markstory** [comment]
Outside of separate Type classes I don't see how else we could handle columns that accept both `''` and `null` when post data is full of strings and the only value we have access to is `''`. Having opt-in types that use `null` seems like a reasonable solution to me.

**Comment by inoas** [comment]
Well there is two things here IMHO:
1. If fields are sql-`NULL`-able then the ORM should allow for things to pass through. This could be configurable on table, possibly even on global level.
2. Treating '' as NULL. This can be managed through entity mutators already, I think.

For instance this mutates between true/1 and null/null instead of true/1 and false/0:

```php
    /**
     * is_published mutates between true and null in the database
     * mapped to true and false for reading and writing entities
     *
     * @param boolean|int|string Is published flag.
     * @return boolean|null Returns true or null.
     */
    protected function _setIsPublished($isPublished)
    {
        if (in_array($isPublished, [true, 1, '1'], true)) {
            return true;
        }

        return null;
    }

    /**
     * is_published mutates between true and null in the database
     * mapped to true and false for reading and writing entities
     *
     * @param boolean|int|string Is published flag.
     * @return boolean|null Returns true or null.
     */
    protected function _getIsPublished($isPublished)
    {
        if (in_array($isPublished, [true, 1, '1'], true)) {
            return true;
        }
    
        return null;
    }
```

**Comment by dereuromark** [comment]
Seems the solution above is sufficient then for the time being.
