### ISSUE TITLE
Text::tokenize doesn't fully support the left/right bounds being the same character

### ISSUE THREAD

**Issue by bradygp** [cakephp/cakephp#10346]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.310.

### What you did
```php
$query = 'question "help needed" "garbage" contents of query';
$tokens = Text::tokenize( $query, ' ', '"', '"');

foreach ( $tokens as $index => $token) {
    echo $token . "\n";
}
```
### What happened
```
question
"help needed"
"garbage" contents of query
```
### What you expected to happen
```
question
"help needed"
"garbage"
contents
of
query
```
[I orginally posted a question about this on stackoverflow](http://stackoverflow.com/questions/42585728/am-i-misusing-cakephps-texttokenize-utility)

**Comment by cleptric** [comment]
PR is open.
