### ISSUE TITLE
[Enhancement] AuthComponent

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10357]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

- What i did:
```
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Form' => [
                    'finder' => 'supplierAuth',
                    'fields' => ['username' => 'username', 'password' => 'pwd'],
                    'scope' => ['Users.status' => 1],
                    'contain' => ['Suppliers'],
                    'passwordHasher' => ['className'=>'Md5']
                ],
            ],
            'loginAction' => ['controller' => 'Users', 'action' => 'login']
        ]);
```
I'm developing rest api; 

- What happed
 
Now client will redirect to sign page if client request a api that need to be authorized. 

- What i need:

 I do not need client jump automatically, I want give a json response that  told client go to sign in and record some logs.
response like:
```
{
  "message": "Please log in first",
  "info": [],
  "code": 104102
}
```

- Enhancement 
AuthComponent will provide some event i can subscribe,  so I can custom a handler .
```
$this->Auth->dispatcher()->on('UserNotAuth', function(){
     $event->stopPropagation();
     return new JsonResponse(104102, __(Please log in first));
});
```

**Comment by ADmad** [comment]
You are using session based authentication for API?  The common practice is to use stateless authenticators for API.

Anyway, you can add a listener for `beforeRedirect` event (or use `AppController::beforeRedirect()`) to throw a custom exception and prevent the redirection.

**Comment by slince** [comment]
Yes, base on session is easier to achieve. 

"beforeRedirect " maybe is not appropriate，you know, not all redirect are caused by AuthCompoent; 

@ADmad

**Comment by slince** [comment]
AuthComponet should support custom handlers. :100:

**Comment by ADmad** [comment]
> not all redirect are caused by AuthCompoent;

You can always check whether redirect url is login url.

> AuthComponet should support custom handlers.

It already does. Make your own authenticator class and return a response instance from it's `_unauthenticated()` methods as per your needs.

**Comment by slince** [comment]
@ADmad  
Yeah, I have create a authorization class , however  i need copy some code of `AuthComponent::_unauthenticated`, 
![image](https://cloud.githubusercontent.com/assets/3785826/23643805/e13dbd6c-033e-11e7-9e98-baf44b6ab8c1.png)





I think  it's more flexible to support multiple custom processors

```
$this->Auth->on('unAuth', function(event){
    //handler1 todo something
   if (some condition) {
         $event->stopPropagation();
   }
}, Priority::LOW);

$this->Auth->on('unAuth', function(){
    //handle2
},  Priority::HIGH);

```

@markstory   Looking forward to change

PS： Do i need to close this issue?

**Comment by ADmad** [comment]
What i suggested was make a custom authenticator `MyAuthenticate extends FormAutheticate` with a `MyAuthenticate::_unauthenticated()` method which response a `Cake\Http\Response` instance. The response could either have redirection URL set or JSON string as per your needs. You won't have to override anything else.

Also we have new plugin [cakephp/authentication](https://github.com/cakephp/authentication) to handle authentication, so enhancements to core's AuthComponent and related classes are unlikely to happen.

**Comment by burzum** [comment]
@ADmad we should think about how this can be done in the new plugin if it's not already possible.

But as I understand it it should be easy for him to do a redirect based on the authentication result that is attached to the request object.

**Comment by ADmad** [comment]
Since we don't do any automatic redirection in the new authentication​ plugin, this is a non issue when using it. He can just check the result and return response as per his needs.

**Comment by burzum** [comment]
@ADmad so let's close this issue?

@slince take a look at the [Authentication ](https://github.com/cakephp/authentication) plugin. As ADmad and me stated before, you can get the the identity and the result of the identification attempt from the request object.
