### ISSUE TITLE
Basic Authentication credentials are not converted to UTF-8 or other charset before usercheck

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#10359]
* [x] bug
* [x] enhancement

* CakePHP Version: 3.4.2

### Problem

When using Basic Authentication and UTF-8 as encoding, username and passwords will not be encoded in utf8 instead the encoding is still iso... , so the comparison with the database in utf8-encoding is not possible and reply the following error:

Error: [PDOException] SQLSTATE[IMSSP]: An error occurred translating string for input param 1 to UCS-2

**Comment by Manuel1948** [comment]
PR #10360

**Comment by cleptric** [comment]
PR is open.
