### ISSUE TITLE
2.9 CakeSchema creates duplicate primary keys

### ISSUE THREAD

**Issue by sebastienbarre** [cakephp/cakephp#10354]
* [x] bug
* CakePHP Version: latest 2.x (e.g. 2.9.6)
* Platform and Target: Platform and Target: Apache/2.2.31 (OSX/Homebrew), MySQL 5.7.17 (OSX/Homebrew) , PHP 7.0.15

### What you did

While using the `schema` shell to export my database schema and later on re-import it to my MySQL database I noticed I'm losing the AUTO_INCREMENT flag in a lot of my tables, which breaks the app.

### What happened

The reason for this is in `CakeSchema::_columns()`:
```php
	protected function _columns(&$Obj) {
		$db = $Obj->getDataSource();
		$fields = $Obj->schema(true);
		$columns = array();
		foreach ($fields as $name => $value) {
			if ($Obj->primaryKey === $name) {
				$value['key'] = 'primary';
			}
```
This above create a duplicate primary key for any table that has no model (which is supported by `CakeSchema` when you pass `models = false`) *and* a primary key already set on a *different* column than `id`.

When exporting a schema `CakeSchema::read()` will create an `AppModel` for each table, whether it is has an actual model or not:
```php
		$Object = new AppModel(array(
			'name' => Inflector::classify($table), 'table' => $table, 'ds' => $connection
		));
```
`read()` will then call `_columns()`. Since the `AppModel`'s `$primaryKey` is automatically set to `id` by the constructor at this point, the above code will trigger `$value['key'] = 'primary'`. However, since my table *already* has a primary key on a different column, re-importing the schema with a table that has now *two* primary keys seem to result with the `AUTO_INCREMENT` attribute being lost.

Here is a bit more context. I've *a lot* of these tables around, it would be painful to create a fake model for each one of them. Each of these tables is used to store *revisions* of tables that map to actual models, using the pretty handy [CakePHP-Assets/revision behavior by alkemann](https://github.com/alkemann/CakePHP-Assets/blob/master/models/behaviors/revision.php). For example `employees_revs` stores the revisions for the `Employee` model associated to the live `employees` table.

Revision models are created on the fly by the behavior as "shadow" models. The behavior also takes care of creating the revisions table which, per instructions, have the same fields as in the live table, except for: 
 * The `id` field should NOT be the primary key, nor auto increment
 * new fields `version_id` (int, primary key, autoincrement) and `version_created` (datetime) need to be present.

In other words, `id` is no longer primary or autoincrement because `version_id` is. This is important for this behavior to work, since we need `id` to match the `id` in the live table -- a record can (and will) have many revisions, therefore multiple rows will have the same `id` in the revisions table.

### What you expected to happen

I expected `id` not to be flagged as `primary` automatically.
I assume the behavior above was added for convenience?

Once fix would be to first check if the table already has *any* primary key. If that is the case, do not create a default primary key in the schema:
```php
	protected function _columns(&$Obj) {
		$db = $Obj->getDataSource();
		$fields = $Obj->schema(true);

		$hasPrimaryAlready = false;
		foreach ($fields as $value) {
			if (isset($value['key']) && $value['key'] === 'primary') {
				$hasPrimaryAlready = true;
			}
		}

		$columns = array();
		foreach ($fields as $name => $value) {
			if ($Obj->primaryKey === $name && !$hasPrimaryAlready && !isset($value['key'])) {
				$value['key'] = 'primary';
			}
```

Note that all tests pass with the above fix. I can create a PR but I've been scratching my head for an hour to create a test that exercises this bug specifically in `CakeSchemaTest.php`. I could use some help here, the test would need to call `read()` with `models => false` and a table need to be there already but without any model to match it against...

**Comment by markstory** [comment]
I agree that does look like a mistake in the existing code. A pull request would be great. Reaching that case in the test suite might be easier if you create another fixture with a non-conventional schema.

**Comment by sebastienbarre** [comment]
Thanks @markstory, I managed to create a test. PR sent.

**Comment by markstory** [comment]
Closing as a pull request is open now.
