### ISSUE TITLE
ignore checking rule if data not present in existsIn()

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10355]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cakephp 3.4.x

### What you expected to happen
cake 3.4:
ignore checking rule in `Cake\ORM\Rule\ExistsIn()` if data/field  not present 
cake 3.2:
in cake 3.2 that is work even if data/field not present

also bake not generate some validate 

```
       public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');
        $validator
            ->allowEmpty('comment');
        return $validator;
    }
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        return $rules;
    } 
```
missed bellow code in  `validationDefault(Validator $validator)`
```
        $validator
            ->requirePresence('user_id', 'create')
            ->notEmpty('user_id');
```

solutions:
1) adding bellow validation to default bake  
```

        $validator
            ->requirePresence('user_id', 'create')
            ->notEmpty('user_id');
```
2)fix  `Cake\ORM\Rule\ExistsIn()`  behavior

**Comment by markstory** [comment]
Rules are supposed to always apply and ensure that objects maintain integrity/follow application rules. The `ExistsIn` rule was fixed as part of the work to add better nullable column support.

**Comment by saeideng** [comment]
So we needs to update bake !?

**Comment by markstory** [comment]
Probably.

**Comment by markstory** [comment]
Closing as there is a pull request open for bake.
