### ISSUE TITLE
How can i run action in controller one times every day at 00:00:00 AM?

### ISSUE THREAD

**Issue by at-tienpham** [cakephp/cakephp#10352]
Sorry when i create issues here. Any help would be greatly appreciated. Thanks you and sorry about my english ability.

**Comment by josegonzalez** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by slince** [comment]
Can u speak chinese? 你是要做定时任务吧， 把你要在Action里做的事写在Shell里面 然后执行 ./bin/Cake Your-Shell-Name   ;  通过linux的crontab 定时执行命令

**Comment by inoas** [comment]
Is there already a chinese cakephp freenode irc channel / slack channel? That could also help a tad.
