### ISSUE TITLE
Parse error PHP 7.0.16  expecting '&'' or"variable (T_VARIABLE)"' 

### ISSUE THREAD

**Issue by Petrucheqa** [cakephp/cakephp#10369]
# Getting parse error PHP 7.0.16 

- parse error, expecting '&'' or"variable (T_VARIABLE)"' in vendor/cakephp/cakephp/src/I18n/functions.php on line 26

* [x] bug

* CakePHP Version: 3.4.2
* Platform and Target: Ubuntu 14.04, PHP : 7.0.16

I'm using Atom with linter-php  and linter-phpcs and i have the same problem like in this issue

https://github.com/cakephp/cakephp/issues/10035

**Comment by ADmad** [comment]
The only way you can have this parse error is if you have PHP < 5.6 for CLI. So please check your environment. Maybe different PHP versions are being used for you webserver and CLI.

**Comment by Petrucheqa** [comment]
Thank's a lot
