### ISSUE TITLE
Error Validate Unique Upper or lower case text

### ISSUE THREAD

**Issue by awilchesl** [cakephp/cakephp#10376]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.15.
* Database: Postgres.

I have the following code.

```
public function validationDefault(Validator $validator)
    {
      $validator
          ->requirePresence('name', 'create')
          ->notEmpty('name')
          ->add('name', [
              'unique' => ['rule' => 'validateUnique', 
                           'provider' => 'table',
                           'message' => __d('administrator','El puesto de trabajo ya existe.')]
          ])
          ->notEmpty('name', __d('administrator', 'Debes ingresar un nombre.'))
      ;
      return $validator;
}
```

When validating the `name` field the validate function does not work. If you enter a text eg **andres** and then enter **Andres** creates a double record. But if I write andres in lowercase as it was at the beginning works without problem validate

**Comment by markstory** [comment]
`validateUnique` emits a SQL query to check unique-ness. Your database is likely using a case-insensitive collation which is causing the issue.

```sql
mysql> create table people (
    -> id int not null primary key auto_increment,
    -> name varchar(255)
    -> ) collate=utf8_general_ci
    -> ;
Query OK, 0 rows affected (0.02 sec)

mysql> insert into people (name) values ('Anders');
Query OK, 1 row affected (0.00 sec)

mysql> select * from people where name = 'anders';
+----+--------+
| id | name   |
+----+--------+
|  1 | Anders |
+----+--------+
1 row in set (0.00 sec)
```

**Comment by awilchesl** [comment]
Is correct, but the error throws it from Postgres. Ex. Enter andres and guard. If I go back and write andres the validation works. But if you typed ANDRES in upper case it creates a new record. I mean stay with two andres - ANDRES.

```
Database -Column Name
Collaction es_ES.utf8
```

**Comment by markstory** [comment]
Do you have a `UNIQUE` key on your name field?

**Comment by awilchesl** [comment]
In Database No. In tableRegistry. Yes.

```
->add('name', [
              'unique' => ['rule' => 'validateUnique', 
                           'provider' => 'table',
                           'message' => __d('administrator','El puesto de trabajo ya existe.')]
          ])
```

**Comment by awilchesl** [comment]
I have found a solution to this problem but I do not know how to validate with a BEFORE SAVE. Before saving the record change the text to lowercase or Mayusucula but not valid.

```
public function beforeSave(Event $event, EntityInterface $entity){
      return $entity->name=strtolower($entity->name);  
}
```

**Comment by inoas** [comment]
Try doing that in an entity mutator.

However unique should imho by default be case sensitive and only as an option it should not. This default could be derived of the schema.
