### ISSUE TITLE
Add Https or Security Middleware

### ISSUE THREAD

**Issue by chrisShick** [cakephp/cakephp#10374]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.x and 4.x

I feel that we should have an Https (or Security) middleware as one of the default middlewares. I feel it is definitely something that would benefit the community and could replace the Security component in 4.

**Comment by markstory** [comment]
What would it do? 'Security' is a pretty broad topic.

**Comment by chrisShick** [comment]
Well, it would do what the Security component currently does or if we can just stick with it redirecting to https securely.

**Comment by cleptric** [comment]
> redirecting to https securely.
This should handle the webserver

**Comment by Oxicode** [comment]
Algo así? https://github.com/BePsvPT/secure-headers/blob/master/config/secure-headers.php

**Comment by cleptric** [comment]
Closing as the PR which implemented this was merged.
