### ISSUE TITLE
Nested prefixes cause controller not found issues

### ISSUE THREAD

**Issue by chrisShick** [cakephp/cakephp#10371]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: mac osx sierra.

### What you did
I decided to follow [Rest api in minutes](http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/) as I always do for my api projects. This time I decided to have nested prefixes to version my api. Like this 
```php
    Router::prefix('api', function(RouteBuilder $routes){
        $routes->extensions(['json','xml']);
        $routes->prefix('v1', function(RouteBuilder $routes) {
            \\.... resources
         }
    }
```

When I create the 'token' action in my users controller and try to call the api to it, I get 

> controllerV1 could not be found

I then decided to map the resource in the routes like this:
```php
    $routes->resources('Users', [
            'map' => [
                'token' => [
                    'action' => 'token',
                    'method' => 'POST'
                ]
            ]
        ]);
```
That solved this issue. But I have never had to do that with any of my other APIs. I then decided to implement [Https middleware](https://github.com/oscarotero/psr7-middlewares#https). To test that actions are being redirected to https by going to http, I get the same error as above: 

> controllerV1 could not be found

Was there a recent change that would have caused this?

**Comment by markstory** [comment]
How are you generating your URLs? And where do your controllers live?

**Comment by chrisShick** [comment]
I am not generating any URLs. I am using postman to make calls to the api. The controllers live in 

src > Controllers > Api > V1

**Comment by markstory** [comment]
Ok. What did the routes that didn't work look like? You've only included code that did work, so I have no idea on how to reproduce your issue.

**Comment by chrisShick** [comment]
> http://localhost/api/v1/users/token.json
Is the route that I was testing. If I do not apply the resources map for the token action then it throws the error of looking for the v1 controller.

**Comment by markstory** [comment]
That doesn't look like a route definition

**Comment by chrisShick** [comment]
I believe I showed my route definition in the opening post.

**Comment by thinkingmedia** [comment]
I've done this exact same route and it works for me.

```
Router::prefix('api', function (RouteBuilder $routes) {
    $routes->extensions(['json']);
    $routes->prefix('secure', function (RouteBuilder $routes) {
        $routes->connect('/:controller', ['action' => 'index'], ['_method' => 'GET']);
        $routes->connect('/:controller/:action', [], ['_method' => ['GET', 'POST']]);
    });
    // used by the new dashboard
    $routes->prefix('v2', function (RouteBuilder $routes) {
        // all API access is via POST for security reasons
        $routes->connect('/:controller', [
            'action' => 'index'
        ], [
            '_method' => 'POST'
        ]);
     //....
});
```

That's a sample from code running in production.

**Comment by chrisShick** [comment]
@thinkingmedia I am using resources instead of connect.

`
    Router::prefix('api', function(RouteBuilder $routes){
        $routes->extensions(['json','xml']);
        $routes->prefix('v1', function(RouteBuilder $routes) {
               $routes->resources('Users');
         }
    }
`

**Comment by thinkingmedia** [comment]
You can verify the routes by running `bin/cake routes` on the command line. You should see something like this.

```
| api:v1:users:index | /api/v1/users | { "prefix": "Api\/V1", "controller": "Users", "action": "index", "_method": "GET" } |
```

A line kind of like that for each resource end point. The important part is `"prefix": "Api\/V1"` if that is missing or wrong then you found a bug.

**Comment by chrisShick** [comment]
The prefix is there and correct. However, I did notice this: 

> | api:_controller:index   | /api/:controller                      | {"action":"index","prefix":"api","plugin":null}                                                      |
| api:_controller:_action | /api/:controller/:action/*     

Which might account for the V1 error that pops up.

**Comment by chrisShick** [comment]
I got rid of the https middleware and tried to test the route for http and it worked. I then decided to do a permanent redirect from 80 to 443 in my vhost file instead of the https middleware. It threw the same V1 controller error as the https middleware. I believe this has something to do with redirects being process wrong by the router.

**Comment by chrisShick** [comment]
Alright, so far, I have narrowed it down to this line in the Route class (Route.php)
     if (!preg_match($this->_compiledRoute, urldecode($url), $route)) {
            return false;
     }
The compiledRoute is placing the V1 as the controller and not as the prefix in the $route array.

**Comment by ndm2** [comment]
Resource routing connects fixed/static routes (whatever you want to call it), ie you cannot point to arbitrary actions. Custom resource endpoints need to be configured via the `map` option, and AFAIK that was always the case.

**https://book.cakephp.org/3.0/en/development/routing.html#resource-routes**

**Comment by chrisShick** [comment]
@ndm2 I did map it and it still throws the same error for http when redirecting to https.

**Comment by chrisShick** [comment]
The compiled routes used in the preg_match is returning the controller as v1 and the prefix as api. Which tells me that the pattern matches to the api:controller before it can match to api:v1 prefix.

**Comment by ndm2** [comment]
> I did map it and it still throws the same error for http when redirecting to https.

I read that, just wanted to make clear that custom mapping is actually required, as you were uncertain about it.

Note that vhost config based redirects will happen before PHP is ever being hit, so redirects should not be an issue as far a CakePHP is concerned. You may want to start again with a clean installation, and provide a complete, reproduceable example (what you've shown so far works fine for me).

**Comment by markstory** [comment]
@chrisShick What does your routes.php file look like? The order routes and scopes are connected in changes how they match in the router.

**Comment by chrisShick** [comment]
@ndm2 The redirects are happening just fine. The issue is when the redirect happens, the Route class seems to recognize v1 as the controller and not as a prefix.

@markstory my routes look like this

    Router::prefix('api', function(RouteBuilder $routes){
    $routes->extensions(['json','xml']);
    $routes->prefix('v1', function(RouteBuilder $routes) {
        $routes->resources('Users', [
            'map' => [
                'token' => [
                    'action' => 'token',
                    'method' => 'POST'
                ]
            ]
        ], function(RouteBuilder $routes) {
            $routes->resources('Appointments');
        });

    });
    $routes->fallbacks(InflectedRoute::class);
    });

**Comment by chrisShick** [comment]
@ndm2 @markstory I completely redid the project and I am still getting the same issue.

**Comment by chrisShick** [comment]
Alright, so I believe I have figured out the issue... correct me if I am wrong. 
According to several things I have read, you cannot redirect POST request. If a POST request gets redirected, the data is dropped and a GET request is made. This is what is causing my issue. I have mapped the token to POST but the router is getting a GET request and thus it is not matching and looking at v1 as the controller.

**Comment by thinkingmedia** [comment]
You have to use a `307` status code to redirect a POST request.

```
   public function index() {
        return $this->redirect([.......], 307);
  }
```

**Comment by chrisShick** [comment]
Ahh, well, that nails this one to being an idiot and learning something new.

**Comment by thinkingmedia** [comment]
An idiot is one who repeats the same behavior expecting a different result. That is not you 👍

**Comment by chrisShick** [comment]
Aye, for anyone that wants to do this via the vhosts file should use 
> Redirect 307 / https://myservername/
