### ISSUE TITLE
2.x - Hash::filter removes floated zeros

### ISSUE THREAD

**Issue by jammy-git** [cakephp/cakephp#10385]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.6.1 - though looking at the current version of Cake 2.x I believe this is still an issue.

As per the [current documentation](https://book.cakephp.org/2.0/en/core-utility-libraries/hash.html#Hash::filter), the Hash::filter function should remove all empty elements from an array, excluding 0. However I have found that if you float the 0, it is removed from the array.

Example:
```
$data = array(
    '0',
    false,
    true,
    (float)0,
    array('one thing', 'I can tell you', 'is you got to be', false)
);
$res = Hash::filter($data);

/* $data now looks like:
    Array (
        [0] => 0
        [2] => true
        [3] => Array
            (
                [0] => one thing
                [1] => I can tell you
                [2] => is you got to be
            )
    )
*/
```

I believe the fix would be to amend the _filter function like so:
```
/**
 * Callback function for filtering.
 *
 * @param array $var Array to filter.
 * @return bool
 */
	protected static function _filter($var) {
		if ($var === 0 || $var === (float)0 ||| $var === '0' || !empty($var)) {
			return true;
		}
		return false;
	}
```
But someone more experienced may know of a better solution, possibly using intval instead?

**Comment by markstory** [comment]
Pull requests open for 2.x and 3.x
