### ISSUE TITLE
_joinData not saved when used in patchEntity with _ids

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10382]
This is a (multiple allowed):

* [x] bug ?
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5

I have following tables: Applicants, DeletionReason, and join table ApplicantDeletionReason

Join table has 2 extra fields-> user_id and createed timestamp

I want to use patch entity to create association between Applicants and DeletionReason with extra info in join table. What I do:

In ApplicantTable:
```
        $this->belongsToMany('DeletionReason',[
            "joinTable"=>"applicant_deletion_reason",
            "saveStrategy"=>"replace"
        ]);
```
Controller :
```
           $app=$this->Applicants->patchEntity($app,[
                "deletion_reason"=>[
                    "_ids"=>[1], //hardcoded for now
                    "_joinData"=>[
                        "user_id"=>$this->loggedUser->id
                    ]
                ]
            ],["associated"=>"DeletionReason"]);
```

And save(); but generated SQL looks like this:

`INSERT INTO applicant_deletion_reason (applicant_id, deletion_reason_id) VALUES (:c0, :c1)`

And this results in error due to NotNull constrains on user_id column.
So obviously association is about to be created, but _joinData is neglected in this scenario.

I am not sure if this is a bug or expected behavior.

Also if _ids will not be an array, nothing will happen. 

I can see the conflict here that _join table has only single value, while we can have many ids and and every association could require different joinData probably this would be field for improvement.

**Comment by lorenzo** [comment]
This is by design, as there is no way to match the ids you have wit the join data for each one. I suggest not using ids in this case an build proper arrays or directly build the entities

**Comment by markstory** [comment]
Agree with @lorenzo. `_ids` is intentionally incompatible with `_joinData`.

**Comment by Antoniossss** [comment]
@lorenzo @markstory  Thank you for clarification on that.

**Comment by Slessi** [comment]
If the above is still true, shouldn't the documentation be updated to reflect this?

https://book.cakephp.org/3.0/en/views/helpers/form.html#creating-inputs-for-associated-data

The example above let me to believe that I *could* mix `_ids` and `_joinData`

**Comment by markstory** [comment]
@Slessi how would you change that example to be more clear?

**Comment by Slessi** [comment]
@markstory For sure theres needs to be one of those warning blocks (class `admonition warning`) to specifically highlight that

> You cant use `_ids` and `_joinData` together

At the minimum on the [saving data](https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-additional-data-to-the-join-table) page, but if it could also be included on [form helper](https://book.cakephp.org/3.0/en/views/helpers/form.html#creating-inputs-for-associated-data) it would've helped me out personally also :D

Not sure if its worth changing the form helper examples if there is such a warning present, but as is its implied that you can copy the entire example as is and expect it to work.
