### ISSUE TITLE
first()->toArray() fails with "Call to a member function toArray() on null"

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10393]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2
* Platform and Target: unimportant

### What you did
`$MyTable->find()->where([...])->contain([...])->order([])->first()->toArray()`

### What happened
In the case when no rows are found by the find(), `first()->toArray()` fails with `Call to a member function toArray() on null`

Doing the same find(), `$MyTable->find()->where([...])->contain([...])->order([])->toArray()` returns an empty array, as expected.

### What you expected to happen
I expected an empty array.

**Comment by markstory** [comment]
`first()` returns an entity, or null in your case which cannot implement `toArray()`. There isn't a way to support what you want without causing other issues.

**Comment by inoas** [comment]
see tbl::get() and tbl::exists() for your purposes

**Comment by aswzen** [comment]
its so bad, every time we want an array results we have to check back if the entity if null or not..

**Comment by markstory** [comment]
@aswzen you might want to use firstOrFail() to avoid the null check.

**Comment by saeideng** [comment]
@aswzen for receiving array dont use `->first()` method 
just 
```php
$MyTable->find()
                ->where([...])
                ->contain([...])
                ->order([])
                ->toArray()
```
