### ISSUE TITLE
Cake 2.x and PHPUnit 4.8

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10398]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.x
* Platform and Target: Any.

It is clear that CakePHP 2.x supports PHPUnit not higher than 3.7.38. My problem is that  one of the projects I work on has many unit tests. Generating the coverage report with xdebug takes hours. According to [this](https://hackernoon.com/generating-code-coverage-with-phpunite-and-phpdbg-4d20347ffb45#.iqfn1oprg) blog generating a coverage report with phpdbg is 14 times faster than with xdebug. PHPUnit 3.7.38 does not support phpdbg but [4.8](https://thephp.cc/news/2015/08/phpunit-4-8-code-coverage-support) does.

The question is how much effort it would take to make CakePHP 2.x compatible with PHPUnit 4.8? Is it achievable at all? What would need to be done?

**Comment by saeideng** [comment]
You can use phpunit4.8 in your project if you need

**Comment by chinpei215** [comment]
> The question is how much effort it would take to make CakePHP 2.x compatible with PHPUnit 4.8?

It is easy. Now I am using PHPUnit 4.8. for my project as I want to to use `assertArraySubset()`. I can send a pull  request to make CakePHP 2.x compatible  with PHPUnit 4.8.

**Comment by markstory** [comment]
@chinpei215 That would be awesome. Previously we pinned the version to 3.7 as I had a number of problems upgrading to earlier versions of PHPUnit 4.x but if you have it working that would be great!

**Comment by tersmitten** [comment]
We also like to upgrade to a more recent version and don't mind putting some work into it. Is there a ticket describing the issues?

**Comment by tersmitten** [comment]
@markstory Congratulations with your baby boy btw

**Comment by tersmitten** [comment]
https://github.com/sebastianbergmann/php-token-stream/issues/65

**Comment by markstory** [comment]
@tersmitten There isn't an existing issue. I remember it having something to do with sessions though.

**Comment by chinpei215** [comment]
All tests passed with PHPUnit 4.8.35: https://travis-ci.org/chinpei215/cakephp/jobs/210079162#L442
I am planning to fix several risky tests and to send a pull request tomorrow.

@tersmitten If I remember correctly, you can use PHPUnit 5.x for your project, after my commits merged. But it is annoying to make core test cases compatible with it, as we have to replace all deprecated `getMock()` calls. I think no one wants to review such a large patch. Of course, we can override the method to suppress the warnings, but I don't think it is a right way.

**Comment by chinpei215** [comment]
Pull request up now.

**Comment by tersmitten** [comment]
@chinpei215 

> we have to replace all deprecated `getMock()` calls

Do you have an example?

**Comment by markstory** [comment]
@tersmitten `getMock()` needs to be updated to use `getMockBuilder()`. There are some examples of the [getMockBuilder interface](https://phpunit.de/manual/current/en/test-doubles.html) here.
