### ISSUE TITLE
ResultSet strange behavior on sortBy

### ISSUE THREAD

**Issue by pedro-stanaka** [cakephp/cakephp#10392]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.15
* Platform and Target: Nginx, PHP 7.0, Postgres

### What you did
I tried to revert a ResultSet using sortBy method, because I need to simulate the following query:
```sql
SELECT *
FROM (
SELECT *
FROM posts
  WHERE id > 10
ORDER BY id DESC) as p
ORDER BY id ASC;
```

### What happened
By calling 
```php
<?php
$resultSet = $resultSet->sortBy('id', SORT_DESC);
?>
```
my serialized result comes with extra keys and not sorted by id desc.
Like so:
```javascript
"data": {
    "0": {
      "id": 18,
      "status_type_id": 1,
      "privacy_type_id": 2,
      "body": "emojis 😃 😃 😃 ",
      "user_id": 2,
      "created": "2017-02-25T14:23:50+00:00",
      "modified": "2017-02-25T14:23:50+00:00"
    },
    "1": {
      "id": 19,
      "status_type_id": 1,
      "privacy_type_id": 2,
      "body": "emojis 😃 😃 😃 ",
      "user_id": 2,
      "created": "2017-02-25T14:23:51+00:00",
      "modified": "2017-02-25T14:23:51+00:00"
    },
    "2": {
      "id": 20,
      "status_type_id": 1,
      "privacy_type_id": 2,
      "body": "emojis 😃 😃 😃 ",
      "user_id": 2,
      "created": "2017-02-25T14:23:51+00:00",
      "modified": "2017-03-08T23:45:26+00:00"
    }
  },
```

### What you expected to happen
My serialized data should be ordered by id. BTW, if I use SORT_ASC everything looks ok.

**Comment by lorenzo** [comment]
The reason for this is that `sortBy` preserves keys. Unfortunately php arrays are crazy in that they are both lists and dictionaries, so when converted to json, php makes the decision dynamically on whether to see the array as a dictionary or a as a list. In this case it chooses to see it as a dictionary.

To prevent this problem you can help PHP by re-indexing the collection without keys:

```php
$resultSet = $resultSet->sortBy('id', SORT_DESC)->compile(false); // false means "no keys"
```

**Comment by pedro-stanaka** [comment]
Thanks for the quick response (as usual) @lorenzo , doing like you said really worked... :+1: :smile:

**Comment by ravage84** [comment]
@lorenzo could it be useful to add your code snipped to the Cookbook as a hint?

Possible here:
https://book.cakephp.org/3.0/en/core-libraries/collections.html#sorting

Or may be even here:
https://book.cakephp.org/3.0/en/core-libraries/collections.html#Cake\Collection\Collection::compile
