### ISSUE TITLE
DebugKit's SQL Log shows boolean values as 0 and 1, which PostgreSQL doesn't like

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10394]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2, DebugKit 3.9.2
* Platform and Target: PostgreSQL

### What you did
Any query involving boolean conditions

### What happened
When I see the generated query in DebugKit's SQL Log "true" values show as 1, "false" as 0... When I copy this query to execute in PostgreSQL console it gives syntax error, which is annoying.

### What you expected to happen
Be able to copy a valid query from the SQL Log into PostgreSQL console

**Comment by markstory** [comment]
This issue was moved to cakephp/debug_kit#508
