### ISSUE TITLE
if any method exists in the controller, no action is scaffolded

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10395]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2 / bake 1.3.1

### What you did
cake bake template MyController

The controller had one other method not index,view or edit

### What happened
index,view,edit actions where not scaffolded

### What you expected to happen
if the controller doesn't have index,view or edit action it seems they should be scaffolded.

**Comment by ADmad** [comment]
CakePHP 3.x doesn't have any scaffolding feature like 2.x.

**Comment by inoas** [comment]
You can take a look at CRUD and possibly CRUD VIEW instead

**Comment by siran** [comment]
By scaffolding I mean baking the CRUD. If any action exists on the controller then nothing is baked. 

I used `bin/cake bake template all MyController --theme MyTheme --force`

I had to change my shell script to do 3 different bakes `bin/cake bake template $action MyController`, where action=[index, edit, view], so as to force cakephp into baking the basic actions.

**Comment by ADmad** [comment]
Bake doesn't modify existing files either. Deciding what parts of PHP code to modify is no easy task.

**Comment by siran** [comment]
I agree it shouldn't overwrite existing files without asking, unless --force is used.

However I believe that simply doing an array_diff between the MyController's and AppController's methods is overly simplistic (`cakephp\bake\src\Shell\Task\TemplateTask.php, line 224`):
```
        if (class_exists($this->controllerClass)) {
            $methods = array_diff(
                array_map(
                    'Cake\Utility\Inflector::underscore',
                    get_class_methods($this->controllerClass)
                ),
                array_map(
                    'Cake\Utility\Inflector::underscore',
                    get_class_methods($base . '\Controller\AppController')
                )
            );
        }
        if (empty($methods)) {
            $methods = $this->scaffoldActions;
        }
```

It might be better to check if the index/edit/view methods are defined and if not bake them.

At least that was what I expected, I had to debug the `bake` command to understand why the `$this->scaffoldActions` were not being baked... It turned out, as I said previously, that the views were not being baked because there was a single myMethod() defined in the MyController (!).

**Comment by dakota** [comment]
I think that bake should definitely **not** create template files for actions/methods that don't exist.
