### ISSUE TITLE
a way to check if value is correct in cookie

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10407]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x or 3.next

### What you did
check if value is correct in cookie

### What happened
`$this->Cookie->check()` is for check a value is set ( `issset()` ) 
`$this->Cookie->read()` read a value or return `''` for invalid cookie 
`valid value` value that is not changed by user (encrypted cookie)
for checking a cookie value (check valid value) we should use this form
```
        if($this->Cookie->check('name')){
           $read=$this->Cookie->read('name');
            if(!empty($read)){
                      //use cookie value 
            }
        }
```

### What you expected to happen
i looking for a way like 
```
        if($this->Cookie->checkAndValid('name')){
           $read=$this->Cookie->read('name');
        }
```
(in cookie component or new http version)

**Comment by markstory** [comment]
Using `empty()` is not going to be universally 'valid' though. `empty()` considers '0' to be false which can be quite useful in cookies to indicate false. Perhaps we should be using `strlen()` instead?

**Comment by saeideng** [comment]
`empty()` is just a sample
i searched on core but I not found a way ( method )
why returned `''` for invalid cookie probably `null` is good 
Or `strlen()` is good if that returned `''`  
but check this in `check()` or new method ? or in new http version

**Comment by saeideng** [comment]
please implement a method /or check for valid cookie  in your related new PR(s) (Http version)

**Comment by markstory** [comment]
How are we defining 'valid' though?

**Comment by inoas** [comment]
`$read=$this->Cookie->read('name');`
Could return CookieClass::INVALID if nothing was found? Then we can check against that, the rest of values like `''`, null, false, 'null', 0, '0', '0.0' are then valid depending on what you want to do ;)?

**Comment by saeideng** [comment]
If we have object instead of array in http version
Probably we can use property for this like entity::error

**Comment by markstory** [comment]
We have a way to check that cookies exist though. Determining if a cookie is 'valid' implies that there is some validation being applied to the values as well. My argument is that we as framework authors cannot make assumptions on what is 'valid' for cookie values.

**Comment by saeideng** [comment]
Oh,i means of 'valid' successfully passing from security (encrypt)

**Comment by saeideng** [comment]
$this->Cookie->readIfDecodePassed()  :)

**Comment by inoas** [comment]
Maybe:
- `$this->Cookie->get('name')`, // returns value or returns CookieNotFoundException or CookieNotDecodableException instead of throwing it as false, -1 etc can be a valid value.
- `$this->Cookie->getOrFail('name')` // returns value or throws decoding exception or not found 
- `$this->Cookie->check('name')`, // returns false if not found or not decoable
- `$this->Cookie->exists('name')` // returns true or throws CookieNotFoundException or CookieNotDecodableException

**Comment by markstory** [comment]
Closing as the work done as part of #10406 covers these changes.
