### ISSUE TITLE
postgresql: NUMERIC field in database appears as float when debug($entity)

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10404]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.3 / Postgresql 9.4

### What you did
1- defined a field as type NUMERIC(1) in PostgreSQL database
2- did a find() over the table

### What happened
when I debug() over the query the field appears as float:
``` 
...
'sgn' => (float) -1,
...
``` 

### What you expected to happen
should appear as integer

**Comment by markstory** [comment]
`NUMERIC` maps to a 'decimal' type in CakePHP which is represented as floats in PHP userspace. Using integer values would truncate any data after the decimal point which would be not be acceptable for most users.

If you have NUMERIC columns that you want to always be mapped to integers, you should reconfigure the column in your table's `_initializeSchema` hook method.
