### ISSUE TITLE
authError does not translate

### ISSUE THREAD

**Issue by mitra-razmara** [cakephp/cakephp#10402]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
"name": "cakephp/cakephp",
            "version": "3.4.2",
            
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.
xampp, mysql

### What you did
I think I find a bug. In my program, everything except authError translate correctly. I tried to translate it in "vendor\cakephp\cakephp\src\Controller\Component\AuthComponent".
So I changed Authcomponent

before change

```
protected function _setDefaults() {`
$defaults = [
...
'logoutRedirect' => $this->_config['loginAction'],
'authError' => __d('cake', 'You are not authorized to access that location.')
...
```

after change

```
protected function _setDefaults() {
$authError = __d('cake', 'You are not authorized to access that location.');
echo $authError;
$defaults = [
...
'logoutRedirect' => $this->_config['loginAction'],
'authError' => $authError
...
```

### What happened
`echo $authError` works.
`'authError' => $authError` does not work and flash message does not translate.

result
`شما به این بخش دست‌رسی ندارید.`
`You are not authorized to access that location.`

### What you expected to happen
Both $authError translating.

result
`شما به این بخش دست‌رسی ندارید.`
`شما به این بخش دست‌رسی ندارید.`

**Comment by ADmad** [comment]
You can just wrap the error message in translate function and set `authError` when configuring the component. E.g.
```php
$this->loadComponent('Auth', [
    'authError' => __('You are not authorized to access that location.'), 
   ...
]);
```

**Comment by markstory** [comment]
Closing as there is an existing way to add translated messages, or customize the text of your error messages.

**Comment by mitra-razmara** [comment]
I did but it does not work. I add some codes to show what happened.
`public function initialize() {`
`   if (function_exists('__')) {`
`      echo "function exists.<br>";`
`      echo __('You are not authorized to access that location.');`
`   }`
`   $this->loadComponent('Flash');`
`   $this->loadComponent('Cookie');`
`   $this->loadComponent('Auth', [`
`      'loginRedirect' => ['controller' => 'Stages' , 'action' => 'show'],`
`      'logoutRedirect' => ['controller' => 'Pages' , 'action' => 'home'],`
`      'authError' => __('You are not authorized to access that location.'),`
`   ]);`
`}`

default.po
`msgid "You are not authorized to access that location."`
`msgstr "شما به این بخش دست‌رسی ندارید."`

result:
`function exists.`
`You are not authorized to access that location.`

The message does not translate.

**Comment by markstory** [comment]
I tried this same configuration locally and I saw a translated message.

Have you tried checking the value of `$this->Auth->getConfig('authError')` after you load the component? Also check that your locale data is being loaded with `debug(__('You are not authorized to access that location.'))`.

**Comment by vnt** [comment]
I'm sorry, I have the same problem

**Comment by koffisani** [comment]
This can help https://stackoverflow.com/questions/33058028/change-message-you-are-not-authorized-to-access-that-location-in-plugin-caked/33059688#33059688
