### ISSUE TITLE
3.next - Consolidate CookieCollections

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10406]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

CakePHP 3.5.0 will feature a new set of cookie objects that provide an object-orienated interface to building and using HTTP cookies. As of #10328 we have a few different Cookie 'collections'. I'd like to unify those collections with the goal of only having 1 single cookie collection, as I don't think the use-cases we have require 4 classes.

### Use Cases for a CookieCollection

CookieCollections are used in a few different places in CakePHP:

1. In an Http\Client as a cookie jar where state is retained between client requests.
2. Adding cookies to a Controller Response.
3. Reading cookie data from a ServerRequest.

Each use case requires some common methods and some use-case specific methods.

### Generic Methods

* Iteration (IteratorAggregate)
* `has($key)` - Check if a cookie exists
* `get($key)` - Get a cookie
* `remove($key)` - Remove a cookie
* `add($cookie)` - Add a cookie

### Methods specific to Http\Client usage

This is the most complex use-case to afford as there are backwards compatibility concerns. The new methods & backwards compatibility behavior required are:

* `addFromResponse($response, $request)` - Add cookies from a response. A request is needed to infer the path and domain of cookies that have not included it. Currently this method is called `store()`. This alias/signature would be deprecated.
* `addToRequest($request)` - Apply all the cookies matching this request. Currently `Http\Client\CookieCollection` calls this method `get($url)`. This behavior for `get()` would be deprecated and could be shimmed by looking for cookie 'names' that contain the `://` URL sub-pattern. Cookies names containing `://` are very rare, and we can use this as a sniff to enable backwards compatible behavior case libraries that consume `Http\Client\CookieCollection`.

These methods allow a CookieCollection to function as a 'cookie jar' for the client. Covering another use case currently covered by a standalone class. 

### Methods specific to adding cookies to a Controller Response

* `addToResponse($response)` - Add cookies in the collection to a response.

### Methods specific to Reading cookie data from a ServerRequest

* `createFromRequest($request)` - Build a new CookieCollection from a request object.

All of the above methods could be implemented in a single class allowing us to streamline how users have to interact with cookies in CakePHP even further.

### Edits

* Removed `all()`. I don't have any use cases for it.

**Comment by robertpustulka** [comment]
Regarding Http\Client use cases:
- `addFromResponse($response, $request)` this would mutate current collection?
- `addToRequest($request)` this would return a new request with modified headers?

**Comment by saeideng** [comment]
> Generic Methods

also https://github.com/cakephp/cakephp/issues/10407

**Comment by burzum** [comment]
> All of the above methods could be implemented in a single class allowing us to streamline how users have to interact with cookies in CakePHP even further.

I'm OK with but but the only solution I could think of right now is a singleton which has it's downsides as well. A "service" like object attached to the request as attribute might work as well but then you don't have access to the response either.

For what you want to do I think the best thing would be a new cookie component, because the controller layer is probably for cookies the most likely place to be read and written by a framework user. So we could attach the related collection as attribute to request and response, this would make them virtually everywhere available and have the component for a streamlined convenient access in the controller layer.

**Comment by markstory** [comment]
@robertpustulka Yes to both questions. CookieCollections currently and in the future would be mutable (unlike proper `Collection\Collection` objects). I felt this was acceptable as they also lack all the methods of standard collections as well. I'm open to not using 'collection' if you think people will be confused.

**Comment by markstory** [comment]
> For what you want to do I think the best thing would be a new cookie component, because the controller layer is probably for cookies the most likely place to be read and written by a framework user. So we could attach the related collection as attribute to request and response, this would make them virtually everywhere available and have the component for a streamlined convenient access in the controller layer.

I was thinking that the new cookie collection could be exposed by methods on both the request and response providing a reasonable way to integrate the new cookie objects into the request/response.  

I'm less interested in the component use cases, and more interested in consolidating the code we have in both `Http\Client` the cookie collections in `Http\Cookie\` and making the core request/response objects more useful. Having object based cookies that are only used in a component seems like a missed opportunity.

**Comment by saeideng** [comment]
i am :+1: with 

>  integrate the new cookie objects into the request/response.

**Comment by robertpustulka** [comment]
@markstory OK. Another question: should we expose cookie object/collection mutation for server request cookies? These are just `name => value` and readonly. AFAIR we had this issue the last time we tried to rework cookies.

**Comment by markstory** [comment]
@robertpustulka I think we'd keep the existing key/value interface, and also allow people to use objects. We will be lacking a lot of information for request cookies, but we'll have enough to build objects.

**Comment by markstory** [comment]
Closing as I think this is complete.

**Comment by robertpustulka** [comment]
@markstory I have some concerns about using non-interface `toArray*()` methods. I'll address this issue in another PR and then we could close this, OK?

**Comment by markstory** [comment]
@robertpustulka Sounds good to me.

**Comment by markstory** [comment]
This is complete now.
