### ISSUE TITLE
Inconsistent default 'safe' for `scriptBlock()` and `scriptStart()`

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#10416]
The default was changed in 3.4 for one method, but not the other:

```php
    public function scriptBlock($script, array $options = [])
    {
        $options += ['safe' => false, 'block' => null];
…
```

```php
    public function scriptStart(array $options = [])
    {
        $options += ['safe' => true, 'block' => null];
…
```

I suggest to adapt scriptStart() to ensure consistent behavior with scriptBlock().

**Comment by ADmad** [comment]
Would you like to make a PR with the required change?

**Comment by dereuromark** [comment]
Does this need to go into 3.5 for BC reasons now?
Or do not many expect this to be that default value?

**Comment by ypnos-web** [comment]
As a user I expected the proposed behavior after reading the migration guide. The current behavior came to me as a surprise. So my suggestion would be to just fix it right away.

I will do a PR tomorrow.
