### ISSUE TITLE
Wrong index from find('list')

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10418]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9.
* Platform and Target: Linux, Apache, MySQL.

### What you did
The database contains records with ids starting from 0 (not from 1).
```
$params = array(
	"fields" => array("my_column", "id"),
);
$data = $this->find("list", $params);
```

### What happened
The query above returns the list of records but one is wrong - the record that has id 0 in the database has id 100 in $data. The last id in the database is 99.

### What you expected to happen
I would expect id to be 0 in $data.

**Comment by markstory** [comment]
I've added a test for the key=0 case and wasn't able to reproduce the dropped key. Could you help in providing a way to reproduce the problem you're seeing?

**Comment by bancer** [comment]
@markstory I commented in your [commit](https://github.com/cakephp/cakephp/commit/9dbeeaa1fa9e23042192eb1a033b526f4fd69003).

**Comment by markstory** [comment]
I changed the test around, but I'm still not able to get incorrect data. See c5e31e590df0673d60e931932abd4fcf28f8134a

**Comment by bancer** [comment]
The primary key column should have 0 value in ArticleFixture. Notice `'id' => '0'`:
```
public $records = array(
	array('id' => '0', 'user_id' => 1, 'title' => 'Zeroth Article', 'body' => 'Zeroth Article Body', 'published' => 'Y', 'created' => '2007-03-18 10:39:23', 'updated' => '2007-03-18 10:41:31'),
	array('user_id' => 1, 'title' => 'First Article', 'body' => 'First Article Body', 'published' => 'Y', 'created' => '2007-03-18 10:39:23', 'updated' => '2007-03-18 10:41:31'),
	array('user_id' => 3, 'title' => 'Second Article', 'body' => 'Second Article Body', 'published' => 'Y', 'created' => '2007-03-18 10:41:23', 'updated' => '2007-03-18 10:43:31'),
	array('user_id' => 1, 'title' => 'Third Article', 'body' => 'Third Article Body', 'published' => 'Y', 'created' => '2007-03-18 10:43:23', 'updated' => '2007-03-18 10:45:31')
);
```

In the test:
```
$result = $model->find('list', array(
    'fields' => array('title', 'id')
));
```
Notice 'id' (not 'user_id').

**Comment by markstory** [comment]
Primary key values of `0` are pretty poorly supported in general across CakePHP, and might not be something we can fix.

**Comment by bancer** [comment]
It seems that setting [NO_AUTO_VALUE_ON_ZERO](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_value_on_zero) MySQL mode solves the problem.

**Comment by dereuromark** [comment]
Is this (and the PR along with it) really something we want to support?
Afaik we always said 0 based keys are not something valid and should not be used - they also make other parts of the framework and code fail, even if this specific DB issue would be resolved.

I am for closing.

**Comment by bancer** [comment]
For the record, that's how I solved the problem in the fixture file:
```
	public function insert($db) {
		$db->query('SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE="NO_AUTO_VALUE_ON_ZERO"');
		$result = parent::insert($db);
		$db->query('SET SQL_MODE=@OLD_SQL_MODE');
		return $result;
	}
```
