### ISSUE TITLE
Router::parse() deprecated

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#10415]
In 3.4 the method `Router::parse(string)` was deprecated for `Router::parseRequest(ServerRequestInterface)`.

How to parse an URL without the deprecated method?
My use case: `Router::parse($this->request->referer(true));`

**Comment by markstory** [comment]
You have to use the deprecated method, or make a new request object and call the new method.

**Comment by wschwarte** [comment]
I just had the same issue. You can call the routeCollection directly:  $parsed_url = Router::getRouteCollection()->parse($refer_url);

**Comment by ypnos-web** [comment]
For my use case I did this:

```php
    $req = new ServerRequest($this->request->referer(true));
    return Router::parseRequest($req);
```

**Comment by berarma** [comment]
Why deprecate this method?

**Comment by markstory** [comment]
Because it was taking attributes from the request. I think the parseRequest() method that works on the entire request is a better api as it has more context which is required for features like hostname matching.

**Comment by berarma** [comment]
OK, so I guess the safest way to replace this method call would be:

```php
\Cake\Routing\Router::parseRequest($this->request->withUri(new \Zend\Diactoros\Uri($url));
```

Since the ```url``` parameter in the ```ServerRequest``` constructor is deprecated too.

Thanks.

**Comment by ypnos** [comment]
What kind of context will this add from `$this->request()`? I wouldn't like to drag current request context into the route originating (in my example) from a previous, unrelated request.

What is the recommended way of creating a request object from a URL in 4.x?

**Comment by markstory** [comment]
@berarma Only the *string* parameter is deprecated `new ServerRequest(['url' => '/path'])` will continue to be supported.

@ypnos The hostname, port and scheme could now be used in route matching, which is required for subdomain/domain specific routes.

What use-cases/scenarios have you creating new request objects? I'm currently of the opinion that applications shouldn't need to create request objects.

**Comment by ypnos** [comment]
You can see my use-case from opening comment of this issue: I simply want to parse the referer URL to get a route.

**Comment by markstory** [comment]
Ok. You can make a new request with `new ServerRequest(['url' => $url])` then. You will not be able to match against domain based routes though. To do that you'd need to provide more context to the request constructor.

**Comment by ypnos** [comment]
>      * - ~~`url`~~ The URL without the base path for the request. This option is deprecated and will be removed in 4.0.0
Also deprecated.

**Comment by markstory** [comment]
I'll get that corrected. It turned out we couldn't remove it as easily as we had hoped.
