### ISSUE TITLE
TranslationField gets translated field alias even on default language

### ISSUE THREAD

**Issue by Robertroid** [cakephp/cakephp#10421]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Hey guys,
I've found that the TranslationField method from TranslateBehavior gets the translation-aliased name from the relationship with i18n table, even when using the default locale on App.php, as seen [here](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TranslateBehavior.php#L436).
It would be good if the function returns early just the normal field alias if the current locale for the implementing table matches the default locale.

Edit; I'm using CakePHP 3.4.3

**Comment by ADmad** [comment]
Would you like to submit a pull request to fix the issue?

**Comment by markstory** [comment]
How is this a defect/bug and not an optimization that could be made?

**Comment by Robertroid** [comment]
@markstory As said in the [documentation](https://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-in-another-language), the idea behind TranslateBehavior is that the default locale is stored in the main entity, while translations are overriding the respective fields. And this function is supposed to aid in that aspect, which isn't doing. Unless I understood something wrong.

Anyways, I'll submit a pull request as soon as possible.

**Comment by markstory** [comment]
Closing as #10427 is open now.
