### ISSUE TITLE
Is there a plan to support .env?

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10420]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

**Comment by markstory** [comment]
Presently we don't have plans to build it into the framework. There is built-in support for using environment variables, but not dotenv files that are parsed in PHP. The previous discussion on this is in cakephp/app#224 and cakephp/app#328

**Comment by slince** [comment]
Yes, it is not necessary ; But it is useful to deal with the difference between the production environment and the develop environment;

**Comment by ADmad** [comment]
As mentioned reading environment variables is already supported in `app.php`.  Can't you just include a lib in your app which read `.env` file and populates the environment vars?  What specific support do you need in core and why?

**Comment by slince** [comment]
@ADmad  I have done support in my project,(In fact, i have  expanded a lot of features include di and this) ; I just want cake core can support parsing `.env` by default;

**Comment by slince** [comment]
PS: People who are familiar with cake can write their own extensions, but those who have just learned do not have this ability， these people may abandon cake if they find that cake does not support certain features

**Comment by markstory** [comment]
@slince Would you agree that `.env` files are a more advanced/sophisticated feature though? They require understanding how to set environment variables in non-development environments and the limitations that environment variables impose.

One option that @jeremyharris came up with on slack could be to include commented out code that shows where/how a .env file could be loaded. The default `config/app.php` already uses `env()` for a number of commonly changed configuration options.

**Comment by slince** [comment]
@markstory   yeah, I know; I'm just answering @ADmad   question  (What do i need cake to do ?And why do that?) 

 I understand that supporting dotenv is just a icing on the cake; If cake core can support better, do not support also no problem;

**Comment by slince** [comment]
if cake is a full-stack framework， Support this may be better  :100:

**Comment by dereuromark** [comment]
@slince Most would probably prefer a plugin as opt-in here.

**Comment by inoas** [comment]
a `_.env.example` file with instructions would be good (.env would not even show up for starters)

**Comment by josegonzalez** [comment]
I'm going to make a PR to add commented out support for `.env` files, similar to how we allow people to uncomment and enhance inflector rules etc.

**Comment by slince** [comment]
😘😘😘that sounds good@josegonzalez


@dereuromark yeah  i have supported
