### ISSUE TITLE
Associations foreignKey with multiple keys in OR condition

### ISSUE THREAD

**Issue by stefanozoffoli** [cakephp/cakephp#10425]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.3
* Platform and Target: Windows XAMPP, php 5.6.8, mysql 5.6.24

### What you did
I'm developing a software with warehouse management and stock movements.
So people can have multiple warehouses, and in every warehouses can occur many stock movements.

I have a two tables like this:

```sql
CREATE TABLE `stock_movements` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
...
  `from_warehouse_id` int(11) unsigned DEFAULT NULL,
  `to_warehouse_id` int(11) unsigned DEFAULT NULL,
...
);
```

```sql
CREATE TABLE `warehouses` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
...
);
```

These are my models:
```php
class WarehousesTable extends Table
{
...
    public function initialize(array $config)
    {
        ...
        $this->hasMany('InboundStockMovements', [
            'className' => 'StockMovements',
            'foreignKey' => 'to_warehouse_id',
        ]);
        $this->hasMany('OutboundStockMovements', [
            'className' => 'StockMovements',
            'foreignKey' => 'from_warehouse_id'
        ]);
...
```

Given a warehouse, I'd like to show a list of stock movements, either inbound or outbound.

### What happened
I can't have a list of stock movements either inbound or outbound, but two different list, one only inbound, and one only outbound.

### What you expected to happen
I'd like to have a way to tell cakephp to have an association StockMovements, with multiple foreign keys in OR condition, something like this:

```php
class WarehousesTable extends Table
{
...
    public function initialize(array $config)
    {
        ...
        $this->hasMany('InboundStockMovements', [
            'className' => 'StockMovements',
            'foreignKey' => 'to_warehouse_id',
        ]);
        $this->hasMany('OutboundStockMovements', [
            'className' => 'StockMovements',
            'foreignKey' => 'from_warehouse_id'
        ]);
        $this->hasMany('StockMovements', [
            'className' => 'StockMovements',
            'foreignKey' => [
                'OR' => [
                    'to_warehouse_id',
                    'from_warehouse_id',
                ],
            ],
        ]);
...
```

That in the sql query, will produce:
```sql
SELECT 
  StockMovements.id AS `StockMovements__id`, 
  ...
FROM 
  stock_movements StockMovements 
WHERE 
  (
    StockMovements.to_warehouse_id in (1) 
    OR StockMovements.from_warehouse_id in (1) 
  ) 
ORDER BY 
  StockMovements.id DESC 

```

Thank you

**Comment by inoas** [comment]
````
            'foreignKey' => [
                'OR' => [
                    'to_warehouse_id',
                    'from_warehouse_id',
                ],
```
I don't think you can do that.

What you can do
- split the inbound and outbound movements into 2 tables / create assocs between them
- create a join table for all stock movements, create an assoc for that or alternative: use an sql view to create a union out of both (optional)

I think this is rather a case for the irc or slack channel, not so much a bug report.

**Comment by stefanozoffoli** [comment]
Thank you for your answer, 😄 

for now I created a third BTM table that associate warehouses and stock_movements, like this:

```sql
CREATE TABLE `stock_movements_warehouses` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `stock_movement_id` int(11) unsigned DEFAULT NULL,
  `warehouse_id` int(11) unsigned DEFAULT NULL,
);
```

```php
class WarehousesTable extends Table
{
...
    public function initialize(array $config)
    {
        ...
        $this->belongsToMany('StockMovements', [
            'foreignKey' => 'warehouse_id',
            'targetForeignKey' => 'stock_movement_id',
        ]);
...
```

So when I create a Stock Movement record, i also create 2 records in the BTM table.

I would prefer not to have an additional table, because in this case it could become a really populated table in a short time only for redundant data..

I think it could be a useful enhancement for the ORM, but I would understand if you'll close the ticket!

p.s. I removed the checkbox on "bug" 👍

**Comment by inoas** [comment]
You can join both assocs in one finder for instance with leftJoinWith().

You can create a direction soft enum (cakedc/enum) having values OUTBOUND or INBOUND. and then create 3 assoc of which two filter by the enum and one does not.

I'd encourage you to further discuss the matter in the communities help channel.

P.s.: maybe complex JOIN ON conditions in assoc setup would still be cool

**Comment by stefanozoffoli** [comment]
I think having the possibility to define complex join conditions would be awesome 👍
