### ISSUE TITLE
Repo: Use Github's enhanced license meta data

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10428]
Check: https://github.com/google/guetzli/blob/master/LICENSE
vs https://github.com/cakephp/cakephp/blob/master/LICENSE.txt
You can select the license like so: https://help.github.com/articles/licensing-a-repository/#disclaimer

This will add meta information that github will display and is useful for standardized licenses like GPL, MIT etc.

**Comment by thinkingmedia** [comment]
GitHub's license logic is just being dumb. I think the only thing different here is the `.txt` extension.

We should start a public protest and collect signatures to get GitHub to support `LICENSE.txt` files. I mean, we're CakePHP and if we can not impose our own standards onto other people then wheres the fun in that.

Either they start showing meta data for our license file, or we are moving to BitBucket.

**Comment by dereuromark** [comment]
I would drop the .txt extension - and all works just fine :)

**Comment by ADmad** [comment]
Extension doesn't seem to matter e.g. https://github.com/ADmad/cakephp-glide/blob/master/LICENSE.txt
