### ISSUE TITLE
Add UUID support for binary(16)

### ISSUE THREAD

**Issue by bluesuiter** [cakephp/cakephp#10432]
This is a (multiple allowed):

* [] bug
* [ ] enhancement
* [X ] feature-discussion (RFC)

Hello All,

### Why the binary UUID support is not added to 3.x. 

Even though it is better than char(36) performance wise, why it was dropped out from cakePHP.

Thank You,

**Comment by dereuromark** [comment]
This is a duplicte of https://github.com/cakephp/cakephp/issues/9502

**Comment by bluesuiter** [comment]
Do we have support for binary uuid for current version or not. Because I tried to generate UUID with binary(16) and binary(36) also but it was all in vain.
Although char(36) is working fine.

Thank You,

**Comment by dereuromark** [comment]
Please also see https://github.com/cakephp/cakephp/issues/7013

The main reason, as stated in the first linked ticket, is really just that no one took the time to do it.
Anyone in need and interested in getting this supported can help out and provide a PR or basic ground works here in forms of custom Type classes (see mine linked in the 2nd ticket as a very first basic draft).

**Comment by markstory** [comment]
We haven't added support for binary(16) as there is support fot native uuid types in postgres and the uuid type maps to char(36) in mysql. I don't know how we could preserve schema types if both char(36) and binary(16) are both interpreted as 'uuid' types.

**Comment by lorenzo** [comment]
If you are interested in implementing it, you can do something like this:

https://github.com/cakephp/cakephp/blob/8c94ea345d6083962266efffde7fdeb1e03b13ef/tests/TestCase/Database/ExpressionTypeCastingIntegrationTest.php

The only thing missing in that implementation is doing the bin packing and unpacking in the type class.

**Comment by inoas** [comment]
Nane it type uuidbinary or binaryuuid @markstory?

**Comment by markstory** [comment]
@inoas `binaryuuid` sounds fine. Just needs implementation and tests :smile:

**Comment by bluesuiter** [comment]
@markstory So that means if I use binary(16) as data type with Postgres, I will get UUID with CakePHP 3.4.3 without adding any third party code and special data handling code?

**Comment by markstory** [comment]
@bluesuiter Only after the `binaryuuid` is created. Presently you won't get the behavior you're describing as the new type hasn't been created.

**Comment by bluesuiter** [comment]
@markstory Hello Mark,
Is `binaryuuid` become the part of CakePHP now?

**Comment by inoas** [comment]
I haven't found time so did no one else, so far, it seems.

**Comment by markstory** [comment]
@bluesuiter No. No one has sent a pull request and this is not a feature I personally need/use.

**Comment by bluesuiter** [comment]
@markstory Please, keep this in 3.5 positively. I didn't started one of my dream project because I need this as a part of framework. I insanely in love with the ORM of Cake and don't want to use any other framework. I hope you will surely add `binaryuuid` support. GoodLuck.

**Comment by saeideng** [comment]
3.5.0-RC1 released 
so you can implement your custom adapter/class for this until having this in cake

**Comment by saeideng** [comment]
like
https://github.com/cakephp/cakephp/blob/master/src/Database/Type/UuidType.php

**Comment by robertpustulka** [comment]
@bluesuiter can you implement this feature and send a pull request?

**Comment by bluesuiter** [comment]
@robertpustulka I am not sure, about this :(

**Comment by robertpustulka** [comment]
@bluesuiter read a page about contributing to the project: https://book.cakephp.org/3.0/en/contributing.html

**Comment by bluesuiter** [comment]
@robertpustulka I was unable to figure out how should I test it on the local server.

**Comment by robertpustulka** [comment]
@bluesuiter you need to write tests for new features:
https://book.cakephp.org/3.0/en/development/testing.html

Then you'll need to run PHPUnit to run tests, ie `vendor/bin/phpunit`

**Comment by markstory** [comment]
Closing as this has a pull request open now.
