### ISSUE TITLE
Add BelongsToMany::getJoinTable()/setJoinTable()

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10436]
I'm looking at the methods introduced with CakePHP 3.4. As for the tables, it all seems perfect, except for one thing: there is a `joinTable` option, but there are no `getJoinTable()`/`setJoinTable()` methods. Instead there is the `junction()` method and no `getJunction()`/`setJunction()` methods.

Clearly **this is not a problem**. But it seems to me to be a little confusion, especially when compared to other methods that have recently been renamed.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/9978

Please feel free to help out and make this more consistent. You can PR more of those improvements towards a clean API for 3.5 branch here for example.

**Comment by mirko-pagliai** [comment]
So I wrote in the other thread. I feel better.
