### ISSUE TITLE
DboSource should be check type in associations

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#10437]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.6
* Platform and Target: WAMP7

### What happened

> Warning (2): Invalid argument supplied for foreach() [CORE\Cake\Model\Datasource\DboSource.php, line 1569]

In line 1569 is

> foreach ($assocResultSet as $data) {

I think, one line before should by `if` statement like this:

> if (is_array($assocResultSet)) {

Because stack methods `queryAssociation();` / `read();` / `_fetchHasMany();` / `fetchAll();` can return `false `on line 699.

**Comment by markstory** [comment]
How can someone reproduce this

**Comment by kicaj** [comment]
Hmmm... I come back to the beginning:)

I use Cake 2.9.6 with built-in datasource database Sqlserver driver and prepare the simplest conditions with Containable Behavior, like this:

```
$lessonCategories = $this->Lesson->LessonCategory->find('all', array(
	'fields' => array(
		'LessonCategory.parent_id',
		'LessonCategory.slug',
		'LessonCategory.name',
		'LessonCategory.description',
		'LessonCategory.state'
	),
	'contain' => array(
		'LessonCategoryChildren' => array(
			'fields' => array(
				'LessonCategoryChildren.' . $this->Lesson->LessonCategory->primaryKey,
				'LessonCategoryChildren.name',
				'LessonCategoryChildren.state'
			),
			//'Lesson' => array(
			//	'fields' => array(
			//		'Lesson.' . $this->Lesson->primaryKey
			//	)
			//)
		),
		'Lesson' => array(
			'fields' => array(
				'Lesson.' . $this->Lesson->primaryKey,
				'Lesson.name',
				'Lesson.finish',
				'Lesson.state'
			)
		)
	),
	'order' => array(
		'LessonCategory.created' => 'DESC'
	),
	'limit' => 4,
	'recursive' => -1
));
```

...and when i uncommented 5 lines i get strange SQL query like this:

**Error: SQLSTATE[42000]:** [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The multi-part identifier "LessonCategoryChildren__state.id" could not be bound.

**SQL Query:** SELECT [LessonCategoryChildren].[id] AS [LessonCategoryChildren__id], [LessonCategoryChildren].[name] AS [LessonCategoryChildren__name], [LessonCategoryChildren].[state] AS [LessonCategoryChildren__state], [LessonCategoryChildren__state].[id] AS [LessonCategoryChildren__state__id], [LessonCategoryChildren].[parent_id] AS [LessonCategoryChildren__parent_id] FROM [lessons_lesson_categories] AS [LessonCategoryChildren] WHERE [LessonCategoryChildren].[parent_id] IN (20, 19, 18, 17)

Why this Sqlserver driver prepare this: 
`LessonCategoryChildren__state.id` (`[LessonCategoryChildren__state__id]`)?

Then I found other MSSQL driver for Cake 2 and It's works but I get errors like what I described in my first post...

**Comment by gacosta87** [comment]
I'm facing the same problem when working with SQL Server and trying to specify what columns to fetch in the fields array when using containable behavior. Did you solve it? I'm forced to use SQL Server for this project.

**Comment by kicaj** [comment]
Unfortunately... but my solutions is to remove `fieds` array from `find();` and it's helps.

**Comment by gacosta87** [comment]
Yes, that's what I did, I was trying to cut down the fields to only the ones I need. Thank you though.

**Comment by JelleKeizer** [comment]
Had the same error, i fixed it with adding a conditions array 'conditions'=>array()

**Comment by dereuromark** [comment]
Can you make a PR here? That would be awesome.
