### ISSUE TITLE
3.x DATETIME(6) support

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10439]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.3
* Platform and Target: MariaDB 10.1, PHP 7.1.2

### What you did
```sql
CREATE TABLE `cms_documents` (
  `id` char(36) CHARACTER SET ascii NOT NULL,
  `revision_id` char(36) CHARACTER SET ascii NOT NULL,
  `created` datetime(6) NOT NULL,
  `is_published` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`,`revision_id`),
  UNIQUE KEY `uniq_create` (`id`,`created`),
  UNIQUE KEY `published_revision` (`is_published`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### What happened
Even if I manually adapt the datetimes with microseconds I still get back a regular datetime.
- E.g. database: 2017-03-21 16:52:49.123123
- Returns: 2017-03-21 16:52:49

### What you expected to happen
- To get back 2017-03-21 16:52:49.123123
- Also to be able to save 2017-03-21 16:52:49.123123 - does Chronos support that anyway?

**Comment by dakota** [comment]
What version as of PHP are you running? Afaik, only 7.1 supports microseconds in Date objects.

**Comment by inoas** [comment]
I am running `PHP 7.1.2-4+deb.sury.org~trusty+1 (cli) (built: Mar  2 2017 13:23:06) ( NTS )`

**Comment by inoas** [comment]
Console:
```php
> var_dump((new \Datetime)->format('Y-m-d\TH:i:s.u'));
string(26) "2017-03-21T17:13:54.093858"
```

In `beforeSave()`
```php
        $entity->set('created', \Cake\I18n\Time::createFromFormat(
            'Y-m-d\TH:i:s.u',
            (new \Datetime)->format('Y-m-d\TH:i:s.u'),
            'America/New_York'
        ));

... but microseconds are not being persisted to the database (instead it saves 2017-03-21T17:13:54.000000)

**Comment by markstory** [comment]
I suspect that the Datetime Type objects are eliding the microseconds when converting Time instances into strings to be inserted into the db.

**Comment by inoas** [comment]
I have checked `DateTimeType:toDatabase()`: `return $value->format($this->_format);`

Changing that to to ``$value->format('Y-m-d\TH:i:s.u');` as a quick hack works.

`protected $_format = 'Y-m-d H:i:s';` isn't settable through any setter or any means I know of.

I will try to add a custom type like here: https://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-types and report back again.

### Question/Suggestion

Could we simply change $_format to `'Y-m-d\TH:i:s.u'` - it should work even if no milliseconds are supplied (then appended by .000000) or the database field not taking them (then the miliseconds are cut)?

**Comment by inoas** [comment]
```php
<?php
namespace App\Database\Type;

use Cake\Database\Type\DateTimeType as CakeDateTimeType;

/**
 * Datetime type converter.
 *
 * Use to convert datetime instances to strings & back.
 */
class DateTimeType extends CakeDateTimeType
{

    /**
     * String format to use for DateTime parsing
     *
     * @var string
     */
    protected $_format = 'Y-m-d\TH:i:s.u';

}
```
boostrap.php `Type::map('datetime', 'App\Database\Type\DateTimeType');`
Does the job for writing.

For reading this however returns `2017-03-21 21:06:20.000000` instead of `2017-03-21 21:06:20.025868` (in bootstrap.php):

```php
$defaultJsonDateTimeFormat = 'yyyy-MM-dd HH:mm:ss.SSSSSS';
Time::setJsonEncodeFormat($defaultJsonDateTimeFormat);
FrozenTime::setJsonEncodeFormat($defaultJsonDateTimeFormat);
```

**Comment by markstory** [comment]
Do the created time objects have microseconds inside them? Perhaps its just an issue with the string formatting?

**Comment by inoas** [comment]
@markstory yes, I think it is a formatting issue:

Patching -> Database: created: 2017-03-23 11:52:01.510044
```php
        $saved = $this->CmsDocuments->save($cmsDocument, [
            'associated' => ['CmsDocumentsTranslations', 'CmsElements']]);
        logdebug($cmsDocument->created->format('Y-m-d\TH:i:s.u'));
        logdebug((new \DateTime())->format('Y-m-d\TH:i:s.u'));
```

debug.log:
```
2017-03-23 11:57:53 Debug: '2017-03-23T11:57:53.169024'
2017-03-23 11:57:53 Debug: '2017-03-23T11:57:53.188525'
 
```

**Comment by markstory** [comment]
Looks like a PHP bug, and some missing features in CakePHP around db insertion.

**Comment by inoas** [comment]
@markstory 
1. For reading/formatting it is either with ICU or with PHP in terms of `IntlDateFormatter`/`IntlDateFormatter::format()` not behaving correctly.
I am currently struggling with downgrading from 7.1.3 to 7.1.2 (because on 7.1.3 datetime itself misses microseconds) on my puphpet box.

2. For persisting to the database all required is a quick fix to https://github.com/cakephp/cakephp/issues/10439#issuecomment-288219530 (at least when I manually create the Time instances in my RevisionsBehavior like so: `$entity->set('created', \Cake\I18n\Time::instance((new \Datetime)));`)

**Comment by inoas** [comment]
Due to how ICU works - **after** PHP will be bugfixed (ref: https://github.com/php/php-src/pull/2432) - it seems we can only get persisting datetines to 6 digits but outputting via ICU parsing/formatting will be stuck at 3 digits of fractions of seconds.

Any idea for a sane workaround?

**Comment by inoas** [comment]
So with https://github.com/php/php-src/commit/1ce355abb648dc6814ddd00876085617a946396f hitting we can get to datetime(3) support, aka 3 microseconds.

**Comment by chinpei215** [comment]
@inoas I appreciate you report this issue to PHP :clap:

Reading ICU documents, probably, there are no workarounds:
> S fractional second - truncates (like other time fields) to the count of letters when formatting. Appends zeros if more than 3 letters specified. Truncates at three significant digits when parsing

http://userguide.icu-project.org/formatparse/datetime

I think you may have to call `format()` method directly if you want to output microseconds.

**Comment by inoas** [comment]
What I suggest is: 3 fractions of seconds write/read support from cakephp (because that is consistent). Userland can increase write support to 6 fractions of seconds.

My current working setup:
MySQL: created DATETIME(6) NOT NULL
```php

$defaultJsonDateTimeFormat = 'yyyy-MM-dd HH:mm:ss.SSSSSS';
$defaultJsonDateFormat = 'yyyy-MM-dd';
Time::setJsonEncodeFormat($defaultJsonDateTimeFormat);
FrozenTime::setJsonEncodeFormat($defaultJsonDateTimeFormat);
Date::setJsonEncodeFormat($defaultJsonDateFormat);
FrozenDate::setJsonEncodeFormat($defaultJsonDateFormat);
```
// shows 3 fractions, then 3 nulls

```php
<?php
namespace App\Database\Type;

use Cake\Database\Type\DateTimeType as CakeDateTimeType;

/**
 * Datetime type converter.
 *
 * Use to convert datetime instances to strings & back.
 */
class DateTimeType extends CakeDateTimeType
{

    /**
     * String format to use for DateTime parsing
     *
     * @var string
     */
    protected $_format = 'Y-m-d\TH:i:s.u';

}
```

**Comment by inoas** [comment]
Ah ne 15... korrekt? Immernoch gut!

**Comment by inoas** [comment]
Try the above custom datetime class with:

```php
    protected $_format = 'Y-m-d\TH:i:s.u\Z';
```

**Comment by ADmad** [comment]
So with the PHP bug presumably solved this can be closed right?

**Comment by htstudios** [comment]
The PHP bug is gone, as can be seen here: https://3v4l.org/LYr48

### Works in conjunction with a custom DateTimeType class like shown above:

Setting the entities created field in newEntity/patchEntity like so:
```php
$newEntity->created = new \DateTimeImmutable();
```

### Setting it through timestamp behavior doesn't work

#### Tracing the Issue:

**`Cake\ORM\Behavior\TimestampBehavior::_updateField()`**

```php
        $ts = $this->timestamp(null, $refreshTimestamp);
        debug($ts->format('Y-m-d\TH:i:s.u'));
```
=> shows 6 digits for u

```php
debug((new $class($ts))->format('Y-m-d\TH:i:s.u'));
```
Shows 0000000 for the u digits.
That's the return value of _updateField, and $class is FrozenTime.

**In `FrozenTime::__construct()`**
```
            $time = $time->format('Y-m-d H:i:s');
```

Changing this to `'Y-m-d\TH:i:s.u'` made TimestampBehavior pass through the 6 u digits to MariaDB/MySQL.


#### More Inconsistencies

I found a few places where I wondered if we shouldn't internally set a more consistent and precise time.

**In `Cake\I18n\Time::__construct()`:**

Is:
```php
$time = $time->format('Y-m-d H:i:s');
```

Should be?
```php
$time = $time->format('Y-m-d\TH:i:s.u');
```

**In `Cake\Chronos\MutableDateTime::__construct()`:**

Is:
```php
$time = $testNow->format('Y-m-d H:i:s.u');
```

Should be?
```php
$time = $testNow->format('Y-m-d\TH:i:s.u');
```

There are 4 occurrences of of `'Y-m-d H:i:s.u'` in Chronos - should they all be converted to `'Y-m-d\TH:i:s.u'`

**Comment by inoas** [comment]
Afterwards to get JsonView to export correctly

```php
    //$defaultJsonDateTimeFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS"; // did not work
    $defaultJsonDateTimeFormat = "yyyy-MM-dd'T'HH:mm:ss.uuuuuu"; //works
    $defaultJsonDateFormat = "yyyy-MM-dd";
    Time::setJsonEncodeFormat($defaultJsonDateTimeFormat);
    FrozenTime::setJsonEncodeFormat($defaultJsonDateTimeFormat);
    Date::setJsonEncodeFormat($defaultJsonDateFormat);
    FrozenDate::setJsonEncodeFormat($defaultJsonDateFormat);
```

**Comment by freefri** [comment]
I am facing similar problem when formatting using the function `i18nFormat`

This line https://github.com/cakephp/cakephp/blob/1daf3c0854c139bac85d3535505cef6154f9d164/src/I18n/DateFormatTrait.php#L104 could be changed to `return (string)static::$formatters[$key]->format($date->format('U.u'));` to allow microseconds when formatting. This should not be a breaking change, since the date us already formatted again within the same line, but I am not sure if this could cause any new problem. 

This is a quick test:

```
$time = new FrozenTime('2014-07-06T13:09:01.523000+00:00');
$this->assertEquals('2014-07-06 13:09:01.523000', $time->format('Y-m-d H:i:s.u'));
$i18nFormat = $time->i18nFormat("yyyy-MM-dd'T'HH':'mm':'ss.SSSxxx", null, Languages::ENG);
$this->assertEquals('2014-07-06T13:09:01.523+00:00', $i18nFormat);
```


@markstory

**Comment by markstory** [comment]
@freefri This issue has been closed for 5 years, please open a new issue with the problem you're having.
