### ISSUE TITLE
Feature Request: Provide automatic XSS protection.

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#10449]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3

By default when outputting a variable, you need to do:
h($var)

Instead, provide the functionality of h() for all variables output in responses, unless explicitly stated. so you could just do:
$var

Similar to how Ruby on Rails templates works.

**Comment by inoas** [comment]
For entities maybe something can be done here: https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L135

And maybe the getter method could be made to then opt-out of auto-escaping.

But then rails as far as I know auto escapes all string objects in ERB context unless flagged safe or forced raw.

And then there is Twig.

But then for JSON the escaping would be different than for HTML or XML context, wouldn't it?

**Comment by dereuromark** [comment]
For normal PHP here it doesn't make any sense IMO.

If you want that, you can use existing template languages (see twig plugin and alike) which offer this out of the box. For PHP it is fair enough to manually wrap with h().

**Comment by markstory** [comment]
I use the TwigView plugin in situations where I need autoescaping. Autoeacaping in PHP templates would require some pre-processing to rewrite the template files, which can get complicated. Is there a reason you don't want to use twig or another templating library that provides autoescaping?

**Comment by burzum** [comment]
I don't think auto escaping on entities is handy. The only time you want to auto escape is when you echo data in HTML almost all other reposnes (JSON, XML, CSV...) don't need it. IMHO this will cause probably more trouble (constantly enabling/disabling auto escaping and forgetting to do so) than being a benefit. Further the template languages are IMHO just an overhead and for sure not less to type than plain php.

However, if you want to do it go ahead:

```php
trait EntityAutoEscapeTrait {
	protected $_autoEscape = false;
        public function enableAutoEscaping() {
		$this->_autoEscape = true;
	}
        public function disableAutoEscaping() {
		$this->_autoEscape = false;
	}
	public function &get($property) {
		return h(parent::get($property));
	}

}
```

**Comment by dereuromark** [comment]
Given the answers so far we can close this then.
