### ISSUE TITLE
Default value for __x() with context not returned if non default language translation is empty

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10440]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.3

I am not sure if this is desired behavior or not. I have pot and po files generated by Cake's i18n shell. 

I have following translation in non default language `pl` 

```
msgctxt "Navigation menu"
msgid "Search"
msgstr ""
```

And now, behavior is different depending on language beeing default or not.
 `__x("Navigation menu", "Search")`  gives me an empty string in language `pl`. If i switch to any other language, so the default lang would be picked up (default.pot in my case) default value "Search" is returned as I would expect it to be.

Defining translation for example like this
```
msgctxt "Navigation menu"
msgid "Search"
msgstr "test test"
```
will result in returning "test test" for `pl` and "Search" for default language.

**Comment by markstory** [comment]
You've asked the translation value to be `''` so that's what you should get. If you don't want `''` don't make it the translated value.

**Comment by Antoniossss** [comment]
But this is the casewhere translation is missing due to overlook. Besides behavior is inconsistent - for example __("Search") will give me the default value if I ommit the context. 

Up to you what to do about it anyway. Thanks

**Comment by markstory** [comment]
Pot files are never read when translating messages did you mean the po files instead? I might not be fully understanding the issue you are having. Do you have snippets of the po files and translation calls that aren't doing what you expect?

**Comment by Antoniossss** [comment]
I meant `po` files, yes.

And for example, lets have following snippet from `po` file (These are actuall snippets used in my app):
```
#: Template/Pages/home.ctp:29
msgid "home.story.short"
msgstr ""

#: Template/Layout/default.ctp:92;122
#: Template/Pages/home.ctp:14
msgctxt "Navigation menu"
msgid "Search"
msgstr ""
```

and lets have
```

<?= __("home.story.short") ?> // output: home.story.short
<?= __x("Navigation menu", "Search") ?> // output: empty string

```
Whats the difference here? Both translations are described as "empty string" like you have pointed out, but outcome is different.

**Comment by markstory** [comment]
Ok. That behaviour should be more consistent.

**Comment by markstory** [comment]
Returning '' was added incorrectly in #8932

**Comment by markstory** [comment]
pull request up.
