### ISSUE TITLE
CakeSocket cannot connect to TLS 1.2 only servers

### ISSUE THREAD

**Issue by RichieB2B** [cakephp/cakephp#10445]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.6 83e5ae522e792f8994637938de29bb553384e9c8
* Platform and Target: CentOS 6, rh-php56 (5.6.25)

### What you did
```
$HttpSocket = new HttpSocket($params);
try {
  $response = $HttpSocket->get('https://www.ssllabs.com:10303/');
} catch (Exception $e) {
  print $e->getMessage();  
}
```

### What happened
The `HttpSocket->get()` throws:
```
Unable to perform enableCrypto operation on CakeSocket
```

### What you expected to happen
The `HttpSocket->get()` should complete without problems.

This issue is caused by https://bugs.php.net/bug.php?id=73388 and exists in PHP >= 5.6.7.
The easy fix is to change the definition of [tls_client](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/CakeSocket.php#L95) to:
```
'tls_client' => STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
```
but this will only work for PHP >= 5.6.0. If support for PHP < 5.6.0 is still important a more elaborate patch is needed.

This issue probably also exists for [tls_server](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/CakeSocket.php#L99).

**Comment by markstory** [comment]
We need to continue supporting PHP 5.3+ in 2.x. Looks like we'll need to coalesce the various constants in the constructor.

**Comment by RichieB2B** [comment]
PHP < 5.6.0 does not have the individual `STREAM_CRYPTO_METHOD_TLSv1_*_CLIENT` constants. So using `STREAM_CRYPTO_METHOD_TLS_CLIENT` is the best way for those older versions.

**Comment by markstory** [comment]
Closing as a pull request is open now.
