### ISSUE TITLE
Keyword support for aggregate functions (function expressions)

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#10454]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.0

---

Currently it's not overly straightforward to generate function calls with keywords like `DISTINCT`, for example:

```sql
COUNT(DISTINCT column)
```

Expressions passed as arguments of function expressions are being wrapped into parentheses, and expressions with multiple conditions are being wrapped in parentheses themselves too, which makes it impossible to generate valid SQL using expressions that would generate snippets like `DISTINCT column`, it would end up as invalid SQL like:

```sql
COUNT(((DISTINCT column)))
```

So one is left with either using raw SQL snippets (and therefore loosing the ability to use identifier expressions), or building the function call manually using expressions (or custom expression classes), like

```php
$query
	->newExpr()
	->setConjunction('')
	->add('COUNT(DISTINCT')
	->add([new IdentifierExpression('column')])
	->add(')')
```

Given that all supported dialects do support keywords for some/all aggregate functions, this might be something that could be supported by the core.

I'd consider an interface like following to be quite handy:

```php
$query->func()->count(new IdentifierExpression('column'))->setKeyword('DISTINCT')
```

For reference:

* **https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html**
* **https://www.postgresql.org/docs/9.6/static/sql-expressions.html#SYNTAX-AGGREGATES**
* **https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql**
* **https://www.sqlite.org/lang_aggfunc.html**

**Comment by markstory** [comment]
Should we have a `countDistinct()` method? Or are there​ other places this keyword feature could be leveraged?

**Comment by ndm2** [comment]
I've just choosen `COUNT` as an example, there are many other aggregate functions that support keywords (see the linked docs), therefore I think a more generic solution would be reasonable.
