### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE

### ISSUE THREAD

**Issue by mrausch1978** [cakephp/cakephp#10455]
When trying to use composer to install cakephp I get the following:

Php version: 5.6.28
OpenSSL - 1.0.2k
os - mac and centos7 (tried it on both)

[Composer\Downloader\TransportException]                                                                  
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1  
  . OpenSSL Error messages:                                                                                
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                        
  Failed to enable crypto                                                                                  
  failed to open stream: operation failed

**Comment by markstory** [comment]
You are unable to make an ssl connection to packagist.org from your php setup. If this issue persists across multiple attempts you should look at how your php is setup. This is not an issue we can solve for you unfortunately.
