### ISSUE TITLE
$this->Auth->redirectUrl($redirect_url) doesn't save redirect URL

### ISSUE THREAD

**Issue by ictgtvt** [cakephp/cakephp#10465]
This is a (multiple allowed):

* [ ] enhancement
* [x] bug
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.4
* Platform and Target: Apache, PHP 7, Mysql

### What you did
I use `$this->Auth->redirectUrl($redirect_url)` to set redirect url but it not effect.

### What happened
I use `$this->Auth->redirectUrl($redirect_url)` to set redirect url but it not effect.

### What you expected to happen
I use `$this->Auth->redirectUrl($redirect_url)` set the destination a user should be redirected 

I already check in `\Cake\Controller\Component\AuthComponent::redirectUrl` but there are no code to execute saving redirect_url.

But i check that code in `\Cake\Controller\Component\AuthComponent::redirectUrl` of CakePHP 3.3.15, there is a line of code that save redirect url:
`$this->storage()->redirectUrl($redir);`

**Comment by dereuromark** [comment]
Please see https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#other-deprecations and https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#behavior-changes for the redirect URL info. That is now passed as query string in the URL instead of being persisted in the session.

> AuthComponent now uses a query string to store the redirect URL when an unauthenticated user is redirected to the login page. Previously, this redirect was stored in the session. Using the query string allows for better multi-browser experience.

**Comment by ictgtvt** [comment]
Thank @dereuromark . Should we update the document ? And i see that `AuthComponent::redirectUrl($url)', the `$url` parameters will be remove soon, because it's redundant now ? Now we just keep it for compatible, alright ?

**Comment by markstory** [comment]
@ictgtvt Yes the unused parameter is around for backwards compatibility. What would have helped clarify this change in the migration notes?

**Comment by ictgtvt** [comment]
@markstory I think this point should be emphasized in migration notes. I think we should change PHPDoc of that parameter to be depreciated and make a notice for user to migrate their code to behavior that use "redirect" parameter in query string.

**Comment by markstory** [comment]
I can make those updates @ictgtvt

**Comment by ictgtvt** [comment]
Thank you so much @markstory 👍

**Comment by markstory** [comment]
I took another look at the code, and the parameter for `redirectUrl()` is not deprecated or unused. It is used only when there is no query string value set. If used after login its behavior is the same, but it cannot be used outside of that scenario which is where the problem has come from.

**Comment by ictgtvt** [comment]
@markstory Excuse me, could you explain about the case when we have to use the parameter for `redirectUrl`? I really don't understand how is it used for now. Because I see that when `$url` parameter is set for `redirectUrl()`, the function just return the redirect url upon the `$url` parameter. And `redirectUrl()` doesn't save that `$url` to anywhere.
