### ISSUE TITLE
"Cannot unpack array with string keys" after switch to variadic in 3.4

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#10463]
* [x] bug
* CakePHP Version: https://github.com/cakephp/cakephp/releases/tag/3.4.0-RC1 https://github.com/cakephp/cakephp/commit/1f53eb67ea27f43d4c0ec3dbdac12cc363922c8d

### What you did
After upgrading 3.3 to 3.4 core, and related to variadic changes done in the related commit, I'm getting "Cannot unpack array with string keys". I was using compact to generate an array of data to be passed to a Mailer::send() method.

### What happened
Error: Cannot unpack array with string keys

### What you expected to happen
Keep it BC or fix docs and migration guide

My first reaction was suggesting array_values() but then I see http://php.net/manual/es/function.array-values.php#36837 so I guess the approach could be either:
* Add to migration guide and docblocks for the affected methods
* get back to call_user_func_array

What do you think?

**Comment by markstory** [comment]
Where would you expect to find this kind of information in thee migration guide? Would it be under behaviour changes?

**Comment by steinkel** [comment]
Yes, https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#behavior-changes would be a good place for this

**Comment by markstory** [comment]
Docs updated.
