### ISSUE TITLE
3.4.x Tests: plugin controller does not automatically load plugin table

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10477]
I don't know if this is a bug. I'm writing tests for a plugin controller (`\MeCms\Controller\PagesCategoriesController`) that has its plugin table (`\MeCms\Model\Table\PagesCategoriesTable`).

So:

```
$Controller = new PagesCategoriesController();
$Controller->index();
```

```
There was 1 error:

1) MeCms\Test\TestCase\Controller\PagesCategoriesControllerTest::testIndex
BadMethodCallException: Unknown finder method "active"

/home/mirko/Libs/Plugins/MeCms/vendor/cakephp/cakephp/src/ORM/Table.php:2204
/home/mirko/Libs/Plugins/MeCms/vendor/cakephp/cakephp/src/ORM/Table.php:1174
/home/mirko/Libs/Plugins/MeCms/src/Controller/PagesCategoriesController.php:39
/home/mirko/Libs/Plugins/MeCms/tests/TestCase/Controller/PagesCategoriesControllerTest.php:50
```

It does not find the `active` `find()` method. The problem is because it does not load the table provided by the same plugin.

Debug:

```
$Controller = new PagesCategoriesController($request);
dd($Controller->PagesCategories);
```

```
object(Cake\ORM\Table) {

        'registryAlias' => 'PagesCategories',
        'table' => 'pages_categories',
        'alias' => 'PagesCategories',
        'entityClass' => '\Cake\ORM\Entity',
        'associations' => [],
        'behaviors' => [],
        'defaultConnection' => 'default',
        'connectionName' => 'test'

}
```

Instead, this works:

```
$Controller = new PagesCategoriesController($request);
$Controller->loadModel('MeCms.PagesCategories');
$Controller->index();
```

Debug:

```
$Controller = new PagesCategoriesController($request);
$Controller->loadModel('MeCms.PagesCategories');
dd($Controller->PagesCategories);
```

```
object(MeCms\Model\Table\PagesCategoriesTable) {

        'registryAlias' => 'MeCms.PagesCategories',
        'table' => 'pages_categories',
        'alias' => 'PagesCategories',
        'entityClass' => 'MeCms\Model\Entity\PagesCategory',
        'associations' => [
                (int) 0 => 'parents',
                (int) 1 => 'childs',
                (int) 2 => 'pages'
        ],
        'behaviors' => [
                (int) 0 => 'Timestamp',
                (int) 1 => 'Tree'
        ],
        'defaultConnection' => 'default',
        'connectionName' => 'test'

}
```

So, is this normal?

**Comment by ADmad** [comment]
When a controller instance is created by dispatcher it sets proper value for `Controller::$plugin` which in turn is used to set value for `Controller ::$modelClass` which ensures your plugin table in loaded properly. Since you are directly creating controller instance you need to set `Controller::$modelClass` yourself.

**Comment by ADmad** [comment]
To avoid such problems it's better to use [controller integration tests](https://book.cakephp.org/3.0/en/development/testing.html#controller-integration-testing) instead of directly creating controller instance yourself.

**Comment by mirko-pagliai** [comment]
Ok, so this is normal.

> To avoid such problems it's better to use controller integration tests instead of directly creating controller instance yourself.

Yes, I know. @ADmad just another question: is there a way, through `IntegrationTestCase` and its `get()` method, to disable (`false`) the layout?  
This is essentially the reason why I create an instance of the controller.

**Comment by mirko-pagliai** [comment]
I answer to myself. I understand that with the `controllerSpy()` method I can access the controller:

    public function controllerSpy($event, $controller = null)
    {
        $controller->viewBuilder()->setLayout(false);

        parent::controllerSpy($event, $controller);
    }
