### ISSUE TITLE
Case of plugin name in html linkhelper

### ISSUE THREAD

**Issue by liviascapin** [cakephp/cakephp#10476]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.6/2.9.7
* Platform and Target: local xampp environment

### What you did
I am not sure if this is actually a bug.

We created a plugin (named Heartbeat) and tried to link to this plugin (for example link to the index action in the HeartbeatController).

### What happened
This works:
```php
echo $this->Html->link('Heartbeat',
	array('plugin' => 'heartbeat', 'controller' => 'Heartbeat', 'action' => 'index')
);
```
This works too:
```php
echo $this->Html->link('Heartbeat',
	array('plugin' => 'heartbeat', 'controller' => 'heartbeat', 'action' => 'index')
);
```
This doesn't work:
```php
echo $this->Html->link('Heartbeat',
	array('plugin' => 'Heartbeat', 'controller' => 'Heartbeat', 'action' => 'index')
);
```
In short, the plugin name seems to have to be lowercase for the link to work correctly.

### What you expected to happen
I did not expect the plugin name to have to be lowercase.
I find that kind of confusing, because with the controller it doesn't seem to matter whether you use uppercase or lowercase (I think uppercase is the way to go?).

In the documentation if you link to assets in plugins, you would use the plugin name in uppercase: https://book.cakephp.org/2.0/en/plugins/how-to-create-plugins.html#linking-to-assets-in-plugins but if you use the plugin in the html linkhelper (or any other place that works similarly, e.g. in unit tests with testAction) it absolutely has to be lowercase, that seems inconsistent with me. If this behaviour is correct, I think it should be documented better?

**Comment by dereuromark** [comment]
This is a 2.x requirement to have those lowercased. This only changed then for 3.0 and forward.

**Comment by ravage84** [comment]
Certainly a documentation issue. Especially since the plugin syntax is mentioned all over the documentation.

I've created #4883 for that because I always felt the router array was not documented properly.

But I guess we could  also mention it more clearly here:
https://book.cakephp.org/2.0/en/development/routing.html#plugin-routing

**Comment by markstory** [comment]
Closing as the documentation has been updated.
