### ISSUE TITLE
3.x Entity Mutators should run before validation

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10483]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.4.3

### What you did
Schema
```sql
`identifier` varchar(50) CHARACTER SET ascii NOT NULL COMMENT 'CONSTRAINT: immutable',
```
HTTP POST JSON:
```json
`"identifier": "12312-3_1Lö23a",`
```

in `validationDefault()`:
```php
->add('identifier', 'unique', ['rule' => 'validateUnique', 'provider' => 'table', 'on' => 'create'])
```

in CmsDocument.php:
```php
    /**
     * Identifiers should be slugs.
     *
     * @param $value string Identifier.
     * @return string Identifier.
     */
    protected function _setIdentifier($value)
    {
        $value = strtoupper(Inflector::slug($value));
        //$value = strtoupper(Inflector::slug(Text::transliterate($value)));
        return $value;
    }
```

### What happened
`"message": "SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='",`

### What you expected to happen
Mutators to run before validators/rules run.

**Comment by ADmad** [comment]
Validation is done on raw request data not entitiy properties. For your particlar example use application rule.

**Comment by inoas** [comment]
I have moved the mutation into `beforeMarshal()`.

I am already using an Application Rule but it is too late for a one-tiered validation response (e.g. user has stateless errors first, then stateful).
