### ISSUE TITLE
How use ajax for live search in cakephp 3.4.

### ISSUE THREAD

**Issue by shoebadmin** [cakephp/cakephp#10484]
Hi, Please anybody have idea about how to used ajax for live search in cakephp3.
I m new learner of cakephp3.I m still facing this problem since last week.

Thanks,

**Comment by inoas** [comment]
Wrong place. Try IRC, Slack, The discourse forum.
In general look at CakeDC/Search for the server side part and jQuery for the client side part.

**Comment by burzum** [comment]
Please use http://discourse.cakephp.org/, https://stackoverflow.com/, IRC or Slack.

This is an issue tracker, not a help forum or a learning resource. It's thought to report issues with the framework or suggest relevant features.

**Comment by shoebadmin** [comment]
Sir, I am using cake php3 as client requirements. We can fetch the data from our database with the help of ajax.So I humble request to you how to use ajax in cakephp for fetching the data.
Thanx for your reply
