### ISSUE TITLE
Call to a member function schema() on null ... AclComponent.php on line 298 

### ISSUE THREAD

**Issue by pedrazadixon** [cakephp/cakephp#10481]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.0.5
* Platform and Target: Windows 10 xampp

### What you did
this is de 298  line in AclComponent:
`$permKeys = $this->_getAcoKeys($this->Aro->Permission->schema());
`
### What happened
after login in my cakephp 2 with acl i get this error 
`Fatal error: Call to a member function schema() on null in D:\ProgramFiles\xampp\htdocs\cgp\lib\Cake\Controller\Component\AclComponent.php on line 298 `
any help for this?

**Comment by markstory** [comment]
Why is `$this->Aro->Permission` null? Do you have app specific models for the `Aro` class? The default core ones do define the `Permission` association.

**Comment by pedrazadixon** [comment]
Hi @markstory thanks for your answer.  I haven't custom Aro class. 
This is my /app/models/aro.php
```
<?php
class aro extends AppModel 
{
	 public $name = 'aros';	 
}
?>
```
Thanks in advanced.

**Comment by pedrazadixon** [comment]
Any way to "track" error in `$this->Aro->Permission` or `$this->Aro->Permission->schema()` ?
I can access to my login page of my app without problems. 
The get this error when login in my app.

**Comment by rchavik** [comment]
Afaik, you're not supposed to create your own Aro model. Instead, you should add AclBehavior in your User or Role/Group models.

Are you using cake 1.3 by chance?

**Comment by pedrazadixon** [comment]
Hi @rchavik , my php version is 2.0.5.

**Comment by markstory** [comment]
The Aro class in your app is the source of this issue. You should copy the Aro class from CakePHP into your app if you need to make changes to it.
