### ISSUE TITLE
Fatal error: Trait method getProtocolVersion has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by mergeweb** [cakephp/cakephp#10495]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

CakePHP 3.4.1 >
ADDING "zendframework/zend-diactoros": "1.3.10" fixes the issue.

### What you did
Updated Composer

### What happened
After composer update it appears 
https://gist.github.com/mergeweb/44257e8509e6ee67092b142ba768804e
ADDING "zendframework/zend-diactoros": "1.3.10" fixes the issue.

### What you expected to happen
Not a big trace error

**Comment by mergeweb** [comment]
Version 3.4.1
and up.

**Comment by ADmad** [comment]
Problem seems to be cause by some change in diactoros' 1.4.0 release.

**Comment by markstory** [comment]
Looks like zendframework/diactoros 1.4.0 introduced this issue. I will get in contact with those folks tonight.

**Comment by juniorionut** [comment]
This was fast :)

**Comment by markstory** [comment]
Closing as new releases are out.
