### ISSUE TITLE
reverseToArray handle pass parameters

### ISSUE THREAD

**Issue by bskade** [cakephp/cakephp#10499]
* [x] bug
* CakePHP Version: 2.9.7

### What you did
request url: "/page/cars/bmw/"
```
Router::connect(__d('routes', '/page') . '/:parent/:slug/', 
		array('admin' => false, 'plugin' => 'wp_cms', 'controller' => 'wp_page', 'action' => 'view'), 
		array('pass' => array('slug', 'parent')));

params
array(
	'plugin' => 'wp_cms',
	'controller' => 'wp_page',
	'action' => 'view',
	'named' => array(),
	'pass' => array(
		(int) 0 => 'cars',
		(int) 1 => 'bmw'
	),
	'parent' => 'cars',
	'slug' => 'bmw',
	'isAjax' => false
)
```
results of reverseToArray 
```
array(
	'plugin' => 'wp_cms',
	'controller' => 'wp_page',
	'action' => 'view',
	'parent' => 'cars',
	'slug' => 'bmw',
	'isAjax' => false,
	(int) 0 => 'cars',
	(int) 1 => 'bmw'
)
```

### What you expected to happen
```
array(
	'plugin' => 'wp_cms',
	'controller' => 'wp_page',
	'action' => 'view',
	'parent' => 'cars',
	'slug' => 'bmw',
	'isAjax' => false,
	//(int) 0 => 'cars', should be removed
	//(int) 1 => 'bmw' should be removed
)
```

**Comment by dereuromark** [comment]
Please format your code with ``` fences.

**Comment by markstory** [comment]
I'm not sure those parameters *can* be removed. The `reverseToArray()` method doesn't know which route the request is being reversed for and thus can't remove the additional parameters.

**Comment by bskade** [comment]
I'm not sure if it's possible to remove these parameters as well. But to recreate the original url in my example these parameters need to be removed. Maybe I'm wrong and the function reverseToArray has another purpose.

**Comment by markstory** [comment]
Closing as I don't think this can be fixed without deeper changes that I don't think are worth the time investment at this point in 2.10.
