### ISSUE TITLE
Disabled checkboxes have disabled hidden fields

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#10492]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.3

### What you did
```
$this->Form->checkbox('x', ['disabled' => true, 'hiddenField' => 1, 'checked' => true])
```

### What happened
```html
<input type="hidden" name="x" disabled="disabled" value="1"/><input type="checkbox" name="x" value="1" disabled="disabled" checked="checked">
```

### What you expected to happen
The hidden field must no be disabled, otherwise it is quite useless :smile: (Browsers don't send disabled fields via POST). I want a checkbox that is disabled and checked, and is send via POST.

I currently don't see a reason why a disabled hidden field would make sense at all... It was introduced by adea104edbb6a703e117f3ab4bb2d7ed636fbbf9, but I' not quite sure why.

**Comment by dereuromark** [comment]
Why are you setting `'disabled' => true` if you dont want it to be disabled?
I think the code behaves exactly like it should and is intended to behave.

**Comment by nrother** [comment]
I wan't the `<input type="checkbox">` to be disabled, but not the `<input type="hidden">` (So that the users see a disabled checkbox, but the value is posted nevertheless)

**Comment by dereuromark** [comment]
> Browsers don't send disabled fields via POST

Exactly. So you already know it behaves like it should :)

In your case it is a user error - you should be using a div with display:none css for example to just hide the input, not to disable it.
This ticket should be closed as invalid. The user expectation is wrong - the code is behaving as it should.

**Comment by nrother** [comment]
Ok, looking from that direction it look correct. I somehow thought that the hidden field was their to fix the "disabled checkboxes are not posted" problem.

I'll just disabled a checkbox with JavaScript.

**Comment by dereuromark** [comment]
No, it is to fix the nothing selected post problem. But those are still "not disabled", just not selected yet.
