### ISSUE TITLE
Directory find result ordering on Linux is not as expected

### ISSUE THREAD

**Issue by ash123456789** [cakephp/cakephp#10504]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5
* Platform and Target: nginx 1.11.9 / MariaDB 10.1.22 / PHP 7.1.3 / Ubuntu 16.04 LTS

### What you did
```PHP
use Cake\Filesystem\Folder;

...

$dir = new Folder(WWW_ROOT . "/img/series/" . $manga->stub . "/" . $num . "/");
$images = $dir->find('.*\.jpg');

$this->set(compact('manga', 'chapter', 'num', 'images'));
```

### What happened
Doesn't read the directory in order of file names on Linux, but reads it in order on Windows 10.

### What you expected to happen
Read the directory in order of file names. Whether I am doing something wrong here I am unsure but I followed it as per the documentation, as far as I am aware.

Example:
01.jpg
02.jpg
etc.

**Comment by markstory** [comment]
What order are you getting on Linux?

**Comment by ash123456789** [comment]
It seems to be random

E.g.
07.jpg
04.jpg
09.jpg
etc.

**Comment by josegonzalez** [comment]
I don't believe `DirectoryIterator` has a natural sort, and just relies on whatever the OS returns to it. You'll want to set the `sort` property on the `find()` call to `true` in order to get the values sorted as you wish.

**Comment by markstory** [comment]
@josegonzalez is correct. You should use the `sort` parameter of `find()` to ensure your results are consistent. `$folder->find('*.jpg', Folder::SORT_NAME)`
