### ISSUE TITLE
Unexpected behavior for nested associations contain

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#10507]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.16
* Platform and Target:  Apache/2.4.23 , MySQL 5.6.31, AND PHP 5.5.38.

### What you did
In my controller action
```php
        $link = $this->Links->find()
            ->contain(['Users.Plans'])
            ->where([
                'Links.alias' => $alias,
                'Links.status <>' => 3,
                'Users.status' => 1
            ])->first();
        $this->set('link', $link);
```

### What happened
The user status is `3` but the ORM returned it and here is the generated SQL
```sql
SELECT 
  Links.id AS `Links__id`, 
  Links.user_id AS `Links__user_id`, 
  Users.id AS `Users__id`, 
  Users.status AS `Users__status`, 
  Users.username AS `Users__username`, 
  Plans.id AS `Plans__id`, 
  Plans.title AS `Plans__title`
FROM 
  links Links 
  LEFT JOIN users Users ON Users.id = (Links.user_id) 
  LEFT JOIN plans Plans ON Plans.id = (Users.plan_id) 
WHERE 
  (
    Links.alias = 'jvrne7qo' 
    AND Links.status <> 3 
    AND Users.status = 1
  ) 
LIMIT 
  1
```
**when I run the above sql via PHPMyAdmin, it doesn't return any records!!!**
### What you expected to happen
I expect not to get any records because user status is `3`(inactive)

**Comment by ADmad** [comment]
Are you sure your app and phpmyadmin are connecting to the same database? :)

**Comment by markstory** [comment]
How can someone reproduce this issue? SQL conditions work fine in our test suite.

**Comment by BassemN** [comment]
@ADmad lol
@ADmad @markstory currently, I'm out after coming, I'll double check and feed you back

**Comment by BassemN** [comment]
I'm so sorry for the inconvenience.
@ADmad was right as my app was connecting to a wrong database.
