### ISSUE TITLE
2.x Incompatibility with PHPUnit 4.x+ and CakePHP 2.10.x when testing static framework code

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#10518]
I just found out, that we have a compatibility issue with CakePHP Version 2.10+ in combination with PHPUnit 4.x+.

After #10405, CakePHP 2.10.x got _essentially_ compatible with PHPUnit 4.x (4.8) and once #10497 is merged, it should become _essentially_ compatible with PHPUnit 5.0.

Unfortunately, the AuthComponent (and probably a few other integral parts of the framework) call important methods in a static way or their methods are static. For example:

https://github.com/cakephp/cakephp/blob/68432f77deed192457e60ea96bb79d8ba6664141/lib/Cake/Controller/Component/AuthComponent.php#L666

In PHPUnit 3.x it was possible to mock static methods with ``staticExpects()``, but this function was deprecated and got removed in 4.0.0.

> staticExpects(), which was slated for removal and marked as deprecated for a while, did not actually allow stubbing and mocking arbitrary static method calls. It only worked within the scope of the same class. Since it was limited in use I have rarely seen it being used. And considering that it provided little gain but considerable maintenance pain we decided to remove it.

https://github.com/sebastianbergmann/phpunit-documentation/issues/77

So starting with PHPUnit 4.0, there seems to be no way to mock static methods anymore:

> Limitation: final, private, and static methods
> Please note that final, private and static methods cannot be stubbed or mocked. They are ignored by PHPUnit's test double functionality and retain their original behavior. 

https://phpunit.de/manual/4.0/en/test-doubles.html
https://phpunit.de/manual/3.7/en/test-doubles.html (even there mentioned)

Too bad, the Cookbook recommends the use of ``staticExpects`` for testing such methods:

`````php
public function testAdd() {
    $Posts = $this->generate('Posts', array(
        'components' => array(
            'Session',
            'Auth' => array('user')
        )
    ));
    $Posts->Auth->staticExpects($this->any())
        ->method('user')
        ->with('id')
        ->will($this->returnValue(2));
`````

https://book.cakephp.org/2.0/en/development/testing.html#a-more-complex-example

Do we need to add non-static methods and use them in such places in the framework?
Or how could one, for example, test his auth related code in his app  with CakePHP 2.10.x and PHPUnit 4.x+?

**Comment by ravage84** [comment]
@chinpei215 & @swordbeta have you guys come accross this?

**Comment by markstory** [comment]
> Do we need to add non-static methods and use them in such places in the framework?

I don't think we can do that without breaking compatibility.

> Do we need to add non-static methods and use them in such places in the framework?

Maybe. I don't think adding non-static methods is going to work in many places. People who want to use PHPunit 4.x+ and CakePHP2 will probably not be able to use static method mocks and will instead need to come up with other solutions to do the tests they need.

**Comment by chinpei215** [comment]
I have never used staticExcpets method. In such cases, I would call `CakeSession::write('Auth.User', $user)` instead of mock. Since `AuthComponent::user()` can be called statically in view layer in 2.x app, I don't think we can mock the method as people expect.

**Comment by ravage84** [comment]
@markstory Well I guess the solution is as simple as doing what @chinpei215 does.
I'm going to adjust the testing docs.

**Comment by markstory** [comment]
Closing as this doesn't require any code changes, just documentation updates.

**Comment by bancer** [comment]
Actually, @chinpei215 solution is not suitable for tests with stateless authentication with BasicAuthenticate class because sessions are not used there. @chinpei215, @ravage84 Is there any workaround for that scenario?

**Comment by ravage84** [comment]
Well, we ran into this, too.

We solved it by manipulating the super globals in the end

```` php


	/**
	 * Mocks a successful authentication
	 *
	 * @return void
	 * @todo consider moving to AppControllerTestCase.
	 */
	protected function _mockSuccessfulAuthentication() {
		$_SERVER['PHP_AUTH_USER'] = 'api_user';
		$_SERVER['PHP_AUTH_PW'] = '011zL36!CDxv'; // fake password ;-P
	}
````
