### ISSUE TITLE
Minus zero value does not pass notEmpty validation

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#10521]
### What you did
````php
<?php
App::uses('AppShell', 'Console/Command');
App::uses('Validation', 'Utility');

class MinusZeroTestingShell extends AppShell {
	public  $User;

	function main() {
		$value_to_save1 = 0 * -0.5;
		$value_to_save2 = 0.0 * -1;
		$value_to_save3 = -0.0;

		var_dump($value_to_save1===0.0);
		var_dump($value_to_save2===0.0);
		var_dump($value_to_save3===0.0);

		var_dump((string)$value_to_save1);
		var_dump((string)$value_to_save2);
		var_dump((string)$value_to_save3);

		var_dump(Validation::notBlank($value_to_save1));
		var_dump(Validation::notBlank($value_to_save2));
		var_dump(Validation::notBlank($value_to_save3));
	}
}
````
### What happened
bool(true)
bool(true)
bool(true)
string(2) "-0"
string(2) "-0"
string(1) "0"
bool(false)
bool(false)
bool(true)

### What you expected to happen
bool(true)
bool(true)
bool(true)
string(2) "-0"
string(2) "-0"
string(1) "0"
bool(true)
bool(true)
bool(true)

### Tested on
PHP: 5.6.30
CakePHP: v2.9.7

This problem only occurs on cake 2.x
(on cake 3.x PHP's minus zero correctly passes notBlank validation)

**Comment by Asgraf** [comment]
Please note that writing -0.0 directly gives you positive zero instead negative zero.
Minus operator only change singn on zero values

**Comment by markstory** [comment]
Interesting, the following has both types of -0 being the same

```php
php > var_dump(-0.0);
php shell code:1:
double(-0)

php > var_dump(0.0 * -1);
php shell code:1:
double(-0)

php > var_dump(-0.0 === (0.0 * -1));
php shell code:1:
bool(true)
```
