### ISSUE TITLE
Possible race-condition while checking `is_dir`

### ISSUE THREAD

**Issue by Theaxiom** [cakephp/cakephp#10530]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: bfa6e091bc5da1c573acf3ead0bb4c25b7298caa

### What happened
https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/FileEngine.php#L383
```
        if (!is_dir($dir)) {
            mkdir($dir, 0775, true);
        }
```
As you can see, there is a possibility of a race-condition while checking `is_dir`. This nomenclature exists in other places in the core as well.

### What you expected to happen
It would be better to do something like the following:
`if (!@mkdir($dir, 0775, true) && !is_dir($dir)) { throw... }`

**Comment by markstory** [comment]
If you're in a high-concurrency environment you should avoid using FileCache, and if that's not possible you should create the directories ahead of time. Multiple operations on the file system are very hard to make atomic in PHP.

**Comment by Theaxiom** [comment]
I agree with you, I was just going through the code and decided to raise this up. Thanks!

**Comment by inoas** [comment]
Wouldn't that change still help?
What should be used instead?
Should there be a note in the docs?

**Comment by Theaxiom** [comment]
Here's an example of where it is done correctly: https://github.com/cakephp/cakephp/blob/master/src/Shell/Task/AssetsTask.php#L170

**Comment by markstory** [comment]
Pull request up now.
