### ISSUE TITLE
SELinux permissions on RHEL / CENTOS / Fedora

### ISSUE THREAD

**Issue by h3x2b** [cakephp/cakephp#10553]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.5 (as downloaded now 2017/04/18 by composer)
* Platform and Target: Fedora 24+ (RHEL7, CENTOS7) + Apache httpd

### What you did
```
dnf -y install composer
cd /var/www/
mkdir /var/www/lowuser
chown lowuser /var/www/lowuser
cd lowuser
sudo -u lowuser composer create-project --prefer-dist cakephp/app exampleapp
cd exampleapp
# Answer [Y] to setting permissions
```

### What happened
The permissions are set to be world writable (to be accessed by the http daemon), but the context is not set (or is set just by the context of directory /var/www).

```
$ ls -ladZ logs logs tmp/cache tmp/cache/models tmp/cache/persistent tmp/cache/views tmp/sessions tmp/tests
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 logs
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 logs
drwxrwxrwx. 5 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/cache
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/cache/models
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/cache/persistent
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/cache/views
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/sessions
drwxrwxrwx. 2 lowuser lowuser unconfined_u:object_r:httpd_sys_content_t:s0 4096 2017-02-21 10:25 tmp/tests
```
Which results in a lots of errors when trying to access over apache:
```
Warning (512): /var/www/lowuser/exampleapp/tmp/cache/persistent/ is not writable [CORE/src/Cache/Engine/FileEngine.php, line 432]


Warning: file_put_contents(/var/www/lowuser/exampleapp/logs/error.log) [function.file-put-contents]: failed to open stream: Permission denied in /var/www/lowuser/exampleapp/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 133
... etc.
```

when in the same directory you run the cake server, it works ok:
```
bin/cake server
```

### What you expected to happen
For the Apache to have write access on RedHat systems (which are with SELinux by default) the context of the directories needs to be set to httpd_sys_rw_content_t (or like) which can be done temporarily by user with command chcon or by root defining the default policy with semanage fcontext.

```
#change the SELinux permissions temporary
for D in tmp/cache tmp/cache/models tmp/cache/persistent tmp/cache/views tmp/sessions tmp/tests tmp logs ; do
    mkdir -p ${CAKEROOT}/${D}
    chcon -R -t httpd_sys_rw_content_t ${CAKEROOT}/${D}
done
```

Also the rest of the cake project directory where httpd should have access should be set to context of httpd_sys_content_t (this is true in /var/www, but might not be for example somewhere in the home directory).

Please can you consider adding this to the setup script?

Thank you

**Comment by markstory** [comment]
> Please can you consider adding this to the setup script?

Would you be willing to put together a pull request to conditionally change the permissions/ownership based on host implementing SELinux?

**Comment by h3x2b** [comment]
I can try, but I am total beginner with cakephp.

**Comment by markstory** [comment]
Cool. I never use SELinux :smile:

**Comment by RobbiNespu** [comment]
Does it related to this problem too ? SInce I using Fedora on computer 
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Set Folder Permissions ? (Default to Y) [Y,n]? y
Permissions set on /var/www/html/ayam/AYAM_v4_site/tmp/bake
Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception                                
  [ErrorException]                  
  chmod(): Operation not permitted  
```

**Comment by h3x2b** [comment]
Re RobbiNespu
I do not think SE linux is the reason for error you are getting ("chmod(): Operation not permitted"), but once you fix that one you will encounter the issues with SE context not being set for the Apache to write there.

I guess that in your case it is something different. I take really wild guess as some key information on what user-id you use and what are the permissions on the /var/www/html/ayam/AYAM_v4_site/tmp/bake directory. - you are are executing composer as some normal user (recommended), but you probably already tried also running as root, which resulted in tmp/bake directory being created as root or another user, and that is the reason why with this account you can't chmod that directory.

Please check that tmp/bake directory is owned by the same account as the rest of the project should be. If not, then re-own it to the right one (sudo chown your_account /var/www/html/ayam/AYAM_v4_site/tmp/bake)

Once fixed this discrepancy in permissions and once the "bin/cake server" is also working fine for you, then try to fix the SE linux context for Apache.

In my case the "composer install" finishes OK including setting of the permissions. 
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Set Folder Permissions ? (Default to Y) [Y,n]? Y
No Security.salt placeholder to replace.
```

**Comment by h3x2b** [comment]
Please @markstory I could use some hint. 
Please when runing the cake installation, how does the composer know what directories to create for cakephp and what permissions to set there?

**Comment by markstory** [comment]
@h3x2b All of that code is in the app skeleton in [src/Console/Installer.php](https://github.com/cakephp/app/blob/master/src/Console/Installer.php/

**Comment by ADmad** [comment]
Closing as the issue has gone stale. Feel free to open a pull request if you are still interested in resolving this issue.
