### ISSUE TITLE
ResultSet caching broken by a recent PHP "security patch"

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#10552]
This is a (multiple allowed):

* [x] bug, but not with CakePHP
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12.
* Platform and Target: PHP 5.6.30, PHP 7.0.15, PHP 7.1.0.

This is a continuation of https://github.com/cakephp/cakephp/issues/10111, but a bit more specifically.  As discussed in the PHP issue list at https://bugs.php.net/bug.php?id=74436, the PHP group has changed the way Serializable and __wakeup() interact when unserializing class instances, and they have done this in a way that breaks ResultSet caching among probably many other things.  Also violates a basic principle of object-oriented languages, but first things first.

PHP 5.6.29 is safe, and there are probably versions of PHP 7.0 that should be reverted to as well.

**Comment by markstory** [comment]
If `__wakeup` is called after unserialization is complete, could we move the count calculation into that method?

**Comment by tharlinsmith** [comment]
From the Serializable docs: "Classes that implement this interface no longer support __sleep() and __wakeup()."  So you can't have both.  You could just not precalculate the count at all, and access the SplFixedArray to get that value when needed.  But that's not the point...  It should be totally kosher to access a contained class within Serializable::unserialize() of a containing class.

Here's another example:  ZipIterator has an unserialize function that unserializes the iterators.  If *any* of those iterators has a __wakeup() function then it won't be called prior to attachIterator(), and that might cause reference errors.  Then there is Mailer/Email and View/ViewBuilder, both of which do significant fiddling inside their unserialize() functions and are thus exposed.

Regardless of what compensations are made to CakePHP, I consider PHP versions with this behavior change to be unsafe.

**Comment by markstory** [comment]
Closing as I'm not able to reproduce this issue with PHP 5.6.32 or 7.1.11 on OSX.
