### ISSUE TITLE
Method setData does not exist

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#10565]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5.
* Platform and Target: xampp php7.

### What you did
I got an error when I use setData in the controller.

### What happened
.Method setData does not exist

### What you expected to happen
setData method missing

**Comment by markstory** [comment]
Why are you using `setData()`?

**Comment by infokani** [comment]
```
 public function add() {
    ...
              $this->request->setData('field',$value); // is correct?
    ...
```

**Comment by markstory** [comment]
No. Those methods don't exist. However, there is a deprecation doc string suggesting them which is incorrect. You should use `withParam()` or `param()` instead. I'll get the deprecation notice updated as the current documentation is wrong.

**Comment by infokani** [comment]
I found setData method in the Event\Event.php
```
public function setData($key, $value = null)
    {
        if (is_array($key)) {
            $this->_data = $key;
        } else {
            $this->_data[$key] = $value;
        }

        return $this;
    }
```

**Comment by infokani** [comment]
Should I use old $this->request->data['field'] = $value; ?

**Comment by markstory** [comment]
If you want to modify the request data you can use `$this->request->data['field']`, $this->request->data()` or `$this->request->withData()`. The `withData()` method is what I would recommend as it is not deprecated, but the other forms will continue to exist for the remainder of 3.x.

**Comment by markstory** [comment]
Closing as there is a pull request open to fix the incorrect documentation.
