### ISSUE TITLE
CakePHP 2.x // 3.x Session.time inconsistent

### ISSUE THREAD

**Issue by jojomartius** [cakephp/cakephp#10563]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.1
* Platform and Target: nginx / apache, mysql

### What you did
Tried to migrate old CakePHP 2 project step by step to version 3.x, i put a nginx proxy before both versions and route everything to the old version. If a new controller is able to handle the user needs i route with nginx reverse proxy /converted_controller_name to the CakePHP 3 project.

### What happened
Session closed, coming back from CakePHP 3 back to CakePHP 2 (browser back button or existing link) because of time expired.

#### CakePHP 2 Session Validation

// lib/Cake/Model/Datasource/CakeSession.php

	protected static function _validAgentAndTime() {
		$userAgent = static::read('Config.userAgent');
		$time = static::read('Config.time');
		$validAgent = (
			Configure::read('Session.checkAgent') === false ||
			isset($userAgent) && static::$_userAgent === $userAgent
		);
		return ($validAgent && static::$time <= $time);
	}

#### CakePHP 3 Session Timeout Check

// src/Network/Session.php

    protected function _timedOut()
    {
        $time = $this->read('Config.time');
        $result = false;

        $checkTime = $time !== null && $this->_lifetime > 0;
        if ($checkTime && (time() - $time > $this->_lifetime)) {
            $result = true;
        }

        $this->write('Config.time', time());

        return $result;
    }

EXPLAIN WHAT IS TO BE EXPECTED, HERE.

The logout is caused because CakePHP 2 and 3 are using Config.time in a different way, once with the last time the session was written and once the time when the session expires. Would be helpful to ether update the name to something different or use it in the same way. Otherwise its hard to share a session between two versions of the same framework.

**Comment by markstory** [comment]
How would you do that and maintain compatibility for each version's current behavior?

**Comment by jojomartius** [comment]
Mh.. i'm not sure if there is any need for maintaining compatibility to prior versions. People who do not have that issue with session sharing should not be effected by a change, the worst thing that could happen is that a users is logged out after a version update of cake. Afterwards it should work as before for "standalone" usage and better if you try something like this :-)

And i assume that could be helpful for people who upgrade larger systems.

**Comment by jojomartius** [comment]
BTW: my current fix was to change line 589 (in Cake3) to

        $this->write('Config.time', (time() + $this->_lifetime));

I know that's not the very best fix, but didn't managed to fix it in 2.x and i wasn't able to overwrite the Network/Session from my app folder, so for now that's the only way it was working.

**Comment by tersmitten** [comment]
We have exactly the same problem, in a similar setup. Porting action by action from the old (2.x) app to the new (3.x) one with haproxy in front of it.

@markstory Do you see any non-hacky ways to make this configurable/ overridable. Maybe a flag to configure 2.x compatibility?

**Comment by tersmitten** [comment]
Maybe something like this?

```
@@ -58,6 +58,13 @@
     protected $_lifetime;
 
     /**
+     * Whether or not to make `_timedOut` 2.x compatible.
+     *
+     * @var bool
+     */
+    protected $_use2xTimeout = false;
+
+    /**
      * Whether this session is running under a CLI environment
      *
      * @var bool
@@ -201,6 +208,10 @@
             $config['ini']['session.gc_maxlifetime'] = 60 * $config['timeout'];
         }
 
+        if (isset($config['use_2x_timeout']) && $config['use_2x_timeout']) {
+            $this->_use2xTimeout = true;
+        }
+
         if (!empty($config['cookie'])) {
             $config['ini']['session.name'] = $config['cookie'];
         }
@@ -588,7 +599,11 @@
             $result = true;
         }
 
-        $this->write('Config.time', time());
+        if ($this->_use2xTimeout) {
+            $this->write('Config.time', (time() + $this->_lifetime));
+        } else {
+            $this->write('Config.time', time());
+        }
 
         return $result;
     }
```

**Comment by markstory** [comment]
@tersmitten We could also patch 2.x to have a forwards compatible mode. I would prefer that as with 3.x we'll be required to maintain the 2.x mode for quite some time.

**Comment by tersmitten** [comment]
If you have any time, can you have a quick look?

**Comment by tersmitten** [comment]
Never mind, I'll have a look at it myself tomorrow morning.

**Comment by tersmitten** [comment]
Pull request is open
