### ISSUE TITLE
Prevent _matchingData if already included via contain

### ISSUE THREAD

**Issue by steffenbrand** [cakephp/cakephp#10568]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: Debian, Apache2, MariaDB

### What you did
I execute a query which includes related data via "contain" and also makes use of "matching".

### What happened
The _matchingData is being filled and according to the documentation this is wanted and supposed to happen.

> The data from the association that is ‘matched’ will be available on the _matchingData property of entities. If you both match and contain the same association, you can expect to get both the _matchingData and standard association properties in your results.

### What you expected to happen
I'm looking for a way (maybe an additional Query method) to prevent matching data being added as _matchingData to the result. I want to use the query result for a REST API and the _matchingData is bloating the response unnecessarily, since it's already included by "contain".

If there already is a way to achieve this and I just didn't find it, feel free to teach me :)

**Comment by ADmad** [comment]
Use `innerJoinWith()` instead of `matching()`. https://book.cakephp.org/3.0/en/orm/query-builder.html#using-innerjoinwith

**Comment by steffenbrand** [comment]
Thanks a lot, works perfectly fine!
