### ISSUE TITLE
2.x-3.x structure

### ISSUE THREAD

**Issue by josephzidell** [cakephp/cakephp#10578]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.8
* Platform and Target: All

We're upgrading from 1.x to 2.x and are planning the structure. Part of our plan is to use 2.x code and maintain a 3.x application structure as much as possible (this will give our team time to adjust to the 3.x structure):

    app-or-src/
        Controller/
        Model/
        View/
    config/
    console/
    plugins/
    tests/
    webroot/

There are a few places in the code that hard-code `APP . DS . 'Config' ...`. It would be immensely helpful to add a `CONFIG_DIR` constant (and cousins) that we could change.

This issue is to discuss the idea. I can make a PR after.

I know that 2.x is old, and you guys are not really adding new features. This is simply a shim to allow us to straddle the fence between 2.x and 3.x until we can do the next upgrade.

**Comment by dereuromark** [comment]
Many of the shimming can be done yourself - or leveraging the [Shim](https://github.com/dereuromark/cakephp-shim) plugin.
That said: Adding those constants is probably not something the core needs here. Moving around some of the folders when migrating to 3.x sounds rather doable to me.
The actual migration issues are elsewhere IMO.

You can provide a PR with your suggested changes and that one can be discussed.

**Comment by josephzidell** [comment]
@dereuromark Of course I can do the tweaks myself. Our goal is not to touch the cake core, since we're installing through Composer.

**Comment by dereuromark** [comment]
PR now open.
