### ISSUE TITLE
Inconsistent behaviour of Entity::has()

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10581]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next and previous

### What you did
Called[ Entity::has()](https://github.com/cakephp/cakephp/blob/3.next/src/Datasource/EntityTrait.php#L339) on an empty hasMany or belongsToMany property.

### What happened
Returns true

### What you expected to happen
Expected false

---

I know you can have a long discussion about if has() means that the property is expected to be empty or just not null. And I'm pretty sure the opinions in the team will be different.

I personally would prefer to get false back when a hasMany / belongsToMany property is an empty array. I could accept that this is not the case if the entity would provide another method to check if a property, that is hasMany / belongsTomany, is empty or not. Maybe notEmpty()?

However, the current implementation, especially to devs not used to it is...

![image](https://cloud.githubusercontent.com/assets/162789/25352921/e5b6606e-292d-11e7-84d0-b2983d19ba26.png)

**Comment by markstory** [comment]
The entity you were checking did *have* a property, so the return value makes sense to me. How would an entity determine whether or not the property being checked is an association property or something that should contain a scalar. This also extends into other types like JSON column values. How should `has()` treat those?

It sounds like we might want another methods for checking if a property is not 'empty'.

**Comment by dereuromark** [comment]
maybe has() should be hasDefined() - and then has() can be non nullish value for real.

**Comment by cleptric** [comment]
Adding a new method for checking if the property is not empty sounds responsible to me, so 👍

**Comment by dereuromark** [comment]
notEmpty()? could be confusing as this should probably return true for 0 :)
hasValue()?

**Comment by burzum** [comment]
Yea, good question, I started writing code but came across the 0 "issue" as well. :) How do we want to threat it?

**Comment by cleptric** [comment]
It should not return `true`for `[]`, `null` and `''` I guess.
If we can agree on that `0` is a a value, `hasValue()` sounds good to me.

**Comment by burzum** [comment]
I don't like `value`, because an empty array is a value and '' is basically a value as well.

How about isEmpty()? I think that most of the time the state you want to check against.

**Comment by inoas** [comment]
> maybe has() should be hasDefined() - and then has() can be non nullish value for real.

:+1:

hasPropertyDefined() = property_exists()
hasPropertySet() = has non nullish value; 2nd arg should allow to set a type strict list of $nullish values, then just agree on values (aka [])?

**Comment by burzum** [comment]
I propose these two:

#### isEmpty()

Returns true on:

* '' (empty string)
* null
* []

#### hasValue()

Returns true on

* 'foo'
* ['foo', 'bar']
* 0

**Comment by davidyell** [comment]
```php
if (!empty($entity->isEmpty())) {
    // Hmm
}
```

**Comment by burzum** [comment]
@davidyell, what? Why would you need to do that?

```php
if (!$entity->isEmpty()) { /*...*/ }
```

**Comment by davidyell** [comment]
To demonstrate that `empty()` is a PHP function, and as such wrapping it doesn't make sense to me. I would much prefer a more descriptive function name which doesn't overlap with PHP. I don't actually use any of these methods as in my experience they're all pretty unreliable. Could just be my lack of understanding of course.

Which is why I tend to use `empty($entity->get('field'))` and `!empty($entity)`, so bearing this in mind, the methods will need to be consistent which I think is the point of the ticket, which is great. I'd just much rather that the method describe what it's doing without overlapping PHP methods.

Naming stuff is super hard though, and I can't really think of a suggestion to put forward here which hasn't already been covered by the existing discussion. Just wanted to give a different angle from my crazy brain.

**Comment by burzum** [comment]
@davidyell check in the php docs what empty() does and compare it to what was discussed above.

`empty(0)` an integer, will return true, while our implementation would not because 0 is a valid value while null is not a value and [] is "empty".

**Comment by inoas** [comment]
Originally you used `Entity::has('AssocName')` and expected true for an empty but existing association.

I think @davidyell has a point that we should not use the 'empty'-nomenclature unless it does exactly what php's `empty()` does (and then is not required).

So originally you wanted to check if the entity had an association defined, whether or not it had entities (aka values) inside or not.

`hasPropertyDefined()` or `hasAssociation()` should do that - it could directly map to php's `property_exists()` and would just be sugar.

Wouldn't that solve your problem?

**Comment by dereuromark** [comment]
PR merged.
