### ISSUE TITLE
order of argument in Cake\Validation\Validator::notEmpty

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10598]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x

there are anomaly between 
`Cake\Validation\Validator::notEmpty($field, $message = null, $when = false)`
and
`Cake\Validation\Validator::allowEmpty($field, $when = true, $message = null)`

see order of `$when` and ` $message `
i  prefer to  (` $field, $when = true, $message = null`)

**Comment by dereuromark** [comment]
Can we do this in 4.0? I mean without having silent misbehavior
We should need to add some check/assert that throws an exception if the wrong type is passed (= wrong order).

**Comment by markstory** [comment]
Does allowEmpty() ever use the message parameter? From what I remember it modifies internal state in the ValidationSet. There has been some talk in the past about removing this state and having `notEmpty` and ` allowEmpty` to manipulate basic rules like other validator features. See #8925 for tue previous discussion.

**Comment by burzum** [comment]
I would prefer if it would be possible to work with objects instead these damn arrays:

```php
Cake\Validation\Validator::allowEmpty($field)
    ->when(Validator::CREATED)
    ->setMessage('My fancy message');
```

This gives us auto-complete / discovery in IDEs, it's easier to read and write without the danger of making typos in these arrays.

**Comment by ADmad** [comment]
What arrays?  `$when` and `$message` are separate method arguments, neither of which are array.

**Comment by saeideng** [comment]
now validator methods return the `$this` for chaining 
```php
    ->allowEmpty($field,...)
    ->notEquals($field,...)
    ->range($field,...);
```
maybe new method could help
```php
Cake\Validation\Validator::set($field)
     ->allowEmpty()
    ->when(false)
    ->setMessage(....);
```

**Comment by saeideng** [comment]
new validators have same order of arguments
```php
public function allowEmpty*($field, $message = null, $when = true)

public function notEmpty*($field, $message = null, $when = false)
```
now can be close this issue 
Refs : https://github.com/cakephp/cakephp/pull/12990
