### ISSUE TITLE
Aliased field in contain() not generating Entity

### ISSUE THREAD

**Issue by hertz1** [cakephp/cakephp#10592]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5
* Platform and Target: PHP 5.6.30 and MariaDB 10.1.22 on Manjaro Linux.

### What you did
When using an aliased field in a `contain()`, CakePHP is not generating the respective Entity.

E.g:
```
$user = TableRegistry::get('Users')
                     ->find()
                     ->select(['id'])
                     ->contain([
                         'Profiles' => [
                             'fields' => ['aliased_field' => 'field']
                         ]
                     ])
                     ->first();
```
### What happened
The following result was returned:
```
object(App\Model\Entity\User)[127]
  public 'id' => int 1
  public 'aliased_field' => string 'This is an aliased field.' (length=24)
  ...
  public '[repository]' => string 'Users' (length=5)
```
### What you expected to happen
The following result should be returned:
```
object(App\Model\Entity\User)[135]
  public 'id' => int 1
  public 'profile' => 
    object(Cake\ORM\Entity)[127]
      public 'aliased_field' => string 'This is an aliased field.' (length=24)
      ...
      public '[repository]' => string 'Profiles' (length=8)
  ...
  public '[repository]' => string 'Users' (length=5)
```

P.S: Sorry if this is not a bug. But I couldn't find anything relate to aliased fields in `contain()` on the documentation nor a issue about this, but for me the correct behavior should be to create the respective Entity.

**Comment by markstory** [comment]
Have you tried also selecting the foreign key fields? Without those the ORM has a hard time putting data back together again.

**Comment by hertz1** [comment]
Even when selecting the foreign key field, the aliased field is not comming in the right place. Assuming my foreign key is `profile_id`:

```
$user = TableRegistry::get('Users')
                     ->find()
                     ->select(['id', 'profile_id'])
                     ->contain([
                         'Profiles' => [
                             'fields' => ['aliased_field' => 'field', 'profile_id']
                         ]
                     ])
                     ->first();
```
The following result was returned:
```
object(App\Model\Entity\User)[135]
  public 'id' => int 1
  public 'aliased_field' => string 'This is an aliased field.' (length=24)
  public 'profile_id' => int 1
  public 'profile' => 
    object(Cake\ORM\Entity)[127]
      public 'profile_id' => int 1
      ...
      public '[repository]' => string 'Profiles' (length=8)
  ...
  public '[repository]' => string 'Users' (length=5)
```

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce this issue in our test suite.

**Comment by markstory** [comment]
I was able to reproduce your issue, but if you select your aliased field as `Profiles__aliased_field` instead of `aliased_field` it will be correctly mapped onto the result sets. Normally the ORM automatically prefixes field names with the association name, but we don't manipulate explicit keys provided by developers as we have to trust them. By defining the alias in your field you should get the expected result.

**Comment by hertz1** [comment]
So maybe it's a good thing to add this orientation to the documentation, because it's not a very natural thing as we expect the association name to be prefixed by default. :)

**Comment by markstory** [comment]
@hertz1 That sounds like a good idea! Where would you have expected to find something like this?

**Comment by hertz1** [comment]
Well, I would expect to find this in the [Loading Associations](https://book.cakephp.org/3.0/en/orm/query-builder.html#loading-associations), where it says: 

> You can select fields from all associations with multiple easy contain() statements:

**Comment by inoas** [comment]
You can give it a try improving here: https://github.com/cakephp/docs/edit/3.0/en/orm/query-builder.rst

**Comment by hertz1** [comment]
@inoas Is that file the same as the one in the CakePHP Cookbook? I don't see the "_You can select fields from all associations with multiple easy contain() statements_" part in the file, for example.

**Comment by saeideng** [comment]
yes but now in not sync there are a  issue 
but you can manipulate it in mentioned link

**Comment by saeideng** [comment]
see https://github.com/cakephp/docs/blob/3.0/en/orm/retrieving-data-and-resultsets.rst
part of this file is extended in https://github.com/cakephp/docs/blame/3.0/en/orm/query-builder.rst#L1114-L1116
