### ISSUE TITLE
postLink method in CakePHP 2.x & 3.x

### ISSUE THREAD

**Issue by sulian** [cakephp/cakephp#10590]
Hello

In CakePHP, you can change the HTTP Method for a Form by using the ```type``` option.

BUT for the postLink function, you can change the HTTP Method  by using the ```method``` option.

Would it not be clearer to use the same option?

Best regards

Sulian

**Comment by dereuromark** [comment]
Maybe both should use `method` option. That is as close to the actual PHP and HTML spec as possible.

**Comment by inoas** [comment]
Ref: https://github.com/cakephp/cakephp/pull/9565

**Comment by inoas** [comment]
Maybe we can move away from `type` to `method` and if `$this->Form->input('file', ['type' => 'file'])` is being added to the Form at least one time we can add a good default for `enctype` on file submitting forms by default?

**Comment by saeideng** [comment]
in both you can use `$options['method']`
```php
form        => "method" + "type" ( methods + file )
postlink   => "method"
```
I think current behavior is good

**Comment by dereuromark** [comment]
Then we can close this.
