### ISSUE TITLE
Passing the Session ID in the URL

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10595]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.9.7.
* Platform and Target: Linux, Apache, MySQL.

### What you did
I configured the session to pass session id in the URL by setting use_trans_sid to 1:
```
	Configure::write('Session', array(
		'defaults' => 'database',
		'ini' => array(
			'session.use_cookies' => 0,
			'session.use_trans_sid' => 1,
		),
	));

```
And appended the session id to all URLs in AppHelper::url() as recommended in the [manual](http://www.php.net/manual/en/session.idpassing.php):
```
	public function url($url = null, $full = false) {
		// ... some code
		$key = md5(Configure::read('App.fullBaseUrl') . serialize($url) . $full);
		$link = Cache::read($key, 'router');
		if ($link === false) {
			$link = parent::url($url, $full);
			Cache::write($key, $link, 'router');
		}
		return $link . '?' . htmlspecialchars(SID);
	}
```

### What happened
The request was blackholed after a form was submitted:
```
/Cake/Controller/Component/SecurityComponent.php line 243 → SecurityComponent->blackHole(BookController, string)
    return $this->blackHole($controller, 'auth');
}
```

### What you expected to happen
I would expect no blackhole. Is it a bug or use_trans_sid is not supported by CakePHP?

**Comment by markstory** [comment]
>  use_trans_sid is not supported by CakePHP?

No. We don't support sessionids in the URLs. Session ids in the URL [expose you to additional security risks](https://security.stackexchange.com/questions/14093/why-is-passing-the-session-id-as-url-parameter-insecure) so we don't officially support it.

**Comment by bancer** [comment]
@markstory I agree about insecurity but it is sad that this feature is not supported because:
> Cookies are optimal, but because they are not always available, we also provide an alternative way. The second method embeds the session id directly into URLs.  
http://php.net/manual/en/session.idpassing.php

Per my knowledge the insecurity of passing the session id in the URL can be mitigated by using one-time session ids (regenerating the session id on each request, f.ex. by using [session_regenerate_id()](http://php.net/manual/en/function.session-regenerate-id.php)).
