### ISSUE TITLE
CakePHP3.4: invisible Form input still display the label

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/cakephp#10608]
* [x] bug

* CakePHP Version: 3.4.6.
* Platform and Target: apache2, php 7.1, mysql 5.7.18.

### What you did
I tried to hide an input with the following statement:
    
    <?= $this->Form->control('name', ['label' => __("Nom :"), 'disabled' => true, 'style' => 'visibility:hidden;']); ?>
 
### What happened
I saw the following display:
    
    Nom:

### What you expected to happen
I suppose that the label shouldn't be display when I don't want to display the input.

**Comment by dereuromark** [comment]
Your expectation is wrong.
Instead of trying to hack the control() method, it would be cleaner to just wrap the whole thing with a manual diff:

```html
<div class="...">
    ... // here goes your form inside an invisible div
</div>
```

For obvious reasons when you look at the generated HTML, the effects of style only for the inside, not the outer wrapper.

**Comment by 2ndGAB** [comment]
Yes sorry, you are right.

**Comment by dereuromark** [comment]
No problem. Happy coding :)

**Comment by inoas** [comment]
I think the expectation should be that `['labelOptions' => ['style' => 'visbility:hidden']]` or `['divOptions' => ['style' => 'visbility:hidden']]` should have worked... you can try and see and if it doesn't IMHO it is a good idea for a PR.

**Comment by 2ndGAB** [comment]
@inoas, why not, maybe quite a good idea but seems not supported at the moment.

**Comment by inoas** [comment]
`labelOptions` should be there. `divOptions` is not (yet).

```
     * - `labelOptions` - Either `false` to disable label around nestedWidgets e.g. radio, multicheckbox or an array
     *   of attributes for the label tag. `selected` will be added to any classes e.g. `class => 'myclass'` where
     *   widget is checked
``
