### ISSUE TITLE
Problems with isUnique() on a composite constraint with null value

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#10606]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0.
* Platform and Target: Windows Server and SQL Server 2008 R2

### What you did
If you have a constraint like this:
```
ALTER TABLE movimentacao_judicial
ADD CONSTRAINT unique_triplo UNIQUE (cnj,data_hora,codigo_movimento)
```
And you create a rule like this:
`$rules->add($rules->isUnique(['cnj', 'data_hora', 'codigo_movimento']));`

### What happened
Cake tried this:

`SELECT TOP 1 1 AS [existing] FROM movimentacao_judicial MovimentacaoJudicial WHERE (MovimentacaoJudicial.cnj = '12345678912345678912' AND MovimentacaoJudicial.data_hora = '2015-06-19 11:01:00' AND MovimentacaoJudicial.codigo_movimento = NULL)`

and an "insert into"

and SQL server complained:

`Error: SQLSTATE[23000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'unique_triplo'. Cannot insert duplicate key in object 'dbo.movimentacao_judicial'. The duplicate key value is (12345678912345678912, Jun 19 2015 11:01AM, <NULL>).`

### What you expected to happen

IS instead equal:

`SELECT TOP 1 1 AS [existing] FROM movimentacao_judicial MovimentacaoJudicial WHERE (MovimentacaoJudicial.cnj = '01018452120108190002' AND MovimentacaoJudicial.data_hora = '2015-06-19 11:01:00' AND MovimentacaoJudicial.codigo_movimento IS NULL)`

I also tried:

```
$rules->add(
                $rules->isUnique(
                        ['cnj', 'data_hora', 'codigo_movimento'],
                        ['allowNullableNulls' => true]
                )
        );
```

**Comment by markstory** [comment]
Is the codigo_movimento column nullable?

**Comment by celsowm** [comment]
Yeah !
```
CREATE TABLE [dbo].[movimentacao_judicial](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[data_hora] [datetime] NOT NULL,
	[descricao] [varchar](max) NULL,
	[codigo_pai_nacional] [int] NULL,
	[codigo_movimento] [int] NULL,
	[identificador_movimento] [varchar](max) NULL,
	[nivel_sigilo] [bit] NULL,
	[cnj] [varchar](20) NOT NULL,
	[data_hora_download] [datetime] NULL,
 CONSTRAINT [PK_movimentacao_judicial] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [unique_triplo] UNIQUE NONCLUSTERED 
(
	[cnj] ASC,
	[data_hora] ASC,
	[codigo_movimento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

**Comment by markstory** [comment]
Thanks. Can you try setting the `allowMultipleNulls` option to false?

**Comment by celsowm** [comment]
It worked ! Thanks ! 

I think would be cool to see a example with this parameter [here](https://book.cakephp.org/3.0/en/orm/validation.html#creating-unique-field-rules)

```
$rules->add(
                $rules->isUnique(
                        ['cnj', 'data_hora', 'codigo_movimento'],
						['allowMultipleNulls' => false]
                )
        );
```

```
2017-05-03 02:12:01 Debug: duration=1 rows=1 SELECT TOP 1 1 AS [existing] FROM movimentacao_judicial MovimentacaoJudicial WHERE (MovimentacaoJudicial.cnj = '01018452120108190002' AND MovimentacaoJudicial.data_hora = '2016-09-30 15:33:00' AND (MovimentacaoJudicial.codigo_movimento) IS NULL)
2017-05-03 02:12:01 Debug: duration=0 rows=0 ROLLBACK
```

**Comment by markstory** [comment]
@celsowm Good idea, would you be able to update the docs or should I?

**Comment by celsowm** [comment]
@markstory I would not dare and my english is not so good (yet) ! 
Please update it for us Mark :D

**Comment by markstory** [comment]
Docs pull request up now.
