### ISSUE TITLE
Cake 3.4 - Cake\Http\ServerRequest deprecations

### ISSUE THREAD

**Issue by highstrike** [cakephp/cakephp#10601]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.x

So Dakota is explaining [here](http://discourse.cakephp.org/t/cakephp-3-4-how-to-change-request-data-programmaticly/2120/3) that the request object is immutable.

However, I need to unset a fake form control (input type text) from request->data because one of my form widgets adds it for "cosmetic" effect. The real input field that i plan on using is actually hidden and updated via javascript when the fake field is changed, anyway...

I'm trying to futureproof my code and not use any deprecated functions or variables and I can't figure out how to remove this fake input from the request->data array on an application level (with a component for example)

Then I noticed that cake's own CsrfComponent is in the same boat as me. For example, one of the hidden fields that shouldn't be available is "_csrfToken" which does not seem to appear in the request->data array.

Problem is, the CsrfComponent just unsets it from the request->data array on line 99, and as we know, the ->data propriety is deprecated 😄 

What happens when that data propriety gets removed in 3.5 or 4.x ?
Perhaps we need an extra function like withoutData() in ServerRequest?

Thanks!

**Comment by cleptric** [comment]
Regarding your point about the CsrfComponent: There is already a PR in the making (#10561) which turns the Component into a middleware. You can take a look at code to see how the unset of the field is done there.
I guess you can also "fix" your issue with a little bit of CSS, if you just need the input for cosmetics 😀

**Comment by highstrike** [comment]
Nice one!

Apparently I totally missed the functions getParsedBody() and withParsedBody()
With those I can mess around inside the request->data array and then overwrite the application request with my cloned modified one 👍 

> I guess you can also "fix" your issue with a little bit of CSS
My widget is unholy, no amount of css can fix it 😁
