### ISSUE TITLE
The documentation for the cakephp email function is not accurate. setLayout, setTo, setSubject all aren't functional

### ISSUE THREAD

**Issue by me0123** [cakephp/cakephp#10605]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12

* Platform and Target: lamp server

### What you did
I just used the cake email function right out of the box.

### What happened
It's giving me an undefined function error.

### What you expected to happen
Send an email

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by dereuromark** [comment]
You are using an outdated version of CakePHP. Please specify the exact version in use as outlined above in the issue template.

**Comment by inoas** [comment]
It was a bad idea to replace the docs instead of extend and deprecate...

**Comment by markstory** [comment]
I will update the examples to have a pre 3.4.0 example as well.

**Comment by markstory** [comment]
Closing as the docs have been updated now.
