### ISSUE TITLE
Session Cache handler Cannot deal with a session cookie name with a dot inside the name

### ISSUE THREAD

**Issue by MichielKeijts** [cakephp/cakephp#10604]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: Nginx 1.10 

### What you did
Set a session save handler to Cache (Memcached) and used a cookie name with a '.' in it (e.g. 'NAME4.0')

### What happened
Sesssion cookie got set on the serverside, when the post with Auth parameters is done. Even the set-cookie header is returned, with the correct cookie.

However when the session is retrieved in the subsequent call, the session cannot be found, as the session cookie name is not set in $_COOKIE
This relates to the use of a '.' in the cookie name Ifound: cookie name is converted to 'NAME4_0'

NB:Cache Class converts the 'key'  to a non-dot-containing string in Cake\Cache\CacheEngine::key

Temporary solution: not use '.' in cookie name for session. 

### What you expected to happen
As described above. Either the cookiename to be converted before it was set to NAME4_0 so the subsequent requests where dealing with it correctly, or not a name change for the cookie.

**Comment by markstory** [comment]
Sounds like you shouldn't use `.` in you cookie name then. Are you expecting different behaviour from CakePHP or is this just a heads up?

**Comment by MichielKeijts** [comment]
I would suggest either making a statement in the docs that a `.` in a cookie name is not supported when using Cache as save handler. Or a log to the debug when using a `.` in the cookie name.

But regarding the question yes, I was expecting Cake to behave normally, as the cookie is set (stored), but cannot be loaded in a subsequent load as the Cache does not support a `.` in the name.

**Comment by markstory** [comment]
Ok. I can update the documentation.

**Comment by markstory** [comment]
Looks like PHP is converting the `.` in cookie names to `_` well before CakePHP ever gets to start the session. I don't think this issue is relegated to the 'cache' handler, as I had the same loss of session between both the 'cache' and 'php' handlers.
