### ISSUE TITLE
fields labels

### ISSUE THREAD

**Issue by hervethouzard** [cakephp/cakephp#10613]
Hello,

This is a:

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: > 3.4.6
* Platform and Target: Apache & co

### What you suggest
In the same way we define validation rules, a great enhancement will be the possibility, in every Model/Table/table.php file, to set `<label>`'s text to use for fields in forms.

No definitions means "use camel case version of the fields".

When you create web apps, your database fields are often in english but when the end users are not english and when you just need one language, let say french, it's easier to define all languages in a place related to the data (without the need to you gettext files).

Bye

**Comment by markstory** [comment]
If your application is in one language couldn't your view files be in french?

**Comment by hervethouzard** [comment]
Yes but I can have the need to display the field's label in several views.

**Comment by markstory** [comment]
Could you use elements or cells to reduce duplication of view template code?

**Comment by robertpustulka** [comment]
I don't think mixing the View layer with Model is a good idea.

**Comment by ADmad** [comment]
@hervethouzard You can achieve what your want through app code itself, by adding labels to the table's schema and overriding `FormHelper::label()` to use that as default value.

But such hacks don't belong in the core. Just use the internationalization / localization features the framework.
