### ISSUE TITLE
Selects in forms

### ISSUE THREAD

**Issue by hervethouzard** [cakephp/cakephp#10612]
Hello,

This is a:

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: > 3.4.6
* Platform and Target: Apache & co

### What you suggest
Adding an "option" in config/app.php to set, by default, 'empty' to true for every select in forms + option for the text will be very usefull.

Bye

**Comment by ADmad** [comment]
Just override FormHelper::select() in your cusom helper and set required default.
