### ISSUE TITLE
3.4.x: flash messages on tests

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10616]
Probably this is my mistake, but I need some help to figure out what does not work.

I'm writing some tests using `get()` / `post()` methods provided by `IntegrationTestCase` and I'm testing some flash messages.

With one action (and **only for one**) it seems that there is nothing in the session.

My action:

    public function forgotPassword() {
        // ...
        $this->Flash->error(__d('me_cms', 'No account found'));
        // ...
    }

My test:

        $this->post($url, ['email' => 'wrongMail@example.it', 'email_repeat' => 'wrongMail@example.it']);
        dd($this->_requestSession->read());

Result:

```
########## DEBUG ##########
[
        'Flash' => []
]
###########################
```

Some oddities. If I add some debug into the action:

    public function forgotPassword() {
        // ...
        $this->Flash->error(__d('me_cms', 'No account found'));
        debug($this->Flash->_session->read());
        // ...
    }

Result:

```
########## DEBUG ##########
[
        'Flash' => [
                'flash' => [
                        (int) 0 => [
                                'message' => 'No account found',
                                'key' => 'flash',
                                'element' => 'MeTools.Flash/flash',
                                'params' => [
                                        'class' => 'alert-danger'
                                ]
                        ]
                ]
        ]
]
###########################
tests/TestCase/Controller/UsersControllerTest.php (line 389)
########## DEBUG ##########
[
        'Flash' => []
]
###########################
```

Then I thought: ok, there is something that **after** the action is executed, it changes the session.
Yet, if I check the body of the response (`_getBodyAsString()`), the flash message is displayed correctly.

What can be wrong?

**Comment by markstory** [comment]
Not sure what's wrong. I have a few apps that do assertions on flash messages without any problems.

**Comment by jeremyharris** [comment]
I think this is because messages are popped from the session when they are displayed in the layout, which is why they are in the body but not the session. I've run into this before.

**Comment by markstory** [comment]
@jeremyharris Yes! displaying a flash message would totally remove it from the session.

**Comment by mirko-pagliai** [comment]
So, what should I do to assert flash messages?

**Comment by jeremyharris** [comment]
I would like to see a way to assert against messages as well. I think I'll play with some ideas and come up with a PR today.
