### ISSUE TITLE
Json View not being rendered if Session is written to before render() is called

### ISSUE THREAD

**Issue by nebojsac** [cakephp/cakephp#10610]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9
* Platform and Target: PHP 7.1, nginx, Ubuntu 14.04 LTS

### What you did
We have set up JSON extension parsing in our `routes.php`:

`Router::parseExtensions('rss', 'json', 'xml', 'json', 'pdf');`

We use this to handle API responses, example url:  `/lists.json` and so far it worked.

### What happened
So far we've been using `echo json_encode($data);` and this worked fine but is hard to test, so we started replacing it with the following snippet:

```php
$this->set('response', $data);
$this->render('json');
return true;
```
And we have a 'json.ctp' view file that just has `<?php echo json_encode($response);?>`.

Early in the Controller we have credential checking and session handling. If the credential check fails, it correctly renders the 'json.ctp' view file, with the error response. But, if the credential check succeeds, and we use `$this->Auth->login();`, then the view won't render at all. At that point it doesn't use the layout nor the view file, although the view "vars" are set.

I was able to narrow it down to this line in Auth->login():
 `$this->Session->write(static::$sessionKey, $user);`, when that is commented out, it works. Also, when we use the non-json url `/lists`, it also works.

### What you expected to happen
Expected `$this->render('json');` to render the `json.ctp` view file, but it silently fails.

**Comment by markstory** [comment]
Do you know where it is failing silently?

**Comment by nebojsac** [comment]
Well, I'm not sure where to look further. It just doesn't go into the "layout" nor "view" files at that point. Anything else I should check for, or data dump I should dig out?

**Comment by tersmitten** [comment]
This might be related to #10519

**Comment by markstory** [comment]
Interesting, I wonder how/why the JsonView is missing its ViewBlocks.

**Comment by nebojsac** [comment]
Here are some files for repeating the issue:
`app/Controller/PagesController.php` with added `test()` method:

```php
<?php
App::uses('AppController', 'Controller');

class PagesController extends AppController {

    public $uses = array();

/**
 * Displays a view
 *
 * @return void
 * @throws NotFoundException When the view file could not be found
 *  or MissingViewException in debug mode.
 */
    public function display() {
        $path = func_get_args();

        $count = count($path);
        if (!$count) {
            return $this->redirect('/');
        }
        $page = $subpage = $title_for_layout = null;

        if (!empty($path[0])) {
            $page = $path[0];
        }
        if (!empty($path[1])) {
            $subpage = $path[1];
        }
        if (!empty($path[$count - 1])) {
            $title_for_layout = Inflector::humanize($path[$count - 1]);
        }
        $this->set(compact('page', 'subpage', 'title_for_layout'));

        try {
            $this->render(implode('/', $path));
        } catch (MissingViewException $e) {
            if (Configure::read('debug')) {
                throw $e;
            }
            throw new NotFoundException();
        }
    }

    public function test()
    {
        $this->layout = 'ajax';
        $this->set('response', ['test']);
        $this->render('test');
    }
}
```

`app/Test/Case/Controller/PagesControllerTest.php` with one working assert. The 2nd assert seems to exit out.

```php
<?php
App::uses('PagesController', 'Controller');

/**
 * Test case for our API.
 *
 */
class PagesControllerTest extends ControllerTestCase
{

/**
 * Fixtures
 *
 * @var array
 */
    public $fixtures = [
    ];

    public function testJsonViewError()
    {
        $result = $this->testAction('/pages/test');
        $this->assertEquals('anything', $result);

        $result = $this->testAction('/pages/test.json');
        $this->assertEquals('anything', $result);

    }
}
```

`app/View/Pages/test.ctp` just to test if we're getting to the view:

```php
<?php echo 'anything' ?>
```
And this in `routes.php`:  `Router::parseExtensions('json');`

**Comment by markstory** [comment]
Thanks @nebojsac I'll see if I can reproduce with that information.

**Comment by markstory** [comment]
I tried to reproduce this and got a slightly different result. Instead of the fatal error, I got

```
1) ArticlesControllerTest::testIndexJson
MissingViewException: View file "Articles/json/json.ctp" is missing.
```

This was my controller code:
```php
<?php
// app/Controllers/ArticlesController.php
App::uses('AppController', 'Controller');

class ArticlesController extends AppController {
	public $components = ['RequestHandler', 'Flash'];

	public function index() {
		$this->layout = 'ajax';
		$this->render('json');
		return true;
	}
}
```

My view file (`app/View/Articles/json.ctp`) only contained `anything`.  My test case was

```php
<?php
// test/Case/Controller/ArticlesControllerTest.php
App::uses('ArticlesController', 'Controller');

class ArticlesControllerTest extends ControllerTestCase {

	public $fixtures = array();

	public function testIndex()
	{
		$result = $this->testAction('/articles');
		$this->assertStringStartsWith('anything', $result);
	}

	public function testIndexJson()
	{
		$result = $this->testAction('/articles.json');
		$this->assertStringStartsWith('anything', $result);
	}
}
```

Is your view file, in a json sub-directory or is in the controller root directory?

**Comment by nebojsac** [comment]
> Is your view file, in a json sub-directory or is in the controller root directory?
It's in the controller root directory, the path is `app/View/Pages/test.ctp`

I know this isn't part of the test code, but did you add the `routes.php` code as well? `Router::parseExtensions('json');` I don't know how to do that within just a currently running test case.

When I remove the routes code I get something similar to you:

```
1) PagesControllerTest::testJsonViewError
MissingViewException: View file "Pages/test.json.ctp" is missing.
```

**Comment by markstory** [comment]
I did have `Router::parseExtensions('json', 'xml')` at the top of my routes file.

**Comment by nebojsac** [comment]
What about loading the `Auth` and `Session` components? These I load in my `AppController`, and I did narrow down the issue to after the `Session->write()` fires.

**Comment by markstory** [comment]
I'll try writing to the session.

**Comment by markstory** [comment]
I tried adding `$this->Session->write('testing', 'wowow');` in both the action and `beforeFilter` of the controller I included in the earlier discussion. I still get `MissingViewException: View file "Articles/json/json.ctp" is missing.`

Is there a way you could share a small app/plugin that could make reproducing the issue easier for me?

**Comment by nebojsac** [comment]
I'll see about creating a skeleton app in which I can repeat the issue in the next few days. Sorry for the delay.

**Comment by markstory** [comment]
Any updates on this?

**Comment by nebojsac** [comment]
I've created a new CakePHP app, and just set up the specific route, controller and test, but the test is passing... Trying to get to repeat the same error now.

**Comment by nebojsac** [comment]
I'm not able to create a self-contained app with this issue repeating.
I've tried stripping down config files, AppController, bootstrap, etc. I'll circle back if I'm able to narrow it down somewhat. I'm considering removing the Route parsing in our app, as it then seems to function with `/Pages/test.json.ctp` as the view file. 

It works correctly in the new cake app, so I guess it's specific to us. If I ever figure it out I'll resurect this issue, but I think you can close it.
