### ISSUE TITLE
Execute shell from controller

### ISSUE THREAD

**Issue by mohammadsaleh** [cakephp/cakephp#10623]
Hi,
In cakephp 3.4.6 I was trying to run shell command in controller as below sample:
```
$shell = ShellDispatcher::run(
            ['cake', 'i18n', 'extract'],
            ['plugin' => 'B2b', 'overwrite' => 'yes', 'merge' => 'yes', 'extract-core' => 'no']
        );
```
but I realized that cake didn't merge my extra parameter in argument 2. so after I investigation in cakephp's codes I found that https://github.com/cakephp/cakephp/blob/master/src/Console/Shell.php#L465 line should be change to `return $this->{$method}->runCommand($argv, false, $this->params + ['requested' => true]);`

Regards,

**Comment by dereuromark** [comment]
Refs
https://github.com/cakephp/cakephp/issues/10202#issuecomment-299044069

**Comment by markstory** [comment]
Use one of PHP's built-in sub process features to invoke shells from you controllers.
