### ISSUE TITLE
Deprecate RepositoryInterface::alias in favor of get/set

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#10632]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: dev-master

### What you expected to happen

Following the changes done in \Cake\ORM\Table to mark alias method as deprecated, it could make sense to deprecate https://github.com/cakephp/cakephp/blob/master/src/Datasource/RepositoryInterface.php#L30 and require get/set methods?

**Comment by markstory** [comment]
Sounds like a good idea. We can't add new methods to interface classes as doing so breaks compatibility. But we can deprecate the existing method and add doc blocks for the new methods.

**Comment by cleptric** [comment]
PR is open
