### ISSUE TITLE
Is it possible to create an `Application` class for the plugin?

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10637]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.x

Is it possible to create an `Application` class for the plugin? I have some middlewares only for the plugin

**Comment by saeideng** [comment]
i think you can use in your plugin bootstrap
```
EventManager::instance()->on('Server.buildMiddleware',
    function ($event, $middleware) {
        $middleware->add(new someMiddleware());
    }
);

```

**Comment by dakota** [comment]
Middlewares interact with the entire request/response lifecycle. You cannot (currently) have middlewares only for certain plugins (I assume your plugin has controllers?).

3.5 will probably have a feature that could allow this: https://github.com/cakephp/cakephp/issues/10308

**Comment by slince** [comment]
1.  Yes, the plugin has controller and models;

2.  however,  we may need to do some initial work for controllers and shells if a plugin is dispatched, i hope that initial works is lazy. just be executed when the plugin is dispatched

Just give a suggestion:

defines a plugin:
```
//  plugins/FooPlugin/src/FooPlugin.php

namespace FooPlugin;

class FooPlugin extends Plugin
{
    public function beforeRun()
    {
          //records some logs
          Log::write('Plugin is dispatched');

         //loads the configuration file of the plugin
          Configure::load('/foo-plugin/config/app.php');

          //Change some globals variables;
          Configure::write('foo-global-var', 'a new value');
         
          // etc
    }
}
```
registers the plugin at `Application`

```
//  src/Application.php

class Application extends BaseApplication
{

    public function registerPlugins()
    {
        return [
               new FooPlugin\FooPlugin();
        ];
    }
}
```

When a plugin is dispatched, Application call `Plugin::beforeRun` first.

**Comment by slince** [comment]
@dakota

**Comment by dakota** [comment]
```
         //loads the configuration file of the plugin
          Configure::load('/foo-plugin/config/app.php');

          //Change some globals variables;
          Configure::write('foo-global-var', 'a new value');
```

That kind of stuff should be in the plugin's bootstrap.php file.

**Comment by markstory** [comment]
@slince We don't have plugin scoped application classes. We will have scoped middleware in 3.5 which is a bit closer. With your FooPlugin example, would beforeRun() be called anytime a plugin class is loaded, or only when a plugin route is visited?

**Comment by slince** [comment]
@saeideng  That is not enough to do that, the plugin `bootstrap.php` is always load when the application start.

@dakota   However it's not lazy load. I just hope it will be exectued when a plugin is loaded

@markstory  Anytime., not only controllers but also shell be dispatched

**Comment by markstory** [comment]
Shells and Controllers are easier to catch and run bootstrap code on. However, if a plugin's 'bootstrap' is required when models, or components are used then it becomes far more complex.

**Comment by slince** [comment]
yeah, but you do not need to think too much for the models and components now. just for controllers and shells, they are the entrance of a plugin application @markstory

**Comment by slince** [comment]
lazy load, lazy load, lazy load

"Important thing to say three times", this is a Chinese online proverb. ┗( ▔, ▔ )┛
@markstory @all

**Comment by markstory** [comment]
> just for controllers and shells, they are the entrance of a plugin application

Won't that leave the plugin in an inconsistent/incorrect state when only the models/components are used. I understand that controllers/shells are the entry point, but we have many more use-cases to consider than just those ones.

**Comment by ADmad** [comment]
Closing as #11564 will resolve this.
