### ISSUE TITLE
Will support that convert `Cake\Database\Schema\TableSchema`  to `Migrations\Table`  directly in  the migration files?

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10648]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

`TableSchema` and `Migrations\Table` are similar

I have a table schema

```php
$schema = new Cake\Database\Schema\TableSchema('foo', [
    'id' => [
         'type' => 'integer',
            'default' => null,
            'null' => false,
            'autoIncrement' => true
    ],
    'name' => [
          'type' => 'string',
           'length'  => 255,
           'default' => '',
           'null' => false
    ]
]);
```

Add method `Migrations\Table::fromTableSchema` 

```php

class CreateFooTable extends AbstractionMigration
{
      public function change()
     {
             $table = Migrations\Table::fromTableSchema($schema);
             $table->create();
     }
}

```
This will make it easy to reuse code.

Or let  `Migrations\Table`  extend `Cake\Database\Schema\TableSchema`. 

Just a suggestion!

**Comment by robertpustulka** [comment]
I like the idea. @slince could you create a PR for this?

**Comment by ADmad** [comment]
Closing as the issue has gone stale and no seems interested in implementing required feature.

**Comment by dereuromark** [comment]
Maybe this could be moved to migrations plugin?
