### ISSUE TITLE
The many to many records are removed from the database

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10641]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6

### background

`Transactions`  many to many `Orders`

### What you did

```
$transactionsModel = TableRegistry::get('Transactions');
$ordersModel = TableRegistry::get('Orders');

$transaction = $transactionsModel->get('1');
$order1 = $ordersModel->get(1);
$order2 = $ordersModel->get(2);
$order3 = $ordersModel->get(3);

$transaction->orders = [$order1, $order2, $order3];
$transactionsModel->save($transaction ); // The table `transactions_orders` has 3 records with transaction_id = 1


//continue
$order4= $ordersModel->get(4);
$transaction->orders = [$order4];
$transactionsModel->save($transaction );
// The table `transactions_orders`  only has one record with order_id = 4 and old records are removed.
```
### What happened

 The table `transactions_orders`  only has one record with order_id = 4 and old records are removed.

### What you expected to happen

Just add one record with order_id =  4 to the table `transactions_orders`, and preserve old records

**Comment by cleptric** [comment]
You can adjust this by changing the `saveStrategy` option when defining your relations in your table.

**Comment by slince** [comment]
@cleptric ; it's not a good idea; 
```
$order4= $ordersModel->get(4);
$transaction->orders = [$order4];
$transactionsModel->save($transaction );
$transactionsModel->save($transaction );
$transactionsModel->save($transaction );
```
If i set `saveStrategy ` as `append`, the above code will creats many same records in the table `users_roles`

**Comment by slince** [comment]
@cleptric   I could not generat too many garbage data in the database

**Comment by cleptric** [comment]
How does the schema of your relation table looks like?

**Comment by slince** [comment]
like:
### orders table
```
CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` char(12) NOT NULL DEFAULT '' COMMENT 'order no',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT 'user id'
  PRIMARY KEY (`id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=57765 DEFAULT CHARSET=utf8 COMMENT='订单';

```
### Tansaction table
```
CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '用户id',
  `serial_number` varchar(250) NOT NULL DEFAULT '' COMMENT '流水号'
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
) ENGINE=InnoDB AUTO_INCREMENT=893 DEFAULT CHARSET=utf8 COMMENT='交易记录';
```
### relations table
```
CREATE TABLE `transactions_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `transaction_id` int(11) NOT NULL DEFAULT '0' COMMENT '交易id',
  `order_id` int(11) NOT NULL DEFAULT '0' COMMENT '订单id',
  PRIMARY KEY (`id`),
  KEY `idx_transaction_order` (`transaction_id`,`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=22890 DEFAULT CHARSET=utf8 COMMENT='交易记录与订单关系';
```

I have removed some unwanted fields

@cleptric

**Comment by cleptric** [comment]
I guess you should set up your `transactions_orders ` to use a composite key of `transaction_id` and `order_id `

**Comment by slince** [comment]
@cleptric  Did you reproduce the problem?

**Comment by slince** [comment]
The relationship statement like this in `TransactionsTable`
```
        $this->belongsToMany('Orders', [
            'foreignKey' => 'transaction_id',
            'targetForeignKey' => 'order_id',
            'joinTable' => 'transactions_orders',
            'saveStrategy' => 'append'
        ]);

```

**Comment by inoas** [comment]
I'd also try to use through and setup a real model with a unique/primary key of both foreign keys and some rules inside that check for the uniqness

**Comment by ADmad** [comment]
@slince Did you remove the `id` field from join table and instead set composite primary key on `transaction_id ` and `order_id` instead?

**Comment by slince** [comment]
@ADmad  Not enough time; i remember an old cake3.0 documents has mentioned that join  table must have a id  for primary_key

**Comment by dakota** [comment]
@slince, Cake 2 had to have that as it did not support composite keys. For Cake 3 you should normally have composite keys for join tables (Where your DB server supports it)

**Comment by slince** [comment]
@ADmad   @cleptric 

### TestCase 1

 #### background：
- cake version: 3.3.16
- preserve id as pk

### result:

There is no difference between saveStrategy = 'append' and saveStrategy ='replace';
All old records will be removed;

***

### TestCase 2

 #### background：
- cake version: 3.3.16
- remove id and set `(transaction_id, order_id)` as pk

### result:

There is no difference between saveStrategy = 'append' and saveStrategy ='replace';
All old records will be removed;

***

### TestCase 3

 #### background：
- cake version: 3.4.6
- preserve id as pk

### result:
Will keep old records; But will generate the same records

***

### TestCase 4

 #### background：
- cake version: 3.4.6
- remove id and set `(transaction_id, order_id)` as pk

### result:
It's ok

**Comment by ADmad** [comment]
Given that 3.4 with composite primary key on the foreign key fields behaves as expected I don't think there's anything to be done here.

**Comment by slince** [comment]
@ADmad   However  the production cake version is 3.3.5; Is there any rescue plan?

**Comment by slince** [comment]
It seems the `saveStrategy` option is no effect in 3.3.x

**Comment by ADmad** [comment]
I have used `append` strategy in 3.3 and it worked as expected. Even if there is a problem in 3.3 bug fixes are only done for latest minor release so you need to upgrade. Minor release are backwards compatible so won't have any issues. Just check the migration guide make make any tweaks necessary if at all.

**Comment by slince** [comment]
OK， but i still hope that it also works well in the case of preserving `id` as pk; 
PS: You know that the composite keys are rarely used;

**Comment by slince** [comment]
@ADmad
