### ISSUE TITLE
3.5/4.0 Query Builder: Make contain() have a similar interface to matching(), leftJoinWith(), innerJoinWith()

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10651]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4

### What you did
I am often using closures on contain, matching, innerJoinWith, leftJoinWith.

### What happened
I am often typing the interface wrong because:

- `contain(['AssocName' => function($q) {}])`
vs
- `matching('AssocName',  function($q) {})` et al.

### What you expected to happen
The interfaces to be the same.

Could this be changed for 4.0?

**Comment by markstory** [comment]
Do we need to break compatibility to make both methods work similarly?

**Comment by inoas** [comment]
From the outside it looks like there are two options that could be BC:
- allow `contain()` to take a string + optional closure in addition to the array syntax.
- allow all the other methods instead to take an array in addition to string + optional closure

**Comment by markstory** [comment]
> allow contain() to take a string + optional closure in addition to the array syntax.

This sounds pretty reasonable given the current signature of `contain()`. Did you want to put a pull request together for that?

**Comment by jeremyharris** [comment]
If you cannot @inoas I would be happy to.

**Comment by inoas** [comment]
@jeremyharris so I am not sure if I can do it this week so in case you are faster, go ahead. Before attempting myself I will query/pm you on IRC/slack - so feel free to start any time!

**Comment by saeideng** [comment]
`contain()` receive multi key/value  but `matching()` no

**Comment by cleptric** [comment]
Closing this as we have an open PR
