### ISSUE TITLE
Supporting `AuthComponent::user()` return a user entity instead of an array

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10653]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

### 1
Usallay we need to get the user entity by `AuthComponent::user('id')`

```php
$user = $this->Users->get($this->Auth->user('id'));

$carts =$this->Carts->findUserCarts($user);
$order = $this->Orders->placeOrder($user, $carts);
```

If AuthComponent returns a user entity directly, it will make code more resuable  and efficient.

### 2
Support get the current authorized user in models and views directly. authorized user data should be global rather than just controllers

**Comment by chinpei215** [comment]
Earlier discussion: #9370, #3929

**Comment by markstory** [comment]
How would the user get injected into all the orm table objects? Right now we recommend using method parameters when you want to pass the user into orm related classes. If a global is wanted one could use `$_GLOBALS`. Getting the user into templates can already be done via beforeRender hooks, so I am nit sure we need to make more global symbols.

The new cakephp/authentication plugin will be replacing AuthComponent long term and it already implements getting the user as an object.

**Comment by slince** [comment]
@markstory   

1.  You know , the $globals is not recommend; We need a more elegant, readable and uniform way；

like this:

```php
// in the controller layer
$user = $request->getAuthorizedUser();

// in the view layer
$user = $request->getAuthorizedUser();

// in the middleware layer
$user = $request->getAuthorizedUser();

// in business logic layer  (like model but not model)
$user = $request->getAuthorizedUser();

// in other plugin
$user = $request->getAuthorizedUser();
```

2. > How would the user get injected into all the orm table objects?

 For code reusability I often write some business code like `getCurrentUserScore()` in models(business logic) ; The method has a  very clear purpose , if i want call the method in multiple controllers, do i have to give it `AuthorizedUserId` every times;

**Comment by ADmad** [comment]
Given that the new cakephp/authentication plugin already has this feature I too am not in favor of adding this to the core AuthComponent.

**Comment by markstory** [comment]
@slince I know that GLOBALS are frowned upon, but I often see developers going to through elaborate steps to effectively recreate global variables when containers are used as service locators.

In the case where you have a method like `getCurrentUserScope()` how does the model layer get the user scope/context set? Are you still passing a user as a method parameter, or do the models get the user passed in some other way?

**Comment by slince** [comment]
@markstory I am pursuing the readability of the code; Ugly code makes me uncomfortable；

>  how does the model layer get the user scope/context set? Are you still passing a user as a method parameter,

No,  we should get the user data directly  in models(business logic);
```
public function getCurrentUserScores()
{
     $user = $this->request->getAuthorizedUser();
     return $user->scores;
}
```
Notes: it should be in a  business logic level; however there is no business layer in cake app; I can only writes the method in the models

**Comment by markstory** [comment]
Ok. I would prefer to avoid adding the request to all the ORM table objects as that feels like an awkward set of responsibilities for a class to have.

You're right that there is no pre-defined 'business layer' in CakePHP, as my personal assumption was that people would build that themselves, as each application has different requirements for the 'business layer'. This is one of the reasons that model loading and mailer loading are provided by traits.

**Comment by slince** [comment]
@markstory 

It' s also good like this
```
public function getCurrentUserScores()
{
     $user = Request::instance()->getAuthorizedUser();
     return $user->scores;
}
```

**Comment by markstory** [comment]
I'm not interested in adding more global variables/singletons. They fare poorly when we have to deal with sub-requests and testing/mocking.

**Comment by robertpustulka** [comment]
`AuthComponent` will probably be removed in 4.0 and deprecated soon in favour of `cakephp/authenticate` so I don't think we should add any new features.

**Comment by slince** [comment]
@ADmad  @robertpustulka   Will `cakephp/authenticate` can let me access the authorized user entity in every level  using a uniform way? 
The focus is not `AuthComponent` or `cake/authenticate` ,  but whether the problem can be solved。

**Comment by robertpustulka** [comment]
@slince it already does through request attribute. Try it [cakephp/authentication](https://github.com/cakephp/authentication)

**Comment by littleylv** [comment]
@slince  cakephp/authentication has set user entity in request attribute. see:
https://github.com/cakephp/authentication/blob/master/src/Identifier/PasswordIdentifier.php#L139
https://github.com/cakephp/authentication/blob/master/src/Authenticator/FormAuthenticator.php#L83-L90
https://github.com/cakephp/authentication/blob/master/src/Middleware/AuthenticationMiddleware.php#L68

**Comment by slince** [comment]
@littleylv  Thanks I will try.

**Comment by dereuromark** [comment]
Can be moved to https://github.com/cakephp/authentication and https://github.com/cakephp/authorization/ respectively if not already solved.
