### ISSUE TITLE
Adding options variable to TableSchema::columnType() and Cake\Database\Type

### ISSUE THREAD

**Issue by riddlemd** [cakephp/cakephp#10652]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: +3.4.*
* Platform and Target: All

### Feature Idea
Support for Types to have options assigned to them when being set to column schema. I ran into a few issues where this would be exceedingly handy. For example I have a cryptedType that uses Security::encrypt to encrypt data before saving to the database and decrypting it when reading back into PHP, the issue is you have to edit the cryptedType.php to set the Key value (or set it up to read a Configure variable). It would be much easier to be able to define a per field secret when assigning the type in the Table class via options passed when setting the column type.

Example:
```
// In the Table class
protected function _initializeSchema(\Cake\Database\Schema\TableSchema $schema)
    {
        $schema->columnType('cc_number', 'crypted', ['secret'=>'SOME_LONG_SECRET_STRING']);
        $schema->columnType('call_in_password', 'crypted',
 ['secret'=>'SOME_OTHER_LONG_SECRET_STRING']);
        return $schema;
    }


// In the cryptedType class
public function toDatabase($value, Driver $driver)
    {
        return Security::encrypt($value, (!empty($this->options['secret']) ? $this->options['secret'] : ''));
    }
public function toPHP($value, Driver $driver)
    {
        return Security::decrypt($value, (!empty($this->options['secret']) ? $this->options['secret'] : ''));
    }
```
This way it increases the time it would take for a compromised database to be fully cracked (vs all fields using the cryptedType having the same key).

I also have a [MpeaType](https://bitbucket.org/snippets/riddlemd/Br946/minimally-populated-entities-arrays-mpea) which takes an array of entities and reduces them to an array of sourceName keys with primaryKey values in it for storage in a text/json field. It would be nice to be able to specify some additional options on column set. Like the ability to set other fields to be stored with the primaryKey that could be used for reference later (Like when saving items in a shopping cart you could reduce the set and save the primaryKey and current price and then when the person comes back and rehydrate the entity it can show them if the price went up and down since they're last visit.)

I've played around with a few implementations of this, but before investing a load of time into this I figured I'd ask if anyone has any suggestions on why this would be a bad idea to implement.

**Comment by markstory** [comment]
One challenge with the example you've provided will be that only one of each Type object is created per request, and types objects don't have access to schema metadata. I like the general concept though, as it allows custom column types to provide more value.

**Comment by ADmad** [comment]
I would like this feature too, especially type classes having access to schema meta data.

**Comment by riddlemd** [comment]
> @riddlemd Do you want to make a PR for 4.x?

Ya -- let me clean up my code and I'll put a PR in for 4.X

**Comment by riddlemd** [comment]
I'll need to dig up the project I worked on this for and cleanup the code -- but yes I'll try to get a PR in for 4.0.

**Comment by dereuromark** [comment]
Any API related changes for 4.x would be addable still for a bit, if you want to make a PR here.

**Comment by othercorey** [comment]
Wouldn't this be possible at the Behavior level instead of the Schema level?
