### ISSUE TITLE
Inconsistent default behaviour between form::control and form::checkbox

### ISSUE THREAD

**Issue by aaronstillwell** [cakephp/cakephp#10662]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6 (Possibly since 3.3.13, see below comment with attached blame)
* Platform and Target: Apache, Mysql 5.7, PHP 7.1

### What you did
Create a checkbox via the form helper.
`$this->Form->control('my_field'); // broken`
`$this->Form->checkbox('my_field'); // works`

### What happened
Using the control method, the hidden input field is _not_ generated. When using the checkbox method, the hidden field _is_ generated.

### What you expected to happen
The `control` method should by default behave in the same way as `checkbox` for generating checkbox fields.

**Comment by aaronstillwell** [comment]
Note that supplying the `hiddenField` option to `control` works as expected. E.g

`$this->Form->control('my_field', ['hiddenField' => true]);`

**Comment by aaronstillwell** [comment]
The issue appears to be here:

https://github.com/cakephp/cakephp/blob/917f876168e4b5af2a787f3d17b7659c1f4cb679/src/View/Helper/FormHelper.php#L1115

The above condition will always evaluate to true when invoking `control` to create a checkbox with no arguments.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue in our [test cases](https://github.com/cakephp/cakephp/commit/18f68aaa36d72dbd91a5eccad790af45dbaebfaa), or in a sample application I have. I'll need a way to reproduce this issue to look into it further. I tested against `master` and the `3.4.6` in my sample application.

**Comment by aaronstillwell** [comment]
Hi @markstory, thanks for investigating - looks like I wasn't thorough enough with this.

After drilling down further into the issue this morning it became apparrent this was a templating issue. Our own templates are based on the Cake defaults regarding checkboxes, so I couldn't figure what would account for the discrepancy.

As it turned out, we were missing `{{hidden}}` on our `nestingLabel` template. Very easy to miss.

E.g
```
// ...
'nestingLabel' => '<label {{attrs}} class="col-sm-6 text-right">{{text}}</label>{{input}}',
// ...
```

Would it be worthwile making a change to the docs to highlight the subtlety here? (https://book.cakephp.org/3.0/en/views/helpers/form.html#creating-checkboxes might be a good place). I'll be more than happy to follow this up myself with a PR.

**Comment by markstory** [comment]
Yes a documentation update would be awesome!
