### ISSUE TITLE
Add support for Common Table Expressions (CTE)

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10666]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: MariaDB 10.2

### What you did

```sql
# This is a Common Table Expression (this issue):
WITH cms_elements_translations AS (
  SELECT
    cms_elements_translations.id AS id,
    cms_elements_translations.locale_code AS locale_code,
    cms_elements_translations.body AS body,
    # This is a Window Function (for demonstration, only):
    ROW_NUMBER() OVER (PARTITION BY id ORDER BY (CASE
      # These conditions need to be build based on HTTP_ACCEPT_LANGUAGE:
      WHEN cms_elements_translations.locale_code LIKE 'en-US' THEN 0
      WHEN cms_elements_translations.locale_code LIKE 'de-__' THEN 1
      WHEN cms_elements_translations.locale_code LIKE 'en-__' THEN 2
      WHEN cms_elements_translations.locale_code LIKE 'fr-__' THEN 3
      WHEN cms_elements_translations.locale_code LIKE 'de-DE' THEN 4
    END) ASC) AS rank
  FROM cms_elements_translations
  # These are some cms_elements.id from contain():
  WHERE cms_elements_translations.id IN (
    '1bc23a23-d9ec-4a48-981d-27a74a8b2446', 'ef6368e3-92f4-47cd-946e-f2633ac36016')
)
SELECT * FROM cms_elements_translations
WHERE cms_elements_translations.rank = 1;
```

### What happened

... cannot easily create this with the 3.x ORM builder. I cannot use an SQL view for the CTE as the CASE WHEN conditions within the window function are programmatically build by reading HTTP_ACCEPT_LANGUAGE

### What you expected to happen

A way to add/prepend CTEs to queries.

I have found `Query::epiloque()` but there is neither `Query::prepend()` (raw) nor `Query::addCommonTableExpression()` or similar.

### Workaround/Hack

Use derived tables, aka `->from(['CmsElementsTranslations' => $rankingQuery])`, then I just had to convert the window function to CakePHP3 ORM, which brought its own issues: https://github.com/cakephp/cakephp/issues/10670

### Vendor Docs for Common Table Expressions
- MariaDB 10.2 https://mariadb.com/kb/en/mariadb/non-recursive-common-table-expressions-overview/
- Postgres (8.4+) https://www.postgresql.org/docs/9.2/static/queries-with.html
- MS SQL Server https://msdn.microsoft.com/de-de/library/ms175972.aspx as per @stmeyer 
- Oracle http://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#SQLRF30048

**Comment by stmeyer** [comment]
CTEs in SQL Server: https://msdn.microsoft.com/de-de/library/ms175972.aspx

**Comment by ADmad** [comment]
It is unlikely the required enhancements to resolve this issue are going to be done in 4.0. Hence changing milestone to `Future`.

**Comment by ndm2** [comment]
@ADmad Do you remember which issues specifically where blocking this?

**Comment by ADmad** [comment]
@ndm2 I don't think anything was blocking it except someone actually implementing required changes. The issue was auto closed due to lack of activity.

**Comment by othercorey** [comment]
This is something I will implement in the future, but I don't think I'll have time to work on it before 4.1 -- I'll re-open and pin it to 4.2 for anyone tracking this.

**Comment by ndm2** [comment]
@ADmad I see, I had to implement this for a recent project, so I thought I might be able to come up with something that could possibly go into the core.

Guess I'll just put a more or less copy & paste PR together and ask for some input.

**Comment by ndm2** [comment]
> This is something I will implement in the future ...

Oh well... guess I could give it a shot anyways :)

**Comment by othercorey** [comment]
Feel free! I'll adjust the milestone when we release 4.1.

**Comment by ndm2** [comment]
PR open #14525

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/cakephp/pull/14525
