### ISSUE TITLE
Route Prefix containing dots

### ISSUE THREAD

**Issue by rchavik** [cakephp/cakephp#10678]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x-next
* Platform and Target: N/A

### What you did
```php
Router::plugin('Croogo/Users', ['path' => '/'], function($route) {
    $route->prefix('api', function($route) {
        $route->prefix('v1.0', function($route) {
            $route->fallbacks();
        });
    });
})
```
### What happened
Cake is not able to resolve namespace and get the controller name

### What you expected to happen
- Cake is able to resolve the request for the following class: `Croogo\Users\Controller\Api\V1_0\UsersController`
- Cake correctly generates the link for:
```php 
echo $this->Html->link('Lookup', [
    'prefix' => 'api/v1.0',
    'plugin' => 'Croogo\Users',
    'controller' => 'Users',
    'action' => 'lookup',
]);

**Comment by markstory** [comment]
Prefixes have to be valid PHP identifiers. One option would be to add a `path` option the prefix method. This would let you call prefix like:

```php
$routes->prefix('v1', ['path' => '/v1.0'], function ($routes) {
   // routes here.
});
```

And you'd used `'prefix' => 'v1'` in your URL generation.

**Comment by rchavik** [comment]
Based on Mark's suggestion, I've managed to achieve what I want by:

```php
Router::plugin('Croogo/Nodes', ['path' => '/'], function (RouteBuilder $route) {
    $route->prefix('api', function (RouteBuilder $route) {
        $route->scope('/v1.0', ['prefix' => 'api/v10'], function (RouteBuilder $route) {
            $route->extensions(['json']);
            $route->scope('/nodes', [], function (RouteBuilder $route) {
                $route->fallbacks();
            });
        });
    });
});
```

And links are generated as follows:

```php
echo $this->Url->build([
    'prefix' => 'api/v10',
    'plugin' => 'Croogo/Nodes',
    'controller' => 'Nodes',
    'action' => 'lookup',
    'type' => $node->type,
    '_ext' => 'json',
]);
```

It seems to work, although the requirement of having to prefix with '/' for first argument of `scope()` and the need for passing `prefix` option threw me off a bit.

**Comment by markstory** [comment]
@rchavik If you have the time/interest, a pull request to enhance `RouteBuilder::prefix()` would be great and would make your code simpler too :smile:
