### ISSUE TITLE
EntityContext->val() always take data from request->data 

### ISSUE THREAD

**Issue by makamo** [cakephp/cakephp#10677]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6.
* Platform and Target: Nginx, php7-fpm, mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### What you did
I want to save my form change data in the entity clear it and render the form with the new entity data without redirect
I change de valueSources for context but i cant reset the request->data because its not mutable
### What happened
The values in Form come from request data not from the entity.
### What you expected to happen
[https://api.cakephp.org/3.4/source-class-Cake.View.Form.EntityContext.html#233](https://api.cakephp.org/3.4/source-class-Cake.View.Form.EntityContext.html#233)
I think this method should check the entity data before getting values from request data.

Sorry for my bad english im french

**Comment by markstory** [comment]
We use the request data over the entity data, because of validation failures. If we used entity data, then user input would be reset when validation errors were encountered.

Request data can be changed via the `withParsedBody()` and `withData()` methods. Is there a reason those aren't working for you?

**Comment by makamo** [comment]
ok but these methods do not change the request->data that is sent to the view

**Comment by markstory** [comment]
If you want to reset the form to the new entity data, you'll have to wipe the request data after your entity has been updated/is saved. Or create a custom context for your application that does what you need. I don't understand this use case well enough to modify CakePHP to accommodate it.

**Comment by makamo** [comment]
Thank you for the explanations. Now I understand better how to solve my problem.
