### ISSUE TITLE
Drop support for HHVM officially?

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#10674]
We recently opted out of building the framework on HHVM in Travis CI due to issues with it and seemingly a lack of interest in it: https://github.com/cakephp/cakephp/commit/6339c68bde825b68026eee4020712760a4addb36

On another note, both Symfony and doctrine will drop their support for HHVM:

https://github.com/facebook/hhvm/issues/7198#issuecomment-302515837

Related tweets:
https://twitter.com/fabpot/status/865263458903875584
https://twitter.com/fabpot/status/865080534669635584

What is our stance towards supporting HHVM for CakePHP 3.x, 2.x or in general?

Related repo searches on framework, app template and docs:
https://github.com/cakephp/cakephp/search?utf8=%E2%9C%93&q=hhvm&type=
https://github.com/cakephp/app/search?utf8=%E2%9C%93&q=hhvm&type=
https://github.com/cakephp/docs/search?utf8=%E2%9C%93&q=hhvm&type=

**Comment by markstory** [comment]
I am :+1: on this. We haven't had passing tests on HHVM in 6+ months. I don't think we can say we 'support' it if our tests can't pass.

**Comment by lorenzo** [comment]
We never had 100% tests passing in hhvm. We tried, though

**Comment by markstory** [comment]
Given the features of PHP we use, HHVM didn't make it easy to get to 💯

**Comment by ravage84** [comment]
I understand your responses and reactions as a clear __Yes__.
