### ISSUE TITLE
Deleting non-existent folder gives warning

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#10676]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.4.6
* Platform and Target: OSX Sierra 10.12.4

### What you did
```php
$folder = new Folder('/this/folder/does/not/exist');
$folder->delete();
```

### What happened
`Warning (2): unlink(/this/folder/does/not/exist): Is a directory [ROOT/vendor/league/flysystem/src/Adapter/Local.php, line 256] `

### What you expected to happen
The default constructor of `Folder($path, $create = false)` should not create a new folder.
Deleting a nonexistent folder should not show PHP errors, and it should not be trying to `unlink()` a folder.

### What I use to avoid this error:
```php
if (file_exists($path)) {
    $folder = new Folder($path);
    $folder->delete();
}
```

**Comment by ndm2** [comment]
If you look closely, the error happens in the Flysystem library. I think you've imported the wrong `File` class.

**Comment by ndm2** [comment]
If you look closely, the error happens in the Flysystem library. Are you sure that you're using the correct class? Respectively that the error is really triggered by the shown code?

**Comment by mehdi-fathi** [comment]
This Lib check existing of folder by `is_dir($path)` after that it starting unlink folder.that's ok.I read it
