### ISSUE TITLE
Plugin::routes('foo') won't always load routes

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#10672]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6

What the API docs say about Plugin::routes():
> Loads the routes file for a plugin, or all plugins configured to load their respective routes file

It seems to imply that when a plugin is specified the routes will be loaded regardless of configuration, but it doesn't work that way. It won't load routes unless they're configured to load for the given plugin.

In case you're thinking the bug is in the documentation, I'd like to make a point that making it work as documented could be useful. I'm trying to do this:

config/boostrap.php
```php
Plugin::load('CakeDC/Users', ['routes' => false, 'bootstrap' => true]);
```
config/routes.php
```php
Router::prefix('admin', function (RouteBuilder $routes) {
  Plugin::routes('CakeDC/Users');
});
Plugin::routes();
```

I'd like to help make it work as documented.

**Comment by berarma** [comment]
No way this could work. The plugin routes don't use the $routes variable but the static class methods.

I'll have to do my own routing for the plugin. It would be cool that something like what I had imagined would work.

I'll let the issue open so you can take what you want out of it or just close it.

**Comment by markstory** [comment]
I think the documentation could be clearer on which routes will be loaded, but I don't want to expand the static interface of Router at all. I haven't put much thought into how plugin routes could be loaded through the RouteBuilder, but I would like to solve that in 3.5 or 3.6

**Comment by berarma** [comment]
Well, then the focus for this issue has changed. Maybe a new issue should be opened.

I'll comment a bit more about my experience with routing and plugins in case something could be done about it. Maybe it's that I'm new to this kind of problems since I haven't used/implemented many plugins implementing controllers.

I'm trying to use the CakeDC/Users plugin into my app without having to fork it and all problems I've had so far are related to routing.

Already said, but the first problem is not being able to load plugin routes inside an app routing prefix/scope.

The next problem has to do with prefixes. I'm starting to dislike prefixes since it hardcodes the mapping of the url to filesystem directories cutting on flexibility. While I like being able to tag URL accesses with a prefix and having admin controllers/templates in a special directory, I'm disliking not being able to fully configure the way it works.

I'm using the admin prefix in my app and I've tried creating the plugin routes inside that prefix with no success. Plugin controllers and templates are searched in the wrong directories since the plugin wasn't built to be used with the admin prefix.

When putting the plugin routes outside the prefix I still have problems using the plugin's helpers to create links to the plugin elements since they use the current prefix and create links with prefix admin that the plugin doesn't have. This could be fixed in the plugin but it would be better that the plugin didn't have to worry about the prefix or scope it has been routed in.

**Comment by markstory** [comment]
> Already said, but the first problem is not being able to load plugin routes inside an app routing prefix/scope.

Having plugin routes loadable from the route builder would solve this problem, as you could load a plugin's routes from inside a scope defined in the application.

> The next problem has to do with prefixes. I'm starting to dislike prefixes since it hardcodes the mapping of the url to filesystem directories cutting on flexibility. While I like being able to tag URL accesses with a prefix and having admin controllers/templates in special directories, I'm disliking not being able to fully configure the way it works.

If you're looking to add path prefixes that don't impact the class/namespace/filesystem layout you should use `RouterBuilder::scope()` as that is what it is for.

**Comment by berarma** [comment]
Is there some easy way to replicate prefixes functionality with scopes that is implemented in the core? That is, being able to easily identify the scope of the current URL, something like ```$this->request->scope```. And also being able to put controllers where I want, ideally some option in the scope definition to change the default controller subdirectory.

**Comment by markstory** [comment]
There is no scope attribute on the request. What use cases do you have for one? Right now scope() just adds static URL segments to the routes that they contain.

**Comment by ADmad** [comment]
Closing the issue has gone stable.
