### ISSUE TITLE
"[Error] Cannot unpack array with string keys" while using custom Validator rules in Cake 3.4.5

### ISSUE THREAD

**Issue by animepauly** [cakephp/cakephp#10682]
This is a (multiple allowed):

* [x] [Error] Cannot unpack array with string keys in /var/www/public/adphenom-portal/vendor/cakephp/cakephp/src/Validation/ValidationRule.php

* CakePHP Version: 3.4.5.

### What you did
When trying to register new users in our user registration form, the above error is thrown. The form consists of first name, last name, email address, password, confirm password, and birthdate fields. This worked on 3.3.x (not sure what exact version we were on before), but the form currently fails in 3.4.5.

### What happened
I have pinpointed the problem to two custom validator rules in the UsersTable.php file:
```
$validator->add('new_password', [
            'length'=>[
                'rule'=>['minLength', 6],
                'message'=>'Password must contain at least 6 characters'
            ],
            'hasUppercase'=>[
                'rule'=>['custom', 'regex'=>'/[A-Z]/'],
                'message'=>'Password must contain at least one uppercase letter'
            ],
            'hasDigit'=>[
                'rule'=>['custom', 'regex'=>'/[0-9]/'],
                'message'=>'Password must contain at least one number'
            ]
        ]);
```

The 'hasUppercase' and 'hasDigit' rules are what's causing this error to be thrown. 

### What you expected to happen
I expect the custom validator rules to work as they did in version 3.3.x.

**Comment by markstory** [comment]
Pull request up now.
