### ISSUE TITLE
3.4.6 Connection::connect() never gets called

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10684]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.6

### What you did
I was toying with something along these lines:
https://gist.githubusercontent.com/inoas/3a767fff7a416e4044339ce58bb66575/raw/828796f6d133f6524d8011de421c32c75c8dd2bd/Connection.php

### What happened
I realized that Mysql::connect() (aka the driver classes connect method) is being called, but not the one on the Connection.

### What you expected to happen
All the connection calls being wrapped from Connection::connect()

* Can you confirm this?
* Is there a reason why this is designed this way?
* What's the purpose of Connection::connect() then?

**Edit:**
### Workaround

```php
<?php
/**
 * Extending CakePHP Core Mysql driver to try to connect to a fallback datasource if the connect was unsuccessful.
 */
namespace App\Database\Driver;

use \Exception;
use Cake\Core\Configure;
use Cake\Database\Driver\Mysql as CoreMysql;

class Mysql extends CoreMysql
{

    /**
     * Establishes a connection to the database server, featuring a fallback config.
     *
     * @return bool true on success
     */
    public function connect()
    {
        $fallbackConfig = Configure::readOrFail('FallbackDatasource') + $this->_baseConfig;
        try {
            parent::connect();
        } catch (\Exception $e) {
            $this->_config = $fallbackConfig;
            parent::connect();
        }

        return true;
    }

}
```

**Comment by inoas** [comment]
Another pain was that the Datasource key of the Configuration seems to be configured (I supposed to stop leaking of passwords).

**Comment by markstory** [comment]
> What's the purpose of Connection::connect() then?

If someone wants to force the connection open, this method is for that.

**Comment by inoas** [comment]
Well that's fair, but it is not what the class appears to be doing (counter-intuitive?), especially not when it is settable in app.php as part of the standard Datasource configuration?

Is class Connection ignored all-together for non-explicit connections?
Is it sufficient to change the docblock of `connection()`?

Would best practice be to overwrite PDODriverTrait::connect()?
