### ISSUE TITLE
3.5 Add Configure::consumeOrFail()

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#10685]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.6

### What you did
Read fallback database sources.

### What happened
`Datasource` is being consumed but `FallbackDatasource` is not.
Realized I cannot move from `readOrFail()` to `consumeOrFail()` cause latter misses.

### What you expected to happen
`consumeOrFail()` to exist.

```php
    /**
     * Used to consume information stored in Configure. It's not
     * possible to store `null` values in Configure.
     *
     * Acts as a wrapper around Configure::consume() and Configure::check().
     * The configure key/value pair consumed via this method is expected to exist.
     * In case it does not an exception will be thrown.
     *
     * @param string $var Variable to consume. Use '.' to access array elements.
     * @return mixed Value stored in configure.
     * @throws \RuntimeException if the requested configuration is not set.
     * @link http://book.cakephp.org/3.0/en/development/configuration.html#reading-configuration-data
     */
    public static function consumeOrFail($var)
    {
        if (static::check($var) === false) {
            throw new RuntimeException(sprintf('Expected configuration key "%s" not found.', $var));
        }

        return static::consume($var);
    }
```

### RFC
Replace all calling instances of consume() with consumeOrFail()?

**Comment by markstory** [comment]
We could just make `consume()` raise exceptions when keys are missing too :smile:

**Comment by inoas** [comment]
Well I'd love too. I think both methods should actually throw exceptions. 
However it is probably not BC?

**Comment by dereuromark** [comment]
In that case a new method consumeOrFail() makes sense to have BC for the old methods.

**Comment by markstory** [comment]
Adding new exceptions to existing methods doesn't break backwards compatibility according to our guidelines.

**Comment by dereuromark** [comment]
Only exceptions in case of unexpected outcome.
In this case here this might Break a few live Apps  that Just didnt expect it.

**Comment by markstory** [comment]
>  In this case here this might Break a few live Apps that Just didnt expect it.

But its the kind of change that would fit into a minor release like 3.5.0 or 3.6.0.

**Comment by inoas** [comment]
I was actually using the consumeOrFail() above in Mysql::connect() to realize that it gets called multiple times and then the configuration parameter is not available anymore.

Now I understand why, but if that changes all of a sudden in an app that you upgrade, it is no fun.

I still think we should introduce consumeOrFail() now and deprecate consumeOrFail() and readOrFail() in 4.x where consume() and read() would do what +OrFail() do now (and then maybe give it an option to not fail on missing keys ... or have another method that doesn't fail on read). Aka exception on default for 4.0

**Comment by ravage84** [comment]
I like the idea of ``consumeOrFail()`` 👍 

The underlying behavior is no supprise using this name, we certainly break nobody's application and the naming is in line with other ``xyzOrFail()`` methods.

**Comment by dereuromark** [comment]
@inoas Will you PR the discussed changes?

**Comment by ADmad** [comment]
Closing as the issue has gone stale. A pull request is welcome if you are still interested in adding this feature.
