### ISSUE TITLE
Native realtime app updates, like Google's Firebase (feature request)

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#10683]
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4

### Native realtime app updates
Like Google's Firebase, automatic realtime updates with whatever is in the database. So reflect the database in the app, in realtime.

Not only would this save me, and others a ton of time, but I think this would help Cake compete with Firebase. 

I assume this would involve including a js file and some server-side endpoints to solve this. There is probably going to be an increase in resource usage, but cake's caching should trim a lot of that down right?

**Comment by inoas** [comment]
IMHO this is a massive application that you should build standalone or as a plugin and should for sure not be in CakePHPs core.

If you really want live database updates programmatically, you could take something like CRUD and/or ReactJS and work from there.

**Comment by markstory** [comment]
Adding support for firebase and realtime updates is well outside the domain of what CakePHP is. This sounds like a great idea for a plugin though :smile:
