### ISSUE TITLE
Improve ergonomics of defining routes

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10689]
Separated from #10643 to be the work that can fit into the 3.5/3.6 timeline. These changes  intend to make the ergonomics of defining routes simpler:

* [x] Addition of HTTP method specific shorthands $routes->post(), $routes->put() etc.
* [x] Fluent interface methods for existing 'options'. The existing options that could have fluent setters defined are name(), method(), host(), requirements()
* [x] Add fluent helpers that were missed the first time. `pass()`, `persist()`, `multibytePattern()`
* [x] Make loading plugin routes a feature of the RouteBuilder. eg. `$routes->loadPlugin($name)`.
* [x] Compact defintion of Articles::view pairs. This is just a sugared version of ['controller' => 'Articles', 'action' => 'view']. It has no option/features for specifying more than the controller/action.
* [x] Enable `{var}` placeholders. This format will replace `:var` style placeholders potentially in 5.x as it is simpler/faster to parse out and doesn't suffer from mid word placement issues like `:var` does. See #9188 for an example route.

**Comment by jeremyharris** [comment]
Copied from slack:

> I was wondering about the shorthand verb methods. Would they cause a 404 or a 405 if you sent a GET to a route that only had a DELETE. My initial assumption would be 404 as a get route doesn’t exist, although this is different behavior than most current applications which throw method not allowed within the action.

Perhaps this is just a matter of documentation.

**Comment by inoas** [comment]
It really depends on security, I think. Github for instance shows 404 for projects you have no access to instead of 403 or 401.

The more pure response would be to clearly state what's wrong within HTTP status code speak: The method. The obfuscating/"secure" response would be to just throw 404.

And well, depending on the context / app - imho - you would want one or the other.
=>
* make it configurable?
* pick a sane default?

**Comment by markstory** [comment]
Presently a mismatch on method will result in a 404 as the URL may not match any defined routes.

**Comment by rchavik** [comment]
Is there anything that can be done for `Html::link()`?

Setting route is a one time thing, but `link()` usage is far more numerous.

**Comment by ravage84** [comment]
I'm not sold on this ``Articles::view`` thing. Is that something that is asked a lot?

Also, agree with @rchavik.

**Comment by jeremyharris** [comment]
I was worried this would be expected if we add a short reference for controller/action.

In regards to links, they often have much more information for building the route. How would you handle this:

```php
$this->Html->link('Title', [
    'controller' => 'Users',
    'action' => 'view',
    'prefix' => 'admin',
    '_ext' => 'json',
    1
]);
```

Perhaps a "short" param of some sort could handle just the `controller::action` only, however that doesn't seem like much of a time save as you'll still need to wrap things in arrays.

**Comment by inoas** [comment]
@jeremyharris that sounds not too bad... 

Some examples with some exemplative/constructed reverse-routing results

```php
$this->Html->link('label', 'controller::action.ext', [options]);
$this->Html->link('List Posts', 'Posts::index.html'); // /posts/index.html
$this->Html->link('Read More...', 'Posts::view', [$id]); // /posts/article-foo-slug
$this->Html->link('New Post', 'MyPlugin.Posts::add'); // /my-plugin/posts/new
$this->Html->link('New Post', 'Admin::Posts::add'); // /admin/posts/new
$this->Html->link('New Post', 'MyPlugin.Admin::Posts::add'); // /my-plugin/admin/posts/new
```

By the way... is there for sure no way to make this shorter?

Maybe we can introduce `$t = $this;` as a convention? I pretty much liked the 1.3 way of doing this but I see that there were a lot of chances for Clashes. Another way to shorten the often appearing links would be to alias link() to a() (similar to `<a href>`).

In total the reduction of repeating boiler-plate charachters in templates would be big I think:
```php
$t->Html->a('Read More...', 'Posts::view', [$id]);
$this->Html->link('Read More...', ['controller' => 'Posts', 'action' => 'view', $id); 
```

**Comment by jeremyharris** [comment]
@ionas at that point, you're basically building the url yourself, save some reverse routing 😆 

Your 3rd example also changes the signature of $this->Html->link. That's what I meant by needing to wrap it in an array despite a short reference:

```php
// not really much of an improvement imo
$this->Html->link('Read more...', ['short' => 'Posts::view', $id]);
```

I'm for more clear explicit definitions. If we want to make the Url builder fluent, I'm okay with that, however it's usually just as much code (in the view).

```php
// constructor could accept the "short" version of controller::action
$url = (new Url('Posts::view'))
  ->setPlugin('Foo')
  ->setExt('json');
$this->Html->link('Read more...', $url);
// or
$url = (new Url)
  ->setController('Posts')
  ->setAction('view')
  ->setPlugin('Foo')
  ->setExt('json');
```

(P.S. I'm against adding `$t` as a local var; that's easy enough to implement in your view class.)

Honestly I think the array structure is fine and moving towards a builder of sorts is fine too. I just think a full string that needs parsing gets a little silly: `FooPlugin.Admin.Posts::view/1.json`

**Comment by ravage84** [comment]
@ionas 
````$t->Html->a('Read More...', 'Posts::view', [$id]);````
This is aweful. 😱 Code like it's 1999.

If you really want/need it shorter, wrap it into a global function like ``htmlLink('Read More...', 'Posts::view', [$id])``.

@jeremyharris I thought about a fluent interface for building URLs, too.
I guess it could even be static.
Anyway, I still don't think we really need that.



I think we already have what we need and it's called "Named routes":



https://book.cakephp.org/3.0/en/development/routing.html#using-named-routes

**Comment by inoas** [comment]
@ravage84 named routes require extra efforts and are very verbose.

The method being named `link()` vs `a()` actually confused me when I started CakePHP years ago because there is both, Html `<link/>` and Html `<a/>` and - history aside - naming it `HtmlHelper::link()` over `HtmlHelper::a()` was a bad choice that can be improved.

**Comment by jeremyharris** [comment]
@ionas what I'm saying is that [HtmlHelper::link][1] already has a third param, so this example:

```php
$this->Html->link('Link', 'view', [$oldParamsHere])
```

Would not allow a passed arg (unless you hijack the third param for url params too, which is a Bad Idea).

If we parse entire strings into URLs, how would a string representation of the following look?

```php
Router::url([
  'prefix' => 'admin',
  'controller' => 'Users',
  'action' => 'view',
  $user->id,
  $user->slug,
  '?' => [
    'query' => 'arg',
  ],
  '_ext' => 'json',
  '_full' => 'true',
]);
```

I don't think a string representation would be a) clearer than a builder/array, or, b) faster to type (especially with a builder + IDE).

If a short representation is done (e.g., just controller/action/plugin/prefix/ext), I still think it should be in a separate array param to not break existing signatures. A partial solution is probably not preferred, and perhaps the short approach should only apply to routes.

Verbosity is not always a bad thing. The more I program the more I prefer it, and that's why tools like IDEs exist; to help reduce the amount we actually type without requiring us compromise on code readability/maintainability.

[1]: https://api.cakephp.org/3.4/class-Cake.View.Helper.HtmlHelper.html#_link

**Comment by markstory** [comment]
Couldn't people use named routes for shorter route generation? The following works today:

```php
$this->Html->link('yay', ['_name' => 'posts:view', $id]);
```

as long as you generate your routes with names :smile:

**Comment by slince** [comment]
@markstory  Not all routes  have names;

I agree with @ravage84  ; Perhaps should provide some global helper function:

```
url('route-name',  ['foo' => 'bar'], true); //it  is easy to generate path for named route.

//for anonymous routing
action('Posts::view', ['foo' => 'bar'], true); // this is not compatiable with routes that have non-scalar action
```

**Comment by dakota** [comment]
I have given some thought to 
> Compact defintion of Articles::view pairs. This is just a sugared version of ['controller' => 'Articles', 'action' => 'view']. It has no option/features for specifying more than the controller/action.

The sugared version should allow the specifying of plugin/prefix pairs working nearly exactly the same as the syntax for view cells (and models, etc.). The following would all be valid shortforms:

* `Articles::view` -> `['controller' => 'Articles', 'action' => 'view']`
* `Admin\Articles::view` -> `['controller' => 'Articles', 'action' => 'view', 'prefix' => 'Admin']`
* `Blog.Articles::view` -> `['controller' => 'Articles', 'action' => 'view', 'plugin' => 'Blog']`
* `Blog.Admin\Articles::view` -> `['controller' => 'Articles', 'action' => 'view', 'plugin' => 'Blog', 'prefix' => 'Admin']`

No other form or syntax should be used here, it is simply a shorthand form based on the same short class name syntax that has been in use across the board in CakePHP forever. I am wondering if the router should use the shortform (if the user has used it) as a default route name. Scopes (including prefixed and plugin scopes) work as currently, where they take precedence and routes cannot override them.

Creating a complex route (For example extensions, methods, etc.) would either require the full array format, or use the new fluent interface. e.g.

```php
Router::scope('/', function ($routes) {
    //Create a route to the view action in the Articles controller in the Blog plugin for json GET requests only.
    $routes->connect('/articles/:id', 'Blog.Articles::view')
            ->setMethods(['GET'])
            ->setExtension('json'); //URI would be /articles/1.json
}
```

The following should also work:

```php
Router::plugin('Blog', ['path' => '/blog'], function ($routes) {
    $routes->connect('/articles/:id', 'Blog.Articles::view')
            ->setMethods(['GET'])
            ->setExtension('json'); //URI would be /blog/articles/1.json
}
```

But, this will error:

```php
Router::plugin('Blog', function ($routes) {
    $routes->connect('/articles/:id', 'Articles::view') //Not a Blog plugin controller
            ->setMethods(['GET'])
            ->setExtension('json');
}
```

Regarding generating of links, you could simply do:

`$this->Html->link('Click me', ['_name' => 'Blog.Articles::view', $id]);`

**Comment by markstory** [comment]
Going to close this as #11688 finishes off the planned improvements for 3.6.
