### ISSUE TITLE
Translatorlocator not found

### ISSUE THREAD

**Issue by jns4u** [cakephp/cakephp#10688]
* CakePHP Version: 3.2
* Platform and Target: apache 2.4.23, MySQL, php7

I have create an API server using cakephp using above mentioned configuration and api data is being utilized by an angular app. Project was running without any flaw on development machine. Now i changed my machine and configured project thereafter app start getting crashed with following errors

Fatal error: Class 'Aura\Intl\TranslatorLocator' not found in <root>\api\vendor\cakephp\cakephp\src\I18n\TranslatorRegistry.php on line 27

Fatal error: Uncaught Error: Class 'Cake\I18n\TranslatorRegistry' not found in <root>\api\vendor\cakephp\cakephp\src\I18n\I18n.php on line 64

Error: Class 'Cake\I18n\TranslatorRegistry' not found in <root>\api\vendor\cakephp\cakephp\src\I18n\I18n.php on line 64

I already tried some solutions like removing cache using cake executable on local machine and followed installation and configuration instruction but issue still persist. Please Review!

**Comment by markstory** [comment]
Without a way to reproduce this, we can't help you. Have you made sure you've installed all of your composer dependencies on your production machine? Perhaps try removing `/vendor` entirely and re-installing.
