### ISSUE TITLE
3.4.6 Update form 403 Forbidden

### ISSUE THREAD

**Issue by chris-andre** [cakephp/cakephp#10696]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6.
* Platform and Target: Production server: Linux (cPanel), Mysql 5.6.35, PHP 5.6
### What you did
I have an edit form to update database records. 
`echo $this->Form->create($entity)`
The form uses form-helper to add inputs and ends the form.

### Description
The form submits. 

On my dev. server (cakebox, VB), the form works as expected (edited data is being saved), but it does not work on production server, and the headers shows a 403 Forbidden error (Google Chrome network tool)

But, if I use `$this->Form->create($entity, ['type' => 'post'])` it also works on the production server. `put` does not work.

Here is a copy from google chrome network tool when the update/edit form _does not_ have `'type' => 'post'`: https://gist.github.com/chris-andre/b0ddb0e290d582f7fd111016e4b9383a#file-network_analysis-txt

Here is a copy from google chrome network tool when the update/edit form has `'type' => 'post'`: 
https://gist.github.com/chris-andre/b0ddb0e290d582f7fd111016e4b9383a#file-network_analysis2-txt

**Comment by markstory** [comment]
What is different on you production and dev environments. Given that the code works on one server and not the other, you should figure out what is different between them and work backwards from there. Right now this doesn't sound like a CakePHP issue.
