### ISSUE TITLE
Query builder "contain" not working with belongsToMany association

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10693]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5

So I have following mapping:
```

        $this->belongsToMany('X', [
            'foreignKey' => 'somefk_id',
            'targetForeignKey' => 'x_id',
            'joinTable' => 'jointable_name'
        ]);

        $this->belongsTo('Y', [
            'foreignKey' => 'y_id',
            'joinType' => 'INNER'
        ]);

```
And following query builder invocation:

```
 return $query->select("id")->contain([
                "X" => function (Query $q) use ($options) {
                    return $q->where(["X.id" => $options['xId']);
                },
                "Y.Z" => function (Query $q) use ($options) {
                    return $q->where(["Z.name" => $options['zName']]);
                }

            ]
        )
```

This produces SQL with proper joins to Y and Z but does not create joins to X at all. 
Am I missing something? 

If I change X to Xwhatever, exception will be thrown that root is not associated with Xwhatever.

PS - looks like `matching` will create proper joins in query. Is that intented ?

**Comment by markstory** [comment]
You have to use matching() contain() with conditions will modify the X records that are loaded but not restrict the parent model. This is why both matching and contain exist.

**Comment by Antoniossss** [comment]
@markstory Great, thanks for the explanation.
