### ISSUE TITLE
Separate runtime and configuration state in EagerLoader

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10702]
The EagerLoader current mixes runtime state and configuration state which results in hard to fix issues when a query has rows fetched, and then a count generated. An example usage that demonstrates this problem is:

```php
$query ->matching('Tags', function ($q) {
    return $q->matching('Authors', function ($q) {
        return $q->where(['Authors.name' => 'larry']);
    });
});
```

The nested `matching()` calls result in the `queryBuilder` for `Tags` being modified and decorated with the `Authors` query builder callback. By having state separated, chained query builders should only exist in the 'runtime' data of `EagerLoader` which is reset before a query is executed.

Related to #10697 #10699

**Comment by inoas** [comment]
> Closing as I have a temporary fix posted for Pagination, but calling all() and then count() will still break in other use cases, so #10702 has been opened to track the underlying issues in EagerLoader

Isn't this a bug?
If not, is it fixable by just running `$newQuery = clone $query;`?
If so, should I add that to the docs about executing queries?

**Comment by markstory** [comment]
> Isn't this a bug?

Maybe. But not many people will hit it.

>  If not, is it fixable by just running $newQuery = clone $query;?

Yes. But that is a cludge in my opinion.

>  If so, should I add that to the docs about executing queries?

I don't think it needs to be in the documentation personally. It is a very situational solution.
