### ISSUE TITLE
RFC - Console CommandRunner to integrate Application into CLI contexts

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#10716]
The `Application` class added in 3.3 is not currently used in the CLI context. This will prevent `Application` from being the canonical way to bootstrap an application, load configuration, define routing and more. To remedy this the Console entry point needs to start using `Application`.

We have also had a number of requests to allow console 'routing' and allow creating standalone CLI tools more easily.

## Application::console hook

By adding a hook method to `Application` we can enable applications to declare their CLI commands or continue using the auto-discovery we have today. The `Application::console()` hook would be called after bootstrapping is complete, and is passed a `CommandCollection` that allows commands to be added and aliases to be set

```php
// In App\Application.

public function console(CommandCollection $collection)
{
   $collection->add('bake', BakeShell::class);
   $collection->add('asset_compress' AssetCompressShell::class);

   // Auto-discover commands in the app/plugin (current behavior)
   $collection->autoDiscover();

   return $collection;
}
```

In addition to the hook method a `Console.buildCommands` event would be emitted to enable plugins to register commands through the global event listener. This mirrors the `Server.buildMiddleware` event for the HTTP server.

Each added command defines its option parser and sub-commands as they do today. The additional console hook lets users define the commands they want loaded, with short aliases, and load commands from plugins. It also makes it easier to split the console libraries into a standalone library.

The `CommandCollection` class would provide the following methods:

- `addCommand($name, $command)` Add a command to the collection.
- `removeCommand($name)` Remove a command.
- `hasCommand($name)` Check if a command has been set.
- `autoDiscover()` Search the application, and plugins for commands.
- IteratorInterface for iterating attached commands.
- Other methods?

The `CommandCollection` will be initialized with two commands. `help/-h/--help` and `-v/--version` will map to commands that provide their current behavior. Users will be able to replace/remove these commands if they wish.

## Deprecate and replace ShellDispatcher

`ShellDispatcher` is the current entry point into the console environment. To preserve full backwards compatibility, `ShellDispatcher` would be left unchanged. A new class `Cake\Console\CommandRunner` would be added. This new class would be responsible for:

1. Accepting an `Application` instance and `$argv`.
2. Use `Application::bootstrap()` to bootstrap the application
3. Use `Application::routes()` to load the HTTP routing so URL generation works.
4. Use `Application::console()`` to load the console routing.
5. Use the created CommandCollection to dispatch the CLI command.

A sketch of the new CLI entrypoint is:

```php
#!/usr/bin/php -q
<?php
// Check PHP version from composer.json, or default value.
$minVersion = '5.6.0';
if (file_exists('composer.json')) {
    $composer = json_decode(file_get_contents('composer.json'));
    if (isset($composer->require->php)) {
        $minVersion = preg_replace('/([^0-9\.])/', '', $composer->require->php);
    }
}
if (version_compare(phpversion(), $minVersion, '<')) {
    fwrite(STDERR, sprintf("Minimum PHP version: %s. You are using: %s.\n", $minVersion, phpversion()));
    exit(-1);
}

require dirname(__DIR__) . '/vendor/autoload.php';

use App\Application;
use Cake\Console\CommandRunner;

// Build the runner with an application and root executable name.
$runner = new CommandRunner(new Application(dirname(__DIR__) . '/config', 'cake');
exit($runner->run($argv));
```

## Rename Shell to Command

To better fit the conventional names used across other frameworks and libraries, `Cake\Console\Shell` should be renamed to `Cake\Console\Command`.

## Backwards Compatibility for upgrading applications

By leaving `ShellDispatcher` alone, we ensure backwards compatibility. Upgrading applications would replace `bin/cake.php` with a new file from the skeleton, and implement the `console()` hook in their Application if the default auto-discovery was not sufficient.

**Comment by jeremyharris** [comment]
After this change I would love to see the console get its own package. Might be a good opportunity to split it up.

**Comment by robertpustulka** [comment]
What about deprecating `Cake\Console\Shell` and creating some "better" implementation for `Cake\Console\Command`? 
Argument/parameter accessors need some rework. Currently there's no way to access an argument by name AFAIR, only by `$this->args[$index]`. Tasks could be refactored into something more like decorators in component/behavior fashion.  Maybe subcommands could be refactored to use `CommandCollection` internally by commands instead of options parser (which should do what the name implies - parse options and arguments).

**Comment by markstory** [comment]
@robertpustulka Creating commands as a separate thing might work out better. We would still need to support shells and commands, but at least the new implementation could start without the public property baggage we currently have.

**Comment by HavokInspiration** [comment]
This is looking very good @markstory.
I agree with @jeremyharris about splitting it into its own package. 
I also agree with @robertpustulka on all of its comments. Tasks are very confusing in my opinion. Are they considered as sub-commands ? Are they considered like components  for shell ? Their role is not very clear.

Having `Commands` class would be a lot clearer.

And I’d also remove the fact that public methods in `Shell` classes (well, `Commands` following this RFC) can be used as subcommands. That is also confusing, because there’s also Tasks to do that.

I’m all in favor of having only one way to do something. Having one way of doing things is easier to document, maintain and understand for new comers. 

Want to create a subcommand ? 

```php
$collection->add('bake model’, BakeModelCommand::class);
$collection->add('bake controller’, BakeControllerCommand::class);
```

Clear, simple, easier to understand.

You don’t have subcommands ? We do that to :

```php
$collection->add(’dosomething’, DoSomethingCommand::class);
```

And if you have things in common to multiple `Commands` (I'm thinking about possible arguments or options such as connection name), either leverage class inheritance or traits.

**Comment by markstory** [comment]
> Tasks are very confusing in my opinion. Are they considered as sub-commands ? Are they considered like components for shell ? Their role is not very clear.

Yes they are a bit of a mutant. I agree that making commands single function makes commands simpler. I think we need to figure out how to provide good patterns for code reuse. I don't like pushing people to use inheritance. Something like 'tasks' that aren't tasks could work well.

For now I'm going to push ahead with the CommandCollection and CommandRunner. Once those are in place we might better understand how to approach the re-usable bits of commands.

**Comment by HavokInspiration** [comment]
> I agree that making commands single function makes commands simpler

@markstory You meant "making commands single class" ? 😄
I'm all in about removing the "one function = one command". A command is, in my opinion, a too complex things to be expressed only as a single function.

> I don't like pushing people to use inheritance

Is there any particular reason about that ? You fear it can add complexity or difficulty to explain / document ? I can agree that this would not seem very "user friendly".
I was just throwing some ideas in. Having a `Command` register `SubCommand` and passing in instance of an `OptionsParser` while doing it could be another solution.

> For now I'm going to push ahead with the CommandCollection and CommandRunner. Once those are in place we might better understand how to approach the re-usable bits of commands.

Step by step sounds like a good plan 👍

**Comment by robertpustulka** [comment]
I think having life cycle events and decorators for commands would be enough to easily share code and dependencies across commands.

**Comment by markstory** [comment]
Given that the Command class has been moved to 3.6 I'm going to close this. I'll open another issue for the Command class change when 3.6 starts.
