### ISSUE TITLE
Response withType not overriding content type

### ISSUE THREAD

**Issue by chrisShick** [cakephp/cakephp#10713]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.x
* Platform and Target: Centos7 

### What you did
I set the xml response inside the controller with content type of 'text/xml' but application/xml is being returned.

     $this->response = $this->response->withType('text/xml'); 

### What happened
It returns application/xml

### What you expected to happen
It should return text/xml

**Comment by JoshuaLuckers** [comment]
The function withType will map the given content type to a mime-type or concrete mime-type.

The MIME type for XML is "application/xml".

I think calling `$this->response->type(['xml' => 'text/plain']);` before using withType() will solve your issue.

**Comment by chrisShick** [comment]
@JoshuaLuckers I actually did that as well and it did not work.

**Comment by chrisShick** [comment]
There was a typo when I did `$this->response->type(['xml' => 'text/xml']);` It works as expected when doing that.
