### ISSUE TITLE
Security.cipherSeed is rounded to PHP_INT_MAX in 2.8 and existing cookies are broken

### ISSUE THREAD

**Issue by ikuwow** [cakephp/cakephp#10724]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.x
  * after this commit: https://github.com/cakephp/cakephp/commit/6a68032e0b6d6115e0c47ee5615a8ba82245561d
* Platform and Target: php5.6.30, apache 2.4

### What you did
I updated cakephp 2.7 to 2.8.

### What happened
All cookies broke (which already exists on client browsers)

### What you expected to happen

Security.cipherSeed is explicitly cast as int (for removing warning in php7):
https://github.com/cakephp/cakephp/commit/6a68032e0b6d6115e0c47ee5615a8ba82245561d

cipherSheed seems to be assumed to be larger than PHP_INT_MAX:
https://github.com/cakephp/cakephp/blob/2.x/app/Config/core.php#L240
（My project also uses large cipherSeed like this）

So after this change all cookies that is encrypted before by `Security` utility cannot be decoded correctly.

---

How can i update to 2.8 without breaking existing cookies?

**Comment by markstory** [comment]
> How can i update to 2.8 without breaking existing cookies?

Sounds like you can't because your seed was too big.

**Comment by ikuwow** [comment]
Oh... I see. Thank you for replying.

I think the TODOs are:

* Change Security.cipherSeed samples to a valid integer
  * in documents
  * in tests
  * in app skeleton (/app/Config/core.php)
* Add warnings of this problem in 2.8 migration guide

**Comment by markstory** [comment]
@ikuwow Any chance you'd be willing to help with those tasks?

**Comment by ikuwow** [comment]
@markstory Ok, i'll do these in a few days or a week 👍

**Comment by ikuwow** [comment]
I found a workaround. It seems strange but it works. #10749

**Comment by markstory** [comment]
Great work @ikuwow. Closing this as there is a pull request now.
