### ISSUE TITLE
Raise exception when there are migrations yet to be run

### ISSUE THREAD

**Issue by aaronstillwell** [cakephp/cakephp#10727]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: -

### What you did
Developing with co-worker, co-worker creates a migration, commits, I pull changes, forget to migrate / don't realise a migration has been added.

### What happened
Hitting errors as the development schema is not up to date. A small but noteworthy productivity hit.

### What you expected to happen
If CakePHP were to raise an exception when running in development mode, this situation would be mostly avoided.

I'll be happy to personally file a PR for this feature. Happy to hear thoughts on whether this would be a wanted / desirable feature by other Cake developers.

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#317
