### ISSUE TITLE
3.4.7 cannot use any getter inside Mailer

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#10721]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7

### What you did
i cannot use any getter inside Mailer
i.e
```php
class OrdersMailer extends Mailer
{
    public function try_me(): void
    {
        $this
            ->setTo($this->getSender());
    }
}
```
throws error:
```
Warning Error: preg_match() expects parameter 2 to be string, object given in [/home/vagrant/Apps/app/vendor/cakephp/cakephp/src/Mailer/Email.php, line 919]
```

### What happened
every getter returns Mailer object instead of data caused by:
https://github.com/cakephp/cakephp/blob/ff5b828b03965483bc69fcde300b502d6aaa9887/src/Mailer/Mailer.php#L250-L255

### What you expected to happen
return needed data

ive changed function to:
```php
public function __call($method, $args)
    {
        $result = $this->_email->$method(...$args);

        if (preg_match('/^get/', $method) > 0) {
            return $result;
        }

        return $this;
    }
```

**Comment by cleptric** [comment]
Couldn't you just use `$this->_email->getSender()` ?

**Comment by Graziel** [comment]
docBlocks exposes getters (ie.  @method array getSender()) as part of Mailer class so yeah i could but still something is not right : )

**Comment by cleptric** [comment]
Ok, got it. This annotations were added recently.
I'm not sure how to fix this in the most elegant way, though.
Your fix could work, as long as we stick with the `get` prefix on every getter in this class.
For example, `Email::message()` is also a getter.
Let's see what others thing about this.

**Comment by markstory** [comment]
Closing as a pull request is open now.
