### ISSUE TITLE
Table::get with contains array, does not load hasMany associated entities

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10722]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cakephp/cakephp                       3.4.5
* Platform and Target: Windows and MySQL

I feel like I keep reporting the same issue but in different context over and over again :)

So I have AuditsTable with given association 
```
        $this->hasMany('AuditDeltas', [
            'foreignKey' => 'audit_id',
        ]);
```
Now I want to fetch audit by id with deltas
```
$audit = $this->Audits->get($auditId,["AuditDeltas"]); //this does not fetch deltas
$this->Audits->loadInto($audit,["AuditDeltas"]); // this is required
```

extra `loadInto` is required as plain get will not generate JOINS for related AuditDeltas. As long as I can understand difference between `contains` and `matching` I don't understand why shouldnt simple `get` work in this case. Loading other types associations works fine (at least didn't noticed any troubles) and they are fetched along with root entity.

**Comment by cleptric** [comment]
Aren't you missing the 'contain' key in your options array?

```
$audit = $this->Audits->get($auditId, 'contain' => [
    'AuditDeltas'
]);
```

**Comment by ADmad** [comment]
As @cleptric pointed out your 1st usage is incorrect.
