### ISSUE TITLE
translate behaviour doesn't seem to patch translations on edit

### ISSUE THREAD

**Issue by danielzzz** [cakephp/cakephp#10747]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: ubuntu 16.04

### What you did

I created form fields using as follows:
`_translations.en_GB.name`
etc..
according to the docs here:
https://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations

### What happened
when I use
```php
$entity = $this->ModelTable->find('translations')->where(['id'=>'1]->first();

$this->ModelTable->patchEntity($entity, $this->request->getData(), ['translations'=>true]);
```

translated fields are not patched even though the data from the form seems to be correct.

### What you expected to happen
I would expect translated fields to be patched as well

**Comment by markstory** [comment]
What does the data you're patching look like? Also what does the entity you're changing look like? I'd like to know more so I can attempt to reproduce this issue.

**Comment by danielzzz** [comment]
hi, 
It's something like this

```
[
  
  '_translations' => [
    'de_DE' => [
      'title' => 'german title',
    ]
  ],
  'title' => 'Cursos',
  
]
```
only the "main" title changes after patchEntity, the translation stays as it was.
but if I use 
```
$entity->translation('de_DE')->title = "german title"
```
it does work.

**Comment by danielzzz** [comment]
I am not if this should be supported or not, but if I have a related model with multilingual data it doesn't get patched either.
```
[
  
  '_translations' => [
    'de_DE' => [
      'title' => 'german title',
    ]
  ],
  'title' => 'Cursos',
  'some_other_model' => [
  
     '_translations' => [
        'de_DE' => [
          'name' => 'german name',
        ]
     ],
      'name' => 'spanish name',
  
    ]
]
```

**Comment by markstory** [comment]
Yes that should work as well. Does your entity have `_translations` set as an accessible property?

**Comment by danielzzz** [comment]
yes,
in fact I have 
```
'*' => true,
'id' => false,
```
but I have also explicitly set "_translations" and "some_other_model" as true

**Comment by markstory** [comment]
Hrm. Then I'm not sure what is going on then. We have [existing tests](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php#L1427-L1461) covering this scenario. The following test is also passing for me locally:

```php
public function testPatchMultipleTranslations()
{
    $table = TableRegistry::get('Articles');
    $table->addBehavior('Translate', ['fields' => ['title', 'body']]);
    $table->entityClass(__NAMESPACE__ . '\Article');

    $data = [
        'author_id' => 1,
        '_translations' => [
            'de_DE' => [
                'title' => 'DE Title',
                'body' => 'DE Body'
            ],
            'es_ES' => [
                'title' => 'ES title',
                'body' => 'ES body'
            ]
        ]
    ];

    $article = $table->find()->first();
    $article = $table->patchEntity($article, $data);
    $this->assertTrue($article->isDirty('_translations'));
    $this->assertSame('ES title', $article->_translations['es_ES']['title']);
}
```

**Comment by danielzzz** [comment]
ok, I'll try to do more tests to find what's the problem in my case. thanks

**Comment by markstory** [comment]
Any updates on this?

**Comment by markstory** [comment]
Closing until we have a way to reproduce this issue.
