### ISSUE TITLE
Why CakePHP is not allowing to create MySQL table names without plural ?

### ISSUE THREAD

**Issue by raghavshekar** [cakephp/cakephp#10740]
Putting  "_ underscore" is old school.  Why CakePHP is using it till now.  And also why CakePHP is not allowing to create MySQL table names without plural. Is this mandatory ?

**Comment by lorenzo** [comment]
You can name your tables anyway you want. That includes using singular table names and not using underscores.

The only downside of using your custom naming, is that you don't leverage the defaults built in Cake. That is not the end of the world, though. It is super simple to configure your table classes to use your custom names.

As an anecdote, I used cake a long time ago on a legacy database having names like `cef01``cef02`... Those table were mapped to more interesting names like `Users` and `Courses`, thanks to cake awesome configuration methods!

**Comment by inoas** [comment]
These are two complaints at once... and I think one is really minor while the other is not, IMHO.

1. The IMHO important thing: I would love to see no singular/plural conversion anywhere. If it is belongsTo/hasOne or hasMany, if it is tables or fields. If it is foreign keys... just go with a simple mapping. If the table is named "foo" the foreign key is "foo_id", if it is "foos", the foreign key is "foos_id". This is what I really hope 4.x will allow with a NullInflector. It could be introduced in 4.x and made default in 5.x. It will take away a lot of pain IMHO.

2. The IMHO unimportant: The PSR thing with underscores is really a nitpicking. It does not interfere with your day to day work. Personally I LOVE it as the visibility is very clear. However I could again live without the underscores.
