### ISSUE TITLE
Exception: Shell class for "WalletManager.Coin" could not be found.

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#10745]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.4.7
* Platform and Target: LAMP

### What you did

    └──╼ bin/cake bake shell coin --plugin WalletManager
    Welcome to CakePHP v3.4.7 Console
    ---------------------------------------------------------------
    App : src
    Path: /Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/src/
    PHP : 5.6.30
    ---------------------------------------------------------------
    Creating file /Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/src/Shell/CoinShell.php
    Wrote `/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/src/Shell/CoinShell.php`
    Bake.Test
    Baking test case for WalletManager\Shell\CoinShell ...
    Creating file /Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/tests/TestCase/Shell/CoinShellTest.php
    Wrote `/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/tests/TestCase/Shell/CoinShellTest.php`

### What happened
    └──╼ bin/cake coin --plugin WalletManager
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 327]
    └──╼ bin/cake coin
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 327]

### What you expected to happen

    CoinShell::main();

**Comment by jeffreyroberts** [comment]
I think this has something to do with the auto-loader, I tried the following with a couple of variants for CoinShell but only got PHP Fatal not found

        public function findShell($shell)
        {
            if($shell == 'coin') {
                 return $this->_createShell('CoinShell', 'coin');
            }
     ....

**Comment by jeffreyroberts** [comment]
and tried

    if($shell == 'coin') {
            return $this->_createShell('CoinShell', 'WalletManager.CoinShell');
    }

**Comment by markstory** [comment]
Is your plugin loaded? You can get a list of plugins/shells CakePHP knows about by using `bin/cake --help`. If your shell is not in that list it will not be callable.

**Comment by jeffreyroberts** [comment]
Ya, the plugin is loaded in bootstrap and bootstrap_cli

the funny part here is that it is finding it, or else how did it know WalletManager?

**Comment by jeffreyroberts** [comment]
└──╼ bin/cake --help

    Welcome to CakePHP v3.4.7 Console
    ---------------------------------------------------------------
    App : src
    Path: /Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/src/
    PHP : 5.6.30
    ---------------------------------------------------------------
    ...

    Available Shells:

    [Bake] bake

    [DebugKit] benchmark, whitespace

    [Migrations] migrations

    [WalletManager] coin

    ...

**Comment by markstory** [comment]
Are you able to call shells inside debug kit? If so double check that your generated shell has the right class name / namepsace. There could have been an issue with bake.

**Comment by HavokInspiration** [comment]
Could it be an issue with the auto-loader ? Like `composer` does not know how to load the class ?

Do you have a `WalletManager` namespace referenced in the `autoload` section of your composer.json file ? If yes, have tried to `composer dump-autoload` and run the shell again to see if it fixes the issue ?

**Comment by jeffreyroberts** [comment]
im not sure how to use a shell from the debugkit at this time, i tried looking it up, but no avail... my first thought was it was an autoloader issue... I havent added anything for the autoloader to find the plugin... I see that the bake shell --plugin command has generated a composer.json file... let me know how do I add the namespace and ill do a pull request, adding it to the bake process

**Comment by jeffreyroberts** [comment]
check this out, if I enable the bootstrap

    Plugin::load('WalletManager', ['bootstrap' => true, 'routes' => true]);

 I get include errors....

    └──╼ bin/cake coin
    Warning Error: include(/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/config/bootstrap.php): failed to open stream: No such file or directory in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Core/Plugin.php, line 400]
    
    Warning Error: include(): Failed opening '/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/plugins/WalletManager/config/bootstrap.php' for inclusion (include_path='.:/usr/share/pear') in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Core/Plugin.php, line 400]
    
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 328]

so it knows where to find the bootstrap, i dunno, i walked the code man, at some point the variable contents just change from line to line for me, dunno wtf thats about, maybe its just xdebug, but it literally goes from coin to WalletManager.Coin in the $shell or $class_name variable, i forget now exactly, but the point is, i think its running twice through different paths, im not sure exactly...

this is all from a fresh clone of cakephp/cakephp, cakephp/app, first thing i did was baked the plugin WalletManager, and then baked the first shell for WalletManager...

**Comment by jeffreyroberts** [comment]
is this how I add it?

    "autoload": {
        "psr-4": {
            "App\\": "src",
            "WalletManager\\": "src"
        }
    },

im going to attempt to debug this again

**Comment by jeffreyroberts** [comment]
Error: Line 328, ShellDispatcher.php

Lines 308-334

    /**
     * Get shell to use, either plugin shell or application shell
     *
     * All paths in the loaded shell paths are searched, handles alias
     * dereferencing
     *
     * @param string $shell Optionally the name of a plugin
     * @return \Cake\Console\Shell A shell instance.
     * @throws \Cake\Console\Exception\MissingShellException when errors are encountered.
     */
    public function findShell($shell)
    {
        $className = $this->_shellExists($shell);

        if (!$className || $className == '') {
            $shell = $this->_handleAlias($shell);
            $className = $this->_shellExists($shell);
        }

        if (!$className) { // Line 327
            throw new MissingShellException([
                'class' => $shell,
            ]);
        }

        return $this->_createShell($className, $shell);
    }

**Comment by jeffreyroberts** [comment]
Here is the same function with debug logging

    public function findShell($shell)
    {
        $className = $this->_shellExists($shell);
    echo "className: " . $className . "\n";
    echo "shell: " . $shell . "\n";

        if (!$className || $className == '') {
            $shell = $this->_handleAlias($shell);
            $className = $this->_shellExists($shell);

    echo "className 2: " . $className . "\n";
    echo "shell 2: " . $shell . "\n";
        }

        if (!$className) {
    echo "className 3: " . $className . "\n";
            throw new MissingShellException([
                'class' => $shell,
            ]);
        }

        return $this->_createShell($className, $shell);
    }

and the output

    └──╼ bin/cake coin
    className:
    shell: coin
    className 2:
    shell 2: WalletManager.Coin
    className 3:
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 334]

it looks like the problem lies within _shellExists

    protected function _shellExists($shell)
    {
        $class = App::className($shell, 'Shell', 'Shell');
        if (class_exists($class)) {
            return $class;
        }

        return false;
    }

which looks like an auto-loader issue?

**Comment by jeffreyroberts** [comment]
from what I understand how auto loaders work, when the function class_exists is executed, if the class does not exist, the auto loader will load it at that time if it can, but i might be wrong about that, here is some more debug code

_shellExists

    protected function _shellExists($shell)
    {
        $class = App::className($shell, 'Shell', 'Shell');

    echo "appClassName: " . $class . "\n";
    echo "appShellName: " . $shell . "\n"; 
        if (class_exists($class)) {
            return $class;
        }

        return false;
    }

and the output now looks like

    └──╼ bin/cake coin
    appClassName:
    appShellName: coin
    className:
    shell: coin
    appClassName:
    appShellName: WalletManager.Coin
    className 2:
    shell 2: WalletManager.Coin
    className 3:
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 334]

actually, it looks like App::className is failing to return anything at all, lets take a look there...

    public static function className($class, $type = '', $suffix = '')
    {
        if (strpos($class, '\\') !== false) {
            echo "Returning class: " . $class . "\n";
            return $class;
        }

        list($plugin, $name) = pluginSplit($class);
        $base = $plugin ?: Configure::read('App.namespace');
        $base = str_replace('/', '\\', rtrim($base, '\\'));
        $fullname = '\\' . str_replace('/', '\\', $type . '\\' . $name) . $suffix;

        if (static::_classExistsInBase($fullname, $base)) {
            echo "Returning base and fullname: " . $base . $fullname . "\n";
            return $base . $fullname;
        }
        if ($plugin) {
            echo "Returning false\n";
            return false;
        }
        if (static::_classExistsInBase($fullname, 'Cake')) {
            echo "Returning Cake fullname" . $fullname . "\n";
            return 'Cake' . $fullname;
        }

        return false;
    }

now the output looks like this ...

    └──╼ bin/cake coin
    appClassName:
    appShellName: coin
    className:
    shell: coin
    Returning false
    appClassName:
    appShellName: WalletManager.Coin
    className 2:
    shell 2: WalletManager.Coin
    className 3:
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 334]
    Returning class: Cake\Log\Engine\FileLog
    Returning class: Cake\Log\Engine\FileLog

so that means its returning false because $plugin is 'WalletManager'

        if ($plugin) {
            echo "Returning false\n";
            return false;
        }

it seems to me that it needs to return something other than false, im thinking, $base . $fullname

output with return base . fullname on if plugin

    └──╼ bin/cake coin
    appClassName:
    appShellName: coin
    className:
    shell: coin
    Returning false, plugin: WalletManager\Shell\CoinShell
    appClassName: WalletManager\Shell\CoinShell
    appShellName: WalletManager.Coin
    className 2:
    shell 2: WalletManager.Coin
    className 3:
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 334]
    Returning class: Cake\Log\Engine\FileLog
    Returning class: Cake\Log\Engine\FileLog

we have an appClassName, but no className 2 or 3, because _shellExists is still returning false because the class_exists function is returning false, im guessing this is an autoloader issue, i tried

    $cs = new $class();

however that resulted in a fatal php error

**Comment by jeffreyroberts** [comment]
@HavokInspiration I tried 

    └──╼ composer dump-autoload
    Generating autoload files
    > Cake\Composer\Installer\PluginInstaller::postAutoloadDump
    
    └──╼ bin/cake coin
    appClassName:
    appShellName: coin
    className:
    shell: coin
    Returning false, plugin: WalletManager\Shell\CoinShell
    appClassName: WalletManager\Shell\CoinShell
    appShellName: WalletManager.Coin
    className 2:
    shell 2: WalletManager.Coin
    className 3:
    Exception: Shell class for "WalletManager.Coin" could not be found. in [/Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 334]
    Returning class: Cake\Log\Engine\FileLog
    Returning class: Cake\Log\Engine\FileLog


not sure if that helps =[

**Comment by jeffreyroberts** [comment]
hrmm, i think i might have gotten it that time, i guess I didnt run dump-autoload proper or something, i just tried it all again and BINGO

    └──╼ bin/cake coin
    appClassName:
    appShellName: coin
    className:
    shell: coin
    Returning base and fullname: WalletManager\Shell\CoinShell
    appClassName: WalletManager\Shell\CoinShell
    appShellName: WalletManager.Coin
    className 2: WalletManager\Shell\CoinShell
    shell 2: WalletManager.Coin
    
    Welcome to CakePHP v3.4.7 Console
    ---------------------------------------------------------------
    App : src
    Path: /Users/jlroberts/Projects/AltCoinWallet.Solutions/CakeCoin/src/
    PHP : 5.6.30
    ---------------------------------------------------------------
    Usage:
    cake wallet_manager.coin [-h] [-q] [-v]
    
    Options:
    
    --help, -h     Display this help.
    --quiet, -q    Enable quiet output.
    --verbose, -v  Enable verbose output.

**Comment by jeffreyroberts** [comment]
so it was def an auto-loader issue, that change i made to what the plugin returns doesn't matter either way now... 

Thank you so much guys, now, how do we feel about adding composer.json edits to the bake function, sorta sucks to have to add that to the autoloader manually with all this automagical greatness around =]

**Comment by jeffreyroberts** [comment]
would be even slicker if we didnt have to add it to the autoloader at all

**Comment by markstory** [comment]
Bake does [attempt to update the autoloader](https://github.com/cakephp/bake/blob/master/src/Shell/Task/PluginTask.php#L225-L273) but it can fail for a variety of reasons.

Closing as this was an autoloader related issue that has now been resolved.
