### ISSUE TITLE
Cannot insert zero using Fixture for testing

### ISSUE THREAD

**Issue by dangerdan** [cakephp/cakephp#10765]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: nginx, mariadb

### What you did
I'm using a fixture to insert values into a status table that has an id and label column. This is failing due to the primary index on id, even though the values are all different.

It appears to be the '0' for pending that is causing the issue:

    public $fields = [
        'id' => ['type' => 'integer', 'autoIncrement' => false, 'length' => 11, 'unsigned' => false,'signed' => true, 'null' => false, 'default' => null, 'comment' => '', 'precision' => 10],
        'label' => ['type' => 'string', 'length' => 15, 'null' => true, 'default' => '', 'comment' => '', 'precision' => null, 'fixed' => null],
        '_constraints' => [
           'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
        ]
    ];
    
    public $records = [
        [
            'id' => -1,
            'label' => 'Cancelled'
        ],
        [
            'id' => 0,
            'label' => 'Pending'
        ],
        [
            'id' => 1,
            'label' => 'Confirmed'
        ]
    ];

### What happened

Exception: Unable to insert fixture "App\Test\Fixture\StatusesFixture" in "App\Test\TestCase\Controller\BusinessControllerTest" test case: 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' in [/application/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 337]

### What you expected to happen

The test table should be created with a '0' as the id for the Pending status.

**Comment by jeremyharris** [comment]
According to the error, it's the third fixture that's the problem. You use 1 again as an id.

**Comment by markstory** [comment]
I will see if I can reproduce this on my side.

**Comment by markstory** [comment]
Looks like this is caused by Cake generating the incorrect schema based on the fixture data. The schema I'm getting locally is:

```sql
CREATE TABLE `statuses` (
`id` INTEGER(11) NOT NULL AUTO_INCREMENT,
`label` VARCHAR(15) DEFAULT '',
PRIMARY KEY (`id`)
)
```

which is not correct as `id` should not be `autoincrement`. This sounds very similar to #10045 which is also about fixtures forcing auto increment on tables in MySQL.
