### ISSUE TITLE
Ability to see SQL generated statement with parameters substituted

### ISSUE THREAD

**Issue by brettl** [cakephp/cakephp#10761]
* [x] enhancement

* CakePHP Version: 3.next
When running the ->sql() function on an ORM call allow the ability to see the sql statement with the parameters in the place holders.

Currently when calling sql on the ORM you will see example "where id = :c1"
allow the ability to call an example ->sql(1) or ->sql()->substituted(); and the resulting sql will now be "where id = 1"
this would allow the ability to take your sql being generated and run in a sql viewer /editor and run your command and possibly see if you are producing the incorrect data or if you are generating the incorrectsql statement

**Comment by dereuromark** [comment]
Isn't `(string)...->sql()` casting doing this? Showing you the final SQL query that would be run?

**Comment by markstory** [comment]
@dereuromark Right now there isn't a way to get the SQL query that will be executed with placeholders populated from the database layer. You can only get that information by interpolating the parameters yourself, or using a tool like debug kit.

We won't be able to chain off of `sql()`, but we could have a new method that returns the populated SQL query.

**Comment by makallio85** [comment]
+1 to this

**Comment by lorenzo** [comment]
I'd like to do this for when calling `debug($query)`

**Comment by thinkingmedia** [comment]
Oh I would like to work on this. I have a working example already and just need to migrate it to the debugKit.

Always including the variable bindings is *risky*. For example; some of the IN operators can be huge which makes reading the SQL difficult. So I will make this an optional feature.

**Comment by thinkingmedia** [comment]
This issue was moved to cakephp/debug_kit#568

**Comment by mehov** [comment]
Hi everyone,

I am working on an endpoint that responds with JSON, so I can't use the debug kit on that exact method. (Unless I refactor it to temporarily have a template.)

This method runs an SQL query that I need to look at, but if I call `->sql()` on it, obviously I'm getting the placeholders. According to [`class-Cake.ORM.Query.html#sql()`](https://api.cakephp.org/3.9/class-Cake.ORM.Query.html#sql()) there doesn't seem to be an argument or a flag I could pass to make it return the full query, and I'm curious why is that.

(I did read the above regarding the SQL injections, and maybe I'm missing the point, but either way nothing stops me from taking the `->sql()` output and filling the placeholders with values if I really wanted to harm myself. As in, obtain the raw query that's being hidden from me, and take it elsewhere.)

Here's my case. The query I'm working on doesn't return any data. I want to take the raw SQL, and play with it in MySQL Workbench until I figure out why. Then I would adjust my CakePHP query conditions accordingly.

Every time I run into this situation, I `debug()` my `$query` and manually copy-paste the values into the placeholder'd SQL. I guess there must be reason why the framework won't have an option to output the full SQL it's about to run, but why is that?

**Comment by ndm2** [comment]
Instead of `debug()` you can use `\DebugKit\DebugSql::sql()`, this will replace the placeholders with the bound values, just like it would for Debug Kit's SQL panel.

Also note that Debug Kit will record any kind of request, you can inspect them afterwards on a different endpoint by selecting the corresponding request in the history panel.

**Comment by markstory** [comment]
>  I guess there must be reason why the framework won't have an option to output the full SQL it's about to run, but why is that?

The framework *is* showing the query it is running. The database layers run prepared statements which have parameters and the statement separate which is what is available from the query object.

Yes, you could interpolate the values yourself and run the queries. We include a `debugSql()` function in DebugKit that does the parameter interpolation so you can get a query that could be run in an interactive prompt/database workbench. I don't think that should be something we include in CakePHP core as it does create a SQL injection vector and I don't want to have to deal with it coming up in future security audits.

**Comment by ndm2** [comment]
+1 for the `debugSql()` shorthand.

**Comment by ndm2** [comment]
Wait... there already are shorthands, `sql()` and `sqld()` 🙃

**Comment by markstory** [comment]
> Wait... there already are shorthands, sql() and sqld() upside_down_face

I totally forgot we added those to DebugKit. Going to leave this closed as we have ways to dump SQL out already.
