### ISSUE TITLE
CakeEmail Comma in From address

### ISSUE THREAD

**Issue by vanbe** [cakephp/cakephp#10763]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4
* Platform and Target: CakeEmail -> SMTP Transport

### What you did
I'm trying to send and email with a comma in the from_name.

### What happened
The sent email is malformed. The MIME enveloppe is not well structured because the comma is not escaped.

Received email header excerpt:
```
From: "Website, =?UTF-8?B?c3DDqWNpYWxpc3RlIFZPTyI=?= <test@domain.com>
To: test@domain2.com
X-Mailer: CakePHP Email

```
### What you expected to happen
The header should have an extra " :

`From: "Website, =?UTF-8?B?c3DDqWNpYWxpc3RlIFZPTw==?=" <test@domain.com>
`
Otherwise some email readers / gmail, etc are considering that there are multiple From emails due to the non-escaped character.

**Comment by markstory** [comment]
Thanks for reporting this. I'll see if I can reproduce it.

**Comment by markstory** [comment]
Pull request is up now.
