### ISSUE TITLE
Problem CakePhp 2.9 connecting with Postgres

### ISSUE THREAD

**Issue by gorge2004** [cakephp/cakephp#10776]
i install postgress recently  and i'm working with the release 2.9 in local (Xampp) ,
i did my db configuration  and when i go to localhost/cakephp , show:

Release Notes for CakePHP 2.9.9.
Read the changelog

Your version of PHP is 5.2.8 or higher.

Your tmp directory is writable.

The FileEngine is being used for core caching. To change the config edit APP/Config/core.php

Your database configuration file is present.

CakePHP is able to connect to the database.
DebugKit plugin is present

but  when i use cake bake for creating a new model appears a issue:
C:\xampp\htdocs\cakephp-2\app>cake bake

Welcome to CakePHP v2.9.9 Console
---------------------------------------------------------------
App : app
Path: C:\xampp\htdocs\cakephp-2\app\
---------------------------------------------------------------
Interactive Bake Shell
---------------------------------------------------------------
[D]atabase Configuration
[M]odel
[V]iew
[C]ontroller
[P]roject
[F]ixture
[T]est case
[Q]uit
What would you like to Bake? (D/M/V/C/P/F/T/Q)
> M
---------------------------------------------------------------
Bake Model
Path: C:\xampp\htdocs\cakephp-2\app\Model\
---------------------------------------------------------------
Error: Database connection "Postgres" is missing, or could not be created.
#0 C:\xampp\htdocs\cakephp-2\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#1 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\Task\ModelTask.php(952): ConnectionManager::getDataSource('default')
#2 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\Task\ModelTask.php(889): ModelTask->getAllTables(NULL)
#3 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\Task\ModelTask.php(979): ModelTask->listAll(NULL)
#4 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\Task\ModelTask.php(203): ModelTask->getName()
#5 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\Task\ModelTask.php(91): ModelTask->_interactive()
#6 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Command\BakeShell.php(109): ModelTask->execute()
#7 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\Shell.php(461): BakeShell->main()
#8 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\ShellDispatcher.php(219): Shell->runCommand(NULL, Array)
#9 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 C:\xampp\htdocs\cakephp-2\lib\Cake\Console\cake.php(54): ShellDispatcher::run(Array)
#11 {main}

please help me

**Comment by markstory** [comment]
You likely don't have the postgres PDO extension installed on your CLI PHP executable. Ensure that `php -m` contains postgres. I don't think this is an issue with CakePHP as you are able to connect to postgres from your webserver.

**Comment by gorge2004** [comment]
Ty
