### ISSUE TITLE
RFC: Router scope cache

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#10778]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next
* Platform and Target: 3.next

In projects where several routes are connected, sometimes with routes coming from the database or external files, there is a possible optimization caching the generated RouteCollection.

### Interface

The interface for this cache could be located in the scope params and define the scoped route like

    Router::scope('/', ['_cache' => 'default'], function (RouteBuilder $routes) {...});

The `_cache` param defines the cache configuration to use, and the cache key will be the `path` of the scope.

### Test config and results

This is the configuration I've used for testing performance locally (using default File based cache)

```
$start = microtime(true);
Router::scope('/', ['_cache' => 'default'], function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $range = range(1, 4000);
    foreach ($range as $i) {
        $routes->connect('/pages/' . $i, ['controller' => 'Pages', 'action' => 'display']);
    }
    $routes->fallbacks(DashedRoute::class);
});
$stop = microtime(true);
Cake\Log\Log::debug($stop - $start);
```

**Times with/without cache were: 
0.00463 vs 0.00276 for 50 connected routes
1.45s vs 0.015 for 4000 connected routes**

### Implementation notes:

* We could think of another implementation Router::cache() to define global caching of the RouteCollection (it's static anyway) but I think it's better to let the user define which scopes should be cached.
* If 2 or more scopes are cached, the per scope cache will store previous cached router collection twice as the RouteCollection object is static, this could be a possible improvement in a future PR if this one is looking good.
* This feature is BC with existing 3.x versions

### Todo:

* Add new option to documentation
* Add note about using `bin/cake routes` to build the routes cache as a deploy step

**Comment by davidyell** [comment]
Sounds like a good idea to me. Would this cache be clearable using a shell? Would it respect the configured `Cache.diabled` configuration flag?

**Comment by markstory** [comment]
Closing as there is a pull request open now.

**Comment by steinkel** [comment]
Here's another round on the route-caching topic. I've been testing the middleware based routing cache and this would remove some of the issues with the scope based caching, getting all the routeCollection serialized and reused between requests. The new CacheRoutingMiddleware class would look like this:

```
class CacheRoutingMiddleware extends RoutingMiddleware
{
    protected function loadRoutes()
    {
        if ($this->app && !Router::$initialized) {
            $routeCollection = Cache::remember('routeCollection', function () {
                $builder = Router::createRouteBuilder('/');
                $this->app->routes($builder);

                return Router::getRouteCollection();
            }, 'routes');

            Router::setRouteCollection($routeCollection);
            // Prevent routes from being loaded again
            Router::$initialized = true;
        }
    }
}

```
We would need to add a Router::setRouteCollection setter. 
There could be specific use cases where the cache would not work, like connecting routes based on dynamic conditions. If we want to cover this use case, we could think about 2 methods in `routes.php`, one for cached routes, another for non-cached and we would need to ensure we run the non-cached routes on every request.

Please let me know your thoughts, I can get a PR with these changes over the next days.

The new 'router' cache configuration would be added to skeleton. `Cache.disabled` would be respected, just trying to get details out of the example.

**Comment by markstory** [comment]
@steinkel That looks like a _much_ cleaner and simpler implementation :clap:

**Comment by steinkel** [comment]
Thinking about a new CacheRoutingMiddleware vs using existing RoutingMiddleware and configuration, the second option looks better because we could have an environment based configuration for the route collection caching, working the same as the core and model caches in development mode (2 minutes). I'll work on a PR based on these ideas...

**Comment by markstory** [comment]
Closing as #11765 is open
