### ISSUE TITLE
I18n translates missing strings if there is one with/without context

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#10774]
As proven by https://github.com/cakephp/cakephp/pull/10597#issuecomment-308281345

> I have setup a small test environment and documented my tests including screenshots in https://github.com/ravage84/cakephp-po-issue-proof/commits/master for my [PO issue] issue.

**Comment by markstory** [comment]
I thought the issue @burzum was facing was related to plurals with `''` values not falling back to the message id? The commits you've linked to seem to further demonstrate the issue of message ids that have the same key with and without a context are incorrectly handled.

**Comment by markstory** [comment]
@ravage84 There are quite a few commits in the linked branch, do you have a smaller po file that demonstrates the issue you are having?

**Comment by ravage84** [comment]
There are many commits but it is a very small po file. The are many commits just to demonstrate the problem step by step, so one can checkout a particular situation for debugging and comparison.

**Comment by markstory** [comment]
If I'm lucky the changes in #10911 might also fix this issue.

**Comment by ravage84** [comment]
@markstory  I asked a colleqgue to verify this with my test repo and your branch. It _seems_ the issue still persits.

**Comment by markstory** [comment]
Cool. I'll get around to this soonish.

**Comment by markstory** [comment]
I attempted to reproduce this in the core test suite, and was not able to. See 24fc1d76993bae4a63f5843a990e1d963aff167d

**Comment by ravage84** [comment]
Hm... it might be the order of the strings? I don't know. I'd be fine if we close this for the moment. If it resurfaces, we can investigate again...

**Comment by dereuromark** [comment]
The file you referenced had invalid headers as @markstory pointed out. Maybe that was the issue here.
Then lets close until we can reproduce for certain with some failing test case etc.
