### ISSUE TITLE
2.x - Router::url() adds a prefix where it should not

### ISSUE THREAD

**Issue by sebastienbarre** [cakephp/cakephp#10771]
This is a:

* [x] bug (possibly)

* CakePHP Version: latest 2.x (e.g. 2.9.9)
* Platform and Target: any (LAMP, Apache, MySQL, PHP 7.0).

### What you did

I called `Router::url(['controller' => 'bonuses', 'action' => 'show'])` from an action that has a prefix. 

More specifically, consider a `AlertNotificationsController`, and its `api_send()` action, which is designed to be invoked as `/api/alert_notifications/send`. I've `Configure::write('Routing.prefixes', ['api']);` in `core.php` (per the CakePHP 2.x documentation on prefixes).

### What happened

I received `http://foo.com/api/bonuses/show`.

### What you expected to happen

I should have received `http://foo.com/bonuses/show`.

The reason an `/api` prefix was automatically added is puzzling, especially considering [this is in old code](https://github.com/cakephp/cakephp/commit/76c1c1cb8e4325956a99c5592c3ac62dec5ca051#diff-082140848984c0d1c1b861a56c83fa49R851) added 8 years ago (by @markstory).

It seems that if you call `Router::url($url, true)` from an action that *has* a prefix, then `Router::url()` will add *the same prefix* to `$url`. I do not quite understand why the fact that a request has a prefix should force all (unrelated) URLs generated from that action to also have one (be it in the action's view, or emails sent from that action, etc). 

In my case, the `/api/alert_notifications/send` action is an API endpoint, which sends emails containing permalinks to actual pages (not API endpoints) -- the resulting URL here ended up with an `api/` prefix (`http://foo.com/api/bonuses/show`), which was never requested in the first place, resulting in 404 permalinks.

The only workaround here is to call `Router::url()` with `$url` where *all* known prefixes defined in `Routing.prefixes` are keys set to `false`. Neither ideal nor robust.

Am I missing something? 
Thanks

**Comment by markstory** [comment]
This is an intentional feature of the routing system. Plugin, prefix and controller are parameters that are inherited from the current request context if not present into the URL parameters. This behavior date back to the origin of routing prefixes as an improvement on the singular static `Routing.admin` configuration variable which predates me working on CakePHP.

Because of how long in the tooth this feature is I'm not willing to remove it and break compatibility.

Your URL parameters should include `'prefix' => false` to disable any prefixes.

**Comment by sebastienbarre** [comment]
I'm with you @markstory on not wanting to break compatibility.
But the URL parameters need to include *all* known prefixes, and each time a prefix would change, or a new prefix is added, that's possibly a lot of calls to `Router::url()` to update :(
Would you be open to a PR *adding* an option that says: "do *not* prefix that URL". Quite literally, it would be `'prefix' => false` for example. And if there is already a prefix that actually *is* the word `prefix`, then it still works (since it's false).

**Comment by markstory** [comment]
> Would you be open to a PR adding an option that says: "do not prefix that URL". Quite literally, it would be 'prefix' => false for example. 

Yes. 3.x has `prefix => false` so adding it to 2.x sounds like a reasonable backport to me.

**Comment by sebastienbarre** [comment]
OK, I think [this commit](https://github.com/cakephp/cakephp/commit/752e0395df20258ed0cfc2b2a0fbb3e258ea33aa#diff-96c4899c68119ff96c047be21a9a1f0bR687) changed the 2.x behavior, followed by [this one](https://github.com/cakephp/cakephp/commit/e8a23e09cd1f5a3a1291d98690212deeb4c95c23#diff-53e2eaefba8d08c4ae2d0d082ef4d2d4R792).

**Comment by sebastienbarre** [comment]
@markstory with the current 2.10 being the last release, fix-only, would it still be OK to backport that "feature"?

**Comment by sebastienbarre** [comment]
Fast forward 2020, I got bitten hard in production by this one again, using Cake 2.x :(
