### ISSUE TITLE
query->select with contain return null on contain keys

### ISSUE THREAD

**Issue by AdrienCS** [cakephp/cakephp#10782]
* [x] bug ?
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.14
* Platform and Target: Apache2/MySQL

### What you did
I'm doing the following : 

```php
$this->Users->find()->hydrate(false)->select([
    'id', 
    'job_short_label' => 'Jobs_slug_translation.content'
])
->contain(['Jobs'], true) // To find the translation with i18n behavior
->all();
```
With an API call, it return : 

```json
{
    "id": 1,
    "job_short_label": "Plumber",
    "jobs": null
}
```

**As you can see, the "jobs": null is present and should not.**
I know it's something about the **contain**, models are : Users->hasOne("Jobs")

### What you expected to happen
I would like to have : 

```json
{
    "id": 1,
    "job_short_label": "Plumber"
}
```
Can't figure out how to solve this problem :(

**Comment by markstory** [comment]
You can't solve that problem. Because you're containing an association the ORM will attempt to build out the association data, which it can't because the data for the association is missing, so it has to insert null.

Have you tried using innerJoinWith() instead?

**Comment by AdrienCS** [comment]
With innerJoinWith('Jobs') instead of contain.
```shell
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Jobs_slug_translation.content' in 'field list'
```
So I changed
```php
    'job_short_label' => 'Jobs_slug_translation.content'
```
With
```php
    'job_short_label' => 'Jobs.slug'
```

And now I have

```json
{
    "id": 1,
    "job_short_label": "Plombier",
    "jobs": null
}
```
It does not translate _Plombier_ in _Plumber_

**Comment by markstory** [comment]
You might also have to innerJoinWith() the generated association that contains your translated field, or continue using contain() and remove the unwanted field with a formatResults() callback.

**Comment by AdrienCS** [comment]
```php
$this->Users->find()->hydrate(false)->select([
    'id', 
    'job_short_label' => 'Jobs_slug_translation.content'
])
->formatResults(function ($results) {
    return $results->map(function ($row) {
        unset($row['jobs']);
        return $row;
    })
})
->contain(['Jobs'], true) // To find the translation with i18n behavior
->all();
```

Do the trick

Response : 
```json
{
    "id": 1,
    "job_short_label": "Plumber"
}
```

It's solved, thanks a lot @markstory
