### ISSUE TITLE
Abstraction layer to manage authorizations

### ISSUE THREAD

**Issue by irongomme** [cakephp/cakephp#10788]
This is a:

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: linux, nginx 1.11.13, mysql 5.6

### What I suggest
What about adding an authorize class, to separate logic between Controller and isAuthorized method ? I'm in a common situation where I manage several kind of users (by roles), and each roles have different authorizations. So, in the isAuthorized method, I have to distinguish each controller action, and for each of them, the user role to return the good authorization. In real case, I've got a big isAuthorized method, and it's not a good thing to manage big methods ... 

We could have for example, associated with an ArticlesController, a binded ArticleAuthorize class, with methods like that : isAuthorizedIndex, isAuthorizedView, isAuthorizedEdit, etc ...

What do you think about ?

**Comment by ADmad** [comment]
`isAuthorized()` is meant for simple use cases. If you need more fine grained access control use a custom Authorization class class. For e.g `SimpleRbacAuthorize` provided by [CakeDC/auth](https://github.com/CakeDC/auth).

**Comment by ADmad** [comment]
Also we are in process of developing separate authentication and authorization plugins and deprecating AuthComponent and related classes, so making enhancements to it won't make sense.
