### ISSUE TITLE
There  is not way to clear POST data in 4.* API 

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10787]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Normally I would do `$this->request->data=[]` but this is depracated. While there is `withQueryParams` that accepts array of params, there is no equivalent for `withData` as this accepts only key,value arguments and does not allow to set post data params array. 

I have such usecase when I have to clear POST data and the input form is filled with posted data, while I want to fill it with different entity content. Right now I will use `$this-request->redirect([])` as a workaround but I would like to ommit one extra redirecting request.

**Comment by dereuromark** [comment]
The prg Pa redirect is not a workaround, it is the proper handling of a clearing after a successful post.

**Comment by inoas** [comment]
Does `foreach()` + https://api.cakephp.org/3.4/class-Cake.Http.ServerRequest.html#_withData resolve your problem? To clear loop through https://api.cakephp.org/3.4/class-Cake.Http.ServerRequest.html#_getData and set that to null with `withData`?

**Comment by Antoniossss** [comment]
@inoas This would surely do the trick, but still why there is inconsistency between `withData()` and `withQueryParameters()` signatures? Shouldn't it be one way or another?

**Comment by saeideng** [comment]
`4.* ==3.4.x?`

**Comment by ADmad** [comment]
As @dereuromark said using PRG is the correct thing to do for your use case. If you find the need to set/rest the whole request data most likely you are doing something wrong.

**Comment by markstory** [comment]
Doesn't `$request->withParsedBody([])` to replace the post data not do what you want?

**Comment by Antoniossss** [comment]
@markstory yest, that is it, this is exactly what i need. I missed that method. Thanks
