### ISSUE TITLE
Add Base64 or Quoted-Printable to Cake\Mailer\Email

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#10789]
This is a :

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.7

### What you did
I'm sending an email in french via Cake\Mailer\Email with chars like "é à ç è", my project is in utf-8, my debug mailer program is "mailcatcher 0.6.5"

### What happened
mailcatcher crash with `Exception: "\xC3" from ASCII-8BIT to UTF-8` error.
This doesn't append when i'm using phpmailer with base64 or quoted-printable encoding

### What you expected to happen
enhance the Mailer\Email with full base64 encoding like https://github.com/PHPMailer/PHPMailer do

**Comment by markstory** [comment]
Would you expect the Email content to be automatically converted and re-encoded? Or would that be a mode you call a method to enable? It looks like phpmailer sniffs the message contents.

**Comment by inoas** [comment]
Sniffing sounds no good to me vs setting modes and a sane default mode sound better imho.

**Comment by Erwane** [comment]
phpmailer encode each "encoded part" in base64, like attachments but also for html and text.

In base 64, emails are bigger (30% size) but if think it's more "compatible".

i imagine something like 
```php
$email = new \Cake\Mailer\Email()->encoding('base64');
```
phpmailer encodeString code : https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L2716

i can work on a PR if it's a nice feature

**Comment by markstory** [comment]
@Erwane I think it could be useful for folks sending unicode emails on unicode ignorant mail servers.

**Comment by LifeOrYou** [comment]
Can't be close ?
