### ISSUE TITLE
Default Installation Missing Files

### ISSUE THREAD

**Issue by MCDELTAT** [cakephp/cakephp#10785]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2
* Platform and Target: Ubuntu Server 16.04 running in a VirtualBox VM for testing. LEMP Stack (Nginx, MySQL, PHP 7.0.8)

### What you did
I'm new to CakePHP, so running through the book on installation, I installed my LEMP stack, installed the php7.0-mbstring and php7.0-intl packages, installed Composer via a method suggested by DigitalOcean (I kinda prefer it more): 
```
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
``` 
Then I ran the command listed in the book in my /var/www/ directory:
```
composer create-project --prefer-dist cakephp/app learning
```
### What happened
Everything looks to go fine, although extremely slow might I note. Folder 'learning' shows up, but when I got to localhost/learning I immediately get an error "LearningController could not be found." So I tried to do as it suggested and create it, it gives another error that it needs a public index() function. If I fix that, then it complains that another file is missing from the configuration "The view for LearningController::index() was not found." I haven't gone past trying to fix that error because it seems ridiculous that I'm missing this many files with a default install. 

Why are these missing? The book doesn't seem to clarify where a good default path is for new projects either. I might guess that it's not in /var/www because composer says you shouldn't run it as root but the only way to install to /var/www/ is by running as root. 

### What you expected to happen
A welcome screen. Like every tutorial I've found for CakePHP says will happen.

**Comment by cleptric** [comment]
Where is your DocRoot, configured in nginx, pointing to?

**Comment by markstory** [comment]
> Everything looks to go fine, although extremely slow might I note. 

There is not much we can do about this. Composer downloads packages off of github, and metadata off of packgist.org, so our hands are tied there.

Were you using your own webserver or the built in one? It sounds like you may be having a configuration issue with your webserver. Or using the wrong path for the built-in server.

If you are using your own webserver check the document root and virtualhost configuration against the configuration in the documentation.

**Comment by MCDELTAT** [comment]
@cleptric I'm running it at the default still, /var/www/html/

@markstory Can you point me to where the virtualhost config stuff is at in the book? It doesn't appear to be on the same "Installation" page. I might assume it is this because as noted, this is running on Ubuntu Server in a VirtualBox VM just for quick testing.

**Comment by cleptric** [comment]
https://book.cakephp.org/3.0/en/installation.html#nginx

**Comment by FallenThinker** [comment]
It seems like you trying to make the request to the site 'localhost' and open it's page 'learning' which default means that your request will handle controller 'Learning' and it's action 'index'. **_Strange_**... (I am about your result.) Where _cakephp_ files are located (folder name)?

**Comment by MCDELTAT** [comment]
Out of an interesting experiment, given that I have seen no tutorials that use nginx, I decided to switch to apache2, so I just stopped nginx in place, then configured apache2 etc. Interestingly, the project now loads semi-expected, but after running just the bare CakePHP install command, I'm missing all the CSS files and the SVG logo. This can be seen from the console.

**Comment by ADmad** [comment]
@MCDELTAT For both nginx and apache you problem is due to URL rewriting. The default install works just fine, you need to follow respective docs and configure URL rewriting for the webserver you are using.

**Comment by MCDELTAT** [comment]
Perhaps a reordering of the Installation section of the Book is in order then. It honestly doesn't make sense in it's current form. It tells you "Requirements: HTTP Server. For Example: Apache..." Then after a bunch of sections do we see that you can use the development server. Especially given that every tutorial besides your own tells you to install WAMP or equivalent, you really should at least state "You can use the development server for testing without Apache" right up front. Just saying...

**Comment by ADmad** [comment]
If URL rewriting is not properly configured the default homepage should already show you a red box mentioning the problem and links to doc for fixing it. https://github.com/cakephp/app/blob/master/src/Template/Pages/home.ctp#L64

**Comment by MCDELTAT** [comment]
@ADmad That's not really an elegant solution given that in nginx not having URL rewriting enabled just sent me to an error screen regarding the default view not existing, so I never saw that error. In Apache, not having it configured meant there was no CSS so it was in a blob of other grey text. In that case as a JS developer, I was mainly worried about what it said in the console, not what it said in the DOM.

Perhaps just state that in the requirements that it's something you to enable. Or write a one liner about the roadmap of installation "To run this in production you must have an HTTP server with URL rewriting enabled..."

I would suggest these changes more formally, but it looks like I'm the odd one out coming from a Node background.

**Comment by ADmad** [comment]
@MCDELTAT You are welcome to suggest improvements to the installation guide. Just click the  "improve this doc" link on the relevant page on the manual.

**Comment by markstory** [comment]
@MCDELTAT The tutorials have started to start recommending the built-in server as nginx/apache paths are not without their pitfalls. The built-in server is not without its problems though as it is single threaded and not intended for production use cases.

**Comment by markstory** [comment]
Closing as the setup issue here was resolved, and the tutorial already recommends using the built-in server.
