### ISSUE TITLE
Fixtures from plugin and subfolder

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10795]
I'm trying to load a fixture that is in a subdirectory of a plugin. My plugin is `MysqlBackup` and the subfolder is `Sqlite` (uppercase first).

Reading from [CookBook](https://book.cakephp.org/3.0/en/development/testing.html#loading-fixtures-in-your-test-cases), I would expect the correct syntax to be:

        plugin.mysql_backup.sqlite/articles

But running phpunit, I get this:

> PHP Fatal error:  Uncaught UnexpectedValueException: Referenced fixture class "MysqlBackup\Test\Fixture\Sqlite/articlesFixture" not found.

Note: incorrect slash and class name with lowercase initial.  
From here it seems that the subfolder should have the uppercase letter: in my case this is so, but the CookBook provides examples (`app.blog/articles`) with the lowercase letter (in other words: how should I do if the subfolder was `sqlite`?).

So the only way I have to load my fixture is this syntax:

        plugin.mysql_backup.sqlite\Articles

And this works.

This is a bit strange, does not it seem to you?

**Comment by ADmad** [comment]
Does using ` 'plugin.MysqlBackup.Sqlite/Articles' work?

**Comment by mirko-pagliai** [comment]
@ADmad no:

> Uncaught UnexpectedValueException: Referenced fixture class "MysqlBackup\Test\Fixture\Sqlite/ArticlesFixture" not found

**Comment by markstory** [comment]
I can take a look what you are describing should work.

**Comment by mirko-pagliai** [comment]
Another thing: fixture is not loaded anyway.  
I mean. Until now I used `$autoFixtures` as `false`, I was getting errors by just specifying the class of fixtures.

In other words, this is the only syntax that does not give me any errors:

    public $autoFixtures = false;

    public $fixtures = [
        'plugin.mysql_backup.sqlite\Articles',
    ];

If I try to load fixtures:

        $this->loadFixtures('Articles');

I get: `UnexpectedValueException: Referenced fixture class Articles not found`

**Comment by markstory** [comment]
Closing as a pull request is open now.
