### ISSUE TITLE
How to enable intl extention in window(plesk) hosting

### ISSUE THREAD

**Issue by nithins21** [cakephp/cakephp#10793]
I uploaded the cakephp 3.4 application on my shared hosting but I get an **intl extension error**.
Then I have extracted the cakephp files to the root of my subdomain and have created a web.config file as per the given instructions of the cakephp document, when i run the project on server I get **500 - Internal server error.**

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
