### ISSUE TITLE
Allow to provide multiple finders to Table#find() method.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10805]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

I have usecase when I want to combine rules provided by multiple find methods. 
For example, lets have 2 finder methods for `Tasks` table

`findApproved()` and `findResolved()`  - both builds obvious constrains for tasks that are approved and tasks that are resolved. But lets find tasks that are aproved and resolved at the same time.

What I am doing right now is

$query=$this->Tasks->find('approved')
$this->Tasks->findResolved($query); 

It would be usefull to combine such atomic rules in single call like `$this->Tasks->find(['approved'=>'optionalOptions','resolved'=>'optionalOptions'])`. Such call would apply both finders in given order.

**Comment by jeremyharris** [comment]
Isn't this already possible?

```
$query=$this->Tasks
    ->find('approved', $options)
    ->find('resolved', $options);
```

**Comment by Antoniossss** [comment]
Gosh how could I missed that........ thanks @jeremyharris
