### ISSUE TITLE
Declaration of Cake\TestSuite\Fixture\FixtureInjector::addFailure() on phpunit 5.7.21 and PHP 5.6

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10814]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.8
* Platform and Target: phpunit 5.7.21 and **only** PHP 5.6 (it works with 7.0 and 7.1)

```
PHP Fatal error:  Declaration of Cake\TestSuite\Fixture\FixtureInjector::addFailure() must be compatible with PHPUnit_Framework_TestListener::addFailure(PHPUnit_Framework_Test $test, PHPUnit_Framework_AssertionFailedError $e, $time) in /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php on line 45
PHP Stack trace:
PHP   1. {main}() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:163
PHP   6. require_once() /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:928
```

Full job log [here](https://travis-ci.org/mirko-pagliai/cakephp-database-backup/jobs/246206206).

**Comment by mirko-pagliai** [comment]
Same problem:

`PHP Fatal error:  Declaration of Cake\TestSuite\Fixture\FixtureInjector::startTestSuite() must be compatible with PHPUnit_Framework_TestListener::startTestSuite(PHPUnit_Framework_TestSuite $suite) in /home/travis/build/mirko-pagliai/cakephp-database-backup/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php on line 34`

**Comment by jeremyharris** [comment]
@mirko-pagliai the second commit on my pr fixed this issue and the cake test suite passes on php 5.6. Are you sure you have the latest master commit?

**Comment by mirko-pagliai** [comment]
I think so. Cakephp 74530d69615fd36a64f78f3580734ad7b05767fc and phpunit 5.7.21.

**Comment by jeremyharris** [comment]
Okay, odd. I'll take a look!

**Comment by cleptric** [comment]
@mirko-pagliai I also tried it against `master`. I'm using php56 and phpunit 5.7.21. Works fine.

**Comment by jeremyharris** [comment]
Okay, I was able to reproduce it on your repo. I'm working on a fix now.

**Comment by jeremyharris** [comment]
@mirko-pagliai I have a new PR up and tested it with your repo with success. Would you mind testing it as well so we can be sure it works for you.

Any other plugin authors out testing against PHP 5.6 who are willing to test the PR out - you'd be doing me a huge favor!

PR: https://github.com/cakephp/cakephp/pull/10821

**Comment by mirko-pagliai** [comment]
Yes, now it works!

**Comment by jeremyharris** [comment]
Awesome! Thanks for testing :)
