### ISSUE TITLE
Pagination count PDOException when used with leftJoin and having

### ISSUE THREAD

**Issue by kojot1234** [cakephp/cakephp#10810]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.8
* Platform and Target: LAMP

### What you did
Issue was introduced in 3.4.8 with the fix to #10697. 
https://github.com/cakephp/cakephp/commit/131c2d8b66f5fafa2eddf8f192b4897600a163a5

Pagination page count breaks with ->leftJoin and ->having. It returns invalid SQL because joins are stripped but having statement stays in the query. Returns: `Column not found: 1054 Unknown column 'RegionTags__matching' in 'having clause'`

### What happened
`$cleanQuery = clone $query;` does not clone the full query to perform count()

### What you expected to happen
Page count query should run successfully and should not trigger PDOException.

**Comment by markstory** [comment]
How can someone reproduce the query you're using that is causing this issue?

**Comment by kojot1234** [comment]
Please ignore this bug, while trying to create a simplified test case from the original query I wasn't able to reproduce the issue. I went back and figured out what the problem was. I was trying to reference original query inside of the `innerJoinWith` function, example below:

```
$query->innerJoinWith('ProgramTags', function ($q) use ($query) {
    ...
    $query->leftJoinWith('RegionTags', function ($qq) {
        return $qq;
    });
    ...
    return $q;
});
```

The following works fine in previous version but not in 3.4.8. After moving the `leftJoinWith` outside of the function (to where it's supposed to be in the first place) things were flying again. Thanks!
