### ISSUE TITLE
HTTP client redirect following doesn't include cookies from intermediary responses

### ISSUE THREAD

**Issue by thumbtech** [cakephp/cakephp#10820]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: Console (Windows 2012)

### What you did
I am using HTTP client to post credentials to an external website login form which requires several cookies & redirects (2 redirects, to be exact) to process ...

Example A (standalone PHP Script):

```php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_COOKIEFILE, 'cookie.txt'); 
curl_setopt($ch, CURLOPT_COOKIEJAR, 'cookie.txt');
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
$response = curl_exec($ch);
```

Example B (CakePHP 3.4 shell):

```php
$http = new Client();
$response = $http->post($url, $post_data, ['redirect' => 99]);
```
Example C (same CakePHP 3.4 shell as B):

```php
$http = new Client();
$response = $http->post($url, $post_data);
while ($response->isRedirect()) {
    $location = $response->getHeader('Location');
    $url = $location[0]; // SEE CAVEAT BELOW
    $response = $http->get($url);
}
```

### What happened
Examples A & C return the content expected after log in. Example B "fails" (status 200, but external webserver just returns the login form indicating failed login attempt).

### What you expected to happen
I would expect all three examples to be functionally equivalent.

I attempted to debug myself but didn't get far ... couldn't even locate where the redirects are actually called for re-requesting!

CAVEAT: Example C simplifies the step where a redirect may be relative (which in my case they are) and I "expand" the previous url for this case. Such a case is (apparently) handled internally by lib_curl (Ex. A) and should be also by the HTTP class (Ex. B), but I couldn't check the logic there since I couldn't even locate the code :-) ... not sure if that is even the issue!

**Comment by ndm2** [comment]
You're probably looking for the `Client` class' `redirect` option.

> Config options
> 
> You can set the following options when creating a client:
> 
> ...
> redirect - Number of redirects to follow. Defaults to false

**https://api.cakephp.org/3.4/class-Cake.Http.Client.html#___construct**

```php
$http = new Client([
    'redirect' => 2
]);
```

**Comment by thumbtech** [comment]
Yes I am sending the redirect option through the post method in Example B. Equivalent to sending through the constructor, or?

The question is why Examples B & C behave differently ...

**Comment by ndm2** [comment]
Sorry, totally overlooked that, haven't had a morning coffee yet :)

**Comment by ndm2** [comment]
A big vanilla raspberry latte later it looks like [**PHPs HTTP wrapper**](http://php.net/manual/en/context.http.php) (the redirects are handled internally) doesn't send cookies when following locations.

**Comment by ADmad** [comment]
> ... vanilla raspberry latte ...
:scream:

**Comment by ndm2** [comment]
I'm just trying to honour the league of cake, it was the closest red velvet drink equivalent I could find at my local coffe bar... it tasted kinda weird to say the least though :smile:

**Comment by markstory** [comment]
Sounds lke @ndm2 has found the root of the issue. I'm not sure how we could go about fixing this issue other than to disable PHP's `max_redirects` option and emulating that behavior in the client.

**Comment by thumbtech** [comment]
Thank you!

**Comment by markstory** [comment]
I am not sure if/when the client would be updated but your example is a good starting point for someone to build from.

**Comment by robertpustulka** [comment]
`Stream` adapter should return all responses including redirects: https://github.com/cakephp/cakephp/blob/master/src/Http/Client/Adapter/Stream.php#L94-L111

And the cookies from all these responses should be stored in a jar: https://github.com/cakephp/cakephp/blob/master/src/Http/Client.php#L372-L381

Looks like we need to fix the adapter to handle redirects on it's own.

**Comment by robertpustulka** [comment]
> Looks like we need to fix the adapter to handle redirects on it's own.
Nah, cookies are held in a `Client`, so it would be better if a client handled the redirects. I'm working on it.

**Comment by robertpustulka** [comment]
PR is open.
