### ISSUE TITLE
Creating fixtures fails if mysql reports current_timestamp() with parenthesis

### ISSUE THREAD

**Issue by kurrestahlberg** [cakephp/cakephp#10829]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9.
* Platform and Target: MacOS, mysqld Ver 10.2.6-MariaDB for osx10.12 on x86_64 (Homebrew).

### What you did
I have a table that has a field called updated_at that was created as follows: ``` `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP```
However my db version reports it back as ``` `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()```.
The bug occurs when trying to run tests that create fixtures for the affected table.

### What happened
An error is displayed and tests won't run.
```
2017-06-27 11:51:16 Error: Fixture creation for "ad_campaigns" failed "SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'"
PHP Warning:  Fixture creation for "ad_campaigns" failed "SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'" in /Users/kurre/mcn/nativeflow/Vendor/cakephp/cakephp/lib/Cake/TestSuite/Fixture/CakeTestFixture.php on line 244
```
Looking at the input to DboSource->_execute() I see the column being described as ``` `updated_at` timestamp DEFAULT 'current_timestamp()' NOT NULL``` which is obviously not correct.

### What you expected to happen
I expect tests to run and no error to be raised.

I am opening a PR with a fix.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
