### ISSUE TITLE
Add TestCase::loadAllFixtures() method

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#10831]
Suppose I'm using `$autoFixtures` as `false`, simply because I do not need fixtures to be loaded for all my class tests.

So I will use the `loadFixtures()` method whenever I need it, but often I manually load the same fixtures manually, which are all I have declared with the `$fixtures` property.

Something like this:

    class DriverTest extends TestCase
    {
        public $autoFixtures = false;

        public $fixtures = ['core.articles', 'core.comments'];

        public function testFirstMethod()
        {
            $this->loadFixtures('Articles', 'Comments');

            //... test
        }

        public function testSecondMethod()
        {
            $this->loadFixtures('Articles', 'Comments');

            //... test
        }
    }

So why not add a `loadAllFixtures()` method?

For now, because the `$this->fixtureManager->_fixtureMap` property is protected, I have this method:

    protected function loadAllFixtures()
    {
        $reflection = new \ReflectionClass($this->fixtureManager);
        $property = $reflection->getProperty('_fixtureMap');
        $property->setAccessible(true);
        $fixtures = $property->getValue($this->fixtureManager);
        $fixtures = array_keys($fixtures);

        call_user_func_array([$this, 'loadFixtures'], $fixtures);
    }

And this works. So I think it's enough to add a `getFixtureMap()` method and then the `loadAllFixtures()` method.

What do you think? Can I do a PR?

**Comment by jeremyharris** [comment]
I believe you can do something like this already:

```php
$this->fixtureManager->load($this);
```

**Comment by mirko-pagliai** [comment]
@jeremyharris 

> Perhaps just let it accept an array

Or even more simply, if the method is called without any argument, it loads all fixtures.  
So "the logic" would like this: `loadFixtures()` "normally" loads all declared fixtures; If you only want to load some, then you have to specify which.

**Comment by markstory** [comment]
Pull request open now.
