### ISSUE TITLE
Allow to rollback transaction in afterSave event

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10838]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Right now, result of (behavior in my case) afterSave callback is neglected. It would be very usefull to me If I would be able to rollback transaction by returning `false` just like I would in `beforeSave` callback especially that there is dedicated `afterSaveCommit` callback where obviously transaction is commited and cannot be rolled back.

**Comment by markstory** [comment]
Have you tried raising an exception from your afterSave hook?

Changing the semantics of the afterSave hook return value will likely have consequences to other applications, and isn't a change I am comfortable making.
