### ISSUE TITLE
QueryBuilder - lastInsertId() returns "0"

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#10836]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: MariaDB (5.5.5-10.1.21), PHP Version 7.1.1, Apache, Windows 7

### What you did

Trying to insert a new record and get the lastInsertId (AUTO_INCREMENT).

### What happened
The result of lastInsertId() is always "0".

Example code:

```sql
CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR (255),
  PRIMARY KEY (`id`)
) ENGINE = INNODB CHARSET = utf8 COLLATE = utf8_unicode_ci ;
```

```php
// composer require cakephp/database
require_once __DIR__ . '/vendor/autoload.php';

// Database settings
$config = array(
    'driver' => 'mysql',
    'host' => '127.0.0.1',
    'port' => '3306',
    'username' => 'root',
    'password' => '',
    'database' => 'test',
    'charset' => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix' => '',
);

$driver = new \Cake\Database\Driver\Mysql($config);
$db = new \Cake\Database\Connection(['driver' => $driver]);

$row = [
    'username' => 'max'
];

$result = $db->insert('users', $row);

$newId = $result->lastInsertId();
echo $newId;  // value is "0"
```

If I try the same with a native PDO query it works, but not with the CakePHP QueryBuilder.

```php
$pdo = $db->getDriver()->connection();
$stmt = $pdo->query("SELECT LAST_INSERT_ID()");
$lastId = $stmt->fetchColumn(); // This works. Returns 1 or more.
```

### What you expected to happen
Returns the ID of the last inserted row or sequence value.

**Comment by lorenzo** [comment]
@odan Try with the query builder instead of working directly with the connection instead while this is being investigated.

**Comment by lorenzo** [comment]
@odan Here you have an example of using the query builder for inserting https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Database/QueryTest.php#L4125-L4136

**Comment by markstory** [comment]
What does `$pdo->lastInsertId('users')` return in your PDO example. That is what CakePHP  is doing under the hood.

**Comment by odan** [comment]
Hi @lorenzo and @markstory 

I've tried it. The new row is inserted but the lastInsertId is still "0".

```php
$query = new \Cake\Database\Query($db);
$insert = $query
	->insert(['username'])
	->into('users')
	->values(['username' => 'max'])
	->execute();

$id = $insert->lastInsertId('users', 'id'); // "0"
$id2 = $insert->lastInsertId('users'); // "0"
$id3 = $insert->lastInsertId(); // "0"
```

**Comment by lorenzo** [comment]
@odan ok, that looks something like you don't have auto increment keys in your table? 

I'm saying that because the test case for the query builder + lastInsertId() is passing... as the rest of the tests in the ORM.

I've seen this behaviour before and turned out to be that I missed the auto increment setting

**Comment by odan** [comment]
@lorenzo Yes there is an AUTO_INCREMENT setting for the primary key (id).

```
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
```

Screenshot:

![image](https://user-images.githubusercontent.com/781074/27648746-c9d49ca0-5c2f-11e7-92cb-c77f30434be6.png)

It works if I add new row manually in MySQL-Workbench and SQLyog.
Also this code returns the new ID. But this is not what I'm looking for.

```
$pdo = $db->getDriver()->connection();
$stmt = $pdo->query("SELECT LAST_INSERT_ID()");
$lastId = $stmt->fetchColumn(); // This works. Returns 1 or more.
```
And this native PDO insert works too:

```php
$host = '127.0.0.1';
$dbname = 'test';
$username = 'root';
$password = '';
$charset = 'utf8';
$collate = 'utf8_unicode_ci';

$pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=$charset", $username, $password,
	array(
		PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
		PDO::ATTR_PERSISTENT => false,
		PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
		PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES $charset COLLATE $collate"
	)
);

$row = [
    'username' => 'bob',
];
$sql = "INSERT INTO users SET username=:username";
$status = $pdo->prepare($sql)->execute($row);

if ($status) { // true
    $lastId = $pdo->lastInsertId();
    echo $lastId;
}
```

The result:

![image](https://user-images.githubusercontent.com/781074/27648910-6a3f2f2a-5c30-11e7-9adb-1069aff2fe1b.png)

**Comment by saeideng** [comment]
and your db after your query  by cake query?

**Comment by lorenzo** [comment]
@odan there is something odd. I think you may be using different databases by mistake or something similar. I copy pasted your code, created a new database and ran the script multiple times:

<img width="948" alt="screen shot 2017-06-28 at 20 03 02" src="https://user-images.githubusercontent.com/37621/27652685-eae2ea34-5c3c-11e7-96a6-69e208544118.png">

Can you maybe create a sample repo with the SQL we could use locally for testing?

**Comment by odan** [comment]
Ok this is crazy.... I've testet the same code on my home computer and here it works.

![image](https://user-images.githubusercontent.com/781074/27653900-d230b7f6-5c40-11e7-8d02-bb5c57f62c6d.png)

But then I started XDebug and the result is 0 again.

![image](https://user-images.githubusercontent.com/781074/27653991-1b64ed48-5c41-11e7-9a32-609722963b09.png)

![image](https://user-images.githubusercontent.com/781074/27654029-40fd5c66-5c41-11e7-89d1-1feed9d243e8.png)

If I disable XDebug in PHPStorm everything works! 
How is that possible?

**Comment by lorenzo** [comment]
Ok, that is indeed crazy. First time I see this.

When using xdebug, does it at least outputs the right value?

**Comment by odan** [comment]
@lorenzo 

I try to summarize it:

XDebug is enabled:

![image](https://user-images.githubusercontent.com/781074/27654986-087ea626-5c44-11e7-8fb6-2ed22a8c7f6a.png)

With this breakpoint it doesn't work:
![image](https://user-images.githubusercontent.com/781074/27655018-3176097a-5c44-11e7-91df-9449427b1321.png)

![image](https://user-images.githubusercontent.com/781074/27655028-41388b3a-5c44-11e7-831b-2f9c219a9853.png)


Without this breakpoint it works:

![image](https://user-images.githubusercontent.com/781074/27655045-4efcd7a8-5c44-11e7-9fc6-67acebed9c95.png)

![image](https://user-images.githubusercontent.com/781074/27655064-5ac5f826-5c44-11e7-99c6-5f15a9dd2a06.png)

The same behavior on two different computers.

> When using xdebug, does it at least outputs the right value?
Yes, but only if I remove all breakpoints.

**Comment by lorenzo** [comment]
@odan sounds like you will have to open a bug in the xdebug repo? Try first to use the latest php + debug available to discard that they didn't fix that issue already.

I'm closing given that the feature works correctly and that we are not in control of what debug does to the code. We'll be happy to reopen this if new information is added with code we can change to fix or make this less of an issue

**Comment by raul338** [comment]
lastInsertId only works if the last query was an insert, if you query a select or another query lastInserId returns 0
I guess in your debugging some variable inspector would execute another query (like a count?) set lastinsertid to 0

**Comment by odan** [comment]
@lorenzo OK thank you :-)

**Comment by gmponos** [comment]
> lastInsertId only works if the last query was an insert, if you query a select or another query lastInserId returns 0
> I guess in your debugging some variable inspector would execute another query (like a count?) set lastinsertid to 0

I have stopped using lastInsertId for the same reason. When ever I want to get back the lastInsertedId I always query the database. It's too unstable having this and you might easily end up with race conditions.

**Comment by odan** [comment]
Here is an update:

There is an issue with the magic method: [__debugInfo()](http://php.net/manual/en/language.oop5.magic.php#object.debuginfo) in Driver.php

https://github.com/cakephp/cakephp/blob/master/src/Database/Driver.php#L386

Xdebug uses PHP's var_dump() function for displaying variables. 
https://xdebug.org/docs/display

Changing the `xdebug.overload_var_dump` value in php.ini has no positive effect. 
https://derickrethans.nl/xdebug-2.3-overload-vardump.html

Workaround / Fix: If you return just an empty array it works like expected.

![image](https://user-images.githubusercontent.com/781074/27680292-8df4ebea-5cbb-11e7-9d47-d2257f74d15b.png)

**Comment by markstory** [comment]
Connection != null is probably good enough for debug data. I wouldn't change isConnected() though.

**Comment by odan** [comment]
I added a PR. Thank you @markstory
