### ISSUE TITLE
Translate behavior with innerJoinWith() fetch data like contain()

### ISSUE THREAD

**Issue by AdrienCS** [cakephp/cakephp#10835]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.14
* Platform and Target: Apache2, MySQL.

### What you did
```php
# JobsTable
$this->addBehavior('Translate', ['fields' => ['label']]);

# In an action
$this->Users
     ->find()
     ->select([
         'Users.id',
         'name' => 'Users.firstname',
         'job_label' => 'Jobs.label'
     )]
     ->innerJoinWith('Jobs')
     ->first();
```

### What happened
```json
{
    "id": 1,
    "name": "Jack",
    "job_label": "Plumber",
    "job": {
        "id": 8,
        "label": "Plumber",
        "_local": "en-GB
    }
}
```

### What you expected to happen
```json
{
    "id": 1,
    "name": "Jack",
    "job_label": "Plumber"
}
```

The innerJoinWith() fetch data from Jobs like a contain() because of the Translate behavior on the table Jobs. If I remove the behavior, i'll get the expected result (but without translation).

**Comment by lorenzo** [comment]
innerJoinWith does not fetch columns. That's by design. You can use `contain` and set the joinType for this case.

**Comment by markstory** [comment]
@lorenzo I think the issue is that translatebehavior is eager loading the job association when @AdrienCS doesn't want the record hydrated.

**Comment by AdrienCS** [comment]
@markstory Thanks, I could not have explained it more clearly.

**Comment by lorenzo** [comment]
I see, the behaviour should detect that the user does not eat any fields to be hydrated.

@AdrienCS I currently have no time to investigate this issue myself, but I can guide you if you like to code a solution for this.

**Comment by AdrienCS** [comment]
@lorenzo Sure but I think that the problem does not come from the TranslateBehavior, he's triggered as he should like 
"_Oh, I see that there is a field that can be translated on the Table you are using.. there it is, you welcome_".
Seem it does not need to look at the query who use the Table who trigger the TranslateBehavior. 
Or I'm misunderstanding the concept..

**Comment by lorenzo** [comment]
@AdrienCS the behaviour is triggered because of `beforeFind`, but I think we can set information in the beforeFind options to let the behaviour know how it is being loaded. Then the behavior can decided whether or not it needs to load any data.

**Comment by markstory** [comment]
I took a look at this again, and I have a question. Are you sure that your `jobs_label` aliased field is loading the correct data?  I tried to reproduce your scenario with an association `Authors hasMany Articles`, with `Articles` having TranslateBehavior attached. In my setup the `jobs_label` field is populated with the data stored in the `articles` table and it never reflects the translated data. This is because the generated queries look like:

```sql
 SELECT Authors.id AS `Authors__id`, Authors.name AS `Authors__name`, Articles.title AS `article_title` 
FROM authors Authors 
INNER JOIN articles Articles ON Authors.id = (Articles.author_id)
LIMIT 1
```

A separate query is emitted for the translations, which are subsequently set into the association property. A similar query and result is generated if I define my association as `hasOne` instead of `hasMany`. I'm not confident we can remove the entity hydration either. Because `innerJoinWith()` is using `matching()` under the hood, the beforeFind event is always triggered on your association resulting in the records being hydrated.

**Comment by AdrienCS** [comment]
> https://book.cakephp.org/3.0/en/orm/query-builder.html#using-innerjoinwith
> There may be cases where you want to use matching() but are not interested in loading the fields into the result set. For this purpose, you can use innerJoinWith():

Fine, that's not dramatic it just seemed to report against the documentation of **innerJoinWith()**.

I maked a retry, still in Cake 3.2.14:
```php
<?php
# TestShell.php

    /**
     * https://github.com/cakephp/cakephp/issues/10835#issuecomment-311617153
     */
    public function gitIssue10835()
    {
        I18n::locale('en-GB');
        $this->loadModel('Users');

        $query = $this->Users
            ->find()
            ->hydrate(false)
            ->innerJoinWith('Jobs')
            ->select([
                'id' => 'Users.id',
                'firstname' => 'Users.firstname',
                'job_label' => 'Jobs.label'
            ])
            ->first();

        debug($query);
    }
```

```shell
/src/Shell/TestShell.php (line 446)
########## DEBUG ##########
[
        'id' => (int) 1,
        'firstname' => 'William',
        'job_label' => 'Plumber',
        'job' => null
]
###########################
```

I don't know why I get a **nulll** now in **job**, even if I does not use it.....

**Comment by AdrienCS** [comment]
Part of the output when I **debug($query)** without **->first()**, it may help :|
```shell
        ...
        'buffered' => true,
        'formatters' => (int) 1,
        'mapReducers' => (int) 0,
        'contain' => [
                'Jobs' => [
                        'Jobs_label_translation' => [
                                'queryBuilder' => object(Closure) {
                                        
                                }
                        ]
                ]
        ],
        'matching' => [
                'Jobs' => [
                        'queryBuilder' => null,
                        'matching' => true,
                        'joinType' => 'INNER',
                        'fields' => false
                ]
        ],

```

**Comment by AdrienCS** [comment]
More simple:

```php
<?php
    /**
     * https://github.com/cakephp/cakephp/issues/10835#issuecomment-311617153
     */
    public function gitIssue10835()
    {
        I18n::locale('en-GB');

        $this->loadModel('Users');

        $query = $this->Users
            ->find()
            ->hydrate(false)
            ->innerJoinWith('Jobs');

        debug($query->first());
    }
```

```shell
########## DEBUG ##########
[
        'id' => (int) 1,
        'firstname' => 'William',
        'job_id' => (int) 37,
        'created' => object(Cake\I18n\FrozenTime) {...},
        'updated' => object(Cake\I18n\FrozenTime) {...},
        'job' => [
                'id' => (int) 37,
                'label' => 'Plumber',
                'created' => object(Cake\I18n\FrozenTime) {...},
                'updated' => object(Cake\I18n\FrozenTime) {...},
                '_locale' => 'en-GB'
        ]
]
###########################
```

**Comment by markstory** [comment]
The reason you're getting an entity hydrated when you're using `innerJoinWith()` is that your associated models *also* have TranslateBehavior attached. `TranslateBehavior::beforeFind()` is triggered for your query, and it attaches the translation associations which result in an entity being hydrated.

The documentation for `innerJoinWith()` are correct, except in the case where TranslateBehavior is also in use.

**Comment by AdrienCS** [comment]
Thanks @markstory for investigations :)
