### ISSUE TITLE
invalid condition when using orWhere() 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10845]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.x

see `orWhere()` with/without `AND` after second calling `orWhere()`

query with `AND`
```
      $table=\Cake\ORM\TableRegistry::get('Tests');
      $query=$table->find();
      $query=$query
          ->where(['AND'=>[
            'Tests.id'=>1,
            'Tests.title'=>'test'
          ]])
          ->orWhere(['AND'=>[
            'Tests.id'=>2,
            'Tests.title'=>'test'
          ]])
          ->orWhere(['AND'=>[
            'Tests.id'=>3,
            'Tests.title'=>'test'
          ]])
          ->orWhere(['AND'=>[
            'Tests.id'=>4,
            'Tests.title'=>'test'
          ]]);

      $query->toList();
```
result query with `AND`
```
WHERE 
  (
    (
      Tests.id = 1 
      AND Tests.title = 'test'
    ) 
    OR (
      Tests.id = 2 
      AND Tests.title = 'test'
    ) 
    OR (
      Tests.id = 3 
      AND Tests.title = 'test'
    ) 
    OR (
      Tests.id = 4 
      AND Tests.title = 'test'
    )
  )
```
query without `AND`
```
$query
          ->where([
            'Tests.id'=>1,
            'Tests.title'=>'test'
          ])
          ->orWhere([
            'Tests.id'=>2,
            'Tests.title'=>'test'
          ])
          ->orWhere([
            'Tests.id'=>3,
            'Tests.title'=>'test'
          ])
          ->orWhere([
            'Tests.id'=>4,
            'Tests.title'=>'test'
          ]);
```
result query without `AND`
```
WHERE 
  (
    (
      Tests.id = 1 
      AND Tests.title = 'test'
    ) 
    OR (
      Tests.id = 2 
      AND Tests.title = 'test'
    ) 
    OR Tests.id = 3 
    OR Tests.title = 'test' 
    OR Tests.id = 4 
    OR Tests.title = 'test'
  )
```
### What you expected to happen
should return 
```
    OR (
      Tests.id = 3 
      AND Tests.title = 'test'
    ) 
    OR (
      Tests.id = 4 
      AND Tests.title = 'test'
    )
```
but returned 
```
    OR Tests.id = 3 
    OR Tests.title = 'test' 
    OR Tests.id = 4 
    OR Tests.title = 'test'
```

**Comment by saeideng** [comment]
if I change  first `where()` to `orWhere()`
```
WHERE 
  (
    (
      Tests.id = 1 
      AND Tests.title = 'test'
    ) 
    OR Tests.id = 2 
    OR Tests.title = 'test' 
    OR Tests.id = 3 
    OR Tests.title = 'test' 
    OR Tests.id = 4 
    OR Tests.title = 'test'
  )
```

**Comment by markstory** [comment]
I think this behavior is intentional. The documentation for `orWhere()` states

>  It is important to notice that when calling this function, any previous set
> of conditions defined for this query will be treated as a single argument for
> the OR operator. This function will not only operate the most recently defined
> condition, but all the conditions as a whole.

Which results in `orWhere` and `andWhere` being dependent on the conditions previously connected. I'm not comfortable changing this behavior as it will certainly break existing applications.

**Comment by lorenzo** [comment]
The behaviour is intentional, and something I regret :(

**Comment by markstory** [comment]
@lorenzo Should we consider deprecating `orWhere()` & `andWhere()` given their less predictable results? They could re-introduced in 4.1 with a simpler to understand behavior.

**Comment by saeideng** [comment]
So why result of first and second usage of orWhere() is defferent ?
This method should return same result 
Or `(..)and(..)` or linear condition `or .. or.. `  for all calling  this method

**Comment by lorenzo** [comment]
@markstory I think that's a good plan

**Comment by saeideng** [comment]
Why for 4.1.x version? Not for 4.0

**Comment by lorenzo** [comment]
4.0 is when we can remove the deprecated methods. 4.1 is when we can introduce again fucyuins that were removed

**Comment by saeideng** [comment]
`orHaving()` use similar code like `orWhere()` and i think there is same problem on that 
`orHaving()` can be deprecate

`andWhere()` can be remove completely because both of `andWhere()` and `where()` have same behavior 
my suggest is removing  `andWhere()` and `andHaving()`

but for `orWhere()`
my suggest is deprecated that and use `orWhere + s` naming for linear `OR` and just linear `OR` if necessary   
or just by `and` condition by  `orWhere` naming

**Comment by markstory** [comment]
Pull request for deprecations is up now.
