### ISSUE TITLE
'Unabled to insert fixture' when columns have the same name as the SQL reserved words

### ISSUE THREAD

**Issue by ckbx-cakebox** [cakephp/cakephp#10849]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.9 / a9eb22193e8df235ec71f4ed4a71158efa5e0b23
* Platform and Target: PHP 5.6.29 / MySQL 5.7.17

### What you did
I have a table with some columns named the same as the SQL reserved words, such as 'interval', 'from', etc.  Baking it into fixtures and running phpunit with the just-baked controller test cases.

```
class UsersFixture extends TestFixture {
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 11, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
        'interval' => ['type' => 'integer', 'length' => 11, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'autoIncrement' => null],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
        ],
        '_options' => [
            'engine' => 'InnoDB',
            'collation' => 'utf8_general_ci'
        ],
    ];
    public $records = [
        [
            'id' => 1,
            'interval' => 1
        ],
    ];
}
```

### What happened
I see the error message 'Unable to insert fixture' like this:

```
Unable to insert fixture "App\Test\Fixture\UsersFixture" in "App\Test\TestCase\Model\Table\UsersTableTest" test case: 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'interval) VALUES (1, 1)' at line 1 in [/path/to/my/project/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 345]
```

Trying to escape column names with backquotes (MySQL's way) seems just to ignore the record value.

```
SQLSTATE[HY000]: General error: 1364 Field 'interval' doesn't have a default value in [/path/to/my/project/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 345]
```

### What you expected to happen
Fixtures are successfully inserted with appropreate escapes for the column names, in the vendor-specific manner if needed.

**Comment by ADmad** [comment]
Enable [identifier quoting](https://github.com/cakephp/app/blob/master/config/app.default.php#L241) for your test connection.

**Comment by ckbx-cakebox** [comment]
Identifier quoting!  Everything is OK when I turn on the feature.
Eventually I know the using of reserved words needs the identifier quoting feature in CakePHP 3 ORM, that leads to a significant performance overhead...
