### ISSUE TITLE
ConsoleIo overwrite failed if output is less than previous overvrite

### ISSUE THREAD

**Issue by yark** [cakephp/cakephp#10858]
This is a:

* [x] bug

* CakePHP Version: 3.4.9.
* Platform and Target: Mac os x 10.11 console.

### What you did
```
<?php
namespace App\Shell;

use Cake\Console\Shell;

class TmertestShell extends Shell
{
    public function testTimer($sec = 10)
    {
        $this->out($sec, 0);
        for ($i = $sec; $i > 0; $i--) {
            $this->_io->overwrite($i, 0);
            sleep(1);
        }
        $this->out();
    }
}

```

```$ ./bin/cake timertest testTimer```

### What happened
If length of `message` param of `_io->overwrite` ($i) less than last output it unable to overwrite next output.
$sec = 10
```
10
9
98
97
...
91
```

$sec = 101
```
101
100
99
9998
9997
...
9912
9911
9910
999
9998
...
9991
```

*) I was showing each iteration in new line, but it actually happens in single line

### What you expected to happen
I expect correct overwrite
```
101
100
99
98
...
11
10
9
8
...
1
```

I can fix it providing third argument length

```
    public function testTimer($sec = 10)
    {
        $this->out($sec, 0);
        $ow_length = strlen((string)$sec);
        for ($i = $sec; $i > 0; $i--) {
            $this->_io->overwrite($i, 0, $ow_length);
            sleep(1);
        }
        $this->out();
    }
```

but in this case it will output extra space after message.

**Comment by markstory** [comment]
I'll see if I can reproduce this locally.

**Comment by markstory** [comment]
Closing as a pull request is open.
