### ISSUE TITLE
Empty form values for fields with array-like values

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#10853]
This is a (multiple allowed):
[x] bug
CakePHP Version: 3.4.9

### What you did
I have created custom JsonType that maps database field with json string to an object (JsonObject class implements JsonSerializable, IteratorAggregate, ArrayAccess,Countable interfaces)

Then i have created following test form:
````PHP
//Users/edit.ctp
echo $this->Form->create($user);
debug($user['metadata']->toArray());

debug($user['metadata']['aff_id']);
debug($this->Form->getSourceValue('Users.metadata.aff_id'));

echo $this->Form->control('Users.metadata.aff_id',['type'=>'number']);
echo $this->Form->end();
````

### What happened
```
[
	'activation_token' => '2r3y0MStLinhS14Ax45Z5BY4x251Far6gwii0fPb',
	'expiry_notifications_active' => '1',
	'bnd_notifications_active' => '1',
	'developer_notifications_active' => '1',
	'aff_id' => '1',
	'language' => 'pl',
	'timezone' => 'Europe/Warsaw',
	'default_currency' => '1'
]

'1'
null

(input form with empty value)
```
### What you expected to happen
```
[
	'activation_token' => '2r3y0MStLinhS14Ax45Z5BY4x251Far6gwii0fPb',
	'expiry_notifications_active' => '1',
	'bnd_notifications_active' => '1',
	'developer_notifications_active' => '1',
	'aff_id' => '1',
	'language' => 'pl',
	'timezone' => 'Europe/Warsaw',
	'default_currency' => '1'
]

'1'
'1'

(input form with '1' value)
```
### The  problem
https://github.com/cakephp/cakephp/blob/master/src/View/Form/EntityContext.php#L262
When the entity field contains plain php array EntityContext->val() returns correct value, but in case of array-like object null is returned instead.

**Comment by markstory** [comment]
How would you recommend we traverse into arbitrary userland objects? Would using `ArrayAccess` in that specific case work?

**Comment by Asgraf** [comment]
ArrayAccess should work in my case.
My JsonObject class is intended to be used with Cake\Utility\Hash::get() and Cake\Utility\Hash::extract()

**Comment by markstory** [comment]
Pull request open now.
