### ISSUE TITLE
PDO::MSSQL PHP7 Driver doesn't return VARBINARY as hexadecimal anymore

### ISSUE THREAD

**Issue by Nic0tiN** [cakephp/cakephp#10854]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.9
* Platform and Target: 
Dev: Windows 7 x64, Apache 2.4.25 x64, SQL Server Express 2014 SP2, PHP 7.1.2 TS x64.
Prod: Windows Server 2012, Apache 2.4.25 x64, SQL Server 2014 SP1, PHP 7.1.2 TS x64

### What you did
Reading VARBINARY values from SQL Server.

### What happened
The Microsoft Drivers for PHP for SQL Server PHP 7 (https://github.com/Microsoft/msphpsql) converts VARBINARY values PDO option PDO::SQLSRV_ENCODING_BINARY is disabled. Therefore, Cake is expecting an hexadecimal but receives a string.

### What you expected to happen
No conversion should happen unless PDO option PDO::SQLSRV_ENCODING_BINARY is enabled.

I would suggest to bypass the following check (must check which version is affected) and expose the raw data to developpers when the option PDO::SQLSRV_ENCODING_BINARY is enabled.

In Cake\Database\Type\BinaryType:
```
        if (is_string($value) && $driver instanceof Sqlserver) {
            $value = pack('H*', $value);
        }
```

**Comment by markstory** [comment]
So this encoding issue only happens when `SQLSRV_ENCODING_BINARY` is disabled?

**Comment by Nic0tiN** [comment]
Yes. I can't find if we can change the default value of that parameter. To use `SQLSRV_ENCODING_BINARY`, we need the following method `PDOStatement::bindColumn(column, &$var, type,length,PDO::SQLSRV_ENCODING_BINARY);`.
I don't think bindColumn is accessible through the ORM nor `Query`.

**Comment by markstory** [comment]
Did the defaults change in PHP7 then?

**Comment by Nic0tiN** [comment]
Yes, it changed in PHP7. Testing with PHP 5.4 returns binary values.

**Comment by markstory** [comment]
Closing as a pull request is open now.
