### ISSUE TITLE
ACL deny, then grant not working as expected.

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#10869]
* [x] bug
* [x] feature request (see bottom of post)

* CakePHP Version: 3.7.7
* Platform and Target: 7.0.18-0ubuntu0.16.04.1

### What you did, what happened
Trying to grant access to an `aco` when it has already been denied at least once does not work. I encountered this problem when trying to grant my administrative users access to a particular `aco` that I had denied previously. 

This would say `Permission granted`, but wouldn't actually work:

```
$ bin/cake acl grant Groups.1 controllers/manage/Tracks/index
```

After messing with it for a while I tried to recover `aro`/`aco`. This didnt help. 

I resolved this by deleting the `aco`, then granting permission again, like so:

```
$ bin/cake acl delete aco controllers/manage/Tracks/index
Aco deleted.
```

```
$ bin/cake acl_extras aco_sync
Created Aco node: controllers/Manage/Tracks/index
Aco Update Complete
```

```
$ bin/cake acl grant Groups.1 controllers/manage/Tracks/index
Permission granted.
```

Then when I accessed the `aco` as an administratively grouped user it worked.

### What you expected to happen
I expect deny, then granting again to allow access to the `aco`.

Also, is it possible to get a bit more documentation on Cake's ACL stuff. Also, is there any way I can get a listing of all permissions for a specific `aco`, such as `/manage/Tracks/index`? And is there a way to get a list of what `aco`'s a user group has access to? Thanks.

**Comment by ADmad** [comment]
This issue was moved to cakephp/acl#122
