### ISSUE TITLE
PHP 7.2 has changed count's behavior causing problems with QueryCompiler

### ISSUE THREAD

**Issue by MCF** [cakephp/cakephp#10862]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.8
* Platform and Target: Windows 7 (but it will affect all platforms running PHP 7.2)

PHP 7.2 has changed the behavior of count, it emits a warning if the object to be counted is not an array, or it does not implement the Countable interface:

https://wiki.php.net/rfc/counting_non_countables

As a result the _sqlCompiler created function in the QueryBuilder now emits many warnings.  This line is the problem:

https://github.com/cakephp/cakephp/blob/master/src/Database/QueryCompiler.php#L128

The `$parts` variable can be many different things, including non-arrays and objects not implementing the Countable interface (for example instances of Cake\Database\Expression\ValuesExpression), and many different warnings will result during normal operations.

I presume that in future versions of PHP the old count behavior of returning 1 for non-arrays and non-Countable objects will be removed, so this should be fixed for that reason as well.

**Comment by markstory** [comment]
Closing as a pull request is open now.

**Comment by igreatdev** [comment]
This issue also exists in v3.3 after updating still gives the same warning. Please update it too.

**Comment by ADmad** [comment]
@igreatdev The fix is available in 3.4.10 and above.
