### ISSUE TITLE
i18n causes problems in new Validator/ORM when used outside of framework

### ISSUE THREAD

**Issue by Swader** [cakephp/cakephp#10883]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.9
* Platform and Target: [Homestead Improved](http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/) VM on OS X

### What you did
Only using ORM. ORM seems to be requiring Validator, which now requires i18n (didn't before). i18n needs the `_cake_core_` cache config value (if Cache is installed, and it is), but has no defaults it uses if this value is not installed.

### What happened
At this point, Cache crashes because it can't find this value.

### What you expected to happen
Ignore the absence of this value by using defaults, or don't pay attention to i18n at all since the app doesn't make use of it. Alternatively, make it easier to set config options for this in projects that don't use the framework but just some components.

Additional info:

```
[2017-07-08 14:14:03] ebay.ERROR: The "_cake_core_" cache configuration does not exist.    

#0 /home/vagrant/Code/notify/vendor/cakephp/cache/Cache.php(183): Cake\Cache\Cache::_buildEngine('_cake_core_') 
#1 /home/vagrant/Code/notify/vendor/cakephp/i18n/I18n.php(79): Cake\Cache\Cache::engine('_cake_core_') 
#2 /home/vagrant/Code/notify/vendor/cakephp/i18n/I18n.php(138): Cake\I18n\I18n::translators() 
#3 /home/vagrant/Code/notify/vendor/cakephp/i18n/functions.php(88): Cake\I18n\I18n::translator('cake') 
#4 /home/vagrant/Code/notify/vendor/cakephp/validation/Validator.php(103): __d('cake', 'This field is r...') 
#5 /home/vagrant/Code/notify/vendor/cakephp/orm/Marshaller.php(245): Cake\Validation\Validator->errors(Array, true) 
#6 /home/vagrant/Code/notify/vendor/cakephp/orm/Marshaller.php(180): Cake\ORM\Marshaller->_validate(Array, Array, true) 
#7 /home/vagrant/Code/notify/vendor/cakephp/orm/Table.php(2412): Cake\ORM\Marshaller->one(Array, Array) 
#8 /home/vagrant/Code/notify/src/Model/Table/EbayNotificationLogTable.php(124): Cake\ORM\Table->newEntity(Array) 
#9 /home/vagrant/Code/notify/src/Model/Table/EbayNotificationLogTable.php(101): n1066\Model\Table\EbayNotificationLogTable->logNew('<?xml version="...', 'NEW') 
#10 /home/vagrant/Code/notify/src/Controllers/Api/Ebay.php(116): n1066\Model\Table\EbayNotificationLogTable->logToBacklog('<?xml version="...') 
#11 /home/vagrant/Code/notify/public/index.php(34): n1066\Controllers\Api\Ebay->ebayLogger() 
#12 /home/vagrant/Code/notify/public/ebay_notify.php(3): require_once('/home/vagrant/C...') 
#13 {main} [] []


```

**Comment by ADmad** [comment]
Can you please provide the full stack trace for the error.

**Comment by Swader** [comment]
The full stack trace is in the "Additional info" section (single line - scroll right. Will try to output a line-broken one as soon as I'm at the computer again).

The reason for the failure is [here](https://github.com/cakephp/i18n/blob/master/I18n.php#L79) which triggers if Cache is installed, which in my project, it is. However, I am not using Cake core, just the ORM, so I don't have this cache key configured anywhere.

**Comment by ADmad** [comment]
Validator tries to use i18n only if `cakephp/i18n` is installed. Neither `cakephp/orm` or `cakephp/validation` required that package. Do you explicitly have `cakephp/i18n` as a dependency in your app?

**Comment by Swader** [comment]
Validator [now requires it explicitly](https://github.com/cakephp/validation/blob/master/composer.json#L27)

**Comment by ADmad** [comment]
Ah sorry, my mistake.

**Comment by ADmad** [comment]
PR #10438 added it as a requirement. I think it should be reverted back. It's required by only `Validation::localizedTime()` and those who want to use that method can explicitly install the `cakephp/i18n` package.

**Comment by Swader** [comment]
An undo on that front would be good for my use case, but I think the problem is bigger than that. 

Those people who want to use that method will then still run into my problem if they want to use these packages without Cake core. The Cake core problem in i18n needs to be addressed - perhaps by checking if the configuration value exists, and using defaults if not, rather than breaking, or by simply providing a clearer error message or a link to instructions on how to set this required config value when not using the whole framework.

Anyway, any chance for a fix being applied today and released, or should I just better revert to an older version?

**Comment by Swader** [comment]
Also note that the above problem will be apparent only if Cache is installed. So this problem will fly under the radar if the packages are being used outside the framework and without cache, but as soon as Cache is in there too, things will blow up because it keeps looking for that key.

**Comment by ADmad** [comment]
> An undo on that front would be good for my use case, but I think the problem is bigger than that.

I have opened PR #10884 to this effect.

> Those people who want to use that method will then still run into my problem if they want to use these packages without Cake core. The Cake core problem in i18n needs to be addressed - perhaps by checking if the configuration value exists, and using defaults if not, rather than breaking, or by simply providing a clearer error message or a link to instructions on how to set this required config value when not using the whole framework.

The `I18n` does check and use caching only if relevant class is available. So I think it's a matter of updating [readme](https://github.com/cakephp/i18n/blob/master/README.md) of `cakephp/i18n` stating that proper cache configuration is done.

> Anyway, any chance for a fix being applied today and released, or should I just better revert to an older version?

The next bugfix release for 3.4 is scheduled this weekend. So you can wait for that (assuming the related PR gets merged) or you can revert back to older version :)

**Comment by Swader** [comment]
@ADmad:
> you can revert back to older version :)

Unfortunately, this isn't possible without clumsy hacks because the version constraints are using carets instead of tildae, which means the Validator will always be pulled in as 3.4.9, even if I constrain ORM and Cache to something like `~3.3.1`.

**Comment by ADmad** [comment]
Then sit tight for potentially couple of days for a new release or just setup the expected cache config by referring to the [manual](https://book.cakephp.org/3.0/en/core-libraries/caching.html) :smile:

**Comment by Swader** [comment]
I've hard-constrained Validation to 3.4.3 for now as I needed to get it working asap. This document doesn't seem to make it clear how to configure the Cache for `_cake_core_` outside of the framework's context - could you provide some additional instructions on that page for such use cases? In particular, the Cache Config document references several values that aren't needed or used in my implementation, since I only use the ORM - I'm wondering about the minimal configuration required to make it work.

**Comment by ADmad** [comment]
Refer to the examples shown below the statement "You can also configure Cache engines at runtime". You need to do same for `_cake_core_` key and modify the options as per your needs.

**Comment by ADmad** [comment]
Please hop on to our IRC or slack channels if you need further help.
