### ISSUE TITLE
I want to use environment variables differently.

### ISSUE THREAD

**Issue by dimgraycat** [cakephp/cakephp#10881]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9 and 3.4
* Platform and Target: All.

### What you did

I want to use environment variables differently.
e.g.) test, development, staging, production

app/config/bootstrap.php
```php
Cake::$env = (isset($_SERVER['CAKEPHP_ENV']) ? $_SERVER['CAKEPHP_ENV'] : Cake::DEVELOPMENT);
```
shells of

```
env CAKEPHP_ENV = production ./Console/cake -app ./path/to/app
```

apache settings of

```
SetEnv CAKEPHP_ENV production
```

nginx settings of

```
fastcgi_param CAKEPHP_ENV production;
```

### What happened

I want to respond without rewriting the code itself.

### What you expected to happen

It can be changed so as not to modify the code by adding the environment variables.
You can also organize the configuration directory.

e.g.)
```
app/config/database.php // default

// override default from Cake::$env
app/config/development/database.php
app/config/staging/database.php
app/config/test/database.php
```

Don't you think it is happy?

**Comment by ADmad** [comment]
Environment based configuration can already be easily achieve as illustrated by this [example](https://github.com/cakephp/app/blob/master/config/bootstrap.php#L82). All you have to do is replace the static string `'app_local'` with `'app_' . env('CAKEPHP_ENV')`.

**Comment by dimgraycat** [comment]
Thank you. I understand that it can be obtained from `env()`.
However, if it divides the setting into multiple files (cache.php, database.php, logs.php), it can be overwritten only from `'app_' . env('CAKEPHP_ENV')`.
Isn't a directory for each environment necessary?

**Comment by ADmad** [comment]
If you want to divide the config into multi files do so and update the code to load the files based according to your needs. I fail to see what's prevent you from doing so and what change do you expect in core if any.

**Comment by markstory** [comment]
What you're describing is very similar to rails environments. I am not personally a fan of it as it encourages committing all your configuration for all your environments (including production). Instead I have found that making environment management part of your deployment process or using environment variables and libraries like dotenv to make local development easier to be a simpler and easier to manage practice. There is an open pull request to make the application skeleton [use dotenv by default](https://github.com/cakephp/app/pull/506). Would something like that solve your needs as well?

**Comment by dimgraycat** [comment]
Thank you. I confirmed the open pull request (# 506). Using dotenv seems to be a simpler and easier to practice.
I will wait for it to be merged. :)

**Comment by ADmad** [comment]
Closes this issue as no change in required in core itself.
