### ISSUE TITLE
Lets drop the "PHP" from the title "CakePHP"?

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#10891]
* [x] enhancement

I'm not sure if I'm posting in the right place here, so if not, apologies. This is more so for those marketing Cake.

In regards to branding, how about we drop "PHP" from "CakePHP". "Cake" sounds cleaner, and modern. 

Symfony, Laravel, Cake. See, much nicer.

**Comment by phpnut** [comment]
People still use Cake to discuss it. We are not planning to change the name though.

**Comment by inoas** [comment]
@notoriousturtle no point unless you gift the Cake Software Foundation:
http://cake.com/
http://cake.net/
http://cake.org/

;-)

**Comment by phpnut** [comment]
Still would not happen. CakePHP is a registered trademark in US, UK and other countries. Cake is registered trademark in the US, UK and other countries by another organization.

**Comment by phpnut** [comment]
"Let’s change your name you have had since brith to something because it sounds better..." 
I wouldn't ask you to change your name because I don't like the way it sounds.

**Comment by phpnut** [comment]
I think I will drop PHP from my nick and just go by Nut now.

**Comment by inoas** [comment]
That was my thought ... ;p

**Comment by notoriousturtle** [comment]
@phpnut just a simple marketing suggestion, go easy.
