### ISSUE TITLE
API docs improve for foreign and binding keys

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#10898]
This is a API docs improve.

* CakePHP Version: 3.4.9

At line 560 on `setForeignKey` (https://api.cakephp.org/3.4/source-class-Cake.ORM.Association.html#557-568) should be `@param string|array $key...` instead of `@param string $key...` and also on `setBindingKey` at line 501 (https://api.cakephp.org/3.4/source-class-Cake.ORM.Association.html#497-509).

**Comment by markstory** [comment]
Any chance you could open a pull request to fix up the API docs? They are generated from the source code.
