### ISSUE TITLE
.po files with empty translations cause wrong output

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10900]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: Windows / Linux

### What you did

Generated the translations of the core strings for our app. Some of the translations are left empty in the po file.

### What happened

Ended up with empty translation strings.

I've added the po file to the core tests `tests/test_app/TestApp/Locale/en/cake.po` and ran the tests. 

You can checkout this branch to reproduce the issue: https://github.com/cakephp/cakephp/commits/i18n-translation-issue

I've already spent some time trying to find a proper fix but without success.

![image](https://user-images.githubusercontent.com/162789/28115284-840b3f3c-6704-11e7-8eaa-231d05c781e6.png)

### What you expected to happen

Falling back to the provided translation string of the __() method as default instead of ending up with empty string.

**Comment by markstory** [comment]
Is this the same or different than #10774?

**Comment by burzum** [comment]
@markstory it's not related to the context I think and it still fails, even with these changes.

**Comment by markstory** [comment]
I'll see if I can reproduce this in the existing test suite.

**Comment by markstory** [comment]
Pull request up now.
