### ISSUE TITLE
Extra slash added for folder paths containing ".."

### ISSUE THREAD

**Issue by gs11** [cakephp/cakephp#10908]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 120578920a89c208f87ccb1a756f10702cbbb4c8
* Platform and Target: nginx/debian.

### What you did
Get Folder->path to concatenate it with "/" and the filename to get the absolute path of the file.
This for the folder named "my folder..name".

### What happened
The absolute path becomes "/rootfolder/my folder..name//file"

### What you expected to happen
No additional slash added for the folder .This is normally the case with folders without ".." in the name.

realpath($path) in Folder.php should be changed to not look for .. in an arbitrary position.

**Comment by markstory** [comment]
Can you provide a pull request to fix this? I think using `..` in a directory path is a very uncommon scenario.

**Comment by gs11** [comment]
Sure, I'll look into it. In this case it's a number of folders that contain mp3 files. The folders have been automatically named by the album name from Musicbrainz metadata.
Unfortunately a lot of artists seem to like .. in their album names..

**Comment by dereuromark** [comment]
You should slug your folder names if those are coming from external names.

**Comment by davidyell** [comment]
I often use the dots in path names for things outside of webroot.

```php
echo $this->Html->image('../files/uploads/example.jpg');
```

**Comment by dereuromark** [comment]
What is the status of this issue? Anything to be done?

**Comment by gs11** [comment]
I never got to fix this in the CakePHP code but did a workaround in the project using CakePHP.
Started looking at it but failed to understand the purpose of the arbitrary '..' checking in realpath().
Shouldn't it look for ('..' . DS) instead?
