### ISSUE TITLE
Tree Behaviour - find children, sort order

### ISSUE THREAD

**Issue by hagen00** [cakephp/cakephp#10919]
This is a:

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7

### What you did
Using the Tree Behaviour, I tried to find children, but sorting the results by a database field e.g
`$descendants = $categories->find('children', ['for' => 1])->order(['sort_order' => 'ASC'];`

### What happened
The ordering is being ignored. The query doesn't "break", but the ordering is being ignored. 

### What you expected to happen
I expect the ordering to work. Setting ASC/DESC on sort_order should change the ordering of the object array.

**Comment by AD7six** [comment]
May I ask why your categories table has a sort_order field? That appears to overlap/conflict with `lft` and `rght`.

The result may be what you expect as:

```
$descendants = $categories
    ->order(['sort_order' => 'ASC'])
    ->find('children', ['for' => 1]);
```
OR

```
$descendants = $categories
    ->find('children', ['for' => 1, 'direct' => true])
    ->order(['sort_order' => 'ASC']);
```

**Comment by hagen00** [comment]
I have tried the below and it works. Apologies for the false positive. It would be useful to update the docs. That wasn't obvious to me. 
```
$descendants = $categories
    ->find()
    ->order(['sort_order' => 'ASC'])
    ->find('children', ['for' => 1]);
```
lft/right is different to the sort order. lft/rght handles parent/child relationship. sort_order (in my case), the sort order of the categories. The sort_order field is so that Admin can control via the admin system, the sort order of categories, i.e. in what order they display on the front end (including Children). 

I will leave open in case the docs require updating. Otherwise, this can be closed.

**Comment by lorenzo** [comment]
@hagen00 would you like to send an update to the docs yourself?

**Comment by hagen00** [comment]
I can certainly do that. I haven't done this in the past. How would I best do this? Post a comment in this issue?

**Comment by AD7six** [comment]
> lft/right is different to the sort order.

This isn't true.

The `lft` field value _also_ indicates the tree's sort order - that's why methods like [moveUp](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TreeBehavior.php#L594-L616) and [moveDown](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TreeBehavior.php#L684-L706) exist. Here's [a random reference](https://www.sitepoint.com/hierarchical-data-database-2/) (if it's still unclear, consider the consequence of setting beef's lft/rght values to [15,16] and pork's lft/rght values to [13,14])

I haven't tried `$categories->find('children', ['for' => 1])->order(['sort_order' => 'ASC']);` but if it ignores the sort order (I repeat ` Please show the generated sql query.`) - That probably warrants attention.

**Comment by lorenzo** [comment]
@hagen00 go to the relevant page for the tree behaviour in the docs and then click on the "pencil" button that's on the right side of the page. It will take you to an online editor where you can propose the changes.

Here's the link for you: https://book.cakephp.org/3.0/en/orm/behaviors/tree.html

**Comment by hagen00** [comment]
@AD7six I see, yes, you're right. I won't update the docs with a sort_order example (that would be confusing/wrong). I'll play around with other conditions, e.g ->where() and if that works, I will update the docs.

**Comment by ADmad** [comment]
> lft/rght handles parent/child relationship

No, in MPTT (the data structure that tree behavior uses) the lft/right denote parent child relationship as well as order of sibling nodes. You are creating unnecessary problems for yourself by using MPTT  incorrectly.

**Comment by ADmad** [comment]
For your use case you can use find('threaded') with appropriate conditions and ordering.

**Comment by hagen00** [comment]
Yes, got it, thanks. Should I still update the docs with something like the below?

> If you need to pass conditions you would do it as follows:
 ```
$descendants = $categories
    ->find()
    ->where(['name LIKE' => '%Foo%'])
    ->find('children', ['for' => 1]);

    foreach ($descendants as $category) {
        echo $category->name . "\n";
    }
```

**Comment by hagen00** [comment]
I've submitted a pull request for this (to update the docs).

**Comment by lorenzo** [comment]
Thanks!

**Comment by hagen00** [comment]
@AD7six here is the generated SQL (removed some fields for brevity)

1) working code:
`->find()->order(['sort_order' => 'DESC'])->find('children', ['for' => $answer->id]);`
```
SELECT  ...
FROM 
profile_question_answers ProfileQuestionAnswers 
WHERE (ProfileQuestionAnswers.rght < :c0 AND ProfileQuestionAnswers.lft > :c1) 
ORDER BY sort_order DESC
```

2) not working code
`->find('children', ['for' => $answer->id])->order(['sort_order' => 'DESC']);`
```
SELECT ...
FROM profile_question_answers ProfileQuestionAnswers 
WHERE (ProfileQuestionAnswers.rght < :c0 AND ProfileQuestionAnswers.lft > :c1) 
ORDER BY ProfileQuestionAnswers.lft ASC, sort_order DESC
```

This actually makes it pretty obvious that the problem is mainly me having misused ->order i.e. i should not have used order() to sort a tree. 

I tried the below as a test, which worked: 
`->find('children', ['for' => $answer->id])->where(['title LIKE' => '%2%']);`

This actually means I need to update the docs. This here is not required:

```
// not required. Too verbose, unnecessary
$descendants = $categories
    ->find()
    ->where(['name LIKE' => '%foo%'])
    ->find('children', ['for' => 1]);

// this works and is better
$descendants = $categories
    ->find('children', ['for' => 1])
    ->where(['name LIKE' => '%foo%']);
```

 I will update docs accordingly.
