### ISSUE TITLE
Shell Progress Helper Formatting is Non-Sane

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#10917]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.10
* Platform and Target: Ubuntu 16.04 LTS Zend OPcache v7.1.5-1+deb.sury.org~xenial+2 using fish shell (https://fishshell.com/) version 2.2.

### What you did
```php
    public function test()
    {
        $progress = $this->helper('Progress');
        $progress->init([
            'total' => 10,
        ]);
        $count = 0;
        while($count != 10){
            $count++;
            $progress->increment();
            $progress->draw();
            sleep(1);
        }
    }
```

### What happened
[Here is a screen shot of the console output](https://imgur.com/a/NWkcK), here is text output:

chris@chris:/var/www/obfuscated/obfuscated$ bin/cake AdminMigration test

Welcome to CakePHP v3.4.10 Console
App : src
Path: /var/www/obfuscated/obfuscated/src/
PHP : 7.1.5-1+deb.sury.org~xenial+2
======>                                                                      10%==============>                                                              20%=====================>                                                       30%=============================>                                               40%====================================>                                        50%============================================>                                60%===================================================>                         70%===========================================================>                 80%==================================================================>          90%==========================================================================> 100%chris@chris:/var/www/obfuscated/obfuscated$ 

### What you expected to happen
I don't remember the progress helper operating in this way. Perhaps it is not compatible with the greatest shell ever invented, the Fish Shell?

**Comment by markstory** [comment]
There was a regression in 3.10. The fix is in master and will be in the next release. See #10897
