### ISSUE TITLE
[2.x]Console: Display error message when unknown option is specified

### ISSUE THREAD

**Issue by tenkoma** [cakephp/cakephp#10914]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9
* Platform and Target: Mac OS X

### What you did

I execute `app/Console/cake schema update` with `--dry-run` option(correct options are ``--dry``).

### What happened
Only Usage was displayed.

### What you expected to happen
Display error message "Unknown option \`dry-run\`".

This issue is related to cakephp/docs#5078 .
CakePHP3 shell displays an error message so I want to backport.
I want to make a pull request. In that case, which branch should be based? (`2.x` or `2.next` ?)

**Comment by markstory** [comment]
>  I want to make a pull request. In that case, which branch should be based? (2.x or 2.next ?)

2.next is fine.

**Comment by dereuromark** [comment]
The documentation on the Shell::dispatchShell() method in 3.x also still displays
```
     * ### Usage:
     *
     * With a string command:
     *
     * ```
     * return $this->dispatchShell('schema create DbAcl');
     * ```
     *
     * Avoid using this form if you have string arguments, with spaces in them.
     * The dispatched will be invoked incorrectly. Only use this form for simple
     * command dispatching.
     *
     * With an array command:
     *
     * ```
     * return $this->dispatchShell('schema', 'create', 'i18n', '--dry');
```
Afaik, in 3.x that one doesnt exist anymore, we should probably use an existing example here better.

**Comment by markstory** [comment]
Closing as a pull request is open now.
