### ISSUE TITLE
Add new method Collection::add

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#10918]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.4.0
### What you did

Add an new method **add** to collection class, which will add a single element to the collection.

e.g.

```
      $items =['A', 'B', 'C', 'D'];

      $result = (new Collection($items))->add('E')->toList();
```

Returns results as shown below

```
      ['A','B','C','D','E']
```

This is a very handy method for add a single element. Otherwise, we would have to do:

```
      $items =['A', 'B', 'C', 'D'];

      $result = (new Collection($items))->append(['E'])->toList();
```

Which feels weird.

**Comment by markstory** [comment]
Seems reasonable to me. @lorenzo ?

**Comment by lorenzo** [comment]
Why is `append` weird? I feel it is pretty obvious how it works

**Comment by dereuromark** [comment]
I agree with @lorenzo that append() is way more speaking than just add() 
"add" where exactly, before or after or in the middle? :)

**Comment by dilab** [comment]
@lorenzo because of the intention, I want to add a single element to a collection. Not append a collection to another collection.

**Comment by dereuromark** [comment]
append() by normal definition means appending **one** item to an existing collection.

**Comment by dilab** [comment]
@dereuromark When I look at the "append" method, I thought I could do $collection->append("E").  But it does not.

**Comment by ADmad** [comment]
@dilab The API tells you the argument type the method takes :)

**Comment by dereuromark** [comment]
The current implementation does indeed something rather counterintuitive compared to other languages

    @param array|\Traversable $items Items list.

Since we cannot fix this BC, adding a method for a single item sounds reasonable indeed.

**Comment by dilab** [comment]
@dereuromark yea, that is why I proposed an "add" method to add a single element.

**Comment by saeideng** [comment]
we have a method named `insert()`

**Comment by dilab** [comment]
@saeideng `Insert()` is even more confusing when you simply want to add a single item

**Comment by davidyell** [comment]
To me append, add and insert all mean roughly the same thing. It's just their context which indicates what will happen really.

**Comment by dilab** [comment]
@davidyell I agree with you that you can accomplish the goal using anyone of them. But a good function name and intention goes a long way. Just think about our famous array related functions.

**Comment by davidyell** [comment]
The choice of nomenclature should focus on clarity of intent, I agree, but we're arguing semantics here really. The only angle I could think of is which word translates best for non-english speakers, so non-english speakers can understand the intention of the method.

For the examples given in the ticket, `add` actually doesn't give any intention of placement within the collection as you've stated. Whereas `append` means adding to the end of, so it actually has much clearer intent than `add`.

**Comment by dilab** [comment]
@davidyell agreed. So my final proposal is `appendItem` to append an **individual** item to the **end** of the collection

**Comment by davidyell** [comment]
Append would imply there is also a Prepend method to add items to the beginning of a collection.

**Comment by lorenzo** [comment]
I could be named`appendOne`

**Comment by robertpustulka** [comment]
Do we have a `prepend()` method?

**Comment by dilab** [comment]
@davidyell yes. but I do not see the problems of having a bunch of useful methods

**Comment by lorenzo** [comment]
@robertpustulka we don't but we could have it

**Comment by HumanG33k** [comment]
I don’t know if my comment is usefull but this is two examples of collection : 
 http://www.cplusplus.com/reference/vector/vector/
 https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html

If can help.

**Comment by rrd108** [comment]
My problem with append is that overwrites keys. I would like to add a collection to the end of another, but it seems there is not an easy way to do it.

**Comment by xaphalanx** [comment]
I created a pr for this milestone. There seems to be a lot of opinions about how to implement this. Looking forward to your feedback.

**Comment by InfosecGene** [comment]
@markstory  We can close this issue. We did appendItem and PrependItem a while back.
