### ISSUE TITLE
Bug or (docs are wrong) for SQL Server and ordering by synthetic columns

### ISSUE THREAD

**Issue by MCF** [cakephp/cakephp#10944]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

PHP 7.2
CakePHP 3.4.11
Windows 7
SQL Server 2008

I'm trying to paginate a query result set that has a synthetic (aka calculated) column.  But the ordering will not work.  AFAIK I am following the proper steps, but it appears that SQL Server will not accept ordering by synthetic columns with the ordering strategy that Cake and it's ORM + Query builder is using.

The code looks soomething like the following.

Model has a custom finder:

```PHP
public function findWithCounts(Query $query, array $options)
{
    return $query
        ->select(['number_applied' => $query->func()->count('DpsComponents.id')])
}
```

The pagination configuration is specifying ```number_applied``` in the whitelist.  But sorting by that column gives the following SQL:

```SQL
FROM 
  (
    SELECT 
      (
        COUNT(DpsComponents.id)
      ) AS [number_applied], 
      (
        ROW_NUMBER() OVER (
          ORDER BY 
             number_applied asc
        )
      ) AS [_cake_page_rownum_] 
    FROM 
      tbl_dps Dps 
      LEFT JOIN tbl_dps_components DpsComponents ON Dps.id = (DpsComponents.dp_id) 
  ) _cake_paging_ 
WHERE 
  _cake_paging_._cake_page_rownum_ <= 25
```

I've chopped the actual code down to show the relevant parts - apologies if there are unrelated syntax errors as a result.  The actual example is quite large.

The core of the problem appears to be that SQL server will not accept aliases in the  ```ROW_NUMBER() OVER``` clause as outlined here:

https://stackoverflow.com/questions/7297609/cannot-use-alias-in-row-number-over-in-sql-server

One possible solution to get the SQL to run is to change the ROW_NUMBER clause to this:

```SQL
      (
        ROW_NUMBER() OVER (
          ORDER BY 
             COUNT(DpsComponents.id) asc
        )
      ) AS [_cake_page_rownum_] 
```

I have not tried this workaround with Pagination sort links because I have other synthetic columms that are the result of much more complicated calculations and am doubtfull I will get them all to work.

So I guess I had a couple of questions:

1. Am I doing something wrong with my approach?
1. If no, is this a CakePHP bug with the SQL server integration?
1. If it is a bug are there any workarounds?  Back to the messy custom pagination I was using with CakePHP 2 ... (is that still possible with CakePHP3?).  Or is it possible to get Cake pagination to use the calculation in the order by clause rather than the alias?

**Comment by markstory** [comment]
> Am I doing something wrong with my approach?

No I don't think so.

> If no, is this a CakePHP bug with the SQL server integration?

Sounds likely. To be honest I don't think any of us on the core team are frequent SQLServer users, and likely have more simple usage than what you're attempting.

> If it is a bug are there any workarounds? 

You could patch/fix the issue you're running into. I'm happy to help with the creation of a patch and updating the relevant tests. The code that transforms a basic query into the required SQLServer query [can be found here](https://github.com/cakephp/cakephp/blob/master/src/Database/Dialect/SqlserverDialectTrait.php#L102-L137). The existing code probably needs to be expanded to inspect the order field and check if it is a simple column, or a complex expression and adjust the generated `UnaryExpression` accordingly.

**Comment by MCF** [comment]
I guess the real lesson here is that SQL sever 2008 is getting old.. Oh well, I'm stuck with it for the foreseeable future.

Thanks for the link to the relevant code.  I'll have a go at fixing it.  Give me a couple of days.

**Comment by MCF** [comment]
@markstory can you please review the pull request I have put together when you have a chance.  It works with all of my testing, but I'm not sure if my approach is the best.

**Comment by markstory** [comment]
Will do. Closing as there is a pull request now.
