### ISSUE TITLE
BETWEEN conditions in not standard order

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#10940]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.11
* Platform and Target: WAMP

### What you did
I would like use `BETWEEN` conditions, but not standard order.
When I wrote standard I mean something like this:
`...field BETWEEN value1 AND value2...`
I would like using like this
`...(value1 BETWEEN field1 AND field2) OR (value2 BETWEEN field1 AND field2)...`

Simlar queries are described here https://stackoverflow.com/questions/2545947/check-overlap-of-date-ranges-in-mysql

My query:
```
$events = $this->find()->select([
    $this->getAlias() . '.' . $this->getPrimaryKey()
])->orWhere(function ($where) use($hour_start) {
    return $where->between($hour_start, 'hour_start', 'hour_end');
})->orWhere(function ($where) use($hour_end) {
    return $where->between($hour_end, 'hour_start', 'hour_end');
})->orWhere([
    'hour_start <=' => $hour_start,
    'hour_end >=' => $hour_end,
]);
```

### What happened
```
SELECT ... WHERE (
    (
        15:00:00 BETWEEN :c0 AND :c1 
    OR 
        17:00:00 BETWEEN :c2 AND :c3 
    OR 
        hour_start <=15:00:00 OR hour_end >=17:00:00
) 
```

### What you expected to happen
```
SELECT ... WHERE (
        '15:00:00' BETWEEN hour_start AND hour_end  
    OR 
        '17:00:00' BETWEEN hour_start AND hour_end  
    OR 
        hour_start <= '15:00:00' OR hour_end >= '17:00:00'
) 
```

It possible, to reproduce query like above?

**Comment by lorenzo** [comment]
@kicaj do you mind asking the question in the IRC channel or in Slack? Let's keep help requests in the issue tracker at a minimum, please :)

**Comment by lorenzo** [comment]
Just to make it clear for anyone reading this:

The order or most (all?) query functions is `(field, value1, value2, value3..)` The field is always first.. like in the expression `field BETWEB value1 and value2` the field is also first
