### ISSUE TITLE
[RFC] Getters/setters for Controller request and response objects.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#10946]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.0

Controller `$this->request` and `$this->response` properties are still public.

I'm wondering if we should deprecate the direct access and add getters and setters instead?

**Comment by robertpustulka** [comment]
BTW there are number of public properties stil in use. Like `$this->name` and  `$this->plugin`  which could be retrieved from request params.

**Comment by inoas** [comment]
Agreed, either we should only have public properties or only getters/setters, never both!

**Comment by saeideng** [comment]
your means is `$this->request` Or `$this->request->methodName` ?

**Comment by markstory** [comment]
We could make the properties protected as well 😄

**Comment by robertpustulka** [comment]
But for BC these should be accessible using `__get` and `__set`?

**Comment by inoas** [comment]
Just deprecate them now and remove them in 4.x without adding more code @ `__get`?

**Comment by markstory** [comment]
Removing these properties is going to have wide sweeping consequences as these are the most used properties on controllers, and changing them will impact all controllers and components. It will also introduce inconsistencies with `View`. Perhaps we need to think about these properties more holistically?

**Comment by robertpustulka** [comment]
I'm afraid we can't make `$request` and `$response` protected and use `__get`/`__set` instead because of `Indirect modification of overloaded property Controller::$request has no effect` error.

Can we mark those deprecated in 3.5 and change the visibilty in 4.0?

**Comment by chinpei215** [comment]
I think you can avoid the error if you change `__get()` to return reference. I was planning to change `__get()` in 2.x, but the last bus had already gone 😭

**Comment by robertpustulka** [comment]
Thanks, I'll try.

**Comment by saeideng** [comment]
we can validate that on `__set()`

**Comment by robertpustulka** [comment]
PR is open.
