### ISSUE TITLE
add `_name` to request object  (for using  it on Paginator , ... )

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#10950]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0

### What you did
detect action by `_name` of routes on across app specially on view 

### How
add `_name` to request object  like `_matchedRoute`

**Comment by markstory** [comment]
How do you see `_name` being used?

**Comment by lorenzo** [comment]
It could be displayed in debugkit

**Comment by markstory** [comment]
Perhaps we should find a way to get more information about the currently matched route into debugkit?

**Comment by saeideng** [comment]
> It could be displayed in debugkit

debugkit use directly `routes` and `foreach()` for showing

**Comment by saeideng** [comment]
> Perhaps we should find a way to get more information about the currently matched route into debugkit?

what debugkit?
we need use this in our programs :)

**Comment by markstory** [comment]
@saeideng What do you use it for?

**Comment by saeideng** [comment]
> How do you see _name being used?

for example :
for detect special actions for add/show/modify view/layout

**Comment by saeideng** [comment]
```
		$this->request->params['lang_params']=
		[
			'_name'=>'ads_show',
		];
```
now i use this form for sending data

**Comment by markstory** [comment]
How does that connect with the Route names though?

**Comment by saeideng** [comment]
`$this->request->getParam('_named');`

but I think we now already below form for 3.5??
`$this->request->route()->getName();`

**Comment by markstory** [comment]
Requests don't have access to the matched route. If we're interested in having more route state available on the request, then we could use an attribute, but I'd like to better understand the use cases for that data.

**Comment by saeideng** [comment]
1)i use this info for display `lang` select but just for especial action
2)now we able to detect all data (passed/controller/action) except `_name` 
3)for detect especial action we need now check both `controller` and `action` but `_name` is fast 
4)with `$this->request->route()` we can deprecate all of params (`controller` ,`action`,passed)
5).... as soon :smile:

**Comment by markstory** [comment]
> with $this->request->route() we can deprecate all of params (controller ,action,passed)

I don't think we can. Route instances don't have complete information on what was in the URL.

**Comment by saeideng** [comment]
@markstory 
if you define a route by `_name`
and you want use Paginator for that action you can not use it without defination `$this->Paginator->options(['url'=>[`
like 
```

**Comment by markstory** [comment]
Named routes can still be matched through reverse routing though.

**Comment by saeideng** [comment]
`Router::reverseToArray()`?

**Comment by saeideng** [comment]
no
is not good for everywhere 
`$this->request->route()->getNamed()` is good :smile:

**Comment by markstory** [comment]
And `Request::route()` would return the currently matched route?

**Comment by saeideng** [comment]
yes if you agree

**Comment by EliasDeVos** [comment]
Hi, i am wondering what the plans are for this issue ? will the _name parameter be made available in Router::route() ?
i would need to be able to find the _name of the current route from the request object

**Comment by dereuromark** [comment]
You could make a PR with your suggested changes. That might be quickest to get a resolution here.

**Comment by EliasDeVos** [comment]
https://github.com/cakephp/cakephp/issues/11595
Yes i tried to explain it here.
But i am not sure if the way i want to fix it is the correct way.
I will try to make a merge request for Request::route() and see how that goes

**Comment by saeideng** [comment]
@markstory 
can we add object into cake v 3.6
in this case , how we able to use route classes ?
https://github.com/cakephp/cakephp/blob/7b86c0649c68718492bd7ae44be7461248715678/src/Routing/Route/Route.php#L426

**Comment by saeideng** [comment]
>What use cases did you have in mind that require the route object @saeideng?

to avoid to using `reverseToArray()`
I feel  `reverseToArray()` is not standard method for us 

even I'm ok with array 
`_route` key (containing array of route option )  just like the `pass`  in the request object 
(for cake 4.0)
...
https://github.com/cakephp/cakephp/blob/83815ac4912656eb9e724e179bbe1dc6440e3359/src/Routing/Router.php#L738-L749

**Comment by markstory** [comment]
@saeideng Do you think #11596 will help address this issue partially or completely?

**Comment by saeideng** [comment]
partially yes 
and we can close this now
until finding a good place for matched routes option in future
