### ISSUE TITLE
Empty translations show as empty strings

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#10954]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.11

Strings with empty translations show as empty strings. It seems to be caused by PR #10597 since it adds a context parameter to all translations and the Translator class doesn't test for empty translations when there's a context parameter in the translation message.

I'm adding a PR with a test in short.

While doing this I realized there was an error in another test that checks empty translations with plurals although the test is succesful with or without the fix anyway.

While investigating this problem I've realized it's a waste of memory storing all those empty translations as arrays with empty contexts. I think the PO parser should discard those translations to save memory.

Also, while gettext tools ignore fuzzy translations, the PO parser does not. This can cause problems since wrong/incomplete translations may appear where they aren't supposed to. I've found a MO parser and I think using it should solve all these problems but I don't know how to select it or if that's discouraged for some reason.

**Comment by robertpustulka** [comment]
PR is open
