### ISSUE TITLE
Ability to use OrmCache build/clear in non-shell contexts

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#10967]
This is a (multiple allowed):

* [x] enhancement

* CakePHP Version: 3.6

### What you did

Tried importing OrmCache shell functions to run programmatically.

### What happened

Unable to call OrmCache shell functions natively creating a shell instance.

### What you expected to happen

Ability to import OrmCache shell functions via a library or similar.

### Why is this useful?

You might wish to clear orm cache and rebuild it for use within a migration.

**Comment by robertpustulka** [comment]
https://github.com/cakephp/cakephp/issues/10202#issuecomment-299044069 here we go again.

This comment and discussion should be seperated into it's own issue @dereuromark

**Comment by markstory** [comment]
@robertpustulka Could we not refactor the shell logic out as people have a need to reuse it elsewhere?  While there is probably a larger discussion to be had around if we want to provide framework hooks for these 'service' classes. I think we could start small with individual shells for which there is a reuse case already known.

**Comment by robertpustulka** [comment]
@markstory right, we should refactor the logic. But should we settle on a pattern for this first that we don't have to refactor the logic twice?

**Comment by markstory** [comment]
@robertpustulka I'm not sure there is going to be a pattern to build though.

**Comment by burzum** [comment]
@robertpustulka we could use events or have something like a ConsoleAware trait that implement a getter and setter for the console i/o objects?

**Comment by markstory** [comment]
> We could use an event there but I think that's to heavy. Another option would be to implement isClearing() and isBuilding() and getCurrentTable() ...

I like this approach it enables integration in various contexts as it is unaware of the output environment (cli/http).

**Comment by burzum** [comment]
@markstory I've started the work here https://github.com/cakephp/cakephp/tree/3.next-orm-cache It's basically done just the verbose message output is missing.

**Comment by markstory** [comment]
Looks good. Perhaps `build()` can return the list of tables that had their cache rebuilt?

**Comment by burzum** [comment]
@markstory @josegonzalez can we close this as the PR has been merged? Does it fulfil all your requirements?

**Comment by markstory** [comment]
I think we're good here.
