### ISSUE TITLE
Created and load plugin Plugin::load('MyCompany/Shop', ['bootstrap' => false, 'routes' => true]);

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#10966]
This is a (multiple allowed):

* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.4
* Platform and Target: XAMP PHP 7.1 32bit, Windows 10 64bit

### What you did
Created by console plugin example.
`.\bin\cake bake plugin EOM/shop`
`.\bin\cake bake controller hola -p EOM/shop`

//change ok bootstrap.php
`Plugin::load('EOM/shop', ['bootstrap' => false, 'routes' => true]);`

Router Plugin:
```
Router::plugin(
    'EOM/shop',
    ['path' => '/e-o-m/shop'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);
```
Print: [ DebugKit](http://s3.postimg.org/e72yqeer7/print_de_pantalla_12.jpg)

Print: [My Tree folder in Plugins](http://s3.postimg.org/9mgsbgv1v/print_de_pantalla_13.jpg)

### What happened

Error in browser: **"An Internal Server Error Occurred"**

Out file **error.log**
```
2017-07-30 21:33:13 Error: [Cake\Core\Exception\MissingPluginException] Plugin EOM/Shop could not be found.
Exception Attributes: array (
  'plugin' => 'EOM/Shop',
)
Request URL: /e-o-m/shop/hola
Stack Trace:
#0 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Core\App.php(190): Cake\Core\Plugin::classPath('EOM/Shop')
#1 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\View\View.php(1269): Cake\Core\App::path('Template', 'EOM/Shop')
#2 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\View\View.php(1087): Cake\View\View->_paths('EOM/Shop')
#3 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\View\View.php(592): Cake\View\View->_getViewFileName('Error\\error500')
#4 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(364): Cake\View\View->render('error500', 'error')
#5 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(341): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#6 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(200): Cake\Error\ExceptionRenderer->_outputMessage('missingControll...')
#7 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(110): Cake\Error\ExceptionRenderer->render()
#8 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(94): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(Cake\Routing\Exception\MissingControllerException), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 D:\www\app.aptitud.local\www\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 D:\www\app.aptitud.local\www\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}
```

### What you expected to happen
Load ok my class my plugin subfolder /app/plugins/EOM/Shop/*** or /app/plugins/MyCompany/Shop/***

**Comment by EOM** [comment]
Hi,
Detect problem is for:

**Generato Fix:**
`.\bin\cake bake plugin EOM/shop`
`.\bin\cake bake controller hola -p EOM/shop`

**Generato Ok:**
`.\bin\cake bake plugin EOM/Shop`
`.\bin\cake bake controller Hola -p EOM/Shop`

It is possible that the console, **"bin\cake bake plugin"** and **"bin\cake bake controller namedemo -p nAME/myplugin"** detect and resolve the file names so that the first letter was not capitalized, . ?
**Example:**
When it is **"bin\cake bake plugin nAME/myplugin"** change automatic and create the folder in this correct way **"/app/plugins/NAME/Myplugin"**
Or **"bin\cake bake controller namedemo -p nAME/myplugin"** change automatic and create controller **"bin\cake bake controller namedemo -p nAME/myplugin"** correct in **"/app/plugins/NAME/Myplugin/Controller/NamedemoController.php"**

**Comment by markstory** [comment]
This issue was moved to cakephp/bake#351
