### ISSUE TITLE
Query Builder orMatching needed

### ISSUE THREAD

**Issue by hagen00** [cakephp/cakephp#10978]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.12

* Refers to: https://github.com/cakephp/cakephp/issues/5721#issuecomment-318170362
* This is related: https://stackoverflow.com/questions/27288957/cakephp-3-0-multiple-matching-conditions

### What you did
There are use cases where one would require the equivalent of orMatching(). Consider the following models: 
articles >-< tags (many to many)
articles >-< categories (many to many)

I would want to write a query that gets all articles that match tag "foo" OR category "bar". 

```
$query = $this->Articles->find();

$query->matching('Tags', function ($q) {
	return $q->where(['Tags.title' => 'tag does not exist']);
});

// orMatching would be nice? I want to get all articles that match either a tag OR a category		
$query->matching('Categories', function ($q) {
	return $q->where(['Categories.title' => 'category exists']);
});

// empty array is returned
debug($query->toArray());
```

### What happened
If one matching condition fails, then no data is returned. This is ok most of the time ("andMatching" but there are cases for "orMatching")

### What you expected to happen
```
// Something like this would be nice i.e. orMatching:
$query->orMatching('Categories', function ($q) {
	return $q->where(['Categories.title' => 'category exists']);
});
```

**Comment by hagen00** [comment]
3.4.12

**Comment by markstory** [comment]
What would the SQL you're expecting to be generated look like?

**Comment by hagen00** [comment]
The below is what I'm trying to do. Quite possibly matching is not the right approach? The OR below is what I mean by orMatching
```
SELECT * FROM articles a
JOIN articles_tags `at` ON a.id = `at`.article_id
JOIN tags t on `at`.tag_id = t.id
JOIN articles_categories ac ON a.id = ac.article_id
JOIN categories c ON ac.category_id = c.id

WHERE c.title = 'cat 1' OR t.title = 'tag 2'
```
I realize this would cause duplicates article ids, so one would have to add (manually, via distinct())
GROUP BY a.id

**Comment by inoas** [comment]
So just do innerJoinWith and then orWhere(['identifier' => 'vaule'], ['identifier2' => 'vaule2'] ?

**Comment by markstory** [comment]
I think you can do what you want with matching() and where() like @inoas said.

**Comment by hagen00** [comment]
I can confirm that the below works. 

```
$query->innerJoinWith('Tags', function ($q) {
	return $q->orWhere(['Tags.title' => 'tag 1']);
});
		
$query->innerJoinWith('Categories', function ($q) {
	return $q->orWhere(['Categories.title' => 'cat 2']);
});
		
$query->distinct('Articles.id');
```

Sorry everyone to log this as an issue :(, but thanks for the help!
