### ISSUE TITLE
Add a setErrors() method to the Form class

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#10971]
This is a (multiple allowed):

* [x] enhancement

* CakePHP Version: 3.x

### What you did

Tried to set form errors on a form using `setErrors`

### What happened

Missing method exception.

### What you expected to happen

 It works.

### Why is this useful?

If you are attempting to persist errors between redirects, you can very easily apply a set of errors to an entity, but cannot do so to a Form instance without a custom setErrors method. There is an `errors` method which only returns it, unlike in the `EntityInterface` which can do setting and getting of an error or set of errors.

**Comment by jorisvaesen** [comment]
Although the method seems convenient, can't this be accomplished by setting the context of the form to `EntityContext`?

**Comment by markstory** [comment]
I don't think Form objects use the EntityContext. They should use the `FormContext` instead.

**Comment by markstory** [comment]
Pull request is open now.
