### ISSUE TITLE
Remove cookie from Response object

### ISSUE THREAD

**Issue by jorisvaesen** [cakephp/cakephp#10975]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0-RC1

### What you did
I wanted to delete a cookie using the new CookieCollection.

### What happened
```
$cookies = $this->request->getCookieCollection();
if ($cookies->has('remember_me')) {
    $cookies = $cookies->remove('remember_me');
}
$this->response = $this->response->withCookieCollection($cookies);
```

Although the method exists in the ServerRequest object, the  `withCookieCollection()` method doesn't seem to exist in the Response object yet.

### What you expected to happen
The response with the modified cookie collection

**Comment by markstory** [comment]
It might be easier to use if the method was `$response->withoutCookie('remember_me');`

**Comment by jorisvaesen** [comment]
Indeed pretty straight forward.

**Comment by cleptric** [comment]
Thanks for taking care of this @jorisvaesen 🙂 
Closing as we have a PR.
