### ISSUE TITLE
Slow DboSource::truncate

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10979]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.9.9.
* Platform and Target: MySQL, Apache, Linux.

### What you did
Run unit tests for a single controller with 73 fixtures and 35 tests using xdebug to generate cachegrind file.

### What happened
Cachegrind reports that `DboSource::truncate` method is quite slow using 28% of tests time.

![screenshot from 2017-08-02 11 27 59](https://user-images.githubusercontent.com/3830106/28867414-5ad8e150-7776-11e7-9825-7e44e6613241.png)

### What you expected to happen
I would expect that truncating tables would not be so slow. Is there a good explanation of that or a way to improve the performance of truncating tables?

**Comment by dereuromark** [comment]
First of all: truncating like this is usually more a debugging tool and not something for productive use.
It is a good way of resetting some local things, but for production, one would usually use the DB directly :)

Second: Did you do this with debug 0 and cache enabled?
Because otherwise your results are void. Only when using production cache for ORM you can actually the the relevant things going on :)
And even then this method really is not relevant IMO (and also always O:1 and a non loop operation which makes it insignificant).

**Comment by bancer** [comment]
Yes, this is not for production. The problem is that unit tests are quite slow. Using 1/4 of unit tests time to truncate tables looks odd.

**Comment by dereuromark** [comment]
Then don't truncate like this :) Use SQL command for it directly.
But I would still consider this a non-issue.

**Comment by bancer** [comment]
Well, it's not our code that calls `truncate()`. It's called by CakePHP in CakeFixtureManager.

**Comment by AD7six** [comment]
@bancer I think you're going to find it'ss not that `truncate` is slow, it's that calling it 7829 times simply adds up. I doubt making truncate faster (even if that were possible) would make much difference.

Therefore:

 * Is it real-world slow, or just the % that caught your attention? how many ms is 27.37%?
 * Is truncate being called unnecessarily by fixture logic?
 * Are fixtures being over used?

Probably worth mentioning that (over)reliance on fixtures leads to unit tests that aren't actually unit tests.

**Comment by bancer** [comment]
> Is it real-world slow, or just the % that caught your attention? how many ms is 27.37%?

I takes 2 minutes to run those tests. 28% from that is 34 sec, so it approx. 34/7829 = 0.004 sec per call to `truncate`. So it seems you are right, @AD7six. It sums up. Maybe it would be faser to drop the test database instead of truncating all tables? I guess one drop per test method would be faster than truncating every table.

> Is truncate being called unnecessarily by fixture logic?

That seems to be also true. `truncate` is called in both `CakeFixtureManager::load` and `CakeFixtureManager::unload`. Although I can understand why it was done this way. Maybe it would be better to truncate only in `CakeFixtureManager::load` and somewhere like in `tearDownAfterClass`?

**Comment by bancer** [comment]
I think `$fixture->truncate($db);` should be moved from `CakeFixtureManager::load` to `CakeFixtureManager::_setupTable` and should be executed only if `$test->dropTables` is `false`.
```
$db->begin();
$this->_setupTable($fixture, $db, $test->dropTables);
$fixture->truncate($db);
$fixture->insert($db);
$db->commit();
```
There is no reason to call `$fixture->truncate($db);` if `$test->dropTables` is true. There is no reason to truncate tables if they have been just dropped.
