### ISSUE TITLE
Error: Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by testmode123** [cakephp/cakephp#10988]
Error: Cannot use 'String' as class name as it is reserved	
File: C:\xampp\htdocs\cakeblog\lib\Cake\Utility\String.php	
Line: 24

**Comment by testmode123** [comment]
I m using cakephp 2.x and i have also working on blog in cakephp 2.x after long time but today,
I working this project then this error show.... ??
Please give me solution for this error.

**Comment by ADmad** [comment]
"String" is a reserved name in PHP 7.0 and hence the `String` class in Cake cannot be used on PHP 7.0. Upgrade to latest 2.x and use `CakeText` instead.

**Comment by govindsom** [comment]
how to upgrade cake php?

**Comment by mnasirkhan** [comment]
easiest way SET your PHP version 5.6 via .htaccess
for example just host offers

AddHandler application/x-httpd-phpbeta .php
