### ISSUE TITLE
expecting `'&'' or `"variable (T_VARIABLE)"'

### ISSUE THREAD

**Issue by origamifreak2** [cakephp/cakephp#10983]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: XAMPP 7.1.4, Mac OS X El Capitan 10.11.5

### What you did
Ran following code from terminal

    bin/cake

### What happened
Received Following error

    Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in /Users/teammember/Sites/prototype.simembers.com/public_html/vendor/cakephp/cakephp/src/I18n/functions.php on line 26

### What you expected to happen
Expected to see list of various available commands and other info about cakephp.

### Notes
I put the following code at the top of the index function of one of my controllers to check the cakephp version and php version I'm using.

    debug('Cake Version: '.Configure::version());
    debug('PHP Version: '.phpversion());
    die();

This is the response

    /src/Controller/LocationMonthlyStatsController.php (line 34)
    'Cake Version: 3.4.7'
    /src/Controller/LocationMonthlyStatsController.php (line 35)
    'PHP Version: 7.1.4'

I've read several places about conflicts with different versions of cakephp and php, but I believe from what I've read that what I have should work together.

**Comment by ADmad** [comment]
You be having different version of PHP for webserver and CLI. Use `php -v` on command line and ensure it's PHP 5.6 or above.

**Comment by origamifreak2** [comment]
Yes that was the issue. Terminal was using old version of php. I changed it to use the php in my /Applications/XAMPP folder.
