### ISSUE TITLE
Discrepancy in the Cookie's default path

### ISSUE THREAD

**Issue by jorisvaesen** [cakephp/cakephp#10982]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0-RC1

The default `path` parameters differs between the Response's `withCookie()` function and the new Cookie object.

`Response::withCookie()`
https://github.com/cakephp/cakephp/blob/3.next/src/Http/Response.php#L2020

Cookie constructor
https://github.com/cakephp/cakephp/blob/3.next/src/Http/Cookie/Cookie.php#L128

This means that cookies differ when used like this:
```php
$response->withCookie(new Cookie('test')); // path = ''
$response->withCookie('test'); // path = '/'
```

**Comment by ADmad** [comment]
There should also be a convenient way to specify default path for cookies. The CookieComponent uses `$request->webroot` as default path. There be an easy way to achieve same with new cookies implementation.

**Comment by jorisvaesen** [comment]
@ADmad I agree, but how do we get this value as default in the Response and Cookie object?

**Comment by markstory** [comment]
If you're making a cookie object you are responsible for making it properly. I don't think the Response should be changing the shape of cookie objects it is given.

**Comment by markstory** [comment]
@ADmad Doesn't `withCookie('foo', 'bar')` make it 'easy' enough? The `withCookie()` method should probably default cookie paths to `$this->webroot` though.

**Comment by ADmad** [comment]
@markstory If `withCookie()` defaults to using `$request->webroot` then it's good enough.

**Comment by markstory** [comment]
Ok I can make that change.

**Comment by markstory** [comment]
I was thinking about this some more, and I don't know how we get the `request->webroot` value into the response and then into the cookies.

**Comment by jorisvaesen** [comment]
Was thinking exactly the same (as my comment above). Having the request object in the response object just to get the webroot to apply to a cookie doesn't seem like an elegant solution.

**Comment by markstory** [comment]
No. The current behavior is also consistent with how `Response::cookie()` has worked for a number of years.

**Comment by Schlaefer** [comment]
Would it be possible to move the Cookie object to array conversion from the ResponseEmitter to a  middleware and access the request there?

**Comment by markstory** [comment]
That is an option. Wouldn't that require everyone to change their applications around?

**Comment by Schlaefer** [comment]
> Wouldn't that require everyone to change their applications around?

Yes. Should probably go on a consideration list for a breaking release.

I think whatever is done now may raise some issues. Esp. with `->request->getCookieCollection()` where it's possible to read cookies with a path but `Cookie::getPath` is going to return empty.

What I see is:

- Use webroot
	- pro: expected app behaviour, security
	- con: non-trivial implementation
- Use empty
	- pro: expected PHP+HTTP behavior (no path set equals current path), simple
	- con: unexpected behavior when accessed from different paths
- Use root "/"
	- pro: consistent, simple
	- con: security

I don't know. I probably tend to root if webroot isn't available. It's a good non-breaking starting point and when people flesh out their app they probably customise their cookies anyway.

**Comment by davidyell** [comment]
I would be in favour of removing the shortcut array processing from the `withCookie()` method in the Response object, and type hinting the method with `Cookie`, although this would be a breaking change.

After all the Response object shouldn't know how to make Cookies.

https://github.com/cakephp/cakephp/blob/master/src/Http/Response.php#L2204

To me it would be nicer as `public function withCookie(Cookie $cookie)`

**Comment by markstory** [comment]
The default array value for `withCookie()` defaults to `/` which was one of the proposed options. The original issue was that `Cookie` and `withCookie()` had inconsistent defaults.

**Comment by davidyell** [comment]
My issue is that it's not possible to change the path either, when setting a Cookie to the response using the array notation and `withCookie()` which is why I think we should not be duplicating this functionality, and `withCookie()` should no longer take an array but a `Cookie` object.

**Comment by markstory** [comment]
Taking away the behavior isn't something we can do inside of 3.x though. I'm a bit reluctant to deprecate behavior that is brand new as well. We could update the documentation to recommend using the object approach. That would minimize the number of folks effected down the road.

**Comment by davidyell** [comment]
Better to deprecate this now than carry it forward into 4.0 in my opinion. There are a few areas in the framework like this, where solid type hinting and return types with PHP 7 will bring huge benefits with the 4.0 release.

Using the deprecations which people are already getting used to to lay that ground work in paramount to me.

If all else, releasing 4.0 with full PHP 7 support, type hinting, proper SOLID principles and such will be a key selling point for the framework. I can imagine the derision if 4.0 is released as the new shiny version, and still has these types of backwards SOLID breaking methods included.

**Comment by markstory** [comment]
Any chance you want to put together a pull request for 3.next @davidyell ?

**Comment by davidyell** [comment]
@markstory Sure thing, I can do that. What is the objective of the PR? To deprecate the Response::withCookie array part of the method?

**Comment by markstory** [comment]
@davidyell That sounds great.

**Comment by markstory** [comment]
Closing as #12198 will solve this by normalizing all cookie operations to use the `Cookie` object.
