### ISSUE TITLE
RFC: Add verbosity levels for the shells

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10984]
Can we implement verbosity levels like whatever shell is powering phpunit for example? You get a different amount of detail depending on how many `v` you use:

* `-v`
* `-vv`
* `-vvv`

`-v` might be already taken by some shells, how about adding `--verbosity-level 2` or something like that?

I consider this as pretty useful when you have shells that run over a lot of data for example. If you get notices or errors the trace completely clutters your screen. Sure I could check the log and everything but it's just not nice to see that mess. I would prefer to get a clear error message, just the message of an exception that happened for example.

Here is a trait we use in our project to cover that in some of our shells:

```php
<?php
namespace App\Shell;
 
use Exception;
 
trait PrettyExceptionRenderTrait {
 
    /**
     * Prints an exception in a pretty way
     *
     * @param \Exception $exception
     * @param bool $quit Quit or not?
     * @return void
     */
    public function printException(Exception $exception, $quit = true) {
        if ($this->param('verbose') === true) {
            $this->out($exception->getTraceAsString());
        }
        $this->err('<error>Error:</error> L' . $exception->getLine() . ' ' . $exception->getFile());
        if ($quit === true) {
            $this->error($exception->getMessage());
        }
        $this->err('<error>Error: ' . $exception->getMessage() . '</error>');
    }
 }
```

**Comment by markstory** [comment]
We already have 3 output levels (quiet, normal, verbose) how many additional levels of verbosity would you suggest we add? Personally I lean towards -vv instead of --verbosity-level as -vv is more common in cli tools and by default -v enables verbose mode.

**Comment by burzum** [comment]
@markstory I'm OK with the three levels, just haven't seen them under their actual names. https://book.cakephp.org/3.0/en/console-and-shells.html#console-output-levels I think we can close this :) My fault.
