### ISSUE TITLE
Csrf token in request params is lost if CsrfProtectionMiddleware is added before RoutingMiddleware.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#10989]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.0 RC1
* Platform and Target: All

### What you did
Added `CsrfProtectionMiddleware` to middleware queue followed by `RoutingMiddleware`.

### What happened
The CSRF token set by  `CsrfProtectionMiddleware` to `$request->params['_csrfToken']` was lost since `RoutingMiddleware` completely resets `$request->params`.

### What you expected to happen
I expected the CSRF token to be preserved in `$request->params`.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
