### ISSUE TITLE
Query::deselect() method

### ISSUE THREAD

**Issue by berrygoudswaard** [cakephp/cakephp#10992]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: > 3.x

### Problem
Sometimes I want the select all columns from a table, except for a few. Right now I am using the Query::select() method to select all the columns I want, but it would be convenient to have a Query::deselect()

### Proposal
By default CakePHP uses the autoField trigger to select all columns.
When a developer calls the Query::select, it will that disable autoField and select only the fields that are passed to the Query::select() method.

My idea is to implement a Query::deselect, that will use the autoFields functionality but removes a few columns from the columns-list.

The following example will select all columns of the articles table, except 'modified' and 'created'
```php
$query = $articles
    ->find()
    ->deselect(['modified', 'created'])
    ->where(['id !=' => 1])
    ->order(['created' => 'DESC']);
```

I could create a PR for this, but I would like to know if this functionality will be accepted in the CakePHP core.

**Comment by lorenzo** [comment]
I'm not sure that it is a method that naturally belongs in the `Query` object, but it can maybe be a helper function.

for example this should work:

```php
$query = $articles
    ->find()
    ->select(array_diff($articles->schema()->columns(), ['created', 'modified']))
    ->where(['id !=' => 1])
    ->order(['created' => 'DESC']);
```

We could make this a helper function

```php
function allExcept($table, $fields) {
   return array_diff($table->schema()->columns(), $fields);
}
```

And then you could call

```php
$query = $articles
    ->find()
    ->select(Db\selectAllExcept($articles, ['created', 'modified']))
    ->where(['id !=' => 1])
    ->order(['created' => 'DESC']);
```

**Comment by burzum** [comment]
@lorenzo can't this simply be `->selectAllExcept($articles, ['created', 'modified']))` and `selectAllExcept(['created', 'modified'])`?

**Comment by lorenzo** [comment]
I'm not comfortable putting it in the `Query` object because then it will need to interact with all the state it has internally:

* What happens if the columns are already selected?
* How does the interact with `autoFields`?

**Comment by berrygoudswaard** [comment]
Autofields is disabled, when you use Query::select(), so I can imagine it does the same with Query::selectAllExcept()

I think that Query::selectAllExcept() could also have a $overwrite parameter (defaults to true). This way the developer can decide what happens if a column is already selected.

Signature would be something like:
```php
selectAllExcept( array|string|callable $excludedFields [] , boolean $overwrite true )
```

**Comment by lorenzo** [comment]
that's my problem with having it in `Query`. `selectAll*` sounds like it actually will select all, not disable the autoFields.

**Comment by berrygoudswaard** [comment]
Maybe another solution (more flexible) would be to allow developers to use their own Query class.

That way a developer could do something like

```php
class CustomQuery extends Query
{
        public function selectAllExcept($excludedFields, $overwrite = true)
        {
                 // Logic
        }
}
```

This would allow developers add functionality that you don't want in de core Query class.
At the moment this can't be done because the CakePHP always instantiates a \Cake\ORM\Query object.

**Comment by inoas** [comment]
My take on this is: I consider the query builder a one way tool. You build stuff, you do not change stuff you already build. If you want to only select a view fields, you explicitly select them. If you are sure that opt-out is a good thing (I am not so sure about that), then you can get the schema's keys and do an array diff.

If we want to traverse the build query then there should be a general approach to modify things instead of just a `deselect()`. AFAIK it is somehow possible to traverse clauses but it doesn't have an easy to use interface AFAIR.

**Comment by berrygoudswaard** [comment]
I am aware of the Entity::hideProperties() en Entity::$_hidden. But this still fetches data from the database, thus consuming memory.

For example.... Let's pretend that I want to have a list of all products in a database of a webshop. My fictional webshop contains 100.000 products with long descriptions...... For my list I only need the 'name' and 'price' of my products, but the table also has a 'description' (LONGTEXT). 

AFAK $_hidden only hides the data, but doesn't prevent that it is selected when I execute the query. This means that my server has the descriptions of 100.000 products in memory. This is unnecessary because I don't even use the descriptions.

**Comment by berrygoudswaard** [comment]
@lorenzo The proposed Query::selectAllExcept() behave the same as the already existing Query::select().

You are right when you say: "selectAll* sounds like it actually will select all, not disable the autoFields." 
It does exactly what Query::select() does, except you provide a list of column's you DO NOT want instead of the column you DO want.

**Comment by lorenzo** [comment]
@berrygoudswaard open a pull request and let's see how it goes :)

**Comment by jorisvaesen** [comment]
@berrygoudswaard Although there were moments where this function might have been useful, I think I would have used it only because it's faster to code than selecting all the fields I need. Also be aware that with the same code you can get different result over time as the the table schema can change.

**Comment by berrygoudswaard** [comment]
@jorisvaesen that's exactly why I wanted to add this method. Just for convenience...

It's true that it can have different results as the table schema changes, but this also happen if you don't explicitly select fields (by omitting the Query::select() call).
