### ISSUE TITLE
__dx() throws an IntlException for strings containing {{...}}

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10996]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: Windows 10, Nginx

### What you did

```php
__dx('wa', 'time_span', '{{startDate}} ... {{endDate}}');
```

### What happened

> IntlException: Constructor failed

It works just fine when I'm using `__d(`)` or `__dx()` without the curly brackets.

### What you expected to happen

Not getting an exception.

I know that `{0}` is used for the translations, but I didn't expect a problen with using two of them and a string instead of an integer. There is probably no fix for it.

**Comment by markstory** [comment]
Your message string is invalid as far as ICU is concerned

```php
php > $m = new MessageFormatter('en_CA', 'Things {{one}}');
PHP Warning:  Uncaught IntlException: Constructor failed in php shell code:1
Stack trace:
#0 php shell code(1): MessageFormatter->__construct('en_CA', 'Things {{one}}')
#1 {main}
  thrown in php shell code on line 1

Warning: Uncaught IntlException: Constructor failed in php shell code:1
Stack trace:
#0 php shell code(1): MessageFormatter->__construct('en_CA', 'Things {{one}}')
#1 {main}
  thrown in php shell code on line 1
```

Your handlebars/twig/mustache delimiters overlap with [complex placeholders](http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping) in ICU. There is nothing CakePHP can do to fix this.
