### ISSUE TITLE
Mutator not working as expected

### ISSUE THREAD

**Issue by rogerpro** [cakephp/cakephp#10993]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.12
* Platform and Target: Ubuntu 16.04.3 LTS, Linux 4.4.0, Apache 2.4.18, MySQL 5.7.19, PHP 7.0.18. All packages installed with apt-get.

### What you did
I created a database with a single table:
```
CREATE TABLE `things` (
  `id` char(36) NOT NULL,
  `duration` int(11) NOT NULL
) ENGINE=InnoDB;

ALTER TABLE `things`
  ADD PRIMARY KEY (`id`);
```

I created an app:
```
$ composer self-update && composer create-project --prefer-dist cakephp/app epoch
```

I configured the database on `config/app.php`

I baked all:
```
$ cd epoch
$ bin/cake bake all --everything
```

I accessed `/epoch/things/add` with the browser and added 10 in the duration field. A 10 value was saved on the DB (right).

I want to save `duration` in integer seconds and show it as human readable time like h:mm:ss, so:

1. I added an accessor and a mutator:
```
class Thing extends Entity
{
(...)
    // Format with human readable time like h:mm:ss
    protected function _getDuration($duration)
    {
        return isset($duration) ? (new FrozenTime($duration))->format('G:i:s') : '';
    }
    
    // Nothing to do here: just save the integer value received
    protected function _setDuration($duration)
    {
        return $duration;
    }
}
```

2. I adapted the template on `src/Template/Things/index.ctp`:
```
				<td><?= h($thing->duration) ?></td>
```
(just output the field as text, as it will come already formatted)

Once again, I accessed `/epoch/things/add` with the browser and added 10 in the duration field.

I accessed `/epoch/things` with the browser.

### What happened
A `0:00:00` value was shown for the last added row.
A `0` value was saved on the DB.

### What you expected to happen
I expected to see `0:00:10` for the last added row on the browser.
I expected a `10` value to be saved on the DB.

**Comment by cleptric** [comment]
I see some problems with this approach. First, your getter will be called when you patch the entity, so that's why it's always save as `0` in your DB.
What would you expect to happen when you call `new FrozenTime(10)`?
Could you not just create a Helper that formats your int? Or do you have to work with the Duration later?

**Comment by rogerpro** [comment]
Why is the getter called when patching the entity?

**Comment by cleptric** [comment]
This happens during `_processSave()` where `EntityTrait::extratct` is called. During `patchEntity` the getter is just called for the `original` property update. My bad...
But anyways, you only want to format the data for displaying it?

**Comment by markstory** [comment]
The getters are no used when patching the entity. They *are* used when persisting to the database, which is the source of your issue. We generally recommend that formatted attributes use a different name. In your case you could use `$entity->duration_time` or any name that does not overlap with the actual property name in the database.

**Comment by markstory** [comment]
I've closed this issue as the behavior you're seeing is how accessor methods work, and we cannot change that behavior without causing significant disruption.

**Comment by rogerpro** [comment]
I understand.

Actually, it's a snap to create a virtual property and use it on a view template:

```
    protected function _getDurationTime()
    {
        $duration = $this->_properties['duration'];
        return isset($duration) ? (new FrozenTime($duration))->format('G:i:s') : '';
    }
```

```
			<td><?= h($session->duration_time) ?></td>
```

Just as feedback, I would like to share that when reading https://book.cakephp.org/3.0/en/orm/entities.html#accessors-mutators I understood that Accessors & Mutators where more high level, like utils to use while designing business logic. But now, somehow, I see them as a low level tool that requires to think about the whole core: persistence, request flow, etc.

Thank you.

**Comment by inoas** [comment]
@rogerpro let me know if the PR https://github.com/cakephp/docs/issues/5150 would have made it clearer.

**Comment by rogerpro** [comment]
@ionas yes, the note is great IMO. I would also switch from `.. note::` to `.. warning::` and pluralize Accessors.
