### ISSUE TITLE
'plugin' option inside Html helper for css has no effect

### ISSUE THREAD

**Issue by birdy247** [cakephp/cakephp#11011]
I have a theme that uses: **$this->Html->css('mycss', ['plugin' => false])**

this the renders **/my_theme/css/....**

The exact same css file exists in my apps webroot/css folder.

I would expect it to instead render **/css/....**

Or have I misunderstood the meaning of the plugin option?

**Comment by rodrigorm** [comment]
Can you fill the issue with more information? Use the following template: (https://github.com/cakephp/cakephp/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by markstory** [comment]
Are you trying to link to an application CSS file from within a theme?

**Comment by birdy247** [comment]
The assets are in my plugins webroot directory. 

I have a gulp task which copies these assets to my app's webroot directory (using the same folder structure).  I was hoping that the Html->css helper would use the assets in my app's webroot over the themes webroot.

If I delete the assets from the themes webroot, the assets in my apps webroot are used.

**Comment by dereuromark** [comment]
A PR here to fix things would sure be welcome.

**Comment by markstory** [comment]
> If I delete the assets from the themes webroot, the assets in my apps webroot are used.

The `plugin` option does not disable the use of theme assets. From your description it sounds like you are in a theme view, which always prefers theme assets over the application assets.
