### ISSUE TITLE
Test case fails with PHPUnit_Util_Diff class not found

### ISSUE THREAD

**Issue by peloncano** [cakephp/cakephp#11016]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.
* Platform and Target: Local testing.

### What you did
Upgraded to CakePHP 2.10 which has limited support for PHPUnit 4.x and 5.x. Also added the `phpunit.phar` version `5.7.21` to `app/Vendors` to use the new version of PHPUnit.

### What happened
When I run the unit test from the browser by going to `/test.php` and my unit test fails I get the following error:

```
Fatal Error

Error: Class 'PHPUnit_Util_Diff' not found	
File: ../lib/Cake/TestSuite/Reporter/CakeHtmlReporter.php	
Line: 268
```

Class `PHPUnit_Util_Diff` seems to have been removed on PHPUnit 4.x and 5.x (it does exist and work with PHPUnit 3.7).

### What you expected to happen
The test case failure be displayed on the screen.

**Comment by dereuromark** [comment]
Did you try 5.7.20? There was a few BC breaks in 5.7.21, for both major versions of CakePHP.
Try the one patch version before just to make sure.

**Comment by peloncano** [comment]
@dereuromark tried `5.7.20` and `4.8.9` and they both fail with the same error.

**Comment by nfedyk** [comment]
+1

**Comment by markstory** [comment]
The webrunner was not updated. Only the CLI runner was upgraded.

**Comment by peloncano** [comment]
@markstory yes - from what I can tell it works well in CLI.

**Comment by markstory** [comment]
So use that :smile: The webrunner is rife with a number of problems. If you really want to continue using the web runner you'll have to fix it :smile:

**Comment by tersmitten** [comment]
Code coverage throws an exception too in the we runner, but works fine in the console

**Comment by dereuromark** [comment]
PR open.
