### ISSUE TITLE
StaticConfigTrait::parseDsn() returns string if parse_url() fails.

### ISSUE THREAD

**Issue by sitedyno** [cakephp/cakephp#11019]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.0-RC1
* Platform and Target: Ubuntu 16.04, Apache, MySQL

### What you did
I used a database password that has a `#` in it. Similar to `mysql://user:#word@localhost/my_db`

### What happened
I can access the database from the command line just fine, but the app throws:
```
Warning (2): Illegal string offset 'className' [CORE/src/Datasource/ConnectionManager.php, line 117]
```
This is because `parse_url()` will not parse a URL with a `#` in it, at least in the password section. This results in `StaticConfigTrait::parseDsn()` returning a string instead of an array and `ConnectionManager` expects an array.

### What you expected to happen
It would have been really nice to have been told the DSN couldn't be parsed by `parse_url()`, then I would have looked into that instead of digging through the core to see what's going on. `parse_url()` specifically mentions that it's not meant for dealing with URIs:

    Note:

    This function is intended specifically for the purpose of parsing URLs and not URIs. However, to comply with PHP's backwards compatibility requirements it makes an exception for the file:// scheme where triple slashes (file:///...) are allowed. For any other scheme this is invalid.

The `#` in password does work if configured in app.php.

Not being able to use `#` in a db password with environment variables is also a limitation on security. A small limitation, but a limitation nonetheless.

**Comment by markstory** [comment]
Pull request up now.
