### ISSUE TITLE
Authcomponent problem if change storage key.

### ISSUE THREAD

**Issue by paulorwd** [cakephp/cakephp#11013]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: **3.3.13**.
* Platform and Target: **local**.

### What you did
**I changed the storage key in authcomponent.**
```
$this->loadComponent('Auth', [
    'storage' => ['className' => 'Session', 'key' => 'Auth.Admin']
]);
```

### What happened
In a controller that calls any component, the authcomponent does not receive the settings made and the response to the server as unauthorized.

### What you expected to happen
There is permission, so it should not redirect to unauthorized (redirectAction default not configured).

P.S: 
I have changed the key of the storage by authcomponent and in a request to a controller that loads another component, analyzing I realized that one of the times "Cake\Controller\Component\AuthComponent::authCheck" is called ( seems to be the last one ) The configured settings are not set and so the key configured in the storage is not found understanding that there is no permission.
I could not understand the relation of a controller any call any component and this problem arises, if there are no extra components in the controller this does not happen.

#### To simulate, do:

* Configure the AuthComponent with a different key in the storage.
* Create a controller and load any component there (initialize function)
* Make the request to this controller already authenticated. You will be redirected to the loginAction default, not the configured._

**Comment by markstory** [comment]
Edited for legibility.

**Comment by markstory** [comment]
> Create a controller and load any component there (initialize function)

Are you missing a call to `parent::initialize()` in the other controller? If you change the AuthComponent settings in one controller, but not another, the error you're seeing is going to happen every time.

If you want to change the session key, I would recommend you do it in `AppController` and ensure that all your controllers call `parent::initialize()` to ensure that the configuration options are applied.

**Comment by paulorwd** [comment]
I'm loading the AuthComponent in AppController, I'm not sure if there's a difference, but I'm not using the AppController of the Admin theme (App\Controller\Admin\AppController).
And also in all initialize i called the parents. `parent::initialize()`

**Comment by markstory** [comment]
Does `AppController::initialize()` always get called? Right now I'm not able to reproduce your issue as changing the session storage key works fine for me when AuthComponent is only loaded in `AppController::initialize()`.

**Comment by paulorwd** [comment]
Yes, it is called in all others. If I can not, I can create an example to show the problem.

**Comment by markstory** [comment]
Yes an example would be very helpful. Right now I don't know anything about what you're doing beyond what is in this issue.

**Comment by paulorwd** [comment]
Okay, give me an example.

**Comment by markstory** [comment]
I don't think I'm able to give you an example of what your code is doing. I was hoping that you would be able to provide me an example of what your code looks like so that I could try and reproduce the issue you are having.

**Comment by paulorwd** [comment]
Sorry, I wrote the wrong one.

**Comment by paulorwd** [comment]
[example.zip](https://github.com/cakephp/cakephp/files/1206838/example.zip)

I did something very simple, when opening the root of the site will be automatically logged, there will be shown a functional page with a link that points to the page with problem.

**Comment by markstory** [comment]
The problem is that your `ExampleComponent` is extending `AuthComponent` but not being configured. Class inheritance does not imply that settings are shared between two different components.

If you really want to extend `AuthComponent` I suggest you find a way to share configuration between it and AuthComponent.
