### ISSUE TITLE
EntityTrait::setDirty($property, false) should return $this

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#11012]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.12.

`EntityTrait::setDirty($property, false)` returns `false` instead `$this`.
https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L756

I'm creating this issue because i don't have time to write a PR with tests.

**Comment by markstory** [comment]
Pull request up now.
