### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1109 Unknown table 'referential_constraints' in information_schema

### ISSUE THREAD

**Issue by testmode123** [cakephp/cakephp#11010]
error : SQLSTATE[42S02]: Base table or view not found: 1109 Unknown table 'referential_constraints' in information_schema

i m new person in cakephp 3.x
i have created a new controller with ArticlesController in src/controller. and also using namespace App\Controller;
one function created with index() and that function have 

```php
      $articles = $this->Articles->find('all');
      $this->set(compact('articles'));
```
code.

and created a index.ctp file in src/template/Articles folder.

i have created a new model ArticlesTable in src/model/table folder.   and also using 
namespace App\Model\Table;
use Cake\ORM\Table;
in this file.

but i have received 
```
SQLSTATE[42S02]: Base table or view not found: 1109 Unknown table 'referential_constraints' in information_schema
```
can i solved it. ??

**Comment by markstory** [comment]
What version of MySQL Server are you using? That table should exist if you run the following SQL.

```sql
USE information_schema;
SHOW TABLES;
```

**Comment by testmode123** [comment]
Mysql server version 7.2 
i m using SQLyog enterprize


where written down USE information_schema
and SHOW TABLES;

**Comment by markstory** [comment]
You would need to run that SQL from a mysql client that lets you run ad-hoc queries.

**Comment by markstory** [comment]
Closing as I've not heard back for a number of days, and am not able to reproduce this using MySQL 5.6 (osx) or MySQL 5.7 (ubuntu 17).
