### ISSUE TITLE
[RFC] Support for connection switching

### ISSUE THREAD

**Issue by makallio85** [cakephp/cakephp#11023]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

CakePHP4?

I would really like to see CakePHP ORM to support connection switching in following scenario.

I have application that is built in concept "customer per database". Meaning, that I have n * databases for each customer and n * some kind of master databases.

I am aware of altering connection details and using one static connection name for each customer database but problem occurs, when i want to use same table objects in customer and master databases.

Example

I have table classes InvoicesTable and InvoiceRowsTable. Each customer can have its own invoices as do I as service provider. Design is equal in both levels. Customers are sending invoices to their customers and I am sending invoices to my customers, that are using this application.

Problem occurs, when I want to do something like this:

```
InvoicesTable extends Table
{
    $this->hasMany('InvoiceRows');
}

InvoiceRowsTable extends Table
{
   $this->belongsTo('Invoices');
}

$tableInShard = TableRegistry::get('Invoices', ['connection' => ConnectionManager::get('shard')]);
$tableInShard->save($table->newEntity(['invoice_rows' => [['amount' => 100]]]), ['associated' => 'InvoiceRows']);

$tableInMaster = TableRegistry::get('Invoices', ['connection' => ConnectionManager::get('master')]);
$tableInShard->save($table->newEntity(['invoice_rows' => [['amount' => 100]]]), ['associated' => 'InvoiceRows']);
```
Because table is already configured in table registry, currently I have to iterate over table registry and replace connection for every table (that is used, even associations) every time Table in instatiated.  This requires small helper class.

**Comment by robertpustulka** [comment]
Maybe all you need is different table aliases for different connections?

```php
$tableInShard = TableRegistry::get('ShardInvoices', [
  'className' => 'Invoices', 
  'connection' => ConnectionManager::get('shard')
]);
$tableInMaster = TableRegistry::get('MasterInvoices', [
  'className' => 'Invoices', 
  'connection' => ConnectionManager::get('master')
]);
```

Your associations could also have connection name prefixes if necessary.

```php
InvoicesTable extends Table
{
    $name = ucfirst($this->_connection->configName()) . 'InvoiceRows';
    $this->hasMany($name, [
        'className' => 'InvoiceRows'
    ]);
}
```

You could build a behavior that would handle the correct naming of associations. Or maybe you need to implement your own table locator, would assign correct connections.

**Comment by makallio85** [comment]
Good suggestions.

Could all this be somehow part of core as I think it is not that rare situation for even little bit more complex applications? I mean some "more-easier-to-do" like solution.

I don't know and that is why it is good to have this kind of discussion :D

**Comment by robertpustulka** [comment]
Another solution I would suggest is using different instances of `TableLocator` for different connections.
That would also require passing the locator around between associations.

```php
class InvoicesTable extends Table
{
    use LocatorAwareTrait;

    public function initialize()
    {
        $this->hasMany('InvoiceRows', [
            'tableLocator' => $this->getTableLocator();
        ]);
    }
}

class ConnectionAwareLocator extends TableLocator
{
    public function __construct(ConnectionInterface $connection) {
        $this->connection = $connection;
    }

    public function get($alias, array $options = [])
    {
        $table = parent::get($alias, $options);
        return $table->setConnection($this->connection)
                  ->setTableLocator($this);
    }
}

$masterLocator = new ConnectionAwareLocator(ConnectionManager::get('master'));
$table = $masterLocator->get('Invoices');
//this table and it's associations share the master connection


$shardLocator = new ConnectionAwareLocator(ConnectionManager::get('shard'));
$table = $shardLocator->get('Invoices');
//this table and it's associations share the shard connection
```

Maybe we could automate the process of sharing the table locator.
Table class could use `LocatorAwareTrait` by default, and a `TableLocator` could pass itself to the table on creation of an instance.

This way we could isolate the groups of tables created by a single locator and avoid issues with alias collisions.

**Comment by makallio85** [comment]
There is one gotcha. What about some one wants to configure on the fly associations connections to differ from main table connection?

Or is to something too crazy to even think about? :D

**Comment by robertpustulka** [comment]
You could swap connections after the table has been created. But you need to remember that this connection would stay changed in a locator.

You could pass another `tableLocator` to the association with a desired connection configured as in an example above.

```php
$table = $masterLocator->get('Invoices'); //master connection
$table->hasMany('SomeTable', [
    'tableLocator' => $shardLocator //shard connection
]);
```

**Comment by makallio85** [comment]
Oh yeah. That is true, didn't thought that.

**Comment by makallio85** [comment]
As a result of quick test it seems that LocatorAwareTrait needs to be included to Table class in able to get this work. Without, following error is thrown
```
BadMethodCallException: Unknown method "tableLocator"

C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Table.php:2293
C:\xampp\htdocs\cakephp-statement\src\Locator\ConnectionAwareLocator.php:20
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Association\BelongsToMany.php:287
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Association\BelongsToMany.php:1376
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Association\BelongsToMany.php:533
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\EagerLoader.php:655
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Query.php:1011
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php:276
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\ORM\Query.php:960
C:\xampp\htdocs\cakephp-statement\src\RowManager\RowManager.php:244
C:\xampp\htdocs\cakephp-statement\vendor\cakephp\cakephp\src\Database\Connection.php:678
C:\xampp\htdocs\cakephp-statement\src\RowManager\RowManager.php:253
C:\xampp\htdocs\cakephp-statement\tests\TestCase\TestCaseTrait\Row.php:73
C:\xampp\htdocs\cakephp-statement\tests\TestCase\Statement\StatementPaymentTest.php:46
```

**Comment by robertpustulka** [comment]
@makallio85 Yes, note my example above:

```php
class InvoicesTable extends Table
{
    use LocatorAwareTrait;
    ...
}
```

**Comment by makallio85** [comment]
@robertpustulka I mean \Cake\ORM\Table class. Doesnt work without. I tried to use trait in my extended classes, but error exception above was thrown until I added trait to base class.

**Comment by robertpustulka** [comment]
Ok i get it. 
We don't have the interface for locator awareness (yet). In this case you probably need to bypass it like that:

```php
if (method_exists($table, 'tableLocator)) {
    $table->tableLocator($this);
}
```

**Comment by markstory** [comment]
I am wary of adding sharding to core. There are many ways to shard a database, and I don't want us to try and do them all. That issue shows it is possible to do sharding with the primitives we provide. Specific sharding implementations might be better as a plugin/app code.

Sharded databases are pretty rare from my experience, and are something you should avoid for as long as possible due to the complexity they introduce.
