### ISSUE TITLE
No valid error in ...->existsIn(['....'], '....',['allowNullableNulls'=>true])

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#11020]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.16
* Platform and Target: Windows 10, Apache, PHP 7.1.7, XAMP 32Bit

### What you did
```
class UsersTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('users');
        $this->displayField('username');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('UserRoles', [
            'foreignKey' => 'user_roles_id',
            'joinType' => 'INNER'
        ]);
        
        .... ....
  
        $this->belongsTo('Licensees', [
            'foreignKey' => 'licensees_id',
            'joinType' => 'LEFT'
        ]);
        
        .... ....

    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        .... ....

        $validator
            ->uuid('licensees_id')
            ->allowEmpty('licensees_id');

        return $validator;
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['user_roles_id'], 'UserRoles'));
        $rules->add($rules->existsIn(['countries_id'], 'Countries'));
        $rules->add($rules->existsIn(['languages_id'], 'Languages'));
        $rules->add($rules->existsIn(['languages_app_id'], 'LanguagesApp'));

//        $rules->add($rules->existsIn(['licensees_id'], 'Licensees'));
        $rules->add($rules->existsIn(['licensees_id'], 'Licensees',['allowNullableNulls'=>true]));
//        $rules->add($rules->existsIn(['licensees_id'], 'Licensees',['allowMultipleNulls'=>true]));

        .... ....

        return $rules;
    }
```
**Controller method update data**

```
protected function users_to_licensees_update($user_ids = [], $licensees_id = '')
    {
.....
.....
// Init
        $users_data = [];
        $ids = [];

        // Loop data post
        foreach ($user_ids as $id => $is_checked) {
                $ids[] = $id;
                $users_data[] = [
                    'id' => $id,
                    'licensees_id' => ($is_checked == '1') ? $licensees_id : null,
                ];
        }

        // Get data DB
        $usersEntities = $this->Users->find('all', [
            'fields' => [
                'id',
                'licensees_id',
            ],
            'conditions' => [
                'id IN' => $ids
            ]
        ]);

        // Patch Entity and Data post
        $usersPatchEntities = $this->Users->patchEntities($usersEntities, $users_data);

        // Multiple Save
        $result = ($this->Users->saveMany($usersPatchEntities)) ? true : false;

        exit(debug($usersPatchEntities));

        // Ok..?
        if ($result) {
            // Msj Flash
            $this->Flash->success(__('Join Users to Licensee has been saved.'));
        } else {
            // Msj Flash
            $this->Flash->error(__('Join Users to Licensee not been saved.'));
        }

        // Out
        return $result;
}
```

### What happened
Error validation  in Entity 1 for **'licensees_id' => null,**

```
\src\Controller\LicenseesController.php (line 246)
[
	(int) 0 => object(App\Model\Entity\User) {

		'id' => '44ef54a4-4a92-49d5-a163-1b278b3bd3c3',
		'licensees_id' => 'c65db3d2-2a86-40e3-a7f1-76cd24dfa5ad',
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Users'
	
	},
	(int) 1 => object(App\Model\Entity\User) {

		'id' => '99d7c765-2637-4a42-b666-25536801186a',
		'licensees_id' => null,
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [
			'licensees_id' => true
		],
		'[original]' => [
			'licensees_id' => 'c65db3d2-2a86-40e3-a7f1-76cd24dfa5ad'
		],
		'[virtual]' => [],
		'[errors]' => [
			'licensees_id' => [
				'_existsIn' => 'No existe este valor'
			]
		],
		'[invalid]' => [],
		'[repository]' => 'Users'
	
	}
]
```

### What you expected to happen
Update Ok my data ;(

**Comment by EOM** [comment]
In the Scheme, in the Scheme, you have the "Users.licensees_id" table set "NOT NULL" and save Users.licensees_id = '' Empty OR Users.licensees_id = NULL, it fails, however Set, as option ['allowNullableNulls' => true]

There is no way that does not fail, the validator, if "Users.licensees_id" set "NOT NULL", and via POST "Users.licensees_id = '' Empty" OR "Users.licensees_id = NULL" would not have to general error if you Step one "and the table is IS NULL.

As a new "feature-discussion (RFC)" ..?


Print DB genera Fix: http://s1.postimg.org/8q8ar02xb/print_de_pantalla_18.jpg

Print DB Solution: http://s1.postimg.org/k3uu27dfz/print_de_pantalla_19.jpg

**Comment by markstory** [comment]
Is there anyway you could provide a more succinct way to reproduce the issue you're having? Between the commented out code and long controller method and screenshots it is hard to figure out what is going on.

**Comment by EOM** [comment]
The problem is generated.
If you pass `User.licensees_id => null` or `User.licensees_id => ''` to `"UserTable"`
The validation error is triggered, while the table in the **DB**, `Users.licensees_id` is set to NOT NULL.
While setting UserTable with:
`$Rules->add ($ rules->existsIn (['licensees_id'], 'Licensees', ['allowNullableNulls' => true]));`

But the validation error does not work anymore if in the **DB**, `Users.licensees_id` is set to NULL.

It would not be good to have a parameter
`$Rules->add ($ rules->existsIn (['licensees_id'], 'Licensees', ['allowEmpty' => true]));`
For cases like these
`User.licensees_id => null` o `User.licensees_id => ''`

**Print an example of an idea you might have:**
Http://s27.postimg.org/iabsmtomb/print_de_pantalla_21.jpg

**Comment by markstory** [comment]
If the column is `NOT NULL` the nullableNulls option will not do anything. That option only takes effect if the key fields are nullable.

**Comment by EOM** [comment]
Of course, I understand that, I realized by the validator; After struggling with the code because it gave me error.

So it would not be nice to have a new option for this combination, when the fields is `NOT NULL`.

For cases:
`User.licensees_id => null` o `User.licensees_id => ''`

`$Rules->add( $rules->existsIn (['licensees_id'], 'Licensees', ['allowEmpty' => true]));`

Since if you pass a `NULL` or `String Empty` does not generate the error.

**Comment by inoas** [comment]
My 2 cents: foreign keys are either `NULL` or a key (best a real referential key). They should never be empty string. You can easily replace empty-string with NULL for your nullable references in SQL.

**Comment by markstory** [comment]
How does a `null` in the field not cause issues when persisting though?

**Comment by markstory** [comment]
Closing as the `nullableNulls` option only applies to nullable columns. I don't think casting to '' is a safe behaviour as rules are used to enforce SQL constraints.
