### ISSUE TITLE
memcached.use_sasl is no longer a thing in memcached extension version 3

### ISSUE THREAD

**Issue by dzuelke** [cakephp/cakephp#11027]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: master
* Platform and Target: PHP 7.1.8 with `memcached` extension 3.0.3

### What you did

Called `MemcachedEngine::init()` on PHP with `memcached` extension, built with SASL support.

### What happened

An exception got thrown, because the `memcached.use_sasl` INI setting no longer exists in version 3 of the extension (released in February 2017). See https://pecl.php.net/package-info.php?package=memcached&version=3.0.0

```
2017-08-09 18:48:04 Error: [InvalidArgumentException] Memcached extension is not build with SASL support
Request URL: …
Stack Trace:
#0 vendor/cakephp/cakephp/src/Cache/CacheRegistry.php(90): Cake\Cache\Engine\MemcachedEngine->init(Array)
…
```

### What you expected to happen

Exception should not be thrown for `memcached` extension 3.0.0 and later.

**Comment by markstory** [comment]
I'll take a look.

**Comment by markstory** [comment]
Pull request up now.
