### ISSUE TITLE
Load fixture of plugin in app controller test fail

### ISSUE THREAD

**Issue by Petrucheqa** [cakephp/cakephp#11038]
* [x] bug

* CakePHP Version: '3.4.12'

I'm using CakeDC/Users plugin and I've extend the controller. I would like to write some tests using UsersFixture of the plugin. 

`    public $fixtures = [
        'plugin.cakedc\\users.users'
    ];
`

It throws, UnexpectedValueException. 

`Exception: Referenced fixture class "Cakedc\Users\Test\Fixture\UsersFixture" not found. Fixture "plugin.cakedc\users.users" was referenced in test case "App\Test\TestCase\Controller\MyUsersControllerTest". in [/var/www/html/project/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 228] `

The className in the FixtureManager is correct but the class is not found.

**Comment by ADmad** [comment]
`'plugin.cakedc\\users.users'` is incorrect. You need to use `'plugin.CakeDC/Users.Users'`.

**Comment by Petrucheqa** [comment]
Still same Exception : `Exception: Referenced fixture class "CakeDC\Users\Test\Fixture\UsersFixture" not found. Fixture "plugin.CakeDC/Users.users" was referenced in test case "App\Test\TestCase\Controller\MyUsersControllerTest". in [/var/www/html/project/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 228]`

**Comment by ADmad** [comment]
Have you added the path to fixture folder for autoloading similar to [this](https://github.com/cakephp/app/blob/master/composer.json#L34) in your `composer.json`?

**Comment by Petrucheqa** [comment]
Yes.

**Comment by ADmad** [comment]
Did you run `composer autoload-dump` after editing `composer.json`? :)

**Comment by Petrucheqa** [comment]
Yeap :)

**Comment by ADmad** [comment]
Please provide your `composer.json`.

**Comment by Petrucheqa** [comment]
`{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.4.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "~1.0",
        "cakedc/users": "^5.0"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1",
        "cakephp/cakephp-codesniffer": "^3.0",
        "phpunit/phpunit": "^5.7|^6.0"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan compatibility.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "pre-install-cmd": [
            "chmod +x bin/cake"
        ],
        "post-install-cmd": [
            "App\\Console\\Installer::postInstall",
            "bin/cake migrations migrate -p CakeDC/Users",
            "bin/cake migrations migrate",
            "bin/cake migrations seed --seed AllSeed"
        ],
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "check-report": [
            "@test-report",
            "@cs-check-report"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-check-report": "phpcs --colors --report=checkstyle --report-file=webroot/report.xml -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",        
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "phpunit --colors=always",
        "test-report": "phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml --colors=always"
    },
    "prefer-stable": true
}
`

**Comment by Petrucheqa** [comment]
https://gist.github.com/Petrucheqa/4510878febd875115092686dba7abc98

**Comment by ADmad** [comment]
You haven't added the autoload path for the plugin's fixture under `"autoload-dev"`.

**Comment by Petrucheqa** [comment]
I didn't understand, now my composer.json looks like : 
https://gist.github.com/Petrucheqa/de5112299185bb5c52b78d1e12a3afbd

**Comment by ADmad** [comment]
It's still incorrect. Sorry but this is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
