### ISSUE TITLE
Hash extract parent_id null fails

### ISSUE THREAD

**Issue by Lin510** [cakephp/cakephp#11033]
Using array below i am trying to extract the id for vocabulary_id and null parent_id. 

Hash::extract(array, '{n}[vocabulary_id=9]') works
Hash::extract(array, '{n}[vocabulary_id=9][parent_id=null') fails

array( array( 'id' => 240,'parent_id' => null, 'term_id' => 245, 'vocabulary_id' => 9 ))

https://stackoverflow.com/questions/45658778/cakephp-hash-extract-parent-id-null

**Comment by saeideng** [comment]
try 
`Hash::extract(array, '{n}[vocabulary_id=9][parent_id=/^$/)`

**Comment by markstory** [comment]
We do not support matching `null` values right now.

**Comment by inoas** [comment]
You can probably use one of the `collection` methods, such as `extract()` with a closure, to achieve what you want: https://book.cakephp.org/3.0/en/core-libraries/collections.html
