### ISSUE TITLE
allow_url_fopen with binary type

### ISSUE THREAD

**Issue by stujn** [cakephp/cakephp#11041]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.11
* Platform and Target: CentOS Linux, Apache 2.4.27, MySQL 5.6.35

### What you did
Set up CakePHP to use database sessions, including creating sessions database table, as in CakePHP documentation, as follows:

```sql
CREATE TABLE `sessions` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `data` BLOB, 
  `expires` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
```

Set allow_url_fopen=Off in php.ini

### What happened

When attempting to log in, receive error on line 86 of /vendor/cakephp/cakephp/src/Database/Type/BinaryType.php along the lines of:

function.fopen: failed to open stream: no suitable wrapper could be found

The login also fails.

While I haven't upgraded to 3.4.12, from looking at BinaryType.php in 3.4.12 and 3.5, I think the problem will still exist in these versions.

Same problem exists when running the site on a Windows machine with XAMPP.

### What you expected to happen

If I enable allow_url_fopen then everything works fine. However, I would prefer to switch this off as it's generally regarded as a security risk. It would be good if database sessions, and the binary type in general, worked with allow_url_fopen disabled.

**Comment by inoas** [comment]
> If PHP has decided that filename specifies a registered protocol, and that protocol is registered as a network URL, PHP will check to make sure that allow_url_fopen is enabled. If it is switched off, PHP will emit a warning and the fopen call will fail. 

Source: http://php.net/manual/en/function.fopen.php

BinaryType.php::86
```php
if (is_string($value)) {
    return fopen('data:text/plain;base64,' . base64_encode($value), 'rb');
}
```
While it is interesting that it cannot only do *real URLs* but also data *data URIs* https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs there is twofold:
- a.) personally, I do think that data URIs should pass even with `allow_url_fopen` off. This should probably be discussed here https://bugs.php.net/ and possibly on Freenode IRC #php. An additional flag like `allow_uri_fopen` could be introduced if there was the desire to block URIs from loading; or `allow_uri_fopen` could be set to true to override `allow_url_fopen` for data-URIs and be 100% BC.
- b.) Even if I'm right *and* the PHP core fixes the problem, then they will probably only fix it in latest 7.1.x; As we still support 5.6, I would 👍 a PR to change this (but I ain't a core member); care to create a PR?

**Comment by inoas** [comment]
Can you check http://php.net/manual/en/wrappers.data.php aka,
- set `allow_url_fopen` to `false`
- set `allow_url_include` to `true`

**Comment by stujn** [comment]
Thanks for the quick response, inoas!

Same problems if allow_url_fopen is false and allow_url_include is true.

But everything works fine if allow_url_fopen is true, while allow_url_include is false. So, this provides some degree of security. 

However, many people seem to think that turning off allow_url_fopen is still advisable, even if allow_url_include is off. A few examples:

https://www.owasp.org/index.php/PHP_Configuration_Cheat_Sheet

http://phpsec.org/projects/phpsecinfo/tests/allow_url_fopen.html

Regarding creating a PR, I'm not sure I have a solution at this stage - I'll have to think about it. If anyone else has any thoughts, feel free to create a PR!

**Comment by inoas** [comment]
See my edited response above... try setting both to true and then just include to false.
Does it work with both to true and not with fopen to true but include to false?

**Comment by stujn** [comment]
Yes, it works with both set to true.

And it also works with just include set to false (and fopen still set to true).

**Comment by markstory** [comment]
Until we can find another way to make file handles out of binary data I don't see how we can fix this issue.

**Comment by stujn** [comment]
Looks like this is going to be tricky. There's a bit of debate about whether leaving allow_url_fopen on really is that much of a security risk, so long as allow_url_include is off.

See this from inoas above: 
https://stackoverflow.com/a/24049626

At the same time cpanel and some hosts are switching allow_url_fopen off by default.

I know I'm the person who first posted this, but I could be convinced either way. Maybe this should be put on hold for now?

**Comment by inoas** [comment]
Maybe for 4.0 the cake database sessions could use a different column type that works on pure strings? Would that work? I don't think it is BC within 3.x though.

Also CakePHP should probably recommend turning on allow_url_fopen (maybe check it as a requirement via composer? possible?) and recommend turning off allow_url_include?

**Comment by Harfusha** [comment]
Hello, i had to bypass this, so i changed condition in BinaryType.php::86 to this 
`if (is_string($value)) {
            $stream = fopen('php://memory','r+');
            fwrite($stream, $value);
            rewind($stream);
            return $stream;
        }`

**Comment by othercorey** [comment]
Please open a new issue if you're encountering a problem.
