### ISSUE TITLE
Built-in Server Crashes and Closes

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#11048]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.4.10
* Platform and Target: OS X Sierra, MySQL, Builtin Server

### What you did
    $this->belongsTo('Messages', array())->setEntityClass('Messages2')->setForeignKey('message_id')->setProperty('messages');

### What happened
    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen/AdminLTE]
    └──╼ bin/cake server -p 9000

    Welcome to CakePHP v3.4.10 Console
    ---------------------------------------------------------------
    App : src
    Path: /Users/jlroberts/Projects/JeffreyLRobertsCom/CakePHPKitchen/AdminLTE/src/
    DocumentRoot: /Users/jlroberts/Projects/JeffreyLRobertsCom/CakePHPKitchen/AdminLTE/webroot
    ---------------------------------------------------------------
    built-in server is running in http://localhost:9000/
    You can exit with `CTRL-C`

    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen/AdminLTE]
    └──╼

### What you expected to happen

The built-in server should be returning a page, not crashing....

**Comment by jeremyharris** [comment]
Is there any information in the logs that can maybe help us track this down? The CakePHP cli logs as well as the PHP built in server logs (`ini_get('error_log')` will show you where it's logged) would be helpful.

You can

**Comment by jeffreyroberts** [comment]
ini_get('error_log') is blank... lol, let me find the error log for os x, they got funny placements..

**Comment by jeffreyroberts** [comment]
└──╼ cat /var/log/apache2/php_errors.log
cat: /var/log/apache2/php_errors.log: No such file or directory

hrmmm, i set the log file in /private/etc/php.ini and then re-ran the crash, but no error was logged...

does the built in webserver use a different php.ini? I know you can specify one from the command line when using php's builtin webserver...

**Comment by jeffreyroberts** [comment]
Would be sweet for debugging to add the error log path to the Welcome screen =]

**Comment by jeffreyroberts** [comment]
more specifically, it only crashes when I add ->setEntityClass('Messages2') to the statement

**Comment by jeffreyroberts** [comment]
im guessing some sort of infinite loop, because I am attempting recursion there...

**Comment by jeffreyroberts** [comment]
mysql> show columns from Messages;
    +------------+---------------+------+-----+---------+----------------+
    | Field      | Type          | Null | Key | Default | Extra          |
    +------------+---------------+------+-----+---------+----------------+
    | id         | int(11)       | NO   | PRI | NULL    | auto_increment |
    | user_id    | varchar(255)  | NO   |     | NULL    |                |
    | subject    | varchar(2048) | NO   |     | NULL    |                |
    | message    | text          | NO   |     | NULL    |                |
    | message_id | int(11)       | NO   |     | 0       |                |
    | read       | int(11)       | NO   |     | 0       |                |
    | replied    | int(11)       | NO   |     | 0       |                |
    | priority   | int(11)       | NO   |     | 0       |                |
    | topic      | int(11)       | NO   |     | 0       |                |
    | closed     | int(11)       | NO   |     | 0       |                |
    | created    | datetime      | NO   |     | NULL    |                |
    | modified   | datetime      | NO   |     | NULL    |                |
    +------------+---------------+------+-----+---------+----------------+
    12 rows in set (0.00 sec)

**Comment by saeideng** [comment]
> Would be sweet for debugging to add the error log path to the Welcome screen =]

no,Welcome screen  will remove in 3.5

**Comment by jeremyharris** [comment]
@saeideng I think this particular shell could output some useful information from it's main or help methods.

At any rate, @jeffreyroberts the CLI could be using a different php.ini. You can point to a specific one with `-c` I believe.

**Comment by jeffreyroberts** [comment]
└──╼ bin/cake server -p 9000 -c /private/etc/php.ini
Error: Unknown short option `c`
PHP Built-in Server for CakePHP
[WARN] Don't use this in a production environment

Usage:
cake server [-d] [-h] [-H] [-p] [-q] [-v]

Options:

--document_root, -d  DocumentRoot
--help, -h           Display this help.
--host, -H           ServerHost
--port, -p           ListenPort
--quiet, -q          Enable quiet output.
--verbose, -v        Enable verbose output.

**Comment by jeffreyroberts** [comment]
this is 3.4.10, anything changed around these CLI parts since then? ... either way I will upgrade shortly...

**Comment by jeremyharris** [comment]
@jeffreyroberts no, this shell is a simple wrapper around the php built in server. It's likely an app code issue, but something should be logging for you somewhere. This ticket, in my mind, is more about giving a better error message.

**Comment by markstory** [comment]
How can someone reproduce the crash you're having?

**Comment by jeffreyroberts** [comment]
Here is the MessagesTable.php


    public function initialize(array $config)
    {
        parent::initialize($config);
        //ini_get('error_log');die();
        $this->hasMany('Messages', array())->setEntityClass('Messages2')->setForeignKey('message_id')->setProperty('messages');

        $this->setTable('messages');
        $this->setDisplayField('subject');
        $this->setPrimaryKey('id');
    }

**Comment by jeffreyroberts** [comment]
I am guessing by creating the messages table above, and using the above initialize method... I will create a new project tomorrow and verify those two alone will reproduce the error

**Comment by markstory** [comment]
Looks like you might have an infinite loop. Does that code not crash in tests or apache?

**Comment by jeffreyroberts** [comment]
Steps to reproduce locally....

    #!/bin/bash
    git clone git@github.com:CakePHPKitchen/CakePHP-Issue-11048.git
    cd CakePHP-Issue-11048
    composer install
    mysql -u root < config/schema/basics.sql
    bin/cake migrations migrate
    mysql -u root issue11048 < config/schema/issue11048.sql
    bin/cake server -p 9001

Then navigate to 

    http://localhost:9001/issue11048

**Comment by jeffreyroberts** [comment]
I havent had a chance to test with apache yet, and I am a slacker when it comes to Test Driven Development....

**Comment by jeffreyroberts** [comment]
I want to say ive done a recursive table before with CakePHP and had to limit the levels of recursion on it... Is there something like that I can do with 3.4.x?

**Comment by markstory** [comment]
Have you tried giving your hasmany association a different alias? Perhaps `Replies` or `ChildMessages`? The duplicate alias is likely the source of the loop.

**Comment by jeffreyroberts** [comment]
I was attempting to set the Alias to Messages2

     ->setEntityClass('Messages2')

Is that not how we set the alias? =]

**Comment by jeffreyroberts** [comment]
woot...

    ->setAlias('Messages2')

crashed the server as well

**Comment by jeffreyroberts** [comment]
both hasMany and belongsTo with setAlias or setEntityClass crashes the server

    $this->hasMany('Messages', array())->setAlias('Messages2')->setForeignKey('message_id')->setProperty('messages');

and

    $this->belongsTo('Messages', array())->setAlias('Messages2')->setForeignKey('message_id')->setProperty('messages');

**Comment by jeffreyroberts** [comment]
what I am trying to do is get the original message from a reply...

I have a button on the replies to convert that reply to a FAQ page... When I click that button, I want to grab the original message so that I can extract the original subject line...

**Comment by markstory** [comment]
I think you need to set the alias in the belongsTo() call. So

```php
$this->belongsTo('ParentMessages', [
  'className' => 'Messages'
]);
```

instead.

**Comment by jeffreyroberts** [comment]
Crashes it...

**Comment by jeffreyroberts** [comment]
That worked, thank you, thats awesome =]
