### ISSUE TITLE
Add disable_compression option for HTTP Client

### ISSUE THREAD

**Issue by stujn** [cakephp/cakephp#11042]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.11

When using the HTTP Client there are various request method options, as outlined here:

https://book.cakephp.org/3.0/en/core-libraries/httpclient.html#request-method-options

It would be good if there was also an option to disable_compression when using SSL, as in the PHP ssl context options here:

http://php.net/manual/en/context.ssl.php

This option should be set to true by default.

**Comment by markstory** [comment]
Any chance you'd be willing to put a pull request together for this change?

**Comment by stujn** [comment]
I'm a complete newbie when it comes to CakePHP, but yes I can give this a go. But I'll only have a chance to take a proper look later in September. If that doesn't fit with the schedule then someone else better step in.

**Comment by markstory** [comment]
@stujn We don't have hard schedules for features. Once a feature is complete we slide it into the next release window. September sounds great to me :+1:

**Comment by burzum** [comment]
Isn't this all we need or am I missing something else?

```diff
diff --git a/src/Http/Client.php b/src/Http/Client.php
index af910b2556..e4a79dfb4b 100644
--- a/src/Http/Client.php
+++ b/src/Http/Client.php
@@ -111,6 +111,7 @@ class Client
         'ssl_verify_peer_name' => true,
         'ssl_verify_depth' => 5,
         'ssl_verify_host' => true,
+        'ssl_disable_compression' => false,
         'redirect' => false,
     ];

@@ -151,6 +152,8 @@ class Client
      *   Defaults to 5.
      * - ssl_verify_host - Verify that the certificate and hostname match.
      *   Defaults to true.
+     * - ssl_disable_compression - If set, disable TLS compression. This can
+     *   help mitigate the CRIME attack vector.
      * - redirect - Number of redirects to follow. Defaults to false.
      *
      * @param array $config Config options for scoped clients.
diff --git a/src/Http/Client/Adapter/Stream.php b/src/Http/Client/Adapter/Stream.php
index 94950ecc76..d30df3c9a9 100644
--- a/src/Http/Client/Adapter/Stream.php
+++ b/src/Http/Client/Adapter/Stream.php
@@ -217,6 +217,7 @@ class Stream
             'ssl_cafile',
             'ssl_local_cert',
             'ssl_passphrase',
+            'ssl_disable_compression'
         ];
         if (empty($options['ssl_cafile'])) {
             $options['ssl_cafile'] = CORE_PATH . 'config' . DIRECTORY_SEPARATOR . 'cacert.pem';
```

**Comment by stujn** [comment]
burzum - I haven't had a chance to look into this, but you could well be right. Would you be OK with creating a pull request for this?
