### ISSUE TITLE
[RFC] EntityContext should not use ServerRequest::getData() to restore input values

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11043]
Reported in #japanese channel on our Slack.

This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.12
* Platform and Target: Non-related

### What you did

Created a bulk edit action:
```php
// In UsersController.php
public function bulkEdit() {
    $users = $this->paginate($this->Users);

    $data = $this->request->getData('users');
    if ($data) {
        // ...
        $this->Users->patchEntities($users, $data);
        // ...
    }

    $this->set(compact('users'));
}
```

And the template:
```php
// In bulk_edit.ctp
<?= $this->Form->create($users, ['novalidate' => true]) ?>
<?php foreach ($users as $i => $user): ?>
<fieldset>
<legend><?= h($user->id) ?></legend>
<?php
echo $this->Form->control("$i.id", ['name' => "users[$i][id]"]);
echo $this->Form->control("$i.email", ['name' => "users[$i][email]"]);
?>
</fieldset>
<?php endforeach ?>
<?= $this->Form->button(__('Submit')) ?>
<?= $this->Form->end() ?>
```
(Note that `name` options are given to prevent the pollution of `$_POST`.)

Entered an invalid email in a `email` field, and submitted the form.
![bulk-edit1](https://user-images.githubusercontent.com/7399393/29317297-378cba60-8206-11e7-8d5d-671868bbb528.png)

### What happened

Got a correct error message expectedly. However, the invalid email I entered was not restored unexpectedly.
![bulk-edit2](https://user-images.githubusercontent.com/7399393/29317305-446c4e76-8206-11e7-9f45-42d19f09d887.png)

### What you expected to happen

The form values should be restored.

### Why this issue happens

Because `EntityContext` uses `SeverRequest::getData()` to restore form values, and it fails to do it if `name` options are given. See 
https://github.com/cakephp/cakephp/blob/ee2ead47b4b5b25a520a91d0b50a039c193af7eb/src/View/Form/EntityContext.php#L234

### Suggestion

`EntityContext` should not use `ServerRequest::getData()`. Instead, it should use `Entity::invalid()` (`getInvalidField()` in 3.5) for invalid properties, and `Entity::get()` for normal properties. Or adding new properties something like `patched` may be better.

**Comment by markstory** [comment]
Won't that make reading request data more complicated as reading the value would depend on whether or not the field has an error? We might also run into data changes of userland code uses a getter to format/manipulate the posted field data.

We could convert the name option into a dot path to read out of the request data if the name option is used. I think that would preserve the current behaviour and possibly fix this issue as well.

**Comment by chinpei215** [comment]
>Won't that make reading request data more complicated as reading the value would depend on whether or not the field has an error? We might also run into data changes of userland code uses a getter to format/manipulate the posted field data.

Yes, it will. So what about adding `Entity::$_patched` property? Currently, `Entity::$_invalid` seems to store string values provided by newEntity/patchEntity if a field has an error. But if `Entity::_$invalid` stores them regardless of whether the field has an error or not, we need not to call `Entity::get()` to restore values of non-error fields.

> We could convert the name option into a dot path to read out of the request data if the name option is used. I think that would preserve the current behaviour and possibly fix this issue as well.

Yes, that would be a reasonable approach. So I am OK if people prefer this approach. But why I suggested the above solution is that it sounds like a hybrid context between entity and request. Since `EntityContext` uses `Entity::errors()` to display error messages, I think it will be more simple if values can be retrieved from on the entity too.

**Comment by markstory** [comment]
I worry about not reading from the request as people _may_ have properties in their forms that are not assigned to entities. We'd be breaking those scenarios if we removed reading from request data.

**Comment by ADmad** [comment]
> I worry about not reading from the request as people may have properties in their forms that are not assigned to entities. We'd be breaking those scenarios if we removed reading from request data.

Yup, for e.g. "I agree to terms" checkboxes, password confirm fields etc.

**Comment by chinpei215** [comment]
In that case, I thought people would call `patchEntity()` to validate them and display error messages, but right. Some people may not validate them at all on the server side. Though I come up with another approach, but an easy solution may be to parse `name` options and to retrieve correct field names, as @markstory suggested above. Thank you for your comments and reactions.

**Comment by chinpei215** [comment]
Changed the milestone to 3.6. 3.5 will be released soon, and either way is not backward compatible.

**Comment by ADmad** [comment]
@chinpei215 Btw you don't need to use `users` in your input names. If you just generate your inputs
like `$this->Form->control("$i.id")` 
and use `$this->Users->patchEntities($users, $this->request->getData());` 
everything works as expected :slightly_smiling_face:

**Comment by chinpei215** [comment]
@ADmad Yes. Actually, I suggested the workaround for the original issue reporter. But then it is hard to iterate the users' data, as the first level $_POST array may contain other data. So I wrote the following note in the description of this issue:
> Note that name options are given to prevent the pollution of $_POST

I am not sure whether "the pollution of $_POST" really means what I wanted to say though 😛

**Comment by diegosardina** [comment]
I'm coming from the issue #14206.

Is there a reason why EntityContext read the request data directly instead of using by default the code below in the FormHelper?

```
protected $_valueSources = ['data', 'context'];
```

The behavior should be the same, without the limit of hard-coding that priority inside EntityContext.

I want to swap the priority by doing ['context', 'data'] because in my case the entity plays a major role in holding the state of the form, but that doesn't work.

This commit https://github.com/cakephp/cakephp/commit/01704a47017086550fc63ba2376bef7bd0b29e93 maybe was done before valueSources was conceived.

**Comment by markstory** [comment]
@diegosardina Using the valueSources list would be a good solution and approach to simplifying the context objects. We could do a change like that in 4.1.0

**Comment by diegosardina** [comment]
> We could do a change like that in 4.1.0

Great :-)

What do you think about giving priority to context with ['context', 'data'] by default?

**Comment by diegosardina** [comment]
I had time for some tests.

I commented the part where EntityContext fetches from the request data and I gave priority to getInvalidField() in val() method:

```
            [...]
            $part = end($parts);

            $val = $entity->getInvalidField($part);
            if ($val !== null) {
                return $val;
            }

            $val = $entity->get($part);
            if ($val !== null) {
                return $val;
            }
            [...]
```
In FormHelper:
```
           protected $_valueSources = ['context', 'data'];
```

It solved my problem where I have to play with dirty entities during multiple form submissions.

I also tested the code reported by the issuer and looks like working.

![image](https://user-images.githubusercontent.com/22911186/73306928-7ef9b400-421d-11ea-9185-1cb92ea8faf0.png)

Also fields that are not part of entity works.

**Comment by markstory** [comment]
@diegosardina would you be able to put a pull request together with the changes you have made?

**Comment by diegosardina** [comment]
Sorry for my late answer.

I'm going to split it in two PRs, one that removes request from context classes and move FormHelper from ['context'] to ['data', 'context'] to keep the same behavior.
The second one will move to ['context', 'data'].

It's better to break things in small steps :-)

**Comment by ADmad** [comment]
> one that removes request from context classes

Don't do that. While `EntityContext` might not need to use request as per your suggested changes, `ArrayContext` still does. Since it needs to return the the values of request data if present instead of default value set for a field.

**Comment by ADmad** [comment]
To keep the code churn to a minimum only `EntityContext::val()` can be modified to give priority to invalid value from entity over request data's value.

**Comment by diegosardina** [comment]
> 
> Don't do that. While `EntityContext` might not need to use request as per your suggested changes, `ArrayContext` still does. `ArrayContext` needs to return the the value from request data if present instead of default value set for a field.

I added a new 'data' section in the array of ArrayContext that holds the current supplied values.
