### ISSUE TITLE
Paginator page count bug

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11052]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4 latest

### What you did
Filtering and pagination shows 0 results.
The params though show

		'finder' => 'all',
		'page' => (int) 1,
		'current' => (int) 0,
		'count' => (int) 0,
		'perPage' => (int) 20,
		'prevPage' => false,
		'nextPage' => false,
		'pageCount' => (int) 0, // Should be also 1 as page
		'sort' => 'Modules.name',
		'direction' => 'asc',
		'limit' => null,
		'sortDefault' => 'name',
		'directionDefault' => 'ASC',
		'scope' => null

### What you expected to happen
```php
$page = max(min($page, $pageCount), 1);
```
most likely needs a max(x, 1) for pageCount as well.

Or is the pageCount here acceptable as "we show first page, but it is not a real page"?

**Comment by lorenzo** [comment]
How is this a problem?

**Comment by dereuromark** [comment]
When catching the exception and relying on the results of params, you need to know the total number of pages sometimes.
There is a 2nd issue here, the count query not run, but thats a different issue.
It was just topic in the channel earlier.

**Comment by dereuromark** [comment]
PR open.
