### ISSUE TITLE
Core methods start using classes instead of interfaces.

### ISSUE THREAD

**Issue by skie** [cakephp/cakephp#11051]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5-RC2

### What you did
Initially when cakephp 3.x branch was started we had discussion and agreed to use interfaces over classes in case we have alternative to use interfaces.
E.g. we used EntityInterface instead of Entity class to provide way to create app level Entity classes implementing same interface with additional functionallity.

### What happened
But in 3.5 branch i see this commit 68d2fcb83fbd1612f10c00b2ba14e44c8cfeeafb (Fix some errors reported by phpstan level 2.) that revert some methods declaration to use Entity instead of interface and some other interfaces replaced with classes too.

### What you expected to happen
I need confirmation everyone fine to revert to interfaces back.

**Comment by dereuromark** [comment]
I don't like it either.
But given the fact that new interface methods added can only be done in new majors, there is no current fix for this.
I vote for more majors in quicker release cycles - that would solve this issue probably a bit better than currently.

**Comment by chinpei215** [comment]
By the way, why don't we allow people to change interfaces in minor releases? In my opinion, the compile error `Class X contains n abstract methods` is better than the runtime error `Call to undefined method X::foo()` though.

**Comment by ADmad** [comment]
@skie Where ever the typehint was changed it's because methods were used on the argument which didn't exist on the interface. So if you were to pass an argument which only implemented the interface methods it wasn't going to work anyway.

**Comment by ADmad** [comment]
Take `CounterCacheBehavior::_processAssociation()` for example. The method has a call to `$entity->extractOriginalChanged()`.  `EntityInterface` does not have a `extractOriginalChanged()` to typing the argument as `EntityInterface` was just wrong.

**Comment by ADmad** [comment]
So I am not in favor of reverting that commit. The type hints should be reverted only after the methods used are actually added to the interface.

**Comment by markstory** [comment]
@chinpei215 We've historically not added new methods to interfaces in minor releases as it breaks existing code, as the existing implementation now causes fatal errors, which is not very backwards 'compatible'.

**Comment by inoas** [comment]
So what's the big benefit for not waiting until 4.x aside avoiding a few ignorable phpstan errors?

**Comment by chinpei215** [comment]
@markstory But, for example, the following code will cause a fatal error if people are not using `EntityTrait` to implement their own `EntityInterface` classes, as `EntityInterface` doesn't have the method:
https://github.com/cakephp/cakephp/blob/94f7011941e81226943c368545372818c1bc96ce/src/ORM/Table.php#L1721
And if people are using `EntityTrait`, then no fatal errors occur even if we change the `EntityInterface`.

@inoas No, strictly speaking, there are no ignorable errors, as I said above. I think @ADmad also has explained the same thing above.

**Comment by chinpei215** [comment]
I said  a similar thing in the past: https://github.com/cakephp/cakephp/pull/9919#issuecomment-269415218
But now, we have already separated methods on interfaces into setter/getter. So now I think we should change the problematic interfaces, as compiler error is better than runtime errors.

**Comment by markstory** [comment]
I don't think adding interface methods in minor releases will work out as well as some might think. To the application developer, their code is broken by those kinds of changes.

I agree that compiler errors are better than runtime errors. Perhaps we should continue using the deprecated interface methods until the interfaces can be updated? That would let us keep the typehints for interfaces while also avoiding runtime errors.

**Comment by chinpei215** [comment]
> Perhaps we should continue using the deprecated interface methods until the interfaces can be updated?

It would be a reasonable compromise. Perhaps, we should remove `@deprecate` annotation from the multi-mode methods, and re-add them in 3.6? Otherwise, people will see lots of strike-through in the source code when they open it with IDE. Fortunately, I am using vim though 😛 

Since we would release 3.6 in near future, we might need not to remove `@deprecate` annotations this time, but for the future, I think we should have a consensus what we should do when we want to deprecate methods on interfaces.

**Comment by skie** [comment]
@ADmad potentially we have similar issue in https://github.com/UseMuffin/Webservice/blob/master/src/Model/Resource.php that also provides new Entity by implementing EntityTrait.

**Comment by ADmad** [comment]
@skie Probably. Another way to tackle this is revert back to using interfaces for typehint and add ignores for those errors in phpstan.neon, though that would be technically incorrect.

**Comment by ADmad** [comment]
The webservice plugin doesn't use `EntityTrait::extractOriginal()` or `EntityTrait::extractOriginalChanged()` methods anywhere internally, which are not present in `EntityInterface`. So having it's method use `EntityInterface` typhint for arguments which receive `Resource` instance is not wrong :)
