### ISSUE TITLE
loginRedirect and logoutRedirect is redirecting to webroot in case of using prefix admin.

### ISSUE THREAD

**Issue by kantsverma** [cakephp/cakephp#11059]
I am using the prefix => 'admin' for admin panel. in cakeph 3.4 
**Below are my auth component code that i add in appController**
```php
			$this->loadComponent('Auth', [
				'loginAction' => [
					'controller' => 'Users',
					'action' => 'index',
					'plugin' => false
				],
				//'authorize' => ['Controller'],
				'loginRedirect' => [
					'controller' => 'Users',
					'action' => 'dashboard',
					'plugin' => false
				],
				'logoutRedirect' => [
					'controller' => 'Users',
					'action' => 'index',
					'plugin' => false
				],
				'authenticate' => [
					'Form' => [
						'fields' => ['username' => 'email', 'password' => 'password']
					]
				],
				'unauthorizedRedirect' => false,
				'authError' => 'Did you really think you are allowed to see that?',
				'storage' => 'Session'
			]);
```

**Here is my routes.php code for admin prefix**

```php
	Router::prefix('admin', function ($routes) {
		// Because you are in the admin scope,
		// you do not need to include the /admin prefix
		// or the admin route element.
		$routes->connect('/', ['controller' => 'Users', 'action' => 'index','prefix' => 'admin']);
		$routes->extensions(['json', 'xml']);
		// All routes here will be prefixed with `/admin`
		//$routes->connect('/admin', ['controller' => 'Users', 'action' => 'index']);
		// And have the prefix => admin route element added.
		$routes->fallbacks(DashedRoute::class);
	});	
```

When i login and logout from the admin panel it redirect me to webroot i.e 
Login Case:-  
http://example.com/admin/users/index  (its login url  it will creat the session but redirect to wrong URL )
http://example.com/webroot/admin/dashboard

Logout Case:- 
http://example.com/admin/users/logout (its logout url  it will destroy session but redirect to wrong URL )
http://example.com/webroot/admin

Please help me out how can i resolve this :( 

Regards
Devender 

This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### What happened
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

**Comment by dereuromark** [comment]
Please fix up your template as outlined in bold. Also mention all missing info.
I fixed up your code snippet, please use code fences the next time to highlight and format it properly.
Thank you.

**Comment by markstory** [comment]
Your loginRedirect and logoutRedirect URL array's don't have admin prefixes in them.

**Comment by kantsverma** [comment]
@markstory  should i give the prefix like the below please check if it will be incorrect please let me know.

`  'loginRedirect' => [
	'controller' => 'Users',
	'action' => 'dashboard',
	'plugin' => false,
	'prefix' => 'admin',
],`

**Comment by markstory** [comment]
I think that should work.

**Comment by kantsverma** [comment]
@markstory  when i use the prefix with loginRedirect, logoutRedirect then login is working fine but logout start redirecting to http:example.com/webroot/admin it should redirect to http:example.com/admin

**Comment by kantsverma** [comment]
@markstory  , @VarCI-bot  I fixed the issues by using below code :- 

**Auth Component in appController :-** 

		```php
	$this->loadComponent('Auth', [
 				'loginAction' => [
					'controller' => 'Users',
					'action' => 'login',
					'plugin' => false,
				],
				//'authorize' => ['Controller'],
				'loginRedirect' => [
					'controller' => 'Users',
					'action' => 'index',
					'plugin' => false
				],
				'logoutRedirect' => [
					'controller' => 'Users',
					'action' => 'login',
					'plugin' => false
				],
				'authenticate' => [
					'Form' => [
						'fields' => ['username' => 'email', 'password' => 'password']
					]
				],
				'unauthorizedRedirect' => false,
				//'authError' => 'Did you really think you are allowed to see that?',
				'storage' => 'Session'
			]);
```
Routes Code in routes.php :- 

	```php
Router::prefix('admin', function ($routes) {
		$routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
		$routes->extensions(['json', 'xml']);
		// All routes here will be prefixed with `/admin`
		// And have the prefix => admin route element added.
		$routes->fallbacks(DashedRoute::class);
	});	
```
And finally logout was redirecting to webroot so i use below tricks :- 

	```php
public function logout()
	{
		return $this->redirect($this->Auth->logout().'/');
	}
```
:)

**Comment by pbarbier35** [comment]
Hi !
For your answer, you just must delete folder with the name of your prefix, of your plugin or of your controller, in the webroot folder.

**Comment by shahvirag07** [comment]
Hi,

Run your application with cake command:
**bin/cake server** OR with **make virtual host**

Your application might have same folder as your route prefix inside **webroot** folder.

Thanks,
Virag Shah
