### ISSUE TITLE
loop redirecting by "Auth" component

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11067]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4

### What you did
loop in redirecting by `Auth` when `unauthorizedRedirect` and requested Url is same
for re-product 
```
		    $this->loadComponent('Auth', [
			  'authorize' => [
				      'Controller',
        ],
		    'authError' => 'message',
		    'loginAction' => [
		        'controller' => 'Users',
		        'action' => 'login'
		    ],
		     'unauthorizedRedirect' => ['prefix'=>'admin','controller'=>'Users','action'=>'allowed']
```

```
//UsersController
		public function isAuthorized(){
				return false;
		}
		public function allowed()
		{

		}
```
see this url `example.com/admin/users/allowed`

this cause loop request/redirect 

this action should accept by cake without authorization cycle

**Comment by ADmad** [comment]
Have you added `allowed` to listed of allowed actions using `Auth->allow()`?

**Comment by dereuromark** [comment]
I think he wants this to be "not public", but "accessible" when logged in but not the right role for the other action.

**Comment by saeideng** [comment]
> Have you added allowed to listed of allowed actions using Auth->allow()?
no
I want auto adding to allowed list with cakephp

**Comment by dereuromark** [comment]
You mean you want this URL to be auto-whitelisted for any logged in user?

**Comment by saeideng** [comment]
yes

**Comment by ADmad** [comment]
It's the developer's job to ensure the custom URL set for `unauthorizedRedirect` is accessible by every authenticated user else just leave it to be the default behavior of redirecting back to referrer URL.

I don't think Cake should be automatically making it accessible. Such "automagic" feature have always caused problem.

**Comment by dereuromark** [comment]
Is login key still auto-whitelisted for public? Then this request kind of makes sense as it would be the "same thing" for authorization as the other for authentication.

**Comment by saeideng** [comment]
```
		    'loginAction' => [
		        'controller' => 'Users',
		        'action' => 'login'
		    ],
```
accessible to every user(public action )
so this can be accessible to user(logged in) that have same url 

there are other check list except URL matching ?

**Comment by saeideng** [comment]
also in authorize adapters we no access  to `unauthorizedRedirect` value (and other `auth` params) to change default behavior 
so we can not manage this in our plugins
https://github.com/cakephp/cakephp/blob/5b082ca65cd460c4ace9267be61e9f33143ff1c5/src/Controller/Component/AuthComponent.php#L536

**Comment by markstory** [comment]
> I don't think Cake should be automatically making it accessible. Such "automagic" feature have always caused problem.

Yeah. I'm not interested in opening the potential security issues in people's applications by forcing `unauthorizedRedirect` to be a public action.
