### ISSUE TITLE
Hash::remove()  removes parent array unexpectedly when conditions given.

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11061]
When I tested #11060, I found another bug of Hash::remove().

This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: Non-related.

### What you did

```php
$array = [
    'foo' => [
        'bar' => [
            'baz' => 1
        ],
    ],
];
debug( Hash::remove($array, 'foo.bar') );
debug( Hash::remove($array, 'foo.bar[baz=1]') );
```

### What happened
FIrst output:
```php
[
        'foo' => []
]
```
Second output:
```php
[]
```

### What you expected to happen
FIrst output:
```php
[
        'foo' => []
]
```
Second output:
```php
[
        'foo' => []
]
```

This behavior seems to be intended, and tested here:
https://github.com/cakephp/cakephp/blob/668c0873986adeec2187aaf8f798d1d62306e61a/tests/TestCase/Utility/HashTest.php#L2151-L2165
But I think it  is incorrect. If people want to remove the first-level elements, the path syntax should be: 
```
{n}[Item.id=/\b2|\b4/]
```
Since Hash class doesn't support this syntax at the moment, I added a 'Enhancement' tag too.

**Comment by markstory** [comment]
I'd be worried about changing the behavior at this point. It could cause application breaks as what used to be an empty array becomes a non-empty array.

**Comment by chinpei215** [comment]
Do you think we can change this behavior in 3.6 or 4.0?
Or do you think we should leave it as it is? Then this will be a documentation issue.

**Comment by markstory** [comment]
We could change it in 4.0.

**Comment by chinpei215** [comment]
OK. Thank you for your comments.

**Comment by inoas** [comment]
I still think this is kind if unexpected/defective - and could even hurt production sites with unexpected behavior.

What about introducing a new method, keeping the old one and deprecating it for 4.x?

**Comment by chinpei215** [comment]
I am not sure if we should add a new Hash::delete()? method. We would have to deprecate Hash::remove() in 3.6, but I have heard that `remove` is more common than `delete` when naming methods. Since 4.0 will be released in the not so far future, personally I would wait until then.
