### ISSUE TITLE
[DateTime]Call to a member function format() on null

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#11079]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: Apache2.4 + Mysql5.7 + Win10 + PHP5.6

### What you did
```php
$product = object(App\Model\Entity\Product) {
	'id' => (int) 90462,
	'name' => 'Long Thin Section Shirt Personalized Lace Short Sleeve Large Size Dress',
	'slug' => 'Long-Thin-Section-Shirt-Personalized-Lace-Short-Sleeve-Large-Size-Dress',
	...
	'amazon_price' => (float) 0,
	'modified_at' => object(Cake\I18n\FrozenTime) {

		'time' => '2017-08-23T14:03:43+08:00',
		'timezone' => 'Asia/shanghai',
		'fixedNowTime' => false
	
	},
       ...
};
//The db type  of "modified_at" is "timestamp" in mysql
echo json_encode($product);
```
### What happened
```
[Fatal Error]
Error: Call to a member function format() on null 
File E:\www\slshop\vendor\cakephp\cakephp\src\I18n\DateFormatTrait.php 
Line: 226
```
### What you expected to happen
dumps a valid json string.

**Comment by lorenzo** [comment]
Sounds like this function ins returning null

https://github.com/cakephp/cakephp/blob/master/src/I18n/DateFormatTrait.php#L217

Can you debug around that and see if that is the case?

**Comment by slince** [comment]
@lorenzo  
I have done that. the function `datefmt_create`  returns `null`

**Comment by lorenzo** [comment]
how did you set the timezone to your object?

**Comment by lorenzo** [comment]
Try using `Asia/Shanghai` instead of `Asia/shanghai`

**Comment by slince** [comment]
@lorenzo  
I did not realize that the format of the timezone was wrong ; And I had not met the similar problem
