### ISSUE TITLE
Cannot use object of type Cake\Http\Cookie\Cookie as array

### ISSUE THREAD

**Issue by vonboth** [cakephp/cakephp#11070]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0
* Platform and Target: Apache 2.4, MySQL, OS: Ubuntu
* AuthComponent and CsrfComponent  activated

### What you did
- migrated from latest 3.4. to 3.5.0 via composer
Just tried to start my cake app

### What happened
Cake fails with exception:
Error: Cannot use object of type Cake\Http\Cookie\Cookie as array
Error in: ROOT/vendor/cakephp/cakephp/src/Http/Response.php, line 546
Cake tries to set the csrf token and fails with the above message

### What you expected to happen
Just simply the app to start

**Comment by vonboth** [comment]
This happens probably due to the change to the new middleware.
-> https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html

**Comment by chinpei215** [comment]
Reopen, as this issue looks like a bug. I could reproduce this issue by using the old Dispatcher, or just calling `Response::send()` in a controller:
```php
$this->Cookie->write('foo', 'bar');
$this->response->send();
$this->response->stop();
```

**Comment by markstory** [comment]
I can take a look.

**Comment by markstory** [comment]
Pull request up now.
