### ISSUE TITLE
Translation fallback to msgid_plural not working

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#11089]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13

### What you did

Ran tests of a helper that uses translations.

The code uses this line for translations `'name' => __d('wa', 'Projects'),` Please note that we're using the *singular* translation here and pay attention to the paste of our po file.

### What happened

`'name' => __d('wa', 'Projects'),` doesn't return a non empty string.

### What you expected to happen

Having plural translations falling back to the msgstr. I think this is somehow related to the order in the po file or something. Because we have `msgid "Projects"` and the plural `msgid "Project"`. See the pasted part of our po file below.

I *guess* this is probably related to the way the translated strings are cached inside the translator object.

Doesn't work, empty output.

```
msgid "Projects"
msgstr ""

#: Model/Search.php:95
msgid "Daily News"
msgstr ""

#: Model/Constants/AwardTypes.php:19
msgid "Personal"
msgstr ""

#: Model/Constants/AwardTypes.php:20
#: Template/Element/Competitions/form.ctp:50;52
#: Template/Element/Profiles/panel.ctp:92
msgid "Project"
msgid_plural "Projects"
msgstr[0] ""
msgstr[1] ""
```

Works:

```
msgid "Projects"
msgstr ""

#: Model/Search.php:95
msgid "Daily News"
msgstr ""

#: Model/Constants/AwardTypes.php:19
msgid "Personal"
msgstr ""

#: Model/Constants/AwardTypes.php:20
#: Template/Element/Competitions/form.ctp:50;52
#: Template/Element/Profiles/panel.ctp:92
msgid "Project"
msgid_plural "Projects"
msgstr[0] "Projects"
msgstr[1] "Project"
```

**Comment by markstory** [comment]
I'm pretty sure this was fixed in #10911. What is different about this scenario?

**Comment by burzum** [comment]
I'm at **3.4.13** and it is not working properly in this case. Like I said, I suspect that it is related to the caching or something a collision between the singular and plural or something like that maybe inside the cached translations? I'm not sure, the code around that is not really the most nice to read and understand part of the core. I haven't had more time for this yet.

**Comment by markstory** [comment]
Ok. You're also in a domain file which might complicate the situation. What makes you think it is caching? Have you tried disabling caching?

**Comment by burzum** [comment]
@markomarkovic why did you set it on hold? I just came across another of these issues today in the live app. By caching I mean that the translations are cached in an array or a property of the Po parser or I18n class, I need to debug this... No idea.

```
msgid "Location"
msgid_plural "Locations"
msgstr[0] "Standort"
msgstr[1] "Standorte"

# Some lines later...

msgid "Locations"
msgstr "Standorte"
```

```php
I18n::locale('de');
debug(__dn('wa', 'Location', 'Locations', 0));
debug(__dn('wa', 'Location', 'Locations', 1));
debug(__dn('wa', 'Location', 'Locations', 2));
```

Result:

```
\src\Controller\AppController.php (line 58)
'Standorte'
\src\Controller\AppController.php (line 59)
'Location'
\src\Controller\AppController.php (line 60)
'Standorte'
```

**Comment by burzum** [comment]
@markstory I've added a test here for the case. https://github.com/cakephp/cakephp/tree/3.next-i18n-plural-issue Check that branch out and see how it fails.

**Comment by markstory** [comment]
Thank you for the test. I'll see if I can get a fix together.

**Comment by markstory** [comment]
Pull request open.
