### ISSUE TITLE
How to do commit rollback in CAKEPHP 3.4

### ISSUE THREAD

**Issue by brandboosters1** [cakephp/cakephp#11080]

**Comment by AD7six** [comment]
@brandboosters1 may I ask what you're doing?

Related https://github.com/cakephp/cakephp/issues/11081, https://github.com/cakephp/cakephp/issues/11082

**Comment by brandboosters1** [comment]
There are two model objects. I am saving them to database one by one. But somehow (i don't know the reason) if second model fails to save into database then it becomes a problem in my project. Please Help!!

**Comment by lorenzo** [comment]
what problem are you talking about? Can you be more specific?

**Comment by inoas** [comment]
Can you try to read the answers on your other issues? Join Slack, IRC, etc.
Also the first two links via web search will help you: https://www.google.com/search?q=cakephp+3+transaction&hl=en

**Comment by brandboosters1** [comment]
Thanks for help guys i got the solution.
I used the code given below;
$conn=ConnectionManager::get('default');
$conn->begin();

//1st sql insert query
//2nd sql  insertquery

// all insert work successfully than 
$conn->commit()

//other wise 
$conn->rollback

**Comment by inoas** [comment]
@brandboosters1 please try to use your-faviourite-web-search + http://book.cakephp.org/ + IRC + Slack instead of opening a ton of issues next time :-)?

Good Luck :)
