### ISSUE TITLE
Manipulating Response in View Classes is not possible

### ISSUE THREAD

**Issue by vonboth** [cakephp/cakephp#11084]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: XAMP on Linux, CakePHP 3.5.0

### What you did
Trying to manipulate the Response object with the new 'with...' functions in a View class.
(e.g. AjaxView)

### What happened
Changed in a View class (e.g. default App\AjaxView)  the $this->response object.
e.g.
$this->response = $this->response->withStatus(401) will not update the Response object in the Controller class

### What you expected to happen
The response object to be changed

### Explanations
The with...-functions return a clone of the Response object which has been passed from Controller class.
Setting $this->response in a View class will change the property $this->response in the View class but will not update the Response object in the Controller class.

I believe it is because the object is cloned and is therefore a copy of the original one.
So when you step up from View back to Controller $this->response in the Controller remain unchanged.

The only way to change the Response is to do it directly in the controller, before rendering.
Changing it inside View classes won't work with the 'with....-functions'

Don't know if this is intention and I'm missing something or don't understand this fully.

If one want's to update the Controller then $this->response inside the View class has to be transfered back into the Controller class, e.g. in Controller->render
```
623 $this->View = $this->createView();
624 $rendered = $this->View->render($view, $layout);
625 $this->response = $this->View->response;
626 $this->response->body($rendered);
```

**Comment by markstory** [comment]
pull request up now.
