### ISSUE TITLE
Baking controller within plugin does not keep model associations

### ISSUE THREAD

**Issue by ash123456789** [cakephp/cakephp#11086]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0
* Platform and Target: Apache 2.4.23, MySQL 5.7.14, PHP 7.0.10

### What you did
I ran two commands:

`bin/cake bake controller Groups --plugin Admin`
`bin/cake bake template Groups --plugin Admin`

When running those commands the controller and template files get generated within the plugin. However, when I accessed it through the URL I noticed the permissions part of my form was missing and the associations part of the `add` method were missing. I copied the rest of the code from my original baked version (which didn't have the `--plugin Admin` part) using the following command.

`bin/cake bake controller Groups`

This generated the following code in the `add` method:

```
        $groups = $this->Groups->Groups->find('list', ['limit' => 200]);
        $permissions = $this->Groups->Permissions->find('list', ['limit' => 200]);
```

Thus resulting in the following error after I copied the code above to the plugin version of `GroupsController`:

`Error: Table "Cake\ORM\Table" is not associated with "Groups"`

---

#### Screenshots
Baking without `--plugin Admin`: https://i.shikashi.me/rpjvv
Baking with `--plugin Admin`: https://i.shikashi.me/XnO4b

After copying association code to plugin `Admin` within the `GroupsController` in the `add` method: https://i.shikashi.me/JjxwB

#### Pastebin of related Models
GroupsPermissionsTable: https://pastebin.com/aLYyR2s8
GroupsTable: https://pastebin.com/DLPz5826
PermissionsTable: https://pastebin.com/dKarrN9L

### What happened
Output an error:

`Error: Table "Cake\ORM\Table" is not associated with "Groups"`

### What you expected to happen
Associations to be maintained regardless of using the `--plugin Admin` part of the bake command and not generate an error.

**Comment by markstory** [comment]
It looks like you're getting an auto-model in your prefixed controller instead of the concrete `GroupsTable` class defined in your application. What is `$this->modelClass` in your controller?

**Comment by ash123456789** [comment]
I just used `die($this->modelClass);` and it printed out `Admin.Groups`.

I assume it's trying to use a model within the Admin plugin?

**Comment by ADmad** [comment]
> I assume it's trying to use a model within the Admin plugin?

Yes a plugin controller will by default looks for related model in the same plugin. But the `GroupsTable.php` you have shown is under `App` namepsace instead instead of `Admin` plugin namespace hence a `Table` instance gets used.

Why are you tables under app instead of admin plugin?

**Comment by ash123456789** [comment]
> Why are you tables under app instead of admin plugin?

I wanted the `Admin` part of my site as a plugin so I can easily replace it in the future if I ever decide to redesign it completely and so that the user will have minimal effort in having to replace it.

I wanted the Models in the `App` namespace (the core `src`) since they will almost never change and are going to be used in other places in the future as well, outside the plugin. I was under the assumption that if I left them in the `App` namespace it would use them regardless of whether the code is inside the plugin or not.

**Comment by ADmad** [comment]
Since your models are under `App` namespace you will have to explicitly set the `$modelClass` property for each plugin controller. E.g. `public $modelClass = 'Groups';` in `GroupsController`. Bake can't guess and do this automatically for you hence it has to be done manually.
