### ISSUE TITLE
Undefined TMP constant appears when you run phpunit

### ISSUE THREAD

**Issue by paulop** [cakephp/cakephp#11085]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 
cakephp/cakephp 3.3.16
phpunit/phpunit 5.7.21
* Platform and Target: Windows, Wamp, PHP7, Postgres 9.3

### What you did
Execute >`bin\cake bake test Controller PagesController`

in Class **pagesControllerTest** changes
```
public function testDisplay()
    {
                // No session data set.
        $this->get('/pages/display/home');
        $this->assertResponseOk();

        //$this->assertRedirect(['controller' => 'Users', 'action' => 'login']);

        //$this->markTestIncomplete('Not implemented yet.');
    }
```

Execute `vendor\bin\phpunit tests --stop-on-error --debug`

### What happened
```
There was 1 error:

1) App\Test\TestCase\Controller\PagesControllerTest::testDisplay
Use of undefined constant TMP - assumed 'TMP'

E:\wamp\www\AGILDev\vendor\cakephp\cakephp\src\Network\Session.php:143
E:\wamp\www\AGILDev\vendor\cakephp\cakephp\src\Network\Session.php:97
E:\wamp\www\AGILDev\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:506
E:\wamp\www\AGILDev\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:419
E:\wamp\www\AGILDev\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:338
E:\wamp\www\AGILDev\tests\TestCase\Controller\PagesControllerTest.php:40

ERRORS!
Tests: 128, Assertions: 3, Errors: 1, Incomplete: 126.
```

### What you expected to happen

continue execution normally.

`config\paths.php` it's ok I've not changed this

**Comment by jeremyharris** [comment]
Are you bootstrapping Cake in your tests bootstrap? (Usually by loading the app bootstrap.) Can you post your tests bootstrap file in the report?

**Comment by Benfarhat** [comment]
Sorry for the question but do you have this line:
`parent::setUp();`
in the beginning of your [setUp()](https://book.cakephp.org/3.0/en/development/testing.html#creating-your-first-test-case) function?

**Comment by paulop** [comment]
I noticed that my cake / app is outdated
I cloned again cake / app skeleton.
And I'm doing the merge.
I'll come back to confirm later.

@jeremyharris , @Benfarhat 
Is the same as [cake / app.](https://github.com/cakephp/app/blob/master/tests/bootstrap.php) Thanks for your help.

```
require dirname(__DIR__) . '/vendor/autoload.php';

require dirname(__DIR__) . '/config/bootstrap.php';

$_SERVER['PHP_SELF'] = '/';

```

**Comment by paulop** [comment]
Everything worked
The `phpunit.xml.dist` file was missing
Sorry for the inconvenience.
