### ISSUE TITLE
CakePHP error with json responses bigger than 4096 bytes

### ISSUE THREAD

**Issue by alphp** [cakephp/cakephp#11107]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: Apache/2.4.27 (Win64), PHP/7.1.18TSx64

### What you did
```
public function validar () {
	$this->autoRender = false;
	$this->viewBuilder()->layout('ajax');
	$response['test'] = str_repeat('A', 4096);
	echo json_encode($response);
}
```

### What happened
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4108 of the JSON data
The response includes, in addition to the correct json, a CakePHP error dump:

> Warning (512): Unable to emit headers. Headers sent in file=src\Controller\TestController.php line=*** [CORE\src\Http\ResponseEmitter.php, line 48]
> Warning (2): Cannot modify header information - headers already sent by (output started at src\Controller\TestController.php:***) [CORE\src\Http\ResponseEmitter.php, line 148]
> Warning (2): Cannot modify header information - headers already sent by (output started at src\Controller\TestController.php:***) [CORE\src\Http\ResponseEmitter.php, line 181]
> 

With CakePHP 2.10.1, on the same server, the code does not give error.

### What you expected to happen
Get jason object with 4096 "A"

**Comment by AD7six** [comment]
echo json_encode($response);

`echo` should never be in controller code.

See [the docs](https://book.cakephp.org/3.0/en/views/json-and-xml-views.html) for one way to generate json responses, or [set and return the response object directly](https://book.cakephp.org/3.0/en/controllers/request-response.html#setting-the-body)

**Comment by markstory** [comment]
Closing you cannot echo from the controller in 3.x. This issue only happens with responses larger than 4096 bytes, as your webserver is buffering smaller responses which allows headers to be sent even though you've sent the body first.
