### ISSUE TITLE
ValidatorAwareTrait shouldn't use self::BUILD_VALIDATOR_EVENT

### ISSUE THREAD

**Issue by lilHermit** [cakephp/cakephp#11106]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0

### What you did
Used an Object with uses the ValidatorAwareTrait for example ([Type](https://github.com/cakephp/elastic-search/blob/master/src/Type.php))

### What happened
Get Error "Undefined class constant 'BUILD_VALIDATOR_EVENT'"

### What you expected to happen
No error ;-)

ValidatorAwareTrait should use `Table::BUILD_VALIDATOR_EVENT` or the const should be in ValidatorAwareTrait and Table references `ValidatorAwareTrait::BUILD_VALIDATOR_EVENT`. Another alternative is put the const in `ValidationAwareInterface`. Then ([Type](https://github.com/cakephp/elastic-search/blob/master/src/Type.php)) can `implement ValidatorAwareInterface` this also means the duplicated `DEFAULT_VALIDATOR` can be removed. 

I'll create a pull request once it's decided which way round it should be moved to.

Discuss ;-)

**Comment by lilHermit** [comment]
My vote is for `BUILD_VALIDATOR_EVENT` to be in `ValidatorAwareTrait` as it isn't used anywhere else

**Comment by markstory** [comment]
Traits cannot define constants. The interface would work though.

**Comment by lilHermit** [comment]
@markstory ofc! I'll create a PR and one for `cakephp/elastic-search`

**Comment by robertpustulka** [comment]
What would be the name of a default event defined in `ValidationAwareInterface::BUILD_VALIDATOR_EVENT`? 

Also https://github.com/cakephp/cakephp/blob/master/src/Validation/ValidatorAwareTrait.php#L174 needs to be changed to use `static::BUILD_VALIDATOR_EVENT` if we want to allow to override the constant.

**Comment by burzum** [comment]
@lilHermit it's already fixed in the ES plugin. I had the problem there some time ago https://github.com/cakephp/elastic-search/pull/132/files

**Comment by lilHermit** [comment]
Closed as PR created
