### ISSUE TITLE
Add template options for `hidden()` method

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#11112]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4

### What you did

The `templates` option does not seem to work: 

        dd($this->Form->hidden('my field', [
            'templates' => ['input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>'],
        ]));

Result (ignore the `class` attribute, it is set elsewhere):

        <input type="hidden" name="my field" class="form-control" templates="&lt;input type=&quot;{{type}}&quot; name=&quot;{{name}}&quot;{{attrs}}/&gt;"/>

Instead, the `setTemplates`  works:

        $this->Form->setTemplates([
            'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>',
        ]);
        dd($this->Form->hidden('my field', []));

Result:

        <input type="hidden" name="my field"/>

**Comment by mirko-pagliai** [comment]
Ok, looking at the code, it seems to me that the `templates` option is only supported by the `control()` method. Right?
If so, it would be interesting to use it with any method of the helper.

**Comment by markstory** [comment]
> Ok, looking at the code, it seems to me that the templates option is only supported by the control() method. Right?

Correct.

>  If so, it would be interesting to use it with any method of the helper.

Why? We have `setTemplates()` for that purpose. Adding more complexity and responsibilities to every method that makes specific types of inputs is at odds with trying to have those methods do 1 thing. `control()` is already a higher level method which is why it has the `templates` option.

**Comment by mirko-pagliai** [comment]
> Why? We have setTemplates() for that purpose

Because the `templates` option is only valid once, that is when you are calling the method.
While the `setTemplates()` method modifies the template for subsequent method calls.

In other words, it would be interesting (in my opinion) to have a way for a permanent template change and another way for the current call of the method.

Obviously nothing unreachable. I can do it differently (eg using a widget).

**Comment by markstory** [comment]
Is there a reason you can't use `control()` with `type => hidden`?

**Comment by mirko-pagliai** [comment]
In my particular case, this is the "hidden" field generated automatically by a checkbox.
So I'm rewriting the `hidden()` method to get the template I want. If I use the `setTemplate()` method, the template will be applied to all input types.

**Comment by markstory** [comment]
Wouldn't you need the `templates` option on `checkbox` then?

**Comment by mirko-pagliai** [comment]
I just say that you can not use the `control()` method any time. Especially if he is calling other methods.
In other words: how can I create a checkbox and modify the template for the hidden field, but only for the current call?

**Comment by markstory** [comment]
>  In other words: how can I create a checkbox and modify the template for the hidden field, but only for the current call?

You have to call:

1. `templates()`
2. `checkbox()`
3. `templates()` again to restore the old templates.

**Comment by mirko-pagliai** [comment]
Yes, I know. Or using a widget.

Only these ways seem complex, dignified and can create unwanted effects.

You can evaluate :-)
