### ISSUE TITLE
BASIC auth not working on production server

### ISSUE THREAD

**Issue by RaXaR** [cakephp/cakephp#11119]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0 (also 3.1.x)
* Platform and Target:  
Apache 2.4, 
PHP 7.0.22 (& PHP 5.6.31)
MySQL 5.6.35
CENTOS 7.3 x86_64 standard
(EasyApache 4, FastCGI

### What you did
I installed a vanilla installation of CakePHP to my local development machine and then to the server with specs mentioned above. I then went on to create a simple Users and Posts MVC + DB tables.
I then implemented the Auth example from [Blog Tutorial](https://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html). I did not include the ACL stuff, just simple Auth and I used 'Form'. I ran two tests on both environments (dev & production, 4 tests total). The first test was to login with 'Form' and the second test was to login with 'Basic'.

### What happened
With 'Form' as the Auth method:
On my development machine I can go to the url /users/index and I get prompted for a username + password.
On my production machine I can go to the url /users/index and I also get prompted for a username + password.
So far so good.
With 'Basic' as the Auth method:
On my development machine I get a popup asking for username + password, I fill it out it logs in.
I 'cancel' it shows 'Unauthorized'. 
So working as expected.
On my production machine I get a popup asking for username + password. I fill it out, click 'OK' and the popup shows again, I fill it out again and again again same result. It seems that the production server does not retain the auth credentials for some reason. I can't figure out why though.
-

### What you expected to happen
I expected the 'Basic' Auth to accept and retain my login details after I typed them in. Especially since the 'Form' Auth works fine. :)

### Files
[src.zip](https://github.com/cakephp/cakephp/files/1259664/src.zip)
[dev.001.sql.zip](https://github.com/cakephp/cakephp/files/1259666/dev.001.sql.zip)
username: admin
password: password

**Comment by ADmad** [comment]
Some servers don't populate `$_SERVER['HTTP_AUTHORIZATION']` based on request headers. So make sure it's being populated on your production server. If you are using Apache try adding `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]` to your `webroot/.htaccess`.

**Comment by RaXaR** [comment]
Thanks for the response.
I tried adding the above rewrite rule to /webroot/.htaccess but no change. 
The login popup still loops over and over.

I checked that my Apache modules and PHP extensions are as close a match as I can get them between Dev and Production. However, I'm not 100% sure if I'm overlooking a config somewhere? Any other ideas?

**Comment by RaXaR** [comment]
Update:
I did find that the server is only populating:
$_SERVER['REDIRECT_HTTP_AUTHORIZATION']
but not
$_SERVER['HTTP_AUTHORIZATION']
I'll attempt to use this and see if that works.

**Comment by RaXaR** [comment]
Alright, that seems to have done the trick. 

I made a small addition to the recommendation above, here's my /webroot/.htaccess
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.+)$
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

I added the following to my AppController.php:
```
class AppController extends Controller
{
   public function initialize()
    {
        parent::initialize();
        if (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']) && preg_match('/Basic\s+(.*)$/i', $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], $matches))
        {
            list($name, $password) = explode(':', base64_decode($matches[1]));
            $_SERVER['PHP_AUTH_USER'] = strip_tags($name);
            $_SERVER['PHP_AUTH_PW'] = strip_tags($password);
        }
        // Load components etc...
    }
}
```
I'm not sure why this is happening on the server though, as in which configuration to set but it now works.

Thank you for assist and pointing me in the right direction.

**Comment by feyex** [comment]
I had this same issue recently and the only thing that worked for me was adding **CGIPassAuth On** to my .htaccess file in the server.

**CGIPassAuth On**: This tells the Apache Web server to pass the encrypted username and password to PHP (or any other script) in a variable named HTTP_AUTHORIZATION
