### ISSUE TITLE
'sortWhitelist' doesn't works on public $paginate

### ISSUE THREAD

**Issue by GusAntoniassi** [cakephp/cakephp#11114]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

CakePHP Version: 
Platform and Target:

* CakePHP Version: 3.4.11
* Platform and Target:
Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
Windows NT 10.0 build 15063 (Windows 10) i586
libmysql - mysqlnd 5.0.12-dev - 20150407
Running under XAMPP v3.2.2

### What you did
As noted [in the docs](https://book.cakephp.org/3.0/en/controllers/components/pagination.html#control-which-fields-used-for-ordering), I tried to set `sortWhitelist` params in the `public $paginate` variable in my controller, though it will only work when set on `$this->paginate`.

Test SQL:
```
CREATE SCHEMA IF NOT EXISTS `cakesort_test` DEFAULT CHARACTER SET utf8 ;
USE `cakesort_test` ;

CREATE TABLE IF NOT EXISTS `cakesort_test`.`foos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cakesort_test`.`bars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `foo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bar_foo_idx` (`foo_id` ASC),
  CONSTRAINT `fk_bar_foo`
    FOREIGN KEY (`foo_id`)
    REFERENCES `cakesort_test`.`foos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO foos (name) VALUES ('Foo');
INSERT INTO foos (name) VALUES ('FooBar');

INSERT INTO bars (name, foo_id) VALUES ('Bar', 1);
INSERT INTO bars (name, foo_id) VALUES ('BarFoo', 2);
```
BarsController.php:
```
class BarsController extends AppController {
    public $paginate = [
        'sortWhitelist' => ['id', 'name', 'Foos.name'] // This won't work
    ];

    public function index() {
        $this->paginate = [
            'contain' => ['Foos'],
            // 'sortWhitelist' => ['id', 'name', 'Foos.name'] // Only works when this line is uncommented
        ];
        // ...
    }
// ...
}
```
Template/Bars/index.ctp
```
<th scope="col"><?= $this->Paginator->sort('id') ?></th>
<th scope="col"><?= $this->Paginator->sort('name') ?></th>
<th scope="col"><?= $this->Paginator->sort('Foos.name', 'Foo\'s Name') ?></th>
<th scope="col" class="actions"><?= __('Actions') ?></th>
```

### What happened
`'sortWhitelist'` will not work when set on `public $paginate`, only works when defined on `$this->paginate`.

### What you expected to happen
Well, either it should work when set on `public $paginate` or the documentation should mention using `$this->paginate` instead of `public $paginate`.

I can provide a .zip of the test project if needed.
Best regards.

**Comment by jeremyharris** [comment]
Are you sure you're just not accidentally overwriting the pagination var in the action?

```
public function index() {
        // this *overwrites* the class variable, overwriting all of the settings
        $this->paginate = [
            'contain' => ['Foos'],
        ];
        // ...
    }
```

Perhaps you want this in your action:

```
$this->paginate['contain'] = ['Foos'];
```

**Comment by dereuromark** [comment]
Or what I always do:

    $this->paginate = [
            'contain' => ['Foos'],
    ] + $this->paginate;
