### ISSUE TITLE
unauthorizedRedirect not working in 2.9.9

### ISSUE THREAD

**Issue by noud** [cakephp/cakephp#11111]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9
* Platform and Target: MAMP PRO

### What you did
Hi, I want an unauthorised json message if basic authentication has the wrong password.
Therefor I defined unauthorizedRedirect, like in the code below.
But if I use the wrong password I get the browser login dialog and if I cancel I get the default.ctp with an Unauthorized message.
Is unauthorizedRedirect not working in 2.9.9 or am I implementing it wrong or should I do it whole different to have a REST JSON unauthorised message and if so how do I do that?

this is my code:
```php
<?php

class RestOffersController extends AppController {
	public $uses = array('Offer', 'OfferContract');
	public $helpers = array('Html', 'Form');
	public $components = array('RequestHandler',
		'Auth' => [
			'authenticate' => [
				'Basic' => [
					'passwordHasher' => 'Blowfish',
				],
			],
			'unauthorizedRedirect' => [
				//'admin' => false,
				'plugin' => false,
				'controller' => 'users',
				'action' => 'access_denied',
 				'ext' => 'json',
 				'prefix' => false
			]
		]
	);

	public function index() {
		//ini_set('memory_limit', '-1');
		$offers = $this->Offer->find('all', array(
			'fields' => array(
				'Offer.id',
				'Offer.offer_name',
				'Offer.offer_description',
				),
			'recursive' => -1
			));
		$c = 0;
		foreach($offers as $offer) {
			$offer_contracts = $this->OfferContract->find('all', array(
				'conditions' => array('OfferContract.offer_id' => $offer['Offer']['id']),
				'fields' => array(
					'OfferContract.offer_contract_id',
					'OfferContract.geo',
					'OfferContract.device',
					'OfferContract.offer_link'
				),
				'recursive' => -1
			));
			foreach($offer_contracts as $offer_contract) {
				$offers[$c]['Offer']['OfferContract'][] = array(
					'offer_contract_id' => $offer_contract['OfferContract']['offer_contract_id'],
					'geo' => $offer_contract['OfferContract']['geo'],
					'device' => $offer_contract['OfferContract']['device'],
					'offer_link' => $offer_contract['OfferContract']['offer_link'],
				);
			}
			$c++;
		}
		$this->set(array(
			'offers' => $offers,
			'_serialize' => array('offers')
		));
	}
}

and in UsersController.php I have:

	public function access_denied()
	{
		$loggedIn = $this->Auth->user('id');
		$response = [
			'result' => false,
			'code' => 'access-denied',
			'message' => 'Invalid credentials or access denied.'
		];
		$this->set(compact('loggedIn', 'response'));
		$this->set('_serialize', ['loggedIn', 'response']);
	}
```

### What happened
If I do basic authentication with the wrong password I get the browser login dialog and not
the Users access_denied method.

### What you expected to happen
I expected the Users access_denied method if I do basic authentication with a wrong password.

Thank you,
Noud

**Comment by noud** [comment]
here is my code formatted:

`<?php

class RestOffersController extends AppController {
	public $uses = array('Offer', 'OfferContract');
	public $helpers = array('Html', 'Form');
	public $components = array('RequestHandler',
		'Auth' => [
			'authenticate' => [
				'Basic' => [
					'passwordHasher' => 'Blowfish',
				],
			],
			'unauthorizedRedirect' => [
				//'admin' => false,
				'plugin' => false,
				'controller' => 'users',
				'action' => 'access_denied',
 				'ext' => 'json',
 				'prefix' => false
			]
		]
	);

	public function index() {
		//ini_set('memory_limit', '-1');
		$offers = $this->Offer->find('all', array(
			'fields' => array(
				'Offer.id',
				'Offer.offer_name',
				'Offer.offer_description',
				),
			'recursive' => -1
			));
		$c = 0;
		foreach($offers as $offer) {
			$offer_contracts = $this->OfferContract->find('all', array(
				'conditions' => array('OfferContract.offer_id' => $offer['Offer']['id']),
				'fields' => array(
					'OfferContract.offer_contract_id',
					'OfferContract.geo',
					'OfferContract.device',
					'OfferContract.offer_link'
				),
				'recursive' => -1
			));
			foreach($offer_contracts as $offer_contract) {
				$offers[$c]['Offer']['OfferContract'][] = array(
					'offer_contract_id' => $offer_contract['OfferContract']['offer_contract_id'],
					'geo' => $offer_contract['OfferContract']['geo'],
					'device' => $offer_contract['OfferContract']['device'],
					'offer_link' => $offer_contract['OfferContract']['offer_link'],
				);
			}
			$c++;
		}
		$this->set(array(
			'offers' => $offers,
			'_serialize' => array('offers')
		));
	}
}`

And this is my Users access_denied method:

`	public function access_denied()
	{
		$loggedIn = $this->Auth->user('id');
		$response = [
			'result' => false,
			'code' => 'access-denied',
			'message' => 'Invalid credentials or access denied.'
		];
		$this->set(compact('loggedIn', 'response'));
		$this->set('_serialize', ['loggedIn', 'response']);
	}
`

Now I hope it is readable.
greetings,
Noud

**Comment by markstory** [comment]
Basic Authentication does use redirects. Instead the server sends a client a 401 challenge header and most browsers will re-prompt for basic authentication credentials.

Unfortunately what you want is not possible with Basic authentication.

**Comment by noud** [comment]
Okay clear.
Thank you,
Noud
