### ISSUE TITLE
X-CSRF-Token Header Not Checked in Security Component for DELETE Requests

### ISSUE THREAD

**Issue by kwentworth** [cakephp/cakephp#11129]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1 with Security Component and CSRF Middleware enabled.
* Platform and Target: apache; DELETE request via AJAX.

### What you did
Sent a DELETE request via ajax that included the X-CSRF-Token header.

### What happened
'_Token' was not found in request data error triggered in Security component.

### What you expected to happen
This worked on 3.4.12.  Testing the same code on 3.4.12, a DELETE request doesn't trigger a call to SecurityComponent::_validatePost() and _validToken(). 

Now that _validToken() is being called on DELETE requests, the X-CSRF-Token isn't found in $this->request->getData().

It seems like either _validToken() needs to check for the token using $this->request->getParam('_csrfToken') or not be invoked for DELETE requests.

**Comment by ADmad** [comment]
Csrf token check done by CsrfProtectionMiddleware / CsrfComponent is totally unrelated to the form token check done by SecurityComponent.

> This worked on 3.4.12. Testing the same code on 3.4.12, a DELETE request doesn't trigger a call to SecurityComponent::_validatePost() and _validToken().

Yes this behavior has been explicitly changed in 3.5 for enhanced security to avoid method type spoofing. You need to update your code accordingly to avoid the check done by SecurityComponent for ajax requests.
