### ISSUE TITLE
RedisEngine::increment() and decrement() are broken for infinite duration caches

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#11135]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.12
* Platform and Target: N/A

RedisEngine::increment() and decrement() now attempt to honor the cache duration when initially creating keys.  This change was submitted in tickets #10743, #10786, and #10796.  However, there is a serious issue with the implementation.  If the cache config duration is 0, meaning infinite, then the ttl is set to 0 seconds and thus expires immediately.  Zero duration is handled properly in RedisEngine::write().

**Comment by markstory** [comment]
Pull request open now.
