### ISSUE TITLE
Cache key is too long when numerous cache groups are used

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#11131]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9.
* Platform and Target: Linux, Apache, MySQL, Memcached.

### What you did
We use cache groups. Some groups have many models therefore some values cannot be saved because the memcache key exceeds the maximum cache key length. We set the cache key in `AppModel::_readDataSource` to make it easier to debug, it gets concatenated to a very long cache key generated by the framework in `CacheEngine::key`.

An example of one cache group in core.php:
```
define('MEMCACHE_ORDERS', 'memcache_orders');
$cacheShopGroups = array('Shop', 'ShopCategory', 'ShopCategoryItem', 'ShopItem', 'ShopItemOverride');
$cacheOrderGroups = array('Order', 'ViewOrder', 'OrderCancellation', 'OrderItem', 'OrderNote', 'Payment', 'PaymentCredit');
Cache::config(MEMCACHE_ORDERS, array(
	'prefix' => $prefix,
	'servers' => $memcacheServers,
	'engine' => $memcacheType,
	'duration' => 86400,
	'groups' => array_merge($cacheOrderGroups, $cacheShopGroups),
));
```

In AppModel:
```
	protected function _readDataSource($type, $query) {
		if (isset($query['cache_config'])) {
			$cacheConfigName = $query['cache_config'];
		} else {
			$cacheConfigName = $this->_cacheConfigName;
		}
		// Cache only models that have non empty $_cacheConfigName.
		if (!empty($cacheConfigName) && $this->_isCacheGroupsEnabled) {
			$cacheName = md5(json_encode($query) . json_encode($this->hasOne) . json_encode($this->belongsTo));
			$backtrace = debug_backtrace();
			if (isset($backtrace[2]['function'])) {
				$cacheName .= '_' . $backtrace[2]['class'] . '::' . $backtrace[2]['function'];
			}
			$results = Cache::read($cacheName, $cacheConfigName);
			if ($results !== false) {
				// reset associatons to preserve the Model::_readDataSource() behavior
				$this->resetAssociations();
			} else {
				$results = parent::_readDataSource($type, $query);
				Cache::write($cacheName, $results, $cacheConfigName);
				// Temporary log the size of the cached results it is too high.
				$size = mb_strlen(serialize($results), '8bit');
				if ($size > 307200) { // 300 KB
					$bytes = Utils::formatBytes($size);
					Debugger::log("The size of cached data is $bytes.");
				}
			}
		} else {
			$results = parent::_readDataSource($type, $query);
		}
		return $results;
	}
```
So `Order2117_OrderCancellation6_OrderItem343_OrderNote9_Payment139_PaymentCredit6_Shop437_ShopCategory49_ShopCategoryItem292_ShopItem67_ShopItemOverride178_ViewOrder1_1` key generated by CacheEngine is concatenated to the key generated by AppModel `f0e0eddc0e58639f7ab85f3652a85ab_mymodel::findorders`. The length of the key generated by CacheEngine depends on the number of models in the cache group. 

### What happened
An example of the warning:
```
Warning (512): memcache_orders cache was unable to write 'Order2117_OrderCancellation6_OrderItem343_OrderNote9_Payment139_PaymentCredit6_Shop437_ShopCategory49_ShopCategoryItem292_ShopItem67_ShopItemOverride178_ViewOrder1_1f0e0eddc0e58639f7ab85f3652a85ab_shopcategoryitem::findallwithavailablebookingtimes' to Memcached cache [CORE/Cake/Cache/Cache.php, line 328]
Code Context

Cache::write() - CORE/Cake/Cache/Cache.php, line 328
AppModel::_readDataSource() - APP/Model/AppModel.php, line 649
Model::find() - CORE/Cake/Model/Model.php, line 3010
MyModel::findOders() - APP/Model/MyModel.php, line 582
MyController::orders() - APP/Controller/MyController.php, line 770
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - ROOT/www/index.php, line 107
```

### What you expected to happen
I would expect that the cache key would be short enough, f.ex. to be generated by md5 function.

A possible solution could be to change 
`$prefix = vsprintf($this->_groupPrefix, $this->groups());` to 
`$prefix = md5(vsprintf($this->_groupPrefix, $this->groups()));` in `CacheEngine::key` method.

**Comment by markstory** [comment]
Couldn't you use smaller/shorter group names too?

**Comment by bancer** [comment]
Using shorter group names is quite inconvenient. Using model names as group names makes it very easy to clear caches in AppModel in afterSave and afterDelete:
```
			$configs = Cache::groupConfigs($this->name);
			foreach ($configs[$this->name] as $config) {
				Cache::clearGroup($this->name, $config);
			}
```
This implementation is very close to what is recommended in the cookbook - https://book.cakephp.org/2.0/en/core-libraries/caching.html#using-groups.

**Comment by markstory** [comment]
This key length issue is not unique to memcached, and would exist in redis, apc, wincache and file cache as well.

**Comment by burzum** [comment]
I don't think this is an issue of the framework for the reason Mark named. It's a generic problem you'll face with different cache backends.

If you want to use these long group names create wrapper around them and create a shorter hash for your long names and use that hash for the group names?

**Comment by bancer** [comment]
@burzum We cannot control the entire hash key from the application because it is generated by the framework in [CacheEngine::key](https://api.cakephp.org/2.9/source-class-CacheEngine.html#171-189) method.

**Comment by bancer** [comment]
In fact it is not clear why it was necessary to generate such long hash keys in CacheEngine::key without using md5 as it is recommended in https://api.cakephp.org/2.9/class-Model.html#__readDataSource.
