### ISSUE TITLE
RFC - Command Classes (replacing Shell / Tasks)

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#11137]
The current Shell/Tasks classes have a number of rough spots which are mostly due to features being incrementally added over the years. A short list of the problems I see are as follows:

* Public properties for `args` and `params`. These simple arrays have been partially wrapped with methods, but they are still a bit clunky to use.
* Subcommands can be tasks or shell methods. Having both options makes it hard to give people clear directions on which approach they should use.
* The API of Shell is confusing. Feature both methods like `out()` `err()` and `abort()` as well as user land code. Shell has too many concerns.

## Focused Commands

If shells were stripped down their goals are to provide a series of 'commands'. Each command is effectively a callable that can be invoked from the CLI. The callable could have the input/output wrappers passed in removing the need for most state in a command.

Sub-commands can be created by mounting commands in a nested fashion. For example `bake test` could be a name that points to `Bake\Console\Console\TestCommand` while `bake controller` could be a name that resolves to `Bake\Console\Console\ControllerCommand`. Each command can focus on only the task they need to accomplish.

## Code Reuse in Commands

If each command is single purpose, we'll need a good way to share logic between commands. We've had good success so far with Traits being utilized to allow access to models, logging and mailers. We can leverage those traits in Commands to cover most of the need for shared logic. In addition to traits, we can improve ShellHelpers to enable more code re-use.

Shared option parser settings is another place where I can see logic needing to be shared. This can be addressed by enabling option parsers to be standalone classes like we did with validators.

## Command Life-Cycle

Commands would have the following life-cycle:

1. `CommandRunner` locates a command based on the CLI arguments.
2. `CommandRunner` constructs the command. The `CommandCollection` would be injected if necessary.
3. The `Command.initialize` event would be triggered. Calling the command's `initialize()` hook if defined.
4. The command's OptionParser is created with `getOptionParser()`
5. CLI options are parsed. An error will be output if required options/arguments are missing.
6. Help might be displayed if requested.
7. The command's `execute()` method would be called receiving the `InputArguments` and `ConsoleIo` objects as parameters.
8. The return value of the command would be converted into an exit code, and passed out to the CLI environment.

## Arguments class

The `Arguments` class provides an interface for interacting with the parameters and passed arguments in a command. It is passed to commands after the CLI arguments have been parsed, and would feature methods like:

```php
// Get all parameters
$input->getParams();

// Get the parameter. No default option as defaults are defined in the option parser.
$input->getParam('debug');

// Bool if parameter is defined.
$input->hasParam('optional_thing');

// Get all arguments
$input->getArguments();

// Get the first argument by position
$input->getArgumentAt(0);

// Get arguments by name
$input->getArgument('classname');

// Bool if argument exists
$input->hasArgumentAt(0); $input->hasArgument('classname');
```

## ConsoleIo & ConsoleOptionParser

Theses classes would be unchanged from today. I think the current API of them works pretty well.

## Command Example

An example showing the various classes in concert could look like:

```php
<?php
// Namespace change
namespace App\Console;

use Cake\Console\Command;
use Cake\Console\ConsoleIo;
use Cake\Console\Arguments;

class OrmCacheBuildCommand extends Command
{

    public function execute(Arguments $input, ConsoleIo $io)
    {
        $schema = $this->getSchema($input->getParam('connection'));
        if (!$schema) {
            $io->err('No schema found.');
            return false;
        }
        $tables = $input->getArguments();
        if (empty($tables)) {
            $tables = $schema->listTables();
        }
        foreach ($tables as $table) {
            $io->verbose('Building metadata cache for ' . $table);
            $schema->describe($table, ['forceRefresh' => true]);
        }
        $io->out('<success>Cache build complete</success>');

        return true;
    }
}
```

## Command Bundles

If commands are single purpose, we'll want a way for console 'applications' to be built in a way that host applications can easily consume them. Take `bake` as an example. A developer should not have to manually add all of the bake commands to their command list. Instead we'll need a simple way for them to add all the commands as a single bundle. Self contained console applications will likely come from plugins. We can extend `Application` to handle plugin loading and introduce 'plugin classes' that interact with the application's bootstrapping process to add console commands.

The core console commands could be added through the same 'plugin class' system. This should remove the need to autodiscover commands, as both CakePHP and plugins will use the same system to add their commands. At a high-level, 'plugin classes' would add their console commands *before* `Application::console()` is called so that the application can replace/remove any commands provided by plugins.

## Subcommands

Sub-commands do not exist in a single purpose command class system. Instead 'subcommands' are bound to the command collection as commands with spaces in their names.

```php
$commands->add('bake controller', ControllerCommand::class);
```

### Shell will exist in 4.0

While we would be deprecating `Shell` in 3.6, we would not be removing it in 4.0. Deprecating and removing a key base class like Shell this late in the life of 3.6 will make upgrading to 4.0 harder as applications & plugins will need to rebuild all of their shell commands. Instead, `Shell` will not be removed until 5.0.0

#### Changelog

1. Clarify when Shell would be removed.
2. Separate methods for reading positional arguments by index an name.
3. Fix initialize order for commands.
4. Rename InputArguments to Arguments

**Comment by chinpei215** [comment]
So would people have to rewrite all existing shells if they want to upgrade their applications to 4.0?

**Comment by markstory** [comment]
@chinpei215 I don't think that would make for an easy upgrade. I'm inclined to say no, and leave the existing `Shell` class in until 5.0. We could still remove other parts of the 'old' console libraries, leaving `CommandRunner` as the only entrypoint into the CLI environment.

**Comment by dereuromark** [comment]
Regarding the API I would suggest not to mix different types of input and behavior here (also in regards of future more strictness of parameters):
```
// Get the first argument
$input->getArgumentAt(0);

// Get arguments by name
$input->getArgument('classname');

// Bool if argument exists
$input->hasArgumentAt(0); 
$input->hasArgument('classname');
```
etc (hasArgumentAt vs hasArgument are two different things IMO)

Regarding the ConsoleIO typehint:
It would be good if in light of this refactoring we would also come up with what I personally find the biggest issue in our current CLI communication layer: Too much coupling specific to this layer, especially what should be business logic instead to be easier reusable also from Web Controllers. See https://github.com/cakephp/cakephp/issues/10202#issuecomment-299044069

Ideally some kind of Web+CLI common Io/Flashbag handling that would then allow to pass in the wrapped ConsoleIO in order to allow dynamic output.
Otherwise you are forced to stay in the Console and thus too much business logic is forced to be put here.

With IdeHelper I wrote a [IO](https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/Console/Io.php) wrapper that already goes a bit in that direction, a common interface that allows to write some feedback from the business logic, separated from the Console itself and thus also available as Controller invoked classes then if needed.

**Comment by inoas** [comment]
:+1: for not mixing named and position based arguments.

**Comment by markstory** [comment]
@dereuromark Good point on not mixing int|string methods for positional arguments. I've updated the proposal with the methods you suggested.

**Comment by robertpustulka** [comment]
@dereuromark I like the idea of abstracting the IO "layer".
How about separating the input from output and abstracting these? Both in CLI/Web.

The command could look something like this:
```php
use Cake\Console\IO\InputInterface;
use Cake\IO\OutputInterface;

class ExampleCommand extends Command
{

    public function execute(InputInterface $input, OutputInterface $output) 
    { 
        $input->getArgument('foo');
        $input->hasArgumentAt(1);
        ...
        if ($ok) {
            $output->success('All good');
        } else {
            $output->success('Something went wrong');
        }
    }
}
```

We could have `Cake\Http\IO\InputInterface` as well that would abstract interaction with request query/data. Both could extend some general `Cake\IO\InputInterface` for CLI/Web agnostic business classes if necessary.

**Comment by markstory** [comment]
@robertpustulka could flashcomponent and a console class implement a shared interface? That would save us a few class additions.

**Comment by dereuromark** [comment]
I didnt say that the Console command itself needs to use that shared Io handler, there are some CLI specific things like progressbar that are unique to that domain. And in that communication layer perspective it is fine to use the ConsoleIO and the full possibilities of it. 
But once you delegate into shared code in business layer you would need the abstraction layer with some very basic output handling at least.
I know that task is difficult, and I cannot offer too much concrete solutions yet at this time, either.
Just wanted to get the idea out there, maybe someone has come up with something related.

**Comment by robertpustulka** [comment]
@markstory yes, I was thinking that we could implement `OutputInterface` in `FlashComponent` and `ConsoleIO`. I'm not sure about `InputInterface` - would it be possible to abstract the input both for CLI and Web. That's a rough idea now.

@dereuromark right, the Console command should use the console specific classes and interfaces. But those classes and interfaces could implement/extend shared ones so it would be easier to pass the input and output to the business logic classes that would be cli/web agnostic. 

Something like:

```php
use Cake\IO\InputInterface;
use Cake\IO\OutputInterface;

//business logic
class LogicHandler
{
    public function _invoke(InputInterface $input, OutputInterface $output)
    {
        ...
    }
}

//command
class LogicCommand extends Command
{

    public function execute(ConsoleInput $input, ConsoleOutput $output) 
    { 
        $handler = new LogicHandler();
        $handler($input, $output);
    }
}

//controller
class LogicController extends Controller
{
    public function execute()
    {
        $handler = new LogicHandler();
        $handler($this->request, $this->Flash);
    }
}
```

**Comment by dereuromark** [comment]
Anything left, or shall we close?

**Comment by markstory** [comment]
Documentation has not been completed yet.

**Comment by markstory** [comment]
Closing as this is done barring bug discovery.
