### ISSUE TITLE
trim warning in Cake\View\Helper::addClass when $options['class'] is an array

### ISSUE THREAD

**Issue by huwcbjones** [cakephp/cakephp#11132]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13.
* Platform and Target: nginx/1.13.4 , MariaDB/10.1.26, php7.0-fpm/7.0.19-1
### What you did
Passing an array of class attributes to a Form field results in a warning in `\Cake\View\Helper.php:183` when the field has an error state, where `Helper::addClass(array $options = [], $class = null, $key = 'class')` is not designed to handle an array of class attributes in the `$option` parameter.

The following results in a trim warning when a modelless form is validated in the controller method.
```
/* template.ctp */
<?= $this->Form->password('new_password', ['class' => ['form-control']]) ?>

/* Controller.php */
$modellessForm->validate($this->request->getData())
```
### What happened
Warning displayed where a parameter passed to trim `trim` was array.

### What you expected to happen
Internally, element gets added to array of classes.
Externally, no trim warning.

**Comment by markstory** [comment]
Closing as a pull request is open now.
