### ISSUE TITLE
Potential bug with marshaller data casting and form helper

### ISSUE THREAD

**Issue by obinoob** [cakephp/cakephp#11138]
* [x] bug

* CakePHP Version: 3.5.1
* Platform and Target: Ubuntu 14.04.5 LTS trusty, MySql Server version: 5.6.33-0ubuntu0.14.04.1, PHP 7.0.21-1~ubuntu14.04.1+deb.sury.org+1

### Creating a Form Control
When creating a form within a view with the following code:

https://gist.github.com/obinoob/cd08bf40719a2d8b2f6c53d553f33c8b

### Problem
The generated select box gets 0 as default selection, this is not happening in the same system under cakephp v3.2.12. I've created two scenarios 1) a new entity/controller/view with DB connection etc (just like my earlier project) 2) modeless form, and I found that the 1) has the same behaviour 2) has the expect correct behaviour. This issue has been discussed over #cakephp and been followed by hmic. Apparently the marshaller is forcing the form data to the database datatype, which is boolean (tinyint(1)) in my case. As the invalid option manually added didn't worked I have no further solution. I also tried empty=>true and select 0 by default both didn't worked.

### Expected Behaviour
I do expect a selection box with 'invalid' option to be default before any submit is made. I also refuse to use a checkbox instead due to the use case which obligates a user to choose a value.

**Comment by ADmad** [comment]
> The generated select box gets 0 as default selection,

Does this happen when the form is generated initially for GET request?  Because the marshaller wouldn't be involved at this point. Only if you patch the entity (which would be during PUT/POST request) would the marshaller be used.

**Comment by obinoob** [comment]
Indeed, the described behaviour happens when the form is generated by the initially GET request.

**Comment by markstory** [comment]
Are you creating the form with a new entity? How is that entity created/

**Comment by obinoob** [comment]
The entity is created inside the controller add action and it follows the following structure: 

https://gist.github.com/obinoob/84411299fc230582fc153ac3379fbd85

**Comment by markstory** [comment]
Does your schema define defaults for the field in question?

**Comment by obinoob** [comment]
By schemas I assume you're referring to the Model layer? If so, yes I have defined both classes Entity and Table ($validator rules as well)... the app was working just fine before upgrading to 3.5.0 and later  3.5.1! So I think that my app is no questionable, definitely this is about cake's internals. I would like to help more if you provide me with more intel.

**Comment by obinoob** [comment]
$validator
            ->boolean('equipment_hermetically_closed')
            ->inList('equipment_hermetically_closed', ['0', '1'])
            ->notEmpty('equipment_hermetically_closed');

**Comment by ADmad** [comment]
> By schemas I assume you're referring to the Model layer?

No, he means have you defined a default value for that field in db table schema?

**Comment by obinoob** [comment]
Ups sorry yes I've...
equipment_hermetically_closed, tinyint(1), unsigned, default => 0

**Comment by ADmad** [comment]
> equipment_hermetically_closed, tinyint(1), unsigned, default => 0

Right, so `EntityContext` uses that value as default that's why it's selected. This behavior has existed since Cake 3.3. For your use case you can specify `'default'` in `FormHelper::control()` options to override the schema default or set `schemaDefault` to false.

**Comment by obinoob** [comment]
It makes perfect sense now, unfortunately never used CakePHP above 3.2.
Thank you for letting me know. I'm glad it's not a bug :-)
