### ISSUE TITLE
$this->Url->build not populating _ext when method is located outside plugin

### ISSUE THREAD

**Issue by nilsonpena** [cakephp/cakephp#11144]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: CENTOS 7, APACHE

### What you did
From a plugin template view, I´d like to generate an url to a method located in my parent App.
Tried using Router::url and  $this->Url->build. Both generate a request with _ext = null. The .json sufix get added to the method name (ajaxSendMail.json), that obviusly does not exist in OrdensServicosController.

Note, if the method is located in any controller plugin (plugin not null) every things works as expected.

In config/routes.php I've using:
```php
use Cake\Routing\Router;
Router::extensions(['json', 'pdf']);
```

on my plugin template:

```javascript
 $.ajax({
                url: '<?= $this->Url->build(["plugin" => null, "controller" => "OrdensServicos", "action" => "ajaxSendMail", "_ext" => "json"]); ?>',
                data: {
                    os_id: "<?php echo $tarefa_usuario->ordens_servico_id; ?>"
                },
                method: 'POST',
. . . 
```

### What happened
The resulting request is:

```php
object(Cake\Http\ServerRequest) {
	params => [
		'controller' => 'OrdensServicos',
		'action' => 'ajaxSendMail.json',
		'pass' => [],
		'plugin' => null,
		'_matchedRoute' => '/:controller/:action/*',
		'_ext' => null
	]
	data => [
		'os_id' => '31530'
	]
```

### What you expected to happen

I´d expect the following request:

```php
object(Cake\Http\ServerRequest) {
	params => [
		'controller' => 'OrdensServicos',
		'action' => 'ajaxSendMail',
		'pass' => [],
		'plugin' => null,
		'_matchedRoute' => '/:controller/:action/*',
		'_ext' => 'json'
	]
	data => [
		'os_id' => '31530'
	]
```

**Comment by markstory** [comment]
What does your entire routes file look like? Right now I'm not able to reproduce your error.

**Comment by nilsonpena** [comment]
This is my APP config/route.php
`<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;


Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {

    $routes->connect('/', ['controller' => 'Usuarios', 'action' => 'login']);
    $routes->connect('/logout', ['controller' => 'Usuarios', 'action' => 'logout']);
    $routes->connect('/login', ['controller' => 'Usuarios', 'action' => 'login']);

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);


    $routes->fallbacks(DashedRoute::class);
});


Router::extensions(['json', 'pdf']);
Plugin::routes();
`
And this is my Plugin config/route.php

`<?php

use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
        'Laudador', ['path' => '/laudador'], function (RouteBuilder $routes) {
    $routes->fallbacks(DashedRoute::class);
});`

**Comment by markstory** [comment]
You're enabling extension parsing **after** the routes have been connected. You need to enable extension parsing **before** routes are connected, or they won't have extension parsing added into them.

**Comment by nilsonpena** [comment]
Perfect @markstory 
Thank You!!
