### ISSUE TITLE
Logging email fails due to array to string conversion

### ISSUE THREAD

**Issue by obinoob** [cakephp/cakephp#11147]
* [x] bug

* CakePHP Version: 3.5.1
* Platform and Target: Linux 3.19.0-25-generic 14.04.1-Ubuntu SMP x86_64 GNU/Linux, PHP 7.0.21-1~ubuntu14.04.1+deb.sury.org+1 (cli), MySQL Server version: 5.6.33-0ubuntu0.14.04.1 (Ubuntu)

When log is set to true

```
'Email' => [
        'default' => [
            'transport' => 'default',
            'from' => 'mail@domain.com',
            'log' => true
        ],
    ],
```

Array to string conversion fails at class Email.php line 2087.
The _logDelivery function under Email.php is trying to convert an array to a string and it's failing as expected.

Fixed with:

```
PHP_EOL . $this->_isKeyArray($contents['headers']) . PHP_EOL . PHP_EOL . $this->_isKeyArray($contents['message']),

private function _isKeyArray($key = null)
{
   return is_array($key) ? implode(';', $key) : $key;
}
```

**Comment by markstory** [comment]
What transport are you using? The SmtpTransport, MailTransport, and DebugTransport that come with CakePHP appear to only return strings for headers out of `send()`.

**Comment by markstory** [comment]
Closing as there is a pull request for further discussion #11149
