### ISSUE TITLE
Message context for relative time formatter translations

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#11143]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1

---

The [**relative time formatter**](https://github.com/cakephp/cakephp/blob/3.5.1/src/I18n/RelativeTimeFormatter.php) uses message IDs like `{0} days`, which, depending on the language and the context, might need to be translated differently.

In german for example `10 days` in `diffFormHumans()` needs to translate to `10 Tagen` (as in `vor 10 Tagen` oder `in 10 Tagen`) [**in case `$isNow` is `true`**](https://github.com/cakephp/cakephp/blob/3.5.1/src/I18n/RelativeTimeFormatter.php#L79), while it needs to translate to `10 Tage` (as in `10 Tage vorher` oder `10 Tage später`) in case `$isNow` is `false`.

In `timeAgoInWords()` and `dateAgoInWords()` it needs to translate to `10 Tagen` (as in `vor 10 Tagen`) [**in case `$backwards` is `false`**](https://github.com/cakephp/cakephp/blob/3.5.1/src/I18n/RelativeTimeFormatter.php#L149), while it probably needs to translate to `10 Tage` in case `$backwards` is `true`. "Probably" because in the latter case the date/time parts are being [**returned as is**](https://github.com/cakephp/cakephp/blob/3.5.1/src/I18n/RelativeTimeFormatter.php#L165), ie without the use of any wrappers like `{0} ago`, meaning that the context is unclear, but most likely used as in `Zeit bis X: 10 Tage` (`Time till X: 10 days`).

I guess similar problems might exist with other languages too, it's just a little nag, but still quite annoying, especially when the grammar police is around. Maybe different contexts per method, and based on `$isNow` and `$backwards` are a possible solution...

**Comment by markstory** [comment]
I'm open to adding contexts to the messages if we can figure out a way to do it without breaking existing translations. If we can't this change would have to wait until 4.0.0

Related to #7747

**Comment by burzum** [comment]
I had to deal with an extreme case of this. I personally have seen zero return of investment in it for our project but I was asked to do it any way. ;)

We had cases like these:

* From 1st October to 2nd October (All day)
* From 1st October 10pm to 2nd October 2am (two days with start and end time)
* From 31st December to 2nd January 2018 (going into a new year)

You can see some of them here, but we don't have many online with times AFAIK.

https://www.world-architects.com/en/events

There are a bunch more cases and all of this had to be translateable because the I18n format of the dates provided by the core was not always what the people liked, for example in Japanese. 

At the end of the day I ended up implementing a class that deals with the logic that determines what conditions are met, an abstract class for the actual time spans per language as base class and a helper that glues all of the stuff together. I couldn't get the requirements implemented with just i18nFormat() alone nor the plain ICU formatting options it offers.

Here is an example of our Japanese time span class. The helper instantiates the correct class depending on the locale with a fallback. For example if you try de_ch and it's not present it will fallback to de. Maybe some of our code could be useful for a better implementation in the core.

```php
<?php
declare(strict_types = 1);

namespace App\View\Helper\TimeSpan;

/**
 * JaTimeSpan
 *
 * Add your special cases for japan here
 */
class JaTimeSpan extends DefaultTimeSpan {

	/**
	 * @return string
	 */
	protected function _sameDayAndAllDay() {
		return $this->_startDate->i18nFormat('YYYY.L.dd');
	}

	/**
	 * @return string
	 */
	protected function _notSameDayAndAllDay() {
		$date = $this->_startDate->i18nFormat('YYYY.L.dd')
			. ' - '
			. $this->_endDate->i18nFormat('YYYY.L.dd');

		if ($this->_noPastDateOutput && $this->_isStartDatePast) {
			$date = $this->_endDate->i18nFormat('d LLLL YYYY') . ' まで';
		}

		return $date;
	}

	/**
	 * @return string
	 */
	protected function _sameDayNoDifferentTime() {
		if ($this->_noTimeOutput) {
			return $this->_startDate->i18nFormat('YYYY.L.dd');
		}

		return $this->_startDate->i18nFormat('YYYY.L.dd, HH:mm');
	}

	/**
	 * @return string
	 */
	protected function _sameDayDifferentTime() {
		if ($this->_noTimeOutput) {
			return $this->_startDate->i18nFormat('YYYY.L.dd');
		}

		return $this->_startDate->i18nFormat('YYYY.L.dd, HH:mm')
			. ' - '
			. $this->_endDate->i18nFormat('HH:mm');
	}

	/**
	 * @return string
	 */
	protected function _notSameDayNotAllDayNoDifferentTime() {
		$startFormat = 'YYYY.L.dd, HH:mm';
		$endFormat = 'YYYY.L.dd';
		if ($this->_noTimeOutput) {
			$startFormat = $endFormat = 'YYYY.L.dd';
		}

		$date = implode(' ', [
			$this->_startDate->i18nFormat($startFormat),
			'-',
			$this->_endDate->i18nFormat($endFormat),
		]);

		if ($this->_noPastDateOutput && $this->_isStartDatePast) {
			$date = $this->_endDate->i18nFormat($endFormat) . ' まで';
		}

		return $date;
	}

	/**
	 * @return string
	 */
	protected function _notSameDayNotAllDayDifferentTime() {
		$startFormat = $endFormat = 'YYYY.L.dd, HH:mm';
		if ($this->_noTimeOutput) {
			$startFormat = $endFormat = 'YYYY.L.dd';
		}

		$date = implode(' ', [
			$this->_startDate->i18nFormat($startFormat),
			'-',
			$this->_endDate->i18nFormat($endFormat),
		]);

		if ($this->_noPastDateOutput && $this->_isStartDatePast) {
			$date = $this->_endDate->i18nFormat($endFormat) . ' まで';
		}

		return $date;
	}
}
```

This class implements the logic to determine the case we have:

```php
<?php
declare(strict_types = 1);

namespace App\Model;

use Cake\Chronos\Chronos;
use Cake\I18n\Time;

/**
 * TimeSpan
 *
 * @link https://github.com/World-Architects/WA3/issues/1090
 */
class TimeSpan {

	/**
	 * @var bool
	 */
	protected $_isSameDay = false;

	/**
	 * @var bool
	 */
	protected $_allDay = false;

	/**
	 * @var bool
	 */
	protected $_differentYear = false;

	/**
	 * @var bool
	 */
	protected $_startDatePast = false;

	/**
	 * @var bool
	 */
	protected $_differentTimes = false;

	/**
	 * @var \Cake\Chronos\ChronosInterface
	 */
	protected $_startDate;

	/**
	 * @var \Cake\Chronos\ChronosInterface
	 */
	protected $_endDate;

	/**
	 * @param string|\Cake\Chronos\ChronosInterface $startDate Start Date
	 * @param string|\Cake\Chronos\ChronosInterface $endDate End Date
	 */
	public function __construct($startDate, $endDate) {
		if (is_string($startDate)) {
			$startDate = new Time($startDate);
		}

		if (is_string($endDate)) {
			$endDate = new Time($endDate);
		}

		$this->_startDate = $startDate;
		$this->_endDate = $endDate;

		$this->_processDates();
	}

	/**
	 * Processes dates
	 *
	 * @return void
	 */
	public function _processDates() {
		$this->_differentYear = (
			$this->_startDate->format('Y') !== $this->_endDate->format('Y') ||
			$this->_startDate->format('Y') > Chronos::today()->format('Y')
		);

		$this->_startDatePast = $this->_startDate->isPast();
		$this->_isSameDay = $this->_startDate->format('d') === $this->_endDate->format('d');
		$this->_differentTimes = $this->_startDate->format('H:i') !== $this->_endDate->format('H:i');
		$this->_allDay = $this->_startDate->format('H:i') === '00:00' && $this->_endDate->format('H:i') === '00:00';
	}

	/**
	 * @return bool
	 */
	public function isDifferentYear() {
		return $this->_differentYear;
	}

	/**
	 * @return bool
	 */
	public function isDifferentTime() {
		return $this->_differentTimes;
	}

	/**
	 * @return bool
	 */
	public function isAllDay() {
		return $this->_allDay;
	}

	/**
	 * @return bool
	 */
	public function isSameDay() {
		return $this->_isSameDay;
	}

	/**
	 * @return bool
	 */
	public function isSameDayAndAllDay() {
		return $this->_isSameDay && $this->_allDay;
	}

	/**
	 * @return bool
	 */
	public function isNotSameDayAndAllDay() {
		return !$this->_isSameDay && $this->_allDay;
	}

	/**
	 * @return bool
	 */
	public function isSameDayAndNoDifferentTime() {
		return $this->_isSameDay && !$this->_differentTimes;
	}

	/**
	 * @return bool
	 */
	public function isSameDayAndDifferentTime() {
		return $this->_isSameDay && $this->_differentTimes;
	}

	/**
	 * @return bool
	 */
	public function isNotSameDayAndNotAllDayAndNoDifferentTime() {
		return !$this->_isSameDay && !$this->_allDay && !$this->_differentTimes;
	}

	/**
	 * @return bool
	 */
	public function isNotSameDayAndNotAllDayAndDifferentTime() {
		return !$this->_isSameDay && !$this->_allDay && $this->_differentTimes;
	}

	/**
	 * Get the start date of the time span
	 *
	 * @return \Cake\Chronos\ChronosInterface
	 */
	public function getStartDate() {
		return $this->_startDate;
	}

	/**
	 * Get the end date of the time span
	 *
	 * @return \Cake\Chronos\ChronosInterface
	 */
	public function getEndDate() {
		return $this->_endDate;
	}

	/**
	 * Is start date is past
	 *
	 * @return bool
	 */
	public function isStartDatePast() {
		return $this->_startDatePast;
	}

}
```
