### ISSUE TITLE
SQL Injection After Order clause

### ISSUE THREAD

**Issue by millancore** [cakephp/cakephp#11148]
* [x] bug

* CakePHP Version: 3.1 to 3.5
* Platform and Target: ORM

### What you did
It is possible to execute SQL sentences after "order" clause
Examples: 

```php
   $query = $this->Assets->find('all',array(
           'contain' => array(
              'Attributes' => array(
                 'sort' => array(
                    'Attributes.name' => "DESC; UPDATE assets SET name = 'inject' WHERE id = 1"
                 )
              )
          ),
          'order' => array(
              'name' => "DESC; UPDATE assets SET name = 'inject' WHERE id = 1"
          )
        ));
```

### What happened
SQL UPDATE executed!

### What you expected to happen
I expected that it doesn't possible!

**Comment by markstory** [comment]
You are inserting snippets of SQL into the QUERY builder, why would you expect different results?

**Comment by millancore** [comment]
I am not sure if this way is correct, I created an API that extends ORM and  I make SQL injection test this happened, at this moment I sanitize all data but I don't know this is a bug or not.

**Comment by markstory** [comment]
You should be using a whitelist for your order fields and directions. We have to support sql snippets in order by clauses to provide support for advanced ordering in postgres and SQLServer. I can update the API docs to make it clearer that order fields/directions are treated as raw data.

**Comment by millancore** [comment]
I'll keep that in mind. Thanks

**Comment by lorenzo** [comment]
We could maybe deprecate that and force people to use `QueryExpression`?

**Comment by markstory** [comment]
@lorenzo It looks like he's using the 2.x compatible `find('type, $options)` call type. I'm not sure we can require query expressions there.

In general I'm :+1: for requiring `QueryExpression` to be the vehicle that raw SQL needs. The extra object prevents accidents as user supplied data will have a very hard time accidentally ending up in an expression object.

**Comment by inoas** [comment]
What about dropping the 2.x compatible way in 4.x then?

**Comment by burzum** [comment]
I agree with @inoas, we should already flag this as deprecated in the next release.

**Comment by markstory** [comment]
@inoas Makes sense to me. Care to put together a pull request for it?

**Comment by markstory** [comment]
Closing as the documentation aspects of this have been fixed.
