### ISSUE TITLE
HtmlHelper::link fullBase option

### ISSUE THREAD

**Issue by huwcbjones** [cakephp/cakephp#11140]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP Version: 3.4.13.
* Platform and Target: nginx/1.13.4 , MariaDB/10.1.26, php7.0-fpm/7.0.19-1

### What you did
Used `$options['fullBase' => true]` in `HtmlHelper::link()`.
Output linkdid not contain full base.
Method options are inconsistent as `fullBase` is accepted as an option in the rest of `HtmlHelper`/`UrlHelper` options.

### What happened
Output link did not contain full base.

### What you expected to happen
Output link contains full base.

**Comment by markstory** [comment]
Closing as a pull request is open now.
