### ISSUE TITLE
3.5 : propertyName problem with Paginator

### ISSUE THREAD

**Issue by Kareylo** [cakephp/cakephp#11159]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: bin/cake server with Postgres on Windows 10 Pro - Enterprise Edition

### What you did
Just create a default Paginate using contain 
```php
<?php
$questions = $this->paginate($this->Questions->find()->contain(['ParentQuestions', 'Users', 'Intents', 'ProposedIntents', 'Clusters', 'DeletedBy', 'ProposedBy']));
```

With table like this
```php
<?php
        $this->belongsTo('ProposedBy', [
            'className' => 'Users',
            'foreignKey' => 'proposed_by',
            'propertyName' => 'id'
        ]);
        $this->belongsTo('DeletedBy', [
            'className' => 'Users',
            'foreignKey' => 'deleted_by',
            'propertyName' => 'id'
        ]);
```

### What happened
While sorting whatever I want, The Question.id become an User ID

### How to solve it
Need to specify className in propertyName like 
```php
<?php
        $this->belongsTo('DeletedBy', [
            'className' => 'Users',
            'foreignKey' => 'deleted_by',
            'propertyName' => 'Users.id'
        ]);
```

I'm sure it's a stupid problem, but I think the propertyName should be mixed with className.

**Comment by markstory** [comment]
Property names are inflected from the association names. You need to define the property name if you want something different. Changing that now will break existing applications and is not something we can do.
