### ISSUE TITLE
RFC: Log translation package / file loading

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#11156]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13

### What you did
Debugging a locale related issue

### What happened
Had to dig through the cores I18n implementation to find the place where the locale files are loaded and add my debug code there.

### What you expected to happen
It would be nice to have a `LogLevel::NOTICE` log entry written to the debug log stream if a file was not found. Debug kit could / should show loaded translation files / packages as well. An I18n tab might be nice to get an overview for everything i18n related.

Something like that in __invoke() of MessageFileLoader:

```php
            Log::notice(sprintf(
                'Failed to load `%s` for locale `%s`',
                $path,
                I18n::locale()
            ));
```

**Comment by saeideng** [comment]
I think debug_kit should be show loaded translation files if possibles
this information is very useful

**Comment by markstory** [comment]
I don't know if 'notice' is the best level, perhaps 'debug'?

**Comment by burzum** [comment]
I'm OK with that as well.

**Comment by makallio85** [comment]
+1

**Comment by dereuromark** [comment]
Are you able to make a PR here?

**Comment by ADmad** [comment]
Closing as the issue has gone stale and there hasn't been any follow up in a long time.
