### ISSUE TITLE
setLayout using plugin syntax is not working

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#11168]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: built in server, mysql, os x

### What you did
![screen shot 2017-09-07 at 8 55 47 am](https://user-images.githubusercontent.com/2320614/30164480-aa1c7fba-93aa-11e7-8ed4-9c8839ce259c.png)
![screen shot 2017-09-07 at 8 56 12 am](https://user-images.githubusercontent.com/2320614/30164502-c89c3dc2-93aa-11e7-826b-3c26ffe3c92e.png)

### What happened
![screen shot 2017-09-07 at 8 55 44 am](https://user-images.githubusercontent.com/2320614/30164483-b23d7b4a-93aa-11e7-98e9-aa2c39b48ecb.png)

### What you expected to happen
![screen shot 2017-09-07 at 8 59 03 am](https://user-images.githubusercontent.com/2320614/30164525-d68ed69c-93aa-11e7-8534-577d0c5d4048.png)

I am creating a project to reproduce this problem now, I will post a repo shortly...

**Comment by jeremyharris** [comment]
I believe the folder should be Layout (singular) as indicated by the error message :)

**Comment by jeffreyroberts** [comment]
lol, my bad
