### ISSUE TITLE
Problem with fastcgi_finish_request

### ISSUE THREAD

**Issue by ictgtvt** [cakephp/cakephp#11162]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.12
* Platform and Target: Nginx, PHP-FPM 7.0, Mac OS, Mysql server

### What you did
I wrote a Custom database session handler extends from `Cake\Network\Session\DatabaseSession`.

### What happened
When the network is slow (My PC connected to a Database server), the subsequent request read the session data before it's parent request finish writing session changes to database. So changes of the parent request is not applied.

> We can emulate this by using `sleep()` in `write()` function of Session.
```php
class CustomDbSessionHandler extends DatabaseSession {
    // Some code ...

   public function write($id, $data)
    {
           sleep(5);

           // Some code
    } 

    // Some code
}

```

### What you expected to happen
I see that the problem is coming from the `fastcgi_finish_request` (http://php.net/manual/en/function.fastcgi-finish-request.php, http://php.net/manual/en/function.session-write-close.php)

> Another important thing is session handling. Sessions are locked as long as they're active (see the documentation for session_write_close()). This means subsequent requests will block until the session is closed.

> You should therefore call session_write_close() as soon as possible (even before fastcgi_finish_request()) to allow subsequent requests and a good user experience.

Perhaps that we have to call the `session_write_close()` before `fastcgi_finish_request()`, in `src/Http/ResponseEmitter.php`.
Another way is calling `session_write_close()` everytime we want to make sure that session is written for the subsequent request.

**Comment by markstory** [comment]
>  Another way is calling session_write_close() everytime we want to make sure that session is written for the subsequent request.

You can do that. I don't think that will require any changes from CakePHP though. What are you hoping to see change in CakePHP to solve this issue?

**Comment by ictgtvt** [comment]
Thank for your response :) Could we add `session_write_close() ` before calling `fastcgi_finish_request()` in `Cake\Http\ResponseEmitter` ? Is there any side effect ? 

```php
if (function_exists('fastcgi_finish_request')) {
            session_write_close(); // Add here
            fastcgi_finish_request();
}
```

**Comment by markstory** [comment]
I don't know what the side-effects of that would be. I don't use fastcgi webservers. You could give it a try test in production and report back on how it works.

**Comment by ictgtvt** [comment]
> You could give it a try test in production and report back on how it works.

I was add `session_write_close()` before `fastcgi_finish_request()` in production code. It worked fine. 
```php
if (function_exists('fastcgi_finish_request')) {
            session_write_close(); // Add here
            fastcgi_finish_request();
}
```

Session is always saved before it call to `fastcgi_finish_request()`, even I put `sleep(2)` in `write()` of Custom Database session handler. The subrequest alway wait until the previous request finish writing session to database. My problem is resolved 👍

**Comment by ndm2** [comment]
Should this maybe be invoked independently of fast CGI usage?

Session locking is generally a problem, especially when sending files, which is why `session_write_close()` is invoked in the deprecated `Response::_sendFile()`, but there is no equivalent for the new `Http/Server` flow, where `Response::send()` isn't invoked anymore.

**Comment by markstory** [comment]
> but there is no equivalent for the new Http/Server flow, where Response::send() isn't invoked anymore.

There could be. The `ResponseEmitter` could close the session off.

**Comment by markstory** [comment]
I took a look at how the framework could automatically close the session and we don't have access to the session object in `ResponseEmitter` and I worry that directly calling `session_write_close()` will cause state to drift between the request's session object and PHP's state.

The only reasonable place I could see to add a session close would be inside [Server::run](https://github.com/cakephp/cakephp/blob/21c8fce5ca8b68292b948a28606006faa935b579/src/Http/Server.php#L98-L107) once the response has been created.

What do you think of that approach @ndm2 ?

**Comment by ndm2** [comment]
I wouldn't expect userland code to fiddle with something like sessions on emitter level, so `Server::run()` sounds good to me.
