### ISSUE TITLE
Integration test fails with named routes using cakephp/app 3.5

### ISSUE THREAD

**Issue by batopa** [cakephp/cakephp#11160]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: Apache 2.4, MySQL 5.7. Integration tests

### What you did
Doing an Integration test in an app (updated to cakephp/app 3.5) that have named routes. The middleware stack was used.

### What happened
The test fails throwing a `DuplicateNamedRouteException` but there aren't duplicate in `_name` option.

### What you expected to happen
Test should be ok.

**Comment by markstory** [comment]
Closing as a pull request is open now.
