### ISSUE TITLE
2.x - 2.10.2 has a non-BC change to flash messages

### ISSUE THREAD

**Issue by kierenpitts** [cakephp/cakephp#11178]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.2
* Platform and Target: Ubuntu 16.04, MySQL

### What you did
In the 2.10.2 release there's a non-BC change on handling flash messages in the old syntax. Obviously the syntax for flash messages changed in 2.10.x but the old syntax still worked up until 2.10.2. It's not clear from the release notes for 2.10.2 if the backwards compatibility was intentional and broken accidentally with this release or if the old syntax should not have worked in any 2.10.x release. 

### What happened
CakePHP 2.10 and 2.10.1 still supported:
$this->Session->setFlash('Some message');

but 2.10.2 produces an error message and you need to update the above to:
$this->Flash->set('Some message');

Similarly, this doesn't work in 2.10.2 but did work in 2.10 and 2.10.1:
<?php echo $this->Session->flash(); ?>

it needs to be this in 2.10.2:
<?php echo $this->Flash->render() ?>

### What you expected to happen
It's not clear if the old syntax should not have been supported in 2.10 and 2.10.1 or whether it should continue to be supported in 2.10.2. Either way it would be better to document the change in case it catches anyone out.

Have also discussed this on IRC with hmic and inoas

**Comment by markstory** [comment]
This might be fixed by #11124 which was recently merged.

**Comment by kierenpitts** [comment]
Cool, thanks for the info.
