### ISSUE TITLE
Text::tokenize() allows only a single separator

### ISSUE THREAD

**Issue by julianpollmann** [cakephp/cakephp#11188]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.2

### What you did
Cake\Utility\Text::tokenize() allows just one seperator as argument. A given String cannot seperated by several separators e.g the String `simple, file, 123.img` cannot be tokenized by `.` and `,` at the same time.

The method should tokenize by a separator array.

**Comment by markstory** [comment]
How would multiple separators work with the boundary options?

**Comment by dereuromark** [comment]
This sounds more like a plugin scope and custom kind of method outside of the core (use) case.
Once proven useful there, you can sure re-introduce for core as PR. I would consider closing this for the time being then.
