### ISSUE TITLE
Quotes with DISTINCT inside COUNT

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11186]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Tested on 2.9.6 and latest 2.10.2
* Platform and Target: WAM(MSSQL)P

### What you did
Using `COUNT` with `DISTINCT` on built-in SQL Server driver.

### What happened
`SELECT COUNT(DISTINCT User.id) AS [count] FROM [users] AS [User]`

### What you expected to happen
Should add quotes/bracklets to `DISTINCT` field, like this:
`SELECT COUNT(DISTINCT [User].[id]) AS [count] FROM [auth_users] AS [User]`
but it does not.

Solutions is to rebuild lines 301-304: https://api.cakephp.org/2.10/source-class-Sqlserver.html#301-304
to:
```
	if (strpos($fields[$i], 'DISTINCT') !== false) {
		$prepend = 'DISTINCT ';
		$fields[$i] = trim(str_replace('DISTINCT', '', $fields[$i]));

		if (strpos($fields[$i], 'COUNT(') !== false) {
			$prepend = 'COUNT(' . $prepend;
			
			$fields[$i] = trim(str_replace('COUNT(', '', $this->_quoteFields($fields[$i])));
		}
	}
```
It will be works with usinq bracklets for field inside `COUNT(DISTINCT alias.field)`.

**Comment by markstory** [comment]
Any chance you could make a pull request for this?

**Comment by markstory** [comment]
Pull request open now.
