### ISSUE TITLE
Load bootstrap_cli.php of a plugin

### ISSUE THREAD

**Issue by igorfelluga** [cakephp/cakephp#11184]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.2

### What you did
In documentation (https://book.cakephp.org/3.0/en/console-and-shells/plugin-shell.html#loading-plugins) I found that to load bootstrap_cli of a plugin I must use bin/cake plugin load --cli MyPlugin, that add 
Plugin::load('MyPlugin');
but it didn't load it.

**Comment by markstory** [comment]
That bake command modifies the application`bootstrap_cli.php` instead of the general one. It does not change how plugin bootstrapping works.

If plugins have cli only bootstrap code, it is up to each plugin to conditionally load it as necessary. Perhaps in the future plugins will have a more formalized pattern for this.

**Comment by igorfelluga** [comment]
Is there a way that when I use command
bin/cake bake template Features --prefix Admin -t MyTheme
it load the plugin bootstrap_cli where I have setted this event ?
EventManager::instance()->on(
    'Bake.beforeRender.Controller.controller',
    function (Event $event) {
        $view = $event->getSubject();
            // add the login and logout actions to the Users controller
            $view->viewVars['actions'] = [
                'index',
                'view',
                'add',
                'edit',
                'delete',
                'online'
            ];
    }
);

**Comment by dereuromark** [comment]
@igorfelluga I updated your post to properly highlight the code. Please see the format and add it yourself for future posts like this.

**Comment by markstory** [comment]
@igorfelluga Of course there is.

```php
// in YourPlugin/config/bootstrap.php

// other code

if (PHP_SAPI === 'cli') {
    require __DIR__ . '/bootstrap_cli.php';
}
```

**Comment by igorfelluga** [comment]
Thanks

**Comment by dereuromark** [comment]
Can be part of https://github.com/cakephp/cakephp/pull/11564 discussion.

**Comment by Tomicapo** [comment]
@markstory I tried implementing your suggestion to make "bake" use my plugin's bootstrap_cli but it didn't work.

My plugin is being loaded here:

app/config/bootstrap.php
```php
// rest of the file
Plugin::load('CoderThemes', ['bootstrap' => true, 'routes' => true]);
```

app/plugins/CoderThemes/config/bootstrap.php
```php
// this is not being reached
if (PHP_SAPI === 'cli') {
	require __DIR__ . '/bootstrap_cli.php';
}
```
The code above (plugin/boostrap) never get executed when running `bin/cake bake controller Whatever`
I even tried to add `-t CoderThemes` but still, nothing happened.

CakePHP version: 3.6.6
Bake version: 1.8.1
OS: Windows 10
Server: Xampp

Am I doing something wrong?

**Comment by markstory** [comment]
Does your plugin's bootstrap file run at all?
