### ISSUE TITLE
Content Security Policy Inline Style Issues. Please allow a nonce or custom class.

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#11192]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.4.13 f9cd66fe071d1cfb2fa6aec94ee37a7fd0916c03
* Platform and Target: Apache/2.4.26 (Ubuntu)

### What you did
I am attempting to enact a strict content policy and only allow inline styles that contain a unique nonce per request. This is not possible with the Security Components CSRF protection or the FormHelper. Each of these include ```<div style="display:none"></div>``` with no ability to set a nonce.  

With apache mod_unqiue_id enabled I have the following in my vhost

```
<Directory /var/www/foo>
Header unset Content-Security-Policy
Header add Content-Security-Policy "default-src 'self' 'nonce-%{UNIQUE_ID}e' fonts.googleapis.com fonts.gstatic.com code.jquery.com www.google.com"

Header unset X-Content-Security-Policy
Header add X-Content-Security-Policy "default-src 'self' 'nonce-%{UNIQUE_ID}e' fonts.googleapis.com fonts.gstatic.com code.jquery.com www.google.com"
</Directory>
```

### What happened

Because I cannot set a nonce in FormHelper the browser (Chrome 59) throws the following in my console:

```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 'nonce-WbrU8n8AAAEAAAp6oCIAAAAD' fonts.googleapis.com fonts.gstatic.com code.jquery.com www.google.com". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

login:49 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 'nonce-WbrU8n8AAAEAAAp6oCIAAAAD' fonts.googleapis.com fonts.gstatic.com code.jquery.com www.google.com". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

### What you expected to happen
I would expect to be able to do both of the following:

1. Instead of a display:none inline style, I should be able to use a class. Some users may want to completely disallow  all inline styles and this would allow them to do that by defining a class which has the display:none property.

2. I should be able to set a nonce attribute on the hidden divs. This would satisfy my scenario here.

Either will do for me, but I believe both should be implemented.

I am aware some issues have been opened on this matter:

https://github.com/cakephp/app/issues/426
https://github.com/cakephp/cakephp/issues/7511

But it seems unresolved and I feel like the solutions I offered have no impact on backwards compatibility as long as these are just new elements added into the existing arrays for FormHelper::create() and end() where the defaults are the current behavior. Furthermore there are probably issues with DebugKit, but it may not be worth addressing since its not meant for production.

**Comment by markstory** [comment]
Have you tried replacing the [hiddenBlock template](https://api.cakephp.org/3.5/class-Cake.View.Helper.FormHelper.html#$_defaultConfig)? It controls the div you want to change.

**Comment by cnizzardini** [comment]
Ahh damnit, that was a lot of bug report to type for an easy solution.
