### ISSUE TITLE
RecordNotFoundException custom message not in the response.

### ISSUE THREAD

**Issue by deanoj** [cakephp/cakephp#11191]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.5.2
* Platform and Target: Apache 2.4, windows and ubuntu.

### What you did
If `Debug=true`, and I throw RecordNotFoundException from a controller action - eg:

`throw new RecordNotFoundException("My custom message") `

then I see "My custom message" in the HTTP response.

If I set `Debug=false`, then the custom message is NOT in the response, but a default one: "Not found"

### What happened
Debug mode = false prevents to custom message from been used when throwing a RecordNotFoundException.

### What you expected to happen
I expect my custom message to be used.

**Comment by markstory** [comment]
This is intentional. Exception messages often contain sensitive information that should not be disclosed in production. If you want to expose exception messages you can customise the error handlers for your application.
