### ISSUE TITLE
Add support easy "Google App Engine for PHP"

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#11204]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Since all the material that is online or repositories fails and is not simple to implement.
It would be very good an official version to install within Google App Engine for PHP.

**Comment by markstory** [comment]
I don't use app engine, but what problems do know of?

**Comment by EOM** [comment]
Hello, the idea was if the community share support via report GIT or tutorial in Book CakePHP or just inside the same version of cakephp. The basis for being able to run the FW within Google App Engine = GAE, only with a set of settings.
For example I after renegar manage to run CakePHP 3.3.x in stable version of GAE that supports PHP 5.5.x. for the CakePHP version> = 3.4 you have to do it with GAE version Flex that is in Beta.

The base configuration is only way with 1 file for CakePHP 2.10.x "app.yaml" GAE stable.
CakePHP 3.3.x GAE stable "app.yaml and php.ini" and CakePHP> = 3.4.x GAE version flex in Beta "app.yaml php.ini and composer.json".

The free version only only supports stable GAE free, GAE flex version requires invoice. And using Google SQL requires invoice. But it's good to have GAE support for people who use CakePHP to have a qualitative jump to scalable system like the one offered by GAE.

That is the idea that CakePHP supports in a simple way with that files the option to make simple deploy on a platform like GAE.

I hope the idea is clear and that Google Traslator clear my idea.

**Comment by markstory** [comment]
Why would we favour App Engine over all other hosting providers. Heroku, PagodaBox, and others? So far we've been trying to make it easy to configure CakePHP via environment variables as those changes make it easier to run CakePHP applications in all containerized environments.

**Comment by ADmad** [comment]
Closing as there's nothing to be done here. We don't favour any particular hosting provider nor it is feasible for us to provide documentation for deploying on various different providers which specifics for each.

This the something the community needs to help with, for e.g. writing blog posts with details about deploying on a specific provider.
