### ISSUE TITLE
2.x: Auto add empty string for default value in ORM

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11205]
When working on an older cake2 app I found a tons of issues with MySQL5.7 now regarding default values for SQL inserts.

    Error: SQLSTATE[HY000]: General error: 1364 Field 'comment' doesn't have a default value

This has been working in MySQL 5.6 and below so far.

Those schema definitions have been left

	'default' => null,
	'null' => false,

Intentionally, so that those would be filled with an empty string when saved.

Is it feasible for the ORM to detect that the default value is null and null is false in order to then set those fields automatically to the right empty value, in this case empty string `''`?

After all the validation came through and the only reason of failure here is now the stricter DB - which can be resolved in a BC way by providing the required strings here.

Rewriting the whole code, or the complete migration seems more painful for an older app here before it can be fully migrated.

**Comment by markstory** [comment]
> Is it feasible for the ORM to detect that the default value is null and null is false in order to then set those fields automatically to the right empty value, in this case empty string ''

If you've made a field required in the schema and defined no default, I don't think the ORM should be trying to guess a default value for you. This sounds like it is an application specific pain you're going through as you move to MySQL5.7. Your current schema would have never 'worked' in postgres for example.

**Comment by slince** [comment]
You can execute 'set global sql_mode = 0' to avoid this.

**Comment by dereuromark** [comment]
Fair enough. It would have just been rather easy to figure out the default values here for certain types like string columns..

I added a help script to generate a migration needed for all non key fields of this type:
https://github.com/dereuromark/cakephp-setup/blob/master/src/Shell/DbMigrationShell.php#L32
This helps to mitigate the effects of the changes on the DB level.
Closing then as works-for-me.

**Comment by inoas** [comment]
Why don't you simply set the comment to `DEFAULT ''` in your RDBMS sql schema?

**Comment by dereuromark** [comment]
That's exactly what the script does now for all 1xx tables and thus 4xx fields now automatically.

**Comment by dereuromark** [comment]
Actualy, default '' does not work for text columns :/

    ALTER TABLE albums CHANGE `description` `description` text NOT NULL DEFAULT ''

> #1101 - BLOB/TEXT-Feld 'content' darf keinen Vorgabewert (DEFAULT) haben

But changing it to null I do not want, because many queries explicitly expect the empty values to be the empty string here.

It seems here the ORM and CakePHP could actually help out to allow continue working with the database, just as it was working before. Simply check the default value and set it to the empty string for text and varchar column types on create.

**Comment by inoas** [comment]
I don't think there should be any/much magic. Default values should be derived from the SQL Schema.
Exception: If in case of SQL text fields there is nothing to derive, the Schema tools of CakePHP could help with injecting a default value that can then be used if the entity is new and the field is null.

**Comment by dereuromark** [comment]
That is exactly what I am proposing to easy developer's life here, there is also no downside of this, and makes the create vs update also more consistent, especially working with forms for update (where the incoming empty string would also be `''` whereas a create with this optional one missing would otherwise be `null` and prevent saving (exception!).
