### ISSUE TITLE
Why can't I extract from my collection?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#11201]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: PHP 7.1.8

### What you did
```php
class RuleCollection extends Collection
{
    public function __construct($items = [])
    {
        $items = [
            new BandwidthRule(),
            new BroadbandTypeRule(),
            new ComponentsRule(),
            new ContractLengthRule(),
            new PackageTypeRule(),
            new PriceRule(),
            new ProviderRule(),
            new UnlimitedBroadbandRule()
        ];

        parent::__construct($items);
    }
}
```

```php
$ruleNames = $rules->extract('name')->toArray();
```

I had to create a `RuleTrait` for all the rules which implements the `toArray()` method to get the rules to show up in DebugKit.

### What happened
`Error: Uncaught Error: Cannot use object of type App\Lib\CatalogImportRules\BandwidthRule as array in /vendor/cakephp/cakephp/src/Collection/ExtractTrait.php:108`

### What you expected to happen
I wanted an array of names from the objects for my template select input.

/cc Copying in @hmic as we had a chat on irc about it.

> check the Cake\Collection\Iterator\ExtractIterator::unwrap() method. this needs to support toArray() in addition to ArrayAccess on the underlying object

**Comment by markstory** [comment]
Why do we need to support `toArray()`? Couldn't your objects implement `ArrayAccess` if you want to put them into a Collection?

**Comment by lorenzo** [comment]
Your objects need to implement `ArrayAccess`

**Comment by davidyell** [comment]
Perhaps this should be documented? If it isn't already

**Comment by lorenzo** [comment]
@davidyell good call, I'm not sure if it is already documented, do you want to give us a hand with that?

**Comment by davidyell** [comment]
Sure, I'll try and find some time today once I have my collections working. Hopefully then, I'll have a solid grasp of what's involved, as I have a nested collections as well.

**Comment by davidyell** [comment]
It also seems that the Collection cannot deal with nested custom collections either.
