### ISSUE TITLE
Error autocompletion bash commands

### ISSUE THREAD

**Issue by Labelsuisse** [cakephp/cakephp#11207]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Since version 3.5 the autocompletion of the commands no longer works.
Here is the error message: Exception: Unknown command `cake Completion`. Run `cake --help` to get the list of valid commands. in [/../vendor/cakephp/cakephp/src/Console/CommandRunner.php, line 173]

I'm on a unix system.

Thank you for your help

**Comment by dereuromark** [comment]
Is this related to https://github.com/cakephp/cakephp/issues/11174 ?

**Comment by Labelsuisse** [comment]
No, this is when I do bin / cake bake <tab>, I have this error << Exception: Unknown command `cake Completion`. >>

**Comment by dereuromark** [comment]
I think it is exactly like the linked docs issue @ https://github.com/cakephp/docs/pull/5261
So this PR already fixed it, see latest dev-master (and soon a new bugfix release tag).

**Comment by Labelsuisse** [comment]
Ok, thank's you. I closed this ticket
