### ISSUE TITLE
Validation : deep datas path

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#11206]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.2
* Platform and Target: php7

### What you did
I'm storing settings datas in a json encoded field into database : 
`{"discord":{"url":"https:\/\/discord.gg\/DhJRtgH"}}` and field name is "audios", so i can add settings for teamspeak3, mumble, discord, .... in one field.

My form field is somethong like 
```php
$this->Form->control('audios.discord.url', [ 'label' => __("Invitation Url"), 'placeholder' => 'https://discord.gg/abcdef' ]);
```

My validation rule is : 
```php
$validator
    ->allowEmpty('audios.discord.url')
    ->regex('audios.discord.url', 'https://discord.gg//', __("Invalid discord invitation"));
```

### What happened
The datas from $controller->request are 
```
[
	'audios' => [
		'discord' => [
			'url' => 'https://discord.gg/DhJRtgH'
		]
	]
]
```
but the validation check for path : 
```
/src/Validation/Validator.php (line 117)
'audios.discord.url'
```
Maybe it can be cool if we use Hash::flatten() on datas of \Cake\Validation\Validator::errors() ?

**Comment by markstory** [comment]
You may need to use [nested validators](https://book.cakephp.org/3.0/en/core-libraries/validation.html#nesting-validators) for this. But you're correct that right now we don't provide great support for nested field validation.
