### ISSUE TITLE
patchEntity validates values before calling mutator

### ISSUE THREAD

**Issue by akalantari** [cakephp/cakephp#11212]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: v3.4.11
* Platform and Target: nginx, MySQL with InnoDB on php 7.0.23-1+ubuntu16.04.1+deb.sury.org+1

### What I did
I have field in my database called `salary` and as its name suggests, it contains an integer that is salary amount. In GUI, user enters the value and jQuery adds commas so the amount is easily read ('100,000,00' e.g.).
I added a mutator in the entity class to prevent it from raising an error while saving
```
protected function _setSalary($value) {
    return str_replace(',','',$value);
}

```
### What happened
What happens is that when I use `patchEntity` function, the default `Marshaller::merger` validates fields and when validator raises an error (obviously it does have error when it wont call mutator!), merger ignores calling the mutator and it won't save the entity.

### What I expected to happen
I believe that Validator should try to evaluate the return value of mutator, not the raw value that is passed.

**Comment by ADmad** [comment]
Validations and done for the request data not entity properties. If you want to do checks on entity use [application rules](https://book.cakephp.org/3.0/en/orm/validation.html#applying-application-rules).

**Comment by akalantari** [comment]
There's a gap here. We can use `set` to use mutators but it won't validate the data, or we can use `patch` that validates data but won't use mutators. My problem is not that I want to do check on entity properties, it's that it won't use mutators when using `patchEntity`

**Comment by ADmad** [comment]
If you want to modify data before validation then use `beforeMarshal` callback instead of entity mutators.

**Comment by inoas** [comment]
I believe you can use validators in the entity too, so you can set things and throw an exception if the value set does not pass the validator?
