### ISSUE TITLE
2.x - have an option to allow empty POST requests after the security component change

### ISSUE THREAD

**Issue by iglocska** [cakephp/cakephp#11215]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10
* Platform and Target: apache, mysql.

### What you did
POST request to an API that uses a POSTed JSON to filter the returned data with an empty payload

### What happened
POST request blackholed

### What you expected to happen
POST request not blackholed, non-truncated data-set returned

We heavily rely on POSTed requests for filtering in cakephp and it seems like 2.10's new Security component changes break a lot of the tools that we are interconnected with, that pass an empty payload in POST requests when no filter parameters are set. 

We understand that this is probably not something that can be reverted, but could there be a global setting that disables this feature?

**Comment by markstory** [comment]
You could disable SecurityComponent when you get an empty POST body.
