### ISSUE TITLE
Bug in CakeEmail matching pattern

### ISSUE THREAD

**Issue by IonutBurlacu** [cakephp/cakephp#11221]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9.
* Platform and Target: Windows, Apache, MySql.

### What happened
Trying to send an email to an address like `*****@threesheets_bar.co.uk` using CakeEmail is throwing an error saying that the email is invalid, even if it isn't.

### What you expected to happen
I would expect that the matching pattern from CakeEmail.php to allow also the `_` character in the email domain name.

**Comment by gemal** [comment]
should perhaps also be backported to cakephp 2.x?

**Comment by dereuromark** [comment]
Resolved with https://github.com/cakephp/cakephp/issues/11221 in 2.x, 3x can be built from that PR.
