### ISSUE TITLE
Saving hasMany association together with new entity

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#11223]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1
* Platform and Target: PHP 7.1.9

### What you did
invoice is an existing entity object.

```php
# App\Controller\RemittanceAdvicesController;
    $entity = $this->RemittanceAdvice->newEntity(null, [
        'associated' => ['Invoices'],
    ]);
    $entity->invoices[] = $invoice;

    $entity->dirty('invoices', true);
    $this->RemittanceAdvices->save($entity);
```

### What happened
`debug($entity);` does not show associated data, `$entity->invoices[] = $invoice;` seems not to work.
`$entity` is created but reference is not stored in existing `$invoice->remittance_advice_id` column.

### What you expected to happen
`$invoice` should be updated with id of `$entity`.

**Comment by markstory** [comment]
I'm guessing your entity starts off with `invoices` as `null`. Because of how entity properties work you'll likely need to initialize `invoices` with `$entity->invoices = []`, and then append to it.

If your invoices never show up in your entity the ORM will not be able to persist them.

**Comment by swiffer** [comment]
ok, thanks for that. tried to figure out whats missing literally for hours. maybe we can improve the docs in similar to the warning about marking the entity dirty?

https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-hasmany-associations

if appreciated i'll do that, just notify here.

**Comment by markstory** [comment]
Was the solution to initialize the property with an empty list?

**Comment by swiffer** [comment]
Yes, worked flawlessly. Ok, I'll try to do that 😄
