### ISSUE TITLE
Email pattern does not match RFC3696

### ISSUE THREAD

**Issue by Benfarhat** [cakephp/cakephp#11229]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.1

Constante [EMAIL_PATTERN](https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L90) does not match **double-quote examples** given in [RFC3696](https://tools.ietf.org/html/rfc3696) and **Literal IPV6** in domain name [RFC2732](https://tools.ietf.org/html/rfc2732)

RFC3696 - page 5:
>    In addition to quoting using the backslash character, conventional
>    double-quote characters may be used to surround strings.  For example
> 
>       "Abc@def"@example.com
> 
>       "Fred Bloggs"@example.com

And theses [examples ](https://en.wikipedia.org/wiki/Email_address#Examples) too:

    "very.unusual.@.unusual.com"@example.com
    "very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com
    "()<>[]:,;@\\\"!#$%&'-/=?^_`{}| ~.a"@example.org
    " "@example.org (space between the quotes)
    user@[2001:DB8::1]

Wich contain an example with litteral IPV6 address in the URL - [RFC2732](https://tools.ietf.org/html/rfc2732)

This pattern work for double quote:
```
^(((?:[\p{L}0-9.!#$%&\'*+\/=?^_`{|}~-]+)*|(".*"))@[\p{L}0-9-_.]+)$
```
And this one if we add IPV6 support:
```
^(((?:[\p{L}0-9.!#$%&\'*+\/=?^_`{|}~-]+)*|(".*"))@([\p{L}0-9-_.]+|\[[0-9A-F:]+\]))$
```

**Comment by thaJeztah** [comment]
Wondering; Do you encounter these _in practice_, or is this theoretical? The spec for email addresses accept a very wide range of formats, many of which would (in my experience) actually be the result of typos by users. 

I recall regex mentioned in this article "somewhat" matching the  specs (not even everything); https://blog.codinghorror.com/regex-use-vs-regex-abuse/

**Comment by Benfarhat** [comment]
@thaJeztah  No just theoretical
In theory it say that an RFC compliant adress is composed of 2 parts:

- Local Part (preceding the last '@' symbol; ASCII hex value 40)
- Domain Part (following the last '@' symbol; ASCII hex value 40)
  - IP Address Literal (if used instead of a domain name)
    - IP v4      Address Literal
    - IP v6      Address Literal (full & compressed)
    - IP v6 v4 Address Literal (full & compressed)

When they say "the **last** "commercial at" (symbol @) it means that we can find more than only one '@' and this regex:
**'/^((?:[\p{L}0-9.!#$%&\'*+\/=?^_`{|}~-]+)*@[\p{L}0-9-._]+)$/ui'** does not validate an email with 2 '@' or even an email with ipv6 adress.

You can check by yourself that two @ are not only theoretical, SMTP server check for the double-quote and validate it (I try twice without quote to show you the error syntax message, and in the third attempt i add the double quote)

```
benfarhat@dev:~/sandbox# telnet mail.port25.com 25
Trying 173.203.187.1...
Connected to mail.port25.com.
Escape character is '^]'.
220 mx1.emailsrvr.com ESMTP - VA Code Section 18.2-152.3:1 forbids sending spam through this system
ehlo test
250-smtp24.gate.iad3a.rsapps.net says EHLO to X.X.X.X:52260
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-SIZE 75000000
250 PIPELINING
mail from:allo @email.com
501 5.5.2 MAIL FROM syntax error
mail from: allo@allo@email.com
501 5.5.2 MAIL FROM syntax error
mail from:"allo@allo"@email.com
250 2.1.0 Ok
```

**Comment by markstory** [comment]
Any chance you would want to put a pull request together for the updated pattern @Benfarhat ?

**Comment by Benfarhat** [comment]
With pleasure
