### ISSUE TITLE
Asset.timestamp not working with CDN path

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#11224]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1

### What you did
I tried to set the Asset.timestamp to force, so it include a timestamp in the CSS, JS and images and I also modified the App.imageBaseUrl, App.cssBaseUrl and App.jsBaseUrl paths to point to the CDN.

### What happened
When setting Asset.timestamp to force the timestamp is included, as expected. But when I set the CDN path, the path is correct but the timestamp is not included anymore.

### What you expected to happen
I would expect that the timestamp would still be included even if the path is on the CDN.

**Comment by markstory** [comment]
How would Cake be able to get timestamp information from a CDN?

**Comment by urionlinejudge** [comment]
@markstory it should not! But the point is that the timestamp of the file (when it was last modified), is the same both when stored in /webroot and in the CDN (the file is the same, it is only fetched from another server, based on an existing file on my server, that is how the CDN we use works). Thus having the timestamp (the local one) on the CDN path generated by Cake, will make sure the file fetched from the CDN by the browser is always fresh. Otherwise, even if I purge all the contents of the CDN, the browser may still use the previously cached file, because it has the same filename and path (and the CDN's caching settings are set to store for a 'long' time). Thus, today or I use the CDN (and manually change the file path) or I use the timestamp and fetch all the files from my server. I am not sure the explanation is clear, but please let me know if anything is confusing.

**Comment by markstory** [comment]
Ok, in your situation the paths/files are the same. That is not a promise that the helpers can assume will be true in all scenarios, which is why we don't attempt to read timestamps when a base URL is set.

**Comment by ADmad** [comment]
I don't think we can reliably check modified time for files on CDN/external servers. In this case users should implement their own caching busting mechanism. I don't think there's anything to be done here.

**Comment by urionlinejudge** [comment]
Would it be possible to have an option to allow that directly on Cake? I mean so that if the paths are the same, like in my case, Cake includes the timestamp? I agree that other CDNs might differ on this, but I would be flexible for those that do behave his way.

**Comment by urionlinejudge** [comment]
@ADmad You do not need to check an external server (that I agree would be a problem), just locally. The CDN we use fetches the files from the same path in our servers (if the resource is not in the CDN), thus the local check done for the timestamp today is enough, as long as it is included in the URL when the CND prefix is set :)

**Comment by ADmad** [comment]
As @markstory "That is not a promise that the helpers can assume will be true in all scenarios, which is why we don't attempt to read timestamps when a base URL is set."

**Comment by markstory** [comment]
> Would it be possible to have an option to allow that directly on Cake? 

Of course it is possible, I'm not convinced that more options/settings is worth the maintenance cost here.

Given that the code for this is isolated to a single method in a helper, it is equally possible for a application to override the UrlHelper and get the implementation they need :smile:

**Comment by urionlinejudge** [comment]
Ok then! :)
