### ISSUE TITLE
Using find with ->page(0) results in inadequate error message

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#11230]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: OS X local setup

### What you did
![screen shot 2017-09-24 at 9 50 47 am](https://user-images.githubusercontent.com/2320614/30783291-625a3980-a10e-11e7-9e80-9610ba274654.png)

### What happened
     Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1000' at line 1 in [/Users/jlroberts/Projects/JeffreyLRobertsCom/Dashbored/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 39]

and if I put the ->page before the ->limit I get another error message

    Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-25' at line 1 in [/Users/jlroberts/Projects/JeffreyLRobertsCom/Dashbored/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 39]

### What you expected to happen

I expected the first page of results to be returned, thinking it was a zero based index.

**Comment by saeideng** [comment]
Pages should start at 1.
https://github.com/cakephp/cakephp/blob/8dea5d8c6a5cb01e9e0e52948c8700f55a7c4d70/src/Database/Query.php#L1256

**Comment by markstory** [comment]
We can raise an error for pages < 1.

**Comment by markstory** [comment]
Pull request merged now (#11233)
