### ISSUE TITLE
RFC Explicit finderMap also for Table classes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11240]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Currently, the magic find(type) is also invoked for false positives, e.g.:
```php
    public function findByPullRequest($pr)
    {
        return $this->find()->where(['pr' => $pr]);
    }
```
as find('byPullRequest') etc, which leads to fatal errors due to the wrong typehinting.

Of course a project could try to prevent methods that start similar to findX naming scheme.
But maybe it would be cleaner to have a similar explicit finderMap for custom finders on Table level, as well.
This way there are no false positives and you can explicitly map them out the way they should work.

This also simplifies introspection and IDE helper support here (refs https://github.com/dereuromark/cakephp-ide-helper/issues/49 ).

**Comment by inoas** [comment]
I don't want to declare the finder types beyond declaring the functions as I would repeat myself and then can even forget to remove finder type declarations after removing finders.

**Comment by dereuromark** [comment]
also findOrCreate() is currently already wrongly accessible this way.

**Comment by ADmad** [comment]
Having a map for custom finders sounds reasonable as long as it's optional. Similar to how we can optionally have a map for mixin methods and events in behaviors.

**Comment by inoas** [comment]
Optional sounds okay, but is there no better solution that is DRY?

**Comment by ADmad** [comment]
The "magic" detection of custom finders it's already DRY. Only those who need to make their IDEs happy need to setup the map.

**Comment by dereuromark** [comment]
So an optional map makes sense then, yeah.

**Comment by markstory** [comment]
Is the optional map just for IDE completion? Couldn't we do something similar with doc tags?

**Comment by dereuromark** [comment]
It would also be used if you wanted a stricter mapping on project level. similar to behaviors and their mapping.

**Comment by dereuromark** [comment]
Without this, I had to do https://github.com/dereuromark/cakephp-ide-helper/pull/147
It would be nice if we could revisit a more explicit mapping instead of too much magic here in the future.
