### ISSUE TITLE
FormHelper for Radio not capturing some values

### ISSUE THREAD

**Issue by nazarioa** [cakephp/cakephp#11247]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:
2.x 8d0590c5d10b4ab4ee2891f2e355bf006873111a

* Platform and Target:
Server version: Apache/2.4.25 (Unix)
Server built:   Feb  6 2017 20:02:10
mysql  Ver 15.1 Distrib 10.2.6-MariaDB, for osx10.12 (x86_64) using readline 5.1

### What you did
I have a view that has radio buttons as part of a table.

**View**
```
<tbody>
<?php
$absentRadioOptions = array(
  'label'  => FALSE,
  'legend' => FALSE,
);
if (!empty($training['Roster'])):
  foreach ($training['Roster'] as $roster):
    $trainee_id = $roster['trainee_id'];
?>
<tr>
<td class="center complete">
  <?php echo $this->Form->radio('Transcript.' . $trainee_id . '.attendance', array(13 => NULL), $absentRadioOptions); ?>
</td>
<td class="center incomplete">
  <?php echo $this->Form->radio('Transcript.' . $trainee_id . '.attendance', array(14 => NULL), $absentRadioOptions); ?>
</td>
<td class="center absent">
  <?php echo $this->Form->radio('Transcript.' . $trainee_id . '.attendance', array(35 => NULL), $absentRadioOptions); ?>
 </td>
</tr>
<?php
endforeach;
endif;
<?tbody>

```
Several rows are generated each with a unique $trainee_id

**Controller**
```
debug($this->request);
```
select some rows with value 13, others with 14, and others with 35,

### What happened
The output of the debugger only shows  those selected as 35. Otherwise the value displayed is an empty string.
```
data => array(
		'Transcript' => array(
			(int) 8680 => array(
				'trainee_id' => '8680',
				'trainee_full_name' => 'S Abbott  ',
				'credit_type_ceu' => 'ceu',
				'attendance' => ''
			),
			(int) 8839 => array(
				'trainee_id' => '8839',
				'trainee_full_name' => 'B Samson  ',
				'attendance' => '35'
			),
			(int) 8882 => array(
				'trainee_id' => '8882',
				'trainee_full_name' => 'M Johnson  ',
				'attendance' => ''
      )
    )
)
```

Changing the order (moving the line with value 13 to the bottom for example) causes only values 13 to appear

### What you expected to happen
Data to look as follows:
```
data => array(
		'Transcript' => array(
			(int) 8680 => array(
				'trainee_id' => '8680',
				'trainee_full_name' => 'S Abbott  ',
				'credit_type_ceu' => 'ceu',
				'attendance' => '13'
			),
			(int) 8839 => array(
				'trainee_id' => '8839',
				'trainee_full_name' => 'B Samson  ',
				'attendance' => '35'
			),
			(int) 8882 => array(
				'trainee_id' => '8882',
				'trainee_full_name' => 'M Johnson  ',
				'attendance' => '14'
      )
    )
)
```

**Comment by markstory** [comment]
It looks like your 3 radio buttons will result in the same name attribute which will result in the last one being the only submitted value. If you check the $_POST variable you could confirm this. If data os missing from POST then there is no way that CakePHP can make it available. You may need to fix your input generation logic.

**Comment by nazarioa** [comment]
My understanding is that radios use "name" to be grouped.
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio

Each row should have the same name but each radio a different value.

**Comment by markstory** [comment]
Ok. You've not included the `hiddenField => false` option. You'll need to do this in order to disable the generation of hidden inputs that ensure a value set even when the radio inputs are not selected.

**Comment by nazarioa** [comment]
Apologies. just found that in the documentation by searching for `hiddenField => false`
