### ISSUE TITLE
i18n data doesn't display in PRODUCTION mode

### ISSUE THREAD

**Issue by anto2b** [cakephp/cakephp#11242]
Config : 
Cakephp 3.5.2
Php 5.6

When i turn off the debug mode on my cakephp app, all i18n data doesn't display (it's work fine in debug mode !). The i18n data are not loaded in all my entities structures.

My i18n structure table is the same as https://book.cakephp.org/3.0/en/orm/behaviors/translate.html#initializing-the-i18n-database-table

For example, I have an entity _Article_ with i18n field _title_
When I tried this : 

`<?= print_r($article->title) ?>`

This does not display any data, BUT in DEBUG MODE = ON, The title of the article appears well !

Has anyone ever had this kind of problem ?
Thanks you for your help

**Comment by markstory** [comment]
Have you made sure that your cache engines are working? You might also want to enable query logging and look for differences in the generated queries.

**Comment by anto2b** [comment]
In production mode (DEBUG = OFF) in my sql query there are not the LEFT JOIN with the i18n, but in debug mode the join exists.

**Comment by anto2b** [comment]
In my AppController in method beforeFilter() I have 
`I18n::setLocale('fr_FR');`

When i put this code in my ArticlesController directly (wich extends AppController) it work's fine ! But why ?

**Comment by anto2b** [comment]
Issue resolved => https://github.com/cakephp/cakephp/issues/11199
