### ISSUE TITLE
Radio : customize css selected class

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#11249]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.x and 3.x generally

### What you did
Displaying a form with 2 radio elements and 1 is selected (default value)

### What happened
html code is something like
```html
<label class="label selected" for="guild-edit-0">
    <input type="radio" name="guild_edit" value="0" id="guild-edit-0" checked="checked">
    <i class="fa fa-minus"></i>
</label>
```

The "selected" class was added by RadioWidget :
```php
if (!is_bool($data['label']) && isset($radio['checked']) && $radio['checked']) {
    $data['label'] = $this->_templates->addClass($data['label'], 'selected');
}
```

### What you expected to happen
I really need to customize that class by "active" instead of "selected" for compatibility with buttons bootstrap 3 javascript : https://getbootstrap.com/docs/3.3/javascript/#buttons-checkbox-radio

Bootstrap3 fix the class too BUT it's more easy for me to PR cake code :)

**Comment by inoas** [comment]
That won't be BC. Making it configurable with defaults to 'selected' would be ok, I guess.

**Comment by markstory** [comment]
The selected class could also be a 'template' value. That would make it use the same extension points that other form helper customizations use.

**Comment by andrej-griniuk** [comment]
@markstory could you clarify about "template value"? Or give any example where it's done this way.

**Comment by markstory** [comment]
Sure. FormHelper uses 'template' strings as the main way that people can customize the output of FormHelper. You can see the [list of templates](https://api.cakephp.org/3.5/class-Cake.View.Helper.FormHelper.html#$_defaultConfig). I could see the `selectedClass` being a template option. This would allow developers to make their 'theme' changes self contained.

**Comment by dereuromark** [comment]
@Erwane Do you want to make a PR here with the suggested changes?

**Comment by Erwane** [comment]
@dereuromark with https://github.com/Erwane/cakephp/commit/3e6ef467efc3383e75fe97e1832220c07b792913 yes, but not with the "template" idea :(

**Comment by Erwane** [comment]
Sorry bot. I will do it.

**Comment by dereuromark** [comment]
PR open.
