### ISSUE TITLE
Bulk Inserts

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#11252]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: OS X Built in web server

### What you did
I am inserting zone files one statement at a time, would be awesome if I could pass an array to build a multiple insert statement

### What happened
INSERT INTO MyTable VALUES ("John", 123, "Lloyds Office");
INSERT INTO MyTable VALUES ("Jane", 124, "Lloyds Office");
INSERT INTO MyTable VALUES ("Billy", 125, "London Office");
INSERT INTO MyTable VALUES ("Miranda", 126, "Bristol Office");

### What you expected to happen
INSERT INTO MyTable ( Column1, Column2 ) VALUES
( Value1, Value2 ), ( Value1, Value2 )

**Comment by ADmad** [comment]
You can already do multi inserts in single query as mentioned as stated in [manual](https://book.cakephp.org/3.0/en/orm/query-builder.html#inserting-data).
