### ISSUE TITLE
More flexible decimal validation

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#11257]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.3

---

Currently the decimal validation is a little restrictive when it comes to localization and required places.

There is no way to disable the locale aware formatting, which is problematic when the data for example stems from a `steps` enabled `number` form input, which will alwas send the data using `.` as the decimal separator, no matter which separator is being used for the display language of the browser. This can lead to the `.` being [**replaced with an empty string**](https://github.com/cakephp/cakephp/blob/3.5.3/src/Validation/Validation.php#L620) in case the locale configured for the application uses `.` as the grouping separator.

Furthermore it would be helpful if one could decide whether the configured number of places are required or not. In many situations `1` is just as valid as `1.00` (same goes for `1.1` and `1.10` and so on), and unfortunately browsers do not send a `1` as `1.00` for `steps` enabled `number` form inputs. One could use a custom regex, but if there is a way to _easily_ make this configurable, I think it would be nice to have.

**Comment by markstory** [comment]
What would the ideal api/option set look like to you?

**Comment by ndm2** [comment]
I'm not quite sure, I guess ideally the signature wouldn't change too much. Maybe this could be split into two methods, like `decimal` and `localizedDecimal` (similarily to `time` and `localizedTime`), so then in case it is deemed useful, it would be just a matter of fitting the optional places requirement in.

Maybe that could be a fourth argument, which however might not be overly nice given that passing `null` or `true` already restrict things kinda similarily. Maybe a "polymorphic" signature could work, where `$regex` accepts a boolean, which determines whether the check should be strict or relaxed. Alternatively passing the places as array might even be an option too, something along the lines of `[2, Validation::RELAXED]`, which I'm not really a fan of though.
