### ISSUE TITLE
RFC Email Shell

### ISSUE THREAD

**Issue by ajibarra** [cakephp/cakephp#11250]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Currently there is no way to test that emails are working besides actually testing the feature in your app.

I was working in an EmailShell that would allow to send test emails using specific configurations to a recipient.

It could also be useful to check if an email template is looking as expected specifying a template  and vars (not implemented yet).

What I have now:

```
$ bin/cake email send --help

Welcome to CakePHP v3.4.13 Console
---------------------------------------------------------------
Email config : default
Email recipient:
---------------------------------------------------------------
Send test email.

Usage:
cake email send [-c default|another|another_one] [-h] [-m] [-q] [-s] [-v]

Options:

--config, -c   Email Config (choices: default|another|another_one)
--help, -h     Display this help.
--message, -m  Email Content
--quiet, -q    Enable quiet output.
--subject, -s  Email Subject
--verbose, -v  Enable verbose output.
```

Test sending:

```
$ bin/cake email send test@email.com

Welcome to CakePHP v3.4.13 Console
---------------------------------------------------------------
Email config : default
Email recipient: test@email.com
---------------------------------------------------------------
Email message sent successfully

Headers
From: you@localhost
To: test@email.com
Date: Thu, 28 Sep 2017 05:42:40 +0000
Message-ID: <98f6824403a54eed9e2d90fdd708e8f1@ranita.local>
Subject: Test email
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Message
This is a test email
```

I think it would be good to include it as a core feature but it would be a plugin as well of course. I would like to know your thoughts.

**Comment by dereuromark** [comment]
I am OK with testing emails (validity, including deep MX etc), and often times build a backend for it to do that :)
It sure sounds like a useful small shell.

What is more dangerous is to provide a one liner to send out actual real emails via CLI.
This can also be either accidentally sending stuff, or abused.

PS: This could just be an opt-in plugin, not sure if this must be a core feature per se.

**Comment by inoas** [comment]
> This can also be either accidentally sending stuff, or abused.

You mean like already possible on some *nix systems: `$ echo "body" | mail -s "subject" mail@example.com`?

**Comment by steinkel** [comment]
Accidentaly: yes if you type the required target email incorrectly
Abused: yes, but also I could use bin/cake console for the same purpose...

**Comment by dereuromark** [comment]
True, so mainly accidental sending is an issue maybe then. We should probably keep it scoped to validation only :)

**Comment by markstory** [comment]
> Currently there is no way to test that emails are working besides actually testing the feature in your app.

What about test cases?

**Comment by dereuromark** [comment]
Well, I think he means in production :)
But either way I would still go then with an admin backend that provides a small validation form here.
For me this still sounds more like a project or plugin use case than core relevant.

**Comment by steinkel** [comment]
The idea was to use in production and debug SMTP transport typical issues, like rate limit exceeded or invalid credentials...

**Comment by markstory** [comment]
Should the SMTP transport have better logging in place? That kind of issue sounds like something that could be handled through logging.

**Comment by ajibarra** [comment]
The idea of this tools is to know in advance of any issues you could face sending emails. Logs work fine when you are already in troubles. 

Anyway we will be preparing a plugin with the shell and we could consider adding it to core plugins later.
