### ISSUE TITLE
loadModel unespected override

### ISSUE THREAD

**Issue by eniacom** [cakephp/cakephp#11268]
This is a (multiple allowed):

* [x] bug ??

* CakePHP Version: 3.4.3
* Platform and Target:
** webserver apache2
** database mysql

I would like to use a plugin's Model inside /src/AppController.php beforeFilter function.
Then I would like to call an action out of plugin and use the model of out of plugin with custom find functions.
Howevere I receive unespected error Unknown finder method "slug".

My use case:

in /src/AppController.php
```php
public function beforeFilter(Event $event) {
  $this->loadModel('MyPlugin.Articles');
  // some manipulation about Articles here
}
```

in /src/ArticlesController.php
```php
public function view() {
         // some manipulation
         $query = $this->Articles->find('slug', . . . )
}
```

in /src/Model/Table/Articles.php but not in /src/plugins/MyPlugin/Model/Table/Articles.php
```php
public function findSlug(Query $query, array $options)
{
        return $query->where(['Articles.slug' => $options['slug']]);
}
```

I expect that action /articles/view/slug.html should find an article through /src/Model/Table/Articles.php and not  /src/plugins/MyPlugin/Model/Table/Articles.php where isn't  findSlug function

I have not found a similar issue

**Comment by dereuromark** [comment]
I think that is because the registry then has already the other model aliases. It can and will only store one per alias and cache it internally (so to speak).
You should never use the same alias twice for different classes. You should alias already beforehand, to avoid this issue. This is not a core bug but a dev error IMO.

**Comment by markstory** [comment]
Do you load the application's Articles Model in the ArticlesController? If not you'll get the plugin model overwriting the application one causing the issue you're seeing.
