### ISSUE TITLE
Entity::set improve

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#11261]
* [x] bug
* [x] enhancement

* CakePHP Version: 3.5.3

### What you did

```php
$Entity = $Table->get($id);
$Entity->set('property', 'new_value');
$Entity->set('property', 'original_value');
```

### What happened
property set to original value but it is marked as dirty
`$Entity->isDirty('property')` returns true

### What you expected to happen

```php
$Entity->isDirty('property') returns false
$Entity->_original['property'] is unset
```

Also will be great to have Entity::set option to set value without making is dirty and 
unset $Entity->_original['property'] when $Entity->setDirty('property', false) was called

**Comment by saeideng** [comment]
we no have any method named `isDuty()` in core

**Comment by andruhapx** [comment]
That was typos, sorry. Updated issue: changed isDuty to isDirty

**Comment by inoas** [comment]
`->set()` should IMHO not be changed to do more magic; also this would not be BC.
However a `->setOrRestore()` could do that (or `setOrOriginal()` or setOrRestoreToOriginal()`.

**Comment by markstory** [comment]
Original value checking could get complicated when associated entity values or value object properties are involved.

**Comment by andruhapx** [comment]
I used entity wrap, working correct for me:

```
namespace App\Model\Entity;

class Entity extends \Cake\ORM\Entity {

	public function set($property, $value = null, array $options = []) {
		$originals = $this->getOriginalValues();
		$result = parent::set($property, $value, $options);

		if (!is_array($property))
			$property = [$property=>$value];

		foreach ($property as $p => $value) {
			$is_duty = $value !== @$originals[$p];
			$this->setDirty($p, $is_duty);
			if (!$is_duty)
				unset($this->_original[$p]);
		}

		return $result;
	}
}
```

**Comment by dereuromark** [comment]
setOrRestore() could indeed provide this functionality.
Modifying the existing set() method itself is sure not advised at this point.

**Comment by andruhapx** [comment]
Now I compare original and passed values after converting with Type::toDatabase().
If values are the same, property is set as not duty.
Works perfectly on large project and minimizes data sent to database. Also allows not update `modified` field if data is the same.

`
class Entity extends \Cake\ORM\Entity {

	public function set($property, $value = null, array $options = []) {
		$originals = $this->getOriginalValues();
		$result = parent::set($property, $value, $options);

		if (!is_array($property))
			$property = [$property=>$value];

		$Table = TableRegistry::get($this->getSource());
		$Driver = $Table->getConnection()->getDriver();
		foreach ($property as $p => $value) {
			if (!array_key_exists($p, $originals))
				continue;

			$value = $this->get($p);
			$original = $originals[$p];

			$typeName = $Table->getSchema()->getColumnType($p);
			if ($typeName) {
				$Type = Type::build($typeName);
				$value = $Type->toDatabase($value, $Driver);
				$original = $Type->toDatabase($original, $Driver);
			}

			$is_duty = $value !== $original;
			$this->setDirty($p, $is_duty);
		}

		return $result;
	}
}
`

**Comment by dereuromark** [comment]
I am for closing this as this can be done using a custom trait and setOrRestore() as wrapper for this kind of custom functionality.
