### ISSUE TITLE
$this->response->withBodyString doesn't work as expected 

### ISSUE THREAD

**Issue by suhaboncukcu** [cakephp/cakephp#11266]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

### What you did
Upgrade legacy $this->response->body methods with $this->response->withBodyString() methods. 

### What happened
I got empty response. 

### What you expected to happen

When I check the PRs and issues, I've seen @cleptric 's [PR](https://github.com/cakephp/cakephp/pull/10296)

This works as expected under controller:
```
public function test() {
        $this->autoRender = false;
        $this->response->type('json');
        $this->response->getBody()->write(json_encode(['TEST' => 'TEST']));   
 }
```

While this one produces an empty respond:
```
public function test() {
        $this->autoRender = false;
        $this->response->type('json');
        $this->response->withStringBody(son_encode(['TEST' => 'TEST']));
}
```

**Comment by dereuromark** [comment]
The with concept requires immutable working. That means you must use the return value to continue, otherwise you are reusing the former object state.
That is documented under the PSR and probably also visible in tests and in docs:

    $this->response = $this->response->withStringBody(son_encode(['TEST' => 'TEST']));

etc.
