### ISSUE TITLE
RFC : EntityRouting

### ISSUE THREAD

**Issue by Kareylo** [cakephp/cakephp#11277]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

As I tried latest releases of Ruby on Rails, I found a really usefull feature with routing : EntityRouting. The main goal is to have the ability to name routes - as we can do with `'_name' => 'myrouteName'` in Route options and use an entity to put on the back side all the parameters we need, and, later, we can change what we need in the route without having the need to change all routes in our views.

For example, we've got this, right now :

```php
// Routing
$routes->connect('/view/:id', ['controller' => 'Posts', 'action' => 'view'], ['pass' => ['id'], 'id' => '\d+']);

// In View
$this->Html->link('View Post', ['controller' => 'Posts', 'action' => 'view', 'id' => $post->id]);
```

If in later days we change the route like this :

```php
$routes->connect('/view/:slug-:id', ['controller' => 'Posts', 'action' => 'view'], ['pass' => ['slug', 'id'], 'slug' => '[a-z\-]+', 'id' => '\d+']);
```
We'll need to change all the routes in the app

### How can we enhance this ?

The main goal is to forgot what we need to pass to the Router::url with the entity directly with something like the following example without having to really change the route side, just the need to give a name to this route :
```php
// Routing
$routes->connect('/view/:slug-:id', ['controller' => 'Posts', 'action' => 'view'], ['pass' => ['slug', 'id'], 'slug' => '[a-z\-]+', 'id' => '\d+', '_name' => 'postsView']);

// In View
$this->Html->link('View Post', ['_name' => 'postsView', '_entity' => $post]);
```

So, I searched for someone who have writing something like that and found this [Blog Post](http://ad7six.com/blog/2014/09/16/cakephp-entity-routing/) 

I know it's not really a needed feature, but still a good one.

Have you got any idea on this feature ?
Maybe could be improved with #10643 ?

**Comment by saeideng** [comment]
>[Blog Post](http://ad7six.com/blog/2014/09/16/cakephp-entity-routing/)

adding `'routeClass' => 'EntityRoute'` is good idea

**Comment by markstory** [comment]
Seems like a neat idea with a pretty simple solution from @AD7six  blog.

**Comment by Kareylo** [comment]
I think just giving the entity should be really nice too, but it's more work on routing.

```php
$this->Html->link('View Post', ['_name' => 'postsView', $post]);
```

Already tried to do, it's possible, but really bad code for the match method
```php
    public function match(array $url, array $context = [])
    {
        if (!isset($url['_entity'])) {
            $keys = array_keys($url);
            foreach ($keys as $key) {
                if ($url[$key] instanceof Entity) {
                    $url['_entity'] = $url[$key];
                    unset($url[$key]);
                    break;
                }
            }
        }

        if (isset($url['_entity'])) {
            preg_match_all('@:(\w+)@', $this->template, $matches);
            foreach ($matches[1] as $field) {
                $url[$field] = $url['_entity'][$field];
            }
        }

        return parent::match($url, $context);
    }
```

**Comment by burzum** [comment]
@Kareylo I don't like the foreach() to check if only an entity was passed. Plenty of iteration just to detect that.

**Comment by Kareylo** [comment]
@burzum I totally agree, need to do it with a array_search()

**Comment by dereuromark** [comment]
PR open, we can close then?
