### ISSUE TITLE
Object of class App\View\AppView could not be converted to string

### ISSUE THREAD

**Issue by patrickquijano** [cakephp/cakephp#11276]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3.
* Platform and Target: Windows 10, PHP 5.6.28, MariaDB 10.1.19

### What you did
Added this line in my head tag in the default layout template (Layout/default.ctp):
`<title><?= $this->fetch('title'); ?></title>`

Added this line in my home template (Pages/home.ctp):
`<?= $this->assign('title', __('The quick brown fox.')); ?>`

### What happened
It's displaying a warning erro:
`Warning (4096): Object of class App\View\AppView could not be converted to string [APP/Template\Pages\home.ctp, line 1]`

### What you expected to happen
No warning/error should show up.

**Comment by dereuromark** [comment]
You should not be echoing void or chaning methods. In this case

    <?php $this->...() ?>

Would be correct, as <?= ?> auto-echos.

**Comment by patrickquijano** [comment]
My bad. I've been writing and reading codes whole day. Thanks @dereuromark!
