### ISSUE TITLE
Multi Tree Deletes Nodes outside the Scope

### ISSUE THREAD

**Issue by jonmc1** [cakephp/cakephp#11289]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3

### What you did
In a Multi Tree, multiple tree structures in the same db table, delete a tree node that is not a leaf

In a Table:
$this->addBehavior('Tree');
...
$this->behaviors()->Tree->config('scope', ['field_name' => $fieldValue]);
$node = $this->get($id);
$this->delete($node);

### What happened
Nodes were deleted, by 'lft' field, for all trees in the db table

### What you expected to happen
Only delete nodes from the tree that 'scope' is set to

**Comment by markstory** [comment]
Closing as a pull request is open now.
