### ISSUE TITLE
SqlserverSchema return column length as a string

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#11296]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3.
* Platform and Target: Windows, MS SQL Server 2012.

### What you did
I've created a fixture with a string field having a limit of 50 characters. 
```php
// extra columns were truncated
class BakeArticlesFixture extends TestFixture
{
    public $fields = [
        'title' => ['type' => 'string', 'length' => 50, 'null' => false],
    ];
}
```

### What happened
During unit-testing, the table's schema object reported, that the "title" field has a length of N characters as a string.
```php
$schema = $table->getSchema();
```

### What you expected to happen
The length of the field to be an integer.

**Comment by markstory** [comment]
Pull request open now.
