### ISSUE TITLE
MissingTemplateException on ajax-only action

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#11307]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.3
* Platform and Target: Linux, PHP 7.0.19-1 (Debian)

### What you did
```php
public function myActionAjax()
    {
        if (!$this->request->is('ajax')) {
            throw new NotFoundException();
        }
        /* implementation here */
    }
```

Testing from multiple browsers, did not allow me to simulate the conditions, in which it fails

jQuery XHR GET request in testing looks like this (Chrome request headers):
```
Request URL: --redacted--
Request Method:GET
Status Code:200 OK
Remote Address: --redacted--
Referrer Policy:no-referrer-when-downgrade


Response Headers
view source
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=UTF-8
Date:Mon, 09 Oct 2017 09:31:23 GMT
Server:nginx/1.13.3
Strict-Transport-Security:max-age=63072000; includeSubDomains; preload
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1; mode=block


Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, br
Accept-Language:en,cs;q=0.9,sk;q=0.8,fr;q=0.7
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:--redacted--
Pragma:no-cache
Referer:--redacted--
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3230.0 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
```

### What happened

However in some cases obviously CakePHP fails to recognize XHR GET request and classify it as 'ajax' type, thus overcoming the initial condition (in testing accessing url directly triggers 404 / NotFoundException, which is correct behavior)

Logging issue like this:
```
2017-10-09 09:25:42 Error: [Cake\View\Exception\MissingTemplateException] Template file "Pages/my_action_ajax.ctp" is missing.
Request URL: --redacted--
Referer URL: --redacted--
```
`src/Template/Pages/json/my_action_ajax.ctp` is available and rendering is working correctly from all testing browsers

### Additional info
jQuery plugin that accesses the data over ajax/xhr is DataTables (https://datatables.net/)

---

Is it possible, that `is('ajax')` classifier is not enough?

**Comment by ADmad** [comment]
Wouldn't a non ajax request without json extension/header cause the error you have show? So besides is('ajax')  you should also check for is('json').

**Comment by smarek** [comment]
@ADmad I could definitely do that, however the action should always response with json. Is it possible to render /convert to json XHR response in all 'ajax' cases? Thank you!

**Comment by ADmad** [comment]
You can call `RequestHandler::renderAs()` from your action to switch template paths and set response type for json response.

**Comment by smarek** [comment]
@ADmad thank you, i've hit a bug probably?
setting `renderAs('json')` searches the template file in 

`Pages/json/json/my_action_ajax.ctp` or `Pages/ajax/json/my_action_ajax.ctp` which is correctly not-found

**Comment by ADmad** [comment]
Use `.json` extension in URL or set `Accepts` header to `application/json` in request and the request handler will automatically set proper path and you won't has to manually call `renderAs('json')`.

**Comment by smarek** [comment]
@ADmad i cannot enforce what the requests will look like, that's why I wanted to enforce the way it renders, to always produce JSON output (my json producing views are placed in Pages/json/my_action_ajax.ctp which should be correct from documentation)

That however does not explain, why CakePHP searches for view in `json/json/my_action_ajax.ctp` path (ie. the json/json or ajax/json folder names are duplicated)

**Comment by ADmad** [comment]
Since you are getting duplicate `json/json` I think it's already being detected as json request and then calling `renderAs()` explicitly is setting the subdir folder template twice.

Please open a new issue with details of your request and the problem as we can see how this duplication can be avoided.
