### ISSUE TITLE
Problem order, in pagination for aliasField() add in controller and where join table, count.

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#11306]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.16
* Platform and Target: WAMP PHP 7.1

Problem order, in pagination for aliasField() add in controller, for paginate and where join table count field.
Order all the results of the page, except the one in the row with the name 'count_users' which is an alias

### What you did
**HTML Example view ctp**

`<?= $this->Paginator->sort('count_users',_('N° Users')); ?>`

**Controller Example**

```
    $this->Licensees->schema()
        ->addColumn('count_users', [
            'type' => 'integer',
        ]);
    $this->Licensees->aliasField('count_users');

    $where = [
        'recursive'=>-1,
        'fields' => [
           'Licensees.id',
           'Licensees.name',
           'Licensees.created',
           'Licensees.modified',
           // 'Licensees.count_users' => 'count(LicenseesUsers.licensees_id)',
           // 'count_users' => 'count(LicenseesUsers.licensees_id)',
           'Licensees__count_users' => 'count(LicenseesUsers.licensees_id)',
           
         ],
        'sortWhitelist' => ['name','count_users','created','modified'],
        'join' => [
            'LicenseesUsers' => [
                'table' => 'licensees_users',
                'type' => 'LEFT',
                'conditions' => [
                    'LicenseesUsers.licensees_id = Licensees.id'
                ],
            ],
        ],
        'group' => 'Licensees.id'
    ];

     // Set pagination
    $this->paginate = $where;

    // Get data
    $licensees = $this->paginate($this->Licensees);
```

### What happened
Order all the results of the page, except the one in the row with the name **'count_users'** which is an alias

### What you expected to happen
I hope it is ordered by all the columns, so I can also order by **'count_users'**

**Comment by ADmad** [comment]
You are misunderstanding what `Table::aliasField()` does. It just returns the provided string prefixed with model alias. It does not modify the query or returned results in any way.

Please use one of the support channels to get help for achieving what you need.

**Comment by EOM** [comment]
OK Admad, not is Bug,

My problem in code, post solution:
[https://stackoverflow.com/questions/46638595/sort-pagination-by-row-alias-count-for-example-in-cakephp-3-x-data-by-linking/46654653#46654653](https://stackoverflow.com/questions/46638595/sort-pagination-by-row-alias-count-for-example-in-cakephp-3-x-data-by-linking/46654653#46654653)
