### ISSUE TITLE
columnType JSON > json_encode options

### ISSUE THREAD

**Issue by andruhapx** [cakephp/cakephp#11311]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3

JsonType should have settings to set json_encode options.
In my case I want to use JSON_UNESCAPED_UNICODE, but only one way to do this - override class.

And also maybe it will be good idea to allow seting $assoc parameter of json_decode

**Comment by dereuromark** [comment]
Are you able to provide a PR here for either 3.5 or 3.6?

**Comment by andruhapx** [comment]
No, because TableSchema::setColumnType has no config parameter
and TypeInterface didnt use InstanceConfigTrait. 
I can work only with SVN, but not GIT.

Creating PR for this will be too big for me ;)

**Comment by robertpustulka** [comment]
@andruhapx

> Creating PR for this will be too big for me ;)

You never know until you try it :)

**Comment by saeideng** [comment]
I'll Open a PR for `json_encode:$options`  unless someone open before me
why we should having bellow options? is necessary ?

```php
 //json_encode:
$depth`
//json_decode 
$assoc 
 $depth 
$options
```

**Comment by markstory** [comment]
>  In my case I want to use JSON_UNESCAPED_UNICODE, but only one way to do this - override class.

What is the problem with that?

**Comment by andruhapx** [comment]
No problem, but type settings, like its already done for components, will be much close to cakephp styles. For any core and custom types

**Comment by davidyell** [comment]
Could this be solved by a custom data type class?

**Comment by markstory** [comment]
> Could this be solved by a custom data type class?

Of course it could.

**Comment by saeideng** [comment]
@markstory 
let me know if needs to implement new method for `json_encode:$options` :)
and what is suggested method name for this
