### ISSUE TITLE
renderAs() duplicates folder name ajax/json

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#11316]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.3
* Platform and Target: Linux, PHP 7.0.19-1 (Debian)

### What you did
on ajax-only action i'm calling 
```php
if (!$this->request->is('ajax')) {
    throw new NotFoundException();
}
$this->RequestHandler->renderAs($this, 'json');
```

### What happened
Two types of errors can be seen in logs/error.log
```
Error: [Cake\View\Exception\MissingTemplateException] Template file "Pages/json/json/my_ajax_action.ctp" is missing 
Error: [Cake\View\Exception\MissingTemplateException] Template file "Pages/ajax/json/my_ajax_action.ctp" is missing
```
### What you expected to happen
Expected CakePHP to correctly address existing template in path `Pages/json/my_ajax_action.ctp`

Duplication occurs when request is already recognized as ajax/json one by framework, and calling `renderAs()` adds another directory level to already established template path

Reference: #11307

**Comment by ADmad** [comment]
What if you wrap the renderAs() call inside `if (! $this->request->is('json'))  {...} ` check? That should prevent it from being unnecessarily called twice.

**Comment by smarek** [comment]
@ADmad thank you, this as a workaround works, but it is an ugly workaround in my opinion

**Comment by ADmad** [comment]
I don't think it's ugly. Even if the duplicate path fragment wasn't an issue you are avoiding unnecessary non trivial method call this way.

**Comment by smarek** [comment]
That should be framework checking if the value is not already set to requested value, isn't it? If not everywhere, then where framework knows there's non-trivial (lenghty / complicated / resource-intensive) operation ahead, it should try and avoid it if possible

**Comment by ADmad** [comment]
You are welcome to submit a patch to make the method bail out early if settings for requested type are already done.

**Comment by markstory** [comment]
If you did `renderAs($this, 'xml')` is the resulting path `json/xml`?

**Comment by markstory** [comment]
Pull request open now.
