### ISSUE TITLE
[2.x] PaginatorHelper class current link

### ISSUE THREAD

**Issue by Vadimushka** [cakephp/cakephp#11312]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.8

I wanted to designate a class for the current link, via PaginatorHelper, but it does not put the class for the link I need. Here's the code to call the method I need:
```php
$this->Paginator->numbers([
   'modulus' => 4,
   'separator' => ' ',
   'class' => 'page',
   'tag' => false,
   'currentTag' => 'span',
   'currentClass' => 'active',
]);
```

I left the output that he would return such a conclusion to the current page number:
`<span class="active">2</span>`

But it returned the opposite without a class:
`<span>2</span>`

Just in case, I found an error in the code, but I do not know how to properly edit:
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/View/Helper/PaginatorHelper.php
Line 799 - 806

I think there should be something like this on line 803:
```php
$out .= $this->Html->tag($tag, $this->Html->tag($currentTag, $params['page'], array('class' => $currentClass)));
```
And line 805:
```php
$out .= $this->Html->tag($tag, $params['page'], array('class' => $class));
```

**Comment by markstory** [comment]
`PaginatorHelper` always applies classnames to the 'wrapping tags' which you've disabled. Making the proposed changes breaks existing tests and will break applications as the classnames will have moved.

**Comment by Vadimushka** [comment]
clearly, I'll try to do it differently, I'll include the wrapper tag and check how everything works for it

by Instatant Translate

**Comment by markstory** [comment]
Ok.
