### ISSUE TITLE
bin/cake stop working after composer update

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11326]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3
* Platform and Target: Non-related

### What you did
```sh
bin/cake
```

### What happened
Got an exception.
```
Exception: Cannot use 'Bake\Shell\CommonOptionsTrait' for command 'common_options_trait' it is not a subclass of Cake\Console\Shell. in [/var/www/vhosts/cakephp3.centos.dev/vendor/cakephp/cakephp/src/Console/CommandCollection.php, line 65]
```

### What you expected to happen
Works.

### Why this happened

As of cakephp/bake#368, CommandScanner finds CommonOptionsTrait in the Shell directory of bake plugin, and CommandCollection throws an exception as it is not a shell. Though the commit triggered this issue, the root problem would be the implementation of CommandScanner::scanDir() or CommandCollection::add().

**Comment by markstory** [comment]
I'm tempted to patch up bake to get a short term fix out, and then update CommandScanner to only include files ending in 'Shell'

**Comment by chinpei215** [comment]
Thank you.

**Comment by ADmad** [comment]
Closing as related PR is open.
