### ISSUE TITLE
3.x/4.x Change MySQL encoding to UTF-8 Full Unicode (utf8mb4)

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#11324]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: 3.4

### What you did

Converting my app from mariadb-utf8 to mariadb-utf8mb4

### What happened

Either I got no query results at all (when I forgot to push real utf8), or this:
```
Illegal mix of collations (utf8mb4_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
```

### What you expected to happen

This to work out of the box.

- app.php datasource encoding should probably change to utf8mb4
- MySql Driver baseConfig encoding should probably change to utf8mb4
- utf8 3 byte access will/should still work like before - **in addition** true utf8 (4byte) support will work without data being truncated before hitting the table collation already (without changing the table and/or column from utf8 to utf8mb4 - 4 byte code points will still fail)

**Comment by markstory** [comment]
I am guessing you didn't set the encoding in your connection configuration?

**Comment by inoas** [comment]
Well I did after I discovered an issue in sequel pro (does not auto detect utf8mb4).

I support setting it as default in cakephp/app and cakephp/cakephp; for posrgres it would map to utf8 as thats 4byte by defUlt as far as I know...

**Comment by inoas** [comment]
Refs:
- https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
- https://mathiasbynens.be/notes/mysql-utf8mb4
- http://www.phptherightway.com/#utf-8-at-the-database-level

**Comment by inoas** [comment]
Closing as PRs are open.
