### ISSUE TITLE
ORM query params are overwritten

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#11337]
This is a (multiple allowed):

* [x] bug

* CakePHP Version:
3.5.4
* Platform and Target: 
Apache/2.4.25 (Ubuntu), 
PHP Version 7.0.22-0ubuntu0.17.04.1
MySQL and Sqlite

### What you did
As I was not able to create a test case for this I have an example app to help you reproduce the bug. My original code and problem is much more complex, and that is how much I was able to narrow it down.

Controller:
https://github.com/rrd108/cakephp-orm-query-param-overwrite-bug/blob/origin/src/Controller/ArticlesController.php

Model:
https://github.com/rrd108/cakephp-orm-query-param-overwrite-bug/blob/origin/src/Model/Table/ArticlesTable.php

### What happened
In the output `$okParams` and `$overwrittenParams` are different for the key `:c0`.
In the `$overwrittenParams` array the second condition overwrites the first one.

### What you expected to happen
`$okParams` and `$overwrittenParams` arrays supposed to have same keys and values.
The only difference in the two `findBugDetailed` calls is that `$options['bug']` is `undefined` in the second case and this creates a notice.

ArticlesTable line 29 modifies the generated SQL but it does not supposed to do anything (excepting creating the notice) and MUST NOT change the generated SQL.

The problem can be avoided by using `if (!empty($options['bug'])) {}` but as the original version creates only a notice and the overwrite happens elsewhere it was really difficult to find a workaround and this solution is not a fix.

**Comment by markstory** [comment]
Your model's findAbstract method never uses the options parameter is that an accident?

**Comment by rrd108** [comment]
In my real code that function users the $option parameter.  I just removed all parts of the code from the example app, what was not  neccesary to reproduce the faulty behaviour.
The same is true for the if. There is some logic there in my actual code.

**Comment by rrd108** [comment]
Does it the same? https://github.com/cakephp/cakephp/issues/9711

**Comment by markstory** [comment]
I'll see if I can reproduce the issue you're having based on the model/controller code you've provided so far.

**Comment by markstory** [comment]
Closing as the query is mutated by the error output. Query objects get partially evaluated when their SQL is rendered. Part of the default notice error output is to render the 'context' around the error which contains the local variables.

If you change your error reporting level to `E_ALL ^ E_NOTICE` you'll notice that the query parameters are consistent across both queries.

Unfortunately I don't think there is a way for us to solve this without reducing/breaking the functionality of `Query::__debugInfo()`.
