### ISSUE TITLE
3.5.* - Controller::paginate() doesn't pass all options correctly

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#11330]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

```bash
sdustinh@sdustinh:~/github/cakephp/app$ php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
sdustinh@sdustinh:~/github/cakephp/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
sdustinh@sdustinh:~/github/cakephp/app$ composer show cakephp/*
cakephp/bake                1.4.2  Bake plugin for CakePHP 3
cakephp/cakephp             3.5.2  The CakePHP framework
cakephp/cakephp-codesniffer 3.0.1  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.2  A simple API extension for DateTime.
cakephp/debug_kit           3.11.1 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.7.1  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.0.0  A composer installer for CakePHP 3.0+ plugins.
```

### What you did
Created a controller with default pagination options in the `$paginate` property and used `$this->paginate($query)`.

### What happened
When calling `$this->paginate($query)` the pagination options were only partially being used in the `Cake\Datasource\Paginator` object.

### What you expected to happen

Here is a copy/paste of my controller almost exactly as it is:

```php
/**
 * Products Controller
 *
 * @property \Facilities\Model\Table\FacilitiesTable $Facilities
 * @property \Products\Model\Table\ProductsTable $Products
 * @property \Products\Model\Table\ProductTypeGroupsTable $ProductTypeGroups
 * @property \Products\Model\Table\ProductTypesTable $ProductTypes
 * @property \Products\Model\Table\ProductManufacturersTable $ProductManufacturers
 */
class ProductsController extends AppController
{
    /**
     * Default Model Class
     *
     * @var string
     */
    public $modelClass = 'Products.Products';
    /**
     * Default Pagination Options
     *
     * @var array
     */
    public $paginate = [
        'Products' => [
            'contain' => [
                'ProductTypes',
                'ProductManufacturers',
                'Assets.AssetLocations.Facilities',
            ],
            'limit' => 50,
            'maxLimit' => 100,
            'sortWhitelist' => [
                'Facilities.code',
                'Products.id',
                'ProductCapacities.bytes',
                'ProductManufacturers.name',
                'ProductTypes.name',
                'total_assets',
            ],
        ],
    ];
    /**
     * Product Availability Report
     *
     * This report will show the total number of assets by product. You can apply
     * filters to it for more specific numbers.
     *
     * @return void
     */
    public function availability()
    {
        $getFilter = function ($filter) {
            $query = $this->request->getQueryParams();

            if (isset($query[$filter]) === false) {
                return null;
            }

            return array_filter((array)$query[$filter]) ?: null;
        };

        $products = $this->Products->find();
        $products
            ->innerJoinWith('Assets', function ($query) {
                return $query->find('tracked');
            })
            ->innerJoinWith('Assets.AssetStatuses', function ($query) use ($getFilter) {
                $assetStatuses = $getFilter('assetStatus');

                if ($assetStatuses !== null) {
                    $query->where(['AssetStatuses.id IN' => (array)$assetStatuses]);
                }

                return $query;
            })
            ->innerJoinWith('Assets.AssetLocations.Facilities', function ($query) use ($getFilter) {
                $facilities = $getFilter('facility');

                if ($facilities !== null) {
                    $query->where([
                        'OR' => [
                            ['Facilities.id IN' => (array)$facilities],
                            ['Facilities.code IN' => (array)$facilities],
                        ],
                    ]);
                }

                return $query;
            })
            ->select([
                'facility_code' => 'Facilities.code',
                'total_assets' => $products->func()->count('Assets.id'),
            ])
            ->contain([
                'ProductCapacities',
                'ProductManufacturers' => function ($query) use ($getFilter) {
                    $manufacturers = $getFilter('manufacturer');

                    if ($manufacturers !== null) {
                        $query->where(['ProductManufacturers.id IN' => (array)$manufacturers]);
                    }

                    return $query;
                },
                'ProductTypes' => function ($query) use ($getFilter) {
                    $productTypes = $getFilter('productType');

                    if ($productTypes !== null) {
                        $query->where(['ProductTypes.id IN' => (array)$productTypes]);
                    }

                    return $query;
                },
                'ProductTypes.ProductTypeGroups' => function ($query) use ($getFilter) {
                    $productTypeGroups = $getFilter('productTypeGroup');

                    if ($productTypeGroups !== null) {
                        $query->where(['ProductTypeGroups.id IN' => (array)$productTypeGroups]);
                    }

                    return $query;
                },
            ])
            ->group(['Products.id', 'ProductTypes.id', 'Facilities.id'])
            ->enableAutoFields(true);
        $this->set('products', $this->Paginator->paginate($products, $this->paginate));

        // Grab filtering data
        $assetStatuses = $this->AssetStatuses->find('list')->order(['AssetStatuses.name' => 'ASC']);
        $facilities = $this->Facilities->find('list', ['valueField' => 'codename']);
        $manufacturers = $this->ProductManufacturers->find('list')->order(['ProductManufacturers.name' => 'ASC']);
        $productTypeGroups = $this->ProductTypeGroups->find()
            ->contain(['ProductCategories'])
            ->find('list', ['groupField' => 'category.name'])
            ->order([
                'ProductCategories.name' => 'ASC',
                'ProductTypeGroups.name' => 'ASC',
            ]);
        $productTypes = $this->ProductTypes->find()
            ->contain(['ProductTypeGroups'])
            ->find('list', ['groupField' => 'group.name'])
            ->order([
                'ProductTypeGroups.name' => 'ASC',
                'ProductTypes.name' => 'ASC',
            ]);
        $this->set(compact(
            'assetStatuses',
            'facilities',
            'manufacturers',
            'productTypeGroups',
            'productTypes'
        ));
    }
    /**
     * Initialize
     *
     * @return void
     */
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('Paginator');

        if ($this->request->getParam('action') === 'availability') {
            $this->loadModel('Assets.AssetStatuses');
            $this->loadModel('Facilities.Facilities');
            $this->loadModel('Products.ProductManufacturers');
            $this->loadModel('Products.ProductTypeGroups');
            $this->loadModel('Products.ProductTypes');
            $this->loadModel('Products.Products');
        }
    }
}
```

This has been a constant problem I've had when using pagination in the framework but I was finally able to make it work so I wanted to open a bug issue with you guys to confirm it's a framework problem instead of something I've messed up in my application code.

As you can see in the code above, I make a call to `$this->Paginator->paginate($products, $this->paginate)`. This was the only way I could get it to pagination correctly. When I didn't call the component directly (e.g. `$this->paginate($products)`) and dumped the paginator object I noticed that the `limit` field was set correctly but none of the other properties were even being set. I was able to confirm this problem in the view with `$this->Paginator->sort()` not generating the correct `direction`.

I did a step by step on `Cake\Datasource\Paginator::paginate()` and the first spot that failed was the actual [call](https://github.com/cakephp/cakephp/blob/master/src/Datasource/Paginator.php#L172) to [validateSort()](https://github.com/cakephp/cakephp/blob/master/src/Datasource/Paginator.php#L341). It was returning an empty array every time. Naturally, this led me to check out `Cake\Controller\Controller::paginate()` as the problem since it was the only place I was able to reproduce the issue. Looking over how that [method](https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L695) works, the only thing I could see that might cause a problem would be when the default options are merged with the incoming [here](https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L716). I don't know *why* that would be a problem, but the fact that `limit` made its way to the paginator object and `sortWhitelist` did not would make me think that a `array_merge()` call would be the fix.

Anyway, if you guys can't reproduce it and it works for you then just close this issue. For my application it seems I'll just have to use the component directly because I can't find another way around it. If you need me to do any more confirmation tests I'd be happy to do it.

Thanks for your hard work!

**Comment by markstory** [comment]
Does a similar issue happen if you pass a Table instance or model name to Controller::paginate()?

**Comment by sdustinh** [comment]
Sorry for the delay. It doesn't seem to matter if I pass a string, the instance, or the query. The only thing that consistently gets set is `limit`, `contain`, or `fields`. When I dump the paginator object I don't see the settings in it unless I call the component directly. Then it works every time. I'm really at a loss for what could be causing it. The only thing I could see as a potential would be that `$settings += $this->paginate;` maybe reading from the initial state?

**Comment by markstory** [comment]
I'll see if I can reproduce this problem.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue in a small app. My controller's `paginate` property and index method looked like:

```php
    public $paginate = [
        'Bookmarks' => [
            'limit' => 3,
            'maxLimit' => 10,
            'sortWhitelist' => ['title', 'Bookmarks.title']
        ]
    ];

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->set('bookmarks', $this->paginate($this->Bookmarks));
        $this->set('_serialize', ['bookmarks']);
    }
```

The `maxLimit` and `sortWhitelist` were respected and I was not able to set a limit above 10, nor sort on a non-title field. Have I missed something?

**Comment by ideagroup-dev** [comment]
considering the following instruction :
$this->set('bookmarks', $this->paginate($this->Bookmarks->find()**->limit(2)**));

 the limit set in the pagintation option overrrides the limit set in the query builder
in the case one wants to limit the results set to xx records
instead of limiting the number of results per page

**Comment by ADmad** [comment]
> the limit set in the pagintation option overrrides the limit set in the query builder
in the case one wants to limit the results set to xx records
instead of limiting the number of results per page

I don't see a problem with that. The whole point of paginator is to set limit and offset for the query.

**Comment by ideagroup-dev** [comment]
What if one wants to paginate 10 rows per page but no more than 1000 records paginated that way?
how would one set the 1000 records limit?

**Comment by ADmad** [comment]
You will have to implement your own paginator for that :)

**Comment by ideagroup-dev** [comment]
in fact i just need a maxPage property that limits the number of pages (companion of maxLimit) !!
modify the cake paginator component ?

**Comment by ADmad** [comment]
You could easily restriction the max page number in your app itself. The paginator would still be returning all counts based on total records/pages so a "maxPage" wouldn't make sense in PaginatorComponent but could can extend the core component and do so in your custom one.

**Comment by ideagroup-dev** [comment]
as far as I understand 
in the core paginator component, limit is intended for limiting the number of rows per page
on the other hand in the query builder limit sets the mysql LIMIT value whenever the app is connecting a mysql database
You suggest that I should create a controller component that extends the core paginator component
Appreciate the advise
will certainly give it a try unless it is milestoned for next release (ha ha)?

**Comment by ideagroup-dev** [comment]
I definitly need to figure out something
althought I don't really have any experience on how to contribute or submit any kind of code to the cake community
if there was any guideline available i will defintly check it out...

**Comment by ideagroup-dev** [comment]
I don't see a problem with that. The whole point of paginator is to set limit and offset for the query.

is there a way to generate a query with no offset statement at all with the paginator component ?

**Comment by ideagroup-dev** [comment]
> considering the following instruction :
> $this->set('bookmarks', $this->paginate($this->Bookmarks->find()->limit(2)));
> 

considering the offset value

$this->set('bookmarks', $this->paginate($this->Bookmarks->find()**->limit(0)->page(1000)**));
should limit the total number of rows to 1000
