### ISSUE TITLE
4.x: Add optional support for use twig templates for view template rendering

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#11343]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x

Suggestion: https://github.com/cakephp/cakephp/issues/10852#issuecomment-313333554
Twig for cake/bake https://github.com/cakephp/bake/issues/371#issuecomment-337923209

**Comment by dereuromark** [comment]
This should be opt-in IMO and CakePHP should probably still support normal .ctp PHP templates here.

The related bake thing is rather unrelated, as there we generate PHP files via PHP which is totally bad and needs hacking around with a unicorn solution.
So there it makes sense to completely switch to a true templating engine that is written in a different "language" so to speak.

**Comment by inoas** [comment]
Well generating Twig with Twig will bring back the same problem?

So ***in case there is a conflict*** I'd say switching the generated output to twig and keeping cake/bake php is preferred.

As for the benefits of Twig as a view template language:

> With that said. I don't think our PHP templates are a good idea long term. It is far too easy to accidentally make a XSS hole.

Source: https://github.com/cakephp/bake/issues/371#issuecomment-337921816
... is reason enough.

**Comment by markstory** [comment]
> Well generating Twig with Twig will bring back the same problem?

Not necessarily. Twig lets you swap out the delimiters used so it would be possible to generate twig with twig.

**Comment by chinpei215** [comment]
I am not in favor of using Twig by default. Sorry if I have misunderstood, but I think it would require not a few additional knowledge - not only the basic features of Twig, but also some customized features for CakePHP, such as `{% cell %}` and `{% element %}`. Additionally, It would introduce some confusion between `View::extend()` and `{{extends}}`, or View blocks and `{% block %}`. It would also make difficult to do step-in debugging.

Instead, I would like to suggest to introduce our own templates - Cake TemPlate (ctp). The only difference between PHP and CTP is an additional `declare` directive:
```php
// In somewhere in your application
register_autoescape_function('h');
```
```php
// In view templates
<?php declare (autoescape=1): ?>
   <?= $var // The output will be escaped automatically by the autoescape handler ?>
<?php enddeclare ?>
```
It would be easy to implement this feature, and probably work faster than Twig, as we can leverage `token_get_all()`.

To be honest, I think this feature should be provided by PHP itself. Though I am not sure whether someone had requested the PHP team to provide this kind of feature in the past, if this feature get good reputation, the PHP team might consider to introduce this feature into the core.

**Comment by markstory** [comment]
@chinpei215 I don't think [declare](http://php.net/declare) allows userland extensions. We could build a template parser, but I think building our own is not a great use of time when there are battle-tested implementations like Twig. Given the overlaps around block features (extends, block), I would see us adopting the features of twig where possible.

I agree that autoescaping should be something PHP provides, but I don't see it happening anytime soon.

**Comment by ADmad** [comment]
> Given the overlaps around block features (extends, block), I would see us adopting the features of twig where possible.

:+1:

**Comment by inoas** [comment]
I don't think we should drop the regular CakePHP View class (that renders ctp for instance, features blocks, cells, elements) at any time. It is still valuable and yields a lot of power to the developer (and eventually would be the base to run TwigView ontop, I assume).

However Twig is a great tool for future developers, increased adoption of CakePHP, integration in the PHP eco-system, security and  division of labour. For instance you could potentially even give write access to designers or CMS towards Twig files, without yielding full control of your application to the "designer" or "admin".

In case of collisions of concepts we can always prefix with cake ( say `{% cake_block %}` ).

**Comment by markstory** [comment]
> I don't think we should drop the regular CakePHP View class (that renders ctp for instance, features blocks, cells, elements) at any time. It is still valuable and yields a lot of power to the developer (and eventually would be the base to run TwigView ontop, I assume).

I'm not recommending we do that. It would create a big backwards compatibility break which I don't want to have. PHP templates would live for quite some time.

**Comment by ADmad** [comment]
PHP based templates are going to stay the default for the foreseeable future and [TwigView](https://github.com/WyriHaximus/TwigView) provides good enough support for using Twig templates with CakePHP. Hence closing this issue.
