### ISSUE TITLE
Email validation gethostbynamel is used wrong

### ISSUE THREAD

**Issue by jeroenbos22** [cakephp/cakephp#11342]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.x / 2.10.x

### What you did
I validated email-adresses with deep validation. On our production-server it says every email-adress is valid. Tested with gmail.com and gmail.cok (filled in by user). Both tested true.

### What happened
When checking the Email validation done by cake I see the use of gethostbynamel (which is provided with the hostname as argument). If the output is an array it returns true. If you check the php documentation you need to provide an dot on the and otherwise it will check it as a local domain, and thats exectly whats happening because it will return an array with the servers ip when providing gmail.cok. Adding the dot after the hostname fixes the issue: 
return is_array(gethostbynamel($regs[1].'.'));

**Comment by markstory** [comment]
Close as a pull request is open now.

**Comment by markstory** [comment]
2.x fixed in #11371
