### ISSUE TITLE
joins result null values for all field if the condition is in array key-value style

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#11367]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.4.13
* Platform and Target: Apache/2.4.25 (Ubuntu), PHP Version 7.0.22-0ubuntu0.17.04.1, MySQL 5.7

### What you did
I have created a custom finder with a right join. I defined the second parameter for the right join in the array syntax as anywhere else.
`$this->find()->rightJoin(
            ['latest' => $latest],
            [
                'Histories.company_grant_id' => 'latest.cg_id',
                'Histories.created' => 'latest.latest'
            ]
        );`

### What happened
The generated SQL is ok, running it in the MySQL console returns the expected results. After executing the query I got the excepted number of entities, but all filed values are null.

### What you expected to happen
I expexted to get the entities with the values from the SQL.

Solution: do not use the array key-value syntax for the condition, but use equals instead.
`$this->find()->rightJoin(
            ['latest' => $latest],
            [
                'Histories.company_grant_id = latest.cg_id',
                'Histories.created = latest.latest'
            ]
        );`

If it is like that for some purpose it should be more clearly stated in the cookbook. This kind of behaviour is hard to debug, as the generated SQL is OK, but the results are not.

**Comment by markstory** [comment]
Are you sure your query is being generated correctly? An array style join condition generally results in the values being set as bound parameters which in your case would result in something like

```sql
RIGHT JOIN () AS latest ON `Histories.company_grant_id` = 'latest.cg_id' AND `Histories.created` = 'latest.latest' 
```
Which is not what I think you're hoping to get.

Instead you might want to try making the values of your conditions into `IdentifierExpression` objects.

```php
use Cake\Database\Expression\IdentifierExpression;

[
  'Histories.company_grant_id' => new IdentifierExpression('latest.cg_id'),
  'Histories.created' => new IdentifierExpression('latest.latest')
] 
```

**Comment by rrd108** [comment]
Well, I was sure that I got the desired SQL, but it seems you are right.
My query object is this:

```php
object(Cake\ORM\Query) {
	'(help)' => 'This is a Query object, to get the results execute or iterate it.',
	'sql' => 'SELECT Histories.id AS `Histories__id`, Histories.company_grant_id AS `Histories__company_grant_id`, Histories.status_id AS `Histories__status_id`, Histories.user_id AS `Histories__user_id`, Histories.event AS `Histories__event`, Histories.created AS `Histories__created` FROM histories Histories RIGHT JOIN (SELECT Histories.company_grant_id AS `cg_id`, (MAX(Histories.created)) AS `latest` FROM histories Histories GROUP BY Histories.company_grant_id ) latest ON (Histories.company_grant_id = :c0 AND Histories.created = :c1)',
	'params' => [
		':c0' => [
			'value' => 'latest.cg_id',
			'type' => 'integer',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => 'latest.latest',
			'type' => 'datetime',
			'placeholder' => 'c1'
		]
	],
        ...
```
Placeholders c0, and c1 gets the correct types, c0 should be and integer, and c1 a datetime.

However I just realized debugkit shows this SQL statement:

```sql
SELECT 
  Histories.id AS `Histories__id`, 
  Histories.company_grant_id AS `Histories__company_grant_id`, 
  Histories.status_id AS `Histories__status_id`, 
  Histories.user_id AS `Histories__user_id`, 
  Histories.event AS `Histories__event`, 
  Histories.created AS `Histories__created` 
FROM 
  histories Histories 
  RIGHT JOIN (
    SELECT 
      Histories.company_grant_id AS `cg_id`, 
      (
        MAX(Histories.created)
      ) AS `latest` 
    FROM 
      histories Histories 
    GROUP BY 
      Histories.company_grant_id
  ) latest ON (
    Histories.company_grant_id = 0 
    AND Histories.created = 'latest.latest'
  )
```
It seems that the first placeholder is not latest.cg_id, but it replaced with a 0.

Using `IdentifierExpression()` also solves the issue.

Anyway I would reccomend to have a paragraph in the documentation about IdentifierExpression, why, when and how to use it.

**Comment by ADmad** [comment]
The book already has [examples](https://book.cakephp.org/3.0/en/orm/query-builder.html#adding-joins) for how to specify conditions for joins.

**Comment by rrd108** [comment]
You are right, there are.

What I trying to tell is with a quite good history with Cake, it was not clear for me. Maybe others also meet the same problem.

Otherwise `quoteIdentifiers` is `false` for me, but hte cookbook there says, I should use `IdentifierExpression` if `quoteIdentifiers` would be `true`. Or am I wrong?

**Comment by lorenzo** [comment]
You should always use `IdentifierExpression` when comparing columns by name

**Comment by markstory** [comment]
DebugKit's placeholder replacement sounds like a separate issue. The query builder is working correctly, and should generate the desired SQL if `IdentifierExpression` objects are used.
