### ISSUE TITLE
Allow conditions or callable to be passed to Association::setDependent() ?

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#11361]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: eb609aff20945f8bc86cfb1fd3c50e6c62a502b0 (3.5.4)
* Platform and Target: n/a

### What you did
Tried to find a way to pass conditions/callable to a table's dependent association so that cascading deletes will occur or not occur based on a specific condition.

### What happened
I don't think this option is supported.

### What you expected to happen
I thought it would be nice if the feature existed.

Is there a feature like this already that I just don't see?

Basically I'm imagining something like this would be nice when setting up associations:
```php

# In say, Articles Table

$this->hasMany('Comments')
    ->setDependent(function ($comment) {
        return $comment->is_archived === false;
    });

# or maybe modifying the query in cascadeDelete would be better?
$this->hasMany('Comments')
    ->setDependent(function ($query) {
        return $query->where(['Comments.is_archived' => false]);
    });

# perhaps allow it to simply append to the $conditions array created in cascadeDelete?
$this->hasMany('Comments')
    ->setDependent(['Comments.is_archived' => false]);
```

I don't know how useful this would be to others, but unless I'm missing something obvious, if you want to automatically delete dependent records conditionally, you have to remove `->setDependent(true)` and handle this yourself in the `afterDelete` callback for instance, so this would be a handy shortcut I think.

**Comment by kevinquinnyo** [comment]
by the way I realize my specific my example is kind of weird, but I just wanted to stick with the default Articles and Comments that are used as examples in the docs, etc

**Comment by kevinquinnyo** [comment]
Just an additional thought -- since setDependent expects boolean (or null) currently, to avoid the headache of adding type checks inside the method (`if (is_callable($dependent))`, `if ($dependent === null)`, etc) and maybe for more flexibility it might be better to allow an `$options = []` to be passed to setDependent for this purpose?

**Comment by markstory** [comment]
I don't know how the query modification approach would work. But having setDependent() calculate state based on the entity state could be reasonable.

**Comment by kevinquinnyo** [comment]
@markstory No rush on this obviously. I just had some time at the end of the day here and thought I would give this a shot. Can you think of anything I'm overlooking with the minor changes in the PR?

I can write a test for it too but haven't yet.
