### ISSUE TITLE
Automatic IN creation slow

### ISSUE THREAD

**Issue by darxmac** [cakephp/cakephp#11373]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4

When doing a query like:

```php
$variants = $this->ProductsVariants->find('all')
            ->select(['variant_id'])
            ->group(['variant_id'])
            ->where(['ProductsVariants.product_id' => $productIds], ['ProductsVariants.product_id' => 'integer[]'])
            ->enableHydration(false)
            ->all()
        ;
```

it takes about 17-18 seconds to run.

If I change the `where()` statement to:

```
->where(['ProductsVariants.product_id IN (' . implode(',', $productIds) . ')'])
```

it takes just a few milliseconds. Clearly the automatic IN creation does something intensive. (Note, in my case the $productIds array contains ~7000 items.

Is this just the workaround, or is there a better way ?

**Comment by inoas** [comment]
Your code does not prohibit sql-injection. Otherwise no clue.

**Comment by dereuromark** [comment]
Wouldn't

    ->where(['ProductsVariants.product_id IN' => $productIds])

be the correct way here?

**Comment by inoas** [comment]
Not sure if it is (still) required but I always add a space `->where(['ProductsVariants.product_id IN ' => $productIds])`

**Comment by dereuromark** [comment]
> Not sure if it is (still) required

No, it is actually the opposite: It is dangerous to add this extra space, at least in 2.x this broke stuff afaik.

**Comment by lorenzo** [comment]
Do you get the productIds from another query? I’m sure passing the query as per of the where condition will be the fastest option

**Comment by markstory** [comment]
7000 bound parameters would be slower than string concatenation. I don't know what we can do here.

**Comment by ADmad** [comment]
As explained the slowness is due to binding of ~7000 params and there isn't much that can be done to improve that. The issue can be mitigated by using a query instead of array of ids as mentioned by lorenzo.

Closing as there's nothing to be done here.
