### ISSUE TITLE
Cake\Http\Client\Auth\*::authentication() - mutable or immutable

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11374]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

please see `$request` object on the
```php
Cake\Http\Client\Auth\Basic::authentication(Request $request,..)
Cake\Http\Client\Auth\Digest::authentication(Request $request,..)
Cake\Http\Client\Auth\Oauth::authentication(Request $request,..)
```
in the `basic` you can see `$request` changed (mutable)
```php
        if (isset($credentials['username'], $credentials['password'])) {
            $value = $this->_generateHeader($credentials['username'], $credentials['password']);
            $request = $request->withHeader('Authorization', $value);//  <---here
        }

        return $request;
```
but in the `Digest` and `Oauth` 
we see immutable method 
```php
return $request->withHeader('Authorization', $value);
```
I think we should use same mutable or immutable approach  for all `authentication` methods

**Comment by ADmad** [comment]
I don't understand what you are trying to say. In all the 3 cases the `Authorization` header is added and new request instance is generated using `$request->withHeader()`. Only difference is the in `Basic::authenticate()` the instance is first assigned to a variable `$request` while in other 2 cases it's directly returned.

**Comment by saeideng** [comment]
I means
We should replace
```php
return $request->withHeader('Authorization', $value);
```
With
```
$request=$request->withHeader('Authorization', $value);
return $request;
```

**Comment by ADmad** [comment]
No, cause it won't make any difference. Object immutability has nothing to do with how the return value is used.

**Comment by saeideng** [comment]
@markstory  says in https://github.com/cakephp/cakephp/pull/8837
>Having the authentication providers return a request is one possible place where BC could have broken

before this you was able to use something like
```php
$auth = new Oauth();
$auth->authentication($request, $options);
$request->...();
```
but now,you should use 
```php
$auth = new Oauth();
$request=$auth->authentication($request, $options);
$request->...();
```

I'm ok by this approach (immutable ) 
but I say cookbook needs a note about this 
can anyone update the book

in this case we need to update basic class from `mutable` into `immutable`
