### ISSUE TITLE
3.6 - Add deprecation warnings across all packages

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#11385]
We have a number of documentation only deprecations across CakePHP. Update these documentation warnings to be runtime errors using `deprecationWarning()`. Having runtime warnings will make it easier for application/plugin developers to know if they are ready for 4.0.0

### Packages to Update

* [x] Auth
* [x] Cache
* [x] Collection
* [x] Console
* [x] Core
* [x] Database
* [x] Event
* [x] Filesystem
* [x] Form
* [x] Http
* [x] I18n
* [x] Log
* [x] Mailer
* [x] Network
* [x] ORM
* [x] Routing
* [x] Shell
* [x] Template
* [x] TestSuite
* [x] Utility
* [x] Validation
* [x] View
* [x] Add warnings for class moves across the various packages.
* [x] Move http exceptions to Http package.
* [x] Revisit `orWhere()` usage in  ORM\Marshaller and in Database\TupleComparisonTranslatorTrait.
* [x] Deprecate ServerRequest::addParams() and ServerRequest::addPaths()
* [x] Add warnings for public properties in `ServerRequest`
* [x] Deprecate ServerRequest public properties.

**Comment by josegonzalez** [comment]
For the shell deprecations, we actually deprecated the whole shell class. I don't think we want to add `deprecationWarning` to the top of the class as any inclusion will trigger it. Leaving it alone sounds fine, right?

**Comment by josegonzalez** [comment]
I've marked `Shell` as complete as it's done in 3.next at least.

**Comment by markstory** [comment]
> For the shell deprecations, we actually deprecated the whole shell class. I don't think we want to add deprecationWarning to the top of the class as any inclusion will trigger it. Leaving it alone sounds fine, right?

`Shell` is special in that it isn't going away until 5.0. I've not added warnings to the class moves yet, as I wasn't sure that was necessary. Now that you bring it up, old class locations should likely emit warnings too.

**Comment by markstory** [comment]
Closing as to the best of my knowledge all the currently deprecated features have runtime warnings :tada:

**Comment by HJerem** [comment]
@markstory 
Deprecated warnings are not displayed when in debug mode :
```php
        if (Configure::read('debug')) {
            $this->addPlugin(\DebugKit\Plugin::class);
        }
```

If I comment this out, deprecated warnings are displayed.

**Comment by markstory** [comment]
> Is there an option to "not catch them" ? Because otherwise we need to check this panel everytime.

Not right now, but the panel should have a 'counter' letting you know when you need to look into the panel.

>  Also, we can't see deprecated warnings when they are happening on submitted forms with redirection, right ?

Deprecation warnings should show up in your logs as well.

**Comment by saeideng** [comment]
you can disable this panel
```php
if (Configure::read('debug')) {
      Configure::write('DebugKit.panels', ['DebugKit.Deprecations' => false]);
      $this->addPlugin(\DebugKit\Plugin::class);
}

**Comment by HJerem** [comment]
@markstory 
> Deprecation warnings should show up in your logs as well.
No they didn't.

> you can disable this panel
It worked perfectly, thanks ! Deprecated warnings are now correctly displayed in local environment 👍
