### ISSUE TITLE
Add support to join on different databases using leftJoinWith() or contain(belongsTo)

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#11394]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: Windows Server 2012, SQL Server 2008 R2 and PHP 7.0

### What you did
two tables, different databases:

**Articles** in the connection 'default'
**Users** in the connection 'anotherdb'

Articles belongsTo Users

`$this->Articles->find()->contain('Users');`

### What happened
CakePHP used the table name from another datasource without prefixes causing **error** for the current connection because the table does not exists there

```
select fields 
from articles Articles
left join users Users on (Users.id = Articles.user_id)
```

### What you expected to happen
CakePHP would add prefix to support join between different databases like:

```
select fields 
from articles Articles
left join anotherdb.dbo.users Users on (Users.id = Articles.user_id)
```

Databases support:

- [mysql](https://stackoverflow.com/questions/12685193/how-to-left-join-2-tables-on-2-different-databases)
- [sqlserver](https://stackoverflow.com/questions/5145637/querying-data-by-joining-two-tables-in-two-database-on-different-servers)
- postgres & oracle (only with dblink unfortunately)

**Comment by markstory** [comment]
We had transparent support for cross database joins very briefly but it was reverted because it had several sharp edges that we couldn't resolve. You may want to use `strategy => select` in the meantime. This should result in associations being loaded with separate queries and not joins.

**Comment by celsowm** [comment]
Hi @markstory thanks for answer me again.

Well.. It's a little bit sad that you guys had problems with transparent cross database joins, so how about "non-transparent cross database joins"?

Idea number 1:

```
//A new associations method/parameter
$this->belongsTo('Users')->setPrefix("anotherdb.dbo.");
```

Idea number 2:

```
//A new parameter on contain() 
$this->Articles->find()->contain('Users', ['prefix'=>'anotherdb.dbo.'])
```

or at least a less verbose way to do that:

```
$table_users     = TableRegistry::get('Users');

$this->Articles->find()->leftJoin(['Users' => "{$table_users->defaultConnectionName()}.dbo.{$table_users->getTable()}"]);
```

**Comment by markstory** [comment]
You should able to use prefixes in your table names with `$this->setTable('otherdb.articles')` as well. Cross schema joins were complicated because they often overlap with multiple connections and it is hard for the orm to safely create cross connection joins as the connections could be separate servers or different server types.
