### ISSUE TITLE
HTTP Client causes circular loop when auth config specified on Client

### ISSUE THREAD

**Issue by timalive** [cakephp/cakephp#11399]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4
* Platform and Target: 
Request made from Chrome to a local apache2 webserver.  Http Client in question accessing another CakePHP 2 application with Digest auth enabled.

### What you did and What Happened
When a request is made with Digest Auth using Http Client, where settings are stored in the client (and not passed on the get function) and do not specify the domain, nonce and other Digest configs.
The Digest adapter then hits the server with no authentication to get the Digest configuration ([the _getServerInfo function of the Digest adapter](https://github.com/cakephp/cakephp/blob/master/src/Http/Client/Auth/Digest.php#L81))
Due to the fact that config is merged from the Client, this subsequent hit is also done using an incomplete Digest configuration, which again triggers a hit to the server to get Digest configuration and so on.

I will submit a pull request with a suggested fix.

**Comment by timalive** [comment]
see pull request: https://github.com/cakephp/cakephp/pull/11400

**Comment by markstory** [comment]
Closing as there is a pull request open.
