### ISSUE TITLE
Association conditions + EagerLoading ( Association conditions + containt + matching ) bug

### ISSUE THREAD

**Issue by Unsigno** [cakephp/cakephp#11407]
I searched and readed a lot to reach conclusions about it is a implementation problem or a bug, and where pointing the bug . But i'm still not sure, so some comment or correction is apreciated .

I don't want a solution for my case, i fix it, but i think is a bug and should be nice get a fix .

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4
* Platform and Target: Apache 2.4.23, MySQL 5.7.14 and PHP 7.0.10

### What you did

I have the models `Comments`, `Articles`, `Photos` and `Users` .

`Users` hasMany `Photos`  ( `Photos` belongsTo `Users`)
`Users` hasMany `Articles`  ( `Articles` belongsTo `Users`)

`Photos` hasMany `Comments`   ( `Comments` belongsTo `Photos`)
`Articles` hasMany `Comments`    ( `Comments` belongsTo `Articles`)

As you can see `Comments` is polymorphic, it can belong to `Photos` or `Articles` . Following the documentation and some articles i use the bellow definition for the associations : 

```

// CommentsTable

$this->belongsTo('Photos', [
        'foreignKey' => 'commentable_id',
        'conditions' => [ 'Comments.commentable_type' => 1 ]
]);
$this->belongsTo('Articles', [
        'foreignKey' => 'commentable_id',
        'conditions' => [ 'Comments.commentable_type' => 2 ]
]);

// PhotosTable

$this->hasMany('Comments', [
        'foreignKey' => 'commentable_id',
        'conditions' => [ 'Comments.commentable_type' => 1 ]
]);

// ArticlesTable

$this->hasMany('Comments', [
        'foreignKey' => 'commentable_id',
        'conditions' => [ 'Comments.commentable_type' => 2 ]
]);

```

### What happened

This is working perfectly for almost all cases . Using `contain` i get the related data and SQL sentence is correct. I can filter `Comments` by `Users` with `matching` and SQL sentence is correct again, related data is correct too but stored is `__matchingData` , all ok there .

The problem begins if i want the `__matchingData` associated to `Comments` . In normal case you just need to add a `contain` : 

```
// finding all Comments of Photos, with Photos, from a specific User
$commentsTable->find('all')
    ->where(['Comments.commentable_type' => 1])
    ->contain(['Photos'])
    ->matching('Photos.Users', function($q) {
        return $q->where(['Users.id' => $userId]); // ( $userId conext its ok )
    })
``` 

These query should work, but in this case is generating a bad SQL sentence . It runs the `matching` and correct SQL , but for `contain` generates new SQL's through `eagerLoading` or some internal thing to 'Photos' that look so 

```
SELECT * // all photo fields aliased, the query is just an example 
FROM photos
WHERE Comments.commentable_type = :c0 AND Photo.id IN (:c1)
```

The SQL is not a copy+paste, but you can see internally generates a `SELECT` on `Photos`, using a list of id's and a `Comments` condition. So it looks a bug generating the `eagerLoading` queries with conditions, because to use the `IN` strategy you should apply the `Comments.commentable_type` condition to filter the id's list, not when use it .

I tryied to simplify the case but some details request or notation is apreciated .
  
### What you expected to happen

I expect all Comments of Photos, with related Photos, filtered by User .

**Comment by markstory** [comment]
If you only contain() the Photos association is the generated query correct?

**Comment by Unsigno** [comment]
Yes , contain() is correct , matching() is correct , but together fails .

**Comment by kojot1234** [comment]
Just ran into this issue as well. Seems to be related when using custom `->select()`.

It works fine without specifying select.

```
$query = $this->LessonRecords->find()
            ->contain(['Users'])
            ->select([
                'Users.id',
                'Users.first_name',
                'Users.last_name',
                'Users.email',
                'LessonRecords.id',
                'LessonRecords.percent_complete',
            ]);
...
$query->matching(['Users.UserSchools'=>function($q) use ( $schoolId) {
            return $q->where(['UserSchools.school_id'=>$schoolId]);
}]);
```

**Comment by Unsigno** [comment]
What is your result @kojot1234  ?

**Comment by kojot1234** [comment]
If the above query is ran is `$entity->user` results with `null` and `_matchingData` is correct.

However if `->select()` is removed from the query (defaults to selecting all) both `$entity->user` and `_matchingData` result with correct values.

It seems an an entity patching issue since the query is generated correctly in both cases.

**Comment by markstory** [comment]
@kojot1234 It doesn't look like you are selecting the foreign key columns. If you add those is the data correctly hydrated?

**Comment by kojot1234** [comment]
@markstory you are absolutely right, selecting additional `LessonRecords.user_id` makes the contain available again. Thank you.
