### ISSUE TITLE
Manipulate date/Time/DateTime with more accurate

### ISSUE THREAD

**Issue by AndreLZGava** [cakephp/cakephp#11419]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
I need to deal with date and time, but I need to do something better than just recover Time::now() I need to get current date and discover its start and end day, same to week, month and year, Rails does. I found nothing in stack or Cake Documentation related to this. I cannot convert Time::now() to just date either;

### What happened
I just can get DateTime, set a specific date, sum days/months but dont get the initial or end of it.

### What you expected to happen
Can you guys provide class options to do this like rails does?
Function to convert Time::now() (datetime to date)
Functions to discover begging of day/month/week/year etc. And its ends.

**Comment by markstory** [comment]
There are a few methods like that already

* start/endOfDay
* start/endOfWeek
* start/endOfMonth
* start/endOfYear

Are those the kinds of things you're looking for?

**Comment by AndreLZGava** [comment]
Yes this may help, but not enoght, Isn't it in documentation, is it? I didn't found

**Comment by lorenzo** [comment]
What would be enough?

**Comment by AndreLZGava** [comment]
Call something like  $date = Time::now, them from time to date $date->toDate(), back to time $date->toTime is possible to make more fluid conversions?

**Comment by ADmad** [comment]
https://book.cakephp.org/3.0/en/chronos.html

**Comment by AndreLZGava** [comment]
I didn't Know, Thank U ADmad this helps a lot :)
