### ISSUE TITLE
2.x HtmlHelper API documentation breaks

### ISSUE THREAD

**Issue by ritesh-pandey** [cakephp/cakephp#11426]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x
* Platform and Target: https://api.cakephp.org/2.6/class-HtmlHelper.html

### What you did
- Open https://api.cakephp.org/2.6/class-HtmlHelper.html
- You can't find anything after return value of `css()`

### What happened
Source code comment parser inserts `style` tag here. Therefore, anything after is not visible on browser.

### What you expected to happen
Complete documentation of `HtmlHelper` API should be displayed.

**Comment by ritesh-pandey** [comment]
Looks like the problem has been fixed at https://github.com/cakephp/cakephp/commit/619b1addd64780f542c6e1388749e0c4eed7e9fb by @ADmad 

But docs is still outdated.

**Comment by saeideng** [comment]
@ADmad fixed the cake 3.x

**Comment by markstory** [comment]
The 2.6 documentation is broken. Use the 2.8 documentation instead.
