### ISSUE TITLE
One hour difference after set custom time zone between local development and VPS production

### ISSUE THREAD

**Issue by fgagneten** [cakephp/cakephp#11420]
My site needs to display hours from my MySQL database. The hours in my database is saving in UTC 0 format.

What I do before showing the date time to my user:
    
    <td><?= h($this->Time->format($myObject->initDate,'dd/MM/yyyy HH:mm:ss', null, $Auth->user('time_zone')))?></td> 

"time_zone" is 

    America/Argentina/Buenos_Aires

**IMPORTANT** (Before answer)

- In my local environment (XAMPP) works PERFECT: the original hour is 20:00 pm before formatting and after that is 17:00 pm (the user see 17:00 pm GREAT!)

- In my VPS environment (MySQL, PHP 7, CentOS 6): the original hour is 20:00 pm before formatting and after that is **18:00 pm** (the user see 18:00 pm  **an hour less**)

- I thought that maybe was the server, but not, because after doing 

    `Time->format`

The hour is the same that my local envirnment.

Version of local environment Cakephp:  3.4.7
Version of VPS environment Cakephp:  3.5.5 (I've just updated it, Before that, the version was 3.4.7. I thought maybe the problem was the version but no)

**bootstrap.php** (same code for both environment)

    date_default_timezone_set('UTC'); 

**app.php**

    'Datasources' => [
        'default' => [
            ...
            ...
        'timezone' => '',
            ...
         ]
     ]

Any help? I need to solve it ASAP

Thanks

**Comment by markstory** [comment]
Check that you have the same timezone databases installed in both environments. Given that your code and CakePHP work fine in one environment but not the other, the issue is environment specific and not related to CakePHP.

**Comment by fgagneten** [comment]
Why did you close it? **Before formatting the hour, in my local and VPS environment have THE SAME hour.**

I mean, if I put the following line
    
    <td><?= h($myObject->initDate)?></td> 

In my local and VPS environment display the same hour (20:00 pm).
 
Please, read again my question.

**Comment by ADmad** [comment]
The time zone for your database might be different on local and production server. Also you are not specifying timezone in your db config.  The problem is with your environment, it's not a bug in cakephp. 

Thus is a bug tracker not a help forum. Use our help forum, slack or IRC channel if you need help sorting out the issue.

**Comment by markstory** [comment]
@fgagneten I don't have an answer for why this is happening, but given that it only happens in that one environment, the issue is likely related to something about that environment. Without a way to reproduce this issue there is really nothing we can do.
