### ISSUE TITLE
RFC: Return null instead of false on cache miss.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11428]
It would be better if `Cache::read()` and `CacheEngine::read()` returned `null` instead of `false` on cache miss, as `null` better represents "value does not exist".  

Moreover [CacheItemInterface::get()](https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L38) of PSR-6 and [CacheInterface::get()](https://github.com/php-fig/simple-cache/blob/master/src/CacheInterface.php#L8) of PSR-16 also return `null` on cache miss.

This change would help us get closer to providing a PSR-16 complaint caching API.

**Comment by dereuromark** [comment]
null should be the default/alt value for a lot of methods that return false right now :)

**Comment by inoas** [comment]
Is this BC-save? 4.x?

Also wouldn't it be better if there was an optional way to really know if it was a miss vs a valid `null` or valid `false` (such as through returning an array with a state flag or throwing an exception).

**Comment by markstory** [comment]
@ADmad I like the idea, but how do we do that change in a backwards compatible way.

**Comment by dereuromark** [comment]
I think he is saying that with 4.0 as major these small semantics can be done in a reasonable way with only little BC break here.

**Comment by ADmad** [comment]
Yeah I am proposing doing this in 4.0.

**Comment by burzum** [comment]
I've started working on a PSR compatible cache interface, it's in my fork because it is not yet close to be ready but I've got the basics covered I hope.

https://github.com/cakephp/cakephp/compare/3.next...burzum:3.next-cache?expand=1

**Comment by ADmad** [comment]
Closing in favor of #12483.
