### ISSUE TITLE
Request session id auto changed every time after auth login

### ISSUE THREAD

**Issue by hanuman1989** [cakephp/cakephp#11437]
I am new with cakephp currently i am using cakephp 3.5. I have faced a problem with session id, we required unique session using $this->request->session()->id() but when i logged in then $this->request->session()->id() this session id auto changed every time after auth login

**Comment by ADmad** [comment]
That's expected. The session id is regenerated after login for security reasons.

**Comment by hanuman1989** [comment]
ok, then now any way to generate session ID?

**Comment by markstory** [comment]
session ids should be unique automatically.
