### ISSUE TITLE
[+3.6 ]  functions.php/deprecationWarning()  and cake packages 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11438]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: +3.6

in cake 3.6 if someone want to use Cake packages like `cakephp/orm` 
they  will receive fatal error

`Call to undefined method deprecationWarning .. `
because all of `composer.json` not  contain    something  like bellow  in their `composer.json`
```php
        "files": [
            "functions.php"
        ]
```

**Comment by markstory** [comment]
The cakephp/core package autoloads `functions.php` and most other packages rely on cakephp/core. I would have thought that enough to get the function loaded.

**Comment by saeideng** [comment]
about `cakephp/core` you are right 
but see `composer.json` for 
`cakephp/Event`
`cakephp/Filesystem`
`cakephp/Utility`

**Comment by markstory** [comment]
Ok. We're missing some dependencies across the packages then. I'll get that fixed up.

**Comment by markstory** [comment]
Fixed with #11441
