### ISSUE TITLE
Cake 2: Catch block not executing even if recipient email doesn't exist

### ISSUE THREAD

**Issue by charliwize** [cakephp/cakephp#11432]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] Question
* [x] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
 I am using cakePHP 2

is there a way in cakePHP to check if an email is delivered or not. I have tried to catch error when $Email->send(); executes. But this always returns some string containing the sent message body etc.

For example I have this:

     ```
    try {
        $to = $message_data['email'];
        if (isset($message_data['name'])) {
            $to = array($message_data['email'] => $message_data['name']);
        }
        $Email->template($template, 'default')
            ->from($sender)
            ->to("c.chardkhkhjfsd@gmail.com")
            ->subject($message_data['subject'])
            ->emailFormat('html');

        if ($replyTo) {
            $Email->replyTo($replyTo);
        }

        if (isset($message_data['attachment'])) {
            $Email->attachments(array(
                $message_data['filename'] => array(
                    'data' => $message_data['attachment'],
                    'mimetype' => $message_data['attachment_mimetype']
                )
            ));
        }
        $Email->send();     
    } catch (SocketException $e) {
        Debugger::log("no way");
    }

```
My smtp setup is like this:

    ```
public $test = array(
      'transport' => 'Smtp',
      'tls' => true,
      'from' => array('*************' => '****'),
      'host' => 'smtp.gmail.com',
      'port' => 587,
      'timeout' => 30,
      'client' => null,
      'log' => false,
      'username' => '***************',
      'password' => ''
   );
```

**Comment by markstory** [comment]
> is there a way in cakePHP to check if an email is delivered or not. 

Yes there is. And you're doing it. The SmtpTransport will throw exceptions when the SMTP server fails to accept a connection or rejects authentication. Sending email to recipients that don't exist *is not* an exception for CakeEmail as the email message got to the SMTP server, and the rejection will happen later when the mail server attempts delivery.

**Comment by charliwize** [comment]
ok, how do I then catch when the SMTP server fails to accept a connection?

**Comment by markstory** [comment]
The catch block you have should be doing that.  You can test that scenario by setting the host to `example.com`.

**Comment by charliwize** [comment]
i am sorry if I am not understanding you but are you asking me to change the host from `smtp.gmail.com` to `example.com`

**Comment by markstory** [comment]
> I'm sorry if I am not understanding you but are you asking me to change the host from smtp.gmail.com to example.com. 

Yes exactly that. That should result in a timeout/connection error.

**Comment by charliwize** [comment]
Hi, that works. But I guess you also meant there is not way to know if the SMTP server does not send mail because the recipient email is incorrect/does not exist.

**Comment by markstory** [comment]
> ...  you also meant there is not way to know if the SMTP server does not send mail because the recipient email is incorrect/does not exist?

Yes. That is not possible in general.
