### ISSUE TITLE
Decode request data

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#11436]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5
* Platform and Target: AWS

### What you did
Hi there.

On my cakephp App, when a user creates an account / logins, the password is encoded on clients side using public/private key method.

On the App, we decode it, and create the password/check the login information. I've used the following command:

$this->request->data['password'] = $this->RsaDecode($this->request->data['password']); and it worked nicely.

With the version 3.5.5, I've changed every $this->request->data['password'] field with $this->request->getData['password']. Yet, when I call the identify, it returns false.

If this is no way to make it like it was, is there any workaround that I can do it?

### What happened
Password gets decoded but identify fails.

### What you expected to happen
Password to be decoded, saved into the request array again to the user be identified

**Comment by markstory** [comment]
Are you using `$this->request->getData['password']` or `$this->request->getData('password')`? The difference being one is a method call, and the other is an array access. `getData()` is a method and will need to be called as one.

**Comment by Cafnio** [comment]
Ok, I've swapped it with the following code:

$this->request->data['password'] = $this->Users->rsaDecode($this->request->getData('password'));

Yet, it doesn't work either. 

I've understand what you have said, but I need to decode the password sent via Ajax on the controller and present it to the Auth->Identify() function. Since this last one identifies values from request->data, I need to update them somehow

**Comment by markstory** [comment]
Do you get different values for `$this->request->data['password']` and `$this->request->getData('password')`? They should reference the same value, as getData() is a fairly basic read method. https://github.com/cakephp/cakephp/blob/ec5f656a7ee9083c949525108c95f81eb59a86e7/src/Http/ServerRequest.php#L1523-L1533

**Comment by Cafnio** [comment]
Sorry for the delay, have been testing some stuff. I was able to solve the problem, so i'm going to put here what i've changed, so you can check if there is any problem:

This is the code that I use to test out my login:

` $this->post('/users/login', json_encode([
            'email' => "nfac93@gmail.com",
            'password' => 'kyjh1jI1g9dC3WzX+AiV2KAyfzcAfzpzggYxrvx0KBMPzZ1vz9mifPUuYSdmYcn1LgQLjlpXz0AWy3i88KO0rJ2XYD5dAXM+um6In1QL8DpCqhxWEjIHQChJVOoky2ejWWrr+aRelsFrtQRyOMjR/zFNnrJqHVwinCz5yNJnJxU=',
        ]));`

I json_encode it all because our front_end works that way.

To decode on the API side, on appController, I do the following:

$data = $this->request->input('json_decode', 'true');
$this->request->getData = $data;

Everything was working with only those two lines, except the login.

I've added the following and it started to work:

$this->request->data = $data;

Not sure if there is a better way to solve this (I believe so), but it's working now

**Comment by markstory** [comment]
You cannot assign to `request->getData` as that is not a property that the request will use. Modifying `request->data` will work in the short term, but will stop working in 4.0.

You may want to use `RequestHandlerComponent` to automatically parse your JSON requests. It will also be compatible in future releases.

Closing this as this isn't a problem with Cake, and more how you're modifying the request.
