### ISSUE TITLE
Missing header in test.php

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#11448]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.4.
* Platform and Target: Linux, MySQL, Apache, PHPUnit 4.8.36.

### What you did
Run test in the browser.

### What happened
The layout is broken. The header, and menu is missing, CSS not loaded.
![screenshot from 2017-11-21 13 13 35](https://user-images.githubusercontent.com/3830106/33072025-1f0f470a-cebe-11e7-8b39-790fb869212f.png)

HTML source starts with:
![screenshot from 2017-11-21 13 16 55](https://user-images.githubusercontent.com/3830106/33072072-4dc1c6ae-cebe-11e7-8185-5e2a0cb3db86.png)

### What you expected to happen
I would expect a normal page like this:
![screenshot from 2017-11-21 13 18 06](https://user-images.githubusercontent.com/3830106/33072110-6ebbaa28-cebe-11e7-8283-2f8db9162697.png)

**Comment by markstory** [comment]
My local test application works fine, how can someone reproduce this?

**Comment by bancer** [comment]
I suspect this is somehow related to PHPUnit 4.8.36 because we started to see that problem after updating PHPUnit.

**Comment by bancer** [comment]
```
 	 * Outputs debug information during a web tester (browser) test case
	 * since PHPUnit>=3.6 swallowes all output by default
	 * this is a convenience output handler since debug() or pr() have no effect
```
https://github.com/dereuromark/cakephp-tools/blob/3c74d55713cda6723ce927e1c05d90c5ad215362/TestSuite/MyCakeTestCase.php#L23

@dereuromark Could that be related? It seems you may have some knowledge about that.

**Comment by dereuromark** [comment]
No, more likely your URLS around the assets are not correct. Are you using a non root setup for your app? Usually one uses mydomain.local/ directly etc without subfolders to avoid these issues.

**Comment by bancer** [comment]
The URL is http://local.our-domain.com/test.php?case=Model/Country. HTML has no opening `<html>` tag, no `<header>`, so no assets are loaded. The first tag of source HTML is `<li class='skipped'>`.

It seems that adding `ob_end_flush();` at the end of `paintHeader()` [method](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/TestSuite/Reporter/CakeHtmlReporter.php#L34) fixes the problem. Would that be an acceptable fix?

```
	public function paintHeader() {
		$this->_headerSent = true;
		$this->sendContentType();
		$this->sendNoCacheHeaders();
		$this->paintDocumentStart();
		$this->paintTestMenu();
		echo "<ul class='tests'>\n";
		ob_end_flush();
	}
```

**Comment by markstory** [comment]
Closing as a pull request is open now.
