### ISSUE TITLE
Dispatch an event inside invokeAction to change action args

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#11446]
This is a (multiple allowed):

* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6.

### What you expected to happen
\Cake\Controller\Controller:: invokeAction uses "$request->getParam('pass')" as parameter for the action, I think that we could dispatch one event to be able to change the value passed to the action.

**Comment by rochamarcelo** [comment]
Some ideas of how to use this new event:

Easy dependency injection way without changing request params.


    public function view(SomeApi $api, $id = null)
    {
        $api->doSomething();
    }

Ability to change simple value into object instance (eg, id turns into entity)

    public function view(User $user)
    {
       ....
    }

    public function edit(User $user)
    {
       ....
    }

    public function delete(User $user)
    {
       ....
    }

**Comment by markstory** [comment]
Could you not use the existing `Controller.startup` event for that? It allows you to interact with the controller and its request before the action is invoked. This would allow you to modify the passed parameters replacing/augmenting them as necessary.

**Comment by rochamarcelo** [comment]
With `Controller.startup` I could set values to controller properties but to do so I need to use public property. If we modify the passed parameters by adding an object in `Controller.startup` event the new value could produce errors in components/helpers that expect simple values (eg PaginatorHelper). Modify request by adding an object is not a good choice when we don't wanna expose it in view layer.
Sometimes we just need to pass a value that obey the contract provided by the action method. Maybe there is a better way and maybe I'm the only one that had this need.

**Comment by markstory** [comment]
> Modify request by adding an object is not a good choice when we don't wanna expose it in view layer. ... Sometimes we just need to pass a value that obey the contract provided by the action method. Maybe there is a better way and maybe I'm the only one that had this need.

The passed parameters come from the request object. In your proposed event where would the passed parameters go?

**Comment by rochamarcelo** [comment]
In `Controller::invokeAction` method we could have something like:
  
```
    if (!empty($event->getResult()['actionArgs'])) {
        $actionArgs = $event->getResult()['actionArgs'];
    }
    
    return $callable(...array_values($actionArgs));
```
