### ISSUE TITLE
Bug in Marshaller::_mergeAssociation()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11444]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

latest cakephp master

after looking into https://github.com/cakephp/cakephp/pull/11439 I found out that

    protected function _mergeAssociation($original, $assoc, $value, $options)

expects \Cake\Datasource\EntityInterface as $original, but then passes this on to

    public function mergeMany($entities, array $data, array $options = [])

via `return $marshaller->mergeMany($original, $value, (array)$options);`
which expect an array of entities and directly

    foreach ($entities as $entity) {}

over them.

PHPStorm marks this as code smell / error of course, and it seems this is indeed some bug, is it not?

PS: Same for _mergeJoinData()

**Comment by markstory** [comment]
I think your pull request solves the issues with the doc block.
