### ISSUE TITLE
ignored exist field when using "EntityRoute"

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11455]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

https://github.com/cakephp/cakephp/pull/11300
in route class
```php
		$url['lang'] = 'en';
		if (isset($url['_entity'])) {

				$entity = $url['_entity'];
				preg_match_all('@:(\w+)@', $this->template, $matches);

				foreach($matches[1] as $field) {
						$url[$field] = $entity[$field];
				}
		}
		debug($url);
```
my entity ( ` $url['_entity']` )  does not any field named `'lang'` 
`debug($url); ` returns 
```php
//
'lang`=>null
//
```
so you can not use 
```php
Router::url([ 'lang' => 'en', '_name' => 'articles:view', '_entity' => $article]);
```

**Comment by saeideng** [comment]
I fixed this by a `if` in my app
```php
				foreach($matches[1] as $field) {
						if(!isset($url[$field])){
							$url[$field] = $entity[$field];
						}

				}
```

**Comment by saeideng** [comment]
but above solution is not true for general usage

**Comment by markstory** [comment]
I think only extracting fields that aren't already defined in the route array makes sense. It gives a way to explicitly override the entity data as well.

**Comment by lorenzo** [comment]
We would need to distinguish between stuff that was passed manually and fields that are present because of the `$this->defaults` property in the Route

**Comment by markstory** [comment]
@lorenzo Does the following precedence make sense:

* URL key
* Entity property
* Route defaults

**Comment by lorenzo** [comment]
It does
