### ISSUE TITLE
Cake 2.x AuthComponent does not return user information when basic auth headers are sent

### ISSUE THREAD

**Issue by db-bogdan** [cakephp/cakephp#11468]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.5
* Platform and Target: Windows, Apache, MySQL

### What you did
Trying to get the user information using basic auth in API environment.

### What happened
Because the method was set as "allowed", AuthComponent would not return the user information.
`$this->Auth->user()` returns `null`, even though basic auth headers are sent.

### What you expected to happen
I was expecting to be able to retrieve the user information regardless of whether or not the endpoint has authentication as mandatory.

-----
I have seen a similar issue reported here: https://github.com/cakephp/cakephp/issues/9070
But it does not seem like the pull request which resulted from it fixed this particular problem.

**Comment by markstory** [comment]
Looks like the changes made in #9072 were to fix the user missing during login, but not during other actions.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
