### ISSUE TITLE
Incorrect paths to template in plugins directory in error view

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11476]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: WAMP

### What you did
I prepare email template in my plugin in direcotry: `C:\...\public_html\project_name\plugins\Auth\src\Template\Email\html\forgot.ctp` and I used 
```
$email = new Email('default');
$email
        ->setTo($to)
        // ...
        ->setEmailFormat('html')
        ->setTemplate('forgot');
```

### What happened
The missing error show:

> Confirm you have created the file: "Email\html\forgot.ctp" in one of the following paths:
> 
> C:\...\public_html\project_name\src\Template\Plugin\Auth\Email\html\forgot.ctp
> C:\...\public_html\project_name/plugins/Auth/src\Template\Email\html\forgot.ctp
> C:\...\public_html\project_name\src\Template\Email\html\forgot.ctp

### What you expected to happen
Firstly, I was think it's problem with incorect slashes, but no:)

The problem is that I forgot add plugin name in template: `->setTemplate('Auth.forgot')`, that's work good.

And, why I open this issues? Because in missing error template the second path (`C:\...\public_html\project_name/plugins/Auth/src\Template\Email\html\forgot.ctp`) was good, but show error. 
I think, in my situation, when I forgot add 'Auth.` in template method, the missing template should just write this:

> Confirm you have created the file: "Email\html\forgot.ctp" in one of the following paths:
> 
> C:\...\public_html\project_name\src\Template\Email\html\forgot.ctp 

without path to plugins...

**Comment by markstory** [comment]
I'm guessing that you were sending the email from a plugin controller? The missing template error page currently draws its path list from the controller/view scope and not the rendered email message. We could update the MissingTemplate exception to include the actual paths searched though.

**Comment by kicaj** [comment]
Yes, I send email from plugin.

**Comment by markstory** [comment]
Ok. We could address this in 3.6 by expanding MissingTemplateException and other view template exceptions to track the paths they searched.
