### ISSUE TITLE
Fix path in cakephp-plugins.php

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11477]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: WAMP

### What you did
After composer install/update the `cakephp-plugins.php` was update.

### What happened
It's look like this:
```
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Auth' => $baseDir . '/plugins/Auth/',
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/'
    ]
];
```

### What you expected to happen
```
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Auth' => $baseDir . DIRECTORY_SEPARATOR . 'plugins' . DIRECTORY_SEPARATOR . 'Auth' . DIRECTORY_SEPARATOR,
        'Bake' => $baseDir . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'cakephp' . DIRECTORY_SEPARATOR . 'bake' . DIRECTORY_SEPARATOR,
        'DebugKit' => $baseDir . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'cakephp' . DIRECTORY_SEPARATOR . 'debug_kit' . DIRECTORY_SEPARATOR,
    ]
];
```

**Comment by ADmad** [comment]
Forward slash in file system paths work just fine on Windows too. The change you suggest will simply add string concatenation overhead with no benefit.

**Comment by dereuromark** [comment]
Indeed, re-classified as small enhancement.
It could only become interesting if you are reusing those paths, and comparing them etc.
But that sounds more like an edge case.

**Comment by markstory** [comment]
@kicaj Why do you think this change should be done?

**Comment by kicaj** [comment]
Beacuse essage below show incorect slashes for second path. 

> Confirm you have created the file: "Email\html\forgot.ctp" in one of the following paths:
> 
> C:...\public_html\project_name\src\Template\Plugin\Auth\Email\html\forgot.ctp
> C:...\public_html\project_name/plugins/Auth/src\Template\Email\html\forgot.ctp
> C:...\public_html\project_name\src\Template\Email\html\forgot.ctp

This can lead to search a bug for where it does not

**Comment by dereuromark** [comment]
You can open a PR to fix the visual aspect here. But as stated before it is merely that usually, no functional change.
Either way: A PR is welcome :) Issues of minor relevance often get outdated quickly, So directly having a merge request ready is easier to integrate.

**Comment by dereuromark** [comment]
ping @kicaj

**Comment by dereuromark** [comment]
Should this be moved to https://github.com/cakephp/plugin-installer/issues ?
