### ISSUE TITLE
3.3.16 - Modelless form validation not working as expected

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#11471]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.16
* Platform and Target: PHP 5.6, MySQL 5.6

### What you did
I'm trying to validate data without a table but the validation rules aren't working the same way vs when a table is being validated.

Controller:
```
$data = [
    'description' => ''
];
$requestForm = new RequestForm();
$requestForm->execute($data);
pr($requestForm->errors());
```

RequestForm:
```
protected function _buildSchema(Schema $schema)
{
    $schema
        ->addFields([
            'description' => ['type' => 'text']
        ]);
    return $schema;
}
protected function _buildValidator(Validator $validator)
{
    $validator
        ->requirePresence('description', function () {
            return false;
        }, "Description is required");
    return $validator;
}
```

### What happened
I get this error printed out:
```
Array
(
    [description] => Array
        (
            [_empty] => This field cannot be left empty
        )

)
```

### What you expected to happen
That callable is never called so the logic inside doesn't matter (it should). In my example there shouldn't be any error since the callable for `requirePresence` on the `description` field returns `false`. Also, the message shouldn't be "This field cannot be left empty" it should be "Description is required". I'm not sure if this happens in 3.4 or 3.5. I'm somewhat positive this worked at some point in the past. I don't see any tests that check if `requirePresence` can accept callables, but it's in the docs.

Thanks.

**Comment by ravage84** [comment]
Refers:
https://api.cakephp.org/3.3/class-Cake.Validation.Validator.html#_requirePresence
https://api.cakephp.org/3.5/class-Cake.Validation.Validator.html#_requirePresence

**Comment by robertpustulka** [comment]
In your example you require **data key** presence, but you pass the empty string and get the `_empty` validation error (not the `_required`). Are you sure you have your validator configured correctly? Note the difference between `requirePresence` and `notEmpty`. The former will require that the *key* is present in data array (the value can be empty) the latter will require that the _value_ is not empty (is not `''` or `null`).

In any case, callable fore `requirePresence` should be supported: https://github.com/cakephp/cakephp/blob/master/src/Validation/Validator.php#L1802-L1804

**Comment by patrickconroy** [comment]
Hi @robertpustulka . The only rule I have in my validation flow is `requirePresence`, which is always happening with an empty value despite there being a callable returning false. I don't have a `notBlank` or a `notEmpty`, my full code is above. I know what you're saying and if I put anything into my `description` above I don't get any errors. I think that would make it seem like `requirePresence` is a little messed up? I'm 100% sure my callable isn't getting called.

**Comment by patrickconroy** [comment]
I think this comes down to that you can't first do `requirePresence` without calling `allowEmpty`. They *should* be separate, but `Validator::errors` calls `Validator::_canBeEmpty` which defaults to false in `ValidationSet::_allowEmpty`. So the second you try to validate any field's presence it also automatically tries to see if it's empty, when I don't think it should. I can't think of a core workaround though.

**Comment by markstory** [comment]
Not really sure what the ask is here. You're getting the 'intended' behavior is, but its not what you were expecting.

**Comment by patrickconroy** [comment]
Hm, why would the intended behavior of checking the presence of a field also immediately check if it's empty? How would you validate *just* the existence of something?

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/8925

**Comment by markstory** [comment]
@patrickconroy I was trying to say that the intended default behavior is to disallow empty values.

> How would you validate just the existence of something?

You'd have to do `requirePresence()` and `allowEmpty(true)` for the field.

**Comment by patrickconroy** [comment]
I think it's just jarring to me that if you have 0 rules applied it won't check emptiness, but if you have at least 1 rule unrelated to emptiness it checks emptiness.

**Comment by markstory** [comment]
Model validation works the same way, or at least that is how I remember it working. Non-empty value rule is applied by default to any field with rules, and requiring a field to be present adds a validation rule. We assumed that if you were validating a field you would want to do more that just make sure it was there which is why allowEmpty is off by default.

**Comment by ADmad** [comment]
The defaults seems reasonable to me as @markstory explained. I don't think anything needs to be changed here.

**Comment by dereuromark** [comment]
Closing then as stale and nothing to be done.
