### ISSUE TITLE
support the parsing date from non-Gregorian calendar 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11486]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

You know cake not support parse date from non-Gregorian calendar 

we can add this feature into cakephp/i18n or probably cakephp/chronos 

sample of code
```php
    $fmt = new \IntlDateFormatter(
    'en_US@calendar=persian',
    \IntlDateFormatter::NONE , //date format
    \IntlDateFormatter::NONE, //time format
    'Asia/Tehran',
    \IntlDateFormatter::TRADITIONAL,
    'yyyy-MM-dd'//pattern
);
$timeStamp = $fmt->parse('1396-09-09');
debug($timeStamp);
$time = Time::createFromTimestamp($timeStamp);
debug($time);
```
we just need date 
cake supports timezones
so I think is good add support parsing date into chronos

**Comment by markstory** [comment]
I am :+1: on supporting non Gregorian calendars. How would you indicate which calendar is being used to the various parse methods?

**Comment by saeideng** [comment]
like the `i18nFormat`
```php
Cake\I18n\Time::i18nFormat($format = null, $timezone = null, $locale = null);

Cake\I18n\Time::parse('2014-10-31', $timezone = null, $locale = null);
```
I'm not sure we need to save name of calendars Or no 
 like `setTimezone`
```php
$date->setTimezone(new \DateTimeZone('America/New_York'));
```

one of thing is  important  now is  converting non Gregorian into timestamp , after that we able to use 
`i18nFormat`

**Comment by saeideng** [comment]
I thinks is good to support the basic parsing in chronos

**Comment by markstory** [comment]
> I thinks is good to support the basic parsing in chronos and porting some of code into chronos.

Wouldn't this add `ext/intl` as a dependency to chronos? That is something we might want to avoid as based on our experience with cakephp/cakephp people have a hard time getting intl installed.

**Comment by dereuromark** [comment]
You could make a calendar library that uses chronos as dependency.

**Comment by saeideng** [comment]
@markstory
Good point
You are right 
Si,we can add a class into cakephp/i18n

**Comment by saeideng** [comment]
@dereuromark 
Cakephp/calendar?

**Comment by dereuromark** [comment]
You can also start in your namespace, if it becomes stable it can still be transferred.
