### ISSUE TITLE
Unable to send email with DKIM signature

### ISSUE THREAD

**Issue by LifeOrYou** [cakephp/cakephp#11485]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Cakephp version : 3.4.13

### What you did
I want to send a email with DKIM signature but my email client can't verify this signature (body hash did not verify).

### What you expected to happen
For solve it, i must force the content-transfer-encoding to `quoted-printable` not `8bit` or `7bit`.
But i must override cakephp source code for set content-transfer-encoding to `quoted-printable`.
```
protected function _getContentTransferEncoding()
    {
        return 'quoted-printable';
        // Cakephp source code
        $charset = strtoupper($this->charset);
        if (in_array($charset, $this->_charset8bit)) {
            return '8bit';
        }

        return '7bit';
    }
```

How i can set the transfer encoding whitout override cakephp source code ?

**Comment by markstory** [comment]
> How i can set the transfer encoding whitout override cakephp source code ?

You'd have to extend the Email interface to expose methods to allow the transfer encoding to be changed.

**Comment by markstory** [comment]
Related to #10789

**Comment by markstory** [comment]
In #10789 there was a suggestion of adding a `setEncoding()` method. No one followed that up with a pull request. If you need this feature @LifeOrYou a pull request would be merged for that kind of thing.

**Comment by markstory** [comment]
Closing as #11488 was merged.
