### ISSUE TITLE
login session not store

### ISSUE THREAD

**Issue by maungyehtunzaw** [cakephp/cakephp#11489]
My Login function was pass in indentify function and debug statement are out. but login session can not get. it is always saying errors. .**You are not authorized to access that location.**
```
public function login()
    {
    if($this->request->session()->read('Auth.M')) {
      return  $this->redirect(['action'=>'profile']);
    }

    if ($this->request->is('post')) {
        if (Validation::email($this->request->data['username'])) { 
      //whole if statement for useraname or email login check
                $this->Auth->config('authenticate', [
                    'Form' => [
                        'fields' => ['username' => 'email']
                    ]
                ]);
                $this->Auth->constructAuthenticate();
                $this->request->data['email'] = $this->request->data['username'];
                unset($this->request->data['username']);
            }
     $user = $this->Auth->identify();
        if ($user) {
          $this->Auth->setUser($user);
          debug($user);
          debug($this->request->session()->read('Auth.M.username'));die;  
          return $this->redirect($this->Auth->redirectUrl());
         }
         $this->Flash->error(__('Invalid username or password, try again'));
        }
    }
```

when i check pass or not if($users) statement. this debug show me correct information.when i was remove these these debug statement and login.. but it always show .**You are not authorized to access that location.**
          debug($user);
          debug($this->request->session()->read('Auth.username'));die;  

debug result----------
```
 \src\Controller\MembersController.php (line 296)

[
	'memberId' => (int) 1,
	'name' => 'Ye Htun',
	'username' => 'yeyeye',
	'email' => 'yeyeye@gmail.com',
	'nickname' => 'JetBee',
	'image' => 'poemhive_profile_1510334362fac.png',
	'short_bio' => 'September26 You don't know the last word. so reply maungyehtunzaw.github.io',
	'status' => (int) 1,
	'is_deleted' => false,
	'created' => object(Cake\I18n\FrozenTime) {

		'time' => '2017-08-19T10:01:29+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'modified' => object(Cake\I18n\FrozenTime) {

		'time' => '2017-11-25T16:23:11+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	}
]

\src\Controller\MembersController.php (line 297)

'yeyeye'
```

---------------------------------------------------------------------------

**Comment by saeideng** [comment]
check session cookie in response (web  browser )

**Comment by maungyehtunzaw** [comment]
![image](https://user-images.githubusercontent.com/5591177/33511027-859d0fca-d742-11e7-85a6-0aa938669ed5.png)

Login in with Facebook and Google worked but normal login can't get. I'm not understand what happen to my code.. these code are worked find earlier days. I have been checked a lot for this errors. 
Please

**Comment by maungyehtunzaw** [comment]
It is worked on hosting www.poemhive.com. but not worked on localhost

**Comment by markstory** [comment]
It sounds like you have an environment related issue then. I think you should start comparing your two environments and figuring out what the differences are and try go make the environments consistent. Given that its an environment related issue it is not a problem with cakephp.
