### ISSUE TITLE
setDefault value before marshalling  

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11499]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

hi
you know there are some issue with saving `''` instead of `null` into DB
see bellow Refs  for more info 
 i handle this by `beforeMarshal`
```php
public function beforeMarshal($event,$data,$options){
  if(empty($data['parent_id'])){
     $data['parent_id']=null;
 }
```
but I have another suggest 

```php
//  model/table/exampleTable.php
    public function beforeMarshalDefault($data)
    {
          $data
            ->setDefault('fieldName',[array of values that must convert ],target value);
            
          $data
            ->setDefault('parent_id',['',0,'0'],null);

         $data
              ->setNull('parent_id',null); 

          return $data
    }
```
or
```php
public function beforeMarshal($event,$data,$options,$marshaller)
	{
    $marshaller
      ->setDefault($data,'fieldName',[array of values that must convert ],target value);
      
    $marshaller
      ->setDefault($data,'parent_id',['',0,'0'],null);
    $marshaller
      ->setNull($data,'parent_id',null);    

      //other codes 
      if(empty($data['otherField'])){
            $data['otherField']=null;
      }

 }
```

other related issues 
#9678 , #10340

**Comment by markstory** [comment]
Setting defaults is a neat idea. How do the defaults prevent the marshaller from overwriting the null with `''` from the request data?

**Comment by ADmad** [comment]
> public function beforeMarshal($event,$data,$options){
  if(empty($data['parent_id'])){
     $data['parent_id']=null;
 }

This is unnecessary. The [integer type class](https://github.com/cakephp/cakephp/blob/master/src/Database/Type/IntegerType.php#L62) already handles converting empty string to null.

Also something like `->setNull('parent_id',null);` seems redundant to me. The db will set required default value if no value is set in the entity.

**Comment by saeideng** [comment]
1)`Parent_id` in above is just a sample
And can be give type as string,int,bool,time,..
2)we say about exist values in request array/data

**Comment by ADmad** [comment]
To me your proposal looks like moving the functionality of db type classes onto the marshaller.

**Comment by saeideng** [comment]
>How do the defaults prevent the marshaller from overwriting the null with '' from the request data?

for example for 
```php
$data
       ->setDefault('parent_id',['',0,'0'],null);
```
```php
function setDefault($field, $array ,$default){
    if(!isset($this->data[$field])) {
         return ;// <-- here
    }
    if($this->data[$field] == $default) {
         return ;// <-- here
    }
  foreach ($array as $item){
           if($this->data[$field]==$item){
                  $this->data[$field]=$default;
                  return;
            }
   }

}
```
`$this->data` is all data passed to `patchEntity()`/`newEntity()`
these methods try to set default just if `isset($this->data[$field])`

**Comment by saeideng** [comment]
we just need a good place for these methods + bake too for generating these :) 

setDefault();
setNull();
removeFieldIf();
convertIntoInt();
...

**Comment by saeideng** [comment]
>To me your proposal looks like moving the functionality of db type classes onto the marshaller.

I think `db type` applied after validation , but these methods applied marshal time

**Comment by inoas** [comment]
Long Short: I am not sure about the syntax but I like the general approach. **Before validation kicks in we need to have a way to define data types and default values. This will become really handy with PHP 7/7.1/7.2.**

* * *

Personally I transform request data for some requests into typed data for /some/ routes and do not do so for other routes:

```php
<?php declare(strict_types=1);
namespace App\Transformer;

use Psr\Http\Message\ServerRequestInterface;

/**
 * Trims, detect and transforms scalar and list data types in request-body and query-strings
 */
final class DetectRequestDataTypesTransformer
{
    /**
     * @param \Psr\Http\Message\ServerRequestInterface $request The request.
     * @return \Psr\Http\Message\ServerRequestInterface The request.
     */
    public function transform(ServerRequestInterface $request) : ServerRequestInterface
    {
        $queryParams = $this->process($request->getQueryParams());
        $request = $request->withQueryParams($queryParams);

        $postParams = $this->process($request->getData());
        foreach ($postParams as $key => $value) {
            $request = $request->withData($key, $value);
        }

        return $request;
    }

    private function process(array $params) : array
    {
        array_walk_recursive($params, function(&$value, $key) {
            $value = trim((string)$value);
            if (count(explode(',', $value, 50)) > 1) {
                $value = (function() use ($value) {
                    foreach (explode(',', $value) as $i => $value) {
                        $value = trim((string)$value);
                        if ($value === 'true') {
                            $value = true;
                        } elseif ($value === 'false') {
                            $value = false;
                        } elseif ($value === '') {
                            $value = null;
                        } elseif ($value === (string)(int)$value) {
                            $value = (int)$value;
                        }
                        $values[$i] = $value;
                    }
                    return $values;
                })();
            } elseif ($value === 'true') {
                $value = true;
            } elseif ($value === 'false') {
                $value = false;
            } elseif ($value === '') {
                $value = null;
            } elseif ($value === (string)(int)$value) {
                $value = (int)$value;
            }
        });

        return $params;
    }
}
```

Our intermediate layers are increasingly not using SQL as a backend (though we still use a lot of SQL and love the ORM <3), and if we do not do so how are we supposed to use those "application rules" and db-field type introspection?

Now the problem is that this code like above adds a ton of conventions and assumptions to how request bodies and request query-strings are expected to be structured.

Much better would be a request transformer that is sensitive towards what fields there can be in the request body (mostly POST) or query string (mostly GET) and how to transform those fields. In strict mode one could even throw exceptions when fields are submitted that are not to be expected.

What I do interim is setting up json schemas: http://json-schema.org/examples.html and pushing request data through it after json_encoding it.
I did also consider peeking into GraphQL but deemed it too much.

**Comment by dereuromark** [comment]
Indeed, normalizing at this point would probably solve the other tickets and Cake not handling nullable properly either. So if there was a good way on marshalling to do this normalizing, it probably would be a benefit for the data integrity of most apps without having to use some shim behaviors.

**Comment by saeideng** [comment]
another good place/syntax 
```php
public function beforeMarshal($event,$data,$options)
{
      beforMarshaller::for($data,'fieldName')
                   ->removeFieldIf(....);
                   ->setNull();
      beforMarshaller::for($data,'otherFieldName')
                   ->removeFieldIf(....)
                   ->setNull()
                   ->convertIntoInt()
                    ->trim();

      //other codes 
      if(empty($data['otherField'])){
            $data['otherField']=null;
      }

 }
```

**Comment by markstory** [comment]
Do folks generally want to cast/ convert data in the same way for a given table/entity? It sounds like having the casting handle by the db types isn't as flexible as you need.

The proposed methods point towards a casting/translation API that is defined at the table level. How do you see this working when the casting operations fail? For example a user sends 'boats' into an integer field? A naive casting would create 0 and possibly not trigger validation to fail. How do you see these new features intersecting with validation?

**Comment by inoas** [comment]
when validating data/query structures and values are "faulty", top of my head:
- take defaults
- remove variables from structure (underlaying layers can then complain about the inconsistency of the structure)
- report errors to the user
- crash via exceptions
... which makes me wonder if it should validate structural things as well (field a and b must be given, a must eval to integer without loss, b must eval to readable-utf-8 string without loss, etc).

**Comment by markstory** [comment]
If people need something like JsonSchema or GraphQL couldn't they use that *before* marshalling?

**Comment by saeideng** [comment]
>Do folks generally want to cast/ convert data in the same way for a given table/entity? It sounds like having the casting handle by the db types isn't as flexible as you need.
The proposed methods point towards a casting/translation API that is defined at the table level. How do you see this working when the casting operations fail? For example a user sends 'boats' into an integer field? A naive casting would create 0 and possibly not trigger validation to fail. How do you see these new features intersecting with validation?

@markstory 
you are right 
`convertIntoInt()` is stupid method 
but we have still 
```php
                   ->setDefault();
                   ->removeFieldIf(....)
                   ->setNull()
                    ->trim();//or  clear()
```

these methods are just for small normalize (for example converting `''` into `null` )
and not throw any error
no any validation 
no any complex converting

I don't want to hijack db-type/validation/marshaller  duty

**Comment by inoas** [comment]
@markstory if we have complex data structures that need type and integrity checks wouldn't the framework and apps build on-top benefit greatly if there were sane tools/integration to do so? This would be something usable for $options as well as for request data/query that would stop a lot of runtime errors?

**Comment by davidyell** [comment]
I like this, I really like this. 

My only concern is that I want it to be obvious that this translation is happening. The similar thing which springs to mind is entities not writing data, because people don't realise that `$_accessible` is set. I guess the user will be writing this code though, so that could be down to the coder.

**Comment by burzum** [comment]
Can't anyone who wants this kind of functionality just use a request transformer as @ionas is already doing or create a behavior and listen on the `Model.beforeMarshal` event and implement the "validation" logic in the behavior?

**Comment by othercorey** [comment]
@saeideng do you have a PR for this?

**Comment by saeideng** [comment]
nope yet
