### ISSUE TITLE
field declared dynamically on first() object in PHPStorm

### ISSUE THREAD

**Issue by anuj9196** [cakephp/cakephp#11500]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5
* Platform and Target: Apache, MySQL
* Tool/IDE: PhpStorm

### What you did
Accessing entity object using `first()` in query shows a Note stating 
```
Field declared dynamically
Referenced field is not found in subject class
```
![image](https://user-images.githubusercontent.com/6560085/33539071-8238e670-d8ea-11e7-9bd7-767fe910901c.png)

### What you expected to happen
Entity fields should show as in `get()` or `newEntity()`

**Comment by markstory** [comment]
It looks like you're missing an annotation for `$getLogin`.

**Comment by dereuromark** [comment]
You cannot easily typehint the ORM methods the way you want it and the way it would be nice to have.
If you find a way please help us to improve the [IdeHelper](https://github.com/dereuromark/cakephp-ide-helper) which can teach PHPStorm a few things here.

For now I recommend always putting each method into the model layer as its own method and typehint there as annotation of the method:
```php
/**
 * @param int $id
 * @return \App\Model\Entity\User
 */
public function getUserById($id) {
    ...
    return $query->firstOrFail();
}
```
So if anywhere else you re-use it, you got it typehinted for free:
```php
$user = $this->getUserById();
$prop = $user->prop;
```

**Comment by markstory** [comment]
Closing as there isn't much the framework can do here. We already hint to the interfaces we could hint against.
