### ISSUE TITLE
Add $_validatorClass to Cake\Form\Form

### ISSUE THREAD

**Issue by andruhapx** [cakephp/cakephp#11501]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5

Is it possible to add new field "protected $_validatorClass = '\Cake\Validation\Validator';" to Cake\Form\Form?
Because now Form does not use ValidatorAwareTrait, and validator class is hardcoded:
$validator = $this->_buildValidator(new Validator());

**Comment by dereuromark** [comment]
You can make a PR here to request your enhancement. Sounds like a good idea.

**Comment by ADmad** [comment]
Closing as related PR #11505 is open.
