### ISSUE TITLE
dd(Type::buildAll()) timeout error

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11507]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest master

### What you did
Debugging type building (static methods of Type class):
```php
dd(Type::build('sth'))
dd(Type::buildAll())
```

### What happened
Runtime timeout after many minutes of nothing happening (probably some inception issue).

### What you expected to happen
Output normal dd() debug output

**Comment by markstory** [comment]
Does your recent change to limit the output from Type instances help with this at all?

**Comment by dereuromark** [comment]
No, those were unrelated. I could not figure out how to solve the static inception issue yet.

**Comment by saeideng** [comment]
confirm with 
```php
//Cake\Database\Type
    public function __debugInfo(){
      return [
        'name' => $this->_name,
        'build'=>static::$_builtTypes
      ];
    }
```

https://github.com/cakephp/cakephp/pull/11491 can be solved this problem 
I tested `dd(\Cake\Database\Type::build('stm'));` in local  with adding `__debugInfo` into `Cake\Database\Type`
```php
//Cake\Database\Type
    public function __debugInfo(){
      return [
        'name' => $this->_name,
      ];
    }
```
is OK :+1:

**Comment by dereuromark** [comment]
I didnt check after I modified the PR to only include name.
So if that's the case, I can happily close, thank you!
