### ISSUE TITLE
Set RequestHandlerComponent::viewClassMap to [] by default

### ISSUE THREAD

**Issue by andruhapx** [cakephp/cakephp#11506]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5

Is it possible set viewClassMap to [] by default?
I just enabled RequestHandlerComponent to use isMobile method (explained in the 1st part of documentation)
and this unexpectly enabled JsonView  (explained at the bottom of documentation). 

As result all view variables passed to views became public accessible
via sending Accept:application/json header.
Seems to be very unsafe behavior.

**Comment by dereuromark** [comment]
I would also be for more opt-in rather than default.
But bear in mind that it does not enable itself without also Router::extensions to be set to those extensions.

**Comment by andruhapx** [comment]
In RequestHandlerComponent::_setExtension it uses both  Router::extensions and RequestHandlerComponent viewClassMap:

```
$extensions = array_unique(
       array_merge(Router::extensions(), array_keys($this->getConfig('viewClassMap')))
 );
```

**Comment by dereuromark** [comment]
Maybe we can talk about 3.6 here, for a bugfix release in 3.5 this might be a bit too intrusive.
But I can see the security relevance here, so with some migration guide note this could go into 3.6.
Are you able to provide a PR here?

**Comment by andruhapx** [comment]
I didnt reach PR sending level yet. 
Can work only with svn, not with git. Dont know how to do tests etc and have no time learn this now.
Will try to improve my capabilities next year ;)

**Comment by ADmad** [comment]
`RequestHandler`'s main job is to handle auto switching view class and setting response type based on extension or "Accept" header. So if you don't want that feature just don't load the component.

For check like `isMobile()` you don't even need the component, can just use request object: `$this->request->is('mobile')`.

So perhaps this is just a documentation issue.

**Comment by dereuromark** [comment]
https://github.com/cakephp/app/blob/039df43070c100b547239ea78ca22d77b43d265f/src/Controller/AppController.php#L44
It is enabled by default though.

**Comment by ADmad** [comment]
It's enabled by default because most people would prefer the auto switching behavior. If someone like @andruhapx don't like that behavior they can remove it :slightly_smiling_face:.

**Comment by andruhapx** [comment]
I agree with autoheaders, autolayout switching. But autosending view vars for all actions without special instructions (including entities, or some configs) - not sure. 

Specially because many people not understand how and why this happens

**Comment by markstory** [comment]
> Maybe we can talk about 3.6 here, for a bugfix release in 3.5 this might be a bit too intrusive.

We'd have to likely push out removing default types to 4.0. I'm ok with defaulting to an empty list in that release though.

**Comment by ADmad** [comment]
> But autosending view vars for all actions without special instructions (including entities, or some configs) - not sure.

That is most likely because of [this](https://github.com/cakephp/app/blob/master/src/Controller/AppController.php#L66) code. We can remove that in next minor release of app skeleton.

@markstory I hope we don't change RequestHandler defaults :) The issue is about auto serializing of all view vars, not auto switching of view class.

**Comment by markstory** [comment]
Oh. Well then, the application skeleton change you have up would take care of this problem.

**Comment by dereuromark** [comment]
Will be closed with https://github.com/cakephp/app/pull/569
