### ISSUE TITLE
multiple paginator problem

### ISSUE THREAD

**Issue by mohammadsaleh** [cakephp/cakephp#11515]
This line 
https://github.com/cakephp/cakephp/commit/ed233e7167f2b693c90fa30fbba0d1ba58d3ec6d#diff-9331fd78b8c7f46ba39642f792749d81L471
should be changed to support params which we would to set it to false, like 'prefix' => false

**Comment by markstory** [comment]
Any chance you'd be willing to send a pull request with the changes you think should be done? It would also be helpful to understand the use case the current code is breaking so we can add a regression test.

**Comment by mohammadsaleh** [comment]
I'm not familiar with git and pull request to cakephp, but ok I will try to do that ...

**Comment by markstory** [comment]
Pull request open now.
