### ISSUE TITLE
RFC: Fewer traits more classes and interfaces for 4.0

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#11511]
I came across this article http://rosstuck.com/how-i-use-traits and I really like it, I agree with the argumentation and think what it suggest could improve the framework code wise and make it easier to change than using traits for the user of it if needed.

We have 43 traits in the framework (master branch / 3.5) at the time of writing this. 😮 If you search through the src folder by this regex you'll find them all `^((?!use))Trait` using the regex search in phpstorm.

I've checked them all briefly and compiled this list with my thoughts about them:

* ExtractTrait: Should be a separate class + interface
* CollectionTrait: Why is this not a base class / abstract?
* ConventionsTrait: Its like a proxy to the static inflector... Can't we use a class that wraps it instead + interface?
* InstanceConfigTrait: Should be a config object, see https://github.com/burzum/cakephp-config-objects
* StaticConfigTrait: Not 100% sure but could be an class as well, the trait feels wrong
* FileConfigTrait: Should be an object + interface
* SqlDialectTrait: Class + interface?
* TypeConverterTrait: Unsure, but could be a class + interface as well and not a trait
* TypedResultTrait: Unsure
* TypeMapTrait: Class + interface?
* \Cake\Database\Dialect\*Trait: Should be all classes implementing an interface
* TupleComparisonTranslatorTrait: Not sure, just a single method, could be a class
* PDODriverTrait: Should be an class? I don't see a reason for this to be a trait?
* FieldTrait: Seems to be OK for me
* BufferResultsTrait: Seems to be OK, but implement classes that use it an inteface that requires this method?
* ExpressionTypeCasterTrait: Should be an class + interface
* EntityTrait: I'm not sure why we picked a trait over an abstract class here?
* ModelAwareTrait: Might be OK as trait
* QueryTrait: I'm not sure why we picked a trait over an abstract class here?
* RulesAwareTrait: I'm not sure why we picked a trait over an abstract class here?
* EventDispatcherTrait: Might be OK as trait
* EventManagerTrait: Deprecated at time of writing, use above trait instead
* DateFormatTrait: Abstract class or object + interface?
* LogTrait: Seems to be OK
* MailerAwareTrait: Seems to be OK
* AssociationsNormalizerTrait: Should be a class + interface
* DependentDeleteTrait: Deprecated at time of writing
* TranslateTrait: Not sure, but feels wrong that this is a trait
* LocatorAwareTrait: Seems to be OK
* RequestActionTrait: Deprecated at time of writing
* EmailAssertTrait: OK
* StringCompareTrait: OK
* CookieCryptTrait: Class + interface?
* MergeVariablesTrait: Seems to be OK
* ValidatorAwareTrait: Seems to be OK, yet another locator
* CellTrait: Not sure about this one
* StringTemplateTrait: Seems to be OK
* ViewVarsTrait: Not sure, feels not right
* IdGeneratorTrait: Class + interface
* SecureFieldTokenTrait: Seems to be OK

It feels for me like we use traits due to the lack of multiple inheritance in php. However, if you have strong need for multiple inheritance, it's more likely a signal your architecture isn't that great and not the direction that should be taken even if it would be possible.

So it would be better to inject objects. But CakePHP relies a lot on service locators, some of them are basically locators. Cake doesn't use any DI container or another concept yet that would allow us to inject the logic as object, guess this is the reason we use traits a lot, for example the IdGeneratorTrait, which is used 5 times. Without a trait and without another concept for DI, it would be hard to inject it as object while maintaining the flexibility to pass another implementation of the (yet to be done) IdGneratorInterface into the class.

Comments please! 😃

**Comment by chinpei215** [comment]
Though it is not written in the above site you linked, trait breaks encapsulation. Unlikely composition, trait touches class properties directly. So strictly speaking, when we write test cases, we have to test any methods from traits for each classes. There is no guarantee of that those methods can be called via the classes. 

Additionally, it could be a security hole in CakePHP. For example, MailerAwareTrait contained a vulnerability in the past. We designed it to use in controllers. However it had a public method, getMailer(), and it become actions when people used it in their controller. It ended up to allow malicious users to instantiate any arbitrary classes. Though I changed the accessibility to protected in 3.4, if someone adds public methods to the trait accidentally, the vulnerability will be back again.

I would suggest to discuss why those MUST be a trait here. Unless we want to override some methods from parent classes, I think we need not to use traits.

**Comment by markstory** [comment]
A few of the traits are used in the elastic search plugin, notably the EntityTrait, ValidatorAwareTrait, QueryTrait and RulesAwareTrait.

Other traits like InstanceConfigTrait, MergeVarsTrait and ViewVarsTrait were intended to help provide consistent method sets across the framework without introducing deep inheritance chains, duplication or kitchen sink base classes like Object from 2.x. I admit we may have gone too far into using traits.

If there are traits that only have a single user we should inline those traits into the implementing class. As you mentioned extracting traits into objects that are used instead of the trait is a strategy we have used to deprecate/remove traits in the past.

**Comment by inoas** [comment]
What worries me most is BC during 3.x/4.x lifetime.

If we remove a trait from one class shouldn't it be removed from all classes and the file should also be gone entirely? So that you see errors in your application very fast and not suddenly during run-time.

TBH while I acknowledge your spirit to do the right thing I'd very much prefer if we had an ASAP focus on non-destructive changes such as first class PHP 7.2 support, php strict mode, extensive type hints, a structural validator with defaults and typecasting for $options and request-data/query etc. during 3.x/4.x life-cycle, etc.

If traits have to go in the mid/long run, what about creating new classes all-together for the same feature set that do not use those traits and live in the core for some time side by side (think Set:: vs Hash::)?

**Comment by ADmad** [comment]
> PDODriverTrait: Should be an class? I don't see a reason for this to be a trait?

This is taken care of by #11713. The methods are moved to `Driver` class itself and the trait is deprecated. `DriverInterface` has been added.

**Comment by dereuromark** [comment]
On a related note:
```
class Component implements EventListenerInterface
```
shouldnt classes like Component be abstract then? Since they dont have a proper ComponentInterface and can directly be used (by accident?) even though they should always be extended somewhere.

**Comment by dereuromark** [comment]
StringTemplate should definitely have an interface here so if passed around you dont have to typehint against a concrete one:

    public function __construct(StringTemplate $templates, SelectBoxWidget $selectBox)

This is a antipattern, both times the interface should be the one used. Especially for the first one at least.

**Comment by robertpustulka** [comment]
@dereuromark Behaviors and Helpers don’t need to listen for events. This is optional.

**Comment by dereuromark** [comment]
Yes, I am not talking about event listening, but clean code in general (as this ticket does).
Typehinting against interfaces instead of concrete classes (or nothing).

**Comment by markstory** [comment]
I'm not sure I agree that individual form helper widgets should have interfaces. I would rather remove the type hints than add interfaces for each widget type.

**Comment by dereuromark** [comment]
Of course they need proper public API to make sense. Just outlining other clean code issues.

**Comment by ADmad** [comment]
`EntityInterface::setError()` has been added in `4.x` so it shouldn't be an issue anymore.

**Comment by dereuromark** [comment]
Closing then as the general consensus has been accepted and will be taken into account for future changes and additions.
