### ISSUE TITLE
4.0: Use same syntax for 18n and Cake sprintf functionality

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11524]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

See https://github.com/cakephp/localized/pull/181#pullrequestreview-80384815

It is currently very annoying when working with translations that you cannot be sure if those are %s or {...}.
They would also currently have to be duplicated and translated twice.

### Option A
Use old sprintf() %s syntax again also for __() by default. With a bit of configuration that should be easily doable.

### Option B
Invent a Cake/I18n sprintf() that can work on the same {0...n} syntax as i18n __() can to consolidate this and make translating easier and more DRY.
Maybe a method `I18n::insert()` or sth could do the trick and can then be used in such cases instead of vanilla PHP.

Since the numbering has the advantage of re-ordering (which is probably necessary in same languages), I guess we would have to go with B.

**Comment by markstory** [comment]
I would prefer us to use the `{0}` style placeholders, as the ICU format gives far more options when plural messages are involved.

**Comment by ADmad** [comment]
I agree with @markstory, it would be unwise to limit usability but not using the ICU format for translation messages.

**Comment by lorenzo** [comment]
I also agree with @markatory

**Comment by dereuromark** [comment]
PR is open.
