### ISSUE TITLE
Make it easier to override timestamp generation when using UrlHelper::assetUrl()

### ISSUE THREAD

**Issue by JoshuaLuckers** [cakephp/cakephp#11520]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6

### Enhancement details
I've set Asset.timestamp to "force" in app.php. When using UrlHelper to generate a URLs for asset files it adds a timestamp like it's intended to do. In certain situations I don't want to add a timestamp to the generated URL.

### What you did
When generating a URL for an asset file the method assetTimestamp is called. It checks the 'Asset.timestamp' configuration value to check if a timestamp should be added. 
When I don't want a timestamp for a certain asset URL I now do this:

```php
$orginalAssetTimestampConfiguration = Configure::read('Asset.timestamp');
Configure::write('Asset.timestamp',false);

$assetUrl = $this->Url->assetUrl('asset.ext');

Configure::write('Asset.timestamp',$orginalAssetTimestampConfiguration);
```

### Enhancement suggestion
Consider adding a parameter to the assetUrl function so we can overrule the 'Asset.timestamp' value set in the configuration file.

**Comment by ADmad** [comment]
You can make a PR to add `assetTimestamp` config to `$options` argument and if set to `false` skip calling `assetTimestamp()` method.

**Comment by JoshuaLuckers** [comment]
Ok! When I have some time this weekend I will create a pull request.
