### ISSUE TITLE
4.0: Use Null Coalesce Operator

### ISSUE THREAD

**Issue by carusogabriel** [cakephp/cakephp#11525]
This is a:

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.

Should we use the new `PHP 7` [Null Coalesce Operator (`??`)](https://secure.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce) in version `4.0`? If so, in what branch should I commit it?

**Comment by markstory** [comment]
> Should we use the new PHP 7 Null Coalesce Operator (??) in version 4.0

Yes we should use it.

> If so, in what branch should I commit it?

The development for 4.0 hasn't started yet as we're still aiming to get 3.6 complete. Once 3.6 hits an RC release, I'll make the `4.x` development branch.

**Comment by dereuromark** [comment]
Closing then as there no further need here for discussion.
