### ISSUE TITLE
ORM Query builder have support subquery same table.

### ISSUE THREAD

**Issue by trunganh07** [cakephp/cakephp#11538]
Dear all,

We have small issue under Cake\ORM\Query, how to execute 2 or 3 same table in once QueryBuilder.

Original query:

`SELECT 
  Tags.id AS "Tags__id", 
  Tags.value AS "Tags__value",
  ( SELECT count(pt.paper_id) FROM paper_tags as pt WHERE pt.tag_id IN(Tags.id) OR pt.tag_id IN (SELECT id FROM tags t WHERE t.parent_id = Tags.id)) as totalTags 
FROM 
  tags tags  
WHERE 
  (Tags.parent_id) IS NULL AND ( SELECT count(pt.paper_id) FROM paper_tags as pt WHERE pt.tag_id IN(Tags.id) OR pt.tag_id IN (SELECT id FROM tags t WHERE t.parent_id = Tags.id)) > 0
  ORDER BY Tags.order_NO asc`

We changed alias table Tags is tags,t,ect..., after all alias replace only one "tags" or "t"

Thanks,

**Comment by inoas** [comment]
This is not a support system. Take a look at ->from() and join IRC or Slack.

**Comment by markstory** [comment]
This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:
 
* [The CakePHP Manual](http://book.cakephp.org)
* [The CakePHP online API](http://api.cakephp.org)
* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than happy to help answer your questions.
 
Thanks!
