### ISSUE TITLE
changing timezone 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11537]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* cakephp/chronos or cakephp/i18n

hi
you know there is not a built-in method for  changing  timezone , without changing time
`2:50` in `UTC` => `2:50` in other timezone

current ways 
```php
1)
$newTime = new \Cake\I18n\Time($utcTime->format('Y-m-d H:i:s'), 'new timezone');
2)
$newTime = \DateTime('now', 'new timezone'); 
$newTime->setTimestamp($otherTime->format('U'));

//thanks @admad
```

suggest name 
```php
asTimezone();
```

how to use: 
```php
//when default timezone = UTC
1)
Time::parseDateTime('10/13/2013 12:54am')->asTimezone('new timezone');
//returns // '10/13/2013 12:54am' (new timezone)
2)
$entity = $this->Models->patchEntity($entity, $this->request->getData());
$entity->time->asTimezone('new timezone');

```
useful to change timezone for incoming times (pars time )

https://github.com/cakephp/cakephp/blob/master/src/I18n/DateFormatTrait.php#L312

**Comment by saeideng** [comment]
or changing  the `parseDateTime` signature 
from
`public static function parseDateTime($time, $format = null)`
to 
`public static function parseDateTime($time, $format = null,$tz=null,$locale=null)`

**Comment by markstory** [comment]
> there is not a built-in method for changing timezone , without changing time
2:50 in UTC => 2:50 in other timezone

I might be misunderstanding, but when would you want to preserve the wall time when changing timezones? Wouldn't changing timezones require changing the clock time as well?

**Comment by saeideng** [comment]
your default timezone is UTC
and you want to pars a time by `parseDateTime()` (for example )
passed time to this method has `other  timezone`
how you able to pars this date/time?

this method right now used UTC or default timezone 
https://github.com/cakephp/cakephp/blob/master/src/I18n/DateFormatTrait.php#L312
but you need to pars from `other  timezone`

**Comment by markstory** [comment]
> your default timezone is UTC and you want to pars a time by parseDateTime() (for example ) passed time to this method has other timezone how you able to pars this date/time?

That is a good question. We could add additional parameters to the `parse*` methods that allow the timezone to be defined.

**Comment by othercorey** [comment]
We can implement this by basically doing what Date does. Capture the values and then re-create the instance with the specified time zone.

I think the function name needs to be clear so users don't confuse it with `setTimezone()`.

Maybe ``forceTimezone($tz)`` or ``swapTimezone($tz)``.

**Comment by othercorey** [comment]
If this is the use case, I added time zone support https://github.com/cakephp/cakephp/pull/13884 to ``parseDateTime()``.  If that's what you need then we don't need to add this weird API.

>your default timezone is UTC
and you want to pars a time by parseDateTime() (for example )
passed time to this method has other timezone
how you able to pars this date/time?

**Comment by saeideng** [comment]
for swap the timezone (when time zone was not correctly for example ) 
no way except creating new instance
```php
$newtime = new \Cake\I18n\Time($oldtime->format('Y-m-d H:i:s'),'newTimeZone');
```

and this feature could be add to chronos in future , so I want to close this issue for now 


@othercorey  your PR about `$tz` parameter for `parseDateTime()` works well :+1:
