### ISSUE TITLE
New shell command forces plugin loading

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11533]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest dev-master

### What you did
Using existing 3.x apps that have a Console Shell and a plugin option, e.g.

    bin/cake upgrade all /path/ -p FooBar 

### What happened
```php
        if (!empty($this->params['plugin']) && !Plugin::loaded($this->params['plugin'])) {
            Plugin::load($this->params['plugin']);
        }
```
Forces a plugin load even though this was never indented to happen. Similar to bake and its plugin option this can very well also just be some other config or for external use.

Also the https://github.com/cakephp/upgrade is currently broken because of this: https://github.com/cakephp/upgrade/blob/master/src/Shell/Task/BaseTask.php#L37
It cannot use plugin option anymore, or dies with 

> Error: [Cake\Core\Exception\MissingPluginException] Plugin FooBar could not be found

### What you expected to happen
We shouldn't load Plugins here automatically as this is new unexpected behavior, or at least we need to find a way to disable this (or to be BC a way to enable it).

**Comment by markstory** [comment]
Why is loading the plugin a problem?

**Comment by markstory** [comment]
@dereuromark ping.

**Comment by dereuromark** [comment]
because those do not exist in that application.
Those are the plugins of the target application.
The param name plugin itself does not warrant force loading plugins as in some scopes this is used for sth else. In this case only for path building.

**Comment by markstory** [comment]
Ok. Perhaps `Shell` should catch the `MissingPluginException` and log a warning instead of dying?

**Comment by dereuromark** [comment]
I think even that is too much. Lots of shells can have a plugin param and use it for doing sth else than requiring an actual plugin present.
This part looks not bc.

Instead only the shells that need it should load plugins from this.

**Comment by markstory** [comment]
The line to load a plugin if the `--plugin` parameter is used was added almost 5 years ago though, in c727444880b5fc7e63493cc46fec6063e7b347f7. I'm not sure it is wise to remove it now.

**Comment by dereuromark** [comment]
Interesting that shells worked so far with it. Is loading now more strict?

**Comment by markstory** [comment]
Not sure. It may have become more strict as we make things stricter in general.

**Comment by dereuromark** [comment]
PR open.
