### ISSUE TITLE
Add option for custom port in SQLServer.php

### ISSUE THREAD

**Issue by mcvermeulen** [cakephp/cakephp#11544]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.8 (ec1e3d7008602b0f28afa08200c28a2570dc3001)
* Platform and Target: I'm running CakePHP with the built in server on my macbook. With php 7.1.1.12 installed. Using a MSSQL 2017 docker container exposed on port 1401, localhost

### What you did
I've setup my datasource in app.php to connect to the mssql server.
```
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Sqlserver',
            'persistent' => false,
            'host' => '127.0.0.1',
            /**
             * CakePHP will use the default DB port based on the driver selected
             * MySQL on MAMP uses port 8889, MAMP users will want to uncomment
             * the following line and set the port accordingly
             */
            'port' => '1401',
            'username' => 'SA',
            'password' => 'password',
            'database' => 'databasename',
```

### What happened
I kept getting timeouts when trying to login to the database server

After analyzing the DSN which was used for the connection i saw the port wasn't listed.

### What you expected to happen
I expected that the port which i entered in de datasource config was being used for the connection.

### What i did to solve it
I changed the file: `vendor/cakephp/cakephp/src/Database/Driver/SQLServer.php` 
Edited line 86 to include the port:
```
$dsn = "sqlsrv:Server={$config['host']},{$config['port']};Database={$config['database']};MultipleActiveResultSets=false";
```
This solution might not be complete. Haven't tested it without specifing a port.

**Comment by markstory** [comment]
Pull request open now.
