### ISSUE TITLE
3.x RFC CsrfProtectionMiddleware and one-time-cookies

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#11546]
In 2.x there was `csrfUseOnce`:
> Controls whether or not CSRF tokens are single use. Set to false to not generate new tokens on each request. One token will be reused until it expires. This reduces the chances of users getting invalid requests because of token consumption. It has the side effect of making CSRF less secure, as tokens are reusable.

Is there a way to do this in 3.x already that I did not discover / is not covered by the docs (I will then improve those)?

Otherwise, the `expiry` flag for CsrfProtectionMiddleware takes only strtotime-compatible strings AFAIK.

* Could we add `oneTimeOnly` flag set to `false` by default, and if that is set to `true`, generate a new CSRF token?
* Would that need to happen after `$next()` or before?
* How could I make sure that `FormHelper` et al. can read the last csrf token but also regenerate it - is that a problem?
* How could this be applied only to certain routes and certain HTTP methods?

Related:
One-time cookies: Preventing session hijacking attacks with stateless authentication tokens
https://dl.acm.org/citation.cfm?id=2220353 (payawalled)

* * *

Edit: I know that this feature (can) cause(ed) a lot of trouble but then it is optional and it always helped a lot protecting contact forms in a simple way from re-sub-mission.

**Comment by markstory** [comment]
> Is there a way to do this in 3.x already that I did not discover / is not covered by the docs (I will then improve those)?

There is not. Single use CSRF tokens require state on the server-side. We used to store that state in the session, but that lead to non-atomic operations which allowed tokens to sometimes be used more than once.

Single use tokens require an atomic datastore like redis or memcache and I feel are best supported by a plugin.

**Comment by ADmad** [comment]
Closing for reasons stated above.
