### ISSUE TITLE
ORM issue /Question 

### ISSUE THREAD

**Issue by FurqanKhan1** [cakephp/cakephp#11541]
@markstory 
Hi there !

I am using cake php version 2.9.8 ,and apparently i am running into issues with ORM writing to db.

The same query with raw sql takes around < .2 seconds and with ORM it takes around 20 seconds.

There is certainly something wrong here ,either with the environment or with my installation of cakephp.

I have exact same version of code-base working just fine on a different machine.

After lots of searching and head breaking i reached here !!

Its a cent os ,with mysql 5.7 .
I am logging the query execution times ,and its a constant delay of 20 seconds between each executed query (they are executed in  a loop) and even outside (same 20 seconds).

Could it have to do with meta data reflection ,i tried keeping debug mode as 0 ,1,2 no difference the issue persists.

Can any one guide me as to where i should be looking.

Thanks and regards

**Comment by robertpustulka** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
