### ISSUE TITLE
Flash Element for Success and Error not working properly

### ISSUE THREAD

**Issue by rafaeldotjs** [cakephp/cakephp#11545]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3
* Platform and Target: Wamp Server x64

### What you did
Created a prefix /admin/, website is inside a subfolder /new/, I have this in my controller: 

`$this->Flash->success(__('The service has been saved.'));`

I placed a Flash/success element in my index action:
`<?= $this->element('Flash/success'); ?>`

the element file, in Template/Element/Flash/success.ctp :
```
<?php
if (!isset($params['escape']) || $params['escape'] !== false) {
    $message = h($message);
}
?>
<div class="message success" onclick="this.classList.add('hidden')"><?= $message ?></div>
```
### What happened
The flash message doesn't print, it gives an error because the $message var is undefined. The same happened to the error element.

> Notice (8): Undefined variable: message [APP/Template\Element\Flash\success.ctp, line 3]

### What you expected to happen
I expected it to print the Success/Error Flash message.

**Comment by ADmad** [comment]
You are supposed to use the Flash helper to render flash messages, `$this->Flash->render()`.

**Comment by rafaeldotjs** [comment]
I understand that. But since I have $this->Flash->success('message'), and in the Flash component it gives it the option "Flash/success", shouldn't the default code of Element/Flash/success.ctp print the success messages? I might not be getting something here, but why does the Flash component points to an element file, and the element file does not print the message? If it is not a bug or incomplete feature, what is it? I asked about this in cakephp slack, didn't find an answer. I searched google, didn't find a solution.

If I use $this->Flash->render() in Flash/success.ctp, it still does not work, unless I hack the Flash component, like I did.

Can we talk a little longer before closing it? If indeed this is not a bug, can you explain clearly the solution? Because bug or not, it is definitely not clear how to proceed. Am I expecting something of the Flash/success.ctp that it is not made to do?

Thank you

**Comment by ADmad** [comment]
> But since I have $this->Flash->success('message'), and in the Flash component it gives it the option "success" as element, shouldn't the default code of Element/Flash/success.ctp print the success messages?

No it won't, since the component only sets the data to session. The flash elements needs required template variables to be set based on the session data, which is done by the FlashHelper. So you can't just set message through component and expect the message to show up properly by directly including the flash element.

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by dereuromark** [comment]
As I pointed out in Slack the other day, you can use [Flash plugin](https://github.com/dereuromark/cakephp-flash) if you want such extended functionality. The core itself does not provide all these extra features.
See https://github.com/dereuromark/cakephp-flash/blob/master/src/View/Helper/FlashHelper.php#L24 but you can also just fetch them separately: https://github.com/dereuromark/cakephp-flash/blob/master/tests/TestCase/View/Helper/FlashHelperTest.php#L89

**Comment by rafaeldotjs** [comment]
I think I got it. Just to make it clear, I thought it was a bug, you pointed out as well in Slack that maybe I should do a core PR, so I saw it as a bug or incomplete feature.

Thank you, sorry for the trouble.

**Comment by ADmad** [comment]
@rafaeldotjs Ping me again whenever you see me online on slack and I'll try to help you out.

**Comment by dereuromark** [comment]
```php
$this->Flash->render('flash', [
   'element' => 'Flash/custom_element'
];
```
should indeed work as documented to use a custom element for rendering them out.

**Comment by ADmad** [comment]
@dereuromark There are already tests showing the specifying `element` when rendering works as expected [[1]](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/View/Helper/FlashHelperTest.php#L158), [[2]](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/View/Helper/FlashHelperTest.php#L181).

**Comment by ADmad** [comment]
Closing again as everything works as expected. 

@rafaeldotjs showed me his code on slack and he was still including the flash element directly in his template and calling `FlashHelper::render()` inside `AppView::initialize()` which of course wasn't going to generate the desired results.
