### ISSUE TITLE
mapresources with prefix does not work, cakephp 2.10.x

### ISSUE THREAD

**Issue by mhorvath** [cakephp/cakephp#11543]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.5.
* Platform and Target: all servers

### What you did

```
Router::mapResources('purchases', array('prefix' => 'admin'));
```
postrequest to /admin/purchases.json

### What happened
```
2017-12-15 08:55:39 Error: [MissingActionException] Action PurchasesController::add() could not be found.
Exception Attributes: array (
  'controller' => 'PurchasesController',
  'action' => 'add',
)
Request URL: /admin/purchases.json
Stack Trace:
#0 /Users/mho4mh/Documents/work/4myhealth/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /Users/mho4mh/Documents/work/4myhealth/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PurchasesController), Object(CakeRequest))
#2 /Users/mho4mh/Documents/work/4myhealth/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
```

### What you expected to happen
that the map resources work :)
everything went well, after i updated from 2.6 to 2.10 the map resources routes with prefixes doesnt work anymore

if i do a post request to admin/purchases/add.json it works

**Comment by markstory** [comment]
I'll see if I can reproduce this issue.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. In my routes file I added

```php
	Router::mapResources('Tags', array('prefix' => 'admin'));
```

I generated a `TagsController` using bake (`Console/cake bake controller Tags`).  I was able to save new tags with `curl -XPOST -v http://cake.localhost/admin/tags -d 'title=newest'` without any errors in the response, or logs.

The existing tests for `mapResources()` are also passing. I'll need a way to reproduce this error before I can look at it further. If you can provide the steps necessary to reproduce this from a clean install of CakePHP or a simple application in a zip file I'd be happy to take another look.
