### ISSUE TITLE
FormHelper data-validation jquery validation rules keep DRY

### ISSUE THREAD

**Issue by mesiarm** [cakephp/cakephp#11558]
enhancement

I thought after FormHelper could autogenerate data-validation attributes in html based on model to ensure that validation rules are kept DRY. And sure there could be some options around it (data-validation attributes format)

**Comment by markstory** [comment]
Sounds like a great idea. You could incubate this idea in a plugin as I don't think it *needs* to be something that comes out of the box.

**Comment by dereuromark** [comment]
Please see https://github.com/FriendsOfCake/awesome-cakephp#rest-and-api validation exposer and other existing validation to JS extractors.
I agree that this is not a core issue at this point but best first introduced as plugin.

**Comment by ADmad** [comment]
Closing for the same reason, it can be implemented as a plugin first.
