### ISSUE TITLE
patchEntities returns new entities 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11556]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6

```php
    $list=$this->Models->find()->toArray();
    $list = $this->Models->patchEntities($list, [0=>['field'=>12]]);dd($list);

```
returns 
```php
[
	(int) 0 => object(App\Model\Entity\myEntity) {

		'[new]' => true,
		'[accessible]' => [
			'myfield1' => true,
			'myfield2' => true,
			'created' => true,
			'modified' => true,
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => '...'
	
	}
]
```
also you can try by 
`$list = $this->Models->patchEntities($list, $this->request->getData());dd($list);`

in all case that returns `'[new]' => true,`

and  there is just one and unrelated testCase 
https://github.com/cakephp/cakephp/blob/2529259fb3a13199b2cb27e8d8f9aea68cf4b709/tests/TestCase/ORM/TableTest.php#L5685

**Comment by markstory** [comment]
The issue is that your patch data doesn't include primary key fields. Because of that they are considered 'new' entities.

**Comment by inoas** [comment]
Is this clearly stated in the docs? Otherwise it should be added.
Or maybe we can add a strict mode where patching fails if the primary key is missing (disabled by default, enabled by default in 4.x)?

**Comment by saeideng** [comment]
@markstory
I used books sample,see again
With/without primaryKey returns new entity

**Comment by saeideng** [comment]
I able to push a PR (just testCase) if you want

**Comment by saeideng** [comment]
I see now your added testCase
Thanks
Looks i mistake
I'm sorry

**Comment by markstory** [comment]
> Is this clearly stated in the docs? Otherwise it should be added.

@inoas I think so. The API docs state

>  Those entries in `$entities` that cannot be matched to any record in `$data` will be discarded. Records in `$data` that could not be matched will be marshalled as a new entity.
