### ISSUE TITLE
Add performance metadata to Query result set.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#11569]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.x
* Platform and Target: LAMP/WAMP

### What you did

If you open the SQL panel in the DebugKit you can see performance data on executed SQL queries. I think this data could be of value (it's just a timing result). The DebugKit comes with a class to perform timing, but I thought it would be a handy feature if you could enable this natively in Query objects.

### What you expected to happen

What if we could use performance data as part of our business logic when working with Query results.

      $records = $documents->find()
                              ->where([......])
                              ->debug(true)
                              ->all();

       if($records->getTimespan()->seconds > 10) {
                   // Query execution took longer than expected. Handle business case here.
       }

You could write log messages about performance issues, or take action in cases where there is "work" that could be done to resolve the problem.

The Query object returns a `ResultSetInterface` when executing a SQL fetch operation. This interface is just a basic implementation of an iterator.

We could add a `getTimespan()` method to the interface, and maybe some other metadata related methods.

**Comment by dereuromark** [comment]
ResultSetInterface is more for actual production use.
What you suggest sounds more like a debugging use case - so I wouldnt want to add these kind of methods to the primary interface.
Why not adding a second interface for this use case that can be used in the context where this is needed or desired (e.g. DebugKit) and otherwise be out of scope of the use of the query object itself?

**Comment by thinkingmedia** [comment]
@derekperkins The idea here was to take what we've learned from DebugKit to the production environment. I'm saying that performance metadata could have a place in people's code. Help them make decisions about what to do. Yes, it has an overhead but we allow people to enable it via the Query interface. The problem with DebugKit is that it's not loaded in production.

I'm open to the idea that my use cases are out on the edges, and there isn't enough interested for it as a core feature. I'm okay with me too. That's why I opened a RFC.

**Comment by markstory** [comment]
What kind of performance metadata would you want to track on the query object?

**Comment by thinkingmedia** [comment]
@markstory right now, I could see the duration in milliseconds as being useful.

For example; I have a web page that has to find records using a very large `IN` operator. The performance is relative to the database size. Overtime the server grows the database to where I might want to start caching query results based upon the duration of the query.

Things like that. I could easily wrap everything in a timer, but I thought why not make this a standard feature.

**Comment by dakota** [comment]
I would rather suggest using and encouraging users to use a proper application performance monitoring solution for things like this.

**Comment by markstory** [comment]
Have you encountered situations that required your code to make decisions based on how long other queries took to execute? I've only needed timing metrics like that for performance monitoring, which as @dakota mentions is often better served by dedicated tools.

**Comment by thinkingmedia** [comment]
@markstory I'm running into cases where page load time is being affected by query duration, but I can not predict the lag. Take a home page for a news website where the front page articles need to be as current as possible, but generating fresh results has a page load cost. So you want to use cached results, and the caching should be relative to the lag. So if the queries are running quickly cache less often, but my case has changing conditions where query lengths depend upon changing news topics, and these can slow down queries. Since it's a front page issue. I want to use caching for the least amount of time relative to query times.

Anyway, that's where all this came from. 😀

**Comment by thinkingmedia** [comment]
I'm leaning towards closing as I think it's not enough to justify the change. Needs to have a broader use case that helps more people.
