### ISSUE TITLE
Truncate html text with style tag

### ISSUE THREAD

**Issue by LifeOrYou** [cakephp/cakephp#11568]
* [x] bug
* [x] enhancement

CakePhp v 3.5.8

When i truncate html text with style tag, the content of style tag is counted.
So the returned string contain only style tag content because my desired length is shoten than style tag content.
It's normaly or it's a forgotten (so i can propose a pull request) ?

**Comment by markstory** [comment]
>  It's normaly or it's a forgotten (so i can propose a pull request) ?

Style tags should not be included. A pull request to fix this would be great.

**Comment by markstory** [comment]
Closing as #11571 is open.
