### ISSUE TITLE
Paginator used finder

### ISSUE THREAD

**Issue by cocacola5959** [cakephp/cakephp#11562]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Paginator.php
false

        if (empty($query)) {
            $query = $object->find($finder, $options);
        } else {
            $query->applyOptions($options);
        }

true

        if (empty($query)) {
            $query = $object->find($finder, $options)->applyOptions($options);
        } else {
            $query->applyOptions($options);
        }

?

**Comment by markstory** [comment]
I don't understand the problem here. Could you explain it a bit better?

**Comment by cocacola5959** [comment]
Passing arguments to finder fails to pass options such as limit for paging, is it a specification?

**Comment by markstory** [comment]
Yes. We don't pass paging parameters to finders as the Paginator applies those options.

**Comment by cocacola5959** [comment]
Is the limit phrase or offset clause specified on the finder side?
Writing like the source below,
['finder' =>
  ['search' =>
    [
      'keyword' => "test",
      'limit' => 30,
    ]
  ]
]
Otherwise the limit and offset clauses will not be reflected.

**Comment by markstory** [comment]
I don't think I understand the problem you're having. Are you having problems getting paginating results when using a custom finder that uses additional options? Or is the problem that the `limit = 30` in your options is being replaced by pagination values?

**Comment by cocacola5959** [comment]
I have a problem getting the break of result page when using custom finder

**Comment by markstory** [comment]
What are you getting in your finder's `options` argument?

**Comment by cocacola5959** [comment]
Since we want to create search keyword for keyword and pass keyword to finder, we created finder putting keyword in options.
If you set it to the finder of the paginator as it is, the page count will be done, but sql using limit and offset will not be issued and all will be displayed.

**Comment by markstory** [comment]
So when the finder has additional options defined in the pagination settings, your queries do not have the limit/offset applied?

**Comment by cocacola5959** [comment]
How can I do this if I want to pass arguments unrelated to paging to finder while leaving the paging settings intact?

**Comment by markstory** [comment]
I think I understand the problem now. I'll see if I can reproduce the problem you're having, as I think what you have should work and pagination limit/offset should be applied as you're expecting.

**Comment by cocacola5959** [comment]
Thank you.

**Comment by markstory** [comment]
I wasn't able to reproduce your issue. I must have missed something.

My Controller action looked like:

```php
    public function index()
    {
        $settings = [
            'finder' => ['search' => ['search' => 'derp']]
        ];
        $this->set('bookmarks', $this->paginate($this->Bookmarks, $settings));
    }
```

My finder method on the `BookmarksTable` looks like:

```php
    public function findSearch($query, $options)
    {
        return $query->where(['Bookmarks.title LIKE' => "%{$options['search']}%"]);
    }
```

And the generated query looks like:

```php
SELECT 
  Bookmarks.id AS `Bookmarks__id`, 
  Bookmarks.user_id AS `Bookmarks__user_id`, 
  Bookmarks.title AS `Bookmarks__title`, 
  Bookmarks.description AS `Bookmarks__description`, 
  Bookmarks.url AS `Bookmarks__url`, 
  Bookmarks.created AS `Bookmarks__created`, 
  Bookmarks.updated AS `Bookmarks__updated`, 
  Bookmarks.starred AS `Bookmarks__starred` 
FROM 
  bookmarks Bookmarks 
WHERE 
  Bookmarks.title like '%derp%' 
LIMIT 
  20 OFFSET 0
```

I'm not seeing the missing limit/offset conditions that you are seeing.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue and there haven't been any updates in quite a while.
