### ISSUE TITLE
RFC: Using closure/anonymous for finder Auth

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11567]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: WAMP

It's will be good to using closure/anonymous function for `finder` in Auth config, like below:

    $this->loadComponent('Auth', [
       'authenticate' => [
           'Form' => [
               'finder' => function ($user) {
                   return $user->select([
                      'Users.id',
                      'Users.username',
                      'Users.password',
                   ])->where([ // conditions
                      // ...
                   ])->contain([
                      // ...
                   ]);
               },
           ],
       ],
    ]);

But I suppose it's not a simple change the line 179 in BaseAuthenticate (https://api.cakephp.org/3.5/source-class-Cake.Auth.BaseAuthenticate.html#178).

**Comment by dereuromark** [comment]
Why not using a custom finder on the Users table?
It is then also easier to test and controller keeps slim/lean as it should be.

**Comment by kicaj** [comment]
Because I use some plugin (for example CakeDC Users), I would like using custom function `finder` but I must use `UsersTable` (from plugin), but I can't rewrite `findAuth`...

I think it's shoud be very easy to use this, by add code below between 168 and 169 line (https://api.cakephp.org/3.5/source-class-Cake.Auth.BaseAuthenticate.html#168-169)
```
if (is_callable($finder) /* is_object($finder) && $finder instanceof Closure */ ) {
    return $table->query($finder);
}
```

**Comment by robertpustulka** [comment]
@kicaj you can create a behavior with a custom finder and attach it to the plugin's table.

**Comment by markstory** [comment]
If you're using a plugin you could also subclass/wrap and add your custom finder there.

**Comment by kicaj** [comment]
@markstory and @robertpustulka Your ideas are better, so I will close the issue
