### ISSUE TITLE
RFC configShallow to change merge function and rename it.

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11579]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: WAMP

### What you did
I use `configShallow` for merge configs with default configs (deeply) in my components.

### What happened
When I used `configShallow('a.b.c', 123);` my other configs for `a` and `a.b` was rewrited and are empty.

### What you expected to happen
Should be merged recursively.

I think should be use `array_replace_recursive` in line 297: https://api.cakephp.org/3.5/source-class-Cake.Core.InstanceConfigTrait.html#279 instead of `array_merge`.

Also in new standards, the method should be renamed to `setConfigShallow`,.

**Comment by kicaj** [comment]
Sorry I did not read: 

> Unlike config() which does a recursive merge for nested keys, this method does a simple merge

Closed.

**Comment by dereuromark** [comment]
Why are you not using setConfig()?

**Comment by ADmad** [comment]
> I use configShallow for merge configs with default configs (deeply) in my components.

Don't you think it's a bit strange expecting a method named `Shallow` to merge `deeply`? :slightly_smiling_face: 

> When I used configShallow('a.b.c', 123); my other configs for a and a.b was rewrited and are empty.

That's exactly show `configShallow()` is supposed to do, since it does "shallow" merging.

If you want deep merging then use `setConfig()`.

**Comment by dereuromark** [comment]
But we can sure split the get/set naming here. That part is valid.

**Comment by ADmad** [comment]
Also when renaming `config()` we could have used more intuitive names: `mergeConfig()` which merges and `setConfig()` which overrides. But it's too late for that.

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/cakephp/cakephp/issues/7267 where we can discuss changes for 4.x then.
