### ISSUE TITLE
Router not applying App.fullBaseUrl

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#11582]
This is a bug.

* CakePHP Version: 3.5.9
* Platform and Target: **CLI script**

### What I did

    echo \Cake\Routing\Router::url([
        'plugin' => false,
        'prefix' => 'admin',
        'controller' => 'Deliveries',
        'action' => 'add',
        '_ssl' => true,
        '_full' => true
    ])

### What happened
`https:///admin/deliveries/add`

### What I expected to happen
`https://example.com/admin/deliveries/add`

### Notes
 - The above code works as expected in non-CLI environments, but not in CLI.
 - The above code works as expected if `_ssl` is unspecified, but not if `_ssl` is either `true` or `false`.

**Comment by markstory** [comment]
I am assuming you have App.fullBaseUrl defined in your cli environment?

**Comment by PhantomWatson** [comment]
Yep, it's defined, and it shows up in the URL when the `_ssl` option is left unspecified.

**Comment by dereuromark** [comment]
PR now open.
