### ISSUE TITLE
RFC: Don't set session cookie name to "CAKEPHP"

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11584]
Setting the session cookie name to "CAKEPHP" by default and advertising the fact that an app uses CakePHP provides no benefit. It can in fact be used to try out attacks against known security vulnerabilities if the app doesn't use an up to date release.

So I propose just using the default session name set in php.in instead.

**Comment by BassemN** [comment]
:1:

**Comment by inoas** [comment]
Well while I don't think security by obscurity has much of a value I don't thing exposure for no reason has a value either. What about something like "app" or `sha1($mainFoldername)` for defaults?

**Comment by markstory** [comment]
I am good with using what is defined in php.ini. Do you think that change will be possible without causing issues fir existing applications?

**Comment by dereuromark** [comment]
Isnt that set only in cakephp/app anyway?

**Comment by ADmad** [comment]
@markstory We will have to document the change in migration guide and existing apps will have to update their app config to keep old cookie name. That's why i propose making the change in 4.0

@dereuromark No the default cookie name is set in core's Session class.

**Comment by patsuckow** [comment]
This will simplify the use of third-party applications that work with CakePHP, and which use the cookie - "PHPSESSID" in their work.

**Comment by dereuromark** [comment]
Let's do it for 3.6 then, a small migration note on how to enable the former one (for existing applications that dont want to switch) with a single line of config on top should suffice.
