### ISSUE TITLE
Make _name available from Route.php

### ISSUE THREAD

**Issue by EliasDeVos** [cakephp/cakephp#11595]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

Hi,
I needed a way to get the _name option from Route.php in my controller.
I didn't really find a good way to do it so i added this to the parse() method.

I tried to create a pull request but didn't have access.
This is the code i would add (in src/Routing/Route/Route.php:482:
`// pass the name if set`
 ` if (isset($this->options['_name'])) {`
      `$route['_name'] = $this->options['_name'];`
  `}`

If there is another way to do this or you dont think this code belongs here let me know.

**Comment by saeideng** [comment]
duplicate : https://github.com/cakephp/cakephp/issues/10950
