### ISSUE TITLE
[RFC] Disable calling methods of inner iterators via Collection

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11593]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.10

Relates to #11396

It is not documented in the [Cookbook](https://book.cakephp.org/3.0/en/core-libraries/collections.html), but in 3.5.10 or earlier, people can call methods of  inner iterators via Collection:
```php
$collection = new \RegexIterator(new \ArrayIterator(['one', 'two', 'three']), '/^t/');
$collection = collection($collection);

debug($collection->getRegex()); // /^t/
```

However, it becomes impossible after some method has been called. If you do the following, you will get a fatal error:
```php
$collection = new \RegexIterator(new \ArrayIterator(['one', 'two', 'three']), '/^t/');
$collection = collection($collection);

$collection = $collection
    ->sortBy(function($item) {
        return strlen($item);
    });

debug($collection->getRegex()); // Call to undefined method ArrayIterator::getRegex() 
```

So I would like to remove this feature completely. I did it in #11064, but now it has been reverted partially by #11440.

But, on the second thought, I am not sure we should do it in 3.6. If people rely on this non-documented feature, I think it may be better to do it in 4.0 instead.

What do you think?

**Comment by lorenzo** [comment]
I agree it should be removed

**Comment by markstory** [comment]
I agree it should be removed, but we'll need to wait until 4.0. In #11440 I was restoring behavior added/fixed in #11396. The behavior in #11396 was to allow classes using the `CollectionTrait` to retain access to their user-land methods. If we remove the `__call` behavior we might have to document that many of the methods in `CollectionTrait` will return objects that disallow access to userland methods.

**Comment by chinpei215** [comment]
OK. Then I will revert #11045 in a few days, and send the same pull request again in 4.0. I don't think we can keep the original behavior if we override `IteratorIterator::__call()`, as `method_exists()` seems to handle it magically: https://github.com/cakephp/cakephp/pull/11440/files#diff-66f2154ab9fca71911f66b7706f66fc7L2559

**Comment by ADmad** [comment]
Can this be closed?

**Comment by chinpei215** [comment]
Probably, we might need to change current behavior of Collection::__call() in 4.0.

**Comment by ADmad** [comment]
@chinpei215 Now would be a good time to make this change for 4.0 :slightly_smiling_face:.

**Comment by chinpei215** [comment]
I forgot I opened this issue in the past. If we remove this feature in 4.0, we would need to raise deprecation warnings in 3.8.
