### ISSUE TITLE
make console scripts return a exitcode

### ISSUE THREAD

**Issue by gemal** [cakephp/cakephp#11606]
could be really really nice if cakephp console script would support returning a exit code to the underlaying system

In laravel if you have a `return 1;` as the last command in the main function the OS will return a exit code of 1 from the console script.

**Comment by jeremyharris** [comment]
It does just that. See: https://book.cakephp.org/3.0/en/console-and-shells.html#status-and-error-codes

-----

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
