### ISSUE TITLE
Unnecessary exception when logging to custom level/filename

### ISSUE THREAD

**Issue by gugleboot** [cakephp/cakephp#11603]
* [x] enhancement
* CakePHP Version: 3.5.8

### What you did

Defined logging configuration for custom level / file
` 'agent' => [
            'className' => 'Cake\Log\Engine\FileLog',
            'path' => LOGS,
            'file' => 'agent'
        ]`

later in the code:
`Log::write('agent', 'Payment failed');   `

### What happened

exception thrown 
> Invalid log level "agent" 

### What you expected to happen

I would like to be able to write the line:

> 2018-01-05 09:12:42 Agent: Payment failed

to /logs/agent.log file only, without using levels and PREVENT!! logging/duplicating to other files like debug.log or error.log .  Maybe extending built in POSIX logging levels on the fly assuming scope = agent , level = agent.

**Comment by markstory** [comment]
We won't be supporting custom log levels as they do not work with non-file based log engines.

You can create a custom log engine that creates the desired formatting, and use scopes to specifically target specific log outputs when you log.
