### ISSUE TITLE
CLI commands should be a verb and not a noun

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#11618]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.10

### What you did

Started the Cake web server for development:

    bin/cake server

### What happened

I keep trying to use the verb `serve`

    bin/cake serve

### What you expected to happen

This is where things get very subjective and I apologize ahead of time. I'm just opening an issue so that I can resolve my own OCD challenges as this has bugged me for awhile.

It's a *verb* and not a *noun*.

You perform a *verb* action against a *noun*, but the *noun* itself doesn't imply an action.

    bin/cake start server

Or

    bin/cake run server

But if you want just a single command to start the server. It should be.

    bin/cake serve

I know I'm insane for complaining about this, but it's the little details.....

**Comment by dereuromark** [comment]
A consistent API for CLI makes sense. And this sounds reasonable.
I guess we can try to keep this in mind for a future major version jump.

**Comment by markstory** [comment]
I'm open to adding more verb based aliases if you think it would improve the usability of the CLI command tools.

**Comment by chinpei215** [comment]
I don't like this idea. Since I am not good at English, I cannot imagine how VersionShell, CommandListShell, RoutesShell and so on are aliased.

**Comment by markstory** [comment]
I don't know how one would convert `version` or `help`  into verbs either. But routes could be `routes show`. Given our current CLI parsing I don't think we could get to `<verb> <noun>` easily. We could get to `<noun> <verb>` though. Which makes commands like `cake server start`.

**Comment by robertpustulka** [comment]
@markstory maybe prefix those with "show"? `show version`, `show help`?

**Comment by chris48s** [comment]
Does `help` need an alias? You can use it like "can you _help_ me out" (verb) as well as "I need some _help_" (noun).

**Comment by dereuromark** [comment]
Since the benefit of this seems rather small, maybe we can focus on other things instead then.
Not sure if we need to keep this discussion open more.

**Comment by robertpustulka** [comment]
You can add shells and commands under your own aliases using console collection in your `console()` application hook. If user preference is the main issue here I think that this can be closed then.
