### ISSUE TITLE
check if route exists with $defaults and $options

### ISSUE THREAD

**Issue by EliasDeVos** [cakephp/cakephp#11625]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

Hi,
Right now i have a use case where i need to check if a given route exists.
I would create the route like this Router::url($defaults, $options).

But right now if the route does not exist it throws an error

https://github.com/cakephp/cakephp/blob/master/src/Routing/RouteCollection.php#L347

So i have to work with try catch to solve this.

Would it be an option to add a new static function in \Cake\Core\Router routeExists($defaults, $options)

which would return false if it doesn't exist and true (or maybe the url) if it does ?

Let me know if this would be a good enhancement and i will create a pull request

**Comment by markstory** [comment]
I thinks that's a reasonable addition to `Router`. It could be a simple try/catch wrapper around `Router::url()`.

**Comment by saeideng** [comment]
`Router::urlOrNull()` :)

**Comment by EliasDeVos** [comment]
@markstory won't there be a lot of issues if we would add try/catch in the `Router::url()` method ? because the code would keep on going instead of halting and throwing an error ?
Maybe @saeideng suggestion is safer ? let me know what you think and i will make a pull request

**Comment by markstory** [comment]
@EliasDeVos I wasn't very clear. I was trying to say that `Router::routeExists()` could be a try/catch wrapper around `Router::url()`. Not that we should add try/catch inside of `Router::url()`.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
