### ISSUE TITLE
My CakePHP Registration issue

### ISSUE THREAD

**Issue by Yogesh-Chauhan** [cakephp/cakephp#11624]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.x
* Platform and Target: https://my.cakephp.org/join

### What you did
I had registered for My CakePHP but by mistake entered the wrong email ID. I was waiting for the verification email but was unable to do so. Now, I am trying to register again with the correct email and same username but it's showing username already taken. 

### What happened
I am trying to register again with the correct email and same username but it's showing username already taken. 

### What you expected to happen
I want to edit the email id in my under verification account but unable to do so. Kindly delete that or allow me to edit because it's deadlock condition here as I can't use that username again.

**Comment by Yogesh-Chauhan** [comment]
Added the cakePHP version but here it is not required

**Comment by thinkingmedia** [comment]
Sorry for your registration troubles. I *assume* that the previous registration account will expire shortly and hopefully be deleted. That should allow you to use that username again. I'll take a look and see if I can find the what's going on.

**Comment by dereuromark** [comment]
Closing as opened in the correct repo.
