### ISSUE TITLE
Controller test cases pass single, fail together

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11626]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.x latest (dev-master)

### What you did
Plugin test case for FeedbackController and \Admin\ prefixed FeedbackController.

 php phpunit.phar tests/TestCase/Controller/FeedbackControllerTest.php => pass
 php phpunit.phar tests/TestCase/Controller/Admin/FeedbackControllerTest.php => pass
 php phpunit.phar tests/TestCase/Controller/ => FAIL (also see Travis confirmation)

Each for itself passes, but together they suddenly fail.
Since those are completely separate test case classes, they shouldnt share anything here in terms of request handling.

Does it play into it that they still use LegacyRequestDispatcher?
Or that I used $this->disableErrorHandlerMiddleware(); ?

Code can be reproduced and checked @ https://github.com/dereuromark/cakephp-feedback/pull/5

### What happened
https://travis-ci.org/dereuromark/cakephp-feedback/jobs/328244684
```
1) Feedback\Test\TestCase\Controller\FeedbackControllerTest::testSave
Cake\Controller\Exception\MissingActionException: Action FeedbackController::save() could not be found, or is not accessible.

...

1) Feedback\Test\TestCase\Controller\FeedbackControllerTest::testSaveInvalid
Failed asserting that exception of type "Cake\Controller\Exception\MissingActionException" matches expected exception "\Cake\Network\Exception\MethodNotAllowedException". Message was: "Action FeedbackController::save() could not be found, or is not accessible."
```

### What you expected to happen
Controller + Admin controller should be testable together for plugins.

**Comment by markstory** [comment]
Outside of your plugin how can this be reproduced?

> Since those are completely separate test case classes, they shouldnt share anything here in terms of request handling.

Have you checked the usual sources of shared global state? The test harness can't reset it all.

**Comment by dereuromark** [comment]
Are there any special guidelines for plugin integration testing?

**Comment by dereuromark** [comment]
Turns out that the setUp() methods didnt call the parents, and thus it failed.
