### ISSUE TITLE
Can not reset mailer replyTo

### ISSUE THREAD

**Issue by caladfelipe** [cakephp/cakephp#11627]
* [x] bug

* CakePHP Version: 3.5.10
* Platform and Target: Apache, MySQL

Tried to reset email replyTo but an error occurs:

$mailer->setReplyTo([]); // Error = "Reply-To requires only 1 email address."

### What you expected to happen
To reset the email replyTo to anybody, technically to an empty array.

**Comment by markstory** [comment]
This is an issue with all of the email address setter methods. Currently it is not possible to unset/clear any email address property.

**Comment by dereuromark** [comment]
I usually use reset() and then set it again.

**Comment by markstory** [comment]
@dereuromark But that will reset all of the mailer state, which is not always desirable.

Pull request open now.
