### ISSUE TITLE
ClassRegistry::init() does not use plugin information for internal model mapping.

### ISSUE THREAD

**Issue by ThomasNunninger** [cakephp/cakephp#11623]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.6.12 (but seems to be in branch 2.x as well)
* Platform and Target: not relevant.

### What you did

```
$model1 = ClassRegistry::init('MyClass');
$model2 = ClassRegistry::init('MyPlugin.MyClass');
```

### What happened
`$model2` is the same as `$model1`

### What you expected to happen
`$model2` should be the class loaded from MyPlugin

### Reason
`ClassRegistry::init()` only uses the `$alias` (without plugin information) to duplicate and map the model:

```
$model = $_this->_duplicate($alias, $class);
if ($model) {
    $_this->map($alias, $class);
    return $model;
}
```

That needs to be enhanced to use plugin information for the key as well.

**Comment by ThomasNunninger** [comment]
Hint: class `MyClass` does not exist and `AppModel` was returned for `$model1` and when called correctly with the plugin prefix `$model2` was `AppModel` as well.

**Comment by dereuromark** [comment]
This is a known limitation, as you are loading something with the internal alias MyClass and then just use the same internal one with the 2nd call.
Either keep all classes unique or use a different alias for the 2nd call, to not reuse the first alias.
This is not considered a core bug, though, afaik.
