### ISSUE TITLE
Unable to configure the session, setting session.save_handler failed (PHP 7.2)

### ISSUE THREAD

**Issue by harpax** [cakephp/cakephp#11628]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.10
* Platform and Target: Ubuntu 16.04, Apache 2.4, PHP 7.2 (7.2.1-1+ubuntu16.04.1+deb.sury.org+1)

### What you did
Updated php from 7.0.x to 7.2

### What happened
![image](https://user-images.githubusercontent.com/75890/34931817-d495c5d0-f9d0-11e7-9d94-d1221e5d02bf.png)

Found a similar issue here: https://github.com/symphonycms/symphony-2/issues/2783

The check in https://github.com/cakephp/cakephp/blob/83815ac4912656eb9e724e179bbe1dc6440e3359/src/Network/Session.php#L113 evaluates to false, so I don't quite know why this is happening, but removing line 166 from that file solves the issue

**Comment by ADmad** [comment]
Hmm.. I have the same PHP version locally and don't get any error with the default session config.

**Comment by markstory** [comment]
Are you attempting to use database sessions?

**Comment by harpax** [comment]
Yes, I am using DB-Sessions

**Comment by markstory** [comment]
Thanks. I'll try and reproduce this issue.

**Comment by ADmad** [comment]
Based on the comments on https://github.com/symphonycms/symphony-2/issues/2783 it seems we can just get rid of setting `session.save_handler` to `user`. Things work fine without it even on PHP 5.6.

**Comment by markstory** [comment]
Pull request open now.
