### ISSUE TITLE
cakephp not using my custom messages (validation)

### ISSUE THREAD

**Issue by agarzon** [cakephp/cakephp#11630]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.9
* Platform and Target: NGINX, LINUX

### What you did
Write a simple validation rule with Modelless form.

### What happened
CakePHP ignores my custom message

### What you expected to happen
CakePHP should show my message instead the default one.

I'm following the code here: https://book.cakephp.org/3.0/en/core-libraries/form.html

My code is like:

```php
    protected function _buildValidator(Validator $validator)
    {
        return $validator
            ->add('firstname', 'required', [
                'rule' => 'notBlank',
                'message' => __('A first name must be provided'),
            ]);
    }
```

I should see my own custom message : _A first name must be provided_ but instead I always get _This field cannot be left empty_

The interesting thing is that if I replace the code for this:

```php
$validator->notEmpty('firstname', __('A first name must be provided'));
```
Then I actually get my custom message as expected... but... notEmpty is being deprecated so if I change it for the official notBlank:

```php
$validator->notBlank('firstname', __('A first name must be provided'));
```

Guess what... again it doesn't work and I get the default: _This field cannot be left empty_

Not sure what's wrong here, but I'm sure it doesn't behave in the expected way. The example given here will lead to my same situation: https://book.cakephp.org/3.0/en/core-libraries/form.html

**Comment by markstory** [comment]
What data are you attempting to validate?

**Comment by agarzon** [comment]
Just checking that the field is not blank.

Form:
```php
echo $this->Form->create($contact);
echo $this->Form->control('firstname');
echo $this->Form->end();
```

Data:

```php
    protected function _buildSchema(Schema $schema)
    {
        return $schema
            ->addField('firstname', ['type' => 'string']);
    }
```

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce this issue with that information.

**Comment by markstory** [comment]
The validation error you're seeing looks like the validation error created by the implict `allowEmpty => false` rule. This state is controlled by `Validator::notEmpty()` which is *not* deprecated.

Perhaps you are confusing `Validator::notEmpty()` and `Validation::notEmpty()` which *is* deprecated. The methods are easy to confuse as they have very similar names. The problematic `allowEmpty` state is being reviewed in #8925 and it may be deprecated/removed as it complicates building validation rules.

**Comment by agarzon** [comment]
Then what validation rule should I use in order to display my custom message?. Because using the notBlank rule is always showing a default error instead my own, which still an unexpected behavior.

**Comment by markstory** [comment]
You should be using `$validator->notEmpty()` to ensure a field is not an empty value.  The notBlank() method exists on `Validator` to afford scenarios where the blankness needs to be checked after other validation rules.

**Comment by agarzon** [comment]
Well, I did what you say and replaced the **notBlank** for **notEmpty**, and now when I execute my phpunit tests:

```php
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

.II.....IIIIII.....Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

.Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

.Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

.Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

Deprecated Error: Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. in [/app/vendor/cakephp/cakephp/src/Validation/Validation.php, line 70]

....I.II                                    30 / 30 (100%)

Time: 20.39 seconds, Memory: 236.92MB

```

**Comment by markstory** [comment]
That is odd. Are you using `$validator->notEmpty()` or `$validator->add()` to apply your not empty rules? Using

```php
$validator
            ->add('firstname', 'required', [
                'rule' => 'notEmpty',
                'message' => __('A first name must be provided'),
            ]);
```

Will result in a deprecation warning as you are adding a validation rule, that delegates to `Validation::notEmpty()`.  If you were to do:

```php
$validator->notEmpty('firstname', __('A first name must be provided'));
```

You shouldn't see a deprecation warning, as this method toggles the 'allow empty' state on the validator (which is separate from the validation rules). I admit this is a pretty awkward and confusing API, which we'd like to change in the future but the current API must remain for the duration of 3.x for backwards compatibility reasons.

**Comment by agarzon** [comment]
Yes, I'm using `$validator->add()` and yes this is quite confusing.

I was expecting `add()` method to be able to **add** any validation rule and behave consistently (always use the message defined in the rule).

Anyways, I hope this can be addressed deeply in future versions. Same as `Validation` and `Validator` having the same methods names.

Thank you, I let you decide the issue will be closed.
