### ISSUE TITLE
Call to undefined method Cake\Chronos\DifferenceFormatter::timeAgoInWords()

### ISSUE THREAD

**Issue by zaros** [cakephp/cakephp#11649]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11 with Chronos 1.1.4
* Platform and Target: MacOS, Apache, PostgreSQL, GET request

I used timeAgoInWords() and got an error "Call to undefined method Cake\Chronos\DifferenceFormatter::timeAgoInWords()"

However, in a different location I had done the same and did not get such error.

**Comment by zaros** [comment]
![screen shot 2018-01-22 at 2 42 31 am](https://user-images.githubusercontent.com/738805/35197763-74bc0d6e-ff1f-11e7-86db-ac7d8f0f461a.png)

**Comment by zaros** [comment]
![screen shot 2018-01-22 at 2 56 34 am](https://user-images.githubusercontent.com/738805/35197789-e49f3660-ff1f-11e7-91a4-d5122abcc71f.png)

As called in another location

**Comment by saeideng** [comment]
How can someone reproduce the error you're seeing?
any sample code !!?

**Comment by dereuromark** [comment]
Looks like a user error to me then?

**Comment by zaros** [comment]
I'm very sure it wasn't an error on my part and I'm sorry for the very vague information I posted earlier.

It was a weird problem and I don't really know how to help you reproduce, because it is literally something like this code (although in reality a bit more complicated, but essentially): 

```
/* In Controller  */
// a typical database request gets the expected entities
$users = $this->Users->find(); 

/* Then in the view */
foreach ($users as $user) {
   echo $user->modified->timeAgoInWords();
}
```
This same code worked fine in one controller/function/view, but not at another controller/function/view. 

As I had posted above, I was showing that in both cases when I do debug($user->modified) the output is the same in both situations, i.e. I get a FrozenTime object, which unless I'm wrong, should implement  the timeAgoInWords() method -- but here the issue is as I documented it was not implemented in at least one situation. 

Any reason this would happen? 

For now I have decided not to use the method in my project and have moved on, but if you can guide me how to troubleshoot this, I'll report back with my findings once I have the time.

**Comment by markstory** [comment]
Closing as this issue has become stale and we don't have a way to reproduce this issue.

**Comment by emaillenin** [comment]
I am able to reproduce this. If we send an entity to the view via `$this->set(compact(..))` from the controller, and from that entity in the view, if we try to access a `datetime` property it contains `DifferenceFormatter` in the `diffFormatter` field:

![image](https://user-images.githubusercontent.com/1235853/76523089-ce263c00-648d-11ea-87db-da862899a8e4.png)

But if we access the same entity in the controller, we get `RelativeTimeFormatter` in the `diffFormatter` field:

![image](https://user-images.githubusercontent.com/1235853/76523124-df6f4880-648d-11ea-9561-89c4beefce2d.png)

**Comment by garas** [comment]
```php
class Chronos extends DateTimeImmutable implements ChronosInterface
{
    use Traits\ComparisonTrait;

    use Traits\DifferenceTrait;
    // has public static function diffFormatter(),
    // returns static::$diffFormatter = new DifferenceFormatter();

    use Traits\FactoryTrait;
    use Traits\FormattingTrait;
    use Traits\MagicPropertyTrait;
    use Traits\ModifierTrait;
    use Traits\RelativeKeywordTrait;
    use Traits\TimezoneTrait;
}

class FrozenTime extends Chronos implements JsonSerializable
{
    use DateFormatTrait;
    // has public static function diffFormatter(),
    // returns static::$diffFormatter = new RelativeTimeFormatter();


    public function timeAgoInWords(array $options = [])
    {
       // is it DifferenceTrait::diffFormatter() or DateFormatTrait::diffFormatter() ?
        return static::diffFormatter()->timeAgoInWords($this, $options);
    }
}
```

**Comment by ADmad** [comment]
>        // is it DifferenceTrait::diffFormatter() or DateFormatTrait::diffFormatter() ?
:man_shrugging:

**Comment by ADmad** [comment]
In Cake 4 `DateFormatTrait::diffFormatter()` was renamed to `DateFormatTrait::getDiffFormatter()` while `DifferenceTrait::diffFormatter()` in Chrons remained unchanged, so the ambiguity is gone as all `Frozen::timeAgoInWords()` uses `DateFormatTrait::getDiffFormatter()`.

**Comment by emaillenin** [comment]
I am using CakePHP `3.4.13`.

**Comment by ADmad** [comment]
@emaillenin What's your PHP version? Also you need to check with latest 3.8 release, 3.4 won't be getting any updates.

**Comment by garas** [comment]
> In Cake 4 `DateFormatTrait::diffFormatter()` was renamed to `DateFormatTrait::getDiffFormatter()` while `DifferenceTrait::diffFormatter()` in Chrons remained unchanged, so the ambiguity is gone as all `Frozen::timeAgoInWords()` uses `DateFormatTrait::getDiffFormatter()`.

But internal `static::$diffFormatter` still same.

Try `composer require cakephp/i18n:^3.0` (or `^4.0`)
```php
<?php
require_once 'vendor/autoload.php';

$chronos = \Cake\Chronos\Chronos::parse('yesterday');
$frozenTime = \Cake\I18n\FrozenTime::parse('yesterday');

// Swap lines to fail
echo $frozenTime->timeAgoInWords() . "\n";
echo $chronos->diffForHumans() . "\n";
```

**Comment by ADmad** [comment]
> But internal static::$diffFormatter still same.

Ah, that being a static property is the issue. Depending on which method is calls first it gets populated by either `RelativeTimeFormatter` or `DifferenceFormatter` instance and that persists.

So intializing `RelativeTimeFormatter::$diffFormatter` could solve the problem. In Cake 4 / Chronos 2 we could made that property and it's getter/sett non static.

**Comment by othercorey** [comment]
I don't think the solution is only making it non-static.

- Chronos has `DifferenceFormatterInterface`
- Cake has `RelativeTimeFormatter` that implements `DifferenceFormatterInterface`

- Cake has `setDiffFormatter()` which sets the instance in `static::$diffFormatter`
- Chronos has `diffFormatter()` that returns that instance
- Cake has `getDiffFormatter()` that returns that instance

We don't want to remove the ability to use the specialized sub-class when calling Chronos methods. There's no reason `diffFormatter()` needs to be overriden by a subclass of all Chronos types to do that.

I think we need a `setDiffFormatterClass()` that sets the class used by `diffFormatter()` in Chronos. Then we would remove the non-Chronos versions of `setDiffFormatter()` and `getDiffFormatter()`.
