### ISSUE TITLE
Insert into between different databases - MySQL

### ISSUE THREAD

**Issue by genellern** [cakephp/cakephp#11641]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.4.*
* Platform and Target: Apache, Mysql, Ubuntu on vagrant.

### What you did
Inserting data from a database to another with INSERT INTO didn't switch between databases.

`

        $etlUsersTable = TableRegistry::get('EtlUsers', ['table' => 'etl_users', 'connectionName' => 'default']);
        $oldUsersTable = TableRegistry::get('OldUsers', ['table' => 'users', 'connectionName' => 'old_system']);

        $select = $oldUsersTable->find()
            ->select(['id', 'email', 'password', 'title', 'first_name', 'last_name'])
            ->where(['email IN ' => $emails]);
            debug($select);

        $query = $etlUsersTable->query()
            ->insert(['user_id', 'email', 'password', 'title', 'first_name', 'last_name'])
            ->values($select)
            ->execute();

`

### What happened
It connected to both databases, but didn't query from the origin to insert in the target.

The mysql log:
```

    33 Connect   root@localhost on old_system using Socket
    33 Query     SET time_zone = '+0:00'
    33 Query     SET NAMES utf8

    34 Connect   root@localhost on new_system using Socket
    34 Query     SET time_zone = '+0:00'
    34 Query     SET NAMES utf8

    34 Query    INSERT INTO etl_users (user_id, email, password, title, first_name, last_name) 
    SELECT OldUsers.id AS OldUsers__id, OldUsers.email AS OldUsers__email, OldUsers.password AS OldUsers__password, 
        OldUsers.title AS OldUsers__title, OldUsers.first_name AS OldUsers__first_name, OldUsers.last_name AS OldUsers__last_name 
    FROM users OldUsers 
    WHERE email in ('email1@example.com', 'email2@example.com')


```

### What you expected to happen
It makes a query pulling data from the source database and inserting it into the target database, set in the table object.

```

    33 Connect   root@localhost on old_system using Socket
    33 Query     SET time_zone = '+0:00'
    33 Query     SET NAMES utf8

    34 Connect   root@localhost on new_system using Socket
    34 Query     SET time_zone = '+0:00'
    34 Query     SET NAMES utf8

    34 Query    INSERT INTO etl_users (user_id, email, password, title, first_name, last_name) 
    SELECT OldUsers.id AS OldUsers__id, OldUsers.email AS OldUsers__email, OldUsers.password AS OldUsers__password, 
        OldUsers.title AS OldUsers__title, OldUsers.first_name AS OldUsers__first_name, OldUsers.last_name AS OldUsers__last_name 
    FROM old_system.users OldUsers 
    WHERE email in ('email1@example.com', 'email2@example.com')

```
Notice the FROM in the expected query `FROM old_system.users` even when the connection is  the default.

**Comment by markstory** [comment]
The orm doesn't allow cross connection operations like this. We don't afford cross database operations because they are not always possible. Instead of having a buggy implementation we elected to not support it as a feature.

You may be able to do `$etlUsers = TableRegistry::get('EtlUsers', ['table' => 'old_system.users'])`.

**Comment by genellern** [comment]
It worked, thanks!
