### ISSUE TITLE
2.x - Cannot unset string offsets	

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#11658]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.9 -> 2.10.7
* Platform and Target: PHP 5.5.9, Apache 2.4.7 under Vagrant (VirtualBox) w/ Ubuntu 14.04.5

### What you did
Upgraded a legacy project from CakePHP `2.9.9` to `2.10.7` using `cakephp/cakephp: ^2.9`

### What happened
My project threw a fatal error.

```
Error: Cannot unset string offsets	
File: /home/vagrant/DigitalTV/vendor/cakephp/cakephp/lib/Cake/View/Helper/SessionHelper.php	
Line: 168
```
[SessionHelper#L168](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/View/Helper/SessionHelper.php#L168)

### What you expected to happen
My project would continue to work as normal.

### Introduced
2e75f12a4f05450b8be062999f0c2157cb80922e

**Comment by markstory** [comment]
How can someone reproduce the error you're getting?

**Comment by davidyell** [comment]
I've added a test case which I hope will reproduce the issue.

**Comment by davidyell** [comment]
[Travis is happy in the PR](https://travis-ci.org/cakephp/cakephp/jobs/332715032), so I'm happy that the issue is with my userland code.

I'll close this.

**Comment by davidyell** [comment]
I've found the offending code.

```php
CakeSession::write(
    'Message.clear_cache_result', 
    array(
        'message' => $message, 
        'element' => 'NiceAdmin.alert-box', 
        'params' => array('class' => 'alert-info')
    )
);
```
