### ISSUE TITLE
Automatically use custom parent field for tree behavior in find('threaded')

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#11657]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11
* Platform and Target: Apache 2, MySQL 5.7

I created a Tree behavior in a table's initialize method, **with a custom parent_id field**

```
public function initialize(array $config)
    {
        $this->addBehavior('Tree', [
            'parent' => 'my_custom_id_field',
        ]);
    }
```
I then wanted to retrieve nested data with that piece of code

```
        $result = $this->find('threaded')
```

I expected the children to be included in the resultset, but they **were missing**. After some research, I found the (**well documented**) option to pass the my_custom_id_field as a parameter

```
        $result = $this->find('threaded', [
            'parentField' => 'my_custom_id_field'
        ]);
```
This works great, but: Is there any possiblity to automatically use the parent field that was passed on intialization of the behavior?

Thanx,
Mario

**Comment by markstory** [comment]
> This works great, but: Is there any possiblity to automatically use the parent field that was passed on intialization of the behavior?

Seems like a reasonable default. Any chance you'd be willing to put together a pull request for `3.next` to implement it? I'm happy to help with tests if you need a hand.

**Comment by mrothauer** [comment]
I'm happy to create a pull request. At least I will try :-)

**Comment by markstory** [comment]
Closing as a pull request is open.
