### ISSUE TITLE
Phone validator seem not existing anymore ?

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#11651]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.10 - 288a1e2c86319a6e51fdeca0d086b95be1853b11
* Platform and Target: Ubuntu 17.10 - Nginx 1.12.1 - PHP 7.1.11

### What you did
I'm in modeless form, and like the doc say, i add a validation rule for phone

    protected function _buildValidator(Validator $validator)
        {
            $validator->setProvider('fr', 'Localized\Validation\FrValidation');

            return $validator
                ->requirePresence('name')
                ->notEmpty('name')
                ->add('name', 'length', [
                    'rule' => ['minLength', 3]
                ])
                ->requirePresence('email')
                ->notEmpty('email')
                ->add('email', 'validFormat', [
                    'rule' => 'email'
                ])
                ->requirePresence('phone')
                ->add('phone', 'validFormat', [
                    'rule'     => 'phone',
                    'provider' => 'fr'
                ]);
        }

### What happened
    2018-01-22 14:18:26 Error: [InvalidArgumentException] Unable to call method "phone" in "fr" provider for field "phone"

**Comment by saeideng** [comment]
related repo : https://github.com/cakephp/localized
https://github.com/cakephp/localized/blob/master/src/Validation/FrValidation.php#L30
you should install `localized` plugin before use it

**Comment by Aerue** [comment]
I've missed that line... Thank for the help, can close this issue
