### ISSUE TITLE
Ajax suport in CakePHP like Rails does

### ISSUE THREAD

**Issue by AndreLZGava** [cakephp/cakephp#11664]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: Linux, Postgres

### What you did
I would like to do Ajax in CakePHP like Rails does, there is so simple to do, like a in a form or a link just adding remote: true, then I tried to make something to work very close to Rails, I developed a javascript function that search for elements that has remote=1 then manipulate them to execute an ajax when submiting, or clicking on it. I almost got it, my links are working very close, in my controller/action I did:

```php
        if(!$this->request->params['isAjax'] && !$this->request->is['Ajax'] ){

            $this->render('form');
        
        }else{
            $this->viewBuilder()->layout(false);
            $this->render('_form');
        }
```

if request is patch post or put (even if in ajax, (form submit)) I verify afeter $this->Flash....

```php
                if(!$this->request->params['isAjax']){
                    return $this->redirect(['action' => 'index']); // normal request
                }else{
                    $this->viewBuilder()->layout(false);
                    $this->render('_index');  //should load index ou could be show
                }
```

But when I submit form this is goig back to form, and no a normal form its looking for ajax/_form, I created but if I tried to load the page for the first time, dont work, Its forcing me to have 2 diferents _form one in root template and other inside ajax dir. And I'm not being able to manage diferent  requests tipes (HTML/Ajax/Json, always have to manage in diferent routes, this become a mess).

### What happened
When I tried to create functions to be ease to manage Ajax requests, this is not working properlly 

### What you expected to happen
I'd like to put in my link or form remote=> true, and then manage this diferent requests  and data in my controller, without create a lot of elements, folders and files, I'd like to be able to call different partials and render them witjout problems.

**Comment by dereuromark** [comment]
You might want to look into [Ajax plugin](https://github.com/dereuromark/cakephp-ajax) and the linked sandbox examples. It goes a bit in the direction you mentioned.
After all, this is something that might have to stay more an opt-in kind of project or plugin specific solution probably.

**Comment by markstory** [comment]
Have you tried using the [RequestHandlerComponent](https://book.cakephp.org/3.0/en/controllers/components/request-handling.html) and [AjaxView](https://github.com/cakephp/cakephp/blob/master/src/View/AjaxView.php)? They should help with automatically switching the layout to the 'ajax' layout allowing you to render view templates with no wrapping layout.

Do you have a link to the rails docs, or example code of how you would like to see this working?

**Comment by AndreLZGava** [comment]
Hello @markstory I will try again this today with this tips that you guys gave me, and yes I have an example of how rails work to make a really ease ajax development, you can downdload this project https://github.com/AndreLZGava/demo this is a very simple project demonstrating of how to make ajax in rails, I just have done a scaffold (bake) in books and made some changes to make work with ajax and this was "ready" in functionallity in just 30 minutes. If you have any explanation feel free to ask how this works :D

**Comment by markstory** [comment]
@AndreLZGava I took a look at the sample app you posted. If I'm understanding your demo app the ajax behavior you'd like to see comes from the `.js.erb` support that rails has?

**Comment by AndreLZGava** [comment]
@markstory not actually, I'd like to put in my link helper a 'remote' => true , this will automatically become a ajax link, then when clicked this will search for a file (no matter extension js.ctp, .ctp etc) that has a javascript function (that renders a part of HTML) in this case a form, then when I fill all inputs and submit I could have a different treatment for every response in my controller action. If is ajax do this, if its a normal submit (post/put etc) do that.

$this->Html->link(__('Editar {0}', ['teste']), ['action' => 'edit', $instituicao->id], ['class' => 'btn btn-add pull-right', 'remote' => true]);

How I did until now, I developed a js function that search for links and forms that has a $('[remote=1]'), if its a link this will remove href, and will insert in the element a function (onclick="") passing a url (href) into it, same happens to form but form also receives its values, $(element).serialize(). This is how I'm trying to do so

function substituteForRemotes(){
    var remotes = $('[remote=1]');

    for (var i = remotes.length - 1; i >= 0; i--) {
        if($(remotes[i]).is('a, a *')){
            var href = $(remotes[i]).attr("href");
            $(remotes[i]).removeAttr("href");
            $($(remotes[i])).attr('onclick', "doAjax('"+href+"')");
        }
        if($(remotes[i]).is('form, form *')){
            var action = $(remotes[i]).attr("action");
            $(remotes[i]).removeAttr("action");
            $($(remotes[i])).attr('onsubmit', "event.preventDefault();formAjax(this, '"+action+"');");
        }
    }
}

function formAjax(element, acao){
    doAjax(acao, $(element).serialize(), 'POST');
    loadPage();
}

function doAjax(url, data, action = "GET"){
    $.ajax({
      url: url,
      data: data,
      type: action
    }).done(function(msg){
        $('.main-footer').append(msg); // I need to insert the functions inside html page so I did this way.
        ajaxOk();
    }).fail(function(){console.log("Ocorreu algum erro ao processar o Ajax!")});
}

I defined that every file that may have a js function to do ajax this way should be named with an undescore in front of name link _form.ctp, _index.ctp, these just for manipulate a js function that usually will create a element php. In my file that contain my js I developed this way:

<script>
    function ajaxOk(){
        $(".instituicaos").hide('slow', function(){
            element = '<?php echo preg_replace( '/\r|\n/', '', $this->render('form')); ?>';
            $(".instituicaos").html(element).show('slow');
            aplicaPadroesAoAjaxOuDocumentoPronto();
        });
    };
</script>

When ajax ready this will call this view (_form.ctp) then my .instituicao div will receive value from a view form (form has the same value of edit/add .ctp, the form will be inserted in .instituicaos), untill here everithing is ok. but in my controller/ action I have this:

    public function edit($id = null)
    {
        $instituicao = $this->Instituicaos->get($id, [
            'contain' => []
        ]);
//don't know how to make it works fine, because, I'm not beeing able to anipulate multiples requisitions, If this had suport like rails does, I think it would be so easilly to do ajax. what is happening when I post my rendered form is that it loads form again, but cake is searching for a ajax/_form but this may search just form _form, if something whent wrong and _index if gone right.
        if ($this->request->is(['patch', 'post', 'put'])) {
            $instituicao = $this->Instituicaos->patchEntity($instituicao, $this->request->getData());
            if ($this->Instituicaos->save($instituicao)) {
                $this->Flash->success(__('instituicao foi salvo com sucesso.'));
                if(!$this->request->params['isAjax']){
                    return $this->redirect(['action' => 'index']);
                }else{
                    $this->viewBuilder()->layout(false);
                    $this->render('_index');
                }
            }
            $this->Flash->error(__('instituicao não pode ser salvo. Por favor, tente novamente.'));
        }


        $tipos = $this->Instituicaos->Tipos->tipos($this->modelClass);
        $this->set(compact('instituicao', 'tipos'));
        $this->set('_serialize', ['instituicao']);
//I need to see if its ajax render one else another
        if(!$this->request->params['isAjax'] && !$this->request->is['get'] ){

            $this->render('form');
        
        }else{
            $this->viewBuilder()->layout(false);
            $this->render('_form');
        }
    }


Its almost how rails does, its not in the best pattern but trying to make work, if this works I wouldn't need to create a ajax function for every request that I had to do, just add 'remtoe => true and create a _file.ctp(JS) that call my "partial" file.ctp (HTML)

**Comment by markstory** [comment]
> when clicked this will search for a file (no matter extension js.ctp, .ctp etc) that has a javascript function (that renders a part of HTML) 

Generating blocks of javascript from PHP is very similar to the JS ERB workflow in rails. I've personally found that workflow resulting in very hard to maintain projects. I'm not overly keen on supporting that in CakePHP as I don't want to be responsible for maintaining it.

However, it sounds like you could factor out a helper & component that allow you to get the workflow you're looking for without having to write duplicate code in each controller.

**Comment by AndreLZGava** [comment]
Thanks for your advice and tips, I did it work by myself, If one day you guys think that it would be great to improve in cake, you have my vote :)
