### ISSUE TITLE
Plugin paths are wrong for vendor prefixed app plugins.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#11673]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11

### What you did

1. Created a new app:

```
composer create-project cakephp/app
```

2. Baked a plugin:

```
bin/cake bake plugin Foo/Bar
```

3. Added `Plugin::loadAll()` (instead of `Plugin::load('Foo/Bar')`) to the `bootstrap.php`.

### What happened
My `Foo/Bar` plugin does not get recognized by `Plugin::loaded()`.

It shows:
```php
[
     "Bake",
     "DebugKit",
     "Foo", // should be "Foo/Bar"
     "Migrations",
     "WyriHaximus/TwigView",
]
```

My `vendor/cakephp-plugins.php` looks like this:

```php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Foo' => $baseDir . '/plugins/Foo/', //wrong!
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'WyriHaximus/TwigView' => $baseDir . '/vendor/wyrihaximus/twig-view/'
    ]
];
```

### What you expected to happen

I expect CakePHP to recognize my vendor prefixed plugin correctly.

File `vendor/cakephp-plugins.php` should look like this:

```php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Foo/Bar' => $baseDir . '/plugins/Foo/Bar/', // here!
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'WyriHaximus/TwigView' => $baseDir . '/vendor/wyrihaximus/twig-view/'
    ]
];
```

**Comment by ADmad** [comment]
`vendor/cakephp-plugins.php` is generated by the [plugin installer](https://github.com/cakephp/plugin-installer) so this issue needs to be moved there.

Also plugin installer has never supported vendor prefixed app plugins. So this would be an enhancement not a defect.

**Comment by ADmad** [comment]
This issue was moved to cakephp/plugin-installer#37
