### ISSUE TITLE
Paginator numbers options first and last don't work like expected

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#11674]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.10
* Platform and Target: Ubuntu 17.10 - Nginx 1.12.1 - PHP 7.1.11

### What you did
    <?= $this->Paginator->numbers(['modulus' => 4, 'prev' => '<', 'next' => '>', 'first' => 1, 'last' => 1]) ?>

### What happened

This is the generated code for the last param

`<li class="page-item"><a href="/catalogue?page=247" class="page-link">1</a></li>`

### What you expected to happen

The page number should be the last aka 247, not 1 like the doc say about it, Whether you want first links generated, set to an integer to define the number of ‘first’ links to generate. 

`<li class="page-item"><a href="/catalogue?page=247" class="page-link">247</a></li>`

### Possible fix

`if (is_int($last) && $params['page'] <= $lower) {`

[https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L1090](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L1090)

`if (is_int($options['last']) && $params['page'] <= $lower) {`

The same goes for the first function 

`if (is_int($first) && $params['page'] >= $first) {`

[https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L1029](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L1029)

`if (is_int($options['first']) && $params['page'] >= $first) {`

**Comment by dereuromark** [comment]
Isn't that related to https://github.com/cakephp/cakephp/issues/11604  and what was proposed to be done there?

**Comment by Aerue** [comment]
Not related, not warning on my side.

The fix is to use $options and not $last or $first direcly because, first() and last() methods are called from _firstNumber() and _lastNumber()

`$out .= $this->first($offset, $options);`

Here $offset is always a string and not my number,

`$offset = ($start <= $first) ? $start - 1 : $options['first'];`

**Comment by markstory** [comment]
There is an existing test covering the `last` option working correctly when it gets an integer https://github.com/cakephp/cakephp/blob/6e1db3599d59745c1ec7d55c84f0064fe11da855/tests/TestCase/View/Helper/PaginatorHelperTest.php#L1542-L1568

I wonder what is different about your situation.

**Comment by Aerue** [comment]
Retested from clean source and the problem is located with the following plugin.

> https://github.com/Holt59/cakephp3-bootstrap-helpers

Method _lastNumber() is called with exactly the same params from this plugin, i restested without the plugin and the method output don't produce the same result. I gonna investigate more to confirm the issue.

**Comment by Aerue** [comment]
I've confirmed the issue from the plugin, 

https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/src/View/Helper/EasyIconTrait.php#L55
