### ISSUE TITLE
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /app/vendor/cakephp/cakephp/src/I18n/functions.php

### ISSUE THREAD

**Issue by salines** [cakephp/cakephp#11681]
After update  cakephp to 3.5.11

`Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /app/vendor/cakephp/cakephp/src/I18n/functions.php`

many methods Arguments have 3 dots `...$args`

**Comment by dereuromark** [comment]
Please see https://wiki.php.net/rfc/variadics
and the required min PHP version as defined in https://github.com/cakephp/cakephp/blob/master/composer.json#L31
So as long as you pull it properly as composer dependency, it will notify you about your invalid PHP setup.

**Comment by markstory** [comment]
You need to have at least PHP 5.6 to use 3.5
