### ISSUE TITLE
RFC - Plugin Classes

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#11687]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

This is a formalization of #11564 that is aiming to get additional feedback and ideas before the API is finalized.

## Problem

Plugins have no central/single place to define their behavior around bootstrapping, routes and CLI commands. We rely on plugin users to copy the correct `Plugin::load()` call from plugin README files resulting in an error prone process.

With the creation of the `Application` classes the differences between applications and plugins has grown more visible. Plugins initialization has no easy way to leverage command classes, and aliased commands. Furthermore, it will be very difficult to amend plugins to use a dependency container in the future as plugins are created from snippet files and global statics.

## Goals of the Solution

The new plugin initialization should aim to solve the above problems, and have the following properties:

* Should work well with the `Application` class and be compatible with DI containers defined in the application, or by CakePHP in the future.
* Should avoid adding new global static features.
* Backwards compatibility with `Plugin` methods. This 'facade' class is a useful shortcut for accessing which plugins are loaded.
* Enable loading plugins with a single method call.
* Allow plugins to load configuration, routes, add console commands, and middleware automatically.
* Allow application developers to disable all of the above and handle those resource types manually.

## Plugin App Classes

Encapsulating the default behavior of a plugin can be supported by creating plugin 'application' classes. Plugin app classes can be added to the host application via a inside its `bootstrap()` hook.

Plugin classes can define the following hook methods:

* `bootstrap()` Load plugin configuration, constants and global event listeners.  Called after application bootstrapping is complete.
* `console(CommandCollection $commands)` Add console commands for the plugin.  Called after application commands are added to the CommandCollection.
* `middleware(MiddlewareStack $middleware)` Add middleware for the plugin.  Called after the application middleware hook is called.
* `routes(RouterBuilder $routes)` Define routes for the plugin. Called after the  application routes have been defined.

By implementing any of these hook methods, a plugin will have them automatically invoked by the application at the appropriate time.

## Loading Plugins

Plugins are added into the application during the application `bootstrap()`. You can load plugins by object, or classname:

```php
// In Application::bootstrap()

// By classname - Accepts all defaults.
$this->addPlugin(ExamplePlugin::class)

// By object, allows customization
$plugin = new OtherPlugin($this);
$this->addPlugin($plugin)
```

Once loaded application plugins are inserted into `Cake\Core\Plugin` for backwards compatibility. They are also added to `$application->plugins` which is a collection object similar `Cake\Console\CommandCollection` providing accessor methods and an iterator. It will also support fetching plugins that match given method support. For example plugins with routing enabled:

```php
// In the scope of an application object
foreach ($this->plugins->with('routes') as $plugin) {
    $plugin->routes($routeBuilder);
}
```

## Taking Control of Plugin Setup

The `PluginApp` base class provides a suite of configuration methods that allow the application to disable specific hooks on a plugin as needed:

```php
$plugin = new ExamplePlugin($application);

// Disable hooks
$plugin->disableRoutes();
$plugin->disableMiddleware();
$plugin->disableConsole();
$plugin->disableBootstrap();

$application->addPlugin($plugin);
```

Plugins also accept an array of options in their constructor to disable hooks:

```php
$plugin = new ExamplePlugin($this, [
    'routes' => false,
    'middleware' => false,
    'console' => false
]);
```

### Customizing Plugin Routes

Sometimes applications need to apply additional routing scopes around plugin routes, or place them higher in the routes file. After disabling automatic route loading with `disableRoutes()` a plugin's routes can be loaded in the application routes.

```php
// In Application::routes() or config/routes.php

$routes->scope('/plugs', function ($routes) {
    $routes->loadPlugin('Example');
});
```

This leverages the existing plugin route loading method on `RouteBuilder`, and the static `Plugin` class to gain access to the correct plugin and invoke it's routes hook. In 4.x the `RouteBuilder` can be provided the collection of loaded plugins.

### Questions

* Are we solving the right problems?
* What are we missing from the proposed API?
* Are there other 'hooks' that plugin classes should provide?

### Related Issues

* Improve plugin architecture #10852, #10672, #10637
* Improve plugin bootstrapping. #11184
* Command Classes require plugin classes to work comfortably #11137

**Comment by markstory** [comment]
> I was wondering if we could have a hook for attaching event listeners by the plugin. We could also have an application event manager that could act as a singleton for easier access 

@burzum Brought this up in a DM with me. I think it could work. Having the app event manager be the same instance as the global event manager might be a nice way to work towards deprecating the global static EventManager later on.

**Comment by ADmad** [comment]
On a related note I have also found need for access to event manager in middlewares.

**Comment by robertpustulka** [comment]
> a nice way to work towards deprecating the global static EventManager later on.

This is something I’d like to do as well in 4.x

**Comment by markstory** [comment]
@ADmad Do you think having `$app->getEventManager()` would help with the use cases you have? If so I think that might be a separate but related change from the plugin classes here.

**Comment by ADmad** [comment]
@markstory Yup, it would.

**Comment by dereuromark** [comment]
Also interesting: https://github.com/cakephp/bake/issues/391#issuecomment-368099030
What is recommended for plugins that require another plugin internally?

**Comment by ADmad** [comment]
Hmm.. But not sure how inter plugin dependency or a plugin loading another plugin will be handled.

**Comment by robertpustulka** [comment]
How about adding `plugins` hook to the PluginInterface? Currently the plugin class doesn’t have access to the app instance, nor the plugin collection so it would’t be possible to load a plugin in bootstrap?

**Comment by ADmad** [comment]
@robertpustulka Yup, we need either the app instance or plugin collection to be made available to plugin class to be able to handle a plugin loading another plugin.

**Comment by markstory** [comment]
We could pass the `Application` into the `bootstrap()` hook of plugins. That would allow plugins to load more dependencies and retain the application if they need to modify it in other hooks.

**Comment by saeideng** [comment]
>We could pass the Application into the bootstrap() hook of plugins.

Does this mean Plugin can change main App behavior ?

**Comment by dereuromark** [comment]
> Does this mean Plugin can change main App behavior ?

That is often times (even already now) a desired behavior.

**Comment by robertpustulka** [comment]
@markstory if a plugin had access to the application would we even need event hooks? Plugins could attach events to the app’s manager in bootstrap hook. Actually app itself could also attach events in bootstrap since it now has an event manager. That would make it even simplier to use. With app interface extending the EventDispatcherInterface having event hooks is beginning to feel a bit redundant.

**Comment by markstory** [comment]
@robertpustulka good point! I can take the event hook out now.

**Comment by markstory** [comment]
Closing as this has been implemented.
