### ISSUE TITLE
Subdomain routing improvement

### ISSUE THREAD

**Issue by LorenzoRogai** [cakephp/cakephp#11689]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11

### What you did
Tried to handle three different domains under the same application frontend/backend/api and configured the routes

### What happened
In the documentation it says that this can be done by using the _host or ->setHost
I had many repeated $routes->connect()->setHost() , one for every route

### What you expected to happen
It would be better to suggest setting this parameter globally on the scopes, so there will be one scope for every domain. It would be more clean

Edit: it doesn't work as it always pick the first / scope, it should pick the one associated to the host

Example

```php
<?php

Router::scope('/', [ '_host' => 'subdomain1.domain.com' ], function (RouteBuilder $routes) {
});

Router::scope('/', [ '_host' => 'subdomain2.domain.com' ], function (RouteBuilder $routes) {
});

Router::scope('/', [ '_host' => 'subdomain3.domain.com' ], function (RouteBuilder $routes) {
});

```

**Comment by LorenzoRogai** [comment]
This feature is already implemented for "File extension routing" that is forced with setExtensions method

It would be good also to have setHost method global

At the moment the workaround is to have a custom Router/RouterBuilder

Src\Routing\SubdomainRouter.php

```php
<?php

namespace App\Routing;

use Cake\Routing\Router;

class SubdomainRouter extends Router
{
    public static function scope($path, $params = [], $callback = null)
    {
        $builder = new SubdomainRouterBuilder(static::$_collection, '/', [], static::$_collection->extensions());
        $builder->scope($path, $params, $callback);
    }
}
```

Src\Routing\SubdomainRouterBuilder.php

```php
<?php

namespace App\Routing;

use Cake\Routing\RouteBuilder;

class SubdomainRouterBuilder extends RouteBuilder
{
    protected $_host = '';

    public function setHost($host)
    {
        $this->_host = $host;

        return $this;
    }

    public function __construct($template, $defaults = [], array $options = [])
    {
        return parent::__construct($template, $defaults, $options);
    }

    public function connect($route, array $defaults = [], array $options = [])
    {
        if (empty($options['_host']) && $this->_host != '') {
            $options['_host'] = $this->_host;
        }

        return parent::connect($route, $defaults, $options);
    }
}
```

And use it like so

```php
$routes->setHost('subdomain1.domain.com');

$routes->connect(..)
$routes->connect(..)

$routes->setHost('subdomain2.domain.com');

$routes->connect(..)
$routes->connect(..)

..

```

**Comment by markstory** [comment]
You have examples that use both a method on the `RouteBuilder` and as an option to `scope()`. If you had to pick only one approach which would you recommend?

**Comment by LorenzoRogai** [comment]
The first one i double checked and it didn't work well

The second one is working is fine (It works like the "File extension routing")

![image](https://user-images.githubusercontent.com/1665768/35778945-cc87ce2e-09c5-11e8-8962-f51b24be8420.png)

It would be solved by adding a forced "host" option inside the connect method if it was set globally using the setHost function in the RouterBuilder class

In this way the setHost method will become a default option for all the connected routes

**Comment by markstory** [comment]
Do a method on the RouteBuilder is how you would see this being best implemented?

**Comment by LorenzoRogai** [comment]
Probably it would be even better to have something like

Router::subdomain('subdomain1', function ()..

Like the prefix router but for subdomains in this case

**Comment by markstory** [comment]
I am trying to avoid adding more static methods to Router. Instead we are trying to add methods to RouteBuilder. We could add the subdomain () or host() method onto RouteBuilder

**Comment by LorenzoRogai** [comment]
The setHost() extended globally in the RouteBuilder is great too, i did it with a custom class in the last example and it's working fine
