### ISSUE TITLE
$registry->normalizeArray() broken 

### ISSUE THREAD

**Issue by hmic** [cakephp/cakephp#11686]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.10
* Platform and Target: any

### What you did
called $registry->normalizeArray() more than once

### What happened
resulting array got nested one step deeper with every iteration

### What you expected to happen
array beeing normalized once, stay stable afterwards

Code to reproduce and output in the gist:

https://gist.github.com/hmic/793fd42ea8c68f8ed6339497e9989830

**Comment by markstory** [comment]
Fixed in #11707

**Comment by saeideng** [comment]
>Fixed in #11707

#11708
