### ISSUE TITLE
CakePHP 3 + ORM query builder and column name escape

### ISSUE THREAD

**Issue by plugowski** [cakephp/cakephp#11696]
A've already rewrite some application from CakePHP 2 to CakePHP 3. I have some structure in database with column: key (autogenerated key-string). In mysql key is a keyword, so when I write an SQL Query I have to escape it as

`INSERT INTO table (`key`) VALUES (....)`

Unfortunately when I try to save Entity I receive an error:

`[42000][1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'key, `

That error is triggered in Cake\ORM\Table in _insert() method on that place:

```
$statement = $this->query()->insert(array_keys($data))
        ->values($data)
        ->execute();
```

Any suggestions how to avoid that situation? CakePHP version 3.5.11

**Comment by dhduc** [comment]
I encountered the same problem, then I found a solution in here: https://github.com/cakephp/cakephp/issues/6189.
Make the `quoteIdentifiers` param on `Datasources` config is `true`
