### ISSUE TITLE
Tests from browser test runner do not work when PHPUnit 5.7 is used

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#11694]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.7.
* Platform and Target: Apache, MySQL, Linux, PHPUnit 5.7.26.

### What you did
Tried to run the test in the browser URL: test.php?case=Model%2FLanguage.

### What happened
I got 404 error. 
```
2018-02-05 15:07:28 Error: [RuntimeException] (Could not find fixture manager .)
Stack Trace:
#0 /www/cakephp/2.10.7/Cake/TestSuite/CakeTestRunner.php(55): CakeTestRunner->_getFixtureManager(Array)
#1 /www/cakephp/2.10.7/Cake/TestSuite/CakeTestSuiteCommand.php(98): CakeTestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 /www/cakephp/2.10.7/Cake/TestSuite/CakeTestSuiteDispatcher.php(259): CakeTestSuiteCommand->run(Array)
#3 /www/cakephp/2.10.7/Cake/TestSuite/CakeTestSuiteDispatcher.php(96): CakeTestSuiteDispatcher->_runTestCase()
#4 /www/cakephp/2.10.7/Cake/TestSuite/CakeTestSuiteDispatcher.php(113): CakeTestSuiteDispatcher->dispatch()
#5 /www/project/www/test.php(109): CakeTestSuiteDispatcher::run()
#6 {main} - File:/www/project/app/Lib/Error/AppExceptionRenderer.php:49
```

### What you expected to happen
Test to be run without 404.

If line `'--fixture', $this->params['fixture']` is commented out in `CakeTestSuiteDispatcher:: _runTestCase()` then the test runs as usually without 404.

**Comment by dereuromark** [comment]
You already opened this: https://github.com/cakephp/cakephp/issues/11528

**Comment by bancer** [comment]
@dereuromark https://github.com/cakephp/cakephp/issues/11528 is about code coverage. This issue is about a usual unit tests without coverage.

**Comment by dereuromark** [comment]
I still feel like those are the same underlying issues from how the autoloader works in newer versions.

**Comment by bancer** [comment]
@dereuromark, you might be right. 

Changing `if (isset($arguments['fixtureManager'])) {` 
to `if (!empty($arguments['fixtureManager'])) {` 
in `CakeTestRunner::_getFixtureManager` seems to fix the problem although I am not sure whether that is the correct fix.

**Comment by dereuromark** [comment]
What is the value of that key at this point in time? That would help to decide if that's the correct fix here.

**Comment by bancer** [comment]
It is an empty string.
The value of the entire $arguments is:
```
array(
	'listGroups' => false,
	'listSuites' => false,
	'loader' => object(CakeTestLoader) {
		
	},
	'useDefaultConfiguration' => true,
	'loadedExtensions' => array(),
	'notLoadedExtensions' => array(),
	'filter' => '',
	'printer' => object(CakeHtmlReporter) {
		params => array(
			[maximum depth reached]
		)
		[protected] _buffer => ''
		[protected] _headerSent => false
		[protected] _characterSet => 'utf-8'
		[protected] column => (int) 0
		[protected] maxColumn => null
		[protected] lastTestFailed => false
		[protected] numAssertions => (int) 0
		[protected] numTests => (int) -1
		[protected] numTestsRun => (int) 0
		[protected] numTestsWidth => null
		[protected] colors => false
		[protected] debug => false
		[protected] verbose => false
		[protected] autoFlush => false
		[protected] out => null
		[protected] outTarget => null
	},
	'fixtureManager' => '',
	'testSuffixes' => array(
		(int) 0 => 'Test.php',
		(int) 1 => '.phpt'
	)
)
```

**Comment by dereuromark** [comment]
Wow, that is very strange, but your fix would indeed then work. Are you able to quickly PR this?

**Comment by bancer** [comment]
Yes, https://github.com/cakephp/cakephp/pull/11695.
