### ISSUE TITLE
WidgetRegistry is a misleading class/method name as the class is not a subclass of ObjectRegistry

### ISSUE THREAD

**Issue by raul338** [cakephp/cakephp#11697]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11
* Platform and Target: linux / internal server - nginx

### What you did
Tried to unload DateWidget from FormHelper, I'm using a [3rd party Helpers](https://github.com/Holt59/cakephp3-bootstrap-helpers). I'm trying to use html5 native datetime pickers (or polyfills).
I expected WidgetRegistry to extend ObjectRegistry, but this was not the case.

```php
// in AppView.php
$this->loadHelper('Form', [
    'className' => 'Bootstrap.Form',
    'templates' => [
        // ....
    ],
]);
$FormHelper = $this->_helpers->get('Form');
$FormHelper->widgetRegistry()->unload('datetime');
```

### What happened
```php
Error: [Error] Call to undefined method Cake\View\Widget\WidgetRegistry::unload()
```

### What you expected to happen
Be able to unload a Helper widget

Right now the workaround is to call `$this->Form->text` and change the type via javascript, but its sloppy

**Comment by markstory** [comment]
You can't unload a widget. You can remap or replace a widget with `WidgetRegistry::add()`.

**Comment by raul338** [comment]
Why not? I think it should be like the others registry. If trying to use a non-loaded widget it should throw an exception.

Anyway, I'll be using an str_replace in a custom helper.

Thanks

**Comment by markstory** [comment]
> Why not? I think it should be like the others registry. If trying to use a non-loaded widget it should throw an exception.

Because we've never had a use case for unloading widgets before. Why would you want a widget name to throw exceptions?

**Comment by raul338** [comment]
> Why would you want a widget name to throw exceptions?

The same way like using helpers
```php
// in a view
$this->Custom->myVoid();
// Error: CustomHelper not found. Create ../src/View/Helper/CustomHelper.php
```
Sure it looks super-specific. But what confused me is that as a registry, it should extend [ObjectRegistry](https://api.cakephp.org/3.5/class-Cake.Core.ObjectRegistry.html)

**Comment by markstory** [comment]
Why should it extend ObjectRegistry? We don't need most of the methods that class provides for Widgets.

**Comment by raul338** [comment]
Because the name `WidgetRegistry` implies it

**Comment by markstory** [comment]
Fair. I'll see how easy it is to rename that class and method.

**Comment by dereuromark** [comment]
> implies it

I don't see a problem with the naming - the IDE will easily tell you that with a simple glance as well.
They registries are similar, but not the same origin. That's no reason to force a rename IMO.

**Comment by markstory** [comment]
We could call it `WidgetLocator`. That name implies the same concepts and doesn't have the surprising aspect.

**Comment by raul338** [comment]
Can I try to make a PR ?
Should I keep BC? Maybe some deprecation warnings ?

**Comment by dereuromark** [comment]
For 3.next sure :)

**Comment by raul338** [comment]
PR Open
