### ISSUE TITLE
Required attribute is ignored in FormHelper's datetime widget

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#11699]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11.
* Platform and Target: ubuntu 16.04 LTS, runtime docker php 7.0-fpm, nginx.

### What you did
Render a date control with required attribute set on true.
```php
<?= $this->Form->control('date', ['type' => 'date', 'required' => true]) ?>
```

### What happened
It render the container div with the `required` class but the selects doesn't have the required attribute.
```html
<div class="input date required">
    <label>Date</label>
    <select name="date[year]">...</select>
    <select name="date[month]">...</select>
    <select name="date[day]">...</select>
</div>
```

### What you expected to happen
It should add the required attribute to each select
```html
<div class="input date required">
    <label>Date</label>
    <select name="date[year]" required="required">...</select>
    <select name="date[month]" required="required">...</select>
    <select name="date[day]" required="required">...</select>
</div>
```

I was deepening into the framework code and this small patch works for me. I was the first solutions that came out after reading the code a bit, but I didn't run any tests.

```php
<?php
    // insert after this line
    // https://github.com/cakephp/cakephp/blob/b557240fc11cdce9e60d35d4a911c01c0f28b5ee/src/View/Helper/FormHelper.php#L2436
    // 
    if (isset($options['required']) && is_array($options[$type])) {
        $options[$type]['required'] = (bool)$options['required'];
    }
?>
```

**Comment by markstory** [comment]
Pull request open now.
