### ISSUE TITLE
CakePHP 3.x Paginator Component Datasource missing range start and end keys

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#11707]
I am fetching paginated data with Json API request from latest 3.5..

I added paging params so I can use them on a react native app..

    public function index()
    {
        $visits = $this->paginate($this->Visits);
        $paging = $this->request->getParam('paging');
        $results = [
            'visits' => $visits,
            'paging' => $paging,
        ];
        $this->set(compact('results'));
        $this->set('_serialize', 'results');
    }

But $this->request->getParam('paging'); doesn't set "start" and "end" metadata, like: (starting on record 21, ending on 40)

{{start}} - number of the first record being displayed.
{{end}} - number of the last record being displayed.

this code from the paginator helper could be implemented with minimal changes to paginator datasource:
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L689-L696

    Datasource\Paginator.php

    public function paginate($object, array $params = [], array $settings = [])
    ......

        $start = 0;
        if ($count >= 1) {
            $start = (($page - 1) * $limit) + 1;
        }

        $end = $start + $limit - 1;
        if ($count < $end) {
            $end = $count;
        }

        $paging = [
            ........
            'start' => $start,
            'end' => $end,
            ........
        ];

Thanks,

Andras

**Comment by dereuromark** [comment]
If you have a code change proposition, the easiest way would be as pull request including a few unit tests.
From your code example it is not so easy to grasp the change and potential test fails.

**Comment by dereuromark** [comment]
@andraskende ping

**Comment by andraskende** [comment]
@dereuromark 
I'm not good with unit tests, also didn't found any unit tests for "start" and "end" in PaginatorHelper tests... 

So basically the the "start" and "end" is already implemented in the PaginatorHelper.
Just needs to be copied from the View/Helper/PaginatorHelper.php to Datasource\Paginator.php
See selected part:
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L689-L696
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L712-L713

Thanks,
Andras

**Comment by dereuromark** [comment]
PR now open. Thank you for bringing this to our attention.
