### ISSUE TITLE
Validate if a cookie can be decrypted or not

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#11714]
This is a (multiple allowed):

* [X] enhancement
* CakePHP Version: 3.4.13 (happens the same at 3.5.x
* Platform and Target: Localhost and AWS server

### What you did
Basicly, I had some cookies that were not encrypted. I've pass them as encrypted. Yet, all the users that maintain the non-encrypted cookies, will find 500 errors on the platform (The data to decrypt cannot be empty. )

### What happened
Error saying: The data to decrypt cannot be empty. 

### What you expected to happen
The idea of this enhancement is to add a configuration option (or at least a try-catch, or something like that). If the platform is looking for encrypted cookies, and, that cookie, by some reason, is not encrypted, allow the core to delete it (or at least fail on "check")

The problem right now is that I have thousands of users with a non encrypted cookie, and I can't change it to encrypted because if I change code, it will give them all a 500 error. Tried all functions (read, check, delete), and they all fail.

Thanks

**Comment by robertpustulka** [comment]
Can't you `try ... catch` in your code? Looks like your app's implementation issue if you want to turn existing not encrypted cookies into encrypted ones.

**Comment by markstory** [comment]
Closing as the proposed try/catch method lets you attempt decryption and change behavior on invalid cookie data.
