### ISSUE TITLE
REST-like calls are responded as normal requests

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#11716]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.10
* Platform and Target: Homestead 5.1 box, with PHP 7.2, Nginx, Postgresql.

### What you did
Configured a basic app with [Authentication](https://book.cakephp.org/3.0/en/controllers/components/authentication.html) and make some request from [Insomina Client](https://insomnia.rest).

The AppController snippet:

```php
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        $this->loadComponent('Security');

        $this->loadComponent('Auth');
        $this->Auth->setConfig('authenticate', [
            AuthComponent::ALL => [
                'userModel' => 'Logins',
                'finder' => 'auth'
            ],
            'Form'
        ]);

        $this->Auth->setConfig('unauthorizedRedirect', '/login');
        $this->Auth->setConfig('loginAction', '/login');
        $this->Auth->setConfig('logoutRedirect', '/login');

        if (!$this->Auth->user()) {
            $this->Auth->setConfig('authError', false);
        }

        if ($this->request->is(['ajax', 'json', 'xml'])) {
            $this->Auth->setConfig('storage', 'Memory');
            $this->Auth->setConfig('unauthorizedRedirect', false);
            $this->Auth->setConfig('loginRedirect', false);
            $this->Auth->setConfig('logoutRedirect', false);
        }
    }
```
### What happened
Response have HTTP Code 200 and body content = null

![REQUEST Sample](https://user-images.githubusercontent.com/83092/36218566-95951bd0-1193-11e8-8ddb-2db96009d02a.png)

### What you expected to happen
Response with HTTP Code 403

If I send the HTTP Header 'X-Requested-With: XMLHttpRequest' in the request, CakePHP understand the call as Ajax and then respond that with http code 403.

I think any call where 'content-type' are not hipermedia (html) can be considered API-like call, and not redirect.

**Comment by xaphalanx** [comment]
AuthComponent has a configuration value called "unauthorizedRedirect" if it is set to true and you have the X-REQUESTED-WITH header set to XMLHttpRequest you will not get redirected and get the 403 error code you are looking for. If there is a bug here to me AuthComponent should respect the config value unauthorizedRedirect even if X-REQUESTED with is not set.

**Comment by CauanCabral** [comment]
Yes @xaphalanx, I mentioned that configuration in my code. The correct value for behaviour you talk é **false**, not **true** as you say.

And the problem is exactly the AuthComponent only using response without redirecting when the request have X-REQUESTED-WITH defined with XMLHttpRequest.

My point here: RequestHandler or AuthComponent should identify a request as "API/REST/AJAX" if the request only accept non-html/hipermedia format.

**Comment by markstory** [comment]
Is the request in question coming from an authenticated user or an unauthenticated one? The `unauthorizedRedirect` only applies when the user is logged in and not allowed. Unauthenticated errors should be handled by the authentication adapter.

**Comment by CauanCabral** [comment]
Is a Unauthenticated user.

But why behaviour change based only in header 'X-Requested-With'? I think should had another reliable way to detect if a request accept or not response with redirect.

Maybe de Accept header, or content-type of the response (all non html).

**Comment by CauanCabral** [comment]
I think the problem is here: https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L383

Request of type 'ajax' aren't the only who don't want response with redirect.

**Comment by ADmad** [comment]
In the code you have shown you have only configured a `Form` authenticator. In actual usage you would have always have stateless authenticator like Basic http auth or JWT for stateless APIs. For unauthenticated request those authenticators would throw an exception which you send a 401/403 status code so you will never have a response code 200 with empty reponse body.

**Comment by CauanCabral** [comment]
You are right @ADmad.

I've tried before with that same setup but using 'Basic' authenticator and don't noticed response did correct (exception unauthorized). My fault.

Maybe we can clarify in CookBook that behaviour (for not redirect, you must enable/create a stateless authenticator)? I just doesn't know if its fit best in REST or Authentication chapter, what do you think?

**Comment by ADmad** [comment]
Well since REST is stateless it's a given that you do need a stateless authenticator for it. 🙂
But if you feel that clarification is necessary feel free to open an issue / pull request against docs repo.
