### ISSUE TITLE
Wrong negative time processing 

### ISSUE THREAD

**Issue by yark** [cakephp/cakephp#11710]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11
* Platform and Target: built-in server, PHP 5.6.20, MySQL 5.6.27

### What you did
            ->select([
                'time_total' => 'DATE_SUB(time(Results.result), INTERVAL time(s.result) HOUR_MICROSECOND)',
                'id' => 'Results.participant_id'
            ]);
will generate
`DATE_SUB(
    time(Results.result), 
    INTERVAL time(s.result) HOUR_MICROSECOND
  ) AS time_total`

### What happened
in some cases `DATE_SUB` can return negative values e.g. '-00:00:01' and PHP returns warning 

`Warning (2): DateTime::modify(): Failed to parse time string (-00:00:01) at position 6 (:): Unexpected character`

because in depth it will be something like this:
 
        $d = date_create();
        $d->modify('-00:00:01');

and negative value isn't accepted by `modify()`

### What you expected to happen
I think this case needs to be handled.

**Comment by lorenzo** [comment]
Alias the column to another name and get the result as a string. There is no way to get around that limitation in PHP.

**Comment by markstory** [comment]
I am with @lorenzo on this. What are you expecting as a result when there is negative time?

**Comment by yark** [comment]
Yes, i just want it as a string. It trying to make it DateTime because of name?

May be it's possible to handle such a situation and return string if unable to process as Date?

**Comment by lorenzo** [comment]
@yark You have a column in your database called `time_total`? That's where it is getting information from to convert it to the right type

**Comment by yark** [comment]
@lorenzo yes, i was having that column and it was confusing. Thank you. Without that column or with another alias value returned as string.
I think it is not a bug anymore :)
