### ISSUE TITLE
Toggle entity class per query

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#11715]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

```bash
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:33:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.14-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sdustinh@sdustinh:~/github/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
cakephp/bake                1.6.0  Bake plugin for CakePHP 3
cakephp/cakephp             3.5.11 The CakePHP framework
cakephp/cakephp-codesniffer 3.0.3  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.4  A simple API extension for DateTime.
cakephp/debug_kit           3.11.6 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.7.2  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.1.0  A composer installer for CakePHP 3.0+ plugins.
```

It would be really handy to change the entity class per query. There are many times where I have a table that stores records that share many properties but their use in the rest of the application is very distinct. There are many places where I have to do checks against the data on the entity when it would be really great to typehint a specific entity.

```php
// Entities
class Device extends Entity {}
class ServerDevice extends Device {
    public function getSwitch(): SwitchDevice;
}
class SwitchDevice extends Device {
    public function getSnmpCredentials();
}

// Table
class DevicesTable extends Table
{
    public function findServers(Query $query)
    {
        return $query->setEntityClass(ServerDevice::class)->where(['Devices.type' => 'servers']);
    }
    
    public function findSwitches(Query $query)
    {
        return $query->setEntityClass(SwitchDevice::class)->where(['Devices.type' => 'switches']);
    }

    public function getSwitch($primaryKey, array $options = [])
    {
        $options['entityClass'] = SwitchDevice::class;

        return $this->get($primaryKey, $options);
    }
}

// Query
$servers = $this->Devices->find('servers');
$switches = $this->Devices->find('switches');
$switch = $this->Devices->getSwitch(1);

// Example application code
// Before
public function getSnmpCredentials(Device $device)
{
    $switchDevices = ['switch', 'topOfRack', 'border', 'distribution'];
    
    if (in_array($device->get('type'), $switchDevices) === false) {
        return null;
    }

    return  $this->association('DeviceSnmpCredentials')->find()
        ->where(['DeviceSnmpCredentials.device_id' => $device->get('id')])
        ->first();
}

// After
public function getSnmpCredentials(SwitchDevice $device)
{
    return  $this->association('DeviceSnmpCredentials')->find()
        ->where(['DeviceSnmpCredentials.device_id' => $device->get('id')])
        ->first();
}
```

This may seem like a trivial change because of how small the checks are, but considering the size of the application this code adds up. In addition to application code, it makes testing the `Device` entity a little cumbersome when you have a mix of methods that only apply to a specific type of record.

Another point that it would be super helpful to toggle the entity class per query would be something like authentication where I want the same data perhaps formatted in a very specific way that would make the `find('auth')` way too complicated.

```php
// Entity
class User extends Entity {}
class AuthUser extends User {
    public function hasPermission($type)
    {
        return false;
    }
    protected function _setRoles($roles)
    {
        return collection($roles)->combine('id', 'slug')->toArray();
    }
}
class InternalUser extends AuthUser {
    public function hasPermission($type)
    {
        return true;
    }
}
class ApiUser extends AuthUser {
    public function hasPermission($type)
    {
        return ($type === 'api');
    }
}

// Table
class UsersTable extends Table
{
    public function findAuth(Query $query)
    {
        return $query
            ->setEntityClass(AuthUser::class)
            ->contain(['UserRoles']);
    }
}
```

I understand that this can be done in `Model.beforeFind` by manipulating the data returned or even wrapping the query with a `$table->setEntityClass()` toggle but that doesn't really scale. Plus, you could not toggle the entity class on associations:

```php
// ProductTypesTable.php
public function findHardDrives(Query $query)
{
    return $query
        ->setEntityClass(HardDriveProductType::class)
        ->contain('Products', function ($query) {
            return $query->find('hardDrives');
        });
}

// ProductsTable.php
public function findHardDrives(Query $query)
{
    return $query
        ->setEntityClass(HardDriveProduct::class)
        ->where(['Products.type IN' => ['hdd', 'ssd']]);
}
```

**Comment by markstory** [comment]
This sounds similar to other mapping strategies like Single Table Inheritance. Have you looked at the existing [sti plugin](https://github.com/UseMuffin/Sti)?

**Comment by sdustinh** [comment]
I had seen that but unfortunately it isn't as robust as I was hoping. It works for simple string comparison but breaks down when you want to toggle entities based on foreign key, more advanced conditions, or even when you want to disable the custom entity (similar to enable / disable hydration).

Attaching the entity declaration to a query would allow significantly more flexibility when accessing and manipulating data after it has been pulled from the table. I haven't looked at the actual marshaller code but I have to assume it would perform much better if data isn't put into an entity only to repeat the process moments later.

I also explored the idea of putting methods on the entity that would construct new entities based on conditions but that got really messy and ended up having a ton of support code.

**Comment by ADmad** [comment]
There's another STI implement too https://github.com/robertpustulka/cakephp-table-inheritance

**Comment by josegonzalez** [comment]
I guess the goal here would be to either:

- bring an STI implementation into the core in some form
- adopt a plugin as an official implementation

@sdustinh can you look into the second implementation and see if it jives more with what you are looking for?

**Comment by robertpustulka** [comment]
@ADmad you linked to my fork, the main repo is here: https://github.com/robotusers/cakephp-table-inheritance

**Comment by dereuromark** [comment]
Closing then as the plugin solutions are acceptable at this point.
