### ISSUE TITLE
UrlHelper Plugin Urls with custom cssBaseUrl's

### ISSUE THREAD

**Issue by jojomartius** [cakephp/cakephp#11717]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
I changed my cssBaseUrl and jsBaseUrl in my local app.php from css/js to styles/scripts, no debug kit is not displayed anymore.

### What happened
Seems like the URLHelper is building the style url's based on the values from the config file, but since this effecting the plugin, that doesnt know about it (and its installed via composer, so i can't really change it) and it tries to load (debug_kit/scripts/...) and so on. ### What you expected to happen.

EXPLAIN WHAT IS TO BE EXPECTED, HERE.

Changes in app.php should not effect plugins url building.

**Comment by markstory** [comment]
Closing as this is being fixed in debug kit.
