### ISSUE TITLE
Allow FormHelper/SecurityComponent to support multiple file input

### ISSUE THREAD

**Issue by lilHermit** [cakephp/cakephp#11720]
Currently if you do 

```
        echo $this->Form->control('photo[]', [
            'type' => 'file',
            'id' => 'photo',
            'label' => 'Upload photo of the issue',
            'accept' => 'image/*',
            'multiple'
        ]);
```

You get a security exception due to the variable nature of the field. Messages like

```
Unexpected field 'photo.0.error' in POST data, Unexpected field 'photo.0.name' in POST data, Unexpected field 'photo.0.size' in POST data, Unexpected field 'photo.0.tmp_name' in POST data, Unexpected field 'photo.0.type' in POST data, Unexpected field 'photo.1.error' in POST data, Unexpected field 'photo.1.name' in POST data, Unexpected field 'photo.1.size' in POST data, Unexpected field 'photo.1.tmp_name' in POST data, Unexpected field 'photo.1.type' in POST data, 
Missing field 'photo.name, photo.type, photo.tmp_name, photo.error, photo.size' in POST data
```

It's not easily solved either with unlockField because if it you do

```
$this->Form->unlockField('photo.0');
$this->Form->unlockField('photo.1');
$this->Form->unlockField('photo.2');
// ... etc
```

You still get "Missing field 'photo.name, photo.type, photo.tmp_name, photo.error, photo.size' in POST data"

**Comment by LubosRemplik** [comment]
+1

**Comment by markstory** [comment]
Odd. This should work. I know there are some existing tests for file inputs.

**Comment by lilHermit** [comment]
@markstory I don't see any file input/control tests in `tests/TestCase/Controller/Component/SecurityComponentTest.php`

**Comment by LubosRemplik** [comment]
Also, not sure if related, but when I use multiple file input and select more images I am getting `CSRF token mismatch.` exception. It is fine with few files, but when I try to upload more than 10 this appears.

**Comment by markstory** [comment]
@lilHermit I was thinking of tests like this https://github.com/cakephp/cakephp/blob/e7935c97d32ca29ccdd48f6d9a8e3679c67c9325/tests/TestCase/View/Helper/FormHelperTest.php#L2259-L2270

Instead of `upload[]` have you tried numbered indexes? eg. `upload.0`? The `[]` element is hard to generate token fields for as we don't currently track the number of times a field is used.

**Comment by saeideng** [comment]
```php
<?php
echo $this->Form->create('',['type' => 'file']);
echo $this->Form->control('photo.0', [
            'type' => 'file',
            'id' => 'photo',
            'label' => 'Upload photo of the issue',
            'accept' => 'image/*',
            'multiple'
        ]);
echo $this->Form->button('Add');
echo $this->Form->end();
```
this works for me
but `echo $this->Form->control('photo[]', [` no

**Comment by lilHermit** [comment]
@markstory using `'photo.0'` you only get the first file in the multiple select. I'd like to avoid adding multiple file fields as this over complicates the UI, as I have to show/hide the others. It also negates the point of the `multiple` attribute.

**Comment by lilHermit** [comment]
@saeideng You only get the first file of the multiple select in your example

**Comment by lilHermit** [comment]
Having dug though the code the `photo[]` is removed for `photo.name` `photo.error` etc I wonder if we could/should change this so it uses `photo.{n}.name` `photo.{n}.error` in the token generation. Then when validating the token we replace any match `photo.0.name` `photo.0.error`, `photo.1.name` `photo.1.error` fields to `photo.{n}.name` and `photo.{n}.error`.

Currently rather than disabling `postValidate` for the whole request I'm using `'secure' => false` in the control options

**Comment by markstory** [comment]
@lilHermit Good point about the sub-optimal user experience. Securing 'n' inputs when we don't know how many there will be has always been a challenge as we don't have all the inputs to generate a checksum.

Using the `{n}` placeholder could work. Would that token be added when multiple option is used?

**Comment by lilHermit** [comment]
@markstory Yeah I'd suggest only add `{n}` when `'type' => 'file'` and `multiple` 

I agree securing/not-securing 'n' inputs is always going to be an issue however any tampering of "file" inputs should be dealt with by PHP. I always try to use `ServerRequest::getUploadedFile()` to further mitigate it.

I'm happy to create a PR and we can discuss from there.

**Comment by markstory** [comment]
> I'm happy to create a PR and we can discuss from there.

:+1: sounds good.

**Comment by markstory** [comment]
I took a look at this, and it doesn't appear to have a simple fix.

The multiple file input request data ends up with a structure like `images.0.name`, `images.0.error` etc. Accepting digit wildcards mid-field could end up compromising other fields that contain similar input name patterns. SecurityComponent lacks the necessary context to judge whether or not a field came from a multi-file input or any other kind of multiple inputs that are shaped in a similar way.

I think our best option for now is to continue marking multi-file inputs as `secure => false` and relying on `getUploadedFiles()` to do the required lifting.

**Comment by assunluis80** [comment]
Please correct this. :)

**Comment by markstory** [comment]
@assunluis80 We'd appreciate any help on this. I don't personally use multiple file uploads so it might be a while before I end up looking at this.

**Comment by lbassuncao** [comment]
I will be taking a look at this as soon as I can.
