### ISSUE TITLE
CSRF protection fail in stateless (rest) context

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#11723]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.
* Platform and Target: RESTful API.

### What you did
Had loaded `CsrfProtectionMiddleware` in my application and tried to make POST/PUT calls to a resource endpoint.

My `Application.php` middlware configuration:

```php
    public function middleware($middlewareQueue)
    {
        $headers = new SecurityHeadersMiddleware();
        $headers
            ->setCrossDomainPolicy()
            ->setReferrerPolicy()
            ->setXFrameOptions()
            ->setXssProtection()
            ->noOpen()
            ->noSniff();

        $cookies = new EncryptedCookieMiddleware(['protected'], Configure::read('Security.cookieKey'));

        $middlewareQueue
            ->add(ErrorHandlerMiddleware::class)

            ->add($headers)

            ->add($cookies)

            ->add(AssetMiddleware::class)

            ->add(CsrfProtectionMiddleware::class)

            ->add(new RoutingMiddleware($this));

        return $middlewareQueue;
    }
```

### What happened
Response missing CSRF token.

```json
{
	"message": "CSRF token mismatch.",
	"url": "\/users",
	"error": {},
	"code": 403
}
```

### What you expected to happen
In stateless context, I can't figure a way to store a CSRF token and send it in next requests - as I do in browser context.

I know I can set scopes to delimit CsrfMiddleware, but I'd like to have a RESTful compliant application at the same time that is accessible via browser. There's a way without disabling totally the middleware?

That discussion make me to open this issue: https://security.stackexchange.com/questions/166724/should-i-use-csrf-protection-on-rest-api-endpoints

**Comment by markstory** [comment]
Are you sending both the cookie/header and request data?

**Comment by CauanCabral** [comment]
What header you mean?

I know I can send a cookie with my request, but a don't want that. As in the discussion I mentioned, I think CSRF protection is "useless".

I thought about it for a time and probably the solution for that is a way to know if a specific request are actually a RESTful call or not. But I don't know how to make that without opening a 'backdoor' for any request.

**Comment by markstory** [comment]
You can send the `x-csrf-token` header and it works the same as the cookie value.

I agree that csrf is less necessary for rest APIs. I also agree that disabling csrf automatically is not a safe plan. I think the best plan would be to use routing scopes or subclass/wrap the csrf middleware and selectively disable it base in other request parameters.

**Comment by CauanCabral** [comment]
I agree @markstory and will close the issue.

The solution is application specific.

Thanks again.
