### ISSUE TITLE
[2.x] afterDispatch does not work when using testAction()

### ISSUE THREAD

**Issue by dmnlk** [cakephp/cakephp#11728]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
CakePHP Version: 2.10.7
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
Creating a class that extends DispatchFilter and running the test with the testAction method will not execute the afterDispatch method.
However, because the default option of testAction is set with 'return' => 'result', I took time to figure out why this problem occurred.

If the request parameter contains return, dispatcher immediately returns the response.
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Routing/Dispatcher.php#L168

Since afterDispatch is executed only when it is not return, the default option of testAction prevents afterDispatch from being executed.
This problem occurs because the return parameter is attached to the request parameter only when the return option is result.
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/TestSuite/ControllerTestCase.php#L289

### What happened
The workaround for this problem is to specify 'return' => 'vars' in the argument option of testAction,

### What you expected to happen
afterDispatch should be executed correctly

**Comment by josegonzalez** [comment]
@dmnlk do you have a small reproduction of the issue that we can use to verify that this is the case/build a regression test from?

**Comment by tenkoma** [comment]
@josegonzalez
dmnlk is my colleague. 
I will submit a reproduction code as follows on his behalf.

```php
<?php
// app/Routing/Filter/SampleFilter.php (add)
App::uses('DispatcherFilter', 'Routing');

class SampleFilter extends DispatcherFilter {
	public function afterDispatch(CakeEvent $event) {
		debug('Fire after dispatch!');
	}
}
```
```php
<?php
// app/Test/Case/Controller/PagesControllerTest.php (add)
class PagesControllerTest extends ControllerTestCase {
	public function testDisplayWithAfterDispatch() {
		$this->testAction('/', array('return' => 'vars'));
	}

	public function testDisplayWithoutAfterDispatch() {
		$this->testAction('/');
	}
}
```

```php
// app/Config/bootstrap.php (modify)

// ... snip
Configure::write('Dispatcher.filters', array(
	'SampleFilter', // <- add
	'AssetDispatcher',
	'CacheDispatcher'
));
// ... snip
```

```console
$ composer require --dev phpunit/phpunit:"3.7.*"
// ... snip
$ app/Console/cake test app Controller/PagesController --debug

Welcome to CakePHP v2.10.7 Console
---------------------------------------------------------------
App : app
Path: /Users/foo/src/github.com/cakephp/cakephp/app/
---------------------------------------------------------------
CakePHP Test Shell
---------------------------------------------------------------
PHPUnit 3.7.38 by Sebastian Bergmann.


Starting test 'PagesControllerTest::testDisplayWithAfterDispatch'.
./app/Routing/Filter/SampleFilter.php (line 6)
########## DEBUG ##########
'Fire after dispatch!'
###########################

Starting test 'PagesControllerTest::testDisplayWithoutAfterDispatch'.
.

Time: 71 ms, Memory: 8.00MB

OK (2 tests, 0 assertions)
```

**Comment by markstory** [comment]
I took a look and the default value for `return` has been `result` for a long time. I agree that it is not a great default value but I'm not willing to change it now as that represents a breaking change. Your work around of setting 'return' to `vars` or `contents` is how I would recommend solving this unfortunate default value.
