### ISSUE TITLE
Constants are being held onto by IntegrationTestCase

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#11724]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13 f9cd66fe071d1cfb2fa6aec94ee37a7fd0916c03
* Platform and Target: Apache/2.4.29 (Ubuntu), PHP 5.6, MySQL  Ver 14.14 Distrib 5.7.21, Ubuntu 16.04.3 LTS.

### What you did
I am using constant to set the currency and exchange rate for each request. I believe the test suite is holding onto the constant from the first request through subsequent tests.

My test:

```php
    public function testUSDtoCAD(){
		$this->post('/publisher/v3.0/book/preview.json',json_encode([
			'key' => 'removed',
			'property_id' => 1111,
			'accommodation_id' => 1303,
			'rate_code' => 'REZ',
			'checkin' => $this->checkin,
			'checkout' => $this->checkout,
                        'currency' => 'CAD',
			'rooms' => [
				['adults' => 2, 'children' => 0],
			]
		]));

		$this->assertResponseOk();
		
		$response = json_decode($this->_response->body());
		
		$accommodation = reset($response->data->property_accommodation);
		$rate = current($accommodation->rates);
        
		$this->assertEquals(258, $rate->total->nightly_avg);
		$this->assertEquals(1032.36, $rate->total->subtotal);
    }
```

Code that sets the defined constant:

```php
class ApiComponent extends Component
{
    public function setCurrency($request)
    {
        // set currency type and exchange rate
        if (isset($request->currency)) {
            $Country = \Cake\ORM\TableRegistry::get('Country');
            $country = $Country->find()->where(['currency_code' => $request->currency])->first();
            
            if ($country && !defined('__currency__')) {
                define('__currency__', $country->currency_code);
                define('__exchangeRate__', $country->usd_value);
            }
            var_dump($request->currency);
            var_dump(__currency__);
            var_dump(__exchangeRate__); die;
        }
        
        if (!isset($country) && !defined('__currency__')) {
            define('__currency__', 'USD');
            define('__exchangeRate__', 1);
        }
    }
}
```

### What happened
When I run my unit test as follows and when I use it in production it works as expected, but when I run it in the suite the constant is not getting set on each request. I believe the first request that sets it makes it stay.

Works:
```
vendor/bin/phpunit --filter testUSDtoCAD plugins/Api/tests/TestCase/Currency/
```

Keeps the default from previous requests which is USD:
```
vendor/bin/phpunit plugins/Api
```

### What you expected to happen
I don't believe this is how the integration test suite should be working. A request should be treated as a new request, no?

**Comment by cnizzardini** [comment]
Edit: I still believe this is a defect, but I am wondering if Cake\Core\Configure::write and Cake\Core\Configure::read would be a better way for me to implement this...

**Comment by josegonzalez** [comment]
I don't think this is a bug. From the [php docs](http://php.net/manual/en/language.constants.php):

> As the name suggests, that value cannot change during the execution of the script (except for magic constants, which aren't actually constants).

Thats how constants work in PHP. By default, phpunit does not run each test in isolation, so any values such as the ones you are setting will persist through requests.

**Comment by cnizzardini** [comment]
I guess so. I'll change my code Cake\Core\Configure
