### ISSUE TITLE
templateVars Bug

### ISSUE THREAD

**Issue by spacebiscuit** [cakephp/cakephp#11738]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5
* Platform and Target: WAMP

**Problem**

There appears to be an issue with the form templates not accepting some templateVars.

My app_form.php file:

```
return [
    'formGroup' => '<div class="form-control ">{{input}} {{error}} {{foobar}}</div>'
];
```

My input field:

```
$this->Form->input('delivery_types._ids', [
     'options' => $options, 
     'multiple' => 'checkbox',
     'templateVars' => [
          'error' => 'This is an error',
          'foobar' => 'This is a test'
     ]
];
```
The 'foobar' is rendered within the form group, the 'error' is not. If 'error' is renamed to anything else it will appear.

Also If I make the input type a single select by removing the 'multiple' and changing the name of the form to 'delivery_type' the {{error}} templateVar is rendered. 

Therefore it seems that  there is a problem with the index when named 'error' for multi-select inputs.

**Comment by markstory** [comment]
The `error` variable is used by FormHelper::control() to render validation errors. You cannot put your own content in that variable as it will be overwritten by the validation error or '' when there is no validation error.

**Comment by spacebiscuit** [comment]
Thank you @markstory. 

Why do we not see consistent behavor for all inputs, for example a text input will render the 'error' using my appriach?

In my case i am doing my validation in Angular so I am not relying on Cake to render the validation errors. Is there anything i can over-ride is app_form.php to work in my case. If not i can quite easily use another variable but i'm just curious to know.

**Comment by inoas** [comment]
prefix like so`_errror` or wrap like so `[error]` for 4.x?

**Comment by markstory** [comment]
> Why do we not see consistent behavor for all inputs, for example a text input will render the 'error' using my appriach?

Only control() replaces the 'error' variable. Using the input methods directly will not display validation errors and thus will not overwrite the 'error' template variable.

> Is there anything i can over-ride is app_form.php to work in my case. I

You could always re-implement the `control()` method to and make your changes there.

@inoas That is an option but I don't think the breaking change is worth it here. Prefixing `error` makes it inconsistent with the other variables that FormHelper uses.

**Comment by spacebiscuit** [comment]
Does a text input and select not also use control()?

For example:
```
<?= $this->Form->input('listing_type_id', [
     'templateVars' => [
          'error' => '<div class="error-message" ng-show="submitted || addListing.listing_type_id.$dirty && addListing.listing_type_id.$invalid"<span ng-show="addListing.listing_type_id.$error.required">Listing type must be selected</span></div>',
     ]					 
]);	?>
```
In this case I am able to over-write the error variable.

**Comment by markstory** [comment]
In that example yes `input()` is the same as `control()`. I did not previously know which method you were calling as it wasn't posted in the issue. The error option is overwritten here https://github.com/cakephp/cakephp/blob/e661cf14537cfd3385b2273bd606d318eccce196/src/View/Helper/FormHelper.php#L1119-L1129 if you're interested in digging in further.
