### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit\Framework\BaseTestListener' not found

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11732]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: latest master

### What you did
plugin development, travis is now red for newer PHP versions
```
PHP Fatal error:  Class 'PHPUnit\Framework\BaseTestListener' not found in 
/home/travis/build/dereuromark/cakephp-ide-helper/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php ...
```

See e.g. https://travis-ci.org/dereuromark/cakephp-ide-helper/jobs/343435569

This can happen if the constraint isnt locked down to PHPUnit 5|6 but also allows for 7 to be pulled.
Mainly because cakephp/cakephp only has a require-dev dependency here to PHPUnit, of course.

### What you expected to happen
Can we class alias or fix it somehow - as we did for some classes in the past? 
So PHPUnit 7 is also supported?

**Comment by markstory** [comment]
> This can happen if the constraint isnt locked down to PHPUnit 5|6 but also allows for 7 to be pulled.

So don't do that. PHPUnit 7 has a number of backwards incompatible changes that make it hard to be compatible with both PHPUnit 6 and PHPUnit 7.

**Comment by dereuromark** [comment]
OK, so we dont plan to support it anytime soon using some shims or alike? Then we can disregard.

**Comment by markstory** [comment]
> OK, so we dont plan to support it anytime soon using some shims or alike? Then we can disregard.

I think in 4.0 we can move to PHPUnit 7+.
