### ISSUE TITLE
RFC: debug() show virtual entity fields

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11733]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement

* CakePHP Version: 3.5

### What you did
debug()/dd() on $entity

### What happened
```
object(App\Model\Entity\ReleaseElement) {
	'id' => (int) 9,
	'release_group_id' => (int) 4,
	'pr' => '3069',
	'repository' => '',
	'data' => null,
	'[new]' => false,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [
		(int) 0 => 'type'
	],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'ReleaseElements'
}
```
$entity->type would be fine as it is a virtual field and would output `1`.
But its value is not listed/shown here.

### What you expected to happen
If defined as such in `protected $_virtual = ...` array, like in this case here, we could add this into the list IMO.

We just need to extend __debugInfo() afaik.
https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L1304

Any downsides here? What do other people think?

**Comment by markstory** [comment]
Seems reasonable to me.

**Comment by dereuromark** [comment]
PR open.
