### ISSUE TITLE
[RFC] Policy about how to change existing interfaces

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11735]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Non-releated

### Problems

I think we don't have policies about how to change exsiting interfaces.

Sometime we add `@method` annotations to existing interfaces (e.g. EntityInterface), and call those undeclared methods. This way seems quite dangerous to me, as it can be happend even in minor/bugfix releases, and users doesn't realize the fact until those methods are called at runtime.

At other times, we add some auxiliary interfaces (e.g. InvalidPropertyInterface) to not change existing interfaces (e.g. EntityInterface). Normally, this way allows users to extend core classes safely. But I think this way also has several problems like the following:
- We sometimes take the above `@method` ways. So now we are calling undeclared methods on InvalidPropertyInterface [like this](https://github.com/cakephp/cakephp/blob/765d9053acc86ab08790c4323deeb7cc1a0f0812/src/ORM/Marshaller.php#L189-L191).
- When people want to implement their own EntityInterface classes, they have to implement not only EntityInterface, but also InvalidPropertyInterface. 

### Suggestions

I think we have several choices to solves the above problems.

**(1) Allow to change existing interfaces in minor releases**

In this way, people cannot extend core classes safely. They may encounter some errors when they upgrade their applications to next minor releases. But they can realize those errors at compile time. I think this is far better than now (runtime errors).

**(2) Stop adding new interfaces**

In theory, interfaces should not be changed in minor releases. But we often do that. Then I think it is better to not provide any interfaces. If we didn't have EntityInterface (and had AbstractEntitty instead), we could avoid the above problems.

In this way, people can extend core classes safely as long as they don't encounter name collision.

**(3) Add derived interfaces**

For example, when we want to change EntityInterface, we should create EntityInterface2 which extends EntityInterface. We shouldn't change any signatures of existing methods. Instead, we should use `instanceof EntityInterface2` checks in those methods. In new major releases, we can remove old interfaces.

In this way, people can extend core classes safely.

Personally, I think (3) is the best way. But I am OK with any ways if we can stop adding `@method` annotations to interfaces.

**Comment by dereuromark** [comment]
(2) is not an option at all - if anything we should be using more and not less interfaces for typehinting and programming against.

As for your (1), that could be an option, if we communicate that in the migration guide and make people aware that it doesn't follow strict semver, but a flavored one.

(3) is not feasable, as it will not work with typehinting, phpstan tooling and other things.

That is why (4) we are currently doing it the "method annotation" way, the soft one, which seems to be most pragmatic for the time being.

I still opt for quicker release cycles of majors, which would quicker resolve these things, rather than years per major, and thus a lot of baggage and deadlock until each jump.

**Comment by ADmad** [comment]
To be clear `@method` annotations were added simply to mitigate errors reported by static analysis tool like phpstan. It's no an actual choice we made for how to add new methods to existing interfaces.

**Comment by dereuromark** [comment]
@ADmad Not only, also for IDE auto-complete and workability with these. This is as important as phpstan and analyzing tooling.

**Comment by chinpei215** [comment]
> (2) is not an option at all - if anything we should be using more and not less interfaces for typehinting and programming against.
 
I want to know why you think so.

> (3) is not feasable, as it will not work with typehinting, phpstan tooling and other things.

I don't think so. If you are sure that your application need not to communicate old interfaces at all, You can use `class_alias(EntityInterface, EntityInterface2)`. Then you can typehint EntityInteface instead of EntityInteface2 if you want.

> That is why (4) we are currently doing it the "method annotation" way, the soft one, which seems to be most pragmatic for the time being.

I don't understand how it helps people. For now we may suddenly call those methods in some bugfix release. Then users' applications suddenly break in the bugfix release.

**Comment by dereuromark** [comment]
> I want to know why you think so.

Basic PHP 1:1 - also refs https://github.com/cakephp/cakephp/issues/11511
We need a lot more clean interface typehinting everywhere, not the opposite direction.

> You can use class_alias(EntityInterface, EntityInterface2)

I am fairly certain this does not work with either IDEs, phpstan and other toolings and also will have other side effects. Far from a clean approach.

> For now we may suddenly call those methods

Well, they shouldnt be called then. Assert that in some way and you fix the issue here at its source instead of working around it.

The only other option, as I said, is a quicker release cycle here and a clean communicated release documentation on it.

**Comment by dereuromark** [comment]
minor releases = interface updating => minimal migration effort
sounds like a fair deal to me.

**Comment by chinpei215** [comment]
> Basic PHP 1:1 - also refs #11511

Could you please explain more clearly? I don't understand well about what `class + interface` means in #11511. It can be implemented as an abstract class. (I understand trait + interface. I don't like it though).

> I am fairly certain this does not work with either IDEs, phpstan and other toolings and also will have other side effects. Far from a clean approach.

I thought PHPStorm supports class_alias() though.

> Well, they shouldnt be called then. Assert that in some way and you fix the issue here at its source instead of working around it.

If we shouldn't call those methods, then we shouldn't add `@method` to interfaces. It helps us when we call those methods accidentally.

**Comment by dereuromark** [comment]
I do not want to explain to you why interfaces should be used and what SOLID means.
You can read on this in external sources.
Bottom line: Concrete classes should not be used to typehint or program against, and abstract classes are already a stretch. We already make a lot of exceptions here for internal "kernel" functionality, e.g. Registry classes, static Cache class and other "unlikely" to be extended classes.

> then we shouldn't add ...

The whole point of the annotations is for people to call and use them - since they are not part of the interface as they should be from the start.
So it is a solution to a problem of us not being able to properly ship those methods as they are intended to be shipped.
So no, removing them is not an option IMO. If core accidentally uses them, a sniffer or other tools are missing here instead that would prevent this. Making it less usable for people because of this sounds less ideal.

**Comment by dereuromark** [comment]
One example:

    $this->Blocks = new ViewBlock();

Here ViewBlock is not only hardcoded into the View, it is also impossible to replace, as it does not come with an interface, so you can only extend it - and that only by hacking the whole View constructor.
This is what people often times complain about in CakePHP - too much coupling internally and not following DI or open closed principle.
Use an interface here, always program against that and people are free to implement their own view block system if desired.
Sure, so far no one needed that, but doesnt mean this is clean code :)

**Comment by robertpustulka** [comment]
@chinpei215 PHP does not support multiple inheritance so interfaces are a far better way of applying polymorphism.

**Comment by chinpei215** [comment]
> I do not want to explain ...

I don't think there are any external sources about the issue we are talking about now. Who says that adding `@method` annotations to interfaces and calling them is better than using abstract classes? Such code cannot be compiled in C#, Java or any other statically typed languages.

And I am not talking about concrete classes, but abstract classes.

> So no, removing them is not an option IMO. If core accidentally uses them, a sniffer or other tools are missing here instead that would prevent this. Making it less usable for people because of this sounds less ideal.

I really don't understand why you think adding `@method` annotations is usable. Let's assume there is an interface:
```php
/**
 * @method void newMethod()
 */
interface SomeInterface {
    public function oldMethod();
}
```

What should I do when I want to implement this interface? Is newMehotd() called in the core? Then I have to implement it. But why don't you provide a complete interface which reports errors when I forgot implemenet newMethod()?
Is oldMethod() still called in the core? If no, then I don't want to implement it. Why don't you remove it from the interface?
For now, our interfaces are quite less helpful.

@robertpustulka Interfaces don't solve ambiguity problems. Even if we have LotteryInterface::draw() and AnimationInterface::draw(), you cannot implements both interfaces to develop LotteryAnimation. In such cases, people will add LotteryAnimation::getLottery() which returns LotteryInterface and LotteryAnimation::getAnimation() which returns AnimationInterface. Then this can be developed without interfaces either. 

Interface-based programming is difficult that class-based programming, as people expect that interfaces are never changed. For example, we wouldn't expect PSR-7 interface is suddenly changed. But if we often want to change our interfaces (like in 3.x selease), I think avoding interface-based programming (2) is an option. I don't say it is the best way though. As I said above, I am OK if we can stop adding `@method` annotations.

**Comment by burzum** [comment]
While I agree mostly with what @dereuromark said in this discussion @chinpei215 has a very good point as well:

> Interface-based programming is more difficult than class-based programming, as people expect that interfaces are never changed. For example, we wouldn't expect PSR-7 interface is suddenly changed. But if we often want to change our interfaces (like in 3.x releases), I think avoding interface-based programming (2) is an option.

We can't change the interfaces randomly every very month, even if we strictly go for semver. This would be like sweeping the dirt under the carpet. 

I think Angular lost a lot of user by doing this, including our company. When we re-evaluated which frontend framework to use Angular didn't made it far because they're changing to much and to often.

What I love about CakePHP is that I don't have to change a lot between releases between majors so far. IMHO a long time stability of the API is a good argument for a framework. Laravel also did a lot changes and not everybody liked it either.

So let's better spend another month in thinking about the architectural changes than doing it quickly and ending up with things we need to change in a few month.

**Comment by markstory** [comment]
> (1) Allow to change existing interfaces in minor releases

This may be our best bet if we continue to evolve our interfaces in minor releases. I agree that we need to stop doing these kinds of changes in bugfix releases. I know I will be more strict about that going forward in the future.

> (2) Stop adding new interfaces

I don't think this is going to work out well for us. Interfaces help reduce coupling application code to framework implementations. They also help make testing/mocking easier.

> (3) Add derived interfaces

How would we handle major upgrades in the example of `EntityInterface` and `EntityInterface2`? Would `EntityInterface` become deprecated leaving `EntityInterface2` in the following major release?

**Comment by chinpei215** [comment]
Thank you for your comments.

> Would EntityInterface become deprecated leaving EntityInterface2 in the following major release?

No. I explain what we should do. Lets' assume we have EntityInterface like the following:
```php
interface EntityInterface
{
    public function source();
}
```
If we want to add setSource/getSource to the interface and deprecate source() on it, we should create EntityInterface2 derived from EntityInterface:
```php
interface EntityInterface2 extends EntityInterface
{
    public function setSource($source);
    public function getSource();
}
```
We can use EntityInterface2 in the core, but we should leave all source() calls as they are:
```php
function doSomething(EntityInterface $entity) {
    if ($entity instanceof EntityInterface2) {
        $source = $entity->getSource();
    } else {
        $source = $entity->source();
    }
}
```
That is the proper interface-based programming manner. People continue to use old EntityInterface classes if they want. And if they implement new EntityInterface2, PHP compiler can tell them what methods they should implement. And they may get some advantages of new interfaces.

In a new major release, we can change EntityInterface if we want, like the follwoing:
```php
interface EntityInterface
{
    // public function source(); // This method can be removed.
    public function setSource($source);
    public function getSource();
}
```
And can remove EntityInterface2 from the core. If users want to upgrade their applications to the new major version, they need to implement new EntityInterface if they have old EntityInterface classes, or they need to replace EntityInterface2 to EntityInterface if they have new EntityInterface2 classes.

**Comment by burzum** [comment]
If we go for that fugly naming of new interfaces by adding numbers we would have to add a new page to the docs explaining our policy on that and why we do it like this.

Also this might look bad for some people. It's sometimes about marketing and not tech (see silly spaces vs tabs). I had one or two people complaining that my plugins don't use PSR but tabs and I give a shit. 😄 

But I'm pretty sure people will point their finger at CakePHP and speak bad about this, intentionally because they're fanboys of another framework or because they don't know or can't understand why we do it.

**Comment by chinpei215** [comment]
Are you sure [this interface](https://github.com/cakephp/cakephp/blob/e54c48b970aa689e6579ee4437a5f0b114c2e3c6/src/Datasource/EntityInterface.php#L26-L41) looks good? And those people never speak bad about it?

Strictly speaking, we did break backward compatibility in 3.3. If I had a class which implements EntityInterface, but not uses EntityTrait, my application would have broken in 3.3. While I don't say there were such applications in the real world, but if we start adding more interfaces and stick to `@method` ways, those problems will happen in future.

**Comment by dereuromark** [comment]
@chinpei215 Then fix the problem at its source: Allow minors to update interfaces properly, as they should be once methods are added (and not just put them into the concrete class).
That is the only reason we need the annotations. Don't complain about the annotations, complain about the actual process.
Interface programming is important, and it will always be. Not using is not an option.
Instead, as I said now multiple times, the process needs to properly reflect interface programming, thus minors should be allowed to be semver flavored in a way to account for the need of contract modifications.

**Comment by dereuromark** [comment]
Alternatively, have a quicker release cycles (3-4 months) for majors, which smaller changesets.
But that will weaken the eco system and plugins probably.
On the other side, it will more clearly communicate the compatibility of framework majors vs plugin, so it is probably a better way to go then the semver weakoning.

**Comment by burzum** [comment]
I'm against shorter major release cycles. I doubt the majority of people writes well maintained code and if you don't follow the changes of the framework you'll have a very bad day once you have to update. I think 3.4 and 3.5 will already give some people a good headache when they're coming from previous versions. 

If you go for publicity you need to please these people as well. And you won't please them but scare them away. So if you do major changes every 4 month, a project that haven't had updated for a year will have the ugly job of updating three iterations of probably bigger API changes. The cool kids might jump on that train like Laravel but if you want to run a serious and large application you won't go for the most bleeding edge but the most stable and long living / maintained lib.

 Actually I would prefer to make the API as stable as we can for as long as possible and market this as a strength of the framework. The cool kids will call CakePHP outdated as they did with 2.x but I'm sure the bigger companies loved the framework for that. I want something stable as well (oh, I think I'm getting old...). Conclusion: Let's stick to the interface plan but let's make sure they're at least triple checked and battle tested in a looong beta / RC phase of 4.0.

@chinpei215 I don't see the problem with the method annotations here, especially in context of the comment above them. The only ugly thing here is that the interface is to much. I've just discussed this with @lorenzo and we agreed on splitting the error methods up into `EntityErrorsInterface`.

**Comment by inoas** [comment]
👍 for current release speed. The pain of always being outdated that is so prevalent in npm-world does not need to be ported over to cakephp-world IMHO.

**Comment by chinpei215** [comment]
@burzum The problem is that it can break users applications even in bugfix releases. Let's assume we had the following code in 3.3.0 for example:
```php
function something(EntityInterface $entity) {
    return $entity;
}
```

This method works with even old EntityInterface in 3.3.0. So users may not realize any issues just after upgraded to 3.3.0.
But if we changes the above function like the following in 3.3.1:
```php
function something(EntityInterface $entity) {
    $source = $entity->getSource();
    return $entity;
}
```
Their applications suddenly break. Then they would get an error `Call to undefined method TheirEntity::getSource() in CORE` at runtime. That is why I said annotations are bad.

If we call some methods annotated `@method`, that means that we no longer supports old interfaces. If we are OK with that, let's add the getSource() method to the interface really, instead of annotations. (Personally, I am not OK with that. So I think (3) is the best way.)
Anyway, if we do that, users can get a error `Class TheirEntity contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (EntityInterface::getSource) in APP` at compile time in 3.3.0, not runtime in 3.3.y.

Regarding EntityErrorsInterface, I don't say it is a bad idea. The difference betweeen EntityErrorsInterface and EntityInterface2 will be:
```php
// People need to implement many interfaces.
class MyEntity implements EntityInteface, EntityErrorsInterface {}
class MyEntity implements EntityInterface2 {}
```
```php
// It is hard to write proper code.
function newFeature(EntityErrorsInterface $entity) {
    $entity->getErrors();
    $entity->getSource(); // Not proper if getSource() is not declared in EntityErrorsInterface
}
function newFeature(EntityInteface2 $entity) {
    $entity->getErrors();
    $entity->getSource(); // OK 
}
```

**Comment by burzum** [comment]
@chinpei215 it was discussed that the ORM might be promoted as standalone ORM as well, especially in this case not everybody wants to deal with errors inside entities. This has nothing to do with what you propose. The point is to split the functionality. The annotations in the case you pointed out are a intermediate solution to make IDEs and users aware that these methods will be part of this interface in 4.0.

**Comment by chinpei215** [comment]
> it was discussed that the ORM might be promoted as standalone ORM as well, especially in this case not everybody wants to deal with errors inside entities. This has nothing to do with what you propose. The point is to split the functionality. 

OK.

> The annotations in the case you pointed out are a intermediate solution to make IDEs and users aware that these methods will be part of this interface in 4.0.

Sorry, I couldn't get what you mean. Those methods have already been a part of the interface in 3.x. 
For example, we are calling those methods [here](https://github.com/cakephp/cakephp/blob/9abaeb2e02610d594c4c53fa169266099c11d146/src/ORM/Table.php#L1731). If users want to have their own EntityInterface classes, they must implement those methods even in 3.x. So I don't understand why it should be annotations.

**Comment by lorenzo** [comment]
I would prefer adding more interfaces whenever we need to add more methods to somethings. 

It is a shame that php does not support union type hints, so we would need to rely on explicit check in the methods themselves whenever we need to use them.

Luckily phpstan does support union type hint (but actually called intersection types there)

**Comment by chinpei215** [comment]
I don't oppose adding more interfaces. I do oppose improper use of interfaces [like this](https://github.com/cakephp/cakephp/blob/765d9053acc86ab08790c4323deeb7cc1a0f0812/src/ORM/Marshaller.php#L189-L191). I cannot see any good reasons of throwing runtime errors instead of compile errors here when setInvalidField() is not declared.

> It is a shame that php does not support union type hints, so we would need to rely on explicit check in the methods themselves whenever we need to use them.

I don't think it is necessary. If some type is a union of two ore more types, that means it is an another type. While PHP **class** doesn't support multiple inheritance, **interface** does support it:
```php
interface AB extends A, B {
}
```

**Comment by markstory** [comment]
> I do oppose improper use of interfaces like this.

Why is that an improper use of an interface? Isn't that a way to make interfaces optional and avoid runtime errors?

**Comment by chinpei215** [comment]
@markstory No. Becase setInvalidField() is not declared on InvalidPropertyInterface. If I have an old class which implements InvalidPropertyInterface, it will pass `instanceof InvalidPropertyInterface ` check but I will encounter runtime errors in the `if` block.

**Comment by chinpei215** [comment]
@burzum Sorry, I overlooked your message.

> @chinpei215 are there other bigger php projects that do something like that?

I don't know whether there are such **php** projects or not. But Windows COM would be the one of the most well-known library which does that.

**Comment by dereuromark** [comment]
I think we are getting better here in 4.x and moving forward, also with help of phpstan and alike.
Closing then as we take this into account for future changes.
