### ISSUE TITLE
insert into mssql issue with triggers

### ISSUE THREAD

**Issue by EliasDeVos** [cakephp/cakephp#11739]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.11

Hi,

We are using MsSql for a client together with cake3.
A table we use has a couple of triggers defined and this gives us some issues.

If we try to save a new entity (create an insert statement) we get the following statement:
`INSERT INTO SUBREIZIGERS (...) OUTPUT INSERTED.* VALUES (...)`
The problem is with the OUTPUT,
this is hardcoded in cake 3 and always gets added, see here
https://github.com/cakephp/cakephp/blob/b27ebbd6a4e9b6062bd45e13a439b7ab7f29d0af/src/Database/SqlserverCompiler.php#L73

The problem is that if you try to insert into mssql on a table with triggers you are not allowed to use output in your query.
Because this gives you the following error:
`SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The target table 'SUBREIZIGERS' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.`

I found online that we should either:

1.  remove the triggers (not an option)
2. remove the output (not possible now but this is the best way imo)
3. work with raw sql inserts (not as pretty and defeats the ORM)

Do you think we could fix this with a pull request ? maybe add an option to work with output ?

If you point me in the right direction then i would be happy to create a pull request for this

**Comment by markstory** [comment]
Without `OUTPUT` I don't think we have a reasonable way to get the last insert id. Which will make create operations involving associations challenging/impossible to implement.

**Comment by EliasDeVos** [comment]
hm @markstory do you now if there is a way to retrieve the insert query from when we would call save()  without actually running it ?
We could then modify it for our case,
This would make it atleast a bit cleaner then writing the entire query in raw sql

**Comment by markstory** [comment]
You can override the `SqlCompiler` by subclassing `Cake\Database\Driver\Sqlserver` and redefining https://github.com/cakephp/cakephp/blob/master/src/Database/Dialect/SqlserverDialectTrait.php#L373-L376

**Comment by EliasDeVos** [comment]
oke thx, i will look into this. you can close this issue
