### ISSUE TITLE
__d() causes a fatal error with CakePHP 3.2 on local environment

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#11730]
I'm checking the compatibility of one of my plugins with the latest versions of CakePHP.

On Travis, with PHP 7.0.25 and with:
- CakePHP 3.5 (with phpunit 6.0)
- CakePHP 3.4 and 3.3 (with phpunit 5.7)
- CakePHP 3.2 (with phpunit 5.7)

tests are completed correctly.

Instead, only in my local environment, with PHP 7.0.27 and CakePHP 3.2 (with phpunit 5.7), I get this fatal error:

`Fatal error: __d(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "Cake\I18n\Translator" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /home/mirko/Libs/Plugins/cakephp-database-backup/vendor/cakephp/cakephp/src/I18n/functions.php on line 84`

I get this error with any call to the `__d()` method. For example:

    throw new InvalidArgumentException(__d('database_backup', '`{0}` executable not available', $name));

Full stack [here](https://pastebin.com/stxbvCtV).  
`tests/bootstrap.php` [here](https://github.com/mirko-pagliai/cakephp-database-backup/blob/cakephp3.2/tests/bootstrap.php)

I would just like to know what could be wrong with my local development environment, thanks.

**Comment by ADmad** [comment]
3.2 won't be getting any bugfixes. Might be a bug which has already been fixed. So if there are no errors using CakePHP 3.5 then there's nothing to be done here.

**Comment by robertpustulka** [comment]
Looks like you're trying to unserialize an old `Translator` object (ie serialized while running a previous version). Try flushing your cache.

**Comment by mirko-pagliai** [comment]
@ADmad many times I ask one thing here and someone answers me with another.  
Sometimes I think my english is bad, but then I re-read what I wrote, and it does not (meaning: my english is really bad, but I have explained properly).  
I know that `3.2` won't be getting any bugfixes. I know that if `3.5 works`, there's nothing to be done here. I was just asking "what **am I** doing wrong?".  
I know that you have to answer and follow many issues and many PR and maybe I should not use this channel (but something like stackoverflow), but this is a bit 'annoying, even if I understand.  
Without controversy and without anything personal.

@robertpustulka yes, I confirm that the problem is that. It is resolved by clearing the cache.

Thanks you all guys.

**Comment by ADmad** [comment]
@mirko-pagliai This issue tracker is for reporting bugs and features requests. It's not the proper place to ask questions like "what am I doing wrong?". Please use one of the help forums for that.
