### ISSUE TITLE
Baking reserved names

### ISSUE THREAD

**Issue by ohjeohje** [cakephp/cakephp#11743]
Can we have reserved names that you cant bake in cookbook or bake shell? I baked Tasks and created shell. After failing to call TasksTable functions I renamed everything to xxxxxxtasks and it worked.

Other solution might be to give warning to user when baking reserved name in console.

**Comment by markstory** [comment]
What issues have you had problems with baking `TasksTable`? I've used that a number of times and not had problems in 3.x

**Comment by dereuromark** [comment]
Also singular Task as Entity name should be fine, there are other names that will create more severe naming conflicts, e.g. Objects=>Object.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/blob/master/src/Console/Shell.php#L189

**Comment by dereuromark** [comment]
We should not use such an internal property, but a method $this->getTasks()->... instead maybe.

**Comment by markstory** [comment]
@ohjeohje Yes you cannot use `loadModel()` on tables that have existent properties. In shell classes `OptionParser` and `Tasks` are the only names that match that pattern. In controllers `View` could prove to be challenging.

**Comment by dereuromark** [comment]
@markstory Aren't properties in PHP case sensitive? Wouldn't the lowercase $tasks solved this when used for the tasks collection?

**Comment by dereuromark** [comment]
OK, given that fact we can then close this, until then people have to use manual loading here in shells.
