### ISSUE TITLE
Paginator unnecessarily modifies value of "sort" option.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11740]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.12

### What you did
Accessed sorting URL like `/posts?direction=asc&sort=title` generated by `PaginatorHelper::sort()` and then used `PaginatorHelper::numbers()` to generate paging links.

### What happened
There number links generated were like `/posts?page=2&sort=Posts.title&direction=asc`

### What you expected to happen
I expected the links to be like `/posts?page=2&sort=title&direction=asc`.

Internally when generation value of `order` option `Paginator::validateSort()` adds model alias as prefix to value of `sort` thereby producing `order` as `['Posts.title' => 'ASC']`. This `order` option is used to reset `sort` and that is how links generated by PaginatorHelper::numbers()` end up with `sort=Posts.title` instead of `sort=Posts.title`. The sorting link generated by `PaginatorHelper::sort()` still uses the non prefix field `sort=title`.

**Now this might seem like just a cosmetic issue but it becomes a real problem when `sortWhitelist` option is set.** 

If I set `'sortWhitelist' => ['title']` then `Paginator::validateSort()` rejects the `sort` value from query string when it's `sort=Posts.title`. So to avoid the problem and ensure links generated by `PaginatorHelper::sort()` as well as `PaginatorHelper::number()` work I have to set the prefixed as well as non-prefixed version of a field in whitelist as `'sortWhitelist' => ['title', 'Posts.title']`. Such redundancy should not be required.

To resolve the issue the original value of `sort` from request query string should be maintained and not reset from `order`. Only in case where validation of `sort` value fails should `sort` be set to `null`.

**Comment by dereuromark** [comment]
I experienced similar issues and always then worked around it by making sure it is prefixed here to avoid the change outlined here.
But I agree, fixing this would be a very good idea.

This relates to https://github.com/cakephp/cakephp/issues/10028#issuecomment-272812357 and the need for some better handling in general at some point.
A quick fix for this issue here only is of course fine for a bugfix release to keep the scope small.

**Comment by dereuromark** [comment]
PR open.
