### ISSUE TITLE
[4.0RFC] Remove "_underscore" from protected or private methods and  properties

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#11766]
Hi there!

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

I know this is a  very old discussion first.

According to #4499, `_protected()` and `__private()` will be abondoned in version 4.0. but i did not find relevant item in this page [4.0-Roadmap](https://github.com/cakephp/cakephp/wiki/4.0-Roadmap)

Is this missing?

**Comment by ADmad** [comment]
We have in general already stopped adding underscore prefix to new protected methods and properties in 3.x. Just haven't made a decision whether to go about removing underscore from methods/props in 4.0.

**Comment by slince** [comment]
@ADmad In that case, there will be two styles of code

**Comment by ADmad** [comment]
I am not opposed to renaming the old protected methods/props if that's the consensus and someone is willing to take up the chore :slightly_smiling_face:.

**Comment by slince** [comment]
This can be done by regular replacement of phpstorm ...

**Comment by markstory** [comment]
Wouldn't this represent a significant break in compatibility for what is basically cosmetic reasons?

**Comment by inoas** [comment]
Can't we wait with that in 5.x, deprecating and aliasing all of those in 4.x?

**Comment by saeideng** [comment]
removing old protected methods/props really not necessary 
and we should focus on important things

**Comment by robertpustulka** [comment]
> and we should focus on important things

:heart:  :100:

**Comment by slince** [comment]
@markstory 
> Wouldn't this represent a significant break in compatibility for what is basically cosmetic reasons?

We use the code style is to prevent the code is not beautiful, is not it? is not it? 
Modifying protected and private properties does not break compatibility.



> Can't we wait with that in 5.x, deprecating and aliasing all of those in 4.x?

There is a saying in China.  One today is worth two tomorrows（明日复明日，明日何其多）

> removing old protected methods/props really not necessary
and we should focus on important things

Coding style is not really the most important thing, but it's a basic; :smile: 


There have been many discussions on this issue, and I think it should be time to solve; otherwise the problem will always be there, 3years or 5 years

**Comment by mosaxiv** [comment]
I think it is better to fix it with 4.0 (better to be quick fix 😎)

With this problem, there is a time when cakephp beginners are confused when reading the code.

**Comment by markstory** [comment]
>  Modifying protected and private properties does not break compatibility.

Except when it does. We have several protected 'hook' methods that are widely used in userland code. Removing prefixes from those hooks will certainly break code. This extends into all accessor methods in entities as well.

**Comment by slince** [comment]
@markstory   

Hi, according to  [https://semver.org/](https://semver.org/),   you can do backwards incompatible changes  if you change the major version.

**Comment by markstory** [comment]
@slince Of course we *can*, but we have a goal of making the upgrade from 3 to 4 easy and not a giant headache for application developers. Large breaking changes like entity accessors that we don't currently have deprecation warnings or documentation for is not aligned with that goal.

**Comment by slince** [comment]
@markstory  I think you do not need to be so cautious. Too cautious does not necessarily benefit the development of the cake. Old school should be decisively removed, like 2.x to 3.x changes 

:smile:

**Comment by ADmad** [comment]
The break in how entity accessor methods work would be a big headache. That's reason enough to not remove the prefix in 4.x.

**Comment by jeremyharris** [comment]
@slince I think the point is that we have learned our lesson from the big breaking changes between 2.x and 3.x. The lesson is that the many very large in the wild cake applications remain in 2.x *because* of the difficulty in upgrading. We are trying to prevent that issue in future major versions to help promote upgrading, while trying to strike the balance with BC and new features/practices.

**Comment by slince** [comment]
It means that `_protected()` and `__private()`  will always stay in cakephp ? or will be removed sometime in the future?

**Comment by dereuromark** [comment]
It is fair to assume that those will be gone in 5.x+ then. Just not at once, but piece by piece.
Closing then.

**Comment by markstory** [comment]
> It is fair to assume that those will be gone in 5.x+ then. Just not at once, but piece by piece.

I think not adding more new prefixed methods is a good way to minimize future breakage, and we can remove prefixes from non-user facing methods incrementally throughout 4.x.
