### ISSUE TITLE
Is right to cache Class File Location without name of plugin?

### ISSUE THREAD

**Issue by GalochkinKirov** [cakephp/cakephp#11762]
This is a (multiple allowed):

* [x] bug?
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.6.13, 2.10.8
* Platform and Target: -

### What you did
I want to use the same classnames in the different plugins, but now cannot due caching file locations.

### What happened
Pluging
-/ApiV1
--/LocationsController.php
/ApiV2
--/LocationsController.php

config/routes.php
```
Router::connect('/api/v1/locations',                        ['controller' => 'Locations', 'action' => 'add', 'plugin'=>'ApiV1', "[method]" => "POST"]);
Router::connect('/api/v2/locations',                        ['controller' => 'Locations', 'action' => 'add', 'plugin'=>'ApiV2', "[method]" => "POST"]);
```

This is not working cuz of caching file locations, App.php:
```
	protected static function _map($file, $name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = 'plugin.' . $name;
		}
		if ($plugin && empty(self::$_map[$name])) {
			self::$_map[$key] = $file;
		}
		if (!$plugin && empty(self::$_map['plugin.' . $name])) {
			self::$_map[$key] = $file;
		}
		if (!self::$bootstrapping) {
			self::$_cacheChange = true;
		}
	}
```

### What you expected to happen
Can we replace the caching mechanism with this, App.php:
```
	protected static function _map($file, $name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = $plugin . '.' . $name;
		}
		if ($plugin && empty(self::$_map[$name])) {
			self::$_map[$key] = $file;
		}
		if (!$plugin && empty(self::$_map[$plugin . '.' . $name])) {
			self::$_map[$key] = $file;
		}
		if (!self::$bootstrapping) {
			self::$_cacheChange = true;
		}
	}
```

I use CakePHP 2.6.13, any solutions are permitted.

**Comment by markstory** [comment]
Duplicate class names are not supported in 2.x. See #11623 and #7859 for more history.

**Comment by GalochkinKirov** [comment]
I solved this turned off the core cache (engine = null).
