### ISSUE TITLE
Association:setConditions() needs to accept a callable

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#11767]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

The `Association::setConditions()` method was added recently, but only accepts arrays. This method needs to also accept a callable, so that conditions can be constructed dynamically.

**Comment by markstory** [comment]
pull request open now.
