### ISSUE TITLE
RFC: Use .php extension by default for templates.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11760]
Using `.ctp` extension for templates doesn't provide much value, just extra hassle to configure editors to recognize them as PHP files. Since all templates are nested under `Template` folder (and generally use underscored file names) they are easily recognizable as templates and don't need a special extension for distinguishing them from class files.

So I propose switching to `.php` extension for templates in 4.0.

**Comment by inoas** [comment]
I'd say we should keep .ctp but the load order would be .twig (in case we support that) > .php > .ctp and .ctp being dropped in 5.x.

**Comment by ADmad** [comment]
Personally I would avoid implicit load order for .php and .ctp files. It would be unnecessary hassle figuring out the right file to load considering things like fallback to default templates of themes and ability to override plugin templates in app. Even when upgrading from 3.x to 4.0, renaming .ctp to .php would be simple enough or one can set `AppView::$_ext` as required.

Twig templates are a separate case altogether as they need a separate view class for rendering. Even if twig support is provided in core itself, it's use should be explicit opt-in or opt-in without any fallback feature.

**Comment by inoas** [comment]
Hm... I am okay with opting in things but I would not make things harder out of the box.

It can be very feasible to have .twig > .php loading - for instance in plugin-world you supply a .php file but end users can overwrite via say `app/src/Template/Plugin/Foobar/batz/quux.twig`

Obviously the path priority would be stronger than the extension/parser priority.

And again, dropping support out of the box for .ctp will be a hassle for seamless upgrading. Why?
If you want to make a clean cut, maybe a bake task that renames all .ctp files to .php would be useful?

**Comment by chinpei215** [comment]
As I said in the dev channel, this change could be a security hole accidentally. If you call `class_exists('App\Template\Users\index')`, composer will include `index.php`. If we want to do that, we would also have to move the `Template` directory to the root directory like `config` or `bin`.

**Comment by ADmad** [comment]
Moving template files out of autoload path `src` does make sense.

**Comment by dereuromark** [comment]
```
config/
src/ (autoload)
templates/
tests/ (autoload-dev and autoload for fixture)
```
sounds reasonable to me, too.

>  maybe a bake task that renames all .ctp files to .php would be useful?

No, @ionas , that has nothing to do with bake plugin. This is an upgrade tool task. But I agree that such a task is vital for this to be adopted and is a hard requirement for me in such a case.

**Comment by saeideng** [comment]
Moving template files out of autoload path src does make sense.
some of templates is under `plugins`

**Comment by inoas** [comment]
well `/plugins/PluginName/templates/*.php` would also need to be read as well as `/templates/PluginName/*.php`, right?

**Comment by dereuromark** [comment]
Lets not put theoretical 5.0 or 6.0 discussion in a small scoped issue. for 4.0.

**Comment by inoas** [comment]
I was off with the numbers (now corrected). What I mean is we can just keep `.ctp` and deprecated it in 4.x in favour of .twig?

**Comment by ADmad** [comment]
> some of templates is under plugins

Yes, so plugin templates would be under `plugins/PluginName/templates` instead of `plugins/PluginName/src/Template`.

**Comment by burzum** [comment]
I would prefer twig to be optional and plain php (*.ctp) to stay the default. I really don't get the obsession with people of template engines. The only reason for them is IMO if you have external template authors you can't trust. Or online editing of templates, just like Typo3 does with Typoscrip for scripting without exposing php. In any other case plain php is always faster and less overhead than a template engine, even with caching.

**Comment by dereuromark** [comment]
> I would prefer twig to be optional and plain php (*.php or *.ctp) to stay the default.

Precisely why I would have liked some here to not widen the scope of the original issue. Everything beyond the extension type for the PHP templates itself is not something that needs discussing here - and only leads us away from the actual relevant discussion.

**Comment by xaphalanx** [comment]
Removing .ctp means moving the template  to root and people will need to  upgrade by either setting _ext property or changing file names. Upgrade path either easy seems trivial to me.  

The .ctp extension  reminds of the zf .phtml which also have been there since its version one.  I like the extension. It tells me here is a file that is not something you execute on its own like other .php files.

**Comment by inoas** [comment]
I'd not move around templates for the sake of moving them around. Just upgrade hassle in 4.x.
For 5.x that's a different matter.

**Comment by robertpustulka** [comment]
I still maintain 2.x apps where templates were in `View` folder. And I still sometimes scratch my head looking for templates in View folder after getting back to 3.x apps. I know it's in my head and just the matter of getting used to, but I think that maybe cleaner seperation of code and templates is a good thing.

**Comment by ADmad** [comment]
@robertpustulka I had moved the templates under `src/Template` in 3.x to avoid the mix of templates and class files we have under `View` in 2.x :slightly_smiling_face:. IIIRC the justification for keeping them under `src` back then was templates are still PHP code. But in hindsight moving them out of `src` would be even better aesthetically and would avoid the potential security concern that @chinpei215 pointed out if `.php` extension was used.

My suggestion to rename `.ctp` to `.php` is based on feedback I have read from new / non cakephp users over the years, wondering why the special extension when the templates are just PHP code.

**Comment by robertpustulka** [comment]
@ADmad that was a good decision back then. But for me having php classes and twig template files in a same file structure feels a bit awkward now. So yes, this is aesthetics mostly.

**Comment by markstory** [comment]
Solving the template directory location can be done in a backwards compatible way. The paths used by an application are defined by `App.paths.templates` in `Configure`, so we can use the new convention for new applications and recommend people update their existing apps. Plugin paths could be shimmed for compatibility inside `App::path()` enabling both the old and new locations to be scanned.

**Comment by ADmad** [comment]
@markstory Yup, as you described the path change can be done in a BC way. What do you think about the extension rename?

**Comment by markstory** [comment]
Extension rename could be backwards compatible if we had an opt-in way to switch the extension used and make that the default for new apps. I think only supporting .php is something we could do in 4.0.0 though. I think renaming files is a simple enough operation for folks to do as they upgrade.

**Comment by dereuromark** [comment]
If we move it outside of src, wouldn't the same logic apply to Locale folder and its po files etc?
I think that was a similar discussion and why or why not it should be part inside of src.

**Comment by odan** [comment]
I think it would make sense to separate the templates and resources from the core application. The `src/` directory should be reserved for PHP classes (the App namespace). Example:

```
.
├── config                  # Configuration files
├── docs                    # Documentation files
├── public                  # Web server files (webroot)
├── resources               # Other resource files
│   ├── assets              # Raw, un-compiled assets such as LESS, SASS
│   ├── locale              # Language files (translations)
│   ├── migrations          # Database migration files (Phinx)
│   └── seeds               # Data seeds
├── src                     # PHP source code (The App namespace)
├── templates               # Twig and PHP templates + JS and CSS
├── tests                   # Automated tests
├── tmp                     # Temporary files
├── vendor                  # Reserved for composer
├── composer.json           # Project dependencies
└── README.md               # This file
```

**Comment by burzum** [comment]
I like @odan proposal, this would also solve the issue where to place JS that is build using something like webpack by simply adding `/resources/scss` and `/resources/js`.

**Comment by dereuromark** [comment]
I wonder if templates shouldnt then just be inside resources, and locale might better be plural for consistency:
```
├── resources               # Other resource files
│   ├── assets              # Raw, un-compiled assets such as LESS, SASS
│   ├── locales             # Language files (translations)
│   ├── migrations          # Database migration files (Phinx)
│   └── seeds               # Data seeds
│   └── templates           # Twig and PHP templates + JS and CSS
```

**Comment by odan** [comment]
Why the templates should live in `/templates` instead of `/resources/templates` (IMHO):

* Centralizing your templates in `/templates` simplifies the work of your designers. That makes it easier to find the templates.
* Referencing to a template is way shorter: `/templates/Articles/index.ctp` instead of `/resources/templates/Articles/index.ctp`
* It's becoming more and more "standard" (in the PHP community) to put templates into the `/templates` directory.

**Comment by burzum** [comment]
@odan I disagree. If you have designers with daily amnesia then this might be a valid argument. Otherwise they'll remember where they are after the first time. Especially if everything else frontend related is in the resources folder as well. And almost every editor and IDE has autocomplete. So having to type and remember one word more is really a non-issue.

**Comment by inoas** [comment]
@dereuromark I would expect css and js to be inside assets not inside templates.

**Comment by dereuromark** [comment]
>  I would expect css and js to be inside assets not inside templates.

I am fairly certain that is the case when you carefully read the above context again surrounding it.
I just copied what was there, and this folder sure is just for templates. So no reason to worry here.

**Comment by lorenzo** [comment]
I also think this should be done, unfortunately this will add significant overhead as we also need to test for older ctp files to keep BC

**Comment by ADmad** [comment]
Keeping support for CTP files isn't necessary IMO. Renaming the files and moving them to `/template` is not a big deal.

All it takes is 3 commands as I have shown in related PR.

https://github.com/cakephp/cakephp/pull/11931#discussion_r182517074

**Comment by inoas** [comment]
@Admad could we have https://github.com/cakephp/cakephp/pull/11931#discussion_r182517074 in the migration guide then? Does it work on osx and *nix? Is windows support (powershell) relevant?

**Comment by ADmad** [comment]
> could we have #11931 (comment) in the migration guide then? 

When the PR is merged sure.

> Does it work on osx and *nix? 

Yes.

> Is windows support (powershell) relevant?

Dunno. Surely someone will be able to come up with equivalent powershell commands if needed.

**Comment by lorenzo** [comment]
Probably a php executable would be better

**Comment by dereuromark** [comment]
Yeah, could easily be part of some migration/update script then :)

**Comment by josephzidell** [comment]
I'd like to offer my 2c here. The OP is correct in that `.ctp` by *itself* provides little immediate benefit over `.php`. The issues raised about autoloading etc. are valid, however, I disagree with the decision to move templates out of the `src` dir, since they are certainly part of an app's source code.

I propose a middle ground: `index.___.php`, similar to how [Laravel](https://laravel.com/docs/5.6/blade) does it `index.blade.php`.

It solves the above problems:
* Can easily configure composer to ignore those
* IDEs can be taught those are cake templates and treat them as such
* They still are bonafide `.php` files
* An app's files (all of them) reside in `src` dir, which is their logical home

The question is: what that middle section should be named, and I suggest `cake`, but am open to other ideas:
`index.cake.php`
`view.cake.php`

Another possibility reusing `ctp`:
`index.ctp.php`
`view.ctp.php`

**Comment by inoas** [comment]
@josephzidell well but looking at it for 2 secs it looks like Laravel's blade is a stand alone templating language (probably allowing PHP, similar to markdown still allowing html code).

So the only thing that is in any way close is the bake template syntax so there the files could look like view.bake.php.

There could be other benefits though... to keep view.ctp.php - that would be VisualCode or Atom marking those files as cake templates and/or for editors to inject macros etc...?!

**Comment by josephzidell** [comment]
@dereuromark I think it's for both purposes.
@ionas Precisely. IDEs can allow following the path of an element, etc...

**Comment by ravage84** [comment]
Personally, I really like the "ctp" file extension. File extensions are to some extend self explaining or at least self expressive. Even though template files are PHP files, they are a special kind of, with a very specific purpose.  Also in the context of a CakePHP application they have [special formatting rules](https://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#template-files).
For me, CTP files aren't just plain PHP files, thus they may have a dedicated file extension and should not be renamed to .php.
Certainly, I understand the argument this file extension can be a small learning hurdle for newbies (What is a .ctp file? Why does my editor not work with them correctly?) but this exact file extension can be a small learning help (CTP files are always template files in a CakePHP application).

Independently whether we change the file extension or not, I'm in favor of moving the templates.
For me, templates should be placed under ``/templates``. ``/resources`` is not the correct place, as it is for "other stuff``, like a XSD file or may be a file to import which one wants to find easily when using a CLI command.
Refs: https://github.com/php-pds/skeleton/issues/12

And static web assets (compiled, generated & minified ones, not their base) should be placed under ``/webroot`` as usual (or ``/public`` for that matter).
Where "raw, un-compiled assets such as LESS, SASS" should go, is currently indifferent to me. ``/templates``, ``/resources`` or even ``/assets`` have advantages and disadvantages.

I agree, locales could be moved to ``/locales``.

If we really can introduce new template (and locale) folder locations in a BC way, we should do it in CakePHP 3.7 as a preparing bridge for CakePHP 4.0, where we onlly accept the new location.

**Comment by saeideng** [comment]
I like @odan proposal too, but  with a bit change 
```
├── webroot                 # Web server files (public)
├── resources               # Other resource files
│   ├── assets              # Raw, un-compiled assets such as LESS, SASS
│   ├── locale              # Language files (translations)
│   ├── migrations          # Database migration files (Phinx)
│   └── seeds               # Data seeds
├── src                     # PHP source code (The App namespace)
├── templates 
```

**Comment by markstory** [comment]
@saeideng would you also keep `bin` and `config` as top level directories?

**Comment by saeideng** [comment]
@markstory yes, I just wrote the changes 

5 changes : 

1) moving `src/templates/` to `/templates`  (root)
2) moving `src/locale`  to `/resources/locale` 
3) moving `config/seeds`  to `/resources/seeds` 
4) moving `config/migrations`  to `/resources/migrations` 
5) having `/resources/assets` (new/optional)

**Comment by burzum** [comment]
@markstory we should follow this and keep these two folders there.

https://github.com/php-pds/skeleton

**Comment by josephzidell** [comment]
I put all database-related things in a `database/` folder
```
├── database                # Database-related things
│   ├── fixtures            # Database migration files (Phinx)
│   ├── migrations          # Database migration files (Phinx)
│   └── seeds               # Data seeds
├── resources               # Other resource files
│   ├── assets              # Raw, un-compiled assets such as LESS, SASS
│   ├── locale              # Language files (translations)
├── src                     # PHP source code (The App namespace)
├── templates
├── webroot                 # Web server files (public)
```

**Comment by ADmad** [comment]
Funny how my issue to change template extension got hijacked into conversation about changing the app's folder structure.

**Comment by ADmad** [comment]
PR #11931 has already been opened to handle the file extension change (and folder move).

In general the following folder structure is a good balance between moving templates and resources out of autoload path and going overboard with changes.

```
|-- bin
|-- config
|-- resources
|   |-- assets
|   |-- locale
|-- src
|-- templates
|-- webroot
```

I am closing this issue to stop the bike shedding :slightly_smiling_face:.

**Comment by dereuromark** [comment]
Well, pulling it out of src is a requirement then with php file ext - to avoid autoloading/cs-sniff or other side effects to templates. And then there is not too much distance to a general discussion here.

@josephzidell Why is locale singular and not plural locales, if all others are plural?
Otherwise this seems to also be OK, to avoid config being overloaded with migration stuff.

**Comment by josephzidell** [comment]
@dereuromark That was a typo. I copied the example above and moved things around 😄

**Comment by inoas** [comment]
- locales should be plural
- I would like to see a clear folder split between test relevant directories (that may not require shipping in dist, but migrations and seeds do) and non-test.
