### ISSUE TITLE
RequestHandler->isXML() returns positive for .json request if Accept header is missing

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#11761]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: apache 2.3, PHP 7.0.27, High Sierra 10.13.3

### What you did
Send API request with empty `Accept` header but with extension `.json`. E.g `http:://localhost/api/example.json`

### What happened
The `$this->RequestHandler->isXml()` returns positive value.

The reason is that code here https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/RequestHandlerComponent.php#L509 which tries to parse the `Accept` header and if it is empty it returns the `$this->_ext` regardless of whether the `$type` variable is set or not.

### What you expected to happen
It should return `false` since the request wants JSON and not XML.

According to function documentation if variable `$type` is set (which it is in `->isXML()` call), it should return boolean true/false.

The fix should be probably:

```
if (empty($acceptRaw)) {
    return $type ? $this->ext == $type : $this->ext;
}
```

Should it be fixed in `RequestHandlerComponent` or is it expected behaviour and my understanding is worng?

**Comment by markstory** [comment]
Your suggested changes seem reasonable. Would you want to make a pull request for them?
