### ISSUE TITLE
3.next  The cors method is making backwards incompatible changes

### ISSUE THREAD

**Issue by mosaxiv** [cakephp/cakephp#11763]
This is a (multiple allowed):

* [ ] bug?
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next

3.next cors method is Immutable Responses.

### ~3.5
```php
$this->response->cors($this->request)
    ->allowOrigin(['*.cakephp.org'])
    ->allowMethods(['GET', 'POST'])
    ->allowHeaders(['X-CSRF-Token'])
    ->allowCredentials()
    ->exposeHeaders(['Link'])
    ->maxAge(300)
    ->build();
```

### 3.next
```php
$this->response = $this->response->cors($this->request)
    ->allowOrigin(['*.cakephp.org'])
    ->allowMethods(['GET', 'POST'])
    ->allowHeaders(['X-CSRF-Token'])
    ->allowCredentials()
    ->exposeHeaders(['Link'])
    ->maxAge(300)
    ->build();
```

~I think it would be better to deprecated  the `cors method` after fixing the compatibility and create a new `withCors method`.~

For parameters it is backwards compatible.
https://github.com/cakephp/cakephp/blob/3.next/src/Http/Response.php#L2395-L2416

**Comment by saeideng** [comment]
what is problem ?
`build()` returns $response 
and we should re-assign to response for `Immutable` reason
`$this->response = ....->build();`

**Comment by saeideng** [comment]
>I think it would be better to deprecated the cors method after fixing the compatibility and create a new withCors method.

`cors` returns builder instance now , for use` builder` methods  
but `with*` methods `$this`

**Comment by mosaxiv** [comment]
The problem is that the backwards compatibility of the `cors method` is gone.

I think that should be done like this : 
https://github.com/cakephp/cakephp/blob/d5c11dfcc3eb150389f2fdb76e9729b178bd24bb/src/Http/Response.php#L2392-L2397
```php
if($builder instanceof CorsBuilder){
    return $builder;
}else{
    if ($updated !== $this) {
        // If $updated is a new instance, mutate this object in-place
        // to retain existing behavior.
        foreach ($updated->getHeaders() as $name => $values) {
            if (!$this->hasHeader($name)) {
                $this->_setHeader($name, $values[0]);
            }
         }
     }
}
```

If can tolerate backwards incompatible changes of the cors method, do not need to change it :)

**Comment by mosaxiv** [comment]
`WithCors` was a mistake as it is a problem with `CorsBuilder :: build ()`

**Comment by markstory** [comment]
You're right that the internal behavior has changed, but the return types and parameter types are all consistent which is what our BC promise focuses on. This behavior change will be added to the migration guide as it is currently missing.

**Comment by mosaxiv** [comment]
That was good.
Thank you.

**Comment by saeideng** [comment]
@mosaxiv thanks for report
Docs is update now
