### ISSUE TITLE
Can't create directory in product mode

### ISSUE THREAD

**Issue by katahide100** [cakephp/cakephp#11777]
It is troubled that you can not create a directory in the production environment.
Problems occur with the settings below.

`define('DEBUG', false);`

When I saw the source code, the following was the cause.

/src/Log/Engine/FileLog.php L90

```
        if ($this->_path !== null &&
            Configure::read('debug') &&    ←←← here
            !is_dir($this->_path)
        ) {
            mkdir($this->_path, 0775, true);
        }
```

Sometimes I want to dynamically generate a directory even in product mode, is this necessary?

Perhaps the following commit is added to this check.
https://github.com/cakephp/cakephp/commit/f5859ca7193dcd82433fb0f617d64b1fbd380801#diff-87ecdb78046ba8cbecb5a92a067be446

**Comment by ADmad** [comment]
Auto creating cache directories in production is an unsafe default, hence we won't be supporting it.

You can instead modify the composer post install script in your app to create the required directories for you. Simply modify this [directories list](https://github.com/cakephp/app/blob/master/src/Console/Installer.php#L35).
