### ISSUE TITLE
Console inspiration

### ISSUE THREAD

**Issue by Oxicode** [cakephp/cakephp#11774]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version:3.x
* Platform and Target: 

Hola:
He visto este repositorio y pensaba si era factible inspirarnos en el para mejorar la consola de cakephp
https://github.com/terkelg/prompts

**Comment by dereuromark** [comment]
Please use English language, most of us will not be able to understand you otherwise.

**Comment by saeideng** [comment]
thanks for your suggest 
if you think there are  special features which we not have it , or you think some feature is good 
you can tell us with a bit text about that feature 
also I think your suggested repo is nodejs base
thanks
