### ISSUE TITLE
Saving new hasMany associations records fails due to existsIn build rule

### ISSUE THREAD

**Issue by pbfman** [cakephp/cakephp#11772]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: Apache2, MySQL, PHP 7

### What you did
I've got two tables ``Events`` and ``Dates`` (``Events`` hasMany ``Dates``):

```php
class EventsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        //further config/associations ....

        $this->hasMany('Dates', [
            'foreignKey' => 'event_id',
            'className' => 'Dsc/Core.Dates'
        ]);
    }
}
```

```php
class DatesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        //further config/associations ....

        $this->belongsTo('Events', [
            'foreignKey' => 'event_id',
            'joinType' => 'INNER',
            'className' => 'Dsc/Core.Events'
        ]);
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['event_id'], 'Events'));

        return $rules;
    }
}
```

I want to insert a **new** Event including a **new** Date. Therefore i created a form:

```php
    <?= $this->Form->create($event) ?>
    <fieldset>
        <legend><?= (isset($edit) && $edit ? __('Edit Event') : __('Add Event')) ?></legend>
        <?php
       //further event fields
        echo $this->Form->control('dates.0.id', ['type' => 'hidden']);
        echo $this->Form->control('dates.0.date_start', ['type' => 'date']);
        echo $this->Form->control('dates.0.time_start', ['type' => 'time']);
        echo $this->Form->control('dates.0.date_end', ['type' => 'date']);
        echo $this->Form->control('dates.0.time_end', ['type' => 'time']);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
```

Patching the data according to this code:

```php
$event = $this->Events->newEntity();
if ($this->request->is('post')) {
   $event = $this->Events->patchEntity($event, $this->request->getData(), ['associated' => ['Dates']]);
   debug($event);
   if ($this->Events->save($event, ['associated' => ['Dates']])) {
       $this->Flash->success(__('The event has been saved.'));
       return $this->redirect(['action' => 'index']);
   }
   $this->Flash->error(__('The event could not be saved. Please, try again.'));
}
```
The resulting entity (output of debug) looks correct:

```
object(Dsc\Backend\Model\Entity\Event) {

	'event' => 'Test',
	'_translations' => [
		'en_US' => object(Dsc\Backend\Model\Entity\Event) {

			'event' => '',
			'description' => '',
			'[new]' => true,
			'[accessible]' => [
				'*' => true,
				'id' => false
			],
			'[dirty]' => [
				'event' => true,
				'description' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Dsc/Backend.Events'
		
		}
	],
	'description' => '',
	'speaker' => '',
	'affiliation_speaker' => '',
	'host' => '',
	'organizer_id' => (int) 71,
	'show_organizer' => (int) 1,
	'location_id' => (int) 1,
	'location_text' => '',
	'serie_id' => (int) 0,
	'dates' => [
		(int) 0 => object(Dsc\Core\Model\Entity\Date) {

			'date_start' => object(Cake\I18n\FrozenDate) {

				'time' => '2018-03-01T00:00:00+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'time_start' => object(Cake\I18n\FrozenTime) {

				'time' => '2018-03-01T08:00:00+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'date_end' => object(Cake\I18n\FrozenDate) {

				'time' => '2018-03-01T00:00:00+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'time_end' => object(Cake\I18n\FrozenTime) {

				'time' => '2018-03-01T08:00:00+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'[new]' => true,
			'[accessible]' => [
				'*' => true,
				'id' => false
			],
			'[dirty]' => [
				'date_start' => true,
				'time_start' => true,
				'date_end' => true,
				'time_end' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Dsc/Core.Dates'
		
		}
	],
	'language' => 'de',
	'topic_id' => (int) 1,
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'event' => true,
		'_translations' => true,
		'description' => true,
		'speaker' => true,
		'affiliation_speaker' => true,
		'host' => true,
		'organizer_id' => true,
		'show_organizer' => true,
		'location_id' => true,
		'location_text' => true,
		'serie_id' => true,
		'dates' => true,
		'language' => true,
		'topic_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Dsc/Backend.Events'

}
```
Nevertheless the save fails.

### What happened
The save of the created entity fails due to:

```
object(Dsc\Core\Model\Entity\Date) {

	'date_start' => object(Cake\I18n\FrozenDate) {

		'time' => '2018-03-01T00:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'time_start' => object(Cake\I18n\FrozenTime) {

		'time' => '2018-03-01T08:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'date_end' => object(Cake\I18n\FrozenDate) {

		'time' => '2018-03-01T00:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'time_end' => object(Cake\I18n\FrozenTime) {

		'time' => '2018-03-01T08:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'event_id' => (int) 13387,
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'date_start' => true,
		'time_start' => true,
		'date_end' => true,
		'time_end' => true,
		'event_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [
		'event_id' => [
			'_existsIn' => 'This value does not exist'
		]
	],
	'[invalid]' => [
		'event_id' => (int) 13387
	],
	'[repository]' => 'Dsc/Core.Dates'

}
```
Intern there is a new event id generated. This id is not persistent in the moment of executing the "application build rules" on ``Dates``. So the rule ``existsIn`` will fail.

### What you expected to happen
The existsIn rules by the buildRules should be ignored while the parent entity is a new one.
OR the existsIn rules should be able to verify the "in memory" existing event id.

I do not want to remove this rules because they are an essential check but they cause an error if you try to save a **new** entity with **new** a nested has many entity.

Same issue for HABTM associations obviously.

**Comment by lorenzo** [comment]
You can instruct the rules checker to only check on `create`, `update` or both. Please read the documentation here to understand how rules can be applied conditionally:

https://book.cakephp.org/3.0/en/orm/validation.html#creating-a-rules-checker

**Comment by markstory** [comment]
The generated rules/validation are intended to be a starting point. If they don't suit your needs you should remove/adapt them to do what you need.

**Comment by pbfman** [comment]
@lorenzo Thanks for the hint. I know that options already but these wont fix the described problem.

@markstory Well I am aware of that fact. But in fact this rule does not work as expected even if it is just a default.

I want to ensure every time when adding OR updating the hasMany ``Dates`` of an ``Event`` that the foreign key association is valid. Therefore the existing ``ExistsIn`` should fit perfect. But there is indeed a bug.
If I update the ``Dates`` of an **existing** (already persited) ``Event`` then it works correct. Because the ``ExistsIn`` rule can find the referenced id of ``Event``.
If I add a **new** ``Event`` with ``Dates`` then it fails! The id of the new ``Event`` is not persisted at the moment of the test and the rule will fail. BUT it should not fail.


In my opinion the rule need to know if the parent entity ``isNew()`` but at the moment the invoked parameters does not provide any information about this.
cakephp/cakephp/src/ORM/Rule/ExistsIn.php line 80:
```php
public function __invoke(EntityInterface $entity, array $options)
```
The options array does not provide any useful information aswell:
```
[
	'errorField' => 'event_id',
	'message' => 'This value does not exist',
	'_primary' => false,
	'atomic' => true,
	'checkRules' => true,
	'checkExisting' => true,
	'_sourceTable' => object(Dsc\Backend\Model\Table\EventsTable) {

		'registryAlias' => 'Dsc/Backend.Events',
		'table' => 'events',
		'alias' => 'Events',
		'entityClass' => 'Dsc\Backend\Model\Entity\Event',
		'associations' => [
			(int) 0 => 'events_event_translation',
			(int) 1 => 'events_description_translation',
			(int) 2 => 'events_speaker_translation',
			(int) 3 => 'events_affiliation_translation',
			(int) 4 => 'events_location_text_translation',
			(int) 5 => 'eventsi18n',
			(int) 6 => 'datasources',
			(int) 7 => 'organizers',
			(int) 8 => 'locations',
			(int) 9 => 'mainevents',
			(int) 10 => 'series',
			(int) 11 => 'maintopics',
			(int) 12 => 'dates',
			(int) 13 => 'links',
			(int) 14 => 'topics'
		],
		'behaviors' => [
			(int) 0 => 'Enabled',
			(int) 1 => 'Timestamp',
			(int) 2 => 'DscTranslate',
			(int) 3 => 'RestrictByUser'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	},
	'associated' => true,
	'repository' => object(Dsc\Core\Model\Table\DatesTable) {

		'registryAlias' => 'Dsc/Core.Dates',
		'table' => 'dates',
		'alias' => 'Dates',
		'entityClass' => 'Dsc\Core\Model\Entity\Date',
		'associations' => [
			(int) 0 => 'events'
		],
		'behaviors' => [
			(int) 0 => 'Timestamp'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	}
]
```

For sure I can easily replace the created default ExistsIn rule. But I can't imagine how to achieve the wanted result (working existsIn rule for creating and updating) at the moment.

**Comment by markstory** [comment]
This may not be solvable, as the child records (DatesTable) have no linkage to the Event before persistence is completed unfortunately.

**Comment by pbfman** [comment]
Well its just an idea but wouldnt it be possible to add to the ``options`` array an value that indicates the parent as *new*.

cakephp/cakephp/src/ORM/Table.php line 1818 - save:
```php
        if ($isNew) {
            $success = $this->_insert($entity, $data);
        } else {
            $success = $this->_update($entity, $data);
        }

        //ADDED FOLLOWING LINE
        $options['parent'] = $isNew;

        if ($success) {
            $success = $this->_onSaveSuccess($entity, $options);
        }
```

Then the ``_onSaveSuccess`` would propagate this options:
cakephp/cakephp/src/ORM/Table.php line 1848 - _onSaveSuccess (no edit):
```php
      $success = $this->_associations->saveChildren(
            $this,
            $entity,
            $options['associated'],
            ['_primary' => false] + $options->getArrayCopy()
        );
```

I did not dig deeper in the structure but the recursive called ``save`` should then get the information in its ``options`` array which is propagated to the application build rules.

**Comment by markstory** [comment]
That could work well. Would you pass the parent entity, or just that there is a parent?

**Comment by pbfman** [comment]
Good point! Based on this just a modification of:
[cakephp/cakephp/src/ORM/Table.php line 1850](https://github.com/cakephp/cakephp/blob/7d52085e6f3874abb18a5de6df73c0c1332054ad/src/ORM/Table.php#L1850) - _onSaveSuccess:
```php
protected function _onSaveSuccess($entity, $options)
{
    $success = $this->_associations->saveChildren(
        $this,
        $entity,
        $options['associated'],
        //add parent entity to children options array
        ['_primary' => false] + ['parent' => $entity] + $options->getArrayCopy()
    );
...
```
would offer enough flexibility to maybe other tasks. Children would be able to check via ``$options['parent']->isNew()`` if the parent entity was persisted before. 

This behavior could be used to add:
[cakephp/cakephp/src/ORM/Rule/ExistsIn.php line 127](https://github.com/cakephp/cakephp/blob/7d52085e6f3874abb18a5de6df73c0c1332054ad/src/ORM/Rule/ExistsIn.php#L127) - __invoke:
```php
if (isset($options['parent']) && is_a($options['parent'], EntityInterface::class) && $options['parent']->isNew()) {
    $parent_fields = $options['parent']->extract($bindingKey);
    $child_fields = $entity->extract($this->_fields);
    return empty(array_diff($child_fields, $parent_fields));
}
```
From the parent the necessary fields would be extracted to parent_fields with its value (e.g. id). Same is done for currently checked entity (in our case the child). All values from child needs to be present in parent. Maybe the ``array_diff`` is not the best way. In my test scenario it worked.

**Comment by markstory** [comment]
@pbfman Any chance you could make a pull request to `3.next` with these changes? I'm happy to help with test cases if you need a hand.

**Comment by pbfman** [comment]
Yes! If you would allow me to create a branch or if you would create an branch (e.g. "issue-11772").

I will commit my suggestions and we can discuss about it.

**Comment by rchavik** [comment]
typically you create the branch in your own fork, commit your stuff there, then submit the PR

**Comment by pbfman** [comment]
Thank you for the hint! Its my first PR (https://github.com/cakephp/cakephp/pull/11860) to an external project.

**Comment by markstory** [comment]
Closing as there is a pull request now.
