### ISSUE TITLE
Improvement: Unneeded redundancy in validator

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11778]
This is a (multiple allowed):

* [] bug
* [x] enhancement

* CakePHP Version: 3.5.x / dev-master

### What you did
```php
        $validator
            ->scalar('status')
            ->add('status', 'validateStatus', [
                'provider' => 'table',
            ]);
```

### What happened
> InvalidArgumentException: Unable to call method "" in "table" provider for field "status"

You need to explicitly define the rule as copy of the name again:
```php
        $validator
            ->scalar('status')
            ->add('status', 'validateStatus', [
                'rule' => 'validateStatus', // HERE
                'provider' => 'table',
            ]);
```

### What you expected to happen
The first example should work: The rule name should inherit from the 2nd argument rule name if not specific otherwise (null).

**Comment by markstory** [comment]
Sounds reasonable to me.
