### ISSUE TITLE
3.6: Fatal error loading plugins

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11783]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest master

### What you did
Using 3.6 pre-beta with a 3.5 app.
And the load command as it always has been:

Plugin::load('Tools', ['bootstrap' => true]);

### What happened

> Fatal error: Cannot redeclare endsWith() (previously declared in /home/vagrant/Apps/x.local/vendor/dereuromark/cakephp-tools/config/bootstrap.php:323) in /home/vagrant/Apps/x.local/vendor/dereuromark/cakephp-tools/config/bootstrap.php on line 323

Seems like it tries to load the plugin now twice?

### What you expected to happen
Still BC - only loading the plugins once (the old way).

**Comment by markstory** [comment]
Are you running tests, or is this part of a web request?

**Comment by dereuromark** [comment]
Normal webrequest after adding 3.next branch to test compatibility of my 3.5 app with 3.6.

**Comment by markstory** [comment]
Ok. Looks like this is caused by the `Plugin::load()` including the bootstrap file, and also the new application hook also running the bootstrap logic. I'll get this fixed up.
