### ISSUE TITLE
[3.6.0-beta1] Failure to load "cascading plugins" bootstrap files

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/cakephp#11787]
This is a bug

* CakePHP Version: 3.6.0-beta1
* Platform and Target: PHP 7.1 / MacOS X / No DB.

### What you did

I'm working on an app that relies on a plugin (let's call it `PluginA`) which itself relies on another plugin (`PluginB`).

Both those plugins have a bootstrap file (mainly to load other plugins and to hook to some events).

When `PluginA` loads `PluginB`, the bootstrap file of `PluginB` is not loaded, even though the call is made with `bootstrap => true`, therefore, the handlers are not hooked.

I'm leaving a test app zip folder for you to test (just a `3.next` cakephp/app dowload with the version number for cakephp/cakephp pinned to `3.6.0-beta1`)
Just `composer install` it and fire it up with a `bin/cake server`. 
There are `debug` calls in the `routes.php` and `bootstrap.php` files for both plugins. You will see that routes are correctly called, but only the bootstrap of `PluginA` is loaded.

Here is the app :

[test-bootstrap-plugins.zip](https://github.com/cakephp/cakephp/files/1780869/test-bootstrap-plugins.zip)

My knowledge of the internal is not really up to date but I suspect this is a side-effect of this PR : https://github.com/cakephp/cakephp/pull/11785

Note that in my real app scenario, the `PluginA` would be loaded using the new "plugin class" concept but the `PluginB` is loaded using the `Plugin::load()` method since I do not control how this last plugin is implemented but the effect is the same.

Right now I'm avoiding the issue by manually calling the bootstrap files needed.

**Comment by markstory** [comment]
I'll take a look.
