### ISSUE TITLE
Optionally remove query params from Paginator urls

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#11799]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.12
* Platform and Target: PHP 7.1.2

### What you did
I added a call to `numbers()` to the bottom of my template.
```php
echo $this->Paginator->numbers();
```

### What happened
The link generated included the sorting and direction paging params as query params.
`http://example.com/news?page=2&sort=Contents.published&direction=desc`

### What you expected to happen
I was expecting to see just a page query param
`http://example.com/news?page=2`

### My use-case
The use-case which lead me to submitting an issue, is that we do not allow the user to sort the news articles on our site. Therefore we have no UI to allow sorting, and as a consequence do not need to show the sorting or direction query params in our urls. As these are defined by us in the controllers Paginator configuration.

### Security risk?
I'm not sure if it counts as a viable attack vector, but I'm not comfortable with the default behaviour exposing my schema via the url. `Contents.published` maps directly to my data store. There is no way for me to map or obfuscate these query params, like there is with the FriendsOfCake/Search plugin.

It seems odd to have a sortWhitelist, but no way to map those whitelisted params to finder/query fields.

### Sidestep solution
In order to sidestep the problem I have had to create my own PaginatorHelper which extends the existing one and overload the `PaginatorHelper::generateUrlParams()` method in order to unset the query params which I do not want to appear in the url.

### RFC
I would like to propose that the Paginator helper be updated to allow more user configuration of the query params, their usage and how they appear in the url, it at all. As I wouldn't have a problem exposing the param in the url if I could configure it. It would also allow me to make my urls neater for pagination which sorts on associations.

**Comment by ADmad** [comment]
What your current URL, have you set any default order through paginator component options?

**Comment by dereuromark** [comment]
There is no security risk.
The issue would also resolve itself once my proposal gets implemented - see https://github.com/cakephp/cakephp/issues/10028#issuecomment-272812357 and following discussion.

**Comment by davidyell** [comment]
> What your current URL, have you set any default order through paginator component options?

Yes, I have. 

```php
        $query = $this->Contents->find()
            ->contain([
                'ContentAttachments',
                'ContentTypes',
                'ContentCategories',
                'ContentAuthors',
                'ContentTags'
            ])
            ->where([
                'Contents.content_type_id' => $type
            ]);

        $contents = $this->Paginator->paginate($query, [
            'order' => ['published' => 'desc'],
            'sortWhitelist' => ['published'],
            'maxLimit' => 20
        ]);
```

**Comment by ADmad** [comment]
If you are not generating sorting links then just you use `$query->order()` instead of `order` option to set the order and your issue will be solved.

**Comment by davidyell** [comment]
Sorry @ADmad that didn't work for me. The links are still generated with the paging query params.

**Comment by ADmad** [comment]
You stated above you are using 3.5.12, check with 3.5.13.

**Comment by davidyell** [comment]
Sorry @ADmad but upgrading to `3.5.13` exhibits the same behaviour, my links are generated with the paging params as query params.

**Comment by dereuromark** [comment]
My https://github.com/cakephp/cakephp/pull/12745 fixing this?
Please close then.
