### ISSUE TITLE
Add new fetch methods

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#11795]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: All

### What you did

Example code:

```php
$driver = new \Cake\Database\Driver\Mysql($config);
$connection = new \Cake\Database\Connection(['driver' => $driver]);

$query = $connection->newQuery()->from('books')->select(['id', 'title']);
$rows = $query->execute()->fetch('assoc');
```

### What happened
I try to get the result as array. It would be nice to have a special and strongly typed method to fetch arrays, objects and field values. Passing the string `assoc` is not very pretty, error-prone, redundant and requires more typing. 

### What you expected to happen

It would be very practical to offer these new methods in the [StatementInterface](https://github.com/cakephp/cakephp/blob/master/src/Database/StatementInterface.php).

```php
public function fetchAssoc(): array;
public function fetchColumn(int $column = 0);
public function fetchObject(string $class = 'stdClass');
public function fetchObjects(string $class = 'stdClass'): array;
```

### Usage

```php
// fetch all rows as array
$rows = $query->execute()->fetchAssoc();

// fetch the column value of the first row
$column = $query->execute()->fetchColumn(0);

// Fetch the first row as stdClass
$object = $query->execute()->fetchObject();

// Fetch all rows as array of stdClass
$objects = $query->execute()->fetchObjects();
```

**Comment by odan** [comment]
Thank you very much for adding the new `public function fetchAssoc()` method.

My only concern is that it does not always return an array, because `false` is a boolean data type. I don't think a return type should be mixed. Instead, it would be better to return an empty array than `false`. Checking the result if it's not `false` requires more casting logic after the query.

Is there a way to set the return type to array (in every case)?

`public function fetchAssoc(): array`

**Comment by markstory** [comment]
>Is there a way to set the return type to array (in every case)?

There is probably a way. Just needs some more code :smile:
