### ISSUE TITLE
Migration_diff does not exist in v3.5

### ISSUE THREAD

**Issue by mickeyze** [cakephp/cakephp#11798]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Platform and Target: Apache2, php7.2.2, mysql

### What you did
Hi there, 
I want to execute migration_diff in console but it seems such option is not supported in v3.5. It worked in 3.4 without problems. 

### What happened
 # bin/cake version
3.5.13
 # bin/cake bake migration_diff MyAgents
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- behavior
- cell
- component
- controller
- fixture
- form
- helper
- mailer
- middleware
- migration
- migration_snapshot
- model
- plugin
- shell
- shell_helper
- task
- template
- test

By using `cake bake [name]` you can invoke a specific bake task.
 # 

### What you expected to happen
Migration_diff is defined in the Red Velvet Cookbook for version 3.5 but I cannot execute it. https://book.cakephp.org/3.0/en/migrations.html#generating-a-diff-between-two-database-states

**Comment by dereuromark** [comment]
Did you load the https://github.com/cakephp/migrations plugin as documented?

**Comment by mickeyze** [comment]
Yes, it is loaded. 


In bootstrap.php:
**Plugin::load('Migrations');**

In compoer.json file:

    "require": {
        "php": ">=5.5.9",
        "cakephp/cakephp": "*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "*",
        "cakephp/plugin-installer": "*",
        "cakephp/acl": "^0.1.0",
.....

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#352
