### ISSUE TITLE
Template entity access

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#11792]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.12
* Platform and Target: PHP 7.2.1

### What you did
I tried to call `Entity::get()` on a non-existent property. [This method](https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L279).

An example might be a Catalog, which has associated Content, which also has associated Advertising.

```php
$catalog->get('content')->get('adverts')
```

### What happened
My application failed with a fatal exception. Because I tried to access an empty property. 
`Cannot call get() on null`

### What you expected to happen
I would expect a way to allow for optional associations, without having to include lots of state checking into my templates.

### How am I sidestepping the issue?
```php
if (!empty($catalog->get('content')) && !empty($catalog->get('content')->get('adverts')) {
   // Output the adverts
}
```
This is what I am having to put into my templates to ensure that I can sidestep the potential fatal. Which, as you can imagine soon gets out of hand with many levels of associations.

I also have to consider my front-end developer colleagues whos primary language isn't PHP, and this could seem confusing. Or even worse, if they copy and paste incorrectly, they'll prevent an entire page from rendering.

### Proposition
I'm hoping for some discussion, but I have had a few chats in Slack about the issue. Usually born out of frustration because I forget to include all the `isset()` or `!empty()` checking, and hit a fatal.

#### Solution 1 (via @hmic)
The general gist of the conversation that @hmic and I had was the inclusion of an entity trait which would allow the entity to avoid the fatal and instead just return null and prevent any further `get()` calls from happening. This was only if the complete association was resolvable would anything be returned.

#### Solution 2 (via @dereuromark)
Marks idea was to create functional separation in the entity with something like `get()` and `getIfExists()`. Which would allow for more flexibility in how the developer wanted to interact with the entity. Alternatively adding an extra param to `get($property, $defaultReturnValue)` to allow for overriding.

### RFC
Adding a new method is my favourite, as it maintains BC, and creates a nice functional separation in the api, with clearly defined behaviours, which are obvious from reading the code.

Please add any thoughts you have on this topic, and if you've struggled with this fatal exception yourself how you have coped with it in your templating.

**Comment by inoas** [comment]
`getIfExists()` is a bit verbose. What about `read()` or `fetch()` or `query()` or something like that. You will find a better verb ;-)

**Comment by hmic** [comment]
https://api.cakephp.org/3.5/class-Cake.ORM.Entity.html#_has

!$catalog->has('content') ? null : !$catalog->content->has('item') ? null : $catalog->content->item

**Comment by raul338** [comment]
You can use [Hash::get](https://api.cakephp.org/3.5/class-Cake.Utility.Hash.html#_get) or write a wrapper like this

```php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Utility\Hash;

class AppEntity extendes Entity
{
    function getDeep($property, $default = null)  {
        return Hash::get($this, $property, $default);
    }
}
```

You would use it like `$catalog->getDeep('content.adverts')` and would return null if not exists

**Comment by markstory** [comment]
Another way around this is to use Twig templates. In a non-strict variables mode they smooth over these kinds off issues.

**Comment by inoas** [comment]
I am no fan of the no-strict modes however. That's something you run in production maybe but nothing I'd rely on as a feature TBH.

What would be wrong with a method?

**Comment by markstory** [comment]
> What would be wrong with a method?

Nothing is wrong with a method. There was an attempt to add dot paths to `get()` but it didn't get merged because the `set()` changes were very complicated, and I wasn't a fan of breaking the symmetry of those methods.

**Comment by dereuromark** [comment]
read() makes sense IMO, it is consistent with other places where read()/find() are soft getters, and get() always a hard one (existing otherwise exception).

**Comment by inoas** [comment]
So this could work?
`$catalog->read('content')->read('adverts', 'hello-world')`
Would return null (by default) if $catalog has no 'content' else would return `'hello-world'` if content has no `'adverts'` but returns catalog.content.adverts is a continous existing path it just returns that value.

**Comment by dereuromark** [comment]
> $catalog->read('content')->read('adverts', 'hello-world')

That is a very bad idea. If you chain, you should never use a soft read, otherwise you run into a null->object fatal error which is worse than what you currently get.

**Comment by inoas** [comment]
So what about returning a NotExistingObject that just implements read and default values in case of no value found?

**Comment by dereuromark** [comment]
Not feasable, what if you do all other methods on the entity that "should exist"?
In these cases maybe helpers or elements with conditional output might be better suited.

**Comment by inoas** [comment]
So you consider dot-path access the better way? though markstory hinted that it was deemd to complex to do?

**Comment by dereuromark** [comment]
Yes, that would be the better way - you can try giving this a shot for this specific use case.

**Comment by inoas** [comment]
@markstory maybe instead of breaking the symmetry just name it `fetch()` or `read()` (instead of adding more functionality to `get()`) which takes the dot notation and will return null if nothing is found?

**Comment by markstory** [comment]
Having a different name would avoid the symmetry issues that dot path `get()` has.

**Comment by ogrrd** [comment]
My vote would be for a fetch() or read() method which supports dot notation, and as @markstory says, avoids the symmetry break from adding dot support to get().

I think I'd prefer fetch() as it semantically can be differentiated from read(), as this data is being pulled out via classes and methods, whereas read() is used elsewhere, e.g. Configure::read(), which I think indicates it's more simply reading from a defined array.

**Comment by hmic** [comment]
I'd opt for read() with dot notation. Just *like* Configure::read() does too! Sounds like a perfect fit!

**Comment by ogrrd** [comment]
@hmic ah, I stand corrected. In which case, yes, my vote would be for consistency with ::read().

**Comment by inoas** [comment]
@jeremyharris would that work with LazyLoad behavior anyway?

**Comment by jeremyharris** [comment]
@inoas the lazy load plugin uses the entity `->get()` method, so a new method would require adding support in the lazy load plugin *unless* the new method uses `->get()` to fetch the values, which I'm guessing it will in order to respect accessors. I don't quite remember how the original PR did it.

Since I'm here, I'll toss a new method name in the mix: `getSafe()`/`getDeep()`. The only issue I have with using the work "safe" is that devs might assume that it's also escaping, but a docs could clear that up.

**Comment by dereuromark** [comment]
So we are back to read() then, which would be consistent to Session::read() and Configure::read() that allow the exact same syntax :)

**Comment by markstory** [comment]
@jeremyharris raised a good point about accessors. How do folks see accessors interacting with deep properties? Does each accessor in the property chain get invoked, or does only the leaf property have its accessor called?

**Comment by jeremyharris** [comment]
Here's a link to the original RFC: https://github.com/cakephp/cakephp/pull/7847

@markstory I would expect it to call the accessors, which by the looks of the code in the RFC it was.

One thing I don't see as clear from the RFC is how it would work with an array, like a 1:n association. Maybe I'm just missing it..

**Comment by inoas** [comment]
I'd like to add to the open questions if it wouldn't only call accessors but also if it would work with virtual properties (which could very well act as a switch between associations?).

As for 1:n I'd say the dot notation should not do that because that could easily become 1:n:n:n etc.
Just let the author of templates handle it with conditions and loops?

**Comment by hmic** [comment]
I think the dot notation handles 1:n just well, if you know the index, like: 
`book.chapter.0.page.2.headline`
I don't think we should discuss optional or conditional accessor access too. It's how the entity interface is supposed to work and I'd not see the need to change it intentionally, except there are special cases that need handling anyways. If the author of a template chooses to implement additional loops and conditions, that's fine. but nothing this read() method would either be needed for, nor could potentially cater for in a sane way. Additionally,you can just use the Collection to get your custom handling done in many of these cases with ease.

**Comment by davidyell** [comment]
I would expect the method to work on any entity, even if it's nested, making the following comparable.

```php
$catalog->get('content')->read('adverts.0'); // returns AdvertEntity
$catalog->read('content.adverts.0') // returns AdvertEntity
```

As for the chain, wouldn't the method fail on the first property which doesn't exist, and then return either `null` or the configured default value?

**Comment by hmic** [comment]
@davidyell that's my understanding too, if the chain fails in any point, it should return null.

**Comment by inoas** [comment]
Ah I got you guys wrong. I meant that `book.chapter.{n}.page.{n}.headline` should not work, should that?

**Comment by dereuromark** [comment]
Void with a getter? Why would that ever make any sense?

**Comment by inoas** [comment]
`null` is a valid value and you would not know if you got `null` or no-value. We could also return an object to test against that on __toString() becomes '' - but why not just use void to make it easy to check if a value exists - or add `check()` or `exists()`?

**Comment by hmic** [comment]
@inoas:
`null` is what you want in return if not found.

Additionally, like I told before - API consistency is king! The other common places where you use `read()` with dot notation act the same, returning null in these cases.
I actually don't see a usecase for `void` like @dereuromark mentioned too. Methods that are **not** supposed to return anything use void to indicate this, but you actually expect this to return something!

**Comment by raul338** [comment]
> null is a valid value and you would not know if you got null or no-value. We could also return an object to test against that on __toString() becomes '' - but why not just use void to make it easy to check if a value exists - or add check() or exists()?

`Hash::get` (which `configure::read()` uses)  does return null if the path does not exists or if the value is null
```php
$array = [
    'nullValue' => null,
];
Hash::get($array, 'nullValue'); // null
Hash::get($array, 'notExists'); // null
```
I prefer to stick with that approach

Also Hash::get does not support `{n}` notation, so it would be a better option than extract (also extract always return array)

**Comment by rchavik** [comment]
Since this is mostly concerning the view layer, why not create a EntityHelper, or even just a short function `__e()`, similar to `h()`,  `__d()`.

Eg:

```php

// instead of the following
if (!empty($catalog->get('content')) && !empty($catalog->get('content')->get('adverts')) {
   // Output the adverts
   echo h($catalog->content->adverts->name);
}

// we do this:

<?= __e($catalog, 'content.adverts.name') // return escaped `$catalog->content->adverts.name` or return empty string when content or adverts is missing ?>

```

We don't modify the entity class at all

**Comment by xaphalanx** [comment]
Option 3.  

 Make the orm lazy loader default behaviour or a  configurable option in core.

Sometimes tracking all your eager loaded objects is too much to track.

**Comment by josegonzalez** [comment]
@xaphalanx that doesn't help for cases where the related record doesn't exist in the database, and also doesn't help in cases where you might not be chaining calls on an entity but instead something else.

**Comment by jeremyharris** [comment]
@xaphalanx as the creator of the lazy loader, I would 👎 making it the default. It's not (yet...?) robust enough to handle 1:n efficiently, and making it the default would cause all sorts of "cake is slow" comments. Last thing I want is to be responsible for someone doing 1K queries where 3 would suffice :D

**Comment by xaphalanx** [comment]
> Please add any thoughts you have on this topic, and if you've struggled with this fatal exception yourself how you have coped with it in your templating.

There are two layers of complexity for me when I think about property checking: 1) associations are eager loaded so in my template I have to know what tables I've selected, and 2) I have to know what what columns were selected -- just because I have an entity doesn't mean it has all it's properties.  If I have an entity with a isPublished() method, I already have to check for the existence of the necessary properties and throw an exception if they are not present before doing the logic to determine if it is published. If I didn't do that checking, I could return true/false erroneously if some other developer uses select() on the query. Given these 2 problems, I'm questioning complex entity property checking in a template as a strategy. 

Here are somethings I've done instead of property checking when I've run into this issue:

1. If I am 3 layers deep in a view, I'd be thinking about the data and whether or not I am accessing it efficiently in the first place. Is there a join table I could use as the primary table in my query? 

2. If I determined I really did need that data in that shape, then I'd think about running a reducer(s) to transform the data passed to the view -- setting defaults along the way -- and passing the result to the view.

3. A lazy loader in the case of a complex system where it is difficult to determine all the things needed upfront makes some sense to me as a stop gap solution.

I wouldn't want to debug a problem where I called get() and a default value set in a template was used instead of the valid value stored in the database because a developer used select() or failed to contain() the associated entities.

There is a lot of developer preference in this issue around whether calling a variable in a view that is not set should stop execution or not. I prefer stopping execution.

**Comment by dereuromark** [comment]
How about getOrFail() as not nullable and current get() as nullable one?
This way it is in sync with the rest of the classes and their API here.

**Comment by dereuromark** [comment]
Is there any interest in providing a PR for my recommended strategy?

If you feel strongly about clean code, you can also transform into [DTOs](https://github.com/dereuromark/cakephp-dto) and use those then to iterate through the content with all the type-safety and sanity checks in place.

**Comment by dereuromark** [comment]
I added a Trait idea to Shim plugin as enhancement PR:
https://github.com/dereuromark/cakephp-shim/pull/48

This would basically enable this. Should this be a core trait? Or remain as plugin?

**Comment by saeideng** [comment]
>How about getOrFail() as not nullable and current get() as nullable one?

@dereuromark `null` is valid value for entity 
so `getOrFail()` should accepts the `null` IMO
probably we able to use `getChild()` naming for this purpose  
`getChild()` should returns en entity , runTimeError/exception  in other types

**Comment by davidyell** [comment]
@dereuromark Your solution doesn't seem to cover nested associated data.

**Comment by dereuromark** [comment]
It does. Or how u you mean? You chain it.

**Comment by garas** [comment]
Trait would require _try-catch_ which is even worse in templates.

In such case I use `$entity->deep->deeper->deepest ?? null` which also let you have autocomplete and typehints.

**Comment by dereuromark** [comment]
I think both @saeideng and @garas you misunderstand the key concept of the trait.
This is NOT about the nullable use case, but the non-nullable one. The use case where you expect (!) the values to be present.

Status quo: Any entity property can be null, any. If you forget to hydrate it (select without that field), then it will silently be null. The null pointer exception is usually worse than a clear exception thrown by the trait.

As such, this aims not to remove/replace nullable usage, but in fact adds support for proper and safe non-nullable (chaining) usage.

**Comment by dereuromark** [comment]
I clarified the importance and how it completely works together nicely with IdeHelper in https://github.com/dereuromark/cakephp-shim/releases/tag/1.8.0
If we do not plan a core adaption here, we can close this ticket then.

**Comment by saeideng** [comment]
>Trait would require try-catch which is even worse in templates.

true
another suggestion can be this method
`$entity->getX('child','child2','child3',...)`
this will return the last `child` or `null`  otherwise

**Comment by dereuromark** [comment]
You are free to further enhance the API or provide alternative traits/methods here, also for dot syntax for example: `getOrFail('foo.0.attributes')` etc.
But yeah, you need to be aware of all environment variables here, and for me IDE support is a major concern, as it should be also easy to use for developers, apart from the importance of static analyzers being able to precheck code for less mistakes/bugs.

**Comment by saeideng** [comment]
I intentional did not suggest the dot syntax
I think we can not use dot syntax in entity's property

**Comment by markstory** [comment]
Entity::get() with paths has been attempted a few times in the past and it isn't a simple problem to solve.

I've never personally experienced this pain as I long ago switched to Twig based templates which automatically handle these null reference scenarios. Have other folks with this problem considered that as a solution?

**Comment by dereuromark** [comment]
This is not only for templates but also static analyzing. See my linked shim pr and examples. 
This fixes usage across the whole app.

**Comment by davidyell** [comment]
> This is NOT about the nullable use case, but the non-nullable one.

This is outside the scope of this RFC in my opinion, as it's specifically concerned with the templates throwing exceptions. Which is why your trait would not be a good inclusion to the core for this RFC, as it is replicating the existing exception throwing present in the core already.

**Comment by davidyell** [comment]
Thanks to everyone who contributed to the discussion. If the core team would still like to pursue the discussion do feel free to re-open the RFC.

**Comment by dereuromark** [comment]
Sry, I misunderstand the 2nd part of your request.
Please see https://github.com/dereuromark/cakephp-shim/pull/49 to complete the first trait now.

As per those methods, you can now chose in the template if you require the path to be present (required fields), or if you are OK with part of the path being null and silently just returning null here, skipping the !empty() checks in the middle.

That should now be in line what you suggested and what we discussed earlier here.
