### ISSUE TITLE
2.x validator()->remove('field', 'rule') fails when rule does not exists (anymore)

### ISSUE THREAD

**Issue by WrDX** [cakephp/cakephp#11808]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 2.10.8

### What you did
Removing a rule from the validator while the rule does not exist (anymore).
```php
$this->validator()->remove('field', 'rule');
```

### What happened
It fails with an "undifined index" when the rule does not exist, for instance it was previously removed by
```php
$this->validator()->remove('field');
```

### What you expected to happen
The same as removing a full rule, nothing. Since removing a full rule uses unset(), this will not result in an error if the rule does not exist.

**Comment by dereuromark** [comment]
PR open.
