### ISSUE TITLE
ServerRequest withAttribute / getParam fail in 3.6

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#11806]
* [x] bug
* CakePHP Version: 3.6.0-beta1

Updating to the 3.6.0-beta1 with my app, some unit tests failed

```
        $this->request = $this->getMockBuilder('Cake\Http\ServerRequest')->getMock();
        $this->request->withAttribute('params', ['controller' => 'Users']);
        debug($this->request->getParam('controller'));
```

I would expect `Users` out in debug, `null` returned.

**Comment by HavokInspiration** [comment]
`ServerRequest` objects are now immutable. You should do :

```php
$this->request = $this->request->withAttribute('params', ['controller' => 'Users']);
```

**Comment by LubosRemplik** [comment]
This is not working for me since both `withAttribute` and `withParam` returned `null` and what ever I try then I get error I am trying to call function on null, e.g. 
```
Error: Call to a member function getParam() on null
```

I am pasting Test class where I am having this problem
https://gist.github.com/LubosRemplik/c79fc56571d00a403384785b94ec6e7d#file-gistfile1-php-L42

**Comment by dereuromark** [comment]
Mocking it sure aint a good idea :)
Without actually then adding the correct "returns" parts for each method of course you will always get null back.

**Comment by LubosRemplik** [comment]
You are right, once I create object normally and do not mock, it works fine.
Sorry about raising issue, it is not problem with `ServerRequest` but with Test class.
