### ISSUE TITLE
Paginator links without trailing slash redirect to /webroot/url

### ISSUE THREAD

**Issue by mspeener** [cakephp/cakephp#11803]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Platform and Target: Apache 2.4.29

### What you did
I navigate to /customers which is paginated. URL's for the paginator are generated thusly:

`echo $this->Paginator->numbers(['first' => 2, 'last' => 2, 'modulus' => 2]);`

### What happened
Clicking a paginator link takes me to /webroot/customers/?page=3

Mousing over the link shows the url as /customers?page=3  

If I change the URL in the bar to /customers/?page=3, or, /customers/index?page=3 it works fine.  

### What you expected to happen
Link should take me to /customers/?page=3 which works, or, /customers?page=3 and it should work as expected instead of redirecting. 

### Additional info.
I'm pretty sure this used to work properly.  I double-checked DocumentRoot .htaccess and it's the stock one from the install documentation. The webroot one is as well.

It seems to only affect /index when it isn't explicitly called in the url. If I add /index?page=3 to the url it's fine but the paginator strips /index from the url when it generates the numbers so the issue just repeats on subsequent paginator number clicks.

**Comment by mspeener** [comment]
I don't know. I'm sure this wasn't happening "before" but I don't know when it started happening.

**Comment by dereuromark** [comment]
Maybe there is some outdated/special .htaccess rewrite configuration in this case?
Check the app repo for a current one (recommended).
Also, you shouldn't use any trailing slash and let apache 301 redirect those to the non trailing slash one.

**Comment by mspeener** [comment]
UPDATE: I did a fresh cake install with composer and pulled my code to it and it's working fine. I compared .htaccess files and they are the same so it's something else. Right now I'm just glad it's working.
