### ISSUE TITLE
Connection aliasing doesn't work inside migration.

### ISSUE THREAD

**Issue by r34117y** [cakephp/cakephp#11802]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11

### What you did

I try to alias db connection (inside up() function in migration) to iterate over connections defined in app.php (this solution works in web app):

```
$conns = ['default', 'c1', 'c2'];

foreach ($conns as $conn) {
   ConnectionManager::alias($conn, 'default');
    //do migration stuff
}
```

### What happened
Aliasing doesn't work. All iterations use 'default' connection as defined in app.php

### What you expected to happen
Each iteration connects to different db, i.e. 'default', 'c1', 'c2' in given order.

**Comment by markstory** [comment]
Migrations don't use ConnectionManager from what I remember. Instead phinx uses your application configuration file to access the database with its own connection management code.
