### ISSUE TITLE
3.6: Plugins bootstrap not included while running phpunit

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#11816]
Looks like https://github.com/cakephp/cakephp/pull/11785 now causes to not load the plugins `bootstrap.php` file while running phpunit.
The application I upgraded from 3.5 contains a `Application.php`.

3.6.0-beta2

**Comment by markstory** [comment]
Do you need the bootstrap files included to define global constants or functions?

**Comment by markstory** [comment]
Ok. I had another solution for #11785 that involved tracking whether or not a plugin had its bootstrapping run. It involved tracking more state so I didn't go with it. I didn't consider the testsuite startup case though.

**Comment by markstory** [comment]
Pull request open now.
