### ISSUE TITLE
Error when applying functions on fields and using IN operator

### ISSUE THREAD

**Issue by pedro-stanaka** [cakephp/cakephp#11813]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.5.12
* Platform and Target: Homestead VM (ubuntu + nginx + php-fpm7.1 + MySQL)

### What you did

Made a simple query like this:

```php
        $nameVariations = [];
        $nameVariations[] = $title;
        $nameVariations[] = str_replace(' ', '', $title);
        $nameVariations[] = Text::slug($title, ['replacement' => '_']);
        $nameVariations[] = Text::slug($title, ['replacement' => '']);
        $nameVariations[] = Text::slug($title, ['replacement' => ' ']);

         $findResult = $this->find()->where([
            "REPLACE(Brands.title, ' ', '') IN" => $nameVariations
        ])->first();
```

Out of despair I also tried:
```php
        $findResult = $this->find()->where([
            "REPLACE(Brands.title, ' ', '')" => $nameVariations
        ], [
            "REPLACE(Brands.title, ' ', '')" => 'string[]'
        ])->first();
```
But no luck.

My final query looks correct (generated with **sql()** method): 

```sql 
SELECT
  Brands.id                     AS `Brands__id`,
  -- ... other fields
FROM brands Brands
WHERE (REPLACE(Brands.title, ' ', '') IN :c0 AND (Brands.deleted) IS NULL
```

From the tests I did here it seems like the Query builder is having trouble with SQL functions with multiple values as parameter. The following query also does not work:

```php
       $this->find()->where([
            'POW(Brands.id, 2) IN' => [1, 2, 3]
        ])->first();
```

### What happened
The code threw the following exception:

https://codepen.io/pedro-stanaka/full/pLvGzK/
![screen shot 2018-03-10 at 2 01 22 pm](https://user-images.githubusercontent.com/2609731/37244689-99de185a-246b-11e8-91d7-5d1014056e43.png)

### What you expected to happen
Expected the Query Builder to replace my array that looks like:

```php
[
	(int) 0 => 'Hellow Worldd',
	(int) 1 => 'HellowWorldd',
	(int) 2 => 'Hellow_Worldd',
	(int) 3 => 'HellowWorldd',
	(int) 4 => 'Hellow Worldd'
]
```

In the query, so it would look like:

```sql
SELECT
  Brands.id                     AS `Brands__id`,
  -- ... other fields
FROM brands Brands
WHERE (REPLACE(Brands.title, ' ', '') IN ('helloworldd', 'HellowWorldd') AND (Brands.deleted) IS NULL)
```

**Comment by markstory** [comment]
I'll take a look.

**Comment by lorenzo** [comment]
The problem is the use of spaces in the array keys of the conditions. Whenever you need to have functions or anything complicated as conditions, I recommend using the expressions builder (using a closure in the where function, for example)

You can use the expressions builder to safely create any function call and comparison you need.

Please let us know if you have questions about it

**Comment by saeideng** [comment]
```php
$this->Posts->find()->where(['Posts.id IN' => [1000, 2000, 3000]])->toArray();
```
uses `Cake\Database\Type\IntegerType`
with one value , `1000` for example
```php
    $this->Posts->find()->where([
     'POW(Posts.id, 2) IN' => [1000, 2000, 3000]
    ])->toArray();
```
uses `Cake\Database\Type\StringType`
with bellow values 
```php
[
	(int) 0 => (int) 1000,
	(int) 1 => (int) 2000,
	(int) 2 => (int) 3000
]
```

**Comment by saeideng** [comment]
>My final query looks correct (generated with sql() method):

your problem occur in `bindvalue` time but `sql()` returns `sql` without binding value

**Comment by pedro-stanaka** [comment]
Just to document my solution here and to help others who might have the same error I ended up using the following solution:

```php
        $nameVariations = [];
        $nameVariations[] = $title;
        $nameVariations[] = str_replace(' ', '', $title);
        $nameVariations[] = Text::slug($title, ['replacement' => '_']);
        $nameVariations[] = Text::slug($title, ['replacement' => '']);
        $nameVariations[] = Text::slug($title, ['replacement' => ' ']);

        $function = new FunctionExpression('REPLACE', ['Brands.title' => 'literal', ' ', '']);
        $comparison = new Comparison($function, $nameVariations, 'string[]', 'IN');

        $findResult = $this->find()->where([
            $comparison
        ])->first();


        dd($findResult);

        return $findResult;
```

IMHO this should be easier to do. I had to navigate through a lot of source code of the ORM to understand how to do it. It was not difficult to me, but for beginners of the FW this would be hard.

@lorenzo is there a easier/cleaner way to do that? 

Thanks for your work, despite of everything the ORM is a BEAST!

**Comment by markstory** [comment]
@pedro-stanaka You can use the function builder to avoid constructing expressions by hand.

```php
$nameVariations = [
    $title,
    str_replace(' ', '', $title);
    Text::slug($title, ['replacement' => '_']),
    Text::slug($title, ['replacement' => '']),
    Text::slug($title, ['replacement' => ' ']),
];

$query = $this->find()->where(function ($exp, $query) use ($nameVariations) {
    $replace = $exp->func()->replace(['Brands.title' => 'literal'], ' ', '')

    return $exp->in($replace, $nameVariations);
});
```

I've not run this, but it should get close to doing what you're looking for.

**Comment by pedro-stanaka** [comment]
@markstory Thanks! The code was a little off, my final solution and I am happy with it looks like this:

```php
       $findResult = $this->find()->andWhere(function (QueryExpression $exp, Query $query) use ($nameVariations) {
            $replace = $query->func()->replace(['Brands.title' => 'literal', ' ', '']);

            return $exp->in($replace, $nameVariations);
        })->first();
```

That magic method there (FunctionBuilder::_call) at the end of the class skipped my eyes. 😉 

Thanks for the help, hope this help someone in the future, closing the issue as it was not a problem with CakePHP itself.
