### ISSUE TITLE
3.5 content of text email is not included when sending email

### ISSUE THREAD

**Issue by Yetispapa** [cakephp/cakephp#11823]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Platform and Target: Apache/2.4.28 on Mac

### What you did
I want to send a multipart email. In order to do that I set the emailFormat to 'both'. Here the code how I send the email.

```
$email = new Email($this->_transport());
$email->from([$this->_from => $this->_name])
	->template('myEmail')	
	->helpers(['InlineCss'])
	->viewVars(['firstname' => 'Kirk'])
        ->to($to)
        ->subject($subject)
	->emailFormat('both')
        ->send();
```

My templates and layouts structure:

## Templates:

**src/Template/Email/html/myEmail.ctp**

```
<div class="content">
	<h1>
		<?php echo htmlentities('Hello ' . $firstname); ?>
	</h1>
</div>
```

**src/Template/Email/text/myEmail.ctp**

`<?php echo htmlentities('Hello ' . $firstname); ?>`

## Layouts:

**src/Template/Api/V1/Layout/Email/html/default.ctp**

```

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
    <title><?= $this->fetch('title') ?></title>
</head>
<body>
    <div class="main">
         <?= $this->fetch('content') ?>
    </div>
    <div class="footer">
         <?php echo htmlentities('Copywrite © 2018 Name here'); ?>
    </div>
</body>
</html>
```

**src/Template/Api/V1/Layout/Email/text/default.ctp**

```
<?php

$this->fetch('content');
-----------
echo "\n";
echo htmlentities('Copywrite © 2018 Name here');

?>
```

I send the email from a controller which is also in the V1 structure. 
`src/Controller/Api/V1/EmailController.php`

### What happened

Unfortunately the text email has not the content from the template included. So it's just the layout without the content of **src/Template/Email/text/myEmail.ctp**. So it would look like this:

```
 -------
Copywrite © 2018 Name here
```

The html email works as expected. Also when I try to switch to the emailFormat('text') it does not work. I digg into the Cakephp code and found out that on the following line he wipes out the content for the text email.

**vendor/cakephp/cakephp/src/View/View.php (1164)**
`$content = $this->_evaluate($viewFile, $data);`

Also I'm wondering why I don't have to add a structure for the templates like I did for the layout. I mean like **src/Template/Api/V1/Email/text/default.ctp**. But that's just a minor question cause the code is grabbing the right template.

### What you expected to happen
The text email should behave like the html email does.

**Comment by markstory** [comment]
You are missing an echo on fetch() in your layout.

**Comment by Yetispapa** [comment]
Thanks @markstory!
