### ISSUE TITLE
HTTP response returning null string

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#11828]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

```
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.1.15-1+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Mar  6 2018 11:10:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.15-1+ubuntu16.04.1+deb.sury.org+2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sdustinh@sdustinh:~/github/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
cakephp/bake                1.6.3  Bake plugin for CakePHP 3
cakephp/cakephp             3.5.12 The CakePHP framework
cakephp/cakephp-codesniffer 3.0.3  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.4  A simple API extension for DateTime.
cakephp/debug_kit           3.14.1 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.7.2  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.1.0  A composer installer for CakePHP 3.0+ plugins.
```

### What you did

```php
// Controller
public function add()
{
    $scopes = $this->Scopes->find()
        ->where(['Scopes.id IN' => $this->request->getData('scopes')])
        ->notMatching('Users', function ($query) {
            return $query->where(['Users.id' => $this->user->get('id')]);
        })
        ->toArray();

    if ($scopes === []) {
        return;
    }

    $this->response = $this->response->withStatus(201);

    if ($this->Users->association('Scopes')->link($this->user, $scopes) === false) {
        $this->response = $this->response->withStatus(400);
        $this->set('errors', $this->user->getErrors());
        $this->set('_serialize', ['errors']);
    }
}

// Test
public function testAdd()
{
    $data = ['scopes' => [1, 2, 3]];
    $this->post('/api/v1/users/1/scopes', $data);
    $this->assertResponseCode(201);
    $this->assertContentType('application/json');
    $this->assertResponseEmpty();
}
```

### What happened

All of the test passes until that `$this->assertResponseEmpty()` call. That fails with: `Failed asserting that a string is empty.`

### What you expected to happen

I didn't expect it to fail. I thought maybe something was being set that I didn't notice so I changed my test to the following:

```php
public function testAdd()
{
    $data = ['scopes' => [1, 2, 3]];
    $this->post('/api/v1/users/1/scopes', $data);

    dd((string)$this->_response->getBody());
    
    $this->assertResponseCode(201);
    $this->assertContentType('application/json');
    $this->assertResponseEmpty();
}
```

```bash
sdustinh@sdustinh:~/github/app$ vendor/bin/phpunit --stop-on-failure
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.15-1+ubuntu16.04.1+deb.sury.org+2 with Xdebug 2.6.0
Configuration: /home/sdustinh/github/app/phpunit.xml

/plugins/Users/Api/V1/tests/TestCase/Controller/ScopesControllerTest.php (line 70)
########## DEBUG ##########
'null'
###########################
```

It seems that a `'null'` string is being returned as the response instead of an empty string. I'm not sure if this is a failure in my code, the `Response` object, the assert method, or a combination.

**Comment by markstory** [comment]
Is the `errors` view variable `null`?

**Comment by sdustinh** [comment]
If the `errors` variable is set, they pass down as expected. I poked around on this a bit and found this...

```php
dd((string)null); // ''
dd((string)$this->_response->getBody()->getContents()); // 'null'
dd((string)$this->_response->getBody()); // 'null'
dd((string)$this->_response); // 'null'
dd($this->_response->getBody()->getContents()); // ''
$this->_response->getBody()->rewind();
dd($this->_response->getBody()->getContents()); // 'null'
dd((string)(new \Zend\Diactoros\Stream('php://memory', 'wb+'))); // ''
```

Then I remembered I still haven't  removed the `['_serialize' => true]` that used to be in the app skeleton. To verify that this was the problem I used the following to simulate how the `JsonView` serializes...

```php
// https://github.com/cakephp/cakephp/blob/3.next/src/View/JsonView.php#L163
$jsonSerialize = function ($viewVars, $specialVars) {
    $data = array_diff_key($viewVars, array_flip($specialVars));

    if (empty($data)) {
        return null;
    }

    return $data;
};

$data = $jsonSerialize([], ['_serialize', '_jsonOptions', '_jsonp']);
$jsonOptions = JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_PRETTY_PRINT;
$result = json_encode($data, $jsonOptions);

debug($data); // null
debug($result); // 'null'
```

It appears that an additional check in the [`_serialize`](https://github.com/cakephp/cakephp/blob/3.next/src/View/JsonView.php#L136) method for a `null` value will resolve this issue.

**Comment by markstory** [comment]
Wouldn't excluding null values potentially break other applications?

**Comment by sdustinh** [comment]
It is a possibility, I suppose, but what would be the proper action here?

* Change `assertResponseEmpty()` to pass even if the response has a length > 0
* Update `JsonView::_serialize` to cast `null` `$data` to a string
    * `json_encode((string)null, $jsonOptions) // ''`
* Make no changes and have the framework potentially generate invalid 204 responses

If a `null` slips through and makes its way to the `json_encode` which in turn generates a `'null'` response, it seems like not fixing it would be protecting the flaw. I searched for related issues and wasn't able to find any (not saying they aren't there, though) so I would assume that this is a super rare case or at least a situation that the majority of users are not concerned with.

Since the app skeleton defaulted to setting `['_serialize' => true]` for a good while you're right... there might be some unexpected behavior when users update their applications. However, wouldn't the worst case scenario here be their tests fail because their application is now returning a proper response?

**Comment by markstory** [comment]
> . However, wouldn't the worst case scenario here be their tests fail because their application is now returning a proper response?

Yes, but then we've 'broken' their code.

> If a null slips through and makes its way to the json_encode which in turn generates a 'null' response, it seems like not fixing it would be protecting the flaw. 

Isn't the flaw that your application is creating a response you don't want? You've effectively asked the framework to serialize a null which it has done.

**Comment by sdustinh** [comment]
Hmm, I guess you're right.

I assumed an empty response would be rendered as an empty response despite saying I wanted all view variables serialized. I would argue that the framework flaw is handling a scenario where I say serialize everything and there is nothing to serialize.

I didn't mean to ruffle feathers here, but converting a literal `null` into a string `'null'` felt like a bug. I'll patch it on my end and you guys can close this issue out if you'd like.
