### ISSUE TITLE
View::extend() with plugin for element

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#11824]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

### What you did
I have a plugin called `MeCms` with the common view `src/Template/Common/Element/userbar.ctp` and I want to extend this common view.

### What happened
If I try to extend with this code:

    $this->extend('MeCms.Common/Element/userbar');

it looks for the view `src/Template/Plugin/MeCms/Element/Common/Element/userbar.ctp`.  
This already seems strange to me. Because it seems that the relative path is `Element/`.

If I try to extend with this code:

    $this->extend('MeCms./Common/Element/userbar');

it looks for the view `src/Template/Plugin/MeCms/Element//Common/Element/userbar.ctp` (note the double slash).  
In this case, it seems that Cake does not understand that the first slash indicates an absolute path (inside the `MeCms` plugin), but it appends it to the relative path.

Note. If I do not specify the plugin at all, like this:

    $this->extend('/Common/Element/userbar');

it works. However in my case I need to specify the plugin.

Moreover: as regards the `View::extend()` method, the [cookbook](https://book.cakephp.org/3.0/en/views.html#extending-views) does not contain explanations or examples regarding relative paths or plugin paths.

Is it a bug or am I doing something wrong?

**Comment by markstory** [comment]
Is this only an issue when your extending plugin elements? or does it also happen with view templates?

**Comment by saeideng** [comment]
`src/Template/Element/Common/userbar.ctp` is true for Element(s)

**Comment by mirko-pagliai** [comment]
@markstory 

> Is this only an issue when your extending plugin elements? or does it also happen with view templates?

This happens, in my case, only when I try to extend a common view provided by a plugin. 
More precisely, within an element I am trying to extend a view common to several elements.

@saeideng I can not understand what you mean

**Comment by markstory** [comment]
Elements historically have always been stored under an `Element` directory in the view template, or prefix directory. I don't think we've ever supported `/` based element names which allow you to escape the `Element` directory.

Because you're using `extend()` inside an element, you'll be contained inside those `Element` directories.

**Comment by mirko-pagliai** [comment]
So if I want a common view (`common_element.ctp`) that the elements will have to extend, the path should be

    Element/Common/common_element.ctp

and the code (supposing the common view is provided by the `MeCms` plugin) should be 

    $this->extend('MeCms.Common/common_element')

?

Is it right?

**Comment by markstory** [comment]
> Is it right?

Yes that should work.

**Comment by dereuromark** [comment]
You could also make a PR that would allow a leading slash to work the same inside plugins as it does for app project level. For me this would be logical and consistent.

**Comment by mirko-pagliai** [comment]
Thanks.

**Comment by dereuromark** [comment]
Also note that if you want auto-complete on this magic strings, you can write a similar task as I did for element() calls @ https://github.com/dereuromark/cakephp-ide-helper/releases/tag/0.11.0
Then you just have to type the first 1-2 chars and you can select from dropdown :)
