### ISSUE TITLE
Fatal error:  Cannot use 'object' as class name as it is reserved

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#11830]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.8
* CakeDC Migrations Plugin: 2.5.1
* Platform and Target: **PHP 7.2**

### What you did

The following command was executed on the console:

```bash
app>php Console/cake.php Migrations.migration genenerate -f --compare --overwrite --preview -c schema -i schema
```

### What happened
The command stopped with this error message:

```
Cake Migration Shell
---------------------------------------------------------------
PHP Fatal error:  Cannot use 'object' as class name as it is reserved in vendor\cakephp\cakephp\lib\Cake\Core\Object.php on line 18
PHP Stack trace:
....
```

## Possible (quick) fix

I removed line 18 in `Object.php`

```php
// class_alias('CakeObject', 'Object');
```

and changed line 16 in `CakeMigration.php` to

```php
class CakeMigration extends CakeObject {
```

It works again.

### What you expected to happen
No error message

**Comment by josegonzalez** [comment]
This was fixed in 2.9.0 - released 2016-10-18 - and the current stable line is 2.10.x. Please upgrade your CakePHP version to the latest 2.x release in order to get the fix.

**Comment by dereuromark** [comment]
If you have 2.x code running on 7.2 you must never use this class - under no circumstance.
You need to fix your code here, this is not a framework issue.
Maybe https://book.cakephp.org/2.0/en/appendices/2-9-migration-guide.html#deprecations should contain this requirement for 2.x code being used on PHP 7.2.

**Comment by dereuromark** [comment]
@josegonzalez He is using the latest version
The problem here is the plugin he uses which has an outdated and invalid Object usage ( https://github.com/CakeDC/migrations/blob/master/Lib/CakeMigration.php#L17 ).
See https://github.com/CakeDC/migrations/pull/311

**Comment by dereuromark** [comment]
Personally, I would use the latest 3.x migrations plugin in 2.x applications ( http://www.dereuromark.de/2016/10/03/use-3-x-migrations-for-your-2-x-cakephp-app/ ).
That will also make upgrading much easier in the (near) future.

**Comment by kamleshwebtech** [comment]
https://stackoverflow.com/a/63991371/10329023

**Comment by mehov** [comment]
I have an old 2.8.4 app and the solution is to upgrade to the latest 2.x ([2.10.24](https://github.com/cakephp/cakephp/releases/tag/2.10.24) right now)
