### ISSUE TITLE
render() is debug true not working.

### ISSUE THREAD

**Issue by tetsuyusan** [cakephp/cakephp#11849]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Platform and Target: apache2.4

### What you did
debug is true.
```AppController.php
$this->render('hoge');
```
It changes the view.

debug is false.

```AppController.php
$this->render('hoge');
```
It dosen't change the view.

if I change the code like this.
```AppController.php
return $this->render('hoge');
```
It changes the view.

I used https://book.cakephp.org/3.0/ja/controllers.html as a reference.

### What happened
Not change view for debug is true.

**Comment by tetsuyusan** [comment]
update.

**Comment by chinpei215** [comment]
I wasn't able to reproduce this issue. By the way, join #japanese channel on [our Slack](https://cakesf.herokuapp.com/) if you are interested. You can report bugs or ask questions in Japanese their. As far as I have read, I think you speak Japanese.

**Comment by markstory** [comment]
Closing until we get a way to reproduce this.
