### ISSUE TITLE
New entity should not bypass validation

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11854]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest master 3.5.x

### What you did
Somewhere in the code was a left over
```
$data = [
    ...
];
$modulesTable->saveOrFail($modulesTable->newEntity());
```

### What happened
Stored in DB as entity of content:
```php
		'id' => (int) 2,
		'name' => '',
		'version' => '',
```

It silently saved it without all the validation triggered, which is defined as
```php
        $validator
            ->requirePresence('name', 'create')
            ->add('name', 'unique', ['rule' => ['validateUnique', ['scope' => ['name', 'type']]], 'provider' => 'table'])
            ->notEmpty('name');

        $validator
            ->requirePresence('version', 'create')
            ->notEmpty('version');
```

### What you expected to happen
This should not allow to be saved with the constraints here not respected (in this case name and version being not empty).

What could be done here for the code to be less error prone (by accident) and make sure the entities are not persisted like this when accidentally forgetting to pass the $data?

Doesn't newEntity() patch just as patchEntity() does? And therefore does not accept this state?

**Comment by ADmad** [comment]
Validation would be triggered only if you pass `$data` argument to `newEntity()`, which isn't in your example.

**Comment by dereuromark** [comment]
Yeah, but the save() operation should then not persist still IMO. Some exception seems useful in these cases. Couldn't it then trigger the patching with empty array and see what happens?

**Comment by dereuromark** [comment]
The alternative is to remove the newEntity() optional argument and make the 1st arg always required.
Currently this is a dangerous thing, and should not continue to be allowed the way it is.

**Comment by lorenzo** [comment]
Making the first argument required is not a bad idea, we could explore that

**Comment by dereuromark** [comment]
A basic rule of DTO is also (according to clean code) that they should always be in a state of validity after creation (usually using constructor injection of data). Or at least contain then a state of "I cant be persisted".
So since none of this is the case, the DTO itself needs to be otherwise be made non-saveable.

**Comment by dereuromark** [comment]
For example a state of "notValidated" could be part of the entity, and if so, it would at least trigger an empty validation on save - which would prevent this empty one to be silently stored as OK (which it clearly is not from application rule setup).

**Comment by xaphalanx** [comment]
I view newEntity()/patchEntity() validation as "request" validation.
Entity validation to me are "rules".

Entities can exist in a non-valid state already because they can come from the database with a partial dataset.

I use newEntity() instead of new Entity from time to time and don't want validation to run and run it later with patchEntity(). I think the baked "add" methods use it this way too.

**Comment by dereuromark** [comment]
@xaphalanx 
But newEntity($data) is actually the same as patchEntity($x, $data) from the point of validation.
I can see your point. And maybe we can find a way for the entity to keep the internal state of knowing whether at least basic validation has been run yet.

**Comment by xaphalanx** [comment]
->wasValidated() && ->hasErrors() instead of just ->hasErrors() which might create issues. That would be handy. Would it know if it had new dirty properties since validation ran and return false?

**Comment by JoshuaLuckers** [comment]
I would also love to see a wasValidated and hasErrors method. At the moment I'm having a large collection of entities and nested associations. Saving the entities takes a very long time because of this function: https://github.com/cakephp/cakephp/blob/d99756209299cd3c076ad418c795659420e448e0/src/ORM/Table.php#L1905,L1907

Uncommenting the function makes saving a lot faster. A faster way to check for errors would be great. 
Especially when we use `'validate' => false` when using `newEntity()` and/or `patchEntity()`.

**Comment by lorenzo** [comment]
@JoshuaLuckers do you have any pointers on how to make that function faster?

**Comment by lorenzo** [comment]
Ah, you are right... just having `hasErrors` would be a lot faster

**Comment by JoshuaLuckers** [comment]
I would like to! I will look into it later this week.

Is there anything I should keep in mind?

**Comment by JoshuaLuckers** [comment]
> The alternative is to remove the newEntity() optional argument and make the 1st arg always required.
Currently this is a dangerous thing, and should not continue to be allowed the way it is.

A good alternative would be a method named `createEntity()` where the data argument is required and can not be empty/null.

**Comment by lorenzo** [comment]
> Is there anything I should keep in mind?
 
Nothing in particular, I think it should be an easy method to implement.

**Comment by dereuromark** [comment]
> Making the first argument required is not a bad idea, we could explore that

So do we want sth like this? Or a createEntity() method that includes validation then?
Or shall we do what I initially thought best: an initial "notValidated" state that must first be set to "validated"  in order for an "isNew" entity to be properly persisted?

**Comment by markstory** [comment]
Making the first argument required could break the method signature compatibility. We could however, run validation when the data argument is empty. This should break fewer applications and prevent invalid entities from being saved.

**Comment by dereuromark** [comment]
A similarly dangerous case we found today, where suddenly validation is not applied anymore:

Before
```php
$job = $this->Jobs->newEntity($array);
$this->Jobs->saveOrFail($job);
```
After
```php
$job = $this->Jobs->findOrCreate($array);
$this->Jobs->saveOrFail($job);
```

Now the save silently goes through without validation checking for cases where it shouldn't.
This is not directly documented there either.

Do we want to fix up that too, allowing a validation config key (default true for 4.x) for this method?

**Comment by lorenzo** [comment]
what about a new method? newValidEntity()

**Comment by saeideng** [comment]
@dereuromark looks your Issue is similar to https://github.com/cakephp/cakephp/pull/12914

**Comment by dereuromark** [comment]
Great to see you are around again :)
How about the other way around: Keeping newEntity() safe (especially since also newEntities() wraps this), and making createEntity() create a "dangerous" empty one?

Personally, I am still for a "persistable" flag that you have to manually set to "true" if you want to save empty rows that have not been patched in with actual data (and as such triggering vital validation).
But I can live with this compromise.

**Comment by saeideng** [comment]
>Keeping newEntity() safe (especially since also newEntities() wraps this), and making createEntity() create a "dangerous" empty one?

I'm :-1:  with this idea
instead we can have a flag into entity as `initialized` or something like this to detect that whether used or not
if it was 'false` , `save()` will not save  
after sending data for `newEntity()`/`patchEntity()` this flag will `true` , and normal behavior ...

**Comment by dereuromark** [comment]
Such a canBePersisted flag would also need to be manually settable (to true) then.
But this might have other edge cases.
Also, as I explained above, silently allowing null to trigger this on newEntity() method etc is super dangerous and unexpected.

We can still add my flag as a follow up to prevent accidental empty rows persisted. But those are separate topics either way IMO.

**Comment by dereuromark** [comment]
We now have two methods at least - for most cases this could suffice.
So I will close this for now.
