### ISSUE TITLE
CakePHP Union Problem

### ISSUE THREAD

**Issue by JMente** [cakephp/cakephp#11855]
Hi, after i'm migrate my website and update the components for PHP7.2 and MariaDB 10.2 my website have a problem when i'm login or query a model the next simple query

$users = $this->Users->query('SELECT * FROM siso_users WHERE email = ' . "'example@example.net';");

Throws me the next error:

[PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNION' at line 2

Please somebody help to fix this error.

**Comment by ADmad** [comment]
It's highly unlikely the error you have shown in generated by the query you have provided. It's generated by a query which has unquoted `UNION` keyword in it. 

You need to either update your table schema to not use SQL keywords as field names or turn on identifier quoting in database config.

**Comment by JMente** [comment]
The query generated is this:  _object(Cake\ORM\Query)#118 (14) { ["(help)"]=> string(65) "This is a Query object, to get the results execute or iterate it." ["sql"]=> string(531) "SELECT `SisoUsers`.`id` AS `SisoUsers__id`, `SisoUsers`.`first_name` AS `SisoUsers__first_name`, `SisoUsers`.`last_name` AS `SisoUsers__last_name`, `SisoUsers`.`email` AS `SisoUsers__email`, `SisoUsers`.`password` AS `SisoUsers__password`, `SisoUsers`.`rol` AS `SisoUsers__rol`, `SisoUsers`.`enabled` AS `SisoUsers__enabled`, `SisoUsers`.`created` AS `SisoUsers__created`, `SisoUsers`.`modified` AS `SisoUsers__modified`, `SisoUsers`.`last_login_date` AS `SisoUsers__last_login_date` FROM `siso_users` `SisoUsers` GROUP BY UNION "_
