### ISSUE TITLE
RFC: Split methods of type `enableFoo()` with boolean argument.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11864]
While updating my plugins for CakePHP 3.6 I felt odd having to do method calls like `$query->enableHydration(false)`.

It would be better to separate methods `enableFoo()` for enabling a flag and `disableFoo()` for disabling a flag.

These are the enabling methods which take boolean argument which would have to be changed:

- `\Cake\ORM\Query::enableHydration(bool $enable = true)`
- `\Cake\Database\Connection::enableSavePoints(bool $enable)` // This odd one doesn't have a default value
- `\Cake\Database\Driver::enableAutoQuoting(bool $enable = true)`
- `\Cake\Database\Query::enableBufferedResults(bool $enable = true)`
- `\Cake\View\ViewBuilder::enableAutoLayout(bool $enable = true)`

**Comment by markstory** [comment]
Deprecating methods we've just added is not ideal as the API churn gets quite high. We could take this as something to change going forwards with new methods. I'm not against introducing disable* methods for the existing enable ones.

**Comment by ADmad** [comment]
> I'm not against introducing disable* methods for the existing enable ones.

Just adding disable* without modifying existing enable* works too. I have a PR for this soon.

**Comment by dereuromark** [comment]
I don't think we have to adjust them, they are maybe not super intuitive, but at least it is only a setter :)
So that's something. For the sake of simpler API we might want to keep the current naming scheme

Refs https://github.com/cakephp/cakephp/pull/11839
He basically just refactored back to the convention we so far had.

**Comment by dereuromark** [comment]
PS: If you want to keep a single setter (which makes sense for a simple bool value IMO), you can also just rename to `setHydrationEnabled(true/false)` etc. But not sure if that is more readable than `enableHydration(true/false)`.

**Comment by chinpei215** [comment]
I don't think just adding disable* works fine, as you seem to prefer interface-based programming. So disable*() should be declared on the interfaces. Then users must implement disable*() witch calls enable*(false) internally. I think it doesn't make sense. If we want to have disable*(), I think it would be better to deprecate enable*(false).

**Comment by ADmad** [comment]
> For the sake of simpler API we might want to keep the current naming scheme.
Keeping current naming scheme would have been a fair consideration if it was consistently followed. For some flags we already have enableFoo()/disableFoo() pair, e.g. `Driver::enableForeignKeySQL()/disableForeignKeySQL()`,  `Controller::enableAutoRender()/disableAutoRender()` which is the better naming scheme IMO.

> So disable*() should be declared on the interfaces. 
So we can add them to respective interfaces in 4.0. Of all the classes are have listed none are likely to have many custom implementations anyway.

> If we want to have disable*(), I think it would be better to deprecate enable*(false).

That was my initial proposal but I am ready to accept a compromise of just adding disable* :)

Totally deprecating `Query::enable()` itself was unnecessary IMO. I should have been retained as a setter and new method should have been added for getter. `$query->hydrate(false)` doesn't sound ironic like `$query->enableHydration(false)` does.

**Comment by dereuromark** [comment]
True. But talking about one simple setter for a bool flag, I would prefer if we moved to a single setter with a good name, instead of having two setters that have no argument. This way it is also easier to use it programatically from data:

    $entity->is_active = true/false;
    ...

    // Not to nice
    if ($entity->is_active) {
        $mySth->enableFoo();
    } else {
        $mySth->disableFoo();
    }

    // Nicer
    $mySth->enableFoo($entity->is_active);

So please lets keep the simple and single setter. The important part is the setter/getter separation which we still didnt even finish yet on quite a few levels.

**Comment by dereuromark** [comment]
Can we close this then as not a good idea for setters to be split?

**Comment by ADmad** [comment]
I still very much dislike `enableFoo()` method taking a boolean param. I am of opinion that we keep them as they are with default `true` argument and add additional `disableFoo()` which doesn't take any argument in 4.x. This way no depredations changes, required in 3.x. The related interfaced can also be updated in 4.x without BC concern. Many are already updated anyway.

**Comment by dereuromark** [comment]
With that addition, we must still never deprecate the argument way, though. And I am a bit afraid this would then actually happen.

**Comment by ADmad** [comment]
We could "soft" deprecated the argument in 4.x and remove in 5.x, so never remove the argument. People who don't mind `enableFoo(false)` usage can keep using it and those like me can use `disableFoo()` :slightly_smiling_face:

**Comment by dereuromark** [comment]
"Remove in 5.x" completely contradicts the 2nd part of the sentence "who don't mind enableFoo(false) usage".
Again: It must never be deprecated or removed. An additional method has little benefit, but sure also not much costs. But removing the argument one is bonkers.

**Comment by dereuromark** [comment]
If you feel strongly about intuitive names, then better to use
```
// setter
$mySth->setIsFoo($entity->is_active); // or similar
// getter
$bool = $mySth->isFoo()
```
as outlined above.

**Comment by ADmad** [comment]
> "Remove in 5.x" completely contradicts the 2nd part of the sentence "who don't mind enableFoo(false) usage".

Yes they are two separate alternatives I proposed.

> But removing the argument one is bonkers.

I proposed just removing the argument of the enableFoo() methods. But I don't mind if it is kept unchanged. Just adding disableFoo() makes me happy.

**Comment by dereuromark** [comment]
As long as you don't remove the very important argument at all, I (and probably most others) am happy too :)

**Comment by inoas** [comment]
`enableFoo(bool $bool)` makes my head spin and should only be kept for BC reasons, IMHO.

However 👍:

> I really don't want to see more inline logic needed for sth trivial like this.
 
So what about these programmatic signatures?
```php
\Cake\ORM\Query::setHydration(bool $enabled) : Query
\Cake\Database\Connection::setSavePoints(bool $enabled) : Connection
\Cake\Database\Driver::setAutoQuoting(bool $enabled) : Driver
\Cake\Database\Query::setBufferedResults(bool $enabled) : Query
\Cake\View\ViewBuilder::setAutoLayout(bool $enabled) : ViewBuilder
```

Same as above setters but hints and at boolean states:
```php
\Cake\ORM\Query::useHydration(bool $enabled) : Query
\Cake\Database\Connection::useSavePoints(bool $enabled) : Connection
\Cake\Database\Driver::useAutoQuoting(bool $enabled) : Driver
\Cake\Database\Query::useBufferedResults(bool $enabled) : Query
\Cake\View\ViewBuilder::useAutoLayout(bool $enabled) : ViewBuilder
```

Toggles the value, returns what value it has been toggled too; you can force the bool state by an argument:
```php
\Cake\ORM\Query::toggleHydration(?bool $enabled) : bool
\Cake\Database\Connection::toggleSavePoints(?bool $enabled) : bool
\Cake\Database\Driver::toggleAutoQuoting(?bool $enabled) : bool
\Cake\Database\Query::toggleBufferedResults(?bool $enabled) : bool
\Cake\View\ViewBuilder::toggleAutoLayout(?bool $enabled) : bool
```

**Comment by dereuromark** [comment]
You are mixing getters and setters again and you kill the chaining, big :-1: here. Keep it single responsibility while good speaking API.

**Comment by ravage84** [comment]
> While updating my plugins for CakePHP 3.6 I felt odd having to do method calls like $query->enableHydration(false).

Totally, :100: %, agree with that. I started to dislike such interfaces over the years.

> Deprecating methods we've just added is not ideal as the API churn gets quite high.

True, but if we added suboptimal method names, we still should fix it asap.

My proposal:

1. (Optionally) Deprecate use of ``enableHydration(true|false)`` with parameter, so only enabling use of ``enableHydration()`` without parameter stays
2. Add ``disableHydration()`` without parameter
3. Add ``setHidrationEnabled(true|false)`` or ``setHidrationActive(true|false)`, for that matter

``enableHydration()`` and ``disableHydration()`` are just convenient and self explaining proxy methods which internally use ``setHidrationEnabled($bool)``.

This way we can keep convenience, keep a readable interface but also can provide a boolean-setter method with a sensible name.

> We could "soft" deprecate the argument in 4.x and remove in 5.x,

I like that proposal.

**Comment by dereuromark** [comment]
Do we really need 3 setter methods for such a simple thing, where a **single** and properly named setter can do the job? `setIsActive(bool $value): void/self` with an also very self-explantory `isActive(): bool` one for example.
We would have 2 * 20 of those additional methods for all those bool setters for what benefit?

**Comment by ravage84** [comment]
Certainly, technically we need one. But I agree with @ADmad the current name is just plain bad for what it does.

I would be fine with a single setter ``setHidrationActive()`` / ``setHidrationEnabled()`` and a single getter ``isHidrationActive()`` / ``isHidrationEnabled()``.

But using the ``is`` part in a setter, such as in ``setIsActive()`` is even worse.

**Comment by markstory** [comment]
I agree with @dereuromark that we need to be careful with the number of methods/aliases we add, as it makes interfaces wider requires more testing and documentation. CakePHP aims to have conventions that make it easier to and aliases have not worked with that goal in the past.

Adding the `disableX()` methods appears to add the fewest number of methods, and if done consistently makes method names easy to remember, operate and doesn't sacrifice any typehinting.

**Comment by ADmad** [comment]
I am perfectly happy with just adding `disableX()` methods, will make a PR soon.
