### ISSUE TITLE
Behavior should support generic Repository implementations

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#11861]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next
* Platform and Target: all.

### What you did

Implement support for behavior in non-table Repositories, like cakephp/elastic-search

### What happened

The constructor of Behavior accept only Table instance:

https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior.php#L153

### What you expected to happen

Maybe we can replace Table typehint to RegistryInterface or other base class definition?

**Comment by dereuromark** [comment]
I am sure this is a plan for 4.0 where such a BC break and generalization is possible.
It sure does make sense to allow for this - and we should more typehint against contracts (interfaces) and less against concrete implementations (classes).

Refs https://github.com/cakephp/cakephp/pull/2854#issuecomment-35332677

**Comment by lorenzo** [comment]
I guess you mean the Behaviors as an idea of firing the callbacks before and after? Most of the current behaviour classes we have in the core make no sense outside of a relational database context.

**Comment by dereuromark** [comment]
@lorenzo Yes, and that makes a lot of sense. Of course the current ones are scoped to the Table usage, but the contracting of classes itself as per SOLID should not restrict here other usage of the repository pattern and behavioral usage.

**Comment by CauanCabral** [comment]
Sure @lorenzo.

But there are also Behaviors like Timestamp or Upload where don't exists a real requirement for relational database.

**Comment by markstory** [comment]
The classnames don't currently work well for non-ORM datasources. Perhaps we need a `Cake\Datasource\Behavior` or at least an interface for that role that non-ORM plugins could use? The existing ORM\Behavior could be retrofitted to implement/support this new behavior interface.

**Comment by dereuromark** [comment]
ORM/Behavior implements Datasource/BehaviorInterface sounds good.
Also from the dependency level.
And this is indeed BC if you adjust the constraint properly on release.

**Comment by qqqqb** [comment]
Hello All,

I was able to [Add Behaviors Suppert](https://github.com/cakephp/elastic-search/commit/6e1e9ecfafdc3f62659726fa798520e62c4186ac) for non-ORM datasources such as TimeStamp Behavior.
It working fine, but the problem was duplicating codes.

**Comment by dereuromark** [comment]
We could get this started soon, if someone wants to take a stab at it.

**Comment by dereuromark** [comment]
Seems like the train left for this one for 4.x milestone.

**Comment by CauanCabral** [comment]
As now `Table implements RepositoryInterface`, changing behavior constructor _typehint_ to expect that interface is BC?

**Comment by dereuromark** [comment]
Maybe in 4.1 (but strictly not BC), otherwise in 5.0.

**Comment by othercorey** [comment]
Should we add this to the 5.0 roadmap and close?

**Comment by othercorey** [comment]
Added to 5.0 roadmap.

**Comment by dereuromark** [comment]
This probably also related to https://github.com/cakephp/cakephp/pull/14499
