### ISSUE TITLE
invalid Exception

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11876]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5x , 3.6.x

```php
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index'],
                      ['_name'=>'index']);
   $routes->connect('/home', ['controller' => 'Pages', 'action' => 'home'],
                      ['_name'=>'home','routeClass' => 'NotExistingRoute']);
```
and try to 'http://sitename/` 
you now receive 
```
 Duplicate Named Route 

Error: A route named "index" has already been connected to "/". 
```
Template | Defaults | Options
-- | -- | --
/ | [ 	'controller' => 'Pages', 	'action' => 'index', 	'plugin' => null ] | [ 	'_name' => 'index', 	'_ext' => [], 	'routeClass' => 'Cake\Routing\Route\DashedRoute' ]

//
`NotExistingRoute` does not exist

**Comment by markstory** [comment]
Pull request open now.
