### ISSUE TITLE
No support for  DboSource::expression in Virtual fields

### ISSUE THREAD

**Issue by giboow** [cakephp/cakephp#11870]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10
* Platform and Target: PHP7 / Mysql 

### What you did
I can't use DboSource::expression in Virtual fields

### What happened
No support for this

### What you expected to happen
in \DboSource::_constructVirtualFields
add condition for process expressions

**Comment by markstory** [comment]
Do you have any interest in fixing this issue? If not it is unlikely to get fixed.

**Comment by markstory** [comment]
Closing as #11871 is open now.
