### ISSUE TITLE
Wrong output by timeAgoInWords on entity date

### ISSUE THREAD

**Issue by narendravaghela** [cakephp/cakephp#11882]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13.
* Platform and Target: WAMP.

### What you did
I am displaying a date using `timeAgoInWords` function.
```
$entity->created->timeAgoInWords([
    'accuracy' => ['week' => 'week'],
    'format' => 'd/m/Y',
    'end' => '+1 week'
]);
```
In database, the `created` field has value - 2018-02-16 10:19:31

Timezone is set to UTC only.

### What happened
It is displaying the output as - `on 16/19/2018`

### What you expected to happen
It should display `on 16/02/2018`

**Comment by saeideng** [comment]
expected result
`m` returns `minute`
but 'M'  => `month`
```php
    $time=new Time('2018-02-16 10:19:31');
    debug($time->timeAgoInWords([
    'accuracy' => ['week' => 'week'],
    'format' => 'd/M/Y',
    'end' => '+1 week'
    ]));
```
see http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details

**Comment by narendravaghela** [comment]
Thanks 👍
