### ISSUE TITLE
Change default value of `$default` arg. of ServerRequest::getParam()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11893]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

`$default` argument of `ServerRequest::getParam()` has default value of `false` which is quite unintuitive and inconsistent with other framework methods which have `null` instead. I guess it is so because of backwards compatibility with old `Server::param()`.

I propose changing the method signature from `ServerRequest::getParam($name, $default = false)` to `ServerRequest::getParam($name, $default = null)` in 4.0.

**Comment by markstory** [comment]
Seems reasonable to me, and the false was to make the new method compatible with param().
