### ISSUE TITLE
getRequest() in View.php ?

### ISSUE THREAD

**Issue by jtraulle** [cakephp/cakephp#11898]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.0-RC1

Now that ``Controller.php`` has a ``getRequest()`` method, that ``$request`` property will become protected for 4.0.0 and that accessing property ``$request`` directly in being deprecated as of 3.6.0, should not there be a ``getRequest()`` method in ``View.php`` to be consistent between Controller and View ?

**Comment by markstory** [comment]
I could see the utility of having the method for consistency. I don't know how much use it would get as view templates execute within the view and will have access to protected properties.

**Comment by jtraulle** [comment]
Thanks for you reply @markstory :slightly_smiling_face: 
For me, it it really a matter of consistency between Controller / View :wink:

**Comment by dereuromark** [comment]
One thing to consider could be usage in helpers.

**Comment by ADmad** [comment]
> One thing to consider could be usage in helpers.

There's already Helper::$request property, so they don't need to get request through View reference.

**Comment by dereuromark** [comment]
True. Would it make sense to refactor to view usage? Or shall we just keep the internal request property?

**Comment by markstory** [comment]
Putting the request onto helpers should be ok. With the request becoming more immutable it is safer to pass around. Having a getRequest() method on View could be nice for consistency though.

**Comment by Asgraf** [comment]
Please don't forget about View Cells since they have controller-like role

**Comment by ADmad** [comment]
@Asgraf Cell's request, response properties should also be deprecated. Don't see any reason why those properties would be required to be accessed from outside, hence no need to provider getters for it.

**Comment by saeideng** [comment]
access to request object in Cells is useful :+1:

**Comment by ADmad** [comment]
@saeideng Cells already have access to request and response objects :) The question is whether cell's request/response need getters methods so that they are accessible from outside, IMO the answer is No".

**Comment by BassemN** [comment]
I think this should be added to 3.6.x milestone

**Comment by xaphalanx** [comment]
@markstory I think this issue can be closed. 3.next has getters and setters for Request and Response.

**Comment by mirko-pagliai** [comment]
I apologize if I open this issue again.

It is not so strange to get the request from inside a cell (and reading this issue, it happens to different users ...).
Example: I want to use a cell to show a drop-down menu with all the my posts categories, to be shown almost everywhere, on all pages (controllers and actions), except on the page where all the categories are already shown (on the `PostsCategoriesController::index()` action, in this example). So I have to know current controller and action and choose what to do. 

Now ... this can be done, since the property is still accessible. But it seems to me correct to add a `getRequest()`method, for compliance with other classes.

**Comment by ADmad** [comment]
@mirko-pagliai Inside the cell you can just use `$this->request`. I don't see a reason why the cell's request instance would need to be accessible from outside and hence there's no need for a public method for it.

**Comment by mirko-pagliai** [comment]
Yes, I know. I said:

> Now ... this can be done, since the property is still accessible. But it seems to me correct to add a `getRequest()`method, for compliance with other classes.

I said it only to make the code uniform and always access the request in the same way. It is obviously not a question of functionality.

**Comment by ADmad** [comment]
Adding unnecessary methods just for the sake of it is quite silly.

**Comment by asgraf** [comment]
I think that the way of getting request object should be consistent everywhere.
So either we should allow use of  `$this->request` everywhere or we should allow use of `$this->getRequest()` everywhere

**Comment by ADmad** [comment]
`$this->request` already does work everything.

**Comment by asgraf** [comment]
Yes, but use of `$this->request` is mark as deprecated in Controllers, Components, Helpers and maybe in few other places i missed.
IMHO framework should be consistent so either undeprecate use of `$this->request` or add `$this->getRequest()` method everywhere for pure consistency sake.

**Comment by asgraf** [comment]
> no use case where it's request property would required to be used from outside,

No one said anything about accessing it from outside.
All i was saying is for consistency sake there should be protected Cell::getRequest() method for purpose of using it from inside cell subclases like this: `$this->getRequest()`

**Comment by mirko-pagliai** [comment]
@ADmad we are all saying, quite simply, that it doesn't look very ok that in some classes we use the `$request` property and in other classes we use the `getRequest()` method, while the `$request` property is obsolete.

That's all. We are not saying that the request cannot be accessed.
For consistency it would be, in my opinion (and others), that the "access mode" is the same and is unique in the whole code.

Really, that's all. If this doesn't seem appropriate or interesting, of course it does nothing!

**Comment by robertpustulka** [comment]
> All i was saying is for consistency sake there should be protected Cell::getRequest() method for purpose of using it from inside cell subclases like this: $this->getRequest()

Do we really need a protected wrapper for a protected property? 
If you want consistency - the general idea is that you use class' properties while in class scope and public getters outside the class scope.

**Comment by asgraf** [comment]
>  you use class' properties while in class scope

And then you get deprecation warning when doing so

**Comment by asgraf** [comment]
In cake 3.6 you have deprecated use of `request` property in controllers, components views and helpers
https://github.com/cakephp/cakephp/blob/3.6.0/src/Controller/Controller.php#L130

In order to get rid of any current of future deprecation errors we had to do some mass replacements in our code.
So we:
- replaced all instances of `$this->request` with `$this->getControllers()->getRequest()` in our components classes
- replaced all instances of `$this->request` with `$this->getView()->getRequest()` in our helpers classes.
- replaced all instances of `$this->request` with  `$this->getRequest()` in all Controllers, all Views and all template (*.ctp) files

The only place where we cannot replace `$this->request` with `$this->getRequest()` are cells classes because cells does not implement such a method.
Thats why people demand existence of such method in cells

**Comment by ADmad** [comment]
> https://github.com/cakephp/cakephp/blob/3.6.0/src/Controller/Controller.php#L130

The message clearly states that's the `..property will be made protected`. One can always use protected properties within a class.

Using the `@deprecated` message was perhaps a mistake as it's not context based. We didn't realize people blindly follow their IDE notifications without paying attention to the message. Later on the `@deprecated` tag was removed as message added within docblock description `https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L128`. Cake itself never throw deprecation notice like it's done for other deprecated features.

Also using `$this->request` within views has never thrown deprecation notice even for IDEs.

> Now we no longer use $this->request anywhere in our code (except cells).
As I have already stated above you **can** use `$this->request` within controller and view.

> All we want is consistency in our code so please add protected getRequest() method into cells so we can safely forgot that $this->request ever existed :)

I already stated above how to achieve that if that's so important for you. Make your own base cell class with `getRequest()`.

As stated by robertpustulka for consistency **use the request while in class scope and public getter outside the class scope.**

To conclude adding a protected method to access a protected property is quite still and it won't be done for cells. So let's stop this discussion.

**Comment by josegonzalez** [comment]
@ADmad While I understand that there isn't any _real_ need for adding the getter/setter in this case, for consistency in how you access throughout a codebase, it would be nice to add them. This would make it such that users wouldn't have to worry about whether to use one access method or another depending upon the current scope - it's always the same code they are writing.

**Comment by ADmad** [comment]
My opinion on the matter is not going to change. Deciding whether to use a protected property or a getter method based on context you are working in is a fairly common thing in programming.

If other core devs think adding a pointless protected method to access a protected property is a reasonable thing to do, to please a particular group of users, then go ahead with the change.
