### ISSUE TITLE
Replaced session engine is not used

### ISSUE THREAD

**Issue by lukeelten** [cakephp/cakephp#11895]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.14
* Platform and Target: Manjaro with Linux 4.15, PHP 7.2.3, PHP internal webserver, MariaDB 10.2

### What you did
I use a middleware to replace the session engine with a custom engine to pass in configuration variables which are not available during bootstrap.
`$request->getSession()->engine($engine);`

### What happened
After exchanging the engine object, it remains inside the session object through the whole life cycle, but isn't used at all. Debugging shows, that none of its methods is invoked.

### What you expected to happen
I expect that the new engine object is used to read the session data before invoking the controller action, and is used to save the session when rendering is finished. 

During debugging, I found out, that the constructor of "\Cake\Network\Session" calls "session_set_save_handler" with the engine object created at construction.
But when replacing the engine, the PHP function is not called to provide the new engine object.
Calling "session_set_save_handler" after passing the new engine to the session object produced the expected behavior.

**Comment by markstory** [comment]
> Calling "session_set_save_handler" after passing the new engine to the session object produced the expected behavior.

Is there a reason you are not calling session_set_save_handler?

**Comment by lukeelten** [comment]
Cake registers the first session engine on its own during creation so I expect cake, when a new session engine is passed, that it registers the new engine properly. 
Otherwise there is no point in providing the functionality to replace the session engine.

If the responsibility of calling "session_set_save_handler" remains at the user, it should at least be documented, that passing in a new session engine has no runtime effect.

**Comment by markstory** [comment]
Having cake call session_set_save_handler makes sense to me.

**Comment by markstory** [comment]
Pull request open now.

**Comment by lukeelten** [comment]
There is an issue with the bugfix:
When the new session engine is passed in as an object, it will not be registered properly.
` return $this->_engine = $class;` in line 256 in src/Http/Session.php will stop the method before the new engine object will be registered in line 277.

**Comment by markstory** [comment]
Looks like I screwed up the merge conflict. I will get that fixed.

**Comment by markstory** [comment]
More complete fix up now.
