### ISSUE TITLE
notEmpty validation rule not working

### ISSUE THREAD

**Issue by yosus** [cakephp/cakephp#11905]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3-5-12

Based on the Cakephp3 tutorial. When using the ArticlesTable.php, when I make 'title = null', the  notEmpty validator does not work and the data (with 'title = null') is saved to the database.

```
// In ArticlesController.php
public function add()    {
        $article = $this->Articles->newEntity();
        if ($this->request->is('post')) {

            $article = $this->Articles->patchEntity($article, $this->request->getData());

	unset( $article->title );
			
            // Hardcoding the user_id is temporary, and will be removed later
            // when we build authentication out.
            $article->user_id = 1;


            if ($this->Articles->save($article)) {
                $this->Flash->success(__('Your article has been saved.'));
                 return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Unable to add your article.'));
        }
        $this->set('article', $article);
    }
```

```
// In ArticlesTable.php
public function validationDefault(Validator $validator)	{
		$validator

			->notEmpty('title' , 'Title empty' )


		return $validator;
	}
```

**Comment by jeremyharris** [comment]
Validation only occurs when converting request data into an entity (via newEntity or patchEntity). Once it's an Entity, it's assumed that it's ready to persist. Manually removing the title from the entity object will not revalidate.

If you unset the title from the request data (or submit without a title) and try to patch it in, you will get the validation error.

**Comment by yosus** [comment]
Thanks. I should be using patchEntity to re-validate data after an Entity is created. I was expecting a Cakephp2 method where validation is done when saving.

**Comment by yosus** [comment]
It seems that the notEmpty validation will not be able to catch a field which is missing. It will only check if the field 'isset' in the array.  It will require the 'requirePresence' check to ensure the field is present. An extra check compared to Cakephp2.
