### ISSUE TITLE
Localization based on multiple gettext files

### ISSUE THREAD

**Issue by nicolabeghin** [cakephp/cakephp#11914]
This is a:
* [x] feature-discussion (RFC)

* CakePHP Version: all
* Platform and Target: all

### What you did
I placed different `*.po` files in `Locale/en_US/` like 

* `default.po`
* `appfeature1.po`
* `appfeature2.po`
* `appfeature3.po`

### What happened
CakePHP used `default.po` only as source for translations when using `__('key')`.

### What you expected to happen
Due to the way modern web apps are versioned and splitted in modules, I think it would be very useful to have a way to split app translations in differents `.po` files. I already know [you can use translations domains](https://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html) by explicitly passing the domain

`__d('appfeature1', 'The field {0} cannot be left empty', 'Name');`

but I'm proposing something different, since the merge of all the translations in the different `.po` files would be taken up by the default `__('key')` method. This would allow modularization of translations for different modules of the app, without having to maintain a single huge `default.po` file. Also, I see a similar behavior could be accomplished with Plugin, but it should be an alternative since moving to plugins-based architecture would require huge refactoring for most apps.

**Comment by nicolabeghin** [comment]
hi @lorenzo I'm managing them manually

**Comment by lorenzo** [comment]
@nicolabeghin just as a friendly tip, use poedit (https://poedit.net) I think you may have a different view of the issue you opened after using it.

**Comment by dereuromark** [comment]
You can already do that using/writing your own (plugin shipped) MessagesLoader class that would combine them (see https://github.com/FriendsOfCake/awesome-cakephp#i18n ).

But I would even consider using a high level plugin (e.g. https://github.com/dereuromark/cakephp-translate) that would contain your specific "modularization" strategy and how to translate and store the result.

Either way, this is completely out of scope of the core framework defaults IMO.

**Comment by nicolabeghin** [comment]
thanks @lorenzo, I used Poedit in the past but I don't see how it could help in the way (I imagine it can combine gettext files, but I'm talking on a framework-level, otherwise I could just script a bash tool for the tool)

thanks @dereuromark it's a RFC, I though it would be a pretty good addition to the framework and its modularization, as many other standard convention-over-configuration CakePHP features :-)

**Comment by dereuromark** [comment]
@nicolabeghin There are many useful features, but they do not necessarily belong into the "essential" core.
Again: As long as they can be easily done as plugin solution, that is perfectly fine to be kept this way.
"Core feature" actually means that the majority is requesting and using this (let's say 80%), otherwise it should rather be an opt-in feature via plugin-extension.
See what happens to Acl, Auth, and many other very useful things that can be handled more flexible this way and don't lie dead in core code for many people. Basic package principles.

**Comment by nicolabeghin** [comment]
@dereuromark thanks for the clarification.

**Comment by dereuromark** [comment]
See also https://www.dereuromark.de/2016/01/29/developing-cakephp-3-plugins-its-fun/#plugin-vs.-core-feature
The core tries to adapt more and more well defined extension points for the ecosystem to "plug in".

**Comment by ADmad** [comment]
I also think this feature can be handled in app/plugin and doesn't need to be in core.

**Comment by ADmad** [comment]
Closing for reasons stated in above comments.
