### ISSUE TITLE
[2.x] Update Security documentation with Security.useOpenSsl

### ISSUE THREAD

**Issue by WrDX** [cakephp/cakephp#11917]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.9
* PHP Version: 7.2

I was trying to get ```Security::encrypt()``` to work on CakePHP 2.10.9 and PHP 7.2. The current documentation states that it relies on the deprecated ```mcrypt``` extension:
https://book.cakephp.org/2.0/en/core-utility-libraries/security.html

But the release notes of 2.10.8 state that setting ```Security.useOpenSsl``` will make ```Security::encrypt()``` use OpenSSL:
https://bakery.cakephp.org/2018/02/24/cakephp_2108_released.html

It took me a while to figure this out, an update to the documentation would be much appreciated.

**Comment by markstory** [comment]
Any chance you would be willing to update the documentation? It can be found in the master branch of cakephp/docs.

**Comment by WrDX** [comment]
I've added a pull request: https://github.com/cakephp/docs/pull/5710
