### ISSUE TITLE
Problem with 'action' property on Create form 

### ISSUE THREAD

**Issue by vanhelmont** [cakephp/cakephp#11911]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: MAMP

### What you did
I doing a form to send data to another action in the same controller. I coded it:
`<?= $this->Form->create($roll, ['url' => ['action' => 'index']]); ?>`
And printed this:
`<form method="post" accept-charset="utf-8" action="/dices">`

### What happened
When I submit the data, it just refresh de page, no codes process in controller.

### What you expected to happen
Just send the data, without doing any bypass codes to do it.
I try to force action to "/dices/", and its ok!

**Comment by markstory** [comment]
What URL were you hoping to see generated for that URL array?

**Comment by vanhelmont** [comment]
"/dices" appear to be a good and friendly URL, but It just don't receiving the date from form posting.

**Comment by markstory** [comment]
If you look at the form submission in the network panel of your browser's developer tools do you see a request with the correct parameters?

**Comment by vanhelmont** [comment]
**General**
`Request URL: http://localhost:8888/dices
Request Method: POST
Status Code: 301 Moved Permanently
Remote Address: [::1]:8888
Referrer Policy: no-referrer-when-downgrade`

**Response Header**
`Connection: Keep-Alive
Content-Length: 236
Content-Type: text/html; charset=iso-8859-1
Date: Sun, 08 Apr 2018 19:04:55 GMT
Keep-Alive: timeout=5, max=100
Location: http://localhost:8888/dados/
Server: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0`

**Request Header**
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 84
Content-Type: application/x-www-form-urlencoded
Cookie: _ga=GA1.1.1627038930.1523128941; _gid=GA1.1.1239273833.1523128941
Host: localhost:8888
Origin: http://localhost:8888
Referer: http://localhost:8888/dices/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

**Form Data**
`_method: POST
name: name
tag: something`

**Comment by ADmad** [comment]
`Status Code: 301 Moved Permanently`  You have a redirect for `/dices` URL, that's why your POST data is lost. You most likely have URL rewriting setup to append `/` to any URL without it and redirect which is what's causing the problem. CakePHP will always generate URLs without trailing slashes.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
