### ISSUE TITLE
MultiCheckboxWidget.php error when using variable names with an underscore

### ISSUE THREAD

**Issue by RichardPilbery** [cakephp/cakephp#11913]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.14
* Platform and Target: PHP 7.1.0, MySQL 5.6.34

### What you did
Created a variable to populate a select Form input (checkbox variant). The variable name ($ksf_dimensions) has an underscore in it. Inserted the following code in the view:

`<?= $this->Form->input('ksf_dimensions',['type'=>'select','multiple'=>'checkbox','label'=>FALSE]); ?>`

### What happened
Received the following error instead of a populated select input:

`Invalid argument supplied for foreach() [CORE/src/View/Widget/MultiCheckboxWidget.php, line 134]`

### What you expected to happen
Correct form input generated. 

Note: If the variable is renamed without the underscore, behaviour is as expected.

**Comment by ADmad** [comment]
Are you setting another view variable names `$ksfDimensions`? By convention if you have not specified value for `'options'` key in options argument of input() then variable name with camelBacked version of field named as used for options.

**Comment by RichardPilbery** [comment]
I'm not. So, I should have set the variable name to $ksfDimensions and then in the view:

`<?= $this->Form->input('ksfDimensions',['type'=>'select','multiple'=>'checkbox','label'=>FALSE]); ?>`

Is that correct?

**Comment by ADmad** [comment]
No, the field name should stay underscored, just the view variable to populate the options should be camelBacked.

**Comment by RichardPilbery** [comment]
Gotcha. Thanks for your help.
