### ISSUE TITLE
Use custom finder with joins without relations

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11915]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: WAMP

### What you did
I prepare custom finder using by Auth, like this:
```
    public function findEmployer(Query $query, $options)
    {
        $query->where([
            'Users.someConditions' => 10,
        ])->innerJoin(['Companies' => 'companies'], function ($expr) {
            pr($expr);
        });

        return $query;
    }
```
`Users` hasn't relations with `Companies` and it should stay like this.

### What happened
The variable `$expr` describe `Users` table.

### What you expected to happen
The variable `$expr` should by describe `Companies` table.

Additional:
Maybe is other solutions to `getPrimaryKey()` inside `innerJoin` of `Companies` table?

**Comment by lorenzo** [comment]
I'm not really following the problem. How are you getting the primary key?

**Comment by kicaj** [comment]
Now I use
```
    public function findEmployer(Query $query, $options)
    {
        $query->where([
            'Users.someConditions' => 10,
        ])->innerJoin(['Companies' => 'companies'], [
            'Companies.id' => '...',,
            'Companies.otherConditions' => '...',
        ]);

        return $query;
    }
```
String `Companies.id` would like replace with `getPrimaryKey` of `Companies` table

**Comment by markstory** [comment]
This doesn't sound like a bug then. The current code does what is documented, you want it to do something else though. How would you recommend we reconcile what the code does with what you want it to do?
