### ISSUE TITLE
Overriding plugin templates, plugin installed via composer

### ISSUE THREAD

**Issue by ivanamat** [cakephp/cakephp#11910]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: Win, OSX, Linux

### What happened
In the [documentation](https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application), where explain how to override plugin template, explain two options, plugins inside plugins folder, and plugins installed via composer. When i try override a plugin template installed vía composer, as described in the manual, it does not work. To override a plugin templates installed via composer, need to do as a plugin inside plugins folder.

```
src/Template/Plugin/ContactManager/Contacts/index.ctp
```
Creating this file would allow you to override **plugins/ContactManager/src/Template/Contacts/index.ctp**.

If your plugin is in a composer dependency (i.e. ‘TheVendor/ThePlugin’), the path to the ‘index’ view of the Custom controller will be:
```
src/Template/Plugin/TheVendor/ThePlugin/Custom/index.ctp
```

### What you expected to happen
As @markstory comment in this [issue](https://github.com/cakephp/docs/issues/5338#issuecomment-379128080):

> The documentation should be how the code is working

**Comment by markstory** [comment]
I got around to looking at this today, and was able to override a vendored plugin view without issues. My scenario was as follows:

1. I created a plugin with `bake plugin Company/Contacts`, and added a controller with only an empty method:

```php
<?php
namespace Company\Contacts\Controller;

use Company\Contacts\Controller\AppController;

class AddressesController extends AppController
{
    public function index()
    {
    }
}
```
2. Add a route to `routes.php`: 
```php
    $routes->get('/addresses', ['plugin' => 'Company/Contacts', 'controller' => 'Addresses', 'action' => 'index']);
```
3. Create plugin template path - `plugins/Company/Contacts/src/Template/Addresses/index.ctp`, which is displayed by going to `/addresses`.
4. App override template - `src/Template/Plugin/Company/Contacts/Addresses/index.ctp`, which is displayed by going to `/addresses`

The names used in the documentation aren't very clear. I'll improve them.

**Comment by markstory** [comment]
Closing as I wasn't able to reproduce.

**Comment by ivanamat** [comment]
Hi @markstory 

The problem is not in the plugins created with "bake", it is in the plugins installed via composer.

1. Install http://github.com/ivanamat/cakephp3-aclmanager 
2. Configure the plugin 
3. The plugin routes in **vendor/ivanamat/cakephp3-aclmanager/config/routes.php** are:
```
    Router::connect('AclManager', ['plugin' => 'AclManager', 'controller' => 'Acl', 'action' => 'index'] );
    Router::connect('AclManager/:action/*',['plugin' => 'AclManager', 'controller' => 'Acl']);

```
4. Create plugin template path as described in the docs 

> If your plugin is in a composer dependency (i.e. ‘TheVendor/ThePlugin’), the path to the ‘index’ view of the Custom controller will be: src/Template/Plugin/**TheVendor**/ThePlugin/Custom/index.ctp

**It does not work**  
```
src/Template/Plugin/ivanamat/AclManager/Acl/index.ctp
```
**It does not work**  
```
src/Template/Plugin/ivanamat/AclManager/index.ctp
```
**it works!**
```
src/Template/Plugin/AclManager/Acl/index.ctp
```
I think that is not what is detailed in the documentation.

Maybe there is something wrong in this plugin? If there is, what is it?

Regards!

**Comment by ivanamat** [comment]
Hi @markstory 

In relation with improving https://github.com/cakephp/docs/commit/3ee74aabbf98bb430e1927624e6ca4ca652faa3c

Company is VendorName? in my case, ivanamat?

**Comment by ADmad** [comment]
You haven't used a vendor name in your namespace https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/composer.json#L24  Hence `src/Template/Plugin/AclManager/Acl/index.ctp` is the expected path for you.

**Comment by ivanamat** [comment]
Hi @ADmad 

Then, It should be?

```
"autoload": {
        "psr-4": {
            "ivanamat\\AclManager\\": "src"
        }
    }
```

Thnx!

**Comment by ADmad** [comment]
It doesn't have to be. Using vendor name at top level in your namespace is optional. For example core plugins like DebugKit, Bake don't use it. If you do use vendor name then it should be camel cased so `Ivanamat\AclManager` not `ivanamat\AclManager`.
