### ISSUE TITLE
Please add license in GitHub settings

### ISSUE THREAD

**Issue by fedir** [cakephp/cakephp#11928]
Please add license in GitHub settings of the repository.

Currently, GitHub could not identify Your project licence, and it's not shown in interface, and not available via API also.

Ref : https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by ADmad** [comment]
The repo already has a [LICENSE.txt](https://github.com/cakephp/cakephp/blob/master/LICENSE.txt). No idea why GH doesn't pick it up.

**Comment by fedir** [comment]
Yep, exactly. I'm trying to figure out, how to define it in Github's settings.

**Comment by ADmad** [comment]
Having `LICENSE.txt` works fine in all my repos. Eg. https://github.com/ADmad/cakephp-glide

**Comment by ADmad** [comment]
IIRC this issue has been reported before too. Need to have GH support look into it I guess.

**Comment by fedir** [comment]
Hi !

I just get the answer from GitHub support team. Basically, GitHub uses automatic license detector : https://github.com/benbalter/licensee

I just installed it locally and get following results :

```
bundle exec bin/licensee detect https://github.com/cakephp/cakephp --remote --license mit
License:        
Matched files:  LICENSE
LICENSE:
  Content hash:  71ed6d0f839345d00a033711a4657b99312869e9
  License:       
  Closest licenses:
    MIT similarity:      92.39%
    NCSA similarity:     78.18%
    BSL-1.0 similarity:  65.44%
Comparing to MIT License:
Input Length:      1169
License length:    1019
Similarity:      92.39%
diff --git a/LICENSE b/LICENSE
index ce3f035..0573856 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,5 +1,7 @@
{+cakephp tm : the rapid development php framework https://cakephp.org copyright c+}
{+2005-2018, cake software foundation, inc. https://cakefoundation.org+} permission
is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files the "software" , to deal in the
software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
software, and to permit persons to whom the software is furnished to do so,
```

All of the sections surrounded by {+ and +} are additions that that tool detected. GitHub has 98% confidence requirement, so with those changes GitHub not meeting that threshold to detect this license.

If the project removes those additions, then the license will be detected properly.

Of course, it's author's and community choice, which version of license the project should use.

**Comment by josegonzalez** [comment]
Seems like their license detector doesn't properly handle copyright headers past a certain length.

@phpnut Do we care enough to include that copyright header? I'm assuming we can include a `COPYRIGHT` file separately that includes such a notice.

> Aside: it's kind of silly for us to be making changes to appease a specific hosting company tool, but in the end, it isn't really worth arguing for or against, so we should make a change (or not) and just close this issue.

**Comment by fedir** [comment]
Example, for React "Copyright" is mentioned directly in the license file : https://github.com/facebook/react/blob/master/LICENSE

```
bundle exec bin/licensee detect https://github.com/facebook/react/blob/master/LICENSE --remote --license mit
License:        MIT
Matched files:  LICENSE, README.md
LICENSE:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2013-present, Facebook, Inc.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
README.md:
  Content hash:  d8d60e4102e27a25c0554c94aa88074af60f46fe
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT
  Closest licenses:
    WTFPL similarity:  9.52%
    MS-PL similarity:  3.87%
    MS-RL similarity:  3.47%
Comparing to MIT License:
Input Length:       1019
License length:     1019
Similarity:      100.00%
Exact match!
```
I think, this line breaks the parsing : `CakePHP(tm) : The Rapid Development PHP Framework (https://cakephp.org)`

**Comment by inoas** [comment]
I think it is due to the MIT license text not matching those github detects.
