### ISSUE TITLE
dateTime pt_BR locale validation

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#11920]
* [x] bug
* [x] enhancement

* CakePHP Version: 3.5.13.

On model table, in validationDefault for dateTime validation, I can't set correct dateFormat that allows use a date with hours, minutes and seconds for my format "d/m/Y H:i". How can I resove this.

**Comment by saeideng** [comment]
you can use `Validation::datetime()`

https://api.cakephp.org/3.5/class-Cake.Validation.Validation.html#_datetime

-----

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
