### ISSUE TITLE
postLink prompt should be templateable

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#11924]
This is an enhancement proposal.
postLink's confirmation script should be templateable
This would make integration with JavaScript window.prompt replacement libraries like [Bootbox](http://bootboxjs.com/examples.html#basic-usage-1) easier
Example use case:
````php
$this->Form->setTemplate([
    'confirmjs'=>"bootbox.confirm({{message}},function(result) { if(result) { {{okCode}}  } else { {{cancelCode}} } });";
]);
````

**Comment by dereuromark** [comment]
This also refs https://github.com/cakephp/cakephp/issues/7511

**Comment by kevinquinnyo** [comment]
This would be a nice feature add.  I think I got around this by something like adding a custom attribute to my postLinks, then intercepting the click and injecting my own alert code (sweet-alert), because I couldn't find a cleaner way.

```
$('.some-post-link-attr').attr('onclick','').unbind('click');
$('.some-post-link-attr').on('click', function (e) {
    e.preventDefault();
    // do custom sweet alert here
});
```

(I am not good at frontend code)

**Comment by markstory** [comment]
Pull request open now.
