### ISSUE TITLE
UrlHelper assetUrl() error filtering data:image/*;base64

### ISSUE THREAD

**Issue by Agacor** [cakephp/cakephp#11922]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.12 #11092

### What you did
`$src="iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==";`
`$this->Html->image('data:image/png;base64, '.$source, array('alt' => 'CakePHP'));`

### What happened
`<img src="/img/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==">`

### What you expected to happen
`<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==">`

**Comment by markstory** [comment]
Pull request open now.
