### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#11934]
Tracking issue for deprecation cleanup in 4.x

* [x] Auth
* [x] Cache
* [x] Collection
* [x] Command
* [x] Console
* [x] Controller
* [x] Core
* [x] Database
* [x] Datasource
* [x] Error
* [x] Event
* [x] Filesystem
* [x] Form
* [x] Http
* [x] I18n
* [x] Log
* [x] Mailer
* [x] Network
* [x] ORM
* [x] Routing
* [x] Shell
* [x] Template
* [x] TestSuite
* [x] Utility
* [x] Validation
* [x] View

**Comment by ADmad** [comment]
@josegonzalez `4.x` branch.

**Comment by markstory** [comment]
> It seems only email transport classes use Socket class. Can they be changed to use Http\Client instead? Or if not move Socket under Mailer?

People could use the socket classes for other socket based transports outside of email though.

**Comment by saeideng** [comment]
>@markstory Network doesn't seem to have any deprecated code anymore. 

https://github.com/cakephp/cakephp/blob/4.x/src/Network/Socket.php#L86-L104

**Comment by ADmad** [comment]
@markstory Okay.

@saeideng Aye, I missed that.

**Comment by jeremyharris** [comment]
I have unticked "Testsuite" as 3.7 deprecates IntegrationTestCase and ConsoleIntegrationTestCase and those will need to be removed. I can get around to doing it when 3.7 releases and is merged into 4.x, but I wanted to make a note of it.

**Comment by markstory** [comment]
Going to close this as 4.x is looking pretty clean. While there are a few new deprecations being added into 3.7, we can clean those up incrementally as they merge into 4.x
