### ISSUE TITLE
FileTest does not work on windows

### ISSUE THREAD

**Issue by DIDoS** [cakephp/cakephp#11938]
https://github.com/cakephp/cakephp/blob/de7ebdb88e11c4283185ba33c827151f02352b4b/tests/TestCase/Filesystem/FileTest.php#L83

First you create a File object without persisting it ($this->File = new File($file, false);) then you expect it to have a filesize and a mime type.
How should this work; is there a magic stub I don't see (that does not work on windows)?

**Comment by saeideng** [comment]
fixed here
https://github.com/cakephp/cakephp/commit/2d168c51a703e84aad8ac043aeb7454c07b2f90b
thank you
