### ISSUE TITLE
Add scalar typehints and return values where possible

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#11935]
Tracking issue for adding scalar typehints and return values where possible in 4.x. Depends on #11934 being completed first.

* [x] Auth
* [x] Cache
* [x] Cache/Engine
* [x] Collection
* [x] Command
* [x] Console
* [x] Controller
* [x] Core
* [x] Database 
* [x] Database/Dialect
* [x] Database/Driver
* [x] Database/Expression
* [x] Database/Schema
* [x] Database/Statement
* [x] Database/Type
* [x] Datasource
* [x] Error
* [x] Event
* [x] Filesystem
* [x] Form
* [x] Http
* [x] Http/Client
* [x] Http/Middleware
* [x] I18n
* [x] Log
* [x] Mailer
* [x] Network
* [x] ORM
* [x] ORM/Association
* [x] ORM/Behavior
* [x] ORM/Rule
* [x] Routing
* [x] Shell
* [x] Template
* [x] TestSuite
* [x] TestSuite/Constraint
* [x] TestSuite/Fixture
* [x] TestSuite/Stub
* [x] Utility
* [x] Validation
* [x] View
* [x] View/Helper

**Comment by dereuromark** [comment]
I also wouldn't do this too early, it will just create a lot of merge conflicts then from 3.x into 4.x.
So better to wait here a while.

**Comment by lorenzo** [comment]
will it create conflicts? The only lines that would change are function signatures, which we don’t actually change in patch versions

**Comment by markstory** [comment]
I'll take Collection and Console.

**Comment by dereuromark** [comment]
Talking about this:
I am strongly in favor of also starting to typehint protected methods. This really helps tons in getting errors early on, both for core and extending classes in userland.
The downsides of performances in higher PHP7 versions can be neglected, especially with the upsides in typesafety.

**Comment by markstory** [comment]
I've been using 

```
perl -pi -w -e 's/\<\?php\n/<?php\ndeclare(strict_types=1);\n/' <path>/*.php
```
to add declare statements if anyone else/future me needs it.

**Comment by ADmad** [comment]
One can use the following to automatically add typehints and then tweak them manually if needed.

```php
vendor/bin/phpcbf --standard=SlevomatCodingStandard --sniffs=SlevomatCodingStandard.TypeHints.TypeHintDeclaration
```

**Comment by ADmad** [comment]
We need to remove the `self` return type hints. It generates an error when you override a method in extended class which returns `$this`.

https://3v4l.org/JMZJ9

**Comment by dereuromark** [comment]
You are doing it wrong. Child uses concrete names as per specs.

**Comment by ADmad** [comment]
Doh, silly me.

**Comment by dereuromark** [comment]
After this one we should try to get phpstan to at least level 3.
This will help to detect a few more issues here in core regarding types.

**Comment by ADmad** [comment]
All packages are checked off, this can be closed now.
