### ISSUE TITLE
Loading associations of _joinData

### ISSUE THREAD

**Issue by itodor** [cakephp/cakephp#11942]
So i have 2 tables with both having association `belongsToMany` to each other. The join table between these 2 has some additional fields and one of them is foreign key to third table. My question is how can i load this association of _jointData between these 2 tables?

Example:

Table `Articles` belongs to many `Tags` and `Tags` belongs to many `Articles`. Join table for both is `ArticlesTags` which has columns: `article_id`, `tag_id` and additional field `image_id` which is connected with `Images` table. When in controller, how can I `conatin()` so that `_joinData` in view contains not just `image_id` but the `Image` object as well?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
