### ISSUE TITLE
App Class Inheritance

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#11951]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

There is one thing I miss a lot about CakePHP version 2.x. Previously not just the controllers, but the tables, helpers and components, if I'm not mistaken, were inheritances of an APP class that inherited from the Framework class (AppTable, AppComponent, AppHelper). This is very useful since it makes super easy to make customizations for all project items of that type. Today it is still possible to do this manually, but every time baker is used, I have to edit the class to correct the inheritance. I think it would be a very useful thing. Do you have any reason not to have it?

**Comment by ADmad** [comment]
There's nothing preventing you from for e.g. adding an `src/Model/AppTable` in your app and having all your table classes extends `AppTable` instead of `Table`.

**Comment by allanmcarvalho** [comment]
Could at least automate baker right? For it to detect if class file "AppTable" exists, inherits from it, not from "Table"... Here is my problem. In a large system with many tables, I have to be doing the "bake model" very often, and then edit all for the right inheritance.

**Comment by dereuromark** [comment]
@allanmcarvalho I dont use the App prefix here tbh, just `Table`. But yeah, this would then be possible to detect IMO, you can make a PR for bake if you want to.
