### ISSUE TITLE
Router scope with setPersist

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#11955]
* enhancement
* CakePHP Version: 3.6

![image](https://user-images.githubusercontent.com/556169/38855752-b44a9cfa-4224-11e8-9217-61ea24ffdbce.png)

`setPersist` needs to be set with every route, I think it would be great if we can set it with scope.

**Comment by markstory** [comment]
Could be done by adding a method to RouteBuilder.
