### ISSUE TITLE
Regression in UrlHelper::build() for empty argument

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#11958]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.0

### What you did
I use `$url = $this->url->build()` to get an URL pointing to the current controller & action (here: MaterialsController, index()).

### What happened
The URL in $url is malformed as it does not include the base URL path.

### What you expected to happen
In previous CakePHP, $url would contain a valid URL. The URL is also valid if the argument is not empty, e.g. `$url = $this->url->build(['controller' => 'materials'])`, or  `$url = $this->url->build('action' => 'index')`, or `$url = $this->url->build('foo', 'bar')`.

**Comment by markstory** [comment]
Usually `/materials` and `/materials/index` are functionally equivalent though.

**Comment by ypnos-web** [comment]
At least in my case I use this functionality in a variety of actions and, most annoyingly, in some elements that are used by templates for several different actions.

**Comment by ypnos-web** [comment]
The problem seems to be more refined than I thought.

The 'index' part is indeed not the problem. The problem is that the base URL path is missing, similar to #11954

**Comment by ypnos-web** [comment]
This patch works for me:
```diff
--- src/Routing/Router.php  2018-04-17 18:53:38.514626771 +0200
+++ patched/Routing/Router.php   2018-04-17 18:58:02.641960414 +0200
@@ -633,7 +633,7 @@
         }

         if (empty($url)) {
-            $output = isset($here) ? $here : $base . '/';
+            $output = $base . (isset($here) ? $here : '/');
             if ($full) {
                 $output = static::fullBaseUrl() . $output;
             }
```

However I tried to track down why such a change would be needed in the git history of Routing/Router.php and Http/ServerRequest.php and couldn't figure it out.

The old `ServerRequest::here()` method would add the base to $here, implying that it is missing in $here. But this method was not used in `Router::url()`. (instead, it seems $here was accessed directly all the time).

**Comment by markstory** [comment]
Ok, the base missing on generated URLs was not clear to me. Is your application running in a subdirectory?

**Comment by ypnos-web** [comment]
Yes this is the problem.

**Comment by markstory** [comment]
Pull request open now.
