### ISSUE TITLE
AuthSecurity error

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#11970]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.0
* Platform and Target: Windows 10 with XAMPP server with PHP 7.0.9 on development mode

Sice 3.6.0 I got this error "URL mismatch in POST data (expected '/rodfmanager2/users/login' but found '/users/login')" when submit a form. My application is not on root from 'www' folder.

**Comment by ADmad** [comment]
Fixed in #11949. The fix will be available in 3.6.1 soon.
