### ISSUE TITLE
Cake\TestSuite\EmailAssertTrait

### ISSUE THREAD

**Issue by MolbioUnige** [cakephp/cakephp#11973]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.0.
* Platform and Target: not relevant

### What you did
I tried to use EmailAssertTrait in an IntegrationTestCase to test emails sent by the tested controller.

### What happened
Obviously, it didn't work as I was expecting. Looking at the Traits code, I could see that it doesn't access the controller's response email object. All trait's assertions are calling the `email()` method which access a protected Email object, which is not the controller's email object.

    /* in trait EmailAssertTrait */

    /**
     * @var \Cake\Mailer\Email
     */
    protected $_email;

    public function email($new = false)
    {
        if ($new || !$this->_email) {
            $this->_email = new Email();
            $this->_email->setProfile(['transport' => 'debug'] + $this->_email->getProfile());
        }
        return $this->_email;
    }
### What you expected to happen
Modifying the `email()` method as here below, I was able to test the email generated by the controller I am testing.

    /* in trait EmailAssertTrait */
    public function email($new = false)
    {
        return $this->_controller->email;
    }

 It is also probable that I was not using `EmailAssertTrait` the way it is intended to use, but if it is the case, an example would be very useful.

**Comment by jeremyharris** [comment]
Since this topic came up, I am working on a plugin and part of it is a new trait that lets you assert against *any* emails sent through a transport. The user just injects the new transport and gets assertions against emails across the board (no extra injection of mocks, etc.):

```
// in tests/bootstrap.php
Email::dropTransport('default');
Email::configTransport('default', [
    'transport' => TestEmailTransport::class
]);
```

If this looks of interest to the core, I can work up a PR and strip it out of my plugin.

(Side note: I have never used the `EmailAssertTrait` because I don't quite understand its usage myself - create an `email()` then inject the `getMockForMailer` into the code? Seems like a lot of work, especially for controllers.)

**Comment by MolbioUnige** [comment]
With the slight modification I did, you don't have to bother with `getMockForMailer`, it just gets the email out of the instanciated controller.

I can then test the email as such

    $this->post('/register', $data);
    
    $this->assertEmailSubject('My fine email subject',  'Set email subject');
    $this->assertEmailTo($data['username'], $data['username'], 'Sending to');
    $this->assertEmailTextMessageContains('/activate/' . $result['activation_code'], 'Activation link');


**Now that I think of it, my modification only works because I've set the Email object as property of the controller. Sorry about that!**


    private function __welcomeMail($user = array()){
        if(Configure::read('debug')){
            $this->email = new Email('debug');
        }
        else{
            $this->email = new Email();
        }
        $this->email
            ->setTemplate('welcome')
            ->setTo($user['username'])
            ->setSubject('Account activation request')
            ->setViewVars(['activation_code' => $user['activation_code']])
            ->setEmailFormat('text')
            ->setHelpers(['Url'])
            ->send();
    }

**Comment by markstory** [comment]
The `EmailAssertTrait` was intended for creating tests for Mailer classes. That use case may be better communicated through a base class like IntegrationTestCase and not a trait, but here we are.

Having a trait that provides assertions that work on any sent email would be great @jeremyharris. I suspect it would be more useful than the current trait we have.
