### ISSUE TITLE
Unexpected behavior for request->getRequestTarget()

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#11977]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1.
* Platform and Target: Apache/2.4.27, MySQL 5.6.37

### What you did
I upgraded my App from 3.5 to 3.6. and my app is located into a sub directory called myapp so the full URL is http://development.local/myapp/

### What happened
I got a warning error says `Accessing 'here' as a property will be removed in 4.0.0. Use request->getRequestTarget() instead. - /www/myapp/src/Template/Layout/front.ctp, Line 45` so I used `getRequestTarget() ` instead of `here`

### What you expected to happen
I expected that `request->getRequestTarget()` will return the same reult from `request->here` but this was not the case. As I told you above that my app is localed at http://development.local/myapp/
in 3.5 & 3.6, `request->here` returns `/myapp/` but on 3.6 `request->getRequestTarget()` returns `/` which is a different result and it should return `/myapp/`

Thanks

**Comment by markstory** [comment]
Have you tried`getPath()`? It was added in 3.6.1 to help with updating the `url` property, and may also fit your needs.

**Comment by BassemN** [comment]
`getPath()` gives the same result for `getRequestTarget()` `/` instaed of `/myapp/`

**Comment by markstory** [comment]
So it does. My mistake.

When used with `Router::url()` is used with `getRequestTarget()` you should get the same value as `here`.

I don't use `here` at all personally. In what scenarios do you find the `here` property useful?  We could add more methods I just worry about adding more methods for less frequently used operations.

**Comment by BassemN** [comment]
I use `here` in my layout to detect if I'm on the homepage or not using the following condition:
```php
if($this->request->here == $this->request->getAttribute('webroot')) {
   // I'm on homepage
}
```
maybe there is a better method but this is how I did it before :)

**Comment by dereuromark** [comment]
Shouldnt you be using

    ->getRequestTarget() === '/'

instead?

**Comment by BassemN** [comment]
@dereuromark Yes, your suggestion will work well but `here` and `getRequestTarget()` are not working in the same manner if your app in a subdirectory so the deprecated warning message is not accurate when asking me to use `getRequestTarget()` instead.

**Comment by markstory** [comment]
@BassemN For that usage, I think you would want `getPath()`. Both `here` and `getRequestTarget()` in that context would run into issues if a query string is present.

I'm reluctant to add a method to completely reproduce `here` as applications should generally not need to be aware that they exist in a sub-directory outside of configuration. Ideally `Router` and other abstractions hide that 'detail'.

**Comment by BassemN** [comment]
Thanks allot :)
