### ISSUE TITLE
Deprecation Warnings on Fresh Bake

### ISSUE THREAD

**Issue by allankenneth** [cakephp/cakephp#11976]
This is a:

* [x] possible bug?

* CakePHP Version: 3.6.0
* Platform and Target: Apache2, MySQL, PHP7.2

### What you did
`composer self-update`
`composer create-project --prefer-dist cakephp/app myappname`
`cd myappname && vim config/app.php`
_edit database connection_
`cd myappname`
`bin/cake bake model all`

### What happened
When running this command, I get:

`Deprecated Error: TableSchema::index() is deprecated. Use TableSchema::getIndex() instead [...]`

every time it tries to create entities.

### What you expected to happen
I wouldn't expect that a fresh bake, starting from scratch, would introduce deprecation errors that need to be fixed.

**Comment by markstory** [comment]
Fixed in cakephp/bake#433
