### ISSUE TITLE
Form validation throws deprecation messages if no rules are set

### ISSUE THREAD

**Issue by highstrike** [cakephp/cakephp#11982]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1

### What you did
I have a modelless form which now contains the new 3.6.x `validationDefault` function (replaced the old protected `_buildValidator` function)
```
public function validationDefault(Validator $validator) {
    return $validator;
}
```

### What happened
![image](https://user-images.githubusercontent.com/2379538/39130888-dbdca758-4716-11e8-9ce1-806cd87869fd.png)

It raised a deprecation message because of this line right here -> https://github.com/cakephp/cakephp/blob/master/src/Form/Form.php#L227

Cake actually calls a deprecated function itself because I didn't explicitly set any validation rules. The form itself is very simple, it doesn't need any validation rules.

Even if I delete the function `validationDefault` from my modelless form it still raises the same deprecation message

### What you expected to happen
not raise any deprecation message 😅 

cc @jeremyharris - https://cakesf.slack.com/archives/C053DPNGT/p1524490620000178

**Comment by ADmad** [comment]
This is a tricky one. The call to deprecated method `validator()` was added in #11857 in an attempt to ensure backward compatibility. Though the usage of overriding `validator()` to add validation is kinda wrong itself. As per the docs the developer was supposed to override `_buildValidator()` to configure the validator.

**Comment by markstory** [comment]
Only emitting the deprecation warning when the subclass implements the `validator()` hook might let us work around this issue.

**Comment by markstory** [comment]
Pull request open now.
