### ISSUE TITLE
Enhancement: Implement "strategies" for TranslateBehavior

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#11997]
Current `TranslateBehavior` uses EAV data model to store the translations. Another better/more convenient approach is using "shadow tables" as implemented in [ad7six/shadow-translate](https://github.com/AD7six/cakephp-shadow-translate). So it would be nice if the core `TranslateBehavior` had support for both data models. 

Implementations for both strategies already exist so it's a matter of modify `TranslateBehavior` to allow user to select preferred strategy. To achieve that we could introduce strategy classes for the translate behavior for handling each approach and one can configure the behavior to use either.

**Comment by lorenzo** [comment]
I like this!

One thing I'd love to do is to abstract the EAV logic in the behaviour to something reusable, sounds like moving the code to a strategy may be able to help us do that.

Would it make sense to have shadow-translate as an official strategy?

**Comment by ADmad** [comment]
> Would it make sense to have shadow-translate as an official strategy?

Absolutely, having it as an official strategy in core itself will give it greater visibility which I am hoping for.

**Comment by rchavik** [comment]
Can we have a way to auto create the shadow tables?
