### ISSUE TITLE
Tree Behavior incorrect quotes

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#12001]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1
* Platform and Target: WAMP

### What you did
I add Tree behavior to my Table, and set field left to `left` instead of 'lft', and `right` instead of `rght`.

### What happened
The syntax of `UPDATE` hasn't quotes.
It's `UPDATE table SET left = ((left + 2)) WHERE (left  >= 0)`

### What you expected to happen
Should be `UPDATE 'table' SET 'left' = (('left' + 2)) WHERE ('left'  >= 0)` because LEFT and RIGHT word are reserved in SQL syntax.

**Comment by kicaj** [comment]
...okey `quoteIdentifiers` :)

**Comment by lorenzo** [comment]
You can also have them in french :D

`UPDATE table SET gauche = ((gauche + 2)) WHERE (droit >= 0)`

It will look tres chic! 💃

Jokes aside... the current naming was so that we could avoid having to quote the columns.
