### ISSUE TITLE
Automatically encode non-ASCII "Content-Disposition" header with RFC5987

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#12015]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1
* Platform and Target: any

### What you did
$this->response->withDownload('пример.txt')

### What happened
In IE9 and IE11 the downloaded file had a different name than was specified.

### What you expected to happen
Downloaded file should have a filename in cyrillic: "пример.txt".

Automatically encode "Content-Disposition" header with [RFC 5987](https://tools.ietf.org/html/rfc5987) / [RFC 8187](https://tools.ietf.org/html/rfc8187)

According to MSDN IE9 supports these RFCs
https://blogs.msdn.microsoft.com/ieinternals/2011/02/11/ie9-rc-minor-changes-list/

**Comment by cholthi** [comment]
Cakephp can not convert strings encoding for developers. It can but it is
really not worth it.

**Comment by dmromanov** [comment]
It would be nice if this feature would be implemented

**Comment by ADmad** [comment]
@dmromanov Can't you encode the string yourself before calling `withDownload()`?

If the issue can be mitigated at app level I would rather not additional code in core to deal with quirks of outdated browsers.

**Comment by garas** [comment]
Encoded header has to be in `Content-Disposition: attachment; filename*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates.txt` but CakePHP sends `Content-Disposition: attachment; filename="£ and € rates.txt"`. Encoding manually wouldn't help.

https://tools.ietf.org/html/rfc5987#section-3.2.2

**Comment by ADmad** [comment]
Okay, then I guess whoever is interested in this can submit a patch to optionally turn on the required encoding.
