### ISSUE TITLE
Creating a custom Locator

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#12014]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1
* Platform and Target: Nginx, PHP 7.2.4

### What you did
```php
class EndpointLocator implements LocatorInterface
{
    public function set($alias, Endpoint $object)
    {

    }

    // Rest of class
}
```

### What happened
An error is generated because the interface stipulates that the `set()` method must take a Table class instance.

https://github.com/cakephp/cakephp/blob/master/src/ORM/Locator/LocatorInterface.php#L62

### What you expected to happen
I was expecting the interface to be more generic to allow for more varying implementations. So I could locate other types of repository class.

**Comment by dereuromark** [comment]
Refs also https://github.com/cakephp/cakephp/issues/11861 etc.

**Comment by davidyell** [comment]
Also seems that the `config()` method is not deprecated in the interface, but is in the `TableLocator` implementation.

**Comment by davidyell** [comment]
It also seems that the interface specifies the `get()` method as being not static. Yet the FactoryLocator class is trying to call it statically.

```php
\Cake\Datasource\FactoryLocator::add('Endpoint', [Muffin\Webservice\Model\EndpointLocator::class, 'get']);

// Deprecated: Non-static method Muffin\Webservice\Model\EndpointLocator::get() should not be called statically in /Users/david/Sites/MuffinWebservice/vendor/cakephp/cakephp/src/Datasource/FactoryLocator.php on line 36
```

**Comment by ADmad** [comment]
Changing the typehint to `RepositoryInterface` would probably cause PHP to complain but I think it's worth doing in 3.6 itself.

**Comment by ADmad** [comment]
Actually given that `LocatorInterface` is under `Cake\ORM` namespace using `Table` typehint makes sense.

If needed we can add a new `Cake\Datasource\LocatorInterface` which non-table data sources can implement.

**Comment by robertpustulka** [comment]
Yes, this interface is intended to work with ORM Tables only.

> It also seems that the interface specifies the get() method as being not static. Yet the FactoryLocator class is trying to call it statically.

@davidyell So why are you trying to call non-static method statically? :)
Locators are intended to be objects. so:

```php
$locator = new \Muffin\Webservice\Model\EndpointLocator;

\Cake\Datasource\FactoryLocator::add(
    'Endpoint', 
    [$locator, 'get']
);
```

**Comment by davidyell** [comment]
@robertpustulka Sounds like a great addition to the documentation.

**Comment by dereuromark** [comment]
Can we close this then now?

**Comment by davidyell** [comment]
Was the new interface added?

**Comment by AidanHaddonWright** [comment]
I've implemented something similar to this but my use case was slightly different. I wanted to create a Registry for payment handlers.

What I've done is copy the TableRegistry and TableLocator classes and created generic base classes. The TableRegistry and TableLocator now extend those base classes.

This enables you to create your own registries by extending the Registry base class and create your own locators by extending the Locator base class or implementing the LocatorInterface.

An example of how this works:

```php
namespace App\Registry;

use Cake\Registry\Registry;
use Cake\Registry\Locator;

class PaymentHandlerRegistry extends Registry
{
    // The locator class to use (used if Registry::setLocator is not called)
    protected static $_defaultLocatorClass = PaymentHandlerLocator::class;

    /* Locations where PaymentHandlers may be found. It corresponds to the directory
     * structure of your app/ plugin.
     * 
     * The below will only look for classes in src/PaymentHandler or
     * plugins/PluginName/src/PaymentHandler, etc
     */
    protected static $_defaultLocations = ['PaymentHandler'];
}

class PaymentHandlerLocator extends Locator
{
    // The suffix of the class. E.g 'Controller', 'Component' or in this case 'PaymentHandler'
    protected $_suffix = 'PaymentHandler'

    // Overriding this method allows you to create custom class-loading logic
    protected function _get($alias, $options)
    {
        // Should return an instance of a PaymentHandler
    }
}
```

Then to use the registry, you would do:

```php
$paypal = PaymentHandlerRegistry::getLocator()->getInstance('Paypal', [
    'customOption' => 'my_value'
]);
// It works with plugins too
$paypal = PaymentHandlerRegistry::getLocator()->getInstance('MyPlugin.Paypal', [
    'customOption' => 'my_value'
]);
```

If this sounds useful, I'll create a pull request for it.

**Comment by markstory** [comment]
@AidanHaddonWright What would be different about the generic registry/locator over extending `Cake\Core\ObjectRegistry`?

**Comment by AidanHaddonWright** [comment]
Ah. I wasn't aware of that class.

I did some digging around in the code and it turns out `Locator` and `ObjectRegistry` are essentially the same. The only difference is that `Locator` has some default class loading behaviour.

Using `Cake\Core\ObjectRegistry` is the answer to this ticket then, surely?

```php
class EndpointRegistry extends \Cake\Core\ObjectRegistry
{
    protected function _resolveClassName($class)
    {
        // Your class-loading logic here
    }
}
```
