### ISSUE TITLE
Collections: appendItem / prependItem not working without key parameter

### ISSUE THREAD

**Issue by chrisch-hh** [cakephp/cakephp#12011]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1

### What you did
I want to use the appendItem method on a collection to add an item to an existing collection. My code:

```
 $collection = new Collection(['a', 'b']);
 $collection = $collection->appendItem('c');
 debug($collection->toArray());
```

### What happened
The result is:

```
[
	(int) 0 => 'c',
	(int) 1 => 'b'
]
```

### What you expected to happen
As far as I understand the documentation on the `appendItem` method, I would expect this:

```
[
	(int) 0 => 'a',
	(int) 1 => 'b',
        (int) 2 => 'c'
]
```

Seems that appending an item to the collection is not working if the (optional) key parameter to `appendItem` is not given. When a key is given, the item gets appended to the collection.

Same for `prependItem`.

**Comment by markstory** [comment]
Odd there are passing tests covering this scenario

https://github.com/cakephp/cakephp/blob/d6f3d00abb0a1fcdc7111ad7a5d10657471062af/tests/TestCase/Collection/CollectionTest.php#L1155-L1165

and 
https://github.com/cakephp/cakephp/blob/d6f3d00abb0a1fcdc7111ad7a5d10657471062af/tests/TestCase/Collection/CollectionTest.php#L1184-L1194

**Comment by saeideng** [comment]
>What is different with your usage?

`toList()` vs `toArray()`

**Comment by saeideng** [comment]
confirm

**Comment by markstory** [comment]
@chrisch-hh The appended items may have duplicate keys which means you'll need to use `toList()` as `toArray()` only emits the last item for each key.
