### ISSUE TITLE
Tree Behavior: Deleting nodes

### ISSUE THREAD

**Issue by chrisch-hh** [cakephp/cakephp#12010]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1

### What you did
I have a table 'Categories' with a tree behavior. This table belongsToMany 'Tags' via join-table 'CategoriesTags'. The `dependend` option is set to true in the association definition. Then I'm deleting a node in the 'Categories' table. 

### What happened
I got a constraint violation in my database and the node and it's children cannot be deleted.

### What you expected to happen
I expect that the entities in the join table of the belongsToMany-association will also get deleted when a node in the tree is deleted so that there will be no trouble with the database constraints. 

It seems that the tree behavior internally uses `deleteAll` to delete the node and all of its children so that delete events won't be triggered and the `dependent` option is silently ignored. 

If it is not possible to implement this in the tree behaviour or it is too complicated, we should update the tree behavior documentation and mention that cascading delete of associated entities is not working here.

**Comment by saeideng** [comment]
`tree` uses `ORM\Query` object  instead of `ORM\Table` 
so Events not exist on it

**Comment by saeideng** [comment]
>It seems that the tree behavior internally uses deleteAll to delete the node and all of its children
