### ISSUE TITLE
4.x / 3.6 $this->getRequest()->getParam() exists but $this->getRequest()->getParams() does not

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12026]
This is a (multiple allowed):

* [x] bug
* [x enhancement

* CakePHP Version: 3.6.2

### What you did
Trying to read request params.

### What happened
Cannot access all request params but only request params by key

### What you expected to happen
getParams() not only getParam()

**Comment by dereuromark** [comment]
getServerParams() is what the PSR dictates as method for this.
We might be able to have an alias here though?

**Comment by inoas** [comment]
Documented in https://github.com/cakephp/docs/pull/5728
