### ISSUE TITLE
4.x move from empty to .keep

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12025]
This is a (multiple allowed):

* [x] enhancement

* CakePHP Version: 4.0

The non hidden empty files bug me for some time and I always recursive replace them with .keep files. These can stay there even if I do add some files into folders as they are usually hidden.

See:
* https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep
* https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep#comment30099040_7229996
* https://github.com/rails/rails/issues/2800

**Comment by inoas** [comment]
cakephp/bake will also be affected.

on Mac OS X you can use this to replace the files

```
brew install rename
find . -name "empty" -exec rename 's|empty|.keep|' {} +
```

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/pull/711
as long as it is not leaking the specific system (e.g. gitkeep etc), I am fine with it. So `.keep` sounds reasonable.
