### ISSUE TITLE
3.6 / 4.x $this->getRequest()->getRequestTarget() and here()

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12027]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.6.2

### What you did
Debugging requests

### What happened
Wanted to access request->here

### What you expected to happen
* Request here doesnt exist in 4.x anymore
* getRequestTarget is long

Would these not work as names / features:

`$this->getRequest()->getTarget()`
`$this->getRequest()->getHere()`

**Comment by ADmad** [comment]
> getRequestTarget is long

That's not a good enough reason to add unnecessary aliases to PSR7 methods.

**Comment by markstory** [comment]
You can still use `$this->request` *inside* a controller, as it will continue to be a property on the controller.

**Comment by ndm2** [comment]
It might be worth noting that the equivalent to `$request->here` actually is

    $request->getAttribute('base') . $request->getRequestTarget()

**Comment by markstory** [comment]
@ndm2 Or `$request->getAttribute('here')`. I'm still not fully caught up on *why* people frequently need the current request URL with the base path present? I personally never use this attribute, as I use the `Router::url()` to build all the URLs my applications generate.

**Comment by ndm2** [comment]
@markstory Is that a new attribute? It returns `null` for me. In my own applications I usually don't need the base, as the document root is set properly, but for plugins that will be used in unknown environments the base might need to be considered.

**Comment by ndm2** [comment]
The `here` attribute doesn't seem to exist, I cannot find any references to it in the source, and fresh installations return `null`, maybe this has been overlooked or removed accidentally?

Using `Router::url()` can surely work, but there are situations where you explicitly want to work with a request object instead, for example when the interface accepts/expects such an object.

**Comment by markstory** [comment]
@ndm What branch are you looking at? The attribute is set in 3.x here https://github.com/cakephp/cakephp/blob/0cb6d514b1764494e0daf9817aa437b273b933da/src/Http/ServerRequest.php#L349

**Comment by markstory** [comment]
Yes you're right. I'll get that fixed.

**Comment by inoas** [comment]
Related: For me `getRequestTarget()` does not even work, it returns nothing, but I considered it to be a problem with my webserver - however it returns nothing on DomainFactory (shared hosting) as well as in puphpet.com's vagrant boxes (setup with Apache)

**Comment by ADmad** [comment]
`Controller::$request` and `Controller::response` will continue to exists as protected properties in 4.x and beyond.

**Comment by inoas** [comment]
Closing as there seems to be no will to add an alias and as I assume `$request->getAttribute('here')` will work in 3.6.3 as committed here https://github.com/cakephp/cakephp/pull/12033
