### ISSUE TITLE
MsSql query with tables having columns name with space cannot be selected

### ISSUE THREAD

**Issue by rudy1976s** [cakephp/cakephp#12038]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.2.
* Platform and Target: Nginx, MsSql 2016  Microsoft Dynamics Navision 2017

### What you did
I have created a model to connect to a MsSql existing table. This table has columns with space in name example : "No_ 2",
Quote identifiers are set to TRUE 

### What happened
The ORM result in error because is not able to recognize fields with space and return the following error : 

Error: SQLSTATE[42S22]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'Items.No 2'.
Error could be seen here : http://sqlserver.acmecms.it/

### What you expected to happen
The query run without problem

**Comment by markstory** [comment]
What does the generated query look like?

**Comment by rudy1976s** [comment]
Hi mark
the query is like the following : SELECT TOP 10 [Items].[No_] AS [Items__No_], [Items.No_ 2] AS [Items__No_ 2] FROM [GLS72_ECOMMERCE$Item] [Items] . You . can check it up a t the following test site: sqlserver.acmecms.it

**Comment by markstory** [comment]
The error you are getting looks like it is coming from the ODBC driver, which means the same query executed with the basic `PDO` class would likely fail in a similar way. Are you able to query this table/field with the basic PDO objects?

**Comment by rudy1976s** [comment]
Hi Mark
you can check a raw conection to PDO here and it works fine

http://sqlserver.acmecms.it

**Comment by dereuromark** [comment]
Why do you need spaces filled field names? Cant you refactor your db? there are many issues and regex on the way that will likely also fail. Also mapping to entity fields and properties is a mess this way.

**Comment by rudy1976s** [comment]
Hi mark , no we cannot refactor because we are connecting to Microsoft Navision and the table we are going to work on  are "core" and cannot be refactored.

**Comment by markstory** [comment]
@rudy1976s What does the code that uses `PDO` directly look like? I'm mostly interested in the SQL query being executed.

**Comment by rudy1976s** [comment]
Hi mark do you mean the raw code used or the one used with cake ? 

The PDO direct is like the following:

`
try
{
    $pdo_object = new PDO("sqlsrv:Server=SERVER,PORT;Database=DATABASE", "USER", "PASSWORD");
    
    $query = 'SELECT TOP 1 * FROM TABLE';

    echo $query;

    foreach ($pdo_object->query($query) as $row) {
        debug($row);
    }

}
catch (\PDOException $e)
{
    echo 'Connection failed: ' . $e->getMessage();
}
`

**Comment by markstory** [comment]
@rudy1976s That query doesn't list out the fields being used. Could you try running the *same* query that CakePHP is trying to run.

**Comment by rudy1976s** [comment]
Hi Mark,
we have make several tests and we have noticed that the problem should be related to the quoteIdentifiers routine which converts space into bad field aliasing. 
We tried to run the query generated by cake on SQL server Studio and got the same error obtained from PDO.
If you check the following query, generated from a find(), without selecting fields, you can see that the second field ( which originally contains a  space  like No_ 2 ) has been converted into  [Items.No_ 2] AS [Items__No_ 2] while it should be [Items].[No_ 2] AS [Items__No_ 2].
We tried the query with changes as described and worked on both Sql Studio and PDO.

You can actualy check the query generated by cake with find() at the following url:

http://sqlserver.acmecms.it/

**Comment by rudy1976s** [comment]
Thank you very much.

Rudy

**Comment by rudy1976s** [comment]
Hello
I found the same errore corrected in the Select when adding multiple conditions on query the query is bad generated and is missing from "=" in the conditions: you can check it here where I perform a query with two conditions:

`SELECT [Products].[No_] AS [Products__No_], [Products].[Item Category Code] AS [Products__Item Category Code], [Products].[Description] AS [Products__Description], [Products].[Base Unit of Measure] AS [Products__Base Unit of Measure] FROM [GLS72_ECOMMERCE$Item] [Products] LEFT JOIN [GLS72_ECOMMERCE$Item Category] [ProductsCategories] ON [ProductsCategories].[Code] = ([Products].[Item Category Code]) LEFT JOIN [GLS72_ECOMMERCE$Manufacturer] [Manufacturers] ON [Manufacturers].[Code] = ([Products].[Manufacturer Code]) LEFT JOIN [GLS72_ECOMMERCE$Brand] [Brands] ON [Brands].[Code] = ([Products].[Brand Code]) WHERE ([Products].[eCommerce] = :c0 AND [Products].[Item] category code :c1) GROUP BY [Products].[No_], [Products].[Item Category Code], [Products].[Description], [Products].[Base Unit of Measure]`

as you see the "AND" is bad formed it should be  " AND [Products].[Item Category Code] = "

the query is shown here :

https://gls72.acmecms.it/catalogo?category=00040

It seems that the correction works on select but not on WHERE and END .

Could you please confirm ?

Thank you


Rudy
