### ISSUE TITLE
DboSource::order() line 3044 uses each() deprecated in PHP 7.2 throws ErrorException

### ISSUE THREAD

**Issue by trenshaw** [cakephp/cakephp#12043]
* Bug
* CakePHP 2.10.9
* Ubuntu Server 18.04 LTS, PHP 7.2, MySQL 5.7.22

I am using my own authentication adapter for Active Directory (PHP's ldap_* functions with set_error_handler() to throw ErrorException for otherwise non-fatal LDAP errors). Domain specific settings and the user's DBO record is being stored in MySQL.

DboSource.php uses each() in DboSource::order() line 3044. The PHP 7.2 deprecated notice for each() is being caught and preventing authentication.

We want to migrate our CakePHP 2.x applications to CakePHP 3.x but we need to be able to stand it up on PHP 7.x before we start migration.

Recommend replacing use of each() with foreach() or a different control structure throughout (wherever each() has been used not just in DboSource.php) for inclusion in CakePHP 2.10.10?

**Comment by trenshaw** [comment]
Happy to! In fact have already started...

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/cakephp/pull/12162 open
