### ISSUE TITLE
RequestHandlerComponent::beforeRedirect() Error

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#12040]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.2
* Platform and Target: Windows 10 XAMPP PHP 7.0.6

I got this error

Deprecated (16384): RequestHandlerComponent::beforeRedirect() is deprecated. This functionality will be removed in 4.0.0. Set the `enableBeforeRedirect` option to `false` to disable this warning. - C:\Users\allan\Desenvolvimento\GitHub\rodfmanager2\vendor\cakephp\cakephp\src\Event\EventManager.php, line: 353
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE\src\Core\functions.php, line 307]

**Comment by ADmad** [comment]
Error message tells you exactly what to do to avoid it.

**Comment by allanmcarvalho** [comment]
But this code is deprecated on Cake Core... Not on my application? So because of a Core deprecated code, should I disable the warnings? I do not know how that sounds right.

**Comment by ADmad** [comment]
https://github.com/cakephp/app/blob/69a00b2a40c417bce9bcbd6394c5e6aed57eb629/src/Controller/AppController.php#L44

**Comment by allanmcarvalho** [comment]
Thank you for providing the solution.

**Comment by danielfpedro** [comment]
It does not make sense.
