### ISSUE TITLE
deleteAll cascading deletes not working

### ISSUE THREAD

**Issue by LorenzoRogai** [cakephp/cakephp#12053]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.2

### What you did

UsersTable.php
```
$this->hasMany('Posts', [
 'foreignKey' => 'user_id'
])->setDependent(true);
```

### What happened

Tried to delete 1 user
```
$user = $this->Users->get($id);
$this->Users->delete($user)
```
The Posts rows are deleted too

`$this->Users->deleteAll(['account_id' => $this->Auth->user('account_id'), 'id IN' => $this->request->getData('ids')]);`

The User row has been deleted but the Posts rows are still there

### What you expected to happen
The Posts rows should be deleted too using deleteAll

**Comment by dakota** [comment]
That is the expected behaviour and is documented as such in the book.

> deleteAll will not trigger beforeDelete/afterDelete events. If you need those first load a collection of records and delete them.

https://book.cakephp.org/3.0/en/orm/deleting-data.html#bulk-deletes
