### ISSUE TITLE
Duplicate 'className' check in TableLocator

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#12055]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.2
* Platform and Target: not relevant

### What you did
I'd like to extend table locator (\Cake\ORM\Locator\TableLocator). I'd prefer to override only _getClassName (which I believe exists only for this reason), but checking of 'className' options is duplicate, so you can never know, if user provided 'className'.

### What happened
see above

### What you expected to happen
see above

**Comment by markstory** [comment]
Closing as there is a pull request open now.
