### ISSUE TITLE
Slow performance with many view files

### ISSUE THREAD

**Issue by gemal** [cakephp/cakephp#12054]
we run a large website and view use cakephp view cache

if you have a large view cache fx 30000+ files the performance is really poor when you try to do any database interactions
It's very easy to reproduce. Just add 30.000 files in the view cache and try to test a page which require database save()

I think DirectoryIterator should be used
I use cakephp 2.10.9

**Comment by markstory** [comment]
> I think DirectoryIterator should be used

ok. Are you able to profile the difference that change would make?

**Comment by dereuromark** [comment]
This is out of scope now for maintenance mode and should be handled as plugin or project solution instead.
