### ISSUE TITLE
getOriginal no longer returns original value after persisting entity

### ISSUE THREAD

**Issue by cwbit** [cakephp/cakephp#12069]
This is a (multiple allowed):

* [x] bug (possibly.. it definitely isn't working like it used to)

* CakePHP Version: 3.5.14
* Platform and Target: NGINX, MYSQL

### what's wrong
`Entity::getOriginal` now returns the *current* value if used after the entity is persisted

### What you did
For several years our app used to (CakePHP 3.2.x - 3.4.x?) do the following
```php
$salesOrder = $this->SalesOrders->patchEntity($salesOrder, $this->request->data, [...]);
$savedOrder = $this->SalesOrders->save($salesOrder);
if ($savedOrder) {
  # IF they just changed it to shipped AND it has a tracking number..
  if (!$salesOrder->getOriginal('is_shipped') && $savedOrder->get('is_shipped') && $savedOrder->shipment_no) :
    # .. do stuff
```
where `getOriginal` would return the original value as it existed prior to being changed/patched. 

This came up when we realized none of our shipment confirmation emails were being sent after the upgrade to Cake 3.5.x. It has been working as noted for about 3 years.

### what we expected
`Entity::getOriginal` should return the value that existed prior to it being modified; the "original" value. It *will* return the expected value after being patched and prior to persistence, but persisting the entity breaks the original value.

**Comment by markstory** [comment]
If the entity has been saved/persisted the current state is 'original' If you want the dirty property values you should grab them before persisting. The last recent change I can find around this is #9459

**Comment by saeideng** [comment]
old issue and similar 
https://github.com/cakephp/cakephp/issues/9411
