### ISSUE TITLE
Console Commands not working as cookbook

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#12068]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.12
* Platform and Target: Localhost - Php 7.1.9

### What you did
I've followed the code present in the cookbook:
https://book.cakephp.org/3.0/en/console-and-shells/commands.html

Wanted to run that command and show a print in the console, as said in the example.

### What happened
I get a bunch of warnings in my console, followed by a not founded shell class

```
Deprecated Error: Use Cake\Http\ServerRequest instead of Cake\Network\Request. - C:\app\vendor\composer\ClassLoader.php, line: 444
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [C:\app\vendor\cakephp\cakephp\src\Core\functions.php, line 307]

Deprecated Error: DebugKit\ToolbarService::config() is deprecated. Use setConfig()/getConfig() instead. - C:\app\vendor\cakephp\debug_kit\src\ToolbarService.php, line: 75
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [C:\app\vendor\cakephp\cakephp\src\Core\functions.php, line 307]

Deprecated Error: EventDispatcherTrait::eventManager() is deprecated. Use EventDispatcherTrait::setEventManager()/getEventManager() instead. - C:\app\vendor\cakephp\debug_kit\src\Panel\PanelRegistry.php, line: 35
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [C:\app\vendor\cakephp\cakephp\src\Core\functions.php, line 307]

Deprecated Error: EventManager::attach() is deprecated. Use EventManager::on() instead. - C:\app\config\bootstrap.php, line: 249
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [C:\app\vendor\cakephp\cakephp\src\Core\functions.php, line 307]

Exception: Shell class for "Hello" could not be found. in [C:\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php, line 327]
```

If I disable the warnings as said, It shows the error present in the last sentence:

`Exception: Shell class for "Hello" could not be found.`

### What you expected to happen
Print the hello message.

When I do the bin/cake command, it shows me the "hello" option, under the [app] group.

**Comment by markstory** [comment]
Your application is using some deprecated methods. You can either [disable deprecations](https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#disabling-deprecation-warnings) or update debugkit.

What does your `HelloShell` class look like, and where is it in your application directory?

**Comment by Cafnio** [comment]
Hi

Already disabled the deprecated methods for this test.

It only shows me the error:

`Exception: Shell class for "Hello" could not be found.`

About the implementation, i've created the folder /src/Command/ with the file HelloCommand.php inside of it, with the following code:

```
<?php

namespace App\Command;

use Cake\Console\Arguments;
use Cake\Console\Command;
use Cake\Console\ConsoleIo;

class HelloCommand extends Command
{
    public function initialize()
    {
        parent::initialize();
        $this->Users = $this->loadModel('Users');
    }

    public function execute(Arguments $args, ConsoleIo $io)
    {
        $io->out('Hello world.');
    }
}
```

Do I need to create a Shell file aswell? The cookbook doesn't refer that

**Comment by markstory** [comment]
Does your `bin/cake.php` file look like [this one](https://github.com/cakephp/app/blob/master/bin/cake.php)? If you've upgraded from an earlier version of cakephp you may have to replace your `cake.php` script to enable command classes to be used.

**Comment by Cafnio** [comment]
Yeah, it was different! Changed it and it worked like a charm. Thanks!

Suggestion to update the cakephp documentation to prevent this situation (I believe that I'm not the only one :) )
