### ISSUE TITLE
Inflector Singularizes Caches as Cach

### ISSUE THREAD

**Issue by xaphalanx** [cakephp/cakephp#12073]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.x 

### What you did
Named a table "caches" 
### What happened

Inflector singularized it "cach"

### What you expected to happen
I expected it to return "cache"

I would like to propose opening up the inflector's _irregular array to allow people to put their own  custom rules in so when things like this happen or when someone just wants to pluralize/singularize in a custom way, whatever the reason, they can do so. A method added to Inflector like this:

```php

/**
  * An interface like this would allow users to append to the _irregular array
  * it could be called in the Application or Plugin class.
  */
public static function setInflection($singularForm, $pluralForm);

```

**Comment by jeremyharris** [comment]
I believe you can already do this. From the cakephp/app bootstrap:

```
/*
 * Custom Inflector rules, can be set to correctly pluralize or singularize
 * table, model, controller names or whatever other string is passed to the
 * inflection functions.
 */
//Inflector::rules('plural', ['/^(inflect)or$/i' => '\1ables']);
//Inflector::rules('irregular', ['red' => 'redlings']);
//Inflector::rules('uninflected', ['dontinflectme']);
//Inflector::rules('transliteration', ['/å/' => 'aa']);
```

**Comment by xaphalanx** [comment]
Thank you that will work.
