### ISSUE TITLE
Mixing {@inheritDoc} and @param does not work in phpstan

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#12070]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.2

### What you did

I use Cake\ORM\Query select method passing instance of Cake\ORM\Table. Problem is that phpstan does not allow rewriting @param when using {@inheritDoc}.

I would suggest copying the whole comment text from Cake\Database\Query::select to Cake\ORM\Query::select 

### What happened

Parameter #1 $fields of method Cake\ORM\Query::select() expects array|Cake\Database\ExpressionInterface|callable|string, Cake\ORM\Table given.

### What you expected to happen

no error

**Comment by markstory** [comment]
Any chance you'd be willing to put a pull request up for this?

**Comment by segy** [comment]
Of course. See #12071

**Comment by markstory** [comment]
Awesome, thank you!
