### ISSUE TITLE
Input type button attribute error.

### ISSUE THREAD

**Issue by paulorwd** [cakephp/cakephp#12080]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1.
* Platform and Target: Chrome, Mysql, Windows 10.

### What you did
`$this->Form->input('field-name', ['type' => 'button', 'text' => 'Hello']);`

### What happened
Attribute text is not assumed, it ends up being replaced with the name of the field.

### What you expected to happen
The attribute should be assumed and should only use the field name in not to be filled.

**Comment by paulorwd** [comment]
`<button name="field-name">Hello</button>`

exactly like the template

`<button{{attrs}}>{{text}}</button>`

**Comment by markstory** [comment]
You should be using `button()` directly instead of going through the `input()` wrapper. While `input()` 'works' it will not do what you are expecting.

If you still want to use `input()` you would need to call it like:

```php
$this->Form->button('Hello', ['type' => 'button', 'name' => 'field-name']);
```

**Comment by paulorwd** [comment]
It is because it is within a loop and I am applying the input pattern, but still thank you, I will use this form quoted.
