### ISSUE TITLE
php intl already enabled

### ISSUE THREAD

**Issue by mathritter** [cakephp/cakephp#12083]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.4.7
* Platform and Target: webserver

### What I did
Tried to run the command line "php cake.php"

### What happened
Says intl is not enabled, but the server is running for over seven months.

### What I expected to happen
I created a shell in my local dev machine, following the right steps from cakephp docs. It worked locally, won't work on webserver. Tried phpinfo, it says intl is enabled.

**Comment by dakota** [comment]
On most server configurations the web and cli PHP instances use different `.ini` files. Try running `php -i | grep intl` to see if intl is enabled for cli.

**Comment by mathritter** [comment]
Oh, thanks. I tried running this command, got no results. I think maybe it's not installed. I see it's not the purpose of this thread, but do you have any advice on installing it without major impacts?

**Comment by josegonzalez** [comment]
You should check to see in what path your webserver's php is installed, the php binary is usually related to that path. Without knowing more about your system, I don't think we can figure out any further solution here for you.

I would suggest reaching out to us via [slack](http://cakesf.herokuapp.com/), as we will be able to more effectively support your debugging into where your php is located and how to install required dependencies. It's free and operators are standing by :)

**Comment by mathritter** [comment]
I'm sorry. It was lack of linux knowledge. So here what happened:
As you commented apache has a php aside the apache server itself. So I managed to find the apache's php, which of course already had intl enabled, so I could execute cakephp's shell. Thanks for everything and sorry bothering :D

**Comment by josegonzalez** [comment]
Hurray! Nice to see everything works :) . Hope you enjoy your CakePHP usage :)
