### ISSUE TITLE
Add an interface for transport classes.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12084]
1. `Email` class currently does a `method_exists($transport, 'send')` check for transport instances. It would better if we can an interface for transport classes and check if the interface was implemented instead.

https://github.com/cakephp/cakephp/blob/1cfebf6c6719a2a743d9a3e59ee091a726f18844/src/Mailer/Email.php#L1660

2. Also currently you can set `className` key to an object in transport config, which is a bit weird. I don't think we allow that for any other class name. So the possibility of doing so should be removed IMO. `className` should always be a string.

https://github.com/cakephp/cakephp/blob/1cfebf6c6719a2a743d9a3e59ee091a726f18844/src/Mailer/Email.php#L1635

**Comment by ADmad** [comment]
If we don't want to introduce a new interface better to check if transport object is instance of `AbstractTransport` instead of checking for `send()` method.

**Comment by ADmad** [comment]
Actually going through the `_constructTransport()` code the `method_exists($className, 'send')` isn't required since there's already a `instanceof AbstractTransport` check if `className` is an object and if string the `App::className()` return  will get a transport class which extends `AbstractTransport`.

So the only issue is point #2.

**Comment by markstory** [comment]
> Also currently you can set className key to an object in transport config,

We do this for cache engine and loggers too from what I remember.

**Comment by markstory** [comment]
It was one of the ways we accommodated dependency injection.

**Comment by ADmad** [comment]
Creating of transport instances has now been offloaded to `TranportFactory` and `TranportRegistry` which ensures the transport object is instance of `AbstractTransport`. So a new interface is not necessary.
