### ISSUE TITLE
Crud-Json-Api connecting in 2 database, returning a Core warning

### ISSUE THREAD

**Issue by dayaners** [cakephp/cakephp#12082]
Hello boys, I'm new here.

* CakePHP Version: 
"cakephp/cakephp": "3.5.*",
"cakephp/migrations": "^1.0",
"cakephp/plugin-installer": "^1.0",
"friendsofcake/crud-json-api": "^0.2.5",
"friendsofcake/search": "^4.4",

I am trying to learn how to make an API, and wanted to use a real example from my everyday life.
I need to connect to two databases (main and patients), looking for courses and documentation...
 I used the friendsofcake plugin and i added the excerpt:
```
 public static function defaultConnectionName ()
    {
        return 'patients';
    }
```
in my model Patients and in the controller that uses the main "historical" database I added the view part of Crud:
   
```
 use \ Crud \ Controller \ ControllerTrait;
    public function view ($ id = null) {
        $ this-> Crud-> on ('beforeFind', function (\ Cake \ Event \ Event $ event) {
            $ event-> subject () -> query-> contain (['Patients']);
        });
        return $ this-> Crud-> execute ();
    }

```

> Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main.tb_pacientes' doesn't exist

### What you did
It does not relate to my database patients, considering that I needed a solution, I added the name of the database in the method:
```
    public function initialize (array $ config)
    {
        parent :: initialize ($ config);
        $ this-> setTable ('patients.tb_patients'); ....

```
### What happened
And I'm having an warning return in Core:
```

Notice (8): Array to string conversion [CORE \ src \ Datasource \ EntityTrait.php, line 281]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 617]
Warning (2): Illegal offset type [CORE \ src \ Datasource \ EntityTrait.php, line 622]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 288]
Notice (8): Array to string conversion [CORE \ src \ Datasource \ EntityTrait.php, line 281]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 617]
Warning (2): Illegal offset type [CORE \ src \ Datasource \ EntityTrait.php, line 622]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 288]
Notice (8): Array to string conversion [CORE \ src \ Datasource \ EntityTrait.php, line 281]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 617]
Warning (2): Illegal offset type [CORE \ src \ Datasource \ EntityTrait.php, line 622]
Warning (2): Illegal offset type in isset or empty [CORE \ src \ Datasource \ EntityTrait.php, line 288]
Warning (512): Unable to emit headers. Headers sent in file = F: \ wamp64 \ www \ historico \ vendor \ cakephp \ cakephp \ src \ Error \ Debugger.php line = 850 [CORE \ src \ Http \ ResponseEmitter.php, line 48]
Warning (2): Can not modify header information already sent by (CORE \ src \ Error \ Error \ Debugger.php: 850) [CORE \ src \ Http \ ResponseEmitter.php, line 149]
Warning (2): Can not modify header information already sent by (CORE \ src \ Error \ Error \ Debugger.php: 850) [CORE \ src \ Http \ ResponseEmitter.php, line 181]
Warning (2): Can not modify header information already sent by (CORE \ src \ Error \ Error \ Debugger.php: 850) [CORE \ src \ Http \ ResponseEmitter.php, line 181]

```
### What you expected to happen
I'd like to understand if it's really a issue or if I did some wrong process.
I apologize for the English, I used a translation tool I hope you understand me. 
Thank you in advance.

**Comment by markstory** [comment]
The table name in your error looks like it contains a typo `main.tb_pacientes` have you tried solving that error?

**Comment by dayaners** [comment]
Not a mistake, that was the only way he connected to the correct database: patients,
when im not using that on method
` $ this-> setTable ('patients.tb_patients');`
the return is: 

> Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main.tb_pacientes' doesn't exist
