### ISSUE TITLE
Bad Request in form submit

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#12086]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.3
* Platform and Target: Windows 10 xamp

After update to 3.6.x I get error on forms submit.
Error: "Bad Request Cake\Controller\Exception\AuthSecurityException"

**Comment by markstory** [comment]
How can someone reproduce the problem you're seeing? What components and helpers are you using? What does your form look like?

**Comment by allanmcarvalho** [comment]
My application is default. No additional packages. This mistake sometimes happens, sometimes not. Every time while submitting a form. My forms are completely created using the documentation recommendations. This error started happening after I upgraded from 3.5.x to 3.6.3. I updated composer.json based on an application I already started using op 3.6.x

**Comment by allanmcarvalho** [comment]
"require": {
    "php": ">=5.6",
    "cakephp/cakephp": "3.6.*",
    "cakephp/migrations": "^1.8.0",
    "cakephp/plugin-installer": "^1.0",
    "josegonzalez/dotenv": "3.*",
    "mobiledetect/mobiledetectlib": "2.*"
  },
  "require-dev": {
    "cakephp/bake": "^1.1",
    "cakephp/cakephp-codesniffer": "^3.0",
    "cakephp/debug_kit": "~3.0",
    "dereuromark/cakephp-ide-helper": "^0.10.10",
    "phpunit/phpunit": "^6.5",
    "psy/psysh": "@stable"
  },

**Comment by dereuromark** [comment]
Please user proper code fencing. I fixed up your post.

**Comment by markstory** [comment]
@allanmcarvalho Any idea on what is the difference between the requests that succeed and those that don't? Do you have any javascript that modifies your forms by adding/removing inputs?

**Comment by EdouardTack** [comment]
Hello,
I have the same error. I updated cakephp form 3.5.17 to 3.6.5. I try to login in my backend and i have this error. It's working with cakephp 3.5.17.
I think it's about [SecurityComponent update](https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#behavior-changes).
The line error is in SecurityComponent::_validatePost(), my hash_equals($check, $token) return false.
I don't know how to fix it ?

Thanks

**Comment by markstory** [comment]
@EdouardTack I don't either. I'm not able to reproduce the problem. If you can help provide a way to reproduce the issue I can look into it further.

**Comment by EdouardTack** [comment]
@markstory I found my error.
With my AuthComponent, i use a [custom storage Class (config)](https://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuration-options).
Into this class, i always renew my session id. So, my Token field was different between my Form and my request.

With my test, i saw something different to create $hashParts with session id. One use `session_id()`, the other user `$request->getSession()->id`. It's normal ?
[SecurityComponent](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/SecurityComponent.php#L396)
[SecureFieldToken](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/SecureFieldTokenTrait.php#L59)

Thanks

**Comment by markstory** [comment]
Yes that is expected. `Session::id()` is a thin wrapper around `session_id()`. Is it possible that your session hasn't been started when your form is created?

**Comment by allanmcarvalho** [comment]
I have in my application several tasks that execute AJAX calls frequently, be it "post" or "get". I noticed that I have this problem whenever I submit a form on a page that made an ajax call.

**Comment by markstory** [comment]
@allanmcarvalho Good to know, I still don't have a way to reproduce the issue though. I'm looking for a controller action, or small application I can run locally to figure out what is going on.

**Comment by allanmcarvalho** [comment]
@markstory I discovered the why of the problem. But I do not know why this is happening. Using the "pr ()" function I got the session id when loading the page. After waiting for the system to make an ajax request, I got the session id again. And he was already another (**l9d7bi0pgadto85hs5j5i8ajn4** => **empqkt6te4qpbq0t611lo51226**). This is what is causing the "Bad Request" exception. I looked in the logs to see if I had any other log like some I've had a few times like "session regenerate", but no log other than the "Bad Request" was generated.

**Comment by Moutard3** [comment]
I have the same issue on 3.6.5 ; After some tests it seems like it only happens when debug is on.
Only happens on pages that have Ajax requests.
In my case, I do an Ajax call to fill an array (with DataTables) but the response is malformed when debug is on (because of the session_regenerate_id warning) and disconnect me.

**Comment by markstory** [comment]
If your session rotates, your security tokens will become invalid as they are tied to the session ids.

**Comment by Moutard3** [comment]
The problem is that sometimes it happens multiple times in a row (got dc'd, I log and get instantly dc'd again), but it doesn't happens when `validatePost` is set to false

**Comment by markstory** [comment]
What is `dc'd` ? Sessions regenerate on login, which may help explain some of the rotations.

**Comment by Moutard3** [comment]
Sorry, disconnected.

**Comment by markstory** [comment]
> but after getting logged it should not regenerate instantly.

That's contrary to how AuthComponent works though.

**Comment by Moutard3** [comment]
So maybe it comes from my local server then.
Here's the full stacktrace as I can't find it in this thread:
```
Warning (2): session_regenerate_id(): Session object destruction failed.  ID: files (path: G:/Logiciels/laragon/tmp) [CORE\src\Http\Session.php, line 593]
Code Context
            if ($previousHandler) {
                return $previousHandler($code, $message, $file, $line, $context);
            }
Cake\Core\Plugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 41
session_regenerate_id - [internal], line ??
Cake\Http\Session::renew() - CORE\src\Http\Session.php, line 593
Cake\Auth\Storage\SessionStorage::write() - CORE\src\Auth\Storage\SessionStorage.php, line 104
Cake\Controller\Component\AuthComponent::setUser() - CORE\src\Controller\Component\AuthComponent.php, line 682
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 95
App\Controller\Admin\AppController::beforeFilter() - APP/Controller\Admin\AppController.php, line 9
App\Controller\Admin\UsersController::beforeFilter() - APP/Controller\Admin\UsersController.php, line 19
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 353
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 330
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 114
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 658
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 115
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 94
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 228
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\I18n\Middleware\LocaleSelectorMiddleware::__invoke() - CORE\src\I18n\Middleware\LocaleSelectorMiddleware.php, line 62
```

**Comment by CHOUKI-Mouhssine** [comment]
You need just to clear you web site cache
