### ISSUE TITLE
Add actual methods to interfaces instead of `@method` tags.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12094]
Tracking issue for interfaces that should be updated in 4.x

* [ ] ConnectionInterface
* [x] EntityInterface
* [x] InvalidPropertyInterface
* [ ] QueryInterface
* [x] RepositoryInterface
* [x] EventDispatcherInterface
* [x] LocatorInterface
* [x] ContextInterface

**Comment by dereuromark** [comment]
Are the remaining ones still doable? Or do we have to keep them out of the interface(s)?

**Comment by ADmad** [comment]
I am pretty sure all possible changes are done. Remaining ones we'll just have to keep.

**Comment by ADmad** [comment]
This reminds me `Entity` has couple of method (maybe more) `getOriginal()`, `getOriginalValues()` values which aren't present in `EntityInterface`.
