### ISSUE TITLE
Collections from Statements

### ISSUE THREAD

**Issue by ccriem** [cakephp/cakephp#12096]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.3
* Platform and Target: Linux SMP Debian 4.9, 10.1-MariaDB

### What you did
When creating a collection from a statement, for instance in cake console...

    >>> $rs = \Cake\Datasource\ConnectionManager::get('default')->query('SELECT id FROM users LIMIT 3');
    => Cake\Database\Statement\MysqlStatement {#1738}
    >>> foreach($rs as $r) echo "$r[id] ";
    1 2 3 ⏎
    >>> $c = new \Cake\Collection\Collection($rs); count( $c->toArray() );
    => 3
    >>> $c = new \Cake\Collection\Collection($rs); $c->extract('id')->toArray();
    => [
         "2",
         "3",
       ]
    >>> 

### What happened
... with some methods the first entry from the iteration seems swallowed.

### What you expected to happen
Collection is documented to allow for any Traversable as constructor argument. Connection::query() (according to the docs) returns an IteratorAggregate. So that should be a valid use case. But Collection's methods like toArray, extract, indexBy, ... return inconsistent results. Noticed with 3.5.1 and 3.6.3.

**Comment by lorenzo** [comment]
It depends on the fetch mode for the statement, what’s the fetch mode that you are using?

**Comment by ccriem** [comment]
How could I tell or change? The default PDO::FETCH_BOTH I guess. Because $c->toArray() returns an array [{"id":"1","0":"1"},{"id":"2","0":"2"},{"id":"3","0":"3"}]. 

BTW I "cheated" by editing code above to make it more readable, without rerunning. And introduced another quirk. Sorry for that. In fact, the original code was: 

>>> $rs = \Cake\Datasource\ConnectionManager::get('default')->query('SELECT id FROM users LIMIT 3')
=> Cake\Database\Statement\MysqlStatement {#1803}
>>> count( (new \Cake\Collection\Collection($rs))->toArray() )
=> 3
>>> (new \Cake\Collection\Collection($rs))->extract('id')->toArray()
=> [
     "2",
     "3",
   ]

When assigning to $c in an intermediate step, the iterator seems to be executed immediately (maybe by psysh?) In that case

>>> $c = new \Cake\Collection\Collection($rs)
=> Cake\Collection\Collection {#1797
     +"count": 3,
     innerIterator: PDOStatement {#1806
       +queryString: "SELECT id FROM users LIMIT 3",
     },
   }
>>> $c->extract('id')->toArray()
=> []

Anyway, that is not consistent behavior either, is it?

**Comment by ccriem** [comment]
Indeed, $c seems "consumed" by psysh output. 
    >>> $c = new \Cake\Collection\Collection($rs); json_encode( $c->toArray() )
    => "[{"id":"1","0":"1"},{"id":"2","0":"2"},{"id":"3","0":"3"}]"
    >>> $c = new \Cake\Collection\Collection($rs); $c->extract('id')->toArray()
    => [
         "2",
         "3",
        ]
    >>>

which reproduces the bug with intermediate assignment to $c as well.

**Comment by ccriem** [comment]
No problem. But just the same :(

**Comment by ccriem** [comment]
While coming closer to internal fiddlings, noticed another correlated strange behavior. All works well, if logQueries is set on, before $rs is created. But fails if not. Really strange.  Now using Console\Shell to avoid potential psysh quirks. So here another minimal example for illustration at slightly lower level:

    public function main( $logFlag = false )
    {
        $con = \Cake\Datasource\ConnectionManager::get('default');
        $con->logQueries( $logFlag );

        $rs = $con->query('SELECT id FROM users LIMIT 3');

        $c = new \Cake\Collection\Collection($rs);
        $p = $c->getInnerIterator();

        echo "P"; foreach($p as $x) echo " $x[id] "; echo "\n";
        echo "C"; foreach($c as $x) echo " $x[id] "; # ... close to the cause ...
    }
.

    $ bin/cake collection_test
    P 2  3
    C 1
    $ bin/cake collection_test 1
    P 1 2  3
    C 1

**Comment by ccriem** [comment]
Thx.

**Comment by markstory** [comment]
I tried to reproduce this in our test suite and the following test method is passing with the MySQL driver:

```php
    /**
     * test query with collections.
     *
     * @return void
     */
    public function testCollectionWrappingStatement()
    {
        $this->loadFixtures('Comments');
        $statement = $this->connection->query('SELECT * FROM comments LIMIT 3');

        $collection = new Collection($statement);
        $result = $collection->extract('id')->toArray();
        $this->assertSame(['1', '2', '3'], $result);
}
```

However, it does not pass with the SQLite driver. With SQLite, I get the same issue as you do where the first result is dropped. I've been able to reduce the source of the problem with SQLite down to the `unwrap()` call used during `extract()`, as the following code also fails:

```php
$statement = $this->connection->query('SELECT * FROM comments LIMIT 3');

$collection = new Collection($statement);
$result = [];
foreach ($collection->unwrap() as $x) {
       $result[] = $x['id'];
}
$this->assertSame(['1', '2', '3'], $result);
```

From what I can tell so far putting a `StatementDecorator` or `BufferedStatement` into `Collection` results in the buffering decorators being removed by Collection unwrapping. This results in results being lost as the statement being iterated is no longer buffered.

**Comment by markstory** [comment]
Looking into this more the issue stems from `Collection` inheriting from `IteratorIterator`. The constructor of `IteratorIterator` recursively calls `getIterator()` until it gets a non-aggregate iterator which happens to be `PDOStatement`. Because the buffering decorators are removed the collection instance is left with a raw `PDOStatement`. This object loses data as it is manipulated by `Collection`. 

As a workaround for this issue you can fetch all records from the statement before creating your collection instance.

```php
$collection = new Collection($statement->fetchAll('assoc'));
```

**Comment by markstory** [comment]
Pull request open now.
