### ISSUE TITLE
I am facing dynamic  routing issue with cakephp 3.6

### ISSUE THREAD

**Issue by anil-sidhu** [cakephp/cakephp#12104]
http://localhost/cake/my_app_name/ when i am using this defult url this is working fine
  but when i am  trying to use 
**http://localhost/cake/my_app_name/anything  it is giving me Not Found**  

  
for example i want to access 
http://localhost/cake/my_app_name/pages/10 

  and routing for this is 
    **$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);**

**Comment by markstory** [comment]
If the 404 page is not one created by CakePHP make sure that your webserver is configured correctly for URL rewriting.

**Comment by anil-sidhu** [comment]
i just find the solution 
go to the  /etc/apache2/sites-available/000-default.conf file 
update this`<VirtualHost *:80>
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

    . . .
</VirtualHost>`
 and restart apache 
sudo systemctl restart apache2
