### ISSUE TITLE
ORM should error when unexpected entities are used in _joinData

### ISSUE THREAD

**Issue by andruhapx** [cakephp/cakephp#12117]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.14.

### What you did
I loaded entity HABTM data with loadInto:

```php
$this->Companies->loadInto($Company, ['FollowedUsers'=>function(Query $query) { return $query->select(['id', 'email', 'name']); }]);
```

After that I set HABTM property of another table to  `$Company->followed_users:
$Notification->users = $Company->followed_users;`

### What happened
Each element of $Company->followed_users has _joinData property, 
so if some properties of _joinData are dirty,
and column names from companies_followed_users and notifications_users are the same
it tried to save dirty properties from companies_followed_users to notifications_users

### What you expected to happen

It should check if _joinData comes from different table and ignore that.
Right now Im doing foreach ($Company->followed_users as $User) $User->unsetProperty('_joinData');

**Comment by markstory** [comment]
> Use join model alias as key (like in cake 2.0) instead of '_joinData' in 4.0

This is not an option right now. It would be a significant break in compatibility that does not have an existing deprecation and forwards compatible implementation.

If we were checking `_joinData` instances what would happen when a mis-match is found? I would expect an exception to be raised. That would force you to have an implementation similar to what you have now where join records need to be unset.

**Comment by andruhapx** [comment]
Yes, exception will be good. At least exception allows prevent incorrect usage of `_joinData`. And maybe add some table/utility function to unset `_joinData` on dataset?
Anyway, will be good to add warning about possible issue into 3.5 documentation.

**Comment by markstory** [comment]
I'll leave the documentation updates to you. I've not come across a scenario a like this.

**Comment by dereuromark** [comment]
There seems to be no progress. Closing as stale. Please reopen in docs if needed.
