### ISSUE TITLE
Unable to retrieve database session

### ISSUE THREAD

**Issue by neobie** [cakephp/cakephp#12118]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.6 - 2.10.10
* Platform and Target: Tested with Apache with PHP 7.0 - 7.2

Load balancing web servers. 
All the servers can retrieve user login information (database session) with PHP 7.0. 
But if I upgraded server to PHP 7.1 / 7.2, the session cannot be retrieved anymore from that upgraded server.

**Comment by markstory** [comment]
How can someone reproduce the error you're having?

**Comment by markstory** [comment]
Closing as we don't know how to reproduce this and there has been no reply.
