### ISSUE TITLE
Route caching + unserialisable instances

### ISSUE THREAD

**Issue by josbeir** [cakephp/cakephp#12129]
This is a 

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4

### What you did
Attached a middleware using  $routes->registerMiddleware that is holding a class instance that cannot be serialised (AwsS3Adapter in my case)

### What happened
Exception thrown "Instances of Aws\S3\S3Client cannot be serialised" in the __sleep() method of AwsClient.php

### What you expected to happen
No exception

I have a middleware that is added using $routes->registerMiddleware that is holding an instance of an Aws\S3\S3Client, when using RoutingMiddleware with cache enabled all of Router::getRouteCollection() is serialised and cached. If this information holds any unserialisable data an exception will be thrown.

Disabling cache on the RoutingMiddleware  fixes the issue but then i loose route caching :-)

It would be handy if there was an option to prevent caching for certain routes/scopes or something in that matter. Or just disable caching of middleware in routes fully.

**Comment by markstory** [comment]
> Disabling cache on the RoutingMiddleware fixes the issue but then i loose route caching :-)

Yes, this is the simplest/most straightforward solution. Another option would be to implement the [Serializable interface](http://php.net/serializable) on your problematic class and resolve the serialization issue there.

I don't think the framework will be able to reliably detect and remove problematic objects buried in middleware.

> It would be handy if there was an option to prevent caching for certain routes/scopes or something in that matter.

We attempted that earlier and it resulted in complicated cache states that were not easy to define or read.

> Or just disable caching of middleware in routes fully.

How would those middleware objects be created when the cache was read?

**Comment by josbeir** [comment]
> Yes, this is the simplest/most straightforward solution. Another option would be to implement the Serializable interface on your problematic class and resolve the serialisation issue there.

Yes but that's not always a realistic possibility, Big and widely used libraries like the amazon aws php library explicitly added an exception in __sleep() so i'm facing a brick wall over there :-)

> How would those middleware objects be created when the cache was read?

One idea would be to add a RouteMiddlewareCollection (singleton?) class separate from the RoutesCollection class that holds all instances. 

When $routes->applyMiddleware('mymiddleware') is then called it will search in the collection class if the middleware is defined somewhere. 

```php
RouteMiddlewareCollection::registerMiddleware($name, $middleware)
RouteMiddlewareCollection::getMiddleware($name);
RouteMiddlewareCollection::removeMiddleware($name);
RouteMiddlewareCollection::hasMiddleware($name);
```

This would be a pretty 'dumb' class that doesn't do anything more that creates and stores the middleware instances

In the RouteCollection class this would require minimal adjustments to the getMiddleware method

Just an idea tho :-)

**Comment by markstory** [comment]
I'm not keen on adding more static methods/registries to the framework. Could your middleware that uses S3 exclude the unserializable instance upon serialization and fetch it from somewhere on wakeup?

**Comment by josbeir** [comment]
Ok, thought so :-)
Everything is possible.. Time to do some out of the box thinking then ;-)

**Comment by markstory** [comment]
Closing as I think this needs to be solved in the application code that contains unserializable objects.
