### ISSUE TITLE
3.6: Console Commands naming issues

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12123]
This is a (multiple allowed):

CakePHP 3.6 latest

### What you did
I tried to write a new command (instead of shell).
But the naming pattern here is not really yet good yet.
Also the overview on the CLI output.

I want to start a discussion how we can make this actually go in right direction.

- Before 3.5: Shells as commands with multiple subcommands (`bin/cake foo` and `bin/cake foo bar`) and plugin grouping.
- Now: Separate commands each, and now the naming and grouping becomes an issue. Flat list. They also have no description and it is very confusing.

I would like to see a grouping, by plugin maybe, but especially by namespace now.
But in fact it is just a alphabetically sorted list and now wildly mixing all the commands.

Side note (possible enhancement): In symfony console, they use `x:y[:z]` pattern etc for naming groups, also allows short calls if unique, e.g. `console code:style:sniff` can be called as `console c:s:s`.

Also:
setName() is not documented at https://book.cakephp.org/3.0/en/console-and-shells/commands.html
And also doesnt seem to work in the Available Commands list.

--- 

### Illustration

Before (at least grouping)
![cake35](https://user-images.githubusercontent.com/39854/40420882-1c2696fe-5e8a-11e8-906a-5e6e750f0176.png)
(cake <3.5)

And also then grouped subcommands when doing `bin/cake shell_name`:
![cake35_2](https://user-images.githubusercontent.com/39854/40421078-ddc28494-5e8a-11e8-9c44-8f47dc4f9a44.png)
(cake <3.5)

Now just super-long flat alphabetical list, very hard to keep organized from a plugin point of view without artifical prefixing everywhere (plugin_name_command) etc.
![cake](https://user-images.githubusercontent.com/39854/40420887-2077f022-5e8a-11e8-843f-ee4b39eccdf5.png)
(cake 3.5 shells or new commands)

A good example of clear grouping, colorful and visually helpful overview including description:
![symf](https://user-images.githubusercontent.com/39854/40420888-22ff2f2c-5e8a-11e8-886d-9f4aab377036.png)
(symfony console)

**Comment by dereuromark** [comment]
I can see how the BC issue here is slowing us down in terms of progress. And how we have to cope with a lot of the mentioned things for now during 3.x.
But maybe we can already do small improvements.
The description on the side (like in Symfony console) would already help a lot.
So would having at least some of grouping option (back), e.g. by plugin or alike.
Faking it right now using "plugin_name_" prefix in class name is not too nice, as I mentioned above.

**Comment by davidyell** [comment]
The naming conventions are especially relevant for me, as we manage lots of projects on various servers. So often either the project author, or the server admin will need to run shell commands on the box.

We might have just come back to it after a long time, and I tend to use `bin/cake` to see the commands, so that I know which one I'm looking for. It would be very handy to get more information about all the available commands without having to make, potentially multiple, guesses with the `-h` flag.

**Comment by dereuromark** [comment]
I added a draft to restore the old way in https://github.com/cakephp/cakephp/pull/12835
But maybe there is a better way that also works with the upcoming "space, comma, colon namespacing"?
