### ISSUE TITLE
MimeType for .bmp is missing

### ISSUE THREAD

**Issue by smap9** [cakephp/cakephp#12125]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: Apache, MariaDB

### What you did
Create a file download of an ```.bmp``` file:

```php
        $response = $this->response->withFile('path/file.bmp', [
            'download' => true,
            'name' => 'file.bmp',
        ]);
```

### What happened
File is downloaded as ```Content-Type: text/html; charset=UTF-8```

### What you expected to happen
File should be downloaded with ```image/bmp```.

### Possible fix
Add Mimetype for bmp files in https://github.com/cakephp/cakephp/blob/master/src/Http/Response.php#L120

**Comment by dereuromark** [comment]
You can open a PR to add this type.

**Comment by smap9** [comment]
PR open now
