### ISSUE TITLE
Mailer in plugin cannot read template correctly

### ISSUE THREAD

**Issue by tsmsogn** [cakephp/cakephp#12134]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4

### What you did

I made UserMailer and template in `Users` plugin as follows.

/var/www/myapp/plugins/Users/src/Mailer/UserMailer.php:

```php
<?php

namespace Users\Mailer;

use Users\Model\Entity\User;
use Cake\Mailer\Email;
use Cake\Mailer\Mailer;

class UserMailer extends Mailer
{

    public function resetPassword(User $user)
    {
        $this
            ->setTo($user->email)
            ->setSubject('Reset password')
            ->set(compact('user'));
    }
}
```

/var/www/myapp/plugins/Users/src/Template/Email/text/reset_password.ctp:

```php
<?php
/**
 * @var \Users\Model\Entity\User $user
 */

use Cake\Routing\Router;

$url = Router::url(array(
    'plugin' => 'Users',
    'controller' => 'Users',
    'action' => 'reset',
    $user->username,
    $user->token,
), true);

echo $url;
```

### What happened

cakephp raised `Cake\View\Exception\MissingTemplateException`.

The error message is follow.

```
Confirm you have created the file: "Email/text/reset_password.ctp" in one of the following paths:

/var/www/myapp/src/Template/Plugin/Users/Email/text/reset_password.ctp
/var/www/myapp/plugins/Users/src/Template/Email/text/reset_password.ctp
/var/www/myapp/src/Template/Email/text/reset_password.ctp
```

### What you expected to happen

Mailer in plugin reads template correctly.

**Comment by markstory** [comment]
Looks like mailer classes don't know that they are in a plugin. Usually we use the request context to infer the plugin name for templates. We cannot do that with Mailers though.

You will likely have to use `setTemplate('Users.reset_password')`.

**Comment by tsmsogn** [comment]
@markstory Thanks you for your replay. `setTemplate('Users.reset_password')` works fine for me.
