### ISSUE TITLE
quoteIdentifier() with function and parameters does not work

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#12147]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: PHP 7.2, MySQL

### What you did

```php
$query = $connection->newQuery()->from('customers');
$query->select(array(
    'created_date' => "DATE_FORMAT(customers.created,'%d.%m.%Y')",
));
$rows = $query->execute->fetchAll('assoc');
```

### What happened

Error message:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`%Y'`) AS `created_date`, DATE_FORMAT(`customers`.`created,'%H:%i:%s'`) AS ' at line 1
```

The quoted expression is:

```sql
DATE_FORMAT(`customers`.`created,'%d`.`%m`.`%Y'`)
```

### What you expected to happen

The quoted expression should be something like this:

```sql
DATE_FORMAT(`customers`.`created`,'%d.%m.%Y')
```
or just raw:

```sql
DATE_FORMAT(customers.created,'%d.%m.%Y')
```

### Possible source

I've checked the source code and found the possbile issue here:
https://github.com/cakephp/cakephp/blob/9c79d8ce3f991d421b5990001d803ae341601b7e/src/Database/SqlDialectTrait.php#L58

Here is a similar issues, but it's still not exact the same problem: https://github.com/cakephp/cakephp/issues/9091

I have already searched for a `$query->func()->dateFormat(...)` function, or something similar.

**Comment by lorenzo** [comment]
Use the functions builder instead, please. Quoting functions out of strings is just guesswork

**Comment by markstory** [comment]
Closing as you should use the function builders or query expression objects instead.
