### ISSUE TITLE
Integration tests and application routing

### ISSUE THREAD

**Issue by dakota** [cakephp/cakephp#12146]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.x
* Platform and Target: Any

### What you did
When relying on the Application class's `route()` hook to load routes, OR using a plugin with routes integration tests fail when trying to use array based routes.

A fully working example application is available: https://github.com/dakota/plugin-test/tree/application-routing

### What happened
`Cake\Routing\Exception\MissingRouteException` is thrown as demonstrated https://travis-ci.com/dakota/plugin-test/builds/74640142

### What you expected to happen
Integration tests should work.

The cause of failure is https://github.com/cakephp/cakephp/blob/master/src/TestSuite/IntegrationTestCase.php#L671

An attempt is made to match the route before the Router middleware is loaded, and so no routes have been loaded at this time. Trying to load the routes manually before the tests works unless named routes are used (In which case a duplicate route exception is thrown)

The server class will need to be refactored to load middleware/routes before execution. Alternatively an `AppBuilder` needs to be created that can build the application state (Including middleware and routing) before a server instance is created.

**Comment by sdustinh** [comment]
I have the same problem with the following:

```
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:55:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
cakephp/bake                1.6.4  Bake plugin for CakePHP 3
cakephp/cakephp             3.6.4  The CakePHP framework
cakephp/cakephp-codesniffer 3.0.3  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.4  A simple API extension for DateTime.
cakephp/debug_kit           3.14.2 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.7.2  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.1.0  A composer installer for CakePHP 3.0+ plugins.
```

**Comment by markstory** [comment]
#12150 is a potential solution to this problem.

**Comment by markstory** [comment]
Closing as a second pull request is open now.
