### ISSUE TITLE
Basic Auth fails to authorize numeric logins

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#12149]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: Linux, PHPUnit

### What you did
I have a controller, with an AuthComponent set up like this.
```php
public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Basic' => [
                    'userModel' => 'SomeModel',
                    'fields' => [
                        'username' => 'id',
                        'password' => 'client_secret'
                    ]
                ]
            ],
            'storage' => 'Memory',
            'unauthorizedRedirect' => false
        ]);
    }
```

I have a following fixture:
```php
'id' => 1,
'client_secret' => 'secret',
```

And the following test method:
```php
$this->configRequest([
       'environment' => [
           'PHP_AUTH_USER' => 1,
           'PHP_AUTH_PW' => 'secret',
       ]
]);
```

### What happened
CakePHP threats login as an integer and thus fails authentication.
https://github.com/cakephp/cakephp/blob/master/src/Auth/BasicAuthenticate.php#L79

### What you expected to happen
Successfull authentication.

**Comment by ADmad** [comment]
Why are you setting `PHP_AUTH_USER` to an integer in your test? It would be a string in real world usage.

**Comment by dmromanov** [comment]
@ADmad We use numeric logins in our app.
Besides, in RFC the only restriction to User-IDs (logins) is that they must not contain colons .
[RFC 7617](https://tools.ietf.org/html/rfc7617) (updates [RFC 2617](https://tools.ietf.org/html/rfc2617#section-2))

**Comment by dmromanov** [comment]
It works :D
