### ISSUE TITLE
3.6: BC Break: Shell in command runner gone

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12152]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6 latest

### What you did
Switched out the cake.php etc, and use the new command runner.
I also have an existing shell for some stuff to run on build:

```
bin/cake app prepare
```

### What happened
The shell is not found and therefore cannot be executed

### What you expected to happen
```
class AppShell extends Shell
```
should work.

Renaming it to e.g. MyAppShell works.

**Comment by markstory** [comment]
`AppShell` has been conventionally used as a base class for shells in the application. The https://github.com/cakephp/cakephp/blob/cfaa31c2cb09309a4db90daca1d64c7e5c3f6a07/src/Shell/Task/CommandTask.php#L38-L63 method has always excluded `AppShell` meaning it ould not show in the command list but still be executable as a 'secret' shell. Secret commands are no longer callable as they don't have a 'route'.

One solution would be to stop excluding `AppShell`. This will result in it showing up in the command list, but that seems like a reasonable thing given folks are using it.

**Comment by dereuromark** [comment]
Yes, App as a name is valid since 3.0.0 (for years now). So currently it just breaks existing use cases unnecessarily IMO.

**Comment by markstory** [comment]
Pull request open now.
