### ISSUE TITLE
Model.afterSaveCommit dispatch has mixed type for third argument

### ISSUE THREAD

**Issue by JoepRoebroek** [cakephp/cakephp#12163]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4 (but from release notes, I found this happens since 3.6.3)
* Platform and Target: nginx, mysql, ubuntu 16.04

### What you did

`public function afterSaveCommit(Event $event, EntityInterface $entity, ArrayObject $options)`

### What happened

Called `findOrCreate()`

Got: argument 3 passed to Camptoo\ORM\Table::afterSaveCommit() must be an instance of ArrayObject, array given

### What you expected to happen

No error

https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1678

This line should convert options to an ArrayObject, just like the save operation does.

**Comment by dereuromark** [comment]
PR open.
