### ISSUE TITLE
Insertion fails for tables with column names containing periods

### ISSUE THREAD

**Issue by ZackaryMurphy** [cakephp/cakephp#12160]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: Apache, MySQL

### What you did
Performed a save query on a table which has a column with a period in its name.

### What happened
The ORM generated incorrect SQL

### What you expected to happen
The insertion to happen

I have a table with colum names along the lines of 'T0.010S'. When attempting to perform a save the generated SQL is INSERT INTO 'table' ('TO'.'010S') VALUES (....) which generates a MySQL error for a non existent field. Since the database was set up by a client, changing the column names is not an option.

**Comment by markstory** [comment]
Yes. `.` is not supported in column names. We cannot easily fix this issue as we use `.` in field names to separate table and field names. Having to support `.` in field names will require non-trivial amounts of complexity that aren't worth the overhead for most applications.
