### ISSUE TITLE
Http\Client\Adapter\Stream not restoring error handler if wrapper throws exception

### ISSUE THREAD

**Issue by snelg** [cakephp/cakephp#12168]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: phpunit

### What you did
Ran some unit tests that use php-vcr

### What happened
I noticed that some error messages were disappearing. Figured out that ConsoleErrorHandler wasn't handling errors.
Tracked down the culprit to Cake\Http\Client\Adapter\Stream.php:
`restore_error_handler` on line 310 not being called when `fopen` on line 309 throws an exception, leaving the little error handling closure on line 306 handling all subsequent errors for the whole process. 

### What you expected to happen
I expected to see error messages :)

I have a pull request ready to go, just submitting this issue first.

**Comment by markstory** [comment]
Closing as there's a pull request open now.
