### ISSUE TITLE
TranslateBehavior allowEmptyTranslations=false does not allow to go back to default language

### ISSUE THREAD

**Issue by pcworld** [cakephp/cakephp#12176]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: all

### What you did
I use `TranslateBehavior` on a table as follows:
```php
$this->addBehavior('Translate', [
	'fields' => ['somefield'],
	'allowEmptyTranslations' => false
]);
```
I create record A without translation. As expected, when querying A with a nondefault locale, the `description` field falls back to the original record.
I then create a nonempty translation of `somefield` with nondefault locale x. As expected, when querying A with locale x, the `description` field shows the translated content.
I then try to set the `description` field in locale x to the empty string.

### What happened
The modification is ignored, the localized `description` field retains its own nonempty value. 

### What you expected to happen
I expected the translation record to be either deleted or changed to the empty string. In both cases, this would allow to fall back to the default language (empty localized string and missing localization record seem to be treated the same way), which is the behavior I expect to happen. As it stands there is no way to fall back to default language once a localization has been created. The current behavior of `'allowEmptyTranslations' => false` does not make sense to me, it has the (useful/as expected) behavior to fall back to the default language when a localized record is empty, but does not allow to create empty records or to delete existing translations.

### Solutions
I suggest that when `'allowEmptyTranslations' => false` is set, let saving of empty translations go through, or better yet let saving empty translations delete existing localized records. In the latter case the code paths for checking for empty translations could be removed (except for interoperability with tables that were only later changed to `'allowEmptyTranslations' => false`, not sure if this should be supported).

The current behavior was introduced with PR #10342 to fix a bug regarding duplicate keys. To implement my suggested behavior, either the `_findExistingTranslations` method needs to be fixed to also take into account records with empty translations. Or in case the deletion behavior would be implemented (which I find better as it prevents unnecessary translation records) these code paths would not need to be touched. In either case, `_unsetEmptyFields` would need to be removed again.

I have created the following workaround by extension of `TranslateBehavior` that allows saving of empty records with `'allowEmptyTranslations' => false` and also prevents the duplicate key error, I publish it under [CC-0 1.0 Universal (public domain) license](https://creativecommons.org/publicdomain/zero/1.0/deed.en):
```php
<?php
namespace App\Model\Behavior;

use Cake\Datasource\EntityInterface;
use Cake\ORM\Behavior\TranslateBehavior;

/**
 * As of CakePHP 3.6.4, the `allowEmptyTranslations` option for TranslateBehavior allows the fallback to default
 * translation when the translation is empty.
 * However, it also prevents existing translations from being set back to empty (i.e. fallback to default language).
 * This class extends TranslateBehavior to allow setting translations to empty even when `allowEmptyTranslations` is
 * set.
 * Note that it currently only works if the translation table is called 'I18n'.
 *
 * @package App\Model\Behavior
 */
class MyTranslateBehavior extends TranslateBehavior
{

    /**
     * Don't unset empty fields in order to be able to save empty translations.
     */
    protected function _unsetEmptyFields(EntityInterface $entity)
    {
    }

    /**
     * When searching for existing translations, temporarily remove the condition that the translation content must not
     * be empty.
     * Otherwise when updating a translation an INSERT instead of an UPDATE is attempted, leading to a duplicate key
     * SQL error.
     */
    protected function _findExistingTranslations($ruleSet)
    {
        $association = $this->_table->getAssociation($this->_translationTable->getAlias());
        $conditions = $association->getConditions();
        $origConditions = $conditions;
        unset($conditions['I18n.content !=']);
        $association->setConditions($conditions);
        $ret = parent::_findExistingTranslations($ruleSet);
        $association->setConditions($origConditions);
        return $ret;
    }
}
```

**Comment by markstory** [comment]
If you are disabling empty translations via `allowEmptyTranslations = false` why do you also want to use empty translations? I think you need to make a decision on which mode/behavior you want to use.

**Comment by ADmad** [comment]
Closing as there was no follow up and the issue has gone stale.
