### ISSUE TITLE
abort() in command class breaking tests

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#12181]
This appears to be a bug in CakePHP Version: 3.6.4

I'm having trouble testing `$this->abort()` in a Command class. The docs suggest that I can just use `$this->assertExitCode(Command::CODE_ERROR);`, but the `StopException` that `abort()` throws bubbles all the way up to my test and breaks it unless if I put `exec()` in a try/catch block.

Should `ConsoleIntegrationTestCase::exec()` be catching exceptions thrown by `abort()`?

### What I did
```
class FooCommand extends Command
{
    public function execute(Arguments $args, ConsoleIo $io)
    {
        $this->abort();
    }
}
```
```
class FooCommandTest extends ConsoleIntegrationTestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->useCommandRunner();
    }
	
    public function testExecute()
    {
        $this->exec('foo');
        $this->assertExitCode(Command::CODE_ERROR);
    }
}
```

### What happened
`Cake\Console\Exception\StopException : Command aborted` is thrown and a a stack trace is displayed.

### What I expected to happen
[The docs](https://book.cakephp.org/3.0/en/console-and-shells/commands.html#testing-interactive-shells) suggest that `abort()` won't break tests and can be tested with `assertExitCode()`.

**Comment by jeremyharris** [comment]
Closing as PR is up
