### ISSUE TITLE
RFC: Refactor the flash message code

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#12180]
I would like to remove almost all code from the component and helper and put it into a new object called `FlashMessage`. The constructor will take a session object.

This way the component can be reduced to almost just the `__call()` method and the constructor will just instantiate the object and pass the session from the controller. The component will basically just become a loader for the class and delegate all calls to the `FlashMessage` object for BC. Another possibility the refactor of this would give us is to load it in the middleware stack and inject the flash as request attribute. Feels hackish but since we don't have a DI container this could work as well.

The helper will probably lose ~50% of it's code as well and the whole logic of reading and writing flash messages will be encapsulated in *one* object that is used by the component and helper. So the helper won't have any logic related to the flash messages and take care of what it should do: Only presentation.

This should work in a BC way and could be done in 3.x or directly go for 4.x. My only problem is where to  place the `FlashMessage` class. We don't have something like `Application\Service` to put an object like this into.

If you guys agree I'll do a PR.

**Comment by markstory** [comment]
Do you have an example of what would change in application after the changes you have in mind are done?

**Comment by burzum** [comment]
Nothing would change on the surface. But if you want to change the whole flash implementation it's a single object. This is especially easy to exchange if you use it through a DI container.

The interface of the object would be mostly the same as the components plus has() and consume() for the code that is now in the helper.

**Comment by ADmad** [comment]
Just out of curiosity what alternate implementation would one want for flash messages? It's basically just setting a session var in current request and pull in back out in next request.

**Comment by burzum** [comment]
@ADmad yes, however take a look at Euromarks flash plugin. Also you could, in theory, have an interface class for the flash and use it in a console as well. So if you have a service class that expects a FlashMessageInterface the service can be used with the console and web or even any other UI.

However the proposed change would improve the code. If the overall opinion "if it works it's good enough" I'm OK with that. I'll stop looking for improvements and put my time and energy into other areas of interest.

**Comment by ADmad** [comment]
>  take a look at Euromarks flash plugin

I had a quick look at his [dereuromark/cakephp-flash](https://github.com/dereuromark/cakephp-flash) and I think he would still have to make changes in `FlashComponent` and `FlashHelper`. For e.g. his `FlashComponent::beforeRender()` takes decisions using request object and sets response headers. I don't see that code going somewhere else unless you are going to inject request and response objects  into `FlashMessage` object and ensure their mutated state it passed back to controller. Skimming through the `FlashHelper`, probably a lot of it's code could be moved inside custom `FlashMessage` implementation.

So if one still needs to override the component (and maybe helper too) for enhancements I don't see how a `FlashMessage` helps, the code split remains.

> Also you could, in theory, have an interface class for the flash and use it in a console as well.

Persistence across requests is the main USP for flash messages which isn't an issue in console. One could use a `FlashMessageInterface` implementation of simply maintain a in-memory list and then output at a later point but I don't see that being needed often and could be achieve with a simple array too.

**Comment by markstory** [comment]
> Nothing would change on the surface, it's fully BC. 

Would the session contain both the new objects and the current array data? The plugin you linked to appears to be coupled to the array data stored in the session. Replacing that data with an object will be challenging to make backwards compatible.
