### ISSUE TITLE
Promote i18n to a Plugin

### ISSUE THREAD

**Issue by Robertroid** [cakephp/cakephp#12193]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0

I think it should be good if **i18n** could me moved to a separate plugin from core, as not all projects require it, and it's not an essencial element either, so the request process can be alleviated a bit more when it's not needed. This means that the php_intl extension only be required when the plugin is on.

**Comment by lorenzo** [comment]
@Robertroid Out of curiosity, is installing the extension not an option to you?

**Comment by Robertroid** [comment]
Oh, no, not yet, but I did fear once with a hosting that I thought it may not have it, and my client just had a contract with them. Gladly that was not the case.
But still, it makes me feel that it's a bit tight coupled

**Comment by markstory** [comment]
>  But still, it makes me feel that it's a bit tight coupled

Currently the datetime objects are used by the ORM. I don't see how a plugin would help as the ORM would pull in the i18n package anyways.

**Comment by Robertroid** [comment]
Sorry, couldn't answer before.
Well, then it's pretty much settled. If it's integrated into cake's datetime, as @markstory says, then there is nothing we can do, as that would require far too much work that I thought. Thanks for your attention.
You can go and dismiss this RFC as if nothing happened 😭 

PS:

> Calling reliance on a "core" PHP extension "tight coupling" is **a bit of a stretch**.
Sorry, I'm not english native, so what would that mean?

**Comment by burzum** [comment]
> Currently the datetime objects are used by the ORM. I don't see how a plugin would help as the ORM would pull in the i18n package anyways.

Provide an interface for whatever the ORM needs to do with the dates and an implementation for Chronos, native and Carbon. This way you can make the dependency optional.

`WhatEverNeedsADateObject::__construct(DateObjectInterface  $date)`

I need to check what exactly we use the date here but I'm sure a wrapping object would do it very nice.

**Comment by JayWalker512** [comment]
@Robertroid that phrase "a bit of a stretch" refers to an exaggeration. It probably comes from another phrase such as "stretching the truth" which again refers to exaggeration.

**Comment by ADmad** [comment]
Closing for reason stated by @markstory.

Those stuck on crappy hosts which don't provide `intl` extension can try this [intl](https://github.com/CakeDC/Intl) polyfill instead.

**Comment by ADmad** [comment]
The `DateTimeType` class and it's sub classes uses `Cake\I8n\Time` for parsing localized date time strings into objects. ORM doesn't do any translation.

I don't think we should spend time trying to accomodate a handful of potential users you can't have intl extension installed.

**Comment by lorenzo** [comment]
The ORM automatically detects the absence of the i18n package, and uses plain php DateTime objects

**Comment by burzum** [comment]
@lorenzo so whats causing a problem for him then?
