### ISSUE TITLE
FixtureManager::_setupTable not respecting $drop argument

### ISSUE THREAD

**Issue by ijonn** [cakephp/cakephp#12194]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.

### What I did
Tried to create shell script that will load fixtures using FixtureManager. Main goal of this script was to load data to tables in database without dropping them. So I did:

```php
// getting model name as argument
$modelName = $this->args[0];
// getting instance of FixtureManager
$this->fixtureManager = new FixtureManager();
// loads fixtures
$this->fixtureManager->fixturize($this);
// setting database connection with default database and without alias
$db = ConnectionManager::get('default', false);
// loading fixture with args: model name, connection to database, dropping tables set to false
$this->fixtureManager->loadSingle($modelName, $db, $dropTables = false);
```
During debugging we have found issue in these lines:
```php
$hasSchema = $fixture instanceof TableSchemaAwareInterface && $fixture->getTableSchema() instanceof TableSchema;
if (($drop && $exists) || ($exists && !$isFixtureSetup && $hasSchema)) {
   $fixture->drop($db);
   $fixture->create($db);
}
```

Source: https://github.com/cakephp/cakephp/blob/a3c937712d6617ca5c65acc4cde3d91a7e9698a4/src/TestSuite/Fixture/FixtureManager.php#L255

### What happened
Loading fixtures as itself works fine, but I noticed that despite setting dropping tables to false it still does that. Firstly FixtureManager drops table, then he create it, after those two steps it finally pushes records to database.

### What was expected
What I expected was to load records from fixtures without dropping tables when drop argument was set to false.

**Comment by markstory** [comment]
The argument is ignored when the table exists, as the current table state is unknown. The table schema could be wrong which would cause record insertion to fail.

> Tried to create shell script that will load fixtures using FixtureManager.

Where are you loading data? The fixture manager is not intended to be used for seeding data into tables. Instead you should use a [seed migration](https://book.cakephp.org/3.0/en/migrations.html#seed-seeding-your-database)

**Comment by markstory** [comment]
Closing as you should likely be using database migrations and not fixtures.
