### ISSUE TITLE
prevent serializing values in redis cache engine

### ISSUE THREAD

**Issue by ava007** [cakephp/cakephp#12208]
This is a (multiple allowed):

* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version 3.6
* Platform and Target: nginx 1.14, redis 4.0

### What you did
Business requirement is to write html output from cakePHP to redis cache
and read the redis cache directly from nginx in order to gain performance and scalability.

### What happened
Writing to redis cache works, reading works as well. Problem is that data is serialized by CakePHP while writing to redis. Serialized data can't be deserialized  by nginx before sending data to the webbrowser.

### What you expected to happen
Provide a way to write data/values without serializing.

Other Cache Engines do not serialize data:

MemcachedEngine.php (does not serialize at all):

```php
    public function write($key, $value)
    {
        $duration = $this->_config['duration'];
        if ($duration > 30 * DAY) {
            $duration = 0;
        }
        $key = $this->_key($key);
        return $this->_Memcached->set($key, $value, $duration);
    }
```
FileEngine.php (serialize if configured)

```php
    public function write($key, $data)
    {
        if ($data === '' || !$this->_init) {
            return false;
        }
        $key = $this->_key($key);
        if ($this->_setKey($key, true) === false) {
            return false;
        }
        $lineBreak = "\n";
        if ($this->_config['isWindows']) {
            $lineBreak = "\r\n";
        }
        if (!empty($this->_config['serialize'])) {
            if ($this->_config['isWindows']) {
                $data = str_replace('\\', '\\\\\\\\', serialize($data));
            } else {
                $data = serialize($data);
            }
        }
```

WinCacheEngine.php (does not serialize)

```php
public function write($key, $value)
    {
        $key = $this->_key($key);
        $duration = $this->_config['duration'];
        return wincache_ucache_set($key, $value, $duration);
    }
```

RedisEngine.php (always serialize)

```php
    public function write($key, $value)
    {
        $key = $this->_key($key);
        if (!is_int($value)) {
            $value = serialize($value);
        }
        $duration = $this->_config['duration'];
        if ($duration === 0) {
            return $this->_Redis->set($key, $value);
        }
        return $this->_Redis->setex($key, $duration, $value);
    }
```

Please advise:

- if there are other ways to write to redis without serialize values
- if I should make a PR in order to make redisEngine configurable for serializing (like FileEngine).
- other thoughts?

thanks.

**Comment by markstory** [comment]
I believe that serialisation is required for redis as the redis drivers do not handle serialisation automatically unlike wincache and memcached. If serialisation were disabled you would be unable to store non-scalar values.

**Comment by lorenzo** [comment]
You don’t need to use the Cache class to interact with redis, you could just use tesis directly and store whatever blob you need

**Comment by ava007** [comment]
thanks for your hint @lorenzo 

I'm calling redis directly now as follows and it seems works without serialization:

use Redis;

$redis = new Redis();
$rc = $redis->connect('127.0.0.1', '6379',0);
$rc = $redis->select(0);
$rc = $redis->set($key, $value);


However, please let me know if I should make a PR and make serialization optional for RedisEngine.

**Comment by lorenzo** [comment]
Thanks but no need for the PR. That would complicate the code in the caching engine and would make it unusable for most caching operations
