### ISSUE TITLE
Multiple entitiy relation

### ISSUE THREAD

**Issue by MertDalbudak** [cakephp/cakephp#12205]
This is a (multiple allowed):

* [~] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Linux Ubuntu PHP 7.0, innoDB MySQL Workbench

Already explained the issue on stackoverflow: https://stackoverflow.com/questions/50761347/multiple-entitiy-relation

I checked all issues by the topic name for "multiple relation's" but didn't found something.

**Comment by markstory** [comment]
If you model your writable associations as a 'hasMany' association between `Products` and `ProductsAttributes` will allow you to create the duplicate join data you want to have that is not possible with a belongsToMany association.

Another association type is worth exploring. Adding a mode into the existing `belongsToMany` association feels risky.

**Comment by MertDalbudak** [comment]
I tried out multiple different associations but `belongsToMany` works best till I found this issue.
I will definetly looking forward to try out more associations maybe in combination with the `ProductAttributes` Table.
I will do a little workaround here and try to share my results here asap.

**Comment by MertDalbudak** [comment]
@markstory I tried it and done it. It worked very well.
Easy and simply. Sorry for the late reply btw.   :-)
