### ISSUE TITLE
maxlength is broken

### ISSUE THREAD

**Issue by kousu** [cakephp/cakephp#12211]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Platform and Target: `bin/cake server` + MariaDB 10.1.33

### What you did

I'm updating some CakePHP 2.x code to 3.6 and I am trying to use the [newer FormHelper](https://book.cakephp.org/3.0/en/views/helpers/form.html#creating-input-elements).

Here's the old code:

```
      echo $this->Form->input('firstname', array(
        "label" => array("text" => "First Name", 'class' => 'control-label'),
        "class" => "input-medium"
      ));
```

Here's the new code:

```
      echo $this->Form->label('firstname', 'First Name', [ "class" => "control-label" ] );
      echo $this->Form->text('firstname', [ "class" => "input-medium" ]);
```

### What happened

The old code generates

```
<div class="input text"><label class="control-label" for="firstname">First Name</label><input type="text" name="firstname" class="input-medium" maxlength="50" id="firstname" value="XXXXXX"/></div>
```

the new code generates

```
    <label class="control-label" for="firstname">First Name</label><input type="text" name="firstname" class="input-medium" value="XXXXXX"/>
```

Notice that it's _dropped_ the `maxlength` [feature](https://github.com/cakephp/cakephp/issues/2137). Now I need to manually add `[ "maxlength" => 50 ]` and keep that in sync with my database schema.

### What you expected to happen

I'm surprised `input()` is still supported, given that it's not in the docs; I expected it to throw an error instead of running.

But given that it runs, I expect it to do the same thing as the old code, but instead it's lost a useful feature---`maxlength`; it's also lost the wrapper `<div>` and setting `id` to the name of the field but I'm not torn up about those: I think those are elements that should be written explicitly by the programmer if desired.

**Comment by ADmad** [comment]
What does your `Form::create()` statement look like in new 3.6 code?  Most likely you forgot to update the old code and pass an entity object as 1st argument to the method instead of just model name string that was used in 2.x.

**Comment by kousu** [comment]
Hi @ADmad, that was a super quick response; thanks.

Here's a complete form (the full one [is here](https://github.com/santropolroulant/volunteerdb/blob/migrate-to-3/src/Template/Volunteers/edit.ctp) but I haven't pushed the changes I made that ran into this bug):

```
<?php
    echo $this->Form->create($volunteer);
    echo $this->Form->hidden('id');
?>

    <div class="span4">
    <?php
      echo $this->Form->label('firstname', 'First Name', [ "class" => "control-label" ] );
      echo $this->Form->text('firstname', [ "class" => "input-medium", "type" => "text" ]);
      echo "\n";
      echo $this->Form->input('firstname', array(
        "label" => array("text" => "First Name", 'class' => 'control-label'),
        "class" => "input-medium"
      ));
    ?>


<?php
    echo $this->Form->end();
?>

```

**Comment by kousu** [comment]
I've traced the code a bit and I think what's happening is that there's some [inflection magic](https://github.com/cakephp/cakephp/blob/614f906e001f5e98174d1b273119931859bd7f39/src/View/Helper/FormHelper.php#L1676) in the new path which calls `widget()`:

```

    public function __call($method, $params)
    {
        ....
        $options = $this->_initInputField($params[0], $options);
        return $this->widget($options['type'], $options);
    }
```

whereas the [old path](https://github.com/cakephp/cakephp/blob/614f906e001f5e98174d1b273119931859bd7f39/src/View/Helper/FormHelper.php#L1241) calls [`control()`](https://github.com/cakephp/cakephp/blob/614f906e001f5e98174d1b273119931859bd7f39/src/View/Helper/FormHelper.php#L1149).

```

    public function input($fieldName, array $options = [])
    {
        deprecationWarning(
            'FormHelper::input() is deprecated. ' .
            'Use FormHelper::control() instead.'
        );
        return $this->control($fieldName, $options);
    }
```

I'm not sure why I'm not seeing that deprecation warning. I have debug mode turned on.

**Comment by ADmad** [comment]
Are you sure you aren't using a customized form helper?  `__call()` should not be triggered when using `input()` and you should see the deprecation error in 3.6 (unless you have disabled showing of `E_USER_DEPRECATED` errors through error config).

**Comment by kousu** [comment]
I'm pretty sure I haven't customized anything. I started from https://github.com/cakephp/app and re-added the templates and controllers. My form code is [here](https://github.com/santropolroulant/volunteerdb/blob/migrate-to-3/src/Template/Volunteers/edit.ctp) now. The issue should be reproducible like this:

```
git clone -b migrate-to-3 https://github.com/santropolroulant/volunteerdb/
cd volunteerdb
composer install
vim config/app.php #-> add a DB connection
bin/cake server
firefox http://localhost:8765/Volunteers/edit
```

**Comment by ADmad** [comment]
Since you allow calling edit action without an id, making a GET request ends ups setting `$volunteer` to [null](https://github.com/santropolroulant/volunteerdb/blob/migrate-to-3/src/Controller/VolunteersController.php#L128). Without the entity set there's no way for the form helper to know about your table schema and do things like selecting proper input type or setting `maxlength` attribute.
