### ISSUE TITLE
Placing custom Model methods in separate places so Bake doesn't remove them

### ISSUE THREAD

**Issue by FinlayDaG33k** [cakephp/cakephp#12214]
This is a (multiple allowed):

* [x] feature-discussion (RFC)
* [ ] bug
* [ ] enhancement

* CakePHP Version: N/A
* Platform and Target: N/A

### What you did
Come up with a possible solution to this issue, which I now bring here for debate.

### What happened
Please bear with me, this can be a bit of a read...
While working on my project I kept coming by the same issue over and over while using the `bake` tool to automatically update models after I editted my `MySQL` schema in `MySQL Workbench`:
> It keps overwriting my custom methods

Hoping CakePHP would have an easy solution for this, I went to the CakePHP forums and opened [a question there](https://discourse.cakephp.org/t/using-bake-without-losing-custom-methods/4392) to seek for help.
This, however, led to the answer that what I wanted wasn't easily doable.
After thinking for a few moments, I came up with something in my head:

> Why can't we just put those custom methods in another file?

So, [I replied](https://discourse.cakephp.org/t/using-bake-without-losing-custom-methods/4392/5?u=finlaydag33k) on the thread with a possible new feature that could be implemented.
Basically we put custom methods for events like `afterSave()`, `beforeDelete()`, `beforeFind()` etc. in a different location, like `Model/Extension/UsersTableExtension.php`.
CakePHP would obviously load up the `Model/Table/UsersTable.php` and after doing that, it would try to see if `UsersTableExtension.php` exists (either throw an error if it doesn't or leave it be)
This file would then be loaded up and extend the `UsersTable` class like so (As far as I have read, chaining classes like this is possible, correct me if I'm wrong):
```php
<?php
  namespace App\Model\Table;

  // Just an example, the Devs should come up with the convention n such
  class UsersTableExtension extends UsersTable {
    public function afterSave(Event $event, EntityInterface $entity, \ArrayObject $options) {
      // do stuff
    }
  }
```

This way, `bake` won't keep overwriting custom methods that we have cooked.
Now, I understand that somebody here will throw in the "just build the models by hand" or "bake is not made for that purpose", but do understand that this could potentially make `bake` a lot more useful (especially for newer CakePHP users) in the longer run.
It would also potentially save time for developers like me (that use `bake` to generate the models) as we don't have to keep re-adding the methods (or discarding the changes in the git client).

### What you expect to happen
Discuss with me the feasability of this feature.
Unfortunately, I haven't dived deep enough in CakePHP and PHP programming in general (I do know my way around a bit, but am still learning a lot everyday) to build this feature into CakePHP myself and create a merge request.
But I hope you guys give it a thought anyways.

**Comment by markstory** [comment]
Extension classes could work. Traits are another option that folks sometimes use. 

Another option would be to make bake significantly smarter and able to re-include methods/code it doesn't know about.

**Comment by FinlayDaG33k** [comment]
Traits seem like they would do the job, but by giving the docs a look, I don't think they would be as intuitive.
Also, doesn't bake also overwrite code that loads up traits? (Haven't worked with them, so I don't really know).

bake could be made to be able to re-include methods/code it doesn't know about, but then again, I think like extension classes would be more intuitive (and probably work more reliable in the long run?).
Also would clean up the code a CakePHP user has to worry about (users like me, that don't touch the core of the framework itself).

**Comment by lorenzo** [comment]
I often just use git to restore my changes after doing another bake, would a workflow like that work?

**Comment by FinlayDaG33k** [comment]
@lorenzo I currently use that workflow as well, but it's not very efficient and takes up a lot of unnecessary time in the long run (you'll have to read the stuff, check what should be removed and what not, check whether you missed anything etc. etc.).
also, this induces more risk of error as you could accidentally push the removal of the code (for example, when you're in a bit of a hurry or tired or something).
This can obviously be undone quite simply, but imo it's better to not have that risk in the first place (better safe than sorry).

**Comment by josegonzalez** [comment]
I think traits are probably the best solution here. Everything else we might implement would end up in a hokey reimplementation of something the php core provides.

I filed an issue in bake [here](https://github.com/cakephp/bake/issues/205) for this functionality, though don't personally have time to work on it.

**Comment by FinlayDaG33k** [comment]
I've been fiddling with it, and nearly immediately already stumbled on something that could make traits a bit more difficult:
```php
<?php
// src/Model/Entity/AfterSaveTrait.php
namespace App\Model\Entity;

trait AfterSaveTrait {
    public function afterSave() {
        // do stuff
    }
}
```

This pretty much seems like I can only have 1 trait that does the `afterSave()`.
Which is fine if you want to share the same logic between different table and/or entity classes, but when you want every table/entity class to have different `afterSave()` logic this can become a roadblock.

That's where my solution differs: it allows for easy per table (and probably can - and should - be made with entities as well) customization.

**Comment by ADmad** [comment]
@FinlayDaG33k The suggested implementation uses traits would have 1 trait per table class. Not a single trait used by all tables.

**Comment by FinlayDaG33k** [comment]
So it would be more like:
```php
<?php
// src/Model/Table/UsersTableTrait.php
namespace App\Model\Table;

trait UsersTableTrait {
    public function afterSave() {
        // do stuff
    }
}
```

But wouldn't that require me to also define the `use UsersTableTrait` every time I rebake my models?

**Comment by jeremyharris** [comment]
I think @lorenzo's suggestion is the way to go, and is what I do (especially when re-baking fixtures which is my most common case). I use `checkout -p` to checkout certain bits.

Adding some sort of smart comparison to bake sounds almost like reinventing version control, e.g. what happens if they have a buildRules already? Sure bake could compare or append, or even get fancy and parse/change the AST, but that seems like a bit much to me for something that git already handles well.

I'm not sure I totally understand creating methods for a table before baking, I think the other way around is more common. Perhaps re-baking with new templates that add functionality to all tables? Except in that case a behavior or adding the method to a base Table class might be a better route.

**Comment by ADmad** [comment]
> But wouldn't that require me to also define the use UsersTableTrait every time I rebake my models?

Nope, bake could check the existing traits you have for the model and add the required "use" statements for you.

**Comment by FinlayDaG33k** [comment]
@jeremyharris using Git (or SVN if that's your gig) will become a pain in the buttocks in bigger projects.
manually using the checkout way with 1 table that gets re-baked? do-able.
Now imagine the same... but with 10, 20 or even 50 tables? have fun with that .-.

@ADmad hm... I'll tinker around with Traits tonight.
I've read some more about PHP Traits, and if Bake can re-add those `use` statements, then it does about the same as my proposal.

**Comment by raul338** [comment]
Another option would be:
1. bake Articles model
1. rename ArticlesTable to BaseArticlesTable
1. create a new class Articles Table extends BaseArticlesTable
1. define behaviors/validators/finders/event hooks
1. profit

Same would be with entities and fixtures. Maybe another option would be to bake to print diff with current class? Something like
```
Column `user_id` found in `articles` table but no BelongsTo relationship found in
ArticlesTable to UsersTable, use the following code to add:
$this->belongsTo('Users');
```
But I think this approach should be discussed in bake repo

**Comment by FinlayDaG33k** [comment]
Sorry for my late response, I have been busy with other stuff the past few days and had to put this on hold.
I have been trying out Traits last night, and it seems to accomplish the same as my proposal would have.
The only issue that remains is that `bake` removes the `use` statement.

If bake could be updated to keep the `use` statements, then this discussion can be closed :)

**Comment by josegonzalez** [comment]
@FinlayDaG33k is that something you'd be interested in working on? You can probably use [`class_uses`](http://php.net/manual/en/function.class-uses.php) to implement pulling traits :)

**Comment by FinlayDaG33k** [comment]
@josegonzalez interested: yes
but since I don't know how to CakePHP core works by itself, and am somewhat of a sloppy developer, I doubt I'll make a decent solution for this :\

**Comment by josegonzalez** [comment]
Thats fine, baby steps :)

For some starting points:

- You can use the `$tableObject` [here](https://github.com/cakephp/bake/blob/master/src/Shell/Task/ModelTask.php#L120) to add the used classes context.
- Modify the [twig template](https://github.com/cakephp/bake/blob/master/src/Template/Bake/Model/table.twig#L26) to inject those used traits. You can probably do it super nicely and split up the trait namespace and the trait name if you _really_ want, so that the long-form goes at the top and you use the short name inside the class itself.

**Comment by FinlayDaG33k** [comment]
I'll go finish my current things first about questions I've asked on the Forum, then I'll get started with this (probably Sunday due to my girlfriend coming over).

**Comment by FinlayDaG33k** [comment]
Due to a lack of time, I'll have to put this on hold for a bit.
Somebody else can work on this if he/she wants to.
If this issue is still open when I find the time, I'll start working on it :)

**Comment by dereuromark** [comment]
Closing then for now, as there are no concrete action points. Maybe this can also be first tried as plugin solution.
