### ISSUE TITLE
Inconsistent behavior between FormHelper::control() and modelless form validation

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#12219]
Type: Behavior inconsistency
CakePHP Version: 3.5.17 (should apply to current master, too)
Platform and Target: Not relevant

I have a somewhat complex form, built using a modelless form.
This form contains a dynamic list of inputs for a previously selected list of insurrance premiums.
Each input can have a custom set of validations configured by a user in the backend of the application.

We want to validate the ``value`` field(s) in the following structure (only partly visible):

![grafik](https://user-images.githubusercontent.com/625761/41289606-a4baf936-6e4a-11e8-9d9b-310db03c620b.png)

There can be multiple ``premiums``, having potentially multiple ``booking_attribute_values`` sets of ``name`` and ``value``.

In the modelless form we build the schema and add the configured validation rules for each field in their dot notation,  e.g  one or more rules for ``premiums.0.booking_attributes_values.0.value``.

![grafik](https://user-images.githubusercontent.com/625761/41289613-aa8fe6dc-6e4a-11e8-93e5-a6895eb36b12.png)

Now, when we use form helper to create the form input field supplying the field names in dot notation, it introspects the list of validation rules for the fields using the dot notation, thus finding the field and its validation rules. This results in a correctly built HTML control, e.g with or without ``"required"`` set.

https://github.com/cakephp/cakephp/blob/3.5.17/src/View/Form/FormContext.php#L121-L135

But when we POST this form, the actual form data validation will not use the configured validation rules as it searches the field names by iterating over the validation rules list, trying to compare the dot notation field names with the data array which contains the data in"short" field names, ``premiums``on the first level of the data structure above.

https://github.com/cakephp/cakephp/blob/3.5.17/src/Validation/Validator.php#L95-L152

``$keyPresent = array_key_exists($name, $data);``

![grafik](https://user-images.githubusercontent.com/625761/41289622-afbaacb4-6e4a-11e8-89cd-5911fb184e34.png)`

I think I can fix the data validation by adding the validation rules as deeply nested ones, but this in turn will not be recognized by the FormHelper then. Alternatively I can add it twice, once in dot notatio and once as deeply nested one.

Nontheless, jI guess this inconsitency should either be fixed or at least documented.

**Comment by ravage84** [comment]
This is probably related: https://github.com/cakephp/cakephp/issues/7532

**Comment by ravage84** [comment]
I can confirm two things about adding the validation rules as deeply nested ones (e.g. ``premiums`` -> ``0`` -> ``booking_attributes_values`` -> ``0`` -> ``value``)

1.  It works for the form data validation
2.  It breaks the HTML form creation (e.g. the ``required`` attribute gets not added)

**Comment by dreamingmind** [comment]
It's not a Core fix, but I've solved this problem by overriding `Form::validate($data)` in my extension of `Form` like this:

```
 /**
     * Validate our flat schema
     *
     * Because we have structure encoded in our schema using
     * dot notation, we have to flatten the post to match,
     * then expand the errors. Errors go to the FormHelper
     * which does not understand the flat version.
     *
     * @param array $data
     * @return bool
     */
    public function validate($data)
    {
        $result = parent::validate(Hash::flatten($data));
        $this->setErrors(Hash::expand($this->getErrors()));
        return $result;
    }
```

**Comment by dereuromark** [comment]
@ravage84 Quite an old ticket
Are you interested in making a PR here, or how shall we continue with this? It doesn't seem it will go anywhere.

**Comment by ravage84** [comment]
@dereuromark Unfortunately, not in the near future. I'm sorry.

By the way, I assume this applies to CakePHP 4.x, too?

**Comment by dereuromark** [comment]
I would even assume that by now this first needs to be addressed in 4.x
And then optionally get a backport.

Same for most issues in the 3.x milestone.
