### ISSUE TITLE
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client Error

### ISSUE THREAD

**Issue by Shabasha** [cakephp/cakephp#12227]
One of the major change that occured in the Last version of MySQL Server 8.x is that it is no longer using the MySQL Native Adapter , and this problem will prevent any PHP Based Web Application in CakePHP , Laravel , Prestashop or any other system from connecting to the database. Then CakePHP must upgrade its core to meet this change. I think so.

the default authentication plugin used by MySQL server is mysql_native_password and in this last mysql release ( 8.x ) its switched to caching_sha2_password. Correspondingly, libmysqlclient will now use caching_sha2_password as the default authentication mechanism, and no longer the first one.

After checking that database already exists in the Server and attempting to fix the Database Connection Issue , this error occur in the default home page 

CakePHP is NOT able to connect to the database.

Database connection "Mysql" is missing, or could not be created.
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

This problem should be fixed by the CakePHP Development Team in order to

**Comment by markstory** [comment]
Until PHP solves this problem we will not be able to solve it either.

**Comment by markstory** [comment]
Closing as this isn't something we can address in CakePHP directly.
