### ISSUE TITLE
Cannot call method select() on array|Cake\Database\Query (phpstan)

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#12225]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6

### What you did

I have a query like this:

```php
$connection->newQuery()->from('users')->select(array('id', 'username'));
```

### What happened
Then I started `phpstan` and I got this error message:

```
Cannot call method select() on array|Cake\Database\Query
```

### What you expected to happen

I would expect, that a method should not return mixed data types. The return value should always be the same, in this case only `\Cake\Database\Query`. Returning an array in some special cases makes no sense to me here.

Edit: The same issue applies to other methods like:

* Cannot call method select() on array|Cake\Database\Query.
* Cannot call method andWhere() on array|Cake\Database\Query.
* Cannot call method newExpr() on array|Cake\Database\Query.
* Cannot call method andWhere() on array|Cake\Database\Query.
* Cannot call method execute() on array|Cake\Database\Query.

**Comment by markstory** [comment]
> Returning an array in some special cases makes no sense to me here.

Ok. But we cannot remove those special cases right now as it will break existing applications. A big part of 4.x is cleaning up these type inconsistencies. Currently `Query::from()` and `Query::join()` have this ambiguous return type. We could deprecate/remove the getter side of those methods as `Query::clause()` allows reading.

**Comment by markstory** [comment]
Closing as the read side of from() and join() will be deprecated in 3.7 and removed in 4.0 (which is the earliest we can make backwards incompatible changes).
