### ISSUE TITLE
Incorrect use of CakeText::uuid() in CakeEmail

### ISSUE THREAD

**Issue by techlands** [cakephp/cakephp#12241]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 2.10.10
* Platform and Target: All

### What happened
lib/Cake/Network/Email/CakeEmail.php
line: 791
CakeText::uuid() used as CakeText::UUID()

### What you expected to happen
should be lowercase to match method name in CakeText

**Comment by dereuromark** [comment]
Can you make a pull request here, please? That would be awesome!

**Comment by markstory** [comment]
Fixed.
