### ISSUE TITLE
EntityTrait::setErrors() removes indexes for addNestedMany validation errors

### ISSUE THREAD

**Issue by tuna-rootnet** [cakephp/cakephp#12249]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.17
* Platform and Target: Ubuntu 16.04, PHP 7.1.17.

### What you did
I created a reusable validator which calls `$validator->addNestedMany()`. This validator is used by a modelless form and an entity who both contain a key which needs to be validated the same way. Hence, the reusable validator. The entity is simply created with `newEntity()` or `patchEntity()`, while the form is validated through `$form->validate($data);`
The data being validated contains 3 records, of which the second has some invalid field which raises a validation error.
```php
$data = [
    ['someKey' => 'a', 'content' => 'x'],
    ['someKey' => 'b'], 'content' => '' // This triggers a validation error for notEmpty()
    ['someKey' => 'c', 'content' => 'z']
];
```

### What happened
The output for the form contains the error on the correct record, `$errors[1]`. The output for the entity contains the error on the very first record, `$errors[0]`. If there are more records which have errors, the form still shows them for the correct index while the entity just starts at zero and continues from there. If there are 5 records and record 2 and 5 trigger errors, the indexes for the entity will be 0 and 1.
``` javascript
// Output for modelless form, in json
{
    "errors": {
        "records": {
            "1": { // Correct index for offending record
                "content": {
                    "_empty": "Waarde mag niet leeg zijn"
                }
            }
        }
    }
}

// Output for entity
{
    "errors": {
        "records": {
            "0": { // <-- Well, there's my problem
                "content": {
                    "_empty": "Waarde mag niet leeg zijn"
                }
            }
        }
    }
}
```
### What you expected to happen
For both outputs to contain the error at the correct index for the records.

I tracked the issue down to `setErrors` in `src/Datasource/EntityTrait:889` (in CakePHP 3.5), which uses `array_merge`, whereby numeric indexes are lost.

**Comment by markstory** [comment]
Closing as there is a pull request open now.

**Comment by muslimrao** [comment]
Any solution for this ? I'm using 3.2.8

**Comment by garas** [comment]
Upgrade CakePHP. Issue was fixed in 3.6.6.

**Comment by muslimrao** [comment]
> Upgrade CakePHP. Issue was fixed in 3.6.6.

Thanks for replying.

I can't update.. Is there any hack ?.. even I can change vendor files if needed.

**Comment by garas** [comment]
Try to apply patch from https://github.com/cakephp/cakephp/pull/12268

**Comment by muslimrao** [comment]
Tried.. The solution link is *not* working..
Also tried array_replace instead of array_merge.. Not working.

**Comment by garas** [comment]
Before 3.4, it was `errors()`, now `setErrors()`, maybe you applied patch incorrectly.

To avoid change vendor files, you can create you own `class AppEntity extends \Cake\ORM\Entity`, overwrite `errors()` method, and make all your entities to use this class.

Sorry, but 3.2 is not supported, I can't help anymore without suggesting to upgrade first.
