### ISSUE TITLE
Router::$_urlFilters empty with route caching enabled

### ISSUE THREAD

**Issue by josbeir** [cakephp/cakephp#12253]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.5

### What you did
Added a Router::addUrlFilter rule, this rule is a callable and is defined in my routes.php file.

### What happened
When route cache is enabled in the RoutingMiddleware and routes are returned from cache the Router::$_urlFilters array is empty so the rule is never executed.

**Comment by markstory** [comment]
You'll have to either move where you define your URL filters or not use route caching :smile:

**Comment by josbeir** [comment]
Fair enough 😏

**Comment by markstory** [comment]
If you put your URL filters in your application's bootstrap it should 'just work' :tm:
