### ISSUE TITLE
Bug using 'contain'

### ISSUE THREAD

**Issue by aritonandrei** [cakephp/cakephp#12258]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.10

### What you did
I've wanted to retrive some data and in my query i have this `'contain' => ['Access' => ['fields' => 'Access.schema']]`. But when it returns, the field `Access.id` is present in the reulse causing tests to fail( the ones with sql_mode=only_full_group_by).

### What you expected to happen
I would expect 'Access.id' to be not retrieved with 
`'contain' => ['Access' => ['fields' => 'Access.schema']]`

**Comment by lorenzo** [comment]
@aritonandrei `contain` needs to add the `id` field so it can match the results with the parent entity. You can use `innerJoinWith`, `leftJoinWith` or use `setAutoFields` to false to get closer to the query you want to build

**Comment by aritonandrei** [comment]
@lorenzo Thanks

**Comment by bancer** [comment]
If 'fields' is set inside 'contain' array I would expect 'autoFields' to be set automatically to `false`.

**Comment by markstory** [comment]
There is no `autoFields` in 2.x. However, the `id` is still required in order to join relational data back together again.

**Comment by lorenzo** [comment]
oh, sorry... I did not realise this was for cake 2 :(

**Comment by markstory** [comment]
Closing as without the additional id field the orm cannot merge data together which would break contain in a more severe way.

**Comment by bancer** [comment]
> There is no autoFields in 2.x.

Actually, there is - https://book.cakephp.org/2.0/en/core-libraries/behaviors/containable.html#containablebehavior-options.

> However, the id is still required in order to join relational data back together again.

Not always. F.ex.:
```
$this->Post->find('all', [
    'fields' => ['Post.date'],
    'group' => ['User.email', 'Post.date'],
    'conditions' => ['Post.date' => '2018-06-19'],
    'contain' => [
        'User' => [
            'fields' => ['User.email'],
       ],
    ],
]);
```
In this scenario it feels like a bug that CakePHP adds 'User.id' to 'fields'. In this case `posts left join users` is generated so the user id from 'fields' is not really used. Of course, this can be "fixed" by using `$this->Post->Behaviors->load('Containable', array('autoFields' => false));` but if the developer sets 'fields' herself the framework should assume that the developer knows what fields to retrieve.

**Comment by lorenzo** [comment]
@bancer I agree with you, unfortunately we cannot change in for cakephp 2 already. That was a problem that was addressed in the cakephp 3 orm
