### ISSUE TITLE
Inflector does not singularize irregular camel cased words correctly

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#12254]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.5

### What you did
I have a Table class `CustomCookiesTable`. 

### What happened
Calling newEntity returns base `Entity` class since `Inflector::singularize('CustomCookies')` returns `CustomCooky`.

### What you expected to happen
I would expect newEntity to create existing `CustomCookie` entity class.

Simple solution is to call `Inflector::classify(Inflector::singularize(Inflector::underscore('CustomCookies')))` in `Table::getEntityClass`, but I think it's an Inflector bug. So please suggest if you prefer this simple solution or `Inflector::singularize` method should be fixed. I can take a look at that.

**Comment by markstory** [comment]
Irregular words are often incorrectly inflected. Do you have the same problem with 'Cookies' as well?

**Comment by segy** [comment]
cookies work and as I mentioned above, if you underscore it first, it also works. so I guess problem is in camel case

**Comment by ADmad** [comment]
`singularize()` and `pluralize()` methods don't take casing into consideration. So `'CustomCookies'` is treated same as `'customcookies'`. So you will have to explicitly specify irregular inflection for `'customcookies' as it's done for `cookies` in core.

**Comment by markstory** [comment]
'customcookies' is not something that fits within the scope of the built-in rules. You can use `Inflector::rules()` to add more rules for your application.

**Comment by segy** [comment]
I can live with the fact, that inflector behaves this way. But I don't see any point in behaving of the Table. Because when i create database table `custom_cookies` and class `CustomCookiesTable`, do you think it's OK that I should add custom inflector rule or set entityClass directly? I'm creating PR for this and will leave it to your consideration wheter you want to merge.

**Comment by dereuromark** [comment]
Yeah, let's discuss it on a concrete PR, that will make it easier to understand the issue.
