### ISSUE TITLE
_basicTypeCast() deprecation warning

### ISSUE THREAD

**Issue by danny3b** [cakephp/cakephp#12257]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.5
* Platform and Target: MAMP 4.4.1, PHP 7.1.12

### What you did
Saved an entity to the database.

### What happened
Entity saved correctly but debug.log is showing below deprecation warning:

Type::_basicTypeCast() is deprecated. - /Applications/MAMP/htdocs/project/vendor/cakephp/cakephp/src/Database/Type.php, line: 273

### What you expected to happen
I would like to have clean debug.log file

**Comment by dereuromark** [comment]
This has been deprecated for a while now.
The message on the doc block states

> `@deprecated 3.1 All types should now be a specific class`

So what you cast and patch here is rather relevant for this issue.
You didnt give much background.

**Comment by danny3b** [comment]
If it's deprecated for a while, what is it doing in vendor/cakephp/cakephp/src/Database/Type.php?

**Comment by dereuromark** [comment]
As just explained you are not supposed to use this part. The description states how not to run into it.
But without more info from your side it is hard to tell you how exactly this can be solved.

**Comment by saeideng** [comment]
I think we can improve deprecation message

**Comment by markstory** [comment]
Pull request open to improve deprecation warning.
