### ISSUE TITLE
Error getOriginalSubject()

### ISSUE THREAD

**Issue by mathritter** [cakephp/cakephp#12278]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.1
* Platform and Target: APACHE, Windows

### What you did
$email->subject( $subject );

### What happened
Error: Call to undefined method Cake\Mailer\Email::getOriginalSubject() 

### What you expected to happen
Send e-mail with set subject

Strange is: I used the same code to test in a Shell I made and it works perfectly, sends e-mail and everything. It's happening in my controller/components classes

**Comment by saeideng** [comment]
update your cake version 
this method added in cake 3.0
https://github.com/cakephp/cakephp/pull/8492

**Comment by saeideng** [comment]
you can not using the `getOriginalSubject` method before adding it to core 
so or update your cakephp version 
or dont use `getOriginalSubject` in cake 3.2.1

**Comment by mathritter** [comment]
But I'm just doing 
$email->subject();
implying $email = new Email( 'default' );

**Comment by saeideng** [comment]
probably one of your plugins tried to use this method 
search `getOriginalSubject` word on your app to see usages 
also `composer show -i` can shows  installed packages

**Comment by saeideng** [comment]
join to Slack to receive help 
All team members are in the Slack
.....................
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
