### ISSUE TITLE
Pagination default order on 3.6.5

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#12275]
I have a very simple paginator and noticed the default order specified on $this->paginate always sticks around and can't be overridden anymore from the url parameters.

I think $this->paginate order was only used if url sort and direction was not set... 

Tested on 2 sites with latest 3.6.5, older 3.5 works fine..

controller:

    $this->paginate = [
        'order' => [
            Names.name' => 'asc'
        ]
    ];

url and Sql Log in DebugKit:

    /names?sort=name&direction=desc

    ORDER BY 
        Names.name asc 

url and Sql Log in DebugKit:

    /names?sort=gender&direction=desc

    ORDER BY 
        Names.gender desc,
        Names.name asc 

Thanks,
Andras

**Comment by markstory** [comment]
This was an intentional change made in 3.6.0 to allow pages beyond page 1 to have multiple sort columns. See #7324, #9791, and #11193 for the discussion on this change.

**Comment by andraskende** [comment]
HI Mark,

Just did some testing here is what I found:

    $this->paginate = [
        'order' => [
            'Visits.created' => 'asc'
        ]
    ];

/visits - correct, sorts by whats defined in $this->paginate
/visits?sort=created&direction=asc -correct
/visits?sort=created&direction=desc - incorrect still orders by 'asc', the url request should come first..


When I remove the Model name from     $this->paginate 'order' everything works great:

    $this->paginate = [
        'order' => [
            'created' => 'asc'
        ]
    ];

Also working:

    $this->paginate = [
        'order' => [
            'Visits.created asc'
        ]
    ];


Thanks,
Andras
