### ISSUE TITLE
Deprecated (16384): Use Cake\Http\Session instead of Cake\Network\Session

### ISSUE THREAD

**Issue by thomaskanzig** [cakephp/cakephp#12281]
Hi guys,

In my debug.log show this error:

2018-06-23 14:26:35 Notice: Deprecated (16384): Use Cake\Http\Session instead of Cake\Network\Session. - /home/carango/public_html/vendor/composer/ClassLoader.php, line: 444

How can I resolve this??

**Comment by saeideng** [comment]
>How can I resolve this??

`composer update`

-----------------------

join to Slack to receive help 

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

**Comment by swiffer** [comment]
Getting this error again in 3.6.12 ?

**Comment by saeideng** [comment]
@swiffer  from cakephp itself , no , you should not see this warning

**Comment by swiffer** [comment]
is it coming from DebugKit ?

![grafik](https://user-images.githubusercontent.com/2990373/46575253-6f17ea00-c9b2-11e8-9013-09d5ebc82d32.png)

**Comment by dereuromark** [comment]
It can also be any usage inside your project code (or /config). Remove all of it, and you will be fine.

**Comment by garas** [comment]
Just find/replace any `Cake\Network\` to `Cake\Http\` (except `Cake\Network\Socket`) within your app (plugins can also use old namespace)

**Comment by swiffer** [comment]
Found it!
