### ISSUE TITLE
Add IP-address support to CakePHP ORM

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#12284]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Task for storing an IP address in a DBMS is pretty frequent. The task is complicated by the fact that you need to take into account both IPv4 and IPv6 addresses.

It would be nice to have a 'standard' way of storing IP-addresses in CakePHP.

I suggest to treat `varbinary(16)` columns (MySQL) prefixed with net_ for storing IPv4/IPv6 addresses in binary form.
Other possible values are:
* `binary(4)` - IPv4 only;
* `binary(16)` - IPv6 only;

Other DMBS may have more suitable types for storing IP addresses.

**Comment by markstory** [comment]
Are you looking for a new `ip4` and `ip6` datatypes in the ORM/database layer?

**Comment by dmromanov** [comment]
I would like to see either a single universal `IpType` which would represent both IPv6 and IPv4. If I don't confuse anything, then IPv6 is backwards-compatible with IPv4 and a generic `IpType` is possible.
But I'm O.K. with having two separate `ipv4` and `ipv6` types.

**Comment by markstory** [comment]
Ok why do you recommend storing ip addresses as binary instead of string values? I can see some advantages in more compact storage but at the cost of requiring encoding to be useful to humans.

**Comment by lorenzo** [comment]
would the type be compatible with the native types for the database? like for postgres https://www.postgresql.org/docs/9.1/static/datatype-net-types.html

**Comment by markstory** [comment]
> However, there is one drawback that can cross out this idea: in SQL logs, IP addresses will be distinguishable, but unreadable: most likely will be represented in a hexadecimal form.

This is the point I was trying to get to. The binary encoding could make ad-hoc queries harder.

> Well, it doesn't make sense to sort IP addresses, and you can only compare them with an exact match.

Agreed, but using a binary column makes it harder to use any string functions like substring() on the values too.

**Comment by dmromanov** [comment]
Sorry for slow answer.

Yes, I agree, working with the text representation of IPv4 is often easier, but considering IPv6 it not always true.
IPv6 has three forms of address representation in text form (see RFC 4291 section-2.2). Work with addresses in text form in IPv6 is very difficult, it even has a special RFC 5952 https://tools.ietf.org/html/rfc5952.
Using binary representation, at least for IPv6 will make things easier.

**Comment by dereuromark** [comment]
This sounds like the perfect use case for a plugin here.
There you can publish a whole collection of these useful types.
But - as you noticed - there is no perfect core solution and most implementations vary per use case.

As such, I think you should go for the plugin approach for now, make sure you add it to https://github.com/FriendsOfCake/awesome-cakephp/ list once you tag releases.

**Comment by lorenzo** [comment]
@sdustinh I so happy there is at least one person using `toExpression()` :D

**Comment by dereuromark** [comment]
Should we close this then as "sufficient as plugin solution"? There seems to be little interest in a core solution right now.
