### ISSUE TITLE
[convention][Foreign Key too long]

### ISSUE THREAD

**Issue by HumanG33k** [cakephp/cakephp#12282]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.5
* Platform and Target: Debian current testing (buster), apache 2.4.33-3+b1, postgresql v10

### What you did
I design my database with cake convention for FK. I currently have several many to many to many to many relations. 

### What happened
 So some FK  have long long long name and it is truncate by pgsql. 

### What you expected to happen
It’s work.
Maybe there is a way to respect length and cakephp conventions ? Or i need to do it without conventions. I think maybe more experiment dev and users should talk about it maybe something about it can be done in V4.

**Comment by markstory** [comment]
You are free to rename the foreign keys on your tables/associations. You will need to use the association options, but after that you shouldn't have any issues.

Out of curiosity what are your table names?

**Comment by HumanG33k** [comment]
Maybe have done something wrong, i'm really tired this days.

zip_codes(__id__, [...]);
towns(__id__, [...], #zip_codes_id);
addresses(__id__, [...], #town_id);
companies(__id__, [...]);
products(__id__, [...]);
roles(__id__, [...])
addresses_companies(__#company_id__, __#address_id__,[...]);
addresses_companies_products(__#addresses_company_company_id__, __#addresses_company_address_id__, __#product_id__, [...]);
addresses_companies_products_roles(__#addresses_companies_product_addresses_company_company_id__, __#addresses_companies_product_addresses_company_address_id__, __#addresses_companies_product_product_id__, __#role_id__, [...]);

I want represent all place used by a company and for each show what is done with a product.
ie :
- Company A product B on C
- Company A sell B on D
- Company A sell E on F
- Company A product E on F

**Comment by markstory** [comment]
> Is bake support other name for FK ?

It should. If you are using `FOREIGN KEY` constraints in your tables bake should read them when generating models. Bake will then use the associations defined in your models when generating views and controllers.

**Comment by markstory** [comment]
Closing as while the conventions can result in long key names in some schemas, you can use the association options to chose shorter names.
