### ISSUE TITLE
Dynamic plugin loading in (Console)IntegrationTestCase

### ISSUE THREAD

**Issue by josbeir** [cakephp/cakephp#12288]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.6

### What you did
Updated plugin loading in Application::bootstrap for plugins that where still using Plugin::load() to $this->addPlugin() (plugins missing Plugin.php)

### What happened
I got some ConsoleIntegrationTestCase(s) for commands and these are all throwing MissingPluginException since the upgrade to 3.6.6 for these types of plugins.

Example stacktrace:
```
1) App\Test\TestCase\Command\IndexCommandTest::testHelp
Cake\Core\Exception\MissingPluginException: Plugin Migrations could not be found.

xx/vendor/cakephp/cakephp/src/Core/PluginCollection.php:125
xx/vendor/cakephp/cakephp/src/Http/BaseApplication.php:137
xx/vendor/cakephp/cakephp/src/Http/BaseApplication.php:97/src/Application.php:201
xx/src/Application.php:49
xx/vendor/cakephp/cakephp/src/Console/CommandRunner.php:191
xx/vendor/cakephp/cakephp/src/Console/CommandRunner.php:136
xx/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestCase.php:95
xx/tests/TestCase/Command/IndexCommandTest.php:36
```

A part of my command testcase:

```php
namespace App\Test\TestCase\Command;

use Cake\Console\Command;
use Cake\ElasticSearch\Index;
use Cake\TestSuite\ConsoleIntegrationTestCase;

class IndexCommandTest extends ConsoleIntegrationTestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->setAppNamespace('App');
        $this->useCommandRunner();
    }

    public function testHelp()
    {
        $this->exec('index --help');
        $this->assertOutputContains('index [-h] [-i Products] [-q] [-v] [-y] <create|delete|reindex>');
        $this->assertExitCode(Command::CODE_SUCCESS);
    }
...
```

I dont have many controller integrations at the moment but i believe the same issue is also happening over there. 

The problem is that ```Configure::read('plugins')``` returns null, after a quick check but i can't seem to trace down where this is reset because ```PluginCollection::loadConfig()``` is executed correctly and populates the configure array.

**Comment by markstory** [comment]
I'll take a look.

**Comment by josbeir** [comment]
Ok, found the the issue: Its related to TestCase::tearDown that calls Configure::clear()

As Plugin::getCollection() returns a static instance of PluginCollection that uses Configure::read('plugins') to check loaded plugins. As this value is unset and never rebuilt.

**Comment by markstory** [comment]
Thank you for digging up why this is happening. I think I have a solution now.

**Comment by markstory** [comment]
Closing as there is a pull request now.

**Comment by josbeir** [comment]
you forgot to close :-)
