### ISSUE TITLE
paginate default order direction 3.6.5

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#12280]
$this->paginate = [
        'order' => [
            'Visits.created' => 'asc'
        ]
    ];

/visits - correct, sorts by whats defined in $this->paginate
/visits?sort=created&direction=asc -correct

/visits?sort=created&direction=desc - incorrect, orders by 'asc', the url request should be priority over the default.

When I remove the Model name, or specify without array everything works great:

    $this->paginate = [
        'order' => [
            'created' => 'asc'
        ]
    ];

    $this->paginate = [
        'order' => [
            'Visits.created asc'
        ]
    ];

Thanks,
Andras

**Comment by markstory** [comment]
The url parameter is `created` but your pagination key is `Visits.created`. Because those are not the same Paginator treats them as separate sort fields.
