### ISSUE TITLE
CakePHP Project does not connect to another database server

### ISSUE THREAD

**Issue by sharnaaysha** [cakephp/cakephp#12299]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

CakePHP Version: 3.6
 I make a simple registration website by CakePHP. I upload the CakePHP project in server. My database is in another server. In database there is user information for registration and login. But now when I login in the website , it does not connect to the database server. 
I change the /app/config/my.cnf 
```
'Datasources' => [
        'default' => [
![cakephp_database_error](https://user-images.githubusercontent.com/40449982/41965564-ce9a506e-7a37-11e8-9bc3-160e9242da93.PNG)

            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => ' ', [ here I put database server ip address ]
            /*
             * CakePHP will use the default DB port based on the driver selected
             * MySQL on MAMP uses port 8889, MAMP users will want to uncomment
             * the following line and set the port accordingly
             */
            'port' => ' ', [here I put database server port]
            'username' => '', [here I put database server user name]
            'password' => '', [[here I put database server user name's password]
            'database' => ' ', [here I give my database name]
```

But now I can not log in because the project do not get database connection.
I expected to login .

**Comment by dakota** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
