### ISSUE TITLE
Subdirectory is added again when using $routes->redirect

### ISSUE THREAD

**Issue by Bird87ZA** [cakephp/cakephp#12295]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.5
* Platform and Target: AWS Hosted server (Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-129-generic x86_64)) PostgreSQL DB. Website is hosted under `www.example.com`, CakePHP runs from `www.example.com/webapp`

### What you did
I created a shortlink for a specific route in my `routes.php` file like so:

    $routes->redirect(
        '/g/:id',
        ['controller' => 'Jobs', 'action' => 'view'],
        ['pass' => ['id'], 'persist' => true]
    );

### What happened
I am being redirected to `www.example.com/webapp/webapp/jobs/view/5`

### What you expected to happen
I expect it to redirect me to `www.example.com/webapp/jobs/view/5`

### More info
I did quite a few debugging and it seems that the bug slips in around the `Router::reverse()` function. You can see my original discussion around the issue with @ndm2 [here](https://stackoverflow.com/questions/51035419/routes-redirect-adds-base-to-address).

**Comment by markstory** [comment]
Pull request open now.
