### ISSUE TITLE
CSRF expiry option

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#12294]
* [x] bug

* CakePHP Version: 3.6.6
* Platform and Target: nginx, mariadb

### What you did
```
// src/Application.php where the middleware is added
// Add csrf middleware.
->add(new CsrfProtectionMiddleware([
    'expiry' => 3600
]))
```

### What happened
No CSFR cookie set, Missing CSRF token cookie exception raised

### What you expected to happen
csrfToken cookie set with browser with timeout 3600

**Comment by markstory** [comment]
Your `expiry` key needs to be a value that is compatible with `strtotime()` and `new Time()`, which `3600` is not. Instead you can use `+1 hour`.

**Comment by LubosRemplik** [comment]
Thanks, makes sense - sorry about invalid issue
