### ISSUE TITLE
Unexpected behavior for i18nFormat with some timezones

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#12304]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:  3.5.17 & 3.6.6
* Platform and Target: Apache/2.4.27, MySQL 5.6.37, PHP 7.1.8

### What you did
Default time zone is UTC. When changing the displayed timezones format some works and others not so please check the following example
```php
// Working timezones
pr(\Cake\I18n\Time::instance($page->modified)->i18nFormat(null, "America/Adak", null));
pr(\Cake\I18n\Time::instance($page->modified)->i18nFormat(null, "America/El_Salvador", null));
pr(\Cake\I18n\Time::instance($page->modified)->i18nFormat(null, "Africa/Nouakchott", null));

// Not working timezones
pr(\Cake\I18n\Time::instance($page->modified)->i18nFormat(null, "America/Fort_Nelson", null));
pr(\Cake\I18n\Time::instance($page->modified)->i18nFormat(null, "Asia/Yangon", null));
```
output of `var_dump($page->modified)`
```
object(Cake\I18n\FrozenTime)[56]
  public 'time' => string '2016-07-01T20:14:16+00:00' (length=25)
  public 'timezone' => string 'UTC' (length=3)
  public 'fixedNowTime' => boolean false
```

### What happened
Timezone like `America/Fort_Nelson`, `Asia/Yangon` releasing the following error message
```
2018-06-28 13:25:44 Error: [Error] Call to a member function format() on null
Request URL: /pages/privacy
Stack Trace:
#0 /vendor/cakephp/cakephp/src/I18n/DateFormatTrait.php(177): Cake\I18n\Time->_formatObject(Object(Cake\I18n\Time), Array, NULL)
#1 /src/Template/Pages/view.ctp(20): Cake\I18n\Time->i18nFormat(Array, 'America/Fort_Ne...', NULL)
#2 /vendor/cakephp/cakephp/src/View/View.php(1203): include('/usr/local/ampp...')
#3 /vendor/cakephp/cakephp/src/View/View.php(1164): Cake\View\View->_evaluate('/usr/local/ampp...', Array)
#4 /vendor/cakephp/cakephp/src/View/View.php(772): Cake\View\View->_render('/usr/local/ampp...')
#5 /vendor/cakephp/cakephp/src/Controller/Controller.php(623): Cake\View\View->render(NULL, NULL)
#6 /vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(125): Cake\Controller\Controller->render()
#7 /vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#8 /vendor/cakephp/cakephp/src/Http/BaseApplication.php(109): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /vendor/admad/cakephp-social-auth/src/Middleware/SocialAuthMiddleware.php(150): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /vendor/cakephp/cakephp/src/Http/Runner.php(65): ADmad\SocialAuth\Middleware\SocialAuthMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 /vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 /vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /webroot/index.php(40): Cake\Http\Server->run()
#23 {main}
```

### What you expected to happen
I expect to get the correct timezone format for all timezones

Many Thanks

**Comment by markstory** [comment]
We don't provide/control any timezone information. Do those timezones work with PHP standard library?

**Comment by BassemN** [comment]
I did the following
```php
$date = new \DateTime('2016-07-01T20:14:16+00:00', new \DateTimeZone('UTC'));
echo $date->format('Y-m-d H:i:sP') . "\n";        //2016-07-01 20:14:16+00:00
$date->setTimezone(new DateTimeZone('Asia/Yangon'));
echo $date->format('Y-m-d H:i:sP') . "\n";        //2016-07-02 02:44:16+06:30

$date2 = new \DateTime('2016-07-01T20:14:16+00:00', new \DateTimeZone('UTC'));
echo $date2->format('Y-m-d H:i:sP') . "\n";        //2016-07-01 20:14:16+00:00
$date2->setTimezone(new DateTimeZone('America/Fort_Nelson'));
echo $date2->format('Y-m-d H:i:sP') . "\n";        //2016-07-01 13:14:16-07:00
```
so I think `America/Fort_Nelson`,`Asia/Yangon`  timezones are wokring well with the PHP standard library.

**Comment by markstory** [comment]
I'm not able to reproduce the issue you're having. Both of those timezones do not emit errors for me in PHP 7.2.5 on macos.

**Comment by BassemN** [comment]
I tested it the following shared hosts and I'm getting the sameerror message with some timezones like  `America/Fort_Nelson`, `Asia/Yangon`

- HawkHost 5.6.36, 7.1.19 & 7.2.7
- NameCheap bussiness hosting 5.6
- OVH.NET PHP 5.6.36

I'll try to install LAMP via vagrant and will feed you back.

**Comment by BassemN** [comment]
I installed new LAMP(Ubuntu 16.04, PHP 7.1.18, Apache 2.4.33, MySQL 5.7.22) instance via vagrant with a new CakePHP App and I'm getting the same error.

**Comment by ndm2** [comment]
Try upgrading the ICU library, sounds like the timezones do not exist (or aren't available for date format creation for whatever other reason) in the ICU library that your PHP installation is using, causing `datefmt_create()` to return `null`.

Note that PHP support and ICU support are two different things. While PHP may list the timzone as available/supported, that doesn't mean that the ICU libary does.

**Comment by BassemN** [comment]
@ndm2 On my local LAMP ICU version is `55.1` and on my hosting is `57.1` and both have the same error.

**Comment by BassemN** [comment]
@ndm2 With the standard PHP library, I don't face any issues as you can see here https://github.com/cakephp/cakephp/issues/12304#issuecomment-401110833

**Comment by ndm2** [comment]
Your vanilla PHP code snippets aren't doing what your CakePHP snippets do. Your vanilla PHP creates formatters with the default timezone identifier (`date_default_timezone_get()`, which can cause wrong results btw, as your `Asia/Yangon` date will be converted into the default timezone when it's being formatted, add the time to your pattern and you'll see it), while your CakePHP snippets will create the formatter with the timezones passed in the `i18nFormat()` arguments. Your vanilla PHP also sets the pattern manually, however that's not what cloaks the problem.

Add the timezone as the fourth argument in the `IntlDateFormatter` constructor, and do not set a pattern, then it is comparable to what CakePHP does:

```php
$date = new \DateTime('2016-07-01 20:14:16', new \DateTimeZone('UTC'));
$date->setTimezone(new \DateTimeZone('Asia/Yangon'));

$formatter = new \IntlDateFormatter(
    'de_DE',
    \IntlDateFormatter::SHORT,
    \IntlDateFormatter::SHORT,
    'Asia/Yangon'
);
$formatter->format($date);
```

**Comment by BassemN** [comment]
After using your vanilla PHP code, I got `Constructor failed` error so I think that the issue is related to ICU. Now I'm trying to add a fallback to the error geberated from CakePHP but the problem is that I can't catch this error because it doen't fired a throw exception.

**Comment by lorenzo** [comment]
I think we should check in candle for the null return value in that function and throw a nice exception. @BassemN would you like to do that ?

**Comment by BassemN** [comment]
@lorenzo Honestly, I'm not on that level yet to edit the CakePHP core files :(

**Comment by markstory** [comment]
Pull request open for a new and hopefully more helpful error message.
