### ISSUE TITLE
PDOException in Cakephp 3.5.12 and SQL Server 2014

### ISSUE THREAD

**Issue by rcarvs** [cakephp/cakephp#12317]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.12
* Platform and Target: a container of docker with Debian, Apache2 and PHP 7... and another with  SQL Server 2014

### What you did
I want to create or update a data in my database sql server 2014

### What happened
The data is changed and created in the database, however at the end of each transaction, a database exception with the following message is returned: Error: SQLSTATE [HY010]: [unixODBC] [Driver Manager] Function sequence error

This occurs with every insertion or update that I try to make in the system, regardless of the attributes of the model.

To get around this, I'm doing a redirect to the same view after each transaction. In some cases I also decided to create a catch in the local scope for the PDOException

**Comment by lorenzo** [comment]
The SQLServer driver only works in windows, as it requires the pdo_sqlsrv extension

**Comment by MCF** [comment]
The PHP PDO drivers for Sql Server are available for Linux:
https://github.com/Microsoft/msphpsql#install-unix
https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017
