### ISSUE TITLE
Subcommand help shows help of current task/shell

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#12325]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.6

---

When requesting help for subcommands that aren't separate tasks, the help for the current task/shell is being displayed, which can be rather confusing, especially since the usage lines will show a syntax that doesn't exist.

For example `$ bin/cake bake all --help` will output the following (shortened):

```
The Bake script generates controllers, models and template files for
your application. [...]

Usage:
cake bake all [subcommand] [options]

Subcommands:

all                 Bake a complete MVC skeleton.
behavior            Bake a behavior class file.
cell                Bake a cell class file.
component           Bake a component class file.
controller          Bake a controller skeleton.
[...]

To see help on a subcommand use `cake bake all [subcommand] --help`

Options:

--connection, -c   The datasource connection to get data from.
                   (default: default)
--everything       Bake a complete MVC skeleton, using all the available
                   tables. Usage: "bake all --everything"
[...]
```

Except for the usage lines, which shows the aforementioned non-existent syntax (there is no subcommand for the `all` subcommand), that is the same output that `$ bin/cake bake --help` generates.

**Comment by markstory** [comment]
What should be displayed given that the `all` command doesn't have explicit help or options defined?

**Comment by ndm2** [comment]
I'm not quite sure, and I don't know what exactly you mean by "explicit" help, but it has the `Bake a complete MVC skeleton` message defined as help, so maybe it should either display the same as if it had an (empty) options parser attached, ie like this:

```
Bake a complete MVC skeleton.

Usage:
cake bake all [-h] [-q] [-v]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
```

which would then require to attach common options to such commands, or they could be automatically inherited (unless a custom options parser is defined), or that the "parents" help should be displayed, but also with the parents usage syntax, ie `cake bake [subcommand] [options]` instead of `cake bake all [subcommand] [options]`, and people would need to explicitly attach an options parser to the subcommand, even if it's just an empty parser.

I'm not really sure what might be the best solution here.

**Comment by ndm2** [comment]
Scratch that, given that non-task subcommands do actually inherit the options of the parent, I think it should display the subcommands help, the subcommands usage, and the inherited options, so in the case of the `cake bake all --help` example, that would be something like this:

```
Bake a complete MVC skeleton.

Usage:
cake bake all [options]

Options:

--connection, -c   The datasource connection to get data from.
                   (default: default)
--everything       Bake a complete MVC skeleton, using all the available
                   tables. Usage: "bake all --everything"
--force, -f        Force overwriting existing files without prompting.
--help, -h         Display this help.
[...]
```

which would basically be the same as if it had a dedicated options parser attached.

**Comment by markstory** [comment]
ok. That sounds like a reasonable change to me.
