### ISSUE TITLE
The Query::bind() method doesn't work properly in some situations

### ISSUE THREAD

**Issue by yakubenko** [cakephp/cakephp#12326]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.6
* Platform and Target: PHP 7.2, Apache 2.4, PostgreSQL 10, PostGIS 2.4

### What you did
I want to create a custom finder method for one of my tables. The finder method expects several options and if they are presented it builds a conditions array which I pass to the where() method. The key thing is that one of the conditions is a PostGIS expression with params such as lat/log, radius, etc., thus I can not just add another key/value item to the conditions array. I know that I can use the where() method multiple times and decided to do it like this.

```
public function findActive(Query $query, array $options)
{
        $place = ($options['place']) ?? null;
        $radius = ($options['radius']) ?? null;
        $categoryID = ($options['categoryID']) ?? null;
        $timeZone = ($options['timezone']) ?? 'UTC';
        $time = new Time('now');

        $conditions = [
            'active_until >' => $time->toAtomString()
        ];

        if (!empty($categoryID)) {
            $conditions['category_id'] = $categoryID;
        }

        $query->where($conditions);

        if (!empty($place)) {
            if ($place instanceof Place) {
                if (!empty($radius)) {
                    $query->where([
                        'ST_DWithin(Orders.geom, ST_GeomFromText(\'POINT(:latitude :longitude)\', :epsg), :radius)'
                    ]);
                    $query->bind(':latitude', $place->lat, 'float');
                    $query->bind(':longitude', $place->lng, 'float');
                    $query->bind(':epsg', Configure::read('epsg'), 'integer');
                    $query->bind(':radius', $radius, 'float');
                } else {
                    $conditions['place_id'] = $place->id;
                }
            } else {
                $conditions['place_id'] = $place;
            }
        }

        return $query;
}
```

### What happened
If I use this code
 ```
$query->where(['ST_DWithin(Orders.geom, ST_GeomFromText(\'POINT(:latitude :longitude)\', :epsg), :radius)']);

$query->bind(':latitude', $place->lat, 'float');
$query->bind(':longitude', $place->lng, 'float');
$query->bind(':epsg', Configure::read('epsg'), 'integer');
$query->bind(':radius', $radius, 'float');

```
I get this error
`Error: SQLSTATE[HY093]: Invalid parameter number: :latitude`

If I change my PostGIS expression to anything else with placeholders and bind values, everything seems to work as expected. 

### What you expected to happen
According to the documentation [Binding values](https://book.cakephp.org/3.0/en/orm/query-builder.html#binding-values) I expected to get my values correctly bound to the conditions, I described in the where() method. Unfortunately, I couldn't find how to get this working.

**Comment by lorenzo** [comment]
Does it work with the other params not `:latitude` and `:longitude`? I wonder if it is because you have those parameters enclosed inside a string in the query

**Comment by lorenzo** [comment]
@yakubenko my question was not about their names, but where you put them inside the query. Does it work for the other arguments if you hardcode the latitude and longitude?

**Comment by yakubenko** [comment]
@lorenzo This variant works as expected.

```
public function findNearest(Query $query, array $options)
    {
        $place = $options['place'];
        $radius = $options['radius'];

        $query->where([
            'ST_DWithin(Orders.geom, ST_GeomFromText(\'POINT(' . $place->lat . ' ' . $place->lng . ')\', :epsg), :radius)'
        ]);

        $query->bind(':epsg', Configure::read('epsg'), 'integer');
        $query->bind(':radius', $radius, 'float');

        return $query;
    } 
```

**Comment by lorenzo** [comment]
@yakubenko Then I think this is not a problem with CakePHP, but just how the database works. I suspect the reason is that you have placeholders inside single quotes, which naturally the database would not see as actual placeholder but just text.

Is there another function you can use that does not involve converting a text to a point?

**Comment by yakubenko** [comment]
@lorenzo Thank you for your fast replies. Yes, looking at the code again I understand why this happens. The ticket can be closed.

**Comment by lorenzo** [comment]
I'm glad I could be of help :)
