### ISSUE TITLE
i18n functions __() throws exceptions

### ISSUE THREAD

**Issue by pbfman** [cakephp/cakephp#12346]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7
* Platform and Target: PHP7

### What you did
Upgraded from CakePhp 3.4 to 3.6.

Function ``__('singular')`` and the other similiar translation functions (https://github.com/cakephp/cakephp/blob/master/src/I18n/functions.php) are throwing now ``\Aura\Intl\Exceptions``. I think they did already in previous versions but the phpdoc was not up to date.
Now my IDE is reminding me at each usage that I need to handle the exceptions from ``__('singular')``. 

### What you expected to happen
While this reminding is indeed a problem related to my IDE, I think the exception handling should be done somewhere in ``i18n\I18n.php`` ``getTranslator()`` (https://github.com/cakephp/cakephp/blob/master/src/I18n/I18n.php#L201). Because it wouldn't be a solution to surround each call to ``__('singular')`` with a ``try/catch`` neither to do really this exception handling in my application.

**Comment by lorenzo** [comment]
Well, the exceptions are necessary if you have a configuration problem or are passing incorrect arguments to the translation function. How else could we communicate those errors?

**Comment by chinpei215** [comment]
Personally I think it would be nice if we had different tags for checked/unchecked exceptions.  For example `@throws InvalidArgumentException` doesn't help any users. No one would write try/catch for those exceptions and those would be ignored always. This issue seemds similar to that.

**Comment by lorenzo** [comment]
I think it makes sense to remove the `@throws` annotation from the `__()` family of functions

**Comment by dereuromark** [comment]
I think I said it before:
throws annotations should only be added with sniffers to avoid them getting wrong/outdated, especially deeper into OOP nesting.
As such this can only be properly enforced on primary level - and there are existing sniffers for this, see the Spryker one that does a good job here.
So yeah, those can be removed IMO.

As for the semantic value of them, thats another topic of course. Especially catchable (useful) vs non-catchable (non-useful) ones.

**Comment by pbfman** [comment]
I agree that exception throwing is necessary to communicate errors. But I think especially the ``__()`` family of functions should not throw exceptions as they are typically used in templates and nobody wants an exception handling there (here also the discussion about checked and unchecked exceptions kicks in). Configuration errors should be handled earlier in ``i18n`` class itself. Unfortunately, I got no time to dig deeper into the structure to evaluate a better solution.

I think first solution could be to remove again the ``@throws`` from the ``__()`` functions.
