### ISSUE TITLE
Avoid duplicate form submit

### ISSUE THREAD

**Issue by rogerpro** [cakephp/cakephp#12347]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Platform and Target: App with SecurityComponent & CsrfComponent

Forms in web sites are sometimes submitted twice because of an end user mistake (caused sometimes by a lack of response due to slow connection and the impatience of the user).

In an app using SecurityComponent & CsrfComponent, this case triggers a blackhole error, annoying the user.

One way to avoid this is to disable the submit form (or the whole form) with JS just after it is clicked, so the user cannot resubmit the same form data. This can be done easily form by form, but in cases that, by design, it is a decision that all forms need this feature, it would be easier to just set a global param. This would also assure that all forms created in the future will conform to this configuration.

Additionally, `FormHelper` could allow an `$options` param to override a specific form config, i.e. to keep the submit button enabled after submit.

**Comment by dereuromark** [comment]
I agree that the default is not nice. That's why I usually don't use it much. Usability is killed completely.
Adding JS though would need to be opt-in and easily replacable based on the userland JS solution in place.
We must also make sure added JS is following https://github.com/cakephp/cakephp/issues/7511

**Comment by ADmad** [comment]
> In an app using SecurityComponent & CsrfComponent, this case triggers a blackhole error, annoying the user.

I don't think this is the case anymore in 3.x. 2.x used "single use" tokens by default for CSRF protection which did cause black holes on double submit but in 3.x the `CsrfComponent` uses same token across all requests.

**Comment by dereuromark** [comment]
@ADmad It still creates weird responses at it will show the form again with a validation error (unique etc) despite it being saved and stuff.

But still, this could be solved using plugin and app code, e.g. snippets like
```js
// jQuery plugin to prevent multi submission of forms
jQuery.fn.preventMultiSubmission = function() {
	$(this).on('submit',function(e){
		var $form = $(this);

		if ($form.data('submitted') === true) {
			// Previously submitted - don't submit again
			e.preventDefault();
		} else {
			// Mark it so that the next submit can be ignored
			$form.data('submitted', true);
		}
	});

	// Keep chainability
	return this;
};

// Add js-allow-multi-submission class to AJAX forms
$('form:not(.js-allow-multi-submission)').preventMultiSubmission();
```

**Comment by rogerpro** [comment]
That's true, @ADmad: this happens in a CakePHP 2 app (I did not report that).

I just tried in a CakePHP 3 app and it looks better: it takes data _but_ shows a `"The project could not be saved. Please, try again."` because data contained a unique key. So, I suppose that when sending data not constrained by a unique key, it would be duplicated in the DB.

**Comment by ADmad** [comment]
@dereuromark I am not saving that double submits are not a problem, just the fact that they don't cause the request to be blackholed anymore as claimed.

**Comment by dereuromark** [comment]
@rogerpro How about starting a "Usability" plugin with such enhancements?
With good docs and sane defaults in place?

Then we could close this here - as core cannot be adjusted here that easily to please all use cases.

**Comment by ADmad** [comment]
I don't think anything needs to be done in core for this. As @dereuromark suggested one can make a plugin for it.

**Comment by rogerpro** [comment]
@dereuromark I would be happy to do that -- need to check my agenda anyhow.

Of course I thought about it as an opt-in as a config param (which would fatten up the core a little bit, yes). If the goal is to keep a light core, it makes more sense to put it in a plugin, I agree.

**Comment by dereuromark** [comment]
The problem is that some use vanilla PHP, others jquery, and so on. Some inject on top, others at the bottom, or inline. And some need the above Content Security Policy.
So core can't be adjusted in a reasonable way here. 

Cool, looking forward to your plugin. Closing then.

**Comment by rogerpro** [comment]
Maybe a quick workaround would be add an `onsubmit` in a form template.
