### ISSUE TITLE
Collection reduce

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#12341]
This is a:

* [x] bug

* CakePHP Version: 3.6.6

### What you did

Tried to use `reduce` function for ResultSet collection to get total (before I found out there is `sumOf`)
```
         $selectedUpgradesTotal = 0;
         if ($selectedUpgrades) {
             $query = $this->OfferUpgrades->find()
                 ->select(['price'])
                 ->where(function($exp) use ($selectedUpgrades) {
                     return $exp
                         ->in('id', $selectedUpgrades);
                 });
             $resultSet = $query->all();
              $selectedUpgradesTotal = $resultSet->reduce(function ($total, $upgrade) {
                dd($total);
                return $total + $upgrade->price;
           });
           dd($selectedUpgradesTotal);
       }
```

### What happened

I can't get into the first `dd`

### What you expected to happen

Getting total, debug variable in the reduce function

**Comment by markstory** [comment]
Was your total not generated as well?

**Comment by LubosRemplik** [comment]
It was not

**Comment by markstory** [comment]
Are you sure the the if statement condition passed? It is unlike PHP to not call a method.

**Comment by markstory** [comment]
Closing as I'm not able to reproduce this issue. When I call reduce() it does its work and the anonymous function is called.

**Comment by LubosRemplik** [comment]
Sorry and thanks. Will try to write use case if I am able to replicate again.
