### ISSUE TITLE
[FormHelper] An error with a multiple value passed by GET method

### ISSUE THREAD

**Issue by w-mazed** [cakephp/cakephp#12342]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.
* Platform and Target: Localhost, wampserver.

### What you did
```php
<?php print $this->Form->create(null, ['type' => 'get, 'valueSources' => ['query']]);
foreach ($queryParams as $key) {
    print $this->Form->hidden($key);
} ?>
```

### Warning !!
Notice (8): Array to string conversion [CORE\src\View\Helper\FormHelper.php, line 1757]

The FromHelper can't insert a multiple value in a hidden field when the values are passed by the GET method,

Thanks.

**Comment by markstory** [comment]
What are you expecting to happen in this case?

**Comment by w-mazed** [comment]
It should generate a set of hidden fields with a attribute NAME an indexed array with the name of field, example:
`<input type="hidden" name="fieldName[0]" value="my value">`
So we can pass the previous value again,

Best regards.

**Comment by ADmad** [comment]
IMO it's the developers responsibility to pass proper field name to `FormHelper::hidden()` call. So if a query param can be array then you should do required checks and call the method like
```php
$this->Form->hidden($key . '.' . $index);
```
to generate input names like `fieldName[0]`, `fieldName[1]` etc.

**Comment by w-mazed** [comment]
Can you give me an example @markstory because I didn't understand what you would say to me :)

**Comment by markstory** [comment]
Closing as converting an array of data into multiple hidden/text inputs is up to the application developer. Any automatic serialization the framework could try to apply will likely cause more problems than it would solve.
