### ISSUE TITLE
Can't install phpunit in cakephp 3.6.7 anymore

### ISSUE THREAD

**Issue by gringlas** [cakephp/cakephp#12340]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7
* Platform and Target: MacOs 10.13.5 with composer 1.6.5 and php 7.1.8

### What you did
I wanted to install phpunit on a fresh cakephp (3.6.7) installation using the `composer require --dev phpunit/phpunit:"^5.7|^6.0"`(like explained in https://book.cakephp.org/3.0/en/development/testing.html) 

### What happened
I recieve a composer error: 

>  Problem 1
    - phpunit/phpunit 6.3.0 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.3.1 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.4.0 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.4.1 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.4.2 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.4.3 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.4.4 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.0 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.1 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.2 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.3 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.4 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.5 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.6 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.7 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.8 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 6.5.9 requires sebastian/diff ^2.0 -> satisfiable by sebastian/diff[2.0.1].
    - Conclusion: don't install sebastian/diff 2.0.1
    - phpunit/phpunit 5.7.20 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.21 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.22 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.23 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.24 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.25 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.26 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 5.7.27 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - phpunit/phpunit 6.1.4 requires sebastian/diff ^1.4.3 || ^2.0 -> satisfiable by sebastian/diff[1.4.3, 2.0.1].
    - phpunit/phpunit 6.2.0 requires sebastian/diff ^1.4.3 || ^2.0 -> satisfiable by sebastian/diff[1.4.3, 2.0.1].
    - phpunit/phpunit 6.2.1 requires sebastian/diff ^1.4.3 || ^2.0 -> satisfiable by sebastian/diff[1.4.3, 2.0.1].
    - phpunit/phpunit 6.2.2 requires sebastian/diff ^1.4.3 || ^2.0 -> satisfiable by sebastian/diff[1.4.3, 2.0.1].
    - phpunit/phpunit 6.2.3 requires sebastian/diff ^1.4.3 || ^2.0 -> satisfiable by sebastian/diff[1.4.3, 2.0.1].
    - phpunit/phpunit 6.2.4 requires sebastian/diff ^1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - Conclusion: don't install sebastian/diff 1.4.3
    - Conclusion: don't install phpunit/phpunit 6.1.3
    - Conclusion: don't install phpunit/phpunit 6.1.2
    - Conclusion: don't install phpunit/phpunit 6.1.1
    - Conclusion: don't install phpunit/phpunit 6.1.0
    - Conclusion: don't install phpunit/phpunit 6.0.13
    - Conclusion: don't install phpunit/phpunit 6.0.12
    - Conclusion: don't install phpunit/phpunit 6.0.11
    - Conclusion: don't install phpunit/phpunit 6.0.10
    - Conclusion: don't install phpunit/phpunit 6.0.9
    - Conclusion: don't install phpunit/phpunit 6.0.8
    - phpunit/phpunit 5.7.10 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.11 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.12 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.13 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.14 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.15 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.16 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.17 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.18 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 5.7.19 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.0 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.1 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.2 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.3 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.4 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.5 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.6 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - phpunit/phpunit 6.0.7 requires sebastian/comparator ^1.2.4 -> satisfiable by sebastian/comparator[1.2.4].
    - Conclusion: don't install sebastian/comparator 1.2.4
    - Conclusion: don't install phpunit/phpunit 5.7.9
    - Conclusion: don't install phpunit/phpunit 5.7.8
    - Conclusion: don't install phpunit/phpunit 5.7.7
    - Conclusion: don't install phpunit/phpunit 5.7.6
    - Conclusion: don't install phpunit/phpunit 5.7.5
    - Conclusion: don't install phpunit/phpunit 5.7.4
    - Conclusion: don't install phpunit/phpunit 5.7.3
    - Conclusion: don't install phpunit/phpunit 5.7.2
    - Conclusion: don't install phpunit/phpunit 5.7.1
    - Conclusion: remove sebastian/diff 3.0.1
    - Installation request for phpunit/phpunit ^5.7|^6.0 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.3.0, 6.3.1, 6.4.0, 6.4.1, 6.4.2, 6.4.3, 6.4.4, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.6, 6.5.7, 6.5.8, 6.5.9].
    - Conclusion: don't install sebastian/diff 3.0.1
    - phpunit/phpunit 5.7.0 requires sebastian/diff ~1.2 -> satisfiable by sebastian/diff[1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Can only install one of: sebastian/diff[1.4.0, 3.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 3.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 3.0.1].
    - Can only install one of: sebastian/diff[1.2.0, 3.0.1].
    - Can only install one of: sebastian/diff[1.3.0, 3.0.1].
    - Installation request for sebastian/diff (locked at 3.0.1) -> satisfiable by sebastian/diff[3.0.1].

I think something is broken in phpunit/phpunit. I then tried to simply install latest phpunit version with `composer require --dev phpunit/phpunit`, which installs phpunit 7.2 but then I recieve `Fatal error: Class 'PHPUnit\Framework\BaseTestListener' not found in /Users/sebastiankoller/Sites/kobschen/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php on line 28` 

### What you expected to happen
I expected to get a working copy of phpunit. On last thursday (2018/7/5) I didn't had any problems installing a new cakephp project with phpunit.

**Comment by garas** [comment]
sebastian/diff is already installed (locked at 3.0.1) by some other package

Try to run with `--update-with-dependencies`

**Comment by markstory** [comment]
Try clearing your lock file. I'm not able to reproduce this problem locally.

**Comment by gringlas** [comment]
I think the conflict comes from dereuromark/cakephp-ide-helper. When I install it before phpunit I recieve the conflict. The other way around it works.

**Comment by ishan-biztech** [comment]
@gringlas is right, it conflicts with `dereuromark/cakephp-ide-helper`. A work around is that,

1. First remove `dereuromark/cakephp-ide-helper`:
```bash
$ composer remove --dev dereuromark/cakephp-ide-helper
```
2. Then require phpunit:
```bash
$ composer require --dev "phpunit/phpunit:^5.7.14|^6.0"
```
3. Install cakephp-ide-helper again:
```bash
$ composer require --dev "dereuromark/cakephp-ide-helper:0.14.*"
```
