### ISSUE TITLE
Add public function EagerLoader::unsetMatching

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#12352]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

public function EagerLoader::unsetMatching($assoc) is needed to allow single 'matching' removing from Query object.
Currenlty I cant find any way to unset matching, because EagerLoader::_matching prop is protected.

**Comment by lorenzo** [comment]
Would you like to add it and send us a pull request?

**Comment by andruhapx** [comment]
@lorenzo , unfortunately no. I can work with SVN only, dont know yet how develop new features for Cake 3, and how to test it with unit tests

**Comment by lorenzo** [comment]
May I ask what’s the use case for removing all matching associations?
