### ISSUE TITLE
[HtmlHelper] CSS files called from an element are missing on the final output

### ISSUE THREAD

**Issue by w-mazed** [cakephp/cakephp#12357]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.
* Platform and Target: Localhost, wampserver.

### What I did
I used the HtmlHelper to include assets in an element called from a view:
```
<?= $this->Html->css([
    '../node_modules/slick-carousel/slick/slick.css'
], ['block' => true]) ?>
<?= $this->Html->script([
    '../node_modules/bootstrap-typeahead/js/bootstrap-typeahead.min.js',
    '../node_modules/slick-carousel/slick/slick.min.js'
], ['block' => true]) ?>
```
Also I called the fetch function from the layout:
```
<?= $this->fetch('css') ?>
<?= $this->fetch('script') ?>
```

### What happened
Only the JS files are included, the CSS files are missing

### What I expected to happen
Including the CSS link files on the final output

**Comment by markstory** [comment]
Is the element executed after the `fetch('css')` call runs?

**Comment by markstory** [comment]
So the element runs *after* the block is fetched?

**Comment by w-mazed** [comment]
No, the fetch is before the call of the element, but I tried to put the fetch to the bottom of the layout, even like this it doesn't work, I tried a trick, i removed the block param on the css function (HtmlHelper) a new line was added but no link tag.

**Comment by saeideng** [comment]
```php
//src/Template/Layout/default.ctp
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
    <?= $this->fetch('content') ?>
```
```php
// src/Template/Pages/index.ctp
<?= $this->Html->css([
    'css1.css'
], ['block' => true]) ?>
<?= $this->Html->script([
    'js1.js',
    'js2.js'
], ['block' => true]) ?>

<?= $this->element('test'); ?>

<?= $this->Html->css([
    'css3.css'
], ['block' => true]) ?>
<?= $this->Html->script([
    'js5.js',
    'js6.js'
], ['block' => true]) ?>
```
```php
// src/Template/Element/test.ctp
<?= $this->Html->css([
    'css2.css'
], ['block' => true]) ?>
<?= $this->Html->script([
    'js3.js',
    'js4.js'
], ['block' => true]) ?>
```
result 
```
<link rel="stylesheet" href="/site/css/css1.css"/>
<link rel="stylesheet" href="/site/css/css2.css"/>
<link rel="stylesheet" href="/site/css/css3.css"/> 
<script src="/site/js/js1.js"></script>
<script src="/site/js/js2.js"></script>
<script src="/site/js/js3.js"></script>
<script src="/site/js/js4.js"></script>
<script src="/site/js/js5.js"></script>
<script src="/site/js/js6.js"></script>
```

**Comment by markstory** [comment]
I am also not able to reproduce this. Could you provide a small layout/template/element to help reproduce the error you are having?

**Comment by w-mazed** [comment]
Indeed (I hope that be clear for you):

```
// default.ctp (layout)
<head>
...
<?= $this->fetch('css') ?>
<?= $this->Html->css('app.css') ?>
...
</head>
<body>
...
<?= $this->element('highlighted') ?>
...
<?= $this->Html->script([
    '../node_modules/jquery/dist/jquery.min.js',
    'app.js'
]) ?>
<?= $this->fetch('script') ?>
</body>

// highlighted.ctp (element)
...
<?= $this->Html->css([
    '../node_modules/slick-carousel/slick/slick.css'
], ['block' => true]) ?>
<?= $this->Html->script([
    '../node_modules/slick-carousel/slick/slick.min.js'
], ['block' => true]) ?>
...

// Final Html output 
<head>
...
// no link tag to slick.css !!
<link rel="stylesheet" href="/path/to/project/css/app.css"/>
...
</head>
<body>
...
<script src="/path/to/project/../node_modules/jquery/dist/jquery.min.js"></script>
<script src="/path/to/project/js/app.js"></script>
// the script tag to slick.min.js is generated !!
<script src="/path/to/project/../node_modules/slick-carousel/slick/slick.min.js"></script>
</body>
```

**Comment by ADmad** [comment]
The `fetch('css')` call has already been made *before* the element `highlight` is included. So it's not surprising that css added inside the element doesn't show up as the code is executed from top to bottom.

**Comment by w-mazed** [comment]
@ADmad, Yes right :/ but is there a solution to include element assets with an param block to true in the case where the fetch method is called before the element ?

**Comment by ADmad** [comment]
Call the element before fetching the script block but instead of directly echoing save the output in a variable and then echo the variable at appropriate location.

**Comment by saeideng** [comment]
why are you trying to add asset (css) in the element ? when element called in  root (layout)??
move methods to layout

**Comment by w-mazed** [comment]
@ADmad thank you for your answer :) (sorry for this fake issue :p), @saeideng why elements are created ?? For keepin layout comprehensible, because in most of time the page can be split in many parts, in this way we can keep code clear (it's my own opinion).
