### ISSUE TITLE
bake, po files and i18n

### ISSUE THREAD

**Issue by jarekgol** [cakephp/cakephp#12354]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I make new project and I think that it will be usable, when bake will produce standard links, like: new something_name_from_db, list ... , as separate words in separate __() functions, so we (foreigners) can translate this 2 words for whole project. example of desired bake effect:
template1.ctp: __("New "). __("zamówienie")
template2.ctp: __("List "). __("Klienci")
template2.ctp  __("List ").  __("zamówienie")

so we can add PO for "new" and it will works on all baked templates and we don't need to add separate msgid for "new **zamówienie**"->"nowe **zamówienie**"  **same word**, that don't need to be translated.
Maybe I don't know something but I tried wild cards in PO like "New*"->"Nowy*" and it does not work.
Jarek (PL)

**Comment by dereuromark** [comment]
You are falsely assuming the order is always the same per language.
What I actually do, is this:

    __('List {0}', __('Posts'))
    __('List {0}', __('Articles'))

This way I only need to translate the action part once, and then each model name once per singular and plural type.
Afaik this used to be also the standard many years back, and I think it still makes the most sense in terms of amount of translations.

**Comment by jarekgol** [comment]
1. I think my proposal doesn't destroy way it work now, so it can be  helpful in some languages.
2. Where or how you put that code? Manually in templates? Or did you modify somehow bake mechanism?

**Comment by dereuromark** [comment]
1. Yes, it does destroy it - I just gave you an example (order in different languages).
2. In my bake templates. But you could make a PR for bake plugin.

Either way, this is the wrong repo for your ticket, you should open one at https://github.com/cakephp/bake instead.

**Comment by jarekgol** [comment]
OK, I will look there, thanks for info.
