### ISSUE TITLE
Passing Variables into an Element

### ISSUE THREAD

**Issue by danny3b** [cakephp/cakephp#12362]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: localhost, MAMP

### What you did
I was trying to pass variable into an element.

### What happened
Variable is passed only when string has at least 14 characters. But it's not a pattern, sometime it's 14, sometime 15, sometime 16.

For example it works: 
    echo $this->element('box', ['text' => 'ABCDEFGHIJKLMN']); //14 characters
    echo $this->element('box', ['text' => 'abcdefghiklmnopq']); //16 characters
    echo $this->element('box', ['text' => '012345678901234']); //15 characters

And it'd does not work:
    echo $this->element('box', ['text' => 'ABCDEFGHIJKLM']); //13 characters
    echo $this->element('box', ['text' => 'abcdefghiklmnop']); //15 characters
    echo $this->element('box', ['text' => '01234567890123']); //14 characters

### What you expected to happen
I'm not sure if it's a bug or desirable behavior. I would like to pass current ID of current record. Can it be done that way?

**Comment by dereuromark** [comment]
echo h($text) always. for Security reasons.

**Comment by markstory** [comment]
@danny3b Could you provide us the code of the problematic element?

**Comment by danny3b** [comment]
Problem solved. There was no problem at all actually, only my stupidity. Sorry guys for bother.
