### ISSUE TITLE
Multiple matchers in a query leads to duplicate sql statements

### ISSUE THREAD

**Issue by chrisch-hh** [cakephp/cakephp#12369]
From [Stackoverflow](https://stackoverflow.com/questions/50509683/cakephp3-multiple-matching-in-query-leads-to-duplicate-sql-statements):

I'm using a query with multiple matching conditions (some of them come from a custom finder) which leads to duplicated sql statements.

For example I have something like that:

```
// Images belongsTo Categories belongsTo Projects
$query = $this->Images->find()
        ->select('id')
        ->matching('Categories', function ($q) {
            return $q->where(['Categories.visible' => 1]);
        })
        ->matching('Categories.Projects', function($q) {
            return $q->where(['Projects.visible' => 1]);
        });
```
The generated sql looks like this:

```
SELECT 
  Images.id AS `Images__id` 
FROM 
  images Images 
  INNER JOIN categories Categories ON (
    Categories.visible = 1 
    AND Categories.visible = 1
    AND Categories.id = (Images.category_id)
  ) 
  INNER JOIN projects Projects ON (
    Projects.visible = 1 
    AND Projects.id = (Categories.project_id)
  )
```
As you can see, `Categories.visible = 1` appears two times in the sql statement. If I add another matching on 'Categories.Projects', `Categories.visible = 1` appears four times and so on. The problem seems to be that the 'Categories.Projects'-matching calls the 'Categories'-matching and adds all the conditions to the sql statement again.

I don't know if I missed something or if this is the expected behavior but I would expect that I can stack multiple matchers and that the conditions appear only once in the sql statement. Maybe a bug in CakePHP?

**Comment by lorenzo** [comment]
Interesting, never seen this before. Can you try this and let me know if it changes anything?

```php
$query = $this->Images->find()
        ->select('id')
        ->matching('Categories.Projects', function($q) {
            return $q->where(['Projects.visible' => 1]);
        })
        ->matching('Categories', function ($q) {
            return $q->where(['Categories.visible' => 1]);
        });
```

If you are blocked by this issue, I know for sure that this is going to work without errors:

```php
$query = $this->Images->find()
        ->select('id')
        ->matching('Categories.Projects', function($q) {
            return $q->where(['Projects.visible' => 1]);
        })
        ->where(['Categories.visible' => 1]);
```

**Comment by chrisch-hh** [comment]
Switching the matchers gives correct SQL without duplicate conditions:

```
$query = $this->Images->find()
	->select('id')
	->matching('Categories.Projects', function ($q) {
		return $q->where(['Projects.id' => 1]);
	})
	->matching('Categories', function ($q) {
		return $q->where(['Categories.visible' => 1]);
	});
```

```
SELECT 
  Images.id AS `Images__id` 
FROM 
  images Images 
  INNER JOIN categories Categories ON (
    Categories.visible = 1 
    AND Categories.id = (Images.category_id)
  ) 
  INNER JOIN projects Projects ON (
    Projects.id = 1 
    AND Projects.id = (Categories.project_id)
  )
```

The problem is that I cannot control the order of the stacked matchers because some of them come dynamically from a custom finder. 

The first version is working for me, because the database's SQL parser seems to ignore duplicated conditions. So it is not a severe problem for my application. But maybe it would be nice if the generated SQL is free from duplicated conditions.

**Comment by lorenzo** [comment]
Thanks for confirming
