### ISSUE TITLE
Alias is removed from value when "updateAll"

### ISSUE THREAD

**Issue by cyan-haru-25** [cakephp/cakephp#12363]
Alias is removed from update value when we use "updateAll".

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.11
* Platform and Target: 
　　DATABASE=> SQL Server

### Example
If alias of "User" model is "u", "u." and "[u]." is removed from update value.

[ex] below updates "user_name" field to "upd-name".
<pre>
$this->User->updateAll(array('user_name'=>"'u.[u].upd-name'"));
</pre>

### Target Database
It occurs when we use "SQL server".
And "MySQL" was no problem.
I didn't verify "Postgres" and "Sqlite".

### Cause of this problem
It occurs because of below function. 
DboSource.php->_prepareUpdateFields

Arias is removed by this code from value.
[line:2183]
<pre>
} elseif (!$alias) {
	$update .= str_replace($quotedAlias . '.', '', str_replace(
		$Model->alias . '.', '', $value
	));
</pre>

## Question
Why alias is removed from $value?
I think it's just a BUG.
Above code should be deleted.

### refer
Aliase is removed from "$field" by this code.
[line:2165]
<pre>
} elseif (!$alias && strpos($field, '.') !== false) {
	$quoted = $this->name(str_replace($quotedAlias . '.', '', str_replace(
		$Model->alias . '.', '', $field
	)));
</pre>
I can understand it , but I think alias shouldn't be removed from "$value"

**Comment by markstory** [comment]
You can try to remove the alias stripping, but I suspect that their are other use cases/test suite scenarios that require that code to continue existing.

**Comment by markstory** [comment]
https://book.cakephp.org/2.0/en/development/testing.html#running-tests-from-command-line shows how to run tests.

**Comment by dereuromark** [comment]
Are you interested in providing a PR with a fix? Otherwise we will close this as out of scope for maintenance mode for 2.x
