### ISSUE TITLE
2.10.10 TranslateBehavior fails to restore old fields when bindTranslation is used

### ISSUE THREAD

**Issue by mma** [cakephp/cakephp#12376]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.10
* Platform and Target: Apache 2.4.23, PHP 7.1.14, MySQL 5.7.14, Windows 10 x64

### What you did
I used Translate behavior to an model like so
```
public $actsAs = array(
		'Translate' => array(
			'description',
			'joinType' => 'LEFT'
                 ),
               'Containable',
	);
```
And everything works as expected.
But given the use case:
```
             $this->Model->bindTranslation(array('description' => 'description_translations'), true);
             $this->Model->find('first',array(
			 'conditions' => [
				'Model.id' => $id,
			],
			'contain' => array(
				'description_translations'
			)
	      ));
              $this->Model->find('first',array(
			'fields' => array(
				'Model.description',
			),
			'conditions' => [
				'Model.id' => $id,
			],
		));
		$this->Model->find('first',array(
			'fields' => array(
				'Model.description',
			),
			'conditions' => [
				'Model.id' => $id,
			],
		));
```
### What happened
The last call to find() will fail with:
```
Column not found: 1054 Unknown column 'Model.description' in 'field list'
```
So why does this happen?

- Looking at bindTranaslation this line https://api.cakephp.org/2.10/source-class-TranslateBehavior.html#685 executes and an value is push to array $this->runtime[$Model->alias]['restoreFields'].
- Now the first find() runs and then in afterFind() restores the fields
 https://api.cakephp.org/2.10/source-class-TranslateBehavior.html#349
- The second find() is run and in afterFind() this gets executed https://api.cakephp.org/2.10/source-class-TranslateBehavior.html#347 and `$this->runtime[$Model->alias]['fields']` is set to empty.
- Last find() tries to run but it can't because it doesn't know that is needs to make an join, because the fields are empty so no join and there is the error.

### What you expected to happen
I would expect that $reset = true to bindTranslation() will just reset the fields to original after it run not to empty.
As a side note the doc is wrong https://api.cakephp.org/2.10/source-class-TranslateBehavior.html#643
According to the doc the second find() should fail but it was the third that failed.

As a fix we could replace this line https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Behavior/TranslateBehavior.php#L347
with `$this->runtime[$Model->alias]['virtualFields'] = array();` 
So that if we use bindTranslation() the old fields will be used not empty. (not 100% about this fix, clearly there are multiple ways to fix this)

Or all of this could be intended and I just lost 1 day for nothing 😢

**Comment by markstory** [comment]
Could you send a pull request with the change that would solve the issue you're having? If the current tests pass what you're expecting sounds reasonable to me.

**Comment by mma** [comment]
@markstory pull request https://github.com/cakephp/cakephp/pull/12378

**Comment by markstory** [comment]
Thank you 👍
