### ISSUE TITLE
URL base configuration is not read correctly in CLI

### ISSUE THREAD

**Issue by liviascapin** [cakephp/cakephp#12375]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7

### What you did
We tried sending some sort of login reminder emails through a shell. As we use localhost to develop our projects, the url to send with that email would have to be http://localhost/project/users/login. We set ``App.base`` (to /project) and ``App.fullBaseUrl`` (to http://localhost) (see https://book.cakephp.org/3.0/en/development/configuration.html#general-configuration). 

### What happened
The resulting URL is http://localhost/users/login instead of http://localhost/*project*/users/login.

### Reproduction
To confirm the issue (and maybe as a guide to reproduce this) I created a new project from scratch. I only changed the ``App.base`` and ``App.fullBaseUrl`` configuration in app.php. I tested Router::url in the PagesController. It did work fine there, because $_requestContext['_base'] gets set (by the RoutingMiddleware I guess). I wrote a very simple shell to confirm that the bug exists in CLI context:

```php
<?php

namespace App\Shell;

use Cake\Console\Shell;

class TestShell extends Shell
{
    public function main()
    {
        $url = \Cake\Routing\Router::url([
            'controller' => 'Pages',
            'action' => 'display'
        ], true);
        $this->log($url, LogLevel::INFO);
    }
}
```

It did work correctly with CakePHP 2.x. I suspect the problem might be in https://github.com/cakephp/cakephp/blob/master/src/Routing/Router.php#L704 (which previously was https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Routing/Router.php#L941) but I'm not sure since I don't know the Router very well.

**Comment by markstory** [comment]
Pull request up now.
