### ISSUE TITLE
unhandled \Aura\Intl\Exception

### ISSUE THREAD

**Issue by jakubpas** [cakephp/cakephp#12372]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.5
* Platform and Target: apache2, mysql 

### What you did
`      $this->set('description', __('Gallery'));`

### What happened
Since cakephp 3.6 functions.php uses Aura so PHP Storm shows hundreds of warnings about "unhandled \Aura\Intl\Exception". Looks like every time I want to use translation I need to catch \Aura\Intl\Exception to disable the warnings. Is it correct or simply "__" function is depreciated and I should use something else?

### What you expected to happen
I expected to not catch  \Aura\Intl\Exception every time I use "__" function

**Comment by lorenzo** [comment]
This is already solved in the master branch

**Comment by jakubpas** [comment]
Thanks. Is there already a tagged version containing this fix?

**Comment by lorenzo** [comment]
not yet, but will be out soon

**Comment by jakubpas** [comment]
Thanks for info
