### ISSUE TITLE
NotFoundException Paginator out of range on post with CakeDC/Search

### ISSUE THREAD

**Issue by BenoKop** [cakephp/cakephp#12370]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.6.
* Platform and Target: Apache, MySQL.

### What you did
Hello guys,

I'm currently doing a list with some search inputs to filter the results.
I use CakeDC/Search version 3.0.x-dev for the search forms.

The pagination is working pretty good and the search component too.
But when I use the two components at the same time, i'm getting an out of range error, and it seems pretty logic.

When I go on the last page of my list and POST my search DATA, i'm getting an Cake\Http\Exception\NotFoundException.

params: **?affcode=&semLivraison=&tirsociete=&isProdCheck=on&isAtelierQuincDone=1&page=3&direction=asc**

I POST at page 3 but the new results are not generating a third page because they are less than before.

I try to catch the exception and it works without writing any code in the catch part. When I write some code in it, it's getting ignored.

```

$this->paginate = [
            'limit' => 20,
            'order' => [
                'semLivraison' => 'asc',
                'affcode' => 'asc',
            ]
];

$this->Prg->commonProcess();

$affairesEnProd = $this->AffairesEnProd->find('forProduction');
$affairesEnProd = $affairesEnProd->contain(['ArticlesPourAffaireEnProd' => [ 'sort' => ['ArticlesPourAffaireEnProd.plvnumligne']],
            'AteliersPourAffaireEnProd',
            'ColisPourAffaireEnProd' => ['sort' => ['ColisPourAffaireEnProd.colisNumero']],
]);

$affairesEnProd = $affairesEnProd->find('searchable', $this->Prg->parsedParams())
            ->distinct();

try {
            $this->paginate($affairesEnProd);
} catch (NotFoundException $e) {
}

```

**Comment by dereuromark** [comment]
Maybe you are missing the use statements to be able to use the catch block here?
Otherwise you could also look into using https://github.com/dereuromark/cakephp-shim/wiki/Paginator-with-out-of-bounds-fix

**Comment by BenoKop** [comment]
After some tests, i'm not sure that CakePHP is the problem, I think that CakeDC/Search is doing something that cake can't handle. Anyway, I personally fixed my bug.

**Comment by dereuromark** [comment]
Closing then as user land issue.
