### ISSUE TITLE
new ServerRequest('/') returns ServerRequest object with wrong path

### ISSUE THREAD

**Issue by calcosta** [cakephp/cakephp#12389]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7
* Platform and Target: LAMP PHP 7.1

### What you did
_config/routes.php:_
```
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Enable json file extension
    $routes->setExtensions(['json', 'pdf', 'csv']);
    
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'home']);
    
    $routes->fallbacks(DashedRoute::class);
});
```
_anywhere in Code when currently at an URL != /, e.g. /reports/articles:_
```
$request = new \Cake\Http\ServerRequest('/');
debug($request->getUri());
debug(\Cake\Routing\Router::parseRequest($request));
```

### What happened
Debug output is:
```
object(Zend\Diactoros\Uri) {
	base => ''
	webroot => '/'
	[protected] allowedSchemes => [
		'http' => (int) 80,
		'https' => (int) 443
	]
	[private] scheme => 'https'
	[private] userInfo => ''
	[private] host => 'HOSTNAME'
	[private] port => null
	[private] path => '/reports/articles'
	[private] query => ''
	[private] fragment => ''
	[private] uriString => null
}
[
	'controller' => 'Reports',
	'action' => 'articles',
	'pass' => [],
	'plugin' => null,
	'_matchedRoute' => '/:controller/:action/*'
]
```

### What you expected to happen
Debug output should be:
```
object(Zend\Diactoros\Uri) {
	base => ''
	webroot => '/'
	[protected] allowedSchemes => [
		'http' => (int) 80,
		'https' => (int) 443
	]
	[private] scheme => 'https'
	[private] userInfo => ''
	[private] host => 'HOSTNAME'
	[private] port => null
	[private] path => '/'
	[private] query => ''
	[private] fragment => ''
	[private] uriString => null
}
[
	'controller' => 'Pages',
	'action' => 'home',
	'pass' => [],
	'plugin' => null,
	'_matchedRoute' => ['controller' => 'Pages', 'action' => 'home']
]
```

I'm not sure whether this behaviour is intended, but it breaks e.g. the isUrlAuthorized() Method of CakeDC/users Plugin when you check if the url / is allowed for a certain user.
The relevant codeline ist https://github.com/cakephp/cakephp/blob/171923fc1fd83fad95bc49858b866f04b0a7223a/src/Http/ServerRequest.php#L312 which shortens the passed url '/' to '' in the ServerRequest Class constructor.

**Comment by markstory** [comment]
> anywhere in Code when currently at an URL != /, e.g. /reports/articles:

Why are you creating another request object? Are you aiming to build a copy of the current request? Building a request with only the string URL will generally not work as the internal Uri object uses context defined in `$_SERVER` which you are not overwriting correctly.

**Comment by calcosta** [comment]
It is used in CakeDC/users plugin to check authorization for a given url: https://github.com/CakeDC/users/blob/0dc18023fe1a3d31a33c3546c64c3918e27a6883/src/Controller/Component/UsersAuthComponent.php#L188

So I probably better open an issue in their project if ServerRequest is not designed to be used this way. Should I close this ticket?

**Comment by markstory** [comment]
Interesting. I'll see if we can make this use case work.

**Comment by hdbywtqg** [comment]
<a href="https://wbvc61.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc62.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc63.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc64.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc65.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc66.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc67.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc68.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc69.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc70.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://wbvc71.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc72.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc73.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc74.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc75.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc76.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc77.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc78.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc79.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc80.github.io/"><font color="#FFFAFA">-</font></a>

<a href="https://wbvc81.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc82.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc83.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc84.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc85.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc86.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc87.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc88.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc89.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc90.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://wbvc91.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc92.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc93.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc94.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc95.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc96.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc97.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc98.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc99.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc100.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://wbvc101.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc102.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc103.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc104.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc105.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc106.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc107.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc108.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc109.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc110.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://wbvc111.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc112.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc113.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc114.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc115.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc116.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc117.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc118.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://wbvc119.github.io/"><font color="#FFFAFA">-</font></a>



<a href="https://bbsbuzama.github.io/"><font color="#FFFAFA">-</font></a>

<a href="https://facai01.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai02.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai03.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai04.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai05.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai06.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai07.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai08.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai09.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai10.github.io/"><font color="#FFFAFA">-</font></a>

<a href="https://facai11.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai12.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai13.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai14.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai15.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai16.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai17.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai18.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai19.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai20.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://facai21.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai22.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai23.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai24.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai25.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai26.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai27.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai28.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai29.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai30.github.io/"><font color="#FFFAFA">-</font></a>


<a href="https://facai31.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai32.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai33.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai34.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai35.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai36.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai37.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai38.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai39.github.io/"><font color="#FFFAFA">-</font></a>
<a href="https://facai40.github.io/"><font color="#FFFAFA">-</font></a>

**Comment by markstory** [comment]
Pull request open now.
