### ISSUE TITLE
$this->referer() returns '/' if $ref == empty. Expected a null/empty return value

### ISSUE THREAD

**Issue by wschwarte** [cakephp/cakephp#12402]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x ] feature-discussion (RFC)

* CakePHP Version: 3.5.1

### What you did
I needed to check the referer on a controller for some params, so i used $this->referer(). This works when there is a referer, but when the page is called directly, the call to referer() returns '/'. 

 ```
   public function referer($local = false)
    {
        $ref = $this->getEnv('HTTP_REFERER');

        $base = Configure::read('App.fullBaseUrl') . $this->webroot;
        if (!empty($ref) && !empty($base)) {
            if ($local && strpos($ref, $base) === 0) {
                $ref = substr($ref, strlen($base));
                if (!strlen($ref)) {
                    $ref = '/';
                }
                if ($ref[0] !== '/') {
                    $ref = '/' . $ref;
                }

                return $ref;
            }
            if (!$local) {
                return $ref;
            }
        }

        **return '/';**
    }

```

### What you expected to happen
I was expecting an empty return value for an empty referer.

**Comment by markstory** [comment]
Changing the default value of `referer()` would be a breaking change, moving to 4.0 where this could be discussed further.

**Comment by ADmad** [comment]
Returning `null` when there is no referrer sounds reasonable to me. If someone wants a default value when there is no referrer than it can be already achieved using `Controller::referer()`. I'll make this change for 4.0.

**Comment by ADmad** [comment]
Closing as the change has been done in 4.0. 3.x can't be changed for backwards compatibility reasons.
