### ISSUE TITLE
Collection::sortBy does not sort properly

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#12406]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.9

* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

na

### What you did

```php
$a = [
        ['x' => 1, 'y' => 1, 'z' => 0],
        ['x' => 2, 'y' => 2, 'z' => 3],
        ['x' => 2, 'y' => 2, 'z' => 1],
        ['x' => 2, 'y' => 2, 'z' => 2],
        ['x' => 1, 'y' => 3, 'z' => 3],
        ['x' => 1, 'y' => 2, 'z' => 0],
    ];
$a = new Collection($a);
$s = $a->sortBy(function ($_a) {
    return $_a['x'] . '-' . $_a['y'] . '-' . $_a['z'];
});
debug($s->extract(function($_a) {
    return $_a['x'] . '-' . $_a['y'] . '-' . $_a['z'];
}, SORT_ASC, SORT_STRING)->toArray());
```

### What happened

The output of the above is the following

```php
[
    (int) 1 => '2-2-3',
    (int) 2 => '2-2-1',
    (int) 3 => '2-2-2',
    (int) 0 => '1-1-0',
    (int) 4 => '1-3-3',
    (int) 5 => '1-2-0'
]
```

### What you expected to happen

I would except a sorting by the whole concetenated string with this output

```php
[
    (int) 0 => '1-1-0',
    (int) 5 => '1-2-0'
    (int) 4 => '1-3-3',
    (int) 2 => '2-2-1',
    (int) 3 => '2-2-2',
    (int) 1 => '2-2-3',
]
```

**Comment by lorenzo** [comment]
Is that the actual code you are running? At first glance it does not make sense

**Comment by rrd108** [comment]
The actual code is much more complicated, I am working with a query with a lot of joins. As I have to add additional items after the query is executed I can not use the ORM's orderBy method.

In my case `x`, `y` and `z` are object properties form the query resultset and I want to sort it by 3 different fileds.

I used this example just to show the sorting seems to be dropped after the first character.

Am I doing something wrong?

**Comment by markstory** [comment]
Why do you provide sort constants to extract()? Shouldn't they go into sortBy()?

**Comment by rrd108** [comment]
@markstory in my actual code there is no extract. Here I just used it to show the unexpected behaviour.

**Comment by markstory** [comment]
Ok. I can try to reproduce this on my end.

**Comment by markstory** [comment]
@rrd108 The following test is passing for me locally.

```php
        $items = [
                ['x' => 1, 'y' => 1, 'z' => 0],
                ['x' => 2, 'y' => 2, 'z' => 3],
                ['x' => 2, 'y' => 2, 'z' => 1],
                ['x' => 2, 'y' => 2, 'z' => 2],
                ['x' => 1, 'y' => 3, 'z' => 3],
                ['x' => 1, 'y' => 2, 'z' => 0],
            ];
        $collection = new Collection($items);

        $sorted = $collection->sortBy(function ($item) {
            return $item['x'] . '-' . $item['y'] . '-' . $item['z'];
        }, SORT_ASC, SORT_STRING);
        $expected = [
            ['x' => 1, 'y' => 1, 'z' => 0],
            ['x' => 1, 'y' => 2, 'z' => 0],
            ['x' => 1, 'y' => 3, 'z' => 3],
            ['x' => 2, 'y' => 2, 'z' => 1],
            ['x' => 2, 'y' => 2, 'z' => 2],
            ['x' => 2, 'y' => 2, 'z' => 3],
        ];
        $this->assertEquals($expected, $sorted->toList());

        $extracted = $sorted->extract(function ($item) {
            return $item['x'] . '-' . $item['y'] . '-' . $item['z'];
        });

        $expected = [
            '1-1-0',
            '1-2-0',
            '1-3-3',
            '2-2-1',
            '2-2-2',
            '2-2-3',
        ];
        $this->assertEquals($expected, $extracted->toList());
```

The key difference is that I'm using `toList()` and you're using `toArray()`. Given that you do not need the keys in your result you should use `toList()` as `toArray()` will create more creative output when there are duplicate keys.

**Comment by rrd108** [comment]
I loop through my collection via foreach and the ordering is wrong.

After `sortBy` I call `groupBy` and than `filter` on the collection. Can they modify the order?

Here is my production code

````php
$items = $items->map(function ($depatmentItems) use ($options) {
    $depatmentItems = collection($depatmentItems);

    $depatmentItems = $depatmentItems->sortBy(function ($departmentItem) {
        return $departmentItem->accountCode
            . ':' . $departmentItem->_matchingData['Invoices']->num
            . ':' . $departmentItem->num;
    })->groupBy('accountCode');

    return $depatmentItems->filter(function ($items, $invoiceNumber) use ($options) {
        if ($options['ac-endAccountId']) {
            return InvoiceNumber::isInRange(
                $invoiceNumber,
                [$options['ac-accountId'], $options['ac-endAccountId']]);
        }
        return InvoiceNumber::format($invoiceNumber) == InvoiceNumber::format($options['ac-accountId']);
    });
});
````

**Comment by markstory** [comment]
I'm not going to be able to help much with that specific example as I'm lacking context and the data it operates on. Have you tried paring down that code to see at which stage the results are not correct?
