### ISSUE TITLE
SecurityComponent Error: Session was already started

### ISSUE THREAD

**Issue by kwentworth** [cakephp/cakephp#12401]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.9

### What you did
I just upgraded a 3.5 app to 3.6.  When I post certain forms I am getting a "session was already started" runtime exception.  

Fixed by adding $this->Security->config('unlockedActions', ['action']); but I want to keep the Security protections in place...

I think something else in my app is opening the session before security component tries to open the session as part of _validatePost().  I haven't tracked it down entirely but I do know that this is happening because Security::_hashParts() now calls $session->start() which in turn throws a runtime exception if a session has already started.

Is it intended behavior to kill the current form post because a session was started before the security component tried to start the session itself in _hashParts()?  If it isn't a risk, is there any reason not to wrap $session->start() code in a try catch logic.

`// In cakephp/src/Controller/Component/SecurityComponent.php

    protected function _hashParts(Controller $controller)
    {
        $request = $controller->getRequest();

        // Start the session to ensure we get the correct session id.
        $session = $request->getSession();
        try {
            $session->start();
        } catch (\RuntimeException $e) {
            
        }
`
Based on the comments in #11932 and this commit: https://github.com/cakephp/cakephp/commit/e2ed51f20a35966228a298be943757b727dd0360#diff-c1445fb25adc45b0f569da99d2b2e7e8

**Comment by markstory** [comment]
How can someone reproduce the 'session already started' errors?

**Comment by kwentworth** [comment]
I think to reproduce this, you would manually start the session prior to the call to validatePost().  It will then throw an exception because the session is already started. 

I haven't been able to figure out what is causing this in my code to give you any more specifics about reproducing this error.

**Comment by ADmad** [comment]
This error could only occur if session was started outside CakePHP, in which case you should fix your application to not do so.

If you still think it's a CakePHP issue please provide example code to reproduce the error.

**Comment by andrii-pukhalevych** [comment]
Why its not allowed to start session outside CakePHP?
In my case I want to run some task twice and also getting this issue.

Is it possible to change [exception](https://github.com/cakephp/cakephp/blob/ed758075d1a12abebcc958baa450c49961c81dea/src/Http/Session.php#L348) to code below?

```
if (session_status() === \PHP_SESSION_ACTIVE) {
       return true;
}
```

**Comment by markstory** [comment]
@andrii-pukhalevych I would be concerned about state getting out of sync or the session handlers that are configured in CakePHP not being used. Starting the session more than once seems like a problem that should be fixed.

**Comment by andrii-pukhalevych** [comment]
@markstory  I see that Session::check()/read()/write() calls checks Session::started() before calling start().
And SecurityComponent only instantly calling start(); 

public function started()
{
	return $this->_started || **session_status() === \PHP_SESSION_ACTIVE**;
}
