### ISSUE TITLE
when use Auth cannot set custom settings after login

### ISSUE THREAD

**Issue by thmsbgfrv** [cakephp/cakephp#12417]
1) I try to add some custom config to my auth object when user login, but it removed after redirect to other page. i think it becouse everytime load auth in AppController initialize method. How can i solve this problem? is this a bug? or misused?
2)$user = $this->Auth->identify(); in there i want to also retrive connected table row to user object without write any more code, its possible to get it from $this->Auth->identify();
i tried and search many ways, but cant do.

**Comment by dereuromark** [comment]
As documented you can have your own custom finder to further customize the auth data result.
Also, which what I do, you can have a calling code addon after login to further write to Auth.User data in session:
```
            $user = $this->Auth->identify();
            if ($user) {
                // here for example 
                $user = $this->Users->hydrate($user);

                $this->Auth->setUser($user);
                $this->Users->loginUpdate($user);

                $this->Flash->success(__('You are now logged in'));
                return $this->redirect($this->Auth->redirectUrl());
            }
```

This is not a helpforum, but a bugtracker, though.

**Comment by thmsbgfrv** [comment]
Thank you for second issue, but what about first problem is this a bug? cant we setup a custom config in login  or any other controllers;
$this->Auth->setConfig('custom_config',$custom_config);  i use this method in my login.

**Comment by dereuromark** [comment]
You cannot add it that late, it is also not wise to do that inside specific controllers at this point in time.
Set it all up where you know it should be: AppController initialize().

**Comment by thmsbgfrv** [comment]
OK. Thank You Very Much :)
