### ISSUE TITLE
Problem with $this->Url->build(null, true)])

### ISSUE THREAD

**Issue by jakubpas** [cakephp/cakephp#12423]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.9 (but bug present at least since 3.5.6)
* Platform and Target: apache2, mysql 

### What you did
` $this->Url->build(null, true)]);`

### What happened
This should return current url of page in my case:

`https://www.url.pl/Chelsea-Wolfe-juz-za-2-tygodnie-na-jedynym-koncercie-w-Polsce-51586.html`

but I get 
`https://www.url.pl/Chelsea-Wolfe-juz-za-2-tygodnie-na-jedynym-koncercie-w-Polsce-51586.html?url=Chelsea-Wolfe-juz-za-2-tygodnie-na-jedynym-koncercie-w-Polsce-51586.html`

### What you expected to happen

Looks like there is an error in implementation of method 'getQuery()" in 
psr/http-message/src/UriInterface.php

In:

src/Http/ServerRequest.php 

In method:

public function getRequestTarget()
line 138
```
if ($this->uri->getQuery()) { 
```
If there is no query params the $this->uri->getQuery() shuld return empty string. Instead it returns:
`url=Chelsea-Wolfe-juz-za-2-tygodnie-na-jedynym-koncercie-w-Polsce-51586.html`

Quick dirty fix that works for me is to replace this line with:
```php
if ($this->uri->getQuery() != preg_replace("/^\//", "url=",$target)) {
```
It did not have a time to get at the bottom of this but this error is not present when I run the local php -S server only on production apache. That is why it also may not affect some unittests.

**Comment by jakubpas** [comment]
The result is  "url=Chelsea-Wolfe-juz-za-2-tygodnie-na-jedynym-koncercie-w-Polsce-51586.html" but I guess it should be empty string. I have no rewriting on web server. The router configuration beside cake standard:

```
	RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]
```

 for this url is:

`$routes->connect('/:slug-:id:suffix', ['controller' => 'News', 'action' => 'view'], ['_name' => 'news', 'pass' => ['id', 'slug', 'suffix'], 'id' => '[0-9]+', 'suffix' => '.html']);`

**Comment by jakubpas** [comment]
Thanks it helps. Look like it was changed in somwhere on the way of 3.x wersion updates. The routed pages looks ok now but I have problme with main page though. The page:

**Comment by dereuromark** [comment]
That is expected.

**Comment by jakubpas** [comment]
Ok. Looks like you are right. The http procol header says "Request URL: https://www.darkplanet.pl/". I will deal with this. Sorry for bothering you - looks like no bug at all.
