### ISSUE TITLE
Scoped routes with placeholder that can be the empty string

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#12422]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.17

I'm trying to setup a set of routing rules with an optional prefix. The routes are named so I can't duplicate them. I've tried the scope() and prefix() methods with similar results.

A simplified example of a route with and without prefix:

 - /:domain/search (name = "search")
 - /search (name = "search")

Since the routes are named I can't just duplicate them with and without prefix.

I've tried setting the routes with the scope "/:domain".

```
Router::scope('/:domain', function ($routes) {
  $routes->connect('/search', [...], ['_name' => 'search']);
});
```

The router can correctly generate the URLs with domain set to the empty string:

```Router::url(['domain' => '', '_name' => 'search']);```

Returns: /search

But it won't work in the other direction.

```Router::parse('/search');```

Returns: A route matching '/search' could not be found.

Unless I'm missing some other solution, I think there's 2 ways to improve the router so this is possible:

 - Since the router already builds URLs correctly, we could extend the router so that it can handle the parsing of scoped routes with a placeholder that can be empty.
 - Being able to duplicate route names we would be able to duplicate the routes with and without scope. The resolution would have to go through all the routes with the same name until one of them matches. Having to duplicate routes makes it less DRY.

**Comment by berarma** [comment]
> How would the router separate the difference between an optional missing segment and an incorrect match? I think we would need a way to mark specific segments as optional.

Yes. That would be a great solution. The router should be able to parse the segment as the empty string.

```Router::scope('/:domain', ...)``` should be interpreted like we do now but also as ```Router::scope('/', ...)``` when ```domain``` is optional. I don't know how easy would it be to implement but it's the only solution I see to my problem apart from creating a custom route class that handles all the routing.

**Comment by markstory** [comment]
Optional segments get tricky as they could overlap/shadow another route. I don't think it would always be easy to figure that situation out.

**Comment by berarma** [comment]
Doesn't it already happen that routes can already overlap other routes and the router takes the one defined first?

**Comment by markstory** [comment]
Yes. But generally that is easy to spot when looking at a dump of the routes as you would see 2 routes with the same path. In this case you would have `/:domain/search` and `/search` in the list. I don't think that is entirely obvious. Having optional leading parameters would also require that mid-path parameters be able to be optional as well, which makes routing less clear as well.

**Comment by berarma** [comment]
I've been looking at the routing code and I think that it could be implemented in the route class. If that's true it would be easy to do inside my application.

Still I think that this can be a fairly common problem that should have a better solution in future versions. The typical case being a multi-domain app with several routes that uses prefixes and a global domain without prefix.

The other possibility is defining all scopes dynamically. In my case that would require reading all possible scopes from the database every time. And named routes would have to be prefixed so I'd have to pass the prefixed name every time. I'd have to change all my uses of the named routes to go from routing without prefixes to routing with and without. That's something the routing component was supposed to avoid.

**Comment by markstory** [comment]
It does seem like something that would be handled inside Route::parse(). Outside of named routes being unique are there other problems with having two routes defined? One with the prefix and one without?

**Comment by berarma** [comment]
I can avoid duplicating code by using an anonymous function so I think the only problem is the named routes.
