### ISSUE TITLE
4.x - Use immutable classes for database type classes by default.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12427]
I think this would be a good time to switch to immutable types by default. I can make the PR once agreed.

It won't be create any migration overhead as those wishing to keep using mutable types by default can simply use `->useMutable()` for required type in bootstrap.

**Comment by lorenzo** [comment]
I agree

**Comment by ADmad** [comment]
I actually already did that when I split `TypeFactory` and `BaseType` :slightly_smiling_face: 

https://github.com/cakephp/cakephp/blob/745eec56a6aa7a94b5d45b8286157732844acc57/src/Database/Type/DateTimeType.php#L96-L100
