### ISSUE TITLE
CakeEmail:: Add reset function for single variables like cc

### ISSUE THREAD

**Issue by makkus183** [cakephp/cakephp#12425]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.9.9
* Platform and Target: LAMP
### What you did
Sending Emails in a loop and trying to reset the `cc` variable if there is no address for that recipient in the loop.

### What happened
inside a loop i was trying to unset the `cc` value:

```
      $Email->to($email);
      // send also to email_assistance
      if(!empty(trim($recipient['User']['email_assistance']))) {
        $Email->cc(trim($recipient['User']['email_assistance']));
      } else {
        $Email->cc(null);
      }
```
`i also tried  $Email->cc('');`

### What you expected to happen
I expected that the `cc` value is empty and the current Email is sent without cc.

But i looked in 
[/cakephp/cakephp/lib/Cake/Network/Email/CakeEmail.php](https://github.com/cakephp/cakephp/blob/bfd2d21d782a69626bcf1ae2d22aad6e565fb29c/lib/Cake/Network/Email/CakeEmail.php#L489)

and saw that you cannot unset it by adding an empty value:

```
	public function cc($email = null, $name = null) {
		if ($email === null) {
			return $this->_cc;
		}
		return $this->_setEmail('_cc', $email, $name);
	}

```

The only possibility to unset values is `reset()`:
https://github.com/cakephp/cakephp/blob/bfd2d21d782a69626bcf1ae2d22aad6e565fb29c/lib/Cake/Network/Email/CakeEmail.php#L1291

```
/**
 * Reset all CakeEmail internal variables to be able to send out a new email.
 *
 * @return self
 */
	public function reset() {
		$this->_to = array();
		$this->_from = array();
		$this->_sender = array();
		$this->_replyTo = array();
		$this->_readReceipt = array();
		$this->_returnPath = array();
		$this->_cc = array();
		$this->_bcc = array();
		$this->_messageId = true;
		$this->_subject = '';
		$this->_headers = array();
		$this->_layout = 'default';
		$this->_template = '';
		$this->_viewRender = 'View';
		$this->_viewVars = array();
		$this->_theme = null;
		$this->_helpers = array('Html');
		$this->_textMessage = '';
		$this->_htmlMessage = '';
		$this->_message = '';
		$this->_emailFormat = 'text';
		$this->_transportName = 'Mail';
		$this->_transportClass = null;
		$this->charset = 'utf-8';
		$this->headerCharset = null;
		$this->_attachments = array();
		$this->_config = array();
		$this->_emailPattern = static::EMAIL_PATTERN;
		return $this;
	}
```
But if you are sending emails in a loop a lot of these settings stay the same.

So it would be nice to have a rest function for single variables like `cc`.

**Comment by markstory** [comment]
There are no new additional features being added to 2.x at this point in time. We could consider adding new features to `Email` in 3.x.

**Comment by ADmad** [comment]
In 3.x you can already do `$email->setCc([])` to reset existing value.

**Comment by ADmad** [comment]
Closing as we are not adding any more enhancement to 2.x and what you need is already achievable in 3.x.
