### ISSUE TITLE
ROOT\config\routes.php:122 You no longer need to call `Plugin::routes()` after upgrading to use Http\Server

### ISSUE THREAD

**Issue by dhananjayve** [cakephp/cakephp#12424]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.
* Platform and Target: cakephp

### What you did
i have upgraded cakephp v3.5 to v3.6

### What happened
upgrading shows multiple deprecation warnings. after removing many warnings, I am unable to understand problem with this
ROOT\config\routes.php:122 You no longer need to call `Plugin::routes()` after upgrading to use Http\Server
I had commented `Plugin::routes()` in routes.php and then nothing works. no routes are working.
there is one more warning
CAKE\Core\Plugin.php:310
You no longer need to call `Plugin::routes()` after upgrading to use Http\Server.

### What you expected to happen
after commenting `Plugin::routes()`  in routes.php file every things should run fine.

I have checked [#634](https://github.com/cakephp/debug_kit/issues/634) and upgraded debug kit to v3.* but nothing works

**Comment by markstory** [comment]
You can either [disable deprecation warnings](https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#disabling-deprecation-warnings) or fix the problems the deprecations point out, as they will be blockers to upgrade to 4.0 when it is ready.
