### ISSUE TITLE
3.x Reference to Shell:: constants in ConsoleIo but no use statement

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12439]
Am I blind / Is it just me?

https://github.com/cakephp/cakephp/blob/abbb678b23de16d0e4d15367804d7ae741510842/src/Console/ConsoleIo.php#L176

https://github.com/cakephp/cakephp/blob/abbb678b23de16d0e4d15367804d7ae741510842/src/Console/ConsoleIo.php#L196

**Comment by markstory** [comment]
Looks like a copy/paste mistake from when all the code lived in Shell. ConsoleIo should only be using its own constants.  Would you be able to send a pull request?

**Comment by inoas** [comment]
Closing as PR is open.
