### ISSUE TITLE
MySQL foreign key description bug

### ISSUE THREAD

**Issue by benyogyerek** [cakephp/cakephp#12431]
This is a **BUG**.
* CakePHP Version: 3.6.10
* Platform and Target: business level hosting from mochahost (Linux, shared, Apache, php7, mysql)

### What I did
Database has multiple foreign keys defined.

### What happened
Script loading for 30-60 seconds(!!) because of a query. Mostly die HTTP/504 Gateway timeout instead.

### What you expected to happen
At least work...

### What is causing the bug
Initially thought it was caused by 'SHOW SCHEMAS' query (see later on) whose usage is restricted on hosting but after an evening of investigation found out Cake\Database\Schema\MysqlSchema::describeForeignKeySql() is causing the problem since queries on information schema db seems also not to be allowed.

Since every uncached pageload uses this my app is basically unusable with foreign keys defined.

### Also note
Many hosting providers restrict the usage of a ton of mysql commands, mine for example requires to use "SHOW SCHEMAS LIKE 'myuser_%' " instead of 'SHOW SCHEMAS', since all db names start with the username.

**Comment by markstory** [comment]
> ... is causing the problem since queries on information schema db seems also not to be allowed.

Why are you not allowed to read from `information_schema`?

Our current database schema reflection never uses `SHOW SCHEMAS`. Why do you mention that command in particular? All of our existing reflection commands are scoped to the application's database. If you need custom schema reflection queries you'll need to implement that with a customized driver.

If you would like to skip schema reflection entirely, you can do so by overwriting the `getSchema()` method in your table classes.

**Comment by benyogyerek** [comment]
"You will not be able to use the above command (mysql privilege). The restriction is applied in order to improve the overall performance of our MySQL servers as well improve the uptime, and server security. (...) For running such queries I recommend upgrading to our private plans where the MySQL service is private and you can have full "root" privileges to it." - this is what the say about it.

I included show schemas because initially I thought it was causing the long runtime, then found out it is not but decided to keep it here as an example of most hosting providers could restrict the access to the database even on these levels.

**Comment by markstory** [comment]
@benyogyerek Sounds like you need to pay for your hosting, build your own driver, or implement `getSchema()` in your table classes so that reflection isn't used.

I'm going to close this issue as there are a few different ways you can solve this problem, which hasn't been a problem for most folks thus far.
