### ISSUE TITLE
Query error when using contain() inside innerJoinWith()

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#12440]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.17

I've found a problem using the ShadowTranslate behavior ([AD7six/cakephp-shadow-translate](url)).

Please, see also [AD7six/cakephp-shadow-translate/issues/52](url) for more information.

I have the associations: Destinations hasMany Countries hasMany CountriesI18n

This is an example that shows what the behavior is trying to do:

```php
$DestinationsTable
  ->find()
  ->innerJoinWith('Countries', function ($q) {
    return $q->contain('CountriesI18n');
   })
  ->where(['CountriesI18n.slug' => 'aaa']);
```
The result:
> PDOException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'CountriesI18n.slug' in 'where clause''

This is the resulting query:

```
=> Cake\ORM\Query {#334                     
     +"(help)": "This is a Query object, to get the results execute or iterate it.",
     +"sql": "SELECT Destinations.id AS `Destinations__id`, Destinations.created AS
`Destinations__created`, Destinations.type AS `Destinations__type`,
Destinations.province_id AS `Destinations__province_id`,
Destinations.country_id AS `Destinations__country_id`,
Destinations.parent_id AS `Destinations__parent_id`, Destinations.enabled AS
`Destinations__enabled`, Destinations.name AS `Destinations__name`
FROM destinations Destinations
INNER JOIN countries Countries ON Countries.id = (Destinations.country_id)
WHERE CountriesI18n.slug = :c0",
     +"params": [                          
       ":c0" => [             
         "value" => "aaa",                  
         "type" => null,                   
         "placeholder" => "c0",
       ],                                   
     ],                                    
     +"defaultTypes": [
....
   ],
     +"decorators": 0,
     +"executed": false,
     +"hydrate": true,
     +"buffered": true,
     +"formatters": 0,
     +"mapReducers": 0,
     +"contain": [
       "Countries" => [
         "CountriesI18n" => [],
       ],
     ],
     +"matching": [
       "Countries" => [
         "queryBuilder" => Closure {#348
           parameters: {
             $q: {},
           },
         },
         "matching" => true,
         "joinType" => "INNER",
         "fields" => false,
       ],
     ],
     +"extraOptions": [],
     +"repository": App\Model\Table\DestinationsTable {#301
       +"registryAlias": "Destinations",
       +"table": "destinations",
       +"alias": "Destinations",
       +"entityClass": "App\Model\Entity\Destination",
       +"associations": [
         "countries",
       ],
       +"behaviors": [],
       +"defaultConnection": "default",
       +"connectionName": "default",
     },
   }
```

I'm trying to understand the issue and fix it but I'm not sure where and how to fix it.

Thanks.

**Comment by berarma** [comment]
Notice the content of the ```contain``` and ```matching``` arrays. The ORM ignores the contain contents because it has already processed the Countries model in the matching array. But then the CountriesI18n isn't processed and not joined in.

**Comment by lorenzo** [comment]
Ok, this is not supported.

The best I can do for now is throw an exception when trying to use contain inside any of the joinWith methods, unless we find a neat way of supporting this complex case.

But we could start debugging now. What happens if you use another innerJoinWith instead of contain?

**Comment by berarma** [comment]
So far I've learned that the ORM is trying to move the contains from the ```innerJoinWith``` to the main query. That's good but while I guess this would work for a ```contain``` inside a ```contain```, it fails for a ```contain``` inside an ```innerJoinWith```.

The problems I've hit here are:
 - The ORM ignores any contained models inside the model we called ```innerJoinWith``` on.
 - The ```where``` clause inside the innerJoinWith should be moved to the ```where``` clause in the main query or any conditions on the contained model will fail.

I'm not saying these are bugs in the ORM. I don't know how far the ORM is supposed to go with cases like this. But I'd like to know how could be made to work.

**Comment by berarma** [comment]
Hi @lorenzo. We posted almost at the same time.

> What happens if you use another innerJoinWith instead of contain?

I've tried and it solves the first issue, now it includes the table, but it fails in the condition placement. The new query is:

```mysql
SELECT Destinations.id AS `Destinations__id` FROM destinations Destinations INNER JOIN countries Countries ON (CountriesTranslation.slug = :c0 AND Countries.id = (Destinations.country_id)) INNER JOIN countries_i18n CountriesTranslation ON (CountriesTranslation.locale = :c1 AND Countries.id = (CountriesTranslation.id)) WHERE (Destinations.enabled = :c2 AND Destinations.url_friendly = :c3)
```

I've also tried to make the EagerLoader go through the ```contain``` an ```matching``` without missing any model. It has the same effect as using the ```innerJoinWith``` above.

Would it be too hard moving the conditions in the ```where``` clause to the main query?

I need to make this work for a project that uses ShadowTranslate. I will follow advice to try to solve it in a generic way if possible. I don't mind doing it in the ORM or the behavior.

Thanks for looking at it.

**Comment by lorenzo** [comment]
If the plugin is doing exactly what you showed then the query builder should be placing the condition in the main query, otherwise it looks like a bug.

It would be a matter of looking where the conditions are being copied to the join, and not do that. Probably some tests will fail.

**Comment by ADmad** [comment]
@lorenzo Simply put the matching between `Destinations` and `Countries` "prevents" the containment (and hence the join) between `Countries` and `CountriesI18n`.

**Comment by lorenzo** [comment]
@admad can you explicitly that? No sure I understand what difference it makes

**Comment by ADmad** [comment]
@lorenzo Well I don't know why it makes a difference but it does :) 

As shown, @berarma does a `$q->contain('CountriesI18n')` inside the closure for  `innerJoinWith()` and one would expect the resulting query to have a left join with the `countries_i18n` table but there isn't. (Countries hasOne CountriesI18n association is setup by the ShadowTranslateBehavior).

**Comment by ADmad** [comment]
@lorenzo https://github.com/cakephp/cakephp/compare/issue-12440

**Comment by lorenzo** [comment]
@ADmad So the summary is:

* Nesting a contain inside an innerJoinWith does not add the join from the contain
* Replacing the contain() with another `innerJoin` or `matching` makes the join be there, but things may fail due to the order of the joins

Is that correct?

**Comment by ADmad** [comment]
> Nesting a contain inside an innerJoinWith does not add the join from the contain

Yes

> Replacing the contain() with another innerJoin or matching makes the join be there, but things may fail due to the order of the joins

IDK, haven't checked :slightly_smiling_face:

**Comment by berarma** [comment]
> Replacing the contain() with another innerJoin or matching makes the join be there, but things may fail due to the order of the joins

Yes, changing the order of the joins would fix it. I asked about taking the conditions in the closure out to the main query as an alternative solution.

Thank you very much @ADmad. I wish I had came up with the test case in the first place.

**Comment by dereuromark** [comment]
PR open.
