### ISSUE TITLE
4.x - Move view vars from `ViewVarsTrait to `ViewBuilder`.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12459]
Having a public property `ViewVarsTrait::$viewVars` feels icky. Instead the `ViewBuilder` should hold the view vars along with getter/setter methods like all other view related data.

Once concern is since `$viewVars` is part of the trait we can't easily remove it and handle using magic `__get()`, `__set()` as we have done with other properties, so deprecating it in 3.x to warn users of it's removal in 4.x would be problematic.

**Comment by markstory** [comment]
I like the idea as view variables are very much part of what the viewbuilder should be handling. I think documentation based deprecation might be our only realistic option here.

**Comment by ADmad** [comment]
Okay, I think this can be done in 3.7 in a BC way while documenting the deprecation.

**Comment by ADmad** [comment]
Done in #12465.
