### ISSUE TITLE
Cakephp unable to disable CSRF 3.6.10

### ISSUE THREAD

**Issue by phil2396** [cakephp/cakephp#12457]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I am trying to create a simple REST API, using CAKEPHP 3.6.10.

I have spent at least 6 hours searching and nothing is working to have my POST request go trough the api endpoint without using any CSRF header or token.

How can i completely disable this component....

 $this->eventManager()->off($this->Csrf); does not work.

I always get the error     Error: CSRF token mismatch.    </title>...

Thanks!

**Comment by ADmad** [comment]
Are you sure you are using the `CsrfComponent` and not the `CsrfMiddleware`?

**Comment by phil2396** [comment]
Yes I am, I'm not using the Middleware.

You can try youself, by downloading the lastest cakephp and trying to create a REST API using the documentation and making a POST request, I am always receiving a CSRF token mismatch error.

I find it a bit disapointing that it is that complex to create such a common thing as a REST api. 

Thanks

**Comment by markstory** [comment]
@phil2396 How are you applying the middleware to your application? If you're doing it in `Application::middleware()` there is no way to disable the middleware from inside the controller, as controllers are called *after* middleware has been applied.

Instead you need to use [scoped middleware](https://book.cakephp.org/3.0/en/development/routing.html#connecting-scoped-middleware) which allows you to apply middleware to your application based on the routing scope. For example you could do:

```php
// in config/routes.php
use Cake\Http\Middleware\CsrfProtectionMiddleware;

Router::scope('/', function ($routes) {
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware());
    $routes->applyMiddleware('csrf');

    // Connect routes that need CSRF protection.
});

Router::scope('/api', function ($routes) {
  // connect routes with *no* CSRF protection as that middleware is not active
  // for this routing scope.
});
```

If your application is primarily API based and doesn't need CSRF protection you can remove the Middleware from `Application::middleware()` too.

**Comment by phil2396** [comment]
Ok, since the application will only be an API,  solution was to remove the CSRF protection from the Application:Middleware(), now its perfectly working.

Thank you very much.

**Comment by mehov** [comment]
I don't get it: [my `router.php` *does not explicitly enable* the middleware](https://github.com/cakephp/app/blob/ffeed1247ef2b9572807c41c5f24213920fc1517/config/routes.php#L49), yet the protection still works (and prevents me from submitting a POST request without CSRF).

To fix this, I'm supposed to... also *not explicitly enable* the middleware.

I'm on CakePHP 3.6.10
