### ISSUE TITLE
XML Utility: Filter out invalid UTF-8 characters

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#12451]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.8.
* Platform and Target: Debian/Nginx/PHP5.

### What you did

    public function cdata() {
        $description = 'Den snabba bruna räven – hoppade över den lata hunden';
        $channel = array();
        $channel['description'] = $description;
        $this->RequestHandler->renderAs($this, 'xml');
        $this->set([
            'channel' => $channel,
        ]);
        $this->set('_serialize', ['channel']);
    }

### What happened

> Warning (2): SimpleXMLElement::__construct(): Entity: line 4: parser error : PCDATA invalid Char value 15 [CORE/src/Utility/Xml.php, line 243]
> Warning (2): SimpleXMLElement::__construct() [<a href='https://secure.php.net/simplexmlelement.construct'>simplexmlelement.construct</a>]:     &lt;description&gt;Den snabba bruna räven – hoppade över den lata hunden&lt;/des [CORE/src/Utility/Xml.php, line 243]
> Warning (2): SimpleXMLElement::__construct() [<a href='https://secure.php.net/simplexmlelement.construct'>simplexmlelement.construct</a>]:                                          ^ [CORE/src/Utility/Xml.php, line 243]

### What you expected to happen

    <?xml version="1.0" encoding="UTF-8"?>
    <response>
      <channel>
        <description>Den snabba bruna räven  – hoppade över den lata hunden</description>
      </channel>
    </response>

### What fixed the problem

    public function cdata() {
        $description = 'Den snabba bruna räven – hoppade över den lata hunden';
        //
        $description = preg_replace ('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', ' ', $description);
        //
        $channel = array();
        $channel['description'] = $description;
        $this->RequestHandler->renderAs($this, 'xml');
        $this->set([
            'channel' => $channel,
        ]);
        $this->set('_serialize', ['channel']);
    }

[source](https://stackoverflow.com/a/12265956)

**Comment by markstory** [comment]
Are you expecting CakePHP to handle filtering out invalid UTF8 bytes?

**Comment by mehov** [comment]
> Are you expecting CakePHP to handle filtering out invalid UTF8 bytes?

I don't know, to be honest. This could actually be one of those cases where framework should not have to fix things out of the box, unless explicitly requested. This is your call.

I know, however, that I've been googling *[cakephp "parser error : PCDATA invalid Char value"](https://www.google.com/search?q=cakephp+%22parser+error+:+PCDATA+invalid+Char+value%22)* on that day, and before that I visited

- [Request & Response Objects - 3.8 - CakePHP Cookbook](https://book.cakephp.org/3.0/en/controllers/request-response.html)
- [Xml - 3.8 - CakePHP Cookbook](https://book.cakephp.org/3.0/en/core-libraries/xml.html)

Knowing the above situation may happen to someone else, and putting the information somewhere on those pages upfront may help future Googlers.

Again, this is your call. This issue comes up in Google search now anyway :)
