### ISSUE TITLE
Database column names containing utf-8 chars (ä) are quoted incorrectly

### ISSUE THREAD

**Issue by benjaminpick** [cakephp/cakephp#12452]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: Apache, MySQL

### What you did

I am creating a connector to a live database which has "creative" column names such as `Reservierungsbestätigung Datum` (containing spaces and Umlauts and I can't change it). 

In my configuration, `quoteIdentifiers` is enabled. 

### What happened
The Database method `quoteIdentifier()` escapes
```
 Reservierungsbestätigung Datum
``` 
to 

```
`Reservierungsbest`ätigung Datum
```
which understably raises an SQL error as soon as the query executes. This is because the regexes use \w as character class.

### What you expected to happen
I hoped the regexes would be more tolerant, as AFAIK only `.` and ` ` (space) are symbols relevant to the query parsing.

### Suggestion
If we add 'u' as modifier to the concerned regexes, it would include these Umlaut chars as well, while still excluding any special chars.

This regex-change might break compatibility (although I can't come up with good examples where this behavior would be used on purpose). Shall I write a PR for this?

Similar: #12079 (spaces in column name)

**Comment by benjaminpick** [comment]
(Fortunately, I do not need the columns containing the UTF-8 chars so if this can't be solved, I can specify all columns that I do need and the query still runs correctly.)

**Comment by markstory** [comment]
Could you send a pull request with the changes that make identifier quoting work for your schema?

**Comment by markstory** [comment]
Closing as a pull request is open now.
