### ISSUE TITLE
3.7 - Deprecate all `Email` methods which are wrappers for `ViewBuilder` methods 

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12458]
`Email` class is humongous and methods like `setTemplate()`, `setLayout()`, `setTheme()`, `setHelpers()` etc. and their corresponding getters unnecessarily add to it's API surface area.

Deprecating these methods will allow us to drop them in 4.0 and make the class leaner. Devs can use the view builder directly to get/set all view related options/values.

**Comment by markstory** [comment]
I think that's reasonable and fits in with some of the issues @burzum has raised about Email's wideness in the past.

**Comment by ADmad** [comment]
All right, I'll make a PR.

**Comment by cleptric** [comment]
Can we at least have one class, called whatever we like, that proxies all methods, to keep a similar API we have atm?

**Comment by ADmad** [comment]
@cleptric Why?

**Comment by cleptric** [comment]
Because i think it's easy to use 🙂

**Comment by cleptric** [comment]
The added example above would then loose the posibility to chain the method calls.

**Comment by cleptric** [comment]
```
$whateverClass
    ->setTo()
    ->setSubject()
    ->setViewVars()
    ->send()
```
would become
```
$email
    ->setTo()
    ->setSubject();
$email->viewBuilder()->setViewVars();
$email->send();

```

**Comment by ADmad** [comment]
`setViewVars()` is not a wrapper for view builder method :slightly_smiling_face: .

Regardless you can do following if you want to keep the chaining:

```
$whateverClass
    ->setTo()
    ->setSubject()
    ->setProfile([
        'template' => 'foo',
        'theme' => 'bar',
        'helpers' => [..],
    ])
    ->send();
```

**Comment by saeideng** [comment]
I'm :+1:  with a  viewBuilder (same methods )  for all cases  view/cell/helper/controller/email/....

**Comment by ADmad** [comment]
Closing as PR is open.

**Comment by burzum** [comment]
> Can we at least have one class, called whatever we like, that proxies all methods, to keep a similar API we have atm?

@cleptric switch to Laravel or write your own facade class. :) But the underlying tight coupled mess of the email class should be refactored ASAP. And there is more code like this in the whole framework.
