### ISSUE TITLE
Task Tests fails with TypeError 

### ISSUE THREAD

**Issue by deanoj** [cakephp/cakephp#12469]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: Apache2, windows, PHP7.2

### What you did
I baked a new Task - i.e. FooTask. I then tried to run the generated Test for the Task.

### What happened
The tests failed with a TypeError:

TypeError : Argument 2 passed to Mock_FooTask_e45fd04b::modelFactory() must be callable, array given ...

### What you expected to happen
I would expect the test to run without a TypeError

Additional, changing a couple of lines of code in cakephp\src\Console\Shell.php seemed to fix the immediate issue:

Existing - line 191
--------

`$this->modelFactory('Table', [$this->getTableLocator(), 'get']);`

Fixed code:
-------------

`$this->modelFactory('Table', function () {
            return $this->getTableLocator();
        });`

**Comment by markstory** [comment]
This issue was moved to cakephp/bake#459
