### ISSUE TITLE
table names with schema

### ISSUE THREAD

**Issue by ccriem** [cakephp/cakephp#12467]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 5.6.4
* Platform and Target: Linux SMP Debian 4.9, 10.1-MariaDB

### What you did

When changing following line in function describe() ( Database/Schema/Collection.php:93 ):

            list($config['schema'], $name) = explode('.', $name);

to 

            list($config['schema'], $tblName) = explode('.', $name);

table names with "schema-dot-table" notation will work as expected, p.ex:

>>> $tbl = 'information_schema.TABLES';
>>> $tbls = \Cake\ORM\TableRegistry::get( $tbl, [ 'table' => $tbl ] );
>>> echo $tbls->find()->count();

so I wonder if overwriting variable $name in this place when setting schema name, is it a feature or bug?

**Comment by markstory** [comment]
I'm pretty sure overwriting `$name` is intentional as it allows table classes to play nicely with SQLServer and postgres databases that use multiple 'schemas'. This behavior was introduced in #4340
