### ISSUE TITLE
Can't change the Paginator-sort() direction

### ISSUE THREAD

**Issue by heohni** [cakephp/cakephp#12476]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6
* Platform and Target: Apache Server

### What you did
in my controller:
`public $paginate = [
        'maxLimit' => 8,
        'order' => ['obj_internet_upload' => 'desc']
    ];`

using the Paginator-Sort link
`echo $this->Paginator->sort('obj_preis', __('Preis sortierenH'), ['escape' => false]);`
for debug reason I check also
`debug($this->Paginator->sortKey());
debug($this->Paginator->sortDir());`

### What happened
By default:
sortKey = null
sortDir = asc

When I press the sort link it will add to my url
`sort=obj_preis&direction=asc`

After reload of the page I see from the debug:
sortKey = obj_preis
sortDir = asc

When I press again the link I see again
sortKey = obj_preis
sortDir = asc
and the url contains
`sort=obj_preis&direction=desc`

### What you expected to happen
For my opinion it seems like Cake always keep the direction=asc and never allows to change it.
Therefore the sort link creates only direction=desc links.

**Comment by markstory** [comment]
> For my opinion it seems like Cake always keep the direction=asc and never allows to change it.

There are tests that demonstrate otherwise. See https://github.com/cakephp/cakephp/blob/6e96b4e839ba7dfe5b29a3f3a49a0838261d7be2/tests/TestCase/View/Helper/PaginatorHelperTest.php#L161-L194

Have you looked into `debug($this->request->getParam('paging');`? PaginatorHelper uses the direction set there to create the opposite direction when the field/column matches.

**Comment by heohni** [comment]
in my controller:
`public $paginate = [
        'maxLimit' => 8,
        'order' => ['Gesamtobjekt.obj_internet_upload' => 'desc']
    ];`

if I do this in my search.ctp:
`$this->Paginator->options([
    'url' => [
        'controller' => $paginatorUrl,
        'cat_id' => $catValue,
        'reg_id' => $locValue,
        'priceMin' => $priceValueMin,
        'priceMax' => $priceValueMax,
        'ref' => $ref
    ]
]);`
`debug($this->request->getParam('paging'));`
`echo $this->Paginator->sort('obj_preis', __('Preis sortierenH'), ['escape' => false]);`

I get on first page load
`'sort' => 'Gesamtobjekt.obj_internet_upload',
		'direction' => false,
		'limit' => null,
		'sortDefault' => 'Gesamtobjekt.obj_internet_upload',
		'directionDefault' => false,`

If I press  the sort link, I get 
`?sort=obj_preis&direction=asc` attached to the url and the debug look like
`'sort' => 'obj_preis',
		'direction' => false,
		'limit' => null,
		'sortDefault' => 'Gesamtobjekt.obj_internet_upload',
		'directionDefault' => 'desc',`

on any further click on the sort link, I always get
`?sort=obj_preis&direction=desc&cat_id=1`
and the debig returns always
`sort' => 'obj_preis',
		'direction' => false,
		'limit' => null,
		'sortDefault' => 'Gesamtobjekt.obj_internet_upload',
		'directionDefault' => 'desc',`

Can I kindly as how to use the PaginatorHelperTest?
I never used something like this before.

**Comment by heohni** [comment]
Hi Mark,
I have never gained experience with phpunit.
I added 
`'order' => ['Gesamtobjekt.obj_internet_upload'`
and 
`$this->Paginator->sort('Gesamtobjekt.obj_preis',`
but this is not helping in "influencing" the direction.

The search works fine, the results are right, the sql log shows the right results, when I manually add 

> ?sort=obj_preis&direction=desc
or
> ?sort=obj_preis&direction=asc

My point is that the $this->Paginator->sort link always gives the "direction=desc" as the direction never gets changed (for the eyes of the Paginator)

**Comment by heohni** [comment]
Ok guys I found the bug! As often it sits in between the own ears :-/
The problem is home made, the database field is in capital letters (bad, I know...)
with

> $this->Paginator->sort('OBJ_PREIS', __('Preis sortieren'), ['escape' => false]);

it works as it should!
I am very sorry for that!!
Thanks so much for your time involved!
