### ISSUE TITLE
RFC - Implement PSR16 support in Cache

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#12483]
The PSR16 interfaces define a simpler Cache interface that would allow CakePHP to leverage solutions from outside of CakePHP in the longer term if we adopt the interfaces. Projects like [php-cache](https://www.php-cache.com/en/latest/) would allow us to offload cache adapters for redis, memcached, and allow users to leverage new cache backends like mongo or couchbase.

The current `Cake\CacheEngine` interface is not compatible with the PSR16 interface primarily because of the differences in the `clear()` method. This limitation can be overcome by using an adapter to bridge between the two interfaces and a new dependency injection container friendly frontend method.

## Goals

The goals of the following changes are:

1. Adopt more broadly accepted interfaces.
2. Be able to leverage projects like php-cache to provide caching adapters we   do not already provide.
3. Add PSR16 interface support so that applications using libraries that require   PSR16 caching don't need to pull in yet another caching library.
4. Prepare CakePHP caching to be compatible with a DI patterns.

## PSR16 Adapter Bridge

A new PSR16 compliant 'bridge' adapter would be added to CakePHP. This bridge would implement the PSR16 interface and also expose CakePHP specific features like 'groups'. This approach differs from the one attempted in #11848 as it has less risk to backwards compatibility because existing adapter classes would not be significantly altered.

### TTL implementation

The PSR16 interface includes a `$ttl` argument on `set()`. Our current
implementation relies on each cache engine having only 1 TTL value configured
when the engine is created. To accommodate the PSR16 requirements the bridge
adapter could use the following pseudo-code:

```php
function set($key, $value, $ttl = null)
{
    $restore = null;
    if ($ttl !== null) {
        $restore = $this->adapter->getConfig('duration');
        $this->adapter->setConfig('duration', $ttl);
    }
    try {
        return $this->adapter->write($key, $value);
    } finally {
        if ($restore !== null) {
            $this->adapter->setConfig('duration', $ttl);
        }
    }
}
```

## Cache::pool to be added

The new bridge class would be used by `Cache` internally, and `Cache::engine()` would be deprecated in 3.7. The new PSR16 wrapper would be exposed by `Cache::pool($name)`. This new method would act similarly to `engine()`. Instead of returning the raw CakePHP cache engine, it would return the adapter bridge. Usage would look like:

```php
// Write
$item = Cache::pool('fast')->set($key, $value, $ttl);

// Get
$item = Cache::pool('fast')->get($key);
```

Internally `Cache` would be updated to use `pool` instead of `engine` to reduce the amount of churn in 4.0 and attempt to front-load regression testing into 3.7-betas.

## Dependency Injection Compatibility

In 4.x with all Cache engines being PSR16 implementations, the `CacheRegistry` can be used as a factory to define named services that can be injected elsewhere. As an example using PHP-Di as a reference:

```php
// in a service definition file
return [
    // Inject all cache backends into a class.
    // `CacheRegistry` could be a service defined by CakePHP.
    'MyThing' => DI\autowire(),

    // Get a specific cache adapter.
    'cache.fast' => function(CacheRegistry $registry) {
        return $registry->getPool('fast');
    }
];
```

Using `CacheRegistry` would not be required as individual cache adapters could be registered individually.

## Deprecations for 3.7

* `Cache::engine()` would be removed in 4.0
* `Cake\Cache\CacheEngineInterface` would be removed in 4.0 and replaced with  a smaller interface that add group related methods to PSR16 cache engines.

## Breaking changes for 4.x

In 4.0 we would be able to drop the methods defined in `CacheEngine` that overlap with PSR16 functionality. We would also be able to redefine the cache adapters to implement the PSR16 interface methods instead of our own variants.

**Comment by markstory** [comment]
@burzum The backwards compatibility issues were why I wanted to try an intermediate adapter instead of modifying the existing engine classes.

**Comment by lorenzo** [comment]
Would we still keep our own stuff like the cache groups implementation?

**Comment by markstory** [comment]
@lorenzo Yes. Other PSR16 implementations do not support 'groups' or 'tags'. However, there are extensions to PSR6 that do support 'tagging'. There is a precursor to a PSR in [taggable-cache](https://github.com/php-cache/tag-interop), but it builds on the PSR6 interfaces which we've not discussed implementing thus far.

**Comment by ravage84** [comment]
> The current `CacheInterface` ...

@markstory I think you meant "`Cache` interface" in this case. Am I wrong?

**Comment by markstory** [comment]
@ravage84 `Cake\CacheEngine`. For some reason I thought there was a interface, but there isnt' 😕

**Comment by burzum** [comment]
@markstory then we should add one 😄

**Comment by markstory** [comment]
Closing as this is done for 3.7
