### ISSUE TITLE
3.6.10 Missing custom http headers set via $response->withHeader() on NotFoundException

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12481]
This is a:

* [x] bug

* CakePHP Version: 3.6.10
* Platform and Target: docker-compose 3.1 / nginx

### What you did

Creating a file based mini cms:

```php
if ((bool)$metaInfo->get('is_published', true) === false) {
    // Set header to be inspected via browser inspectors or other tools
    $this->response = $this->response->withHeader('X-Route-Is-Published', 'false');
    // Throw 404 exception
    throw new NotFoundException(sprintf(
        '"%s" for locale "%s" is not published.',
        $routes[$locale][$requestPath]['source_base'],
        $locale
    ));
}
```

### What happened

The NotFoundException is rendering correct but the custom http header is missing. Custom headers are passed through to the HTTP client (browser) just fine if no exception is thrown.

### What you expected to happen

The custom http header to be kept.

**Comment by ADmad** [comment]
```php
$exception = new NotFoundException();
$exception->responseHeader('X-Route-Is-Published', 'false');
throw $exception;
```

**Comment by inoas** [comment]
@Admad thank you. I will tinker around and if things work out well cross check docs and push a PR to the docs in case it's not in there.
