### ISSUE TITLE
Validating dependent fields/groups in Form

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#12484]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7
* Platform and Target: linux

In custom implementation of modelless form (`\App\Form`), I'd like to validate using this logic

  - If all of the fields in group (not entire form) are empty, allow all to be empty
  - If one of the fields in group (not entiry form) is not-empty, require not-empty for all fields in said group

Setting the validation on every field seems little bit non-elegant to me.

This is sample code, with "redundant" setting of validator rules:
```php
<?php

namespace App\Form;

use Cake\Event\Event;
use Cake\Form\Form;
use Cake\Form\Schema;
use Cake\Validation\Validator;

class ValidatedModellessForm extends Form
{
    protected $groupEmptyAllOrNone = ['field1', 'field2', 'field3'];

    public function buildValidator(Event $event, Validator $validator, $name)
    {
        parent::buildValidator($event, $validator, $name);

        foreach ($this->groupEmptyAllOrNone as $field) {
            $validator->allowEmpty($field, function ($context) {
                return $this->groupEmptyAllOrNone($context);
            }, 'This group fields must be filled in completely or not at all');
        }
    }

    public function groupEmptyAllOrNone($context = null)
    {
        if (empty($context) || empty($context['data'])) return true;
        $oneEmpty = false;
        $allEmpty = true;
        foreach ($this->groupEmptyAllOrNone as $field) {
            if (empty($context['data'][$field])) {
                $oneEmpty = true;
            } else {
                $allEmpty = false;
            }
        }
        return $allEmpty || !$oneEmpty;
    }
?>
```

Is it possible to do this in more elegant manner? Thank you

**Comment by markstory** [comment]
Right now there isn't a simple way to do this. How would you do the same task in an ORM backed model?

**Comment by markstory** [comment]
Ok. I was wondering if you used [application rules](https://book.cakephp.org/3.0/en/orm/validation.html#applying-application-rules) in your ORM entities, as they fit this use-case pretty well and would be straightforward to add to Forms too.
