### ISSUE TITLE
Cake PHP Schema list table getting views too

### ISSUE THREAD

**Issue by AndreLZGava** [cakephp/cakephp#12482]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5
* Platform and Target: Ubuntu 16.04, Postgres

### What you did
ConnectionManager::get('default')->schemaCollection()->listTables();
Ive used this code, this must return just tables, but its returning tables and views

### What happened
Its returning my views too, then It breaks my code forward because my views has 0 columns;

### What you expected to happen
Bring just tables, If need to list views develop another function to it;

**Comment by AndreLZGava** [comment]
Instead generate this 
'SELECT table_name as name FROM information_schema.tables WHERE table_schema = ? ORDER BY name' 
sql inside Collection must generate this:
'SELECT table_name as name FROM information_schema.tables WHERE table_schema = ? and TABLE_TYPE='BASE TABLE' ORDER BY name' ?

**Comment by markstory** [comment]
Getting views is a 'feature' not a 'bug'. Removing reflection for views would break existing applications.

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
