### ISSUE TITLE
Allow marking shell options as required

### ISSUE THREAD

**Issue by AD7six** [cakephp/cakephp#12498]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: N/A

### What you did
It is useful sometimes to specify cli options as required, but at the moment we cant. 

This is most relevant If a cli has multiple required inputs - in this case it is currently only possible to enforce via the command parser by using (positional) arguments. 

Example, consider a shell with this options parser:

```
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();

        foreach(range(1,3) as $i) {
            $parser->addArgument("thing$i", [
                'help' => "Required thing $i",
                'required' => true
            ]);
        }

        return $parser;
    }
```

```
-> bin/cake my-cli --help
Usage:
cake my_cli [-h] [-q] [-v] <thing1> <thing2> <thing3>

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.

Arguments:

thing1  Required thing 1
thing2  Required thing 2
thing3  Required thing 3

-> bin/cake my-cli
Error: Missing required arguments. thing1 is required.
```
Although helpful, having to specify args in order is sometimes pretty awkward.

It's be much easier with this example to create a parser like so:

```
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();

        foreach(range(1,10) as $i) {
            $parser->addOption("thing$i", [ <---- changed
                'help' => "Required thing $i",
                'required' => true <---- ignored 
            ]);
        }

        return $parser;
    }
```

But that only achieves the syntax I'm looking for:

```
-> cake/bin/cake my-cli --help
Usage:
cake my_cli [-h] [-q] [-v] [--thing1] [--thing2] [--thing3]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
--thing1       Required thing 1
--thing2       Required thing 2
--thing3       Required thing 3
```
It does not enforce `required` as options are, according to the Shell class, always optional:

```
-> cake/bin/cake my-cli
Hello now going to try and do something in the main method and fail because required things are missing...
```

So, the ask here is simply to allow marking options required.

**Comment by markstory** [comment]
If an option is required, is it really 'optional' :smile: In all seriousness this seems reasonable.

**Comment by josegonzalez** [comment]
We could rename them to Command Flags?

**Comment by markstory** [comment]
Flags would be a better name for required/optional values.
