### ISSUE TITLE
Query::__call does not support findBy* magic method syntax

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#12493]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: na

### What you did
In a model

````php
$this->find('all')->findByTitle('First title');
````

### What happened
I got `BadMethodCallException with message 'Unknown method "findByTitle"'`

### What you expected to happen
I would except to get the same query object than with the following

````php
$this->findByTitle('First title')->find('all');
````

If it is the expected behaviour than I think it should be mentioned in the cookbook.

**Comment by rrd108** [comment]
typo fixed

**Comment by markstory** [comment]
This is a limitation in the current implementation of magic finders. I can update the documentation as `QueryTrait::__call` has never offered `findByX` functionality, but could in the future given some work.
