### ISSUE TITLE
Using setTemplates with a config file name does not appear to work as documented

### ISSUE THREAD

**Issue by acjbizar** [cakephp/cakephp#12490]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: XAMPP

### What you did
In `config\dehtml.php` I return an array of templates. Example:

    return [
        'foo' => '<bar>'
    ];

Then, in `src\Templates\Layout\default.ctp` I want to apply these templates, so I add:

    $this->Html->setTemplates('dehtml');

### What happened
`Argument 1 passed to Cake\View\Helper\HtmlHelper::setTemplates() must be of the type array, string given` and `Error in: ROOT\vendor\cakephp\cakephp\src\View\StringTemplateTrait.php, line 41`. Which makes sense, since that **does** explicitly ask for an array.

### What you expected to happen
I would expect the templates array to be populated with the array that is returned in the file I defined. This behavior is described by ¶[Changing the Tags Output by HtmlHelper](https://book.cakephp.org/3.0/en/views/helpers/html.html#changing-the-tags-output-by-htmlhelper) in the Cookbook (unless I’m reading it wrong).

Of course, I could just define the templates array in the template, but the twist is that there are actually a ton of other templates in which they will be required.

**Comment by dereuromark** [comment]
You can also look into the source code.
That would clarify the behavior:

> string|null|array $templates null or string allow reading templates. An array
allows templates to be added.

was the combined one, the setter now only has array for adding, of course.

The example in the docs is wrong.
That must be getTemplates($string).

**Comment by acjbizar** [comment]
Thanks for your reply, @dereuromark.

I _did_ look into the source code and try `$this->Html->getTemplates('dehtml');`, but that didn’t appear to do anything, so I figured I’d really need the setter.

Am I missing something?

**Comment by markstory** [comment]
It looks like the documentation is just wrong. Both `templates()` and `setTemplates()` do not accept a string for a filename. You can only provide a config file when calling `FormHelper::create()` via the `templates` option.

If you want to dynamically load templates in the layout you need to use `Form->templater()->load('dehtml')`.

I'll get the documentation updated.
