### ISSUE TITLE
[RFC] I18n for routing

### ISSUE THREAD

**Issue by jyrkidn** [cakephp/cakephp#12508]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

## Why would this be useful?

This would be very helpful for multi-language websites. Other frameworks already implemented. Here is how [Symfony](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing
) did this.

Now you have to duplicate the `$router->connect()` to achieve this. Imagine there are 10 languages available.

## How it (could) work

`$router->connect()` now expects a string as first parameter. It would already be helpful if we could pass an array as first parameter and then parse it with a custom route class.

```php
$router->connect('/', ['controller' => 'Articles', 'action' => 'index'])
```
```php
$router->connect(
    [
        'en' => '/articles',
        'nl' => '/artikelen'
    ],
    ['controller' => 'Articles', 'action' => 'index']
)
```

**Comment by markstory** [comment]
We could generate multiple routes internally based on the array template. I have a few questions on how this would interact with other features:

* How would you see this addition working with names routes?
* Would the router be responsible for checking that each locale has the same number and names parameters

**Comment by jyrkidn** [comment]
* For named routes the current or given locale will make the name match a route
  * E.g. `Router::url(['_name' => 'articles']);` (this uses then `I18n::getLocale()` internally) or `Router::url(['_name' => 'login', 'locale' => 'nl']);`
  * Internally the name could be `articles.en`
* No, checking if each locale has the same number and names of parameters would make it to complicated.
* It would be good if the locale is visible in the parsed parameters and required to match (see first bullet)

**Comment by markstory** [comment]
Do you think we could use the current request's locale parameter instead of adding coupling  between the i18n and routing packages?

**Comment by jyrkidn** [comment]
Do you mean from the `Accept-Language` request header? 
We make sometimes a mapping for all English locales to `en` instead of handling `en-GB`, `en-US` etc. separately (via custom middleware that extends the LocaleSelectorMiddleware), I think that's more difficult when the locale from the current request is used.

**Comment by markstory** [comment]
> Do you mean from the Accept-Language request header?

Sorry I meant `request->getParam('locale')`. Using when matching/generating URL strings would allow the router to not be coupled to `I18n::getLocale()` as we're trying to avoid adding more inter-package dependencies.

**Comment by jyrkidn** [comment]
Using `request->getParam('locale')` is good for me.

**Comment by robertpustulka** [comment]
Can you have `$routes->connect(__d('routes', '/articles'), 'Articles::index')` and keep your translations in a `routes.po` file?

**Comment by jyrkidn** [comment]
@robertpustulka that was also an option for us, but was a no go for longer url's + translations are editable in our cms and that would cause to much hassle for adding redirects when a translation in routes is changed (blame our marketing department for that).

```php
$routes->connect('/:locale/' . __d('routes', 'category') . '/:categorySlug/'  . __d('routes', 'article') . '/:slug', 'Articles::index');
```
vs
```php
$routes->connect('/:locale/category/:categorySlug/article/:slug', 'Articles::index');
```

**Comment by ADmad** [comment]
How is your proposal going to help with routes like

```
$routes->connect('/:locale/category/:categorySlug/article/:slug', 'Articles::index');
```
