### ISSUE TITLE
BodyParserMiddleware error

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#12513]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.9
* Platform and Target: Windows, using Xampp (localhost). PHP 7.1

### What you did
1) On My application, when an user does the login, I encode the password on user side, and decode it on server side.

Right now, when I decode the password, I use the $this->request->data['password'], but this field is deprecated.

So, to fix this, I've started to test out the BodyParserMiddleware. I've added the following code, which I took from https://book.cakephp.org/3.0/en/controllers/middleware.html#body-parser-middleware, but with adaptations ('application/x-www-form-urlencoded' instead of json)

```
$bodies = new BodyParserMiddleware();
$bodies->addParser(['application/x-www-form-urlencoded'], function ($body, $request) {
     // Use a CSV parsing library.
     //Check if Password field exists
     //If exists, $password = $this->decodePassword()
     return $body;
});
```

Yet, it gives me a cake error.

2) If I remove the parameter $request from the code. It no longer gives that error. But, it starts giving another type of error:  'Bad Request ', from BodyParserMiddlware:146

Not sure if 2 is related to number 1 error, or just me not thinking correctly

### What happened
Got the following error:

Too few arguments to function App\Application::App\{closure}(), 1 passed in (...)\vendor\cakephp\cakephp\src\Http\Middleware\BodyParserMiddleware.php on line 144 and exactly 2 expected 

### What you expected to happen
Nothing at all, but no error at least

**Comment by garas** [comment]
You don't need to parse 'application/x-www-form-urlencoded' data, it is already handled by PHP (`$_POST`) and is accessible with `$this->request->getData('password')` in CakePHP.

If you wish to decode password in middleware, use [custom middleware](https://book.cakephp.org/3.0/en/controllers/middleware.html#creating-middleware) with
```php
$password = $this->decodePassword($request->getData('password'));
$request = $request->withData('password', $password);
return $next($request, $response);
```

**Comment by ADmad** [comment]
Besides what @garas said a middleware seems to be the wrong place to decode a password in my opinion. It should be done in a custom password hasher.

Closing as there's no issue here, just misunderstanding about how middlewares work. Use one of the help forum if you still have questions.
