### ISSUE TITLE
Saving hasMany associations doesn't allow orphan records to be created

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#12517]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.17

I have a model that has the Tree behavior. I call the save method on this model with an entity and its children. It's a hasMany association (parent -< children) using the ```replace``` saveStrategy.

When adding entities to this association, the Tree (the ```lft``` and ```rght``` fields) is updated correctly, but not when removing them.

I've looked at the code that saves this association (it has to write the ```parent_id``` field for the children) and it adds entities using the ```save``` method but it removes them with the ```updateAll``` and ```deleteAll``` methods. Thus, adding children calls the required methods in the Tree behavior but removing them does not.

It seems strange that it behaves differently when adding than replacing.  Do you think it's possible switching to the ```save``` method for both cases?

Thanks.

**Comment by markstory** [comment]
Saving and replacing are different modes, they are supposed to work differently. I agree that the tree fields should not become incorrect when using replace mode. Have you tried enabling `cascadeCallbacks` in your association?

**Comment by berarma** [comment]
No, this doesn't work. I've worked around it by first deleting the removed associations and then saving with the append strategy.

**Comment by markstory** [comment]
We use updateAll and deleteAll when removing association data because it is more efficient. I am happy to hear you found a workaround but if possible we should fix this behavior so that a workaround is not required.

**Comment by berarma** [comment]
Sure.

Should we add a new option since cascadeCallbacks is for cascade deletes?

We can add a new option to turn callbacks on for delete but then we'll have an option for cascaded deletes and another one for association deletes. Would it be better in the association settings or in the query itself?

It's still a bit weird we have callbacks on inserts but not on deletes in the same operation though the reason is clear.

**Comment by berarma** [comment]
I tried just with the cascadeCallbacks option on and it did nothing, I should have used the dependent option too.

Anyway, that code would delete the entities in the association, while I just want to orphan them. Setting both options would not only turn callbacks on but it would also switch the behavior from orphaning to deleting. I can't delete and create new entities for this association.

I'm sorry, I said I worked around it by deleting the associations while I wanted to say that I unlinked them before saving.

Deleting them with callbacks is possible but orphaning them with callbacks is not.

**Comment by markstory** [comment]
> Deleting them with callbacks is possible but orphaning them with callbacks is not.

Yes we don't have a mode/configuration that will orphan associated records yet.

**Comment by berarma** [comment]
> Yes we don't have a mode/configuration that will orphan associated records yet.

I think we have, it's just that it doesn't use callbacks and there's no option to turn callbacks on. I think it's done here:
https://github.com/cakephp/cakephp/blob/98d559c6071555bba26fdae8fc9c87acfb169eca/src/ORM/Association/HasMany.php#L540-L542

**Comment by MertDalbudak** [comment]
Is this fixed in the newer version?

**Comment by markstory** [comment]
@MertDalbudak No, this issue is still open.
