### ISSUE TITLE
CakePHP Mailer does not allow multiple headers of the same name

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#12523]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.x

### What you did
```php
->addHeaders(['o:tag' => $newsletter->get('id')])
->addHeaders(['o:tag' => 'swissmailer'])
```

### What happened
Ending up with just `o:tag: swissmailer`

Duplicate headers are allowed for specific types and third party headers. See https://stackoverflow.com/questions/18039142/email-legitimate-duplicate-email-header-keys-with-mutually-exclusive-values

### What you expected to happen
Getting all the headers in the email.

**Comment by markstory** [comment]
Changing the existing behavior of `addHeaders()` could break existing applications that rely on the overwrite as a 'feature'. We would be better off adding a new method. For responses we have `withHeader()` and `withAddedHeader()`. Does anyone have a suggestion for a new method name on Email?

**Comment by ravage84** [comment]
How about ``withAdditionalHeader()`` (preferred) or ``withAnotherHeader()``?

**Comment by garas** [comment]
`Email` is mutable object, and `with*()` method would suggest instance is immutable and returns another instance like `Response`.

I would prefer add parameter `$replace = true` similarly to PHP [header()](https://php.net/manual/en/function.header.php)

**Comment by markstory** [comment]
@garas Modal flags on methods are not an API pattern I'm a huge fan of. It requires memorizing the API or looking at the documentation to understand what the flag does.

**Comment by josegonzalez** [comment]
Break it for 4.x?

**Comment by JoshuaLuckers** [comment]
`addHeadersAndMergeRecursive()`

**Comment by markstory** [comment]
Adding a new method for the append operation is my preference as it requires the least churn overall.

**Comment by ADmad** [comment]
One way to solve this without any API changes would be allow providing the value as array:

```php
->addHeaders(['o:tag' => [$newsletter->get('id')]])
```

There subsequent call like
```php
->addHeaders(['o:tag' => ['swissmailer'])
```
 would merge the values for that particular header.

`addHeaders()` method would be updated to use `Hash::merge()` instead of `array_merge()` and `AbstractTransport::_headersToString()` updated to account for values being an array.

**Comment by markstory** [comment]
@admad I like that approach over breaking the existing behavior.
