### ISSUE TITLE
Get recursive associations

### ISSUE THREAD

**Issue by MertDalbudak** [cakephp/cakephp#12524]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Linux Ubuntu PHP 7.0

### What you did
```
$attribute = $this->Attributes->get($id, [
     'contain' => ['AttributeCategories', 'Products', 'Types', 'Childs', 'Parents']
]);
```
I want to get all relation from an element. I do get these but I want to iterate till there is no relation. 
Parents parent and so on.
Childs child and so on.

An attribute can have an attribute child or parent.

Table:

**Attributes**
unique_id
...
**Attribute_Attributes**
parent_id
child_id

### What happened
This would work but only in depth of 3 for parents:
```
$attribute = $this->Attributes->get($id, [
     'contain' => ['AttributeCategories', 'Products', 'Types', 'Childs', 'Childs.'Childs'', 'Parents', 'Parents.parents', 'Parents.parents', 'Parents.parents.parents']
]);
```

I tried to solve using `find()` but I couldn't see any difference between them.
```
$attribute = $this->Attributes->find('all', ['recursive'=> 2])
    ->contain(['AttributeCategories', 'Products', 'Types', 'Childs', 'Parents'])
    ->where(['Attributes.unique_id =' => $id])->all();
```

This is what I want to achive: https://pastebin.com/Y4pyrU0c
This is what I get: https://pastebin.com/kPs2Vgb3

**Comment by markstory** [comment]
Do you want the ORM to recursively load parent/child relations until it finds a missing relation?

**Comment by garas** [comment]
Did you tried `->find('threaded')`?

Also, in CakePHP 3, `['recursive'=> 2]` was removed and was replaced with `contains()`

**Comment by MertDalbudak** [comment]
@markstory yes this is exactly what I want 2 archive.

@garas, no I didn't tried that out.

**Comment by markstory** [comment]
@MertDalbudak you should try find(threaded) as @far as recommended. It is the only way we have to traverse parent/child associations recursively.

**Comment by MertDalbudak** [comment]
I solved it by using a recrusive function:
```
private function findAttribute($attributes, $id){
    for($i = 0; $i < count($attributes); $i++){  // GO THROUGH ALL CHILDREN
        if($attributes[$i]->unique_id == $id) // $id FOUND?
            return $attributes[$i]; // FOUND AND RETURN
        else{
            if(count($attributes[$i]->children) > 0){ // DOES THE CURRENT ATTRIBUTE HAVE CHILDREN
                $val = $this->findAttribute($attributes[$i]->children, $id); // CHECK CHILDREN OF CURRENT ATTRIBUTE
                if($val != null)
                    return $val;
            }
        }
    }
    return null; // $id NOT FOUND
}
```
If there is a more elegant solution let me know.
