### ISSUE TITLE
RouteBuilder::connect() should not try to override 'action' key defined in RouteBuilder::scope()

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#12535]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11

### What you did
In routes.php:
```PHP
$routes->scope('/packagePrice',['controller'=>'Checkout','action'=>'packagePrice'],function (RouteBuilder $routes) {
	$routes->connect('/shared', ['dynamic_package_type'=>'shared']);
	$routes->connect('/exclusive', ['dynamic_package_type'=>'exclusive']);
	$routes->connect('/geo', ['dynamic_package_type'=>'geo']);
	$routes->connect('/:id', [], ['id'=>'[0-9]*']);
});
```
### What happened
I get following error:
```
BadMethodCallException
You cannot define routes that conflict with the scope.
Scope had action = packagePrice, while route had action = index
```

### What you expected to happen
Since ```action``` key is already defined inside ```scope```, ```connect``` method should not try to override it with ```['action'=>'index']``` which causes error

**Comment by markstory** [comment]
Looks like we set the action default value too early. This could be moved to `RouteBuilder::_makeRoute` instead.
