### ISSUE TITLE
Enhancement to Collection::last

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#12531]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: PHP 7.2.8 

### What you did
```php
$scriptParts = new \Cake\Collection\Collection($script->parts);
$count = $scriptParts->count();
$finalScriptParts = $scriptParts->take(2, $count - 2);
```

### What happened
I got the last two items of the collection.

### What you would like to happen
I think it would be much easier if `Collection::last()` implemented a single parameter for the number of items to get from the end of the collection.

### Examples
```php
$collection = new Collection(['first', 'second', 'third']);
$lastTwo = $collection->last(2);
// ['second', 'third']

$collection = new Collection(['first', 'second', 'third']);
$tooMany = $collection->last(4);
// ['first', 'second', 'third']
// Or out of range exception perhaps?

$collection = new Collection(['first', 'second', 'third']);
$tooMany = $collection->last();
// ['third']

$collection = new Collection(['first', 'second', 'third']);
$tooMany = $collection->last(-1);
// Out of range exception perhaps?
```

**Comment by markstory** [comment]
How would this work for a collection of unknown size? The current `count()` method has some edge cases with filtered iterators as the count will reflect the unfiltered set.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
