### ISSUE TITLE
input type="date" name="" vs. dateWidget

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#12537]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.6.8

### What you did

```
echo $this->Form->create(null, [
    'type' => 'GET',
    'url' => '/foo/bar',
    'templates' => [
        'inputContainer' => '{{content}}',
        'formGroup' => '{{input}}',
        'dateWidget' => '<input type="date" name="{{name}}"{{attrs}}/>',
    ],
]);
echo $this->Form->input('created', [
    'type' => 'date',
    'placeholder' => 'Date Created',
    'id' => '_created',
    'class' => 'form-control',
]);
```

### What happened

    <input type="created" name placeholder="Date Created" id class="form-control">

### What you expected to happen

    <input type="created" name="created" placeholder="Date Created" id="_created" class="form-control">

**Comment by markstory** [comment]
You can't replace the `dateWidget` template like that. If you want to create HTML5 datepickers you should use `$this->Form->text('created', ['type' => 'date'])`
