### ISSUE TITLE
Response->withFile( 'download'=>true) different behavior than old ->file()

### ISSUE THREAD

**Issue by djamesfar** [cakephp/cakephp#12544]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10.
* Platform and Target: Apache 2.4.7, MySQL 5.7, Ubuntu 16.04 

### What you did
I upgraded CakePHP from 3.4 to 3.6.10.  Addressing some deprecations, I changed a call from 
`$this->response->file($file->path, ['download' =>  true]);`
to
`$this->response->withFile($file->path, ['download' => true]);`

### What happened
Instead of the file downloading as it did before, we get a blank page.

### What you expected to happen
Expected the force-download of the file as before.

However, with the upgrade, the old syntax still works as expected: the file downloads.  So I changed to the deprecated form.  Obviously in preparation for CakePHP 4 I would like to replace deprecated functions as I go.
Here is the full function:
```
public function downloadXl()
    {
        $this->autoRender = false;
        $output = FILES."Invoice_Summary.xlsx";
        $file = new File($output);
        //force download of file
        if ($file->exists()) {
//            $this->response->withFile($file->path, ['download' => true]); // get a blank page, no download
            $this->response->file($file->path, ['download' => true]);   // this still works with 3.6.10
        }
        return $this->response;
    }
```

**Comment by dereuromark** [comment]
You need to read the updated docs on the immutability of the request and response objects.
As such, all changes are lost without reassignment:

    $this->response = $this->response->withFile();
