### ISSUE TITLE
HttpApplication plugin route loading is broken

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#12557]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11
* Platform and Target: PHP 7.2.8

### What you did
I created my `src/Application.php` file and added this to my `boostrap` method.

`$this->addPlugin('ExitLinks', ['routes' => true]);`

Then I removed the `Plugin::routes()` from my `routes.php` file.

### What happened
I get a Missing Route Exception, because none of my plugins routes are loaded.

### What you expected to happen
I expected my plugin routes to be loaded.

**Comment by markstory** [comment]
Does your Application class extend `BaseApplication` or did you implement the `HttpApplication` interface yourself?

Are your routes currently being loaded from cache?

**Comment by davidyell** [comment]
Yes, my class `Application` extends `Cake\Http\BaseApplication`.
I've cleared my cache with `bin/cake cache clear_all`.

**Comment by markstory** [comment]
Do the following lines of code get run? https://github.com/cakephp/cakephp/blob/509553d2ededb2715a7d32a56ecbed0a5e915c34/src/Routing/Middleware/RoutingMiddleware.php#L110-L114

This where the routing middleware loads plugin routes based on your application implementing the plugin app interface.

**Comment by davidyell** [comment]
I'm on vacation for a week now, but I will check when I'm back.

**Comment by L4suicide** [comment]
> Do the following lines of code get run?
> 
> [cakephp/src/Routing/Middleware/RoutingMiddleware.php](https://github.com/cakephp/cakephp/blob/509553d2ededb2715a7d32a56ecbed0a5e915c34/src/Routing/Middleware/RoutingMiddleware.php#L110-L114)
> 
> Lines 110 to 114 in [509553d](/cakephp/cakephp/commit/509553d2ededb2715a7d32a56ecbed0a5e915c34)
> 
>          if ($this->app instanceof PluginApplicationInterface) { 
>              $this->app->pluginRoutes($builder); 
>          } 
>   
>          return Router::getRouteCollection(); 
> This where the routing middleware loads plugin routes based on your application implementing the plugin app interface.

I have the same issue and it appears that $this->app is not an instanceof PluginApplicationInterface (at least in my case)
I am trying to use admads SocialAuth plugin with 3.6.11

**Comment by ADmad** [comment]
> ..it appears that $this->app is not an instanceof PluginApplicationInterface

`Cake\Http\BaseApplication` implements `PluginApplicationInterface`. So if your `Application` class extends `Cake\Http\BaseApplication` then it would be an instanceof `PluginApplicationInterface`.

**Comment by Iandenh** [comment]
Do you give the pass the current Application to the Router Middleware?
Like so:
```php
->add(new RoutingMiddleware($this));
```

I have manage to reproduce the missing routes when I removed the arguments from the RoutingMiddleware.

In older versions of `cakephp/app` there arguments where not set.

**Comment by L4suicide** [comment]
`
use Cake\Http\BaseApplication;
...
class Application extends BaseApplication
...`

From my Application.php - am I missing something?

**Comment by Iandenh** [comment]
Can you past the content of the `middleware()` method in `Application`?

**Comment by saeideng** [comment]
compare your code with this file https://github.com/cakephp/app/blob/master/src/Application.php

**Comment by ADmad** [comment]
Based on the comments not adding the routing middleware to the queue like 
`$middlewareQueue->add(new RoutingMiddleware($this));` seem to be the source of problem.

Hence closing the issue. Feel free to re-open if that's not the case.
