### ISSUE TITLE
RouteBuilder load plugin routing is broken

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#12556]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11
* Platform and Target: PHP 7.2.8

### What you did
I added this to my `config/routes.php` file.

`RouteBuilder::loadPlugin('ExitLinks');`

### What happened
`Error: Using $this when not in object context`

` Cake\Routing\RouteBuilder::loadPlugin ROOT/config/routes.php, line 151`
`Error in: ROOT/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php, line 640`

### What you expected to happen
I'm honestly not sure, but I was hoping that my plugins routes would be loaded.

**Comment by ADmad** [comment]
`RouteBuilder::loadPlugin()` is not a static method and hence can't be used as such.

**Comment by davidyell** [comment]
🤦‍♂️
