### ISSUE TITLE
SQL exception when CURRENT_TIMESTAMP is used in DATETIME columns

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#12553]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.11.
* Platform and Target: Apache, MySQL 5.7.

### What you did
In a fixture:
```
		'my_column' => [
			'type' => 'datetime',
			'null' => false,
			'default' => 'CURRENT_TIMESTAMP',
		],
```

### What happened
SQL exception:
> PHP Warning:  Fixture creation for "my_table" failed "SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'my_column'" in /.../Cake/TestSuite/Fixture/CakeTestFixture.php on line 244

The failed SQL contained `my_column datetime DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,`.

Notice quotes around `CURRENT_TIMESTAMP`. There is no error when `'type' => 'timestamp'`.

### What you expected to happen
No SQL error.

**Comment by dereuromark** [comment]
PR open.
