### ISSUE TITLE
Router::addUrlFilter is ignored when route caching is enabled

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#12562]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11
### What you did
1) Add following url filter to /config/routes.php
```php
Router::addUrlFilter(function ($params, $request) {
	debug('Url filter is called !!!');
	return array_merge($params,['url_filter_called'=>true]);
});
```

2) Create a link to any action via HtmlHelper (in any ctp file)
3) Set debug=>false and make sure that you haven't disabled route caching

### What happened
1) Url filter is called correcly.
2) Refresh web page to hit route cache.
3) Url filter is not called anymore.

### What you expected to happen
Url filters should be called everytime.
Whenever route caching is enabled or not.

My current workaround is to move url filter definitions from routes.php to bootstrap.php

**Comment by markstory** [comment]
> My current workaround is to move url filter definitions from routes.php to bootstrap.php

This is what you'll have to do if you want cached routes.

**Comment by Asgraf** [comment]
Please add warning the manual to not use Router::addUrlFilter in bootstrap.php
Because this is causes hard to catch bugs that are invisible when debug is enabled.

**Comment by markstory** [comment]
Where would you expect to see that warning?

**Comment by ADmad** [comment]
I would suggest keeping routies caching turned off by default. Unless you have thousands of routes connected the caching isn't going to give you much gains, just such headaches.

**Comment by markstory** [comment]
@ADmad that works for me too.

**Comment by Asgraf** [comment]
> 
> 
> Where would you expect to see that warning?

https://book.cakephp.org/3.0/en/development/routing.html#creating-persistent-url-parameters
