### ISSUE TITLE
Ordering being ignored inside the innerJoinWith function

### ISSUE THREAD

**Issue by BenoKop** [cakephp/cakephp#12570]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.6
* Platform and Target: nginx, MySQL.

### What you did
I just wrote a custom finder in a table class:
```
public function findForChargements(Query $query, array $options){
        return $query->innerJoinWith('AffairesEnProd', function($q){
            return $q->contain(['ColisPourAffaireEnProd' => ['sort' => ['ColisPourAffaireEnProd.colisNumero']]])
            ->where(['isLivr' => false, 'isAnnule' => false, 'AffairesEnProd.isFacteur' => false, 'isTransp' => true])
            ->order(['blTourneeTranspOrdre', 'semLivraison']);
        })
        ->leftJoinWith('Transporteurs')
        ->contain('Transporteurs')
        ->order(['-datePrevue' => 'desc']);
}
```

### What happened
No ordering on my INNER JOINED class.

### What you expected to happen
I want to order the elements of my inner joined class (AffairesEnProd) by blTourneeTranspOrdre and semLivraison. It's like the order inside the innerJoinWith function is being ignored. When I check the SQL Log, I can see that NO ordering is being executed on the AffairesEnProd class.

Thanks in advance.

**Comment by BenoKop** [comment]
I found an other way to do it:

When setting the association between the tables:

```
$this->hasMany('AffairesEnProd', [
        'bindingKey' => 'blid',
        'foreignKey' => 'blTransp',
])
->sort(['blTourneeTranspOrdre' => 'asc', 'semLivraison' => 'asc']);
```

Is the sort being ignored on purpose to force users to do it that way ? Or is it a miss ?

**Comment by markstory** [comment]
> It's like the order inside the innerJoinWith function is being ignored. 

It completely is, that is intentional and documented as part of the behavior. See the docs for [innerJoinWith](https://api.cakephp.org/3.6/class-Cake.ORM.Query.html#_innerJoinWith) and [matching](https://api.cakephp.org/3.6/class-Cake.ORM.Query.html#_matching).

**Comment by BenoKop** [comment]
Thanks for reply !
