### ISSUE TITLE
Regression with extensions and routing

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12577]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: dev-master (3.x)

### What you did

Updating core:
```
  - Updating zendframework/zend-diactoros (1.8.1 => 1.8.6):  Checking out 20da13beba
  - Updating cakephp/cakephp (3.6.4 => 3.6.11):  Checking out ddbfcdb479
  - Updating friendsofcake/bootstrap-ui (dev-develop b46d01e => dev-master b8e17bb):  Checking out b8e17bbb40
  - Updating cakephp/debug_kit dev-master (0e29ced => d5cd818):  Checking out d5cd81818b
  - Updating dereuromark/cakephp-geo dev-master (f6dae59 => 192517e):  Checking out 192517e70d
  - Updating dereuromark/cakephp-ide-helper dev-master (2731cc6 => a481a29):  Checking out a481a29fe1
  - Updating dereuromark/cakephp-setup dev-master (6336740 => 12adf45):  Checking out 12adf45c4b
  - Updating dereuromark/cakephp-test-helper dev-master (96339fe => 82e714c):  Checking out 82e714c940
  - Updating dereuromark/cakephp-tinyauth dev-master (9d5d22e => 479adb7):  Checking out 479adb7bdb
  - Updating dereuromark/cakephp-tools dev-master (0fce0f3 => 1fac073):  Checking out 1fac073732
  - Updating friendsofcake/search dev-master (7c14e0c => cc2decf):  Checking out cc2decf52c
```

### What happened
Integration tests around `_ext` now fail. See travis: https://travis-ci.org/dereuromark/cakephp-sandbox/jobs/431208574

### What you expected to happen
There should be no regression from 3.6.4 to 3.6.11
It seems it happened in 3.6.5: https://github.com/cakephp/cakephp/compare/3.6.4...3.6.5
Most likely around the legacy router part - and might only be relevant for tests.

But there is also no indication how tests would need to be refactored to work in the patch(es) after 3.6.4.

Tests are using
```php
	/**
	 * @return void
	 */
	public function setUp() {
		parent::setUp();

		Router::extensions(['rss']);
	}
```
which worked fine so far.

**Comment by markstory** [comment]
I don't see the source code for those failing tests here https://github.com/dereuromark/cakephp-sandbox/tree/update-core/tests/TestCase/Controller ? Could you provide a link to the tests that are failing now?

**Comment by dereuromark** [comment]
Sure thing,  it is the same one working for 3 years now:
https://github.com/dereuromark/cakephp-sandbox/blob/3.0/plugins/Sandbox/tests/TestCase/Controller/FeedExamplesControllerTest.php
see pr for more infos.

**Comment by markstory** [comment]
Ok. How does your plugin load its routes? You might be hitting a case where the router is reset dropping your extension enabling.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-sandbox/blob/3.0/plugins/Sandbox/config/routes.php
Nothing changed here either in 3 years. So it is some kind of hidden regression.
Note that this is a non vendor plugin, so the routing here is on top of the normal app one.

I am fine if we have to adjust the test framework here somehow, but then we should put it into docs/migration guide - as soon as we figure it out.

**Comment by dereuromark** [comment]
Any ideas/pointers on what could be fixed for https://github.com/dereuromark/cakephp-sandbox/pull/12 to have tests passing again and the regression fixed/resolved?

**Comment by dereuromark** [comment]
@markstory After some more debugging I finally found the regressor:
https://github.com/cakephp/cakephp/compare/3.6.4...3.6.5#diff-3d58de79d11037069356ea3dd5556605R126

Router::reload() is not a good idea at this point. It kills the static (extensions) config in the setup() of tests. Any way we can get rid of it?

**Comment by dereuromark** [comment]
PR resolves this with some manual work to be done.
Fair enough.

We should probably include a note in the docs?
