### ISSUE TITLE
EntityRoute has invalid regex

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#12572]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11

### What you did
In routes.php
```PHP
$routes->scope('/en', ['language'=>'en'], function (RouteBuilder $routes) {
    $routes->connect('/proxyplans/:slug_:id', ['controller'=>'Proxyplan','action'=>'view'], ['id'=>'[0-9]*','slug'=>'[a-zA-Z0-9_]*', 'routeClass' => 'EntityRoute']);
}
```
Anywhere in your app:
```PHP
debug($userpackage->id);
debug($userpackage->slug);
debug(Router::url(['language'=>'en','controller'=>'Proxyplan','action'=>'view','id'=>$userpackage->id,'slug'=>$userpackage->slug]));
debug(Router::url(['language'=>'en','controller'=>'Proxyplan','action'=>'view','_entity'=>$userpackage]));
```

### What happened
`(int) 1`
`'shared_custom'`
`'/en/proxyplans/shared_custom_1'`
`'/en/proxyplan/view'`

### What you expected to happen
`(int) 1`
`'shared_custom'`
`'/en/proxyplans/shared_custom_1'`
`'/en/proxyplans/shared_custom_1'`

### My current workaround

In EntityRoute.php find:
```PHP
preg_match_all('@:(\w+)@', $this->template, $matches);
```
and replace with:
```PHP
//field name shouldn't end with _ character
preg_match_all('@:(\w*[a-zA-Z0-9])@', $this->template, $matches);
```

**Comment by markstory** [comment]
Pull request open now.
