### ISSUE TITLE
Paginator limitControl bypass by a modification of the url parameter

### ISSUE THREAD

**Issue by ckheder** [cakephp/cakephp#12583]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.

### What you did
I'm using the paginator to paginate a list of records with the LimitControl parameter. The paginator limit is set to limit => 10 and maxLimit => 30.

My query in the Controller is also limit to 30 results.

In my database, i have 40 records.

### What happened
Everything works but if the URL parameter is set to 40 by user the 30 limit is overpass and the paginator load the 40 records.

http://localhost/mywebsite/ask?limit=10 works
http://localhost/mywebsite/ask?limit=30 works
http://localhost/mywebsite/ask?limit=40 works too event with the 30 limit.

### What you expected to happen
I hope that changing the URL parameter with a value higher than the limit does not allow to override this limit.

**Comment by markstory** [comment]
How have you configured the paginator component?

**Comment by garas** [comment]
Use `$paginate` and `$this->paginate($table)`

Or use only `$this->Paginator->paginate($table, $settings)`.

**Comment by markstory** [comment]
@garas is correct here.  Your paginate() call *replaces* the defaults with configuration that does not contain a maxLimit.

**Comment by ADmad** [comment]
`Controller::$paginate` should be killed :slightly_frowning_face:.
