### ISSUE TITLE
fatal error due to not existing components

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12590]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11 (dev-master)

### What you did
Setting a redirect in htaccess for a URL/domain change.
Suddenly we got 5xx exceptions with very weird (and hard to debug) behavior.

### What happened
```
[Error] Call to a member function allow() on boolean
Request URL: /hybrid-auth/endpoint?redirect=%2Faccount%2Flogin&hauth.start=Github&hauth.time=1537783531
Referer URL: /account/login
Stack Trace:
#0 /app/vendor/cakephp/cakephp/src/Event/EventManager.php(353): ADmad\HybridAuth\Controller\HybridAuthController->beforeFilter(Object(Cake\Event\Event))
#1 /app/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#2 /app/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#3 /app/vendor/cakephp/cakephp/src/Controller/Controller.php(658): Cake\Controller\Controller->dispatchEvent('Controller.init...')
#4 /app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#5 /app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(ADmad\HybridAuth\Controller\HybridAuthController))
#6 /app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), 
```

or also

```php
if ($this->Auth->user('id')) {
}
```
inside Controller method login() suddenly throws this exception.

How come the Auth component as very internal and core one can not be available in a controllers execution cycle? This should never happen.

### What you expected to happen
We must be able to trust the controller to have the components available always, otherwise it must fail earlier with a good exception.

**Comment by garas** [comment]
`Controller::__get()` should at least trigger warning `Property "%s" not set` when returning `false`.

Errors like `Call to a member function allow() on boolean` not helpful at all.

**Comment by dereuromark** [comment]
Trying to debug this on a live heroku instance is also super painful. We had to actually enable debug mode here to find out more :/

**Comment by markstory** [comment]
> How come the Auth component as very internal and core one can not be available in a controllers execution cycle

Sounds like you didn't load the component.

**Comment by dereuromark** [comment]
No, everything has been working for 2-3 years now.
Everything is there, and everything is working normally.
But in a specific case it just happens to not be there, and that is not acceptable. On top, the error is really bad, and as said by @garas needs to be more speaking instead of then blowing up with the unclear message "... on boolean".

**Comment by markstory** [comment]
So how can someone reproduce this problem? If you got a MissingComponentException your HTTP response would also be a 500. When reading controller properties we can't always discern which things should be a components that failed to load, or a model and which ones aren't.

**Comment by dereuromark** [comment]
There is no error here, that's the thing. Maybe we can start fixing the symptom with better error messages for now, and once this is more reproducible we fix the actual cause?

**Comment by markstory** [comment]
It's surprising that if/when your component failed to load that it the ComponentRegistry failed to load `Auth` it didn't raise an exception, as that is the normal behavior.

**Comment by dereuromark** [comment]
That's why I am so troubled by this. Everything suddenly failed after the hybrid auth had a different endpoint url config, which should not affect the app itself, nor produce such a weird behavior.
Everything works fine, until you do this config switch in github API.

**Comment by dereuromark** [comment]
Closing then for now, until we have a more clear way to reproduce.
