### ISSUE TITLE
Routes.php not always loaded

### ISSUE THREAD

**Issue by qqqqb** [cakephp/cakephp#12598]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11.
* Platform and Target:  
1. macOS Sierra 10.12.6
2. Apache2
3. PHP 5.6.30

### What you did
I'm trying to force adding parameter to URL on `config/routes.php` so I used `Router::addUrlFilter`

```
Router::addUrlFilter(function ($params, $request) {
    if ($request->getParam('lang') && !isset($params['lang'])) {
        $params['lang'] = $request->getParam('lang');
    }
    return $params;
});
```
[https://book.cakephp.org/3.0/en/development/routing.html#creating-persistent-url-parameters](url)
### What happened
At first it worked well, but then I discovered it did not work sometimes. After troubleshooting I found `config/routes.php` is not in INCLUDE list through debugKit.

### What you expected to happen
I have some scripts from older versions that work well. What I did now as a temporary solution is adding this could at `config/bootstrap.php` and I have no issue. I tried to fix it through you code, but could it not find the tip of the thread.

### Did you search before submit new issue
Yes I did search here and StackOverFlow

**Comment by markstory** [comment]
Do you have route caching enabled?

**Comment by qqqqb** [comment]
I don't know where to enable or disable it, it is just as default settings. I found all my routes at ROUTES tab on debugKit. but is seems doesn't cache addUrlFilter

**Comment by markstory** [comment]
Check in `src/Application.php`. If you have this line https://github.com/cakephp/app/blob/0c7d98344d867e4d279e6c0a6331ba97d2dbecdb/src/Application.php#L100

you have route caching enabled. You'll need to either stop using the route cache or move your `addUrlFilter` calls into your application's bootstrap file/method.

**Comment by markstory** [comment]
See #12562 and #12253 for similar issues.
