### ISSUE TITLE
Unexpected logging into multiple files

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#12600]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11
* Platform and Target: PHP 7.2.1

### What you did

I try to log only into one specific "scope" (logfile).

Example:

```php
use Cake\Log\Log;

Log::setConfig('module1', [
	'className' => 'Cake\Log\Engine\FileLog',
	'path' => LOGS,
	'file' => 'module1',
	'size' => '0.99MB',
	'mask' => 0777,
]);

Log::setConfig('module2', [
	'className' => 'Cake\Log\Engine\FileLog',
	'path' => LOGS,
	'file' => 'module2',
	'size' => '0.99MB',
	'mask' => 0777,
]);

Log::write(LOG_INFO, 'my message', ['scope' => 'module2']);
```

### What happened

Two output files with the same content: `2018-09-26 09:43:37 Notice: my message`

* module1.log
* module2.log

### What you expected to happen

I expect only one logfile with the filename: `module2.log`.

### Possible issue

I suspect the problem somewhere in the [Log.php](https://github.com/cakephp/cakephp/blob/master/src/Log/Log.php#L380) file e.g. here:

```php
$inScope = $scopes === false && empty($context['scope']) || $scopes === [] ||
    is_array($scopes) && array_intersect((array)$context['scope'], $scopes);
```

**Comment by ADmad** [comment]
In your example `module1` and `module2` are config names not scopes. Scopes need to be defined using `scopes` key in config array. Please refer to the [manual](https://book.cakephp.org/3.0/en/core-libraries/logging.html#logging-scopes).

**Comment by dereuromark** [comment]
See also https://sandbox.dereuromark.de/pages/best-practices#logging
