### ISSUE TITLE
How to access multiple result rowsets using nextRowset() from stored procedure in CakePHP 3.4

### ISSUE THREAD

**Issue by bitkaru** [cakephp/cakephp#12615]
This is a 
* [x ] feature-discussion (RFC)

* CakePHP Version: 3.4.8
* Platform and Target: WampServer Version 3.0.6 64bit, Mysql V 5.7.14 

### What you did
I am trying to access multiple result sets returned from a stored procedure in my CakePHP 3.4 project. Here is my code:

$stmt = $db->execute("call mydatasp($paramlist)");
    $result = array();                     
    try{
            do
            {
                $rowset = $stmt->fetchAll('assoc');
                $result[]=$rowset;
            } while($stmt->nextRowset());
        }
        catch(Exception $e){}

### What happened
Its giving me error
Call to undefined method Cake\Database\Log\LoggingStatement::nextRowset()

### What you expected to happen
how can i call the nextRowset() in Cakephp 3

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
