### ISSUE TITLE
Phan support

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#12618]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement

* CakePHP Version: 3.6.x

### What you did
Looked for .phan/

### What happened
Couldn’t find .phan/
Is it me?

### What you expected to happen

cakephp/cakephp
cakephp/app

... should/could specify phan plugins and pathes
https://github.com/phan/phan/blob/master/README.md

**Comment by ADmad** [comment]
We already `phpstan` for `3.x` and `phpstan` and `psalm` for `4.x`. There are still lot of issues reported by these two static analyzers that could be fixed, so using `phan` is not necessary right now.

**Comment by inoas** [comment]
There is (hopefully) quite some overlap between phpstan, pslam and phan, but seeing issues early (even if not fixing them right now), isn't that a good thing? And even only for 4.x not 3.x?

**Comment by dereuromark** [comment]
As he said: There are already tons of issues that needs adressing. Once they all are gone in 4.x one can think about the leftovers.
