### ISSUE TITLE
Use of `self` return type hint causes problem with Phake

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12613]
While working on updating `TwigView` for Cake 4.x, which uses `Phake` I got errors like

```
Declaration of TwigView_PHAKE5bb103193ff9c1::setResponse(Cake\Http\Response $response): WyriHaximus\TwigView\View\TwigView must be compatible with Cake\View\View::setResponse(Cake\Http\Response $response): Cake\View\View
```

So it seems the use of return typehint `self` can cause problem for mocking utilities like `phake`. 

Changing the return type hint of `View::setResponse()` from `self` to `View` fixes the issue. So I think we need to update all such usage of `self` with concrete class instead.

**Comment by WyriHaximus** [comment]
Personally I'm moving away from `Phake` and use the build in `$this->prophesize()` for mocking these days. Haven't updated `TwigView` yet but if it helps it I'll do it when I get back home. My preference goes to `self` over the concrete class mainly because when reading the code you always know that `self` references to the class you're in without having to keep the class name in mind, where using the concrete name you do that to the that. It's a little bit easier on the developer's mind.

**Comment by ADmad** [comment]
> Personally I'm moving away from Phake and use the build in $this->prophesize() for mocking these days. Haven't updated TwigView yet but if it helps it I'll do it when I get back home. 

Okay, but given the popularity of `phake` someone might might be / want to use it.

> My preference goes to self over the concrete class mainly because when reading the code you always know that self references to the class you're in without having to keep the class name in mind, where using the concrete name you do that to the that. It's a little bit easier on the developer's mind.

Even in Cake's classes use `self` if your app/plugin code is extending core that then you would have to tyhint using the concentrate. Using `self` in overridden method too would generate the same error and you see above in phake's mocked class.

**Comment by ADmad** [comment]
@markstory @lorenzo Your thoughts on this?

**Comment by dereuromark** [comment]
Sounds like those tools have a problem, rather than the language.
I also think self is more correct.
I wonder, however, if other tools, have solved this maybe? or if they all have an issue here - that would be sth then to evaluate.

**Comment by markstory** [comment]
I'm fine with sticking to `self` if we get multiple reports of `self` being a problem because of Phake and they are unwilling to update (which I think they should) then we can revisit this.

**Comment by ADmad** [comment]
Cool, closing then. We can revisit in future if needed.
