### ISSUE TITLE
RFC: Use lower case names for special templates folders.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12629]
We have few special templates folder like `Element`, `Layout`, `Plugin` and `Cell`. I propose changing them to lower case names: `element`, `layout`, `plugin` and `cell` respectively. 

This helps differentiate these special folder from corresponding controller templates folders and makes them easier to spot in a directory listing, especially when you have lot of controller folders in your project.

**Comment by dereuromark** [comment]
Plugin was always plugins so far (since 3.x).
The others have been inside /src/, and as such were uppercase.
Now, that they moved into /templates/ (and outside psr-4 src) it sure can make sense to rename.

**Comment by ADmad** [comment]
> Plugin was always plugins so far (since 3.x).

I was referring to the templates folder in 3.x `src/Template/Plugin` which is used for overriding plugin templates, not the `plugins` folder at app root which contains full plugins. As per my proposal it would now be `templates/plugin`.

**Comment by markstory** [comment]
Do you think this is a change we could automate easily with rector? If so I'm ok with doing it.

**Comment by ADmad** [comment]
I haven't looked into rector but the proposed folder renames are similar to templates folder rename we have already done, so I don't see these additional changes being an issue.
