### ISSUE TITLE
i18n locales from plugin using the same domain

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#12621]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.
* Platform and Target: WAMP

### What you did
In API documentation https://book.cakephp.org/3.0/en/core-libraries/global-constants-and-functions.html#__d is wrote "Useful when internationalizing a plugin: `echo __d('PluginName', 'This is my plugin');`".

If two or more loaded plugins using in function `_d()` the same domain parameter (**becase domain not always equal plugin name**) then will be conflict. 
Developer can create new doman.po file (the same domain like above) in `src/Locale/[language]/` (for example: maybe wants to overwrite translated text from plugin).

I think, solution for this problem will be extend function https://api.cakephp.org/3.6/source-class-Cake.I18n.MessagesFileLoader.html#151-183 to work with path included plugin name. 

Now works like that:
```
Array
(
    [0] => ...\src\Locale\pl_PL\
    [1] => ...\src\Locale\pl\
    [2] => ...\vendor\[name]\[package]\src\Locale\pl_PL\
    [3] => ...\vendor\[name]\[package]\src\Locale\pl\
)
```

Can be works like that:
```
Array
(
    [0] => ...\src\Locale\[pluginName]\pl_PL\
    [1] => ...\src\Locale\[pluginName]\pl\
    [2] => ...\src\Locale\pl_PL\
    [3] => ...\src\Locale\pl\
    [4] => ...\vendor\[name]\[package]\src\Locale\pl_PL\
    [5] => ...\vendor\[name]\[package]\src\Locale\pl\
)
```

Similar solutions is implemented in templates.

**Comment by ADmad** [comment]
I don't think there's there any need to complicate things. Just selecting unique domain names is not difficult.

**Comment by kicaj** [comment]
Yes, but you do not decide on the name of the domain only the authors of plugins, so you can come to a situation where two authors give the same name and then what?

**Comment by markstory** [comment]
> so you can come to a situation where two authors give the same name and then what?

Has this happened to you in practice? It is certainly a theoretical problem.

**Comment by kicaj** [comment]
Not yet. But what blocks us to protect ourselves against this?

**Comment by markstory** [comment]
> But what blocks us to protect ourselves against this?

The proposed structure would require applications to change which we can't do outside of major versions. I'm hesitant to break compatibility for hypothetical problems.

**Comment by ravage84** [comment]
Naming things well is a hard problem, as we probably all know but I think it is the actual problem at hand. Thus I would not overcomplicate our code for a problem that is in the hands of the user land developer.

**Comment by kicaj** [comment]
If we check firstly path `...\src\Locale\[pluginName]\pl_PL\` the Cake will be compatibility with previous versions because none of the programmers used that before, Also there was no described in documentation.

**Comment by kicaj** [comment]
Also Laravel to solve this problem: https://laravel.com/docs/5.7/localization#overriding-package-language-files

**Comment by kicaj** [comment]
What do you think about it? Try to prepare pull-request?

**Comment by markstory** [comment]
In the proposed path example where is `pluginName` coming from? Is that the translation domain?
