### ISSUE TITLE
VarDumper integration

### ISSUE THREAD

**Issue by agarzon** [cakephp/cakephp#12627]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.17
* Platform and Target: Linux 

### What you did
The command line **vendor/bin/var-dump-server** is available with any cakephp installation. It's a dependency from another dependency.

[The VarDumper Component](https://symfony.com/doc/current/components/var_dumper.html)

### What happened
After executed the listener I noticed that is not getting any dump of variables while debugging.

### What you expected to happen
It should dump the variables as commanded by dump() function.

Not sure if is not fully not integrated or I'm not doing it properly (considering I use cake 3.5 and under docker containers, behind reverse-proxy, etc..) anyone else had luck with this tool?

If is not fully integrated, it should be a nice addition to consider

**Comment by ADmad** [comment]
It's most likely being installed through `psy/psysh` which we have as a dev dependency in default app skeleton. It's actually causing problem with output of Cake's `debug()` method too. Quick fix would be to pin `psy/psysh` to a lower version.

**Comment by markstory** [comment]
Could VarDumper be used to improve the output of `debug()` and `pr()`? Having the option to use the dump-server to redirect dumps to a terminal is a nice addon. Right now our vardumping doesn't do a great job with circular references.

**Comment by lorenzo** [comment]
I think it is an idea worth exploring
