### ISSUE TITLE
RFC: File Extension Handling & Routing Behavior

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#12624]
In the context of #12586 and out of curiosity I setup a vanilla CakePHP and and tested some routing behavior cases.

CakePHP Core 3.6.12
CakePHP App 3.6.5

Implemented ``TestController`` with ``event()`` and ``anotherIcal()`` , added the templates ``/Test/event.ctp`` & ``/Test/another_ical.ctp`` and added a route for ``/test/another.ical`` to ``TestController::anotherIcal()`` but used the fallback routes for everyhting else.

No. | URL | RequestHandler active | Extensions active | Expected | Result
--- | ---- | ----------------------- | ----------------- | --------- | ------
1 | /test/event | Yes | - | TestController::event() | As expected
2 | /test/event.ical | Yes | - | Not sure | **The action event.ical is not defined in TestController** *2
3 | /test/another.ical | Yes | - | TestController::anotherIcal() | As expected
4 | /test/event | Yes | ical | TestController::event() | As expected
5 | /test/event.ical | Yes | ical | TestController::event() | As expected
6 | /test/another.ical | Yes | ical | TestController::anotherIcal() | **The action another is not defined in TestController** *1
7 | /test/event | No | - | TestController::event() | As expected
8 | /test/event.ical | No | - | Not sure | **The action event.ical is not defined in TestController** *2
9 | /test/another.ical | No | - | TestController::anotherIcal() | As expected
10 | /test/event | No | ical | TestController::event() | As expected
11 | /test/event.ical | No | ical | TestController::event() | As expected
12 | /test/another.ical | No | ical | TestController::anotherIcal() | **The action another is not defined in TestController** *1

What do you think of the following statements:

1. Routing should  have precedence over extension handling
2. Action names with a dot, like ``event.ical``, are invalid anyway, we could raise  a not found exception with a more helpful errro message like ``The extension ".ical" is not handled nor is there a route configured.``.

**Comment by ADmad** [comment]
Your expectation of `6` is incorrect. If `ical` extension parsing is enabled in router than `/another.ical` would call `another()` method not `anotherIcal()` method.

The errors for `2` and `8` are also expected, they won't map to any action.

**Comment by dereuromark** [comment]
You have a few flaws in your setup. Why is the extension part of the action name? It shouldn't.

**Comment by ravage84** [comment]
@ADmad thanks for the numbering.

> Your expectation for 6 is incorrect. If ical extension parsing is enabled in router then /another.ical would call another() method not anotherIcal() method, so the error is correct if you don't have that method.

My expectation of the result is based on my expectation on how the routing vs. extension handling works ("1. Routing should have precedence over extension handling").

> The errors for 2 and 8 are also expected, they won't map to any action.

Sure. I just go one step further and would like to help those who see that error, as I stated in:

> 2. Action names with a dot, like ``event.ical``, are invalid anyway, we could raise  a not found exception with a more helpful errro message like ``The extension ".ical" is not handled nor is there a route configured.``.

@dereuromark 

> You have a few flaws in your setup. 

Please state them (not just one), so we can either correct them or I can explain them.

> Why is the extension part of the action name? It shouldn't.

Well, it's just a choice for the sake of showcasing the current behavior. Why shouldn't it? Especially since this seems to be the default behavior without extension handling.

**Comment by ADmad** [comment]
> Routing should have precedence over extension handling

Extension is parsed before trying to match routes and you have enabled parsing of `.ical` extension, hence route for URL string `/another.ical` will never match since router effective sees it as string `/another` and extension `ical`. @markstory can probably confirm this.

**Comment by markstory** [comment]
> Extension is parsed before trying to match routes and you have enabled parsing of .ical extension, hence route for URL string /another.ical will never match since router effectively sees it as string /another and extension ical

Yes extensions are the first thing parsed out of URLs. https://github.com/cakephp/cakephp/blob/95222a05833faf02aca9892dd788591f1b518027/src/Routing/Route/Route.php#L448-L452

**Comment by ravage84** [comment]
Thanks for clarifying. 
What was the reasoning behind this order of parsing? Because to me this seems odd.

For me a route is (or at least can be) more specific and thus should be considered first, while extension handling is a very general rule of behavior ("cut away what it's after a dot").

**Comment by markstory** [comment]
>  What was the reasoning behind this order of parsing? Because to me this seems odd.

I've forgotten the reason, as it has been a long time. One possibility I can think of is that parsing the extension *after* the route path would make finding the extension harder as it could be in a passed argument or a routing key based on the template.

Another possible solution to that problem would be to compile the extension pattern into the route's regular expression. That could create other side-effects and but it could be something we do in a minor or major release.

**Comment by dereuromark** [comment]
@ravage84 Extension should never be part of the action name.
Action => what to get
Ext => in what form

Also, there are cases like /controller.json (which implicitly has index action), and which are valid.

The only issue I had and is still open IMO is the silent "duplicate page" for unrouted extensions.
As per https://github.com/cakephp/cakephp/issues/12585

If you request `/foobar.ical` and it just serves the HTML of `/foobar` instead of more clearly failing with the reason why this extension cannot be routed.

**Comment by ravage84** [comment]
@markstory I guess we can keep how it is but I feel we should communicate the current behavior better.

For example with a note or warning under https://book.cakephp.org/3.0/en/development/routing.html#Cake\Routing\Router::extensions after:

> By using extensions, you tell the router to remove any matching file extensions, and then parse what remains. If you want to create a URL such as /page/title-of-page.html you would create your route using:

With a text something like this:

"Be aware that the extensions are parsed __before__ the routes are matched. If you parse a file extension ``bar``, a route for ``/foo.bar`` will never match."
