### ISSUE TITLE
Import comments from tables and fields in models

### ISSUE THREAD

**Issue by hervehobbes** [cakephp/cakephp#12631]
Hello,

This is a:

* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Apache, Ubuntu, Mysql

### What I'd like
When we bake models, if a table in the database has a comment, write back this comment in the Model/Table/MyTable.php script.
The same thing could be done for comments on fields

I'm not enough confortable with Cake' source code to create a PR.

**Comment by ADmad** [comment]
This issue was moved to cakephp/bake#465
