### ISSUE TITLE
Hard coded test paths instead of using existing constants

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#12636]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.12.
* Platform and Target: Apache, MySQL.

### What you did
Tried to move tests to a different folder, adjusted `App::build` call in bootstrap.php to point the tests to that folder.

### What happened
No tests detected.

### What you expected to happen
The tests should be detected in another folder. It seems that the cause of the problem is that paths are hardcoded in some places, f.ex. in TestShell.php:
* `if ($testCase = preg_replace('@.*Test\/Case\/@', '', $testCase)) {`
* `$testFile = str_replace(APP, APP . 'Test/Case/', $file) . 'Test.php';`
* `$testCase = preg_replace('@.*Test/Case/@', '', $testCase);`.

There are `TESTS` and `APP_TEST_CASES` constants defined but it seems they are not used everywhere where they are supposed to be used.

**Comment by markstory** [comment]
> There are TESTS and APP_TEST_CASES constants defined but it seems they are not used everywhere where they are supposed to be used.

Would you be willing to send a pull request to update the locations that need updating? I've never had the need to move test case directories around.

**Comment by bancer** [comment]
Yes, I will take a look what can be done to improve that.

**Comment by markstory** [comment]
#12680 is open to solve this.
