### ISSUE TITLE
Cake\I18n\Time is used in TimestampBehavior.php but does not exist in cakephp/orm

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#12630]
_From @elovin on October 8, 2018 17:3_

I get the following error:

[`Error: Class 'Cake\I18n\Time' not found in /ws/vendor/cakephp/orm/Behavior/TimestampBehavior.php:149`](https://github.com/cakephp/orm/blob/eeb330f0a96d10a6f876a748bc3384d2ddb294a0/Behavior/TimestampBehavior.php)

And indeed, the class does not exist in cakephp orm standalone.

Im useing cakephp/orm 3.6.10

_Copied from original issue: cakephp/orm#16_

**Comment by saeideng** [comment]
@elovin  its now in suggested list 
https://github.com/cakephp/cakephp/blob/b0d6f718a3ae35671d0e2dcd579724a82a6e23c6/src/ORM/composer.json#L36

**Comment by markstory** [comment]
Closing as the `TimestampBehavior` is not a required part of the ORM, and is already a recommended package.
