### ISSUE TITLE
AuthComponent redirect query parameter double encoding url to redirect back to

### ISSUE THREAD

**Issue by cjquinn** [cakephp/cakephp#12643]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11
* Platform and Target: Docker | nginx/1.11.9 | PHP/7.1.22 | MySQL/5.7.23

### What you did

My application uses routes that have characters that need url encoding, specifically the pip `|`. When a user tries to directly access a route with a pipe in it they get redirected to the login page with the redirect query parameter.

### What happened
That query parameter ends up double encode:

`/sign-in?redirect=%2Fadmin%2Fitems%2Fproduct%257C3%257C-901592549%2Ffix`

### What you expected to happen

`/sign-in?redirect=%2Fadmin%2Fitems%2Fproduct%7C3%7C-901592549%2Ffix`

I've followed the execution of `AuthComponent` through and the place where is gets double encoded is in the `Route::_writeUrl` method - https://github.com/cakephp/cakephp/blob/master/src/Routing/Route/Route.php#L852. This is because  the `\Zend\Diactoros\Uri` class returns the path with certain characters encoded - https://github.com/zendframework/zend-diactoros/blob/master/src/Uri.php#L577.

Not entirely sure what the work around here is and I would normally avoid putting characters like pipe in my routes but in the case of this project it makes sense to use them. One option could be to use `urldecode` before `http_build_query` in the `Route::_writeUrl` method.

`http_build_query(array_map('urldecode', $query))`

Seems like a bit of a strange thing to do though!

**Comment by markstory** [comment]
Could AuthComponent remove the URL encoding in the `_getUrlToRedirectBackTo` method?

**Comment by cjquinn** [comment]
Yeah that makes a lot more sense, touches far less things! Shall I submit a pull request?

**Comment by dereuromark** [comment]
Are you sure you are not mistaken?
The double encoding makes sense if you encode a querystring in a querystring.
As it currently works that properly decodes again into the actual redirect target.
At least it does it for me totally correct.

**Comment by dereuromark** [comment]
Maybe I didnt use these special characters. Would be nice to see a test case then as well.

**Comment by cjquinn** [comment]
I could very well be mistaken, I'll be sure to add a test case proving the defect.

**Comment by markstory** [comment]
I am not clear on whether the double encoding is causing your application to behave incorrectly or if it was not what you were expecting?
