### ISSUE TITLE
Console\Cake\Shell::createFile Unable To Use UNC path

### ISSUE THREAD

**Issue by bryonbean** [cakephp/cakephp#12657]
This is a:
* [x] bug

* CakePHP Version: 2.10.9

* Platform and Target: All

### What you did
We use [vfsStream](http://vfs.bovigo.org/) for file system emulation for testing. Using it requires paths to be fully formed, i.e. paths contain both the protocol (in this case, `vfs:`), and of course the required `//` separator indicating the start of computer name and path. A complete file path will look resemble `vfs://path/to/virtual/file`. However this issue will affect any UNC path for saving files on, for instance, a network share, e.g. `//<computer name>/<path>`.

### What happened
https://github.com/cakephp/cakephp/blob/5b57a1e9263d288bb47abdf2d092f702a862a084/lib/Cake/Console/Shell.php#L766-L767

`Shell::createFile` is stripping file paths of any legitimate directory separators occurring in succession and replacing it with a single directory separator, turning a legitimate path, e.g. `vfs://path/to/file` into one that will not work, e.g. `vfs:/path/to/file`.

### What you expected to happen
Perhaps one solution is to ensure that, should the double directory separators match either of the following conditions, they will not be replaced:
* `//` is preceded immediately by a `:` character
* `//` are the first two characters in the string.

**Comment by markstory** [comment]
This issue is also present in 3.x.

**Comment by bryonbean** [comment]
Whoops, sorry about that errant click.
