### ISSUE TITLE
[2.x] Error in PostgreSQL describe when the default value is a function 

### ISSUE THREAD

**Issue by begnini** [cakephp/cakephp#12652]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.12 (commit 5b57a1e9263d288bb47abdf2d092f702a862a084)
* Platform and Target: PostgreSQL

### What you did
Create a table where one field has a function in the default value.

```php
$db->execute('CREATE TABLE test_function_default_describe (
   id integer PRIMARY KEY, 
   year int default date_part(\'year\'::text, now()))');
```

### What happened

When call `$db->describe('test_function_default_describe');` the default value returned is truncated.

```php
Array (
    'type' => 'integer'
    'null' => true
    'default' => 'date_part('year''
    'length' => null
) 
```

So, if you use this table to clone other table (for example, a fixture), the generated SQL comes broken:

```sql
ERROR:  invalid input syntax for integer: "date_part('year'"
STATEMENT:  CREATE TABLE "public"."test_function_default_describe" (
    "id" serial NOT NULL,
    "year" int DEFAULT 'date_part(''year''' NOT NULL
);
```

### What you expected to happen

The expected is the default value describing the function without truncation.

**Comment by saeideng** [comment]
Closing as a pull request is open  now

**Comment by begnini** [comment]
I think the master branch has the same bug. 

https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/PostgresSchema.php#L204
