### ISSUE TITLE
4.x - Optimizing PHP performance by using fully-qualified function calls

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#12654]
Adding a `\` before some (see list below) native php functions increases performance by saving lookup time, sometimes even drastically.
As Cake 4.x requires php 7.1, I guess this is a nice thing to do.

<details>
<summary>List of all functions that benefit from this</summary>
    <ul>
        <li>`array_slice`</li>
        <li>`assert`</li>
        <li>`boolval`</li>
        <li>`call_user_func`</li>
        <li>`call_user_func_array`</li>
        <li>`chr`</li>
        <li>`count`</li>
        <li>`defined`</li>
        <li>`doubleval`</li>
        <li>`floatval`</li>
        <li>`func_get_args`</li>
        <li>`func_num_args`</li>
        <li>`get_called_class`</li>
        <li>`get_class`</li>
        <li>`gettype`</li>
        <li>`in_array`</li>
        <li>`intval`</li>
        <li>`is_array`</li>
        <li>`is_bool`</li>
        <li>`is_double`</li>
        <li>`is_float`</li>
        <li>`is_int`</li>
        <li>`is_integer`</li>
        <li>`is_long`</li>
        <li>`is_null`</li>
        <li>`is_object`</li>
        <li>`is_real`</li>
        <li>`is_resource`</li>
        <li>`is_string`</li>
        <li>`ord`</li>
        <li>`strlen`</li>
        <li>`strval`</li>
    </ul>
</details>

Follow up info:

http://php.net/manual/en/language.namespaces.faq.php#language.namespaces.faq.shortname2
http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
https://github.com/Roave/FunctionFQNReplacer

**Comment by lorenzo** [comment]
:-1: To doing that in the code itself
:+1: To adding a shell command you can execute on deploy

**Comment by ADmad** [comment]
This was considered earlier but and IIRC adding backlash to core functions did not show any considerable improvement.

@cleptric Do you have any benchmarks showing the improvement?

**Comment by inoas** [comment]
Would adding these as use statements allow the modification of global functions in apps by developers?

**Comment by cleptric** [comment]
@ADmad The last two links show some stuff, for example `call_user_func `

```
+----------------------------------------+---------+---------+---------+---------+---------+--------+---------+
| subject                                | best    | mean    | mode    | worst   | stdev   | rstdev | diff    |
+----------------------------------------+---------+---------+---------+---------+---------+--------+---------+
| benchCallUserFuncWithRelativeReference | 2.642μs | 2.729μs | 2.694μs | 2.839μs | 0.062μs | 2.28%  | +68.78% |
| benchCallUserFuncWithAbsoluteReference | 1.577μs | 1.617μs | 1.610μs | 1.688μs | 0.029μs | 1.77%  | 0.00%   |
+----------------------------------------+---------+---------+---------+---------+---------+--------+---------+
```

**Comment by cleptric** [comment]
@lorenzo Does it causes harm to add the `\` directly to the core?

**Comment by dereuromark** [comment]
Still some micro opt in normal cases right?
Thats exactly why deploy adjustment is enough here as opt in. 
The overhead for devs is more - and also them not being to overwrite them anymore can be bad in cases where needed.

**Comment by cleptric** [comment]
1. Altering vendor files on prod is bad imo
2. Using `\call_user_func` instead of `call_user_func` is neither overhead nor any problem to overwrite. We just call the methods directly in global namespace. Userland is not touched at all.
3. Only OPCache enabled apps will benefit, for the others it stays the same.

**Comment by dereuromark** [comment]
s0ppp 0000 ppp

**Comment by dereuromark** [comment]
Then you must have a sniffer to do and ensure this. Everything else is bongers.
And then this becomes a global rule for the whole ecosystem. Just saying.

**Comment by lorenzo** [comment]
@cleptric 

- It is a significant deviation from our style guide and the way the general PHP community does things
- Almost objectively, it looks worse
- It is more work for whoever is contributing to cake
- App code does not directly benefit from this, so our users would have to adapt to the new style

**Comment by cleptric** [comment]
Alright, as I don't personally agree on arguments like "it looks bad", I'll close this issue, as it already was discussed in a long manner.
I wasn't ware of the old issue.

Thanks for your opinions 🙏
