### ISSUE TITLE
I'm using Laravel framework, with Phinx as my DB migration feature.

### ISSUE THREAD

**Issue by bs-thomas** [cakephp/cakephp#12669]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cakephp/core, 3.6.12

* Platform and Target: WAMP, MySQL

I'm currently using Laravel 5.5, and recently added Phinx to deal with migrations.  (Yes, I do not like Laravel's migration feature).  I noticed a weird problem with Twig at first, because the cache files keep getting generated on a directory called "false", directly inside the webroot directory instead of my preferred cache directly.

### What you did
I investigated quite a bit and compared the working and non-working versions.

### What happened
I noticed that Laravel's "env()" function did not get declared.  The reason is because CakePHP core's "env()" function gets called and declared first.  The problem here is, the "env()" functions of Laravel and CakePHP work differently.

In my .env file, I have "TWIG_CACHE=false".  On Laravel, this gets interpreted as the boolean FALSE.  However, on CakePHP, it gets interpreted as the string "false".  So instead of shutting off the Twig cache, the cache gets generated to the directory "false/"

### What you expected to happen
I expected the definition TWIG_CACHE=false inside .env file should return boolean false, instead of string false.

Cake's env declared here:
\vendor\cakephp\core\functions.php

Laravel's env declared here:
\vendor\laravel\framework\src\Illuminate\Support\helpers.php

Would be great if the two behaviors can be matched up, as this problem was actually quite tricky, and took a while for me to find out.

Your help is greatly appreciated!

**Comment by lorenzo** [comment]
I don't have a quick solution in mind, but maybe there is a workaround for you.

1. Try adding a `require "/path/to/laravel/function.php" (the file where the env function is declared in larvel. Add the in one of the bootstrap files or your app. This way you can make sure that the larval definition gets loaded first.
2. Open a similar issue to laravel. They are at fault as much as we are for defining global functions, which is the underlying issue.

We'll investigate if it is possible to change the env function so that it behaves closer to the larvae's implementation.

Or... You could join the dark side, we have cookies!

**Comment by ADmad** [comment]
We need a new PSR for how frameworks should add global functions :trollface:.

**Comment by bs-thomas** [comment]
Then those crappy "Facades" I'm Laravel will burn in hell, lol...  IMO the worst practice ever adapted.  Those are not even real Facades...

**Comment by ADmad** [comment]
> Those are not even real Facades...

:zipper_mouth_face:

**Comment by ADmad** [comment]
The different lies in where the type conversion is done. Laravel uses `vlucas/phpdotenv` which returns all env vars and string to better mimic how they work in shells. Laravel's `env()` converting string `'false'` to boolean `false`.

CakePHP's `env()` doesn't do any type conversion. Instead if using `.env` files we rely on `/josegonzalez/php-dotenv` which does the boolean type conversion.

**Comment by lorenzo** [comment]
Maybe it makes sense to do the conversion automatically?

**Comment by bs-thomas** [comment]
Thanks for all these comments.

I'm posting a few reference links here:

https://github.com/motdotla/dotenv/issues/51
https://github.com/lorenwest/node-config/issues/272
https://github.com/vlucas/phpdotenv/issues/129
https://github.com/vlucas/phpdotenv/issues/104

Based on my readings, here's what I think.

dotenv should NOT convert strings to boolean.  What if somebody really wants to call a a variable the string "null", or "true", or "false"?  It doesn't always happen, but it's possible and we don't want to put such a limitation on things.

Then, helper functions like env(), they should never change the default behavior if they are meant to be called this way.  Unless you call it something like cakeEnv() or laravelEnv().

If you choose a global function to be called env(), keep it the behavior it should be.  So Cake's doing the right thing, Laravel's changing the behavior behind the dotenv concept, which I don't quite agree here.

But @lorenzo, I'm already on Laravel, and... Obi-wan tells me that I must not join the dark side.

There's nothing much I can do at the moment actually.  Maybe as per your suggestion, requiring Laravel's helper file before anything gets loaded.  But it really sucks that way!

**Comment by dereuromark** [comment]
Maybe we can add this workaround into the phinx docs for now and then close this issue here?

**Comment by patricknelson** [comment]
```
MY_VAR=0
```

... then...

```php
if ((int) getenv('MY_VAR')) {
    // ... do a thing...
}
```
