### ISSUE TITLE
Replace Header Value Magic Literals in SecurityHeadersMiddleware with Constants

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#12666]
CakePHP Version: 3.7

Recently, I was integrating the SecurityHeadersMiddleware  into some of our applications. I noticed I had to use magic literals such as ``sameorigin`` to configure the behavior of the middleware. Since it is a bad practise to use/have magic literals, I thought it would make sense to replace those magic literals in that middleware with class constants.

I wasn't sure which way was the best, so I created two PRs alternative solutions.

1. Replacing the magic literals with class constants within that middleware #12664
1. Replacing the magic literals with class constants from separate, dedicated classes #12665

Personally, I prefer #12665 over #12664, as it is more readable and has a clear separation.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
