### ISSUE TITLE
'errorField' should accept array of properties when adding new rules

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#12676]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.12
* Platform and Target: not relevant

### What you did
I added an isUnique rule to my table, referencing two properties ("code" and "revision").
I also set the 'errorField' option to the same properties.

```php
$properties = ['code', 'revision'];
$rules->add($properties, 'code_revision_UNIQUE', [
    'errorField' => $properties,
    'message' => __('Code and revision combination already in use')
]);
```
### What happened
```php
Warning (2): Illegal offset type [CORE\src\Datasource\EntityTrait.php, line 993]
Notice (8): Array to string conversion [CORE\src\Datasource\RuleInvoker.php, line 135]
```
And no errors showing on my form controls

### What you expected to happen
I expected both of my fields to be invalidated and my form controls to show the error

**Comment by ADmad** [comment]
As a user I would find seeing the same error message for 2 fields pretty weird.

**Comment by efanzini** [comment]
@ADmad It doesn't sound weird to me, as long as the error message is pertinent.

**Comment by ravage84** [comment]
@efanzini I used to create a CakePHP plugin for this for my CakePHP 2.x applications.
I never upgraded it, though.

https://github.com/ravage84/cakephp-multi-column-uniqueness

**Comment by dereuromark** [comment]
Or use the Tools plugin 2.x branch (0.x versions).

**Comment by dereuromark** [comment]
It is fair to say that this can be done on user land code and exists as multiple plugin code, so since 2.x is in maintenance mode, we an close this then now.

**Comment by ravage84** [comment]
@dereuromark I agree that this can be done in user land code, but I'd keep it for 3.x, if it can be done.

**Comment by dereuromark** [comment]
Let's see if someone wants to provide a PR here for 3.7 before it lands.
