### ISSUE TITLE
CakePHP Console: Unable to configure the session on PHP 7.2.0

### ISSUE THREAD

**Issue by trenshaw** [cakephp/cakephp#12678]
* [x] bug
* CakePHP Version: 2.10.12
* Platform and Target: Ubuntu 18.04, MySQL 5.7.24, PHP 7.2.10

### Description
A behavior attached to a model which calls AuthComponent::user() in attempts to obtain the logged in user fails when used in a console shell/task.

Have re-tested on and confirmed bug / issue does not manifest in shells / tasks on PHP 5.3.3. Issue appears to be related to the following (fixed) PHP bugs:-

Bug #71038 | session_start() returns TRUE on failure
https://bugs.php.net/bug.php?id=71038

Raised in PHP 7.1.0 and fixed in 7.2.0. CakeSession (in console / shells / tasks) appears to have relied on session_start() falsely returning TRUE and/or $_SESSION still being usable after headers have been sent. Refer:-

Bug #75227 | You cannot change the session module's ini settings at this time
https://bugs.php.net/bug.php?id=75227

Bug #73245 | session_start() doesn't start the session if headers have been sent
https://bugs.php.net/bug.php?id=73245

### Result
Error: Unable to configure the session, setting session.use_trans_sid failed.
#0 /var/www/html/cakephp-2.10.12/lib/Cake/Model/Datasource/CakeSession.php(619): CakeSession::_configureSession()
#1 /var/www/html/cakephp-2.10.12/lib/Cake/Model/Datasource/CakeSession.php(632): CakeSession::_cookieName()
#2 /var/www/html/cakephp-2.10.12/lib/Cake/Model/Datasource/CakeSession.php(248): CakeSession::_hasSession()
#3 /var/www/html/cakephp-2.10.12/lib/Cake/Controller/Component/AuthComponent.php(670): CakeSession::check('Auth.User')

### Expected
AuthComponent::user() should return NULL in console shells/task. CakeSession should not rely on session_start() always returning TRUE the same for any INI settings related to a session that failed to start.

CakeSession should gracefully handle the absence of session in the CLI. As a workaround, I added a !static::$_isCLI check to if(empty($_SESSION) statement on line 578 in Cake/Model/Datasource/CakeSession.php to ensure ini_set() is not called for session.* related settings in the CLI.

**Comment by markstory** [comment]
> CakeSession should not rely on session_start() always returning TRUE the same for any INI settings related to a session that failed to start.

How would you expect the session to behave properly if there is no session?

**Comment by trenshaw** [comment]
Hi Mark,

I am still running test cases between PHP 5.3.3 on CentOS 6.10 and PHP 7.2.10 on Ubuntu 18.04.

A session can be started in the CLI for as long as the shell/task is running but obviously there will be no Auth.User key set unless a user is manually logged in by passing their user record to AuthComponent::login()

The error "ini_set(): Headers already sent. You cannot change the session module's ini settings at this time" is a bit ambiguous in the CLI as there are no headers to send. 

Apparently, PHP (prior to 7.2) was tolerant and allowed invalid usage without errors. Even when it might seem to work, it didn't. PHP 7.2 session now raises errors for code that cannot work.

PHP's session manager has 2 modes "cookie" and "transid" - neither of which can be modified once output has started.

Users of other MVC frameworks on PHP 7.2 e.g. Symfony are also reporting similar issues in their framework's packages when it comes to session and modifying session related settings in the CLI.

CakeSession::_hasSession returns TRUE as static::$_isCli is TRUE, this is being set through static::init() when static::_cookieName() is called.

A CakeSessionException is being thrown before static::start() can be evaluated - the second expression in the || comparison with static::_hasSession().

If evaluated separately, static::start() would call static::_startSession() as static::started() is FALSE. This is where there is a key difference between PHP versions.

On PHP 5.3.3 headers_sent() returns FALSE whereas on PHP 7.2.10 it returns TRUE.

I've mocked up a PHP script that does nothing other than call ini_set() on a handful of session.* settings. It is possible to configure / modify these settings in the CLI at runtime but only before any output has occurred.

I'm not sure what the solution is except that a re-think is needed for CakeSession to provide session support in the CLI as it did on earlier versions of PHP.

Regards,

Trent Renshaw > IT Manager | Lead Developer 
Object Systems Technology 

p: 02 9002 5800 | d: 02 9002 5802 | m: 0411 038 749 | skype: trent_renshaw 
e: trent.renshaw@objectst.com.au | www.objectst.com.au 
Level 2, 21-25 King Street, Rockdale NSW 2216 

----- Original Message -----

**Comment by markstory** [comment]
Have you tried initializing the session before your shell emits any output? Output to stdout or stderr causes headers to be 'sent'.

**Comment by trenshaw** [comment]
Calling $this->out(AuthComponent::user()) in a basic shell works fine. I experience the issue with CakeSession calling AclExtrasShell::aco_sync(). Output must already be started before the model with the my behavior that uses AuthComponent is called. I will back trace and continue to provide details.

**Comment by dereuromark** [comment]
I remember we did similar things on 3.x
Maybe comparing the changes done there in recent months can also clarify things for 2.x

**Comment by akeiper** [comment]
Are there any updates on these issues? Running into the same issue when trying to run phpunit on 7.2.

**Comment by jrbasso** [comment]
I guess this issue can be closed since #12906 was merged.
