### ISSUE TITLE
Virtual generated columns support

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#12677]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.12

I'm developing a Cake application wich connects to a pre-designed MySQL database.
This db has some table columns defined as 'virtual generated' and they're messing with my app.

Is there any plan to officially support this MySQL/MariaDB feature?

**Comment by markstory** [comment]
> Is there any plan to officially support this MySQL/MariaDB feature?

No immediate plans. Could you expand on how are these fields 'messing' with your application?
