### ISSUE TITLE
Integration tests cannot access console output anymore

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#12683]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.0-RC1

---------------

I often want to test the whole output, not just whether it contains something, so I often used `$this->_out/_err->messages()` instead of the available assertion methods.

#12072 changed the properties holding the input/output objects (`$_in`, `$_out`, `$_rr`) from protected to private (btw this isn't documented as a breaking change in the migration guide), so it's no longer possible to retrieve the generated output.

One could probably work around this by importing the trait directly and changing the properties visibility, but having to not do that would IMHO be nicer :) And while additional assertion methods might work for some, people might still want test/inspect the data in other ways that require access to the actual data, so being able to directly access the output wouldn't hurt I think.

**Comment by ADmad** [comment]
Changing the properties to private seems like an oversight, they should be reverted to protected.

**Comment by jeremyharris** [comment]
Sorry about that! I also renamed them >< I will try to get to fixing this this weekend if no one grabs it first.

**Comment by jeremyharris** [comment]
PR up
