### ISSUE TITLE
Extended AuthComponent returns no content on JSON exception

### ISSUE THREAD

**Issue by rdcx** [cakephp/cakephp#12689]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: Apache2

### What you did
Extend AuthComponent then assign controller to class parameter
```
class AuthComponent extends \Cake\Controller\Component\AuthComponent 
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->_controller  = $this->_registry->getController();
    }
}
```
Throw an exception within a standard controller action i.e
```
class ArticlesController extends Controller 
{
     public function add()
     {
           throw new BadRequestException('THIS TEXT SHOULD BE SHOWN');
     }
}
```

Call the action using JSON
```
http://localhost/articles/add.json
```

### What happened
A Content Length of 0 is returned to the browser and only the headers are set.

### Potential cause
If I remove the following line from the extended AuthComponent the message the content length is normal and the Json output of the exceptions message is shown.
```
$this->_controller  = $this->_registry->getController();
```

Also using a variable instead of setting it on the object works i.e
```
$controller = $this->_registry->getController();
```

Using a random parameter name also prevents causes Content Length 0:
```
$this->awdawwdwawadw = $this->_registry->getController();
```

### What you expected to happen
Exceptions with content type json, should return the body (message) of the exception regardless of setting the controller to an object parameter within the AuthComponent.

**Comment by ADmad** [comment]
`3.2` isn't going to get any bugfixes. Please test against latest `3.6` release.
