### ISSUE TITLE
No way anymore to load plugins on demand and in non-integration tests?

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#12682]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0

--------------------------

`Plugin::load()` has been deprecated in favour of `Application::addPlugin()`, and will be removed in 4.0. 

I'm using `Plugin::load()` a lot in the test environment, and having to load everything at (application) bootstrap time, I don't know, I have a feeling that this will introduce quite some overhead to get plugin loading "on demand" working, which might be required to for example avoid polluting the test environment with unnecessary or even conflicting bootstrapping logic and routes.

Furthermore, outside of integration tests, the `Application` class will not be involved in the test environment, meaning there would be no clean way to load plugins for regular unit tests at all?

Maybe I'm missing something, maybe there are (plans for) alternatives? I know there's `Plugin::getCollection()->add()`, but `Plugin::getCollection()` is marked as internal, so it cannot really be treated as a stable API.

btw, why isn't `Plugin::unload()` deprecated too?

**Comment by markstory** [comment]
> btw, why isn't Plugin::unload() deprecated too?

If there is no load, there is nothing to unload 😛 but mostly because I forgot.

Are you loading plugins dynamically during your application's test suite? Wouldn't your application's tests be more representative if all plugins were loaded?

**Comment by ndm2** [comment]
Well, I'd say it depends, it might not neccessarily be an actual application, but just a test application, for example when developing standalone plugins. Such a plugin, or pretty much any extensible system, might need to be tested separately with other plugins, in order to ensure things work with only additional plugin X and Y available.

There might be ways to overcome this, but I think there's at least two situations that show the need for some way to dynamically load plugins:

1. When the tests aren't integration tests, as in that case the `Application` class is not going to be involved, ie `Application::addPlugin()` cannot be used.

2. When testing standalone plugins, as the plugin must somehow be able to load itself. [**DebugKit for example uses**](https://github.com/cakephp/debug_kit/blob/918b810e42cdf36b6228f98a504121a795b675f5/tests/bootstrap.php#L116) the for internal use only marked `Plugin::getCollection()`: 

If there isn't really a technical problem with dynamically loading plugins, ie things were only deprecated to move people towards using the `Application` class instead of the bootstrap file, then maybe `Plugin::getCollection()` could be made non-internal? Or maybe just have some additional description that makes it clear that it's OK to be use it in the test environment, and that it can be treated as a stable part of the API, despite being marked as internal?

**Comment by saeideng** [comment]
you can use `$this->loadPlugins(['myPlugin']);`  in tests

**Comment by ndm2** [comment]
Ah, I didn't saw that one... but that isn't the advised way to load standalone plugins for their own test environment, or is it?

**Comment by saeideng** [comment]
@ndm2  it is official way and added here https://github.com/cakephp/cakephp/pull/12309

**Comment by ndm2** [comment]
@saideng You might have misunderstood what I was referring to, I understand that `TestCase::loadPlugins()` is the new way for dynamically loading plugins in tests, but is it the recommend way to load a tested standalone plugin itself? That's usually done in the tests bootstrap file, see the mentioned debug kit example:

https://github.com/cakephp/debug_kit/blob/918b810e42cdf36b6228f98a504121a795b675f5/tests/bootstrap.php#L116

My static analyzer tests are saying "_don't do that, it's an internal API_".

**Comment by saeideng** [comment]
just keep in mind , replacement of `Plugin::load()` is not `Plugin::getCollection()->add()` but  is `TestCase::loadPlugins()`
duty of `Plugin::load()`  was adding a plugin + run it ( loading )
but  `Plugin::getCollection()->add()`  is only for adding  a plugin
`Plugin::getCollection()->add()` is mostly  internal API , yes IMO

**Comment by saeideng** [comment]
if its necessary , my suggest is having 2 methods
`Plugin::add()`
`Plugin::get()`
 and remove all bellow methods 
1.  `plugin::path()`
2. `plugin::classPath()`
3. `plugin::configPath()`
4. `plugin::templatePath()`

and instead `Plugin::get(...)->*()` 
for example `Plugin::get(...)->getClassPath()` instead of `PLugn::classPath(..)`

**Comment by markstory** [comment]
@ndm2 Taking the `internal` flag off of `Plugin::getCollection()` would be a good way forward. My concern would be that it is a clunky/long method chain. Perhaps that doesn't matter much as they aren't methods used every day.

**Comment by ndm2** [comment]
@markstory That would work for me.

I'd think that dynamic plugin loading outside of the test environment is rather rare, personally I've never done that so far, and I think I've only ever stumbled over one question on StackOverflow regarding that, which was about dynamically loading themes depending on user session data IIRC.
