### ISSUE TITLE
4.x: more consistent validate callback

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12697]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: 4

### What you did

            ->add('pr', 'unique-issue', [
                'rule' => ['validateUniqueIssue', ['scope' => ['repository']],
                'message' => 'This PR is already linked to a group with this issue.',
                'provider' => 'table',
            ]);

and

    /**
     * @param string $value
     * @param array $additional
     * @param array $context
     *
     * @return bool
     */
    public function validateUniqueIssue($value, array $additional, array $context)

### What happened

This is fine until you remove the additional scope

            ->add('pr', 'unique-issue', [
                'rule' => ['validateUniqueIssue'],
                'message' => 'This PR is already linked to a group with this issue.',
                'provider' => 'table',
            ]);

Then it breaks as the arguments into the method fail with "ArgumentCountError: Too few arguments to function ...".
It now suddenly expects

    /**
     * @param string $value
     * @param array $context
     *
     * @return bool
     */
    public function validateUniqueIssue($value, array $context)

### What you expected to happen
To have a more reliable and reusable kind of signature here, consistent in both cases so if used in one table validator with and in another without it still works out.

Either we keep 2 args and merge the additional keys into the existing context.
Or we always have 3 and the 2nd can be an empty array here.

**Comment by dereuromark** [comment]
I thought this would be a bit easier to do.
https://github.com/cakephp/cakephp/compare/4.x-validation-rule
It seems to cause also all other Validator rule tests to fail.

Any better ideas?

**Comment by markstory** [comment]
This [part](https://github.com/cakephp/cakephp/compare/4.x-validation-rule#diff-e9a33ae291cad769634b51725279d597R141) is likely causing tests to fail as it is a breaking change. I think always having a 3rd argument will be safer in the short term than changing the semantics of the 2nd argument.

**Comment by dereuromark** [comment]
But either way context should probably the the 2nd, as 1 and 2 are always there, 3+ can be the ones merged in.
I wanted to keep the existing way of method argument injection while allowing an upgrade path to the pass key in the context (which makes way more sense anyway).
I am open to alternative solutions, though. If someone wants to help out getting this on track.

**Comment by markstory** [comment]
Is using reflection to check the number of arguments the validator expects and adding in an empty `$additional` parameter an option. It would let us solve the warnings. We could also catch the ArgumentError and retry with the additional parameter as well.

**Comment by robertpustulka** [comment]
Could there be a DTO that would keep the context (preferably as an object too), a value and additional arguments? This DTO could be passed to the rule alone. I'm not sure how to deal with the BC though. Maybe check the rule parameters with reflection and when it expects something else than a DTO as a first argument unwrap the DTO and pass the arguments the old way?

**Comment by dereuromark** [comment]
Actually, that could really be a way out here indeed :)

**Comment by markstory** [comment]
Using reflection would work. Adding a new ValidationContext type would make that reflection have fewer edge cases which is nice.

**Comment by Schlaefer** [comment]
Is it correct that while stale was removed the issue stayed closed?

**Comment by dereuromark** [comment]
I dont think so.

**Comment by Schlaefer** [comment]
I don't want to expand the scope of the issue, but if this is changed it could be helpful to consider having only one official how to set the arguments.

The core rules all use

```
[
    'rule' => ['validateUniqueIssue', <arg1>, <arg2>, ...],
...
```

But there's also

```
[
    'rule' => 'validateUniqueIssue',
    'pass' => [<args>],
```

And [the Cookbook currently describes](https://book.cakephp.org/3/en/core-libraries/validation.html#using-custom-validation-rules) stuffing `$context` by abusing it's `providers` property.

```
$this->Examples->validator('default')->provider('passed', [
    'count' => $countFromController,
    'userid' => $this->Auth->user('id')
]);
```

**Comment by dereuromark** [comment]
Are we still interested in doing this consistency part?
Do we need to move this to 5.x milestone?

**Comment by markstory** [comment]
If we can figure out a solution that is backwards compatible and emits warnings for not upgraded code either by reflection or other heuristics I don't see why this couldn't be part of 4.x.
