### ISSUE TITLE
Arguments in chained queries are leaking down the chain

### ISSUE THREAD

**Issue by dreamingmind** [cakephp/cakephp#12690]
* [x] Query bug
* CakePHP Version: 3.6.12

### What I did
When chaining queries with simple array arguments, the array elements are leaking down the chain

#### Sample custom finders in a table

    public function findAssignedTo($query, $options) {
         return $query->where(['format_id IN' => $options]);
    }
    public function findNumbers($query, $options) {
        return $query->where(['number IN' => $options]);
    }

#### Sample controller code 

    // assuming $pieces is a table object
    $query = $pieces->find('assignedTo', [3, 6, 13])->find('numbers', [2, 5]);

#### The SQL that is generated

    SELECT 
      Pieces.id AS `Pieces__id`, 
      Pieces.number AS `Pieces__number`, 
      Pieces.quantity AS `Pieces__quantity`, 
      Pieces.format_id AS `Pieces__format_id`, 
      Pieces.collected AS `Pieces__collected` 
    FROM 
      pieces Pieces 
    WHERE 
      (
        format_id in (3, 6, 13) 
        AND number in (2, 5, 13)
      )

### What I expected to happen

Though I understand Query objects manage named arguments so the parameters for multiple queries can be packaged together, when chaining fine-grain custom finders like this, I expect the array arguments to have a limited scope.

**Comment by dereuromark** [comment]
I don't think you are supposed to use the incoming options/config array directly as value.
Usually, that is an assoc array that you use:

```
$pieces->find('assignedTo', ['values' => [3, 6, 13][)
    ->find('numbers', ['values' => [2, 5]]);
```
etc

**Comment by dreamingmind** [comment]
Well, I should be able to resolve my code simply enough.

I guess I'll call this a 'stylistic gotcha' rather than a bug then?

**Comment by jeremyharris** [comment]
I would agree that this if this is happening it is a bug. Finder options should not persist between finders. I don't think there should be an issue with using the array how you want, either.

I don't think this is happening in the core, though. I ran some quick tests to see if the `$options` param is somehow shared, but it's an array not array object so I don't think it is. 

Perhaps some outer code is merging your option arrays? Can you write a failing test case?

**Comment by lorenzo** [comment]
It is a feature, it was designed like that on purpose, Mostly as a way to emulate some cake 2.x behavior and to have all passed options in beforeFind. But I’m not sure the idea is worth keeping today.

**Comment by markstory** [comment]
@lorenzo Is this something we should consider changing in 4.0, or does the subtlety of this make it a dangerous change?

**Comment by dreamingmind** [comment]
I wasn't imagining a change in the way associative array elements were handled. This part did seem thought out; named elements = managed elements. But having elements on numeric keys persist was surprising; un-named elements = transient values.

**Comment by lorenzo** [comment]
@markstory I have taken advantage of this fact many times, so I know already that my apps would break (not that I care since I know how to fix them), but I suspect others will be surprised about this. 

I think, though, that we should plan already on removing the feature. Maybe start investigating if removing it would break how beforeFind works, and possibly add a flag to keep the old behaviour for a while.

**Comment by lorenzo** [comment]
Just to be clear, the idea behind this feature is the following:

Passing `$options` to any finder is equivalent to calling `$query->applyOptions($options)` and then calling the finder with no options.

**Comment by ADmad** [comment]
Changing the behavior will definitely break many apps, so I don't think doing so in 4.0 is a good idea. We should plan for the change in 5.0.

**Comment by markstory** [comment]
Sounds like there is a big enough tradeoff here that it is not a simple change to make, and requires further discussion.

**Comment by othercorey** [comment]
Moved to 5.x roadmap wiki. There will probably be discussions/changes made in 4.x before 5.0 to support this, but this is more of an architecture discussion than a bug fix discussion.
