### ISSUE TITLE
Swoole in cakephp

### ISSUE THREAD

**Issue by johnlanz** [cakephp/cakephp#12705]
Anyone tried running cakephp on swoole
I found this benchmark and php is on top 4 which is shocking: https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=fortune

I think the benchmark is using mysql pool and this is the fastest mysql benchmark I've ever seen.
So now how can we implement this in cakephp...

**Comment by markstory** [comment]
Seems like this could be a plugin or alternate application skeleton. It will require a bunch of changes to the application startup as instead of relying on the apache/phpfpm environment data to would need to consume the request events from swoole.

**Comment by EOM** [comment]
It is a good idea to have **CakePHP 4.x support** in the future to be able to do microservices for example.

**Example as some of these projects.**

laravel-swoole - ❤️ A high performance HTTP sever based on Swoole. Speed up your Laravel or Lumen applications. This repo is maintained by Swoole Taiwan Community.
Lawoole - A combination framework with Swoole and Laravel.
laravel-swoole-jsonrpc - The JSON-RPC server and client based on Swoole, for Laravel and Lumen framework.
lumen-swoole-http - A bridge from Swoole to Lumen.
laravel-s - Speed up Laravel/Lumen by Swoole, 'S' means Swoole, Speed, High performance.
Slim-Swoole - Convenient library to run SlimPHP applications with Swoole.
zys - A high performance service framework based on Yaf or Swoole.
yii2-swoole - An integration with yii2 and Swoole.
phwoolcon- An integration with Phalcon and Swoole.
zend-expressive-swoole - Swoole support for Expressive applications

**Comment by dereuromark** [comment]
Is there something to do here, or shall we close this? Someone can just make a plugin or repo here.

**Comment by ADmad** [comment]
This should start out as a community plugin/skeleton. Someone can try out implementing it with 4.x and if changes are required in core to support it then open specific issues/pull requests for it.

**Comment by gautam-askme** [comment]
Any update on this ?

**Comment by markstory** [comment]
@gautam-askme Nope. I don't think a community plugin was started, do you have any interest in taking that on?

**Comment by t73biz** [comment]
> @gautam-askme Nope. I don't think a community plugin was started, do you have any interest in taking that on?

I would be interested in taking this on as a community plugin. Any suggestions on a process for this @markstory ?

**Comment by markstory** [comment]
@rongchaplin You make a repository, get the code working and go from there. :smile:

**Comment by t73biz** [comment]
LOL. Fair enough. Will update when I have something a bit more substantial.

**Comment by ishan-eventrac** [comment]
Found this example repo: https://github.com/rochamarcelo/cakephp-api-swoole-sample
