### ISSUE TITLE
TreeBehavior: Decrease default Priority for beforeDelete-Event

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp#12706]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.6
* Platform and Target: LAMP, debian 9, not so relevant

### What you did
I have a Model which uses TreeBehavior. And I use to push changes to the on-Device offline-First caches of an App.
So I created the default way a beforeDelete Event in the table, which pushed Ids which had deleted to the apps. I put the finder for children in there, which searches for chidren using the "lft" and "rght" fields to know the Ids of the children deleted with the entity.

### What happened
The apps got pushed that the next root-nodes of the MPTT got deleted. They actually didnt get deleted. But a lot of apps deleted them from their offline-first-caches.
What i figured out: my beforeDelete from the Table got fired after the beforeDelete of TreeBehavior. Searching for children beetwen lft and rght returns the next nodes which got reassigned the MPTT.

### What you expected to happen
I'd expect beforeDelete beeing really before anything is deleted.

Kind of very weird if you are not so much used to MPTT and you think your lft/rght is corrupt so you walk the long way of inspecting 12.000 records manually.

_Proposed Easy fix:_
- Lower the priority, so that treeBehavior::beforeDelete gets significant priority difference to any costum Events and 
- document how to deal with this this in the cookbook. (contributed a note already here: https://github.com/cakephp/docs/pull/5886)

_Proposed Long fix:_

- Implement new livecycle callbacks for TreeBehaviour in the ORM like ```afterChildrenDelete``` or ```beforeMainEntityDelete```.

**Comment by markstory** [comment]
Closing as documentation was updated.

**Comment by 3811015** [comment]
@markstory dont you think by default TreeBehavior::beforeDelete() should run after ModelsTable::beforeDelete()?

I intended the documentation change to be one part of the solution.

**Comment by markstory** [comment]
Why would it be timed differently than other behavior callbacks?

**Comment by 3811015** [comment]
Based on the assumption that other devs would expect the same as I would do. I was actually expecting to be in a Callback _before_ _anything_ is deleted, as it suggests by its name beforeDelete.

Giving it a different timing would help to roll straight out with writing a costum Callback in Table.

Maybe one will need to adjust TreeBehavior::beforeSave to an earlier timing.

Did anyone ever try out if TreeBehavior does work the correct way with other default Behaviors like TranslationBehavior?

I think putting everything default on priority 10 might be conflicting with the expectations of the name of the Callbacks. As well it makes it harder for Cake beginners, as they will understand the ORM as a "Blackbox" and the callbacks as wires hanging out of it, where they can wire up their code.

Maybe as another suggestion: 
Use the $options to easily set the priority of callbacks of ORM-included behaviours earlier or later.

**Comment by markstory** [comment]
> Did anyone ever try out if TreeBehavior does work the correct way with other default Behaviors like TranslationBehavior?

People can control the order events are fired by attaching the behaviors in the required order.

> I think putting everything default on priority 10 might be conflicting with the expectations of the name of the Callbacks.

How could we set the defaults better? Each behavior having its own priority would require more documentation as each behavior would need its own priority documented. Having all the priorities the same makes callbacks work like DOM events which have the same ordering around first-attached, first-fired.

**Comment by 3811015** [comment]
> How could we set the defaults better? Each behavior having its own priority would require more documentation as each behavior would need its own priority documented. Having all the priorities the same makes callbacks work like DOM events which have the same ordering around first-attached, first-fired.

Thats why I had the idea to use the options:

> Maybe as another suggestion:
Use the $options to easily set the priority of callbacks of ORM-included behaviours earlier or later.

You leave everything default 10. But make it very easy to reconfigure.

Something like:

```
$this->addBehavior('Tree', [
        'parent' => 'ancestor_id',
        'left' => 'tree_left',
        'right' => 'tree_right',
        'callbackPriorities' => [
            'beforeDelete' => 99,
            'afterSave' => 2,
            'beforeSave' => 2,
        ]
    ]);
```

If something does conflict, youre off adjusting it as easy as renaming the fields.

**Comment by markstory** [comment]
> Thats why I had the idea to use the options:

All behaviors already support the `priority` option which you can use to configure the priority of event handlers. I'm not convinced we need different priorities per callback, at least I've not seen a use case that required it.

**Comment by 3811015** [comment]
> I'm not convinced we need different priorities per callback, at least I've not seen a use case that required it.

Well I need to push the Ids of the children in on creation and deletion. It did work great all the time on creation. Because the Behavior was first. Now it fails on the deletion. Increasing the priority of the Behavior would make it fail on the other end.

**Comment by 3811015** [comment]
Having had some discussion with royalty on irc, i am going to write a section about how you prioritize your costum callbacks in your table with implementedEvents(). The function is just mentioned once in the hole /en/ORM/table-objects.rst

If there is a nice guide how to priotize your costums events in the table, then there might be indeed not be any need for any change.

As well, this implementedEvents() in Table was new to me too...
