### ISSUE TITLE
FormHelper maintaining model name on label

### ISSUE THREAD

**Issue by ahmyi** [cakephp/cakephp#12702]
Having Inflector::humanize excepting multiple delimiters on pull request 

_Originally posted by @markstory in https://github.com/cakephp/cakephp/pull/12701#issuecomment-435684038_

Here is the modified FormHelper

https://github.com/ahmyi/cakephp/blob/d98ca97a6cd9fb6462f2392f53456249f9343f1d/src/View/Helper/FormHelper.php#L899

This will help multiple model's with same field name to be distinguished itself. As metioned in above pull request.

![image](https://user-images.githubusercontent.com/630603/47967637-8e319680-e09a-11e8-8618-bdee80a82849.png)

to 

![image](https://user-images.githubusercontent.com/630603/47967649-a86b7480-e09a-11e8-9dde-d72e49d8f0a4.png)

```PHP
echo $this->Form->control('Father.first_name',['type'=>'text']);
echo $this->Form->control('Mother.first_name',['type'=>'text']);
```

**Comment by markstory** [comment]
My concern would be that this will negatively impact the behavior of existing applications. By changing the default behavior we could cause layout and display issues.

**Comment by ahmyi** [comment]
No layout problem..It just changes text within label before this it removes the model's name and just gets the field name. In cases that I have done before, I have to manually put in at options label for each single form inputs.

**Comment by markstory** [comment]
The content in labels could be significantly longer which is what could cause layout issues/breaks.

**Comment by dereuromark** [comment]
Could this be an opt in config for form helper?
that also solves the inflection issue.

**Comment by ahmyi** [comment]
You can use 
```PHP
$this->Form->control("Some.label_name",['label'=>'Some Label Name']);
```

but then again have to do to every form actions. No magic in that.

**Comment by markstory** [comment]
> but then again you have to do it to every form actions. No magic in that.

You could also define your own application `FormHelper` extension that applies the necessary logic.

> Could this be an opt in config for form helper?

We could, but with more options come more complexity and documentation we need to maintain. I'm not convinced that this cannot be handled in application/plugin code so I'm reluctant to add it. I would rather pass the original fieldName into the `LabelWidget` so that applications/plugins can have more control over the inflections than any options we add can provide.
