### ISSUE TITLE
FormHelper matching/rendering errors when getting belongsToMany association ids with {n}.id syntax

### ISSUE THREAD

**Issue by hdogan** [cakephp/cakephp#12710]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next
* Platform and Target: any

### What you did
I'm using belongsToMany association and getting associated entity ids with using (multiple) **independent** select-box controls instead of using single selection-box with multiple selection enabled (ie, using `._ids` suffixed single input). I'm getting associated ids with using `plural_association_name.0.id` naming convention and checking `validCount` rule in main `Table` object. It invalidates `plural_association_name` field but `FormHelper` is unable to detect `plural_association_name.0.id` control to invalidate it.

I've added

```
if (substr($field, -5) === '0.id') {
    $field = substr($field, 0, -5);
}
````

control in `FormHelper` `error` method to normalize input name then it started to invalidate successfully that independent selection input.

https://github.com/cakephp/cakephp/blob/21c8fce5ca8b68292b948a28606006faa935b579/src/View/Helper/FormHelper.php#L790-L792

### What happened
It fails to invalidate single control with named `plural_association_name.0.id`

### What you expected to happen
It would be nice to have separated input(s) to be detected and invalidated too (like that `.ids` suffixed ones).

**Comment by markstory** [comment]
If you have multiple inputs which ones should have error highlighting applied when an association level rule like yours fails? Should it be all inputs or just the 0th one?

**Comment by hdogan** [comment]
I think only first one is better for UX/UI (I'm not an UX expert).

Or 

* It can invalidate all inputs as a default (like all `plural_association_name` prefixed inputs, or all `{n}.id` suffixed inputs)
* rules checker `errorField` option can be used to overwrite (like indicating `plural_association_name` to invalidate all fields, `plural_association_name.1.id` to invalidate only 2nd one).

**Comment by hdogan** [comment]
By the way, FormHelper `error` method always check if context has errors. It's impossible to invalidate *Form field / Form control* manually at the moment.

I used custom validator to validate first element of array (ie, `[0]['id']` key) and `error` option of `control` method of FormHelper to set input invalidated manually, but it does not work, because of the context error checking in FormHelper empties `$error` value.

https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L796-L798

```php
<?= $this->Form->control('somethings.0.id', ['error' => $this->Form->error('somethings')]) ?>
```

If I comment out those check, it starts to work.

I think FormHelper `error` may has `force` or `skipContextCheck` option to skip strict context error checking. It might be splited to `getError` `setError` methods to control errors more easily, maybe...
