### ISSUE TITLE
Events are called multiple times within IntegrationTestCase

### ISSUE THREAD

**Issue by liqueurdetoile** [cakephp/cakephp#12713]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.13
* Platform and Target: tested under Wamp (Php 7.1) and Lamp (PHP 7.2)

### What you did
I'm working on a quite huge REST server under Cakephp. We need to create global listeners for some app's events (auth failure for instance) that can be fired from many places (many auth methods :). It also lets customers settle some custom actions (logs, mails, notifications, account termination...) in response.

Listeners are hooked in bootstrap method of `application.php`.

Important : EVERYTHING IS GOING WELL IN FRONT-END TESTING. TROUBLES CAME WITH INTEGRATION TEST CASES

### What happened
When doing some integration testing, I've planned to trigger a ban by spamming API. It didn't work as expected because I was banned "too soon". It appears that when doing multiple API calls (with a simple GET request) inside the same test function, callbacks are called as many times that requests have been made :
- 1 time for 1st call
- 2 times for 2nd call
- and so on

I've made a [quick repro of the bug](https://github.com/liqueurdetoile/cakePHP_error_exponential_events/blob/master/tests/TestCase/failTest.php) and publish a repo [available here](https://github.com/liqueurdetoile/cakePHP_error_exponential_events)

I found a work around by unregistering the event before each API call with  `EventManager::instance()->off('test.failed');`. The [second test case](https://github.com/liqueurdetoile/cakePHP_error_exponential_events/blob/master/tests/TestCase/failTest.php) show the trick.

### What you expected to happen
Events should be triggered only once.

I didn't find anything related to this issue nor dug in the code (lack of time).

**Comment by markstory** [comment]
This is a limitation in the test harness. Events listeners are only torn down during a test case's teardown method by Cakephp. Your workaround is the correct approach given how your application is using events.

We could expose a helper method for dropping all event listeners but I am not sure what else we could do at the framework level to make this better.

**Comment by liqueurdetoile** [comment]
@markstory Thanks for the quick reply. I was somehow expecting a response like that due to static declaration of the global event manager (I've read some code by now ;).

An helper would be very handy. Maybe it can be added to `_sendRequest` method to automatically drop all events before a request ?
