### ISSUE TITLE
Include bug when writing plugin tests

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12727]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6 latest

### What you did
Test case for a plugin helper that internally uses

    $this->Html->link()

### What happened

```
1) Search\Test\View\Helper\SearchHelperTest::testResetLink
include(/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/tests/test_app/config/routes.php): failed to open stream: No such file or directory

/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/src/Routing/Router.php:1170
/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/src/Routing/Router.php:1170
/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/src/Routing/Router.php:610
/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/src/View/Helper/UrlHelper.php:56
/app/vendor/friendsofcake/search/vendor/cakephp/cakephp/src/View/Helper/HtmlHelper.php:354
/app/vendor/friendsofcake/search/src/View/Helper/SearchHelper.php:68
/app/vendor/friendsofcake/search/tests/TestCase/View/Helper/SearchHelperTest.php:144
```

Obviously, using normal composer install (and "cakephp/cakephp": "^3.5" etc) on plugins, we
of course pull a tag instead of dev-master.
As such https://github.com/cakephp/cakephp/blob/master/.gitattributes#L55 excludes too much here.

### What you expected to happen
The file should either be there, or we must make sure it is not hard-required for these kind of routing tests.

**Comment by markstory** [comment]
How should `Router` load routes if not through the routes file?

**Comment by dereuromark** [comment]
True. But can we either auto add good defaults for testing (as it tries), or better yet dont try to load a nonexistent file and instead then throw a more meaningful exception?

**Comment by dereuromark** [comment]
I guess fair enough then.
