### ISSUE TITLE
CsrfComponent and CsrfProtectionMiddleware clash not notified

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#12737]
CakePHP version 3.6.13

I've just spend some time on debugging something odd, added CsrfProtectionMiddleware, and the cookie was not set with httpOnly and secure flags, but duplicate cookie was set correctly when provided cookieName config param.

I found out, that by mistake, i've had configured both CsrfComponent and CsrfProtectionMiddleware (one in Application and one in AppController) 

I do think, if by docs the CsrfComponent is deprecated, there should be warning of using it by default, or at least there should be warning/error when using both of these CSRF built-in protections at once.

Maybe the right time is for either one or both of these to notify an error, when they try to set the csrfToken cookie, but it is already present and not set by the component itself?

I've tried to find where to notify of the clash, but i found no way to access application/middlewareQueue from the controller (available through Event in Controller/Component) and neither to check from Middleware for specific Component to be used.

Second guess is to modify the error message "CSRF token mismatch." to say "CSRF token mismatch. Check if you have only {CsrfComponent / CsrfProtectionMiddleware} configured" (respectively in both components)

Also related is to clarify docs on how to use CsrfProtectionMiddleware https://github.com/cakephp/docs/issues/5893

**Comment by smarek** [comment]
Also as mentioned in docs, even when using singleton CsrfProtectionMiddleware, and using both methods `Application->middleware { $middlewareQueue->add(...); }` and `Application->routes { $routes->registerMiddleware(...); }` the usage clashes and ends up throwing "CSRF token mismatch"

So there should probably be an error/notification about using both of the methods, or duplicating middlewares between routes/middlewareQueue

**Comment by garas** [comment]
https://github.com/cakephp/cakephp/pull/12568 will emit deprecation warning on `3.7`.

I've argued it should be on `3.6`, but it was decided to add it to `3.7`.

**Comment by ADmad** [comment]
Given that 3.7 stable will be released very soon I don't think there's anything to be done here. Hence closing the issue.

**Comment by smarek** [comment]
@ADmad sorry, i don't agree, 

  - Using both CsrfComponent and CsrfProtectionMiddleware should emit warning or even error
  - Configuring CsrfProtectionMiddleware twice (as mentioned in https://github.com/cakephp/cakephp/issues/12737#issuecomment-439679445 ) should emit warning or error, because the usage is syntactically correct, but will break the purpose implementation

**Comment by smarek** [comment]
@ADmad i've also mentioned, that the clash is not currently detected by framework on-runtime, and no error/warning occurs, see proposal to docs

https://github.com/cakephp/docs/pull/5894/files
