### ISSUE TITLE
[RFC] Router prefix variable with validation

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#12734]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.13 composer
* Platform and Target: should not matter

If I've seen correctly, neither Router::prefix or Router::scope (or another Router provided method) can be used to define router variable with validation

What can be done easily in single route connect, such as
```php
 $routes->connect('/user/:user_id/profile', ['controller' => 'Users', 'action' => 'profileDetail'], ['user_id' => '[0-9]+']);
```

Is not possible with mentioned. What I'd expect is to be able to use something like this:
```php
Router::scope('/user/:user_id', ['user_id' => '[0-9]+'], function (RouteBuilder $routes) {
    $routes->connect('/profile', ['controller' => 'Users', 'action' => 'profileDetail');
});
```

And the best would be to provide default value as well (useful ie. for language scopes)
```php
Router::scope('/:language/', ['language' => ['validation' => '[a-z]{2}', 'default' => 'en'], function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index');
});
```

If this is already possible, then please point me in the right direction, and i'd document that feature more through https://github.com/cakephp/docs

**Comment by dereuromark** [comment]
Did you see the `->setPatterns(['id' => '\d+'])` part? Regex basically is a form of validation here.
https://book.cakephp.org/3.0/en/development/routing.html
Specifically https://book.cakephp.org/3.0/en/development/routing.html#configuring-route-options

**Comment by ADmad** [comment]
Variables / route elements are not supported in scopes.

**Comment by smarek** [comment]
@ADmad and will be? Or should I use something else, such as custom routing middleware?

**Comment by markstory** [comment]
I am pretty sure you can use variables in scopes as scope paths are prepended to route URLs. You can also set patterns for scopes routes but you have to do it in each route which isn't great. 

If we were to add builder level patterns I would want to use methods instead of positional arrays. Method would be more aligned with the rest of the builder and our overall direction of improving typehinting/ide completion.

**Comment by smarek** [comment]
Well I'm completely OK with builder where methods allow chaining, ie. like this

```php
// /en => /:language=en/:controller=Pages/:action=index
Router::scope("/:language", function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index');
})->routerScopeVariable(':language', '[a-z]{2}', 'en');

// Which would convert URLs such as
// "/:controller/:action" => "/:language=en/:controller/:action"
// "/de/:controller/:action" => "/:langauge=de/:controller/:action"

/**
  * @param string $varName uri variable/param name, must be prefixed with ':'
  * @param string|callable $validation regexp string or function validating the variable contents before route match
  * @param mixed $defaultValue value to provide in param, if left empty, route will require the variable to be present
  * @param boolean $redirect to redirect to url with explicitly set default value (ie. redirect from "/:controller/:action" to "/:defaultValue/:controller/:action" in case of example above, effective only if the $defaultValue is provided
  * @return \Cake\Routing\RouteBuilder builder to chain more calls to
*/
function routerScopeVariable($varName, $validation, $defaultValue = null, $redirect = false) { ... }
```

**Comment by markstory** [comment]
Couldn't that be `$routes->setPatterns(..)` so its on the RouteBuilder? Doing it as a chain off the scope method requires going back in time and updating all the routes connected in a scope callback which isn't something the builder or Router keep track of.
