### ISSUE TITLE
3.7.0 middleware loading issues

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12740]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6 latest (3.7)

### What you did

I upgraded a 3.5 app to 3.6 latest, and while doing so I kept the middelware loading the same:

	->add(RoutingMiddleware::class);

### What happened
$app going into the middleware is null (see https://github.com/cakephp/cakephp/pull/12739).
This silently fallbacks to some weird thing where now no plugin routes are loaded anymore in Web requests. CLI works fine, though.

So it seems that this is not so bc after all, and as such dangerous to be kept silent.

### What you expected to happen
That it still loads the plugin routes.
Or maybe some deprecation warning here if `$app === null` to make it easier to know that it now requires the $app to be actually passed as object to load plugin routing.

As

	->add(new RoutingMiddleware($this, '_cake_routes_'))

fixes the issue

**Comment by Iandenh** [comment]
On #12557 this was also the issue. I think a deprecation warning is a good idea.

**Comment by dereuromark** [comment]
Yeah, I also didnt find anything about this in the migration guide https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html

**Comment by markstory** [comment]
We could add a deprecation warning to `master` if you think it would help others.

**Comment by dereuromark** [comment]
I think even a deprecation warning is not enough if functionality doesnt work anymore at all (in this case the plugin routing).
But I think it would be a fair start

Added some migration notes about it on top here: https://github.com/cakephp/docs/pull/5897

**Comment by markstory** [comment]
Pull request open on master. I'm happy to move to 3.next if folks are concerned about adding a new deprecation warning in master.

**Comment by ADmad** [comment]
I would prefer moving it to 3.7.
