### ISSUE TITLE
Using the Flash component for automatic downloads

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#12751]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

The use case I'm interested in is a POST form that delivers a file when submitted. I want the POST to redirect to some page displaying a Flash message like "Your download will start shortly", and then the download starts without user intervention.

I don't want to have a dedicated download page just like there's no dedicated page for Flash messages. They just happen on whatever page you are.

The implementation would be like "$this->Flash->setDownload($url, $time)" and the beforeRender callback in FlashHelper would set the meta refresh tag. It's an early idea.

Would that be interesting for CakePHP (with my PR) or do you think it would be best implementing it in the app space?

**Comment by dereuromark** [comment]
I dont think this is part of flash messagings.

Instead, this would be its own plugin and component and could also leverage the session etc.
But definitely not core material, either.

Feel free to create your own plugin and then announce it via awesome list.

**Comment by berarma** [comment]
@dereuromark, it's easy to agree with you. But it's so specific that I don't think it deserves its own plugin.

I was thinking about a way to make it into a plugin that was worth it and I've had an idea. I think this could already be done. The Flash component may be flexible enough as it is. I could define a Flash message template that calls the HtmlHelper to set a meta tag and displays the "Your download will begin shortly". I'll try it tomorrow.

So easy... but the Flash documentation is so centered around messages (naturally because that's what it's meant for) that it's easy to overlook its power.

**Comment by ADmad** [comment]
> But it's so specific that I don't think it deserves its own plugin.

Same argument can be used in favor of not having it in core. Code for catering to very specific use case is not some that belongs in core.

FlashComponent does the job well it's intended for. Please make your own component for your augmented use case.

**Comment by berarma** [comment]
@ADmad, in my defense, I didn't intend to bend the core to my needs. By specific I meant that it was a very simple task but I thought that it may be of interest to many. Maybe it's not.

**Comment by dereuromark** [comment]
No. Edge cases, even if simple, should first find a plugin solution.
If they prove to be of use for > 70% of the community, usually those can be re-evaluated for core.
Core should only cover those generic and common use cases.
