### ISSUE TITLE
Notice error in Database\FieldTypeConverter.php

### ISSUE THREAD

**Issue by Nic0tiN** [cakephp/cakephp#12766]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.9
* Platform and Target: PHP 7.1.2 x64 / MySQL 5.6 x64

Hello,

I came accros the same error message mentioned in issue [8648](https://github.com/cakephp/cakephp/issues/8648) but it looks like another case.

### What you did
When `quoteIdentifier` is On and your statement contains an aliased field, the passed `TypeMap` contains both fields name protected and unprotected by quotes. If one of those field is mapped to any type recognized by `$batchingMap` (and if there's less than 3 fields for this type), when `FieldTypeConverter` is invoked and iterates over `$this->_typeMap`, extra-quote protected field undefined in `$row` throws a Notice.

IMO, testing the field existence may not be enough. I think the TypeMap should be clean upfront.

#### app.php
```php
$datasources = [
...
  'Datasources' => [
    'mydb' => [
      'className' => 'Cake\Database\Connection',
      'driver' => 'Cake\Database\Driver\Mysql',
      'host' => 'localhost',
      'user' => 'myuser',
      'pass' => 'superpasswd',
      'database' => 'mydb',
      'quoteIdentifiers' => true
    ]
  ]
...
];
```

#### Controller
```php
$tbl = TableRegistry::getTableLocator()->get('Tables');
$results = $tbl->find()->select([
	'floatField' => $tbl->find()->func()->sum('intField'), // Float type is defined in batchingMap
	//'duplicatedFloatField' => $tbl->find()->func()->sum('intField'), // Uncomment to avoid notice thrown by FieldTypeConverter.
	'stringField' => $tbl->find()->func()->substr(['strField' => 'identifier', '-4' => 'literal']), // String type is ignored as not defined in $batchingMap
])
->toArray();
```

### What happened
An Notice message is thrown 
```
Notice (8): Undefined index: `field` [CORE\src\Database\FieldTypeConverter.php, line 135]
```

### What you expected to happen
No Notice message...

**Comment by markstory** [comment]
How could someone reproduce his problem.  I am not entirely clear on how to trigger the error. Is it enough to have identifier quoting enable and use the same field in two different aggregations?

**Comment by Nic0tiN** [comment]
I wrote a test to reproduce the bug with CakePHP 3.6.13

#### Cake\Test\TestCase\Database\QueryTest
```php
    public function testAliasFieldTypeConverterNotice()
    {
        $this->loadFixtures('Profiles');

        $tblProfile = TableRegistry::getTableLocator()->get('Profiles');

        $tblProfile->getConnection()->getDriver()->enableAutoQuoting(true);
        $results = $tblProfile
            ->find()
            ->select([
                'sumUsers' => $tblProfile->query()->func()->sum('user_id')
            ]);
        debug($results->execute()->fetchAll());
    }
```

**Comment by markstory** [comment]
Shouldn't you be calling `fetchAll('assoc')` to get an associated array? When you specify aliases and then fetch a numerically indexed result set the FieldTypeConverter cannot effectively cast your data. Have you tried `fetchAll('assoc')` as that is working for me?

I've added your test in 9a26183eccaa59a0fdef4c00ce698df184032c35 with a small change to get associated results as numerically indexed results are not going to work.

**Comment by Nic0tiN** [comment]
That work but if I call `CollectionInterface::sumOf` on the collection, the `CollectionTrait::sumOf` calls `toList()` and throws the notice.

**Comment by markstory** [comment]
Could you give me the code that gives you a notice error?

**Comment by Nic0tiN** [comment]
In my case, the Notice error appears only when I put a breakpoint at the line in View.

### In Controller
```php
        // Loading hour data
        $tdbHours = TableRegistry::getTableLocator()->get('Accounting.TdbHours');
        $hours = $tdbHours->find()->select([
            'amount' => $tdbHours->find()->func()->sum('centiemes_h/100')
        ])->where(function (QueryExpression $q) use ($tasks) {
            return $q->or_([
                'affaire IN' => $tasks,
                'compte_ana IN' => $tasks
            ]);
        })
            ->orderAsc('rob_annee');
```

### In View
```php
<?= $this->Html->link($this->Number->currency($hours->sumOf('amount')), ['controller' => 'hours', 'action' => 'view', '?' => ['task' => $jobs->id_job]], ['target' => '_blank']); ?>
```

**Comment by markstory** [comment]
If the error only appears if there is a breakpoint I don't think its a reproducible issue that we can realistically solve.

**Comment by Nic0tiN** [comment]
I agree. That notice appears upon very special circumstances and, as long as it doesn't poluate the server logs (which isn't), I can live with that.

**Comment by it-mob** [comment]
Just a short update to mention that if you pass the query results of the following snippet in JsonView, without applying `Collection::toArray()`, that triggers the Notice in the event logs and interrupts the execution.

```php
        // Loading hour data
        $tdbHours = TableRegistry::getTableLocator()->get('Accounting.TdbHours');
        $hours = $tdbHours->find()->select([
            'amount' => $tdbHours->find()->func()->sum('centiemes_h/100')
        ])->where(function (QueryExpression $q) use ($tasks) {
            return $q->or_([
                'affaire IN' => $tasks,
                'compte_ana IN' => $tasks
            ]);
        })
            ->orderAsc('rob_annee')
            ->toArray(); // Avoid Notice and allows data in JsonView

        $this->set(compact('hours'));
        $this->set('_serialize', ['hours']);
```
