### ISSUE TITLE
PURGE method in Http Client

### ISSUE THREAD

**Issue by chuyenim** [cakephp/cakephp#12778]
Please add PURGE method to Http Client or allow creating a request with custom method.

**Comment by markstory** [comment]
Are you looking for a `purge()` method on the client? You can build your own request object and use [send()](https://api.cakephp.org/3.6/class-Cake.Http.Client.html#_send) to send the request. I don't see anything that would stop you from building a request with the PURGE method and sending it.

**Comment by ADmad** [comment]
Closing due to lack of response.
