### ISSUE TITLE
Entity of BelongsTo association empty when using innerjoin with match and specifying select fields

### ISSUE THREAD

**Issue by davalb** [cakephp/cakephp#12771]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.13
* Platform and Target: apache, mysql

I used `innerJoinWith` in combination with `select`.

The belongsTo association was empty. (the _matchingData-property was set - but it is now what I expected). I will post a PR shortly with a test, that demonstrates the problem.

I expected the belongsTo association entity to be present

**Comment by markstory** [comment]
The `innerJoinWith()` method wraps `matching()` which why the `_matching` property is populated and not your association property. If you want to select fields from an association use `contain()` and use `select()` to subset the fields.
