### ISSUE TITLE
CTP file takes time to load the page.

### ISSUE THREAD

**Issue by narasimhakamath** [cakephp/cakephp#12789]
I'm using CakePHP 1.3 and I'm having issues with the loading of the page.

I have a controller which gives me the required data that I need to populate into the DataTable (jQuery library for UI tables). The controller gives me a huge data of about 2088 array with arrays inside it. I have also created a .ctp file for the controller where I have added a script with a $(document).ready(function() {} ) with a console.log written in it. 
I also have an h1 tag outside the script with a text inside it.

Once the URL is hit for that view file, the page takes a while to load. It takes about 8-10 seconds for the console.log line written inside the ready function to be executed.

I'm not really sure why this is happening since all the queries I checked which PHP was hitting in the SQL log file and ran the same queries in phpMyAdmin, they take a maximum of 1-2 seconds in total (all of the queries).

I don't know if I'm doing anything wrong in the controller for the slow rendering of the .ctp file. Please let me know what could be done in the above case. 

At first I thought it was the DataTable issue and had raised an issue in the DataTable forum. I tried those options mentioned in those comments, but it didn't make any difference to the time at all.

I optimized a lot of code by fetching only the required fields from the database whenever I'm performing a find operation. It did make the timing a bit better in the Network tab of Dev Tools of Google Chrome. But again, the UI takes too long and I'm looking for a feasible solution for the above issue.

Thanks in advance.

**Comment by markstory** [comment]
CakePHP is unsupported. Sounds like you should explore using a tool like debug profiling to get more accurate data.
