### ISSUE TITLE
Adding base64urlEncode/base64urlDecode methods to the Text class

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#12785]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I'd like to add support for the base64url encoding as described in https://tools.ietf.org/html/rfc4648#page-7.

As a suggestion:

 - Text::base64urlEncode($string, $padding = true)
 - Text::base64urlDecode($string, $strict = false)

Do you think it's suitable for this class?

**Comment by dereuromark** [comment]
I am not sure those methods are needed often enough to warrant a core addition.
What's wrong with adding those to plugins, e.g. [Toosl.Utility](https://github.com/dereuromark/cakephp-tools/blob/master/src/Utility/Utility.php) class etc.
This way it is easily opt-in without having to be in the core API.

**Comment by berarma** [comment]
I thought they were a better fit for the Text class. There's nothing wrong except perhaps having methods randomly grouped in several libraries/classes. It makes it harder to find.

**Comment by dereuromark** [comment]
You can make even your own plugin, but based on package principles a bit of grouping is usually better than too much clustering, especially for maintainability.
In the end, I would just find a spot to put it for reusability.
