### ISSUE TITLE
Add support for filling Form data

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#12792]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.0

### What you did

I created a Form class and wanted to fill it with some default data before presenting it to the user.

For example I have a contact form with a reply-to email field and I'd like to fill it with currently logged in user's email address.

### What happened

The only way to set default values for my fields is with `_buildSchema` but this doesn't allow to set values fetched from a datasource dynamically.

I'm aware that I could fill request data (`$this->request = $this->request->withData()`) but it feels wrong and I don't want to do this.

### What you expected to happen

I'd like to be able to fill my form with data before sending it to the view.

For example:
```php
//Controller

public function contact() {
    $form = new ContactForm();
    $form->setData(['email' => $identity->email]);
    if ($this->request->is('post')) {
        //send message
    }
    $this->set('from', $form);
}

**Comment by ADmad** [comment]
`Form::setData()` has already been added in 3.7.0.

**Comment by robertpustulka** [comment]
LOL, sorry :)
