### ISSUE TITLE
Property _transportConfig does not exist

### ISSUE THREAD

**Issue by michal-fordonski** [cakephp/cakephp#12797]
Hi, after update to 3.7 from 3.6 i have error: Property _transportConfig does not exist. Can You help me?

**Comment by HelloBytes** [comment]
You have to update debug kit also, not documented yet.
"cakephp/debug_kit": "^3.17.0",

**Comment by michal-fordonski** [comment]
> You have to update debug kit also, not documented yet.
> "cakephp/debug_kit": "^3.17.0",

Thx. It works ;)
