### ISSUE TITLE
[RFC] Form widget override/customize (input type date datetime-local month ...)

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#12817]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.13
* Platform and Target: LNPM

This discussion was ongoing for the last years, as far as I can tell. Reference tickets might be:
https://github.com/cakephp/cakephp/issues/1888
https://github.com/cakephp/cakephp/issues/12537
https://github.com/cakephp/cakephp/issues/7254

and of course lots of stackoverflows and similar

Existing date/date-time widget is technically correct, working, however not user friendly.

Existing recommendations, such as input[type=text]+jQueryUI, [Form->text instead Form->control](https://github.com/cakephp/cakephp/issues/12537#issuecomment-418738334), or [string replacing type=text with type=date](https://discourse.cakephp.org/t/cakephp3-form-control-with-type-date/3290) are not satisfying neither systematic

[Documentation on topic of providing custom widgets](https://book.cakephp.org/3.0/en/views/helpers/form.html#adding-custom-widgets) allows users to create custom implementation, however that requires every Form control call to be annotated with correct widget type, which is again unpleasant.

Would it be possible, either by documentation or new feature, to override default widgets (either configuration override or subclassing of ie. [DateTimeWidget](https://api.cakephp.org/3.7/class-Cake.View.Widget.DateTimeWidget.html) ) to provide custom implementation to use on default field types, such as `date`, `timestamp`,  etc?

**Comment by markstory** [comment]
Are HTML5 date inputs widely supported enough that we should use them instead of multiple select boxes in 4.0? Not having to support date arrays would allow us simplify internal date handling in meaningful ways and browser pickers are a better experience than multiple select boxes are.

**Comment by smarek** [comment]
@markstory might be, but the RFC was more asking for replacing the basic widgets (not having to meddle with setting the text widget type for example, or similar), which is, as far as i can tell, currently impossible, due to the way, how those basic widgets are hard-wired in framework core.

HTML5 date/date-time widgets are not ultimate solution either, the design and accessibility is not always perfect, so being able to configure that on run-time would be nice.

Best in my opinion would be documentation, how to globally replace widget of type `date` or `datetime`, and similar, with custom implementation, so the way to solution of choice will be pretty and straightforward.

**Comment by markstory** [comment]
Om. I don't understand what is being asked for them. Currently you can use addWidget() to overwrite the existing date and time widgets. Doing so will replace the core implementation with your functionality.

**Comment by markstory** [comment]
It could be an extra sentence or two in the section on adding custom input widgets. I don't think it is necessary to have a complete example when we have an example for custom widgets already.

**Comment by markstory** [comment]
Closing as `FormHelper` has been updated to use HTML5 input types in 4.0. See #12934
