### ISSUE TITLE
Change Page Number To URL Directory For Pagination

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#12823]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: 3.6.13
* Platform and Target: Ubuntu LAMP

### What you did
I am upgrading a CakePHP 1.x site to 3.6.x

The 1.x site has URLs that are published in books, and we would like to keep the URL structure if possible

The 1.x site pagination URLs look like this

    /ledgers/index/<page_int>

### What happened
In 3.6.x the pagination URLs look like

    /ledgers/index?page=<page_int>

### What you expected to happen
I would like to be able to specify the page number location in the route, or something similar

I asked this question on Stackoverflow, however, I have not received a response so I am guessing it is not possible...

https://stackoverflow.com/questions/53778526/cakephp-3-x-possible-to-set-where-the-page-number-is-in-the-url

**Comment by markstory** [comment]
The built in paginator helper / component do not work that way. You can define a route and move the page parameter from the path to query arguments in your controller, but you will need a custom helper to generate URLs with the structure you need.
