### ISSUE TITLE
Problem when testing subfolder setup

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#12853]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.12
* Platform and Target: phpunit

### What you did
I have been having some issues with running my app from a subdirectory in the web server configuration, and am trying to adjust my unit tests to help nail this down. To this end, I set `$_SERVER['PHP_SELF']` to /folder/index.php in my `tests/bootstrap.php`.

### What happened
`TestSuite\MiddlewareDispatcher.php` is ignoring my setting, replacing it with just /, and generated URLs are wrong as a result.

### What you expected to happen
It should honour my setting, using it to determine the baseUrl, and hence to generate various URLs in the system.

`MiddlewareDispatcher::_createRequest` is generating `$environment` with `array_merge`, but it seems the order of arguments is wrong, so that the "default" PHP_SELF of / is overwriting my setting.

**Comment by saeideng** [comment]
it was added here https://github.com/cakephp/cakephp/pull/12076 for solve the PHP_SELF issue 

I think you  able to  set headers with  
```php
->configRequest(['headers'=>['PHP_SELF'=>'addYourCode']])
```

**Comment by Zuluru** [comment]
The commit note there indicates that it was added to help people who don't have it set in their tests/bootstrap.php. It shouldn't cause harm to those who do. Simply reversing the order of arguments in the `array_merge` call would allow whatever I set to propagate instead of being overwritten.

**Comment by dereuromark** [comment]
Sounds fair. You can open a PR and we can then discuss that concrete result.

**Comment by saeideng** [comment]
>Simply reversing the order of arguments in the array_merge

I dont think this could help to someone that dont have/set $_SERVER['PHP_SELF'] in their tests/bootstrap.php
but you can open a PR for more discuss

**Comment by Zuluru** [comment]
By reversing the order, it will default to the value provided here, but allow anything the user has set to override that, instead of the other way around. The code change for the PR is easy, but I always have problems running the test suite before submitting it. Working on it...

**Comment by dereuromark** [comment]
Let Travis handle the results :)

**Comment by Zuluru** [comment]
Multiple failures, but it's not clear that any of them are due to my change. Is it supposed to run clean? There's stuff about missing controllers and tables already existing that I just can't see being a result of this.

**Comment by markstory** [comment]
How are you setting php_self in your test suite requests?

**Comment by josegonzalez** [comment]
Master branch passes, so given that the failing tests are in IntegrationTestTraitTest - which is affected by routing - I believe the failing tests are due to the PR.

**Comment by Zuluru** [comment]
> How are you setting php_self in your test suite requests?

bootstrap.php: $_SERVER['PHP_SELF'] = '/testfolder/index.php';

**Comment by markstory** [comment]
@zuluru the current builds for master and 3.next are currently passing.

**Comment by Zuluru** [comment]
I see now why my first change didn't work; hadn't realized that PHP_SELF was set elsewhere during tests vs just being undefined.

I've pushed an alternate method. If that doesn't work (whether technical issues or it just doesn't "fit"), I'll look into the suggested alternative. But I feel like it's a more obscure way of doing things, so less likely that people will stumble across it than simply setting the variable in `tests/bootstrap.php`.

**Comment by markstory** [comment]
Closing as there is a pull request open.
