### ISSUE TITLE
Setting 404 response withStatus

### ISSUE THREAD

**Issue by vttn** [cakephp/cakephp#12855]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1.
* Platform and Target: Controller Action.

### What you did
I am trying to return a 404 status on a controller action using withStatus
```
            $this->response->withStatus(404);
            dd($this->response->__debugInfo());
```

### What happened
200 status is returned. Below is the degugging info
```
array:8 [▼
  "status" => 200
  "contentType" => "text/html"
  "headers" => array:1 [▶]
  "file" => null
  "fileRange" => []
  "cookies" => CookieCollection {#25 ▼
    #cookies: []
  }
  "cacheDirectives" => []
  "body" => ""
]

```
### What you expected to happen
The status is supposed to change to 404

**Comment by dereuromark** [comment]
Please read the docs on immutable responses and how to work with those.
As documented you must reassign

    $this->response = $this->response->withStatus(404);
