### ISSUE TITLE
Setting session to use cache config throws RuntimeException on PHP7.2 (CakePHP 3.4.14)

### ISSUE THREAD

**Issue by akalantari** [cakephp/cakephp#12858]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.14
* Platform and Target: Debian 9 stretch

### What you did
I tried to set sessions on the Redis Engine by setting the `defaults` values on `Session` config to `cache` as follows:
``    'Session' => [
        //'defaults' => 'php',
        'handler' => [
            'config' => 'session'
        ],
        'defaults' => 'cache',
        'ini' => [
            // Invalidate the cookie after 30 minutes without visiting
            // any page on the site.
            'session.cookie_lifetime' => 1209600
        ],
        'timeout' => 20160
    ],``

### What happened
A RuntimeException is thrown and the following warning is shown
`Warning (4096): ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() [CORE/src/Network/Session.php, line 293]`

### What you expected to happen
Sessions to be stored on Redis and managed by CakePHP

On line 111 of CORE/src/Network/Session.php it is mentioned in a comment that `// In PHP7.1.0+ session.save_handler can't be set to user by the user`, but the ini option it is not removed from the default configurations of cache and database configuration and still exists on lines 154 and 166

**Comment by ADmad** [comment]
The `3.4` series won't be getting any updates. Please test using latest `3.7` release.

**Comment by ADmad** [comment]
Closing as issue has already been fixed in #11646 and available in latest 3.7 release. Feel free to reopen if you are still having problems with latest release.
