### ISSUE TITLE
Custom finder of association is ignored when using saveStrategy "replace"

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#12859]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1
* Platform and Target: Apache, MySQL 5.6.38

### What you did
I have three Models: Article, Group, Element.
Articles and Groups have many elements:

```
// ArticlesTable.php
$this->hasMany('Elements', [
	'dependent' => true,
	'saveStrategy' => 'replace',
	'foreignKey' => 'entity_id',
	'finder' => [
		'forType' => [
			'type' => 'article'
		]
	]
]);

// GroupsTable.php
$this->hasMany('Elements', [
	'dependent' => true,
	'saveStrategy' => 'replace',
	'foreignKey' => 'entity_id',
	'finder' => [
		'forType' => [
			'type' => 'group'
		]
	]
]);
```

Here is the custom finder method:

```
// ElementsTable
public function findForType(Query $query, array $options) {
	if(!empty($options['type'])) {
		$query->where([
			$query->repository()->alias() . '.entity_type' => $options['type']
		]);
	}
	
	return $query;
}
```

So far, everything works as expected. When fetching Articles (incl. contained Elements), only the elements having `entity_type = 'article'` are fetched.

But when saving the following article data …

```
[
	'id' => 2,
	…
	'elements' => [
		[
			'content' => 'Lorem Ipsum',
			'entity_type' => 'article',
			…
		]
	]
]
```

### What happened

… all rows with `entity_id = 2` are deleted from the elements table, regardless of their `entity_type` value. In other words, the custom finder is ignored when using  `'saveStrategy' => 'replace'`.

### What you expected to happen

I expected only the Elements which have `entity_type = 'article'` to be replaced.

**Comment by markstory** [comment]
Unless you use `cascadeCallbacks` I don't think we can easily apply the finder conditions to the delete operation. The reason for this is the use of deleteAll to remove association records. See https://github.com/cakephp/cakephp/blob/d34b0d74237d2ba8d9e165fbd229113fe6c1c37d/src/ORM/Association/HasMany.php#L517-L532

The association internals don't use finder options for the proxied `exists`, `deleteAll` or `updateAll` methods. It seems possible to update the association to use finders more consistently but I think that is a pretty risky change to introduce in a bugfix release given the current (albiet sub-optimal implementation) has been around for a number of years.

I think making associations use finders internally is something we could aim to do in 4.0 (the next scheduled non-bugfix release).

**Comment by markstory** [comment]
Closing as fixing this in 3.x is pretty risky and there is now an RFC to resolve this in 4.x where we can better communicate the risk around this change.
