### ISSUE TITLE
Query::traverseExpressions() should also have $parts argument like Query::traverse()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#12864]
I wanted to do full depth traversal of just the `where` clause :slightly_smiling_face:.

**Comment by lorenzo** [comment]
sounds good to me

**Comment by ADmad** [comment]
I had actually forgotten about this ticket.

`Query::traverse()` itself doesn't have a `$parts` argument in `4.x`, instead there's a new method `Query::travereParts()`. Change was done in https://github.com/cakephp/cakephp/pull/12429.

So still ok to add `$parts` argument to `Query::traverseExpressions()`?

**Comment by lorenzo** [comment]
can't the expressions traverse their own parts?

**Comment by ADmad** [comment]
I don't remember what was use case for traversing only `where` expressions :(

**Comment by othercorey** [comment]
@ADmad Do we want to do anything for 4.1 or close it?

**Comment by ADmad** [comment]
I don't remember my use case and no else has requested for the same with any info, hence closing.
