### ISSUE TITLE
The cakephp/datasource component attempts to use the ORM component without requiring it

### ISSUE THREAD

**Issue by WilHall** [cakephp/cakephp#12862]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.14
* Platform and Target: PHP 7.1, OS X 10.14.2

### What I did
1. Set up a new project with a `composer.json` requiring cakephp/database:
```
{
    "require": {
        "cakephp/database": "3.7.1"
    }
}
```
2. `composer install`
3. Run any of the example code from the cakephp/database repository README

### What happened
Failure due to `Cake\ORM\TableRegistry` unable to be found.

This is used in the CakePHP datasource code:
https://github.com/cakephp/datasource/blob/8ac1cd771b67bca472df53aa4f4105924419d8c8/FactoryLocator.php#L17

But the `composer.json` of cakephp/datasource does not require it:
https://github.com/cakephp/datasource/blob/master/composer.json#L26

### What I expected to happen
I would expect the cakephp/datasource repository's `composer.json` to list cakephp/orm as a requirement since it is required in order to run.

**Comment by ADmad** [comment]
The FactoryLocator won't actually use TableRegistry if you explicitly set a locator beforehand. So I don't think the ORM is a hard dependency.

**Comment by ADmad** [comment]
Closing for reasons stated above.
