### ISSUE TITLE
ErrorException in FormHelper introduced in 3.7

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#12887]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.7.3, current master 8c298945e3c4299fde8189864ddace5c571b0a65

Line https://github.com/cakephp/cakephp/blob/8c298945e3c4299fde8189864ddace5c571b0a65/src/View/Helper/FormHelper.php#L1466 throws an ErrorException _Undefined index: required_.

The method sets the key required before, but only for non-hidden fields.
The code in question is actually not relevant here, as it deals with browser validation messages, and
1. The field is hidden
2. `autoSetCustomValidity` option is not set

However, a quick and dirty fix would be to check for `!empty(options['required'])` instead.

**Comment by markstory** [comment]
How can someone reproduce the problem you're seeing? We have a few tests covering EntityContext + hidden fields and the `required` key is always set.

**Comment by ypnos-web** [comment]
This is what I do:

```php
/* create hidden form that is to be altered by script */
echo $this->Form->create($data);
foreach ($data->fields as $index => $field) {
    $prefix = "fields.$index";
    /* submit id so that row is recognized and updated instead of new insert */
    echo $this->Form->control("$prefix.id", ['type' => 'hidden']);
    echo $this->Form->control("$prefix.position", [
        'type' => 'hidden',
        'id' => "field-$index" // used by sortable
    ]);
    $this->Form->unlockField("$prefix.position"); // allow JS modification
}
…
        <?= $this->Form->button('i:check '.__('Apply'), [
            'type' => 'submit',
            'bootstrap-type' => 'primary',
            'class' => 'pull-right',
        ]); ?>
…
echo $this->Form->end();
```

Pretty basic as you see.

This is what `$data` looks like:
```php
object(App\Model\Entity\Materialtype) {

	'id' => (int) 1245,
	'name' => 'foo',
	'description' => '?',
	'unit_id' => (int) 5,
	'department_id' => (int) 1,
	'created' => object(Cake\I18n\FrozenTime) { … },
	'modified' => object(Cake\I18n\FrozenTime) { … },
	'createdby_id' => (int) 1,
	'modifiedby_id' => (int) 30,
	'parent_id' => (int) 1014,
	'lft' => (int) 1022,
	'rght' => (int) 1023,
	'fields' => [
		(int) 0 => object(Cake\ORM\Entity) {

			'id' => (int) 4338,
			'materialtype_id' => (int) 1245,
			'datatype' => 'string',
			'position' => (int) 1,
			'name' => 'bar',
			'comment' => '',
			'unit_group_id' => (int) 1,
			'default_unit_id' => null,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[hasErrors]' => false,
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Fields'
		},
	],
	'[new]' => false,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [],
	'[hasErrors]' => false,
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Materialtypes'

}
```

When debugging with xdebug, I see that the Error happens with form field name `fields.0.id`. At this point, `$options` contains: type = 'hidden', empty templateVars, prepend, append, help, inline all set to false.

Does this already help?

**Comment by markstory** [comment]
Are you using a modified FormHelper? The first few lines of [control set the required option](https://github.com/cakephp/cakephp/blob/310ef2d8709a78972abb0246b01d284735bce7e0/src/View/Helper/FormHelper.php#L1159-L1170) which is why I'm probably having a hard time reproducing this issue.

**Comment by ypnos-web** [comment]
Yes I use cakephp3-bootstrap-helpers and somebody provided a fix there just in the meantime: https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/2edfd8dfc92cb3ebdadd330b86d6b0661b96e1db
