### ISSUE TITLE
Form Validation Error not appearing for multiple file upload field

### ISSUE THREAD

**Issue by spacebiscuit** [cakephp/cakephp#12895]
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

CakePHP Version: 3.6

What you did

I am validating a form field which allows multiple files to be uploaded:

`$this->Form->input('listing_images. ', ['type' => 'file', 'multiple' => 'multiple']);`

I have a custom validation provider which correctly validates the multiple images:

```
$validator ->add('listing_images', 'listing_images', [
      'rule' => [
           'dimensions', [
                'min' => ['w' => 100, 'h' => 100],
                'max' => ['w' => 1600, 'h' => 1600]
           ]
       ],
       'message' => 'Maximum image size is 1600 x 1600 pixels',
       'provider' => 'custom'
]);
```
The problem is that when validation fails the validation error does not appear below the field. If I make the file upload single file only naming the field as 'listing_images' the validation error does appear.

I suspect that the validation rule is applied to the id of the field 'listing_images' but the validation error targets the "name" of the field. since in this case they differ the error does not appear?

**Comment by markstory** [comment]
> $this->Form->input('listing_images. '

Using this as an input name is likely going to cause the FormContext to not be able to match your input field and the validation error in the entity.

**Comment by spacebiscuit** [comment]
how else is it possible to make the upload field multiple, it needs to be an array to allow multilple files to be added if I understand correctly.

**Comment by ndm2** [comment]
Better late than never I guess, for anyone reading this, what you have to do is use a regular field name without the dot, and then specify a custom value for the `name` attribute using the bracketed syntax required for PHP:

```php
$this->Form->control('images', ['name' => 'images[]', 'type' => 'file', 'multiple' => true]);
```

Errors would need to be set for the `images` field accordingly, then they will be picked up correctly by the form helper. There's no API to run rules on arrays, so you'd have to iterate and validate each file manually in custom rules, like:

```php
$validator
    ->hasAtLeast('images', 1)
    ->add('images', 'uploadedFiles', [
        'rule' => function (array $images) {
            foreach ($images as $image) {
                if (
                    !Validation::uploadedFile($image, [
                        'types' => ['image/jpg', 'image/png'],
                        'minSize' => 1024,
                        'maxSize' => 1024 * 1024,
                    ])
                ) {
                    return false;
                }
            }

            return true;
        }
    ])
    // ...
```

**Comment by markstory** [comment]
Finally got around to looking into this, and I was able to get this working with the APIs we have today, so I don't think there is anything that needs to be fixed right now.

First start with a template like
```php
<?php

use Cake\View\Form\ArrayContext;

echo $this->Form->create(
    new ArrayContext([
        'data' => $this->request->getData(),
        'errors' => $errors,
    ]),
    ['type' => 'file']
);
echo $this->Form->control('images', [
    'type' => 'file',
    'name' => 'images[]',
    'multiple' => 'multiple',
]);
echo $this->Form->submit('Submit');
echo $this->Form->end();
```

I'm using `ArrayContext` to keep the example small and self contained. This submits to a controller action that looks like.

```php
    // Rough controller action code
    public function multipleFiles()
    {
        $result = [];
        if ($this->request->is('post')) {
            $imageValidator = new Validator();
            $imageValidator->uploadedFile('file', [
                'types' => ['pdf'],
            ], 'Must be pdf');

            $validator = new Validator();
            $validator->add('images', 'valid', [
                'rule' => function ($value, array $context) use ($imageValidator) {
                    if (!is_array($value)) {
                        return 'Images must be a list of files';
                    }
                    foreach ($value as $item) {
                        $validType = Validation::uploadedFile($item, [
                            'types' => ['image/png'],
                        ]);
                        if (!$validType) {
                            return 'Must be a png';
                        }
                    }
                    return true;
                },
            ]);
            $result = $validator->validate($this->request->getData());
        }
        $this->set('errors', $result);
```

This controller action is a bit rough, but I was trying to keep the reproduction small. I've used a custom rule callback here to apply other validation methods to each item in the array.

One potential improvement I could see is that defining validation rules for lists of files is not ergonomic at all, and would greatly benefit from a method similar to `addNestedMany()`. Perhaps something like `addList($fieldName, $rule, $validatorOrOptions)`?
