### ISSUE TITLE
[3.6.*] [Minor issue] Cake bake command make error on model key belonging to another model

### ISSUE THREAD

**Issue by Bulinator** [cakephp/cakephp#12894]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.7 (known since 3.5) and probably 3.7.*
* Platform and Target: Windows (apache) / Debian 8 (nginx)

### What you did
When you try to generate a model with the command "cake bake" and your model is ending by "fs", for instance "qrefs" or "refs".
`Command: cake bake Model Qrefs`

### What happened
The generated code will defined "Qrefs" by "Qreves" into the model relation:
```
        $this->belongsTo('Qreves', [
            'foreignKey' => 'qref_id',
            'joinType' => 'INNER'
        ]);
```

### What you expected to happen
```
        $this->belongsTo('Qrefs', [
            'foreignKey' => 'qref_id',
            'joinType' => 'INNER'
        ]);
```

**Comment by ADmad** [comment]
This is an inflection issue. Since `Qref` is not a proper English word. `qref` is incorrectly pluralized to `qrevs`. You need to add custom inflection rule in your app's [bootstrap](https://github.com/cakephp/app/blob/master/config/bootstrap.php#L196).

**Comment by Bulinator** [comment]
@ADmad Ok good to know. Thanks ;)
