### ISSUE TITLE
Core makes use of Cache but it's composer.json doesn't require it

### ISSUE THREAD

**Issue by rmsj** [cakephp/cakephp#12908]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.

### What you did
I'm trying to make usage of the standalone Cakephp packages such as utility, core, etc. to be able to start migrating an application to latest version of cake. I just notice Cake\Core uses Cake\Cache but it's composer.json doesn't require it.

**Comment by saeideng** [comment]
> I just notice Cake\Core uses Cake\Cache but it's composer.json doesn't require it.

if you use `Cake\Core\Configure`  , yes it require it.

**Comment by markstory** [comment]
We could add `cakephp/cache` to the suggest list for if/when someone wants to use cached configuration files.

**Comment by markstory** [comment]
Pull request up to add the suggest and more helpful runtime errors for if/when the dependency is missing.
