### ISSUE TITLE
Cake\I18n\Time toQuarter() returns Float instead of Int

### ISSUE THREAD

**Issue by jonmc1** [cakephp/cakephp#12903]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2
* Platform and Target: apache, php 7.1

### What you did
use Cake\I18n\Time;

$date = new Time();
$quarter = $date->toQuarter();

### What happened
$quarter is a float 

### What you expected to happen
$quarter should be an int. 

The documentation says that toQuarter() returns an int but it returns a float. The value is rounded up to a whole number, but it's type is still float. This can cause problems if you're using strict comparison:
```
Time::parse('2019-01-01 00:00:00')->toQuarter() === 1 // false
Time::parse('2019-01-01 00:00:00')->toQuarter() === 1.0 // true
```
Or you could fail validation like this:
```
$validator
    ->integer('quarter')
    ->allowEmpty('quarter');
```

**Comment by dereuromark** [comment]
We should cast it then before returning.

**Comment by lorenzo** [comment]
Yeah, we should do that
