### ISSUE TITLE
Default format on custom type

### ISSUE THREAD

**Issue by sylvain-riviere-SRC** [cakephp/cakephp#12910]
Hi,

I’m actually working with a PostreSQL / PostGIS database. I’ve create a custom Point type like below :

Point.php :

```php
class Point {
	
	public $lat;
	public $lon;

	public function __construct($lat, $lon) {
		$this->lat = $lat;
		$this->lon = $lon;
	}
}
```

PointType.php :

```php
class PointType extends Type implements ExpressionTypeInterface
{
	public function toPHP($value, Driver $d) {
		return $value;
	}

	public function marshal($value) {
		if (is_string($value)) {
			$value = explode(',', $value);
		}
		if (is_array($value)) {
			return new Point($value["lat"], $value["lon"]);
		}
		return null;
	}

	public function toExpression($value) {
		if ($value instanceof Point) {
			$lat = $value->lat;
			$lon = $value->lon;
		}
		if (is_array($value)) {
			$lat = $value["lat"];
			$lon = $value["lon"];
		}
		return new FunctionExpression("ST_PointFromText", ["POINT($lon $lat)", 4326]);
	}
}
```

It works very well for INSERT/UPDATE queries, but when I try to make a SELECT query, the point field is not well formated : I got it like “0101000020E6100000B3976DA7AD0F4940E770ADF6B0EF2C40”.

What I want is to apply a custom function for the "Point" type field, like that:
`SELECT ST_AsText(Table.point) AS "Table__point" FROM table Table`

**Comment by markstory** [comment]
You will likely need to implement the `toDatabase()` hook on your Type class and return a FunctionExpression from there as well.

**Comment by sylvain-riviere-SRC** [comment]
Thanks @markstory 

I made it like that :
```php
class PointType extends Type implements ExpressionTypeInterface
{
	public function toDatabase($value, Driver $d) {
		return new FunctionExpression("ST_AsText", [$value]);
	}
	public function toPHP($value, Driver $d) {
		return $value;
	}

	public function marshal($value) {
		if (is_string($value)) {
			$value = explode(',', $value);
		}
		if (is_array($value)) {
			return new Point($value["lat"], $value["lon"]);
		}
		return null;
	}

	public function toExpression($value) {
		if ($value instanceof Point) {
			$lat = $value->lat;
			$lon = $value->lon;
		}
		if (is_array($value)) {
			$lat = $value["lat"];
			$lon = $value["lon"];
		}
		return new FunctionExpression("ST_PointFromText", ["POINT($lon $lat)", 4326]);
	}
}
```

But the toDatabase is NEVER called !

**Comment by markstory** [comment]
That is odd. The `toDatabase` method should be called when data is cast as part of query building. The [TypeConverterTrait](https://github.com/cakephp/cakephp/blob/6d5209dac6752dcf0b2d0023112c4a6dc483a0c2/src/Database/TypeConverterTrait.php#L37) which is used in [PDOStatement](https://github.com/cakephp/cakephp/blob/6d5209dac6752dcf0b2d0023112c4a6dc483a0c2/src/Database/Statement/PDOStatement.php#L69).

These lines should get hit when to try to generate queries using `Point` objects as values.

**Comment by ADmad** [comment]
Closing as the issue has gone stale and there hasn't been any follow up in a long time.
