### ISSUE TITLE
SecurityComponent not allowing multiple choice hidden inputs

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#12912]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2.

### What I did

    echo $this->Form->create(null, array(
        'type' => 'POST',
        'url' => '/my/url',
    )).PHP_EOL;
    foreach (range(0, 9) as $i) :
        echo $this->Form->input('gid.', [
            'name' => 'gid[]',
            'type' => 'hidden',
            'value' => $i,
        ]);
    endforeach;
    echo $this->Form->end();

### What happened

    <form method="post" accept-charset="utf-8" role="form" action="/my/url">
        <div style="display:none;">
            <input type="hidden" name="_method" value="POST"/>
            <input type="hidden" name="_csrfToken" autocomplete="off" value="6748..90c6"/>
        </div>
        <input type="hidden" name="gid[]" id="gid" value="0"/>
        <input type="hidden" name="gid[]" id="gid" value="1"/>
        <input type="hidden" name="gid[]" id="gid" value="2"/>
        <input type="hidden" name="gid[]" id="gid" value="3"/>
        <input type="hidden" name="gid[]" id="gid" value="4"/>
        <input type="hidden" name="gid[]" id="gid" value="5"/>
        <input type="hidden" name="gid[]" id="gid" value="6"/>
        <input type="hidden" name="gid[]" id="gid" value="7"/>
        <input type="hidden" name="gid[]" id="gid" value="8"/>
        <input type="hidden" name="gid[]" id="gid" value="9"/>
        <div style="display:none;">
            <input type="hidden" name="_Token[fields]" autocomplete="off" value="e7ecb..4c6e%3Agid"/>
            <input type="hidden" name="_Token[unlocked]" autocomplete="off" value=""/>
            <input type="hidden" name="_Token[debug]" autocomplete="off" value="%5B%22%5C%2Fmy%5C%2Furl%22%2C%7B%22gid%22%3A%229%22%7D%2C%5B%5D%5D"/>
        </div>
    </form>

After submitting:

> Notice (8): Undefined index: gid [CORE/src/Controller/Component/SecurityComponent.php, line 458]
> Tampered field 'gid' in POST data (expected value '9' but found '')

Note how `_Token[debug]` is set to `["\/my\/url",{"gid":"9"},[]]`.

### What else I tried

    // …
    echo $this->Form->input('gid.', [
        'name' => 'gid[]',
        'type' => 'text', // ← changed from 'hidden' to 'text'
        'value' => $i,
    ]);
    // …

### What I expected to happen
Expected `debug($this->request->getData())` to output below for hidden inputs as well. Currently it works with text inputs only.

    [
    	'gid' => [
    		(int) 0 => '0',
    		(int) 1 => '1',
    		(int) 2 => '2',
    		(int) 3 => '3',
    		(int) 4 => '4',
    		(int) 5 => '5',
    		(int) 6 => '6',
    		(int) 7 => '7',
    		(int) 8 => '8',
    		(int) 9 => '9'
    	]
    ]

May be related: #8170

**Comment by markstory** [comment]
I don't think anyone has attempted this before which explains why it doesn't work well. If this is a hard requirement for you, perhaps you could help expand the capabilities of SecurityComponent?

**Comment by Asgraf** [comment]
@mehov If you want to have hidden field i just use
```
//this can be changed by javascripts
$this->Form->input('yourField', ['label'=>false,'hidden'=>true]);
```
instead of
```
//no one should mess with that field!
$this->Form->input('yourField', ['type' => 'hidden']);
```
More information about hidden attribute
https://www.w3schools.com/tags/att_global_hidden.asp

> I don't think anyone has attempted before

I did and i always thought of it as a security feature.
Few of my projects even depend on this behavior!

Changing this would introduce security flaws in existing projects that depend on current behavior.
Suddenly fields that should not be editable will now become editable.

**Comment by Asgraf** [comment]
@mehov 
```
 echo $this->Form->input('gid.', [
    'label'=>false,
    'hidden'=>true,
    'options'=>range(0, 9)
]);
```

**Comment by ADmad** [comment]
Closing as the issue has gone stable and no one seems interested in enhancing SecurityComponent to support the particular use case.
