### ISSUE TITLE
Need setData() for immutable request data object

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#12926]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.6
* Platform and Target: Apache2, PHP 7.3

### What you did
$this->request->data['newKey'] = 'newValue';
Then looked around: https://github.com/cakephp/cakephp/issues/10565
used:
$this->request->withData('newKey', 'newValue');

### What happened
It set a new key - value pair - but a NEW copy was created. It did not update the existing one.

### What you expected to happen
Since there is getData() under Request Object, there should be a setData(). When using request->data, it throws a deprecated notice.

### What do you offer
I can send a PR with setData(), point is to over-write the request in-place instead of creating a new one.

**Comment by markstory** [comment]
There should not be a `setData()` requests are immutable on purpose. Modifying the data in-place would break the immutability of the request.

**Comment by saeideng** [comment]
>It set a new key - value pair - but a NEW copy was created. It did not update the existing one.

you should  re-assign request object if you need to update it
```php
  $this->request = $this->request->withData('newKey', 'newValue');
```

**Comment by karmicdice** [comment]
> There should not be a `setData()` requests are immutable on purpose. Modifying the data in-place would break the immutability of the request.

Need for discussion, maybe?

From usage point of view (also structural).
I have a field which stores url of the uploaded files (local). Uploaded fieldname is an array, but I want to handle this in a structure fashion... so, I created an Entity and performed a move_uploaded_file and using `_set` mutator, I would return the local URL. Handling files under 'Models' is bad, afaik
Ideally, I use a component which would change the `$this->request->data['fieldname'] = ` with the new string as opposed to the array.
What would be a structured way to handle such scenario?
I would have asked on Stackoverflow but I think there is no canonical answer... just yet.

Thanks

**Comment by karmicdice** [comment]
> > It set a new key - value pair - but a NEW copy was created. It did not update the existing one.
> 
> you should re-assign the request object if you need to update it
> 
> ```
>   $this->request = $this->request->withData('newKey', 'newValue');
> ```

Re-assigning is worse!

**Comment by markstory** [comment]
> Ideally, I use a component which would change the $this->request->data['fieldname'] = with the new string as opposed to the array.
What would be a structured way to handle such scenario?

Why does the new url need to go into the request? The entity has been saved with the local file path, it could now serve as the source of truth.

**Comment by dereuromark** [comment]
@karmicdice Please move the discussion into the forum or alike.
This bug tracker is not the right medium to discuss the issues you have with the request immutability as designed by fig psr. They are responsible, Cake just happens to implement this, as all other frameworks did.
