### ISSUE TITLE
Warning on insert when primary key is Date

### ISSUE THREAD

**Issue by cosarara** [cakephp/cakephp#12920]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1 and 3.7.3
* Platform and Target: apache2 (not relevant), PHP 5.6.38, MySQL 5.5.62

### What you did
I am using the CakePHP ORM only.
I have the following table:
```sql
CREATE TABLE `thing` (
	`somedate` DATE NOT NULL DEFAULT '0000-00-00',
	`someval` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`somedate`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

And the following code, which creates a record:
```php
<?php
require_once "vendor/autoload.php";
require_once("config.php"); // DB_ constants here

use Cake\Datasource\ConnectionManager;
use Cake\ORM\Locator\TableLocator;

ConnectionManager::setConfig('default', [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    'persistent' => false,
    'host' => DB_HOST,
    'username' => DB_USER,
    'password' => DB_PASS,
    'database' => DB_NAME,
    'encoding' => 'latin1',
    'timezone' => 'UTC',
    'cacheMetadata' => false,
]);

$locator = new TableLocator();
$things = $locator->get('Thing');
$thing = $things->newEntity([
    "somedate" => "2018-01-01",
    "someval" => 22,
]);
$things->save($thing);
```

### What happened
When the record is new (that is, we do an insert and not an update) PHP complains:
```
PHP Warning:  strlen() expects parameter 1 to be string, object given in /var/www/cake_test/vendor/cakephp/orm/Table.php on line 2089
```

[That line](https://github.com/cakephp/cakephp/blob/b0b9a3713720b30cd8e90c8b1a317a8294b2513a/src/ORM/Table.php#L2089) is running strlen over the values of the primary key - that is, over the following array:
```php
["somedate" => new \DateTime("2018-01-01")]
```
Now I don't know what the point of that line is, but obviously running strlen on a DateTime doesn't make a lot of sense.

### What you expected to happen
I expect no warnings.

**Comment by lorenzo** [comment]
Interesting, that’s an optimization gone wrong. Thanks for reporting!

**Comment by markstory** [comment]
Closing as a pull request is open.
