### ISSUE TITLE
Router enable/disable from controller

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#12927]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.3
* Platform and Target: Linux, nginx, PHP7.3

### Idea
For security purposes, guests and users of app, should have different routes available (configured)
ie. When the current user level (controller decision) is of some level, we might enable some routes within the base scope or disable them.

This applies for fallbacks as well (ie. having router fallbacks available for administrators, but not for registered users or public)

Is this feasible feature? Is this achievable with current state of CakePHP ? Is there any related documentation?

**Comment by dereuromark** [comment]
This already exists and is actually exactly done this way, see my [sandbox](https://sandbox.dereuromark.de/auth-sandbox).
You use prefixing and simple auth setup to assert exactly that. With [TinyAuth](https://github.com/dereuromark/cakephp-tinyauth) it is even just a matter of 2-3 lines of config.
As such, I think this can be closed.

**Comment by smarek** [comment]
@dereuromark thank you, could you maybe point out where to look? It's kind of hard to reverse the whole sandbox app.
Also if this is quite easy to do currently, I could maybe propose into cakephp/docs once I understand the concept

**Comment by dereuromark** [comment]
Specifically the Auth sandbox part. And how prefixing (admin, ...) can be used to easily switch permissions, either for authentication or authorization.
For all more, I think you should refer to irc, slack, or the forum, as this bug tracker is not a support forum.

**Comment by ADmad** [comment]
You can use [prefix routing]9https://book.cakephp.org/3.0/en/development/routing.html#prefix-routing) which allows you to easily do easily control access for various user type by checking current route prefix.

For further help please use one of the help forums.

**Comment by smarek** [comment]
@dereuromark thank you, but my idea was about modifying the common scope, not using prefixes to separate user groups. I will join the slack
