### ISSUE TITLE
SaveOrFail with errors in hasMany associated data -> "Array to string conversion" error

### ISSUE THREAD

**Issue by andres-ml** [cakephp/cakephp#12931]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

CakePHP Version: 3.7.3

Gist with necessary files to reproduce here:
[https://gist.github.com/andres-ml/93aea170698a0e1607c2cf6e135a0028](https://gist.github.com/andres-ml/93aea170698a0e1607c2cf6e135a0028)

### What you did
Save an entity with nested associations that don't pass rules check using the saveOrFail() method.

### What happened
Notice Error: Array to string conversion in [(...)/vendor/cakephp/cakephp/src/ORM/Exception/PersistenceFailedException.php, line 76]
Also, the exception's error message shows "Array" instead of an error message:
Entity save failure (association: "Array")

### What you expected to happen
At least, the error shouldn't trigger. As of how the error message should be, I'm not sure; maybe a comma-separated list of all errors.

### Possible fix
Making PersistenceFailedException::buildError recursive (line 73):
`$errors[] = is_int($key) ? static::buildError($message) : $key;`

**Comment by dereuromark** [comment]
We could also print_r($x, true) here in a non-scalar case.
