### ISSUE TITLE
Checkboxes rendered using the dot name notation share the same DOM element ID

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#12937]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2

### What you did
Render checkboxes in a loop.

```
$this->Form->input('id.', [
    'templates' => [
        'checkboxContainer' => '{{content}}'
    ],
    'hiddenField' => false,
    'type' => 'checkbox',
    'value' => $my_id,
    'label' => false,
]);
```

### What happened

    <input type="checkbox" name="id[]" value="1" id="id">
    <input type="checkbox" name="id[]" value="2" id="id">
    …

### What you expected to happen

    Avoid using same DOM element ID

**Comment by markstory** [comment]
You will have to overwrite the id attribute. FormHelper does not track id values.
