### ISSUE TITLE
Checkboxes rendered without hiddenField become mandatory with SecurityComponent

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#12938]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2

### What you did

1.

```
$this->Form->input('id.', [
    'templates' => [
        'checkboxContainer' => '{{content}}'
    ],
    'hiddenField' => false,
    'type' => 'checkbox',
    'value' => $my_id,
    'label' => false,
]);
```

2. submit without checking any of them

### What happened

> Missing field 'id' in POST data

### What you expected to happen

Have SecurityComponent figure out it's a checkbox field which may be empty, and let it go through

**Comment by mehov** [comment]
Hotfix:

```
echo $this->Form->input('id', array(
    'type' => 'hidden',
    'value' => '',
));
```
… at the beginning of the form

**Comment by markstory** [comment]
You can also mark the in field as an unlocked field to exclude it from the input name hash.

Closing as this is an intentional feature of securitycomponent and you can either use a hidden field or unlockedfields ti avoid this error.
