### ISSUE TITLE
Cookie::getExpiresTimestamp() returns string - Type error when calling `set_cookie`

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#12933]
`ResponseEmitter::emitCookies` calls `set_cookie`, which throws an `TypeError`, as the third parameter should be an `integer`.
The reason is the return value of `Cookie::getExpiresTimestamp()`, which is a `string`.
I'm not sure if we simply can change the return value of `getExpiresTimestamp` or typecast the value on the way to `emitCookies`

**Comment by ADmad** [comment]
First issue reported which is caused by strict typing, yay! :tada:

**Comment by dereuromark** [comment]
wouldnt phpstan have done the same if the code was cleaner (level4+)^^ 

jokes aside: nice work!

**Comment by ADmad** [comment]
The docblock of `Cookie::getExpiresTimestamp()` states it return string to prevent integer overflow on 32-bit systems. But even core PHP methods like `DateTime::getTimestamp()` return integer so 32-bit systems are gonna have problem one way or another when dealing with datetime/timestamps values far in future.

So I think we could just change `Cookie::getExpiresTimestamp()` to return integer.

**Comment by dereuromark** [comment]
what timestamp would cause this? must be many years in the future?

**Comment by ADmad** [comment]
> must be many years in the future?

Yup

**Comment by ADmad** [comment]
Since values than max int overflow to float PHP itself will take care of throwing error if the method has return type hint as `int`.

**Comment by cleptric** [comment]
PR open.
