### ISSUE TITLE
Restrict __ to return string in 4.x

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#12944]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: any

I would suggest redefining `Cake\I18n\I18n\__` function from`function __(string $singular, ...$args): ?string` to `function __(string $singular, ...$args): string` in cakephp 4.

I honestly can't think of any case where returning null is suitable. There is no point in returning null when you pass an empty string and not even if any translation error occurs.

Finally if you have phpstan enabled, this requires a lot of unneccessary conditions or simply adding `ignoreErrors` rule but I don't see any point in any of them

**Comment by dereuromark** [comment]
Sounds reasonable to me.

**Comment by segy** [comment]
Hi @ADmad :) No problem. I added a PR. Phpunit tests results were the same before and after the change so hopefully there won't be any other problems
