### ISSUE TITLE
Time manipulation with $time->year()->month()->day() leads to unexpected result

### ISSUE THREAD

**Issue by Tobse** [cakephp/cakephp#12940]
This is a:

* [x] bug

* CakePHP Version: 3.7.3
* Platform and Target: docker-container with php 7.2.13, Webserver: Ubuntu with php 7.1.26

### What you did
Manipulated Time-Object as described in the book: https://book.cakephp.org/3.0/en/core-libraries/time.html#manipulation. Set the month of an object to a future month.
```php
use Cake\I18n\Time;
$date = new Time('2019-02-02', 'UTC');
$time = new Time('2019-01-29 18:15', 'UTC');
debug($time); // output is time object with 'time' => '2019-01-29T18:15:00+00:00', 
debug($date->year); // output is (int) 2019
debug($date->month); // output is (int) 2
debug($date->day); // output is (int) 2

$time = $time->year($date->year)->month($date->month)->day($date->day);
debug($time); // output is time object with 'time' => '2019-03-02T18:15:00+00:00',
$time->setDate($date->year, $date->month, $date->day);
debug($time); // output is time object with 'time' => '2019-02-02T18:15:00+00:00', (as expected)
```

### What happened
When I modify the $time-Object via $time->year($date->year)->month($date->month)->day($date->day) I get the wrong month. At start, my day is "29" and setting "month" to "2" sets the "month" to "3" because there is no february, 29th. Afterwards setting "day" to "2" does not correct the wrong month.

### What you expected to happen
Following the book https://book.cakephp.org/3.0/en/core-libraries/time.html#manipulation
I expected the same result in using the chained method $time->year($date->year)->month($date->month)->day($date->day) or the "setDate" $time->setDate($date->year, $date->month, $date->day);
If I try the examples in the book at september 30th I do not get the same results either. Maybe a hint in the book would be helpful.

**Comment by markstory** [comment]
I don't think there is much we can do about this. The single property mutators have to use setDate() under the hood and as you mentioned your individual changes create an invalid date when they get to 2019-02-29.

If you reorder the method calls to be day, month, year you should get the expected results.

**Comment by Tobse** [comment]
@markstory Thank you for your reply. As I wrote down the issue I already noticed that reordering the method calls fixes the problem. It was still an unexpected behavior. In my case it crashed a reservation-system that worked till date without a problem :-) So I opened the issue for later reference if someone experiences the same.
