### ISSUE TITLE
4.x saveAll()/deleteAll() for callbacks

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#12957]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

CakePHP Version: 4+

### Status Quo
Every week people confuse deleteAll() to be a wrapper for delete() in loops.
But in fact, as atomic operations, there is no callbacks..

### Proposal
Are you open to harmonize the API here in 4.0 or 5.0 to reflect this a bit more cleanly?

- save(Entity $entity) - stays, incl callbacks
- saveMany(Entity[] $entities) - added, incl callbacks then
- delete(Entity $entity) - stays, incl callbacks
- ~~deleteAll~~ deleteMany(Entity[] $entities) - added, incl callbacks then
- updateAll($conditions) - stays as it is, atomic
- removeAll($conditions) - renamed from deleteAll(), atomic

The rename should clarify this is not as related to delete() as one might think.
The updateAll() addition clarifies that updateAll() is sth different then saveAll().

### Interface?
Do we then need the atomic operations to be part of the RepositoryInterface?
What methods are needed e.g. for abstractions like TwitterApi or Rss reading and should be part of the generic interface, which ones should go on top for more concrete cases like ORM?

### Transaction safe?
We can either keep transactional outside of the class, or we could add it by default. This example does the first:
```
	/**
	 * save() calls for multiple entities.
	 *
	 * Wrap it to be transaction safe for all save calls:
	 *
	 *  // In a controller.
	 *  $articles->connection()->transactional(function () use ($articles, $entities) {
	 *      $articles->saveAll($entities, ['atomic' => false]);
	 *  }
	 *
	 * @param \Cake\Datasource\EntityInterface[] $entities
	 * @param array $options
	 * @return bool
	 */
	public function saveAll(array $entities, array $options = []) {
		$success = true;
		foreach ($entities as $entity) {
			$success = $success & (bool)$this->save($entity, $options);
		}
		return (bool)$success;
	}
```

Looking into https://github.com/UseMuffin/Webservice/blob/master/src/Model/Endpoint.php it seems that all methods could be part of the RepositoryInterface.

**Comment by markstory** [comment]
I would prefer we don't break the API on `deleteAll` and instead add new methods that accept entity lists. `deleteMany($entities)` as an example.

Having to supply a list of entities would help make the new methods distinct and differently flexible from the existing bulk operation methods.

**Comment by dereuromark** [comment]
*Many() is instead more in sync with the existing api and what "many" means here (a collection of the same type the single one accepts). "all" is instead a bit too generic.

**Comment by ADmad** [comment]
There's already `saveMany()` which saves multiple records with callbacks inside a transaction.

**Comment by dereuromark** [comment]
Sounds like all is needed then:

- deleteMany() added

deleteAll() and updateAll() can stay the atomic operations then.

**Comment by dereuromark** [comment]
Is it also feasible to have a more strict saveMany()?

    saveManyOrFail()?

I see a lot of code silently doing 

    $this->saveMany($entities);

But it can return null and silently continue, where it should should have been logged/aborted or otherwise informing the dev/user.

**Comment by ADmad** [comment]
> But it can return null and silently continue

It never returns null. It can return `false` if saving any record fails (due to validation failure) or it can throw exception for e.g. in case of PDO exception. So it's pretty much the same like how `save()` work. If doesn't bother checking if return value is `false` it's his fault.

**Comment by dereuromark** [comment]
Yes, false, but the essence is still the same issue. Thus my question if a saveManyOrFail() that always returns array or throws exception can make sense.

**Comment by ADmad** [comment]
We do have `saveOrFail()` so I guess could have `saveManyOrFail()` too which throws exception on validation/application rules failure too.

**Comment by dereuromark** [comment]
PRs open.
