### ISSUE TITLE
Session is cleared after setting Flash message in tests

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#12958]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.3

### What you did
I have a controller action like this:

```php
//FooController.php
public function bar()
{
    $this->Flash->success('Info');
    $data = $this->request->getSession()->read('data');
    // do things with data
}
```

### What happened
While performing integration tests session data is missing and my logic fails. Session contains the flash message only. 

```php
public function testBar()
{
    $this->session(['data' => 'some data']);
    $this->post('/foo/bar');

    debug($this->_requestSession->read()); // 'data' key is no longer there
}
```

### What you expected to happen

I expected my session data stays there after setting flash messages.

### What do you think happened

`FlashComponent` stores the session object on component instantiation and operates on that object afterwards. Changing `$this->_session->...()` calls with `$this->getController()->getRequest()->getSession()->...()` seems to solve the issue so I suspect it's something related to request immutability.

**Comment by dereuromark** [comment]
Isn't there a retainSessionData flag somewhere?

**Comment by robertpustulka** [comment]
There's `enableRetainFlashMessages` but that's not it.

**Comment by markstory** [comment]
Do you have a small controller action & test method that could help reproduce this?

**Comment by robertpustulka** [comment]
I wasn't able to reproduce this on a clean app install. I narrowed it down to the DI plugin I use. This plugin provides a [custom controller factory](https://github.com/robotusers/cakephp-di/blob/master/src/Http/ControllerFactory.php) which sets the request and response after the controller is instantiated. Since FlashComponent stores it's request during constructor time, the controller and component get different request objects and different session objects.

This is a limitation to the plugin of course, but it also means that swapping the request after the controller is created will not change the request referenced in a component which can be considered as another limitation. Maybe we could change the FlashComponent behavior and get the currently referenced request from the controller itself each time the flash messages are accessed?

**Comment by markstory** [comment]
>  Maybe we could change the FlashComponent behavior and get the currently referenced request from the controller itself each time the flash messages are accessed?

I don't see why that shouldn't be possible.
