### ISSUE TITLE
Can't run PHPUnit 5 with CakePHP 2.10.15 and PHP 7.3

### ISSUE THREAD

**Issue by lucasiturbide** [cakephp/cakephp#12965]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.15
* Platform and Target:  PHP7-cli/apache

### What you did
I installed a vanilla CakePHP 2.10.15, created a new app, installed PhpUnit 5 following the documentation [instructions](https://book.cakephp.org/2.0/en/development/testing.html#install-via-composer) via composer, and executed the Core Test 

### What happened
I run `./myapp/Console/cake test core` and I get this error Message:

>Warning Error: include(PHPUnit/Autoload.php): failed to open stream: No such file or directory in [/cake2/vendor/cakephp/cakephp/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 178]

If I replace the line 178 from 
```php
include 'PHPUnit' . DS . 'Autoload.php';
```
to 
```php
include $vendor . DS . 'Autoload.php';
```
it works

### What you expected to happen
The Unit test can be executed

**Comment by markstory** [comment]
The loop above that line aims to modify the `include_path` to allow that include and other relative includes in PHPUnit to work, what is your `ini_get('include_path')` just before this include?

**Comment by lucasiturbide** [comment]
@markstory this is what the value is:
```
./cake2/Vendor/phpunit/phpunit:.:/usr/local/Cellar/php/7.3.1/share/php/pear
```

**Comment by markstory** [comment]
I am guessing that the phpunit autoload file was removed in v4 or v5 of phpunit. The change you have made will include you applications vendor/autoload.php file a second time which is isn't ideal.

Another solution could be to check for that file's existence, or to use a silence operator on it.

**Comment by lucasiturbide** [comment]
You are correct, it seems that the `PHPUnit/Autoload.php` file was removed, and without that include I am doing, it won't work, it will error out saying that PHPUnit is not installed.
Using PHPUnit 3.x won't work either, since I'm trying to use PHP 7.3 and it errors out with a different message saying that the signature of the `assert` is invalid.

**Comment by markstory** [comment]
Does your application not include `vendor/autoload.php` during its bootstrap?

**Comment by lucasiturbide** [comment]
It should, I installed cakePHP with `composer`, then created the new app, then installed PHPUnit with composer, then run  `./Console/cake test core`.
No other configuration besides the one that `cake bake` does.

**Comment by markstory** [comment]
I don't think bake, or the default application skeleton are setup to require composer's autoload.php file. Generally that is something that needs to be added afterwards in 2.x.

**Comment by lucasiturbide** [comment]
mmmm.... so it is a problem with the documentation that doesn't say anything about it?

**Comment by markstory** [comment]
There is a section [in the documentation on how to install CakePHP 2 with composer](https://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-cakephp-with-composer)

It also includes a sub-section that states

> If you’re installing any other libraries with Composer, you’ll need to setup the autoloader, and work around an issue in Composer’s autoloader. In your Config/bootstrap.php file add the following:
> ```php
> // Load Composer autoload.
> require APP . 'Vendor/autoload.php';
> 
> // Remove and re-prepend CakePHP's autoloader as Composer thinks it is the
> // most important.
> // See: http://goo.gl/kKVJO7
> spl_autoload_unregister(array('App', 'load'));
> spl_autoload_register(array('App', 'load'), true, true);
> ```
> You should now have a functioning CakePHP application installed via Composer. Be sure to keep the composer.json and composer.lock file with the rest of your source code.

Did you follow those steps?

**Comment by lucasiturbide** [comment]
Oh, I'm embarrassed 🙈 I have not seen that before. To be honest, I think this should be linked in the same page where it explains how to include PHPUnit in the project, because it leads you to a dead end.
Thanks for pointing me out to the right direction.

**Comment by markstory** [comment]
> To be honest, I think this should be linked in the same page where it explains how to include PHPUnit in the project, because it leads you to a dead end.

Feel free to update the documentation please as you know what would help in this situation :smile:

**Comment by lucasiturbide** [comment]
On the website? I don't know how to do that.

**Comment by lucasiturbide** [comment]
I am talking about this URL 
https://book.cakephp.org/2.0/en/development/testing.html

**Comment by garas** [comment]
On that page, there is pencil ✏ icon with "Improve this doc" link. Use it to suggest changes.
