### ISSUE TITLE
Inflector doesn't convert "media" to "medium"

### ISSUE THREAD

**Issue by AidanHaddonWright** [cakephp/cakephp#12968]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2
* Platform and Target: Local LAMP stack.

### What you did
I have a table called 'media' which holds references to videos and images, as well as a few join tables such as 'products_media' and 'users_media'. I added a couple of inflection rules to convert from plural 'media' to singular 'medium' and from singular back to plural, but it did not work as I expected. I added an extra rule for 'premia' to check it wasn't my own fault but that did work. So for some reason, Inflector doesn't like the word 'media'.

These are the rules I added:
```php
Inflector::rules('plural', ['/^(medi)(um)$/i' => '\1a', '/^(premi)(um)$/' => '\1a']);
Inflector::rules('singular', ['/^(medi)(a)$/' => '\1um', '/^(premi)(a)$/' => '\1um']);

debug(Inflector::pluralize('medium'));
debug(Inflector::pluralize('premium'));
debug(Inflector::singularize('media'));
debug(Inflector::singularize('premia'));
exit;
```

### What happened
The output I get is:
'media'
'premia'
'media'
'premium'

### What you expected to happen
The expected output is:

'media'
'premia'
'medium'
'premium'

**Comment by dereuromark** [comment]
https://sandbox.dereuromark.de/sandbox/inflector?string=Medium => singural to plural Media OK
https://sandbox.dereuromark.de/sandbox/inflector?string=Media => plural to singular BROKEN

Your expectations on doing the same operation again is not valid (plural on plural is not clear).
But otherwise, your issue for plural to singular on Media is true.
Are you able to provide a PR here to fix this issue?

**Comment by AidanHaddonWright** [comment]
Ah, it seems 'media' was intentionally added to the [$_uninflected](https://github.com/cakephp/cakephp/blob/master/src/Utility/Inflector.php#L158) word.

So I guess I'll close this issue :P

**Comment by dereuromark** [comment]
Ah, according to https://en.oxforddictionaries.com/definition/media it is actually more "correct" to use it as both singular and plural.
Not sure if that is also the common perception here, but at least it seems to be the official guideline.
