### ISSUE TITLE
2.x hasMany conditions overwritten

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#12978]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I'm not sure if this a bug or if it is by design.

* CakePHP Version: 2.10.11
* Platform and Target: IIS, PHP 7.1.19 (Windows), MySQL 5.5

### What you did
In model file:
```
<?php
public $hasMany = [
    'SourceFile' => [
        'className' => 'ProjectFile',
        'conditions' => [
            'SourceFile.project_file_type_id' => ProjectFileTypeID::SOURCE,
        ],
    ],
];
```

In find query:
```
<?php
find("all", [
    "contain" => [
        "SourceFile" => [
            "conditions" => [
                /** any other conditions */
            ],
        ],
    ],
]);
```

### What happened
Only the `conditions` passed in to the `contain` array are actually applied. The conditions defined in the model relationship are ignored. If no `conditions` are defined in the `contain` array, the conditions defined in the model relationship are applied.

### What you expected to happen
I expected the `conditions` passed in to the `contain` array to be merged with those defined in the model relationship.

**Comment by dereuromark** [comment]
I suspect this is somewhat historically handled. Especially since strategy "replace vs merge" was never possible here. 
Since you can set those now manually, and 2.x is in maintenance mode (critical fixes only), I recommend to just go with that approach for now and close this.

**Comment by garethellis36** [comment]
`Since you can set those now manually (redundant)`
How do you mean?

**Comment by dereuromark** [comment]
You just gave the solution:
You just set them on the contain again, dont expect merge, but replace and always set all necessary conditions.

**Comment by garethellis36** [comment]
That is not an elegant solution. It makes it pointless to even define those conditions in the model relationship in the first place.

Do you know where in the Cake code the query for the hasMany relations is built? Perhaps I could override the behaviour.

**Comment by ADmad** [comment]
> That is not an elegant solution

The 2.x ORM in an inelegant beast with lots of issues. That is why the ORM was rewritten in 3.x :slightly_smiling_face:.

**Comment by dereuromark** [comment]
> Do you know where in the Cake code the query for the hasMany relations is built? Perhaps I could override the behaviour.

You can sure try to make a PR, but we also need to be careful not to break BC here then.
Otherwise I recommend closing this as a workable solution is available as workaround until upgrading is possible.

**Comment by garethellis36** [comment]
I didn't mean a PR, I meant an override in our codebase, if it's possible. Upgrading to 3.x is never going to happen on this project.

**Comment by dereuromark** [comment]
Set a break point and use stepping through in your IDE to find out what sets those.

**Comment by garethellis36** [comment]
It's line 165 in `ContainableBehavior::beforeFind()`:
```
$instance->{$type}[$assoc] = array_merge($instance->{$type}[$assoc], $model['keep'][$assoc]);
```

The first argument is what is defined on the model, the second is what comes from the `contain` index on the find query.

Is it possible to override the instance of `ContainableBehavior` used in the application? If so I could submit a PR to separate that line into a protected method and then override locally.

**Comment by garethellis36** [comment]
Another possibility would be to allow the developer to define the behaviour in the `ContainableBehavior` config:
```
// in model
public $actsAs = [
  "Containable" => [
    "queryStrategy" => "merge",
  ]
];

// in ContainableBehavior
if (isset($this->settings["queryStrategy"]) && $this->settings["queryStrategy"] === "merge") {
  $instance->{$type}[$assoc] = array_merge_recursive($instance->{$type}[$assoc], $model['keep'][$assoc]);
} else {
  $instance->{$type}[$assoc] = array_merge($instance->{$type}[$assoc], $model['keep'][$assoc]);
}
```

**Comment by dereuromark** [comment]
Copy the core Containable into a plugin or into the app, as other devs have done, and use it from there on as your own custom solution.
No need then to modify the core anymore.

We will then close this for now.

**Comment by garethellis36** [comment]
In case anyone else has the same issue, here is how I have resolved it:

```
<?php

/**
 * If you provide a "conditions" array to a contained association in a find query
 * ContainableBehavior::beforeFind() will *REPLACE* any conditions defined on the model with those provided in the find query
 * https://github.com/cakephp/cakephp/issues/12978
 *
 * This class addresses this by merging the default conditions defined on the model with those provided in the find query
 */
class RetainsDefinedRelationshipConditionsBehavior extends ModelBehavior
{
    public function beforeFind(Model $model, $query)
    {
        $contain = $query["contain"] ?? [];
        if (!is_array($contain)) {
            $contain = [$contain];
        }

        foreach ($contain as $containedModel => $options) {

            /**
             * entries in the contain array are either numerically indexed, in which case
             * the value is just a string (the name of the linked model)
             * or the key is the name of the model and the value is an array of options, which could include conditions
             */
            if (!is_array($options) || !isset($options["conditions"])) {
                continue;
            }

            /**
             * ContainableBehavior::beforeFind() replaces the conditions by directly modifying the defined relationship on the model property
             * It "backs up" the original relationship properties in the model's `__backAssociation` property
             * We can retrieve the default conditions and merge them in with those provided in the query
             * The original relationship is restored from the back-up after the query is executed
             *
             * The associations() method just returns the relationship types, e.g. "hasMany", "belongsTo", etc.
             */
            foreach ($model->associations() as $type) {

                // relationship has not been backed up, therefore it has not been modified, so we don't need to do anything
                if (!isset($model->__backAssociation[$type][$containedModel])) {
                    continue;
                }

                // no conditions backed up for this relationship, so we don't need to do anything
                if ($model->__backAssociation[$type][$containedModel]["conditions"] === "") {
                    continue;
                }

                $model->{$type}[$containedModel]["conditions"] = array_merge(
                    $model->__backAssociation[$type][$containedModel]["conditions"],
                    $options["conditions"]
                );
            }
        }

        return $query;
    }
}
```

Then in `AppModel`:
```
    public $actsAs = [
        'Containable',
        'RetainsDefinedRelationshipConditions',
    ];
```
