### ISSUE TITLE
hasErrors() returns true if field errors array is empty.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#12974]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.3

### What you did

I set an empty error array:
```php
$entity->setError('foo', []);
```

### What happened
`hasErrors()` indicates that there are errors for this entity.
```php
$entity->hasErrors(); //true
$entity->getErrors('foo'); //empty array []
```

### What you expected to happen
I expect that `hasErrors()` return false if all fields have empty errors arrays.

**Comment by ADmad** [comment]
PR open.
