### ISSUE TITLE
EntityRoute causes MissingControllerException when :controller url part is lowercased

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#12997]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.4

### What you did
In config routes.php
```
$routes->connect('/{controller}/{action}/{id}/*', [], ['id' => '[0-9]+', 'pass' => ['id'], 'routeClass' => 'EntityRoute']);
```

1) requested `/users/view/1` in browser
2) requested `/Users/view/1` in browser

### What happened
1) MissingControllerException has been thrown
2) user view action has been called normally

### What you expected to happen
Expecting same behavior like in case of DashedRoute and InflectedRoute classes
Typing lowercase controller url part should not cause MissingControllerException

### My current workaround
In config routes.php
```

$routes->connect('/{controller}/{action}/{id}/*', [], ['id' => '[0-9]+', 'pass' => ['id']]);//extra routing without EntityRoute avoid the bug
$routes->connect('/{controller}/{action}/{id}/*', [], ['id' => '[0-9]+', 'pass' => ['id'], 'routeClass' => 'EntityRoute']);
```

**Comment by Asgraf** [comment]
Looks like copying DasherizeRoute::parse() & DasherizeRoute::_camelizePlugin() methods into EntityRoute class fixes the bug.

**Comment by markstory** [comment]
Entity route has historically not inflected parameters. I am conflicted on whether this is a big or new feature.

**Comment by ADmad** [comment]
We can make `EntityRoute` extend `DashedRoute` in 4.x, not sure what would be the best approach for 3.x.

**Comment by dereuromark** [comment]
A config flag to enable certain behavior, or a separate new route class in core or shim maybe?

**Comment by saeideng** [comment]
>We can make `EntityRoute` extend `DashedRoute` in 4.x, not sure what would be the best approach for 3.x.

I use custom Entity routing since 3.5 with body like the core
and I think this should apply on 3.x series 
```php
class EntityRoute extends DashedRoute {
```

>A config flag to enable certain behavior

:+1: 

probably we have to use set of packages/behavior 
and for every route just enable the especial behavior that we want 

I have problem when I want to use several routes
another way is applying several route class into connect/scope 
```php
         $routes->connect('/:id/:title', ['action' => 'view'],
         ['routeClass' => ['EntityRoute','DashedRoute'],'id' => '[0-9]+','pass' => ['id']]);
```
I'm not sure this idea is possible or not

**Comment by ADmad** [comment]
I am not in favor of adding config flags for something which can be handled at app level. Just create your own route class with required inflection.

**Comment by Asgraf** [comment]
Please notice the fact that currently requesting `/users/view/1` causes error message that clearly states that UsersController does not exist.
The error message gives you the path to the existing UsersController.php and instructions to create it there!
I think [this ](https://github.com/cakephp/cakephp/blob/master/src/Http/ControllerFactory.php#L87)can be real cause of this problem not the EntityRoute itself

**Comment by ADmad** [comment]
I agree that the current error message can be confusing, so it's something we should try to improve.
