### ISSUE TITLE
Enhancement Routes

### ISSUE THREAD

**Issue by lpj145** [cakephp/cakephp#12999]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x?
* Platform and Target: Web Server

### What you did
I'm thinking if Server have some way to work with multiple routes (psr-15) libraries, like nikic/fast-router, ok i'm not herege, but if open the framework to much possibilities and workaround to go, have more addopt to the community part.

### What happened
actually only possible define routes with structure, and my route cannot a invoke or function.

i'm know, todo it, some changes needed, but this is my point, on a short month i'm thinking about cake micro skeleton.

ps* i'm interested with contribute to do.

**Comment by ADmad** [comment]
PSR 15 support has already been implemented in Cake 4. So you will be able to use any PSR 15 middleware you want.

But if you don't use Cake's router then your have to take care of setting required request params yourself if you want Cake's controllers to work normally.

**Comment by lpj145** [comment]
the requested params is express in any interface ? i think if have some requiriments to work right, this needed expresse by interface. right ?

**Comment by ADmad** [comment]
No they are not.

I fail to see what benefit you are going to achieve by replacing Cake's router by another one and then setting the request params/attributes yourself which Cake's router already does for you.

**Comment by lpj145** [comment]
Ok, we can think in add callable instead array to routes ?

**Comment by dereuromark** [comment]
Can maybe someone answer the callable question here?
I think then we can probably close this.
