### ISSUE TITLE
Random issue with missing route on 3.7

### ISSUE THREAD

**Issue by ibrahimrm7** [cakephp/cakephp#12996]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.4.
* Platform and Target: CloudLinux, Maria DB on a cPanel Hosting.

### What you did
In the routes.php  i added **use Cake\ORM\TableRegistry;** and a **$this->MenuItems= TableRegistry::get('MenuItems');** to identify the alias of the URL and select the **Action** and the **Controller** i got stored in the database, and assign it in the routes.php like this **$routes->connect($alias, ['controller' => $controller,  'action' => $viewdetail]); .**

### What happened
In the 3.5 version, this solution works perfect. But, in the 3.7 Sometimes it loads properly and in other it doesn't. It is totally random. (You can try it in the next link http://dev.diarioempleo.com/log-in (You should refresh it so you will realize sometimes it loads and in others it doesn't ))

### What you expected to happen
I expect to always load the controller and the action as it should.

**Comment by markstory** [comment]
Are you using route caching? That could explain the seemingly random route behavior.
