### ISSUE TITLE
RFC: Add a CORS middleware to the core

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#13015]
Right now, it's pretty hard to implement a working solution for the CORS preflight request.
There is something in the  [book](https://book.cakephp.org/3.0/en/controllers/request-response.html#setting-cross-origin-request-headers-cors) about this topic, though.

Could we add a middleware to respond with the correct headers early in the request cycle, if an `OPTIONS` preflight request is send by the browser?

**Comment by dereuromark** [comment]
This cannot be handled on plugin level?
The [awesome list](https://github.com/FriendsOfCake/awesome-cakephp) already lists 
- https://github.com/ozee31/cakephp-cors
- https://github.com/snelg/cakephp-cors

**Comment by CauanCabral** [comment]
Or any PSR-7 compatible middleware? They should work, I think.

- https://packagist.org/packages/neomerx/cors-psr7?query=psr7%20cors

**Comment by ADmad** [comment]
Checking for an `OPTIONS` request and returning a response with required headers is, CORS or otherwise, is pretty easy.

Deciding what headers are the "correct headers" depend on your application and it's not something the framework can do you for you.

So what do you expect your proposed Cors Middleware to do? If you have a draft implementation you can create a PR for review.

**Comment by ADmad** [comment]
@CauanCabral Indeed, one can use any PSR 7 compatible middleware. That's the benefit of following standards :).

Cake 4 will also support PSR 15 middlewares.

**Comment by Asgraf** [comment]
I would expect usage similar to:
```PHP
$routes->prefix('api', function (RouteBuilder $routes) {
    $routes->applyMiddleware('cors');
    $routes->prefix('v1', function (RouteBuilder $routes) {
        //some REST api routest defined here
        //cors middleware should affect routes here
    });
});
//cors middleware should not affect routes here
//some non-api routes here

**Comment by ADmad** [comment]
@Asgraf You can do that already using any PSR-7 middleware.

For e.g. you can use [this](https://github.com/tuupola/cors-middleware) lib. Register the middleware using code similar to
```php
$routes->registerMiddleware('csrf', (new Tuupola\Middleware\CorsMiddleware([
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    // other config here
]));
```
and then apply it as you have shown.

**Comment by ADmad** [comment]
Closing as this can be easily handled at app level using already available PSR 7 middlewares and requires no addition/enhancement in core.
