### ISSUE TITLE
Sessions: session_write_close() and redirect() - data not saved on php-fpm/nginx

### ISSUE THREAD

**Issue by micdobro** [cakephp/cakephp#13018]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.0
* Platform and Target: php-fpm 7.1.26-1+ubuntu16.04.1+deb.sury.org+1, nginx 1.10.3
* Using database sessions - no specials, just plain vanilla. `session.lazy_write` Off in fpm config.

### What you did
We were doing final testing of our app after major upgrade and noticed that some code does not work as it should. The code is highly dependent on session variables as they hold the state. The script updates the state in the session just before redirecting - and then we noticed, that the variable that is written before the redirect is not written to the session itself. It does succeed after ca. 8-10 attempts. 

### What happened
I am not sure how much of a problem it is - but it's not something that is wildly discussed other places. I also have a feeling this could somehow be related to #11162. 

I can reproduce this behavior on my php-fpm setup every time. I cannot reproduce it when running on cakephp built-in server. 

The following snippet shows the problem (controller action):

```php
public function bazinga()
    {
        $this->autoRender = false; 
        $session = $this->request->getSession();                 

        if($this->request->getQuery('next') !== null) {                                  
            $sval =  time(); 
            $session->write('Bazinga.yes',$sval);                   
           // GLUE
            return $this->redirect(['controller' => 'Bazinga', 'action' => 'bazinga', '?' => ['sval' => $sval]]);            
        }

        echo "<hr>";
        echo $session->read('Bazinga.yes'); 

    }
```
If you access the url as `/bazinga/bazinga?next` it should print the timestamp recorded at the time of the redirect. But it does not. If you manage to save the timestamp - you will notice it is not changing on subsequent requests where `?next` is in the URL. 

Snippet above will work EVERY time if you add the following after `// GLUE` and before the `return` statement: 

```php
// GLUE
session_write_close(); 
return $this->redirect(['controller' => 'Bazinga', 'action' => 'bazinga', '?' => ['sval' => $sval]]);  
```
Then it works flawlessly as intended. 

Session data is written automatically on `destroy` - and if I terminate the script with an `exit;` before the return - then data is also saved correctly in the database. 

### What you expected to happen
Where does it come from. It "used to work" w/o problems on older PHP releases/Cake version. I would expect it just worked as intended - i.e. when I do `$session->write()` I would like to have that data stored in the session.

How is the `session_write_close()` administered internally by cakephp? Isn't it an idea to add it into the `Controller::redirect()` - and check whether session is started etc. and then explicitly close it? 

Are there better alternatives that could solve this problem for majority of "possible" cases?

**Comment by markstory** [comment]
Normally the session_write_close() is handled by the sapi and we don't explicitly close the session. You could use `session->close()` to close the session in a way that will it to automatically be reopened as necessary.

In older versions we would always close the session even when it wasn't open, but I think that caused some compatibility issues in newer php versions.

**Comment by markstory** [comment]
How could someone else reproduce your php-fpm setup?

**Comment by micdobro** [comment]
OS: Ubuntu 16.04 xenial

PHP from http://ppa.launchpad.net/ondrej/php/ubuntu 

Installed version 7.1 with the following modules: 
- php7.1-fpm
- php7.1-cli
- php7.1-common
- php7.1-mbstring
- php7.1-xml            
- php7.1-bz2
- php7.1-xmlrpc
- php7.1-gd
- php7.1-mysql
- php7.1-intl            
- php7.1-json
- php7.1-soap
- php7.1-curl
- php7.1-mcrypt
- php7.1-zip
- php7.1-readline            
- php7.1-opcache
- php7.1-bcmath
- php-igbinary
- php-redis

nginx - stock `apt-get install nginx-extras`. 

MariaDB 10.2 from http://fra1.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu

Relevant configs: 

Parts of nginx that show `/` and `php` configs: 

```
location / {
               try_files $uri $uri/ /index.php?$args;
        }
        
        location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.1-fpm.sock;
    }
```

PHP ini is stock, pool config below: 

```
[www]

user = www-data
group = www-data
listen = /run/php/php7.1-fpm.sock

listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 6
pm.start_servers = 3
pm.min_spare_servers = 3
pm.max_spare_servers = 5
pm.max_requests = 500

php_flag[display_errors] = off
catch_workers_output = yes
;request_slowlog_timeout = 5s
;slowlog = /var/log/php-fpm/slowlog-site.log
php_admin_value[error_log] = /var/log/fpm-php.www.log
php_admin_flag[log_errors] = on

security.limit_extensions = .php

env[HOSTNAME] = $HOSTNAME
;env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
env[HTTPS] = on

php_admin_value[memory_limit] = 192M
request_terminate_timeout = 120s
php_admin_value[max_execution_time] = 30
php_admin_value[open_basedir] = /srv/project:/tmp
php_admin_value[upload_max_filesize] = 60M
php_admin_value[post_max_size] = 65M
php_admin_value[max_file_uploads] = 200
php_admin_value[max_input_time] = 180
php_admin_flag[session.lazy_write] = off
```
I am willing to answer questions regarding that - and even configure a VPS/put a VPS online (although the 2nd option limits granting options to the people that are in cake core/their personal recommendations as I don't want the police knocking on my door at 6 am ;).

**Comment by micdobro** [comment]
There is no nginx level caching nor varnish in my setup, i.e. all requests go through plain nginx php setup.

PS Regarding "close" mishap: never post comments without enough morning coffee ;)

**Comment by micdobro** [comment]
Data is saved when the script finishes in a "normal way" as I already mentioned - it's only the redirect that causes the problem (I did some additional testing with some ajax calls). 

The following workaround fixes my problem which probably might be there in the wild and messing with session data when using it in conjunction with the redirect - and specifically here - outputting the `Location` header. 

I added the following to my `AppController.php`: 

```php
public function redirect($url, $status = 302)
{
        session_write_close(); 

        return parent::redirect($url, $status); 
}
```
I tested this behavior on some old PHP 5.5.9: works properly w/o explicit call to `session_write_close()` (that was using Cake 3.3 - but they do call `session_write_close()` in the same places - 3.7 offers though one additional function in the `Session` class, mainly `close()`). 

Following questions remain unanswered: 
- should this be a standard behavior? (`session_write_close()` in `Controller.php`)
- what could be the implications of it? (is there maybe a better place to add it? Or more places?)
- it works in cake dev server and on old release of php (5.5.9).

**Comment by markstory** [comment]
I don't think the controller should be calling session_write_close() directly as we have a session object for handling the session. It also sounds like the issue you're having is specific to php-from a it cannot be reproduced in the php server. I can try to reproduce this issue later this week.

**Comment by micdobro** [comment]
Yes, you are right - it should be `$this->getRequest()->getSession()->close();`. 

Please let me know if I should setup a VPS for testing (and send me your ssh pubkey with the request). In the meantime I will be trying to get some info from php devs - maybe they cast some light on the subject, especially that it works flawlessly with fpm 5.5.9.

**Comment by micdobro** [comment]
I did some more investigation. 

If I comment out `fastcgi_finish_request()` in `Http/ResponseEmitter.php` ca. line 66 in method `public function emit(ResponseInterface $response, $maxBufferLength = 8192)` then the `bazinga()` action works, i.e. session data is saved (I was testing that without my `AppController` modification of course). 

If I add `session_write_close()` before `fastcgi_finish_request()` - session data is again saved correctly. 

The old version of the app runs on php-fpm 5.5.9 and Apache+fastcgi - there it works no problemo. Here with php-fpm 7.1 and **nginx** this no longer works as expected. 

It looks like it's not a cake problem - but I would love to have this confirmed (or demented) by others.

**Comment by micdobro** [comment]
It begins to have a bit more sense: https://github.com/nginx/unit/issues/219

**Comment by micdobro** [comment]
It sounds ridiculous - but changing the Session engine from `database` to `redis` got it working again - i.e. data is saved w/o explicit call to `session_write_close()`. 

It looks like a latency problem where the database is too slow. I started thinking about it once I could not reproduce it using stock php session in a simple php file (in the same env of course).

**Comment by markstory** [comment]
Interesting.  With database sessions does the data go into the database but only after the redirect has been completed? Adding a session close could be something you do in application code with middleware.  I am not sure we need to modify the framework to account for application race conditions.

**Comment by micdobro** [comment]
It lands in the DB only if I explicitly call `session_write_close()` or `exit` the script. Otherwise it's not even saved (why?). One thing latency - but why it's not saved... <scratching head>.

**Comment by markstory** [comment]
Very interesting. We could probably add a [session_write_close call here](https://github.com/cakephp/cakephp/blob/57ebc5b35a6cc93219451e3819777b029d4fdc96/src/Http/ResponseEmitter.php#L66) that should solve the issue.

**Comment by micdobro** [comment]
As mentioned in https://github.com/cakephp/cakephp/issues/13018#issuecomment-467385260 - that also fixes the problem. 

Deep down here http://php.net/manual/en/function.session-write-close.php there is also an old comment that mentions what I experienced (session DB not saved consistently). 

I would expect that calling `session_write_close()` on an already closed session makes no difference.

**Comment by micdobro** [comment]
@markstory - is there anything else I can do here?

**Comment by markstory** [comment]
You could put a pull request together of the changes to ResponseEmitter, I've been a bit underwater lately and haven't had time to come back to this.

**Comment by micdobro** [comment]
Created a PR and referenced also the other issue that can be closed at the same time (same problem).

**Comment by maximumG** [comment]
@micdobro : I am so relived about your issue and pull request 😄 .

We had the same issue while migrating from apache mod_php to nginx+php-fpm running cakephp 3.6.15. I found the same thing that you (from a network capture on the FCGI server), meaning the HTTP redirect response is sometimes sent BEFORE completed the session transaction saving in database (database backend kind of slow...).

I guess that we will need to migrate to 3.7.5 from which the session flush is done before fastcgi_finish_request.

If you are interested in a a network capture showing the problem I might be able to share something.

**Comment by Railstutorialorgcryptic7** [comment]
+1



Give this a glance
