### ISSUE TITLE
Nested loop is not working properly.

### ISSUE THREAD

**Issue by issy-s16** [cakephp/cakephp#13021]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
```
$users = $this->Users->find()->all();

echo "*START\n";
foreach ($users as $outerUser) {
    echo "OUTER: {$outerUser->id}\n";
    foreach ($users as $innerUser) {
        echo "INNER: {$innerUser->id}\n";
    }
}
echo "*END\n";
```

### What happened
```
*START
OUTER: 1
INNER: 1
INNER: 2
INNER: 3
INNER: 4
INNER: 5
*END
```
when you looping the same query set twice using foreach
as inner loop finishes the task , simultaneously outer loop also stops even it hasn't finished its task.

solution would be using toArray() for the inner loop.

### What you expected to happen
expected to get nested loop results. However, outer loop stops as inner loop stops.

**Comment by markstory** [comment]
You are reusing an iterator and invalidating its loop position by rewinding and fully iterating it in the nested loop.

PHP iterators are not well suited to this usage and I don't think there is a simple solution.

**Comment by issy-s16** [comment]
Thank you.

**Comment by Asgraf** [comment]
`clone` keyword should do the trick:
```PHP
$users = $this->Users->find()->all();

echo "*START\n";
foreach (clone $users as $outerUser) {
    echo "OUTER: {$outerUser->id}\n";
    foreach ($users as $innerUser) {
        echo "INNER: {$innerUser->id}\n";
    }
}
echo "*END\n";
```

**Comment by issy-s16** [comment]
@Asgraf 
Thanks that works for me!
