### ISSUE TITLE
Add support to retrieve data from associations of _joinData (a.k.a ternary association)

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#13039]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: PHP 7.3 Mysql 5.

### What you did

 I have created a simple database with those models:
 
 _Doctors_ **belongsToMany** _Patients_ **through** _Appointments_
 _Appointments_ **hasMany** _Examinations_
 
 Full SQL: https://pastebin.com/9fY8Vibx
 
As you can see, I have a classic "ternary association".

So, I have tried to create a kind-of report showing _all doctors with theirs appointments date including patient name and a list of requested exams_

**Controller**:

```php

$table = TableRegistry::getTableLocator()->get('Doctors');
        
        $data = $table->find()
                ->contain('Patients')
                ->contain('Appointments.Examinations'); //Error !
        
        $this->set(compact('data'));
```

**Template:**

```php

<?php

echo "<table>";
echo $this->Html->tableHeaders(['Doctor','Patient','Appointment Date', 'Exams']);

foreach ($data as $doctor){

    echo "<tr>";
    echo "<td rowspan='".count($doctor->patients)."'>".$doctor->name."</td>";
    foreach ($doctor->patients as $key => $patient) {
            if($key == !array_key_first($doctor->patients)){
                echo "<tr>";
            }
            echo "<td>".$patient->name."</td>";
            echo "<td>".$patient->_joinData->date."</td>";
            //$exams = array_column($patient->_joinData->examinations, 'name'); //Error !
            //echo "<td>".implode('; ', $exams); //Error !
        echo "</tr>";
    }
    
}

```

### What happened

The "pivot" table it is not associated with doctors so it is no possible to reach by the "normal" way the associated data of this _joinData

### What you expected to happen

Be able to get Associated data from a model defined using "setThrough". 
Some changes could be applied on **findAssociation()** to "infere" (like a OWL Reasoner) that Doctors (or Patients) has a association with Appointments thanks to the association belongsToMany  
This data would be accessed on _joinData like regular entities when you choose to use contain() or maybe a new Query method like "containJoinData"

**Comment by ADmad** [comment]
Please show your associations setup.

**Comment by celsowm** [comment]
Of course, @ADmad !

Appointments Model:

```php
class AppointmentsTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('appointments');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Doctors', [
            'foreignKey' => 'doctor_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Patients', [
            'foreignKey' => 'patient_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Examinations', [
            'foreignKey' => 'appointment_id'
        ]);
    }
}

```
Doctors Model:

```php
class DoctorsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('doctors');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsToMany('Patients')
                ->setThrough('Appointments');
    }
}

``````

Examinations Model:

```php
class ExaminationsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('examinations');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsTo('Appointments', [
            'foreignKey' => 'appointment_id',
            'joinType' => 'INNER'
        ]);
    }
}
```
Patients Model:

```php
class PatientsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('patients');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsToMany('Doctors')
                ->setThrough('Appointments');
    }
}
```

**Comment by ADmad** [comment]
Can you try calling `$table->Appointments->junction()` method before doing the `find()` call you have shown?

The `junction()` method takes care of setting the `hasMany` association with the pivot table's model, i.e `Patients` hasMany `Appointments` in your case. Normally that's handled internally when you do a `find()` call.

**Comment by celsowm** [comment]
I've tried, @ADmad:

```php
class TestsController extends AppController {
    
    public function index(){
        
        $table = TableRegistry::getTableLocator()->get('Doctors');
        
        $table->Appointments->junction();
        
        $data = $table->find()
                ->contain('Patients')
                ->contain('Appointments.Examinations'); //Error !
        
        $this->set(compact('data'));
        
    }
    
}
```
Error:

> Table "App\Model\Table\DoctorsTable" is not associated with "Appointments"

**Comment by ADmad** [comment]
Oops sorry, the call should be `$this->Patients->junction()`.

**Comment by celsowm** [comment]
No problem @ADmad !
Well, no more error on Controller, however, I've had no extra exams data on my $data:

https://imgur.com/a/LZd4nm0

**Comment by dereuromark** [comment]
PR for docs open.

**Comment by celsowm** [comment]
@dereuromark I did not understand why this issue was closed because there is a bug here:

https://imgur.com/a/LZd4nm0
https://imgur.com/a/elMqo9H

CakePHP do the query on examinations but not "attach" the data on _joinData or any place. The result is lost.

**Comment by markstory** [comment]
It looks like there is `_joinData` in the first screenshot. If you frequently access the `Appointments` and need to manipulate it separate of the Patients and Doctors, you should consider creating the required hasMany & belongsTo associations. While the `through` option can be used for lightweight operations creating distinct associations will make other parts of CakePHP like FormHelper easier to operate.

**Comment by celsowm** [comment]
@markstory There is data on ``_joinData``, but not the property "examinations" as expected. Cake did the query but have not attached in any place.

About your suggestion, I've created this example from scratch this weekend using english names and pnly few tables to exemplify a real situations that I have on my real app, about lawsuits in portuguese, with 150 tables. Sometimes we need to retrieve data from very similar situations.

**Comment by celsowm** [comment]
Hi @markstory , still "need more information" ?

**Comment by markstory** [comment]
@celsowm I've not had time to look into this. These kinds of issues take a non-trivial amount of time to investigate, reproduce, debug and fix.

**Comment by celsowm** [comment]
@markstory Such a pity was labeled as defected even with screenshots showing the queries and the variables. Okay, I will try to investigate the core code by myself someday and try a solution to ternary associations.

**Comment by markstory** [comment]
@celsowm It is no fault of yours. You provided a good amount of context to reproduce this. I just haven't been able to make time to make the code locally and sidt through the orm guts.

**Comment by celsowm** [comment]
> 
> 
> @celsowm It is no fault of yours. You provided a good amount of context to reproduce this. I just haven't been able to make time to make the code locally and sift through the orm guts.

No problems, @markstory ! I am a little busy too (my first son is coming in few weeks), well maybe one day, this can be useful for you: https://github.com/celsowm/hospital-cake-php
