### ISSUE TITLE
Line breaks between rendered output of $this->Html->css and $this->Html->script

### ISSUE THREAD

**Issue by andyfoote** [cakephp/cakephp#13032]
This is a:

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Platform and Target: Platform agnostic problem. Tested on CentOS, Apache, PHP 7, Chrome.

### What you did
When using the HTML Helper to output CSS and JS files (e.g. in `/src/Template/Layout/default.ctp`) there is no line break between each statement in the rendered output. For example if you did this:

     <?= $this->Html->css('foo'); ?>
     <?= $this->Html->css('bar'); ?> 
     <?= $this->Html->css('baz'); ?>

The rendered output looks like this:

     <link rel="stylesheet" href="/css/foo.css"/>    <link rel="stylesheet" href="/css/bar.css"/>    <link rel="stylesheet" href="/css/baz.css"/> 

When you View Source on the page this format is tedious because it's easier to read if there is a line break between each asset, e.g.     

     <link rel="stylesheet" href="/css/foo.css"/>
     <link rel="stylesheet" href="/css/bar.css"/>
     <link rel="stylesheet" href="/css/baz.css"/>

The same is true of using the script helper, `$this->Html->script('some_js')`

### What happened
See above

### What you expected to happen
It would be better if the output can have a line break, as you might write it in a flat HTML file. It's much easier to read when "view source" is being used. This has actually been a long-standing issue in Cake and isn't specific to this version. I appreciate some people use things to minify their output making this seem redundant, but for development or even people learning it's far easier to read if the markup is presented in a neater way.

**Comment by dereuromark** [comment]
This is purely a presentation issue, and also only for the dev looking into the source code.
This is a non-issue for production, and there most also minify and do not use any newlines anymore.
I would not call this is long-standing "issue" to be honest, this is not even a minor improvement as you should not rely on that output. The browser itself does not care, either.

As for the technical part: The `?>` sucks up the next newline. As software developer in PHP you should know this.
The solution is therefore as simple as using either an extra newline (as most do that care for this) or somehow else fix your code here (e.g. manual PHP_EOL). You could also use a templating language like twig that can also have certain tweaks on top for this non-issue.

```
<?= $this->Html->css('foo'); ?>

<?= $this->Html->css('bar'); ?> 

<?= $this->Html->css('baz'); ?>
```

**Comment by josegonzalez** [comment]
> As for the technical part: The `?>` sucks up the next newline, this is a PHP issue itself. As software developer in PHP you should know this.

Note: As a software developer, I did not know this. Lets keep the personal remarks out of this :)

**Comment by dereuromark** [comment]
Well, if you care that much about source code presentation, you might want to.
But sure.

**Comment by josegonzalez** [comment]
Personally I use the webkit inspector/Firebug - is that still separate on Firefox these days? - so this is less of an issue :)

**Comment by andyfoote** [comment]
As a (experienced) software developer I'm fully aware of using things like the browser's development tools which take care of this.

People are learning all the time and you would be mindful that those learning CakePHP or web development may well "care that much about source code presentation" because yes, they do actually use things like "view source" in the browser, and it is handy if the markup is presented in a readable way.

I accept you might feel differently but as @josegonzalez said, there's no need to get personal about the issue. Considering your user base and people learning/new to development shouldn't be a bad thing though.

**Comment by dereuromark** [comment]
Apologies. Your "long-standing issue in Cake" sounded like a bit of a harsh critic, as such I wanted to clarify that this is a PHP issue you need to know instead of blaming the framework.
Anyway, moving forward, you will have take this up with the language itself, maybe clarify with them.

**Comment by ruslandem** [comment]
There is a way to override the template of the Html helper (in AppController initialize()):
```
$this->viewBuilder()->setHelpers([
            'Html' => [
                'templates' => [
                    'javascriptlink' => '<script src="{{url}}"{{attrs}}></script>' . PHP_EOL,
                    'css' => '<link rel="{{rel}}" href="{{url}}"{{attrs}}/>' . PHP_EOL,
                    'meta' => '<meta{{attrs}}/>' . PHP_EOL,
                    'charset' => '<meta charset="{{charset}}"/>' . PHP_EOL
                ]
            ]
        ]);
```
