### ISSUE TITLE
Change Response::getJson() to return object instead of array

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#13038]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.4.
* Platform and Target: ANY.

### What you did
Using `Cake\Http\Client\Response::getJson()` when consuming external services. 

### What happened
`Response::getJson` returns a `json_decoded` as `array`.

### What you expected to happen
Returned value as `object`.

Current behavior made sense before CakePHP 3.x, where all there things are `arrays`, but now everything are `objects`.

**Comment by saeideng** [comment]
if you need to stream object use `Cake\Http\Client\Response::getBody()`

**Comment by markstory** [comment]
The 'object' that json_decode() creates is a `stdClass` which isn't significantly better than an array. I'm also concerned about the backwards incompatibility this would create. Asking people to rework all their code that interacts with external systems is a big ask and there isn't much gain to be had.

I'd be open to having another method that provides the response decoded as an object though.

**Comment by CauanCabral** [comment]
@saeideng for sure, for now I did that and implement my own method.

@markstory that make sense, it's a huge BC break. Is reasonable put a parameter in `getBody(bool $assoc)`?

**Comment by markstory** [comment]
A flag parameter is harder to comprehend when reading code later. A separate method makes IDE usage easier too.

**Comment by CauanCabral** [comment]
I'm not confident with creating on more method if I'll be the only interested on it.

It's just more lines into code base to take care. I'll close that issue, if more people show interest, I'm volunteering to implement it.

**Comment by jicho** [comment]
Just found this "discussion". Moved from CakePHP 3.6.something to 3.7.5 and encountered the same issue... getJson() returns an array, but in my past code I had a stdClass as a result with $response->body('json_decode');

Is this going to change my new code:
```
$jsonData = $response->getJson();
```

Into
```
 $jsonData = json_decode($response->getStringBody());
```

Or remove the "true" in:
```
return $this->_json = json_decode($this->_getBody(), true);
```

Why not make the true optional in the getJson()? Oh... That's not an option (for a good reason) as I see in a comment above.

Anyway... the current change is a breaking change for my code :'(

**Comment by markstory** [comment]
You're still able to use `$response->body('json_decode')` if you want to, it will continue working as it does for the rest of 3.x. The new `getJson()` method matches the behavior of the `$response->json` property which also exposed arrays.

We could add an additional method like `getJsonObject()` to get `stdClass` instances back.

**Comment by jicho** [comment]
Yes, ```$response->body('json_decode')``` can be used, but it gives the (logical) message:
> Deprecated Error: Response::body() is deprecated. Use getStringBody()/getJson()/getXml() instead.

I don't want to turn off the "warnings" since they are very usefull :)

```getJsonObject()``` woud be a nice fix!

**Comment by ADmad** [comment]
A patch to add the new method is welcome.
