### ISSUE TITLE
SecurityComponent doesn't seem to handle redirects returned from blackhole callback

### ISSUE THREAD

**Issue by nemmons** [cakephp/cakephp#13036]
I believe that SecurityComponent::startup() should return the results of the blackhole callback ([here](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/SecurityComponent.php#L127)).

This is a (multiple allowed):
* [x] bug

* My CakePHP Version: 3.5.4 (but this issue looks current as well)
* Platform and Target: Ubuntu 16.04, PHP 7.1; issue occurs for both web and api requests

### What you did
With the following blackhole callback in AppController, i am posting to a 'store' endpoint for a controller action that IS NOT unlocked by the security component. The form being posted is not being created with the FormHelper.
```
    /**
     * blackhole
     * @param string $type
     * @return \Cake\Http\Response
     */
    public function blackhole($type, \Cake\Controller\Exception\SecurityException $Exception)
    {

        if (!$this->Auth->user()) {
            $this->Flash->error('You must login to continue.');
            return $this->redirect('/users/login');
        }

        $this->Flash->error("You are not authorized to view this page.");
        return $this->redirect($this->referer());
    }
```

### What happened
My browser is redirected and i get the "You are not authorized to view this page." flash error, which is correct. However, via debugging i can also see that the controller action is executed in full and i can see the new record inserted into the database.

### What you expected to happen
I expected to be redirected and for the controller action to not be executed (due to the form tampering protection in SecurityComponent)

### Extra Info
I have noticed that if i modify the following lines in SecurityComponent::startup()
```
} catch (SecurityException $se) {
     $this->blackHole($controller, $se->getType(), $se);
}
```
to
 ```
} catch (SecurityException $se) {
     return $this->blackHole($controller, $se->getType(), $se);     
}
```
this issue goes away.

Here's my best understanding of what's happening: Since the response from the blackhole callback is not being returned, Cake\Controller\Controller::startupProcess() has no reason to return the redirect as a response, so it just moves forward with executing the controller action. The redirect then occurs at the end of the controller action that should have been black-holed. 
The reason that the redirect is still occurring, despite the fact that the redirect was not returned correctly from the blackhole callback, was that \Cake\Controller\Controller::redirect() had mutated the controller's response object, adding the location header.

**Comment by markstory** [comment]
Adding a return should be ok. The default behavior and examples in the book all show an exception being re-raised from the blackhole callback which is potentially why this hasn't come up before. A while back there was a return but it was lost during 21cf7914617

**Comment by markstory** [comment]
Pull request open.
