### ISSUE TITLE
Saving Model with first-level BTM associations will fail silently, if the BTM field is not accessible

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13043]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.3
* Platform and Target: linux php7.3 nginx

While dev/testing i've baked three models
  - documents
  - document_types
  - document_types_documents

Having done some changes, i've manually added belongsToMany from Documents to DocumentTypes

Setting data correctly through `Form->control('document_types._ids', ['options'=>$arr])`

What was not working is saving data, and there is no warning/error about it.

DocumentsTable $_accessible was missing property `'document_types'=>true` which corresponds with belongsToMany alias, adding it fixed everything.

So I'd like to know, if it is possible to make such situation developer-detectable, that `Documents->patchEntity($document, $this->request->getData())` does not set the BTM fields (or generate appropriate entitites), because of the BTM alias/field accessibility

It is currently not even detectable from contents of `$document` (in this case) entity after patching, because neither `dirty`, `original` or other fields, that could hint such problem, do not reflect this.

Thank you

**Comment by markstory** [comment]
How would you want to find out about fields not being marshalled?

**Comment by smarek** [comment]
Well, as soon as possible, i guess /s

Either if it would be possible to handle non-accessible fields strictly (ie. trying to update such field would trigger full blown error), so I could turn that on for whole application and prevent such situations by getting rid of warnings/errors

Or at least some notice, when using `Model->patchEntity($entity, $requestData)`, possibly using non-default settings, that would produce warnings (by default turned off), or hinting in the entity fields, after patching proceeds, that some dirty fields/assocs will be ignored on save.

**Comment by markstory** [comment]
> Either if it would be possible to handle non-accessible fields strictly (ie. trying to update such field would trigger full blown error), so I could turn that on for whole application and prevent such situations by getting rid of warnings/errors

Wouldn't this make API endpoints more challenging to operate? Any unexpected field would cause an exception which doesn't create very [robust applications](https://en.wikipedia.org/wiki/Robustness_principle).

Opt-in errors and warnings could work. If you remember to enable the opt-in warnings couldn't you also check the marshalled entity as well?

**Comment by smarek** [comment]
Yes, mentioned is not robust approach, however as I said, either only in debug mode, or debug mode and having said strict validation enabled.

Well, there is a difference imho between having the framework report errors (single point of validation in ORM implementation) and having to validate every entity patching on field-level/assoc-level (a lot of validation points and an insance amount of work on the developer side)

**Comment by markstory** [comment]
Enabling a strict mode on marshalling could work. I don't think that would require debug as well though.

```php
$articles->patchEntity($article, $data, ['strict' => true]);
```

Could raise an error when any fields are part of the data that could not be marshalled into the entity graph.

**Comment by dereuromark** [comment]
I use a similar strict mode (default true here, however) for [DTO patching](https://github.com/dereuromark/cakephp-dto). Makes sense to do that for entities, too.
The only question is if this should raise exceptions or just set error() for those fields/keys.

**Comment by smarek** [comment]
@markstory as long as I could set it as default for whole application or model, without need to modify code for every patchEntity call, i'm happy.
Also I vote for keeping default strict disabled, as that would break too many existing code-bases

@dereuromark error() for said fields/keys, which will prevent successful save into database thus propagate to business logic

**Comment by dereuromark** [comment]
Yeah, don't get me wrong: Of course it has to be disabled - for this specific use case - by default :) BC reasons but also because often you do not care here too much for too much input posted (can have other reasons like referer keeping.

**Comment by markstory** [comment]
@smarek You could use inheritance to replace patchEntity() and newEntity() and set `strict` mode on all calls. The ORM doesn't really have much in the way of global configuration right now and I'm not sure this warrants adding it.

**Comment by dereuromark** [comment]
See how [Shim plugin](https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Table/Table.php#L442) did it for strict saving/deleting.

**Comment by smarek** [comment]
well, we already have `AppController`, `AppView`, `AppExceptionRenderer`
and in default configuration of datasource we have `className` and `driver`
we could, as well, have AppTable or option to set such parent globally

or could one achieve the inheritance change through changing config of datasource / something else?

**Comment by smarek** [comment]
@dereuromark ok, that is proper cool example, thank you

**Comment by dereuromark** [comment]
For app level Table I use simple aliasing
```php
namespace App\Model\Table;

use Cake\ORM\Table as CoreTable;

class Table extends CoreTable {
```

Then just use this Table instead of core Table class (in your use statements).

**Comment by smarek** [comment]
This issue is still relevant, i'm pro using the proposal from https://github.com/cakephp/cakephp/issues/13043#issuecomment-472849027

**Comment by markstory** [comment]
@smarek Would you be interested in putting together a pull request to improve this scenario? It previously went stale because no one has taken initiative to fix it.

**Comment by smarek** [comment]
Yes, i'm interested, but probably won't be able to for at least few weeks now. I'll try to get back to this issue, if you leave it open.
