### ISSUE TITLE
2.x - deleting dependent HABTM records ignores conditions defined on the model

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#13046]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.15
* Platform and Target: PHP 7.2, IIS, Windows

I'm trying to create a single table to house all `tag` relationships. So we have a `tags` table with fields `id` and `name`, and then `tagged_entities` table, which has fields `entity_type`, `entity_id`, `tag_id`. This way we can attach tags to multiple models in the application without having to have a join table for each relationship.

The relationship is created automatically in `AppModel::__construct()`:

```php
<?php
        $this->bindModel(
            [
                "hasAndBelongsToMany" => [
                    "Tag" => [
                        "joinTable" => Inflector::tableize(TaggedEntity::class),
                        "conditions" => [
                            TaggedEntity::class . ".entity_type" => $this->useTable,
                        ],
                        "foreignKey" => "entity_id",
                        "with" => TaggedEntity::class,
                    ],
                ],
            ],
            false
        );
```

The provided `conditions` enable the `contain` usage with `Model::find()` to work as expected.

However, when I call `Model::delete()` on a 'taggable' entity, it cascades the deletes to the join table and ignores the `conditions`.

The code responsible for this is `Model::_deleteLinks()`:

```php
<?php
	protected function _deleteLinks($id) {
		foreach ($this->hasAndBelongsToMany as $data) {
			list(, $joinModel) = pluginSplit($data['with']);
			$Model = $this->{$joinModel};
			$records = $Model->find('all', array(
				'conditions' => array($Model->escapeField($data['foreignKey']) => $id),
				'fields' => $Model->primaryKey,
				'recursive' => -1,
				'callbacks' => false
			));

			if (!empty($records)) {
				foreach ($records as $record) {
					$Model->delete($record[$Model->alias][$Model->primaryKey]);
				}
			}
		}
	}
```

It is a fairly straightforward fix to address this, and I do not think this would be breaking BC. I am happy to submit a PR.

Revised version would look something like:

```php
<?php
	protected function _deleteLinks($id) {
		foreach ($this->hasAndBelongsToMany as $data) {

            $defaultConditions = isset($data["conditions"])
                ? ($data["conditions"] ?: array())
                : array();
		    
			list(, $joinModel) = pluginSplit($data['with']);
			$Model = $this->{$joinModel};
			$records = $Model->find('all', array(
				'conditions' => array_merge($defaultConditions, 
                    array($Model->escapeField($data['foreignKey']) => $id)
                ),
				'fields' => $Model->primaryKey,
				'recursive' => -1,
				'callbacks' => false
			));

			if (!empty($records)) {
				foreach ($records as $record) {
					$Model->delete($record[$Model->alias][$Model->primaryKey]);
				}
			}
		}
	}
```

**Comment by markstory** [comment]
I agree that the current behavior isn't great. My worry around changing this is that the current behavior has been in place for 7+ years and changing it now creates risk, when 2.x is effectively in maintenance mode.

**Comment by garethellis36** [comment]
I also realised after I posted that the conditions on the model can also refer to other tables besides the join table (in my example the `tags` table), in which case the example updated code would not work. Could we at least extract the conditions to a protected method to make the local override a bit less of a copy-pasta?

**Comment by markstory** [comment]
> Could we at least extract the conditions to a protected method to make the local override a bit less of a copy-pasta?

That sounds doable if you have the time/interest.
