### ISSUE TITLE
Custom label setting for control[type=radio]

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13045]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: LAMP

### What you did
I tried to generate radio options:
```
echo $this->Form->radio(
    'favorite_color',
    [
        ['value' => 'r', 'text' => 'Red', 'label' => ['style' => 'color:red;']],
        ['value' => 'u', 'text' => 'Blue', 'label' => ['style' => 'color:blue;']],
        ['value' => 'g', 'text' => 'Green', 'label' => ['style' => 'color:green;']],
    ]
);
```

### What happened
Labels around inputs were generated without custom attributes

### What you expected to happen
Each label has own custom style attribute

**Comment by andrii-pukhalevych** [comment]
I created [PR](https://github.com/cakephp/cakephp/pull/13044) 
But it cant pass appveyor tests due time limit: Build execution time has reached the maximum allowed time for your plan (60 minutes).
Please manually process this PR

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/cakephp/pull/13044 open
