### ISSUE TITLE
FormHelper::error() does not respect passed 'escape' option

### ISSUE THREAD

**Issue by savedario** [cakephp/cakephp#13053]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.16 (commit 4fd57b86ca2263ac39ed66a278cd1f058b6d550e)
* Platform and Target: Apache2, MySQL

In a View I set the following:
```
		$this->Form->inputDefaults( [
			'error' => [
				'attributes' => [ 'class' => 'my-error-class' ],
				'escape' => false,
			]
		]);

```
The 'attributes' option is applied to all the generated inputs, but the 'escape' option never makes it to  FormHelper::error(). In my tests, the same happens when the 'error' option is specified when calling FormHelper::input();

If I change  how the error() method is called (around line 1069) from:

```
$errMsg` = $this->error($fieldName, $error);
```
to:
```
$errMsg = $this->error($fieldName, null, $error);
```

my error message appears with HTML inside.

Happy to submit a pull request...

**Comment by savedario** [comment]
Relates to issue ##8821

**Comment by dereuromark** [comment]
Yes, looks like a backport seems necessary.
If you can, please open a PR here.

**Comment by savedario** [comment]
It turns out the change was not as painless as I thought, mainly because the error() method has a 'funny' way to deal with its options.
If I use the 'error' option like this:
```
		$this->Form->inputDefaults( [
			'error' => [
				'attributes' => [
                                    'class' => 'my-error-class' ,
                                    'escape' => false,
                               ]
			]
		]);
```
it works as expected.
I added 2 tests for this in the pull request, if you still think to merge...
