### ISSUE TITLE
loadModel with fully qualified name of class

### ISSUE THREAD

**Issue by samuelszabo** [cakephp/cakephp#13069]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: built-in webserver

### What you did
```php
$this->loadModel(ProductsTable::class);
$this->Products->find();
```

### What happened
`Call to a member function find() on boolean`

### What you expected to happen
It would be great if I can _optionally_ load model directly by fully qualified name. We have an application with 300+ table classes divided into tens of plugins. For me, the top reasons are:
- ease of pointing to table (thanks to class names autocomplete)
- easier refactoring (changing model name)

Also, `TableLocator::get()` accept fully qualified name.

**Comment by dereuromark** [comment]
As a side note:
I dont like that loadModel silently returns false here. Much better would be to throw meaningful exception in such cases (in 4.x)?

**Comment by celsowm** [comment]
Would be nice for **contain()** too :)

**Comment by saeideng** [comment]
>But this is fixed in 4.0 afaik.

no
```php
//debug($this->loadModel('InvalidExample'));
object(Cake\ORM\Table) {

	'registryAlias' => 'InvalidExample',
	'table' => 'invalid_example',
	'alias' => 'InvalidExample',
	'entityClass' => 'Cake\ORM\Entity',
	'associations' => [],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

}
```

**Comment by saeideng** [comment]
this is useful when someone need to load a Model , but he did not bake(create ) it 
but in other side this is painful for someone that uses incorrect file name (model file name) and silent ignoring the model and hard debugging

**Comment by dereuromark** [comment]
fixed = not returning false (no object)

**Comment by saeideng** [comment]
same return  in cake 3.7.x

**Comment by dereuromark** [comment]
I don't think that is true for all cases.
See the above "Call to a member function find() on boolean" error message.
My point still stands, that should never happen ideally.

**Comment by samuelszabo** [comment]
Guys, I think we have three subjects here. To make conversation a little bit clearer, let me make a quick summary.

(a) An option to loadModel with fully qualified name of a class, which is an enhancement.

(b) As @dereuromark pointed, loadModel with invalid argument silently returns false and should throw an exception ([this is fixed in 4.x](https://github.com/cakephp/cakephp/blob/2341c3cd7c32e315c2d54b625313ef55a86ca9cc/src/Datasource/ModelAwareTrait.php#L114))

(c) As @saeideng pointed, loadModel with _InvalidModel_ string, which returns `Cake\ORM\Table` object. I think it can solve [Disabling Generic Tables](https://book.cakephp.org/3.0/en/development/configuration.html#disabling-generic-tables), am I right?

**Comment by dereuromark** [comment]
Silent Table fallback is FINE imo, part of RAD :)
So yeah, basically only a) remains for 3.x here.

**Comment by ADmad** [comment]
Allowing `ModelAwareTrait::loadModel()` sounds okay to me, though not sure about `TableLocator::get()`. 

If were to allow using FQCN for `TableLocator::get()` people might expect being able to using it for other methods of locator too.

**Comment by samuelszabo** [comment]
@ADmad Yup, that's right. It will be ok for me; I found using FQCN more natural.

But back to this case, what if loadModel change FQCN to _Cake style_ `plugin.model`, so there is no need to change `TableLocator::get()`?

**Comment by dereuromark** [comment]
@ADmad Couldnt we still make a instance of check for RepositoryInterface etc?
This way you also couldnt accidentally load like a similar kind of class of some totally unrelated namespace.

**Comment by ADmad** [comment]
So the reason you got `Call to a member function find() on boolean` error is because `$this->loadModel(ProductsTable::class);` did load the table but with alias and property name `ProductsTable::class`.  So your table is now available using `$controller->{ProductsTable::class}` :slightly_smiling_face:.

The error message was triggered as you were using a non existent property which triggered `Controller::__get()` which returned `false`.

**Comment by samuelszabo** [comment]
Yup, that`s right. It looks like a bigger issue then I thought first.

The problem here (`$controller->{ProductsTable::class}->find()...`) is, you will get error, e.g.:
```sql
PDOException : SQLSTATE[42000]: Syntax error or access violation:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB
server version for the right syntax to use
near '\Model\Table\ProductsTable.id AS `App\Model\Table\ProductsTable__id`' at line 1
```
So the real subject of this task should be:
- aliasing in loadModel (I expect to use `Products` alias, `$this->Products->find()..`)
- proper table naming in TableLocator (I guess)

**Comment by dereuromark** [comment]
@samuelszabo What is the reason you like and want to use FQCN here? is it autocomplete?
Then I would just recommend you using IdeHelper and have autocomplete on all the magic strings here, makes it even way faster than your FQCN approach:

![autocomplete_loadmodel](https://user-images.githubusercontent.com/39854/55065070-75427580-507b-11e9-8e44-52ce74e1648d.png)
![autocomplete](https://user-images.githubusercontent.com/39854/55065075-77a4cf80-507b-11e9-8985-a0256325f410.png)

**Comment by samuelszabo** [comment]
@dereuromark This is a great point, I forgot about IdeHelper. Yes, it may be faster, we had tried it a year ago, but in our case (428 tables/table classes) it makes phpstorm recognizably slower.

**Comment by dereuromark** [comment]
I hope that new versions of it use better caching :)

**Comment by sukihub** [comment]
> What is the reason you like and want to use FQCN here?

In a similar fashion, do Cake names have any advantages over FQCN? It was a great solution for php < 5.5, but maybe it's not necessary anymore?

(full disclosure, I work with @samuelszabo so it's not 2 people coming to same conclusion independently :)

**Comment by dereuromark** [comment]
> do Cake names have any advantages over FQCN?

As I just mentioned: They do, if you use IdeHelper and autocomplete. The dropdown list will only display the applicable ones, not just all possible FQCN classes in your whole system :)

**Comment by ADmad** [comment]
Even without the `IdeHelper` short names are more convenient to use is smaller projects. This is why in most places we allow using both short names and FQCN. This method was one of the few exceptions which didn't allow FQCN.
