### ISSUE TITLE
Folder / File ownership

### ISSUE THREAD

**Issue by mp155** [cakephp/cakephp#13063]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: Ubuntu 18.04, LAMP stack managed with Ispconfig 3, 

### What you did
1/ based on ispconfig, web server is running as web34:client12
thus folder structure on webroot: 
# pwd
/var/www/clients/client12/web34/web/webroot

2/ I set up chmod g+s webroot/uploads, so new folders get group client12

3/ in src/Controller/StudiesController.php
$randFile = bin2hex(random_bytes(12));
$Folder = new Folder(WWW_ROOT . 'uploads' . DS .  $randFile , true, 0755);

### What happened
folder was created as expected, but ownership has changed to www-data:client12 instead of web34:client12. 
---
root@k1:/var/www/clients/client12/web34/web/webroot/uploads# ll
total 12
drwxrwsr-x 3 web34    client12 4096 Mar 21 15:07 ./
drwxrwxr-x 7 web34    client12 4096 Mar 21 14:16 ../
drwxr-sr-x 3 www-data client12 4096 Mar 21 14:15 7b64a5036955e6790ee86212/

### What you expected to happen
$Folder = new Folder(WWW_ROOT . 'uploads' . DS .  $randFile , true, 0755);
will create folder and keep ownership of apache / domain:

root@k1:/var/www/clients/client12/web34/web/webroot/uploads# ll
total 12
drwxrwsr-x 3 web34    client12 4096 Mar 21 15:07 ./
drwxrwxr-x 7 web34    client12 4096 Mar 21 14:16 ../
drwxr-sr-x 3 web34    client12 4096 Mar 21 14:15 7b64a5036955e6790ee86212/

mp155

**Comment by karmicdice** [comment]
Cannot replicate. This isn't Cake issue.

Head over to https://discourse.cakephp.org/ for further discussion.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
