### ISSUE TITLE
Events using more "generic" conventions

### ISSUE THREAD

**Issue by FinlayDaG33k** [cakephp/cakephp#13062]
Hii there,

I'm currently trying to make an event in CakePHP to inform all registered users on my website when a new post has been made.   
However, while doing so, I noticed that events don't really follow the general CakePHP conventions like Controllers, Forms, and Components.  
Eg. `BlogController` would be placed in `src/Controller/BlogController.php` with the class `BlogController`.  
Events seem to not follow a convention like this (atleast, not that I can make up out of the documentation).  
I think it'd be nice to see a convention that would make it easier to make events.  
Eg. `NewPostEvent` would be placed in `src/Event/NewPostEvent.php`.  

What do you guys think?

**Comment by markstory** [comment]
That sounds fine. We don't provide a folder for events as they are often not implemented by applications. Suggesting this directory could be part of the documentation though.

**Comment by FinlayDaG33k** [comment]
it'd also be nice if it could be defined something like this (though the `Event` library might be replaced with `EventListener` or something):
```php
namespace App\Event;

using Cake\Event\Event;

class NewPostEvent extends Event {
  public function registerEvents() {
    return [
      'Blog.Post.new' => 'informUsers'
    ]
  }

  private function informUsers (
    // Do magic
  }
}
```

I know it already *sortoff* works like this, but it would look cleaner as now it's more or less structured like (for example) a controller or component.

**Comment by josegonzalez** [comment]
You should already be able to do that:

```
<?php
namespace App\EventListener;

use Cake\Event\EventListenerInterface;

class PostEventListener extends EventListenerInterface
{
  public function implementedEvents()
  {
      return [
        'Blog.Post.new' => 'informUsers'
      ];
  }

  public function informUsers
  (
    // Do magic
  }
}
```

I used this pattern in my CakeAdvent 2016 example app - [example here](https://github.com/josegonzalez/cakeadvent-2016/blob/master/src/Listener/PostsListener.php), though I extend Crud's BaseListener.

Where you place Event and EventListener classes is up to you.

**Comment by FinlayDaG33k** [comment]
I'll have a look at it, it looks promising :)

**Comment by markstory** [comment]
@FinlayDaG33k This sounds like another thing that could exist as an update to the documentation. I'm not sure we need to make any code changes to CakePHP or the application skeleton to enable these conventions.

**Comment by FinlayDaG33k** [comment]
well, tbf, I think it'd be nice to have all the listeners for an app/plugin in the same directory like we have for controllers, tables, entities etc. etc. and pretty much enforce them to be there.  
Makes it easier for people to find registered events instead of allowing them to be all over the place.

**Comment by josegonzalez** [comment]
@FinlayDaG33k I sometimes have shared listeners in `src/EventListener`, and sometimes place them in `src/Model/EventListener`, depending on how scoped they are. Its also possible to build an app 
_without_ events at all - I do this frequently for things that don't use the Crud plugin - and I believe that is how many people write apps (we don't have metrics on this of course).

There are a large number of folders we _could_ add to the base app skeleton but choose not to, and instead rely on documentation examples to show people where they should be placed.

@markstory maybe if we have a bake task for Events and EventListeners, that would be enough from a code perspective?

**Comment by markstory** [comment]
> maybe if we have a bake task for Events and EventListeners, that would be enough from a code perspective?

We could add more bake commands. I personally don't have the time to do the work, but if @FinlayDaG33k wants to take it on I can help guide them on where to start.

**Comment by karmicdice** [comment]
I am not sure if we need rfc on this... but, adding events will change the entire structure.
@josegonzalez I fail to see how behaviors are different from events (from the example point of view above). From the suggestion pov, It will become more like Event-Observer model.
@FinlayDaG33k I remember using RoR with [EventMachine](https://github.com/eventmachine/eventmachine). Maybe create a plugin to accomplish this?

**Comment by FinlayDaG33k** [comment]
> There are a large number of folders we could add to the base app skeleton but choose not to, and instead rely on documentation examples to show people where they should be placed.

They don't have to be part of the base skeleton app to be honest but a fixed location and naming convention (like `NewPostListener` or `NewPostEvent`) stated in the documentation would be desirable, as well as possible enforcing this location and naming.  
Possibly we could have a folder `EventListener` in the `src` folder and have subdirectories (eg. `src/EventListener/Controller`) to scope them, though this might get too complex too quickly.
Again, it's mostly about having a place where we can expect things to be.
If we, for example, want to modify a controller, we know to find it in `src/Controller/MyController.php`.
I've had a few occasions already with events where I thought to find them in the `BlogController`, but some chickennugget put it in the `UsersController` (for whatever reason).  
Of course, I just walked to him and explained it to him but having a convention for this (and enforcing it) would save a lot of these scenarios.

>We could add more bake commands. I personally don't have the time to do the work, but if FinlayDaG33k wants to take it on I can help guide them on where to start.

While I'd love to work on it, due to my own work, I don't personally have time for this either :\
