### ISSUE TITLE
RFC: Plugin/App path methods need adjusting

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13067]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
With the change from 2.x to 3.x and plugins not required to be loaded anymore due to direct autoload-inclusion, we have an issue with Plugin::path() and App::path() to work in those cases.

Loading a plugin is usually only required for certain types of classes contained.
So often you dont "load" it explicitly.

My concrete issue:
The IdeHelper is supposed to run on both loaded and not loaded plugins.
But with the not loaded ones this does not work.

### What happened
```
bin/cake annotations all -p Markup
```
Exception: Plugin not found even though it is there.

It required `Plugin::load('Markup');` in bootstrap or the Application version of it.
Even though none of the classes require this as they are already in the autoload map.

### What you expected to happen
To still be able to use those methods and find the right paths.

So, are we able to provide a way in core to support those methods above also for those use cases?
My current "workaround" is custom wrappers ( https://github.com/dereuromark/cakephp-ide-helper/compare/plugin-path ), but I am not sure this is a good idea, especially since those methods are internal/deprecated and won't work beyond 3.x.

**Comment by markstory** [comment]
We could try to 'autoload' plugins if they have not already been explicitly loaded.

**Comment by dereuromark** [comment]
Yeah this is basically the current workaround: https://github.com/dereuromark/cakephp-ide-helper/compare/plugin-path#diff-fec1982b7a04c04113b90e7913c6f84fR24

**Comment by dereuromark** [comment]
Until we "fix" this in core I released https://github.com/dereuromark/cakephp-ide-helper/releases/tag/0.13.9 with shimming in place.

**Comment by ADmad** [comment]
Everything installed plugin in listed in `vendor/cakephp-plugins.php` generated by the plugin installer. So that could be leveraged if a plugin isn't explicitly loaded and added to plugin collection.
