### ISSUE TITLE
App\View\AppView could not be converted to string

### ISSUE THREAD

**Issue by AshLeece** [cakephp/cakephp#13073]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: Debian GNU/Linux 9.8 (stretch), Apache 2.4.25-3+deb9u6, 10.1.37-MariaDB, PHP 7.0.33-0+deb9u3

### What you did
Please understand I am somewhat new to CakePHP and hopefully this isn't something stupid I've missed.

Currently we have been asked to migrate from 3.0.5 to 3.7.5, everything for us appears to be working except for one issue we have been unable to iron out. It does not appear to be affecting any functionality of our site but we'd rather fix it than hide it.

There is a similar issue #11276 but I could not seem to resolve it.

### What happened
After upgrading the following warning appears:

`Warning (4096): Object of class App\View\AppView could not be converted to string [APP/Template/Mailmerge/process_premerged.ctp, line 129]`

`- APP/Template/Mailmerge/process_premerged.ctp, line 129`
`Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1413`
`Cake\View\View::_render() - CORE/src/View/View.php, line 1374`
`Cake\View\View::render() - CORE/src/View/View.php, line 880`
`Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 791`
`Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 126`
`Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 94`
`Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 67`
`[main] - ROOT/webroot/index.php, line 36`

process_premerged.ctp:

`126 <?= $this->start('mergeFlash') ?>`
`127     <div id="Flash-Success" class="message success"></div>`
`128     <div id="Flash-Fail" class="message error"></div>`
`129 <?= $this->end(); ?>`
`130 <?= $this->start('sidebar'); ?>`
`131     <h3><?= __('Actions') ?></h3>`
`132     <ul class="side-nav">`

The warnings occur multiple times, all referencing the "Object of class App\View\AppView could not be converted to string" just referencing different lines of the same template.

If you need any more detail please ask.

Thanks in advance! :)

**Comment by saeideng** [comment]
test this
```php
<?php $this->start('mergeFlash') ?>
<div id="Flash-Success" class="message success"></div>
<div id="Flash-Fail" class="message error"></div>
<?php $this->end(); ?>
<?php $this->start('sidebar'); ?>
<h3><?= __('Actions') ?></h3>
<ul class="side-nav">
```
