### ISSUE TITLE
Mime Type validation fails for capitalized mimetypes

### ISSUE THREAD

**Issue by wschwarte** [cakephp/cakephp#13075]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5

### What you did
I uploaded a text file and used the `Validation::uploadedFile` method to check mime types.
using ['text/plain', 'text/csv', 'text/x-Algol68']

### What happened
Validation failed.

This code lowers the casing for the $val in my array. But, the mime type itself is using a capital 'A'.

```
        foreach ($mimeTypes as $key => $val) {
            $mimeTypes[$key] = strtolower($val);
        }
```

so this code:

`return in_array($mime, $mimeTypes);`

returns false. Because 'x-Algol68' is not in the array (x-algol68 is). 

### What you expected to happen
I expected a true result.

Should the $mime value also be lowercased to prevent this?

**Comment by markstory** [comment]
Should mime-types be case-insensitive?

**Comment by garas** [comment]
https://tools.ietf.org/html/rfc6838#section-4.2:
Both top-level type and subtype names are case-insensitive.

**Comment by markstory** [comment]
Then changing the validations sounds ok to me, just needs some doing :smile:
