### ISSUE TITLE
Testing a controller action that use the SecurityComponent with unlockedFields fails

### ISSUE THREAD

**Issue by alaxos** [cakephp/cakephp#13071]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: Linux, PHP 7.0

### What you did
I'm trying to test a controller action that is used to add a new organization. The view contains two input fields (`field1` and `field2`) that are added to the form by using Javascript. There is a validation rule that makes at least one value required for these two fields.

In order to make the posted data pass the SecurityComponent check, I added these two fields into the `unlockedFields`:

_OrganizationsController:_
```
$this->Security->setConfig('unlockedFields', ['field1', field2']);
```

In order to test the `add` action I put some values for `field1` and `field2` as they are required to pass validation.

_OrganizationsControllerTest:_
```
$this->enableCsrfToken();
$this->enableSecurityToken();
$data = [
	'name'   => 'Test organisation',
	'field1' => ['value1'],
	'field2' => ['value2']
];
$this->post('/organizations/add', $data);
```
### What happened
The test gives the following error:
```
Possibly related to Cake\Controller\Exception\AuthSecurityException: "Invalid security debug token." 
Cake\Controller\Component\SecurityComponent->_validatePost
```
### What you expected to happen
The expected result would be a successful test instead of this error.

Please not that if I don't set values for `field1` and `field2`, the Security exception is not raised. But my validation rules make the test fail as the new organization is not created.

**Comment by markstory** [comment]
Unlocked field information is normally part of the submitted form data. Right now the `enableSecurityToken()` helper doesn't have arguments to add unlocked fields though.

**Comment by dereuromark** [comment]
@alaxos You want to make a PR for 3.8 to include this addition for fields?

**Comment by dereuromark** [comment]
PR open.
