### ISSUE TITLE
2.x CakeEvent class not found via CakeEventManager::dispatch

### ISSUE THREAD

**Issue by bryonbean** [cakephp/cakephp#13083]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 461c5dc9fac291ee17e17d1a71db426654893aca.
* Platform and Target: All.

### What you did
One of our tests requires us to use the `CakeEventManager` to dispatch an event (as a string), e.g.:
```php
CakeEventManager::instance()->dispatch('Cache.clearAll')
```

### What happened
https://github.com/cakephp/cakephp/blob/3d216935c9f7d65af7d7f7a0c93a1ac445509ef2/lib/Cake/Event/CakeEventManager.php#L228

### What you expected to happen
Given that `CakeEventManager` is creating the `CakeEvent` I would expect `CakeEventManager` file to have the statement  `App::uses('CakeEvent', 'Event');`

**Comment by dereuromark** [comment]
You can make a PR here to fix this.

**Comment by markstory** [comment]
Fixed in 85eb25e8b5bb6eb1a2f9208c218f80de0637d372
