### ISSUE TITLE
Saving Additional Data to the Join Table

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13082]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: LAMP

### What you did
```
$student = $this->Students->newEntity($this->request->getData(), [
    'associated' => ['Courses._joinData']
]);
```

### What happened
It changes not only join table data, but also allow to change Course data, that is unexpected and insecure.
Its possible to wrap in following way, but its unclear from documentation:
```
$student = $this->Students->newEntity($this->request->getData(), [
    'associated' => ['Courses'=>['fields'=>['_joinData']], 'Courses._joinData']
]);
```

### What you expected to happen
Only join data is changed

Generally, shouldn't we remove following code from newEntity/patchEntity in 4.0?:
```
if (!isset($options['associated'])) {
        $options['associated'] = $this->_associations->keys();
}
```
So developers have to specify what exactly they want to change, because editing all is good for app skeleton fast build, but it in real world application it becomes security hole.

**Comment by markstory** [comment]
> Generally, shouldn't we remove following code from newEntity/patchEntity in 4.0?:

I'm not sure I agree with this change. It complicates everyday usage of the ORM, and for folks who need to restrict operations down to the field level they can use the `fields` option, or change which fields are accessible on their entities.

In your situation if you had a formal association between Students and Courses you could use that association name to prevent updates to Courses.

**Comment by ADmad** [comment]
Closing as per above comment.
