### ISSUE TITLE
Use DateTimeInterface for withModified transformation in Response

### ISSUE THREAD

**Issue by dorxy** [cakephp/cakephp#13087]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
I return a response `$response->withModified($myEntity->modified)`.
My locale was set to `de_DE`, and the modified property is a FrozenTime object. 

### What happened
The `_getUTCDate` function in Response.php will check if the object given is an instance of DateTime, which FrozenTime is not. It will fallback to creating a new DateTime object, using toString of the original FrozenTimeobject, and it tries to resolve 'dd.mm.yy, HH:ii' (the default german format) which fails.

### What you expected to happen
I expect `_getUTCDate` to handle DateTimeInterface instead of DateTime, allowing for support of FrozenTime and other objects which to not extend DateTime but do implement the interface which should be sufficient for conversion to the UTC timezone.

**Comment by ADmad** [comment]
Sounds reasonable, would like to submit a fix for this?

**Comment by dorxy** [comment]
I currently do not have the time, but when I do and nobody else has done anything with this issue I'll be glad to ;)
