### ISSUE TITLE
Saving an entity with unspecified foreign key of type String (3.7.1)

### ISSUE THREAD

**Issue by mathieugrimault** [cakephp/cakephp#13084]
This is a : bug

* CakePHP Version: 3.7.1
* Platform and Target: Apache2 / Debian Stretch / Mysql 5.5.62-0+deb8u1

### What you did
Try to save an entity with a unspecified foreign key. The foreign key is a string ! 
All code is done with bake.

```sql
DROP TABLE IF EXISTS `sections`;
CREATE TABLE `sections` (
  `id` varchar(5) NOT NULL,
  `name` varchar(64),
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `demandes`;
CREATE TABLE `demandes` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `section_id` varchar(5),
  `name` varchar(64),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `demandes`
ADD CONSTRAINT `sectionservices_ibfk_1`
FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`);

INSERT INTO `sections` VALUES 
('AAA','A A A'),
('BBB','B B B');
```

### What happened
Submitting the form send an empty value '' for the foreign key. 
Validation fail to validate the foreign key because '' doesn't exist in the foreign table.
Cake is returning the user to the form with an error attached to the input "This value does not exist". 

### What you expected to happen
A correct save was expected. No workarround should be necessay in my opinion. 
The validation process is inconsistent, the same case with a foreign key of type INT is behaving correctly and don't need a workarround.

The workarround, add some code to the entity :

```php
...
protected function _setSectionId($value)
    {
		if (is_string($value) && empty($value))
		{
			$value = null;
		}
		return $value;
	}
...
```

**Comment by ADmad** [comment]
> The validation process is inconsistent, the same case with a foreign key of type INT is behaving correctly and don't need a workarround

The difference is empty string is not a valid value for integer field while empty string is.

Also empty string can be used as a valid foreign key.

**Comment by markstory** [comment]
Is `demandes.section_id` nullable? It looks like it is nullable from the schema you've included which means bake would not have generated a notBlank validation rule which should help prevent this case.

I agree with @ADmad. `''` is a valid value for string columns and if it is invalid for your application's use case you need to use validation rules to prevent that state from being accepted.
