### ISSUE TITLE
2.x file cache errors on PHP 7.2 when running a single database test by itself

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#13085]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.15
* Platform and Target: Windows 10, PHP 7.2.16 (but bug present from PHP 7.2.0 onwards)

When I run a single test which hits the database, I get the following errors in my console. These are spawned by the `Mysql::__destruct()` method, which tries to update `method_cache` cache. The actual test passes and I get the PhpUnit green output in the console followed by the errors.

If I run a single test which doesn't hit the database, I do not get the error ouput. If I run the entire test suite, I do not get the error ouput.

I have tested this on PHP 7.1.latest and the error does not occur. It occurs from PHP 7.2.0. 

I am using PHPUnit 5.7.27, in case that is relevant.

Therefore I assume it is a PHP bug. However I am having real difficulty reproducing it with a plain PHP script so I'm not at the stage where I can submit a PHP bug report. If anyone else is able to reproduce this error, please do let me know!

```
» app/Console/cake test app Jobs/Queue/Database --configuration=phpunit.xml

CakePHP Test Shell
---------------------------------------------------------------
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.16
Configuration: C:\inetpub\my_project\phpunit.xml

.....                                                               5 / 5 (100%)

Time: 2.63 seconds, Memory: 24.00MB

OK (5 tests, 8 assertions)

Warning: flock(): supplied resource is not a valid stream resource in C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Engine\FileEngine.php on line 138

Warning: SplFileObject::rewind(): stream does not support seeking in C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Engine\FileEngine.php on line 141

Fatal error: Uncaught RuntimeException: Cannot rewind file c:\inetpub\my_project\app\tmp\cache\persistent\my_project_dev_cake_core_method_cache in C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Engine\FileEngine.php:141
Stack trace:
#0 C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Engine\FileEngine.php(141): SplFileObject->rewind()
#1 C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Cache.php(317): FileEngine->write('my_project_dev_cake...', 'a:3:{i:0;b:0;s:...', 10)
#2 C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(3748): Cache::write('method_cache', Array, '_cake_core_')
#3 [internal function]: DboSource->__destruct()
#4 {main}
  thrown in C:\inetpub\my_project\app\Vendor\cakephp\cakephp\lib\Cake\Cache\Engine\FileEngine.php on line 141
```

I have spent a lot of time debugging this without any joy so far. I have established that when running a single test, `FileEngine::_setKey()` does not enter the if block (line 356) when doing the write call, because the previous cache operation was the read for the same key. Whereas, when running all tests, another cache operation has happened somewhere, so it has to enter the if block and re-establish the `SplFileObject` instance.

**Comment by markstory** [comment]
How can someone reproduce this problem? The tests we have for 2.x don't have this issue and I personally don't have any 2.x apps that have had this problem either.

**Comment by garethellis36** [comment]
I'm trying to create a test project to reproduce the problem. Not having any luck so far!

**Comment by garethellis36** [comment]
I was able to reproduce this in a test project:
https://github.com/garethellis36/cakephp-file-cache-errors-php7.2

**Comment by garethellis36** [comment]
Hi @markstory were you able to reproduce this issue?

**Comment by markstory** [comment]
@garethellis36 I've not gotten around to this issue. I'm hoping to get to it this week.

**Comment by markstory** [comment]
@garethellis36 Thanks for providing the repository to reproduce this, I've got the error showing locally now :+1:

**Comment by garethellis36** [comment]
Great, is that on Windows too?

**Comment by markstory** [comment]
No I was on macOS. The root of the problem is that during the process shutdown `FileCacheEngine`'s internal File pointer is destroyed before the method cache is persisted. Because the key is the 'same' as last used cache key we don't rebuild the `_File` property. My hunch right now is that `FileEngine::_setKey()` needs some additional checks to ensure the current stream is still open.

**Comment by garethellis36** [comment]
It is interesting that it only happens on 7.2 though, I wonder if they changed something about the shutdown processes. I can't come up with a generic enough reproduction to be able to submit a PHP bug report unfortunately.

**Comment by markstory** [comment]
PHP's Shutdown order isn't guaranteed, so I don't think they would accept a bug report anyways :)

**Comment by markstory** [comment]
Pull request open.

**Comment by garethellis36** [comment]
Thank you!

**Comment by johannesnagl** [comment]
Really great! We also had exactly the same problem after upgrading to 7.2 and our "solution" (aka: workaround) was to simply disable the methodCache!

**Comment by it9gamelog** [comment]
The problem is that the DataSource and the Cache FileEngine could be destructed in random order since they are referenced by static variables. PHP does not guarantee any order by calling destructor during shutdown.

The commit simply avoid the error, yet when the FileEngine is destructed first, there will be no cache writing. Since this bug only happens randomly and after all it's just a cache, nothing would really blow up.

I am using something like this to remove the DataSourceObject reference during shutdown, such that DataSourceObject would be destructed while the FileEngine is still valid to use.

```
register_shutdown_function("CleanupConnectionManagerSource");
function CleanupConnectionManagerSource() {
    foreach (ConnectionManager::sourceList() as $name) {
        ConnectionManager::drop($name);
    }
}
```
