### ISSUE TITLE
Command doesnt autoload own model

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13099]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x latest

### What you did
```php
class MyCommand extends Command
{
    public $modelClass = 'Tools.Emails';

    public function execute(Arguments $args, ConsoleIo $io)
    {
        $this->Emails->doSth();
    }
}
```
### What happened

Notice: Notice (8): Undefined property

+ Exception of method not found on null.

### What you expected to happen
Like with controllers and shells before, the defined primary model should be available without having to first call
```
$this->loadModel();
```

**Comment by ADmad** [comment]
I actually prefer command not having this auto-magic.

**Comment by dereuromark** [comment]
why that? we should lazyload it, but otherwise the whole property would be without purpose.

**Comment by markstory** [comment]
I am not sure this is a bug as I don't remember this ever being something we discussed implementing for commands.

I am not opposed to adding this behavior as it adds consistency with controllers.

**Comment by saeideng** [comment]
>I actually prefer commands not having this auto-magic.

:+1:  even in controllers in future (4.x or 5.x)

**Comment by dereuromark** [comment]
PR open for 3.next.
