### ISSUE TITLE
Behaviors for model less Form classes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13094]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

### What you did
I have a contact form as ContactForm class (model less) and want to attach the existing Captcha behavior (as plugin solution) to validate based on captcha input.

### What happened
Form classes have always been some kind of 2nd class citizen with the move to 3.x.
It still feels kind of wrong to have such isolated classes, that cannot be extended as easily as models. In some of these cases it would be better/cleaner to just use a fake model (with no table) to be able to attach existing behaviors and functionality.

### What you expected to happen
I would expect us to have behavior support or sth similar for Form classes as well.

    $form->load('FooBar')

That would then leverage the same validator callbacks to auto-add their validation rules for example.
Is that something other people also feel like a crucially missing piece for Form classes?
Or how does one use generic (existing) plugin functionality in a DRY way with the current implementation?

If we dont want to confuse them with the more complicated `Behaviors`, we could come up with a different name, e.g. `Enhancers`, `Attachments`, `FormBehaviors` or `ValidationBehaviors` for forms.

They dont need all the model overhead, no custom finders, no custom methods, I guess hooking into the existing buildValidator callback could suffice, maybe we also want to check if a beforeExecute etc could make sense.

**Comment by dereuromark** [comment]
Right now I am hacking it a bit using a trait to replicate the behavior load methods and using this in the controller:

    $contact->addBehavior('Captcha.PassiveCaptcha');
    $contact->behaviors()->PassiveCaptcha->addValidation($contact->getValidator());

That works for now. But requires a dummy Table class to be used for the event system (as it is typehinted to this). Also, of course, some of the events would fail - I am only using the buildValidator one here in my case.

**Comment by markstory** [comment]
Are you hoping to re-use ORM behaviors entirely? Or have a concept like behaviors for Form classes? Using behaviors as they stand isn't a great fit as behaviors have a ton of hook methods that don't work for forms.

If you're looking to have something that gives the ability to compose Form classes from 'behaviors' defined in plugins I think that is something we should explore, as we have similar features for almost every other subsystem in the framework.

**Comment by dereuromark** [comment]
As oultined above: To have a new concept, similar to it, just with either the same or close naming.
I am just reusing the existing as hack until then as this gets the job done.

Yeah, Forms are lacking this reusable components part as attachable elements completely.

**Comment by robertpustulka** [comment]
Can't you use some old-fashioned dependency injection?

```php
$validator = new CaptchaValidator();
$form = new ContactForm($validator);
```

Placing captcha validation in a behavior seems odd to me. If you want to perform just validation why mixing it with model stuff?

**Comment by dereuromark** [comment]
This is only one example of many - where things are done in a cakephp behavior driven way.
validation is the same, if done on model persistence level or form execution one. Even has the same event name :) If you look again closely.

**Comment by ADmad** [comment]
> They dont need all the model overhead, no custom finders, no custom methods

So they would be just generic event listeners listening to a bunch of events? That's possible to achieve even now.

**Comment by dereuromark** [comment]
The ones outlined in its body: 
https://github.com/cakephp/cakephp/blob/master/src/Form/Form.php#L127-L129

Guys, please :) Think about the Cake way, how other parts of the systems work. Then you will understand why and how this is important to fix up.

**Comment by ADmad** [comment]
> Think about the Cake way,

That's the thing, I am conflicted whether we should be adding another CakePHP specific way to do something which can be achieved in a generic way.

**Comment by robertpustulka** [comment]
> Think about the Cake way, how other parts of the system work, especially in terms of attaching reusable parts with no DI system in place.

The Cake way used to be making things more complex than should be. If you want simple DI you don't need a DI system or any other "mixin" layer of complexity.

If you want to listen on an event just attach a listener. Seems simple or I'm not seeing the full picture.

**Comment by dereuromark** [comment]
The merging is what you are missing.
I want to add more rules via event system, not creating my own all the time to manually DI here.

This is how things work with behaviors and this is how one would expect Forms (as modelless pendant to it) to work :)

**Comment by robertpustulka** [comment]
> I want to add more rules via event system

What's stopping you right now? Form is Validation and Event aware. Attach a listener and it's done.

**Comment by dereuromark** [comment]
Tell me how that would work with a single line of app code :)
The plugin should keep all the main logic, of adding stuff, and all I do from app is to attach this class to the form.
I am curious how you would want to solve this with your idea. Can you maybe elaborate on this? I might just get the full picture.

**Comment by robertpustulka** [comment]
This is my idea of solving this. I agree that more event hooks for form lifecycle could help with more complex cases.

```php
class CaptchaValidator
{
    public function attachRules(Validator $validator)
    {
        //add rules
    }
}

class CaptchaListener implements EventListenerInterface
{
    public function __construct()
    {
        $this->validator = new CaptchaValidator();
    }

    public function buildValidator(Event $event, Validator $validator)
    {
        $this->validator->attachRules($validator);
    }

    public function implementedEvents()
    {
        return [
            'Form.buildValidator' => 'buildValidator',
        ];
    }
}

class ContactForm extends Form
{
    public function __construct(EventManager $eventManager = null)
    {
        parent::__construct($eventManager);
        
        $eventManager->on(new CaptchaListener);
    }
}

**Comment by dereuromark** [comment]
OK, i see that this could be doable in this case.

But if we also want to add beforeExecute and afterExecute (similar to beforeSave and afterSave) events, we should really think about my idea of making this a bit closer to what people expect coming from Table classes and behaviors and their hook in points.

**Comment by dereuromark** [comment]
I would still like to see this happening, to have common shared behaviors that can apply to multiple form classes in terms of adding validation or data transformation.

**Comment by dereuromark** [comment]
Do we have an agreement on this now for what kind of hooks/events to use/add for model less forms to be closer to how behaviors work?
If they cannot fully be reused for this, that's fine.
But we should be able to hook in a "behavior" of some sorts that adds itself and its validation without having to extend and modify a plugin-based Form for example. One could always extend on project level, sure. But would be nice if those work out of the box together.

Right now this seems to work for me, so I am also fine with closing then:
```php
   $contactForm = new ContactForm();

    if ($this->Common->isPosted()) {
        $this->Captcha->addValidation($contactForm->getValidator());

        if ($contactForm->execute($this->request->getData())) {
            // success flash and redirect back
        }

        $this->Flash->error(__('The form contains errors. Please fix those and try again.'));
    }
```

**Comment by markstory** [comment]
There's currently only the one event in Forms. I don't think using Behaviors is ideal because they won't interact well with all of the non-validation aspects that Behaviors have. We could add a new behavior like object though for use in Forms.
