### ISSUE TITLE
Model introspection / validation

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13096]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.3

For the purpose of handling and validation of Model in ORM there are now several features that are available.
Namely Validator throug `validationDefault` (and ofc non-default validators), integrity Checker through `buildRules`, model Behaviors (for Timestamp, Tree, etc.), and of course relations (hasMany, hasOne, belongsTo, BTM, ...)

When developing some non-trivial application, one is constantly modifying underlying DB as well as the application implementation, and not always there are integration tests done.

There is some space, in terms of, what could ORM Table/Entity provide, to allow introspection validation, that the underlying model matches the implemented handling/validation.

Specifically methods to:

  - check that all db-table columns are matched with Validator or Checker
  - check that db-table column type matches the Validator rules
  - check that db-table constraints are handled by Checker rules
  - check that db-table UNIQUE/FULLTEXT index is matched by Checker
  - check that there are no invalid relations defined in implementation (such as hasMany joinType=INNER where business model does not require presence of the related model entries)
   - etc..

Not all of them are feasible to be checked or possible to validate, however developer could use the introspection ability (either core or plugin provided) to check that implementation matches the business design/purpose.

So the proposal to enhancement/rfc is to add introspection methods to ORM in core framework, to allow such validation in better way, than ie. comparing `Model->getSchema()->columns` with `Model->getValidator()->_fields`

**Comment by dereuromark** [comment]
For me this is clearly plugin specifics, already done quite extensibly in e.g. [Setup](https://github.com/dereuromark/cakephp-setup) or alike as shells.
Most of them cannot be run in sync with the execution code of validating, and as such have to be a completely isolated verification/checking tooling anyway.

**Comment by smarek** [comment]
@dereuromark i'm sorry, but i'm not talking about introspection of Plugin models, could you please explain your comment more?
This is not, in my opinion, specific to any particular framework component.

Also if you could point out, where in referenced Setup plugin, you do model validation (ie. checking one of the mentioned methods in my initial post), i'd be grateful.

**Comment by ADmad** [comment]
@smarek He's not talking about plugin models. He means the feature the you want should be implemented in a plugin and doesn't need to be in core. I concur with him.

**Comment by smarek** [comment]
@ADmad thank you, that is clear statement to me.

**Comment by inoas** [comment]
> There is some space, in terms of, what could ORM Table/Entity provide, to allow introspection validation, that the underlying model matches the implemented handling/validation.

There are constraints a database cannot catch well (unless you add tons of stored procedures)
Ecto (of Elixir Phoenix) which is very close to SQL, too much like Rail's AREL, respects the contraint errors from the database and just shows those to the user UNLESS you catch them and it provides some defaults for catching foreign key and unique constraints.

What's the benefits?

- You do not need to duplicate unique and foreign key constraint checks in the application. That means you do not need to run (transactioned) queries while writing new data which check for unique and foreign key constraints.
- For many of the simple foreign key and unique constraints your application will automatically update with the database schema constraint changes.

That's quite difference in approach to how 3.x (and 4.x I suppose) handle this.
