### ISSUE TITLE
Cookies with array values are not decoded back from json

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#13092]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5

### What you did
```PHP
use Cake\Http\Cookie\Cookie;

$cookieData = [
	'a' => 1,
	'b' => 2
];
$cookie = new Cookie('test', $cookieData);
$this->setResponse(
	$this->getResponse()->withCookie($cookie)
);
debug($this->getRequest()->getCookie('test.a'));
debug($this->getRequest()->getCookie('test.b'));
debug($this->getRequest()->getCookie('test'));
```

### What happened
```
null
null
'{"a":1,"b":2}'
```
### What you expected to happen
```
(int) 1
(int) 2
[
	'a' => (int) 1,
	'b' => (int) 2
]
```

**Comment by asgraf** [comment]
After additional tests i had found out that this this issue seems to affect only cookies that are not encrypted.
Cookies encrypted via EncryptedCookieMiddleware are properly json decoded and this issue does not affect them.

**Comment by markstory** [comment]
The encrypted cookie middleware is the the piece decoding cookies from JSON. We don't support decoding arbitrary cookie values as the framework doesn't know the encoding of application cookies and it is not efficient to attempt to decode every cookie as JSON when most of the time it will fail.

If you need specific cookies to be JSON encoded, you can add middleware to decode the required cookies and validate the data as required.

**Comment by asgraf** [comment]
Im aware that i can make some custom middleware to do the trick or i can just do something like this to get equivalent effect:
```PHP
debug($this->getRequest()->getCookieCollection()->get('test') ? $this->getRequest()->getCookieCollection()->get('test')->read('a') : null);
debug($this->getRequest()->getCookieCollection()->get('test') ? $this->getRequest()->getCookieCollection()->get('test')->read('b') : null);
debug($this->getRequest()->getCookieCollection()->get('test') ? $this->getRequest()->getCookieCollection()->get('test')->read() : null);
```
My point is that currently `Cake\Http\Cookie\Cookie` class already auto-magically translate array values into JSON strings. So it is logical to expect that cakephp should offer equivalent auto-magical way to translate them back to arrays even when they are not encrypted.


So i'm proposing new shorthand method `$this->getRequest()->readCookie('test.x.y.z')` that would internally just call `$this->getRequest()->getCookieCollection()->get('test')->read('x.y.z')`

This way developer should not need to know (or care) of what specific encoding method Cookie class uses internally to encode arrays.

**Comment by markstory** [comment]
Ok. Adding a new method that provides easier access to cookie values is a good idea. The `readCookie()` method could work well. How would it interact with cookie names that contain a `.`?

**Comment by asgraf** [comment]
getCookie method already uses Hash::get internally so would expect same behavior from readCookie
readCookie('test.a') should work identically for unencrypted cookies like getCookie('test.a') does currently for encrypted ones.

**Comment by markstory** [comment]
Where do you see `getCookie()` using `Hash::get()` internally? CookieCollection::get() does a basic key lookup. The problem I see with the proposed interface is that `readCookie('test.a')` could resolve to a cookie named `test.a` or read the `a` property from cookie `test`. If the signature was `readCookie('test', 'a')` we could safely read from cookies with `.` in their names though.

**Comment by asgraf** [comment]
> Where do you see `getCookie()` using `Hash::get()` internally
https://github.com/cakephp/cakephp/blob/master/src/Http/ServerRequest.php#L1790

**Comment by markstory** [comment]
My mistake I had confused request and response, and was looking at the response class.

Thie getCookie() method operates on a basic array, and lacks the ability to read cookies with `.` in their names. I am not sure that us a limitation we should apply to new methods. Having two arguments would allow us to be clear on which cookie and which nested value was required.

**Comment by asgraf** [comment]
I don't see reason why anyone would ever want to have a dot in his cookie names but in order to support this special case there could be third optional argument like this:

```PHP
//readCookie($valuePath, $defaultValue = null, $cookieName = null)
$this->getRequest()->readCookie('test.x.y.z','default_value');//No cookieName argument, works like getCookie()
$this->getRequest()->readCookie('x.y.z','default_value','test');//With $cookieName argument works like @markstory suggested
```
