### ISSUE TITLE
Integration of dephpugger into Cakephp

### ISSUE THREAD

**Issue by liaogz82** [cakephp/cakephp#13091]
I would like to recommend integrating [dephpugger](https://github.com/tacnoman/dephpugger) into CakePHP. It works like RoR byebug and it helps developers to understand the workflow of their code.

What the developers need to do is to make cakephp able to work well with PHP web server and this will work.

I understand there will be arguments that we already have DebugKit and we do not need another debugging tool but both of these tools operates differently and having a variety of usable debugging tools will help developers

**Comment by markstory** [comment]
What kind of integration do you have in mind? From the dephpugger docs it looks like it needs a yaml file to run the server.

I think dephpugger solves different problems than DebugKit does and both can and should co-exist together :smile: They could either be separate plugins or dephpugger could be integrated with debugkit.

**Comment by liaogz82** [comment]
@markstory thanks for your support. It needs the framework to be able to run on php server instead of apache2. I wrote an [article](https://medium.com/@mosesliao/debug-drupal-using-dephpugger-a0839f878b56) on it before.

**Comment by markstory** [comment]
@liaogz82 CakePHP already works with the php server. The `bin/cake server` command is a small wrapper around the native PHP server.

**Comment by liaogz82** [comment]
Oh I did not know that! Great let me try this out!

**Comment by markstory** [comment]
DebugKit can have cli tools added into it as well.

**Comment by ADmad** [comment]
@markstory Looks like dephpugger is just CLI tool for debugging using Xdebug similar to the Xdebug debugging support we find in IDEs. It doesn't need to have anything to do with DebugKit.

@liaogz82 CakePHP app code can already be debugged with Xdebug using IDEs, same as any other PHP app. So I fail to see what specific support / integration you expect for using dephpugger.

**Comment by liaogz82** [comment]
@ADmad many of us don't use IDE tools, and xdebug helps for people like me who uses cmd more often

**Comment by ADmad** [comment]
@liaogz82 Sure, but you still fail to answer "what specific support / integration you expect for using dephpugger."?

**Comment by dereuromark** [comment]
Seems to be already possible then.
