### ISSUE TITLE
Missing alternative function for deprecated Response::send() 

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#13108]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.6
* Platform and Target: Apache/2.4.27, MySQL 5.6.37, PHP 7.1.8

### What you did
On my controller `beforeFilter` function I use the following code to make a redirect
```php
$this->redirect(['controller' => 'Install', 'action' => 'index'], 307)->send();
exit();
```
### What happened
I'm getting that warning `Response::send() will be removed in 4.0.0`

### What you expected to happen
When I navigate to `Response::send()` function, I expect to see the alternative function into the `@deprecated` warning message

**Comment by ADmad** [comment]
Just use `return $this->redirect ()`.

In general you should always return a response instance now. Never try to send response yourself or exit in controller.

**Comment by garas** [comment]
You should now `return $this->redirect(...);` without `send()` and `exit`.

Generally, with immutable response, you need to return or assign modified response to `$this->response`. There is no replacement function.

Response object should not send itself with `send()`, it is now sent by `ResponseEmitter` after middleware chain.

**Comment by markstory** [comment]
The deprecation message could recommend returning the response instead.

**Comment by BassemN** [comment]
@ADmad @garas @markstory I'm using `send()` and `exit()` because I'm doing this redirect from within the `beforeFilter` function not the controller action just to ensure the code execution is not continued.

**Comment by ADmad** [comment]
@BassemN Did you actually trying doing what I showed from `beforeFilter`?

**Comment by BassemN** [comment]
@ADmad I tried it again and I can't reproduce it on CakePHP 3.7 so maybe this issue was on earlier versions so I replaced my code with your solution. Now I think @markstory is right about recommending return the response instead.

**Comment by saeideng** [comment]
this should  work 
```php
  public function beforeFilter(\Cake\Event\Event $event) {
       parent::beforeFilter($event);
      $controller = $event->getSubject();
      //$event->stopPropagation();
      $url = ['controller'=>'..','action'=>'..'];
      return $controller->redirect($url);
  }
```

**Comment by BassemN** [comment]
@saeideng Thanks a lot
My question was that the `Response::send()` function is deprecated but the warning message doesn't provide the alternative function which it should be the response as per @markstory

**Comment by saeideng** [comment]
no alternative function , just `action` or `beforeFilter` should returns a response
