### ISSUE TITLE
Missing dependency to SimpleCache library

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13104]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: any.

### What you did
Tried to use Cache.

### What happened
Missing SimpleCache library.
`Psr\SimpleCache\CacheInterface` is used in [SimpleCacheEngine.php](https://github.com/cakephp/cakephp/blob/master/src/Cache/SimpleCacheEngine.php#L19).

### What you expected to happen
I would expect SimpleCache to be present in "require" section in [composer.json](https://github.com/cakephp/cakephp/blob/master/src/Cache/composer.json#L24).

**Comment by dereuromark** [comment]
You mean "require-dev" right? As this is one of many engines, and you are not forced to use SimpleCache :)

**Comment by dereuromark** [comment]
Ah, you mean the split repository. Yes, sounds like a good idea then.
Can you make a PR here with the suggested change?

**Comment by ADmad** [comment]
The main composer.json has `"psr/simple-cache": "^1.0.0"` so the composer.json of the standalone cache lib should have it too.
