### ISSUE TITLE
Rogue div tag get out putted on label => false 

### ISSUE THREAD

**Issue by KasunWijesekara** [cakephp/cakephp#13115]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.4
* Platform and Target: Apache, MySQL, PHP 5.6 

### What you did
I'm trying to disable the label from the Form Helper by using this method. 

`<?php echo $this->Form->control('name', array('class' => 'form-control' , 'label' => false)); ?>`

### What happened
And i keep getting this output. This wasn't happening to me on previous versions i think. I cannot really recall. I get an extra div outputted for some reason. 

`<div class="input text"><input type="text" name="name" class="form-control" maxlength="255" id="name" value="Users"></div>`

### What you expected to happen
I'm expecting just a plain input tag with a disabled label. That is all. 

`<input type="text" name="name" class="form-control" maxlength="255" id="name" value="Users">`

**Comment by ADmad** [comment]
`FormHelper::control()` is meant the generate the input, label, error message (if any) and a wrapping div. So if you disable the label you still get the rest.

If you want just the input tag use `FormHelper::text()`.

**Comment by saeideng** [comment]
you can customize the template

---------------------------------
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by saeideng** [comment]
also you can customize the template 
https://book.cakephp.org/3.0/en/views/helpers/form.html#customizing-the-templates-formhelper-uses
