### ISSUE TITLE
BasicWidget doesn't output `value` attribute correctly.

### ISSUE THREAD

**Issue by geoidesic** [cakephp/cakephp#13116]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.6
* Platform and Target: Apache, MySQL.

### What you did
I created a custom template for FormHelper input type text.

To elaborate. I have replaced the `input` template by adding the `/config/app_form.php` file as suggested by the docs here: https://book.cakephp.org/3.0/en/views/helpers/form.html#customizing-templates

Here's the original template: 
```
'templates' => [
    ...
    'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>',
    ...
]
```
I replaced it with this: 
```
'templates' => [
    'input' => '<my-input type="{{type}}" name="{{name}}" value="{{value}}" {{attrs}}></my-input>',
]
```

### What happened
The `value` attribute is incorrectly rendered for BasicWidget. The output gives two value keys, the first of which is empty: 
```
<my-input name="email" value="" required="required" maxlength="255" id="email" value="noel@arc2.co.uk" ></my-input>
```

### What you expected to happen
The `value` attribute should be added directly, rather than as part of the `attr` key to provide correct output. This is the expected output (notice the single `value` attribute:
```
<my-input name="email"  required="required" maxlength="255" id="email" value="noel@arc2.co.uk" ></my-input>
```

This can be achieved with the following code change:
```
public function render(array $data, ContextInterface $context)
    {
        $data += [
            'name' => '',
            'val' => null,
            'type' => 'text',
            'escape' => true,
            'templateVars' => []
        ];
        $data['value'] = $data['val'];
        unset($data['val']);

        return $this->_templates->format('input', [
            'name' => $data['name'],
            'type' => $data['type'],
            'value' => $data['value'],
            'templateVars' => $data['templateVars'],
            'attrs' => $this->_templates->formatAttributes(
                $data,
                ['name', 'type']
            ),
        ]);
    }
```

**Comment by geoidesic** [comment]
See https://github.com/cakephp/cakephp/compare/master...geoidesic:patch-2 for proposed patch.

**Comment by ADmad** [comment]
Why do you want `value` separately when using `'<my-input type="{{type}}" name="{{name}}"{{attrs}}></my-input>'` as your customized template would achieve the same result?

**Comment by geoidesic** [comment]
Great question. When I first tried that it didn't work... but that's because I had a typo in my closing tag. It does work as you suggest. So no need for this I guess.
