### ISSUE TITLE
Cakephp 4 composer update problem

### ISSUE THREAD

**Issue by vnt** [cakephp/cakephp#13114]
I tried to install Cakephp to version 4.
I followed these instructions for a clean installation
https://book.cakephp.org/4.0/en/installation.html

I get this errors.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cakephp/cakephp 4.0.* is satisfiable by cakephp/cakephp[4.0.0-alpha1] but these conflict with your requirements or minimum-stability.
  Problem 2
    - cakephp/bake 1.9.4 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.9.3 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.9.2 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.9.1 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.9.0 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.9.4 requires cakephp/cakephp ^3.7.0 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.8.0-beta1] but these conflict with your requirements or minimum-stability.
    - Installation request for cakephp/bake ^1.9.0 -> satisfiable by cakephp/bake[1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4].

* CakePHP Version: PHP 7.2.14 (cli)
* Platform and Target: MAMP (APACHE + MYSQL + PHP)

This is my composer.json
`{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "4.0.*",
        "cakephp/migrations": "^2.0.0",
        "cakephp/plugin-installer": "^1.0",
        "mobiledetect/mobiledetectlib": "2.*"
    },
    "require-dev": {
        "cakephp/bake": "^1.9.0",
        "cakephp/cakephp-codesniffer": "^3.0",
        "cakephp/debug_kit": "^3.17.0",
        "josegonzalez/dotenv": "3.*",
        "phpunit/phpunit": "^5|^6",
        "psy/psysh": "@stable"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan compatibility."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests/",
            "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    }
}
`

**Comment by saeideng** [comment]
you have to use `"cakephp/bake": "4.x-dev"
see https://github.com/cakephp/app/blob/4.0.0-alpha1/composer.json for more info
