### ISSUE TITLE
Using page() and limit() in specific order in Query, causes issues

### ISSUE THREAD

**Issue by eaxexe** [cakephp/cakephp#13124]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.10
* Platform and Target: Apache + MariaDB

### What you did
```
$ArticlesTable = TableRegistry::getTableLocator()->get('Articles');
$articles = $ArticlesTable
  ->find()
  ->page(2)
  ->limit(10);
```

### What happened
I gives me results 25 - 35.
This means that many entities won't be able to be found.

SQL generated for this:
```
SELECT `Articles`.`id` AS `Articles__id`,
       `Articles`.`name` AS `Articles__name`,
FROM `Articles` `Articles`
LIMIT 10
OFFSET 25
```

### What you expected to happen
I expected it to give me results 10 - 20.
In other words: I expected it to give me 10 results, offset by 10 (due to it being page 2).

I expected the following SQL:
```
SELECT `Articles`.`id` AS `Articles__id`,
       `Articles`.`name` AS `Articles__name`,
FROM `Articles` `Articles`
LIMIT 10
OFFSET 10
```

### Further info
If I switch limit() and page() like below, it works correctly.
```
$ArticlesTable = TableRegistry::getTableLocator()->get('Articles');
$articles = $ArticlesTable
  ->find()
  ->limit(10)
  ->page(2);
```

The issue seems to be in cakephp/cakephp/src/Database/Query.php, where the limit() method doesn't update the offset.

**Comment by ADmad** [comment]
Well `page()` is an abstraction to with sets `offset` and `limit` clauses. By calling `limit()` after `page()` you are resetting the limit and result you get is expected.

`page()` method has 2nd argument to set limit so for your use case do `page(2, 10)`.
