### ISSUE TITLE
4.0.0 - FormHelper required validation conflicts with Twitter Bootstrap

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13139]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2 & Bootstrap 4.3.1

### What you did
I created an add Question form
```php
echo $this->Form->create($question);
echo $this->Form->control('title');
echo $this->Form->control('question');
echo $this->Form->control('tags', ['type' => 'select', 'multiple' => true]);
echo $this->Form->submit('Save', ['class' => 'btn btn-primary']);
echo $this->Form->end();
```

Which outputs some required fields, as inputs with a property of `required="required"`

### What happened
When I try and submit the form an HTML5 validation bubble pops up telling me the field is required even though I have entered some content.

https://imgur.com/yGTfik8

### What you expected to happen
I figured that the FormHelper would be compatible with Twitter Bootstrap.

### RFC
Twiiter Bootstrap is a very popular front-end tool, there is even the `friendsofcake/bootstrap-ui` plugin, however it seems that the new FormHelper HTML conflicts somehow with their own validation.

Bootstrap seems to use the CSS pseudo classes, [as detailed in the documentation](https://getbootstrap.com/docs/4.3/components/forms/#how-it-works). Not including the Bootstrap JS file will stop this behaviour, but will also stop all the other JS Bootstrap features from working.

I've opened this as an RFC, as it's not strictly a bug, but I thought that an incompatibility like this out of the box would be something which is worth addressing in case other front-end tools like Zurb Foundation implement similar validation.

### Codebase
I am working on this in an example project, which you can find here. https://github.com/davidyell/Learning-CakePHP4
[It's worth noting that I've changed the FormHelper wrapping templates](https://github.com/davidyell/Learning-CakePHP4/blob/master/src/View/AppView.php#L39-L46).

**Comment by ADmad** [comment]
The boostrap doc page you linked shows when using bootstraps JS based validation you need to turn off the default browser based validation by using `novalidate` validate attribute in `form` tag. Have you done that?

**Comment by davidyell** [comment]
I bet I probably haven't!

Yes, I haven't done that. I will close this ticket now, as it's userland code and not related.
