### ISSUE TITLE
Separate dirty array|scalar returns

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13132]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x

### What you did
Inside controller actions patching
```php
$stateMachineProcess = $this->StateMachineProcesses
    ->patchEntity($stateMachineProcess, $this->request->getData());
```

### What happened
getData() returns too much, especially array|scalar which is somewhat a code smell here.

Phpstan with level 6+ in apps always fails for
```
Parameter #2 $data of method StateMachine\Model\Table\StateMachineProcessesTable::patchEntity() expects array, array|string|null given.
```

### What you expected to happen
To have separate methods here for all vs specific input, making the optional first argument invalid.
We could in a first step introduce the single version, and later then deprecate the god wrapper.

What about
- getDataArray() / getAllData()
- getData(string $key)

?

The current workaround is to add manual (array) casts everywhere.

And I am sure there are other methods that suffer the same issue here. This is only one of the examples I found in our API.

**Comment by markstory** [comment]
We could use `getParsedBody()` which is the PSR7 method to get all the request data. That would avoid needing to add another method.

**Comment by dereuromark** [comment]
I checked, that method is annotated as `null|array|object` which actually makes it worse IMO.

**Comment by dereuromark** [comment]
If 
```php
    ->patchEntity($stateMachineProcess, (array)$this->request->getData());
```
is the only and recommended way to go, I am fine adding the cast into my bake templates.
It works for phpstan level 7 at least now.

**Comment by dereuromark** [comment]
I am fine with casting, for now. Closing then as we need to focus on more important matters now.

**Comment by dereuromark** [comment]
After https://github.com/cakephp/cakephp/pull/13539 and thinking about it:
- `getDataOrFail()` would be nice, always returning an array or failing with meaningful exception.
