### ISSUE TITLE
Add native support for Polymorphic Associations

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#13135]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: Windows 10, PHP 7.3.

### What you did
I've created a simple app using this [old article ](https://scienceofweb.wordpress.com/2015/11/14/polymorphic-relations-in-cakephp-or-laravel/)as inspiration:
https://github.com/celsowm/blog

### What happened
Some frameworks like [Laravel](https://laravel.com/docs/5.8/eloquent-relationships#polymorphic-relationships), [Rails](https://guides.rubyonrails.org/association_basics.html#polymorphic-associations), [Java Lite](http://javalite.io/polymorphic_associations) have this feature. Each one implementing in their own way, but all with a similar characteristic: allow "on-the-fly" association based on a column storing the Model name, so, you can have references to multiple tables.
Currently, the "only" way is using explicit Association->setConditions() and Association->setForeignKey().

```
<?php
class AlbumsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('albums');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');
        $this->hasMany('Photos')
                ->setForeignKey('foreign_key')
                ->setConditions(['Photos.model'=> 'Album']);
    }
}
```

### What you expected to happen
Would be cool if CakePHP had something like this in the future:

```
<?php
class AlbumsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('albums');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');
        $this->hasMany('Photos')
                ->isPolymorphic(true); 
               /* default values (like tree behavior) would be 'foreign_key' 
              *  and 'model' or else manually methods like setModelCollumn() 
              * and setForeignKey() from an new Cake ORM Class "Polymorphic" 
              * would be enough. */
    }
}
```
Another cool way would be a Native Behavior like TreeBehavior to add this "polymorphic behavior" to associations.

**Comment by markstory** [comment]
This has come up a few times in the past, most recently in #4412. There exists a plugin based implementation of single table inheritance. Do you see the polymorphic association as a higher level abstraction around existing association options or something else?

**Comment by celsowm** [comment]
Hi @markstory! Well, first of all, I think Boyce & Codd would kill us for using Polymorphic Association 😅. Jokes aside, I see PA as a "fast way to avoid":

- lots of hasOne association to emulate inherentance.
- or using lots of UNION.

My "real-real" example is a table called "caixa_entrada" (translation:entry box, something like a email box, but for a public attorney job).

CaixaEntrada can have different type of "entries" from tables (from different taxonomies). Examples: a new judge sentence, a new task from boss , new reply from my intern, new scheduled return from a suit or almost any table.

My suggestion is emulate something like TreeBehavior with some patterns like "foreign_key_collumn" and "model_name_collumn".

**Comment by markstory** [comment]
I have a few more questions about how polymorphic associations would work:

* What would you want to see as the interface for defining them? To support 1:N we would need two new methods to define the associations.
* How would you expect the table classes to work for these association types. Does each type have its own table class or does each type share a table class but use multiple entity classes?

**Comment by tgoeminne** [comment]
I am also interested in this polymorphic behaviour. Where you have source_model, source_id.

**Comment by Theaxiom** [comment]
How best to create a notifications model without polymorphic associations?

**Comment by markstory** [comment]
@Theaxiom That is a great situation for a polymorphic association. There are a few plugins that offer solutions, as for a core provided one, the discussion here didn't go anywhere so I assumed that the plugins were sufficient.

**Comment by Theaxiom** [comment]
@markstory I couldn't find any plugins which support direct polymorphic associations. Back in the day, I contributed to a Polymorphic behavior, made it work with deep associations and containable; it was extremely critical in the application I was developing at the time: https://github.com/Dynamictivity/Polymorphic2.0

**Comment by markstory** [comment]
@Theaxiom https://github.com/robotusers/cakephp-table-inheritance is the most recent one I am aware of. I misremembered as it doesn't provide polymorphic associations, but single table inheritance instead. A plugin like [this tags](https://github.com/dereuromark/cakephp-tags) one use polymorphic associations internally though.

**Comment by Theaxiom** [comment]
Thanks @markstory -- I know there are ways to accomplish this through manual effort in your application, having it as part of the core or as a plugin is really just a convenience factor. :)

**Comment by markstory** [comment]
I think having a plugin first is a good way to prototype the APIs out and get something working. I don't think we'll see any core support until a plugin exists first.

**Comment by Theaxiom** [comment]
@markstory fair enough. If I end up building Polymorphic relations into my app (I decided against it for now), I will wrap it in a plugin and push it up.
