### ISSUE TITLE
4.0.0 - Transliterate return type is invalid

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13138]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2

### What you did
I created a basic method in my entity for slugs.
```php
/**
 * When setting the title, automatically create a basic slug
 *
 * @param string $title Title to be sluggified
 * @return string
 */
protected function _setTitle(string $title): string
{
    if (empty($this->get('slug'))) {
        $this->set('slug',Text::slug(strtolower($title)) . '-' . rand(1000, 9999));
    }

    return $title;
}
```

I wanted to see how it behaved, so I created a unit test for the method. 
```php
public function providerSlugs()
{
    return [
        'Basic title' => ['An example question', '/an-example-question-[\d]+/'],
        'Title with accents' => ['Das Pferd fährt nicht', '/question-with-accents-[\d]+/'],
        'Non latin title' => ['马不开车', '/ma-bu-kai-che-[\d]+/']
    ];
}

/**
 * @dataProvider providerSlugs
 */
public function testSlugGeneration($title, $expectedPattern)
{
    $question = new Question([
        'title' => $title,
        'user_id' => 1
    ]);

    $this->assertNotEmpty($question->get('slug'));
    $this->assertRegExp($expectedPattern, $question->get('slug'));
}
```

### What happened
The test failed, due to a return type error.
```bash
There was 1 error:

1) App\Test\TestCase\Model\Entity\QuestionTest::testSlugGeneration with data set "Title with accents" ('Das Pferd fährt nicht', '/question-with-accents-[\d]+/')
TypeError: Return value of Cake\Utility\Text::transliterate() must be of the type string, bool returned

/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Utility/Text.php:1108
/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Utility/Text.php:1144
/Users/davidyell/Sites/CakePHP4/src/Model/Entity/Question.php:53
/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Datasource/EntityTrait.php:257
/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/ORM/Entity.php:76
/Users/davidyell/Sites/CakePHP4/tests/TestCase/Model/Entity/QuestionTest.php:58
```

### What you expected to happen
I expected that the transliterate method would return a string rather than bool. I presume it might have failed to transliterate my string, and returned false to indicate failure.

**Comment by ADmad** [comment]
`transliterator_transliterate()` returns `false` on failure. So I guess we'll have to check it's return value and throw exception.

By the way you are using `strtolower()` instead of `mb_strtolower()` for multi byte string which might be the source of your problem.

**Comment by markstory** [comment]
Closing as a pull to throw on failure is open now.

**Comment by davidyell** [comment]
I've upgraded to 4.0.0-RC1 and now this same test is failing again, but this time with Arabic. The transliteration return has changed.

Here is my test case https://github.com/davidyell/Learning-CakePHP4/blob/master/tests/TestCase/Model/Entity/QuestionTest.php#L48

..and the output I'm getting
```bash
There was 1 failure:

1) App\Test\TestCase\Model\Entity\QuestionTest::testSlugGeneration with data set "Another non latin" ('الحصان لا يقود', '/alhisan-la-yaqud-[\d]+/')
Failed asserting that 'alhsan-la-yqwd-8179' matches PCRE pattern "/alhisan-la-yaqud-[\d]+/".

/Users/davidyell/Sites/Learning-CakePHP4/tests/TestCase/Model/Entity/QuestionTest.php:63
```

Not sure how the transliteration has changed though.

**Comment by ndm2** [comment]
Probably a change in the underlying ICU library. https://3v4l.org/oo1Y7
