### ISSUE TITLE
Cake 4 - Form Submit Button markup

### ISSUE THREAD

**Issue by riddlemd** [cakephp/cakephp#13143]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0

### Current Implementation
Cake currently uses `<input type='submit'>` which are void type elements for it's submit button type. These can not have css ::before or ::after assigned to them.

### Suggested Implementation
Changing it to `<button type='submit'></button>` with a template similar to `<button type="{{type}}" {{attrs}}>{{caption}}</button>` this would allow for a much larger range of styling to be done to submit buttons purely with css. As Well as open up some interesting use cases as `<button></button>` also supports HTML inside the tag.

The underlying form helper code to make this template work is a bit frustrating too and might deserve it's own RFC discussion as currently expanding templates to include more variables requires the entire logic of FormHelper::control, submit, etc to be copied into the override, perhaps it would make more sense to break them into preprocess functions and then have them call the preprocess and pass that info to the templater, that way if you wanted to add variables to the templeter call you could just override the primary function etc and not have to worry about all the pre processing code having to be kept up to date with cake core.

**Comment by ADmad** [comment]
We already have `FormHelper::button()` which generates submit buttons by default, so why can't you just use that? The baked add/edit forms also use this method.

**Comment by riddlemd** [comment]
> We already have `FormHelper::button()` which generates submit buttons by default, so why can't you just use that? The baked add/edit forms also use this method.

I could, I'm just pointing out submit should be consistent with those as it should be a button 9/10 times it is used. Also the code needed to add variables/tokens to templates needs some love as I discussed, not a huge rewrite of the form helper, but I'd like to see if anyone else is butting heads with it from time to time.

**Comment by ADmad** [comment]
I still don't see why you want `submit()` method to be changed when `button()` already achieves what you want. Just train your mind to type `button()` instead of `submit()` :slightly_smiling_face:.

As for other improvements you want to suggest for FormHelper please open new issue with specifics.
