### ISSUE TITLE
CakePHP 4 alpha: webroot and index.php missing 

### ISSUE THREAD

**Issue by ava007** [cakephp/cakephp#13144]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP 4.0.0-alpha1
* Platform and Target: FreeBSD, nginx, PHP 7.3.2

### What you did
Installed CakePHP 4.0.0-alfpha1 as follows:
composer create-project --prefer-dist cakephp/cakephp:4.0.0-alpha1 lfcakephp4alpha

### What happened
Installation ended successfully. The following directories and files were installed:

LICENSE         
VERSION.txt     
composer.lock   
psalm.xml       
templates       
vendor
README.md       
composer.json   
config          
src            
tests

### What you expected to happen
Expected to be installed, but missing are these directories/files:
- webroot
- webroot/index.php

**Comment by garas** [comment]
You need to install `cakephp/app`, not `cakephp/cakephp`
