### ISSUE TITLE
postgres: where clause with spaces in double quoted identifier fails

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13149]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: postgres 9.6, php 7.0, linux

### What you did
We are porting some queries to cakephp that use a legacy table with column names that require double quotes.  There are some columns that have spaces such as "Total Pounds".

When adding a where() clause to a query, we double-quoted the column name:
where->(['"Total Pounds" >= 0])

We do not have identifier quoting enabled.

### What happened
The generated SQL modified the column name in the where clause only to "Total pounds".

### What you expected to happen
I expected the identifier in the where clause to be left as-is. This did not seem to occur in other places we used the quoted identifier.

I checked for similar issues and found one involving backslashes which seems different than this case as this doesn't seem to interfere with cake or php language.

For this similar query scenario, I replaced it with a query expression which did not modify the double quoted identifier.

I did find an issue mentioning spaces dropped for cakephp 2 that met with some nasty rejection so I expect something similar here.  Dropping anyway as it doesn't seem to be tracked yet for others to find.

**Comment by markstory** [comment]
> We do not have identifier quoting enabled

If you have identifiers needing quoting why wouldn't you enable identifier quoting?

Your solution to use an expression is the right approach if you don't want to enable identifier quoting. If your interested in fixing this you would want to look hereabouts

**Comment by othercorey** [comment]
So, we don't enable automatic identifier quoting because that doesn't work with spaces (as expected though).

With identifier quoting, the expression becomes "Total" pounds > :c0 which is also incorrect.

**Comment by othercorey** [comment]
Looking at the code you linked, I'm guessing this is the culprit.  The expression is actually anything to the left of the last space in this scenario while this makes the operator everything to the right of the first space.

if (count($parts) > 1) {
    list($expression, $operator) = $parts;
}

$operator = strtolower(trim($operator));

**Comment by lorenzo** [comment]
with the current state of the code, you need to take care of this manually by using `new IdentifierExpression("Field With Spaces")` and use the `QueryExpression` API to build conditions instead of the shorthand way of using arrays

**Comment by othercorey** [comment]
I think this covers everything I wanted to convey for tracking.
