### ISSUE TITLE
AssetMiddleware does not recognize plugins more than 2 namespaces deep.

### ISSUE THREAD

**Issue by riddlemd** [cakephp/cakephp#13180]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.7
* Platform and Target: Apache, Linux

### What you did
Tried to use plugin nested 3 namespaces deep.
./plugins/Company/Project/Plugin

### What happened
AssetMiddleware does not recognize plugins more than 2 namespaces deep.
url: /company/project/plugin/css/style.css is not recognized.

This is contrary to the rest of cake's view methods like element, and cell which go multiple namespaces deep.

### What you expected to happen
AssetMiddleware to recognize plugins more than 2 namespaces deep, or at least be able to configure it easily to do so.

Looking into AssetMiddelware the foreach loop is limited to <2. Is this just a performance precautions? Could this not be a config variable in ./config/app.php?

**Comment by markstory** [comment]
> Looking into AssetMiddelware the foreach loop is limited to <2. Is this just a performance precautions? Could this not be a config variable in ./config/app.php?

Yes it is related to performance and also that there has been no practical scenario where someone needed more than 2 namespaces for a plugin.

If there was going to be a control for this, I would rather see a class constructor parameter over configure data.

**Comment by riddlemd** [comment]
That makes sense and is exactly what I ended up doing after creating a
child class of assetmiddleware. It should also perhaps be documented
somewhere, as the behavior (as I've stated) causes the HTML helper to have
several methods that do not behave like you'd expect compared to other cake
plugin resource accessors.

**Comment by ADmad** [comment]
Supporting namespaces 2 levels deep is enough for majority of the applications. If someone wants support for deeper levels then can use then own customized middleware for serving assets.
