### ISSUE TITLE
4.x snailCase template files?

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#13197]
Would it be a good idea to snail case template files by default (and keep looking for the underscored once during 4.x and drop that support in 5.x)?

Then the view template files would match one-by-one the action method names again (with the addition of .php or .ctp)

**Comment by ADmad** [comment]
Avoiding inflection is always nice. The suggested change can be easily done in a BC way by first checking for uninflected template name followed by underscored name.

**Comment by markstory** [comment]
We could rename files when switching the extensions :smile:

**Comment by markusramsak** [comment]
I love that idea. It also makes renaming code a lot easier. I my IDE I can search files by name and when I try to rename oder delete a controller and its model and its view I now have to search for different naming conventions to find the views. Especially when I have used different Prefixes in Routing (Admin, Admin/Settings, ...) it would be a lot easier to find any occurrence of the piece of code related to a specific controller.

**Comment by ADmad** [comment]
@markstory Good idea, then we don't need fallback :D
