### ISSUE TITLE
4.x EmailTrait::assertMailSentWith()

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#13206]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x

This is the signature of the method:
```php
public function assertMailSentWith(string $expected, string $parameter, string $message = ''): void
```

Suppose I want to test attachments
Attachments are an array, as returned by the `Message::getAttachments()` method.

So, I can't do something like this:
```php
$this->assertMailSentWith(['myfile.txt' => ['file' => '...', 'mimetype' => '...'], 'attachments');
```

Because the method wants a string as first argument:
```
There was 1 error:

1) DatabaseBackup\Test\TestCase\Utility\BackupManagerTest::testSend
TypeError: Argument 1 passed to DatabaseBackup\Test\TestCase\Utility\BackupManagerTest::assertMailSentWith() must be of the type string, array given, called in /home/mirko/Libs/Plugins/cakephp-database-backup/tests/TestCase/Utility/BackupManagerTest.php on line 180

/home/mirko/Libs/Plugins/cakephp-database-backup/vendor/cakephp/cakephp/src/TestSuite/EmailTrait.php:229
/home/mirko/Libs/Plugins/cakephp-database-backup/tests/TestCase/Utility/BackupManagerTest.php:180
```

So, in my opinion, there are two possibilities:

1. allow the first argument of `assertMailSentWith()` to be an array;
2. add a new method, something like `assertMailSentWithAttachment()`
```php
public function assertMailSentWithAttachment(string $expectedFilename, array $expectedFile, string $message = ''): void
```
or
```php
public function assertMailSentWithAttachments(array $expectedFiles, string $message = ''): void
```

I want to remember that the `EmailAssertTrait::assertEmailAttachmentsContains()` method existed in CakePHP 3.x.

**Comment by dereuromark** [comment]
Do you want to make a PR with your suggested changes?

**Comment by mirko-pagliai** [comment]
OK, I'll do it on Monday

**Comment by markstory** [comment]
Pull request merged now.
