### ISSUE TITLE
Form validation for nested field

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#13217]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.7
* Platform and Target: ubuntu, php7.2-fpm, nginx, mariadb

### What you did
Saving some custom features into a JSON field `options` i want to add rules into some of theses options

    /**
     * @param Validator $validator
     *
     * @return Validator
     */
    public function validationMenuSubPages(Validator $validator)
    {
        $validator = $this->validationDefault($validator);

        $subpages = new Validator();
        $subpages
                ->requirePresence('subpages', true)
                ->allowEmptyString('subpages', false);

        $validator
                ->addNested('options', $subpages)
                ->requirePresence('options', true)
                ->allowEmptyString('options', false);

        return $validator;
    }

This is my form

    <?= $this->Form->control('options.subpages', [
        'label' => __d("content_builder", "Pages à afficher"),
        'type' => 'select',
        'multiple' => true,
        'options' => $entity->get('subpages')
    ]) ?>

### What happened

Submitting the form without data, the validation work, but is not cathed by FormHelper to be reinjected into my form view...

    +"[errors]": array:1 [▼
        "options" => array:1 [▼
            "subpages" => array:1 [▼
                "_empty" => "This field cannot be left empty"
            ]
        ]
    ]

Seems related to #11206 

### What you expected to happen

The validation error should be related to the view form and not out of context, here i need to manually bind theses validation (requierements / errors) into my form, breaking the need of using FormHelper

**Comment by markstory** [comment]
How are you currently getting the error values? From what I found in my testing `$entity->getErrors('options.subpages')` doesn't return the error either, which is a separate but related error.

**Comment by markstory** [comment]
Closing as a pull request is open.
