### ISSUE TITLE
Additional steps required for "Adding the new HTTP Stack to an Existing Application"

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#13211]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: N/A

### What you did
We just performed the migration described in https://book.cakephp.org/3.0/en/development/application.html#adding-the-new-http-stack-to-an-existing-application.  There were a few other necessary steps that should be added to that documentation:
* Updated bootstrap.php and bootstrap_cli.php from the app skeleton
* Updated bin/cake* from the app skeleton
* Added a "\_cake_routes\_" cache definition in app.php

**Comment by markstory** [comment]
Any chance you'd be willing to update the documentation? The source for that page [lives here](https://github.com/cakephp/docs/blob/3.0/en/development/application.rst).

**Comment by tharlinsmith** [comment]
Sure, and I'll take that as an endorsement that the additions make sense.

**Comment by markstory** [comment]
Fixed in cakephp/docs#6067
