### ISSUE TITLE
Cakephp 4.x-dev requires zendframework/zend-diactoros ^2.0

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/cakephp#13229]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev.
* Platform and Target: MacBook Pro local install, PHP 7.2.1.

### What you did
composer require nexmo/client

### What happened
Nexmo's client SDK's composer.json at https://github.com/Nexmo/nexmo-php/blob/master/composer.json specifies "zendframework/zend-diactoros": "^1.3". The CakePHP master branch's composer.json currently specifies "zendframework/zend-diactoros": "^1.4.0".

However, the 4.x-dev branch bumps the minimum version for zend-diactoros to ^2.0. This means that, for the moment, I need to abandon CakePHP 4.x for this project. I thought you'd like to know, and am providing this issue as feedback. Please close/resolve this issue in whatever manner makes sense.

### What you expected to happen
I expected to still be able to integrate the Nexmo API's PHP toolkit via "composer require".

**Comment by markstory** [comment]
Do you know if Nexmo has any plans in updating to diactoros 2.x?

**Comment by josegonzalez** [comment]
Looks like _maybe_. I've linked the ticket as appropriate, and someone seems to have come up with a workaround...

**Comment by ewbarnard** [comment]
Lorna Mitchell has a PR for the Nexmo SDK here https://github.com/Nexmo/nexmo-php/pull/175 and Michael Heap asked her if that PR should allow version ~2.0 as well. So Nexmo's aware of the issue and I don't think the CakePHP dependency version needs to be relaxed. Perhaps we should flag the 1.x vs. 2.x Diactoros change in the release notes or migration guide? 

From my standpoint this issue can be closed - Nexmo is aware that at least one framework has moved up to requiring Diactoros ~2.0.

**Comment by mheap** [comment]
https://packagist.org/packages/nexmo/client#1.8.1 has been released and should solve this issue
