### ISSUE TITLE
FormContext removes error name keys

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#13235]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.7

### What you did

I have  a modelless form with custom validation.

```php
class RegisterForm extends Form
{
    public function validationDefault(Validator $validator)
    {
        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->allowEmptyString('email', false);
    }
}
```

I wanted to overwrite error messages using form helper.

```php
 $this->Form->control('email', [
    'label' => false,
    'placeholder' => __('E-mail address'),
    'error' => [
        'email' => __('Please provide a valid e-mail address.'),
    ]
]) 
```

### What happened

Error messages set with a helper are not displayed.

### How to fix it

`FormContext` returns only array values in `errors()`:

https://github.com/cakephp/cakephp/blob/cedcb681b3e383dfa272956b002a0448aa4443c6/src/View/Form/FormContext.php#L227-L230

This should be easy to fix by removing `array_values()` but is it BC safe enough? 

This says the error array is expected to have error names:

https://github.com/cakephp/cakephp/blob/cedcb681b3e383dfa272956b002a0448aa4443c6/src/View/Helper/FormHelper.php#L790-L791

**Comment by markstory** [comment]
How does EntityContext behave?

**Comment by robertpustulka** [comment]
@markstory it does not drop the keys. Error message overwrite feature works correctly with entities.

**Comment by markstory** [comment]
Having this implementation match EntityContext makes sense to me.
