### ISSUE TITLE
3.next: Auto-init hasMany property?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13231]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.next (current 3.x master has the issue)

### What you did
```php
$releaseGroup = $this->saveOrFail($releaseGroup);
// $releaseGroup->release_elements is null as it wasnt touched (yet).

$releaseElement = $releaseGroupsTable->ReleaseElements->saveOrFail($x);
$releaseGroup->release_elements[] = $releaseElement;

$releaseElement = $releaseGroupsTable->ReleaseElements->saveOrFail($y);
$releaseGroup->release_elements[] = $releaseElement;

return $releaseGroup;
```

### What happened
The release group didnt have any of the properties further on in code :/

### What you expected to happen
a) If the current property is not set (null), this should be equal to empty collection (array `[]`).
The entity should auto init and then assign the properties.

b) OR fail with some kind of feedback.
Currently, it silently swallows it without clear message why this operation didnt do what it was intended to do.

I am for a) if that is possible in 3.next.

To clarify, this works (but should not be necessary - or otherwise fail with clear dev feedback):
```php
$releaseGroup = $this->saveOrFail($releaseGroup);
$releaseGroup->release_elements = []; // HERE

$releaseElement = $releaseGroupsTable->ReleaseElements->saveOrFail($x);
$releaseGroup->release_elements[] = $releaseElement;

$releaseElement = $releaseGroupsTable->ReleaseElements->saveOrFail($y);
$releaseGroup->release_elements[] = $releaseElement;

return $releaseGroup;
```

**Comment by markstory** [comment]
When would the orm initialize empty association properties? We would have to be careful about managing the dirty state as to not accidentally wipe any already persisted but not loaded data.

**Comment by dereuromark** [comment]
if the property is null, as in this case, only IMO. In this case one would except the collection to init and collect the first assigned collection item.

I agree that we have to be careful, but here the issue is that it seems to be assigned fine, but in fact the returned group doesnt contain any such collection. This is a bug that needs addressing either way.

**Comment by othercorey** [comment]
Could you explain a little more where in that code you expect it to assign?

**Comment by robertpustulka** [comment]
> a) If the current property is not set (null), this should be equal to empty collection (array []).

I don't think it's a good idea. `null` means the collection has not been initialized. It is not an equivalent of an empty collection. I believe this change would break BC.

Is there any way of checking if a `null` is accessed as an array?

**Comment by dereuromark** [comment]
And then throwing exception? That would also be fine.

**Comment by ADmad** [comment]
> Is there any way of checking if a null is accessed as an array?

Pretty sure there isn't a way to differentiate between 
`$entity->foo[] = 'val'` vs `$bar = $entity->foo`
 for a unset property `foo`. 

For both cases the magic `__get()` method of the entity is the method that get's call with `foo` as field. There's no way to tell if you are trying to do any array operation. `__isset()` or `__set()` never get called either.

**Comment by dereuromark** [comment]
All entity docblocks are then lying, by the way, both for required and for optional fields. But especially for required scalar or relation properties.
```
/**
 * @property \App\Model\Entity\Release $release
*  @property \App\Model\Entity\Features[] $features
 */
```
on an entity that has a required (not null) release_id field would then actually also have to be annotated as
```
/**
 * @property \App\Model\Entity\Release|null $release
 * @property \App\Model\Entity\Features[]|null $features
 */
```

Same for the 0...n collection of "hasMany Features" then.

There must be a way to detect that a collection item is being tried to add to null property, right now this is cloaked silently, and we just need to make this non-silent. That would already solve the main issue at hand, dismissing the docblock lies for now. Using [GetTrait](https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Entity/GetTrait.php) you can make static analyzers happy (PHPStan level 7) etc, which here is enough for me at the time.

**Comment by robertpustulka** [comment]
Yeah, looks like docblocks are lying but only if you don't contain the relations explicitly. I tripped over this so many times, having to check if a related entity is set every time is a pain.

The entity should probably know somehow if a relation property is optional (nullable) or not and throw an exception if it's being accessed while being non-optional and null at the same time. Not possible for 3.x but maybe 4.x?

Too bad that entities are dumb and know little about the data they contain. It would be great if entities performed at least some basic internal validation on accessed properties in the future. Maybe 5.x :)

**Comment by dereuromark** [comment]
Well, that's why I have the traits now in place, that allows the surrounding code at least to know what is going on and is a bit cleaner for this use case. If you really want to have consistent containers, use [dtos](https://github.com/dereuromark/cakephp-dto).

We should still fix this silent no op here. Rest is fine for me to ignore on core level.

**Comment by ADmad** [comment]
> The entity should probably know somehow if a relation property is optional (nullable) or not and throw an exception if it's being accessed while being non-optional and null at the same time.

I don't think that would be achievable without using concrete properties for relations. Only than we would be able to do null checks.

**Comment by robertpustulka** [comment]
On a side note, it is also a good idea to use concrete methods for changing the state of the entity and wrap the current state checks in that method. 

So instead `$releaseGroup->release_elements[] = $releaseElement` have `$releaseGroup->addReleaseElement($releaseElement)`. It's not very RAD anymore having to implement a method for every little thing you need to do with your entity but at least you get the bullet-proof business logic and clean API.

**Comment by dereuromark** [comment]
Do we want to do anything here for 4.0+?
Otherwise, I am also happy to close this as "works-for-me" :/
