### ISSUE TITLE
ISO8601 for datetime json format, when on Danish locale

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13232]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7, 3.8.
* Platform and Target: LAMP (Ubuntu, with Danish locale).

### What you did
var_dump((new FrozenTime())->jsonSerialize());

### What happened
Output is string(25) "2019-05-14T10.22.48+02:00"

### What you expected to happen
':' should be used for time instead of '.':
string(25) "2019-05-14T10:22:48+02:00"

The similar issue is described by another user here:
https://gist.github.com/stoykovnet/a3fc93f0e54c71f69854ddce2e8fa728

**Comment by ADmad** [comment]
You can use `FrozenTime::setJsonEncodeFormat()` in your bootstrap to set required format.

**Comment by andrii-pukhalevych** [comment]
@ADmad Default value for DateFormatTrait::$_jsonEncodeFormat = "yyyy-MM-dd'T'HH:mm:ssxxx" (with ':' for time).
But in DateFormatTrait::jsonSerialize() it uses i18nFormat(), so value is incorrect with Danish locale:
```
public function jsonSerialize()
{
	return $this->i18nFormat(static::$_jsonEncodeFormat);
}
```

**Comment by andrii-pukhalevych** [comment]
Maybe change default value `DateFormatTrait::$_jsonEncodeFormat = DateTime::ATOM`
and use normal format instead of i18nFormat:
public function jsonSerialize() {
	return $this->format(static::$_jsonEncodeFormat);
}

**Comment by inoas** [comment]
For 4.0+, could we switch it to an expected standard in JS/JSON-World aka:
https://stackoverflow.com/a/15952652

**Comment by ADmad** [comment]
@andrii-pukhalevych If the default string for `$_jsonEncodeFormat` has colons `:` how do they get converted to dots `.`?  Are you sure the default string isn't getting changed?

**Comment by andrii-pukhalevych** [comment]
@ADmad I dind't change default json format string anywhere. 
It works correct on server, but produces dots on production server.
In app config I have `'defaultLocale' => env('APP_DEFAULT_LOCALE', 'da_DK'),`
Locally I cant reproduce issue with php 7.0 or 7.3, icu 52 or 62.

Anyway, it shoud use `DateTime::ATOM` as default format and normal format for json, 
because json don't need locale-depended delimiters.

**Comment by ADmad** [comment]
If the same issue doesn't occur for you locally than it's more likely an environment/configuration issue rather than a bug in the code.

**Comment by andrii-pukhalevych** [comment]
Somewhere in server settings they have dots `.` for time delimiters.
But this does not mean that default `$_jsonEncodeFormat` should produce dots in json encoded time.
Found solution for this: set default format to `$_jsonEncodeFormat = "yyyy-MM-dd'T'HH':'mm':'ssxxx"`
Single quotes around colons prevents locale-depended delimiters for default format, 
but still allow to override default format and uses `i18nFormat` for formatting

**Comment by ADmad** [comment]
That's really strange, I have no idea what's going on :slightly_smiling_face:. Hopefully someone else does.

**Comment by othercorey** [comment]
@andrii-pukhalevych what version of php is your server running?

**Comment by andrii-pukhalevych** [comment]
@othercorey PHP 7.0.33-0ubuntu0.16.04.4

**Comment by othercorey** [comment]
I could not reproduce the issue with 7.0.x.  It seems unlikely to be a php-intl or libicu bug.

If you call `FrozenTime::setJsonEncodeFormat("yyyy-MM-dd'T'HH:mm:ssxxx");` using the same original format does it work? I was wondering if something was overwriting the default before you call jsonSerialize().

**Comment by andrii-pukhalevych** [comment]
@othercorey 
Code:
```
ini_set('display_errors', 1);
echo datefmt_create('da_DK', 0, 0, 'UTC', null, "yyyy-MM-dd'T'HH:mm:ssxxx")->format(0);
phpinfo(INFO_GENERAL);
```
Output:
```
1970-01-01T00.00.00+00:00
PHP Version 7.0.33-0ubuntu0.16.04.4
```

**Comment by othercorey** [comment]
Perhaps it's worth submitting a bug report to php?  I looked and didn't find anything related to this.

The . and : characters are not locale-specific. They're considered escaped characters even without the ':' so that seems like a bug?

**Comment by andrii-pukhalevych** [comment]
`datefmt_create` is part of internationalization extension (php-intl) "that is a wrapper for ICU library, enabling PHP programmers to perform various locale-aware operations".

[http://www.icu-project.org/userguide/formatDateTime](http://www.icu-project.org/userguide/formatDateTime) explains:

> Otherwise all ASCII letter from a to z and A to Z are reserved as syntax characters, and require quoting if they are to represent literal characters. In addition, certain ASCII punctuation characters may become variable in the future (eg ":" being interpreted as the time separator and '/' as a date separator, **and replaced by respective locale-sensitive characters in display**).

This means that on some server configurations unquoted colons will produce incorrect values for json. 
So `$_jsonEncodeFormat` value should be changed to `"yyyy-MM-dd'T'HH':'mm':'ssxxx"`.

**Comment by othercorey** [comment]
I still suggest filing a php bug report to find out what is happening.

**Comment by ADmad** [comment]
That's good info @andrii-pukhalevych. If `"yyyy-MM-dd'T'HH':'mm':'ssxxx"` consistent results across all environments the we can use that as default format.

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/cakephp/pull/13243

**Comment by othercorey** [comment]
If you post a php bug report on this, can you comment the link here?
