### ISSUE TITLE
Controller::afterFilter() as no access to the response returned from an action

### ISSUE THREAD

**Issue by hmic** [cakephp/cakephp#13249]
[x] enhancement
* CakePHP Version: master

**AController.php:**
```
...
public function some() {
    return $this->response->withStringBody('empty');
}
public afterFilter($event) {
    return $this->response->withHeader('additional', 'stuff');
}
...
```

I expected a response with the string 'empty' as the body and the header 'additional' set to 'stuff'. I got a response with the header, but not the string body.

FROM IRC:

> hmic: Is there a way to access the resposne returned from an action in a afterFilter callback? - Of course I can access $this->response from it, but that does not (necessarily) reflect whats returned from the controller action. - Or any other solution on how to change the response of any action (i just want to add additional headers) in the afterFilter callback?
It's just weird that it (afterFilter) has no access to the response object that has been returned by an action, but is able to return a response that will be send...

> admad: hmm.. yeah Controller::$response never get's updated if an action explicitly return response.  It's updated only when render() is called.

> hmic: Either i need that be accurate in the afterFilter callback, or I need access to the response object that has been returned from the action in the $event data, somehow.

> admad: Fix is easy, ActionDispatcher::_invoke() should check and set return value of invokeAction() call.

**Comment by ADmad** [comment]
Actually it should be `Controller::invokeAction()` itself that should set `Controller::$response` not `ActionDispatcher::_invoke()` :slightly_smiling_face:.

**Comment by dereuromark** [comment]
PR open.
