### ISSUE TITLE
`$this->{'NotLoadedModel'}` silently reverts to `$this`

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#13256]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2

### What you did

```
// in Model/Table/SomeTable.php
function getDataFromAnotherTable($id) {
    $tableLocator = \Cake\ORM\TableRegistry::getTableLocator();
    $anotherTable = $tableLocator->get('AnotherTable');
    // the following was copy-pasted from elsewhere
    $this->{'AnotherTable'}->get($id); 
}
```

### What happened

> Exception: Table "App\Model\Table\SomeTable" is not associated with "AnotherTable"

Apparently, after failing to locate `$this->{'AnotherTable'}`, it reverted to just `$this`, which happened to be the initial `SomeTable`.

### What you expected to happen

> Exception: Trying to access "AnotherTable" which is not loaded

I understand this was my fault, but still if the system can detect that, making the reason obvious would help to detect the problem much faster

**Comment by ADmad** [comment]
It didn't "revert" to `$this`. You are already in context of SomeTable (referenced by $this) trying to access it's non existent property.

Perhaps changing the order of the names mentioned in the error message will avoid confusion: `'AnotherTable is not associated with 'SomeTable'`.

**Comment by markstory** [comment]
The exception you're seeing happens when `Table::__get()` attempts to resolve `$this->{'AnotherTable'}` which fails as the association doesn't exist.

There is no fallback to $this happening. Would the error message be clearer if it said

> You've attempted to access `$this->AnotherTable` from `App\Model\Table\SomeTable` but that association is not defined.

**Comment by mehov** [comment]
I got confused because I tried to access `AnotherTable` (as a property of `SomeTable`), but instead I got the base `SomeTable` itself – this is why I used the word "revert" (although @ADmad I don't insist on it). The object I got looked and acted like a table, and it took me some non-zero time to figure out it's just a wrong one.

I'm not sure why is the framework doing that: is it due to the architecture, or it's just trying to "help", but it feels misleading. For me, this good old PHP notice would seem more precise and straightforward:

> Notice (8): Undefined property: SomeTable::$AnotherTable

However, the message wording is completely up to you. Moreover, I understand there must be reasons for such implementation, so I'm not trying to argue. I was just trying to see if there's a way to somehow avoid any future confusion.

**Comment by ADmad** [comment]
Table classes have magic `__get()` method which auto load associations for you and when an association with the name you are trying to access is not setup it throws the error message you get, not PHP's standard "Undefined property" error you expect.

**Comment by markstory** [comment]
I've put up a pull request to improve the error message. Any feedback would be appreciated.
