### ISSUE TITLE
Use view builder options instead of special view vars like "_serialize"

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13272]
Currently we use special view vars like `_serialize`, `_jsonOptions`, `_xmlOptions` etc. for various options for `JsonView` and `XmlView`.

Instead of abusing data vars for configuring the serialized view classes, we can use `ViewBuilder::options()` which allows passing custom options to them.

I can whip a PR if there's an agreement.

**Comment by dereuromark** [comment]
Isn't the main benefit of those options, similar to Routes, that you can store them as array, or even pass them down more easily like this from different APIs?
When making them pure class options this will not work this way anymore. But I dont think this is a strong case against it.

**Comment by markstory** [comment]
What would the upgrade path be for folks using the current system?

**Comment by ADmad** [comment]
We can check for the new view options and if unset check for the corresponding view vars currently used. In debug mode throw a warning to use new option instead. Drop the check for old view vars in 4.1.

**Comment by markstory** [comment]
That could work well.
