### ISSUE TITLE
Thinking of implementing $this->request->getPass(0)

### ISSUE THREAD

**Issue by groovenectar** [cakephp/cakephp#13288]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

It is sometimes useful to get the URL segments based on a numeric index. Personally, I see this as relatively common use case.

Right now, we can do this with this method, for example to get the `about` segment from `/pages/about` (the 2nd segment at index 1):

    $this->request->getParam('pass')[1];

If the current request is `/pages`, this will throw an error because the index is not defined.

One option may be to use:

    $isAboutPage = !empty($this->request->getParam('pass')[1]) && $this->request->getParam('pass')[1] === 'about';

But if we have a `$this->request->getPass()` method, we eliminate the need to check first, and it would just work:

    $isAboutPage = $this->request->getPass(1) === 'about';

Perhaps it might actually be named `getSegment()`, `getUriSegment()`, `getPathSegment()`, `getPathPart()`, etc? Another name might be `Fragment` or `UriFragment`. Or perhaps it would be implemented in the `Url` helper instead, like `$this->Url->getSegment()`

See also:

https://www.codeigniter.com/userguide3/libraries/uri.html#CI_URI::segment
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Request.php#L160

I would like to implement this, but I don't want to waste time if it's no one else wants it, or some other reason that it might not be accepted. I know I want this method to exist

**Comment by markstory** [comment]
I think the using `segments` or `pathSegment` is better than `getPass()` as 'pass' already means something in the context of CakePHP's routing.

I don't think we'd be able to add this to the `Uri` object inside the request, but the new methods could be added to the `ServerRequest` object directly.

**Comment by othercorey** [comment]
You're free to submit a PR any time if you want to work on this!
