### ISSUE TITLE
Must set field alias for setDefaultTypes() to hydrate dates

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13283]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: apache 2.4, postgres 9.6

### What you did
I selected a date from a table along with other aggregate fields after grouping results.

```
        $collection = $query
            ->select([
                'service_date'
            ])
            ->setDefaultTypes(['service_date' => 'date'])
```

### What happened
The date field was not hydrated to a FrozenDate object but left as a string.  This only worked if  I set an alias for the field: select([`service_date` => `service_date`]).

### What you expected to happen
I was expecting the fields to be converted to a FrozenDate object because the field was specified in `setDefaultTypes()`.

**Comment by markstory** [comment]
What is the generated query without the alias? You might need to call `setDefaultTypes()` with the `Model.service_date`. Internally the Query object sets both `Model.field` and `Model__field` keys into the type map, and userland usage would have to do the same.

**Comment by othercorey** [comment]
```sql
SELECT WssEntries.service_date AS "WssEntries__service_date" FROM wss_entries WssEntries
```

So, you need to pass the Association.Field name to setDefaultTypes().

**Comment by markstory** [comment]
> ... but maybe documentation could be cleared up.
I'm happy to do that, which documentation were you referencing?

**Comment by othercorey** [comment]
I'm not really sure of the intended use and am not sure what to recommend.  After re-reading the documentation, I'm just resolved to avoid it.

**Comment by markstory** [comment]
If you need you set types for aliases fields you can also use the $types parameter of select() which should handle aliasing from what I remember.

**Comment by othercorey** [comment]
I think it could be helpful to link the setDefaultTypes documentation to the TypeMap setDefaults documentation which does the actual work.

Perhaps a sentence explaining if there is a difference between setting types here vs other $types parameters.

**Comment by othercorey** [comment]
@markstory I'm not sure what $types parameter of select() is

>If you need you set types for aliases fields you can also use the $types parameter of select()

**Comment by markstory** [comment]
The `$type` parameter of select/where is the last argument and lets you specify how a field should be mapped in the current query. You can see an example [here](https://book.cakephp.org/3.0/en/orm/query-builder.html#automatically-creating-in-clauses). That is the interface I would recommend using unless you would need to set types multiple times in a query. Instead of setting types multiple types you can use defaults.

**Comment by othercorey** [comment]
But. that doesn't exist for select() does it?  At least I've yet to find it.

https://api.cakephp.org/3.7/class-Cake.ORM.Query.html#_select

**Comment by markstory** [comment]
You're right, my mistake. I think the selectTypeMap() method is the one we would want to use but I will confirm that.

**Comment by markstory** [comment]
Yes, `$query->getSelectTypeMap()->addDefaults(...)` is how the ORM internally sets type mappings for fields when [queries are transformed](https://github.com/cakephp/cakephp/blob/f263df5768598e3edb34365d1fed86fa9aa106f0/src/ORM/Query.php#L1204-L1222) to the driver dialect.

**Comment by othercorey** [comment]
Why does select have a separate type map from other $types including insert?  Sorry if this is annoying line of questioning, but I'm having a hard time following the nuances.  Wouldn't a single type map work for all scenarios?

From ``Query::insert``
>@param array $types A map between columns & their datatypes.
```
$this->_parts['values'] = new ValuesExpression($columns, $this->getTypeMap()->setTypes($types));
```

**Comment by markstory** [comment]
> Why does select have a separate type map from other $types including insert?

I don't remember to be honest. The commit logs likely have the answer though.

**Comment by othercorey** [comment]
@markstory commit 8477fa8bb89ea6c33bd8d9f62870aaa030d5afca

**Comment by markstory** [comment]
It may be related to select queries being able to use other queries in the where/join clause and not wanting the type maps of subqueries to become mixed with the select clause.
