### ISSUE TITLE
Finder closure for dynamically set associations

### ISSUE THREAD

**Issue by r34117y** [cakephp/cakephp#13286]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x ] feature-discussion (RFC)

* CakePHP Version: 3.7.0
* Platform and Target: Not relevant

### What you did
I used closure as finder in accociation definition.
```
        $labels = TableRegistry::getTableLocator()->get('Labels')->find('models');

        foreach ($labels as $id => $label) {
            $pluralModelName = Inflector::pluralize($label);
            $this->belongsToMany($pluralModelName, [
                'className' => 'Elements',
                'joinTable' => 'pwt_elements',
                'foreignKey' => 'pwt_id',
                'targetForeignKey' => 'element_id',
                'finder' => function (Query $query) use ($pluralModelName, $id) {
                    return $query->where(["{$pluralModelName}.label_id" => $id]);
                }
            ]);
        }
```

### What happened
`Table.php`  method `callFinder()` raised error. It didn't expect closure, just string.
I could use custom finder, but then how do I pass options to it?

### What you expected to happen
Closure working in association definition.

**Comment by r34117y** [comment]
```
if ($type instanceof \Closure) {
     return call_user_func($type, $query);
}
```
in `callFinder()` method in `Table.php` does the job.

**Comment by markstory** [comment]
>  I could use custom finder, but then how do I pass options to it?

Have you tried using an array?

```
$this->belongsTo('Things', [
  // other options
  'finder' => ['published => ['option1', 'option2']]
]);
```
This might not be documented well, but it is covered by test cases.

**Comment by r34117y** [comment]
No, I didn't dig into tests :) Thanks for that tip.

But I still believe it would be nice to have opportunity to use closure as finder, as custom finder role is to avoid duplicating logic and in case we want to use certain query just once it's more natural to use anonymous function.

**Comment by markstory** [comment]
> But I still believe it would be nice to have opportunity to use closure as finder, as custom finder role is to avoid duplicating logic and in case we want to use certain query just once it's more natural to use anonymous function.

I can see how it would be convenient in some scenarios to use a closure, but it will require adding special casing in multiple places in the framework to handle a use case that can already be handled with the features we have. In efforts to not increase complexity/documentation/testing efforts I'd rather not have another way to do this.
