### ISSUE TITLE
SaveMany not save with boolean

### ISSUE THREAD

**Issue by bcetienne** [cakephp/cakephp#13280]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.0.
* Platform and Target: 
  - System: Linux ubuntu-xenial 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64
  - Server API: Apache 2.0 Handler
  - Apache version : Apache/2.4.18 (Ubuntu)
  - Database : MySQL
  - PHP version : 7.2.15-1

### What you did
 ```
public function updateTrainingsShow() {
      $this->RequestHandler->renderAs($this, 'json');
      $this->set('_serialize', true);
      $response = [];
      $trainings = $this->request->getData();
      $toSave = [];
      foreach ($trainings as $training) {
        $result = $this->Formations->get($training['id']);
        $result->show = $training['show'];
        $toSave[] = $result;
      }
      $this->Formations->saveMany($toSave);
      $this->set($response);
    }
```
I also reused Cake's answer to make the request by hand via MySQL CLI, this one works, whether it is a string, integer or boolean type with `UPDATE formations
SET formations.show = false, updated = '2019-05-22 13:11:23' WHERE id = 27;`.

I've clear cache.

I also tried to harden the boolean, string and integer type, but the result remains the same.

The function is executed if, for example, I modify a text field.

### What happened
`Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show = 0 , updated = '2019-05-22 13:11:23' WHERE id = 27' at line 1`

The `show`value doesn't change.

### What you expected to happen
What is normally expected to happen is that the database value `show` should be `true` or `false` (`false`in this case).

Thanks

**Comment by bcetienne** [comment]
I've also tried with that (always in Controller) but same error
```
        $this->Formations->updateAll(
          ['show' => $training['show']],
          ['id' => $training['id'], 'show' => !$training['show']]
        );
```

**Comment by ADmad** [comment]
"show" is a reserved word in MySQL. You will have to turn on [identifier quoting](https://github.com/cakephp/app/blob/master/config/app.default.php#L271) if you want to use it as a column name.

**Comment by dereuromark** [comment]
I still believe it would be the smarter default value to keep it on as per my [tips](https://sandbox.dereuromark.de/pages/beginner-tips#enable-quote-identifiers).
Everything else is an optimization that can be done later if needed. But for many cases it just works fine this way - and beginners also have less trouble.
I always have it on in all of my apps.

**Comment by ADmad** [comment]
I disagree. Having identifier quoting on by default would mean such problems would go unnoticed initially and then it would be too late to change table schema if one wants to optimise after the app goes to production.
