### ISSUE TITLE
MSSQL query having condition on aggregated aliased field

### ISSUE THREAD

**Issue by inspectorman** [cakephp/cakephp#13293]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.11

### What you did
I have been trying to add a Having condition for an aliased max field in a Query, I'm using MSSQL Server for the database.
The select looks like:
`'diam_1'=>$q->func()->max('(tmls.nom_diam)'),`
and the having function looks like:
`$q->having(['diam_1 >='=>5])`

### What happened
Sql Srv throughs an error telling that diam_1 is not a recognized field.

### What you expected to happen
I would expect that query builder would detect that the diam_1 is actually an aggregated field and must convert the having statement to: Having(max(tmls.nom_diam)>=5) as it does with order clauses on aggregated named fields.

**Comment by markstory** [comment]
I don't think this was ever implemented. If you want to build it I can help with tests.

**Comment by othercorey** [comment]
> convert the having statement to: Having(max(tmls.nom_diam)>=5) as it does with order clauses on aggregated named fields

There is code that replaces a column alias with the expression sql in order by clauses?

**Comment by markstory** [comment]
Closing as there is a pull request open for this now.
