### ISSUE TITLE
Use the 'finder' option from an association in the existsIn build rule

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#13295]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: I guess such thing would be for `4.x`
* Platform and Target: Not sure this is relevant for non-bugs :) 

### What you did
```php
//Userstable.php::beforeFind(Event $event, Query $query, ArrayObject $options)

return $query->where(['Users.deleted' => null]);
```

```php
//Userstable.php::findWithTrashed(Query $query, $options)

return $query->where([
	'OR' => [
		'Users.deleted IS' => null,
		'Users.deleted IS NOT' => null
		]
	]);
```

```php
//ArticlesTable.php::initialize($config)
$this->belongsTo('Users', [
    'foreignKey' => 'user_id',
    'joinType' => 'INNER',
	'finder' => 'withTrashed' //Soft-delete related finder from https://github.com/UseMuffin/Trash
]);
```

```php
//ArticlesTable.php::validationDefault($validator)
$rules->add($rules->existsIn(['user_id'], 'Users'));
```

```php
//Create new entity with a user that is not found in the default ->find() but only with the custom finder
$article = $this->Articles->newEntity([
	'user_id' => 1,
	'content' => 'foo',
]);

$this->Articles->save($article); //This one fails if user with ID 1 is not present in default find.
```

### What happened
The ExistsIn build rule is not passing since the `User` is not found with the default `->find()`

### What you expected to happen
that the ExistsIn build rule would respect the 'finder' option in `->belongsTo('Users')` in Articlestable as I believe it respects 'conditions' array (at least per: https://github.com/cakephp/cakephp/issues/7968)

I'm sorry if this has already been discussed before, but I could not find a particular issue with `ExistsIn` and `finder` options

**Comment by markstory** [comment]
This change has already been made for 4.0. See the [exists method](https://github.com/cakephp/cakephp/blob/8067bd0b59004609654c63e8134b05ed5ca46bc0/src/ORM/Association.php#L866). I think this would be a risky change for 3.x.

**Comment by dereuromark** [comment]
Closing then.
