### ISSUE TITLE
Save multiple tree inside the table

### ISSUE THREAD

**Issue by bouro** [cakephp/cakephp#13306]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Tested in 3.7.8 & 3.5.18
* Platform and Target: Linux PHP 7.3

### What you did

```php
class TemplatesTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('Tree');
    }

    public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)
    {
        $this->behaviors()->get('Tree')->config([
            'scope' => [
                'Templates.category_id' => $entity->category_id
            ],
        ]);
    }
}
```

### What happened
The scope is not supported and we can't create one tree per category

| id  | category_id | name | parent_id | lft | right |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 1  | 20  | Template 1  | null  | 1  | 2  |
| 2  | 25  | Template 2  | null  | 3  | 4  |
| 3  | 20  | Template 3  | null  | 5  | 6  |
| 4  | 20  | Template 4  | null  | 7  | 8  |
| 5  | 25  | Template 5  | null  | 9  | 10  |

### What you expected to happen
Persist multiple tree inside the table

| id  | category_id | name | parent_id | lft | right |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 1  | 20  | Template 1  | null  | 1  | 2  |
| 2  | 25  | Template 2  | null  | 1  | 2  |
| 3  | 20  | Template 3  | null  | 3  | 4  |
| 4  | 20  | Template 4  | null  | 5  | 6  |
| 5  | 25  | Template 5  | null  | 3  | 4  |

### Observation
When i enable the Tree behavior inside the callback beforeMarshal, it works!

```php
class TemplatesTable extends Table
{
    public function initialize(array $config)
    {
        // $this->addBehavior('Tree');
    }
    
    public function beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)
    {
        $this->addBehavior('Tree');
    }

    public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)
    {
        $this->behaviors()->get('Tree')->config([
            'scope' => [
                'Templates.category_id' => $entity->category_id
            ],
        ]);
    }
}
```

**Comment by markstory** [comment]
You cannot enable Behaviors in `beforeSave()` as behavior beforeSave events are fired *before* the Table event listener. You could overload `save()` and put your logic there.

**Comment by bouro** [comment]
I understand, thanks for your answer. What is the best place to overload `save()` without reinventing the wheel

**Comment by markstory** [comment]
You can do something like

```php
public function save(EntityInterface $entity, $options = [])
{
   $this->behaviors()->get('Tree')->config([
            'scope' => [
                'Templates.category_id' => $entity->category_id,
            ],
   ]);
  return parent::save($entity, $options);
}

**Comment by bouro** [comment]
Thanks for your help ;)
