### ISSUE TITLE
I18N ExtractTask does not extract those strings generated and passed to Gettext through core helpers

### ISSUE THREAD

**Issue by trenshaw** [cakephp/cakephp#13303]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.10.18
* Platform and Target: Nginx 1.14.0, PHP 7.2.17, MySQL 5.7.26

### Current functionality
FormHelper::input(), ::radio() and Paginator::sort() all use Inflector to generate strings for HTML output and pass this output to Gettext.

However, ExtractTask::_extractTokens() currently only calls ExtractTask::_parse() to process user-defined strings through the __?() functions and not those generated and passed to Gettext through its core helpers.  

### Proposed enhancement
Form::input(), Form::radio() and Paginator::sort() should be passed in as an array to the $functionName argument when calling ExtractTask::_parse() (similar to call_user_func() when passing a class method) and ExtractTask::_parse() statements added to ExtractTask::_extractTokens() to process these.

ExtractTask::_parse() should have a if() check for token of type T_OBJECT_OPERATOR and if the token being parsed matches the $functionName an additional if() check be performed for an array of options and if there is no match for a 'label' or 'legend' option pass the token string as $fieldName argument to a new protected ::_formatLabel() to split and humanize the token string (e.g. a Model.Field token string) before passing to ::_addTranslation()

FormHelper::label() currently performs similar functionality to the proposed ::_formatLabel() - it passes the strings it generates to Gettext but these strings are never extracted which this proposed enhancement will address.

### Enhancement as plugin
The proposed enhancement extends the core I18nShell and ExtractTask. Attached is a pluginized version that we use across all our projects / CakePHP apps. This alleviates the need to define a 'label' or 'legend' option on every FormHelper::input() or ::radio() just to pass the same string as the default inflected field name to __() when the core helpers already do this.

[I18n.zip](https://github.com/cakephp/cakephp/files/3234866/I18n.zip)

**Comment by markstory** [comment]
Thank you for sharing this. We're not adding any new features to 2.x at this point in time though. Have you considered publishing your changes as a plugin so that others could use it? Alternatively it could be adapted to 3.x and added into the existing `I18nShell` code.

**Comment by trenshaw** [comment]
Will publish plugin for 2.x and adapt to PSR-2 coding style for addition to existing `I18nShell` and `ExtractTask`. The proposed protected `ExtractTask::_formatLabel()` could potentially be factored into the existing `ExtractTask::_formatString()` but chose not to override as `::_formatString()`explicitly deals with formatting quoted strings and C style slashes.

**Comment by dereuromark** [comment]
I guess this has  no relevance for 3.x? Otherwise we need to reopen with a different milestone.

**Comment by trenshaw** [comment]
Hi Mark,

I apologise I haven't managed to commit this work; have been too tied up with other work and study commitments.

I think it's still very relevant. While FormHelper and PaginatorHelper use Inflector and Gettext to generate translatable labels / strings, those strings really do need to be extracted to the POT file.

I suspect this has gone unnoticed / been overlooked for as long as it has, as I18N does not get a lot of attention and is more often than not, low priority for most developers.

I should be able to get these changes committed within the next 2 weeks / beginning of July. You are also welcome to take my work and commit it on my behalf.

We heavily use / rely on the I18N shell in our CakePHP 2.x projects (which are not 3.x ready yet!). So if we could have also please have this in the 2.x branch (so our POTs are at least 3.x ready) that would be great!  

Regards,

Trent Renshaw > Systems Architect | Software Engineer 
Object Systems Technology 

p: 02 9002 5800 | d: 02 9002 5802 | m: 0411 038 749 | skype: trent_renshaw 
e: trent.renshaw@objectst.com.au | www.objectst.com.au 
Level 3, 100 Harris Street, Pyrmont NSW 2009 

----- Original Message -----
