### ISSUE TITLE
$query->bind() to array of strings/integers broken, or example code for $query->bind() incorrect

### ISSUE THREAD

**Issue by darxmac** [cakephp/cakephp#13307]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8

### What you did

When trying to use $query->bind() like the example in https://github.com/cakephp/cakephp/blob/master/src/Database/Query.php#L1968

```
->order(['FIELD(Table.field, :sortValues)'])
->bind(':sortValues', $options['ids'], 'integer[]');
```

### What happened

Following error was thrown:
`Unknown type "integer[]"`

![Screenshot 2019-05-31 at 16 27 43](https://user-images.githubusercontent.com/139267/58712530-06f29a00-83c1-11e9-8b51-837aa768f74b.png)

### What you expected to happen

Array of values bound to the `:sortValues` placeholder

**Comment by markstory** [comment]
The documentation block on `bindValue()` is incorrect.  List type expansion can only be done inside condition and comparison expressions.

**Comment by markstory** [comment]
I have a pull request up to fix the documentation. To do what you are trying to do I think you'd need to use a function expression

```php
$func = $query->func()->field(array_merge(
  ['Table.field' => 'identifier'],
  array_values($options['id'])
));
```
