### ISSUE TITLE
Completion command should ignore public methods for Shell

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#13313]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x.
* Platform and Target: PHP 7.2.13

### What you did
baked a shell and overwritten the methods runCommand  and getOptionParser
bin/cake completion subcommands hello_world

### What happened
The output contains runCommand and  getOptionParser

### What you expected to happen
Completion for shells should ignore all public methods defined at \Cake\Console\Shell. This is the relevant line https://github.com/cakephp/cakephp/blob/7dca886d7739779515fa3390d1e96da9ea046bea/src/Command/CompletionCommand.php#L205  at CompletionCommand.php

**Comment by markstory** [comment]
Pull request open now.
