### ISSUE TITLE
phpunit does not trigger Application::routes()

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#13317]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8
* Platform and Target: PHP 5.6.40 on Mageia Linux 6.1 (x64)

### What you did
in src/Application.php
```PHP
public function routes($routes)
{
	// Register scoped middleware for use in routes.php
	$routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
		'httpOnly' => true,
		'secure' => !Configure::read('debug'),
	]));
	parent::routes($routes);
}
```
in config/routes.php
```PHP
$routes->scope('/pl', ['language' => 'pl'], function (RouteBuilder $routes) {
    $routes->applyMiddleware('csrf');
   //some routes here
});
```

Then called from console:
`./vendor/bin/phpunit`
### What happened
Every test fails with following error:
```
RuntimeException: Cannot apply 'csrf' middleware or middleware group. Use registerMiddleware() to register middleware.
```

I have added xdebug_print_function_stack() to my routes.php to trace how this occurs.
Here is interesting part:
```
0.8846   11347576  15. Cake\TestSuite\MiddlewareDispatcher->resolveUrl(string(28)) ./vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:513
0.8846   11348000  16. Cake\Routing\Router::url(string(28), ???) ./vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:105
0.8846   11348096  17. Cake\Routing\Router::_loadRoutes() ./vendor/cakephp/cakephp/src/Routing/Router.php:662
0.8861   11714744  18. include('./config/routes.php') ./vendor/cakephp/cakephp/src/Routing/Router.php:1222
0.8861   11714792  19. xdebug_print_function_stack() ./config/routes.php:49
```

Looks like `routes.php` is included internally via `Router::_loadRoutes()` and `Application::routes()` is never called

Moving registerMiddleware call from `Application::routes()` method into `routes.php` file seem to fix problem for me

### What you expected to happen
Tests should use Application::routes()

**Comment by saeideng** [comment]
use like this
```php
    public function setUp()
    {
        parent::setUp();
        $this->useHttpServer(true); <-- add this line 
    }
```

**Comment by asgraf** [comment]
I have added `setUp()` method with `$this->useHttpServer(true);` to my TestCase class as you suggested, but this did not help in any way.
Exception `RuntimeException: Cannot apply 'csrf' middleware or middleware group. Use registerMiddleware() to register middleware` is still throwed and `Application::routes()` is still not being called

**Comment by asgraf** [comment]
I also just noticed that all my `Router::addUrlFilter()` filters in my `Application::bootstrap()` are also not called.

**Comment by markstory** [comment]
How can someone reproduce this problem? My applications get their bootstrap() and routes() hooks called when the test case enables `useHttpServer()`.

**Comment by othercorey** [comment]
@asgraf Can you provide more information on your application setup?

**Comment by ADmad** [comment]
Closing as the issue has gone stale and there hasn't been any follow up in a long time.

**Comment by othercorey** [comment]
@vladbanyai-spearline Can you help us reproduce it?

**Comment by othercorey** [comment]
Closing again due to no response.
