### ISSUE TITLE
[2.x] Model->save insert or update race condition

### ISSUE THREAD

**Issue by kirkcerny501** [cakephp/cakephp#13322]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.15
* Platform and Target: apache, PostgreSQL 9.5, cli command through cakeShell

### What you did
A database row that was deleted, magically reappears, and  usually with missing data.
Steps:
A row is inserted into a table using save.
The row is then attempted to be updated with save.
While the update is executing, delete the row.
CakePhp will decide the second save is an insert and not an update.

### What happened
View from the database.
#shell1> CREATE TABLE IF NOT EXISTS cake_race (uuid UUID PRIMARY KEY NOT NULL, name text, title text);
#shell1> INSERT INTO cake_race (uuid, name, title) VALUES ('5cf5870a-c8e8-4742-9180-22f67f000001', 'my_name', 'manager');
#shell2> DELETE FROM cake_race WHERE uuid = '5cf5870a-c8e8-4742-9180-22f67f000001';
#shell1> INSERT INTO cake_race (uuid, name) VALUES ('5cf5870a-c8e8-4742-9180-22f67f000001', 'my_name');

The last insert is not what I wanted.
I wanted an update statement.
UPDATE cake_race SET name = 'my_name' WHERE uuid = '5cf5870a-c8e8-4742-9180-22f67f000001';

### What you expected to happen
I expected cake to run an update sql statement.

**Comment by kirkcerny501** [comment]
[SaveUuidRaceShell.txt](https://github.com/cakephp/cakephp/files/3259252/SaveUuidRaceShell.txt)
[Model.txt](https://github.com/cakephp/cakephp/files/3259253/Model.txt)

I added a sleep call to the Model.php file to allow time for the race condition.

**Comment by kirkcerny501** [comment]
I cannot reproduce this issue in cakephp 3.x.
CakePhp 3.x throws a Cake\Datasource\Exception\RecordNotFoundException

**Comment by kirkcerny501** [comment]
#> php -q /gui/dsweb/Console/cake.php -working /gui/dsweb/Console -app /gui/dsweb save_uuid_race run_test -v

Wait 5 seconds, until it says
Run the delete code now.
scm save_uuid_race delete_row -v

Then from another window run
#> php -q /gui/dsweb/Console/cake.php -working /gui/dsweb/Console -app /gui/dsweb save_uuid_race delete_row -v

**Comment by markstory** [comment]
Sounds like you need to use transactions. In cake3 saving and updating have transactions applied by default. This is not true of Cake 2.

**Comment by markstory** [comment]
Sounds like you need to use transactions. In cake3 saving and updating have transactions applied by default. This is not true of Cake 2.

**Comment by kirkcerny501** [comment]
I thought I was using database transactions
The save call appears to be wrapped in a transaction
The code inside of the save function calls $db->begin(); and $db->commit();

// code from lib/Cake/Model/Model.php save function
$db = $this->getDataSource();
$transactionBegun = $db->begin();
try {
        $success = $this->_doSave($data, $options);
        if ($transactionBegun) {
                if ($success) {
                        $db->commit();
                } else {
                        $db->rollback();
                }
        }
        return $success;
} catch (Exception $e) {
        if ($transactionBegun) {
                $db->rollback();
        }
        throw $e;
}

------------------------------------------
Details from the PostgreSQL log.

-- The database connection with pid 14911 calls save to insert the row.
-- The save call is wrapped in a transaction.
2019-06-06 11:37:43 MDT [14911]: [23-1]  LOG:  duration: 0.022 ms  statement: BEGIN
2019-06-06 11:37:48 MDT [14911]: [32-1]  LOG:  duration: 0.030 ms  execute pdo_stmt_00000007: SELECT COUNT(*) AS "count" FROM "public"."cake_race" AS "CakeRace"   WHERE "CakeRace"."uuid" = '5cf5870a-c8e8-4742-9180-22f67f000001'
2019-06-06 11:37:48 MDT [14911]: [36-1]  LOG:  duration: 0.339 ms  execute pdo_stmt_00000008: INSERT INTO "public"."cake_race" ("uuid", "name", "title") VALUES ('5cf5870a-c8e8-4742-9180-22f67f000001', 'my_name', 'manager')
2019-06-06 11:37:48 MDT [14911]: [38-1]  LOG:  duration: 4.519 ms  statement: COMMIT

-- Connection with pid 14911 and 14935 both begin transactions
-- pid 14911 calls save to update the row, but an insert happens.
-- pid 14935 deletes the row wrapped in a transaction
-- When pid 14911 does a select to check for the existence of the row, the delete has already been committed.
-- The exist call does not find the row, and does an insert instead of an update
2019-06-06 11:37:48 MDT [14911]: [39-1]  LOG:  duration: 0.027 ms  statement: BEGIN
2019-06-06 11:37:50 MDT [14935]: [9-1]  LOG:  duration: 0.189 ms  statement: BEGIN
2019-06-06 11:37:50 MDT [14935]: [12-1]  LOG:  duration: 0.239 ms  execute pdo_stmt_00000003: SELECT COUNT(*) AS "count" FROM "public"."cake_race" AS "CakeRace"   WHERE "CakeRace"."uuid" = '5cf5870a-c8e8-4742-9180-22f67f000001'
2019-06-06 11:37:50 MDT [14935]: [16-1]  LOG:  duration: 0.223 ms  execute pdo_stmt_00000004: DELETE  FROM "public"."cake_race"  WHERE "uuid" = '5cf5870a-c8e8-4742-9180-22f67f000001'
2019-06-06 11:37:50 MDT [14935]: [18-1]  LOG:  duration: 4.883 ms  statement: COMMIT
2019-06-06 11:37:53 MDT [14911]: [42-1]  LOG:  duration: 0.076 ms  execute pdo_stmt_00000009: SELECT COUNT(*) AS "count" FROM "public"."cake_race" AS "CakeRace"   WHERE "CakeRace"."uuid" = '5cf5870a-c8e8-4742-9180-22f67f000001'
2019-06-06 11:37:53 MDT [14911]: [47-1]  LOG:  duration: 0.100 ms  execute pdo_stmt_0000000a: INSERT INTO "public"."cake_race" ("uuid", "name") VALUES ('5cf5870a-c8e8-4742-9180-22f67f000001', 'my_name')
2019-06-06 11:37:53 MDT [14911]: [49-1]  LOG:  duration: 78.083 ms  statement: COMMIT

**Comment by markstory** [comment]
Ok. Well if you figure out a solution you can open a pull request. I am happy to help with writing unit tests if you need a hand.

**Comment by othercorey** [comment]
@markstory I believe the user is saying that calling update() should fail when a row doesn't exist after being  deleted instead of inserting partial data.  I've never looked at cake 2 though.

**Comment by markstory** [comment]
Ok. I don't use 2.x anymore either and outside of security fixes I don't have the energy to try and fix issues like this. For the last couple of years the core team has been relying on folks who use 2.x to support it.

**Comment by othercorey** [comment]
If it helps, it looks like this is where the id is unset causing the insert.  You could change this to always attempt insert if the id is set or fail the save instead of inserting.

https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Model.php#L1906
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Model.php#L1923

**Comment by kirkcerny501** [comment]
> Ok. I don't use 2.x anymore either and outside of security fixes I don't
have the energy to try and fix issues like this.
> For the last couple of years the core team has been relying on folks who
use 2.x to support it.

Thanks, I appreciate your help.
I understand that I am on an old version.
I was happy to see that I could not reproduce the issue in 3.x
After working on Microsoft products, I actually welcome actually being able
to look at the source code,
and I like that you would even consider code changes from the community.

I am loving open source software.
If I don't like it, I can always fix it myself, or get my money back.

**Comment by dereuromark** [comment]
Closing then as 2.x goes into maintenance mode.
