### ISSUE TITLE
Form Helper, Randomly Builds TextAreas instead of TextBoxes

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#13336]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.13
* Platform and Target: MySQL, Apache, PHP 7.2

### What you did
https://i.imgur.com/oFOaiYv.png

As you can see, the textbox on the left is a textarea, but i have not specified a textarea... what is confusing to me, is the textbox right above it, is designed the same way, but is a normal textbox, not a textarea...

### What happened
https://i.imgur.com/oFOaiYv.png

### What you expected to happen
https://i.imgur.com/yA1K7dE.png

I would expect both textboxes on the left to be textboxes, not one textbox and one textarea

**Comment by dakota** [comment]
What is your field types in the database? The FormHelper infers field type based on your database schema (`varchar` being a text box, and `text` being a text area)

**Comment by jeffreyroberts** [comment]
ahhh that makes sense =]

**Comment by jeffreyroberts** [comment]
Hey Guys, so, yesterday, I had two textarea fields as inputs on a form, both of those inputs were single line inputs, i infact had to add "type" => "textarea" to one of them to get it to become a multi-line input, after a refresh the one input with the type set, was a multi-line and the other was a single line, exactly how I wanted, a couple of refreshes later, the single line suddenly turned into a multi-line...

I will continue my research into this issue, just a heads up

**Comment by markstory** [comment]
@jeffreyroberts we will need a way to reproduce the problem you're seeing.

**Comment by jeffreyroberts** [comment]
@markstory Absolutely, Im not sure how im going to do that just yet, but I will be attempting to get you something reproducible as soon as possible, Im not sure if Im going to be able to reproduce it outside of this project, Im thinking I might start with a screen capture, just so you guys know im not crazy =] =]
