### ISSUE TITLE
Post/Redirect/Get pattern

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#13333]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0
I would like to propose a new very useful feature. I think everybody here know what Post/Redirect/Get pattern is and why use it should be a best practices.
Why cakephp doesn't implement Post/Redirect/Get patter out of the box?

probably it can be simply implememented with a middleware, and some dedicated controller method for setting which variables persist across redirect.

What do you think about it?

**Comment by dereuromark** [comment]
Prg is used everywhere usually. See baked actions.

**Comment by doshu** [comment]
At this moment PRG is used only after a succesfully executed POST action. In case of errors during the save operation the view is immediatly rendered. This behaviour cause the POST will be resend in the case of page refresh and cause a page cache miss error in the case of the user go back through the history

the controller action shoud redirect to itself before render the view. 
In case of doubt see how laravel framework implement it

**Comment by dereuromark** [comment]
What you describe violates the PRG pattern. It specifically states (see wikipedia) that only successful ones are allowed to be redirected.
CakePHP adheres to this 100% as the forms - if invalid - are keeping the post data until successfully redirecting, making it possible to go back for a good reason here in case of failure.
This is also basically how PHP forms are designed to work in general.

If you claim that other frameworks do that differently, you will have to consult with them on the specifics, but CakePHP implements PRG correctly here.

For further discission please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Closing as follow up goes more into support question than rfc.
Thanks!
