### ISSUE TITLE
Non-static method 'addPlugin' should not be called statically

### ISSUE THREAD

**Issue by nnahito** [cakephp/cakephp#13340]
My English is poor, but I appreciate your kindness. 

---

This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8
* Platform and Target: When I write codes in IntelliJ IDEA

### What you did
I want to upgrade CakePHP3.6 to CakePHP3.7.

### What happened
In document says "`Cake\Core\Plugin::load() and loadAll() are deprecated. Instead you should use Application::addPlugin().`".
So I rewrite `Cake\Core\Plugin::load()` to `Application::addPlugin()`.

However, [IntelliJ IDEA](https://www.jetbrains.com/idea/)(IDE) says `Non-static method 'addPlugin' should not be called statically`.
It is written`public function addPlugin` in `vendor/cakephp/cakephp/src/Http/BaseApplication.php`.

### What you expected to happen
I could upgrade no matter.

**Comment by ADmad** [comment]
You are supposed to use `$this->addPlugin()` in `bootstrap()` method of `src/Application.php` class.

Check the latest default skeleton.

**Comment by jeremyharris** [comment]
In documentation (and docblocks) we reference all methods in classes in this format, `Application::addPlugin`, even though it's not a static method. It can be confusing, but visiting the API documentation will indicate if it is static or not 🙂

**Comment by nnahito** [comment]
I see! Thank you!
