### ISSUE TITLE
Let Cake\Database\Type::buildAll also return types added with Type::set

### ISSUE THREAD

**Issue by nickygerritsen** [cakephp/cakephp#13358]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.7.5
* Platform and Target: not relevant for this issue

### What you did
I register a type with
```php
Type::set('somename', $someInstance);
```

Note that I can't use `Type::map` because I want an *instance*, because I have things configured on it that are needed when converting data to/from the database.

### What happened
My fields are not correctly converted from the database to PHP and vice versa.

### What you expected to happen
I would expect that my data would get correctly converted using the type.

### Further info
After some debugging and digging, I found out that if I change `Type::buildAll()` to return `static::$_builtTypes` instead of `$result` all works well, because any types that are set using `Type::set` will then be returned.
I am not sure if this is indeed the best fix, but it seems logical to me. Either that or `Type::set` should be changed/removed.

p.s. the documentation of `Type::set` also seems confusing to me.

**Comment by ADmad** [comment]
Please provide a way to reproduce the problem you are having.

**Comment by nickygerritsen** [comment]
```
<?php

use Cake\Database\Type\DateTimeType as CakeDateTimeType;
class DateTimeType extends CakeDateTimeType
{
    /**
     * @inheritDoc
     */
    public function getBaseType()
    {
        return 'timestamp';
    }
}

$name = 'test';
$type = new DateTimeType($name);
Cake\Database\Type::set($type, $name);

// Now:

class DemoTable extends Cake\ORM\Table {
    protected function _initializeSchema(TableSchema $schema)
    {
        $schema->setColumnType('field', 'test');
    }
}
```

Now if you load a row from the database from this table, the `field` field will *not* be cast to a date time.

p.s.

I know that in this example the custom type does not make a lot of sense, but we have types that are more complex. However, they are not needed for the example, so I thought to make it more simple.

**Comment by markstory** [comment]
I think `Type::set()` also needs to update the `static::$_types` array when a custom type is added. The `_types` property is used to iterate type objects in a few places.
