### ISSUE TITLE
Update use of deprecated / internal phpunit classes

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13350]
- [x] `FixtureInjector` implements `PHPUnit\Framework\TestListener` which has been deprecated as of phpunit 8. The alternative is to use [Hook Interfaces](https://phpunit.readthedocs.io/en/8.3/extending-phpunit.html#extending-the-testrunner).

- [ ] `PHPUnit\Framework\TestSuite` extended by `Cake\TestSuite\Testsuite` is marked as internal.

- [ ] `PHPUnit\Framework\AssertionFailedError` used in various constraint classes is marked as internal.

**Comment by ADmad** [comment]
A noteworthy difference is the hook interface methods seem have only the testcase classname as argument as opposed to the testcase instance in listener methods.

**Comment by markstory** [comment]
If we only get the class name will we have enough context to read the fixture names? We could run into problems if user land tests define `$fixtures` in the constructor.

**Comment by ADmad** [comment]
Yes that's a concern. I am not sure how easy/difficult the change would be.

Personally I am not too keen digging into this right away. When I noticed the deprecation I presume switching to hooks would be simple enough.

**Comment by othercorey** [comment]
I think we need https://github.com/sebastianbergmann/phpunit/issues/3795 implemented to move away from inherited TestSuite.

This would let us bootstrap the database suite with different configurations as unique test suites for filtering too.

**Comment by dereuromark** [comment]
Should this be moved to 5.x milestone?

**Comment by othercorey** [comment]
I removed the use of TestSuite from our internal tests. Now we run phpunit twice.

https://github.com/cakephp/cakephp/pull/15844

I don't know if we should deprecate/remove TestSuite.

**Comment by dereuromark** [comment]
If it is just about internal, I wouldn't go that way.
The main issue is the deprecation usage IMO.

**Comment by othercorey** [comment]
I looked into the use of AssertionFailedError. These could really just throw another exception to fail the test since they are configuration errors.

The use of `$this->fail()` doesn't really work as a replacement.

**Comment by othercorey** [comment]
Closing this. Think we have to wait to see what PHPUnit 10 provides us.

The use of TestSuite was removed.
