### ISSUE TITLE
isInteger() validation returns true when provided with boolean value "true"

### ISSUE THREAD

**Issue by georgeconstantinou** [cakephp/cakephp#13351]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8
* Platform and Target: PHP's build-in webserver.

### What you did
```php
<?php
use Cake\Validation\Validation;

$value = true;
$result = Validation::isInteger($value);
```
### What happened
`$result` is **true**.

### What you expected to happen
`$result` should be **false**.

**Comment by saeideng** [comment]
PR open.
