### ISSUE TITLE
[2.x] Call to a member function header() on null

### ISSUE THREAD

**Issue by ShuiPingYang** [cakephp/cakephp#13361]
cakephp  version : 2.0.5
php version : 7.0.25
I am maintaining an old project ,It was written in cakephp 2.0.5 ,when I use redirect() in controller，it came up an error :
```
Call to a member function header() on null
```
the code : 

![image](https://user-images.githubusercontent.com/22534808/59745102-a3180e80-92a6-11e9-923f-be182cbf31fc.png)

upload_attachment function ：
![image](https://user-images.githubusercontent.com/22534808/59745132-b3c88480-92a6-11e9-9f8b-78c98b350545.png)

I wonder if this is a bug ?
I came to the Controller@redirect ,and var_dump($this->response) ,I get null .

**Comment by markstory** [comment]
This version of CakePHP is not supported. If $this->response is null in your controller ensure that your controller constructor is correct, and that the action doesn't accidentally null out the response property.

**Comment by ShuiPingYang** [comment]
@markstory I am sure my controller constructor is correc . that's to say cakephp version 2.0.5 do not support use redirect iacross different controller ,right ? I think whenever I use redirect ,it should just redirct and no matter how deep the function in the other controller . in this case ,which would be the better solution ? I use upload_attachment function in many controller .

**Comment by saeideng** [comment]
>I think whenever I use redirect ,it should just redirct and no matter how deep the function in the other controller . in this case ,which would be the better solution ?

better solution  is use `redirect()` just in  main action
you can use it in indirect method/action but needs `return` again in main action
```php
public function edit(){
  //your code
  $result = $this->anotherAction(....);
  if($result instance of response){
    return $result; 
  }
  //other code
}
public function anotherAction(){
  //your code
  if (..... ){
    return $this->redirect('/toASampleAction');
  }
  //other code
}
```

join to one of help forum to receive more help/info

-------
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by ShuiPingYang** [comment]
@saeideng thank you very much , your suggestion helps me a lot.
