### ISSUE TITLE
$this->render does not work when a request is ajax

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#13367]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: Apache2, MariaDB (Mysql community 5.7+)

### What you did
```
if($this->request->is('ajax')) {
            $this->viewBuilder()->setLayout(false);
// code stuff
            if($series->count() < 1) {
                return $this->response->withStringBody("Sorry. We couldn't find it.");
            }
            $this->set(compact('series'));
            if($this->request->isMobile()) {
                $this->render('m/ajaxseries');
            } else {
                $this->render('ajaxseries');
            }

// Action's name is series

```

### What happened

It said - Confirm if you have created a file in <controller>/ajax/m/series.ctp and threw a 500 :(

### What you expected to happen

`It should pick up <controller>/m/ajaxseries.ctp`

**Comment by markstory** [comment]
Are you certain that your request is getting through the `isMobile()` check? What happens if you remove all the conditional logic and simply call `$this->render('m/ajaxseries')` in your controller action?

**Comment by karmicdice** [comment]
Are you certain that your request is getting through the isMobile() check?
Yes, it is. Checked via Inspect of Chrome and a real device. I performed an exit with an echo, and displaying ajax output on screen. It showed.


What happens if you remove all the conditional logic and simply call $this->render('m/ajaxseries') in your controller action?

Let me try.

**Comment by karmicdice** [comment]
What happens if you remove all the conditional logic and simply call $this->render('m/ajaxseries') in your controller action?

It goes to `Template/<controller>/ajax/m/series.ctp`. Removing conditional logic didn't work.


Here is a full action...


```php
public function series()
    {
        $seriesTable = TableRegistry::get('Series');
        $mobile = false;
        if($this->request->isMobile()) {
            $mobile = true;
        }
        if($this->request->is('ajax')) {
            $this->viewBuilder()->setLayout(false);
            $where = array();
            $lang = $this->request->getQuery('lang');
            $genre = $this->request->getQuery('genre');
            $prov = $this->request->getQuery('provider');
            if(!is_null($prov) && $prov != '') {
                $provIds = explode(',', $prov);
                $mpt = TableRegistry::get('ProvidersSeries');
                $mpids = $mpt->find()->where(['provider_id IN' => $provIds]);
                if($mpids->count() < 1) {
                    return $this->response->withStringBody('false');
                }
                $seriesToFilter = array();
                foreach($mpids as $mpx) {
                    $seriesToFilter[] = $mpx->series_id;
                }
                if(count($seriesToFilter) < 1) {
                    return $this->response->withStringBody('false');
                }
                $where['id IN'] = $seriesToFilter;
            }
            if(!is_null($lang) && $lang != '') {
                $lang = explode(',', $lang);
                $where['language_id IN'] = $lang;
            }
            if(!is_null($genre) && $genre != '') {
                $genre = explode(',', $genre);
                $where['genre_id IN'] = $genre;
            }
            if($lang == '' && $genre == '') {
                $where[1] = 1;
            }
            $series = $seriesTable->find()->where($where)->order(['id' => 'DESC']);
            $series = $this->paginate($series);
            if($series->count() < 1) {
                return $this->response->withStringBody('false');
            }
            $this->set(compact('series'));
           $this->render('m/ajaxseries'); // Edit to check if removing conditional logic does anything
            /* if($mobile) {
                 $this->render('m/ajaxseries');
             } else {
                 $this->render('ajaxseries');
             } */
        }
        $languages = TableRegistry::get('Languages');
        $this->set('languages', $languages->find('all'));
        $genresTable = TableRegistry::get('Genres');
        $this->set('genres', $genresTable->find());
        $providersTable = TableRegistry::get('Providers');
        $this->set('providers', $providersTable->find());
        if(!is_null($this->Auth->user('id'))) {
            $userId = $this->Auth->user('id');
            $userlang = TableRegistry::get('LanguageUsers');
            $this->set('userlangs', $userlang->find()->where(['user_id' => $userId]));
            $genrlang = TableRegistry::get('GenreUsers');
            $this->set('usergenrs', $genrlang->find()->where(['user_id' => $userId]));
            $userprov = TableRegistry::get('ProvidersUsers');
            $this->set('userprovs', $userprov->find()->where(['user_id' => $userId]));
        }
        $this->set('series', $this->paginate($seriesTable->find()->order(['id' => 'DESC'])));
        if($mobile) {
            $this->render('m/'.$this->request->getParam('action'));
        }
    }

```

**Comment by karmicdice** [comment]
Just created a boilderplate to see if issue persists. Yes, it does.

Performed a fresh create-project and added below to replicate:

[https://github.com/karmicdice/cakestuff/blob/master/src/Controller/PagesController.php#L44:L50](https://github.com/karmicdice/cakestuff/blob/master/src/Controller/PagesController.php#L44:L50)

**Comment by garas** [comment]
You need to `return $this->render(...);`.

Problem with you code could be that it didn't `return` in `if ajax`, and then code continued to end of method and it called `$this->render('m/'.$this->request->getParam('action'));` which is same as `$this->render('m/series');`

**Comment by karmicdice** [comment]
> You need to `return $this->render(...);`.
> 
> Problem with you code could be that it didn't `return` in `if ajax`, and then code continued to end of method and it called `$this->render('m/'.$this->request->getParam('action'));` which is same as `$this->render('m/series');`

Interesting. It worked. However, when a return is not supplied - it does go till the end but, here it still requires me to create a folder named 'ajax'.

**Comment by markstory** [comment]
If you don't `return $this->render()` the controller action continues to the end and then renders the default view which would match the action name. Given that this was a missed `return` I'm going to close this.
