### ISSUE TITLE
Cake\Database\Query::join() depreciation message is misleading

### ISSUE THREAD

**Issue by madbbb** [cakephp/cakephp#13373]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.9

### What you did
I had $query-> join() in my code

### What happened
I got deprecation message:

> Using Query::join() to read state is deprecated. Use **clause("join")** instead.

I was confused with word clause without class.

### What you expected to happen
I think this message will be better:

> Using Query::join() to read state is deprecated. Use **Query::clause("join")** instead.

**Comment by dereuromark** [comment]
Can you make a PR please?

**Comment by madbbb** [comment]
@dereuromark here you go

**Comment by ADmad** [comment]
@madbbb You just made a commit on your fork, you need to open a pull request do that it can be merged :).

**Comment by madbbb** [comment]
@ADmad sorry, I never worked with issues here before and was confused with automatic issue attachment in our conversation.
