### ISSUE TITLE
Validation::alphaNumeric() allows non-alphanumeric characters

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#13376]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Non-related

### What you did
```php
debug( Validation::alphaNumeric('日本語') );
```

### What happened
`true`

### What you expected to happen
`false`

Though I think it's a well-known feature,
https://github.com/cakephp/cakephp/blob/e39e85e3fc441e60bfe8f71d7a30794e9f053481/tests/TestCase/Validation/ValidationTest.php#L121-L125
it would be nice if it could be changed in 4.0. Since `containsNonAlphaNumeric()` assumes `[a-zA-Z0-9]` as alphanumeric, I think we can apply the same rule to `alphaNumeric()`.

**Comment by markstory** [comment]
Having `alphaNumeric()` and `containsNonAlphaNumeric()` operate on the same character classes would be ideal. If we exclude non-latin characters how would folks validate that their inputs only had word characters/numbers?

**Comment by chinpei215** [comment]
It would be depending on the country. At least in Japan, any people wouldn't expect that `alphaNumeric()` returns true against our word characters such as hiragana (e.g. にほんご), katakana (e.g. ニホンゴ), and kanji (e.g. 日本語). And they would use custom validation rules such as isHIrgana, isKatakana, and isKanji. I don't think it should be the part of the core library though.

As another option, we could use the `[[:alnum:]]` pre-defined character class of PCRE instead. By default, the `u` modifier should not be used, and it can be used optionally. Though `/[[:alnum:]]/u` also returns `1` against `日本語`, I don't mind it as long as it is not a default behavior.

@ADmad or @saeideng might have another opinion though. I think they are using yet another word characters in their language. Also umlaut characters in German should be considered.

**Comment by ADmad** [comment]
I too would expect the method to return true for English alphabet and digits only. IIRC that's how it worked before but it was changed because people wanted it to include latin chars too for other European languages.

**Comment by ravage84** [comment]
The current regex means:

https://github.com/cakephp/cakephp/blob/master/src/Validation/Validation.php#L147

![grafik](https://user-images.githubusercontent.com/625761/60197707-31a90480-9840-11e9-8f18-7870a534d7fa.png)

(Output by [RegExBuddy](https://www.regexbuddy.com/))

The Cookbook for 3.x doesn't say anything about alphanumeric:

https://www.google.ch/search?ei=Y5wTXfa1MeT4qwGwiaDYBw&q=site%3Ahttps%3A%2F%2Fbook.cakephp.org%2F3.0+%22alphanumeric%22&oq=site%3Ahttps%3A%2F%2Fbook.cakephp.org%2F3.0+%22alphanumeric%22&gs_l=psy-ab.3...1046.1853..2019...0.0..0.86.163.2......0....1..gws-wiz.bkORQoSj_8I

The Cookbook for 2.x does, however:

https://book.cakephp.org/2.0/en/models/data-validation.html

```` php
        'loginRule-1' => array(
            'rule' => 'alphaNumeric',
            'message' => 'Only alphabets and numbers allowed',
         ),
````

I think there are at least two sides to this:

1. **Our understanding** of "alpha numeric"
2. The **user expectation** of what an  "alpha numeric" validator

Wikipedia is kind of contradictive on the subject

While it explains "alphanumeric" as the following

> Alphanumeric is a combination of alphabetic and numeric characters, and is used to describe the collection of **Latin letters and Arabic digits** or a text constructed from this collection. 

https://en.wikipedia.org/wiki/Alphanumeric

It describes "alphabetic"/"alphabet" as

> An alphabet is a standard set of letters (basic written symbols or graphemes) that represent the phonemes (basic significant sounds) of **any spoken language** it is used to write. 

https://en.wikipedia.org/wiki/Alphabet

**Comment by dereuromark** [comment]
Totally agree. Alphanumeric always means any number or alphabet character (A-Z + local additions per language).

**Comment by ravage84** [comment]
I guess if somebody wants to use a restrictive validation, finds ``Validation::alphaNumeric()``, s/he might assume it is what s/she is looking for.
At the same time, if somebody wants to validate "typical" (the ones s/he is used to) letters and digits, s/he might think, too, s/he found the right one in ``Validation::alphaNumeric()`.

**Comment by ravage84** [comment]
> [...]  local additions per language).

I think there in lies a powerful assumption in most of us. :grin:

**Comment by othercorey** [comment]
Just some food for thought.  Python defines alpha as:

>Return true if all characters in the string are alphabetic and there is at least one character, false otherwise. Alphabetic characters are those characters defined in the Unicode character database as “Letter”, i.e., those with general category property being one of “Lm”, “Lt”, “Lu”, “Ll”, or “Lo”. Note that this is different from the “Alphabetic” property defined in the Unicode Standard.

https://docs.python.org/3/library/stdtypes.html#str.isalpha

**Comment by ADmad** [comment]
@othercorey That's pretty much what the current regex `'/^[\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}]+$/Du'` includes along with digits.

**Comment by othercorey** [comment]
@ADmad It seems like alphaNumeric is working and constainsNonAlphaNumeric is broken.  You could easily add asciiAlphaNumeric and constainsNonAsciiAlphaNumeric.  Just an observers opinion though.

I would suggest making a parameter instead of more copies of similar functions, but since there are existing default parameters, that would make things awkward.

**Comment by ADmad** [comment]
@othercorey Well @chinpei215's issue is with `alphaNumeric()` as he expects `Validation::alphaNumeric('日本語')` to return `false` not `true`.

**Comment by othercorey** [comment]
Well, unless you want to build validators based on the current locale set (which doesn't sound reasonable), seems like he just needs a new feature added to validate ascii alpha-numeric values.  

Instead of being based on locale, you could have a setting that flips whether alphaNumeric includes unicode characters by default.  If an application handles unicode user-input, it sets that to 'allow unicode', otherwise it set it to 'allow ascii only'.  I'll leave it at that in case this isn't helping.

**Comment by ADmad** [comment]
My only concern is the disparity between `alphaNumeric()` and `containsNonAlphaNumeric()` using different sets of characters as "alpha".

**Comment by othercorey** [comment]
@ADmad I would have the config setting affect both validators.

**Comment by dereuromark** [comment]
we can make a new one ascii() and nonAscii() on top. This way we have both
but the negative one should match the positive one as counter part.

**Comment by chinpei215** [comment]
Thank you for a lot of comments. Adding asciiAlphaNumeric() would be not bad. A problem of inconsistency between alphaNumeric() and containsNonAlphaNumeric() would be still remain though.

I am curious about what people use the `alphaNumeric()` for. It is easy to come up with use cases of `asciiAlphaNumeric()`.

**Comment by ravage84** [comment]
:+1: for ``asciiAlphaNumeric()`` and ``containsNonAsciiAlphaNumeric()``.

> I am curious about what people use the alphaNumeric() for. It is easy to come up with use cases of asciiAlphaNumeric().

To be honest, I though it would be easy to come up with an example, but two minutes later I still haven't found any.

**Comment by dereuromark** [comment]
You could also use "strict" as suffix/prefix, instead of ascii.But I think ascii is more clear on the difference between the human alphabet and ascii alphabet.

**Comment by saeideng** [comment]
>I am curious about what people use the alphaNumeric() for. It is easy to come up with use cases of asciiAlphaNumeric().

I just found how it works after test
I tested it ,looks works fine with most cases (and expected ) and I think it returns `false` when we use vowels in content ( not fully test )
vowels are optional in some language (to emphasize the correct pronunciation )
and use most time in other language 
vowel `َ`  in word : 
```php
Validation::alphaNumeric('سلام');//true
Validation::alphaNumeric('سَلام');//false
```
vowel in `سَلام` is not usual
but another vowel in another language is 
```
Validation::alphaNumeric('أيضاً');//false
```

**Comment by othercorey** [comment]
@chinpei215 You could use it to validate the title of something along with punctuation/etc.  A lot of sites these days let you put anything unicode, but you could validate a display name as well.

**Comment by chinpei215** [comment]
@othercorey I wouldn't use `alphaNumeric()` for the purpose as it returns `false` against [究極超人あ〜る](https://en.wikipedia.org/wiki/Ky%C5%ABkyoku_Ch%C5%8Djin_R) for example, and there isn't any good reason for me to reject those inputs. But thank you anyway.

**Comment by ADmad** [comment]
@chinpei52 Japanese characters / kanji is pretty different from what are considered as "alphabets" in Latin based and other languages. So that might be the reason of its limited usefulness to you.

**Comment by ravage84** [comment]
I totally agree with @ADmad 

Would it may be make sense if we reduce the allowed characters?
I'm aware that would trip some applications that currently use the validation, but at its current state I highly doubt its usefulness.
I believe,  most developers aren't aware of the vast character sets this method currently allows.

**Comment by othercorey** [comment]
@chinpei215 I think the issue is this validation and regex does not include punctuation marks as in your example of the wave dash/full tilde.

**Comment by chinpei215** [comment]
> I think the issue is this validation and regex does not include punctuation marks as in your example of the wave dash/full tilde.

Yes, but since my expectation is `false` in any case if a Japanese character is contained, I don't think it is an "issue" though.
As another example, since the current regex doesn't contain `\p{Nl}`, it doesn't allow Kan-suji (Chinese numeral) zero [〇](https://en.wiktionary.org/wiki/〇), Hence it returns false against (一九〇五)[https://en.wikipedia.org/wiki/1905_(film)] for example. If we really want to allow unicode letters, then `/^[[:alnum:]]+$/Du` would be better than the current regex.

> I believe, most developers aren't aware of the vast character sets this method currently allows.

I believe so too. That is why I opened this pull request. But if someone is using the `alphaNumeric()` to allow unicode letters, then I don't want to change it. Adding the `asciiAlphaNumeric()` would be better.
To let people misuse the `alphaNumeric()`, it would be nice if there is a side note in the docblock of the `alphaNumeric()` and our Cookbook.

**Comment by othercorey** [comment]
Perhaps it's easier to just say alphaNumeric is broken in 3.0 and make it/add ascii-only in 4.0.  Then, you could accept feature requests for other validators.  I would bet Python has the same disappointing results.

https://www.regular-expressions.info/unicode.html

This page gives a nice explanation of how to capture those combining marks that I think would capture the Arabic example earlier.  You could consider a feature request adding this and punctuation marks.

**Comment by ADmad** [comment]
Making `containsNonAlphaNumeric()` use the same character set as `alphaNumeric()` and adding new methods `asciiAlphaNumeric()` and `containsNonAsciiAlphaNumeric()` (perhaps shorten to just `nonAsciiAlphaNumeric()`) seems like a reasonable resolution.

**Comment by chinpei215** [comment]
I agree with @ADmad . `notAsciiNumeric()`/`notAsciiAlphaNumeric()` seems better name to me for consistency with `notBlank()`. 

Referring to other languages, in Java,  [StringUtils::isAlphanumeric](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isAlphanumeric-java.lang.CharSequence-) of Apache Commons also seems to allow unicode letters. So the current behavior of our `alphaNumeric()` would be not so weird.

**Comment by ADmad** [comment]
So to summarize:
- `alphaNumeric()` Keep as it is (Or update to include chars pointed out in https://github.com/cakephp/cakephp/issues/13376#issuecomment-506927194)
- `containsNonAlphaNumeric()` Keep as it is and mark as deprecated for removal in 5.0.
- `notAlphaNumeric()` Add with same alphababet set as `alphaNumeric()`.
- `asciiAlphaNumeric()` Add to only allow `[[:alnum:]]`.
- `notAsciiAlphaNumeric()` Add to not allow only `[[:alnum:]]`.

**Comment by dereuromark** [comment]
Someone wants to make a PR here now?

**Comment by markstory** [comment]
I can do this.

**Comment by davidyell** [comment]
Perhaps an addition to the localized plugin validation class would be helpful? 
https://github.com/cakephp/localized/blob/master/src/Validation/JpValidation.php

**Comment by dereuromark** [comment]
Localized plugin can be updated as well.
