### ISSUE TITLE
unable to change applicationClassName

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#13371]
cake version : 3.x and 4.x
unable to change applicationClassName

https://github.com/cakephp/cakephp/blob/9bead284a3e148bd1bde2f77f17d25b3f899ae7e/src/TestSuite/ConsoleIntegrationTestTrait.php#L245

suggest: 
adding a method similar to  `IntegrationTestTrait::configApplication()`
https://github.com/cakephp/cakephp/blob/9bead284a3e148bd1bde2f77f17d25b3f899ae7e/src/TestSuite/IntegrationTestTrait.php#L255-L259

**Comment by markstory** [comment]
Having the same interface/method as IntegrationTestTrait would :+1:

**Comment by saeideng** [comment]
done https://github.com/cakephp/cakephp/pull/13384
