### ISSUE TITLE
eanble the intl extension to use CakePHP

### ISSUE THREAD

**Issue by DinhQuocNhat** [cakephp/cakephp#13378]
Fatal error: You must enable the intl extension to use CakePHP. in C:\xampp\htdocs\cakephp-3-7-2\config\requirements.php on line 31

**Comment by dereuromark** [comment]
Please follow the docs and the clear description in this error message.
The intl extension is required. 

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
