### ISSUE TITLE
notEmptyString() missing from Validator

### ISSUE THREAD

**Issue by bugezzy** [cakephp/cakephp#13388]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: Nginx, Mariadb 10.1, Ubuntu 18

### What you did
I baked the code using bin/cake bake all [table name]

### What happened
The default table class is generated with validator methods notEmptyStirng() functions for database fields as: `first_name` VARCHAR(90) NOT NULL DEFAULT

Example:
$validator
            ->scalar('first_name')
            ->maxLength('first_name', 90)
            ->notEmptyString('first_name');

Seems to be based upon this code:
vendor/cakephp/bake/src/Shell/Task/ModelTask.php
line 806: getEmptyMethod
returns 'notEmptyString'

This function 'notEmptyString' does not exists in: vendor/cakephp/cakephp/src/Validation/Validator.php

### What you expected to happen
The bake task should return:

$validator
            ->scalar('first_name')
            ->maxLength('first_name', 90)
            ->allowEmptyString('first_name', false);

**Comment by saeideng** [comment]
`notEmptyString()` added since cake 3.8.0
which  version of `bake` you are using  ?

**Comment by bugezzy** [comment]
Yes, this is 3.7 - fresh install on a new server

**Comment by saeideng** [comment]
latest version of cake is 3.8 and bake <1.10 work with it 
new tag will release very soon for work with cake 3.8

**Comment by saeideng** [comment]
bake 1.10.1 released you can use it with cake 3.7.x
