### ISSUE TITLE
Empty property when matching() and contain() on the same alias

### ISSUE THREAD

**Issue by k-risc** [cakephp/cakephp#13389]
This is a (multiple allowed):

* [x] bug (or a feature)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.5
* Platform and Target: Apache/MariaDB.

### What you did
My question is very similar to #5463, but what seems to be resolved there still causes some issues in our current project. This is about three tables in the database: assets, entities, payables.

The relations are:
* payables belongsTo asset
* payables belongsTo entity
* entity hasMany assets
* assets belongsTo entity

AssetsTable has a `beforeFind()` that under certain circumstances amends the query by adding a matching() clause for "Entity". 

I then do a query on payables containing ["Assets", "Entity", "Entity.Assets"].

### What happened
In the resulting payables, although they have an entity_id, the data for the entity is not contained, it is only present under _matchingData.

### What you expected to happen
The entity data also being contain in the result set, not only to have it in _matchingData.

The issue does *not* occur if we do a query on payables containing only ["Entity", "Entity.Assets"]. It seems that the first level association from payables to assets, and then the matching() executed on the assets, causes the alias "Entity" to be changed in a way that CakePHP only stores the entity data in _matchingData.

**Comment by markstory** [comment]
Could you provide a sample schema and find() call that would help someone reproduce your issue? These kinds of issues can take a long time to reproduce and are likely to not ever be looked into without that information.

**Comment by othercorey** [comment]
@k-risc Can you provide a sample query?

**Comment by k-risc** [comment]
Thanks for the patience, this is much appreciated.

I created a small CakePHP 4.0 app, with one new controller and three table classes, as well as a migrations file for creating the database tables and some test data. How can I hand this over to you. Should I attach a compressed file containing the "src" and "Migrations" folder here? Or is it something even simpler you would need?

Please find a screenshot showing some debugging results of both ways (with and without matching)
![matching-plus-contain](https://user-images.githubusercontent.com/1674868/70989885-baed1580-20c4-11ea-98e4-95dd3a2d3e40.png)

**Comment by markstory** [comment]
@krisc you could publish the sample application as a repository.

**Comment by k-risc** [comment]
Ok, you should have received an invite to https://github.com/k-risc/matching-test

**Comment by othercorey** [comment]
@k-risc I received it, thank you.  We will need a little time, but we will take a look!

**Comment by markstory** [comment]
I took a look at your application, is it setup to trigger the error or the expected case? I'm currently seeing a list of assets and no matching data. What else needs to be done to make the issue visible?

**Comment by k-risc** [comment]
It is currently not showing the error. If you edit the `AssetsTable->beforeFind()` and remove the if statement and its body, so that `$query->find('Filter');` is executed even if the query is not the primary one, then the error should show. `AssetsTable->findFilter()` puts a `matching()` on the query, and that seems to trigger the behaviour which I think is unexpected.

**Comment by markstory** [comment]
The reason that your query is incorrect is that you are using `beforeFind()` to attach the `matching()` condition. The ORM calls `beforeFind()` on all participating tables which includes 'Assets' due to it being included in the contain() on the payables table. The beforeFind on AssetsTable then replaces the previously defined contain() for both `Entity` and `Entity.Assets` as the alias is the same as the new matching() condition being added in the beforeFind.

Unfortunately because all your association aliases are shared the ORM can't sort out how to handle the matching + contain conditions better. You should consider another way to create your query, or try changing your aliases so they aren't the shared between different models.
