### ISSUE TITLE
Hash::sort()'s $dir accepts SORT_DIR/SORT_ASC ?

### ISSUE THREAD

**Issue by o0h** [cakephp/cakephp#13392]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: CakePHP 2/3

### What you did
I feel Hash::sort() is similar to `Collection::sortBy()`.
But `$dir` param is '(str)asc|desc' in Hash method, against Collection method accept `(int)SORT_ASC|SORT_DESC`.
These difference are a bit confusioning.
 
```
>>> \Cake\Utility\Hash::sort($array, '{n}.class', SORT_DESC)
=> [
     [
       "class" => "c",
     ],
     [
       "class" => "b",
     ],
     [
       "class" => "a",
     ],
   ]
>>> collection($array)->sortBy('class', SORT_DESC)->toList()
=> [
     [
       "class" => "a",
     ],
     [
       "class" => "b",
     ],
     [
       "class" => "c",
     ],
   ]
```

### What happened
`SORT_ASC` wth Hash::sort is not working.

### What you expected to happen
Hash::sort() accepts SORT_xxx constants.

Many developers use IDE or editors which has code complete feature, so working with constants will benefit for their DX.

**Comment by markstory** [comment]
Seems like a reasonable idea to me.

**Comment by o0h** [comment]
Thanks!
Well then, I try to solve this and send pull request.

**Comment by markstory** [comment]
Closing as a pull request was merged into 3.next
