### ISSUE TITLE
4.x Security::encrypt() 

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#13390]
Just to understand. These are the methods:

```
public static function encrypt(string $plain, string $key, ?string $hmacSalt = null): string
```
```
public static function decrypt(string $cipher, string $key, ?string $hmacSalt = null): ?string
```

I understand that the `$hmacSalt` argument can be `null`. In this case the `Security::getSalt()` method will be called.
But this method throws an exception if you have not set a HMAC salt.

I understand that:
- it is necessary to set a HMAC salt with the `Security::setSalt()` method, before using the `Security` utility. But the [Cookbook](https://book.cakephp.org/4.0/en/controllers/components/security.html) says nothing about it, or in the annotations of the code;
- or there's something in the code that doesn't work like you'd like it to work.

**Comment by ADmad** [comment]
The default app skeleton already sets the salt for you, that's why how to set the salt is not explicitly mentioned.

I'll update the exception message to state how to set the salt.

**Comment by markstory** [comment]
Pull request open now.
