### ISSUE TITLE
Unable to set protocol version 1.1 with curl client adapter

### ISSUE THREAD

**Issue by mstroink** [cakephp/cakephp#13398]
* [x] bug
* CakePHP Version: from 3.7 

### What you did
```php
$client = new Client();
$request = new Request('http://localhost/requestbin.php', 'GET');
$request = $request->withProtocolVersion("1.1");
$client->send($request);
```

### What happened
`HTTP/1.0 request`

### What you expected to happen
`HTTP/1.1 request`

### Issue
As you can see here: https://github.com/cakephp/cakephp/blob/master/src/Http/Client/Adapter/Curl.php#L75
The value for CURLOPT_HTTP_VERSION is set to 1.0, 1.1 or 2.0.
Valid values are `1` (v1.0), `2` (v1.1) and `3` (v2).

### fix
Code example
https://github.com/php-http/curl-client/blob/master/src/Client.php#L254

**Comment by markstory** [comment]
Thanks for the great bug report. I've opened a pull request.
