### ISSUE TITLE
GET request with body is being sent as POST request (HTTP Curl Client)

### ISSUE THREAD

**Issue by mstroink** [cakephp/cakephp#13406]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: from 3.7

### What you did
```php
$client = new Client();
$request = new Request(
    'http://localhost:8888/requestbin.php', 
    'GET',
    [],
    'param1=foo'
);

$response = $client->send($request);
```

### What happened
POST Request

### What you expected to happen
GET Request

I know it's a very unusual use case (but not prohibit by the HTTP spec). But i don't think a Request should be converted to something that's unexpected. 

### Issue
cURL will automatically change method to PUT or POST if CURLOPT_POSTFIELDS is set. 
https://github.com/cakephp/cakephp/blob/master/src/Http/Client/Adapter/Curl.php#L98

**Comment by ADmad** [comment]
So what change do you suggest?

**Comment by garas** [comment]
For unusual use cases, there is `curl` option.

You could try to set `CURLOPT_CUSTOMREQUEST` to `'GET'`.

https://github.com/cakephp/cakephp/blob/76de47e8c4430e79854a6c3df2adc251d43ca6ce/src/Http/Client/Adapter/Curl.php#L128

**Comment by othercorey** [comment]
This is probably due to the order in which the options are applied.  It might work if we could ensure `CURLOPT_HTTPGET` is applied after `CURLOPT_POSTFIELDS`.
