### ISSUE TITLE
[Redis] Optimize Cache::clear by using SCAN instead of KEYS

### ISSUE THREAD

**Issue by annuh** [cakephp/cakephp#13404]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3

Currently the RedisEngine uses the `KEYS` command to clear all cache objects.
This is not efficient, according to the Redis docs: https://redis.io/commands/keys

They propose to use the `SCAN` command to find all matching keys.

**Comment by markstory** [comment]
Closing as there is a pull request open for this now.
