### ISSUE TITLE
Paginator count query is so dumb with SELECT count(*) FROM (....)

### ISSUE THREAD

**Issue by NightCat419** [cakephp/cakephp#13418]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8
* Platform and Target: Apache, MySQL
### What you did

        $fields=[
            'id'=>[ ... ],
            'ship_date'=>[ ... ],
                ... ... ... ...
            'total_value'=>[ ... ],
        ];
        $defaults=[];
        $default_display= 'id'=>true,'ship_date'=>true,'warehouse'=>true,'status'=>true,'age'=>true];

        // apply default sort
        if(!isset($this->request->query['sort']))
        {
           $this->request->query['sort']='id';
           $this->request->query['direction']='desc';
        }
        // apply default limit
        if(!isset($this->request->query['limit']))
           $this->request->query['limit']=20;

        $finder=$this->Filter
            ->filter_to_conditions(
                $fields,
                $filter,
                [
                    'a',
                    'b',
                    'c',
                    'd',
                    ....
                ],
                ['Shipments.id']
            );
        $fields=$this->Filter->assign_defaults($fields,$filter,$defaults,$default_display);
        $this->set('_serialize', ['shipments']);

        $this->set('fields',$fields);
        $this->set('shipments', $this->paginate($finder));

### What happened
This is executing so long query to get count.

SELECT 
  (
    COUNT(*)
  ) AS `count` 
FROM 
  (
    SELECT 
      Shipments.id AS `Shipments__id`, 
      Shipments.ship_date AS `Shipments__ship_date`, 
      ....... ......... .........
      Shipments.status AS `Shipments__status` 
    FROM 
      shipments Shipments 
      LEFT JOIN ... 
      LEFT JOIN ...
      LEFT JOIN ...
      LEFT JOIN ...
      LEFT JOIN 1
      LEFT JOIN 2
      LEFT JOIN 3 
      LEFT JOIN 4
      LEFT JOIN 5
      LEFT JOIN 6
      LEFT JOIN 7
    GROUP BY 
      Shipments.id
  ) count_source

This query takes even about 20000 milliseconds.
It's so terrible.

**Comment by lorenzo** [comment]
Ok... do you have any suggestions to make it better?

**Comment by NightCat419** [comment]
Why cannot use more simple count query excluded other fields and left join?
And is there any option to avoid this query, for example we can set total count of paginator manually to avoid long count query like this.

**Comment by lorenzo** [comment]
You can use your own counter query with `$query->counter(function() { return $newQuery; })`

Maybe it is not immediately obvious to you, but joins, extra fields and group by clauses have an effect on the number of results that need to be counted. That's the reason the query looks like that

**Comment by NightCat419** [comment]
It is nice there is the way to to custom counter query.
Thanks

**Comment by NightCat419** [comment]
Btw, is the $newQuery query interface or plain SQL?

**Comment by lorenzo** [comment]
The query interface. You can see an example here https://book.cakephp.org/3.0/en/orm/query-builder.html#returning-the-total-count-of-records

**Comment by Erwane** [comment]
Sorry to comment on closed issue but my problem is very similar.
A HUGE table (millions of rows) and a pagination very slow.

Laravel have an elegant method for this : `simplePaginate` 
https://laravel.com/docs/5.7/pagination

There is no  first query count. You can display only `prev` and `next` buttons.
Maybe there is a problem if `next` return no rows BUT, it's a fast and working solution.

What do you think about integrate a method like that ?

**Comment by ADmad** [comment]
@Erwane You are welcome to submit a patch for such an implementation.

**Comment by Erwane** [comment]
i will try ;)

**Comment by ADmad** [comment]
Just keep in mind new features need to target the `3.next` branch.

**Comment by Erwane** [comment]
You do it so quickly :) 
Thanks

**Comment by ADmad** [comment]
I had done some reorganization of the Paginator code just a while back which made making the count query optional relatively easier :slightly_smiling_face:
