### ISSUE TITLE
Incorrect query results when using two BelongsToMany associations with the same joinTable

### ISSUE THREAD

**Issue by andres-ml** [cakephp/cakephp#13410]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.0

Gist with files: https://gist.github.com/andres-ml/0723ffab34454c20d232cb9544ef9b12

### What you did
Define two associations using the same table (users_parents):
`Users belongsToMany Parents`
`Users belongsToMany Children`
 ```php
 $this->belongsToMany('Parents', [
    'className' => 'Users',
    'foreignKey' => 'child_user_id',
    'targetForeignKey' => 'parent_user_id',
    'through' => 'UsersParents'
]);

$this->belongsToMany('Children', [
    'className' => 'Users',
    'foreignKey' => 'parent_user_id',
    'targetForeignKey' => 'child_user_id',
    'through' => 'UsersParents'
]);
```

Add finders that filter by parent/child:
```php
public function findChildrenOf(Query $query, array $config) : Query
{
    return $query->distinct('Users.id')->matching('Parents', function($q) use($config) {
        return $q->where(['Parents.id' => $config['user_id']]);
    });
}

public function findParentsOf(Query $query, array $config) : Query
{
    return $query->distinct('Users.id')->matching('Children', function($q) use($config) {
        return $q->where(['Children.id' => $config['user_id']]);
    });
}
```
Use both finders, one after the other (order does not matter):
```php
// users_parents has the entry (child_user_id:1, parent_user_id:2)
$child_id = 1;
$parent_id = 2;
 
$child = $this->Users->find('childrenOf', ['user_id' => $parent_id])->first();
$this->assertEquals($child->id, $child_id);

// will fail
$parent = $this->Users->find('parentsOf', ['user_id' => $child_id])->first();
$this->assertEquals($parent->id, $parent_id);
```

### What happened
The second find fails, regardless of the order.

### What you expected to happen
Both finds to work.

--

I'm guessing the join table alias 'UsersParents' is stored and whichever Association you use first works, the other does not.

A workaround to this issue: changing one of the `through`s for 'ParentsUsers' and defining a `ParentsUsersTable.php` with` $this->setTable('users_parents');`. Maybe something can be done to handle these cases automatically.

**Comment by lorenzo** [comment]
This should probably throw an exception.
In the mean time, use another through table. The important thing is using a different alias for it

**Comment by markstory** [comment]
@lorenzo This could be tricky to detect. Wouldn't we need to compare the foreign key configuration on each read operation to ensure they match the current setup?

**Comment by lorenzo** [comment]
@markstory I think we just need to detect, when building the BelongsToMany object, that the junction table instance does not already `belongsTo` different aliases

**Comment by markstory** [comment]
This kind of association will start raising exceptions in 4.1 hopefully preventing bad queries from being created.
