### ISSUE TITLE
Syntax error in the code

### ISSUE THREAD

**Issue by itsChathurangaJ** [cakephp/cakephp#13417]
When `dd(); ` method is used, it gives below error

> Error: syntax error, unexpected '(' 
File /.../vendor/symfony/var-dumper/VarDumper.php 
Line: 46

**Comment by markstory** [comment]
Sounds like you might be using an incompatible version of PHP. Also that line reference is referring to the symfony implementation of dd(), not ours which lives in https://github.com/cakephp/cakephp/blob/72cac845feb28148312357344b9a132055eaebff/src/basics.php#L127-L142

The symfony version is likely being loaded first as a dependency of phinx or another package you're using. In any case there isn't anything we can do to help with that.

**Comment by saeideng** [comment]
- do `composer update` , your issue will solve , it will install compatible version of vendors 
- or use  `php  7.x`

**Comment by itsChathurangaJ** [comment]
I upgraded the php version to 7.1.8. and it solved the issue
