### ISSUE TITLE
RedisEngine setTimeout deprecated

### ISSUE THREAD

**Issue by danger2k7** [cakephp/cakephp#13425]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.x, 3.8.x, 4.0.0-beta1.
* Platform and Target: PHP 7.3, php-redis: 5.0.0 

### What you did
Using RedisEngine.

### What happened
Deprecated Error: Function Redis::setTimeout() is deprecated.

### What you expected to happen
Change setTimeout() function to expire().
> Note: setTimeout is an alias for expire and will be removed in future versions of phpredis.

I can make a quick fix for this.

**Comment by saeideng** [comment]
you can open a PR on `master` , we will merge it to `3.8.x` , and `4.0`

**Comment by danger2k7** [comment]
Yes, expire is available since at least v2 (released in 2014)

**Comment by saeideng** [comment]
A PR now is open
