### ISSUE TITLE
4.x: FormHelper confirm via data-confirm?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13424]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement

* CakePHP Version: 3.x/4.x

### What you did
```php
echo $this->Form->postLink(..., ..., ['confirm' => __('Are you sure you want to delete # {0}?', $country->name)]);
```

I wanted to [intercept the form post and do an ajax delete instead](https://sandbox.dereuromark.de/sandbox/ajax-examples/table), re-using the confirm string in a different way here via .ajax().

### What happened
It is inline JS here:
```html
onclick="if (confirm(&quot;Are you sure you want to delete # \u00d6sterreich?&quot;)) { document.post_5d2f83592564f777576700.submit(); } event.returnValue = false; return false;"
```

### What you expected to happen

The core contains
```php
$message = $this->_cleanConfirmMessage($message);
$confirm = "if (confirm({$message})) { {$okCode} } {$cancelCode}";
```

It would be nice if the confirm part would just become a re-usable `data-confirm="Are you sure you want to delete # \u00d6sterreich?"` attribute on the link element and the JS code then would be simpler and directly just used this:

```js
if (confirm(document.{...}.dataset.confirm) ...
```

Then the following code would work:

```js
$('table.list a.postLink').removeAttr('onclick').click(function(e) {
            e.preventDefault();

            var alert = $(this).data('confirm');
            if (!confirm(alert)) {
                return false;
            }
            var form = $(this).prev();
            var url = $(form).attr("action");
            var tr = $(this).closest('tr');
            url = url + '.json';
            $.post(url).success(function(res) {
                if (res.error) {
                    alert(res.error);
                    return false;
                }
                tr.fadeOut(200);
            }).error(function() {
                alert("Error");
            });
            return false;
        });
```

Currently, I would have to duplicate this in the Form->postLink() call as separate data attribute for it.

What do people think?

**Comment by dereuromark** [comment]
For now I am just hacking it a bit on the app level ( https://github.com/dereuromark/cakephp-sandbox/commit/f27bb8b177669f447719a6c8a4aadab9281d080f ) to make it work more DRY.
A custom FormHelper overwriting the parent and:
```php
	public function postLink($title, $url = null, array $options = []) {
		if (isset($options['confirm'])) {
			$options['data-confirm'] = h($options['confirm']);
		}

		return parent::postLink($title, $url, $options);
	}
```

**Comment by ADmad** [comment]
Using data attribute for the error message sounds good.

**Comment by dereuromark** [comment]
PR open
