### ISSUE TITLE
Add new static method in Inflector class

### ISSUE THREAD

**Issue by delamux** [cakephp/cakephp#13431]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Hello, many times I have the need to create a related string, for example: MyItems to `my_item_id`, I don´t know if someone here has had the same need. 
It should be practice create a Static Method in Inflector Class? 
Like:
```php
<?
public static function relate($string) //propose names
{
}
``` 
This method will call the underscore and singularize static methods and return the string with suffix **`_id`.**

I can do it, update the documentation and obviously the tests.

**Comment by dereuromark** [comment]
What is a "related" string?
I don't think this warrants a method added, as the scope is not generic enough.

**Comment by delamux** [comment]
Sorry, I mean the associated property field.

**Comment by dereuromark** [comment]
Make your own DatabaseInflector that offers such custom methods. This is not core topic IMO.

**Comment by ADmad** [comment]
Closing as what you want can be easily achieved by making your own class/method.
