### ISSUE TITLE
Unstrict loadmodel() creates followup issues

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#13448]
### Code snipplet

`$this->loadmodel('tariffs');`

### Expected

To load TariffsTable or fail.

### What happens

Loads TariffsTable but sets its alias to 'tariffs'.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tariffs.id' in 'field list'
sql debug: `FROM tariffs tariffs`

Suggested fix:
3.x make loadModel upper case the first character
4.x make loadModel strict and not find the table if it is not {$modelname}Table

**Comment by dereuromark** [comment]
I agree that there shouldnt be too much inflection going on here to avoid these kind of casing issues.

**Comment by markstory** [comment]
Failing when the Table class doesn't exist will break existing applications and can't be done until 4.x.

Uppercasing the first letter will solve some scenarios but not all as multi word table names will fail in a similar way.

**Comment by inoas** [comment]
then let's only fix it for 4.x and not do any juggling at all?

**Comment by inoas** [comment]
(and maybe add a warning to the 3.x docs?)

**Comment by dereuromark** [comment]
Can you open a PR against 4.x here?

**Comment by ADmad** [comment]
> 4.x make loadModel strict and not find the table if it is not {$modelname}Table

This isn't a practical solution. Creating table classes is not mandatory.

**Comment by dereuromark** [comment]
Are we OK with disallowing `'tariffs'` here? In favour of the proper alias `Tariffs`?

**Comment by ADmad** [comment]
The fact that using `'tariffs'` loads `TariffsTable` is caused by this:

https://github.com/cakephp/cakephp/blob/c31eaeccb5a10017bd0607cff663417234056e47/src/ORM/Locator/TableLocator.php#L224-L226

We should see if we get a more reasonable error if that inflection is removed.

**Comment by dereuromark** [comment]
I can imagine this inflection to be used for lazy-using "DB table names" directly.
But we shouldn't allow this then maybe or people need to accept the alias being used exactly as such.
I opened https://github.com/cakephp/cakephp/pull/13475 for discussing and seeing how tests react.
