### ISSUE TITLE
Validation::date() invalidates dates before 1600

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#13441]
* [x] bug ?
* [x] enhancement ?
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: Windows Server 2012, PHP 7.0

### What you did
I tried to insert create a entity whose Table has a validation to Date:

```
<?php

$myTable->newEntity([
    'date' => '1062-07-01'
]);

// and of course:

$validator->date('date');
 
```

### What happened
Date is invalid

### What you expected to happen
To be valid :)

I don't know why but there is explicit restriction on this regex: https://api.cakephp.org/3.0/source-class-Cake.Validation.Validation.html#327-402

That invalidates everything before 1600 !
I even isolated an example here: https://3v4l.org/#preview

Can we accept dates before that? No? Why?

**Comment by celsowm** [comment]
@dereuromark  IMO the minimum date should be moved to **SQLDialect** because, for example, on MSSQL, using datetime2, the min date is 0001-01-01

**Comment by markstory** [comment]
> Can we accept dates before that? No? Why?

We haven't had many use-cases for dates prior to the 1800s. The current restrictions date back to https://github.com/cakephp/cakephp/commit/33fbace4c77040acf2379bc1e9463e6f580feeef#commitcomment-7145913

**Comment by celsowm** [comment]
@markstory A simple case of a classic Books and Authors would be invalidate by Cake Validation. I am not complaining, but I would suggest that thing like that should take advantage of each SQLDriver and be consistent with theirs respective limit (and not a generic regex validation). Would be a nice addition to Cake 4.x :)

**Comment by markstory** [comment]
Being consistent with the SQL layer is not simple as we accept multiple formats that are not handled by all database vendors. If you'd like to extend the year range to 0001 I think that's reasonable as that value can be represented by PHP's datetime well enough.

**Comment by celsowm** [comment]
Such a pity because would be a differential of Cake ORM, invalidate, for example 1752-12-01 using datetime1 on mssql but validates on mysql. Well, at least, could we have an information about the 1600 limit on books and api?

**Comment by ADmad** [comment]
I agree that any year starting with 0001 should be considered valid.
@celsowm Would you like to submit a patch for it?

**Comment by celsowm** [comment]
Yes I would! My first patch! Would be a pleasure!

**Comment by ADmad** [comment]
@celsowm Ping
