### ISSUE TITLE
Add time only data type

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13440]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: any

### What you did
Retrieved `time` value from a database.

### What happened
`time` data type column values are converted to Time object with date added. The problem and solution are described in more details [here](https://stackoverflow.com/questions/30960843/cakephp-3-time-column-gets-date-added/30965562#30965562).

![Screenshot from 2019-07-25 14:03:19](https://user-images.githubusercontent.com/3830106/61872995-0c61f180-aee5-11e9-88ba-1b816a768bd9.png)
![Screenshot from 2019-07-25 14:03:41](https://user-images.githubusercontent.com/3830106/61873000-0f5ce200-aee5-11e9-9799-fb55313f7396.png)

### What you expected to happen
I would expect the values that are retrieved from the database time type columns to have no date.

**Comment by dereuromark** [comment]
Shoudn't this be handled/solved first in Chronos? Then used in the framework? See https://github.com/cakephp/chronos/issues/102

**Comment by ADmad** [comment]
@dereuromark Yes, once we an object representing time only values making a database type class for it would be easy enough.

**Comment by ADmad** [comment]
@bancer `DateInterval` seems to be a suitable class for representing time only values. So you could make a database type class which using it's instances. Or perhaps use [CarbonInterval](https://carbon.nesbot.com/docs/#api-interval).

**Comment by bancer** [comment]
In our case time is not an interval but a clock time.

**Comment by ADmad** [comment]
You can search for a vendor class which provides object based representation of clock time or if you don't want any sort of conversion then simply map your `time` columns to string type by adding following in your bootstrap:

```php
\Cake\Database\Type::map('time', \Cake\Database\Type\StringType::class);
```

**Comment by dereuromark** [comment]
You can also make a PR against [Shim](https://github.com/dereuromark/cakephp-shim/tree/master/src/Database/Type) to provide a TimeType here to easily hook in.
The nice thing would be that you can handle edge cases more gracefully, e.g. normalizing 24:00 to 0:00 if those are basically the "same". Also set null for all overflow values beyond that range.

**Comment by markstory** [comment]
Would you expect to have time data mapped into a primitive type like `string` or would you want an object with methods? What methods would that object have?

**Comment by bancer** [comment]
Primitive type like string is fine for me. If it would be an object I would expect format methods to convert it to nicer forms like "13:00", "1:00 pm" and back to SQL format "13:00:00" and methods to add and deduct some minutes (23:50 + 15 minutes = 00:05).

**Comment by bancer** [comment]
But that may be too specific for our project. For a more general approach in implementing the time type class I would use MySQL [description](https://dev.mysql.com/doc/refman/8.0/en/time.html) of `time` data type.

**Comment by ndm2** [comment]
The common denominator for the supported databases is that time types represent the time of the day, and Postgres even supports timezones. MySQL also supports intervals for the time type, more or less at least, with a valid range of `-838:59:59.000000` to `838:59:59.000000`, but I think intervals should be a separate type (if at all).

A primitive string type doesn't seem to be overly useful here, one could simply remap the `time` type in order to achieve that. If there's specific support for time types, then I'd expect to retrieve an object that implements `\DateTimeInterface`, and comes with time manipulation/retrieval/comparison methods, test instance support, and ideally with timezone support. Basically the time equivalent of the date object, with a fixed date part, and string/JSON formatting that defaults to time only.

Timezone support could probably be tricky if we're talking about timezone manipulation, not just representation, as a fixed date part could cause unexpected results in comparisons.

**Comment by markstory** [comment]
Should a standalone time value have a timezone? The value `12:00` will occur in all timezones at some point, and representing them without timezones would mirror how we handle calendar date values.

**Comment by ndm2** [comment]
There certainly are situations where being able store and/or apply timezones might be helpful. While a certain time will happen at some point in any timezone, just like dates, a possible event scheduled for that time might only happen once at that time in a specific timezone.

Let's take a radio show as an example, scheduled daily for 10:30 PDT, and you'd wanted to show users the schedule in their local timezone.

**Comment by garas** [comment]
Time object shouldn't have any time zone assigned same as Date objects. Instead it should be converted to Datetime object before using when necessary. It just should be easy method to create full datetime+tz from time.

Time with timezone has meaning only when it comes with date. 

`10:30 PDT` is only valid March to November. DST starts/ends (if at all) at different days worldwide. Time zone conversions can only made with full date and time.

**Comment by inoas** [comment]
To have a deterministic time conversion DST and date info is required. now/today is sufficient as a context but otherwise one doesn't know enough

**Comment by dereuromark** [comment]
You can look into https://github.com/dereuromark/cakephp-shim/pull/54
As outlined above, it can be solved here on plugin level first and we can see if that provides useful enough in the future to warrant a core addition.

Also, without Chronos or Shim to enable a value object for time, I dont think we can do here much inside core itself, as those rely soonish also on date parts if you want to transform or diff values inside such an object representation.
Even so, you can try to further add useful classes to Shim here without forcing core to adapt these things in such an early stage.

**Comment by bancer** [comment]
We do not use timezone with time and datetime columns directly. All our customers are associated to a timezone, that does not change for a customer. So we save the timezone in customers table. Any time and datetime associated to that customer is applied to the customer's timezone in the code. MySQL `time` data type does not  support timezones so I would follow that and go with the implementation without timezone.

**Comment by bancer** [comment]
The problem with the implementation that in a plugin is that when ORM is used as standalone library with CakePHP 2.x it seems impossible to install 3.x plugins to 2.x app. `time` data type is not something unusual that should be in a plugin. It is one of basic database data types. In my opinion the framework core must be able to handle it properly.

**Comment by dereuromark** [comment]
Looks like the "resolves" keyword auto closed this. I guess this is valid though as we can keep this plugin based for now.

As for your 2.x use case: You can copy and paste this into project or 2.x plugin level until you can fully upgrade to 3.x.
That should resolve this for the time being.

The original ticket on Chronos still remains open as an object implementation approach.

**Comment by ADmad** [comment]
> Looks like the "resolves" keyword auto closed this.

That's silly of GH. The commit was done on a different repo under a different user/organization.

**Comment by bancer** [comment]
@dereuromark For the sake of simplicity we decided to use @ADmad [proposal](https://github.com/cakephp/cakephp/issues/13440#issuecomment-515029770) until time data type will be implemented in the framework.

@ADmad that is documented [here](https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-a-different-repository).

**Comment by ADmad** [comment]
@bancer It might be documented but auto closing issues across accounts shouldn't be a default feature IMO.

**Comment by dereuromark** [comment]
Most likely it is bound to the role (>= member) or sth - but yeah, a bit dangerous.

**Comment by dereuromark** [comment]
Given that there is no easy viable option and that the current time type is buggy in many ways, I think we should actually change the Cake internal default to the suggested string type @ADmad proposed:
```php
\Cake\Database\Type::map('time', \Cake\Database\Type\StringType::class);
```
