### ISSUE TITLE
Prevent parse error

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13452]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement

* CakePHP Version: latest master on local dev

### What you did
Development on a controller and view with some helpers.

### What happened
Got `var_export does not handle circular references` in `src/Core/ObjectRegistry.php` line 147  `$msg .= var_export($existingConfig, true);`

![parse_error](https://user-images.githubusercontent.com/39854/62292405-9f130b00-b466-11e9-9e0d-9ffa524cc25b.png)

### What you expected to happen
Trying to catch/prevent this parse error from happening during development as this one is really hard to understand and track down, as the stracktrace is completely missing on that one.

**Comment by dereuromark** [comment]
Note:
once I remove that line from the debug code I get a more meaningful error including stacktrace:

> The "RequestHandler" alias has already been loaded with the following config: which differs from array ( 'enableBeforeRedirect' => false, )

**Comment by markstory** [comment]
What is the circular reference created by?

**Comment by dereuromark** [comment]
A plugin controller extending the core one, I had to fence it with has() check to prevent it being loaded twice with different config ( https://github.com/dereuromark/cakephp-queue/blob/master/src/Controller/Admin/QueuedJobsController.php#L34 ).

**Comment by markstory** [comment]
I will see if I can reproduce given that. I wonder if json_encode() has a similar issue.
