### ISSUE TITLE
Split combined getter/setter EntityInterface::isNew()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13454]
Should we add a new method `EntityInterface::setNew(bool $new)` and change `isNew()` to `EntityInterface::isNew(): bool`?

**Comment by markstory** [comment]
Makes sense. Could we keep compatibility with a deprecation warning to avoid yet another 3.x release?

**Comment by ADmad** [comment]
Yup we can, I'll whip up a PR soon.

**Comment by robertpustulka** [comment]
Should this be backported to 3.x?
