### ISSUE TITLE
Refactor entity properties representing columns to objects

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13461]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: any.

`$_properties`, `$_original`, `$_dirty`, `$_errors`, `$_invalid`, `$_accessible`  in Entity class contain arrays of property names with different attributes related to those properties. In OOP world this is an indicator that properties should be objects themselves and encapsulate those attributes. Something like this:
```
class EntityProperty {
    public function getName() {...}
    public function getValue() {...}
    public function getOriginal() {...}
    public function isDirty() {...}
    public function getError() {...}
    public function isValid() {...}
    public function isAccessible() {...}
    ...
}
```
Entity class then could have a single reference to an array of property objects.

**Comment by bancer** [comment]
[M. Fowler, Dealing with Properties (pdf)](https://martinfowler.com/apsupp/properties.pdf)

**Comment by markstory** [comment]
What do you see the benefits of this approach being? Does it make ORM entities easier or more efficient to use?

**Comment by dereuromark** [comment]
While this might be making a few things easier, it will also most likely hugely complicate things IMO.
Also, on such a low level, the additional computation needed for things like lists of "valid, dirty" etc could easily be a performance loss, as you now need to walk through a lot of objects to find the answers.
Before looking into this more you might want to try making a prototype to test these things, and especially around batch processing of hundreds of (nested) entities and more here.

That said: I also wonder what the main benefits would be, from the user/developer perspective especially.

**Comment by bancer** [comment]
> What do you see the benefits of this approach being? Does it make ORM entities easier or more efficient to use?

Better encapsulation, simpler and easier to understand code, improved flexibility (it would be easier to add more functionality to properties class if the need arrives), better adherence to single responsibility principle, easier maintainability (smaller classes are easier to maintain). 

> While this might be making a few things easier, it will also most likely hugely complicate things IMO.

I believe it will slightly simplify things.

> Before looking into this more you might want to try making a prototype to test these things, and especially around batch processing of hundreds of (nested) entities and more here.

I may agree with that. Testing would not hurt.
