### ISSUE TITLE
Inconsistent cell attribute format at tableHeaders and tableCells 

### ISSUE THREAD

**Issue by garas** [cakephp/cakephp#13465]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8

### What you did
To set custom attributes for cells in `$this->Html->tableHeaders()`, format is `['Text' => ['attribute' => 'value']]` ([docs](https://book.cakephp.org/3.0/en/views/helpers/html.html#creating-table-headings)).
To set custom attributes for cells in `$this->Html->tableCells()`, format is `['Text', ['attribute' => 'value']]` ([docs](https://book.cakephp.org/3.0/en/views/helpers/html.html#creating-table-cells)).

Ex. 
```php
echo $this->Html->tableHeaders([
    ['Date' => ['class' => 'sortable']]
    ['Name' => ['class' => 'highlight']]
]);

echo $this->Html->tableCells([
    ['Jul 7th, 2007', ['Best Brownies', ['class' => 'highlight']]],
    ['Jun 21st, 2007', 'Smart Cookies'],
]);
```

### What you expected to happen
Both should support same format.

**Comment by markstory** [comment]
Which method should we normalize on? The format used by tableHeaders() is more verbose, so I would lean towards using the format tableCells() uses.

**Comment by garas** [comment]
Both are same verbose, but I slightly more lean to `tableCells()` format too.

**Comment by dereuromark** [comment]
@garas Are you opening a PR against 3.next here? Or 4.x and we backport it later?

**Comment by garas** [comment]
I'll open PR against 3.next

**Comment by markstory** [comment]
Pull request open now.
