### ISSUE TITLE
Pagination limit doesn't work with values >100 for custom finders

### ISSUE THREAD

**Issue by andyfoote** [cakephp/cakephp#13473]
This is a (multiple allowed):
bug

* CakePHP Version: 3.7
* Platform and Target: Apache, MariaDB, CentOS

### What you did
See https://stackoverflow.com/questions/57359873/cakephp-3-giving-wrong-pagination-output-when-limit-is-changed-for-a-custom-find which includes examples.

### What happened
If you try using `limit` value of anything above 100 it doesn't work. It will always limit the query to 100. This seems to affect custom finders, not "vanilla" ORM queries.

### What you expected to happen
It should use the `limit` value supplied

**Comment by garas** [comment]
There is `maxLimit` option (default 100) too, you need to raise it.

https://book.cakephp.org/3.0/en/controllers/components/pagination.html#limit-the-maximum-number-of-rows-per-page

**Comment by andyfoote** [comment]
It still doesn't work with a custom finder though.

If, for example, you set this in the Controller:

`public $paginate = [
        'finder' => 'filters',
        'maxLimit' => 200,
        'limit' => 150
    ];`

That will work.

But if you try doing this when using the custom finder:

`$this->paginate = ['page' => 3];`

It will "reset" the pagination such that it doesn't use any of the values supplied in `public $paginate`

**Comment by sugat** [comment]
This worked for me

public $paginate = array(
    // other keys here.
 'maxLimit' => 1000,
    'limit' => 1000
);

Reference:
http://caky.de/en/core-libraries/components/pagination.html#limit-the-maximum-number-of-rows-that-can-be-fetched
https://book.cakephp.org/3/en/controllers/components/pagination.html#limit-the-maximum-number-of-rows-per-page
