### ISSUE TITLE
Make metadata cache key configurable

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13471]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: any.

### What you did
Use case: each client has its own database. Client database schemas are identical. There are thousands of clients and therefore thousands of databases.

### What happened
The framework caches metadata for each database using the connection name as part of the cache key [(1)](https://api.cakephp.org/3.8/source-class-Cake.Database.Schema.CachedCollection.html#72-81). This results in many identical value caches stored in the cache engine. This is a performance hit as queries to `information_schema`  are very slow and inefficient use of space.

### What you expected to happen
I would expect the metadata cache key name to be configurable like 'cacheMetadata' key:
```
'cacheMetadata' => true,
'cacheMetadataKey' => 'client_database',
```
So that when 'cacheMetadataKey' is not empty then it would be used as the cache key instead of the connection name. This would greatly reduce the number of queries to `information_schema` and improve performance.

**Comment by bancer** [comment]
@ADmad we need this to be fixed in 3.x in order to be able to migrate from 2.x.

**Comment by bancer** [comment]
In some cases queries to `information_schema` last almost 2 seconds.

![Screenshot from 2019-08-07 11:04:04](https://user-images.githubusercontent.com/3830106/62610104-44186280-b903-11e9-8d15-971089c8d81e.png)

![Screenshot from 2019-08-07 11:06:32](https://user-images.githubusercontent.com/3830106/62610185-6f02b680-b903-11e9-81ed-bd13e4e71a97.png)

**Comment by ADmad** [comment]
Personally I have no interest in adding new features to 3.x unless they help a large number of users.

You can either backport the enhancement to 3.next (and wait for 3.9 release) or just use custom connection and schemacollection class and override relevant bits of code.

**Comment by bancer** [comment]
Okay, could you reopen the issue please?

**Comment by ADmad** [comment]
The schema collection is cached and you would see queries for `information_schema` only during development. If your schema doesn't change frequently then simply set a long duration for `_cache_model_` cache config even when debug is on.

**Comment by bancer** [comment]
> Use case: each client has its own database. Client database schemas are identical. There are thousands of clients and therefore thousands of databases.

Yes, it is cached. But in this scenario such caching does not help much. We have to clear caches after each deployment. And deployments are few times per week. It takes several days to refresh all caches for thousands of databases.

**Comment by ADmad** [comment]
Okay. Simply over ridding the 2 classes I mentioned above would get you going right away and it's a pretty simple change.

**Comment by bancer** [comment]
It is very disappointing that CakePHP team is so resistant to any changes. It feels that the framework team have no interest in helping people to migrate from 2.x but making it extremely difficult by placing many stops. Any changes to 2.x branch are banned. Now we cannot get changes into 3.x. Such attitude makes people think twice before choosing CakePHP for new projects.

**Comment by dereuromark** [comment]
@bancer Please open a PR with your suggested changes for further discussion. That is more simple and helpful to resolve this the way you want it to. Please also mention in the description that it is a backport of PR xyz of 4.x then to cross-reference them.

**Comment by dereuromark** [comment]
> You can either backport the enhancement to 3.next (and wait for 3.9 release) or just use custom connection and schemacollection class and override relevant bits of code.

@bancer No one here is resistant to changes, please read again. You were asked to open a PR against 3.next branch, that is all that is needed to further progress on the topic at hand.
