### ISSUE TITLE
3.next: Backport 4.x functionality for easier migration

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13493]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement

in 4.x we added API that should ideally be backported into 3.next (3.9).
The migration guide is quite empty so far ( https://github.com/cakephp/docs/blob/3.next/en/appendices/3-9-migration-guide.rst ). We should fix that - and make the diff between 3.x and 4.x easier for future migration then.

According to docs (catch all ticket here to tick off):

ORM
---

* [x] isNew() => setNew()

* [x] ``Table::saveManyOrFail()`` method has been added that will throw ``PersistenceFailedException``
  with the specific entity that failed in case of an error. The entities are saved transaction safe.
* [x] ``Table::deleteMany()`` and ``Table::deleteManyOrFail()`` methods have been added for removing many
  entities at once including callbacks. The entities are removed transaction safe.

( https://github.com/cakephp/cakephp/pull/13212 )

Http
----

* [x] ``Cake\Http\Client\Response::isSuccess()`` was added. This method returns true
  if the response status code is 2xx.
* [x] ``CspMiddleware`` was added to make defining Content Security Policy headers simpler.
* [ ] Support for `SameSite` attribute in cookies. #13766 #13806

TestSuite
---------

* [x] ``TestSuite\EmailTrait::assertMailContainsAttachment()`` was added. https://github.com/cakephp/cakephp/pull/13216

Console
-------

* [x] Command classes can implement the ``defaultName()`` method to overwrite the
  conventions based CLI name.

More to be added? You can create list items via `* [ ] ...`.

---

Already included in [Shim](https://github.com/dereuromark/cakephp-shim) plugin and thus not necessarily needed (can easily be opt-in if desired):
- Controller referer default security improvement
- newEmptyEntity() method for Table (unless you want to move this also into 3.next)
- FormHelper BC behavior is included here as helper
- [this maybe](https://github.com/dereuromark/cakephp-shim/issues/56)

**Comment by dereuromark** [comment]
Small question:
- Do we need to also backport newEmptyEntity() to core 3.9? (Currently, this is in Shim plugin as opt-in FC shim + deprecation and suffices as such IMO).

You can use :+1:  / :-1: on the comment for your feedback.

If not, I will tag a release here for Shim shortly documenting it.

**Comment by othercorey** [comment]
> * Do we need to also backport newEmptyEntity() to core 3.9? (Currently, this is in Shim plugin as opt-in FC shim + deprecation and suffices as such IMO).

Why not, right?

**Comment by othercorey** [comment]
Because this is a breaking change in 4.0, I think backporting `newEmptyEntity()` to 3.9 should include a deprecating warning in `newEntity()`.

I don't know if that is an unpopular opinion. But, with `newEmptyEntity()`, they have a way to fix it with warnings before 4.0 where it simply throws a PHP error.

**Comment by dereuromark** [comment]
Jep, in 3.next this is safe to be added as deprecation warning IMO.

**Comment by dereuromark** [comment]
- [ ] Backport the exceptions for ->Form->create() using false or string as clear deprecation message to help upgrading. Right now apps break in 4.x then all of the sudden, where this could have been known before in 3.x.

**Comment by dereuromark** [comment]
- [ ] Backport new afterMarshal event ( https://github.com/cakephp/cakephp/pull/14383 )

**Comment by dereuromark** [comment]
SameSite attribute in cookies and the Command change is mainly left to have a complete 3.9 here it seems
Anyone interesting in doing the rest here?

**Comment by dereuromark** [comment]
- [ ] https://github.com/cakephp/cakephp/pull/14114 backport.

**Comment by othercorey** [comment]
I think we can close this out? We aren't backporting the SameSite cookie change unless someone randomly does that before release.
