### ISSUE TITLE
option to hide user input in command

### ISSUE THREAD

**Issue by waspinator** [cakephp/cakephp#13495]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: php:7.3-apache-stretch

### What you did
In a command, I asked the user to enter a password.

`$password = $io->ask('password');`

### What happened
When the user typed in the password I could see it on the screen.

### What you expected to happen
`*` in place of actual characters 

possible ways of making this work
- https://github.com/Seldaek/cli-prompt/

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/cakephp/issues/2110

**Comment by trenshaw** [comment]
Laravel's Artisan Console secret() method current provides this

https://laravel.com/docs/5.8/artisan#prompting-for-input
https://laravel.com/api/5.8/Illuminate/Console/Command.html#method_secret

Dig a little deeper and this method uses \Symfony\Component\Console\Question\Question for this by calling Question::setHidden(true)

https://github.com/illuminate/console/blob/master/Command.php 

More details in Symfony's documentation and repo

https://symfony.com/doc/current/components/console/helpers/questionhelper.html#hiding-the-user-s-response
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Console/Question/Question.php
