### ISSUE TITLE
Unquoted alias and field names when using 'join' array

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13509]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: Apache, Linux.

### What you did
```
$options = [
    ...,
    'join' => [
        'table' => 'orders',
        'alias' => 'Order',
        ...,
    ],
];
$logs = $this->find('all', $options)
    ->enableHydration(false)
    ->toArray();
```
Data source is configured with `'quoteIdentifiers' => true,`.

### What happened
`Order` alias was not escaped in SQL.
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order
```
SQL (partial):
```
... LEFT JOIN orders Order ON ...
```

### What you expected to happen
I would expect it to be quoted:
```
... LEFT JOIN `orders` `Order` ON ...
```

**Comment by markstory** [comment]
I wasn't able to reproduce this problem. I added a test for `join()` in 1cd1aed9625c78a9853449d1e7455d0dff408e9e and I also got the expected result from

```php
        $this->loadFixtures('Articles');
        $table = $this->getTableLocator()->get('Articles');

        $table->getConnection()->getDriver()->enableAutoQuoting(true);
        $query = $table->find('all', [
            'join' => [
                'table' => 'orders',
                'alias' => 'Order',
                'conditions' => '1 = 1',
            ]
        ]);
        debug($query->sql());
```

How would I go about reproducing the problem you're seeing?

**Comment by bancer** [comment]
You have
```
'alias' => 'orders',
'table' => 'Order',
```

Have you tried
```
'alias' => 'Order',
'table' => 'orders',
```

**Comment by markstory** [comment]
Yes. That's in the snippet I posted in my previous comment. Both forms generate quoted names.

```sql
'SELECT "Articles"."id" AS "Articles__id", "Articles"."author_id" AS "Articles__author_id", "Articles"."title" AS "Articles__title", "Articles"."body" AS "Articles__body", "Articles"."published" AS "Articles__published"
FROM "articles" "Articles"
INNER JOIN "orders" "Order" ON 1 = 1'
```
If I invert the names used for alias/table I get:

```sql
'SELECT "Articles"."id" AS "Articles__id", "Articles"."author_id" AS "Articles__author_id", "Articles"."title" AS "Articles__title", "Articles"."body" AS "Articles__body", "Articles"."published" AS "Articles__published"
FROM "articles" "Articles"
INNER JOIN "order" "Orders" ON 1 = 1'
```

**Comment by bancer** [comment]
> How would I go about reproducing the problem you're seeing?

@markstory take a look at https://github.com/cakephp/cakephp/pull/13699 please.

**Comment by othercorey** [comment]
Wouldn't this work if you use the array form instead?

```
                'conditions' => [
                    'Order.product_id' => 'products.id',
                ],
```

**Comment by bancer** [comment]
@othercorey Nope. That generated:
```
ON `Order`.`product_id` = 'products.id'
```

@markstory I cannot reproduce the problem on our production code anymore. So this issue can be closed I think.

**Comment by othercorey** [comment]
Sorry, my example was wrong. For others interested, check out QueryExpression::equalFields.

https://api.cakephp.org/3.8/class-Cake.Database.Expression.QueryExpression.html#_equalFields
