### ISSUE TITLE
Unnecessary escaping in query's select method

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13507]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: Linux, MySQL.

### What you did
I tried to construct a subquery:
```
$TempOrder = TableRegistry::getTableLocator()->get('TempOrder', [
	'className' => 'App\Model\Table\OrdersTable',
]);
$Query = $TempOrder->find()
	->select(['COUNT(*) > 0'])
	->where([
		... // some conditions here
	]);
debug($Query->sql());
```

The data source is configured with `'quoteIdentifiers' => true,`.

### What happened
Output:
```
SELECT `TempOrder`.`COUNT`(*) > 0 AS `TempOrder__COUNT(*) > 0` 
FROM `orders` `TempOrder` 
WHERE ...
```

### What you expected to happen
I would expect `COUNT(*) > 0` function to be unescaped:
```
SELECT COUNT(*) > 0
FROM `orders` `TempOrder` 
WHERE ...
```

**Comment by lorenzo** [comment]
This is expected, you need to use the query api to create expression like that. You can use `$query->func()->count()` for instance.

**Comment by bancer** [comment]
@lorenzo `$query->func()->count()` does not generate `COUNT(*) > 0`.

**Comment by dereuromark** [comment]
Please read the docs here: https://book.cakephp.org/3.0/en/orm/query-builder.html#using-sql-functions

**Comment by bancer** [comment]
`$query->func()->count()` generates `COUNT(*)` but not `COUNT(*) > 0`.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by markstory** [comment]
If you need that exact expression you can use an [expression object](https://book.cakephp.org/3.0/en/orm/query-builder.html#raw-expressions)
