### ISSUE TITLE
Add option 'escape' => false into Paginator->meta()

### ISSUE THREAD

**Issue by danielhrenak** [cakephp/cakephp#13518]
Hi, 
would it be possible to add option  
`escape' => false`
to each `$this->generateUrl()` in `Paginator->meta()` method? 
https://github.com/cakephp/cakephp/blob/7e59d47997eda56bc52a1282cd18b8d266abbe3b/src/View/Helper/PaginatorHelper.php#L1191

Because `Html->meta()` then escapes URL again.

**Comment by ADmad** [comment]
You can already use `escape` option for the `$urlOptions` argument of `generateUrl()`.

**Comment by ADmad** [comment]
Sorry, I misread the issue.

**Comment by dereuromark** [comment]
PR open.
