### ISSUE TITLE
TestEmailTransport::send returns wrong type

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#13510]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.0
* Platform and Target: PHP 7.2.19-0ubuntu0.18.04.1 with PHPUnit 6.5.14

### What you did
In my phpunit test:
```
    use EmailTrait;
```
In my code:
```
private static function sendMail() {
    $email = new Email('default')->setFrom(...)->setTo(...)->....;
    $sent = $email->send();
    self::verifySent($sent, $email);
}

private static function verifySent(array $sent, Email $email): array
{
    ....
}
```

### What happened
The sent function could not be called:
 ```
2019-08-13 13:31:25 Error: [TypeError] Argument 1 passed to App\Service\EmailService::verifySent() must be of the type array, boolean given
```
### What you expected to happen
The sent function can be called

### Why did that happen

`\Cake\Mailer\AbstractTransport::send` declares to `@return array` and we trusted this when developing our code.

Sadly, `\Cake\TestSuite\TestEmailTransport::send` breaks that promise given by its parent class by returning `@return bool`

I guess you'll also stumble over this when you're trying to get more typed in cake 4

**Comment by ADmad** [comment]
> I guess you'll also stumble over this when you're trying to get more typed in cake 4

The return type is already fixed in Cake 4 :)

We should fix it in Cake 3 too.
