### ISSUE TITLE
4.x: JsonType null handling fix

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13519]
Are we fixing the null part of the JsonType in 4.x?

Looking into https://github.com/cakephp/docs/blob/4.x/en/appendices/4-0-migration-guide.rst#database I didnt see JsonType being a bit more strict around null handling yet.

Do we want to move the Shim JsonType into core?
https://github.com/dereuromark/cakephp-shim/blob/master/src/Database/Type/JsonType.php
Especially with "DEFAULT NULL" type columns this would be saner IMO to have.
At the same time it would also properly escalate on "NOT NULL" columns that just silently get a " null" string right now.

Refs: 
- https://github.com/dereuromark/cakephp-shim/blob/master/docs/Database/Json.md
- https://github.com/cakephp/cakephp/issues/11499

**Comment by ADmad** [comment]
I am :+1: for this change. Hardly anyone would be interested in having PHP `null` being JSON encoded to `"null"`.
