### ISSUE TITLE
CakeEventManager::instance() leaks memory in unit tests

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13526]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.19
* Platform and Target: Linux, Apache, MySQL.

### What you did
Used `CakeEventManager::instance()->attach($this)` in a component.

### What happened
Unit tests suite memory usage increased from 330M to 3500M.

### What you expected to happen
I would expect the framework to cleanup the static instance of CakeEventManager between tests.

**Comment by markstory** [comment]
> I would expect the framework to cleanup the static instance of CakeEventManager between tests.

We can't do that as we'd break events attached during application bootstrap.

**Comment by dereuromark** [comment]
Extend the Test class or add a trait that you can call and clean up as custom method call.
This is probably the best solution for now for 2.x version.
