### ISSUE TITLE
Add MiddlewareInterface to MiddlewareQueue's @param hints

### ISSUE THREAD

**Issue by PatrickG** [cakephp/cakephp#13528]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x.

### What you did
`$middlewareQueue->add();`

### What happened
Psalm reports an error when adding a Middleware that implements MiddlewareInterface to the MiddlewareQueue.

### What you expected to happen
Psalm should not report an error when using MiddlewareQueue's `add`, `push`, etc. methods.

That's easily fixable by add `MiddlewareInterface` to the @param hints in `MiddlewareQueue`.

**Comment by dereuromark** [comment]
Do you want to make a PR here with your suggested changes?

**Comment by ADmad** [comment]
PR up.
