### ISSUE TITLE
Slow information_schema queries

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13522]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: Apache, MySQL 5.6.

### What you did
Used table class.

### What happened
ORM layer generates queries to information_schema table that are very slow. F.ex.:

![Screenshot from 2019-08-15 10:45:04](https://user-images.githubusercontent.com/3830106/63083726-c29b8280-bf49-11e9-93f8-ec777d3007fa.png)

### What you expected to happen
The query is cached but maybe there is a way to improve it's performance by setting `innodb_stats_on_metadata` to 0 before it is executed like it is recommended [here](https://www.percona.com/blog/2011/12/23/solving-information_schema-slowness/) and back to its original value after.

**Comment by markstory** [comment]
Have you tried the metadata configuration change on your application? My applications generally operate out of a small number of databases which lets me pre-compile metadata during deploy.

**Comment by bancer** [comment]
> Have you tried the metadata configuration change on your application?

I do not fully understand what do you mean here.

**Comment by ADmad** [comment]
What you want can be done an application level and the default `app.php` even shows how https://github.com/cakephp/app/blob/master/config/app.default.php#L295.

**Comment by bancer** [comment]
@ADmad it would be good to mention that somewhere in the cookbook.

**Comment by ADmad** [comment]
The `init` option for connections is mentioned [here](https://book.cakephp.org/3.0/en/orm/database-basics.html#configuration).
