### ISSUE TITLE
Routes broken

### ISSUE THREAD

**Issue by squalltua** [cakephp/cakephp#13531]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.15
* Platform and Target: LAMP

### What you did
I create my routes.php is
`````
Router::scope('/:lang', ['lang' => 'th|en|ja'], function (RouteBuilder $routes) {
    // ... other code ... 

    $routes->connect('/blog', ['controller' => 'Articles', 'action' => 'index']);
    $routes->connect('/blog/all', ['controller' => 'Articles', 'action' => 'index']);
    $routes->connect('/blog/read/:slug', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);

    $routes->connect('/courses', ['controller' => 'Courses', 'action' => 'index']);
    $routes->connect('/courses/detail/:slug', ['controller' => 'Courses', 'action' => 'view'])->setPass(['slug']);
    $routes->connect('/courses/enroll/:slug', ['controller' => 'Courses', 'action' => 'enroll'])->setPass(['slug']);

    $routes->fallbacks(DashedRoute::class);
});
`````

and go URL with `https://[example.com]/th/courses` *Boom!!!*

### What happened
*NOTE:* Before, still working normally. today not work. I do not touch anything.

Missing Route with this route.
`/:lang/courses`

`$routes->connect('/courses', ['controller' => 'Courses', 'action' => 'index']);`

#### Error is
`Missing Route
Cake\Routing\Exception\MissingRouteException`

`Error: A route matching "array ( 'page' => false, 'action' => 'index', 'plugin' => NULL, 'controller' => 'Courses', '_ext' => NULL, )" could not be found.`

None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php

The passed context was:
`````
[
	'_base' => '',
	'_port' => null,
	'_scheme' => 'https',
	'_host' => 'kplearningspace.com',
	'params' => [
		'lang' => 'th',
		'pass' => [],
		'controller' => 'Courses',
		'action' => 'index',
		'plugin' => null,
		'_matchedRoute' => '/:lang/courses',
		'_ext' => null
	]
]
`````

#### Connected Routes

Template | Defaults | Options
-- | -- | --
/:lang/blog | [ 'controller' => 'Articles', 'action' => 'index', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute' ]
/:lang/blog/all | [ 'controller' => 'Articles', 'action' => 'index', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute' ]
/:lang/blog/read/:slug | [ 'controller' => 'Articles', 'action' => 'view', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute', 'pass' => [ (int) 0 => 'slug' ] ]
/:lang/courses | [ 'controller' => 'courses', 'action' => 'index', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute' ]
/:lang/courses/detail/:slug | [ 'controller' => 'Courses', 'action' => 'view', 'lang' => 'th\|en\|ja', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute', 'pass' => [ (int) 0 => 'slug' ] ]
/:lang/courses/enroll/:slug | [ 'controller' => 'Courses', 'action' => 'enroll', 'lang' => 'th\|en\|ja', 'plugin' => null ] | [ '_ext' => [], 'routeClass' => 'Cake\Routing\Route\DashedRoute', 'pass' => [ (int) 0 => 'slug' ] ]

*Observations from me: * In template `/:lang/courses` on `Defaults` column `'controller' => 'courses'` The `c` is small letter. I think is wrong.

And in Debug-kit in Routes tab is look good, not wrong

Route name | URI template | Defaults
-- | -- | --
courses:index | /:lang/courses | {     "controller": "Courses",     "action": "index",     "lang": "th\|en\|ja",     "plugin": null }

PS. I really don't know why happened.
PS. Run-on production server not working.
PS. Run-on development server is work.

### What you expected to happen
To come back to work

**Comment by ADmad** [comment]
Are you using routes caching? Have you tried clearing it?

**Comment by squalltua** [comment]
> Are you using routes caching? Have you tried clearing it?

Yes.

**Comment by markstory** [comment]
Did you update CakePHP between the working and non-working states?

**Comment by squalltua** [comment]
> Did you update CakePHP between the working and non-working states?

No.

And sorry about report CakePHP version is **must be 3.6.14**
I just upgrade CakePHP version to 3.6.15 after the project has an error (2019-08-17)
This project has been online for almost 1 year since 2018.

#### last upgrade result 

`````
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 25 updates, 0 removals
  - Updating cakephp/plugin-installer (1.1.0 => 1.1.1): Loading from cache
  - Updating zendframework/zend-diactoros (1.8.6 => 1.8.7): Loading from cache
  - Updating cakephp/chronos (1.2.4 => 1.2.8): Loading from cache
  - Updating cakephp/cakephp (3.6.14 => 3.6.15): Loading from cache
  - Updating erusev/parsedown (v1.7.2 => 1.7.3): Loading from cache
  - Updating google/recaptcha (1.2.1 => 1.2.2): Loading from cache
  - Updating squizlabs/php_codesniffer (3.4.1 => 3.4.2): Loading from cache
  - Updating symfony/process (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/finder (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/filesystem (v4.2.4 => v4.3.3): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/debug (v4.2.4 => v4.3.3): Downloading (100%)         
  - Updating symfony/console (v3.4.23 => v3.4.30): Downloading (100%)         
  - Updating composer/xdebug-handler (1.3.2 => 1.3.3): Loading from cache
  - Updating composer/spdx-licenses (1.5.1 => 1.5.2): Loading from cache
  - Updating composer/ca-bundle (1.1.4 => 1.2.3): Loading from cache
  - Updating composer/composer (1.8.4 => 1.9.0): Loading from cache
  - Updating symfony/config (v3.4.23 => v3.4.30): Downloading (100%)         
  - Updating symfony/yaml (v3.4.23 => v3.4.30): Downloading (100%)         
  - Updating nikic/php-parser (v4.2.1 => v4.2.3): Downloading (100%)         
  - Updating symfony/polyfill-php72 (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/var-dumper (v4.2.4 => v4.3.3): Loading from cache
  - Updating twig/twig (v1.38.4 => v1.42.2): Loading from cache
  - Updating ajgl/breakpoint-twig-extension (0.3.3 => 0.3.4): Loading from cache
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
`````

**Comment by saeideng** [comment]
```php
Error: A route matching "array ( 'page' => false, 'action' => 'index', 'plugin' => NULL, 'controller' => 'Courses', '_ext' => NULL, )" could not be found.
```
what is this parameter? :arrow_right:   `'page' => false,`

**Comment by ADmad** [comment]
The presence of `'page' => false` in the error message makes me think the error is not caused by the URL you are accessing but rather due to a link/URL on the page you are accessing.

**Comment by squalltua** [comment]
@ADmad thank you.
I will try to check all the information on the page and see if there is anything wrong.

**Comment by squalltua** [comment]
@ADmad Thank you so much.

Your comment is correct. It's wrong on some links / URLs on the page. I just hide the last data. It works. now I will investigate about this data why make the site broken.

**Comment by ADmad** [comment]
> I found it. because paginator does not add :lang in next or prev link button

That's because you haven't persisted the `lang` param.

https://api.cakephp.org/3.8/class-Cake.Routing.Route.Route.html#_setPersist
