### ISSUE TITLE
4.x - Combine Mailer and Email classes.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13535]
With the creation of `Renderer` and `Message` classes `Email` is now just a glue class which uses the two to send email using a `Transport`. `Mailer` is a higher level convenience class which forwards most of the calls to `Email` class using `__call()` anyway.

So having both `Email` and `Mailer` seem unnecessary. The responsibility of both can be handled by a single class. If we move/add function for managing profiles and transport to `Mailer` then it can directly send mails using `Message`, `Renderer` and `Transport`, making `Email` redundant which can be marked as deprecated.

**Comment by ADmad** [comment]
Currently calling `Mailer::viewBuilder()` calls `Email::viewBuilder()` which calls `Renderer::viewBuilder()`. That's some crazy misdirection :slightly_smiling_face:.

**Comment by markstory** [comment]
What would the migration path be for user land code?

**Comment by ADmad** [comment]
I haven't worked out the details yet but there would be minimal BC break if at all.

**Comment by markstory** [comment]
Might be worth trying to outline the migration/upgrade path in a wiki page/issue first.

**Comment by ADmad** [comment]
I already have a PR up :)
