### ISSUE TITLE
Cake 2.X: CSRF Token Re-Generated on Unlocked Action

### ISSUE THREAD

**Issue by KidA78** [cakephp/cakephp#13532]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.13
* Platform and Target: Nginx, MySQL 5.7

### What you did
I've set up a Controller to use the `SecurityComponent` for CSRF protection. I've specified most of the actions to be unlocked, with only a few actions enabled for CSRF validation.

### What happened
One of the unlocked actions, we'll call it `MyController#safeAjaxAction()`, runs asynchronously after a secure form is loaded via a locked action,`MyController#csrfForm()`.  When this action is called, it still triggers the 
 `SecurityComponent#startup()` method, which regenerates the CSRF token and saves it to the session. This automatically invalidates the CSRF token generated in the form. 

From the startup method:

```
	public function startup(Controller $controller) {
		// ... some stuff
		$this->generateToken($controller->request);
               // ... some more stuff
	}
```

As you can see, the `SecurityComponent` `startup` method will be called for every action in a controller, and `generateToken` is called without any check if the action is locked or not.  

### What you expected to happen
My expectation is that `unlockedActions` should have no effect on the CSRF workflow, even if they exist within the same controller as other locked actions.

**Comment by markstory** [comment]
Do you need one-time tokens for your application? You could set `Security->csrfUseOnce = false` to avoid this problem and a few other CSRF related woes when doing asynchronous work.

**Comment by KidA78** [comment]
@markstory that's certainly an idea, but wouldn't that compromise on security?
Is there an intentional reason why an excluded action would generate a new token?

**Comment by markstory** [comment]
If an excluded action is submitting to an included one, not generating s token will result in a csrf failure. Because we don't know the destination of any potential form we have to generate a token.

I don't think multi-use csrf tokens are a significant risk. They are the default in 3.x+ as single use tokens have a number of sharp edges.
