### ISSUE TITLE
Cloning entities on saving BelongsToMany with SAVE_APPEND strategy

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13547]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8

### What you did
Saving entity with `BelongsToMany` data, strategy=`SAVE_APPEND`
```
$tag = $this->Tags->newEntity(['name'=>'test']);
$article = $this->Articles->findById(1);
$article->tags = [$tag];
$this->Articles->save($article);
var_dump($tag->id); //Null
var_dump($article->tags[0]); //New id
```

### What happened
Associated entities are [were cloned](https://github.com/cakephp/cakephp/blob/bbd4abe94c6c6c0b86af19b66beb750e32a69d9b/src/ORM/Association/BelongsToMany.php#L774), reference is lost:
`$article->tags[0]` is not the same instance as `$tag`.

### What you expected to happen
`$article->tags[0]` is still the same instance as `$tag`.

**Comment by ADmad** [comment]
Having you checked if existing tests still pass if the cloning is removed? I presume it must be for a reason.

**Comment by andrii-pukhalevych** [comment]
Looks like its some [manipulation with validation errors](https://github.com/cakephp/cakephp/blob/bbd4abe94c6c6c0b86af19b66beb750e32a69d9b/src/ORM/Association/BelongsToMany.php#L784).
So 99% that tests will fail after removing the cloning.
But Im not fully clear what happens at this point, therefore created issue instead of PR.
If its just error messages manipulation, will be good to refactor to reduce memory consumption on large entities cloning and to do not lost references.

**Comment by markstory** [comment]
The validation error manipulation is also to ensure that if multiple records are saved and the wrapping transaction fails that associated entities don't have ids set when they have not actually been persisted.

**Comment by andrii-pukhalevych** [comment]
Can we add methods that will get/set all protected entity fields from array to backup/restore fields data instead of cloning object?
I see following fields in `EntityTrait`:
```
protected $_fields
protected $_original
protected $_hidden
protected $_virtual
protected $_dirty
protected $_new
protected $_errors
protected $_invalid
protected $_accessible
protected $_registryAlias
```
