### ISSUE TITLE
3.x cookies in the Cake\http\client are copied from the wrong (sub)domain during redirects

### ISSUE THREAD

**Issue by michielkeijts** [cakephp/cakephp#13543]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7

### What you did
In the script I use the HTTP Client with the option to follow redirects (`$options['redirect'] = 10`). I opened an url with a post request (an authentication request) to `authentication.domain.com`. The response included a `Set-Cookie` header as well as a `Location` header, which redirected the location to `backstage.domain.com` The cookie had this domain also. 

The cookie collection of the `Cake\Http\Client` holds all the cookies for the top level domain and all its subdomains (in this case: `backstage.domain.com` `authentication.domain.com`)
During the redirect in the [Cake\Http\Client::send](https://github.com/cakephp/cakephp/blob/master/src/Http/Client.php#L417) method, the cookies from the requests' cookie collection for the new location are copied in the request, so the valid cookies for the new sub-domain are included, if any cookies for this subdomain exists in the requests' cookie collection

### What happened
In my case, both the `authentication.domain.com` and the `backstage.domain.com` holds a cookie with the same name, but different value (SESSION=123 for backstage and SESSION=456 for authentication). 

When redirecting from the `authentication.domain.com` to the `backstage.domain.com`, the cookie SESSION from the authentication domain was copied in the request to `backstage.domain.com`. 
In this case, the request did already have a cookie with name SESSION and value 123 for the `backstage.domain.com` and was overwritten by the requests` cookie collection cookie SESSION with value 456. So my session was basically overwritten.

This means that when cookies with different names or equal values were used, this problem would not have poped up. 

This has to do with the fact that in the [Cake\Http\Client::send](https://github.com/cakephp/cakephp/blob/master/src/Http/Client.php#L417) method, the cookies are copied from the cookie collection, before the new url for the request is set. In other words: it looks for cookies for the current domain, which is still the `authentication.domain.com` in my case instead of the `backstage.domain.com`

### What you expected to happen
as said, the cookie from the cookie collection belonging to the domain `backstage.domain.com` should be copied or remained and not overwritten with a cookie with the same name from the other domain.

This can easily be done by placing the cookie injecting after the change of URI in the code:
[Cake\Http\Client](https://github.com/cakephp/cakephp/blob/master/src/Http/Client.php#L417)
```
public function send(Request $request, $options = [])
    {
      ...
            if ($handleRedirect) {
                $url = $request->getUri();
                $request = $this->_cookies->addToRequest($request, []);
                $location = $response->getHeaderLine('Location');
                $locationUrl = $this->buildUrl($location, [], [
                    'host' => $url->getHost(),
                    'port' => $url->getPort(),
                    'scheme' => $url->getScheme(),
                    'protocolRelative' => true
                ]);
                $request = $request->withUri(new Uri($locationUrl));
            }
    ....
    }
```

to 
```
public function send(Request $request, $options = [])
    {
      ...
            if ($handleRedirect) {
                $url = $request->getUri();
                
                $location = $response->getHeaderLine('Location');
                $locationUrl = $this->buildUrl($location, [], [
                    'host' => $url->getHost(),
                    'port' => $url->getPort(),
                    'scheme' => $url->getScheme(),
                    'protocolRelative' => true
                ]);
                $request = $request->withUri(new Uri($locationUrl));

                $request = $this->_cookies->addToRequest($request, []);
            }
    ....
    }
```

**Comment by markstory** [comment]
Thanks for the suggested changes. I will see if I can reproduce the issue you are having.
