### ISSUE TITLE
3.next/4.0: Split getter/setter TODO

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13559]
We have a few more that we didnt find and fix yet in terms of clean API:

ConsoleOutput:

- [x] public function styles(?string $style = null, $definition = null) {}

The API here is especially wacky in terms of true/false input/output mixed in to allow removing :)

RequestHandlerComponent

- [ ] accepts()
- [ ] requestedWith()

etc

**Comment by ADmad** [comment]
`RequestHandlerComponent` as a whole is a bit wacky and it's code is quite difficult to walk through.

**Comment by dereuromark** [comment]
Closing then as good enough for now.
