### ISSUE TITLE
Use `UploadedFileInterface` objects in request data.

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#13554]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

---

#9407 introduced `UploadedFileInterface` objects to the server request, but for backwards compatibility reasons, it had to keep the array style in the request data.

I think it would be nice if at some point having objects instead of arrays in the request data would be the default, IMHO it's way more comfortable to work with. However, such a hard break is hard to sell of course, so how about introducing it stepwise, making it optional and disabled by default at first?

In my personal projects I've usually used a custom middleware that merges the upload objects into the request data, it's simple and works fine, but introducing a middleware for handling file uploads in the core, probably isn't the best way to solve this.

So I'd like to propose a configuration option approach that could be used by the request factory. `ServerRequestFactory::fromGlobals()` already reads the session config, so this wouldn't introduce any new dependencies.

* [ ] The feature could be introduced immediately,
* [ ] then made the default (in the application template) at some point,

and in case the old behavior should be dropped later on,

* [ ] there could possibly a phase of deprecation next,
* [ ] until it could finally be made the default behavior of the `ServerRequest` class, dropping the configuration option.

**Comment by ADmad** [comment]
We can add the feature as opt-in in 3.9 and then make it default in 4.0 with the ability to opt-out for those upgrading from 3.x.

**Comment by markstory** [comment]
@ADmad Do you mean to default the configuration flag to on for new applications in 4.0? We should allow folks upgrading a smooth path where they can retain the old behavior for a while.

**Comment by ADmad** [comment]
@markstory Yes I meant default to `on` for new 4.0 applications. New users / applications shouldn't have to bear the burden of legacy. How to maintain old behaviour can be documented in migration guide.
