### ISSUE TITLE
Stopping the Model.afterSave event should abort the pending transaction

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#13573]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
Call `$event->stopPropagation` at `afterSave` event

### What happened
Save function is not stopped

### What you expected to happen
Cancel save and rollback DB

**Comment by garas** [comment]
[Events list](https://book.cakephp.org/3.0/en/orm/table-objects.html#lifecycle-callbacks) has information whether they can be stopped.

`afterSave` currently doesn't check if it was stopped. Try `beforeSave` if possible.

**Comment by markstory** [comment]
This isn't a bug, this is how the afterSave event has always worked. Changing the behavior would be a breaking change.

**Comment by PhantomWatson** [comment]
Even if this were suggested as a new feature, this sounds like a large undertaking that not many developers would (or should) find themselves in need of. This seems more like a situation that calls for an "undo" plugin that maintains a table of database transaction history.

**Comment by mcsknp** [comment]
Please re-open this.

**Comment by othercorey** [comment]
@mcsknp Can you provide a use case?

**Comment by mcsknp** [comment]
When I create an image of item, I using item's id in image name.
Item id is identity so it can be get only after save, but an error occurred when saving image, so I need to rollback saved item.
Other case is an behavior to save additional information after save but an error occurred in `afterSave` event.

**Comment by saeideng** [comment]
you can use `transactional()` for all these cases
```php
//model
$this->getConnection()->transactional(function () ) {
    if($this->save($entity)){
        //create image
        //an error when creating image ?
        //then return false
    }
});
```
use `afterSave()` when you are sure that save process successfully finished
and you dont need to a rollback

**Comment by mcsknp** [comment]
@saeideng What is difference between `afterSave` and `afterSaveCommit`?

Isn't it below reason:
- `afterSave`: process that require rollback on error
- `afterSaveCommit`: process doesn't require rollback

**Comment by saeideng** [comment]
> What is difference between afterSave and afterSaveCommit?

assume you have several entities for saving 
`afterSave` calls after each save (before `commit` ) `afterSaveCommit` calls after `commit` query (when all entities saved)

**Comment by mcsknp** [comment]
@saeideng What is difference in use case?

> assume you have several entities for saving
> `afterSave` calls after each save (before `commit` ) `afterSaveCommit` calls after `commit` query (when all entities saved)

Are you mentioning `saveMany` function?
As I know, `afterSaveCommit` will not be dispatched in `saveMany`

And as you mentioned at https://github.com/cakephp/cakephp/issues/13573#issuecomment-644515190

> you can use transactional() for all these cases

How to use behavior for adding same process for many table at `afterSave`

**Comment by saeideng** [comment]
> Are you mentioning saveMany function?

`save` method , when there is an entity with several relations

> Other case is a behavior to save additional information after save but an error occurred in afterSave event.

> How to use behavior for adding same process for many table at afterSave

```php
//model
$this->getConnection()->transactional(function () ) {
    if($this->save($entity)){
        //create image
        //an error when creating image ?
        //then return false
    }
     //call behavior's method
     if(!$this->MyBehaviorName->addMoreInfo($data)){
          return false;//to ignore save process
      }
});
```

join to support community if you need more help

**Comment by mcsknp** [comment]
You must write same code in many table class. Is that good solution?
Why cakephp doesn't check status of `afterSave` event?

**Comment by saeideng** [comment]
> You must write same code in many table class. Is that good solution?

no , why?

you can have a new layer as service and put these code into it when you want to code between several models/ behaviors ,  or make new behavior to handle them , depends to your strategy 

more info: https://github.com/burzum/cakephp-service-layer

---- 

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by mcsknp** [comment]
Firstly I thought that is a bug, but as @markstory mentioned, cakephp is not covering this case.
So I request a feature to cover that because it's very common scenario.
