### ISSUE TITLE
Dispatch event after saveMany commited

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#13574]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

There are no event dispatched after `saveMany` function processed

**Comment by markstory** [comment]
Each record that is saved will emit saved events. What would you use this event for that you can't accomplish today?

**Comment by mcsknp** [comment]
I want to save updated history after saveMany.
Now I'm using afterSave but its look like slowly so I want to save many at one query.

**Comment by markstory** [comment]
>  Now I'm using afterSaveCommit but its look like slowly so I want to save many at one query.

What makes you think afterSaveCommit is slow?

**Comment by mcsknp** [comment]
Table's rows count is being increased and insert query is becoming slowly.
So I think insert many rows at one time is faster than insert at each `afterSaveCommit`.

**Comment by markstory** [comment]
Interesting, as `saveMany()` is a simple loop around multiple `save()` calls inside a single transaction. It doesn't use a bulk insert at the database level.
