### ISSUE TITLE
RFC: Generate URLs using compact action name

### ISSUE THREAD

**Issue by garas** [cakephp/cakephp#13570]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8

### Current state

Since 3.6.0, route builder supports specifying target in `[Plugin].[Prefix]/[Controller]::[action]` compact string format
```php
$routes->connect('/admin/cms/articles', 'Cms.Admin/Articles::index');
```

To generate to such URL, it still necessary to use expanded array
```php
Router::url(['prefix' => 'admin', 'plugin' => 'Cms', 'controller' => 'Articles', 'action' => 'index']);
```

Some keys can be skipped and determined from current request context.

But it can generate unexpected URLs. Ex. same email template generates different URL for `['controller' => 'Articles', 'action' => 'index']` when sent from frontend and admin backend, and all links must have `'prefix' => false` to avoid this.

There is also problem locating all links to the action when renaming/removing action. `'action' => 'index'` without prefix/plugin/controller might mean this or another controller and requires extra thinking.

Option `_name` helps to shorten, but it needs to be explicitly specified when connecting. It also often just duplicates target action.
```php
$routes->connect('/admin/cms/articles', 'Cms.Admin/Articles::index', ['_name' => 'cms:admin:articles:index']);

Router::url(['_name' => 'cms:admin:articles:index']);
```

### Suggestion
I suggest to extend `action` key functionality and allow specifying everything using same `[Plugin].[Prefix]/[Controller]::[action]` format.
```php
Router::url(['action' => 'Cms.Admin/Articles::index']);
```

Internally, if `action` contains `::`, first expand `['action' => 'Cms.Admin/Articles::index', ...]` to full `['prefix' => 'admin', 'plugin' => 'Cms', 'controller' => 'Articles', 'action' => 'index', ...]`, then continue as usually.

It should fail (throw exception) if prefix, plugin or controller specified too.

It would be always absolute, i.e. `['action' => 'Articles::index']` would mean `['prefix' => false, 'plugin' => null, 'controller' => 'Articles', 'action' => 'index']` even if used in prefix or plugin context.

It would let avoid specifying `_name` in most cases, it would avoid relative route array ambiguity, and it would be in single canonical searchable form.

### Further possibilities

It could be also just plain string `Router::url('Cms.Admin/Articles::index')`. It is enough specific format to distinguish, but it might be too ambiguous to plain URLs strings, so I do not suggest that for now.

`$routes->connect()` could internally use same expansion too:
```php
$routes->connect('/admin/cms/articles', 'Cms.Admin/Articles::index');
// same as 
$routes->connect('/admin/cms/articles', ['action' => 'Cms.Admin/Articles::index']);
// or 
$routes->connect('/admin/cms/articles', ['prefix' => 'admin', 'plugin' => 'Cms', 'controller' => 'Articles', 'action' => 'index']);


$routes->connect('/about-us', ['action' => 'Cms.Pages::display', 'about']);
// same as 
$routes->connect('/about-us', ['plugin' => 'Cms', 'controller' => 'Pages', 'action' => 'display', 'about']);
```

**Comment by dereuromark** [comment]
Sounds like a good idea to me. Also fully BC it seems. :+1: 
People who want to retain the defaulting (like me) when not specifying the plugin/prefix can continue to use the array way.

**Comment by ADmad** [comment]
Sounds good to me too. Just instead of overloading the `action` key we could instead use a new special key like `_path`.

**Comment by dereuromark** [comment]
I agree. Overloading means you always need to strpos check on the action content. Otherwise a simple isset() on that key would suffice.

**Comment by markstory** [comment]
I like the idea of making URL generation simpler.

Would generating route names be another way to solve this problem? For routes using the compact action name we could inflect/generate a `_name` if one was not provided enabling URL generation to using existing features.

Other things to consider with a new compact syntax is how it might interact with pagination and how do we provide helpful errors when users make a syntax error.

**Comment by dereuromark** [comment]
PR open.
