### ISSUE TITLE
Session handlers silently ignore errors that occur during session write

### ISSUE THREAD

**Issue by sukihub** [cakephp/cakephp#13581]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6 (but master still seems to have this).
* Platform and Target: Apache & mod_php, but all are probably affected (I replicated it on Nginx & php cgi).

### What you did
We use Cake's `DatabaseSession`. A bug in the application code caused an exception during session write. DatabaseSession uses ORM's tables and entities, so this can easily happen.

### What happened
Obviously, the session did not get written. But no error was emitted which made the problem incredibly difficult to find. Also, all the requests were finishing correctly, with 2xx responses, etc. The only visible symptom was that session sometimes did not get written.

I think this might be because of `session_write_close()` being called/registered as a shutdown function (`session_register_shutdown()` does that). There's not much that PHP can do if shutdown handler throws an exception. Yet it would be very helpful if the error was somehow reported.

### What you expected to happen
Since both `DatabaseSession` and `CacheSession` perform some non-trivial tasks during session write, I would expect my app to crash if session write fails.

Even though PHP itself cannot do much about errors in shutdown functions, CakePHP (as a provider of some session handler implementations) can.

One solution I propose is wrapping session handler's write method in a try catch:
```php
public function write($id, $data)
{
    try {
        return parent::write($id, $data); // or original implementation of write
    } catch (Throwable $exception) {
        Log::error($exception);
        return false;
    }
}
```
This solution does not make the app crash if session write fails, but at least it reports the error correctly into a log.

Actually crashing an application might not be possible as long as `session_write_close()` is being called as a shutdown function. Which seems to be the preferred way of doing it in newer PHPs. But I also tested calling `session_write_close()` manually, earlier in the request cycle and error was correctly reported. So that's option no. 2.

**Comment by markstory** [comment]
Throwing an exception on write failure is something we can add, but for the reasons you've outlined it might not work in all scenarios. Logging directly from the session adds additional cross package dependencies and might not be what all users want, whereas an exception can be caught and converted into logs, or sent to an upstream for collection.

**Comment by sukihub** [comment]
The exception already gets thrown on write failure (probably, most of the time), doesn't it?

I see what you're saying with cross package dependencies. But exceptions in shutdown functions are silently ignored, so this will solve nothing.

**Comment by markstory** [comment]
> But exceptions in shutdown functions are silently ignored, so this will solve nothing.

What if we wrote/closed the session from inside the `ResponseEmitter`? That class currently closes the session before shutdown when the server is using fastcgi, doing it all the time could help fix this issue.

**Comment by sukihub** [comment]
Sure, sounds to me like the best option (the error gets logged and user receives error) 👍 

I'm however a bit confused by warnings here in the official docs: https://www.php.net/manual/en/function.session-set-save-handler.php#refsect1-function.session-set-save-handler-notes

If I understand it correctly (from very limited information provided in the link above), closing session in the `ResponseEmitter` might be possible, but it could be a breaking change, since some apps may depend on the session later in a request cycle (they mention object destructors).

**Comment by sukihub** [comment]
> But exceptions in shutdown functions are silently ignored, so this will solve nothing.

I take this back. Exceptions are ignored, but when accompanied by `return false;` in `SessionHandlerInterface::write` PHP (apache, mod_php) reports this error: `Warning (2): session_write_close(): Failed to write session data using user defined save handler. (session.save_path: tcp://10.80.25.10:6379?database=1) in [Unknown, line 0]`

At least it's something, but the cause of the original issue (exception) is still lost, so not ideal.

**Comment by markstory** [comment]
> If I understand it correctly (from very limited information provided in the link above), closing session in the ResponseEmitter might be possible, but it could be a breaking change, since some apps may depend on the session later in a request cycle (they mention object destructors).

There isn't much of a request cycle after the `ResponseEmitter` sends the response. I agree there could be potential risk, but we can use 3.9 or 4.0 to change this behavior and document the change as it doesn't modify any methods or public properties.

**Comment by othercorey** [comment]
@sukihub If you want to make a PR for 4.0, now is the time.

**Comment by sukihub** [comment]
@othercorey thanks for the heads up. I will try. Is there a (recommended) deadline?

And to recap:
1. we agreed to manually call [session_write_close](https://www.php.net/manual/en/function.session-write-close.php) in `ResponseEmitter` 
2. probably before a call to `fastcgi_finish_request` - can anybody confirm this? 
3. and remove a call to `session_register_shutdown` from `Session`

**Comment by othercorey** [comment]
You should make it as soon as possible as we are at RC2.

That sounds like the changes discussed.  We can confirm in the PR.

**Comment by sukihub** [comment]
So, I looked into it and I wanted to discuss one more thing before submitting a PR.

I figured it would be nice to use Cake's `Session` object and `Session::close` method - which calls `session_write_close` (it would help with the tests). `ResponseEmitter` does not however have access to `Session` instance - it only gets the response object.

The last place with `Session` instance available, to my knowledge, is the end of `Server::run`. The same method also created the `Session` instance (in `ServerRequestFactory::fromGlobals`) so I figure it would be nice if it also closed the session.

What I'm proposing is that we call `Session::close` - and `session_write_close` - as the last thing in `Server::run`, instead of calling it in `ResponseEmitter`. Would you be OK with that? 

There might be 1 possible issue. If it is possible for a `ResponseEmitter` to somehow call some application code (callback or something, that generates body), that depends on the session, the code would break. To me, this sounds like something that people should not be doing, but what do I know ... :)

The alternative solution is to send `Session` or `Request` instance as a patameter to `ResponseEmitter` and call `Session::close` there, as originally discussed. Just to make its dependency on session subsystem explicit.

So, which option sounds better - `Server::run` or `ResponseEmitter`?

**Comment by markstory** [comment]
I think `Server::run()` is fine.

> and remove a call to session_register_shutdown from Session

This could impact people who use the framework in unconventional ways. For example calling exit() from a controller action or not using the ErrorHandlerMiddleware and relying on the default exception handler to render error pages.

If the we are closing the session  in Server::run() do we need to remove the session shutdown function? Wouldn't it be a noop most of the time?

**Comment by sukihub** [comment]
> For example calling exit() from a controller action

At first I agreed. On second thought though, I don't. If you call exit from anywhere, you should not expect your session to be saved. That also applies for exceptions.

I'd even argue, that the session may not get saved when some php internal `Error` that is not `Throwable` occurs.

**Comment by markstory** [comment]
If you are using the error middleware, then yes the session would be saved. Shutdown functions are also run when uncaught exceptions are raised.
