### ISSUE TITLE
Memory leak in unit tests - $fixtures property in TestCase class

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13583]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: all
* Platform and Target: all

`$fixtures` property in unit tests leaks the memory and it is not possible to unset it in `tearDown` method.
I would suggest to refactor that to a getter and to remove `$fixtures` property:
```
public function getFixtures() : array {
    return ['app.Posts', 'app.Articles'];
}
```
And in the parent TestCase it could be like this for backwards compatibility:
```
public function getFixtures() : array {
    if (isset($this->fixtures) {
        return $this->fixtures;
    }
    return [];
}
```

Other properties in TestCase class also leak memory. I think it would be useful to refactor them to getters too.

**Comment by markstory** [comment]
Adopting a method for getting the fixture list seems reasonable to me.

**Comment by dereuromark** [comment]
Are there any numbers on how much memory we are talking about here?
If you run the current (core) suite with memory profiling output and your suggested changes, how much of a difference is there?

**Comment by bancer** [comment]
In order to measure that all `public $fixture = ...;` declarations in unit tests must be replaced by `public function getFixtures() {...};` method as if `$this->fixtures` is not empty in `tearDown` method then the memory leak occurs. 10 elements array may use 300 bytes. A project with 10000 tests that use fixtures may get 30000000 bytes (28 MB) leaked. That should be multiplied by 5 for code coverage runs.

**Comment by dereuromark** [comment]
This seems to be of very little win at this point, especially during 3.x.
Would you be able to make a PR for 4.x that also makes the property protected?
That would be a double-win then for this major, as we try to make more properties non-public and at the same time the getter then allows some better memory allocation, right?

**Comment by bancer** [comment]
I can provide more specific numbers later after we apply this improvement in our 2.x code.

I can try to make 4.x PR. The memory usage of public and protected properties is the same though per my knowledge. 

The memory leaks in unit tests is a well known problem by the way. Most often cited [handling](https://kriswallsmith.net/post/18029585104/faster-phpunit) suggests to unset all properties that do not belong to 'PHPUnit_' classes. Any non-empty property in `tearDown` leaks memory whether it is public, protected or private.

**Comment by dereuromark** [comment]
The protected is more for clean code and less side effects (clean getter access).
But we can see about the rest and possible ways to improve here also in terms of memory.
