### ISSUE TITLE
4.x - Use Closure instead of callable wherever possible

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13598]
The benefits of using `Closure` instead of `callable` are mentioned [here](https://wiki.php.net/rfc/closurefromcallable#why_would_you_use_this).

The primary consideration is whether public methods which accept callables should be changed to accept closure only.

**Comment by ADmad** [comment]
This change would be especially beneficial in the db layer for methods which accept arrays as well as callable which makes type checking tricky. It would allow us to do away with methods like this:

https://github.com/cakephp/cakephp/blob/12aaeb157cc58dbb9cbc6aeba6909a9f7e7c0b6a/src/Database/Expression/QueryExpression.php#L602-L623

**Comment by markstory** [comment]
Seems like a postitive change to me. I've never really liked the `isCallable` method and requiring `Closure` prevents several potential attack vectors where we miss an `isCallable` check.

**Comment by lorenzo** [comment]
I personally don’t like this as creating invokable classes is more meaningful that passing plain closures. This would also make it a bit of a hassle for me to update many of my apps.

The benefits can be realized internally if we convert the callable to closures if we plan to invoke in loops.

**Comment by ADmad** [comment]
Done for db layer in #13620
