### ISSUE TITLE
4.x: Sqlite TypeError

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13608]
This is a (multiple allowed):

* [x] bug

4.x-dev

### What you did
Upgrading a plugin to 4.x and running phpunit.

### What happened
```
PHP Fatal error:  Uncaught TypeError: file_exists() expects parameter 1 to be a valid path, bool given in /.../vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php:69
Stack trace:
#0 /.../vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php(69): file_exists(false)
#1 /.../vendor/cakephp/cakephp/src/Database/Driver.php(165): Cake\Database\Driver\Sqlite->connect()
#2 /.../vendor/cakephp/cakephp/src/Database/Connection.php(468): Cake\Database\Driver->beginTransaction()
#3 /.../vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(69): Cake\Database\Connection->Cake\Database\{closure}()
#4 /.../vendor/cakephp/cakephp/src/Databa in /.../vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php on line 69
```

### What you expected to happen
A more meaningful message, we might want to check on the bool before we further pass it along.

**Comment by dereuromark** [comment]
I found that someway along the bootstrapping of tests, 4.x needs sth else than 3.x.

Hardcoding Sqlite::connect() to use

    $databaseExists = file_exists($config['database'] ?: 'tmp');

made the tests pass.
So I think somewhere along that stracktrace we should check on that key to be not false.

**Comment by ADmad** [comment]
How / why did you set the `database` key to `boolean`? :slightly_smiling_face:  It does have a sensible default `:memory:`.

**Comment by dereuromark** [comment]
The same way the plugin is configured and working in 3.x:
```php
// Ensure default test connection is defined
if (!getenv('db_class')) {
	putenv('db_class=Cake\Database\Driver\Sqlite');
	putenv('db_dsn=sqlite::memory:');
}
Cake\Datasource\ConnectionManager::setConfig('test', [
	'className' => 'Cake\Database\Connection',
	'driver' => getenv('db_class'),
	'dsn' => getenv('db_dsn'),
	'database' => getenv('db_database'),
	'username' => getenv('db_username'),
	'password' => getenv('db_password'),
	'timezone' => 'UTC',
	'quoteIdentifiers' => true,
	'cacheMetadata' => true,
]);
```

Somewhere along the line there is an upgrade path a bit hard to spot.

Best to bail early inside core if the values become non-valid.

**Comment by dereuromark** [comment]
Looking into other 4.x code, the 3.x:

    putenv('db_dsn=sqlite::memory:');

seems to become

    putenv('db_dsn=sqlite:///:memory:');

in 4.x now.
Can we either shim this or check and throw exception on invalid string/scheme?

**Comment by ADmad** [comment]
Perhaps the DSN string parsing code should throw exception when it can't parse the string into sensible values.

**Comment by dereuromark** [comment]
The above change itself doesn't fix it though.
Apparently the absence of the `'url'` key on that config seems to cause this.

**Comment by markstory** [comment]
If we were to guard around `file_exists()` would an error like 'Your sqlite database file path should be a string?' make sense?

**Comment by dereuromark** [comment]
The issue is more low level, when parsing dsn.
The missing url now triggers this, which shouldnt happen.

**Comment by markstory** [comment]
I don't think this issue is caused by DSN parsing at all. This issue can be reproduced with the following invalid configuration:

```php
ConnectionManager::setConfig('test', [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Sqlite',
    'database' => false,
]);
```
I think my suggestion of a guard around the `file_exists()` check is our best bet here.
