### ISSUE TITLE
4.x: Plugin path resolution for non-src

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13604]
This is a (multiple allowed):

* [x] RFC/enhancement

4.x 

### What you did

App::path() method still resolves non-src paths (no classes, but templates/locales etc).

### What you expected to happen

Mixing src path generation with other non src paths is a bit weird moving forward.
Note the mix of classPath() vs path() vs templatePath() usage inside of this wrapper now.

The cleaner strategy is to not have the App::path() being used anymore for such root folders.
We should use a different method for non class lookup IMO.

E.g.

- `App::templates(?string $plugin = null)`
- `App::locales(?string $plugin = null)`

Or we separate the App class similar to Plugin and its path() vs classPath() method:

- `App::classPath($type, ?$plugin)` for actual classes ("Model/Datasource" etc) inside src/
- `App::path($type, ?$plugin)` for the root folders (and use "templates" instead of "Template"), same for `App::path('Locale', $plugin);` using "locales" then to sync with the actual path element?

What do people think?
A clear and consistent API here would be probably quite helpful.

**Comment by dereuromark** [comment]
Related: https://github.com/cakephp/app/blob/master/config/app.default.php#L66

**Comment by ADmad** [comment]
We could add `App::templatePath()` and `App::resourcePath()`. The latter could have a `$type` or `$subfolder` as argument so `App::resourcePath('locales')` would return you path to locales. I don't think we need a method specific for locales folder path.

**Comment by ADmad** [comment]
In reference to the `app.default.php` you have linked, it's for `3.x`. Those paths updated for 4.x:

https://github.com/cakephp/app/blob/fb5fa72862f3347acf61033ba1915958bb406f3d/config/app.default.php#L66

**Comment by markstory** [comment]
> App::path() method still resolves non-src paths (no classes, but templates/locales etc).

Why is this weird? `App::path()` provides lets people use/remember fewer methods and get what they need. I could see a potential issue if folks try to create `Locale` or `Template` namespaces in their applications, but we could solve that by having the non-class keys be lowercased (`locale` and `templates`).

I don't think we need a plugin argument on any of the `App::*path` methods as we also have `Plugin::path()` and `Plugin::classPath()` to resolve paths for plugins.

Whatever changes we make to path methods on `App` we should also mirror that behavior for `Plugin` so we have consistency between both.

**Comment by dereuromark** [comment]
When working with class paths in 4.x now you need to do weird stuff like

    $paths = $plugin ? [Plugin::classPath('Controller')] : App::path('Controller');

as the classPath returns string, but path still array of strings.

I would expect to deprecate path() more, and instead use similar clean separation also on app level then, as outlined above.
It makes it also then more easy to use from API consistency level, both are then e.g. classPath().
Ideally, the app one would still have the defaulting to plugin again, as 

    App::classPath('Controller', $optionalPlugin)

is simpler to code for inside commands, when the plugin is an optional argument. Less logic needed in the controller code then.

**Comment by dereuromark** [comment]
I would still like to fix this issue up

> Notice: Deprecated (16384): Using App::path() with 2nd argument $plugin is deprecated. Use \Cake\Core\Plugin::classPath()/templatePath() instead. - /.../vendor/dereuromark/cakephp-ide-helper/src/Utility/AppPath.php, line: 18

This is not only annoying to work with, but it also makes this out of sync if you need to make code like IdeHelper, TestHelper and other plugins that should be able to easily work with any class, app or plugin level.

Can we either undeprecate or better yet move towards also
- App::className()
- App::templatePath()

here?
It would be nice synantic sugar to allow plugin param to be set in order to have less logic and noise conditionals on user land code here.
I want to easily say
```php
    $className = App::className('Foo', $pluginOrNull);
```

**Comment by dereuromark** [comment]
PR open.
