### ISSUE TITLE
Cakephp3.2 enabling debug mode on app.php(config) throws method exists error

### ISSUE THREAD

**Issue by karthikn-php** [cakephp/cakephp#13613]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.
* PHP 7.2.19-0ubuntu0.18.10.1 (cli) (built: Jun  4 2019 14:46:43) ( NTS )
* Platform and Target: Tested in Ubuntu(Linux) can support any platform.
  WEB-SERVER : APACHE2
  DATABASE : MySQL
 
### What you did
On Enabling debug mode on cakephp3.2 throws the following fatal error
Fatal Error: method_exists() [<a href='http://php.net/function.method-exists'>function.method-exists</a>]: The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Cake\I18n\FrozenTime&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition
File **/var/www/html/Sprint3.1.12/vendor/cakephp/cakephp/src/Error/Debugger.php**
Line: 543

[debugger.zip](https://github.com/cakephp/cakephp/files/3577731/debugger.zip)

**Comment by markstory** [comment]
CakePHP 3.2 is no longer supported. Could you upgrade to 3.7 or 3.8 and see if you still have this problem?

**Comment by karthikn-php** [comment]
Our product is a SaaS platform running in the cakephp3.2 version and it may take a month or more to upgrade. We are planning to upgrade 3.8 soon. I just dropped a message since i found. No issues. Thanks.
