### ISSUE TITLE
4.0.0-beta3 PHP Fatal error:  Declaration of setUp() must be compatible with Cake\TestSuite\TestCase::setUp()

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#13624]
This is a (multiple allowed):

* [] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-beta3
* Platform and Target: Ubuntu 18.04.3 LTS, PHP v7.2.21-1+ubuntu18.04.1+deb.sury.org+1

### What you did

Ran unit tests on https://github.com/cnizzardini/cakephp-yummy/tree/dev/maintenance

### What happened

> PHP Fatal error:  Declaration of Yummy\Test\TestCase\Controller\Component\YummyAclComponentTest::setUp() must be compatible with Cake\TestSuite\TestCase::setUp(): void in /var/www/personal/cakephp-yummy/tests/TestCase/Controller/Component/YummyAclComponentTest.php on line 17

### What you expected to happen

Is it expected we will have to update all of our setUp methods? If so, perhaps consider adding a deprecation warning in 3.8.* or 3.9 (if there will be a 3.9)?

**Comment by dereuromark** [comment]
This is PHPUnit related, find respective rector tasks here: https://github.com/rectorphp/rector
So this is pretty much fully automated.

**Comment by dereuromark** [comment]
If you have a PHP7+ project, you can already modify your tests in 3.x, but not all have dropped 5.6 support, as such we can't propose this more globally.

**Comment by ADmad** [comment]
Cake 4 uses phpunit 8 and you need to update your test cases accordingly to match new method signature. 

Error message tells you exactly what the problem is and how to fix it.

**Comment by beporter** [comment]
This should be mentioned in the 4.0 migration guide at least.
