### ISSUE TITLE
4.x: I18nExtractCommand outputs translations to server root folder, instead of resources/locales

### ISSUE THREAD

**Issue by mentisy** [cakephp/cakephp#13622]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x (https://github.com/cakephp/cakephp/commit/7e248eafde2b40aab1ee9ab521d6ab6f0bed8905)
* Platform and Target: Linux 2.6.32-896.16.1.lve1.4.54.el6.x86_64 #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64

### What you did
1. Ran command `bin/cake i18n extract` with the CakePHP 4.0.0-beta3 version
2. Pressed enter repeatedly to use all default values with no options set, as to extract the translation strings inside the project and Cake Core to the default output path

### What happened
Got error message from the CLI: The output directory / was not found or writable.

https://github.com/cakephp/cakephp/blob/da764a254e64791508a93b105d9a212f7590dde5/src/Command/I18nExtractCommand.php#L209-L219

1. The `hasOption('output')` (line 209) and `hasOption('plugin')` (line 211) as they exist, but is not necessarily in use. It will always return true, so will get the default output and plugin value, which is an empty string. This means the default output directory is the server's root folder.

2. If we fix the but mentioned above, and ignore empty output and plugin options, it will then extract to this directory: `src/Locale`. This is wrong with the new templates folder directory. It now resides outside the `src/` directory. This bug occurs on line 218.

### What you expected to happen
With the new directory for templates, the current default output directory should be `resources/locales`

### What I think needs to be done
Change how checking that the output and plugin option are done. Change the default output directory to match the new 4.x directory.
`resources/locales`

**Comment by mentisy** [comment]
There are two slightly correlated bugs in I18nExtractCommand, but I decided to split them.

https://github.com/cakephp/cakephp/issues/13623: 4.x: I18nExtractCommand does not extract from templates folder

There were no failing tests with the existing code, and there are none after I changed the code.

**Comment by ADmad** [comment]
Issue will be resolved by https://github.com/cakephp/cakephp/pull/13618
