### ISSUE TITLE
EmailTrait::assertEmailSentTo fails when RCPT-Name is null

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#13636]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.2
* Platform and Target: irrelavant

### What you did
- Sent an email to `["my@customer.net" => null]`
- Wrote a test using the `EmailTrait`
- Called `$this->assertEmailSentTo('my@customer.net');`

### What happened
The assertion failed.

### What you expected to happen
The assertion should have succeeded

### Why did that happen?
The `MailSentWith` constraint uses `isset($value[$other])` to check the assertion. this fails for existing array keys with a null value. `array_key_exists($other, $value)` should do the job.

https://www.php.net/manual/de/function.array-key-exists.php#example-6219

**Comment by ADmad** [comment]
Would you like to submit a patch to fix this?

**Comment by BGehrels** [comment]
I'm sorry, but it doesn't look like i'm going to get this done before my vacation, so i could fix that earliest in 3 weeks from now
