### ISSUE TITLE
cURL Get requests come across as POST

### ISSUE THREAD

**Issue by KainGNX** [cakephp/cakephp#13639]
https://github.com/cakephp/cakephp/blob/a2baa58e0150da4109313954975b6a3681cf8e86/src/Http/Client/Adapter/Curl.php#L112-L114

I have been trying to use a get request to call to another Cake API I have running in the same environment, but when using the `Cake\Http\Client::get()` method with something like `$client->get($fullUrl);` the request is received as POST no matter what causing a route mismatch in my other Cake app.

I even tried a wrapped PSR-7 request object in conjunction with `Cake\Http\Client::sendRequest()` and got the same result.

I then commented out setting `CURLOPT_POSTFIELDS` key in a brief test and it works as GET.

I was going to put in a pull request to put back the conditional around setting `CURLOPT_POSTFIELDS` that used to be there.

But wanted to ask first, was there a reason it was removed? With this change, am I missing something else to make sure the request is GET?

EDIT: If I am not mistaken, I think I get why the conditional was removed, it would likely wind up evaluating 'true` and always execute within anyway. 

Thanks in advance!

**Comment by markstory** [comment]
Thank you for the issue. Going to close this as we can continue the discussion in your pull request.
