### ISSUE TITLE
4.x: Associations generate magic class properties

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13638]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: PHP 7.3

### What you did
I was adding a `@property` docblock to my controller to document the associated table class `Audits`. However, when I discussed this with my colleagues the question turned into why are the association properties not declared in the Table class.

```php
<?php
namespace \App\Model\Table;

use \Cake\ORM\Table;

class ExamplesTable extends Table
{
    /**
     * Tags association
     * 
     * @var \App\Model\Table\TagsTable&\Cake\ORM\Association\HasMany $Tags
     */
    public $Tags;

    /**
     * Initialize the table
     * 
     * @param  array  $config Configuration options
     * @return void
     */
    public function initialize(array $config)
    {
        $this->belongsTo('Tags');
    }
}
```

### What happened
It seems that the association classes are using magic methods to access the properties, meaning that they cannot be reasoned about with any ease.

### What you expected to happen
I would expect that these classes worked similarly to `loadModel()` and dynamically added a property to my class.

### RFC
It was proposed by @ADmad that the association classes should function in a similar way to `loadModel()`.

**Comment by dereuromark** [comment]
What about the magic needed for `$this->TableOne->TableTwo->TableThree->find()` calls?
Did you account for these and similar use cases?

I am sure there is a reason why the annotations are used here, it is also a bit simpler in terms of adding/removing those, you just need the IdeHelper annotations command sync.

**Comment by ADmad** [comment]
> It was proposed by @ADmad that the association classes should function in a similar way to loadModel()

I meant that the association methods like `Table::hasOne()` etc. could assign properties like `ModelAwareTrait::loadModel()` does :)

> What about the magic needed for $this->TableOne->TableTwo->TableThree->find() calls?

Yeah that won't work, since `TableTwo` etc. are actually association class instances not `Table` instances. You can't have actual properties declared for it nor annotation (unless you have some IDE specific special sauce for the latter).

**Comment by markstory** [comment]
We didn't add association properties as we were trying to keep state contained in as few places as possible. Having two copies (one on the property and one in the AssociationCollection) creates opportunities for the data to diverge if references get disconnected.

**Comment by dereuromark** [comment]
There is nothing that can be done here at this point.
