### ISSUE TITLE
4.x - Clean up Router class.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13651]
* `Router::setRequestInfo()` and `Router::pushRequest()` essentially do the same thing with the former calling the latter internally. So one of them should be removed/deprecated.

* Required changes should be done to address this comment:

https://github.com/cakephp/cakephp/blob/3627681045acd0bb181fbe5a78df6645b69469ed/src/Routing/Router.php#L479

**Comment by ADmad** [comment]
Is maintaining a stack of requests necessary now? I believe it was only required for the new removed `requestAction` feature.

**Comment by garas** [comment]
Getters:
`popRequest` - unused,
`getRequest` used in many places.

Setters:
`setRequestContext` - used in `RoutingMiddleware`,
`pushRequest` - used in `ActionDispatcher`,
`setRequestInfo` - alias of `pushRequest`.

It should be only one setter, as calling `setRequestContext` can make `Router` out of sync between current route and current context.

Ideally setter should be named `setRequest` to match `getRequest`.

I see no need for stack, only one current request is enough.

**Comment by ADmad** [comment]
IMO there should be only `setRequestContext()` and `getRequestContext()`.

**Comment by markstory** [comment]
> Is maintaining a stack of requests necessary now? I believe it was only required for the new removed requestAction feature.

The request stack was primarily used for `requestAction()`. It could also be used to simulate edge side includes, or other features that need simulated requests. If we're not concerned with those scenarios than removing those features sounds like a good idea as they are not going to be used.

**Comment by ADmad** [comment]
The `In 4.x this should be replaced with state injected via setRequestContext` in `Router::url()` isn't easily addressable right away. 

That's because `setRequestContext()` doesn't set `controller`, `action`, 'prefix' etc. keys but `Router::url()` needs them to set defaults.

The context set by `setRequestContext()` is sufficient only in case of say current URL matching a route for `RedirectRoute`.

**Comment by markstory** [comment]
Could we shim up the request context from the request object? I would think that `pushRequest()` could generate `Router::$_requestContext` when the request is changed?

**Comment by ADmad** [comment]
`pushRequest()` already calls `setRequestContext()` currently but the latter only sets `_base`, `_port`, `_host`, `_scheme` keys to `Router::$_requestContext`. So we can change it to add additional keys too.

**Comment by ADmad** [comment]
Router currently stores reference to a complete request instance in the `Router::_requests` stack and also selective info from the current request as context in `Router::$_requestContext`.

That creates a possibility of discrepancy as the context info might not always match the data in current request's instance.

If we drop the request stack we can maintain reference to just one request instance or just maintain context info from the request instance passed to methods instead of the full request instance.

Given that request instance are immutable maintaining reference to a full instance doesn't seem right.

**Comment by markstory** [comment]
> Given that request instance are immutable maintaining reference to a full instance doesn't seem right.

We hold onto the request reference as we use it in a few places. Not storing the request in a global value will require changes in a few other parts of `Router`.

**Comment by ADmad** [comment]
Router needs the full instance to pass it to URL filters. Other than that the error handler, exception renderer, action dispatcher use `Router::getRequest()`. So I guess keeping reference to full instance is necessary.

In that case why do we need to maintain `Router::$_requestContext` separately when everything could be fetched directly from the request instance?

**Comment by markstory** [comment]
> In that case why do we need to maintain Router::$_requestContext separately when everything could be fetched directly from the request instance?

The only benefit to having `_requestContext` is not having to generate it multiple times per request. While it can be derived from the request object it is generally invariant and calling several methods each time it is used adds overhead.

**Comment by ADmad** [comment]
Okay, makes sense.

So if we were to drop the internal stack we would just need 1 method `Router::setRequest()` which would store the request instance reference as well as update `Request::$_requestContext`, instead of the current 3 methods `pushRequest()`, `setRequestInfo()` and `setRequestContext()`.

`popRequest()` would be dropped all together and `$current` argument of `getRequest()` would be removed.

**Comment by markstory** [comment]
@ADmad That makes sense to me.
