### ISSUE TITLE
Memcached - wrong expiration time when duration is set as timestamp

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13654]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: any.

### What you did
```
$config['duration'] = time() - 1;
Cache::setConfig($name, $config);
```

### What happened
The cache does not expire. Looks like expiration time is in the future instead of in the past.

It seems that [this line](https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/MemcachedEngine.php#L305) is the cause of the problem.

### What you expected to happen
> Some storage commands involve sending an expiration value (relative to an item or to an operation requested by the client) to the server. In all such cases, the actual value sent may either be Unix time (number of seconds since January 1, 1970, as an integer), or a number of seconds starting from current time. 

https://www.php.net/manual/en/memcached.expiration.php

According to that I would expect that expiration time would be 1 second in the past.

**Comment by ADmad** [comment]
Jeez, that's only wacky interpretation of expiration value. BTW why are you setting expiration value in the past instead of using `delete()` method?

**Comment by bancer** [comment]
The problem I try to solve is to disable all cache configurations except `_cake_core_` and `_cake_model_` in unit tests. 

Another use case is when it is necessary to set the expiration time greater than 30 days then a Unix timestamp can be used, f.ex. `$config['duration'] = strtottime('+40 days')`.

**Comment by garas** [comment]
You could also use `NullEngine` to disable some configurations.
