### ISSUE TITLE
TranslateBehavior joins i18n table when not necessary

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13659]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.4.
* Platform and Target: Apache, MySQL

### What you did
```
$Post = $this->Posts->find()
	->select(['id'])
	->first();
```

### What happened
The query was generated with `JOIN i18n`.

### What you expected to happen
I would expect `SELECT id FROM posts LIMIT 1` to be generated.

**Comment by garas** [comment]
It is joined when current locale is not default locale.

It is joined because:
- translated fields might used in `where`, `order` and other clauses,
- if `onlyTranslated=true`, only records having translations are returned.

It is hard to automatically distinguish whether or not translation table is used.

**Comment by bancer** [comment]
> translated fields might used in where, order and other clauses,

It is pretty clear that this is not the case in 
```
$Post = $this->Posts->find()
	->select(['id'])
	->first();
```

> if onlyTranslated=true, only records having translations are returned.

What is that? I can't find anything about that in the cookbook.

**Comment by garas** [comment]
Cookbook has incomplete info. All options can be found in class itself https://api.cakephp.org/3.8/class-Cake.ORM.Behavior.TranslateBehavior.html#$_defaultConfig.

With `onlyTranslated=true`, post is translated only if it has translation in `i18n`. With `false` (default), it takes values from `posts` table if there is no translation in `i18n`.

**Comment by bancer** [comment]
Is it not possible to check the value of `onlyTranslated` when `SELECT` is generated?

**Comment by othercorey** [comment]
Closing as there is no planned change for this.
