### ISSUE TITLE
find('list', $options) fetches more fields than required

### ISSUE THREAD

**Issue by IonutBurlacu** [cakephp/cakephp#13658]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: Windows 10, Nginx, PHP 7.1

### What you did
I have the following code:
```
$options = [
	'keyField' => 'country.id',
	'valueField' => 'country.name',
];
return $this->Restaurant->find('list', $options)
	->distinct(true)
	->where(['Restaurant.status_id IN' => Status::$activeStatuses])
	->contain(['Country'])
	->order(['Country.name' => 'ASC'])
	->toArray();
```
Which generates the following SQL query:
```
SELECT DISTINCT `Restaurant`.`id` AS `Restaurant__id`, `Restaurant`.`type_id` AS `Restaurant__type_id`, `Restaurant`.`country_id` AS `Restaurant__country_id`, `Restaurant`.`status_id` AS `Restaurant__status_id`, `Restaurant`.`group_id` AS `Restaurant__group_id`, `Restaurant`.`parent_id` AS `Restaurant__parent_id`, `Restaurant`.`timezone` AS `Restaurant__timezone`, `Restaurant`.`currency_id` AS `Restaurant__currency_id`, `Restaurant`.`language_id` AS `Restaurant__language_id`, `Restaurant`.`communication_language_id` AS `Restaurant__communication_language_id`, `Restaurant`.`name` AS `Restaurant__name`, `Restaurant`.`address` AS `Restaurant__address`, `Restaurant`.`zip_code` AS `Restaurant__zip_code`, `Restaurant`.`city` AS `Restaurant__city`, `Restaurant`.`email` AS `Restaurant__email`, `Restaurant`.`phone` AS `Restaurant__phone`, `Restaurant`.`latitude` AS `Restaurant__latitude`, `Restaurant`.`longitude` AS `Restaurant__longitude`, `Restaurant`.`homepage` AS `Restaurant__homepage`, `Restaurant`.`no_portal_show` AS `Restaurant__no_portal_show`, `Restaurant`.`concurrent_users` AS `Restaurant__concurrent_users`, `Restaurant`.`sms_sender_name` AS `Restaurant__sms_sender_name`, `Restaurant`.`shared_customers` AS `Restaurant__shared_customers`, `Restaurant`.`vat` AS `Restaurant__vat`, `Restaurant`.`vatp` AS `Restaurant__vatp`, `Restaurant`.`area_id` AS `Restaurant__area_id`, `Restaurant`.`price` AS `Restaurant__price`, `Restaurant`.`tags` AS `Restaurant__tags`, `Restaurant`.`accountid` AS `Restaurant__accountid`, `Restaurant`.`app_type` AS `Restaurant__app_type`, `Restaurant`.`insideview` AS `Restaurant__insideview`, `Restaurant`.`politikenid` AS `Restaurant__politikenid`, `Restaurant`.`invoice_startdate` AS `Restaurant__invoice_startdate`, `Restaurant`.`facebookid` AS `Restaurant__facebookid`, `Restaurant`.`googleplaceid` AS `Restaurant__googleplaceid`, `Restaurant`.`account_id` AS `Restaurant__account_id`, `Restaurant`.`menulink` AS `Restaurant__menulink`, `Restaurant`.`retention_period` AS `Restaurant__retention_period`, `Restaurant`.`created` AS `Restaurant__created`, `Restaurant`.`modified` AS `Restaurant__modified`, `Restaurant`.`modified_by` AS `Restaurant__modified_by`, `Restaurant`.`created_by` AS `Restaurant__created_by`, `Restaurant`.`score` AS `Restaurant__score`, `Restaurant`.`has_reviews` AS `Restaurant__has_reviews`, `Restaurant`.`total_reviews` AS `Restaurant__total_reviews`, `Country`.`id` AS `Country__id`, `Country`.`name` AS `Country__name`, `Country`.`code` AS `Country__code`, `Country`.`phone` AS `Country__phone`, `Country`.`main` AS `Country__main`, `Country`.`zipcode_optional` AS `Country__zipcode_optional`, `Country`.`currency_id` AS `Country__currency_id`, `Restaurant_description_translation`.`id` AS `Restaurant_description_translation__id`, `Restaurant_description_translation`.`locale` AS `Restaurant_description_translation__locale`, `Restaurant_description_translation`.`model` AS `Restaurant_description_translation__model`, `Restaurant_description_translation`.`foreign_key` AS `Restaurant_description_translation__foreign_key`, `Restaurant_description_translation`.`field` AS `Restaurant_description_translation__field`, `Restaurant_description_translation`.`content` AS `Restaurant_description_translation__content`
FROM `restaurants` `Restaurant`
LEFT JOIN `countries` `Country` ON `Country`.`id` = (`Restaurant`.`country_id`)
LEFT JOIN `i18n` `Restaurant_description_translation` ON (`Restaurant_description_translation`.`model` = 'Restaurant' AND `Restaurant_description_translation`.`field` = 'description' AND `Restaurant_description_translation`.`locale` = 'en-US' AND `Restaurant`.`id` = (`Restaurant_description_translation`.`foreign_key`))
WHERE `Restaurant`.`status_id` IN (1,8,9,10)
ORDER BY `Country`.`name` ASC
```

### What happened
It seems that if you don't provide the `select(['Country.id', 'Country.name'])` call, it fetches all the fields that are present in the database tables.

### What you expected to happen
It should select only the fields that are mentioned inside `$options` array.

**Comment by dereuromark** [comment]
Currently, you could also use a custom key and value field of virtual combination, or alike.
As such the query itself doesn't know for sure which fields are required - unless you specify them.
I am not sure if this performance improvement should be hardcoded in the way you propose.

**Comment by bancer** [comment]
> As such the query itself doesn't know for sure which fields are required - unless you specify them.

Aren't they specified in `$options`?

```
$options = [
	'keyField' => 'country.id',
	'valueField' => 'country.name',
];
```

**Comment by jimbo2150** [comment]
It can be a performance issue. For example, lets say there is a `country.description` field that contains 5000+ characters per row (maybe even a large `restaurant.description` field). Querying for, sending it all back to the web server (sending large result set data containing the description fields across the network), having PHP parse the data (it still has to parse the large strings even if they are then discarded by the app) when all you expect are the `country.id` and `country.name` field is a very big performance hit.

If there were a way to do multiple queries (list x fields then do a select of y fields) from the same query I would say it should be left the way it is - but I don't think that is possible (correct me if I'm wrong).
Otherwise, I agree with @bancer : a list action indicating a key and value should only query for those fields. It seems redundant to have to add a `select` in this case:

```
$options = [
	'keyField' => 'country.id',
	'valueField' => 'country.name',
];
$this->Restaurant->find('list', $options)
        ->distinct(true)
        ->select([ $options['keyField'], $options['valueField'] ]);
	->where(['Restaurant.status_id IN' => Status::$activeStatuses])
	->contain(['Country'])
	->order(['Country.name' => 'ASC'])
	->toArray();
```

@dereuromark - Additionally, I believe the virtual fields are processed after the data is received and would do nothing to the query sent to the database.

**Comment by dereuromark** [comment]
With virtual fields I meant mainly custom fields as in sql() snippets for aggregation or alike.

While I agree with you for trivial, cases, you also need to consider the presence of e.g. "groupField" config and alike.

So if only key and value is configured, and no custom select() fields have been set, we could auto-use the two fields. With a join, and custom join fields included, we also have to careful again to not exclude too much.

Refs https://github.com/cakephp/cakephp/pull/6434

**Comment by ADmad** [comment]
The list finder already does try and optimize the selects when it's absolutely sure that no other fields are required. For other cases explicitly select the fields yourself.

Refs #6434
Duplicate #6186
