### ISSUE TITLE
SecurityComponent problem in generating token hash

### ISSUE THREAD

**Issue by ictgtvt** [cakephp/cakephp#13652]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: PHP 7.3

### What you did
I open 2 forms **at the same time in 2 tabs**:
- 1st Form: Change user last name, first name
- 2nd Form: Change password

### What happened
- I submit 1st Form and run `$this->Auth->setUser($newUserInfoFromDB)` to update user info in session.
- I clicked submit on 2nd Form => The request will be sent to black-hole

### What you expected to happen
- The request of 2nd Form have to work normally.

### Problem I found:
https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/SecurityComponent.php#L391-L395

```php
return [
    Router::url($request->getRequestTarget()),
    serialize($fieldList),
    $unlocked,
    $session->id() // Problem came from here after running $this->Auth->setUser()
];
```

This is from Cakephp 3.4.14
https://github.com/cakephp/cakephp/blob/3.4.14/src/Controller/Component/SecurityComponent.php#L381-L385

```php
return [
    $controller->request->here(),
    serialize($fieldList),
    $unlocked,
    Security::salt() // Not $session->id() in Cakephp 3.8
];
```

### Another case to consider:
- Only 1 page with 1 ajax form, 1 normal form. Submitting ajax form and run `$this->Auth->setUser()` will cause the normal form be sent to black-hole

**Comment by ADmad** [comment]
As per security best practices the session id is regenerated when user credentials are saved in session (when you call AuthComponent::setUser()), there by invalidating the earlier session id and token generated by security component.

So the behavior you are seeing is expected. I don't see a way to avoid this as someone allowing the previous security token to be accepted even after session id is regenerated would negate the benefits of session id regeneration.

**Comment by ADmad** [comment]
The switch to using session id in security token was done in https://github.com/cakephp/cakephp/pull/11151.

The use case you are expecting to work can lead to privilege escalation issue as you want to allow a token created for an unauthenticated user to be valid even after authentication.

**Comment by ictgtvt** [comment]
@ADmad 
I appreciate your detailed explanation. Many thanks.

**Comment by ADmad** [comment]
@ictgtvt The flow you have mentioned above is different than the issue you have described in your initial post. This flow this be working without issue.

In your original post you are POSTing a form with security token that was created before the session id was regenerated and that expectedly gets blocked.

**Comment by ADmad** [comment]
Sorry I misread your last comment. 

You are saying that the session id should not be generated when updating user info after login. That sounds reasonable but the problem is we don't whether non critical fields like first name, last name where updated or important field like group id or password was updated. Whenever any fields related to privileges the user has are updated ideally the session id should be regenerated.

**Comment by ictgtvt** [comment]
@ADmad yes, that's right. Is it possible to change `AuthComponent::setUser()` like this:

```php
AuthComponent::setUser($user, $renewSessionId = true)
```

**Comment by ADmad** [comment]
Well `AuthComponent::setUser()` internally calls `StorageInterface::write()` so the interface methods and all it's implementations would have to be updated too.

Instead you can just directly use `request->getSession()->write()` to update user data in session if the session id regeneration is an issue for you. `AuthComponent` and related classes are deprecated in 4.0 so it's best not to make updates to it now in 3.x.

**Comment by ictgtvt** [comment]
@ADmad I see. I think using `request->getSession()->write()` in my case is a good solution. Thanks.
