### ISSUE TITLE
Entity patching: Derive accessible from validation rules

### ISSUE THREAD

**Issue by raul338** [cakephp/cakephp#13660]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.4
* Platform and Target: All

### What you did
Have an Entity with accessible set and a validation.
```php
class Article extends Entity
{
    public $accessible = [
        'name' => true,
        'published' => true,
    ];
}

public class ArticlesTable extends Table
{
    public function validationDefault(Validator $validator)
    {
        $validator
            ->scalar('name')
            ->notEmpty('name')
            ->requirePresence('name');

        return $validator;
    }
}

$entity = $this->Articles->newEntity(['name' => 'A', 'published' => true]);
```

### What happened
`$entity->published` is dirty with a true value.

### What you expected to happen
Have a option to set accessible from the validator used, without having to duplicate fields names.
Currently I have to do:
```php
$entity = $this->Articles->newEntity(['name' => 'A', 'published' => true], [
    'accessible' => ['published' => false],
    // or...
    'fields' => ['name'],
]);
```

### How could it be
```php
$entity = $this->Articles->newEntity(['name' => 'A', 'published' => true], [
    'validate' => 'default',
    'fields' => 'fromValidator', // maybe another key
]);
```

My use case is that I have an entity with fields that each should be empty until it reaches certain state. A patch for state2 should not allow any field of state3 to be assigned.

Also this would allow to have an empty accessible (or not declare it at all) and use the validation to set values.

**Comment by markstory** [comment]
Another way to approach this is to add validator methods to constrain the field set. That would allow the validator to fail validation if disallowed fields are present.

```php
public function validationStepThree(Validator $validator)
{
  // Add rules
  // Fail validation if fields other than name, and otherField are provided.
  return $validator->onlyAccept(['name', 'otherField']);
}
```

The name `onlyAccept` is not great but gets the gist of what I am thinking across.

**Comment by raul338** [comment]
Sure, that can work too.

I was thinking more of a whitelist than fail the whole validation. Maybe could both be added?

**Comment by markstory** [comment]
Controlling the accessible fieldset from the validator can work too. I don't think we need both systems though as `SecurityComponent` could be used to fail requests that have added fields in web forms and I don't think failing on additional parameters is good pattern for API based applications.

**Comment by raul338** [comment]
> Controlling the accessible fieldset from the validator can work too

Yes, maybe a rule `ignoreUnvalidated()` or `patchKnownFields()` and then merge `$validator->getIterator()` with `$options['fields']` [in Marshaller](https://api.cakephp.org/3.8/source-class-Cake.ORM.Marshaller.html#600). If it is ok I can try and open a PR

> as SecurityComponent could be used to fail requests that have added fields in web forms

I never used SecurityComponent before, but sounds ok, though maybe I could not open a PR for that.

**Comment by inoas** [comment]
Isnt this a consequence of having non relational validation (e.g. stuff like unique, fk references) in the table rather thant he entity where it should belong?

**Comment by markstory** [comment]
@inoas No I think is a consequence of having multiple forms that mutate different parts of the same model and not wanting to duplicate fieldsets.

**Comment by inoas** [comment]
Wouldn't that problem also vanish if the same table supported 1:n entities and all the validation concerning just syntax and state that is encapsulated within the entity (say password vs password_confirm) would be validated there.

I have had a pain with multi step wizards and different validators and would have loved to have multiple partial entities that are all valid and then are just combined for the final save including all the validation rules within those.

**Comment by ADmad** [comment]
I don't like the idea of increasing coupling between entities and validator. As is it lot of people don't realize that validation is done on the request data, not entity properties. That fact that patching an entity triggers validation is just a convenience.

> I have had a pain with multi step wizards and different validators and would have loved to have multiple partial entities that are all valid and then are just combined for the final save including all the validation rules within those.

For such use case you should use `Form` objects with related validations and create entity after all steps are complete.

**Comment by raul338** [comment]
> Wouldn't that problem also vanish if the same table supported 1:n entities and all the validation concerning just syntax and state that is encapsulated within the entity

True, It is better, in my case I don't see it necessary since its only data and the only validators are string/integer and requirePrecense on each step on 17 columns..

I took the idea from a coworkers that use laravel use a code like this:
```php
public function update(Request $request, $id) {
    $validator = Validator::make($request->all(), [
        // some rules...
    ]);
    if ($validator->fails()) { /* ... */ }

    $article = Articles::find($id);
    // "strict" patchEntity
    $article->fill($validator->validated() + [
        // ... extra default data
    ]);
    // call save and return response
}
```

At the end, $article would have dirty only what was specified in the validator. Unlike the example in this issue.
I want to achieve the same using cakephp, AFAIK right now is not possible without a hack like this

```php
$fields = array_keys(iterator_to_array($this->Articles->getValidator('stepA')->getIterator()));
$entity = $this->Articles->newEntity(['name' => 'A', 'published' => true], [
    'validate' => 'stepA',
    'fields' => $fields,
]);
```

**Comment by raul338** [comment]
Will there be any discussion about this?
Should I close this?
