### ISSUE TITLE
Translate behavior sets `dirty` on contained property if the parent doesn't have the behavior

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#13666]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.4
* Platform and Target: PHP7.2.21

### What you did
To use an example from core unit tests, Articles belongs to Authors. Add Translate behavior to Authors, but not Articles. (Assume that in the actual use case, there's nothing worth translating in Articles.) Load an Article (or Articles; it doesn't seem to matter if you use `find` or `get`), containing Authors.

### What happened
The Article entity has the author property flagged as dirty.

### What you expected to happen
The author property should not be flagged as dirty.

If Articles has the Translate behavior on it, or if neither Articles nor Authors does, or if you use `loadInto` instead of `contain`, the author property is correctly not flagged.

This can be easily replicated in the core tests by commenting out `$table->addBehavior('Translate', ['fields' => ['title', 'body']]);` (and therefore also `$table->setLocale('eng');`) in `Cake\Test\TestCase\ORM\Behavior\TranslateBehaviorTest::testFindSingleLocaleBelongstoLoadInto`.

**Comment by Zuluru** [comment]
Note, I have only tested this so far on the `belongsTo` association. Not sure if it affects others.

**Comment by Zuluru** [comment]
I've done a little more digging into this, and found the following. Hopefully, it helps someone to track down and resolve the issue; I don't know nearly enough about ORM internals to fix it.

I looked at where `setDirty` is being called from. In the case where the error occurs, the call stack looks like this:

```
Table.php:1624, App\Model\Table\GamesTable->get()
QueryTrait.php:483, Cake\ORM\Query->firstOrFail()
QueryTrait.php:472, Cake\ORM\Query->first()
CollectionTrait.php:386, Cake\Datasource\ResultSetDecorator->first()
CollectionTrait.php:386, LimitIterator->rewind()
CollectionTrait.php:386, Cake\Datasource\ResultSetDecorator->rewind()
BufferedIterator.php:112, Cake\Collection\Iterator\BufferedIterator->rewind()
BufferedIterator.php:112, Cake\Collection\Iterator\BufferedIterator->rewind()
BufferedIterator.php:112, Cake\Datasource\ResultSetDecorator->rewind()
InsertIterator.php:118, Cake\Collection\Iterator\InsertIterator->current()
EntityTrait.php:668, App\Model\Entity\Game->offsetSet()
EntityTrait.php:248, App\Model\Entity\Game->set()
EntityTrait.php:839, App\Model\Entity\Game->setDirty()
```

In the case where it works correctly (where the parent table also has the translate behaviour), it's like this:

```
Table.php:1624, App\Model\Table\GamesTable->get()
QueryTrait.php:483, Cake\ORM\Query->firstOrFail()
QueryTrait.php:472, Cake\ORM\Query->first()
CollectionTrait.php:386, Cake\Datasource\ResultSetDecorator->first()
CollectionTrait.php:386, LimitIterator->rewind()
CollectionTrait.php:386, Cake\Datasource\ResultSetDecorator->rewind()
BufferedIterator.php:112, Cake\Collection\Iterator\BufferedIterator->rewind()
BufferedIterator.php:112, Cake\Collection\Iterator\BufferedIterator->rewind()
BufferedIterator.php:112, Cake\Datasource\ResultSetDecorator->rewind()
**BufferedIterator.php:112, Cake\Collection\Iterator\ReplaceIterator->rewind()**
InsertIterator.php:118, Cake\Collection\Iterator\InsertIterator->current()
EntityTrait.php:668, App\Model\Entity\Game->offsetSet()
EntityTrait.php:248, App\Model\Entity\Game->set()
EntityTrait.php:839, App\Model\Entity\Game->setDirty()
```

Note that the call stack here includes ReplaceIterator. ReplaceIterator's `current` function (called very shortly after this) has a callback into TranslateBehavior's `_rowMapper` function, which calls `$row->clean`, removing the dirty setting.

In the case where `loadInto` is used instead, `LazyEagerLoader::_injectResults` is called, which calls `setDirty` with false to clear this.

I tried to track the case where TranslateBehavior is not involved at all to see why what works correctly, but got out of my depth.

**Comment by Zuluru** [comment]
Apart from submitting a PR that fixes this (which I don't think I can do without learning a LOT more about ORM internals, just for this one thing), is there anything else I can do to help get it resolved?

**Comment by markstory** [comment]
@Zuluru I think someone needs to spend the time to track down why the property ends up being set dirty. This is generally a time consuming process no matter who does it.

**Comment by Zuluru** [comment]
Okay. Hopefully, the info I've provided will help a little bit whenever someone gets to it.

**Comment by markstory** [comment]
If you have a test case or sample application to help reproduce the problem that might help others interested in investigate this further.
