### ISSUE TITLE
Accessing and modifying the current route

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13661]
For CakePHP version 3.7.9

* [x] Enhancement

There is, afaik, currently no easy way to access current route and array of attributes, that matched the route

What is known (accessing current route/url build params):
- Cake\Http\ServerRequest method `getRequestTarget()` returns only string representation (including query and without hash url params)
- `Cake\Routing\Router::reverseToArray($this->request)` will return array of params to build the url, however including params not contained in current url (such as _csrfToken, isAjax)
- Cake\View\Helper\UrlHelper method `build()` used like `$this->Url->build(Router::reverseToArray($this->request))` will return url as string, but containing _csrfToken as get query param (see point above)
- `Cake\Routing\Router::parseRequest($this->request)` will return relevant array of params to build array, but including `_matchedRoute`

What is known (building new url based on current one, given that ':lang' is recognized route segment)
- `$this->Url->build(['lang'=>'fr'] + Router::reverseToArray($this->request))` will generate url that contains additional data (eg. _csrfToken)
- `$this->Url->build(['lang'=>'fr'] + Router::parseRequest($this->request))` will generate url that contains additional data (eg. _matchedRoute)

Since there is always some extra data in the returned, developer cannot be sure, that even manually filtering values that are apparent, will filter out all the extra data, that could appear (ie. it is not known if the data in reverseToArray, parseRequest and others will not contain more unnecessary attributes under different circumstances)

So what I'm seeking is documentation update or API update, that would provide clear way of
  1. Retrieving only relevant array of data needed to build current URL (matching current route)
  2. Modifying current route param(s) and re-generating (reverse routing url build) url (eg. using Url->build, Html->link or Html->url)

**Comment by markstory** [comment]
Have you tried using the Uri object, it can return the path in isolation.

```php
// Get the path (without subdirectory)
$request->getUri()->getPath();
```

Which can then be used with any of the helpers to get paths to the current URL.

**Comment by saeideng** [comment]
if you use `_name` in routes , its possible to detect current route

**Comment by ADmad** [comment]
>  $this->Url->build(Router::reverseToArray($this->request)) will return url as string, but containing _csrfToken as get query param (see point above)

This seems like a bug / oversight. `Router::reverseToArray()` should unset `_csrfToken` key too like it unsets `_Token`.

**Comment by ADmad** [comment]
Closing as `Router::reverseArray()` cleans out `_csrfToken` and `isAjax` keys too. 

The main culprit here is the router feature which turns any extra key in URL array into query string param. This has already been changed in 4.x.

**Comment by smarek** [comment]
Thank you all :)
