### ISSUE TITLE
Support for convert expression in database

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#13668]
How to add `convert` expression to query?
Some example of use:
* Get date part from an datetime
* Convert int to varchar to use in concat

**Comment by ndm2** [comment]
The issue tracker isn't really ment for such questions, you're better off asking them on Slack/IRC, StackOverflow, etc.

Anyways, the multi-argument variant of `CONVERT` can be created via the functions builder (https://book.cakephp.org/3.0/en/orm/query-builder.html#using-sql-functions), like:

```php
$query->select(function (\Cake\ORM\Query $query) {
	return [
		'date_part' => $query->func()->CONVERT([
			'Products.created' => 'identifier',
			'DATE' => 'literal'
		]),
		'char_variant' => $query->func()->CONVERT([
			'Products.amount' => 'identifier',
			'CHAR' => 'literal'
		]),
	];
});
```

The MySQL specific variant with `USING` would require you to create a custom expression class.

**Comment by mcsknp** [comment]
@ndm2 Did you check your code in MS SQL Server?

**Comment by mcsknp** [comment]
@ADmad Please reopen this!

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by mcsknp** [comment]
This is feature enhancements.

**Comment by ndm2** [comment]
@mcsknp  No, I did not, the example is ODBC syntax. The SQL Sever variant can be created the very same way however, simply switch the arguments, and add a third one for style if needed.

**Comment by mcsknp** [comment]
@ndm2 I working with both MySQL and MS SQL Server so I need a support from Query Compiler

**Comment by ADmad** [comment]
> This is feature enhancements.

A question like `How to add convert expression to query?` doesn't really read as a feature enhancement request.

Please submit a concrete proposal of enhancement you expect.
