### ISSUE TITLE
Limit debug stack trace when logging to file

### ISSUE THREAD

**Issue by mfrascati** [cakephp/cakephp#13663]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.4
* Platform and Target: Ubuntu 18.04

### What you did
Raised some kind of error, which is logged to debug.log. In development mode, with debug enabled.

### What happened
The error is logged with a full, in depth stack trace which is generating over 20MB of logs for a single Exception, and making the log debug impossibile since one needs to scroll hundreds of lines.
![image](https://user-images.githubusercontent.com/2734747/65372019-95d63b80-dc6a-11e9-9f81-95370ef477fb.png)

### What you expected to happen
In previous versions the log was more concise, just displaying file:line and the functions calls, without the full data. There should be a way to limit the depth of this logs. (Or there is and I missed? I tried Error.trace = false, but nothing changed.

**Comment by markstory** [comment]
How can someone reproduce a log message like that. Locally my errors have the compact trace you mentioned.

**Comment by mfrascati** [comment]
Found out it was caused by a custom ExceptionRenderer I didn't notice before.
Switching to \Cake\Error\ExceptionRenderer::class fixed the issue.
