### ISSUE TITLE
Cake\Http\Client\FormData format error

### ISSUE THREAD

**Issue by littleylv** [cakephp/cakephp#13673]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.9

### What you did
Upload a file using [Building Multipart Request Bodies by Hand](https://book.cakephp.org/3.0/en/core-libraries/httpclient.html#building-multipart-request-bodies-by-hand)

### What happened
The response result to be 400 error:   

```
<Code>MalformedPOSTRequest</Code>
<Message>The body of your POST request is not well-formed multipart/form-data</Message>
```

### What you expected to happen
Upload file successfully

### How did I resolve

I modified two of the cake source code and then it worked.

First, [FormData.php#L233](https://github.com/cakephp/cakephp/blob/master/src/Http/Client/FormData.php#L233), change

```
return 'multipart/form-data; boundary="' . $this->boundary() . '"';
```

to

```
return 'multipart/form-data; boundary=' . $this->boundary()';
```

And [FormData.php#L252](https://github.com/cakephp/cakephp/blob/master/src/Http/Client/FormData.php#L252), change

```
$out .= "--$boundary--\r\n\r\n";
```

to

```
$out .= "--$boundary--\r\n";
```

If you approve my modification, I would love to make a PR

**Comment by ADmad** [comment]
What's generating this error?

```
<Code>MalformedPOSTRequest</Code>
<Message>The body of your POST request is not well-formed multipart/form-data</Message>
```

Are you sure the the double are the issue? Even the RFC shows example of boundary with double quote. https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by ADmad** [comment]
That's said since the boundary is generated using `md5()` quoting isn't necessary.

**Comment by littleylv** [comment]
> What's generating this error?
> 
> ```
> <Code>MalformedPOSTRequest</Code>
> <Message>The body of your POST request is not well-formed multipart/form-data</Message>
> ```
> 
> Are you sure the the double are the issue? Even the RFC shows example of boundary with double quotes. https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

1. The error was response by server to save my file (oss-cn-shanghai.aliyuncs.com or amazon s3 for example)

2. I'm very sure after editing those two codes, my project worked.

3. [symfony](https://github.com/symfony/symfony/blob/1ce83dab3464c2ed92d17b54352af59724b10bee/src/Symfony/Component/Mime/Part/AbstractMultipartPart.php#L74) uses one `\r\n`

4. It occurs to me that, maybe it's not CakePHP's issue. Maybe the server(I'm uploading files to oss-cn-shanghai.aliyuncs.com) verify the form-data format for some mistake. Maybe with or without quoting is both OK. Anyhow, I got my project work.

**Comment by littleylv** [comment]
I Google for "form-data boundary quote" and got some information.

According to rfc2616

```
Although RFC 2046 [40] permits the boundary string to be quoted, some existing implementations handle a quoted boundary string incorrectly.
```

**Comment by markstory** [comment]
Removing the quotes on the boundaries makes sense. Like @ADmad noted our MD5 sums don't require quoting. Removing the extra \r\n should be ok.
