### ISSUE TITLE
Not able to fetch authorization header

### ISSUE THREAD

**Issue by sandriti** [cakephp/cakephp#13671]
Hi everyone!

I'm using Cakephp 3.3 and I'm trying to pass Authorization header to external page from my controller.

`$this->response->header('Authorization', 'Bearer ' . $token);
 $this->response->header('Location', $url);`

Debugging I get 2 request. The first one is my page with 302 code and I can see the Authorization header, and the other one with 200 code but without header.

Also I added this on `webroot/.htaccess`

`RewriteCond %{HTTP:Authorization} ^(.*)`
`RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

But nothing happens. Any idea? Thanks in advance!

**Comment by garas** [comment]
1. `Authorization` is request header, not response.
2. You can't set headers of redirect target. 

You may need help of some [`Oauth` library](https://packagist.org/?query=oauth) to implement what you need.

---

This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:

* [The CakePHP Manual](https://book.cakephp.org)
* [The CakePHP online API](https://api.cakephp.org)
* [CakePHP Official Forum](https://discourse.cakephp.org)
* [Stackoverflow](https://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](https://cakesf.herokuapp.com/) or [#cakephp](https://webchat.freenode.net/?channels=#cakephp) on irc.freenode.net
