### ISSUE TITLE
Unable to generate code coverage

### ISSUE THREAD

**Issue by dmarra** [cakephp/cakephp#13674]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.19
* Platform and Target: linux

### What you did
I attempted to generate code coverage via the following command from the cookbook:

`./Console/cake test app Model/Article --coverage-html webroot/coverage`

### What happened
I got the following output:

```
Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/html/app/
---------------------------------------------------------------
CakePHP Test Shell
---------------------------------------------------------------
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.


Error:         No whitelist configured, no code coverage will be generated
W                                                                   1 / 1 (100%)

Time: 88 ms, Memory: 11.00MB

```

### What you expected to happen
I expected to see some code coverage generated...

**Comment by markstory** [comment]
Did you fix the error:

> No whitelist configured, no code coverage will be generated

You'll need to configure a whitelist in your phpunit.xml file.

**Comment by dmarra** [comment]
I haven't been able to locate a phpunit.xml file in the Cake distribution. Where should I place the xml file? There is one that comes with the phpunit install via composer, but it doesn't feel correct to edit that  one.

**Comment by dereuromark** [comment]
This is a phpunit specific question, you can see the deails in their docs. 
This issue is not core relevant.

**Comment by dmarra** [comment]
But Cake is providing wrappers around the usage. If I am running test from the cake console, how am I to know what the root folder is considered? is it relative to the entire project, or just app? Console? this is unclear.

**Comment by markstory** [comment]
I am pretty sure it goes in the application directory. I am not sure though as I haven't worked with 2.x in a while.

**Comment by dmarra** [comment]
I tried this, but I still get the error message. I tried:

- ./
- ./app
- ./app/test

What else could I try?

**Comment by markstory** [comment]
You can use the `--configuration` option to provide a path to your phpunit.xml file.

**Comment by dereuromark** [comment]
So far 2.x code coverage is working fine as also e.g. seen for plugins like https://github.com/dereuromark/cakephp-tools/tree/2.x
This is a developer issue as outlined above, and should be consulting the coverage docs of phpunit here then instead for further questions.
