### ISSUE TITLE
Response status with constants

### ISSUE THREAD

**Issue by lpj145** [cakephp/cakephp#13688]
https://github.com/cakephp/cakephp/blob/cde7a1c39138eadd2ffb2e2d524ad09672ca6c66/src/Http/Response.php#L47

Shouldn't be a constants ? if this turn to constants i think is more reusable and clarity to work with this.

````php
$response
    ->withStatus(\Cake\Http\Response::HTTP_BAD_REQUEST)
`````

maybe on interface off response this make more sense!

Whats your think ? thanks for attention.

**Comment by lpj145** [comment]
Maybe the same rule for the *application types*, all we know about http from init of protocol the things about status and application type don't change.

**Comment by markstory** [comment]
Having constants for commonly used status codes would be good. Having constants would help prevent typos and enable IDE auto-completion.

I'm not sure we'd want constants for every mime type as many are very infrequently used, but for commonly used ones constants could be beneficial.

**Comment by lpj145** [comment]
Okay, i'm can make a pr ?

**Comment by ADmad** [comment]
https://github.com/php-fig/http-message-util
https://github.com/lmc-eu/http-constants

**Comment by lpj145** [comment]
ahaha @ADmad i'm not surprise with you comment, okay, if not have a interest, close this issue!

**Comment by othercorey** [comment]
The http-message-util does not include all of the status codes that cakephp enumerates such as `499` and `599`.

However, does CakePHP allow mentioning such a package for users to use when calling `withStatus()` and checking against `getStatusCode()` if they want constants in their code instead of raw integers?

**Comment by dereuromark** [comment]
> does CakePHP allow mentioning such a package

What you add to your project's composer.json is completely up to you. So yes, of course, the framework doesn't prevent you from using this library :) It just doesnt ship with it by default.

**Comment by othercorey** [comment]
> What you add to your project's composer.json is completely up to you. So yes, of course, the framework doesn't prevent you from using this library :) It just doesnt ship with it by default.

lol, of course :). I meant in terms of documentation like in the doc header of the class.

**Comment by dereuromark** [comment]
I am sure mentioning it in the docs or docblock is a good idea here.
Feel free to make such pull requests.
