### ISSUE TITLE
Make TableSchema class name configurable

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13689]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: Any.

### What you did
I would like to override TableSchema in order to add more functionality.

### What happened
I found that the construction is hard coded by using `new TableSchema` that makes it very difficult to extend TableSchema.

### What you expected to happen
I would like to make it configurable - what class to use as TableSchema.
One option would be to set it like connection and database driver classes are set for `ConnectionManager::setConfig` method:
```
    'className' => Connection::class,
    'driver' => Mysql::class,
    'tableSchemaClass' => TableSchema::class,
```
Another option would be to introduce a new method to Cake\Database\Driver class:
```
public function getTableSchemaClass() 
{
    return TableSchema::class;
}
```
So that instead of hard coded `new TableSchema` the class name would be taken from configuration or Driver. That would allow to extend the functionality of TableSchema.

**Comment by markstory** [comment]
The method on the connection sounds like a good approach to me. Instead of returning the classname would a factory method on the driver work for what you're doing?

**Comment by bancer** [comment]
If you mean something like this in Driver class then it would be okay:
```
public function constructTableSchema($table, $columns => []) {
    return new TableSchema($table, $columns);
}
```

**Comment by markstory** [comment]
Yes that's what I was thinking @bancer
