### ISSUE TITLE
[RFC] Support for SameSite Cookies

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#13682]
CakePHP Version: 3 and 4
Platform and Target: any with PHP 7.3+

I propose to add support for setting "SameSite" cookies to the Cookie functionality.

The Cookie class would need ``withSameSite()`` & ``isSameSite()`` methods, just like [withHttpOnly](https://api.cakephp.org/3.8/class-Cake.Http.Cookie.Cookie.html#_withHttpOnly) [isHttpOnly()](https://api.cakephp.org/3.8/class-Cake.Http.Cookie.Cookie.html#_isHttpOnly).
Also, the [Cookie class constructor](https://api.cakephp.org/3.8/class-Cake.Http.Cookie.Cookie.html#___construct) should allow for a new, optional ``$sameSite`` parameter.

For CakePHP 4.0, we could extend the [CookieInterface](https://api.cakephp.org/3.8/class-Cake.Http.Cookie.CookieInterface.html#_isHttpOnly), too.

Since [version 7.3.0, PHP](https://www.php.net/ChangeLog-7.php#7.3.0) supports SameSite cookies.

> SameSite cookie directive, including an alternative signature for setcookie(), setrawcookie() and session_set_cookie_params().

Possible values are:

- Strict
- Lax
- None

Chrome seems to make ``SameSite=Lax`` the default value [by Chrome 78](https://scotthelme.co.uk/csrf-is-really-dead/).

Consensus & Standardization
Firefox: [In development](https://bugzilla.mozilla.org/show_bug.cgi?id=1551798) (Fixed as for FF 69, released)
Edge: Mixed public signals
Safari: No public signals
Web Developers: No signals
Some ressources: 

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
- https://ayesh.me/PHP-Samesite-cookies
- https://wiki.php.net/rfc/same-site-cookie
- https://scotthelme.co.uk/csrf-is-really-dead/ & https://scotthelme.co.uk/csrf-is-dead/
- https://blog.benpri.me/blog/2019/05/13/samesite-cookies-in-practice/

**Comment by garas** [comment]
Based on [Can I use](https://caniuse.com/#feat=same-site-cookie-attribute), `SameSite` cookie already has global support of 86.58% browser users.

As `setcookie()` supports `SameSite` only from PHP 7.3, until then CakePHP should send cookies with `header()`.

CakePHP 4 should send some cookies with `SameSite` by default.

**Comment by ADmad** [comment]
Support for "SameSite" attribute for cookies is now available in `4.x`. Is someone interested in back porting it to `3.9`? :slightly_smiling_face:.

**Comment by ADmad** [comment]
I have added this feature to the consolidated backporting list in #13493.
