### ISSUE TITLE
Invalid precision with float data type in MySQL

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13698]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.1.
* Platform and Target: Apache, MySQL 5.6.

### What you did
Set float data type $fields in AreasFixture:
```
        'latitude' => [
            'type' => 'float',
            'length' => 53,
            'precision' => 7,
            'unsigned' => true,
            'null' => true,
            'default' => null,
            'comment' => ''
        ],
        'longitude' => [
            'type' => 'float',
            'length' => 53,
            'precision' => 7,
            'unsigned' => true,
            'null' => true,
            'default' => null,
            'comment' => ''
        ],
```
We use `double` data type in production database for that though.

Added to $fields in AreasFixture:
```
            [
                'id' => 5,
                'name' => 'My area',
                'latitude' => 55.6760968,
                'longitude' => 12.5683371,
            ],
```

Wrote unit test in AreasTableTest.php:
```
    public function testGet()
    {
        $expected = [
            'id' => 5,
            'name' => 'My area',
            'latitude' => 55.6760968,
            'longitude' => 12.5683371,
        ];
        $actual = $this->Areas->get(5)->toArray();
        $this->assertEquals($expected, $actual);
    }
```

Then I run `vendor/bin/phpunit tests/TestCase/Model/Table/AreasTableTest.php`.

### What happened
The test failed:
```
1) App\Test\TestCase\Model\Table\AreasTableTest::testGet
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-    'latitude' => 55.6760968
-    'longitude' => 12.5683371
+    'latitude' => 55.6760979
+    'longitude' => 12.5683374
```

### What you expected to happen
I would expect the test to pass.

**Comment by ADmad** [comment]
This is similar to the problem we had with high precision decimal fields. The solution is to use strings instead of float in PHP (as done for `DecimalType` in 4.x).

**Comment by bancer** [comment]
We have no problems with such columns in 2.x. Why is it a problem in 3.x?

**Comment by ADmad** [comment]
2.x doesn't do type casting of values returned by PDO. It's all strings.

**Comment by dereuromark** [comment]
Maybe the docs/migrationguide should be a bit more clear on the subject and the potentially BC breaking manner of 3.x vs 2.x here?

**Comment by markstory** [comment]
There isn't much we can do here. Floats have many precision challenges. You could remap these columns to string types if you need the full precision and don't intend to do any math on the values.

**Comment by bancer** [comment]
Casting string '12.5683371' to float gives the correct value 12.5683371. http://sandbox.onlinephpfunctions.com/code/aa9105ccfe2e4c86e1084564a2784cdb0d870d2a

Do I miss here something?

**Comment by bancer** [comment]
> You could remap these columns to string types if you need the full precision and don't intend to do any math on the values.

We use latitude and longitude to calculate a distance.

**Comment by ADmad** [comment]
Can you check after disabling results casting (by calling `disableResultsCasting()` on the query object).

**Comment by markstory** [comment]
The precision could be getting lost when the floats are inserted into the database, you might want to check that data got into the database safely.

**Comment by garas** [comment]
At database, the number was stored as 32bit float and lost precision.

`'12.5683371'` close values are:
`~12.56833710000000081` - 64bit float
`~12.56833648682` - 32bit float a bit lower
`~12.56833744049` - 32bit float a bit higher (closest value in 32bit)

PHP uses 64bit double precision numbers so your code at sandbox  formated back to shortest number which still stores same value, and it was same initial value.

https://www.h-schmidt.net/FloatConverter/IEEE754.html

**Comment by bancer** [comment]
> This is similar to the problem we had with high precision decimal fields. The solution is to use strings instead of float in PHP (as done for DecimalType in 4.x).

@ADmad Using `Type::map('double', StringType::class);` and `Type::map('float', StringType::class);` in bootstrap.php does not fix the problem.

**Comment by ADmad** [comment]
There is no `double` type, but using `Type::map('float', StringType::class)` in boostrap should work. You can also try overriding the type for the fields to string from `Table::_intializeSchema()`.

**Comment by bancer** [comment]
The precision problem is only in unit tests. The latitude and the longitude have correct values when not in tests. It seems that the reason of the problem is related to how the table is created in the test database. 2.x also uses floats instead of doubles and there is no precision problem in tests. I am pretty sure there is a bug somewhere during the conversion of the fixture class to the database table.

**Comment by bancer** [comment]
> There is no double type, but using Type::map('float', StringType::class) in boostrap should work.

It works but does not fix the precision problem.

**Comment by bancer** [comment]
In 2.x in tests those columns are:
```
`latitude` float(53) UNSIGNED DEFAULT NULL,
`longitude` float(53) UNSIGNED DEFAULT NULL,
```
 
In 3.x they are
* when 'length' and 'precision' are not set in the fixture
```
`latitude` FLOAT UNSIGNED,
`longitude` FLOAT UNSIGNED,
```
* when `'length' => 53, 'precision' => null` 
         or `'length' => 53, 'precision' => false`
         or `'length' => 53` and 'precision' not set in the fixture
```
`latitude` FLOAT(53,0) UNSIGNED,
`longitude` FLOAT(53,0) UNSIGNED,
```
* when `'length' => 53, 'precision' => 7` in the fixture
```
`latitude` FLOAT(53,7) UNSIGNED,
`longitude` FLOAT(53,7) UNSIGNED,
```
* when `'precision' => 53` and 'length' is not set in the fixture
```
`latitude` FLOAT(0,53) UNSIGNED,
`longitude` FLOAT UNSIGNED,
```

I would expect `latitude float(53) UNSIGNED DEFAULT NULL` when `'length' => 53` and 'precision' is not set in the fixture but that does not happen.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
