### ISSUE TITLE
Support for convert expression in database

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#13694]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

### Enhancement description
Add `CONVERT` or `CAST` or both expression to use for
* Get date part from an datetime
* Convert int to varchar to use in concat
* etc...

### Usage:
Using `$query->newExpr()->convert('db_field', 'target_type')` to generate convert expression

**Comment by markstory** [comment]
Wouldn't these methods be `$query->func()->convert(...)`? As all the database agnostic function wrappers are provided by `FunctionsBuilder` not the Query class.

**Comment by mcsknp** [comment]
If there's method to use its, both of `function` and `expression` are ok.

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/cakephp/pull/13725

**Comment by othercorey** [comment]
> * Get date part from an datetime

For postgresql, I would use the `to_char()`, `date_part()`, `date_trunct()` or `extract()` functions which are specifically designed for this.

**Comment by mcsknp** [comment]
It seems have not fixed

**Comment by othercorey** [comment]
`FunctionsBuilder::cast()` was added in 4.1.
