### ISSUE TITLE
PropertyMarshalInterface::buildmarshalmap

### ISSUE THREAD

**Issue by fredckl** [cakephp/cakephp#13707]
* [x] Question

* CakePHP Version: 3.8.4
* Platform and Target: APACHE, MySQL, MacOS.

### What you did
Why can not I implement 2 methods buildMarshalMap in 2 behaviors?

### What happened
I have 2 behaviors that implement PropertyMarshalInterface and I get an error <App \ Model \ Behavior \ TagBehavior contains duplicate method "buildmarshalmap" which is already provided by "Seo">.
If I take the example of the Translate behavior, it is possible to implement the buildMarshalMap method without error.

Why it does not work with those I build?

Thanks for your help

**Comment by ndm2** [comment]
Please note that the issue tracker usually isn't the right place to ask such questions, you're better of using Slack, Stackoverflow, the forum, etc.

That being said, by default all public methods of a behavior are proxied through the table the behavior is attached to, so multiple methods with the same name are conflicting with each other, hence the error.

Either reduce the visibility of the methods, or use the `implementedMethods` option to limit and/or rename the exposed methods, see **https://book.cakephp.org/3.0/en/orm/behaviors.html#limiting-or-renaming-exposed-mixin-methods**.
