### ISSUE TITLE
Smtp authentication error

### ISSUE THREAD

**Issue by Edsol** [cakephp/cakephp#13708]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.9
* Platform and Target: Apache/2.4.25 (Debian), PHP: 7.1.31, Mysql 5.7.27

### What you did
I set EmailTransport in config app.php:

```
'myconf' => [
            'className' => 'Smtp',
            'host' => 'mail.poweringsrl.it',
            'port' => 587,
            'timeout' => 20,
            'username' => 'XXXXXXXXX',
            'password' => 'XXXXXXXXX',
            'tls' => true,
            'log'=> true,
            'context' => [
                'ssl' => [
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                ]
            ]destinatario
        ]
```

and send email via Mailer:
```
    $this
      ->setFrom('sender@domain.com')
      ->setTo('receiver@domain.com')
      ->setTransport('myconf')
      ->setSubject('smtp test  mail');
```

### What happened
Receive this error message:

`SMTP Error: 535 5.7.8 Error: authentication failed: Invalid authentication mechanism `

if I test the server response on 587 port:

```
edoardo@debian:~$ telnet mail.poweringsrl.it 587
Trying 34.90.118.46...
Connected to mail.poweringsrl.it.
Escape character is '^]'.
220 poweringsrl.it ESMTP Postfix

```

I tested php mailer library with the same config of EmailTransport and work perfectly.

**Comment by garas** [comment]
`SmtpTransport` always connects using `AUTH LOGIN` authentication mechanism. Your server only supports `AUTH PLAIN`.

**Comment by wnhre2ur8cxx8** [comment]
> `SmtpTransport` always connects using `AUTH LOGIN` authentication mechanism. Your server only supports `AUTH PLAIN`.

I am sorry to revive this, but why was this closed? Has this every been fixed? And if, since which version? Or is this the expected behaviour? You only support AUTH LOGIN?
