### ISSUE TITLE
Cache::read default value

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#13706]
A discussion about feature coding way.

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8

I'm trying to code a Cache processor system, related to #11563 .
For this, i'm using the SimpleCacheEngine::set() and add a `_processorIn` method before call of `$this->innerEngine->write`. Works fine.

The problem came with `read`. The current code of `Cache::read` don't use `SimpleCacheEngine::get`, i've fixed that BUT, the `SimpleCacheEngine::get` method have a `$default` value set to null.
The `Cake\Database\SchemaCachedCollection` read cache for Schema and if Cache return is not `false`, return as is. By default, it is `null`. This return thrown an error : 

```
Argument 1 passed to Cake\ORM\Table::_initializeSchema() must be an instance of Cake\Database\Schema\TableSchema, null given
```

My idea is to add a $default param to `Cache::read` but it completely break the compatibility.
I've check the code in 4.x and no default value too. 

Should we add `default` value in Cache::read ? should we change the SimpleCacheEngine::get default value to be compatible ?

Thanks

**Comment by markstory** [comment]
If you need to use the default values you can use `Cache::pool('configname')->get()` instead of `Cache::read()`
