### ISSUE TITLE
Plugins for Plugins

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#13719]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: 3.7.1
* Platform and Target: Apache, MySQL

### What you did
I created a plugin inside a plugin

### What happened
nothing

### What you expected to happen
I want the plugin inside the plugin to load

I want to create Plugins inside Plugins, and I am willing to modify the CakePHP code (and create pull request) to allow for this to occur, but before I do that, I want to make sure this is something that would be accepted into the codebase. 

Let me explain my use case...

I have created a plugin with the AdminLTE dashboard template, I now want to create plugins for that template, for example, I have coded out a Support system (Tickets, Live Chat, etc...) and I feel like that best way to organize plugins for the AdminLTE plugin, is to put those plugins inside the AdminLTE plugin. It appears this would work with composer... Ive thought long and hard about this, and it just doesn't make sense to me to put them side by side, as one without the other doesn't work.

**Comment by jeffreyroberts** [comment]
I actually did this for CakePHP 2.x and it worked out great, but now I am working with 3.x and I want to publish my plugins, hence why I will only do it if it will be accepted into the codebase

**Comment by dereuromark** [comment]
I dont quite understand what you want to do.
You use composer to make plugins depend on each other. That already is like this since 2.x days.
See my Shim and Tools and ... plugins doing exactly that, for example.

**Comment by jeffreyroberts** [comment]
Thank you for your quick reply, I took a look at your repositories, you have some good stuff there, I will be back to take a deeper look into your boxes of treasures this afternoon =]

I am looking to build something like the following

    app/plugins/AdminLTE/plugins/Support/config/routes.php

Then I would load in the following order

    app/plugins/AdminLTE/config/routes.php
    app/plugins/AdminLTE/plugins/Support/config/routes.php
    app/config/routes.php

routes may not be the best example, maybe bootstrap would make a better example, I was going to do an example of Plugin::load inside AdminLTE/config/bootstrap.php, loading the Support plugin, but I know that just recently changed, so again, not a good example lol...

I am on my way out the door at the moment, I will be thinking of a better example, I hope this does give you some clarity on what I am trying to do though =]

**Comment by ADmad** [comment]
I don't think plugin inside a plugin is a complication which we need to support. A plugin can have other plugins as dependency through composer the same way an app depends on other plugins.

For example the `friendsofcake/crud-view` plugin has `friendsofcake/crud` and `friendsofcake/bootstrap-ui` as dependencies and it works just fine.

**Comment by jeffreyroberts** [comment]
I believe this is a good example, lets not focus on the dependency part, but more on the ability to extend a plugin. I use the CakeDC/Users plugin in a lot of my projects, and I find myself extending that plugin quite often, usually with cut and paste, it would be nice to be able to extend that plugin as a plugin, so that the config/*.php files are loaded in the proper order. For example, the following config files would be loaded in the order they are listed.

     src/plugins/Users/config/permissions.php
     src/plugins/Users/plugins/UsersExtension/config/permissions.php
     src/config/permissions.php

Please allow me to elaborate. As of right now, I am not aware of a way to extend the CakeDC/Users plugin, as another plugin, I am under the impression that I have to extend inside the application. Which means if I distribute my extension of said plugin, then I have to distribute it as an app skeleton. If I were able to nest my plugin extension inside the plugin itself, then the overridden config files would be sure to be loaded in the proper order. 

I hope that makes more sense, please let me know if you have any questions

**Comment by markstory** [comment]
If your plugin extends another couldn't the base plugin be a dependency of the extension and your application use the extension classes?

I am reluctant to add nested plugins as it complicates path resolution for plugin templates and resource files.

**Comment by jeffreyroberts** [comment]
@markstory Thank you for your quick reply, That is definitely a solution for packaging the extension outside of an app skeleton, and I am totally open to using that solution, but would the config files be loaded in the order I listed above?

**Comment by saeideng** [comment]
you can add/load plugin in order of you want just you need to use `addPlugin()` in your `bootstrap()` hook in your main plugin at `src/Plugin.php` class

**Comment by dereuromark** [comment]
If you want to further follow this, I think you can try to create your own loader for this as plugin/custom solution.
Let's close this for core at this point though, as there is no interest on increasing the complexity here for all users.
