### ISSUE TITLE
[CakePHP 4.x] belongsToMany doesn't work like in 3.x

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#13712]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev - Hash: 6fec49c146.
* Platform and Target: 
PHP 7.3.9 (via FPM)
MariaDB 10.3.18
NGINX 1.14

### What you did
- Download https://github.com/cakephp/cakephp/releases/tag/4.0.0-beta3 & adjust config/app.php for DB connection
- Import SQL from bellow 
- `bin/cake bake model all`
- `bin/cake bake controller all`
- `bin/cake bake template all`
- Insert "Category 1" into the categories table
- Go to the books "add" template

### What happened
It doesn't populate the dropdown with the already present "Category 1"

### What you expected to happen
It should populate the dropdown with the already present "Category 1"

# Other usefull information
In both the BooksTable.php as well as the CategoriesTable.php the `belongsToMany` connection is correctly set (in my opinion)

![image](https://user-images.githubusercontent.com/9105243/66233615-17f34500-e6ec-11e9-9f3a-c838ca316f16.png)

Controller and Template also contain the (in my opinion) correct code for outputting the connected tables content.

src/Controller/BooksController.php
![image](https://user-images.githubusercontent.com/9105243/66233144-e7f77200-e6ea-11e9-9957-a670e6f96c78.png)

templates/Books/add.php
![image](https://user-images.githubusercontent.com/9105243/66233178-fd6c9c00-e6ea-11e9-940c-ac96b8c40662.png)

But I don't get the already present "Category 1" in the dropdown on the /books/add template.

After enabling the DebugKit I recognised, that the single SQL Query being made on that template is the following:

```
SELECT 
  Books.id AS `Books__id`, 
  Books.name AS `Books__name` 
FROM 
  books Books 
  INNER JOIN books_categories BooksCategories ON Books.id = (BooksCategories.book_id) 
LIMIT 
  200
```

My question here is: Why does it inner join with the "connection table"?

I first thought this problem persist in the current CakePHP 3 version as well, but as you can see in this issue, it works there (if you generate the files in the correct order)

https://github.com/cakephp/bake/issues/587 

# SQL
```
DROP TABLE IF EXISTS books;
CREATE TABLE books
(
    id       INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name     varchar(255),
    created  DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS categories;
CREATE TABLE categories
(
    id       INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name     varchar(255),
    created  DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS books_categories;
CREATE TABLE books_categories
(
    book_id     INT UNSIGNED,
    category_id INT UNSIGNED,
    PRIMARY KEY (book_id, category_id)
);
```

**Comment by saeideng** [comment]
I checked my generate query is bit different with your generated query 
```php
$list = $this->Categories->find('list'); //query 1
$list2 = $this->Posts->Categories->find('list'); //query 2
```

cake3 for both query 
```
SELECT 
  Categories.id AS `Categories__id`, 
  Categories.title AS `Categories__title` 
FROM 
  categories Categories
```

cake4 for first query same is cake 3 
for second query ( `$list2 = $this->Posts->Categories->find('list');` )
```
SELECT 
  Categories.id AS `Categories__id`, 
  Categories.title AS `Categories__title` 
FROM 
  categories Categories 
  INNER JOIN categories_posts CategoriesPosts ON Categories.id = (CategoriesPosts.category_id)
```


my query is
```
FROM 
  categories Categories 
  INNER JOIN categories_posts ....
```
but for you 
```
FROM 
  books Books 
  INNER JOIN books_categories ...
```

**Comment by saeideng** [comment]
anyway if you have correct rows in pivot tables 
your query will works well

**Comment by LordSimal** [comment]
ok, but if we stick with my example above we are in the add function of the BooksController.

In there I cant just access another Model with 
`$this->Categories->find('list')`

i have to go through my current Controller into the other connected model, therefore
`$this->Books->Categories->find('list');`

But this line doesn't work now anymore, because it makes the mentioned inner join.

In my "old" CakePHP3 program this line `$this->Books->Categories->find('list');` gets me all available Categories without any join.

Therefore do I have to load the other Model into my Controller to get all available Categories to get them into the view?

Something like that?

```
use Cake\ORM\TableRegistry;
$query = TableRegistry::getTableLocator()->get('Categories')->find();
```

**Comment by LordSimal** [comment]
My problem here is, that I want to "prefill" all available categories in the categories table and then make all these categories available in a dropdown in the add template of the books table.

I can kinda understand, that the "new" way only gets you already connected categories in the BooksController, but how do I add Books to already present Categories that don't already have connections and therefore entries in the pivot table?

**Comment by LordSimal** [comment]
And yes, im sorry, i posted the wrong DebugKit SQL Query

As @saeideng mentioned, it should have been

```
SELECT 
  Categories.id AS `Categories__id`, 
  Categories.name AS `Categories__name` 
FROM 
  categories Categories 
  INNER JOIN books_categories BooksCategories ON Categories.id = (BooksCategories.category_id) 
LIMIT 
  200
```

**Comment by markstory** [comment]
I was able to reproduce the additional join locally. It seems like this may be related to 6b8d5de2013  checking the finder conditions incorrectly. I'll get this fixed.

**Comment by saeideng** [comment]
>Therefore do I have to load the other Model into my Controller to get all available Categories to get them into the view?

no , I first was thinking this is intended in cake 4 but I did another test , and I checked `4.0 migration-guide` and I see this in not intended  and this is a bug in cake 4 (beta),

 I put now a new method into `Posts` table 
```php
    public function aMethod(){
        ....
        return $this->Categories->find('list');
    }
```
this  use in many use cases , but for now it executes extra join
and this changes user's program behavior and should be fix
so as @markstory mentioned and labeled this issue , this is a bug and will fix
 
thank you for reporting

**Comment by LordSimal** [comment]
After manually applying your changes from the pull request I indeed can confirm, that this change fixes my problem.

Thank you for the quick fix @markstory!

I'm looking forward to seeing the pull request being applied and I can apply this change with the next composer update.
