### ISSUE TITLE
SQL Server VARBINARY(MAX) reflection generates invalid schema

### ISSUE THREAD

**Issue by danellos** [cakephp/cakephp#13714]
# Environment
CakePHP 3.8.4
PHP 7.2.19
Bake 1.11
Microsoft SQL Server 2017 (running in a Docker Container)

# What I did
`bin/bake fixture test_table`

This is the structure of the test case table:
```
CREATE TABLE [dbo].[test_table](
	[id] [int] NOT NULL,
	[bin_field] [varbinary](max) NOT NULL,
)
```

# What Happened

This generates a fixture with the following line:
`'bin_field' => ['type' => 'binary', 'length' => -1, 'null' => false, 'default' => null, 'precision' => null, 'comment' => null],`

In a test case, the SQL being generated is as follows:
```
CREATE TABLE [test_table] (
    [id] INTEGER NOT NULL,
    [bin_field] VARBINARY(-1) NOT NULL
)
```

The **length => -1** is causing the invalid SQL error. However, if you actually specify the length of a number that is not MAX, it generates the SQL correctly. For example, VARBINARY(100) generates the following, which is correct:
`'bin_field' => ['type' => 'binary', 'length' => 100, 'null' => false, 'default' => null, 'precision' => null, 'comment' => null],`

SQL:
```
CREATE TABLE [test_table] (
    [id] INTEGER NOT NULL,
    [bin_field] VARBINARY(100) NOT NULL
)
```
Possible that "-1" in this case can be interpreted as MAX by the SQL generator for MSSQL?

VARBINARY(MAX) stores a max file size of 2GB according to SQL Server documentation.  While ideally I'd love to not have this field even exist in the database itself, currently I am coding against a legacy database system and reworking this field is not possible in the scope of my project.

I haven't seen this issue reported anywhere, so I thought I'd post here.

**Comment by markstory** [comment]
I've moved this issue to cakephp/cakephp as that is where the schema reflection & schema generation is done.
