### ISSUE TITLE
Would it be possible to split CakePHP in resuable components?

### ISSUE THREAD

**Issue by GBeushausen** [cakephp/cakephp#13713]
For some projects i need something like a micro framework, which just uses some great tested components for some tasks. Unfortunatly from a business point of view, most Frameworks are not reliable. Zend Framework 1 was great, untill they turned the project into an over engineered mess which later completely failed. Silex & Symfony Components was also a great combination until it got canceled. I could write a microframework myself which uses Symfony Components, but they keep on cancelling features like crazy. For example cancelling the support of PHP templates and only supporting Twig alone. Or doing useless changes to their codbase like transforming the signature from this:

`$this->eventDispatcher->dispatch(Events::My_EVENT, $event);`
to this:
`$this->eventDispatcher->dispatch($event, Events::My_EVENT);`

This is totally unreliable. These changes bring no benefit at all, but cost thousands of people time and money to refactor their apps.

So i came accross CakePHP, which from a business point of view seems to be the most reliable and sane framework out there. However in some cases it would be cool to be able to use only some compenents within a micro framework.

I don't know the source code of Cake too much at the moment. Would it be possible, to do something like Cake Components, the same way Symfony has Symfony Components? Or is it not possible with Cake?

**Comment by markstory** [comment]
We have a several [package splits](https://packagist.org/users/cakephp/) available today. However, notable omissions are http, routing and console libraries. We hope to have more package splits available in the future though.

**Comment by markstory** [comment]
The [http package](https://github.com/cakephp/http) has a split now for the 4.x version.

**Comment by ADmad** [comment]
The [console package](https://github.com/cakephp/console) also has a split now for 4.x version.

Since we don't plan to do any more splits at this time closing the issue.
