### ISSUE TITLE
DateTimeType::setTimezone() does not affect converting to DateTime

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13729]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

This is something I noticed while implementing fractional seconds and timezone support.  I think this warrants a discussion instead of either ignoring or randomly changing in a pull request.

DateTimeType has an interface to set the timezone (stored as `dbTimezone`).

```
     * Set database timezone.
     *
     * Specified timezone will be set for DateTime objects before generating
     * datetime string for saving to database. If `null` no timezone conversion
     * will be done.
    public function setTimezone($timezone)
    {
        if (is_string($timezone)) {
            $timezone = new DateTimeZone($timezone);
        }
        $this->dbTimezone = $timezone;

        return $this;
    }
```

This is used in the toDatabase() function to convert the DateTimeInterface instance to that specific timezone before formatting into a string to use in SQL queries.

```
        if ($this->dbTimezone !== null
            && $this->dbTimezone->getName() !== $value->getTimezone()->getName()
        ) {
            if (!$value instanceof DateTimeImmutable) {
                $value = clone $value;
            }
            $value = $value->setTimezone($this->dbTimezone);
        }
```

This makes sense and should work for the common datetime and timestamp times for both MySQL and PostgreSQL.  The timestamp is assumed to be in the local time and this allows converting to a unique local time that is different from php timezone.

However, this is not used in toPHP() when converting the database string to DateTimeInterface instances.  As the interface implies, it is setting the 'database timezone' which suggests it should match the local time mysql and postgres use when converting the timestamp value.  The summary docblock is vague while the remaining part is more explicit, but that leaves a very confusing suggestion of what's implemented by the function name.

MySQL will convert timestamp values to local time when returning values:

>MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time. 

PostgreSQL will do something very similar for timestamptz:

>When a timestamp with time zone value is output, it is always converted from UTC to the current timezone zone, and displayed as local time in that zone. To see the time in another time zone, either change timezone or use the AT TIME ZONE construct

I am working on a change to support postgresql's timestamptz (timestamp with time zone), but I feel this will still leave a gap where setting a database timezone won't produce a DateTimeInterface instance in the expected format for non-timezone timestamps.

Users can work around this by setting their php timezone to match the database timezone (which one would already need to do), but this bug is pointing out the discrepancy between having a setTimezone() function and how it should be replacing that solution.

**Comment by ADmad** [comment]
This is already taken care of in 4.x. 

The `$_datetimeInstance` which is used for string read from db is created using the `$dbTimezone`

https://github.com/cakephp/cakephp/blob/3e88be4194a71c14a03a0e05685f000607fcfa17/src/Database/Type/DateTimeType.php#L156

And `toPHP()` then check the timezone of the `$_datetimeInstance` and changes it to PHP's timezone if it doesn't match.

https://github.com/cakephp/cakephp/blob/4.x/src/Database/Type/DateTimeType.php#L184-L186

**Comment by ADmad** [comment]
In general it would be better if any enhancements/fixes you think are needed,are done on 4.x first, as it already has improvements. We can then backport whatever changes are possible to 3.x ensuring backward compatibility.

**Comment by othercorey** [comment]
@ADmad After reviewing 4.x, I agree this is implemented properly.  Hope you can understand my assumption since setTimezone() was already in 3.8!  

I've been working with 3.8 because my goal is to get DateTimeTimezoneType into 3.8 without changing any of the way current types are parse, assigned etc.  I am trying to find the minimal change needed for that.  I just want it to exist so I can re-build the 'timestamp' type on postgres.

Of course, I'll be happy to submit the request for 4.x first so it works with the expanded/fixed support before backporting.
