### ISSUE TITLE
inteliphense error

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13738]
![erro2](https://user-images.githubusercontent.com/50879411/66689434-2fd54680-ec61-11e9-924e-5af35881296b.png)

This is a (multiple allowed):

* [x] bug

* CakePHP Version: last 3.8.5
* Platform and Target: localhost, mysql, windows 10

**Comment by markstory** [comment]
I'm not sure how we fix that. As there is a truthy check directly above which prevents the null calse.

**Comment by garas** [comment]
It is about `WidgetLocator` and `WidgetRegistry` probably, not `null`.

https://github.com/cakephp/cakephp/blob/a217f7667e8873212ca5cc7d0a412360597a0dbc/src/View/Widget/WidgetRegistry.php#L15-L18

**Comment by dereuromark** [comment]
@LuizMarin Can you confirm that https://github.com/cakephp/cakephp/pull/13775 works?

**Comment by LuizMarin** [comment]
> @LuizMarin Can you confirm that #13775 works?

I don't know how to confirm. I'm learning ... A lot of new things for me

**Comment by dereuromark** [comment]
You take those changes into your local core code, or checkout that branch and see what you IDE says now.
