### ISSUE TITLE
inteliphense error

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13734]
This is a (multiple allowed):

* [x] bug ??   Not sure if it's really bug, image attachment

* CakePHP Version: 3.8.5
* Platform and Target: localhost, last version mysql, windows 10 updated, chrome updated

### What you did
![Anotação 2019-10-09 154254](https://user-images.githubusercontent.com/50879411/66510507-87ca4c80-eaab-11e9-8091-58dd2a4efe0d.png)

{
	"resource": "/d:/www/olabombinhas/vendor/cakephp/cakephp/src/View/Helper/PaginatorHelper.php",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "10006",
	"severity": 8,
	"message": "Expected type 'array'. Found 'string|null'.",
	"source": "intelephense",
	"startLineNumber": 476,
	"startColumn": 56,
	"endLineNumber": 476,
	"endColumn": 62
}

**Comment by ADmad** [comment]
Isn't it obvious that it's an incorrect error? There's an `is_array()` on `$title` var just before the `array_key_exists()` call.
