### ISSUE TITLE
Inconsistency in query generation

### ISSUE THREAD

**Issue by IonutBurlacu** [cakephp/cakephp#13730]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7
* Platform and Target: Nginx, Windows

### What you did
I have the following query condition:
```
'NOT' => [
	'UserPermission.restaurant_id' => 1,
	'UserPermission.role_id' => 2,
],
```

### What happened
The output of this in Cake 3.x is:
```
NOT ((`UserPermission`.`restaurant_id` = 1 AND `UserPermission`.`role_id` = 2))
```
which gives me different results than it did in Cake 2.x

### What you expected to happen
I would expect the query to be:
```
NOT (`UserPermission`.`restaurant_id` = 1) AND NOT (`UserPermission`.`role_id` = 2)
```
Like it happens in Cake 2.x

**Comment by dereuromark** [comment]
Why is that important? The result is the same.

**Comment by saeideng** [comment]
you can create your query that you want cake 3 supports 
https://book.cakephp.org/3.0/en/orm/query-builder.html#advanced-conditions

**Comment by IonutBurlacu** [comment]
I modified to this:
```
'NOT' => [
	['UserPermission.restaurant_id' => 1],
	['UserPermission.role_id' => 2],
],
```
but there is no change in the query conditions.
