### ISSUE TITLE
Suggestion postLink to specific postLinkDelete #13741  (sorry markstory, I closed it by mistake)

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13743]
sorry, I closed it by mistake  https://github.com/cakephp/cakephp/issues/13741

* [x] enhancement

![pr1](https://user-images.githubusercontent.com/50879411/66715840-7f6d5c80-ed9e-11e9-8b06-cfdf0a96392a.png)

**_index.ctp or edit.ctp or view.ctp_** or....

`<?= $this->ViewExt->postLinkDelete (
	'<span class="fa fa-trash"></span><span class="sr-only">' .
	__('Delete') . '</span>',
	['action' => 'delete', $user->id],
	[
	'escape' => false, 'title' => __('Delete'),
	'class' => '**_actions-table_**',
	'confirm' => __('Are you sure you want to delete # {0}?', $user->id)
])?>`

IN ### AppView.php:

...
`public function initialize()
{
parent::initialize();
$this->loadHelper('ViewExt');
...`

### CSS

`.cake-error a,
.cake-error a:hover {
    color:#fff;
    text-decoration: underline;
}
.actions-table {
    background-color: transparent;
}
.actions-table:hover {
    background-color: transparent;
    color: white;
}
**.modal-delete** {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1050;
    display: none;
    width: 100%;
    height: 100%;
    overflow: hidden;
    outline: 0;
    background-color: rgba(0, 0, 0, 0.6);
}`

### ViewExtHelper.php

`< ? php
namespace Cake\View\Helper;

class ViewExtHelper extends FormHelper
{
    public function      postLinkDelete     ($title, $url = null, array $options = [])
    {

           ... original code ...

           /*
            $options['onclick'] = $this->templater()->format('confirmJs', [
            'confirmMessage' => $this->_cleanConfirmMessage($confirmMessage),
            'formName' => $formName,
            'confirm' => $confirm
            ]);
            */

        $options['data-toggle'] = 'modal';
        $options['data-target'] = '#' . $formName . '-modal';
        $append = '';
        $append .= '<div class="       modal-delete        modal-danger fade text-left clearfix" id="' . $formName . 
            '-modal" tabindex="-1" role="dialog" aria-labelledby="#' . $formName . '-label" aria-hidden="true">';
        $append .= ' <div class="modal-dialog">';
        $append .= ' <div class="modal-content **_cake-error_**">';
        $append .= ' <div class="modal-header">';
        $append .= ' <h4 class="modal-title" id="#' . $formName . '-label">' . __('Confirm Delete') . '</h4>';
        $append .= ' <button type="button" class="close" data-dismiss="modal" aria-label="Close">';
        $append .= ' <span aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></span>';
        $append .= ' </button>';
        $append .= ' </div>';
        $append .= ' <div class="modal-body">
                            <p></p>' . $confirmMessage . '<p></p>';
        $append .= '
                        </div>';
        $append .= ' <div class="modal-footer">';
        $append .= ' <button type="button" class="btn btn-light waves-effect" data-dismiss="modal">' . __('No') . '</button>';
        $append .= $this->Html->link(__('Yes'), '#', array('class' => 'btn btn-dark waves-effect waves-light', 'onclick' => $onClick));
        $append .= ' </div>';
        $append .= ' </div>';
        $append .= ' </div>';
        $append .= '</div>';

        $out .= $this->Html->link($title, $url, $options) . $append;

        return $out;
    }
}
`

**Comment by ADmad** [comment]
Thank you for your suggestion but we don't use bootstrap (or any other frontend lib) for the default app skeleton which provides javascript based modal dialogs.

Users can use custom bake templates with additional markup you have shown for frontend let b of their choice.

**Comment by LuizMarin** [comment]
> Thank you for your suggestion but we don't use bootstrap (or any other frontend lib) for the default app skeleton which provides javascript based modal dialogs.
> 
> Users can use custom bake templates with additional markup you have shown for frontend lib of their choice.

thank you for the explanation
