### ISSUE TITLE
Suggestion postLink   to  specific   postLinkDelete

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13741]
* [x] enhancement

* CakePHP Version: 3.8.x last update

### What happened

Cakephp has incredible power of customization.

For practicality and elegance (really catch the user's eye) a specific postLink for deleting records.

Attached, what I called 'postLinkDelete'. It's exactly the same as the original 'postLink', but customized to get attention.

Thanks for listening.

[pr1_php.txt](https://github.com/cakephp/cakephp/files/3721142/pr1_php.txt)
![pr1](https://user-images.githubusercontent.com/50879411/66707545-61f5af80-ed18-11e9-9a22-4233551fde4b.png)
[pr1_css.txt](https://github.com/cakephp/cakephp/files/3721143/pr1_css.txt)

**Comment by markstory** [comment]
How would this additional HTML be displayed/hidden?

**Comment by LuizMarin** [comment]
index.ctp or edit.ctp or view.ctp or....

                           <?= $this->**_ViewExt->postLinkDelete_**(
                                    '<span class="fa fa-trash"></span><span class="sr-only">' .
                                        __('Delete') . '</span>',
                                    ['action' => 'delete', $user->id],
                                    [
                                        'escape' => false, 'title' => __('Delete'),
                                        'class' => 'actions-table',
                                        'confirm' => __('Are you sure you want to delete # {0}?', $user->id)
                                    ]
                                )
                                ?>

IN AppView.php:
...
    public function initialize()
    {
        parent::initialize();
        **_$this->loadHelper('ViewExt');_** 
  ...
