### ISSUE TITLE
4.x TranslateTrait doesn't allow setting translation if the locale already exists in the DB

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#13756]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-beta4
* Platform and Target: MAMP, PHP 7.3.8

### What you did
Tried to translate and persist translation using ShadowTableStrategy

### What happened
Translation not persisted

### What you expected to happen
Translations should persist

Hey guys. First off, I can't wait for 4, it looks awesome. This issue is something that I noticed in 3 but just made my own TranslateTrait to get around. But it might be tripping up other people somewhere. If you have a DB record for a locale, then try updating it, it won't persist if the locale of the request matches the locale of the translated record.

PHP:
```
// Controller
$foo = TableRegistry::get('Foo');
$thing = $foo->get(1);
$thing->translation('en_us')->set(['title' => 'Test US']);
$thing->translation('de_de')->set(['title' => 'Test DE']);
$foo->save($thing);

// Table
namespace App\Model\Table;

use Cake\ORM\Behavior\Translate\ShadowTableStrategy;
use Cake\ORM\Table;

class FooTable extends Table
{
    public function initialize(array $config): void
    {
        $this->addBehavior(
            'Translate',
            [
                'fields' => ['title'],
                'strategyClass' => ShadowTableStrategy::class
            ]
        );
    }
}

```

SQL:
```
CREATE TABLE `foo` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `foo_translations` (
  `id` int(11) unsigned NOT NULL,
  `locale` varchar(7) NOT NULL,
  `title` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`,`locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `foo` (`id`)
VALUES
	(1);

INSERT INTO `foo_translations` (`id`, `locale`, `title`)
VALUES
	(1, 'en_us', 'test');
```

The controller code when hit will create a de_de record in foo_translations. It *won't* update the en_us translation. It *will* update the de_de translation even if that already exists. This is because in `TranslateTrait` there's this:
```
if ($language === $this->get('_locale')) {
    return $this;
}
```

This skips the `->translation('en_us')` setter. Is there a reason that's there? My custom TranslateTrait that I've used since 3 just removes that line, and I'd rather just use the core if possible.

Thanks!

**Comment by markstory** [comment]
Would you be open to making a pull request to remove those lines? We can see what CI thinks of the proposed change and go from there.

**Comment by patrickconroy** [comment]
Sure I’ll be able to tomorrow morning. I just don’t know if the the current locale is guarded for some reason - but like you said hopefully the tests pass.

**Comment by ADmad** [comment]
This is not a bug. By design the `TranslateBehavior` expects the default locale to be in the primary table itself, so your `foo` table is supposed to have a title field.

This design allows using the primary locale as fallback if a translation for particular language doesn't exist.

If you want all your locales to be in the translations table then easy way to achieve that is simply set `defaultLocale` config to a dummy non-existent locale.

**Comment by patrickconroy** [comment]
Ok I figured it was something like that.
Just noting that this design to me is clunky, the fallback could be gleaned from the translation table (That’s what I did in my custom ShadowTranslate behavior for 3.) If the fallback is in the main table then you have to have fields in both the main and translation table that have matching schemas and to me is less DRY than it should be. 
As you said though, to get around this I could set the defaultLocale to something else, or set the locale to a dummy one prior to the fields’ setting.

**Comment by ADmad** [comment]
Implementing a fallback mode with primary locale when having all locales are in translation field would require additional code and also unnecessary extra joins even for primary locale. While currently all that's needed to achieve your use case is setting `defaultLocale` to a dummy value. So I say current implementation is just fine as it doesn't require additional effort for either use case :slightly_smiling_face:.

**Comment by ADmad** [comment]
If you are interested you can explore disabling primary locale by setting `defaultLocale` to `false` and see if the code/tests need to be updated. We could then document this instead of suggesting people to set `defaultLocale` to a dummy value.

**Comment by patrickconroy** [comment]
Thanks, I’ll check that tomorrow and see if setting it to false works for me.
And just saying that for me the code update was worth it. I manage a bunch of sites that use ShadowTranslate, and the amount of translation tables that I have in total is probably close to 100. So, between having 100 duplicated schemas or using custom translate stuff I went with that. I’m not in front of my comp, but I think my code extracts the default from the already-existing hasMany _i18n translations which matches the default and returns it if the hasOne is null.
I understand that’s probably too late to be in 4, but it still makes sense to me that for users the DB is cleaner/easier to maintain than the core. Of course keeping the default in the main table might make more sense to a lot of people, so I guess it doesn’t become much of an issue until you dev on a larger scale. For e.g., change the main table from varchar(255) to varchar(500), then change it in the translation table. Or change the charset in two places, etc.
