### ISSUE TITLE
Invalid security exception when an integer is used in postLink data

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13751]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.19.
* Platform and Target: Apache, MySQL.

### What you did
```
$anotherId = 123;
echo $this->Form->postLink(
    'Add',
    [
        'controller' => 'my_controller',
        'action' => 'add',
    ],
    [
        'escape' => false,
        'data' => [
            'MyModel' => [
                'another_id' => $anotherId,
            ],
	],
    ]
);
```

### What happened
After pressing on the post link the form is submitted to `add` action and the exception is thrown in lib/Cake/Controller/Component/SecurityComponent.php line 247:
> Tampered field 'MyModel.another_id' in POST data (expected value '123' but found '123')

The error message itself makes no sense.

### What you expected to happen
I would expect no errors.

**Comment by markstory** [comment]
Does the error go away if you cast the value to a string first?

**Comment by bancer** [comment]
> Does the error go away if you cast the value to a string first?

Yes but it is quite difficult to find all the places where it should be casted.

**Comment by markstory** [comment]
Perhaps FormHelper could cast integer/float values so there aren't type mismatches.

**Comment by dereuromark** [comment]
If there is no one interested in fixing this up, we will have to close.

**Comment by bancer** [comment]
I could try to fix that.
