### ISSUE TITLE
extra option in select - formHelper - 3.x

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#13765]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest commit on master ( https://github.com/cakephp/cakephp/commit/2ace767 / include v3.8.5 )

### What you did
according to document ....
```php

echo $this->Form->date('registered', [
    'minYear' => 2018,
    'monthNames' => false, // Months are displayed as numbers
    'empty' => [
        'year' => 'Choose year...', // The year select control has no option for empty value
        'month' => 'Choose month...', // The month select control does, though
    ],
]);
```
result 
```php
<select name="registered[year]">
       <option value="" selected="selected">Choose year...</option>
       <option value="2024">2024</option>
         ....
       <option value="2018">2018</option></select>
<select name="registered[month]">
       <option value="" selected="selected">Choose month...</option>
       <option value="01">1</option>
       ...
       <option value="12">12</option>
</select>
<select name="registered[day]">
       <option value="year">Choose year...</option>
       <option value="month">Choose month...</option>
       <option value="01">1</option>

       ...
       <option value="31">31</option>
</select>
```

### What happened
extra option in invalid place :) 

### What you expected to happen
as you can see there are 2 options in `day` select that is incorrect 
because `day` is `true` by default in `empty` option 
```php
    'empty' => [
        'day` => true
    ],

       <option value="year">Choose year...</option>
       <option value="month">Choose month...</option>
```

**Comment by saeideng** [comment]
If i change the `empty` to 
```php
'empty' => ['------']
```
it generates 
```php
<select name="registered[day]">
   <option value="0">------</option>  <---- see this line 
   <option value="01">1</option>
```

value `0` here is not expected 
same as for `year` and `month`

**Comment by dereuromark** [comment]
I agree that `'empty' => ['------']` should be the same as verbose `'empty' => ['' => '------']` as the numeric number creates issues along the way. The empty string for the "empty" key seems more intuitive.

**Comment by markstory** [comment]
We have existing tests and potentially applications that rely on the empty option being able to have a real value. `0` is a potentially valid empty value so I don't think we should erase it.

There are some tests for the array style empty options, but they are not very robust as they've missed this problem :cry:
