### ISSUE TITLE
Log connection id to queries log or use different log files

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13768]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5.
* Platform and Target: Linux, Apache, MySQL.

### What you did
Enabled queries log.

### What happened
All queries are logged to the same file. But it is quite difficult to understand when multiple database connections are used and it is impossible to debug database transactions as it is not clear on what connection the query is executed.

### What you expected to happen
I would expect each database connection to use it's own query log or if one log file is used then to record also the connection id.

**Comment by markstory** [comment]
Including the connection name is a good idea. Logging to multiple files could work but would logged queries to have addition scopes applied so that loggers could select those scopes.

**Comment by ADmad** [comment]
One can extend `Cake\Database\Log\QueryLogger` and override relevant parts and use `Connection::setLogger()` to use their custom logger instance. (In 4.0 it can be any `\Psr\Log\LoggerInterface` instance).

**Comment by dereuromark** [comment]
@bancer Do you want to make a PR here to improve this for 4.0 or 3.9?
Otherwise, we close and let user land (or plugin) code handle this.

**Comment by bancer** [comment]
I can give a try a bit later.

**Comment by othercorey** [comment]
Would you just want the connection name prefixed like this?  I don't think the connection name is set in most cases and most of the documentation doesn't mention it.

`[name] query`

**Comment by bancer** [comment]
@othercorey My thought was to have the connection id. Something like the value of `SELECT CONNECTION_ID()` in MySQL.

**Comment by othercorey** [comment]
If you want connection id, I think you could use a custom logger. I'm not sure how that will help users trying to identify multiple connections.

I think the name configuration could be clear as long as the user sets it.

**Comment by bancer** [comment]
Different connections may have the same connection name.

**Comment by othercorey** [comment]
Moved discussion to PR.
