### ISSUE TITLE
Collection::sumOf() requires an int return type

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13763]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-beta4.

### What you did
Ran `sumOf()` on a float field.

### What happened
PHP error on return types not matching.

>Uncaught TypeError: Return value of Cake\Collection\Collection::sumOf() must be of the type int, float returned in /var/wasterev/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php:331

### What you expected to happen
Allow both float and int values.

I'm 99% sure this is just a return typo, but seemed odd to run into it this late.

CollectionInterface::sumOf() does not specify a return type, but does show 'float|int' in the type hint.

```
     * @return float|int
     */
    public function sumOf($matcher = null);
```

CollectionTrait::sumOf() does specify a return type but inherits docblock.

```
    /**
     * @inheritDoc
     */
    public function sumOf($matcher = null): int
```

**Comment by ADmad** [comment]
Close as related PR is open.
