### ISSUE TITLE
cake4.   Not load "cake server"

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13777]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: cake4, updated with "composer update".
* Platform and Target: cake server, meysql, windows10.

### What you did
Does not reload the server. It worked the first time, I gave "ctrl + C" to do something else, I didn't do it, I reloaded it and ... it doesn't work.

I tested 3.8.5: OK. I returned to cake4. Does not reload server.

### What you expected to happen
Yesterday it worked. Not today. If it does not load server, I can not test. If I can not test: :(

![erro8](https://user-images.githubusercontent.com/50879411/67094897-16655a80-f18b-11e9-922b-cf8e4d219cad.png)

**Comment by dereuromark** [comment]
Don't use cake from the bin directoy, that screws up paths.
Always use the documented and recommended approach, running it relative from your app dir:
```
bin/cake
```

This is user error. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
