### ISSUE TITLE
Blank Association Is Not Defined

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#13794]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1
* Platform and Target: LAMP

### What you did
        $menuNotifications = TableRegistry::get('AdminLTE.AdminLTEMenuNotifications');
        $linkNotifications = $menuNotifications->find('all', ['contain' => 'AdminLTEMenuNotificationLogs']);
        $linkNotifications->select(['total' => $linkNotifications->func()->sum('notification_count')])
            ->where(['menu_title' => $menuItem['link'], 'menu_group' => $menuItem['link']])
            ->where(['destination' => 'User', 'user_id' => $user_id])
            ->orWhere(['destination' => 'Global'])
            ->orWhere(['destination' => 'Role', 'role_id' => $role]);
        $linkNotifications->notMatching(['AdminLTEMenuNotificationLogs' => function (\Cake\ORM\Query $query) use($user_id) {
            return $query->where(['AdminLTE\Model\Entity\AdminLTEMenuNotificationLog.user_id' => $user_id]);
        }]);
        debug($linkNotifications);
        $linkNotificationsResult = $linkNotifications->first();
        $linkNotificationsResultTotal = $linkNotificationsResult->total;

### What happened
![Screen Shot 2019-10-23 at 6 23 36 AM](https://user-images.githubusercontent.com/2320614/67383690-ac1f3200-f55d-11e9-9c85-53043aaa592b.png)

![Screen Shot 2019-10-23 at 6 23 22 AM](https://user-images.githubusercontent.com/2320614/67383704-b2ada980-f55d-11e9-8731-e3a4244f63bf.png)

### What you expected to happen
The tables to be associated, and if not, for the error message to tell me what association...

Here is the table associations...

AdminLTEMenuNotifications
====================
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('admin_l_t_e_menu_notifications');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->hasMany('AdminLTEMenuNotificationLogs', [
            'foreignKey' => 'admin_l_t_e_menu_notification_id',
            'className' => 'AdminLTE.AdminLTEMenuNotificationLogs'
        ]);
    }

AdminLTEMenuNotificationLogs
=======================
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('admin_l_t_e_menu_notification_logs');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('AdminLTEMenuNotifications', [
            'foreignKey' => 'admin_l_t_e_menu_notification_id',
            'joinType' => 'INNER',
            'className' => 'AdminLTE.AdminLTEMenuNotifications'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
            'className' => 'AdminLTE.Users'
        ]);
    }

**Comment by ndm2** [comment]
`Query::notMatching()` doesn't take an array, but a string and an optional callable as separate arguments.

**https://api.cakephp.org/3.8/class-Cake.ORM.Query.html#_notMatching**

**Comment by jeffreyroberts** [comment]
My apologies, my IDE said that to me too, and I took it out of an array, but when I did that, it returned a 500 error, so I thought my IDE was wrong... Any ideas why it is throwing a 500 error when I make it a string rather than an array? =]

![Screen Shot 2019-10-23 at 6 43 54 AM](https://user-images.githubusercontent.com/2320614/67385175-9828ff80-f560-11e9-9f0d-1873ff178f46.png)

**Comment by jeffreyroberts** [comment]
I also thought my IDE was wrong because of answer you posted on stackoverflow

https://stackoverflow.com/a/33372036/1150847

**Comment by jeffreyroberts** [comment]
Figured out the 500 error, looking into the blank association now

**Comment by ndm2** [comment]
> I also thought my IDE was wrong because of answer you posted on stackoverflow
> 
> https://stackoverflow.com/a/33372036/1150847

That was a "typo", sorry... fixed.

**Comment by jeffreyroberts** [comment]
fixing the array to string, and making the anonymous function a second parameter, fixed the blank association, thank you ndm =]
