### ISSUE TITLE
Auth Component _unauthenticated should accept return value as boolean

### ISSUE THREAD

**Issue by chetanvarshney** [cakephp/cakephp#13807]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-beta4
* Platform and Target: Windows 10 FIrefox Nightly 72.0a1 (2019-10-21) (64-bit) Wamp Apache php 7.2.14, Mysql 5.7.24

### What you did
Custom unauthenticated function in plugin to check guest permission of action.

### What happened
If guest permission is available then this function should return true (Boolean).

### What you expected to happen
Auth component following functions must accept return value as Boolean
startup()
authCheck()
_unauthenticated()

**Comment by ADmad** [comment]
`AuthComponent` is deprecated in 4.x and hence won't be getting any enhancements. You should look into the new [Authentication](https://github.com/cakephp/authentication/tree/2.x) lib instead.

**Comment by chetanvarshney** [comment]
I am not asking for enhancement, this is bug and should be fixed.
I know Auth component is deprecated, deprecated functions always work with warning but due to this bug it's not working

**Comment by ADmad** [comment]
Sorry for closing. I still don't understand the problem. Can you please provide example code which worked in 3.x but doesn't work in 4.x.

**Comment by chetanvarshney** [comment]
Yes I can try to explain.
I am working on plugin user management system. which also handles permission of controller's actions for guests and logged in users.

So in plugin's custom auth component in beforeFilter function I configured core Auth component this way
```
if(isset($this->controller->Auth)) {
	$this->controller->Auth->setConfig('authenticate', [
		'Usermgmt.Permission'
	]);
	
	$this->controller->Auth->setConfig('authorize', [
		'Usermgmt.Permission'
	]);
	
	$this->controller->Auth->setConfig('loginAction', [
		'controller'=>'Users',
		'action'=>'login',
		'plugin'=>'Usermgmt',
		'prefix'=>false
	]);
	
	$this->controller->Auth->setConfig('loginRedirect', LOGIN_REDIRECT_URL);
	$this->controller->Auth->setConfig('logoutRedirect', LOGOUT_REDIRECT_URL);
}
else {
	trigger_error(__('Cakephp Auth component not loaded, please load in AppController.'));
	exit;
}
```
and plugin I have PermissionAuthenticate.php (in plugins\Usermgmt\src\Auth)
```
public function unauthenticated(ServerRequest $request, Response $response) {
	if(guest do not have permission of currect action) {
		$this->controller->Auth->setConfig('authError', __('You need to be signed in to view that page.'));
		return null;
	}

	//if permission is for guest then we return true.
	return true;
}
```
This is working fine upto cakephp 3.8.x version but giving error in 4.0.0-beta4

![Screenshot_2019-10-27 Error Return value of Cake Controller Component AuthComponent _unauthenticated() must be an instance ](https://user-images.githubusercontent.com/325154/67632796-613f4a80-f8ce-11e9-87bf-c37a5c887f99.png)

**Comment by ADmad** [comment]
Even in 3.x `null` (or void) and `Response` are the only valid return values for `BaseAuthetication::unauthenticated()`.

https://github.com/cakephp/cakephp/blob/181a1e6a2a15b9db59c40e6dfa2ca88cae18cfac/src/Auth/BaseAuthenticate.php#L237-L242

So returning a boolean is incorrect usage. It's just coincidence that things worked for you. Please update your code to return values as documented.

**Comment by chetanvarshney** [comment]
Sorry in 3.x it is working in 3.7.x I will test in 3.8.x as well.
Auth component _unauthenticated() function expects either null or response interface object.
If null is returned then it redirects user to login page (as expected)
If response object is returned it show blank page.

Also please read this function commenting,

> The authenticator can handle sending response or redirection as appropriate and **return `true`** to indicate no further action is necessary. 

 /**
     * Handles unauthenticated access attempt. First the `unauthenticated()` method
     * of the last authenticator in the chain will be called. The authenticator can
     * handle sending response or redirection as appropriate and **return `true`** to
     * indicate no further action is necessary. If authenticator returns null this
     * method redirects user to login action.
     *
     * @param \Cake\Controller\Controller $controller A reference to the controller object.
     * @return \Cake\Http\Response|null Null if current action is login action
     *   else response object returned by authenticate object or Controller::redirect().
     * @throws \Cake\Core\Exception\Exception
     */
protected function _unauthenticated(Controller $controller): ?Response
{
...
}

**Comment by ADmad** [comment]
It seems the docblock for `AuthComponent::_unauthenticated()` is incorrect. There's no actually check for return value of `true` just whether the value is not `null`.

Have you tried simply removing the `return true;` from your `PermissionAuthenticate::authenticate()`? I believe things should keeping the same for you.

**Comment by chetanvarshney** [comment]
Yes tried to remove return true. behaving same as null. redirecting to login page

**Comment by ADmad** [comment]
Great. So just the docblock of  AuthComponent::_unauthenticated() needs to be fixed :slightly_smiling_face:  Would you like a submit a fix for it for 3.x (`master` branch)?

**Comment by chetanvarshney** [comment]
for your information I just upgraded cakephp 3.x upto 3.8.5 and plugin PermissionAuthenticate::unauthenticated() function is returning true and working fine.

I request you to look into issue in 4.0.0-beta4

AuthComponent::_unauthenticated() should accept return boolean value or change code to render current action view page, which is currently showing blank page.

I tried to remove function return definition from these 3 functions in Auth component.
startup()
authCheck()
_unauthenticated()

then it is working fine in 4.0.0-beta4.

what do you say ?

**Comment by ADmad** [comment]
You lost me again. In your previous comment you said:

> Yes tried to remove return true. behaving same as null

So if returning `null` behaves same as returning `true` why can't you just remove the `return true`?

**Comment by chetanvarshney** [comment]
Sorry for confusion, let me explain again
PermissionAuthenticate::unauthenticated() 

```
public function unauthenticated(ServerRequest $request, Response $response) {
      if(guest do not have permission of currect action) {
		$this->controller->Auth->setConfig('authError', __('You need to be signed in to view that page.'));
		return null;
	} else {
	    //if permission is for guest then we return true.
	    return true;
       }
}
```

In above function we have 3 options as return value
1. null //which for redirecting user to login page
2. true //which is for rending current action view page (which is not working as of now in 4.x but working in 3.8.5)
3. Response Object //which is showing/rendering blank page.

I request you to look into issue in 4.0.0-beta4

AuthComponent::_unauthenticated() should accept return boolean value or change code to render current action view page, which is currently showing blank page.

I tried to remove function return type from these 3 functions in Auth component.
startup()
authCheck()
_unauthenticated()

then it is working fine in 4.0.0-beta4.

**Comment by ADmad** [comment]
Returning `true` from `PermissionAuthenticate::unauthenticated()` is simply wrong even in 3.x. You were mislead by docblock of `AutheComponent::_unauthenticated()` which incorrectly claims the authenticator can return true.

For you 3.x and as well as 4.x app code change your `PermissionAuthenticate::unauthenticated()` method to not return `true`:

```php
public function unauthenticated(ServerRequest $request, Response $response) {
      if (guest do not have permission of currect action) {
		$this->controller->Auth->setConfig('authError', __('You need to be signed in to view that page.'));
      }
}
```

**Comment by chetanvarshney** [comment]
I agree we should not return boolean value. then what is the solution ?
we should return some value to AutheComponent::_unauthenticated() function, to tell whether user has permission to view current action or not.

If we are not returning anything like you suggested, it redirecting user to login page in both cases (has permission or has not permission).

**Comment by ADmad** [comment]
I think I finally understand your use case. You neither want to return a response nor redirect to login page. You just want to let the normal page rendering to continue where the `authError` message you set will be shown, right?

**Comment by chetanvarshney** [comment]
no, what I want here it is.
1. If Guest has permission to view current action then render just view
2. If Guest has not permission just redirect to login page with error message (set in authError)

That's it

**Comment by ADmad** [comment]
> If Guest has not permission just redirect to login page with error message (set in authError)

That's what you get even after removing the `return true` in your `PermissionAuthenticate::unauthenticated()`, so why can't you just do that?

**Comment by chetanvarshney** [comment]
Still you are not understanding issue, I do not know why.

Redirecting to login page is not issue.
Issue is how to render current action view for guest ??

**Comment by ADmad** [comment]
Does the following change fix your problem?

```
diff --git a/src/Controller/Component/AuthComponent.php b/src/Controller/Component/AuthComponent.php
index 901bf5510c..c979f4a021 100644
--- a/src/Controller/Component/AuthComponent.php
+++ b/src/Controller/Component/AuthComponent.php
@@ -354,7 +354,7 @@ class AuthComponent extends Component implements EventDispatcherInterface
         }
         $result = $auth->unauthenticated($controller->getRequest(), $response);
         if ($result !== null) {
-            return $result;
+            return $result instanceof Response ? Response : null;
         }
 
         if (!$controller->getRequest()->is('ajax')) {
```

**Comment by chetanvarshney** [comment]
yes only if we return true from PermissionAuthenticate::unauthenticated()
also 
added line should be return $result instanceof Response ? $result : null;

**Comment by ADmad** [comment]
I have opened a PR with the proper fix #13808.

Sorry for taking so long to understand your issue. The docblock of `BaseAuthenticate::unauthenticated()` lying about possible return values really threw me off. Can you please submit a PR to update the docblock for 3.x?

**Comment by chetanvarshney** [comment]
> Can you please submit a PR to update the docblock for 3.x?

To be honest this is my first issue on github/cakephp, I have no idea how to do that. I would love to learn.

**Comment by ADmad** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by othercorey** [comment]
I am curious, where is the change that "broke" this?  The logic hasn't changed since 3.8 from what I see.

**Comment by chetanvarshney** [comment]
the issue is with return type only. the same code is working on cakephp 3.8.5

**Comment by ADmad** [comment]
> Are you actually just hitting a php error on return type or was 4.0 actually behaving differently?

The addition of return typehint in 4.0 has highlighted the incorrect value returned by `AuthenticateComponent::_unauthenticated()`. Even though things work in 3.x, it shouldn't return true.

**Comment by othercorey** [comment]
> The addition of return typehint in 4.0 has highlighted the incorrect value returned by `AuthenticateComponent::_unauthenticated()`. Even though things work in 3.x, it shouldn't return true.

Got it.  The logic just accidentally worked with true up the chain.
