### ISSUE TITLE
The @link references in 4.x branch point to 3.0 book

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13804]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x branch

There are @link references to the book documentation using 3.0 link.

Should these be manually updated or is there some global script that runs before 4.0.0 is released?

https://github.com/cakephp/cakephp/blob/2c50b16c2be2a47dc00d9d867d3f8171507b5ba8/src/Utility/Hash.php#L31

**Comment by ADmad** [comment]
We don't have any script, though it would be pretty easily done with a search / replace.

That said the links should still require checking manually a some might no longer be valid.

**Comment by othercorey** [comment]
```
$ grep -r --include="*.php" "https://book.cakephp.org/3.0/" . | wc -l
217
```

**Comment by othercorey** [comment]
@ADmad I don't mind doing this fix-up, but I'm going to wait until the docs URL change is done.  I think it'll be easier to change master to /3/, let that merge to 4.x branch and then update 4.x branch to /4/.

**Comment by othercorey** [comment]
This is completed.
