### ISSUE TITLE
Call to an undefined method Cake\Datasource\ConnectionInterface::query()

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13814]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5
* Platform and Target: Linux, Apache, MySQL.

### What you did
```
$Connection = ConnectionManager::get('default');
$Connection->query($sql);
```
and executed `phpstan analyse --level=2`.

### What happened
Got an error:
```
  31     Call to an undefined method                    
         Cake\Datasource\ConnectionInterface::query().
```

### What you expected to happen
I would expect no error. I think `query()` method should be either defined in ConnectionInterface or ConnectionManager::get() should have the correct `@return` annotation.

**Comment by markstory** [comment]
We can't extend the interface at this point as it is a breaking change. Have you considered using the `prepare()` and `execute()` methods instead? They are part of the interface's methods and allow you to use prepared statements which are recommended over raw SQL.

**Comment by bancer** [comment]
@markstory I will give it a try but in some cases it makes more sense to use `query()` method than `execute()`, f.ex. `$sql = 'SHOW TRIGGERS FROM my_database';`

**Comment by ADmad** [comment]
`query()` method can't be added to `ConnectionInterface` as it's meant to be a generic interface for  datasources. For e.g. `elastic-search` plugin's `Connection` class implements `ConnectionInterface` but doesn't have (or need) a `query()` method.

You can prevent static analyzers from complaining by using inline annotation:

```php
/** @var \Cake\Database\Connection */
$Connection = ConnectionManager::get('default');
```

**Comment by ADmad** [comment]
Another option is we add a `@method` annotation to the `ConnectionInterface`, we already have it for various other methods of  `Connection` class.

**Comment by ADmad** [comment]
> Have you considered using the prepare() and execute() methods instead? They are part of the interface's methods...

Nope they aren't. We just have `@method` annotations for those methods too on the interface.
