### ISSUE TITLE
Fixture throws error trying to create Products table

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13820]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x

### What you did
Run the phpunit tests.

### What happened
I seem to get this error about the products table already existing.  Has this been investigated?

>PHP Warning:  Fixture creation for "products" failed "SQLSTATE[HY000]: General error: 1 table "products" already exists" in /home/travis/build/othercorey/cakephp/src/TestSuite/Fixture/TestFixture.php on line 295

This is currently triggering a larger failure.

>Warning: Fixture creation for "products" failed "SQLSTATE[HY000]: General error: 1 table "products" already exists" in /home/travis/build/othercorey/cakephp/src/TestSuite/Fixture/TestFixture.php on line 295
>PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: products.category, products.id in /home/travis/build/othercorey/cakephp/src/Database/Statement/StatementDecorator.php:178

**Comment by markstory** [comment]
Were you running tests with SQLite?

**Comment by othercorey** [comment]
Yea, it was failing on sqllite. I was trying to run 4.x tests against a custom chronos branch and it was just 100% hitting this.

**Comment by markstory** [comment]
SQLite gets salty about removing/adding tables and having that error output is pretty normal. It is theoretically fixable but I don't think anyone has dedicated time to it when the tests are passing.

**Comment by dereuromark** [comment]
I would consider closing then for now as we can't do too much about this.

**Comment by othercorey** [comment]
I was looking at it.  The issue is caused by a specific test.  This issue makes all the tests catch and ignore exceptions.

Give me a little bit of time then can ignore it :)

**Comment by othercorey** [comment]
I'll post a PR if I fix it.
