### ISSUE TITLE
Recommended middleware order

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13838]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8.5
* Platform and Target: not relevant

(Maybe this would fit more into cakephp/docs)

With recent changes to Authentication/Authorization process and general process of shifting components into middlewares, I'm missing overall recommendations on **in which order should middlewares be applied**

Given basic app skeleton, using ErrorHandlerMiddleware, AssetMiddleware and RoutingMiddleware, adding AuthenticationMiddleware and AuthorizationMiddleware, CsrfMiddleware. 

In which order should the be applied in Application->middleware($middlewareQueue) ?
Is there any general rule that one can follow, or should the order matter only in case of *some* middlewares?
Also **should the correct order be checked by core/framework, at least in some cases, or not at all?**

- Documentation for Authorization says in comment "Add authorization (after authentication if you are using that plugin too)." ( https://book.cakephp.org/authorization/1.1/en/index.html )
- Authentication docs do not say anything ( https://book.cakephp.org/authentication/1.1/en/index.html )
- Documentation on Middlewares does not mention order at all ( https://book.cakephp.org/3/en/controllers/middleware.html )
- Basic skeleton (from composer) uses RoutingMiddleware as the last in the queue, however that is not mentioned anywhere in the docs or examples, if RoutingMiddleware should be always the last one
- etc...

**Comment by markstory** [comment]
> ... missing overall recommendations on in which order should middlewares be applied

I don't think there are any hard rules. If your authentication adapters don't require routing to build login/logout URLs then it could go before the RoutingMiddleware. If you are using Router to make URLs then authentication needs to be *after* RoutingMiddleware.

> Is there any general rule that one can follow, or should the order matter only in case of some middlewares?

The order matters for certain middleware. We could outline the dependencies better in each plugin's documentation.

> Also should the correct order be checked by core/framework, at least in some cases, or not at all?

I don't think this is possible. We could could check against a fixed ordering, but I'm not sure how that would work.

**Comment by smarek** [comment]
It would be great if the documentation improved in this way, and also it might be useful to either provide order validation mechanism within middleware (warning about missing recommended or throwing error about missing required middlewares in the queue), or in documentation use for example `$middlewareQueue->insertAfter` which would avoid the confusion on developer side, as each new middleware addition would have explicitly listed requirements of middlewares that should precede in usual situations.

**Comment by saeideng** [comment]
>Documentation on Middlewares does not mention order at all ( https://book.cakephp.org/3/en/controllers/middleware.html )

it mentioned , section https://book.cakephp.org/3/en/controllers/middleware.html#using-middleware

```
In addition to adding to the end of the MiddlewareQueue you can do a variety of operations:
```
```php
$layer = new \App\Middleware\CustomMiddleware;

// Added middleware will be last in line.
$middlewareQueue->add($layer);

// Prepended middleware will be first in line.
$middlewareQueue->prepend($layer);

// Insert in a specific slot. If the slot is out of
// bounds, it will be added to the end.
$middlewareQueue->insertAt(2, $layer);

// Insert before another middleware.
// If the named class cannot be found,
// an exception will be raised.
$middlewareQueue->insertBefore(
    'Cake\Error\Middleware\ErrorHandlerMiddleware',
    $layer
);

// Insert after another middleware.
// If the named class cannot be found, the
// middleware will added to the end.
$middlewareQueue->insertAfter(
    'Cake\Error\Middleware\ErrorHandlerMiddleware',
    $layer
);

```

when you can add Middleware in your needed place/order
it  says implicit  that order is important   :)


>Authentication docs do not say anything ( https://book.cakephp.org/authentication/1.1/en/index.html )

fell free to open  PRs where you want

**Comment by dereuromark** [comment]
Yeah, one needs to carefully set up the order as per use case - and most docs mention already basic order issues like direct dependencies.
Closing then for now. PRs to docs to further improve welcome.
