### ISSUE TITLE
ORM: Add support to lag() and lead() 

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#13835]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

In the last years, a powerful function that allow recover the row that precedes (lag) or succeeds (lead) was added in SGBDs like:

- **MySQL ** 8.0>= ([dbfiddle](https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=b8368c46ef03356e2778e8d21c898aaa))
- **SQL Server ** 2012 >= ([dbfiddle](https://dbfiddle.uk/?rdbms=sqlserver_2012&fiddle=3c0ef5224dc1e76ebbf3f3b1679d9df0))
- **Postgres** ?? version >= ([[dbfiddle](https://dbfiddle.uk/?rdbms=postgres_12&fiddle=6b9ff041139e6140414ba612b8a05f63)])
- SQLite ?? version >= ([dbfiddle](https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=293e1e2620fd5ee738e31819bcf4811e))

All running the same syntax (example):

```sql
SELECT
     company,
     quote,
     LAG(quote) OVER(PARTITION BY company ORDER BY time) AS prev_quote
FROM tab
```

Recently, I have had a real necessity to use this on CakePHP because we need to retrieve all of LawSuits that had a specific type of new Proceedings and their respective proceedings before that.

Using custom [func()](https://book.cakephp.org/3/en/orm/query-builder.html#function-arguments) was not so cool and not easy at all. 
So, as a CakePHP entusiast, I believe that lag() and lead() would be very welcome on [this list](https://book.cakephp.org/3/en/orm/query-builder.html#using-sql-functions).

Thanks in advance,
Celso

**Comment by ndm2** [comment]
I'm using custom expressions for this currently, and things grew quite a little too complex.

If support for windows would be added, then it would be nice if a broad range of window functions (respectively any (function) expression) would be supported, and named windows would be nice too :upside_down_face:

**Comment by markstory** [comment]
What would be the API you would want to see for these functions?

**Comment by celsowm** [comment]
How about:
`
$query = $this->Articles->find();

$query->select(['last'=>$query->windowFunc()->lag('date', $lagOptions)] );
`
Of course the lag(or lead) options will be the hardest thing to implement. But, in my humble opinion could be things like:

- offset: positive integer or expr() 
- default: a literal, a column name or expr()
- over: the most complex thing, but the first thing in my mind is expr() too

Ps.: I tried to create this pseudo api using mobile on my daily commute. Mobile github is a pain in a**

**Comment by markstory** [comment]
To expand on your example would

```sql
SELECT
     company,
     quote,
     LAG(quote) OVER(PARTITION BY company ORDER BY time) AS prev_quote
FROM tab
```

be achieved with

```php
$query->select([
  'last' => $query->func()->lag('quote', [
    'partition' => 'company',
    'order' => ['time' => 'desc']
  ])
]);
```

Or would we want a more fluent API like

```php
$query->select([
  'last' => $query->func()->lag('quote')
    ->partitionBy('company')
    ->orderBy('time', 'desc')
]);
```

Given the work we've been doing around improving typehinting, I prefer the second approach.

**Comment by celsowm** [comment]
> 
> 
> To expand on your example would
> 
> ```sql
> SELECT
>      company,
>      quote,
>      LAG(quote) OVER(PARTITION BY company ORDER BY time) AS prev_quote
> FROM tab
> ```
> 
> be achieved with
> 
> ```
> $query->select([
>   'last' => $query->func()->lag('quote', [
>     'partition' => 'company',
>     'order' => ['time' => 'desc']
>   ])
> ]);
> ```
> 
> Or would we want a more fluent API like
> 
> ```
> $query->select([
>   'last' => $query->func()->lag('quote')
>     ->partitionBy('company')
>     ->orderBy('time', 'desc')
> ]);
> ```
> 
> Given the work we've been doing around improving typehinting, I prefer the second approach.

so cool !!! :D 
I do love **Fluent Interface** !!!

So, How about a more complex situation too?

## easy:

sql:

 ```sql
SELECT
     company,
     quote,
     LAG(quote, 1, 'empty') OVER(PARTITION BY company ORDER BY time) AS prev_quote
FROM tab
 ```

## medium:

https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=dcf63a2cee285b8f7c321b39362dd408

## hard:

https://dbfiddle.uk/?rdbms=sqlserver_2012&fiddle=d7e99f84ef44254cbae06cb645b285cb

**Comment by garas** [comment]
This should be generalized as Window Function support, not limited to `LAG`/`LEAD`. See also #10670. 

The question is how to build `OVER` statement, function expression builder support exists already. Fluent interface for `OVER` would be nice.

I imagine it as `$query->windowFunc()->lag()` with similar interface to `func()`, but would return `OVER` builder with initially empty `OVER()`, but it could be further built fluently with `partitionBy()`, `orderBy()` and frame extent functions.

**Comment by markstory** [comment]
I don't think we need $query->windowFunc()`. The current func() builder can return a specialized `WindowExpression` that lets the various aspects of the windowing be defined. Are there additional properties that need to be defined beyond `partitionBy()` and `orderBy()`?

The additional parameters on lag could be handled like:

```php
$query->func()->lag('quote', 1, 'empty')
```

**Comment by celsowm** [comment]
It's fine for me, func().
@markstory sensei, how would be for this case:

```sql
SELECT year, 
       quarter, 
       sales, 
       LEAD(2*sales) OVER(
       ORDER BY year, 
                quarter ASC) AS NextQuarterSales
FROM product_sales;
```

**Comment by celsowm** [comment]
> 
> 
> Are there additional properties that need to be defined beyond`partitionBy()`and`orderBy()`?

```sql
SELECT year, sales,   
    LAG(year-2, 19874, sales/2.0 ) OVER (PARTITION BY (select min(quarter) from product_sales) ORDER BY year) AS no_sense  
FROM product_sales;
```

**Comment by ndm2** [comment]
> Are there additional properties that need to be defined beyond`partitionBy()`and`orderBy()`?

There's the frame part, which is pretty important, see

* **https://www.sqlite.org/windowfunctions.html#frame_specifications**
* **https://dev.mysql.com/doc/refman/8.0/en/window-functions-frames.html**
* **https://www.postgresql.org/docs/12/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS**
* **https://docs.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql**

Sqlite and Postgres kinda make the `FILTER` clause part of the window function call syntax too, as far as standard SQL goes it's part of aggregate functions AFAICT.

It should also be noted that many if not most, or even all aggregate functions, can be used as window functions too (depending on the DMBS), ie `AVG()`, `SUM()`, `MIN()`, `MAX()`, etc.

**Comment by markstory** [comment]
The `frame-spec` is a pretty complex aspect of the windowing function, and seems to not be entirely standardized. Would it be reasonable to have a method that accepts a string snippet there?

More complex window function arguments, and partition expression, like the example @celsowm provided could be handled by accepting either strings or `QueryExpression` objects.

**Comment by ndm2** [comment]
Reasonable in terms of "_being able to implement it in a not too distant future_"? Sure :)

I haven't done extensive cross DBMS testing, but if I'm not mistaken, the frame specification implementations in the supported DBMS's only differ with regards to the `GROUPS` mode and the `EXISTS` clause, which both aren't supported in MySQL and SqlServer, and what expressions are allowed for the `FOLLOWING` and `PRECEDING` bounds.

Personally I'm pretty hooked on the builder approach, as I've used it regularly in the past. If I had a more time I'd untangle and polish my custom expression stuff, and publish it, maybe something of it could be integrated :/ But I guess it could always be upgraded later on.

**Comment by othercorey** [comment]
I'm interested in adding windows functions to cakephp too!  It helps with some of the data mining analysis queries I have to run manually.

**Comment by markstory** [comment]
@ndm2 I'm also :+1: on the builder approach. I'm trying to get an idea on how fine grained we want those builder methods to be. Do we want multiple methods to populate the `frame-spec` or a single one?

**Comment by othercorey** [comment]
@markstory 

> Do we want multiple methods to populate the `frame-spec` or a single one?

We could run into a problem with the code being really difficult to read for window functions.  I'd vote for an interface that formats cleanly ... somehow.

**Comment by markstory** [comment]
I've not used frame-spec options much so I don't think I'm in a good position to recommend an abstraction for it. I would personally start off with a method that takes `string|QueryExpression` and refine the abstractions as we learn more.

**Comment by celsowm** [comment]
> 
> 
> I've not used frame-spec options much so I don't think I'm in a good position to recommend an abstraction for it. I would personally start off with a method that takes `string|QueryExpression` and refine the abstractions as we learn more.

If my vote as OP count, I think string | QueryExpression it is the best approach now. Something simple its better than nothing.

**Comment by markstory** [comment]
@celsowm Would you be interested in getting an implementation of this started, I'm happy to help with tests and the implementation.

**Comment by celsowm** [comment]
@markstory  Yes I would ! But If can, I would appreciate some tips:

- What is the best way to start ? Is it literally on **vendor\cakephp\cakephp\src\Database\FunctionsBuilder.php**?
- Where, if necessary, I could implement specificy dialect/drivers for lag() and lead()?
- For the current methods on func(), what you recommend to see as good example to have similar or near the lag() and lead() api idea?

**Comment by markstory** [comment]
> What is the best way to start ? Is it literally on vendor\cakephp\cakephp\src\Database\FunctionsBuilder.php?

Yes, FunctionsBuilder should have a new `lag()` and `lead()` methods. These methods should return a `WindowExpression` object that implements the `Cake\Database\ExpressionInterface`. This class will also have the builder methods for the windowing. An similar example would be the `CaseExpression`.

> Where, if necessary, I could implement specificy dialect/drivers for lag() and lead()?

Each SQL dialect has a `_transformFunctionExpression` method that can do platform specific transformations if necessary.

> For the current methods on func(), what you recommend to see as good example to have similar or near the lag() and lead() api idea?

`$query->func()` gives you a FunctionsBuilder, and FunctionsBuilder mostly provides methods to create new expression objects of which your `WindowFunctionExpression` would fit into. An example that closely relates to what you'd be doing is the CaseExpression.

**Comment by othercorey** [comment]
> `$query->func()` gives you a FunctionsBuilder, and FunctionsBuilder mostly provides methods to create new expression objects of which your `WindowFunctionExpression` would fit into. An example that closely relates to what you'd be doing is the CaseExpression.

The idea being the window expression is separate from lag/lead, but can be initiated by it.  Would allow you to do normal window expressions.

**Comment by celsowm** [comment]
thanks @markstory ! Now I am trying to understand (looking for others classes) what would be the best way to implement the abstract methods from ExpressionInterface sql() and traverse()

**Comment by markstory** [comment]
The `traverse()` method is intended to allow the database layer to enumerate and walk through each node/part of the expression. The `sql()` method is used to convert an expression into its SQL representation. The [CaseExpression](https://github.com/cakephp/cakephp/blob/ebc3bf8179743e45d2fa4accc27183223e1941c9/src/Database/Expression/CaseExpression.php#L212-L247) is a good example here.

**Comment by ndm2** [comment]
I took some time and extracted some somewhat cleaned up interfaces from my implementation, still a little noisy, but not near as complex and cluttered as the actual implementation. Maybe you can get some ideas from it, even if it's just an idea what to avoid ;)

https://gist.github.com/ndm2/d88261e822d6eb7b41cc4846f25c0a59

**Comment by celsowm** [comment]
Hi @markstory ! My first attempt forked is here: https://github.com/celsowm/cakephp/commit/b8b52d5a775b0a5182471a554cecbc467e747f97

Now I need advices to how is the best way to implement methods to support things like:

`SELECT LAG(2*id, 1, (SELECT MIN(id) FROM livro)) OVER (PARTITION BY id ORDER BY titulo) AS nonsense FROM livro `

**Comment by garas** [comment]
Left side of `OVER` can be built like any other SQL function as `FunctionExpression` with `$this->_build()`. It would take care of advanced expressions like `2*id` or subquery.

Built `FunctionExpression` would then be passed as the only parameter to `WindowExpression::__construct()`. `WindowExpression` would only take care of right side of `OVER` and would generate SQL as `$leftSideFunction->sql() . ' OVER(' . $rightSideExpression . ')'` without touching `WindowExpression` .

Your `lag()` would look now `return new WindowExpression($this->_build('LAG', ...));`.

Your `WindowExpression` is now specific to `LAG/LEAD`. There are more window functions with different arguments: `LAST_VALUE(expr)`, `NTH_VALUE(expr, N)`, `RANK()` etc. This way these function could be easily added too.

**Comment by celsowm** [comment]
Hi, sorry for the long delay ! I have made the changes that @garas wrote on my fork. But now I have some errors trying to using it:

` Call to a member function getTypes() on int `

` Error in: ROOT\vendor\cakephp\cakephp\src\Database\Expression\QueryExpression.php, line 73`

```
class TesteController extends AppController {
    
    public function lagLead(){
        
        $editoraTable = TableRegistry::getTableLocator()->get('Editora');
        $query = $editoraTable->find();
        $editoras = $query->select([
            'last'=>$query->func()
                ->lag('id', 2, 'not found')
                ->partitionBy('id')
                ->orderBy('id')
                ]);
        $editoras2 = $query->select([
            'last'=>$query->func()
                ->lag(['literal'=>'2 *'], 2, 'not found')
                ->partitionBy('id')
                ->orderBy('id')
                ]);
        debug($editoras2);
        
    }
```

**Comment by garas** [comment]
Could you click _Create pull request_ at https://github.com/cakephp/cakephp/compare/master...celsowm:master? It is easier to comment on code itself and guide you to necessarily changes. It might be also hard to find where is the _I have made the changes on my fork_ for those who doesn't know GitHub well.  

The methods of `FunctionsBuilder` uses different kind of arguments than your current `lag/lead` uses. Most of them takes `$expression` or `$args` or something else, then `$types = []` as last argument. So the `lag/lead` method signature likely needs the change or what arguments are passed to `$this->_build()`. That's why you get that error.

Read how other function expressions are built https://book.cakephp.org/3/en/orm/query-builder.html#using-sql-functions.

**Comment by othercorey** [comment]
@celsowm If you are not ready to submit a full PR, I am planning to work on window functions including `lag()` and `lead()`.   It will be generic for all windows.

**Comment by celsowm** [comment]
@othercorey no problem ! I hope I have had collaborated in some way

**Comment by othercorey** [comment]
Closing in favor of general window support issue https://github.com/cakephp/cakephp/issues/14080
