### ISSUE TITLE
Multiple redirects/reloads occurring

### ISSUE THREAD

**Issue by Ryan19841** [cakephp/cakephp#13831]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: done on a Windows machine with XAMPP installed as well as on a LINUX SERVER

### What you did
I noticed an odd issue when writing code to log visitor interactions with a website I'm developing. I found that multiple records were being recorded on a single run (i.e. headers, ip, referral). I assumed that it might be to do with how I coded the initial functionality. So I implemented some logging to a text file so that I can see the general interactions between scripts and functions, and I saw that requests between functions were occurring multiple times. I did a fresh install, and implemented the following code into index.php within the webroot folder:

```
writeLine("=== Start App ===");
// Bind your application to the server.
$server = new Server(new Application(dirname(__DIR__) . '/config'));

// Run the request/response through the application and emit the response.
$server->emit($server->run());
writeLine("=== End App ===");

function writeLine($line)
{
  $file = fopen("E:/xampp/htdocs/website/test.txt", "a");
  fwrite($file , $line);
  fwrite($file , "\n");
  fclose($file );
}
```

### What happened
When looking at the log file, the following appeared (this was just on a single execution):

```
=== Start App ===
=== End App ===
=== Start App ===
=== End App ===
=== Start App ===
=== End App ===
=== Start App ===
=== Start App ===
=== End App ===
=== End App ===

```

### What you expected to happen
Surely the application is only meant to run once, and not multiple times? Shouldn't I only have a single START and END?

**Comment by saeideng** [comment]
are you using plugin for template/assets ??
`plugins/PluginName/src/Template/webroot/....` ??

**Comment by garas** [comment]
Is DebugKit active?

Check Network tab of browser Developer tools.

Log result of `var_export($_SERVER, true);`.

**Comment by Ryan19841** [comment]
> 
> 
> are you using plugin for template/assets ??
> `plugins/PluginName/src/Template/webroot/....` ??

It's a fresh install without any plugins

**Comment by Ryan19841** [comment]
> 
> 
> Is DebugKit active?
Debug Kit is enabled
> 
> Check Network tab of browser Developer tools.
I checked Network tab, and checked Persist Logs. I don't see multiple occurrences of the same file running more than once
> 
> Log result of `var_export($_SERVER, true);`.

```
array (
  'REDIRECT_REDIRECT_MIBDIRS' => 'E:/xampp/php/extras/mibs',
  'REDIRECT_REDIRECT_MYSQL_HOME' => '\\xampp\\mysql\\bin',
  'REDIRECT_REDIRECT_OPENSSL_CONF' => 'E:/xampp/apache/bin/openssl.cnf',
  'REDIRECT_REDIRECT_PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php',
  'REDIRECT_REDIRECT_PHPRC' => '\\xampp\\php',
  'REDIRECT_REDIRECT_TMP' => '\\xampp\\tmp',
  'REDIRECT_REDIRECT_STATUS' => '200',
  'REDIRECT_MIBDIRS' => 'E:/xampp/php/extras/mibs',
  'REDIRECT_MYSQL_HOME' => '\\xampp\\mysql\\bin',
  'REDIRECT_OPENSSL_CONF' => 'E:/xampp/apache/bin/openssl.cnf',
  'REDIRECT_PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php',
  'REDIRECT_PHPRC' => '\\xampp\\php',
  'REDIRECT_TMP' => '\\xampp\\tmp',
  'REDIRECT_STATUS' => '200',
  'MIBDIRS' => 'E:/xampp/php/extras/mibs',
  'MYSQL_HOME' => '\\xampp\\mysql\\bin',
  'OPENSSL_CONF' => 'E:/xampp/apache/bin/openssl.cnf',
  'PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php',
  'PHPRC' => '\\xampp\\php',
  'TMP' => '\\xampp\\tmp',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en-ZA;q=0.7,en;q=0.3',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_HOST' => 'localhost:81',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'PATH' => '',
  'SystemRoot' => 'C:\\WINDOWS',
  'COMSPEC' => 'C:\\WINDOWS\\system32\\cmd.exe',
  'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
  'WINDIR' => 'C:\\WINDOWS',
  'SERVER_SIGNATURE' => '<address>Apache/2.4.37 (Win32) OpenSSL/1.1.1 PHP/7.2.12 Server at localhost Port 81</address>
',
  'SERVER_SOFTWARE' => 'Apache/2.4.37 (Win32) OpenSSL/1.1.1 PHP/7.2.12',
  'SERVER_NAME' => 'localhost',
  'SERVER_ADDR' => '::1',
  'SERVER_PORT' => '81',
  'REMOTE_ADDR' => '::1',
  'DOCUMENT_ROOT' => 'E:/xampp/htdocs',
  'REQUEST_SCHEME' => 'http',
  'CONTEXT_PREFIX' => '',
  'CONTEXT_DOCUMENT_ROOT' => 'E:/xampp/htdocs',
  'SERVER_ADMIN' => 'postmaster@localhost',
  'SCRIPT_FILENAME' => 'E:/xampp/htdocs/new_site/webroot/index.php',
  'REMOTE_PORT' => '62843',
  'REDIRECT_URL' => '/new_site/webroot/',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_METHOD' => 'GET',
  'QUERY_STRING' => '',
  'REQUEST_URI' => '/new_site/',
  'SCRIPT_NAME' => '/new_site/webroot/index.php',
  'PHP_SELF' => '/new_site/webroot/index.php',
  'REQUEST_TIME_FLOAT' => 1572720325.421,
  'REQUEST_TIME' => 1572720325,
)
```

**Comment by saeideng** [comment]
when you see multi requests in `index.php` it says requests come from out of cake like request for assets 
and if asset was exist Apache handles it , if no , request comes to cake and this file 

now test the requests number from browser , network tab ,....

**Comment by Ryan19841** [comment]
> 
> 
> when you see multi requests in `index.php` it says requests come from out of cake like request for assets
> and if asset was exist Apache handles it , if no , request comes to cake and this file
> 
> now test the requests number from browser , network tab ,....

Developer Tool shows that there's 14 assets. 
Logs shows 9 starts and ends

**Comment by garas** [comment]
Is line `'REQUEST_URI' => '/new_site/',` same for all requests?

**Comment by saeideng** [comment]
I tested it request are for main site + debug_kit requests and expected
as I said requests are for assets ( in this case for debug_kit )

add these lines to see result 
```php
file_put_contents('time', "\nstart__".$_SERVER['REQUEST_URI'], FILE_APPEND);

file_put_contents('time', "\nend__".$_SERVER['REQUEST_URI'], FILE_APPEND);
```

result 
```
start__/requests/
end__/requests/
start__/requests/debug_kit/js/toolbar.js?....
end__/requests/debug_kit/js/toolbar.js?....
start__/requests/debug-kit/toolbar/.....
end__/requests/debug-kit/toolbar/.....
start__/requests/debug_kit/css/reset.css
start__/requests/debug_kit/css/toolbar.css
end__/requests/debug_kit/css/reset.css
start__/requests/debug_kit/js/jquery.js
start__/requests/debug_kit/js/toolbar-app.js
start__/requests/debug_kit/js/debug_kit.js
end__/requests/debug_kit/js/debug_kit.js
end__/requests/debug_kit/js/jquery.js
end__/requests/debug_kit/css/toolbar.css
end__/requests/debug_kit/js/toolbar-app.js
start__/requests/debug_kit/img/cake.icon.png
end__/requests/debug_kit/img/cake.icon.png
start__/requests/debug_kit/css/raleway-regular.woff
end__/requests/debug_kit/css/raleway-regular.woff
```
