### ISSUE TITLE
I can't get the validation errors of an association

### ISSUE THREAD

**Issue by ozee31** [cakephp/cakephp#13840]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.3

### What you did

```php
$data = [
    'name' => "46800",
    'postal_code' => '46800',
    'postal_codes' => [
        ['id' => 'ff9ebfb3-e600-4c47-b5d3-78824143bdb6'],
    ],
];

$entity = $this->Areas->newEntity();
$entity = $this->Areas->patchEntity($entity, $data);

$this->Areas->save($entity); // return false

debug($entity->postal_codes[0]->getErrors()); // []
debug($entity->getErrors()); // []
```

```php
// AreasTable
$this->belongsToMany('PostalCodes', [
    'foreignKey' => 'area_id',
    'targetForeignKey' => 'postal_code_id',
    'joinTable' => 'areas_postal_codes'
]);

// AreasPostalCodesTable
public function buildRules(RulesChecker $rules)
{
    $rules->add($rules->isUnique(['postal_code_id']));

    return $rules;
}
```

### What happened

I don't get an error message when the validation failed in joinTable

### What you expected to happen

```php
debug($entity->getErrors()); // [ 'postal_codes' => ['isUnique' => 'bla bla'] ]

// OR

debug($entity->postal_codes[0]->getErrors()); // [ 'postal_codes' => ['isUnique' => 'bla bla'] ]
```

**Comment by ndm2** [comment]
_Application_ rules are applied at saving time, not at patching time, that's when _validation_ rules are applied, hence you won't get any errors for your `isUnique` rule, see **https://book.cakephp.org/3/en/orm/validation.html#validation-vs-application-rules**.

Debug the entity after the `save()` call and see if it has any errors, they might still be missing, as errors in join table save operations are currently swallowed in certain situations.

**Comment by ozee31** [comment]
Oh yes sorry, but i have the same problem

**Comment by markstory** [comment]
Are you sure your rule is failing? The error should be on the root entity.

**Comment by ozee31** [comment]
yes in my unit test `$this->assertFalse($this->Areas->save($entity));`

But after `$entity->getErrors()` is empty

**Comment by ndm2** [comment]
That doesn't necessarily mean that the rule is failing though. Add an empty join data entry to your postal code data, ie:

    ['id' => 'ff9ebfb3-e600-4c47-b5d3-78824143bdb6', '_joinData' => []]

and see if it makes any difference (this should cause an entity for `_joinData` being present after patching), if the problem is that the rule is failing and the error is being swallowed in the join data saving stage, then this should fix it, and the error should show up in `postal_codes.0._joinData`.

If there's still no error, then it might be a different problem.

**Comment by ozee31** [comment]
Thank you @ndm2 it's works with `['id' => 'ff9ebfb3-e600-4c47-b5d3-78824143bdb6', '_joinData' => []]` but it's strange to have to do this.

After `$rules->add($rules->existsIn(['postal_code_id'], 'PostalCodes'));` does not work in Join Table.

I think I'll create custom rules

**Comment by ndm2** [comment]
Well, it's more of a workaround I guess... I'm not sure, maybe the marshaller could add it by default, even if there's no additional join data to patch, not sure, that might have some unwelcome side effects.
