### ISSUE TITLE
Input parameters (fields) not sanitized when using Model::find()

### ISSUE THREAD

**Issue by barezina-intellipharm** [cakephp/cakephp#13844]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: v2.10.19
* Platform and Target: Ubuntu 18.04.2 LTS, MariaDB 10.4.41, Console Script.

### What I did:
- Check out a new instance of v2.10.19. 
- Create a simple shell/task set. 
- Create a simple model. 

In the task file, write something like this:
```
        $result = ClassRegistry::init('Member')->find(
            'first',
            [
                'fields' => ['DISTINCT count(1); truncate `members`;']
            ]
        );
```

### What happened:
The members table gets truncated.

### What I expected to happen:
The member table not to be truncated:

As per cake documentation here: https://book.cakephp.org/2/en/core-utility-libraries/sanitize.html
"CakePHP handles SQL escaping on all parameters to Model::find() and Model::save()... "

**Comment by markstory** [comment]
Yes, the documentation also states that using values that are SQL snippets is dangerous and that you should [never let users control the array keys](https://book.cakephp.org/2/en/models/retrieving-your-data.html#complex-find-conditions) for any inputs to the Model layer as it makes you vulnerable to SQL injection.

**Comment by barezina-intellipharm** [comment]
You guys should probably update your documentation page then as it gives users of the framework a false sense of security.

**Comment by markstory** [comment]
@barezina-intellipharm Which page do you think needs to be updated?

**Comment by barezina-intellipharm** [comment]
The page in the initial post - https://book.cakephp.org/2/en/core-utility-libraries/sanitize.html
The text on the page I believe is incorrect:

> "CakePHP handles SQL escaping **on all parameters** to Model::find() and Model::save()"

Also, the page you linked me to - https://book.cakephp.org/2/en/models/retrieving-your-data.html#complex-find-conditions
Has the red warning text which is also incorrect:

> "CakePHP only escapes **the array values**. You should never put user data into the keys. Doing so will make you vulnerable to SQL injections"

In the example at the beginning of this issue, the parameter I provided **was in an array value**.

Also just above the red warning text, there is a sentence that reads:

> "Using the array syntax also enables CakePHP to secure your queries against any SQL injection attack."
