### ISSUE TITLE
I am facing problem with cakephp 3 auth component where I unable to login using right password and email

### ISSUE THREAD

**Issue by neerajdelhi** [cakephp/cakephp#13842]
Here is my auth in appcontroller
$this->loadComponent('Auth',[

			'authenticate' => [
				'Form' => [
					'fields' => [
						'username' => 'email',
						'password' => 'password'
					]
				]
			],
			'loginAction' => [
				'controller' => 'Users',
				'action' => 'login'
			]
		]);

UserController
public function login(){
		
		if($this->request->is('post')){
			$user = $this->Auth->identify();
			if($user){
				$this->Auth->setUser($user);
				$this->redirect($this->Auth->redirectUrl());
			}
			//Bad login
			$this->Flash->error('Username or password is incorrect.');
		}
	}

login template file

<div class="index large-4 medium-4 large-offset-4 medium-offset-4 columns content">
	<div class="panel">
	        <h1 class="text-center">Login User</h1>
		<?= $this->Form->create(); ?>
			<?= $this->Form->input('email'); ?>
			<?= $this->Form->input('password',array('type'=>'password')); ?>
			<?= $this->Form->submit('submit',array('class'=>'button small info')); ?>
		<?= $this->Form->end(); ?>
	</div>
</div>

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
