### ISSUE TITLE
3.9 - Backport support for database datetime types with fractional seconds

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#13855]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.6

### What you did
I use the TimestampBehavior and I have a "modified"-column with DATETIME(6) (with microseconds) and I updated the record

### What happened
microseconds = 000000

### What you expected to happen
correctly set microseconds

### Possible solution
Database\Type\DateTimeType::toDatabase()

if I change the last line in this method to:
`return $value->format('Y-m-d H:i:s.u');`
then the TimestampBehavior correctly sets the microseconds

**Comment by ADmad** [comment]
This should already work now in 4.x by using the `DateTimeFractionalType` #13752.

**Comment by othercorey** [comment]
I am working on a PR that will change the default type for DATETIME(6), TIMESTAMP(6) to the new DateTimeFractionalType in 4.x.

**Comment by othercorey** [comment]
https://github.com/cakephp/cakephp/pull/13864 adds the type mapping support to 4.x.

If there is a consensus that this could or should be backported to 3.9, I could work on that later.  I would prefer to backport the cleaned up version instead of trying to re-write it into the existing 3.8 DateTimeType code.

**Comment by ADmad** [comment]
>  I would prefer to backport the cleaned up version instead of trying to re-write it into the existing 3.8 DateTimeType code.

:+1:

**Comment by othercorey** [comment]
I'm not planning to backport this to 3.9.  I think it's too large of a change to switch the default mappings and too much work to ensure it works without that.
