### ISSUE TITLE
Exception call stack shows frame with the parent frame's source

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13869]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.x-dev

### What you did
Throw class not found exception

### What happened
The stack frames are linking the function being called with the current source file instead of the function currently executing.

![stack](https://user-images.githubusercontent.com/24221186/68539925-fa9b4180-034f-11ea-98ad-523a2a8acbbe.png)

**Comment by markstory** [comment]
Where are you throwing your exception from?

**Comment by othercorey** [comment]
This was caused by a missing class reference in an Entity class in the bookmarker tutorial.

**Comment by markstory** [comment]
ok. I'll see if I can reproduce that.

**Comment by ADmad** [comment]
I too have noticed this issue too.
