### ISSUE TITLE
Console Commands not working for plugins

### ISSUE THREAD

**Issue by FinlayDaG33k** [cakephp/cakephp#13876]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: `3.8.3` @ 705b43b70e87ec226a6b37099013de1003a17c17
* Platform and Target: PHP-CLI 7.2 with MySQL and Docker

### What you did
I've created a console command at `/src/Command/TranslateCommand.php` in my plugin with the following code (some actual code is removed for ease of readability):
```php
<?php
  namespace FinlayDaG33k\Translate\Command;

  use Cake\Console\Arguments;
  use Cake\Console\Command;
  use Cake\Console\ConsoleIo;

  class TranslateCommand extends Command {
    public function execute(Arguments $args, ConsoleIo $io) {
      $io->out('Translate command ran');
    }
  }
```

I then loaded the plugin in my `Application.php` with the following code:
```php
$this->addPlugin('FinlayDaG33k/Translate');
```

My `bin/cake.php` has the following content:
```php
#!/usr/bin/php -q
<?php
// Check platform requirements
require dirname(__DIR__) . '/config/requirements.php';
require dirname(__DIR__) . '/vendor/autoload.php';

use App\Application;
use Cake\Console\CommandRunner;

// Build the runner with an application and root executable name.
$runner = new CommandRunner(new Application(dirname(__DIR__) . '/config'), 'cake');
exit($runner->run($argv));
```

I've already checked #12068 but this didn't give me a solution.

### What happened
It tells me the command could not be found:
> Exception: Unknown command `cake translate`. Run `cake --help` to get the list of valid commands. in [/var/www/vendor/cakephp/cakephp/src/Console/CommandRunner.php, line 347]

### What you expected to happen
It outputting `Translate command ran`.

**Comment by markstory** [comment]
Does your plugin have a plugin class that defines a `console()` hook?

What is the output from `bin/cake -h`?

**Comment by dereuromark** [comment]
What's your composer setup? Most likely that's the cause or plays into it (autoload).

**Comment by FinlayDaG33k** [comment]
@markstory Yes, it does.
```php
<?php
  namespace FinlayDaG33k\Translate;

  use Cake\Core\BasePlugin;
  use Cake\Core\PluginApplicationInterface;
  use FinlayDaG33k\Translate\Command\TranslateCommand;
  
  class Plugin extends BasePlugin {
    public function console($commands) {
      // Add console commands here.
      $commands = parent::console($commands);
  
      $commands->add('translate', TranslateCommand::class);

      return $commands;
    }
  }
```

@dereuromark That apparently was the issue... whoops.
It somehow didn't get dumped by composer's `dump-autoload`.
Deleting my vendor folder and re-installing the packages did the trick...
