### ISSUE TITLE
Date create from format returns wrong timestamp

### ISSUE THREAD

**Issue by jcv-pt** [cakephp/cakephp#13879]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.18 && 3.6.15
* Platform and Target: Ubuntu 16.04, Apache, PHP 7.0.32

### What you did
use Cake\I18n\Date;

$format = 'Y-m-d H:i:s';
$date = '2019-12-06 23:59:59';
$d = Date::createFromFormat($format, $date);

$result = $d->format($format);

### What happened
Date utility is returning $result with a value of '2019-12-06 00:00:00'

### What you expected to happen
Date utility should return $result with a value of '2019-12-06 23:59:59' as happens if i use PHP Datetime lib such as:

DateTime::createFromFormat(...)->format(...);

**Comment by ADmad** [comment]
`Date` as per it's name holds only date, the time value is dropped, so output is expected.

**Comment by jcv-pt** [comment]
You r right :( , my apologies...
