### ISSUE TITLE
Deleting BelongsTo associations

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13886]
https://github.com/cakephp/cakephp/blob/ed758075d1a12abebcc958baa450c49961c81dea/src/ORM/Association/BelongsTo.php#L121

Setting property to null do not delete BelongsTo association.
It should update foreign key (set to null) if $targetEntity === null

Example:
User belongs to country;
Setting $user->country = null should set $user->country_id = null;

**Comment by ADmad** [comment]
A property set to null vs not set is not easy to discern in PHP.

So trying to implement what you want wouldn't be practical. Just set the foreign key field to null.

**Comment by ADmad** [comment]
IIRC there was a ticket earlier too where reason why this isn't implemented was mentioned. I can't find it.

**Comment by andrii-pukhalevych** [comment]
Setting null is not the same as unset property. 
In this case its possible to handle null correctly and do not refer to keys (country is marked as duty and BelongsTo::saveAssociated() is called anyway).

**Comment by ADmad** [comment]
What happens if both the association property and foreign key property are dirty, which one to ignore?

**Comment by andrii-pukhalevych** [comment]
https://github.com/cakephp/cakephp/blob/ed758075d1a12abebcc958baa450c49961c81dea/src/ORM/Association/BelongsTo.php#L131
BelongsTo::saveAssociated() updates foreign key property to actual value

**Comment by Ali1** [comment]
Maybe you can look to keep `country` and `country_id` in sync with __set. If `country` is set and has an id, it can update country_id and if country_id is set, then it can update `country` (an entity with only an id)

**Comment by andrii-pukhalevych** [comment]
Should we include this in cake 5? It's so annoying that not possible set property to null and must set key instead?

**Comment by dereuromark** [comment]
> IIRC there was a ticket earlier too where reason why this isn't implemented was mentioned. I can't find it.

@andrii-pukhalevych  If u can make it happen, go for it.
