### ISSUE TITLE
\Cake\Mailer\Email::deliver() not picking up default profile

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#13883]
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8.5

### What you did
1. 
````
// config/app.php
/**
 * Email delivery profiles
 *
 * Delivery profiles allow you to predefine various properties about email
 * messages from your application and give the settings a name. This saves
 * duplication across your application and makes maintenance and development
 * easier. Each profile accepts a number of keys. See `Cake\Mailer\Email`
 * for more information.
 */
'Email' => [
    'default' => [
        'transport' => 'my-custom-transport',
        'from' => 'support@example.com',
    ],
],
````

2. 

````
\Cake\Mailer\Email::deliver($to, $subject, $message)
````

### What happened
> From is not specified.
> BadMethodCallException

When no configuration was passed, `deliver()` [uses](https://api.cakephp.org/3.8/source-class-Cake.Mailer.Email.html#2201) the `default` [*transport*](https://github.com/cakephp/app/blob/278b35a380023d8d49aeb3545c58210e696091e7/config/app.php#L207).

### What you expected to happen

When no configuration was passed, `deliver()` uses the `default` [*profile*](https://github.com/cakephp/app/blob/278b35a380023d8d49aeb3545c58210e696091e7/config/app.php#L237) and obtains the `from` and `transport` values from there, just like [`$email=new \Cake\Mailer\Email(); $email->send()`](https://book.cakephp.org/3/en/core-libraries/email.html#basic-usage) does.

### Why

The Email doc page [says](https://book.cakephp.org/3/en/core-libraries/email.html#sending-messages-quickly):

> Sometimes you need a quick way to fire off an email, and you don’t necessarily want do setup a bunch of configuration ahead of time. Cake\Mailer\Email::deliver() is intended for that purpose

Since the `From` header is required, and `deliver()` doesn't seem to pick it from elsewhere, I have to explicitly specify it. So now my code looks like
````
\Cake\Mailer\Email::deliver($to, $subject, $message, [
    'transport' => 'my-custom-transport',
    'from' => 'support@example.com',
]);
````
instead of simply
````
\Cake\Mailer\Email::deliver($to, $subject, $message);
````

- Is this the intended behaviour?
- Am I using it wrong?
- Is it going to change in 4.x?

Please advise!

**Comment by ADmad** [comment]
> Is it going to change in 4.x?

The `Email` class is deprecated in 4.x and instead you need to use `Mailer`. There's `Mailer::deliver()` which is no longer a static method and will use all options set in `Email.default` config.

**Comment by mehov** [comment]
> The Email class is deprecated in 4.x 

Whoa, okay, it doesn't say that anywhere on the [Email page](https://book.cakephp.org/3/en/core-libraries/email.html) though.

> instead you need to use `Mailer`

Can I start using it while on 3.8 so that my code is ready for 4.x? Searched for the `Mailer` docs but the [cookbook](https://book.cakephp.org/3/en/index.html) seems to be up to 3.x only

The only mention of Mailer I remember was in [Creating Reusable Emails](https://book.cakephp.org/3/en/core-libraries/email.html#creating-reusable-emails), is that it?

**Comment by ADmad** [comment]
You won't find mention of 4.x related features in docs for 3.x :slightly_smiling_face:.  Check https://book.cakephp.org/4/en/index.html

**Comment by mehov** [comment]
> You won't find mention of 4.x related features in docs for 3.x 🙂. 

Oh, sorry, I meant the version switcher on the cookbook UI doesn't have the option to choose 4.x, the highest version listed is 3.x. And I didn't think about manually changing 3 to 4 in the URL for some reason :)

Anyway, I got my answers. Thank you for the heads up!

**Comment by ADmad** [comment]
Yeah the 4.x don't are still now linked in the menu. We will do so soon now that we are getting close to RC release.
