### ISSUE TITLE
Error trying to upgrade to RC1

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13888]
This is a (multiple allowed):

* [x] bugv
* Platform and Target: localhost: 8765, windows 10, chrome, all updated. Or rather, almost everything ...

### What happened
I did the update procedure set for RC1, but I get the image messages.

![Captura de Tela (3)](https://user-images.githubusercontent.com/50879411/68993861-46bc1980-085b-11ea-9081-c2feaee254d7.png)

**Comment by saeideng** [comment]
you can change the `composer.json` manually 
```php
    "require": {
        "php": ">=7.2",
        "cakephp/cakephp": "4.x-dev",
        "cakephp/plugin-installer": "^1.0",
        "mobiledetect/mobiledetectlib": "2.*"
    },
    "require-dev": {
        "cakephp/bake": "4.x-dev",
        "cakephp/cakephp-codesniffer": "dev-next",
        "cakephp/debug_kit": "4.x-dev",
        "cakephp/migrations": "4.x-dev",
        "josegonzalez/dotenv": "3.*",
        "phpunit/phpunit": "^8.0",
        "psy/psysh": "@stable"
    },
```

then run `composer update`
this will install latest commits on branch
you have to change those to `4.0.*` later (for cake core )  ( after final release out )

Refs : https://github.com/cakephp/app/blob/4.x/composer.json

**Comment by LuizMarin** [comment]
weird. The composer.json file is configured like this, with your suggestion.

**Comment by ADmad** [comment]
The plugins still use `4.x-dev`. You can just run `composer update`, don't try to install RC-1.
