### ISSUE TITLE
Update 4.0 migration docs to include upgrade tool

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#13881]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: N/A

The 4.0 migration documentation should include information on using the upgrade tool and the required order of operations.

**Comment by ADmad** [comment]
This ticket should be under the `docs` repo?
