### ISSUE TITLE
Missing validation rule allowNull()

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13901]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5.
* Platform and Target: Linux, Apache, MySQL.

### What you did
I tried to create validation rules for a column that may contain `string` min length 36 or `null` but not an empty string.

### What happened
 `allowEmpty()` worked fine but is deprecated and allowed to save an empty string. `allowEmptyString()` cannot be used because empty strings are not allowed to be saved according to the business rules. 

### What you expected to happen
I would expect to have something like `allowNull()` validation rule. I think it is pretty common to have nullable varchar columns in a database.

**Comment by bancer** [comment]
@ADmad It is good that it is fixed in 4.x but the problem was 3.x.

**Comment by dereuromark** [comment]
@bancer You can backport it to 3.x
