### ISSUE TITLE
4.x - Prefixes must be CapsCase in links?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13917]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-RC1
* Platform and Target: Nginx 1.17.3 & PHP 7.3.10

### What you did
I upgraded my old Cake 4 beta application to the latest 4.0.0-RC1 release, for the framework and the `cakephp/app` skeleton. Then I tried to visit my application after logging in.

Here is my routing setup, and also the template link which I think was causing an exception.

```php
$routes->prefix('admin', function (RouteBuilder $builder) {
    $builder->fallbacks();
});
```

```php
<?= $this->Html->link(
    'Administration',
    ['controller' => 'Questions', 'action' => 'index', 'prefix' => 'admin'],
    ['class' => $this->getRequest()->getParam('prefix') === 'admin' ? 'nav-link active' : 'nav-link']
)?>
```

### What happened
I got an exception for a missing route. As I have a navigation element which has an `admin` prefix link in it.

### What you expected to happen
I expected the element to render.

### What's changed?
I managed to solve this by having to change `admin` to `Admin` in my template. Which I find confusing as I've defined my prefix as `admin` and not as `Admin`.

Does this mean that when I upgrade my apps I need to change every template using a prefix link to captialise the prefix, even when it's not defined as such in the routing?

**Comment by davidyell** [comment]
Seems this is an intentional change, as pointed out by @dereuromark 

➡️ https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html#router

**Comment by ADmad** [comment]
Yes it's an intentional change for consistency. Lowercased (dashed to be precise) string is URL but when specifying the prefix in URL you must used CamelCased versions similar to what's done for `plugin` and `controller` keys.

**Comment by markstory** [comment]
If you need to preserve the existing behavior because you have too many links to update at once you can use

```php
$routes->scope('/admin', ['prefix' => 'admin'], function ($builder) { ... });
```

Instead of prefix(). You will get a deprecation warning about non camelcased prefix values but your application should continue working.
