### ISSUE TITLE
OpenSSL should use lowercase

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13913]
This is a (multiple allowed):

* [x] enhancement

* CakePHP Version: any (dev-master)

### What you did

Due to openssl 1.1.1 patch and `openssl_get_cipher_methods()` now only returning lowercase.

The current code contains upper case usage for openssl:
```php
    public static function encrypt($plain, $key)
    {
        $method = 'AES-256-CBC';
        $ivSize = openssl_cipher_iv_length($method);

        $iv = openssl_random_pseudo_bytes($ivSize);

        return $iv . openssl_encrypt($plain, $method, $key, OPENSSL_RAW_DATA, $iv);
    }
```

Please see https://www.php.net/manual/en/function.openssl-get-cipher-methods.php#123319

> With OpenSSL 1.1.1 this no longer returns the uppercase variants of the name, i.e. `AES-256-CBC` no longer exists but `aes-256-cbc` does

And https://github.com/composer/composer/issues/7769

So in order to make the code future proof, we should streamline this (available methods should match the input method).

**Comment by othercorey** [comment]
Sounds like a simple change.  My guess is they using string insensitive comparison internally and don't see the reason to generate both versions in the list.

**Comment by markstory** [comment]
We aren't comparing or looking at the list of available ciphers though, what needs to change?

**Comment by dereuromark** [comment]
Can we a simple change in master then :) No BC issue, just forward compatibility and consistency.
Using lowercase only from now on.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/pull/13919
