### ISSUE TITLE
4.x - Soft deprecate NumberHelper and TextHelper

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#13915]
### NumberHelper

All methods of `NumberHelper` are just wrappers for methods of utility class `Number`. A couple of the methods add on htmlentitites escaping but the risk of XSS in formatted number string is relatively low and users can directly use `h()`.

### TextHelper

Similarly most of the methods of `TextHelper` are just wrappers for `Text` utility class. It has additional methods which deal with HTML generation like `autoLink()`, `autoParagraph()` etc. which can be moved to `HtmlHelper`.

The proposal is to just add `@deprecated` tags to these helper classes without explicit warning being triggered to avoid annoyance to those upgrading from 3.x.

One (and perhaps only) reason in favour of keeping these helpers is they are autoloaded so one can directly use `$this->Text->foo()` as opposed to using FQCN or `use` statement for using the utility class.

**Comment by dereuromark** [comment]
The last sentence sums it up. We need helpers to have easy access to those.

**Comment by davidyell** [comment]
I like the helpers. Although you raise good points, they're obvious classes, and people know what they do and understand their expected usage. I think removing them would just spawn plugins which re-introduce the same classes.

**Comment by ADmad** [comment]
The ticket was to gauge people's response, hence I stated reason in favour of retaining them too :slightly_smiling_face:.  If the community find them useful we can keep them.
