### ISSUE TITLE
Error in isLoginAction in authComponent when prefixed routes are in use

### ISSUE THREAD

**Issue by menshutin** [cakephp/cakephp#13916]
This is a (multiple allowed):

* [x] bug

* CakePHP Version:3.8.5
* Platform and Target: CentOS Linux release 7.4.1708, Apache 2.4.6, Mariadb 5.5.56-2, request from firefox.

### What you did
Added prefix route for api in routes.php:
`
Router::scope('/api',function (RouteBuilder $routes) {
    $routes->connect('/tasks/addProcess/*', ['prefix'=>'api','controller' => 'Tasks', 'action' => 'addProcess']);
});
`
In AppController set BasicAuth for prefixed route:
`
if ($this->request->getParam('prefix')==='api')
{
        $this->loadComponent('Auth',[
                'unauthorizedRedirect'=>false,
                'storage'=>'Memory',
                'authenticate' => [
                    'Basic' => [
                    'fields' => ['username' => 'short_name', 'password' => 'api_key'],
                    'userModel' => 'Users'
                    ],
                ],
            ]
        );
}
else ...
`
It results in error in authComponent:  
A route matching "array ( 'controller' => 'Users', 'action' => 'login', 'plugin' => NULL, 'prefix' => 'api', '_ext' => NULL, )" could not be found. 

Which is happening in authComponent in _isLoginAction during route normalization.
Since I have unauthorizedRedirect=false this check is not necessary I suppose.

**Comment by markstory** [comment]
You should be setting `prefix => false` in your login action url to fix this.

**Comment by dereuromark** [comment]
Or use [Url](https://github.com/dereuromark/cakephp-tools/blob/master/docs/Url/Url.md#reset) and other convenience helpers to auto-set the false for nondefined URL parts.
Especially useful inside layout snippets and default layout template.

**Comment by menshutin** [comment]
> You should be setting `prefix => false` in your login action url to fix  @this.
@markstory, i didn't quite understand where should i set prefix=>false?
I added fake route under the 'api' scope in routes:
`$routes->connect('/users/login', ['prefix'=>'api','controller' => 'Users', 'action' => 'login']);
`
It works.
