### ISSUE TITLE
4.x-dev : Deprecated ConsoleErrorHandler

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13912]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev `a26796a9b6fa824d47ce34b226e1b6a3b107550b`
* Platform and Target: Nginx 1.17.3, PHP 7.3.10

### What you did
I setup an application using `cakephp/app:4.0.0-alpha1`. Then I ran `bin/cake` in my Terminal.

### What happened
I got a deprecated exception output.

![Terminal outpu](https://i.imgur.com/iAUjO0n.png)

### What you expected to happen
I thought it would just list available commands.

**Comment by dereuromark** [comment]
Looks like those should be soft deprecations instead.

**Comment by othercorey** [comment]
This is using RC1 with that commit hash, right?

**Comment by markstory** [comment]
I tagged a 4.0.0-RC1 tag for the app repo which has an updated alias.
