### ISSUE TITLE
Curl version 1.1 instead of 2

### ISSUE THREAD

**Issue by frent** [cakephp/cakephp#13922]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.7.7
* Platform and Target: PHP 7.2

### What you did
Http client request to a https website - happenend overnight on working code/multiple servers.

### What happened
got an error: cURL Error (56) OpenSSL SSL_read: Success
tracked it down to Cake\Http\Client\Adapter\Curl.php where the $request->getProtocolVersion() function on line 75 returns '1.1' instead of the '2.0' my server provides. 

Also when executing env('SERVER_PROTOCOL') it returns HTTP/2.0 as expected in the getProtocolVersion() of ServerRequest. 

### What you expected to happen
Request.php - getProtocolVersion()  to return protocol 2.0 instead of 1.1

**Comment by markstory** [comment]
How are you making your request into an HTTP/2.0 one? The default protocol version in http/client is 1.1.

**Comment by frent** [comment]
I bypassed this by changing $request->getProtocolVersion() into CURL_HTTP_VERSION_2TLS in Curl.php line 75. If I don't do that the error shows:

Got some feedback from my hosting about overnight update:

Nov 20 21:48:47 Updated: ea-libcurl-7.67.0-1.1.2.cpanel.x86_64
Nov 20 21:49:17 Updated: ea-php70-php-curl-7.0.33-10.10.4.cpanel.x86_64
Nov 20 21:49:18 Updated: ea-php72-php-curl-7.2.24-1.1.3.cpanel.x86_64
Nov 20 21:49:18 Updated: ea-php56-php-curl-5.6.40-9.9.4.cpanel.x86_64
Nov 20 21:49:18 Updated: ea-php71-php-curl-7.1.33-1.1.3.cpanel.x86_64

**Comment by markstory** [comment]
So is the problem that you've been making HTTP/1.1 calls to an HTTP/2.0 service that is no longer willing to downgrade?

**Comment by othercorey** [comment]
> So is the problem that you've been making HTTP/1.1 calls to an HTTP/2.0 service that is no longer willing to downgrade?

I think they are saying with `SERVER_VERSION` env variable set to `HTTP/2.0` they expect `ServerRequest::getProtocolVersion()` to override the 1.1 default with 2.0.

**Comment by markstory** [comment]
But the SERVER_VERSION environment variable is set by the web server running a cake application and represents the incoming http protocol version. That environment variable doesn't and shouldn't control outbound connections.

**Comment by frent** [comment]
I did was expecting the SERVER_VERSION to override the 1.1 protocol. 

The problem occured only when I was sending the 1.1 with my Curl request and not with the 2.0 parameter. But Cakephp always sends 1.1 with their Curl request while CURL_HTTP_VERSION_2TLS  fallsback tot 1.1 when it's non SSL

**Comment by ndm2** [comment]
IMHO neither the client nor the adapter should make any assumptions about the protocol version to use for outgoing requests.

@frent You can use `\Cake\Http\Client::send()` with a custom request object, where you can define things the way you need them. Or you can create a custom adapter that forces a specific protocol version by overriding `\Cake\Http\Client\Adapter\Curl::getProtocolVersion()`.

Maybe there should be an easy way to process the automatically generated request object when using the client's shorthand methods, something like a callback option where one can modify the object before it's being passed to the adapter, idk.

**Comment by frent** [comment]
If no assumption should be made, why is the Curl request making one? 

CURLOPT_HTTP_VERSION => $request->getProtocolVersion(), : line 75

**Comment by ndm2** [comment]
It's not making assumptions, that method will try to use the version that the request object provides, and the request object has a static default.

**Comment by othercorey** [comment]
@frent Can you provide a short code example of how you are sending the request?

**Comment by frent** [comment]
`$http = new Client();
        $response = $http->post($url, [
          'fields' => $fields,
          'key' => $key,
        ]`

It's a real simple Curl Post trough the Client. And it worked until recently with the updates mentioned above. But should the HTTP version be sent along with the CURL request then?

**Comment by markstory** [comment]
>  But should the HTTP version be sent along with the CURL request then?

It should. We don't currently have a good way to set the default protocol a client is using. This is an oversight that hasn't come up until now. Would something like:

```php
$client = new Client(['protocolVersion' => '2.0'])
```
Be a reasonable approach? We would also need to conditionally use the new `CURL_HTTP_VERSION_2TLS` if it is defined.

**Comment by frent** [comment]
Perhaps also the option to disable sending the protocolVersion at all with the Curl request. But yes I do believe that giving the option to decide what version you are going to use should be implemented. 

According to https://curl.haxx.se/libcurl/c/CURLOPT_HTTP_VERSION.html a next version is being put in place with CURL_HTTP_VERSION_3 - with no fallback.

**Comment by garas** [comment]
Any Curl option can be overwritten with `'curl' => [CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_2TLS]` in `$options` of `Client` constructor or get/post/put/patch/delete().

**Comment by othercorey** [comment]
It's a little unfortunately how deep you have to dig to find the default.

I think an app config that sets the default would work. You could set it to null to not enforce I suppose.

**Comment by markstory** [comment]
I don't think an Application configuration would work. You could make requests to different services that require different protocol versions.

Not sending a protocol version doesn't match up well with how the psr7 abstractions are meant to work.

**Comment by othercorey** [comment]
I meant to set a default other than 1.1 -- the constructor options are best for what you describe.
