### ISSUE TITLE
4.x: collect missing rectors

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13927]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement

* CakePHP Version: 4.x

### What you did
Upgrade a plugin

### What happened
Errors in e.g. in tests
```
$request = new ServerRequest('/tags');
```

### Collecting missing rectors here
- [ ] ServerRequest($string) to ServerRequest($array) with maybe `['url' => $string]`

- [x] sed -ir 's|public function middleware($middleware) {|public function middleware(\\Cake\\Http\\MiddlewareQueue $middleware): \\Cake\\Http\\MiddlewareQueue {|g' src/Application.php (return typehint)

**Comment by markstory** [comment]
There is an existing rector to add the middeware queue return type. I'm not sure why it didn't get applied for you. See https://github.com/rectorphp/rector/blob/225f873d2cca67b40eaffb106848b4258d1e11db/config/set/cakephp/cakephp40.yaml#L48
