### ISSUE TITLE
4.x - Controller integration testing mismatched tokens

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#13925]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-RC1
* Platform and Target: Nginx 1.17.3 & PHP 7.3.10

### What you did
I am trying to run an integration test on a controller method. My AppController implements both AuthComponent and SecurityComponent. I also have the CsrfMiddleware enabled in the routing.

My test case looks like the following. I have used `$this->session()` in the `setUp` to add Auth session data.

```php
/**
 * Test add method
 *
 * @return void
 * @throws \PHPUnit\Exception
 * @throws \Throwable
 */
public function testAddWithInvalidCommentModel()
{
    $this->expectException(\BadMethodCallException::class);
    $this->expectExceptionMessage('Ye gads! What did you do?');

    $this->enableCsrfToken();
    $this->enableSecurityToken();
    $this->setUnlockedFields(['comment']);
    $this->post('/comments/add/invalid/999', ['comment' => 'Expecting an exception here']);

    $this->assertResponseFailure();
}
```

The code snippet I am trying to test is the following,
```php
/**
 * Add a new comment to either a Question or Answer
 *
 * @param string $model Name of the model being commented on, expected lowercase plural, eg, questions
 * @param int|string $id Primary key of the item
 * @return \Cake\Http\Response
 */
public function add(string $model, $id)
{
    $className = Inflector::camelize($model);

    $this->getRequest()->allowMethod('post');
    if (!in_array($className, ['Questions', 'Answers'])) {
        throw new \BadMethodCallException('Ye gads! What did you do?');
    }
    // Rest of method, etc
```

### What happened
Thanks to some help from @ADmad and @ndm2 in Slack, I added some methods to include the tokens in my request. However I still see an exception due to mismatched tokens.

`2019-11-21 16:11:48 Error: [Cake\Controller\Exception\AuthSecurityException] Invalid security debug token. in /Users/davidyell/Sites/Learning-CakePHP4/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php on line 245`

### What you expected to happen
I expected the`IntegrationTestTrait` to take care of the tokens for me, so that I could focus on testing my controller method.

### What's going on?
I am not sure, but my investigations have led me to think that the `fields` property is missing from the `_Token`. When I debug the data in `SecurityComponent::_validatePost` I can see the following.
Which are the json encoded `$hashParts`, `$check` and `$token`, as they appear in that method.

```
2019-11-21 16:11:48 Debug: ["\/comments\/add\/invalid\/999","a:0:{}","comment",""]
2019-11-21 16:11:48 Debug: 640dba12fdacfa1a216fd075110213e5b4155971
2019-11-21 16:11:48 Debug: da1283c6d02a43992eaf3b52b6b3f2276b6a1b6b
```

It's clear from this that the token mismatch is causing the request to fail, but I'm unsure why that might be, except for the `a:0:{}` empty `fields` which I tracked down through `_hashParts()` and into `_fieldsList()` methods.

For reference this code is available in my repository https://github.com/davidyell/Learning-CakePHP4

**Comment by ndm2** [comment]
The empty list is expected, as you are unlocking the only field that you're sending.

The fourth value in `$hashParts` is suspicious, it's supposed to be the session id, AFAICT it should be `cli` in the test environment, it's determined via **https://github.com/cakephp/cakephp/blob/4.0.0-RC1/src/Http/Session.php#L237**.

**Comment by ADmad** [comment]
The new `FormProtector` instance is created with session id as `cli` https://github.com/cakephp/cakephp/blob/7dcc92f871198cc0d2377c8bbd6cc805dff42a4d/src/TestSuite/IntegrationTestTrait.php#L663

**Comment by malamalca** [comment]
I have the same problem. There is a bug in Session::id() which returns session_id(). The former returns empty string in CLI. A simple fix could go in a way below.

https://github.com/cakephp/cakephp/blob/ac80eb89cb29aa82b4c5c5f2306c2f3d387d8cf3/src/Http/Session.php#L502
```php
    public function id(?string $id = null): string
    {
        if ($this->_isCLI) {
            return 'cli';
        }

        if ($id !== null && !headers_sent()) {
            session_id($id);
        }

        return session_id();
    }

**Comment by ADmad** [comment]
The core tests set the session id to `cli` during bootstrapping https://github.com/cakephp/cakephp/blob/4.x/tests/bootstrap.php#L139.

Perhaps we need to add the same to app's tests/bootstrap.

**Comment by davidyell** [comment]
Thanks for the patch @ADmad that code change has fixed my test-case.
