### ISSUE TITLE
Rules don't stop delete operation

### ISSUE THREAD

**Issue by gbredif** [cakephp/cakephp#13933]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.x
* Platform and Target: PHP 7.2; NGINX; SQL Server

### What you did
I have 3 models
Model A hasMany Model B
Model B hasMany Model C
They are configure with dependent => true and cascadeCallbacks => true.
I have rules on Model B and C to prevent delete on certain conditions.
$rules->addDelete(...)

### What happened
When the rules don't succeed on Model B or C the delete operation continues without deleting the record B or C. So I get a database errors because of foreign key constraints.

### What you expected to happen
The delete operation should stop if rules of associations failed 

PS: Same behaviour with beforeDelete and event->stopPropagation() on association.

Thanks in advance.

**Comment by markstory** [comment]
Are you expecting that a rules failure on B or C will prevent the deletion of a related A record?

Are you running your delete operations in a database transaction?

**Comment by gbredif** [comment]
Hi Markstory.

Thanks for your answer.

> Are you expecting that a rules failure on B or C will prevent the deletion of a related A record?

Yes but I realized that make no sense. Model B or C should not stop the deletion when it's trigger by model A (master). My problem is on deep level deletion.

My associations are configured with dependent set to true.

If I remove cascadeCallbacks the deletion will perform on model B only. May be I am wrong but it seems that deep associations can't be deleted with dependent option set between each association.

If I use cascadeCallbacks model C will be loaded but its rules made my transaction failed (foreign key constraints).

For now I have just write my own delete method.
It would be great to have a delete option like below when cascadeCallbacks is true:

```
$tableA->delete($entityA, [
    'associated' => [
        'ModelB.ModelC' => ['checkRules' => false]
    ]
]);
```

Thanks.

**Comment by karmicdice** [comment]
> For now I have just write my own delete method.

I was unable to replicate this. Would you be interested in sending the PR or sharing the exact code?
Tried https://book.cakephp.org/3/en/orm/deleting-data.html#cascading-deletes ?
I reckon we can perform a check in `beforeDelete()` if it is your app specific issue.
How did this exception manifest?

**Comment by karmicdice** [comment]
Update: I just saw your target platform. PHP 7.2; NGINX; SQL Server
I tested it on Apache, PHP 7.4, MariaDB
Can you please confirm the scenario? I am trying suss if it is SQL server specific issue or ORM as a whole.
