### ISSUE TITLE
wrong time when using BRAZILIAN TIMEZONE 

### ISSUE THREAD

**Issue by LeandroFranciscato** [cakephp/cakephp#13932]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5
* Platform and Target: Debian 10 (Buster) - Apache 2.4

### What you did
I've configured cake to use BRAZILIAN TIMEZONE. 
On `App.php` we did  ` 'defaultTimezone' => env('APP_DEFAULT_TIMEZONE', 'America/Sao_Paulo')`

### What happened
Cake is one hour forward the current time 

### What you expected to happen
The date time had to be right. 
Maybe it is happening because our summer time, that was deprecated this year.

**Comment by markstory** [comment]
You need to update your timezonedb. This can be done using your os upgrade tools on linux. On windows you might  need to update php to get a new timezonedb.

Closing as this isn't anything we can fix in cake.

**Comment by othercorey** [comment]
https://pecl.php.net/package/timezonedb

Somewhere to start.

**Comment by ndm2** [comment]
ICU needs to be updated too if your using the I18n aware formatting methods, not sure though if the current version (65.1) is aware of it, the previous one (64.2) doesn't seem to.

**Comment by LeandroFranciscato** [comment]
@markstory got it.

@othercorey I've installed it from https://pecl.php.net/package/timezonedb.
But still one hour foward... strange.
Anyway, thanks for replying, I'm going to stackoverflow.

**Comment by ndm2** [comment]
https://stackoverflow.com/questions/58547257/cake-i18n-time-object-echoes-wrong-hour-plus-daylight-saving-time :wink:

**Comment by LeandroFranciscato** [comment]
@ndm2 great!!! Thanks.
