### ISSUE TITLE
The datasource configuration debug_kit was not found in config\app.php. 

### ISSUE THREAD

**Issue by Xbirdfr** [cakephp/cakephp#13937]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v4.0.0-RC1
* Platform and Target: built-in server (bin/cake server -H 127.0.0.1 -p 8080)
* Php version : php-7.3.9-Win32-VC15-x64

### What you did
install Cakephp : 
`composer create-project cakephp/app:4.x-dev CakePHP4`
Start built-in webserver
`bin/cake server -H 127.0.0.1 -p 8080`
navigate to the page
`http://127.0.0.1:8080/`
### What happened
`Missing Datasource Configuration error`
`the datasource configuration debug_kit was not found in config\app.php. `
### What you expected to happen
get the Cakephp 4 frontpage

**Comment by Xbirdfr** [comment]
extension=pdo_sqlite was not loaded on my php version, enabled it fix the error

**Comment by jcvasquez07** [comment]
Accodring to the docs: "By default DebugKit will store panel data into a SQLite database in your application’s tmp directory." So, if you don't enable a database config for debug_kit, you should have the extension pdo_sqlite installed on your web server

**Comment by Hamfri** [comment]
Ensure you have php7.4-sqlite installed. That seems to solve the problem

**Comment by jasonrusso** [comment]
@Hamfri is correct. That was exactly my issue. for me I had to run
sudo apt-get update --fix-missing Or just sudo apt-get update
sudo apt-get install php7.4-sqlite
sudo service apache2 restart

**Comment by anvydigital** [comment]
I am baking Strawberry cake 4 with PHP-8.0 FPM.

```
sudo apt-get update
sudo apt-get install php8.0-sqlite
service php8.0-fpm restart
service apache2 restart
```
