### ISSUE TITLE
[cakephp 4.0.0 rc1]  Argument 1 passed to /Cake\Utility\Security::setSalt() must be of the type string, null given, called in cake4/performer/config/bootstrap.php on line 160

### ISSUE THREAD

**Issue by vnt** [cakephp/cakephp#13938]
Version: cakephp 4.0.0. r.c.1
PHP 7.3.8

Type error: 
Toggle Vendor Stack Frames
CORE/src/Utility/Security.php:306
/cake4/performer/vendor/cakephp/cakephp/src/Utility/Security.php

> Argument 1 passed to Cake\Utility\Security::setSalt() must be of the type string, null given, called in /cake4/performer/config/bootstrap.php on line 160

```

public static function setSalt(string $salt): void
  {
   static::$_salt = $salt;
   }

```
Error in: ROOT/vendor/cakephp/cakephp/src/Utility/Security.php, line 306 

This is my Security salt in app.php

```
 'Security' => [
        'salt' => env('jaksdfj9fjaskfeufkaj94u90q9rueKsaasdenca'),
     ],
```

**Comment by garas** [comment]
`env('jaksd...')` tries to get environment variable `jaksd...`, but as it is not set, salt is set to `null`.

It should be simply
```
 'Security' => [
        'salt' => 'jaksdfj9fjaskfeufkaj94u90q9rueKsaasdenca',
  ],
```

**Comment by Fred-by2020** [comment]
Hi I'm a beginner in cakephp. And I have this error on cakephp 4.0.5 while adding a new user in Users table. can you help please?
erreur: Argument 1 passed to Cake\Database\TypeFactory::build() must be of the type string, null given, called in C:\xampp\htdocs\mag_test\vendor\cakephp\cakephp\src\ORM\Table.php

**Comment by garas** [comment]
Your error looks like is different problem than in this issue.

Please open new issue with more details how to replay your error. It is too little information to reproduce error.
