### ISSUE TITLE
The "_cake_core_" cache configuration does not exist on non standard paths

### ISSUE THREAD

**Issue by MayMeow** [cakephp/cakephp#13935]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x.x
* Platform and Target: Everything - Prevent to start app

### What you did
When you create custom files outside standard paths like controllers and models ... and try to add localization function there `__()` it cause app to prevent start with `The "_cake_core_" cache configuration does not exist` No logs was made. You can open console with `bin/cake` - reutrns same error

for example my menu

```php 
<?php

// file plugins/PostBox/src/Menu/BackendMenu.php

namespace PostBox\Menu;

use MayMeow\CakePHP\Crud\View\Menu\Menu;
use MayMeow\CakePHP\Crud\View\Menu\MenuHeader;
use MayMeow\CakePHP\Crud\View\Menu\MenuItem;

class BackendMenu extends Menu
{
    function initialize()
    {
        $this->menu = [
            new MenuHeader('post-box'),
            // The __('Post') is useless because application will return error before start
            (new MenuItem(__('Posts'), ['plugin' => 'PostBox', 'prefix' => 'backend', 'controller' => 'Posts', 'action' => 'index']))->withIcon("fad fa-mail-bulk mr-2", 'text-success'),
            (new MenuItem('Addresses', ['plugin' => 'PostBox', 'prefix' => 'backend', 'controller' => 'Addresses', 'action' => 'index']))->withIcon('fad fa-home mr-2'),
            new MenuHeader('storage'),
        ];
    }
}

```

and yes all classes are available and its working unless you use `__()` in it

### What happened
`bin/cake` returns error `The "_cake_core_" cache configuration does not exist` 

### What you expected to happen
Expected is to do what i18n localization have to do... so localizing app. For my requirements is cakephp useless because client need whole app translated to language as he want. And **create another menu for other language is not an option**.

I asked this many times but it seems to nobody have or can answer why its going wrong

P.S: **Yes i have created cache folder** and **have created `_cake_core` config as it is standard** and **yes cache folder is writeable.**

**Comment by garas** [comment]
`__()` can be used anywhere, but only after cache configuration was set. It is unclear when  `BackendMenu::initialize()` is executed.

Cache configuration is loaded at [config/bootstrap.php](https://github.com/cakephp/app/blob/0181f2014ceb095939d8f68cc5ae2c4bf6496387/config/bootstrap.php#L150), make sure `_cake_core_` was not removed from [config/app.php](https://github.com/cakephp/app/blob/0181f2014ceb095939d8f68cc5ae2c4bf6496387/config/app.php#L111).

**Comment by MayMeow** [comment]
soo  there is problem... Back menu or menu doesn't have initialize function() is there any docummentation how to implement one ?

**Comment by garas** [comment]
`app.php` is loaded before `Cache::setConfig()`.

You should refactor your app to load menus later. Move loading to the end of `config/bootstrap.php`, or create _component_ or _view helper_ etc, depending on how/when menu is later used.

**Comment by ADmad** [comment]
This is an app config/architecture issue. Closing as there's nothing which needs to be changed/fixed in core.
