### ISSUE TITLE
URL mismatch in POST data in Form Protection Component

### ISSUE THREAD

**Issue by chetanvarshney** [cakephp/cakephp#13940]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.0.0-RC1
* Platform and Target: Windows 10 Mozilla, Localhost

### What you did
I used Form Protection component, on posting form I am getting URL mismatch error.

### What happened
URL mismatch in POST data (expected/cakephp4/users/add but found /users/add)
I am testing on localhost using wamp server.
There is no issue with Security Component.

### What you expected to happen
I have fixed issue by editing FormProtectionComponent.php (in forked project)
I will send pull request now.

**Comment by ADmad** [comment]
Closing as PR is open.
