### ISSUE TITLE
Support for objects not implementing `\ArrayAccess` to `Hash::extract`

### ISSUE THREAD

**Issue by Wouter0100** [cakephp/cakephp#13948]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.x
* Platform and Target: Local server, NGINX.

### What you did
I tried to `Hash::extract` a long path, with some conditions in them. This path contained some objects that do not implement `\ArrayAccess`. This is as documented, though - so kinda expected.

### What happened
I got no output.

### What you expected to happen
I hoped to get the correct response regardless of the incompatibility with `\ArrayAccess`. It would be possible to read variables from an object and make `Hash::extract` even more powerful.

**Comment by saeideng** [comment]
`ArrayAccess` supports by `Hash::extract()`
there are a lot of tests about `\ArrayAccess`
see `ArrayObject` in tests 
 https://github.com/cakephp/cakephp/blob/29c73f66ec644c8eb5dd8f22677d406b81e97523/tests/TestCase/Utility/HashTest.php#L1527-L1545

**Comment by Wouter0100** [comment]
> `ArrayAccess` supports by `Hash::extract()`
> there are a lot of tests about `\ArrayAccess`
> see `ArrayObject` in tests
> https://github.com/cakephp/cakephp/blob/29c73f66ec644c8eb5dd8f22677d406b81e97523/tests/TestCase/Utility/HashTest.php#L1527-L1545

I but `\ArrayObject` implements `\ArrayAccess`? My RFC is for objects not implementing `\ArrayAccess`.

**Comment by saeideng** [comment]
it works with objects that are instance of `\ArrayAccess`

>I but \ArrayObject implements \ArrayAccess?

yes

also there is test for `entity` object see the test class

**Comment by saeideng** [comment]
if you looking for objects you can use `Collection` too

**Comment by Wouter0100** [comment]
Yes, I know that - but that's not where this RFC is about. It's about implementing support in extract for objects that do not implement `\ArrayAcces` in any way.

**Comment by othercorey** [comment]
@Wouter0100 Do you have a proposal?

**Comment by markstory** [comment]
How would Hash know how to traverse into those objects?

**Comment by othercorey** [comment]
@Wouter0100 Do you have more information?

**Comment by Wouter0100** [comment]
Sure! Let me get back asap with some more information.

**Comment by othercorey** [comment]
Closing due to no proposal and no obvious solution.
