### ISSUE TITLE
Collision uuid in PHP 5.6

### ISSUE THREAD

**Issue by nojimage** [cakephp/cakephp#13944]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: PHP 5.6

### What you did

In PHP 5.6 `Cake\Utility\Text::uuid()` uses `mt_rand`.
If the seed is inadvertently initialized with `mt_srand`, the generated UUID collides.

Sample code: https://gist.github.com/nojimage/df00550e9cbc412e479ec9d54939cb67

I think Text::uuid should always use `random_int` instead of `mt_rand` and install [paragonie/random_compat](https://github.com/paragonie/random_compat).

**Comment by nojimage** [comment]
I think to solve this problem, just add `"paragonie/random_compat": "^2.0|9.99.99"` into composer.json.

**Comment by rchavik** [comment]
Is there anyway to NOT add `random_compat` as dependency when already using php > 7.1?

**Comment by markstory** [comment]
@rchavik I don't think there is.

**Comment by othercorey** [comment]
> Is there anyway to NOT add `random_compat` as dependency when already using php > 7.1?

Is there a downside to having the dependency?

**Comment by rchavik** [comment]
I'd rather it throws exceptions when used in 5.6.  It's already past EOL and next year reaches end of support.

**Comment by othercorey** [comment]
You want `Text::uuid()` to throw an exception in 5.6?

**Comment by rchavik** [comment]
Or something like this:

```diff
diff --git a/src/Utility/Text.php b/src/Utility/Text.php
index ddcef7eb3a..e1cc10aac2 100644
--- a/src/Utility/Text.php
+++ b/src/Utility/Text.php
@@ -61,6 +61,9 @@ class Text
     public static function uuid()
     {
         $random = function_exists('random_int') ? 'random_int' : 'mt_rand';
+        if ($random === 'mt_rand') {
+            trigger_error('Please install random_compat');
+        }
 
         return sprintf(
             '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
```

Affected installations can then install random_compat or upgrade to supported php versions.

**Comment by nojimage** [comment]
"paragonie/random_compat" v9.99.99 installs with PHP 7, but it does nothing provide.

https://github.com/paragonie/random_compat/tree/v9.99.99

**Comment by nojimage** [comment]
@rchavik How about using `deprecationWarning` instead of trigger_error?

**Comment by othercorey** [comment]
`Text::uuid()` isn't deprecated.  An error or exception would break compatibility.

**Comment by rchavik** [comment]
Agree we should not deprecate text::uuid(). It has its uses, and the caveats are already documented.

IMO, show notices in this case for users during dev is tolerable. One can then `composer require paragonie/random_compat` on their app. Once that's done, the notice is gone, since function random_int now exist.

**Comment by othercorey** [comment]
Users with ^3.8 could auto-upgrade deployed apps to 3.9 with this change and run into unexpected runtime errors.

**Comment by rchavik** [comment]
if we trigger `E_USER_NOTICE` errors, do we consider this as breaking compatibility? I couldn't find applicable case from https://book.cakephp.org/3/en/contributing/backwards-compatibility.html

IMO, this is not considered a breakage, since if said apps has `debug = false`, it will continue working as before; no public visible errors will be displayed. 

Also, i'm hoping most people would test upgrading in a dev env first.

**Comment by markstory** [comment]
Deprecation warnings and new exceptions are not backwards compatibility breaks based on our documentation.  A deprecation warning or exception is preferable over e_notice. We don't generally emit notice warnings.

**Comment by othercorey** [comment]
@nojimage Can you make a PR for this?

**Comment by othercorey** [comment]
Moved discussion to PR.
