### ISSUE TITLE
3.7.8 Deprecated Error: Function Redis::getKeys() is deprecated

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#13946]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.7.8

### What you did
`bin/cake cache clear_all`

### What happened
Deprecation Error

### What you expected to happen
As the cache adapters are Cake Core I was not expecting to see deprecation warnings.

**Comment by ADmad** [comment]
Upgrade to latest `3.8` releasee. The use of `Redis::getKeys` in `RedisEngine` has already been removed.
