### ISSUE TITLE
PHP 7.4 Preloading

### ISSUE THREAD

**Issue by assunluis80** [cakephp/cakephp#13950]
Does the version 4.0 will include the new Preloading feature of PHP 7.4? 
https://stitcher.io/blog/preloading-in-php-74

**Comment by markstory** [comment]
We don't have any plans to add a preload right now. It could be something we explore in 4.1 or when the composer support for generating preloaded becomes available.

With that said there shouldn't be anything preventing you from making a preloaded and loading cake.

**Comment by jimbo2150** [comment]
You can keep tabs on Composer's 7.4 preload support discussions in the issue here: https://github.com/composer/composer/issues/7777

**Comment by dereuromark** [comment]
So doesn't look like an issue for CakePHP core issue tracker then.
