### ISSUE TITLE
Loading plugins in tests after 3.6

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#13951]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8

### What you did
Updated from 3.6 to 3.8. Removed Plugin::routes() and passed the app instance to the routing middleware. Added the Plugin.php file to our plugins.

### What happened
Failing routes in our unit tests.

### What you expected to happen
No failing routes in our unit tests.

It looks like that the plugins aren't loaded anymore in unit tests for whatever reason. Just adding them to the collection won't load them unlike Plugin::load() did before.

How can I load a plugin into the unit tests?

**Comment by markstory** [comment]
Routes are not loaded in unit tests automatically if you use the middleware. You can either use an integration test case, or load the routes for the tests that need them. Here is an [example of loading routes ](https://github.com/cakephp/cakephp/blob/e16d98815b14e3e482f4b0e9a0c5c119a6388e9c/src/Console/CommandRunner.php#L415) in a non middleware context.

**Comment by markstory** [comment]
You could also use [TestCase::loadPlugins](https://github.com/cakephp/cakephp/blob/e16d98815b14e3e482f4b0e9a0c5c119a6388e9c/src/TestSuite/TestCase.php#L202) which will load the plugin and its routes.

**Comment by burzum** [comment]
@markstory thank you. Might be a good idea to put this directly into the book (routes and plugin section) or a link to wherever else this might be documented?
