### ISSUE TITLE
Validator::errors() is ambiguous

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#13952]
We have `Validator::errors()` which validates the passed in data and returns the validation result + error messages.  This name suggests that some validation already occurred as you normally see with other `getErrors()` methods.

The docblock tries to explain it which suggests that this is ambiguously named.

>     * Returns an array of fields that have failed validation. On the current model. This method will
>     * actually run validation rules over data, not just return the messages.

As a user, I'd expect something like `Validator::validateData()` or just `Validator::validate()`.

**Comment by dereuromark** [comment]
Also `Validator::result()` or alike could work.

**Comment by markstory** [comment]
Closing as there is a pull request open.
