### ISSUE TITLE
Add support for log message placeholders from log context

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#13963]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8.6
* Platform and Target: Built-in cakephp server on OSX 10.14.6

### What you did

I was creating a new plugin that uses queue-interop, and one of the log messages from within the queue-interop library showed up funny:

```
2019-12-01 00:58:25 Info: [client] Processed {topic} -> {processor}	{body}	{result} {reason}
```

This was from me passing in the default configured `debug` logger object. The following was the [call within the queue-interop codebase](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/ConsumptionExtension/LogExtension.php#L46):

```php
$context->getLogger()->log($logLevel, $logMessage, [
    'result' => str_replace('enqueue.', '', $result),
    'reason' => $reason,
    'topic' => $topic,
    'processor' => $processor,
    'queueName' => $context->getConsumer()->getQueue()->getQueueName(),
    'body' => Stringify::that($message->getBody()),
    'properties' => Stringify::that($message->getProperties()),
    'headers' => Stringify::that($message->getHeaders()),
]);
```

### What happened

Based on my understanding, they are using the context as placeholder replacements. When using Monolog, the replacements seem to be handled properly.

### What you expected to happen

Would be super-awesome if we could inject any placeholders into the logging message. Idk if this is in the PSR or not, or if its some sort of extension we need to add.

**Comment by ADmad** [comment]
Done in #14056
