### ISSUE TITLE
Changed load order of plugin routes

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#13968]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.x

### What you did

We upgraded to 3.8 and remove `Plugin::routes();` this call from our app routes.php:

```php
	/**
	 * Static pages
	 */
	$routes->connect('/:language/pages/*', ['controller' => 'Pages', 'action' => 'display']);
	/**
	 * Load all plugin routes. See the Plugin documentation on
	 * how to customize the loading of plugin routes.
	 */
	Plugin::routes(); // <--- WE REMOVED THIS
	$routes->connect('/:language/' . I18nRouteSegments::get('emagazine-list') . '/:action',
		['plugin' => 'Psa/MailingLists', 'controller' => 'MailingLists'],
		['language' => $langRegex]
	);
	$routes->connect('/:language/:controller',
		[],
		['language' => $langRegex, 'routeClass' => 'DashedRoute']
	);
	$routes->connect('/:language/:controller/:action',
		[],
		['language' => $langRegex, 'routeClass' => 'DashedRoute']
	);
	$routes->connect('/:language/:controller/:action/*',
		[],
		['language' => $langRegex, 'routeClass' => 'DashedRoute']
	);
```

We added this to App\Application::bootstrap():

```php
		$this->addPlugin('Psa/Cms', [
			'routes' => true,
			'bootstrap' => true
		]);
```
### What happened
The load order of the routes isn't the same anymore. The plugin routes appear now **after** the default controller/action route `/:language/:controller`.

### What you expected to happen
That our routes still work the same as before, given the fact this was no major version bump.

Is there any way to control where in between the list of routes the plugin routes get loaded?

### Ugly Workaround

Our ugly workaround for now is to load the routes.php from the plugin directly on top:

```php
require_once Plugin::getCollection()->get('Psa/Cms')->getPath() . 'config' . DS . 'routes.php';
```

**Comment by markstory** [comment]
> That our routes still work the same as before, given the fact this was no major version bump.

With your updated code that simply isn't possible as you were loading plugin routes at a very specific point in the routes file, and now you're getting the default behavior of plugin routes being loaded after application routes.

> Is there any way to control where in between the list of routes the plugin routes get loaded?

Yes, you can use [$routes->loadPlugin()](https://book.cakephp.org/3/en/plugins.html#plugin-routes) to load a plugin's routes at a specific point in your application routes.

**Comment by burzum** [comment]
@markstory thanks this works. The call to $routes->loadPlugin() would have been helpful in a comment above the deprecation of the old plugin method, nor was it mentioned in the migration guide. :(
