### ISSUE TITLE
Add official queueing library

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#13964]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: N/A

### What you did

I think it's about time for us to add an official queueing library. I've wanted to do this for some time, and my latest attempt involved creating engines for each potential queueing system.

Rather than have this be something we maintain, I found a very excellent standard in [queue-interop](https://github.com/queue-interop/queue-interop). This doesn't implement any PSR, but appears to follow the FIG in spirit. The practical [implementation](https://github.com/php-enqueue/enqueue-dev) implements engines (they call them drivers) for many popular queuing mechanisms.

Taking the above library and my previous [queuesadilla](https://github.com/josegonzalez/cakephp-queuesadilla) work, I implemented a [cakephp-queue](https://github.com/josegonzalez/cakephp-queue) library. As always, it comes with no tests, but appears to work locally pretty well with Redis. It's very much a rough draft and subject to change - I took a ton of short-cuts - but I think it could make a great basis for an official queue library.

The readme should have quite a bit of documentation, and anyone who has used the `cakephp-queuesadilla` library should feel at home. Happy to discuss how it could be moved to the cakephp framework, as well as any implementation details that seem wonky.

**Comment by markstory** [comment]
Queuing and background jobs seems like a good fit as a core supported plugin like authentication or authorization. Using the queue-interop libraries as a foundation sounds like a great idea to me.

**Comment by josegonzalez** [comment]
The biggest concern with my current implementation is that job classes don't have a distinct pattern. That is to say, anyone can create a job class that targets any function in any class.

The nice thing is that this allows stuff like Mailers to be jobs without any extra work. However, this also means we don't really have a good interface/contract for declaring jobs.

I also allow random functions to be jobs, though without real support for anonymous functions. We can probably use something like [SuperClosure](https://github.com/jeremeamia/super_closure) to support them, but I'm not convinced that having random functions across your codebase be jobs is a great idea for actual app maintenance, and thats also why I don't really like the idea of not having a job interface..

Would be great to have some feedback on the actual usage of the plugin from a UX standpoint. I think the underlying tech is pretty decent otherwise.

**Comment by jeremyharris** [comment]
I have a few apps using cakephp-queuesadilla and one thing I've done with my jobs is move them all into event listeners. This gives the project a direct way to queue a job - queue an event. This also gives us the flexibility of moving between directly dispatching events or queuing them depending on the use case.

I think the event class is a logical class that can be considered a "job" in a lot of cases and this has kept our codebase organized into listeners. Writing code that consumes job data is then consistent and is just like writing an event handler.

The biggest caveat I've found with this is falling into the trap that all event data is okay to pass around when non-serializable data is not and normally would be in the typical event cycle.


Here's the class I use to `QueueManager::queue(new Event('Myevent', null, ['data' => 'val']))`:
<details>
<summary>QueueManager</summary>

```
<?php
namespace App\Queue;

use Cake\Event\Event;
use Cake\Event\EventManager;
use Josegonzalez\CakeQueuesadilla\Queue\Queue;
use josegonzalez\Queuesadilla\Job;

/**
 * QueueManager
 *
 * Like EventManager, but for Queues. Use QueueManager to queue regular Events
 * into a proper job queue that are fired when the worker runs
 */
class QueueManager
{

    /**
     * Queued events. For testing mostly
     *
     * @var array
     */
    protected static $queued = [];

    /**
     * Sets the queued list
     *
     * @param array $queued Array of queued events
     * @return void
     */
    public static function setQueuedList($queued)
    {
        static::$queued = $queued;
    }

    /**
     * Places an event in the job queue
     *
     * @param Event $event Event to queue
     * @param array $options Additional Job options
     * @return int
     */
    public static function queue(Event $event, array $options = [])
    {
        static::$queued[] = $event;
        Queue::push('\App\Queue\QueueManager::dispatchEvent', [get_class($event), $event->getName(), $event->getData()], $options);

        return Queue::queue('default')->engine->lastJobId();
    }

    /**
     * Gets events that were queued during this request
     *
     * @return array
     */
    public static function getQueuedList()
    {
        return static::$queued;
    }

    /**
     * Constructs and dispatches the event from a job
     *
     * ### Data array
     * - 0: event FQCN
     * - 1: event name
     * - 2: event data array
     *
     * @param Job\Base $job Job
     * @return void
     */
    public static function dispatchEvent($job)
    {
        $eventClass = $job->data(0);
        $eventName = $job->data(1);
        $data = $job->data(2, []);
        $event = new $eventClass($eventName, null, $data);
        EventManager::instance()->dispatch($event);
    }
}
```
</details>

**Comment by josegonzalez** [comment]
Could/should we add a `Queue::pushEvent()`  method? I'm assuming my `Queue` class would otherwise be equivalent to the `QueueManager` class in your example.

One other thing that might be useful is the RPC-style command sending that queue-interop supports. My library doesn't handle that now, but maybe that also something that would be useful to implement?

**Comment by karmicdice** [comment]
> anyone who has used the cakephp-queuesadilla library should feel at home. 

How about we take the first step to include the lib and work up with concerns? For now, as I see, these are arch level concerns which relies on how the user will use them. I am such a big fan of this! I use it mainly for notifs because mysql lacks post event trigger, and putting it on app level slows down the user experience. Your plugin is a god sent to me. Would highly recommend inclusion and take it forward.

**Comment by josegonzalez** [comment]
I added - untested of course! - methods of queuing both Events and Mailers, which I think covers my worries around having job interfaces. As such, I'd be happy to drop generic closure support, though not sure if I need to type hint it or just not reference them in the docs...

**Comment by josegonzalez** [comment]
@markstory Do you think I should move the repo to the cakephp namespace and go from there?

**Comment by dereuromark** [comment]
I would first stabilize a plugin, similar to twig view, before making this a core one.
Look what happened to acl one :)

**Comment by markstory** [comment]
> Do you think I should move the repo to the cakephp namespace and go from there?

Sure, we can continue to refine it and add test coverage before doing releases of it.

>  Look what happened to acl one :)

We intentionally chose not to continue working on the ACL plugin, at least I did.

**Comment by josegonzalez** [comment]
@dereuromark I have yet to even put it on composer, but it's fairly feature-complete, and really just needs folks to play around with it/give feedback (and also tests from @lorenzo).

**Comment by josegonzalez** [comment]
I moved the project over to the cakephp namespace, though it has yet to be placed on packagist. Next steps:

- Setup travisci for tests/code linting
- Setup sticklerci
- Setup doc generation under the book namespace (but don't link them yet)
- Write tests? Any volunteers/victims?
- Code review from interested parties (@dereuromark would love your feedback here since you've written a few things in this space)
- Add to packagist
- Link docs in book sidebar
- Add to either `suggest` or `require` in the `composer.json` for the `cakephp/app` repo

Anything I'm missing here?

**Comment by ADmad** [comment]
I can take care of adding it to packagist and wiring up CI to run on travis/GH over the weekend. (I am not volunteering to write any tests :stuck_out_tongue:)

**Comment by hanumanyadav1989** [comment]
If you want add queueing library officially then please consider https://github.com/dereuromark/cakephp-queue existing plugin also because it is provide admin UI section also and it is simply to use

**Comment by ADmad** [comment]
Closing as work has started on https://github.com/cakephp/queue.
