### ISSUE TITLE
Error missing table when linking model twice

### ISSUE THREAD

**Issue by felangga** [cakephp/cakephp#13979]
I'm using cakephp 2.10.18 and want to use multiple belongsTo linking. I have table Admin and want to link my admin_id and admin_designer_id column into Admin table. 

```
public $belongsTo = array(
	    'Admin' => [
	        'classname' => 'Admin',
	        'foreignKey' => 'admin_id'
	    ],
	    'AdminDesigner' => [
	        'classname' => 'Admin',
	        'foreignKey' => 'admin_designer_id'
	    ],
	    'User' => [
	        'classname' => 'User',
	        'foreignKey' => 'user_id'
	    ],
	);
```
But the result is this

![image](https://user-images.githubusercontent.com/14814984/70206390-fbaa6d80-1759-11ea-91ff-e034c9ec54a9.png)

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
