### ISSUE TITLE
[feature request] i18n core shell - find non localizable strings

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#13977]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8

Would it be possible for core i18n shell, to add new task "Find localization disabled strings" ?

Ideally two possible selections

  1. find non-localizable php strings (ie. contained in <?(php) block wrapped with single or double quotes, not wrapped in known i18n functions)
  2. strings in templates which are not wrapped with i18n functions and are not php strings)

I'm not really able to implement something like that, so I'm writing this feature-request / enhancement issue, to see if core-devs do find my proposition sensible

**Comment by markstory** [comment]
How would a tool know which strings should be translated? For example options to FormHelper; they sometimes contain text shown to users but often don't. Sorting out what is important will be the hard part of this kind of tool.

**Comment by smarek** [comment]
Also I'd like to point out, there is something similar in Symfony 1.x, see legacy docs: https://symfony.com/legacy/doc/reference/1_4/en/16-Tasks#chapter_16_sub_i18n_find

![2019-12-05-060935_711x593_scrot](https://user-images.githubusercontent.com/384824/70205853-d26fea00-1725-11ea-91bf-f1b8fff53842.png)

however looking into sources, seems that implementation might not be easily portable
https://github.com/symfony/symfony1/blob/1.4/lib/task/i18n/sfI18nFindTask.class.php

**Comment by othercorey** [comment]
Can you accomplish this with a regex query?

**Comment by smarek** [comment]
@othercorey I don't think so, linked Symfony code does that with DOM tree traversal, which might be useful for static strings, nothing used in php code

Regarding the #markstory mentioned context difficulties, i agree, and also there should/could be filters, for usual syntax, or we could extract and tag the strings with the context (ie. if it is constructor argument, function argument, echo/print/log statement, etc..) that might help with sorting out the situation for developer

**Comment by smarek** [comment]
@ADmad @markstory please fix your github-actions, i mean, if the ticket is not `wontfix` or similar tag, it should not be marked as stale, just because you've yet to work on it

**Comment by ADmad** [comment]
@smarek If a ticket has been open for over 4 months without any action it means no one is interested in implementing the feature. Keeping it the issue open won't do much good. You (or anyone from the community) is welcome to provide a PR to implement it.

**Comment by othercorey** [comment]
@smarek If we plan to work on it, we will either *pin* the issue or add it to the future roadmap.
