### ISSUE TITLE
4.x - Email with links with route raises MissingRouteException on tests

### ISSUE THREAD

**Issue by mentisy** [cakephp/cakephp#13978]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev https://github.com/cakephp/cakephp/commit/7751403267ba4c8196cc444d70ac3877eac0911b
* Platform and Target: Attempted on Windows and Linux

### What you did
1. Downloaded the latest version of CakePHP 4.x-dev using composer create-project cakephp/app:4.x-dev
2. Baked a Mailer
3. Added an HTML link it the mailer template trying to route to `['controller' => 'pages', 'action' => 'display', 'home' `
4. Inside the baked MailerTest I tried to assert that an email was sent and contained `pages/home`

### What happened
A `Cake\Routing\Exception\MissingRouteException` is raised saying `A route matching ['controller' => 'pages', 'action' => 'display', 0 => 'home'] could not be found`

### What you expected to happen
I expected the test to pass as an email was sent and contained the link routed.

### Reproduce raised MissingRouteException ###
* I cloned this repository, ran all the tests inside `tests/TestCase/Mailer/` using `bin/vendor/phpunit tests/TestCase/Mailer` and they all passed.
* I added
`<?php echo $this->Html->link('Test', ['controller' => 'pages', 'action' => 'display', 'home']);`
 to the bottom of `templates/email/html.php` and ran the tests again. This raised the MissingRouteException.

### Full stack trace ###
```
4) Cake\Test\TestCase\Mailer\MailerTest::testSendRenderWithHTML
Cake\Routing\Exception\MissingRouteException: A route matching "array (
  'controller' => 'pages',
  'action' => 'display',
  0 => 'home',
  'plugin' => NULL,
  '_ext' => NULL,
)" could not be found.

X:\xampp\htdocs\cakephp-mail\src\Routing\RouteCollection.php:341
X:\xampp\htdocs\cakephp-mail\src\Routing\Router.php:494
X:\xampp\htdocs\cakephp-mail\src\View\Helper\UrlHelper.php:51
X:\xampp\htdocs\cakephp-mail\src\View\Helper\HtmlHelper.php:257
X:\xampp\htdocs\cakephp-mail\tests\test_app\templates\email\html\html.php:16
X:\xampp\htdocs\cakephp-mail\src\View\View.php:1160
X:\xampp\htdocs\cakephp-mail\src\View\View.php:1121
X:\xampp\htdocs\cakephp-mail\src\View\View.php:746
X:\xampp\htdocs\cakephp-mail\src\Mailer\Renderer.php:86
X:\xampp\htdocs\cakephp-mail\src\Mailer\Mailer.php:372
X:\xampp\htdocs\cakephp-mail\src\Mailer\Mailer.php:389
X:\xampp\htdocs\cakephp-mail\tests\test_app\TestApp\Mailer\TestMailer.php:32
X:\xampp\htdocs\cakephp-mail\src\Mailer\Mailer.php:330
X:\xampp\htdocs\cakephp-mail\tests\test_app\TestApp\Mailer\TestMailer.php:40
X:\xampp\htdocs\cakephp-mail\tests\TestCase\Mailer\MailerTest.php:939
```

### Note ###
This works live, both through a web page and through CLI. It's only a problem when doing tests.

**Comment by markstory** [comment]
Sounds like your application's routes have not been loaded. The test suite no longer automatically loads routes.

**Comment by markstory** [comment]
Follow up thought: Perhaps we should add a method to TestCase that makes loading application routes simpler, as redefining routes in test cases is hard to maintain.

**Comment by mentisy** [comment]
> Sounds like your application's routes have not been loaded. The test suite no longer automatically loads routes.

I added `Router::connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);` to the `MailerTest::setup` and the test passes. I was unaware that routes weren't automatically loaded.

> Follow up thought: Perhaps we should add a method to TestCase that makes loading application routes simpler, **as redefining routes in test cases is hard to maintain.**

+1 for that. Does the bold part of your quote mean that I would have to redefine the routes like I did in my above code in this comment, or is there a smarter way (I understand this is not a place for support, but as we're on the subject)

**Comment by markstory** [comment]
> Does the bold part of your quote mean that I would have to redefine the routes like I did in my above code in this comment, or is there a smarter way (I understand this is not a place for support, but as we're on the subject)

Ideally routes would not need to defined more than once, and instead each test case that depends on routes being loaded would call a helper method in setup() or before running code that depends on routes.

**Comment by mentisy** [comment]
> Ideally routes would not need to defined more than once, and instead each test case that depends on routes being loaded would call a helper method in setup() or before running code that depends on routes.

Thanks, I was able to create a trait that has a method to load routes. After adding that trait to the required tests, they passed.

It's not very "merge-worthy" though, and I'm pretty sure you guys would solve this better. Works for me in the meantime.

```
<?php

namespace App\Test\Traits;

use Cake\Routing\RouteBuilder;
use Cake\Routing\RouteCollection;
use Cake\Routing\Router;

trait RouterTrait
{
    public function loadRoutes()
    {
        $routeCollection = new RouteCollection();
        $routes = new RouteBuilder($routeCollection, '/app');
        require ROOT . DS . 'config' . DS . 'routes.php';
        Router::setRouteCollection($routeCollection);
    }
}
```
