### ISSUE TITLE
Too difficult to generate a form input without div

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13986]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5.
* Platform and Target: Apache, Linux, MySQL.

### What you did
In order to generate an input without `<div>` and `<label>` I had to do:
```
echo $this->Form->control('title', [
    'templates' => ['inputContainer' => '{{content}}'],
    'label' => false,
]);
```

### What happened
That generated the input without `<div>` and `<label>`.

### What you expected to happen
I would expect it to be a little bit easier like in 2.x:
```
echo $this->Form->control('title', [
    'div' => false,
    'label' => false,
]);
```

I would suggest to add support for ` 'div' => false` to `FormHelper::control()`.

**Comment by ADmad** [comment]
If you don't want the label and div then use the input specific method like `FormHelper::text()` or `FormHelper::select()`.

**Comment by dereuromark** [comment]
Aren't those specific methods also dropping the error/validation part that was usually quite useful to have wrapped?

**Comment by ADmad** [comment]
Call `FormHelper::error()` if you want validation errors.

**Comment by dereuromark** [comment]
Upgrading from 2.x here was really painful for most of us, though, mainly because of this.

**Comment by ADmad** [comment]
One can always use their own customized form helper. 

The decision to remove options for controlling generated markup and instead use string templates has been made years ago.

**Comment by dereuromark** [comment]
It has - indeed.
Thus we can probably close this at this point.

**Comment by bancer** [comment]
The cookbook need to be more clear about that.

**Comment by markstory** [comment]
> The cookbook needs to be more clear about that.

More clear about what specifically? That the decision to use templates was made long ago or that you can make your own formhelper if you have specific requirements?

**Comment by bancer** [comment]
> More clear about what specifically?

That in order to generate inputs without `<div>` and `<label>` text() should be used. 

Just to clarify. This issue is not about using string templates but about how it is inconvenient to disable the generation of `<div>`.

There is also inconsistency. The generation of the label can be disabled:
```
echo $this->Form->control('title', [
    'label' => false,
]);
``` 
But the generation of the div cannot be disabled in a similar manner.

**Comment by markstory** [comment]
The label is a separate widget, while the 'container' is a template which is why you interact with them separately. The `div` option will not return as the template system gives more control and flexibility without the complexity problems/bugs we had with the div option.

Where would you expect to find the additional context you're looking for in the documentation?
The [section on creating form controls](https://book.cakephp.org/3/en/views/helpers/form.html#creating-form-controls) has a tip about using individual methods, and each [input type method](https://book.cakephp.org/3/en/views/helpers/form.html#creating-input-elements) has its own section and examples.

**Comment by bancer** [comment]
> Where would you expect to find the additional context you're looking for in the documentation?

Probabliy in the [migration guide](https://book.cakephp.org/3/en/appendices/3-0-migration-guide.html#formhelper).

**Comment by othercorey** [comment]
> Probably in the [migration guide](https://book.cakephp.org/3/en/appendices/3-0-migration-guide.html#formhelper).

This?

> The div, before, after, between and errorMessage options have been removed from input(). You can use templates to update the wrapping HTML. The templates option allows you to override the loaded templates for one input.

I think there are some legacy ``input()`` names in the docblocks that should be updated to ``control()``.

**Comment by ADmad** [comment]
The use of method name `input()` instead of `control()` in 3.0 migration guide is expect as `control()` was added in a later minor.

**Comment by bancer** [comment]
Per my understanding `input()` in 3.x does not handle 'div' option too, does it?

**Comment by markstory** [comment]
@bancer That is correct, the `div` option was removed as part of the 3.0 work.

**Comment by othercorey** [comment]
Is there anything more here?  It looks like the questions have been answered.
