### ISSUE TITLE
3.9: Upgrade phpunit

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13998]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x

### What happened
Almost all travis builds are failing across plugins and ecosystem due to the mocks not being supported anymore.
We need to upgrade phpunit here.

See this complicated workaround that does not scale:
https://github.com/dereuromark/cakephp-shim/pull/61

Instead, I propose to make the necessary (API breaks) on test level to support a new PHPUnit version (7 or 8) in 3.next.
This seems necessary now to allow 3.x code and plugins to still be able to run for a while using php7.4+.

**Comment by markstory** [comment]
Is there a version of PHPUnit that is compatible with both PHP5.6 + 7.4? My understanding was that no such version of PHPUnit exists.

**Comment by garas** [comment]
PHPUnit version 7 seems feasible, it has pretty few changes, it might be possible to support `^5.7.14|^6.0|^7.0` at once. Drop v5 support if necessary.

Version 8 requires `void` on `setUp` and other methods, thus not possible with PHP 5.6.

**Comment by garas** [comment]
@markstory It is not necessary to use same PHPUnit version on PHP 5.6 and 7.4. But it should run with same CakePHP test suite.

**Comment by dereuromark** [comment]
I checked

> Fatal error: Declaration of Cake\Test\TestCase\DatabaseSuite::count($preferCache = false) must be compatible with PHPUnit\Framework\TestSuite::count($preferCache = false): int in /cakephp/cakephp/tests/TestCase/DatabaseSuite.php on line 24

Not sure how we can extend those without hardcoding the return types on our ends - which would make the code php7.0+

**Comment by dereuromark** [comment]
This would be my idea:
https://github.com/cakephp/cakephp/compare/3.next-phpunit
Based on PHP Version (Or PHPUnit version even), we could use a different factory method.

But there are sure other classes we might need to shim (as the test result shows).

**Comment by othercorey** [comment]
Is there any way we could just re-define the class for php 7?

**Comment by dereuromark** [comment]
That could also be an option.

**Comment by dereuromark** [comment]
Looks like this is now solved with https://github.com/cakephp/cakephp/pull/14061
Awaiting a patch release to be able to get my travis runs green here :)
