### ISSUE TITLE
possible Router BC break

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#13997]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8 latest

### What you did
Travis tests on cakephp-tags

### What happened
Now red after the release of
https://github.com/cakephp/cakephp/compare/3.8.6...3.8.7#diff-37dbf1f85d9888de3ac3c50006f2704fR1023-R1024

```
1) Tags\Test\TestCase\View\Helper\TagCloudHelperTest::testDisplayUlLi
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="tag-cloud"><li style="font-size: 80%"><a href="/?by=Foo" id="tag-1">Foo</a></li><li style="font-size: 160%"><a href="/?by=Bar" id="tag-2">Bar</a></li><li style="font-size: 120%"><a href="/?by=X-Y-Z" id="tag-3">X Y Z</a></li></ul>'
+'<ul class="tag-cloud"><li style="font-size: 80%"><a href="/{controller}?by=Foo" id="tag-1">Foo</a></li><li style="font-size: 160%"><a href="/{controller}?by=Bar" id="tag-2">Bar</a></li><li style="font-size: 120%"><a href="/{controller}?by=X-Y-Z" id="tag-3">X Y Z</a></li></ul>'
/home/travis/build/dereuromark/cakephp-tags/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:317
/home/travis/build/dereuromark/cakephp-tags/tests/TestCase/View/Helper/TagCloudHelperTest.php:109
```
https://travis-ci.org/dereuromark/cakephp-tags/jobs/622451557?utm_medium=notification&utm_source=github_status

Is this a regression, if the URLs change in a way that they dont fit expected one anymore?

**Comment by ADmad** [comment]
You mostly like have routes set for the same path twice, once using the `{controller}` and another using `: controller`.

In 3.9 the fallback routes were update to use the new style placeholders using curly braces.

**Comment by dereuromark** [comment]
This is a patch release on 3.8 though. I wouldnt expect this to happen here.
I will double check the setup of routes.

**Comment by dereuromark** [comment]
Hm, it now also fails in other plugin tests
https://travis-ci.org/dereuromark/cakephp-tools/jobs/622597363

All it uses is
```php
Router::scope('/', function (RouteBuilder $routes) {
	$routes->fallbacks(DashedRoute::class);
});
```

which worked fine since Cake 3.0.

**Comment by dereuromark** [comment]
Aha, so

    ->Url->build(['action' => 'x']);

was valid before (<= 3.8.6) and became `/x` URL (empty controller was removed).

Now in 3.8.7 this keeps the empty placeholders, in this case {controller}

Is this intended?

**Comment by dereuromark** [comment]
I can fix up the tests, but then all my prefer lowest checks show the opposite of the fix:
https://travis-ci.org/dereuromark/cakephp-tools/jobs/629502451?utm_medium=notification&utm_source=github_status

**Comment by markstory** [comment]
@dereuromark if there was no controller parameter in the request context then there isn't anything to replace. I think it would be better to raise an error when required placeholders have not been replaced though.

I am going to add an error for that situation as I don't think the behavior <3.8.6 was right either.

**Comment by dereuromark** [comment]
It seems to only be an issue for fake requests, so in tests.

**Comment by markstory** [comment]
Pull request up now to make optional parameters work with brace placeholders and make controller & action required keys when they are in the route template.
