### ISSUE TITLE
missing getOriginal() in EntityInterface

### ISSUE THREAD

**Issue by ludeus** [cakephp/cakephp#13999]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: all

### What you expected to happen
I think that all methods of EntityTrait must be present in EntityInterface. 
extractOriginal() will be added in 4.x; why not getOriginal() ?

**Comment by ADmad** [comment]
It has been added to the EntityInterface in 4.x

https://github.com/cakephp/cakephp/blob/2f6431f9dc40a2cba5f36892b482e3e6b77d045a/src/Datasource/EntityInterface.php#L207

**Comment by dereuromark** [comment]
And in 3.x it is still extractOriginal(), right?
https://github.com/cakephp/cakephp/blob/3.next/src/Datasource/EntityInterface.php#L41-L42

**Comment by ADmad** [comment]
getOriginal() and extractOriginal() are different methods. Former takes single field as arguments while latter takes array of fields.

**Comment by markstory** [comment]
Closing as the interface couldn't be updated in 3.x because of compatibility breaks, and has already been updated in 4.x.
