### ISSUE TITLE
cakephp/database package does not require or suggest cakephp/i18n

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14000]
`DateTimeType` expects a class that implements `I18nDateTimeInterface` for locale-aware parsing in `DateTimeType::marshal()`.  It also prefers that type when setting the mutable/immutable type class.

```
    "require": {
        "php": ">=7.2.0",
        "cakephp/core": "^4.0",
        "cakephp/datasource": "^4.0"
    },
```

We don't call out that dependency anywhere.  Can we assume the use of i18n types in `marshal()` or only where `_parseLocaleValue()` is called?

I don't think we test for this configuration either.  Should we warn the user they don't have the types they might expect?

I think they will hit a php error if they try to set a locale-aware format because the i18n types won't autoload by the checker.

**Comment by othercorey** [comment]
Depending on what's allowed, we could do something like this to simplify the code: https://github.com/othercorey/cakephp/commit/01cf912cb6d42f18c131456394c33298170f35ef

**Comment by markstory** [comment]
> We don't call out that dependency anywhere. Can we assume the use of i18n types in marshal() or only where _parseLocaleValue() is called?

There is a runtime check when `useLocaleParser()` is called. If the passed class is not suitable an exception is raised. We should however, add cakephp/i18n to the suggest list for the database package.

**Comment by othercorey** [comment]
> There is a runtime check when `useLocaleParser()` is called. If the passed class is not suitable an exception is raised.

Do you know if this refers to the interface::class we pass in?  If so, will that cause a failure?

```
        if (is_subclass_of($this->_className, I18nDateTimeInterface::class)) {
            $this->_useLocaleMarshal = $enable;

            return $this;
        }
```

https://www.php.net/manual/en/function.is-subclass-of.php
>Using this function will use any registered autoloaders if the class is not already known.

**Comment by othercorey** [comment]
Nevermind, I think it's safe.
