### ISSUE TITLE
Lost timezone part of FrozenTime JSON serialization on libicu < 51

### ISSUE THREAD

**Issue by nojimage** [cakephp/cakephp#14015]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: >=3.3
* Platform and Target: libicu < 51 (RHEL/CentOS 7, AmazonLinux2, etc)

### What you did

```php
echo FrozenTime::now()->jsonSerialize();
```

### What happened

```
2019-12-13T02:13:39
```

### What you expected to happen

```
2019-12-13T02:14:04+00:00
```

Lost timezone part.

I created a repository that reproduces this problem: [nojimage/cakephp-time-i18nformat-test](https://github.com/nojimage/cakephp-time-i18nformat-test)

#### 1. Use `ZZZZZ` instead of `xxx`

The difference between `ZZZZZ` and `xxx` is that `'Z'` is returned instead of `'+00:00'` when in UTC timezone.
'Z' is also correctly interpreted by the JavaScript `Date` class.

Quick fix: Add the below code in app's `config/bootstrap.php`,

```php
\Cake\I18n\FrozenTime::setJsonEncodeFormat("yyyy-MM-dd'T'HH':'mm':'ssZZZZZ");
\Cake\I18n\Time::setJsonEncodeFormat("yyyy-MM-dd'T'HH':'mm':'ssZZZZZ");
```

#### 2. Add `$useI18nFormat` to `setJsonEncodeFormat`'s 2nd argument

Add `$useI18nFormat` to `setJsonEncodeFormat`'s 2nd argument.
The param be used to control the formatting method.

```php
// `$useI18nFormat` to false, then jsonSerialize will use `format` method.
FrozenTime::setJsonEncodeFormat(DATE_ATOM, false);
// For backward compatibility, Default `$useI18nFormat` is `true`.
FrozenTime::setJsonEncodeFormat("yyyy-MM-dd'T'HH':'mm':'ssZZZZZ");
```

`format` is faster than `i18nFormat`:

```bash
docker-compose run --rm remi php /data/performance.php
Number of loops: 1,000,000
use i18nFormat: 8.725sec
use format: 0.854sec
```

I want to fix the problem with 2.

**Comment by ADmad** [comment]
Screw these distros which still provide ICU version older than 51.

51.1 was released in *2013*.

> Version: 51.1 (Initial Public Release of ICU4C 51)
> Release Date: 2013-03-22

http://site.icu-project.org/download/51

**Comment by othercorey** [comment]
@nojimage Can you give us an example of a system where you run into this issue?

**Comment by nojimage** [comment]
If you install PHP from "remi" repos on CentOS, the new ICU will be installed and there is no problem.
If you build your own or install PHP from SCL, the OS default ICU will be used, the problem occur. Installed PHP from "amazon-linux-extra" repo on AmazonLinux, same too.
It also occurs on some Japanese rental servers.

**Comment by othercorey** [comment]
@nojimage Do you send a large array of times back to the client in json?  The format might be slower, but only if you're sending a large amount.

**Comment by ADmad** [comment]
@nojimage What exactly version did you check on which had the problem?

**Comment by ADmad** [comment]
Based on the ICU version check in the test case it seems exist format works for ICU 50.0+

https://github.com/cakephp/cakephp/blob/9ff52cf29f268ba80a35ccc35456a17f5bd8f33e/tests/TestCase/I18n/DateTest.php#L156-L164

ICU 50.1 was release on 2012-12-17

> Version: 50.1.2
> Release Date: 2012-12-17

http://site.icu-project.org/download/50

I see no reason to add unnecessary complexity to our code to support ICU versions older than 7 years. I am **strongly** against making any change to the core to support such edges cases. We can instead just updated the requirements check in app skeleton to check for ICU version too https://github.com/cakephp/app/blob/master/config/requirements.php#L30

**Comment by nojimage** [comment]
@othercorey In my almost use cases will handle around 500 ~ 1,000 Time objects per request. Still, I would be happy if it would be a little faster and low load.

**Comment by nojimage** [comment]
@ADmad 50.1.2 (It is a live application on a shared rental server, and EC2 AmazonLinux1).
I've confirmed it in 50.2 on RHEL7 and AmazonLinux2, same too.

**Comment by othercorey** [comment]
I am surprised AmazonLinux2 has the same version as AmazonLinux1.
