### ISSUE TITLE
Marshalling date-time without seconds

### ISSUE THREAD

**Issue by malamalca** [cakephp/cakephp#14028]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev e9818adacf758b3057f4d7e3868c8b2791c6b3df
* Platform and Target: XAMPP, Windows 10, Chrome 79.0.3945.79, also on Edge
* PHP 7.2.2 (cli) (built: Jan 31 2018 19:51:55) ( ZTS MSVC15 (Visual C++ 2017) x86 )

### What you did
I am trying to save datetime field with browser via Form::control('datefield').
I created my HTML5 datetime input with step 60 parameter (I only want minutes). Database /mysql/ field is of "datetime" type.

Verified this bug on Chrome and Edge browsers.

### What happened
```html
<input type="datetime-local" name="valid_from" step="60" id="valid-from" value="2019-12-16T10:01:00.000">
```
When I change my element's hour to 10:02 (note that there are no fraction or millis displayed in html element because of step 60), _POST value of my field contains "2019-12-16T10:02" (no fractions or millis in post data either).

Marshalling value to datetime field fails as there are no valid formats in
https://github.com/cakephp/cakephp/blob/767b164747df789db8c0fbcf3bcf9eaf3be55b38/src/Database/Type/DateTimeType.php#L61

neither in 

https://github.com/cakephp/cakephp/blob/767b164747df789db8c0fbcf3bcf9eaf3be55b38/src/Database/Type/DateTimeFractionalType.php#L32

### What you expected to happen
Marshalling to work with HTML elements containing only "Y-m-d H:i" or similar format of datetime data in $_POST.

**Comment by othercorey** [comment]
We are thinking about replacing the specific formats with a regex check and then let DateTime constructor figure out the values.
