### ISSUE TITLE
i18n extract command fails

### ISSUE THREAD

**Issue by malamalca** [cakephp/cakephp#14027]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev e9818adacf758b3057f4d7e3868c8b2791c6b3df
* Platform and Target: XAMPP, Windows 10, cmd.exe
* PHP 7.2.2 (cli) (built: Jan 31 2018 19:51:55) ( ZTS MSVC15 (Visual C++ 2017) x86 )

### What you did
(1) Installed latest CakePHP by "composer create-project --prefer-dist --stability=dev cakephp/app:4.x caketest"
(2) Moved to "caketest" folder
(3) Tried to extract i18n strings to .pot file from console by running "bin\cake i18n extract"
(4) This is the console output:

> C:\htdocs\caketest>bin\cake i18n extract
> Current paths: None
> What is the path you would like to extract?
> [Q]uit [D]one
> [C:\htdocs\caketest\src\] >
> 
> Current paths: C:\htdocs\caketest\src\
> What is the path you would like to extract?
> [Q]uit [D]one
> [C:\htdocs\caketest\templates\] >
> 
> Current paths: C:\htdocs\caketest\src\, C:\htdocs\caketest\templates\
> What is the path you would like to extract?
> [Q]uit [D]one
> [D] >
> 
> The output directory \ was not found or writable.
> 

### What happened
After prompting for paths following error is issued: "The output directory \ was not found or writable."

### What you expected to happen
CakePHP to extract my localization strings into .pot file. This might be windows specific.

### Why it happened
Because following lines return true when they should not. There are no paths or plugin arguments. If I negate the condition in mentioned line, everything works fine.
https://github.com/cakephp/cakephp/blob/767b164747df789db8c0fbcf3bcf9eaf3be55b38/src/Command/I18nExtractCommand.php#L191
https://github.com/cakephp/cakephp/blob/767b164747df789db8c0fbcf3bcf9eaf3be55b38/src/Command/I18nExtractCommand.php#L193

**Comment by saeideng** [comment]
A PR has been merge 
you can test the master branch and confirm it
thanks for reporting

**Comment by malamalca** [comment]
This works great. Thanks.
