### ISSUE TITLE
errors when creating new application 

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#14023]
This is a (multiple allowed):

* [x] bug

* Windows 10, php73

After going through the issues
> https://github.com/cakephp/cakephp/issues/14021
> https://github.com/cakephp/cakephp/issues/14022

when accessing localhost: 8765, I have, first hand:

![image](https://user-images.githubusercontent.com/50879411/70856199-0f6e7600-1eb6-11ea-8e0b-57698224d27b.png)

After I fix this, another comes:

![image](https://user-images.githubusercontent.com/50879411/70856298-18f8dd80-1eb8-11ea-8e5e-7f9b3cba9e81.png)

and other...  (thanks to @ADmad  @Sean Kelly @dereuromark  et all patience and instructions)

![image](https://user-images.githubusercontent.com/50879411/70856316-afc59a00-1eb8-11ea-90bf-36d4d18e21bc.png)

WOW!  

![image](https://user-images.githubusercontent.com/50879411/70856321-0af78c80-1eb9-11ea-95db-a33b8c958e80.png)

WOW !!! went crazy ! I'm going to sleep. Tomorrow I see the rest ... this screen stunned me ...

**Comment by markstory** [comment]
Those depredations and warnings indicate that you are updating a cake3 application to cake4. Is that what you're doing?

**Comment by LuizMarin** [comment]
@markstory 

I am following the steps of "Create a CakePHP Project" and "Keeping Up To Date with the Latest CakePHP Changes" on
> https://book.cakephp.org/4/en/installation.html#create-a-cakephp-project

I was having a lot of errors in my little application. With php73 it ran fine. With php74 it worked well but every update ('composer update') was not completed. Then it started with a series of errors - even using php73.

Then I thought about starting over again. Then I followed the steps and started this huge list of problems # 14021, # 14022, # 14023.

According to the script I followed:
- composer installed version 3.8.0 (with composer --create-project ...)
- later (with composer update) updated to 3.8.7
- then again with composer update, did nothing else.

In my case, the image below did not come true. Not updated to 4.x. Only at 3.x

![image](https://user-images.githubusercontent.com/50879411/70862491-e54f9f00-1f1b-11ea-8aa9-3a5b03abf133.png)

Manually changing composer.json, as per the instructions there, resulted in it all.

NOTE: My goal is to start a new application. Using rc2, rc1 or beta4, and then using 'composer update' (as I did the first time weeks ago) didn't work. I was catching mistakes all over the place.

I will try to start over with an rc2 and see what happens.

**Comment by ADmad** [comment]
As stated in the error message change the typehints for the callback methods from `Event` to `EventInterface`.

**Comment by ADmad** [comment]
@LuizMarin Using `composer create-project --prefer-dist cakephp/app my_app_name` will currently get you 3.x skeleton. Those instructions will only we applicable after 4.0 stable is released.

**Comment by LuizMarin** [comment]
now I understand. Thanks for explaining
