### ISSUE TITLE
Upgrade script to CakePHP 4 error

### ISSUE THREAD

**Issue by SvenBuis** [cakephp/cakephp#14036]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.7
* Platform and Target: Vagrant, Ubuntu 18, PHP 7.3
Running:
`bin/cake upgrade rector --rules phpunit80 /var/www/html/tests`
`bin/cake upgrade rector --rules cakephp40 /var/www/html/`

### What you did
Run the provide command in the upgrade guide.
I did not run de update tot CakePHP 4 since the guide said not to. I did try, just to test, but updating with composer was a pain in the ass because of errors.

### What happened
For both commands:
`PHP Fatal error:  Declaration of Cake\I18n\Time::isThisWeek() must be compatible with Cake\Chronos\MutableDateTime::isThisWeek(): bool in /var/www/html/vendor/cakephp/cakephp/src/I18n/Time.php on line 27`

### What you expected to happen
That the upgrade script runs without errors

**Comment by garas** [comment]
`Declaration of Cake\I18n\Time::isThisWeek() must be compatible with Cake\Chronos\MutableDateTime::isThisWeek(): bool` means you have CakePHP 3.x, but Chronos 2.x.

Downgrade Chronos to 1.x.

Do not upgrade any CakePHP or PHPUnit related packages before running upgrade command.

**Comment by SvenBuis** [comment]
I have checked. 

Somehow chronos isn't locked on to a version in my composer.lock, but when I open the package and the README.md it show documentation urls to the 1.x

So I'm not running chronos 2. Also, I have only installed CakePHP and some FriendsOfCake package. I have not manually loaded cakephp/chronos. All these packages require 1.x.

**Comment by hagen00** [comment]
Same problem for me when trying to update from the latest Cake3.8 to 4. 
`bin/cake upgrade rector --rules cakephp40 /var/www/code/src` 
results in
```PHP Fatal error:  Declaration of Cake\I18n\Time::isThisWeek() must be compatible with Cake\Chronos\MutableDateTime::isThisWeek(): bool in /var/www/code/vendor/cakephp/cakephp/src/I18n/Time.php on line 27
```

**Comment by markstory** [comment]
I suspect this is caused by the dev dependencies for the upgrade tool pulling in chronos@2 and that conflicting with chronos@1 that 3.x applications use. I will try to reproduce this.

**Comment by markstory** [comment]
Likely related to #14070

**Comment by markstory** [comment]
Likely related to #14070

**Comment by dereuromark** [comment]
Upgrade app is being adjusted. Further issues should be reported there.

**Comment by hagen00** [comment]
Some issues, using the latest version of the upgrade tool. 
1. 
`bin/cake upgrade file_rename locales /var/www/myapp` results in
`PHP Fatal error:  Uncaught Error: Class 'Cake\Console\CommandRunner' not found in /var/www/upgrade/bin/cake.php:11`

`composer dump-autoload --optimize` fixed this and I was able to rename locales and templates

2. 
`bin/cake upgrade rector --rules phpunit80 /var/www/myapp/tests` results in
```

**Comment by othercorey** [comment]
Can you open a new ticket in the Upgrade project?
https://github.com/cakephp/upgrade/issues

**Comment by hagen00** [comment]
https://github.com/cakephp/upgrade/issues/128
https://github.com/cakephp/upgrade/issues/136
