### ISSUE TITLE
CsrfProtectionMiddleware does not work with Basic Auth

### ISSUE THREAD

**Issue by malamalca** [cakephp/cakephp#14035]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP Version: 4.x-dev e9818adacf758b3057f4d7e3868c8b2791c6b3df
* Platform and Target: Platform and Target: XAMPP, Windows 10, Chrome 79.0.3945.79
* PHP 7.2.2 (cli) (built: Jan 31 2018 19:51:55) ( ZTS MSVC15 (Visual C++ 2017) x86 )

### What you did
(1) I've setup a basic cakephp installation by "composer create-project --prefer-dist --stability=dev cakephp/app:4.x caketest"
(2) I've added authentication plugin "composer require cakephp/authentication"
(3) Turned on csrf middleware and auth middleware in Application.php, enabled session and basic auths

```php
    public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        $middlewareQueue
            ->add(new RoutingMiddleware($this))
            ->add(new CsrfProtectionMiddleware([]))
            ->add(new AuthenticationMiddleware($this));

        return $middlewareQueue;
    }
    public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $service = new AuthenticationService();

        // Load identifiers
        $service->loadIdentifier('Authentication.Password');

        // Load the authenticators, you want session first
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.HttpBasic');

        return $service;
    }
```
(3) navigated to http://localhost/caketest/

### What happened
An error pops up
instance of Cake\Http\Response, instance of Zend\Diactoros\Response given, called in C:\htdocs\caketest\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php on line 128

### What you expected to happen
I expected an auth popup to appear.

### Why it happened
Csrf middleware already filters \Zend\Diactoros\Response\RedirectResponse on redirects in line below.
https://github.com/cakephp/cakephp/blob/abcb6cf7bf7f2bbc797d9b75cea4a1381f1b42ac/src/Http/Middleware/CsrfProtectionMiddleware.php#L124

This time a response is of class \Zend\Diactoros\Response so executing _addTokenCookie fails because of strict parameter checking.

Everything works fine if I add another condition:
```php
            if ($response instanceof \Zend\Diactors\Response) {
                return $response;
            }
```

**Comment by markstory** [comment]
Fixed with #14037
