### ISSUE TITLE
Validation rule can not be added without a name

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#14038]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0

### What you did

this doesn't work:
```
public function validationDefault(Validator $validator): Validator
    {
        return $validator
            ->add('date_field', [
                ['rule' => 'date', 'provider' => 'custom'],
            ])
     }
```

this works:
```
public function validationDefault(Validator $validator): Validator
    {
        return $validator
            ->add('date_field', [
                'validationRuleName' => ['rule' => 'date', 'provider' => 'custom'],
            ])
     }
```

### What happened
Argument 1 passed to Cake\Validation\ValidationSet::add() must be of the type string, int given, called in vendor/cakephp/cakephp/src/Validation/Validator.php on line 475

### What you expected to happen
Validation rule added successfully without having to add a name

### Possible solution
revert add-method in ValidationSet class
from
`public function add(string $name, $rule)`
back to
`public function add($name, $rule)`

**Comment by ADmad** [comment]
Why can't you just provide a name as expected?

**Comment by ADmad** [comment]
Validations rules were always meant to be added with a name. It's just due to lack of strict typing in earlier versions of PHP and implicit type coercion that not providing a name (associative array key) didn't throw an error.

**Comment by markusramsak** [comment]
I use CakePHP for 9 years now und I have really really large projects where I don't WANT to think about an extra validation rule name every time I add a validation rule to the validation set because the validation rule in most cases has a self explaining name. There is no benefit in forbidding to skip the name, so why don't just allow numeric indexes? I really don't see the benefit when I name the validation rule 'date' to 'date' when adding to validation set - it is just redundant in my opinion and it wasn't documented that I HAVE TO use a name, so please remove this requirement. I want to upgrade over 10 CakePHP 3.8 applications to CakePHP 4.0 und I would add names like '0' or '1' or '2' or 'date' (with no benefit at all). I think that the name of the application rules are self explaining and don't need an extra name in the validation set.

**Comment by dereuromark** [comment]
We could add this to the shim plugin to auto add a name here if not given?

**Comment by markusramsak** [comment]
But why force the name it in the first place? What is the benefit? I really don't see it ...

**Comment by markusramsak** [comment]
It is an undocumented backwards incompatible change with no benefit. It took me several minutes find the real issue when I got the PHP error and others might just give up ... We want to be CakePHP 4.0 to be a simple upgrade, right?

**Comment by dereuromark** [comment]
To be able to remove it again or modify it based on this identifier, would be my assumption.

```php
    ->add('date_field', [
        ['rule' => 'date', 'provider' => 'custom'],
    ])
```
In your example this could actually auto-add "date" as key if not yet used (and otherwise throw exception). That would mitigate this issue - and I agree that this should be mitigated if possible that easily.

**Comment by markusramsak** [comment]
but why force it - what is the benefit?

**Comment by saeideng** [comment]
>it wasn't documented

https://github.com/cakephp/cakephp/blob/3.8.7/src/Validation/Validator.php#L429-L442

**Comment by saeideng** [comment]
this keys use for showing error 
`$....getError('password')['size]'` ....

**Comment by markusramsak** [comment]
When I add a validation rule, I never went that deep in the source code. In meant in the documentation or upgrade guide. I try to use everything properly as intended and I always get some extra work ... :(
Of course I just could add the validation rule names - that's not the question. The question is why change this and break applications and frustrate developers when it doesn't help anyone?

**Comment by dereuromark** [comment]
This would be my idea: https://github.com/cakephp/cakephp/pull/14041

**Comment by markusramsak** [comment]
I most cases (or in my case "all" cases) I don't care which validation rule failed. I just loop through the error messages array and give a list of errors to the user. I can imagine that some people use extra logic based on the name but why it is forced when I don't need it? I think it is the same reason why we have anonymous functions in PHP because we don't need a name in every case.

**Comment by markusramsak** [comment]
my backwards compatible simple solution (if the name exists) was:
`if (is_int($name)) { $name = (string)$name; }`
then the names would be "0" oder "1" which I would expect.

**Comment by saeideng** [comment]
A PR now open , follow discussion there
thanks

**Comment by markusramsak** [comment]
Maybe the label "defect" is more appropriate than "works-for-me" because it doesn't work in this case.
