### ISSUE TITLE
Time __tostring() add an entire year to the date on the last week of the year

### ISSUE THREAD

**Issue by yourikoeman** [cakephp/cakephp#14045]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Webserver:apache2, Database: mysql 8, TimeZone: Europe/Amsterdam 

### What you did
I tried to retrieve a DateTime value (Value=2019-12-31) from the database trough the model layer, after i retrieved it i tried to  use the DateTime with the `strtotime()` function. the value passed to this function appears to be wrong (2020-12-31). What appears to be happening is that the __tostring function uses the wrong format [Y instead of y] but i am not sure.

Related code:
```php
      /**
         * Create the strings used to determine the last
         * and first days of the month we are working with
         * Extra: $startDate and $endDate are Time objects
         */
        $startOfMonthString = date('Y-m-1', strtotime($startDate));
        $endOfMonthString = date('Y-m-t', strtotime($endDate));
````

### What happened
The resulting date is (2020-12-31)

### What you expected to happen
The resulting date to be (2019-12-31)

### Note:
Managed to fix this issue already by using `->i18nFormat('yyyy-MM-dd HH:mm:ss')` on the Time objects, but still made the issue since this does not seem like the desired __tostring behaviour

**Comment by markstory** [comment]
I'm not able to reproduce this problem in our test suite or in an application I have. The following tests pass for me

```php
    public function testStrtotime()
    {
        $t = new Time('2019-12-31');
        $this->assertEquals('2019-12-1', date('Y-m-1', strtotime($t)));
        $this->assertEquals('2019-12-31', date('Y-m-t', strtotime($t)));
    }
```
