### ISSUE TITLE
ErrorHandlerMiddleware does not use App Error configuration as default

### ISSUE THREAD

**Issue by mentisy** [cakephp/cakephp#14040]
This is a (multiple allowed):

* [x]  bug
* [ ]  enhancement
* [ ]  feature-discussion (RFC)
* CakePHP Version: 4.0.
* Platform and Target: apache, mysql, any request that throws an exception

### What you did
In `config/app.php` I have configured a custom errorLogger

```
'Error' => [
    'errorLevel' => E_ALL,
    'exceptionRenderer' => \Cake\Error\ExceptionRenderer::class,
    'skipLog' => [],
    'log' => true,
    'trace' => true,
    'errorLogger' => \App\Error\ErrorLogger::class,
],
```

### Expected Behavior
I expect that any logging was handled by `App\Error\ErrorLogger`

### Actual Behavior
Every exception is handled by `Cake\Error\ErrorLogger`.

I think that `Cake\Error\Middleware\ErrorHandlerMiddleware` should read from configuration if no config is passed to the constructor.

One way to solve it without changing core behavior is to get configuration in `ErrorHandlerMiddleware` constructor in `Application.php`, like so:
```
$middlewareQueue->add(new ErrorHandlerMiddleware(Configure::read('Error')))
```

My opinion though, for what it's worth, is that it should attempt to use app configuration by default.

**Comment by ADmad** [comment]
> $middlewareQueue->add(new ErrorHandlerMiddleware(Configure::read('Error')))

That's exactly what's done in the 4.0 app skeleton. https://github.com/cakephp/app/blob/d949a327749c65d026209e39c1d52f82c057fc4a/src/Application.php#L71
