### ISSUE TITLE
Missing support of callables in Query::contain()

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#14044]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: Apache, MySQL.

### What you did
Retrieving all translations according to the [cookbook](https://book.cakephp.org/3/en/orm/behaviors/translate.html#retrieving-all-translations-for-associations) works fine:
```
// in ArticlesTable.php
$article = $this->find('translations')->contain([
    'Categories' => function ($query) {
        return $query->find('translations');
    }
])->first();
```
I would like to refactor the closure to a method in CategoriesTable class and call it like this:
```
// in CategoriesTable.php
public function findAllTranslations($query) {
	return $query->find('translations');
}

// in ArticlesTable.php
$article = $this->find('translations')->contain([
    'Categories' => [$this->Categories, 'findAllTranslations'],
])->first();
```
This syntax works with custom validation rules in a table class:
```
$this->getValidator()->add('my_field', [
	'checkMaxPax' => [
		'rule' => [$this, 'myCustomValidationRule'],
	],
]);
```
So I would expect this syntax to work with `contain()` too but it doesn't.

### What happened
The error:
```
Illegal offset type in isset or empty

.../Vendor/cakephp/orm/EagerLoader.php:410
.../Vendor/cakephp/orm/EagerLoader.php:430
.../Vendor/cakephp/orm/EagerLoader.php:161
.../Vendor/cakephp/orm/Query.php:472
.../tests/TestCase/Model/Table/ArticlesTableTest.php:863
```

### What you expected to happen
I would expect the query without errors.

**Comment by markstory** [comment]
We have generally been removing/not adding support for the callable type as it creates security issues when it intersects with user data. You should be able to use Closure::fromCallable() to convert your callable into a closure.

**Comment by ADmad** [comment]
Also since options array can be used for containment like `'Categories' => ['conditions' => $foo]` allowing array callables would mean additional overhead to differentiate options array from callables.

As stated by Mark just wrap your use callable with `Closure::fromCallable()`.

**Comment by bancer** [comment]
> We have generally been removing/not adding support for the callable type as it creates security issues when it intersects with user data. 

It would be interesting to know what are those security issues.

> You should be able to use Closure::fromCallable() to convert your callable into a closure.

`'Categories' => Closure::fromCallable([$this->Categories, 'findAllTranslations'])` seems to work fine.
But I would rather use objects instead of closures. Something like `'Categories' => new TranslationsFinder()`. Perhaps I was not clear enough describing my issue. The purpose is to use no closures. Closures do not fit well into OOP in my opinion. Callables is one of the ways to achieve that. I would also be happy if `TranslationsFinder` be not a callable but a class that implements an interface with abstract `findAllTranslations` method (or any other more generic method name like `getQuery`) defined by the framework.

> Also since options array can be used for containment like 'Categories' => ['conditions' => $foo] allowing array callables would mean additional overhead to differentiate options array from callables.

I understand and partially agree with that. But callables are not necessarily a two items array. And I would not insist of using array syntax for callables. `new TranslationsFinder()` or `'CategoriesTable::findAllTranslations'` string could also be a callable. Would it really be such an overhead to use `is_callable($options)` in a similar way as `$options instanceof Closure` is used?

**Comment by bancer** [comment]
Just an idea:
```
// In the framework
interface QueryBuilder {
	public function getQuery($query);
}

// Somewhere in Cake\ORM where 'queryBuilder' is used
if ($options instanceof QueryBuilder) {
       ... $options->getQuery($query) ...
}

// In my app
class TranslationsFinder implements QueryBuilder {
	public function getQuery($query) {
		return $query->find('translations');
	}
}
```

**Comment by markstory** [comment]
> But callables are not necessarily a two items array. And I would not insist of using array syntax for callables.  ... Would it really be such an overhead to use is_callable($options) in a similar way

You're right they can be a bunch of different things and this is where all the risk comes from. As callables can also be a string, a closure, or an invokable class. The string and the array forms are the problematic ones as they can be created through user provided data. 

> But I would rather use objects instead of closures. Something like `'Categories' => new TranslationsFinder()`

With an invokable class, you can use `Closure::fromCallable()`. For example:

```php
class Finder {
   function __invoke($query) {
  }
}

$query->contain(['Categories' => Closure::fromCallable(new Finder())]);
```

**Comment by ADmad** [comment]
> Would it really be such an overhead to use is_callable($options) in a similar way as $options instanceof Closure is used?

Given all the various types that can be used as a callable in PHP, is_callable() is lot more expensive than `instanceof Closure` check.

That's one of the reasons `Closure::fromCallable()` was added.

**Comment by bancer** [comment]
>With an invokable class, you can use Closure::fromCallable(). 

Right, but my point is that I would like to use no closures as they do not fit well into OOP in my opinion.

**Comment by markstory** [comment]
> I would like to use no closures as they do not fit well into OOP in my opinion.

Why not? They are objects, and even have a class name.

**Comment by markstory** [comment]
To go back to your original ask of being able to refactor contain closures away. The contain method also supports the `finder` option which allows you to re-use an existing finder method to define the association query conditions. An example would be

```php
$query->contain(['Categories' => ['finder' => 'allTranslations']])
```

Does being able to use a finder help?

**Comment by bancer** [comment]
> Why not? They are objects, and even have a class name.

Closure class cannot be extended and Closure objects cannot be constructed using `new` keyword. So, we have limited control of these objects. And it doesn't feel right to rely on PHP's internal implementation details of closures.

> Does being able to use a finder help?

I think using 'finder' is okay. I wish the cookbook would be more clear about that option. Are there any limitations of using 'finder' vs a closure? Are there any scenarios that can be implemented by using closures but cannot be implemented by using 'finder'?

**Comment by othercorey** [comment]
> And it doesn't feel right to rely on PHP's internal implementation details of closures.

This isn't a solid argument for cakephp to change its design.  The behavior and scope of closures are well defined. The team is most likely to be open to interface changes based on used cases.

We understand you have a strong preference and want to implement code that's tightly coupled to a coding standard for your team.  However, cake has a lot of legacy, backwards compatibility,  a large number of unit tests and use cases to consider when changing something large.  The cakephp framework is also opinionated about how it designs the interfaces as there are many frameworks to evaluate and use.

The cost of adding something -- even if it's a solid OOP principle -- has to be worth the cost of maintenance. The team works with the time it has.

I hope you can understand that in these discussions.

> Are there any limitations of using 'finder' vs a closure? Are there any scenarios that can be implemented by using closures but cannot be implemented by using 'finder'?

This is basically overriding the default finder set for each association (which is just 'all').  See the `finder` option for each association in https://book.cakephp.org/4/en/orm/associations.html.

There is no limitation. In fact, the finder is called before the closure to create the `Query` instance.  

You can have a custom `finder` in the association definition in the table then pass a closure to the `contain()` method and the closure will be passed the `Query` created by that default finder.

The behavior difference is the finder mechanism is used which accepts arguments/options.
