### ISSUE TITLE
TranslateBehavior allowEmptyTranslations should only work on retrieval, not saving

### ISSUE THREAD

**Issue by JoshaMunnik** [cakephp/cakephp#14054]
This is a (multiple allowed):

* [x] bug
* [x] enhancement?
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0

### What you did

I created a small test app. I created a table `categories` with two translatable text fields. I used the shadow table strategy and created a table `categories_translations` containing an id, locale and two text fields using the same names.

I baked the templates, controllers and models. I adjusted the model/entity classes and added support for the TranslateBehavior using shadow table strategy. I adjusted the controller to include `finder => 'translations'` with the get call. I adjusted the add/edit templates to include additional input fields for extra locales.

I tested it and everything worked correctly, when adding or editing the `categories_translations` table contained the correct translated texts.

I then added `allowedEmptyTranslationes = false` so that with an empty translation, the original text is shown.

### What happened

After setting `allowedEmptyTranslationes = false` it was no longer possible to clear a text for a locale and save an empty string for that locale. Empty strings are ignored, only non empty strings are stored.

### What you expected to happen

Empty strings should be saved like any other string, so that it is possible to revert back to the original text.

### Additional comments

As I understand this is caused by a fix for https://github.com/cakephp/cakephp/pull/10342 ; but imho this fix seems to add incorrect behavior. Also I'm curious if this fix is required when using the new shadow table strategy.

Atm I fixed the 'bug' by adding code to the add/edit controller actions to change the TranslateBehavior allowedEmptyTranslationes setting to `true`

**Comment by ADmad** [comment]
I also use `ShadowTable` strategy with `'allowedEmptyTranslations' => false` and I am able to set a field to empty string after it has already been saved with a non empty value earlier.

I presume you are saving all translations together by nesting them under `_translations` key by using field names like `_translations.en.title`. I save 1 translation at a time by passing "regular" data array like `['title' => 'translated value']` and simply setting required locale for the behavior. They way the values end up in the shadow table without empty values being unset.

**Comment by JoshaMunnik** [comment]
I indeed save all translations using code similar to https://book.cakephp.org/4/en/orm/behaviors/translate.html#saving-multiple-translations

As temporary solution I have created a `Table` subclass that sets the translate behavior and uses `beforeSave` (using a high priority) and `afterSave` to temporary change the `allowedEmptyTranslations`

I discovered that updating the config of the behavior does not update the config of the strategy (is this an issue?), so I update the config of the strategy directly:

    $this->behaviors()->get('Translate')->getStrategy()->setConfig([
      'allowEmptyTranslations' => (true or false),
    ]);

**Comment by ADmad** [comment]
> As temporary solution I have created a Table subclass that sets the translate behavior and uses beforeSave (using a high priority) and afterSave to temporary change the allowedEmptyTranslations

Modifying the config through callbacks is a reasonable way to get what you want.

> I discovered that updating the config of the behavior does not update the config of the strategy (is this an issue?), so I update the config of the strategy directly:

Yeah it's the strategy class which actual handles the various operations so it's config is what needs to be updated. We kept the various config options as configs of the behavior class itself as convenience and backward compatibility.

**Comment by othercorey** [comment]
> > As temporary solution I have created a Table subclass that sets the translate behavior and uses beforeSave (using a high priority) and afterSave to temporary change the allowedEmptyTranslations
> 
> Modifying the config through callbacks is a reasonable way to get what you want.

We could split the config option into `allowLoadingEmptyTranslations` and `allowSavingEmptyTranslations`.

**Comment by JoshaMunnik** [comment]
I don't think that is a needed, I can not think of a situation where you save or update new translations and want that empty texts do not override existing translations.
