### ISSUE TITLE
Plugin route not loading

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#14052]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.
* Platform and Target: apache , mysql, php 7.3.9 , windows 10 .

### What you did
plugins/myPluginName/config/routes.php
```
<?php

use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'Api',
    ['path' => '/api'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
        $routes->setExtensions(['json']);
        $routes->resources('Posts');
    }
);
```
in Application.php 

`$this->addPlugin('Api', ['routes' => true]);`
### What happened
I am building REST api plugin
But not loading Plugin routes

**Comment by markstory** [comment]
What is the path to your routes snippet, and does your plugin have a `Plugin` class that implements the `routes()` method?

**Comment by eduilson** [comment]
I had this same problem. To solve, just go to **plugin_dir/src/Plugin.php::routes()**.

This method override route settings in **plugin_dir/config/routes.php**. Just remove this method or return: `parent::routes($routes)`

This solution will work only if you have created the plugin via bake.

**Comment by markstory** [comment]
@eduilson Yes bake generates code that uses the hook methods. This results in fewer files being loaded and is what I recommend for smaller plugins. We could add the parent call to the generated code, or switch back to a routes file if that makes sense to more folks.

**Comment by saeideng** [comment]
>We could add the parent call to the generated code

:+1:  this helps , and is enough IMO

**Comment by ADmad** [comment]
I realise this change can trip existing users but I would prefer if we don't promote old inefficient ways.

We can try to add comments / improve docs to make users aware of the change.

**Comment by infokani** [comment]
> What is the path to your routes snippet, and does your plugin have a `Plugin` class that implements the `routes()` method?

i updated code path

**Comment by markstory** [comment]
Ok. Does your plugin plugin class that has a `routes()` method?

**Comment by infokani** [comment]
> Ok. Does your plugin have `Plugin` class that has a `routes()` method?

Yes. There is. This is baked plugin. Should i use that method instead config/routes.php.

```
<?php
declare(strict_types=1);

namespace Api;

use Cake\Core\BasePlugin;
use Cake\Core\PluginApplicationInterface;
use Cake\Http\MiddlewareQueue;
use Cake\Routing\RouteBuilder;

/**
 * Plugin for Api
 */
class Plugin extends BasePlugin
{
    /**
     * Load all the plugin configuration and bootstrap logic.
     *
     * The host application is provided as an argument. This allows you to load
     * additional plugin dependencies, or attach events.
     *
     * @param \Cake\Core\PluginApplicationInterface $app The host application
     * @return void
     */
    public function bootstrap(PluginApplicationInterface $app): void
    {
    }

    /**
     * Add routes for the plugin.
     *
     * If your plugin has many routes and you would like to isolate them into a separate file,
     * you can create `$plugin/config/routes.php` and delete this method.
     *
     * @param \Cake\Routing\RouteBuilder $routes The route builder to update.
     * @return void
     */
    public function routes(RouteBuilder $routes): void
    {
        $routes->plugin(
            'Api',
            ['path' => '/api'],
            function (RouteBuilder $builder) {
                // Add custom routes here

                $builder->fallbacks();
            }
        );
    }

    /**
     * Add middleware for the plugin.
     *
     * @param \Cake\Http\MiddlewareQueue $middleware The middleware queue to update.
     * @return \Cake\Http\MiddlewareQueue
     */
    public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        // Add your middlewares here

        return $middlewareQueue;
    }
}

```

**Comment by ADmad** [comment]
Yes you should.

**Comment by markstory** [comment]
I will check the docs and make sure we aren't telling people to use the routes file when the code generated by bake doesn't use it.

**Comment by saeideng** [comment]
> Should i use that method instead config/routes.php.

```    /**
     * Add routes for the plugin.
     *
     * If your plugin has many routes and you would like to isolate them into a separate file,
     * you can create `$plugin/config/routes.php` and delete this method.
...
     */
    public function routes(RouteBuilder $routes): void
    {
```

see the doc block content

**Comment by markstory** [comment]
So do we want to add a `parent::routes($routes)` call to generated plugins? Or continue to rely on the doc block comments informing people to delete the method if they want to use the configuration file.

**Comment by markstory** [comment]
Do we want to add a `parent::routes($routes)` call to generated plugin classes or continue relying on the doc comment informing people to remove the method if they want to use the config file.

**Comment by dereuromark** [comment]
I am for auto adding the parent call. Removing it is simple if needed. Most wouldnt need removal would they?
