### ISSUE TITLE
Bug on timestamp with SQL SERVER [4.0]

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14058]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Windows, Nginx, PHP 7.3, SQL server 2017

### What you did
Run query with condition of datetime

### What happened
Below error occurred because sql server cannot convert timestamp with 6 digit of milisecond part to datetime type
```
SQLSTATE[22007]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string.
```

### What you expected to happen
Use datetime2 or change miliseconds part to 3 digit for datetime type in sql server

**Comment by othercorey** [comment]
Can you post the query you're using?

**Comment by mcsknp** [comment]
```
SELECT SystemSettings.id AS [SystemSettings__id], SystemSettings.name AS [SystemSettings__name], SystemSettings.priority AS [SystemSettings__priority], SystemSettings.description AS [SystemSettings__description], SystemSettings.value AS [SystemSettings__value], SystemSettings.start_time AS [SystemSettings__start_time], SystemSettings.end_time AS [SystemSettings__end_time], SystemSettings.deleted AS [SystemSettings__deleted], SystemSettings.created AS [SystemSettings__created], SystemSettings.modified AS [SystemSettings__modified] FROM system_settings SystemSettings WHERE (name = :c0 AND deleted = :c1 AND (start_time <= :c2 OR (start_time) IS NULL) AND (end_time >= :c3 OR (end_time) IS NULL)) ORDER BY priority ASC
```

With parameters is

|Name|Type|Value|
|-|-|-|
|c0|string|xyz|
|c1|boolean|false|
|c2|datetime|new DateTime()|
|c3|datetime|new DateTime()|

My table design is

|Column|Type|
|-|-|
|id|int|
|name|nvarchar(255)|
|priority|int|
|description|nvarchar(255)|
|value|nvarchar(255)|
|start_time|datetime|
|end_time|datetime|
|deleted|bit|
|created|datetime|
|modified|datetime|

**Comment by othercorey** [comment]
When you say you expected `Use datetime2`, what do you mean?  This is an existing database, correct?

**Comment by mcsknp** [comment]
It's error when convert timestamp with 6 digit of milisecond to `datetime` type but no error when convert its to `datetime2` type
