### ISSUE TITLE
Can not get tmp path of uploaded file

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14053]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: MacOS, Nginx

### What you did
Migrate amazon s3 file upload from 3.8.7 to 4.0

### What happened
Can not get uploaded file path to upload to s3 because 4.0 use `Zend\Diactoros\UploadedFile` for uploaded file.

### What you expected to happen
Get `file` property of `Zend\Diactoros\UploadedFile` via `$uploadedFile->getFilePath()` or etc...

**Comment by ADmad** [comment]
```php
$metaData = $uploadedFile->getStream()->getMetadata();
if ($metaData['wrapper_type'] == 'plainfile') {
    $tmpFileName = $metaData['url'];
}
```

**Comment by mcsknp** [comment]
I found that `Psr\Http\Message\StreamInterface` can be set to `Body` of `S3Client->putObject`.
Thank you for support!
