### ISSUE TITLE
4.x $_SESSION not always present causes type error

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#14065]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0
* Platform and Target: Debian 10, NGINX 1.14.2, PHP FPM 7.3.13, MariaDB 10.3.18

### What you did
1. Enable Debug Kit
2. Create an entry in any of your tables/models
3. Delete it after you created it

### What happened
The following error message shows up
![image](https://user-images.githubusercontent.com/9105243/71327064-1e7fa480-2504-11ea-8ab7-6b1bf3da8f2d.png)

**!! The item will still be deleted, its just that this error appears !!**

### What you expected to happen
No error

### Additional Infos

I tried adding a var_dump before the functions is called in vendor/cakephp/cakephp/src/Http/Session.php, which produces this error.
![image](https://user-images.githubusercontent.com/9105243/71327080-5a1a6e80-2504-11ea-9643-f109d96d0628.png)

As you can see here, the $_SESSION is **NOT** defined which causes the problem.
![image](https://user-images.githubusercontent.com/9105243/71327097-89c97680-2504-11ea-97d9-6b8d3140bc32.png)

I would suggest to add a check if $_SESSION is defined. If not, initialize it with an empty array.

**Comment by LordSimal** [comment]
The interesting is, that I only have this behaviour when debug mode is active.
When I disable debug mode, the $_SESSION variable is present.

**Comment by markstory** [comment]
Are your sessions not starting properly? The `$_SESSION` super global should be created when the session is opened/started which happens at the top of `write()`. If however, your session cannot be started because headers have been sent then this error could come up.

Setting `$_SESSION` to an array will solve this error but will not result in the session data being persisted as the session has not been started, and won't likely be written when the request ends. The deprecation error that is in your screen shot is a likely culprit of why the session couldn't be started.

**Comment by LordSimal** [comment]
Thanks @markstory,

indeed this problem is caused by the deprecation message.

But this deprecation message is only shown, when I activate the Debug Mode on a "live" instance.

Only when I add `Configure::write('DebugKit.safeTld', ['dev', 'local', 'example', 'at']);` or `Configure::write('DebugKit.forceEnable', true);` the message disappears after I delete an entry.

The DebugKit still doesn't show up on the live instance, but this is another issue.
Therefore this issue is caused by DebugKit.

Don't know if we want to dig deeper.

**Comment by othercorey** [comment]
The deprecation notice is being sent before the session start which causes session start to fail.  You need to fix the deprecation or disable deprecation notices with debug mode enabled.

**Comment by LordSimal** [comment]
@othercorey thx for that info.
I will therefore close this issue since it hasn't been a CakePHP issue from the beginning.
