### ISSUE TITLE
Cakephp 4 : inconsistency while loading model

### ISSUE THREAD

**Issue by Xbirdfr** [cakephp/cakephp#14063]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0
* Platform and Target: 
-> dev : windows, web server from cake (bin/cake server -p 8080), php 7.2.24
-> prod : ubuntu, apache & nginx proxy (plesk), php 7.2.26

### What you did
In my Controller, I load my model like this : 
`$UsersTable = TableRegistry::getTableLocator()->get('users');`

### What happened
on dev : works perfectly
on prod : UsersTable.php & User.php (entity) was not called, but insertion on database work

### What you expected to happen
I was expecting an error "user model not found, check the case" as well as not being able to work with the table, because the treatments carried out in particular in the file UsersTable.php are ignored

### What i've done to fix the issue
I set the U of users to Uppercase
`$UsersTable = TableRegistry::getTableLocator()->get('Users');`

**Comment by josegonzalez** [comment]
As you can see [from our examples](https://book.cakephp.org/3/en/orm/table-objects.html#getting-instances-of-a-table-class), we use the UpperCamelCase format that matches the filenames on disk for loading models.

The reason this works in your development environment is that Windows is case-insensitive by default, so it is inflecting the filename to `usersTable.php` but still loading `UsersTable.php`. On case-sensitive filesystems - such as the one on your Ubuntu server - the literal file `usersTable.php` does not exist and therefore you get an error.

The correct way is indeed to uppercase your modelnames. Unfortunately, there isn't a way for us to correct this as this has to do with the filesystem on a user's computer.
