### ISSUE TITLE
incompatibility with 7.3?

### ISSUE THREAD

**Issue by jviure** [cakephp/cakephp#14077]
Hi to everyone! I ve a little doubt. I've installed an existing cakephp 1.3 -> cakephp 2.10.19 project to a server with php 7.3 and I receive this error in some places:

Error: Cannot use 'object' as class name as it is reserved
File: /var/www/lib/Cake/Core/Object.php
Line: 18

I ve to downgrade to php 7.2 or what can I do? thanks a lot! :)

**Comment by ADmad** [comment]
CakePHP 2.10.19 is compatible with PHP 7.3. You'll just need to use `CakeObject` instead of the `Object` class.
