### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by ammukarthi** [cakephp/cakephp#14076]
i wrote this in appcontroller
  public function beforeRender(Cake\Event\Event $event)
   {
      
       $this->viewBuilder()->setTheme('Twit');
   }
and got this error 
Argument 1 passed to App\Controller\AppController::beforeRender() must be an instance of App\Controller\Cake\Event\Event, instance of Cake\Event\Event given, called in /var/www/html/website/vendor/cakephp/cakephp/src/Event/EventManager.php on line 311

**Comment by karmicdice** [comment]
This isn't an 'issue'.

```
public function beforeRender(\Cake\Event\Event $event)
{

   $this->viewBuilder()->setTheme('Twit');
}
```

Add a `\` before Cake.

This isn't a cake issue.

**Comment by ammukarthi** [comment]
if i changed that it shows another warning
Declaration of App\Controller\AppController::beforeRender(Cake\Event\Event $event) should be compatible with Cake\Controller\Controller::beforeRender(Cake\Event\EventInterface $event) [APP/Controller/AppController.php, line 29]

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by ammukarthi** [comment]
thank you for your help
