### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by ammukarthi** [cakephp/cakephp#14075]
i wrote my theme in appcontroller.php as 
public function beforeRender(Event $event)
   {
      
       $this->viewBuilder()->setTheme('Twit');
   }
the warning says
Declaration of App\Controller\AppController::beforeRender(Cake\Event\Event $event) should be compatible with Cake\Controller\Controller::beforeRender(Cake\Event\EventInterface $event) [APP/Controller/AppController.php, line 29]

**Comment by ADmad** [comment]
The error message clearly states what the problem is, fix the typehint for the `$event` argument as stated in message.

**Comment by ammukarthi** [comment]
i changed the code but i get this error
Argument 1 passed to App\Controller\AppController::beforeRender() must be an instance of App\Controller\Cake\Event\Event, instance of Cake\Event\Event given, called in /var/www/html/website/vendor/cakephp/cakephp/src/Event/EventManager.php on line 311
