### ISSUE TITLE
4.0.1 delete action error

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#14074]
composer create-project --prefer-dist cakephp/app public
    Installing cakephp/app (4.0.1): Loading from cache
    cd public
    bin/cake bake all Users

When trying to delete a record it errors out with:

Deprecated (16384): Request input data parsing feature has been removed from RequestHandler. Use the BodyParserMiddleware in your Application class instead. - /home/site/sites/io36.com/public/vendor/cakephp/cakephp/src/Event/EventManager.php, line: 311
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 305]

**Comment by garas** [comment]
Looks like https://github.com/cakephp/cakephp/pull/13981 fix is incomplete. https://github.com/cakephp/cakephp/issues/14065 has duplicate issue.

When deleting, web form is posted with data like `'_method=POST&_csrfToken=256c2...'` in `$request->input()`, but is empty `[]` in `$request->getParsedBody()` after handling `_method` and `_csrfToken`.

`BodyParserMiddleware` only handles `xml` and `json`. `RequestHandlerComponent` should check if it is json/xml or skip warning with `application/x-www-form-urlencoded` or something else.

**Comment by ADmad** [comment]
The check for displaying this warning is getting overly complicated. I would rather just remove the warning.
