### ISSUE TITLE
Add sql window function support

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14080]
Tracking issue for implementing window function support.

Goals:

- Any aggregate function can be extended to a window function
  - List of supported function is driver specific, up to user to pick right one
- Windows can be declared separate from functions and shared
- Support for all standard/common window definitions
  - Window Name
  - OVER()
  - PARTITION
  - ORDER BY
  - FRAME_START + FRAME_END
- Pre-defined wrappers for common window functions like `lag()` and `lead()`

**Comment by inoas** [comment]
Ref https://github.com/cakephp/cakephp/issues/10670

**Comment by ndm2** [comment]
I'm a little late to the party... but, @othercorey do you have any plans for adding support for [**named windows**](https://dev.mysql.com/doc/refman/8.0/en/window-functions-named-windows.html)? Looking at the current state, it would probably not possible to implement without breaking changes.

Also would you share my concern that the fact that all window functions that the builder can create are implemented as `AggregateExpression`, could be a little misleading, and perhaps awkward to use, given that not all window functions actually are aggregate functions, like `RANK()`, `ROW_NUMBER()`, `LAG()`, `LEAD()`, etc...?

**Comment by othercorey** [comment]
Can you open a new issue so we aren't discussing in one that isn't listed?

**Comment by ndm2** [comment]
Sure thing, I've create a new issue.
