### ISSUE TITLE
Error checking out the repository

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#14094]
I'm getting this issue when trying to checkout the repository (windows)

Cloning into '.\cakephp'...
  error: filename in tree entry contains backslash: 'company\test_plugin_three.po'
  fatal: Not all child objects of df7693eb8e7ca8e67a15bd5baa0c6c486327f39f are reachable

Anything I can do about it?

**Comment by garas** [comment]
At some point of time, CakePHP had file named `company\test_plugin_three.po`. There is now valid filename `test_plugin_three.po`.

However latest Git 2.24 warns even if current file tree doesn't contain invalid file names. Wait for next version. For now, run `git config --global core.protectNTFS false`.

https://github.com/git-for-windows/git/issues/2435

```
$ git ls-tree df7693eb8e7ca8e67a15bd5baa0c6c486327f39f
100644 blob f47df47f072a184415b3a31831d623b6f0ed6fa2    "company\\test_plugin_three.po"
```

**Comment by swiffer** [comment]
Thanks!!
