### ISSUE TITLE
4.0.1 Zip Release Includes Incorrect Dependencies

### ISSUE THREAD

**Issue by jimbo2150** [cakephp/cakephp#14099]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

The zip file of 4.0.1's composer.json file includes incorrect older package dependencies (CakePHP 3.8.* and dependencies). It appears the 3.x branch from cakephp/app was included by mistake.

The 4.0.0 release dependency versions appeared to be correct and was used for comparison.

**Comment by othercorey** [comment]
@markstory

**Comment by ADmad** [comment]
It's your merge commit @othercorey https://github.com/cakephp/cakephp/commit/adbe61881fc8a573461a28df846a739825f54eea#diff-b67911656ef5d18c4ae36cb6741b7965R31 :slightly_smiling_face:

**Comment by othercorey** [comment]
Of course.  I had no idea that would merge.

**Comment by chetanvarshney** [comment]
Yes cakephp-4-0-1.zip released with 3.x Application Skeleton. I made changes according this release then I realized something is wrong and found it's 3.x Application Skeleton.
Reverted changes.

**Comment by ADmad** [comment]
New zip has been uploaded for the release.

**Comment by ADmad** [comment]
Why are people even using those zips instead of composer?

**Comment by chetanvarshney** [comment]
I am using composer to update CakePHP and vendors code but for app skeleton I use zip file to compare files and update them manually.

**Comment by LuizMarin** [comment]
> Why are people even using those zips instead of composer?

I use composer only. I downloaded the zip to see why my composer.json does not upgrade to 4.0.1. I didn't find my answer, but I found more work for the team ...

**Comment by ADmad** [comment]
@LuizMarin Running `composer update` doesn't actually update your `composer.json`. It will only download new dependencies if available.

**Comment by LuizMarin** [comment]
> @LuizMarin Running `composer update` doesn't actually update your `composer.json`. It will only download new dependencies if available.

@admad  How do I keep everything updated? I want my cakephp to be updated daily. What alternatives do I have?

**Comment by chetanvarshney** [comment]
Edit composer.json
change as per below carefully

"cakephp/cakephp": "4.x-dev",
"cakephp/bake": "4.x-dev",
"cakephp/cakephp-codesniffer": "dev-next",
"cakephp/debug_kit": "4.x-dev",
"cakephp/migrations": "4.x-dev",

**Comment by ADmad** [comment]
@LuizMarin Just run `composer update` whenever a new 4.x release is done. You don't need to check for updates daily.

@chetanvarshney Those devs branches will be dropped soon. People should just use the stable releases now and per constraints provided in official skeleton app's composer.json

**Comment by LuizMarin** [comment]
thanks you

**Comment by jimbo2150** [comment]
@ADmad He was looking for a composer command that would take the latest app skeleton composer.json and merge it with the existing composer.json file so that thing like having the 4.0-dev from beta would be updated to the ^4.0 for stable while keeping our custom plugin paths, custom added dependencies, or other changes.

Unfortunately after doing a number of web searches there does not appear to be any function that will do this, sadly.

**Comment by chetanvarshney** [comment]
@ADmad Okay I will take care of them, thanks for informing us.

**Comment by LuizMarin** [comment]
@jimbo2150  @admad  the correct is 4.0-dev or ^4.0  ?

**Comment by ADmad** [comment]
This discussion is best continued on a help forum.
