### ISSUE TITLE
EagerLoader fails to load belongsTo (why at all)

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#14095]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: master
* Platform and Target: PHP 7.4

### What you did
In master currently one queries fails (most likely by changes introduced  in EagerLoader.php).

### What happened
Possibly related to InvalidArgumentException: "Unable to load `HierarchyNodes` association. Ensure foreign key in `Prices` is selected."

### What you expected to happen
Should work fine. Works with 4.0.

```php
        $this->belongsTo('HierarchyNodes', [
            'foreignKey' => 'hierarchy_node_id',
        ]);
```
Why is the Hierarchy Nodes loaded by the EagerLoader? Shouldn't it be part of the query already (as it is belongsTo). I'm not manually selecting fields so hierarchy_node_id is present...

**Comment by othercorey** [comment]
What is the query?

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by swiffer** [comment]
sorry, digged deeper, seems I've had an error in my query..
