### ISSUE TITLE
LogTrait behaviour does not match documentation

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#14115]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.1
* Platform and Target: irrelevant

### What you did
Within my AppController, i use the following code:
```
public function invokeAction(Closure $action, array $args): void
    {
         ConnectionManager::get('default')->transactional(
                    function () use ($action, $args) {
                        parent::invokeAction($action, $args);
                    }
                );
            }
        } catch (ExpectedException $e) {
            $this->log($e, LogLevel::INFO);
            [...]
       }
   }
```

### What happened

     Error: Argument 1 passed to Cake\Log\Engine\BaseLog::_format() must be of the type string, object given, called in /vagrant/oyaso/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 119

### What you expected to happen

The [documentation](https://book.cakephp.org/4/en/core-libraries/logging.html#logging-trait) says that
>  If $msg isn’t a string it will be converted with print_r before being logged.

so i would have expected that a stringified version of my exception is logged (as it has been in CakePHP 3.x)

**Comment by markstory** [comment]
This behavior was changed in 4.0 in fa745835a79 as the old behavior was not aligned with the PSR4 specs. You'll need to do `$e->getMessage()` print_r() yourself before logging. I can update the documentation.
