### ISSUE TITLE
Model->setDataSource() remembers bad database names

### ISSUE THREAD

**Issue by Tom-Condon** [cakephp/cakephp#14125]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x
* Platform and Target: Apache/MySQL

### What you did
Wrote a function that was supposed to collect data from multiple DBs using the same model.  Used Model->setDataSource() to change databases, and wrapped it in a try/catch to catch the MissingConnectionException.

### What happened
If I attempt to switch to a database that isn't set up in database.php, it throws the exception as expected.  If I try to go to a database that does exist RIGHT AFTER trying to setDataSource() to a non-existent DB, I get the same exception saying "The datasource configuration "firstDB" was not found in database.php".

https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Model.php#L3652

I checked the code, and I'm pretty sure the problem is that even if can't connect to a database, it keeps the name handy in $this->useDbConfig, and that gets thrown into $oldConfig the next time the function ic called.  If the new DB Configuration is using prefixes, it calls ConnectionManager::getDataSource() with the $oldConfig and the exception hit again.

### What you expected to happen
It switches to the database I tell it to, no exceptions.

**Comment by markstory** [comment]
Any chance you would want to make a pull request to fix this?

**Comment by othercorey** [comment]
@Tom-Condon Can you open a PR with the changes?
