### ISSUE TITLE
4.x - http/client

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#14127]
without having base uri you have to use like 
 ```php
new Client([
                'host' => "example.com",
                'scheme' => "https",
            ]);
```
after adding 
```php
new Client([
                'base_uri' => "https://example.com",
            ]);
```

`base_uri` could be change

**Comment by saeideng** [comment]
even we can add `uri` to accept `Uri` objects
maybe something like this 
```php
new Client([
                'uri' => new Uri("https://example.com"),
            ]);
```

**Comment by markstory** [comment]
Would you want to support path and query strings in the baseUrl as well? We could use `parse_url()` to parse the provided string into the current array data.

**Comment by ADmad** [comment]
I am not in favour of providing multiple ways to set uri/host/protocol. It makes the code and usage unnecessarily difficult to follow.

**Comment by saeideng** [comment]
>Would you want to support path and query strings in the baseUrl as well?

probably no

>I am not in favour of providing multiple ways to set uri/host/protocol

ok, then we can have a method to do this 
```php
new Client()->setUrl(....);
new Client()->setBaseUrl(....);
```

**Comment by saeideng** [comment]
A PR has been merged :  https://github.com/cakephp/cakephp/pull/15090
closing....
