### ISSUE TITLE
Twig error with Bake

### ISSUE THREAD

**Issue by ckheder** [cakephp/cakephp#14132]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Apache, MYSQL, Linux Mint .

### What you did
Using the Bake tool to generate model, controller.
`bin/cake bake model users`

### What happened
`Exception: Unexpected token "name" of value "if" ("end of statement block" expected).
In [/var/www/html/website/vendor/cakephp/bake/templates/bake/Model/table.twig, line 71]`

### What you expected to happen
Generate a CRUD for my application

I'm not familiar with Twig so i dont know how to fix this error.

**Comment by dereuromark** [comment]
This is fixed in latest twig/bake afaik. Just make sure you updated to that.

**Comment by dereuromark** [comment]
Follow up topics for Bake should go into the plugin tracker: https://github.com/cakephp/bake
