### ISSUE TITLE
Custom finder in Paginate missing Limit

### ISSUE THREAD

**Issue by gooseleggs** [cakephp/cakephp#14138]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.8
* Platform and Target: Apache web server on linux

### What you did
I started out with a paginate query in the controller and wanting to apply a limit clause

### What happened
When I created a query in the controller, it works as expected...

```
        $this->paginate = [            
            'limit'=>1
        ];

       $scans = $this->Scans->find();
        $scans ->contain(['Probes','Networks'])
                ->Select(['Scans.Type','Scans.created','Networks.name','Probes.address','Probes.name','total_ports'=> $scans->func()->count('Portscanresults.id')])
                ->leftJoinWith('Portscanresults')
                ->group('Scans.id')
                ->where(['Portscanresults.host_id'=>$id]);
```

and this did what was expected and added a limit=1 to the SQL query.  
I have then changed to use a custom finder, as this would be more appropriate.  However, it is NOT applying the limit clause to the SQL statement.  However, the pagination nav links are displaying correctly (like a limit has been applied).

Current code in controller:

```
       $scansOptions = [
            'host_id' => $id  
        ];
        
        $this->paginate = [            
            'finder' => [
                    'ScansByHost' => $scansOptions
            ],
            'limit'=>1
        ];
        // Get Scan history
        $this->loadModel('Scans');       
        $scans = $this->paginate($this->Scans);

```

Custom finder code:

```
   /**
     * Custom finder to find all scan for a host
     * @param Query $query Query string to be modified
     * @param array $options array of options to be passed
     * @return \Cake\ORM\Query
     */
    public function findScansByHost(Query $query, array $options) {
        $scans = $this->find();
        $scans ->contain(['Probes','Networks'])
            ->Select(['Scans.Type','Scans.created','Networks.name','Probes.address','Probes.name','total_ports'=> $scans->func()->count('Portscanresults.id')])
            ->leftJoinWith('Portscanresults')
            ->group('Scans.id')
            ->where(['Portscanresults.host_id'=>$options['host_id']]);
        return $scans;
    }

```

### What you expected to happen
I am expecting the limit options to be applied to the resulting SQL query.  This is a duplicate/more information for issue #11562.

**Comment by markstory** [comment]
I wasn't able to reproduce this using new code from bake. Is your custom finder applying a limit? I need a way to reproduce this this to help more.
