### ISSUE TITLE
Missing table alias in Table::updateAll method

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#14136]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: Apache, Linux, MySQL

### What you did
I tried to use `$this->updateAll(...)` in a table class. It is necessary to migrate queries with aliases from 2.x to 3.x. Simplified example of a query in 2.x:
```
UPDATE `users` AS `User`
SET `posts_qty` = (
    SELECT COUNT(*) AS `count` 
    FROM `posts` AS `Post` 
    WHERE Post.user_id = User.id
) 
WHERE `status` = 'active'
```

### What happened
Wrong query was generated because the alias is missing.
`$this->updateAll($fields, $conditions)` generated an invalid query without `User` alias:
```
UPDATE `users`
SET `posts_qty` = (
    SELECT (COUNT(*)) AS `count` 
    FROM `posts` `Post` 
    WHERE Post.user_id = User.id
) 
WHERE `status` = 'active'
```
This is quite annoying and does not allow to migrate from 2.x.

### What you expected to happen
I would expect `updateAll()` method to support aliases.

**Comment by markstory** [comment]
We don't include aliases in update queries because updates don't use joins and haven't had a need to include aliases. Adding aliases seems like a high risk change as it would break applications that have working subquery updates today.

Are you unable to change the conditions of your subquery?

**Comment by bancer** [comment]
I think there would be no risk if an optional alias parameter would be added to `updateAll()` method. It would not change the existing queries that are generated without an alias.

The conditions of the sub-query cannot be changed - the sub-query needs to know the id values of the parent query. Performance wise that is the most effective way to update many records with calculated values in large tables. Otherwise multiple queries would be needed with pagination.

**Comment by markstory** [comment]
> I think there would be no risk if an optional alias parameter would be added to updateAll() 

We cannot change the `updateAll` signature to add a parameter as it is an interface method, and changing it will break compatibility.

> The conditions of the sub-query cannot be changed - the sub-query needs to know the id values of the parent query. Performance wise that is the most effective way to update many records with calculated values in large tables. Otherwise multiple queries would be needed with pagination.

I wasn't suggesting you not use a sub-query or take the performance hit. My question was more
directed to the where clause of the subquery. Would the sub-query work if its where clause was `WHERE Post.user_id = users.id`?

**Comment by bancer** [comment]
> Would the sub-query work if its where clause was WHERE Post.user_id = users.id?

I cannot believe that this thought have not come to my mind. Yes, that works. :)

**Comment by dereuromark** [comment]
Closing then as this can be solved on dev side.
