### ISSUE TITLE
Specify ssl in dsn email string breaks the pattern

### ISSUE THREAD

**Issue by thedrumz** [cakephp/cakephp#14130]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.0

I'm triying to convert my email transport configuration to DSN url, but the ssl specified in host string breaks the dsn pattern

This is my config:
```
'EmailTransport' => [
        'default' => [
            'className' => SmtpTransport::class,
            'host' => 'ssl://mi.host',
            'port' => 465,
            'timeout' => 30,
            'username' => 'myusername@email.com',
            'password' => 'mypassword',
            'client' => null,
            'tls' => null,
            'url' => env('EMAIL_TRANSPORT_DEFAULT_URL', null),
        ],
    ]

```

But if I make a DSN string with this config
```
EMAIL_TRANSPORT_DEFAULT_URL=smtp://myusername@email.com:mypassword@ssl://mi.host:465
```
It results in a parsed error
<i>The DSN string 'smtp://myusername@email.com:mypassword@ssl://mi.host:465' could not be parsed.</i>
Because of <strong>ssl://</strong> in the string breaks the DSN pattern

What I spected is to specify SSL in a key, like tls or the other config settings
```
'EmailTransport' => [
        'default' => [
            'className' => SmtpTransport::class,
            'host' => 'mi.host',
            'ssl' => true,
            'port' => 465,
            'timeout' => 30,
            'username' => 'myusername@email.com',
            'password' => 'mypassword',
            'client' => null,
            'tls' => null,
            'url' => env('EMAIL_TRANSPORT_DEFAULT_URL', null),
        ],
    ]

```
And translate to DSN like this
```
EMAIL_TRANSPORT_DEFAULT_URL=smtp://myusername@email.com:mypassword@ssl://mi.host:465?ssl=true
```

**Comment by garas** [comment]
`Socket` supports `'protocol'` option, try to set it to `'ssl'`.

`EMAIL_TRANSPORT_DEFAULT_URL=smtp://myusername@email.com:mypassword@mi.host:465?protocol=ssl`

**Comment by thedrumz** [comment]
It worked fine, thanks!!
