### ISSUE TITLE
Default FileEngine Cache keys of elements in subfolders of templates/element

### ISSUE THREAD

**Issue by mmsd-ts** [cakephp/cakephp#14144]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.1

### What you did
* Set className of default Cache config to FileEngine::class (default from install)
* Create element file in app/templates/element/en_US/modal_signout.php
* Call the element in a view using <?= $this->element('en_US/modal_signout',[],['cache' => true]); ?>

### What happened
Cake\Cache\InvalidArgumentException thrown:
Cache keycake_element__en_US/modal_signout contains invalid characters. You cannot use /, \, <, >, ?, :, |, *, or " in cache keys.

### What you expected to happen
Characters disallowed for file created would be replaced with a valid character, e.g. '-'

**Comment by dereuromark** [comment]
@markstory 
I took care of this: https://github.com/cakephp/cakephp/pull/14145
