### ISSUE TITLE
cakephp live server files setup local server showing errors

### ISSUE THREAD

**Issue by cibyjohn** [cakephp/cakephp#14142]
currently i am working in a cakephp project.
While setup the files in local server showing as the error 
''Not Found'' and ''requested url was not on the server''.

In the initial without adding files to local folder can accessing the url in browser.
But adding files to local folder showing the error.
How can i resolve this issue.
Give me a solution for this issue.

**Comment by cibyjohn** [comment]
the old versions are used in this project.How will you upgrade to new version of cakephp.
What are the things we consider for updating the version in cakephp project.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
