### ISSUE TITLE
IntegrationTestTrait - get() & post() do not need to throw an exception

### ISSUE THREAD

**Issue by tfont** [cakephp/cakephp#14143]
`@throws \PHPUnit\Exception`

Since:
```
$this->get('path/dir');
$this->assertResponseCode(200);
```

will be catched with a negative test as:
```
$this->get('path/dir');
$this->assertResponseCode(404);
```

Note; this would be considered an 'enhancement' but should be discussed.

**Comment by dereuromark** [comment]
Yes, those can be removed IMO. You can make a PR here.

**Comment by tfont** [comment]
PR has been made and can be found:
https://github.com/cakephp/cakephp/pull/14193

**Comment by markstory** [comment]
Thanks @tfont
