### ISSUE TITLE
Add FrozenDateTime like FrozenDate and FrozenTime

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#14148]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: PHP 7.3

MySQL supports data types DATE, TIME, and DATETIME, which usually map to CakePHP classes Date, Time, and DateTime. When setting them to immutable (which is the default) they "translate" to FrozenDate for Date and FrozenTime for Time and DateTime. This means when I read records which contain both TIME and DATETIME columns, I get back FrozenTime objects for both. To display in a view I like to format TIME columns as HH:mm, and DATETIME columns as yyyy-MM-dd HH:mm. I can't do that by default because setting the default format for FrozenTime would affect both types so I have to do it in code. Worse, when I want to json_encode the records I'll get back either a DATETIME column without the date part, or a TIME column with an irrelevant date part. So I ended up creating my own FrozenDateTime class, which is nothing else but a copied FrozenTime class, just so I can set different defaults.

I'd like to have a FrozenDateTime class in addition to the 2 existing ones in CakePHP, so that each class may show and parse only the relevant parts.

**Comment by dereuromark** [comment]
FrozenTime extends Chronos and is the immutable DateTime
https://github.com/cakephp/cakephp/blob/master/src/I18n/FrozenTime.php#L30
As such I think this already exists.

**Comment by chtheis** [comment]
Am 09.01.2020 um 18:12 schrieb Mark Sch.:
> FrozenTime extends Chronos and is the immutable DateTime
> https://github.com/cakephp/cakephp/blob/master/src/I18n/FrozenTime.php#L30
> As such I think this already exists.

Yes, but FroznTime always includes a date part which is irrelevant for
TIME columns. That's why I asked for different classes for DATETIME and
TIME, though the code is (almost) the same.

A FrozenDateTime should format and parse including the date part, a
FrozenTime should only format and parse the time.

As I tried to explain I don't see a way do that with just one class for
both, DateTime and Time.

So a new FrozenDateTime would be what FrozenTime is now, and an updated
FrozenTime would be less (but what one would expect from the name).

**Comment by dereuromark** [comment]
We just majored, so there wont be any such change possible for years - for BC reasons.
But if there is a good name, we could add the new frozen Time one you suggest.
You should probably also look into https://github.com/cakephp/chronos first, providing the functionality there, and then it can be used by the core framework.

**Comment by othercorey** [comment]
`FrozenTime` is just an unfortunate name. It should have been `FrozenChronos` or something.

**Comment by chtheis** [comment]
I was afraid it will be too late for this change ...

Can we put it on a wish list for the next possible release?

And maybe someone has an idea how to set different defaults depending if
a FrozenTime object has or as not a valid date part without breaking BC.

And, addressing another remark, FrozenTime is a good name for sthg which
includes no valid date :)

**Comment by dereuromark** [comment]
I think it comes from Time() which also already existed. The old mutable datetime one.

**Comment by chtheis** [comment]
A solution in 4.1 or even 5.0 is OK for me.
I have a workaround with my own copies of ORM/Type/DateTime and I18n/FrozenDateTime. Ugly, because I had to copy a lot of code, but working.

**Comment by dereuromark** [comment]
`FrozenTimeOnly` extending https://github.com/cakephp/chronos/issues/102?
That said, you still should make the support in Chronos first, so the framework can use this new dependency.

**Comment by chtheis** [comment]
Why so complicated? All 3 could derive from Chronos, but focusing on the relevant parts of date and time only. My problem is not that FrozenTime doesn't work for DateTime or Time types, all I need is there. My problem is that I can't make it to behave differently, depending on the column type I'm dealing with.

Or am I missing something?

**Comment by markstory** [comment]
There have been a few discussions around adding a 'time only' object. After building the `Date` objects in chronos I don't think a 'time only' object should inherit/extend the core DateTime interfaces in PHP; instead it should be a net new object.

A new time object could be added without breaking compatibility if we gave people a way to opt-into the new time type mapping. The fractional datetime types are an example of this. I think the larger challenge for a 'time only' object is figuring out the appropriate methods and implementing them.

**Comment by othercorey** [comment]
Added to the roadmap wiki. Closing for now because this will just sit here forever.
