### ISSUE TITLE
Model::save() $fieldList ignores 'id'

### ISSUE THREAD

**Issue by DJAxel** [cakephp/cakephp#14159]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.
* Platform and Target: MySQL database

### What you did
I used Model::save to save user data, both for saving new data as to edit existing data:
```php
$this->Workdayentry->save($data, ['fieldList' => ['opmerkingen', 'vervoerwens']])
```

### What happened
The fact that 'id' is not listed in the fieldList is ignored (might be whatever the primary key is set to). Therefore, a user can send an id with the request to edit existing data he might not have permission to access.

### What you expected to happen
Since the id field is not listed, it should not be set to the model, OR the CakePHP documentation ([book ](https://book.cakephp.org/2/en/models/saving-your-data.html#model-save-array-data-null-boolean-validate-true-array-fieldlist-array)and [api reference](https://api.cakephp.org/2.10/class-Model.html#_save)) should state clearly that 'id'/the primary key is always saved in order to warn developers for this issue.

### Workaround
By unsetting the id in the request data, CakePHP can not use it while saving the data:
```php
unset($data['Workdayentry']['id']);
```

**Comment by markstory** [comment]
If the id was not always part of the fields how would the record be updated? The models don't have another way to locate the model being saved.

Changing the current functionality is not possible this late in 2.x lifecycle. I can update the documentation though.

**Comment by DJAxel** [comment]
@markstory Updating the docs would be nice. In my case, the ID was set earlier with `$this->Model->id = $id`in order to fetch some data. When saving, I don't want that overwritten by user input. Maybe that's not a very common use case, but with the current documentation, some security threats could easily be implemented by mistake.

Thanks in advance for your effort!

**Comment by dereuromark** [comment]
Always call `->create()` when saving a new entity :) That part should be documented already, though.

**Comment by DJAxel** [comment]
@dereuromark Correct, but what if data needs to be altered? If user data is not filtered on the id, he might edit data that is not his to edit. In my case, people should only edit their own entry. If another id would be specified, the user could hijack that user's entry.

**Comment by dereuromark** [comment]
The 2.x ORM indeed has a few of those old deficiencies. This sounds even like a security relevant one.
One could throw an exception if the given id doesnt match the already existing id on the stateful model class. This way it would at least prevent security relevant injection vectors.

**Comment by DJAxel** [comment]
@dereuromark That sounds sensible.

**Comment by ADmad** [comment]
> One could throw an exception if the given id doesnt match the already existing id on the stateful model class

That sounds risky, I bet someone has a valid use case for overriding the existing model is.

> If user data is not filtered on the id, he might edit data that is not his to edit.

One should have proper access control in place to avoid that.

**Comment by DJAxel** [comment]
> One should have proper access control in place to avoid that.

Well that's what field List is for, isn't it? I could do things manually, but then the whole feature wouldn't make sense.

> That sounds risky, I bet someone has a valid use case for overriding the existing model id.

I do agree with you on this one though, fair point.

**Comment by dereuromark** [comment]
But then you would include the id in the whitelist to be mass assigned imo.

**Comment by markstory** [comment]
The book has been updated now.
