### ISSUE TITLE
skipLog ignored

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#14167]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2

### What you did
configured
```
'Error' => [
        'errorLevel' => E_ALL,
        'exceptionRenderer' => ExceptionRenderer::class,
        'skipLog' => ['Cake\Http\Exception\NotFoundException'],
        'log' => true,
        'trace' => true,
    ],
```
then:
not existing url was called

### What happened
not found exception was logged

### What you expected to happen
skip logging of notfoundexception

**Comment by markstory** [comment]
I'm unable to reproduce this problem in a fresh application skeleton. After adding the `skipLog` configuration, throwing a `NotFoundException()` from a controller does not result in logs being created, while other non-skipped exceptions are logged.

Could you double check that your configuration is being loaded, and that you are passing configuration into the ErrorHandlerMiddleware. It should look like:

```php
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))
```

**Comment by markusramsak** [comment]
Thanks - I forgot to add the middleware. Sorry - I thought, I did everything right because the application was working ...
