### ISSUE TITLE
Problem with computed fields

### ISSUE THREAD

**Issue by gamesralito** [cakephp/cakephp#14166]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2
* Platform and Target: xampp for linux, mysql

### What you did
I follow the "Tutorials and examples" of the CookBook, in the tutorial "Tags and users", the section "Improving the Tagging experience" still does not work.

### What happened
It can't save the new tags from the computed field "tag_string", in ArticlesTable.php inside "beforeSave" method,  >> if ($entity->tag_string) {... << this " if " is not passing values.

When I debug the variable "$entity->tag_string" with an echo: I only see the old values or empty string.
But when I debug with "var_dump($entity)": I can see the new values of "tag_string".

$entity->tag_string does not work.

### What you expected to happen
In Cakephp 3.8 this tutorial works well.

**Comment by dereuromark** [comment]
Tutorials topic is probably more a https://github.com/cakephp/docs/ issue.

**Comment by markstory** [comment]
@gamesralito What does your Article entity look like?

**Comment by gamesralito** [comment]
> @gamesralito What does your Article entity look like?

@markstory here is what I have in Model/Entity/Article.php

`<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Collection\Collection;

class Article extends Entity {
    protected $_accessible = [
        '*' => true,
        'id' => false,
        'slug' => false,
        'tag_string' => true
    ];
    
    protected function _getTagString()
    {
        if (isset($this->_properties['tag_string'])) {
            return $this->_properties['tag_string'];
        }
        if (empty($this->tags)) {
            return '';
        }
        $tags = new Collection($this->tags);
        $str = $tags->reduce(function ($string, $tag) {
            return $string . $tag->title . ', ';
        }, '');
        return trim($str, ', ');
    }
    
    
}`

**Comment by markstory** [comment]
I don't see the public function in there. Are you adding it inside the class braces?

**Comment by gamesralito** [comment]
I wrote the same code that is in tutorial, this exactly code works on Cakephp 3.8

**Comment by markstory** [comment]
A parse error about a missing public indicates that you have a syntax error which is unrelated to CakePHP. The code you provided doesn't have any public methods so I can't help you fix the problem either.

**Comment by markstory** [comment]
Ok. In 4.0 the internal property was  renamed to _fields instead of _properties. I can get the tutorial updated.
