### ISSUE TITLE
FormProtection-Component expects $_File array while file-object is sent 

### ISSUE THREAD

**Issue by Tobse** [cakephp/cakephp#14178]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2
* Platform and Target: docker-container running Ubuntu, nginx, mySQL

### What you did
1. Enabled FormProtection component in AppController
     $this->loadComponent('FormProtection');
2. Generated file-upload field via FormHelper in View
    echo $this->Form->control('file', ['type' => 'file']);
3. Tried to upload file

### What happened
Upload fails with exception
    Unexpected field file in POST data, Missing fieldfile.name, file.type, file.tmp_name, file.error, file.size in POST data
In request-data the file-field is of type object
    object(Laminas\Diactoros\UploadedFile) {}

### What you expected to happen
Expected to have a file-object in request-data to do additional validation and move the file to a certain location.

**Comment by markstory** [comment]
A similar issue will exist in `SecurityComponent`.
