### ISSUE TITLE
4.x Mutators not hit 

### ISSUE THREAD

**Issue by andrekat** [cakephp/cakephp#14171]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.
* Platform and Target: Ubuntu 18.04.3 LTS, PHP 7.4.1, MySQL 8, Apache2

### What you did
Followed the tutorial on cakephp.org --> 

`  protected function _setPassword(string $password) : ?string {
        return (new DefaultPasswordHasher())->hash($password);
   }
`
This mutator function is placed in my User.php Entity. However it does not get hit when setting it via $user->password = 'plaintext'. The crazy thing is, it works on my local machine with same setup (docker). 

### What happened
Mutator function not hit.

### What you expected to happen
Mutator function should be hit.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
