### ISSUE TITLE
4.x - Association not found

### ISSUE THREAD

**Issue by andrekat** [cakephp/cakephp#14172]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Ubuntu 18.04.3 LTS, PHP 7.4.1, MySQL 8, Apache2

### What you did

Loading category to a product:

ProductsController.php

`
public function index()
    {
        $products = $this->paginate(Product::getAll()->contain(['Categories']));

        $this->set('products', $products);
    }
`

Product.php (Entity)

`
   public static function getTable(): Table
    {
        return TableRegistry::getTableLocator()->get('products');
    }

    public static function getAll(): Query
    {
        return self::getTable()->find();
    }

`

ProductsTable.php

`
 $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER',
        ]);

`

### What happened

Calling the action "index()" on "ProductsController" giving me following exception:

The Categories association is not defined on products.

The crazy thing about this is, that the same code works on my local development machine without throwing this exception. /tmp/* many times cleared. 

### What you expected to happen
Loading products with associated category.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
