### ISSUE TITLE
Tag a new 2.x version?

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#14175]
There're [quite a lot of improvements](https://github.com/cakephp/cakephp/compare/2.10.19...2.x) in the 2.x branch that are not released yet. Is there any reason not to tags a new version?

**Comment by markstory** [comment]
I can do a release later this week.

**Comment by tersmitten** [comment]
Thanks @markstory

**Comment by tersmitten** [comment]
https://github.com/cakephp/cakephp/releases/tag/2.10.20
