### ISSUE TITLE
FormHelper doesn't show the correct value of virtual fields when entity is dirty

### ISSUE THREAD

**Issue by diegosardina** [cakephp/cakephp#14206]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2
* Platform and Target: PHP 7.4

### What you did
I have a complex form where some calculations are evaluated but only the final result is stored in the database, the intermediate values are evaluated and showed through virtual fields in the form just for the verification by the operator.
There is a button "Preview" in the form that only performs patchEntity() just to show the values before the final save.

Just for the sake of simplicity, I have a Foo entity with value1 and value2 as real fields and sum as a virtual field.

Files were generated by bake, I will show just those parts that were modified for the example:

src/Model/Entity/Foo.php
```
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

class Foo extends Entity
{
    protected $_accessible = [
        'value1' => true,
        'value2' => true,
        'sum'  => true,
    ];

    protected $_virtual = [
        'sum'  => true,
    ];

    protected function _getSum()
    {
        return $this->value1 + $this->value2;
    }
}
```
src/Controller/FoosController.php
```
<?php
declare(strict_types=1);

namespace App\Controller;

class FoosController extends AppController
{
    [...]
    public function add()
    {
        $foo = $this->Foos->newEmptyEntity();
        if ($this->request->is('post')) {
            $foo = $this->Foos->patchEntity($foo, $this->request->getData(), [
                'associated' => ['Bars']
            ]);
            if ($this->request->getData('preview') === null) {
                if ($this->Foos->save($foo)) {
                    $this->Flash->success(__('The foo has been saved.'));

                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error(__('The foo could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('foo'));
    }
    [...]
}
```

templates/Foos/add.php
```
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('List Foos'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="foos form content">
            <?= $this->Form->create($foo) ?>
            <fieldset>
                <legend><?= __('Add Foo') ?></legend>
                <?php
                    echo $this->Form->control('value1');
                    echo $this->Form->control('value2');
                    echo $this->Form->control('sum');
                ?>
                <p>Entity value: <?= $foo->sum ?></p>
                <br>
            </fieldset>
            <?= $this->Form->button(__('Preview'), ['name' => 'preview']) ?>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>
```

![image](https://user-images.githubusercontent.com/22911186/73118603-ac610c00-3f56-11ea-9a74-ab0bcf74de34.png)

Debug output of $foo:

```
object(App\Model\Entity\Foo) {
	'value1' => (int) 1,
	'value2' => (int) 2,
	'sum' => '0',
	(int) 1 => null,
	'[new]' => true,
	'[accessible]' => [
		'value1' => true,
		'value2' => true,
		'sum' => true
	],
	'[dirty]' => [
		'value1' => true,
		'value2' => true,
		'sum' => true
	],
	'[original]' => [],
	'[virtual]' => [
		'sum' => true
	],
	'[hasErrors]' => false,
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Foos'
}
```

### What happened
The value of virtual fields and the final result are correct, but the FormHelper show a wrong value for virtual fields when entity is dirty.

### What you expected to happen
FormHelper must show the same values as the entity for virtual fields when entity is dirty.

### Workaround
Passing directly the value to the FormHelper works:

`echo $this->Form->control('sum', ['value' => $foo->sum]);`

I found this workaround [here](https://discourse.cakephp.org/t/3-4-cannot-display-a-virtual-field-in-a-form/2621) where another user had this issue in 2017

**Comment by ADmad** [comment]
You are POSTing the form for preview. When populating the HTML inputs POSTed values from request take precedence over the entity values, so the behaviour you see is expected.

The workound you have shown is the way to go if you want the POST values to be ignored.

**Comment by diegosardina** [comment]
> When populating the HTML inputs POSTed values from request take precedence over the entity values, so the behaviour you see is expected.
> 

Thank you. I got it, it makes sense now :-)

Then it is totally unrelated to virtual fields, indeed making them as real won't work either. 

In my opinion documentation [here](https://book.cakephp.org/4/en/views/helpers/form.html#getting-form-values-from-the-query-string) should be improved:

> The default contexts, such as EntityContext, **will fetch data from the current entity, or from $request->getData()**.

to

> The default contexts, such as EntityContext, **will fetch data from $request->getData() or the current entity**.

**Comment by ADmad** [comment]
@diegosardina Would you like to submit a PR to the docs with suggested change?

**Comment by diegosardina** [comment]
Yup, I will when I'm home. Closing here
