### ISSUE TITLE
Entity with underscored properties having problem with accessors

### ISSUE THREAD

**Issue by davidspeijer** [cakephp/cakephp#14202]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2
* Platform and Target: CentOS 7, PHP7.3.13 MariaDB 10.4

### What you did
I want to use Accessors method in an Entitity with underscores in the variable name.

```
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Company Entity
 *
 * @property int $id
 * @property int $customerid
 * @property string $name
 * ....
 * @property string|null $contact_general_email
 * ....
 */
class Company extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * @var array
     */
    protected $_accessible = [
        'customerid' => true,
        // .....
        'contact_general_email' => true,
        // .....
    ];

    protected function _getContactGeneralEmail($contact_general_email)
    {   
        return trim(strtolower($contact_general_email));
    }
}
```

### What happened
I get an error 

> strtolower() expects parameter 1 to be string, null given

```
protected function _getContactGeneralEmail($contact_general_email)
{
	return trim(strtolower($contact_general_email));
}
```

### What you expected to happen
According to the docs (https://book.cakephp.org/4/en/orm/entities.html#accessors-mutators) this should be the right way to use the accessor. 

> Accessors use the convention of _get followed by the CamelCased version of the field name.

When I remove the accessor, the field is loaded in the correct way (so the var `$contact_general_email` is not null or empty). 

When use the accessor on a field without underscores it is working without a problem. For example this is working;
```
protected function _getName($name) {
	return strtoupper($name);
}
```

**Comment by markstory** [comment]
Is your contact_general_email column ever null?

**Comment by davidspeijer** [comment]
Totally my error. The 2nd result was a null value. Simple check for null value solved the "issue".

```
protected function _getContactGeneralEmail($contactGeneralEmail) {
	return $contactGeneralEmail != null ? trim(strtolower($contactGeneralEmail)) : null;
}
```

Or is there a better method to check for null value?

**Comment by othercorey** [comment]
If you always want a string value, you can do something like `trim(strtolower($contactGeneralEmail ?? ''))`
