### ISSUE TITLE
Disable select alias generation for ORM query used as join subquery

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14203]
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

When an ORM query is used as a subquery for a join, the field aliases are still generated which requires the user to map new aliases for every field/column they want to use from the join.

```
LEFT JOIN (
    SELECT
      ClientSites.id AS "ClientSites__id"
    FROM client_sites ClientSites
    WHERE
      client_id = :c0
  ) Access ON Access.id = ClientSites.id
```

Would be nice to have a way to disable the alias generation for the query.

**Comment by ADmad** [comment]
Don't we need to populate entities from the subquery when using subqueries for join? Without the aliases the ORM wouldn't be able to do so?

**Comment by othercorey** [comment]
Does it work like that? I couldn't find any subquery tests for ORM queries.

**Comment by markstory** [comment]
If we didn't generate aliases in subqueries we could break existing queries that people have built on the aliases existing.

**Comment by othercorey** [comment]
It would have to be an option set if anything.

**Comment by othercorey** [comment]
This would also be useful for CTE/with clauses.

**Comment by othercorey** [comment]
Now that we have CTE/with, I'm going to try to get a PR for 4.1.

**Comment by othercorey** [comment]
Implemented in https://github.com/cakephp/cakephp/pull/14764
