### ISSUE TITLE
`ServerRequest` shouldn't try to build itself.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#14213]
- Methods like `_processPost()`, `_processFiles()`, `_processGet()` shouldn't exist in `ServerRequest`. All that data pre processing should be consolidated within `ServerRequestFactory` and then passed to `ServerRequest`'s constructor.

- `ServerRequest::_processPost()` has special handling for content type `'application/x-www-form-urlencoded'` to convert the string input data into array. This should be moved into `BodyParserMiddleware` where other content types like `application/json` and `application/xml` are parsed.

- `ServerRequest::input()` should be deprecated. One can use `ServerRequest::getBody()` to get the stream containing the input string. Also the `$callback` argument of the method which allows converting input string to other representations is unnecessary as `BodyParserMiddleware` can handle the same.

**Comment by markstory** [comment]
> Methods like _processPost(), _processFiles(), _processGet() shouldn't exist in ServerRequest

Would you still want to retain backwards compatibility with the current `ServerRequest` constructor? I worry about thrashing a non-trivial amount of tests for a change like this.

**Comment by ADmad** [comment]
> Would you still want to retain backwards compatibility with the current ServerRequest constructor?

The constructor could remain same.

**Comment by dereuromark** [comment]
Can this be closed?

**Comment by ADmad** [comment]
Not yet.
