### ISSUE TITLE
POST data not in getData

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#14210]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.2
* Platform and Target: Apache 2.4

### What you did
JSON data sent using curl 
curl --request POST http://.../add-comment.json -H 'Content-Type: application/json'  -d @add-comment.json

### What happened
$this->request->getData() is empty array
$this->request->input() contains JSON string

### What you expected to happen
$this->request->getData() contains POST data

### What you did
submit data using form
to action .../add-comment

### What happened
$this->request->getData() is array with data
$this->request->input() contains url encoded data string, incl. _csrfToken

### What you expected to happen
behaves as expected

**Comment by markstory** [comment]
In case 1 did you also apply the [BodyParserMiddleware](https://github.com/cakephp/cakephp/blob/master/src/Http/Middleware/BodyParserMiddleware.php) to your application? Without that CakePHP doesn't automatically decode request bodies that aren't encoded as form-encoded data.

**Comment by nitramxx** [comment]
I didn't apply the middleware. It works as expected once added to the middleware queue.

So it's not a bug, maybe a suggestion - it doesn't have to be decoded, but it would be intuitive to  have access to raw data (string) using getData() even when middleware is not applied.

**Comment by ADmad** [comment]
> ... but it would be intuitive to have access to raw data (string) using getData() ...

There's already `ServerRequest::input()` to get the raw request data.

**Comment by nitramxx** [comment]
I am not saying there's no way. Just that without applying middleware, there is no data coming out of getData().

The [documentation](https://book.cakephp.org/4/en/controllers/request-response.html#Cake\Http\ServerRequest::getData) says: 

> All POST data can be accessed using Cake\Http\ServerRequest::getData(). 

Raw data could be served for the sake of consistency?

Don't consider this as me trying to be right, just trying to help. The issue can be closed if you don't think it's an idea worth implementing.

**Comment by ADmad** [comment]
The docs have been updated to reflect how the code actually works.
