### ISSUE TITLE
HtmlHelper::para should accept "null" as first (CSS-class) argument

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#14225]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.3

### What you did

Trying to create an `<p>` tag without a class attribute. In a template file:

```
echo $this->Html->para(null, 'my text');
```

### What happened

*TypeError Argument 1 passed to Cake\View\Helper\HtmlHelper::para() must be of the type string, null given*

### What you expected to happen

No error should be thrown.

An element without CSS-class should be created:

```
<p>my text</p>
```

### Additional note

Further arguments:
- The second argument (text) is already allowed to be *null*.
- CakePHP 3 accepts *null*, so this would ease the migration to CakePHP 4

**Comment by markstory** [comment]
Allowing `string|null` seems reasonable to me.
