### ISSUE TITLE
Table::loadInto() does not work with new entities

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#14224]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.6

### What you did
````PHP
$new_invoice = $this->Invoices->newEntity();

//skipped some irrelevant code here
$new_invoice->user_id = 1;
//skipped some irrelevant code here

$new_invoice = $this->Invoices->loadInto($new_invoice, ['Users.Useraddresses']);

$copy_columns = [
     'firstname',
     'lastname',
     'company',
     'country_id',
     'city',
     'postcode',
     'address1',
     'address2',
];

foreach ($copy_columns as $col) {
    //this code fails because $new_invoice->user is null
    $new_invoice->set($col, $new_invoice->user->useraddress->get($col));
}
//skipped some irrelevant code here

$this->Invoices->saveOrFail($new_invoice);
````

### What happened
Looks like `loadInto` does not work correctly with new entities. It silently fails instead.
`$new_invoice->user` has `null` value

### What you expected to happen
Expected that following line
```PHP
$new_invoice = $this->Invoices->loadInto($new_invoice, ['Users.Useraddresses']);
```
would have same result as following line:

```PHP
$new_invoice->user = $this->Invoices->Users->get(1, ['contain' => 'Useraddresses']);
```

**Comment by markstory** [comment]
The `loadInto` is failing because your new entity does not have a primary key value, so associations cannot be loaded. Under the hood `loadInto()` does an additional query for the provided entity's primaryKey fields and applies containments.

**Comment by asgraf** [comment]
@markstory  Yes, i'm aware of that.
The question is why primary key value is required in the first place.
IMHO only foreign field value should be required.

```PHP
$this->SomeTable->loadInto($entity, ['Users']);
```
should work internally like this:
```PHP
$entity->user = $this->SomeTable->Users->get($entity->user_id);
```

**Comment by markstory** [comment]
Currently the primary key is required as we use contain() to load all the requested associations in as few queries as possible. The strategy you're suggesting would be ok for belongsto but would not be possible for any other association type.
