### ISSUE TITLE
Interrupt email sending in reusable mailer

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#14220]
This is a:

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x, 4.x

When sending an email using a reusable Mailer i usually load the email recipient directly in the mailer methods. If for some reasons the email should not be sent to anybody, is not possible to interrupt the email sending.

It should be awesome if in the mailer action there will be the possibility to interrupt the email sending with a specific method call, in order to separate the logic of email sending from the controller.

**Comment by markstory** [comment]
> It should be awesome if in the mailer action there will be the possibility to interrupt the email sending with a specific method call, in order to separate the logic of email sending from the controller.

What do you have in mind? What would the methods/API you use look like?

**Comment by doshu** [comment]
probably shoud be enough calling a method inside the mailer action like "$this->abortSending()" or simply returning false. intercept that in the "send" method of \Cake\Mailer\Mailer class like this

`public function send($action, $args = [], $headers = [])
{
    try {
        if (!method_exists($this, $action)) {
            throw new MissingActionException([
                 'mailer' => $this->getName() . 'Mailer',
                 'action' => $action,
            ]);
        }

       $this->_email->setHeaders($headers);
       if (!$this->_email->viewBuilder()->getTemplate()) {
           $this->_email->viewBuilder()->setTemplate($action);
       }

       $this->$action(...$args);
       if($this->isSendingAborted()) {
           return true;
       }
  
       $result = $this->_email->send();
    } finally {
        $this->reset();
    }
    return $result;
}`

**Comment by markstory** [comment]
Couldn't your action raise an exception to halt the send?

**Comment by doshu** [comment]
of course it can, but if reusable mailer was been created in order to
separate the logic from the controller, it should be awesome if it can
abort the email sending without need to catch exception in the controller.

Il giorno mar 28 gen 2020 alle ore 20:24 Mark Story <
notifications@github.com> ha scritto:

**Comment by josegonzalez** [comment]
In what cases would you want to send the abort that would be applicable to multiple mailers?

**Comment by doshu** [comment]
usually, reusable mailer, are used in conjunction with event system. when,
for example, we throw an event from a controller, the controller itself
doesn't know what happens in the event observers.
The mailer can be used as event listener and when a specific event is
fired, an email will be sent. We don't know first if there are any
recipient for that specific event, and if there are no recipients the
mailer throws an error. No exceptions can be thrown to stop the sending
otherwise all the observer listening on the same event will not be executed.

in this case there is the need to stopping the email sending without throw
exceptions.


Il giorno mer 29 gen 2020 alle ore 10:23 Jose Diaz-Gonzalez <
notifications@github.com> ha scritto:

**Comment by markstory** [comment]
> of course it can, but if reusable mailer was been created in order to
separate the logic from the controller, it should be awesome if it can
abort the email sending without need to catch exception in the controller

Yes, the duplicate catch blocks would be tedious. We could add a specific exception type that mailers could use to signal failure. Similar to the StopException used in commands.

I am reluctant to add a hook method as the timing of hooks is fixed and people will need a way to run logic after the hook as well.

**Comment by berarma** [comment]
I've also found some shortcomings when working with the Mailer class mainly because it's too rigid. It does one thing well but there's no flexibility to change the way it's done. There's no way to do anything with the resulting email message before or after delivery.

I always end up implementing my own Mailer class by overriding the `send` method. I copy it and modify it to do what I need. Not ideal but it works.

Hooks might not be the best solution. I would like to be able to handle the logic outside of the `send` method. Something like this:

```php
$mailer = new MyMailer();
$mailer->$action(...);
$mailer->viewBuilder()->setTemplate($action);
// Here we can do checks on the mailer or change it
...
if ($checksPassed) {
  $mailer->deliver();
}
$mailer->restore();
```

That's basically what the `send` method does but the `restore` wouldn't work here because it depends on something else the `send` is doing. Instead of calling restore you should just dispose the Mailer object.

If this could streamlined into something like:

```php
$mailer = new MyMailer();
$mailer->prepare($action, ...); // Save internal state, set template and invoke action
// Here we can do checks on the mailer or change it
...
if ($checksPassed) {
  $mailer->execute(); // Send email and restore internal state
} else {
  $mailer->cancel(); // Restore internal state
}
```

This code could be implemented in Mailer classes as helper functions in our projects without overriding `send`.

**Comment by ADmad** [comment]
@berarma The `Mailer` is essentially a convenience wrapper. If you want more flexibility you can use the `Message`, `Mailer\Renderer` and one of the transport classes directly to sent mails.

**Comment by berarma** [comment]
> @berarma The `Mailer` is essentially a convenience wrapper. If you want more flexibility you can use the `Message`, `Mailer\Renderer` and one of the transport classes directly to send mails.

I know but does that mean that convenience wrappers are sealed and rather we search for solutions elsewhere? I've done that but my 2 cents.

**Comment by markstory** [comment]
Making send() composed of smaller methods that could be overridden or used without calling send() sounds reasonable to me. You mentioned adding prepare() and execute() @berarma are there other steps that could be split up?

**Comment by doshu** [comment]
i think that could be enough create a method like "beforeSend" where can be
implemented a logic to decide if the mail must be sent or not.
Returning false in the beforeSend method must stop the email sending
process.
In addition can be splitted the process of loading email recipients in a
different method. The method must returning an array of recipients, that
could be empty too.
An empty recipients array must stop the sending process

Il giorno mar 18 feb 2020 alle ore 23:55 Mark Story <
notifications@github.com> ha scritto:

**Comment by berarma** [comment]
> Making send() composed of smaller methods that could be overridden or used without calling send() sounds reasonable to me. You mentioned adding prepare() and execute() @berarma are there other steps that could be split up?

I can't think of any other steps. Of course the `cancel` method would be equivalent the current `restore` method. No need to add one more method unless it has to do something different. I was carried away by the semantics.

> i think that could be enough create a method like "beforeSend" where can be implemented a logic to decide if the mail must be sent or not. Returning false in the beforeSend method must stop the email sending process. In addition can be splitted the process of loading email recipients in a different method. The method must returning an array of recipients, that could be empty too. An empty recipients array must stop the sending process

@doshu, this would be pretty easy to implement in your own Mailer class.

@markstory, to make it easier, the `prepare` method could return a boolean that would allow stopping the sending of the email. This way you would just override the `prepare` method (or whatever is called), call the parent method, do the checks and return true/false.

**Comment by markstory** [comment]
Ok. Is there a way to combine the two ideas going on here? Or does having a beforeSend() method reduce the need to have finer grained public methods?

**Comment by doshu** [comment]
i think that a beforeSend method could allow moving the entire email
sending logic in the mailer itself, and i think that this should be the
purpose of reusable mailer.
Creating some public methods like prepare and restore are useless if i must
call them, for example, in a controller.
The main goal of this issue is to add a way to stop the email sending where
the reusable mailer action was already called, for example, when an event
is fired, and the who have fired the event have no visibility of what
happens later.

another options is a simple method or a specific exception to throw in the
mailer action, managed by the mailer base class, that will stop the email
sending


Il giorno mer 19 feb 2020 alle ore 15:20 Mark Story <
notifications@github.com> ha scritto:

**Comment by berarma** [comment]
> i think that a beforeSend method could allow moving the entire email sending logic in the mailer itself, and i think that this should be the purpose of reusable mailer. Creating some public methods like prepare and restore are useless if i must call them, for example, in a controller. The main goal of this issue is to add a way to stop the email sending where the reusable mailer action was already called, for example, when an event is fired, and the who have fired the event have no visibility of what happens later. another options is a simple method or a specific exception to throw in the mailer action, managed by the mailer base class, that will stop the email sending

It's not useless since you can override the `prepare` method to do exactly what you want. It's more flexible to accomodate future needs too.

**Comment by berarma** [comment]
It could be done overriding the `execute` method too. You'd check the recipients before calling the method in the parent class.

**Comment by dereuromark** [comment]
In general, you shouldnt send emails from a controller, but use an async. process for this, usually done with a queuing system.
That has several advantages, re-sending on HTTP failure(s) and network issues as well as such special cases of aborting and CO.

For normal Mailer this seems a bit out of core scope IMO.
