### ISSUE TITLE
Smtp Transport says timeout when its an error response

### ISSUE THREAD

**Issue by reloxx13** [cakephp/cakephp#14228]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.2
* Platform and Target: apache,mysql

### What you did
Send an e-mail with SMTP

### What happened
SMTP Transport class said it timeouted, but it got a response with an error message.
It never stopped when it got the error back and waited till the timeout triggered.
There is no "\r\n" in the error response.

### What you expected to happen
Catch or log the correct error/response and just dont show "SMTP Timeout" which is incorrect.

Additional:
Spent some time to debug this just to find out its not a timeout, its a "Message size too large" Error.
in $response was
```
554 5.2.0 STOREDRV.Submission.Exception:MessageSubmissionExceededException.MapiExceptionMaxSubmissionExceeded; Failed to process message due to a permanent exception with message Cannot save changes made to an item to store.
```

https://github.com/cakephp/cakephp/blob/8b07fc218597156d4f2dacdcc9b8f6bfdee4924f/src/Mailer/Transport/SmtpTransport.php#L468

https://github.com/cakephp/cakephp/blob/8b07fc218597156d4f2dacdcc9b8f6bfdee4924f/src/Mailer/Transport/SmtpTransport.php#L447-L486

**Comment by markstory** [comment]
Smtp errors are supposed to have a trailingn\r\n according to the specs. Would it have helped to have the current buffer contents in the timeout exception?

**Comment by reloxx13** [comment]
> Smtp errors are supposed to have a trailingn\r\n according to the specs. 

I suppose you are right, but still MS :snowflake: office360 SMTP server did not do this. 

> Would it have helped to have the current buffer contents in the timeout exception?

Yes this would help. I had to output the buffer to get the correct error message.

**Comment by markstory** [comment]
@reloxx13 Would you be able to put together a pull request to add the buffer to exception message?
