### ISSUE TITLE
Mailer->viewBuilder()->setLayout() not pointing to the right directory

### ISSUE THREAD

**Issue by davidspeijer** [cakephp/cakephp#14238]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: CentOS 7

### What you did
```
$mailer = new Mailer('support');
$mailer
	->setTo('david@davidspeijer.nl')
	->setSubject(__('Reset Your Password'))
	->setEmailFormat('html')
	->viewBuilder()
		->setTemplate('forgotPassword');
		->setLayout('polarkrush');
	

$mailer->deliver('My message');
```

### What happened
The layout file layout.php can not be found or does not exist.

Confirm you have created the file: layout.php in one of the following paths:
/home/user/domains/domain.nl/public_html/portal/templates/layout.php

### What you expected to happen
That the layout is found and the email is send like mentioned in the docs
https://book.cakephp.org/4/en/core-libraries/email.html#sending-templated-emails

**Comment by michalfordonski** [comment]
I have a similar problem:
On MacOS, everything works, after moving the application to the Debian system there is an error that /templates/app_login.php was not found (app_login is set by setLayout) - for me it does not work on the web version, not in the mail. Maybe the setLayout function is wrong?

**Comment by davidspeijer** [comment]
I'm working on a OS 7 machine.

**Comment by michalfordonski** [comment]
On my MacOs (10.15.2) and CakePHP 4.0.1 is ok, but when i copy all files to webserver (Debian 9) show error with path /templates/app_login.php but files are in /templates/Layout/app_login.php, when i copy file to /templates/app_login.php error is still displaing.

**Comment by ADmad** [comment]
> files are in /templates/Layout/app_login.php

The files are supposed to be in `files are in /templates/layout/app_login.php`. It works for you on macos because it uses case insensitive file system while debian doesn't.

**Comment by ADmad** [comment]
@davidspeijer Make sure you aren't making the same mistake.

**Comment by michalfordonski** [comment]
Ok, when I changed /templates/Layout to /templates/layout is fine, but the CakePHP 3 to 4 upgrade plugin changes my element/Layout to element/layout and this confused me, which changed /templates/layout instead of element/layout is Layout. My mistake, thank you for help.

**Comment by davidspeijer** [comment]
The case sensitive thing was the issue :-).
