### ISSUE TITLE
SQL Server - Pagination Component drops alias when sorting

### ISSUE THREAD

**Issue by mikeswiz** [cakephp/cakephp#14233]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.8
* Platform and Target: Ubuntu 18.04, SQL Server

### What you did
Used pagination component helper to create sort links, sort by relational link.

### What happened
Query generated has: `order by (SELECT NULL)` instead of Aliased column. 

### What you expected to happen
Query generated would be : `order by Alias.column` 
When manually sorting (for testing) via `->sort('Alias.column');` works, I believe the Alias is being stripped out here: https://github.com/cakephp/cakephp/blob/master/src/Database/Dialect/SqlserverDialectTrait.php#L134

**Comment by markstory** [comment]
Does the original query have an order clause or not? That branch should only be reached if the query didn't have an order clause before.

**Comment by brentmdecker** [comment]
@markstory Here is an example query:

SELECT 
  Persons.Id AS [Persons__Id], 
  Persons.MemberNumber AS [Persons__MemberNumber], 
  Persons.IsDeleted AS [Persons__IsDeleted], 
  Persons.FirstName AS [Persons__FirstName], 
  Persons.LastName AS [Persons__LastName], 
  Persons.Email AS [Persons__Email], 
  Persons.PreferredPersonAddressId AS [Persons__PreferredPersonAddressId], 
  PrimaryAddresses.Id AS [PrimaryAddresses__Id], 
  PrimaryAddresses.PersonId AS [PrimaryAddresses__PersonId], 
  PrimaryAddresses.Line1 AS [PrimaryAddresses__Line1], 
  PrimaryAddresses.Line2 AS [PrimaryAddresses__Line2], 
  PrimaryAddresses.City AS [PrimaryAddresses__City], 
  PrimaryAddresses.StateId AS [PrimaryAddresses__StateId] 
FROM 
  Person Persons 
  LEFT JOIN PersonAddress PrimaryAddresses ON (
    PrimaryAddresses.IsPreferred = 1 
    AND Persons.Id = (PrimaryAddresses.PersonId)
  ) 
WHERE 
  (
    IsDeleted = 0 
    AND RecordTypeId = 1
  ) 
ORDER BY 
  (
    SELECT 
      NULL
  ) OFFSET 0 ROWS FETCH FIRST 100 ROWS ONLY

Example URL: `/admin/person/person?sort=PrimaryAddresses.Line1&direction=asc`

**Comment by markstory** [comment]
Ok. And you are confident that the query had an order clause applied to it before the pagination transform was applied?

**Comment by brentmdecker** [comment]
@markstory 

Whelp, it looks like the issue was on us, you can close the issue.

Inside of Paginate.php: `public function paginate($object, array $params = [], array $settings = [])` I noticed that the sorting option was removed here: `$options = $this->validateSort($object, $options);` (line 172).

That lead me to review ` /src/Datasource/Paginator.php (line 171) ` and the `sortWhitelist` option enabled an incorrect model name `PrimaryAddress` vs. `PrimaryAddresseses`.

Thank you for your time.
- Brent
