### ISSUE TITLE
4.x - Exceptions not testable using disableErrorHandlerMiddleware()

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#14237]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: PHP 7.2, apache 2.4, MySQL 5.7, 

### What you did

1. Create new project with `composer create-project --prefer-dist cakephp/app`
2. Create a DB with table "mytable"
3. Bake controller `bin/cake bake controller Mytable`
4. Throw an exception in controller

```
class MytableController extends AppController
{
     public function index()
    {
        throw new \Exception();
```

5. Check for the exception in the test created by `bake`

```
class MytableControllerTest extends TestCase
{
     public function testIndex(): void
    {
        $this->disableErrorHandlerMiddleware();
        $this->expectException(\Exception::class);
        $this->get('/mytable/index');
```
6. Run test

```
vendor/bin/phpunit tests/TestCase/Controller/MytableControllerTest.php --filter testIndex
```

### What happened

```
There was 1 failure:

1) App\Test\TestCase\Controller\MytableControllerTest::testIndex
Failed asserting that exception of type "Exception" is thrown.
```

### What you expected to happen

The test should not fail but detect the thrown exception.

Using `disableErrorHandlerMiddleware()` a exception was testable in Cake 3, but this isn't the case in CakePHP 4 (at the moment)?

**Comment by ADmad** [comment]
Sounds related to #14193 but that PR is a mess. Perhaps you can open a new PR :slightly_frowning_face:.

**Comment by Schlaefer** [comment]
From what I see it's not directly related to #14193 because the exception has no chance to bubble up to `IntegrationTestTrait`. 

Because `disableErrorHandlerMiddleware()` doesn't actually remove the `ErrorHandlerMiddleware` the exception is always caught there in `ErrorHandlerMiddleware::handleInternalError()`.
