### ISSUE TITLE
Controllers of same Model but under different prefixes don't load the same model

### ISSUE THREAD

**Issue by MolbioUnige** [cakephp/cakephp#14234]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8.

### What you did
I need to use the same model but called from controller under different prefixes, one of them doesn't load the correct model. It is not the first time I do this, but it's the first time I have this problem. To illustrate the problem here's what I did.

First controller under "Coordinator" prefix:
```
<?php
namespace StudentsAdmin\Controller\Coordinator;

use StudentsAdmin\Controller\AppController;

class ThesisCertificatesController extends AppController{

    public function view(){
        debug($this->ThesisCertificates);
        debug($this->modelClass);
    }
}
```

The second controller under the "Student" prefix:
```
<?php
namespace StudentsAdmin\Controller\Student;

use StudentsAdmin\Controller\AppController;

class ThesisCertificatesController extends AppController{

    public function view(){
        debug($this->ThesisCertificates);
        debug($this->modelClass);
    }
}

```

### What happened
First prefix "Coordinator" loads the correct model:

**/plugins/StudentsAdmin/src/Controller/Coordinator/ThesisCertificatesController.php (line 9)**
```
object(StudentsAdmin\Model\Table\ThesisCertificatesTable) {

	'registryAlias' => 'StudentsAdmin.ThesisCertificates',
	'table' => 'thesis_certificates',
	'alias' => 'ThesisCertificates',
	'entityClass' => 'StudentsAdmin\Model\Entity\ThesisCertificate',
	'associations' => [
		(int) 0 => 'students',
		(int) 1 => 'phdprograms',
		(int) 2 => 'faculties',
		(int) 3 => 'certificate',
		(int) 4 => 'principalsupervisor',
		(int) 5 => 'thesissupervisors'
	],
	'behaviors' => [
		(int) 0 => 'Timestamp'
	],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

}
```
**/plugins/StudentsAdmin/src/Controller/Coordinator/ThesisCertificatesController.php (line 10)**
`'StudentsAdmin.ThesisCertificates'`

Under the "Student" prefix, the controller doesn't find the model:

**/plugins/StudentsAdmin/src/Controller/Student/ThesisCertificatesController.php (line 9)**
```
object(Cake\ORM\Table) {

	'registryAlias' => 'ThesisCertificates',
	'table' => 'thesis_certificates',
	'alias' => 'ThesisCertificates',
	'entityClass' => 'Cake\ORM\Entity',
	'associations' => [],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

}
```

**/plugins/StudentsAdmin/src/Controller/Student/ThesisCertificatesController.php (line 10)**
`'StudentsAdmin.ThesisCertificates'`

### What you expected to happen
As I wrote before, it is not the first time that I am using prefix routing, never had any problem.

**Comment by markstory** [comment]
Could the model alias be referenced somewhere in your application without the plugin prefix? It seems like you have a generic model being included in the registry.

You could try flushing the table registry and then calling loadModel() on your controller to see if you're running into registry conflicts or if loadModel() is misbehaving.

**Comment by MolbioUnige** [comment]
@markstory Can you tell me where I should flush the table registry please?

**Comment by MolbioUnige** [comment]
Argh... sorry, I did load the model somewhere without specifying the plugin
