### ISSUE TITLE
Request RAW JSON not work in CakePHP 4

### ISSUE THREAD

**Issue by michalfordonski** [cakephp/cakephp#14248]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
Update CakePHP from 3 to 4

### What happened
Request RAW JSON not work ($this->request->getData() empty)

### What you expected to happen
Postman: [https://imgbbb.com/image/LofzIW](https://imgbbb.com/image/LofzIW)
Dump in Cake 4 part 1: [https://imgbbb.com/image/Lof7ev](https://imgbbb.com/image/Lof7ev)
Dump in Cake 4 part 2: [https://imgbbb.com/image/Lof1VU](https://imgbbb.com/image/Lof1VU)

**Comment by ADmad** [comment]
You need to use the `BodyParserMiddleware` and mentioned in the migration guide.
