### ISSUE TITLE
Get accessible properties in an Entity

### ISSUE THREAD

**Issue by mentisy** [cakephp/cakephp#14249]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: CakePHP 4.0.3
* Platform and Target: Irrelevant

I'm creating an import entity plugin where I want to fetch which fields are accessible in an entity, but it seems like there is no such method available.

The property `$_accessible` is protected, so can't use it directly. Is it ok if I create a PR creating a `getAccessible()` method in the `EntityTrait`? Should I rather get the database schema and loop through the fields using `isAccessible` to check for accessibility? Just seems like unnecessary effort when there's already a property readily available to be returned.

**Comment by dereuromark** [comment]
The problem with just exposting the property `$_accessible`:
They dont necessarily contain a bool result, they can also still contain the raw `*` etc.

So you need to loop over it anyway, using the internal `isAccessible()` wrapper method.
But it could be done inside a wrapper `getAccessible()` as a convenience method maybe.

**Comment by ADmad** [comment]
> I'm creating an import entity plugin where I want to fetch which fields are accessible in an entity

Why do you need to explicitly check the accessible properties for that? Just set all and the non accesible properties will be ignored.

**Comment by mentisy** [comment]
> > I'm creating an import entity plugin where I want to fetch which fields are accessible in an entity
> 
> Why do you need to explicitly check the accessible properties for that? Just set all and the non accesible properties will be ignored.

I'm going to import entities using a spreadsheet. I want to get all accessible fields for that entity, so I can assert which column in the spreadsheet contains which field property.

So if my entity has these properties: `name, age, address`
I could create a command prompt like this:
```
Which column contains the value of 'name'? (A/B/C)
[A] >
Which column contains the value of 'age'? (A/B/C)
[B] >
Which column contains the value of 'address'? (A/B/C)
[C] >
```

A/B/C refers to the column index in the spreadsheet.

**Comment by dereuromark** [comment]
I would recommend you to use an AccessibleTrait that you add to your entities, which exposes this functionality, or extending a BaseEntity here that has this functionality - or a wrapper from the outside doing this loop operation.
It seems too project-specific after all for a core addition.

**Comment by mentisy** [comment]
> I would recommend you to use an AccessibleTrait that you add to your entities, which exposes this functionality, or extending a BaseEntity here that has this functionality - or a wrapper from the outside doing this loop operation.

Yeah, that's what I did before creating this issue (created a trait). It's just that all entities that needs to import data, have to import (use) that trait. As it's a plugin, and I want to import any entities, I wanted to avoid that.

Exposing `$_accessible` via a new `getAccessible()` method would be reasonable though? Then developers can get the array (no modification or checks), and process it for their project-specific needs.

**Comment by dereuromark** [comment]
I opened a PR against 4.0, once this is merged you can make a backport to 3.x (probably 3.next).
