### ISSUE TITLE
Description of Table::buildRules is incorrect.

### ISSUE THREAD

**Issue by mtak3** [cakephp/cakephp#14250]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: 

### What you did

`Table::buildRules()` 
https://github.com/cakephp/cakephp/blob/4.0.3/src/ORM/Table.php#L2914
description is incorrect
https://github.com/cakephp/cakephp/blob/4.0.3/src/ORM/Table.php#L99-L100

`Behavior::buildRules()` is correct
https://github.com/cakephp/cakephp/blob/4.0.3/src/ORM/Behavior.php#L64-L66
https://github.com/cakephp/cakephp/blob/4.0.3/src/ORM/Behavior.php#L277
https://github.com/cakephp/cakephp/blob/4.0.3/src/Datasource/RulesAwareTrait.php#L99-L100

### What happened

https://github.com/cakephp/docs/blob/4.x/en/appendices/4-0-upgrade-guide.rst
```
 bin/cake upgrade rector --rules cakephp40 <path/to/app/src>
```
execute...

https://github.com/rectorphp/rector/blob/v0.6.14/config/set/cakephp/cakephp40.yaml#L98-L99
"Type declarations" is incorrect

**Comment by markstory** [comment]
Thank you for the great bug report. I've updated our documentation and opened a pull request to fix rector.
