### ISSUE TITLE
Making control template vars available to the container

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#14252]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Why not having all the template vars which are available to the control also available in the container?

I want to use the name in the container and I have to duplicate it in templateVars. Other vars are available but the name is not. Is there any reason to split them and passing just some of them to the container?

**Comment by markstory** [comment]
What are you referring to when you say container here?

**Comment by berarma** [comment]
> What are you referring to when you say container here?

The template `inputContainer` for example.

An example:
```
echo $this->Form->create(null, [
    'templates' => [
        'inputContainer' => '<div class="input {{type}} {{name}}{{required}}">{{content}}</div>',
    ],
]);
echo $this->Form->control("myfield", ['templateVars' => ['name' => "myfield"]]);
$this->Form->end();
```

Since `inputContainer` can't see the `name` value I have to define it for the container template.

**Comment by markstory** [comment]
Ah ok. I didn't understand the context as there are a few places we have templates and containers.

I don't see why we couldn't add more variables to the inputContainer rendering.
