### ISSUE TITLE
Validation of decimal numbers vs non-breaking space as a grouping separator

### ISSUE THREAD

**Issue by micdobro** [cakephp/cakephp#14254]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.2
* Platform and Target: LEMP

### What you did
Adding some serious multilang in the past days. In locale `pl_PL` the grouping separator is a "space", but in reality it's a non-breaking space aka `\xc2\xa0`. Validation code does a regular `str_replace()` - and that works as long as there is a value in the form actually containing the non-breaking space. Entering an amount like `1 200,99` is perfectly valid (in the human-input realm) - but obviously that cannot be validated, because the code tries to replace a non-breaking space. 

It works for editing - as my `Decimal` widget outputs via `Number::format()`. 

### What happened
Validation fails for amounts with space as a separator (entered via a form). 

### What you expected to happen
I would expect the validation to take into account the fact that non-breaking space can be also a space. 

In file `Validation/Validation.php` function `decimal()` we have today: 
```php
// account for localized floats.
        $locale = ini_get('intl.default_locale') ?: static::DEFAULT_LOCALE;
        
        $formatter = new NumberFormatter($locale, NumberFormatter::DECIMAL);
        $decimalPoint = $formatter->getSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
        $groupingSep = $formatter->getSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL);

        $check = str_replace([$groupingSep, $decimalPoint], ['', '.'], $check);
       
        return static::_check($check, $regex);
```

I propose: 
```php
// account for localized floats.
        $locale = ini_get('intl.default_locale') ?: static::DEFAULT_LOCALE;
        
        $formatter = new NumberFormatter($locale, NumberFormatter::DECIMAL);
        $decimalPoint = $formatter->getSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
        $groupingSep = $formatter->getSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL);
        
        // Some locales use non-br as separator - add a human space to the list
        if($groupingSep == "\xc2\xa0") {
            $check = str_replace([' ', $groupingSep, $decimalPoint], ['', '', '.'], $check);
        }
        else {
            $check = str_replace([$groupingSep, $decimalPoint], ['', '.'], $check);
        }
        
        
        return static::_check($check, $regex);
```

Tested locally - works. Again - could this open a "new hole" somewhere? IMHO this is a non-impact fix - but I might be of course mistaken. More eyes needed.

**Comment by markstory** [comment]
Do you know of other white space characters that intl might use, so we can account for those as well?

**Comment by micdobro** [comment]
@markstory sorry if I am behind the schedule - are we done with 3.x releases? (I see the 4.0.4 milestone)

As for other locales - yes - there is a narrow non-breaking space also - found it out by iterating over all `ICU` locales.

Here's the code: 

```php
$locales = ResourceBundle::getLocales('');

$seps = []; 
foreach($locales as $locale) {
 
    $formatter = new NumberFormatter($locale, NumberFormatter::DECIMAL);
    $decimalPoint = $formatter->getSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
    $groupingSep = $formatter->getSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL);
    
    $seps[$groupingSep] = "->{$groupingSep}<- " . bin2hex($groupingSep);

}

print_r($seps); 

```

And that produces: 

```php
Array
(
    [ ] => -> <- c2a0
    [,] => ->,<- 2c
    [٬] => ->٬<- d9ac
    [.] => ->.<- 2e
    [’] => ->’<- e28099
    [ ] => -> <- e280af
)

```

**Comment by markstory** [comment]
> sorry if I am behind the schedule - are we done with 3.x releases? (I see the 4.0.4 milestone)

No need to apologize. I set the milestone to 4.0 as the issue is present there as well.

> Should I prepare a PR that solves the problem for 3.x?

That would be great I can port it to 4.x then.

**Comment by micdobro** [comment]
I hope I based it off the proper branch. The snippet where I check all types of locales and their separators - I haven't looked into tests - but maybe this could land somewhere there? That's optional - I would expect that locales do not change that often.
