### ISSUE TITLE
syntax error, unexpected 'funtion' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by harichandana1810** [cakephp/cakephp#14262]
Unable to run the cakephp project in the website. I am getting an internal error

**Comment by ADmad** [comment]
Make sure you have the minimum PHP version required for the CakePHP version you are using.

**Comment by harichandana1810** [comment]
I have the php version 7.4.2. Is this enough for the CakePhp 2.x

**Comment by garas** [comment]
Syntax error is because you have typo in _funtion_
