### ISSUE TITLE
Tree Behaviour manual setting left end right (jQuery ordering)

### ISSUE THREAD

**Issue by davidspeijer** [cakephp/cakephp#14267]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3

### What you did
I have used the nestedSortable jQuery plugin (https://github.com/ilikenwf/nestedSortable) to order my categories with drag and drop. Every time a category is been ordered an Ajax request is going to the controller with a post of an array with the complete data of the categories. Everything is working as expected so for;

Array received in controller by Ajax post:
```
Array
(
    [0] => Array
        (
            [item_id] => 
            [parent_id] => 
            [depth] => 0
            [left] => 1
            [right] => 8
        )

    [1] => Array
        (
            [id] => 1
            [parent_id] => 
            [depth] => 0
            [left] => 2
            [right] => 3
        )

    [2] => Array
        (
            [id] => 4
            [parent_id] => 
            [depth] => 0
            [left] => 4
            [right] => 5
        )

    [3] => Array
        (
            [id] => 2
            [parent_id] => 
            [depth] => 0
            [left] => 6
            [right] => 7
        )
)
```

In my controller I have the following function to process:
```
public function reorder() {
    $list = isset($_POST['_list']) ? json_decode($_POST['_list'], true) : null;
    foreach ($list as $item) {
        if (!empty($item['id'])) {

            $category = $this->Categories->get($item['id']);

            if (!empty($category)) {
                empty($item['parent_id']) ? $category->parent_id = null : $category->parent_id = $item['parent_id'] ;
                $category->lft = $item['left'];
                $category->rght = $item['right'];

                $this->Categories->save($category);
            }
        }
    }
}
```

### What happened
When I debug the categories before saving the lft and rght are set correctly, however after saving the lft and rght contain completely different values.

I assume that since TreeBehavior is implemented the save function is doing some checks and resetting lft and rght to other values? Anyway to skip this?

### What you expected to happen
Manual edit my the lft rght values.

**Comment by dereuromark** [comment]
I think it is an anti-pattern to use a manual foreign lft/right value here when saving.
Instead, make sure to pass the expected parent_id and position, and make the TreeBehavior adjust the values internally.
This keeps you from losing data.

**Comment by dereuromark** [comment]
Closing in favor of community question @ https://stackoverflow.com/questions/60151742/cakephp-4-tree-behaviour-manual-setting-left-end-right-jquery-ordering

**Comment by saeideng** [comment]
dont set left/right manually 
one of ways  is using the `moveUp()`/`moveDown()`
