### ISSUE TITLE
Which is correct, App.mergeFilesAsObjects or App.uploadedFilesAsObjects ?

### ISSUE THREAD

**Issue by mtak3** [cakephp/cakephp#14278]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: 

### What you did
Which is correct?

https://github.com/cakephp/cakephp/blob/4.0.3/src/Http/ServerRequestFactory.php#L81
```
            'mergeFilesAsObjects' => Configure::read('App.uploadedFilesAsObjects', true),
```

https://github.com/cakephp/docs/blame/4.x/en/appendices/4-0-migration-guide.rst#L224
```
* The default value of ``App.mergeFilesAsObjects`` is now ``true``. If your
```

**Comment by ADmad** [comment]
When in doubt follow the code instead of the doc :slightly_smiling_face:
