### ISSUE TITLE
CakePHP 4.0.3 CounterCache on null association

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp#14276]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: N/A

### What you did
UsersTable has Behavior CounterCache with ['Tenants' => ['user_count']]. Save a user with a tenant_id = null

### What happened
Exception is thrown `Expression is missing operator (IS, IS NOT) with null value.`

### What you expected to happen
No exception to be thrown.

**Comment by markstory** [comment]
Pull request open now.
