### ISSUE TITLE
CakePHP 4.0.3: Asserting Session Variable after Request in Test Case clears $_SESSION

### ISSUE THREAD

**Issue by danellos** [cakephp/cakephp#14270]
Let me know if you need any more info from me. Possible I am missing something here, but this worked before.

___

This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: Apache 2.4, Ubuntu 18.04, Microsoft SQL Server 2017

### What you did
We're trying to upgrade a Cake 3.8 application to Cake 4.0.x. Some of our test cases do the following:
```
    public function testSomePostRequest()
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();
       
        // form data
        $data = [
            'FormItem1' => 'something'
        ];
       
        // this action will proceed normally, and set a session key in 'sessionKey'
        $this->post('some-plugin/some-controller/some-action', $data);

        /* We want to assert now that certain session variables were set */
         
        // this code works (but is not desired)
        $this->assertArrayHasKey($_SESSION['sessionKey']);
        $this->assertNotNull($_SESSION['sessionKey']);

        // this code worked in 3.8, but stopped working in 4.0.x
        $value = $this->_requestSession->read('sessionKey'); // alternatively, was also possible to use $this->_controller->getRequest()->getSession(), but that returns null also
        $this->assertNotNull($value); // causes error

        $this->assertRedirect('/redirect/somehwere/else');
    }
```

### What happened
$_SESSION is getting cleared when $this->_requestSession->read() or $this->_controller->getRequest()->getSession()->read() is being called.

When I dug a little deeper, for some reason, $this->started() in Session.php is returning false, which is causing $this->start() to be executed under the first IF condition in ->read(). 

### What you expected to happen
$_SESSION should contain the session variables that were set by the controller POST action, as in Cake 3.8.

**Comment by markstory** [comment]
Do the assertSession() methods work? https://book.cakephp.org/4/en/development/testing.html#testing-flash-messages has an example usage of assertSession().

**Comment by danellos** [comment]
The assertSession() method works if I know what value to expect in the session at a given key, so we could use this for many of our cases for sure. However, for some of our cases, we have an assertion that just checks that something was set, because it could be a random value like a UUID generated from the database during testing. I might be missing something here, but I am not sure how assertSession() can be used to just check the existence of something not null in the session key.

Asserting that $_SESSION['keyName'] is set and not null is a workaround for now, but it isn't clean and feels like a hack. 

Here is another snippet:
```
        // assume 'testValue' is a non-random value in 'testKey'
        $this->assertSession('testValue', 'testKey'); // passes, no errors

        // now assume that 'testValue' is random (such as a UUID)
        $value = $_SESSION['testKey'];
        $this->assertNotNull($value); // passes, no errors
        $value = $this->_requestSession->read('testKey');
        $this->assertNotNull($value); // fails, $_SESSION is empty now
```

I've noticed that internally assertSession() also uses _requestSession and passes it to a SessionEquals constraint. It seems the first check in _requestSession->read() method is causing $_SESSION to clear.

**Comment by markstory** [comment]
> I might be missing something here, but I am not sure how assertSession() can be used to just check the existence of something not null in the session key.

You're right that `assertSession()` is not a good fit for this scenario. We could add an `assertSessionHasKey()` or `assertSessionNotNull()` method though to make that possible though.

I'll see if I can reproduce the `_requestSession` erasing the `$_SESSION` on use as that is not how it should be working in a test scenario.

**Comment by markstory** [comment]
I was looking into building a new assertion for `assertSessionHasKey` and found an interesting comment

```
        // Server::run calls Session::close at the end of the request.
        // Which means, that we cannot use Session object here to access the session data.
        // Call to Session::read will start new session (and will erase the data).
```

Which matches your results. It would seem like the simulated request closes the session which results in the next read restarting and wiping the session.

We might be able to use a stubbed session that doesn't open/close the session storage, but that will likely break applications that have tests that reach into the underlying session storage, so I'm hesitant to make a change like that.

Using the `$_SESSION` variable seems like your best option in the short term, unless other changes can be made to session handling that won't break existing applications.

**Comment by dereuromark** [comment]
@danellos See https://github.com/dereuromark/cakephp-test-helper/commit/0a8eaf56b02d39c25293ac51d9b1591050a437ed#diff-74bfea6f6fb4add7746dde591fe332efR76-R83 for a project/plugin level fix

And I opened a more permanent core solution as PR now as well.
Closing then as to continue the discussion there.
