### ISSUE TITLE
IntegrationTestTrait gives SecurityToken error if enableCsrfToken () and enableSecurityToken () are both enabled.

### ISSUE THREAD

**Issue by mtak3** [cakephp/cakephp#14273]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: 

### What you did

`Possibly related to Cake\Http\Exception\BadRequestException: "Invalid form protection debug token." `

ex.
```
...
use IntegrationTestTrait;

public function testPost()
{
  $this->enableCsrfToken();
  $this->enableSecurityToken();

  $this->post('/path/to', [...]);
}
```

### What happened

https://github.com/cakephp/cakephp/blob/3.8.9/src/Controller/Component/SecurityComponent.php#L420
```
        unset($check['_Token'], $check['_csrfToken']);
```

https://github.com/cakephp/cakephp/blob/4.0.3/src/Form/FormProtector.php#L297
```
        unset($formData['_Token']);
```

The hash value is different because `_csrfToken` is included in POST data by `$this-> enableCsrfToken();`.

**Comment by mtak3** [comment]
Do not `unset ()` `_csrfToken`.
Change the processing order?
https://github.com/cakephp/cakephp/blob/4.0.3/src/TestSuite/IntegrationTestTrait.php#L647-L684

**Comment by mtak3** [comment]
sorry. The problem was my code.

https://github.com/cakephp/cakephp/blob/4.0.3/src/Http/Middleware/CsrfProtectionMiddleware.php#L151-L166

`_csrfToken` not include POST data.

`_csrfToken` also contains URL information.
There was a mistake in routing
config/routes.php
```
...
  $routes->connect('/:controller/:action');
...
```

Unit Test
```
  $this->post('/articles/edit/1', [...]);
```

CakePHP3 was OK.

CakePHP4

config/routes.php
```
...
  $routes->fallbacks(DashedRoute::class);
...
```
or

Unit Test
```
  $this->post('/Articles/edit/1', [...]);
```

`_csrfToken` problem is gone.

**Comment by righel** [comment]
I had a similar issue, for future people that may hit this issue:
my `_Token` was being was set like this:
```
[_Token] => Array
(
    [fields] => 3781d8b340e01f1622930402a99d9d8d0a80bcaf%3A
    [unlocked] => 
    [debug] => FormProtector debug data would be added here
)
```
Since my `debug` setting was not set, this check was failing:
https://github.com/cakephp/cakephp/blob/551239eeadb152982ac3ae2927600c83989338f2/src/Controller/Component/SecurityComponent.php#L272-L274

Solved it by setting `debug` to `true`.

My integration test:
```php
<?php

declare(strict_types=1);

namespace App\Test\TestCase\Controller;

use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

class UsersControllerTest extends TestCase
{
    use IntegrationTestTrait;

    public function testLogin(): void
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        $this->post('/users/login', [
            'username' => 'admin',
            'password' => 'Password1234',
        ]);

        $this->assertResponseCode(302);
    }
}
```
