### ISSUE TITLE
CakePHP 4.0.3 - Relax $this->Text->autoParagraph(h($model->field)); to accept NULL.

### ISSUE THREAD

**Issue by tomrwaller** [cakephp/cakephp#14271]
This is a:

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3.

In my view.php I have $this->Text->autoParagraph(h($model->field)); as per the baked view. It should show the field value.

If the field is NULL, an error is raised:

> Argument 1 passed to Cake\View\Helper\TextHelper::autoParagraph() must be of the type string, null given

It would be handy if this function handled NULL values gracefully. I'm currently working around this by using:

$this->Text->autoParagraph(h($model->field ?? ''))

**Comment by markstory** [comment]
Sounds reasonable, could you open a pull request with that change?
