### ISSUE TITLE
EagerLoader with leftJoin loading optional association exception when there's no matching keys

### ISSUE THREAD

**Issue by victoreassis** [cakephp/cakephp#14281]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: Any

### What you did
Let's say I have TableA related to TableB, as such:
TableA:
```php
        $this->belongsTo('TableB', [
            'foreignKey' => 'table_b_id',
        ]);
```
TableB:
```php
        $this->hasMany('TableA', [
            'foreignKey' => 'table_b_id',
        ]);
```
Normally I would query then with innerJoin, but I then need to perform a leftJoin because that relation is optional and I want to list both for some reason. Then I build a query like so:
```php
        $query = $this->TableA->find()
            ->contain([
                'TableB',
            ])
            ->leftJoinWith('TableB');
```

### What happened
It works fine if there's at least one relation between the two, like, if I have 2 records and one of then have the relation, it works as intended, but if both doesn't have one, it will blow following exception:

> "Unable to load `TableB` association. Ensure foreign key in `TableA` is selected."

### What you expected to happen
I expected to work fine even if there's no relation on the result set.

I looked into the EagerLoader class and it appear the issue comes from the _groupKeys that causes a if statement on loadExternal method to not match in this case.
https://github.com/cakephp/cakephp/blob/master/src/ORM/EagerLoader.php#L666
```php
               if (empty($collected[$path][$alias])) {
                    continue;
                }
```
Will not be true because the first condition will throw the exception because the $collected array is empty, on _groupKeys the $keys returned is an empty array in this because of this condition:
https://github.com/cakephp/cakephp/blob/master/src/ORM/EagerLoader.php#L834
```php
                if ($parts[2] === true && !isset($result[$parts[1][0]])) {
                    continue;
                }
```
Removing this condition and inserting one inside the second one in _groupKeys appear to fix the issue and return the expected result to the loadExternal method.
```php
                if ($parts[2] === true) {
                    if (empty($keys[$nestKey][$parts[0]]) && !isset($result[$parts[1][0]])) {
                        $keys[$nestKey][$parts[0]] = [];
                    } else {
                        $value = $result[$parts[1][0]];
                        $keys[$nestKey][$parts[0]][$value] = $value;
                    }
                    continue;
                }
```
I would be happy to provide a PR for this if my reasoning is correct.

**Comment by markstory** [comment]
A pull request with a test for this scenario would be great.

**Comment by markstory** [comment]
If your association is nullablenis there a reason you haven't configured the association to use left joins by default?

**Comment by victoreassis** [comment]
Until now the system would make 2 queries and list then in different places because it relates to another table, but I need to make a unified list that shows the nullable association when needed. Maybe I could just change the association's join, but I don't know how much it will affect other things as the system is not that well tested.

**Comment by victoreassis** [comment]
I will work on the PR.
