### ISSUE TITLE
getOriginal and combined operators

### ISSUE THREAD

**Issue by DrMickArtisan** [cakephp/cakephp#14297]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.7.9
* Platform and Target:php 7.2.27, ubuntu 18.04 

### What you did
I just modify a field of an entity by 
$aventurier->combat += 1;
And thus, while trying to get the original value by
$combat = $aventurier->getOriginal('combat');
I always got a 0.

### What happened
getOriginal doesn't return the original value, as expected.

Dumping the the entity, I see : 
$aventurier->dirty = [dirty]: array:2 [
    "combat" => true
    "experience" => true
  ]
and
$aventurier->original = [dirty]: array:1 [
    "experience" => 10
  ]
no mention of combat value in original property.

### What you expected to happen
the original combat value in entity property 'original'

### solution
Everything works fine if I modify the value by using : 
$aventurier->combat = $aventurier->combat  + 1;

**Comment by DrMickArtisan** [comment]
Ha, it seems that the issue is not present with php 7.3.14

**Comment by markstory** [comment]
Closing as this is fixed by using a newe PHP version that calls magic methods better.
