### ISSUE TITLE
CAKEPHP 4.X Model prefix

### ISSUE THREAD

**Issue by purnarao** [cakephp/cakephp#14295]
With few blogs inspiration, we have started upgrading our existing project from Cakephp-2X version to Cakephp-4X. We started it from scratch. Now we have been stuck with few things -

1. How to give prefix to a particular table in the model and also on fly in the controller?
2. In Cakephp-4X, we can list out virtual fields in Entity it seems, But how to give virtual fields on fly in the controller like in Cake2X?
3. In Cake2X, we can also give conditions based on the virtual fields for model find method. But, how is it possible in Cake4.

Appreciate your help.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
