### ISSUE TITLE
CakePHP 4.03 installed with improper permissions on tmp SQLSTATE[HY000] [14] unable to open database file

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#14307]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3

### What you did

1. Installed CakePHP using `composer create-project --prefer-dist cakephp/app:4.* myapp` and said Yes to Set Folder Permissions ? (Default to Y).

2. After configuring a virtual host in Apache/2.4.29 on Ubuntu 18.04 LTS I browsed to the localhost. 

### What happened

Encountered error: `SQLSTATE[HY000] [14] unable to open database file`

```
PDO->__construct
CORE/src/Database/Driver.php:102
Cake\Database\Driver->_connect
CORE/src/Database/Driver/Sqlite.php:79
Cake\Database\Driver\Sqlite->connect
CORE/src/Database/Schema/BaseSchema.php:47
Cake\Database\Schema\BaseSchema->__construct
CORE/src/Database/Dialect/SqliteDialectTrait.php:173
Cake\Database\Driver\Sqlite->schemaDialect
CORE/src/Database/Schema/Collection.php:53
Cake\Database\Schema\Collection->__construct
CORE/src/Database/Connection.php:391
Cake\Database\Connection->getSchemaCollection
ROOT/vendor/cakephp/debug_kit/src/Model/Table/LazyTableTrait.php:44
DebugKit\Model\Table\RequestsTable->ensureTables
ROOT/vendor/cakephp/debug_kit/src/Model/Table/RequestsTable.php:53
DebugKit\Model\Table\RequestsTable->initialize
CORE/src/ORM/Table.php:310
Cake\ORM\Table->__construct
CORE/src/ORM/Locator/TableLocator.php:263
Cake\ORM\Locator\TableLocator->_create
CORE/src/ORM/Locator/TableLocator.php:217
Cake\ORM\Locator\TableLocator->get
ROOT/vendor/cakephp/debug_kit/src/ToolbarService.php:232
DebugKit\ToolbarService->saveData
ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php:66
DebugKit\Middleware\DebugKitMiddleware->process
CORE/src/Http/Runner.php:73
Cake\Http\Runner->handle
CORE/src/Http/Runner.php:58
Cake\Http\Runner->run
CORE/src/Http/Server.php:90
Cake\Http\Server->run
ROOT/webroot/index.php:40
```

### What you expected to happen

I expect: 

1. At least a more descriptive error to aid me in solving this. `SQLSTATE[HY000] [14] unable to open database file` makes be believe the problem is with MySQL. The problem is that I have the following folder permissions on `tmp`: 

`drwxr-xrwx  5 chris www-data   4096 Jan 18 21:41 tmp/`

And therefore, `tmp/debug_kit.sqlite` cannot be created since www-data for some reason didn't get write permissions. An error such as `Cake was unable to create the SQLITE database at  tmp/debug_kit.sqlite, please check your fiile/directory permissions` would be much better for someone like me who is just isn't that sharp.

I eventually figured this out after reading the stacktrace, but man did I spend extra time.

2. I expect the installer to create directories with proper permissions.

After setting the directory to `777` I was greeted with the CakePHP install page. My `logs` directory is not writable either. Anything CakePHP can do to get users to this page right from the start and indicate idiot-proof steps to get them going is a win for the project.

**Comment by ADmad** [comment]
The installer script already sets permission for `tmp` and `logs` folder to `777` when you select `Y` for `Set Folder Permissions ?`. I wonder why that did not happen for you.

If you can debug and figure out the cause we can update the [installer script](https://github.com/cakephp/app/blob/master/src/Console/Installer.php).

**Comment by ADmad** [comment]
I tested on Linux Mint 19 which is based off Ubuntu 18.04 and there were no issues with folder permission setting.

**Comment by cnizzardini** [comment]
Well that is unfortunate that you cannot reproduce. I think in the event that you cannot reproduce, you can at least recreate by deleting your sqlite and setting folder permissions to match mine. From there, you can at least hit expectation 1 with a better error message.

**Comment by cnizzardini** [comment]
Cool, this looks like it will say SQLite at least in the error message.
