### ISSUE TITLE
Can not parse env value with double quote at end of string

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14302]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: Windows, Nginx, PHP 7.3

### What you did
Parse .env with below value
```
export mykey="myvalue:\"my description\""
```

### What happened
Parsed value is `myvalue:"my description\`

### What you expected to happen
Parsed value must be `myvalue:"my description"`

**Comment by josegonzalez** [comment]
That might be a bug in `m1\Env` - which we use for `.env` parsing - but it seems that [should be supported](https://github.com/m1/env#strings)?

Worth opening the issue upstream though, and at least filing a PR with the failing test.

**Comment by josegonzalez** [comment]
I see you already filed something related to this [here](https://github.com/m1/Env/issues/13). Again, worth opening upstream and filing a PR with a failing test for that one too (if they aren't related).

**Comment by mcsknp** [comment]
My PR was merged. When it will be released?

**Comment by markstory** [comment]
@mcsknp We don't know. We don't maintain that project. You would have to talk to the maintainers of m1/Env.

I am closing this as there isn't anything we can to fix this and the upstream project has fixed the issue.
