### ISSUE TITLE
HasMany::_saveTarget attempts to set original to failed target entity

### ISSUE THREAD

**Issue by dorxy** [cakephp/cakephp#14303]
The flow in `Cake\ORM\Association\HasMany::_saveTarget` seems to indicate that when one of the target entities fails to save because of any errors, the parent entity's property is reverted to the original set of entities, with the appropriate errors.

The line at which this happens seems to be incorrect, as it uses `$entity->set($this->getProperty(), $original)` instead of `$parentEntity->set($this->getProperty(), $original)`, see https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/HasMany.php#L235

E.g. Users hasMany Articles, save a user A with a new set of articles X, one of the articles Y has an error because of rules, this line will attempt to set the set of articles X (with the errors of Y set to the original Y found X) on the article Y instead of the user A.

**Comment by victoreassis** [comment]
Actually each article that has errors is set with a property `articles` that contains all associated articles.
I made a test case for this and it appears there's no need to have `$entity->set($this->getProperty(), $original)` when `$original[$k]->setErrors($entity->getErrors());` is changing the original object and is already working properly. Then this line only affects the entity of the method itself inside that particular foreach as each entity is cloned.
Can I make a PR for this?

**Comment by dereuromark** [comment]
A PR for docs? Sure.

**Comment by victoreassis** [comment]
To remove this line and add the test case to cover it. Shouldn't the method also update the $_invalid content of the original entity?

**Comment by markstory** [comment]
A test case and fix would be great!
