### ISSUE TITLE
Cache query does not work when the fields of the select do not have an alias

### ISSUE THREAD

**Issue by bouro** [cakephp/cakephp#14300]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: PHP 7.4.1 /  Ubuntu 18.04.3

### What you did
I'm trying to cache the result of the query

```
public function index(): void
{
	$query = $this->Videos->find()
		->select(['id', 'title', 'slug', 'thumbs', 'duration'])
		->where(['active' => true])
		->orderDesc('created')
		->cache(function (Query $query) {
			$key = serialize($query->clause('select'));
			$key .= serialize($query->clause('where'));
			$key .= serialize($query->clause('order'));

			$this->log(implode(',', $query->clause('select')));

			return 'videos-index' . '-' . md5($key);
		}, 'videos');

	$videos = $this->paginate($query);

	$this->set(compact('videos'));
	$this->viewBuilder()->setOption('serialize', 'videos');
}
```

### What happened
At each call, the cache is recreated and a request is made to the database.

### What you expected to happen
The result must be retrieved from the cache directly without going through the database.

### Temporary solution
I did several tests and I discovered that the problem came from the `cache()` method and more precisely from the line `$key = serialize($query->clause('select'));`

When I remove this line the cache works as it should

So I tried to see what `implode(',', $query->clause('select'))` returned and I put a log, here is the result:
```
2020-02-18 18:45:30 Error: id,title,slug,thumbs,duration
2020-02-18 18:45:30 Error: Videos.id,Videos.title,Videos.slug,Videos.thumbs,Videos.duration
```
For each request the log returns two lines, one without `alias` and the second without `alias` 

I then added `alias` to all the `fields` in the `select` and the cache worked

I think the cache should work without putting an alias on the fields.

**Comment by markstory** [comment]
Couldn't this be solved in your application code by ensuring the generated key is correct for both scenarios? CakePHP simply uses the provided cache keys. How do you propose that we solve this problem in the framework?

**Comment by bouro** [comment]
In order for the key to be generated correctly in both cases in the application, there are two solutions that can be applied:

Add an `alias` in the `select` directly

```
public function index(): void
{
	$query = $this->Videos->find()
		->select(['Videos.id', 'Videos.title', 'Videos.slug', 'Videos.thumbs', 'Videos.duration']);
	...
}
```

Create a `$fields` variable and pass it to the `cache()` method and use it instead of `$query->clause('select')`

```
public function index(): void
{
	$fields = ['id', 'title', 'slug', 'thumbs', 'duration'];
	
	$query = $this->Videos->find()
		->select($fields)
		...
		->cache(function (Query $query) use ($fields) {
			$key = serialize($fields);
			$key .= serialize($query->clause('where'));
			$key .= serialize($query->clause('order'));

			return 'videos-index' . '-' . md5($key);
		}, 'videos');

	...
}
```

If we want to manage this directly from the framework, the call to `$query->clause('select')` in `cache()` method, must always returns the fields with alias, or add some sort of option `withAlias` for example

**Comment by markstory** [comment]
> If we want to manage this directly from the framework, the call to $query->clause('select') in cache() method, must always returns the fields with alias

I am not sure how that would be implemented as aliases aren't resolved/added until just before the query is executed. The reason we defer that work is fields can change multiple times during a query's life. I am also not certain that the overhead is justified when the framework doesn't even know that the select clause is going to be used in the cache key.

Your solution of always including aliases when creating queries is the simplest solution that doesn't incur any additional overhead. You can also use the aliasField() method in your cache closure to ensure that fields have aliases.

**Comment by webme** [comment]
OK fine.
Thank you for your reply.
Problem solved for me.
