### ISSUE TITLE
Tree Behaviour not working with underscored model names.

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/cakephp#14311]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: apache2 mysql

### What you did
Create supplier_types (id, parent_id, lft, rght, name) in database. Use bake all. The tree behaviour is automaticly added. 

### What happened
When trying to add data, it gives errors everywhere. With field parent_id, ... the tree behaviour is not working as expected.

### What you expected to happen
When renaming the model to a non underscored name eg. suppliertypes. Everything is working correctly.

**Comment by ADmad** [comment]
Model names are supposed to be CamelCased. So if you table name is `supplier_types` it's model name would be `SupplierTypes` (with table class `SupplierTypesTable`). TreeBehavior can be used perfectly fine with such model names.

**Comment by ADmad** [comment]
Please show the table class generated for you using `bake`.

**Comment by tgoeminne** [comment]
Uh, ok, I just checked this again and it appears another problem with my cache. Ever since I updated to version 3.8, I am having problems with the cache system. It somehow does not update the cache anymore even when debug is set to true.
Am I missing some updates to the cache or settings that need to be changed?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
