### ISSUE TITLE
compatibility issue of CAke PHP 3.2 while moving server

### ISSUE THREAD

**Issue by Aparajita591** [cakephp/cakephp#14333]
Hi, I am facing an issues while migrating a cakephp project to a php 7.2 version server. Earlier my project was on a server with PHP 5.x and now I am moving my project to a server which has PHP version 7.2. My cakephp version is 3.2
The errors that I am getting are -
![image](https://user-images.githubusercontent.com/55868901/75541091-4b3fc300-5a43-11ea-8ef6-d733492a1b60.png)

**Comment by ADmad** [comment]
CakePHP 3.2 is not compatible with PHP 7.2. You need to either upgrade to latest 3.8 release or whatever the minimum 3.x release is which supports PHP 7.2.
