### ISSUE TITLE
Use psalm templates/generics for collections 

### ISSUE THREAD

**Issue by vladyslavstartsev** [cakephp/cakephp#14336]
This is a:

* [x] enhancement

* CakePHP Version: any (collections).

Since you have already used psalm and it's templates feature, I would like to suggest you to type all the collections library

**Comment by ADmad** [comment]
Would you like to make a PR adding the required tags?

**Comment by vladyslavstartsev** [comment]
@ADmad yes, but not promising. So it's better to do this by your team

**Comment by othercorey** [comment]
Closing this due to lack of contribution/PR.
