### ISSUE TITLE
Strange behavior when testing controller action that updates boolean fields

### ISSUE THREAD

**Issue by BenoKop** [cakephp/cakephp#14358]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.9
* Platform and Target: Nginx, MySQL.

### What you did
Hi all,

I'm currently writing the tests of my controllers actions and I found a strange behavior when saving an entity with boolean fields.

This is my controller action that consists to toggle the active/inactive state of my user:

```
    public function toggleActive($id = null)
    {
        $utilisateur = $this->Utilisateurs->get($id);

        if($this->request->is(['patch', 'post', 'put'])){
            $utilisateur->active = !$utilisateur->active; // Makes the tests crash
            if(!$utilisateur->active ){
                $utilisateur->duree_activation = -1;
                $utilisateur->date_desactivation = Time::now();
                $utilisateur->date_suspension = Time::now();
            }else{
                $utilisateur->duree_activation = 10;
                $utilisateur->date_activation = Time::now();
            }
            if($utilisateur = $this->Utilisateurs->save($utilisateur)){
                $this->Flash->success($utilisateur->active ? __('L\'utilisateur a bien été activé.') : __('L\'utilisateur a bien été désactivé.'));

                return $this->redirect(['action' => 'index', '?' => $this->request->getQueryParams()]);
            }
            $this->Flash->error(__('Une erreur est survenue durant la modification de l\'utilisateur.'));
        }

        $this->set(compact('utilisateur'));
        $this->set('_serialize', ['utilisateur']);
    }
```

Code of my test:
```
    public function testPostToggleActiveWithAuth()
    {
        // Définit des données de session
        $this->session([
            'Auth' => [
                'User' => [
                    'id' => 1,
                    'login' => 'USERTEST',
                    'role' => 'admin',
                ]
            ]
        ]);

        // Security
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        // Activate
        $this->post('/utilisateurs/toggle-active/2');
        $this->assertResponseSuccess();
        $this->assertResponseCode(302);
        $this->assertSession(__('L\'utilisateur a bien été activé.'), 'Flash.flash.0.message');
  }
```

### What happened
When I run my test I get the following error:

```
Possibly related to InvalidArgumentException: "Cannot convert value of type `boolean` to integer"
#0 /var/www/deckgenius/lucie/vendor/cakephp/cakephp/src/Database/Type/IntegerType.php(84): Cake\Database\Type\IntegerType->checkNumeric(true)
```

### What you expected to happen
Temporarily, I found a workaround thats consists to replace this line in my controller:

```
$utilisateur->active = !$utilisateur->active;
REPLACED BY
$utilisateur->active = $utilisateur->active ? 0 : 1;
```

It is like that going through phpunit expects the boolean fields to be set explicity as integers and not booleans. When it goes through the type checking in the saving process, it just crashes.

Thanks for the support.

**Comment by ADmad** [comment]
Have you used `tinyint(1)` for you `active` field in the db table?

**Comment by BenoKop** [comment]
Yes I have, and this is this line concerning the field in the fixtures:

`'active' => ['type' => 'boolean', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],`

**Comment by ADmad** [comment]
Hmm.. I am not sure why `IntegerType` is being used for the field instead of `BooleanType`.  Recheck your fixture and ensure your test is using that fixture.

**Comment by BenoKop** [comment]
Alright, I'm migrating an existing app and i'm mixing the the old fields with some new ones.
An old field is used as a bool in the code but was set as standard int in the data structure...
I upgraded it and it is working now...

Sorry for the bother and thanks for the fast reply, I close it here.
