### ISSUE TITLE
ConsoleInput->read() throws Exception at stdin end

### ISSUE THREAD

**Issue by binsky08** [cakephp/cakephp#14350]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.4
* Platform and Target: Ubuntu 18.04.4, nginx/1.14.0

### What you did
I run something like `cat file.txt | cake command`
Inside the command it's about the following code:
```
$ConsoleInput = new ConsoleInput();
while ($ConsoleInput->dataAvailable()) {
    $result = $ConsoleInput->read();
    if ($result !== false) {
        $this->myMethod($result)
    }
}
```

### What happened
At the end of the input stream (after the last row of my file) I get an exception from the read method:
```
Exception: strlen() expects parameter 1 to be string, boolean given
In [/opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/ConsoleInput.php, line 64]

2020-03-10 17:10:19 Error: [TypeError] strlen() expects parameter 1 to be string, boolean given in /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/ConsoleInput.php on line 64                                                                                                               
Stack Trace:                                                                                                                                       
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/ConsoleInput.php:64                                                                     
- /opt/openitc/frontend/src/Lib/MyCustomLib.php:581                                                                                      
- /opt/openitc/frontend/src/Command/MyCommand.php:100                                                                                           
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/BaseCommand.php:175                                                                     
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:336                                                                   
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171                                                                   
- /opt/openitc/frontend/bin/cake.php:12
```

### What you expected to happen
I expect that there will be no more output and no errors.

**Comment by victoreassis** [comment]
It's indeed broken as ```readline()``` and ```fgets()``` returns false on EOF and the method is set to return a string.

Can the method signature be changed as the following and return null when these methods return false?
```php
public function read(): ?string
```
Then this can help fixing this issue and make it easier to check against EOF. As of today the ```fgets``` call is cast as string and returns a empty string when false is the returned, which doesn't say much about anything, as it is a possible line content.

Can I make a PR for this with the proposed changes?

**Comment by ADmad** [comment]
@victoreassis Sounds good.
