### ISSUE TITLE
SQLite 3: Your database does not have any tables.

### ISSUE THREAD

**Issue by ikkysleepy** [cakephp/cakephp#14360]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
 Platform and Target: Apache2, SQLite 3

### What you did
CLI: Tried to run ./cake bake model users

First Bug: Cake is not recognizing **app_local.php** for config changes, so I have modify app.php.
Second Bug: Adding these line makes the installer say "CakePHP is able to connect to the database."

```
            'driver' => \Cake\Database\Driver\Sqlite::class,
            'database' => '/var/www/notes/webroot/database/fake_non_existing00156445.db',
```

### What happened
Third Bug: running that cake bake command results in " Your database does not have any tables."

```
Exception: Your database does not have any tables.
In [/media/notes/notes_www/vendor/cakephp/bake/src/Utility/TableScanner.php, line 68]

2020-03-12 23:00:21 Error: [RuntimeException] Your database does not have any tables. in /media/notes/notes_www/vendor/cakephp/bake/src/Utility/TableScanner.php on line 68
Stack Trace:
- /media/notes/notes_www/vendor/cakephp/bake/src/Utility/TableScanner.php:82
- /media/notes/notes_www/vendor/cakephp/bake/src/Command/ModelCommand.php:1076
- /media/notes/notes_www/vendor/cakephp/bake/src/Command/ModelCommand.php:74
- /media/notes/notes_www/vendor/cakephp/cakephp/src/Console/BaseCommand.php:175
- /media/notes/notes_www/vendor/cakephp/cakephp/src/Console/CommandRunner.php:336
- /media/notes/notes_www/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171
- /media/notes/notes_www/bin/cake.php:12
```

### What you expected to happen
Cake create the model. I have verified the database

**Comment by markstory** [comment]
How can someone reproduce this issue? Could you post an application skeleton in a repository that shows this problem?

**Comment by ikkysleepy** [comment]
How about you try to use the Northwind sample database?

https://github.com/jpwhite3/northwind-SQLite3/blob/master/Northwind_small.sqlite

I just tried it for Customers table and got the same result. The only thing that changed are those two lines and adding the file.

**Comment by markstory** [comment]
I'll see what I can do.

**Comment by markstory** [comment]
I wasn't able to reproduce your problem with my local setup. Furthermore, the `app_local.php` file works fine for me.

**Comment by ikkysleepy** [comment]
I just did a clean install on Ubuntu 18.04.4 running PHP 7.2
```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

and I have the same issues. Which version of PHP are  you using?

**Comment by othercorey** [comment]
For app_local, how did you setup the cakephp application? That file is loaded in bootstrap.php from the cakephp/app skeleton.

https://github.com/cakephp/app/blob/a1ecb83e73068880874852dbac6d3f18cb556ec7/config/bootstrap.php#L88

**Comment by markstory** [comment]
@ikkysleepy I tested on 

```
$ php -v
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

Since you are trying to use SQLite. Do you have the required sqlite3 and pdo_sqlite extensions installed?

**Comment by ikkysleepy** [comment]
> @ikkysleepy I tested on
> 
> ```
> $ php -v
> PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:37) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
> ```
> 
> Since you are trying to use SQLite. Do you have the required sqlite3 and pdo_sqlite extensions installed?

Yeah I have it installed. I usually install it to get the cakephp debug plugin to work.

```
sysadmin@notes:/var/www$ php -m  | grep sqlite
pdo_sqlite
sqlite3
```

I used composer to set it up, 
`composer create-project --prefer-dist cakephp/app:4.* notes_www`

I edited the app_local.php to add those lines but it wouldn't stick, which meant that the landing page will say it could  not connect to the database. Editing the app.php did fix the error;however it looks like it is not validating the .sqlite database because I put a fake database name it said it was connected.

**Comment by markstory** [comment]
Sounds like you got it sorted which is good. I'll see if we can make the connection error a bit better as I think a better error would have helped with this.

**Comment by markstory** [comment]
I don't think we can do much about this. When you use a non-existant file with SQLite, SQLite will create the file with an empty database in it. See this sample script

```php
<?php

$con = new PDO('sqlite:' . __DIR__ . 'nope.sql');
$res = $con->query('select * from sqlite_master');
var_dump($res->fetchAll());
```

When you run this it will create `nope.sql`. If you then remove the sql file and re-run the script a new file will be created. Because of this there are no errors for us to catch or propagate.
