### ISSUE TITLE
CakePHP 4.0.3 CounterCache on null association using finder

### ISSUE THREAD

**Issue by chopstik** [cakephp/cakephp#14362]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.3
* Platform and Target: Docker/php:7.4.3-apache

### What you did
Suffering the same InvalidArgumentException as #14276. My CounterCache behaviour however uses a finder method. When using the finder and the association is null, $entity->save() throws InvalidArgumentException.

```
$this->addBehavior('CounterCache', [
	'ContractorCompanies' => [
		'threshold_jobs_count' => [
			'finder' => 'ThresholdJobsCount',
		],
	],
	'Instructions'        => ['jobs_count'],
]);
```

```
public function findThresholdJobsCount(Query $query, array $options)
{
	$query->andWhere(['Jobs.assigned' => true]);
	$currentWeek = Time::parse('monday this week');
	$query->andWhere(
		$query->newExpr()->gte('Jobs.created', $currentWeek->format('Y-m-d H:i:s'))
	);
	return $query;
}
```
### What happened
$entity->save() throws InvalidArgumentException, "Expression is missing operator (IS, IS NOT) with `null` value.","File":"\/var\/www\/html\/vendor\/cakephp\/cakephp\/src\/Database\/Expression\/QueryExpression.php (Line: 782)"

### What you expected to happen
On $entity->save() the CounterCache behaviour (using a finder or not) ignores the null association.

**Comment by victoreassis** [comment]
This is not fixed on 4.0.4 already?

**Comment by markstory** [comment]
@chopstik Could you try upgrading to 4.0.4 and see if you still have the same problem?

**Comment by chopstik** [comment]
@markstory Have upgraded to v4.0.4 and retested. Issue still occurs. I tried three adjustments;

1. Commenting just the `\\ $query->andWhere(['Jobs.assigned' => true]);` $query modificatiosn within the finder `findThresholdJobsCount()` methods
2. Commenting out the finder option on the model option from the `$this->addBehavior('CounterCache')` method
3. Commenting out the entire model option from the `$this->addBehavior('CounterCache')` method

It is only 3) that will allow the original save() to proceed without the InvalidArgumentException being thrown.

**Comment by chopstik** [comment]
```
$this->addBehavior('CounterCache', [
/*			'ContractorCompanies' => [
		'threshold_jobs_count' => [
//					'finder' => 'ThresholdJobsCount',
		],
	],*/
	'Instructions'        => ['jobs_count'],
]);
```
