### ISSUE TITLE
Setting response code out of 1xx-5xx range (rest/restful api)

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14372]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8.10/4.x
* Platform and Target: nginx php7.3+

Currently, to be able to send custom HTTP Status Code for REST API use-case, i've had to patch the Http/Response.php (diff against 3.8.10 version) like this
```diff
> git diff
diff --git a/src/Http/Response.php b/src/Http/Response.php
index 54e68c6..488c0dc 100644
--- a/src/Http/Response.php
+++ b/src/Http/Response.php
@@ -992,16 +992,9 @@ class Response implements ResponseInterface
      */
     protected function _setStatus($code, $reasonPhrase = '')
     {
-        if (!isset($this->_statusCodes[$code])) {
-            throw new InvalidArgumentException(sprintf(
-                'Invalid status code: %s. Use a valid HTTP status code in range 1xx - 5xx.',
-                $code
-            ));
-        }
-
         $this->_status = $code;
         if (empty($reasonPhrase)) {
-            $reasonPhrase = $this->_statusCodes[$code];
+            $reasonPhrase = isset($this->_statusCodes[$code]) ? $this->_statusCodes[$code] : 'API Response';
         }
         $this->_reasonPhrase = $reasonPhrase;
```

Incorrect and awful solution (second part could be solved by changing default reasonPhrase or always passing some string), yes, but there is currently no supported framework way

I came up with checklist, that I'd like to see implemented, and I can contribute directly via PRs to do that, but I'd like to know your opinion on this subject first.

For CakePHP 3.8.10
 - [ ] There should be non-deprecated way to set statusCodes (method `Cake\Http\Response::httpCodes($code = null)` is deprecated and to be removed in 4.0.0)
 - [ ] Method `Response::httpCodes($code = null)` accepts any http status-code definition, if status code number is in range **100<=statusCode<=999** this filter should be optional and it does not match next issue
 - [ ] `InvalidArgumentException` in `Response::_setStatus($code, $reasonPhrase = '')` message is misleading, since the validation (`httpCodes`) allows codes out of range 1xx-5xx
 - [ ] Should the status codes number range be validated, validation should be optionally turned off, not hard-coded

For CakePHP 4.x
 - [ ] There should be way to set statusCodes (method `httpCodes` is already removed, and no other documented way is available)
 - [ ] Should the status codes number range be validated, validation should be optionally turned off, not hard-coded

**Comment by markstory** [comment]
What are you using custom HTTP status codes for? Given that the HTTP spec is fairly well established I'm not aware of why we need to allow people to go outside of it.

**Comment by ADmad** [comment]
HTTP status codes are well defined http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

If one wants to use non-standard codes using a custom response class is the way to go.

**Comment by smarek** [comment]
In this case proxying a legacy API, that uses cca 300 different application states / response codes, providing them directly using http status-code instead of content/body of response, numbers in range 600 - 1200, wild I know

ie. expanding from HTTP 400/409/422 status codes, to 110 specific reasons why the request is not correct/conflicting/processable, again communicated using HTTP Status codes

Anyway, @ADmad custom response class is documented where please?

and for both of you, is there any RFC or PSR reason, why the framework should not allow using codes outside of range defined in [RFC7231#section-6](https://tools.ietf.org/html/rfc7231#section-6) ?

**Comment by ADmad** [comment]
> Anyway, @ADmad custom response class is documented where please?

Just extend `Cake\Http\Response` and override what you need. Then either set `$controller->response` to instance of your class or return it's instance from your method.

> is there any RFC or PSR reason, why the framework should not allow using codes outside of range defined in RFC7231#section-6

Because HTTP status codes are a well defined set
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml. There's no reason for frameworks to allow made up ones like you want.

Closing as yours is an edge case use case which can be solve by using a custom response class. There's no need for the framework to support non standard HTTP status codes.

**Comment by smarek** [comment]
But framework supported that and could again.
Also closing this ticket does not solve the mentioned issues, currently neither 3.x or 4.x are able to set custom http codes, even within range of 1xx - 5xx (IANA unassigned ranges), and that is something worth looking into.
