### ISSUE TITLE
Datetime parsing regression in 3.x

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14385]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest 3.x

### What you did

An upgraded cake2 app has this code:
```php
$data['last_click'] = date('Y-m-d H:i:s'); // 2020-03-22 xx:yy:zz
$user = $this->newEntity($data);
$this->saveOrFail($user);
```

### What happened
Now silently the whole app is filled up with future dates:

    2025-09-10 11:22:00

for this above entry of `last_click`.

### What you expected to happen
No such hidden future travels when storing datetime.

I was able to prevent this from changing
```php
Type::build('time')
	->useImmutable()
	->useLocaleParser();
Type::build('date')
	->useImmutable()
	->useLocaleParser();
Type::build('datetime')
	->useImmutable()
	->useLocaleParser();
```
to
```php
Type::build('time')
	->useImmutable();
Type::build('date')
	->useImmutable();
Type::build('datetime')
	->useImmutable();
```
in bootstrap

But the local format shouldnt be relevant here for an ISO string format used IMO.

**Comment by ADmad** [comment]
This isn't a bug. You turned on locale based string and hence it was parsed as such (how you ended up with that particular date is up to whatever shenanigans `IntlDateFormatter` does for your locale).

Checking whether the string is in ISO format (and there's isn't just one) before doing locale based parsing would be necessary overhead.

You can avoid the string parsing by setting your field to a numeric timestamp or `DateTimeInterface` instance.

**Comment by dereuromark** [comment]
Hm, I see.
Yeah, it can make some overhead to check ISO formats.
Just a bit hard to spot now all the cases inside a larger upgraded app as this silently puts those timestamps 5 years into the future, without warning/notice.

**Comment by othercorey** [comment]
Were you using a locale parser in 2.x?

**Comment by dereuromark** [comment]
Well, there everything seemed to work a bit differently.
I can accept the fact that in this case the local parsing has to be disabled then.
