### ISSUE TITLE
HtmlHelmer::meta icon did not respect plugin assets

### ISSUE THREAD

**Issue by yarkm13** [cakephp/cakephp#14387]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: CakePHP 3.8.10 (looks like last master behaves the same)
* Platform and Target: n/a

### What you did
use `HtmlHelper::meta()` to generate favicon inside theme(plugin) template like

    $this->Html->meta('icon', '/img/favicon.png', ['type'=>'image/png']);

### What happened
Generated url exactly as provided `/img/favicon.png`

    <link href="/img/favicon.png" type="image/png" rel="icon"/>
    <link href="/img/favicon.png" type="image/png" rel="shortcut icon"/>

### What you expected to happen
Expected `/plugin/img/favicon.png` path to plugin assets like `HtmlHelper::image()` or `HtmlHelper::script()` does

**Comment by markstory** [comment]
One reason the paths are not automatically generated/changed is that meta() handles a variety of meta tags and not all of them are assets. What behavior would you expect when creating meta tags for `rss` or `next` and `prev` links?. I don't think we can assume that the content of these tags should be treated as plugin prefixed assets.

**Comment by ADmad** [comment]
@yarkm13 You can use the following to achieve what you need:

```
$this->Html->meta('icon', $this->Url->image('favicon.png'), ['type'=>'image/png']);
```
