### ISSUE TITLE
CakePHP Model Events inconsistency.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14388]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: master+4.next

### What you did
When looking into Cake4.1 and event hook improvements @saeideng and me stumbled upon an inconsistency in event order/execution.

See https://github.com/dereuromark/executionorder/pull/8
(can be reproduced locally)

### What happened
When using Table::initialize() to add a behavior, the order is as expected and as known so far ( https://github.com/dereuromark/executionorder/blob/cake3/RESULTS.md#model-validate--save )
```
TokensTable:initialize
AlphaBehavior:initialize
AlphaBehavior:beforeMarshal
TokensTable:beforeMarshal
TokensTable:validationDefault
AlphaBehavior:buildValidator
TokensTable:buildValidator
AlphaBehavior:afterMarshal
TokensTable:afterMarshal
TokensTable:buildRules
AlphaBehavior:buildRules
AlphaBehavior:beforeRules
TokensTable:beforeRules
AlphaBehavior:afterRules
TokensTable:afterRules
AlphaBehavior:beforeSave
TokensTable:beforeSave
AlphaBehavior:afterSave
TokensTable:afterSave
```

But if you load it inside a controller dynamically on a Table:
```
TokensTable:initialize
AlphaBehavior:initialize
TokensTable:beforeMarshal
AlphaBehavior:beforeMarshal
TokensTable:validationDefault
TokensTable:buildValidator
AlphaBehavior:buildValidator
TokensTable:afterMarshal
AlphaBehavior:afterMarshal
TokensTable:buildRules
AlphaBehavior:buildRules
TokensTable:beforeRules
AlphaBehavior:beforeRules
TokensTable:afterRules
AlphaBehavior:afterRules
TokensTable:beforeSave
AlphaBehavior:beforeSave
TokensTable:afterSave
AlphaBehavior:afterSave
```
### What you expected to happen
The order shouldn't change based on the fact of loading differently.
I often, for example, unload to load with a different config or have other reasons to add dynamically.

This shouldn't matter usually too much. 
But I am sure some edge cases make this a trap, as the order is expected to be the one we know, with model coming after behavior(s).

If we want to consolidate this, then this probably has to go into 4.next.

**Comment by markstory** [comment]
> The order shouldn't change based on the fact of loading differently.

How could the order not change though? Listeners are always appended to the listener list for their priority level. When a behavior is loaded during a controller action it happens *after* other listeners (table listeners) are bound and thus the listener is fired later.

**Comment by dereuromark** [comment]
OK, so this is then "expected" behavior, and people just need to be careful not to create code that would depend on the coupling / order of adding.

**Comment by markstory** [comment]
Yes. If very specific ordering is required then priorities should be used to ensure listeners are not subject to temporal coupling.
