### ISSUE TITLE
Migrations plugin exception on fresh installation

### ISSUE THREAD

**Issue by LaaHudra** [cakephp/cakephp#14386]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.4
* Platform and Target: Ubuntu, PHP 7.4

### What you did
Do a Initial snapshop for migrations plugin

### What happened
root@4da68403a4db:/var/www/html# bin/cake bake migration_snapshot Initial

Creating file /var/www/html/config/Migrations/20200323124551_Initial.php
Wrote `/var/www/html/config/Migrations/20200323124551_Initial.php`
Marking the migration 20200323124551_Initial as migrated...
Exception: Shell class for "Migrations" could not be found. If you are trying to use a plugin shell, that was loaded via $this->addPlugin(), you may need to update bin/cake.php to match https://github.com/cakephp/app/tree/master/bin/cake.php
In [/var/www/html/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 332]

### What you expected to happen
Migrations plugin should work on fresh instalation

**Comment by dereuromark** [comment]
How did you load your plugin?

**Comment by dereuromark** [comment]
This looks like a user error, the exception message shows what needs to be done here.
This is a bug tracker, please refer to forum or Slack channel for support/help.

**Comment by saeideng** [comment]
sorry for this failure
 
a PR now is open , you can confirm/test it 
https://github.com/cakephp/migrations/pull/435
