### ISSUE TITLE
Cors Issue.

### ISSUE THREAD

**Issue by LaaHudra** [cakephp/cakephp#14392]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.4
* Platform and Target: Ubuntu, React Frontend, Cake as Backend

### What you did
Triggered xhr request
I put in AppController::beforefilter:
```php
$this->response = $this->response->cors($this->request)
            ->allowOrigin(['*'])
            ->allowMethods(['GET', 'POST', 'OPTIONS', 'PUT'])
            ->allowHeaders(['Content-Type','X-CSRF-Token','Authorization'])
            ->maxAge(172800)
            ->build();
```

### What happened
Request is blocked because of cors.

### What you expected to happen
Request should be allowed because I set headers.

I had the same issue before on cakephp 3.x but plugin cames into play: https://github.com/ozee31/cakephp-cors
and it was workign like a charm. Now when this plugin dont have cake v4 version I am stuck. Looks like OPTIONS request is not properly handled. `Origin` header is set on final request not on OPTIONS request. 
Also tried Middleware but without any results.
https://www.munderwood.ca/index.php/2017/02/28/responding-to-http-options-requests-in-cakephp/

**Comment by LaaHudra** [comment]
`class HttpOptionsMiddleware implements MiddlewareInterface
{

  public function process(
    ServerRequestInterface $request,
    RequestHandlerInterface $handler
  ): ResponseInterface
  {
    // Calling $handler->handle() delegates control to the *next* middleware
    // In your application's queue.
    $response = $handler->handle($request);

      if (isset($_SERVER['HTTP_ORIGIN'])) {
          // Decide if the origin in $_SERVER['HTTP_ORIGIN'] is one
          // you want to allow, and if so:
          header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
          header('Access-Control-Allow-Credentials: true');
          header('Access-Control-Max-Age: 86400');    // cache for 1 day
          if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {

              if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
                  // may also be using PUT, PATCH, HEAD etc
                  header("Access-Control-Allow-Methods: GET, POST, OPTIONS");

              if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
                  header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

              exit(0);
          }
      }

    return $response;
  }
}`

**exit(0);** solves the problem and all works. but I can not use withHeaders etc. because it will not use a response object in this case.

**Comment by markstory** [comment]
If you're building a middleware why couldn't you add the headers and return the response?

**Comment by LaaHudra** [comment]
When I return response, it didn't fix the problem. The code was moving forward. Only if I put `exit(0)` to stop the script and just sent headers it worked.

Honestly, I have no idea whats the difference between (v.3.x):
```
return $next($request, $response);
```
and
```
return $response;
```

but base on v4.x there is less params in `process` function then in cakephp v3 `__invoke`.

**Comment by markstory** [comment]
Ok. You shouldn't need to use header() or exit() ever. I can try and reproduce the missing cors headers.

**Comment by LaaHudra** [comment]
> Ok. You shouldn't need to use header() or exit() ever. I can try and reproduce the missing cors headers.

```
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event);
        if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
            file_put_contents(TMP . 'text.txt', json_encode($_SERVER));
        }
        $this->response = $this->response->cors($this->request)
            ->allowOrigin(['*'])
            ->allowMethods(['GET', 'POST', 'OPTIONS', 'PUT'])
            ->allowHeaders(['Content-Type','X-CSRF-Token','Authorization'])
            ->maxAge(172800)
            ->build();
        print_r($this->response);

    }
```

Text.txt content:
```
'HTTP_ORIGIN' => 'http://localhost:3000',
```

```
Response Object print_r

Cake\Http\Response Object
(
    [status] => 200
    [contentType] => text/html
    [headers] => Array
        (
            [Content-Type] => Array
                (
                    [0] => text/html; charset=UTF-8
                )

            [Access-Control-Allow-Origin] => Array
                (
                    [0] => *
                )

            [Access-Control-Allow-Methods] => Array
                (
                    [0] => GET, POST, OPTIONS, PUT
                )

            [Access-Control-Allow-Headers] => Array
                (
                    [0] => Content-Type, X-CSRF-Token, Authorization
                )

            [Access-Control-Max-Age] => Array
                (
                    [0] => 172800
                )

        )

    [file] => 
    [fileRange] => Array
        (
        )

    [cookies] => Cake\Http\Cookie\CookieCollection Object
        (
            [cookies:protected] => Array
                (
                )

        )

    [cacheDirectives] => Array
        (
        )

    [body] => 
)
```

So looks like headers are set correctly, but then it wipes..

I found the problem....

In my token action I have:
```
return $this
          ->getResponse()
          ->withStatus($status)
          ->withType('json')
          ->withStringBody(json_encode($response));
```
This code overwrites previous headers.

Replaced with:
```
$this->set(compact('response'));
      $this->set('_serialize', ['response']);
```

Leaving all this information future user reference. Issue can be closed.

**Comment by LaaHudra** [comment]
Finall setup with StateLess Jwt Style.
```
public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event);
        $this->response = $this->response->cors($this->request)
            ->allowOrigin(['*'])
            ->allowCredentials()
            ->allowMethods(['GET', 'POST', 'OPTIONS', 'PUT'])
            ->allowHeaders(['Content-Type','X-CSRF-Token','Authorization','Origin'])
            ->maxAge(172800)
            ->build();
        if ($this->request->is('OPTIONS')) {
            $event->stopPropagation();
            return $this->response;
        }
    }
```

Works like a charm.

**Comment by ulziibadrakh-p** [comment]
I want to do it CakePHP way but not working in both AppController and MIddleware. It's working raw PHP way in bootstrap.

AppController
```
public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event);
        $this->response = $this->response->cors($this->request)
            ->allowOrigin(['*'])
            ->allowCredentials()
            ->allowMethods(['GET', 'POST', 'OPTIONS', 'PUT'])
            ->allowHeaders(['Content-Type','X-CSRF-Token','Authorization'])
            ->maxAge(172800)
            ->build();
        if ($this->request->is('OPTIONS')) {
            $event->stopPropagation();
            return $this->response;
        }
    }
```

MIddleware
```
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {

        $response = $handler->handle($request);

        if ($request->getHeader('Origin')) {
            $response = $response
                ->withHeader('Access-Control-Allow-Origin', '*')
                ->withHeader('Access-Control-Allow-Headers', '*');
            if (strtoupper($request->getMethod()) === 'OPTIONS') {
                $response = $response
                    ->withStatus(200, __('Say cheese!'));
            }
        }

        return $response;
    }
```

 in bootstrap
```
header('Access-Control-Allow-Origin: http://localhost:3000');
header('Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, PATCH, DELETE');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Authorization, Content-Type, x-xsrf-token, x_csrftoken, Cache-Control, X-Requested-With');
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    exit(0);
}
```

**Comment by othercorey** [comment]
Please open a new issue if there is a new bug.

**Comment by ulziibadrakh-p** [comment]
> Please open a new issue if there is a new bug.

I think it is the same issue
