### ISSUE TITLE
RFC: Trigger a notice when doing "where B.field" in $a->find()->contain('B') without "joinWith/matching" where A hasMany B

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#14390]
This is a (multiple allowed):

* [ ] bug
* [?] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Any

### What you did
After years and years not only using CakePHP (since 1.2) but also "teaching" my interns, I've realised a repetitive mistake very common: people still think that, in a some sort of "magic way", a hasMany association like users -> articles, you can do something like this:

```
<?php
$users->find()->contain('Articles')->where(['Articles.title'=>'test']);

```
And something naturally 2d as SQL will be transformed in 3d without any kind of repetition (or separated query). But the result, of course, it's a SQL error.

Believe in me, even with [this whole dedicate section](https://book.cakephp.org/3/en/orm/query-builder.html#filtering-by-associated-data) that even I have collaborated recently, people still trying codes like the above and they still trying through years or decades because it's very temptative to think in "transparent ORM for every situation".

So I thought myself, what if Mark and the others guys included some sort of notice or even a Throwable when someone do something like this happening, maybe with a message suggesting something like "are you trying to match filter associated data....." ?

### What happened
Sql Error without any kind of "hint" or "help"

### What you expected to happen
A helpful throwable or even a simple trigger_error

**Comment by markstory** [comment]
What kind of query does this generate? I would assume it would be an invalid one as hasMany associations don't join by default.

**Comment by celsowm** [comment]
> 
> 
> What kind of query does this generate? I would assume it would be an invalid one as hasMany associations don't join by default.

Yep !
Something like:

`SELECT .... FROM users WHERE Articles.title = 'test' `

And of course, a SGBD like MSSQL will complain saying "_**The multi-part identifier "Articles.title" could not be bound**_."
