### ISSUE TITLE
IntegrationTestCase regression on session flash

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14398]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: dev-master

### What you did
3.x plugin test code
```php
	public function testGenerate() {
		$this->disableErrorHandlerMiddleware();

		$data = [
			'plugin' => 'Tools',
			'name' => 'MyCoolRecords',
		];

		$this->post(['plugin' => 'TestHelper', 'controller' => 'TestFixtures', 'action' => 'generate'], $data);

		$this->assertResponseCode(302);

		$flash = $this->_requestSession->read('Flash.flash');
		$flash = Hash::combine($flash, '{n}.element', '{n}.message');
		$this->assertTextContains('bake fixture MyCoolRecords -q -p Tools', $flash['Flash/info']);
		$this->assertSame('MyCoolRecordsFixture generated.', $flash['Flash/success']);
	}
```

Upgraded to 4.x
```php
	public function testGenerate() {
		$this->disableErrorHandlerMiddleware();
		//$this->_retainFlashMessages = true; // Only necessary for rendering involved.

		$data = [
			'plugin' => 'Tools',
			'name' => 'MyCoolRecords',
		];

		$this->post(['plugin' => 'TestHelper', 'controller' => 'TestFixtures', 'action' => 'generate'], $data);

		$this->assertResponseCode(302);

		$flash = $this->_requestSession->read(); dd($flash);	
		//FIXME - why null?
		/*
		$flash = $this->_requestSession->read('Flash.flash');
		$flash = Hash::combine($flash, '{n}.element', '{n}.message');
		$this->assertTextContains('bake fixture MyCoolRecords -q -p Tools', $flash['flash/info']);
		$this->assertSame('MyCoolRecordsFixture generated.', $flash['flash/success']);
		*/
	}
```

### What happened
The session is empty, despite the 302 and thus no rendering happening.

### What you expected to happen
This shouldn't happen.
The session data, especially the flash messages (I double-checked, they are written to session in controller code), should still be there for test assertion.

--- 

Reproducible directly when cloning master: https://github.com/dereuromark/cakephp-test-helper

**Comment by markstory** [comment]
This limitation is documented in the migration guide from what I remember. The cause is that the session is closed at the end of each simulated request and because  all the code runs in the CLI, the session restarts fresh. This problem was also reported in  #14270

**Comment by dereuromark** [comment]
Jep, indeed, it runs into start() due to session_status() being 1 instead of 2, it clears.
I wonder if we could keep that open for the remaining time or use a wrapper Session object for testing to store and retain the data?

**Comment by dereuromark** [comment]
For now, using $_SESSION directly seems like a viable short term workaround. So fair enough if we don't want to get the convenience wrappers working again.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-test-helper/commit/0a8eaf56b02d39c25293ac51d9b1591050a437ed#diff-74bfea6f6fb4add7746dde591fe332efR76-R83
fixes it for now on project/plugin level.

And I opened a PR as core solution to allow this regression to be solved with minimal
migration effort and fully BC.
