### ISSUE TITLE
Query in database SQL Server always add Unicode in conditions string evenif data and column is not Unicode

### ISSUE THREAD

**Issue by kongka** [cakephp/cakephp#14393]
* [x] enhancement

* CakePHP Version: 2.10.20
* Platform and Target: SQL Server

### What happened
Query in database SQL Server always add Unicode in conditions string. like `SELECT * FROM users WHERE email = N'mail@example.com'`. For many records data (like 10M records), this will take too long to get the result from database.

### What you expected to happen
It should not add Unicode in conditions string, if data is not Unicode. like `SELECT * FROM users WHERE email = 'mail@example.com'`

### How to fix this
Update this file `Model/Datasource/Database/Sqlserver.php` on method `value()` with below code:
```
public function value($data, $column = null, $null = true) {
	if ($data === null || is_array($data) || is_object($data)) {
		return parent::value($data, $column, $null);
	}
	if (in_array($data, array('{$__cakeID__$}', '{$__cakeForeignKey__$}'), true)) {
		return $data;
	}

	if (empty($column)) {
		$column = $this->introspectType($data);
	}

	switch ($column) {
		case 'string':
			if (mb_strlen($data) !== strlen($data)) {
				return 'N' . $this->_connection->quote($data, PDO::PARAM_STR); // unicode condition
			}
			return '' . $this->_connection->quote($data, PDO::PARAM_STR);
		case 'text':
			return 'N' . $this->_connection->quote($data, PDO::PARAM_STR);
		default:
			return parent::value($data, $column, $null);
	}
}
```
So before compare the string, we need to check if data is Unicode or not. if data is Unicode string, `mb_strlen($data)` and `strlen($data)` will output different length.

#### Note
I always need to do this change when there is new version release CakePHP 2.x in my current production because there are 30M records in my database.
I found the issue and fix it by doing this. And I hope this help other too.

**Comment by markstory** [comment]
Any chance you'd be interested in putting together a pull request for the changes you've been patching in each time?

**Comment by othercorey** [comment]
@kongka Can you make a PR?

**Comment by othercorey** [comment]
@kongka Can you create a PR with your changes?
