### ISSUE TITLE
4.0: ConsoleIntegrationTestTrait

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#14409]
I noticed the latest changes to `ConsoleIntegrationTestTrait`.

However, I noticed that a relevant error is shown only for the `$_in` property, while this does not happen for the `$_err` property.

In fact, by updating a plugin to the latest version, I get this output:

```
There was 1 error:

1) MeCms\Test\TestCase\Command\AddUserCommandTest::testExecute
RuntimeException: You can use `$input` only if `$_in` property is null and will be reset.

/home/mirko/Libs/Plugins/me-cms/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestTrait.php:111
/home/mirko/Libs/Plugins/me-cms/tests/TestCase/Command/AddUserCommandTest.php:59

--

There were 2 failures:

1) MeCms\Test\TestCase\Command\Install\CreateGroupsCommandTest::testExecute
Failed asserting that error output is empty.

/home/mirko/Libs/Plugins/me-cms/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestTrait.php:297
/home/mirko/Libs/Plugins/me-cms/tests/TestCase/Command/Install/CreateGroupsCommandTest.php:66

2) MeCms\Test\TestCase\Command\Install\FixKcfinderCommandTest::testExecute
Failed asserting that error output is empty.

/home/mirko/Libs/Plugins/me-cms/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestTrait.php:297
/home/mirko/Libs/Plugins/me-cms/tests/TestCase/Command/Install/FixKcfinderCommandTest.php:50
```

The two failures are caused by the fact that the `$_err` property has not been reset and is not `null`.
Why not do the same, as for `$_in`?

Also, wouldn't it be appropriate to add a `reset()` method or something similar at this point?

**Comment by dereuromark** [comment]
It is reset in https://github.com/cakephp/cakephp/blob/master/src/TestSuite/ConsoleIntegrationTestTrait.php#L137
So you must have a different setup or forgetting to call parent:: calls.

What does your code look like?

**Comment by mirko-pagliai** [comment]
> It is reset in https://github.com/cakephp/cakephp/blob/master/src/TestSuite/ConsoleIntegrationTestTrait.php#L137
> So you must have a different setup or forgetting to call parent:: calls.
I apologize, I had ignored it.

> What does your code look like?
In the same test I use the `exec()` method several times, for example with different options.

**Comment by dereuromark** [comment]
Can you try to not do that, integration tests by definition need only one call per test() method.
As the state around it should be cleared/reset.
Does that work then?

**Comment by mirko-pagliai** [comment]
> Does that work then?

Yes, this is not the problem.
I was just saying that, in my opinion, as with the `$_in` property, it should throw the same exception even if the` $_err` property is not `null`.

If [this check](https://github.com/cakephp/cakephp/blob/master/src/TestSuite/ConsoleIntegrationTestTrait.php#L102) is done, why a `RuntimeException` only for the `$_in` property?

**Comment by dereuromark** [comment]
Because of the side effect of input through the argument. See the exception message.

**Comment by mirko-pagliai** [comment]
> Because of the side effect of input through the argument. See the exception message.

Yes. So if so, everything is ok.
