### ISSUE TITLE
Printer method of Collection don't respecting spacer

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#14402]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5
* Platform and Target: WAMP

### What you did
Example from docs https://book.cakephp.org/4/en/core-libraries/collections.html#Cake\Collection\Collection::listNested:
```
$collection = new Collection([
    ['id' => 1, 'parent_id' => null, 'name' => 'Birds'],
    ['id' => 2, 'parent_id' => 1, 'name' => 'Land Birds'],
    ['id' => 3, 'parent_id' => 1, 'name' => 'Eagle'],
    ['id' => 4, 'parent_id' => 1, 'name' => 'Seagull'],
    ['id' => 5, 'parent_id' => 6, 'name' => 'Clown Fish'],
    ['id' => 6, 'parent_id' => null, 'name' => 'Fish'],
]);

pr($collection->listNested()->printer('name', 'id', '---'));
```

### What happened
Returns:
```
Array
(
    [0] => Birds
    [1] => Land Birds
    [2] => Eagle
    [3] => Seagull
    [4] => Clown Fish
    [5] => Fish
)
```

### What you expected to happen
Should return:
```
Array
(
    [0] => Birds
    [1] => ---Land Birds
    [2] => ---Eagle
    [3] => ---Seagull
    [5] => Fish
    [4] => ---Clown Fish
)
```

I think, there are two problems, first there is no added spacer to string, second `Clown Fish` should be under `Fish`.

**Comment by markstory** [comment]
It looks like you're missing a call to `nest()`. Your flattened data cannot be printed as a nested list as it is not nested.
