### ISSUE TITLE
Which keys are used in PaginatorHelper options

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#14400]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5
* Platform and Target: PHP 7.4, MariaDB, Windows x64

### What you did
I want to add some default URL parameters to my Paginator links so I did:

```php
<?php $this->Paginator->options(['url' => [$user->id, '#' => 'show-related-users']]) ?>
```

### What happened
The URL parameters are ignored when building Navigation links via:

```php
<?= $this->Paginator->first('<< ' . __('first')]) ?>
```

### What you expected to happen
I would expect the params to be added to the Navigation links.

I see `PaginatorHelper::first()` is defaulting to `'url' => []` but then what's the code in PaginatorHelper.php#182 for and what options are supported in `PaginatorHelper::options()`.
From how I interpret the method docblock of `PaginatorHelper::options()` I think more options should be kept for link generation. Additionally the docblock points to `PaginatorHelper::$options`, however there is no class variable with this name.

**Comment by ADmad** [comment]
It's the `PaginatorHelper::generateUrlParams()` method which merges the URL params set using `options()` method.

There are tests shows link generated for `first()` does take the `url` set using `options()` method into account:

https://github.com/cakephp/cakephp/blob/dabb56c4afc76b3a5fed8e2c6ea03fde3b45f3d4/tests/TestCase/View/Helper/PaginatorHelperTest.php#L2751-L2757

**Comment by swiffer** [comment]
ok, got it - sorry - when using scoped pagination the default options need to include the scope:

```php
<?php $this->Paginator->options([
    'url' => ['related_users' => [$user->id, '#' => 'show-related-users']]
]) ?>
```
