### ISSUE TITLE
HasMany associations has different property name on empty result

### ISSUE THREAD

**Issue by hakito** [cakephp/cakephp#14426]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.10
* Platform and Target: docker php 7.4

### What you did

The table 'OrderedTicketTypes' is empty.

```php
$entity = $this->Order->get('1', ['contain' => 'OrderedTicketTypes']);
foreach($entity->OrderedTicketTypes as $key => $value)
```

### What happened

```
Warning Error: Invalid argument supplied for foreach()
```

[The _groupResult does not consider the alias when the associated result is empty](https://github.com/cakephp/cakephp/blob/a96483bc6066ffedbc787e3f7e7e3e2483242f78/src/ORM/ResultSet.php#L552).

Instead it uses the propertyName of the association (which defaults to underscore variant of the association name)

### What you expected to happen

```php
$entity['OrderedTicketTypes'] == []
```

**Comment by markstory** [comment]
Associations should always be populating the property name key and not the association alias. When do you get the association alias set in the entity?

**Comment by hakito** [comment]
After a 2nd look at this you are right. Sorry for this.
