### ISSUE TITLE
Support for TLS 1.3 in CakeSocket

### ISSUE THREAD

**Issue by coolacid** [cakephp/cakephp#14422]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Branch: 2.x - File Hash: da8414e13bfc559f1eb7c45176050a2c1a16562b
* Platform and Target: No specific details

### What you did
MISP is a PHP software solution for sharing cyber intelligence details. MISP currently uses Cake version v2.10.19. It has the ability to connect to other MISP instances, and uses Cake SyncTool to do so. This fails when connecting to a server that forces TLS 1.3. 

Cake 2.x uses the function `_addTlsVersions` to identify which TLS versions should be set for the encrypted socket. https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/CakeSocket.php#L137-L158

PHP 7.4.0 added support for TLS 1.3 ( https://www.php.net/ChangeLog-7.php ) and a modified version of the above function which just prints out the available `STEAM_CRYPTO_METHOD`'s yields the following (via docker container):

```
root@9120a03ed694:/usr/src/myapp# php --version
PHP 7.4.4 (cli) (built: Mar 31 2020 18:15:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
root@9120a03ed694:/usr/src/myapp# php test.php 
STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_1_SERVER
STREAM_CRYPTO_METHOD_TLSv1_2_SERVER
STREAM_CRYPTO_METHOD_TLSv1_3_SERVER
root@9120a03ed694:/usr/src/myapp# 
```
Unfortunately, I don't currently have a way to PR and test this issue.

**Comment by RichieB2B** [comment]
Did you try to add these constants to the `_addTlsVersions` function? Looks like that might work. 
```
STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_3_SERVER
```

**Comment by markstory** [comment]
The TLS 1.3 constants would need to be conditionally added if defined as they won't exist on the majority of php versions that 2.x supports.

**Comment by coolacid** [comment]
Finding the bug was the easy part. Unfortunately, since I don't personally code against CakePHP and don't have test rigs to test, I don't trust that I know the correct way to solve this issue. 

I suspect, adding those defines, and building a similar isset test that appends the 1.3 defines would work.

**Comment by RichieB2B** [comment]
> The TLS 1.3 constants would need to be conditionally added if defined as they won't exist on the majority of php versions that 2.x supports.

Isn’t that exactly what ` _addTlsVersions` does?

**Comment by markstory** [comment]
@RichieB2B Yes, but when I commented I was on a phone, and I have unloaded most 2.x from my brain.

Given that we have a way to add new TLS versions in I can put a pull request up for that.

**Comment by RichieB2B** [comment]
There is now a PR for this upstream: 
Can you try this:
```
cd app/Lib/cakephp
git pull
git checkout 50e0ca7f9d791f8e98b02c5a63ee79a932051b4b
```

**Comment by othercorey** [comment]
TLS 1.3 constants added in https://github.com/cakephp/cakephp/pull/14425
