### ISSUE TITLE
Status of delete() of associated model is ignored when  cascadeCallback is true.

### ISSUE THREAD

**Issue by menshutin** [cakephp/cakephp#14434]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.8.5
* Platform and Target: Linux, Apache, Mysql.

When associated model is set to be dependent and cascadeCallbacks is set to true, cakephp triggers separate delete fro each associated entity. If this delete is prohibited by application rules, this information is silently ignored (since return status of delete is not checked). This results in DB corruption when parent entity is deleted, and associated records are still present in DB without any errors being detected.

**Comment by markstory** [comment]
> This results in DB corruption when parent entity is deleted, and associated records are still present in DB without any errors being detected.

Shouldn't database constraints and transactions prevent the data from being corrupted?

**Comment by menshutin** [comment]
Yes, they do. But constraint violation is only a safety measure and should not be relied on.
The problem is that we ignore results of checks done by application rules and could not inform user with some meaningful error description. What we get instead is a database error and application crash because of constraint violation.

In DependentDeleteHelper.php function cascadeDelete() always returns true. It should return false if not all associated entities were deleted. And code that calls cascadeDelete() should abort transaction if delete fails.

**Comment by markstory** [comment]
@menshutin Sounds like you have a good grasp of the change that needs to be made. Would you be able to submit a pull request for a fix. I am happy to help with tests.
