### ISSUE TITLE
[SQLServer]stored procedure case sensitivity

### ISSUE THREAD

**Issue by Nic0tiN** [cakephp/cakephp#14432]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.10
* Platform and Target: SQLServer 2014 (12.0.5579)

### What you did
Fixturemanager calls `Connection::disableConstraints` and runs `SQLServer::disableForeignKeys` and `SQLServer::enableForeignKeys`.

When running on SQLServer , the statements are queried:
```sql
EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"
EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"
```

### What happened
Even though my database collation is set to Case Insensitive, driver replies it can't find `sp_msforeachtable`.

### What you expected to happen
I had to replace with those statements to run the query:
```sql
EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"
EXEC sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"
```

**Comment by othercorey** [comment]
Can you create a PR?
