### ISSUE TITLE
Plurals not recognised in localization

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#14437]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5
* Platform and Target: Safari, macOS

### What you did
I am trying to format localized.

in view
```
__dn('cake', '{0} hour', '{0} hours', 1, 1);
echo '; ';
__dn('cake', '{0} hour', '{0} hours', 2, 2);
echo '; ';
__dn('cake', '{0} hour', '{0} hours', 11, 11);
```

in cake.po file:
```
msgid "{0} hour"
msgid_plural "{0} hours"
msgstr[0] "{0} hour singular"
msgstr[1] "{0} hours plural 1"
msgstr[2] "{0} hours plural 2"
```

### What happened
With en locale:
1 hour; 2 hours; 11 hours

translated:
1 hour singular; 2 hour singular; 11 hour singular

### What you expected to happen

translated:
1 hour singular; 2 hours plural 1; 11 hours plural 2

**Comment by markstory** [comment]
I will see if I can reproduce this. Is what you provided all the message strings in your po file? Where does that po file live in the filesystem?

**Comment by nitramxx** [comment]
> Is what you provided all the message strings in your po file?
No, only the ones related to "{0} hour/s", no other occurrence of hour or hours in any cake.po or any other po files

> Where does that po file live in the filesystem?
resources/locales/cz


It's part of "%s ago" string when formatting timeAgoInWords. This part (%s ago) is interpreted correctly, ie. "ago" is translated. The %s part is the part where hour(s) are.

**Comment by markstory** [comment]
I'm not able to reproduce this problem.

1. I created `resources/Locales/en/cake.po`
2. I pasted in the msg strings you provided.
3. Added
```php
echo __dn('cake', '{0} hour', '{0} hours', 1, 1);
echo '; ';
echo __dn('cake', '{0} hour', '{0} hours', 2, 2);
echo '; ';
echo __dn('cake', '{0} hour', '{0} hours', 11, 11);
```
to a view template and got the correct results. Your original code was missing `echo` calls so I had to add them.
4. Got the following 
![Screen Shot 2020-04-11 at 14 39 47](https://user-images.githubusercontent.com/24086/79052158-874d7280-7c02-11ea-82db-324725d8ed5e.png)

I'll need a way to reproduce this problem before I can help further.

**Comment by Yorwba** [comment]
> I'm not able to reproduce this problem.
> 
>     1. I created `resources/Locales/en/cake.po`

I think you'll be able to reproduce it with `cz` instead of `en`. Or really any locale that isn't hard-coded in [PluralRules](https://github.com/cakephp/cakephp/blob/8fc5a0a33f04ea6d554be9fcad3a446d5a782b23/src/I18n/PluralRules.php#L28).

There should at least be a warning if the locale given doesn't have a plural rule defined, and ideally an escape hatch to add custom plural rules for languages that aren't supported out-of-the-box.
