### ISSUE TITLE
Class 'PHPUnit\Framework\MockObject\MockBuilder' not found

### ISSUE THREAD

**Issue by aleksiIvakhnenko** [cakephp/cakephp#14443]
This is a bug:

* CakePHP Version: **3.8.11**
* Platform and Target: **Linux**, **PHPUnit 6.2.4**.

### What you did
Run phpunit-tests

### What happened
`Fatal Error: Class 'PHPUnit\Framework\MockObject\MockBuilder' not found in [/var/www/.../vendor/cakephp/cakephp/src/TestSuite/MockBuilder.php, line 26]`.

### What you expected to happen
I expect that unit-tests should be success, as in "cakephp/cakephp": "**3.8.10**".

Plugins are loading through `$this->loadPlugins(['MyPlugin'])` in the **TestCase::setUp()**.

**Comment by garas** [comment]
Will be fixed in   #14445

But the easiest fix is if you upgrade to PHPUnit 6.5.
