### ISSUE TITLE
Database name in query

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14446]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### What you did
Build query
```
...->select()->from('Tables')->...
```

### What happened
Generated query is
```
select ... from tables Tables ....
```

### What you expected to happen
I can join a table from other database if generated query is
```
select ... from database.tables Tables ...
```

**Comment by markstory** [comment]
We don't support cross database joins in all scenarios as different databases can be located on different physical machines and be impossible to join. You *can* do cross database queries in by setting your table names with `setTable('database.users')` in MySQL at least.

**Comment by mcsknp** [comment]
I think possible to join or not is not framework problem. I think developers will not use this function if they not sure that is impossible.
If cakephp support adding database name to query from library, developers can write more useful code easily.

**Comment by ADmad** [comment]
As mentioned above setting table name like `database.users` is supported, so what's still preventing you from achieving what you want?

**Comment by mcsknp** [comment]
If my database is SQLServer, it must be `database.dbo.users`.
So I must check type of connection at my code to set table name.
I don't want to  check type of connection because I'm using query builder.

**Comment by mcsknp** [comment]
What do you think about a method that return table name with database name?

**Comment by markstory** [comment]
>  I don't want to check type of connection because I'm using query builder.

You don't have to if your table classes all set their table names based on application configuration.

> What do you think about a method that return table name with database name?

Where would something like this be used?

**Comment by mcsknp** [comment]
It's useful for process on a table from other database.
I can separate big database to many smaller database to speed up system.

**Comment by markstory** [comment]
Ok. Does the existing `setTable()` not enable you to do what you need? I'm hesitant to add additional methods to handle what I believe is an uncommon scenario.

**Comment by mcsknp** [comment]
`setTable()` can do it but I can't do it without checking database type, getting database name, that was made transparent by MVC.
You believe it is an uncommon scenario, but if you support it, it may become popular scenario.
And if you don't think so, please close this issue.

**Comment by othercorey** [comment]
I think you could override `setTable()` to automatically add the database name prefix.

**Comment by markstory** [comment]
@mcsknp I'm assuming which tables are in which databases doesn't change at runtime. Given that assumption I'm not sure why something like `setTable(Configure::read("Database.partOneName") . '.things')` wouldn't work? I'm reluctant to add more API surface area when it seems to me that this problem can be solved with what we have today.

**Comment by mcsknp** [comment]
@othercorey @markstory Thank you for suggestion. But now, I'm doing with extend each `Driver` class to write new method in it, and config by set `className` for `DATABASE_URL`.

For Mysql:
```
public function getTableFullname($table)
{
    return sprintf('`%s`.`%s`', $table->getConnection()->config()['database'], $table->getTable());
}
```
For Sqlserver:
```
public function getTableFullname($table)
{
    return sprintf('[%s].[dbo].[%s]', $table->getConnection()->config()['database'], $table->getTable());
}
```
And I call it when build query.
I think that code can become very simple for everybody if it'll be support by library and I create this issue.
Now there is noway to use it without write additional code so developer will use a way to do their process without cross database join, but if it's supported from library, I think many developer will use it.
I'll be happy to create a PR but I don't have knowledge about PostgreSQL and SQLite to do its.

**Comment by othercorey** [comment]
This does not support identifier quoting and is very hard to test. I don't think we are going to add cross-database query support.

If users need that, they can just add custom table names.

**Comment by mcsknp** [comment]
This issue is about table name in query, not about cross database join.
Cross database join is only one advantage of its.
No new test case required for this support, if current testing query is running, it'll run if you add database name to query.

**Comment by ADmad** [comment]
> This issue is about table name in query, not about cross database join.

That's not what you said in your initial post. You said:

> I can join a table from other database if generated query is

**Comment by mcsknp** [comment]
@ADmad Sorry, I will write request description clearly next time.
The content I want to talk about is using full name of table (database name included).
@markstory @othercorey Sorry if you think same as @ADmad

**Comment by markstory** [comment]
I'm still not clear on why using `setTable()` isn't going to work for your use case. It enables you to include the database name in each query. I'm reluctant to add additional methods or change the behavior of the ORM as I don't believe that multi-database setups are that common that we need to include them in the default ORM setup.

**Comment by mcsknp** [comment]
`setTable` is worked as below code in `initialize` of `Table` class
```
$driver = $this->getConnection()->getDriver();
if ($driver instanceof Mysql) {
    $this->setTable(sprintf('%s.%s', $this->getConnection()->config()['database'], $this->getTable()));
} elseif ($driver instanceof Sqlserver) {
    $this->setTable(sprintf('%s.dbo.%s', $this->getConnection()->config()['database'], $this->getTable()));
}
```

But if it will become simply as below if there is `getTableFullname` method in `Driver` class
```
$this->setTable($this->getConnection()->getDriver()->getTableFullname($this));
```
Or nothing to do if table name in query builder was generated with database name.

**Comment by othercorey** [comment]
Closing as we consider this very uncommon. Users will need to implement for their use case.
