### ISSUE TITLE
Uninitialized string offset: 998 on Mailer\Email

### ISSUE THREAD

**Issue by andres-ml** [cakephp/cakephp#14459]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5

(Also happens on 3.8.10)

### What you did
Send an email with line length 998 and some html:

```php
use Cake\Mailer\Message;
use Cake\Mailer\Email;

$line = 'some text <b>with html</b>';
$content = $line . str_repeat('X', Message::LINE_LENGTH_MUST - strlen($line));

$email = new Email();
$email
    ->setTo('example@mail.com')
    ->send($content);
```

### What happened
A Notice is thrown: `Notice Error: Uninitialized string offset: 998` (line `2461` in `Mailer\Email` for 3.x, `1667`in `Mailer\Message` for 4.x)

### What you expected to happen
No notice to be thrown.

I saw this issue was supposedly fixed in #5954 but I guess it got lost somewhere along the way.

It's a very specific case but I'm hitting it 5-10 times/day in production. I also got an `Uninitialized string offset: 1945` (at the same line of code than with 998) once, but I'm not sure where that 1945 comes from.

Here's a full test case for convenience (to reproduce it in 3.x you need to change `Message::LINE_LENGTH_MUST` for `Email::LINE_LENGTH_MUST`):
```php
<?php
namespace App\Test\TestCase;

use Cake\Mailer\Email;
use Cake\Mailer\Message;
use Cake\TestSuite\EmailTrait;
use Cake\TestSuite\IntegrationTestCase;

/**
 * EmailTest class
 */
class EmailTest extends IntegrationTestCase
{

    use EmailTrait;

    /**
     * 
     */
    public function testWrapping()
    {
        $line = 'some text <b>with html</b>';
        $content = $line . str_repeat('X', Message::LINE_LENGTH_MUST - strlen($line));

        $email = new Email();
        $email
            ->setTo('example@mail.com')
            ->send($content);
    }
    
}
```

**Comment by ADmad** [comment]
Thank for the test case to reproduce the issue. PRs up for 3.x and 4.x.
