### ISSUE TITLE
RFC ORM: Add support to string aggregation

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#14455]
Hi folks !
Well, since Cake 4.1 will adopt [window functions](https://github.com/cakephp/docs/pull/6527), I think the timing would be very good to add a very useful feature adopted by all major SGBDs in the last years:

- Mysql: http://sqlfiddle.com/#!9/146217/3
- Postgres:  http://sqlfiddle.com/#!17/fb46f/1/0
- SQLite: http://sqlfiddle.com/#!7/fb46f/1
- SQLServer 2017 >=: http://sqlfiddle.com/#!18/2cb0e/5 

As you can see, there are two different syntaxes: **STRING_AGG** and **GROUP_CONCAT**, this [article ](https://database.guide/mysql-group_concat-vs-t-sql-string_agg/)has a very good comparison.

An usage on Cake ORM would be something like:

```php
$q = $this->Classes->find();
$q
    ->select(['description', $q->func()->strAgg('name')])
    ->innerJoinWith('Students')
    ->groupBy('description');
```

This could be very useful to produce a fast and simple query for reports and similars

* [x] enhancement
* [x] feature-discussion (RFC)

**Comment by dereuromark** [comment]
@celsowm Are you interested to make a PR against 4.next branch?

**Comment by celsowm** [comment]
Sorry my ignorance, but what is PR?

**Comment by dereuromark** [comment]
Pull Request (some call it merge request). A change as seen in the tab above.

**Comment by celsowm** [comment]
Ah okay, hehe. I can try if you guys give me some tipos on which classes I need to add new methods

**Comment by jimbo2150** [comment]
Working on this, should have a PR in the next day.

**Comment by dereuromark** [comment]
@jimbo2150 Are you interested in finishing the PR https://github.com/cakephp/cakephp/pull/14620 ?
Lets continue the discussion there.
