### ISSUE TITLE
Documentation for validationDefault has incorrect definition

### ISSUE THREAD

**Issue by SharonGilmore** [cakephp/cakephp#14451]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: n/a

### What you did
I was trying to declare a validationDefault function.  I did: 
`public function validationDefault(Validator $validator)`
which is what the documentation at https://book.cakephp.org/4/en/core-libraries/validation.html#adding-validation-providers seems to say.

### What happened
Got the following error:
`Fatal error: Declaration of App\Model\Table\UsersTable::validationDefault(Cake\Validation\Validator $validator) must be compatible with Cake\ORM\Table::validationDefault(Cake\Validation\Validator $validator): Cake\Validation\Validator in /Applications/MAMP/htdocs/src/Model/Table/UsersTable.php on line 26`

### What you expected to happen
The correct declaration in the documentation should be:
`public function validationDefault(Validator $validator): Validator`

**Comment by dereuromark** [comment]
Can you make a PR to fix this?

**Comment by SharonGilmore** [comment]
Sorry, I don't know what PR means?

**Comment by dereuromark** [comment]
Pull Request
towards https://github.com/cakephp/docs/

**Comment by SharonGilmore** [comment]
Sorry, I don't know how to do that.  Happy to do it if someone tells me what to do.

**Comment by dereuromark** [comment]
One just goes to the repo and makes a chance, proposed a PR as I now did:
https://github.com/cakephp/docs/pull/6582
