### ISSUE TITLE
4.0.5: ConsoleOutput being retained through multiple executions

### ISSUE THREAD

**Issue by mentisy** [cakephp/cakephp#14468]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.0.5
* Platform and Target: Testing console commands in a Windows environment

### What you did
[Look at this **gist** to understand my problem more easily](https://gist.github.com/mentisy/ed0349197a76141447eb817314a7b2fe)
I've created this gist to reproduce my problem. I have created a command that will:
* Normal output `First` when running the command `bin/cake test first`.
* Error output `Second` when running the command `bin/cake test second`.`

This works as expected when you perform the commands using the CLI. The gist linked above also contains my test code. 

1. Run first execution `bin/cake test first`. It should then assert that output contains `First` and error is empty.
2. Run second execution `bin/cake test second`. It should then assert that output is empty and error contains `Second`. 

### What happened
**From above numbering**
1. The first test passes. It successfully asserts that output contains `First` and error is empty
2. The second test does **not** pass. It successfully asserts that error contains `Second`, but it does not successfully assert that output is empty. Output contains `First`. The output is being retained from the first execution.

### What you expected to happen
I expected all my assertions to pass.

This problem occurred after upgrading from 4.0.4 to 4.0.5. I've traced the origin of this issue to [this commit](https://github.com/cakephp/cakephp/commit/d2694e2f1b6fb98892557d421be9fbe2be570958).

From looking at the code, it seems like it's retaining the previous ConsoleOutput in the entire test method. So within the test method, all output will be concatenated. Before 4.0.5 it created a new ConsoleOutput instance on every execution.

When I move the second `$this->exec()` to another test method, all tests pass.

Is doing multiple `$this->exec()` inside one test method considered bad practice? My problem occurred in a Shell, where I have a test method for each sub-command. With Commands only doing one thing, however, I could see it be OK to do several test methods for different execution variations.

**Comment by dereuromark** [comment]
You are using multiple calls in integration testing. That is not how this is designed to work.
Use only one test...() per invocation of such a high level access.
Otherwise exactly these side effects appear.

These are not unit tests, but integration tests.

**Comment by mentisy** [comment]
Alright, I'm not that experienced in testing. I should probably refactor my tests then. The tests failing are for shells, which are deprecated, so would need to be refactored to commands some time anyway.  

Thanks @dereuromark

**Comment by dereuromark** [comment]
It should still work for shells the way outlined.
If you can confirm that using separate runs, you can close this.

**Comment by mentisy** [comment]
Yes, Shells behaves exactly like Commands. So doing like you described would solve it independent on how which you use.
