### ISSUE TITLE
Calling any controllerls action from view file in cakephp 3.8

### ISSUE THREAD

**Issue by henryuu** [cakephp/cakephp#14460]
Below is the code I was using in cakephp 1.3 for calling action from controller.
`$proactive_chart_data = $this->requestAction("/health/group_consult_data_bootstrap/".$company_id, array(‘return’));
`
Now I am upgrading my same website to cakephp 3.8.
Is there any simplest way to use above code for calling action from controller ?
Please help.

**Comment by garas** [comment]
`requestAction()` is deprecated. You should refactor to use View Cells or Components instead.

**Comment by henryuu** [comment]
Thanx. How to use via components, can you please summerize something in detail ?

**Comment by garas** [comment]
Follow instructions at https://book.cakephp.org/3/en/controllers/components.html#creating-a-component.

Move code from `HealthController::group_consult_data_bootstrap()` to method of your component, then call it from controller actions.

**Comment by henryuu** [comment]
Okay, Thanx. But I am upgradiing cakephp. So I can not do that, Its very large website. and Its already in use everywhere. Thanx for the solution. Is there any other way, such that to minimize my rework ?

**Comment by ADmad** [comment]
As stated above please use one of the help forums.
