### ISSUE TITLE
Named windows and non-aggregate window functions

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#14469]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x

---------------------------------

Continuation from https://github.com/cakephp/cakephp/issues/14080

Seeing the first implementation of window function support, I'm wondering whether there are any plans for adding support for [**named windows**](https://dev.mysql.com/doc/refman/8.0/en/window-functions-named-windows.html)? Looking at the current state, it would probably not possible to implement without breaking changes.

To be able to implement named window usage, it would need to be possible to generate `OVER` clauses like `OVER window_name` and `OVER (window_name further_window_spec_clauses...)`, and it it would need to be possible to generate a window specification without an over clause, so that it can fit in the `WINDOW` clause, like `WINDOW window_name AS (window_spec_clauses...)`.

Also would you share my concern that the fact that all window functions that the builder can create are implemented as `AggregateExpression`, could be a little misleading, and perhaps awkward to use, given that not all window functions actually are aggregate functions, like `RANK()`, `ROW_NUMBER()`, `LAG()`, `LEAD()`, etc...?

**Comment by othercorey** [comment]
For named windows, I am not sure if we want to support extending the named window clause. That might be confusing interface for users who don't know there are special limitations. I think it would be minimal overhead for users to simply create the full window they want and name it.

Implementing named windows is something we would like to do.

**Comment by othercorey** [comment]
For the concern about AggregateExpression being used for all window functions, we found this was a user-experience compromise.

We discussed creating separate FunctionsBuilder versions for aggregate functions/window functions, but found that to be confusing for the user. We would have to duplicate previous functions and enforce that the user call the right builder.

For now, we chose to use a single FunctionsBuilder with an `aggregate()` helper. If we added a `window()` helper, that would feel more confusing than helpful as it suggests you can't use aggregate functions.

So, generally, while AggregateExpression might have options in the future that don't strictly belong to a handful of window functions, it seems like the least confusing compromise.

**Comment by othercorey** [comment]
Named windows ended up being easier to implement with full support. Users can chain windows freely as long as their database supports it.

**Comment by ndm2** [comment]
That's great news 👍

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/cakephp/pull/14536
