### ISSUE TITLE
Request to change package "zendframework/zend-diactoros" to "laminas/laminas-diactoros" in CakePHP version 3.8

### ISSUE THREAD

**Issue by vivekpipaliya** [cakephp/cakephp#14487]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11

I see version 3.8.11 is still using zendframework/zend-diactoros and that is abandoned

It is better to update CakePHP 3.8.* to change package to "laminas/laminas-diactoros". I know this is already fixed in CakePHP 4.* but not all developers can upgrade to version 4.0 as it has breaking changes.

![image](https://user-images.githubusercontent.com/60814309/79859909-67cafc80-83ef-11ea-8234-f30267ade9d1.png)

**Comment by ADmad** [comment]
Expect for that warning there are no issues using the `zendframework` packages. Switching to `laminas` could actually cause problems and break existing applications, the class aliasing they have added isn't perfect.

**Comment by dereuromark** [comment]
It could make sense to fix this in 3.next
To allow for this minor to be compatible for possible fixes coming in.
https://github.com/cakephp/cakephp/blob/3.next/composer.json#L38

**Comment by burzum** [comment]
Well, I would prefer https://github.com/Nyholm/psr7 it's fast, it's small and the guy who developed it is working for Mailgun I think, he worked on their php client lib as well and is using it there as well.

**Comment by dereuromark** [comment]
For moving forward in 5.x this can be discussed, but for 3.9 to be in sync with 4.x we should stick to the same replacement (1:1 other than naming).

**Comment by markstory** [comment]
@burzum Switching to a different PSR7 library will certainly break compatibility.

**Comment by markstory** [comment]
Fixed in #14508 for 3.9
