### ISSUE TITLE
Can't find all translations for a single entity

### ISSUE THREAD

**Issue by webme** [cakephp/cakephp#14480]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.6 Strawberry.
* Platform and Target: Apache 2.4.29, Ubuntu 18.04.3, PHP 7.4.3, MySQL 8.0.19

### What you did
```
// In app.php
'App' => [
	'defaultLocale' => 'en',
	...
]
```
```
class CategoriesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('categories');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Translate', [
            'fields' => ['name'],
            'translationTable' => 'CategoriesI18n',
        ]);

        $this->belongsToMany('Videos', [
            'foreignKey' => 'category_id',
            'targetForeignKey' => 'video_id',
            'joinTable' => 'categories_videos',
        ]);
    }	
}
```
```
class CategoriesController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $categories = $this->Categories->find('translations')
            ->disableHydration()
            ->toArray();

        debug($categories);

        $this->set(compact('categories'));
    }
}
```

### What happened
```
[
	(int) 0 => [
		'id' => (int) 1,
		'name' => 'Family',
		'slug' => 'family',
		'position' => (int) 36,
		'identifier' => '73',
		'video_count' => (int) 18679,
		'active' => true,
		'_i18n' => []
	],
	(int) 1 => [
		'id' => (int) 2,
		'name' => 'Horror',
		'slug' => 'Horror',
		'position' => (int) 50,
		'identifier' => '138',
		'video_count' => (int) 998154,
		'active' => true,
		'_i18n' => []
	]
]
```

### What you expected to happen
```
[
	(int) 0 => [
		'id' => (int) 1,
		'name' => 'Family',
		'slug' => 'family',
		'position' => (int) 36,
		'identifier' => '73',
		'video_count' => (int) 18679,
		'active' => true,
		'_i18n' => [
			(int) 0 => [
				'id' => (int) 1,
				'locale' => 'de',
				'model' => (int) 1,
				'foreign_key' => (int) 1,
				'field' => 'name',
				'content' => 'Familie'
			],
			(int) 1 => [
				'id' => (int) 2,
				'locale' => 'fr',
				'model' => (int) 1,
				'foreign_key' => (int) 1,
				'field' => 'name',
				'content' => 'Famille'
			],
		],
	],
	(int) 1 => [
		'id' => (int) 2,
		'name' => 'Horror',
		'slug' => 'Horror',
		'position' => (int) 50,
		'identifier' => '138',
		'video_count' => (int) 998154,
		'active' => true,
		'_i18n' => [
			(int) 0 => [
				'id' => (int) 3,
				'locale' => 'de',
				'model' => (int) 1,
				'foreign_key' => (int) 2,
				'field' => 'name',
				'content' => 'Grusel'
			],
			(int) 1 => [
				'id' => (int) 4,
				'locale' => 'de',
				'model' => (int) 1,
				'foreign_key' => (int) 2,
				'field' => 'name',
				'content' => 'Horreur'
			],
		],
	]
]
```

I want to find all translations for a single entity as described in the documentation.

Unless I am mistaken, the result returned is not what is expected. I even did a new installation of CakePHP to remove the doubt and it is the same result.

I noticed that the translations are not retrieved when I am on the default language `en`

When i change the language in the action `$this->Categories->setLocale('fr');` the translations are retrieved, but not the default language `en`

To work around the problem and recover all the languages, I put a false locale which does not exist `$this->Categories->setLocale('fake');` and there I get the entity with the default language and all translations

**Comment by ADmad** [comment]
By design the TranslateBehavior expects fields for default locale are saved in the primary table. Only non default locales go into the translation table. Setting the default locale for table to `false` or dummy locale is the way to achieve what you want.

You can read more details here https://github.com/cakephp/cakephp/issues/13756#issuecomment-542483802

**Comment by webme** [comment]
Hello and thank you for your reply.
I think we misunderstood or I misspoke.

To be brief, is it normal that this code does not return translations
```
$categories = $this->Categories
            ->find('translations')
            ->disableHydration()
            ->first();
```

But in this code returns the translations

```
$categories = $this->Categories
            ->find('translations')
            ->disableHydration()
            ->where(['active' => true])
            ->first();
```

The difference between the two is the `WHERE clause` 

I created a github repository if you want to test it.
https://github.com/webme/cakeTestTranslations

Initialize Tables: /config/schema/categories.sql
While create database test if not exists, create tables categories and categories_i18n
username: root
password: root

The base path  '/' is connected to Categories controller

You can access it to see the result directly

Thank you.

**Comment by othercorey** [comment]
@ADmad Anything to do for this?

**Comment by ADmad** [comment]
Not sure, I haven't tried reproducing the issue. The repo provided by the user is also gone now.

**Comment by othercorey** [comment]
@webme Do you still have the schema details?

**Comment by webme** [comment]
Hello,

Yes the repository has been deleted.
I tried to reproduce the problem but was not successful.

I then looked to see if the deposit could be restored, bingo, the deposit became accessible again.

I installed the repository to test, the problem is still present. I also tried on a recent version with the same Schema it's the same. 

I didn't look for more than that, I think there is something with the `referenceName`

**Comment by othercorey** [comment]
> I didn't look for more than that, I think there is something with the `referenceName`

Why use model name `1`?

**Comment by webme** [comment]
Joins are faster especially for tables with several million records, such as the `videos` table which has more than 2 million records and the `videos_i18n` table with 12 languages. 
Besides, it would be a good idea if we use a dedicated translation table, not to use the 'referenceName' because it is useless in queries.

**Comment by othercorey** [comment]
You might be interested the new Shadow Table strategy. Unfortunately, this was missing from migration notes.

https://book.cakephp.org/4/en/orm/behaviors/translate.html#translation-strategies

**Comment by webme** [comment]
Yes, that's what we're currently using in the new version, we have videos_translations, categories_translations, etc.

**Comment by othercorey** [comment]
FYI, this issue happens due to no `order` clause.
