### ISSUE TITLE
4.1: urlFromPath in general?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14494]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1+

### What you did

Looking more into what we are currently doing in 4.1 and fromPath usability improvements:

I use a lot of URLs everywhere (preferably always array to be agnostic, never the final routed one!):

    return $this->redirect(
        ['plugin' => 'Messaging', 'controller' => 'Conversations', 'action' => 'index']
    );

in config (auth):

    'loginAction' => [
        'controller' => 'Account', 'action' => 'login', 'prefix' => false, 'plugin' => false
    ],

or in tests:

    $this->get(
        ['prefix' => 'Admin', 'plugin' => 'MyPlugin', 'controller' => 'MyController', 'action' => 'myAction']
    );

### What happened
Right now you need to manually write those, or use copy and paste.

### What you expected to happen
Given, that we can typehint/autocomplete the string paths from a generated list of available actions, it would be nice if we could generate the array from the string path.

What if we created similar methods we did before for collection(), __() and more?
Syntactic sugar that can do that?

    function url(string $path): array {
        return ...
    }

And then we could just inject that in any (even custom) method we need it:
```php
// controller and alike
return $this->redirect(
    url('Messaging.Conversations:index')
);

// config or custom usage
'loginAction' => url('Account::login'],

// testing
$this->get(
    url('MyPlugin.Admin/MyController::myAction')
);
```
The non-declared parts automatically become false (prefix/plugin).

It stays fully optional, would make the rest of us though 300% faster and more productive.
It only needs one meta directive to make this possible for all possible use cases, so we don't need tons of more ways to get this implemented throughout the whole system.

Naming of this global function?
- url()
- urlFromPath()
- ?

Thoughts? Alternatives?

**Comment by ADmad** [comment]
I am onboard for having a `url()` method, I too have thought of having the same in the past but never got around to proposing/implementing it.

**Comment by ADmad** [comment]
Though I would prefer being able to pass other URL parts too to the function, not the path string.

**Comment by dereuromark** [comment]
You are absolutely right, the 2nd $params array must not be forgotten here to make this able to give us back a proper complete array form.

**Comment by dereuromark** [comment]
PR open.
