### ISSUE TITLE
3.x | LocatorInterface only allows getting Tables?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#14495]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11
* Platform and Target: PHP 7.4.1

## What you found
Why does the `\Cake\ORM\Locator\LocatorInterface` stipulate that the `get()` method must return `\Cake\ORM\Table` and not `\Cake\Datasource\RepositoryInterface`?

If I was to implement this interface into my own locator to find my custom repositories it would 
 fail the interface? Unless my custom repository classes also extended `\Cake\ORM\Table`?

The class `\Cake\ORM\Locator\TableLocator` does return `\Cake\ORM\Table` as its name implies. So it seems to me the interface has been missed.

## Suggested change
The interface be updated to return an interface, allowing more flexibility.

I can open a pull request to update this if needed.

## References
Follows on from #12014
https://github.com/cakephp/cakephp/blob/3.8.11/src/ORM/Locator/LocatorInterface.php#L37-L44

**Comment by markstory** [comment]
A pull request to update the interface would be great!

**Comment by dereuromark** [comment]
Wouldnt that have to go into 4.next or even 5.0?
I can imagine this to be the current way as RepositoryInterface is in Datasource and very abstract, whereas the whole TableLocator and the ORM package stay in ORM specific ways.

**Comment by davidyell** [comment]
I will close this, as I have opened a pull request for discussion.
