### ISSUE TITLE
Plugin::bootstrap is not called, version 4.0.6

### ISSUE THREAD

**Issue by thomasherisson-scaledev** [cakephp/cakephp#14505]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.6
* Platform and Target: PHP 7.2

### What you did
When i load a plugin in my Application.php, Plugin::bootstrap is not called.

Application::bootstrap : 
`
$this->addPlugin('MyPlugin', [
                'routes' => true,
                'bootstrap' => true,
                'console' => true,
                'middleware' => true,
            ]);
`

**Comment by markstory** [comment]
How can someone reproduce this? I use several plugins and they all have their bootstrap hooks triggered. Have you made sure that your plugin class is included in your project's autoloader?

**Comment by dereuromark** [comment]
Also, it would be nice to see the code of this bootstrap content. Maybe there is a typo.

**Comment by thomasherisson-scaledev** [comment]
Hi,

I have check the composer autoloader, and after a dumpautoload it work !
Thanks, and i close this issue.
