### ISSUE TITLE
TreeBehavior Extra query

### ISSUE THREAD

**Issue by yarkm13** [cakephp/cakephp#14503]
Why fire extra query if `$entity` passed already of type `\Cake\Datasource\EntityInterface` and already have `lft` & `rght` fields?

https://github.com/cakephp/cakephp/blob/190f3089c26580192fa3673fa51ee8f393997db8/src/ORM/Behavior/TreeBehavior.php#L997-L1011

May be it make sense to check if `lft` & `rght` is present and is not dirty?

**Comment by saeideng** [comment]
because entity position could be change after fetching and during your code
and an extra query avoids from possible side effect
