### ISSUE TITLE
Router arguments disambiguation

### ISSUE THREAD

**Issue by yarkm13** [cakephp/cakephp#14501]
This is a

* [x] enhancement
or
* [x] documentation

* CakePHP Version: HEAD
* Platform and Target: n/a

### What you did

    // routes.php
    $builder->connect('/test/{id}', ['controller' => 'Some', 'action' => 'paramsTest', 'sometype'], ['pass' => ['id']]);

    // SomeController.php
    public function paramsTest($type, $id)
    {
        printf('$type: %s, $id: %s', $type, $id);die;
    }

### What happened
If i will go open `/test/12` that code will produce `$type: 12, $id: sometype` so `pass` will be processed first and then `sometype` added to the end.

### What you expected to happen
I think arguments order is little bit disambiguous and also there is no mention about order in such case. For me seems logical if `sometype` will be passed first and than `id` added.

It is not a bug but need some clarification i think. Docs have a little about order:

    // Define the route elements in the route template
    // to pass as function arguments. Order matters since this
    // will simply map "{id}" to $articleId in your action

To make my code more clear I have to do something like

    $builder->connect('/test/{id}', ['controller' => 'Some', 'action' => 'paramsTest', 'type' => 'sometype'], ['pass' => ['type', 'id']]);

And then it will work as expected.

**Comment by markstory** [comment]
We can't change the behavior to the what you were expecting as we'd break a lot of existing applications.

I can try to clarify the documentation as I agree it could be clearer.

**Comment by markstory** [comment]
Closing as the docs have been updated.
