### ISSUE TITLE
Use of <code> in dev_error header causes unreadable title

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14510]
The `<code>` tags generated by `Debugger::formatHtmlMessage()` cause an unreadable dev_error header.

With code tags:
![image](https://user-images.githubusercontent.com/24221186/80484405-4a30f200-891d-11ea-9f5e-187e7836f72d.png)

Without code tags:
![image](https://user-images.githubusercontent.com/24221186/80484346-34233180-891d-11ea-9926-4879d0c0822c.png)

**Comment by markstory** [comment]
This smells of flexbox I'll get it fixed.
