### ISSUE TITLE
custom connection managaer query in cakephp 3

### ISSUE THREAD

**Issue by henryuu** [cakephp/cakephp#14517]
In older version for cakephp 1.3 ,when using custom query like below I was getting result in array of defined model or table name, like below
$query = "SELECT `survey_responses`.`created`, `survey_question_options`.`name` FROM `survey_responses` LEFT JOIN `survey_question_options` ON `survey_responses`.`id` = `survey_question_options`.`survey_response_id`";
$res = $this->ChallengeResponse->query($query);
result is 

Array
(
    [0] => Array
        (
		['survey_responses'] => Array
		(
            [created] => 2020-04-17 07:10:52
		)
		['survey_question_options'] => Array
		(
            [name] => 'test'
		)
        )

    [1] => Array
        (
		['survey_responses'] => Array
		(
            [created] => 2020-04-18 07:10:52
		)
		['survey_question_options'] => Array
		(
            [name] => 'test2'
		)
        )
)

but using connection manager in cakephp 3.x I am getting result like below

Array
(
    [0] => Array
        (
            [created] => 2020-04-17 07:10:52
			[name] => 'test'
		)
		

    [1] => Array
        (
            [created] => 2020-04-18 07:10:52
			[name] => 'test2'
		)
)

---------------------
Any idea how can i get result like above, so getting result with table array..
Actually I am upgrading cakephp from 1.3 to 3.x. So It may help me, so that I need not change at so many places.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
