### ISSUE TITLE
Improve error message for EmailTrait::MailContains

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#14518]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.6

If the assert fails, I get a message similar to this
`Failed asserting that 'my text' is in an email.
`

It would be great, If I could see the actual message that was available, like:
`Failed asserting that 'my text' is in an email. Was: 'your text'
`

**Comment by dereuromark** [comment]
The main issue here could be the potential length of the content.
Making the error message then hard to read across hundreds of lines.

**Comment by mrothauer** [comment]
Is there another way to debug / log the message during the test? I was not able to get the email text.

**Comment by dereuromark** [comment]
We could also truncate the message if it exceeds a certain limit.
Do you want to make a PR here?

**Comment by mrothauer** [comment]
Truncating is a good idea. Yes, I'll make a PR.
