### ISSUE TITLE
Add support for date/time interval

### ISSUE THREAD

**Issue by jimbo2150** [cakephp/cakephp#14528]
This is a (multiple allowed):

* [ ] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

It is difficult to produce an interval to add/subtract dates/times within the database such as:
```sql
SELECT '2020-04-17 02:03:02.21' + INTERVAL 2 YEAR + INTERVAL 3 DAY;
```

PR: #14527

**Comment by dereuromark** [comment]
The PR itself is fine :) The ticket would only be needed if you didn't start yet a PR and further discussion is needed before that.
