### ISSUE TITLE
Paginator skipping URL params when using scope

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#14521]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.6
* Platform and Target: WAMP

### What you did
I prepare multiple paginations with `scope` param in `$paginate` and `paginate()`.

### What happened
When I use scoped pagination on detail page with URL params (like `/products/detail/[productId]`), then pagination links (sort, page, etc.) skipping `productId`. 

It' looks like this:  /products/detail/?scopeName&[sort]...

I think the problem is here: https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L581-L584

### What you expected to happen
Pagination links (sort, page, etc.) should have `productId` param in URL.

Should looks like this:  /products/detail/**532**?scopeName&[sort]...

**Comment by markstory** [comment]
How are you calling Paginator->options()?

**Comment by kicaj** [comment]
I’m not calling options.

**Comment by markstory** [comment]
@kicaj Yes. The line you linked to is looking in the data set by options()

**Comment by kicaj** [comment]
@markstory You mean `options` as 3rd param in `sort` method? If yes, this works. But what when I have many `sort` methods in one page? Can I use something like global, maybe `$this->Paginator->options();`?

**Comment by kicaj** [comment]
Maybe question is, why `sort()` method don't use `options.url` config param?

**Comment by markstory** [comment]
I was referring to `Paginator->options()` method to set URL parameters up. I would have expected this line https://github.com/cakephp/cakephp/blob/a88035df28e8a6d1a8dc51e8e3aa7fb423e8ce36/src/View/Helper/PaginatorHelper.php#L489 to handle using the scope when the `model` option is set.

**Comment by kicaj** [comment]
How? It's documented anywhere?

**Comment by markstory** [comment]
This [example](https://book.cakephp.org/4/en/views/helpers/paginator.html#paginating-multiple-results) shows using the model option when paginating multiple models.

**Comment by kicaj** [comment]
Still the same...
So, I should show my code for You.

**ProductsController::detail($productId):**
```
...
$this->paginate = [
    'ModelOne' => ['scope' => 'one'],
    'ModelTwo' => ['scope' => 'two'],
];

$one = $this->paginate($this->ModelOne, ['scope' => 'one'']);
$two = $this->paginate($this->ModelTwo, ['scope' => 'two']);

$this->set(compact('one', 'two'));
...
```

**templates/Products/detail.php:**

*Solution 1*
```
$this->Paginator->defaultModel('ModelOne');
echo $this->Paginator->sort('field_name', 'Field name'); 
echo $this->Paginator->sort('field_name', 'Field name, ['model' => 'ModelOne']); 
```

*Solution 2*
```
$this->Paginator->options(['model' => 'ModelOne']);
echo $this->Paginator->sort('field_name', 'Field name'); 
echo $this->Paginator->sort('field_name', 'Field name, ['model' => 'ModelOne']); 
```

All above solutions, generate incorrect URL: `/products/detail?one[sort]=field_name...`, because `productId` value is missing!

Correct URL should look like this: `/products/detail/123?one[sort]=field_name...`.

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce this problem.

**Comment by markstory** [comment]
I was able to reproduce your problem and the solution is to use `options()` correctly.

```php
$this->Paginator->options([
    'url' => [
        'one' => [
            '1234',
            '?' => ['one' => 'value'],
        ],
        'two' => [
            '5678',
            '?' => ['two' => 'value'],
        ],
    ],
]);
```

Where `one` and `two` are your scope names. This usage pattern isn't in the docs so I'll get that added.

**Comment by kicaj** [comment]
Sorry. I can't see the difference.
What with passed arguments?

**Comment by markstory** [comment]
I was using passed arguments to test out this problem as I didn't have routes that used routing parameters.

**Comment by kicaj** [comment]
You're right, everythings works.
