### ISSUE TITLE
4.1 - Add closure support to window expression partition and order clauses

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14537]
We should allow closures for `WindowInterface::partition()` and `WindowInterface::order()` like other query builders.

**Comment by othercorey** [comment]
@ndm2 I don't understand how to add expression support for frames. Can you link me to some documentation?

**Comment by ndm2** [comment]
Sure, see the frame bounds description here:

* https://dev.mysql.com/doc/refman/8.0/en/window-functions-frames.html
* https://www.postgresql.org/docs/12/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS

MySQL and Postgres accept intervals additionally to numbers, ie you can do something like:

```sql
RANGE BETWEEN INTERVAL 1 DAY PRECEDING AND INTERVAL 10 DAY FOLLOWING
```
```sql
RANGE BETWEEN '1 day' PRECEDING AND '10 days' FOLLOWING
```

Being able to pass a transformable expression that translate to syntax like `INTERVAL n unit` or `n unit` respectively would come handy.

**Comment by othercorey** [comment]
Ah, ok. I thought you meant something else. There is a PR open for IntervalExpression which I'm waiting to see what happens. 

Adding interval expression support is something we should add, but was out of scope of the previous PR.

**Comment by jimbo2150** [comment]
That is what is being worked on in #14527. Do you need just the interval or would you like me to add the ability to include a prefix/suffix so that BETWEEN/FOLLOWING can be added?

**Comment by othercorey** [comment]
> That is what is being worked on in #14527. Do you need just the interval or would you like me to add the ability to include a prefix/suffix so that BETWEEN/FOLLOWING can be added?

No, that would not be part of IdentifierExpression.

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/cakephp/pull/14581
