### ISSUE TITLE
Cannot store "false" values as a hidden field in a reliable way

### ISSUE THREAD

**Issue by ttm-tt** [cakephp/cakephp#14548]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Debian Buster

### What you did
See #5639 
I have a column declared as "TINYINT(1) DEFAULT 0 NOT NULL". When I store the value "false" as a hidden field in a form it is read back and converted to NULL, which cannot be written back into the table.

### What happened
I get a database error indicating that NULL instead of false was written back

### What you expected to happen
That the value is converted back to false and written back as such instead of NULL

"Before you open an issue, please check if a similar issue already exists or has been closed before."
Yes, I did :)

In my form I write
`echo $this->Form->control("<table>.<column>", "hidden")`
which produces the output
`<input id="..." type="hidden" name="...">`
Note, that there is no `value="..."` in the input field.
On submit, the POST parameter is empty, which translates to an empty string, which is marshaled as NULL in patchEntity.

In my opinion, we have 4 different values of bool: true, false, and "not a value" aka null, and "not specified". A hidden field should somehow be able to distinguish between them, though I have no idea how to do that with the last 2 (null and undefined).

**Comment by dereuromark** [comment]
I agree that at least for a not null column the empty string must default to false instead of null here.
As @markstory once said:

> False is '' in string form.

And the null conversation would just create a DB error here.

**Comment by ADmad** [comment]
> ..at least for a not null column...

The database type classes have no info about the table schema, hence marshalling values based whether column is nullable or not is not possible.

**Comment by dereuromark** [comment]
That may very well be the case, here then the discussed issue of auto-transforming null to false of the closed issues and my workaround of Nullable behavior applies.
Null just doesn't make sense as marshaled input coming from empty string (`''`), or at least not as final data reaching the database. Intuitively, this should set the column to `false` = `0` here for DB.

**Comment by ADmad** [comment]
> For boolean true/false(1/0): Null just doesn't make sense as marshaled input coming from empty string ('')

Marshalling empty string to `null` would make sense if the column was nullable. One can have nullable boolean columns. So we need to think of a solution which works for both nullable and non-nullable columns.

One way to deal with this is make the FormHelper convert `false` to `0` for boolean fields. Making `ContextInterface::val()` do that could be considered, since it does have the schema info.

**Comment by dereuromark** [comment]
That sounds like a fair compromise.
I think we had similar issues also in some other place before, where a `false` => `''` => null aka nothing then would result in an undesired value in the end.

If we scope this to booleans, this should be without side effects then.
