### ISSUE TITLE
'OR' conditions are ignored if multiple

### ISSUE THREAD

**Issue by marcheimendinger** [cakephp/cakephp#14547]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11
* Platform and Target: Apache/2.4.41 (Unix) and 10.4.6-MariaDB

### What you did
In a controller I'm building a query using `->where()` with two `OR` to get something like :
```sql
WHERE
  (
    (condition1 AND condition2) OR
    (condition3 AND condition4)
  ) AND
  (condition5 OR condition6)
```

So in PHP I did :
```php
->where([
    'OR' => [
        [
            condition1,
            condition2
        ],
        [
            condition3,
            condition4
        ]
    ],
    'OR' => [
        [condition5],
        [condition6]
    ]
])
```

### What happened
The whole first `OR` is ignored in the generated SQL query, which looks like this :
```sql
WHERE 
  (condition5 OR condition6)
```

### What you expected to happen
The complete query should be generated. There is no mention in the documentation of a limiting to only one `OR` clause.

**Comment by garas** [comment]
It is not issue with CakePHP.

You are using same array key `'OR'` and PHP uses value of the last one.

Result of `['x'=>1, 'x'=>2]` is `['x'=>2]`.

**Comment by ADmad** [comment]
If you set the same array key again in PHP, it will overwrite the key.

Use
```php
->where([
    'OR' => [
        [
            condition1,
            condition2
        ],
        [
            condition3,
            condition4
        ]
    ],
    ['OR' => [
        [condition5],
        [condition6]
    ]]
])
```

**Comment by marcheimendinger** [comment]
Mmm I see. Thanks for the quick replies.
