### ISSUE TITLE
Missing CSRF token body

### ISSUE THREAD

**Issue by iarcas-com-br** [cakephp/cakephp#14550]
* CakePHP Version: v4.0.7 .
* Platform and Target: ubuntu (localhost - .local), mysql.

### Log
2020-05-06 03:43:01 Error: [Cake\Http\Exception\InvalidCsrfTokenException] Missing CSRF token body in /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php on line 275
Stack Trace:
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:134
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:77
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:138
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:162
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:119
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php:60
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /home/sites/my_devices/vendor/cakephp/cakephp/src/Http/Server.php:90
- /home/sites/my_devices/webroot/index.php:40

Request URL: /users/login?redirect=%2Fusers%2Fadd
Referer URL: http://iarcas_devices.local/users/login?redirect=%2Fusers%2Fadd
Client IP: 127.0.0.1

### /.../cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php on line 270

```
debug($request->getHeaderLine('X-CSRF-Token'));
return:
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 269)
''
```
## Debug $request->getHeaders();
```

/src/Http/Middleware/CsrfProtectionMiddleware.php (line 269)
[
	'Host' => [
		(int) 0 => 'iarcas_devices.local'
	],
	'Connection' => [
		(int) 0 => 'keep-alive'
	],
	'Content-Length' => [
		(int) 0 => '359'
	],
	'Cache-Control' => [
		(int) 0 => 'max-age=0'
	],
	'Upgrade-Insecure-Requests' => [
		(int) 0 => '1'
	],
	'User-Agent' => [
		(int) 0 => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/81.0.4044.129 Chrome/81.0.4044.129 Safari/537.36'
	],
	'Origin' => [
		(int) 0 => 'http://iarcas_devices.local'
	],
	'Content-Type' => [
		(int) 0 => 'application/x-www-form-urlencoded'
	],
	'Accept' => [
		(int) 0 => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
	],
	'Referer' => [
		(int) 0 => 'http://iarcas_devices.local/users/login?redirect=%2Fusers%2Fadd'
	],
	'Accept-Encoding' => [
		(int) 0 => 'gzip, deflate'
	],
	'Accept-Language' => [
		(int) 0 => 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7'
	],
	'Cookie' => [
		(int) 0 => 'csrfToken=4bd592fd984ea9b23efa736ede4388e021d0aef73c8ba5245516d1d0; PHPSESSID=lncnr062pk14b12r0som1f3mp6'
	]
]

```

## Template ~/login.php
```
<div class="users form">
   <form method="post" accept-charset="utf-8" action="/users/login?redirect=%2Fusers%2Fadd"><div style="display:none;"><input type="hidden" name="_csrfToken" autocomplete="off" value="4bd592fd984ea9b23efa736ede4388e021d0aef73c8ba5245516d1d0"/></div>				    

...				        
				    
<div style="display:none;"><input type="hidden" name="_Token[fields]" autocomplete="off" value="fc23599c3dea644f7d973005a8edcf0e34ad92cb%3A"/><input type="hidden" name="_Token[unlocked]" autocomplete="off" value=""/><input type="hidden" name="_Token[debug]" autocomplete="off" value="%5B%22%5C%2Fusers%5C%2Flogin%3Fredirect%3D%252Fusers%252Fadd%22%2C%5B%22email%22%2C%22password%22%5D%2C%5B%5D%5D"/></div></form>	
```

## $header empty
```
270        $header = $request->getHeaderLine('X-CSRF-Token');
271        if (hash_equals($header, $cookie)) {
272            return;
273        }
274
275        throw new InvalidCsrfTokenException(__d('cake', 'Missing CSRF token body'));
```

__

Hello, I'm using CakePHP v4.0.7, I got this error (***Missing CSRF token body***)
I'm trying to use Login cakephp-tinyauth, but after going through the form I get the error, from line 275 of the file /vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php

I'snt was able to verify the return that the getHeaderLine ('X-CSRF-Token') try find, on line 270. And not exist X-CSRF-Token in $ request-> getHeaders ().

**Comment by markstory** [comment]
Did you create your form with `$this->Form->create()`? If not your form will be missing the `csrfToken` POST parameter and since it does not contain a header or POST parameter it will fail CSRF token validation.

**Comment by garas** [comment]
You are using form so `$request->getHeaderLine('X-CSRF-Token')` is expected to be empty.

But few lines above it, variable `$body` should contain form data. Does `$body` contains `_csrfToken` key? Does it's value matches value of `csrfToken` cookie?

**Comment by iarcas-com-br** [comment]
Hi @markstory, yes i'm using <?= $this->Form->create(); ?>, see:

```

				<div class="users form">
				    <?= $this->Flash->render() ?>
				    <?= $this->Form->create(); ?>
				    <fieldset>
				        <legend><?= __('Legenda do form') ?></legend>
				        <?= $this->Form->control('email', ['required' => true]) ?>
				        <?= $this->Form->control('password', ['required' => true]) ?>

				    </fieldset>
				    <?= $this->Form->submit(__('Login')); ?>
				    <?= $this->Form->end() ?>
				</div>

``` 


thank you

**Comment by iarcas-com-br** [comment]
Hi @garas in line 271 there is the *hash_equals ($ header, $ cookie)* comparison of the header and the cookie. But as they are different it does not enter this condition, falling in error InvalidCsrfTokenException of line 275.

thank you

**Comment by garas** [comment]
@iarcas-com-br I've asked about `$body` at line 262.

`$post` at line 264 should contain the token.

https://github.com/cakephp/cakephp/blob/845b307199afa8a248a5a146b532790a354a6eff/src/Http/Middleware/CsrfProtectionMiddleware.php#L262-L268

**Comment by iarcas-com-br** [comment]
@garas, I'm sorry.

Just generated $ doby content:

``` 
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 261)
[
	'_csrfToken' => '20b005240b389e3e84e21fc30f03fb9f1b7e3d3c8abc409740b0e69c',
	'email' => '1@12.com',
	'password' => '1',
	'origins' => '{"redirect":"\/users\/add"}',
	'_Token' => [
		'fields' => '7a45ed408c23fa5c26bf1b1ea9b634899e549da1%3Aorigins',
		'unlocked' => '',
		'debug' => '%5B%22%5C%2Fusers%5C%2Flogin%3Fredirect%3D%252Fusers%252Fadd%22%2C%7B%220%22%3A%22email%22%2C%221%22%3A%22password%22%2C%22origins%22%3A%22%7B%5C%22redirect%5C%22%3A%5C%22%5C%5C%5C%2Fusers%5C%5C%5C%2Fadd%5C%22%7D%22%7D%2C%5B%5D%5D'
	]
]

```

**Comment by garas** [comment]
Does `$body['_csrfToken']` value matches value of `csrfToken` cookie?

**Comment by iarcas-com-br** [comment]
> I'll do the debugs again:

@garas see that it duplicates the debugs.

And on the second impression, the $post is empty.



```


debug($cookie);
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 247)
'20b005240b389e3e84e21fc30f03fb9f1b7e3d3c8abc409740b0e69c'
debug($post);
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 264)
'20b005240b389e3e84e21fc30f03fb9f1b7e3d3c8abc409740b0e69c'


debug($cookie);
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 247)
'20b005240b389e3e84e21fc30f03fb9f1b7e3d3c8abc409740b0e69c'
debug($post);
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 264)
''


debug($header);
/src/Http/Middleware/CsrfProtectionMiddleware.php (line 270)
''

```


thank you

**Comment by garas** [comment]
I've looked again to your callstack from first message. You have added `CsrfProtectionMiddleware` twice. 

Remove one of them.
 
```
/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:134 *************
/cakephp/cakephp/src/Http/Runner.php:73
/cakephp/cakephp/src/Http/Runner.php:77
/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:138 *************
```

Outer one validates successfully, but removes token from post data, so inner one doesn't see it anymore and fails validation.

**Comment by markstory** [comment]
Applying the CSRF middleware twice will lead to this failure. Removing the second middleware instance will fix this problem.

**Comment by VARGA-Peter** [comment]
@markstory 
Hi, I have exactly the same problem. Below the Stack Trace and as you can see I don't apply it twice.

```
/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:143
/vendor/cakephp/cakephp/src/Http/Runner.php:73
/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:164
/vendor/cakephp/cakephp/src/Http/Runner.php:73
/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:166
/vendor/cakephp/cakephp/src/Http/Runner.php:73
/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
/vendor/cakephp/cakephp/src/Http/Runner.php:73
/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:121
/vendor/cakephp/cakephp/src/Http/Runner.php:73
/vendor/cakephp/cakephp/src/Http/Runner.php:58
/vendor/cakephp/cakephp/src/Http/Server.php:90
/webroot/index.php:40
```

Any idea what am I doing wrong?

**Comment by markstory** [comment]
I don't know what's going on there, sorry. I would start by looking at the request data and cookies and seeing if there is a mismatch there, and then figure out how the cookies and request data are ending up different.

**Comment by othercorey** [comment]
Didnt we add an exception in 4.1.1 to detect the token being applied twice?

**Comment by VARGA-Peter** [comment]
@markstory 
Does it help when I tell you

- I am getting using login from the Admin-LTE plugin and
- I am running the page in a subdomain, like `my.example.com`

I examined the cookies and I see clearly in the request data is missing `field` which is compared with `$cookie` and `$header = $request->getHeaderLine('X-CSRF-Token');` in `CsrfProtectionMiddleware.php#297` returns an empty string.

So, in my case according to the error message 'CSRF token from either the request body or request headers did not match or is missing.' the expression **_CSRF token is missing_** - there isn't a mismatch.

**Comment by VARGA-Peter** [comment]
@garas No, there is no `$body['_csrfToken']` entry/field. It's empty.

**Comment by garas** [comment]
Check your browser Developer Tools if token is actually sent in cookie and also sent as header or form data.

**Comment by VARGA-Peter** [comment]
@garas 
@markstory 
@othercorey 

Guys, the subdomain is running under Cloudflare. Can this be the problem? I had in the past different issues regarding Cloudflare. Any idea?

**Comment by VARGA-Peter** [comment]
@garas 
@markstory 
@othercorey 

This is the information from Developer Tools - does it help?

```
Request URL: https://my.*****.com/users/login
Request Method: POST
Status Code: 200 
Remote Address: *****:443
Referrer Policy: no-referrer-when-downgrade
content-type: text/html; charset=UTF-8
date: Tue, 28 Jul 2020 17:52:21 GMT
server: nginx
status: 200
strict-transport-security: max-age=63072000; includeSubDomains
X-DNS-Prefetch-Control: off
x-powered-by: PHP/7.4.8
x-powered-by: PleskLin
:authority: my.*****.com
:method: POST
:path: /users/login
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: de-AT,de;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,en-US;q=0.5,en;q=0.4,sk;q=0.3
cache-control: max-age=0
content-length: 47
content-type: application/x-www-form-urlencoded
cookie: __cfduid=db92029ead986fb7abafee2ba7dfeeed81595450946; csrfToken=50732e944ddcddac0bb1b4ec248742c5cc9659a36f9226cf4c02bb2e; PHPSESSID=tuq4mq1cssb7l2g4jdjs3lk4nm
dnt: 1
origin: https://my.*****.com
referer: https://my.*****.com/users/login?redirect=%2F
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
email: *****
password: *****
```

**Comment by garas** [comment]
The form only sends `email: *****   password: *****`, but no `_csrfToken`.

How do you generate form? Do you use form helper or just added `<form>` directly?

**Comment by VARGA-Peter** [comment]
@garas 

This is exactly the point, thank you for confirming. I am using the default login.php from [Admin-LTE plugin](https://github.com/maiconpinto/cakephp-adminlte-theme). Nothing else!

**Comment by markstory** [comment]
You might want to contact the maintainer of that plugin or look at the login form it is using and ensure it was created with FormHelper.

**Comment by VARGA-Peter** [comment]
@markstory  I will do.

**Comment by VARGA-Peter** [comment]
@garas 
@markstory 
@othercorey 

OK guys, in the referenced issue I posted the CSRF safe version of the [Admin-LTE plugin](https://github.com/maiconpinto/cakephp-adminlte-theme) and it works perfectly. The trigger was garas' question if I use `$this-Form->create()` - As I am a bloody CakePHP beginner and started 2 days ago I needed for the safe version 1 day but I understand more and more the internal logic. Thank you a lot!

**Comment by othercorey** [comment]
Next time, we need more information. If a form is being submitted without the right into then post the form that's being generated.

Also, if you're using a plugin to generate something then we don't support the plugin. You should start with the plugin developer first.
