### ISSUE TITLE
Table Validator not firing up on new entity

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14558]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11
* Platform and Target: linux amd64, nginx, php7.4.5

### What you did
```
$instance = $this->Table->newEntity();
$instance->field = 'value';
if($this->Table->save($instance)) {
  // ...
}
```

### What happened
Validator is not fired up on `Table::save($instance);` even though it should fire up per-docs (note at the end of section https://book.cakephp.org/3/en/core-libraries/validation.html#validating-data )

### What you expected to happen
Entity not created from request data (using eg. `$this->Table->newEntity($this->getRequest()->getData())`, but initialized side-ways (direct property access or through Entity::set()) should be validated before saving. Instead `Table::save($entity)` checks only rules, not using validator and checks for existing errors, which are not created along the documented way.

**Comment by ADmad** [comment]
Validation is meant incoming request data, not entity properties and it's when entity is created or patched, not when it's saved. So if you don't pass the `$data` argument for either `Table::newEntity()` or `Table::patchEntity()` there won't be any validation.

**Comment by smarek** [comment]
This is misleading, first sentence of https://book.cakephp.org/3/en/core-libraries/validation.html#validating-entities says **While entities are validated as they are saved, you may also want to validate entities before attempting to do any saving.**

I'd expect the entity to be validated before saving, not at time of creating it, since there is usually post-processing to entity properties in controller, not pre-processing of incoming request data before creating entity.

**Comment by ADmad** [comment]
Docs are inaccurate, I have opened a PR to fix.

**Comment by smarek** [comment]
Please update both mentioned sections, my previous comment is about different docs section

**Comment by dereuromark** [comment]
Please see newEmptyEntity() vs newEntity() in 3.9 and 4.1.

**Comment by smarek** [comment]
@dereuromark I see, hopefully this is what you mean (and btw. 3.9 is not released or tagged yet?) https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L2664
>     * By default, the data is validated before being passed to the new entity. In
>     * the case of invalid fields, those will not be present in the resulting object.
>     * The `validate` option can be used to disable validation on the passed data:

Ok, I understand the approach, but still this is confusing to me a lot, because validating the data presented to ORM when creating/patching entity and not when saving it either expects the input-data pre-processing by controller (which seems duplicated to me, if the validator is defined), or it expects from user to manually run validation after the properties has been changed after entity create/patch (eg. if the entity property is not defined by request data, but other controller logic)

**Comment by ADmad** [comment]
@smarek I have submitted fixes for both the sections you pointed out.

**Comment by smarek** [comment]
Also, since I've been mislead by the docs the whole time, i'm sharing my fix-up solution using AppTable modified method of `save($entity,$options);`

```php
<?php

namespace App\Model\Table;

use Cake\Datasource\EntityInterface;
use Cake\Datasource\InvalidPropertyInterface;
use Cake\ORM\Table;

class AppTable extends Table
{
    public function save(EntityInterface $entity, $options = [])
    {
        $validator = $this->getValidator((!empty($options['validate']) && is_string($options['validate'])) ? $options['validate'] : null);
        $errors = $validator->errors($entity->toArray(), $entity->isNew());
        foreach ($errors as $key => $val) {
            if ($entity instanceof InvalidPropertyInterface) {
                $entity->setInvalidField($key, $entity->{$key});
            }
            $entity->setError($key, $val);
        }
        return parent::save($entity, $options);
    }
}
```

**Comment by garas** [comment]
There is also example in [Using Validation as Application Rules](https://book.cakephp.org/3/en/orm/validation.html#using-validation-as-application-rules) how to validate through rules.
