### ISSUE TITLE
Controller class Notifications_users could not be found.

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#14560]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.7.
* Platform and Target: Windows 10, PHP 7.4.1

### What you did
I am upgrading my rest API 3.8 to 4 . It has no problem with 3.8.*

### What happened
Camel cased controller class not found 
```
code: 404
file: "C:\xampp\htdocs\spot-back2\vendor\cakephp\cakephp\src\Controller\ControllerFactory.php"
line: 160
message: "Controller class Notifications_users could not be found."
url: "/v1/notifications-users.json"
```

### What you expected to happen
How to solve this?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
