### ISSUE TITLE
Serialize issue on ResultSet

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14569]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: master / 4.x

### What you did

Upgraded from 3.x:
```php
	$this->loadModel('Data.States');
	$states = $this->States->find('all');

	$this->set(compact('states'));
	$this->set('_serialize', ['states']);
```

### What happened

Some of my controllers error with

> [Cake\View\Exception\SerializationFailureException] Serialization of View data failed. in /.../vendor/cakephp/cakephp/src/View/SerializedView.php on line 127

caused by

> Caused by: [TypeError] array_keys() expects parameter 1 to be array, object given in /.../vendor/cakephp/cakephp/src/View/XmlView.php on line 142

### What you expected to happen
That it works even without having to force-call toArray() on it, as it did before.

Do we want to fix this? Or should we expect people to always do

    $states = $this->States->find('all')
        ->toArray();

?

**Comment by markstory** [comment]
Is there a longer stack trace for this error?
