### ISSUE TITLE
RFC: No way to reset Query::$_resultsCount

### ISSUE THREAD

**Issue by Phally** [cakephp/cakephp#14564]
### Issue

There's no direct way to reset the result set + count in a query object. It's the exacty functionality implemented in `Query::_dirty()`.

This is for CakePHP 3.x and 4.x.

Basically, it's for reusing Query objects to run the same query many times. 

In the past I've done a few things to work around it, but I keep bumping into it. See the use case below.

Things I've done in the past to work around it:
- Wrap the `$this->query()->..` in a method so I get a new query instance every time.
- Clone the query object every time and then execute the clones instead.
- Override `Table::query()` to give me a custom Query object with a `clean()` method which calls `Query::_dirty()`. (my personal favorite)

All these things work, but I feel this is missing in the framework.

### Proposal

I'm proposing a new public method `Query::clean()` which simply calls `Query::_dirty()`.

Alternatively, I'm fine with having `Query::setResult(null)` call `Query::_dirty()` instead.

Which has your preference and should I send in a pull request?

### Example use case

It comes down to reusing a query object when importing changes from a different table. These source tables are placed in the database using ETL for example.

These are tables with millions of rows and the number of changes are large as well. The sources can rarely be trusted to give us perfect data, so we almost always have to validate it as well.

So what I do is make a query that joins the source and target tables where the fields are different. This query will only give me the changed records and the new ones. A bit like a negative select query.

I set an appropriate limit to the query so we don't run out of memory, let's say 1000 and then I'll execute this query in a loop until it no longer gives any results.

In the loop I will validate the data and update the target table(s) accordingly.

So, in this use case I execute the exact same query up to 100 times. `while ($query->count()) { .. }` won't work in the current situation. Not even after calling `Query::setResult(null)`.

**Comment by markstory** [comment]
Query::clean() would be my preference.

**Comment by othercorey** [comment]
We have `ORM\Query::cleanCopy()`. If we use the name `clean()` then `cleanCopy()` needs to call it or users will be confused.

**Comment by Phally** [comment]
> We have `ORM\Query::cleanCopy()`. If we use the name `clean()` then `cleanCopy()` needs to call it or users will be confused.

True! Any suggestions on a different name?

I thought about something like `clearData()`. So it's more in the spirit of cache but not exactly cache. But I feel users might confuse it with a `TRUNCATE`. I'm trying to avoid using the word "Result", so it doesn't conflict with `setResult()` and the property.

**Comment by othercorey** [comment]
I am not sure the name is a problem. I think we could simply make the API more complete:

- `Query::clean()`
- `Query::cleanCopy()`
- `ORM\Query::cleanCopy()`

Both clean copies will clone and clean. `ORM\Query::cleanCopy()` would call `clean()` along with the cleanup it already does.

**Comment by markstory** [comment]
`Query::reset()` could work too. It wouldn't overlap with the existing `cleanCopy()` method.

**Comment by othercorey** [comment]
`reset()` kind of feels like you're just resetting the iterator. `clean()` is a good name. 

I think I prefer consistent api over instead of trying to write one-off special cases. Users won't ask what the difference is "Why can't I just clone and reset ORM\Query?".

**Comment by ADmad** [comment]
`Query::clean()` doesn't really tell me what parts of query it will clean. Without an additional qualifier one would think it's it clears all internal state.

I would prefer the name `Query::clearResult()`. It's tells you exactly what it does and the name is consistent with `Query::clearContain()` we already have.

**Comment by othercorey** [comment]
> I'm trying to avoid using the word "Result", so it doesn't conflict with setResult() and the property.

How does it conflict?

**Comment by Phally** [comment]
> `Query::reset()` could work too. It wouldn't overlap with the existing `cleanCopy()` method.

I do like short names, though I feel @othercorey makes a good point regarding the iterator.

> `Query::clean()` doesn't really tell me what parts of query it will clean. Without an additional qualifier one would think it clears all internal state.
> 
> I would prefer the name `Query::clearResult()`. It's tells you exactly what it does and the name is consistent with `Query::clearContain()` we already have.

It probably should be `Query::clearResult()` in the sense that it is what users expect to find as well yeah. After sleeping on it, I do think `Query::clean()` might have the expectation of getting the same result as `Query::cleanCopy()` except for the clone/copy part which it won't.

> > I'm trying to avoid using the word "Result", so it doesn't conflict with setResult() and the property.
> 
> How does it conflict?

Just that `setResult()` is a setter for `QueryTrait::$_result` whereas this method would touch two properties instead. Tbh, I'm not feeling that strongly about it. I'm okay with naming it `Query::clearResult()`.

**Comment by othercorey** [comment]
Can you open a PR?

**Comment by Phally** [comment]
Yes, absolutely!
