### ISSUE TITLE
CsrfProtectionMiddleware / Cookie / ResponseEmitter does not allow to set SameSite security

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14588]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12
* Platform and Target: nginx, php-7.4.5-fpm, linux

See scan report for cakephp.org https://securityheaders.com/?q=cakephp.org&followRedirects=on

Configuring session, it's possible to configure session cookie to be pretty much secure

```php
<?php
// snip from app_local.php
   return [ 'Session' => [
        'cookie' => '__Host-CAKEPHP',
        'defaults' => 'cake',
        'ini' => [
            'session.cookie_samesite' => 'Strict',
            'session.cookie_path' => '/',
            'session.cookie_httponly' => 1,
            'session.cookie_lifetime' => 60 * 60 * 24 * 7
        ],
        'timeout' => 60 * 60 * 24 * 7 // week
    ]];
```

However, as can be seen in scan report, it's not possible to configure samesite security for csrfToken cookie, because `Cake\Http\Cookie\Cookie` does not allow setting additional cookie params, and ResponseEmitter uses the [`setcookie`](https://www.php.net/manual/en/function.setcookie.php) call variant, which does not allow the samesite 'Strict'/'Lax' setting

Used setcookie function is available since PHP 5.2.0
```php
function setcookie ($name, $value = "", $expire = 0, $path = "", $domain = "", $secure = false, $httponly = false)
```
Desired function is available since PHP 7.3.0
```php
function setcookie($name, $value = '', array $options = []) :bool
```

Or one could avoid using PHP `setcookie()` function, and use `header()` directly, see https://www.php.net/manual/en/function.setcookie.php#124644

Tasks, as I see them
- [ ] Backport 4.x ResponseEmitter `protected function setCookie($cookie): bool` which already supports the newer call and workaround for samesite, to **3.x branch**
- [ ] Backport 4.x Cookie class to 3.x branch, because it supports samesite setting ($defaults)
- [ ] Update CsrfProtectionMiddleware in both 3.x and 4.x to suport SameSite option

Also, there is some new security measurement, called "Cookie Prefixing", see https://scotthelme.co.uk/tough-cookies/#cookieprefixes
That would be nice, to have it configurable site-wide, without need to configure each component, that uses framework provided Cookie class (or it might be already supported through 4.x call `public static function setDefaults(array $options): void` ?)

I'll gladly push PR for backporting tasks, but I'd like you guys to take care of updating CsrfProtectionMiddleware to support SameSite cookie setting. Could it be?

----
I've just confirmed, on 4.x the samesite defaults can be set via this snippet
```
\Cake\Http\Cookie\Cookie::setDefaults([
    'samesite' => 'Strict'
]);
```
which I personally placed in bootstrap.php, after Configure::read('debug') settings

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/13493#issuecomment-623011356 and https://github.com/cakephp/cakephp/pull/14122

**Comment by markstory** [comment]
The cookie prefix features are still a working draft, and we generally don't implement functionality that exists in only working drafts.

**Comment by markstory** [comment]
Backporting the 4.x samesite cookie features fits within the goals of 3.9. If you have the interest a pull request doing that would be awesome.

**Comment by dereuromark** [comment]
Note that https://github.com/cakephp/cakephp/releases/tag/3.9.0-RC1 is already out and thus there is  time window of only a few weeks until such an addition will be hard to land in 3.9.

**Comment by othercorey** [comment]
> Refs [#13493 (comment)](https://github.com/cakephp/cakephp/issues/13493#issuecomment-623011356) 

I put a small amount of work into porting the cooking changes back to 3.9, but I gave up trying to update the different cookie collections. Someone who is more familiar with the changes would need to do it.

**Comment by othercorey** [comment]
With 3.9 released, are we closing this backport request?

**Comment by ADmad** [comment]
Done in #14987
