### ISSUE TITLE
Button names with dots don't play well with FormProtection

### ISSUE THREAD

**Issue by diegosardina** [cakephp/cakephp#14591]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.7.
* Platform and Target: Linux / PHP 7.4

### What you did

```
<?= $this->Form->button(__('Do this'), ['name' => 'do.this']) ?>
```
However this happens also if one overrides the name attribute in ->control().

### What happened
```
Unexpected field do_this in POST data
Cake\Http\Exception\BadRequestException
```
It seems that PHP (written [here](https://www.php.net/manual/en/language.variables.external.php)) converts dots to underscore:

> Note:
> Dots and spaces in variable names are converted to underscores. For example \<input name="a.b" /> becomes $_REQUEST["a_b"]. 
> 

### What you expected to happen
Convert dots/spaces to underscore before PHP takes that action, so FormProtection will see the same field.

In alternative (and it would be better) to convert dots and underscores to the index notation to be coherent with predefined names (and they result namespaced in the request), but it would be a BC.

**Comment by ADmad** [comment]
Why can't you just use names without dot and avoid this problem?

**Comment by markstory** [comment]
Don't use dots is the solution here.
