### ISSUE TITLE
Paginator change page url with Paginator->numbers function

### ISSUE THREAD

**Issue by Noralina** [cakephp/cakephp#14603]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.4
* Platform and Target: 

### What you did
Trying to paginate Projects
```
echo $paginator->numbers();
```

### What happened
```
<li class="active"><a href="">1</a></li>
<li><a href="/projects?page=2">2</a></li>
```

### What you expected to happen
```
<li class="active"><a href="">1</a></li>
<li><a href="/building/our-projects?page=2">2</a></li>
```

I searched on the cookbook but didn't find any response for this "bug".
Is it possible to keep the page url ?

**Comment by markstory** [comment]
>  Is it possible to keep the page url ?

Yes. You need to use `Paginator->options()` to set the parameters you want pagination URLs to use.

**Comment by markstory** [comment]
This [section in the docs](https://book.cakephp.org/4/en/views/helpers/paginator.html#configuring-pagination-options) gives an example of how to do that.

**Comment by Noralina** [comment]
This section in the docs gives an example of how to do with query params only.
On my project, there is no route for ```/projects```.
I need to keep my route ```/building/our-projects```.

**Comment by ADmad** [comment]
> This section in the docs gives an example of how to do with query params only.

You can set any route element for the `url` key, not just query params.

> I need to keep my route /building/our-projects.

What route have you connected which handles the `/building/our-projects` URL?  You need to set required route elements so the reverse routing working and can generate back your URL.

**Comment by Noralina** [comment]
@ADmad That's not obvious in the doc but you made my day !
