### ISSUE TITLE
Remove seconds from time/date FormHelper inputs

### ISSUE THREAD

**Issue by ryanolton** [cakephp/cakephp#14611]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0-beta1 (all of 4.x)
* Platform and Target: Debian 10.4, nginx 1.14.2, PostgreSQL 11.7, PHP 7.3.14

### What you did
I used FormHelper to create a control and set the type to "time".

`$this->Form->control( 'bedtime', [ 'type' => 'time' ] )`

### What happened
The resultant input was of type "time" and had seconds (and a "step" attribute).

### What you expected to happen
I knew what to expect based on the documentation, I just need the ability to remove seconds.

**Comment by othercorey** [comment]
Does setting the step not work for you? Can you show the html output that is generated and what you expect?

**Comment by ryanolton** [comment]
> Does setting the step not work for you? Can you show the html output that is generated and what you expect?

Setting the step does work to remove the step attribute, however, removing the step alone does not remove the seconds (at least not in Firefox), you must also remove the seconds from the input value:

**No step and no value (and no seconds):**

```
<html>
  <body>
    <form>
      <input type="time">
    </form>
  </body>
</html>
```

**No step but with a value (and with seconds):**
```
<html>
  <body>
    <form>
      <input type="time" value="11:00:00">
    </form>
  </body>
</html>
```

Even if a time without seconds is supplied to FormHelper, "11:00" for example, there is a function within the DateTimeWidget that converts it into predefined formats:

```
protected $formatMap = [
  'datetime-local' => 'Y-m-d\TH:i:s',
  'date' => 'Y-m-d',
  'time' => 'H:i:s',
  'month' => 'Y-m',
  'week' => 'Y-\WW',
];

...

$data['value'] = $this->formatDateTime($data['val'], $data);
```

Per the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Time_value_format), if seconds are supplied in the value, then seconds show in the input. Due to this reason, the FormHelper format defaults need overwritten so that seconds are omitted from the value used in the final HTML output.

It's the combination of having no step **and** having no seconds in the input's value that allows the format to omit seconds.

See PR #14612

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/14614.
