### ISSUE TITLE
Optional routing parameter

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#14628]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.7

I don't know if this is a bug, a feature, or something impossible ...

I want to switch my datasource based on an optional prefix in my url, E.g. /test/controller/action would use datasource "test" and /controller/action would use datasource "default". 

I adopted the routing class of admad/cakephp-i18n (@ADmad: Thank you very much for this project, I wouldn't have succeeded without that!), changed {lang} to {ds} and added it to defaults, too. So I have nice patterns where {ds} in /{ds}/{controller} is an optional subpattern and both, /test/controller and /controller match the route.

But: preg_match called for /controller returns an empty string for {ds}. Therefore, in the request object the parameter 'ds' is set to an empty string. When I call Route::url(['controller' => 'other']) the (supposed to be optional) key 'ds' in the url array is set to en empty string in Route::match (precisley: _persistParams). At the end of the method match all options are checked against their corresponding keys in the $url array with preg_match using an on-the-fly created pattern, using my definition of {ds} (i.e. 'test'), without making it optional. And that, of course, would fail.

As a workaround I overloaded the method parse in my route class and replace it with null when empty. The preg_match above would succeed checking against null.

My question: when compiling the route all parameters from the templates are removed from defaults so the information that a parameter was optional is lost. If it were somehow stored, or if the generated pattern for the parameters were stored it could detect in parse that a parameter was not part of the url, or it could use it in the match method instead of the on-the-fly pattern,

**Comment by ADmad** [comment]
You should be connecting 2 routes, 1 for pattern `/{ds}/{controller}` and another for `/{controller}`, have you done that?

**Comment by chtheis** [comment]
I thought about that but then I had to duplicate every route, including those in plugins and also the fallback-routes. It would not be DRY. 

But I can append a '|' to my pattern so it should match an empty string, too.
It would still be a workaround but a nicer one.

**Comment by ADmad** [comment]
Currently the router doesn't have any support for optional parameters/elements. I am not sure how feasible that is. @markstory would have a better idea about it.

**Comment by chtheis** [comment]
It is almost there, but it might be the famous 80%.
If I put ['ds' => null] into defaults the resulting pattern for this parameter will have a '?' appended and /controller will match. Unfortunately it will then continue to use {ds} as if it were found and had been an empty string, and the information, it had a default, is removed.

Anyway, making my pattern match an empty string, too, seems to be working :)

**Comment by markstory** [comment]
Optional elements are tricky as they can create ambiguous routes that match inconsistently. This is why keys/placeholders are removed from defaults when matches are made.

Instead of duplicating routes you can put all the routes that need the ds prefix into a function and then define two scopes that use your function as their 'builder's

```php
$routes->scope'/', ['ds' => 'default'], $prefixRoutes);
$routes->scope'/{ds}', $prefixRoutes);
```

**Comment by chtheis** [comment]
I know, something optional can introduce ambiguities, so I'll never write a controller named 'Test'.

But my point is not how to avoid optional parameters. I think they are a very helpful feature of CakePHP. In fact, my approach wouldn't be possible without it. 

My point is that by removing keys from default in the compile step the information, that a parameter was optional is lost and that loss makes using them a less elegant than I think they could be.  E.g. when parsing a route you'll use the optional pattern but you can't detect anymore that the empty string is an artifact from preg_match and not something present. And in match you'll build a check pattern again, but this time you don't know anymore that the parameter was optional.

I workaround this by making my pattern to match an empty string, too, and so I have an elegant way to prefix all route auto-magically with my datasource, but I think, what I wrote in the paragraph above, is not what you intended when you introduced optional parameters.

I don't know where default interferes with keys, nor the background why you had to do it at that time. But could it be a possible way to store those removed parameters in another array optionalKeys? At least the information a parameter of the route is optional and which default it had would not be lost and one could access it where necessary.

**Comment by markstory** [comment]
> My point is that by removing keys from default in the compile step the information, that a parameter was optional is lost and that loss makes using them a less elegant than I think they could be. E.g. when parsing a route you'll use the optional pattern but you can't detect anymore that the empty string is an artifact from preg_match and not something present. And in match you'll build a check pattern again, but this time you don't know anymore that the parameter was optional.

I took a look at the code, and the unsetting of keys from the defaults list was added in 328db0c36b1. However, when I remove that block now, no tests fail. We may have lost those tests, but that seems unlikely.

If you would be willing to make a pull request to remove that loop and add tests for the optional parameter support I'd be happy to help with tests and review.

**Comment by chtheis** [comment]
I will do.
