### ISSUE TITLE
Add $session->readOrFail() and $session()->readOrCreate() 

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#14623]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7 / 3.8

### What you did
Used sessions to read/write data.

### What happened
Got silent null values.

### What you expected to happen
Stuff to crash.

**Comment by dereuromark** [comment]
orCreate() is usually an antipattern - or not applicable in this context IMO. 

    read(?string $name = null)

could also become

    read(?string $name = null, $default = null)

or alike, having a default value where needed.

But otherwise the orFail() sounds reasonable.

**Comment by markstory** [comment]
I prefer the `read()` with a default value over `readOrCreate()`

**Comment by inoas** [comment]
@dereuromark however null is a legit value so ?? $default only works for keys that are not considered valid when set to null - right?

**Comment by dereuromark** [comment]
Well, null in that context it is not. Check also all other default cases.
The same for *orFail() as that one for all our methods so far also excludes null as value.
If null would would be a valid value, you would need custom logic here either way - if we change that behavior we create a snowflake.

The orFail() just makes more sense here as defaulting is already super easy anyway.

Rule of thumb: Don't store null as meaningful value, cast it to the type you need if you want to use such methods.

**Comment by othercorey** [comment]
Isn't this signature more consistent with cake? I'm not sure if we like the nullable name convention in cake still.

`read(?string $name = null, $default = null)`

**Comment by dereuromark** [comment]
Yes it would be :) just saying that it is not null value aware.

**Comment by dereuromark** [comment]
If you want a defaulting or orFail() added, now would be the time, as RC will now be finalized for both 4.1 and 3.9 backport.

**Comment by dereuromark** [comment]
I opened https://github.com/cakephp/cakephp/pull/14647 for further fine-tuning.
