### ISSUE TITLE
Response type issue when sending Accept header: application/json, */*

### ISSUE THREAD

**Issue by sergiudb** [cakephp/cakephp#14638]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.21
* Platform and Target:
Windows 10
Apache 2.4, PHP 7.1.3 and MySQL 5.7.26

### What you did
Making a GET request to a non-existing file, example: http://local.mywebsite.com/non-existing.txt 
And adding an `Accept header: application/json, */*`

In our application we determine if the request is json and we return a json response; in this case it should be a 'Not found' json response.

### What happened
In the main controller, in the beforeRender method, `$this->request->is('json')` returns `true`.

Server responds back with a `500 Internal server error` because we're checking to see if the request is json, so we start initializing a json response, but we actually end up with a `text/html` Content-Type and a lot of undefined variables, due to how the request handler works when an `Accept header: application/json, */*` is sent.

Based on [this](https://github.com/cakephp/cakephp/issues/4794), that's what is supposed to happen if we don't manually set the extension, but when checking both the request type and the response type, there seems to be a bug:

`$this->request->is('json')` will be `true`, but `$this->response->type() === 'text/html'` is also `true`, which seems to be a bug. 

### What you expected to happen
We expect the `$this->response->type()` to coincide with the request type, thus a json response to be generated with a 404 code.

**Comment by markstory** [comment]
Your accept header includes both the json and * content types with equal preference. If you don't coerce the response type, and HTML response satisfies the accept header of the client.

Do you have the same results with `Accept: application/json` or `Accept: application/json, */*;q=0.5`?

**Comment by sergiudb** [comment]
> Do you have the same results with `Accept: application/json` or `Accept: application/json, */*;q=0.5`?

With these headers it works fine. 

So, it's not actually an issue that for `Accept: application/json, */*` the request type is `json` and the response type is `text/html`?

**Comment by markstory** [comment]
@sergiudb I don't think so. The request type is both json and html at the same time. RequestHandlerComponent requires a clearer content-type preference to make a decision. When both HTML and JSON are preferred at the same rate it sticks with HTML.

**Comment by sergiudb** [comment]
@markstory Ok, thank you for the info.
