### ISSUE TITLE
Switch from deprecated PSR-2 to PSR-12

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#14637]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x and higher.
* Platform and Target: any.

> Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.
https://www.php-fig.org/psr/psr-2/

I would like to propose to use PSR-12 coding standard instead PSR-2. 

> PSR-2 was accepted in 2012 and since then a number of changes have been made to PHP which has implications for coding style guidelines. Whilst PSR-2 is very comprehensive of PHP functionality that existed at the time of writing, new functionality is very open to interpretation. This PSR, therefore, seeks to clarify the content of PSR-2 in a more modern context with new functionality available, and make the errata to PSR-2 binding.
https://www.php-fig.org/psr/psr-12/

F.ex.:
```
if (
    $expr1
    && $expr2
) {
    // if body
} elseif (
    $expr3
    && $expr4
) {
    // elseif body
}
```
is a valid code style in PSR-12 but invalid in PSR-2.

The code sniffer reports something like `Expected 0 spaces after opening bracket; newline found (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)`.

**Comment by ADmad** [comment]
PSR-12 is already used for CakePHP (v4 of this package). Changing the standard for 3.x would create unnecessary chore for us.
