### ISSUE TITLE
Hash:Diff bug on multidimensional array with different keys

### ISSUE THREAD

**Issue by ayoub-bousetta** [cakephp/cakephp#14640]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x and plus.

### What you did
i try to use Hash::diff on multi with different keys but same values the returned result is not the same..

### What happened
if we take your the example on the website and change 0.1.2 keys to 4.6.1 it will return everything in both arrays 

```
$a = [
    0 => ['name' => 'main'],
    1 => ['name' => 'about']
];
$b = [
    4 => ['name' => 'main'],
    6 => ['name' => 'about'],
    1 => ['name' => 'contact']
];

$result = Hash::diff($a, $b);
/* $result ressemble maintenant à:
    [0] => Array
        (
            [name] => main
        )

    [1] => Array
        (
            [name] => about
        )

    [4] => Array
        (
            [name] => main
        )

    [6] => Array
        (
            [name] => about
        )
*/
```

### What you expected to happen
maybe 

```
[0] => [
                [name] => contact
        ]
```

**Comment by markstory** [comment]
This is working as designed though. Numeric key differences are differences, as the values at each key are different.
