### ISSUE TITLE
Wrong magic method signature

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14642]
https://wiki.php.net/rfc/magic-methods-signature

PHP 8 is considering better signature checks and found an error in cakephp.

wrong native return type of __call(): void
https://github.com/cakephp/cakephp/blob/8718b2e9bbd092b991a1da6472d1a28e89b63dac/src/Controller/Component/FlashComponent.php#L137

**Comment by dereuromark** [comment]
I agree, those should not have void as return type.
Semantically speaking such a method can both return something and null, but not really void (as it is not fully assertable to only be used as setter and not getter).

So let's just remove it in 4.1.

**Comment by ADmad** [comment]
It's strange that the RFC only mentions `__toString()` with regarding to future runtime time. Why not just add return type `string` for the method?

**Comment by othercorey** [comment]
Looks like they have by making it bound to type Stringable.

https://3v4l.org/jIg7b/rfc#git-php-master

**Comment by ADmad** [comment]
Ah so we can add `string` return typehint to all `__toString()` usages.

**Comment by othercorey** [comment]
Btw, only have one other type hinted `__call()`, and it wasn't flagged. That should indicate it's compatible with their intended typehint.

https://github.com/cakephp/cakephp/blob/a98ed4ef6a55cb524d67da33e668fbde76edb78f/src/Database/FunctionsBuilder.php#L293

**Comment by ADmad** [comment]
So since `void` is a special type they don't consider it as covariant with `mixed`. Using any other type except `void` won't generate an error.

**Comment by dereuromark** [comment]
Yes.
