### ISSUE TITLE
Add last=true for Validator::scalar()

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#14651]
This is a:

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12
* Platform and Target: LAMP.

### What you did
I added validation rule:
```
$validator
	->requirePresence($field='password')->scalar($field)->minLength($field, 8)
	->add($field, 'strict-password', ['rule'=>function ($data, $provider) {
		if (!preg_match('/[a-zA-Z]/', $data) || !preg_match('/\d/', $data))
			return __d('validation', 'Your password must contain consist of both numbers and letters.');

		return true;
	}]);
```
And simulated submitting array instead of string for password.

### What happened
Since [`Validator::scalar()`](https://github.com/cakephp/validation/blob/3.8.12/Validator.php#L2265) is not marked as last, I got error messages regarding invalid length and not strict password. Also warning was produced: `preg_match() expects parameter 2 to be string, array given`.

### What you expected to happen
Validation is stopped if value is not scalar

Shouldnt we add `'last' => true` by default for [`Validator::scalar()`](https://github.com/cakephp/validation/blob/3.8.12/Validator.php#L2265) ?
I think it will be useful for 99% of use cases.

**Comment by dereuromark** [comment]
I always add this to my validation, for thid reason. 
But i am not sure if it should be a change for 4.1 globally now.

**Comment by andrii-pukhalevych** [comment]
I have `\App\Model\Validation\Validator` extends `\Cake\Validation\Validator` for such useful things, because waiting this in core can continue years.
And also for overriding default error messages in one place.
