### ISSUE TITLE
Wrong inflections of 'criterion' and 'criteria'

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#14665]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x and 4.x
* Platform and Target: any.

### What you did

![Screenshot from 2020-06-03 14:51:59](https://user-images.githubusercontent.com/3830106/83638693-d2a05380-a5a9-11ea-8096-d8f63802f161.png)

### What happened
[TestCriterion](https://sandbox.dereuromark.de/sandbox/inflector?string=TestCriterion), [TestCriteria](https://sandbox.dereuromark.de/sandbox/inflector?string=TestCriteria), [AnyWordCririon](https://sandbox.dereuromark.de/sandbox/inflector?string=AnyWordCririon), [AnyWordCriria](https://sandbox.dereuromark.de/sandbox/inflector?string=AnyWordCriria) are wrongly inflected.

### What you expected to happen
Singular - 'criterion', plural - 'criteria'.

**Comment by dereuromark** [comment]
When you go to https://en.wiktionary.org/wiki/criteria you get two links to
- https://en.wiktionary.org/wiki/criterion#English
- https://en.wiktionary.org/wiki/criterium#Dutch

saying that
- plural of `criterion` is `criteria`
- plural of `criterium` is `criteriums`

**Comment by dereuromark** [comment]
Given my findings of https://github.com/cakephp/cakephp/pull/14667 it seems you can already workaround the issue by inflecting always under_scored versions, never CamelCased ones.

**Comment by markstory** [comment]
I found another approach that avoids the additional inflections and also removes some redundant pattern string allocations by leveraging the cache property better.
