### ISSUE TITLE
Appending to session data in IntegrationTestTrait

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#14661]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.7

### What you did
For integraton tests I setup a session as per 
`$this->session(['Auth' => ['User' => ['id' => 1, ...]]]);`

In a specific test I want to make the user disabled, so I call 
`$this->session(['Auth' => ['User' => ['enabled' => false]]]);`
But this replaces 'Auth' with what I want to append.

The source reads
`
public function session(array $data) {
  $this->_session = $data + $this->_session;
}
`

Afaik adding arrays is not a deep copy and works only for the top-level key.

Is it possible to change to, or allow for, a deep copy, i.e. replace the plain adding with Hash::merge? Or the documentation of the method shall be more clear what "append" means.

**Comment by dereuromark** [comment]
I don't think that is feasable to be honest.
Merging recursive has several issues, especially if the array cannot fully be guaranteed to be assoc.

**Comment by chtheis** [comment]
That is possible. I thought of the way CakePHP merges configuration data. Maybe, like there, have a parameter switch 'deep' or 'merge' which defaults to false in this case? Or a separate method to do the merge.

**Comment by ADmad** [comment]
You can access the property directly and use `$this->_session = Hash::merge($this->_session, $array)`.

**Comment by chtheis** [comment]
Yes, thank you. That's what I will do.
