### ISSUE TITLE
Deletion fails if dependent delete of hasMany has no result

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#14672]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0rc1
* Platform and Target: PHP 7.4.4

### What you did
Defined a hasMany relation in the Companies Table (dependent)

Company -> hasMany -> HierarchyNodeLevels

### What happened
When trying to delete a Company and no entries exist in the HierarchyNodeLevels the delete() operation fails:

sql log:

```sql
BEGIN
DELETE FROM    hierarchy_node_levels  WHERE    company_id = 1
ROLLBACK
```

when an entry exists in HierachyNodeLevels the deletion works just fine so I guess the rowCount of 0 might is misinterpreted somehow?

### What you expected to happen
deletion should work just fine if hasMany is already empty (maybe the call can be skipped at all?

**Comment by ADmad** [comment]
Can you show your association config please?

**Comment by swiffer** [comment]
```php
        $this->hasMany('HierarchyNodeLevels', [
            'foreignKey' => 'company_id',
            'dependent' => true,
            'saveStrategy' => 'replace',
        ]);
```

**Comment by ADmad** [comment]
PR #14673 up. Thanks for trying out 4.1RC.
