### ISSUE TITLE
CakePHP 4 Association Not Defined issue.!

### ISSUE THREAD

**Issue by Jeganprogrammer** [cakephp/cakephp#14688]
In Cakephp 4.0, Cakephp contain query shows error.

**Query :** $products = $this->products->find()->contain(["Category"])->where(["status" => 0]);

**ProductsTable:** 

public function initialize(array $config): void
    {

     parent::initialize($config);
        $this->setTable('products');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Category', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER',
        ]);
    }

 But Query shows error, when add contain query.

**The Categories association is not defined on products.**

**Comment by ADmad** [comment]
You are supposed to use `$this->Products->`,  not `$this->products->`.

In future please use one of our support forums instead of this issue tracker if you need help.

**Comment by dereuromark** [comment]
Also IdeHelper plugin can help to avoid this.
