### ISSUE TITLE
Weird localisation issue in docker container

### ISSUE THREAD

**Issue by rmamba** [cakephp/cakephp#14687]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.7.9
* Platform and Target: docker container mambix/cakephpbase:php7.2.14-apache

### What you did
I deploy my code using mentioned docker container

### What happened
This is weird behaviour. When container starts the localization is not working. I see empty parsed files in cache. The only thing I can do to make it work is go to console inside container and execute this:
```
ls -la src/Locale
rm -r tmp/cache
```

### What you expected to happen
Localization should work whenever you restart the container.

**Comment by markstory** [comment]
What leads you to believe this is a problem in CakePHP? Could there be an issue with how you're building your docker image?

**Comment by rmamba** [comment]
because I have another project with CakePHP 4.0.4 that works with same docker template

**Comment by markstory** [comment]
Ok. How would we go about reproducing the problem you're having is your docker file published somewhere publically?

**Comment by rmamba** [comment]
I'll try to put a reproducer together asap for you

**Comment by othercorey** [comment]
@rmamba We will close this unless there is a test case.
