### ISSUE TITLE
Customizable separator for results from find('list') when using multiple display fields

### ISSUE THREAD

**Issue by MuresanSergiu** [cakephp/cakephp#14698]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.8
* Platform and Target: PHP 7.4.6, Apache/2.4.43 (Unix)

### What you did
When setting multiple display fields like this:
```
$this->setDisplayField(['field1', 'field2']);
```
Then, getting them using find('list') like so:
```
$this->find('list')->toArray();
```

### What happened
I'm getting this result:
```
[
  '1' => 'field_value1;field_value2',
  ...
]
```

### What you expected to happen
The result is as expected, but it would be nice to have a way to customize the ';' separator that is being used. To possibly getting a result such as this:
```
[
  '1' => 'field_value - field_value2',
  ...
]
```

### Implementation idea
I think the setting could nicely be placed in the 'setDisplayField' function, like so:
```
$this->setDisplayField(['field1', 'field2'], ['separator' => ' - ']);
```
And, to have this work, the ';' hardcoded value in Table.php:1445 (_setFieldMatchers function) should be replaced with some property of the table that is set by the options of setDisplayField.

**Comment by markstory** [comment]
Would defining the separator on the `find('list')` call work? Storing this state on the table when its only relevant for a few operations that tables do.

**Comment by AfterWind** [comment]
If that's the only place this functionality is used that'd be fine as well.
I also noticed that a function can be passed to `setDisplayField` that takes in an entity and returns its string representation. This seems to work well except it's not documented anywhere (I just figured it out based on the CakePHP's code)
