### ISSUE TITLE
Validator::decimal and Validator::boolean failing

### ISSUE THREAD

**Issue by notpron** [cakephp/cakephp#14699]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12
* Platform and Target: LAMP

### What you did

```
        $validator = new Validator();
        $validator->decimal('test_float')->boolean('test_bool');
        $data = [
            'test_float' => 42.42,
            'test_bool' => false
        ];
        $errors = $validator->errors($data, true);
        debug($errors);
```

### What happened

```
[
	'test_float' => [
		'decimal' => 'The provided value is invalid'
	],
	'test_bool' => [
		'boolean' => 'The provided value is invalid'
	]
]
```

### What you expected to happen
I expect no validation errors.

It seems like the number of args Validation::decimal and Validation::boolean are expecting, is one more than Validator::decimal/boolean is providing. Therefor $context ends up being the last arg.

**Comment by dereuromark** [comment]
Can you check if this is fixed in https://github.com/cakephp/cakephp/pull/14679 ?
I provided some backports from 4.x where these things should also all be fixed already.

**Comment by notpron** [comment]
That's a quick reply, thanks! Those changes unfortunately don't fix this issue.

There's even a little bit more warning of what's happening:

`Warning Error: preg_match() expects parameter 1 to be string, array given in [/vagrant/www/oefenweb.dev-app-3x/vendor/cakephp/cakephp/src/Validation/Validation.php, line 1264]`

Which makes sense because $data array is passed as the $regex string.

**Comment by notpron** [comment]
After doing some additional checks it seems like this is caused by our own Validator::addDefaultProvider changes. Without using our own Validation, the code passes. So I'm closing this issue.
