### ISSUE TITLE
4.1 RC Composer Required Version Incorrect?

### ISSUE THREAD

**Issue by jimbo2150** [cakephp/cakephp#14693]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1-RC1

### What you did
Downloaded the release candidate for version 4.1 and looked at composer.json.

### What happened
The requirement for the RC is cakephp ^4.0. Is that correct?

### What you expected to happen
Something along the lines of 4.1-dev.
I went back to the 4.0-RC and looked at composer.json and it was using 4.x-dev.

**Comment by markstory** [comment]
Thanks for letting us know about this problem. I made a mistake building the zip ball. I've removed the bad zipball, and the next release will have a fixed one.
