### ISSUE TITLE
ReflectionException (-1) Class App\Http\Controllers\admin\UserviewController does not exist

### ISSUE THREAD

**Issue by prahatravichandan** [cakephp/cakephp#14709]
namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Requests\admin\UserRequest;
use App\Http\Requests\admin\GuessingFormRequest;
use App\AdminServices\MatkaResultService;
use App\AdminServices\AdvertiseService;
use App\AdminServices\NoticeBoardService;
use App\AdminServices\CreateAdminService;
use App\AdminServices\ChartZoneService;
use App\AdminServices\FixGuessService;
use App\AdminServices\FixGameService;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Hash;
use App\ChartZone1;
use DB;
use App\User;

use App\Http\Controllers\Controller;

class UserViewController extends Controller
{        

public function registerUser(UserRequest $request){
          
            $insertuser=DB::table('users')->insert([
                'name'      => $request->name,
                'email'     => $request->email,
                'passPlainText' => $request->passPlainText,
                'password' => Hash::make($request->passPlainText),
                'role_id'      => $request->role_id,
                'is_active'      => $request->is_active
            ]);
            if($insertuser){
                return redirect()->back()->with('success', 'User Created');
                // return redirect()->back()->with('success', false)->with('message', trans('web.user_created'));   
            }else{
                return redirect()->back()->with('success', 'Please Insert Unique Email id');
            }
        } 
This is my controller 
here to start route
Route::post('registeruser/add','admin\UserviewController@registerUser')->name('registeruser/add');

**Comment by markstory** [comment]
It looks like you're using laravel. Perhaps check with them :smile:
