### ISSUE TITLE
Problems with DOUBLE values in find list using keyField

### ISSUE THREAD

**Issue by spellord** [cakephp/cakephp#14716]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.7
* Platform and Target: PHP 7.2.24-0ubuntu0.18.04.6, Apache/2.4.29 (Ubuntu), Mysql 5.7.30-0ubuntu0.18.04.1 (Ubuntu) request from Safari Version 13.1.1 (15609.2.9.1.2)

### What you did
I try to get a new list using custom keyField and valueField
```
        $listaitbms = $this->Proveedoresfacturas->Itbms->find('list',  
            [
                'keyField' => 'itbmscol',
                'valueField' => 'detalle'
            ]
        )->toArray();
```
In database itbmscol it's a float field and detalle is DOUBLE
```
CREATE TABLE IF NOT EXISTS `HBBD`.`itbms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NULL DEFAULT NULL,
  `itbmscol` DOUBLE NULL DEFAULT NULL,
  `audit` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
```

Values stored in database
```
INSERT INTO `itbms` (`id`, `detalle`, `itbmscol`, `audit`) VALUES
(1, '7%', '0.07', NULL),
(2, 'No Aplica', '0', NULL),
(3, '40%', '0.4', NULL);
```

### What happened
Get a list with only one value
`array(0 => 'No Aplica');`

### What you expected to happen
```
array(
      '0.07' => '7%',
      '0' => 'No Aplica',
      '0.4' => '40%'
);
```

In this point cakephp/cakephp/src/ORM/Table.php, I insert a print_r to this point to check the result set on $results and all work fine to this point after I don't know why combine() function ignore double values

        return $query->formatResults(function ($results) use ($options) {
            /** @var \Cake\Collection\CollectionInterface $results */
           //print_r($results)
            return $results->combine(
                $options['keyField'],
                $options['valueField'],
                $options['groupField']
            );
        });

I solved changing the value type in database of itbmscol from DOUBLE to TEXT and now work fine but I prefer store in database a DOUBLE value instead of a TEXT value

**Comment by markstory** [comment]
Wouldn't the change in type from float to string also be surprising when you're reading this data? PHP doesn't really support floats as keys which is why you're having the problem you're having.

```php
php > $a = [1.2 => '1', 2.6123 => 'two', 2.0001 => 'two 2'];
php > var_dump($a);
php shell code:1:
array(2) {
  [1] =>
  string(1) "1"
  [2] =>
  string(5) "two 2"
}
php >
```

**Comment by ADmad** [comment]
Since PHP doesn't support float keys I don't think this is a defect and auto type conversion of keys isn't something that should be done.

**Comment by spellord** [comment]
I see, I don't know why I didn't look for this in php oficial documentation (mental note for me).

**Comment by markstory** [comment]
Closing as remapping the field is something that could work here. Adding workarounds for php behavior will likely cause other problems.
