### ISSUE TITLE
Marshaller: _joinData accessibility in _marshalAssociation vs _mergeAssociation

### ISSUE THREAD

**Issue by dorxy** [cakephp/cakephp#14712]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x and 4.x

### What you did
Saving a belongsToMany association with a new entity does not set `_joinData` accessibility while merging does do this. This results in issues when explicitly having set the accessible properties of the target entity.

### What happened
In case of a new entity being associated through a BelongsToMany, the marshaller calls `_belongsToMany` and sets the join data on the target entity using the joint marshaller. In this case, no accessibility is forced before calling the `set`.

### What you expected to happen
I expect the `_joinData` property accessibility to be set to `true` before it is set to the target entity in `Marshaller::_belongsToMany`.

### References
Suggested accessibility change is expected here:
https://github.com/cakephp/cakephp/blob/3.x/src/ORM/Marshaller.php#L459

Deduction made that this should probably be done taken from here:
https://github.com/cakephp/cakephp/blob/3.x/src/ORM/Marshaller.php#L817

### Example
Students belongsToMany Courses through CourseMemberships
`Courses::$_accessible = ['id' => false, 'name' => true];`
```
        $studentsTable->patchEntity([
            'courses' => [
                [
                    'name'      => 'My Course',
                    '_joinData' => [
                        'joined_time' => new DateTime(),
                    ],
                ],
            ],
        ]);
```
In this case, the patched join data is not present on the new course entity, which is the case if the accessibility is changed at the suggested location.

**Comment by markstory** [comment]
Setting properties individually shouldn't involve the accessible fields checks. I'll see why the `_joinData` is not being marshalled, as it setting properties individually should always work.

**Comment by markstory** [comment]
I tried to reproduce this in our test suite and wasn't able to:

```php
    public function testMergeBelongsToManyImplicit()
    {
        $this->tags->setEntityClass(OpenTag::class);
        $options = ['associated' => ['Tags']];
        $data = [
            'title' => 'My title',
        ];
        $marshall = new Marshaller($this->articles);
        $entity = $marshall->one($data, $options);
        $this->assertEmpty($entity->tags);

        $data = [
            'title' => 'Haz data',
            'tags' => [
                ['tag' => 'Cake', '_joinData' => ['foo' => 'bar']],
                ['tag' => 'new tag', '_joinData' => ['active' => 1, 'foo' => 'baz']],
            ],
        ];
        $result = $marshall->merge($entity, $data, $options);

        $this->assertEquals($data['title'], $result->title);
        $this->assertTrue($result->isDirty('tags'));
        $this->assertSame('Cake', $entity->tags[0]->tag);
        $this->assertSame('bar', $entity->tags[0]->_joinData->foo);
    }
```

The `OpenTag` entity has an `accessible` attribute of `'tag' => true`  which doesn't include the `_joinData` attribute. The line you've referenced was run by the above test and it currently passes with no changes against 4.0.8.

**Comment by dorxy** [comment]
I'll see if I can reproduce it myself in a stand-alone project, this occurred in an existing project within our company. I'm still wondering why it would then be necessary in `_mergeJoinData` and not in `_belongsToMany`.

**Comment by dorxy** [comment]
This seems to be a bug created by ourselves because we overwrite `EntityTrait::set` and always turn it into an array before calling the parent, my bad. 🙈
