### ISSUE TITLE
3.x Connection::transactional doesn't catch Throwable

### ISSUE THREAD

**Issue by notpron** [cakephp/cakephp#14717]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12

If an Error occurs in a transaction, rollback isn't called. This is because Exception is caught instead of Throwable.

**3.x** implementation:
```php
    public function transactional(callable $transaction)
    {
        $this->begin();

        try {
            $result = $transaction($this);
        } catch (Exception $e) {
            $this->rollback(false);
            throw $e;
        }
```

**4.x** implementation:
```php
    public function transactional(callable $transaction)
    {
        $this->begin();

        try {
            $result = $transaction($this);
        } catch (Throwable $e) {
            $this->rollback(false);
            throw $e;
        }
```

**Comment by ADmad** [comment]
3.x supports PHP 5.6+ and 5.6 doesn't have the `Throwable` interface, hence it can't be used.

Have you encountered any actual issue with this? `Exception` is enough to catch any normal case of db failure.

**Comment by notpron** [comment]
This was encountered when null was passed to a function that wasn't expecting it. This caused a TypeError to be thrown.

**Comment by ADmad** [comment]
`TypeError` can usually be caught with static analysis so that it doesn't become a problem at runtime.

Regardless, as I stated above we can't use `Throwable` in 3.x due to PHP 5.6 support and your issue won't occur in 4.x, so the solution is to upgrade :slightly_smiling_face:.

I personally am not in favour of littering the 3.x codebase with PHP version checks and switching the interface/class used for catching errors accordingly.

**Comment by dereuromark** [comment]
Actually, we can and should also use Throwable here, both can be chained
The Throwable will just be ignored in 5.x - we did that before all over the place in the past as well by the way.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/blob/3.next/src/Error/Middleware/ErrorHandlerMiddleware.php#L97-L100

**Comment by tersmitten** [comment]
@dereuromark That sounds like a good solution. Do we need to prepare a pull request?

**Comment by dereuromark** [comment]
I guess this could even go into master as bugfix.
But if it is not that time sensitive, 3.next (soon to be released as stable) could also work.

**Comment by tersmitten** [comment]
I think I prefer `master`, because we have some issues with it

**Comment by notpron** [comment]
Thanks all for the quick answers. I hope the PR is pointing to the right branch :)

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/14721
