### ISSUE TITLE
Entity::getOriginal behaves inconsistently when using increment/decrement operators

### ISSUE THREAD

**Issue by josephshanak** [cakephp/cakephp#14723]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11 - 74f2083bc612b438f30bb9bff86bea65d6bd19bf
* Platform and Target: PHP 7.2.31

### What you did
This test illustrates the issue. `Entity::getOriginal` behaves inconsistently when modifying properties using increment/decrement operators.

```
    public function testGetOriginalPlusEquals(): void
    {
        $subject = new Entity(['property' => 0]);
        $subject->property += 1;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(1, $subject->property);
    }

    public function testGetOriginalPrefixIncrement(): void
    {
        $subject = new Entity(['property' => 0]);
        ++$subject->property;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(1, $subject->property);
    }

    public function testGetOriginalPostfixIncrement(): void
    {
        $subject = new Entity(['property' => 0]);
        $subject->property++;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(1, $subject->property);
    }

    public function testGetOriginalMinusEquals(): void
    {
        $subject = new Entity(['property' => 0]);
        $subject->property -= 1;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(-1, $subject->property);
    }

    public function testGetOriginalPrefixDecrement(): void
    {
        $subject = new Entity(['property' => 0]);
        --$subject->property;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(-1, $subject->property);
    }

    public function testGetOriginalPostfixDecrement(): void
    {
        $subject = new Entity(['property' => 0]);
        $subject->property--;
        $this->assertEquals(0, $subject->getOriginal("property"));
        $this->assertEquals(-1, $subject->property);
    }

```

These tests fail:
* `testGetOriginalPlusEquals`
* `testGetOriginalPrefixIncrement`
* `testGetOriginalMinusEquals`
* `testGetOriginalPrefixDecrement`

Issue #14297 documents this, however it is closed because this is fixed in PHP 7.3. I still think this is an issue though because the minimum supported version of PHP for CakePHP 4 is PHP 7.2 and for CakePHP 3 is 5.6.

These tests also fail on ff1ed12cd208f363323b79391d270a06a580b3ef (see my for https://github.com/josephshanak/cakephp/tree/get-original-increment-bug)

### What happened
When changing an entity property value using `+=`/`++`, the original value seems to be overridden, making it impossible to get the original value.

### What you expected to happen
I'd expect that when changing an entity property value using `+=`/`++` that the original value is still accessible via `Entity::getOriginal`.

**Comment by dereuromark** [comment]
I think the same reason stated in that linked ticket still applies:

 > Closing as this is fixed by using a new PHP version that calls magic methods better.

That is an issue of the language itself it seems. And people are already able to use this, as right now the default PHP version for both 3.x and 4.x is expected to be 7.3+ (ideally 7.4).
See EOL chart for PHP. If you use a version below that, it is your own problem and fault. Not of the language or the framework.

That said: If you can find a way to fix this, a PR would sure be welcome. But given the complexity of such a low level issue probably difficult to do.

**Comment by josephshanak** [comment]
Do you know where this change in PHP is documented? (Such as a PHP bug). It would be nice to reference it when suggesting we update to PHP 7.3 / 7.4.

I think it's a fair argument that PHP 7.2 is EOL, but updating is sometimes difficult.

**Comment by dereuromark** [comment]
They probably fixed that rather silently along the way.
