### ISSUE TITLE
Bug in SchemaShell when Update Schema

### ISSUE THREAD

**Issue by kamelj** [cakephp/cakephp#14720]
This is:
* [x] bug

* CakePHP Version: 2.10.19

### What you did
Using the cake command for update database schema:
"Console/cake schema update"

### What happened
The command not working and get this error message:
Error: Missing cache configuration for "default" 

That because of line number 56 in the file: "/lib/Cake/Console/Command/SchemaShell.php"
`Configure::write('Cache.disable', 1);`

This error happened because the line number 49 in file "/lib/Cake/Model/Datasource/CacheSource.php"
`if(Configure::read('Cache.disable') === true)`

### What you expected to happen
After I changed the line number 56 in the file: "/lib/Cake/Console/Command/SchemaShell.php"
to be like this:
`Configure::write('Cache.disable', true);`

It's worked fine hope to add this fix in the next release.

Thanks

**Comment by markstory** [comment]
Pull request open now.

**Comment by kamelj** [comment]
Thanks for the quick response.
I have more enhancements for this section "Schema management and migrations" on Cake 2.x version I found some issues related to updating schemes like handling the view as a table so could you add me to contributions list.
And I'm wondering there is a date to stop supporting 2.x Cake release?

Thanks

**Comment by ADmad** [comment]
> I found some issues related to updating schemes like handling the view as a table so could you add me to contributions list.

You can just fork the repo, make your changes and create a pull request.

> And I'm wondering there is a date to stop supporting 2.x Cake release?

https://github.com/cakephp/cakephp/wiki#2x-security-mode
