### ISSUE TITLE
Console command unable to parse quoted string starting with "-" as argument

### ISSUE THREAD

**Issue by ghost** [cakephp/cakephp#14733]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.8
* Platform and Target: Linux server CLI

### What you did
I added new argument "since" to my console command handling dates in past.
```
 public function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        $parser
            ->addArgument(
                'since',
                ['help' => 'Update range start date']
            );

        return $parser;
    }
```

### What happened
Passing quoted string "-1 day" as positional argument gives error:
```
$ bin\cake update_stuff "-1 day"
Error: Unknown short option `1`.
```
Passing "1 day" as argument works as expected:
```
$ bin\cake update_stuff "1 day"
string(5) "1 day"
```

### What you expected to happen
I expected to get string "-1 days" by calling `$since = $args->getArgument('since');` in my command main code.

As workaround I changed options parser setup to use `addOption()` instead of `addArgument()` and called the command successfully:
```
$ bin\cake update_stuff --since "-1 day"
string(6) "-1 day"
```

**Comment by markstory** [comment]
I don't think this is fixable. The option parser will see `-1 day` with no quotes and `-1` looks the same an option. While checking for spaces and excluding those from being considered as options would fix this situation, it would not fix the same problem for values like `-1day`. Using an option is your best option here.

**Comment by othercorey** [comment]
It might be possible to parse it if there are no options defined.

**Comment by markstory** [comment]
All commands have `--help` though, adding loopholes for a scenario that seems like an infrequent one and one that has good alternatives seems like unnecessary complexity for us to maintain.

**Comment by othercorey** [comment]
Agreed. We would have to check that it doesn't match any options and that an argument is expected. That would require double parsing and possibly other edge cases.

**Comment by garas** [comment]
Bash commands uses `--` as the end of command options, after which only positional arguments are accepted.

Options parser could be adjusted to support `--`, so `bin\cake update_stuff -- "-1 day"` would be accepted as argument.

**Comment by othercorey** [comment]
That could work.

**Comment by dereuromark** [comment]
Quoting or the -- option are both suitable workarounds or solutions to this.
