### ISSUE TITLE
Wrong type hint in I18n functions php docblock

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#14732]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.8.6
* Platform and Target: Linux Ubuntu 18.04. PHP 7.2

### What you did
Update CakePHP in an existing project

### What happened
The IDE (Phpstorm) began complaining  about "Expected parameter of type 'array|array[]', 'string' provided" in every function like this `__('some string with placeholder {0}', 'Placeholder')` with strings arguments, besides that, the functions works as expected when executing it.

### What you expected to happen
As it was a minor version update, and it's backward compatible, shouldn't be argument's type mismatch.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/blob/master/src/I18n/functions.php#L29
It looksl like the IDE doesnt quite understand the new `...$args` syntax here.
Functionality, nothing is broken, though. This is only some IDE warning issue here at this point.

**Comment by dereuromark** [comment]
I see that the documented type is array for 3.x, but `mixed` for 4.x
This might be the issue, should probably be adjusted here.

**Comment by ADmad** [comment]
Typehint declaration for this method is tricky since it has 2 forms. You can use it with variadic args like `__('some string {0} {1}', 'val1', 2)` or pass 2nd argument as array `__('some string {0} {1}', ['val1', 2])`. So the `array` type used in 3.x will generate error when using 1st form. 

The solution is to use `mixed` as done for 4.x.

**Comment by xavier83ar** [comment]
Yep, as @ADmad said, there are 2 forms of using it, but the IDE can handled it both, at least phpstorm, it understands the variadic argument, in fact, right now is expecting an array or an array of arrays... so if the type hint is `@param string ...$args` it will get it right in both forms, I've tested, but in phpstorm only.

**Comment by dereuromark** [comment]
Thats a good point. If we typehint `string` here only (which we should as it is string or string[], right?), then the variadic part here should auto-clarify the string[] part as well.

**Comment by dereuromark** [comment]
Never mind, we need to use mixed, as you can also pass float, int and other types to be casted as per need.

**Comment by ADmad** [comment]
We should have dropped support for using array as second argument in 4.x, most people would find using variadic more convenient. But that ship has sailed :)

**Comment by xavier83ar** [comment]
@dereuromark it seems that with only `@param string ...$args` works ok, and the IDE handle both string and string[]. But yeah, it should be mixed.

@ADmad do not forget that the array functions enable us to use named replacement using it this way 

```php
__('{icon} Back to the list', ['icon' => '<i class="fas fa-fw fa-angle-left"></i>'])
```
and I find it convenient sometimes because it can hint the translators about what it gona be there.

**Comment by ADmad** [comment]
@xavier83ar Ah, I forgot about named placeholders, so nothing to change :)

**Comment by dereuromark** [comment]
This is the commit that needs backporting: https://github.com/cakephp/cakephp/commit/fafaf67efd56f5ac06f393e1b68fedea03805ad4
