### ISSUE TITLE
[4.1] config/routes.php isn't loaded

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#14744]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0-RC2
* Platform and Target: Linux / nginx

### What you did

Upgraded a app from CakePHP 3.9 to 4.1-RC2 and notice only plugins routes are loaded.

I revised Cookbook about upgrading, routes and don't found nothing to help.

### What happened

Exception talking I doesn't have a `'/'` route defined.

### What you expected to happen

`routes.php` read and page load.

If I override `Application::routes` to always read my route file, everything work fine.
Tried also clear my cache with `bin/cake cache clear_all`, but didn't help.

I found when the change are made: https://github.com/cakephp/cakephp/commit/5dee28709cffe6e4ca66e9a8c26bcd28e65ab344

Checked my _RoutingMiddleware_ setup and its equal of `cakephp/app` source.

My `Application.php` setup is:

```php
    public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        $middlewareQueue
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))
            ->add(new AssetMiddleware([
                'cacheTime' => Configure::read('Asset.cacheTime')
            ]))
            ->add(new RoutingMiddleware($this, '_cake_routes_'))
            ->add(new BodyParserMiddleware());

        return $middlewareQueue;
    }
```

I doesn't have any other methods beside `middleware`, `bootstrap` and `bootstrapCli` loading plugins.

**Comment by ADmad** [comment]
Maybe it's a caching issue. Remove the second argument from `RoutingMiddleware` constructor here  `->add(new RoutingMiddleware($this, '_cake_routes_'))` (and remove the `Application::routes()` method).`

**Comment by CauanCabral** [comment]
> Not exactly 🙂 https://github.com/cakephp/app/blob/79299f3d25ede1b897f64e12e137f82bcce9ed7c/src/Application.php#L86

Tried this also, didn't help =(

> Maybe it's a caching issue. Remove the second argument from `RoutingMiddleware` constructor here `->add(new RoutingMiddleware($this, '_cake_routes_'))` (and remove the `Application::routes()` method).`

This too =(

**Comment by markstory** [comment]
I don't think we'll be able to help much without a way to reproduce. You might want to implement the routes() method on your Application class and ensure that it is being called (it should be).

**Comment by CauanCabral** [comment]
Thanks guys, I created a new dummy app to reproduce - and, everything is ok.

So, I put log call to `RouteCollection::add` to see who's initializing it, and is the `CakeDC/Auth` plugin: https://github.com/CakeDC/auth/blob/master/config/bootstrap.php

I'll open a issue or a pr for it.

Thanks again.
