### ISSUE TITLE
set BelongsToMany targetBindingKey 

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#14745]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.9.

I am trying to set specific targetBindingKey for belongsToMany association.

Default targetBindingKey  is target table primary key. I want to use another key for example: post_id instead id

topics -> topics_posts[topic_id,post_id] <- news[id , post_id]

**Comment by ADmad** [comment]
Care to elaborate what's this about?

**Comment by othercorey** [comment]
This should be fixed in 4.1. 

https://github.com/cakephp/cakephp/pull/14377

**Comment by othercorey** [comment]
I also ported this to 3.9 for anyone interested.
