### ISSUE TITLE
Add support to belongsToMany for the same table (using a join table)

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#14752]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.*
* Platform and Target: Any

### What you did
I've create two tables: 

1- users (_id, name_)
2- users_users (_id, user_id, user_relative_id, kinship_)

**user_id** and **user_relative_id** references to **users.id**

And inserted two rows on users and one on users_users

I've Tried on **UsersTable.php:**

```php
$this->belongsToMany('Users')
			->setTargetForeignKey('user_relative_id')
			->setForeignKey('user_id');
```
and on Controller:

```
$users = TableRegistry::getTableLocator()->get('Users');
		$result = $users->find()->contain('Users')->toArray();
		var_dump($result);
```

### What happened
Cake returns this:

```
[
	(int) 0 => object(App\Model\Entity\User) {
		'[new]' => false,
		'[accessible]' => [
			'name' => true,
			'users' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[hasErrors]' => false,
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Users'
	
	},
	(int) 1 => object(App\Model\Entity\User) {
		'id' => (int) 2,
		'name' => 'Maria',
		'users' => [],
		'[new]' => false,
		'[accessible]' => [
			'name' => true,
			'users' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[hasErrors]' => false,
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Users'
	
	}
]
```

### What you expected to happen
I've expected the result that was only possible doing this "workaround":

1- created a "alias":

```php
class UsersMirrorTable extends UsersTable {}
```

2- made another association:

```
$this->belongsToMany('UsersMirror')
			->setTargetForeignKey('user_relative_id')
			->setForeignKey('user_id');
```
and got the correct result:
```

[
	(int) 0 => object(App\Model\Entity\User) {
		'id' => (int) 1,
		'name' => 'José',
		'users_mirror' => [
			(int) 0 => object(Cake\ORM\Entity) {
				'id' => (int) 2,
				'name' => 'Maria',
				'_joinData' => object(App\Model\Entity\UsersUser) {
					'id' => (int) 1,
					'user_id' => (int) 1,
					'user_relative_id' => (int) 2,
					'kinship' => 'father',
					'[new]' => false,
					'[accessible]' => [
						'user_id' => true,
						'user_relative_id' => true,
						'kinship' => true,
						'user' => true
					],
					'[dirty]' => [],
					'[original]' => [],
					'[virtual]' => [],
					'[hasErrors]' => false,
					'[errors]' => [],
					'[invalid]' => [],
					'[repository]' => 'UsersUsers'
				
				},
				'[new]' => false,
				'[accessible]' => [
					'*' => true
				],
				'[dirty]' => [],
				'[original]' => [],
				'[virtual]' => [],
				'[hasErrors]' => false,
				'[errors]' => [],
				'[invalid]' => [],
				'[repository]' => 'UsersMirror'
			}
		],
		'[new]' => false,
		'[accessible]' => [
			'name' => true,
			'users' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[hasErrors]' => false,
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Users'
	},
	(int) 1 => object(App\Model\Entity\User) {
		'id' => (int) 2,
		'name' => 'Maria',
		'users_mirror' => [],
		'[new]' => false,
		'[accessible]' => [
			'name' => true,
			'users' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[hasErrors]' => false,
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Users'
	}
]
```
Edit: a second workaround too:

```php
		$this->belongsToMany('UsersAssociated')
			->setClassName('Users')
			->setTargetForeignKey('user_relative_id')
			->setForeignKey('user_id');
```

I've seen that you guys are working recently on something similar (https://github.com/cakephp/cakephp/pull/14377) so I think this could be a good timing.

**Comment by othercorey** [comment]
This isn't possible because BelongsToMany will try to create 2 different associations on the same table. I think 4.1 throws an exception on this.

**Comment by celsowm** [comment]
> 
> 
> This isn't possible because BelongsToMany will try to create 2 different associations on the same table. I think 4.1 throws an exception on this.

I can test it, how can I "force" composer to update to cakephp 4.1?

**Comment by othercorey** [comment]
You can require cakephp/cakephp:4.1.0-RC2.

**Comment by celsowm** [comment]
@othercorey updated and tested and no, no exception throwed (and yes, the bug of empty entity stills persists)

**Comment by othercorey** [comment]
The only way this can work is if you create another UsersTable (RelativeUsersTable) and create the association between UsersTable and RelativeUsersTable. You can set RelativeUsersTable to use the same db table name.

I will try to add an exception for the default case.

**Comment by celsowm** [comment]
> 
> 
> The only way this can work is if you create another UsersTable (RelativeUsersTable) and create the association between UsersTable and RelativeUsersTable. You can set RelativeUsersTable to use the same db table name.
> 
> I will try to add an exception for the default case.

```php
$this->belongsToMany('RelativeUsersTable')
			->setClassName('Users')
			->setTargetForeignKey('user_relative_id')
			->setForeignKey('user_id');
```
This solution could be used and something like this will not fall on your **alias == alias** exception, right?

**Comment by othercorey** [comment]
You need to create a table class named `RelativeUsersTable`.

**Comment by LordSimal** [comment]
As othercorey explained adding a separate/copy of the self referencing TableClass indeed fixes the issue of receiving the exception
```
The `X` association on `Y` cannot target the same table.
```
