### ISSUE TITLE
CaseExpression doesn't support boolean false value

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14753]
If you use a boolean `false` value in the case expression, you get a PDO error:

> Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""

```
$query->newExpr()->addCase(
    $query->newExpr()->add(['is_true' => false]),
    0
);
```

**Comment by marlonbrando-real** [comment]
test

**Comment by marlonbrando-real** [comment]
test
@messi-source

**Comment by marlonbrando-real** [comment]
test
@messi-source

**Comment by markstory** [comment]
Does `0` work in this scenario?

**Comment by othercorey** [comment]
> Does `0` work in this scenario?

0 is valid for the db I'm using along with a couple other string values. I haven't tested how all of them work with prepare statements.

**Comment by markstory** [comment]
Ok. Have you tried using the types parameter (3rd parameter) to map the type of your condition?

**Comment by othercorey** [comment]
If you mean this, then it makes no difference. 
```
$query->newExpr()->addCase(
    $query->newExpr()->add(['is_true' => false]),
    0,
    'boolean'
);
```

That seems to rely on `ExpressionTypeInterface` implemented by the type. However, only `OrderedUuidType` implements any of that. Otherwise, the value is untouched.

**Comment by markstory** [comment]
I think you need to set the types on the condition expressions. While I didn't execute this SQL fragment the generated SQL and bindings seem correct:

```php
        $trueCond = new QueryExpression();
        $falseCond = new QueryExpression();
        $case = new QueryExpression();
        $case->addCase(
            [
                $trueCond->add(['is_true' => false], ['is_true' => 'boolean']),
                $falseCond->add(['is_true' => true], ['is_true' => 'boolean'])
            ],
            ['no', 'yes'],
            ['string', 'string']
        );
        $expected = 'CASE WHEN is_true = :c0 THEN :param1 WHEN is_true = :c2 THEN :param3 END';
        $binder = new ValueBinder();
        $this->assertSame($expected, $case->sql($binder));
        $expected = [
            ':c0' => ['value' => false, 'type' => 'boolean', 'placeholder' => 'c0'],
            ':c2' => ['value' => true, 'type' => 'boolean', 'placeholder' => 'c2'],
            ':param1' => ['value' => 'no', 'type' => 'string', 'placeholder' => 'param1'],
            ':param3' => ['value' => 'yes', 'type' => 'string', 'placeholder' => 'param3'],
        ];
        $this->assertEquals($expected, $binder->bindings());

```

**Comment by othercorey** [comment]
Adding the type to the `add()` call works for `false`. `PDOStatement` must be converting it internally since BoolType leaves it unchanged.

```
$trueCond->add(['is_true' => false], ['is_true' => 'boolean']),
```
