### ISSUE TITLE
Collection : Append and shuffle problem

### ISSUE THREAD

**Issue by DrMickArtisan** [cakephp/cakephp#14757]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.7.9
* Platform and Target: apache2, mysql on ubuntu 18

### What you did
I was just making two requests and append the two results Set :
`$Trouvables = $this->Lesobjets->find('Region',['region_id' => $options['position']['region']['id']])->find('action', ['action' => $options['action']])->distinct('Lesobjets.id');`
(gives 12 results)
`$TrouvablesAussi = $this->Lesobjets->find('NoRegion')->find('action', ['action' => $options['action']])->distinct('Lesobjets.id');`
(gives 1 result)
Then I try to pick a random element : 
`$laListe = $Trouvables->append($TrouvablesAussi)->shuffle();`
### What happened
In fact,  after applying shuffle(), the resulting set contain only 12 objects.

### What you expected to happen
There was 13 objects before applying shuffle() so I expected to obtain 13 objects after :)

After a close examination of code, It seems that this is because shuffle() use a toArray() transformation on resultSet(), instead of toList(). As the first collection has object numbered from 0 to 11, appending another collection with 1 object at key 0 leads to overwrite of the first one by toArray().

**Comment by othercorey** [comment]
We should probably document the other uses of `toArray()` in CollectionTrait. I think `toArray()` is correct for both of these, but still it's a hidden change.

- `jsonSerializable()`
- `countKeys()`
