### ISSUE TITLE
Support Throwable in FlashComponent::set

### ISSUE THREAD

**Issue by hakito** [cakephp/cakephp#14768]
Wouldn't it be possible (in Cake 4) to use _Throwable_ instead of _Exception_ in FlashComponent::set()?

https://github.com/cakephp/cakephp/blob/12e88528685e8a7b0da841dab3659e71f1849890/src/Controller/Component/FlashComponent.php#L73

**Comment by ADmad** [comment]
Sure, would you like to submit a pull request?

**Comment by hakito** [comment]
Accidently closed this issue

**Comment by dereuromark** [comment]
After you opened the PR closing is fine. Your PR looks like it wilö be merged.
