### ISSUE TITLE
Test Component with Session Based Authentication 

### ISSUE THREAD

**Issue by byuilazenbyt** [cakephp/cakephp#14760]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.9
* Platform and Target: Testing on my localhost using XAMMP using the integrated PHPUnit tester in PHPStorm to try and get the user's user_id. 

### What you did
Created method to simulate logging in with my User Fixture which has a user_id of 1.

```
// CSVComponentTest.php
public function testRemoveDuplicates(): void
{
    $this->login();
    // Other Code
}

protected function login($userId = 1)
{
    $users = TableRegistry::getTableLocator()->get('Users');
    $user = $users->get($userId);
    $this->session(['Auth' => $user]);
}

// CSVComponent.php
public function sortOutUpdates($imports)
{
    $appController = new AppController();
    $user = $appController->Authentication->getIdentity()->getOriginalData();
    $user_id = $user->id;
    // Other code
}
```

### What happened
I get the following error: Error : `Call to a member function getOriginalData() on null`

### What you expected to happen
I would expect to have the user_id be assigned to the $user_id

**Comment by markstory** [comment]
Your test is not compatible with how the authentication plugin or authcomponent work. The authentication plugin relies on request attributes that are not being set in your test case. Instead you should use the integration testing features in CakePHP, or build the required Identity object and set it into the request.

**Comment by byuilazenbyt** [comment]
I am going off the documentation here, and thought that this would be setting it to the session

[https://book.cakephp.org/authentication/2/en/testing.html#session-based-authentication](https://book.cakephp.org/authentication/2/en/testing.html#session-based-authentication)

I know how to create an Identity object, how would I send it to the request and make sure the request was run with the test?

**Comment by ADmad** [comment]
Closing as I helped sort of his issue in Slack.
