### ISSUE TITLE
Can not load a Plugin Behavior in model.

### ISSUE THREAD

**Issue by zsfoto** [cakephp/cakephp#14771]
* [x] bug

* CakePHP Version: 4.0.9.
* Platform and Target: WAMP Server 3.1.9

### I develop an own admin plugin. I tried a use a Plugin Behavior in model. The plugin is loaded.

In Model: **$this->addBehavior('JeffAdmin.Datepicker');** _(After the $this->addBehavior('Timestamp');)_

**The answer is:** JeffAdmin.DatepickerBehavior could not be found.
**Error:** Create the class DatepickerBehavior below in file: D:\www\jeffadmin.loc\plugins\JeffAdmin\src\Model\Behavior\DatepickerBehavior.php

```
<?php
namespace JeffAdmin\Model\Behavior;
use Cake\ORM\Behavior;
class DatepickerBehavior extends Behavior
{
}
```

I created this file the in path and content.

![jeffadmin](https://user-images.githubusercontent.com/53469564/86761960-9ea3cc80-c046-11ea-9844-7825239f7233.jpg)

![plugins](https://user-images.githubusercontent.com/53469564/86762243-ce52d480-c046-11ea-89a6-f02708ddc6d4.jpg)

![model](https://user-images.githubusercontent.com/53469564/86762784-2984c700-c047-11ea-8e00-d7937c1b6139.jpg)

**Comment by dereuromark** [comment]
This sounds like a developer error and configuration mistake
You most likely didn't set up the correct autoload part in your composer.json, thus the autoloader of composer not able to find it.
For help refer to the docs or the existing plugins.
There is pretty sure no bug here on core side, though.

**Comment by zsfoto** [comment]
Dear @dereuromark!

Can you tell me what I forgot? I installed a new CakePHP 4 and the settings are below. my plugin is in **plugins/JeffAdmin**. 
Everything works fine so far only Behavior doesn't work. Plugin Behavior is not available as I wrote above.

Thank you!

Here is my settings:

In config/**bootstrap.php**:
```
Configure::load('JeffAdmin', 'default');
Configure::write('Bake.theme', 'JeffAdmin');
```

And the config/**jeffadmin.php** exists.

In config/**routes.php**:
```
$routes->prefix('admin', function ($routes) {
    $routes->connect('/', ['controller' => 'Posts', 'action' => 'index']);  // pl.
    $routes->fallbacks(DashedRoute::class);
});
```


In src/**Application.php:**
```
public function bootstrap(): void
{
    // Load more plugins here
    $this->addPlugin('JeffAdmin', ['routes' => true]);
}
```

In src/Controller/**Admin/AppController.php** with:
`namespace App\Controller\Admin;`

AND

```
public function initialize(): void
{
    parent::initialize();
	...
    $this->viewBuilder()->setTheme('JeffAdmin');
}
```

**Comment by dereuromark** [comment]
Whats your composer autoload setup?

**Comment by zsfoto** [comment]
@dereuromark, thank you very much!
It seems to work now. 
I develop this plugin but composer is not yet.
I manually made everything anf i learn a lot during develop time.
