### ISSUE TITLE
NumberHelper uses deprecated Number Utility method

### ISSUE THREAD

**Issue by julianpollmann** [cakephp/cakephp#14776]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: >3.9.0

### What you did
Set the Default Currency for the NumberHelper in AppView: `$this->Number->defaultCurrency('EUR');`

### What happened
Raised this Deprecation Warning:
```
Deprecated (16384): Number::defaultCurrency() is deprecated. Use Number::setDefaultCurrency()/getDefaultCurrency() instead. - /usr/www/xxx/vendor/cakephp/cakephp/src/View/Helper/NumberHelper.php, line: 228
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 305]
```
The NumberHelper doesn't have these getter/setter methods, only the Cake\I18n\Number Utility.

### What you expected to happen
Getter/Setter methods for NumberHelper.

**Comment by dereuromark** [comment]
I guess using too much mocks is just always a bad idea.

    $number = $this->getMockBuilder(__NAMESPACE__ . '\NumberMock')
            ->setMethods([$method])
            ->getMock();

That's why this wasn't found so far.

**Comment by dereuromark** [comment]
Both 3.9 and 4.1 have been updated.
