### ISSUE TITLE
SQL Server maximum of parameters

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14775]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: Nginx, PHP 7.4, SQL Server

### What you did
Export CSV by run select query with fetching hasMany data.
Result has over 2100 rows.

### What happened
Below error occurred on associated select query.
```
Error: [PDOException] SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.
```

### What you expected to happen
No error occurred.

**Comment by ADmad** [comment]
You are exceeding the limits set by your database server. What do you expect the framework to do here?

**Comment by mcsknp** [comment]
I want to pass primary key values to associated query without adding any parameters.
Or adding an option to separate fetching associated data in many times.

**Comment by othercorey** [comment]
Please give an example of the query you're using that has so many parameters.

**Comment by mcsknp** [comment]
`Articles` has many `Comments`

- `articles` table
```
id
...
```

- `comments` table
```
id
article_id
...
```

- Sample code
```php
$query = $articlesTable->find()->contain(['Comments']);
foreach ($query as $row) {
    // ...
}
```

**Comment by garas** [comment]
Your `articles` table has likely over 2000 entries. [HasMany](https://book.cakephp.org/4/en/orm/associations.html#hasmany-associations) default strategy is `select`, and CakePHP will generate 
```sql
SELECT * FROM articles;
SELECT * FROM comments WHERE article_id IN (1, 2, 3, 4, 5); // Inserted using parameters
```

You can [change strategy](https://book.cakephp.org/4/en/orm/retrieving-data-and-resultsets.html#fetching-with-the-subquery-strategy) to `subquery`:
```php
$articles->find()->contain([
    'Comments' => ['strategy' => 'subquery']
]);
```
Instead second query will be
```sql
SELECT * FROM comments WHERE article_id IN (SELECT id FROM articles);
```

**Comment by mcsknp** [comment]
It's worked but it looks like query is becoming more slowly.

**Comment by garas** [comment]
Does SQL query executes slowly or PHP/CakePHP?

To speed up SQL query, check if `comments.article_id` has index on it.

From CakePHP side, hydrating thousands of rows to entities might be slow. Add `disableHydration()` to get results as PHP arrays.

**Comment by mcsknp** [comment]
I'm using `disableHydration()` so I thinks SQL is execute slowly because main query has many conditions with joining summary from other table. And this conditions will run more 1 times in sub query.

**Comment by othercorey** [comment]
I don't know if there is anything we can do here. We could try checking the param count and throw a more useful warning.

**Comment by mcsknp** [comment]
I think this problem can be solved if there is an option to separate fetching association to run many times.
```
SELECT * FROM comments WHERE article_id IN (1, 2, 3, 4, 5);
SELECT * FROM comments WHERE article_id IN (6, 7, 8, 9, 10);
```
Instead of
```
SELECT * FROM comments WHERE article_id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
```

**Comment by othercorey** [comment]
How is that better than changing the strategy to subquery?

**Comment by mcsknp** [comment]
It's faster when main query has many conditions.

**Comment by othercorey** [comment]
Running the same query multiple times doesn't seem better than a single subquery.

**Comment by mcsknp** [comment]
The result of subquery can be difference with result when run main query.

**Comment by othercorey** [comment]
The subquery to get id values might be expensive, but this is just a limitation of sqlserver.

**Comment by othercorey** [comment]
Added exception to help users fix their queries.
