### ISSUE TITLE
4.1: ORM regression with callbacks

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14788]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1

### What you did
Travis Test Suite for Tool started to become red with 4.1 release (7 days ago)
https://travis-ci.com/github/dereuromark/cakephp-tools/builds

Mysql
> 1) Tools\Test\TestCase\Model\Behavior\BitmaskedBehaviorTest::testSaveBasic
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'statuses' in 'where clause'

Postgres
> 1) Tools\Test\TestCase\Model\Behavior\BitmaskedBehaviorTest::testSaveBasic
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "statuses" does not exist
LINE 1: ...OM "bitmasked_comments" "BitmaskedComments" WHERE "statuses"...
HINT:  Perhaps you meant to reference the column "BitmaskedComments.status".

And also Sqlite (but here it lets the unknown field slide and only fails on assert afterwards):
> 1) Tools\Test\TestCase\Model\Behavior\BitmaskedBehaviorTest::testSaveBasic
Failed asserting that false is true.

This seems to be not specific to DB, so the callback (logic) in CakePHP itself must have changed in a BC breaking way.

### What happened

The beforeFind() callback seems compromised here and doesn't exchange the array values with the int bitmask as it used to do in 3.x/4.0.

So the search query stays

        [protected] _conditions => [
                (int) 0 => object(Cake\Database\Expression\Comparison) {
                        [protected] _value => [
                                (int) 0 => (int) 2,
                                (int) 1 => (int) 4
                        ]
                        [protected] _type => 'string[]'
                        [protected] _operator => 'in'
                        [protected] _isMultiple => true
                        [protected] _valueExpressions => []
                        [protected] _field => 'BitmaskedComments.statuses'
                }
        ]

instead of expected `status` of bitmask value `6`.

I didn't find any relevant part in migration guide: https://book.cakephp.org/4/en/appendices/4-1-migration-guide.html

The weird part about this is that locally it passes...
I use PHP 7.3 locally, but on Travis it fails for all versions, so that cannot be it either.

**Comment by dereuromark** [comment]
This is what it seems to have an issue with on Travis now since 4.1 came out:
```php
	/**
	 * @param \Cake\Event\EventInterface $event
	 * @param \Cake\ORM\Query $query
	 * @param \ArrayObject $options
	 * @param bool $primary
	 *
	 * @return void
	 */
	public function beforeFind(EventInterface $event, Query $query, ArrayObject $options, $primary) {
		$this->encodeBitmaskConditions($query);

		$field = $this->_config['field'];
		$mappedField = $this->_config['mappedField'];
		if (!$mappedField) {
			$mappedField = $field;
		}

		$mapper = function ($row, $key, $mr) use ($field, $mappedField) {
			/**
			 * @var \Cake\Collection\Iterator\MapReduce $mr
			 * @var \Cake\Datasource\EntityInterface|array $row
			 */
			if (!is_object($row)) {
				if (isset($row[$field])) {
					$row[$mappedField] = $this->decodeBitmask($row[$field]);
				}
				$mr->emit($row);

				return;
			}

			/** @var \Cake\Datasource\EntityInterface $entity */
			$entity = $row;
			if ($entity->has($field)) {
				$entity->set($mappedField, $this->decodeBitmask($entity->get($field)));
				$entity->setDirty($mappedField, false);
			}
			$mr->emit($entity);
		};
		$query->mapReduce($mapper);
	}
```
Specifically the encodeBitmaskConditions() not doing what it used to do:
```php
		$field = $this->_config['field'];
		$mappedField = $this->_config['mappedField'];
		if (!$mappedField) {
			$mappedField = $field;
		}

		$where = $query->clause('where');
		if (!$where) {
			return;
		}

		$callable = function ($comparison) use ($field, $mappedField) {
			if (!$comparison instanceof Comparison) {
				return $comparison;
			}
			$key = $comparison->getField();

			if ($key !== $mappedField && $key !== $this->_table->getAlias() . '.' . $mappedField) {
				return $comparison;
			}

			$comparison->setValue((array)$this->encodeBitmask($comparison->getValue()));
			if ($field !== $mappedField) {
				$comparison->setField($field);
			}

			return $comparison;
		};

		$where->iterateParts($callable);
```

**Comment by markstory** [comment]
@othercorey I wonder if this could be related to the changes made to fix missing clone operations, as the last code block is using `iterateParts` to mutate the where conditions during the `beforeFind` callback.

**Comment by othercorey** [comment]
If you replace `Comparison` with `ComparisonExpression`  does it work? Make sure to change the `use` statement.
