### ISSUE TITLE
Route issues, template Debugger::exportVar formatted Html instead of Text

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14785]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1 stable

In templates https://github.com/cakephp/cakephp/blob/master/templates/Error/missing_route.php#L52-L53 and https://github.com/cakephp/cakephp/blob/master/templates/Error/duplicate_named_route.php#L54-L55 exported route defaults and options get formatted by Debugger HtmlFormatter instead of TextFormatter, and `h()` will turn the resulting Html into escaped Html, making the output non-readable

I've not found quick way to change the current formatter in the call-chain, so i'm submitting bug report instead

**Comment by garas** [comment]
It is probably better leave dump in HTML, but remove `h()`,

**Comment by smarek** [comment]
@garas if you can keep the html expanded, why not, but in my case all the 2nd and 3rd level of information is collapsed, and i'ts impractical to have to click them all
