### ISSUE TITLE
Associated form inputs - merging by the ID

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14786]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: nginx, php7.4

Having Association like this **Book hasMany Author**
Entity of Book like this
```
Book => [
  id: 1,
  name: My Book
  authors: [
    [
      id: 2,
      name: Peter
    ],
    [
      id: 3,
      name: Jonathan
    ],
  ]
]
```

Creating Form like this
```php
echo $this->Form->create($book);

echo $this->Form->control('name'); // book name

echo $this->Form->control('authors.0.id', ['value' => 3);
echo $this->Form->control('authors.0.name', ['value' => 'Jonathan']);

echo $this->Form->control('authors.1.id', ['value' => 2);
echo $this->Form->control('authors.1.name', ['value' => 'Peter']);

echo $this->Form->submit();
echo $this->Form->end();
```

Will on `$this->Books->patchEntity($book, $this->getRequest()->getData())` switch the IDs and Names in the entities, where one would expect the patching to match the associated controls by ID, not by order in Query/Result

**Comment by markstory** [comment]
> Will on $this->Books->patchEntity($book, $this->getRequest()->getData()) switch the IDs and Names in the entities, where one would expect the patching to match the associated controls by ID, not by order in Query/Result

Is this a question? The ORM attempts to use entity primary keys to match entities to their updated data. Your example would result in a no changes as you've not changed the name on either entity and only shuffled the order, however the order of entities isn't important to the patching process.

**Comment by smarek** [comment]
I'm sorry, there was another issue, the question/bug I reported originally is not caused by framework. Closing as invalid, and thank you for the response
