### ISSUE TITLE
CSRF token expiration / update after request/form submit

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#14780]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1 / 3.9
* Platform and Target: nginx / php7.4

Currently CSRF tokens, through CsrfProtectionMiddleware are generated once, and last users browser session by default (option `expiry`), there was previously (CakePHP 2.x) option `SecurityComponent->csrfUseOnce` to use each token only once, and regenerate, which has a lot of sharp edges and degrades user experience

I'd like to know, if you'd consider optional feature, that would expire the CSRF token after submitting page (POST/PUT/PATCH/DELETE) to prevent
  - Double form submission errors
  - Persistent CSRF bypass, once the attacker is able to obtain current CSRF token once, which is fixable only by invalidating user session / closing user browser

This should balance out the user user-experience and obtaining possible security through CSRF protection

**Comment by markstory** [comment]
> once the attacker is able to obtain current CSRF token once, which is fixable only by invalidating user session / closing user browser

How are attackers getting CSRF tokens?

> I'd like to know, if you'd consider optional feature, that would expire the CSRF token after submitting page (POST/PUT/PATCH/DELETE) to prevent

You can do this today in your application by unsetting the csrfToken cookie and then using the CsrfProtectionMiddleware's createToken() method to generate a new token.

How would this new feature work? Would it be generally enabled for all requests? or only on a subset of paths?

**Comment by smarek** [comment]
> How are attackers getting CSRF tokens?

Hijacking the browser session, by attacking TLS/SSL, attacking underlying OS or hijacking browser with extension/malware.

This particular test of course nothing that complicated, he just used 2 browsers on same computer and cookie editor extensions and Burp proxy, but once the token is obtained, it's valid in any request to the server with same Security salt, disregarding IP/browser identification/session ID/user ID

> You can do this today in your application by unsetting the csrfToken cookie and then using the CsrfProtectionMiddleware's createToken() method to generate a new token.

You mean subclassing CsrfProtectionMiddleware and adding the logic, in Applications `middleware()` or in AppController beforeFilter/beforeRender ? Also access the method by creating new instance, or accessing the one created in Applications middleware() ?

> How would this new feature work? Would it be generally enabled for all requests? or only on a subset of paths?

New option, for next few minor versions disabled, possibly enabled with next major version, applied to all routes the middleware applies to (if applied through routes), configurable if
  - csrfToken is re-generated on every request - middleware does automatically
  - csrfToken is re-generated on match with array of HTTP method (eg. allowing to re-generate on POSTS but not on GETs when webapp, but allowing to re-generate on-demand - middleware does automatically
  - csrfToken is re-generated on-demand, ie. when business/controller logic decides to - this can be enabled automatically - middleware does by consuming emitted signal / setting session var correctly / etc.

**Comment by markstory** [comment]
> Hijacking the browser session, by attacking TLS/SSL, attacking underlying OS or hijacking browser with extension/malware.

At this point CSRF is the least of your concerns, as this attacker has already compromised the session token as well.

> You mean subclassing CsrfProtectionMiddleware and adding the logic, in Applications middleware() or in AppController beforeFilter/beforeRender ? Also access the method by creating new instance, or accessing the one created in Applications middleware()?

You could create another middleware in your application that uses/extends CsrfProtectionMiddleware. 

> New option, for next few minor versions disabled, possibly enabled with next major version, applied to all routes the middleware applies to (if applied through routes), configurable if 

Regenerating the CSRF token on every request is a useful mode, it will break as soon as there are any XHR requests, or multiple tabs are involved. You'll run into similar problems regenerating the CSRF token on each POST/PUT/DELETE.

Using application logic to signal when a cookie needs to be regenerated will give application developer the most control and will let them do CSRF token replacements on important events like authentication changes.

**Comment by smarek** [comment]
Ok, so best option is create custom csrf middleware and be more careful with the token through binding it to session-id or user-id if possible ? that way if only the csrf token is stolen, it is useless, if it is stolen together with session cookie, there are other means of securing the user data

**Comment by markstory** [comment]
I think that's a good idea if you need to scope CSRF tokens further. We can't easily use the session id as we don't want to forcibly start the session on each request to validate/create a CSRF token. At the framework level we could use the user's user-agent and/or IP address to further scope the CSRF token, but I'm not sure those are helpful in the scenarios you're concerned about.

**Comment by smarek** [comment]
Session does not need to be forced, something along the lines,

```php
regenerate_csrf_token = false
params_to_hash = [ user-agent, client-ip ]
if (session is started) {
  params_to_hash += [phpsession-id]
}
if ($this->getConfig('user_callback') instanceof Closure) {
  list(app_regenerate_csrf_request, app_provided_params) = user_callback($request)
  params_to_hash += user_provided_params
  if (app_regenerate_csrf_request) {
    regenerate_csrf_token = true
  }
}
if (regenerate_csrf_token || $this->validateToken($request, params_to_hash) !== true) {
  $token = $this->createToken(params_to_hash)
}

**Comment by smarek** [comment]
Til the discussion is resolved, either way, I've came up quickly with CsrfUserProtectionMiddleware, that tighly couples the current Identity's Identifier from Session to CSRF token, sharing for anybody who would need

```php
<?php
declare(strict_types=1);

namespace App\Middleware;

use Authentication\IdentityInterface;
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Http\ServerRequest;
use Cake\Utility\Hash;
use Cake\Utility\Security;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Modified CsrfProtectionMiddleware allowing tight link between Identity in Session (Authentication)
 * and CSRF protection token.
 *
 * Original process not modified if the current request has no session or no Identity in Session,
 * however once the identity is provided the CSRF token is kept up-to-date with Identity's Identifier
 * on each GET request
 *
 * Provides configurable HMAC hashing alogirthm (by default sha2-512)
 *
 * @copyright   Copyright (c) Marek Sebera (https://github.com/smarek)
 * @license     http://www.opensource.org/licenses/mit-license.php MIT License
 */
class CsrfUserProtectionMiddleware extends CsrfProtectionMiddleware
{

    /**
     * Indication if identity was found in current request
     * @var boolean
     */
    private bool $identityFoundInSession = false;
    private string $identifierFromFoundIdentity;
    /**
     * Key for HMAC hash algorithm in $config passed to constructor
     *
     * @var string
     */
    public const CONFIG_HMAC_ALGORITHM = 'hmac_algo';
    public const CONFIG_HMAC_ALGORITHM_DEFAULT = 'sha512';
    /**
     * Key for Session key where Identity is stored in $config passed to constructor
     *
     * @var string
     */
    public const CONFIG_SESSION_KEY = 'sessionKey';
    /**
     * Default key for storing Identity within Session, should to equal `sessionKey` from
     * Authentication\Authenticator\SessionAuthenticator::$_defaultConfig
     *
     * @var string
     */
    public const CONFIG_SESSION_KEY_DEFAULT = 'Auth';

    /**
     * CsrfUserProtectionMiddleware constructor.
     *
     * Configures default values for HMAC algorithm and sessionKey, if not provided
     *
     * @param array $config Config options. See \Cake\Http\Middleware\CsrfProtectionMiddleware::$_config for valid keys.
     */
    public function __construct(array $config = [])
    {
        if (empty($config[self::CONFIG_HMAC_ALGORITHM])) {
            $config[self::CONFIG_HMAC_ALGORITHM] = self::CONFIG_HMAC_ALGORITHM_DEFAULT;
        }
        if (empty($config[self::CONFIG_SESSION_KEY])) {
            $config[self::CONFIG_SESSION_KEY] = self::CONFIG_SESSION_KEY_DEFAULT;
        }
        parent::__construct($config);
    }

    /**
     * @param ServerRequestInterface $request ServerRequest
     * @param RequestHandlerInterface $handler RequestHandler
     * @return ResponseInterface
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        // parse request data and prepopulate
        $this->identityIsInSession($request);
        // if user is logged in and fetching, not submitting data
        if ($this->identityFoundInSession && $request->getMethod() === 'GET') {
            $cookies = $request->getCookieParams();
            $cookieData = Hash::get($cookies, $this->_config['cookieName']);
            if (!empty($cookieData) && !$this->_verifyToken($cookieData)) {
                // if CSRF cookie contents are not bound to Identity, remove the cookie before passing to parent
                $cookies = Hash::remove($cookies, $this->_config['cookieName']);

                return parent::process($request->withCookieParams($cookies), $handler);
            }
        }

        return parent::process($request, $handler);
    }

    /**
     * Verifies that current request has session containing Identity within configured Session storage key
     *
     * @param ServerRequestInterface $request ServerRequest to be tested for Identity presence
     * @return void
     */
    public function identityIsInSession(ServerRequestInterface $request): void
    {
        if (!($request instanceof ServerRequest) || !$request->getSession()->started()) {
            return;
        }
        $userdata = $request->getSession()->read($this->_config[self::CONFIG_SESSION_KEY]);
        if ($userdata instanceof IdentityInterface) {
            $this->identifierFromFoundIdentity = strval($userdata->getIdentifier());
            $this->identityFoundInSession = true;

            if (empty($this->identifierFromFoundIdentity)) {
                triggerWarning('Session contained IdentityInterface returned empty Identifier, CSRF protection cannot be enhanced');
            }
        }
    }

    /**
     * Returns CSRF token, either static for un-authenticated requests, or bound to Identity Identifier if present
     * {@link identityIsInSession} must be called before this method
     *
     * @return string
     */
    public function createToken(): string
    {
        if ($this->identityFoundInSession) {
            $value = Security::randomString(static::TOKEN_VALUE_LENGTH);

            return $value . hash_hmac($this->_config[self::CONFIG_HMAC_ALGORITHM], sprintf("%s.%s", $value, $this->identifierFromFoundIdentity), Security::getSalt());
        }

        return parent::createToken();
    }

    /**
     * Verifies the CSRF token is bound ti Identity, if Identity is present in Request Session
     * {@link identityIsInSession} must be called before this method
     *
     * @param string $token token data found in request
     * @return bool
     */
    protected function _verifyToken(string $token): bool
    {
        if ($this->identityFoundInSession) {
            if (strlen($token) <= self::TOKEN_VALUE_LENGTH) {
                return false;
            }

            $key = substr($token, 0, static::TOKEN_VALUE_LENGTH);
            $hmac = substr($token, static::TOKEN_VALUE_LENGTH);

            $expectedHmac = hash_hmac($this->_config[self::CONFIG_HMAC_ALGORITHM], sprintf("%s.%s", $key, $this->identifierFromFoundIdentity), Security::getSalt());

            return hash_equals($hmac, $expectedHmac);
        }

        return parent::_verifyToken($token);
    }
}

```

**Comment by markstory** [comment]
Thank you for sharing your User based CSRF middleware.

I did some more thinking and I retract my earlier comments about being able to use the IP address to help pin the CSRF token. Doing so would cause users on mobile devices to hit CSRF errors as they moved between wifi networks and LTE data.

I'm now considering adding a separate session based CSRF token middleware implementation that stores the CSRF token in the session data directly and not using any additional cookies. This would follow the [synchronizer token pattern](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern). Having a separate middleware would allow people to swap out the current implementation for the session based one if their application used sessions. Using session based CSRF tokens would ensure they are coupled to the user and only last as long as a session does. It also removes the need for transmitting the cookie data (at the cost of opening the session on each request).

**Comment by smarek** [comment]
@markstory i think it's wonderful idea, and the more security-concerned of us, would really appreciate it

**Comment by saeideng** [comment]
related PR : https://github.com/cakephp/cakephp/pull/14825
cc : @smarek

**Comment by smarek** [comment]
Cool, closing this issue in favor of #14825
