### ISSUE TITLE
RFC to add additional MIME types (HAL and JSON-LD) to Cake\HTTP\Response MIME types

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#14796]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

Add HAL and JSON-LD mime types to [Response](https://github.com/cakephp/cakephp/blob/master/src/Http/Response.php).

Proposal:

```php
        'hal+json' => ['application/hal+json', 'application/vnd.hal+json'],
        'hal+xml' => ['application/hal+xml', 'application/vnd.hal+xml'],
        'ld+json' => 'application/ld+json',
```

I am not sure whether indexes for `hal+json` and `hal+xml` should instead by expressed as `vnd.hal+json` and `vnd.hal+xml`. There might be some debate there.

Not having these in necessitates some userland hacks to modify the Response at runtime such as including this code during the bootstrap phase of a plugin: https://gist.github.com/cnizzardini/1cf144d4d66b9f94f7d55b1c99d7ce62

Particularly, my use-case is building a HalJsonView and HalXmlView (and eventually a JsonLdView). It seems silly to have to add these MIME types in at runtime, though maybe there is a better way that I don't know about. Regardless, these are common enough message formats to be included IMO.

Reference:
- https://www.iana.org/assignments/media-types/media-types.xhtml
- http://stateless.co/hal_specification.html 
- https://json-ld.org/

**Comment by markstory** [comment]
Those sound like useful additions to me. As for the content types for hal. I would prefer to follow the hal specs.

**Comment by othercorey** [comment]
I looks like `application/hal+json` should always be the generic response for hal objects.

**Comment by cnizzardini** [comment]
I think this task also needs a modification to ServerRequest, example:

```php
ServerRequest::addDetector(
    'hal',
    [
        'accept' => ['application/hal+json'],
        'param' => '_ext',
        'value' => 'hal+json',
    ]
);
```

**Comment by cnizzardini** [comment]
Sidenote, Is there a reason that ServerRequest does not have a getDetector() and modifyDetector()? Would there be a danger in this functionality? If not, I may want to submit a PR for this functionality.

**Comment by dakota** [comment]
While we’re adding mime types, should probably also add JSON:API?

**Comment by ADmad** [comment]
> Would there be a danger in this functionality?

@cnizzardini That's the wrong question to ask when adding new methods :slightly_smiling_face:. The right question would be determine the use case for the new methods you propose and whether they would be required often enough.

**Comment by othercorey** [comment]
Btw, looking at the rest of the documentation, it seems like `application/vnd.hal+json` should be the official type although the original design document lists `application/hal+json`. I assume this was because the original design document was hoping for a consortium to adopt the type.

I don't know why the author didn't update the original design document to match the registered type though.

**Comment by cnizzardini** [comment]
Add both is my vote.

**Comment by othercorey** [comment]
Feel free to submit a PR.

**Comment by cnizzardini** [comment]
So the reason I decided to do an RFC was for the very issue you pointed out and I addressed in the initial post. The PR seemed easy, I wanted this question addressed more than the code.

**Comment by othercorey** [comment]
There isn’t much to discuss. Any problems can be fixed in the PR.

**Comment by othercorey** [comment]
@dakota Is this not json api?

> 'jsonapi' => 'application/vnd.api+json',
