### ISSUE TITLE
Query with ->matching() returns duplicate results, with seemingly no way to easily remove them

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#14791]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0-RC1
* Platform and Target: PHP 7.4, MySQL 5.7

### What you did
```
// Put something into a things table
INSERT INTO `things` (`id`, `title`)
VALUES
    (40, 'Test');

// Put stuff into a platforms table
INSERT INTO `platforms2` (`id`, `name_slug`)
VALUES
    (12, 'pc'),
    (13, 'mac');

// Add a link between the two
INSERT INTO `things_platforms2` (`game_id`, `platform_id`)
VALUES
(40, 12),
(40, 13);

// Try to match wherever a Thing is either pc or mac
ThingsTable
$query = $this->getTable('Things')
    ->find()
    ->matching(
        'Platforms2',
        fn($q) => $q->where([
            'Platforms2.name_slug IN' => ['pc', 'mac'],
        ])
    );
```

### What happened
This creates the sql (snipped db name) which, when run, returns the same record twice.
```
SELECT `Things`.`id` AS `Things__id`, `Things`.`title` AS `Things__title`, `ThingsPlatforms2`.`thing_id` AS `ThingsPlatforms2__thing_id`, `ThingsPlatforms2`.`platforms2_id` AS `ThingsPlatforms2__platforms2_id`, `Platforms2`.`id` AS `Platforms2__id`, `Platforms2`.`name_slug` AS `Platforms2__name_slug` FROM `things` `Things` INNER JOIN `things_platforms2` `ThingsPlatforms2` ON `Things`.`id` = (`ThingsPlatforms2`.`thing_id`) INNER JOIN `platforms2` `Platforms2` ON (`Platforms2`.`name_slug` in ('pc','mac') AND `Platforms2`.`id` = (`ThingsPlatforms2`.`platforms2_id`))
```

### What you expected to happen
I'd expect that adding the following, that a `DISTINCT` would be added to the select, but it adds a `GROUP BY`, which doesn't remove duplicates.
```
->distinct(['Things.id', 'ThingsPlatforms2.platforms2_id'])
```

The SQL that would remove duplicates would be 
```
SELECT DISTINCT Things.id, Things.* FROM `things` `Things` INNER JOIN `things_platforms2` `ThingsPlatforms2` ON `Things`.`id` = (`ThingsPlatforms2`.`thing_id`) INNER JOIN `platforms2` `Platforms2` ON (`Platforms2`.`name_slug` in ('pc','mac') AND `Platforms2`.`id` = (`ThingsPlatforms2`.`platforms2_id`))
```

Is there a reason `distinct()` adds a `GROUP BY` clause and not a `DISTINCT` clause as someone would expect? Even the doc in Query->distinct says:
```
 Adds a `DISTINCT` clause to the query to remove duplicates from the result set.
```

I've tried this, but it doesn't work, so right now I have no idea what to do. `enableAutoFields` also adds too many fields, so I have to remove that and manually add all the fields the query needs.
```
->enableAutoFields()
->select(['Things__id' => 'DISTINCT(Things.id)'])
```

**Comment by lorenzo** [comment]
Possible solution: use distinct() and pass a column that would make the records unique

**Comment by patrickconroy** [comment]
``->distinct(`Things.id`)`` errors out in MySQL 5.7, with this:
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column \u0027ThingsPlatforms2.platforms2_id\u0027 which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

So you have to make it ``->distinct(['Things.id', 'ThingsPlatforms2.platforms2_id'])`` which doesn't add a DISTINCT, and returns 2 results.

**Comment by lorenzo** [comment]
ah yes, in 5.7 you need to enable a compatibility flag, which I cannot remember the name.

**Comment by patrickconroy** [comment]
Yeah it's ```SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));``` .. but that seems a little weird to me. Is the core's recommendation to run that? Wouldn't it trip up new Cake users?

**Comment by othercorey** [comment]
MySQL doesn't support DISTINCT on specific columns. Cake generates the equivalent GROUP BY statement instead which can violate sql standard.

**Comment by patrickconroy** [comment]
If MySQL 5.7 needs that flag that's something I can make sure is run, then use the distinct on ID. Just confused if it's even possible to do it with 5.7 out of the box.

**Comment by othercorey** [comment]
This is the mysql doc on it - https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by patrickconroy** [comment]
Hm yeah I've read that and understand it, the thing is even when I add the nonagreggated fields to the `group`, out of the box with the defaults, you still get duplicates. You can solve it by mucking with the selected fields, but using the group would be cleaner to me. Right now someone download the core and using 5.7 would get duplicates unless they use the 5.6 way of grouping or 5.7 with the flag.
```
->group([
    'Things.id',
    'ThingsPlatforms2.platforms2_id',
]);
```

**Comment by ndm2** [comment]
Do you actually _need_ to use `matching()`, ie do you need to have the matching data in the results? If not, then you could simply use `innerJoinWith()` instead, which will not add any fields of the association to the `SELECT` list, grouping on the primary key should then work fine in strict mode.

**Comment by patrickconroy** [comment]
@ndm2 thank you, using `innerJoinWith` worked, and for this instance I don't need that in the `SELECT`.

**Comment by othercorey** [comment]
I wonder if we should deprecate automatically mapping distinct to group by and require users to explicitly set the group to avoid issues.
