### ISSUE TITLE
Csrf Token Missmatch on first form submission

### ISSUE THREAD

**Issue by julianpollmann** [cakephp/cakephp#14799]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.9
* Platform and Target: PHP 7.4, PHP Sessions, Authentication Plugin 2.3, CsrfMiddleware enabled

### What you did
I have a Login Form on the Frontpage of my App and a seperate Login Page.
The Login Form on the Frontpage is generated with FormHelper like this:

```
<?= $this->Form->create(null, ['id' => 'loginForm', 'url' => ['plugin' => 'Users', 'controller' => 'Users', 'action' => 'login']]) ?>
<?= $this->Form->email('email') ?>
<?= $this->Form->password('password') ?>
<?= $this->Form->submit('Login'); ?>
<?= $this->Form->end() ?>
```
On first login form this results in (Token Missmatch):
```
<form method="post" accept-charset="utf-8" id="loginForm" action="/anmelden">
    <div style="display:none;">
    <input type="hidden" name="_csrfToken" autocomplete="off" value="46ae8a9f33b8cd061c08586f800691cd7698bf555ddfdcf8442a25eb"></div>
    <input type="email" name="email">
    <input type="password" name="password">
    <div class="submit"><input type="submit" value="Login"></div>
</form>
```
The Csrf Cookie:
csrfToken:"**82eccb2883b3acf3a798a0f006bd22045de9d15614ac93b36fe48f5d**"

After Reloading the page the Token matches:
```
<form method="post" accept-charset="utf-8" id="loginForm" action="/anmelden">
    <div style="display:none;">
    <input type="hidden" name="_csrfToken" autocomplete="off" value="82eccb2883b3acf3a798a0f006bd22045de9d15614ac93b36fe48f5d"></div>
    <input type="email" name="email">
    <input type="password" name="password">
    <div class="submit"><input type="submit" value="Login"></div>
</form>
```
So to login it's necessary to reload the page.

### What happened
When the Cookie of the Site is cleared/expired there's a InvalidCsrfTokenException (Token Missmatch) on first login try. After reloading the Page the Csrf Token on the Form and the CsrfToken Cookie matches.

### What you expected to happen
Set the Csrf Token correctly to match the Cookie Token. Maybe the Form's Token needs to be set after the Cookie Token is set?

**Comment by markstory** [comment]
Do you have the CSRF middleware applied multiple times in your application?

**Comment by julianpollmann** [comment]
No, it's added once at Application's middleware():


```
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
    $middlewareQueue
        ->add(new ErrorHandlerMiddleware(Configure::read('Error')))

        ->add(new AssetMiddleware([
            'cacheTime' => Configure::read('Asset.cacheTime'),
        ]))

        ->add(new RoutingMiddleware($this, '_cake_routes_'))

        ->add(new AuthenticationMiddleware($this))
        ->add(new AuthorizationMiddleware($this, [
            'identityDecorator' => function (AuthorizationServiceInterface $auth, User $user) {
                return $user->setAuthorization($auth);
            },
        ]))

        ->add(new LocaleSelectorMiddleware(['de_DE', 'en_GB', 'en_US']))
        ->add(new CsrfProtectionMiddleware());

    if (Configure::read('debug')) {
        // Disable Auth for DebugKit
        $middlewareQueue->add(function (ServerRequest $req, Response $res, $next) {
            if ($req->getParam('plugin') === 'DebugKit') {
                $req->getAttribute('authorization')->skipAuthorization();
            }

            return $next($req, $res);
        });
    }

    return $middlewareQueue;
}
```

**Comment by ADmad** [comment]
@julianpollmann Check your `routes.php` and make sure the middleware is not added to a scoped route too.

**Comment by julianpollmann** [comment]
@ADmad Right, there was a CsrfMiddleware added in the Routes like here: https://github.com/cakephp/app/blob/3.x/config/routes.php#L50-L58
I removed this and it's working.

**Comment by othercorey** [comment]
I wonder if we can throw an exception on this in debug.

**Comment by markstory** [comment]
@othercorey I can look into that.
