### ISSUE TITLE
LazyEagerLoader::loadInto (_getQuery) retrieves both sides of the association

### ISSUE THREAD

**Issue by notpron** [cakephp/cakephp#14807]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.0

### What you did
```
Game:
   int $id
   int $domain_id
   ... more fields

Domain:
   int $id
   ... more fields
```
```
        $game = $this->Games->get(1);
        $game = $this->Games->loadInto($game, ['Domains']);
```

### What happened
Query log shows 2 queries: one for the `get(1)`, one for the `loadInto()`:
```
(int) 4 => object(Cake\Database\Log\LoggedQuery) {
    query => 'SELECT `Games`.`id` AS `Games__id`, `Games`.`domain_id` AS `Games__domain_id`, `Games`.`foo` AS `Games__foo`, ....snip..., `Games`.`bar` FROM `games` `Games` WHERE `Games`.`id` = :c0 LIMIT 1'
    took => (int) 0
    params => [
        'c0' => (int) 1
    ]
    numRows => (int) 1
    error => null
},
...
(int) 9 => object(Cake\Database\Log\LoggedQuery) {
    query => 'SELECT `Games`.`id` AS `Games__id`, `Games`.`domain_id` AS `Games__domain_id`, `Games`.`foo` AS `Games__foo`, ....snip..., `Games`.`bar` AS `Games__bar`, `Domains`.`id` AS `Domains__id`, `Domains`.`foo` AS `Domains__foo`, ...snip..., `Domains`.`bar` AS `Domains__bar` FROM `games` `Games` INNER JOIN `domains` `Domains` ON `Domains`.`id` = (`Games`.`domain_id`) WHERE `Games`.`id` IN (:c0)'
    took => (int) 0
    params => [
        'c0' => (int) 1
    ]
    numRows => (int) 1
    error => null
}
```

### What you expected to happen
I expected `loadInto` to be retrieving only the Domain, not also the Game, since the provided $game already contains the required domain_id for this association.

**Comment by markstory** [comment]
The join allows loadInto() to work with partial entities and leverage the association conditions and finder method via contain(). Removing the join is potentially possible but may incur more code complexity. I'd you're up for trying to improve this I can help with tests and reviews.

**Comment by othercorey** [comment]
I think requiring the foreign key in the entity is reasonable. I assume the partial entity support is simply to load foreign keys from the primary key.

I haven't looked into it closer myself.

**Comment by markstory** [comment]
Related to #14224
