### ISSUE TITLE
Cakephp 4 Form Helper: Create Individual dropdown for day, month and year

### ISSUE THREAD

**Issue by degee147** [cakephp/cakephp#14803]
* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.8.
* Platform and Target: Apache MySQL, PHP server on wamp and online

Maybe I'm not supposed to ask this here, but I've posted a question on stackoverflow for a while now and no response yet. I'm not sure if this is a bug or an enhancement or a deliberate left-out feature

Kindly see the post: https://stackoverflow.com/questions/62711251/cakephp-4-form-helper-create-individual-dropdown-for-day-month-and-year

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by ADmad** [comment]
Multiple selects for dates were deliberately removed in 4.x in favour of HTML5's date inputs.
