### ISSUE TITLE
Cake\Utility\Inflector::variable does not remove slashes

### ISSUE THREAD

**Issue by PaulHendriks** [cakephp/cakephp#14802]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* Platform and Target: Windows 10, Apache,  PHP7.4.6

### What you did
I am writing a command to migrate all loaded plugins.
To determine if there's a phinxlog table, i want to use the Inflector class to modify the plugin name to a corresponding _phinxlog table name.
```$io->out(Inflector::underscore('Cake/TwigView'));```

### What happened
The output:

```cake/twig_view```

### What you expected to happen
I expected the slash to be stripped, like ```cake_twig_view```

Or ```$io->out(Inflector::variable('Cake/TwigView'));``` to be a valid variable.
Instead that results in ```cake/twigView```, which isn't a valid variable name.

Neither slashes are stripped; forward nor back slashes.

Workaround: manually strip the slashes from the string. This is a very minor issue.

**Comment by dereuromark** [comment]
The current workaround is acceptable here. That method is not a silver bullet and can not know about all possible "issues" around inflection side effects.
It does its job as documented, but nothing more.

You could create your own wrapper on top that provides smarter inflection for example:
CustomInflector::underscoreNamespaced() or alike
But this is probably out of scope for core classes where namespaces are not an issue, or are handled separately from the actual inflection already.

**Comment by PaulHendriks** [comment]
Thank you for the quick reply.
I can live with the workaround, i'll close this issue.
