### ISSUE TITLE
Validation cannot validate invalid datetime

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14800]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: Windows, NGINX, PHP 7.3, SQL Server

### What you did
Define validation method in table class:
```php
public function validationDefault(Validator $validator): Validator
{
    // ...
    $validator->notEmptyDateTime('field');
    // ...
    return $validator;
}
```

Patch entity in controller:
```
$entity = $table->patchEntity($entity, $requestData);
$table->save($entity);
```

Request data:
```
field=test
```

### What happened
SQL error occurred: Column 'field' cannot be null

Local time format (`H:i, Y/m/d` in `vi_VN` locale) cannot be validated if I add below code to validator
```
$validator->dateTime('field', ['ymd', 'dmy']);
```

And if I don't use `H:i, Y/m/d` format, time string cannot be parsed by local parser. See #14071 

### What you expected to happen
Error on `field` of entity

**Comment by markstory** [comment]
> Local time format (H:i, Y/m/d in vi_VN locale) cannot be validated if I add below code to validator

To me this is expected behavior as your datetime string doesn't match the format you defined so it isn't valid based on how the rule is defined.

Do you have the same problem if you are not using locale based datetime parsing?

**Comment by mcsknp** [comment]
I found method `$validator->localizedTime(...)` but there is an problem with below code
https://github.com/cakephp/cakephp/blob/4f635e709ad0a9610a0ca4a1e2b6129c08ec6cd0/src/Validation/Validation.php#L661
It must be `is_string` or `is_scalar` with cast to string because first argument of `Time::parse...` is `string`
