### ISSUE TITLE
SQL Stored Procedure running through sp_cursorprepexec 

### ISSUE THREAD

**Issue by iomariani** [cakephp/cakephp#14806]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* PHP Version: 7.4.5
* Platform and Target: Azure WebApp Microsoft Windows NT 10.0.14393.0, Microsoft SQL Azure (RTM) - 12.0.2000.8
* SQLSRV Version: 5.7.1

### What you did
Execute an stored procedure using CakePHP:
```php
$this->connection = ConnectionManager::get('default');
$query = 'EXEC PROCEDURE_NAME PARAM';
$stmt = $this->connection->execute($query);
$result = $stmt->fetchAll('assoc');
$stmt->closeCursor();
```

### What happened
The database server receives the query, but is executed as a cursor such as:
```sql
declare @p1 int
set @pq=1
declare @p2 int
set @p2=0
declare @p5 int
set @p5=8
declare @p6 int
set @p6=8193
declare @p7 int
set @p7=0
exec sp_cursorprepexec @p1 output, @p2 output,NULL,N'EXEC PROCEDURE_NAME PARAMS',@p5 output,@p6 output,@p7 output
select @p1,@p2,@p5,@p6,@p7
```

### What you expected to happen
The DB receives the query as sent
```sql
EXEC PROCEDURE_NAME PARAMS
```

This was reported to me from the DBA which said this is affecting the database performance.
Since we use stored procedures to process large data and retrieve summarized output to present it into dashboards/reports.
And this execution is in loop like every 3-5 seconds.

I noticed that at **src/Database/Driver/Sqlserver.php#195**
https://github.com/cakephp/cakephp/blob/74b320a4fca22280ff311dac57b611fa0a0affd6/src/Database/Driver/Sqlserver.php#L195
Is enforcing this PDO::ATTR_CURSOR attribute as PDO::CURSOR_SCROLL.

To be honest I have no idea if this is what is causing this...
Or if this is an expected behaviour using Microsoft's SQLSRV Driver.
Hopefully there's some way to circumvent it that I missed out and you guys are better suitable to enlighten me.

**Comment by rchavik** [comment]
I also have performance issue with sqlserver normal queries (not sp calls). I had to patch that line as described here: https://github.com/cakephp/cakephp/issues/8579 to get bearable performance.

**Comment by markstory** [comment]
The solution in #8579 was to update the sqlserver driver. Does that not help with this problem?

**Comment by iomariani** [comment]
> I also have performance issue with sqlserver normal queries (not sp calls). I had to patch that line as described here: #8579 to get bearable performance.

That "workaround" was exactly the way I solved the problem, there was a significant performance boost on the queries as well as the server.
What I did was overriding the method "prepare" from Cake's `Database/Driver/Sqlserver` and using its class instead on my `config/app.php`:

```php
<?php

namespace App\Database\Driver;

use Cake\Database\Query;
use Cake\Database\Statement\SqlserverStatement;
use Cake\Database\StatementInterface;
use Cake\Database\Driver\Sqlserver as Driver;

class Sqlserver extends Driver
{
	public function prepare($query, array $options = []): StatementInterface
	{
		$this->connect();
		$options += [\PDO::ATTR_CURSOR => \PDO::CURSOR_SCROLL, \PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => \PDO::SQLSRV_CURSOR_BUFFERED];
		$isObject = $query instanceof Query;
		/** @psalm-suppress PossiblyInvalidMethodCall */
		if ($isObject && $query->isBufferedResultsEnabled() === false) {
			$options = [];
		}
		/**
		 * @psalm-suppress PossiblyInvalidMethodCall
		 * @psalm-suppress PossiblyInvalidArgument
		 */
		$statement = $this->_connection->prepare($isObject ? $query->sql() : $query, $options);

		return new SqlserverStatement($statement, $this);
	}
}
```

However, I think maybe a cleaner solution would be to implement the `PDOStatement::setAttribute` method (https://www.php.net/manual/en_US/pdostatement.setattribute.php) over at **Cake\Database\Statement\Sqlserverstatement.php** as well.

**Comment by iomariani** [comment]
Okay so, apparently PDO's `ATTR_CURSOR` and `SQLSRV_ATTR_CURSOR_SCROLL_TYPE` cannot be set through [`PDOStatement::setAttribute`](https://www.php.net/manual/en/pdostatement.setattribute.php), as I got the following error trying to do so :

`SQLSTATE[IMSSP]: The PDO::ATTR_CURSOR and PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE attributes may only be set in the $driver_options array of PDO::prepare.`

So I propose a PR for the changes I implemented above and simply add the $options array as a parameter to the Driver's prepare function.

**Comment by othercorey** [comment]
@iomariani Let me know if this affects your queries - https://github.com/cakephp/cakephp/pull/14842

**Comment by iomariani** [comment]
> @iomariani Let me know if this affects your queries - #14842

Not at all, in fact, it's what I set as default on our system back-end by overriding the core.
Like I mentioned earlier, any chance we can to customize it, either by a config option or by a function argument would be welcome as well.

But this for me would be a default for basically all my PDO requests through SQL Server.

**Comment by othercorey** [comment]
This should be fixed by https://github.com/cakephp/cakephp/pull/14842. Users who don't use buffered queries will still have a server-side cursor.
