### ISSUE TITLE
Error when create/patch entity with array data has numeric key

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14810]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: Windows, NGINX, PHP7.3, SQL server

### What you did
Patch entity with below request data
```
0=sample&1=value&....
```

### What happened
Below error occurred
```
Argument 1 passed to Cake\Database\Schema\TableSchema::getColumnType() must be of the type string, int given
```
at
https://github.com/cakephp/cakephp/blob/4f635e709ad0a9610a0ca4a1e2b6129c08ec6cd0/src/ORM/Marshaller.php#L75

### What you expected to happen
`$prop` must be a scalar and cast to string before pass to `TableSchema::getColumnType()`

**Comment by othercorey** [comment]
Are you looking to use column names that are numeric strings or are you expecting a column number mapping to happen?

**Comment by mcsknp** [comment]
No, I'm testing my code with invalid request data.
