### ISSUE TITLE
Skip next validation rule if data is not valid

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14815]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: Windows, NGINX, PHP 7.3, SQL server

### What you did
Validate invalid request data.

### What happened
Some validation method is written with type for arguments or using function that defined with datatype for arguments but request data can be an array or string, so system error will be occurred with invalid request data.

### What you expected to happen
An option to skip next validation rule if data is invalid.

**Comment by markstory** [comment]
What would the interface you'd like to use to do this look like?

**Comment by mcsknp** [comment]
Add `$skipOnError` property to `ValidationRule`.
Add `$sequence` property to `Validator`.

```php
$validator->beginSequence();
// use $validator->...() to add any rule for field
$validator->endSequence();
```

When `$sequence` is on rule will be added to `ValidationSet` with `$skipOnError` flag.
And in `Validator::_processRules()`, if an error found, break `for` if `$skipOnError` flag is on.

**Comment by dereuromark** [comment]
We should close this in favor of https://github.com/cakephp/cakephp/issues/14816 and the linked PR there.

**Comment by markstory** [comment]
I don't fully understand what a 'sequence' is and have a few questions:

* Would a 'sequence' be a chain of validation methods that stop when the first rule fails? 
* Would you be able to define sequences within other sequences?
* What happens to sequences that are started but not ended?
* What happens with empty sequences?

**Comment by mcsknp** [comment]
Sorry for bad explanation.
It isn't sequence, it's a property of validation rule.
And the `sequence` I wrote is a property to enable `skipOnError` flag of validation rule when add a rule to set.
I think adding a property to `Validator` class and use its when add a validation rule is better than add an argument to all method of it.

**Comment by dereuromark** [comment]
Isnt this somewhat what last=> true does?

**Comment by mcsknp** [comment]
How to set `last` to true?

**Comment by dereuromark** [comment]
The old way: https://github.com/dereuromark/cakephp-sandbox/blob/master/src/Model/Table/UsersTable.php#L41
The new way is a method on it afaik.
EIther way: The default should here be true (as I think was once discussed years ago), as the next rule only makes sense usually if that one worked.
Email is a classic example: First check if min length, then regexp pattern, then domain existence (API) check and alike.
Most rules are usually always in such a chain - and thus last should be considered true here always as default case.

**Comment by mcsknp** [comment]
The default is `false`.
https://github.com/cakephp/cakephp/blob/94ab7ac1b1e82a48bfec6c01b8ce603b01cb76a0/src/Validation/ValidationRule.php#L45-L50

> EDIT: https://book.cakephp.org/4/en/core-libraries/validation.html#marking-rules-as-the-last-to-run still a key.

Will adding rule by array be deprecated?

By the way, I think it's name shouldn't be `last`.

**Comment by dereuromark** [comment]
I dont think so, as long as there is no full fluid interface yet.

What would be a better name?

Either way, not much we can do here during 4.x - and given the docs I linked we can probably close this then as it should work this way already if configured accordingly.

**Comment by mcsknp** [comment]
> What would be a better name?

I think it's should be `skipNextRuleOnError`

`last` in `ValidationRule` only skip next rule of same field, other field validation isn't stopped.

**Comment by dereuromark** [comment]
The validation is per field. I dont think what you suggest is in scope of current core. Or would be useful for enough people that it warrants such an addition. This is really not a case I have ever seen needed in 13+ years with Cake apps.

**Comment by dereuromark** [comment]
@mcsknp Can you check if https://github.com/cakephp/cakephp/pull/14943 is also somewhat in line what you need?

**Comment by mcsknp** [comment]
@dereuromark Yes. I think my request will be resolved. Thanks!

**Comment by othercorey** [comment]
Is this fixed?
