### ISSUE TITLE
Debug of ResultSet with associated data fails

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#14839]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1
* Platform and Target: Apache, MySQL

### What you did
I called debug() on result of DB query (Cake\ORM\ResultSet) with associated data (belongsToMany).

### What happened
Argument 1 passed to Cake\Error\Debug\PropertyNode::__construct() must be of the type string, int given, called in .../vendor/cakephp/cakephp/src/Error/Debugger.php on line 745

I checked what specific data caused it and it's the array with associated data, which is an array and keys are numeric.

Debugger.php starting at line 740:
```
foreach ($objectVars as $key => $value) {
                if (array_key_exists($key, $outputMask)) {
                    $value = $outputMask[$key];
                }
                $node->addProperty(
                    new PropertyNode($key, 'public', static::export($value, $context->withAddedDepth()))
                );
```

PropertyNode constructor requires key to be string:
```
    public function __construct(string $name, ?string $visibility, NodeInterface $value)
```

beginning of var_dump() of what is $objectVars at the moment of crash
```
array(2) {
  [0]=>
  object(Cake\ORM\Entity)#344 (14) {
    ["id"]=>
    int(1)
    ["organisation_id"]=>
    int(9)
    ... etc.
```

### What you expected to happen
I expected printed data :-)

**Comment by garas** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/14774.

Upgrade to CakePHP 4.1.1.
