### ISSUE TITLE
hidden boolean field does not vaidate

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#14833]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.1
* Platform and Target: Debian Buster and others

### What you did
I have a form in with a hidden boolean field which value is false.
With #14548 a value of false is stored (correctly) as '0', but for the SecurityComponent FormHelper#hidden returns the value as
  (string)$option['val']
see FormHelper line 1635
So the SsecurityComponent expects the value to be an empty string "", but in POST it is "0", which causes validatePost to fail

### What happened
See above, POST data fails to validate

### What you expected to happen
POST validates, of course :)
My guess is that the security is called before BasicWidget had a change to change $option

**Comment by dereuromark** [comment]
Closing dup in favor of https://github.com/cakephp/cakephp/issues/14834
