### ISSUE TITLE
Asserting email subject in EmailTrait

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#14845]
* [x] enhancement
* CakePHP Version: 4.1.1

Hello,
I'm looking for the possibility of asserting the email **subject** in EmailTrait.

In the docs https://book.cakephp.org/4/en/core-libraries/email.html#email-testing, there is stated: "We want to check that the **subject** and body contain the user’s name:" - but the example does not assert the subject, it only uses "assertMailContainsText".

I digged deeper and found another misleading line of code:
https://github.com/cakephp/cakephp/blob/ffa1fa5715e3569d30a4e07d0ff8e6c035ef3781/src/TestSuite/EmailTrait.php#L153

It assumes, that "subject" can be asserted with the "$parameter" argument - but as the assertMethod uses "MailSentWith" it cannot work.

So my question is:
Is there any way to assert the subject of an email? And if not, is such a feature planned? I would suggest a new class "MailSubject", extending "MailConstraintBase".

I could make a PR if you want.

**Comment by markstory** [comment]
Seems like we're missing subject in this list https://github.com/cakephp/cakephp/blob/ffa1fa5715e3569d30a4e07d0ff8e6c035ef3781/src/TestSuite/Constraint/Email/MailSentWith.php#L59 Would you be able to make a pull request to add that?

**Comment by mrothauer** [comment]
Yes, I can make a PR for that but I'm afraid it's not that easy.
MailSentWith is not the appropriate class to use for an assertion of the email subject - of course it would work but "subject" has nothing to do with "SentWith".
I would suggest creating a new method `assertMailSubject` and new class `MailSubject` which handle the new feature - and don't add "subject" to the quoted array.

**Comment by markstory** [comment]
@mrothauer Ok, a new constraint class works too.
