### ISSUE TITLE
RFC: Better OR support for the query builder

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#14849]
So right now you have to do this - **totally** counter intutive syntax - to get a list of chained ORs for the same field.

```php
foreach ($tagStrings as $tag) {
	$tags[] = ['Tags.name LIKE' => '%' . trim($tag) . '%'];
}
$query->where(['OR' => ['OR' => $tags]]);
```

To get this:

```sql
    (
      `Tags`.`name` like '%tag1%' 
      OR `Tags`.`name` like '%tag2%'
    ) 
```

I would like to propose a query builder method for that, to make it more clear:

```php
$query->chainedOr('Tags.name LIKE', ['tag1, 'tag2']));
```

Maybe someone else has a better method name.

**Comment by othercorey** [comment]
I think this could be improved, but don't you only need this:
```
$query->where(['OR' => $tags]);
```
