### ISSUE TITLE
RFC for Cake5: Refactor the helper API

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#14859]
## Suggested changes:

* Change HtmlHelper to be a collection of factories that will return element objects
  * The HtmlHelper itself should be construced via DI config that controls also the available elements in the collection. If you need custom elements hook them up there
* Remove the array options of helpers and make them methods of the objects

For example HtmlHelper::link() will return an object that implements `HelperInterface` and `LinkHelperInterface`. One of both interfaces (probably HelperInterface) will require __toString() which is used to turn the object into a string when echo is called.

While the actual amount of typing becomes just a little less (if you're not using an IDE that discovers the methods) the benefit is that we can get rid off the anoying arrays that are prone to mistakes like typos and that you'll have to look rarely used option keys up in the docs while methods allow IDEs to support you by showing the methods.

Benefits are better readability, less errors through typos, faster code writing (with an IDE), easy adding and replacing elements via DI config.

### Proposed:

```php
echo $this->Html->link('Test', ':namedRoute')
	->attr('id', 'test'), // Setter to allow any custom attribute
	->id('test'),
	->data('name', 'value')
	->classes(['button', 'btn-sm']); // Takes now an array to turn it into a string, easy to merge with defaults
```` 

This could be even further reduced if we provide namespaced (Cake\View) helper functions:

```php
echo link('Test', ':namedRoute')
	->attr('id', 'test'),
	->id('test'),
	->data('name', 'value')
	->classes(['button', 'btn-sm']));
```

### Existing:

```php
echo $this->Html->link('Test', ':namedRoute', [
	'attribute' => 'test',
	'id' => 'test',
	'data-name' => 'value',
	'class' => 'button btn-sm'
]);
```

### Passing URLs

Either make *all* methods that take URLs taking an URL object, that could provide static factory methods like `Url::fromName()`, `Url::fromArray()` or keep it mixed and check, if a string was provided. If it is prefixed with : and then internally (not prefered because it couples the router to the helper) check if there is a named route with that name and use it. We could of course use another prefix as well if there is a problem with the colon. Instead of the static methods we could use here namespaced functions like linkFromArray() and linkFromName() as well.

**Comment by inoas** [comment]
Now that PHP8 is there, what about named parameters?
