### ISSUE TITLE
Fix HTTP Client Curl adapter with HEAD requests with non-zero content-length in response

### ISSUE THREAD

**Issue by nickygerritsen** [cakephp/cakephp#14851]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.1 (but is also broken in older and newer versions)
* Platform and Target: PHP 7.4.3, Ubuntu 20.04, libcurl 7.68.0

### What you did
Do a `HEAD` request to a webservice that returns a `Content-Length > 0` but no body, in accordance with the [HTTP spec](https://tools.ietf.org/html/rfc2616#section-9.4).
For example Elasticsearch, see https://github.com/elastic/elasticsearch/pull/21123 .

### What happened
I get an error `cURL Error (18) transfer closed with 431 bytes remaining to read`.

### What you expected to happen
The HTTP request succeeds

### What is the fix?
Add a case [here](https://github.com/cakephp/cakephp/blob/master/src/Http/Client/Adapter/Curl.php#L105):

```php
            case Request::METHOD_HEAD:
                $out[CURLOPT_NOBODY] = true;
                break;
```

If you have a webserver which sends a non-zero content length for HEAD requests, you can reproduce it using the curl CLI:

```bash
curl -H 'Connection: close' -X HEAD [url here]
```

Note that using `-I` instead of `X HEAD` does work, since that will set `CURLOPT_NOBODY` correctly.

**Comment by ADmad** [comment]
Would you like to submit a pull request which the suggested fix?

**Comment by nickygerritsen** [comment]
I can definitely try, not sure if there are tests that handle this? If so I will need to investigate how to add one.
