### ISSUE TITLE
FormProtectionComponent throws BadRequestException on valid hidden input array

### ISSUE THREAD

**Issue by PaulHendriks** [cakephp/cakephp#14854]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* Platform and Target: Windows Xampp

### What you did
```
<?php echo $this->Form->create($model, ['url' => ['controller' => 'Controller', 'action' => 'add']]); ?>
<?php echo $this->Form->hidden('test[' . $model->id . ']', ['value' => $model->name]); ?>
<?= $this->Form->end() ?>
```
### What happened
I am trying to submit a hidden field; an HTML array.
FormProtectionComponent throws BadRequestException, suspecting that de form was tampered with.
The exact message: ```Tampered field test in POST data (expected value name but found ``)```

### What you expected to happen
I expected the request to be processed by the controller. 

When i change the type from hidden to text, the form get's submitted without a BadRequestException:

```
<?php echo $this->Form->create($model, ['url' => ['controller' => 'Controller', 'action' => 'add']]); ?>
<?php echo $this->Form->text('test[' . $model->id . ']', ['value' => $model->name ] ); ?>
<?= $this->Form->end() ?>
```

**Comment by ADmad** [comment]
Instead of `<?php echo $this->Form->text('test[' . $model->id . ']', ['value' => $model->name ] ); ?>` use `<?php echo $this->Form->text('test.' . $model->id, ['value' => $model->name ] ); ?>`.

**Comment by othercorey** [comment]
@PaulHendriks Does this work for you?

**Comment by PaulHendriks** [comment]
Sorry for the late reply.

Yes, @ADmad that works :-)

This also works:

```<?php echo $this->Form->hidden('test.' . $model->id, ['value' => $model->name ] ); ?>```


Thank you for the feedback
