### ISSUE TITLE
RFC: PHP 8 Attributes (annotations) as alternative for Event System (and beyond)

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#14861]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 5 ?
* Platform and Target: Any

As you might know, PHP 8 introduces native annotations using the @@ syntax. This new feature has a huge potential for reduce drastically the needs of methods calls. IMHO one of the first possible use of this could be a new and short way to set "listeners".

Example:

```php
use Cake\Event\EventListenerInterface;
use Cake\Attributes\ListensTo;

class UserStatistic
{
    @@ListenTo(OrdersTable::class, 'afterPlace')
    public function updateBuyStatistic($event)
    {
        // Code to update statistics
    }
} 
```
**and beyond that:**

```php
use App\Model\Entity\PO;

@@EntityClass(PO::class)
@@PrimaryKey('my_id')
class PurchaseOrdersTable extends Table {
}
```

**Comment by othercorey** [comment]
I'm not sure that annotations for tables is saving anything. It's the same work to set the attribute and make the same call in the header. It also requires duplicate implementation for anyone creating tables dynamically.

**Comment by markstory** [comment]
I think annotations can fit well for listeners. One challenge I see is ensuring that all classes with listeners are loaded in each request. With current autoloading systems, listeners defined in files that don't get loaded will never be triggered.

**Comment by celsowm** [comment]
and routes too, would be very useful (something similar to springboot):

```php
class RecipesController extends AppController
{

    @@PutMapping("/recipes/{id}")
    public function update(int $id)
    {
    }

    @@Post("/recipes")
    public function insert()
    {
    }
{
```

**Comment by othercorey** [comment]
> I think annotations can fit well for listeners. One challenge I see is ensuring that all classes with listeners are loaded in each request. With current autoloading systems, listeners defined in files that don't get loaded will never be triggered.

There would have to be some sort of preload list. I don't think naming conventions will help since they could be implemented anywhere.

**Comment by markstory** [comment]
@celsowm Routes are another potential good fit for attributes, but like event listeners are another scenario that would likely need to be pre-compiled into code. Loading every controller on each request and using reflection to build the route list/event listeners could be expensive. We would need to do some testing on the overhead of attributes for listeners or routes before committing to using them.

**Comment by ADmad** [comment]
> ..would likely need to be pre-compiled into code.

Yup pre-compiling (and caching) will be required for most places where we decide to use annotations.

**Comment by celsowm** [comment]
> 
> 
> > ..would likely need to be pre-compiled into code.
> 
> Yup pre-compiling (and caching) will be required for most places where we decide to use annotations.

I am very curious to see how others php libs and frameworks will handle this

**Comment by dereuromark** [comment]
I think this is 6-12 months too early to discuss in this context 
People can Explore this on app or plugin level.

**Comment by othercorey** [comment]
Closing this in favor of more specific discussions.
