### ISSUE TITLE
Add more paths to i18n extract

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#14869]
I use `i18n extact` command to regenerate .pot files for translations and I have translated routing stored in /config/routes.php.

Whether it is possible to config paths to extract per project? When I using command above, I always must write path to /config directory by hand.

**Comment by garas** [comment]
Paths can be only specified with command line arguments. There is no config settings.

**Comment by mcsknp** [comment]
You can use composer script.
Add below script to `scripts` section of `composer.json`
```javascript
{
    // ...
    "scripts": {
        // ...
        "i18n": "@php bin/cake.php i18n extract --paths src,templates,config/routes.php --output resources/locales"
        // ...
    }
    // ...
}
```
and call it by
```
composer i18n
```

**Comment by kicaj** [comment]
@mcsknp Interesting!
