### ISSUE TITLE
RFC - Adding a DI container

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#14865]
CakePHP has long been without a dependency injection container, as we haven't needed one in CakePHP core. Instead of using a DI container we rely on service locators for the ORM, global configuration and constructor/method parameters instead. While CakePHP hasn't needed a dependency injection container directly it would be useful for application developers.

## Problems a Container Solves 

As applications increase in complexity they need ways to centralize object creation, reduce coupling to dependencies, and have a central place to build reusable objects and the relationships between them.

A container solves these problems by acting as a configurable factory for a variety of objects. By  fetching objects from the container, the container can resolve dependency trees based on the configured state. Having a central factory makes swapping implementations for testing or refactoring simpler as all the creation logic is located in one place.

## Proposed Implementation

This proposal does not include the creation of a container implementation. Instead, we should re-use an existing container based on PSR-11. Using a PSR-11 container and coupling to those interfaces allow us to change container libraries more easily in the future if necessary.

### High Level Goals

A dependency injection container in CakePHP should enable applications and plugins to define services and then have those services injected into controllers and commands as requested. Views, Helpers, Tables, Mailers and Behaviors will not have container services injected into them. These objects are generally created far away from the `Application` and thus hard to inject into. Furthermore, none of these class types are 'entrypoints' into an application and could have services passed into their methods as parameters by the top level 'entrypoint' classes (controllers and commands).

The container would be initialized during `Application` construction. Services could be registered during the new `register()` hook which would be called *after* `bootstrap()`. Calling `register()` after `bootstrap()` lets us ensure that the application and all plugins have initialized their configuration and constants before any services are defined.

### Registering Services

Services would be registered during the `register()` hook method implemented on both the
`BaseApplication` and `BasePlugin` classes. Application classes would implement a new interface,
(`ContainerApplicationInterface`). This interface would define the following methods:

- `register(ContainerInterface $container): ContainerInterface` - Implemented by applications to register their services.
- `getContainer(): ContainerInterface` - Creates the new container if one has not been created, registers all application and plugin services. Once the container is prepared references to the container will be returned.

Having a new interface ensures that container features are opt-in for standalone HTTP and console applications.

#### Plugin Services

Plugins would be able to register services in an application's container. Plugins would have a `register` hook method called *after* the application services are registered.

```
register(ContainerInterface $container): ContainerInterface
```

Would be the signature of `BasePlugin::register()`. The `register()` method would be implemented on `BasePlugin` and added to the `PluginInterface` via a `@method` annotation because of backwards compatibility. Adding another interface is an alternative approach but I'd prefer to avoid it as it adds complexity and most plugins inherit from `BasePlugin` anyways.

The `PluginInterface::VALID_HOOKS` constant would be updated to include the `register` value. This is required to enable `with('register')` to work.

### Tagged and Deferred Services

Most of the container options listed below offer the creation of deferred and tagged services, which enables applications with many services to improve performance and customization. 

### Configuration Service

If possible, CakePHP would register the state of `Configure` as a 'service'. Doing so allows services to access configuration information without having to refer to `Configure`. Because DI containers are class/interface based, configuration data would be wrapped in a wrapper class (`Config`, `ConfigData` or `Configuration`) that includes the following methods:

- `has(string $key): bool` Test for a value.
- `get(string $key, $default = null): mixed` Read a value.

Both of these methods would support the simple `.` based traversal that `Configure::read()` does.

### Getting Services

Controllers and Commands would receive registered services as constructor arguments. Controllers would also have services injected as parameters to action methods. The construction of controllers and commands is contained within factory classes which can both easily be passed `Application` references. The same is true of command execution and controller action invocation.

An example controller action using injection would be:

```php
function index(RepositoryService $repos)
{
  // RepositoryService would be injected from the container.
  $records = $repos->findAll($user);
}
```

If a controller action accepts passed parameters, services would be appended to the *end* of the argument list:

```php
function edit(int $pullRequestId, int $commentId, RepositoryService $repos)
{
  // method body.
}
```

### Container Library Options

A short list of options is:

* https://container.thephpleague.com/3.x/
* http://php-di.org

### Feedback requested

- Is this the kind of DI container integration that will help you build your applications?
- What kind of testing helpers would you expect to see, or want to use?
- Are there container libraries we should be considering?

## Changes

- Remove command and shell methods from the places the container will inject services. Getting the container into Shell and Command is complicated and commands should be focused on a single task so constructor arguments should suffice.

**Comment by cnizzardini** [comment]
How is the service "mapped" to a controller action?

**Comment by burzum** [comment]
league/container, php-di is a monster of a library. I prefer small code, less complexity, less possible points of failure until the complexity is *really* needed. If you go for PSR compatibility it should be easy to switch to php-di when really needed.

**Comment by markstory** [comment]
> How is the service "mapped" to a controller action?

I don't understand this question entirely. Are you asking about how services injected into actions? The controller factory would have access to the container and use reflection to get parameter types and the resolve those types into objects with the container. If an object cannot be resolved and there is a non-primitive type used an error would be raised.

> league/container, php-di is a monster of a library. I prefer small code, less complexity, less possible points of failure until the complexity is really needed. If you go for PSR compatibility it should be easy to switch to php-di when really needed.

Good to know. I'm tempted to have the framework require the PSR interfaces and then have the application require a specific container implementation. This could make plugins a mess to work with though, as they don't have a stable set of interfaces beyond the PSR interfaces that they can use.

**Comment by othercorey** [comment]
> I'm tempted to have the framework require the PSR interfaces and then have the application require a specific container implementation. This could make plugins a mess to work with though, as they don't have a stable set of interfaces beyond the PSR interfaces that they can use.

I would prefer this approach as well. Can we identify which interfaces would make plugins a mess?

**Comment by othercorey** [comment]
The idea of DI as a language-level feature was proposed and rejected with this comment about the design of injection in 8+ with attributes. Something I hope we can adapt to with what we choose.

https://externals.io/message/111290#111293

**Comment by ndm2** [comment]
> > I'm tempted to have the framework require the PSR interfaces and then have the application require a specific container implementation. This could make plugins a mess to work with though, as they don't have a stable set of interfaces beyond the PSR interfaces that they can use.
> 
> I would prefer this approach as well. Can we identify which interfaces would make plugins a mess?

I think the problem is that plugins can't know or rely on what DIC implementation the application would use, and there is no PSR interface for configuring containers, only for reading from a container, ie plugins would have no interface to add something to a container, which would most likely result in plugin authors requiring specific container implementations, which would be a hot mess.

Support for swapping DIC implementations would probably require something like CakePHP providing a) a very versatile container builder with an interface that applications and plugins can share, and b) bridges for different container implementations.

Somehow that kinda smells like it has the potential to turn into a world of pain.

**Comment by othercorey** [comment]
Well, I was wondering if the requirements are small, cakephp could provide a builder that implements a small API for the 2 big libraries and users can implement their own for custom libraries.

**Comment by markstory** [comment]
>I think the problem is that plugins can't know or rely on what DIC implementation the application would use, and there is no PSR interface for configuring containers, only for reading from a container, ie plugins would have no interface to add something to a container, which would most likely result in plugin authors requiring specific container implementations, which would be a hot mess.

Yes this is precisely my concern as well. Having a container implementation that plugins cannot use makes the solution nonviable in my opinion.

Are the concerns with larger libraries that they are too heavy weight, or too complex to operate? We could provide simpler API's on top of a more complex container, but adding more complex features to a simpler container is more challenging.

**Comment by burzum** [comment]
> Are the concerns with larger libraries that they are too heavy weight, or too complex to operate? We could provide simpler API's on top of a more complex container, but adding more complex features to a simpler container is more challenging.

To wire up some classes is not really rocket science. So if somebody really needs some super advanced feature from a very specific container library, he can simply configure the plugin manually. If somebody *really* needs something advanced I would assume that this person is smart enough to deal with that and knows what he is up to.

I think providing a simple array structure for the container config would be good enough. Almost all other frameworks do that for a decade. You just need a kind of reader that reads the array and configures the actually used container based on that. An object might be better.

```php
$diConfig->map('Foo::class', function(ContainerInterface $container) { ... });
$diConfig->mapStatic('Foo::class', function(ContainerInterface $container) { ... });
$diConfig->useAutoloading();
```

If auto loading is not supported by a container throw an exception in the code that consumes the config object to configure the container.

**Comment by markstory** [comment]
> I think providing a simple array structure for the container config would be good enough. Almost all other frameworks do that for a decade. You just need a kind of reader that reads the array and configures the actually used container based on that. An object might be better.

Wouldn't using an array for configuration add more indirection and overhead than having applications/plugins use the container directly? How would the actual container be configured, would there be adapters from the configuration format you're thinking we provide and different container libraries?

**Comment by burzum** [comment]
> Wouldn't using an array for configuration add more indirection and overhead than having applications/plugins use the container directly?

That's why I suggested an object instead of an array. You can transform it to whatever you want, even using your own object if it implements an interface. "Directly" means tight coupling and you end up being bound to a specific container in the worst case. And I really hate tight coupling.

> How would the actual container be configured, would there be adapters from the configuration format you're thinking we provide and different container libraries?

You would have to manually configure whatever your favorite container is very early in the apps bootstrapping process or create a factory:

```php
LeagueContainerFactory::fromConfig(DiConfig $config);
LeagueContainerFactory::fromArray(DiConfig $config);

PhpDiContainerFactory::fromConfig(DiConfig $config);
PhpDiContainerFactory::fromArray(DiConfig $config);
```

But can you name any "complex" case that might be needed and can only provided by some very specific DI library? The only "problem" are plugins, so you'll need to find a way to abstract interaction with the container when adding stuff to it.

**Comment by robertpustulka** [comment]
Looks cool! More or less how the [DI plugin](https://github.com/robotusers/cakephp-di) works :+1:

**Comment by markstory** [comment]
@robertpustulka Yes. I drew inspiration from that plugin and the piping bag one :smile:

I did some more thinking on what the tasks for these changes could be in case other people want to help move it forward:

- Add league/container as a dependency
- Add wrapper interface and implementation. Having a wrapper interface/class in the Cake namespaces will give us an API that we can control and ensure backwards compatibility for plugins and applications should league/container become unmaintained of if application developers want to use a different container implementation.
- Add new application interface and plugin interfaces. Update BaseApplication and Plugin hook list
  Implement those interfaces. Ideally application has one new method that calls its register and plugin
  register methods so there are fewer changes to make in CommandRunner and Http\Server
- Call new register methods in Server and CommandRunner.
- Update ControllerFactory to resolve dependencies on controller constructor and actions.
- Update CommandFactory to resolve dependencies on constructor and actions.
- Add configure option for autowiring?
- Add Configuration class so that services can have application config added from non-global source.
- Add configuration class to container.
- Write docs chapter on:
    - when to use DI
    - Why no access to container in most places.
    - Adding services
    - How to get dependencies in controllers and cli commands.
    - Service providers
    - Tagging services

I will have some time next week to get started on this.

**Comment by cnizzardini** [comment]
Autowiring could be useful. I didn't like it initially when working with Symfony but I've come to terms with it. Their YAML based approach is not my favorite and I'm not sure how many people actually use the XML variant. I imagine this would be pure PHP and use either OOP or some array structure. 

I'd prefer to deal with objects over `$config` or `$option` style arrays. Beyond simplistic configs/option type things, arrays cause problems if you want to change the structure down the line. Classes are easier to show deprecations and at worst if you intentionally break BC it's done in a way that is easier for users to figure out.

**Comment by robertpustulka** [comment]
Autowiring is possible with `league/container` using `ReflectionContainer` as a delegate.

I actually like the choice of league/container because it's flexible enough to allow me to register other containers as delegates. This way I don't have to rewrite PHP-DI definitions while porting my current projects to 4.2, I will be able to register PHP-DI as a backup container :+1:

**Comment by ADmad** [comment]
I too like `league/container`. PHP-DI seems akin to Guzzle, very feature rich but an overkill for most use cases. 

I am just a bit concerned about `league/container`'s maintenance. My PR for adding PHP 8 support hasn't had any comment or feedback for almost 3 weeks https://github.com/thephpleague/container/pull/205.

[laminas/laminas-di](https://docs.laminas.dev/laminas-di/) could be another lib to consider.

**Comment by burzum** [comment]
IMHO is the "need" for auto-wireing an indicator that something is wrong with the way DI is used. Of course there are cases like services that take a lot different constructor args, but then a factory that runs reflections for this specific kind of object could do the job as well or simply a service provider. No need to introduce global lazyness. :) But I totally agree on the YAML and XML configurations.

**Comment by markstory** [comment]
> IMHO is the "need" for auto-wireing an indicator that something is wrong with the way DI is used. 

That's fair. I don't think we should be enabling auto-wiring out of the box as it has failure modes that people will bump into often (scalar and primitive values). We could show how to use league/container's autowiring features in the docs though for those who need it.

**Comment by markstory** [comment]
Closing as the work related to this issue is complete.
