### ISSUE TITLE
How to get some particular nodes and sub nodes of a particular parent in cake php3

### ISSUE THREAD

**Issue by unni5593** [cakephp/cakephp#14879]
Cake php 3

 when i fetch all the nodes and sub node of a user with referer id "142563" im getting the below array
How to get the id of the first user having vacant not equal zero from this array ????

Array
(
    [3] => Array
        (
            [id] => 3
            [vacant] => 0
            [nodes] => Array
                (
                )
        )
    [4] => Array
        (
            [id] => 4
            [vacant] => 1
            [nodes] => Array
                (
                    [0] => Array
                        (
                            [id] => 5
                            [vacant] => 0
                            [nodes] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 6
                                            [vacant] => 1
                                            [nodes] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [id] => 7
                                                            [vacant] => 2
                                                            [nodes] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [id] => 8
                                                                            [vacant] => 2
                                                                            [nodes] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [id] => 9
                                                                                            [vacant] => 2
                                                                                            [nodes] => Array
                                                                                                (
                                                                                                    [0] => Array
                                                                                                        (
                                                                                                            [id] => 10
                                                                                                            [vacant] => 2
                                                                                                            [nodes] => Array
                                                                                                                (
                                                                                                                    [0] => Array
                                                                                                                        (
                                                                                                                            [id] => 11
                                                                                                                            [vacant] => 2
                                                                                                                            [nodes] => Array
                                                                                                                                (
                                                                                                                                    [0] => Array
                                                                                                                                        (
                                                                                                                                            [id] => 12
                                                                                                                                            [vacant] => 2
                                                                                                                                            [nodes] => Array
                                                                                                                                                (
                                                                                                                                                    [0] => Array
                                                                                                                                                        (
                                                                                                                                                            [id] => 13
                                                                                                                                                            [vacant] => 2
                                                                                                                                                            [nodes] => Array
                                                                                                                                                                (
                                                                                                                                                                    [0] => Array
                                                                                                                                                                        (
                                                                                                                                                                            [id] => 14
                                                                                                                                                                            [vacant] => 2
                                                                                                                                                                            [nodes] => Array
                                                                                                                                                                                (
                                                                                                                                                                                )
   )  
 )  
)   
    )      
 )
        )        
  )  
        )
) 
)
  )
  )  
)

                                        )
                                )
                        )
                )
        )
)

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
