### ISSUE TITLE
Debug output doesn't preserve white space anymore.

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#14874]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x

------

I guess this is either an oversight, or a side-effect of the new formatted debug output, but since `<pre>` has been dropped, white space is not being preserved anymore.

```php
debug("foo    bar\nbaz\t42");
```
displays as:

```
'foo bar baz 42'
```

From a quick test, making `.cake-dbg` preserve white space seems to work fine, but I'm not sure if I'm missing something, as I'm not yet overly familiar with the new formatted HTML output.

**Comment by markstory** [comment]
> From a quick test, making .cake-dbg preserve white space seems to work fine, but I'm not sure if I'm missing something, as I'm not yet overly familiar with the new formatted HTML output.

Not preserving whitespace is an oversight, not an intentional change.
