### ISSUE TITLE
PluginLoadCommand load should check if Plugin exists and CamelCase is correct

### ISSUE THREAD

**Issue by YveIce** [cakephp/cakephp#14870]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 8f673ad
* Platform and Target: 

### What you did
`bin/cake plugin load NOTEXISTINGplugin
`
### What happened

> $this->addPlugin('NOTEXISTINGplugin');

gets added to Application.php, even if the plugin does not exists, breaking everything as the plugin could not be loaded. 

### What you expected to happen
Throw an exception/print an error if the user try's to load a plugin that does not exists or is spelled wrong.

**Comment by markstory** [comment]
Pull request open now.
