### ISSUE TITLE
Any possible to hide pagination column name will be good

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#14878]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: -

Paginator helper using for sorting (and other methods) database column field name. This reveals the structure of the table in the database.
It's possible to using some alias to hide realy column field name?

For example:
`PaginatorHelper::sort('user_id', 'User', ...)` given `?sort=user_id&direction...`
but better for security would be:
`PaginatorHelper::sort(['user_id' => 'user'], 'User', ...)` which given `?sort=user&direction...`

**Comment by dereuromark** [comment]
I dont think that this is security related.
As long as it is properly whitelisted (as documented), only the actual intended fields will be sortable and all is fine.

That said:  Refs https://github.com/cakephp/cakephp/issues/10028#issuecomment-272812357
If anyone would implement this improved paginator we would also solve a lot of other issues in the process, including the overly complex way of building and validating the current sort/direction. Even the current latest implementation has some flaws when it comes to joined tables etc.
We would also be able to drop the direction even altogether, making this much simpler in usage.

But given the response here so far, no one wanted to touch this piece of code yet :)
