### ISSUE TITLE
SQL Azure transient connection error when server unavailable

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/cakephp#14875]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1.1
* Platform and Target: Windows, IIS (Azure App Service), SQL Server Azure, HTTPS

### What you did
I'm using SQL Server on Azure (not by my choice) and it works fine for our application, but we recently tried using an on-demand instance for the database to reduce costs. There's no issue with the application, except when the database is waking up from pausing. I currently set it up to pause after 1 hour of inactivity. When connecting after the database was 'paused', SQL Server throws an error saying to basically check again in a few moments.

I tried to get around this error by setting the `loginTimeout` option on the database connection to 600 (10 minutes), hoping CakePHP could wait until the server is available or retry the connection at some point.

### What happened
The following error is thrown by the SQL Server driver when the database is still waking up: 
`[PDOException] SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258]`

And the following can also be thrown: 
```Error: [Cake\Database\Exception\MissingConnectionException] Connection to Sqlserver could not be established: SQLSTATE[HY000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'xxxxx' on server 'xxxxx.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{xxxxx}'. in D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver.php on line 121

Caused by: [PDOException] SQLSTATE[HY000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'xxxxx' on server 'xxxxx.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{xxxxx}'. in D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver.php on line 118
```

### What you expected to happen
I noticed there is some connection retrying code in CakePHP, and I understand this is a pretty specific platform issue. I opened this issue to determine if this is something that either the framework can allow handling, if this is truly a bug (or unsupported), and if there is a workaround I can do. 

Thanks for all the great work on the framework!

**Comment by othercorey** [comment]
Is this thrown in the connection code or during a query? How long does it actually wait to timeout?

**Comment by kyleweishaupt** [comment]
The error is being thrown when one of my behaviors calls `$this->getTable()->hasField()` during initialization, so it appears to be a query.

When the database is paused, it's right around 20 seconds before the error is thrown.

Here is the full stack trace:
```Stack Trace:
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver.php:118
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver\Sqlserver.php:154
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Schema\SchemaDialect.php:47
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver\Sqlserver.php:273
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Schema\Collection.php:53
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Connection.php:399
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Table.php:508
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Table.php:623
- D:\home\site\wwwroot\src\Model\Behavior\PasswordBehavior.php:37
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Behavior.php:167
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\BehaviorRegistry.php:145
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php:108
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Table.php:775
- D:\home\site\wwwroot\src\Model\Table\UsersTable.php:164
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Table.php:318
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php:245
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php:200
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Datasource\Locator\AbstractLocator.php:59
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php:155
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Datasource\ModelAwareTrait.php:124
- D:\home\site\wwwroot\src\Controller\SpaController.php:47
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Controller\Controller.php:210
- ReflectionClass::newInstance() - [internal], line ??- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Controller\ControllerFactory.php:56
- D:\home\site\wwwroot\src\Policy\RequestPolicy.php:88
- D:\home\site\wwwroot\src\Policy\RequestPolicy.php:35
- D:\home\site\wwwroot\vendor\cakephp\authorization\src\AuthorizationService.php:93
- D:\home\site\wwwroot\vendor\cakephp\authorization\src\AuthorizationService.php:66
- D:\home\site\wwwroot\vendor\cakephp\authorization\src\Middleware\RequestAuthorizationMiddleware.php:97
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\authorization\src\Middleware\AuthorizationMiddleware.php:129
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\authentication\src\Middleware\AuthenticationMiddleware.php:124
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php:166
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Middleware\BodyParserMiddleware.php:159
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php:68
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:121
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:73
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Runner.php:58
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Http\Server.php:90
- D:\home\site\wwwroot\webroot\index.php:40
- D:\home\site\wwwroot\index.php:17

**Comment by garas** [comment]
Could you try `ConnectRetryCount`, `ConnectRetryInterval` options ([docs](https://docs.microsoft.com/en-us/sql/connect/php/connection-options?redirectedfrom=MSDN&view=sql-server-ver15))? CakePHP doesn't handle these now, but should be able to inject via other options like `'database' => 'dbname;ConnectRetryCount=10'`.

**Comment by kyleweishaupt** [comment]
@garas 
That's a great idea. I did try adding `ConnectRetryCount` and `ConnectRetryInterval` to the options like you suggested. After waiting for the database to pause, the same error still comes up.

**Comment by othercorey** [comment]
@kyleweishaupt Does the connection timeout after the new interval + count or still after 15s?

**Comment by kyleweishaupt** [comment]
@othercorey I've only been able to test once since adding the options, but it seemed to still fail after ~15s.

I have this in my app.config: `'database' => env('DATABASE_NAME', 'database'). ';ConnectRetryCount=5;ConnectRetryInterval=10',`

**Comment by othercorey** [comment]
Can you give us a link to the documentation on the azure db instance type you're using?

**Comment by kyleweishaupt** [comment]
The closest documentation I can find is [Troubleshoot Common Error Issues](https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-errors-issues).

There's also [Connect resiliently to SQL with PHP](https://docs.microsoft.com/en-us/sql/connect/php/step-4-connect-resiliently-to-sql-with-php?view=sql-server-ver15)

**Comment by othercorey** [comment]
> but we recently tried using an on-demand instance for the database to reduce costs. There's no issue with the application, except when the database is waking up from pausing.

I want the information on this.

**Comment by kyleweishaupt** [comment]
@othercorey 

Pricing Tier: General Purpose: Serverless, Gen5, 1 vCore
Location: North Central US
Max Size: 32 GB
Auto-pause Delay: 1 hour (minimum)

Documentation: [Serverless Tier Overview](https://docs.microsoft.com/en-us/azure/azure-sql/database/serverless-tier-overview)

**Comment by othercorey** [comment]
The retry logic in the odbc driver must be wrapping a high-level connection not the sql server result. We might need to catch this specific error code and retry the full connection.

The error code **40613** isn't part of the transient error logic they provide, but it does match the errors other have reported.

**Comment by kyleweishaupt** [comment]
That's what made me unsure about if this was something that could be handled by CakePHP. The PHP connection resiliency docs says error codes starting with `08` like in `[PDOException] SQLSTATE[08001]` should retry.

**Comment by othercorey** [comment]
If this is going to be a common configuration, we can do something to support it. However, it will be difficult to test. Are you able to run with a patched cakephp package?

**Comment by kyleweishaupt** [comment]
I did find a [pause API](https://docs.microsoft.com/en-us/rest/api/sql/databases/pause) so I can run a patched version and test this. Thanks for looking into it!

**Comment by othercorey** [comment]
@kyleweishaupt Are you able to apply the patch in #14884 to test? This waits 5s for 5 retries. I'm not sure that's long enough for the pause sequence.

**Comment by kyleweishaupt** [comment]
@othercorey I've loaded the `retry-connect` branch and deployed it, but the error remains the same and still within around 15s before the exception is thrown. 

Here's the log again from the exception with the details obscured: ```
2020-08-09 18:14:22 Error: [Cake\Database\Exception\MissingConnectionException] Connection to Sqlserver could not be established: SQLSTATE[HY000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database '_dbname_' on server '_dbname_.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_}'. in D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Driver.php on line 153
```

**Comment by othercorey** [comment]
@kyleweishaupt Thanks for testing. I guess the error code returned by PDOException is not what we thought?

```
    protected const CONNECT_RETRY_ERROR_CODES = [
        40613, // Azure Sql Database paused
    ];
```

**Comment by othercorey** [comment]
I think there might be a php bug with the error info not set during PDO creation.

Can you try testing again? I updated the implementation, but I have only been able to test with local mysql errors which probably set the code differently.

**Comment by othercorey** [comment]
https://bugs.php.net/bug.php?id=64705

**Comment by kyleweishaupt** [comment]
I just tried the latest changes on the branch and did get the application to load without throwing the PDO error. 
I'll try a couple more times throughout the day to make sure.

Just for information, my app is supposed to be running PHP 7.4 on Azure, but it's reporting as 7.3.17 with pdo_sqlsrv driver version 5.6.1+11919. 

Hopefully the PHP issue gets addressed soon. Thanks again for looking into this!

**Comment by othercorey** [comment]
The Driver instance has a new connectRetries() getter. Would love to know what that is after successful connection to help tune the settings.

**Comment by kyleweishaupt** [comment]
I'll add in some code today to try and grab the connection retries and log it. If you have any specific way of implementing this, let me know.

**Comment by othercorey** [comment]
Nope. You can get the driver from the connection and then just log the retry count.

**Comment by kyleweishaupt** [comment]
Just made a simple middleware that logged the retry count, and got a connection after 2 retries. Both times the database was paused. 

```
2020-08-10 19:00:49 Notice: Cake\Database\Driver\Sqlserver had 2 retries.
2020-08-10 20:19:57 Notice: Cake\Database\Driver\Sqlserver had 2 retries.
```
