### ISSUE TITLE
Should ExceptionRenderer only set HTTP code if a cake Exception?

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14897]
Should the exception code only be interpreted as an HTTP code if the exception extends `Cake\Core\Exception\Exception` which documents the code explicitly as an HTTP code?

**Exception.php**
```
     * @param string|array $message Either the string of the error message, or an array of attributes
     *   that are made available in the view, and sprintf()'d into Exception::$_messageTemplate
     * @param int|null $code The code of the error, is also the HTTP status code for the error.
     * @param \Throwable|null $previous the previous exception.
     */
    public function __construct($message = '', ?int $code = null, ?Throwable $previous = null)
```

**ExceptionRenderer**
```
    protected function _code(Throwable $exception): int
    {
        $code = 500;
        $errorCode = (int)$exception->getCode();
        if ($errorCode >= 400 && $errorCode < 600) {
            $code = $errorCode;
        }

        return $code;
    }
```

**Comment by dereuromark** [comment]
What's the reason? If you didn't set one it will be 5xx as expected already, won't it?
I don't see an issue with current way so far.

**Comment by othercorey** [comment]
There are many exception codes outside of cake's internal exceptions.

**Comment by ADmad** [comment]
> There are many exception codes outside of cake's internal exceptions.

Are there any non HTTP codes within the 400-599 range?

**Comment by othercorey** [comment]
> Are there any non HTTP codes within the 400-599 range?

I have no idea what other codes like PDOException throw. That's why I'm asking this.

**Comment by garas** [comment]
More logical would be only use `\Cake\Http\Exception\HttpException` error code for HTTP code, any other exception would be always 500.

That would require change parents of few exceptions:

Change parent of `\Cake\Controller\Exception\MissingActionException` to `\Cake\Http\Exception\NotFoundException`.

Change parent to `\Cake\Http\Exception\NotFoundException`, but `cakephp/datasource` would require new dependency `cakephp/http`:
- `\Cake\Datasource\Exception\InvalidPrimaryKeyException`
- `\Cake\Datasource\Exception\PageOutOfBoundsException`
- `\Cake\Datasource\Exception\RecordNotFoundException`

Change parent of `\Cake\Http\Exception\InvalidCsrfTokenException` to `\Cake\Http\Exception\ForbiddenException`.

Change parent of `\Cake\Routing\Exception\RedirectException` (deprecated) to `\Cake\Http\Exception\RedirectException`.

`\Cake\Mailer\Exception\MissingActionException` has error code 404, but it is server error, not user error, should be 5xx.

**Comment by dereuromark** [comment]
@garas MissingAction as well as https://github.com/dereuromark/cakephp-tools/blob/master/src/Error/ErrorHandlerTrait.php#L36-L55 should all be treated as 4xx from the outside (user web) as well inside (logging) IMO. Especially if they are triggered from the outside through old links or bots.
Having them wrongly go into error stream is a huge pain as it cloaks the actual errors. Thats why I am using this shim error handling for 5 years now.

**Comment by ADmad** [comment]
@garas Your suggestions sound reasonable, I just don't like having the `http` package as a dependency of `database` package. We should add a new parent exception for all database exception and the error handler/exception renderer should convert that exception to an HttpException with error code 500.

**Comment by markstory** [comment]
> \Cake\Mailer\Exception\MissingActionException has error code 404, but it is server error, not user error, should be 5xx.

I don't think this is always a 500 though. If you're using fallback routing, then missing actions are not found and not 500s.

I would like to not add a dependency between datasource and the http packages. Not wanting that cross package dependency is one of the reasons we currently type hint against the base class in Core.

**Comment by dereuromark** [comment]
Yes, please dont make more 4xx to 5xx where this is just plain wrong. From external perspective we shouldn't be able to trigger any 5xx where the conventional routing just triggers those exceptions, but in the end are all "not found" and should also be that way (not leaking internal controller structure).

**Comment by garas** [comment]
There are 2 `MissingActionException`:

- `\Cake\Mailer\Exception\MissingActionException` is unrelated to routing, current 404 should be changed to 500.

- `\Cake\Controller\Exception\MissingActionException` is used in routing, should be child of `Cake\Http\Exception\NotFoundException`.

---

Overall idea is exceptions to 2 groups:
- error code is HTTP code,
- error code is just plain code, and rendered as 500.

I wouldn't like adding new dependency of `datasource` too. But I don't know how to do this otherwise for datasource exceptions, because they should stay 404.

**Comment by othercorey** [comment]
> I wouldn't like adding new dependency of `datasource` too. But I don't know how to do this otherwise for datasource exceptions, because they should stay 404.

We could simply have another exception type convert error code to http. Maybe a RecordException or something in Datasource.

**Comment by garas** [comment]
> We could simply have another exception type convert error code to http. Maybe a RecordException or something in Datasource.

Another part of idea is to simplify `if ($errorCode >= 400 && $errorCode < 600)` to `if ($exception instanceof HttpException)`.

But new exception would make it unsimple like `if ($exception instanceof HttpException || $exception instanceof RecordException)`.

**Comment by othercorey** [comment]
> But new exception would make it unsimple like `if ($exception instanceof HttpException || $exception instanceof RecordException)`.

Right, but we could have an interface in Core\Exception that provides a `hasHttpCode()` or something.

**Comment by markstory** [comment]
An interface in the core package is a great place for the 'interface of exceptions that can return an HTTP status code'. That would allow datasource and http package work together without more cross package dependencies.
