### ISSUE TITLE
PaginatorHelper not merging URL parameters correctly

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#14894]
This is an apparent **bug** in CakePHP 3.8.12.

### What I did
I'm using the `PaginatorHelper` in CakePHP 3.8 and passing `'url' => ['?' => ['foo' => 'bar']]` into the options of its `first()`, `prev()`, `next()`, and `last()` buttons.

### What happened
`prev()` and `next()` are forming URLs as expected, but `first()` and `last()` are ignoring the query string parameter and not adding `'foo'` to the URL.

**Comment by othercorey** [comment]
Might be related to https://github.com/cakephp/cakephp/issues/14155

**Comment by dereuromark** [comment]
Do you have a PR with a fix or the failing tests for 3.x?

**Comment by PhantomWatson** [comment]
I have neither of those. At the moment, I only have the time and wherewithal to help document this. I'll post another comment if I can begin work on a fix.
