### ISSUE TITLE
Setting filename for inline attachment in response is missing

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#14892]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.2

### What you did
In my response I want to send a file, but instead of forcing the download I want to set the Content-Disposition to "inline" so that the file (in this case a pdf) is opened in the browser and when the user decides to save the file, the specified filename should be used. This is not possible so far (or at least I did not find out how to do this).

A new method in Cake/Http/Response would help

```
public function withInlineAttachment(string $filename)
{
    return $this->withHeader('Content-Disposition', 'inline; filename="' . $filename . '"');
}
```

It would be nice, if this could be integrated in the existing method `withFile()`, 

Thank you!

**Comment by markstory** [comment]
> It would be nice, if this could be integrated in the existing method withFile(),

What would the interface extension to `withFile` look like? Would something like 

```php
$this->response->withFile('file.pdf', ['as' => 'inline', 'name' => 'best-thing.pdf']);
```

Work? This would also make the `download => true` option an alias for `as => 'download'`. I don't think another boolean option is a good idea as then we have to handle the situation where both are set.

**Comment by mrothauer** [comment]
Yes, your interface suggestion is working for my use case.

**Comment by dereuromark** [comment]
I have been using https://github.com/dereuromark/cakephp-tools/blob/5753afad12101c14974fa98e1fbde8685f4bf8a7/src/Mailer/Message.php#L189 for 10 years now for embedded attachments etc. But that doesnt mean download true though. 
maybe inline means sth else than embedded here?

**Comment by ADmad** [comment]
Isn't in browser display the default behavior if you don't force download? @mrothauer Have you tried just setting `'download' => false` in options of `withFile()`?

**Comment by othercorey** [comment]
If you view a file inline, can you then save the file from the browser? Does the browser accept the content disposition when saving? Maybe that's what the user wants. 

I wonder if the behavior is different for mobile browsers.

**Comment by mrothauer** [comment]
> Have you tried just setting 'download' => false in options of withFile()?
Yes, I tried that. Instead of the passed filename, the name of the action is used in the save-as dialog.

**Comment by mrothauer** [comment]
> If you view a file inline, can you then save the file from the browser? Does the browser accept the content disposition filename when saving?
In Windows 10 / Chrome it works (with a PDF)
In Android / Chrome the file is downloaded immediately and then opened with my default pdf app. Filename is correct.

That's my workaround (using ->withFile() - download defaults to null - and then overriding the Content-Disposition header).
https://github.com/foodcoopshop/foodcoopshop/blob/9827c848eeb580e0a526a7c6fdbc7830c88cb70f/plugins/Admin/src/Controller/ListsController.php#L165-L169

**Comment by othercorey** [comment]
Unless the filename is absolutely needed, we could just have withFile() default to `inline` explicitly even though it's supposed to be the default Content Disposition.

**Comment by mrothauer** [comment]
`
$this->response->withFile('file.pdf', ['as' => 'inline', 'name' => 'best-thing.pdf']);
`
This suggestion from @markstory would fit my needs. If I create a PR for that, would it be merged?

**Comment by markstory** [comment]
@mrothauer A pull request would be great. I'm cautious of changing the current default behavior as we run the risk of breaking existing usage and adding a new option whilst also deprecating `download` is safer.

**Comment by dereuromark** [comment]
Oh I first thought this was about emails and inline files.

Regarding inline files and file names:
This is quite browser-specific. Even if you put a name there, usually they still take the current file name in the URL when downloading it.
As such I would also rather go that way, e.g. URL of:

   .../my-file.ext

This can even be just an additional passed param of sorts after the actual action.
This way it will work without any specific tricks and also work across usually all browsers.

**Comment by mrothauer** [comment]
> As such I would also rather go that way, e.g. URL of:
> .../my-file.ext

@dereuromark Thank's for that input!

My current url looks like this: (The file name is passed as get parameter)
https://demo-de.foodcoopshop.com/admin/lists/getOrderList?file=2020/08/2020-08-07_Demo-Milch-Hersteller_15_Bestellliste_Produkt_FoodCoopShop-Demo-2020-08-05_04-30-03.pdf
Without the "new" inline option, Chrome on Windows suggests to save it as "getOrderList.pdf" in the save-as dialog.
With `'Content-Disposition', 'inline; ` and setting the file name explicitely, this file name is suggested.

> This can even be just an additional passed param of sorts after the actual action.
My question: How would that work, can you give me an example for my url? Of course, I could still add a route so that I do not need an extra parameter.

**Comment by dereuromark** [comment]
I documented it here: https://www.dereuromark.de/2011/11/21/serving-views-as-files-in-cake2/#browser-bugs-and-easter-eggs

**Comment by mrothauer** [comment]
Great! I'll adapt my url and everything should work (in every browser!). So no PR needed here.

**Comment by dereuromark** [comment]
Check it first :) this was written and analyzed 9 years ago^^

**Comment by mrothauer** [comment]
We can close this issue for now, I'll keep it updated as soon as I implement your suggested solution. Thank's to everybody!

**Comment by othercorey** [comment]
If setting the content disposition as inline makes the browser work in all situations, I thunk it would be useful to have. Its something I’ll will need soon if there are issies.

**Comment by dereuromark** [comment]
Back in those years it sure didnt work in all browsers, at best only in some. But since then the situation (and standards) could have improved.

**Comment by mrothauer** [comment]
> If setting the content disposition as inline makes the browser work in all situations, I think it would be useful to have. Its something I will need soon if there are issues.

But only If it works in all browsers... It's definitely the better option, as it's a url-independent solution. Somebody needs to proof that it works.
