### ISSUE TITLE
.json ext giving Missing Method

### ISSUE THREAD

**Issue by ukkpower** [cakephp/cakephp#14902]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:4.0.9
* Platform and Target: MAMP, PHP 7, MYSQL

### What you did
I have a relatively clean install of CakePHP 4. I have read all the docs related to JSON routing with an extension and using accept header in the AJAX call `"Accept", "application/json"`. Both methods give me a 404 missing method. I have posted the issue on both StackOverflow and CakePHP support forum but the help unfortunately didn't solve the issue. I am beginning to think it is an issue with CakePHP because I have done all in the docs.

https://discourse.cakephp.org/t/json-ext-giving-missing-method/8211

https://stackoverflow.com/questions/63282271/cakephp-json-ext-giving-missing-method

    Missing Method in StrategiesConditionsController
    Cake\Controller\Exception\MissingActionException
    
    Error The action conditions.json is not defined in StrategiesConditionsController
    
    Create StrategiesConditionsController::conditions.json() in file: src/Controller/StrategiesConditionsController.php.

From reading the doc a couple of times I am sure I have the routes correct.

routes.php

    <?php
    /**
     * Routes configuration.
     *
     * In this file, you set up routes to your controllers and their actions.
     * Routes are very important mechanism that allows you to freely connect
     * different URLs to chosen controllers and their actions (functions).
     *
     * It's loaded within the context of `Application::routes()` method which
     * receives a `RouteBuilder` instance `$routes` as method argument.
     *
     * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
     * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
     *
     * Licensed under The MIT License
     * For full copyright and license information, please see the LICENSE.txt
     * Redistributions of files must retain the above copyright notice.
     *
     * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
     * @link          https://cakephp.org CakePHP(tm) Project
     * @license       https://opensource.org/licenses/mit-license.php MIT License
     */
    
    use Cake\Http\Middleware\CsrfProtectionMiddleware;
    use Cake\Routing\Route\DashedRoute;
    use Cake\Routing\RouteBuilder;
    use Cake\Routing\Router;
    
    /*
     * The default class to use for all routes
     *
     * The following route classes are supplied with CakePHP and are appropriate
     * to set as the default:
     *
     * - Route
     * - InflectedRoute
     * - DashedRoute
     *
     * If no call is made to `Router::defaultRouteClass()`, the class used is
     * `Route` (`Cake\Routing\Route\Route`)
     *
     * Note that `Route` does not do any inflections on URLs which will result in
     * inconsistently cased URLs when used with `:plugin`, `:controller` and
     * `:action` markers.
     */
    /** @var \Cake\Routing\RouteBuilder $routes */
    $routes->setRouteClass(DashedRoute::class);
    
    $routes->scope('/', function (RouteBuilder $routes) {
        $routes->setExtensions(['json']);
        $routes->resources('StrategiesConditions', [
            'map' => [
                'conditions' => [
                    'action' => 'conditions',
                    'method' => 'post'
                ]
            ],
            'only' => ['conditions']
         ]);
    });
    
    $routes->scope('/', function (RouteBuilder $builder) {
        // Register scoped middleware for in scopes.
        $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
            'httpOnly' => true,
        ]));
    
        /*
         * Apply a middleware to the current route scope.
         * Requires middleware to be registered through `Application::routes()` with `registerMiddleware()`
         */
        $builder->applyMiddleware('csrf');
    
        /*
         * Here, we are connecting '/' (base path) to a controller called 'Pages',
         * its action called 'display', and we pass a param to select the view file
         * to use (in this case, templates/Pages/home.php)...
         */
        $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    
        /*
         * ...and connect the rest of 'Pages' controller's URLs.
         */
        $builder->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    
        /*
         * Connect catchall routes for all controllers.
         *
         * The `fallbacks` method is a shortcut for
         *
         * ```
         * $builder->connect('/:controller', ['action' => 'index']);
         * $builder->connect('/:controller/:action/*', []);
         * ```
         *
         * You can remove these routes once you've connected the
         * routes you want in your application.
         */
        $builder->fallbacks();
    });
    
    Router::prefix('admin', function (RouteBuilder $routes) {
        $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);
        $routes->fallbacks(DashedRoute::class);
    });
    
    /*
     * If you need a different set of middleware or none at all,
     * open new scope and define routes there.
     *
     * ```
     * $routes->scope('/api', function (RouteBuilder $builder) {
     *     // No $builder->applyMiddleware() here.
     *     // Connect API actions here.
     * });
     * ```
     */

strategiesConditionsController

    public function conditions()
    {
        $this->request->allowMethod(['post']);

        if ($this->request->is('ajax')) {
            $this->response = $this->response->withDisabledCache();
        }

        $strategy_id = $this->request->getData('strategy_id');
        
        $strategiesConditions = $this->StrategiesConditions->find('all', [
            'where' => ['strategy_id' => $strategy_id],
        ]);
        $this->viewBuilder()->setOption('serialize', ['strategiesConditions']);
    }

Cakephp console has 8 routes showing

    Route name	URI template	Defaults
    pages:display	/	
    {
        "controller": "Pages",
        "action": "display",
        "0": "home",
        "plugin": null
    }
    pages:display	/pages/*	
    {
        "controller": "Pages",
        "action": "display",
        "plugin": null
    }
    _controller:index	/{controller}	
    {
        "action": "index",
        "plugin": null
    }
    _controller:_action	/{controller}/{action}/*	
    {
        "plugin": null,
        "action": "index"
    }
    admin:users:index	/admin	
    {
        "controller": "Users",
        "action": "index",
        "prefix": "Admin",
        "plugin": null
    }
    admin:_controller:index	/admin/{controller}	
    {
        "action": "index",
        "prefix": "Admin",
        "plugin": null
    }
    admin:_controller:_action	/admin/{controller}/{action}/*	
    {
        "prefix": "Admin",
        "plugin": null,
        "action": "index"
    }
    strategiesconditions:conditions	/strategies-conditions/conditions	
    {
        "controller": "StrategiesConditions",
        "action": "conditions",
        "_method": "post",
        "plugin": null
    }

Update from the history tab in debug kit

    Request
    Routing Params
    controller StrategiesConditions
    action conditions.json
    pass (empty)
    plugin (null)
    _matchedRoute /{controller}/{action}/*
    _ext (null)
    Post data
    strategy_id 11
    Query string
    No querystring data.
    
    Cookie
    csrfToken dd12f852560a384d39206e511f1857f77f71da2eadb023a6c67ae346
    PHPSESSID 3d2jt7dgpo09af8b1908quljpn
    Matched Route
    template /{controller}/{action}/*

and the routes tab:

    Routes
    Toggle debugkit internal routes
    Route name	URI template	Defaults
    pages:display	/	
    {
        "controller": "Pages",
        "action": "display",
        "0": "home",
        "plugin": null
    }
    pages:display	/pages/*	
    {
        "controller": "Pages",
        "action": "display",
        "plugin": null
    }
    _controller:index	/{controller}	
    {
        "action": "index",
        "plugin": null
    }
    _controller:_action	/{controller}/{action}/*	
    {
        "plugin": null,
        "action": "index"
    }
    admin:users:index	/admin	
    {
        "controller": "Users",
        "action": "index",
        "prefix": "Admin",
        "plugin": null
    }
    admin:_controller:index	/admin/{controller}	
    {
        "action": "index",
        "prefix": "Admin",
        "plugin": null
    }
    admin:_controller:_action	/admin/{controller}/{action}/*	
    {
        "prefix": "Admin",
        "plugin": null,
        "action": "index"
    }
    strategiesconditions:conditions	/strategies-conditions/conditions	
    {
        "controller": "StrategiesConditions",
        "action": "conditions",
        "_method": "post",
        "plugin": null
    }

Request URL

http://localhost:8888/trading-journal/strategies-conditions/conditions.json

Application.php

            // Add routing middleware.
            // If you have a large number of routes connected, turning on routes
            // caching in production could improve performance. For that when
            // creating the middleware instance specify the cache config name by
            // using it's second constructor argument:
            // `new RoutingMiddleware($this, '_cake_routes_')`
            ->add(new RoutingMiddleware($this))

Thanks

**Comment by markstory** [comment]
It looks like your requests are being handled by the fallback routes instead of your resource route based on the `_matchedRoute /{controller}/{action}/*` that is in your request data.

You can try disabling those routes to see if you end up in the correct route. You should also be seeing the `_ext` route parameter populated.

**Comment by ukkpower** [comment]
I have removed everything in the routes.php except for the conditions.json scope. I now get the error `A route matching "/strategies-conditions/conditions.json" could not be found.`

**Comment by markstory** [comment]
I'll see if I can reproduce your problem based on what is here.

**Comment by markstory** [comment]
The issue is that you have `method => 'post'` it should be `method => 'POST'`. I will open a pull request to uppercase the HTTP methods for custom actions though as this is something the framework could smooth over.

**Comment by ukkpower** [comment]
Thanks Mark. I can confirm that has worked 👍
