### ISSUE TITLE
Add support None/Dummy Datasource

### ISSUE THREAD

**Issue by mhf-ir** [cakephp/cakephp#14928]
I need View and Controller and Elements and etc feature of cakephp. Exclude Model/Database/Datasource.

This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
Run cakephp just as VC framework I dont need Database/Datasource

### What happened
Error seems be a dependency or there is no documentation for that 

### What you expected to happen
Run cakephp without Model/Database/Datasource

**Comment by markstory** [comment]
We don't offer `Controller` or `View` as separate packages. How are you getting just those pieces? Or are you asking for a way to make that possible?

**Comment by mhf-ir** [comment]
@markstory yeah the way of how to we have cake without database/datasource

**Comment by CauanCabral** [comment]
I did an experiment with a `Dummy` driver (for another reason), maybe it can help you: https://github.com/cakephp/elastic-search/blob/cd85257c4062507f63615dd31641b1115c25d870/src/Database/Driver/Dummy.php

**Comment by garas** [comment]
You don't need any dummy drivers, just don't use CakePHP datasource/database/ORM functionality.

Use controller, templates, routing functionality etc what you need, add additional libraries via Composer if necessary.

**Comment by mhf-ir** [comment]
@garas year will be great if be part of documentation. By default i comment or add even dummy driver try to write a driver non of those work as i expected. so will be great if we have best practices for this usecase.

**Comment by dereuromark** [comment]
"Error seems be a dependency or there is no documentation for that"
You need to be more specific here
What exactly is the error that you see?
As by default, the framework can work just fine with the use case you described.

**Comment by mhf-ir** [comment]
```
composer create-project --prefer-dist cakephp/app:^4 tmp1
```

Set `'Datasources' => []` in `app.local.php` and `app.php`.

```
bin/cake server
```

Error:


![Screenshot from 2020-08-25 14-43-05](https://user-images.githubusercontent.com/1172526/91162432-510c1d80-e6e1-11ea-8c88-c83e6489656a.png)

**Comment by mhf-ir** [comment]
After all 

* Datasources
* EmailTransport
* Email

Should be easily disabled. This parts are not essential. 
Think about the cake is simple router/View/Controller framework. Model will be the the remote data with HTTP client.

 Micro services might help with those parts

**Comment by dereuromark** [comment]
Why is DebugKit not using default SQLite DB?
a) install SQLite and make sure it uses that (which should happen by default)
or
b) remove DebugKit for now, until this is resolved from your side

**Comment by mhf-ir** [comment]
@dereuromark seems be the cakephp require `ext-sqlite3`

**Comment by dereuromark** [comment]
No, DebugKit does, as I just explained :)
So remove this optional plugin (which you don't need - it is just to help people develop their apps faster/better), and all works fine.
Closing then.

For the future: Please always attach the concrete error messages and details in the opening comment of your ticket.
Then this would have been cleared up way faster.
