### ISSUE TITLE
Unable to render flash helper templates from plugins

### ISSUE THREAD

**Issue by ordinarywebguy** [cakephp/cakephp#14920]
* [x] bug

* CakePHP Version: 4.1.3
* Platform and Target: OS: Ubuntu Linux 18.04.5 PHP 7.2.24

### What you did
In the template:
`<?= $this->Flash->render('flash', ['plugin' => 'PluginName']) ?>`

Plugin loaded in App\Application::bootstrap
$this->addPlugin('PluginName');

Updated composer ps-4 autoload

### What happened
It is still rendering the template from templates/element/flash/*

### What you expected to happen
It should use the template from plugins/PluginName/templates/element/flash/*

Suggested fix in FlashHelper::render
From
```php
foreach ($flash as $message) {
    $message = $options + $message;
    $out .= $this->_View->element($message['element'], $message);
}
```
To	

```php
foreach ($flash as $message) {
     if (!empty($options['plugin'])) {
         $message['element'] = $options['plugin'] . '.' . $message['element'];
     }
     $message = $options + $message;
     $out .= $this->_View->element($message['element'], $message);
}
```

**Comment by dereuromark** [comment]
Following other conventions and existing plugin syntax, this would be more like

    <?= $this->Flash->render('PluginName.flash') ?>

Or at least that's what one would expect to work.

**Comment by markstory** [comment]
There is no documented `plugin` option for FlashHelper::render(). There could be one added in a future release though.

**Comment by ADmad** [comment]
I don't see why we need a new option if `Flash->render('PluginName.flash')` achieves the same.

**Comment by ordinarywebguy** [comment]
> Following other conventions and existing plugin syntax, this would be more like
> 
> ```
> <?= $this->Flash->render('PluginName.flash') ?>
> ```
> 
> Or at least that's what one would expect to work.

Nope, I tried this one and it's not rendering the flash message anymore

Below will work however, it will only render a single message type or state e.g. success or default:

```
echo $this->Flash->render('flash', [
     'element' => 'MyPlugin.my_custom_element',
]);
```


Yeah, best to document the correct usage. 

Thanks!

**Comment by markstory** [comment]
Going to close this. I've added an example to the docs.
