### ISSUE TITLE
HtmlHelper>-_renderCells should convert mixing values of $cell to string bevor passing it to tableCell()

### ISSUE THREAD

**Issue by YveIce** [cakephp/cakephp#14921]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 8f673ad
* Platform and Target: --

### What you did
`echo $this->Html->tableCells(
    [
        ['Foo', 'Bar'],
        ['Yve', 'Ice'],
        [42, 1.2345],
    ]
);`

### What happened
TypeError Exception in HtmlHelper::tableCell(), because this function aspects the argument strictly to be of type string

### What you expected to happen
HtmlHelper::_renderCells() should convert arguments of type int, float, bool to string before passing it to HtmlHelper::tableCell() as $cell. 
So we can use mixed arrays.

**Comment by ADmad** [comment]
I think we should just remove the `string` typehint from `$content` argument of `tableCell()`. the `vsprintf()` in string formatter will eventually take care of typecasting any value to string.

**Comment by dereuromark** [comment]
@ADmad is that also true for php 8 in strict mode?

**Comment by ADmad** [comment]
The individual items of `$args` array are of mixed type and pretty sure it won't change in PHP 8. Test case would confirm that since we run builds in PHP 8 too.

**Comment by dereuromark** [comment]
Adding the cast might still be a bit more BC than removing a typehint.
Also phpstan would complain about any non string input anyway due to docblock.

**Comment by YveIce** [comment]
My point of view is, to leave the string typehint until cakephp is PHP-8+ only. Then uniontypes of PHP-8 can be handy with a typehint deceleration of "string|int|float". 
When passing objects, void, null ... i still would aspect an exception, instead of having an silent conversion to a string. So just removing the string typehint from tableCell() is maybe not the best way to go. 
vsprintf() would typecast bool and null to an empty string without exception, if i remember it correctly.

**Comment by dereuromark** [comment]
@YveIce Do you want to make a PR with the suggested changes?

**Comment by ADmad** [comment]
> vsprintf() would typecast bool and null to an empty string without exception

I personally have no problem with that. All falsey PHP values would be same in string/HTML.

**Comment by ADmad** [comment]
That said I don't mind if we just cast to string when calling tableCells(). Changing typehint is not something we can do in a patch release anyway.

**Comment by ADmad** [comment]
> a typehint deceleration of "string|int|float"

The list should include `Stringable` too :)
