### ISSUE TITLE
Not able to delete cookie !

### ISSUE THREAD

**Issue by neobie** [cakephp/cakephp#14926]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
CakePHP 2.10.20

https://book.cakephp.org/2/en/core-libraries/components/cookie.html#CookieComponent::delete

Deleting Cookie
$this->Cookie->delete('User'); //is not able to delete the cookie itself.
$this->Cookie->delete('User.id'); //I need to call this to actually delete the cookie !

**Comment by markstory** [comment]
What cookie value are you trying to delete?

**Comment by othercorey** [comment]
@neobie We will close this if you don't have more information.
