### ISSUE TITLE
Cakephp 3 prefix routing namely 'vendor' not working without trailing slash

### ISSUE THREAD

**Issue by kathiresanKRTB** [cakephp/cakephp#14937]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:  3.6

### What you did

created project with 3 prefix namely admin , vendor, and customer

### What happened

In local it is working fine , all the prefix are working fine.

i have moved my project linux server it is working fine 

once i have added SSL certificate , i have access my website like

**https://myproject.com/vendor** 

"It does not working " browser keeps loading, after some time it shows **This site can’t be reached took too long to respond.**

if i add  **https://myproject.com/vendor/**  it is working fine

### What you expected to happen

i dont want to add new trailing slash

then cakephp doesnot respond with prefix routing.

**Comment by othercorey** [comment]
Please show how you create the prefix.

**Comment by markstory** [comment]
Where is your application's webroot configured to be? It possible that `/vendor` is resolving to your application's vendor directory where composer installs dependencies. Make sure you've set your webserver's Document Root to the webroot directory in your application.

**Comment by kathiresanKRTB** [comment]
ok sure i will add to webroot directory

**Comment by kathiresanKRTB** [comment]
if we add to  Document Root to the webroot directory , then how can we add subdomain or another websites

**Comment by markstory** [comment]
@kathiresanKRTB With additional virtual host/server configurations in your webserver. If that is not possible due to hosting limitations you might need to explore other hosting solutions, or accept that /vendor does the wrong thing :smile:

**Comment by ADmad** [comment]
Try adding `Options -MultiViews` to your root `.htaccess` file.

**Comment by othercorey** [comment]
Closing as a configuration issue.
