### ISSUE TITLE
Binary UUID: Warning (2): pack(): Type H: illegal hex digit

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#14942]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x latest

### What you did

Sandbox implementation of binary UUIDs

### What happened

The logs are filling up with thousands of these (probably bot induced?):

> Warning (2): pack(): Type H: illegal hex digit m in [/var/www/dereuromark/sandbox4/vendor/cakephp/cakephp/src/Database/Type/BinaryUuidType.php, line 138]
Request URL: /sandbox/expose-examples/view/mUMPWUxCpaCi685A9fEwJZ

### What you expected to happen
That we don't run pack() on invalid input or we somehow don't throw this warning.

**Comment by markstory** [comment]
How would one go about triggering this warning?

**Comment by dereuromark** [comment]
You can literally use the URL in the log and it triggers the error live right now
So that also happens locally for the same test/URL
I guess it can also be boiled down to someone just inserting this "wrong UUID" into the type class manually (by simulating someone adding it as passed param).

**Comment by dereuromark** [comment]
Yeah, I am able to reproduce with


    /**
     * Test converting to database format fails
     *
     * @return void
     */
    public function testToDatabaseFail()
    {
        $value = 'mUMPWUxCpaCi685A9fEwJZ';
        $result = $this->type->toDatabase($value, $this->driver);
        dd($result);
    }

That part should probably also validate the incoming one before passing it on to the ORM layer - as anyone could habe submitted such an invalid URL in the request - inside /view/ID part.
