### ISSUE TITLE
Add $path parameter to Hash::filter()

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#14951]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: `3.9`, `4`

Add 3r parameter `$path` parameter to `Hash::filter()` to allow filter by deep values (or maybe create new function).
Currently it filters only by top level values:
`public static function filter(array $data, $callback = ['self', '_filter'])`

**Comment by markstory** [comment]
>  Currently it filters only by top level values:

Are you sure about that? There are tests covering that Hash::filter() recurses into all array values as well. How would the proposed path parameter work? Would only those paths be filtered?

**Comment by andrii-pukhalevych** [comment]
I just want to filter root array by some filed, specified in path without using array_filter + callback:
`Hash::filter($data, '{*}.is_enabled')`

**Comment by markstory** [comment]
That sounds like another method. Perhaps something like `Hash::filterBy()`?

**Comment by T0mats0** [comment]
How would a filterBy function be different than extract?
