### ISSUE TITLE
conversion of time-input to time-instance failing 

### ISSUE THREAD

**Issue by Tobse** [cakephp/cakephp#14957]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.3
* Platform and Target: NGINX, mySQL, php7.4.7 in a docker-container

### What you did
Using the form-helper, I created a time-field ([https://book.cakephp.org/4/en/views/helpers/form.html#creating-time-controls](https://book.cakephp.org/4/en/views/helpers/form.html#creating-time-controls)).
Validation setting: 
```
$validator
    ->time('departuretime')
    ->requirePresence('departuretime', 'create')
    ->notEmptyTime('departuretime');
```

### What happened
When entering a time-value without seconds (i.e. 18:45), no time-value is patched into the entity. No validation-error is beeing shown. When I leave the time-field empty, the validation-error shows up. In the request-data-Array the time-value is shown.

```
[
    'name' => 'Test',
'departuretime' => '18:00',
]
```

In the entity the departuretime is missing.

### What you expected to happen
I expected the time-value beeing converted into a time-instance and saved to the database. When I manually alter the time-value in a beforeMarshal()-function in my model (i.e. 18:45:00) or create a time instance everything works out fine.
```
public function beforeMarshal(EventInterface $event, ArrayObject $data, ArrayObject $options)
    {
        if ($data['departuretime']) {
             // creating time-instance
              $data['departuretime'] = new FrozenTime($data['departuretime']);
             // setting time-format manually
              $data['departuretime'] = '18:45:00';
        }
    }
```

**Comment by markstory** [comment]
Couldn't the format of `18:00` also be 18 minutes and 45 seconds? The ambiguity of this input format is why we don't support this format right now.

**Comment by othercorey** [comment]
I think Validation accepts time formats that marshal does not. There was a recent PR relaxing them further. I'm not sure if that is a good idea.

**Comment by Tobse** [comment]
> Couldn't the format of `18:00` also be 18 minutes and 45 seconds? The ambiguity of this input format is why we don't support this format right now.

Thank you for explaining your reasons. But I think the most common use-case for the <input type="time"> field is to capture hours and minutes without seconds. Unfortunately what comes from the browser is in HH:mm format. Chrome and Edge dismisses the seconds if you leave them empty. And using the attribute 'step="60"' to prevent the browser from showing the seconds even Firefox sends HH:mm.

I worked around the issue by generating a time-instance before marshal in my model. I used new FrozenTime() and this also excepts HH:mm to generate a correct time-instance.

Besides that I expected a validation error when passing a value in a wrong format. In my case the time-field is defined as "requirePresence" and "notEmptyTime" in my model. But the entity passes validation although the time-field is not set. Instead I get a database-error because no default-value is defined.

**Comment by markstory** [comment]
> Besides that I expected a validation error when passing a value in a wrong format. In my case the time-field is defined as "requirePresence" and "notEmptyTime" in my model. But the entity passes validation although the time-field is not set. Instead I get a database-error because no default-value is defined.

Yes the validation error not showing up is unexpected to me as well. Even if the value wasn't marshalled into a timevalue it would have been cast to `null` which should fail the `notEmpty` rule.

**Comment by markstory** [comment]
I took a look at this and tracked it down to a difference in what the validator and time mapper accept as values. The time validator method accepts `18:00` as a valid value so no validation errors are triggered. However, the value is then marshalled and cast to a null due to it being an ambiguous value as discussed earlier.

Changing the marshalling implementation is an option but I don't know how we do that in a backwards compatible way. If you only want to accept the format described above you could create a Type subclass in your application and map it to the model using [custom datatypes](https://book.cakephp.org/4/en/orm/database-basics.html#adding-custom-types)

**Comment by othercorey** [comment]
We did adjust DateTimeType to accept hh:mm format since that's the minimum precision that browsers were sending when using a large time step in the date time picker.

https://github.com/cakephp/cakephp/blob/c2b20709bbd3c3602421dcc17b5fdc97e0ca7ff5/src/Database/Type/DateTimeType.php#L62

https://github.com/cakephp/cakephp/pull/14544

**Comment by markstory** [comment]
@othercorey Right, but not in the TimeType. Given the precedent created in DateTimeType I'm ok with changing TimeType to accept H:i

**Comment by markstory** [comment]
Closing this as H:i format will be marshalable in 4.2.0 and validation has been aligned with that format as well.
