### ISSUE TITLE
Theme assets not loaded - missing dispatcher?

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#14956]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.3
* Platform and Target: Apache, macOS

### What you did
I created theme in plugins folder and I want to load theme asset (javascript).

I have it in folders:
```
/plugins/Theme/templates/Feeds/show.php
/plugins/Theme/webroot/js/feed.js
```
I try to load the script by including it in the view show.php:

`echo $this->Html->script('feed');`
It correctly generates path:

`/theme/js/feed.js`

### What happened
But the framework doesn't interpret the path correctly, it says that I am missing controller (Theme).

I checked documentation again and it says that "Whilst in development, requests for theme assets will be handled by Cake\Routing\Dispatcher"

Btw. there is no Cake\Routing\Dispatcher class in /vendor/cakephp/cakephp/src/Routing/.

### What you expected to happen
Script to be loaded.

**Comment by ADmad** [comment]
Do you have the `AssetMiddleware` loaded? https://github.com/cakephp/app/blob/fa16aa6e084db7a51a3665ad8d7a9c28bcd06fe9/src/Application.php#L75

**Comment by markstory** [comment]
> I checked documentation again and it says that "Whilst in development, requests for theme assets will be handled by Cake\Routing\Dispatcher"

I've fixed the docs up. They were referencing the wrong class.

**Comment by nitramxx** [comment]
> Do you have the `AssetMiddleware` loaded? https://github.com/cakephp/app/blob/fa16aa6e084db7a51a3665ad8d7a9c28bcd06fe9/src/Application.php#L75

Yes, it is loaded.

**Comment by nitramxx** [comment]
I was trying to debug the path, it seems that AssetMiddlware checks if plugin is loaded before composing path to the asset.

_getAssetFile(), line 127:
```
     $plugin = implode('/', $pluginPart);
            if (Plugin::isLoaded($plugin)) {
```

I enhanced the theme to be very lightweight plugin, added it to composer.json (this I found necessary for plugin to even work, also seems redundant) and loaded it in Application.php (would be cool to load plugin on the fly in the app). When I did that, the asset get's loaded. 

If this is intended behavior, it's counterintuitive. I don't need to load theme as a plugin to be able to use its templates. Assets are enhancing templates. 

Also documentation says:

> If your theme also acts as a plugin, don’t forget to ensure it is loaded in your application’s bootstrap method.

This implies that if I don't want it to act as a plugin, I don't need to load it.

**Comment by markstory** [comment]
@nitramxx Themes do need to be proper plugins. You shouldn't need to create a Plugin class, but you will need to `loadPlugin()` the theme. I can update the documentation to make that more clear.

**Comment by nitramxx** [comment]
OK, I see. As I was saying before, it's counterintuitive. Even in the plugins section the documentation says:

> If you just want to use helpers, behaviors or components from a plugin you do not need to load a plugin.

The templates do not require theme to be loaded as plugin. The framework finds its way. 
Similar to that, view assets are static and I would not expect the need to load it.

So as a suggestion, I would vote for AssetMiddleware to be able to server assets without plugin being loaded. The change is simple, just removing the condition. I can't think of any risk.

**Comment by ADmad** [comment]
>The templates do not require theme to be loaded as plugin

The docs mentions helpers, behaviors, components which are classes (and their loading is handled by composer's autoloader). Templates are just php files and the theme plugin needs to be loaded for framework to be able to located them.

> I would vote for AssetMiddleware to be able to server assets without plugin being loaded.

As stated above themes aren't just assets files but can include templates files too which require it's plugin to be loaded.

As the docs state the `AssetMiddleware` is just to make development easier. Ideally your theme assets should be copied or symlinked under "webroot".

Lastly you can just use your own modified `AssetMiddleware` instead of the one provided in core, if you don't want to bother loading theme plugins.

**Comment by nitramxx** [comment]
> Templates are just php files and the theme plugin needs to be loaded for framework to be able to locate them.

It doesn't. It's enough to call $this->viewBuilder()->setTheme($theme) in controller.

**Comment by ADmad** [comment]
It's enough because the plugin gets autoloaded internally, since you explicitly asked for that theme to be used. `AssetMiddleware` deals with request path fragments which may or may not be for theme assets and hence doesn't autoload plugins.
