### ISSUE TITLE
Unit Testing: Tables not truncated when fixture is setup

### ISSUE THREAD

**Issue by jonmc1** [cakephp/cakephp#14958]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.3
* Platform and Target: Apache, MariaDB

### What you did
Unit testing using fixtures that don't have $fields or $import set, so it uses existing database table structure. And data is inserted through the fixtures

### What happened
The first run of the tests works fine but if you run it again, you get 'Unable to insert fixture "" in "" test case:' errors because of duplicate entries. The tables are not being truncated when the fixture is loaded.

### What you expected to happen
Multiple test runs in a row without having to manually truncate the database tables. It was working correctly in version 4.0

**Comment by jonmc1** [comment]
TestCase:
```
<?php
namespace App\Test\TestCase\Controller;

use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

class ExampleControllerTest extends TestCase {
	use IntegrationTestTrait;

	/**
	 * Fixtures
	 *
	 * @var array
	 */
	public $fixtures = [
		'app.Examples',
		...
	];

	public function setUp(): void {
		parent::setUp();

		$this->configRequest(['environment' => ['HTTPS' => 'on']]);
		$this->enableRetainFlashMessages();
		$this->enableCsrfToken();
		$this->enableSecurityToken();
	}

	/**
	 * Test index() method
	 *
	 * @return void
	 */
	public function testIndex() {
		...
	}
}
```

Fixture:
```
<?php
namespace App\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

class ExamplesFixture extends TestFixture {
	/**
	 * Records
	 *
	 * @var array
	 */
	public $records = [
		[
			'id' => 1,
			'name' => 'Test'
		],
		...
	];

}
```

**Comment by markstory** [comment]
I wasn't able to reproduce this problem with MySQL 5.7.31. Perhaps is is limited to MariaDB? We don't do any formal testing on MariaDB though.
