### ISSUE TITLE
phpunit warnings about deprecated xml config

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#14968]
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

**Comment by ADmad** [comment]
We might not be able to support both phpunit 8 and 9 if we migrate.

**Comment by othercorey** [comment]
Looks like I'm still using php8 locally, so that's with phpunit 9.

**Comment by othercorey** [comment]
I think the only issue will be when phpunit 10 is required for 8.1 and removes support for deprecation. phpunit might even randomly remove it much earlier.
