### ISSUE TITLE
hasMany association fails to handle callable in condition

### ISSUE THREAD

**Issue by mixable** [cakephp/cakephp#14961]
This is a:

* [x] bug

* CakePHP Version: 3.8.13 and 3.9.2
* Platform and Target: Apache 2.4, MySQL 5.5.5, PHP Version 7.2.31 and 7.4.6.

### What you did
I use a hasMany association in my Articles table. The association uses a callable as condition:

    $this->hasMany('Tags')
        ->setForeignKey('article_id')
        ->setDependent(true)
        ->setSaveStrategy('replace')
        ->setConditions(function () {
            return ['locale' => $this->getLocale()];
         });

An existing article was edited and the Article entity (containing associated Tag entities) was saved using:

    $article = $this->Articles->patchEntity($article, $this->getRequest()->getData(), [
        'associated' => ['Tags'],
    ]);
    $this->Articles->save($article);

### What happened
The given condition is only recognized for find(), but not for save(). When calling save, **all** associated datasets are deleted and the following error is thrown:

> Warning (2): array_merge(): Argument #2 is not an array [CORE/src/ORM/Association/HasMany.php, line 538]

### What you expected to happen
Because of the replace save strategy, it is expected that all associated datasets (Tags) will be deleted. **But only those, that match the given conditions.** After this, the new Tag entities should be inserted.

In the [api docs](https://api.cakephp.org/3.8/class-Cake.ORM.Association.HasMany.html#_setConditions), it is shown that the method 'setConditions' accepts an `array` or a `callable`. But this does not work for a `callable`.

A simple test shows, that the same relation with a static `array` works as expected:

    $this->hasMany('Tags')
        ->setForeignKey('article_id')
        ->setDependent(true)
        ->setSaveStrategy('replace')
        ->setConditions(['locale' => 'en']);

This will only handle datasets with `locale = 'en'`, even if there are other datasets with the same `foreign_key` in the table.

**Comment by markstory** [comment]
Pull request open now.
