### ISSUE TITLE
Argument 2 passed to Cake\Error\ErrorHandler::_displayError() must be of the type bool, int given, called in

### ISSUE THREAD

**Issue by mcbblancos** [cakephp/cakephp#14974]
This is a :

* [x] bug

* CakePHP Version: 4.1.4.
* Debian 10 - php 7.3

### What you did
On dev; when an error is occured, I have : Argument 2 passed to Cake\Error\ErrorHandler::_displayError() must be of the type bool, int given, called in
![error](https://user-images.githubusercontent.com/10488643/92942495-dae21780-f451-11ea-8d2e-a3ecd148cb9e.png)

### What happened
Argument 2 passed to Cake\Error\ErrorHandler::_displayError() must be of the type bool, int given, called in

### What you expected to happen
Bugfix

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by garas** [comment]
What is value of `Configure::read('debug')`?

**Comment by mcbblancos** [comment]
(int) 2 

Thanks !

**Comment by ADmad** [comment]
Since Cake 3 the value of `debug` config can only be a boolean.

**Comment by mcbblancos** [comment]
Ark thanks, I set this now ! Very sorry !
