### ISSUE TITLE
Hash::reduce

### ISSUE THREAD

**Issue by nachitox** [cakephp/cakephp#14978]
https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L920
https://www.php.net/manual/en/function.array-reduce.php

If initial is not set, the function returns NULL, so Hash::reduce() will always return NULL, right?

**Comment by markstory** [comment]
> If initial is not set, the function returns NULL, so Hash::reduce() will always return NULL, right?

No. The first value that is return overwrites the initial value.
