### ISSUE TITLE
Failure to setup second Memcached instance on another port

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#14985]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: Ubuntu, MySQL, Apache.

### What you did
1. Started another memcached instance on port 11213 by running `memcached -p 11213 -d` in the console.
2. Configured `'_cake_core_'` cache to use that instance by using `'servers' => ['localhost:11213'],`

### What happened
`'_cake_core_'` used the default memcached on port 11211 instead 11213.

The line [157](https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/MemcachedEngine.php#L157) `if (!$this->_Memcached->addServers($servers)) {` seems to be never executed because `$this->_Memcached->getServerList()` on the line [148](https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/MemcachedEngine.php#L148) in MemcachedEngine always  returns `true`.

### What you expected to happen
I would expect `'_cake_core_'`  to use 'localhost:11213' memcached.

**Comment by markstory** [comment]
Closing as there is a pull request open to fix this.
