### ISSUE TITLE
Wrong MySQL Query with multiple NOT conditions

### ISSUE THREAD

**Issue by nook24** [cakephp/cakephp#14981]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.4
* Platform and Target: MySQL Server: 5.7.31-0ubuntu0.18.04.1, PHP 7.2.24-0ubuntu0.18.04.6

### What you did
I tried to apply multiple NOT conditions to an query
```php
        /** @var TestTable $TestTable */
        $TestTable = TableRegistry::getTableLocator()->get('Test');
        $query = $TestTable->find()
            ->where([
                'NOT' => [
                    'service_id IN' => [600,701,702],
                    'host_id' => 60
                ]
            ]);

        die((string)$query);
```

### What happened
The ORM generates an wrong syntax for MySQL. It looks like that MySQL ignores the whole WHERE condition

Generated Query:
```sql
SELECT
  `Test`.`id` AS `Test__id`,
  `Test`.`host_id` AS `Test__host_id`,
  `Test`.`service_id` AS `Test__service_id`
FROM
  `test` `Test`
WHERE
  NOT (
    (
      `service_id` in (600,701,702)
      AND `host_id` = 60
    )
  )
```

Query result:
**Test\_\_id**|**Test\_\_host\_id**|**Test\_\_service\_id**
:-----:|:-----:|:-----:
6|70|702
5|70|701
4|70|700
3|60|602
2|60|601

### What you expected to happen
The MySQL Result should be only one line.

Working Query:
```SQL
SELECT
  `Test`.`id` AS `Test__id`,
  `Test`.`host_id` AS `Test__host_id`,
  `Test`.`service_id` AS `Test__service_id`
FROM
  `test` `Test`
WHERE
  NOT (
      `service_id` in (600,701,702)
  )
  AND
  NOT (
      `host_id` = 60
  )
```

Expected query result:
**Test\_\_id**|**Test\_\_host\_id**|**Test\_\_service\_id**
:-----:|:-----:|:-----:
4|70|700

My Test data:

```SQL
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `host_id` int(11) DEFAULT NULL,
  `service_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

INSERT INTO `test` (`id`, `host_id`, `service_id`)
VALUES
	(1, 60, 600),
	(2, 60, 601),
	(3, 60, 602),
	(4, 70, 700),
	(5, 70, 701),
	(6, 70, 702);
```

```
cake bake model Test
```

As long as I only have one NOT condition the query is working fine like so:
```php
        $query = $TestTable->find()
            ->where([
                'NOT' => [
                    'service_id IN' => [600,701,702],
                ]
            ]);
```

**Test\_\_id**|**Test\_\_host\_id**|**Test\_\_service\_id**
:-----:|:-----:|:-----:
2|60|601
3|60|602
4|70|700

This code generates the right query, but it is not dynamically. Normally my conditions are not hardcoded ^^
```php
        $query = $TestTable->find()
            ->where(function(QueryExpression $exp){
                $and = $exp
                    ->notEq('host_id', 60)
                    ->notIn('service_id', [600,701,702]);
                return $and;
            });
```

This is my $where array if it helps:
```
^ array:1 [▼
  "NOT" => array:2 [▼
    "Services.id IN" => array:6 [▼
      0 => "600"
      1 => "701"
      2 => "702"
    ]
    "Services.host_id" => "60"
  ]
]
```

**Comment by nook24** [comment]
Alex in the Slack channel came up with this workaround:

```php
$TestTable = TableRegistry::getTableLocator()->get('Test');
$query = $TestTable->find()
    ->where([
        'NOT' => ['service_id IN' => [600,701,702]]
    ])
    ->where([
        'NOT' => ['host_id' => 60]
    ]);
```
Due to this is working as expected I think there is a bug in the ORM as soon as you pass more than 1 element as NOT condition.

Generated Query:
```sql
SELECT
  `Test`.`id` AS `Test__id`,
  `Test`.`host_id` AS `Test__host_id`,
  `Test`.`service_id` AS `Test__service_id`
FROM
  `test` `Test`
WHERE
  (
    NOT (
      `service_id` in (600,701,702)
    )
    AND NOT (`host_id` = 60)
  )
```

Result:
**Test\_\_id**|**Test\_\_host\_id**|**Test\_\_service\_id**
:-----:|:-----:|:-----:
4|70|700

**Comment by dereuromark** [comment]
That is not a workaround, that is expected behavior - as is yours.
The nesting makes the difference in how the query gets generated.

I don't think this ticket is valid.

**Comment by rchavik** [comment]
What if you split into 2 `where':

```
            ->​where​([
                ​'NOT'​ => [
                    ​'service_id IN'​ => [​600​,​701​,​702​],
                ])
            ->where([
                ​'NOT'​ => [
                     ​'host_id'​ => ​60​
                ]
            ]);
```

**Comment by rchavik** [comment]
> What if you split into 2 `where`:
> 
> ```
>             ->​where​([
>                 ​'NOT'​ => [
>                     ​'service_id IN'​ => [​600​,​701​,​702​],
>                 ])
>             ->where([
>                 ​'NOT'​ => [
>                      ​'host_id'​ => ​60​
>                 ]
>             ]);
> ```

Nvm. Just saw your msg

**Comment by nook24** [comment]
What should i do now?
Should i go with the 2 `where` workaround or will this be removed with 4.1.5? I also can not find any documentation about the `->where(['NOT' => []])` syntax. ()


I also do not understand this unit test:
https://github.com/cakephp/cakephp/blob/740f5a1e187e4e557a76c197b2efe7a18bb3c61d/tests/TestCase/Database/QueryTest.php#L1659-L1674

It generates this SQL statement:
```sql
SELECT
  `Test`.`id` AS `Test__id`,
  `Test`.`host_id` AS `Test__host_id`,
  `Test`.`service_id` AS `Test__service_id`
FROM
  `test` `Test`
WHERE
  NOT (
    (
      (
        `id` = 1
        OR `id` > 2
      )
      AND `id` = 3
    )
  )
```

It return 1, 2 and 3 (and all other records in the table) in my setup (with the test table posted above) 🤷‍♂️
**Test\_\_id**|**Test\_\_host\_id**|**Test\_\_service\_id**
:-----:|:-----:|:-----:
1|60|600
2|60|601
3|60|602
4|70|700
5|70|701
6|70|702

**Comment by nook24** [comment]
I found the answer. Conditions with `NOT` and `AND` or `OR` are a bit confusing. At least for me.

My mistake was based on the assumption that two or more array values get chained to an AND condition. Like it would happen with a _normal_ query
```php
$query->where([
    'host_id' => 60,
    'service_id' => 70
]);
```
gets to:
```sql
WHERE host_id=60 AND service_id=70
```
which is perfectly fine.

How ever, when using the `NOT` operator, CakePHP will still use `AND`, but the AND will now act as an `OR` operator which is the confusing part.
```php
$query->where([
    'NOT' => [
        'host_id' => 60,
        'service_id' => 70
    ]
]);
```

gets to:
```sql
WHERE NOT ( host_id=60 AND service_id=70)
```
this is equivalent to
```SQL
WHERE NOT host_id=60 OR NOT service_id=70
```

With this knowledge in mind, we need to use the `OR` operator, which will work as an `AND` in the final query:
```php
$query->where([
        'NOT' => [
            'OR' => [
                'host_id'       => 60
                'service_id' => 70,
            ]
        ]
    ]);
```
gets to:
```sql
WHERE NOT ( host_id=60 OR service_id=70)
```
this is equivalent to
```SQL
WHERE NOT host_id=60 AND NOT service_id=70
```

Probably not a bug in the ORM it just confused me AF

---

All this is described in detail here: https://www.peachpit.com/articles/article.aspx?p=1276352&seqNum=6

**Comment by ndm2** [comment]
Generally you can also nest conditions If you want to pass multiple conditions using the same operator:

```php
->where([
    [
        'NOT' => ['service_id IN' => [600, 701, 702]]
    ],
    [
        'NOT' => ['host_id' => 60]
    ],
])
```

**Comment by garas** [comment]
Query can be expressed without nesting too

```php
->where([
      'service_id NOT IN' => [600,701,702],
      'host_id !=' => 60,
]);
```
