### ISSUE TITLE
TreeBehavior randomly sets an invalid value on lft/rght indices of nodes during unrelated operations

### ISSUE THREAD

**Issue by andres-ml** [cakephp/cakephp#14983]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12
* MySQL: 5.6

Hello,

We have a moderately big tree in production (70k entries) which uses `TreeBehavior`. We've been experiencing a problem with it for quite some time now (1-2 years). Since it happened rarely and I wasn't able to reproduce it myself, I didn't want to open an issue here, but lately it's happening quite often (about 1/week) and I still haven't been able to find out why.

The problem is that, at some point, the lft/rght indices of some nodes in the tree become incorrect. With incorrect, I mean that either a group's `lft` index is bigger than its `rght` index, or that for a group g and a parent p, `g.lft < p.lft` or `g.rght > p.rght`. What's worse is that such nodes don't seem to hold any particular connection with the group that is being handled at the time of the "index corruption" happening.

As an example, I'll provide what I can of the context of the last time we encountered this error:

This is the code that reports errors (pretty straightforward):
```php
public function afterSave(Event $event, EntityInterface $group, ArrayObject $options)
{
        $corrupted = $this->find()->where(['lft > rght'])->toArray();
        if ($corrupted) {
            // format the data and notify
        }
}
```

This is a simplified version of the code that was running (which builds a tree based on a csv):
```php
private function importGroups($groups) {
        $this->loadModel('Groups');
        $user = $this->Auth->user();
        foreach ($groups as $i => $row) {
            // throw error if group already exists
            if ($row[1]) {
                $group = $this->Groups->findByCodeAndClientId($row[1], $user['client_id'])->first();
                if ($group !== null) {
                    throw new \Exception("Group $row[1] already exists");
                }
            }
            
            $parent = $this->Groups->findByCodeAndClientId($row[2], $user['client_id'])->first();
            $this->Groups->create($user['client_id'], $row[0], $parent ? $parent->id : null, $row[1]);
        }
}
```
And `GroupsTable::create` (GroupsTable has no other relevant beforeSave,etc. hooks):
```php
    public function create($client_id, $name, $parent_id, $code = null)
    {
        if ($parent_id === null) {
            $parent = $this->getRoot(client_id);
        }
        else {
            $parent = $this->findByIdAndClientId($parent_id, client_id)->first();
            if ($parent === null) {
                throw new \Exception("Invalid parent id");
            }
        }
        
        $group = $this->newEntity();
        $group->name = $name;
        $group->client_id = $client_id;
        $group->parent_id = $parent->id;
        $group->code = $code;
        
        $this->save($group);
        
        return $group;
    }
```

The error happened during the import process (at a seemingly random point):
![rght-1](https://user-images.githubusercontent.com/21081145/93744455-26cf5200-fbf2-11ea-9689-9c4b56df84a5.png)

These rows are sorted by modification date, and as you can see the only operation currently happening is the import process. It is at the moment of creating the group I highlighted with the red circle that the error is reported for the first time (check the rght indices under `corrupted`):

```json
{
    "current": {
        "id": 68026,
        "parent_id": 68023,
        "lft": 134399,
        "rght": 134400,
        "modified": "2020-09-20T20:05:09+0000"
    },
    "corrupted": [
        {
            "group": {
                "id": 61238,
                "parent_id": null,
                "lft": 135145,
                "rght": 7183, <---------
                "modified": "2020-09-18T10:41:02+0000"
            },
        },
        {
            "group": {
                "id": 62396,
                "parent_id": 61238,
                "lft": 135146,
                "rght": 7180, <---------
                "modified": "2020-09-18T15:04:10+0000"
            },
        }
    ],
    "requestUrl": "\/admin\/tools\/import_groups"
}
```
From this point on, each new insertion resulted in a new notification about corrupted data sent to me. This is the final set of nodes that somehow ended up with corrupted indices:

![rght-2](https://user-images.githubusercontent.com/21081145/93745042-21bed280-fbf3-11ea-9410-ca811ccaa36b.png)

Sorry I can't provide any more useful information but as I said, I haven't been able to reproduce it. My attempts of inserting thousands of nodes at the same time in my local environment have been unsuccessful so far. Before I decide whether I want to spend more time trying to reproduce it, or split the tree into smaller chunks, or delve deeper into `TreeBehavior`'s code, I figured I could ask for some advice around here.

Thanks for your time,

**Comment by ADmad** [comment]
The TreeBehavior uses MPTT which is quite write heavy as the left/right values for multiple records need to be updated when a record is added/removed and hence not suitable for very large numbers of records like you have.

It's like that a new request starts updating the values before a previous request has finished updating. I don't think there's any easy fix for your problem except for using the `recover()` method of the behaviour to fix the left/right values whenever the issue occurs.

**Comment by andres-ml** [comment]
Yeah, `recover()` is what we've been using to fix it so far. What I don't understand is how there could be a conflict when apparently there was no concurrency at that point (the import process is sequential, and the timestamps show no other group being modified at that moment)

**Comment by ADmad** [comment]
I too have have similar issue with no concurrency.

**Comment by adamroyle** [comment]
I experience this problem semi-frequently too. Not sure what causes the problem but it is quite frustrating.

**Comment by andres-ml** [comment]
By the way, I ended up circumventing this problem by splitting my tree into smaller chunks.

Since I wanted to split it dynamically (by the value of one of my columns), I had to tweak `TreeBehavior.php` so that the `scope` config took an extra argument, which is the entity in the context of the operation, such as this:

```php
$this->addBehavior('Tree', [
    'scope' => function($query, $entity) {
        if ($entity) {
            $query->where($entity->extract(['client_id']));
        }
        return $query;
    }
]);
```
There's a couple of instances where there is no context entity (`findTreeList`, `getNode`); for the rest, I simply added it to the `_scope` function calls. I also tweaked the `recover` function(s) so that the context entity includes all fields and not just the primary key, and to add an optional base query argument to recover specific subtrees separately:

```php
// recover just one subtree
$this->getBehavior('Tree')->recover($this->find()->where(['client_id' => 123]));

// rebuild each client's subtree separately
$this->find()
    ->select(['client_id'])
    ->group(['client_id'])
    ->disableHydration()
    ->all()
    ->each(function($group) {
        $this->getBehavior('Tree')->recover($this->find()->where(['client_id' => $group['client_id']]));
    });
```

Here's a diff with the changes: https://gist.github.com/andres-ml/6700ce574dc782666ed194a05a64a528

I've had it running for a few months in production and I haven't come across any issues, nor have I ran into any other corrupted indices case.

**Comment by othercorey** [comment]
I'm not sure what we can do without a way to reproduce it.

**Comment by othercorey** [comment]
@ADmad Should we close this with 3.x support ending or move to another milestone?

**Comment by ADmad** [comment]
Guess we can move it to 4.x.

**Comment by nook24** [comment]
Sorry for opening up this old case again. I'm facing a similar issue and while searching for possible root causes, I found this issue. I'm using CakePHP 4.4.14.

@ADmad said
> It's likely that a new request starts updating the values before a previous request has finished updating and you won't be able to reproduce it without concurrent requests.

This sounds plausible. In my case it is also total random which node is affected. I use a single tree (~5k nodes) and end up with all sort of random issues like `lft` > `rght` or even multiple nodes with the same values for `lft` and `rght`.

Concurrency could be the issue in my case as the Frontend sends multiple API requests to the backend. I'm using php-fpm so multiple php processes run at the same time.

Did anyone came up with a good locking/mutex solution? In my case the default PHP file session is used, which should act as some sort of lock as long as nothing calls `session_write_close()`.

My code looks something like this:
```php
<?php
    public function delete($id = null) {
        $ContainersTable = TableRegistry::getTableLocator()->get('Containers');
        $container = $ContainersTable->get($id, [
            'contain' => [
                'Servicetemplategroups'
            ]
        ]);

        $ContainersTable->delete($container)
    }
```
