### ISSUE TITLE
AuthComponent: Handle Ajax request in _unauthorized()  like _unauthenticated()

### ISSUE THREAD

**Issue by Agacor** [cakephp/cakephp#14994]
* [x] bug
* [x] enhancement
* CakePHP Version: 4.x

### What you did
When I perform an ajax request to an action (IE: /articles/autocomplete), if the user is not authenticated I get a response with error 403 (as expected), but if the user is authenticated but not authorized (return false in the AppController isAuthorized() method), the AuthComponent set a Flash message and a redirect instead of return a '\Cake\Http\Response|null' as Expected in the method description.

### What happened
Cannot check response status in ajax callback, and when go to another action the Flash Message is shown.

### Solution
Compare _unauthenticated() and _unauthorized() methods.
It seems that _unauthorized() method could check the request like _unauthenticated() to return a 403 status code Response.

Line 424:

if ($controller->getRequest()->is('ajax')) {
    return $controller->getResponse()->withStatus(403);
}

That works for me.

**Comment by ADmad** [comment]
AuthComponent is deprecated so making any changes to it wouldn't make sense.

**Comment by Agacor** [comment]
I am trying to help with the code.
AuthComponent does not work as expected in the method description. It will be removed in CakePHP 5. 
Many people (like me) that is checking CakePHP4 to migrate their CakePHP3 projects will find similar problems with or withouth deprecated components, helpers or wathever. It makes sense to fix them when they are reported and a solution proposed by the community.

**Comment by ADmad** [comment]
You can set the `unauthorizedRedirect` config to `false` for ajax requests so that a `ForbiddenException` is thrown which sets `403` status code. So what you want is already achievable.
