### ISSUE TITLE
Controller/Component/AuthComponent.php declare(strict_types=1);

### ISSUE THREAD

**Issue by Agacor** [cakephp/cakephp#14990]
* [x] bug
* 4.x (master)

### What you did
// Instance reflection class of a controller (with AuthComponent)

$rcController = new \ReflectionClass($controllerClassName);
$obController = $rcController->newInstance();
$obController->startupProcess();

### What happened
Controller/Component/AuthComponent.php lines 271 and 330 TypeError.

Argument 1 passed to Cake\Controller\Controller::isAction() must be of the type string, null given, called in C:\wamp64\www\cakephp4\plugins\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php on line 271

### Solution
Replace line 270
$action = $controller->getRequest()->getParam('action');
with 
$action = $controller->getRequest()->getParam('action', '');

Replace line 330
$action = strtolower($controller->getRequest()->getParam('action'));
with
$action = strtolower($controller->getRequest()->getParam('action', ''));

**Comment by markstory** [comment]
Why does your controller not have an action parameter? That generally should not be happening.

**Comment by Agacor** [comment]
Hey Mark, first of all thanks for the fix, but there is a problem, im trying the new release 4.1.5 and there is an 'error'.

In the first fix:
$action = $controller->getRequest()->getParam('action', '');
if (!$controller->isAction($action)) {
    return null;   // $action is null ('') then return NULL, there is no action '' in the controller [OK]
}

When the action was null, the function returns null (that's correct, there is no action null/'' in the controller)

But in the second fix
https://github.com/cakephp/cakephp/commit/8917b09ae12af6056df7f417b59a2ccfc9bd778c

$action = $controller->getRequest()->getParam('action');
if ($action !== null && !$controller->isAction($action)) {
    return null; //  $action is null an then there is no check for the action in the controller [KO].
}

when the action is null there is no check for the action, so there is no return null wich is the expected result.
The first approach was correct, in the second the correct handling for the null value the would be:

$action = $controller->getRequest()->getParam('action');
if (is_null($action) || !$controller->isAction($action)) {
    return null; //  $action is null an then the return is null (that return null as intended where no action is in the controller and avoids the execution of the next code in the function).
}

Thanks,

PD: The reason for not having an action parameter in the controller is that i am not handling a request in it. I am reading each ../src/Controller/ folder (App and plugins) , to map the Acces Control Objects (ACOs) in a function called 
getFolderACOs($plugin = null, $path = null){}
I need to startup the controller for initialize AuthComponent in each controller to check if the action is already allowed
...
// ReflectionController
$obController = $rcController->newInstance(); 
$obController->startupProcess();

$allowed_actions = array_merge(
$obController->Auth->allowedActions, 
    ['initialize', 'beforeFilter', 'beforeRender', 'beforeRedirect', 'afterFilter', 'isAuthorized']
);
...

**Comment by dereuromark** [comment]
This might be a regression, the check probably should be inverted.
