### ISSUE TITLE
Collection iterator is invalidated by calling count or debugging

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#14999]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.6

This code:
```
$x = collection([1, 2, 3, 4, 5])->reject(function ($i) { return $i > 3; });
foreach ($x as $i) {
	$x->count();
	pr($i);
}
```
generates just "1" as the output. Removing the `count()` call, it will generate "1 2 3". Stepping through the same code (with the `count` call removed) in a debugger also will only output "1". This is presumably all because `count` invalidates the iterator, and the debugger indirectly calls `count` through `__debugInfo()`? Is there any way to resolve this universally, or do I just make sure that I don't call count inside my loops, and remain aware that this can be a problem when debugging?

**Comment by othercorey** [comment]
This is probably because `CollectionTrait::count()` uses `iterator_count()` which modifies the position of the iterator. The iterator can be $this which cause the problem.

**Comment by markstory** [comment]
> Is there any way to resolve this universally, or do I just make sure that I don't call count inside my loops, and remain aware that this can be a problem when debugging?

 I don't think there is a good way around this problem as collections can wrap arbitrary iterators and count needs to consume results.

**Comment by Zuluru** [comment]
That was sort of my expectation. I never like finding those pieces of rope long enough to hang myself, but understand that they can't all be eliminated.

**Comment by othercorey** [comment]
Does the debugger evaluate debug info for the collection when inside any function that has a collection instance?

That might be much more common than documenting that count() invalidates iterating over the collection in a loop. Perhaps it's not best to evaluate that in `__debugInfo()`

**Comment by Zuluru** [comment]
I believe so, yes. I'm using PHPStorm with xdebug, I can't vouch for any other combination. It seems to re-evaluate everything every time it breaks execution, including on every line as you step through. It would decrease (though not entirely eliminate) the impact of this if it were to cache the count, but I expect that raises issues in terms of trying to invalidate that cached value when the collection itself changes, and it only fixes it in scenarios where it is counted and cached before the debugger breaks inside a loop, so probably not worth the bother of implementing that sort of a solution.

**Comment by othercorey** [comment]
A warning for this already exists, but I moved it to hopefully be clearer.
