### ISSUE TITLE
Type Error in php8 str_replace(): Argument #2 ($replace) must be of type array|string, int given

### ISSUE THREAD

**Issue by Badman12** [cakephp/cakephp#15020]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.4.
* Platform and Target: php:8.0-rc-apache image

### What you did
I try to run cakephp application on new php8-apache docker image

### What happened
I got error str_replace(): Argument #2 ($replace) must be of type array|string, int given
In  ROOT/vendor/cakephp/cakephp/src/Utility/Text.php, line 240
![image](https://user-images.githubusercontent.com/20132986/95015517-ff4aa180-0655-11eb-8f50-01602262bbdb.png)

### What you expected to happen
It was working on image php7.4 perfectly

**Comment by dereuromark** [comment]
PR open.

**Comment by dereuromark** [comment]
I clarified the version map in https://github.com/cakephp/cakephp/wiki#version-map

**Comment by sselvanathan** [comment]
Glad to see that im not the only one, who run into this bug.
