### ISSUE TITLE
__() translation throws exception when same placeholder is used multiple times

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#15024]
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.2
* Platform and Target: LAMP (PHP Version 7.4.3), ICU version 66.1.

### What you did
Used the same substitution as normal substitution and and value for plural expression:
`__('{companies} {companies,plural,=1{virksomhed} other{virksomheder}}', ['companies'=>1]);`

### What happened
`Aura\Intl\Exception\CannotFormat` was thrown with message `Inconsistent types declared for an argument: U_ARGUMENT_TYPE_MISMATCH`

### What you expected to happen
No exception happens

When I use one more substitution, it works:
`__('{companies} {companies2,plural,=1{virksomhed} other{virksomheder}}', ['companies'=>1, 'companies2'=>1]);`

**Comment by andrii-pukhalevych** [comment]
I know that its possible to use `#` but its not always applicable

**Comment by garas** [comment]
It is problem with PHP/ICU. There is nothing to do from CakePHP side.

See https://3v4l.org/OEuOb

Use `#` or submit bug to PHP/ICU if you think it is bug.

It was similar issue with same error code at https://github.com/cakephp/cakephp/issues/12592, it was PHP fault then. I might be here too.
