### ISSUE TITLE
Strong typed action (route) arguments

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15023]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1.4
* Platform and Target: nginx, php 7.4, linux

### What you did
```php
// routes.php
    $routes->connect('/organizations/{organization_id}/edit', ['controller' => 'Organizations', 'action' => 'addModify'], ['organization_id' => '\d+'])->setPass(['organization_id'])->setMethods(['GET', 'POST']);

// OrganizationsController action method
    public function addModify(int $organization_id = null)
    {
    }
```

### What happened
```
[TypeError] Argument 1 passed to App\Controller\OrganizationsController::addModify() must be of the type int, string given, called in /var/www/html/paro2/vendor/cakephp/cakephp/src/Controller/Controller.php on line 529 in /var/www/html/paro2/src/Controller/OrganizationsController.php on line 47
Oct 05 17:23:45 paro2 [461576]: error: Stack Trace:
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Controller/Controller.php:529
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:79
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/BaseApplication.php:251
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:77
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php:156
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:159
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php:124
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:166
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:121
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:73
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Runner.php:58
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/vendor/cakephp/cakephp/src/Http/Server.php:90
Oct 05 17:23:45 paro2 [461576]: error: - /var/www/html/paro2/webroot/index.php:40
```

### What you expected to happen
I'd expect the argument to be casted to expected type, if possible and if passes the regex validation defined in routes.php, otherwise some kind of error, such as 400, 421 or some 5xx code

I currently work-around this by overriding `AppController::invokeAction` like this, which supports strong-typing arguments or `string` and `int` types, possibly nullable
 
```php
<?php
declare(strict_types=1);

namespace App\Controller;

use ArrayAccess;
use Authentication\Controller\Component\AuthenticationComponent;
use Cake\Controller\Controller;
use Closure;
use Exception;
use ReflectionException;
use ReflectionFunction;

class AppController extends Controller
{
    /**
     * Allows action methods to have strong-typed arguments
     *
     * @param Closure $action
     * @param array $args
     * @throws ReflectionException
     */
    public function invokeAction(Closure $action, array $args): void
    {
        $reflection = new ReflectionFunction($action);
        $passedArgs = [];
        $counter = 0;
        foreach ($reflection->getParameters() as $reflectionParameter) {
            if (!$reflectionParameter->hasType()) {
                $passedArgs[] = $args[$counter];
            } else {
                switch ($reflectionParameter->getType()->getName()) {
                    default:
                        dd('Unknown argument type', __METHOD__, $reflectionParameter->getType()->getName());
                    case "int":
                        if (!isset($args[$counter]) && $reflectionParameter->allowsNull()) {
                            $passedArgs[] = null;
                        } else {
                            $passedArgs[] = isset($args[$counter]) ? intval($args[$counter]) : 0;
                        }
                        break;
                    case "string":
                        if (!isset($args[$counter]) && $reflectionParameter->allowsNull()) {
                            $passedArgs[] = null;
                        } else {
                            $passedArgs[] = isset($args[$counter]) ? strval($args[$counter]) : "";
                        }
                }
            }
            $counter++;
        }

        parent::invokeAction($action, $passedArgs);
    }
}
```

Usually the action arguments are scalars  
  - `int` usually for object ID or `string` if UUID primary keys are used
  - `string` for data that are expected to be strings
  - other data types are not usually passed in URL, but might be (boh `bool` and `float` i can imagine using in URL)

I think, if CakePHP currently targets PHP 7.2+ and strong-typed, scalar, function arguments were added in 7.0 ( see https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types ), we should support strong-typed action declarations and convert the value if we can be sure, and delegate the work to user-handler or fail if we cannot be sure about correct input-type-output handling

**Comment by othercorey** [comment]
Type hints are used to enforce a type. This forces the data into that type. What if the data isn't the type you expect? 

The regex patter in the Route ensure the data is valid, but they are not required.

**Comment by smarek** [comment]
Yes, gets rid of stress (copy-pasta) like this
```php
function myAction($a, $b, $c) {
  $a = intval($a);
  $b = strval($b);
  $c = intval($c);
  if ( empty($a) || $a < 1 ) {
        throw new \http\Exception\InvalidArgumentException();
  }
}
```
Because usually I want to know, that I'm working with specific type of data, thus I validate the data in router (regexp) and I'd expect the data to be strong-typed in function, so I do not have to do any more type checks, just value checks, that are easier once I'm certain of the type.

And if I understand the question correctly, if the data is not of expected type, it should fail hard, because I have either invalid route definition or invalid action-function argument type declaration, and that is something that should not pass silently

**Comment by othercorey** [comment]
How should it fail?

**Comment by smarek** [comment]
I guess standard 500 for internal server/app misconfiguration error is better than 404 for standard mismatched route (404 can occur if URL will not pass validation of regexp in routes.php), 500 better suits the incorrect configuration vs. request
For debug then InvalidArgumentException to hint at what kind of problem we're dealing with

**Comment by othercorey** [comment]
But how does it validate the data?

**Comment by smarek** [comment]
I don't think it does validate the data, validation occurs either before (route param regexp) or after (ie. validating range or in_array or by ORM Table::get), it only simplifies the necessary casting of string (default route param type) to specific target data type, so it can be directly used, instead of having to cast it first.


use-case 1:
Usual SQL model is integer primary key auto-increment, and scaffold methods to add/edit/detail that take the primary key as first argument. ORM does the casting as well, if it has to, but if I want to work with the raw value passed from route to action/function, i have to cast it first to expected type before I can use in_array or numeric operations

use-case 2:
```php
// routes.php - simple route without validation, only passing the data down
$routes->connect('/organizations/{organization_id}/edit/{type_id}', ['controller' => 'Organizations', 'action' => 'addModify'])->setPass(['organization_id', 'type_id']);

// OrganizationsController addModify before RFC
    public function addModify($organization_id, $type_id)
    {
        if ( !empty($type_id) && !is_numeric($type_id) ) { throw new Exception('invalid type_id'); }
        $type_id = intval($type_id);
        if ( in_array($type_id, [1,3,5]) ) {
            // do something
        }
        if ( !empty($type_id) && !is_numeric($type_id) ) { throw new Exception('invalid organization_id'); }
        $organization_id = intval($organization_id);
        $organization = $organization_id > 0 ? $this->Organizations->get($organization_id) : $this->Organizations->newEmptyEntity();
    }

// OrganizationsController addModify after RFC
    public function addModify(int $organization_id, int $type_id)
    {
        if ( in_array($type_id, [1,3,5]) ) {
            // do something
        }
        $organization = $organization_id > 0 ? $this->Organizations->get($organization_id) : $this->Organizations->newEmptyEntity();
    }

**Comment by othercorey** [comment]
I think we would have to require the data is validated via regex if there if the parameters are typed. When if users are expecting a string and accidentally type their parameter as int? That could be a difficult bug.

https://3v4l.org/2uauA

**Comment by smarek** [comment]
Well might be and might not, I personally would use this as a security filter, knowing that whatever is passed into url, will come out as predictable data type, and if the input was not expected (or was deliberately messed with), the output is still something I can work with.
I currently use routes regex that way, but it is kind of complementary, if I don't validate the param in route, unexpected input will still result in expected output (data type), which can be further handled programatically, except for strings (that can contain unexpected symbols, and that is something regex must handle either in routing or after the method is invoked) and booleans (those are tricky to handle, see https://www.php.net/manual/en/function.boolval.php#reflectionproperty.hastype.example.basic )

Actually, thinking about it, requiring regex validation of input would probably slow down the process and put duplicate checks in as well, and currently I cannot think of reason why `regex(\d+) -> cast(intval) -> invokeAction(int)` would provide better clarity about the process or security than `cast(intval) -> invokeAction(int)`

**Comment by markstory** [comment]
> I guess standard 500 for internal server/app misconfiguration error is better than 404 for standard mismatched route

I don't agree with this. An incorrect URL should always be a 4xx error code, either a 404 or a 400. 5xx error codes are for when the server had a failure it couldn't handle when the client made an otherwise valid request.

I think regex is required to validate parameters as well. PHP type casting silently fails and mis-handles data like

```php
php > var_dump(intval('3 bears'));
int(3)
```

Simply casting will yield incorrect results. Because routes are already applying regex patterns, that would also be a good place to do casting. This would result in the output of `Route::parseRequestl()` being typed correctly, or have an exception raised.

**Comment by othercorey** [comment]
> Actually, thinking about it, requiring regex validation of input would probably slow down the process and put duplicate checks in as well, and currently I cannot think of reason why regex(\d+) -> cast(intval) -> invokeAction(int) would provide better clarity about the process or security than cast(intval) -> invokeAction(int)

You can think of a reason why validating data would give better security?

What's the point of this change then? Why not just cast your value to (int) when you pass it along?

**Comment by smarek** [comment]
@markstory ok, regexp it is, however since the params will be casted, i presume there will be something as `originalParams` and `castedParams` in the request for debugging?
ad 4xx/5xx code, if I connect route and the function exists, but has different number / type of arguments, that's less *not found situation* and more *internal server error*, obviously this won't happen if we require params to be validated through regexp, because the action/function would not connect to the route, if it contains unexpected data

@othercorey i poorly articulated, to explain, if param regexp will allow any word character or empty string, eg. `\w*`, casting the data into `int` param-type will still silently fail/mis-handle data. Which concludes that if I skip the `regex` step and cast directly before executing the function, i get the same result. In such case, user-provided regex gives no additional security.

**Comment by othercorey** [comment]
My opinion is the value of adding a feature like this is ensuring the data is the right type. It should throw an exception is the value isn't the right type (integer, float, string).  Without that, it's not much different than what we have now where you can cast the parameter in the action. There are only a few PHP types we could validate. Another option would be the type system, but there isn't a dependency on that from the controller code.

If we coerce all input into a type, then we hide all invalid input and replace it with unknown behavior (unknown because you can't tell if it's valid or not or know if the user request performed correctly). That might be what you want, but it's not typically the design users want.

**Comment by markstory** [comment]
> regexp it is, however since the params will be casted, i presume there will be something as originalParams and castedParams in the request for debugging?

I wouldn't include before/after parameters. The data is either valid and casts correctly or is invalid and the route does not match. A potential API for this could be:

```php
$routes->get(
  '/organizations/{organization_id}/edit/{type_id}',
  ['controller' => 'Organizations', 'action' => 'addModify']
)
->setPass(['organization_id', 'type_id'])
->setTypes(['organization_id' => 'integer', 'type_id' => 'float'])
```

Any parameter that doesn't have a cast will be assumed to be a string. Using a type for a parameter will also set a pattern for that parameter. The pattern could be overwritten via `setOptions()` which would also remove the cast operation.

**Comment by smarek** [comment]
@markstory thank you for the proposal, i agree in whole, it looks both simple/clear and extensible enough.
I'll also would appreciate if I could add custom types as well, something as
```php
/**
 * bootstrap.php or routes.php
 */

// $typeName => unique name of the type within Route/Router/RouteBuilder
// $matchingValidator => regex processing the input to see if it's valid per expected type
// $deserializer => closure/callable that will return matching data type
// Route::addType(string $typeName, string $matchingValidator, callable|Closure $valueProvider)
Route::addType('customFloat', '\d*(\.\d+)?', function (string $argument) { return new \App\Types\CustomFloat($argument); });

/**
 * routes.php
 */

$routes->get(
  '/organizations/{organization_id}/edit/{type_id}',
  ['controller' => 'Organizations', 'action' => 'addModify']
)
->setPass(['organization_id', 'type_id'])
->setTypes(['organization_id' => 'integer', 'type_id' => 'customFloat']);

/**
 * OrganizationsController.php
 */

public function addModify(int $organization_id, \App\Types\CustomFloat $type_id) { }
```

What do you think?

**Comment by markstory** [comment]
What kind of use cases do you have around custom types? I don't think I've had many use case come up personally.

**Comment by othercorey** [comment]
I would prefer not to have multiple concepts of "types" in cakephp.

**Comment by smarek** [comment]
@markstory exactly as i presented, deduplicating the code that handles conversion from string URL param(s) to expected scalar or complex type (class instance), no particular app use-case now, but I think it has potential and would make the controller interfaces inherently more readable
