### ISSUE TITLE
Windows 10 virus software is blocking

### ISSUE THREAD

**Issue by ognb** [cakephp/cakephp#15030]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1 Strawberry.

### What you did
I was installing new project like this command "composer create-project --prefer-dist cakephp/app:~4.0 my_app_name"

### What happened
Windows 10 virus software blocked this file "vendor/symfony/console/a9c0c8687b8694df6fbdaebd524c0889"
![120850614_342948377149507_918404467777320263_n](https://user-images.githubusercontent.com/4508233/95269582-aa38a680-0874-11eb-9a01-1491523b9a58.png)

**Comment by othercorey** [comment]
You should discuss this with symfony.
