### ISSUE TITLE
"Undefined index: samesite" if an app is upgraded to 3.9.3

### ISSUE THREAD

**Issue by motooka** [cakephp/cakephp#15049]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.3
* Platform and Target: 
  * Amazon Linux 1
  * Apache 2.4.46
  * PHP 7.3.21
  * PostgreSQL 9.6.x
  * behind AWS ALB

### What you did
* deploy a CakePHP 3.9.2 application
  * `debug` : false
* issue a request to the application
* upgraded the application from CakePHP 3.9.2 to CakePHP 3.9.3
* issue a request with no cookie

### What happened
The following log appears in a log file

```
2020-10-12 03:13:31 Notice: Notice (8): Undefined index: samesite in [/var/www/html/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php, line 213]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 168
Sentry\ErrorHandler::handleError() - ROOT/vendor/sentry/sentry/src/ErrorHandler.php, line 379
Cake\Http\Middleware\CsrfProtectionMiddleware::_addTokenCookie() - CORE/src/Http/Middleware/CsrfProtectionMiddleware.php, line 213
Cake\Http\Middleware\CsrfProtectionMiddleware::__invoke() - CORE/src/Http/Middleware/CsrfProtectionMiddleware.php, line 123
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 170
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
App\Middleware\SentryReportMiddleware::__invoke() - APP/Middleware/SentryReportMiddleware.php, line 12
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 96
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 97
[main] - ROOT/webroot/index.php, line 40
```

### What you expected to happen
No such log appears

### Comment
A configuration item `samesite` is added to the class in CakePHP 3.9.3.
The instance of `CsrfProtectionMiddleware` is stored in the route cache : `tmp/cache/myapp_cake_routes_route_collection` by default. 

If the instance of the middleware is cached by CakePHP 3.9.2 or earlier, the instance does not have `samesite` configuration. And, it seems that the constructor function of the cached class is not called when the cache is used. So, after upgrading to 3.9.3, `invoke()` method emits the notice log.
https://github.com/cakephp/cakephp/blob/74f60e2e1f15c8fd27653db2ee835d426b59ee83/src/Http/Middleware/CsrfProtectionMiddleware.php#L210

I guess 4.x version has the same issue.

### Workaround
The issue can be resolved by removing the route cache file when upgrading.
I was not doing so (my deploy script deletes only `models` & `persistent` cache), and I'm afraid that many application developers will see the same issue.

**Comment by ADmad** [comment]
> I guess 4.x version has the same issue.

No it doesn't since support for "Samesite" attribute for cookies exists in 4.x since the first stable release. It was recently backported to `3.9`.

While this particular error can be mitigated such error can crop up with array key changes to a property of any object that gets serialized during routes collection caching.

So busting routes cache during script deployment would be the reasonable thing to do.

**Comment by markstory** [comment]
Is there anything to be done here. I think the deployment docs already recommend clearing the core caches.

**Comment by motooka** [comment]
Thank you for checking.

> I think the deployment docs already recommend clearing the core caches.

I also thought so, but I could not find it in this page : https://book.cakephp.org/3/en/deployment.html
This page does not mention route cache. On the other hand, it is recommended to clear schema cache.

I think it's better to do one of the following :

- using `$this->_config['samesite'] ?? $this->_defaultConfig['samesite']` or similar code
- adding a recommendation to clear also route cache, in [the deployment doc](https://book.cakephp.org/3/en/deployment.html)

**Comment by ADmad** [comment]
Would you like to open pull requests with your suggested changes?

**Comment by motooka** [comment]
Yes, I'll do it.
