### ISSUE TITLE
Add support for PDOStatement::setFetchMode method with PDO::FETCH_CLASS argument

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#15048]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: Any.

I would like to use `setFetchMode` in order to fetch results directly into plain PHP objects instead of entities. Using entities is not memory efficient in some cases where thousands of records should be retrieved. But using plain PHP objects with explicitly defined properties is efficient enough  in some of such cases (see https://gist.github.com/nikic/5015323 for the explanation why).

I can achieve this by using plain SQL with `$this->getConnection()->query(...)` but that is not an elegant solution.

What I would like is something similar to this in the table class:
```
$records = $this->find()
    ->setFetchClass(PlainPerson::class)
    ->select(['id', 'first_name', 'last_name'])
    ->where(['type' => 'active'])
    ->toArray();
```

Where the new method signature would be like this:
```
public function setFetchClass($className, $setPropertiesAfterConstructor = true)
```
If `$setPropertiesAfterConstructor` is `true` then `PDO::FETCH_CLASS|PDO::FETCH_PROPS_LATE` arguments would be used for `fetchMode` method, else `PDO::FETCH_CLASS`.

Calling `setFetchClass` would result in making calls to `fetchMode` and `fetch` by using `PDO::FETCH_CLASS|PDO::FETCH_PROPS_LATE` or `PDO::FETCH_CLASS` arguments instead of `fetch('assoc')` that is usually called and the query result would return an array of plain PHP objects:

```
$PDOStatement->setFetchMode(PDO::FETCH_CLASS|PDO::FETCH_PROPS_LATE, $className);
$result = $PDOStatement->fetch();
```

Ref.:
* https://www.php.net/manual/en/pdostatement.fetch.php
* https://www.php.net/manual/en/pdostatement.setfetchmode.php

**Comment by bancer** [comment]
Another way how this could be implemented is by adding more parameters to `toArray` method:
```
$records = $this->find()
    ->select(['id', 'first_name', 'last_name'])
    ->where(['type' => 'active'])
    ->toArray(PlainPerson::class);
```

**Comment by ADmad** [comment]
You have shown a simple case. Your proposal of being able to specify the fetch class for PDOStatement itself won't work when there are joins or containments involved, so exposing such a feature at ORM level is not practical.

You can instead make a custom entity class which implements `EntityInterface` with it's methods as no-ops and have your "plain" classes extend that. Then you can use `Table:setEntityClass()` to specify that your plain class should be used for hydration.

**Comment by ADmad** [comment]
Or after setting the up the required query clauses call `Query::execute()` to get `StatementInterface` instance using which you can can call `StatementInterface::fetch()` or `StatementInterface::fetchAll()` with required PDO fetch mode.

**Comment by bancer** [comment]
> You have shown a simple case. Your proposal of being able to specify the fetch class for PDOStatement itself won't work when there are joins / containments involved, so exposing such a feature at ORM level is not practical.

`contain()` supports some custom options like 'foreignKeys' and 'queryBuilder' so I believe it would be possible to add another one like 'fetchClass'. If it would be not set then the entity class would be used as usual to fetch associated records or an exception could be thrown asking to set 'fetchClass' for the associations.

**Comment by markstory** [comment]
I agree with @ADmad any new fetch mode would also need to support loading associations and handle _matching. Without that it will be 'broken' for a large number of use-cases and won't be something we can support.

From my understanding the performance benefit comes from 'record' object having all of its properties explicitly defined instead of using the dynamic `_properties` like the base Entity class does. Wouldn't you be able to get the benefits you're looking for using the approach outlined by @ADmad?

**Comment by bancer** [comment]
> You can instead make a custom entity class which implements EntityInterface with it's methods as no-ops and have your "plain" classes extend that. Then you can use Table:setEntityClass() to specify that your plain class should be used for hydration.

I don't see how this would help if `fetch('assoc')` would still be called by the framework.

> Or after setting the up the required query clauses call Query::execute() to get StatementInterface instance using which you can call StatementInterface::fetch() or StatementInterface::fetchAll() with required PDO fetch mode.

This might work in a similar way as by using raw SQL but would have the same limitations related to contain() when hasMany relationship is involved because it would generate at least 2 SQL statements in my understanding. 

> ...and handle _matching...

Is the handling of matching done on the database level or after the query is executed?

**Comment by markstory** [comment]
> Is the handling of matching done on the database level or after the query is executed?

A bit of both. Joins are added during query execution but the data is reformatted after data has been fetched from the database, much like how `contain()` works.

**Comment by bancer** [comment]
Probably it would make sense to allow to use only 'select' strategy in `contain()` when PDO::FETCH_CLASS is used and 'fields' is not empty in `contain()`. So that each SQL query would contain data only from one table.

**Comment by Purus** [comment]
Is this supported now?
