### ISSUE TITLE
TypeError when using Entity::getError() with dot notation

### ISSUE THREAD

**Issue by DBnR1** [cakephp/cakephp#15059]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.5

### What you did
Consider the following example:

```
$entity = new \Cake\ORM\Entity();
$entity->setError('some_field', ['error1' => 'some error', 'error2' => 'some other error']);

debug($entity->getError('some_field.error1'));
```

### What happened
What you get is a TypeError `Return value of Cake\ORM\Entity::_nestedErrors() must be of the type array, string returned`

### What you expected to happen
Expected to see `some error`. Maybe the return type should be removed?

**Comment by ADmad** [comment]
Dot in field name is only meant to be used for nested (associated) fields not specific error keys.
