### ISSUE TITLE
responce->withStringBody() does not send data when withStatus() is used.

### ISSUE THREAD

**Issue by menshutin** [cakephp/cakephp#15067]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.1.5
* Platform and Target: Linux, Apache.

When using `$responce->withStatus()` to set custom status `$responce->withSting()` does not have any effect.

For example, in Controller
```
$response = $this->response;
$response = $response->withStatus(400);
$responce = $response->withStringBody($message);
```
only returns response with 400 error code, but does not send message. And the problem is not related to 400 error code. If I set status to 200, the content-length of response is still 0.

**Comment by ADmad** [comment]
Are you returning your response instance from the action?

Also maybe you are making typos in your variable names as you have done above :). `$response` vs `$responce`.

**Comment by menshutin** [comment]
Return is in the place, as well as a typo :). Thanks for your help.
