### ISSUE TITLE
Oauth 1.0 authentication / Wrong signature 

### ISSUE THREAD

**Issue by Jonathanmav** [cakephp/cakephp#15066]
* [x] bug

* CakePHP Version: 4.1.5
* Platform and Target: Any.

### What you did
I'm trying to make a post request with Oauth 1.0 authentication with an xml body. like this :

```php
$http = new Client();
$response = $http->post('http://example.com/test', '<?xml version="1.0" encoding="utf-8"?><test></test>', [
  'headers' => ['Content-Type' => 'text/xml'],
  'auth' => [
    'type' => 'oauth',
    'consumerKey' => 'xxx',
    'consumerSecret' => 'xxx',
    'token' => 'xxx',
    'tokenSecret' => 'xxx'
  ]
]);
```

### What happened
Everything works fine except that the signature generated is wrong. Cakephp uses the request body to generate it when it shouldn't.

### What you expected to happen
**Section 9.1.1 of Oauth spec (https://oauth.net/core/1.0a/#anchor13) :**

![Capture](https://user-images.githubusercontent.com/3149449/96109067-94635b00-0ede-11eb-9b10-3bc14cf7c00d.PNG)

I'm expecting for cakephp dont use the body of the request to generate the Oauth Authorization when it shouldn't do it :)

**Comment by markstory** [comment]
Pull request open.
