### ISSUE TITLE
RFC: Add support to JSON PATH in queries

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#15073]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

[SQL ANSI 2016 introduced](https://webstore.iec.ch/preview/info_isoiec19075-6%7Bed1.0%7Den.pdf) SQL support for JavaScript Object Notation (JSON):

> The SQL/JSON path language is a query language used by certain SQL operators (JSON_VALUE,
> JSON_QUERY, JSON_TABLE and JSON_EXISTS, collectively known as the SQL/JSON query operators)
> to query JSON text. The SQL/JSON path language is not, strictly speaking, SQL, though it is embedded in
> these operators within SQL. Lexically and syntactically, the SQL/JSON path language adopts many features
> of [ECMAscript], though it is neither a subset nor a superset of [ECMAscript]. The semantics of the SQL/JSON
> path language are primarily SQL semantics.
> 

### What you did

Functions to use JSON PATH was implemented in all modern DBMS supported by CakePHP ORM:

- mysql: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=591207ceddca6fe4f11a3ad8589e7c5b
- sqlserver: https://dbfiddle.uk/?rdbms=sqlserver_2017&fiddle=5c70245f5bb7c96d4adcc6b10ebed195
- postgres: https://dbfiddle.uk/?rdbms=postgres_13&fiddle=0914b4d9622b28f813eed51bab263203
- sqlite: https://www.db-fiddle.com/f/tMcVDVmjxb5wSjemg34dy8/2

### What you expected to happen

A possible approach could be:

```php
$query = $logs->find();
$query->select(['price' => $query->func()->jsonPath("$.data.price")]);
```

Thanks in advance

**Comment by markstory** [comment]
From those fiddle bins it looks like the only thing that varies between the vendors it the name of the JSON path function. This sounds like something that could be supported relatively easily using our existing `FunctionExpression` translation hooks.

I think the new method name you suggested is great, and if you're interested in getting this enhancement added I'd be happy to help with guidance and tests.

**Comment by celsowm** [comment]
> 
> 
> From those fiddle bins it looks like the only thing that varies between the vendors it the name of the JSON path function. This sounds like something that could be supported relatively easily using our existing `FunctionExpression` translation hooks.
> 
> I think the new method name you suggested is great, and if you're interested in getting this enhancement added I'd be happy to help with guidance and tests.

Hi @markstory , I would really appreciate because I still have dificulties to create a pull request on git
I have already forked and clone the cakephp/cakephp but now I need the "src app" to test my ideias on vendor classes. Do you have a article or something to provide me quick steps to how do that?

**Comment by markstory** [comment]
@celsowm I don't generally do development on CakePHP from within an application. You might be able to get that workflow if you add a [composer repository alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to point at your fork. You should be able to edit CakePHP code in the vendor directory and be able to push those changes up to your fork when you're done with them.

**Comment by celsowm** [comment]
> 
> 
> @celsowm I don't generally do development on CakePHP from within an application. You might be able to get that workflow if you add a [composer repository alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to point at your fork. You should be able to edit CakePHP code in the vendor directory and be able to push those changes up to your fork when you're done with them.
> 
> Writing and running tests from within the vendor directory is uncharted waters for me, and I would recommend doing that step outside of an application.

I understand, what is your approach to dev new thing "for cake" and test using it?

**Comment by markstory** [comment]
> I understand, what is your approach to dev new thing "for cake" and test using it?

My workflows is to build features with just a clone of CakePHP and use the test cases as a way to ensure the interface/methods do what I want. For features that involve browser features I use composer repository aliases to get my branch into an application.

**Comment by celsowm** [comment]
Sorry for another dumb question but, how can I run, for example, a method of TestCase\Database\FunctionsBuilderTest.php ?

**Comment by markstory** [comment]
Not a dumb question. From a clone of cakephp with dependencies installed, `vendor/bin/phpunit tests/TestCase/Database/FunctionBuilderTest.php` would run just that one test case.

**Comment by celsowm** [comment]
@markstory Am I missing another step beside git clone and composer require? 
My cakephp-git-fork\vendor\bin:
https://i.imgur.com/v2pbcN2.png

**Comment by markstory** [comment]
you might need to do `php vendor/bin/phpunit tests/TestCase/Database/FunctionBuilderTest.php` or use `\` if `/` isn't working properly on windows.

**Comment by celsowm** [comment]
I did it !

https://i.imgur.com/PEygYYq.png

Now, What the next step to test a "real" sql?

**Comment by markstory** [comment]
Add a new method like `testJsonOperators()`, and build a query that uses the new jsonPath() function. You can dump the SQL a query would make with `debug($query->sql())` and use `assertQuotedQuery()` to compare entire queries with identifier quoting support.

**Comment by celsowm** [comment]
> 
> 
> Add a new method like `testJsonOperators()`, and build a query that uses the new jsonPath() function. You can dump the SQL a query would make with `debug($query->sql())` and use `assertQuotedQuery()` to compare entire queries with identifier quoting support.

Thanks, but I've alrealdy did it, I would like to know how test sql with different databases and different versions too (mysql 8.0.21 has a diferent syntax, for example)

**Comment by othercorey** [comment]
> Thanks, but I've alrealdy did it, I would like to know how test sql with different databases and different versions too (mysql 8.0.21 has a diferent syntax, for example)

Our github actions tests the full range of mysql and postgres versions.

**Comment by celsowm** [comment]
> Our github actions tests the full range of mysql and postgres versions.

Thanks, @othercorey. Well searching for it I've found a interesting thing, **schema_articles**  has a json data column on PostgresSchemaTest:

https://github.com/cakephp/cakephp/blob/29163cb8f360bf9304f72aba4ab735dfcce90977/tests/TestCase/Database/Schema/PostgresSchemaTest.php#L70

But does not in MySQL:

https://github.com/cakephp/cakephp/blob/29163cb8f360bf9304f72aba4ab735dfcce90977/tests/TestCase/Database/Schema/MysqlSchemaTest.php#L279

**Comment by celsowm** [comment]
> 
> 
> > Thanks, but I've alrealdy did it, I would like to know how test sql with different databases and different versions too (mysql 8.0.21 has a diferent syntax, for example)
> 
> Our github actions tests the full range of mysql and postgres versions.

Thanks, I will try to generate the schema table used on queries first

**Comment by othercorey** [comment]
You can enable testing on branches in your fork by changing this:

https://github.com/cakephp/cakephp/blob/29163cb8f360bf9304f72aba4ab735dfcce90977/.github/workflows/ci.yml#L5
