### ISSUE TITLE
SqliteSchemaDilect fails on derived columns from SQLite Views

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#15075]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: `4.1.5`
* Platform and Target: Ubuntu 20.04 LTS, PHP 7.2.33, SQLite 3.32.3, running `bin/cake server`

### What you did
Created a SQLite View that has a derived column using `count()`

```sql
CREATE VIEW view_film_categories AS
	SELECT
	    categories.id,
	    categories.name,
	    CAST(count(film_categories.uuid) as INT) as total
	FROM
	    categories
	LEFT JOIN
	    film_categories on film_categories.category_id = categories.id
	GROUP BY
		categories.name
```

Created a class extending `Cake\ORM\Table`

```php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Table;

class ViewFilmCategoriesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->setTable('view_film_categories');
        $this->setPrimaryKey('id');
    }
}
```

Then called `Cake\Database\Schema\CachedCollection::describe` which ultimately calls `Cake\Database\Schema\SqliteSchemaDialect::_convertColumn`. See stack trace below. 

### What happened

> Unable to parse column type from ""
> Cake\Database\Exception
> CORE/src/Database/Schema/SqliteSchemaDialect.php:57
> Cake\Database\Schema\SqliteSchemaDialect->_convertColumn
> CORE/src/Database/Schema/SqliteSchemaDialect.php:172
> Cake\Database\Schema\SqliteSchemaDialect->convertColumnDescription
> CORE/src/Database/Schema/Collection.php:146
> Cake\Database\Schema\Collection->_reflect
> CORE/src/Database/Schema/Collection.php:100
> Cake\Database\Schema\Collection->describe
> CORE/src/Database/Schema/CachedCollection.php:84

### What you expected to happen

To be able to use views. It seems the SQLite is unable to determine the column affinity (https://www.sqlite.org/datatype3.html) for derived columns. In this case, it would be nice if CakePHP at least defaulted to text or some other string value to avoid the exception?

I am curious about what is happening on other Dialects like MySQL and Postgres for Views with derived columns as well. Maybe those handle types better...

**Comment by markstory** [comment]
> I am curious about what is happening on other Dialects like MySQL and Postgres for Views with derived columns as well. Maybe those handle types better...

It will depend on what data is returned in information_schema. What does SQLIte show as the column information in `PRAGMA table_info($name)` for the view name?

**Comment by cnizzardini** [comment]
It's nihilistic

```sql
pragma table_info('view_film_categories');
```

cid|name |type       |notnull|dflt_value|pk|
---|-----|-----------|-------|----------|--|
  0|id   |INTEGER    |      0|          | 0|
  1|name |VARCHAR(25)|      0|          | 0|
  2|total|           |      0|          | 0|

**Comment by cnizzardini** [comment]
I tried informing it using `CAST()` but unfortunately it doesn't care. Unless I should try different cast type, tried `INT` and `INTEGER`.

**Comment by ADmad** [comment]
Seems we need to default to string type if it can't be inferred from the schema.

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15076
