### ISSUE TITLE
Cookies - Take into account the deletion

### ISSUE THREAD

**Issue by DazordM** [cakephp/cakephp#15095]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1.4
* Platform and Target: Local server with MAMP / Chrome & Firefox navigators.

### What you did
Hello team, I'm actually trying to implement a cookies process for an authentication system wich set cookies with login and hash password for automatically login the user when the option "remember me" is checked. 
The add cookie step work perfectly, I'm using the Cookie class for instanciate a new cookie and add it into the response with the "withCookie()" function as below : 
`$cookie_login = new Cookie('authentication_email', $data['email']);`
`$this->response = $this->response->withCookie($cookie_login);`

The main problem happened when I try to logout the user, the logout process need to remove cookies and redirect in the same function on the login page.

### What happened
When I try to use the remove method on the cookies collection coming from the request, cookies are not persist on the navigator : 
`$cookies = CookieCollection::createFromServerRequest($this->request);`
`$cookies->remove('authentication_email');`
`return $this->redirect($url)->withCookieCollection($cookies);`

If I debug rifght after the remove function, everything is ok but nothing is persist in the navigator, all initial cookies are still here.

### What you expected to happen
I guess cookies have to be deleted when I replace the CookieCollection with the method `withCookieCollection` on the response.

### Workaround
I use this solution to indicate to the navigator the cookie expired.
`return $this->redirect($url)->withExpiredCookie(new Cookie('authentication_email'));`
This actually working but not an ideal solution because the cookie is still into the navigator.

Did i miss something with the cookie management ? I thing the documentation on it is not update because the CookieComponent present in version 3.X is not here in version 4.X.

Thanks for your help.
Matthieu

**Comment by garas** [comment]
_Request_ CookieCollection contains cookies which were received from browser. Changing it won't change anything is browser.

_Response_ CookieCollection contains only cookies you want to add, modify or delete (=expire). It is empty if there is no changes. You don't need to resend all request cookies as in your _What happened_ code snippet.

You need to delete cookies with `$response->withExpiredCookie()` as in your _Workaround_.

3.x had `CookieComponent`, it's `delete()` also sent expired cookie with `$response->withExpiredCookie()`. To use encrypted cookies, `CookieComponent` was replaced with `EncryptedCookieMiddleware`.

**Comment by ADmad** [comment]
Sending cookies with expiry time in the past is how cookies are deleted and that's what `withExpiredCookie()` does. Closing as there's nothing to be fixed here.

**Comment by DazordM** [comment]
Thanks for your answers guy's ! 😃
