### ISSUE TITLE
Dot notation in config files causes overwrite instead of merge.

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#15098]
This is a bug.
CakePHP Version: 4.1.4

### What I did
One config file that sets a config value like this:
```
[
    'Plugin' => [
        'Foo' => [
            'Bar' => ['a' => 1] 
        ]
]
```
and another config file that attempts to set another 'Plugin.Foo.Bar' value like this:
```
[
    'Plugin.Foo' => [
        'Bar' => ['b' => 2]
    ]
]
```

### What happened
Instead of merging the values, the latter completely overwrites the former, resulting in only `['b' => 2]` being persisted for `'Plugin.Foo.Bar'`.

### What I expected to happen
I expected the `Configure::load()` behavior to translate dot notation into array keys like `Configure::write()` does and merge both values into `['a' => 1, 'b' => 2]`.

### Why it happened
 - `Configure::load()` uses `Hash:merge()`, but it doesn't merge `['Plugin']['Foo']['Bar']` with `['Plugin.Foo']['Bar']`. It stores each as separate values.
 - `Configure::write()` then uses `Hash::insert()`, which _does_ translate dot notation, but it also overwrites without merging
 - This overwrite appears to be due to [`Hash::_simpleOp('insert')`'s `$_list[$key] = $values` operation](https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L371) which overwrites instead of `array_merge()`ing.

**Comment by markstory** [comment]
I don't know how we'd fix this without recursively visiting every key in a load operation, checking for `.` and potentially expanding it. Expanding key names could also cause merge conflicts and data loss. Configuration files have never supported key expansion to my knowledge, and I don't think supporting it is straightforward or simple.

**Comment by ADmad** [comment]
I too don't think we should try to support expanding keys with dots.

**Comment by PhantomWatson** [comment]
To clarify, expanding keys with dots is something that's already taking place in this process, but it just results in an overwrite instead of a merge in the case of an existing value due to its reliance on the overwrite-only `Hash::insert()` function.

I think that data loss would only occur when conflicting values for the same key are provided by the user, which the user should expect, and I don't think the framework would need to prevent, especially if it's due to a bugfix for unexpected data loss resulting from non-conflicting values like the a/b thing I described above.

A fix could be implemented like this:
 - `Hash::insert()` is given a fourth `$merge` boolean parameter that `array_merge()`s instead of assigning values when existing and new array values are found.
 - `Configure::write()` is given a third `$merge` boolean parameter that gets passed to `Hash::insert()`
 - `Configure::load()` calls `Configure::write()` with the parameters `$values, null, true`

Then I think dot notation would work as expected in configuration files.

In lieu of a fix, a note about this would be warranted in the docs, as a lot of documentation around the CakePHP community uses dot notation to refer to configuration keys without explicitly saying that those literal dot notation strings are for calls to `Configure::write()` and not for configuration files. The fact that dot notation actually _does_ work in configuration files without any problems as long as you're not expecting to inherit default values has probably lead to more people using this format and not realizing the potential problem.

**Comment by markstory** [comment]
> To clarify, expanding keys with dots is something that's already taking place in this process (not in Hash:merge(), but in Hash::insert()

From what I can tell `Hash::insert()` isn't used during config file load operations. Having Configure::write() and Configure::load() work on different data is required as they do different things. `Configure::write()` also doesn't expand `.` in keys that are in the middle of the data payload. For example

```php
        Configure::write('one', ['Thing.thing' => 'value']);
        $result = Configure::read('one');
```

Will not expand `Thing.thing` into nested keys. I'm not confident that the expectation that keys will be expanded by `Configure::load()` is widely held. I'm reluctant to add more parameters to several methods to enable this path when it doesn't seem like a general use case yet.

**Comment by PhantomWatson** [comment]
`Configure::load()` [calls](https://github.com/cakephp/cakephp/blob/master/src/Core/Configure.php#L339) `Configure::write()`, which [calls](https://github.com/cakephp/cakephp/blob/master/src/Core/Configure.php#L92) `Hash::insert()`.

I think that adding a note in the documentation that conveys "dot notation is only intended for the first parameter of `Configure::write()` and not anywhere else in the Configure context" is an acceptable solution. Not supporting it in config files shouldn't be an impediment to anyone, as long as it's explicitly stated that it's not supported (despite it working for full array overwrites).

**Comment by ADmad** [comment]
Adding a note in the manual clarifying the behaviour sounds good. No code change is necessary.
