### ISSUE TITLE
Mass Assignment with Hidden Fields Validation Error

### ISSUE THREAD

**Issue by wiifree** [cakephp/cakephp#15094]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.5
* Platform and Target: POST request over nginx

### What you did
I have a defined entity with many fields, one of them in the protected $_accessible array is false and in the protected $_hidden array. If you request the entity over the route resources function with /:id the entity comes out without the field. Thats fine. But if a user send this data to the edit endpoint without this field and you override the entity with the patchEntity method the validation fires an error that the property is reqired, but the property is already set.

For example:
Entity:
```
class Customer extends Entity
{
    protected $_accessible = [
        'organisation_id' => false,
        'number' => true,
        'type' => true,
    ];

    protected $_hidden = [
        'organisation_id'
    ];

}
```

Model:

```
public function validationDefault(Validator $validator): Validator
{
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->integer('organisation_id')
            ->maxLength('organisation_id', 255)
            ->requirePresence('organisation_id', true)
            ->notEmpty('organisation_id');
```

Controller:
```
$customer = $this->Customers->get($id);
debug($customer); /* <--- NO ERRORS */
$data['number'] = '123';
$customer = $this->Customers->patchEntity($customer,$data);
debug($customer); /* <--- Error 'organisation_id' => ['_required' => 'This field is required',], */
```

The field "organisation_id" is not empty but the validator think it is empty.

**Comment by ADmad** [comment]
The validator validates the request data, not the entity properties. So based on your validation rules the error is expected since the `$data` passed to `patchEntity()` does not have `organisation_id`.

Since your `organisation_id` isn't accessible (mass assignable) you can just remove validations for that field or use different set of validation rules as per your use case.
