### ISSUE TITLE
4.x regression on patchEntity update query for datetime columns 

### ISSUE THREAD

**Issue by jmbIFR** [cakephp/cakephp#15099]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.5
* Platform and Target: apache, php 7.3 ; .

### What you did
When I update data with patchEntity, datetime data are always updated even if the datetime is not modified.

### What happened
When using patchEntity, CakePHP 4 generate an sql query to update all datetime columns, even if the columns is not modified.    

cakePHP convert datetime columns to FrozenTime objects.

This is a regression come with commit  : https://github.com/cakephp/cakephp/commit/9bd82d7ac13642f03cde23c43e73c5a5271694b9

 src/ORM/Marshaller.php (line 562 563)
```php
 -  (is_object($value) && !($value instanceof EntityInterface) && $original == $value)
+  (is_object($value) && !($value instanceof EntityInterface) && $original === $value)
```

in cakePHP 3, $original == $value, check that FrozenTime objects are set dirty only if object data is different
in cakePHP 4, $original === $value,  FrozenTime objects are always set dirty even if FrozenTime objects data have the same date.

### What you expected to happen

restore the cakePHP 3 behavior so update query are correct.

**Comment by markstory** [comment]
Closing as a pull request is open.
