### ISSUE TITLE
Model.afterSaveCommit on Table::saveMany() can't acess entity original values

### ISSUE THREAD

**Issue by victoreassis** [cakephp/cakephp#15106]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.3
* Platform and Target: Any

### What happened
Using the `Table::saveMany()` method and check against original data on `Model.afterSaveCommit`, but it is not possible as the original values are being cleaned on the `Table::save()` before the `Table::_saveMany()` calls it.

### What you expected to happen
That the original values could be accessible on the `Model.afterSaveCommit` as it works when `Table::save()` is called.

The problem seems to be that the following is always called before the `Table::saveMany()` can dispatch the event.
https://github.com/cakephp/cakephp/blob/39d8d1247d33916777676603cbeb0d620cae279f/src/ORM/Table.php#L1842-L1846

**Comment by dereuromark** [comment]
I don't know if this can be solved in core - especially in a BC way.
I think I once created a behavior you can attach and then get the entity from before actually resetting:
https://github.com/dereuromark/cakephp-tools/blob/master/docs/Behavior/AfterSave.md
Is that what you need?

**Comment by victoreassis** [comment]
Thanks. It should work.

**Comment by othercorey** [comment]
Closing with the solution available in user code.
