### ISSUE TITLE
RFC: Replace asset timestamp by asset hash on URLs

### ISSUE THREAD

**Issue by jrbasso** [cakephp/cakephp#15108]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 5.0+
* Platform and Target: N/A

### The problem
Currently we can set the `Asset.timestamp` option or pass an option on the `HtmlHelper`/`UrlHelper` methods, so the URL will contain the file timestamp on it as query parameter. It helps to generate a new cached version/request for the file. It is great when the assets are static on the repository, however with the increase of asset bundle builder and compilers for assets (webpack, sass, rollup, grunt tasks, etc) it's making the timestamp to vary on every build.

It is not a problem in terms of functionality since the assets are going to work the same way, but when it's deployed, the browser and CDNs will have to download the assets again, increasing network throughput, slowing down the page load, etc.

### Proposal solution
Replace the asset timestamp functionality by an asset hash. It will have the same end goal (vary the cache when file is modified), but will not vary the hash when the content of the file is update. PHP offers the methods `md5_file` and `sha1_file` that can be used for that and they are pretty quick.

### Migration plan
For CakePHP 5.0:
* Replace the asset timestamp functionality by asset hash (likely `sha1_file`).
* Create the configuration called `Asset.hash` with the same values from `Asset.timestamp`
* The configuration `Asset.timestamp` will be marked as deprecated and will be an "alias" for `Asset.hash`
* Deprecate option `timestamp` from UrlHelper, making an alias to `assetHash`
* Add the option `assetHash` on the methods currently supporting `timestamp` on `UrlHelper`

### Considerations
An alternative would be supporting both options (timestamp and hash), but both will accomplish the same goal, so I don't think is necessary to create more global configurations and helper method options. It will make things more confuse when one option solves both problems.

**Comment by dereuromark** [comment]
I think this could already go into 4.next and could be completely replacing the timestamp for 5.0.

**Comment by jrbasso** [comment]
What type of resources? Currently the timestamp is used to css, script/js, image and any other asset you target directly with `assetUrl`.

**Comment by dereuromark** [comment]
```
// Check again if path has protocol as `pathPrefix` could be for CDNs.
        if (preg_match('|^([a-z0-9]+:)?//|', $path)) {
            return Router::url($path);
        }
```
So I guess there is a use case for CDN assets, which would be easier handled with the timestamp still.
Or at least here checking the content is a bit more cumbersome.
In general, the asset hash requires opening the files - so this could also be a performance issue on the server side.

In the end both ways have their pros and cons.

**Comment by jrbasso** [comment]
I don't think this change would make any difference for CDN assets. The use of CDN is based on the `App.*BaseUrl`, so the method will generate either the timestamp or hash, which is indifferent for the CDN server. They will treat just as variation. What I'm proposing is to change the value of the query parameter, everything else remain as it is.

I agree that asset hash requires opening file and hashing it, which can elevate the CPU. Most of the assets should take under 1ms since they are in few KB when using md5, but it needs to be multiplied by the number of assets on the request. And yes, it's way higher than checking the file modified time, which doesn't require opening the file.

So I wonder if an option would be better for the user to pick. In that case it can choose between md5/timestamp globally and also override when calling `HtmlHelper` methods. Thoughts?
If that's better, I will adjust the original description with the change plan.

**Comment by ADmad** [comment]
Generating a hash instead of using modified time quite is significantly more expensive operation and I don't think most people would need it. 

Instead we can come up with a more generic solution which allows setting a callable which would take the asset path as argument and return required string which would be used as query string for the asset URL.

**Comment by othercorey** [comment]
I would also not want to read each file for each request.

**Comment by jrbasso** [comment]
That's fair enough, we don't need to have the hashing in the core. Having a way to customize the behavior is a good step. At the application level it can use use the hash combined with caching to avoid processing the files on every request.

Ok, so a new proposal: 
* Change the configuration `Asset.timestamp` to `Asset.versioning`, so the configuration can be used for any method
* Update the `timestamp` option on the helper to `versioning`
* Add a new optional configuration called `Asset.versioningMethod` who either receives a callable (default to `[\ Cake\Routing\Asset::class, 'assetTimestamp']`) or a class implementing a new interface for versioning assets (something like `\Cake\Routing\Asset\VersioningInterface`). If using the interface, the method from `Asset` would be moved to a new class implementing the `VersioningInterface`.

This way an application/plugin can setup a custom method and implement it as desired.

After you guys mentioned about the fact the file is read every request, I started looking alternatives, such as combining with cache, but I also saw that webpack has a filename modifier called `contenthash` which will generate the filename with a unique hash for that file. They also generate a manifest file that the app can read and adjust. With the callback/interface solution it would be easier to implement too, since the app won't have to worry about it, the asset versioning feature would look for the manifest and update the url accordingly.

**Comment by markstory** [comment]
> Add a new optional configuration called Asset.versioningMethod who either receives a callable (default to [\ Cake\Routing\Asset::class, 'assetTimestamp']) or a class implementing a new interface for versioning assets (something like \Cake\Routing\Asset\VersioningInterface). If using the interface, the method from Asset would be moved to a new class implementing the VersioningInterface or the Asset itself would implement that interface.

I'm not sure we need a formal interface. An adhoc interface is probably fine. There is only one input (the file) and one output, the new path.

**Comment by jrbasso** [comment]
I found a less intrusive/configurable way to introduce that. It's a pretty small change but accomplish the desired and also open for other types of changes.

I have tested with a sample app and I will write test cases before opening the PR, but just in case you want to validate the approach: https://github.com/cakephp/cakephp/compare/4.next...jrbasso:4.next-asset-versioning

The app can create the file `src/Routing/Asset.php` and have something like this:
```php
<?php

namespace App\Routing;

use Cake\Routing\Asset as CakeAsset;

class Asset extends CakeAsset {
    public static function scriptUrl(string $path, array $options = []): string
    {
        $url = parent::scriptUrl($path, $options);
        return $url .= '?hash';
    }
}
```

**Comment by ADmad** [comment]
Now if we just make the use of `Asset` class in `UrlHelper`  configurable no other change will be needed in the core :slightly_smiling_face:.

**Comment by jrbasso** [comment]
@ADmad Do you mean to pass the asset class as part of the `$options` of each method? Or maybe a configuration like `Asset.urlBuilderClass`?

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15120
