### ISSUE TITLE
Bulk insert using \Cake\ORM\Table->saveMany()

### ISSUE THREAD

**Issue by Shylajhaa** [cakephp/cakephp#15111]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.9.3.

### What you did
There are certain use-cases, where there are too many records to insert, and the ```saveMany()``` function doesn't seem to have a solution to insert rows in bulk (though this can be achieved using ```\Cake\ORM\Query->insert()```).

### What happened
The ```save``` and ```saveMany()``` functions have similar implementations. ```saveMany()``` iterates through the entities and insert queries are run one by one.

### What you expected to happen
The 2nd parameter of ```saveMany() - $options``` can support a boolean key to decide if the records should be inserted at once.

Moving from ```saveMany()``` to ```query()->insert()``` resulted in significant performance gains. So it would be great if this could be accommodated in the ORM.

**Comment by markstory** [comment]
> Moving from saveMany() to query()->insert() resulted in significant performance gains. So it would be great if this could be accommodated in the ORM.

I'm not sure a bulk insert fits in the ORM paradigm, unless it also handles all the ORM callbacks. The reason saveMany() loops over the entities is so that the beforeSave, afterSave and application rule callbacks can be fired. A bulk insert would need to also trigger all of these events. Perhaps the events could be triggered in bulk around the insert query?

**Comment by Shylajhaa** [comment]
If I'm not wrong, in the current implementation, the bulk updates/deletes doesn't invoke the lifecycle events (```beforeSave(), afterSave()```, etc.). The bulk inserts can skip the lifecycle events as well.

The single insert can approach can be used in cases where the callbacks are necessary.

**Comment by dakota** [comment]
Perhaps an `insertAll` method to  compliment the existing `updateAll` and `deleteAll`?

**Comment by dereuromark** [comment]
I had the same thought :)

**Comment by Shylajhaa** [comment]
Agree with @dakota and @dereuromark 
This sounds perfect.

**Comment by othercorey** [comment]
Those operate on fields while saveMany operates on entities.  What's the difference between insertAll and just using insert?

**Comment by Shylajhaa** [comment]
@othercorey Idea is to minimize the number of queries, insertAll() will insert all rows at once.

**Comment by othercorey** [comment]
And why wouldn't insert?

**Comment by othercorey** [comment]
I would support letting `saveMany()` perform a single insert somehow.

**Comment by ADmad** [comment]
@Shylajhaa Why can't you just use Query::insert()?

**Comment by othercorey** [comment]
> @Shylajhaa Why can't you just use Query::insert()?

Thats what Im saying too. However if there is a good solution for saveMany I’d be interested to see it. I dont think insertAll makes sense because it would be the same signature as insert.

**Comment by ADmad** [comment]
saveMany() works with entities, if the aim is to speed up the process I don't see why someone would  create entities first before doing a bulk insert.

**Comment by markstory** [comment]
The `updateAll` and `deleteAll` methods are partly a relic of trying to make the 2.x to 3.x migration a bit easier. The lack of callbacks has caused a few issues to be reported for these methods. Adding an `insertAll` method is preferable over adding a modal option to `saveMany`. The behavior is different enough that an option is not great.

What would the signature be for the `insertAll` method be?

**Comment by dereuromark** [comment]
> partly a relic 

That is not true. Those are atomic operations and have their fair use also in 3.x and 4.x, no? :)

The same would apply to insertAll (being atomic), rather than saveAll()/Many(),.. which are working on entities and use callbacks.

**Comment by Shylajhaa** [comment]
Possible signature for the ```insertAll()```

```insertAll($columns, $rows) : int```
```$columns``` - array of column headers
```$rows``` - array of rows to be inserted

**Comment by markstory** [comment]
> That is not true. Those are atomic operations and have their fair use also in 3.x and 4.x, no? :)

They do, but those operations can be done without the Table wrappers now using `Query::delete()` and `Query::update()`. Not having to duplicate the cursor handling logic is one of the reasons the `updateAll()` and `deleteAll()` methods are still around.

> The same would apply to insertAll (being atomic), rather than saveAll()/Many(),.. which are working on entities and use callbacks.

Yes, having an insert based method completes the set :smile:

@Shylajhaa Do you need the column names? Could they be inferred from the first row of data?

**Comment by Shylajhaa** [comment]
> Do you need the column names? Could they be inferred from the first row of data?

@markstory Just had one concern. Having a separate ```$columns``` array will help us validate if all the ```$rows``` have the same set of keys. Since the ```validationDefault()``` or ```buildRules()``` of entities wouldn't be invoked in case of ```insertAll()```, this validation would be helpful.

**Comment by ADmad** [comment]
> Having a separate $columns array will help us validate if all the $rows have the same set of keys.

That can be done without a `$columns` var too. Get the keys of first row (which would be the fields/columns) and ensure subsequent rows have the same keys.

I am not thrilled about adding new methods to `Table` which don't use entities. How about adding `insertAll()` to `ORM\Query` instead? `deleteAll()` and `updateAll()` too should probably be moved there. These methods don't use/need any info from the `Table` class.

**Comment by markstory** [comment]
@ADmad Would those be on the ORM\Query or Database\Query?

**Comment by ADmad** [comment]
@markstory I think people would expect the db types mapping to be handled automatically so `ORM\Query` I guess.
