### ISSUE TITLE
bin/cake server ignores PHP environment variable

### ISSUE THREAD

**Issue by levu42** [cakephp/cakephp#15116]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.5
* Platform and Target: linux x64

### What you did
I wanted to try out a different PHP version than the one installed system-wide, compiled it and ran

    $ PHP=/path/to/my/own/cli/php bin/cake server

### What happened
The bin/cake script was running with the PHP version I compiled locally, but the server it starts with `php -S` runs with the system-wide installed PHP version.

### What you expected to happen
I expected the ServerCommand.php script to also check for the PHP environment variable like the bin/cake script and use the PHP path provided in it if available, else fall back to the system-wide PHP installation

The relevant code is in [ServerCommand.php:130](https://github.com/cakephp/cakephp/blob/master/src/Command/ServerCommand.php#L130)

**Comment by markstory** [comment]
Pull request open now.
