### ISSUE TITLE
Add a tag to right justify text in TableHelper

### ISSUE THREAD

**Issue by imo-tikuwa** [cakephp/cakephp#15117]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.5
* Platform and Target: Any

### What i did
I have added a text-right tag to [TableHelper](https://github.com/cakephp/cakephp/blob/master/src/Shell/Helper/TableHelper.php) that allows right-justified output of columns.

I checked the operation with the test code in the following branch.
https://github.com/imo-tikuwa/cakephp/commit/95e783868c68d625ba2928d427dff9262a2d4458

### What you expected to happen
If there is no problem with this fix, I would like to send a pull request to merge.

**Comment by othercorey** [comment]
It is easier to discuss if you open the PR.

**Comment by imo-tikuwa** [comment]
I tried to create a PR.
