### ISSUE TITLE
process() function in AuthenticationMiddleware.php takes sometimes too long

### ISSUE THREAD

**Issue by VARGA-Peter** [cakephp/cakephp#15114]
Some pages need for a simple reload sometimes very long [between 4 and 45 seconds]. Unfortunately the delay isn't predictable. First I thought it's of course something I did wrong but after further investigations I found the delaying function. 

----------

It's in `vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php` the function `process()` running this code `$service->authenticate($request);`

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $service = $this->getAuthenticationService($request);

        try {
            $result = $service->authenticate($request);
            ^^^^^^^^ This call needs between 0.01 and 45 seconds
        } catch (AuthenticationRequiredException $e) {
            $body = new Stream('php://memory', 'rw');

----------

These are some sample dumps from my execution time measurements:

A dump for `/api/shop` with a long execution time; scroll to the right to see the delta times between each time snapshot:

    [2020-11-01T16:58:02+00:00] /api/shop/ - /vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php :0103 - Delta time:0.04342
    [2020-11-01T16:58:14+00:00] /api/shop/ - /vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php :0107 - Delta time:11.81272
    [2020-11-01T16:58:14+00:00] /api/shop/ - /vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php :0121 - Delta time:11.81295  

Then, 17 seconds later [no change, just reloading the page] there is no delay:

    [2020-11-01T16:58:31+00:00] /api/shop/ - /vendor/cakephp/cakephp/src/Http/Runner.php                                :0071 - Delta time:0.03756
    [2020-11-01T16:58:31+00:00] /api/shop/ - /vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php :0103 - Delta time:0.04211
    [2020-11-01T16:58:31+00:00] /api/shop/ - /vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php :0107 - Delta time:0.04506

----------

Any idea what the reason can be? It's very frustrating because it's totally unpredictable. As in the above real samples shown, within few seconds there is a huge delay and then it works for 3-4 times and then suddenly it delays again. As mentioned before, I am not doing anything; just reloading the page.

CakePHP 4.1.4

**Comment by othercorey** [comment]
When there is a delay, are you submitting credentials such as a form?

**Comment by VARGA-Peter** [comment]
> When there is a delay, are you submitting credentials such as a form?

To access the in the example mentioned `/api/shop/` site the user must log in which happens before. But while reloading of `/api/shop` no data is sent. The logged in status is in stored in the cookies. It's really a very simple reload without any parameters.

What confuses me totally is that 3-4 times it works perfectly and then there can be a delay up to 45 seconds. You know what in the year 2020 in 45 seconds can happen: You can copy GB of data....

**Comment by othercorey** [comment]
Can you add timings to `Authentication\Authenticator\SessionAuthenticator` to see which part of it is taking that long? If you have 'identify' enabled, add timings to that code.

I assume you're just using session authentication since you said cookies.

**Comment by VARGA-Peter** [comment]
> Can you add timings to `Authentication\Authenticator\SessionAuthenticator` to see which part of it is taking that long? If you have 'identify' enabled, add timings to that code.
> 
> I assume you're just using session authentication since you said cookies.

We are coming closer to the solution! Thank you very much for your support. This is now the function which is delaying it so much:

in `vendor/cakephp/cakephp/src/Http/Session.php` 
   --> `start()` 
      --> `if (!session_start()) {`

The full code:
```
        if (!session_start()) {
            throw new RuntimeException('Could not start the session');
        }
```

OK, checking [SO](https://stackoverflow.com/questions/13772074/session-start-takes-very-long-time) and I get this answer and this gives me a clue... I will post here an update.

**Comment by VARGA-Peter** [comment]
_I think I found the reason:_
I am using also SSE and this was apparently locking the session file which caused this unpredictable delays.

_My solution:_
I am calling `session_write_close();` in the SSE function as I don't need there the session. After testing it now for 20 minutes and all reloads have been finished <2 seconds I think I can say it's solved.

@othercorey **THANK YOU VERY MUCH!**

I know, this is a very special situation but I cannot believe I am the first one who is using SSE within CakePHP. May be some check could be added when `session_start()` takes longer than X seconds that a hint/exception is thrown. Just my two cents...
