### ISSUE TITLE
I want to translate the return of this function (timeAgoInWords) 

### ISSUE THREAD

**Issue by arbims** [cakephp/cakephp#15128]
I want to translate the return of this function (timeAgoInWords) cakephp which in French which allows to return the date in text format

* CakePHP Version: 4.x.

I create folder Locale in src

this is the function in my view

```
$this->Time->timeAgoInWords($v->created)
```

this is my code in app.php

```
 'encoding' => env('APP_ENCODING', 'UTF-8'),
 'defaultLocale' => env('APP_DEFAULT_LOCALE', 'fr_FR'),
 'defaultTimezone' => env('APP_DEFAULT_TIMEZONE', 'UTC')
```

this is my code in bootstrap.php

```
use Cake\I18n\I18n;
use Cake\I18n\Time;
use Cake\I18n\Number;
I18n::setLocale('fr_FR');

```

but the date is alway in English 
alway i have same result like this : 23 hour, 54 minute ago

thank you for help

**Comment by garas** [comment]
Cakephp 4 translations should be in `resources/locales/fr_FR/cake.po`, not  in `src/Locale/fr_FR/cake.po` like it was in 3.x.

You can copy translations from https://github.com/cakephp/localized

**Comment by arbims** [comment]
@garas  I did as you said but always the same result

**Comment by arbims** [comment]
@garas it works thank you very much :+1:
