### ISSUE TITLE
QueryTest::testSQLFunctions failing on postgres

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15125]
This is failing on 4.next consistently now.

```
1) Cake\Test\TestCase\Database\QueryTest::testSQLFunctions
Failed asserting that false is true.

/home/runner/work/cakephp/cakephp/src/TestSuite/TestCase.php:842
/home/runner/work/cakephp/cakephp/tests/TestCase/Database/QueryTest.php:3705
/home/runner/work/cakephp/cakephp/tests/TestCase/DatabaseSuite.php:72
```

**Comment by markstory** [comment]
I tried running just the Database\QueryTest and the entire database package tests locally against postgres 10.14 and there weren't any failures. I wonder what is different in github actions environment :thinking:

**Comment by othercorey** [comment]
I increased the now() comparison to 5s.
