### ISSUE TITLE
Session lost when return back from payment gateway with post method

### ISSUE THREAD

**Issue by udaythanks1810** [cakephp/cakephp#15142]
* CakePHP Version: 4.0.9.
* Platform and Target: Nginx, PHP 7.4, Mysql 8.

### What you did
I have upgraded my application cakephp 3.2.5 to 4.0.9 version, after upgradation facing issue to lost session when return back from payment gateway with post method and working fine with get method and anywhere moving into application.

I have changed session configuration into app.php but still facing same error.

'Session' => [
        'defaults' => 'php',
        'timeout' => 1800,
		'ini' => [
                 'session.cookie_lifetime' => 7200, 
                 'session.cookie_secure' => false, 
                 'session.cookie_samesite' => 'Lax' 
                 ]
    ],

**Comment by garas** [comment]
`SameSite=Lax` prohibits cross-origin requests using `POST`, so this is expected behavior.

You can specify `SameSite=None` if the cookie should be sent in cross-site requests.

**Comment by udaythanks1810** [comment]
HI Garas,

I have checked with SameSite=None but getting same error

'Session' => [
        'defaults' => 'php',
        'timeout' => 1800,
		'ini' => [
                 'session.cookie_lifetime' => 7200, // two hour
                 'session.cookie_secure' => false, 
                 'session.cookie_samesite' => 'None' 
                 ]
    ]

**Comment by garas** [comment]
`SameSite=None` requires the `Secure` attribute, otherwise it will be rejected by browser.

You can read more about SameSite cookies https://web.dev/samesite-cookies-explained/
