### ISSUE TITLE
Wrong second paginator query in beforeFind

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#15141]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12.
* Platform and Target: Apache, MySQL.

### What you did
In the controller class: `$Paginator->paginate($Query)->toArray();`.
In the table class:
```
    public function beforeFind(Event $event, Query $query, ArrayObject $options, $primary)
    {
        \Cake\Log\Log::debug($query->sql());
    }
```

### What happened
In the queries log I got two paginator queries - one that retrieves the data and another that counts. But in the debug log I got two identical queries that retrieves the data. So the second query is supposed to be like `SELECT (COUNT(*)) AS count FROM ...` in beforeFind method but it is not.

Partial stacktraces of both paginator queries.
The query that retrieves records:
```
App\Model\Table\MyTable::beforeFind() - APP/src/Model/Table/MyTable.php, line 153
Cake\Event\EventManager::_callListener() - APP/Vendor/cakephp/event/EventManager.php, line 352
Cake\Event\EventManager::dispatch() - APP/Vendor/cakephp/event/EventManager.php, line 329
Cake\ORM\Table::dispatchEvent() - APP/Vendor/cakephp/event/EventDispatcherTrait.php, line 113
Cake\ORM\Query::triggerBeforeFind() - APP/Vendor/cakephp/orm/Query.php, line 1108
Cake\ORM\Query::_execute() - APP/Vendor/cakephp/orm/Query.php, line 1137
Cake\ORM\Query::_all() - APP/Vendor/cakephp/datasource/QueryTrait.php, line 310
Cake\ORM\Query::all() - APP/Vendor/cakephp/orm/Query.php, line 1088
Cake\Datasource\Paginator::paginate() - APP/Vendor/cakephp/datasource/Paginator.php, line 186
```
The query that counts records:
```
App\Model\Table\MyTable::beforeFind() - APP/src/Model/Table/MyTable.php, line 153
Cake\Event\EventManager::_callListener() - APP/Vendor/cakephp/event/EventManager.php, line 352
Cake\Event\EventManager::dispatch() - APP/Vendor/cakephp/event/EventManager.php, line 329
Cake\ORM\Table::dispatchEvent() - APP/Vendor/cakephp/event/EventDispatcherTrait.php, line 113
Cake\ORM\Query::triggerBeforeFind() - APP/Vendor/cakephp/orm/Query.php, line 1108
Cake\ORM\Query::cleanCopy() - APP/Vendor/cakephp/orm/Query.php, line 868
Cake\ORM\Query::_performCount() - APP/Vendor/cakephp/orm/Query.php, line 919
Cake\ORM\Query::count() - APP/Vendor/cakephp/orm/Query.php, line 906
Cake\Datasource\Paginator::paginate() - APP/Vendor/cakephp/datasource/Paginator.php, line 188
```

### What you expected to happen

I suspect that the second query is altered after `beforeFind` is called in order to generate the count query and that is wrong.
I would expect to get Query object that generates `SELECT (COUNT(*)) AS count FROM ...` query (by PaginatorComponent) in beforeFind callback of the table class for the second paginator query.

**Comment by ADmad** [comment]
The issue is due to `Cake\ORM\Query::cleanCopy()` calling the `triggerBeforeFind()` method.

Triggering the before find callback when creating a clean copy definitely seems premature. Since the query would usually be modified after that and callback should be called with the updated query.

The exists in both CakePHP 3 and 4.

**Comment by othercorey** [comment]
Unfortunately, doesn't look like we can change this in 4.x. The way Query::count() is implemented, it cant handle some conditions added to the query after the call to cleanCopy(). 

This seems to be a work-around for some issues in the original implementation of count and matching.
