### ISSUE TITLE
Baking test for controller that use Authorization component

### ISSUE THREAD

**Issue by dlr4spotloc** [cakephp/cakephp#15168]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: All

### What you did
Bake a test for a controller that uses the Authorization component 

### What happened
Error: [InvalidArgumentException] Expected that `authorization` would be an instance of Authorization\AuthorizationServiceInterface, but got NULL ... AuthorizationComponent.php on line 238

### What you expected to happen
If controller has AuthorizationComponent loaded the  exception is thrown.

**Comment by markstory** [comment]
What command are you running that is failing like this?

**Comment by dlr4spotloc** [comment]
I do cake bake test controller "controlerName" --prefix "prefixName"
As i can understand, when baking test for a controller that uses Authorization component, the middleware method from Application was not called so the Auth service han not been created, so when issuing the request the exception i mentioned is triggered.

**Comment by ndm2** [comment]
What's the stacktrace for that error? IIRC that should only happen when you are running authorization checks in `Controller::initialize()`, which you most likely could move into `Controller::beforeFilter()`.

**Comment by dlr4spotloc** [comment]
Yes you're right,  if component loading is put in Controller::beforeFilter() that works. Maybe it might be useful to put it in documentation (?) and also the content management tutorial code should be updated as the Authorization component is loaded in Controller()::initialize().

**Comment by ndm2** [comment]
Loading the component in `initialize()` should be fine,  just don't do any authorization checks there.

By default the component shouldn't run any authorization on its own, unless `authorizeModel` is configured, but even then the automatic authorization check would by default happen in the `Controller.startup` event (this can be configured via the `authorizationEvent` option), which shouldn't be triggered when Bake instantiates the controller.

**Comment by AokuYuki** [comment]
I wanted to thank you @ndm2 
I followed the cookbook and put the skipAuthorization() into initialize() what of course led to the same error as @o-dlr-o had.
After i followed you advice an put that into beforeFilter() everything works fine! (I am using cakephp 4.3.11)
