### ISSUE TITLE
2.x ACL

### ISSUE THREAD

**Issue by kazoli** [cakephp/cakephp#15167]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.22

### Problem
In the ACL, users table group_id field is bound to aros table permission group so I have group level authentication.

I added a group_id field to the form (by open inspector of browser and added it like a hacker) and I posted it to the server, so my incoming post array ($this->request->data) is like the following: array('User' => array('any_field' => 'test', 'group_id' => 1));

After validation, I save data with the avoidance of malicious user interaction (https://book.cakephp.org/2/en/models/saving-your-data.html#model-clear) and no group_id among second fieldList array:
$this->User->save(array('id' => 1234, 'any_field' => 'test'), false, array('id','any_field'));

Because no group_id in second fieldList array, CakePHP has not changed the group_id in users table but in aros table the user's parent_id has changed to the id of the permission group, so user's permission group has changed to that I added to the form by the inspector.

Currently I can avoid this hacking by unsetting group_id from posted fields but this behaviour causes a vulnerability.

### What I expect
If I do not save intentionally the group_id into users table (ie. fieldList array contains group_id), CakePHP does not change user's permission group in aros table either.

**Comment by markstory** [comment]
Closing as 2.10 has reached end of support and will only receive security fixes going forward.
