### ISSUE TITLE
Log "info" only once.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#15171]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: master

### What you did

$this->log($string, 'info');

### What happened

Every log output gets written twice, ends up doubled then.
- info file
- debug file

Interesting enough not in notice, as well, though.

On our servers this creates tons of additional messages without benefit, making it more difficult to find the actual info one is looking for.

### What you expected to happen

https://github.com/cakephp/app/blob/master/config/app.php#L355
lists the levels info and debug, but one would expect them only ending up in one file, not in multiple.

Maybe the writing process could try to avoid the writing into both streams since the config channels them into "one" `debug` config?

**Comment by ADmad** [comment]
With the config provided in app skeleton app using `$this->log($string, 'info');` the message shows up only once in `debug.log`. You probably have another log config setup for `info` level.

**Comment by dereuromark** [comment]
They must be merging wrongly then in the app files.

**Comment by dereuromark** [comment]
I now know what the problem is, it is the merging...

I customized the debug into debug+info:
```php
 'Log' => [
        'debug' => [
            'className' => 'DatabaseLog.Database',
            'type' => 'debug',
            'levels' => ['notice', 'debug'],
        ],
        'error' => [
            'className' => 'DatabaseLog.Database',
            'type' => 'error',
        ],
        'info' => [
            'className' => 'DatabaseLog.Database',
            'levels' => ['info'],
            'scopes' => false,
            'file' => 'info',
        ],
```
But the merge then adds the "debug levels" in a way that they duplicate even.

This is the result:
```
^ array:8 [▼
  "debug" => array:7 [▼
    "className" => "DatabaseLog.Database"
    "file" => "debug"
    "url" => null
    "scopes" => false
    "levels" => array:5 [▼
      0 => "notice"
      1 => "info"
      2 => "debug"
      3 => "notice"
      4 => "debug"
    ]
    "type" => "debug"
  ]
  "error" => array:7 [▶]
  "queries" => array:5 [▶]
  "info" => array:4 [▼
    "className" => "DatabaseLog.Database"
    "levels" => array:1 [▼
      0 => "info"
    ]
    "scopes" => false
    "file" => "info"
  ]
```

My only workaround for now is to remove those keys from Configure before I merge in the actual custom config file.
