### ISSUE TITLE
What about https://medium.com/realmodelabs/sd-pwn-part-2-citrix-sd-wan-center-another-network-takeover-a9c950a1a27c

### ISSUE THREAD

**Issue by estebancano-dev** [cakephp/cakephp#15178]
Sorry, may be nothing, but need to know
CakePHP 2.x
https://medium.com/realmodelabs/sd-pwn-part-2-citrix-sd-wan-center-another-network-takeover-a9c950a1a27c

**Comment by garas** [comment]
Duplicate of https://github.com/cakephp/cakephp/issues/15163
