### ISSUE TITLE
URLs generated with arrays aren't working with IntegrationTestTrait

### ISSUE THREAD

**Issue by MrGrimpy** [cakephp/cakephp#15174]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: SLES 15.2, MySQL, using PHPUnit

### What you did
```php
$this->get(['_name' => 'home', 'lang' => 'en']);
```

### What happened
```php
App\Test\TestCase\Controller\AppControllerTest::testIsEnAlerte
RuntimeException: URL filter defined in /local/var/Projets/www/html/config/routes.php on line 37 could not be applied. The filter failed with: Argument 2 passed to Cake\Http\BaseApplication::{closure}() must be an instance of Cake\Http\ServerRequest, null given, called in /local/var/Projets/www/html/vendor/cakephp/cakephp/src/Routing/Router.php on line 353
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/Routing/Router.php:367
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/Routing/Router.php:460
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:135
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:106
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:495
/local/var/Projets/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:385
/local/var/Projets/www/html/tests/TestCase/Controller/AppControllerTest.php:27`
```

### What you expected to happen
Working test.

**Comment by dereuromark** [comment]
This must be something specific to your test harness and test bootstrapping process.
I do set up all my integration tests using array URLs, and they work so far.

Can you share more details on the tests setup?
Also, please double check with latest master.

I recommend you run the improved upgrade shell command "skeleton" of
https://github.com/dereuromark/upgrade#cakephp-upgrade-tool
or manually put all new skeleton files of cakephp/app into your project and diff it, maybe you forgot something to set up to run those as the tests expect.

**Comment by ADmad** [comment]
The relevant detail here is that he has URL filter setup for the routes. 

It's a chicken and egg problem. The `Router` passes the request instance to the URL filter callback but there's no request instance created yet and set to the router.

**Comment by MrGrimpy** [comment]
That's a different issue but I did have trouble using the upgrade tool mentionned in https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html. It would move files around but the rector commands wouldn't execute correctly. I had some errors related to --set is not a valid option or something. I had to install rector to my project and run the commands manually.

**Comment by markstory** [comment]
I don't think there is a way for this to be made to work as your route generation relies on a request existing, which isn't possible as the test runner needs to build your routes in order to build the request.
