### ISSUE TITLE
getMessage method undefined

### ISSUE THREAD

**Issue by djmenkveld** [cakephp/cakephp#15180]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: n/a

### What you did
I'm trying to setup a custom transport class following:
https://book.cakephp.org/4/en/core-libraries/email.html#creating-custom-transports

And I'm calling getMessage on the Message Class.

### What happened
And while I'm trying to access the getMessage() method (like in Mailer and others) the method through Message class throws:
`Call to undefined method Cake\Mailer\Message::getMessage()`

### What you expected to happen
That the actual class is available and accessible like explained in docs.

**Comment by ADmad** [comment]
There's `Cake\Mailer\Message::getMessage()` method so the error is expected. Looks that the `send()` code of one of the existing transports like `MailTransport::send()` to see how to get relevant data.
