### ISSUE TITLE
XSS backport fix for 3.next?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#15189]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
When upgrading an app to 4.x, I found some HTML markup to be escaped.
```php
<?php echo $this->Form->button($this->Format->icon('add') . ' ' . $labelText); ?>
```

### What happened
I needed this to make it work again:
```php
<?php echo $this->Form->button($this->Format->icon('add') . ' ' . $labelText, ['escapeTitle' => false]); ?>
```

### What you expected to happen
That means that this was already "wrong" in the 3.x code, and using this with e.g. user input (`$labelText`) would without knowing expose XSS vuln.
Should we fix that by escaping this element there by default, as well? So that it is in sync with 4.x behavior?

This should be done in 3.next then probably as this could break current apps (tradeoff between safe and BC).

**Comment by markstory** [comment]
Wouldn't changing the default escaping be a breaking change in 3.x though?

**Comment by dereuromark** [comment]
Sure, therefore 3.next with Migration guide.
I wasnt quite aware of the issue, and i am experienced in the templates of 3.x
So the security relevance could warrant this.

**Comment by markstory** [comment]
I agree that the behavior in 4.x is better as HTML escaping needs to be explicitly turned off, but backporting that change to 3.x now can create subtle and hard to find errors in applications which isn't something we've been doing in minor releases so far.

**Comment by dereuromark** [comment]
I wouldnt see 3.10 as a normal minor release, given that 4.x is long stable.
It should be more seen as an important compatibility release and can be clearly communicated that way

refs also
- https://github.com/cakephp/cakephp/pull/14846
etc
that should also be backported in the same way and communication.

**Comment by ADmad** [comment]
We can't just change the meaning of a minor release whenever we please. Not everything has to be backported. Minor release shouldn't add backwards incompatible changes unless necessary.

**Comment by dereuromark** [comment]
I disagree here as the balance of security relevance vs bc topics warrants this with a clear migration note. 
The fix outweighs the issues here IMO.
But since there is no clear consensus I will also not pursue it futher.
