### ISSUE TITLE
4.2 - Enable mocking/faking of services in test cases

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#15184]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.0

Testsuites can't easily replace services in the container. Being able to do so is important to realize many of the benefits of dependency injection. In a test case application developers need a simple way to replace or augment services with mocks or fakes.

```php
// Inside a test case.
$this->mockService(StripeService::class, function () {
     return new StripeFake();
});
```

The `mockService` method would register factory methods that would be attached to the container during application startup.

## Container Delegation

In order to append the mocks in a unobtrusive way, we need to make the application container a delegate of the testing container. This will require an addition event to be fired by the application class. The  `Application.buildContainer` event would be fired after building the application's container. Event listeners are able to modify the result of this event with a new container.

By listening to the above event, the test suite can do something like.

```php
function onBuildContainer($event)
{
    if ($this->mockServices) {
        $container = new Container();
        // Simplified
        $container->addMany($this->mockServices);
        $container->delegate($event->getSubject());
        $event->setResult($container);
    }
}
```

I think this will make working with services and the container in tests much easier than it is today.

Related to #14865

**Comment by ndm2** [comment]
I suppose the test could then overwrite the callback in order to gain full control over the new container?

And with delegates, we're going one step closer to tight `league/container` coupling? I know, I'm annoying 🙃 I don't really have a problem with tight coupling as long as it's clearly communicated that this is how it is.

**Comment by markstory** [comment]
> I suppose the test could then overwrite the callback in order to gain full control over the new container?

The callback in Application would be an event, and the test suite could listen to that event via the global listener. The test suite is already using the beforeRender event to gain access to template variables.

> And with delegates, we're going one step closer to tight league/container coupling? I know, I'm annoying upside_down_face I don't really have a problem with tight coupling as long as it's clearly communicated that this is how it is.

I don't know if we're necessarily becoming more coupled. The proposed interface that developers will use doesn't expose the container. How mocked services get into the application should be less important. The container the application registers services into wouldn't have a delegate either, as the delegation would be setup in the event listener which is triggered after the container is built.

**Comment by ndm2** [comment]
> The container the application registers services into wouldn't have a delegate either

Ah, of course, I somehow read that wrong, thinking the inner container would have to provide the delegation API 😴
