### ISSUE TITLE
Wrong URL generated with a string in `?`

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#15188]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: MacOS, NGINX, PHP 7.4, MySQL

### What you did
Generate url with query string in view
```
$this->Url->build(['controller' => 'Test', 'action' => 'sample', '?' => 'querystring']);
```

### What happened
Generated url is
```
/test/sample?0=querystring
```

### What you expected to happen
Generated url must be
```
/test/sample?querystring
```

**Comment by ADmad** [comment]
The querystring is built using `http_build_query()` which doesn't accept a string, hence the value for `?` is typecast to an array.

You can use `'?' => ['querystring' => '']` instead which will result in `/test/sample?querystring=`. But both `?querystring` and `?querystring=` get parsed into key values pairs in the same way.

**Comment by mcsknp** [comment]
There are problem when `querystring` is key value pairs such as `sample=value&something=any string`

**Comment by ADmad** [comment]
What problems? The space in `any string` in your example would need to be URL encoded (which is done by the router).

**Comment by mcsknp** [comment]
If `querystring` is `sample=value&something=any string`, above code

> `'?' => ['querystring' => '']`

will generate

```
?sample%3Dvalue%26something%3Dany%20string=
```

so `querystring` will not be passed.

**Comment by othercorey** [comment]
You don't pass the entire "string" of query parameters to `?`. You pass key-value pairs that generate a `key=value` string.

**Comment by ADmad** [comment]
Either use `parse_str()` to first convert the string `sample=value&something=any string` into key value pair, or simply concatenate the querysting to the URL after the call to `UrlHelper::build()`.

**Comment by dereuromark** [comment]
@mcsknp In general, always try to pass only an associative array into the array for URL generation:

```
'?' => $array
```
This will auto convert it to valid URLs.

The topic here is not a bugtracking ticket, for further help and consulting I would recommend the slack channel or forum.

**Comment by mcsknp** [comment]
> Either use `parse_str()` to first convert the string `sample=value&something=any string` into key value pair, or simply concatenate the querysting to the URL after the call to `UrlHelper::build()`.
I think it should be supported in `Route::match` because write same code everywhere before build url is not good idea.
