### ISSUE TITLE
CakePHP 2.x support PHP 8.0?

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#15197]
This is a (multiple allowed):

* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.X

**Comment by markstory** [comment]
There are no plans to update 2.x to support PHP8. CakePHP 2.x is scheduled to only receive security updates as of December 15 2020.

**Comment by EOM** [comment]
OK ;(

**Comment by bancer** [comment]
@EOM maybe we should make it compatible with PHP 8 in a fork if it would not require too many changes. I believe it would be much simpler to make 2.x compatible with PHP 8 than to migrate the entire project to 3.x. This would be quite a bummer if 2.x would be the only reason why we could use PHP 8 in our project.

**Comment by RyanTheDevGuy** [comment]
> @EOM maybe we should make it compatible with PHP 8 in a fork if it would not require too many changes. I believe it would be much simpler to make 2.x compatible with PHP 8 than to migrate the entire project to 3.x. This would be quite a bummer if 2.x would be the only reason why we could not use PHP 8 in our project.

@bancer do you know if this fork was ever created?

**Comment by bancer** [comment]
@fezzy2020 Not per my knowledge.

**Comment by kamilwylegala** [comment]
@bancer @fezzy2020 I actively maintain project that uses mix of CakePHP 2 and Symfony. Like you mentioned, moving to CakePHP 3.* is too expensive for me.

So I created a fork at the beginning of this year: https://github.com/kamilwylegala/cakephp2-php8 to support PHP 8.0.

I plan to migrate to PHP 8.1 in my project soon, so you can expect an update in my fork.

**Comment by osd84** [comment]
You are an hero, if you do that little month before i didn't jump on CakePHP 4.
Now i will stay here, for ever and ever...

**Comment by RyanTheDevGuy** [comment]
@kamilwylegala Amazing!

**Comment by vincent-fletcher** [comment]
@kamilwylegala - Thank you very much for providing this :)

**Comment by JoelFB** [comment]
@kamilwylegala can your fork only be used if we use Symfony as you do or this will work well for being able to support php8 on cake 2?

**Comment by kamilwylegala** [comment]
@JoelFB You can use fork alone just like you use original framework. Forks contains only necessary changes to support PHP8/8.1.

**Comment by JoelFB** [comment]
Please confirm that we do not need to use Symfony to make use of your fork @kamilwylegala 

Thank you
