### ISSUE TITLE
Cake4X isUnique() allowMultipleNull expected

### ISSUE THREAD

**Issue by Agacor** [cakephp/cakephp#15198]
* [ ] enhancement

* CakePHP Version:4x

### What you did
Saving an entity with RulesChecker isUnique(['key_a', 'key_b']) with multiple keys and some of them with null value.

### What happened
There is no option like Cake3X for allowMultipleNull.

### What you expected to happen
I was expected to have $options for the isUnique() Rule as Cake3. I think this could be forgotten in the migration to Cake4.

**Comment by markstory** [comment]
The allowMultipleNull option was removed in #13214

**Comment by markstory** [comment]
The option was deemed redundant because of improvements in how null conditions are handled. See https://github.com/cakephp/cakephp/pull/13214#discussion_r311835830 for the related discussion. It is also possible that our test suite did not cover the required scenarios well enough.
