### ISSUE TITLE
context parameter of error handler deprecated

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15195]
https://www.php.net/manual/en/function.set-error-handler.php

> Warning This parameter has been DEPRECATED as of PHP 7.2.0. Relying on it is highly discouraged.

The context parameter of error handler callback is currently used by ErrorHandler.

**Comment by othercorey** [comment]
This was removed in 8.0. We'll have to remove the context data.

> Warning
This parameter has been DEPRECATED as of PHP 7.2.0, and REMOVED as of PHP 8.0.0. If your function defines this parameter without a default, an error of "too few arguments" will be raised when it is called.

**Comment by othercorey** [comment]
This change causes a bug in the deprecations panel in debug kit since the $context was used to find the filename with the correct stack offset.

**Comment by markstory** [comment]
@othercorey The loss of $context leads me to think that the error callback idea we talked about before has some legs. I'll try to get a proposal for that together in the upcoming weeks.

**Comment by othercorey** [comment]
This should be fixed by the new error handler implementation.
