### ISSUE TITLE
Probleme when create Service 

### ISSUE THREAD

**Issue by arbims** [cakephp/cakephp#15206]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2 RC.
* Platform and Target: PHP 7.4

### What you did
```
namespace App\Service;

use Cake\Core\ContainerInterface;
use Cake\Core\ServiceProvider;
use PostsTable;


class PostService extends ServiceProvider {
    

    public function services(ContainerInterface $container): void
    {
        $container->add(PostsTable::class);
    }

    public function bootstrap(ContainerInterface $container): void
    {
        $container->add(PostsTable::class);
    }
}

namespace App\Controller;

use App\Service\PostService;
use PostsTable;

class PostsController extends AppController {

  
    public function index(PostService $postService)
    {
        $posts = $postService->find();
        dd($posts);
    }
}
```
### What happened
Could not resolve action argument postService. It has no definition in the container, no passed parameter, and no default value

**Comment by ADmad** [comment]
Have you used the `Application::services()` hook to add `App\Service\PostService` to the container?

**Comment by arbims** [comment]
Where is the file that manages the container to add this method

**Comment by markstory** [comment]
> Where is the file that manages the container to add this method

You can do this in `Application::services()` so `src/Application.php`

**Comment by arbims** [comment]
thank you that works but for example I need to call my postsTable directly without applying the TableRegistey each time how I can do it

**Comment by markstory** [comment]
@arbims You would need to register all the dependencies of the Table class too. There are a few of those which is why we recommend using the LocatorTrait or TableRegistry. You could also use a factory method in the container.

```php
$container->add(PostsTable::class, function() {
  return TableRegistry::get('Posts');
});
```

Doing this for all the tables in an application could be verbose though. We might need a better abstraction for this in the future if it becomes a common pattern.

**Comment by arbims** [comment]
Thank you 🙏🙏
