### ISSUE TITLE
cakephp 4.2 RC

### ISSUE THREAD

**Issue by arbims** [cakephp/cakephp#15202]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2 RC

Problem when execute php bin/cake.php

Class 'League\Container\Container' not found

**Comment by markstory** [comment]
Did you remember to `composer up`?

**Comment by ADmad** [comment]
@markstory They are probably using the zip archive for the release, which is missing league/container in the vendors folder.

**Comment by othercorey** [comment]
The 4.2 beta and rc releases don't have the packaged zip at all.

**Comment by markstory** [comment]
@othercorey I deleted the zipball after this issue was opened. I think we can close this now that the zipball is gone.
