### ISSUE TITLE
BelongsToMany not "replace" associated when foreignKeys are binaryuuid 

### ISSUE THREAD

**Issue by marianodonal** [cakephp/cakephp#15212]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: MAMP with MySQL.

### What you did
I'm trying to update belongstomany relations with saveStrategy "replace".
When i create new one everything goes well but when i try to update (ie: removing one related and leaving others) nothing happen.
In my PostsTable.php:
```
$this->belongsToMany('Therapies', [
      'foreignKey' => 'post_id',
      'targetForeignKey' => 'therapy_id',
      'joinTable' => 'posts_therapies',
    ]);
```
MySQL tables:
```
CREATE TABLE `posts` (
  `id` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0',
......,
  PRIMARY KEY (`id`)
)

CREATE TABLE `posts_therapies` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0',
  `therapy_id` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`id`)
)
```
PostsController.php:
```
public function edit($id = null)
  {
    $post = $this->Posts->get($id, ['contain' => ['Therapies']]);
    if ($this->request->is(['patch', 'post', 'put'])) {
      $post = $this->Posts->patchEntity($post, $this->request->getData(), ['associated' => [ 'Therapies']]);
      if ($this->Posts->save($post)) {
        $this->Flash->success(__('The post has been saved.'));
        return $this->redirect(['action' => 'index']);
      } else {
        $this->Flash->error(__('The post could not be saved. Please, try again.'));
      }
    }
    $therapies = $this->Posts->Therapies->find('list');
    $this->set(compact('post', 'therapies'));
  }
```

### What happened
Nothing happen when i try to update.
I've made some test without uuid as primary key and everything goes well, so i think is a matter of uuid.

### What you expected to happen
When i update a record with belongstomany related must unlink existing relations and create new ones.

**Comment by othercorey** [comment]
> Nothing happen when i try to update.

Do you mean post_therapies isn't updated or do you mean all Therapies assocations are removed?

**Comment by marianodonal** [comment]
Pivot table posts_therapies isn't updated. I think is not deleting related records before linking again.
