### ISSUE TITLE
2.x PHP 8 limitations

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#15210]
Hello folks,

[This commit](https://github.com/cakephp/cakephp/commit/b07bba4d4f6b37da104475eb7c2851a06b7f510f) states that 2.x will not support PHP 8 due to unsupported dependencies. Are the specific problems documented anywhere?

I support a large legacy application, and for us upgrading to 3.x/4.x is simply not practical. I would like to investigate the possibility of maintaining a fork of 2.x with PHP 8 support.

Thanks :)

**Comment by garas** [comment]
CakePHP 2.x uses PHPUnit 5 which is incompatible with PHP 8. Without running test suite, it is not even known where issues exist.

Upgrading PHPUnit would take too much work, it might introduce new non backward compatible changes, which we don't want for CakePHP 2.x anymore.

**Comment by bancer** [comment]
@garethellis36 Probably, my 5 cents here are too late, but... In our 2.x (partially migrated to 3.x) project we moved TestSuite classes from the core to our project folders and upgraded them to PHPUnit 9.5.5. We use PHP 7.3 and just recently fixed our tests and they pass in PHP 8.0 now. So another approach could be to move TestSuite classes to a plugin and upgrade them separately from other CakePHP core classes.

**Comment by garethellis36** [comment]
We actually ended up [forking the framework](https://github.com/icon-pcs/cakephp); I upgraded PHPUnit (and removed the custom test runner), and then added PHP 8 support. There are a few things that fail hard on PHP 8, or which behave slightly differently.

We've been running in production on our fork for a while and are going to be upgrading to PHP 8 shortly.

**Comment by osd84** [comment]
I don't use CakePhp 2.x i had to migrate all old apps.... it s was very unproductive task.... But **great job**, it's too difficult to folow cakephp versions updates. We will stay in cakephp4.2 now and fork it when support will stop. All new version functionality are not useful compare to code stability. Breaking change are unnecessary task... for developpers.
