### ISSUE TITLE
CakePHP 4 conver

### ISSUE THREAD

**Issue by mproenza** [cakephp/cakephp#15217]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6

### What I did
I'm trying to send a GET request to my endpoint, which contains query params.

**I need some params to contain a dot sign (.) in them**, for instance to express a condition for a filter, like:

`<endpoint_url>?ItemStates.state=approved` (notice the dot)

If I send a query like that, when I get the query params via `$request->getQuery()` in my server, it returns an array like:

`[ ItemStates_state: "approved" ]` (notice the dot changed to a _ )

### What I expected to happen

I expected to get an array like the one below when using `$request->getQuery()`:

`[ ItemStates.state: "approved" ]` (notice the dot)

Thanks!!

**Comment by markstory** [comment]
Have you looked at the `$_GET` super global? Does it have the dots?

**Comment by garas** [comment]
Dots and spaces in variable names are converted to underscores by PHP, not CakePHP. 

https://www.php.net/manual/en/language.variables.external.php
