### ISSUE TITLE
Function expression `ISNULL`

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#15214]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.6
* Platform and Target: Mac OS, NGINX, PHP7.2, SQLServer

### What you did
Generate sql function `ISNULL`

### What happened
I must write raw sql and no compatible with MySQL.
Or use `addCase`

### What you expected to happen
A function like below:
```
$query->func()->ifNull($field, $valueIfNull)
```

**Comment by ADmad** [comment]
`ISNULL` and `IFNULL` are two different functions. Based on your code example it seems you need the latter.

Currently you can use `$query->func()->ifnull([$field => 'identifier', $valueIfNull => 'literal'])` to achieve the same SQL expression as your example code, (which is supported through [FunctionsBuilder::__call()](https://api.cakephp.org/4.1/class-Cake.Database.FunctionsBuilder.html#__call)).

**Comment by ADmad** [comment]
`IFNULL` is not a standard SQL function, so it won't be added to the functions builder. Instead you can use `FunctionsBuilder::coalesce()` function which achieves the same.
