### ISSUE TITLE
RFC to add additional MIME types (KML / KMZ) to Cake\HTTP\Response MIME types

### ISSUE THREAD

**Issue by impronta48** [cakephp/cakephp#15213]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

### Proposal
Support KML / KMZ file types in order to avoid _Invoked extension not recognized/configured: kml_

### What happened
I try to define   $builder->setExtensions(['xls', 'json', 'kml', 'xml']);
but the KML extension is not recognized because it does not appear in protected $_mimeTypes

### What you expected to happen
I would like all valid extensions to be recognized, in particular common ones like KML.

### Version .2
Would be great to use an official updated source of mime types, such as
https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json
(more details here https://www.npmjs.com/package/mime-db)

**Comment by impronta48** [comment]
In the meanwhile I discovered that I could add extra mime types like this, in my controller
```php
  public function beforeFilter($event)
  {
    $this->response->setTypeMap('kml', ['application/vnd.google-earth.kml+xml']);
    parent::beforeFilter($event);

    if ($this->request->getParam('_ext') == 'kml') {
      $this->response = $this->response->withType('kml');
    }
  }
```
Is this the proper way to handle them?

**Comment by othercorey** [comment]
One issue we have with newer types is the lack of agreed extension to represent them. Those lists don't provide that.

**Comment by ADmad** [comment]
> Is this the proper way to handle them?

Yes it is.

**Comment by othercorey** [comment]
@impronta48 You can create a PR that adds kml and kmz types.
