### ISSUE TITLE
CounterCacheBehavior leads to wait lock timeout error with Mysql 8

### ISSUE THREAD

**Issue by liqueurdetoile** [cakephp/cakephp#15228]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.2
* Platform and Target: Debian 10 / PHP 7.4.11 / Mysql 8.0.22 (community)

### What you did and what happened
Within an app used as REST server, I'm using several counter cache behaviors on my models. Multiple instances are already working fine with Mysql 4.7.

When installing a new one with Mysql 8, I immediately got `wait lock timeout` errors when dealing with a model using counter cache behavior (well, in fact, I've spent some times to dig it up). It appears that the counter update request was blocking the whole transaction when saving an entity (and only one at once). For testing purposes, I've tried with many other models (usually, there's only one counter per model) and still the same issue.

It couldn't come from any requests overflow as the error was from the first save operations at install process within a wizard and only me was working on the server.

For experimentation sake, I decided to tweak CounterCache to use `afterSaveCommit` hook and it solves the issue. I can presume, the same trouble should occur for removals.

### What you expected to happen
I'm not very used to mysql config about transactions and I don't know exactly who is the culprit : do I miss something in my db server config (as far as I remember, I've didn't tweak anything so it should be the stock one) or does it rely in cakephp logic ?

I'm also remembering that I had the same error when removing many entities through multiple single requests, even with mysql 4.7 (1 removal per request). Maybe it is related ?

I'm definitely not very pleased with my solution as I presume that if counter update fails, the whole transaction should rollback to avoid flaws in counts.

**Comment by markstory** [comment]
How can someone go about reproducing this issue?

**Comment by liqueurdetoile** [comment]
@markstory Thanks for reply.

The plan can be to set up a minimalist app that fails on the same server and then port it to Github actions. I think I can use [`setup-mysql`](https://github.com/marketplace/actions/setup-mysql) to implement Mysql 8 in workflow. At least, it may show if issue can be reproduced elsewhere.

I may need some help as I was used to Travis and totally new to Github actions. Anyway, I've already planned to learn it to migrate my CI from Travis, so i should be a good start ^^.

What do you think about that plan ?

**Comment by othercorey** [comment]
We are asking how the models are setup to reproduce the situation.

**Comment by liqueurdetoile** [comment]
I see. My bad ^^

There's two kind of setups. All models are following Cakephp conventions.

## BelongsTo setup
Users belongs to Models. Users is initialized with :
```
$this->addBehavior('CounterCache', [
    'Models' => ['objects_count'],
]);
```

## BelongsToMany setup
Users belongs to many Roles through Affiliations. Affiliations is initialized with :
```
$this->addBehavior('CounterCache', [
    'Roles' => ['users_count'],
    'Users' => ['roles_count'],
]);
```
I've tried both link or directly creating an Affiliation entity and both fails.

Is it enough or do you need more ?

**Comment by markstory** [comment]
Thabks for providing the association setup. Having the schema of the relevant tables and what methods you are calling would be helpful.

**Comment by liqueurdetoile** [comment]
OK. I've setup a basic app with the 2 kinds of counter cache behavior : https://github.com/liqueurdetoile/test_mysql8.

It doesn't fail with `wait lock timeout` error on the same server the app does. I will close this issue for now and give more investigation on the whole schema. I'm now suspecting a kind of circular update with counters. I will check for that and report here for knowledge.

Thanks guys for the time given to my issue and all my apologies for the premature report.
