### ISSUE TITLE
Configure::write("debug", 1) not outputting sql command after reading Session.

### ISSUE THREAD

**Issue by neobie** [cakephp/cakephp#15225]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.23
* Platform and Target: PHP 7.2, Apache

After reading session like $this->Session->read('Auth.User.id') or $this->Auth->User('id') in AppController, the Configure::write('debug', 2) no longer working (not printing out the SQL command).

$this->Auth->User('id');
Configure::write('debug', 2); // no longer working

**Comment by markstory** [comment]
Closing as 2.x is no longer receiving bug fixes. We have supported 2.x since October 2011 and have [communicated](https://bakery.cakephp.org/2017/07/22/cakephp_2100_released.html) that it will receive only security fixes from December 2020 going forward.
