### ISSUE TITLE
Supporting NOT IN with nullable columns

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15224]
When you compare a column to a list of values using `NOT IN`, the result can be unexpected if the comparison is against `NULL`. In order to support a nullable column in the comparison, you have to add a separate condition when the column is null.

```
->where([
    'OR' => [
        ['nullable_column NOT IN' => ['value1', 'value2']],
        ['nullable_column IS' => null]
    ],
]);
```

Would it be possible to add an options to `notIn()` to automatically generate this conditions to support nullable columns.

**Comment by dereuromark** [comment]
Technically, a similar problem is also with != and normal comparison, if you have both empty string and NULL in our columns.
But that is probably a user problem.

**Comment by othercorey** [comment]
Is it possible to find the schema for a field in QueryExpression? All we have access to is the typemap which doesn't tell us whether the field is nullable.

**Comment by markstory** [comment]
Do we need the schema?

**Comment by othercorey** [comment]
You think it would be ok to generate that condition in all cases? It would make the query more complicated by default, but it's necessary when the column is nullable.

**Comment by markstory** [comment]
I think its a reasonable to generate the IS NOT fragment whenever there is a null in the value options.

**Comment by othercorey** [comment]
> I think its a reasonable to generate the IS NOT fragment whenever there is a null in the value options.

The issue is when the column is nullable. If the column contains the value `null` then it will fail the NOT IN check no matter what's in the list because SQL will perform a `null != value` check.

**Comment by markstory** [comment]
Ah ok, then auto-detecting when to add the null clause gets harder. Should this be a separate method on the builder? Something like `$exp->notInWithNull()`?
