### ISSUE TITLE
Unique field allow to be NULL

### ISSUE THREAD

**Issue by davidspeijer** [cakephp/cakephp#15223]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* Platform and Target: CentOS + MariaDB

### What you did
I have a Users table;

```
CREATE TABLE `users` (
  `id` int(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `firstname` varchar(50) DEFAULT NULL,
  `middlename` varchar(50) DEFAULT NULL,
  `lastname` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `lastlogin` datetime DEFAULT NULL,
  `published` BOOLEAN NOT NULL DEFAULT FALSE,
  `token` varchar(40) DEFAULT NULL,
  `locale` varchar(5) NOT NULL DEFAULT 'nl_NL',
  `superadmin` BOOLEAN NOT NULL DEFAULT FALSE,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  UNIQUE KEY (email),
  UNIQUE KEY (token)
);
```

with validator
```
        $validator
            ->scalar('token')
            ->maxLength('token', 40)
            ->allowEmptyString('token')
            ->add('token', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);
```

and build rules
```
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->isUnique(['email']), ['errorField' => 'email']);
        $rules->add($rules->isUnique(['token']), ['errorField' => 'token']);
        $rules->add($rules->existsIn(['company_id'], 'Companies'), ['errorField' => 'company_id']);

        return $rules;
    }
```

### What happened
when I try to reset the token to NULL and save the user to the database 

```
            $user = $this->Users->patchEntity($user, $this->request->getData());
            $user = $this->Users->patchEntity($user, ['token' => null]);
            //print_r($user);
            
            

            if ($this->Users->save($user)) {
                $this->getMailer('User')->send('resetPassword', [$user]);
                $this->Flash->success(__('Your password new password is saved.'));
                //return $this->redirect(['controller'=>'Users','action' => 'login']);
            } else {
                print_r($user);
            }
```

I get the error;

```
[[errors]] => Array
        (
            [token] => Array
                (
                    [_isUnique] => This value is already in use
                )

        )
```

### What you expected to happen
I expect that it allows by default to have multiple NULL values for the unique check.

**Comment by dereuromark** [comment]
Depending on how long 4.2 takes, this might have to go into 4.1 still as bugfix.

**Comment by markstory** [comment]
Changing the validation rule now will cause other applications to break. The most recent relevant change was in eed8df1ebd where the `allowMultipleNulls` option was removed. We might want to have a separate rule class to emulate the way SQL indexes on nullable fields work.

**Comment by othercorey** [comment]
I think we can support this with a simple option change to IsUnique that doesn't change default behavior.

We can add `areNullsUnique` that determines if a null value is compared against at all. Multiple columns can probably remove any columns with a null input from the check. I think that is how the db check works - but can verify with multi-column index.

This can be `false` by default and enabled for situations where we want to simulate db unique index better.

**Comment by davidspeijer** [comment]
Aren’t (most) databases allowing multiple nulls even when the field should be unique?

the logical way for me is that cake is following that path.

**Comment by othercorey** [comment]
> Aren’t (most) databases allowing multiple nulls even when the field should be unique?

Yes, except for Sql Server.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15226
