### ISSUE TITLE
Localization for plugins with complex namespace

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#15237]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Hi, I have created a first plugin called `MeCms` and which has this namespace. In essence it is a CMS.
Now I am creating plugins for the plugin, i.e. to extend its functionality. The first plugin has the `MeCms\Photos` namespace.

Everything seems to work perfectly: the plugin is loaded correctly by the main plugin; controller, view, model, routes... everything works, except localization.
Everything seems ok: the `me_cms_photos.po` file exists and is in the right path. CakePHP does not "complain" about anything, rightly because a localization might not exist (and it doesn't find it).

I imagined that the problem might be due to the slash, also because in this case the domain syntax should be `my_plugin` (and in fact for my plugin it is `me_cms_photos`).
So I did a lot of debugging and eventually figured out where the problem is:
https://github.com/cakephp/cakephp/blob/master/src/I18n/MessagesFileLoader.php#L173

The domain `me_cms_photos` will obviously generate the expected plugin name `MeCmsPhotos`, which will turn out not even loaded.
So the search paths will be just the app directories.
**This seems to me correct on CakePHP's part.**

Now, how to do it? I tried adding the slash in the domain name (`me_cms/photos`). The plugin name is now understood correctly. The problem, however, is that the name of the expected file changes, which will now be just `photos.po` (obviously the `me_cms/photos.po` file could never exist). But the path is right.
By renaming the `.po` file... yes, now localization works too. I also noticed that the same happens with the dot in domain notation (so `me_cms.photos`).

Instead, when trying to generate the `.pot` file from shell, the plugin name is correctly interpreted, but the generated file name will be wrong. So:
```
bin/cake i18n extract --plugin MeCms/Photos
```
will create the `me_cms_photos.pot` file, which, as mentioned, will not be considered (in fact I didn't choose that name). And of course it will look for the same domain (`me_cms_photos`), which is incorrect.

All of this is not documented in the CookBook and it seems to me that this behavior is neither intended nor considered.

**Comment by dereuromark** [comment]
I had similar concerns when adding an autocomplete task for the IdeHelper plugin.
See https://github.com/cakephp/docs/pull/6585

**Comment by markstory** [comment]
Do you think it would be better if the domain file was normalized to `me_cms_photos.po`? I don't think we have much in the way of tests/documentation around how translation files for namespaced plugins should work, so minor behavior variances could be introduced in the next minor release.

**Comment by ADmad** [comment]
> so minor behavior variances could be introduced in the next minor release.

That would be a BC break for plugins like [cakedc/user](https://github.com/CakeDC/users/tree/master/resources/locales) which include po/pot files.

**Comment by ADmad** [comment]
Since using `me_cms/photos` as domain name in code and having `photos.po` file works we can just update the bake task to drop the vendor name prefix when generating `.pot` files.

**Comment by mirko-pagliai** [comment]
I don't know how to "normalize" the situation. But it seems to me that the problem exists.

I try to recap.

The plugin name is `MeCms/Photos` and its namespace is `MeCms\Photos`.

The command
```
bin/cake i18n extract --plugin MeCms/Photos
```
will search for the `me_cms_photos` domain and will generate the `me_cms_photos.pot` file.
**This is probably what is wrong**.

After, however
```
__d('me_cms_photos', 'a string');
```
won't work, because it look for the `me_cms_photo.po` file for the `MeCmsPhotos` plugin (which doesn't exist).

Instead Cake would like to have the `photo.po` file and the `me_cms/photo` (or `me_cms.photo`) domain.

**Comment by ADmad** [comment]
The command does seem to have the code for removing vendor prefix when generating file name but it seems it's not working as expected.

https://github.com/cakephp/cakephp/blob/ef6f30be22ab65bc7da4f20a615979b13fd9e859/src/Command/I18nExtractCommand.php#L634-L638

**Comment by ADmad** [comment]
Hmm... Actually there is a test showing that the vendor prefix is removed.

https://github.com/cakephp/cakephp/blob/ef6f30be22ab65bc7da4f20a615979b13fd9e859/tests/TestCase/Command/I18nExtractCommandTest.php#L296-L312

**Comment by mirko-pagliai** [comment]
Ok, so it looks like I just got it wrong by initially using a wrong domain name and there is no bug.
