### ISSUE TITLE
4.2.0 - Foreign key constraint error at fixtures creation when not loading fixtures for all referenced tables

### ISSUE THREAD

**Issue by liqueurdetoile** [cakephp/cakephp#15234]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.0
* Platform and Target: Mysql 4.7 with innodb tables

### What you did
For speed sake, I'm used to load only relevant fixtures in my unit tests. Therefore, some associated tables are not created if no data is needed from them. It can make a huge boost difference with central models like `users` that can be referenced in several other tables.

### What happened
When upgrading to 4.2.0, tests start failing with `SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint error.` When adding the "missing" fixtures, it works. Reverting to 4.1.7 also solved the issue.

### What you expected to happen
No foreign key constraint error for unused fixtures.

**Comment by othercorey** [comment]
We need more information on the fixtures you're loading that cause this error.

**Comment by liqueurdetoile** [comment]
The schema is simple : 
- Users has many Deployments (and reverse belongsTo)
- Creleases has many Deployments (and reverse belongsTo)
- Sreleases has many Deployments (and reverse belongsTo)

Fixtures are all baked from db and Deployments references user_id, crelease_id and srelease_id as FK :
```
public $fields = [
        'id' => ['type' => 'uuid', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'user_id' => ['type' => 'uuid', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'crelease_id' => ['type' => 'uuid', 'length' => null, 'null' => true, 'default' => null, 'comment' => '', 'precision' => null],
        'srelease_id' => ['type' => 'uuid', 'length' => null, 'null' => true, 'default' => null, 'comment' => '', 'precision' => null],
        'cconstraint' => ['type' => 'string', 'length' => 45, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'sconstraint' => ['type' => 'string', 'length' => 45, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'domain' => ['type' => 'string', 'length' => 100, 'null' => false, 'default' => null, 'collate' => 'utf8mb4_general_ci', 'comment' => '', 'precision' => null],
        'islocked' => ['type' => 'boolean', 'length' => null, 'unsigned' => false, 'null' => false, 'default' => '0', 'comment' => '', 'precision' => null],
        'sass' => ['type' => 'boolean', 'length' => null, 'unsigned' => false, 'null' => false, 'default' => '1', 'comment' => '', 'precision' => null],
        'standalone' => ['type' => 'boolean', 'length' => null, 'unsigned' => false, 'null' => false, 'default' => '0', 'comment' => '', 'precision' => null],
        'ipv4' => ['type' => 'string', 'length' => 15, 'null' => true, 'default' => null, 'collate' => 'utf8mb4_general_ci', 'comment' => '', 'precision' => null],
        'ipv6' => ['type' => 'string', 'length' => 39, 'null' => true, 'default' => null, 'collate' => 'utf8mb4_general_ci', 'comment' => '', 'precision' => null],
        'created' => ['type' => 'datetime', 'length' => null, 'precision' => null, 'null' => true, 'default' => null, 'comment' => ''],
        'modified' => ['type' => 'datetime', 'length' => null, 'precision' => null, 'null' => true, 'default' => null, 'comment' => ''],
        '_indexes' => [
            'fk_deployments_users_idx' => ['type' => 'index', 'columns' => ['user_id'], 'length' => []],
            'fk_deployments_sreleases1_idx' => ['type' => 'index', 'columns' => ['srelease_id'], 'length' => []],
            'fk_deployments_creleases1_idx' => ['type' => 'index', 'columns' => ['crelease_id'], 'length' => []],
        ],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
            'domain_UNIQUE' => ['type' => 'unique', 'columns' => ['domain'], 'length' => []],
            'fk_deployments_users' => ['type' => 'foreign', 'columns' => ['user_id'], 'references' => ['users', 'id'], 'update' => 'noAction', 'delete' => 'cascade', 'length' => []],
            'fk_deployments_sreleases1' => ['type' => 'foreign', 'columns' => ['srelease_id'], 'references' => ['sreleases', 'id'], 'update' => 'noAction', 'delete' => 'setNull', 'length' => []],
            'fk_deployments_creleases1' => ['type' => 'foreign', 'columns' => ['crelease_id'], 'references' => ['creleases', 'id'], 'update' => 'noAction', 'delete' => 'setNull', 'length' => []],
        ],
        '_options' => [
            'engine' => 'InnoDB',
            'collation' => 'utf8mb4_general_ci'
        ],
    ];
```

If I use Deployments fixture in a test, I must load fixtures for ALL referenced tables (Users, Creleases, Sreleases) or deployments table creation fails since 4.2.0 :

```
Exception: Unable to create constraints for fixture "App\Test\Fixture\DeploymentsFixture" in "App\Test\TestCase\Model\Table\UsersTableTest" test case:
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

As use case, I have a custom finder on users that reduce deployments to a single `domains` property on User entity. To unit test it, I used to load only 'app.Users' and 'app.Deployments' fixtures as no other data is needed.

This test is now failing with 4.2.0 unless I add the two releases fixtures. When reverting to 4.1.7, it succeeds again.

**Comment by othercorey** [comment]
How would you expect foreign key creation to work without the target table?

**Comment by liqueurdetoile** [comment]
Obviously, it's not on Mysql side. Perhaps "unused" foreign keys constraints were not added prior 4.2.0 ?

Anyway, here's the capture from console :

```
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 2 updates, 1 removal
  - Removing aura/intl (3.0.0)
  - Installing league/container (3.3.3): Downloading (100%)
  - Updating cakephp/cakephp (4.1.7 => 4.2.0): Downloading (100%)
  - Updating cakephp/debug_kit (4.3.9 => 4.4.1): Downloading (100%)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
52 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed

> "vendor/bin/phpunit" --filter UsersTableTest
PHPUnit 8.5.13 by Sebastian Bergmann and contributors.

Exception: Unable to create constraints for fixture "App\Test\Fixture\DeploymentsFixture" in "App\Test\TestCase\Model\Table\UsersTableTest" test case:
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
In [F:\Projets\XXX\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 331]

> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 2 updates, 1 removal
  - Removing league/container (3.3.3)
  - Installing aura/intl (3.0.0): Loading from cache
  - Downgrading cakephp/cakephp (4.2.0 => 4.1.7): Loading from cache
  - Downgrading cakephp/debug_kit (4.4.1 => 4.3.9): Loading from cache
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
51 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed

> "vendor/bin/phpunit" --filter UsersTableTest
PHPUnit 8.5.13 by Sebastian Bergmann and contributors.

..........                                                        10 / 10 (100%)

Time: 8.53 seconds, Memory: 14.00 MB

OK (10 tests, 17 assertions)
```

The fixtures are loaded in UsersTableTest. php like so :
```
protected $fixtures = [
    'app.Users',
    'app.Deployments',
];
```

If I push `app.Creleases` and `app.Sreleases` in fixtures, it works again under 4.2.0 but test duration doubles from 8.5 seconds to 17 seconds (I know my dev Mysql server is a brave and brilliant turtle but overhead is a reality).

**Comment by othercorey** [comment]
So you want the foreign key constraints to be created only if the target table exists and not throw an error?

**Comment by liqueurdetoile** [comment]
It seems it was the regular behavior before 4.2.0, wasn't it ? It's kinda breaking change, at least for me, as it implies rewriting fixtures in test cases.

For test duration, it's really relevant to avoid time overhead in my opinion, especially with minutes based CI/CD.

I found the commit that changed behavior : 963eeaebe93294eb52b7a83a6ff6d3d135bf3045. Prior this one, constraints  checks were disabled for all callbacks. By now, it's only disabled at fixture insertion.

A quick fix could be to call the "create constraints" callback in transactional mode to restore previous behavior.

Another one is to check through $tableCache (that is passed to callback and can be then passed by `crateConstraints`) if target table for FK is in schema. Both are working when tested in dirty mode. Pro is malformed FK in fixtures will be detected from tests.

Both are working in dirty quick tests.

Aside this, it makes me think it can be a nice feature to be able use `TestCase::loadFixtures` to add on-the-fly seldom used fixtures in whole test case in order to optimize fixtures setup.

I can submit a PR for the fix and/or on-the-fly fixtures loading if you find it useful.

**Comment by othercorey** [comment]
The side-effect of running the DLL in the transaction callback wasn't really on purpose. We aren't specifically trying to support invalid constraints in the schema. I think adding flags to support that would be unnecessarily complex.

You can use `loadFixtures()` as you mentioned, but it has to be called for each test case.

If you're seeing such a huge overhead for a few tests, do your fixtures have a large number of records?

**Comment by liqueurdetoile** [comment]
If FK checks is not an issue, a wrap in `disableConstraints` of the callback calls in the else part of `runPerFixture` should also restore previous behavior and no additional flags is needed as well.

Loadfixtures doesn't actually mix with autofixtures. What I propose is the possibility to also use autofixtures and loadFixtures to only load additional fixtures when it's relevant without manually loading same fixture(s) in all tests. It can also be called `addFixtures` to avoid confusion.

There's only 1 to 4 records inserted per fixture. The poor performance for raw duration value is mostly due to my dev server. It takes ages on it for handling table creation./dropping/truncating. Nevertheless, Create/Truncate/Drop statements [are still cost intensive with InnoDB](https://www.percona.com/blog/2011/12/22/optimizing-innodb-for-creating-30000-tables-and-nothing-else). Moreover, in another huge project, I managed to cut by 4% time taken by whole test suite on Gitlab CI/CD only by splitting test case based on fixtures used. Sounds like not a big deal but it is really worthy when struggling with free 400 minutes/month Gitlab fee for pipelines.

**Comment by othercorey** [comment]
> If FK checks is not an issue, a wrap in `disableConstraints` of the callback calls in the else part of `runPerFixture` should also restore previous behavior and no additional flags is needed as well.

I'm sorry, but I don't think we're going to restore this. The constraint behavior you describe does not work for all databases and we consider a TestCase setup like this a bug.

However, if you really want it to behave like this, you can override the FixtureManager created.

https://github.com/cakephp/app/blob/45fc99022b231b06c003af747a46ffaf2c8517f5/phpunit.xml.dist#L25

> 
> Loadfixtures doesn't actually mix with autofixtures. What I propose is the possibility to also use autofixtures and loadFixtures to only load additional fixtures when it's relevant without manually loading same fixture(s) in all tests. It can also be called `addFixtures` to avoid confusion.

I think `loadFixtures` could be improved. However, you would have to control *all* fixtures loaded for a test together otherwise you will still have constraint failures.

**Comment by liqueurdetoile** [comment]
@othercorey Thanks for reply and your time. I didn't know the trick of custom fixtures manager in phpunit config. Great thing ^^

Anyway, I'm still thinking it's definitely a breaking change. I found [this thread](https://github.com/cakephp/cakephp/issues/4461) that elaborates on FK constraints issues for fixtures. It was maintained til 4.2.0. Why dropping it now ?

Moreover, I can't understand why using it in non transactional context is problematic as `enableForeignKeySQL` and `disableForeignKeySQL`, that are used under he hood by `disableConstraints`, are mandatory by `DriverInterface` and implemented by all core database drivers ?

If you agree, I propose to create a PR that you can review and discuss.

I will also propose a second one for the on-the-fly loading as an improvement to `loadFixtures`.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15253
