### ISSUE TITLE
4.2.0 Non empty action params

### ISSUE THREAD

**Issue by ludeus** [cakephp/cakephp#15236]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.0 | 4.2.1 | master
* Platform and Target: Ubuntu 20.04LTS

### What you did
```
<?php

namespace App\Controller;

class FooController extends AppController
{
    public function bar(...$baz)
    {
        var_dump($baz);
    }
}
```

### What happened

null value in key 0

```
src/Controller/FooController.php:9:
array(1) {
  [0] =>
  NULL
}
```

### What you expected to happen

Expected same as previous versions of cake.  
ex: CakePHP 4.1.7:
```
src/Controller/FooController.php:9:
array(0) {
}
```

**Comment by markstory** [comment]
What does the route for this controller action look like? And what is in `$this->request->getAttribute('params')`?

**Comment by ludeus** [comment]
I used the skeleton app

```
src/Controller/FooController.php:10:
array(6) {
  'controller' =>
  string(3) "Foo"
  'action' =>
  string(3) "bar"
  'pass' =>
  array(0) {
  }
  'plugin' =>
  NULL
  '_matchedRoute' =>
  string(24) "/{controller}/{action}/*"
  '_ext' =>
  NULL
}
```

**Comment by ludeus** [comment]
I tried this :
```
    public function testNull($attr)
    {
        var_dump($attr);
    }
```
version >= 4.2.0 -> output NULL
version 4.1.7 -> `Error: Too few arguments to function App\Controller\FooController::testNull(), 0 passed`

**Comment by markstory** [comment]
Thanks! I can get this fixed.
