### ISSUE TITLE
Inconsistent array types between PoFileParser and Package lead to TypeError

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#15231]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.0
* Platform and Target: PHP 7.4.5, IntegrationTestTrait, PhpUnit 9.4.2

### What you did
Upgraded from cakephp 4.1 to 4.2. Ran one of my integration tests that calls an API endpoint that throws an exception

### What happened
error500.php tries to render. it therefore tries to fetch some message from the PO file which fails with a type error

```
2020-12-21 17:46:00.669 Error: [TypeError] Argument 2 passed to Cake\I18n\Package::addMessage() must be of the type string, array given, called in /var/www/vendor/cakephp/cakephp/src/I18n/Translator.php on line 98 in /var/www/vendor/cakephp/cakephp/src/I18n/Package.php on line 85
Stack Trace:
- /var/www/vendor/cakephp/cakephp/src/I18n/Translator.php:98
- /var/www/vendor/cakephp/cakephp/src/I18n/Translator.php:123
- /var/www/vendor/cakephp/cakephp/src/I18n/functions.php:98
- /var/www/templates/Error/error500.php:41
- /var/www/vendor/cakephp/cakephp/src/View/View.php:1176
- /var/www/vendor/cakephp/cakephp/src/View/View.php:1134
- /var/www/vendor/cakephp/cakephp/src/View/View.php:764
- /var/www/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:438
- /var/www/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:416
- /var/www/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:407
- /var/www/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:281
- /var/www/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:143
- /var/www/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:125
- /var/www/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /var/www/vendor/cakephp/cakephp/src/Http/Server.php:90
- /var/www/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:142
- /var/www/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:470
- /var/www/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php:356
- /var/www/plugins/Rest/tests/TestCase/Controller/MyControllerTestControllerTest.php:131
- /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:1536
- /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:1142
- /var/www/vendor/phpunit/phpunit/src/Framework/TestResult.php:730
- /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:883
- /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
- /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
- /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
- /var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
- /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:148
- /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:101
- /var/www/vendor/phpunit/phpunit/phpunit:61


```
### What you expected to happen
standard 500 error page being rendered

### Investigations
CakePHPs `PoFileParser::parse` returns a complex array structure. `MessagesFileLoader:142` takes this complex, multi-dimensional array structure and calls `$package->setMessages($messages)` with it. The later expects a much simpler `string[]`. Because of PHPs lack of strict array types, this error propagates: the bad typed messages array is persisted in Package::$messages, which causes `Package::getMessage($key)` to return the wrong type (`array` instead of `string`) when being called by the `Translator::getMessage(string $key)`. This all works fine until `Translator::getMessage(string $key)` tries to call `$this->package->addMessage($key, $message)` which expects parameter 2 to be a string, but an array is provided.

**Comment by markstory** [comment]
Do you have an example of a po/more file that cause this problem?

**Comment by BGehrels** [comment]
https://app.oyaso.com/rest/translations

When i rewrite `Package::setMessages` to
```
public function setMessages(array $messages): void
    {
        foreach ($messages as $message) {
            if (!is_string($message)) {
                throw new InternalErrorException(json_encode($message));
            }
        }
        $this->messages = $messages;
    }
```

I see the following in the logs:

```
   {
        "_context": {
            "": "en"
        }
   }
```

**Comment by markstory** [comment]
I wasn't able to reproduce this problem locally. I copied the translations file you provided `resources/locales/en_US/default.po` to my local application and added:

```php
<?= __('actions.ok') ?>
```
to a template. It was translated properly. Have you tried clearing the cache on your application?

**Comment by dereuromark** [comment]
https://github.com/cakephp/debug_kit/issues/811 seems to have the same issue, with sqlite db and cache cleared etc.

**Comment by bor-attila** [comment]
Please try this, this to reproduce the error:

1. Create a translatable string: __('string');
2. create a pot file with _bin/cake i18n_ then create a po file with Poeditor (default.po)
3. translate it (create a mo file)
4. modify the __('string') to __d('domain', 'string')
5. create a pot file with _bin/cake i18n_ for the _domain_ then create a po file with Poeditor (domain.po)
6. translate it (create a mo file)

You should see the error. So, you must have the same string in two different files (default.mo and domain.mo).

**Comment by BGehrels** [comment]
Thank you a lot once again for the amazingly fast fix and your great work here!

**Comment by LordSimal** [comment]
For those who can't wait till the this patch is released in a version:

Adjust your composer.json to have this set `"cakephp/cakephp": "dev-issue-15231 as 4.2",` 
and perform a `composer update`

**Comment by dereuromark** [comment]
You mean dev-master.

**Comment by LordSimal** [comment]
Ah sure since it is already merged into master

**Comment by markstory** [comment]
Thank you for the detailed steps @bor-attila. I will get another release out this week.
