### ISSUE TITLE
December 30-31 is shown as next year

### ISSUE THREAD

**Issue by BillWebStudio** [cakephp/cakephp#15235]
hi guys!

I have a strange issue with showing dates like 2018-12-30 or 2018-12-31. Which are saved into MySQL database correctly as DATE.
But when I print it back to HTML like echo $book->release_date; I'm getting 2019-12-30 or 2019-12-31 (same date but next year). If any year is selected - next year got.
Though the debug shows this:
[release_date] => Cake\I18n\FrozenDate Object
        (
            [time] => 2018-12-30 00:00:00.000000+00:00
            [timezone] => UTC
            [fixedNowTime] => 
        )
This issue does not happen on any other dates except December 30-31
settings are:
FrozenDate::setToStringFormat('MM/dd/YYYY');
Date::setToStringFormat('MM/dd/YYYY');

Best regards,
Alex

**Comment by ADmad** [comment]
Use `LL` instead of `MM` http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax

**Comment by othercorey** [comment]
I think this might be due to `YYYY` instead of `yyyy`.

**Comment by ADmad** [comment]
> I think this might be due to YYYY instead of yyyy.

Actually yes. Basically `LL` and `yyyy` are the equivalent ICU placeholders for `M` and `Y` respective for PHP's `date()` placeholders.

**Comment by BillWebStudio** [comment]
thanks for help. yyyy solved the problem
