### ISSUE TITLE
Order fixtures automatically by dependencies

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#15246]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.0
* MariaDB Version 10.3

This is related to #15243 
Without disabling foreign key checks fixtures must be created in the order of FK constraints (and drop'ed in the reverse order).
When I import them from database with
  $import = ['model' => 'MyModel']
the FixtureManager could know the order of dependencies, i.e. the belongsTo or hasMany associations, and sort them accordingly so I don't have to do it manually in the test case.

**Comment by othercorey** [comment]
Yes, this will likely need to be done to resolve the issue. Again, we seem to be missing a test scenario probably due to lack of foreign key constraints in many of the core fixtures.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15253
