### ISSUE TITLE
Fixtures are not dropped before and after a test run

### ISSUE THREAD

**Issue by chtheis** [cakephp/cakephp#15243]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.0
* Database: MariaDB 10.3

### What you did
In a test case I load several fixtures, the schema is "import"ed from database. 

### What happened
Neither after the test nor at the start before setting up fixtures the tables are dropped from DB.
Debugging reveals that drop fails because of foreign key constraints still in place.

### What you expected to happen
That a test case starts with an empty DB :) 
It worked with prior versions and started to fail after I updated to 4.2.0.

I'm not sure if this is related to #15234 or not. In contrast to that bug I don't have (or so I believe) unmet FK constraints.

When I set $transactional to true in  FixtureManager::runPerFixture tables are dropped as expected.

**Comment by othercorey** [comment]
I think we're missing a test case for this. Are you seeing an error when this happens? I'd like to confirm we produce the same error when testing.

**Comment by chtheis** [comment]
Not in the log, but debugging I see that an exception is thrown (un-met FK constraint) and caught. No further handling there, just a return false. It happens in TestFixture::drop.
I think all you'd need to test are 2 (managed) fixtures related by FK and a test case using them.

Btw., FixtureManager::_setupTable checks for "!method_exists(..., 'isManaged') || isManaged()" when to drop and create the fixture. But in shutDown it checks for "method_exists(..., 'isManaged') && isManaged()" when to drop.
Is this behavior, if the method does not exist, correct? In _setupTable it will drop and create, but in shutDown it will just truncate? Not that this really matters, the method will always exist I assume.

**Comment by othercorey** [comment]
Thanks for the info! I'm sure we need to adjust and fix this.

How did you notice the problem if you don't see an error in any logs? Does it fail to re-create the tables in a later test?

**Comment by chtheis** [comment]
I meant the test leaves the tables behind without any errors. So the first run is OK, but then the second run will fail with:
Warning Error: Fixture creation for "groups" failed "SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'groups' already exists"

**Comment by chtheis** [comment]
One problem may be that at the end of the test the tables are dropped in the same sequence than they are created. But if my sequence is as I need it to create the tables they shall be dropped in the reverse order.

And, to emphasize, I use 
  $import = ['model' => 'MyModel']
to define the fixture / table structure, without explicit constraints in the fixture definition.

**Comment by othercorey** [comment]
I have a solution in mind for you, but it seems you're running into an edge case somehow. 

I don't see how you reach the end of the test suite with constraints still in place. Does this always happen? Does it only happen when a test fails? Anything like that?

**Comment by chtheis** [comment]
It always happens, even if I run only one test. The test itself is OK but the DB is not cleaned.
I put a breakpoint on TestFixture::dropConstraints and it seems that the member _constraints is empty, despite that constraints exist. Is it possible that the Fixture doesn't know about the constraints because I get them implicitly from the model and don't define them explicitly as such?

**Comment by othercorey** [comment]
It must be an issue with reflecting/describing the constraint in the imported table. Would it be possible to show the sql you use to create the constraint?

**Comment by chtheis** [comment]
I don't create them explicitly. Not at that time. Instead I used phpMyAdmin at that time to create my tables.

I checked what happens in Fixture: when setting up it imports the schema which contains a key 'constraint' (or so), but the entire structure is then put into the member '_table' and '_constraints' is left alone. dropConstraints only checks for _constraints and not what may be in _table so it misses the constraints.

**Comment by othercorey** [comment]
Perfect, thank you. Definitely looks like we're improperly importing constraints. I should be able to test this properly now.

**Comment by chtheis** [comment]
Thanks a lot! :)

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15253
