### ISSUE TITLE
On associations, Cake looks for plural column name while it should be singular

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15255]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.7
* Platform and Target: Windows 10 (XAMPP) PHP 7.2, 10.1.35-MariaDB

### What you did

**Proceedings Model**
```php
$this->hasOne('Complaints');
```
*NOTE: If I add `'foreignKey' => 'proceeding_id'` it works.*

**ComplaintsTable Model**
```php
$this->belongsTo('Proceedings', [
    'foreignKey' => 'proceeding_id',
    'joinType' => 'INNER',
]);
```
*NOTE: If I remove `'foreignKey' => 'proceeding_id'` it looks for `proceedings_id` (plural) and fails.*

**Proceedings Controller**
```php
$proceedings = $this->Proceedings->get($id, [
    'contain' => ['Complaints'],
]);
```

### What happened

**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Complaints.proceedings_id' in 'on clause'**

Cake is looking for `proceedings_id` (in plural) but it does not exists. The actual column is, must be and is configured as singular: `proceeding_id` 

**Generated SQL**
```sql
SELECT Proceedings.id AS Proceedings__id, Proceedings.code AS Proceedings__code, Proceedings.reference AS Proceedings__reference, Proceedings.title AS Proceedings__title, Proceedings.status AS Proceedings__status, Proceedings.created AS Proceedings__created, Proceedings.modified AS Proceedings__modified, Proceedings.deleted AS Proceedings__deleted, Complaints.id AS Complaints__id, Complaints.proceeding_id AS Complaints__proceeding_id, Complaints.user_id AS Complaints__user_id, Complaints.type AS Complaints__type, Complaints.source AS Complaints__source, Complaints.relationship AS Complaints__relationship, Complaints.events_place AS Complaints__events_place, Complaints.events_date AS Complaints__events_date, Complaints.events_time AS Complaints__events_time, Complaints.text AS Complaints__text, Complaints.people AS Complaints__people, Complaints.already_submitted AS Complaints__already_submitted, Complaints.company_visible AS Complaints__company_visible, Complaints.hash AS Complaints__hash, Complaints.created AS Complaints__created, Complaints.modified AS Complaints__modified, Complaints.deleted AS Complaints__deleted FROM proceedings Proceedings LEFT JOIN complaints Complaints ON (Proceedings.id = (Complaints.proceedings_id) AND Complaints.deleted IS NULL) WHERE (Proceedings.id = :c0 AND Proceedings.deleted IS NULL) LIMIT 1
```

### What you expected to happen
ORM should look for `Complaints.proceeding_id` (singular) instead of `Complaints.proceedings_id` [as stated in the Cookbook](https://book.cakephp.org/4/en/orm/associations.html#hasone-associations)

## PS:
I also opened a DIFFERENT issue between this two tables on Nov, 10. **It was closed** but I think it was misunderstood. If you read carefully and if you read my reply, you will understand why it may be an actual bug:

Cake baked a BelongsTo association with `Complainants` while that table DOES NOT exist (the actual table is `complaints`). Also it created a totally wrong RulesChecker.

This is the closed issue: #15145 You'll understand it better if you read [my reply](https://github.com/cakephp/cakephp/issues/15145#issuecomment-724812504) first.

I do not know how to reopen it or if I actually should...

**Comment by othercorey** [comment]
`proceedings` is considered "plural only" which means only the plural form of the word is used. This is a special case in the inflection code.

You will have to specify the key manually or change your keys to `proceedings_id`.

**Comment by dereuromark** [comment]
https://sandbox.dereuromark.de/sandbox/inflector?string=proceedings
Indeed, I didn't know that special case either.

Closing then.

**Comment by ndm2** [comment]
You could also always overcome such limitations by using custom inflection rules in case you actually want that inflection, for example:

```php
Inflector::rules('irregular', ['proceeding' => 'proceedings']);
```

Maybe the problems in your other issue were somewhat related to that, or maybe you had some old schema data cached when you baked the tables. From a quick test with the schema from your other issue, baking works as expected for me, no `Complainants` association is being generated.

**Comment by hacheraw** [comment]
Thanks for the Inflector rule, for reading the closed issue and trying my SQL.
I never had other tables and my develop cache last +2 seconds so I don't know why this happened.

Anyways I'll just do:
```php
$this->hasOne('Complaints', ['foreignKey' => 'proceeding_id']);
```
