### ISSUE TITLE
Route.php urlencodes params once but decodes twice, causing params like `xx%2Fyy` to fail.

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#15269]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.1

### What you did

Obviously this is not exactly what I am trying to do, but this is the simplest way I can show what is happening.

```php
// ProductsController.php
public function index(): ?Response
{
    $url = Router::url(['action' => 'test', 'xx/yy']); //products/test/xx%2Fyy
    return $this->redirect($url);
}

public function test()
{
    var_dump(func_get_args());
    exit;
}
```

### What happened
1. I get redirected to `http://localhost:8080/products/test/xx%2Fyy`
2. The var dump shows:
```
/var/www/src/Controller/ProductsController.php:54:
array (size=2)
  0 => string 'xx' (length=2)
  1 => string 'yy' (length=2)
```

### What you expected to happen
1. To get redirected to `http://localhost:8080/products/test/xx%2Fyy`
2. The var dump to show:
```
/var/www/src/Controller/ProductsController.php:54:
array (size=1)
  0 => string 'xx/yy' (length=5)
```

### What is causing this
In https://github.com/cakephp/cakephp/commit/d5283af818b59c5d96355d6e42bbd77e1322d8cb `urldecode` got added. Which is still present in [4.2.1](https://github.com/cakephp/cakephp/blob/4.2.1/src/Routing/Route/Route.php#L453).

```php
if (!preg_match($compiledRoute, urldecode($url), $route)) {
    return null;
}
```

This line of code decodes the entire URL before routing the request. Causing this bug. Changing it to `if(!preg_match($compiledRoute, $url, $route))` fixed the problem.

Please be aware that all the params are indvidually encoded on [Route.php#L794](https://github.com/cakephp/cakephp/blob/4.2.1/src/Routing/Route/Route.php#L794) and decoded on [Route.php#L575](https://github.com/cakephp/cakephp/blob/4.2.1/src/Routing/Route/Route.php#L575)

So we are now encoding once, and decoding twice, which doesn't make any sense to me.

### Disclaimer

I fully understand why this is happening, because of international URI (IRI) which might contain characters like `آموزش` and I respect that. But I think we should think of another solution, because very basic functionality and expected behavior is now broken.

**Comment by JelmerD** [comment]
### Thought process 1
Adding below code just in front of the if-statement solved it for me, but this is a really dirty fix. Because this isn't really expect behavior as well. 
```php
str_replace('%2F', '%252F', $url);
```

### Thought process 2
We could also add something in the config or route builder? Maybe define per route if we want utf-8 patterns to be decoded?

**Comment by othercorey** [comment]
@JelmerD Wanted to update that we've quickly discussed this and are not sure we can fix it without breaking other behavior.

**Comment by JelmerD** [comment]
@othercorey which behaviour? Because if it is breaking other behaviour, is that behaviour even correct? I mean, it's encoding once, and decoding twice. That isn't exactly what anybody is expecting, right?

**Comment by JelmerD** [comment]
@ADmad thanks for the fix. I hope this will solve the problem.

But, shouldn't the new parameter be set to 'false' by default? As then you have 1 urlencode and 1 urldecode call. When enabling the 'extra' urldecode, you then explain what happens in the routing. So that it becomes non-ascii url compatible?

Or maybe update the comment for the new param more clearly? Something like: 

> '_urldecode' - Set to false to disable `double` URL decoding before route parsing to prevent params containing a '/' to be split up into two separate params.

**Comment by ADmad** [comment]
> But, shouldn't the new parameter be set to 'false' by default?

No, that would be a backwards compatibility break. Also having UTF-8 chars in URL is more common than having encoded `/`. Other frameworks like [symfony](https://github.com/symfony/routing/blob/fcbc2b81d55984f04bb704c2269755fa5aaf5cca/Matcher/UrlMatcher.php#L88) also urldecode the request URL by default when routing.

> Or maybe update the comment for the new param more clearly? Something like:

The is no "double" decoding per se. The additional decoding is *only* for the URL part which matches `*` in the URL template.

**Comment by JelmerD** [comment]
Ah okay. Thanks for the clear explanation. I hope this will help others as well. Good job guys, keep up the good work.
