### ISSUE TITLE
Regression in 4.2.2 ? Flash Messages

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#15268]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.2
* Platform and Target: PHP 7.4.11

### What you did
```php
    /**
     * Test resetPassword method
     *
     * @return void
     */
    public function testResetPassword(): void
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        $this->enableRetainFlashMessages();
        $this->post('/users/reset-password', ['reset_password_token' => 'validresettoken']);
        $this->assertResponseSuccess();
        $this->assertSession('The Password has been reset.', 'Flash.flash.0.message');
        $this->assertRedirect(['controller' => 'Users', 'action' => 'login']);

        $this->post('/users/reset-password', ['reset_password_token' => 'unknownresetpasswordtoken']);
        $this->assertResponseSuccess();
        $this->assertSession('The Password Reset Token is unknown.', 'Flash.flash.0.message');
        $this->assertRedirect(['controller' => 'Users', 'action' => 'login']);
    }
```
### What happened
This test started to fail after updating to 4.2.2. Worked fine before.

Failed asserting that 'The Password Reset Token is unknown.' is in session path 'Flash.flash.0.message'.

using $this->assertFlashMessage didn't work either.

### What you expected to happen
Test should still pass?

It still works when splitting the test into two test cases

```php

    /**
     * Test resetPassword method with valid token
     *
     * @return void
     */
    public function testResetPasswordValid(): void
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        $this->enableRetainFlashMessages();
        $this->post('/users/reset-password', ['reset_password_token' => 'validresettoken']);
        $this->assertResponseSuccess();
        $this->assertFlashMessageAt(0, 'The Password has been reset.');
        $this->assertRedirect(['controller' => 'Users', 'action' => 'login']);
    }

    /**
     * Test resetPassword method with invalid token
     *
     * @return void
     */
    public function testResetPasswordInvalid(): void
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();

        $this->enableRetainFlashMessages();
        $this->post('/users/reset-password', ['reset_password_token' => 'unknownresetpasswordtoken']);
        $this->assertResponseSuccess();
        $this->assertFlashMessageAt(0, 'The Password Reset Token is unknown.');
        $this->assertRedirect(['controller' => 'Users', 'action' => 'login']);
    }
```

**Comment by ADmad** [comment]
Relying on internal implementation detail and directly checking session key isn't a good idea in the first place but using `assertFlashMessage()` multiple times within the same test method for multiple requests should be expected to work.

I am guessing the `empty()` check here might be the reason why the message for the 2nd request isn't being captured https://github.com/cakephp/cakephp/blob/c71bf2c4852da199726930d1797b0625fc79a7af/src/TestSuite/IntegrationTestTrait.php#L515-L518.

**Comment by swiffer** [comment]
yes, already rewritten to the methods provided.

**Comment by dereuromark** [comment]
We had a few issues already last year, especially around 3.x => 4.x when using multiple integration tests in one succession/run.
To separate them into separate runs is quite important, as the side effects of such integration tests are immense, and resetting between them is vital.
So the solution you found is correct of course.

That said: We could probably remove the !empty() nano-optimization here, as then it would also work in such edge cases still.

**Comment by markstory** [comment]
If we remove that empty() we will need to merge the flashMessages, as they could be blanked between beforeRender and beforeRedirect :|
