### ISSUE TITLE
$this->Form->control('due_date', ['type'=>'date']) --- produces wrong date format for HTML <input> element --- depending on locale

### ISSUE THREAD

**Issue by starlocke** [cakephp/cakephp#15271]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.1
* Platform and Target: Docker PHP Container

### What you did

Given "app.php" with (some truncation for brevity)

```
<-- truncated -->
    'App' => [
        <-- truncated -->
        'defaultLocale' => env('APP_DEFAULT_LOCALE', 'en_US'),
        <-- truncated -->
    ],
<-- truncated -->
```

With the key point being `'defaultLocale' => env('APP_DEFAULT_LOCALE', 'en_US'),` (a typical out-of-the-box locale, I guess)

### What happened

With a template (used to be called a view) for some "model / edit" page having a form input being constructed like this:

```
$this->Form->control('due_date', ['type'=>'date'])
```

Then, when CakePHP is rendering the HTML `<input>` with the `date` type, its `StringTemplate._formatAttribute()` method would simply dump a `Cake\I18n\FrozenDate` as an automatically formatted "__toString()" value, resulting in the input looking like:

`<input type="date" value="1/1/16" />` (other attributes not shown)

I would guess that any other date/time classes are also affected in the same manner (ie: mutable ones, etc).

### What you expected to happen

It is expected that dates are always output in yyyy-MM-dd format for HTML date inputs, like so:

`<input type="date" value="2016-01-01" />`

**Comment by ADmad** [comment]
The `DateTimeWidget` formats the value to required string format before passing it to the string template. So I don't see how what you claim is possible. Are you sure you are not using a customised DateTimeWidget?

https://github.com/cakephp/cakephp/blob/6c9ff4d0adb8776b93a65500021e017340d2bba4/src/View/Widget/DateTimeWidget.php#L121

**Comment by starlocke** [comment]
When going through my system's `$widget = $this->_locator->get($name);` -- a mere BasicWidget was returned instead of a DateTimeWidget.

Yep. I now see that this system happens to have "lost" the assignment of DateTimeWidget when it extended and overwrote `$_defaultWidgets `. Not a problem inherent with CakePHP.

Thank you!
