### ISSUE TITLE
SmtpTransport causes "invalid HELO" when client is empty

### ISSUE THREAD

**Issue by FinlayDaG33k** [cakephp/cakephp#15277]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.9.5
* Platform and Target: Nginx + PHP 7.4.12

### What you did
I've tried sending an email from my project yesterday, as I've posted in the [Discourse](https://discourse.cakephp.org/t/501-syntactically-invalid-helo-argument-s/8854/4).
In my specific case, the `$config['client']` variable had a value of `null`, this caused the server to send an empty/invalid `HELO` command to the server, instead of the host due to the code checking whether the value is set instead of empty or null.
https://github.com/cakephp/cakephp/blob/036f5d2a0a8c09b4aab35040a71f110afac479e0/src/Mailer/Transport/SmtpTransport.php#L233

### What happened
The server trying to send an empty "HELO"

### What you expected to happen
The code to go to the "else" clause.
https://github.com/cakephp/cakephp/blob/036f5d2a0a8c09b4aab35040a71f110afac479e0/src/Mailer/Transport/SmtpTransport.php#L237-L240.

I'm opening this issue, to ask whether this was intended behaviour, and/or whether it may be an idea to use `!empty` instead of `isset`.
Making this change would check the `HTTP_HOST` environment variable, and if that doesn't exist, fall back to the default `localhost`.
https://github.com/cakephp/cakephp/blob/036f5d2a0a8c09b4aab35040a71f110afac479e0/src/Mailer/Transport/SmtpTransport.php#L232

**Comment by ADmad** [comment]
> instead of the host due to the code checking whether the value is set instead of empty or null.

`isset()` will return `false` for `null` value true https://3v4l.org/KcBPc.

**Comment by FinlayDaG33k** [comment]
Hm... in my `.env`, I have the following line:
```
export SMTP_CLIENT=
```

and in my `app.php` it is loaded as such:
```
'client' => env('SMTP_CLIENT', null),
```

However, this results in the issue described above.

**Comment by saeideng** [comment]
>export SMTP_CLIENT=

if you test this 
```php
 var_dump(env('SMTP_CLIENT', null));
```
it returns 
```
string '' (length=0)
```

so `isset` will return `true`

**Comment by saeideng** [comment]
if you don't want to set the `SMTP_CLIENT` , just comment it with `#` or remove it
```
#export SMTP_CLIENT=
```

**Comment by FinlayDaG33k** [comment]
Hm... it does indeed now just become an empty string, might have been some random fluke that it became null then.  
Anyhow, back to the matter at hand, would it be an idea to check whether the variable actually contains a non-empty value for the check?

**Comment by othercorey** [comment]
Do we want to disallow an empty string?

**Comment by FinlayDaG33k** [comment]
@othercorey I think yes, since most servers should reject the connection if the HELO has an empty host.
