### ISSUE TITLE
CakePHP Heroku app for slack signup down

### ISSUE THREAD

**Issue by tomcata12** [cakephp/cakephp#15286]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Tried to join cakephp slack channel using the link in the docs: https://cakesf.herokuapp.com/

### What happened
"Application Error"

### What you expected to happen
To be able to join the cakephp slack channel

**Comment by josegonzalez** [comment]
Just restarted the application, thanks for the report!
