### ISSUE TITLE
DI for other classes, specially services

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#15285]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.0
* Platform and Target: independent.

### What you did

The new DI container works fine to inject dependency into `Controller` and `Command`, but today there's no easy way to inject dependency on other objects - which is useful for service composition.

### What happened

Nothing

### What you expected to happen

Should be cool to create services classes using other services classes, on a composition pattern (just like we can do with Tables relationships).

### What we can do

Maybe a kind of `ServiceLocator` and `ServiceAwareTrait`, just like in [Burzum\Cake\Service](https://github.com/burzum/cakephp-service-layer) did could help.

**Comment by markstory** [comment]
Are you not able to have dependencies of you services injected into services created the container? Where else are you looking to have container objects available?

I don't think a service locator is something that we should offer in Cake yet. Having many dependencies hidden by string lookups concerns with long term maintenance.

**Comment by slava-basko** [comment]
Container works as expected. Let's write FirstService:
```php
class FirstService
{
    public function getResult(): string
    {
        return 'This is result from first service!';
    }
}
```
And SecondService which depends on FirstService:
```php
class SecondService
{
    private $firstService;

    public function __construct(FirstService $firstService)
    {
        $this->firstService = $firstService;
    }

    public function getResultFromFirstService(): string
    {
        return $this->firstService->getResult();
    }
}
```

Now you should define these dependencies in Application:
```php
public function services(ContainerInterface $container): void
{
    // Define FirstService
    $container->add(FirstService::class);

    // Define Second service which depends on FirstService
    $container->add(SecondService::class)
            ->addArgument(FirstService::class);
}
```

Test in in your controller:
```php
class TestController extends AppController
{
    public function show(SecondService $secondService)
    {
        $res = $secondService->getResultFromFirstService();
    }
}
```
Value of $res will be "This is result from first service!", value from FirstService.

Service which injected to Controller or to Command should by with all necessary dependencies.

In all cases your app starts from Controller of from Command. If you need a service from another place just ask yourself: "Maybe i'm doing something wrong."

If cakephp team makes access to DI container from places other than Controller or Command, then it will push people to the wrong patterns.

**Comment by ADmad** [comment]
Nice example @slava-basko.

I think the general issue here is that people don't realize that "auto wiring" only exists for `Controller` and `Command` methods. For other services they have to explicitly register the dependencies with the container.

**Comment by slava-basko** [comment]
@CauanCabral Also, you can use `\League\Container\ReflectionContainer`.
```php
public function services(ContainerInterface $container): void
{
        $container->delegate(new \League\Container\ReflectionContainer);
}
```

But it will cause a long loop. Because container will try to load CakePHP core (part of core?) by itself. As I understand it's happening in Cake\Controller\ControllerFactory::invoke() on line 136.

To avoid this create your own ReflectionContainer that extends `\League\Container\ReflectionContainer` and override `has` method.
```php
public function has($id) : bool
{
        // Avoid CakePHP Controller selfload.
        $parts = explode('\\', $id);
        if ($parts[1] == 'Controller') {
            return false;
        }
        return class_exists($id);
}
```

Finally, you need some changes in `services` method.
```php
public function services(ContainerInterface $container): void
{
        $container->delegate(new \App\Container\CustomReflectionContainer);
}
```

From now one you have sort of nested auto-wiring. Read more here: https://container.thephpleague.com/3.x/auto-wiring/.

❗️**CAUTION**
It's a bit trick that I've not tested.

**Comment by CauanCabral** [comment]
You all are right.

I missed the fact auto-wire is scoped only for Controller and Command (and that make sense as pointed out by @slava-basko in him first comment). I'll think how to include it on Cookbook to dismiss future doubts.

Defining service (or other classes) dependencies + put parameters on their constructors are already enough.

But is good to know I can enable auto-wire on my own with Reflection.

Thanks.

**Comment by doshu** [comment]
what about if you need a service in a model or in custom class that is not injectable itself.
container must be accessible globally if you want to make an object on the fly, like all other frameworks like laravel do.

**Comment by CauanCabral** [comment]
As I understood from out stated @slava-basko (and I agree with him)

> In all cases your app starts from Controller of from Command. If you need a service from another place just ask yourself: "Maybe i'm doing something wrong."

You should pass the service instance when call the model method on your Controller or Command (app entrypoints).

**Comment by doshu** [comment]
What about if the injected object is needed in a method of an object that
you call after other 3 or 4 nested calls? You should pass the service
through all the calls?


Il Ven 22 Gen 2021, 13:31 Cauan Cabral <notifications@github.com> ha
scritto:

**Comment by ADmad** [comment]
Except for controllers and commands the dependencies should be injected through the constructors, not other methods.

**Comment by doshu** [comment]
So, if i need an injected service in a model table i should inject the
table in the controller? and bypass all cakephp table loading mechanism?

Il giorno ven 22 gen 2021 alle ore 13:46 ADmad <notifications@github.com>
ha scritto:
