### ISSUE TITLE
FormHelper::postButton escape option

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#15281]
This is a:
* [x] bug

* CakePHP Version: 4.1

### What you did
```
<?= $this->Form->postButton(
    '<i class="fa fa-trash"></i>',
    ['controller' => 'GridItems', 'action' => 'delete', $item->id],
    ['escape' => false, 'class' => 'btn btn-delete btn-danger']
) ?>
```

### What happened
It shows escaped `<i class="fa fa-trash"></i>` tag even when `escape` is set to false

### What you expected to happen
render html output

**Comment by dereuromark** [comment]
Note:

            'escapeTitle' => true,
            'escape' => true,
            
There are two different ones.
Sounds like the specific one overwrites the generic one here for security reasons.

**Comment by jadb** [comment]
Should be `true` instead.

**Comment by LubosRemplik** [comment]
@dereuromark is right

with 
```
'escapeTitle' => false
```
It does what expexted as documented https://api.cakephp.org/4.2/class-Cake.View.Helper.FormHelper.html#button
