### ISSUE TITLE
Upgrade version sending AWS SES V4 emails

### ISSUE THREAD

**Issue by vitorhps** [cakephp/cakephp#15291]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.1
* Platform and Target: AWS SMTP SESV4 in CakePHP

We use the service of sending emails directly by SMTP (CakePHP Email) in our system, without using a aws sdk, is it necessary to make any changes in sending email config? If so, how could we do that?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
