### ISSUE TITLE
Wrong example on Cache::remember PHPDoc

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15302]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.2
* Platform and Target: Windows 10 (XAMPP) PHP 7.2, 10.1.35-MariaDB

### What you did
Recreate the example in `vendor\cakephp\cakephp\src\Cache\Cache.php::remeber()`'s PHPDoc at [line 572](https://github.com/cakephp/cakephp/blob/master/src/Cache/Cache.php#L572):

```php
/**
 * Provides the ability to easily do read-through caching.
 *
 * When called if the $key is not set in $config, the $callable function
 * will be invoked. The results will then be stored into the cache config
 * at key.
 *
 * Examples:
 *
 * Using a Closure to provide data, assume `$this` is a Table object:
 *
 * ```
 * $results = Cache::remember('all_articles', function () {
 *      return $this->find('all');
 * });
 * ```
 *
 * @param string $key The cache key to read/store data at.
 * @param callable $callable The callable that provides data in the case when
 *   the cache key is empty. Can be any callable type supported by your PHP.
 * @param string $config The cache configuration to use for this operation.
 *   Defaults to default.
 * @return mixed If the key is found: the cached data, false if the data
 *   missing/expired, or an error. If the key is not found: boolean of the
 *   success of the write
 */
```

### What happened
A **PDOException** was thrown:
**You cannot serialize or unserialize PDO instances**

### What you expected to happen
Replace the current example:

```php
$results = Cache::remember('all_articles', function () {
    return $this->find('all');
});
```

with a working one; eg:

```php
$results = Cache::remember('all_articles', function () {
    return $this->find('all')->toArray();
});
```

There is a working example in the docs here: [Read Through Caching](https://book.cakephp.org/4/en/core-libraries/caching.html#read-through-caching) but I think it is not the same case because it is using a `ConnectionManager` and actually returns and array.

----

**PS1: I would gladly do a PR but I'm not confident enought on my solution.**
PS2: I was sure I already submited this "issue" before but I can't find it anywhere so I might did not hit the submit button.

**Comment by markstory** [comment]
Thanks for the issue! Your change looks like the right one to make. If you're not confident in making a pull request I can take care of updating the doc block.

**Comment by hacheraw** [comment]
@markstory created the PR and linked it to this issue. **I don't know if I need to do further actions**. This is what the PR shows:

![image](https://user-images.githubusercontent.com/10481749/105635983-d09f4380-5e5d-11eb-8456-c43ce07c6d26.png)

**Comment by garas** [comment]
You need to open PR in `cakephp/cakephp`, not `hacheraw/cakephp`.

Open https://github.com/cakephp/cakephp/compare/master...hacheraw:hacheraw-patch-1 to create PR.

**Comment by hacheraw** [comment]
> You need to open PR in `cakephp/cakephp`, not `hacheraw/cakephp`.
> 
> Open [master...hacheraw:hacheraw-patch-1](https://github.com/cakephp/cakephp/compare/master...hacheraw:hacheraw-patch-1) to create PR.

I was sure something was going on. I usually open PRs locally but this time, since it was just a line I did it here in githab and did some step wrong for sure.

It's correctly open now!
