### ISSUE TITLE
When i use $this->loadComponent('Auth') in AppController.its returning to usercontroller.but iam using customer controller.wh

### ISSUE THREAD

**Issue by apzscorpion** [cakephp/cakephp#15307]
iam using Customer controller.
but i need login and logout, so i decided to use Auth in appcontroller.But when i use $this->loadComponent('Auth') its redirect to userController in webpage.
my Controller = CustomerController.
i want to use Auth in Ciustomer Controller.Anyone please help me.

public function login()
		{

			//$this->layout=false;
			//echo "string<br>";
			$name= $this->request->getdata('uname');
			$pwd= $this->request->getdata('psw');
			if($this->request->is('post')){
				 
				$result=$this->loadModel('login_data');
				
				$data=$result->find();

				$connection = ConnectionManager::get('default');
				$results = $connection->execute('SELECT password FROM login_data where username='."'".$name."'")->fetch('assoc');
				if($results)
				{
					foreach ($results as $row=>$value)
					{
					
						if($value==$pwd)
						{
							return $this->redirect(['action' => 'index']);
							$this->Flash->success(__("Login Success"));
						}
						else{
							$this->Flash->error(__("Login Failed"));

						}
					}
				}
				else
				{
					$this->Flash->error(__("Login Failed"));
				}
				//print_r($this->request->data('uname'));
				//print_r($results);
				//echo $pwd;
			}

my routes.php 
----------------
   $routes->connect('/', ['controller' => 'Customer', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/index/*', ['controller' => 'Customer', 'action' => 'index']);

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by apzscorpion** [comment]
Ok thanku sorr for the inconvenience
