### ISSUE TITLE
Hash::merge not merging numeric values. Could we change this behavior?

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15305]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

[Configure::read()](https://github.com/cakephp/cakephp/blob/master/src/Core/Configure.php#L327)'s third argument is `merge = true`

It calls [Hash::merge()](https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L774) who calls [static::_merge()](https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L796).

I'm facing the same problem as I would face when using [array_merge()](https://www.php.net/manual/en/function.array-merge.php): it does not merge numeric keys. Not even if they are present on both arrays.

[array_replace()](https://www.php.net/manual/en/function.array-replace.php) solves this. Another workaround it to use `+` operator, eg: `$array1 + $array2`

----

**Is this a expected behavior? What could happen if we change it? Should we maybe add a fourth param to allow merging numeric keys?**

----

### Current behavior examples:

```php
// config/app.php
return [
    'default_group_ids' => [1, 3]
];

// config/app_local.php
return [
    'default_group_ids' => [2]
];

Configure::load('app', 'default', false);
Configure::load('app_local', 'default');
debug(Configure::read('default_group_ids')); // output: [1, 3, 2]
```

```php
// config/app.php
return [
    'text' => [0 => 'default']
];

// config/app_local.php
return [
    'text' => [0 => 'custom']
];

Configure::load('app', 'default', false);
Configure::load('app_local', 'default');
debug(Configure::read('text')); // output: [0 => 'default', 1 => 'custom']
```

----

PS: **I'm a newbie when it comes to contributing. What should I do next time? To open an issue like this one or to open a PR and discuss it there?**
Thanks.

**Comment by dereuromark** [comment]
Assoc (associative) merging is by default only something defined on stringish keys.
The default PHP arrays however are numerically based indexes (0 falls into this).
Therefore the behavior is kind of expected for the default merging operations.

I think we once discussed certain merge flags and options, as this can be difficult to control for deep merging or edge cases.
Not sure, though, if this falls into core territory or should rather be community (plugin or app) level.

**Comment by hacheraw** [comment]
> Your data is actually just:
> 
> ```
> 'text' => ['default']
> ```
> 
> in short form.
> 

Yeah, I know. I did not write the short form because it could lead, at first sight, to think that it's a string key.
Also, my english is not that fluent so I might have not expressed myself quite well.

I think using numeric arrays in config files can be a common practice. I can imagine a lot of examples:

``` 
'allowed_actions' => ['register', 'login', 'view'],
'staff_group_ids' => [1, 5, 6],
'meta_tags' => ['blog', 'news', 'community'],
```

Right now I'm using [array_replace_recursive()](https://www.php.net/manual/es/function.array-replace-recursive.php) and then I write the result to config. I still miss something: it does not replace a sub-tree from $array1 if its value in $array2 is an empty array.

**Comment by markstory** [comment]
Changing the default behaviour would certainly break application code. We would need a different method name or an option flag.
