### ISSUE TITLE
4.next - Separate schema and data for test fixtures

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#15308]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Maintaining and improving the current fixture system is challenging as it is complex has many hidden features and relies on deprecated PHPUnit APIs. 

## Problems

* The various ways we currently manage schema results in even more complexity as handling constraints requires workarounds and hacks.
* We rely on deprecated PHPUnit APIs which will be removed. Potentially in PHPUnit 10.
* The replacement APIs in PHPUnit are not suitable for our use case.

As there are a few orthogonal problems we could address them separately, but addressing them together could unlock a better developer experience.

### Integration with PHPUnit

Currently the test suite uses `PHPUnit\Framework\TestListener` to listen for tests being started. The test suite and test case start events are used to create schema and populate records before a test is run. This interface is deprecated, and [extensions are recommended instead](https://phpunit.readthedocs.io/en/9.5/extending-phpunit.html#extending-the-testrunner). Unfortunately, extensions do not have access to the testsuite or the test case objects. While they do have access to the class and method names, this data is not ideal and limits any future fixture APIs to being static.

We have had reasonable success using traits that leverage the `@before` annotation to do setup work. Another potential approach is to use the `TestCase::setUp()` to collaborate with shared global that wraps the database 'state'.

### Managing Schema

Currently the test suite drops and manages schema at the table level. As fixtures are loaded/used tables are created. At the end of the test run all tables are dropped. This incurs some overhead as we need to track which tables have been created, and whether the table needs to be dropped before it is created. Compounding this complexity is the variety of ways we allow developers to define schema:

1. As abstract schema in fixture classes via the `$schema` property. This form is not the actual schema, but an abstract representation, that can be leaky or incorrect. Having schema in fixtures, creates complexity for developers, as there is another place to manage schema as it changes.
2. As an 'import' from a table or a model. Using the reflection API's schema is read and then reverse engineered back into SQL. This conversion can be lossy or inaccurate.
3. As an unmanaged table that does not import or generate a schema but does truncate table rows.

These various schema generation approaches require us to have a comprehensive schema generation library in CakePHP adding complexity to the database abstractions.

### Managing Schema

There are several potential options when it comes to schema management.

1. No schema management - We could take a path where the test suite expects all of the required database schema to exist *before* tests are run. The test suite would still use fixtures to create/drop rows, but all schema management would be external to tests. This option also enables users to use their chosen migration tool to create the necessary schema.
2. Leverage migrations - Similar to how Laravel manages databases in tests, the migrations plugin could provide a trait that allows database schema & seed data to be 'reset' by dropping the database and running migrations again.
3. In addition to option 2, offer basic SQL schema loading in CakePHP core.
4. Something else?

### Load schema during test bootstrap

Previous revisions of this issue proposed loading schema via the PHPUnit extension and leveraging different extensions to provide support for migrations. PHPUnit extensions have limited configuration options, and upon further consideration we can have more expressive APIs if we load schema during test bootstrap.

Test bootstrap is an ideal time to build the required schema for a test run. Datasource plugins like elastic-search can provide their own adapters and applications can use multiple adapters. Using `tests/bootstrap.php` to initialize schema also lets application developers extend schema creation to suite their needs if they have more custom requirements.

The general behavior of a schema loader would be:

1. Drop the test database.
2. Load the required schema.

An example of this approach can be found in the [cakephp-test-migrator](https://github.com/vierge-noire/cakephp-test-migrator). If we adapt that interface to the migrations plugin we could have an API like:

```php
\Migrations\TestSuite\Migrator::migrate();
```

This method would accept additional parameters to define which connection and which plugins need migrations run:

```php
// Each element defines a set of migrations to run.
\Migrations\TestSuite\Migrator::migrate([
    // For the test connection, read migrations from the migrations/TestFolder
    ['connection' => 'test', 'source' => 'TestFolder'],
    // Run the FooPlugin migrations on the FooConnection connection.
    ['plugin' => 'FooPlugin', 'connection' => 'FooConnection'],
    // Run migrations in migrations/BarFolder as well.
    ['source' => 'BarFolder'],
    ...
 ]);
```

For applications that want to load schema from a SQL file the `Cake\TestSuite\Schema\SchemaManager` class can be used. It exposes a `create()` method to create schema:

```php
\Cake\TestSuite\Schema\SchemaManager::create('test', 'path/to/schema.sql');
```

For CakePHP core tests we could use a small wrapper around `phinx` and a single migration that can be run on all database vendors. This would remove the burden of having to maintain 4 schema files that will inevitably diverge.

#### Loading Rows

In all of the above options we need to integration points. One for loading and resetting rows, and the other for potentially managing schema. Ideally loading rows can continue to use the same interfaces we use today. Rows would continue to be loaded during `setUp()` and tables truncated during `tearDown()`. Any table that had a fixture loaded during a test (either via `$fixtures`, `loadFixtures()`, or `fixtureManager->loadSingle()`) would be automatically truncated during teardown.

Similar to the current fixture system, data fixtures would load rows from within the extension. Using the `BeforeTest` hook the fixture extension can create an instance of the test case and use `getFixtures()` to get the fixture list. Likewise, the `AfterTest` hook would be used to truncate rows.

When rows are loaded foreign keys would be *disabled or deferred*. While this will allow invalid states to be created with some database vendors it greatly aids test suite performance, and is a behavior of our current fixture system.

#### Data only fixture manager

In order to maintain backwards compatibility a simpler fixture manager (`Cake\TestSuite\DataFixtureManager`) that implements a common interface as the current `FixtureManager` would be required. The required public methods for common fixture manager interface are:

* `loadSingle(string $name, ?ConnectionInterface $connection = null): void` Load a single fixture based on the name.
* `load(TestCase $test): void` Load all fixtures for the provided test.
* `loaded(): array` Get a list of loaded fixtures.
* `fixturize(TestCase $test)` Would be a no-op on the data fixture manager.

DataFixtureManager would use a global registry, with a single instance per connection (managed through static methods).

#### Resetting state

Because data and schema will be separate we can no longer rely on the fixture manager knowing precisely which tables are used by a given test. This complicates resetting the state of the database, as the tables that need to be truncated are unknown. There are a few potential options around resetting data:

1. Wrapping each test in a transaction that is rolled back during teardown. This approach is used by Symfony, Laravel and Django. It can create issues with older versions of MySQL where nested transactions are poorly supported, and can fail if tests mutate schema.
2. Applying triggers to all tables and using those triggers to track which tables have mutations. This approach is used by the [test suite light](https://github.com/vierge-noire/cakephp-test-suite-light) package to enable factory based flows. This approach requires more complex code within CakePHP as triggers and a 'tracking table' need to be installed so that cleanup can be done.
3. Resetting all tables with `truncate`. This approach while simple and mostly free of complications is the least performant and most likely to scale poorly for large applications.

In any of the above approaches we should aim to make the truncation strategy separate/contained from other aspects of fixture data management so that user land fixture extensions can customize/replace the approach used.

#### Opt-in process

Applications would opt into using the new fixture manager by using one the new PHPUnit extensions (see above). The new extensions would set constants that enable `TestCase` to get a reference to the new fixture manager in a `setupBeforeClass` hook instead of relying on the filter setting the public property. This would mean that *having both* the new and old PHPUnit extensions would end up with the *old* fixture system.

## Questions

* Can the same extension be used multiple times in PHPUnit?
* How do plugins provide database schema to their users?
* Do plugins ship with migrations, or SQL files? 
* How common are applications that use multiple test database connections?

## Changes

* Added `env://` to file loading
* Added transactions around tests to rollback changes.

**Comment by pabloelcolombiano** [comment]
Great to see things evolving at this end 👍 

In order to develop the [fixture factories plugin](https://github.com/vierge-noire/cakephp-fixture-factories), we had to tackle the issue of separating schema and fixtures. This is why we developed the [test suite light plugin](https://github.com/vierge-noire/cakephp-test-suite-light), which truncates the dirty tables between each test, without dropping tables at no time.

This is the strategy we took:

A. Schema:

1. The schema is handled outside the fixtures: SQL commands, or hopefully migrations.
2. In the highly recommended case where migrations are present, our [migrator tool ](https://github.com/vierge-noire/cakephp-test-migrator) takes care of the schema of the test DB. Migrations get run once (really once, not once per go, you know migrations...) as long as you do not switch to a branch with migrations up but missing (in such case, the migrator drops all tables and start from null). So it's fast. If you have migrations here or there, or in a plugin, this can all be parametrized.

The framework should encourage good practice, and migrations definitely are. So why not have this as a requirement? It is already the case in the [app skeleton](https://github.com/cakephp/app/blob/master/composer.json).

B. Fixtures:

Let's face it, fixtures are an awful practice.
1. Their performance decrease as they force you to load fixtures in tests, that your test might just not need. The bigger your app, the slower each tests.
2. Tests share fixtures: this is bad practice and if not dangerous, a nightmare to maintain.
3. Very hard to read. It is hard enough to read/review/understand a test. Having to run from one fixture file to the other consumes a lot of energy, nerves, coffee.
 
I tried to demonstrate all that at the [CakeFest 2020](https://www.youtube.com/watch?v=PNA1Ck2-nVc&t=35s). It is out of the topic of the current discussion, but since you are willing to do a bit of clean-up there, I would say that fixture factories solve all the problems related to fixtures you mentioned above. And add a lot of benefits (easy to read, to write, it's all in your test, IDE friendly, ...).

**Comment by markstory** [comment]
> The framework should encourage good practice, and migrations definitely are. So why not have this as a requirement? It is already the case in the app skeleton.

I generally agree that migrations are the best path for applications to use, and would prefer that we ship an app skeleton that is pre-configured to use migration based fixture schema. With that said I think there are scenarios that justify externally managed schema or dump files that the 'basic' implementation would provide. CakePHP's internals are one such situation, and another is applications that are using other tools to manage schema, or are sharing a database with another application.

> Let's face it, fixtures are an awful practice.

I agree, and would like to update the documentation to recommend factory based approaches more going forward. While I'm reluctant to add more dependencies to CakePHP perhaps we can find a path forward via the app skeleton coming with more batteries included?

**Comment by othercorey** [comment]
> Tests share fixtures: this is bad practice and if not dangerous, a nightmare to maintain.

This is the core design of cake tests.

**Comment by pabloelcolombiano** [comment]
> there are scenarios that justify externally managed schema or dump files

The migrator could easily be extended to have a method that runs SQL queries stored in one or multiple files. No problems there.

> I'm reluctant to add more dependencies to CakePHP

I completely agree with you. I think that it makes sense to sensibilize the developers to the existence of the factories in the Cookbook and I can prepare some PR, if you want. But before doing this, we should agree that the approach is the correct one, and that users installing the fixture factories plugin will not be deceived in the future with CakePHP implementing its own solution, with much refactoring implied.

But back to the topic of the thread...

**Schema - data separation requires a strategy to clean up the test DB between tests.**

I believe this is the real challenge. CakePHP tests are dependent on the fixtures not only because they provide the schema, but because they allow to clearly define which tables should be truncated after a test. Given we have a schema with `N` tables, no fixtures loaded, and a test performs an insert in table `foos`, how will the test suite know which tables to truncate? In the current state of the framework, you cannot insert in the table `foos` without loading the fixture `FoosFixture.php`, because the latter is needed to create the table. Truncating all tables is too costly if `N` is big.

The [test suite light plugin](https://github.com/vierge-noire/cakephp-test-suite-light) tackles that problem, using SQL commands only. SQL engines have enough features to enable to detect the "dirty" tables at the end (or in the plugin at the start) of the test and truncate these only. 

One other strategy consists in wrapping tests in an SQL transaction, rolled back at the end. This is what Laravel and Symfony do. With Symfony [warning that this might collide with other transactions](https://github.com/dmaicher/doctrine-test-bundle#troubleshooting), I would be careful with this approach.

What do you think?

**Comment by pabloelcolombiano** [comment]
> > Tests share fixtures: this is bad practice and if not dangerous, a nightmare to maintain.
> 
> This is the core design of cake tests.

True. Do you mean that this is immutable? What do you mean exactly?

**Comment by markstory** [comment]
> One other strategy consists in wrapping tests in an SQL transaction, rolled back at the end of each tests. This is what Laravel and Symfony do. With Symfony warning that this might collide with other transactions, I would be careful with this approach.

Wrapping tests in a transaction that is rolled back during teardown is the approache used in Django, and rails as well and is worth exploring. Having a new fixture system is a great opportunity to switch, as tracking which tables have been mutated is complicated as you are very aware of :smile: I'll update the RFC with that change.

**Comment by othercorey** [comment]
> Wrapping tests in a transaction that is rolled back during teardown is the approache used in Django, and rails as well and is worth exploring.

How do they handle auto-commits from DDL statements in mysql?

**Comment by pabloelcolombiano** [comment]
I forgot to emphasize that truncating the test DB before (setup) and not after (teardown) tests are run presents the significant advantage that the developer can query the test DB after a given test was run. I find this very convenient when writing tests.

**Comment by markstory** [comment]
> How do they handle auto-commits from DDL statements in mysql?

Poorly. Doing DDL inside a test will break the transaction abstraction and cause tests to not reset in the transaction based mode.

> I forgot to emphasize that truncating the test DB before (setup) and not after (teardown) tests are run presents the significant advantage that the developer can query the test DB after a given test was run. I find this very convenient when writing tests.

This is a workflow that can't be performed with a transaction based fixtures. It would work with the trigger based tracking table though. The tracking table seems interesting, but the complexity of triggers and dealing with varying level of support across database platforms concerns me.

**Comment by pabloelcolombiano** [comment]
> The tracking table seems interesting, but the complexity of triggers and dealing with varying level of support across database platforms concerns me.

True.

Triggers are featured by all DB engines [listed in the Cookbook](https://book.cakephp.org/4/en/installation.html#installation). The test suite light does not feature Microsoft SQL Server nor Oracle so far, but this could be implemented as well (I highly presume).

I drafted a ["universal" test DB cleaner](https://github.com/vierge-noire/test-database-cleaner/tree/main/src/ConnectionManager) that works for Laravel and Symfony (the latter still in progress). If CakePHP featured this alternative trigger-based approach, it could easily share it with other frameworks via adapters, with the maintenance (back to your point) shared by more users.

One additional drawback of the transaction-based approach is that the test DB needs to be dropped prior to running the test suite and migrations to be re-run. For large projects, one application may easily come up with migrations taking 10s of seconds. While doing TDD, supposing tests get run in average every 5 minutes, this makes within a day 15 minutes spent running migrations. Merging a bunch of migrations within one single migration on a regular basis reduces the impact of this artefact though.

**Comment by pabloelcolombiano** [comment]
> In any of the above approaches we should aim to make the truncation strategy separate/contained from other aspects of fixture data management so that user land fixture extensions can customize/replace the approach used.

@markstory Reading your RFC update, it makes totally sense to develop a simple CakePHP official transaction-based approach for the test DB reset. And leave it to the developer's convenience to choose the approach.

**Comment by markstory** [comment]
I've been thinking a bit more about this and I've been reconsidering the schema creation aspect of the phpunit extension.

For applications using migrations the application's `test/bootstrap.php` could use wrappers exposed by the migrations plugin to run all migrations. For schema file loading, we could provide an easy to operate API.

Not including the schema loading in the extension lets us avoid additional configuration complexity in the PHPUnit extension and also makes replacing how schema is loaded easy to access due to where it would be located. This could also help address some of the comments raised around re-using schema in CI.

**Comment by ravage84** [comment]
I don't know how other companies test their complex, database intensive applications but for years now (2012 up until today) we do these things in **our applications**:

- Do not have a fixated schema in our fixtures but **import the schema** from either **the table or the model**. We see no benefit for having a 1:1 copy of the schema in our fixtures for which we have an up to date model or table anyway.
- Have **a shared set fixtures for the whole test suite**. We have applications with dozens if not more than one hundred tables. Many tests need to interact with several tables. Having to set up a dedicated data set for each test would be a nightmare. If we need, we still can set up data at run time (in the test case) manually or use specialized fixtures, which happens seldom.
- For CakePHP 3.x, we **use the  [FriendsOfCake / fixturize ](https://github.com/FriendsOfCake/fixturize)** to prevent all these tables and rows being reset all the time. This helped to improve the performance of our test suites greatly.

If there will be a separate place to define the test schema, it would be great **for us** to be able to import it from the models or tables, again.

@markstory or how do you envision the options of keeping the test schema up to date as least work intensive as possible?

> How common are applications that use multiple test database connections?

We have at least one application among ours. In that case, it's even two different database systems (in production).

**Comment by markstory** [comment]
> If there will be a separate place to define the test schema, it would be great for us to be able to import it from the models or tables, again.

The two sources that are included in the scope of this so far are migrations and static schema files. Using schema reflection and rehydrating the schema is something I'd like to avoid because it can be a lossy process and the abstract -> concrete schema translation code is something I would like to remove from the database package long term. We have similar functionality inside of phinx and duplicating it in cake/database is additional complexity that we could do away with.

**Comment by pabloelcolombiano** [comment]
Concerning the creation of the schema of the test DB:

I am working on a version of the [Migrator](https://github.com/vierge-noire/cakephp-test-migrator) that could be integrated into the Migrations plugin, or partly into CakePHP, as far as the SQL file solution is concerned, to be discussed.

The job of the migrator is to maintain the schema with migrations or SQL dump file.

The developer specifies to the migrator which migrations your tests require, and let them run.
**OR**
The developer provides one or several paths to the files containing the schema in SQL format.
All this happens in `tests/bootstrap.php`.

After running the migrations, if any migrations were moved from down to up, the Migrator will truncate all tables, to ensure that the test suite starts with a clean test DB.
**OR**
After running the dump, if specified, the developer can indicate that the tables need to be truncated.

If you work with migrations:
- As long as no migrations are added, nothing happens to the schema
- If you add one / several additional migrations, only those get run, and the tables get all truncated after, to make sure that all tables are empty prior to the test suite begins.
- If you switch to a branch that does not feature some migrations marked as up, the schema is inconsistent. All tables get dropped, and the migrations are run completely again.

If you work with SQ file:
- the tables get dropped and the schema gets recreated prior to running the tests. This is less efficient, especially if you have many tables.

**Comment by markstory** [comment]
I've updated the issue description to better match the current plans. After discussion and thinking more, I dislike the idea of using PHPUnit extensions to load schema. Instead we can call schema loading libraries from `tests/bootstrap.php`. This enables us to have more expressive APIs for loading schema and easily afford applications that require multiple connections, and a variety of datasources.

**Comment by pabloelcolombiano** [comment]
There is one point that we should address here: when dropping or truncating all tables, views should be ignored in order to avoid an exception thrown.

Since the native `listTables()` method does not exclude views, I suggest we add a `listTablesIgnoreViews()` method [here](https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/Collection.php#L61).

**Comment by markstory** [comment]
Closing this as these changes have been merged into 4.next and documented.
