### ISSUE TITLE
dependency injection container is not accessible globally

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#15300]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2

Why the dependency injection container is not accessible globally? It can be useful if the container can be used in custom class

**Comment by slava-basko** [comment]
Hi, plz read my comment from similar issue https://github.com/cakephp/cakephp/issues/15285#issuecomment-761524899. Maybe it will helps you to understand that DI container not necessary in other classes.

**Comment by markstory** [comment]
How would you use the container in a global way? The various factories and registries that CakePHP uses internally don't create their objects through the container as it would require significant changes to the framework internals and userland code. We're also trying to avoid creating a global service locator.

**Comment by doshu** [comment]
if cakephp does not use the container internally when instantiate objects,
the user has not the ability to instantiate object from the container in
code that is executed before the controller.
For example it is not possible to inject an object in a middleware.
i agree that cakephp core must not instantiate every object through the
container but the user should have the ability to use container manually in
edge cases.
The container should expose a make method that create an object based on
the dependency injection rules

Il giorno ven 22 gen 2021 alle ore 16:46 Mark Story <
notifications@github.com> ha scritto:

**Comment by markstory** [comment]
> For example it is not possible to inject an object in a middleware.

This is not true. You can create middleware from the container in your Application. The framework does not construct middleware objects.

> The container should expose a make method that create an object based on
the dependency injection rules

Where would that method live?

**Comment by doshu** [comment]
Dependency injection is not usable in view class or in table class too.
view must be built from the container and table classes should not be autoloaded, but injected in the controller through constructor or method injection.
if this could not be possible, manually creating object from the container is necessary

**Comment by markstory** [comment]
Yes all of that is true right now. We didn't have solid use cases for container injection in the view layer so we're waiting for the use cases to come up.

The ORM is a bit tricky as it can be used at arbitrary points in the application life and ensuring the container is always present is challenging. The container support is still in an experimental stage and we are interested in ways to expand its utility.

**Comment by robertpustulka** [comment]
@doshu for a DIC aware table locator check this plugin: https://github.com/robotusers/cakephp-di/tree/0.3

At 0.3 it is compatible with CakePHP 4.2+

**Comment by CriztianiX** [comment]
What about DI in event listeners? I have a multitenant application. Each tenant has a biometric data validation service. In my use case, after registering a user (Model :: afterSave), a call must be made to the service. Inside the listener, you should have the corresponding service (a specific implementation) available

**Comment by doshu** [comment]
Sure, this is another valid example.

Il Dom 9 Mag 2021, 19:53 Cristian Haunsen ***@***.***> ha
scritto:

**Comment by robertpustulka** [comment]
You can register your event listeners in Application::bootstrap hook where the DIC is accessible.

**Comment by CriztianiX** [comment]
> You can register your event listeners in Application::bootstrap hook where the DIC is accessible.

Sure.. i've done that.
But imo i feel like that is not the best option. 
Register listeners for model should be in the model, i think

**Comment by robertpustulka** [comment]
> Register listeners for model should be in the model, i think

You mean Table class? Nah, it’s usually better to separate class responsibilities and reduce complexity.

**Comment by CriztianiX** [comment]
> You can register your event listeners in Application::bootstrap hook where the DIC is accessible.

Yes ... but anyway, autowiring does not work in the event 's method, and i should get key from container manually.

**Comment by othercorey** [comment]
Is there any change to make for 4.3?

**Comment by othercorey** [comment]
If there are requests and use cases for the specific scenarios discussed here, please open a new issue or PR.

Closing the global instance request since there doesn't seem to be a specific solution.
