### ISSUE TITLE
Table::loadInto does not use dirty values

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15309]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.13

Having RequestsTable with HasMany relation such as
```
        $this->hasMany('Identities', [
            'foreignKey' => [
                'user_id',
                'version',
            ],
            'bindingKey' => [
                'user_id',
                'user_identity_version',
            ],
        ]);
```

Then this procedure will load incorrect associated entities
```
$request = $this->Requests->get(123);
// change part of bindingKey data
$request->set('user_identity_version', $request->user_identity_version + 1);
$request = $this->Requests->loadInto($request, ['Identities']);
```

Specifically loaded association data will be matched by NON-DIRTY (original) 'user_identity_version' instead of current dirty value.
Is it possible to `loadInto` with current data instead of original values, without having to save the entity first?

From inspection of LazyEagerLoader method `_getQuery` it looks like it actually does a brand new select from Requests table with `contain` set as requested via `loadInto` method, however that will always yield association as currently present in DB instead of using current dirty values of bindingKey properties.

**Comment by markstory** [comment]
>  Is it possible to loadInto with current data instead of original values, without having to save the entity first?

Not really with the current implementation. As you noted we reload the original entity and the requested associations with `contain()`.

The method would need to be rebuilt to do what you're looking for. I think using the current entity values would make the method more complex and less efficient as we would need to emit 1 query per association instead of being able to load all the joinable associations with a single query.

**Comment by ADmad** [comment]
IMO the method should always fetch associated records based on persisted data.

**Comment by smarek** [comment]
@markstory  Thank you for confirmation, it is not necessary to modify current loadInto behavior (make it less efficient), however in my opinion it's not always possible to persist entity before fetching association (ie. FK constraints and association table beforeSave will prevent saving before associated model is updated as necessary for integrity)
And I can imagine the performance trade-off being opt-in, eg. something like `LazyEagerDirtyLoader` which would allow for behavior I described. Certainly not as default behavior of the `loadInto`, that's for sure (thus I agree with @ADmad )

Still I can write such loader myself, or instead of reloading whole entity, just fill the current entity with appropriate association through `find()` on association model. If you don't think it should not be part of the framework, we can just close this ticket.

**Comment by othercorey** [comment]
I'm closing this as it's a large scope feature no one is planning to work on. Essentially, users will have to patch the entity.
