### ISSUE TITLE
Invalid PDO attribute on SQL server database connection

### ISSUE THREAD

**Issue by bor-attila** [cakephp/cakephp#15315]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.2
* Platform and Target: Ubuntu 18 LTS, PHP 8.0.1, sqlsrv 5.9, pdo_sqlsrv 5.9, unixOdbc 2.3.7

### What you did
Tried to connect to a Azure SQL database instance.

### What happened
PHP Error.
Connection to Sqlserver could not be established: SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object. 

### What you expected to happen
After the connection, the query returns some result.

Based on the [documentation](https://docs.microsoft.com/en-us/sql/connect/php/pdo-prepare?view=sql-server-ver15#remarks) what I found on microsoft.com the _PDO::ATTR_EMULATE_PREPARES_  is an attribute for PDO::prepare not for the connection.

In PHP 7.4 this is not a problem, but for PHP 8+ this throws an error.

When I moved `PDO::ATTR_EMULATE_PREPARES => false,` from connect() to prepare() in the [Sqlserver.php](https://github.com/cakephp/cakephp/blob/045122bd895847d4ce2a8173d31101bd5144dcc0/src/Database/Driver/Sqlserver.php#L132) solved the problem.

UPDATE: Actually you don't even need to move _PDO::ATTR_EMULATE_PREPARES_ to prepare() bcz according to the documentation, the default value is false - just remove it.

The problem looks like the PHP version. After 8.0 the [default error mode was changed to exception](https://www.php.net/ChangeLog-8.php).

This also throws an error
`$this->MyUserTables->getConnection()->getDriver()->getConnection()->setAttribute(\PDO::ATTR_EMULATE_PREPARES, true)`
even in PHP 7.4.

**Comment by othercorey** [comment]
We were waiting for a new pdo driver to test on php 8.

**Comment by uiartist** [comment]
@bor-attila Thanks for letting us know that PDO::ATTR_EMULATE_PREPARES value is false by default and so can be removed from our code. This saved my day.
