### ISSUE TITLE
Allow array parameter on $this->request->getData()

### ISSUE THREAD

**Issue by cacobala** [cakephp/cakephp#15321]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

I think it would be really useful if we could filter data from the request by passing an array as a parameter in the `$this->request->getData()` method.

So, for example, let's say I want to restrict the fields to be updated for a user to their first name, last name and date of birth.

You could write it like this, but I think it would be a bit verbose:

```
$data = [
    'first_name' => $this->request->getData('first_name'),
    'last_name' => $this->request->getData('last_name'),
    'date_of_birth' => $this->request->getData('date_of_birth'),
];
$user = $table->patchEntity($user, $data);
```

Or you could simply accept all the data in the request to keep it simple. But I think this wouldn't be the most secure way, especially if you're doing the request through ajax, which could have the SecurityComponent disabled, and would allow any of the data in the request to be assigned to the entity. Apart from that, it's not easy to read what's actually being saved here.

```
$user = $table->patchEntity($user, $this->request->getData());
```

So the proposal is to be able to pass an array with the names of the allowed values in the request to be passed to the `getData` method, which would return an array with the keys and values.

```
$data = $this->request->getData(['first_name', 'last_name', 'date_of_birth']);
$user = $table->patchEntity($user, $data);
```

The same could apply to the `getQuery` as well.

**Comment by ADmad** [comment]
You can already use the `fields` to restrict the fields that would be used to patch the entity.
```
$user = $table->patchEntity(
    $user, 
    $this->request->getData(),
    ['fields => ['first_name', 'last_name', 'date_of_birth']]
);
```

**Comment by markstory** [comment]
How would your proposal work with default values? We might need a different method to keep types reasonable.

**Comment by cacobala** [comment]
@ADmad this is great, didn't know about this to be honest.

But what about situations in which I'm not actually saving the data to a record?
Let's say I want to filter data on an advanced search, it would be good to limit the fields.

@markstory this could indeed get tricky. Maybe the second parameter contains the default values?
`$this->request->getData(['first_name' => 'John'], ['first_name' => 'default name])`

Or if this is too complicated, as we would probably want a similar behavior for other methods like `getQuery`, an alternative would be to add a `only` method to the collection class? Just to make this a bit easier? What about

`collection($this->request->getData())->only(['first_name', 'last_name', 'date_of_birth']);`

A way to do it in php is, but I think it's a bit difficult to understand what's going on:
`array_intersect_key($this->request->getData(), array_flip(['first_name', 'last_name', 'date_of_birth']));`

**Comment by othercorey** [comment]
Closing this since it's a large change without a clear implementation or design. Users will have to add this manually.
