### ISSUE TITLE
Translations with YAML instead of PO/MO?

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#15329]
* [x] feature-discussion (RFC)
* CakePHP Version: 4.x

Is it possible to change the po/mo translations to more readable and easier to modify .yaml files?
The documentation provides an example of parsing existing yaml files (https://book.cakephp.org/4/en/core-libraries/internationalization-and-localization.html#creating-message-parsers), but I am missing a way to generate the yaml files, similar to bin/cake i18n extract.

Or is po/mo just the way to do it?

Thx,
Mario

PS: I'm asking here because I got no answer in the forum https://discourse.cakephp.org/t/translations-with-yaml-instead-of-po-mo/7084

**Comment by markstory** [comment]
There is no yaml loader or extractor built in right now. The i18n extract command would need some work to make file generation extendable via plugins. It is doable if someone has interest/motivation to extract the existing code and provide plugin hook points.

**Comment by lorenzo** [comment]
The po format is a great way to do translations as there are several specialized editors for the format itself that are tailored for producing translations. 

Have you tried using any of those editor? Such as poedit

**Comment by ADmad** [comment]
Once can extend core's `I18nExtract` command and override relevant parts to generate YAML files instead of pot. For e.g. I have done so to store the messages in database instead of generating .pot files in my [I18n](https://github.com/ADmad/cakephp-i18n/blob/master/src/Command/I18nExtractCommand.php) plugin.

**Comment by mrothauer** [comment]
Thanks everybody for the quick replies.

> Have you tried using any of those editor? Such as poedit

Yes, I am working with poedit and I'm fine with that. A lot of projects use it and it's doing it's job well. The only reason I'd like to switch to .yaml files is, that one could use any text editor to create / change translations. And because I read the section in the documentation, I got curious.

> For e.g. I have done so to store the messages in database instead of generating .pot files in my I18n plugin.

It would be great if your plugin - some day - could also work with .yaml files.

**Comment by ADmad** [comment]
Closing as currently we have no plans to include support for YAML file generation for translation messages in CakePHP core (or my I18n plugin either :slightly_smiling_face:).
