### ISSUE TITLE
Time::createFromFormat from Unixtime with timezone

### ISSUE THREAD

**Issue by yosus** [cakephp/cakephp#15320]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.6
* Platform and Target: Ubuntu 20, PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )

### What you did
Referring to [Time doc](https://book.cakephp.org/3/en/core-libraries/time.html#creating-time-instances). I am trying to create a Time object from Unixtime with timezone. Code :
`$startTimeDateObj = Time::createFromFormat(
				'U',
				1612108800,
				'America/New_York'
			);`
Output :
```
object(Cake\I18n\Time) {
	'time' => '2021-01-31 16:00:00.000000+00:00',
	'timezone' => '+00:00',
	'fixedNowTime' => false
}
```

### What happened
Timezone was not captured. 

### What you expected to happen
timezone should be captured during creation.  Instead, I need to add this extra line
`
$startTimeDateObj->timezone = 'America/New_York';
`
Output :
```
object(Cake\I18n\Time) {
	'time' => '2021-01-31 11:00:00.000000-05:00',
	'timezone' => 'America/New_York',
	'fixedNowTime' => false
}
```

**Comment by ADmad** [comment]
That behavior is consistent with that [DateTime::createFromFormat()](https://www.php.net/manual/en/datetime.createfromformat.php). If the time value is a UNIX timestamp then the timezone is ignored: https://3v4l.org/ZB5PB

**Comment by yosus** [comment]
Thanks. Maybe the this can be added to the docs, or could this "UNIX timestamp with timezone" be added as a feature ? 


Taken from [datetime.createfromformat.php](https://www.php.net/manual/en/datetime.createfromformat.php)
```
Note:

The timezone parameter and the current timezone are ignored when the datetime parameter either contains a UNIX timestamp (e.g. 946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).
```

**Comment by markstory** [comment]
Adding a 'timestamp with timezone' variant could create a one-off that can't be used in other methods. We would need to look at all the other methods that take timestamps and ensure they work they are changed in the same way.

I'm not convinced that 'timestamps with timezones' are something we should be supporting though. It is not consistent with how other libraries and PHP itself handle timestamps. Timestamps conventionally are 'points in time' that have different date/time values depending on the timezone they are formatted into.

**Comment by ADmad** [comment]
I concur with @markstory, hence closing the issue.
