### ISSUE TITLE
Entity::isEmpty() behaves differently than method's comments

### ISSUE THREAD

**Issue by mtak3** [cakephp/cakephp#15339]
* [x] bug

* CakePHP Version: 3.x, 4.x
* Platform and Target: 

### What you did
`Entity :: isEmpty()` behaves differently than method's comments
```
     * This is not working like the PHP `empty()` function. The method will
     * return true for:
     *
     * - `''` (empty string)
     * - `null`
     * - `[]`
     *
     * and false in all other cases.
```

### What happened
`"0"` is true

### What you expected to happen
`"0"` is false
https://github.com/cakephp/cakephp/pull/10709#discussion_r137542451

**Comment by dereuromark** [comment]
Are you able to make a PR with the suggested changes?

**Comment by markstory** [comment]
Closing as this has been fixed on 3.x and master
