### ISSUE TITLE
Calling  a method in an associated Table does not modify variables passed by reference

### ISSUE THREAD

**Issue by japita-se** [cakephp/cakephp#15337]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9
* Platform and Target: httpd, mysql.

### What you did
I have two Tables `A` and `B`. `B` has a relation to `A` of type `belongsTo`. I have a custom method in `B`
```
public function test(&$a) {
   $['pippo'] = 'pippo';
}
```
In `A`'s Controller:
```
$a=[];
$this->loadModel('B');
$this->B->test($a); // this works and $a is getting modified
```

But 
```
$a=[];
$this->A->B->test($a); // this does not work and $a is not getting modified
```

### What happened
The $a variable is not getting modified.

### What you expected to happen
Why the two approaches give different results?

**Comment by garas** [comment]
`$this->A->B` is `Cake\ORM\Association` which forwards calls to target table:

https://github.com/cakephp/cakephp/blob/dcbf2095a61b87270b6a5baa11aef26a39f2bba2/src/ORM/Association.php#L1181-L1184

But it loses `&` while forwarding.  I'm not sure if there is another way to keep reference in `__call()`. Modifying to `function __call($method, &$argument) ` gives `Fatal error: Method Classname::__call() cannot take arguments by reference`.

So either refactor function to return modified array, or use `$this->A->B->getTarget()->test($a)` to get true table object.

**Comment by othercorey** [comment]
I don't think this is possible either. You'll need to access the table directly like garas explains.

**Comment by othercorey** [comment]
We couldn't change this until cakephp 5. Users will have to call `getTargetTable()` if they need to call special functions.
