### ISSUE TITLE
Error handling is logging silenced (@) errors in PHP8

### ISSUE THREAD

**Issue by AdmDevelopment** [cakephp/cakephp#15336]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.2.3
* Platform and Target: PHP8

### What you did
Triggered an error that is silenced by @ when using PHP8

### What happened
It logged the silenced error to error.log that should not be logged. Works properly in PHP7.4.

### What you expected to happen
It should not have logged the error.

The fix:
Error handlers that expect error_reporting to be 0 when @ is used, should be adjusted to use a mask check instead:
https://www.php.net/manual/en/migration80.incompatible.php

Can be fixed by replacing
"if (error_reporting() === 0) {"
with
"if (!(error_reporting() & $code)) {"

at line 151 in BaseErrorHandler.php.

**Comment by markstory** [comment]
Any chance you'd be interested in sending a pull request? You seem to know the code that needs to be changed already and have a setup to verify that it works.

**Comment by AdmDevelopment** [comment]
> Any chance you'd be interested in sending a pull request? You seem to know the code that needs to be changed already and have a setup to verify that it works.

I have created pull request #15338 with my changes.
