### ISSUE TITLE
BufferedIterator::firstMatch not able to find elements

### ISSUE THREAD

**Issue by notpron** [cakephp/cakephp#15341]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x/4.x (dcbf2095a61b87270b6a5baa11aef26a39f2bba2)
* Platform and Target: LAMP

### What you did
```
    public function testBufferedIterator() {
        $data = [['myField' => '1'], ['myField' => '2'], ['myField' => '3']];
        $buffered = (new \Cake\Collection\Collection($data))->buffered();
        // $buffered->count();
        debug($buffered->firstMatch(['myField' => '1']));
        debug($buffered->firstMatch(['myField' => '2']));
        debug($buffered->firstMatch(['myField' => '3']));
    }
```

### What happened
```
BufferedIteratorTest.php (line 42)
########## DEBUG ##########
[
  'myField' => '1'
]
###########################
BufferedIteratorTest.php (line 43)
########## DEBUG ##########
[
  'myField' => '2'
]
###########################
BufferedIteratorTest.php (line 44)
########## DEBUG ##########
null
###########################
```

### What you expected to happen
Third item should be found.

After adding a `$buffered->count()` the issue goes away, so something is likely off with the index.

**Comment by notpron** [comment]
I'm looking into a fix, but I'm having some trouble understanding the logic of BufferedIterator. It seems like it's relying a lot on valid() to be called. Now I'm looking at the SortIterator and am wondering why it's not more like that. Something as simple as the following would work, but I'm pretty sure I'm missing some important reason why it's not like that.

```
class BufferedIterator extends Collection
{

    /**
     * Maintains an in-memory cache of the results yielded by the internal
     * iterator.
     *
     * @param array|\Traversable $items The items to be filtered.
     */
    public function __construct($items)
    {
        $buffered = [];
        foreach ($items as $key => $val) {
            $buffered[$key] = $val;
        }
        parent::__construct($buffered);
    }
}
```

What am I missing here?

**Comment by markstory** [comment]
@notpron Iterating the items in the constructor could run into problems with streaming iterators. For example if you had a streaming database result set, iterating that result in the BufferedIterator constructor would likely exhaust the server memory as all the rows would be fetched.

Using `valid()` incrementally load results means that we only need to store results that have been seen/used.

**Comment by notpron** [comment]
Yeah, I see what you mean. I only suggested it because calling `count()` (which will be common) will net the same result.

The actual issues arises from `next()` incrementing the parent as well as the internal `_index`. Because the intention is to visit each entry from the internal collection only once, `parent::next()` should only be called if it's combined with `parent::valid()` and getting the current and key at the same time.

I'm thinking along the lines of:

```php
    /**
     * Returns whether or not the iterator has more elements
     *
     * @return bool
     */
    public function valid()
    {
        // if we've reached the end of the parent before (_finished) we can skip the following
        if (!$this->_finished && !$this->_buffer->offsetExists($this->_index)) {
            // parent is current behind our index pointer, catch up
            while(!$this->_finished && $this->_buffer->count() <= $this->_index) {
                $this->_finished = !parent::valid();
                if (!$this->_finished) {
                    $this->_buffer->push([
                        'key' => parent::key(),
                        'value' => parent::current(),
                    ]);
                }

                parent::next();
            }
        }

        if ($this->_buffer->offsetExists($this->_index)) {
            $current = $this->_buffer->offsetGet($this->_index);
            $this->_current = $current['value'];
            $this->_key = $current['key'];

            return true;
        }

        return false;
    }

    /**
     * Advances the iterator pointer to the next element
     *
     * @return void
     */
    public function next()
    {
        $this->_index++;
    }
```

**Comment by notpron** [comment]
However, it seems like it would also benefit from a more thorough change, as `BufferedIterator::current` and  `BufferedIterator::key` are not working without calling valid. This doesn't need to be the case: we could just update $this->_buffer more frequently.
