### ISSUE TITLE
Query::from() should accept VALUES list

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15359]
Anywhere a subquery is allowed, a `VALUES` list is also allowed. This is most commonly in a subquery.

The syntax is:

`SELECT * FROM (VALUES (v1, v2), (v3, v4)) as Alias (column1, column2)`

The column names are auto-generated and are implementation specific but you can specify the columns for the temporary values table in parenthesis after the alias.

https://www.postgresql.org/docs/current/queries-values.html

**Comment by CriztianiX** [comment]
In MySQL 8.0.19, this syntax is supported. please refer to https://dev.mysql.com/doc/refman/8.0/en/values.html

mysql> VALUES ROW(1,-2,3), ROW(5,7,9), ROW(4,6,8);

**Comment by othercorey** [comment]
Pinning so I will check on it before closing.

**Comment by dereuromark** [comment]
Do we want to support this for 4.3?

**Comment by othercorey** [comment]
MySQL supports this with VALUES ROW(), ROW() syntax which I don't think I'm going to add for 4.3.
