### ISSUE TITLE
Collection::avg() returns null when 0 rows

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15358]
```
        if ($result[0] === 0) {
            return null;
        }
```

It seems strange to me that the average of 0 is null instead of 0. This shouldn't try to mimic SQL behavior but give the user a useful result. This just causes the user to have to perform checks anyway so what's the point.

This is not documented in the book or api docs. You have to look at the return type to see it can be `null` and then read the code.

https://book.cakephp.org/4/en/core-libraries/collections.html#Cake\Collection\Collection::avg

https://api.cakephp.org/4.2/interface-Cake.Collection.CollectionInterface.html#avg

**Comment by markstory** [comment]
Returning an int|float consistently seems like a good improvement that should be backwards compatible as well.

**Comment by othercorey** [comment]
There is one scenario where this wouldn't be backwards compatible. 

Imagine you have rows with a column that you've somehow guaranteed to be within a specific range (100 - 200). The average, if there are rows, would always be in that range. If you have 0 rows and `avg()` returned null, there might be a situation where the avg is defaulted to a non-0 value.

You could re-create that logic with 0 (an unexpected) value, but the code would need to change.

This seems like a rare scenario. We could avoid it by adding a 2nd parameter to `avg()` with the default.

`avg($path, $default = null)`

**Comment by ADmad** [comment]
`$value = $collection->isEmpty() ? $collection->avg('foo') : $default` isn't too bad to handle the case you mention.

**Comment by othercorey** [comment]
I think it's a reasonable piece of code to expect, just want to point out the possible scenario.

I noticed that `median` has the same logic. There is more of an argument for null being a useful result from `median`, but this would make it stand alone.

**Comment by garas** [comment]
Mathematically average of empty set is undefined. I think it is more reasonable to leave `null` as is.

Code always can have `$set->avg('path') ?? $default`

**Comment by ADmad** [comment]
For reference Laravel's collection too returns `null` for average and medium for an empty collection. So I guess it's better to just keep what we have.

**Comment by othercorey** [comment]
We should be consistent then. Although 0 is probably the only default, users could use null as a count check.

**Comment by othercorey** [comment]
Documented return value and behavior instead - https://github.com/cakephp/cakephp/pull/15361
