### ISSUE TITLE
Command is not found if it is inside a folder

### ISSUE THREAD

**Issue by ishan-biztech** [cakephp/cakephp#15356]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: `3.9.3`
* Platform and Target: -

### What you did
Created a command inside a directory `src/Command/Onetime` named `MigrateDataCommand`.

### What happened
Currently there's no way to run this command it doesn't show up when we run `bin/cake list` command. Neither it works when I run `bin/cake migrate_data` or `bin/cake onetime/migrate_data`. I even tried [changing the default command name](https://book.cakephp.org/3/en/console-and-shells/commands.html#changing-the-default-command-name) to something different, but no luck.

### What you expected to happen
I think this should work, either by some convention or something. I don't know if it's a feature discussion or a bug, but I think we should give this ability.

My use case here is that I want to group commands that are only run once in separate directory that way in future we can delete this command file as all these commands are only used once and then no need of it anymore. Like data migration command, etc.

**Comment by dereuromark** [comment]
Many types of classes that are auto-detected are so only by convention on the primary level of namespace (for cost/runtime reasons).
So here, best to either keep the list flat or use plugins for nesting.

It is expected behavior right now, as for Controllers (small exception of prefix), Components, Behaviors, ...)

**Comment by ADmad** [comment]
As pointed out by @dereuromark conventionally only classes directly under the `Command` folder are auto detected.

You can use the `Plugin::console()` or `Application::console()` hooks to explicitly add classes at non default location to the command collection using their FQCN as shown [here](https://github.com/cakephp/bake/blob/a06d520a513150d28987f4921fcd4eadfefb68ed/src/Plugin.php#L76).
