### ISSUE TITLE
Error: array_merge() does not accept unknown named parameters

### ISSUE THREAD

**Issue by antonvolokha** [cakephp/cakephp#15372]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.24 commit: cf14e6546ec44e33
* Platform and Target: docker php:8-apache

### What you did
Run console/cake bake fixture
Then choose my model, after that answer on all questions

### What happened
`
Error: array_merge() does not accept unknown named parameters
#0 /var/www/html/lib/Cake/Utility/Folder.php(230): array_merge(/var/www/html/lib/Cake/Console/Templates/default/actions: Array, /var/www/html/lib/Cake/Console/Templates/default/classes: Array, /var/www/html/lib/Cake/Console/Templates/default/views: Array)
#1 /var/www/html/lib/Cake/Console/Command/Task/TemplateTask.php(75): Folder->read()
#2 /var/www/html/lib/Cake/Console/Command/Task/TemplateTask.php(50): TemplateTask->_findThemes()
#3 /var/www/html/lib/Cake/Console/Shell.php(511): TemplateTask->initialize()
#4 /var/www/html/lib/Cake/Console/Command/Task/FixtureTask.php(288): Shell->__get('Template')
#5 /var/www/html/lib/Cake/Console/Command/Task/FixtureTask.php(270): FixtureTask->generateFixtureFile('Admin', Array)
#6 /var/www/html/lib/Cake/Console/Command/Task/FixtureTask.php(170): FixtureTask->bake('Admin', 'admins', Array)
#7 /var/www/html/lib/Cake/Console/Command/Task/FixtureTask.php(116): FixtureTask->_interactive()
#8 /var/www/html/lib/Cake/Console/Shell.php(459): FixtureTask->execute()
#9 /var/www/html/lib/Cake/Console/Shell.php(456): Shell->runCommand('execute', Array)
#10 /var/www/html/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('Fixture', Array)
#11 /var/www/html/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/html/app/Console/cake.php(37): ShellDispatcher::run(Array)
#13 {main}
`

**Comment by othercorey** [comment]
We are not supporting PHP 8 for CakePHP 2.x.

See https://github.com/cakephp/cakephp/issues/15197

**Comment by antonvolokha** [comment]
> We are not supporting PHP 8 for CakePHP 2.x.
> 
> See #15197

Okay ;( But it works good on production)))

**Comment by markstory** [comment]
Supporting PHP8 with CI would have required several breaking changes in dependencies or other workarounds that we were not willing to commit time to given that 2.x was going to be end-of-life last 1 month after PHP8 was released.

**Comment by Shabasha** [comment]
It is too late to fix this issue 
Bug : Folder.php / 230 => $files = call_user_func_array('array_merge', $files);

Try to use array_values to pass values of the $files array like this : 
Fix : Folder.php / 230 => $files = call_user_func_array('array_merge', array_values($files));

It should fix the issue.

**Comment by parasBisht** [comment]
https://github.com/kamilwylegala/cakephp2-php8
