### ISSUE TITLE
CakePHP 3.9.7 breaks muffin/footprint plugin

### ISSUE THREAD

**Issue by reloxx13** [cakephp/cakephp#15377]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.7
* Platform and Target: nginx,mysql,debian buster

### What you did
composer update
cakephp updating to 3.9.7

### What happened
after updating cakephp, the muffin/footprint (v1.2.2) throws a 500.

### What you expected to happen
geting the user from the muffin/footprint plugin

![grafik](https://user-images.githubusercontent.com/14855001/110430677-049c9400-80ad-11eb-8c12-a593c04767db.png)

**Comment by reloxx13** [comment]
Ah, i just saw we got a 2.x verion of footprint, ill try and close if it works.

**Comment by reloxx13** [comment]
The 2.x verion of footprint does not work with cakephp 3.x.

**Comment by othercorey** [comment]
Without going into details, the exception is showing a real issue, but the footprint code is doing it on purpose. 

We'll have to push out a patch for 3.9.8 to avoid this.

**Comment by othercorey** [comment]
Fixed in 3.9.8

**Comment by reloxx13** [comment]
thank you!
