### ISSUE TITLE
PaginatorHelper::limitControl() form escapes query parameters in URL

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp#15382]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.4
* Platform and Target: MacOS/Ubuntu

### What you did
In my Controller I'm using friendsofcake/Search and have a search applied. Request URL is `/batches?owner=Ch%2A&expected_sku=TST%2A` and the form action generated is `/batches?owner=Ch%2A&amp;expected_sku=TST%2A`

### What happened
The Form action for the `PaginatorHelper::limitControl()` should not escape the URL. But really this boils down to https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L413 not having an ['escape' => false] since `UrlHelper` defaults to escaping a URL.

### What you expected to happen
The `PaginatorHelper::limitControl()` form should have an action of `/batches?owner=Ch%2A&expected_sku=TST%2A`

**Comment by othercorey** [comment]
@markstory Does this need to be fixed in 4.3.0 or can it be a bug fix?

**Comment by markstory** [comment]
It can go into either release I think. Once fixed, the output will the same or better.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue, I have a pull request open to add a test for this scenario. Did I miss something to cause it to happen?

**Comment by challgren** [comment]
Well its been so long I'm unable to reproduce this now. But I am noticing that if I have query string parameters set and use the Paginator->limitControl() and choose a value the query string is remove and just the limit is applied.

**Comment by markstory** [comment]
> But I am noticing that if I have query string parameters set and use the Paginator->limitControl() and choose a value the query string is remove and just the limit is applied.

That sounds like a different issue. We have a test covering that scenario (added in #15878) I wonder what could be different about your setup?

Going to close this as the escaping is intentional. If you find a way to reproduce the new problem you're seeing please open an issue :smile:
