### ISSUE TITLE
Support for OLAP database : Clickhouse

### ISSUE THREAD

**Issue by imdad** [cakephp/cakephp#15385]
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.4
* Platform and Target: Clickhouse Database.

[Clickhouse](https://clickhouse.tech/docs/en/) is a OLAP database which can be used in Analytics/BI applications. The database is already compatible with [MySQL protocol](https://clickhouse.tech/docs/en/interfaces/mysql/) to some extend. If CakePHP could support this database in its ORM it would be a great addition to CakePHP framework. May be we could start with supporting its data types and table engines for the first phase and later add more support.

**Comment by markstory** [comment]
This sounds like a great thing to do in a plugin. Clickhouse cannot be used in the same way as a tranditional OTLP based database and the existing ORM abstractions are not suitable.

**Comment by othercorey** [comment]
Closing as out of scope.
