### ISSUE TITLE
Cake\I18n\PluralRules::calculate changes

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15383]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.4
* Platform and Target: Windows 10 PHP 7.4

**I was having trouble with Plurals. Cake was always returning singulars.**
I found that `Cake\I18n\PluralRules::calculate` does:

```php
if (!isset(static::$_rulesMap[$locale])) {
    $locale = explode('_', $locale)[0];
}

if (!isset(static::$_rulesMap[$locale])) {
    return 0;
}
```

So it always returns 0 (singular) because I'm not using **underscode** but an **hyphen**:
using es-ES instead of es_ES

I searched on the Internet looking for the correct form and some people says the correct is the former and some others the latter.

So I have two questions ~~and a bug~~:

### Question 1
Could we accept both forms? It could be done with:
- `str_replace('-', '_', $locale)`
- or `preg_match('/^[A-Za-z]+/', $locale, $out)`

### Question 2
I don't know if this is possible but what are *.po headers for? Could we extract the `Plural-Forms` rule from it?
Example:
```gettext
"Project-Id-Version: PROJECT VERSION\n"
"POT-Creation-Date: 2020-12-15 21:32+0000\n"
"PO-Revision-Date: 2021-02-23 23:12+0000\n"
"Last-Translator: Hache_raw <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <EMAIL@ADDRESS>\n"
"Language: es-ES\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"  <------- THIS
"X-Generator: Poedit 2.4.1\n"
```

### ~~Bug~~
~~`static::$_rulesMap[]` has a value which is: 'pt_pt'.~~
~~That will never be used because of the current `explode('_', $locale)[0]`;~~

**Comment by hacheraw** [comment]
I just removed the "bug" part. I was wrong.

**Comment by markstory** [comment]
> Could we accept both forms? It could be done with:

Converting `-` to `_` to increase interoperability with other tools/po files seems reasonable to me.

> I don't know if this is possible but what are *.po headers for? Could we extract the Plural-Forms from it?

It is possible but not all po files contain the plural headers which is why we have the lookup table.
