### ISSUE TITLE
CacheSession TTL vs. Session.timeout

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15387]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.13
* Platform and Target: linux, nginx, php7.4, redis

### What you did
Session storage configured like this
```
    'Session' => [
        'defaults' => 'cache',
        'cookie' => '__Host-CAKEPHP',
        'timeout' => 60 * 60 * 24 * 7,
        'ini' => [
            'session.cookie_secure' => true,
            'session.cookie_samesite' => 'Lax',
            'session.cookie_lifetime' => 60 * 60 * 24 * 7,
        ],
    ],
```

### What happened
'cache' defaults will use Cache configuration 'default', which can have different, and in this particular case had far shorter duration than what was configured in Session (both timeout and ini)

Result was that session was ending on Cache.timeout/Redis.ttl not on Session.timeout interval

### What you expected to happen
I expected CacheSession handler to propagate `Session.timeout` as `Cache.ttl` when writing the session data to cache

**Comment by markstory** [comment]
> I expected CacheSession handler to propagate Session.timeout as Cache.ttl when writing the session data to cache

Should there be an error if those timeouts are not aligned. Silently overwriting a defined configuration value seems like it will be differently hard to debug/track down.

**Comment by smarek** [comment]
Agree, i'd probably prefer warning instead of error, and probably only when cache timeout/ttl is shorter than session.timeout, otherwise i'd expect session to expire correctly and get removed from storage by SessionHandler `gc()`

**Comment by markstory** [comment]
Moving to enhancement. All of the code is doing what it should, but we can improve developer experience by letting them know their configuration will yield poor results.
