### ISSUE TITLE
Split session storage based on session contents (authentication status)

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15391]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.1.7
* Platform and Target: nginx, php7.4, redis, mysql db

### Environment
Let's have a cluster application, 1x standalone DB, 1x shared redis cache, 1x shared S3 file storage, 3x Frontend (CakePHP) instances covered by HAProxy (or different loadbalancer)

### Situation
Writing session into database (long-term store) is expensive, and validating the session with database is expensive as well.  
When general public visits the frontend webapp, in my case, there is no need to assign the session id unless the user authenticates with the services.

### Proposal
SessionHandler should be aware of session context, ie. whether the user is authenticated or whether the session data / session handler, define the desired storage method.

Right now the parent SessionHandlerInterface is not aware of anything useful, and there is no optional switching logic regarding the decision, what to do with the session, or where to store it.

### Intermediate solution
I wrote this ugly hack, extending the default session storage (in my case DatabaseSession) to avoid persisting sessions, that do not contain authentication data, into database. Browser/Client will still poses the session cookie which can eventually be used to access authentication/flash/other session-related works.

```php
<?php
declare(strict_types=1);

namespace App\Session;


use Cake\Http\Session\DatabaseSession;

class SelectiveSessionHandler extends DatabaseSession
{

    public function write($id, $data): bool
    {
        if (
            empty($data) ||
            // if does not contain Auth data
            preg_match('/}Auth\|/', $data) == 0
        ) {
            // returning false triggers warning in failed session_write_close
            // faking success to avoid touching DB
            return true;
        }

        return parent::write($id, $data);
    }

}
```

**Comment by markstory** [comment]
> SessionHandler should be aware of session context, ie. whether the user is authenticated or whether the session data / session handler, define the desired storage method.

This sounds like the kind of thing you could do in a custom session handler that either wraps the handlers that the framework provides or implements the required logic directly.

**Comment by smarek** [comment]
Ok, thank you for clarification, i'm closing this idea ticket
