### ISSUE TITLE
debug() cause "Headers already sent" in a new project (4.2.4)

### ISSUE THREAD

**Issue by mathieugrimault** [cakephp/cakephp#15398]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cakephp/cakephp (4.2.4)
* Platform and Target: Debian Buster PHP 7.3.19-1~deb10u1

### What you did
Create a new project : composer create-project --prefer-dist cakephp/app test
Add "debug("test");" in src/Controller/PagesController.php:63

### What happened
 APP/Controller/PagesController.php (line 63)
'test'

Warning (512): Unable to emit headers. Headers sent in file=/var/www/html/test/vendor/cakephp/cakephp/src/Error/Debugger.php line=1030 [CORE/src/Http/ResponseEmitter.php, line 71]

Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/html/test/vendor/cakephp/cakephp/src/Error/Debugger.php:1030) [CORE/src/Http/ResponseEmitter.php, line 168]

Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/html/test/vendor/cakephp/cakephp/src/Error/Debugger.php:1030) [CORE/src/Http/ResponseEmitter.php, line 197]

Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/html/test/vendor/cakephp/cakephp/src/Error/Debugger.php:1030) [CORE/src/Http/ResponseEmitter.php, line 197]

### What you expected to happen
No error displayed.

**Comment by dereuromark** [comment]
This is how PHP works.
if you don't want that, use dd() to really stop code execution or a debugger and your IDE to step through.

**Comment by mathieugrimault** [comment]
Yes but in cakephp 3.8.0 (just tested now), this error doesnt happen. Only the debug statement is shown as expected.

**Comment by ndm2** [comment]
You'll experience the same behavior in 3.x once your configured `output_buffering` size (usually defaults to `4096` bytes) is exceeded. Debug output in 4.x has become way larger as it now sports syntax highlighting, so it easily exceeds even larger output buffers.

You can either live with it, or increase your output buffering for debugging.

**Comment by markstory** [comment]
This isn't a bug, you're creating output. The 4.x implementation creates a bit more output due to HTML formatting which is exceeding your web servers output buffer.
