### ISSUE TITLE
Add JSON format output to the ConsoleLog

### ISSUE THREAD

**Issue by bor-attila** [cakephp/cakephp#15393]
This is a:

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: All
* Platform and Target: Kubernetes (Google Cloud Engine), but I think all container environment is affected

### What you did
Based on the [12factor app](https://12factor.net/logs) recommendations (and ofc bcz it's logic) in Kubernetes I changed the logging output from File, Database etc ... to Console. GCE automatically offers you a very nice, feature rich logging system, where you can store and search logs very easily. 

### What happened
Multiline outputs are recorded as separate log events bcz is separated with new lines (like stack trace). So the first line of message <error> and the closing </error> 'tag' is logged separately (new insertId, new timestamp, etc ...).
But the bigger problem is I can't search in the full textPayload.

### Solution
One solution can be monolog, but only for formatting reason I didn't wanted to add a new package to my project
Another solution is the custom logger

I wrote an ugly ConsoleJsonLog class (bcz I needed a solution fast) what extends the ConsoleLog.
```php
public function log($level, $message, array $context = [])
{
    $this->_output->write(json_encode([
        'level' => $level,
        'date' => $this->_getFormattedDate(),
        'content' => $this->_format($message, $context),
        'context' => $context
    ]));
}
```

After this, all log entries (until now) are logged as 1 line (even multiline output) and I can make some ["crazy" query](https://cloud.google.com/logging/docs/view/advanced-queries#introduction).

My solution is not a really good solution, bcz:
* json_encode paramaters are not customizable
* I think BaseLog::_format not fully really neccessary
* what if $context is a resource
* maybe fallback if json_encode fails
* the 'content' key should be named 'message' : D

### Suggestion
In my opinion, the ConsoleLog should have a default 'json' (=false) option which accepts a boolean or an array (with json_encode params).
When it's enabled, the 'outputAs' must be forced to use RAW (???) and the output instead of `<level>%message</level>` must be a json string.

Before:
<img src="https://user-images.githubusercontent.com/6832955/110946520-3f1d5f80-833f-11eb-90d6-3db812162e6c.jpg" width=150 />

After:
<img src="https://user-images.githubusercontent.com/6832955/110946612-5ceac480-833f-11eb-8aa8-ee670baf57b4.jpg" width=150 />
<img src="https://user-images.githubusercontent.com/6832955/110946621-5fe5b500-833f-11eb-8c89-9b0520737c04.jpg" width=150 />

**Comment by markstory** [comment]
> In my opinion, the ConsoleLog should have a default 'json' (=false) option which accepts a boolean or an array (with json_encode params).

What about a JsonConsoleLog adapter instead? The console logger already has a few options for colouring which wouldn't be needed in a containerized environment, and JSON formatting is not something you would want in a developer environment generally.

**Comment by bor-attila** [comment]
After some search, I must say you are right. 
An adapter would be much better, not just bcz of coloring simply bcz Json logging can have a lot of options.

First of all: naming.

I wouldn't name it `JsonConsoleLog` bcz how the log is handled is more important than the format, so `ConsoleJsonLog` would be better imo.

As you can see in my example the ConsoleLog did the job, _reached the destination_ just simply painful to process it. The format is secondary, but in my case it's pretty important.
That's why I would name it `ConsoleJsonLog` instead of JsonConsoleLog. I suggest `<Handling><Format>Log` naming.

Or .. what about simply `JsonLog`? Let's start with console, and in the future we can extend it with HTTP, TCP or UDP.

What about the options? Options: `levels` and `scopes` are basic stuff + params for `json_encode`.

We need a `stream` options if we don't plan to put networking in this adapter (Http,tcp,udp), or an `output` if we do.

`output` can be `php://stderr` or `php://stdout` and in the future one of the following: `http://x.y.z.w:port`, `udp://x.y.z.w:port`, `tcp://x.y.z.w:port`

How the final JSON should look like ?

I can recommend [GELF Payload Specification](https://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) or at least we need a versioning/formatting option.

So if the `version` or `format` option is set to `BaseFormat::class` the JSON should look like this:

```json
{
  "host": "example.org",
  "message": "Hello, world!",
  "timestamp": "2021-03-16 00:00:00",
  "level": 1,
  "context": ["test"]
}
```

If the `version` or `format` is set to `GraylogExtendedLogFormat::class` the JSON should look like this:

```json
{
  "version": "1.1",
  "host": "example.org",
  "short_message": "Hello, world!",
  "full_message": "We can use this field ???",
  "timestamp": 1385053862.3072,
  "level": 1,
  "_context": ["text"],
}
```

These classes must implement a common interface to give the ability to anyone to create their own JsonFormatter.

But I think I went too far ... : )

**Comment by markstory** [comment]
> I wouldn't name it JsonConsoleLog bcz how the log is handled is more important than the format, so ConsoleJsonLog would be better imo.

I'm fine with that name too.

> Or .. what about simply JsonLog? Let's start with console, and in the future we can extend it with HTTP, TCP or UDP.

This points to a problem I've been avoiding in our logging framework which is separating the message formatting and the message transport/delivery system. We could introduce them in 4.3, but I would want to be careful that all of the existing loggers maintain their current formatters.I don't know if *now* is the time to introduce formatters, but it could help if we maintain backwards compatibility.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15559
