### ISSUE TITLE
Should ConnectionInterface define connect method?

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#15401]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.4
* Platform and Target: any

### What you did

Running `phpstan` inside **templates** directory from a clean clone of [cakephp\app](https://github.com/cakephp/app) I got the message:

```
 ------ -----------------------------------------------------------------------------
  Line   templates/Pages/home.php
 ------ -----------------------------------------------------------------------------
  145    Call to an undefined method Cake\Datasource\ConnectionInterface::connect().
```

...and some others I will put on that repository.

### What you expected to happen

i reviewed the `\Cake\Datasource\ConnectionInterface` and `\Cake\Database\Connection` code and found the method `connection()` are only on implementation class.

Its that a bug or is by design?

**Comment by markstory** [comment]
> Its that a bug or is by design?

That is partially by design. Not all connection types need an active connection to be created. For example the elasticsearch plugin doesn't have a connect() method on its connection class. We should probably use a `method_exists()` guard in the setup page though.

**Comment by CauanCabral** [comment]
> Not all connection types need an active connection to be created.

That's true, just a test in the setup page should be enough.
