### ISSUE TITLE
Unable to save associated BTM data

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#15407]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.4
* Platform and Target: PHP 7.4.12, MacOS 10.15.7

### What you did
Trying to patch/save a belongs to many association data when a primary key is non-standard (in the sense that I have a composite pk) doesn't work.
```
#PostsTable
'belongsToMany' => [
    'Tags' => [
        'through' => 'PostsTags',
    ],
],

#PostsTagsTable
public function initialize(array $config): void
{
    $this->setPrimaryKey(['post_id', 'tag_id', 'primary']);
}

#Save function in PostsTable
$tags = [
    [
        'id' => 123,
        '_joinData' => ['primary' => 1],
    ],
];
$post = $this->get(155);
$this->patchEntity($post, compact('tags'));
$this->save($post);
```

### What happened
`Cannot insert row, some of the primary key values are missing. Got (155, 123, ), expecting (post_id, tag_id, primary)`

### What you expected to happen
I should be able to patch the `$post` and have it save the Tags association. This is working for me in my old Cake 3.3 project. I've tried debugging on my own but I don't know where the marshaller is going wrong or if the shape of my data is wrong.

**Comment by markstory** [comment]
Is the `primary` column part of your primary key data? Do you have a stacktrace for the error you're getting?

**Comment by othercorey** [comment]
Closing due to no response.
