### ISSUE TITLE
TreeBehavior Recover doesn't work with large data sets

### ISSUE THREAD

**Issue by irpguardian** [cakephp/cakephp#15408]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.9
* Platform and Target:  RHEL7, PHP 7.2.24,  Apache/2.4.6, MariaDB 5.5.68

### What you did
After populating a database with approx. 5.1 million items, and having  the requisite parent_id, lft, and rght columns, running a console run version of tree recover does not ever complete running, even when the process had been niced to a near-runtime priority and having being run for 2+ weeks.

Example of RebuildtreeCommand:
`public function execute(Arguments $args, ConsoleIO $io)
{
    $this->Files->recover();
}`

I had been testing the volume of data that tree-recovery can handle before it just doesn't finish anymore with with data, and it worked fine for smaller subsets. Once it hits about over ~1million entries the tree recover no longer finishes.

### What happened
Tree recover never finished recovering the tree after very long period of time

### What you expected to happen
I had expected it to take a while, but not a seemingly infinite amount of time to complete a tree recovery with only 5.1 million elements.

I also could not find any documentation in the cakephp cookbook about how long the operation takes on a volume of data, nor if there were any upper limits for tree behavior either.

If you require any more information, please let me know.

Thank you for your support.

**Comment by markstory** [comment]
Are all 5.1 million records in a single tree?

**Comment by irpguardian** [comment]
Yes, they are all in one single tree

**Comment by markstory** [comment]
Yeah you'll need some beefy machines to get that done and even then it will be very slow to recover 5.1 million records. You might want to consider using [scoped trees](https://book.cakephp.org/3/en/orm/behaviors/tree.html#scoping-and-multi-trees) as the number of rows and operations that are required to recover the trees will be smaller.

There are no limits in the book as the max size depends on your hardware and pain tolerance :smile:

**Comment by irpguardian** [comment]
Could you elaborate more on how to do that? It seems like scoped trees only work for trees that already have their relations already built, and not for non-recovered trees. I have identified how I could possibly use a scoped tree using one of my data-columns as the scope (able to divide my working set into about 6 separate trees) but from the cakephp cookbook, it appears that I can only do this scoping 1 at a time.

**Comment by markstory** [comment]
Yes, you couldn't retrofit a scoped tree into a 5.1 million record single tree. Yes you can only query across a single scoped tree at once. You can change the scoped tree using `setConfig()`

**Comment by othercorey** [comment]
@irpguardian Does your database have a high number of queries? Is the CPU % high on your php server? Is everything idle but taking a long time?

**Comment by irpguardian** [comment]
> @irpguardian Does your database have a high number of queries? Is the CPU % high on your php server? Is everything idle but taking a long time?

Right now, the database does not have many queries since it's still in development. And when doing the tree recovery, it looks like there is little to no cpu usage but like I mentioned before, whenever it ran a tree  recovery, it never really finished, even after spending over 2 weeks running.

**Comment by othercorey** [comment]
> Right now, the database does not have many queries since it's still in development.

I am talking about during the recovery. Is there an open query when it is idle or are queries still being created?

**Comment by irpguardian** [comment]
A follow-up on what has occurred in the past week,
After another developer on our team was looking at what was going on with the rebuild process, he determined that we should add an index to the parent_id field. After doing so (create index parent_id_table_index on table(parent_id);), I ran the tree recover again, and this time it was able to complete in just about an hour(!) with our same 5.1 million item tree.

**Comment by ADmad** [comment]
Closing as the mystery is solved and I have opened a PR to update the manual.
