### ISSUE TITLE
getOriginal() returns new value when property was not originally set

### ISSUE THREAD

**Issue by sheldonreiff** [cakephp/cakephp#15402]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.9

### What you did
When a particular field is not set on a new entity, I set the field, then call `getOriginal()`.
```
    /** @test */
    public function demonstrates_get_original_unexpected_behavior_when_value_is_not_set()
    {
        $entity = new Entity();

        $this->assertNull($entity->field);
        $this->assertNull($entity->getOriginal('field'));

        $entity->set('field', 'example');

        $this->assertEquals('example', $entity->getOriginal('field'));
    }

```

### What happened
The test passes. `getOriginal()` returns 'example'.

### What you expected to happen
 I wouldn't expect it to pass and for `getOriginal()` to return null. Is this expected?

**Comment by ADmad** [comment]
This is expected behavior. A non existent value is not considered the "original" value. In your example since `'example'` is the initial value set, it's the original value.
