### ISSUE TITLE
How to do the Cakephp3.4 Application Performance Monitoring

### ISSUE THREAD

**Issue by NareshKurukuti** [cakephp/cakephp#15410]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.
* Platform and Target: Apache, MySQL, and Angularjs

### What you did
Application Build in CakePhp3.4 with MySQL and Frontend Angularjs.

### What happened
It takes a long time to load the application. 

### What you expected to happen
I want to Application Performance Monitoring.  How can I achieve it and how to analysis the each request and response time.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
