### ISSUE TITLE
TypeError : str_replace() on missing database connection instead of MissingConnectionException

### ISSUE THREAD

**Issue by samuelgfeller** [cakephp/cakephp#15415]
This is a
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: `cakephp/database` `4.2.4`
* Platform and Target: XAMPP 3.2.4 on Windows 10, PHP8.0, MariaDB, ran on CLI (PHPUnit `9.5.4`) or normal request

### What you did
1. Forget to start database server in XAMPP
2. Run integration test with PHPUnit 
Edit: making a normal request that needs database access makes the same error 

### What happened
Following error happened: 
```
TypeError : str_replace(): Argument #3 ($subject) must be of type array|string, null given
 C:\xampp\htdocs\project\vendor\cakephp\core\App.php:141
 C:\xampp\htdocs\project\vendor\cakephp\database\Driver.php:142
 C:\xampp\htdocs\project\vendor\cakephp\database\Driver\Mysql.php:178
```

### What you expected to happen
Expected that a `MissingConnectionException` is thrown, not a `TypeError`.  
Code from `Driver.php` 
```php
try {
    $retry->run($action);
} catch (PDOException $e) {
    throw new MissingConnectionException(
        [
            'driver' => App::shortName(static::class, 'Database/Driver'), // line 142, TypeError happening in App::shortName
            'reason' => $e->getMessage(),
        ],
        null,
        $e
    );
```

**Comment by ADmad** [comment]
The line mentioned in the stack trace is this:

https://github.com/cakephp/cakephp/blob/80cc7872a800db1533049571362226b246fd6aea/src/Core/App.php#L141

`Configure::read('App.namespace')` returning `null` seems to be an app config/bootstrapping issue rather than missing database connection.

**Comment by samuelgfeller** [comment]
Feel free to change the title accordingly. I don't know much about Cake and just wrote how the issue presented in my POV which is not accurately describing the issue.

**Comment by othercorey** [comment]
Telling us to change the bug doesn't help us fix it. You said the issue is from not starting the db.  Is App.namespace defined?

**Comment by samuelgfeller** [comment]
I'm not using the whole CakePHP Framework (just `cakephp/database`) and thus know pretty much nothing about it apart from some query builder syntax.  I don't know what `App.namespace` is and how I can check if it is defined.   
The only thing I know is that when I have the database running, the issue doesn't appear and the query builder works fine but when the db is stopped, this error happens. 

I would gladly follow debugging steps to help fix the bug though if you tell me what I can do.

**Comment by ADmad** [comment]
> I'm not using the whole CakePHP Framework (just cakephp/database) 

This is the important piece of info, which should help us investigate the issue, thank you.
