### ISSUE TITLE
Cakephp4 throws invalid argument exception while retrieving data 

### ISSUE THREAD

**Issue by Ganesh-kvk** [cakephp/cakephp#15419]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.1
* Platform and Target: PHP 7.4.12

### What you did
We are just using a simple query to find users. We have multi databases for each of our customer. Below is the query call
```
$Users = TableRegistry::get('Users');
$users_data = $Users->find()->order(['id'=>'ASC']);
if(!empty($user_data)){
   $users_data->toArray();  
}
```

### What happened
**In production environment it some times gives below error, I went to **CustomerManagementsController** to check what is the cause I found above query where it throws exception**

```
- Error: [InvalidArgumentException] Cannot convert value of type `string` to integer in /var/www/vhosts/vhostsproduction/cpanelnew.ceipal.com/vendor/cakephp/cakephp/src/Database/Type/IntegerType.php on line 40
- Stack Trace:
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Database/Type/IntegerType.php:91
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Database/FieldTypeConverter.php:134
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Database/Statement/CallbackStatement.php:63
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/ORM/ResultSet.php:427
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/ORM/ResultSet.php:261
- - iterator_to_array - [internal], line ??- /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php:676
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:309
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/src/Controller/CustomerManagementsController.php:246
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Controller/Controller.php:521
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:79
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/BaseApplication.php:251
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:77
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:159
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:73
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:166
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:73
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:73
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:121
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:73
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Runner.php:58
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/vendor/cakephp/cakephp/src/Http/Server.php:90
- - /var/www/vhosts/vhostsproduction/Ourwebserver.com/webroot/index.php:40
```

### What you expected to happen
I Just needed result array but it is not happening.Can any one suggest how to fix this.

I tried to find solution through stackoverflow but nothing helped as it is just find query with out any conditions.

**Comment by markstory** [comment]
That error implies that you have a field mapped as an integer but it contains values that cannot be converted to an integer.

**Comment by Ganesh-kvk** [comment]
> That error implies that you have a field mapped as an integer but it contains values that cannot be converted to an integer.

Mark, Can you please suggest how can we verify that integer as we are pulling all the users array. We verified table structure and all are fine. But still it is throwing exception.

**Comment by markstory** [comment]
You can check that the reflected schema metadata that cake is using with `debug($User->getSchema())`. This will show you the columns and what type the ORM thinks they are. This metadata is used to cast values when data is read (amongst other uses). You would be looking for columns that the ORM thinks are integers but contain strings or values that cannot be converted to PHP integers.

If none of that is working you can use `$query->disableResultsCasting()` to turn off result casting. This isn't ideal as you'll need to do it all over the place. It is better to figure out the data issue that is causing the problem.

**Comment by Ganesh-kvk** [comment]
> You can check that the reflected schema metadata that cake is using with `debug($User->getSchema())`. This will show you the columns and what type the ORM thinks they are. This metadata is used to cast values when data is read (amongst other uses). You would be looking for columns that the ORM thinks are integers but contain strings or values that cannot be converted to PHP integers.
> 
> If none of that is working you can use `$query->disableResultsCasting()` to turn off result casting. This isn't ideal as you'll need to do it all over the place. It is better to figure out the data issue that is causing the problem.

Thank your mark for the help, I will follow the process as you suggested.
