### ISSUE TITLE
Exception if field does not exist

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#15423]
https://github.com/cakephp/cakephp/blob/76babd83538e3e247d1189c2289b2f7b31c2bc9a/src/Datasource/EntityTrait.php#L275-L295

Shouldnt it throw `InvalidArgumentException` if field does not exist?

It will help possible issues when user forgot to add some field to database query.

Sounds like good thing for 5.0

**Comment by markstory** [comment]
I agree that this kind of change is something that would need to be in 5.0. I agree it helps applications become more strict, but my concern is how many applications it could break.

**Comment by othercorey** [comment]
We can add this to the 5.0 ideas wiki to evaluate then.

**Comment by othercorey** [comment]
Added to wiki.
