### ISSUE TITLE
Time manipulation unexpected result due to setters order

### ISSUE THREAD

**Issue by BenoKop** [cakephp/cakephp#15422]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4.
* Platform and Target: Nginx, MySQL

### What you did
Hello, I tried to manipulate a date like this :
```
$now = new Time();
$now->day(31)
    ->month(3)
    ->year(2021);
$now->format('Y-m-d H:i:s');
```

### What happened
returns 2021-03-**01** 10:34:11

### What you expected to happen
to return 2021-03-**31** 10:34:11

After looking at the documentation, I figured out that the order of the manipulation is different:
```
$now = new Time();
$now->year(2021)
    ->month(3)
    ->day(31);
```
In that order, it works perfectly.

I know that i'm on an older version, but it maybe still persists on other versions ?

Thanks.

**Comment by othercorey** [comment]
Depending on the month you're in, the day 31 might not exist. This modifies the date, it does not "build" it.

**Comment by BenoKop** [comment]
I mean, the day 2021-03-31 exists, it was yesterday ?

**Comment by garas** [comment]
```
$now = new Time(); // 2021-04-01
$now->day(31) // 2021-04-31 not exists, next day is 2021-05-01
    ->month(3) // 2021-03-01
    ->year(2021); // 2021-03-01
```

Use `setDate(int $year, int $month, int $day)` instead.

**Comment by BenoKop** [comment]
Thanks for the explanation, it is clearer for me now.
