### ISSUE TITLE
Easier way to extend database schema capabilities

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/cakephp#15435]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.next
* Platform and Target: any

### Allow extending Schema types support

Recently I tried to implement [tsvector](https://www.postgresql.org/docs/current/textsearch-intro.html#TEXTSEARCH-INTRO-CONFIGURATIONS) type support following [Cookbook](https://book.cakephp.org/4/en/orm/database-basics.html#adding-custom-database-types). Aside from get the new type running in my app, I can't do tests for code using that column.

> Note: to setup my database table and indexes, I run migrations with RAW sql

To support that type on fixture, I need to extend `Cake\Database\Schema\PostgresSchemaDialect` - at least methods `_convertColumn()` and `columnSql()`. But after I have a new class for `PostgresSchemaDialect`, I can't inject it into the database _driver_ `Cake\Database\Driver\Postgres`.

- Should I build another _driver_ extending `Cake\Database\Driver\Postgres` with support to FTS (full text search)? So I can attach the new _dialect_ inside it and use the new driver on my connection setup.
- Is this also somebody else problem and I can help implement a new configuration to inject _dialect_ when `ConnectionManager` initialize the _driver_?

Support `schema` type is just the first step. There are two new _indexes_  types and some useful sql _functions_ .

**Comment by ndm2** [comment]
Yes, currently you would need to also create an extended driver. Custom SQL functions are also a little "complicated" to integrate into the core's functions builder, as you'd need an extended query class and an extended functions builder, and then you need to integrate it into table and connection classes, so usually you're better of providing/using custom function expression classes directly.

For 4.next, ie 4.3, types will support custom column conversion and SQL generation, you might want to give that a try and provide some feedback if you can.

* https://book.cakephp.org/4.next/en/orm/database-basics.html#connecting-custom-datatypes-to-schema-reflection-and-generation
* https://github.com/cakephp/cakephp/pull/15371

Custom index types aren't supported, maybe you can provide some info on how exactly your indices look like, and what functionality in type classes could possibly help you with integrating them.

**Comment by CauanCabral** [comment]
Thanks @ndm2, `ColumnSchemaAwareInterface` seems a perfect for the custom type support.

The [index types](https://www.postgresql.org/docs/current/textsearch-indexes.html) are the form: 

```sql
--- type GIST
CREATE INDEX idx_custom_name_gist ON my_table USING GIST(column_of_type_tsvector);
--- Type GIN
CREATE INDEX idx_custom_name_gin ON my_table USING GIN(column_of_type_tsvector);
```

Now, I think to override `PostgresSchemaDialect::indexSql()`. The generated sql are in `'CREATE INDEX %s ON %s (%s)'` format. `MysqlSchemaDialect` seems a good start point. But I also need to override in some way the array `Cake\Database\Schema\TableSchema::_validIndexTypes`.

**Comment by CauanCabral** [comment]
I put a mirror of my experiment at  https://github.com/CauanCabral/cakephp-pg-search

Commit messages and readme are in portuguese, but code and tests are in english.

What I needed to extends:

 - `Cake\Database\Driver\Postgres`: to inject custom `TableSchema` and `PostgresSchemaDialect`.
 - `Cake\Database\Schema\TableSchema`: to define new column and indexes types.
 - `Cake\Database\Schema\PostgresSchemaDialect`: to define how the new column and indexes should translate into sql.
 - `Cake\Database\Type\BaseType`: to implement the new abstract type `Tsvector`.

I think the main problems doing that is in `Cake\Database\Schema\PostgresSchemaDialect`, the methods I need override aren't small (`columnSql` and `_convertColumn`) and any bug fix or feature patched on upstream will need to replicate.

Would be amazing If I can extend that two methods without copy-paste.

**Comment by ndm2** [comment]
You don't have to reimplement everything, you can ditch most of the code and only implement what you actually need for your specific type(s), for example:

```php
protected function _convertColumn(string $column): array
{
    preg_match('/([a-z\s]+)(?:\(([0-9,]+)\))?/i', $column, $matches);
    if (empty($matches)) {
        throw new DatabaseException(sprintf('Unable to parse column type from "%s"', $column));
    }

    $col = strtolower($matches[1]);
    
    if (strpos($col, 'tsvector') === false) {
        return parent::_convertColumn($column);
    }
    
    return ['type' => TableSchema::TYPE_TSVECTOR, 'length' => null];
}
```

```php
public function columnSql(TableSchema $schema, string $name): string
{
    /** @var array $data */
    $data = $schema->getColumn($name);
    
    if ($data['type'] !== TableSchema::TYPE_TSVECTOR) {
        return parent::columnSql($schema, $name);
    }

    $out = $this->_driver->quoteIdentifier($name);
    $out .= ' TSVECTOR';

    if (isset($data['null']) && $data['null'] === false) {
        $out .= ' NOT NULL';
    }
    
    return $out;
}
```

I misread your initial post a little bit, thinking you were talking about index functionality in type classes. Thinking about that a bit, type classes aren't really index related, as indexes don't necessarily belong to a specific column type, so a different API for custom indexes would be warranted, though I don't really have an idea right now what it could look like.

**Comment by CauanCabral** [comment]
Thanks again. You are right.

Refactored my code to reimplement only what I need.

I also agree with indexes not having a strict relationship with column type. Besides your `ColumnSchemaAwareInterface`, we need a way to tell `TableSchema` what is a valid indexes (replacing current `_validIndexTypes` static array) and how to write sql for that index type (improving current `indexSql` method).

Maybe a `IndexFactory` the same way we have `TypeFactory`? Or a way to inject a callable on each step (validate type and build sql)?

**Comment by othercorey** [comment]
When do you need to generate these indexes from cake?

**Comment by CauanCabral** [comment]
I don't need, because I can write my migrations with raw SQL.

But if I can write migrations and fixtures with other types of indexes, why I wouldn't write `GIN` or `GIST` the same way?

**Comment by othercorey** [comment]
We are moving away from schema creation in cakephp so I suggest you try to use cakephp/migrations or raw sql instead.

**Comment by CauanCabral** [comment]
Moved and published the Postgres driver supporting `tsvector` column type and `gin`|`gist` indexes type at https://packagist.org/packages/autopage/pg-search

Thanks @ndm2 for all tips and directions.
