### ISSUE TITLE
RFC: use full path by default as reference in .pot files when using I18n extract

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15432]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.5

### What you did

```bash
bin/cake i18n extract (multiple directories)
```

### What happened
When extracting multiple folders like vendor, templates, src, etc, the references are not clear:

```gettext
#: Error/error400.php:39
msgid "The requested address {0} was not found on this server."
msgstr ""

#: Error/ExceptionRenderer.php:340
msgid "An Internal Error Has Occurred."
msgstr ""
```

With the current behavior, the references start with Error/ but one is in `ROOT/template/Error` and the other is inside `ROOT/vendor/.../src/Error`

### What you expected to happen
To show paths from ROOT:

Applying my changes would show them this way:

```gettext
#: templates/Error/error400.php:39
msgid "The requested address {0} was not found on this server."
msgstr ""

#: vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:340
msgid "An Internal Error Has Occurred."
msgstr ""
```

I know changing this would change a LOT of lines _.pot_ and _.po_ files first time the user uses _extract command_ but I think it's way cleaner this way.

## Note:
***I found this while writing this RFC** but I still think there may be something we could do.

The default behaviour of the command is supposed to show full paths instead of relative paths. It is actually showing neither the full nor the relative ones. **So what is the expected behaviour?**

I say this because there's an option called `relative-paths` that can be passed to the to the _extract command_.
The DocBlock says:

```php
    /**
     * Use relative paths in the pot files rather than full path
     *
     * @var bool
     */
    protected $_relativePaths = false;
```

When this option is true, the paths will be like this:

```gettext
#: ./templates/Error/error400.php:39
msgid "The requested address {0} was not found on this server."
msgstr ""

#: ./vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php:340
msgid "An Internal Error Has Occurred."
msgstr ""
```

Which is almost the same result I want to get.

I don't know if I have expressed myself correctly...
**At this point I do not know if the actual behavior is the expected one**.

I'm ready to send a PR which, by default, shows use the "full" paths like in the second example but since it does quite the same as `relative-paths` option does, I don't know if we should just change the description of the command and some DocBlocks to state that the default behavior does not use the full path. **What do you think?**

If we do not make any changes, there will still be, in my opinion, confusion in the routes when no `relative-paths` option is passed

**Comment by ADmad** [comment]
Problem is the check for `no-location` option here:

https://github.com/cakephp/cakephp/blob/dfa79715247b8e904c53d96073fa9bff35a6cd88/src/Command/I18nExtractCommand.php#L554-L567

The path prefix should be stripped when `no-location` is `true` instead they are stripped when it's `false` (the default value).

That said this behaviour has existed since a very long time, so changing it in a bugfix release would be unwise.

**Comment by ADmad** [comment]
Having both `no-location` and `relative-paths` is quite confusing IMO. Perhaps we should just drop the `no-location` option in next minor.

**Comment by garas** [comment]
Since CakePHP 4 split code and template locations, relative paths should be always used, `relative-paths` should be ignored/deprecated in next minor version, removed in next major version.

`no-location` controls whether paths are printed at all. It is sometimes useful to skip printing paths to avoid Git diff noise.

**Comment by ADmad** [comment]
Ah, though the paths currently shown for default options are quite silly. Always using paths relative to the `ROOT` makes a lot more sense.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15437
