### ISSUE TITLE
RFC: Preloading

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#15457]
* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

https://www.php.net/manual/en/opcache.preloading.php

There was an issue (#13950) opened on this a while back and core developers wanted to wait on composer support (composer/composer#7777) which now seems dead. I think this is something CakePHP should be offering its users as other major frameworks have already implemented support.

I haven't done much with preloading, but it seems CakePHP could offer a Command for generating a preload file that might include CakePHP `vendor/cakephp` and some (or all) of userland `src/` and `plugins/`.

**Comment by cnizzardini** [comment]
I might take a stab today at building some alpha code for this, but I likely need some assistance from core devs.

**Comment by markstory** [comment]
I have never worked with preloading either, but I can try to help.

**Comment by cnizzardini** [comment]
If I am understanding what I've read, you only gain preload performance if all of the dependencies of a preloaded file are preloaded as well. It's semi-trivial to grab a list of all `CAKE` and `APP` files. But the moment those files have dependencies on other vendor files you lose the benefit (again if I am understanding correctly). I think tools can be provided to assist users with managing their own `APP` preloads, the framework shouldn't get into that mess. For Cake specifics, not all of these dependencies are well known to me in terms of usage in the various area of Cake core:

```json
        "composer/ca-bundle": "^1.2",
        "laminas/laminas-diactoros": "^2.2.2",
        "laminas/laminas-httphandlerrunner": "^1.1",
        "league/container": "^3.2",
        "psr/http-client": "^1.0",
        "psr/http-server-handler": "^1.0",
        "psr/http-server-middleware": "^1.0",
        "psr/log": "^1.0.0",
        "psr/simple-cache": "^1.0.0"
```

I've also come across some packages which assist in managing building preloads, but I'd imagine if Cake were to leverage a library we'd want to ensure it's from a quality maintainer that won't "disappear". I'm not necessarily recommending that at this time, but it's an option.

For the additional cake core dependencies, it should be possible to grab all the files in their vendor directory. FWIW I do have some rudimentary code that can be run by command or integrated into userland code that I'll try and open a PR with this weekend or shortly after. 

Benchmarks can be tricky, but with what I wrote I am seeing about a 15% "grain of salt" boost on a dockerized application running on my local Ubuntu.

**WITHOUT: opcache.preload:**

```console
> ab -n 10000 -c 10 http://localhost:8080/public/actors.json

Concurrency Level:      10
Time taken for tests:   29.082 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      21700000 bytes
HTML transferred:       20150000 bytes
Requests per second:    343.86 [#/sec] (mean)
Time per request:       29.082 [ms] (mean)
Time per request:       2.908 [ms] (mean, across all concurrent requests)
Transfer rate:          728.68 [Kbytes/sec] received
```

**WITH: opcache.preload:**

```console
> ab -n 10000 -c 10 http://localhost:8080/public/actors.json

Concurrency Level:      10
Time taken for tests:   24.911 seconds
Complete requests:      10000
Failed requests:        0
Non-2xx responses:      10000
Total transferred:      9470000 bytes
HTML transferred:       7650000 bytes
Requests per second:    401.42 [#/sec] (mean)
Time per request:       24.911 [ms] (mean)
Time per request:       2.491 [ms] (mean, across all concurrent requests)
Transfer rate:          371.24 [Kbytes/sec] received
```

**Comment by othercorey** [comment]
Be careful to not load dev dependencies.

If this script just needs to load files -- should we run a vertical slice path through cake that would load most dependencies?

**Comment by cnizzardini** [comment]
I've released this as a plugin. Feedback is welcomed: https://github.com/cnizzardini/cakephp-preloader

**Comment by ADmad** [comment]
Great, we'll see how it's received by the community 🙂.
Closing the issue for now.
