### ISSUE TITLE
Empty strings are not converted to NULL for DATE columns

### ISSUE THREAD

**Issue by ttm-tt** [cakephp/cakephp#15450]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.5
* Platform and Target: Debian 10, Apache 2.x, MariaDB 10.3

### What you did
In a database I have a nullable column of type DATE. When I try to store an empty string I get an SQL error 
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column ...

Valid date strings like '2021-04-12' will work

### What happened
See above

### What you expected to happen
I would expect that an empty string is converted to null, esp. since the View could send me only empty strings at best and not null.

Database/Type/DateTimeType.php, method toDatabase(...) checks if a value is already a string and if so returns it unchanged. In contrast, IntegerType will return null if it is an empty string.

Sorry if this has been asked before, but, to my surprise,  I haven't found a previous issue.

**Comment by ndm2** [comment]
The conversion normally happens at marshalling time in [**`DateTimeType::marshal()`**](https://github.com/cakephp/cakephp/blob/4.2.5/src/Database/Type/DateTimeType.php#L304-L306), ie when you are creating/patching entities.

**Comment by ttm-tt** [comment]
Yes, of course. I thought marshal is the other way round ...
Then I have to investigate further what went wrong.

**Comment by ttm-tt** [comment]
Found it: in that specific case I bypass patchEntity and set the values directly. Didn't thought about that his implies bypassing validation, too.

Out of curiosity, is it intended that DateTime behaves different from numeric types? For both types empty string don't make sense, in contrast to e.g. strings.

**Comment by ndm2** [comment]
IIRC this is for compatibility with MySQL's non-strict mode where empty strings are converted to `0000-00-00 00:00:00`.

**Comment by ttm-tt** [comment]
One could argue likewise for numeric values ...
But thank you that for pointing out that such conversion exists. 
Thank you for commenting, it really helped me understanding some caveats. I'll close the issue then.

**Comment by dereuromark** [comment]
@ttm-tt You can see if https://github.com/dereuromark/cakephp-shim/blob/master/docs/Model/Nullable.md helps you.
It might be able to detect the nullable column and auto marshal the empty string to null for sanity reasons of the DB structure.

**Comment by ttm-tt** [comment]
Thank you, I'll try it.
