### ISSUE TITLE
manyToOne associations with foreignKey alias and className does not get added to table _associations 

### ISSUE THREAD

**Issue by geoidesic** [cakephp/cakephp#15466]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.7.
* Platform and Target: MAMP PRO on Mac OS X (it's just Apache / MySQL and PHP v7.4.2

### What you did
Created two tables: `people` & `enquiries` plus a manyToOne association on `enquiries`.
Here are the migrations:
```
$this->table('enquiries', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('created', 'datetime', [
                'default' => 'CURRENT_TIMESTAMP',
                'limit' => null,
                'null' => true,
            ])
            ->addColumn('id', 'uuid', [
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
            ->addColumn('notary_id', 'uuid', [
                'comment' => 'Notary responsible for taking this enquiry forward (and for billing), not necessarily the same as logged in user',
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
...
 $this->table('people', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'uuid', [
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
``` 
Here is the association on the `EnquiryTable`:
```
        $this->belongsTo('Notaries', ['className' => 'People', 'foreignKey' => 'notary_id']);

```

### What happened
Given the `PeopleTable` instance, I would expect that the association is listed in $PeopleTable->_associations` property (which can be accessed via $PeopleTable->associations()` but it is not.

If I alter the migrations so as to add `person_id` to the `enquiries` table, then the above association does work (i.e. is listed via $PeopleTable->associations()`. This is weird... I'm not referencing `person_id` in the association, so adding it to the migration should not have an impact on the association.

### What you expected to happen
It should not require the default foreignKey column to be present in order to recognise the association. It should use the alias, not the default foreignKey naming convention for registering the association.

**Comment by markstory** [comment]
> Given the PeopleTable instance, I would expect that the association is listed in $PeopleTable->_associations property (which can be accessed via $PeopleTable->associations() but it is not.

You've created an association from Enquiries to People. Reverse associations are not automatically created. You'd need to define the reverse association on the `PeoplesTable` as well.

When using `person_id` you are likely getting convention based associations generated by `bake`. Bake is not able to generate associations when fields don't follow the naming conventions strictly.

**Comment by geoidesic** [comment]
As @markstory mentions – the reverse association on `PeopleTable` was missing:
```
        $this->hasMany('NotaryEnquiries', ['className' => 'Enquiries', 'foreignKey' => 'notary_id']);
```
