### ISSUE TITLE
Deprecated Plugin::routes somehow required for DebugKit to work in 3.9

### ISSUE THREAD

**Issue by ProFire** [cakephp/cakephp#15465]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.8
* Platform and Target: PHP 7.4

### What you did
I recently inherited a project running CakePHP 3.5.6 and I was tasked to update it to 4.x version. I decided that I should not do a direct upgrade to 4.x but to go to 3.9 first before going to 4.x. Once I updated to 3.9.8, I started the process of updating the deprecated codes to use the newer ones. 

### What happened
I have stumbled when I'm trying to remove Plugin::routes(). Despite my best google-fu, I could not remove it without affected DebugKit.

I have added the debug plugin in src\Application.php:
```
    public function bootstrap()
    {
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            $this->bootstrapCli();
        }

        if (Configure::read('debug')) {
            $this->addPlugin(DebugKitPlugin::class);
        }
    }
```

I'm getting Cake\Routing\Exception\MissingControllerException: DebugKitController could not be found. 

I've tried clearing cache manually and through CLI, but it still shows up the same error. Only when I put back Plugin::routes() in config\routes.php that DebugKit works are intended.

### What you expected to happen
Removing Plugin::routes() and adding $this->addPlugin(DebugKitPlugin::class) in src\Application.php should have a working debugkit.

**Comment by ProFire** [comment]
Sorry, I realised this is probably my oversight. I totally missed out on https://book.cakephp.org/3/en/development/application.html#adding-the-new-http-stack-to-an-existing-application
I was clearing other deprecation when I stumble on this documentation. Maybe a suggestion but perhaps this piece of documentation should be the first thing to do before any other upgrading task? I didn't realise this should be the first thing to do. It was only after I did this that debugkit worked without Plugin::routes()

**Comment by markstory** [comment]
>  Maybe a suggestion but perhaps this piece of documentation should be the first thing to do before any other upgrading task? 

That sounds like a good idea. What were you using as a guide to do your upgrade?

**Comment by ProFire** [comment]
I tried to look at https://book.cakephp.org/3/en/appendices/3-9-migration-guide.html and https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html initially. Obviously not all the content is applicable. I picked and choose the content that is relevant to apply to my 3.9.x app. 

As I was applying the deprecation update, I followed some of the instructions from the deprecation warning message from the app and from DebugKit toolbar.

That's when one of the deprecation fix caused the DebugKit toolbar to be messed up. If only I knew https://book.cakephp.org/3/en/development/application.html#adding-the-new-http-stack-to-an-existing-application was the first thing I should have applied.

**Comment by othercorey** [comment]
The part you're doing is from the 3.3 migration guide:

https://book.cakephp.org/3/en/appendices/3-3-migration-guide.html#psr-7-middleware-support-added

**Comment by ProFire** [comment]
I get what you mean. It appears the previous developer didn't apply this migration, so I missed it out. The documentation works, that's for sure. I wished it was a little easier to migrate if there is a 1 stop guide on all the essential stuff if I'm upgrading from any 3.x version to 3.9.x.

**Comment by othercorey** [comment]
Well, we don't know what applies if you start at a random version otherwise we'd have to tell people to change everything with every version.

However, for your specific issue, what changed in 3.9 where you couldn't use the deprecated code?

**Comment by ProFire** [comment]
It was Plugin::routes() that was deprecated. I only found out that I needed to apply the new http stack when I paid attention to DebugKit's deprecation report. 

It was likely an oversight by me. I was thrown several messages like "_Use Application::addPlugin() instead_." and "_Plugin::bootstrap() is deprecated_." that I decided to just remove all the plugin functions that is deprecated. I totally missed out that 1 specific message that says "**See https://book.cakephp.org/3/en/development/application.html#adding-the-new-http-stack-to-an-existing-application for upgrade information**." It was nested in a sea of other deprecated messages.

That's my mistake. I hope it's not too much to ask that maybe we could it a bit more obvious that we must use the new http stack. Maybe in the debugkit documentation, a note would be nice before running the command: `bin/cake plugin load DebugKit`

**Comment by othercorey** [comment]
I'm not sure what you want. If the user doesn't read the deprecation message, I'm not sure they'll see a note in a later migration guide about a previous migration guide.

**Comment by ProFire** [comment]
True that.

Perhaps something that would be beneficial is the documentation on https://book.cakephp.org/debugkit/3/en/index.html for 2 reasons:

1. I did try to look into debugkit documentation and followed the instructions but it didn't mention anything about the new http stack
2. Versions prior to 3.3 isn't using the new http stack. Developer should know the different set up process before and after 3.3.
