### ISSUE TITLE
[Cake 2] Error Handler does not supress warnings with @ in PHP 8.0

### ISSUE THREAD

**Issue by Rakasch** [cakephp/cakephp#15460]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.24
* Platform and Target: Apache with PHP 8.0

### What you did
call @ldap_bind with wrong credentials and @ to suppress warnings.

### What happened
Warning was echoed. 
<b>Warning</b> (2)</a>: ldap_bind(): Unable to bind to server: Invalid credentials [<b>APP/Lib/ldap.php</b>, line <b>67</b>]

### What you expected to happen
Warnings should be supressed when using @. 

### Suspected cause
Prior to PHP 8.0.0, the value of the severity passed to the custom error handler was always 0 if the diagnostic was suppressed. This is no longer the case as of PHP 8.0.0.
as stated here: https://www.php.net/manual/en/language.operators.errorcontrol.php

Cake's error handler does not take this change into account.
lib/Cake/Error/ErrorHandler.php
![image](https://user-images.githubusercontent.com/8471027/115223714-67516880-a10c-11eb-82d4-fc4d82483d49.png)

Should be changed to
```
if (!(error_reporting() & $err_no)) {
    return false;
}
```

**Comment by ADmad** [comment]
2.x has reached EOL and won't be getting anymore updates for PHP 8 compatibility or otherwise.
