### ISSUE TITLE
I18n uses different locale depending where Cache::setConfig is executed. Is this an expected behavior?

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#15473]
Hello, I asked this in #15463 because I do not know if this is an expected behavior and I think it may be, someway, related but a member ask me to open an issue for this.

I've found that if I edit `config/bootstrap.php` and write this line:

```php
Cache::setConfig(Configure::consume('Cache'));
```

before than this one:

```php
ini_set('intl.default_locale', Configure::read('App.defaultLocale'));
```

I18n does use the system language instead of the one configured in `Configure::read('App.defaultLocale')`.

If after doing that, I use `I18n::setLocale(Configure::read('App.defaultLocale'))` it works as expected: it loads the correct .po file

So the question is:
### Is this an expected behavior?

----
**Some background**:
I was doing this so I can use `__('bar foo')` inside `/config` files. Later I found that it's not good idea since **the user's language** can not be set before reading those config files in `bootstrap.php`

----

# Debugging

```php
// AppController.php::beforeRender
debug(I18n::getDefaultLocale()); // Line 134
debug(I18n::getLocale()); // Line 135
```

## Changing the order in bootstrap

`I18n::getDefaultLocale()` returns `es_ES`
Results in Spanish texts showing regarless `I18n::getLocale()` returning `en_US`:

![image](https://user-images.githubusercontent.com/10481749/116467898-2114ab80-a868-11eb-8827-1071aafc0c6a.png)

## Using the default order in bootstrap

`I18n::getDefaultLocale()` returns `en_US`
Results in English texts showing as expected because `I18n::getLocale()` is returning `en_US`:

![image](https://user-images.githubusercontent.com/10481749/116468347-a730f200-a868-11eb-9751-d4840b161362.png)

**Comment by markstory** [comment]
Where were your message translations being done in relation to these two lines? I don't think `Cache::setConfig()` creates translated messages, but if one was created it would result in the default locale being set before intl is configured and the fallback locale is `en_US`.

**Comment by hacheraw** [comment]
> Where were your message translations being done in relation to these two lines? I don't think `Cache::setConfig()` creates translated messages, but if one was created it would result in the default locale being set before intl is configured and the fallback locale is `en_US`.

I think you found the key.
This happens when I translate a text between Cache and `intl.default_locale` **but it does not fallback to en_US** but to system's one.
I say it's the system's one because my computer is spanish and my Server english and the results match with system's locale.

I've done all the "testing" inside `bootstrap.php` to be sure.

**Scenario**:
- Default System locale: **es_ES**
- App.defaultLocale in config/app.php: **en_GB**

**Default order: expected result**
```php
// config/bootstrap.php

Configure::load('app', 'default', false);
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'es_ES'
...
// debug(__('Today')); // Fatal Error: can't do this before _cake_core_ exists
...
ini_set('intl.default_locale', Configure::read('App.defaultLocale'));
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'en_GB'
...
Cache::setConfig(Configure::consume('Cache'));
...
debug(__('Today')); // outputs: 'Today'
```

**Different order: it translates all strings to Spanish even when the defaultLocale is en_GB**. It uses system's language.
```php
// config/bootstrap.php

Configure::load('app', 'default', false);
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'es_ES'
...
Cache::setConfig(Configure::consume('Cache'));
...
debug(__('Today')); // outputs: 'Hoy' (spanish)
...
ini_set('intl.default_locale', Configure::read('App.defaultLocale'));
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'en_GB'
...
debug(__('Today')); // outputs: 'Hoy' (spanish)
```

**Different order without translating between Cache and intl.default_locale: expected result**
```php
// config/bootstrap.php

Configure::load('app', 'default', false);
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'es_ES'
...
Cache::setConfig(Configure::consume('Cache'));
...
// NO __('') IN BETWEEN
...
ini_set('intl.default_locale', Configure::read('App.defaultLocale'));
...
debug(I18n::getDefaultLocale()); // outputs: 'es_ES'
debug(I18n::getLocale()); // outputs: 'en_GB'
...
debug(__('Today')); // outputs: 'Today'
```

**Comment by markstory** [comment]
> This happens when I translate a text between Cache and intl.default_locale.

Don't do that :smile:

**Comment by ADmad** [comment]
Properly setting your default locale **before** translating any message is kinda the obvious thing to do. Closing as there's nothing to be fixed here.
