### ISSUE TITLE
CSRF token error despite matching Request Header sent

### ISSUE THREAD

**Issue by eBug** [cakephp/cakephp#15475]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.3
* Platform and Target: Debian 10, Apache 2.4.38, MariaDB 10.3.27

### What you did
I'm trying to learn how ajax works within cakephp, my first attempt here. I added this script to an add form:
 
```
//templates/Documents/add.php
[...]
<?= $this->Form->button(__('Submit'), ['id' => 'cakebtn']) ?>
[...]
<script>
    $(function(){
        $('#cakebtn').click(function(){
            $.ajax({                                                           
                method: "POST",                                                
                url: "<?= $this->Url->build(['controller' => 'Formats', 'action' => 'receive'])?>",
                data: {id: 3},                                                             
                headers: { 'X-CSRF-Token': $('[name="_csrfToken"]').val()}
            })
        });
    })
</script>
```
From Firefox inspector I can see the form includes a

`<input type="hidden" name="_csrfToken" autocomplete="off" value="nMYK3MzCabZJfjfEHCzxoMwl59LpnrOUqM57/RdMJOAROBhfI9EuMmppq8srtpKCTTS3/RyuPTK8klmbENpHczThImcz9n/trhbU6976i6TLrEOZcy1B2CINIW0WsktWDlHOqRLUprssBoHPec8IAw==">`

### What happened
When clicking Submit button, I get a
`404: CSRF token from either the request body or request headers did not match or is missing.`
from
`Cake\Http\Middleware\CsrfProtectionMiddleware->_validateToken CORE/src/Http/Middleware/CsrfProtectionMiddleware.php:165`

The Request Header matches the _csrfToken input value:
`X-CSRF-Token: nMYK3MzCabZJfjfEHCzxoMwl59LpnrOUqM57/RdMJOAROBhfI9EuMmppq8srtpKCTTS3/RyuPTK8klmbENpHczThImcz9n/trhbU6976i6TLrEOZcy1B2CINIW0WsktWDlHOqRLUprssBoHPec8IAw==
`
But there's also a cookie with a different value:
`csrfToken=IFRTR9wYLsV9nxWjL9qOTWIzMzk3ZDgwY2I4ZGRhZTgzNTkyNWNlZGQ4ZWI5YjQ5YTI2MmVhNTE%3D; `
 
### What you expected to happen
Middleware shouldn't block my request
Aren't the cookie and the header supposed to have the same value? What value is the request header checked against? input tag or cookie?

**Comment by markstory** [comment]
The cookie and the input value are different on purpose. The input value changes on every request to prevent BREACH vulnerabilities to applications behind SSL connections. Do your form submissions without AJAX succeed?

**Comment by eBug** [comment]
Without AJAX the form works perfectly.

**Comment by markstory** [comment]
So if the form submissions work, then you should look at the network tab to see what is different between the basic form submission and your ajax submission.

**Comment by eBug** [comment]
After logging out/login in, it all seems to work fine now. I didn't change anything to the existing code though.
I'm not sure what mecanism was involved, all pretty misterious.
