### ISSUE TITLE
Can't save boolean values to the cache engine (Redis).

### ISSUE THREAD

**Issue by genellern** [cakephp/cakephp#15489]
This is a (multiple allowed):

* [x] bug
* [x] enhancement

* CakePHP Version: 3.9.8
* Platform and Target: Docker with PHP-7.4-fpm, and Redis from phpdocker.io

### What you did
Tried to save true or false boolean values using `Cache::remember()`
```
    $active = Cache::remember($cacheIdentifier, function () use ($checkEntity) {
        return ($checkEntity->status == 'active');
    });
```

### What happened
Didn't save to the cache engine.

### What you expected to happen
It would save to the cache engine. Instead I had to trick it to compare strings.
```
    $cachedActive = Cache::remember($cacheIdentifier, function () use ($checkEntity) {
        return ($checkEntity->status == 'active') ? 'true': 'false';
    });
    $active = ($cachedActive === 'true');
```

**Comment by genellern** [comment]
I'm thinking instead of returning `false` the default return value when a key is not found should be `null`.

**Comment by markstory** [comment]
> I'm thinking instead of returning false the default return value when a key is not found should be null.

Changing the default value would break existing applications. This behavior has already been corrected in 4.x

**Comment by genellern** [comment]
Would it be a good idea to set that in the config like `Cache.defaultReturn` to `false`|`null` or something?

**Comment by markstory** [comment]
That could be possible. Are you thinking it would be used as way to make upgrading simpler? It isn't a configuration value I would want to have in 4.x as it isn't necessary there.

**Comment by othercorey** [comment]
This seems like something worth adding to the 3.x docs then.

**Comment by othercorey** [comment]
Looking at it further, I don't think it really works even in 4.x. `remember()` returns bool values for error/success which conflicts the bool value being cached.

**Comment by ADmad** [comment]
> remember() returns bool values for error/success which conflicts the bool value being cached.

No, in case of cache hit it returns the value read from the cache engine and in case of cache miss is returns the value returned by the callable. The docblock needs to be fixed.

Closing as this issue doesn't exist in 4.x as cache engine's return `null` on failure instead of `false`. It's too late to add a config like `Cache.defaultReturn` as proposed for 3.x. Users should just avoid trying to cache boolean values.
