### ISSUE TITLE
Query encoding switch is missing in the http Client

### ISSUE THREAD

**Issue by RobRikken** [cakephp/cakephp#15497]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP version 4.1
* Platform and Target: Windows, request to Odata API

### What you did
Did a request with the http Client of CakePHP to a Odata API server.

### What happened
The request produced an error from the API, because the API doesn't support a + in the query part of the url.

### What you expected to happen
That the CakePHP http Client encoded the space character into %20 so the request succeeds.

### Notes
The http_build_query() function that is used has a option to change the encoding to a %20 instead of a + while encoding, but this is not an option in the CakePHP http client.

The php function:
```
* @param int $encoding_type By default, PHP_QUERY_RFC1738.
 *  <p>If enc_type is PHP_QUERY_RFC1738, then encoding is performed per » RFC 1738 and the application/x-www-form-urlencoded media type,
 *  which implies that spaces are encoded as plus (+) signs.
 *  <p>If enc_type is PHP_QUERY_RFC3986, then encoding is performed according to » RFC 3986, and spaces will be percent encoded (%20).
 * @return string a URL-encoded string.
 */
#[Pure]
function http_build_query ($data, string $numeric_prefix = "", string $arg_separator = "&", int $encoding_type = PHP_QUERY_RFC1738){}
```

CakePHP not using the encoding option:
```
public function buildUrl(string $url, $query = [], array $options = []): string
    {
        if (empty($options) && empty($query)) {
            return $url;
        }
        if ($query) {
            $q = strpos($url, '?') === false ? '?' : '&';
            $url .= $q;
            $url .= is_string($query) ? $query : http_build_query($query);
        }
```

**Comment by ADmad** [comment]
Fixed in  #15498
