### ISSUE TITLE
TypeError on bad URLs

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#15494]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest master

### What you did

Upgrade cake3 app to cake4
Apparently, with some old URLs still "crawled", internal server errors can happen
```php
$path = parse_url($url, PHP_URL_PATH); // Can be false in bad URL case
$parts = array_map('rawurldecode', explode('/', $path));
```

### What happened
URL `/posts/index/adbirawwy/page:6/sort:type/` triggers
```
[TypeError] explode() expects parameter 2 to be string, bool given in /var/www/site/vendor/cakephp/cakephp/src/Routing/Asset.php on line 217
Stack Trace:
- /var/www/site/vendor/cakephp/cakephp/src/Routing/Asset.php:217
- /var/www/site/vendor/cakephp/cakephp/src/Routing/Asset.php:196
- /var/www/site/vendor/cakephp/cakephp/src/View/Helper/UrlHelper.php:181
- /var/www/site/vendor/cakephp/cakephp/src/View/Helper/HtmlHelper.php:180
```

### What you expected to happen
No error just display the same URL again or maybe we throw an error that goes into 404 instead?

**Comment by markstory** [comment]
Do you know what input URL caused the URL generation failure? We could try to guard against that and return '' as the generated URL.

**Comment by dereuromark** [comment]
See above "URL /posts/index/adbirawwy/page:6/sort:type/ triggers"
