### ISSUE TITLE
PluginLoadCommand cannot find boostrap()-method when not following the CakePHP code style convention

### ISSUE THREAD

**Issue by fabsn182** [cakephp/cakephp#15503]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.5
* Platform and Target: 

### What you did
* Reformatted the method `bootstrap` in `src/Application.php` from
`public function bootstrap(): void` to
`public function bootstrap (): void`
* Called `bin/cake plugin load <pluginname>`

### What happened
Received the message `Your Application class does not have a bootstrap() method. Please add one.` instead of the addPlugin code being added

### What you expected to happen
The addPlugin code being added to the existing `bootstrap()`-method

### Solution
Add a non-capturing group checking for whitespaces `(?:\s*)` after `bootstrap` in both regular expressions (line 107 and 112)
of `src/Command/PluginLoadCommand.php`

Line [107:](https://github.com/cakephp/cakephp/blob/master/src/Command/PluginLoadCommand.php#L107)
`if (!preg_match('/function bootstrap(?:\s*)\(\)(?:\s*)\:(?:\s*)void/m', $contents)) {`
See https://regex101.com/r/rpaw9U/1

Line [112](https://github.com/cakephp/cakephp/blob/master/src/Command/PluginLoadCommand.php#L112):
`'/(function bootstrap(?:\s*)\(\)(?:\s*)\:(?:\s*)void(?:\s+)\{)/m',`
See https://regex101.com/r/htQexE/1

**Comment by markstory** [comment]
Seems like you know the changes that need to be made, any chance you'd be willing to send a pull request?

**Comment by fabsn182** [comment]
I never did that and I don't want to make a mistake but I guess there's always a first time. I'll have a look tomorrow and try to figure it out.

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15505
