### ISSUE TITLE
Number helper does not initialize NumberFormatter on PHP 8.0 correctly

### ISSUE THREAD

**Issue by cschomburg** [cakephp/cakephp#15501]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.5
* Platform and Target: PHP 8.0.5

### What you did

While upgrading our application to PHP 8.0, we noticed a strange bug when interacting with `NumberFormatter` through `Cake\I18n\Number` that did not happen in PHP 7.4:

```php
<?php

require './vendor/autoload.php';

use Cake\I18n\Number;
var_dump(Number::parseFloat('invalid'));
var_dump(Number::precision(123.45, 2));
```

### What happened

On PHP 8.0 above code fails with message: `PHP Fatal error:  Uncaught Exception: Failed to clone NumberFormatter object in /www-root/vendor/cakephp/cakephp/src/I18n/Number.php:413`

### What you expected to happen

On PHP 7.4 this works without throwing an exception.

There seems to be either a bug or behavior change in PHP 8 which occurs when cloning a NumberFormatter that is in an error-state. See vanilla example here: https://3v4l.org/CLcph

**Comment by markstory** [comment]
Interesting, I wonder if we're not hitting this line in CI as we are running tests in PHP 8.

**Comment by ADmad** [comment]
https://bugs.php.net/bug.php?id=81019
