### ISSUE TITLE
Extend primitives support in action arguments

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15514]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6
* Platform and Target: nginx, php7.4

Per this code in ControllerFactory https://github.com/cakephp/cakephp/blob/master/src/Controller/ControllerFactory.php#L122

Would it be possible to extend this support for primitives at least for integers? It's usually main navigational param when accessing objects (usually it's database id which is of `int` type)

Currently the only way to support this in implementation is to override the `controllerFactory` protected field within `Application` to subclass of current ControllerFactory and handle the primitives in `invoke`

Previously working was solution I presented in initial report of  #15023 (specifically overriding the `AppController::invokeAction` implementation), which is not with changes introduced in cakephp 4.2.x

**Comment by markstory** [comment]
> Would it be possible to extend this support for primitives at least for integers? It's usually main navigational param when accessing objects (usually it's database id which is of int type)

Possible but we need to solve how invalid data should be handled. If we add `int` we should also add `float`, and `bool` too.

**Comment by smarek** [comment]
@markstory is there anything i can help with ? 
Also please, could the final solution be something, that is easily extendable? I've seen the [DI container](https://book.cakephp.org/4/en/development/dependency-injection.html) work-in-progress, and even tho that could be confusing, i had initially tried to override the primitives support through providing primitives Service, and putting the logic of parsing/casting/matching action arguments in overridable component, would be really appreciated. Thank you

**Comment by markstory** [comment]
> is there anything i can help with ?

If you have time you could extend the string support to also work with int/float/bool. We can start by raising an exception on data that can't be cast to the right type, and go from there.

The DI container is the plan for making action parameters extensible. Primitives need to be an exception though as the DI container uses type hints to resolve parameters and primitives can't be typehint resolved.

**Comment by smarek** [comment]
I'll provide PR with that and tests, not a problem. I'd like to also include setter/getter for `controllerFactory` within `BaseApplication` and externalizing component that handles the casting arguments, so it's extendable. Sounds good to you?

**Comment by markstory** [comment]
>  I'd like to also include setter/getter for controllerFactory within BaseApplication and externalizing component that handles the casting arguments, so it's extendable.

How would a a setter/getter for controllerFactory be used? The application object and just mutate the controllerFactory as required, and there isn't generally anything controlling the application.

I also don't understand why you would need to swap out how scalar values are resolved. What use cases do you have in mind for that?

**Comment by smarek** [comment]
@markstory to explain

1) setter/getter would be imho better than this snippet, i had to implement, to support `int` typed action/function arguments.
Currently the factory is automatically created in protected field by current `BaseApplication::handle` implementation, instead of having transparent getter/setter methods, that could be overriden

```php
// src/Application.php

    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        // where TypedControllerFactory is copy of Cake\Controller\ControllerFactory with int support added in "invoke" function
        $this->controllerFactory = new TypedControllerFactory($this->getContainer());
        return parent::handle($request);
    }
```

2) In my opinion there is strong probability that framework handling eg. **casting float-like data** would result in different value than the user/developer expects, hence I'd like to optionally give the developer control about how the data is casted (eg. checking the character-set, stripping/substringing before casting or modifying when the argument data is unfit for the action type), instead of naively assuming that the framework can handle all the cases itself and in best possible way.

To elaborate further, my understanding of this whole typed arguments support, is to de-duplicate the argument-content checking/casting code from actions/controllers to single component. And if that is the case, developer should have more control even over the primitive arguments, and not be forced to create DI service/resolver and use custom-types for data, that could be valid primitives if the input is modified how the developer pleases

**Comment by markstory** [comment]
> Currently the factory is automatically created in protected field by current BaseApplication::handle implementation, instead of having transparent getter/setter methods, that could be overriden

I agree that snippet isn't ideal. Is there a reason you don't use the constructor parameter to pass in your ContorllerFactory? Having the existing constructor parameter, makes me leery of having more ways to change the factory. However, we add another hook method on the Application that returns the constructor property. An application override implementation could be:

```php
// in user land code
public function controllerFactory()
{
    return new TypedControllerFactory($this->getContainer());
}
```

> In my opinion there is strong probability that framework handling eg. casting float-like data would result in different value than the user/developer expects, hence I'd like to optionally give the developer control about how the data is casted (eg. checking the character-set, stripping/substringing before casting or modifying when the argument data is unfit for the action type), instead of naively assuming that the framework can handle all the cases itself and in best possible way.

Couldn't these special use cases be captured as a container service that can read from the request and cast it as required?

I don't like the idea of having different applications manipulate PHP primitive values and their string equivalents. Having these basic types varying from one application to the next, or having it be altered by plugins feels like too much potential surprise.
