### ISSUE TITLE
belongsToMany _joinTable in another database

### ISSUE THREAD

**Issue by yosus** [cakephp/cakephp#15515]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.*
* Platform and Target: Ubuntu 20, MySql

### What you did
I am trying to do 'belongsToMany' to another database, but encountered error in my project. So, following the CMS tutorial, I tested it with 2 database (where 'tags' is in another database) as below :
![cake cms](https://user-images.githubusercontent.com/5551430/118363815-bc2bb600-b5c8-11eb-9d11-1e60f9c82e22.png)

**Model/Table/ArticlesTable.php**
```
// Model/Table/ArticlesTable.php
$this->belongsToMany('Tags', [
	'through' => 'ArticlesTags',
	'joinTable' => 'articles_tags',
]);

```

**Model/Table/TagsTable.php**
```
// Model/Table/TagsTable.php
// To link this table to cake_cms2 database
public static function defaultConnectionName(): string
{
	return 'article';
}


public function initialize(array $config): void
{
	parent::initialize($config);

	$this->setTable('tags');
	$this->setDisplayField('title');
	$this->setPrimaryKey('id');

	$this->addBehavior('Timestamp');

	$this->belongsToMany('Articles', [
		'through' => 'ArticlesTags',
		'joinTable' => 'articles_tags',
	]);


}

```

**Model/Table/ArticlesTagsTable.php**
```
// Model/Table/ArticlesTagsTable.php
$this->belongsTo('Articles', [
	'foreignKey' => 'article_id',
	'joinType' => 'INNER',
]);
$this->belongsTo('Tags', [
	'foreignKey' => 'tag_id',
	'joinType' => 'INNER',
]);
```

### What happened
It was looking into the wrong database, '_cake_cms2_' instead of '_cake_cms_'.
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cake_cms2.articles_tags' doesn't exist`
![cake cms 2](https://user-images.githubusercontent.com/5551430/118363890-feed8e00-b5c8-11eb-8ed9-bcf0057011f5.png)

### What you expected to happen
It should follow database connection in '_ArticlesTagsTable.php_', which will then look into the correct database ('_cake_cms_' database).

**Comment by ndm2** [comment]
This isn't really a bug, but just how retrieving `belongsToMany` associations works, the target table and the the join table are being read in one and the same separate query, so they must be both in the same database, as connections will only apply to queries, not to joins.

In case your DBMS supports cross schema communication, and your default connection has the required permissions etc to access `cake_cms2`, then one workaround can be to include the database name in the table name, ie in `TagsTable` set the name like `$this->setTable('cake_cms2.tags')`, then you'll get a query like:

```sql
FROM tags
INNER JOIN cake_cms2.articles_tags
```

**Comment by othercorey** [comment]
Maybe we can document how, if possible, a separate connection can be used with BelongsToMany.

**Comment by yosus** [comment]
I tried setting TagsTable.php to use default connection, and  ` $this->setTable('cake_cms2.tags');` 

**Model/Table/TagsTable.php**
```
public function initialize(array $config): void
{
	parent::initialize($config);

	$this->setTable('cake_cms2.tags');
	$this->setDisplayField('title');
	$this->setPrimaryKey('id');

	$this->addBehavior('Timestamp');

	$this->belongsToMany('Articles', [
		'through' => 'ArticlesTags',
		'joinTable' => 'articles_tags',
	]);


}
```


**connection in app_local.php**
```
'default' => [
	'host' => 'localhost',
	'username' => '**',
	'password' => '**',
	'database' => 'cake_cms',
	'url' => env('DATABASE_URL', null),
],

```


Now, when I access /tags/index, it is trying to search in `cake_cms `instead of `cake_cms2`

`
Debug: connection=default duration=0 rows=0 SHOW FULL COLUMNS FROM 'tags'
`

![cake cms 3](https://user-images.githubusercontent.com/5551430/118425452-d1edc800-b6fb-11eb-912a-4cdf7751c564.png)

**Comment by ndm2** [comment]
Ah, I forgot about the schema queries, for them you still need to keep the separate connection for the tags table, as operations like the one here for reflecting the schema will run queries via the table's connection, ignoring the possible database name set in the table name.

Sorry for the confusion, you'd then actually have to set the custom table name for `ArticlesTagsTable` instead, ie `cake_cms.articles_tags`. The query for the tags will run on the separate connection, and the join should then refer to the other schema, like:

```php
FROM tags
INNER JOIN cake_cms.articles_tags
```

**Comment by yosus** [comment]
Thanks. That did the trick.

to recap, 

1. Model/Table needs to explicitly mention ` $this->setTable('cake_cms.articles_tags');`
2. database connection needs to have proper access to both schemas
