### ISSUE TITLE
RFC: Ordering union types

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15528]
I thought I'd make an RFC issue to track this idea for moving to php 8 union types.

If we decide to convert most types to union types in cakephp 5, one of the solutions is copy the types from the existing docblocks. There are limitations to this approach since php does not support typed arrays - only the `array` type.

Union types in cakephp should follow a specific pattern to make it easier to read and update the type. It makes sense that we will copy from docblock types since we know they are correct.

I'm suggesting the following format:

```
{classes\interfaces, unsorted}|\Closure|\Traversable|\ArrayAccess|callable|resource|object|iterable|array|string|float|int|bool|true|false|null|void
```

An example would be:

`\Cake\I18n\FrozenDate|\DateTime|\Callable|string[]|string|null|false`

**Comment by markstory** [comment]
I'm good with choosing an order if we can enforce it and autocorrect with linters. Without that it adds toil to review and maintenance.

**Comment by dereuromark** [comment]
The order looks good to me, expect for the null/false part at the end, null should always be last IMO, as it already is for docblock types (true|false|null):

    ...|float|false|null

**Comment by othercorey** [comment]
Yea, it would only make sense with a sniff. However, if we feel that is burdensome, we could enable it to fix the docblocks once.

`false|null` is ok with me if that's desired (it's probably very rare). I was trying to find php manual examples of multiple scalar return types to see if there is any conflicting ordering.
