### ISSUE TITLE
bin/cake plugin load inserts code before parent::bootstrap()

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15521]
The regex inserts the load plugin code at the very first line of the function which is likely not next to the other plugin loading code. 

This often puts the load plugin code before the `parent::bootstrap()` line which just looks very out of place.

If users have to go in and re-write the generated code, I'm not sure it's helping much. Because many plugins copy our suggestion of using this command to load a plugin, I would prefer it be a little cleaner.

**Comment by LordSimal** [comment]
Looking at the current Application.php wouldn't it be best if the new `$this->addPlugin('MyPlugin');` is being added bellow the `// Load more plugins here` aka at the bottom of the `bootstrap()` function?

**Comment by othercorey** [comment]
That's where we want to add them, but we can't guarantee that comment will exist.

**Comment by LordSimal** [comment]
Sure, but we can guarantee the end of the  `bootstrap()` functions `}`
Maybe we can find a regex or step through each line and insert it there

**Comment by dereuromark** [comment]
You can use tokenizing (see IdeHelper) or AST (like rector) to make it more sophisticated, but might be overkill.

**Comment by LordSimal** [comment]
Well if regex is not suitable for this problem and Tokenizing/AST is too much of a hassle what would be the "in between" solution? 😄

**Comment by ndm2** [comment]
There's already an indirect dependency for [**`nikic/php-parser`**](https://github.com/nikic/PHP-Parser), it's pretty easy to modify code with it, but unfortunately the printer seems to easily loose track of formatting, specifically of newlines. However it can still be used to quickly find the line/position of the method's closing parentheses, so appending data should be relatively easy and realiable using standard string modifications.

Here's a somewhat janky quick and dirty example in case anyone's interested:

```php
$lines = file($app);

$parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
try {
    $ast = $parser->parse(implode('', $lines));
} catch (\Error $error) {
    // parse error
}

$visitor = new FirstFindingVisitor(function (Node $node) {
    if (
        $node instanceof ClassMethod &&
        $node->name->toString() === 'bootstrap'
    ) {
        return true;
    }

    return false;
});

$traverser = new NodeTraverser();
$traverser->addVisitor($visitor);
$traverser->traverse($ast);

$methodNode = $visitor->getFoundNode();
if ($methodNode === null) {
    // method not found error
}

$closingLine = $lines[$methodNode->getEndLine() - 1];
if (!preg_match('/^(.*?)\}[^\r\n]*(.+)$/s', $closingLine, $matches)) {
    // line format not matching error
}
$offset = mb_strlen($matches[1]);
$eol = $matches[2];

$replacement = sprintf(
    '%s    $this->addPlugin(\'%s\');%s%s',
    str_repeat(' ', $offset),
    $plugin,
    $eol,
    $closingLine
);
$lines[$methodNode->getEndLine() - 1] = $replacement;

$modifiedCode = implode('', $lines);
```

**Comment by othercorey** [comment]
There was concern about adding a direct dependency (and therefore version constraint) on php-parser. It would be nice if we had dev-only dependencies where that could make sense.

php-parser is *almost* ubiquitous, but with new php releases and features, you don't know what version users need to support.

**Comment by ndm2** [comment]
So what you're saying is, you'd prefer an even jankier vanilla PHP solution that can explode when a mosquito farts in the distance... a tempting challenge 🙃

**Comment by othercorey** [comment]
My first thought was we don't need a load plugin command. But, it seems to be how we document it everywhere.

**Comment by ndm2** [comment]
Yeah, dropping this after all those years will probably cause quite some complaints.

**Comment by dereuromark** [comment]
Current way might not be perfect, but I don't see the need to directly change anything here.
If there is a quick and easy way, sure. Otherwise I would just keep it as is, and moving the code around is still easier than having to come up with the line on your own. So for now it seems to already do a good job as is.

**Comment by ndm2** [comment]
Depends on how you define "_quick and easy_" I guess. Certainly there would be no way around parsing the code if we wanted to append the calls, so some amount of "overhead" would be inevitable.

```php
$code = file_get_contents($app);
$tokens = token_get_all($code);

$position = 0;
foreach ($tokens as $index => $token) {
    if (!is_array($token)) {
        $tokens[$index] = [$token, $token, null];
    }
    $tokens[$index][3] = $position;
    $position += mb_strlen($tokens[$index][1]);
}

$count = count($tokens);
$index = 0;
$next = function ($search = null) use (&$tokens, $count, &$index) {
    if ($search === null) {
        return $tokens[$index ++];
    }

    while ($index < $count) {
        if ($tokens[$index][0] === $search) {
            return $tokens[$index ++];
        }
        $index ++;
    }

    return null;
};

if (
    !$next(T_CLASS) ||
    strtolower($next(T_STRING)[1]) !== 'application'
) {
    // class not found error
}

$closingBracePosition = null;
while ($next(T_FUNCTION)) {
    if (
        strtolower($next(T_STRING)[1]) === 'bootstrap' &&
        $next('{')
    ) {
        $bracesStack = 1;
        while ($bracesStack) {
            $token = $next();
            if ($token[0] === '{') {
                $bracesStack ++;
            }
            if ($token[0] === '}') {
                $bracesStack --;
            }
        }
        $closingBracePosition = $token[3];
        break;
    }
}

if (!$closingBracePosition) {
    // method not found error
}

$before = mb_substr($code, 0, $closingBracePosition);
$after = mb_substr($code, $closingBracePosition);

$modifiedCode = "$before    \$this->addPlugin('$plugin');\n$after";
```
