### ISSUE TITLE
Port not working in DB config

### ISSUE THREAD

**Issue by stuchalk** [cakephp/cakephp#15522]
I think I have found a bug in the database config file 'Config/database.php', when a non-standard MySQL port is defined...

* CakePHP Version 2.10.24
* Platform and Target: macos 10.15.7, Apache 2.4.47, PHP 7.4.19

### What you did
I updated the config file to add 'port' => '3307' instead of the default '3306'.  Port '3307' is linked to a remote server on port '3306' via an SSH tunnel ![Uploading openports.png…](see)

### What happened
I ran a script to add some new data to a field in a database and the data was added to the local DB no the remote one at '3307'

### What you expected to happen
the script would update data in the remote database at port '3307'

I also tried hard coding the port in '/lib/Cake/Model/Datasource/Database/Mysql.php' and that does not change which server the scripts end up updating.... :(

**Comment by markstory** [comment]
The [MySQL driver creates the PDO connection string here](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Datasource/Database/Mysql.php#L181) and that should reflect the port you configure. If that doesn't result in the port being used you might be running into a problem with PDO.

With all of that said CakePHP 2.x is no longer receiving bug fixes, so this issue should it exist will not be fixed.

**Comment by stuchalk** [comment]
Mark

Thanks for the quick reply and thank you for everything CakePHP.

Stuart

On May 19, 2021, at 2:56 PM, Mark Story ***@***.******@***.***>> wrote:



The MySQL driver creates the PDO connection string here<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcakephp%2Fcakephp%2Fblob%2F2.x%2Flib%2FCake%2FModel%2FDatasource%2FDatabase%2FMysql.php%23L181&data=04%7C01%7Cschalk%40unf.edu%7C069116be08cf479ac98f08d91af7da09%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637570474101345175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VOH86bfik6ERouJWlKdVyQ%2FTNz7XokQ9360fkzn2Yvo%3D&reserved=0> and that should reflect the port you configure. If that doesn't result in the port being used you might be running into a problem with PDO.

With all of that said CakePHP 2.x is no longer receiving bug fixes, so this issue should it exist will not be fixed.
