### ISSUE TITLE
Cannot access PDOStatement::$queryString before initialized

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15537]
In PHP 8.1, accessing PDOStatement::$queryString before it's initialized with a value throws a type error:

```
Error: Typed property PDOStatement::$queryString must not be accessed before initialization
```

This is caused by code like this in `StatementDecorator`:
```
    public function __get(string $property)
    {
        if ($property === 'queryString') {
            /** @psalm-suppress NoInterfaceProperties */
            return $this->_statement->queryString;
        }
    }
```

And in `SqliteStatement` leading to that call:
```
    public function rowCount(): int
    {
        /** @psalm-suppress NoInterfaceProperties */
        if (
            $this->_statement->queryString &&
            preg_match('/^(?:DELETE|UPDATE|INSERT)/i', $this->_statement->queryString)
        ) {
```

This code seems to expect a `null` value returned when uninitialized. We'll need to only check this when the statement has executed.

**Comment by ADmad** [comment]
Checking if `$this->_hasExecuted` is `true` before trying to access `$this->_statement->queryString` would avoid the error isn't it?

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15548
