### ISSUE TITLE
Change return type of `BaseLog::scopes()`

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#15544]
The current return type of `BaseLog::scopes()` is `array|false` in docblock which should be changed to either `array` or `array|null`. All emptish values for scopes are treated the same anyway by the loggers.

Currently our app skeleton uses `'scopes' => false` in config arrays so best to do the suggested change in next major.

**Comment by dereuromark** [comment]
> Currently our app skeleton uses 'scopes' => false

Are you suggesting to make that null for the same behavior?
I am a bit afraid that null values here could easily be "wrongly" merged with empty array or alike, causing behavior changes.
The array config value here could still be false, but then reflect inside the actual code as different (null) return value?

**Comment by ADmad** [comment]
> Are you suggesting to make that null for the same behavior?

Yes.

> I am a bit afraid that null values here could easily be "wrongly" merged with empty array or alike

`Hash::merge(['scopes' => []], ['scopes' => null])` results in `['scopes' => null]` so we don't need to worry about values being "wrongly" merged.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/cakephp/pull/15610
