### ISSUE TITLE
Do we need to set isAjax attribute on request?

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15565]
In `RequestHandlerComponent::startup()`, set the the `isAjax` attribute if `is('ajax')` is true:

```
$isAjax = $request->is('ajax');
$controller->setRequest($request->withAttribute('isAjax', $isAjax));
```

This feels awkward and redundant. Why do we need to set 2 flags for the same value?

A search for `isAjax` in cakephp returns 0 use cases.

**Comment by othercorey** [comment]
I found a 4.0 migration note on this, but why aren't we promoting the use of `is('ajax')` which the code that is used to set this?

https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html#id1

> Cake\Controller\Component\RequestHandlerComponent now sets isAjax as a request attribute instead of request param. Hence you should now use $request->getAttribute('isAjax') instead of $request->getParam('isAjax').

**Comment by ADmad** [comment]
In 4.x all extra request params like `pagination`, `csrfToken`, `isAjax` where converted to request attributes. I guess in hindsight we should have just done away with `isAjax`.

**Comment by othercorey** [comment]
If it's actually used then nothing can do about it. Was confused until I saw the notes.

**Comment by ADmad** [comment]
It might be used by users in their apps/plugins.
