### ISSUE TITLE
Add lock support for model unique rule

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#15573]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: any

Actually, the unique model rule does not really avoid that no duplicated data will be inserted in DB.
In the most use cases, the unique model rule, is associated with a unique index on the DB, but not always.
In the case of the unique index is not present if some simultaneous request are handled there is the possibility that two request write the same data because there is no lock between the uniqueness check and the writing of the datum.
Also, if the unique index is present, sometimes two equal value will be written with a consequent database exception.

Can be helpful adding an additional rule params used for forcing a database lock when the uniqueness is checked.
Considering that Cakephp always open a transaction before the saving procedure, it shoud be enough adding a FOR UPDATE lock in the uniqueness check query. This will avoid the explained problem.

If the user open a transaction manually it will works too.

**Comment by othercorey** [comment]
I think adding a transaction in a rule that has to be unlocked by the save is too difficult. The user can wrap the save in a transaction if it is important to avoid save failures, right?

**Comment by doshu** [comment]
no its not simple. if when a unique rule is checked, the spalecial FOR
UPDATE lock must be set in the select statement to ensure the other
transaction will be locked

there is no options to manipulate the select statement generated by the
unique rule

Il sab 25 set 2021, 16:13 othercorey ***@***.***> ha scritto:

**Comment by othercorey** [comment]
Well, if you have an idea how to implement it, please open a PR.

Since locking is only available for specific database engines, the QueryCompiler would have to check driver features, I think. 

Also, the SQL syntax might be different for engines, not sure. If so, the driver should customize it. https://github.com/cakephp/cakephp/blob/4.x/src/Database/Driver/SqlDialectTrait.php#L144

**Comment by doshu** [comment]
a valid option could be pass permit to pass a callback to the unique rule
definition in the rule building process. the callback will give the
possibility to customize the generated select statement, so an epilog can
be addedd

Il sab 25 set 2021, 17:22 othercorey ***@***.***> ha scritto:

**Comment by othercorey** [comment]
> a valid option could be pass permit to pass a callback to the unique rule definition in the rule building process. the callback will give the possibility to customize the generated select statement, so an epilog can be added

I don't think cake will support a callback to inject SQL It would have to be part of the query.

**Comment by othercorey** [comment]
Closing due to lack of support. Application rules are meant to make basic checks in support of database indexes. We aren't going to be able to support this.
