### ISSUE TITLE
Custom CSRF Token cookie name not respected by IntegrationTestTrait

### ISSUE THREAD

**Issue by captain-redbeard** [cakephp/cakephp#15585]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6 - 243a54d83438d9e9d5e3f4ccc1e379dcd20b5a38
* Platform and Target: PHP 7.4.9 CLI

### What you did
Within Application.php middleware I updated the CsrfProtectionMiddleware to use a custom cookie name, after this I reran my unit tests and found all POST requests were failing with 'Cake\Http\Exception\InvalidCsrfTokenException: Missing or incorrect CSRF cookie type.'.

Application.php
```
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
    ...

    // Cross Site Request Forgery (CSRF) Protection Middleware
    ->add(new CsrfProtectionMiddleware([
        'httponly' => true,
        'secure' => true,
        'cookieName' => '__Secure-myapp-csrfToken',
        'samesite' => 'Strict',
    ]))
```

ForgotControllerTest.php
```
class ForgotControllerTest extends IntegrationTestCase
{
    public function setUp(): void
    {
        parent::setUp();
        $this->disableErrorHandlerMiddleware();
        $this->enableCsrfToken();
        $this->enableSecurityToken();
    }

    public function testResetPassword()
    {
        $data = [
            'email' => 'test@test.com',
        ];
        $this->post('/forgot/reset-password/myguid', $data);
        $this->assertResponseOk();
    }
```

### What happened
Setting a custom cookie name within CsrfProtectionMiddleware is causing unit tests to fail with 'Cake\Http\Exception\InvalidCsrfTokenException: Missing or incorrect CSRF cookie type.'.

Using the default cookie name of 'csrfToken' allows the tests to pass as expected.

### What you expected to happen
I expected the IntegrationTestTrait to use the custom cookie name when setting tokens with the enableCsrfToken() function.

From my initial investigation I have found the IntegrationTestTrait.php is using a hardcoded cookie name on lines 658 - 671.
https://github.com/cakephp/cakephp/blob/95a6818297c8ea1b30d9013dae0cfbc57acdfc5d/src/TestSuite/IntegrationTestTrait.php#L658-L671

**Comment by markstory** [comment]
> I expected the IntegrationTestTrait to use the custom cookie name when setting tokens with the enableCsrfToken() function.

How would tests get the cookie name configured in your application. The difficulty in doing that is one reason that we have the field hardcoded right now.

**Comment by captain-redbeard** [comment]
> > I expected the IntegrationTestTrait to use the custom cookie name when setting tokens with the enableCsrfToken() function.
> 
> How would tests get the cookie name configured in your application. The difficulty in doing that is one reason that we have the field hardcoded right now.

Could this be an optional parameter passed into the enableCsrfToken function for those who change the name of the cookie?

**Comment by markstory** [comment]
> Could this be an optional parameter passed into the enableCsrfToken function for those who change the name of the cookie?

That could work. Would you be interested in putting together a pull request for that change?

**Comment by captain-redbeard** [comment]
Yeah I’ll take a look.
