### ISSUE TITLE
Looking for a way to disable sessions update

### ISSUE THREAD

**Issue by neobie** [cakephp/cakephp#15581]
I am looking for a way to disable cake_sessions update to database.

Some action/ajax is calling general page which doesn't need to check for user session or auth.

But it is frequent requests from app / web, which could cause DB frequent write/update and thus could use up the connections quickly, which isn't really necessary.

Also, no session update required if user is not authenticated user.

**Comment by markstory** [comment]
You could write your own Session handler that does more application aware session data change detection. I'm not sure the conditions you've outlined are universally true and something that we can incorporate into the classes that CakePHP provides.

**Comment by ADmad** [comment]
Closing for the reason stated above.
