### ISSUE TITLE
Command test fails with error "sprintf(): Too few arguments" when asserting contents that have a format specifier (e.g. %s)

### ISSUE THREAD

**Issue by fugaco** [cakephp/cakephp#15588]
This is a **bug**.

* CakePHP Version: 4.2.6.
* Platform and Target: PHP 7.4 (`sprintf` still returns `false` when fails)

### What you did
Executed a phpunit test like: `vendor/bin/phpunit tests/TestCase/Command/SomethingCommandTest.php`.

The command outputs json formatted text containing format specifiers such as "%s".

### What happened
The test failed  with error: 
```
1) App\Test\TestCase\Command\SomethingCommandTest::testExecute
TypeError: Return value of Cake\TestSuite\Constraint\Console\ContentsContain::toString() must be of the type string, boolean returned
```

The essential problem is that the test throws `sprintf(): Too few arguments` because my `$this->contents` has format specifiers such as "%s".
```php
// Cake\TestSuite\Constraint\Console\ContentsContain::toString()

    public function toString(): string
    {
        return sprintf('is in %s,' . PHP_EOL . 'actual result:' . PHP_EOL . $this->contents, $this->output);
    }
```

### What you expected to happen

Eliminate the error by moving the sprintf's closing bracket like this:
```php
        return sprintf('is in %s,' . PHP_EOL . 'actual result:' . PHP_EOL, $this->output) . $this->contents;
```

**Comment by ADmad** [comment]
Would you like to submit a PR with the fix?

**Comment by dereuromark** [comment]
Both static analyzers didnt report this mistake?

**Comment by fugaco** [comment]
I submitted a pull request: #15590
