### ISSUE TITLE
Check if HTTP_HOST has been set before resorting to localhost in test/bootstrap.php

### ISSUE THREAD

**Issue by alexvanniel** [cakephp/cakephp#15584]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6.
* Platform and Target: CentOS 7, MariaDB, PHPUnitTest 8.5.15

### What you did
Configured phpunit.xml to have the server and http_host lines like so:
    <php>
        <server name="HTTP_HOST" value="my.domain.local" />
    </php>

And then ran a unittest from the terminal/shell/cli that reads/outputs the HTTP_HOST / HTTP_REFERER.

### What happened
App.fullBaseUrl is set to http://localhost in test/bootstrap.php resulting so things like Controller::referer() always return http://localhost no matter what you set HTTP_HOST to.

### What you expected to happen
App.fullBaseUrl set to the value defined in the phpunit.xml file and Controller::referer() to return that value.

**Comment by ADmad** [comment]
The request instance created by the factory already sets the hostname to `localhost` by default https://github.com/cakephp/cakephp/blob/95a6818297c8ea1b30d9013dae0cfbc57acdfc5d/src/Http/ServerRequestFactory.php#L248
So perhaps we simply need to remove the line that sets `App.baseUrl`.

**Comment by alexvanniel** [comment]
I did not even know that. I must admit that I did not dig THAT deep, I hope you will forgive me for that.
Also, it is something that will be present when you create an application based on the skeleton application. So any changes done in the skeleton app will not change any existing projects.

**Comment by markstory** [comment]
Closing as cakephp/app#844
