### ISSUE TITLE
Add isInternal to Router::class

### ISSUE THREAD

**Issue by alexvanniel** [cakephp/cakephp#15609]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6
* Platform and Target: CentOS 7, PHP 7.4.x

### What you did
Trying to determine if something considered a url is either internal or external using Router.

### What happened
There isn't really such a method. routeExists() will return true for valid external links. So what happened is that there isn't really a method to use that can actually tell if a url is internal or external.

### What you expected to happen
Passing something like /controller-name/action-name/some-id should be identified somehow as internal, just like https://my.local-machine.lan/controller-name/action-name/some-id and something like https://www.external-site.com/ should be considered an external link. 

I would like to see the Router::class be extended with a method called isInternal() for instance. This could be done like this, bare in mind this is not something I would like to submit as a PR since I am not sure if it would hold up in all cases. It will not for instance take subdomains into account. So https://my.local.lan/ is an internal link but https://nothing.local.lan/ could be considered internal but will not be when the below code would be used. Nor do I know if this is entirely up to par with the CakePHP coding standards and for addition to the Router::class some things need to changes like getting the request object. But here goes:

```
        // default redirect url (in case an invalid or no redirect was supplied)
        $redirect = Router::url([
            'controller' => 'DefaultController',
            'action' => 'defaultAction',
        ]);

        // get the current host to check against
        $currentHost = $this->getRequest()->host();

        // get the redirect param from the request query string
        $redirectParam = $this->getRequest()->getQuery('redirect', null);

        if (!empty($redirectParam)) {
            // parse the redirect param so we can access the host
            $parsedUrl = parse_url(Router::url($redirectParam, true));
        }

        if (
            !empty($parsedUrl)
            && !empty($parsedUrl['host'])
            && strtolower($parsedUrl['host']) === strtolower($currentHost)
        ) {
            // get the raw redirect query parameter since it appears to be internal
            // this does not mean it is a valid route, only that it is considered an internal one
            $redirect = Router::url($redirectParam);
        }

```

**Comment by markstory** [comment]
> There isn't really such a method. routeExists() will return true for valid external links. So what happened is that there isn't really a method to use that can actually tell if a url is internal or external.

By internal and external do you mean whether or not the URL would go back to the current application? How would you define 'internal' and 'external' for applications that span multiple subdomains?

**Comment by alexvanniel** [comment]
Above code would not be ideal for subdomains... I have been taking a look at the getLoginRedirect used by the Authentication middleware, but simply checking if a host/scheme is missing does not really answer this question I suspect. And checking for multiple domains might be prone to hacking attempts. Would getting the domain from the host using a regex be something?
Something like this:

```
    public function extractDomain(string $domain): string
    {
        if (preg_match("/(?P<domain>[a-z0-9][a-z0-9\-]{1,63}\.[a-z\.]{2,6})$/i", $domain, $matches)) {
            return $matches['domain'];
        } else {
            return $domain;
        }
    }

    public function extractSubdomains(string $domain): string
    {
        $subdomains = $domain;
        $domain = $this->extractDomain($subdomains);

        $subdomains = rtrim(strstr($subdomains, $domain, true), '.');

        return $subdomains;
    }

```

Not sure if this will be helpful ...

**Comment by markstory** [comment]
If you need to parse the URL, using [parse_url](https://www.php.net/parse_url) is better as the regex for domains names is complicated. That function will extract the domain and protocol and should let you check if the host does not match the current application's host.

How to include subdomains would require defining a host list. I'm not sure we need to add the concept of internal/external though. It sounds like you're looking to compare the domain of a URL to an allowed list of domains. This is a bit out of scope for `Router` which covers application URL generation, and URL parsing for incoming requests. There could be another class for URL related operations though.

**Comment by alexvanniel** [comment]
This idea was actually born out of the need to validate a url or path passed by a query parameter but I eventually went with the Authentication::getLoginRedirect() way of things... So this might be completely unnecessary by now and external/internal would not even be the answer to what I was really asking.
