### ISSUE TITLE
ConnectionAlias + @dataProvider

### ISSUE THREAD

**Issue by lordphnx** [cakephp/cakephp#15618]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.7
* Platform and Target: Chrome, OSX, PHP7.4, Apache, PHPUnit, XDebug

### What you did
Inside a unit test, I `$this->loadModel("Users");` then `$Table = $this->Users`. The resulting `Table` object is configured to use the `default` connection instead of `test`.

### What happened
When loading a model (`$this->loadModel("Users");` inside a method marked as `@dataProvider`, the resulting `Table` connects to the `default` datasource instead of `test`. My debugging sessions suggest this is because the `setUp` method is not run before the `@dataProvider`

### What you expected to happen
Before `@dataProviders` are run, the `Testcase::setUp` method should be run, so that `default` can be correctly aliased to `test`

**Comment by markstory** [comment]
> Before @dataProviders are run, the Testcase::setUp method should be run, so that default can be correctly aliased to test

This is not something we can change as it is how PHPUnit behaves.
