### ISSUE TITLE
Should we start setting maximum php versions?

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15629]
We've started to see how incompatible different php versions are with 8.0 and 8.1. Although we strive to support the latest version of php, this seems to always require a minor/point release of cakephp.

Should we simply set the maximum php version supported and require users to disable platform requirements when they want to use an unstable/unsupported configuration?

We've had to set a maximum for previous major releases due to lack of support. However, if we don't do this then users won't know there isn't support.

I have not done a comparison against the major framework libraries, but cakephp does not do maintenance releases for previous minors.

**Comment by dereuromark** [comment]
Clear :-1: 
We always aim to then also support it as soon as possible, way in advance, unblocking people from using also earlier versions then.

As do most other software vendors for this reason.
The locking-in is worse than the drawback of the current way IMO.

**Comment by othercorey** [comment]
It seems to always require a minor release. How is that fixing it way in advance?

**Comment by dereuromark** [comment]
So far, history showed it was always such minor issues in also only a small part of the system.
Often not even used parts by the majority.
Maybe this time it is different now.

**Comment by markstory** [comment]
I'm somewhat in favour. We would have been able to avoid a bunch of questions around 2.x and PHP8 compatibility if we had done this in the past. If a new PHP version comes out and we don't have to do any work, we can increase the allowed versions in patch release too.

**Comment by dereuromark** [comment]
Given that composer now has --ignore-platform-req=php (without s) for only skipping one specific requirement like PHP makes it at least easier to workaround if needed without having to ignore all other reqs.
That's at least something that minimizes issues here in case of locking down "too much" where it actually would work.

**Comment by othercorey** [comment]
I don't know what the right answer is. I just want to discuss the pros and cons to see if it makes cake a better package. If we do it, I think it makes sense for cakephp/cakephp and maybe cakephp/chronos only.

I think the con @dereuromark was describing is "perception". We want people to think of cake as responsive and supporting what they need on time. If we want to deal with support issues to avoid that, then so be it.

However, I'm starting to think this is just a technical issue. We don't back-port fixes to previous minor releases. For example, cake 4.1 definitely does not support php 8 and cake 4.2 definitely does not support 8.1. We do want to add support for future versions as soon as possible. Usually that requires a minor release -- sometimes that minor release doesn't happen before the php version is released. Sometimes like 4.3, it will happen well before.

The change in 3.9 to limit to PHP 7 was awkward because that wasn't set for any previous versions.

**Comment by othercorey** [comment]
Setting php version restrictions to point releases is unusual. Looking at other packages, I think they just do what we have done and assume people know it's not supported. 

However, how do you know? Only if you see php errors thrown.

**Comment by markstory** [comment]
> Setting php version restrictions to point releases is unusual. Looking at other packages, I think they just do what we have done and assume people know it's not supported.

I was thinking more that we would expand the compatible ranges in bugfix releases if the scope of changes required for a future php are minor. I know that has not been the case in the past few years though.
