### ISSUE TITLE
Timeout when using auto-wiring 

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#15634]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.7
* Platform and Target: LEMP (Alpine/Docker)

### What you did

In `src/Application.php` I added a service to the container and add a ReflectionContainer() delegate for auto-wiring.

```php
    /**
     * @param ContainerInterface $container
     */
    public function services(ContainerInterface $container): void
    {
        /** @var Container $container */
        $container->add(GetActorService::class);
        $container->delegate(new ReflectionContainer());
    }
```

GetActorService expects an ActorsTable class:

```php
class GetActorService
{
    /**
     * @var ActorsTable
     */
    private $table;

    public function __construct(ActorsTable $table)
    {
        $this->table = $table;
    }
```

### What happened

```
<b>Fatal error</b>:  Maximum execution time of 30 seconds exceeded in <b>/srv/app/vendor/league/container/src/Container.php</b> on line <b>188</b><br />
```

### What you expected to happen

The service to be properly auto-wired and usable where injected. In this case, in a controller:

```
    /**
     * View method
     *
     * @param GetActorService $getActor An instance of GetActorService.
     * @param string $id Actor id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException Actor Not Found
     * @throws \Cake\Http\Exception\MethodNotAllowedException
     */
    public function view(GetActorService $getActor, string $id)
    {
        $this->request->allowMethod('get');
        $this->set('actor', $getActor->get(intval($id)));
        $this->viewBuilder()->setOption('serialize', 'actor');
    }
```

It appears to be attempting to auto-wire EVERYTHING when this is enabled. Ideally, I'd just like to auto-wire what I've added to the container. It might be that I don't understand this well enough...

**Comment by markstory** [comment]
Auto wiring will recourse through dependencies until it can build the full tree. You might have some cycles and may need to explicitly define some objects to break the cycles.

Finding out where cycles are can be tedious. In the past I have modified the container to output what it is resolving to debug this kind of thing.

**Comment by CriztianiX** [comment]
In the past, I was struggling with the same problem.
My solution was to use ModelAwareTrait.
 ModelAwareTrait gives you loadModel(), so, you can load your tables from registry.

Here my example

```php
class ValidateCsvJob
{
    use LogTrait;

    use ModelAwareTrait;

    use SealedContainerTrait;

    private StorageServiceinterface $storageService;

    private EventServiceInterface $eventService;

    public function __construct()
    {
        $this->storageService = $this->getContainer()->get(StorageServiceInterface::class);

        $this->eventService = $this->getContainer()->get(EventServiceInterface::class);

        $this->loadModel(ImportedCsvTable::class);
    }
}
```

**Comment by cnizzardini** [comment]
Another way to handle this would be functionality akin to laravel: https://laravel.com/docs/8.x/container#binding-a-singleton

**Comment by markstory** [comment]
You can create shared services with [setShared()](https://container.thephpleague.com/3.x/definitions/)
