### ISSUE TITLE
->firstOrFail() not working after ->map()

### ISSUE THREAD

**Issue by RiteshParyali** [cakephp/cakephp#15631]
**->firstOrFail()** is not working after **->map()**

* CakePHP Version:  "version": "4.2.7" 

### What you did
Not working code:
```php
$this->Payments->find('all')->where([............])->contain([.......])
            ->map(function ($q) {
                $q->code = $q->prefix . $q->id;
                return $q;
            })
            ->firstOrFail();
```

### What happened
**Call to undefined method Cake\ORM\ResultSet::firstOrFail()**

### N.B
 **->first() is working perfectly**

### What you expected to happen

Records not found if not available

**Comment by othercorey** [comment]
`map()` returns `CollectionInterface` which has `first()`. 

https://book.cakephp.org/4/en/core-libraries/collections.html#list-of-methods

You can use `formatResults()` to do something similar with the Query object:
https://book.cakephp.org/4/en/orm/query-builder.html#adding-calculated-fields

**Comment by RiteshParyali** [comment]
Not resolved in **4.2.8**

**Comment by markstory** [comment]
@RiteshParyali There is no fix for this. Don't call firstOrFail() after `map()` as the result of `map()` is a collection which doesn't have `firstOrFail()`.

**Comment by othercorey** [comment]
We added a deprecation warning in 4.3 so users know they must call `all()` before calling `map()`.
