### ISSUE TITLE
Logs skipScopes option

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#15677]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: 4, 3.10

Can we add option Log.{name}.skipScopes (like Error.skipLog)?

So it will be possible to exclude some scopes but leave all other scopes.

Example:

	'debug' => [
		'className' => FileLog::class,
		'path' => LOGS, 
		'file' => 'debug',
		'levels' => ['notice', 'debug'],
		'skipScopes' => ['queriesLog'],
	],

**Comment by markstory** [comment]
If a logger has the same scope in both `scopes` and `skipScopes` what happens?

**Comment by andrii-pukhalevych** [comment]
If `scopes` are defined it's ok to ignore `skipScopes`

**Comment by dereuromark** [comment]
Ignoring the ignore? this might take it a bit too far ;)

**Comment by dereuromark** [comment]
I am not sure we have here enough supporters for this.
I would recommend using your own plugin based extension here to support this as opt-in solution instead.

Can we close this then?

**Comment by andrii-pukhalevych** [comment]
I asked this mostly to skip writing query logs into debug.log. But I will find a way to wrap this )
