### ISSUE TITLE
cake 5: Normalize passing $config to initialize()

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15670]
We have 2 separate patterns for `initialize()` methods in cakephp:

1. initialize with no arguments
2. initialize with the un-merged user-provided config

I would like to normalize these into a single, consistent pattern (where applicable).

Most places, we do *not* want to pass the un-merged user options to initialize because:

1. Confusing to users.
2. Unable to retrieve the same values later

There is one example of this as expected behavior in TimestampBehavior:

```
    public function initialize(array $config): void
    {
        if (isset($config['events'])) {
            $this->setConfig('events', $config['events'], false);
        }
    }
```

In this case, because constructors call `$this->setConfig($config)` where `$merge` defaults to true, the events are actually merged with the default value:

```
    protected $_defaultConfig = [
        'implementedFinders' => [],
        'implementedMethods' => [
            'timestamp' => 'timestamp',
            'touch' => 'touch',
        ],
        'events' => [
            'Model.beforeSave' => [
                'created' => 'new',
                'modified' => 'always',
            ],
        ],
        'refreshTimestamp' => true,
    ];
```

The typical way classes override user-provided config behavior is to override the constructor to *fixup* the config values. 

Do we want to:

1. Move config "fixup" to the constructor
2. Change how defaults are merged
3. Rely on the un-merged config in `initialize()` and expand that behavior

**Comment by markstory** [comment]
Aligning on the 'un-merged' config data as a parameter will create the fewest breaking changes, and gives us the more flexibility than pre-merging does.
