### ISSUE TITLE
Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by ariany-f** [cakephp/cakephp#15693]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.*

* Platform and Target: All

### What you did
Altered the line 242 of ConsoleOutput.php because implode function can no longer receive glue after the pieces in PHP 7.4*
`-> return "\033[" . implode(';', $styleInfo) . 'm' . $matches['text'] . "\033[0m";`

### What happened
Implode function can no longer receive glue after the pieces

### What you expected to happen
implode( $glue, $pieces );

**Comment by ndm2** [comment]
This has been fixed as of CakePHP 3.8.3.

https://github.com/cakephp/cakephp/blob/705b43b70e87ec226a6b37099013de1003a17c17/src/Console/ConsoleOutput.php#L243

You'll either have to upgrade your application accordingly, or stick to an older PHP version.
