### ISSUE TITLE
Add mock response support to Http\Client

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#15694]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

When writing tests for application code that interacts with external APIs it is often necessary to 'stub' out the external API via mock responses. PHPUnit mock objects are a poor fit for this purpose as they are verbose to configure and setup.

I have used general purpose libraries like [VCR](https://github.com/php-vcr/php-vcr) in the past to mock external HTTP APIs. It has the benefit of being able to mock client libraries outside of CakePHP's HTTP client. However, it requires a more complex setup step, and defining responses in YAML or JSON can be challenging to maintain and contain duplication.

This issue aims to provide a simple to operate API for our `Http\Client` that is similar (but smaller) in scope than [responses](https://github.com/getsentry/responses) and [guzzle mock handlers](https://docs.guzzlephp.org/en/stable/testing.html).

```php
use Cake\Http\Client;
use Cake\Http\Client\Response;

// In a test method.
$headers = [
    'Content-Length' => 11,
];
$body = 'Hello World';
Client::addMockResponse('POST', 'http://example.com/path', Response::create(200, $headers, $body));
```

The above would require the addition of `Response::create()` in addition to `addMockResponse()`

### Matching Requests

The basic matching would be performed on the request method and URL. Additional matching logic can be defined by developers using an option:

```php
Client::addMockResponse('post', 'http://example.com/path', $response, [
    'match' => function (Request $request): bool {
        return true;
    }
]);
```

The result of the match function is applied *after* the URL matches. URLs can use a trailing wildcard (`*`) to match path fragments. An example of this would be `http://example.com/api/v1/*` The trailing wildcard is only valid at the end of the URL. In the future we could expand URL matching to accept patterns, but that is out of scope for now.

### Multiple Responses

Several styles of APIs require you to do multiple requests to an endpoint and each operation generates a different result based on the input parameters. This usage case can be accomodated by calling `addMockResponse()` multiple times and using the `match` option to disambiguate the responses. Without a `match` option, the client will iterate the responses in a cycle.

### HttpMockTrait

While the above examples use the `Client::addMockResponse()` interface, we should also provide a trait to improve ergonomics.  Application test code would be able to use the following:

```php
use Cake\TestSuite\HttpMockTrait;
use Cake\TestSuite\TestCase;

class ArticlesControllerTest extends TestCase
{
    use HttpMockTrait;

    public function testList()
    {
        $this->mockClientPost('http://example.com', $this->newResponse(200, [], 'some text'), $options);
    }
}
```

The trait would provide `mockClient{$method}` methods for GET, POST, PATCH, DELETE, PUT, HEAD, OPTIONS. The `mockClientRequest($method, $url, $response, $options)` would also exist for non-standard request methods.

The `HttpMockTrait` would also use an `@after` hook to automatically clean up the mocked responses.

### Clearing Mock Responses

Mock responses can be cleared with:

```php
Client::clearMockResponses();
```

This method would be used from test case `tearDown()` methods.

### Implementation Ideas

Mock responses would be matched within `Client::_sendRequest()` before sending the request to the current adapter. This allows mocks to shortcut the adapter. Pseudo code for the new method would be:

```php
protected function _sendRequest(RequestInterface $request, array $options): Response
{
    if ($this->_mockResponses) {
        $responses = $this->_matchingMocks($request, $options);
    }
    if (empty($responses)) {
        $responses = $this->_adapter->send($request, $options);
    }
    foreach ($responses as $response) {
        $this->_cookies = $this->_cookies->addFromResponse($response, $request);
    }

    return array_pop($responses);
}
```

I remember there being another open issue related to this but have failed to find it this evening.

**Comment by othercorey** [comment]
This seems to be incomplete for 4.3. Do we need to create a trait?

**Comment by markstory** [comment]
The trait is done too.
