### ISSUE TITLE
Wrong required="required" attribute for requirePresence validation

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#15699]
* [x] bug

* CakePHP Version: 4.2

### What you did
Code in model-less form or in table:

	public function validationDefault(\Cake\Validation\Validator $Validator): \Cake\Validation\Validator {
		return parent::validationDefault($Validator)
			->requirePresence('fieldname')
			;
	}

### What happened
Input was generated with form helper has `required="required"` attribute

### What you expected to happen
Input is generated with form helper does not have `required="required"` attribute, because `Validator::requirePresence()` does not check that field can not be empty, it only checks that field is present in request.

**Comment by markstory** [comment]
Fields by default are not allowed to be empty. You need to set `allowEmpty()` on the field to make it not required.

**Comment by andrii-pukhalevych** [comment]
Seems that fields are not allowed to be empty in fronted only (when `requirePresence('fieldname')` only was called).

Executing `jQuery('[required]').prop('required', false)` in JS console allows easily to send empty fields and Form->valiate() returns true in this case.

Looks like inconsistency between front-end and back-end.

**Comment by markstory** [comment]
That is odd. I'm reluctant to change the behavior in a bugfix release because it will most likely cause problems in userland applications as previously required fields become no longer required.

**Comment by othercorey** [comment]
Should this be moved to 5.0 or closed as won't fix?

**Comment by andrii-pukhalevych** [comment]
Or should be fixed and included in 4.3?

**Comment by markstory** [comment]
> Or should be fixed and included in 4.3?

I don't know how we change the behavior and also have it be 'backwards compatible' at the same time.

**Comment by dereuromark** [comment]
Then we should revisit this for 5.x then.

**Comment by ADmad** [comment]
This happens because `ValidationSet::$_allowEmpty` is `false` by default. One needs to explicitly use one of the `Validator::allowEmpty*()` methods to allow the field to be empty. This is a reasonable default IMO.

**Comment by andrii-pukhalevych** [comment]
Should not `ValidationSet::$_allowEmpty` be `true` by default?

Its good to be any by default, but inconsistency between front-end and back-end should be fixed.

**Comment by ADmad** [comment]
> Its good to be any by default, but inconsistency between front-end and back-end should be fixed.

Yes the inconsistency should be addressed.

**Comment by ADmad** [comment]
So the issue occurs because of how `Validator::isEmpty()` works. Since no `allowEmpty*/notEmpty*()` call was used for the field, `validate()` calls `isEmpty()` with flag `Validator::EMPTY_NULL` (and value `''`) causing it to return `false`. Hence empty string gets allowed and validation passes.

**Comment by othercorey** [comment]
> > Its good to be any by default, but inconsistency between front-end and back-end should be fixed.
> 
> Yes the inconsistency should be addressed.

Is there anything left to do for this?

**Comment by markstory** [comment]
> Is there anything left to do for this?

We could update FormHelper to detect whether or not a field is required to be non-empty so that the required attribute is only applied when the field is both required and has a validation rule or not-empty requirement.

**Comment by andrii-pukhalevych** [comment]
Can a fix for this issue be included in cake 5.0?

**Comment by markstory** [comment]
> Can a fix for this issue be included in cake 5.0?

It could if someone wanted to put together a pull request for the changes.
