### ISSUE TITLE
HtmlHelper::image() with 'base64' option throws InvalidArgumentException with Asset.timestamps = 'force'

### ISSUE THREAD

**Issue by trenshaw** [cakephp/cakephp#15695]
* [x] bug
* CakePHP Version: 2.10.24
* Platform and Target: Nginx 1.18.0, MySQL 8.0.25, Linux 5.4.0 (Ubuntu 20.04)

### What you did
    Configure::write('Asset.timestamp', 'force');
    $this->Html->image('logo.png', ['base64' => true]); 

### What happened
HtmlHelper::image() calls Helper::assetUrl() which appends a query string to the image's $path which cannot be canonicalized in the file system i.e. results in a file path of /var/www/html/project/app/webroot/img/logo.png?1545961216

As such the check for if not file exists or if not file is readable results in an InvalidArgumentException and the message 'Unable to find the requested image to output as base64!'

This may have been resolved in future versions of CakePHP but suspect it has been carried over?

**Comment by trenshaw** [comment]
In my project I actually extend and override HtmlHelper::image() for output of base64 encoded images (from files and dynamic sources e.g. QR codes for OATH and output of LDAP attribute thumbnailPhoto)

It may not be the most elegant solution but I use strtok() to split the file path from the query string and asset timestamp when setting the $fullPath variable

    $fullPath = strtok(WWW_ROOT . $path, '?');

**Comment by markstory** [comment]
2.10 has reached end of life and is no longer being maintained.
