### ISSUE TITLE
Invalid handling of null value by isUnique validation rule

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#15704]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.10.
* Platform and Target: Apache, MySQL 5.6.

### What you did
Add validation rule in `buildRules` method:
```
      $rules
            ->add($rules->isUnique(
                ['a_id', 'b_id', 'c']
            ));
```
Save entity:
```
        $data = [
            'a_id' => '2',
            'b_id' => '33',
            'c' => null,
        ];
        $entity = $this->MyTable->newEntity($data);
        $this->MyTable->save($entity);
```

### What happened
Wrong SQL was generated:
```
SELECT 1 AS `existing` 
FROM `my_table` `MyTable` 
WHERE (`MyTable`.`a_id` = 2 AND `MyTable`.`b_id` = 33 AND `MyTable`.`c` = NULL) 
LIMIT 1
```

### What you expected to happen
I would expect this SQL:
```
SELECT 1 AS `existing` 
FROM `my_table` `MyTable` 
WHERE (`MyTable`.`a_id` = 2 AND `MyTable`.`b_id` = 33 AND `MyTable`.`c` IS NULL) 
LIMIT 1
```

**Comment by bancer** [comment]
Thanks. This works but it doesn't look right to generate wrong SQL in order to handle some scenario. 

>  You cannot use arithmetic comparison operators such as =, <, or <> to test for NULL. To demonstrate this for yourself, try the following query:
>
> ```
> mysql> SELECT 1 = NULL, 1 <> NULL, 1 < NULL, 1 > NULL;
> +----------+-----------+----------+----------+
> | 1 = NULL | 1 <> NULL | 1 < NULL | 1 > NULL |
> +----------+-----------+----------+----------+
> |     NULL |      NULL |     NULL |     NULL |
> +----------+-----------+----------+----------+
>```
>
> Because the result of any arithmetic comparison with NULL is also NULL, you cannot obtain any meaningful results from such comparisons. 

https://dev.mysql.com/doc/refman/5.6/en/working-with-null.html

Couldn't the null value field comparison be simply removed from `WHERE` instead of comparing it to `null` with `=` in the scenario when 'allowMultipleNulls' is true?

**Comment by markstory** [comment]
> Couldn't the null value field comparison be simply removed from WHERE instead of comparing it to null with = in the scenario when 'allowMultipleNulls' is true?

It could, but no one has been interested in fixing it enough that it got fixed.

**Comment by othercorey** [comment]
This option was re-introduced in 4.2 with a different implementation that avoids the invalid null sql.

You could backport to 3.10 as long as it has the same behavior.

https://github.com/cakephp/cakephp/pull/15226

**Comment by othercorey** [comment]
Closing due to 3.x maintenance support ending.
