### ISSUE TITLE
Form radio id when value is negative

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#15700]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x and 3.9
* Browser: Firefox & Brave (chromium)

### What you did
```php
echo $this->Form->control('bounces', [
    'type' => 'radio',
    'options' => [
        0 => 'default',
        -1 => 'reject',
        1 => 'accept',
    ],
])
```

### What happened
Code above produce this html
```html
<label for="bounces-0">
    <input type="radio" name="bounces" value="0" id="bounces-0">default
</label>
<label for="bounces-1">
    <input type="radio" name="bounces" value="-1" id="bounces-1">reject
</label>
<label for="bounces-1">
    <input type="radio" name="bounces" value="1" id="bounces-1">accept
</label>
```

### What you expected to happen
The `for` in label for value `1` and `-1` are exactly same.  Like `input` ids
When users click on `accept label`, the `reject` radio is checked

**Comment by dereuromark** [comment]
Negative values should have some kind of prefix or suffix then on the slug probably.

**Comment by Erwane** [comment]
maybe the id should be `bounces--1` ?

**Comment by Erwane** [comment]
Thanks a lot @markstory :kneeling_person:
