### ISSUE TITLE
PHP 8.1: ContainerInterface::add() incompatible

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15710]
Looks like the added `$shared` parameter is incompatible.

```
PHP Fatal error:  Declaration of League\Container\Container::add(string $id, $concrete = null): League\Container\Definition\DefinitionInterface must be compatible with Cake\Core\ContainerInterface::add(string $id, $concrete = null, bool $shared = false): League\Container\Definition\DefinitionInterface in /cake/src/Core/Container.php on line 64
```

**Comment by othercorey** [comment]
@ADmad This seems related to the interface changes you are making in 5.0.

**Comment by ADmad** [comment]
Well I bumped the major for league/container to v4 for Cake 5.0, it's still v3 for Cake 4.x where League\Container\Container::add() does have the 3rd param.

Did you maybe forget to run `composer up` after switching branches?

**Comment by othercorey** [comment]
> Did you maybe forget to run `composer up` after switching branches?

That's probably it, thanks. I was trying to test 4.next with 8.1 to find what's causing bizarre phpunit errors.
