### ISSUE TITLE
Zero Primary Key Bug

### ISSUE THREAD

**Issue by raizpvp** [cakephp/cakephp#15721]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6
* Platform and Target: XAMPP v3.2.4 (local) | Database: MySQL (external)

* Database:
CREATE TABLE IF NOT EXISTS `roles` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

### What you did
I wanted to create a second role via the template. I created the controller and the template via CakePHP.

### What happened
This error message returned:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

### What you expected to happen
A new role should actually be created.

**Comment by dereuromark** [comment]
You forgot the auto increment for interger primary keys as per SQL specs.

**Comment by raizpvp** [comment]
> You forgot the auto increment for interger primary keys as per SQL specs.

<3 thank you
