### ISSUE TITLE
Subdirectories inside src/Command

### ISSUE THREAD

**Issue by peyopeev0206** [cakephp/cakephp#15733]
This is a (multiple allowed):

* [] bug
* [] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8 (but it's happening on 4.0 too)
* Platform and Target: nginx. Mysql

Add the ability to have subdirectories inside the src/Command folder.

**Comment by ADmad** [comment]
You can use the CommandCollection::add() method to add commands from whatever location you need. The directory scanning for auto discovery won't be changed to support sub folders.

**Comment by zejji** [comment]
I think this is the wrong decision from a code organization and maintenance perspective.

Once a project has tens or hundreds of commands, it becomes very ugly to keep all commands in the root Command directory.

Requiring commands to be added manually to the command collection just adds an additional maintenance burden.

I am currently updating a CakePHP 3 solution which has hundreds of shell methods (neatly organized into related functionality by shell class) to Cake PHP 4 commands and this feels like a backwards step in more ways than one, requiring much more boilerplate code.

**Comment by dereuromark** [comment]
@zejji The org/maintenance of classes is not the issue IMO, my main concern was the verbosity of the root level in CLI
See https://github.com/cakephp/cakephp/issues/12123
So far this was not resolved yet and is the main issue with the flat list (vs nested from shells).
