### ISSUE TITLE
Duplicate logs in Console Command with ConsoleLog

### ISSUE THREAD

**Issue by shigemk2** [cakephp/cakephp#15735]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.10.0
* Platform and Target: Apache Mysql

### What you did

ConsoleCommand
```php
<?php
namespace App\Command;

use Cake\Console\Arguments;
use Cake\Console\Command;
use Cake\Console\ConsoleIo;

class HelloCommand extends Command
{
    public function execute(Arguments $args, ConsoleIo $io)
    {
        $this->log('this log info hello', 'info');
    }
}
```

Logging settings
```php
    /*
     * Configures logging options
     */
    'Log' => [
        'debug' => [
            'className' => ConsoleLog::class,
            'scopes' => false,
            'levels' => ['notice', 'info', 'debug'],
        ],
        'error' => [
            'className' => ConsoleLog::class,
            'scopes' => false,
            'levels' => ['warning', 'error', 'critical', 'alert', 'emergency'],
        ],
        // To enable this dedicated query log, you need set your datasource's log flag to true
        'queries' => [
            'className' => ConsoleLog::class,
            'scopes' => ['queriesLog'],
        ],
    ],
```

### What happened

Duplicate logs are output when using $this->log or Log::info in Console Command with ConsoleLog class.

```sh
2021-08-06 15:17:51 Info: this log info hello
2021-08-06 15:17:51 Info: this log info hello
```

### What you expected to happen

This is probably because when the ConsoleLog class is used for logging, both the ‘stdout’ log setting and the ‘debug’ log setting are used for log output, resulting in duplicate log output.
If I use Log::drop(‘debug’) just before $this->log, the duplicate log is fixed.

```sh
2021-08-06 15:17:51 Info: this log info hello
```

**Comment by markstory** [comment]
> This is probably because when the ConsoleLog class is used for logging, both the ‘stdout’ log setting and the ‘debug’ log setting are used for log output, resulting in duplicate log output.

This is exactly what is happening. You have two loggers that receive the log, so you get two log messages output. If you don't want two log messages output, remove one of the loggers.

**Comment by shigemk2** [comment]
Is it recommended to use $io instead of $this->log if we want to output the log in Console Command?

**Comment by markstory** [comment]
It depends. If you want output to only go to stdout then using `$io` is the way to go. If however, you want output to go to file logs, or analog (or other loggers you have) then you should use `$this->log()`.

**Comment by shigemk2** [comment]
I'm not sure if this is the correct behavior, because the output of $this->log on Console Command is duplicated, but the output of $this->log on Controller is not.

**Comment by markstory** [comment]
It is correct. Commands run in a CLI environment which has stdout and stderr. A web server does not have the same output streams.
