### ISSUE TITLE
Set default value for allowMultipleNulls to TRUE

### ISSUE THREAD

**Issue by VARGA-Peter** [cakephp/cakephp#15734]
I am referring to this pull request: https://github.com/cakephp/cakephp/pull/15226

In 4.2 `allowMultipleNulls` has been re-introduced and I think it was a very good decision. Unfortunately I cannot find a proper way(1) how to set it for the whole project to `TRUE` without bothering with rules which aren't - **in this case** - the best solution - or do you have a very simple solution without functions and dozen lines of code?

It should be quite very simple to set `allowMultipleNulls` to `TRUE` for the whole project in one code of line. I think about something like this:

It could be pre-set in the `Datasources` section in `app_local.php` for the whole project. If it isn't set there so it defaults to `FALSE`. This wouldn't break any compatibility for any project but it would be perfect if multiple `NULL` values are valid in a unique index in the underlying database.

(1) For the moment I do `allowMultipleNulls => TRUE`  in line 39 in `cakephp/cakephp/src/ORM/Rule/IsUnique.php`  - I know, this is very stupid and equals to death penalty but for the moment - hoping you implement something fast - I have to live with it.

**Comment by kevinquinnyo** [comment]
One option would be to create your own `RulesChecker` class and override the `isUnique()` method like this:

```php
namespace App\Model;

class RulesChecker extends \Cake\ORM\RulesChecker
{
    public function isUnique(array $fields, $message = null): RuleInvoker
    {
        $options = is_array($message) ? $message : ['message' => $message];
        $options += ['allowMultipleNulls' => true];

        return parent::isUnique($fields, $options);
    }    
}
```
Then your own `AppTable` class and override the `RULES_CHECKER` const like this:

```php
namespace App\Model\Table;

class AppTable extends \Cake\ORM\Table;
{
    public const RULES_CHECKER = \App\Model\RulesChecker::class;
}
```

Then of course you do have to change all of your tables to extend your `AppTable` instead of cakephp's `Table` class...

Maybe someone more knowledgeable with the 4.x framework can chime in with a better solution than this as it is a bit heavy handed.

**Comment by VARGA-Peter** [comment]
@kevinquinnyo
Your code in comparison to my 1 line which works globally. I have only to read my internal to do list when I run composer once a month.

Exactly this is what I meant in my opening post with "this is not the best solution" .

**Comment by kevinquinnyo** [comment]
> @kevinquinnyo
> Your code in comparison to my 1 line which works globally. I have only to read my internal to do list when I run composer once a month.
> 
> Exactly this is what I meant in my opening post with "this is not the best solution" .

I assumed you were looking for a solution in the meantime that didn't involve modifying the vendor code

**Comment by markstory** [comment]
I think the solution @kevinquinnyo is a good one. I'm reluctant to add global configuration options when we already have ways to do what you're looking for. Another path forward is to subclass the IsUnique rule class and use that instead of `RulesChecker::isUnique()`

**Comment by VARGA-Peter** [comment]
> I think the solution @kevinquinnyo is a good one. I'm reluctant to add global configuration options when we already have ways to do what you're looking for. Another path forward is to subclass the IsUnique rule class and use that instead of `RulesChecker::isUnique()`

Hm, how can be 12+ lines of code better than 1 line? And, there are always several ways how to achieve it.

_My request/wish is clear:_
Add a very simple option to change `FALSE` to `TRUE` of a setting which is only needed for SQL Server prior 2008. It was now re-introduced again in 4.2 with `FALSE` so it has to remain like this in order not to brake the compatibility of existing projects.

Anyway, I don't understand why it was selected to default `FALSE` when all underlying database engines have exactly the opposite behaviour. But I don't have to understand everything.

Why should I bother with `Rules` when my project contains 60+ tables and I need it set to `TRUE`? As mentioned before I modify each time CakePHP was updated in the source even it's horrible practise.

**Comment by kevinquinnyo** [comment]
@markstory While there are certainly workarounds, and 4.x is obviously a major release, so BC changes are expected, I kind of understand the frustration here.  I am in the process of updating a fairly large application from cake 3.8 to 4.2, and we ran into this issue immediately.

IMO it's more intuitive that `null`'s would be ignored when you have something like `['manufacturer_id', 'model_number']`.  In a case like this the logic is "I want to ensure that model_number is unique for a manufacturer, but if the model_number doesn't exist or is not known right now, allow null.

> Another path forward is to subclass the IsUnique rule class and use that instead of RulesChecker::isUnique()

How would you advise doing this?  At first glance, there doesn't seem to be a way to drop in your own `IsUnique` class without subclassing `RulesChecker`, and in order to swap out the `RulesChecker`, subclass `Table`.  I could be missing something obvious though

**Comment by kevinquinnyo** [comment]
I should add that I also understand not wanting to add a global configuration option that probably immediately represents new technical debt for later releases.

**Comment by VARGA-Peter** [comment]
> I should add that I also understand not wanting to add a global configuration option that probably immediately represents new technical debt for later releases.

Really? For an option which should have been enabled by default as - I repeat myself - it does exactly the opposite of each underlying database engine?

I am already now curious how this will be solved and if I have to modify manually the next 5 years after each CakePHP update the setting in `cakephp/cakephp/src/ORM/Rule/IsUnique.php` :-)

**Comment by markstory** [comment]
> How would you advise doing this? At first glance, there doesn't seem to be a way to drop in your own IsUnique class without subclassing RulesChecker, and in order to swap out the RulesChecker, subclass Table. I could be missing something obvious though

```php
// Import your modified isunique rule
use App\Model\Rules\IsUnique;

// In a table's buildRules
$rules->add(new IsUnique(['field', 'other_field']), '_isUnique', ['message' => 'field must have a unique value']);
```

**Comment by kevinquinnyo** [comment]
> > How would you advise doing this? At first glance, there doesn't seem to be a way to drop in your own IsUnique class without subclassing RulesChecker, and in order to swap out the RulesChecker, subclass Table. I could be missing something obvious though
> 
> ```
> // Import your modified isunique rule
> use App\Model\Rules\IsUnique;
> 
> // In a table's buildRules
> $rules->add(new IsUnique(['field', 'other_field']), '_isUnique', ['message' => 'field must have a unique value']);
> ```

Right.  I was assuming you meant a way to do it without having to update existing rules in each table/behavior, etc

**Comment by VARGA-Peter** [comment]
Because I am only a human and before I forget I have the below code in `app_local.php` which checks each time the default value of `allowMultipleNulls`. I can live with the delay caused by the execution time.

If an update overrides my setting the project stops working and I get reminded. But I hope it becomes obsolete in one of the next updates anyway. A normal developer isn't running an update while the business hours and usually tests after an update if the site works properly so this should be ok.

When something changes in the internal structure so I have to investigate it because the check fails with an error message so I intentionally don't implement any error checking.

```
$voidIsUnique = new \Cake\ORM\Rule\IsUnique( [], [] );
$isUnique     = new ReflectionClass(\Cake\ORM\Rule\IsUnique::class);
$property     = $isUnique->getProperty("_options");
$property->setAccessible(TRUE);
if ( !$property->getValue($voidIsUnique) ["allowMultipleNulls"] ) {

    die('<span style="background-color: black; color: yellow; font-size: 36px;">' .
          'IsUnique::_options ["allowMultipleNulls"] is FALSE. Fix the source code!</span>');

}
$property->setAccessible(FALSE);
```

**Comment by inoas** [comment]
I think I was the one who originally added the support to ExistsIn and IsUnique because that is how vanilla SQL works on these constraint checks and at least for IsUnique should have been the default (instead of making it the default in 4.x it got removed). Should be the default in 5.x

**Comment by othercorey** [comment]
You can open a PR for 5.0 with the `5.0` branch.

**Comment by othercorey** [comment]
This is now the default in cake 5.
