### ISSUE TITLE
Wrong date&time format in deleteAll condition "where"

### ISSUE THREAD

**Issue by PatrickG** [cakephp/cakephp#15741]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.3
* Platform and Target: Ubunu Server, nginx 1.10.3, MySQL

### What you did
I have a similar problem like this: https://github.com/cakephp/cakephp/issues/15452 But I'm not using a join.

I'm fetching a model and use a datetime prop of that model to create a where condition for  a `deleteAll` call on that same table.

```
// somewhat like that:
$item = $table->find()->where(['id' => 'xyz']);
// when i var_dump $item, $item->prop is an instance of FrozenTime
$table->deleteAll(['prop >=' => $item->prop]);
```

`App.defaultTimezone` and `Datasources.default.timezone` are both UTC.
Also, it does work localy but on a server with the same system timezone (UTC) it does not work.

### What happened
I'm getting an MySQL error like:
`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '8/11/21, 4:15 PM' for column 'start_date' at row 1`

### What you expected to happen
No error.

**Comment by ndm2** [comment]
Try clearing the schema cache (`tmp/cache/model` if you're using file caching). And check `$table->query()->getTypeMap()->toArray()` to figure whether the `start_date` column is actually assigned a date/time-ish type.

**Comment by PatrickG** [comment]
Thanks for you reply, I already deleted all cache files.
```
Array
(
...
    [CalendarEvents__start_date] => datetime
    [CalendarEvents.start_date] => datetime
    [start_date] => datetime
    [CalendarEvents__end_date] => datetime
    [CalendarEvents.end_date] => datetime
    [end_date] => datetime
...
)
```

**Comment by dereuromark** [comment]
`'prop >=' => $item->prop`
Is that a datetime one?

Best to not use different code in your example, as reproducing is much harder this way
What is your actual code?

Looks like the localized string cast of that datetime object is not readable by the database in the end.

**Comment by PatrickG** [comment]
> 'prop >=' => $item->prop
Is that a datetime one?

Yes, that is `start_date`.

The actual code:
```php
$table->deleteAll([
    'CalendarEvent.parent_id'     => $event->id,
    'CalendarEvent.start_date >=' => $event->start_date,
]);
```

> Looks like the localized string cast of that datetime object is not readable by the database in the end.

Yea, should'nt it send an ISO 8601 formatted string?

**Comment by ndm2** [comment]
What's the deal with `CalendarEvent` vs `CalendarEvents`? (trailing `s`).

**Comment by PatrickG** [comment]
Oh my god, that is embarrassing 😅

CalendarEvent*s* works.
Thank you for your time^^

But why did it worked localy with CalendarEvent.start_date, hmmm.

**Comment by ndm2** [comment]
Maybe your local code schema cache has/had different names cached, the non-plural name doesn't follow the naming conventions, so I would assume that you've changed it at some point.
