### ISSUE TITLE
Change branch Master to Main

### ISSUE THREAD

**Issue by Coreusa** [cakephp/cakephp#15753]
The use of Master is "harmful and antiquated terms" and "no longer considered appropriate.".

CakePHP should follow suit. Use Main instead.

[Read more about why this is important](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)

**Comment by markstory** [comment]
I don't disagree with the reasons for switching to main, however I'm concerned that the switch will break userland installs that are pulling from `dev-master`. The change will also require some tooling/CI changes. Any chance you'd be interested in helping with those changes?

**Comment by garas** [comment]
I'm more in favor to avoid both `main` and `master` and use branches like `4.x` for main branch and never rename branches when releasing new major version.

With existing workflow, two renames happen: 
- `master -> 4.x` - existing clones pull possibly incompatible next major and may need switch back to renamed branch,
- `5.x -> master` - existing clones cannot pull anymore missing `5.x` branch, must switch to renamed branch.

Using `dev-4.x` would be also safer than `dev-master`.

Default branch can be always switched in GitHub settings.

**Comment by markstory** [comment]
Using version number branches is a good path forward as well. It would save a step when we promote major versions and avoid master/main moving to an incompatible release.

**Comment by othercorey** [comment]
Should we keep `N.next` branches or use literal versions like `4.3` and `5.1`?

**Comment by markstory** [comment]
I prefer the next as juggling the version numbers at the minor version was tedious in the past. It also had the drawback of closing all the open pull requests that are pointing at the minor when it gets deleted.

**Comment by othercorey** [comment]
> It also had the drawback of closing all the open pull requests that are pointing at the minor when it gets deleted.

That's true, I forgot about that.
