### ISSUE TITLE
Implementation of ARIA into the FormHelper.php

### ISSUE THREAD

**Issue by shadowx-jb** [cakephp/cakephp#15755]
Is it possible to implement the following code in FormHelper, please?

src/View/Helper/FormHelper.php

**public function control**

Line 1038:
```
    public function control(string $fieldName, array $options = []): string
    {
        $options += [
            'type' => null,
            'label' => null,
            'error' => null,
            'required' => null,
            'options' => null,
            'templates' => [],
            'templateVars' => [],
            'labelOptions' => true,
            'aria-label' => empty($options['placeholder']) ? $options['label'] : $options['placeholder'],
            'aria-required' => $options['required'] == true ? 'true' : null,
            'aria-invalid' => $this->isFieldError($fieldName) ? 'true' : null,
            'aria-describedby' => $this->isFieldError($fieldName) ? $fieldName . '-hint' : null,
        ];
```

**public function error**

Line 769:
```
        return $this->formatTemplate('error', [
            'content' => $error,
            'field' => $field,
        ]);
```

**protected $_defaultConfig**

Line 98:
`
'error' => '<div class="error-message" id="{{field}}-hint">{{content}}</div>',
`

This is support for the ARIA tag, which will make it easier for a blind user to work with forms. 

Thank you

**Comment by markstory** [comment]
Sounds like a good change to me. If you are able to you could get the process started by updating the helper, I'm happy to help fix the test failures that are certain to occur.

**Comment by shadowx-jb** [comment]
Thank You!
How do I get the right to push changes ?

**Comment by ADmad** [comment]
You need to open a pull request https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by shadowx-jb** [comment]
Thank You, and can i do pullreqest if the tests are not done yet? I can't handle the tests.

**Comment by markstory** [comment]
> Thank You, and can i do pullreqest if the tests are not done yet? I can't handle the tests.

Yes, please leave 'allow maintainers to edit' checked so that I can update your pull request with tests.

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/cakephp/pull/15761
