### ISSUE TITLE
RFC - Add prompting for undefined command options 

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#15782]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

When building command line tools you can end up with a complex collection of options that are hard to remember and use. When a subset of those options are required getting all of them specified can be tedious for the operator as they try/fail/read help/try again until they get a working command.

An alternative solution to this would be to allow commands to 'prompt' the operator for values if the value is undefined. An example of how this could defined is:

```php
$optionParser->addOption('color', [
   'required' => true,
   'prompt' => 'What is your favourite color?',
   'options' => ['red', 'blue', 'green'],
])
```

By providing a `prompt` string the `ConsoleOptionParser` can request option values from the operator before marking the option set as 'invalid'.  If a response to an option does not fit within the listed options an error could be printed and the question can be retried.

### Similar features:

While I wasn't able to find a similar feature in Symfony or Laravel, there are examples of this behavior in python:

* [Click prompting](https://click.palletsprojects.com/en/8.0.x/options/#option-prompting)

**Comment by othercorey** [comment]
Should we have options that *must* be user input such as passwords?

**Comment by markstory** [comment]
Can't that already be done by using `$io->question()`? You won't be able to have it show up in the help message though. Doing that _might_ be doable with a new option-parser type that is for 'required interactive questions' :thinking:

**Comment by othercorey** [comment]
It's probably not needed. I was thinking of postgres pg_dump as an example, but that always prompts so the option isn't required.

**Comment by markstory** [comment]
Closing as a pull request is open now.
