### ISSUE TITLE
WARNING: CORE\src\Database\Statement\MysqlStatement.php, line 39

### ISSUE THREAD

**Issue by zsfoto** [cakephp/cakephp#15814]
* CakePHP Version: The newest
* Platform and Target: WAMP, Php 7.3.5, MySQL 5.7.26

When in **$this->paginate** is **'limit' => n** and/or **'maxLimit' => n** where **n > 31** displays the following warning:
```
_Warning (2): PDOStatement::execute() [<a href='https://secure.php.net/pdostatement.execute'>pdostatement.execute</a>]:
Error reading result set's header [CORE\src\Database\Statement\MysqlStatement.php, line 39]_
```
My cakephp is the newest.
What is the problem?

**Comment by zsfoto** [comment]
I founded the next: When the
```
$this->paginate = [
            'contain' => ['... something ...'],
]

```
this problem is exists.

**Comment by markstory** [comment]
How can someone reproduce the problem you're having?

**Comment by othercorey** [comment]
@zsfoto Can you give us more information about the query?

**Comment by zsfoto** [comment]
The story is as follows. I installed cakephp. During installation, it stated that the composer was old. Nevertheless, I continued to work with him. Then it turned out that pagination could not run from record 32 without warning.
I updated the comoser. I reinstalled capephp and now I work that way. Now is good.
Maybe that was the reason. That's how I close my post.
