### ISSUE TITLE
Custom message for validation rule adding failed

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#15854]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest master

### What you did

```php
$limit = Configure::read('Conversations.limit');
		$validator->add('user_id', 'limit', [
			'rule' => ['validateLimitReached', $limit],
			'message' => ['valErrRecipientLimitReached {0}', $limit],
			'provider' => 'table',
		]);
```

### What happened
I am pretty sure this used to work in 3.x
But with 4.x now the error message is always just the default one ("input invalid").

### What you expected to happen
That the custom message is also displayed for users.

**Comment by ADmad** [comment]
Message translation didn't work in 3.x either. I had proposed implementing it but the idea wasn't accepted. IIRC the argument was that one can use the translation function when setting the message itself.

I have implemented the feature through custom validator in my i18n plugin.

**Comment by dereuromark** [comment]
I see
So if I hardcode it it would be fine, just the translation part is missing.

If there is no interest here in core, and a plugin exists, I can also close this then as works-for-us.
