### ISSUE TITLE
Hi Use CakePHP + Rector Update versión CakePHP ..?

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#15866]
Hello everyone, someone ever used this tool to change the version in CakePHP, it sounds interesting or to take into account within "bin/cake upgrade ..."

Tool and lib:
https://github.com/rectorphp/rector
Home: https://getrector.org/

* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

**Comment by othercorey** [comment]
This is the CakePHP upgrade project: 
https://github.com/cakephp/upgrade

There are some user-experience issues with rectorphp though.

**Comment by markstory** [comment]
The upgrade tool already leverages rector to do a bunch of upgrade related changes. Is there something that you were hoping to see but didn't from the existing implementation?

**Comment by EOM** [comment]
Hello, I have not just seen what is used in cakephp v4 and since it did not reach that version, I did not see it and how interesting the tool is, I wanted to comment to the community so that they take it into account.

Greetings thank you

PS: I'm going to see if I can implement it to upload from CakePHP 2.x to 4.x or rewrite everything or move everything to an API, I'll see, greetings

**Comment by EOM** [comment]
> La herramienta de actualización ya aprovecha a rector para realizar un montón de cambios relacionados con la actualización. ¿Hay algo que esperabas ver pero no lo hiciste de la implementación existente?

Hello, I have not just seen what is used in cakephp v4 and since it did not reach that version, I did not see it and how interesting the tool is, I wanted to comment to the community so that they take it into account.
Greetings thank you

PS: I'm going to see if I can implement it to upload from CakePHP 2.x to 4.x or rewrite everything or move everything to an API, I'll see, greetings
