### ISSUE TITLE
TypeError in CsrfProtectionMiddleware

### ISSUE THREAD

**Issue by smarek** [cakephp/cakephp#15868]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.8
* Platform and Target: nginx, php-fpm 7.4.23

### What you did
After update from 4.1.7, where issue with malformed/crafted cookies/form-params was manifested by NoticeException **Array to string conversion** on line 300 of vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php

In 4.2.8 it's manifested by TypeError **strlen() expects parameter 1 to be string, bool given** on line 281 of vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php

### What happened
Someone enumerating/bruteforcing endpoints crafted request and provided invalid values where CsrfProtectionMiddleware expected valid, previously framework-set, data.

stacktrace here:
```
#0 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(281): strlen()
#1 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(153): Cake\Http\Middleware\CsrfProtectionMiddleware->saltToken()
#2 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Runner.php(73): App\Middleware\CsrfUserProtectionMiddleware->process()
#3 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(126): Cake\Http\Runner->handle()
#4 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Runner.php(73): Cake\Error\Middleware\ErrorHandlerMiddleware->process()
#5 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Runner.php(73): App\Middleware\TrustProxyMiddleware->process()
#6 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Runner.php(58): Cake\Http\Runner->handle()
#7 /var/www/cakephp.app/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run()
#8 /var/www/cakephp.app/webroot/index.php(40): Cake\Http\Server->run()
#9 {main}
```

### What you expected to happen
Invalid value in cookie/form-params, should be detected and handled, instead of relying on php TypeError faults
Base64_Decode return signature is string|false, and for any kind of invalid value, this should be handled gracefuly, so the client (web user) is not permanently cut out from the app, just because he has invalid cookie data, that prevents him from being able to access the webapp

**Comment by markstory** [comment]
How can someone reproduce this problem? Is there a cookie value that would help trigger the error?

**Comment by markstory** [comment]
I'm guessing this is caused when the csrf cookie contains a string value, but that string is not a hexadecimal value, nor is it a base64 encoded value.

What are you expecting to happen when this situation arises. We cannot use the token as provided because it is invalid. If the request is not a GET we have no choice but to fail the form submission. On a GET we could renew the cookie with a valid value.

**Comment by smarek** [comment]
@markstory sorry for the delay, yes, proposed would work just fine. I mean POST/DELETE/PUT/PATCH with invalid CSRF token should not be accepted and should fail hard, as it already does. But on GET/HEAD/OPTIONS the cookie should be replaced with valid value, so it does not prevent the user from accessing the web/app in long-term. Thank you!
