### ISSUE TITLE
Request Ajax does not identify whilst using Fetch API

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#15874]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.8
* Platform and Target: Apache2, PHP 8, Ubuntu 20.04

### What you did

**Frontend code:**
```
fetch('/participants/index')
  .then(function(jsonResponse) {
    participants.forEach(function(participant) {
		// Did stuff.
  	});
  });
}
```

**Backend Code:**
```
if ($this->request->is('ajax')) {
 // Stuff
 return $response->withStringBody($jsonStringOfParticipants)
}
// Continues the code
```

### What happened
When I perform an Ajax using `XMLHttpResponse` it gets identified by `$this->request->is('ajax')` but when I use Fetch API, it does not. It continues the code whereas it should return the json. Works fine when I switched to XMLHttpRequest or used $.ajax of jQuery.

### What you expected to happen
If would recognize the request via Fetch API as Ajax.?

**Comment by ADmad** [comment]
A request made using `Fetch` API doesn't use `XMLHttpRequest` so it's not an AJAX request per se.

You should set the `Accept` header to `application/json` and use `$this->request->is('json')` to decide whether to return a JSON response.

**Comment by markstory** [comment]
The `ajax` detector operates by looking at the `X-Requested-With` header, which fetch() doesn't use. You could include this header in your fetch() requests or use a content type like ADmad suggested.
