### ISSUE TITLE
Code contribution on 4.3 disapeared

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#15894]
First, congratulations on the coming 4.3!

I was wondering why the commits I submitted for the 4.3 release do not appear in the git logs under my account. For example here:
https://github.com/cakephp/cakephp/blob/8acbbbff8cd9ab13a7b82c07152fda9e7ad395fe/tests/TestCase/TestSuite/Fixture/SchemaCleanerTest.php#L24
and generally that whole [commit](https://github.com/cakephp/cakephp/commit/fab8cc91b19c3f5bfacc4662a421b8d2365a7649).
Any chances to get my credits? Just to show my grand children one day...

**Comment by othercorey** [comment]
How has it disappeared? I see it in 4.next and the commit you linked loads.

I don't think mark listed contributors in the RC1 release, but when he does I'm sure it will be there.

**Comment by othercorey** [comment]
You might be looking in `4.x` branch. `4.next` will merge into `4.x` for the stable release.

**Comment by pabloelcolombiano** [comment]
Great, thanks for the input, I feel... released!

**Comment by markstory** [comment]
> I don't think mark listed contributors in the RC1 release, but when he does I'm sure it will be there.

Oops. I forgot to include the contributor list. I'll get that added in.
