### ISSUE TITLE
[4.3 RC1] - New Testing system requires test-datasource for all defined datasources

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#15895]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: https://github.com/cakephp/cakephp/commit/a81efac0ea39ba42501a7f872dfc20dfda255251
* Platform and Target: Apache, MySQL 5.7, PHP 8.0

### What you did
Updated my local environment to the current 4.3 RC1 and tried to adjust to the new fixture testing system.

### What happened
After doing pretty much everything defined in https://book.cakephp.org/4.next/en/appendices/fixture-upgrade.html I got the following error message.

```
Cannot create alias of "test_jira" as it does not exist.
```

Well, till that point my additional datasource `jira` didn't need an extra test datasource.
But it seems like this is now required according to https://github.com/cakephp/cakephp/blob/4.next/src/TestSuite/ConnectionHelper.php#L42

**Comment by othercorey** [comment]
Can you give more information about this connection? Is `jira` configured somewhere? That error suggests you have `test_jira` configured somewhere.

**Comment by LordSimal** [comment]
Till that moment the string `test_jira` was never present in my whole setup.
In this screenshot of the stacktrace I have the extra datasource `test_jira` now disabled so you can see how the error can be reproduced.

![image](https://user-images.githubusercontent.com/9105243/133203537-816db9fb-e88b-451d-9ab2-e4fa8fb2cfc0.png)

**Comment by othercorey** [comment]
This is caused by a change to `ConnectionManager::alias()`. However, if your test code tried to `get()` the `jira` connection, it should a `MissingDatasourceConfigException` because `test_jira` doesn't exist. 

Does your test code use `jira`? It seems like `alias()` was hiding this issue where unused connections were aliased.

**Comment by LordSimal** [comment]
Actually I just realised, that I didn't even need that datasource anymore because I removed that code which used that connection 😅 
So the error seems to be happening when a datasource is present even when it is not used.

**Comment by othercorey** [comment]
The test/fixture initialization maps **all** connections to a `test_` prefix so test fixtures didn't have to redefine what connection they used.

This was implemented in a buggy way which hid the missing connections, but we can support aliasing connections that aren't setup yet.

**Comment by LordSimal** [comment]
I guess you mean `ConnectionManager::alias('test_debug_kit', 'debug_kit');`?

**Comment by othercorey** [comment]
Yes.

**Comment by LordSimal** [comment]
I can confirm with the lastet 4.next version my error from above is now gone. I don't have to define a `test_jira` datasource anymore
