### ISSUE TITLE
RFC: Add method to detect if the same Command is already running 

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#15905]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x
* Platform and Target: Windows and Linux

When building custom command line you can face situations where is desirable to avoid multiple instances of the same Command running at the same time. 

Example: a routine to consume a diary collection of data from a web service.

### How I implemented :

I have used this "old" lib: https://github.com/christian-vigh-phpclasses/ProcessList and created this Trait:

```php
<?php

namespace App\Traits;
use Cake\Utility\Inflector;
use Cake\Collection\Collection;

trait CommandUtilTrait {
    
	public function getOthersRunning() : Collection {
	
		$process_name = Inflector::underscore(str_ireplace('Command','',(new \ReflectionClass($this))->getShortName()));
	
		$collection = (new Collection(new \ProcessList()))->filter(
			fn($p) => $p->Command == 'php' && in_array($process_name,$p->Argv) && $p->ProcessId != getmypid()
		);
		return $collection;
	}
}
```

After that, inside my Custom Command:

```php
<?php

namespace App\Command;
require_once ROOT . DS . "vendor" . DS . "process-list" . DS . "autoload.php"; 
use Cake\Console\Arguments;
use Cake\Console\Command;
use Cake\Console\ConsoleIo;
use App\Traits\CommandUtilTrait;

class ConsumoAvisoCommand extends Command {

	use CommandUtilTrait;

        public function execute(Arguments $args, ConsoleIo $io){

		$process = $this->getOthersRunning()->first();
		if($process ){
			echo PHP_EOL;
			echo "Is there another Command (pid: {$process->ProcessId}) running by {$process->User}";
			echo PHP_EOL;
			exit();
		}
                $io->out('Running...');
	        $io->out('End !');
        }
}
```

### What happened

The message was shown when I tried to run another "instance" of same Command.

### What I expect

A native CakePHP implementation to detect if the same Command is already running

**Comment by othercorey** [comment]
This is limited to commands running in the same php process, right?

**Comment by celsowm** [comment]
> 
> 
> This is limited to commands running in the same php process, right?

Not exactly in my case here: we needed a way to avoid two or more users (even cron/task-scheduler) to run the same "task" (command) at the same time

So, they have differents pids

`$p->ProcessId != getmypid()`

**Comment by markstory** [comment]
Getting a process list from windows is going to be the tricky part. The library you linked to has addition COM dependencies that are required, which make is unlikely that we'd be able to support behaviour that uses a process list from the host.

I've seen this implemented in other ways with mutex values stored in a cache. If the key is present the check fails. The key can be set with a short expiry time to prevent an accidental death from locking the system going forward. Would something like that work for your usage?

**Comment by celsowm** [comment]
> Getting a process list from windows is going to be the tricky part. The library you linked to has addition COM dependencies that are required, which make is unlikely that we'd be able to support behaviour that uses a process list from the host.
> 
> I've seen this implemented in other ways with mutex values stored in a cache. If the key is present the check fails. The key can be set with a short expiry time to prevent an accidental death from locking the system going forward. Would something like that work for your usage?

Of course! Would it be very useful too!!! #ILoveCakePHP

**Comment by LordSimal** [comment]
I personally would say that this requirement is more suited for a queue system rather than commands.

**Comment by markstory** [comment]
> I personally would say that this requirement is more suited for a queue system rather than commands.

How would a queue message producer know if the previously created job was complete or is still in progress? You'd need a persistent storage location to hold the progress and result of each job. By using a cache key, we would get that persistent storage without requiring users to create specific schema.

**Comment by Phally** [comment]
We're doing it by opening a socket and listening on a port on localhost instead while something is running. This also has the benefit that you can communicate with the running process. However, you'd have to run everything asynchronous so you can accept connections while it's busy.

**Comment by othercorey** [comment]
Is this expected to work only in a local environment or in a distributed/cloud environment?

**Comment by markstory** [comment]
> Is this expected to work only in a local environment or in a distributed/cloud environment?

Yes, I think having a 'only works on a single machine' caveat require additional documentation and will only spawn many bugs down the road.

Using a cache key gives you the potential of having the mutex work across multiple hosts if you use memcache or redis as your cache. We can reinforce the idea of choosing a cache backend based on your requirements with less toil.
