### ISSUE TITLE
TransactionStrategy and primary keys

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#15903]
I have played a bit with the TransactionStrategy offered by Cake 4.3, which is a great thing. I have a concern though, since auto-increment values are not reseted before each test: how can one create belongsToMany test fixtures? The pivot table will need to have fixed foreign keys, which are most likely primary keys, so we are back to primary keys being set statically.
I have created a test https://github.com/vierge-noire/cakephp-fixture-factories/blob/852f02839547b37ff31a4e2cf2e56c1d42724ea1/tests/TestCase/StaticFixturesTest.php#L59 on the fixture factories plugin, that illustrates that. I am a bit concerned, but I might oversee something...

**Comment by othercorey** [comment]
This is a known limitation of TransactionStrategy. Fixtures would need to have non-static foreign keys.

**Comment by markstory** [comment]
Yeah static fixtures can't work with transaction based fixtures as rollbacks don't revert sequence advances. Instead fixtures need to be created dynamically with factories or similar functionality. You also have to constrain assertions on ids to the objects you created as sequence values will shift over time.

**Comment by pabloelcolombiano** [comment]
O.K. thanks for the explanation.
