### ISSUE TITLE
Test strategy enhancements

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#15956]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0-RC1

### What you did
Persisted data in a test that did not have test fixtures. 

### What happened
Since there are no fixtures, the test wrapping transaction is not activated and the test DB is not cleaned.

First congratulation on the new test cycle with "strategies", this is working really well and looks really elegant.

Generally, I am implementing the trigger-based strategy that the [test suite light](https://github.com/vierge-noire/cakephp-test-suite-light/issues/49) will be using, and having a tiny issue with the current implementation of the test cycle. I would propose to make the two following enhancements:

1. In `TestCase::setupFixtures()`, I would comment out the return on empty `$fixtureNames`. Since fixtures are not required for managing the schema, it is well possible to create test fixtures with factories and still want to take advantage of the transaction for the cleanup. If you still want to skip the "transactioning" on empty static test fixtures, it would be handier to move that check in the `TransactionStrategy::setUp`, instead of the `TestCase::setupFixtures()`. 

2. `FixtureStrategyInterface::setupTest()` could take  `TestCase $test` as argument, instead of `array $fixtureNames`. This enables to do much more elaborate work in some custom strategy, and on the TransactionStrategy side, it is then still possible to get the fixtures from the test with `$test->getFixtures()`.

3. If you agree on point 2, we could also then have `FixtureStrategyInterface::teardownTest(TestCase $test)`. 

I am open to propose a PR, just wanted to discuss this with you first.

**Comment by markstory** [comment]
> In TestCase::setupFixtures(), I would comment out the return on empty $fixtureNames. Since fixtures are not required for managing the schema, it is well possible to create test fixtures with factories and still want to take advantage of the transaction for the cleanup. 

We do this early return to avoid the runtime cost of starting/stopping transactions doing truncation/transactions on test methods that aren't using the database.

> FixtureStrategyInterface::setupTest() could take TestCase $test as argument, instead of array $fixtureNames. This enables to do much more elaborate work in some custom strategy, and on the TransactionStrategy side, it is then still possible to get the fixtures from the test with $test->getFixtures().

This seems reasonable to me. I have some concerns that the TestCase interface is really wide and the amount of theoretical compatibility breaks that presents. Perhaps @othercorey can weigh in on this?

**Comment by othercorey** [comment]
The idea was to keep strategies separate concepts from TestCase itself. We pass the fixtures the strategy should care about instead of making them go find it.

You could pass `$this` to the strategy constructor for custom implementations.

**Comment by pabloelcolombiano** [comment]
Passing the test in the constructor is a reasonable solution. For me it's fine to leave the signature of the interface as it is. This closes points 2 and 3.

Concerning point 1, I understand that the transaction should run only if the test has fixtures. However, I propose to make that return in the TruncationStrategy, rather than in the TestCase. This makes the strategy approach more prone to extension. I'll send a small PR for that.

**Comment by othercorey** [comment]
If you want a generic hook to run for each test, why not add an extension?

**Comment by pabloelcolombiano** [comment]
If I add an extension that handles the cleaning of the database, I need to create a DoNothingStrategy strategy that inhibits the default fixture strategy (TruncateStrategy). And in each of his DB interacting TestCases, the developer must specify to use that DoNothingStrategy.

The solution you propose is to have strategy A (applied by default) + strategy B, and since I do not want strategy A, explicitly remove strategy A. What I propose is the possibility so replace strategy A by strategy B.

In the present implementation, the TestCase interacts with the fixtures, by counting them and skipping the strategy if empty. This excludes the replacement of a strategy by another. I believe a smoother approach would be to let the strategy decide by itself, whether it is going to perform the cleanup or not.

In addition, there will be tests where no fixtures are loaded, but still the database is involved. Example: testCreateUser().
I think it would be good to create a trait that specifies that this test case needs to be cleaned up, although it has no static test fixtures.
Something like `use TruncateFixturesAfterTest` for the truncation strategy, or `use RollbackTransactionAfterTest` for the transaction strategy. Like this, the strategy would apply either if fixtures are declared, or if the test has the provided trait.

Example:
```
trait RollbackTransactionAfterTest
{
    public $rollbackTransactionAfterTest = true;

    protected function getFixtureStrategy(): FixtureStrategyInterface
    {
        return new TransactionStrategy();
    }
}
``` 
And in the `TransactionStrategy`, assuming we do pass the test as argument:

```
    public function setupTest(TestCase $test): void
    {
       if ($test->rollbackTransactionAfterTest !== true) {
         return;
       }
    
        // And the rest...
    }
```

What do you think?

This makes if very easy for the developer to declare in one `use  ...` the strategy required, and the fact that the database needs to be cleaned-up.

**Comment by othercorey** [comment]
So, we started with a complex solution and reduced it down to something simple. We also discussed adding more to the interface, but decided it wasn't worth the cost.

However, I'm not directly opposed to letting the strategy handle optimizing no fixtures -- but it seems unnecessary.

I think it's unnecessary because fixture strategies are meant for fixtures. It sounds like what you want is a trait with helpers to clean up user-specific db testing in tearDown(). As you said, the user can manipulating the database without fixtures -- but that seems unrelated to fixtures.

Again, it sounds like you just need code to run in the tearDown() for all tests.

**Comment by pabloelcolombiano** [comment]
My problem are these three lines [here](https://github.com/cakephp/cakephp/blob/8acbbbff8cd9ab13a7b82c07152fda9e7ad395fe/src/TestSuite/TestCase.php#L264).

Because of this return, you oblige the developer to create a second hook if they want to clean up the database, although the test does not have test fixtures.

And because you apply by default the truncate strategy if fixtures are declared, you oblige the developer to overwrite the truncate strategy with one doing nothing, because there might be fixtures in the tests.

You see my point? These three lines could be conveniently placed in the strategies.
The rest are just proposed solutions, you can ignore them ;-)

**Comment by pabloelcolombiano** [comment]
Just to make it clearer:
* our developers do use fixtures, but not all of their DB-interacting TestCases use fixtures.
* they cannot use the transaction solution because it forces primary keys to be populated randomly, which is incompatible with belongs to many / has many relations. Therefore, we use a trigger-based solution to clean up the DB before each tests.
* the truncate solution will truncate only the tables of the declared fixtures. This is not enough, because we might load fixtures for table A and B, and have table C modified during the test. Table C will thus be not cleaned.

The strategy does two things: insert data with fixtures, and cleanup the DB. This is exactly what I am developing. I want to insert fixtures when some are declared, and cleanup the test DB, wether fixtures are declared or not (this is the `testCreateUser()` I was talking about, it has no fixtures declared, how do we clean it up with transaction or truncation strategy if the test case has no fixtures?).

**Comment by othercorey** [comment]
> how do we clean it up with transaction or truncation strategy if the test case has no fixtures?).

We would drop or clear the table in tearDown() for test-specific database changes.

If we allow "fixture" strategies to support performing arbitrary work, then we can't really maintain it as a fixture strategy. We would need a different solution, I think.

**Comment by pabloelcolombiano** [comment]
This is a solution indeed. It is not very handy though, because if creating a user in the background creates a profile, some logs, later in an additional feature some emails in the queue, and another feature later creates some more tables, this produces quite some maintenance. While the [trigger-based approach](https://github.com/vierge-noire/cakephp-test-suite-light) handles that automatically.

But I understand that you want to keep the strategy concept to static test fixtures only. In that case, our team will need to migrate all their tests built with static fixtures to fixture factories, which will make 4.3 a very heavy change.

I have sent a PR with the only fix required for having the strategy, IMO, a powerful and moreover extendable solution for managing test fixtures.
The modification proposes to keep all fixture related logic outside the TestCase, which is in line with your approach, I guess.

**Comment by othercorey** [comment]
> But I understand that you want to keep the strategy concept to static test fixtures only. In that case, our team will need to migrate all their tests built with static fixtures to fixture factories, which will make 4.3 a very heavy change.

Can you explain what changed between 4.2 and 4.3 where your non-fixture tests need this change? I understand your concept, but I think I'm missing the real-world fix that is your motivation.

**Comment by pabloelcolombiano** [comment]
We are using Cake 4.2, 80% of our tests rely on static test fixtures, 20% on fixture factories, goal is to get rid one day of the static fixtures, but this is a long way. The tests get cleaned with the trigger-based approach. We ignore Cake's legacy fixture-based table truncation. 

Now migrating to Cake 4.3, the `TestCase::setUp()` calls `TestCase::setupFixtures()`, which itself calls `TestCase::fixtureStrategy->setupTest()`. Right now I cannot overwrite the fixture strategy for the tests without static fixtures, and I cannot "deactivate" the default FixtureStrategy.

**Comment by othercorey** [comment]
> Right now I cannot overwrite the fixture strategy for the tests without static fixtures, and I cannot "deactivate" the default FixtureStrategy.

What prevents you from doing that?

**Comment by pabloelcolombiano** [comment]
This explained at multiple places above, here for example:
> If I add an extension that handles the cleaning of the database, I need to create a DoNothingStrategy strategy that inhibits the default fixture strategy (TruncateStrategy). And in each of his DB interacting tests, the developer must specify to use that DoNothingStrategy.

It is technically possible, but ugly.

Or how would you do it?

**Comment by markstory** [comment]
> Concerning point 1, I understand that the transaction should run only if the test has fixtures. However, I propose to make that return in the TruncationStrategy, rather than in the TestCase. This makes the strategy approach more prone to extension. I'll send a small PR for that.

I agree, that moving the early return when fixtures are empty would help make the strategy interface more extensible and let custom strategies clear the database even if there are no static fixtures. Would that work for your use case too?

**Comment by othercorey** [comment]
> This explained at multiple places above, here for example:
> 
> > If I add an extension that handles the cleaning of the database, I need to create a DoNothingStrategy strategy that inhibits the default fixture strategy (TruncateStrategy). And in each of his DB interacting tests, the developer must specify to use that DoNothingStrategy.
> 
> It is technically possible, but ugly.
> 
> Or how would you do it?

This seems like the concept of strategies to me. I don't understand your objections especially with your custom setup.

**Comment by pabloelcolombiano** [comment]
The difficulty here is that the concept of strategies handles two completely different tasks, namely populating the test DB and cleaning up the test DB, in different manners.

**The TruncateStrategy:**
_SetUp_: inject entities in the test database with test fixtures
_TearDown_: truncate the tables that had test fixtures involved in tearDown. Not all dirty tables will be cleanup.

**The TransactionStrategy:**
_SetUp_: inject entities in the test database with test fixtures and start a transaction if test fixtures were found
_TearDown_: rollback the transaction if static test fixtures were involved. All dirty tables will be cleanup, but auto increment is not reset.

As you see, the two strategies produce different results, with their advantages and drawbacks. Transaction is faster than truncation, and cleans up all tables, but the auto increment is not reset. There is no standard that says a strategy will do this.

**The [TriggerStrategy](https://github.com/vierge-noire/cakephp-test-suite-light/blob/%2349-cake-4.3-compatibility/src/Fixture/TriggerStrategy.php#L39):**
_SetUp_: truncate the non-empty tables in the DB and inject entities in the test database with test fixtures
_TearDown_: do nothing

The asset of this approach is that all and only dirty tables get truncated, even if no test fixtures were loaded. Another advantage is that the test DB is not emptied after the test, which makes the test driven development easier, as the developer may query the test database.

The trigger strategy follows, I believe, the concept of fixture strategies. It only needs to be given a chance to act, even for TestCases with no static test fixtures.

**Comment by markstory** [comment]
> Truncation Strategy ... 
> TearDown: truncate the tables that had test fixtures involved in tearDown. Not all dirty tables will be cleanup.

I wanted to give some context on this, as it was an intentional decision. My thinking was that the fixture system shouldn't assume all tables in a database belong to it and truncate them all. Instead we require developers to include static fixtures (with no records) to flag them as safe for the fixture system to manage.

> It only needs to be given a chance to act, even for TestCases with no static test fixtures.

Isn't this what the changes #15962 would do? If so I think we can move the discussion of the changes that should be made there.

**Comment by pabloelcolombiano** [comment]
This is all we needed, thanks a lot @markstory and @othercorey !
