### ISSUE TITLE
Is TestCase::loadFixtures() deprecated in Cake 4.3?

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#15950]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0-RC1

### What you did
Installed CakePHP 4.3.0-RC1
Updated phpunit.xml accordingly
I have a test calling `$this->loadFixtures('Countries');`

### What happened
The TestCase::loadFixtures() relies on the legacy FixtureManager, which I do not use now and which is marked as deprecated.
Therefore, my test will fail.

The method should be either 1. marked as deprecated, or 2. updated with the FixtureHelper.
Since `$autoFixtures` is marked as deprecated, we probably want to take the first solution.
The second solution needs to ensure that it remains transaction compatible.

**Comment by othercorey** [comment]
We can mark loadFixtures() deprecated.
