### ISSUE TITLE
marshal to DateTimeImmutable keeps time \Cake\Database\Type\DataType

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#15976]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.9

fix:
$date = $date->setTime(0, 0, 0); // for DateTimeImmutable

file: \Cake\Database\Type\DateType
```
public function marshal($value): ?DateTimeInterface
    {
        $date = parent::marshal($value);
        if ($date && !$date instanceof I18nDateTimeInterface) {
            // Clear time manually when I18n types aren't available and raw DateTime used
            /** @psalm-var \DateTime|\DateTimeImmutable $date */
            $date->setTime(0, 0, 0);
        }

        return $date;
    }
```

**Comment by markstory** [comment]
> file: \Cake\Database\Type\DataType

This isn't a file in the Cake project, did you mean another file?

How can someone reproduce the problem that you're running into?

**Comment by markusramsak** [comment]
typo: \Cake\Database\Type\DataType ->  \Cake\Database\Type\DateType

**Comment by othercorey** [comment]
@markusramsak Do use actually DateTime/DateTimeImmutable instead of I18n? I am curious since this is a rare feature.

**Comment by markusramsak** [comment]
No but I assigned (accidently) a FrozenTime to a FrozenDate column and why cake rules relied on FrozenDate for a business rule and it failed because the FrozenTime was not converted to FrozenDate. With MutableDate (Cake->Date-Class) it worked because the assignment above: $date->setTime(0, 0, 0); works -> so my business rules have a FrozenTime but with time set to 0. But with FrozenDate it fails because setTime(...) is not assigned to $date again.
