### ISSUE TITLE
beforeDelete/afterDelete on belongToMany association generates entity with incorrect type

### ISSUE THREAD

**Issue by kojot1234** [cakephp/cakephp#15977]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.9

### What you did
Removing associated data via patchEntity, beforeDelete/afterDelete on the relationship contains incorrect Entity type

TopicsController.php
```
// $data['groupings']['_ids'] = [];

$topic = $this->Topics->patchEntity($topic, $data, ['associated'=>['Groupings']]);
$this->Topics->save($topic, ['associated'=>['Groupings']])
```

TopicsTable.php
```
$this->belongsToMany('Groupings', [
  'foreignKey' => 'topic_id',
  'targetForeignKey' => 'group_id',
  'through' => 'GroupTopics'
]);
```

GroupTopics.php
```
public function afterDelete(EventInterface $event, EntityInterface $entity, ArrayObject $options)
{
   dd($entity);

  // expecting $entity of type App\Model\Entity\GroupTopic

/*
  App\Model\Entity\Grouping {#544
  #_accessible: array:18 
  #_fields: array:3 [
    "topic_id" => 18
    "group_id" => 7
    "id" => 9
  ]
  #_registryAlias: "Groupings"
  topic_id: 18
  group_id: 7
  id: 9
  [repository]: "Groupings"
*/
}
```

### What happened
before/after delete function contain an entity with wrong type but with correct data.

### What you expected to happen
entity type should be `App\Model\Entity\GroupTopic` not `App\Model\Entity\Grouping`

**Comment by markstory** [comment]
Changing which entity is passed to the delete callbacks could break existing applications. This kind of change would need to be done in a minor release where we could document the behavior change.

edit: clarify my hasty response.

**Comment by markstory** [comment]
When you call `$this->Topics->save()` are the junction entities you're passing in of the correct type? Or is the ORM fetching the incorrect entities inside the BelongsToMany association?

**Comment by kojot1234** [comment]
When saving it's using the standard `relationship._ids` form helper to save Groupings entities. In this case yes, the _joinData on belongsToMany relationship is of correct entity type.

In case of removal the "original" attribute on the topic entity right after patching does contain the correct entity in _joinData, if that's what you are asking by junction entitles.

```
App\Model\Entity\Topic Object
(
[id] => 18
...
[[original]] => Array
        (
            [groupings] => Array
                (
                    [0] => App\Model\Entity\Grouping Object
                        (
                            [id] => 7
                           ...
                            [_joinData] => App\Model\Entity\GroupTopic Object
                                (
                                    [id] => 8
                                    [group_id] => 7
                                    [topic_id] => 18
```

I believe it's the later, when deleting BelongsToMany fetches correct data however applies incorrect entity type to that data.
