### ISSUE TITLE
RFC - Action passed args: add support for other primitive types like int, float, bool ...

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#15992]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.9

### What i did
Tried to type the `$id` passed arg to an action as `int`:
```php
// my controller view action
public function view(int $id)
{
    // logic
}
```

### What happened
**InvalidArgumentException** thrown from `CORE/src/Controller/ControllerFactory.php:140`:
```
Could not resolve action argument id. It has no definition in the container, no passed parameter, and no default value.
InvalidArgumentException
```

### What i expected to happen
The framework support the primitive type `int` for the `$id` passed arg !

-> It's mentioned in a comment that the framework support only string(https://github.com/cakephp/cakephp/blob/4.x/src/Controller/ControllerFactory.php#L122):
>   // Primitive types are passed args as they can't be looked up in the container.
     // We only handle strings currently.

My question: is there a particular reason to support only the **string** type for the passed action args ?

IF there isn't, i can create a PR to add support for other primitive types like int, float, bool ...

Thanks

**Comment by ADmad** [comment]
Support for other primitive types has been implemented as will be available in 4.3.0 https://github.com/cakephp/cakephp/pull/15984.
