### ISSUE TITLE
dependent true in hasMany Association with TreeBehavior not deleting associations on children nodes

### ISSUE THREAD

**Issue by infoliv** [cakephp/cakephp#16019]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.2.9.
* Platform and Target: Apache2, PHP7.4.24.

### What you did
I have a CategoriesTable using TreeBehavior and hasMany Articles :
```
class CategoriesTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->addBehavior('Tree');
        $this->belongsTo('Categories');
        $this->hasMany('Articles', [
            'dependent' => true
        ]);
    }
 }
```

### What happened
When I delete a category "C" that contains articles, the articles are correctly deleted as I have set dependent on true. However, if I delete the parent of category "C", articles in "C" are not deleted any more.

### What you expected to happen
I expected that it would work like on Cakephp2, dependent on true made it possible to automatically delete associations (i.e Articles) both on node concerned or its sub-nodes.

**Comment by othercorey** [comment]
> However, if I delete the parent of category "C", articles in "C" are not deleted any more.

What do you mean by "parent of Category C"?

**Comment by markstory** [comment]
You also need to set `cascadeCallbacks` to `true` on your associations. Cake 3+ requires that setting to delete associated records individually. When not enabled the ORM uses more efficient bulk delete queries.

**Comment by infoliv** [comment]
Even when I set `cascadeCallbacks` to `true` Articles in the sub-caregories of the category I delete are not deleted...

**Comment by ndm2** [comment]
Some more insight as far as I understood it: https://stackoverflow.com/a/69494133/1392379

**Comment by ADmad** [comment]
The TreeBehavior uses a single delete query to delete all child nodes. Since it doesn't fetch and delete entities of the child nodes, no callbacks are triggered.

**Comment by othercorey** [comment]
Is this going to stay as designed?

**Comment by ADmad** [comment]
Ideally it should have an option to fetch the sub tree records and delete using entities so that the callbacks for associated records can be run. 

Need someone with the time and motivation to implement it :)

**Comment by infoliv** [comment]
(Hey GitHub, please remove the stale label)

**Comment by othercorey** [comment]
4.4 will have new cascadeCallback option
