### ISSUE TITLE
Use of 'self' and 'parent' callables being deprecated

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16017]
Using context-specific callables is being deprecated in 8.2.

https://wiki.php.net/rfc/deprecate_partially_supported_callables

```
['self', '_filter']
```

https://github.com/cakephp/cakephp/blob/4.next/src/Utility/Hash.php#L652-L660

**Comment by ADmad** [comment]
We could use the class name instead of `self` in 4.next?

**Comment by othercorey** [comment]
> We could use the class name instead of `self` in 4.next?

Should work. Need to confirm a unit tests runs this.
