### ISSUE TITLE
Theme overrides Plugin element file

### ISSUE THREAD

**Issue by lamasgergo** [cakephp/cakephp#16024]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: x

### What you did
I have a theme, it contains an element (with irrelevant content) with same name of a loaded Plugin's element name.

For example i have a Downloads plugin with an element on this path:
plugin/Downloads/templates/Admin/Element/form.php

I have set a theme in my application for example "MyTheme" and this theme contains an element with same name.
plugin/MyTheme/element/form.php

### What happened
MyTheme plugin's element form.php overrides the Download plugin form.php.
Because the template file load path look like this:

1. plugins/MyTheme/templates/plugin/Download
2. plugins/MyTheme/templates **<- wrong path**
3. templates/plugin/Download
4. plugins/Download/templates
5. templates/vendor/cakephp/templates

### What you expected to happen
Always try to find the plugin template files in plugin directories first. After try to find in another places.

The good order should be:
1. plugins/MyTheme/templates/plugin/Download
2. templates/plugin/Download
3. plugins/Download/templates
4. plugins/MyTheme/templates
5. templates/vendor/cakephp/templates

Example solution
Change in vendor/cakephp/cakephp/src/View/View.php @1570

```
 if (!empty($this->theme)) {
    $themePaths[] = Plugin::templatePath(Inflector::camelize($this->theme));

    if ($plugin) {
        for ($i = 0, $count = count($themePaths); $i < $count; $i++) {
            $pluginPaths[] =$themePaths[$i]
                . static::PLUGIN_TEMPLATE_FOLDER
                . DIRECTORY_SEPARATOR
                . $plugin
                . DIRECTORY_SEPARATOR;
        }
    }
}
```

```
$paths = array_merge(
    $pluginPaths,
    $themePaths,
    $templatePaths,
    App::core('templates')
);
```

So first of all fill up the $pluginsPath correctly, after that cahnge the loading order.

What do you think?

**Comment by markstory** [comment]
I'm reluctant to have theme paths *after* the plugin path as themes are supposed to be able to override plugin templates and changing that will likely impact existing theme use cases. Are you not able to move the top level template that is causing this problem?

**Comment by jamisonbryant** [comment]
What if it was made possible to specify the order in which the paths were searched, like in a config file? Individual applications could change the order as they saw fit, of course with a default order pre-configured. 

The easy solution to the problem here is most likely what Mark suggested but this would be an interesting feature for more complex cases where changing a template file in a path where there's a load order problem is not an option.

**Comment by markstory** [comment]
> What if it was made possible to specify the order in which the paths were searched, like in a config file? Individual applications could change the order as they saw fit, of course with a default order pre-configured.

Isn't that something one could do in their `View` class? If a custom path solution is needed `View::_paths()` can be implemented in application logic to do the required order.

**Comment by lamasgergo** [comment]
First of all @markstory thanks, we have override the View::_paths in the AppView, so at this point we have solved the problem.
But i don't think this is the best coice, thats why let think together, to help others and protect the code from core overrides :)

I totally understand that the theme overrides the plugin files, it is the best feature ever, we are using it every day, but now we have ran into this special case. 
The theme not only a "theme", it is a "plugin" too (with lot of functionality, own forms, list items etc..).
If the programmer do not knows the Download plugin (in this case) whole used element names, he will run into this problem easily.
And it is hard to debug, becuse there will be no error, only another form will appear in the Download plugin :)

It is interesting because only the element and cell (cell has own setTheme so you can change in the view file before you echo it ) files are conflicting... 

When a view file getting rendered, the Controller name will appear in the file path, so it harder to get conflicted but not impossible i think.

Let see the view file rendering process for a view file:
1. plugins/MyTheme/templates/plugin/Download/DownloadFiles/add.php
2. plugins/MyTheme/templates/DownloadFiles/add.php 
3. templates/plugin/Download/DownloadFiles/add.php
4. plugins/Download/templates/DownloadFiles/add.php

On the 2. point if the MyTheme contains a same controller, than the plugin template will be overwritten too :( (same like an element but harder to ran into).

I think the second path is in wrong place in the row.

1: The Theme plugin overrides the another plugin files. So if i would like to override the plugin rendered files i can because the 1. step makes it.

2-3: If i don't want to override let use the plugin's file. (it would be the 2.)

4: After all use the Theme plugin paths for everything all. (not for plugin files, usually the Theme plugin own controller and view files)

5: look into cake

Thank you guys for the conversation. It is closable because the application can ovcerride the rendering process.

**Comment by markstory** [comment]
> On the 2. point if the MyTheme contains a same controller, than the plugin template will be overwritten too :( (same like an element but harder to ran into).

I don't disagree that the current paths could be improved and the top-level template path should probably not be included. However, changing that creates a breaking change and we'd have to push that out to 5.0. If someone is willing to put together a pull request for that change we can discuss it further :smile:

**Comment by lamasgergo** [comment]
OKay of course it is a hard core change so maybe later. Thanks for the tip.
