### ISSUE TITLE
DI: ContainerInterface is missing share() function mentioned in docs

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16022]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Current 4.next aka https://github.com/cakephp/cakephp/commit/adb63fef6bbbe4d4852957581c008ed2f42fcf21
* Platform and Target: Any

As righel mentioned in the Slack channel currently the `$container->share()` function of the DI container is not being auto-completed by e.g. PHPStorm because the ContainerInterface doesn't contain that function.

https://github.com/cakephp/cakephp/blob/4.x/src/Core/ContainerInterface.php

But this is the type the `$container` parameter has in the `src/Application.php`

https://github.com/cakephp/app/blob/4.next/src/Application.php#L116

So either:

* we adjust the Interface to also contain the `->share()` function or
* we adjust the documentation so that shared services should only be added via `->add($id, $concrete, true)`. 

Adjusting the docs would be necessary anyway in the long term because the 4.0 version of thephpleague/container already changes the function name from `Container::shared` to `Container::addShared` and removes the third parameter of `Container::add`

See https://github.com/thephpleague/container/blob/4.x/CHANGELOG.md#400

**Comment by ADmad** [comment]
The easy way would be to simply add that method to our `ContainerInterface`. 

The "proper" way to deal with this is would be to backport https://github.com/cakephp/cakephp/pull/15668 to `4.next` which bumps `league/container` to v4 and makes our `ContainerInterface` extend it's `DefinitionInterface` which fixes the discrepancy of methods between the interface and the implementing class.

**Comment by othercorey** [comment]
Would be nice not to lag behind league/container already.

**Comment by ADmad** [comment]
> Would be nice not to lag behind league/container already.

I agree, it would be extra work when migrating apps to Cake 5. Since the container feature is marked experimental I think we can break backwards compatibility in a minor.

**Comment by othercorey** [comment]
Do we remove the experimental flag in 4.3?

**Comment by markstory** [comment]
> I agree, it would be extra work when migrating apps to Cake 5. Since the container feature is marked experimental I think we can break backwards compatibility in a minor.

Yes, we can. That was one of the goals of using experimental flags.

> Do we remove the experimental flag in 4.3?

We could, but I don't think we've had many users adopt it yet. We'll be safer if we wait until 4.4.
