### ISSUE TITLE
PHPUnitExtension not truncating Tables of Plugins between different Test Cases

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#16028]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0-RC3
* Platform and Target: Sqlite (on disk), PHP 8.0.11 x64 NTS

### What you did
I'm using AuditStash to monitor changes for different Entities. AuditStash in configured to run as part of the Migrations.

```php
$migrator = new Migrator(['outputLevel' => ConsoleIo::VERBOSE]);
$migrator->run([['connection' => 'test'], ['plugin' => 'AuditStash', 'connection' => 'test']]);
```

### What happened
2 tests started to fail because the Number of Entries in the AuditLogs Table is too high.
It seems like the table (audit_logs) is not truncated between different Test Cases.
How does CakePHP determine which Tables to truncate?
Does the table need to be named in the $fixtures[] ? Currently it's not because by default it's empty and I don't want to insert data.

### What you expected to happen
Tables of Plugins should be truncated in the same way application tables are between test cases.

**Comment by othercorey** [comment]
We truncate only fixtures tables referenced by that TestCase.

**Comment by othercorey** [comment]
If you don't want to manually truncate the table, you can create a Fixture for it with no records.

**Comment by swiffer** [comment]
Thanks! Ok, I'll do that :)

**Comment by othercorey** [comment]
@swiffer We appreciate testing this for us even with the awkward dev branch requirements in all these packages.

**Comment by markstory** [comment]
>  How does CakePHP determine which Tables to truncate?

This is based on the `$fixtures` array of the result of `getFixtures()` in your test cases. Which is the same as before.

**Comment by swiffer** [comment]
Ok, I added back a empty fixture for the AuditLogs Table and also copied the Plugin Migration to the App migrations as it's just a single table.

this allows me to locally test in memory via sqlite again.

https://github.com/cakephp/migrations/issues/513#issue-1021687344

120/120 integration test cases passing now with the new fixture system and migrator on cakephp 4.3

**Comment by markstory** [comment]
> this allows me to locally test in memory via sqlite again.

Great to hear, does that mean that cakephp/migrations#513 can be closed?
