### ISSUE TITLE
Replace TableSchemaInterface with TableSchema

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16027]
We have an interface `TableSchemaInterface` that is implemented by one class `TableSchema`.

`TableSchema` is the return type for `Driver::newTableSchema()` and is required by function such as `SchemaDialect::dropTableSql()`.

Is there a need for a separate interface when we have to assume the implementation is `TableSchema`?

**Comment by dereuromark** [comment]
We either move to the interface contract for those using classes, or if we really cant, don't need such interfaces.
The former sounds a bit cleaner, of course.

**Comment by markstory** [comment]
Having and interface with a single implementation is something we have in a few places. It can be useful when user-land has to typehint against core classes, or when userland code may need to implement/extend the framework.

Another example, the new Case expression also includes an interface with a single implementation. I don't know if we'll ever have another implmentation and that could be another interface we remove.

**Comment by othercorey** [comment]
Just feels silly to have an interface that you have to `@var` annotate to the correct type since it's the only type.

**Comment by ADmad** [comment]
`Database\DriverInterface` => `Database\Driver` is another one. Highly doubt anyone is going to implement then own driver class without using `Driver`.

**Comment by othercorey** [comment]
> `Database\DriverInterface` => `Database\Driver` is another one. Highly doubt anyone is going to implement then own driver class without using `Driver`.

Also, we make some assumptions that Driver is the base class by calling annotated methods on DriverInterface.

**Comment by ADmad** [comment]
> Also, we make some assumptions that Driver is the base class by calling annotated methods on DriverInterface.

I got rid of that at least, the annotated methods are added to the interface in 5.x.

**Comment by dereuromark** [comment]
> make some assumptions that Driver is the base class by calling annotated methods on DriverInterface.

No, those are for BC, as you cannot add the real methods in minors, only in the major.

**Comment by othercorey** [comment]
> No, those are for BC, as you cannot add the real methods in minors, only in the major.

But they must exist if we are calling them, right?

**Comment by dereuromark** [comment]
Sure, thats why they need to be implemented. The doc block trick kind of also requires it, just less strictly (code wise).

**Comment by othercorey** [comment]
I'm not confused about why we add the annotation. I'm saying we expect all drivers to use `Driver` base class because of that.

**Comment by dereuromark** [comment]
Technically, any (also custom) base class that implements those methods, but in reality that is sure true.

**Comment by othercorey** [comment]
You're right, they don't have to use `Driver` itself, but the expectation is the same.
