### ISSUE TITLE
Truncate multiple Tables at once in SchemaCleaner for greater performance

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#16021]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0-RC3
* Platform and Target: PHP 8.0.8, PostgreSQL 13.4

### What you did
The SchemaCleaner (https://github.com/cakephp/cakephp/blob/4.next/src/TestSuite/Fixture/SchemaCleaner.php) is currently truncating every table seperatly. For postgres this leads to very slow performance and most of the time spent of test suite execution spent in truncation.

It is possible to truncate multiple tables at once - see for example: https://github.com/jbogard/Respawn/pull/58

This is a enhancement request to the handle method / driver interface to allow truncation of multiple tables in one step.

### What happened
TestSuite execution is slow (Postgres) as all Tables of the Testsuite (34 in my case) are truncated seperatly.

### What you expected to happen
Truncating them in one SQL statement greatly improves testsuite execution time.

**Comment by markstory** [comment]
I'm not sure if its the separate truncate queries that is the problem, and that it might be the `RESTART IDENTITY` part that is time consuming. The other implementation you linked does not reset sequences.

**Comment by othercorey** [comment]
I did not cleanup SchemaCleaner because it was internal, but I'll take a look before release hopefully.

**Comment by swiffer** [comment]
when you are at it:

executing the testsuite i currently get this warning in the postgresql logs:

`2021-10-11 15:47:21.212 UTC [481] WARNING:  SET CONSTRAINTS can only be used in transaction blocks`

the truncate statements seem to be wrapped with set constraints while not running in a transaction.

from the `logs/queries.log`
```log
2021-10-11 15:47:12 debug: connection=test duration=45 rows=0 SET CONSTRAINTS ALL IMMEDIATE
2021-10-11 15:47:12 debug: connection=test duration=0 rows=0 COMMIT
2021-10-11 15:47:12 debug: connection=test duration=76 rows=0 SET CONSTRAINTS ALL DEFERRED
2021-10-11 15:47:13 debug: connection=test duration=565 rows=0 TRUNCATE "companies" RESTART IDENTITY CASCADE
2021-10-11 15:47:13 debug: connection=test duration=281 rows=0 TRUNCATE "users" RESTART IDENTITY CASCADE
.....
2021-10-11 15:47:18 debug: connection=test duration=59 rows=0 SET CONSTRAINTS ALL IMMEDIATE
2021-10-11 15:47:18 debug: connection=test duration=0 rows=0 BEGIN
2021-10-11 15:47:18 debug: connection=test duration=58 rows=0 SET CONSTRAINTS ALL DEFERRED
```

**Comment by othercorey** [comment]
Yea. I think I'll try to merge SchemaCleaner into FixtureHelper which can wrap code in the appropriate logic for db-specific foreign key disable/enable.

**Comment by othercorey** [comment]
I've merged SchemaCleaner. I don't think we'll do anything like truncate multiple tables in a single statement just for postgres though. I'm closing this for now.

**Comment by pabloelcolombiano** [comment]
@swiffer you may try cleaning your test DB with the CakePHP test suite light plugin. Truncation is made in one single procedure there, that could improve the performance of your test suite.
