### ISSUE TITLE
Call to undefined method Cake\Validation\Validator::truthy()

### ISSUE THREAD

**Issue by marianodonal** [cakephp/cakephp#16036]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.10.
* Platform and Target: Localhost MAMP.

### What you did
I,m trying to implement truthy validation function but i get an error.

### What you expected to happen
I want to validate a checkbox TOS.

I think there is a problem in code quotation in vendor/cakephp/cakephp/src/Validation/Validation.php after line 625.

**Comment by othercorey** [comment]
Can you give more details about what you're doing?

**Comment by marianodonal** [comment]
Hi!

This is the code in Table Model:

`$validator
    ->boolean('informed_consent')
    ->requirePresence('informed_consent', 'create')
    ->truthy('informed_consent');`

and this is the code in the view:
`<?= $this->Form->control('informed_consent', ['type' => 'checkbox', 'label' => __('Informed Consent')]); ?>`

**Comment by othercorey** [comment]
`truthy` does not exist in `Validator`. It does exist in `Validation` where the rules live.

You can add the rule using `Validator::add()`:

```php
$validator->add('informed_consent', 'truthy', ['rule' => 'truthy', 'message' => 'Error message']);
```

**Comment by markstory** [comment]
We could add a `truthy` method to `Validator`. Would you be interested in helping get that added @marianodonal
