### ISSUE TITLE
Singular plural question 

### ISSUE THREAD

**Issue by zsfoto** [cakephp/cakephp#16034]
I do not speak English well. I make a page for my photos where I would also store EXIF. Also the lenses.
I created the **lenses** table. The singular would be **lens**.
[https://sandbox.dereuromark.de/sandbox/inflector?string=Lenses](https://sandbox.dereuromark.de/sandbox/inflector?string=Lenses)
He thinks of cakephp **lense**.
Where is the mistake?

**Comment by othercorey** [comment]
We must be missing a special case for this and the default is dropping the s at the end.

**Comment by othercorey** [comment]
This will be fixed in 4.3. 

You can add a custom inflector until then. https://book.cakephp.org/4/en/core-libraries/inflector.html#loading-custom-inflections
