### ISSUE TITLE
Undefined index: table in (...)/Database/QueryCompiler.php, line 272

### ISSUE THREAD

**Issue by rmard** [cakephp/cakephp#16043]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.8
* Platform and Target: Apache/2.4.48, PHP 7.4.21

### What you did
I created a query with a join like this:
```
$comments = $this->Comments->find('all', [
	'fields' => ['extras', 'username'=>'users.name', 'text'],
	'join' => [
		'users' => [
			'conditions' => 'users.record_num = comments.user_id'
		]
	],
	'conditions' => [
		'users.category_id' => 1,
	]
]);
```

### What happened
That works, but throws two notices in my _debug.log_ file:
* `Notice: Notice (8): Undefined index: table in [/var/www/html/vendor/cakephp/cakephp/src/Database/QueryCompiler.php, line 272`
* `Notice: Notice (8): Undefined index: table in [/var/www/html/vendor/cakephp/cakephp/src/Database/QueryCompiler.php, line 276`
The query only works because I used the exact table name as join alias.

### What you expected to happen
I figured out that I just need to add `'table' => 'users'` in the join=>users array to get rid of the two notices, I've already done that. I just thought it would be nice if the notices were a bit more descriptive (making it super clear that I forgot the 'table' property).

Peharps if the 'table' key is missing, just try and use the alias as table name, while throwing a warning (using Cake's  `triggerWarning`) like: "Missing table name in join {$joinAlias}. Specify a table name in ${$joinAlias}['table']."

I'd really like to contribute to the CakePHP project, would that be a good first issue for me to submit a PR?

Thanks!

**Comment by markstory** [comment]
> Peharps if the 'table' key is missing, just try and use the alias as table name, while throwing a warning (using Cake's triggerWarning) like: "Missing table name in join {$joinAlias}. Specify a table name in ${$joinAlias}['table']."

This seems like it could be an exception. If someone is using a malformed `join` clause it should make an exception.

Is there a reason you chose to use this API over `Query::join()` or defining an association?

**Comment by rmard** [comment]
@markstory No reason, I just based that on a previously written code that we needed changed due to a change in a business rule. Then we started using the malformed `join` because it worked, only noticed the _debug.log_ entries afterwards.

I agree that raising an exception in such cases would be good too, it would make it easier to spot the missing `'table'` property right away.
