### ISSUE TITLE
PaginatorComponent ignores $_defaultConfig

### ISSUE THREAD

**Issue by fabian-mcfly** [cakephp/cakephp#16056]
### Description

I just found out that the PaginatorComponent in `src\Controller\Component\PaginatorComponent.php` ignores the $_defaultConfig because it overwrites the `setConfig`-Method which itself calls `$this->_paginator->setConfig()` without the defaults:
https://github.com/cakephp/cakephp/blob/6ccf771238720ec4815a1bca68e379263afc67c7/src/Controller/Component/PaginatorComponent.php#L289

This is not a problem until you extend PaginatorComponent and try to change the default settings because it uses the $_defaultConfig in `\src\Datasource\Paginator.php` instead.

### CakePHP Version

4.2.10

### PHP Version

8.0

**Comment by othercorey** [comment]
This is resolved by removing the unsupported $_defaultConfig from PaginatorComponent. There isn't a way to support those defaults and the Paginator class defaults. You'll have to customize setConfig() yourself or customize Paginator moving forward.
