### ISSUE TITLE
TestFixture::_schemaFromReflection getting "wrong" column type (Sqlite, Json)

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#16067]
### Description

When using the new Fixture System and relying on `TestFixture::_schemaFromReflection` instead of specifying fields in the Fixture file CakePHP is not taking `_initializeSchema` of the table into consideration.

Having 2 json columns in a sqlite database result in errors inserting the fixture data now.

Within the Migration:

```php
            ->addColumn('excluded_articles', 'json', [
                'default' => null,
                'length' => null,
                'null' => true,
            ])
```

within the table:

```php
    protected function _initializeSchema(TableSchemaInterface $schema): TableSchemaInterface
    {
        $schema->setColumnType('excluded_articles', 'json');

        return $schema;
    }
```

within the fixture:

```php
        $this->records = [
            [
                ...
                'excluded_articles' => [],
                ...
            ],
```

error message:
```log
InvalidArgumentException: Cannot convert value of type `array` to string
```

Note: it is currently working just fine for PostgreSQL because it has a json column type but it's not for sqlite.

### CakePHP Version

4.3.0

### PHP Version

8.0

**Comment by othercorey** [comment]
> Having 2 json columns in a sqlite database result in errors inserting the fixture data now.

Does the number of columns matter?

**Comment by swiffer** [comment]
No sorry, it does not - I'm just having two :)

**Comment by swiffer** [comment]
Thanks! working fine for me!
