### ISSUE TITLE
Relative paths for `Error.ignoredDeprecationPaths`

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#16079]
### Description

```
Deprecated: You are using the listener based PHPUnit integration. This fixture system is deprecated, and we recommend you upgrade to the extension based PHPUnit integration. See https://book.cakephp.org/4.x/en/appendixes/fixture-upgrade.html - /home/mirko/Libs/Plugins/me-tools/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php, line: 79
 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `endor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php` to  `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file. in /home/mirko/Libs/Plugins/me-tools/vendor/cakephp/cakephp/src/Core/functions.php on line 322
```

Look at the relative path that is detected: `endor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php` (the leading `v` is missing).

Paradoxically, it works correctly just by adding the wrong path to `Error.ignoredDeprecationPaths`:
```
Configure::write('Error.ignoredDeprecationPaths', ['endor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php']);
```

The error seems to me to be found [here](https://github.com/cakephp/cakephp/blob/4.x/src/Core/functions.php#L291
).

However, if I'm opening an issue instead of doing a PR, it's because (I know it's late) CakePHP could also be in another path not related to the `ROOT` (for example, sometimes I create a symbolic link to test a branch of cakephp within my apps and plugins).

So, instead of the file path, I would look for another system. For example the file name only, or the class name (but some deprecations are inside functions...).

Example. Instead of (current code to suppress the message)
```
if (fnmatch($pattern, $relative)) {
                    return;
                }
```
Something like:
```
if (fnmatch($pattern, $relative) || $pattern === basename($frame['file'])) {
                    return;
                }
```

This should also make it possible to do so:
```
Configure::write('Error.ignoredDeprecationPaths', ['FixtureInjector.php']);
```

### CakePHP Version

4.3.0

**Comment by markstory** [comment]
> However, if I'm opening an issue instead of doing a PR, it's because (I know it's late) CakePHP could also be in another path not related to the ROOT (for example, sometimes I create a symbolic link to test a branch of cakephp within my apps and plugins).

This is not a supported installation method.

> So, instead of the file path, I would look for another system. For example the file name only, or the class name (but some deprecations are inside functions...).

I think we need more than just the filename to ignore deprecations, as filenames are not unique. Using an `fnmatch` compatible expression could be a good improvement.

**Comment by mirko-pagliai** [comment]
> This is not a supported installation method.

Ok.

> I think we need more than just the filename to ignore deprecations, as filenames are not unique. Using an `fnmatch` compatible expression could be a good improvement.

I can confirm that with a wildcard, it works correctly:
```
Configure::write('Error.ignoredDeprecationPaths', ['*/cakephp/src/TestSuite/Fixture/FixtureInjector.php']);
```

I will check whether to do a PR.

**Comment by othercorey** [comment]
This already uses fnmatch to compare the ignored patterns against deprecation.

**Comment by mirko-pagliai** [comment]
> This already uses fnmatch to compare the ignored patterns against deprecation.

The problem currently is that it does not recognize the correct path, see example of the first post.

It recognizes this as a relative path:
```
endor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php
```
