### ISSUE TITLE
Cakephp 4.2.10 to 4.3.0 upgrade downgrades pimple/pimple

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#16070]
### Description

I had to downgrade to CakePHP 4.2.10 because pimple/pimple https://github.com/silexphp/Pimple/blob/main/CHANGELOG was downgraded from 3.4.0 to 3.0.2 -> please upgrade the dependency

### CakePHP Version

4.3.0

### PHP Version

8.0.8

**Comment by ADmad** [comment]
Pimple `v3.4` using `v1` of `psr/container` while CakePHP 4.4 using `v2`. Based on it's readme doesn't seem like it will be updated to support v2 of `psr/container`, but you could try opening an issue/PR.

> No new features will be added and no cosmetic changes will be accepted either.

Given that CakePHP already includes a service container now you can just switch to that instead.

**Comment by ADmad** [comment]
Given that [Pimple\Psr11\Container::has()](https://github.com/silexphp/Pimple/blob/86406047271859ffc13424a048541f4531f53601/src/Pimple/Psr11/Container.php#L51) already has `bool` return type (which is the only difference between v1 and v2 of psr/container), it can already support `psr/container` v2 without any change. So it's just a matter of updating the constraints in it's composer.json.

**Comment by ADmad** [comment]
There's already a PR for adding psr/container v2 support https://github.com/silexphp/Pimple/pull/265, so you should help getting that merged :)

**Comment by markusramsak** [comment]
#16071 this is related and seems to serve the purpose to make the dependency more visible

**Comment by othercorey** [comment]
Added an explicit dependency on psr/container to make it clear.

Closing since this isn't something we can change.
