### ISSUE TITLE
CSP Header Middleware + NONCE

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16086]
### Description

I tried the new NONCE population feature of CSP Header middleware in 4.3.0 and noticed, that there is an error in the docs at https://book.cakephp.org/4/en/controllers/middleware.html#content-security-policy-header-middleware where the code example says:

```
$middlewareQueue->add($csp, [
    'scriptNonce' => true,
    'styleNonce' => true,
]);
```

The add() method of MiddlewareQueue doesn't expect a second parameter. I think the second parameter must be added when instantiating the CspMiddleware, so the code example should actually look like this:

```
$csp = new CspMiddleware([
    'script-src' => [
        ...
    ],
], [
    'scriptNonce' => true,
    'styleNonce' => true,
]);
```

I also realised that in order for this to work, you NEED to have `script-src` and `style-src` in your CSP config. I.e. a setup like ...

```
$csp = new CspMiddleware(
    [
        'default-src' => [],
    ],
    [
        'scriptNonce' => true,
        'styleNonce' => true,
    ]
);
```

... wouldn't work as expected. The NONCE neither gets added to the HTML elements, nor to the CSP header. The header instead looks like this: `default-src 'none';`

Only if i configure the middleware WITH (even an empty) script-src and style-src ...

```
$csp = new CspMiddleware(
    [
        'default-src' => [],
        'script-src' => [],
        'style-src' => [],
    ],
    [
        'scriptNonce' => true,
        'styleNonce' => true,
    ]
);
```

... it adds the NONCE to the header correctly, which could be considered a bug?

### CakePHP Version

4.3.0

### PHP Version

7.4

**Comment by markstory** [comment]
> The add() method of MiddlewareQueue doesn't expect a second parameter. I think the second parameter must be added when instantiating the CspMiddleware, so the code example should actually look like this:

Yes, the docs are incorrect. I goofed that up when I last updated them.

> I also realised that in order for this to work, you NEED to have script-src and style-src in your CSP config. I.e. a setup like ...

Yes, unfortunately the CspBuilder won't add the nonce unless the directive already exists. The cspbuilder also doesn't provide a good way to read the state of the builder without mutating it. I didn't want to try munging the header value as CSP headers can get complicated.

I'll get the docs updated, as those are wrong. I can include some extra content explaining that you need to have a `script-src` or `style-src` directive defined for the nonces to work as well.

**Comment by markstory** [comment]
With the docs updated I think the issues outlined here are as solved as we can make them. Having the new CSP behaviors be opt-in isn't as smooth as it could be because of how the cspbuilder library works, but I've not found many other good alternatives that we could use either.

**Comment by tuntuntun** [comment]
Hello!
Thanks for the info.

I saw this information and added CspMiddleware.
However, it is not working as expected, so I have a question.


//Current status
my Cakephp ver 4.4.1
Http header outputs nonce value as expected.
However, the output of the html file shows only the nonce and the value is empty.
The Http header and the nonce in the html do not match, so there is an error and it is broken.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/5017373/173758630-97235c5a-a53d-40e7-9f62-7d6af039373b.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/5017373/173758887-5bc883a5-618b-4862-80a4-0c93e141a8dd.png">


//Question
How can I display the value of nonce in the output of the html file?

**Comment by ADmad** [comment]
@tuntuntun This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
where we will be more than happy to help answer your questions.
 
Thanks!

**Comment by tuntuntun** [comment]
@ADmad 
Sorry, I'll be careful from now on.
Thanks for the link!

**Comment by tuntuntun** [comment]
@ADmad 
This may be a bug.

The reason.
My version, despite being 4.4.
implemented in cakephp 4.3 and automatically outputting is not actually outputting.
The part that is output automatically refers to nonce.

```
New in version 4.3.0: Automatic nonce population was added.
```

URL
https://book.cakephp.org/4/en/security/content-security-policy.html

**Comment by gerhard-lechner** [comment]
@tuntuntun Note that the Inspector - e.g. in Chrome - doesn't display the nonce value, see https://stackoverflow.com/questions/55670985/google-chrome-stripping-nonce-values-from-script-tags

Use "view source" to check the HTML that is actually rendered.

**Comment by tuntuntun** [comment]
@gerhard-lechner 
Thank you!
You were very helpful.
I'm glad you didn't have any problems.

I will have to look into this more carefully.
