### ISSUE TITLE
Support read and write database connections

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16095]
### Description

CakePHP is missing native support for a very common convention: separate read and write database connections.

There are some externals solutions such as the cakephp-master-replica plugin:
https://github.com/Connehito/cakephp-master-replica

This was presented at CakeFest 2021:
https://www.youtube.com/watch?v=Ey8VljZBk-g

These external solutions generally require switching the connection globally each time a read or write is required.

A native solution would enforce the correct connection is used for each query regardless of when they're executed.

Generally speaking, a connection will have a read and write "role" configuration instead of creating separately named connections. This means, you would still specify just `test` or `default` as the connection for queries or Tables and the correct role is used for each execution.

However, users will need more than the default behavior in many situations.

#### Open Questions

* Can tables specify a role?

  What is the resolution when an associated target has a different role than the source table?

* Do you specify the role when creating a new query to override the behavior?

  What if you want to read from the write connection instead of dealing with replica lag?

  What if you need an entire series of queries or an entire request to use a specific role?

* Do you specify the role for non-query operations like starting a transaction?

  Would users expect any role validation when executing queries with a different role during a transaction?
  

### CakePHP Version

Depending on the API changes required, this would target CakePHP 5.0 or 4.4.

**Comment by markstory** [comment]
> Can tables specify a role?

I think we should have read/write configuration at the query level, and have affordances at the table level to set defaults. Having role configurations at the query level allows us to accommodate scenarios where you need to read from the primary to avoid replica lag (question 2).

> Do you specify the role for non-query operations like starting a transaction?

I think we would want a way to get the read/write connection for a table and use it. Something like

```php
$users->getConnectionFor('read')->transactional(function () {
    // Many queries here.
});
```

**Comment by othercorey** [comment]
> I think we would want a way to get the read/write connection for a table and use it. Something like
> 
> ```
> $users->getConnectionFor('read')->transactional(function () {
>     // Many queries here.
> });
> ```

This implies having a separate `Connection` instance for each role. That makes sense for some reasons, but would conflict with the idea of still having a a `test` or `default` connection. 

Would a `Connection` have an array of other `Connection` instances for the roles? Could users use `ConnectionManager` get those role instances?

**Comment by ADmad** [comment]
> Would a Connection have an array of other Connection instances for the roles?

Cycle ORM has a `Database` class (which is equivalent to our `Connection`) with multiple drivers. `Database::getDriver()` allows specifying the type (role) read or write.

**Comment by othercorey** [comment]
> Cycle ORM has a `Database` class (which is equivalent to our `Connection`) with multiple drivers. `Database::getDriver()` allows specifying the type (role) read or write.

Our `Driver` owns the PDO instance. I'm not sure if that's correct or not, but certainly not changing it in 4.4. So, the Driver could own the array of PDO instances for the roles or the `Connection` could own the array of Drivers.

There is some client-side state management for transactions and save points. That needs to be attached to the PDO instance.

We also have some db-specific methods in `ConnectionInterface` that would be hard to abstract out if we added roles to them.

**Comment by markstory** [comment]
> This implies having a separate Connection instance for each role. That makes sense for some reasons, but would conflict with the idea of still having a a test or default connection.

With our current model of Connection and Driver each role would need to be a separate datasource connection and driver connection. We could move to a model where a connection wraps multiple drivers with different roles like @ADmad described but it is a larger amount of work than separate connections. For reference Django also models read/write as separate 'connections' that models switch between based on role -> connection mappings that are handled by [database routers](https://docs.djangoproject.com/en/3.2/topics/db/multi-db/#automatic-database-routing).

> Would a Connection have an array of other Connection instances for the roles? Could users use ConnectionManager get those role instances?

I would stick to having Connection and Driver remain 1:1 and instead we could leverage conventions to do role selection. For example the `default` connection and `read` role could translate to `default_read` as a connection name, if that connection doesn't exist in `ConnectionManager` then the `default` connection could be used instead. Similarly for `default_write` falling back to `default`. This should be compatible with connection aliasing as well because each connection name managed by `ConnectionManager` can have aliases and the role fallbacks could be handled in the Table/Query layers.

> We also have some db-specific methods in ConnectionInterface that would be hard to abstract out if we added roles to them.

One potential improvement for 5.x could be to fold `Connection` and `Driver` together. The alternative use cases we originally planned for other datasources never really materialized, and having fewer layers to the ORM could help simplify the ORM. However, that is a separate discussion as I'm sure there are scenarios I'm not considering right now.

**Comment by othercorey** [comment]
Generating other connections with a name that are accessible via ConnectionManager feels a little strange. However, most users shouldn't notice that and don't think we need to document that behavior.

So, we'll have "roles" configured with a connection. Those roles are just the db credentials part of the datasource and they inherit the top-level config.

Users can still use the top-level connection name like `test` and the query will use the correct read/write role connection behind the scenes.

`Query::getConnection()` will return the top-level connection `test` even if the query is a `select`.

If a user actually creates a `Query` from a role connection, it will return that connection.

**Comment by othercorey** [comment]
I'm still not sure what's supposed to happen when you call `transactional()` on `default` connection if it has read and write roles.

**Comment by ADmad** [comment]
> I'm still not sure what's supposed to happen when you call transactional() on default connection if it has read and write roles.

Cycle defaults to [write](https://github.com/cycle/database/blob/b96ecc8fe74cefd92756f7ed579d9bf2c804bbe2/src/Database.php#L254-L257).

**Comment by othercorey** [comment]
> Cycle defaults to [write](https://github.com/cycle/database/blob/b96ecc8fe74cefd92756f7ed579d9bf2c804bbe2/src/Database.php#L254-L257).

That makes sense. 

What should happen if a user gets `default-read` and tries to start a transaction on it? It should throw a PDO exception from the read replica, right? Well, the db engine might not fail to start a transaction, but it should fail to perform any write operations.

I think relying on db-engine behavior is good enough. We are only tracking basic role assignments not the properties of a db instance.

**Comment by othercorey** [comment]
Should the read and write roles share a schema cache or maintain separate copies?

**Comment by markstory** [comment]
> Should the read and write roles share a schema cache or maintain separate copies?

I would start with separate. There are scenarios where not all tables from a primary will be replicated, so having separate schema caches will help in that situation.

**Comment by othercorey** [comment]
Current proposal: https://github.com/markstory/cakephp/wiki/Minimal-Database-Replication-API

**Comment by othercorey** [comment]
Closing in favor of https://github.com/cakephp/cakephp/issues/16579
