### ISSUE TITLE
Add HSTS header to HttpsEnforcerMiddleware

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16092]
### Description

I think a useful enhancement for the already existing HttpsEnforcerMiddleware would be to automatically (or at least optionally) add the HSTS header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security).

Basically, whenever `$request->getUri()->getScheme() === 'https'`, the middleware could add something like:

```
$this->headers['Strict-Transport-Security'] = 'max-age=' . YEAR * 2 . '; includeSubDomains; preload';
```

The duration as well as presence of `includeSubDomains` and `preload` could be determined through some sort of configuration array.

Whether the HSTS header makes more sense in the HttpsEnforcerMiddleware or the SecurityHeadersMiddleware is probably subject for discussion. Personally i think it makes more sense in the former.

**Comment by markstory** [comment]
> Whether the HSTS header makes more sense in the HttpsEnforcerMiddleware or the SecurityHeadersMiddleware is probably subject for discussion. Personally i think it makes more sense in the former.

I would agree that it should live with HttpEnforcer
