### ISSUE TITLE
Router::reverse() fails for routes with ->setPass()

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16119]
### Description

In my routes.php I have a route like this one:

```
$builder->connect('/articles/{slug}', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
```

Because of the `->setPass(['slug'])` the slug is listed twice in `$this->getRequest()->getAttribute('params');` which is the desired behaviour, i guess:

```
[slug] => testslug
[pass] => Array
(
    [0] => testslug
)
```

However, this causes problems when using `Router::reverse($this->getRequest()->getAttribute('params'))`, because the router class says that no route is matching. When i change my aforementioned route to ...

```
$builder->connect('/articles/{slug}/*', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
```

... it creates the route `/articles/testslug/testslug`. So i think `Router::reverse()` or actually the underlying `Router::reverseToArray()` needs to handle things a little differently when using `->setPass()` when defining a route.

Same behaviour in CakePHP 3 and 4.

### CakePHP Version

3.9.6 AND 4.3.1

### PHP Version

7.4

**Comment by skie** [comment]
After this commit routeReverse stop working for url '/authors/1/articles/1' (still works for /authors/1/articles/10) Looks like 1 found in passed author_id which is same as for article id.

The reverse route receive 
```Array
(
    [author_id] => 1
    [pass] => Array
        (
            [0] => 1
        )

    [controller] => Articles
    [action] => view
    [_method] => GET
    [map] => Array
        (
        )

    [plugin] => 
    [_matchedRoute] => /authors/{author_id}/articles/{id}
)
```
Reverting the reverseToArray changes fixes issue.
