### ISSUE TITLE
RFC - Show route collision notice in debug mode

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16126]
### Description

Lets imagine a `config/routes.php` which has the following routes connected:

```
$builder->connect( '/', [ 'controller' => 'Pages', 'action' => 'display', 'home' ] );
$builder->connect( '/', [ 'controller' => 'Pages', 'action' => 'display', 'slack_ids' ] );
```

Sure, here it is obviously clear that we have a collision and only one of those 2 will actually be used when doing a Request to `/`

In the current implementation the first match will be displayed on `/` and the second just doesn't do anything.

But for new users some may argue that it should "overwrite" the already present route - which I don't support either.

But it would be usefull to at least show a warning/message/do something when a Route collision is being detected in debug mode.

Wondering what you think about that.

### CakePHP Version

4.3

**Comment by dereuromark** [comment]
DebugKit could have the routes panel show this
Also a `bin/cake routes` could highlight those maybe.

But the normal workflow should not be interrupted IMO as there are quite a few cases where routes are just more specific up front and have catch-alls or fallbacks of sorts afterwards defined. Detecting here what is an accident and what on purpose sounds not trivial.

**Comment by saeideng** [comment]
#16227 has been merged
