### ISSUE TITLE
SchemaLoader fails to purge MySQL database containing Views

### ISSUE THREAD

**Issue by rmarsh1ua** [cakephp/cakephp#16122]
### Description
While following [the docs](https://book.cakephp.org/4.next/en/development/testing.html#creating-test-database-schema) for setting up unit tests, it describes some example code to use the SchemaLoader class to define the app's database. Running this more than once, i.e. the database is created/schema is created, generates an error trying to drop a table that doesn't exist. The error refers to a view. 

It seems like SchemaLoader is trying to drop all tables in the SHOW TABLES FROM clause regardless of whether or not it's an actual table or view. This essentially makes using SchemaLoader useless for setting up unit tests and it would be preferable if it would exclude dropping views from the database.

### CakePHP Version

4.3.0

### PHP Version

7.4.3

**Comment by othercorey** [comment]
Are you creating views in the schema sql loaded by SchemaLoader?

**Comment by rmarsh1ua** [comment]
> 

Yea, the schema file includes views from the main application database's dump file. I'm not sure it makes a difference because the views are critical to the app functionality and would need to exist in the database no matter what during the test database recreation process where this error is triggered. As you have seen, there's further discussion in the PR thread.

**Comment by markstory** [comment]
Now that I've separated this from the separate but related issue in migrations, are you not able to tweak your SQL dump to do what you need? If your schema dump is created with `DROP IF EXISTS` style statements that manage your schema in the way you want, then you can disable drop & truncate using the paramters.

```php
(new SchemaLoader())->loadSqlFiles('path/to/schema.sql', 'test', false);
```

Using a schema file implies you want a high level of control or need to use platform specific features. You're using the expert mode APIs so you might have to do a bit more work.

**Comment by rmarsh1ua** [comment]
I started with SchemaLoader just to get some basic unit tests setup and I eventually want to move my project to use Migrations. It's not clear yet if I'll be able to do that, since there are some idiosyncrasies to the schema. 
I think I've inferred that this new, third parameter in loadSqlFiles is an array of tables/views to skip? FWIW, in our use case there's not an insignificant # of views which would be annoying to keep track of if SchemaLoader becomes the permanent solution. So, still hoping the changes we're working on the linked PR will be helpful / relevant!

**Comment by markstory** [comment]
The third parameter isn't an option/array yet. It is a boolean that when false disabled table drop SQL being generated by `SchemaLoader`. My suggestion was for you to change your SQL dump file that contains your schema to include `DROP IF EXISTS` statements where necessary.

>  I started with SchemaLoader just to get some basic unit tests setup and I eventually want to move my project to use Migrations. It's not clear yet if I'll be able to do that, since there are some idiosyncrasies to the schema.

You don't have to use migrations if it doesn't work for your project. You can also build a wrapper for the existing tools you're using to create/modify your schema.
