### ISSUE TITLE
Milliseconds are not logged anymore

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#16128]
### Description

With https://github.com/cakephp/cakephp/pull/14850 CakePHP made it possible to log messages with a millicsecond precision timestamp.

This feature was lost when the date formatting was moved to the `DefaultFormatter`.

Since upgrading to 4.3.1, when i use a format like this:

```
            'formatter' => [
                'className' => DefaultFormatter::class,
                'dateFormat' => 'Y-m-d H:i:s.v'
            ]
```
i always get log timestamps ending in `.000`.

Solution will probably be the same as in https://github.com/cakephp/cakephp/pull/14850 : Use ` (new DateTimeImmutable())->format()` instead of `date()`

### CakePHP Version

4.3.1

### PHP Version

8.0.12

**Comment by ADmad** [comment]
Would you link to send a pull request with your suggested changes?

**Comment by BGehrels** [comment]
It depends. If it's just about fixing the bug: sure.
iven that this is a regression that has not been caught by a test, a test might make sense. Then we are in the field of "How to mock time in an existing tech stack you don't know well" which is a field i would love to leave to you.

**Comment by markstory** [comment]
If you open a pull request with the fix we can help with updating the tests. :smile:

**Comment by othercorey** [comment]
Whoops. I'll patch it.
