### ISSUE TITLE
Don't see _cake_core_ storing file maps in CakePHP4.2.8

### ISSUE THREAD

**Issue by manhlx-fsoft** [cakephp/cakephp#16135]
### Description

I dont see maping file in folder /tmp/cache/persistent.
Did CakePHP4.2.8 remove this function?

In CakePHP2X i saw cache method? Did CakePHP4.2.8  also remove it?

Could you help me my isssue?
Thanks for reading.

### CakePHP Version

4.2.8

### PHP Version

7.4

**Comment by ADmad** [comment]
CakePHP doesn't need to manage the filemap itself anymore as class file auto loading is handled by composer now.
