### ISSUE TITLE
Git ignoring any file under an `icons` folder

### ISSUE THREAD

**Issue by rmard** [cakephp/cakephp#16138]
### Description

My company stores icon files (mostly SVGs and PNGs) inside a `[CAKEPATH]/webroot/img/icons/` folder. While working on a server migration we noticed that all our icon files were ignored by Git, the files just didn't exist on our Git repository.

I found out this is due to CakePHP's default `.gitignore` file, [line 23](https://github.com/cakephp/cakephp/blob/4.x/.gitignore#L23), which reads `Icon?`. This causes any file inside any folder with `icon` in its name to be ignored, especially in case-insensitive systems like MacOS.

On [GitHub's official gitignore template](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore#L7) for MacOS-related files, it's recommended that we use `Icon` followed by two `\r`. Replacing `Icon?` with `Icon\r\r` fixes the issue I just described and it's still enough to make Git ignore those MacOS hidden system files.

### CakePHP Version

4.3.0

**Comment by garas** [comment]
`.gitignore` from `cakephp/cakephp` doesn't affect `webroot` folder, but `cakephp/app` does.

You should modify https://github.com/cakephp/app/blob/4.x/.gitignore#L16 instead.

Also leave comment `# Icon must end with two \r` as it is invisible and easy to lose `\r`.

**Comment by rmard** [comment]
Got it, thanks for pointing that out @garas.

I've just created a [new PR in the cakephp/app repository](https://github.com/cakephp/app/pull/873) and closed the first one.

**Comment by markstory** [comment]
Fixed in cakephp/app#873
