### ISSUE TITLE
Fixture insertion errors need better messaging

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp#16147]
### Description

When running unit tests with a table that has foreign key constraints (CakeDC/Users) the tests fail because it is unable to truncate the tables with foreign keys defined.

```
44) App\Test\TestCase\Model\Table\MyUsersTableTest::testBeforeSave
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`authenticon_test`.`social_accounts`, CONSTRAINT `social_accounts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

/var/www/html/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
/var/www/html/vendor/cakephp/cakephp/src/Database/Connection.php:337
/var/www/html/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
/var/www/html/vendor/cakephp/cakephp/src/Database/Connection.php:340
/var/www/html/vendor/cakephp/cakephp/src/Database/Query.php:250
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:343
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:139
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:121
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:134
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/Fixture/TruncateStrategy.php:52
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:301
/var/www/html/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:249
/var/www/html/tests/TestCase/Model/Table/MyUsersTableTest.php:41
```

### CakePHP Version

4.3.1

### PHP Version

8.0.12

**Comment by othercorey** [comment]
I don't think this matters, but what version of mysql is this using?

**Comment by challgren** [comment]
> I don't think this matters, but what version of mysql is this using?

MariaDB 10.5.12 installed via Docker `FROM mariadb:10.5`

**Comment by othercorey** [comment]
There is logic to sort tables when dropping, but this is skipped for mysql due to the above constraint. We should be seeing this failure internally if it was happening so must be an edge case.

**Comment by challgren** [comment]
> There is logic to sort tables when dropping, but this is skipped for mysql due to the above constraint. We should be seeing this failure internally if it was happening so must be an edge case.

Should I create a test app that shows the issue? There's 2 projects this same issue is occuring on and both use the CakeDC/Users plugin

**Comment by othercorey** [comment]
No, I think I can follow. The issue appears to be in ConnectionHelper used by Migrator. That does not have explicit logic for sorting or foreign key constraints when dropping tables. The logic I mentioned is only for truncating tables.

That requirement must have been lost in the re-work since we no longer support dropping tables between tests.

**Comment by challgren** [comment]
What would be my short term solution? As this has resolved one of our biggest problem with Fixtures being outdated

**Comment by othercorey** [comment]
Hmm, sorry, I misread the issue you reported. This failure is happening on a row insert not when dropping tables. Not sure why I assumed that.

It would be helpful to see the list of fixtures defined for this test so I can understand the what order the inserts are expected. There seems to be a failure in the constraint sorting.

**Comment by challgren** [comment]
The only 2 fixtures for the test are app.Users and app.SocialAccounts. I'll try to throw together an app that reproduces the error.

**Comment by challgren** [comment]
The test function is 

```
public function testBeforeSave(): void
    {
        $userEntity = $this->Users->newEmptyEntity();
        $userEntity->email = 'test@email.com';
        $userEntity->role = 'superuser';
        $userEntity->theme = 'CustomsUs';

        $this->Users->beforeSave(new Event('Model.beforeSave'), $userEntity, new \ArrayObject());
        $this->assertTextEquals('test@email.com', $userEntity->get('username'));
        $this->assertNull($userEntity->get('theme'));
        $this->assertTrue($userEntity->get('is_superuser'));

        $userEntity = $this->Users->newEmptyEntity();
        $userEntity->email = 'test@email.com';
        $userEntity->role = 'user';
        $userEntity->theme = 'CustomsUs';

        $this->Users->beforeSave(new Event('Model.beforeSave'), $userEntity, new \ArrayObject());
        $this->assertTextEquals('test@email.com', $userEntity->get('username'));
        $this->assertSame('CustomsUs', $userEntity->get('theme'));
        $this->assertFalse($userEntity->get('is_superuser'));
    }
```

**Comment by othercorey** [comment]
I don't see a foreign key defined in the CakeDC/Users fixtures.

https://github.com/CakeDC/users/blob/master/tests/Fixture/SocialAccountsFixture.php#L43

Am I missing something else?

**Comment by challgren** [comment]
It's in migration https://github.com/CakeDC/users/blob/600ea02a2053d51d55380cbb6122fb8a447d7f05/config/Migrations/20150513201111_initial.php#L149

**Comment by othercorey** [comment]
So, you're saying the migrations under config are now used instead of the schema in the fixture files?

Unless the foreign key is added after the schema for the table is cached, this should include that constraint.

**Comment by challgren** [comment]
I took the CakeDC/Users Migrations copied them to my migrations. Then created custom table/entity for the `users` model. And then created a fixture and tests. Previously before switching to Migrator all tests passed 100%. Now that I'm switching they are failing with this issue. I'll create a demo app on Monday to highlight the issue.

**Comment by pabloelcolombiano** [comment]
@challgren this looks more like an issue with the test suite, in particular the TruncateStrategy, than with the migrator.

My hint here would be to try using the TransactionStrategy.

Also probably do not need to copy any migrations from a plugin to your app. The Migrator enables you to run migrations for a provided plugin + the ones of your app.

**Comment by othercorey** [comment]
@challgren Can you provide the example? We're just missing some context to help resolve this.

**Comment by challgren** [comment]
Yes, I will be creating a test app to highlight the problem when I'm back in town on Sunday. So it will take a couple days.

**Comment by othercorey** [comment]
@challgren If you can still find time to give a full example, would like to resolve this soon.

**Comment by challgren** [comment]
The example repo I setup is https://github.com/challgren/cakephp-16147

**Comment by othercorey** [comment]
This issue is caused by an invalid user_id entry in the SocialAccountsFixture:

```php
        $this->records = [
            [
                'id' => '4a77e7f3-e10a-4d7f-bcfc-00747d79f622',
                'user_id' => '2ec948de-c128-4402-bc7c-b59e3a49d44f',
```

This user id is not in the UsersFixture records. if you replace it with the first user id from UsersFixture, the tests pass.

**Comment by othercorey** [comment]
@markstory We could catch PDO exceptions when inserting and add the name of the fixture to the error.

**Comment by markstory** [comment]
I thought we were doing that. All rows for a fixture are inserted at once so we won't be able to show which row is problematic.

**Comment by challgren** [comment]
Thanks @othercorey I probably would have never caught it with the SQL error message it presented. The funny thing is without the new Migrator the records are fine but thats due to the old schema not using FKs.  Should I close this out since it's more of a user issue than a framework issue.

It would be helpful to have more useful error messages.

**Comment by markstory** [comment]
> It would be helpful to have more useful error messages.

Agree, lets leave this issue open as a record that fixture insertion failure messages need to be improved.

**Comment by othercorey** [comment]
> I thought we were doing that. All rows for a fixture are inserted at once so we won't be able to show which row is problematic.

The new FixtureHelper does not catch any errors yet. It's much more cleaned up though and should be possible.
