### ISSUE TITLE
TestSuite Migrator Docs don't match expected results

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp#16146]
### Description

According to the docs at https://book.cakephp.org/4/en/development/testing.html#creating-test-database-schema if I want to run tests for CakeDC/Users and my own app. I would do the following in the `tests/bootstrap.php`

```
use Migrations\TestSuite\Migrator;

$migrator = new Migrator();
$migrator->run();
$migrator->run(['plugin' => 'CakeDC/Users']);
```

Now when I run my tests I get failures for my own fixtures. But if I invert the `->run()` command and use the following example below the tests pass.

```
use Migrations\TestSuite\Migrator;

$migrator = new Migrator();
$migrator->run(['plugin' => 'CakeDC/Users']);
$migrator->run();
```

What is the recommended method of running tests with the Migrator 

### CakePHP Version

4.3.1

### PHP Version

8.0.13

**Comment by markstory** [comment]
If you need to run multiple configurations you should use `runMany()`. So you would do

```php
$migrator = new Migrator();
$migrator->runMany([
  ['connection' => 'test'],
  ['plugin' => 'CakeDC/Users'],
]);
```

This will avoid the plugin migration run from dropping the tables added by app. I can get that added to the docs.
