### ISSUE TITLE
Boolean validation not work with `true` and `false` in string

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#16144]
### Description

Boolean validation return false for below request
```
field1=true&field2=false
```

https://github.com/cakephp/cakephp/blob/7c71f7a96faff3feea1e67e9ae4fb95e14c80e30/src/Validation/Validation.php#L705

### CakePHP Version

4.3

### PHP Version

7.4

**Comment by ADmad** [comment]
For the current list of values, types casting to `bool` results in the correct boolean value. `(bool)'false'` returns `true`, which is why string `'true'` and `'false'` are not included in the list.

You can make your own validator for your use case.
