### ISSUE TITLE
Router issue after changes in #16119

### ISSUE THREAD

**Issue by skie** [cakephp/cakephp#16148]
### Description

After changes comming from #16119 routeReverse stop working for url '/authors/1/articles/1' (still works for /authors/1/articles/10) 

In this usecase author_id is same as passed id for article and it is deleted.

The reverse route receive
```
(
    [author_id] => 1
    [pass] => Array
        (
            [0] => 1
        )

    [controller] => Articles
    [action] => view
    [_method] => GET
    [map] => Array
        (
        )

    [plugin] => 
    [_matchedRoute] => /authors/{author_id}/articles/{id}
)
```
Reverting the reverseToArray changes fixes issue.

### CakePHP Version

4.3.2

**Comment by markstory** [comment]
How was this route defined? It looks like it is missing a `id` parameter in the array .
