### ISSUE TITLE
PHP 8.2: Fix dynamic property deprecation warnings

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16158]
### Description

With PHP 8.2, dynamic properties without `AllowDynamicProperties` attribute or using __get()/__set() are deprecated.

https://wiki.php.net/rfc/deprecate_dynamic_properties

Current failures:
https://github.com/cakephp/cakephp/runs/4362732361?check_suite_focus=true

The following classes would need the attribute:

- [x] Controller
- [x] Component
- [x] Command
- [x] Shell
- [x] Mailer
- [x] View
- [x] Helper
- [x] Cell

### CakePHP Version

4.4

### PHP Version

8.2

**Comment by othercorey** [comment]
This is the majority of failures:

```
3) Cake\Test\TestCase\Auth\BasicAuthenticateTest::testAuthenticateNoPassword
Creation of dynamic property Laminas\Diactoros\Uri::$base is deprecated

/home/runner/work/cakephp/cakephp/src/Http/ServerRequestFactory.php:254
/home/runner/work/cakephp/cakephp/src/Http/ServerRequestFactory.php:220
```

**Comment by markstory** [comment]
I can take care of that. I added that property on so I could avoid subclassing deeper. That is looking like the better long term solution though.

**Comment by othercorey** [comment]
Last issues fixed with https://github.com/cakephp/cakephp/pull/16212

**Comment by web010** [comment]
I am using CakePHP 4.4.10 with PHP 8.2. In this aplication I also make use of cakephp/acl version 0.8.0.
I would like to keep using this plugin for this application, but there are some deprecated notices like "Creation of dynamic property Acl\Adapter\DbAcl::$Aro is deprecated".

Is there a way to stop these notices? I've tried to put the path to the acl in app.php Error ignoredDeprecationPaths like this:
```
'Error' => [
        'errorLevel' => E_ALL,
        'exceptionRenderer' => 'Cake\Error\ExceptionRenderer',
        'skipLog' => [],
        'log' => true,
        'trace' => true,
        'ignoredDeprecationPaths' => ['vendor/cakephp/acl/*'],
    ]
```
but the notices still are written in the debug.log file. It is not a big issue, but I would like to know if there is a way to stop this via f.e. ignoredDeprecationPaths as written in https://book.cakephp.org/4/en/development/errors.html

Thanks in advance

**Comment by garas** [comment]
`Error.ignoredDeprecationPaths` supresses only CakePHP deprecation warnings.

Dynamic property deprecation warnings comes from PHP. To disable PHP deprecation warnings, set `Error.errorLevel` to `E_ALL ^ E_DEPRECATED`.

**Comment by markstory** [comment]
If you're interested and motivated to fix this, we could use a pull request for the acl plugin. That would be a good way to get this resolved instead of ignoring the error.

**Comment by web010** [comment]
Thanks for your respond. We are working on 2 applications with cakephp 4.4.10 in php 8.2. And yes I would prefer to get the deprecations resolved instead of ignored.
 
I don't know what a pull request exactly means, but if that is the way to go to resolve the issue, I am interested. So let me know what to do.

**Comment by web010** [comment]
> If you're interested and motivated to fix this, we could use a pull request for the acl plugin. That would be a good way to get this resolved instead of ignoring the error.

Deprecations notices are given in:
- Acl/src/Model/Table/PermissionsTable.php (2)
   -  Creation of dynamic property Acl\Model\Table\PermissionsTable::$Aro is deprecated
   - ... $Aco is deprecated

- Acl/src/Adapter/DbAcl.php (3)
   -  Creation of dynamic property Acl\Model\Table\PermissionsTable::$Permission is deprecated
   - ... $Aro is deprecated
   - ... $Aco is deprecated

Could this be repaired with ```#[\AllowDynamicProperties]``` in both files and how to make a pull request for this in https://github.com/cakephp/acl

**Comment by garas** [comment]
It would be better to add real properties to classes than `#[\AllowDynamicProperties]`.

Follow instructions on https://opensource.com/article/19/7/create-pull-request-github to create pull request.
