### ISSUE TITLE
Add matched route as a request attribute

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#16155]
### Description

After routing has been applied, it would be useful to have the route that matched available on the request. This would allow features like `Router::reverse()` to be more efficient. It would also enable DebugKit to expose more data.

The current route could be added as a request attribute by `RoutingMiddleware`. We could deprecate the `params['_matchedRoute']` key as well.

### CakePHP Version

4.4.0

**Comment by dereuromark** [comment]
Also refs https://github.com/cakephp/cakephp/issues/16126

**Comment by markstory** [comment]
Refs #16151

**Comment by othercorey** [comment]
Do you want the same value from `_matchedRoute` attached?

**Comment by markstory** [comment]
> Do you want the same value from _matchedRoute attached?

Yes they should be the same.

**Comment by LordSimal** [comment]
I am a bit confused here...

As far as I understand it now the current routing behaviour is like this:

The RoutingMiddleware calls `Router::parseRequest($request)` which in the end gets to the `RouteCollection->parseRequest($request)` method and iterates over all loaded routes (`$this->_paths`)

Inside this foreach every route is being checked if it can be applied to the given request (via `$route->parseRequest($request);` and finally `$route->parse($uri->getPath(), $request->getMethod())`)

If a valid route has been found it returns the array of request parameters. These parameters are already present in the request object via this line: https://github.com/cakephp/cakephp/blob/4.x/src/Routing/Middleware/RoutingMiddleware.php#L145

These now valid route params actually contain the matched route string already (which is set via the to be deprecated `_matchedRoute`) 

So I don't really understand what should be done here.

**Comment by ADmad** [comment]
This issue is about making the whole matched route instance available as a request attribute instead of just the string in `_matchedRoute`.

Having the instance available would avoid have to loop through all the connected routes to find the one matching the current route params template in Router::reverse().

**Comment by markstory** [comment]
Currently `Route::parse()` returns an array that contains `_matchedRoute` which is the string template for the route. What if instead it also returned `_matchingRoute` that contained the route object itself.

We might need to update the tests before making this change. Right now there are a *ton* of tests that would need to change in a tedious way. We might to add new assertions to the route test cases that allows for partial array matching and update the tests to use those. That will allow us to make a smaller change and we can dynamically generate the expected value of `_matchingRoute` using the existing `_matchedRoute` expected values.

**Comment by LordSimal** [comment]
Sorry but I am not that accustomed to the router logic/system (yet) 😅
