### ISSUE TITLE
Unwanted contain due to Translate Behavior

### ISSUE THREAD

**Issue by EricRKLS** [cakephp/cakephp#16167]
### Description

When fetching records from a table using a matching on a second table that has Translate Behavior, a contain of the second table is added to the query automatically.

For example:

**ProductsTable**
```php
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->belongsTo('Brands', [
            'foreignKey' => 'brand_id',
        ]);
        $this->addBehavior('Translate', [
            'fields' => ['name', 'description', 'slug', 'meta_title', 'meta_description'],
        ]);
    }
```

**BrandsTable**
```php
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->hasMany('Products', [
            'foreignKey' => 'brand_id',
        ]);
    }
```

**Query**
```php
$this->Brands->matching('Products', function ($q) {
    return $q->where(['Products.active' => 1]);
})->toArray();
```

**Expected behavior**
All Brands with active products are fetched with a single product in the matching data.

**Actual behavior**
All Brands with active products are fetched with a single product in the matching data and all products of the brands are contained.

This is unwanted and in my case causes a fatal error because of memory exhaustion. Disabling the Translate behavior on the ProductsTable before executing the query works but shouldn't be necessary in my opinion so it seems like a bug to me.

### CakePHP Version

4.2.9

### PHP Version

7.4

**Comment by Zemke** [comment]
I can't seem to reproduce this.

```
mysql> select * from products;
+----+--------+----------+--------+
| id | active | brand_id | name   |
+----+--------+----------+--------+
|  1 |      1 |        1 | first  |
|  2 |      0 |        1 | second |
|  3 |      0 |        2 | third  |
|  4 |      1 |        2 | fourth |
|  5 |      0 |        3 | fifth  |
|  6 |      1 |        1 | sixth  |
+----+--------+----------+--------+
```

```php
$this->Brands->find()->matching('Products', function ($q) {
    return $q->where(['Products.active' => 1]);
})->toArray();
```

in either case—with and without Translate behavior—returns 

```
2022-03-02 11:22:30 Debug: xxArray
(
    [0] => App\Model\Entity\Brand Object
        (
            [id] => 1
            [_matchingData] => Array
                (
                    [Products] => App\Model\Entity\Product Object
                        (
                            [id] => 1
                            [active] => 1
                            [brand_id] => 1
                            [name] => first
                        )
                )
        )

    [1] => App\Model\Entity\Brand Object
        (
            [id] => 2
            [_matchingData] => Array
                (
                    [Products] => App\Model\Entity\Product Object
                        (
                            [id] => 4
                            [active] => 1
                            [brand_id] => 2
                            [name] => fourth
                        )
                )
        )

    [2] => App\Model\Entity\Brand Object
        (
            [id] => 1
            [_matchingData] => Array
                (
                    [Products] => App\Model\Entity\Product Object
                        (
                            [id] => 6
                            [active] => 1
                            [brand_id] => 1
                            [name] => sixth
                        )
                )

        )
)
```

Check [Zemke/cake_iss](https://github.com/Zemke/cake_iss) for more. It has all the database migrations and seeds available to reproduce the scenario the way I think it was mean to be. Same Cake and PHP version as mentioned as well. Did I miss something?

I see you used `$this->Brands->matching` which doesn't seem to exist. Could that be a copy-paste error? I did `$this->Brands->find()->matching`. I also assume that [Eav Translation Strategy](https://book.cakephp.org/4/en/orm/behaviors/translate.html#eav-strategy) is used.

Edit: The translations are also available in `i18n.sql` in the root of the repo.

**Comment by markstory** [comment]
Thanks for taking the time to try and reproduce this @Zemke :bow:
