### ISSUE TITLE
ConsoleIntegrationTestTrait json arguments

### ISSUE THREAD

**Issue by nachitox** [cakephp/cakephp#16164]
### Description

When using the `ConsoleIntegrationTestTrait` with json arguments, the double quotes are removed and the json is invalidated.

```
$data = ["foo" => "faa"];
$this->exec('foo "' . json_encode($data) . '"');
```

where foo:

```
$this->out($this->args);
```

The shell output is:

```
/src/TestSuite/ConsoleIntegrationTestTrait.php (line 91)
########## DEBUG ##########
object(Cake\TestSuite\Stub\ConsoleOutput) {
	[protected] _out => [
		(int) 0 => '{foo:faa}'
	]

```

which is invalid json.

I'm no expert and I'm not sure exactly what the regexp is doing, but I use this code for a similar thing and seems to work well:

```
    protected function commandStringToArgs($command)
    {
        if (preg_match_all ('/(?<=^|\s)([\'"]?)(.+?)(?<!\\\\)\1(?=$|\s)/', $command, $ms))
            return $ms[2];

        return [];
    }
```

The same test outputs:

```
/src/TestSuite/ConsoleIntegrationTestTrait.php (line 91)
########## DEBUG ##########
object(Cake\TestSuite\Stub\ConsoleOutput) {
	[protected] _out => [
		(int) 0 => '{"foo":"faa"}'
	]
```

which is fine.

### CakePHP Version

3.9

**Comment by saeideng** [comment]
```php
$data = ["foo" => "faa"];
$string = 'foo "' . json_encode($data) . '"';
echo $string;
```
returns 
```
foo "{"foo":"faa"}"
```
you need to change your input style

**Comment by nachitox** [comment]
@saeideng sorry, I'm not sure how your comment is related to the issue.

**Comment by markstory** [comment]
@nachitox He is saying that the current concatenation you're creating results in a command that looks like

```
foo "{"foo":"faa"}"
```

Which isn't not a valid command line string. Have you tried.

```php
$data = ["foo" => "faa"];
$this->exec("foo '" . json_encode($data) . "'");
```
