### ISSUE TITLE
Inject the ServerRequest in the dependency container by default

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#16176]
### Description

Services will often have the server request as a dependency.

I would suggest to move [this line](https://github.com/cakephp/cakephp/blob/0dff8995ad617ec3f57b553d661061fbf447599a/src/Controller/ControllerFactory.php#L85) one line up, so we always have the server request injected into the services with a dependence on the server request.

```php
$this->container->add(ServerRequest::class, $request);
if ($this->container->has($className)) {
    $controller = $this->container->get($className);
} else {
    $controller = $reflection->newInstance($request);
}
```

This way I can for example simply write:
```php
public function services(ContainerInterface $container): void
  {
      $container
          ->add(UserRegisterServiceInterface::class, UserRegisterService::class)
          ->addArgument(ServerRequest::class);
}
```

My workaround so far is a Middleware1 placed first in the queue that sets the container in a request attribute, and a Middleware1000 placed as last in the queue and that injects the request processed by all other middlewares in the container injected in the request by Middleware1.
It works, it is not so elegant, and I think that injecting the server request in the container (if not already set) right before the controller is built is a really nice to have.

I can propose a PR if interest arises.

### CakePHP Version

4.4.0

**Comment by ADmad** [comment]
`BaseApplication::handle()` seems like a more appropriate place to add the request instance instance to the container instead of `ControllerFactory::create()`.
