### ISSUE TITLE
Mailer profiles: muitiple addresses in a single string

### ISSUE THREAD

**Issue by nishimura-d** [cakephp/cakephp#16182]
### Description

Want to configure like

```php
            'to' => 'addr1@an.example,addr2@an.example',
```

for the same meaning as:

```php
            'to' => ['addr1@an.example', 'addr2@an.example'],
```

This is useful in configuring with environment variables.

```php
            'to' => env('EMAIL_EXAMPLE_TO'),
```

We can configure with a DSN string, but it's hard to write.

```php
            'url' => 'mailto://?to[]=addr1%40an.example&to[]=addr2%40an.example',
```

I want this feature for keys which accepts multiple addresses: `to`, `cc`, `bcc` and `replyTo`.

**Comment by markstory** [comment]
> We can configure with a DSN string, but it's hard to write.

What is hard to write about the example you gave?

My concern with adding another string format is that `to` will work differently than all of the other methods that operate on address lists. Having all of those methods split on `,` could create unexpected behavior in existing applications where user data is being validated as a string and then used to send emails.

**Comment by dereuromark** [comment]
I also think this might be best handled through a custom user side convenience function like splitByComma(env(...))
which can then take this in and return an array.
Other users might want to pass a JSON string, here a json_decode might be useful, or others might use a different delimiter, like `;`.

So maybe this doesnt need to be part of the core.

**Comment by nishimura-d** [comment]
> What is hard to write about the example you gave?

- `[]` syntax
- percent encoding


> My concern with adding another string format is that `to` will work differently than all of the other methods that operate on address lists.

I'm not asking you to give special treatment to just `to`.
The same is true for `cc`, `bcc` and `replyTo`, which handle address lists.


> Having all of those methods split on `,` could create unexpected behavior in existing applications where user data is being validated as a string and then used to send emails.

Yes, it may affect applications using `emailPattern` which allows `,`.
Default `EMAIL_PATTERN` doesn't allow `,`.
And RFC 5322 allows `,` only in quoted strings (applications may handle this with `emailPattern`, this is concern), and uses `,` as separator of address list.


> I also think this might be best handled through a custom user side convenience function like splitByComma(env(...)) which can then take this in and return an array. Other users might want to pass a JSON string, here a json_decode might be useful, or others might use a different delimiter, like `;`.

OK, but `,` is a standard delimiter for address lists, so I think many people will use it.

For me, it is enough to know the policy of the project.
Is it correct that we should use the DSN string or otherwise deal with it in the application?

**Comment by markstory** [comment]
>  Is it correct that we should use the DSN string or otherwise deal with it in the application?

Given that there is already a way to do lists in the environment variable, I'm reluctant to add another way to do it. I'm also concerned that transforming strings with `,` in them to lists will have adverse effects in existing and future applications. The example you gave of 

```php
'to' => env('EMAIL_EXAMPLE_TO'),
``` 

could become

```php
'to' => explode(',', env('EMAIL_EXAMPLE_TO')),
```

and do what you want without needing to add a helper function :smile:

**Comment by nishimura-d** [comment]
> ```
> 'to' => explode(',', env('EMAIL_EXAMPLE_TO')),
> ```
> 
> and do what you want without needing to add a helper function 😄

Yes, we write that in many applications.
In real:

```php
            'to' => array_filter(array_map('trim', explode(',', env('EMAIL_EXAMPLE_TO', '')))),
```

I just want to simplify this.

**Comment by ADmad** [comment]
I too am not in favour of adding support for a comma separated list for `to` and similar configs.

> array_filter(array_map('trim', explode(',', env('EMAIL_EXAMPLE_TO', ''))))

You can just create your own function for the above to avoid code reputation and use wherever needed.

**Comment by nishimura-d** [comment]
Hmm.
How about adding support for a comma separated list to mailer DSN string only?
Is it also unacceptable?

```php
            'url' => 'mailto://?to=addr1%40an.example,addr2%40an.example',
```
