### ISSUE TITLE
BufferedStatement::fetchAll() does not match PDOStatement behavior

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16208]
### Description

`PDOStatement::fetchAll()` returns the "remaining" rows in the result set. If you fetch a single row before calling `fetchAll()`, it will return the rows after that first row.

The statement wrappers that return `PDOStatement::fetchAll()` will have this behavior but `BufferedStatement` returns the entire result set every time.

Most of the time, `BufferedStatement` is attached internally and is not a switch configurable by the user.

### CakePHP Version

4.3

**Comment by othercorey** [comment]
It's not great to leave this in, but most users aren't going to run into this. Since it's existing behavior, planning to change in 5.0.

**Comment by markstory** [comment]
> The statement wrappers that return PDOStatement::fetchAll() will have this behavior but BufferedStatement returns the entire result set every time.

Isn't that part of how the buffering statement needs to work though? The main benefit that BufferedStatement provides is that it returns the entire result set? Are you proposing that we track the internal offset better and return the 'rest' of the result set if the offset is > 0?

**Comment by othercorey** [comment]
This is an inconsistency issue. The default implementation is a wrapper around PDOStatement which works one way. If the user happens to get a BufferedStatement somewhere in the chain, it changes the behavior. They don't really know which version they're getting.

We are clearly wrapping PDOStatement, so trying to match documented behavior would be nice. However, with a combined implementation, we could more easily document the behavior change and make it consistent no matter what query the user executes.

Making it work one way or the other isn't too difficult This defect is calling out the problem with nested statements.

**Comment by markstory** [comment]
They don't really know which version they're getting. I didn't fully grasp it the first time around.

> They don't really know which version they're getting.

This is the crux of the issue to me. The unpredictability of the Statement object which should be a simple proxy/decorator now changes very basic behaviors.

> Making it work one way or the other isn't too difficult This defect is calling out the problem with nested statements.

:+1: I think we should at least try to emulate `PDOStatement` better. It doesn't seem that complex right now.

**Comment by othercorey** [comment]
Not sure we want to change this for 4.x.

**Comment by ADmad** [comment]
Closed by #16268
