### ISSUE TITLE
BufferedStatement::rowCount() does not match PDOStatement: behavior

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16214]
### Description

`PDOStatement::rowCount()` returns the number of rows modified by a query - typically only INSERT, UPDATE and DELETE. The number of rows returned by SELECT queries is not usually returned.

We document rowCount()  with a SELECT query example, but the default implementation is just a wrapper for `PDOStatement::rowCount()`.

`BufferedStatement` changes the implementation to return the number of rows returned by the query for all queries. This means that INSERT, UPDATE and DELETE queries will only show number of rows returned instead of affected rows.

### CakePHP Version

4.3.0

**Comment by othercorey** [comment]
This isn't exactly the bug. The actual bug is logged already.

**Comment by ADmad** [comment]
Closed by #16268
