### ISSUE TITLE
Mailer->viewBuilder()->setLayout(null) doesn't work

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16229]
### Description

When i set up a fresh installation of CakePHP, remove `/templates/layout/email/html/default.php` and add the following code to AppController.php ...

```
use Cake\Mailer\Mailer;

// inside initialize()
$mailer = new Mailer();
$mailer
    ->setEmailFormat('html')
    ->setTo('bob@example.com')
    ->setFrom('app@domain.com')
    ->viewBuilder()
        ->setTemplate('default')
        ->setLayout(null);

$mailer->deliver();
```

... I get a `MissingLayoutException` telling me to create a `/templates/layout/email/html/default.php` file. However, I want to send the email without a layout, hence the `->setLayout(null)`.

I think the problem is caused by the `isset()` in `View::__construct()` ...

```
foreach ($this->_passedVars as $var) {
    if (isset($viewOptions[$var])) {
        $this->{$var} = $viewOptions[$var];
    }
}
```

... which isn't satisfied by `NULL`, therefore the default layout of the `View` class is used. `array_key_exists($var, $viewOptions)` could be an option to solve this, however, not sure if it might cause any unwanted side effects?

### CakePHP Version

4.3.3

### PHP Version

7.4

**Comment by dereuromark** [comment]
It used to be false in previous versions, with the type strictness this might have become an empty string to signal "no layout".-

    ->setLayout('');

Maybe try that - as null just means not defined (or take default one).

**Comment by gerhard-lechner** [comment]
Thanks for the immediate response!

Setting an empty string produces the error `View::$layout must be a non-empty string. To disable layout rendering use method View::disableAutoLayout() instead.`.

This pointed me in the right direction though. Using `disableAutoLayout()` instead of `setLayout(null)` works. In this case, the docs at https://book.cakephp.org/4/en/core-libraries/email.html > `Configuration Profiles` aren't correct:

- `'layout'`: If you are using rendered content, set the layout to render. If you want to render a template without layout, **set this field to null**. See `ViewBuilder::setTemplate()`.

**Comment by ADmad** [comment]
@gerhard-lechner You can use the edit (pencil) icon on the right side of the screen to submit a fix to the docs :)

**Comment by gerhard-lechner** [comment]
Thanks ADmad, I'll check it out! I think the cleanest way would be to add the key `'autoLayout'` to the email configuration like so:

- `'layout'`: If you are using rendered content, set the layout to render. See `ViewBuilder::setTemplate()`.
- `'autoLayout'`: If you want to render a template without layout, set this field to false. See `ViewBuilder::disableAutoLayout()`.

In order for the email configuration to work, this would need a fix in the code though. I think the following code needs to be added in Mailer::setProfile()

```
if (array_key_exists('autoLayout', $config)) {
    if ($config['autoLayout'] === false) {
        $this->viewBuilder()->disableAutoLayout();
    }
    unset($config['autoLayout']);
}
```

**Comment by ADmad** [comment]
@gerhard-lechner That sounds good, would you like to submit a patch?

**Comment by gerhard-lechner** [comment]
I created a pull request with the updated code as well as a PR to update the docs, both on 4.next branch. I'm not really experienced when it comes to writing tests, so I didn't add any tests - pls bear with me.

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/cakephp/pull/16230
