### ISSUE TITLE
RFC: Add ability to log events on() and off() calls

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16225]
### Description

Debugging events can be quite troublesome since event listeners can be rather easily added/removed anywhere in your code.

Therefore having an e.g. `events.log` which contains all the `->on()` and `->off()` calls (or maybe even the `->dispatch()` calls) including the callstack of each one would be a usefull for debugging event system related problems.

I thought this could be 
- depending on the `debug mode` being on **AND**
- an extra `App.log_events` config key (or somewhere else)

What are your thoughts about that?

### CakePHP Version

4.4

**Comment by LordSimal** [comment]
Well, I was a bad dev and didn't check already discussed issues.

This has already been discussed in the past but has been auto-closed by the github actions in https://github.com/cakephp/cakephp/issues/12909

**Comment by LordSimal** [comment]
Well #12909 already has a working example of how the `dispatch()` function can be adapted to log 

- event names + its origin and
- all listeners which are being executed at that moment

But it would also be nice to see when listeneres are being either added or removed from the event manager.
I guess these log infos should also be placed inside an extra log file?

**Comment by markstory** [comment]
If we do add logging it would be good to cover off the scenarios described in #12909? Some options that come to mind are:

* Configuration like you've mentioned. Having `EventManager` read that configuration value on each event call could add a non-trivial amount of overhead.
* A setter method that works like `EventManager::trackEvents()`. This will be a bit harder to make into a global option as the global manager and the instances in controllers/tables.
