### ISSUE TITLE
CakePHP3 query object returns wrong value

### ISSUE THREAD

**Issue by sanjeevdivekar** [cakephp/cakephp#16234]
### Description

Query object return avg rating is 3 instead of 3.5, when I have 4 and 3 values for ratings in the table

```
        $query = $Comments->find()
            ->select(['rating'=>'AVG(rating)'])
            ->first();
```

### CakePHP Version

3.8.13

### PHP Version

7.4.27

**Comment by ADmad** [comment]
Your `rating` field is of integer type hence the value gets typecast to integer. Use another alias like `'avg_rating'=>'AVG(rating)'` to avoid the type casting.

**Comment by markstory** [comment]
Another option is to overwrite the type for the select.

```php
$query->select(['rating' => 'avg(rating)'], ['rating' => 'float'])
```

**Comment by othercorey** [comment]
> Another option is to overwrite the type for the select.
> 
> ```
> $query->select(['rating' => 'avg(rating)'], ['rating' => 'float'])
> ```

I don't believe that's a valid signature for select().

**Comment by markstory** [comment]
> I don't believe that's a valid signature for select().

You're right. I was thinking of the expression APIs that do that.

```php
$avg = $query->func()->avg('rating');
$query->select(['rating' => $avg])
```

By using the expression object to make your function call you should get the correct output data.
