### ISSUE TITLE
Empty string in database instead of NULL

### ISSUE THREAD

**Issue by a-d-w-s** [cakephp/cakephp#16231]
### Description

If I enter a value from a field that is empty via a form, an entry with an empty string is stored in the database.
Could it be NULL instead?

Thank You

**Comment by othercorey** [comment]
Please use the slack or discord channels to discuss this first.

**Comment by LordSimal** [comment]
There is already a thread open in our discourse forum where shadowx-jb asked this question again.
Therefore I will close this issue since the support will go on there.

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/cakephp/issues/15450 etc
