### ISSUE TITLE
Allow multiple aliases for the same command

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#16238]
### Description

In a plugin I have:

```php
    public function console($commands): CommandCollection
    {
        // Alias old command for retro compatibility
        $commands->add('old_command', MyNewCommandCommand::class);
        $commands->add('my_new_command', MyNewCommandCommand::class);

        return $commands;
    }
```

Because of [this line](https://github.com/cakephp/cakephp/blob/4.x/src/Console/Command/HelpCommand.php#L110), only the shortest of the two  commands will be displayed in the `HelpCommand`, when running `bin/cake`.

What is the motivation behind keeping only one of the two? And why keeping only the shortest one?

I would suggest either displaying both, or at least keeping the latest one loaded, here `my_new_command`.

### CakePHP Version

4.4

**Comment by dereuromark** [comment]
For Display it is counterproductive to Show both. At least without verbose Mode.
The list is already cluttered and less helpful as it once was.

**Comment by ADmad** [comment]
If someone wants to have multiple aliases for their app commands then let them have the slightly longer list. It's going to be quite uncommon in any case.

**Comment by markstory** [comment]
Hiding the 'long' alias was done to prevent all plugin commands from showing up twice. When plugin commands are added they get both a short alias `cake migrations` and a long one `cake migrations.migrations` added [^1].

[^1]: https://github.com/cakephp/cakephp/blob/4.x/src/Console/CommandCollection.php#L166-L177
