### ISSUE TITLE
ConsoleIo can cause system error "Too many open files"

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#16259]
### Description

The `ConsoleIo` class has the potential to create too many open files by opening new file handles for `stdin`, `stderr`, and `stdout`. That's my theory anyway, maybe I'm wrong.  This is not something that is likely to happen under normal usage of the `Command/Console` system as far as I can tell, so it's probably a bit of an edge case.

One way it can happen, and how I encountered it is the following:
- if you call `Command::executeCommand()` to execute a sub command from a command
- you are doing this inside a loop/iteration say hundreds or thousands of times
- you do not explicitly pass the parent command's `ConsoleIo` to the `executeCommand()` call. It is an optional 3rd argument.

On the one hand, a solution is to just not do this. Or to pass the parent `ConsoleIo` to the `executeCommand()` call.  So maybe the solution here is just to add a warning in the documentation in this area?

I am mentioning it only because it was very easy for me to create this situation, and not immediately clear why the error was happening.

Some possible solutions might be:
- Add a `__destruct()` to the `ConsoleIo` that closes the filehandles?
- Use a singleton pattern (this might be considered an anti-pattern and might be a headache)
- Require that `ConsoleIo` is always passed instead of allowing it to be null in `executeCommand` and creating a new instance of it (this is obviously a breaking change)

I did not have time to dig into this more than at a surface level so far, but I just wanted to jot the issue down in case you all think it's worth fixing or if it's such an edge-case that a simple warning in the docs would suffice.

I encountered this in 3.8 but at first glance it looks like it would be possible in 4.x as well.

### CakePHP Version

3.8.13

### PHP Version

7.4.26

**Comment by kevinquinnyo** [comment]
Possibly related: https://github.com/cakephp/cakephp/issues/12255

**Comment by markstory** [comment]
> On the one hand, a solution is to just not do this. Or to pass the parent ConsoleIo to the executeCommand() call. So maybe the solution here is just to add a warning in the documentation in this area?

If you're calling `executeCommand()` thousands of times you'll need to pass the ConsoleIo in. Adding a note to the documentation on how to do this is a great idea.

> Require that ConsoleIo is always passed instead of allowing it to be null in executeCommand and creating a new instance of it (this is obviously a breaking change)

Yeah we're not going to introduce a breaking change for this.

> Add a __destruct() to the ConsoleIo that closes the filehandles?

This might work. We would have to make sure that closing one file handle doesn't close the stream for other instances.

> Use a singleton pattern (this might be considered an anti-pattern and might be a headache)

We could default the out/err/in to the current commands instances if the options are undefined. That would give you the benefits of a singleton without using a singleton pattern. It would also be backwards compatible.

**Comment by kevinquinnyo** [comment]
> We could default the out/err/in to the current commands instances if the options are undefined. That would give you the benefits of a singleton without using a singleton pattern. It would also be backwards compatible.

The only problem I see with this approach is that currently, the `ConsoleIo` is never really set as a property on `BaseCommand` or `Command`. It's simply passed to `run()`.

A solution might be to add a `__construct()` (or in the existing `initialize()`?) on the abstract `BaseCommand`, and initialize with some kind of:
```php
if (!$this->defaultIo) {
    $this->defaultIo = new ConsoleIo();
}
```

Then in `executeCommand()`:
```diff
- $io = $io ?: new ConsoleIo();
+ $io = $io ?: $this->defaultIo;
```

Another solution might be something like:
```diff
- $io = $io ?: new ConsoleIo();
+ $io = $io ?: $this->getConsoleIoInstance();
```

```php
// docblock should make note of why this exists since it might be confusing
private function getConsoleIoInstance(): ConsoleIo
{
    if (!$this->defaultIo) {
        $this->defaultIo = new ConsoleIo();
    }

    return $this->defaultIo;
}
```

It seems the only time that maintaining state on a command for the `ConsoleIo` is needed in this specific case, where a command executes another command.

Or maybe there's another way and I'm missing something.  Also happy to just leave this alone and rely on the documentation recently added about this edge-case usage.  This was just something on my to-do list to look into this weekend so I took a look this morning.

**Comment by othercorey** [comment]
Closing since we don't think this worth changing with the existing work around now documented. We'd have to re-think how ConsoleIo is shared in a future version.
