### ISSUE TITLE
[cakephp/http] Auth adapters can't be used

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#16258]
### Description

Using `cakephp/http` standalone, with any auth adapter, currently doesn't work without setting `App.namespace` during bootstrap.

```
PHP Fatal error:  Uncaught TypeError: rtrim() expects parameter 1 to be string, null given in vendor/cakephp/core/App.php:63
```

We could either add a fallback in https://github.com/cakephp/cakephp/blob/4.x/src/Core/App.php#L62 to `App` or check for a null `$base` value before applying `rtrim`.

### CakePHP Version

4.3.4

### PHP Version

7.4

**Comment by markstory** [comment]
I think checking for the null will be safer than adding a fallback. Having a null namespace should be ~= to using no namespace.
