### ISSUE TITLE
Allow empty string as value for FormHelper::checkbox()'s hiddenField

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16254]
### Description

I was wondering if there's a reason that in `FormHelper::checkbox()` and `FormHelper::radio()` (and also `select()` and `multiCheckbox()`) the check for `hiddenField` looks like ...

```
if ($options['hiddenField']) {
```

... and not like ...

```
if ($options['hiddenField'] !== false) {
```

The odd thing about this is that the default value for radios is an empty string, however, it's not possible to have checkboxes with the same value (default value is `0`) as the `if`-check in the helper methods obviously isn't fulfilled by `''`. Hence when setting it to an empty string for `FormHelper::checkbox()`, no hidden field is rendered at all which feels like a somewhat unexpected behaviour to me.

### CakePHP Version

4.3

**Comment by markstory** [comment]
The `hiddenField` option is documented as a boolean, that's why we're using it as a boolean. What problem are you running into with the current behavior?

**Comment by gerhard-lechner** [comment]
You're right @markstory , that's what the comment of `FormHelper::checkbox()` says:

```
* - `hiddenField` - boolean to indicate if you want the results of checkbox() to include
*    a hidden input with a value of ''.
```

However, the comment is wrong in terms of the mentioned value, which in fact is `0` instead of `''`.

Furthermore, based on the actual code of `FormHelper::checkbox()`, it's absolutely possible to set a desired string value for the `hiddenField`:

```
$output = '';
if ($options['hiddenField']) {
    $hiddenOptions = [
        'name' => $options['name'],
        'value' =>
            $options['hiddenField'] !== true && $options['hiddenField'] !== '_split'
                ? $options['hiddenField'] // <-------------------- see here
                : '0',
        'form' => $options['form'] ?? null,
        'secure' => false,
    ];
    if (isset($options['disabled']) && $options['disabled']) {
        $hiddenOptions['disabled'] = 'disabled';
    }
    $output = $this->hidden($fieldName, $hiddenOptions);
}
```

So I **can** create a checkbox with values of `yes` (active) and `no` (inactive), but i **cannot** create one with `1` and `''` which is what I actually want to achieve.

I don't see a reason why this use case shouldn't be possible, hence I would argue that the documentation of `hiddenField` should be updated and state that it can either be a boolean or a string (which is in fact already the case!) and the method itself should then also support empty strings by applying the minor change suggested in my initial post.

**Comment by markstory** [comment]
The `_split` string had me intrigued as I haven't looked at these methods in a few years, and that is a curious looking value. This feature is used as a hack for `input()` to get the hidden input and checkbox separately so they can be templated independently. This behavior was introduced in https://github.com/cakephp/cakephp/pull/5099. However, the hiddenField being a string goes back quite a while in https://github.com/cakephp/cakephp/commit/5225fe2b5c8cf1f24b044998aeff7e32ace62793

In anycase, looks like we've supported string values for a really long time (since 2.1.0!) and the documentation is just wrong. I also see no reason why `''` can't be a valid value.
