### ISSUE TITLE
Support arrays for $type in Table::find() and Query::find()

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16263]
### Description

I'm curious if there's a specific reason why the `Table::find()` and `Query::find()` methods require the `$type` to be a string. I find finders very handy to use so I have quite a few of them. However, writing queries like ...

```
$this->Users->find('finder1')->find('finder2')->all();
```

... seems overly complicated in more complex scenarios.

Of course I can create a new finder `finder1And2` which combines whatever `finder1` and `finder2` are doing and just use this finder in the Query. However, that's a workaround which creates unnecessary code and complexity, especially if you don't have only two but multiple finders to combine.

I think a great option would be to just write a query like ...

```
$this->Users->find(['finder1', 'finder2'])->all();
```

... and internally the `find()` methods just loop through these if `is_array($type)` (more specifically I think `Table::callFinder()` is where this would actually need to happen?). What do you think? Does this make sense?

### CakePHP Version

4.4

**Comment by dereuromark** [comment]
This will unnecessarily increase internal complexity IMO.
All finders can accept an array of options to pass along into the protected methods.
Using an array means we either
- have to introspect both key and value each time and as per those types define how to handle the delegation of the options.
- pass the same options to all finders

I am not sure the cons here are outweighed by your "pros" that are mentioned above.

**Comment by dereuromark** [comment]
Example: Geo plugin and
```php
// In a controller action
$options = ['lat' => 13.3, 'lng' => 19.2, 'distance' => 200];

$query = $this->Addresses->find('distance', $options);
```
and
```php
public function findDistance(Query $query, array $options) {}
```
No other finder would need those keys of the options.
And in case if different finders need the same key with different values, you have yet an even bigger issue at hand.
How would that case be solved using the combined method?

**Comment by gerhard-lechner** [comment]
Thanks for your inputs.

I'm hardly ever using finders with parameters, hence I didn't consider this additional complexity. My main use case is to not type the same conditions over and over again. For example, to only get users that are active I'd write `$this->Users->find('active')` instead of `$this->Users->find()->where(['Users.active' => 1])`. And of course, using multiple of these finders results in something like `$this->Users->find('active')->find('admin')->find('whatever')->all()`.

With that being said, I'd be fine to not support any parameters if `$type` is an array. But of course that's not a great solution in general. However, I think the issue with the parameters would be solvable like this:

```
$this->Users->find(['finder1', 'finder2', 'distance' => ['lat' => 13.3, 'lng' => 19.2, 'distance' => 200]])->all();
```

The finders have to be looped through anyway, so if the loop looks something like ...

```
foreach ($type as $finder) {
    $query->find($finder);
}
```

... or rather like ...

```
foreach ($type as $key => $value) {
    if (!is_numeric($key)) {
        $query->find($key, $value);
    } else {
        $query->find($value);
    }
}
```

... probably doesn't make too much of a difference. Of course it's more complex when properly implemented, but you get idea.

I'd agree that when using overly complex finders it doesn't make too much sense in general, but I'd argue there are countless cases where you just have very simplistic finders without any parameters as in my example above and where it actually makes a lot of sense.

**Comment by markstory** [comment]
I'm not a fan of this change as it makes parameterized finders more complicated to use and adds edge cases where finders share parameters. It will not only add complexity to `Table` but also `Orm\Query` and all the association code which would also need to change. Making multiple finders work consistently across the ORM will add complexity to several places.

Personally, I find the array format to be harder to read than multiple calls to find() are. While I get that typing find() multiple times can be tedious, have you explored making 'higher level finders'? Something like

```php
public function findActiveAdmin(Query $query, array $options): Query
{
    return $query->find('active')->find('admin');
}
```

This allows you to bundle up finders that are commonly used together.

**Comment by dereuromark** [comment]
Also, for any string input here you can get autocomplete from the IDE using meta (e.g. in PHPStorm using IdeHelper plugin).
This way you are faster than with arrays for sure, as well.
See https://github.com/dereuromark/cakephp-ide-helper/blob/master/docs/Generator.md#tablefinders

**Comment by gerhard-lechner** [comment]
Thanks for the suggestion @markstory ... I do know that I can just create more finders that combine things. However, if you have 4 or 5 ones with various combinations it becomes somewhat bloated. But if my idea doesn't make sense in a wider perspective, that's okay of course.

However, I think the changes needed are actually much less complex than one might think as both, `Table::find()` and `Query::find()`, are using `Table::callFinder()`.

I got a working draft by just editing a few lines of code in `\Cake\ORM\Table`. I changed ...

```
public function callFinder(string $type, Query $query, array $options = []): Query
{
    [some code in here]
}
```

... to ...

```
public function callFinder($type, Query $query, array $options = []): Query
{
    if (!is_array($type)) {
        return $this->_callFinder($type, $query, $options);
    }

    foreach ($type as $key => $value) {
        if (!is_numeric($key)) {
            $query = $this->_callFinder($key, $query, $value);
        } else {
            $query = $this->_callFinder($value, $query, []);
        }
    }

    return $query;
}

protected function _callFinder(string $type, Query $query, array $options): Query
{
    [all the code of original callFinder()]
}
```

... and of course changed `string $type = 'all'` to `$type = 'all'` in `Table::find()` and `Query::find()`.

So I'm not sure if it's really super complex, but of course you are the experts here. As I said, if you just don't like the idea, that's okay too.

**Comment by ADmad** [comment]
I too am not in favour of allowing finder name arrays for reasons stated by markstory and dereuromark.

Hence closing the issue.

**Comment by dereuromark** [comment]
@gerhard-lechner That said, you can always create your own custom finder here on Table level, either app or plugin based.
e.g. findCustom() with string|array input.
This one could exactly do that as per your suggestion.

If you publish this as a plugin extension, also other people who find it useful can use it.

**Comment by gerhard-lechner** [comment]
Thank you for the suggestion @dereuromark , I'll definitely consider that!
