### ISSUE TITLE
Make it easier to override translation functions 

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#16265]
### Description

It is impossible to override __d() function because the file is autoloaded by composer before any other files are loaded in the project.

My idea was to use [gettext](https://www.php.net/manual/en/function.gettext.php) for translations. I also tried to create my own translator as described in the [cookbook](https://book.cakephp.org/3/en/core-libraries/internationalization-and-localization.html#creating-your-own-translators) but it does not work because the translator (instance of Package) does not have access to the translation domain name that is necessary for gettext:
```
textdomain($domain);
return gettext($message);
```
I think there should be some way to access the domain value from the translator class.

### CakePHP Version

3.x

**Comment by ADmad** [comment]
Instead of `I18n::setTranslator()` you can use `I18n::config()` to register loaders for new translators. The loader callable receives the domain name and locale as arguments. 

https://book.cakephp.org/3/en/core-libraries/internationalization-and-localization.html#creating-generic-translators

**Comment by bancer** [comment]
What I tried so far:

```
<?php

declare(strict_types=1);

namespace App\Test\TestCase\I18n;

use App\I18n\GettextTranslator;
use Cake\I18n\I18n;

class GettextTranslatorTest extends TestCase
{
    public function testGetTranslator()
    {
        $domain = 'frontend';
        $loader = function() {
            return new GettextTranslator('default');
        };
        I18n::clear();
        I18n::setTranslator($domain, $loader, 'ru_RU');
        $actual = I18n::getTranslator($domain, 'ru_RU');
        $translation = $actual->translate('No');
        $this->assertEquals('Нет', $translation);
    }
}
```

```
<?php

declare(strict_types=1);

namespace App\I18n;

use Aura\Intl\Package;

class GettextTranslator extends Package
{
    public function getMessage($key)
    {
        debug($key);
        // translation domain is needed but not accessible here!
        return false;
    }
}
```

@ADmad it does not look like using I18n::config() will fix my problem. I do not want to load all translations at once. What I want to achieve is that only one translation would be retrieved from PO file when `__d(...)` is called. I do not want CakePHP to keep thousands of translations in memory and in cache. I want to use the native caching implemented by gettext. It looks like the natural way to achieve that is to override `getMessage()` method but the domain name is not accessible there.

**Comment by ADmad** [comment]
Well then you will have to simply bypass the use of translators and override the `__*()` functions with your own.

Now due to limitation of composer you'll need to to use a package linked [here](https://github.com/composer/composer/issues/6768#issuecomment-1023823862) or simply include the file containing your own translation function before including composer's autoload files in `webroot/index.php`.

**Comment by garas** [comment]
You could add new property `$domain` to `GettextTranslator` and set it when creating new `GettextTranslator` object.

**Comment by bancer** [comment]
The problem I stumbled is that the path to po files used by CakePHP is not compatible with gettext paths.
Cake path: src/Locale/de_DE/frontend.po
Gettext path: src/Locale/de_DE/LC_MESSAGES/frontend.po
So I wonder whether it would be possible to add some configuration variable or function that would add LC_MESSAGES folder to the translation paths so that it would be possible to quickly switch between gettext implementation and CakePHP implementation without removing LC_MESSAGES folder. Something like `I18n:configPaths('Locale/{locale regex}/LC_MESSAGES/{*.po}');`.

**Comment by bancer** [comment]
Still needed.

**Comment by bancer** [comment]
Still needed.

**Comment by markstory** [comment]
This came up in my notifications again - thanks stalebot. Would passing the domain to the loader function help here?

```php
declare(strict_types=1);

namespace App\Test\TestCase\I18n;

use App\I18n\GettextTranslator;
use Cake\I18n\I18n;

class GettextTranslatorTest extends TestCase
{
    public function testGetTranslator()
    {
        $loader = function($name) {
            // Pass the domain into your message loader.
            return new GettextTranslator($name, 'default');
        };
        I18n::clear();
        I18n::setTranslator('frontend', $loader, 'ru_RU');
        $actual = I18n::getTranslator($domain, 'ru_RU');
        $translation = $actual->translate('No');
        $this->assertEquals('Нет', $translation);
    }
```

This doesn't work yet, but is a simple change that we could make to help with this use case.

> So I wonder whether it would be possible to add some configuration variable or function that would add LC_MESSAGES folder to the translation paths so that it would be possible to quickly switch between gettext implementation and CakePHP implementation without removing LC_MESSAGES folder.

Isn't this the responsibility of the custom message loader callback you're defining? If you need to load different message package from different paths a custom loader is how you would go about doing that.

**Comment by bancer** [comment]
> Would passing the domain to the loader function help here?

I am not sure that I fully understand your idea but if this would make the domain available inside getMessage() function then that could be a possible way to go.

```
class GettextTranslator extends Package
{
    public function getMessage($key)
    {
        debug($key);
        // translation domain is needed but not accessible here!
        return false;
    }
}
```

> Isn't this the responsibility of the custom message loader callback you're defining? If you need to load different message package from different paths a custom loader is how you would go about doing that.

My point is to make it possible to quickly switch between Gettext and CakePHP implementations back and forth without moving or renaming the folders with translation files. So that the same files and paths would be used in both implementations.

**Comment by bancer** [comment]
Let's say both 'frontend' and 'backend' domains would use GettextTranslator. How would GettextTranslator know what domain to use inside `getMessage()` function when calls to `__d('frontend', 'Price')` and `__d('backend', 'Amount')` are executed? Would that mean that different instances of GettextTranslator would be invoked for 'frontend' and 'backend' domains?

**Comment by markstory** [comment]
> I am not sure that I fully understand your idea but if this would make the domain available inside getMessage()

The suggestion I had was to pass the domain in to the loader function so that it could be passed into your package's constructor/setter methods. This wouldn't change the signature of `getMessage()` but because each domain == separate package instance you could have the domain available to the translation package.

> My point is to make it possible to quickly switch between Gettext and CakePHP implementations back and forth without moving or renaming the folders with translation files. So that the same files and paths would be used in both implementations.

That would require custom message loading, which you can do inside your custom package class.

**Comment by bancer** [comment]
> ... because each domain == separate package instance...

Sounds like this might work.

> That would require custom message loading, which you can do inside your custom package class.

Maybe I was not clear enough about this. "My point is to make it possible to quickly switch between Gettext and CakePHP implementations **back and forth** ...". I mean it should be possible to switch from Gettext to CakePHP implementation in such a way that CakePHP implementation would use the same paths pattern as gettext, e.g. "src/Locale/de_DE/LC_MESSAGES/frontend.po". Custom package class cannot do that as it does not control what paths are used by CakePHP implementation as they are not configurable now. In other words, there should be a way to configure CakePHP implementation so that it would use "src/Locale/de_DE/LC_MESSAGES/frontend.po" path instead "src/Locale/de_DE/frontend.po" what is not possible now.

**Comment by markstory** [comment]
Yes paths are not configurable in the base package class. If you need custom path resolutions, you need a custom package class.

**Comment by bancer** [comment]
One point that have not been mentioned: when I will switch to gettext implementation I would expect `cake i18n` shell still work and generate pot files into gettext compatible paths like "src/Locale/de_DE/LC_MESSAGES".

**Comment by bancer** [comment]
> ... generate pot files into gettext compatible paths like "src/Locale/de_DE/LC_MESSAGES".

My bad. POT files are not locale dependent. I meant "src/Locale" as it is now.

**Comment by dereuromark** [comment]
Is there anything to be done here still? Or are current ways enough?

**Comment by bancer** [comment]
> Or are current ways enough?

Not enough in my opinion. A way to configure the paths to po files is not available.

**Comment by ADmad** [comment]
In Cake 5 all global functions are loaded through the app's [bootstrap](https://github.com/cakephp/app/blob/9a7f511ed5f10dac993051cb1ecad79ab7cc93e5/config/bootstrap.php#L50) file. So one can declare their own before before that.

**Comment by bancer** [comment]
@ADmad would it be possible to backport this to 4.x?

**Comment by ADmad** [comment]
It's possible but not probable as we don't intend to make any changes to 4.x except bug/security fixes.
