### ISSUE TITLE
5.0 - Database & ORM package changes

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#16267]
- [x] Drop `StatementInterface::count()` and stop using `StatmentInterface::rowCount()` for `SELECT` queries. 
      #16255
      #16264
- [x] Change return type of `SteatmentInterface::fetchAll()`.
      #16274
- [x] Change argument type for `QueryTrait::_decorateResults()` to `ResultSetInterface`.
      #16282
- [x] Drop `BufferredStatement` and results buffering feature.
- [x] Drop decorator pattern for statements and loop over a list of decorator callbacks instead. (Drop `CallbackStatment`)
       #16264 
       #16301
- [ ] Adding deprecation warnings to methods which deal with results buffering where possible in 4.x.
      - Database\Query\enableBufferedResults() and related methods
      - ORM\Query::count()

**Comment by markstory** [comment]
> Change argument type for QueryTrait::_decorateResults() to array. Having it as Traversable doesn't seem necessary.

Are we also changing the return type of `QueryTrait::_execute()` which passes in a `ResultSetInterface`

https://github.com/cakephp/cakephp/blob/aa1b4df1d75156d43e71dbfb027ed0a7d7337a95/src/Datasource/QueryTrait.php#L287

> Drop BufferredStatement and results buffering feature.

Isn't this more removing streaming results? Buffered results were on by default before and now we're effectively buffering results by converting them to an array up-front. This removes the ability to do `SELECT * FROM reddit_comments` and work with the entire dataset if it didn't fit into PHP memory. I'm ok with that being removed as pagination is something people should be doing anyways. But I think it would be better for users if we communicated what is being changed.

**Comment by ADmad** [comment]
> Are we also changing the return type of QueryTrait::_execute() which passes in a ResultSetInterface

Ah, so that's why `Traversable` is needed. I will have a look at it again and drop this point in that case.

**Comment by ADmad** [comment]
@markstory So actually that point should be "change Traversable to ResultSetInterface" (not change to array) since return type of QueryTrait::_execute() is ResultSetInterface.

**Comment by ADmad** [comment]
Umm.. so it's seem it's the following piece of code which requires the argument type to be a `Traversable`. It's to accommodate the fact that `$this->_results` could be any traversable?

The only code that sets `$this->_results` is `QueryTrait::setResult()` who's argument type is `iterable`. So the argument type of `QueryTrait::_decorateResults()` should also be `iterable`. Plus we need additional test for `setResult()` using an array as argument.

https://github.com/cakephp/cakephp/blob/ec36b4c0b17fed7f178eea017d18d12327504087/src/ORM/Query.php#L1128-L1133

**Comment by ADmad** [comment]
Then again we have this

https://github.com/cakephp/cakephp/blob/ec36b4c0b17fed7f178eea017d18d12327504087/src/Datasource/QueryTrait.php#L276-L280

So if `$this->_results` is not a `ResultSet` instance there would be a type error.

**Comment by markstory** [comment]
Oh my. What a mess if types that is. Given that no one has opened an issue about TypeErrors from `all()` I think it should be safe to align types on ResultSetInterface.

**Comment by othercorey** [comment]
Marked the CallbackStatement item done.

**Comment by othercorey** [comment]
I mentioned this on discord, but for the issue:

> Adding deprecation warnings to methods which deal with results buffering where possible in 4.x.
> Database\Query\enableBufferedResults() 

I prefer we document the behavior change of buffering in the migration guide instead of deprecating. Users might be able to recreate their use cases in the new API so a deprecating warning would be noise.

I'm not sure what other methods beyond results buffering could be deprecated.

**Comment by ADmad** [comment]
Yeah, also given that these methods are used in current ORM code (for e.g. ShadowTableStrategy has call to `disableQueryBuffering()`), deprecation with warning is not feasible anyway.

**Comment by othercorey** [comment]
I think this set of changes is complete. We need to work on some 5.0 documentation, but there are also more changes to come.

**Comment by othercorey** [comment]
> Adding deprecation warnings to methods which deal with results buffering where possible in 4.x.
- Database\Query\enableBufferedResults() and related methods
- ORM\Query::count()

Are these still pending?

**Comment by ADmad** [comment]
@markstory also wanted to backport methods where possible.

**Comment by markstory** [comment]
> also wanted to backport methods where possible.

I'm working on this albeit slowly. I'm hoping to have a proposal for how this could work next week.

**Comment by othercorey** [comment]
@markstory Do we have anything left to track?

**Comment by markstory** [comment]
I don't think so.
