### ISSUE TITLE
Question regarding loadInto()

### ISSUE THREAD

**Issue by ilazaridis** [cakephp/cakephp#16277]
Hello,

what I have noticed when I use `loadInto()` is that the underlying query will try to select all the columns of the initial object again.

To make it more clear with an example:

```
$article = $this->Articles->find()->where(['id => 1])->first();
$withMore = $this->Articles->loadInto($articles, ['Comments', 'Users']);
```

the query which loads the additional associations is trying to refetch all the columns of the `$article`.
Is this intentional? I noticed that the object properties are not refreshed, so I am not sure what's going on.

Removing the `enableAutoFields()` from `LazyEagerLoader::_getQuery()` changes this behavior.
Are there any side effects ?

**Comment by ndm2** [comment]
Is it causing any issues?

One reason to do it this way most likely was that it was easier to enable auto fields than to check the associations whether they are joinable ones (their fields must be selected in main query), and explicitly include them. Should be easy enough to do that, but there still might be gotchas waiting in userland code that rely on all fields being selected by default, in result formatters for example.

**Comment by ilazaridis** [comment]
> Is it causing any issues?

Well, in case of big tables (50+ columns) it's unwanted/not optimal behavior for sure and I would like to avoid that.
So, I need to know if there are any side effects / issues that might arise and I am not aware of.

**Comment by markstory** [comment]
> Is this intentional? I noticed that the object properties are not refreshed, so I am not sure what's going on.

Yes. Like @ndm2 stated. We have to query the original table so that associations with finders, callbacks and  and result formatters work as expected. Removing the line of code you mentioned will break userland code somewhere.

**Comment by ilazaridis** [comment]
I don't suggest removing it, I try to understand, but maybe making it optional would be an option here with the current behavior as the default one. Wdyt ?

**Comment by markstory** [comment]
An option could work. The `enableAutoFields()` call was added to solve #13181. The new option would cause usage problems with translated models.

If the performance is a problem have you tried eager loading the associations with your large model? Loading all the associations at once lets the ORM do a better job of building queries. `loadInto()` was intended to be used in scenarios where that isn't possible but with a tradeoff that you would make additional DB queries.

**Comment by ilazaridis** [comment]
> loadInto() was intended to be used in scenarios where that isn't possible but with a tradeoff that you would make additional DB queries.

This is also my intention :D. Making additional db queries is the trade off of course.
Eager loading from the very beginning would be optimal, but it's not possible in my case. :(

**Comment by TheLevti** [comment]
> > Is this intentional? I noticed that the object properties are not refreshed, so I am not sure what's going on.
> 
> Yes. Like @ndm2 stated. We have to query the original table so that associations with finders, callbacks and and result formatters work as expected. Removing the line of code you mentioned will break userland code somewhere.

The issue is not that it queries the root entity again, its clear that this is needed, because of the relationships. What we have noticed is that it loads all of the columns of the root entity even though they are not used for anything. They do not replace or refresh the properties of the root entity. Only the requested associations are attached as expected from loadInto. Is my assumption correct?

**Comment by markstory** [comment]
> They do not replace or refresh the properties of the root entity. Only the requested associations are attached as expected from loadInto. Is my assumption correct?

Yes that is intentional though. We wanted `loadInto()` to be useful with 'dirty' entities, which is why it doesn't refresh or overwrite any properties.

Fields are selected because they are required for `TranslateBehavior` to work from what the history looks like. We could potentially make that conditional on the table having `TranslateBehavior` attached.

**Comment by TheLevti** [comment]
> > They do not replace or refresh the properties of the root entity. Only the requested associations are attached as expected from loadInto. Is my assumption correct?
> 
> Yes that is intentional though. We wanted `loadInto()` to be useful with 'dirty' entities, which is why it doesn't refresh or overwrite any properties.
> 
> Fields are selected because they are required for `TranslateBehavior` to work from what the history looks like. We could potentially make that conditional on the table having `TranslateBehavior` attached.

Ok I am missing the in depths knowledge of those mechanics. I am not sure why we should translate fields of the root entity if the result of it is not used (does not refresh the passed entity, does not load not loaded fields of the root entity if it was fetched with a subset of fields).

In any case it would help. Its just an edge case for apps that have tables with hundreds of columns. A load into is expected to load relationships only, but behind the scenes fetches also this huge root table with all columns and discards the result of it, which is a waste of resources. For small tables I guess its not visible, but for big ones it makes a difference. Sometimes the fetch time is effectively halved when this one line is removed.

**Comment by ilazaridis** [comment]
This sounds nice!
Well, we don't make use of the `TranslateBehavior` so in our case,  it would be rather safe to make this change. :)

**Comment by TheLevti** [comment]
Any input how we can proceed with this issue? Can we help with a pull request on our own?

**Comment by markstory** [comment]
> Any input how we can proceed with this issue? Can we help with a pull request on our own?

A pull request would be helpful. We'll need to be careful here as to not break existing behavior though.

**Comment by TheLevti** [comment]
Well we have overwritten the class and so far it works fine and as expected for over a year now. I will submit the proposal soon.

**Comment by dereuromark** [comment]
ping @TheLevti
