### ISSUE TITLE
Empty array with Cake\View\JsonView returns null

### ISSUE THREAD

**Issue by telemmaite** [cakephp/cakephp#16280]
### Description

Hello, I am following this guide
https://book.cakephp.org/4/en/views/json-and-xml-views.html

REST API returning JSON 

```php
  $posts = []; // case if user has yet to create a post

  $this->set($posts);
  $this->viewBuilder()->setOption('serialize', true);
```

My issue is that my API returns null instead an empty Array.
I would like to keep my response types the same hence arrays with or without values.

I think the issue is here could be this null as my `$serilaze` payload is `[]` but `$data` remains empty and becomes null.
https://github.com/cakephp/cakephp/blob/4.x/src/View/JsonView.php#L179

### CakePHP Version

4.3.2

### PHP Version

8.1

**Comment by ADmad** [comment]
Your statement `$this->set($posts);` won't set any view data. 

You should be using `$this->set(compact($posts));` or `$this->set('posts', $posts);`, then you will get the desired output `{"posts":[]}`.

**Comment by telemmaite** [comment]
But what if I don\`t have the `posts` key,  and my response wrap is `[]` and not `{}`.

Example:
```json
//with data
[
  {"id":1, "post":"cool"},
  {"id":2, "post":"amazing"},
  {"id":3, "post":"great"}
]

//without data
[]
```

**Comment by othercorey** [comment]
> But what if I don`t have the `posts` key, and my response wrap is `[]` and not `{}`.

I don't understand what you mean by "don't have the posts key".

**Comment by raul338** [comment]
Use 

```
$this->set(compact('posts'));
$this->viewBuilder()->setOption('serialize', 'posts');
```
