### ISSUE TITLE
coerceStringToType conversion, convert in case of array conversion '' to ['0'=>'']

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/cakephp#16306]
### Description

The CoerceStringToType function in vendor\cakephp\cakephp\src\Controller\ControllerFactory.php [268], convert in case of string to array conversion a empty string '' to ['0' =>''].

Better is when check in type of string to array conversion if the string match '' then return []

Old:
return explode(',', $argument);

New:
return $argument === '' ? [] : explode(',', $argument);

### CakePHP Version

4.3.4

### PHP Version

8.0

**Comment by markstory** [comment]
We had a discussion about this in the dev channel and one reason to retain the existing behavior is that it replicates how PHP handles string to array conversions.

```php
$s = '';

var_dump((array)$s);
```

Will output `[0=> '']`.

**Comment by ADmad** [comment]
@nicokaiser79 Can you provide an example URL which generates a passed param as empty string, cause I am unsure how that would be possible?

**Comment by saeideng** [comment]
@ADmad 
just for sample:
```php
        //routes
        $builder->connect(
            '/pages/**',
            ['controller' => 'Pages', 'action' => 'show']
        );
        //controller
        public function show(array $page)
        {
           debug($page);
        }
```
```
url:
 example.com/pages/

//result 
[
(int) 0 => '',
]
```

cake 4.3.5

**Comment by ADmad** [comment]
While coercing `''` to array gives `[0 => '']` I don't see it being useful for any practical use case. Converting it to an empty array `[]` as suggested makes a lot more sense.
