### ISSUE TITLE
Support RETURNING syntax in Sqlite

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16302]
### Description

https://www.sqlite.org/lang_returning.html

> The RETURNING syntax has been supported by SQLite since version 3.35.0 (2021-03-12).

This works similar to PostgreSQL's RETURNING syntax and should allow proper compound key and multi-key insert ID support.

### CakePHP Version

4.4

**Comment by markstory** [comment]
What versions of php have that sqlite included?

**Comment by othercorey** [comment]
I don't think it's an API change. It's just part of the query.

**Comment by markstory** [comment]
Don't we currently use `epilog()` to do `RETURNING` in postgres/sqlserver?

**Comment by othercorey** [comment]
Yea. We would replicate that for Sqlite.
