### ISSUE TITLE
bypass coerceStringToType when source type is equal param type

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/cakephp#16307]
### Description

In case of using custom routing classes, for passing and manipulating pass params. In this case the custom routing class return the parameters in the correct target type. This generates a type error in  the controllerFactory.
When the source paramtype equal target param type in this case cann we bypass the the coerceStringToType conversion

In (vendor\cakephp\cakephp\src\Controller\ControllerFactory.php) ControllerFactory[204] after 
```
// Use any passed params as positional arguments
            if ($passedParams) {
                $argument = array_shift($passedParams);
```

```
if ($type->getName() === \get_debug_type($argument)) {
                    $resolved[] = $argument;
                    continue;
                }
```

### CakePHP Version

4.3.4

### PHP Version

8.0

**Comment by markstory** [comment]
> In case of using custom routing classes, for passing and manipulating pass params. In this case the custom routing class return the parameters in the correct target type.

This was not a use case we had designed around which is why it isn't working. I can see it being useful though.

**Comment by ADmad** [comment]
Now that type casting feature is already provided by the framework why not just update your custom route code?

**Comment by nicokaiser79** [comment]
But what is with params that are build in and correctly typed in the paramlist? I have a action that need three params publuc function list (string $search,array $filter,bool $redirect). This action is also used in another controller that extends a special controller. I use a route Class that exctract, the params from the url /cleaner,b-vanish:dr.schnell,s-500ml:600ml.html. The params are there extracted as array [ 'b' => ['vanisch','dr.schnell','s'=>['500ml','600ml']]. This is the filter array that are i needed in the action. The routing Class prepare that and added this to $params['pass']. But the params must cake like converted to string and i lost the key on this way. When I remove the type in the method parameter list, that no problem and no conversion in the controllerfactory, but no type in method param list is like a workaround. The bypass in the controllerfactor is in my opinion the  correctly way, to prevent unneccesary converting.

**Comment by othercorey** [comment]
I think we can take another look at this.
