### ISSUE TITLE
Incorrect handling of updates where only the primary key of an entity is changed

### ISSUE THREAD

**Issue by robertgdev** [cakephp/cakephp#16308]
### Description

If you attempt to save an object to the database and this object has

1. only 1 changed/altered field
2. and this altered field is the primary key field

Then this code [(https://github.com/cakephp/cakephp/blob/4.x/src/ORM/Table.php#L2133)]

```
        $data = array_diff_key($data, $primaryKey);
        if (empty($data)) {
            return $entity;
        }
```

removes the primary key field (which it should) and then, if there are no more fields left to process (see points 1 & 2) above, simply returns the entity. 

There are 2 problems with this: 
1) The entity is marked as clean after this happens
2) In essence, this is a failure condition that fails silently. 

Ideally this would throw an exception (because you don't really want to update a PK and after this processing (described above) you have no data left to update) but at the very least, the entity should not be marked as clean as this suggests that the update was performed when in reality nothing was done. 

### CakePHP Version

4.3.0

### PHP Version

8.1

**Comment by markstory** [comment]
> but at the very least, the entity should not be marked as clean as this suggests that the update was performed when in reality nothing was done.

But the update that was requested (no changes) was completed.

> Ideally this would throw an exception (because you don't really want to update a PK and after this processing (described above) 

Throwing an exception is an option. I think we would need to refine the condition to be that the primary key was changed. Doing an update operation where the primary key is in the payload but is the same as the current value will frequently show up in application code.

**Comment by robertgdev** [comment]
I agree with both of your comments. In my case, I spent several hours trying to figure out why a DB row was not updated, therefore this bug report. 

FYI: I did a bonehead thing: the primary key of the table I was attempting to update was a character field and I changed this field. When I attempted to save, nothing was written to the DB and it just failed silently. I understand that this is not an everyday use-case (and a stupid thing to do) but it cost me a few hours to figure out what was going on.

**Comment by markstory** [comment]
```diff
diff --git a/src/ORM/Table.php b/src/ORM/Table.php
index 8b0cecbeb6..90614dfb58 100644
--- a/src/ORM/Table.php
+++ b/src/ORM/Table.php
@@ -2129,8 +2129,13 @@ class Table implements RepositoryInterface, EventListenerInterface, EventDispatc
     {
         $primaryColumns = (array)$this->getPrimaryKey();
         $primaryKey = $entity->extract($primaryColumns);
-
         $data = array_diff_key($data, $primaryKey);
+
+        if (empty($data) && !$entity->isNew() && !empty($entity->extract($primaryColumns, true))) {
+            $entityClass = get_class($entity);
+            $message = "Cannot change the primary key of a `{$entityClass}`.";
+            throw new RuntimeException($message);
+        }
         if (empty($data)) {
             return $entity;
         }
diff --git a/tests/TestCase/ORM/TableTest.php b/tests/TestCase/ORM/TableTest.php
index b469d0bbd6..536e78be1d 100644
--- a/tests/TestCase/ORM/TableTest.php
+++ b/tests/TestCase/ORM/TableTest.php
@@ -2635,7 +2635,7 @@ class TableTest extends TestCase
      *
      * @group save
      */
-    public function testUpdateNoChange(): void
+    public function testSaveUpdateNoChange(): void
     {
         /** @var \Cake\ORM\Table|\PHPUnit\Framework\MockObject\MockObject $table */
         $table = $this->getMockBuilder(Table::class)
@@ -2645,10 +2645,26 @@ class TableTest extends TestCase
         $table->expects($this->never())->method('query');
         $entity = new Entity([
             'id' => 2,
-        ], ['markNew' => false]);
+        ], ['markNew' => false, 'markClean' => true]);
         $this->assertSame($entity, $table->save($entity));
     }
 
+    /**
+     * Tests that modifying only the primary key raises an error.
+     *
+     * @group save
+     */
+    public function testSaveUpdateNoChangeOtherThanPrimaryKey(): void
+    {
+        $table = $this->getTableLocator()->get('Articles');
+        $entity = $table->get(1);
+        $entity->id = 99;
+
+        $this->expectException(RuntimeException::class);
+        $this->expectExceptionMessage('Cannot change the primary key of a `TestApp\Model\Entity\Article`');
+        $table->save($entity);
+    }
+
     /**
      * Tests that passing only the primary key to save will not execute any queries
      * but still return success
@@ -2656,7 +2672,7 @@ class TableTest extends TestCase
      * @group save
      * @group integration
      */
-    public function testUpdateDirtyNoActualChanges(): void
+    public function testSaveUpdateDirtyNoActualChanges(): void
     {
         $table = $this->getTableLocator()->get('Articles');
         $entity = $table->get(1);
@@ -2671,7 +2687,7 @@ class TableTest extends TestCase
      *
      * @group save
      */
-    public function testUpdateNoPrimaryButOtherKeys(): void
+    public function testSaveUpdateNoPrimaryButOtherKeys(): void
     {
         $this->expectException(InvalidArgumentException::class);
         /** @var \Cake\ORM\Table|\PHPUnit\Framework\MockObject\MockObject $table */

```

I tried the change we had discussed and it caused a few existing tests to fail. I don't think we'll be able to add the exception you're looking for as the ORM internals rely on this quirky behavior for now. Given the relative infrequency that this scenario is hit, I'm reluctant to pursue a potentially risky change to association saving.

**Comment by robertgdev** [comment]
OK, I understand your reasoning and I agree that it's a weird/stupid edge case. Thank you for taking a look none-the-less.
