### ISSUE TITLE
Is there a way to connect to multiple redis servers?

### ISSUE THREAD

**Issue by bohehe** [cakephp/cakephp#16315]
### Description

I can't find any configurations to config redis cluster in [official document](https://book.cakephp.org/4/en/core-libraries/caching.html#redisengine-options)
How can I connect to multiple redis servers with cakephp?

### CakePHP Version

4.2

**Comment by markstory** [comment]
There is no support for Redis Cluster right now. We would need another Cache adapter for that as the constructors for clustered and non-clustered redis clients are a bit different.

**Comment by bohehe** [comment]
I see. Thank you. @markstory
