### ISSUE TITLE
No length for integer fields in table schema

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16314]
### Description

I noticed that when creating form fields, the following code used in the `FormHelper::control()` ...

```
$context = $this->_getContext();
$fieldDef = $context->attributes($fieldName);
```

... gives different results for CakePHP 3 and CakePHP 4. More specifically, if I have an `int(2)` field in my database, CakePHP 3 lets me know through `$fieldDef` that this field has `['length' => 2]`. In CakePHP 4, the length is null.

I was curious as to why this is the case and made my way to `\Cake\Database\Schema\MysqlSchema::_convertColumn()` (CakePHP 3) / `\Cake\Database\Schema\MysqlSchemaDialect::_convertColumn()` (CakePHP 4).

So, in CakePHP 3 the relevant excerpt of the method looks like this:

```
if (in_array($col, ['int', 'integer', 'mediumint'])) {
    return ['type' => TableSchema::TYPE_INTEGER, 'length' => $length, 'unsigned' => $unsigned];
}
```

In CakePHP 4 `length` is hard-coded to `null`:
```
if (in_array($col, ['int', 'integer', 'mediumint'])) {
    return ['type' => TableSchema::TYPE_INTEGER, 'length' => null, 'unsigned' => $unsigned];
}
```

I realised though that changing the hard-coded `null` to `$length` (so basically using the CakePHP 3 code) actually gives me a correct result, hence I'd be able to detect in the `FormHelper` that the `int` field has a length of 2.

So my question is: Is there a specific reason as to why this information was exposed in CakePHP 3 but isn't available in CakePHP 4 anymore? Needless to say, I'd prefer to have the `length` information also in CakePHP 4 ... :-)

Same applies for bigint, tinyint, smallint.

### CakePHP Version

4.3.5

### PHP Version

7.4

**Comment by othercorey** [comment]
Integer display lengths were deprecated and removed from MySQL.

**Comment by dereuromark** [comment]
Sounds related to https://github.com/cakephp/migrations/issues/502 which very much creates problems for enums and the ability to migrate/bake those properly.

**Comment by markstory** [comment]
Like @othercorey mentioned display lengths were removed from MySQL. We can't make this work consistent across the various versions of MySQL we support so we've opted to normalize on how MySQL is going to work going forwards.

**Comment by dereuromark** [comment]
I would rather suggest reverting this and instead using the diplay length for bake and validation rules.
After all that is the semantic contract of those fields and is what is expected to show up.
If those are used for storing or not seems not relevant IMO, thats a DB internal issue.

**Comment by gerhard-lechner** [comment]
I think that's not possible @dereuromark

If I create the following table ...

```
CREATE TABLE `example` (
  `id` int(10) UNSIGNED NOT NULL,
  `col1` varchar(200) DEFAULT NULL,
  `col2` int(2) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

... and then `DESCRIBE example;` I get different information depending on the MySQL version.

**MySQL 5.7.34**

```
+-------+------------------+------+-----+---------+-------+
| Field | Type             | Null | Key | Default | Extra |
+-------+------------------+------+-----+---------+-------+
| id    | int(10) unsigned | NO   |     | NULL    |       |
| col1  | varchar(200)     | YES  |     | NULL    |       |
| col2  | int(2) unsigned  | YES  |     | NULL    |       |
+-------+------------------+------+-----+---------+-------+
```

**MySQL 8.0.28**

```
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| id    | int unsigned | NO   |     | NULL    |       |
| col1  | varchar(200) | YES  |     | NULL    |       |
| col2  | int unsigned | YES  |     | NULL    |       |
+-------+--------------+------+-----+---------+-------+
```

So the display length just isn't there anymore on MySQL 8.0.28, hence no chance of using it for bake I guess.
