### ISSUE TITLE
Custom cache engine is not available

### ISSUE THREAD

**Issue by bohehe** [cakephp/cakephp#16327]
### Description

I defined custom cache engine in `src/Cache/Engine/RedisCacheEngine`
In `config/app.php`, I defined the cache config for it.
```
    'Cache' => [
        'default' => [
            'className' => 'File',
            'path' => CACHE,
            'url' => env('CACHE_DEFAULT_URL', null),
        ],

        'my_session' => [
            'className' => 'RedisCacheEngine',
            'duration' => '+60 days',
            'prefix' => 'my_session_',
            'fallback' => 'default',
        ],

```
In `config/bootstrap.php`, I loaded the config
```
Cache::setConfig(Configure::consume('Cache'));
```

When I want to use `Cache::read('test', 'my_session')` to test it, it throws error:
```
Error: [BadMethodCallException] Cache engine RedisCacheEngine is not available. in /usr/local/rms/agency/releases/27/php/vendor/cakephp/cakephp/src/Cache/CacheRegistry.php on line 59
```

Is my cache configuration incorrect? What can I do to resolve this error? Thanks.

### CakePHP Version

4.2

### PHP Version

8.0

**Comment by ADmad** [comment]
You need to either use the fully qualified class name or the short name without "Engine" suffix for the `className` config.
