### ISSUE TITLE
CacheEngine stops deleteMany after first non existent key

### ISSUE THREAD

**Issue by Sammaye** [cakephp/cakephp#16347]
### Description

I have noticed that if you call a deleteMany on the CacheEngine class with keys that could return false due to not existing in the cache it will stop running deleteMany entirely, i.e.
````
[
    'key1',
    'key2',
]
````
Key1 does not exist but key2 does, but key2 will never be removed because key1 returns false from the function.

This also means this function has unpredictable behaviour depending on the order in which you place keys, so defo buggy.

### CakePHP Version

4.3

### PHP Version

7.1

**Comment by markstory** [comment]
Which cache engine are you using?

**Comment by Sammaye** [comment]
File engine, it breaks specifically when searching for a file by that key
