### ISSUE TITLE
FormValidation with custom validator are not applied on Form

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/cakephp#16349]
### Description

I defined a form and add the option 'context' => ['validator' => 'private'] to define that form follow a custom validator. I defined in my customerModel a validatorDefault and a validatorPrivate($validator). The validatorPrivate call the validatorDefault and extend the ruleset. The rule with regex are not applied in the form, when i put the rule in validatorPrivate. But when I put the rule in teh validatorDefault the rule will be applied and the error is shown in the form. Rule with notEmptSting will be apllay in both validators. All rules that use the $validator->add will be only apllied in validatorDefault.

```
snipped validator of the customerTable.php

/**
   * Validator for private validation
   *
   * @param \Cake\Validation\Validator $validator the validator
   * @return \Cake\Validation\Validator
   */
  public function validationPrivate(Validator $validator): Validator
  {
      $validator = $this->validationDefault($validator);

      $validator
          ->notEmptyString('Name_1', 'Bitte geben Sie einen Vorname ein.')
          ->regex('Name_1', $this->pattern, 'Vorname enthält ungültige Zeichen');
      $validator
          ->notEmptyString('Name_2', 'Bitte geben Sie einen Nachname ein.')
          ->regex('Name_2', $this->pattern, 'Nachname enthält ungültige Zeichen');

      return $validator;
  }
```

regex rule will not applay in my form.

### CakePHP Version

4.3.5

**Comment by markstory** [comment]
I'm not sure we ever implemented multiple validator support for `FormContext`. We should add that though as multiple-validator support isn't very useful without it.

**Comment by ADmad** [comment]
@nicokaiser79 Would you like to submit a patch to allow switching the validator for `FormContext`?
