### ISSUE TITLE
formatResults fails on contained association when the primary query is transformed with mapReduce

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#16344]
### Description

Attaching a formatter to a contained association using `formatResults` usually works like this: The Association attaches a Formatter to the primary query, in which it assembles a Collection of entities extracted from the parent entities. Then it applies the actuall formatters to that collection and injects the results back into the parent entities.

But when the results are transformed using mapReduce, everything falls apart. The associated entities cannot be extracted and thus the formatters are not applied.

## Example

The model "ScheduleItems" has a belongsTo association to "Talks".

```
$schedule = $this->ScheduleItems->find()
->contain(['Talks' => function($query) {
	$query->formatResults(function($results, $query) {
		return $results->map(function($row) {
			// Doing something irrellevant
			return $row;
		});
	});
	return $query;
}])
->mapReduce(
	function($item, $key, $mapReduce) {
		$mapReduce->emitIntermediate($item, $item->get('start')->i18nFormat('d. MMMM'));
	},
	function($items, $date, $mapReduce) {
		$mapReduce->emit($items, $date);
	}
);
```

The mapReduce is used to group the ScheduleItems by Date, so the Result after the mapReduce will be:

```
[
	'1. January' => /* Collection of ScheduleItems */,
	'2. January' => /* Collection of ScheduleItems */,
]
```

The formatters are applied after the mapReduce. The Association expects the Result to be a collection of ScheduleItems from which it would extract the Talks. But instead, it is given an *array of* collections of ScheduleItems, so it cannot extract the Talks (see Association::_formatAssociationResults for the relevant bit of code.)
Not only can the formatters not be applied to the result, the Association will attempt to call the method `clean()` on each ScheduleItem once it is done – which fails, since it calls the method on the Collection of ScheduleItems instead of the ScheduleItems itself.

## Solutions?

I am not sure if this is even a bug, or if the formatters and mapReducers should not be used together at all.
I do not know if this issue needs a fix, or maybe just a note in the documentation.

A possible solution would be to apply the formatters *before* applying the mapReducers, but that would probably break some other use cases. Another possible solution would be to shove the MapReduce into a formatter, so it is applied after the other formatters like this:

```
->formatResults(function($results, $query) {
	return new MapReduce(
		$results,
		function($item, $key, $mapReduce) {
			$mapReduce->emitIntermediate($item, $item->get('start')->i18nFormat('d. MMMM'));
		},
		function($items, $date, $mapReduce) {
			$mapReduce->emit($items, $date);
		}
	);
})
```

### CakePHP Version

4.x

**Comment by markstory** [comment]
> I am not sure if this is even a bug, or if the formatters and mapReducers should not be used together at all.
I do not know if this issue needs a fix, or maybe just a note in the documentation.

They can be used together but you can easily make impossible logic in combining them. Result formatters are a simpler to operate 'map' operation. Its up to the developer to ensure they apply compatible transformations.

> A possible solution would be to apply the formatters before applying the mapReducers, but that would probably break some other use cases.

Agree, changing the order of operations will very likely break other usage.

> Another possible solution would be to shove the MapReduce into a formatter, so it is applied after the other formatters

Why though? That creates another usage pattern we have to support. You can also do map/reduce operations on the `ResultSet` after `formatResults()` has been applied using the Collection methods. I'm reluctant to add even more ways to accomplish the same task as we have a few already.
