### ISSUE TITLE
Implementing buildValidator method in a modelless Form causes an error

### ISSUE THREAD

**Issue by zejji** [cakephp/cakephp#16359]
### Description

Implementing the `buildValidator` method in a modelless form (i.e. a class deriving from `Cake\Form\Form`) triggers the following error:

```
Cake\Event\EventManager::on(): Argument #3 ($callable) must be of type ?callable, array given, called in /app/vendor/cakephp/cakephp/src/Event/EventManager.php on line 148
```

This is because the signature of the `on()` method in EventManager is as follows:
``` php
public function on($eventKey, $options = [], ?callable $callable = null)
```

However, lines 145-148 of the `_attachSubscriber` method in EventManager attempt to pass an **array** as the third argument in certain scenarios:
``` php
if (is_string($method)) {
    $method = [$subscriber, $function];
}
$this->on($eventKey, $options, $method);
```

This is a bug because the types do not match.

### CakePHP Version

4.3.4

### PHP Version

8.1.3

**Comment by markstory** [comment]
Arrays *are* `callable` if they  contain an object and public method reference. Is your method not public?

**Comment by zejji** [comment]
@markstory - Thanks for the reply. The methods were protected as they originally implemented the `_buildValidator` method from CakePHP 3, so that will be the reason. I have to admit I wasn't aware of the quirks of the `callable` type!
