### ISSUE TITLE
Error when using BodyParserMiddleware in Route Scope with caching active

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#16364]
### Description

In my efforts not to load unnecessary stuff application-wide, I removed the `BodyParserMiddleware` from my Application.php file and wanted to use it only as a Route Scoped Middleware like so:

```
$routes->scope('/api', function (RouteBuilder $builder) {
    $builder->applyMiddleware('bodyParser', new BodyParserMiddleware());

    ...
}
```

So far, so good. However, when I add caching for my routes in the Application.php (`new RoutingMiddleware($this)` -> `new RoutingMiddleware($this, '_cake_routes_')`), I start getting the following error:

```
Serialization of 'Closure' is not allowed
```

Would you consider this a bug or is this scenario (Route Scoped BodyParserMiddleware with route caching active) simply not supported?

### CakePHP Version

4.3.5

### PHP Version

8.0

**Comment by markstory** [comment]
RouteMiddleware and caching routes are becoming an increasingly frequent problem. I think we may need to explore a different solution for cached routes or deprecate and remove it.

**Comment by othercorey** [comment]
We plan to deprecate. 

https://github.com/cakephp/cakephp/pull/16331#issuecomment-1051042373

**Comment by gerhard-lechner** [comment]
Okay, got it - you're obviously aware of this (and similar) problems. I just wanted to share my findings. Feel free to close this issue if it doesn't serve any real purpose then.

**Comment by ADmad** [comment]
Closing as there's no fix for this problem and the feature is already slated for deprecation and removal.
