### ISSUE TITLE
Cache::clear() in RedisEngine is ~100x slower than in Cake 3.7

### ISSUE THREAD

**Issue by ethanpooley** [cakephp/cakephp#16360]
### Description

[This](https://github.com/cakephp/cakephp/pull/13405) change, which uses SCAN instead of KEYS, was indeed in line with Redis recommendations. But that recommendation glosses over the repercussions:

**KEYS** (return all keys at once)
- All keys must occupy the calling script's memory simultaneously (BAD)
- Blocks the entire Redis server until complete (BAD)
- Takes very little wall clock time (GOOD)

**SCAN** (return pages of keys until all have been returned)
- Only one page of keys must occupy the calling script's memory simultaneously (GOOD)
- Unblocks the Redis server between each page, allowing other calls to be served (GOOD)
- Takes approximately 100x the wall clock time of KEYS (BAD)

That ~100x number comes from my own experience after a recent CakePHP upgrade, which is why I went investigating. I found it supported by other sources [[1](https://stackoverflow.com/questions/67034121/predis-scan-slower-than-keys), [2](https://github.com/redis/redis-py/issues/1102)]. In my case the blocking and memory issues have never yet presented a problem, but the timing increase is unworkable in one of our use cases. For that use case I have bypassed the Cache class and am making direct Redis calls to accomplish what I need.

I thought of PRing a change that would allow the caller to specify which implementation to use. But after looking over the code I'm not sure that level of control would be appropriate, given the level of abstraction Cake is attempting to provide with its Cache class. **I am looking for guidance on whether this timing issue is a concern to the framework maintainers, as well as what solutions they recommend.** I'm up for PRing something if it sounds promising to all.

### CakePHP Version
3.8.1-5.x

**Comment by markstory** [comment]
How often are you wiping your redis cache?  From your analysis on the differences it sounds like we should continue using `SCAN` as locking up redis will cause more problems than having a slower purge.

> I am looking for guidance on whether this timing issue is a concern to the framework maintainers, as well as what solutions they recommend. I'm up for PRing something if it sounds promising to all.

I don't know how we would fit different kinds of clears into the abstractions that `Cache` provides. We could expose additional methods on the `RedisEngine` for the 'fast and dangerous' style of clear but the typecheckers will require casting to avoid errors.

**Comment by ethanpooley** [comment]
>How often are you wiping your redis cache?

Approximately weekly, during deployments. We put our app into a maintenance mode during deployments, so there are actually no other requests to be blocked. In that use case, the most aggressive approach is the best: it doesn't hurt anything, and it lets us come out of maintenance mode as quickly as possible.

> From your analysis on the differences it sounds like we should continue using SCAN as locking up redis will cause more problems than having a slower purge.

Normally I would agree, though the 100x multiplier is perhaps large enough to call that into question. With a large enough multiplier, the slowness of SCAN could cause practical problems before KEYS ever would have, in spite of its theoretically nicer behavior.

That said, I'm not suggesting changing the implementation back. But I do feel like it is worth adding an additional method to `RedisEngine`, as you mentioned. **I propose a new method called `clearFast()` that implements KEYS to get the list of keys, and then uses the somewhat newer (Redis 4.x) deletion command [UNLINK](https://redis.io/commands/unlink) to remove those keys.** UNLINK removes the keys from the namespace immediately, so it is logically effective by the time it returns. But actual cleanup and recovery of the space on the Redis server side is handled asynchronously, so the client doesn't have to wait as long. Both are departures from the norm, but KEYS and UNLINK make good partners in corner cases with lots of keys.

I'm open for you to tell me, on reflection, not to bother. Also open to alternative names for the new method. It looks like `RedisEngine` would benefit from a `deleteMultiple()` implementation, as well.

**Comment by markstory** [comment]
> That said, I'm not suggesting changing the implementation back. But I do feel like it is worth adding an additional method to RedisEngine, as you mentioned. I propose a new method called clearFast()

That works for me.

> It looks like RedisEngine would benefit from a deleteMultiple() implementation, as well.

Sounds like you have changes in mind, any chance you could open a pull request for this?

**Comment by itosho** [comment]
That's interesting.

Taking this opportunity, we may have both a method using DEL command and a method using UNLINK command.

---

- delete($key): bool
  - current method
  - using  DEL method

- deleteAsync($key): bool
  - new method
  - using UNLINK method

- clear(): bool
  - current method
  - using DEL method

- clearAsync(): bool
  - new method
  - using UNLINK method

---

Or it could be named `unlink()` instead of `Async`, as in [this library](https://github.com/redis-store/redis-store/blob/3acfa95f4eb6260c714fdb00a3d84be8eedc13b2/lib/redis/store/namespace.rb#L61).

There may be a way to add `isAsync` option to second argument of existing methods.
However, this may have an impact on other CacheEngine.

**Comment by markstory** [comment]
I like those method names @itosho . We could add the proposed async methods to the `RedisEngine` and not have to worry about the high level cache interface. This feels like a redis-specific optimization that we can't easily implement in other cache engines.

**Comment by itosho** [comment]
Thank you for your reply @markstory 
If no one does, I will create the pull request.

**Comment by ethanpooley** [comment]
I wish that name worked. For the UNLINK portion it's perfect. But for the new key-selection portion, async is the opposite of what this change would be. The new method is blocking to both the client and the server—it is in no sense asynchronous. :(

The current method could be described as being "nice" like the [Unix command](https://man7.org/linux/man-pages/man2/nice.2.html). But I don't know of an antonym to that in common technical use. `clearAggressively()` or `clearAsap()`? Sorry—I know `clearFast()` is poor but I couldn't come up with anything better.

@itosho I am willing to work on a PR too, and was hoping to get around to this. Let me know if you start, and I'll do the same, so we don't duplicate work? And I'll be happy to review/test if you do push something. Thank you!

**Comment by markstory** [comment]
Does `clearBlocking()` work? It covers the 'clear' and 'blocks something' components. Hopefully the 'blocking' aspect leads people to read up on how/why this method blocks.

**Comment by itosho** [comment]
@ethanpooley 
Sorry for the late reply. I have not been able to it, so you can have it started first.
Since you found it, that would be nice 👍 

I'm here to help, if you need it!

**Comment by itosho** [comment]
@ethanpooley I'm sorry. I didn't get a response from you in a while, so I created a PR.
Please give me feedback and better ideas if you like!
https://github.com/cakephp/cakephp/pull/16478
