### ISSUE TITLE
Using TableRegistry::getTableLocator() in a table initialize method poses a conflict with Fixtures

### ISSUE THREAD

**Issue by mcube27** [cakephp/cakephp#16373]
### Description

Case and how to reproduce :

You need for example Users and Emails fixtures for a test.
In UsersTable:Initialize() you call $emailsTable = TableRegistry::getTableLocator()->get('Emails');
I do that in order to load Events.

When I passed to the new system of fixtures, I removed everything but the init function. Therefore, my table I created with `$this->_schemaFromReflection();` in TestFixtures.

By doing so it triggers an exception because EmailsTable is already created by loading UsersTable.

I do not know if the behavior is intended or if I should not use TableRegistry in initialize, but it worked like a charm until now.

### CakePHP Version

4.3.6

**Comment by ndm2** [comment]
Oops, I forgot the promised [backport](https://github.com/cakephp/cakephp/pull/16289#issuecomment-1028045028) :frowning_face:

**Comment by mcube27** [comment]
I tried adding the line proposed but it doesn't solve my issue.

I'll wait for your feedback

**Comment by ndm2** [comment]
I would probably generally advise against manually loading tables inside your tables. If the tables are related, then you could/should use associations, and if they're not related, then they probably shouldn't be a dependency. But that's programming principles, and even if discouraged, it ideally shouldn't break code.

I guess things would work when reflection would do `$this->getTableLocator()->clear();` instead of just removing the one fetched alias? Not sure though how I'd feel about doing that, and what side effects it could possibly have.

**Comment by mcube27** [comment]
It's mostly to send emails through events without using a global event manager.

I tend to want to change and forget about using event, as it doesn't make code easily readable.

However, I don't feel that the fixture creation should force me to change my code either.

**Comment by markstory** [comment]
> By doing so it triggers an exception because EmailsTable is already created by loading UsersTable.

Do you have an error message and stack trace for this error, or a small code sample to help reproduce this problem?

**Comment by mcube27** [comment]
I explained in the beginning how to reproduce.

The error message is only that it can't create my EmailTable as it's already in registry.

Let me know if I can help anymore

**Comment by ndm2** [comment]
@markstory As I understand it, the flow is as follows:

1. Test fixture fetches table `A` for reflection.
2. In `A::initialize()` table `B` is manually loaded via the table locator.
3. Test fixture removes `A` from locator.
4. Test fixture fetches table `B` for reflection.
5. Error is triggered because `B` has already been loaded in step 2 and therefore cannot be reconfigured.

**Comment by mcube27** [comment]
Sounds as I understood it

**Comment by markstory** [comment]
> I explained in the beginning how to reproduce.

Vaguely yes, I was hoping to get an error message and stack trace so I could look at where the error is coming from and what you're seeing. I'll try and blunder my way through it instead.

**Comment by mcube27** [comment]
I ll send it over on Monday. 
it all starts with the TestFixture:init() where it passes in $this->_schemaFromReflection();

**Comment by markstory** [comment]
I'm not able to reproduce this issue. I'm not able to put anymore time into this without a way to reproduce.

**Comment by mcube27** [comment]
Hi,

Sorry for the delay.

Here is the error log :
```
RuntimeException : You cannot configure "Emails", it already exists in the registry.
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\Datasource\Locator\AbstractLocator.php:57
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php:205
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\ORM\Locator\LocatorAwareTrait.php:90
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:250
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:155
 C:\webserver\www\weeezy-api\tests\Fixture\EmailsFixture.php:29
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:115
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureHelper.php:94
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TruncateStrategy.php:51
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\TestCase.php:301
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\TestCase.php:249
 C:\webserver\www\weeezy-api\tests\TestCase\IntegrationTests\UsersIntegrationTest.php:46
```
You need a User fixture with only an init() function, same for emails.
Emails fixture must be called after Users fixture.

This works, 
```
 public $fixtures = [
        'app.Emails',
        'app.Users',
    ];
```
but this does not
```
public $fixtures = [
        'app.Users',
        'app.Emails',
    ];
```

Users and Emails are connected like this :

In UsersTable : `$this->hasMany('Emails');`
In EmailsTable: `$this->belongsTo('Users');`

In UserTable:initialize() you need to call `$emailsTable = TableRegistry::getTableLocator()->get('Emails');`

Because they are connected as associations and that I need the table in the UsersTable::intialize(), the table is created twice and causes the exception.

After checking again, if in UsersTable::initialize() I do : `$emailsTable = $this->Emails` instead, it works.

But in my opinion, it should work in both cases.

**Comment by mcube27** [comment]
I realize that I have the same problem with I18n tables.

I18n tables are named in my case services_i18n, so when I load the fixture, it wants to find a services_i18ns table. So I need to add a table property in the fixture. But doing so, generates an error :
```
RuntimeException : You cannot configure "CategoriesI18n", it already exists in the registry.
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\Datasource\Locator\AbstractLocator.php:57
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php:205
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\ORM\Locator\LocatorAwareTrait.php:90
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:250
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:155
 C:\webserver\www\weeezy-api\tests\Fixture\CategoriesI18nFixture.php:31
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php:115
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureHelper.php:94
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\Fixture\TruncateStrategy.php:51
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\TestCase.php:301
 C:\webserver\www\weeezy-api\vendor\cakephp\cakephp\src\TestSuite\TestCase.php:249
 C:\webserver\www\weeezy-api\tests\TestCase\IntegrationTests\BookingsIntegrationTest.php:83
```
of course, I could have named it differently but it has never been a problem until now.
