### ISSUE TITLE
Email Issue

### ISSUE THREAD

**Issue by webdeveloper510** [cakephp/cakephp#16370]
### Description

I am facing error when i am trying to update email with saveAssociated function. Please see my code and fix me know

 if ($this->request->is(array('post', 'put'))) {
			if ($this->Client->saveAssociated($this->request->data)) {
	            echo "<pre>";
	            print_r($this->request->data);die;
				$this->Client->ClientAddress->updateLatLng();
				$this->Session->setFlash('The client has been saved.', 'success');
				return $this->redirect(array('action' => 'view', $this->Client->id));
			}

			$this->Session->setFlash('The client could not be saved.');
		}
		$regions = $this->Client->ClientAddress->Region->find('list');
		$groups = $this->Client->Group->find('list', array('conditions' => array('is_active' => true)));
           
		$this->set(compact('regions', 'groups'));
		$this->render('_form');

### CakePHP Version

2

### PHP Version

7

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
