### ISSUE TITLE
CakePHP Email Validator

### ISSUE THREAD

**Issue by mattprado21** [cakephp/cakephp#16388]
### Description

Email validator (email()) are using the regex pattern based on **cakephp/src/Mailer/Email.php EMAIL_PATTERN**
**^((?:[\p{L}0-9.!#$%&\'*+\/=?^_`{|}~-]+)*@[\p{L}0-9-._]+)$/ui**

### Issue:
`->email('email', false, 'The email is invalid.')`
When I used default email() validator, an email with dot(.) before @ character was invalid (ex. sample.@email.com)

But when I create a custom email validator using the same regex, the email becomes valid
```
->add('email', 'email',[ 
                'rule' => function ($value, $context) {
                    return preg_match('/^((?:[\p{L}0-9.!#$%&\'*+\/=?^_`{|}~-]+)*@[\p{L}0-9-._]+)$/ui', $value);
                },
                'message' => 'The email is invalid.'
            ])
```

### CakePHP Version

3.7.*

### PHP Version

7.2

**Comment by markstory** [comment]
A trailing dot with no following characters isn't a valid email address though. The local part of an email address isn't allowed to have consecutive dots or a trailing dot as per [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1)

You'll need to use your own validation rules if you want to accept non-compliant addresses.
