### ISSUE TITLE
MySQL 8.0 - use reserved keywords as table name fails

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#16390]
### Description

My tests fail due to an update from MySQL 5.7 to 8.0.
I found out, that in MySQL 8.0 the keyword "groups" must not be used - except it's correctly quoted.

Fixtures generate SQL-inserts without quoted table names and therefore they fail
`INSERT INTO groups (id, name) VALUES (2, 'admin'), (7, 'repairhelper'), (9, 'orga')`

https://github.com/anstiftung/mapped-repair-events/runs/5568618234?check_suite_focus=true

Can that be fixed? Or do you think it's better to rename the table (which includes some refactoring that I want to avoid).

Thanks for your help,
Mario

### CakePHP Version

4.3.6

### PHP Version

8.0

**Comment by ADmad** [comment]
Either rename your table to not use reserved names or turn on identifier quoting in the datasource config 
https://github.com/cakephp/app/blob/6e5a382819596846e76accff5639259e64099d02/config/app.php#L313-L320

**Comment by mrothauer** [comment]
Thanks a lot - I will use `quoteIdentifiers`.
