### ISSUE TITLE
MissingTemplateException missing type in __construct

### ISSUE THREAD

**Issue by flowl** [cakephp/cakephp#16396]
### Description

    Fatal error: Type of Cake\View\Exception\MissingTemplateException::$file must be string (as in class Exception)

https://github.com/cakephp/cakephp/blob/4.x/src/View/Exception/MissingTemplateException.php

### CakePHP Version

4

### PHP Version

8.1

**Comment by flowl** [comment]
Has been fixed here:
https://github.com/cakephp/cakephp/pull/15529

**Comment by MarwanSalim** [comment]
**Conclusion:** This issue was resolved in CakePHP [4.3.0](https://github.com/cakephp/cakephp/pull/15529#:~:text=othercorey%20added%20this%20to%20the%204.3.0%20milestone%20on%20May%2021%2C%202021)
