### ISSUE TITLE
__isset() Inconsistency

### ISSUE THREAD

**Issue by boshrin** [cakephp/cakephp#16408]
### Description

According to the [Entity Class documentation](https://api.cakephp.org/4.2/class-Cake.ORM.Entity.html), `__isset()` "Returns whether this entity contains a field named $field _regardless of if it is empty_" (emphasis added). However, the actual implementation in EntityTrait calls `$this->has()` and [the comment](https://github.com/cakephp/cakephp/blob/78d149852f881aa9140d4e524d40ec36e35761a6/src/Datasource/EntityTrait.php#L145) for `__isset()` says "Returns whether this entity contains a field named $field and _is not set to null_" (which is consistent for the behavior of `has()`).

Minimally, the documentation should be made consistent with the implementation, but better would be for `__isset()` to implement the functionality described in the API documentation. Otherwise, in order to tell if a null key is set it is necessary to jump through some hoops, such as first calling `extract()` or `jsonSerialize()`.

### CakePHP Version

4.2.9 and later

### PHP Version

7.4.27

**Comment by othercorey** [comment]
This was already fixed https://github.com/cakephp/cakephp/pull/16354

**Comment by boshrin** [comment]
Sorry, I searched for __isset tickets but that one didn't show up. That said, it would still be useful to have the functionality as originally described (_regardless of if it is empty_) unless there's some other way to do that that I  missed (and doesn't require conversion to an array or another object)?

**Comment by markstory** [comment]
>  That said, it would still be useful to have the functionality as originally described (regardless of if it is empty) unless there's some other way to do that that I missed (and doesn't require conversion to an array or another object)?

Having `__isset()` ignore all empty values would go against the spirit of what overloading `isset()` is supposed to do. Magic methods should work at close as possible to how `isset()` works on arrays and other objects that don't implement a magic method. Having them behave differently will also cause breaking changes with `empty($entity->prop)` works.

My interpreation of what you've described would make `__isset()` return false for values like `''` `false` and `0`. These are all common types that almost all existing applications rely on. We already have the `isEmpty()` method which provides the behavior you've described and doesn't cause any breaking changes.

**Comment by othercorey** [comment]
Best we could do is provide a helper that works similar to `array_key_exists()` that checks if the field exists in the entity.

**Comment by boshrin** [comment]
I think the analogy to `array_key_exists()` makes sense, and is a better option than my original bug report as it would be more consistent with the equivalent PHP functionality.

- Key not present in object:
  - `key_exists`: false
  - `isEmpty`: true
  - `__isset`: false
- Key present in object, null:
  - `key_exists`: true
  - `isEmpty`: true
  - `__isset`: false
- Key present in object, not null:
  - `key_exists`: true
  - `isEmpty`: false
  - `__isset`: true

**Comment by ADmad** [comment]
> Best we could do is provide a helper that works similar to array_key_exists() the checks if the field exists in the entity.

That could work for now since we store the properties in an array but what if we were to have an entity implementation which uses actual object properties?

Even when using typed nullable properties there's no easy way to check for null vs uninitialized except using `ReflectionProperty::isInitialized()`.

P.S.  We currently have no plans to change how entity properties are stored.

**Comment by othercorey** [comment]
> That could work for now since we store the properties in an array but what if we were to have an entity implementation which uses actual object properties?

In that case, we'd probably have to throw an error when getting an invalid field.

**Comment by dereuromark** [comment]
You can `->toArray()` and then do the key check. So small workaround.
Having the method directly is of course very cheap to add 🙂

I am fine with adding it.
Would be interesting to know the use case(s) for this, though.

**Comment by othercorey** [comment]
Do we want to introduce anything in 4.4 for this?

**Comment by markstory** [comment]
~~I'll get the documentation updated for `EntityTrait`.~~ (docs are already updated in the code). I don't fully understand the scenarios where you would need to check if an attribute is defined and null vs. not-defined though.

**Comment by othercorey** [comment]
The scenario I thought of is checking association properties. The association could be loaded and the entity null if no matching join.

**Comment by boshrin** [comment]
Yeah, we're basically performing calculations on an entity's associations using a trait, where different entities can have different parent associations defined and/or populated. Theoretically we could probably do something at the table level instead, but that would add more overhead and code complexity.

**Comment by dereuromark** [comment]
You can also have a base entity and use a trait for what u need
See e.g.
https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Entity/ReadTrait.php
If all entities extend that base class, a community plugin Version might suffice.
Then core doesnt need to provide it

**Comment by othercorey** [comment]
> You can also have a base entity and use a trait for what u need See e.g. https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Entity/ReadTrait.php If all entities extend that base class, 

This would be something you have to add after baking, right? We do require users augment the User entity class, but this might affect many classes.

**Comment by dereuromark** [comment]
Should we close this as works-for-us?
