### ISSUE TITLE
Mailer() uses incorrect template path

### ISSUE THREAD

**Issue by umer936** [cakephp/cakephp#16417]
### Description

In our `AppController.php:beforeRender()`, we have `$this->viewBuilder()->setTheme(SITE_KEY);`

This sets the App to default to the templates in `/plugins/SITE_KEY/templates`, which is working as expected. 

However, in `src/Mailer/UserMailer.php`, I have an `invite()` which _should_ point to the template with the same name checking the theme's template path first. In this case, it should point to `/plugins/SITE_KEY/templates/email/html/invite.php` but it instead points to `/templates/email/html/invite.php`, not using the templates path from `setTheme()`. 

Workaround is to add `->setTemplate(SITE_KEY.'.invite');` in `invite()`, but that should not be necessary given the theme. 

### CakePHP Version

4.3.6

### PHP Version

7.4.21

**Comment by markstory** [comment]
The controller's view class and the mailer's view class are not connected. You'll need to set the theme name in both places.

**Comment by umer936** [comment]
... That makes a lot of sense. 

Fixed by adding 
```php
    public function viewBuilder(): ViewBuilder
    {
        $viewBuilder = parent::viewBuilder();
        $viewBuilder->setTheme(SITE_KEY);
        return $viewBuilder;
    }
```
to `src/Mailer/UserMailer.php`

Thank you!
