### ISSUE TITLE
EntityInterface::getSource() returns a different value depending on how the entity table is loaded, if the table is from a plugin

### ISSUE THREAD

**Issue by steven-v** [cakephp/cakephp#16419]
### Description

an example from EntityInterface::getSource() return values

```php
// Plugin/src/Controller/EntitiesController.php

// using the default table
$entity = $this->Entities->find()->first();
$entity->getSource(); // returns 'Plugin.Entities'

// using fetchTable string
$entity = $this->fetchTable('Plugin.Entities')->find()->first();
$entity->getSource(); // returns 'Plugin.Entities'

// using fetchTable FQCN
use Plugin\Model\Table\EntitiesTable;

$entity = $this->fetchTable(EntitiesTable::class)->find()->first();
$entity->getSource(); // returns 'Entities'
```
To get the correct source when using fetchTable with FQCN I have to manually set `$this->setRegistryAlias('Plugin.Entities');` in the EntitiesTable.
I would expect getSource() to return the same value regardless of how a table is loaded.

### CakePHP Version

4.3.7

**Comment by markstory** [comment]
When creating a table instance with a fully qualified class name the framework is not able to determine that the class came from a plugin. I don't know if there will be a solution to this.

**Comment by steven-v** [comment]
Am I correct to assume that the correct way to solve this for now is to manually set `$this->setRegistryAlias('Plugin.Entities')`?

The only solution I could think of is using the namespace, but I don't know if that is clean

**Comment by markstory** [comment]
> Am I correct to assume that the correct way to solve this for now is to manually set $this->setRegistryAlias('Plugin.Entities')?

Yeah. Using namespaces is hard plugins don't have to be loaded to be used, and while we try to encourage users use conventional namespaces it doesn't always happen.

**Comment by othercorey** [comment]
There's nothing we can change here, correct?

**Comment by ADmad** [comment]
Nothing for 4.x, we can investigate if we can make things consistent for 5.x.

**Comment by asgraf** [comment]
In this case, I would suggest that getSource() return FQCN string instead of current invalid value. (In 4.x)
This way `$this->fetchTable($entity->getSource())` would no longer throw `MissingTableClassException`

**Comment by ADmad** [comment]
We could probably use `App::shortName()` to get `Plugin.Table` form from FQCN.

**Comment by ADmad** [comment]
Looking into this the value of registry alias when using FQCN is a lie. For e.g. using `$table = $locator->get(Articles::class)` the registry alias for the table instance is set as `Articles` but the instance is actually stored in `TableLocator::$instances` using `Articles::class` as the key. So later if you do `$locator->get($table->getRegistryAlias())` it will create and return a new instance of the class.

So I think the table's registry alias should be set to whatever value is passed to `TableLocator::get()` without any manipulation as that's the value that's actually used to store the instance in the locator.

**Comment by ADmad** [comment]
Commenting out line 219 which manipulates the alias in case of FQCN does not cause any test failures https://github.com/cakephp/cakephp/blob/17dd37309b4517dcc41afd41e3898c3e36239e80/src/ORM/Locator/TableLocator.php#L213-L220.

So I agree with @asgraf's suggestion.
