### ISSUE TITLE
Between not supported as find option.

### ISSUE THREAD

**Issue by bstibi** [cakephp/cakephp#16418]
While refactoring from 2.x to 4.3.x I found the BETWEEN statement is no longer supported as a condition option. Using '<FIELD> BETWEEN ? AND ?' => array('val1','val2') throws a string expected, array found error.

Not wanting to refactor my app to utilize the query builder, is there plans to return this option to the find conditions?

In the meantime I was able to hack in a solution that allows me to utilize the BETWEEN statement, but I'd feel better about it if it was still officially supported. 

I'm pretty much a solo dev and never really contributed to github. But perhaps this is my chance.. I run my on git server, but I'm not familiar with github etiquette or procedures.

**Comment by othercorey** [comment]
You need to use Query::newExpr() to create a QueryExpression and then call `between()`.

https://api.cakephp.org/4.3/class-Cake.Database.Expression.QueryExpression.html#between()

**Comment by markstory** [comment]
Closing as you can still create BETWEEN expressions, it requires different syntax now though. There are some examples of [between on this page](https://book.cakephp.org/4/en/orm/query-builder.html#advanced-conditions)
