### ISSUE TITLE
Automatic mailto: links

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#16424]
### Description

Add something like
```php
filter_var($title, FILTER_VALIDATE_EMAIL)
```
to [HtmlHelper::link](https://github.com/cakephp/cakephp/blob/4.x/src/View/Helper/HtmlHelper.php#L253) so if we do:
```php
$this->Html->link('john@doe.com')
```
it detects the `$title` as an email and automaticaly creates a `mailto:` link.

----

I know I can extend the helper. This is just a suggestion.

I would do a PR but my code is quite poor!

<details>
<summary>In case you want to see my code..</summary>

**I even added cc, bcc, subject and body compatibility**

```php
/**
 * Generates a mailto: link
 *
 * @param string $email Email
 * @param array $options subject, cc, bcc, body
 * @return string
 */
public function email($email, $options = []): string
{
    $args = [];

    // Adds the subject if it exists
    if (!empty($options['subject'])) {
        $args[] = 'subject=' . urlencode($options['subject']);
    }

    // Adds cc and bcc if they exist
    // They can be strings or arrays of emails
    foreach (['cc', 'bcc'] as $key) {
        if (!empty($options[$key])) {
            if (is_array($options[$key])) {
                $options[$key] = implode(', ', $options[$key]);
            }
            $args[] = "{$key}=" . trim($options[$key]);
        }
    }

    // Adds the body if it exists
    if (!empty($options['body'])) {
        $args[] = 'body=' . urlencode($options['body']);
    }

    $args = implode('&', $args);

    return $this->Html->link($email, empty($args) ? "mailto:{$email}" : "mailto:{$email}?{$args}");
}
```
</details>

**Comment by ADmad** [comment]
I wouldn't want an unnecessary `filter_var()` check for each call to `HtmlHelper::link()`. Adding a separate `HtmlHelper::emailLink()` using the code you have shown would be fine.

**Comment by markstory** [comment]
>Adding a separate HtmlHelper::emailLink() using the code you have shown would be fine.

I don't disagree that an additional method would be the safer & more efficient solution. I wonder if one of the following would let us meet in the middle on performance.

```php
// Using an option. We could infer based on the option that the link
// should be a mailto.
$this->Html->link('user@example.org', [], ['_mailto' => true]);

// Using a string prefix. I like this less as it adds a few more function 
// calls to detect the prefix and I feel that sniffing the prefix is on 
// the wrong side of 'good magic'.
$this->Html->link('mailto:user@example.org');
```

Does the option feel like more or less 'work' to use than a separate method?

**Comment by ADmad** [comment]
> $this->Html->link('user@example.org', [], ['_mailto' => true]);

This doesn't seem very convenient to use but I don't mind it.

> $this->Html->link('mailto:user@example.org');

I don't like this because as you said it would involve additional code to check the prefix.

**Comment by othercorey** [comment]
I don't expect to use this either way, but the `_mailto` option feels very obscure.

**Comment by T0mats0** [comment]
I like emailLink() my IDE can autocomplete that. It doesn't know about parameters in an array.
