### ISSUE TITLE
Possible PHP 8.1 deprecated code in Route.php? 

### ISSUE THREAD

**Issue by VARGA-Peter** [cakephp/cakephp#16425]
### Description

I receive this under PHP 8.1 

> parameter #1 ($string) of type string is deprecated [CORE/src/Routing/Route/Route.php, line 810]

the exactly same code works under PHP 8.0 without any warning. I think It should be caught in `Route.php` - or do you have any idea how I can fix it at my site?

It is this code:

```
    $editLink = $this->Html->link(
        $editButton,
        [
            'controller'    => $controllerName,
            'action'        => 'edit', $currentRow->id,
            $base64Format
        ],
        [   'escape' => FALSE ]
    );

```

### CakePHP Version

4.3.7

### PHP Version

8.1

**Comment by ndm2** [comment]
That doesn't look like the complete error message.

I would suspect that one of the values in your URL parameters array is `null`, which could indicate that there's something that you need to fix in your code/data.

**Comment by VARGA-Peter** [comment]
OK, you are right. I rebuilt the code and I am now **NOT** passing a `NULL` value which was before 8.1 accepted in the function.

Thx

PS: It was `$base64Format` which sometimes was `NULL`.
