### ISSUE TITLE
Testsuite: Recreating EventManager on setUp prevents global listeners to work in tests

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16437]
### Description

Olive (in Slack) and I encountered an issue related to the https://github.com/UseMuffin/Footprint plugin and it not working in tests.

Basically what we did was add this to the `config/bootstrap.php`

```
$eventManager = EventManager::instance();
$eventManager->on(
    'Server.buildMiddleware',
    function (EventInterface $event, MiddlewareQueue $middleware) {
        $middleware->insertAfter(AuthenticationMiddleware::class, new FootprintMiddleware());
    }
);
```

So the FootprintMiddleware always gets added after the AuthenticationMiddleware.
It works beautifully in "normal" web requests but didn't work when running PHPUnit.

In the end it turns out the main cause is the following line:
https://github.com/cakephp/cakephp/blob/4.x/src/TestSuite/TestCase.php#L258

With that the global EventManager (which we use in the above code example AND the Footprint Plugin uses as well - https://github.com/UseMuffin/Footprint/blob/master/src/Plugin.php#L31) will be re-created before each test is run.

Removing that line fixes our issue but I am not sure if this will cause problems further down the line in a more "event heavy" system.

This also seems to be an "age old" problem looking at https://stackoverflow.com/questions/38495504/cakephp-3-behavior-not-loaded-during-controller-unit-test

What are your thoughts?

### CakePHP Version

4.3.7

### PHP Version

8.1

**Comment by LordSimal** [comment]
The reason I am adding the FootprintMiddleware via the `Server.buildMiddleware` event is the fact, that I am using `CakeDC/Users` and therefore don't have access to the place where the `AuthenticationMiddleware` is being added.
https://github.com/CakeDC/users/blob/master/src/Loader/MiddlewareQueueLoader.php#L86

**Comment by ndm2** [comment]
Have you tried using `Application::bootstrap()` instead? Unlike `config/bootstrap.php`, which is only being loaded once, the `bootstrap()` method will be invoked on every integration test request.

**Comment by LordSimal** [comment]
Damn, I got confused because I thought due to this line https://github.com/cakephp/cakephp/blob/4.x/src/Http/BaseApplication.php#L173 it will be no problem
But I missread `require_once` and instead thought its a normal `require` 🙈 

Yes, it does indeed work if I put my code from above inside the `Application::bootstrap()` method.
