### ISSUE TITLE
BelongsToMany + matching ignores bindingKey

### ISSUE THREAD

**Issue by zachee54** [cakephp/cakephp#16432]
### Description

BelongsToMany with custom bindingKey works well with `contain()`, but ignores the bindingKey with `matching()` and fallbacks to primary key.

## Database schema
```
CREATE TABLE `tags` (
  `id` int unsigned NOT NULL,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `articles` (
  `id` int unsigned NOT NULL,
  `title` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `articles_tags` (
  `tagname` varchar(50) NOT NULL, // Be aware that junction table references tag names
  `article_id` int unsigned NOT NULL,
  PRIMARY KEY (`tagname`,`article_id`)
);
```
## Model definition
```
class TagsTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('tags');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsToMany('Articles', [
            'foreignKey' => 'tagname',
            'targetForeignKey' => 'article_id',
            'bindingKey' => 'name', // This is the point
            'joinTable' => 'articles_tags',
        ]);
    }
}
```
## Controller
```
class TagsController extends AppController
{
    public function index()
    {
        $tags = $this->Tags->find()
          ->matching('Articles', function ($q) {
            return $q->where('Articles.id > 0');
          })
          ->all();

        $this->set(compact('tags'));
    }
}
```
## Generated query
```
SELECT 
  Tags.id AS Tags__id, 
  Tags.name AS Tags__name, 
  ArticlesTags.tagname AS ArticlesTags__tagname, 
  ArticlesTags.article_id AS ArticlesTags__article_id, 
  Articles.id AS Articles__id, 
  Articles.title AS Articles__title 
FROM 
  tags Tags 
  INNER JOIN articles_tags ArticlesTags ON Tags.id = ArticlesTags.tagname 
  INNER JOIN articles Articles ON (
    Articles.id > 0 
    AND Articles.id = ArticlesTags.article_id
  )
```

Obviously `Tags.id = ArticlesTags.tagname` tries to match tag name in junction table with tag id on source table, ignoring the custom binding key.
In contrast, the query works well with contain, although makes impossible to filter with conditions on associated data.

### CakePHP Version

4.3.7

### PHP Version

7.4.3

**Comment by markstory** [comment]
Thank you for the great issue report. I've been able to reproduce locally, and I'll get a pull request opened as soon as I figure out a solution.

**Comment by markstory** [comment]
A temporary workaround is to define the model for the junction table and define the belongsTo association. This will prevent the automatic association generation.

```php
// in your ArticlesTagsTable class add the following association.
        $this->belongsTo('Tags', [
            'bindingKey' => 'name',
            'foreignKey' => 'tagname',
        ]);
```

**Comment by zachee54** [comment]
Yes, I saw the workaround when looking at the source code, but since I couldn't understand the whole logic I decided not to run into a PR myself.
As a workaround, I decided in contrast to create a twin table model such as `NamedTagsTable`, declaring `name` as primary key. This is possible because `name` is unique and non-null in my case, so it's an isomorphic key.
The `NamedTags BelongsToMany Articles` association then doesn't need a custom binding key.

### Correlated enhancement

BTW, I wonder why there isn't any config option for the binding key in the target table.
I mean, it shall be expected to be able to define an `Articles BelongsToMany Tags` association with such a schema. It's sadly impossible due to the target-binding key customization lack.
Is it intentional ? Since CakePHP offers a binding key option in source table, it would be logical to offer the same feature for the symetric association.

**Comment by markstory** [comment]
> BTW, I wonder why there isn't any config option for the binding key in the target table. ... Is it intentional?

I don't think this was an explicit decision. It was likely never implemented as the author of bindingKey didn't think of it at the time.

> As a workaround, I decided in contrast to create a twin table model such as NamedTagsTable, declaring name as primary key. This is possible because name is unique and non-null in my case, so it's an isomorphic key.

This is generally what I would recommend too. I'm not a big proponent of `bindingKey` but it does provide a useful escape hatch when working with existing schemas.
