### ISSUE TITLE
'list' finder doesn't work in contain - Easy solution for that

### ISSUE THREAD

**Issue by rzcrx** [cakephp/cakephp#16446]
### Description

Hi everybody, and first : **a huge THANK YOU for all the amazing things your are creating !!!** [🙏]

So... In cake 4.* latest version (no need more precision as the "pb" is located)

**Here is what I do** (`Sheets` -> `SheetData` is a `hasMany` relation) : 

```
$myResults = $sheetsTable
	->find()
	->contain([ 'SheetData' => function($q) {
		return $q
		->applyOptions(['preserveKeys' => true]) // see explanation below
		->select(['id', 'value', 'field_id', 'sheet_id'])
		->find('list', [ 'keyField' => 'field_id', 'valueField' => function($item) { return $item; } ]);
	} ])
	->first();
```
		
**The result :** 
```

App\Model\Entity\Sheets Object
(
	[id] => 1
	[sheet_data] => Array
		(
			[**0**] => App\Model\Entity\SheetDataTable Object
				(
					[id] => 4
					[sheet_id] => 1
					[field_id] => 998
					[value] => 'blabla 998'
				)

			[**1**] => App\Model\Entity\SheetDataTable Object
				(
					[id] => 23
					[sheet_id] => 1
					[field_id] => 999
					[value] => 'blabla 999'
				)
		)
)		
```

**As I am expecting :** 
```

App\Model\Entity\Sheets Object
(
	[id] => 1
	[sheet_data] => Array
		(
			[**998**] => App\Model\Entity\SheetDataTable Object
				(
					[id] => 4
					[sheet_id] => 1
					[field_id] => 998
					[value] => 'blabla 998'
				)

			[**999**] => App\Model\Entity\SheetDataTable Object
				(
					[id] => 23
					[sheet_id] => 1
					[field_id] => 999
					[value] => 'blabla 999'
				)
		)
)		
```

**A simple solution is to keep the associativity which is properly calculated before, but... erased in SelectLoader:_buildResultMap**

- In src/ORM/Association/Loader/SelectLoader.php:_buildResultMap:477

- Now : 

```
	foreach ($fetchQuery->all() as $result) {
            $values = [];
            foreach ($key as $k) {
                $values[] = $result[$k];
            }
            if ($singleResult) {
                $resultMap[implode(';', $values)] = $result;
            } else {
                $resultMap[implode(';', $values)][] = $result;
            }
        }
```
		
- Update suggested (inside comments) : 
```

	/*****
	### Option 1 (my prefered one as it is more generic) : 
		$fetchQueryOptions = $fetchQuery->getOptions();
		$preserveKeys = $fetchQueryOptions['preserveKeys'] ?? false;
	### Option 2 : 
		$fetchQueryOptions = $fetchQuery->getOptions();
		$preserveKeys = $fetchQueryOptions['keyField'] ?? false;
	*****/
		
	foreach ($fetchQuery->all() as /**** $resultKey => ****/ $result) {
		$values = [];
		foreach ($key as $k) {
			$values[] = $result[$k];
		}
		if ($singleResult) {
			$resultMap[implode(';', $values)] = $result;
		} else {
			/****
			### Both options
			if ($preserveKeys) {
				$resultMap[implode(';', $values)][$resultKey] = $result;
			} else {
				$resultMap[implode(';', $values)][] = $result;
			}
			****/
			$resultMap[implode(';', $values)][] = $result;
		}
	}
```

And with that, I am the happiest man in the world 😃 ! 
I think this update is very usefull for processes that need to point directly on a junction key. That's my case with a lot of data. I got 20000 sheets, that have 105 sheetData each. And I must point on data field_id key -> if key association is made in SelectLoader, it saves 30/40% of process time. I tested.

Thanks by advance and Have a good week-end everybody.

Christophe

### CakePHP Version

4.*

**Comment by markstory** [comment]
> And I must point on data field_id key -> if key association is made in SelectLoader, it saves 30/40% of process time. I tested.

Where is this performance improvement coming from. Nothing in the proposed changes looks like it would yield that kind of improvement. Or is the improvement coming from not having to iterate the results again?

I'm hesitant to add new options that could be applied to all find() operations when only `find(list)` could occasionally use them. The proposed change looks like it could cause problems with other query patterns that may attempt to use `preserveKeys` which makes me concerned that this change could create more bugs. Perhaps there is another solution that we can apply to only findList() though.

**Comment by rzcrx** [comment]
Thank you for your response.

Well, I understand : it adds lines in one of the most used function of the ORM. Anyway, with a new option key, I think this is relatively safe. But I also know that you... know the ORM better than me, of course :-) !

As the result of the findList is reformatted in SelectLoader, I think that the only solution should be to modify SelectLoader. Maybe the findList function itself can add the option ? Something like :

```
    public function findList(Query &$query, array $options): Query
    {
        $query->applyOptions(['_finder' => 'list']);
	...
	$query->applyOptions(['_preserveKeys' => true]);
	...
    }
```

If I submitted you this issue, this is because the findList use in contain is allowed and documented. I thought that it could be improved to fit the findList result structure specification. 

**Here is my current problem :**

**1/  without the improvement :  about 100 000 000 loops**
```
$exportRows = [];
foreach($sheets as $sheet) {                                // 20 000 loops
     $exportRow = [];
     foreach($exportColumns as $columnFieldId) {             // 105 loops
          foreach($sheet->sheet_data as $sheetData) {         // (average 52 loops)
               if ($sheetData['field_id'] === $columnFieldId) {
                    $exportRow[] = $sheetData['value'];
                    break;
               }
          }
     }
     $exportRows[] = $exportRow;
}
```

**2/ with the improvement about 2 000 000 loops**
```
foreach($sheets as $sheet) {                                // 20 000 loops
     $exportRow = [];
     foreach($exportColumns as $columnFieldId) {             // 105 loops
          $exportRow[] = $sheet->sheet_data[$columnFieldId]['value'];
     }
     $exportRows[] = $exportRow;
}
```

Well, I have other solutions to optimize this personal case : making my own "hasMany relationship builder" for example. So don't worry about me ;-)

If I can help, do not hesitate ! 
Have a good day.

**Comment by ADmad** [comment]
Instead of using `find('list')` inside `contain()`, `formatResults()` could also be used for the main query to achieve the same data structure

**Comment by rzcrx** [comment]
Yes ADmad, for the record, here is the workaround I am using : 
```

$mySheets = $sheetsTable->find()->formatResults(
	function(\Cake\Collection\CollectionInterface $sheets) {
		$sheets = $sheets->indexBy('id');
		if ($sheetKeys = array_keys($sheets->toArray())) {
			$sheetDataGrouped = TableRegistry::getTableLocator()
				->get('SheetData')
				->find('list', ['keyField' => 'field_id', 'valueField' => 'value', 'groupField' => 'sheet_id'])
				->select(['id', 'field_id', 'value', 'sheet_id'])
				->where(['SheetData.sheet_id IN' => $sheetKeys])
				->toArray();
			foreach($sheets as $sheetId => $sheet) {
				$sheet->sheet_data = $sheetDataGrouped[$sheetId] ?? [];
			}
		}
		return $sheets;
	}
);
```

**Comment by markstory** [comment]
> Instead of using find('list') inside contain(), formatResults() could also be used for the main query to achieve the same data structure

It would be nice if we didn't require user-land code to replace `find(list)` on HasMany associations. Historically `find(list)` has not worked with associations loaded with `contain()` well, but it would be nice if it 'just worked'.
