### ISSUE TITLE
Multi-word Model Issue

### ISSUE THREAD

**Issue by rkhe** [cakephp/cakephp#16454]
### Description

Hi All, 

Has somebody encounter an issue when having a multi-worded entity? 
I created a database called `purchase_orders` and ran a bake all cli to scaffold. 

All generated codes are looking fine. Table, Entity and Controller.  Looks like `$this->PurchaseOrders` is null.

Single-worded works fine without issues.

Error: 
`[Notice (1024)](javascript:void(0);): Undefined property: PurchaseOrdersController::$PurchaseOrders in C:\....\src\Controller\PurchaseOrdersController.php on line 24 [CORE\src\Controller\Controller.php, line 329]
[Code](javascript:void(0);) [Context](javascript:void(0);)
Cake\Controller\Controller::__get() - CORE\src\Controller\Controller.php, line 329
App\Controller\PurchaseOrdersController::index() - APP/Controller\PurchaseOrdersController.php, line 24
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 539
Cake\Controller\ControllerFactory::handle() - CORE\src\Controller\ControllerFactory.php, line 140
Cake\Controller\ControllerFactory::invoke() - CORE\src\Controller\ControllerFactory.php, line 115
Cake\Http\BaseApplication::handle() - CORE\src\Http\BaseApplication.php, line 317
Cake\Http\Runner::handle() - CORE\src\Http\Runner.php, line 77
Authorization\Middleware\RequestAuthorizationMiddleware::process() - ROOT\vendor\cakephp\authorization\src\Middleware\RequestAuthorizationMiddleware.php, line 102
Cake\Http\Runner::handle() - CORE\src\Http\Runner.php, line 73
Authorization\Middleware\AuthorizationMiddleware::process() - ROOT\vendor\cakephp\authorization\src\Middleware\AuthorizationMiddleware.php, line 129
Cake\Http\Runner::handle() - CORE\src\Http\Runner.php, line 73
Authentication\Middleware\AuthenticationMiddleware::process() - ROOT\vendor\cakephp\authentication\src\Middleware\AuthenticationMiddleware.php, line 124
Cake\Http\Runner::handle() - CORE\src\Http\Runner.php, line 73
Cake\Http\Middleware\CsrfProtectionMiddleware::process() - CORE\src\Http\Middleware\CsrfProtectionMiddleware.php, line 174
Cake\Http\Runner::handle() - CORE\src\Http\Runner.php, line 73`

### CakePHP Version

4.3.7

### PHP Version

7.4

**Comment by othercorey** [comment]
Please discuss this in the slack channel.
