### ISSUE TITLE
Handle numeric keys in \Cake\Http\Cookie\CookieCollection::createFromHeader()

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#16451]
### Description

Handling numeric cookie names in `Handle numeric keys in \Cake\Http\Cookie\CookieCollection::createFromHeader()` is required.

There is cookie from real website that causes `TypeError` "rawurlencode() expects parameter 1 to be string, int given" 
```

$collection = \Cake\Http\Cookie\CookieCollection::createFromHeader([
	'14=tid=18%2D04%2D2022+10%3A45%3A00; expires=Mon, 17-Apr-2023 22:00:00 GMT; path=/'
]);
$collection->addToRequest(new \Cake\Http\Client\Request());
```

### CakePHP Version

4.3

### PHP Version

7.2

**Comment by saeideng** [comment]
#16452 has been merged
