### ISSUE TITLE
4.4 - Required content-negotiation

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#16467]
### Problem

With the new content-type negotiation APIs it is not currently possible to **require** content-type negotiation be performed and that there is no fallback to an HTML error page.

### Proposal

We could add another View class that handles this usage. With this approach the behavior is opt-in, and maintains the declarative nature of most application implementations.

The new class could be `Cake\View\NegotiationRequiredView` . This class would:

* Set the status code to 406
* Remove the body of the response.
* Retain all other headers currently set.

To achieve this the `NegotitationRequiredView` would have a `contentType()` of `'*'`. This would require a special case in Controller logic, but I think the special case in framework code is worth the improved developer experience.

### CakePHP Version

4.4

**Comment by othercorey** [comment]
A couple questions:

Do we need to allow XmlView to support all of the mime types listed in Response? Is that something any api requires? I'm not sure where we use the multi-mime types listed in Response.

Do we need to allow something other than html to be the default? For example: json and xml api would default to json?

**Comment by markstory** [comment]
> Do we need to allow XmlView to support all of the mime types listed in Response? Is that something any api requires?

I don't think so. While one *could* argue that it should be possible. Practically user land code is likely only going to be using a single content-type. If applications need to support multiple XML content types, they can subclass the `XmlView` we provide for each additional flavour of XML they need.

> Do we need to allow something other than html to be the default? For example: json and xml api would default to json?

I don't know if that is a scenario we need to design around. Historically we've not provided APIs for that. It can be done of course using a `beforeRender` hook:

```php
public function beforeRender($event)
{
    if (!$this->request->getHeaderLine('Accept')) {
         $this->viewBuilder()->setClassName(JsonView::class);
    }
}
```

**Comment by othercorey** [comment]
> I don't know if that is a scenario we need to design around. Historically we've not provided APIs for that. It can be done of course using a `beforeRender` hook:

True. I was only thinking of debug scenarios using curl on the command line without setting everything properly. I've never developed a multi-mime api though.
