### ISSUE TITLE
Radio and Multiple Checkbox Hidden Input id is missing in 3.x and 4.x

### ISSUE THREAD

**Issue by chetanvarshney** [cakephp/cakephp#16461]
### Description

When we generate radio and multiple checkbox input using form helper, it generates hidden input without id attribute.
Due to this issue I am not able to show error on ajax/javascript validations.

syntax
```
<?php echo $this->Form->control('Users.gender', ['type'=>'radio', 'label'=>false, 'options'=>['Male'=>'Male', 'Female'=>'Female']]);?>
<?php echo $this->Form->control('Users.hobbies', ['type'=>'select', 'label'=>false, 'multiple'=>'checkbox', 'options'=>['Cricket'=>'Cricket', 'Tennis'=>'Tennis', 'Football'=>'Football']]);?>
```

Solution
root\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php

```
function multiCheckbox()
add id in $hiddenAttributes
'id' => $attributes['id'].'-',

function radio()
add id in $this->hidden( function call
'id' => $attributes['id'].'-',
```

It is working fine in Cakephp 2.x

### CakePHP Version

3.x and 4.x

**Comment by markstory** [comment]
Hidden inputs aren't visible though. How would they have validation errors on them?

**Comment by chetanvarshney** [comment]
Let me explain,

For server side ajax validations, I use model validations and return errors in key value pair
For e.g.
Users.name = 'Please enter your name',
Users.gender= 'Please select your gender',
I pass these errors in ajax response, and javascript process these errors in loop and create id in variables (as per cakephp dom id standard)
so generated ids are users-name and users-gender (for hidden inputs I saw ids are like 'users-gender-')
now javascript adds errors messages in form by finding input ids.

Please see screen shot 1: before modifying Form helper, it does not add validation on radio input
 
![16461_ss1](https://user-images.githubusercontent.com/325154/164883043-e976aa13-d511-4ee6-9fdf-604f3654f4ce.png)

Please see screen shot 2: after modifying Form helper, it does add validation on radio input

![16461_ss2](https://user-images.githubusercontent.com/325154/164883065-662e0aec-99ee-4956-9f3a-8e736779a9d9.png)

I hope it helps you to understand the issue

**Comment by markstory** [comment]
Ok. I think there are probably more robust ways to implement that behavior but can also appreciate that a simple solution is also possible. If you're willing to do the work to add the attributes back in and update the tests we can talk about this more.

**Comment by chetanvarshney** [comment]
Yes Mark, this solution is simple and effective in CakePHP 2.x, I can modify Form helper and send pull request.

**Comment by chetanvarshney** [comment]
Hi @markstory I am working on test cases and found 1 more issue in CakePHP form behavior

Generating radio options in 2 ways giving different ids
Case 1: Without custom name

```
<?php echo $this->Form->control('Model.field', ['type'=>'radio', 'label'=>false, 'options'=>['Option A', 'Option B']]);?>

//output with ids like model-field-0 and model-field-1 SEEMS OK
<div class="input radio"><input type="hidden" name="Model[field]" value=""><label for="model-field-0"><input type="radio" name="Model[field]" value="0" id="model-field-0">Option A</label><label for="model-field-1"><input type="radio" name="Model[field]" value="1" id="model-field-1">Option B</label></div>

<?php echo $this->Form->radio('Model.field', ['Option A', 'Option B']);?>

//output with ids like model-field-0 and model-field-1 SEEMS OK
<input type="hidden" name="Model[field]" value=""><label for="model-field-0"><input type="radio" name="Model[field]" value="0" id="model-field-0">Option A</label><label for="model-field-1"><input type="radio" name="Model[field]" value="1" id="model-field-1">Option B</label>
```

Case 2: With custom name
```
<?php echo $this->Form->control('Model.field', ['type'=>'radio', 'label'=>false, 'options'=>['Option A', 'Option B'], 'name'=>'Model[custom]']);?>

//output with ids like model-field-0 and model-field-1 SEEMS WRONG
<div class="input radio"><input type="hidden" name="Model[custom]" value=""><label for="model-field-0"><input type="radio" name="Model[custom]" value="0" id="model-field-0">Option A</label><label for="model-field-1"><input type="radio" name="Model[custom]" value="1" id="model-field-1">Option B</label></div>

<?php echo $this->Form->radio('Model.field', ['Option A', 'Option B'], ['name'=>'Model[custom]']);?>

//output with ids like model-custom-0 and model-custom-1 SEEMS OK
<input type="hidden" name="Model[custom]" value=""><label for="model-custom-0"><input type="radio" name="Model[custom]" value="0" id="model-custom-0">Option A</label><label for="model-custom-1"><input type="radio" name="Model[custom]" value="1" id="model-custom-1">Option B</label>
``` 
What are your thoughts?

**Comment by chetanvarshney** [comment]
l have also seen issue in other inputs
```
//without custom name
<?php echo $this->Form->control('Model.field', ['type'=>'text', 'label'=>false, 'class'=>'form-control']);?>

//output with correct id SEEMS OK
<input type="text" name="Model[field]" class="form-control" id="model-field">

//with custom name
<?php echo $this->Form->control('Model.field', ['type'=>'text', 'label'=>false, 'class'=>'form-control', 'name'=>'Model[custom]']);?>

//output with incorrect id SEEMS WRONG
<input type="text" name="Model[custom]" class="form-control" id="model-field">
```

**Comment by markstory** [comment]
> What are your thoughts?

The id generation is not wrong. Custom name attributes don't influence id generation in other inputs either.

**Comment by chetanvarshney** [comment]
> > What are your thoughts?
> 
> The id generation is not wrong. Custom name attributes don't influence id generation in other inputs either.

I agree Custom name attributes don't influence id generation in other inputs either in CakePHP 2.x as well.

Then following is wrong only, because it is taking custom name in generating ids

```
<?php echo $this->Form->radio('Model.field', ['Option A', 'Option B'], ['name'=>'Model[custom]']);?>

<input type="hidden" name="Model[custom]" value=""><label for="model-custom-0"><input type="radio" name="Model[custom]" value="0" id="model-custom-0">Option A</label><label for="model-custom-1"><input type="radio" name="Model[custom]" value="1" id="model-custom-1">Option B</label>
```

**Comment by markstory** [comment]
> Then following is wrong only, because it is taking custom name in generating ids

Possibly, however changing element IDs will most certainly break existing applications so we can't do it until 5.x
