### ISSUE TITLE
TreeBehavior recover(): Column 'id' in order clause is ambiguous

### ISSUE THREAD

**Issue by hacheraw** [cakephp/cakephp#16476]
### Description

If the target Table has a behavior like `TranslateBehavior` you must `->removeBehavior('Translate')` before running `->recover()` or an SQL error will be thrown:

#### SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous

Generated Query:
```
SELECT
    Categories.id AS Categories__id
FROM
    categories Categories
LEFT JOIN i18n Categories_name_translation ON
    (
        Categories_name_translation.model = :c0 AND Categories_name_translation.field = :c1 AND Categories_name_translation.locale = :c2 AND Categories.id = Categories_name_translation.foreign_key
    )
WHERE
    (parent_id) IS NULL
ORDER BY
    id
```

I think the problem is in the `ORDER BY` because all other use `Caregories.id`

### CakePHP Version

4.3.5

### PHP Version

8.0

**Comment by dereuromark** [comment]
Where does your "order by" come from?
What's the code snippet?
Looks like a developer injected sort order which is not (model) prefixed.

**Comment by hacheraw** [comment]
You are right.
It's conditionally happening in my project.

This code:

```php
$catT = $this->fetchTable('Categories');
$catT->recover();
die('hecho');
```

Works on any Controller inside my `/admin` prefix but does not work on any controller outside prefix.

Quite weird but almost certainly my fault.

Still haven't found any differences between unprefixed and prefixed Controllers on my code...

----

Update: I just created an all-new project with just categories and i18n tables and admin prefix. **There it works fine**... so... you may close this.
