### ISSUE TITLE
TestFixture::_tableFromClass is double pluralizing!

### ISSUE THREAD

**Issue by OneHatRepo** [cakephp/cakephp#16496]
### Description

The TestFixture::_tableFromClass method should first singularize the table name.

Line 170 of Cake\TestSuite\Fixture\TestFixture should read:
`return Inflector::tableize(Inflector::singularize($table));`

The table name is _already_ plural, and tableize runs it through pluralize again. In most cases, this is okay, but in certain cases it fails. Example: With 'ChildrenFixture' it looks for 'ChildrensFixture'

Alternatively, if you wanted to be more generalized, you could change line 478 of Cake\Utility\Inflector to:
`$result = static::pluralize(static::singularize(static::underscore($className)));`
... as I think this could take either a singular or plural $className and would handle it properly; but I don't know what the knock-on effects of that might be.

### CakePHP Version

4.3.8

**Comment by markstory** [comment]
Are you able to provide a fixture that reproduces the problem you're having? Changing inflections often breaks existing applications, and it may be that your fixture is incorrect.

**Comment by OneHatRepo** [comment]
Nevermind. A simplified test case shows the error is in my code. Sorry about that!
