### ISSUE TITLE
Non-consistent afterSaveCommit dispatch in saveMany in Table.php

### ISSUE THREAD

**Issue by OlofMorra** [cakephp/cakephp#16499]
### Description

When executing a save on a table, Model.afterSaveCommit is dispatched if the transaction is committed. However, this method is also used for saveMany (and saveManyOrFail), so in a different context. Then, the save method does not dispatch Model.afterSaveCommit as the transaction is not yet committed. Now, the save method cleans the entity and sets new to false. After all calls to save from saveMany Model.afterSaveCommit is dispatched with cleaned entities, hence, the information for dirty fields and original values is lost and is not passed to Model.afterSaveCommit. 

In cakephp/src/ORM/Table.php
```php

protected function _saveMany(iterable $entities, $options = []): iterable
    {
        ...

        try {
            $this->getConnection()
                ->transactional(function () use ($entities, $options, &$isNew, &$failed) {
                    foreach ($entities as $key => $entity) {
                        $isNew[$key] = $entity->isNew();
                        // normal save called here, so each entity is cleaned here
                        if ($this->save($entity, $options) === false) {
                            $failed = $entity;

                            return false;
                        }
                    }
                });
        } catch (Exception $e) {
            $cleanup($entities);

            throw $e;
        }

       ...

        if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
            foreach ($entities as $entity) {
                // Cleaned entities are passed with the dispatch, missing dirty and original fields
                $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
            }
        }

        return $entities;
    }

public function save(EntityInterface $entity, $options = [])
    {
        ...

        if ($success) {
            // transaction is committed for single save, but not for saveMany operation
            if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
                $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
            }
            // For saveMany the entity is cleaned here, but the dispatch above was not executed.
            // Hence, all fields unset by clean are lost (dirty, original, etc.)
            if ($options['atomic'] || $options['_primary']) {
                $entity->clean();
                $entity->setNew(false);
                $entity->setSource($this->getRegistryAlias());
            }
        }

        return $success;
    }
```

What I expected is that a saveMany dispatches the model.afterSaveCommit with the dirty and original values. So, I propose to execute the clean operation for entities saved via saveMany only after the dispatchEvent in the _saveMany method. 

Let me know if you agree with my logic, then I will make an MR!

### CakePHP Version

4.3.9

### PHP Version

8.1.5

**Comment by lordphnx** [comment]
Yes, we are experiencing a similar issue

**Comment by markstory** [comment]
This issue has been around since the introduction of the `afterSaveCommit` event to `saveMany` in #14659. I agree that normalizing the behavior would be good.

**Comment by othercorey** [comment]
Was this fixed with the linked PR?

**Comment by OlofMorra** [comment]
@ADmad Thank you for the fix!
