### ISSUE TITLE
Router::url full not work in cli env (ie: Queue Job, Command, etc...)

### ISSUE THREAD

**Issue by lepresk** [cakephp/cakephp#16490]
### Description

The full url (hostname included) is not returned when calling `Router::url($url, true)` in the cli env (ie: Queue Job, Command, etc...)
How to ?

### CakePHP Version

4.3.7

### PHP Version

8.1.2

**Comment by ADmad** [comment]
There's no host/domain name available in CLI context. You need to explicitly set the `App.fullBaseUrl` config in `config/app.php` to get full URLs in CLI environment.

**Comment by lepresk** [comment]
Won't this affect the global routing system?

**Comment by othercorey** [comment]
Setting the fullBaseUrl config will affect the routing system. How you separate the CLI and Web instances/config is up to you.

**Comment by lepresk** [comment]
> Setting the fullBaseUrl config will affect the routing system. How you separate the CLI and Web instances/config is up to you.

Please can you clarify me how to do these separation, because there are only one app.php (app_local.php) ?

**Comment by LordSimal** [comment]
You already have that logic present inside your `config/bootstrap.php` via the `$isCli` variable. See https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L136

The `app.php` file is loaded via this line
https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L81
and the `app_local.php` file is loaded via this line
https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L91

So any `Configure::write()` call after those 2 lines will overwrite your config which is present in either `app.php` or `app_local.php`

**Comment by lepresk** [comment]
> You already have that logic present inside your `config/bootstrap.php` via the `$isCli` variable. See https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L136
> 
> The `app.php` file is loaded via this line https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L81 and the `app_local.php` file is loaded via this line https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L91
> 
> So any `Configure::write()` call after those 2 lines will overwrite your config which is present in either `app.php` or `app_local.php`

Thanks for the trick!
