### ISSUE TITLE
False is not Empty check in whereInList()

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#16505]
### Description

Input:

```php
$this->Model->whereInList ( 'id', [], ['allowEmpty' => true])
```

Expected Output:

```php
[]
```

Output currently:
`Error: Impossible to generate conditions with empty list of values for field (id)`

Expected Solution:

This:

```php
if ($options['allowEmpty'] && !$values)
```

https://github.com/cakephp/cakephp/blob/4.x/src/Database/Query.php#L1085

Could be:

```php
if ($options['allowEmpty'] && empty($values))
```

### CakePHP Version

4.3

### PHP Version

8.1

**Comment by othercorey** [comment]
That change would do the opposite. We want to check for an empty array.

**Comment by karmicdice** [comment]
had an oversight, didnt remove !.
Corrected it now.

**Comment by othercorey** [comment]
We test this case and the code change doesn't look like it would make a difference. 

https://github.com/cakephp/cakephp/blob/4.x/tests/TestCase/Database/QueryTest.php#L1581

Can you give more information? Are you passing `[]` exactly?

**Comment by karmicdice** [comment]
Yes, passed exactly `[]`

**Comment by markstory** [comment]
What are you expecting the generated SQL for this to be?  Generating a condition like `WHERE id IN ()` will result in a query that will never match anything which is why we raise an error presently.

**Comment by othercorey** [comment]
> Yes, passed exactly `[]`

Can you show more of the query? The example code doesn't look valid.

**Comment by ADmad** [comment]
`IN ()` is invalid syntax http://sqlfiddle.com/#!9/38f7db/1.

So throwing an exception when the list is empty is the appropriate thing todo. Users should check for non empty list before hand.

**Comment by othercorey** [comment]
Well the allowEmpty option allows passing any empty array. The code works so must be something else.

**Comment by ADmad** [comment]
Ah right, so mostly likely he isn't passing the arguments he thinks he is.

**Comment by karmicdice** [comment]
> Ah right, so mostly likely he isn't passing the arguments he thinks he is.

I wrote the code on original post.

**Comment by karmicdice** [comment]
> What are you expecting the generated SQL for this to be?  Generating a condition like `WHERE id IN ()` will result in a query that will never match anything which is why we raise an error presently.

There is a use case I have where I get the list of ids matching a keyword, pass it in iterator and generate an array of ids... then pass the ids to fetch the rows to send in my api.
Sometimes when it doesn't match, it returns an empty list of array which then gets passed into this. I have added a condition `allowEmpty` so that it doesn't throw a 500 (though from design point of view, it should) but instead I want to return an empty array to the user through api.
It doesn't say in the docs but I can see it there in the functionality...
However even after doing 'allowEmpty' it still threw a 500 whereas the "where" should have been replaced from using an `in ()` to `1=0` thus returning empty.
The idea of allowEmpty (as I presume) is to allow an empty list of ids, if ids are an array, pass it in `in` or replace it altogether.

**Comment by markstory** [comment]
>However even after doing 'allowEmpty' it still threw a 500 whereas the "where" should have been replaced from using an in () to 1=0 thus returning empty.

We will need some help reproducing that. The logic of whereInList() is pretty simple and we have tests covering it behaving correctly.

> There is a use case I have where I get the list of ids matching a keyword, pass it in iterator and generate an array of ids... then pass the ids to fetch the rows to send in my api.

Ok, but why do you want to run a query when you can skip running it? If the list of ids is empty you could skip the query build and execution and make an empty array instead?

**Comment by karmicdice** [comment]
Oddly enough. It started working.!

However, I believe it is `more semantic` to use an `empty` to check whether an array is empty.

**Comment by othercorey** [comment]
> However, I believe it is `more semantic` to use an `empty` to check whether an array is empty.

Not really. `empty()` does more than check the array length and so does `falsy` (or bool conversion).
