### ISSUE TITLE
page(int, int) does not behave as expected in a loop

### ISSUE THREAD

**Issue by darkcry** [cakephp/cakephp#16500]
### Description

When the query object is used inside a loop it will skip entries.
I assume that the offset parameter is somehow not reset or is applied before each page() statement.

Below is my current used code. From a datasource with 23 entries this will loop 5 times but $lEntities has unexpected values
1. Loop contains entries from 1-5
2. Loop contains entries from 11-15
3. Loop contains entries from 21-23
4. Loop empty
5. Loop empty

```        
        //fetch entities which require sync
        $oSearchQuery = $oSearchQuery ?? AttributeTypesTable::T()
            ->find('all', ['archived' => 1])
            ->find('requireSynchronization');

        $iMaxObjects = $oSearchQuery->count();

        //determine loops to process all entities, we have to limit the fetched data to not exceed memory limit
        $iItemsPerRun = 5;
        $iRequiredIterations = ceil( $iMaxObjects / $iItemsPerRun );

        for($iCurrentIteration=1; $iCurrentIteration <= $iRequiredIterations; $iCurrentIteration++)
        {
            /** @var AttributeType[] $lEntities */
            $lEntities = $oSearchQuery
                ->contain([
                    'AttributeUnits',
                    'AttributeListOptions',
                    'DeployTargetAttributes'
                ])
                ->page($iCurrentIteration, $iItemsPerRun)
                ->toArray();

            //do stuff with loaded entities
        }
```

when i change the statement to
` ->page(1, $iItemsPerRun)`
it is working fine. But that is counter intuitive since i do not want do retrieve always the data from page 1.

If not a bug please add some text to the page() method who is describing this behavior.
Or am i using the statement incorrect for that use case when i can only fetch a limited amount of data but have to process all entries?

### CakePHP Version

4.2.10

### PHP Version

8.0

**Comment by markstory** [comment]
Have you looked at the generated query log that you're find operations are generating? The page() method wraps setting the `offset()` and `limit()` clauses on a query. There are several tests covering the `page()` method and that method is also the underpinnings of how pagination works in CakePHP as well.

**Comment by darkcry** [comment]
Log was correct.
Later in the process i set a flag to each entity and with that the query did no longer match these entities again so it is absolutely required the use `->page(1, $iItemsPerRun)`

Issue can be closed
