### ISSUE TITLE
A vague full screen error message when headers already send and debugging enabled

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16508]
### Description

This error is exclusive to CakePHP 4.x branch, and does not occur in CakePHP 3.x branch

What i did:

1) in app_local.php `'debug' => true`
2) store any data into session in your AppController->beforeFilter() function
3) set invalid chmod in `/tmp/cache/` to generate `SplFileInfo::openFile: failed to open stream: Permission denied` php warning

What happened:

CakePHP throws following TypeError:
```
Argument 1 passed to Cake\Http\Session::_overwrite() must be of the type array, null given, called in vendor/cakephp/cakephp/src/Http/Session.php on line 514
```

What expected happen:
`Warning: Cannot persist session data because headers where already sent` Not full blown exception with vague message.

### CakePHP Version

4.3.9

### PHP Version

7.4

**Comment by markstory** [comment]
I'm not able to reproduce the issue you're having. My steps were:

1. Use a new app skeleton.
2. Update `Sessions.defaults` to be `cake`. This gets cakephp to store sessions in the application tmp directory.
3. Change permissions on `tmp/sessions` with `chmod -R 0444 tmp/sessions`. This prevents write access to the session directory.

My resulting error is 

![Screenshot from 2022-05-21 16-01-27](https://user-images.githubusercontent.com/24086/169667302-a6706978-5f92-4b3a-a924-8d939da9037c.png)

Which is pretty clear to me. The session couldn't be started and there are several PHP errors indicating that it is permission related. Are you able to provide a screenshot of what you're seeing and some steps on how to reproduce that state?

**Comment by othercorey** [comment]
@asgraf Can you provide more information?
