### ISSUE TITLE
Collection::__debugInfo() may cause fatal error "__debuginfo() must return an array"

### ISSUE THREAD

**Issue by sheldonreiff** [cakephp/cakephp#16526]
### Description

`Collection::__debugInfo()` calls `$this->count()` which could throw an exception depending on usage. For example, if the iterator passed is an instance of `CallbackFilterIterator` like cake's `FilterIterator`, and the callback throws an exception, then calling  `Collection::__debugInfo()` will cause a fatal error "__debuginfo() must return an array" when the iterator is iterated to obtain the count. This was reported as a bug in PHP with https://bugs.php.net/bug.php?id=73067 and was fixed, but was later reverted according to the comments. It appears this remains an issue with PHP.

This is probably primarily an issue for xdebug users because xdebug calls `__debugInfo()` (similar to this chronos issue: https://github.com/cakephp/chronos/issues/164). I encountered this while using xdebug.

### CakePHP Version

4.3.8

### PHP Version

7.4.29,8.1.6

**Comment by markstory** [comment]
How can someone reproduce this problem?

**Comment by sheldonreiff** [comment]
Here's an example. It can be run with xdebug in `trace` mode or without debug by adding `var_dump($filteredCollection);`.
```
$collection = new \Cake\Collection\Collection([1, 2, 3]);
$filteredCollection = $collection->filter(function ($value) {
    throw new \Exception('filter exception');
});
```
