### ISSUE TITLE
FN BUILDER: Add support to CONCAT_WS (with separator)

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#16523]
### Description

- **mysql**: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=32a91ca920aa54120e320edd008cc5cc
- **sqlsrv**: https://dbfiddle.uk/?rdbms=sqlserver_2019l&fiddle=32a91ca920aa54120e320edd008cc5cc
- **postgres**: https://dbfiddle.uk/?rdbms=postgres_14&fiddle=32a91ca920aa54120e320edd008cc5cc

Well... sqlite, is the same (and old) problem: there is no literal concat() function neither concat_ws() of course, but something like:

https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=1bfadd88cbcc596faec064ff2429f3ea

my suggestion is something like:

```php
$query = $articlesTable->find();
$query
    ->select(['slug' => $query->func()->concatWithSeparator('-', ['title' => 'identifier', 'id' => 'identifier'])])
    ->select($articlesTable);
```

### CakePHP Version

5.0 ?

**Comment by othercorey** [comment]
Why can't you use call this with the existing `FunctionsBuilder`?

**Comment by celsowm** [comment]
> Why can't you use call this with the existing `FunctionsBuilder`?

I thought would by nice since sqlite does not have a native one and Cake's ORM would help the user in this case

**Comment by markstory** [comment]
I think having a function wrapper for this seems reasonable if we can come up with a solution for SQLite.

**Comment by celsowm** [comment]
> I think having a function wrapper for this seems reasonable if we can come up with a solution for SQLite.

I would add something like:

```php
public function concatWithSeparator(string $separator, array $args, array $types = []): FunctionExpression
    {
        return new FunctionExpression('CONCAT_WS', $separator, $args, $types, 'string');
    }
```
and would add a new case (sqlite driver, for example):

```php
case 'CONCAT_WS':
                $expression->setName('')->setConjunction(" || $separator ||");
                break;
```
Taking advantage of the opportunity, I think all the others drivers could not only receive a new case like:

```php
case 'CONCAT_WS':
                $expression->setName('CONCAT_WS');
```

But I think they could using their native CONCAT function instead "+" or "||"

**Comment by othercorey** [comment]
For postgresql, CONCAT() throws an error when passing parameters via a prepared statement about an unknown type. I assume for CONCAT_WS(), we'd have to cast each parameter to a string to avoid that same error.

CONCAT_WS() has different behavior with NULL parameters so I'm not sure we could simulate it with the `||` operator.
