### ISSUE TITLE
Aliases are being removed from conditions for UPDATE/DELETE queries

### ISSUE THREAD

**Issue by samyan** [cakephp/cakephp#16522]
### Description

Hello. My query:

```php

$query = new Query($this->connection);

$query
	->update('game_session')
	->set([
		'game_session.active' => false
	])
	->join([
		'type' => 'INNER',
		'table' => 'game',
		'conditions' => 'game.id = game_session.game_id'
	])
	->where([
		'game_session.player_id' => $playerId,
		'game.provider_id' => $providerId
	])
	->execute();
```

Receive this exception:

`Aliases are being removed from conditions for UPDATE/DELETE queries, this can break references to joined tables.`

What's the wrong? I dont use aliases.

### CakePHP Version

4.2.0

### PHP Version

7.4

**Comment by ndm2** [comment]
The code that triggers that message doesn't actually look at the columns that you're referencing, it throws that error for any query that is using joins.

Maybe the message should explicitly say that joins in update and delete queries aren't supported, and say "_Aliases and table names_", as both are being removed, eg `some_alias.active` just like `game_session.active` would be affected and turned into just `active`.

**Comment by samyan** [comment]
The problem is caused by join condition. If i remove it, no more error exception. So how solve it?

**Comment by ndm2** [comment]
Well, I think subqueries are currently not affected by the cleanup process, so in case supported by your DBMS and applicable (think proper atomicity handling), you could use a `game_id IN (subquery with join)` condition instead of the join in the base query, something along the lines of this:

```php
$filterQuery = $this->connection
    ->newQuery()
    ->select(['game_session.id'])
    ->from('game_session')
    ->join([
        'type' => 'INNER',
        'table' => 'game',
        'conditions' => 'game.id = game_session.game_id'
    ])
    ->where([
        'game_session.player_id' => $playerId,
        'game.provider_id' => $providerId
    ]);

$statement = $this->connection
    ->newQuery()
    ->update('game_session')
    ->set([
        'active' => false,
    ])
    ->where([
        'game_id IN' => $filterQuery,
    ])
    ->execute();
```

In case your DMBS supports [**common table expressions**](https://book.cakephp.org/4/en/orm/query-builder.html#common-table-expressions), specifically with `UPDATE` queries, then that could be an option too:

```php
$query
    ->with(function (
        \Cake\Database\Expression\CommonTableExpression $cte,
        \Cake\Database\Query $query
    ) use (
        $playerId,
        $providerId
    ) {
        $cteQuery = $query
            ->select('game_session.id')
            ->from('game_session')
            ->join([
                'type' => 'INNER',
                'table' => 'game',
                'conditions' => 'game.id = game_session.game_id'
            ])
            ->where([
                'game_session.player_id' => $playerId,
                'game.provider_id' => $providerId,
            ]);

        return $cte
            ->name('cte')
            ->query($cteQuery);
    })
    ->update('game_session')
    ->set([
        'active' => false,
    ])
    ->where(function (
        \Cake\Database\Expression\QueryExpression $exp,
        \Cake\Database\Query $query
    ) {
        return $exp->in(
            'id',
            $query
                ->getConnection()
                ->newQuery()
                ->select('cte.id')
                ->from('cte')
        );
    });
```

and as a last resort there's always [**raw SQL queries**](https://book.cakephp.org/4/en/orm/database-basics.html#interacting-with-statements) instead of the query builder:

```php
$statement = $this->connection->execute(
    '
        UPDATE game_session
        INNER JOIN game ON game.id = game_session.game_id
        SET game_session.active = 0
        WHERE game_session.player_id = ? AND game.provider_id = ?
    ',
    [
        $playerId,
        $providerId,
    ],
    [
        'integer',
        'integer',
    ]
);
```

**Comment by samyan** [comment]
> Well, I think subqueries are currently not affected by the cleanup process, so in case supported by your DBMS and applicable (think proper atomicity handling), you could use a `game_id IN (subquery with join)` condition instead of the join in the base query, something along the lines of this:
> 
> ```
> $filterQuery = $this->connection
>     ->newQuery()
>     ->select(['game_session.id'])
>     ->from('game_session')
>     ->join([
>         'type' => 'INNER',
>         'table' => 'game',
>         'conditions' => 'game.id = game_session.game_id'
>     ])
>     ->where([
>         'game_session.player_id' => $playerId,
>         'game.provider_id' => $providerId
>     ]);
> 
> $statement = $this->connection
>     ->newQuery()
>     ->update('game_session')
>     ->set([
>         'active' => false,
>     ])
>     ->where([
>         'game_id IN' => $filterQuery,
>     ])
>     ->execute();
> ```
> 
> In case your DMBS supports [**common table expressions**](https://book.cakephp.org/4/en/orm/query-builder.html#common-table-expressions), specifically with `UPDATE` queries, then that could be an option too:
> 
> ```
> $query
>     ->with(function (
>         \Cake\Database\Expression\CommonTableExpression $cte,
>         \Cake\Database\Query $query
>     ) use (
>         $playerId,
>         $providerId
>     ) {
>         $cteQuery = $query
>             ->select('game_session.id')
>             ->from('game_session')
>             ->join([
>                 'type' => 'INNER',
>                 'table' => 'game',
>                 'conditions' => 'game.id = game_session.game_id'
>             ])
>             ->where([
>                 'game_session.player_id' => $playerId,
>                 'game.provider_id' => $providerId,
>             ]);
> 
>         return $cte
>             ->name('cte')
>             ->query($cteQuery);
>     })
>     ->update('game_session')
>     ->set([
>         'active' => false,
>     ])
>     ->where(function (
>         \Cake\Database\Expression\QueryExpression $exp,
>         \Cake\Database\Query $query
>     ) {
>         return $exp->in(
>             'id',
>             $query
>                 ->getConnection()
>                 ->newQuery()
>                 ->select('cte.id')
>                 ->from('cte')
>         );
>     });
> ```
> 
> and as a last resort there's always [**raw SQL queries**](https://book.cakephp.org/4/en/orm/database-basics.html#interacting-with-statements) instead of the query builder:
> 
> ```
> $statement = $this->connection->execute(
>     '
>         UPDATE game_session
>         INNER JOIN game ON game.id = game_session.game_id
>         SET game_session.active = 0
>         WHERE game_session.player_id = ? AND game.provider_id = ?
>     ',
>     [
>         $playerId,
>         $providerId,
>     ],
>     [
>         'integer',
>         'integer',
>     ]
> );
> ```

I thank you for the solution you offer, but I'm not looking for an alternative, rather, I'm looking for a way to execute that query the way I've put it, since if I hardcode the sql, it works perfectly. The problem is from the current version of the ORM since in v3 of Cakephp, I don't have this problem.

**Comment by ndm2** [comment]
Well, you have to look for an alternative, because as I've pointed out in my first reply, joins in update/delete queries are currently simply not supported, in fact they never where. This hard exception was [introduced in CakePHP 3.3.12](https://github.com/cakephp/cakephp/pull/9420), until then joins in update queries where simply silently swallowed, eg they weren't being compiled, resulting in various failures, so it never actually worked.

Until someone updates the core to add proper join and alias support in a cross DBMS manner, you cannot directly use joins with update and delete queries with the query builder.

**Comment by samyan** [comment]
> 

Understood. Thank you for clarify.
