### ISSUE TITLE
Memory exhaustion when using League ReflectionContainer as a container delegate

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#16544]
### Description

When using [auto-writing](https://container.thephpleague.com/4.x/auto-wiring/) memory exhaustion is encountered. I did isolate the problem and have a work-around, but am not sure what the best solution might be (see below).

#### Steps to reproduce:

1. Create a new cakephp app from [cakephp/app skeleton](https://github.com/cakephp/app)
2. Add a ReflectionContainer as a delegate (see code sample below)
3. Browse to welcome page.

Code:

```php
# in src/Application.php
public function services(ContainerInterface $container): void
{
    $container->delegate(
        new \League\Container\ReflectionContainer(true) // this occurs with or without passing a boolean arg
    );
}
```

#### Expected:

App loads

#### Actual:

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 524288 bytes) in /srv/app/vendor/league/container/src/Argument/ArgumentResolverTrait.php on line 24
```

--------------------------------------

If I add some simple debug logging to `ReflectionContainer::has($id)` like `Log::debug($id)` I can see that the same dependencies attempt getting resolved over and over until memory exhaustion is encountered:

```
2022-06-05 14:40:37 debug: Cake\Event\EventManagerInterface
2022-06-05 14:40:37 debug: Cake\Controller\ComponentRegistry
2022-06-05 14:40:37 debug: Cake\Controller\ComponentRegistry
2022-06-05 14:40:37 debug: Cake\Controller\ComponentRegistry
2022-06-05 14:40:37 debug: Cake\Controller\Controller
2022-06-05 14:40:37 debug: Cake\Controller\Controller
2022-06-05 14:40:37 debug: Cake\Controller\Controller
2022-06-05 14:40:37 debug: Cake\Http\Response
2022-06-05 14:40:37 debug: Cake\Http\Response
2022-06-05 14:40:37 debug: string
```

I think this is because `ComponentRegistry` takes `Controller` as a constructor argument. This work around seems to have resolved the issue:

```php
# in src/Application.php
public function services(ContainerInterface $container): void
{
    $container->add(ComponentRegistry::class, null);
    $container->delegate(
        new \League\Container\ReflectionContainer(true) // this occurs with or without passing a boolean arg
    );
}
```

### CakePHP Version

4.3.10

### PHP Version

8.0

**Comment by ADmad** [comment]
`Controller`'s constructor has `ComponentRegistry` as argument and the latter again has `Controller` as it's constructor arg. The container is unable to deal with this cyclic dependency and adding `ComponentRegistry` to the container beforehand seems to be the only fix.

Perhaps we can change the constructor of either of the classes in 5.x to avoid this problem.

**Comment by cnizzardini** [comment]
Looking at [Controller::__construct()](https://github.com/cakephp/cakephp/blob/4.next/src/Controller/Controller.php#L231) it seems like ComponentRegistry is being deprecated from the constructor anyways or is that not the case? It looks like that warning is gone in 5.x but the constructor arg is still there.

I think some test cases should be added for auto wire functionality too.
