### ISSUE TITLE
Extract url generation logic from Router class

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#16548]
### Description

I have an application that requires the use of coroutine and can't rely on static properties including `Router::$_request` and `Router::$_requestContex`, since this could cause to point to a different request context, but still need an easy way to create urls (`Router::url`, and `Router::fullBaseUrl`). 
I copied the source code from Router class into a new class RouteContext in my project but it would be good to have it in the core.

This change is backward compatible, the Router class would use the new class in the existing methods:
``` 
 public static function url($url = null, bool $full = false): string
    {
        if (static::$_routeContext === null) {
            static::$_routeContext = new RouteContext([]);
        }

        return static::$_routeContext->buildUrl($url, $full);
    }
```

```
public static function setRequest(ServerRequest $request): void
    {
        static::$_request = $request;
        if (static::$_routeContext === null) {
            static::$_routeContext = new RouteContext([]);
        }
        static::$_routeContext->setRequest($request);
    }
```

```
public static function fullBaseUrl(?string $base = null): string
    {
        if (static::$_routeContext === null) {
            static::$_routeContext = new RouteContext([]);
        }

        return static::$_routeContext->fullBaseUrl($base);
    }
```

I have forked this repository but my source is based on 4.3.10.

Additionally would be good to have an option to not call `setRequest` at https://github.com/cakephp/cakephp/blob/4.x/src/Routing/Middleware/RoutingMiddleware.php#L146

**Comment by markstory** [comment]
The code snippets you have show the more static properties. Won't those have the same problems as we have today? Or do you use the `RouteContext` instead of `Router` in your co-routines?

**Comment by rochamarcelo** [comment]
I'm using the class `RouteContext` the code is to show the existing `Router` methods should continue working.

**Comment by rochamarcelo** [comment]
This is how I use the new class

```
$this->routeContext = new RouteContext([], $this->request);


$url = $this->routeContext->buildUrl(['action' => 'view', 100], true);
```

**Comment by rochamarcelo** [comment]
@markstory which branch should I use as base for this?

I noticed that we can also refactor the methods `Router::normalize`  and `Router::routeExists`.  I did't used them but are related to `Router::url`.

**Comment by markstory** [comment]
> $this->routeContext = new RouteContext([], $this->request);

I don't love this as a user-facing API. We should try to provide a high level API that covers common usage. What do you think of something like

```php
$routeContext = Router::getContext();
```

This method would use the current / top request in the stack to create a new `RouteContext`. Internally `Router` could regenerate this object each time the request is push/popped.

**Comment by ADmad** [comment]
@markstory Currently the `Router` holds a single instance of request object. There's no stack, we removed it when we got rid of the "request action" feature. I am not too thrilled about re-introducing a request stack in the Router.

**Comment by rochamarcelo** [comment]
I don't see the need of adding request stack for this. 
We can  provide the api for `$routeContext = Router::getContext();`, by the way, with this we could deprecated on Router class the methods that will be added to the new class, for instance suggenting to use ` Router::getContext()->buildUrl()` instead of using `Router::url`

**Comment by ADmad** [comment]
> ...by the way, with this we could deprecated on Router class the methods that will be added to the new class, for instance suggenting to use Router::getContext()->buildUrl() instead of using Router::url

Absolutely not :). I wouldn't want all the extra typing to generate a URL.

**Comment by rochamarcelo** [comment]
Keeping `Router::url` will not kill me, the important thing is to extract the logic

**Comment by markstory** [comment]
> There's no stack, we removed it when we got rid of the "request action" feature. I am not too thrilled about re-introducing a request stack in the Router.

Totally forgot that we removed the stack :blush: I agree that we shouldn't re-add one.
