### ISSUE TITLE
Calling result set method `last()` directly on query instance is deprecated. You must call `all()` to retrieve the results first

### ISSUE THREAD

**Issue by k2rn** [cakephp/cakephp#16557]
### Description

I don't know the why is this is deprecated, but it should be on the documents if it is true.
https://book.cakephp.org/4/en/orm/query-builder.html#using-sql-functions

It should not recommend that query retrieving by `all()` instead of `first()` or `last()`, because it must slows the DB performance, we should add `limit(1)` by ourselves.
And other SQL functions are also said like this.
Are you sure that we should retrieve all record and have them calculate sum, avg, min or max?

### CakePHP Version

4.3.7

### PHP Version

8.0

**Comment by othercorey** [comment]
`first()` is unrelated to the SQL functions you linked. 

Can you show how you're calling `first()`?

**Comment by k2rn** [comment]
@othercorey 
Sorry, I couldn't reproduce by `first()`.
But `last()` is said deprecated, same way as `first()`.
```
$model = FactoryLocator::get('Table')->get(SomeTable::class);
$data = $model->find()->where($conditions)->last();
```

**Comment by othercorey** [comment]
Make the change described in the depreciation message.

**Comment by othercorey** [comment]
> because it must slows the DB performance, we should add limit(1) by ourselves.

These never added a `limit()` call. These simply called `all()` before calling the method on the `ResultSet` (`Collection`).

**Comment by k2rn** [comment]
Now, I understand that I was my fault.
Thank you @othercorey for your support.
I close this issue.

**Comment by othercorey** [comment]
Improved deprecation warning will be in cakephp 4.4.1.

https://github.com/cakephp/cakephp/pull/16558
