### ISSUE TITLE
Select Partition with query builder

### ISSUE THREAD

**Issue by samyan** [cakephp/cakephp#16556]
### Description

Hello,

Is it possible to implement new future of select partition via query builder?

example of raw query:

````mysql
SELECT * FROM employees PARTITION (p1);
````

Or maybe such an implementation already exists? I can't find anything about it in the CakePHP documentation.

### CakePHP Version

4.2

**Comment by raul338** [comment]
At the moment you can use [$query->epilog()](https://api.cakephp.org/4.3/class-Cake.Database.Query.html#epilog())

**Comment by samyan** [comment]
> At the moment you can use [$query->epilog()](https://api.cakephp.org/4.3/class-Cake.Database.Query.html#epilog())

Is possible use epilog() in this case?

````mysql
SELECT * FROM employees PARTITION (p1) WHERE id = 1
````

**Comment by othercorey** [comment]
> Is possible use epilog() in this case?
> 
> ```sql
> SELECT * FROM employees PARTITION (p1) WHERE id = 1
> ```

I think the only way is executing a raw SQL query using Connection::execute(). 
https://api.cakephp.org/4.3/class-Cake.Database.Connection.html#execute()

**Comment by samyan** [comment]
> > Is possible use epilog() in this case?
> > ```sql
> > SELECT * FROM employees PARTITION (p1) WHERE id = 1
> > ```
> 
> I think the only way is executing a raw SQL query using Connection::execute(). https://api.cakephp.org/4.3/class-Cake.Database.Connection.html#execute()

If there is no way with query builder then yes, raw query...

**Comment by celsowm** [comment]
> ```sql
> PARTITION 
> ```

Which SGBD is it?
Is there an equivalent for all main SGBDs (mysql, sqlserver, postgres and sqlite) ?

**Comment by samyan** [comment]
> > ```sql
> > PARTITION 
> > ```
> 
> Which SGBD is it? Is there an equivalent for all main SGBDs (mysql, sqlserver, postgres and sqlite) ?

Hello, yes there are equivalent functions  in mysql, sqlserver or postgresql. For sqlite is not exists (i think). 
I think that would be a very important functionality to implement in cakephp. Perhaps the easiest would be to just give some function like epilog(), to concatenate the keyword PARTITION and followed by (your_partition_name) after the table name


Mysql: https://dev.mysql.com/doc/refman/8.0/en/partitioning-overview.html
SqlServer: https://docs.microsoft.com/es-es/sql/t-sql/functions/partition-transact-sql?view=sql-server-ver16
Postgresql: https://www.postgresql.org/docs/current/ddl-partitioning.html

**Comment by othercorey** [comment]
I don't believe partitions in postgresql work the same way. You don't query a partition through a special statement but rather through the unique table name.
