### ISSUE TITLE
Render an element inside a controller method for JSON responses

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16567]
### Description

Today we got the following question in our slack support channel:

Hi, could you recommend me a document/tutorial that explains how to render a view created by ajax in Cakephp 4?
I have clear to recieve a JSON as a response... but also I would like to pass an html fragment in this response... and I am not sure what is the best way to obtain this html (in order to re-use code) e.g. if the good practice is to use an 'element' here or a 'cell' or..... 
imagine I am adding blocks with a button (via ajax) I would like to add the new block structure without refresh de page...

After some discussion with @ADmad it was clear, that its currently not possible to render e.g. the element `/element/Categories/test` to recieve its generated HTML as a variable like so:
```
$html = $this->render('/element/Categories/test')->getBody()->getContents();
```

This currently returns an empty string as you see here:
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/9105243/173405909-a6b08450-4822-4755-9099-a1c75bbdd57f.png">

We don't know why it returns an empty string because the correct string is present inside the `render()` method of the Controller class as you see here:
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/9105243/173406562-0f8a161a-6945-4439-9e2c-24e9b198767c.png">

ADmad's solution was to use the CellTrait and render each re-usable element inside its own cell which in my opinion is completely overkill.

Now the question is: Is this apporach of rendering multiple re-usable elements inside an AJAX action call to return it as a JSON response justified? Is there a better way to achieve the same goal with the current tools available?

### CakePHP Version

4.4

**Comment by LordSimal** [comment]
As @ADmad clarified, this works:
```
$html = (string)$this->render('/element/Categories/test')->getBody();
```

**Comment by ADmad** [comment]
We can either rewind the body stream after writing the content here
https://github.com/cakephp/cakephp/blob/b4ebd881ddbf820589285bfda2ab1015b9b0cf14/src/Controller/Controller.php#L774
or we can rewind inside `withStringBody()` itself.

**Comment by LordSimal** [comment]
I was thinking more of an extra `renderElement(string $element, array $data): string` method available in the controller which partially does what the `render()` method currently already does, just without the 
* layouting since we don't need it
* setting the response object

**Comment by ADmad** [comment]
I don't think that's really necessary when one can use `$html = $this->cell('Foo')->render()` to get a rendered string (after "using" the `CellTrait` in the controller).

**Comment by LordSimal** [comment]
So theoratically one can create a e.g. `ElementCell` which provides a more generic approach to render different kinds of (already present) elements instead of one having to refactor all elements into cells to just use them inside an API project.

**Comment by markstory** [comment]
You could use JsonView with templates to do exactly this with no additional APIs being added to CakePHP.

**Comment by ADmad** [comment]
Closing as there are already multiple ways to achieve JSON responses with HTML fragments.

**Comment by markstory** [comment]
@LordSimal Do you think this is a common enough request that we should include an example of how to do this in the book?

**Comment by LordSimal** [comment]
I haven't seen it that often in either the support chat nor in discourse so no, there is no need to document it in the book.

But I am definitely curious what you mean by using the JsonView with templates. 
Aka documenting it here in the issue is also sufficient 😉

**Comment by markstory** [comment]
This is what I was referring to with [templates with JsonView](https://book.cakephp.org/4/en/views/json-and-xml-views.html#using-a-data-view-with-template-files).
