### ISSUE TITLE
EntityTrait::hasErrors() may cause infinite loop

### ISSUE THREAD

**Issue by ludeus** [cakephp/cakephp#16588]
### Description

hasErrors() call _readHasErrors(),  
_readHasErrors() call hasErrors() on objects

You can make an infinite loop with that code : 

```php
$e = new Cake\ORM\Entity; 
$e->set('entity', $e);
```

__debugInfo() will call hasErrors()

quick fix:
```php
    public function hasErrors(bool $includeNested = true): bool
    {
        if (Hash::filter($this->_errors)) {
            return true;
        }

        if ($includeNested === false || $this->_disableHasErrors) {
            return false;
        }

        $this->_disableHasErrors = true;
        foreach ($this->_fields as $field) {
            if ($this->_readHasErrors($field)) {
                return true;
            }
        }
        $this->_disableHasErrors = false;

        return false;
    }
``` 

### CakePHP Version

4.4.1

### PHP Version

7.4

**Comment by ADmad** [comment]
> $e = new Cake\ORM\Entity; 
> $e->set('entity', $e);

How would such a case even occur in actual practice?

**Comment by ludeus** [comment]
I gave an example simplified to the maximum. The same result can be obtained with several levels of depth.

**Comment by ADmad** [comment]
The issue can only occur in case of an entity property referencing itself and I can't think of a practical use case of such a situation. It would always be a dev error IMO.

**Comment by othercorey** [comment]
Is there a way we can detect this without much overhead?

**Comment by dereuromark** [comment]
Closing as stale.
