### ISSUE TITLE
$this->getRequest()->is('xml') always true in 4.4

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16583]
### Description

I have noticed that after updating cakephp from 4.3 to 4.4 `$this->getRequest()->is('xml')` always returns true, even for regular html requests (tested on latest Firefox).

This breaks some cakephp plugins:
https://github.com/FriendsOfCake/crud/issues/676

### CakePHP Version

4.4

### PHP Version

7.4

**Comment by markstory** [comment]
Do you know what your browser is sending as it's `Accept` header?

**Comment by asgraf** [comment]
> Do you know what your browser is sending as it's `Accept` header?

Firefox 101.0.1 sends:
```
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
```

**Comment by othercorey** [comment]
I'm pretty sure Chrome includes `application/xml` when you type in a URL.

**Comment by asgraf** [comment]
The presence of the wildstar content type means that the browser merely declares that it supports them, but does not require the server to respond in any of these formats
I would suggest completely ignoring the `Accept` header when it contains the `*/*` content type.

**Comment by markstory** [comment]
Thanks for sharing that accept header, I'll get this scenario fixed up.

>  I would suggest completely ignoring the Accept header when it contains the */* content type.

That isn't the behavior the HTTP specs recommend.
