### ISSUE TITLE
RoutingMiddleware::__construct deprecationWarning

### ISSUE THREAD

**Issue by notpron** [cakephp/cakephp#16581]
### Description

After moving to 4.4.1 our application is logging deprecation warnings and I cannot resolve them using the proposed solution.

Our code:
```
class Application extends BaseApplication
{
...
    public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        $middlewareQueue
            ->add(new RoutingMiddleware($this, '_cake_routes_'));

        return $middlewareQueue;
    }
}
```

Produces:

> deprecated: 16384 :: Use of routing cache is deprecated and will be removed in 5.0. Upgrade to the new `CakeDC/CachedRouting` plugin. See https://github.com/CakeDC/cakephp-cached-routing

Trying to resolve this issue takes me to the cakedc/cakephp-cached-routing plugin. Problem I'm facing is that this hasn't been released yet. So as of right now I can't resolve the deprecation warning.

Has this deprecation warning been added too soon?
Also looks like the documentation wasn't updated with this change. The following still suggests using the cache parameter:
https://book.cakephp.org/4/en/controllers/middleware.html#routing-middleware

Commit:
https://github.com/cakephp/cakephp/commit/723d3a705381ee778a93408b938fac87f6b2ccb1

### CakePHP Version

4.4.1

### PHP Version

7.4

**Comment by markstory** [comment]
> Has this deprecation warning been added too soon?

No, we're planning on removing the route cache in 5.0 so the deprecation is accurate.

> So as of right now I can't resolve the deprecation warning.

You remove route caching until the cakedc plugin is released or use a dev branch/specific commit in that repository.

>  Also looks like the documentation wasn't updated with this change. The following still suggests using the cache parameter:

I'll get the docs updated.

**Comment by tersmitten** [comment]
https://github.com/CakeDC/cakephp-cached-routing/issues/1

**Comment by ADmad** [comment]
> You remove route caching until the cakedc plugin is released or use a dev branch/specific commit in that repository.

Or you can silence the error message.

Closing as there's nothing to be done in the core.

**Comment by ADmad** [comment]
Keeping it open until docs are updated.

**Comment by markstory** [comment]
Docs were updated in https://github.com/cakephp/docs/commit/1780d127e1a589f745dc996aac08c4ea3d4b0177
