### ISSUE TITLE
[v4.4][Datasource] Query trait with memory leaks

### ISSUE THREAD

**Issue by fabiofdsantos** [cakephp/cakephp#16592]
### Description

After performing a migration from v3.9 to v4.4, we start getting some "memory exhausted" errors.

In v3.9, the following source code produces no memory changes after the first iteration:

```php
for ($i = 0; $i < 10; $i++) {
    $order = TableRegistry::getTableLocator()->get('Model')
        ->find('withAssociated')
        ->where(['Model.id' => 123])
        ->first();

    echo "$i -- " . round((memory_get_usage() / 1024)) . 'kb' . "\n";
}
```

v4.4 output:
```
0 -- 17296kb
1 -- 18598kb
2 -- 19911kb
3 -- 21211kb
4 -- 22508kb
5 -- 23804kb
6 -- 25133kb
7 -- 26430kb
8 -- 27791kb
9 -- 29096kb
```

### CakePHP Version

4.4.1

### PHP Version

8.1.7

**Comment by othercorey** [comment]
Can you show the `withAssociated` finder? Does the Model schema have any special or custom data types?

**Comment by fabiofdsantos** [comment]
> Can you show the `withAssociated` finder? Does the Model schema have any special or custom data types?

@othercorey I get the same issue without the `withAssociated`. Any idea why (I'm not super familiar with CakePHP internals)?

Here's another example:

```php
TableRegistry::getTableLocator()->get('Core.Items')->find()->first();
```

Table definition:

```php
class ItemsTable extends Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('items');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');
    }
}
```

Output:
```
0 -- 12540kb
1 -- 12571kb
2 -- 12602kb
3 -- 12634kb
4 -- 12665kb
5 -- 12696kb
6 -- 12727kb
7 -- 12758kb
8 -- 12789kb
9 -- 12820kb
```

**Comment by ADmad** [comment]
I am unable to reproduce this. Even when containing hasMany related records I don't get any memory increase using the provided example over 100 iterations.

**Comment by markstory** [comment]
Do you have debug kit, or an in memory logger enabled when collecting this memory usage information? Some performance monitoring tools will also collect SQL queries as they are run which will appear as a leak.

**Comment by othercorey** [comment]
Are we sure it's a leak? Maybe php simply never garbage collected.

**Comment by fabiofdsantos** [comment]
@ADmad @markstory Since I'm not super familiar with the core of the framework, I reported the issue as you could provide some insights. I will check with other tools and try to figure out.

@othercorey I tried to call it explicitly but it didn't work. The same project with CakePHP 3.9 had no issues.  

Thanks everyone!

**Comment by fabiofdsantos** [comment]
I just found the cause.. We had this in `bootstrap.php`:
```php
EventManager::instance()->setEventList(new EventList());
```
