### ISSUE TITLE
laminas\diactoros\marshalurifromsapi has been marked as deprecated

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16599]
### Description

psalm 4.23.0 reports this failure against laminas/laminas-diactoros 2.11.2.

```
src/Http/ServerRequestFactory.php:246:16: DeprecatedFunction: The function laminas\diactoros\marshalurifromsapi has been marked as deprecated
```

### CakePHP Version

4.x branch

**Comment by ADmad** [comment]
Fixed in #16607

**Comment by othercorey** [comment]
Did we already remove in 5.x?

**Comment by ADmad** [comment]
Nope, 5.x uses the same version of diactoros. I don't even see a branch for v3 on it's repo.
