### ISSUE TITLE
Code Generation Single Model CRUD have issue during add process

### ISSUE THREAD

**Issue by hazwan91** [cakephp/cakephp#16597]
### Description

I have one table called districts such as below
![Alter-table-districts-Adminer](https://user-images.githubusercontent.com/97268905/177083192-15532416-ed32-4a89-97c7-280eb4183234.png)

Then i do the code generation using bake by using this comman `bin\cake bake all Districts`. And it running good

Then i have a page like this
![CakePHP-the-rapid-development-php-framework-Districts](https://user-images.githubusercontent.com/97268905/177083310-99ee7d1b-6d5c-4e43-8388-34a616e2cfdd.png)

But as soon as i fill like above image, i get an error like this.
![Error-Database-Error](https://user-images.githubusercontent.com/97268905/177083346-95089a7a-c15a-411b-9f27-92c3f95231a4.png)

Is there something that i do wrong?

P/S: I haven't done any customization to the code. This code comes from baking.

### CakePHP Version

4.4.*

### PHP Version

8.1.3

**Comment by ADmad** [comment]
You have used a SQL keyword `desc` as column name. You need to either rename the column or turn on the [quoteIdentifiers](https://book.cakephp.org/4/en/orm/database-basics.html#database-configuration)  option in database config.

**Comment by hazwan91** [comment]
oh thanks. didn't know that. problem solve. Thank you very much.
