### ISSUE TITLE
Response need API to closing stream

### ISSUE THREAD

**Issue by k2rn** [cakephp/cakephp#16594]
### Description

Response class create a stream for download, but there is no way to access the stream.
It prevents from deleting the file after the request completed.
And it implies this framework cannot test it with clean the temporary file up.

I want to test the download action like below.

```php
class DownloadController extends Controller
{
    public function index()
    {
        // create a file by some conditions...
        $filename = 'foobar';
        $filepath = '/tmp/some/directory/file';
        return $this->response->withFile($filepath, ['download' => true])->withHeader('Content-Disposition', "attachment;filename*=UTF-8''{$filename}");
    }
}
```

And testing code is like this.

```php

class DownloadControllerTest extends TestCase
{
    use IntegrationTestTrait;

    public function testDownload()
    {
        // setup download file, it's something cannot fixed filename.
        $filename = '/tmp/' . time();
        $this->get("/download/and_some_params");
        $this->assertResponseOk();
        $this->assertFileResponse($filename);

        // clean it up after test, but it causes error rm: cannot remove 'filename': Text file busy
        system("rm -rf {$filename}");
    }
}
```

Monkey patched like this, in vendor directory. adding closing stream API.
Response.php
```php

public function closeStream()
{
    $this->_stream->close();
}
```

And add it after finished test.

```php
    public function testDownload()
    {
        // setup download file, it's something cannot fixed filename.
        $filename = '/tmp/' . time();
        $this->get("/download/and_some_params");
        $this->assertResponseOk();
        $this->assertFileResponse($filename);
        $this->_response->closeStream();

        // this works!
        system("rm -rf {$filename}");
    }
```

### CakePHP Version

4.4

**Comment by ADmad** [comment]
You can use `$this->_response->getBody()->close()`.

**Comment by k2rn** [comment]
@ADmad 
Thank you! It helps me a lot!

**Comment by markstory** [comment]
I feel like user-land code shouldn't have to manage file handle status. This feels more like a broken abstraction that user-land code shouldn't be exposed to.

**Comment by markstory** [comment]
@k2rn I wasn't able to reproduce the problem you were having locally and added a test to cover it. Am I missing anything in how to reproduce this problem?

**Comment by k2rn** [comment]
@markstory 
I reproduced it. The smallest codes are below, with new project, no database, just input security salt.
OS: CentOS Linux release 8.3.2011
PHP: PHP 8.0.3 (cli) (built: Mar  2 2021 16:37:06) ( NTS gcc x86_64 )
bin/cake version: 4.4.1



`src/Controller/DownloadController.php`

```php
<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Download Controller
 *
 * @method \App\Model\Entity\Download[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class DownloadController extends AppController
{
    /** 
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {   
        $filename = $this->request->getQuery('file');
        $filepath = TMP . $filename;
        if (!file_exists($filepath)) {
            throw new \Exception('file not found');
        }   

        return $this->response->withFile($filepath, ['download' => true])
            ->withHeader('Content-Disposition', "attachment;filename*=UTF-8''{$filename}");
    }   
}
```


`tests/TestCase/Controller/DownloadControllerTest.php`

```php
<?php
declare(strict_types=1);

namespace App\Test\TestCase\Controller;

use App\Controller\DownloadController;
use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

/**
 * App\Controller\DownloadController Test Case
 *
 * @uses \App\Controller\DownloadController
 */
class DownloadControllerTest extends TestCase
{
    use IntegrationTestTrait;

    /** 
     * Test index method
     *
     * @return void
     * @uses \App\Controller\DownloadController::index()
     */
    public function testIndex(): void
    {   
        $file = microtime(true) . '.txt';
        $path = TMP . $file;
        $text = uniqid();
        file_put_contents($path, $text);

        $this->get("/download?file={$file}");
        $this->assertResponseOk();
        $this->assertFileResponse($path);

        // if comment out this line, test is OK but it can't remove txt file.
        // $this->_response->getBody()->close();

        system("rm -rf {$path}");
    }   
}
```



results:

```
$ vendor/bin/phpunit tests/TestCase/Controller/DownloadControllerTest.php 
PHPUnit 9.5.21 #StandWithUkraine

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

rm: cannot remove 'ROOT/tmp/1656909771.2766.txt': Text file busy
.                                                                   1 / 1 (100%)

Time: 00:00.099, Memory: 8.00 MB

```

**Comment by k2rn** [comment]
The problem, it shows this line
`rm: cannot remove 'ROOT/tmp/1656909771.2766.txt': Text file busy`

I want to keep the tests folders clean.

**Comment by markstory** [comment]
Thanks for providing more steps @k2rn. I updated the changes in my pull request to match what you provided but I still wasn't able to reproduce the problem. I'll have to try again in a minimal application. Perhaps there is something in our test suite that is causing the file handles to not be opened.

Edit: I tried locally with your sample code and I don't get an open file error either. Perhaps this is a PHP version/operating system related issue? I've been testing on PHP 8.0.8 on an ubuntu 21.10 based distro.

**Comment by k2rn** [comment]
@markstory 
> Perhaps this is a PHP version/operating system related issue?

It would be so. I've just tried this on PHP 8.0.18 on an ubuntu 20.04.2, I couldn't reproduce it.

**Comment by markstory** [comment]
> It would be so. I've just tried this on PHP 8.0.18 on an ubuntu 20.04.2, I couldn't reproduce it.

Ok. Would you be able to checkout the pull request I've made and see if those changes fix the problem on your end?

**Comment by k2rn** [comment]
Sure, but the environment is at my client's office. I'll be there next Friday. I'll send you feedback at that time.

**Comment by k2rn** [comment]
@markstory 
I commented to the PR. It fixed this issue, thanks a lot!
https://github.com/cakephp/cakephp/pull/16596

**Comment by othercorey** [comment]
@markstory Is this closed now?
