### ISSUE TITLE
Missing plugin part in Entity::getSource() string

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16615]
### Description

Example1 code:
```PHP
$exampleTableClassFromPlugin = 'Captcha.Captchas';
//Following code will work correcly

$tableFromPlugin = $this->fetchTable($exampleTableClassFromPlugin);
$entityFromPlugin = $tableFromPlugin->newEmptyEntity();
$tableFromSource = $this->fetchTable($entityFromPlugin->getSource());
```

Example2 code:
```PHP
$exampleTableClassFromPlugin = \Captcha\Model\Table\CaptchasTable::class;
//Following code will throw `Table class for alias Captchas could not be found.` exception

$tableFromPlugin = $this->fetchTable($exampleTableClassFromPlugin);
$entityFromPlugin = $tableFromPlugin->newEmptyEntity();
$tableFromSource = $this->fetchTable($entityFromPlugin->getSource());
```

In first example `getSource()` returns `'Captcha.Captchas'` string
In second example `getSource()` returns `'Captchas'` string
Expected `'Captcha.Captchas'` or `'\Captcha\Model\Table\CaptchasTable'` string instead

### CakePHP Version

4.4.2

### PHP Version

7.4

**Comment by othercorey** [comment]
Same as https://github.com/cakephp/cakephp/issues/16419

**Comment by dereuromark** [comment]
I wonder if this is possible if the plugins are known or loaded (plugins.php namespace map)
As we could then know what plugin such a namespaced class could belong to

**Comment by ADmad** [comment]
Closing this as duplicate.
