### ISSUE TITLE
IdentifierQuoter::_basicQuoter() doesn't quote AggregateExpression with aliased identifiers for Postgres database

### ISSUE THREAD

**Issue by JOSEPHGILBY** [cakephp/cakephp#16614]
**Update**
Wrapping complex identifier expressions with $query->identifier() will resolve the issue.

```
->select([
    'id' => $this->aliasField('id'),'
    'name' => $this->aliasField('name'),
    'assoc_table2_count' => $query->func()->count(
        $query->identifier($this->AssocTable1->AssocTable2->aliasField('id'))
    )
])
```

### Description

The following query builder statement will yield

Aliases
```
table -> Table
assoc_table1 -> AssocTable1
assoc_table2 -> AssocTable2
```
Code
```
->select([
    'id' => $this->aliasField('id'),'
    'name' => $this->aliasField('name'),
    'assoc_table2_count' => $query->func()->count(
        $this->AssocTable1->AssocTable2->aliasField('id')
    )
])
```
Resulting PosgreSQL
```
SELECT "Table"."id" AS "id", "Table"."name" AS "name", (COUNT(AssocTable2.id)) AS "assoc_table2_count"

"SQLSTATE[42P01]: Undefined table: 7 ERROR:  invalid reference to FROM-clause entry for table "assoc_table2"
LINE 1: ...id" AS "id", "Table"."name" AS "name", (COUNT(AssocTable2.id...                                                             
^HINT:  Perhaps you meant to reference the table alias "AssocTable2"."
```
PostgreSQL which works
```
SELECT "Table"."id" AS "id", "Table"."name" AS "name", (COUNT("AssocTable2"."id")) AS "assoc_table2_count"
```

Drilling down into the cakephp code, the Query translator will instantiate and call IdentifierQuoter->quote which eventually calls down to IdentifierQuoter::_basicQuoter() which will replace "Table.id" and "Table.name" with "Table"."id" and "Table"."name". However, the basicQuoter does not handle the third select entry since it is an AggregateExpression and "AssocTable2.id" is under the AggregateExpression's _conditions instance variable. 

I'm not deeply familiar with all of the cakephp's source code internals, so there might be a second place where IdentifierQuoter is called when compiling the sql statement when implementing a fix.

### CakePHP Version

4.4.2

### PHP Version

8.1.7

**Comment by othercorey** [comment]
You need to create an `IdentifierExpression` to wrap the identifier. The string is assumed to be a literal.

**Comment by JOSEPHGILBY** [comment]
Yep, wrapping $query->identifier() around the expression did the trick!
