### ISSUE TITLE
Folder::create: umask has no effect 

### ISSUE THREAD

**Issue by magicschattenmann** [cakephp/cakephp#16611]
### Description

In Folder::create the call on `$old = umask(0);` is directly followed by `umask($old)` and therefor is directly reseted to its old value. This leads to unexpected permission set in the filesystem.

Solution: wrap the umask calls around the `mkdir` call.

### CakePHP Version

4.3.0

### PHP Version

8.1

**Comment by othercorey** [comment]
The `Folder` class will be removed in 5.0. You might want to move over to `mkdir` with recursive = true or another package even if we patch this.

**Comment by markstory** [comment]
Looks like this regressed in https://github.com/cakephp/cakephp/commit/558a55fbc584e02b59bf60cfe838efc5b5702077#diff-2d718ebfa51c6fdb9c2ea4f4a609516b7cddd500d534a52fb16703001be12a63R649

**Comment by othercorey** [comment]
We don't really need all the logic currently used. We can just use mkdir. In fact, we already have recursive set to true so just needs to be called with the original path passed in.

**Comment by ADmad** [comment]
I would rather we just revert to the previous code rather than trying to improve it. The File/Folder code is too flaky as it is.

**Comment by othercorey** [comment]
> I would rather we just revert to the previous code rather than trying to improve it. The File/Folder code is too flaky as it is.

I agree. Note, that accidentally testing with root user is really confusing :)
