### ISSUE TITLE
Plugin Templates Path Building Incorrectly

### ISSUE THREAD

**Issue by rmarsh1ua** [cakephp/cakephp#16620]
### Description

When attempting to load a template that's included as part of a plugin, the path to the template file will not be built correctly. This seems to happen when the plugin is not yet 'loaded', specifically [at this point in the code](https://github.com/cakephp/cakephp/blob/73cb104936c9a82270451716a5024b49facfaf98/src/View/View.php#L1453). For me, while debugging that line will evaluate as false. The plugin otherwise works fine so I don't know when in the lifecycle that should return true. Adding the following code under line 1458 fixes the whole problem for me:

`$name = $second;`

If I don't do this, the plugin name continues to be resolved as part of the template name, the template can't be found, and when used as part of an email, the email fails to send.

### CakePHP Version

4.4.1

### PHP Version

7.4.3

**Comment by othercorey** [comment]
Are you loading the plugin?

**Comment by rmarsh1ua** [comment]
The plugin otherwise works fine so I'm assuming that it loads at some point. What I'm not sure about if that's happening implicitly, and if so, when that happens in the lifecycle. I think there may be some way to explicitly load the plugin, of which I'm not aware, that could also fix this problem. Regardless, the contingent `else` case here produces an undesired result.

Also I'm not sure if this is relevant or not, but the plugin in question here is both: a) a custom plugin and b) loaded through the vendor folder and not in the plugins folder.

**Comment by ADmad** [comment]
> ..so I'm assuming...

Coding based on assumptions isn't exactly the smartest way. Just ensure that the plugin is loaded.

> ...I think there may be some way to explicitly load the plugin..

Of course there is, read the manual on how to load plugins.

**Comment by rmarsh1ua** [comment]
> > ..so I'm assuming...
> 
> Coding based on assumptions isn't exactly the smartest way. Just ensure that the plugin is loaded.
> 
> > ...I think there may be some way to explicitly load the plugin..
> 
> Of course there is, read the manual on how to load plugins.

Certainly I can do that, perhaps you could wait to close the issue so I can find out if I'm already explicitly loading the plugin?

Regardless of what I'm doing or not doing, the fallback case should work as intended. That's my main point here.

**Comment by ADmad** [comment]
The "fallback case" is to just use the template name as is and since you don't have a template matching that name getting a missing template exception is expected.

**Comment by rmarsh1ua** [comment]
`Plugin::isLoaded($first)` always returns false for me, this is after I add `$this->addPlugin()` to my Application.php. AFAIK, this plugin is installed via composer and per the documentation:

"If you install your plugins via composer or bake you shouldn’t need to configure class autoloading for your plugins."

I read this and to me it implies that the plugin is already autoloaded, which is reinforced by the fact that this isn't an issue until now that I'm trying to use a template. [The documentation](https://book.cakephp.org/4/en/plugins.html) also says, "If you want to use a plugin’s routes, console commands, middleware, or event listeners you will need to load the plugin."

So it's really confusing that I should have to add this call to addPlugin to use a template when the documentation doesn't explicitly say I need to do that, and it's otherwise working as expected. 

I would also disagree that it's using the template name because I'm saying `setTemplate('FOO.bar')` and so the template name is `bar` and instead it's looking for a template named `f_o_o.bar`. 

Following the debugger I even get to [this line ](https://github.com/cakephp/cakephp/blob/73cb104936c9a82270451716a5024b49facfaf98/src/Core/Plugin.php#L124)where the code comments say the function isn't  meant to be used during runtime, so it makes me wonder if the check is even appropriate.

If there's no agreement or motivation to change how this works, I would strongly suggest at least updating the documentation so it's really explicitly clear if/when someone needs to put addPlugin in Application.php. My experience so far is that it doesn't make any difference for this problem.

**Comment by ADmad** [comment]
Closing as the docs have been updated.
