### ISSUE TITLE
Try Catch-Block in foreach over ResultSet break the loop 

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/cakephp#16623]
### Description

A try-catch block in a foreach loop leads to a termination when iterating over a ResultSet. I noticed this when using the Authorization plugin where an exception is caught when querying the policy in the [ResolverCollection](https://github.com/cakephp/authorization/blob/90c3a6556d2263b4a1970dfad8110ba06fba197f/src/Policy/ResolverCollection.php#L85)

Here is a simple example, which leads to the same result:

```
$articlesByStatus = $articles->find()
    ->where(['author_id' => 1])
    ->mapReduce($mapper, $reducer)
    ->all();

foreach ($articlesByStatus as $status => $articles) {
    echo sprintf("There are %d %s articles", count($articles), $status);
    try {
        throw new Exception('break');
    } catch (Exception $e)
    {
    }
}
```
### CakePHP Version

4.4.2

### PHP Version

8.1.8

**Comment by markstory** [comment]
What is the error message and stack trace from the termination?

**Comment by tobiasbhn** [comment]
There is no Error / Stacktrace. The Loop gets terminated peacefully as if there is no Iteration left to do.

**Comment by tobiasbhn** [comment]
Behaves like a `break`

**Comment by markstory** [comment]
And you're sure that your mapper/reducer callbacks are yielding results? I'm not able to reproduce the problem you're having based on the information available so far. The following test passes in our test suite:

```php
    public function testQueryIterationThrow()
    {
        $table = $this->getTableLocator()->get('Articles');
        $results = $table->find('all')->all();
        $counter = 0;
        foreach ($results as $row) {
            try {
                throw new \Exception('break');
            } catch (\Exception $e) {
                $counter++;
            }
        }
        $this->assertEquals(3, $counter);
    }
```

**Comment by tobiasbhn** [comment]
I just tested it again, and found that it works when I run it in the controller. However, when I apply the same code in the view, it does not work.

Our use case is that we want to iterate over all the contents of a ResultSet in the view and display the contents in a table. However, some of the columns are dependent on the permissions of the current users with respect to a concrete entity. The permission check via authorization plugin uses a try-catch block in the background. Would moving the logic to the controller be appropriate?

Apart from that, I assume that the behavior of the loop in the view is not intentional? Can you reproduce this in the view?

**Comment by markstory** [comment]
> Apart from that, I assume that the behavior of the loop in the view is not intentional? Can you reproduce this in the view?

No, I'm not. The way queries run, and exceptions work in a view is no different than in a controller or test case. I suspect you have a mistake in your query conditions or map/reduce logic that is yielding the unexpected results.
 
> The permission check via authorization plugin uses a try-catch block in the background. Would moving the logic to the controller be appropriate?

Building query conditions in the view is generally not an approach I would recommend taking, but I have no context on what you're doing or the constraints of your scenario.

**Comment by tobiasbhn** [comment]
Im also able to recreate this scenario in a fresh cake init. Steps to reproduce:
1. `composer create-project --prefer-dist cakephp/app`
2. setup local server and db connection
3. create database and table (I used default SQL from cake [example](https://book.cakephp.org/4/en/tutorials-and-examples/cms/database.html))
4. run `bin/cake bake all articles`
5. open in browser and create some articles in frontend -> all created artilces are shown in index
6. insert try-catch block in index
7. artilces index will only show first article

Relevant Parts of the baked and modified articles index looks something like this:
```
// other bake html
<tbody>
    <?php $counter = 0; ?>
    <?php foreach ($articles as $article): ?>
        <?php
            try {
                throw new \Exception('break');
            } catch (\Exception $e) {
                $counter++;
            }
        ?>
    <tr>
        <td><?= $this->Number->format($article->id) ?></td>
        <td><?= h($article->title) ?></td>
        <td><?= h($article->slug) ?></td>
        <td><?= h($article->published) ?></td>
        <td><?= h($article->created) ?></td>
        <td><?= h($article->modified) ?></td>
        <td class="actions">
            <?= $this->Html->link(__('View'), ['action' => 'view', $article->id]) ?>
            <?= $this->Html->link(__('Edit'), ['action' => 'edit', $article->id]) ?>
            <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $article->id], ['confirm' => __('Are you sure you want to delete # {0}?', $article->id)]) ?>
        </td>
    </tr>
    <?php endforeach; ?>
    <?php debug($counter); ?>
</tbody>
// other bake html
```

The controller code is unchanged from the cake bake:
```
    public function index()
    {
        $articles = $this->paginate($this->Articles);

        $this->set(compact('articles'));
    }
```

**Comment by LordSimal** [comment]
We were able to reproduce the problem **only** if the `Xdebug` PHP Extension was enabled.
@tobiasbhn and @nicokaiser79 Do you by chance have Xdebug enabled in your setups?

**Comment by ADmad** [comment]
Xdebug is the cause here. I can't reproduce the issue with it disabled. Xdebug is known to cause weird issues when iterators are involved.

**Comment by LordSimal** [comment]
Please try the fix from the linked PR (just adjust that one file in your `vendor/cakephp/cakephp` directory) and see if that fixes your problem

**Comment by tobiasbhn** [comment]
Yes! These changes have fixed the problem.
