### ISSUE TITLE
Add input minlength attribute from context interface

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#16639]
### Description

Right now we have a `\Cake\View\Form\ContextInterface::getMaxLength` method to get and set `maxlength` attribute to input fields. Why don't we have a `minlength` attribute in a similar fashion? Is there a particular reason why only maxlength is implemented? 
This way, `\Cake\Validation\Validator::minLength`, `\Cake\Validation\Validator::maxLength` and `\Cake\Validation\Validator::lengthBetween` methods should set the `minlength` and `maxlength` attributes consistently.

### CakePHP Version

4.*

**Comment by markstory** [comment]
> Why don't we have a minlength attribute in a similar fashion? Is there a particular reason why only maxlength is implemented?

Mostly because we can't infer minlength from schema. Using validation rules to infer minlength sounds like a good idea though. Any chance you'd want to contribute a pull request for that? I'd be happy to help with tests if you need a hand.

**Comment by xavier83ar** [comment]
Sure, I'll try to do it. I'll ask for your help if I've any trouble with tests or anything else.

**Comment by xavier83ar** [comment]
Just to let you know, I'm still working on this, I didn't found to much time to work on it but I've done some progress, there is still work to do.. mostly with tests...
