### ISSUE TITLE
RFC 5.x - Split Database/Query into separate classes.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#16648]
`Database/Query` is currently a ~2400 lines behemoth. 

`Query` could be turned into a base class with common code and then have separate classes for SELECT, UPDATE, INSERT and DELETE queries. Splitting into separate classes would help with code readability and maintainability. It will also allow removing some code which is currently needed to keep track of what type of a query is being made and checks such as [this](https://github.com/cakephp/cakephp/blob/5.x/src/Database/Query.php#L255).

Does anyone foresee any problems in doing the above?

**Comment by ADmad** [comment]
Proposed change would of course require downstream change too and `ORM\Query` will also need to be split up. We would have to do away / rethink `ORM\Query` implementing `Datasource/QueryInterface`.

**Comment by markstory** [comment]
> Does anyone foresee any problems in doing the above?

Won't having separate query classes cause breaking changes in usage that converts one kind of query to another? Right now we have code internally that does

```php
$table->find()->where(...)->delete()->execute();
```

Which is ergonomic from a user perspective as you can build the query and until you run it all of the parts of the query can be changed.  Would users have to move to using 

```php
$table->query()->where(...)->delete()->execute();
```

Instead or would each kind of query have methods to convert it into the other kinds?

**Comment by ADmad** [comment]
Sounds a bit weird to me that someone wouldn't have already decided what type of query they are building before hand and needs to change it mid build :slightly_smiling_face:.

`Table`'s methods internally use `$this->query()->{$type}()->....->execute()` for update/insert/delete queries. If we had separate queries the 2 calls `->query()->{$type}()` could be replaced with a single `->query($type)` (or have separate methods for each type) call which would return the query instance of appropriate type.

In case of the end user using the ORM wouldn't they be using the ORM methods like `Table::delete()` etc.? I would imagine only someone using the dbal directly would be building the query themselves. Even for that we have convenience methods for delete/update/insert on the `Connection` class.

**Comment by othercorey** [comment]
We would have to provide a deprecation path that involves Query using query objects underneath and supporting both where needed.

**Comment by ADmad** [comment]
Pretty much all internal/sub queries would be select queries.

**Comment by markstory** [comment]
> Table's methods internally use $this->query()->{$type}()->....->execute() for update/insert/delete queries. If we had separate queries the 2 calls ->query()->{$type}() could be replaced with a single ->query($type) (or have separate methods for each type) call which would return the query instance of appropriate type.

Having a type parameter to `Table::query()` and `Connection::newQuery()` could work. Having additional method for each query type seems a bit heavy and we could add methods in the future if the type parameter is clunky in usage.

> In case of the end user using the ORM wouldn't they be using the ORM methods like Table::delete() etc.? I would imagine only someone using the dbal directly would be building the query themselves. Even for that we have convenience methods for delete/update/insert on the Connection class.

I think you've got one of the important impacted use cases captured. I know in my applications I've used a bit of

```php
$this->find('someType')->delete();
```

style operations, and we use those internally in the ORM to do association operations. This pattern is useful as it lets users define conditions in a finder and have those finder conditions used in a delete or update operation as well.  How could we migrate that kind of usage to separate query objects?

**Comment by ADmad** [comment]
Initially I was only thinking about DBAL so didn't factor in the usage of `find()` which only exits for `ORM\Query`. Maybe we can keep the public API of `ORM\Query` the same, not have it extend `Datbase\Query` and have it do some internal query juggling. But that sounds complicated and not sure if I want to take up such a task :slightly_smiling_face:.

**Comment by markstory** [comment]
> Maybe we can keep the public API of ORM\Query the same, not have it extend Datbase\Query and have it do some internal query juggling. But that sounds complicated and not sure if I want to take up such a task slightly_smiling_face.

What would be complicated in the type juggling? Each query type could have a factory method to create it from another type of query. If unsupported clauses are present we could raise an error.

Queries will need to know which of their parts are not empty, and parts with the same name are the 'same'. We have talked about making `Query\Orm` a wrapper around `Database\Query` for a while now, and this is another change that will help push that along and provide some type checking/early warning feedback to userland code that is building bad queries.

**Comment by ADmad** [comment]
Okay, so `ORM\Query` will retain the current API and call to it's various method will return an instance of itself as it currently does. Depending on the method called it will create an instance of `Database\(Select|Update|Delete)Query`. For subsequent calls depending on the current database query instance stored, it will call a factory method to convert the query instance to a different type if required. Is this what you are thinking?

**Comment by celsowm** [comment]
We could remove all ...join... Methods from Query and put them in a Trait and use/import them in Query

**Comment by markstory** [comment]
>  Is this what you are thinking?

Perfectly :clap: What do you think about that approach? Does it seem like a reasonable balance of us wanting to get more typesafe and a simpler query builder API and keeping backwards compatibility for userland code. I understand that 5.x is a breaking release, but based on the 2.x -> 3.x transition breaking changes to the ORM/Model layer cause fundamental upgrade challenges.

If we really hate the 'bloat' that this approach takes, we can deprecate it in 5.x and remove it in 6.x. This gives people a major release worth of notice about our intentions.

**Comment by ADmad** [comment]
> What do you think about that approach?

I think it's a reasonable approable. It allows up to improve the lower level of abstraction which does the heavy lifting, while keeping the higher level API the same which is what the majority of the users would be using.

**Comment by othercorey** [comment]
I think this is done.
