### ISSUE TITLE
Create a built-in CORS handler

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#16652]
### Description

Cakephp should be able to manage cors request without the need of external packages
The proposal is te create a CorsMiddleware that, based on a global configuration, is able to manage preflight and actual cors request, and set the correct response headers.

**Comment by ADmad** [comment]
CakePHP already includes a `CorsBuilder` class whose instance is accessible through `Response::cors()`. It provides various convenience methods for setting required CORS headers.

The reason there's no `CorsMiddleware` is because what CORS headers to set is quite application specific so the middleware would be essentially "empty".

**Comment by doshu** [comment]
CorsBuilder has only the responsibility to set cors headers, but it is not
capable of detecting if a request is a CORS actual request o a preflight
request.
Cors headers should be only setted if the request is a CORS and if an
origin header is present in the request.

A CORS analyzer class should be implemented to detect if the request is a
CORS.
The CorsMiddleware, based on a configuration and on the result of the
analyzer, should set the required response headers.

The use of a configuration file for defining the CORS rules, allow the
creation of a predefined cors middleware.
For further examples, take a look at how laravel, or laminas implements
their own cors handling logic


Il giorno gio 28 lug 2022 alle ore 10:29 ADmad ***@***.***>
ha scritto:

**Comment by ADmad** [comment]
You can open a pull request with a proposed implementation.

**Comment by markstory** [comment]
>  CorsBuilder has only the responsibility to set cors headers, but it is not
capable of detecting if a request is a CORS actual request o a preflight
request.

Generally this detection is pretty simple, so we don't have a middleware for it. The logic around Origin management could be arbitrary so we've avoided applying a framework around it. Perhaps we could clarify how the having a framework for handling OPTIONS requests would help application developers? Right now I'm don't see it as a source of complexity.

> The use of a configuration file for defining the CORS rules, allow the
creation of a predefined cors middleware.

Having a configuration file implies that the framework needs to validate the configuration file and raise errors when developers make mistakes. The current method call based solution avoids all of that as we can rely on PHP checking some of those errors for us.

> Cors headers should be only setted if the request is a CORS and if an origin header is present in the request.

Don't you also need to set `Access-Control-Allow-*` headers in responses to the OPTIONS requests?

> For further examples, take a look at how laravel, or laminas implements their own cors handling logic

Do you have links to those? I looked at laravel briefly and only found community solutions.

While I'm not against providing a cors middleware, we would need to be clearer on what problems we were solving and what the APIs we would want to expose to developers would be. Right now those details aren't clear to me.

**Comment by doshu** [comment]
Cors detecting must be in a middleware anyway, cause of the OPTIONS method.
Managing CORS request, for example, in the beforeFilter event, require the
current route support always the OPTIONS method, so, the route will be
never hitted.

The detection and management of the Origin header is quite simple, dut the
correct creation of the CORS Response is not.
Access-Control-Allow-* headers are needed in the OPTIONS Response and some
of them in the actual request response.
Note that not all CORS request results in a preflight options request.

The use of a configuration file is not mandatory and the middleware can be
configured manually when added to the queue through some specific methods.

here, some link to take a look at laravel implementation

https://laravel.com/docs/9.x/routing#cors
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Http/Middleware/HandleCors.php#L33


Il giorno ven 29 lug 2022 alle ore 03:48 Mark Story <
***@***.***> ha scritto:

**Comment by markstory** [comment]
Thanks for the links to the laravel implementation. I noticed that their solution doesn't allow you to have different CORS header values for different paths. This could be me misunderstanding how their code works though.

Given that we already have an existing `CorsBuilder` it would be preferable to re-use that object in any middleware we add. One potential API that comes to mind is:

```php
$middlewareQueue->add(new CorsMiddleware(['/api/*'], function ($corsBuilder) {
  return $corsBuilder
    ->allowOrigin(...)
    ->exposeHeaders(...);
});
```

Using a closure to define cors headers would let us re-use the APIs we already have and avoid needing to add another configuration file. This approach would also allow us to have different cors configurations if an application needs that, as the middleware could be added multiple times for different paths.

**Comment by ndm2** [comment]
I've seen quite a few people struggling with correctly setting up CORS responses, especially beginners seem to often mess up bailing out on preflights, keeping authentication/authorization out of the way, and having the proper headers set for error responses too, so I'd be very much pro having a middleware available in the core.

While we're at it, maybe we can also add a transparent way to distinguish CORS requests and preflight requests, as they shouldn't have the same response headers if one really wants to be strict to the specs. Maybe we could have methods on the builder, or possibly better on the request object, something like `isCors()` and `isCorsPreflight()`.

I'd also second that this should preferably use the CORS builder API over configuration, at least for the first implementation. ~Since middleware's can be applied per routing scopes, even path configuration could be at least optional~ Actually, route scoped middlewares are applied too late, so path config is pretty much required.

**Comment by markstory** [comment]
> Maybe we could have methods on the builder, or possibly better on the request object, something like isCors() and isCorsPreflight().

We could add request detectors for this making the methods compatible with `request->is('cors')` too.

> I've seen quite a few people struggling with correctly setting up CORS responses, especially beginners seem to often mess up bailing out on preflights, keeping authentication/authorization out of the way, and having the proper headers set for error responses too, so I'd be very much pro having a middleware available in the core.

Sounds like more good reasons to move forward with providing a middleware in the framework. I was thinking that the callback would be applied for both the pre-flight and matching requests.  We could expand the callback interface to be

```php
function (CorsBuilder $corsBuilder, ServerRequest $request): CorsBuilder
```

To enable building preflight/regular response header generation. Will it be unexpected that this method would be called at different points in time? For pre-flight requests the provided closure would need to be called before the controller action, as the generated cors builder is all of what will be in the response. When we're handling a regular request, the generated cors builder would be applied to the response **after** the controller action was.

**Comment by doshu** [comment]
using a callback for setting headers is not possible because the preflight
request and actual request must send a different set of headers.

Cors builder must be used internally by the middleware.
Defining cors rules based on the path could be done using route specific
middleware

A possible api could be

$middlewareQueue->add(new CorsMiddleware()
  ->setAllowedOrigin([...])
  ->setAllowedMethod([...])
  ->setAllowedHeaders([...])
);

two additional detectors could be added in the request object

request->is('cors') for detecting simple and actual cors request

request->is('preflight') for detecting preflight cors request



Il sab 30 lug 2022, 04:13 Mark Story ***@***.***> ha scritto:

**Comment by ndm2** [comment]
> We could add request detectors for this making the methods compatible with `request->is('cors')` too.

Not a big fan of the detector API, but given the current state of the request object that would probably be the right approach.


> To enable building preflight/regular response header generation. Will it be unexpected that this method would be called at different points in time? For pre-flight requests the provided closure would need to be called before the controller action, as the generated cors builder is all of what will be in the response. When we're handling a regular request, the generated cors builder would be applied to the response **after** the controller action was.

For me personally it makes sense, but it could certainly be unexpected for people that don't yet fully understand CORS. Since the middleware would have to distinguish between CORS and preflight, this could possibly also be an additional argument for the closure, which might make the behavior more clear.

I probably also wouldn't mind having two separate callbacks. I'm also wondering if the builder could possibly apply only the headers that are actually required, based on the type of the request. Not sure though if that would maybe be a bit too much magic?


> Defining cors rules based on the path could be done using route specific middleware

That came to my mind too, but route scoped middlewares are applied too late, to be specific, they apply _after_ the error, and possibly the authentication, and authorization middlewares, each of which could prevent from reaching the routing middleware and therefore the CORS handling.

**Comment by markstory** [comment]
> I probably also wouldn't mind having two separate callbacks. I'm also wondering if the builder could possibly apply only the headers that are actually required, based on the type of the request. Not sure though if that would maybe be a bit too much magic?

Building the correct headers from the overall CORS configuration should be possible as we know the subset of headers that are needed for the pre-flight request.

> Since the middleware would have to distinguish between CORS and preflight, this could possibly also be an additional argument for the closure, which might make the behavior more clear.

Do we still need the developer facing API to know whether a pre-flight or normal request is being handled if `CorsBuilder` is expanded to know more about how to build pre-flight responses?

**Comment by ndm2** [comment]
> Do we still need the developer facing API to know whether a pre-flight or normal request is being handled if `CorsBuilder` is expanded to know more about how to build pre-flight responses?

I guess chances for it being "needed" would then be greatly reduced. It could still be nice to have in case one has a need to run additional logic on either preflight or CORS requests, and the builder could potentially use it internally too.

**Comment by markstory** [comment]
> It could still be nice to have in case one has a need to run additional logic on either preflight or CORS requests, and the builder could potentially use it internally too.

Couldn't the `CorsBuilder` have a method to enable headers in the pre-flight request? Perhaps something like:

```php
$corsBuilder->allowMethods(['post', 'get'])
  ->allowHeaders(['Authorization'])
  ->addToPreflight('allowHeaders');
```

I'm not sure if `addToPreflight()` is the right name or if using builder method names as the inputs is a solid design, but I hope it illustrates the idea of giving users an API to get what they want with less complexity.

**Comment by ndm2** [comment]
I've expressed that somewhat unclearly, I meant logic that isn't tied to setting CORS headers. To be fair I don't really have a good real world example at hand, but it would allow to easily do something like:

```php
if ($request->is('preflight')) {
    // run logic specifically on preflights
}

return $builder
    ->allowOrigin(/* ... */)
    ->allowMethods(/* ... */)
    ->allowHeaders(/* ... */)
    ->exposeHeaders(/* ... */)
    ->allowCredentials()
    ->maxAge(/* ... */);
```

I don't think the builder needs more user facing functionality, having it auto-set the right headers should be good enough.

**Comment by markstory** [comment]
> To be fair I don't really have a good real world example at hand, but it would allow to easily do something like:

I think the example you gave is exactly the possibilities I had as well. If we wanted to give *even* more flexibility in the future we could expand the return type of the callback to be `CorsBuilder | ResponseInterface` and let users enter 'power user mode'.
