### ISSUE TITLE
MysqlSchemaTest::testDescribeTable fails with latest mysql version

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#16656]
### Description

```
1) Cake\Test\TestCase\Database\Schema\MysqlSchemaTest::testDescribeTable
Field definition does not match for title
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'length' => 20
     'precision' => null
     'comment' => 'A title'
-    'collate' => 'utf8_general_ci'
+    'collate' => 'utf8mb3_general_ci'
 )
```

### CakePHP Version

4.4

**Comment by LordSimal** [comment]
This is because of the latest change in MySQL 8.0.30
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html

> Important Change: A previous change renamed character sets having deprecated names prefixed with utf8_ to use utf8mb3_ instead. In this release, we rename the utf8_ collations as well, using the utf8mb3_ prefix; this is to make the collation names consistent with those of the character sets, not to rely any longer on the deprecated collation names, and to clarify the distinction between utf8mb3 and utf8mb4. The names using the utf8mb3_ prefix are now used exclusively for these collations in the output of SHOW statements such as [SHOW CREATE TABLE](https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html), as well as in the values displayed in the columns of Information Schema tables including the [COLLATIONS](https://dev.mysql.com/doc/refman/8.0/en/information-schema-collations-table.html) and [COLUMNS](https://dev.mysql.com/doc/refman/8.0/en/information-schema-columns-table.html) tables.

**Comment by markstory** [comment]
Well that makes our lives harder as we need to span multiple versions of MySQL.

**Comment by othercorey** [comment]
I don't understand why they don't do normal point releases for this stuff instead of just saying 5 patch releases is enough time to remove a deprecated feature.

**Comment by markstory** [comment]
Oracle gonna oracle.
