### ISSUE TITLE
Error in session write

### ISSUE THREAD

**Issue by StanByes** [cakephp/cakephp#16660]
### Description

Hello, I recently tried to write value of a Session in my Component with:
$this->getController()->getRequest()->getSession()->write('visit_check', true);

Then the website throw this error: Cake\Http\Session::_overwrite(): Argument #1 ($old) must be of type array, null given, called in C:\laragon\www\Project\vendor\cakephp\cakephp\src\Http\Session.php on line 508

### CakePHP Version

4.4.3

### PHP Version

8.1.8

**Comment by markstory** [comment]
That error often comes up when sessions cannot be started. Have you checked your logs to make sure that PHP is able to start a session?

**Comment by StanByes** [comment]
I tried again now, the issue is gone.
Thank you
