### ISSUE TITLE
Update laminas/laminas-diactoros to the latest version because of vulnarability

### ISSUE THREAD

**Issue by vivekpipaliya** [cakephp/cakephp#16667]
### Description

I found that current version of laminas/laminas-diactoros package used in cakephp latest version is vulnerable to HTTP Header Injection in ServerRequestFactory.php, which does not filter out untrusted values for X-Forwarded-* headers for Laminas\Diactoros\Uri instances.

It was reported by snyk platform. Find more details in below screenshot and given link.
![image](https://user-images.githubusercontent.com/60814309/182615197-c86f4180-6a79-49ae-b894-70fc7dde856b.png)

https://security.snyk.io/vuln/SNYK-PHP-LAMINASLAMINASDIACTOROS-2961637

I think we should update laminas/laminas-diactoros package to latest version.

**Comment by LordSimal** [comment]
CakePHP's version string for `laminas/laminas-diactoros` is `^2.2.2`, therefore all versions from `>=2.2.2 <3.0.0` will automatically be checked and the latest one installed when you perform a `composer update -W` in your app.

If it doesn't update for your app please check your dependencies via `composer why laminas/laminas-diactoros` to see all packages which require `laminas/laminas-diactoros`
