### ISSUE TITLE
Postgres Driver : Max Alias Length

### ISSUE THREAD

**Issue by marcelobns** [cakephp/cakephp#16662]
### Description

Why 63? It shouldn't be.
Maybe it's a typo.

### CakePHP Version

4.x

**Comment by othercorey** [comment]
Why shouldn't it be?

**Comment by marcelobns** [comment]
Because is no longer a standard, and can be raiser in NAMEDATALEN.
Could be a convention and not obligation.

**Comment by othercorey** [comment]
It's the default length. I think most people are using the default postgres build and not a custom executable.

**Comment by othercorey** [comment]
You can also create a custom driver if you need to support a custom server.
