### ISSUE TITLE
Problem with aliasname of subquery to the same table

### ISSUE THREAD

**Issue by samyan** [cakephp/cakephp#16679]
### Description

Hello. Just check the generated query:

````sql
SELECT 
  RedeemedFinishedBonus.bonus_uid AS RedeemedFinishedBonus__bonus_uid, 
  RedeemedFinishedBonus.player_id AS RedeemedFinishedBonus__player_id, 
  RedeemedFinishedBonus.redeemed_count AS RedeemedFinishedBonus__redeemed_count 
FROM 
  redeemed_finished_bonus RedeemedFinishedBonus 
WHERE 
  id = (
    SELECT 
      (
        MAX(id)
      ) 
    FROM 
      redeemed_finished_bonus RedeemedFinishedBonus 
    WHERE 
      (
        bonus_uid = bonus_uid
        AND player_id = player_id 
      )
  )
````

I've tried to set the ALIAS but as **getTableLocator()** always returns the same table instance, so it's not working. If you ask me why I put the conditional in that way, it is because it is part of another LEFT JOIN complex query

### CakePHP Version

4.2

### PHP Version

7.4

**Comment by ADmad** [comment]
Use [Table::subquery()](https://book.cakephp.org/4/en/orm/query-builder.html#subqueries) as stated in the manual.

**Comment by samyan** [comment]
> Use [Table::subquery()](https://book.cakephp.org/4/en/orm/query-builder.html#subqueries) as stated in the manual.

Thank you for response. I will check it!

**Comment by samyan** [comment]
I don't know if i'm doing something wrong but the generated query is the same:


````php
$table = $this->getTableLocator()->get('RedeemedFinishedBonus');

// Construimos la query de max id
$maxIdQuery = $table
	->subquery()
	->select($rfbQuery->func()->max(['id']))
	->from()
	->where([
		'bonus_uid' => 'bonus_uid',
		'player_id' => 'player_id'
	]);

// Construimos la query de LEFT JOIN
$leftJoinSubQuery = $table
	->find()
	->select([
		'bonus_uid',
		'player_id',
		'redeemed_count'
	])
	->where([
		'id' => $maxIdQuery
	]);
````

````sql
SELECT 
  RedeemedFinishedBonus.bonus_uid AS RedeemedFinishedBonus__bonus_uid, 
  RedeemedFinishedBonus.player_id AS RedeemedFinishedBonus__player_id, 
  RedeemedFinishedBonus.redeemed_count AS RedeemedFinishedBonus__redeemed_count 
FROM 
  redeemed_finished_bonus RedeemedFinishedBonus 
WHERE 
  id = (
    SELECT 
      (
        MAX(:param0)
      ) 
    FROM 
      redeemed_finished_bonus RedeemedFinishedBonus 
    WHERE 
      (
        bonus_uid = : c1 
        AND player_id = : c2
      )
  )

````

**Comment by samyan** [comment]
I reopen the issue as the problem persist. 

I have this query structure.
- query
	- sub_query
		- sub_query

So i've tried to add `->subquery()` to the **first** sub_query for convenience. After add `->subquery()`, i get this result:

````sql
SELECT 
  id, 
  bonus_uid, 
  player_id, 
  redeemed_count 
FROM 
  redeemed_finished_bonus RedeemedFinishedBonus 
WHERE 
  id = (
	SELECT 
	  (
		MAX(RedeemedFinishedBonus.id)
	  ) AS id 
	FROM 
	  redeemed_finished_bonus RedeemedFinishedBonus 
	WHERE 
	  (
		RedeemedFinishedBonus.bonus_uid = bonus_uid 
		AND RedeemedFinishedBonus.player_id = player_id
	  )
  )
````

You can see that the fields of the first subquery that don't have the alias but the table name still has alias and that is causing incorrect result. 

The solution I propose is to have the ability to indicate a custom alias. In this way I think it would not be necessary to have the **->subquery()** function and it would be much more elegant something like that:

````php
$table = $this->getTableLocator()->get('RedeemedFinishedBonus');
$table ->setAlias('RedeemedFinishedBonus2');

$table2 = $this->getTableLocator()->get('RedeemedFinishedBonus')->newInstance();
$table2 ->setAlias('RedeemedFinishedBonus1');

$query = $table->find();

$maxIdQuery = $table
	->find()
	->select([
		'id' => $query->func()->max('id')
	])
	->where(function (QueryExpression $exp) {
		return $exp
			->eq('bonus_uid', new IdentifierExpression('RedeemedFinishedBonus1.bonus_uid'))
			->eq('player_id', new IdentifierExpression('RedeemedFinishedBonus1.player_id'));
	});

$leftJoinSubQuery = $table2 
	->find()
	->select([
		'id',
		'bonus_uid',
		'player_id',
		'redeemed_count'
	])
	->where([
		'id' => $maxIdQuery
	]);

````

**RESULT:**

````sql
SELECT 
  RedeemedFinishedBonus1.id, 
  RedeemedFinishedBonus1.bonus_uid, 
  RedeemedFinishedBonus1.player_id, 
  RedeemedFinishedBonus1.redeemed_count 
FROM 
  redeemed_finished_bonus RedeemedFinishedBonus1 
WHERE 
  id = (
	SELECT 
	  (
		MAX(RedeemedFinishedBonus2.id)
	  ) AS id 
	FROM 
	  redeemed_finished_bonus RedeemedFinishedBonus2 
	WHERE 
	  (
		RedeemedFinishedBonus2.bonus_uid = RedeemedFinishedBonus1.bonus_uid 
		AND RedeemedFinishedBonus2.player_id = RedeemedFinishedBonus1.player_id
	  )
  )


````

**Comment by ADmad** [comment]
`$this->getTableLocator()->get('NewAlias', ['className' => 'ReedemedFinishedBonus'])` will give you a new table instance with a different alias.

**Comment by markstory** [comment]
> The solution I propose is to have the ability to indicate a custom alias. In this way I think it would not be necessary to have the ->subquery() function and it would be much more elegant something like that:

This already roughly exists though. With a query (or subquery) you can:

```php
// Using your example code from above.
$leftJoinSubQuery = $table2 
	->find()
	->select([
		'id',
		'bonus_uid',
		'player_id',
		'redeemed_count'
	])
        ->from(['RedeemedFinishedBonus2' => 'redeemed_finished'])
	->where([
		'id' => $maxIdQuery
	]);
```

The `from()` method lets you define a custom table alias, and combined with `subquery()` you can skip column prefixing in the subqueries. For *complex* queries you also don't have to use the ORM builder. If your query is using nested subqueries, you might be better served by using a [prepared statement](https://book.cakephp.org/4/en/orm/database-basics.html#database-basics-binding-values). Write the SQL you want and bind the parameters to protect against SQL injection.

**Comment by samyan** [comment]
Hello. Thank you to both guys! Works perfectly.
