### ISSUE TITLE
Update to 4.4 - Deprecated BaseErrorHandler in one of many *.js file from webroot

### ISSUE THREAD

**Issue by michalfordonski** [cakephp/cakephp#16672]
### Description

Upgrade to 4.4 - Deprecated BaseErrorHandler in one of many * .js files from webroot - only for one of many plugins (it's like the others - created by me)

Output from browser:
<br />
<b>Deprecated</b>:  Use of `BaseErrorHandler` and subclasses are deprecated. Upgrade to the new `ErrorTrap` and `ExceptionTrap` subsystem. See https://book.cakephp.org/4/en/appendices/4-4-migration-guide.html
/config/bootstrap.php, line: 127
You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`. Adding `config/bootstrap.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` config will mute deprecations from that file only. in <b>/vendor/cakephp/cakephp/src/Core/functions.php</b> on line <b>321</b><br />
$(document).ready(function () {
    $('[name="field"]').datetimepicker({
        format: 'YYYY-MM-DD HH:mm',
        icons: {
            time: 'fa fa-clock-o',
            date: 'fa fa-calendar',
            up: 'fa fa-chevron-up',
            down: 'fa fa-chevron-down',
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-calendar-o',
            clear: 'fa fa-trash',
            close: 'fa fa-times'
        },
        stepping: $timeInterval,
        locale: $lang.i18n
    });
});

URL: localhost/Driver/js/plugin/script.js

Plugin: Driver
File: /plugins/Driver/webroot/js/plugin/script.js

Content of file:

$(document).ready(function () {
    $('[name="field"]').datetimepicker({
        format: 'YYYY-MM-DD HH:mm',
        icons: {
            time: 'fa fa-clock-o',
            date: 'fa fa-calendar',
            up: 'fa fa-chevron-up',
            down: 'fa fa-chevron-down',
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-calendar-o',
            clear: 'fa fa-trash',
            close: 'fa fa-times'
        },
        stepping: $timeInterval,
        locale: $lang.i18n
    });
});

This message is nowhere to be found.

### CakePHP Version

4.4

### PHP Version

7.4

**Comment by markstory** [comment]
This error is coming up in your plugin assets as they are being handled by Cake's AssetMiddleware.

You can either update your error handling to use the new ErrorTrap/ExceptionTrap classes or turn off the deprecation for those files.
