### ISSUE TITLE
cakephp 2.10 .htaccess redirection not working

### ISSUE THREAD

**Issue by siddharthaweb** [cakephp/cakephp#16678]
### Description

I would like to use webroot .htaccess file to redirect one url in my project
```
<IfModule mod_rewrite.c>
    RewriteEngine On    
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
    ## additional rules written by me
    RewriteRule /mylink/old_article_id /mylink/new_article_id [R=301,L]
</IfModule>
```
but this rule in not working in godaddy shared hosting.

### CakePHP Version

2.10

### PHP Version

7.3

**Comment by LordSimal** [comment]
This is not a defect from CakePHP, its just an invalid .htaccess you are using.
The RewriteRule part should look like this:
```
RewriteRule ^mylink/old_article_id$ https://mydomain.com/mylink/new_article_id? [R=301,L]
```
Also see: https://www.301-redirect.online/htaccess-rewrite-generator
I would recommend googling things like that before creating issues on github.

**Comment by siddharthaweb** [comment]
Thank you for your suggestion the missing symbol was a typo. But If I write the correct formation, it is not working. 
#Example : RewriteRule ^mylink/old_article_id$ /mylink/new_article_id? [R=301,L]
Please suggest a way out with .htaccess based solution.

**Comment by ADmad** [comment]
Use an appropriate support forum to get help with URL rewriting rules. Your problem isn't directly related to the CakePHP framework.

**Comment by garas** [comment]
Your rule is not applied, because URL is already matched by previous rule and is last (L):
```
RewriteRule ^(.*)$ index.php [QSA,L]
```

For simple redirects, better use [Redirect / RedirectPermanent](https://httpd.apache.org/docs/2.4/mod/mod_alias.html) instead.
