### ISSUE TITLE
Dev error page no longer show any arguments

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16683]
### Description

Steps to reproduce:
1) clone and install `cakephp/app`
2) enable debugging
3) generate any error page (404 error page is fine for checking this)
4) select any function from stack trace and then click `Toggle Arguments` button to reveal arguments
5) you will get `No arguments` for every function

Modifying line below to `'args' => true,` seems to fix problem
https://github.com/cakephp/cakephp/blob/4.x/src/Error/Renderer/WebExceptionRenderer.php#L263

### CakePHP Version

4.4.4

### PHP Version

7.4.3

**Comment by markstory** [comment]
> you will get No arguments for every function

I'm not sure this is *new*. Looking back to 4.3.0 there were also no arguments present. I'm happy to turn them on though as I agree it is useful context to have in development.
