### ISSUE TITLE
Cannot marshal data 

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/cakephp#16709]
### Description

Cannot marshal data for "ArticleAttributeAttachments" association. It is not associated with "MypluginArticlesAttributes"

In ArticleAttributeAttachments:

```php
$this->belongsTo('ArticlesAttributes', [
            'className' => 'Myplugin.ArticlesAttributes',
            'foreignKey' => 'articles_attribute_id',
            'joinType' => 'INNER',
        ]);
```

Is it normal that it says associated MypluginArticlesAttributes ? Because the class is not named like that? The code used to work in cakephp 3, but without it being in a plugin that is.

### CakePHP Version

4.4.4

### PHP Version

8.0

**Comment by tgoeminne** [comment]
It would seem it is using the setTable(myplugin_articles_attributes) value instead of using the actual table class name residing inside the plugin folder?

**Comment by markstory** [comment]
How can someone reproduce the scenario you're in? We have a few existing tests covering associations with plugin models and they are currently passing .

**Comment by tgoeminne** [comment]
the database tables : myplugin_articles_attributes and the table class ArticlesAttributes

Then when using patchentity 'Associated' => ['Attributes._joinData.ArticleAttributeAttachments']

Then it says it is not associated with MypluginArticlesAttributes. The marshaller is somehow adding the plugin name to the table class. Articles and Attributes is belongstomany relation. If I not use setTable to change the table name it would work correctly but because of use the setTable it is looking for the wrong association a class which doesnt exist and hasnt been declared. If you understand.

**Comment by tgoeminne** [comment]
In the table class you write setTable('myplugin_articles_attributes') so I can use the different table then the class is named. But the association is linking it to table name which is different from the actual classname. Having the tables prefixed with myplugin_ is easy for managing the database. But I dont want to use the prefix in the table class names otherwise they become too long...

**Comment by tgoeminne** [comment]
Or is it because of the joinTable value on belongstomany that it uses that tablename as classname?

**Comment by tgoeminne** [comment]
I guess thats the problem since the tablename and classname are different you would need a setting probably for classname of jointable and tablename of jointable, while you only have the tablename option now in the belongstomany

**Comment by tgoeminne** [comment]
maybe using the class instead of the tablename in jointable would be eassier there... then when you use setTable it would still work as expected....

**Comment by tgoeminne** [comment]
So in joinTable can also write the classname instead of the table name? Then it works fine...

**Comment by tgoeminne** [comment]
Great then can close this, just write joinTable('Myplugin.ArticlesAttributes') solve my problem
