### ISSUE TITLE
Command arguments with same 'choices' array are considered equal and therefore ignored

### ISSUE THREAD

**Issue by MuresanSergiu** [cakephp/cakephp#16715]
### Description

I'm trying to create a command that imports some entities from one partner to another. Therefore I needed to add 2 arguments: a "from-partner-id" and a "to-partner-id" which would have the same usage/choices array. Here's that part of the code:
```php
$parser->addArgument('from-partner-id', [
    'required' => true,
    'help' => 'The partner id from which we import the data',
    'choices' => array_map(function (Partner $partner) {
        return "$partner->id";
    }, $partners),
]);
$parser->addArgument('to-partner-id', [
    'required' => true,
    'help' => 'The partner id to which we import the data',
    'choices' => array_map(function (Partner $partner) {
        return "$partner->id";
    }, $partners),
]);
```
Whenever I am running this command it tells me I only have 1 argument defined even though I defined 2 of them. The issue is with this line: https://github.com/cakephp/cakephp/blob/4.x/src/Console/ConsoleInputArgument.php#L99 which is used here https://github.com/cakephp/cakephp/blob/4.x/src/Console/ConsoleOptionParser.php#L503

### CakePHP Version

4.3.5

### PHP Version

8.1

**Comment by othercorey** [comment]
@markstory Can we merge your fix or was there an issue?

**Comment by markstory** [comment]
>  Can we merge your fix or was there an issue?

Oops, I forgot to open the pull request.
