### ISSUE TITLE
Possibility to add attributes for empty option

### ISSUE THREAD

**Issue by ghost** [cakephp/cakephp#16721]
### Description

... because in design we need sometimes placeholder for select. Otherwise we have to use JavaScript hacks.

```
$this->Form->control('something', [
    'type' => 'select',
    'empty' => [
        'text' => 'Select something...',
        'disabled' => true,
        'hidden' => true,
    ],
    'required' => true,
]);
```

### CakePHP Version

4.x

**Comment by ADmad** [comment]
The option with empty value acts as a placeholder. If you set the option as hidden it won't be visible at all and if you set it as disabled its shown only in the options selection dropdown. So I don't see how either of those options help you display a placeholder value.

**Comment by ghost** [comment]
Yes, but without any styling options like color, font, opacity... 

<img width="401" alt="01" src="https://user-images.githubusercontent.com/57835176/188153708-974ab647-66d8-4735-94b4-7a16e8a6a073.png">
<img width="390" alt="02" src="https://user-images.githubusercontent.com/57835176/188153716-70a756b7-1666-4540-816e-9089e0777fab.png">

If it were possible to add attributes, only a couple of CSS lines would be enough.

**Comment by ADmad** [comment]
Sorry I still don't understand. How did you get the "search for role"?  `<select>` doesn't support the `placeholder` attribute (unless my knowledge is outdated).

Would be better if you could provide a jsfiddle example to show what you are trying to achieve.

**Comment by ghost** [comment]
For a better understanding, I will explain why I need these attributes. I described it wrong before (sorry).
I needed to create a placeholder for select the same as for input - color, opacity, not visible on focus (same UI and UX)...
I used the required attribute for select to change the color with pseudo selectors in CSS:

```html
<select required="required">
    <option value="">Placeholder</option>
</select>

<style>
select:invalid {
    color: #929496;
}
select:focus:invalid {
    color: transparent;
}
</style>
```

And for behavior like input placeholder (disabled and not visible on dropdown in select) I need put attributes `disable` and `hidden` for empty option...
For now I'm putting in these attributes via JS:

```js
document
  .querySelectorAll("form select")
  .forEach((e) => {
    if (!e.options[0].value) {
      let attrs = Object.entries({
        disabled: "disabled",
        hidden: "hidden",
      });
      for (const [key, value] of attrs) {
        e.options[0].setAttribute(key, value);
      }
    }
  });
```

It's just for design where you need the same UI and UX as other form elements... mostly always. And yeah, it's not about performance or anything like this. Just because attributes should be added everywhere they can.

**Comment by ADmad** [comment]
Have you checked your solution in Firefox? :slightly_smiling_face: Unlike Chrome it doesn't show the "Placeholder" at all if you set the option as hidden.

**Comment by ADmad** [comment]
https://www.w3docs.com/snippets/css/how-to-create-a-placeholder-for-an-html5-select-box-by-using-only-html-and-css.html

So the trick to get same display in both Chrome and Firefox is to add `selected` attribute too for the empty option.

@jarovarga You are welcome to open a pull request for the suggested change.

**Comment by ghost** [comment]
I use Firefox Developer Edition 105.0b5 and screenshots above and screenshot bellow are from FF...

<img width="635" alt="03" src="https://user-images.githubusercontent.com/57835176/188179676-600d6070-d93a-40e4-8189-80520b7c9d28.png">
