### ISSUE TITLE
Add a form template for class "required"

### ISSUE THREAD

**Issue by ghost** [cakephp/cakephp#16746]
### Description

Add a form template for the `required` input like `selectedClass` template for implementing CSS methodologies such as BEM, ABEM, SMACSS, etc.

Eg class: `--required`

### CakePHP Version

4.4.5

**Comment by markstory** [comment]
We already have the `required` & `aria-required` attributes. These attributes could be used in your CSS rules.

**Comment by ghost** [comment]
Unfortunately not :( because containing white space. Therefore add prefix is impossible eg `—{white space}required`.

>

**Comment by markstory** [comment]
> Unfortunately not :( because containing white space. Therefore add prefix is impossible eg `—{white space}required`.

I'm confused, with the current attributes that form helper adds you can write CSS rules like

```css
input[required] {
}
input[aria-required="true"] {
}
```

While I recognize these are not strictly conformant with some CSS authoring trends, they can be used, so what is 'impossible'?

I'm reluctant to add yet another place/attribute to input elements to indicate it is required when we already have two.

**Comment by ghost** [comment]
It’s not about input attributes. It’s about class for input wrapper: https://github.com/cakephp/cakephp/blob/3c4de0ac44b2e6e5a65fb1101ad0c7f4b3a0f765/src/View/Helper/FormHelper.php#L1183

It’s impossible add prefix to this class (required) because whitespace. Template var for input type with prefix eg `—{{type}}` is fine because result is `—email`.

Example of “nice to have”:

<div class=“form__input —{{type}} —{{required}} —error”>

**Comment by ADmad** [comment]
> Example of “nice to have”:
> `<div class=“form__input —{{type}} —{{required}} —error”>`

You can customize the `inputContainer` and `inputContainerError` templates to achieve what you want as explained in the [manual](https://book.cakephp.org/4/en/views/helpers/form.html#customizing-the-templates-formhelper-uses).

**Comment by ghost** [comment]
Ok, one more time... For class/template var `required` I simply cannot add a prefix because `$options['options']['required'] ? ' required' : ''` contain whitespace. Template var `{{required}}` is unusable except as set `{{type}}{{required}}`.

FormHelper:
```
protected $_defaultConfig = [
    'templates' => [
        'inputContainer' => '<div class="input {{type}}{{required}}">{{content}}</div>',
    ],
];
```

My AppView:
```
$this->Form->setTemplates([
    'inputContainer' => /** @lang text */ '<div class="form__input --{{type}} --{{required}}">{{content}}</div>',
]);
```

Result:
```
<div class="form__input --email -- required"><input...
```

Expected result:
```
<div class="form__input --email --required"><input...
```

**Comment by othercorey** [comment]
Can you use the `trim()` filter in twig to remove the whitespace?

**Comment by ghost** [comment]
Yes, but that's just bending. If I wanted to use the `required` class, it must also return a negative result like `not-required`. Template vars `{{type}}`, `{{name}}` always returns a results... but only for this `required` I must bending template or even better write som JS.

**Comment by othercorey** [comment]
I can't talk about the variable design in cakephp forms, but I think it's ok to build twig functions to build what you need from the variables.

They should have reliable values between point and major releases.

**Comment by ghost** [comment]
It's just something I noticed during development and had to deal with it. It's not a problem or something like that. Just "nice-to-have" for a front-ends needs.

**Comment by markstory** [comment]
> Can you use the trim() filter in twig to remove the whitespace?

Form helper templates aren't using twig, they use similar syntax but don't have filters or conditionals.

> It’s impossible add prefix to this class (required) because whitespace. Template var for input type with prefix eg `—{{type}}` is fine because result is `—email`.

Ah ok, I get it now. Yes adding leading characters to the required class segment wouldn't be possible. If you're willing to put together a pull request with tests, I would be on-board with making the existing template value more flexible.

**Comment by othercorey** [comment]
> > Can you use the trim() filter in twig to remove the whitespace?
> 
> Form helper templates aren't using twig, they use similar syntax but don't have filters or conditionals.

Whoops. I was confused, but just assumed some configuration allowed it.

**Comment by dereuromark** [comment]
Whats the result of this?
The PR it seems is not moving forward.

**Comment by markstory** [comment]
I forgot about this, I'll take another look this week.

**Comment by ADmad** [comment]
Done in https://github.com/cakephp/cakephp/commit/87a8e1f09926e24fe9736119273f969cb24449df
