### ISSUE TITLE
TreeBehavior not adding lft / rght

### ISSUE THREAD

**Issue by zunnu** [cakephp/cakephp#16748]
### Description

I'm trying to get the tree behaviour to work.
I have parent_id, lft, rght in the table and on the model initialize I have:
```
        parent::initialize($config);

        $this->translatableFields = ['title', 'description'];
        $this->addBehavior('Translate', ['fields' => $this->translatableFields]);
        $this->setTable('industries');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->addBehavior('Tree', [
            'parent' => 'parent_id',
            'left' => 'lft',
            'right' => 'rght'
        ]);
```

When I set the parent_id in this case to be 2 the tree information is not set. Below screenshot is taken after save() is called.
![image](https://user-images.githubusercontent.com/7551907/189704279-b0bd55b0-1f79-4fa2-b2a8-8c41f3025704.png)

### CakePHP Version

4.4

### PHP Version

7.4

**Comment by markstory** [comment]
How can someone reproduce the problems you're having? We have test coverage around TreeBehavior and `lft/rght` columns being populated and those tests are currently passing.

**Comment by othercorey** [comment]
Have you tried discussion this issue in the slack channel?

**Comment by zunnu** [comment]
This has been solved on Slack. The problem was that parent_id was set to 0 when empty rather than null
