### ISSUE TITLE
Validation of Entities with propertyName set are not working

### ISSUE THREAD

**Issue by mcube27** [cakephp/cakephp#16778]
### Description

In a table I have set an association like this :
```
$this->hasMany(
            'TimetableTimeRanges',
            [
                'propertyName' => 'time_ranges',
                'dependent' => true,
                'sort' => [
                    'TimetableTimeRanges.start',
                ],
            ]
        );
```
Note, I have set the property name.

In the same table, I do a validation like this :
```
 $validator->requirePresence('time_ranges', true, __('Time ranges must be given'));
```
But the validation does not take it into account. However, it does take it into account if my "field" is named "timetable_time_ranges".

But if I have named the property "time_ranges", I will never marshall an entity with a "timetable_time_ranges" field.

### CakePHP Version

4.4.4

### PHP Version

8.1

**Comment by ADmad** [comment]
Have you set `time_ranges` as accessible in the parent table's entity?

**Comment by mcube27** [comment]
Yes 
```
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
```

**Comment by markstory** [comment]
@mcube27 I wasn't able to reproduce this issue. Could you look at #16797 and let me know what I'm missing?

**Comment by mcube27** [comment]
In my case, I save a Timetable Entity that contains weekdays. Each Weekdays contains TimetableTimeRanges. I did a test like this : 
```
public function testValidationDefault(): void
    {

        $timetable = $this->Timetables->newEntity(
            [
                'valid_from' => '2022-10-03',
                'employee_id' => EMPLOYEE_ID_JESSICA,
                'weekdays' => [
                    [
                        'available' => true,
                        'flexible' => true,
                        'weekday' => 1,
                        'time_ranges' => [
                            [
                                'start' => null,
                                'end' => null,
                                'duration' => null,
                                'break' => null,
                                'location_id' => '',
                                'position' => 1,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'associated' => [
                    'Weekdays.TimetableTimeRanges',
                ],
            ]
        );
        // dd($timetable);

        dd($timetable->getErrors());
    }
```

In TimetablesTable, the association is :
```
$this->hasMany('Weekdays')
            ->setDependent(true)
            ->setCascadeCallbacks(true)
            ->setSort(['Weekdays.weekday'])
            ->setSaveStrategy(HasMany::SAVE_REPLACE);
```
In WeekdaysTable, the association is :
```
$this->hasMany(
            'TimetableTimeRanges',
            [
                'propertyName' => 'time_ranges',
                'dependent' => true,
                'sort' => [
                    'TimetableTimeRanges.start',
                ],
            ]
        );
```
During the debugging of the test, the `time_ranges` do not trigger all validation errors. If I rename them `timetable_time_ranges` in the data of the test and remove proertyName, they do. 

Here is the debug with propertyName as `time_ranges` and data with `time_ranges`: 
```
[
  'valid_from' => [
    'valid_from' => 'Valid from must be in the future'
  ],
  'weekdays' => [
    (int) 0 => [
      'time_ranges' => [
        (int) 0 => [
          'location_id' => [
            '_empty' => 'Location can't be left empty'
          ]
        ]
      ]
    ]
  ]
]
```
And here without the propertyName and the data with `timetable_time_ranges` :
```
[
  'valid_from' => [
    'valid_from' => 'Valid from must be in the future'
  ],
  'weekdays' => [
    (int) 0 => [
      'timetable_time_ranges' => [
        (int) 0 => [
          'start' => [
            '_empty' => 'Start must be given'
          ],
          'end' => [
            '_empty' => 'End must be given'
          ],
          'duration' => [
            '_empty' => 'Duration must be given'
          ],
          'location_id' => [
            '_empty' => 'Location can't be left empty'
          ]
        ]
      ]
    ]
  ]
]
```
I expect the second output with propertyName set.

Hope I could make it clearer.

**Comment by markstory** [comment]
What is special about `location_id` that results in it showing up as an error in both scenarios?

**Comment by mcube27** [comment]
Hi,

I figured out. I used an afterMarshall hook and did some changes on `start`, `end` and the errors associated were wiped out.

I thought it was an issue with the propertyName, but it was just "luck" it worked with changed propertyName.

However, is it expected that the errors linked to the field should be wiped clean if you touch a property in the afterMarshall ?

**Comment by markstory** [comment]
>  However, is it expected that the errors linked to the field should be wiped clean if you touch a property in the afterMarshall ?

Yes that is expected. Updating a field's value invalidates validation state as the validation was applied to a value that is no longer present in the entity.

**Comment by mcube27** [comment]
I understand. But it got me surprised. Found a way using beforeMarshall instead. Sorry again for the trouble !
