### ISSUE TITLE
Simplify event callback signature

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#16786]
Currently, there is a certain uncertainty regarding signatures here, specifically the return type(s).
Also, the documentation is lacking that information across all events:
- https://book.cakephp.org/4/en/orm/table-objects.html#beforemarshal
- https://book.cakephp.org/4/en/controllers.html#controller-life-cycle
- https://book.cakephp.org/4/en/views/helpers.html#helper-api

I found it cumbersome to find the signatures from the docs actually, I had to look into the code in some cases for
- https://github.com/dereuromark/cakephp-ide-helper/pull/285/files
- https://github.com/dereuromark/cakephp-ide-helper/pull/286/files

etc, and still only then used the "recommended" or likely return signature.

As for 5.x: Is there a reason to stick to the "old ways" of returning?
> In order to stop events you can either return false in your callbacks or call the stopPropagation() method on the event object:

https://book.cakephp.org/4/en/core-libraries/events.html#stopping-events

```php
        if ($event->isStopped()) {
            $result = $event->getResult();
            if ($result === null) {
                return false;
            }

            if ($result !== false) {
                assert(
                    $result instanceof EntityInterface,
                    sprintf(
                        'The beforeSave callback must return `false` or `EntityInterface` instance. Got `%s` instead.',
                        get_debug_type($result)
                    )
                );
            }

            return $result;
        }
```
Or could we just make those all void and let the event propagation be stopped via its API and methods.
```php
    public function beforeSave(EventInterface $event, EntityInterface $entity, ArrayObject $options): void
    {
    }
```

You could still pass `$event->setResult(false);` to stop the event if needed, but maybe also that part could be deprecated then?

Any feedback?

So call of actions:
- [ ] Documentation clarity for 4.x+
- [ ] Signature changes if any for 5.x

**Comment by ADmad** [comment]
I wouldn't want to break BC for the return values for the event callbacks.

I think the main issue is that we don't have stub/concrete methods for the event callbacks which makes their discoverability difficult. Perhaps adding `@method` annotations for them would avoid having to shift through the docs to find the method signatures for the callback methods?

**Comment by markstory** [comment]
> I wouldn't want to break BC for the return values for the event callbacks.

Agreed, breaking compatibility for this feels hard to justify. We're not making userland code safer, or easier to build. Having the mixed return type is a bit awkward for us but makes userland code simpler as they can return the modified entity or false to stop the event. Returning `false` was intended to give our event system consistent and predictable behavior to folks who are familiar with the DOM event handlers.

Using `@method` annotations could help with discoverability :+1:

**Comment by dereuromark** [comment]
I dont think method annotations would be more helpful than current stub inclusion via IdeHelper.
There is even the risk that it then makes people try to ::parent() call those, as those seem "existing".

Then I would rather recommend focusing on the docs mentioning the possible return types.

As for BC breaks:
"false" case could stay, but the other cases seem not useful and it is quite unlikely a lot of code would be touched by this even.

**Comment by ADmad** [comment]
> There is even the risk that it then makes people try to ::parent() call those, as those seem "existing".

Well the code would error out for calls to non-existent parent methods.

> Then I would rather recommend focusing on the docs mentioning the possible return types.

That's something that should surely be done.

> "false" case could stay, but the other cases seem not useful and it is quite unlikely a lot of code would be touched by this even.

I am sure non false values like returning a response instance from callback for `Controller.initialize` and `Controller.startup` should be fairly commonly and removing that would be make users quite unhappy.

**Comment by dereuromark** [comment]
> I am sure non false values like returning a response instance

I was only talking about ORM callbacks like beforeSave()/beforeMarshal() etc, sry for the unclear statement above.

As show in the example I posted, or like
```php
    public function beforeMarshal(EventInterface $event, ArrayObject $data, ArrayObject $options): void
    {
    }
```

Essentially:
```php
public function beforeMarshal(EventInterface \$event, ArrayObject \$data, ArrayObject \$options): void;
public function afterMarshal(EventInterface \$event, EntityInterface \$entity, ArrayObject \$data, ArrayObject \$options): void;
public function beforeFind(EventInterface \$event, Query \$query, ArrayObject \$options, \$primary): void;
public function buildValidator(EventInterface \$event, Validator \$validator, \$name);
public function buildRules(EventInterface \$event, RulesChecker \$rules);
public function beforeRules(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options, \$operation): void;
public function afterRules(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options, \$result, \$operation): void;
public function beforeSave(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
public function afterSave(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
public function afterSaveCommit(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
public function beforeDelete(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
public function afterDelete(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
public function afterDeleteCommit(EventInterface \$event, EntityInterface \$entity, ArrayObject \$options): void;
```
buildValidator() also should return void - and buildRules() returns own object afaik. We probably want to typehint that too.

I didnt plan on touching the Controller ones.

This refs the discussion @ https://github.com/dereuromark/cakephp-ide-helper/issues/288 about what to best "default" to here.

**Comment by dereuromark** [comment]
So am I able to make a PR to only allow void for the ORM specific ones mentioned above in 5.x?
And a soft deprecation in 4.4?
Any objections to this?

**Comment by markstory** [comment]
> So am I able to make a PR to only allow void for the ORM specific ones mentioned above in 5.x?

I think that sounds reasonable.
