### ISSUE TITLE
QueryBuilder support : json_table

### ISSUE THREAD

**Issue by albarqx** [cakephp/cakephp#16799]
### Description

[https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html 3](https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html)

Hi, 
Query builder will automatically adds parentheses () and this will break the query …

Can you please add feature to accept this type of table? or control to add/not add "()" ?

More explanation

$json_table = $query->expr("JSON_TABLE(col, path COLUMNS (columns))");
$query->select(['t.id']);
$query->from(['t' => 'table', 'jt' => $json_table]);

this is output
[sql] => SELECT t.id FROM table t, (JSON_TABLE(col, path COLUMNS (columns))) jt

While it should be like this
[sql] => SELECT t .id FROM table t , JSON_TABLE(col, path COLUMNS (columns)) jt

Thank you

**Comment by markstory** [comment]
Have you tried using `$query->func()->json_table(['col', 'path COLUMNS (columns)'])`? That might be a way around the extra parenthesis.

We're not likely to add formal support for `json_table` as it lacks support in more than one of the databases we support.

**Comment by celsowm** [comment]
I would add this too (json path): https://github.com/cakephp/cakephp/issues/15073

All main dbms supports json nowadays and would be very cool to add to CakeORM

**Comment by markstory** [comment]
> All main dbms supports json nowadays and would be very cool to add to CakeORM

If folks want to add cross platform function helpers to `FunctionBuilder` by all means please send pull requests. We're looking for one or two functions per pull request with tests that pass against mysql, sqlite, postgres and sqlserver. We don't want to add support for any functions that are not available on all platforms as then we're offering broken abstractions that aren't yet possible.

**Comment by celsowm** [comment]
> > All main dbms supports json nowadays and would be very cool to add to CakeORM
> 
> If folks want to add cross platform function helpers to `FunctionBuilder` by all means please send pull requests. We're looking for one or two functions per pull request with tests that pass against mysql, sqlite, postgres and sqlserver. We don't want to add support for any functions that are not available on all platforms as then we're offering broken abstractions that aren't yet possible.

this is exactly the case of **JSON_PATH/VALUE** (_used in json_table btw_):

- mysql: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=591207ceddca6fe4f11a3ad8589e7c5b
- sqlserver: https://dbfiddle.uk/?rdbms=sqlserver_2017&fiddle=5c70245f5bb7c96d4adcc6b10ebed195
- postgres: https://dbfiddle.uk/?rdbms=postgres_13&fiddle=0914b4d9622b28f813eed51bab263203
- sqlite: https://www.db-fiddle.com/f/tMcVDVmjxb5wSjemg34dy8/2

But in the case of **json_table**, is a little bit different, because the similar on sqlserver is [OPENJSON](https://learn.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver16).
On the other hand, [Postgres 15 supports it](https://pganalyze.com/blog/5mins-postgres-sql-json-table-postgres15).
Unfortunately **sqlite** does not have a native solution yet, but it is possible to [emulate using json_array](https://github.com/jOOQ/jOOQ/issues/11465).

**Comment by albarqx** [comment]
> Have you tried using `$query->func()->json_table(['col', 'path COLUMNS (columns)'])`? That might be a way around the extra parenthesis.
> 
> We're not likely to add formal support for `json_table` as it lacks support in more than one of the databases we support.

I tried this ..

```php
      $json_table = $query->func()->json_table(['col', 'path COLUMNS (columns)']);
      $query->select(['t.id']);
      $query->from(['t' => 'table', 'jt' => $json_table]);
```

and this the output

```sql
SELECT `t`.`id` FROM `table` `t`, (json_table(:param0, :param1)) `jt`
```

still showing parenthesis ..  the issue as I believe is ->from(); .. 



Suggestion:
you can give user control to pass whatever he wants without adding automatic parenthesis something like this 

```php
      $json_table = new markstory($query->func()->json_table(['col', 'path COLUMNS (columns)']));
      $query->select(['t.id']);
      $query->from(['t' => 'table', 'jt' => $json_table]);
```

then ->from will examine the entry 

```php
if ($table instanceof markstory) 
{

   .. then no parenthesis otherwise it will added as default

} else {
//Add parenthesis

}
```

this will be useful to be done under user desire for whatever he wants .. this will make any commands like json_table auto supported instead of pull request every time . 


Thank you @markstory

**Comment by markstory** [comment]
@albarqx Thanks for trying out the existing APIs we have. I agree that it would be ideal to not need to add additional methods for platform specific things. Looking at how queries are compiled, the additional parenthesis are coming from how `QueryCompiler::_buildFromPart` is stringifying expressions.

Previously the main use case for expressions in `FROM` were for sub-queries which do require the additional parenthesis. We would need additional cases for expressions that aren't subqueries.
