### ISSUE TITLE
Quoting error in BelongsToMany queries on Oracle Driver

### ISSUE THREAD

**Issue by stbuccia** [cakephp/cakephp#16819]
### Description

Hi,

Using the BelongsToMany Association from CakePHP 4.3, is generated query like this:

```sql
SELECT TstArticlesTags.article_id AS "TstArticlesTags__article_id", TstArticlesTags.tag_id AS "TstArticlesTags__tag_id" 
FROM (
    SELECT TstArticlesTags.tag_id AS "tag_id" 
    FROM tst_tags Tags 
    INNER JOIN tst_articles_tags TstArticlesTags ON Tags.id = TstArticlesTags.tag_id WHERE TstArticlesTags.article_id = :c0
) TstArticlesTags__matches 
INNER JOIN tst_articles_tags TstArticlesTags ON TstArticlesTags.tag_id = TstArticlesTags__matches.tag_id
```

but in apps I use CakeDC Oracle Plugin, and in Oracle DB this is an erroneous query and I get this error:

`ORA-00904:` "TSTARTICLESTAGS__MATCHES"."TAG_ID": invalid identifier`

The correct modification of the query could be deleting the quotes in line 3 of the query:

```sql
SELECT TstArticlesTags.tag_id AS tag_id
```

or adding quotes in line 7:

```sql
INNER JOIN tst_articles_tags TstArticlesTags ON TstArticlesTags.tag_id = TstArticlesTags__matches."tag_id"
```

So modifing `CORE/src/ORM/Association/BelongsToMany` line 1198 could resolve:

```php
$matchesConditions[$aliased] = new IdentifierExpression($junctionQueryAlias . '."' . $key . '"');
```

Thank you

### CakePHP Version

4.3.10

### PHP Version

8.1

**Comment by markstory** [comment]
> Using the BelongsToMany Association from CakePHP 4.3, is generated query like this:

How are you generating that query?, and do you have identifier quoting enabled?

> So modifing CORE/src/ORM/Association/BelongsToMany line 1198 could resolve:

Your suggested change cannot be made as it will fail on databases that do not use `"` as the quoting character (eg. mysql, sqlserver).  We could use the quoting separators instead though.

**Comment by stbuccia** [comment]
> How are you generating that query?

I generate the query, having a post request in edit action where are modified the tags associated to article, so the situation is similar to the one described in [CakePHP tutorial](https://book.cakephp.org/4/en/tutorials-and-examples/cms/tags-and-users.html#updating-articles-to-enable-tagging), actually the association is in `ArticlesTable`:

```php
$this->belongsToMany('Tags', [
            'joinTable'  => 'tst_articles_tags',
            'foreignKey' => 'article_id',
            'targetForeignKey' => 'tag_id',
            'dependent' => true
        ]);
```

> do you have identifier quoting enabled?

No, I also tried to enable it, but also every query generated is erroneous because in the DB all the table and column names are uppercase:

```sql
SELECT "Articles"."id" AS "Articles__id", "Articles"."title" AS "Articles__title", "Articles"."body" AS "Articles__body", "Articles"."published" AS "Articles__published", "Articles"."created" AS "Articles__created", "Articles"."modified" AS "Articles__modified" 
FROM "tst_articles" "Articles" 
WHERE "Articles"."id" = :c0 FETCH NEXT 1 ROWS ONLY 
```

so in this case it can't find table "tst_articles" and all the fields selected. I know that (and also I tried) it's possible to set 'case' to 'upper' in Oracle Driver, but then I should have to use uppercase for every field reference in the code, which is odd .

**Comment by markstory** [comment]
Thanks for getting back to me about identifier quoting. We would need to see if we can remove the quoting on the sub-query selected field without causing problems in other database platforms. Given that your database schema is in all caps you might need to work with all uppercase values as that is how your schema is defined.

> I know that (and also I tried) it's possible to set 'case' to 'upper' in Oracle Driver, but then I should have to use uppercase for every field reference in the code, which is odd .

That's expected actually. Entity attributes reflect the database schema, so if you cast all the identifier to upper case that's what you'd get.

**Comment by markstory** [comment]
Going to close this. It has been a year or so and no other activity has been added to this issue. I think this might be an issue that is only impacting you as your schema has all fields upper cased, but you want to use lowercased attribute names. This isn't something I think we can or should handle automatically in the ORM. With Cake's conventions your schema == your attribute names. This reduces the cognitive load and runtime overhead of the ORM for most use cases. 

If you really need this re-casing of fields some places to attempt it could be:

- In `resultDecorator` in all of your queries (using a base class, or `Model.beforeFind` listener). In your `resultDecorator` you can down case the entity attributes. 
- Override `EntityTrait` methods to make attribute reads automatically downcase.

There are likely other solutions to the problem, and you might better know how to solve your problem as well. I don't think this is a problem that the framework can address without adding overhead to all applications, and most do not.
