### ISSUE TITLE
CakePHP with Mailer + Microsoft with SASL XOAUTH2 

### ISSUE THREAD

**Issue by michalfordonski** [cakephp/cakephp#16815]
### Description

Hi,
in connection with the withdrawal of basic verification by Microsoft, I would like to suggest introducing the new verification service to the mailer. From what I was able to determine, the situation is similar in the case of Google.
Link to the authorization description in Microsoft:
[https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth)

Unfortunately, I did not find anything about the topic in your documentation.

### CakePHP Version

4.0

**Comment by ADmad** [comment]
The thing about Google/Gmail is the tokens they provide for SASL XOAUTH2 are short lived (1 hour), so in practice just adding support for `XOAUTH2` auth to our `SmtpTransport` wouldn't help much. One needs to implement the whole [token generation/refreshing flow](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2) which isn't something that belongs in the CakePHP core, and best done as a separate community plugin.

**Comment by ADmad** [comment]
[Microsoft](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#smtp-protocol-exchange)'s and [Google](https://developers.google.com/gmail/imap/xoauth2-protocol#smtp_protocol_exchange)'s docs show slightly different client-server responses for `AUTH XOAUTH2`. I wonder if using either one works for both.

**Comment by michalfordonski** [comment]
I have the most up-to-date token refresh service, but does the mailer allow me to send an email using the current token? If not, can you extend the mailer / transport to include this option? I would not like to use two mailing systems in the application (CakePHP Mailer and PhpMailer). Due to the steps taken by Microsoft, there will probably be more people like me.

I'm not sure if MS and Google work the same way, but from what I knew with PhpMailer, the call is the same for them:

MS:
https://github.com/PHPMailer/PHPMailer/pull/2793/files#diff-28e122e27586817e889514dd346f49b26de94bb1005be022dfcc73d5e3380f95

Google:
https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps

**Comment by ADmad** [comment]
> does the mailer allow me to send an email using the current token? If not, can you extend the mailer / transport to include this option?

Currently the mailer (`SmtpTransport`) doesn't support using `XOAUTH2` but it's not too difficult to update it to do so.

> I'm not sure if MS and Google work the same way, but from what I knew with PhpMailer, the call is the same for them:

Given that `XOAUTH2` is a standard specification I would exact both MS and Google to work with the same way. It's just that the token can be specified for `AUTH XOAUTH2` in couple of different ways and MS's and Google's docs use the 2 different ways. I'll look at `PhpMailer`'s code.

**Comment by michalfordonski** [comment]
@ADmad Different configurations still return this or the associated error. In the specification from the administrator, I have indications that the Microsoft sending integration should use TLS 1.0 or later. Is it so?

In the configuration, I have the EmailTransport.default.tls key set to true

SMTP Error: 530 5.7.57 Client not authenticated to send mail. Error: 535 5.7.3 Authentication unsuccessful

SMTP Error: 535 5.7.3 Authentication unsuccessful

**Comment by ADmad** [comment]
Please continue the conversation on the PR  #16821 so that it's easier to follow for everyone.
