### ISSUE TITLE
TimeHelper is passing timestamps into the DateTime constructor

### ISSUE THREAD

**Issue by PaulPatat** [cakephp/cakephp#16820]
### Description

Backporting some cake 3 functions to a cake 2 application. Dates are stored
in a Europe/Amsterdam timezone.

Since cake 3's TimeHelper uses ICU formats I've added a date() function
to a custom helper to replace Timehelper::format().

```php
use Cake\I18n\Time;

function date($t, $format) {
    if ($t === null || $t === 0 || $t === '0000-00-00 00:00:00') {
        return '-';
    }
    try {
        $time = new Time($t);
        return $time->i18nFormat($format);
    } catch (Exception $e) {
        return '-';
    }
}
```

One of our templates does date calculations using strtotime(). As a result $Time->format() gets a
timestamp. $Time->format() works correctly, while my replacement function is off by two hours.

This is because Cake\I18n\Time is constructed with a timestamp, which gives the wrong result if the server timezone
isn't UTC, as explained on https://stackoverflow.com/questions/12038558/php-timestamp-into-datetime/35525866#35525866

CakePHP 3's TimeHelper::format does the same and must therefore have the same issue.

### CakePHP Version

3.10.2

### PHP Version

7.4

**Comment by markstory** [comment]
> This is because Cake\I18n\Time is constructed with a timestamp, which gives the wrong result if the server timezone isn't UTC

Timestamps are always interpreted as UTC by PHP's `DateTime` object as well.

> CakePHP 3's TimeHelper::format does the same and must therefore have the same issue.

Changing how timestamps are handled will cause all existing applications to become 'wrong' instead. Unfortunately, we can't make that kind of behavior change at this time in 3.x.

**Comment by PaulPatat** [comment]
> > This is because Cake\I18n\Time is constructed with a timestamp, which gives the wrong result if the server timezone isn't UTC
> 
> Timestamps are always interpreted as UTC by PHP's `DateTime` object as well.

The interpretation of the timestamp is correct (and can't be wrong since timestamps don't have timezones).
It's the DateTime (or Cake\I18n\Time) itself that gets the wrong timezone in this case:


```
>>> App::uses('View', 'View');
=> null
>>> App::uses('TimeHelper', 'View/Helper');
=> null
>>> $Time = new TimeHelper(new View());
=> TimeHelper {#2646
     +settings: [
       "engine" => "CakeTime",
     ],
     +helpers: [],
....
   }
>>> $date = new DateTime();
=> DateTime @1666173224 {#2655
     date: 2022-10-19 11:53:44.510649 Europe/Amsterdam (+02:00),
   }
>>> $Time2 = new Cake\View\Helper\TimeHelper(new Cake\View\View());
=> Cake\View\Helper\TimeHelper {#2668
....
   }
>>> $Time->format('d-m-Y H:i', $date);
=> "19-10-2022 11:53"
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 11:53"
>>> $date = $date->getTimeStamp();
=> 1666173224
>>> $Time->format('d-m-Y H:i', $date);
=> "19-10-2022 11:53"
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 9:53"
```

There is a discrepancy here in the last two outputs.

Usually this defect will be hidden by TimeHelper's 'outputTimezone'
configuration but if it's null, there is no reason why it should not
obey PHP's default timezone setting.


> 
> > CakePHP 3's TimeHelper::format does the same and must therefore have the same issue.
> 
> Changing how timestamps are handled will cause all existing applications to become 'wrong' instead. Unfortunately, we can't make that kind of behavior change at this time in 3.x.

I should add that the CakePHP 4 branch seems to have the same problem.

**Comment by ADmad** [comment]
When using a timestamp PHP will simply ignore the timezone as stated in the [manual](https://www.php.net/manual/en/datetime.construct.php).

> The $timezone parameter and the current timezone are ignored when the $datetime parameter either is a UNIX timestamp (e.g. @946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

**Comment by PaulPatat** [comment]
> When using a timestamp PHP will simply ignore the timezone as stated in the [manual](https://www.php.net/manual/en/datetime.construct.php).
> 
> > The $timezone parameter and the current timezone are ignored when the $datetime parameter either is a UNIX timestamp (e.g. @946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

That is my point. If the timestamp is converted to a DateTime with setTimestamp(), this problem does not occur:

```
>>> $date = (new DateTime())->setTimestamp($date);
=> DateTime @1666173224 {#2678
     date: 2022-10-19 11:53:44.0 Europe/Amsterdam (+02:00),
   }
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 11:53"
```

**Comment by othercorey** [comment]
I'm sorry but your example is not clear and hard to read.

Are you saying that the TimeHelper time zone setting is not respected when a timestamp is passed to `format()`?

**Comment by PaulPatat** [comment]
The TimeHelper output timezone is null. It's not always respecting the php timezone setting:

```
>>> $Time2 = new Cake\View\Helper\TimeHelper(new Cake\View\View());
=> Cake\View\Helper\TimeHelper {#2648
     +fieldset: [],
     +tags: [],
     helpers: [],
     implementedEvents: [],
     _config: [
       "outputTimezone" => null,
     ],
   }
>>> $date = "2022-10-19 11:53:44";
=> "2022-10-19 11:53:44"
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 11:53"
>>> $Time2->format($date, 'd-M-yyyy H:mm', false, 'Europe/Amsterdam');
=> "19-10-2022 11:53"
>>> $date = new DateTime($date);
=> DateTime @1666173224 {#2654
     date: 2022-10-19 11:53:44.0 Europe/Amsterdam (+02:00),
   }
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 11:53"
>>> $Time2->format($date, 'd-M-yyyy H:mm', false, 'Europe/Amsterdam');
=> "19-10-2022 11:53"
>>> $date = $date->getTimeStamp();
=> 1666173224
>>> $Time2->format($date, 'd-M-yyyy H:mm');
=> "19-10-2022 9:53"
>>> $Time2->format($date, 'd-M-yyyy H:mm', false, 'Europe/Amsterdam');
=> "19-10-2022 11:53"
>>> date_default_timezone_get();
=> "Europe/Amsterdam"
```

**Comment by markstory** [comment]
> The TimeHelper output timezone is null. It's not always respecting the php timezone setting:

The `outputTimezone` isn't supposed to inherit the default timezone. It is a supposed to be configured by application code to define which timezone value should be formatted in. Generally this is used to format values into the user's preferred timezone.

In your example when you pass in a timestamp to `TimeHelper`, the assumed timezone is coerced to UTC as you're using a timestamp. If that's not what you want, don't pass in timestamps.

**Comment by othercorey** [comment]
Does this resolve the issue?

**Comment by PaulPatat** [comment]
I'm not sure whom you're asking, but if you mean my issue, i solved that already by fixing my date function:

```
        function date($t, $format) {
                if ($t === null || $t === 0 || $t === '0000-00-00 00:00:00') {
                        return '-';
                }
                try {
                        if (is_numeric($t)) {
                                $time = new Time();
                                $time->setTimestamp($t);
                        } else {
                                $time = new Time($t);
                        }
                        return $time->i18nFormat($format);
                } catch (Exception $e) {
                        return '-';
                }
        }
```

If you mean the defect in cake 3's TimeHelper::format() when passed a timestamp, no. It's not consistent with Cake 2's, nor is it consistent with itself when passed a string. If you don't see a problem with that, I have nothing more to add.
