### ISSUE TITLE
Route prefix redirect me to /webroot/prefix

### ISSUE THREAD

**Issue by LoickMEYER** [cakephp/cakephp#16823]
### Description

Hello,
I've build an admin panel with route prefix : 
```php
  $routes->prefix('administration', function (RouteBuilder $routes) {
      $routes->connect('/', ['controller' => 'Pages', 'action' => 'dashboard']);
      $routes->connect('/dashboard', ['controller' => 'Pages', 'action' => 'dashboard']);

      $routes->fallbacks(DashedRoute::class);
  });
```

The problem is that when i try to access to `mywebsite.com/administration` CakePhp redirect me to `mywebsite.com/webroot/administration` 
But, when I try to access to `mywebsite.com/administration/`  (With the "/" at the end) it's work fine.

Regards
Loic

### CakePHP Version

4.4.6

### PHP Version

7.4

**Comment by ADmad** [comment]
This is a URL rewriting issue with your webserver, not a routing issue. Please use one of our supports forums for help.

P.S. You can also avoid such problems by setting your webserver's document root to the "webroot" folder.
