### ISSUE TITLE
Invalid array access in MysqlSchemaDialect::listTablesSql() 

### ISSUE THREAD

**Issue by UlrichEckhardt** [cakephp/cakephp#16827]
### Description

The error I snatched from the logs is this:
```
Argument 1 passed to Cake\Database\Driver\Mysql::quoteIdentifier() must be of the type string, null given, called in /var/www/html/squeeze/vendor/cakephp/database/Schema/MysqlSchemaDialect.php on line 45
```

The code where this occurs is:
```
    public function listTablesSql(array $config): array
    {
        return ['SHOW FULL TABLES FROM ' . $this->_driver->quoteIdentifier($config['database']), []];
    }
```
I managed to work around this by simply removing the `FROM <database>` from the generated SQL code. This seems to work and it gives me the info I'm after.

Notes:
* I'm using the cakephp/database package, not the full cake package.
* Its sibling `listTablesWithoutViewsSql()` is similarly affected. 
* `describeForeignKeySql()` also uses `$config['database'])`, not sure if that needs work, too.
* The according functions for other DBs seem to not retrieve this parameter from the array, so they seem to not be affected, but I haven't really verified that.
* I don't really know what is expected from the `$config` array. It could be that my app is messed up, so that this array just isn't populated correctly. I'd welcome feedback on that matter. Alternatively, some `assert()`s in the code would help, too.

### CakePHP Version

4.4.5

### PHP Version

7.4.30

**Comment by ndm2** [comment]
Are you configuring your connection with a pre-instantiated driver object by any chance? Like in the first example shown in the readme?

**Comment by othercorey** [comment]
https://book.cakephp.org/4/en/orm/database-basics.html#configuration

Here is an example of a datasource/db configuration.

**Comment by UlrichEckhardt** [comment]
I'm not sure which readme you're referring to, @ndm2 , but maybe I can clarify things with a little bit of code:

```
$config = [
    'host' => ...,
    'port' => ...,
    'database' => ...,
    'username' => ...,
    'password' => ...,
];
$driver = new Cake\Database\Driver\Mysql($config);
$connection = new Cake\Database\Connection([
    'driver' => $driver,
    'log' => false,
]);
$schema = $connection->getSchemaCollection();
$schema->listTables();
```
That's basically the steps we take for establishing and using a DB connection.

**Comment by ndm2** [comment]
I mean [**the `cakephp/database` package's readme**](https://github.com/cakephp/database/blob/master/README.md), which shows that exact usage.

The code that's failing for you obtains the configuration from the connection, and the connection doesn't know about the driver's configuration. That's a small problem right there.

It should work fine when creating a connection as shown in the docs that @othercorey linked, with the options passed to the connection. Passing only the `database` option would probably work too, though that's bit of a dirty workaround.

Not sure what could be done about it in the framework right now, as the driver's interface doesn't expose all the necessary configuration.

**Comment by ADmad** [comment]
@UlrichEckhardt For the time being you can avoid the problem by creating your connection instance like this:

```php
$connection = new Cake\Database\Connection([
    'driver' => Cake\Database\Driver\Mysql::class,
    'host' => ...,
    'port' => ...,
    'database' => ...,
    'username' => ...,
    'password' => ...,
    'log' => false,
]);
```

**Comment by UlrichEckhardt** [comment]
@ADmad, thanks! Not only does that give me a workaround, I'm even saving a bunch of code like that. =)

As far as I'm concerned, this ticket could be closed. I'm not sure how the maintainers here see this though, i.e. whether they consider it an actual bug.
