### ISSUE TITLE
Sqlserver driver: add an flag option to disable cursor client buffer

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#16848]
### Description

In some situations, its desired to avoid the use of the [SQL Server Driver Client buffer](https://learn.microsoft.com/en-us/sql/connect/php/cursor-types-pdo-sqlsrv-driver?view=sql-server-ver16) (examples: performance, large result sets, use of varbinary etc.)
Currently, on CakePHP4.*, the are only "two" ways:

- **First**: using **disableBufferedResults()** in all queries that can/could have potential to overflow the client buffer
- **Second**: creating a CustomDriver extending Cake\Database\Driver\Sqlserver and overwriting the [prepare method](https://github.com/cakephp/cakephp/blob/4.x/src/Database/Driver/Sqlserver.php#L200)  literally removing [this line](https://github.com/cakephp/cakephp/blob/78c541b884c04c9fbd983950b61c46ecb6a7a6ee/src/Database/Driver/Sqlserver.php#L207):
`PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => PDO::SQLSRV_CURSOR_BUFFERED`

I would like to propose a simple modification of on Sqlserver driver:

```php
public function prepare($query): StatementInterface
    {
        $this->connect();

        $sql = $query;
        $options = [
            PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL,
            $this->_config['flags'][PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE]
        ];
        if ($query instanceof Query) {
            $sql = $query->sql();
            if (count($query->getValueBinder()->bindings()) > 2100) {
                throw new InvalidArgumentException(
                    'Exceeded maximum number of parameters (2100) for prepared statements in Sql Server. ' .
                    'This is probably due to a very large WHERE IN () clause which generates a parameter ' .
                    'for each value in the array. ' .
                    'If using an Association, try changing the `strategy` from select to subquery.'
                );
            }

            if (!$query->isBufferedResultsEnabled()) {
                $options = [];
            }
        }

        /** @psalm-suppress PossiblyInvalidArgument */
        $statement = $this->_connection->prepare($sql, $options);

        return new SqlserverStatement($statement, $this);
    }

```

and of course a default setting for CURSOR on [connect()](https://github.com/cakephp/cakephp/blob/78c541b884c04c9fbd983950b61c46ecb6a7a6ee/src/Database/Driver/Sqlserver.php#L114) method, something like that:

```php
if (!$config['flags'][PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE]) {
            $config['flags'][PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE] = PDO::SQLSRV_CURSOR_BUFFERED
        }
```

I hope the devs consider this because currently I have had to create a custom driver to run my real application with sql server 

### CakePHP Version

4.*

**Comment by othercorey** [comment]
This was added to improve performance on typical result sets. Are you saying you prefer to disable it for all queries?

https://book.cakephp.org/4/en/appendices/4-2-migration-guide.html#id3

**Comment by celsowm** [comment]
> This was added to improve performance on typical result sets. Are you saying you prefer to disable it for all queries?
> 
> https://book.cakephp.org/4/en/appendices/4-2-migration-guide.html#id3

Yes !

Even small result sets are faster (at least) in my environment disabling client buffer ! 

And, in my very humble opinion, would be a nice option to advanced users who prefers to disable this 

**EDIT:**
A good example of better performance without client cursor is pagination of big and complex results

**Comment by othercorey** [comment]
Well, if this does not have the desired effect, then we should consider reverting it.

Unfortunately, we've had no other feedback on this.

**Comment by celsowm** [comment]
Please no 😞

I do not think reverting is the best way, just a flag for people like me that uses lots of varbinary and had problems with client cursors.

**Comment by othercorey** [comment]
Well, we'd like to understand why you have such poor performance with small result sets.

**Comment by celsowm** [comment]
> Well, we'd like to understand why you have such poor performance with small result sets.

I made others tests here and problem is beyond that:

If I try:

```php
function myTest() {

        $table = TableRegistry::getTableLocator()->get('TableWithVarBinary');

        $conteudo = file_get_contents('arquivo.pdf'); //more than 50MB pdf
        $entity = [
            'name' => 'Very big file',
            'binario' => $conteudo, //my varbinary
            'mimetype' => 'application/pdf',
        ];

       $entity =  $table->newEntity($entity);
       $table->save($entity);
    }
```

I got this error (using the original Driver):

`Erro: SQLSTATE[IMSSP]: Memory limit of 50000 KB exceeded for buffered query`

Is there a way to disable Buffer on save() ?

**Comment by othercorey** [comment]
> `Erro: SQLSTATE[IMSSP]: Memory limit of 50000 KB exceeded for buffered query`
> 
> Is there a way to disable Buffer on save() ?

I don't think so. I didn't expect that to be affected either.

We should definitely allow this to be disabled. For some reason, I thought it could be disabled with driver config, but we can look into it.

**Comment by bor-attila** [comment]
> Well, if this does not have the desired effect, then we should consider reverting it.
> 
> Unfortunately, we've had no other feedback on this.

Azure SQL Server without this option is useless. Very slow. Poor performance.
Please consider to not revert it : )
A flag should do the job : )

**Comment by junior-paytech** [comment]
I have this same issue here.
I am working on a project that saves files in SQL Server database, and get an error 
**SQLSTATE[IMSSP]: Memory limit of 10240 KB exceeded for buffered query**

when doing a SELECT in those tables

I am using cakephp/database 5.0.11

**Comment by bor-attila** [comment]
You need to increase the limit in php.ini. For example:

`client_buffer_max_kb_size='76800'`
`sqlsrv.ClientBufferMaxKBSize=76800`
`pdo_sqlsrv.client_buffer_max_kb_size=76800`

**Comment by othercorey** [comment]
@ADmad Did your change to re-add disabling results buffering cover this?

**Comment by ADmad** [comment]
This seems to be an issue at the pdo driver level. My changes which restored 4.x behavior only disable the buffering for the fetched results.

**Comment by junior-paytech** [comment]
I followed the @celsowm suggestion and extended Sqlserver driver and remove the buffer line

**Comment by othercorey** [comment]
Do we think this flag should be disabled by disableBufferedResults only?

Would that work for you?

**Comment by celsowm** [comment]
> disableBufferedResults

Hi ! long time no see !

I have some suggestions:

A simple check on SqlServerDriver if [_config['flags']](https://book.cakephp.org/5/en/orm/database-basics.html#configuration) has something like:
`_config['flags'][PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE]`
so the cakephp + sqlserver user can use/set it own type of cursor

edit: I tried a pull request !

edit2: by the way, **PDO::SQLSRV_CURSOR_FORWARD** is the default of **SQLSRV_ATTR_CURSOR_SCROLL_TYPE**
