### ISSUE TITLE
"Html->script" type option for "module"

### ISSUE THREAD

**Issue by ghost** [cakephp/cakephp#16853]
### Description

`<script type="module" src="main.js"></script>`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by ADmad** [comment]
Did you try `$this->Html->script('main.js', ['type' => 'module'])`?

**Comment by ghost** [comment]
Yep, sorry. I don’t find this in documentation and I didn’t think to try it.

**Comment by ADmad** [comment]
The [API](https://api.cakephp.org/4.4/class-Cake.View.Helper.HtmlHelper.html#script()) description for the method's `$options` argument states that it's `Array of options, and **html attributes**`.
