### ISSUE TITLE
Strictness of event dispatch result / return values

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#16854]
###  for ORM checkRules()

Error

> Cake\ORM\Table::checkRules(): Return value must be of type bool, null returned

As the signature of that method is:
```php
public function checkRules(...): bool
```

The code inside checkRules() reads
```php
$event = $this->dispatchEvent(
    'Model.afterRules',
    compact('entity', 'options', 'result', 'operation')
);

if ($event->isStopped()) {
    return $event->getResult();
}
```

Maybe, to make this less hard to fail, we should allow null as OK value?

    return $event->getResult() ?? false;

What do you think?

### CakePHP Version

4.4.7

### PHP Version

8.1

Seems to also ref https://github.com/cakephp/cakephp/issues/16786

**Comment by dereuromark** [comment]
The code causing this seems to be this of the GeocoderBehavior:
```php
	public function beforeRules(EventInterface $event, EntityInterface $entity, ArrayObject $options) {
		if ($this->_config['on'] === 'beforeRules') {
			if (!$this->geocode($entity)) {
				$event->stopPropagation();
			}
		}
	}
```
But this code existed since the beginning of Cake3 as such, and it shouldnt throw such a hard fail error now IMO that we have those types in place in 4.x.

Or is it expected to always then add

    $event->setResult(false);
    
into that piece of code?

IMO just stopping without an explicit return result should be considered `false` by default.

**Comment by dereuromark** [comment]
Do we want to act on this regarding 4.5 or 5.0 now?

**Comment by markstory** [comment]
> Do we want to act on this regarding 4.5 or 5.0 now?

We could add the coalesce to false in 4.4. The current behavior is broken so we won't be breaking application code.

**Comment by dereuromark** [comment]
With 5.x released I guess we are closing this as works-for-us?

**Comment by dereuromark** [comment]
For 5.1 or 6.0 we might also want to look into Component/Controller signatures for events

Almost all are `Response|null|void`, but could easily be `Response|null` return typed which makes stubbing way easier, also more clear.
The only outlier seems to be 

> beforeRedirect(EventInterface $event, $url, Response $response)
Is invoked when the controller’s redirect method is called but before any further action. If this method returns false the controller will not continue on to redirect the request. The $url, and $response parameters allow you to inspect and modify the location or any other headers in the response.

The `false` part here..
Maybe we could say null is that value, and you simply continue to return the response for normal flow?

TBH: I dont think we even need that redirect cancel part, as it would just not do anything anymore? Maybe one should throw some other exception instead?

**Comment by markstory** [comment]
>  Maybe we could say null is that value, and you simply continue to return the response for normal flow?

That would break existing behavior though. Currently returning null is a no-op return. While `false` is an explicit choice.  This could be replaced with `$event->stopPropagation()` though. That is another explicit 'result' that the framework can read from application code.

**Comment by dereuromark** [comment]
We should do this with 5.1 finally, deprecation to be removed with 6.0
