### ISSUE TITLE
\Cake\ORM\Table infinite loop bug

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16874]
### Description

This simple code causes infinite loop:
```php
$table = new \Cake\ORM\Table();//no arguments are passed to constructor
$alias = $table->getAlias();//this line starts infinite loop
```
This bug was discovered while investigating  https://github.com/dereuromark/cakephp-ide-helper/issues/295

### CakePHP Version

tested on 4.4 (3.x propably also affected)

### PHP Version
tested on 8.1 (should not matter)

**Comment by markstory** [comment]
What do you think it should do? My opinion is that you shouldn't be able to make an instance with no arguments.
