### ISSUE TITLE
DateTimeType timezone in marshal()

### ISSUE THREAD

**Issue by GabrielLasso** [cakephp/cakephp#16878]
### Description

I am migrating a legacy code base to 4.3.0 and after each `Table->patchEntity($data)` with an DateTime object in $data, I got the result converted to the application default timezone.

But in my application I deal with many stores with different timezones, so I'd like the result to be in the same tz as the $data given.

From what I've searched, [this commit](https://github.com/cakephp/cakephp/commit/26cbe21352ad6c3e09fa61c92fbb48a42d3e0db5) changed the marshal method to convert the result to the default timezone. Would it be possible to make this convertion optional or to convert to `DateTimeType->userTimezone` instead?

Or is there any workaround to override DateTimeType and map `datetime` types to this new class?

### CakePHP Version

4.3.0

### PHP Version

8.1

**Comment by othercorey** [comment]
The user time zone does represent the user/UI time zone when marshalling values, but it's a persistent setting. I'm not sure how useful it actually is since all the marshalled values must be in this time zone. Since it's fixed, seems like they might as well be in the server time zone.

We could add a flag for this, but again, it's confusing since it's not configurable per-entity.

**Comment by GabrielLasso** [comment]
@othercorey I think that the new behavior of returning in a standard time zone is better in general, but I have a lot of legacy code that rely on this old behavior...

I don't think that changing this in the framework is good in general, but a flag is a good idea.

Maybe somethink like
```php
TypeFactory::build('datetime')->setConvertTimezone(false);
```

Btw, I found a solution (maybe not a good one, but works):
```

use Cake\Database\Type\DateTimeType as InternalDateTime;
use DateTimeInterface;
use Exception;

class DateTimeType extends InternalDateTime
{
    // Overwrite marshal method
}
```

And in bootstrap.php:
```
TypeFactory::map('datetime', 'App\Database\Type\DateTimeType');
TypeFactory::map('timestamp', 'App\Database\Type\DateTimeType');
```

**Comment by ADmad** [comment]
Using a custom type class to deal with such odd use cases is the right way. I don't think any change is necessary in the core.

**Comment by GabrielLasso** [comment]
@ADmad ok, thanks! So Im closing the issue
