### ISSUE TITLE
Implement SHA256 Digest Auth in \Cake\Http\Client

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#16876]
### Description

Currently the [Digest Class](https://github.com/cakephp/cakephp/blob/4.x/src/Http/Client/Auth/Digest.php) only implements MD5 but there are certain devices (like [Shelly](https://shelly-api-docs.shelly.cloud/gen2/General/Authentication/)) which require SHA256 Digest Auth

Ideally the same Algorithms will be supported as Postman offers

<img width="603" alt="image" src="https://user-images.githubusercontent.com/9105243/203789315-76fc4909-1555-47e0-a0fb-26c9f0010132.png">

### CakePHP Version

4.4

**Comment by ajibarra** [comment]
Hi, I have started the improvements required to Digest class to support multiple algorithms and qop values. While implementing I have assumed most of this would be sent under `options` but then realized than most of the time it will rely on the first response of the server (`_getServerInfo`) so I need to refactor the `constructor` a bit and also the `_getServerInfo` function to set class properties correctly. 

@LordSimal it would be great if you can provide any third party server with an API requiring some of this algorithms or options so I could make some tests against it since I am basically checking against Postman but usually people won't be passing the algorithm or qop params beforehand.

You can see the progress here: https://github.com/CakeDC/cakephp/blob/bcce7d989ae80dc82274ef1719762a06873058c9/src/Http/Client/Auth/Digest.php

**Comment by LordSimal** [comment]
As far as I understand it there is no real difference between SHA256 Digest Auth and MD5 Digest Auth despite the algorithm used to hash the data. So the logic should still be the same, only the hashing algorithm should be adjustable/configurable.

In theory you can start up a NodeJS server with a MD5 digest implementation like [this one](https://www.dotnetcurry.com/nodejs/1237/digest-authentication-nodejs-application) and try if it works with your changes.

Depending on your OpenSSL version (and maybe your NodeJS version) there are different hashing algorithms present which you can see [here](https://nodejs.org/api/crypto.html#cryptocreatehashalgorithm-options)

Hope this helps you.

I currently only have my [Shelly Plug](https://shelly-api-docs.shelly.cloud/gen2/General/Authentication/) which requires that SHA256 install which I am not that easily able to "provide" to you since it currently controls a lightswitch in our office 😁

**Comment by LordSimal** [comment]
We are currently using guzzle to call the api. So you could try to use that as a verification process as well.
``` php
$client = new \GuzzleHttp\Client([
    'base_uri' => 'http://hostname-or-ip',
    'auth' => ['admin', 'somesupersecretpassword', 'digest'],
]);
$response = $client->request('GET', '/rpc/Switch.Toggle?id=0');
if ($response->getStatusCode() === 200) {
    return true;
}
// or parsing json
$response = $client->request('GET', '/rpc/Input.GetStatus?id=0');
if ($response->getStatusCode() === 200) {
    $result = (string)$response->getBody();

    return json_decode($result, true)['state'];
}
```

**Comment by ajibarra** [comment]
> As far as I understand it there is no real difference between SHA256 Digest Auth and MD5 Digest Auth despite the algorithm used to hash the data. So the logic should still be the same, only the hashing algorithm should be adjustable/configurable.
> 
> In theory you can start up a NodeJS server with a MD5 digest implementation like [this one](https://www.dotnetcurry.com/nodejs/1237/digest-authentication-nodejs-application) and try if it works with your changes.
> 
> Depending on your OpenSSL version (and maybe your NodeJS version) there are different hashing algorithms present which you can see [here](https://nodejs.org/api/crypto.html#cryptocreatehashalgorithm-options)
> 
> Hope this helps you.
> 
> I currently only have my [Shelly Plug](https://shelly-api-docs.shelly.cloud/gen2/General/Authentication/) which requires that SHA256 install which I am not that easily able to "provide" to you since it currently controls a lightswitch in our office 😁

Thank you! I will try with the nodejs server.

**Comment by LordSimal** [comment]
See https://github.com/cakephp/cakephp/pull/17035
