### ISSUE TITLE
Validation::url doesn't conform to RFC1035

### ISSUE THREAD

**Issue by iffonox** [cakephp/cakephp#16894]
### Description

The comment on this function refers to RFC1035 for the definition of a valid domain, but the regex in Validation::$_pattern['hostname'] does not conform to this RFC.

It will reject valid domain names like "localhost", because it expects the name to contain at least one ".".

### CakePHP Version

4.4.7

**Comment by ADmad** [comment]
Can you please provide a link to the relevant section of the RFC cause I can't find anything here https://www.ietf.org/rfc/rfc1035.txt regarding "localhost".

**Comment by iffonox** [comment]
It's in section [2.3.1](https://www.rfc-editor.org/rfc/rfc1035#section-2.3.1). It's not specifically about "localhost", but the grammar described there allows domain names without a "." (domain -> subdomain -> label).

**Comment by ADmad** [comment]
Hmm the standard is too broad and allowing any label as a hostname would make the validator useless for most practical purposes. IIRC in the past we decided to got with the practical use case rather than following the RFC to the "T". We can perhaps update the documentation to clarify that.

**Comment by iffonox** [comment]
Yes, it is very broad. 

Would adding "localhost" as a special case be possible, as this is probably the most common single word domain name the validator will encounter?

**Comment by ADmad** [comment]
Personally I would be okay with that, let's see what others have to say.

**Comment by markstory** [comment]
I am not a fan of including localhost. While useful for development it creates opportunity for serverside request forgery to other services on non-public networks.

Why do you need localhost to be counted as a valid url?

**Comment by iffonox** [comment]
It's mostly for development, but also because it is a valid domain name.

I don't think the validator is the correct place to protect against serverside request forgery, as it only checks the syntax and doesn't know which URLs should/shouldn't be accessible.

**Comment by othercorey** [comment]
I think we could put security checks into Http Client that requires an option to allow local domains or IPs. That could be enabled by test suites.

**Comment by markstory** [comment]
>  I don't think the validator is the correct place to protect against serverside request forgery, as it only checks the syntax and doesn't know which URLs should/shouldn't be accessible.

That's fair, and I agree that URL validation alone isn't enough to prevent SSRF.

> It's mostly for development, but also because it is a valid domain name.

Yes it is *valid* but it is rarely a value you would want stored in a production application. We've made similar deviations from the specs for email addresses. We don't accept *all* theoretically valid email addresses and instead aim to only accept values that would exist in the wild.

We could add an option/flag or another validator method that accepts localhost and other not `.` delimited host names. I don't like the idea of changing what the default validation rules accept as we're likely to break an existing application or have to deal with additional support issues complaining that `localhost` shouldn't be valid.

**Comment by othercorey** [comment]
> We could add an option/flag or another validator method that accepts localhost and other not `.` delimited host names. I don't like the idea of changing what the default validation rules accept as we're likely to break an existing application or have to deal with additional support issues complaining that `localhost` shouldn't be valid.

I also prefer a special validator that includes local domains.

**Comment by markusramsak** [comment]
Adding an extra option for those who really need it would be the best solution I think. Most developers haven‘t misses it the last ten years of the framework therefore I am sure it is not a pressing issue. And zhere is always the possibility to build a custom validation rule or extend existing ones.

**Comment by dereuromark** [comment]
Does anyone want to provide a PR here for 5.0 or 4.5?
