### ISSUE TITLE
Simplified select type mapping

### ISSUE THREAD

**Issue by UlrichEckhardt** [cakephp/cakephp#16890]
### Description

Greetings!

In the `TypeMapTrait` trait, there is a method `setTypeMap()` taking an `array` or a `TypeMap`. In the `Query` class, there is a similar method `setSelectTypeMap()`. This method only takes a `TypeMap`, not an `array`. Can you add this feature? It would make code using this a tiny bit more readable.

That said, two quick questions: 

- I was wondering whether the use of the `TypeMapTrait` in `Query` was done correctly. Point is, that the setters there call `$this->_dirty()`. The setters from the `TypeMapTrait` don't do that though, which may or may not be a bug.
- Why is there a separate `setTypeMap()` and `setSelectTypeMap()` in the `Query` class?

Thank you!

### CakePHP Version

4.4.7

**Comment by UlrichEckhardt** [comment]
I'm suggesting something like this untested code:

```
    /**
     * Sets the TypeMap class where the types for each of the fields in the
     * select clause are stored.
     *
     * @param \Cake\Database\TypeMap|array $typeMap Creates a TypeMap if array, otherwise sets the given TypeMap
     * @return $this
     */
    public function setSelectTypeMap($typeMap)
    {
        $this->_selectTypeMap = is_array($typeMap) ? new TypeMap($typeMap) : $typeMap;
        $this->_dirty();

        return $this;
    }
```

**Comment by markstory** [comment]
That sounds reasonable to me. Would you be willing to put a pull request together?

**Comment by ADmad** [comment]
What practical usage improvement would this achieve? Unless using the database package directly one rarely needs to set the select typemap explicitly.

**Comment by UlrichEckhardt** [comment]
It's indeed the use case you mention, @ADmad, we're using the DB package directly.

Concerning the pull request, @markstory, I can probably do that when I find time. My first thought was to ask whether it was going in the right direction though, but it seems I'm on track there.

**Comment by othercorey** [comment]
@UlrichEckhardt This is unrelated, but we rarely get feedback on this use case. Do you use the I18n package with the Database package for datetime types?

**Comment by UlrichEckhardt** [comment]
@othercorey, I'm not aware of using the i18n package. The app I'm working on was built on manual SQL formatting and PDO use. We're now using Cake to allow writing code that is agnostic of the SQL dialect and for reliability. Using type mapping, we're hoping to improve code further. And yes, we are using it to map datetime values, but I have no idea (it's currently out of scope) whether we're handling timezones correctly.
