### ISSUE TITLE
Table::getOrNull(), nullable version of Table::get()

### ISSUE THREAD

**Issue by ckbx-cakebox** [cakephp/cakephp#16904]
### Description

`Table::get()` throws `RecordNotFoundException` if the `$primaryKey` does not exist.

It is reasonable for the first codes in the controller actions; if it does not exist, then show 404 error pages. But if the non-existence is the regular case, we have to select the following: to call `get` with try-catch statement, or use `Query` chain methods like `findById()`, `first()`.

As known, using exceptions in non-exceptional cases is regarded as a bad habit.

```php
try {
    /** @throws RecordNotFoundException */
    $article = $articlesTable->get($id);
} catch (RecordNotFoundException $e) {
    $article = null;
}
if ($article === null) {
    // ...
}
```

The other hands, the results of `Query` chains is `EntityInterface|array|null` (`array` is the case of disabled hydration) , so it should be typed manually.

```php
/** @var Article|null */
$article = $articlesTable->findById($id)->first();
```

## Table::getOrNull()

`Table::getOrNull()` is implemented as such:

```php
class Table
{
    public function getOrNull($primaryKey, array $options = []): ?EntityInterface
    {
        try {
            return $this->get($primaryKey, $options);
        } catch (RecordNotFoundException $e) {
            return null;
        }
    }
}
```

It can be annotated to return subtypes of `EntityInterface` with `@method`.

```php
/**
 * @method Article|null getOrNull($primaryKey, array $options=[])
 */
class ArticlesTable extends Table
{
}
```

The following code is not only looks reasonably short, but type analyzer friendly.

```php
$article = $articlesTable->getOrNull($id);
if ($article === null) {
    // ...
}
```

**Comment by ADmad** [comment]
> But if the non-existence is the regular case..

I doubt that's a common case for most apps.

You can add the `getOrNull()` easily at the app level either using a trait or behavior or a base table class and have all your tables extend that class.

**Comment by markstory** [comment]
We've been moving away from optional return types in the ORM. Instead we're trying to provide more APIs that raise errors when they encounter problems or missing data. This encourages developers to handle these scenarios explicitly.

While I can see the argument that this ceremony isn't always required, the current API isn't much longer than your example

```php
$article = $articlesTable->findById($id)->first();
if ($article === null) {
    // ...
}
```

This is only 8 characters longer than the new method. How often do you find yourself needing to use this style of optionally reading a record by id?

**Comment by dereuromark** [comment]
Closing then, as this can be done as optional part via trait etc.
