### ISSUE TITLE
paginator in plugin

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/cakephp#16909]
### Description

protected function _removeAliases(array $fields, string $model): array
--
  | {
  | $result = [];
  | foreach ($fields as $field => $sort) {
  | if (strpos($field, '.') === false) {
  | $result[$field] = $sort;
  | continue;
  | }

I get this error when clicking on the paginator links <?= $this->Paginator->sort('created') ?> inside a plugin

### CakePHP Version

4.4

### PHP Version

8.0.22

**Comment by tgoeminne** [comment]
strpos(): Argument #1 ($haystack) must be of type string, int given

**Comment by tgoeminne** [comment]
I read in cakephp5 paginator will be removed, but then there will be another method to implement the same thing right?

As for now its not version 5 so I would appreciate it, if you stop breaking the existing paginator.

**Comment by ADmad** [comment]
How can one reproduce the problem you are having?

Also paginator isn't going to be removed in Cake 5, just the PaginatorComponent is. Usage of Controller::paginate() will remain the same.

**Comment by tgoeminne** [comment]
in Plugin folder have the table ArticlesTable.php
$this->setTable('plugin_articles');
->hasMany("Plugin.ArticleOptions")

then have ArticleOptionsTable.php
$this->setTable('plugin_article_options');

->belongsTo("Plugin.Articles")

Then 

$this->paginate = [
            'contain' => ['Users','Articles'],
            'conditions' => ['user_id' => $user['id']],
            'order' => ['Articles.created DESC']
        ];
        $orders = $this->paginate($this->Articles);

data is shown correct but the paginator sort links throw the error

If outside of plugin folder everything works correct.

**Comment by tgoeminne** [comment]
the relation in plugin is like this

$this->hasMany('ArticleOptions', [
            'className' => 'Plugin.ArticleOptions',
            'foreignKey' => 'article_id'
        ]);

**Comment by tgoeminne** [comment]
If I change numericpaginator to this it works because $field seems to be 0 so str_pos is throw the error

`protected function _removeAliases(array $fields, string $model): array
    {
        $result = [];
        foreach ($fields as $field => $sort) {
            
            if($field == 0){
                continue;
            }
            
            if (strpos($field, '.') === false) {
                $result[$field] = $sort;
                continue;
            }

            [$alias, $currentField] = explode('.', $field);

            if ($alias === $model) {
                $result[$currentField] = $sort;
                continue;
            }

            $result[$field] = $sort;
        }

        return $result;
    }`

**Comment by tgoeminne** [comment]
paginate like this
'order' => ['Articles.created' => 'DESC']

paginate like before
'order' => ['Articles.created DESC'] error when sorting using paginator links

**Comment by tgoeminne** [comment]
i was using the order field like before, have changed them to use the array now...
