### ISSUE TITLE
Access to dependency injection container inside test cases

### ISSUE THREAD

**Issue by ishanvyas22** [cakephp/cakephp#16901]
### Description

Currently to unit test an individual method of the class, we are creating object of that class directly.

Example:
```php
$fooCommand = new FooCommand();
$fooCommand->doSomething();
```

This works fine as long as we don't have any dependency injection in place. After injecting a service into `FooCommand` command, this can no longer work because it can't find that injected class object.

In scenarios like this, it would be good to have access to DI container so we can fetch the class object from the container.

Example:
```php
// inside FooCommandTest.php
// Get command class
$fooCommand = $this->getContainer()->getService(FooCommand::class);

// Get service class
$fooService = $this->getContainer()->getService(FooService::class);
```

**Comment by ADmad** [comment]
Why are you not using `ConsoleIntegrationTestTrait::exec()` to run your command? That would use the normal command dispatching process and the container will get setup as it would when you run a command from CLI.

**Comment by ishanvyas22** [comment]
I don't want to test the whole command. It's a bit expensive and time consuming in this case. I just want to test a single method declared inside the command class.

Currently, the code is instantiating the command class' object in the test and calling that method. Now after introducing DI it's not working (which is expected).

**Comment by ndm2** [comment]
The container is part of your application, defining how the various services will integrate and work together, which hence is something that should be covered accordingly using integration tests.

In unit tests, just pass the required dependencies to your command constructor manually, that is still DI, just without the C, and that's perfectly appropriate in tests that are meant to cover the subject in an "isolated" manner.

**Comment by markstory** [comment]
One concern I have with adding a `getContainer()` method to test cases is around late bound dependencies. It is currently possible for dependencies to be bound 'late' after the container has been created. An example of this is `ServerRequest` which isn't added to the container until a request is handled in `BaseApplication::handle()`. It is also possible for plugins to have late bound services.

Any `getContainer()` method we could provide would be lacking these late bound services. Userland code would still need to duplicate container definitions for these services.

**Comment by ishanvyas22** [comment]
@ndm2:
> In unit tests, just pass the required dependencies to your command constructor manually, that is still DI, just without the C, and that's perfectly appropriate in tests that are meant to cover the subject in an "isolated" manner

This is what I initially thought, for 1 or 2 dependencies this is fine. But when we have 3, 4 or more manually preparing and even if that dependency itself depends on another one then it can become tricky. But I understand your point, I just wanted to know what is the recommendation(and options) to handle this kind of situations. 

@markstory: I see your point. This really needs lot more thinking if it will make maintenance and support of this hard.

**Comment by ndm2** [comment]
A unit test isn't meant to cover all dependencies, but just certain behavior of the subject, and the subject naturally shouldn't care about transitive dependencies, but only about the API of the direct dependencies that it declared.

Meaning what's important for a unit test is that these direct dependencies act as expected, and thus allow you to properly cover the subject behavior that you need to test. So if necessary, dealing with transitive dependencies can be avoided by using stubs and/or mocks accordingly.

**Comment by ishanvyas22** [comment]
@ndm2 got your point.
