### ISSUE TITLE
GitHub "create repository" template uses CakePHP 3.x gitignore

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/cakephp#16913]
### Description

In creating a new GitHub repository, and specifying the CakePHP gitignore file from the template, I notice the resulting gitignore file is for CakePHP 2 and CakePHP 3. Since that template is part of the GitHub infrastructure, I assume the core team would need to contact GitHub administration to update. I also assume the current CakePHP 4.x or 5.x gitignore is the correct solution, so this bug report contains no suggested code.

Steps to reproduce: Create a new repository (private, in my case), specifying the CakePHP gitignore from the dropdown menu.

This report, obviously, is quite minor and not really a defect, but I'm guessing this is the most appropriate classification.

### CakePHP Version

4.4.6

### PHP Version

8.0

**Comment by garas** [comment]
https://github.com/github/gitignore/blob/main/CakePHP.gitignore is the source.

**Comment by dereuromark** [comment]
You should be opening a ticket or PR on their repo
That is not within our control or domain.

**Comment by ewbarnard** [comment]
Thank you Mark and garas. I'll create a PR for that file (350 open PRs on that file!) and use current CakePHP 4.4 as my basis.
