### ISSUE TITLE
Form with empty value

### ISSUE THREAD

**Issue by Trylam** [cakephp/cakephp#16912]
### Description

I create an array. For each element I have a value and a text : 
```
$options = [];
foreach ($types as $type) {
    $elemt=[];
    $elemt['value'] = $type['id'];
    $elemt['text'] = $type['name'];
    array_push($options, $elemt);
}
```
My array has no empty elements.
In my form I have a drop down list : 
```
echo $this->Form->select('type_group_id', $options);
```
And in the list there are all the elements plus an empty element that should not be there. 
Can you help me?

### CakePHP Version

4.3.10

### PHP Version

7.4

**Comment by DGivney** [comment]
I tested your code in 4.4.x and the extra element is not present so you may want to upgrade your CakePHP version.

Alternatively you could try adding `'empty' => false` as an attribute like this.

`echo $this->Form->select('type_group_id', $options, ['empty' => false]);`

See `empty` option in the docs for more info: https://book.cakephp.org/4/en/views/helpers/form.html#options-for-select-checkbox-and-radio-controls

**Comment by Trylam** [comment]
While waiting to upgrade, your other solution works very well, thanks !
