### ISSUE TITLE
Passing undefined variables $limit and $offset, instead of function arg $num in Query::limit() and Query::offset()

### ISSUE THREAD

**Issue by petevieiratlc** [cakephp/cakephp#16938]
### Description

Release 4.2.11 contains the commit [1ca8fd3acd72fc26c9521f69ff3e8acffc5dc228](https://github.com/cakephp/cakephp/commit/1ca8fd3acd72fc26c9521f69ff3e8acffc5dc228), which introduced the following two bugs:
- In **src/Database/Query.php**, line 1497, the `limit()` method passes in `$num` but the change checks `$limit`, which doesn't exist.
- In **src/Database/Query.php**, line 1526, the `offset()` method passes in `$num` but the change checks `$offset`, which doesn't exist.

To reproduce the issue:
- Use the query builder and use the `limit()` or `offset()` methods.
- For example:
  - $this->Articles->find()->limit(5);

Problem code pasted here with my comments indication the issue:
```php
    public function limit($num)
    {
        if (is_string($limit) && !is_numeric($limit)) {  /* $limit is not defined and should be $num */
            throw new InvalidArgumentException('Invalid value for `limit()`');
        }
        $this->_dirty();
        $this->_parts['limit'] = $num;

        return $this;
    }
```

```php
    public function offset($num)
    {
        if (is_string($offset) && !is_numeric($offset)) { /* $offset is not defined and should be $num */
            throw new InvalidArgumentException('Invalid value for `offset()`');
        }
        $this->_dirty();
        $this->_parts['offset'] = $num;

        return $this;
    }
```

### CakePHP Version

4.2.11

### PHP Version

7.4.33

**Comment by markstory** [comment]
Thanks for reporting this issue. I neglected to double check the patch when it was backported to 4.2. I have the 4.2.12 release building right now which will resolve this.

**Comment by petevieiratlc** [comment]
Thanks so much!
-Pete
