### ISSUE TITLE
Trailing slash on HTML Helpers has no effect 

### ISSUE THREAD

**Issue by tobiasbhn** [cakephp/cakephp#16944]
### Description

No critical bug but discussion about the HTML Standard.

[According to the standard](https://html.spec.whatwg.org/multipage/syntax.html#start-tags):
"If the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/), which on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) marks the start tag as self-closing. On [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it does not mark the start tag as self-closing but instead is unnecessary and has no effect of any kind. For such void elements, it should be used only with caution. [..]"

Void elemets as per the standart; area, base, br, col, embed, hr, img, input, link, meta, source, track, wbr

CakePHP does not allow, as far as I know, to omit the slash from HTML helpers like meta tags.

### CakePHP Version

4.4.8

**Comment by ADmad** [comment]
The trailing slash are already removed on the `4.next` branch and will be available in `4.5.0` release.
