### ISSUE TITLE
Response withStringBody to include status code.

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#16962]
### Description

My request is specifically when using CakePHP as an API instead of a monolith.

An example snippet from my `UsersController`.

```php
$this->response = $this->response->withStatus(403);
return $this->response->withStringBody('Use refreshed token. This token has expired.');
```

and

```php
$this->response = $this->response->withStatus(401);
return $this->response->withStringBody('Token is invalid.');
```

and

```php
$this->response = $this->response->withStatus(403);
return $this->response->withStringBody('Token valid. User is not authorized to access this.');
```
and

```php
$this->response = $this->response->withStatus(402);
return $this->response->withStringBody('Subscription has expired.');
```

now the same code in Flask (Python) can be written as:

```python
return "<Message>", 40x
```

It is important for the frontend developers to classify the error they are receiving, status code helps a lot and they can show relevant error to the user or develop a good usable product.

    It is just a line extra but why write 2 when we can write 1.

In Cake 5, Can we have it so that we merge StringBody with Status? or if we already do, please point me to the docs.

**Comment by markstory** [comment]
Is there a reason you don't do combine what you have to a single line?

```php
$this->response = $this->response->withStatus(402);
return $this->response->withStringBody('Subscription has expired.');
```

can be written as

```php
return $this->response->withStatus(402)->withStringBody('Subscription has expired');
```

While its not as simple as the tuple it is a bit better. Would a method like `withStatusAndBody(402, '...')` be a significant improvement for you?

**Comment by karmicdice** [comment]
> Is there a reason you don't do combine what you have to a single line?

From readability point of view, chaining methods sometimes makes it difficult for other developers to grasp the code efficiently. But... This is a self-claimed standard 🥇 


> While its not as simple as the tuple it is a bit better. Would a method like withStatusAndBody(402, '...') be a significant improvement for you?

Yes! A definite yes!

**Comment by karmicdice** [comment]
Should this be OK?

```php
public function withStatusAndBody(int $status, ?string $string)
    {
        $new = clone $this;
        $new->_setStatus($status);
        $new->_createStream();
        $new->stream->write($string);
        return $new;
    }
```
