### ISSUE TITLE
Deprecation warning with php 8.2 due to adding queryString to Exception

### ISSUE THREAD

**Issue by nicosp** [cakephp/cakephp#16963]
### Description

Cake\Database\Log\LoggingStatement adds the queryString to any caught exception. This is deprecated starting with php 8.2 (dynamic property).

Ideally the exception should be wrapped with a custom exception class that has the property or provide the query string in another way.

### CakePHP Version

4.4.10

### PHP Version

8.2

**Comment by othercorey** [comment]
I wonder why this isn't causing a deprecation warning during unit tests.

**Comment by dereuromark** [comment]
Are those running on 8.2? Then I wonder the same thing. But had similar issues in the past with such things.
It is possible that the unit tests emit them but they stay invisible as the return code is still 0.

**Comment by othercorey** [comment]
We are running in PHP 8.2 and have seen the warning show up in test logs before. Our test case is avoiding the real-world issue.
