### ISSUE TITLE
Error in Form->setTemplates method

### ISSUE THREAD

**Issue by KengoYamazaki** [cakephp/cakephp#16972]
### Description

I set the value to false in the Form->setTemplates method in View,
and an error occurred in str_replace in _compileTemplates method in "src\View\StringTemplate.php".

Description in View
- NG Pattern(NG in PHP8.2, but OK in PHP7.4)
-----------------------------------
<?php
	$this->Form->setTemplates([
		'inputContainer' => '{{content}}',
		'label' => false,
	]);
?>
-----------------------------------

- Error content
> str_replace(): Argument #3 ($subject) must be of type array|string, bool given

If I set the value to '', the error does not occur and the intended behavior is achieved, but in PHP 7.4 it worked fine with false.

- OK pattern(PHP8.2)
-----------------------------------
<?php
	$this->Form->setTemplates([
		'inputContainer' => '{{content}}',
		'label' => '',
	]);
?>
-----------------------------------

### CakePHP Version

4.4.10

### PHP Version

8.2

**Comment by ADmad** [comment]
Templates are supposed to be strings only. PHP 8 is more strict with typing while PHP 7.4 silently casts the `false` to string that's why you didn't get an error.

**Comment by KengoYamazaki** [comment]
Thank you for your response.

However, the following statements are allowed in Form->control, and in the controls method, the official documentation also states to set false to disable the filedset.

<?= $this->Form->control('user_id', ['label' => false, 'empty' => true]) ?>

- Official document: https://book.cakephp.org/4/en/views/helpers/form.html
> The wrapping div will have a required class name appended if the validation rules for the model’s field indicate that it is required and not allowed to be empty. You can disable automatic required flagging using the 'required' option:
> echo $this->Form->control('title', ['required' => false]);

Form->control and Form->setTemplates do the same thing, but it is inconvenient that false cannot be used on one of them.
I understand that this is a specification and would be happy if you could improve it in the future.

Thank you.

**Comment by ADmad** [comment]
The the `label` option for FormHelper::control() is not a template. It's a config for the label tag generation and can be a boolean, string or even an array.

The equivalent of `setTemplates(['label' => ''])` would be `control(['templates' => ['label' => '']])`.
