### ISSUE TITLE
FrozenDate was renamed but without notice

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#16976]
### Description

On CakePHP 5.x branch the class Cake\I18n\FrozenDate was renamed but I don't see any notice in the CakePHP 4.

Are we going to have a deprecation warning in a possible 4.5 version, or just a new entry in the migration guide (doc repository)?

**Comment by othercorey** [comment]
We have not figured out a way to deprecate this in 4.x because mutable `Date` class already exists.

**Comment by markstory** [comment]
We could add an alias for `FrozenDate` that points to the new `Date`. That would avoid the hard break and we could add a deprecation for `FrozenDate` in 5.1 🤷

**Comment by othercorey** [comment]
> We could add an alias for `FrozenDate` that points to the new `Date`. That would avoid the hard break and we could add a deprecation for `FrozenDate` in 5.1 🤷

I think something for a better upgrade path would be welcome here.
