### ISSUE TITLE
getModelType/setModelType not marked as deprecated

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16974]
### Description

While `loadModel` method is marked as deprecated, methods `getModelType` and `setModelType` are not.
Until i checked cakephp 5 preview release today i incorrectly assumed that those methods will be preserved in some shape or form (in another controller trait for example).
So i suggest to mark them as deprecated same way like you did with `loadModel` method so the IDE tools would complain about their usage like they currently do with `loadModel`

### CakePHP Version

4.x

**Comment by asgraf** [comment]
Another (prefered) solution would be to add `getModelType` and `setModelType` as a part of `LocatorAwareTrait` in cakephp 5 but this would also require renaming `fetchTable` to `fetchRepository` with more generic `RepositoryInterface` return type

**Comment by markstory** [comment]
What are you using `getModelType` and `setModelType` for? I'm only aware of two implementations (cakephp/elasticsearch, and usemuffin/webservices). I'm interested in knowing more about how you've used them in your application.

For context the methods were removed as they were part of the Datasources experiment that never really panned out in my opinion. We had thought that there would be many ORM-like plugins but after building elasticsearch the abstractions we were providing were either not helpful or wrong.

**Comment by asgraf** [comment]
Most of my apps heavy rely upon `usemuffin/webservices` for custom integrations with various external APIs.
This integrations were made for internal use and i cannot publish them without my client's permission:
- custom integration with client's statistic server
- custom integration with NBP API (https://api.nbp.pl/en.html)
- custom integration with external IP to geolocation API
- custom integration with  Paypal API (planned)

All of those integrations have admin panel controller created with `FriendsOfCake/crud-view` and  `FriendsOfCake/search`
This allows easy browsing, filtering and sorting data from external apis from admin panel same way as with normal tables.
Mapping external APIs to Endpoins also creates synergy with many other cakephp plugins like `FriendsOfCake/cakephp-csvview`
I also created custom `EndpointResolver` class (based on `OrmResolver`) to integrate `Endpoint` and `Resource` classes with `cakephp/authorization`.
So as you see i'm very heavily dependent on webservices plugin and this is the main thing that can stop me from migrating to cakephp 5.

**Comment by ADmad** [comment]
Closing as the deprecations have been reverted for 4.5. Only `loadModel()` remains deprecated in favor of new `fetchModel()`.

**Comment by asgraf** [comment]
I think i would be great idea to backport [fetchModel](https://github.com/cakephp/cakephp/blob/5.x/src/Datasource/ModelAwareTrait.php#L96) method to 4.x
This would help with migrating code to 5.x

**Comment by LordSimal** [comment]
[fetchTable()](https://api.cakephp.org/4.4/trait-Cake.ORM.Locator.LocatorAwareTrait.html#fetchTable()) is present since 4.3
see https://book.cakephp.org/4/en/orm/entities.html#creating-entities

**Comment by ADmad** [comment]
> I think i would be great idea to backport [fetchModel](https://github.com/cakephp/cakephp/blob/5.x/src/Datasource/ModelAwareTrait.php#L96) method to 4.x

It has been backported in `4.next` https://github.com/cakephp/cakephp/blob/4.next/src/Datasource/ModelAwareTrait.php#L165. We can't add new methods in patch releases.
