### ISSUE TITLE
SmtpTransport events

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/cakephp#16983]
### Description

The issue:
When sending an email, it can be required to set a different sender than the one defined in the default Mailer configs.
Additionally, it may be usefull to get the output of the commands after the mail was sent.

This could be accessible if the SmtpTransport triggered events, such as _beforeSend_ and _afterSend_ with the sent message as subject.

This is something that we implemented at Passbolt. But when it comes to testing, this is pretty complex as the DebugTransport will not send these events. So we had also to create our custom DebugTransport.

It all works, but we propose to enhance the _SmtpTransport_ and the _DebugTransport_ to trigger these two events. Services can then listened to these events and set some configs on the fly and retrieve the output of the transport on the fly.

Is this something the community would be interest in?

I can provide a PR for that.

### CakePHP Version

CakePHP 4.x

**Comment by dereuromark** [comment]
I dont think Emails should ever be send sync, only async.
So whatever background task is doing it should be easily able to switch the necessary configs, no?

**Comment by pabloelcolombiano** [comment]
We sometimes send them sync, for example when the user is testing its SMTP configs and provides an array of configs in the payload.

And generally yes async using the EmailQueue. But the settings may be on file (_app/config.php_), but also in  the DB. In order to properly set the settings for all our scenarios (testing SMTP config with an endpoint, testing SMTP config with the command, sending the emails with the queue and previewing the emails with a dedicated command) with one single event, we implemented this _beforeSend_ event in order to make sure that the sender is always the right one. An _afterSend_ would also be welcome, but for the moment we do without.

But the most painful is that all this is not at all testable with the _EmailTrait_ as it will erase all transports and enforce the `TestEmailTransport`. So testing emails with our requirements is simply impossible. Considering that sending emails can be a crucial feature for an app, I though we could share that approach.

Of course if you see a better approach, I'll be very interested!

**Comment by markstory** [comment]
> This could be accessible if the SmtpTransport triggered events, such as beforeSend and afterSend with the sent message as subject.

Couldn't this and the logic that these event listeners use to swap configuration data be packaged into a transport class that wraps the SmtpTransport? Events can can lead to hard to understand side-effects, whereas a decorating class/wrapper will have all the code for this behavior co-located into a class.

**Comment by pabloelcolombiano** [comment]
Yes to your first point, this was our first approach: extend the SmtpTransport with a CustomSmtpTransport and add a method like `->processConfigBeforeSend()`. But when it came to testing, we had also to add this method our CustomDebugTransport. That was already 2 new classes. And yet this was not enough because the CustomDebugTransport got overwritten by the `TestEmailTransport`. So we also had to write a `CustomEmailTrait` to be able to test our emails.

I am not saying that what we wanted to achieve is impossible, we did it. After realizing that vital parts of our code could not be tested with the existing tools. But the Cake testing tools of the emails are IMO a bit rusty and could be improved.

I also agree that events can lead to unreadable code. But Cake is full of them, and it works really well: beforeRender, beforeSave just to name these are really nice and the Cake developer understands them. Now I was wondering why not taking this approach:

* Add two Email events
*  Make DebugTransport listen to the afterSend email event so the TestEmailTransport registers the emails sent in the tests

**Comment by markstory** [comment]
> I am not saying that what we wanted to achieve is impossible, we did it. After realizing that vital parts of our code could not be tested with the existing tools. But the Cake testing tools of the emails are IMO a bit rusty and could be improved.

What do you think could be improved? Is it missing assertions, should we capture email in a different way? Would having better testing tools remove the need for the additional events you're proposing?

> I also agree that events can lead to unreadable code. But Cake is full of them, and it works really well: 

Yes events are pervasive in the framework, but we generally try to avoid adding new ones unless the other solutions come up short. I'm trying to see if there are other design solutions to your issue other than adding more events.

**Comment by pabloelcolombiano** [comment]
Thinking about it again, this might be worth doing a library, and might be a little too specific. Since there is no traction here, I will close the issue.
