### ISSUE TITLE
FormHelper support for Object value fields

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#16984]
### Description

In CrudViewHelper there is a way to map specific field type to formatting callbacks via `fieldFormatters` field:
https://github.com/FriendsOfCake/crud-view/blob/master/docs/_partials/fields/formatter-callable.rst

I use it to map [Money](https://github.com/moneyphp/money) objects to strings

I think core FormHelper should have similar functionality.
Currently in order to add support for new object type like Money i need to overload whole FormHelper.
I think it would be much cleaner to just pass some formatting callback in AppView.php to make FormHelper render MoneyType objects as `<input type="number" step="0.01">` with decimal value extracted from money object via logic provided in callback.

Since cakephp 5 adds support for [BackedEnum's](https://www.php.net/manual/en/language.enumerations.backed.php) with introduction of EnumType, this object to form input mapping could be also used by users to map those EnumType objects into `<select>` inputs with current value selected.

### CakePHP Version

5.0 with optional backport for 4.x

**Comment by asgraf** [comment]
Alternative approach instead of callbacks would be to implement new optional interface:

```php
interface FormInputTypeInteface
{
    public function formValue($value);
    public function defaultInputOptions($value, array $inputOptions = []): array;
}
```
with example hypotetical implementation for EnumType:
```php
class EnumType extends \Cake\Database\Type\BaseType implements FormInputTypeInteface
{
    public function formValue(BackedEnum $value): string|int
    {
        return $value->value;
    }

    public function defaultInputOptions(BackedEnum $value, array $inputOptions = []): array
    {
        $enumClass = $this->enumClass;
        $inputOptions['type'] = 'select';
        $inputOptions['options'] = collection($enumClass::cases())->reduce(
            static function (array $selectOptions, BackedEnum $case) {
                if (is_subclass_of($enumClass, DisplayNameInterface::class)) {
                    $name = $case->getDisplayName();
                } else {
                    $name = $case->name;
                }

                return [...$selectOptions, $case->value => $name];
            },
            []
        );

        return $inputOptions;
    }
```
And support for types with that interface inside FormHelper

**Comment by ADmad** [comment]
Custom form input types are already supported using [widgets](https://book.cakephp.org/4/en/views/helpers/form.html#adding-custom-widgets). So you can make a `MoneyWidget` and specify `'type' => 'money'` for the `FormHelper::control()` call.

**Comment by asgraf** [comment]
But you still have to type `'type' => 'money'` manually in every single money input in your entire app instead defining it globally once for a given database type.
When you are working with database with 90+ tables and you endup with hundreds of forms for those tables.
Manually typing `'type' => 'money'` in every single money input is just lot of unnessesary work.
That's why i'm currently extending FormHelper to do that.
What i mean is that there should be some cleaner native official way to map MoneyType to MoneyWidget, EnumType to EnumWidget, OtherCustomType to OtherCustomWidget.

And you have to take in to account that some types can have multiple subtypes:
```php
$schema->setColumnType('language', EnumType::from(SupportedLanguage::class));
$schema->setColumnType('currency', EnumType::from(SupportedCurrency::class));
$schema->setColumnType('usd_price', MoneyType::from(SupportedCurrency::US_Dollar));
$schema->setColumnType('eur_price', MoneyType::from(SupportedCurrency::Euro));
```

**Comment by ADmad** [comment]
> What i mean is that there should be some cleaner native official way to map MoneyType to MoneyWidget, EnumType to EnumWidget, OtherCustomType to OtherCustomWidget.

The FormHelper has `typeMap` config to map db types to form types.

https://github.com/cakephp/cakephp/blob/77fe71c2aecbc2611d6bd1108575eedd8bc02651/src/View/Helper/FormHelper.php#L68
