### ISSUE TITLE
leftJoinWith with aliases

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#16991]
### Description

Working with `leftJoinWith` all condition setted on associations in table class is respected. 
But when I would like use twice or more leftJoinWith on the same query, I can't set alias for each left join query.

I try describe more complex:
```
$this->belongsToMany('Options', [
     'foreignKey' => 'entity_id',
     'targetForeignKey' => 'option_id',
     'joinTable' => 'table_name',
]);
```
and query
```
....->find()
    ->leftJoinWith('Options', function ($b) {
        return $b->where(); // Additional conditons
    })
    ->leftJoinWith('Options', function ($b) {
        return $b->where() // Additional other conditions
    });
```
then generate just one LEFT JOIN query based on two above conditions array and conditions from table class

I would like to use some like this with alias (similary like `leftJoin()`):
```
....->find()
    ->leftJoinWith(['alias_1' => 'Options'], function ($b) {
        return $b->where(); // Additional conditons
    })
    ->leftJoinWith(['alias_2' => 'Options'], function ($b) {
        return $b->where() // Additional other conditions
    });
```
to generate two LEFT JOINS with aliases

Excepted query (aka pivot table):
```
SELECT the *, alias_1.field_name, alias_1.field_name
LEFT JOIN options AS alias_1 ON ...
LEFT JOIN options AS alias_2 ON ...
```

It's possible now with `leftJoin` but always still to remember to rewrite conditions based on association in table class.

### CakePHP Version

4.5, 5.0

**Comment by ajibarra** [comment]
How are we expecting this to work? leftJoinWith() expects an association to exist on the table so we could load the association on the fly using the original association conditions inside this method if user passes an array instead of string. It does not looks like a clean solution but I can't think about something else right now. 

You can always define the association yourself with the alias directly on the table.

Please let me know your thoughts so I can prepare a MR if needed.

**Comment by kicaj** [comment]
@ajibarra Maybe you're right, but solution with aliases still sounds good for me.

For this example I think will be better adding association before run query.

**Comment by ajibarra** [comment]
IMO it looks like a very particular use case and the framework already provides a way to do it so adding it at framework level would add some complexity that probably we don't actually need to deal with.

**Comment by ADmad** [comment]
For such use cases one such use `leftJoin()` which allows specifying the alias. I don't think we needs more ways to achieve the same.
