### ISSUE TITLE
urlwithprotocol used with allowEmpty

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/cakephp#16996]
### Description

```php
 $validator
            ->scalar('website')
            ->maxLength('website', 50)
            ->requirePresence('website', 'create')
            ->allowEmptyString('website')
            ->urlWithProtocol('website');
```

Not sure if this intended behavior but when use allowEmptyString with urlWithProtocol it will automatically add the http:// to the textbox, then it will not pass validation anymore. Maybe the validation should be a bit better and allow http:// to pass if allowemptystring is set?

### CakePHP Version

4.4

**Comment by tgoeminne** [comment]
->urlWithProtocol('website','Website needs url with protocol http:// or https://',function ($context) {
                   return $context['data']['website'] !== 'http://';
                })
I added the when like this so it also accepts http://, the validator seems to accept any protocol, but actually would like to limit it to http and https protocol.

**Comment by markstory** [comment]
> but when use allowEmptyString with urlWithProtocol it will automatically add the http:// to the textbox,

How is the `http://` being added to the text box? I don't think that CakePHP will do that on its own.

> the validator seems to accept any protocol

The validator accepts http, https, ftp, ftps, sftp, file, news and gopher. If you need a more limited set you'd need to use a custom validator like you're doing.

**Comment by tgoeminne** [comment]
The value was already in the database apparently

**Comment by ADmad** [comment]
There's nothing to fix here. Either remove the default value from the database or use a custom validator.
