### ISSUE TITLE
Mysql: Cannot convert value of type boolean to integer

### ISSUE THREAD

**Issue by oresch** [cakephp/cakephp#17003]
### Description

like #15185 where a tinyint field was making trouble I have a similar issue:

    object(Cake\ORM\Query) id:0 {
    '(help)' => 'This is a Query object, to get the results execute or iterate it.'
    'sql' => 'SELECT 1 AS existing FROM table_name TableName WHERE TableName.id = :c0 LIMIT 1' 
    'params' => [
      ':c0' => [
        'value' => true, 
        'type' => 'integer', 
        'placeholder' => 'c0',
      ],
    ] 

The error appears in `CORE/src/Database/Query.php` row 254 in execute().

In my query (or better in the post-request) I put in a "1" (int) and the cakephp is translating it into boolean. Therefore the query is not working. How can this be solved?

cakePHP v4.4.10
PHP 8.2.2
MySQL 8.0.32 on a ubuntu 20.0ß4.2 machine.

### CakePHP Version

4.4.10

### PHP Version

8.2.2

**Comment by othercorey** [comment]
Can you provide the table schema and example of how you're setting the int?

**Comment by oresch** [comment]
```sql
    CREATE TABLE `table_names` (
    `id` int NOT NULL AUTO_INCREMENT,
     `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'visible',
    `valid` tinyint(1) NOT NULL DEFAULT '1',
    `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

In a form, I put the value in and post it to the controller:
```php
<?= $this->Form->hidden('port_visibility_id', ['id' => 'port_visibility_id', 'value' => 1]) ?>
```
later in js I use this value

```php
<input type="hidden" name="<my_field_id>" id="<my_field_id>" value="  + $('#port_visibility_id').val() + ">
```

In the Debugkit console I can see also the value correctly assigned to my object.

**Comment by ADmad** [comment]
`tinyint(1)` columns are emulated as booleans as MySQL doesn't have a true boolean type, so you can only set value `0` or `1` for those fields.

So either change your column to `tinyint` or override the column type to `integer` using `$this->getSchema()->setColumnType('valid', 'integer');` in your table class' `initialize()` method.

**Comment by oresch** [comment]
Hi @ADmad 
this issue is **not** about the `valid` field, but the `ID` field. About the `tinyint` I know - here it shall be boolean

**Comment by ADmad** [comment]
Please show the table/query method call you  are calling and the stack trace.

**Comment by othercorey** [comment]
@oresch Can you show us where the `id` is set in a query?

**Comment by oresch** [comment]
Hi. I thnik, I will skip this issue. I don't know what happened, but Currently there's no further issue.
Sorry for bothering you all about this strange issue.

thanks
Oliver
