### ISSUE TITLE
Undefined variable $class in missing_controller.php

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#17008]
### Description

My tests fail after the update from 4.4.10 to 4.4.11

warning: 2 :: Undefined variable $class on line 24 of /app/vendor/cakephp/cakephp/templates/Error/missing_controller.php
Stack Trace:

include /app/vendor/cakephp/cakephp/templates/Error/missing_controller.php, line 24
Cake\View\View::_evaluate() /app/vendor/cakephp/cakephp/src/View/View.php, line 1220
Cake\View\View::_render() /app/vendor/cakephp/cakephp/src/View/View.php, line 1177
Cake\View\View::render() /app/vendor/cakephp/cakephp/src/View/View.php, line 808
Cake\Controller\Controller::render() /app/vendor/cakephp/cakephp/src/Controller/Controller.php, line 773

Warning can be reproduced on calling a non-existing route.

After some digging I found out that the variable name was changed in this commit
https://github.com/cakephp/cakephp/commit/4d0992832b784b043d3b3ae8be1e277ee8df05e2
But in https://github.com/cakephp/cakephp/blob/4.x/templates/Error/missing_controller.php the variable $class is still expected.

I can make a PR if you want.

### CakePHP Version

4.4.11

### PHP Version

8.2

**Comment by othercorey** [comment]
@ADmad This is from https://github.com/cakephp/cakephp/pull/16980

**Comment by ADmad** [comment]
Welps, seems I forgot to update the variable name in the template.

@mrothauer Though how does it make your app tests fail? Testing output of error page only meant for development when debug is on seems weird to me.

**Comment by othercorey** [comment]
My guess they're testing http code and have APP_DEBUG defined without realizing it.

**Comment by mrothauer** [comment]
> @mrothauer Though how does it make your app tests fail?

Thanks for the fix!

My tests fail because I wrote some integration tests that also call non-existing routes or routes that lead to an error page (eg. content with status flag 0). And within all tests I automatically check both error log and debug log for warnings / notices. To avoid caching I test with debug mode. That's why my tests failed.

> Testing output of error page only meant for development when debug is on seems weird to me.

Maybe a bit too much, I agree.

**Comment by ADmad** [comment]
@mrothauer Thank you for the info.
