### ISSUE TITLE
Issue with php 8.2 where str_replace can be given a bool|null, instead of a string|array.

### ISSUE THREAD

**Issue by fr3nch13** [cakephp/cakephp#17011]
### Description

on file `/src/View/StringTemplate.php:184` 
It's allowing a bool to be passed to str_replace:
`str_replace(): Argument #3 ($subject) must be of type array|string, bool given`

### CakePHP Version

4.4.10

### PHP Version

8.2

**Comment by dereuromark** [comment]
How is that possible?

    $template = $this->get($name);
    
Would normally only either return null or the string
That said, the (string) cast is indeed missing here, as if it was null, the following code you mention would indeed run with null as 3nd arg:

    $template = str_replace('%', '%%', $template);
    
or we need to put this into the else clause.

**Comment by fr3nch13** [comment]
I submitted a pull request for this issue.
When I run my applications phpunit, it passes for php 7.4, 8.0, 8.1, but it fails here for 8.2 and latest.

**Comment by fr3nch13** [comment]
> I submitted a pull request for this issue. When I run my applications phpunit, it passes for php 7.4, 8.0, 8.1, but it fails here for 8.2 and latest.

Sorry, it's actually failing for all PHP 8.x, only 7.4 is passing.
I need to track down how/where in my code am I allowing a bool to pass this far up.

**Comment by fr3nch13** [comment]
It also seems to only happen when I'm serving up json via the JsonView.

I tracked it down to some old code that I had written back in the 3.x days:
For the PaginatorHelper.
```
'nextDisabled' => false,
```

maybe this should instead maybe throw an exception?

Edit: Specifically, In my API, I serve up json with the paginator helper, and it includes the pagination links with the templates like so:
```
$templates = [
    'nextActive' => '{{url}}',
    'nextDisabled' => false,
    'prevActive' => '{{url}}',
    'prevDisabled' => false,
    'counterRange' => '{{start}} - {{end}} of {{count}}',
    'counterPages' => '{{page}} of {{pages}}',
    'first' => '{{url}}',
    'last' => '{{url}}',
    'number' => '{{url}}',
    'current' => '{{text}}',
    'ellipsis' => '&hellip;',
    'sort' => '{{url}}',
    'sortAsc' => '{{url}}',
    'sortDesc' => '{{url}}',
    'sortAscLocked' => '{{url}}',
    'sortDescLocked' => '{{url}}',
];
$this->Paginator->setTemplates($templates);
```

I do this, because I load, and use tables from DataTables:
[https://datatables.net/examples/data_sources/server_side](https://datatables.net/examples/data_sources/server_side)
[https://datatables.net/examples/server_side/object_data.html](https://datatables.net/examples/server_side/object_data.html)
But I also add the pagination information to the json so I'm not loading the whole dataset, only what's being viewed.

I tried to change from false to null, and still get an error; however, I think the null should still be acceptable. 
My current patch allows bool|null, and only formats when it's a string.

**Comment by fr3nch13** [comment]
An example of what it normally spits out:
```
{
    "paging": {
        "total": 1,
        "page": 1,
        "pageCount": 1,
        "start": 1,
        "end": 1,
        "hasPreviousPage": false,
        "hasNextPage": false,
        "sortDir": "asc",
        "sortKey": null,
        "urls": {
            "first": null,
            "last": null,
            "previous": "false",
            "next": "false",
            "current": "\/orgs\/user.json"
        }
    },
    "draw": 1,
    "recordsTotal": 1,
    "recordsFiltered": 1,
    "data":[
        {
            "id": 1,
            "name": "name"
        }
    ]
}
```

**Comment by markstory** [comment]
Seems like this is fixed by changes in #17013 and #17012

**Comment by fr3nch13** [comment]
@ADmad see my use above as an example.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/pull/17015 is an alternative here that keeps it closer to the code it was before.
