### ISSUE TITLE
conditions on belongsTo

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/cakephp#17017]
### Description

The conditions on belongsTo relation still can not make conditions based on its own data.

in ArticlesTable

```php
$this->belongsTo('Users', [
            'className' => 'Users',
            'foreignKey' => 'writer_id',
            'joinType' => 'INNER',
            'conditions' => ['Articles.type_id' => '1']
]);
$this->belongsTo('Admins', [
    'className' => 'Admins',
    'foreignKey' => 'writer_id',
    'joinType' => 'INNER',
    'conditions' => ['Articles.type_id' => '2'],
]);
```

SQLSTATE[42S22]: Column not found: 1054 Unknown column Articles.type_id

How to use the conditions in belongsTo on its own table?

### CakePHP Version

4.4

### PHP Version

8

**Comment by markstory** [comment]
What is the query you're having generated? `BelongsTo` associations should generate joins and be able to reference aliases.

**Comment by ajibarra** [comment]
@tgoeminne From your code I understand that Articles of type 1 are associated to Users through `writer_id` and Articles of type 2 with Admins through the same field but I would like to understand the use case you are trying to implement because it  looks like maybe the design is not correct.

Could you please describe the use case?

**Comment by tgoeminne** [comment]
the use case is irrelevant. I used users and admins as an example.

**Comment by ajibarra** [comment]
@tgoeminne it is relevant for sure since I don't see why you would use conditions on the same table to filter another table. It does not make sense.

**Comment by tgoeminne** [comment]
because writer_id can match in both tables

**Comment by tgoeminne** [comment]
anyhow i dont see why it shouldnt be possible to have conditions on its own table, this would be convenient in cases where there is polymorphic.

where one field can associate data from another table based onvthe value of another field. in this case type_id

**Comment by ADmad** [comment]
Without an example query to reproduce the error there's nothing that can be done here.
