### ISSUE TITLE
Loading local plugins with atypical namespace

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#17033]
### Description

Reproduce:
1. Run command `bin/cake bake plugin PluginA` with double "yes"
2. Write simplest "HelloCommand" in /plugins/PluginA/src/Command (like below)
3. Update all files of "PluginA" in /plugins directory from namespace `PluginA` to `NamespaceA\PluginA`
4. Update file "composer.json" in plugin directory to change autoloader/ps-4 namespaces path to `"NamespaceA\\PluginA\\"`
5. Update file "composer.json" in main directory of app like above
6. Run command `composer dumpautoload`
7. Run `bin/cake` and there is no `hello` command
8. Optionally run `bin/cake plugin load PluginA` and repeat point 7.

Solution:
In "Application.php" we should change:
 from `$this->addPlugin('PluginA');` 
 to `$this->addPlugin(\NamespaceA\PluginA\PluginAPlugin::class);`
and now `hello` command is available.

Question:
It is possible to add additional param "namespace" to command 
`bin/cake plugin load PluginA --namespace=NamespaceA\PluginA` 
to load plugins based on namespace path?

Additional question
Prepared `hello` command is listed under "NamespaceA/PluginA" as `hello` and available as `bin/cake hello`. For this example we don't need to add command in `console()` method to be available. 
Is running command described here (https://book.cakephp.org/4/en/plugins.html#commands) is correct? I mean `contact_manager.user`. 
Using `$commands->add()` is just like alias?

### CakePHP Version

4.4.11

**Comment by markstory** [comment]
>  It is possible to add additional param "namespace" to command

Yeah we could do that, I think having the `plugin` command tool figure it out automatically would be better. However, I don't know how we could do that as the namespace is arbitrary. Having a parameter to set the classname would be more explicit as this scenario is outside of the 'conventions' for plugins.

> Prepared hello command is listed under "NamespaceA/PluginA" as hello and available as bin/cake hello. For this example we don't need to add command in console() method to be available.
Is running command described here (https://book.cakephp.org/4/en/plugins.html#commands) is correct? 

Yes the docs are correct. If you don't want to use auto-discovery then you should use `$commands->add()` to choose the command names you want.

From the docs

> By default all shells and commands in the plugin are auto-discovered and added to the application’s command list. Plugin commands are prefixed with the plugin name. For example, the UserCommand provided by the ContactManager plugin would be registered as both contact_manager.user and user. The un-prefixed name will only be taken by a plugin if it is not used by the application, or another plugin.

The reason you're getting `hello` is that no application or core commands use `hello` so we don't need the plugin prefix to disambiguate the command name.

**Comment by dereuromark** [comment]
I agree that the tool should figure this out automatically. And it does so using

    bin/cake plugin load PluginA
    
So if you removed the addPlugin() part and re-ran it, it would have shown it working, correct?
If so, I guess we can close this as works for me, since you manually edited the namespace afterwards, and as such you also need to either manually adjust the addPlugin() call, or remove and re-run manually.

**Comment by dereuromark** [comment]
Currently plugin name used here is matching the namespace
See
https://github.com/ADmad/cakephp-social-auth#setup
and
https://github.com/ADmad/cakephp-social-auth/blob/master/composer.json#L15

I dont see any need to act here further.
