### ISSUE TITLE
Add implicit deprecation info to `__call()` in QueryTrait

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17046]
A community member in slack recently asked if it would be possible to add the `deprecated` bubble to e.g. [Query::map()](https://api.cakephp.org/4.4/class-Cake.ORM.Query.html#map()) since it currently throws this warning:

```
Calling `Cake\Datasource\ResultSetInterface` methods, such as `map()`, on queries is deprecated.
You must call `all()` first
```

This however is not represented via the [API Docs](https://api.cakephp.org/4.4/class-Cake.ORM.Query.html#map())

Implementing this may be a bit trickier though since its a `__call()` method on the [QueryTrait](https://github.com/cakephp/cakephp/blob/4.x/src/Datasource/QueryTrait.php#L539-L565) which itself is not marked as `deprecated`

Currently only `Cake\ORM\Query` uses that QueryTrait though. But this may also be present in other traits/classes as well which have a deprecation warning in `__call()` methods.

Wondering what @othercorey thinks about that.

**Comment by othercorey** [comment]
We would need some way to add a deprecation annotation to @method tags which is how that's generated.

**Comment by markstory** [comment]
Another option would be to add a `map()` method to ORM\Query and alias the trait method. That would give us a place to add the deprecation warnings. I can take care of adding those if you'd like.
