### ISSUE TITLE
CSRF middleware custom options are ignored.

### ISSUE THREAD

**Issue by michelgeny** [cakephp/cakephp#17043]
### Description

If you want to modify the options of the CSRF middleware based on a cookie you must modify the options of the middleware when adding it to the queue. For example:

```php
$middlewareQueue->add(new CsrfProtectionMiddleware(['httponly' => true, 'secure' => true, 'samesite' => 'Lax']));
```

You can see that the cookie sent to the browser retains the default options: 'httponly' false, 'secure' false, 'samesite' null. To ensure that custom options are not ignored, the `$_config` property must be declared in the CsrfProtectionMiddleware class as private instead of protected.

### CakePHP Version

4.4.11

### PHP Version

8.1.13

**Comment by markstory** [comment]
We've added a tests covering the behavior you're having an issue with and as far as we can tell the behavior is correct and that cookie attributes are correctly set. Did we miss something in reproducing your issue?

**Comment by michelgeny** [comment]
I don't know if this will help you; here is the code used in src/Application.php 👍 

```php
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
	$middlewareQueue
		->add(new ErrorHandlerMiddleware(Configure::read('Error')))
		->add(new AssetMiddleware([ 'cacheTime' => Configure::read('Asset.cacheTime'), ]))
		->add(new RoutingMiddleware($this)) ->add(new BodyParserMiddleware())
		->add(new CsrfProtectionMiddleware([ 'httponly' => true, 'secure' => true, 'samesite' => 'Lax', ]))
		->add(new CspMiddleware($this->csp)); return $middlewareQueue;
}
```

I'm working on Mac OS Monterey 12.6.3 with a local MAMP Pro server with Apache 2.4.54 and PHP 8.1.13.
My development is not blocked since I found the solution quoted in my first message.
In any case, thank you for your responsiveness and sincere congratulations for your framework, which I really appreciate.
