### ISSUE TITLE
Add a component from a subfolder

### ISSUE THREAD

**Issue by triopsi** [cakephp/cakephp#17066]
### Description

Hello,

as long as the application is small, you can put the component in the /src/Controller/Components folder. However, with 50+ components, the view there becomes a bit more difficult. It would be much nicer and clearer if you could store your own components in subfolders, e.g. **/src/Controller/Components/Pays** or in **/src/Controller/Components/Systems**.

It should be loaded via ` $this->loadComponent('Systems/Utils');` be possible to load the Utils component in the Systems subfolder.

Unfortunately, this is currently not possible.

- https://discourse.cakephp.org/t/add-a-component-from-a-subfolder/11042

### CakePHP Version

4.X

**Comment by ADmad** [comment]
Sub folders under components aren't going to be supported. You can use plugins to group your components instead.

Also 50+ components seems a bit much and as already suggested in your forum post reply, you should look into service classes or plain utility classes which you can place under any namespace / folder in your app.

**Comment by garas** [comment]
It is possible to load component from any namespace:

`$this->loadComponent('SystemsUtils', ['className' => 'App\Controller\Components\Systems\UtilsComponent']);`
