### ISSUE TITLE
validateUnique fail with null values

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17067]
### Description

```php
        $validator
            ->add('user_id', 'unique', [
                'rule' => ['validateUnique', ['scope' => ['country_id', 'city_id', 'dance_id']]],
                'provider' => 'table',
                'message' => 'This country/city/dance already exists for this user',
            ]);
```

user_id, country_id are not null, so always present/required
city_id and dance_id are optional (DEFAULT NULL).

I used to use empty strings or 0 in DB here back in the days for this exact issue.
But for other data integrity issues I did switch to using more NULL as defaults in the last years.

The null part of the DB now does not match the empty strings being passed if no value selected.
```
'user_id' => '1',
'country_id' => '2',
'city_id' => '',
'dance_id' => '',
```

So those never trigger, and you can add multiple rows where the optional fields are null, so e.g.

    user_id 1, country_id 2, rest null
    user_id 1, country_id 2, rest null
    user_id 1, country_id 2, rest null

etc

I had to write the following fix for now to workaround it, by setting the values from empty string to null:
```php
	public function validateUnique($value, array $options, ?array $context = null) {
		$data = $context['data'] ?? null;
		if ($data) {
			foreach ($data as $field => $value) {
				if (empty($options['scope']) || !in_array($field, $options['scope'], true)) {
					continue;
				}

				if ($value !== '') {
					continue;
				}

				$data[$field] = null;
			}
			$context['data'] = $data;
		}

		return parent::validateUnique($value, $options, $context);
	}
```

With this the nullable fields are also "counted" into the uniquess now.

Is this a proper fix we should add into the core?
And could we detect this maybe based on schema and if those are not DEFAULT NOT NULL (default `'0'` I guess) and in that case this fix would not be needed? Otherwise (like here) it is needed.

### CakePHP Version

4.4.11

### PHP Version

8.2

**Comment by ADmad** [comment]
Did you try using the [allowMultipleNulls](https://api.cakephp.org/4.4/class-Cake.ORM.Rule.IsUnique.html#__construct()) config?

**Comment by dereuromark** [comment]
That blows up hard with
```
Cake\ORM\Entity::get(): Argument #1 ($field) must be of type string, bool given
```
in
```php
// EntityTrait
if (!$onlyDirty \|\| $this->isDirty($field)) {
    $result[$field] = $this->get($field);
}
```

**Comment by ADmad** [comment]
Seems like a mistake in the method call, don't see how a boolean would end up for a field name.

**Comment by dereuromark** [comment]
Ah, so the config for allowMultipleNulls was probably set wrongly, with this now

    'rule' => ['validateUnique', ['scope' => ['country_id', 'city_id', 'dance_id'], 'allowMultipleNulls' => true]],
    
It would still behave the same broken way as before.
It would accept the duplications to be added.

This really is about normalizing the empty values to the DB default here before comparing.

Otherwise you force devs/users to never use `default null`, but always `not null, default empty string`, to ensure data integrity.

**Comment by ADmad** [comment]
The fact that you are using a validation rule instead of application rule might be the issue here. The marshaler would handle the conversion of empty strings to null for integer nullable columns, but since validation occurs on the request data and not the entity property values you have the problem at hand.

**Comment by dereuromark** [comment]
I cannot use Application rule since it wouldnt Show up with the other rules, the 2 step process is not user friendly, :/

**Comment by ADmad** [comment]
I guess then a custom validator as you have shown is the only solution.

**Comment by dereuromark** [comment]
I wonder if the conversion should happen before Marshal since the fields are here also already known?

**Comment by dereuromark** [comment]
We could check the fields for
```php
            $this->getSchema()->hasColumn($field) &&
            $this->getSchema()->getColumn($field)['null'] !== false &&
            $this->getSchema()->getColumn($field)['default'] === null
```
and in that case apply the empty string to null conversation right in that validation method?
This would yield the most correct results IMO, since in this case there could already be another value with null in DB.

**Comment by dereuromark** [comment]
Currently I am using this extension: https://github.com/dereuromark/cakephp-tools/blob/ed75342c438f25d15065c77f8172db9af069cbfd/src/Model/Table/Table.php#L74

If there is no further interest for core, this can probably be closed.
