### ISSUE TITLE
`Cake\Log\Log` is not a PSR-3 compatible provider

### ISSUE THREAD

**Issue by evansims** [cakephp/cakephp#17076]
### Description

👋 I noticed that CakePHP's Composer manifest was [recently updated](https://github.com/cakephp/cakephp/pull/17059) to identify it as being a provider a number of PSRs, including PSR-3 `psr/log-implementation`. Great to see! 👏

However, it doesn't appear [`Cake\Log\Log`](https://github.com/cakephp/cakephp/blob/4.x/src/Log/Log.php) is actually PSR-3 compatible at present. Although it has the correct methods, many of them are *static*, which is incompatible with [the standard](https://www.php-fig.org/psr/psr-3/#3-psrlogloggerinterface). The standard expects `log()`, `debug()`, `info()`, `notice()`, `warning()`, `error()`, `critical()`, `alert()` and `emergency()` to not be static.

As it is, a library that might consume `Cake\Log\Log` anticipating it speaks PSR-3 would throw exceptions due to the missing methods.

### CakePHP Version

4.4.12

### PHP Version

8.1

**Comment by ADmad** [comment]
It's the various engines(classes) under the `Cake\Log\Engine` namespace which are PSR-3 compatible and implement the `LoggerInterface`, not `Cake\Log\Log` itself.

**Comment by othercorey** [comment]
@evansims Did this resolve your issue?
