### ISSUE TITLE
ServerRequest::withAttribute('here', '/dummy') and ServerRequest::getAttribute('here') don't align

### ISSUE THREAD

**Issue by lazur5566** [cakephp/cakephp#17075]
### Description

sample code:
```php
use Cake\Http\ServerRequest;
 $req = (new ServerRequest())->withAttribute('here', '/dummy');

 print_r($req->getAttribute('here'));
```

I'm not sure if this is expected behavior though.

### CakePHP Version

4.4.0

**Comment by markstory** [comment]
> I'm not sure if this is expected behavior though.

Why are you modifying the request `here` attribute? The `here` request attribute is an oddball backwards compatibility alias for 'base path + application path'. While we could likely fix this issue I would like to know more about the use case you have.

**Comment by lazur5566** [comment]
I'm helping to migrate from cakephp3 to 4 and there's a function in codebase that's doing sort of 'clean' to the request
it's like:
```php
$controller->request->here = str_replace(["\r\n", "\r", "\n"], '', $controller->request->here); 
```
so the way I modify this line would be 
```php
$request = $request->withAttribute('here', str_replace(["\r\n", "\r", "\n"], '', $request->getAttribute('here')));
```
which would lead to unit test failure.

**Comment by lazur5566** [comment]
I looked into the code, guess I should use `getRequestTarget` and `withRequestTarget` instead?

**Comment by markstory** [comment]
> I looked into the code, guess I should use getRequestTarget and withRequestTarget instead?

Yes. This would be a way to get the compatibility you want.
