### ISSUE TITLE
Non intuitive name of `Cake\Validation\Validator->isArray()`

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#17072]
### Description

This method adds a rule but by its name I wouldn't have thought so. There's the method `isEmpty` in the same class that follows the semantics we're used to and returns true or false.

I guess `isArray()` should be changed to `array()` following the same naming conventions as decimal, integer and scalar types.

### CakePHP Version

4.4.11

**Comment by garas** [comment]
When this rule was added in https://github.com/cakephp/cakephp/pull/9057, `isArray` was used because it was impossible to use `array` as method name in PHP 5. 

Since PHP 7 it is possible to use `array` as method name, so it would be good to rename to use same naming conventions as other methods.

**Comment by ADmad** [comment]
We can add `Validator::array()` in `4.5` and deprecated `Validator::isArray()`
