### ISSUE TITLE
PaginatorHelper::generateUrlParams unexpected behavior 

### ISSUE THREAD

**Issue by lazur5566** [cakephp/cakephp#17086]
### Description

in cakephp3.6
```php
generateUrlParams(['page'=>2, '?'=>['a'=>1, 'b'=>'B']], null);
```
gives result: 
```
Array
(
    [page] => 2
    [?] => Array
        (
            [a] => 1
            [b] => B
        )
)
```
whereas in cakephp4.4

```php
generateUrlParams(['page'=>2, '?'=>['a'=>1, 'b'=>'B']], null, []);
```
gives result: 
```
Array
(
    [?] => Array
        (
            [a] => 1
            [b] => B
            [page] => 2
            [?] => Array
                (
                    [a] => 1
                    [b] => B
                )
        )
)
```

### CakePHP Version

4.4.0

### PHP Version

8.2

**Comment by markstory** [comment]
Yes the behavior of this method changed from 3.x to 4.x. We can't change it back without breaking compatibility again. You need to put the `?` into the `$url` parameter instead of the `options`.

**Comment by lazur5566** [comment]
you mean to call the function like this:?
```php
generateUrlParams(['page'=>2], null, ['?'=>['a'=>1, 'b'=>'B']]);
```
result doesn't seem right,
```php
Array
(
    [?] => Array
        (
            [a] => 1
            [b] => B
            [page] => 2
        )

)
```
thanks in advance

**Comment by markstory** [comment]
> result doesn't seem right,

Pagination changed quite a bit from 3 to 4. If you want `page` as a routing key, you need to use 

```php
$this->Paginator->setConfig('routePlaceholders', ['page']);
```

This will tell URL generation to put the page option into the URL parameters instead of as a query string key.

**Comment by lazur5566** [comment]
I figured that should be
```
$this->Paginator->setConfig('options.routePlaceholders', ['page']);
```

**Comment by lazur5566** [comment]
https://github.com/cakephp/cakephp/blob/3.x/src/Routing/Route/Route.php#L735
Here the `['page' => 2]` key value pair of `$url` will be extracted and put into `$query`
whereas in cakephp4.x it doesn't do that anymore (https://github.com/cakephp/cakephp/blob/4.x/src/Routing/Route/Route.php#L736)


which causes this line returning different result even `generateUrlParams` returns the same 
(https://github.com/cakephp/cakephp/blob/4.x/src/View/Helper/PaginatorHelper.php#L512) 
```php
$this->Url->build($this->generateUrlParams($options, $model, $url), $urlOptions);
```
i.e.
Cakephp3.x:
```php
/?a=1&amp;b=B&amp;page=2
```
Cakephp4.x: page=2 won't be in the query
```php
/?a=1&amp;b=B
```

**Comment by ADmad** [comment]
As already stated, the way query string params are handled is different in 3.x and 4.x. So continuing to compare them won't yield anything fruitful. Just update your code as per 4.x.

**Comment by dereuromark** [comment]
I wonder if the migration guide could offer some more guidance here for this specific topic

**Comment by lazur5566** [comment]
I tried to refer https://book.cakephp.org/4/en/views/helpers/paginator.html#generating-pagination-urls but it didn't provide much information, function arguments also not align with the code

**Comment by markstory** [comment]
> I tried to refer https://book.cakephp.org/4/en/views/helpers/paginator.html#generating-pagination-urls but it didn't provide much information, function arguments also not align with the code.

Oops that's our bad. I'll get the signatures updated in the docs.

It seems like you're trying to align the output of your URLs to something. Could you provide some more information on what you want the end result URLs to look like and perhaps we can help you generate the page/sort links you're looking to create.

**Comment by lazur5566** [comment]
I wanted to generate url with page as one of query param (```/?a=1&amp;b=B&amp;page=2```)
And I found 
```php
$this->Url->build($this->generateUrlParams(['page'=>2], null, ['?'=>['a'=>1, 'b'=>'B']]), $urlOptions);;
``` 
without setting 
```php
$this->Paginator->setConfig('options.routePlaceholders', ['page']);
```
would work
Thanks for your help!

**Comment by markstory** [comment]
It sounds like you got to the result you're looking for then.
