### ISSUE TITLE
Typemap ignored when using the iterator interface of a statement

### ISSUE THREAD

**Issue by UlrichEckhardt** [cakephp/cakephp#17104]
### Description

When making a query and using the statement as an iterator, the type map is ignored. When using `fetch()` or `fetchAll()`, the typemap is correctly applied.

The following is an excerpt from our code here:

```php
        $fields = [
            'status' => 'string',
            'comment' => 'string',
            'modified_ts' => 'datetime',
        ];
        $query = $this->connection->newQuery()
            ->from(self::TABLE)
            ->select(array_keys($fields))
            ->setSelectTypeMap(new TypeMap($fields))
            ->where(['docid' => $documentId], ['docid' => 'integer'])
            ->execute();

        $res = [];

        // This loop does not work:
        foreach ($query as $row) {
            $res[] = static::createRecordFromRow($row);
        }

        // This loop works:
        while ($row = $query->fetch('assoc')) {
            $res[] = static::createRecordFromRow($row);
        }

        return $res;
```

The issue this caused was that the `modified_ts` field was supplied as a string, not as a `DateTimeImmutable`, causing `TypeError` exceptions.

On a related note, when using the iterator there is no way to specify a `$type` (e.g. `'assoc'`) as there is for `fetch()` and `fetchAll()`, which would make a nice addition.

### CakePHP Version

4.4.12

### PHP Version

7.4.30

**Comment by ADmad** [comment]
This is expected as without fetching the records as associative arrays (where field/columns names are keys) it's not possible to know which values needs to be converted.

**Comment by ADmad** [comment]
> On a related note, when using the iterator there is no way to specify a $type (e.g. 'assoc') as there is for fetch() and fetchAll(), which would make a nice addition.

So why can't just call fetch()/fetchAll() of the statement instead of directly iterating over the statement instance?

**Comment by UlrichEckhardt** [comment]
It's not that I can't do that. It's that I would have expected it to be an equal alternative and it's non-obvious that it isn't one. That explanation, that without the `'assoc'` parameter it can't work makes sense though, but in that light I'd extend this bug even further: If you use `$stmt->fetch('num')`, the type map isn't applied either!

In any case, thanks for your feedback, @ADmad! At least I understand this a bit better now. Fixing this in a way that doesn't break existing expectations may be difficult or even impossible, so I'll live with it for now. Maybe that's something that could be fixed in a 5.x version.

**Comment by ADmad** [comment]
> If you use $stmt->fetch('num'), the type map isn't applied either!

Well it won't for the same reason. Without having the field names as keys it's just not possible to know which values needs to be converted.

> Maybe that's something that could be fixed in a 5.x version.

In 5.x the statement isn't iterable which avoid s issues/ambiguities like this. So just update your code to use fetch()/fetchAll() before iterating :)
