### ISSUE TITLE
Reverse routes are extremely slow on large sites

### ISSUE THREAD

**Issue by impronta48** [cakephp/cakephp#17113]
### Description

I've got a site with more than 15.000 routes.
Everytime we call a reverse-router (for example to get the translated url of that page), we wait up to 8 seconds.

We have created a little improvement in the function

Router::reverse()
in file /src/Routing/Router.php

```php
    public static function reverse($params, $full = false): string
    {
        // massimoi: add a fast cache here
        $h = md5(serialize($params));
        $cparams = Cache::read("rev-route-$h");
        
        if ($cparams === null) {
            $params = static::reverseToArray($params);
            Cache::write("rev-route-$h", $params);
        } else {
            $params = $cparams;
        }
        return static::url($params, $full);
    }
```

### CakePHP Version

4.x

### PHP Version

7.4

**Comment by ADmad** [comment]
How are you calling `Router::reverse()`? If you pass it the current request instance, `Router::reverseArray()` will use the current route stored as a request attribute (in 4.4.0+) and won't have to iterate through all the the connected routes to find the matching route, which is already quite efficient.

**Comment by impronta48** [comment]
I call it like this in several elements <?= Router::reverse($route) ?> in every page in order to get the url of the same node in a different language. (es: /articles/view/my-name (eng) --> /articles/view/13 --> articles/view/mio-nome (ita)
This is necessary for SEO.

With a large site this gets extremely un-efficient.
The cache will make the pageload from 8 seconds down to 0.1 second

**Comment by ADmad** [comment]
You didn't answer my question :)  Are you calling `Router::reverse()` with an array or request instance?

**Comment by impronta48** [comment]
I'm calling it like this 
```
$arr = $this->request->getAttribute('params');
unset($arr['lang']);
$route = array_merge(['lang' => $lang], $arr);
<?= Router::reverse($route) ?>

```

**Comment by ADmad** [comment]
Following code should give you the same result without the overhead:
```php
$url = Router::reverseToArray($this->request);
$url['lang'] = $lang;
<?= Router::url($url) ?>
```
