### ISSUE TITLE
4.next: Get string representation of route object

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17128]
### Description

Based on https://github.com/cakephp/cakephp/pull/17051 it would be nice if a user could easily be able to get the string representation of the current route via the request object.

So one can already easily get the connected route object from the request object via
```
$route = $this->request->getAttribute('route');
```

`$route` does have a `->getName()` method but this does not return the correct string which is usable with `Router::parseRoutePath()` which should be in the structure of 
```
[Plugin.][Prefix/]Controller::action/param1/param2/param3
```

`categories:index` instead of `Categories::index` or
`alfredprojects.projects:_action` instead of `AlfredProjects.Projects::view/123`

But as far as I can tell this is not easily doable (as can be seen by the 2nd example) for routes which are connected via e.g. `fallbacks()`.

### CakePHP Version

4.next aka 4.5

**Comment by markstory** [comment]
Do you frequently use the current request's route to make URLs? What other ways are you getting route objects?

> But as far as I can tell this is not easily doable (as can be seen by the 2nd example) for routes which are connected via e.g. fallbacks().

Could we make `parseRoutePath()` able to match `Categories::index` to the fallback route though? That route would have a template of `/{controller}/{action}`. If this is a valuable workflow we could make it work.

**Comment by LordSimal** [comment]
My current way of getting the string representation is to fetch all routes via `Router::routes();` and then iterate over them to build the correct string representations for all of them so I can use them in a dropdown like so

![image](https://user-images.githubusercontent.com/9105243/235591612-5c082f88-8962-4425-97cd-6d75e3400817.png)

The idea here would be to make it easier for my users to add new items to the menu themselves via just going to whatever page they want and then just say "Add current page to menu"

If this of course isn't such a widespread usecase that the whole framework userspace can benefit from it then this should be handled just on my side.

**Comment by LordSimal** [comment]
I'll handle that on my side.
