### ISSUE TITLE
TLS support for RedisEngine

### ISSUE THREAD

**Issue by Phally** [cakephp/cakephp#17130]
### Description

For 5.x I'd love to see TLS support for the Redis cache engine.

We're using Redis as cache (because Azure) for every project and in every project we have something like this included:

```php
namespace Redis\Cache\Engine;

class RedistlsEngine extends \Cake\Cache\Engine\RedisEngine
{
    protected $_defaultConfig = [
        'database' => 0,
        'duration' => 3600,
        'groups' => [],
        'password' => false,
        'persistent' => true,
        'port' => 6380,
        'prefix' => 'cake_',
        'probability' => 100,
        'host' => null,
        'server' => '127.0.0.1',
        'timeout' => 0,
        'unix_socket' => false,
        'scanCount' => 10,
        'tls' => true
    ];
    
    protected function _connect() : bool
    {
        if ($this->_config['tls'] === true) {
            $this->_config['server'] = 'tls://' . $this->_config['server'];
        }

        return parent::_connect();
    }

}
```

For a widely used framework I don't think this solution is the best. I can imagine use cases where you'll need to be able to add a CA certificate for example.

### CakePHP Version
5.0 with optional backport for 4.x

**Comment by garas** [comment]
TLS is already supported, just use `'server' => 'tls://127.0.0.1'`.

But to specify TLS context, `RedisEngine::_connect()‎` needs changes to allow set `others` parameter for [Redis::connect()](https://github.com/phpredis/phpredis#connect-open).

**Comment by Phally** [comment]
Yeah, that's what I'm doing in the example.

The problem is that you can't do that when using URL-based environment variables.

It would become something invalid like: 
```
redis://tls://127.0.0.1?password=....
``` 
instead of 

```
redis://127.0.0.1?tls=true&password=...
```

I could try to urlencode the `tls://` bit, but that's ugly if it even were to work like that.

**Comment by jamisonbryant** [comment]
Chiming in to say we also have to do loop-de-loops to accommodate Redis connection strings that may/may not require a `tls://` prefix (TLS is required in our cloud infrastructure, but not in our local dev environments).

Currently we're adding `tls://` to the environment variable `REDIS_HOST`, and using that to set PHP's `session.save_path` (in bootstrap.php). It will not work without this. 

But, we must REMOVE this prefix in our custom RedisEngine that is much like the one @Phally has. The Engine will not work _with_ the prefix present (the error is the infamous `php_network_getaddresses: getaddrinfo failed`)

**Comment by markstory** [comment]
Having an option sounds reasonable as it makes DSN connection strings easier to build. A pull request to `4.next` would be much appreciated.

**Comment by Phally** [comment]
Copy that, I got you. TLS default off for backward compatibility or on because it's TLS?

**Comment by ADmad** [comment]
In 5.x we can turn it on by default but off for 4.x backport.

**Comment by othercorey** [comment]
@markstory Is this something we could finish up?

**Comment by markstory** [comment]
Yeah I can take care of it.
