### ISSUE TITLE
Utility\Text.php  different type errors

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#17146]
### Description

Error: [TypeError] preg_replace(): Argument #2 ($replacement) must be of type array|string, int given in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Utility\Text.php on line 235

Stack Trace:
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Utility\Text.php:235
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:359
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\ErrorLogger.php:111
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\ErrorLogger.php:72
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:343
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:139
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:121
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\cakephp\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php:60
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:58
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Server.php:90

[TypeError] str_replace(): Argument #1 ($search) must be of type array|string, int given in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Utility\Text.php on line 244

Stack Trace:

- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Utility\Text.php:244
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:359
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\ErrorLogger.php:111
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\ErrorLogger.php:72
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:343
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:139
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:121
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\cakephp\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php:60
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Runner.php:58
- C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Http\Server.php:90

### CakePHP Version

4.0.10

### PHP Version

8.0.28

**Comment by LordSimal** [comment]
How can one reproduce this problem?

**Comment by Manuel1948** [comment]
In the src/Application.php I have the public function for Authentication:

public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface{

my returned variable at the end was a not existing one.

But maybe it is some complexity of our application which causes this error :(

**Comment by Manuel1948** [comment]
Maybe it has something to do with our ErrorHandler?

bootstrap:

// activate our error-handler for mail-messages on fatal errors
$errorHandler = new \App\Error\AppError();
$errorHandler->register();



`class AppError extends ErrorHandler {

    public function _displayError($error, $debug): void {
        parent::_displayError($error, $debug);
    }

    public function _displayException($exception): void {
        parent::_displayException($exception);
    }

    public function handleFatalError($code, $description, $file, $line): bool {
        if (!Configure::read('debug') and Configure::read('AdminSettings.alarmOnFatalError')) {  // send mail, if not in debug mode
            $cToMail = Configure::read('AdminSettings.TechAdminsMail');
            $aToMail = explode(',', $cToMail);
            $this->emailErrors([
                'code' => $code,
                'description' => $description,
                'file' => $file,
                'line' => $line
                    ], $aToMail);
        }
        return parent::handleFatalError($code, $description, $file, $line);
    }

    /**
     * Email fatal errors to the specified eMail address, but only up to one within a certain time period.
     * A temp file is created to determine whether to send an email. Only errors that haven't been sent via email are
     * stored there; The sent ones are deleted, so there's no need to periodically empty this file.
     *
     * @param array $errorData The error details.
     * @param string $recipient To which address the error email should be sent.
     * @param string $wait How much time has to pass for an identical message to be sent again.
     * @return boolean
     */
    private function emailErrors($errorData = [], $recipient = '', $wait = '1 hour') {
        //Open json file with the latest errors and read it
        $latestErrorsFile = new File(TMP . 'latest_errors.json');

        //Create array from the latest errors file
        $errors = json_decode($latestErrorsFile->read(), true);

        if (!$errors) {
            $errors = [];
        }

        //Append date and name to error data
        $now = new Time(null, 'Europe/Vienna');
        $errorData['date'] = $now->i18nFormat('yyyy-MM-dd HH:mm:ss');
        $errorData['error'] = $this->mapErrorCode($errorData['code'])[0];


        $cloneCount = 0; //Count how often the same error exists in latest errors file
        $send = true; //Whether to email this error

        foreach ($errors as $entry) { //Loop through all entries and count how often they occured
            $date = new Time($entry['date'], 'Europe/Vienna');

            if ($this->isIdenticalError($entry, $errorData)) { //If this error is identical to the newest error...
                if ($date->wasWithinLast($wait)) { //...and happened within the waiting period...
                    $send = false;
                    break; //...don't send the email and stop the loop.
                } else { //Otherwise add it to the count
                    $cloneCount++;
                }
            }
        }

        if ($send) { //Should the eMail be sent?
            foreach ($errors as $k => $entry) { //Loop through all entries and remove clones
                if ($this->isIdenticalError($entry, $errorData))
                    unset($errors[$k]);
            }

            //Prepare the email content
            $message = "\nYou have received this error $cloneCount time(s) within the last $wait.\n\n Debug information:\n\n";

            $message .= sprintf(
                    '%s (%s): %s in [%s, line %s]', $errorData['error'], $errorData['code'], $errorData['description'], $errorData['file'], $errorData['line']
            );

            $trace = Debugger::trace([
                        'start' => 1,
                        'format' => 'log'
            ]);

            $request = Router::getRequest();
            if ($request) {
                $message .= $this->_requestContext($request);
            }
            $message .= "\n\nTrace:\n" . $trace . "\n";

            //Email the error message
            $email = new Email('default');
            $result = $email->setTo($recipient)
                    ->setSubject('A fatal error occurred :: ' . $errorData['description'])
                    ->setEmailFormat('text')
                    ->send($message);
            if (Configure::read('EmailTransport.default.className', false) == 'Debug') {
                Log::debug($result, ['scope' => 'maildebug']);
            }
        }

        //Append it to the file
        $errors[] = (object) $errorData;

        //Write the new errors array to the json file
        $latestErrorsFile->write(json_encode(array_values($errors), JSON_PRETTY_PRINT));

        return $send;
    }

    private function isIdenticalError($a, $b = array()) {
        return
                $a['code'] === $b['code'] &&
                $a['description'] === $b['description'] &&
                $a['file'] === $b['file'] &&
                $a['line'] === $b['line'];
    }

}
`

**Comment by garas** [comment]
Before 4.1.2, `Text::insert()` used `crc32`, which gave integer hashes. Now it uses `md5` hashes which are strings https://github.com/cakephp/cakephp/pull/14829.

Those hashes are passed to `preg_replace()`/`str_replace()` as integers. That throws errors in PHP 8. 

Upgrade to at least CakePHP 4.2 as it was first version tested on PHP 8.0.

**Comment by markstory** [comment]
Closing as 4.2 is the minimum CakePHP version compatible with PHP 8.
