### ISSUE TITLE
Index.php with query params will fill path with query on the url object

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/cakephp#17158]
### Description

Why is when I call index.php?value=key direcly, the path param of URL-Object filled with query params? Because this constalation no fallback routes of the routesmiddleware will trigger no routes missing exception. The reason for fallback routes is all path begin with / . When called index.php with query params there no starting / of path is found. In the commit https://github.com/cakephp/cakephp/commit/dbc5d413cc341dd1af198d4f4cd2050ae2bd0a54#r24714579 is the reason for this problem.

### CakePHP Version

4.4.10

### PHP Version

8.0

**Comment by markstory** [comment]
From the commit you linked.

> This is to support webserver setups without URL rewriting.

I'm not really clear on what the problem is here.

> Because this constalation no fallback routes of the routesmiddleware will trigger no routes missing exception. The reason for fallback routes is all path begin with / . When called index.php with query params there no starting / of path is found.

Are you expecting an error page and not getting one? How would I go about reproducing the scenario you're observing locally?

**Comment by nicokaiser79** [comment]
When I call index.php with a query, all routes from routes.php and the fallback routes will be failed. The AuthMiddleware is also no longer called due to the MissingRouteException. Running through the ExceptionsRender and building the ErrorController then fails because the necessary Auth attributes are not present.  If no RewriteRules can be used on the server, is it possible to switch this behaviour on or off by configuration?

**Comment by markstory** [comment]
> Running through the ExceptionsRender and building the ErrorController then fails because the necessary Auth attributes are not present. 

Having your error handling require a logged in user/auth context is dangerous as that condition cannot always be met.

> If no RewriteRules can be used on the server, is it possible to switch this behaviour on or off by configuration?

No, there is no configuration options for this behavior, as 404 errors from unauthenticated users are something applications have to handle.

**Comment by nicokaiser79** [comment]
The User is all ready logged in in a verified session, when the user call the index.php with a query param, I want to show a normal error page. That is not possible when I want to startup in the ExceptionRenderer the ErrorController, because I need a the user object in the app controller. When the user is logged in, I need the user context on every page also on error page. I need that to show the cart of the current logged in user. 

if ($path === '/index.php' && $uri->getQuery()) {
            $path = $uri->getQuery();
} 
is that possible to configure this part above, or create a toggle in app.php

**Comment by markstory** [comment]
>  is that possible to configure this part above, or create a toggle in app.php

Why though? This would only fix one source of 404 errors. Wouldn't you have similar issues with other requests that don't have a valid route?
