### ISSUE TITLE
Cache with redis cannot run in the Jobs

### ISSUE THREAD

**Issue by DaveTang6** [cakephp/cakephp#17181]
### Description

Code like below:

```php
class GameLivesJob implements JobInterface
{
    public function execute(Message $message): ?string
    {
        // TODO: Implement execute() method.
        **Cache::write('testData', '123', 'redisYear'); //cannot run**
        return Processor::ACK;
    }
}
```

### CakePHP Version

4.4

### PHP Version

7.4.3

**Comment by markstory** [comment]
Why can't this code run? What error do you get?

**Comment by DaveTang6** [comment]
> Why can't this code run? What error do you get?
it does not write to Redis Cache, no any error I got, but it can write to File Cache

**Comment by markstory** [comment]
>  it does not write to Redis Cache, no any error I got, but it can write to File Cache

Is is possible that CakePHP cannot write to your redis instance? CakePHP doesn't connect to redis differently in command line mode or in a webserver context. If CakePHP cannot write to redis you should check that:

- The extension or client libraries are present.
- You are able to write to redis using a simple php script.
