### ISSUE TITLE
Add support to deal with more native php types in $query->newExpr()

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#17182]
### Description

If you try something like:

```php
$query->select([
            'number' =>  $query->newExpr([$query->func()->rand(), 10])->setConjunction('*')
        ])
```

You will have only this (in mysql):

```sql
SELECT
  (
    RAND()
  ) AS number
FROM
  test Test
```

To work as expected you need to "cast" 10 as string:

```php
$query->select([
            'number' =>  $query->newExpr([$query->func()->rand(), '10'])->setConjunction('*')
        ])
```

```sql
SELECT
  (
    (
      RAND() * 10
    )
  ) AS number
FROM
  test Test
```

### CakePHP Version

5.0

**Comment by markstory** [comment]
> To work as expected you need to "cast" 10 as string:

What kind of types are you looking to add support for?

**Comment by celsowm** [comment]
> > To work as expected you need to "cast" 10 as string:
> 
> What kind of types are you looking to add support for?

Hi Mark !

Besides **string**, how about **int** and **float** ?

I tried to think of an (useful) example using other types like **bool** or even **null** but couldn't do it :(

**Comment by markstory** [comment]
I think sticking to `int | float | string | Stringable` is a good choice. Including stringable will let userland custom types interact with this interface.

**Comment by celsowm** [comment]
> I think sticking to `int | float | string | Stringable` is a good choice. Including stringable will let userland custom types interact with this interface.

agreed !
