### ISSUE TITLE
4.x: Division by zero in ProgressHelper

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17195]
### Description

Bake a command via `bin/cake bake Test`

Just like the docs say in https://book.cakephp.org/4/en/console-commands/input-output.html#command-helpers add
```
$progress = $io->helper('Progress');
$progress->increment(10);
$progress->draw();
```

to the execute method and execute the command bin `bin/cake test`

This will result in the following error:
```
2023-07-27 09:51:38 error: [DivisionByZeroError] Division by zero in /myapp/vendor/cakephp/cakephp/src/Shell/Helper/ProgressHelper.php on line 134
Stack Trace:
- /myapp/src/Command/TestCommand.php:25
- /myapp/vendor/cakephp/cakephp/src/Console/BaseCommand.php:190
- /myapp/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /myapp/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /myapp/bin/cake.php:12
- [main]:

[DivisionByZeroError] Division by zero in /myapp/vendor/cakephp/cakephp/src/Shell/Helper/ProgressHelper.php on line 134
```

Should this be adjusted in the docs or is this actually a core issue?

### CakePHP Version

4.4.15

### PHP Version

8.2

**Comment by markstory** [comment]
We're missing a call to init() in the docs. However, we should also handle that operational error when render() is called.
