### ISSUE TITLE
Validator::equals() with strings

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#17199]
### Description

[`Validator::equals()`](https://github.com/cakephp/cakephp/blob/5.0.0-RC2/src/Validation/Validator.php#L1317) does not accept string for `$value`.

So calling `$validator->equals('fieldName', 'test', __('Invalid code.'))`, that was working in cake 4, now producing error.

If only numbers are allowed here, what is the proper replacement for equals? Should we allow strings here?

### CakePHP Version

5.0.0-RC2

### PHP Version

8.1

**Comment by andrii-pukhalevych** [comment]
Actually, [Validator::equals()](https://github.com/cakephp/cakephp/blob/5.0.0-RC2/src/Validation/Validator.php#L1317) uses comparison with `Validation::COMPARE_EQUAL` - not strict comparison.

It means that `$validator->equals('fieldName', 5)` will be passed for value `'005'`.
If we allow strings here, then `$validator->equals('fieldName', '005')` will be passed with `'5'`.

Its ok for numbers but not for strinigs.

**Comment by andrii-pukhalevych** [comment]
Should we rename `sameAs` to `sameAsField` to align with `equalToField`.

And make new `sameAs` that compares with some value using `Validation::COMPARE_SAME`?

**Comment by markstory** [comment]
The `Validation::equals()` method hasn't changed since 2019 are you sure this is new behavior? It seems like this bug/feature has been around for a while now.

**Comment by andrii-pukhalevych** [comment]
Parameter types were added in cake 5. Before it was just doc block with types

**Comment by markstory** [comment]
> Parameter types were added in cake 5. Before it was just doc block with types

Ok. Sounds like we need to relax types on `Validator`
