### ISSUE TITLE
Limit association table inside contain 

### ISSUE THREAD

**Issue by Dameen-Rainer** [cakephp/cakephp#17192]
### Description

I'd like to see this feature in v 5.0 if possible
Inside controller:

`'contain' => ['Articles' => ['limit' => 5]]`

**Comment by ADmad** [comment]
Implementing this for MySQL < 8 would be quite inefficient as it would require a separate query for every parent record.

The same problem doesn't exist for MySQL 8 and other dbs which support "window functions" and you can use this plugin https://github.com/icings/partitionable.

**Comment by LordSimal** [comment]
Also see https://stackoverflow.com/a/30270675
