### ISSUE TITLE
functional/expression-based indexes from MySQL 8.0 do not seem to be supported

### ISSUE THREAD

**Issue by mkuebler-infosec** [cakephp/cakephp#17201]
### Description

I'm not entirely sure if this should be a bug report or a feature request. I tried to broach this briefly on the Cake Slack channel but was told to file an issue with more detail.

The project I am working on uses Cake v4.3.11, PHP 8.1.13, and MySQL 8.0.31. The issue I am running into primarily involves the ORM's interaction with some of MySQL 8's more advanced features — particularly [functional indexes on expressions](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-functional-key-parts). I am filing this issue to figure out if this is even possible to do within Cake.

I have a table `items` that uses a MySQL JSON column `properties` which stores lots of different varying pieces of data within it. We want to create a specific index based on a part of the JSON data stored in this column.

This is possible within MySQL 8.0 — we can create a [generated virtual column](https://dev.mysql.com/doc/refman/8.0/en/create-table-secondary-indexes.html) that automatically changes the value of the index column to match whatever the values are from within the JSON field. I can create an index using a raw MySQL query within the migration and Cake handles this just fine.

An example migration command we might run on the existing `items` table would be:

```
$table = $this->table('items');
$this->query(
'ALTER TABLE items 
                ADD COLUMN 
                children_item_ids VARCHAR(400) GENERATED ALWAYS AS (
                    properties->>'$.children[*].id'
                ) VIRTUAL;'
);
$table->save();
```

This would create a column that would always maintain as a separate column all the children IDs extracted from the JSON column. The field would be a string like: `[3, 45, 687, 2]`.

The problem lies in the special type of index we want to create on the created virtual column — in order to get the query performance savings, we need to cast the index as an unsigned array. In MySQL 8, this is possible through creating [functional indexes on expressions](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-functional-key-parts) rather than on columns directly. 

In MySQL 8, we can create an index using the following:

```
CREATE INDEX children_item_ids_idx ON items ((CAST(children_item_ids AS UNSIGNED ARRAY)));
```

This generates the desired index that works with regular PHP running raw MySQL queries outside of Cake. (And boosts our query performance for that table significantly.)

However when I try to create this index within Cake I run into problems.

1) First of all, obviously Cake's addIndex() doesn't allow me to do this. That's perfectly understandable.

2) When I try to create this index in a migration using raw MySQL, I get the following error:

**Migration Code:**
```
$this->query('CREATE INDEX children_item_ids_idx ON items ((CAST(children_item_ids AS UNSIGNED ARRAY)))');
```

**Error:**

```
error: [Cake\Database\Exception\DatabaseException] Columns used in index "children_item_ids_idx" in table "items" must be added to the Table schema first. The column "" was not found. in /app/vendor/cakephp/cakephp/src/Database/Schema/TableSchema.php on line 495`
```

Even though this error happens, the index does get created in MySQL anyway. However, when I try to interact with the database in any way (select, load table, etc). I will get the same error now that this special index exists:
`error: [Cake\Database\Exception\DatabaseException] Columns used in index "children_item_ids_idx" in table "items" must be added to the Table schema first. The column "" was not found. in /app/vendor/cakephp/cakephp/src/Database/Schema/TableSchema.php on line 495`

This seems to be due to the fact that the index `children_item_ids` is not associated with a column, but rather the expression. Indeed, in MySQL when I run the following:
```
SHOW INDEXES FROM items;
```
The entry for `children_item_ids_idx` shows `Column_name` to be NULL. Instead, there is now an Expression column at the end which contains the value:

```
cast(`children_item_ids` as unsigned array)
```

When looking at the actual error in TableSchema.php, this is in the middle of the addIndex() function, which seems to be assuming indexes will always be associated with at least one column. In the case of functional indexes, this is not true.

In the end I guess my question is: does Cake plan to support MySQL 8's new functional indexes? Have I missed a feature of Cake that could deal with this? (Alternatively, is there a workaround to the problem I am describing?) I can go into more detail about the initial setup for the table if you need it.

### CakePHP Version

4.3.11

### PHP Version

8.1.13

**Comment by ndm2** [comment]
I'd say its a bit of both, a bug in the sense that it shouldn't cause a crash, and a feature request in terms of being supported as far as recognizing and managing those expression based indexes.

Since the internal index handling is just arbitrary attribute based, it should be fairly easy to safely ignore expression indexes as a quick bug fix, and in a possible next step, actively support them. Migrations might be a different beast, as it would probably first require support being added to Phinx.

As a quick and very dirty workaround you should be able to use a custom table schema class, compare against the indexes in the DB and ignore expression indexes accordingly.

```php
namespace App\Database\Schema;

use Cake\Database\Schema\TableSchema;
use Cake\Datasource\ConnectionManager;

class AppTableSchema extends TableSchema
{
    public function addIndex(string $name, $attrs)
    {
        if (empty($attrs['columns'])) {
            $stmt = ConnectionManager::get('default')->query('SHOW INDEXES FROM ' . $this->_table);
            foreach ($stmt->fetchAll('assoc') as $index) {
                if (
                    $index['Table'] === $this->_table &&
                    $index['Key_name'] === $name &&
                    $index['Expression'] !== null
                ) {
                    return $this;
                }
            }
        }

        return parent::addIndex($name, $attrs);
    }
}
```

In your connection config (where username, password etc for the connection is defined), set this like:

```php
'tableSchema' => \App\Database\Schema\AppTableSchema::class,
```

This is a very dirty workaround though, the schema querying stuff, that's a no-go. A cleaner workaround would be to implement a custom schema dialect to change where `addIndex()` is called, and pass the expression attribute too, which could then be evaluated in the custom schema. This would however require to completely reimplement `\Cake\Database\Schema\MysqlSchemaDialect::convertIndexDescription()`, and also a custom/extended driver in order to construct the custom dialect class.

**Comment by markstory** [comment]
I agree with @ndm2 here. Schema reflection shouldn't fail for expression based indexes, but it is unlikely that the ORM will support creating them via abstract schema generation as I don't see a way for indexes like this to be portable across DB vendors.

> I can go into more detail about the initial setup for the table if you need it.

It would be great to have a minimal schema to reproduce the issue you're having, as we can use it in fixing the issue and adding a regression test.

**Comment by ndm2** [comment]
> [...] it is unlikely that the ORM will support creating them via abstract schema generation as I don't see a way for indexes like this to be portable across DB vendors.

My thinking would've been that it should be possible to loosen the portability restrictions of the table schema, meaning expressions could be arbitrary config that would only be supported by the same dialect accordingly. That should be easy enough, but it would of course make a dent into the portability aspect. On the other hand, I think it's unreasonable for users to actually expect portability for such aspects of a schema in the first place.

I've run into problems with those schema restrictions myself before, I remember the last time it was something regarding collations+charsets, so I'm a bit biased. Being able to have dialect specific attributes would be nice, but I am aware that this would possibly open a very large barrel of worms.

**Comment by mkuebler-infosec** [comment]
Here is a schema migration setup that should work with the information given earlier:

```
$this->table('items', ['id' => false, 'primary_key' => ['id']])
	->addColumn('properties', 'json', ['null' => false]);
```

Sample simplified entry for properties's JSON data:
```
{
	"children": [
		{
			"id": 2,
			"type_id": 1000
		},
		{
			"id": 3,
			"type_id": 1000
		},
		{
			"id": 4,
			"type_id": 1001
		}
	]
}
```

I believe this should suffice -- what the ids actually represent aren't really important to the functional index part, as long as the generated index column `children_item_ids` would produce the result `[2, 3, 4]` in the above case. Let me know though if I need to flesh out other parts for this.
