### ISSUE TITLE
Wrong relative date / failed unit test on specific dates

### ISSUE THREAD

**Issue by fabian-mcfly** [cakephp/cakephp#17209]
### Description

https://github.com/cakephp/cakephp/blob/e28e6125405bcf447d5c7120b3af8f0f4f47feff/tests/TestCase/I18n/DateTest.php#L505-L507

This tests fails on "July, 31st", because `-5 months -2 days` results in "March, 1st" due to PHP's overflow behavior (here in `DateTimeImmutable`), as described here: https://www.php.net/manual/en/datetime.examples-arithmetic.php (Example 3).
Other tests will fail on other dates. The three tests above will fail every year on March, 31st, if the current is not a leap year.

While I don't expect Chronos to cover those edge-cases and work around PHPs implementation, the tests should not fail, I think.
Should the tests still fail on those days or should they get adjusted so that all `+/- day`-statements use at least 3 days of difference?

Mentioning this behavior in the Chronos Cookbook would also be helpful for those that encounter such problems in their implementation.

### CakePHP Version

4.4.15 / 5.x

### PHP Version

8.2

**Comment by LordSimal** [comment]
For reference: 
working CI run "yesterday": https://github.com/cakephp/cakephp/actions/runs/5708985799
failed CI run "today": https://github.com/cakephp/cakephp/actions/runs/5709084516

**Comment by othercorey** [comment]
We have a few tests that fail if run exactly on date/month change.
