### ISSUE TITLE
I get error when update to latest version 4.4.15

### ISSUE THREAD

**Issue by osama-kassar** [cakephp/cakephp#17205]
### Description

I tried to install Dompdf library ... but it force to update cakephp to latest version then I gt below error ... 

Deprecated: Use of `BaseErrorHandler` and subclasses are deprecated. Upgrade to the new `ErrorTrap` and `ExceptionTrap` subsystem. See https://book.cakephp.org/4/en/appendices/4-4-migration-guide.html C:\xampp\htdocs\ptpms\config\bootstrap.php, line: 129 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`. Adding `config/bootstrap.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` config will mute deprecations from that file only. in C:\xampp\htdocs\ptpms\vendor\cakephp\cakephp\src\Core\functions.php on line 328

Fatal error: Cannot use ::class with dynamic class name in C:\xampp\htdocs\ptpms\vendor\laminas\laminas-diactoros\src\Uri.php on line 229

any help please?

thanks in advance

### CakePHP Version

4.3

### PHP Version

8.1

**Comment by LordSimal** [comment]
You need to update your app to the new error handling system as explained here:
https://book.cakephp.org/4/en/appendices/4-4-migration-guide.html#errorhandler-consoleerrorhandler

You can also just compare your app files with what is currently present in https://github.com/cakephp/app and adjust the files (specifically for this error the `config/bootstrap.php`) to what is the current state.

**Comment by dereuromark** [comment]
You are not forced to update.
You can also just silence deprecations, see docs.

**Comment by LordSimal** [comment]
Also the error `Cannot use ::class with dynamic class name` indicates you are trying to run code meant for PHP 8.0+ but with 7.4 or lower. See https://php.watch/versions/8.0/class-constant-on-objects

So also make sure your CLI is on the same PHP version as your webserver/cakephp is running. Then composer will install the packages supported for that PHP version.

**Comment by LordSimal** [comment]
If you have any further questions lets continue this in the discourse support forum entry you just started:
https://discourse.cakephp.org/t/i-get-error-when-update-to-latest-version-4-4-15/11409

**Comment by osama-kassar** [comment]
> You need to update your app to the new error handling system as explained here: https://book.cakephp.org/4/en/appendices/4-4-migration-guide.html#errorhandler-consoleerrorhandler
> 
> You can also just compare your app files with what is currently present in https://github.com/cakephp/app and adjust the files (specifically for this error the `config/bootstrap.php`) to what is the current state.



Thanks, I will try it... I hope it works...  I did work around , by avoid updating ... I installed the dom/pdf library manually to not updating my framework ... but I think I need to solve for later too

**Comment by osama-kassar** [comment]
> You are not forced to update. You can also just silence deprecations, see docs.

I tried this ,, but its not worked

**Comment by osama-kassar** [comment]
> Also the error `Cannot use ::class with dynamic class name` indicates you are trying to run code meant for PHP 8.0+ but with 7.4 or lower. See https://php.watch/versions/8.0/class-constant-on-objects
> 
> So also make sure your CLI is on the same PHP version as your webserver/cakephp is running. Then composer will install the packages supported for that PHP version.

Oh ... its might be , because I have some old codes within my project...

Thanks a lot LordSimal , you're amazing!
