### ISSUE TITLE
Entity::getOriginal($field) returns a wrong value if $field was not set originally

### ISSUE THREAD

**Issue by fabian-mcfly** [cakephp/cakephp#17200]
### Description

Example:

```php
$comment = $this->Comments->get(1);
dump($comment->getOriginal('article'));
$this->Comments->loadInto($comment, ['Articles']);
dump($comment->getOriginal('article'));
```

This will return two different values, none of them is correct:

> \> `null`
> \> `App\Model\Entity\Article`

The reason for this that `getOriginal()` falls back to the `get`-method in case no original value exists (see L313)
https://github.com/cakephp/cakephp/blob/9fee4c83049a43babb32cf7a8fb01cf9c7b645af/src/Datasource/EntityTrait.php#L304-L314

The contain is just an example. Fetching a row from the database with a select of a subset of the table's fields, and then setting a field that wasn't selected, will produce in the same issue:

```php
$comment = $this->Comments->findById(1)->select(['id', 'text'])->first();
dump($comment->getOriginal('article_id'));
$comment->set('article_id', 2);
dump($comment->getOriginal('article_id'));
```

> \> `null`
> \> `2`

I mentioned this a few days ago on Discord and I will create a PR in the next days for this. @dereuromark suggested to introduce a new `hasOriginal`-method and make `getOriginal()` throw an exception in case one requests an unknown field.

My main questions:

1. What exception should `getOriginal()` throw in case no original value exists? RuntimeException, InvalidArgumentException?
2. Should I target 4.next or 5.x for this? Such a change will most certainly break a couple implementations.
 It will also affect `getOriginalValues()` and `extractOriginal()`

### CakePHP Version

4.4.15

### PHP Version

8.2

**Comment by fabian-mcfly** [comment]
And while I was looking at the EntityTrait, I asked myself if unseting the `$_original[$field]` when using `unset()` is correct. Shouldn't the entity always* return the original value, even if a field was unset?

https://github.com/cakephp/cakephp/blob/9fee4c83049a43babb32cf7a8fb01cf9c7b645af/src/Datasource/EntityTrait.php#L441-L449

*Clarification: always, until explicitly set do not dirty, or marked as clean (by saving it, or calling `clean()` manually).

**Comment by dereuromark** [comment]
Given that we cannot just change the API now that dramatically, `getOriginal()` should maybe not change even in 5.x.
Instead, if someone is interested to know whether `null` is now the original value or just default return of the method, one can use `hasOriginal()` to know this for sure.

As for unsetting: If a field doesnt count as touched (dirty) anymore, it should be fine to remove it from those values, as "original" is about the state after a change, which has now been revoked, thus no original value.
Otherwise all fields would have be always be duplicated in both normal property + original array.

**Comment by fabian-mcfly** [comment]
> Given that we cannot just change the API now that dramatically, `getOriginal()` should maybe not change even in 5.x.
> Instead, if someone is interested to know whether `null` is now the original value or just default return of the method, one can use `hasOriginal()` to know this for sure.

So just removing the fallback to `get()` and instead returning `null`!? I'm okay with that.

```php
public function getOriginal(string $field) 
 { 
     if ($field === '') { 
         throw new InvalidArgumentException('Cannot get an empty field'); 
     } 
     
     return $this->_original[$field] ?? null;
 } 
```


> As for unsetting: If a field doesnt count as touched (dirty) anymore, it should be fine to remove it from those values, as "original" is about the state after a change, which has now been revoked, thus no original value.

I will have to dig deeper but unsetting a field isn't the same as setting a field as not-dirty:

```php
$comment = $this->Comments->get(1);
dump($comment->getOriginal('article_id'));
$comment->unset('article_id');
dump($comment->getOriginal('article_id'));
$comment->set('article_id', 2);
dump($comment->getOriginal('article_id'));
```

> \> `1`
> \> `null`
> \> `2`

Imho saving an entity is the only way to set it to a new "original" state as a whole. `$table->save()` calls `clean()` on the entity, so that's a given.
Calling `setDirty('article_id')` could also remove the field from `$_original`, but calling `unset()` shouldn't.

**Comment by dereuromark** [comment]
> So just removing the fallback to get()

Well, ideally, maybe.
But given that this could introduce hard to find behavior changes, maybe we should leave the method as it is completely.

Thinking about it: Isn't `isDirty()` then exactly the method you need? Checking first if the value got changed at all, and then get the original value to compare your current value against?

**Comment by fabian-mcfly** [comment]
> Thinking about it: Isn't `isDirty()` then exactly the method you need? Checking first if the value got changed at all, and then **get the original value** to compare your current value against?

There are cases where exactly this can't be done:

```php
$comment = $this->Comments->findById(1)->select(['id', 'text'])->first();
$comment->set('article_id', 2);
dd($comment->getOriginalValues(), $comment->getDirty());
```

This will dump:

> \> `["article_id" => 2, "id" => 1, "text" => "Testcomment #1"]`
> \> `[0 => "article_id"]`

I now know that `article_id` is dirty but I will never find out whether "2" is the actual current value in the database, unless I fetch the record again. In my case, 1 is the original value in the db but `getOriginalValues()`/`getOriginal('article_id')` wrongly returns 2 while a more correct (or at least more helpful) result would be "i don't know, man, you're asking too much".

---

> unless I fetch the record again

I tried doing this now. I am in the `afterSave`-event of a model (more specific: an AuditBehavior), but I cannot fetch the original values from the database since this all happens inside a transaction. Moving the logic to `beforeSave()` makes that operation possible. I'd still prefer only doing this in case I can be certain that there are unknown original fields.

With the current behavior, I end up with log entries of records that have a wrong "old"-value.

**Comment by dereuromark** [comment]
I am not sure working with a "partially" filled entity will be a use case that can be supported here fully.
It sure looks like beforeSave() would have to be the place to check this in detail.

The null issue is still present even for such non fetched fields, is it not?
How would you know the DB entry was indeed null and not just null because it wasnt fetched?

**Comment by dereuromark** [comment]
I can understand the pain in regards to "original" value retainment, however.
For me the following also yields not the correct results for all actually changed values (so excluding the ones being set the same value again):
```php
$result = $entity->extractOriginalChanged($entity->getDirty());
```
My tests indicate that this does not work, though, with current behavior of code, due to that fallback.

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/cakephp/pull/17208 open
