### ISSUE TITLE
trait \Cake\Core\StaticConfigTrait

### ISSUE THREAD

**Issue by N1k0l4ss** [cakephp/cakephp#17212]
### Description

Forgot to allow bool and string for $config in \Cake\Core\StaticConfigTrait::setConfig()

### CakePHP Version

5

### PHP Version

8.1

**Comment by dereuromark** [comment]
Can u give some code examples please?

**Comment by N1k0l4ss** [comment]
```php
class StaticConfigTraitTest {

    use StaticConfigTrait;
}

StaticConfigTraitTest::setConfig('name', 'Foo');
StaticConfigTraitTest::setConfig('isEnabled', true);
```
bool and string values not allowed
