### ISSUE TITLE
[4.x & 5.x] Form::getError()

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#17219]
### Description

Just like the `EntityInterface`, the `Form` has a `getErrors()`method.

https://api.cakephp.org/4.4/interface-Cake.Datasource.EntityInterface.html#getErrors()
https://api.cakephp.org/4.4/class-Cake.Form.Form.html#getErrors()

But unlike  `EntityInterface`, the `Form` has no `getError(string $field)`method.

https://api.cakephp.org/4.4/interface-Cake.Datasource.EntityInterface.html#getError()
https://api.cakephp.org/4.4/class-Cake.Form.Form.html#getError()

Is there a particular reason for it lacking?
If not, I would propose (& volunteer) to add it.

One specific use case that came up for having it was the follwoing.

Instead of having a test case snippet like this:

```php
        $errors = $form->getErrors();
        $this->assertSame('Wrong password', $errors['password']);
```

One could simply do:

```php
        $this->assertSame('Wrong password', $form->getError('password'));
```

https://github.com/cakephp/form/blob/41da298aba74fc4f608b62f4af9248bab0c9222e/Form.php#L222-L233
https://github.com/cakephp/datasource/blob/cc101051e8d601cf6c2895d635ccefecca97ff4e/EntityInterface.php#L96-L109
https://github.com/cakephp/datasource/blob/cc101051e8d601cf6c2895d635ccefecca97ff4e/EntityTrait.php#L864-L898

### CakePHP Version

4.5

**Comment by dereuromark** [comment]
For forms it doesnt have to a "field", but maybe could also just be a "name" I would imagine.

**Comment by markstory** [comment]
Seems like a reasonable method to have on `Form`.

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/pull/17228
