### ISSUE TITLE
2.5 timezone() is deprecated. Use setTimezone() instead

### ISSUE THREAD

**Issue by GabrielLasso** [cakephp/cakephp#17223]
### Description

`i18nFormat` causes this error due to the following dependency
```
"cakephp/chronos": "^2.2"
```

It is getting chronos 2.4.0 when I compose install, which deprecates the timezone function

### CakePHP Version

4.4

**Comment by othercorey** [comment]
For a work-around, you can add a specific Chronos version to your compoer.json until we release a version that doesn't use the deprecated methods.
