### ISSUE TITLE
Allow return null for \Cake\Http\Cookie\CookieCollection::get() 

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#17222]
### Description

Can we allow return `null` for [`\Cake\Http\Cookie\CookieCollection::get()`](https://github.com/cakephp/cakephp/blob/80c89e0f07fad69d9a4887ffa2ee1905a2b0dd6e/src/Http/Cookie/CookieCollection.php#L146) without throwing exception `'Cookie ``%s`` not found. Use ``has()`` to check first for existence.'`?

To replace call `CookieCollection::has()` simple with checking result of `get()` for `null` every time cookie is needed?

Call `has` + `get` means double `foreach ($this->cookies as $cookie)`. Its speed issue + usage issue, because cookie name must be copied 2 times.

### CakePHP Version

5.0

**Comment by dereuromark** [comment]
There is not really a performance issue around cookie access, as those are accessed "few" times only per request, rendering any such loops rather nano-optimization at best.

get() is usually not nullable in return for consistency.
That said: I don't think it is too much to have the has() check prior to accessing it.
The benefit is that once retrieved it you know the value to be the one you are looking for.

**Comment by andrii-pukhalevych** [comment]
We are using it for website monitoring service, and in this case its not nano-optimization, its at least micro :)

Is it ok to add magic getter and use it, like it is done in `ObjectRegistry` registry? I did demo PR.

If not, please just close PR/issue to not spend more time
