### ISSUE TITLE
Extending layout content results in empty string

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#17232]
### Description

What i did:
I have created `templates/layout/default_main.php` with following content:
```php
$this->extend('default');
$this->prepend('content', '<main class="container content">');
$this->append('content', '</main>');
```

What i expected:
Same output as in `templates/layout/default.php` but with content wrapped with `main` html tag

What i got:
Same output as in `templates/layout/default.php` but content is replaced with empty string

### CakePHP Version

4.4.16

### PHP Version

8.1

**Comment by markstory** [comment]
Your extended layout doesn't emit any content. Have you tried adding `<?= $this->fetch('content') ?>` to the `default_main` layout?

**Comment by asgraf** [comment]
Thanks. Adding `echo $this->fetch('content');` fixed issue for me.
I think extending layouts examples should be included in documentation https://book.cakephp.org/4/en/views.html#extending-views
