### ISSUE TITLE
Class "Cake\Chronos\Date" not found

### ISSUE THREAD

**Issue by joanhey** [cakephp/cakephp#17257]
### Description

`Class "Cake\Chronos\Date" not found in /cakephp/vendor/cakephp/cakephp/src/I18n/FrozenDate.php:29`

In the last Techempower benchmark CakePHP fail to run.
With php-fpm, don't show any error but don't run.
With Workerman also fail, but show this error.

Info:
Bench build:
https://tfb-status.techempower.com/unzip/results.2023-08-30-17-02-33-292.zip/results/20230824091415/cakephp-workerman/build/cakephp-workerman.log
![image](https://github.com/cakephp/cakephp/assets/249085/e8fe3bd3-9755-4bf4-be10-9de348b59839)

Bench run:
https://tfb-status.techempower.com/unzip/results.2023-08-30-17-02-33-292.zip/results/20230824091415/cakephp-workerman/run/cakephp-workerman.log

Composer.json
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/cakephp/composer.json
Here you can check the rest of files, including the dockerfiles.

Looks like a problem from the Cakephp side, but any help will be apreciated.

Thank you.

### CakePHP Version

4.4.17

### PHP Version

8.2.9

**Comment by LordSimal** [comment]
The class directly does not exist any more since `2.4.0` but we made sure it still works the same as before via doing
https://github.com/cakephp/chronos/blob/2.x/src/Date.php#L15
and
https://github.com/cakephp/chronos/blob/2.x/src/ChronosDate.php#L288

But it seems in your specific case this fix does not work.

**Comment by joanhey** [comment]
The last run was using CakePHP v4.4.14  and Chronos 2.3.3, and worked without problems.

![image](https://github.com/cakephp/cakephp/assets/249085/0b4b0b82-615c-44c9-9650-ddf628944c2a)

And the test don't use any date or time related code.

**Comment by ndm2** [comment]
I don't remember the details, but IIRC `class_alias()` and [authoritative class maps](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps) can be problematic.

**Comment by LordSimal** [comment]
In the meantime you can try to add 
```
cakephp/chronos: 2.3.*,
```
as a dependency. Then it won't use the chronos 2.4 release which breaks your usecase.

**Comment by othercorey** [comment]
> I don't remember the details, but IIRC `class_alias()` and [authoritative class maps](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps) can be problematic.

This looks like the issue. I wouldn't call it a cakephp issue - more like a setting that's unlikely to work with large frameworks.

Since we call class_exists() in the old location, I'm not sure what else we can do here.

**Comment by LordSimal** [comment]
@othercorey could we do this instead of the `class_exists()` call?
```
if(!class_exists('\Cake\Chronos\Date')){
  require __DIR__ . DS . 'ChronosDate.php';
}
```

**Comment by othercorey** [comment]
We'd need more information on how the classmap is generated. We certainly won't do that for all aliases, this would just be a hack just for the path techempower's test code is taking.

**Comment by markusramsak** [comment]
@joanhey Does your issue still exist? If I remember right, then Chronos 2.4.0 was a little buggy but 2.4.1 fixed that. Therefore maybe try again to update your dependencies.

Maybe try
1) remove "vendor" folder
2) `php composer.phar update`
3) `php composer.phar dumpautoload -o`

`dumpautoload -o` generates the class list

**Comment by joanhey** [comment]
The same problem with Chronos 2.4.1.

![image](https://github.com/cakephp/cakephp/assets/249085/e784a94c-cad3-4467-a1f8-5fb6420a176a)

![image](https://github.com/cakephp/cakephp/assets/249085/498c4217-ef4f-49b2-a1ea-586291fc7c68)

For now the only solution is add:
`cakephp/chronos: 2.3.*,`
to the `composer.json`

**Comment by markusramsak** [comment]
I would like to test your project in my local machine. How can I do this? I tried to download the source code but it seems to be forbidden.

**Comment by joanhey** [comment]
You can use git to clone the benchmark, only need docker:
https://github.com/TechEmpower/FrameworkBenchmarks

Go to the main directory and run:
`./tfb --mode verify --test cakephp`
or  (than give you all the information)
`./tfb --mode verify --test cakephp-workerman`

**Comment by joanhey** [comment]
Remember that now we are using `cakephp/chronos: 2.3.*`. Only remove it in the `composer.json` in the `frameworks/PHP/cakephp` dir.

**Comment by joanhey** [comment]
I update almost all PHP frameworks in the benchmark, and usually I find problems before the maintainers in minor versions. I only update it for major frameworks version change.

Because the benchmark is run continuously.
I have created issues for Codeigniter, Symfony, .... for problems running or big performance regressions.

**Comment by joanhey** [comment]
And I need to say that CakePHP is faster each day.

![image](https://github.com/cakephp/cakephp/assets/249085/ac34008f-06d1-49f7-94cf-c3185fada493)

**Comment by markusramsak** [comment]
I installed it on my local machine with MAMP (Mysql, Apache, PHP 8.2.4) and it seems to work without any issues in this environment. Therefore I think that I could be a PHP configuration or composer or docker configuration problem.
How you tried a clean install by removing the "vendor" folder?

I tried the following 3 commands to trigger the error:
TypeFactory::build('date');
debug(new DateType('date'));
debug(new FrozenDate());

But everything works as expected.
Sometimes for me it is a simple cache issue ... maybe for you too.

**Comment by joanhey** [comment]
I don't delete the vendor folder.
We create a new docker image each time.
Please, check the dockerfile if we need an extra extension or anything abnormal.

But till now was working without problems.
Perhaps you have anything that change in your local environment, and it's working for that.

Like I said, go to the main directory and run:
`./tfb --mode verify --test cakephp`
or (than give you all the information)
`./tfb --mode verify --test cakephp-workerman`

That will create a docker image for Cakephp, that is completely isolated from your local. And for the database and test server. And it will run the tests automatically.

The build and test process for Cakephp with Adapterman  (because Cakephp normal don't show the errors but don't run also).

![image](https://github.com/cakephp/cakephp/assets/249085/d84af912-1834-4630-b7c8-0be23499c628)

**Comment by joanhey** [comment]
I checked your CI github action, to search any difference.

But I see that the CI is using Chronos 3.0.3
https://github.com/cakephp/cakephp/actions/runs/6386861328/job/17334265179#step:13:20

Also it is so in the `composer.json` for v5.x.
https://github.com/cakephp/cakephp/blob/5.x/composer.json#L29C37-L29C37

In v4.1.18 `"cakephp/chronos": "^2.2"` 
https://github.com/cakephp/cakephp/blob/4.4.18/composer.json#L29

But the CI GHaction for 4.1.18 is using kronos 2.4.1:
https://github.com/cakephp/cakephp/actions/runs/6386197652/job/17332423630#step:15:18
Without problems.

**Comment by joanhey** [comment]
The only difference that I see is that we don't install the `apcu`, `redis` and `memcached` extensions in our dockerfile
![image](https://github.com/cakephp/cakephp/assets/249085/10776a50-9949-4b83-a42b-7fcefe024572)

Well and that the CI test use another bootstrap (that is normal).

With `cakephp/chronos: 2.3.*` is working, with `2.4.x` it isn't working in our docker image.

**Comment by markusramsak** [comment]
CakePHP 4 should use Chronos 2 and CakePHP 5 should use Chronos 3. Is this the case and your project?

**Comment by joanhey** [comment]
Our docker image was working from 2017.

And actually still work with `cakephp/chronos: 2.3.*`, with `2.4.x` it isn't working in our docker image with CakePHP 4.1.18.

**Comment by joanhey** [comment]
Wait a moment, because I'm testing more, now normal Cakephp with debug and without log and it's working, but fail others things.

With debug = false, simply don't run, with chronos 2.4.x.
Give me some time to identify the problems.

And with Adapterman perhaps fail caused for any CLI SAPI check.

**Comment by joanhey** [comment]
The problem could be with the last update to CakePHP v4  , and fail when we use the database.
![image](https://github.com/cakephp/cakephp/assets/249085/a9745105-77fd-43d8-a57f-b6007b253cf1)

But possibly is with a fast update without all the files to CakePHP v4.

As I see that now you have v5 released, I'll update the benchmark to that version with a clean skeleton.
And also check v5 with Adapterman (that now it's slower only with cakephp).

As we'll update to v5, you can close this issue.

PD: I'll need some time to update to v5 for all the BC.

**Comment by ndm2** [comment]
@joanhey Try running `composer install` without `--classmap-authoritative` and see if it makes a difference with the new Chronos version.

**Comment by joanhey** [comment]
Updated the benchmark to CakePHP v5.
https://github.com/TechEmpower/FrameworkBenchmarks/pull/8472
If anybody want to review it !!

Later I'll send the results from v4.4 vs v5.
And check also with Adapterman if it's faster now.

@ndm2 yes I can change the branch and test without `--classmap-authoritative`.

**Comment by joanhey** [comment]
@ndm2 Yes !!!, without `--classmap-authoritative` it is working :tada: .

![image](https://github.com/cakephp/cakephp/assets/249085/9c4cc8b9-2dc4-4ee4-a820-6dd9f992f5f5)

![image](https://github.com/cakephp/cakephp/assets/249085/bbc714dd-ba8c-4d12-9744-b957eb31f1eb)

**Comment by joanhey** [comment]
I tested again with `--classmap-authoritative` and fail.

Here is the problem.

**Comment by markusramsak** [comment]
with classmap-authoritative the alias (which is not part of the class map) is not found
Cake\Chronos\Date is the alias of Cake\Chronos\ChronosDate in Chronos 2.4.1
and with classmap-authoritative only Cake\Chronos\ChronosDate (the real class) is in the autoload_classmap.php of composer.

There this issue can be solved with two solutions (if I am not mistaken):
1) By YOU allowing PHP Classloader to lookup the file Cake\Chronos\Date in the filesystem by NOT USING --classmap-authoritative 
2) By the CAKE CORE TEAM by using directly Cake\Chronos\ChronosDate instead of the alias Cake\Chronos\Date in Chronos 2.4.x (for instance in a patch release 2.4.2)

**Comment by joanhey** [comment]
The bench with CakePHP 5 is ready.

Framework | JSON | 1-query | 20-query | Fortunes | Updates | Plaintext
-- | -- | -- | -- | -- | -- | --
Cakephp 5.0.1 | 22,186 | 12,025 | 3,792 | 10,480 | 1,642 | 22,637
Cakephp 4.4.18| 26,255 | 13,308 | 3,920 | 11,419 | 1,689 | 27,101

The new version is a bit slower.
Adapterman is still slower than normal php-fpm, I'll create a issue about that.

**Comment by markstory** [comment]
Thank you for getting Cake 5 added to the techempower benchmarks :clap: We'll look into the performance issue and see if there are ways to improve.

**Comment by wojtekLs** [comment]
> https://github.com/cakephp/cakephp/issues/17257#issuecomment-1745307927

@joanhey True. This **is** a problem. For me also. But, as you stated somewhere near the start of this issue, its down to `composer` to fix it.

**Comment by dereuromark** [comment]
So we can close?
