### ISSUE TITLE
Show route specific middlewares in `bin/cake routes` command

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17253]
### Description

Would be cool to have an overview which route specific middlewares are being loaded inside the `bin/cake routes` command.

### CakePHP Version

5.0

**Comment by markstory** [comment]
Would that be in the main route listing, or in a new subcommand for getting additional details on a route?

**Comment by LordSimal** [comment]
The main route listing is already pretty loaded with data so either an argument like `bin/cake routes middlewares` or an option `bin/cake routes --with-middlewares` would suffice
