### ISSUE TITLE
5.x: Regression with named routes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17265]
### Description

A plugin uses
```php
$builder->setRouteClass(DashedRoute::class);
$builder->connect(
			'/edit/*',
			['controller' => 'Tags', 'action' => 'edit'],
			['_name' => 'Tags::edit'],
		);

		$request = ['_name' => 'Tags::edit'];
```
and
```php
$routes = Router::getRouteCollection()->named();
$defaults = $routes[$url['_name']]->defaults;
```
It now contains 
```php
[
  'controller' => 'tags',
  'action' => 'edit',
  'plugin' => null
]
```
But this used to be `Tags` and due to this change there is now breaking behavior that is unexpected.

So for some reason the lowercasing is happening where it should not, making comparison impossible.

### CakePHP Version

5.x

### PHP Version

8.1

----

See now failing tests https://github.com/dereuromark/cakephp-tinyauth/actions/runs/6136836223/job/16652063643

**Comment by LordSimal** [comment]
I have narrowed it down to this line being called
```
\Cake\Routing\Router::url(['_name' => 'Tags::edit']);
```
this results in the controller name being changed from uppercase to lowercase.
Digging deeper...

**Comment by LordSimal** [comment]
Its the `$url = $this->_dasherize($url);` call inside the DashedRoute.
```
array (
  'controller' => 'Tags',
  'action' => 'edit',
  'plugin' => NULL,
)
```
will turn into
```
array (
  'controller' => 'tags',
  'action' => 'edit',
  'plugin' => NULL,
)
```

**Comment by LordSimal** [comment]
Don't know if its expected that URL array's like shown above will also be dasherized if used with the DashedRoute class.

**Comment by markstory** [comment]
> Don't know if its expected that URL array's like shown above will also be dasherized if used with the DashedRoute class.

Routing historically has not used dashed controller/action names. We should continue to do reverse routing with camelcase / camelbacked names.

**Comment by dereuromark** [comment]
Does that mean that the expected named route for dashed routing would be

    ['_name' => 'tags::edit'],
    
in this case? To match the `'controller' => 'tags'` part?

**Comment by markstory** [comment]
> Does that mean that the expected named route for dashed routing would be

Ideally I think the name used to generate the route should be consistent with the one used to define the route. Ideally each route class normalizes names in the same way. I think `DashedRoute` is the odd one out here though.

**Comment by ADmad** [comment]
Last change for `DashedRoute` class was about 2 years ago, so I doubt there's a regression.

@dereuromark For you 2 failing tests you are actually missing `$builder->setRouteClass(DashedRoute::class);` statement after `$builder = Router::createRouteBuilder('/');`

**Comment by LordSimal** [comment]
@ADmad you mean exactly the 2 lines I removed in the linked PR above to fix the error?

**Comment by ADmad** [comment]
@LordSimal Ah, I didn't notice your comment, still as I said `DashedRoute` has been unchanged for 2 years and the dasherizing of route defaults inside `match()` exists since it's creation.

**Comment by ADmad** [comment]
That said I do have a solution to avoid inflecting the defaults while matching, will make a PR soon.

**Comment by LordSimal** [comment]
I was also pretty confused why this issue appeared here out of nowhere but in the end I do agree with your proposed solution.

**Comment by markstory** [comment]
I don't think there was a regression with `DashedRoute`, but that the behavior has always been broken. The following tests fails in `4.x` as well:

```php
        $routes = new RouteCollection();
        $builder = new RouteBuilder($routes, '/');
        $builder->setRouteClass(DashedRoute::class);
        $builder->connect('/tags/edit', ['controller' => 'Tags', 'action' => 'edit'], ['_name' => 'tags:edit']);
        // Without this line the test passes.
        $routes->match(['_name' => 'tags:edit'], []);

        $route = $routes->routes()[0];
        $this->assertSame('Tags', $route->defaults['controller']);
        $this->assertSame('edit', $route->defaults['action']);
```

Mutating the `defaults` based on whether or not the route has has match() called on it seems like the problematic behavior. I think ADmad's pull request is going in the right direction but we can't require developers to update their patterns, as the BC break could be large and would be hard to track down.

**Comment by dereuromark** [comment]
We could add New Route classes that would fix this?
Or I could just have them in Shim plugin as opt in for those that want it.
In the end it isnt a big Deal if we dont fix itcin core directly.

**Comment by markstory** [comment]
I think there is a solution we can provide within CakePHP. I'll try to get a pull request together later this week.
