### ISSUE TITLE
The `Example` alias has already been loaded. The `className` was not defined in the previous configuration data.

### ISSUE THREAD

**Issue by kolorafa** [cakephp/cakephp#17268]
### Description

```
The `Second` alias has already been loaded. The `className` was not defined in the previous configuration data.
CORE/src/Core/ObjectRegistry.php at line 160
```

Issue relate to loading custom Plugin View Helpers.

How to reproduce:
1. Create 2 custom helpers inside a plugin, first plugin needs to load and use the second one using the `Plugin.Helper` style Helper dependency.
2. Use use both plugins from Plugin Template without setting those plugins in Plugin View (so they will be loaded by the cake autoloader.

The issue is due miss match load logic between [HelperRegistry](https://github.com/cakephp/cakephp/blob/5.x/src/View/HelperRegistry.php#L78) and [Helper](https://github.com/cakephp/cakephp/blob/5.x/src/View/Helper.php#L108) or rather [ObjectRegistry](https://github.com/cakephp/cakephp/blob/5.x/src/Core/ObjectRegistry.php#L301)

Loading the Helper directly from View goes over normalization and in turn gets a generated config of ['enabled' => false, 'className' => 'PluginName']
While loading Helper thru Helper dependency goes thru HelperRegistry that is not setting the 'className' for plugin helpers.

`Helper dependency`:

```
class FirstHelper extends Helper
{
    /**
     * Other helpers used by FormHelper
     *
     * @var array
     */
    protected array $helpers = ['PluginName.Second'];
```

I think the fix would be to set className while doing a fallback into plugin in [HelperRegistry](https://github.com/cakephp/cakephp/blob/5.x/src/View/HelperRegistry.php#L78) by changing it from 
```
$this->load($plugin . '.' . $helper);
```
to
```
$this->load($helper, ['className' => $plugin . '.' . $helper]);
```

(Yes, I could initialize that helper in Plugin View and provide the className, but I would really like to still have the autoload function working, unless it's deprecated and could get removed in the near future)

This issue could also affect CakePHP 4.x (untested)

### CakePHP Version

5.0.0

### PHP Version

8.2

**Comment by markstory** [comment]
> Create 2 custom helpers inside a plugin, first plugin needs to load and use the second one using the Plugin.Helper style Helper dependency.

Does this issue only come up when you have two plugins, each with a helper, and the two helpers reference each other?

> Loading the Helper directly from View goes over normalization and in turn gets a generated config of ['enabled' => false, 'className' => 'PluginName']

How are you loading the helper? Are you use the `$this->MyHelper` style autoloading, or using `loadHelper()`?

**Comment by kolorafa** [comment]
In template:
$this->MySecondHelper->
$this->MyFirstHelper->

MyFirstHelper is loading the Second helper.

The issue is only showing when you load/use the Second helper both ways (from template and from First Helper)

Ofc, the issue only affects Helper inside a Plugin

**Comment by markstory** [comment]
I'll see if I can reproduce with the information provided.

**Comment by kolorafa** [comment]
@markstory Created a example project with this issue:

https://github.com/kolorafa/cakephp_issue_17268/blob/main/plugins/MyExample/templates/Simple/index.php

https://github.com/kolorafa/cakephp_issue_17268/tree/main/plugins/MyExample/src/View/Helper


![obraz](https://github.com/cakephp/cakephp/assets/921517/79eb445d-ad37-41df-ae8c-d939dc3ce295)
