### ISSUE TITLE
JsonView not serializing viewVars

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#17273]
### Description

While working on a simple REST example, following https://book.cakephp.org/5/en/development/rest.html#rest to generate json serialized output

Using this code

```
<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\View\JsonView;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 */
class UsersController extends AppController
{
    public function viewClasses(): array
    {
        return [JsonView::class];
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $query = $this->Users->find();
        $users = $this->paginate($query);

        $this->set(compact('users'));
        $this->viewBuilder()->setOption('serialize', ['users']);
    }
...
}
```

and

```
curl -H 'Accept: application/json' http://localhost:8765/users/index
{
    "users": {}
}% 
```

No data is serialized.

The same example, with the same database is producing the expected serialized data for the users records.

When tracing the data in JsonView class I see

vendor/cakephp/cakephp/src/View/JsonView.php:150 $data contents are a Cake\Datasource\Paging\PaginatedResultSet with non empty items.

### Expected Behavior

```
curl -H 'Accept: application/json' http://localhost:8765/users/index
{
    "users": {...serialized data for users in database...}
}% 
```

I've used CakePHP 5.0.0 but also checked the latest 5.x e227a2a95d291c393980b3be51957fb6b5d368db commit just in case it was already fixed

### CakePHP Version

5.0.0

### PHP Version

8.2.9

**Comment by ADmad** [comment]
You should get the expected results passing `$users->getItems()` as the view var.

We can make PaginatedInterface to be Json serializable too currently it's only Traversable. Though in that case I would expect the JSON to contain paging info too.

**Comment by markstory** [comment]
> We can make PaginatedInterface to be Json serializable too currently it's only Traversable. Though in that case I would expect the JSON to contain paging info too.

This will be a tripping point for folks upgrading, and even our default bake templates use code similar to what @steinkel is using. 
Having `PaginatedResultSet` json serialize without paging metadata seems like a good solution to me as user-land code doesn't have to change as much.
