### ISSUE TITLE
Dependencies issue when upgrading from 4 to 5

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#17270]
### Description

When upgrade is followed step by step, it fails with composer updating the packages:

> composer require --update-with-dependencies "cakephp/cakephp:5.0.*"

 

> Problem 1
>     - Root composer.json requires cakephp/cakephp 5.0.*, found cakephp/cakephp[5.0.0] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - cakephp/bake is locked to version 2.9.3 and an update of this package was not requested.
>     - cakephp/bake 2.9.3 requires cakephp/cakephp ^4.3.0 -> found cakephp/cakephp[4.3.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.*).
>   Problem 3
>     - cakephp/debug_kit is locked to version 4.9.4 and an update of this package was not requested.
>     - cakephp/debug_kit 4.9.4 requires cakephp/cakephp ^4.4.0 -> found cakephp/cakephp[4.4.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.*).

### CakePHP Version

5.0.0

### PHP Version

8.1

**Comment by dereuromark** [comment]
Did you also try `--update-with-all-dependencies`?
As for the specific other libraries/plugins, you might also want to include them into the statement

**Comment by nitramxx** [comment]
Yes. Important to notice, I am on the latest CakePHP 4, which is not 4.5, but 4.4.17.

> composer require --update-with-all-dependencies "cakephp/cakephp:5.0.*"

> ./composer.json has been updated
> Running composer update cakephp/cakephp --with-all-dependencies
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires cakephp/cakephp 5.0.*, found cakephp/cakephp[5.0.0] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - cakephp/bake is locked to version 2.9.3 and an update of this package was not requested.
>     - cakephp/bake 2.9.3 requires cakephp/cakephp ^4.3.0 -> found cakephp/cakephp[4.3.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.*).
>   Problem 3
>     - cakephp/debug_kit is locked to version 4.9.4 and an update of this package was not requested.
>     - cakephp/debug_kit 4.9.4 requires cakephp/cakephp ^4.4.0 -> found cakephp/cakephp[4.4.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.*).

**Comment by othercorey** [comment]
Do you have any of the other cake packages in your composer.json?

**Comment by nitramxx** [comment]
It's brand new app made from app skeleton literally last week. 

 This is after running `composer require --dev --update-with-dependencies "phpunit/phpunit:^10.1"`


```
"require": {
        "php": ">=7.4",
        "cakephp/cakephp": "4.4.*",
        "cakephp/migrations": "^3.2",
        "cakephp/plugin-installer": "^1.3",
        "mobiledetect/mobiledetectlib": "^2.8"
    },
    "require-dev": {
        "cakephp/bake": "^2.6",
        "cakephp/cakephp-codesniffer": "^4.5",
        "cakephp/debug_kit": "^4.5",
        "josegonzalez/dotenv": "^3.2",
        "phpunit/phpunit": "^10.1"
    }, 
```

**Comment by LordSimal** [comment]
you also need to update all the other packages which were previously cakephp 4 only.
So
```
"require": {
        "php": ">=8.1",
        "cakephp/cakephp": "5.0.*",
        "cakephp/migrations": "^4.0",
        "cakephp/plugin-installer": "^2.0",
        "mobiledetect/mobiledetectlib": "^3.74"
    },
    "require-dev": {
        "cakephp/bake": "^3.0",
        "cakephp/cakephp-codesniffer": "^5.0",
        "cakephp/debug_kit": "^5.0",
        "josegonzalez/dotenv": "^4.0",
        "phpunit/phpunit": "^10.1"
    }, 
```
You could also look at the composer.json of [cakephp/app](https://github.com/cakephp/app/blob/5.x/composer.json#L7-L20)

After you have adjusted your composer.json then do a `composer update -W`

**Comment by nitramxx** [comment]
Sure. I think you see my point, right? I was following the [upgrade guide](https://book.cakephp.org/5/en/appendices/5-0-upgrade-guide.html), there is nothing like "manually edit composer.json"

**Comment by ADmad** [comment]
You seems to have missed the last part of the upgrade guide:

> Update app files based upon latest app template
> Next, ensure your application has been updated to be based upon the latest version of [cakephp/app](https://github.com/cakephp/app/blob/5.x/).

You created your project a week ago when 4.x was still the default and 5.x hadn't been released yet.

**Comment by nitramxx** [comment]
Ok… if you guys think that the migration guide is clear, incl how to update dependencies, and the migration scripts work as intended, don’t feel like you need to change anything.

I just suspect there won’t be many successful migrations.

**Comment by LordSimal** [comment]
I understand what you mean. It ain't a step by step migration formula which you can apply and have no errors.
But the problem with dependencies like that is the simple fact, that we can't know which dependencies you are using in your app and therefore can't prepare you for which packages you must update and which you can leave as it is.

That's the job of composer and its output to give you the information you need to fix the dependency problems, not ours.
Like in your example it specifically said:
```
Problem 2
- cakephp/bake 2.9.3 requires cakephp/cakephp ^4.3.0 -> found cakephp/cakephp[4.3.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.).
Problem 3
- cakephp/debug_kit 4.9.4 requires cakephp/cakephp ^4.4.0 -> found cakephp/cakephp[4.4.0, ..., 4.4.17] but it conflicts with your root composer.json require (5.0.*).
```
so it should have lead to you thinking about adjusting these version strings in your composer.json

Both these plugins are NOT required to run CakePHP, therefore we can't just add them by default to the upgrade guide (even if they are installed by default in the app template)

If you have something specific in mind how we could adjust the upgrade doc so its clearer please provide a PR.

**Comment by markstory** [comment]
> If you have something specific in mind how we could adjust the upgrade doc so its clearer please provide a PR.

We could give instructions like 'also remember to update your cakephp plugins'. We could give an example of how to update cakephp and a few plugins that we provide.

**Comment by othercorey** [comment]
Closing this with the documentation update resolution.
