### ISSUE TITLE
Method Cake\Database\Connection::enableQueryLogging() vanished without migration docs

### ISSUE THREAD

**Issue by BGehrels** [cakephp/cakephp#17278]
### Description

When i'm trying to upgrade to CakePHP 5, i get the following error in my App:

> Call to undefined method Cake\Database\Connection::enableQueryLogging()

It seems like the Query Logging has been removed from the Connection class. Sadly, this information (and ideas what to use instead) is missing in the migration documentation.

### CakePHP Version

5.0.0

### PHP Version

8.2

**Comment by markstory** [comment]
> It seems like the Query Logging has been removed from the Connection class.

Query logging is still available. The methods to turn it on and off at runtime have changed though. I'll get the migration guide updated for this as the required changes are not outlined.

**Comment by othercorey** [comment]
Resolved in migration docs.
