### ISSUE TITLE
ConsoleIntegrationTestTrait is missing in 5.0

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#17287]
### Description

I can no longer find ConsoleIntegrationTestTrait - was it planned to be removed in 5.0 ? Not mentioned in the Migration Guide.

### CakePHP Version

5.0.0

### PHP Version

8.2

**Comment by LordSimal** [comment]
It wasn't removed, it was just moved to [\Cake\Console\TestSuite\ConsoleIntegrationTestTrait](https://github.com/cakephp/cakephp/blob/5.x/src/Console/TestSuite/ConsoleIntegrationTestTrait.php)

You should have updated to CakePHP 4.4 and removed all its deprecations before going to 5.0
See https://book.cakephp.org/4/en/appendices/4-4-migration-guide.html#testsuite

**Comment by ADmad** [comment]
> I can no longer find ConsoleIntegrationTestTrait

Any decent editor/IDE these days has fuzzy search which would reveal the exact location by typing just part of the classname :)

**Comment by swiffer** [comment]
:/ sorry!

**Comment by ADmad** [comment]
No worries.
