### ISSUE TITLE
Fallback to non plugin/prefix route if it doesn't exist in current context

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17294]
### Description

Lets image you develop a private plugin in `plugins/MyDeploy`.
Inside this plugin you have the usual suspects of models, controllers and templates as well as a plugin based route like so
```
public function routes(RouteBuilder $routes): void
{
    $routes->plugin('MyDeploy', ['path' => '/deploy'], function (RouteBuilder $builder): void {
        // Add custom routes here

        $builder->fallbacks();
    });
    parent::routes($routes);
}
```

With that out of the way if you then open a index table for the deployments which has a URL like that: http://localhost/deploy/deployments you can always get "plugin relative" URL's inside your template like this
```
$this->Html->link($deployment->deployment_type->name, [
      'controller' => 'DeploymentTypes',
      'action' => 'edit',
      $deployment->deployment_type->id
])
```
This works and doesn't require a `'plugin' => 'MyDeploy'` config inside the `$this->Html->link()` call because we are "relative" to the `MyDeploy` plugin template.

BUT if you want to reference an app entity like so
```
$this->Html->link($deployment->deployment_type->name, [
      'controller' => 'MyAppController', // <== Controller inside the base app, not the plugin
      'action' => 'edit',
      $deployment->my_app_assoc->id
])
```
This does not error but instead generated a faulty URL
http://localhost/deploy/my-app-controller/edit/1234

but instead it should fallback to
http://localhost/my-app-controller/edit/1234

the first url doesn't exist (and Cake should know from the Route Collection as far as I can tell - maybe I am wrong)

So in the end what I would like to have is a graceful fallback to `'plugin' => false` if the given link config is not possible.

Same should be done for prefixed routes.

I just don't like adding so many `'plugin' => false` and `'prefix' => false` to all my private plugins whenever I reference a base app model

### CakePHP Version

5.0

**Comment by dereuromark** [comment]
Some could consider this a bit too much fallback magic.
But if it is indeed not possible (route wise), I think this could make sense.

I so far just used a helper method ( https://github.com/dereuromark/cakephp-tools/blob/378dd5cbd3ff1419fe0423302d549e2e9832d4fa/src/View/Helper/HtmlTrait.php#L47 ) so far.
A specific logic here could make peoples lives easier.

**Comment by LordSimal** [comment]
That would be the current "quickfix" for my current problem but I would also consider throwing an exception if a route array config is given which cannot exist.
Then this problem would be easier to catch and fix instead of having faulty URL's being printed to the template.

**Comment by markstory** [comment]
How would Router know that your generated URL is invalid? It matches the fallback routes you defined with

```php
    $routes->plugin('MyDeploy', ['path' => '/deploy'], function (RouteBuilder $builder): void {
        // Add custom routes here

        $builder->fallbacks();
    });
```

That `fallbacks()` call is the likely culprit of why you're getting a plugin relative URL and not an application one.

**Comment by ADmad** [comment]
No routing system checks for the actual existence of the controller/action. It works based on the URL patterns you set.

You are essentially creating routes to non existent controllers by using `fallbacks()` since it sets routes with pretty generic patterns. So don't use fallbacks if you don't want the router to create URLs to non existent controllers.

**Comment by LordSimal** [comment]
Indeed, removing the `$builder->fallbacks();` call will result in an exception...
Seems like I just have to explicitly add routes for each controller like so
```
$builder->connect('/deployments', ['controller' => 'Deployments', 'action' => 'index']);
$builder->connect('/deployments/{action}/*', ['controller' => 'Deployments']);
```

Maybe we should add a warning about this to the [docs](https://book.cakephp.org/4/en/development/routing.html#fallbacks-method)
