### ISSUE TITLE
5.x: env() fatal error with array

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17307]
### Description

> PHP Fatal error:  Uncaught TypeError: Cake\Core\env(): Return value must be of type string|int|float|bool|null, array returned in /var/www/dereuromark/sandbox5/vendor/cakephp/cakephp/src/Core/functions.php:220
Stack trace:
#0 /var/www/dereuromark/sandbox5/vendor/cakephp/cakephp/src/Core/functions_global.php(140): Cake\Core\env()
#1 /var/www/dereuromark/sandbox5/vendor/dereuromark/cakephp-databaselog/src/Model/Table/DatabaseLogsTable.php(139): env()

The code was upgraded from 4.x:

    (array)env('argv')
    
We could now say we dont support array env() return values anymore.
But then we should probably document this in the migration guide.

### CakePHP Version

5.x

### PHP Version

8.1

**Comment by LordSimal** [comment]
What kind of use case would `(array)env('argv')` be used in?

**Comment by dereuromark** [comment]
CLI part, instead of `(array)($_SERVER['argv'] ?? null)` etc

**Comment by LordSimal** [comment]
the return type is already quite broad so I wouldn't mind extending it with `array`

**Comment by dereuromark** [comment]
I am fine either way.
