### ISSUE TITLE
Collection::combine fail when target v

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#17315]
### Description

When using the combine method with a source data has null values for the target key, the result array incorrectly populate the value.

For this issue, lets use a simple array:

```php
 $data = [
      [
          'status' => 1,
          'price' => 10,
      ],
      [
          'status' => null,
          'price' => 20,
      ],
  ];
  debug(\collection($data)
      ->combine('status', 'price')
      ->toArray()
  );
``` 

This results :
```
[
    (int) 1 => (int) 20,
]
```

The value for key 1 should be 10 not 20. Additionally If the method does not supports null value I would expects to get an exception or warning. 

### CakePHP Version

4.4.8

### PHP Version

8.1.14

**Comment by ADmad** [comment]
Since `null` isn't allowed as array key, an exception would be suitable in this case.

**Comment by othercorey** [comment]
> Since `null` isn't allowed as array key, an exception would be suitable in this case.

Technically it is converted to `""`. We've added exceptions on null values used as keys for `groupBy()` and `indexBy()` so this makes sense.

Users have to manually support `null` with a closure.
