### ISSUE TITLE
Tree Helper 

### ISSUE THREAD

**Issue by Dameen-Rainer** [cakephp/cakephp#17316]
### Description

Is there any chance of having a 'Tree Helper' to render the hierarchical data generated by 'Tree Behavior (threaded)' in the view/template part?

I think that kind of data is common and many projects might need to implement it like Comments For articles or products or whatever, so having a core tree helper in the view vs tree behavior in the model makes sense to me. 

### CakePHP Version

5.1.0

**Comment by dereuromark** [comment]
Those have always existed as community versions, as they can be quite different in style and needs.
See e.g. https://github.com/dereuromark/cakephp-tools/blob/master/docs/Helper/Tree.md and https://sandbox.dereuromark.de/sandbox/tools-examples/tree as example output.

**Comment by Dameen-Rainer** [comment]
Yeah I've come across cakephp-tools. But as the name suggests it contains several tools that the projects rarely need all of them and that will add extra size plus the compatibility might be an issue.

**Comment by ADmad** [comment]
Here's the TreeHelper standalone https://github.com/ADmad/cakephp-tree

**Comment by Dameen-Rainer** [comment]
Thank you ADmad, I'll check it out.

**Comment by Dameen-Rainer** [comment]
I've noticed some differences in the source code between the standalone Tree Helper and the one in cakephp-tools. Seems the latter's source code is newer last change 9 months ago while the standalone last change was in  2020.

**Comment by dereuromark** [comment]
That is up to you to clarify. Those are community plugins and not affiliated with core or core issues.

**Comment by Dameen-Rainer** [comment]
That's why I have suggested having that Tree Helper as core helper to handle what's coming from Tree Behavior. I thought suggestions are decided by vote just like in PHP.

Anyway many thanks.

**Comment by ADmad** [comment]
Did you actually try out the available solutions? Both handle the data structure returned by Tree behavior just fine.
