### ISSUE TITLE
5.x: Extension based routing too eager

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17314]
### Description

The code was upgraded from RequestHandler and clear extension based View class routing to
```php
	/**
	 * @return string[]
	 */
	public function viewClasses(): array {
		return [JsonView::class, XmlView::class];
	}
```
As it has some routes/actions in this controller with `.json` and `.xml` to respectively render this kind of type.
But in effect it now also tries to render even basic index actions (`/export`) with the overview as XML:

>  The view for ExportController::index() was not found.
Confirm you have created the file: "Export/xml/index.php" in one of the following paths:
/shared/httpd/sandbox/templates/Export/xml/index.php

I had to hack it for now with this:
```php
	/**
	 * @return string[]
	 */
	public function viewClasses(): array {
		if (!$this->request->getParam('_ext')) {
			return [];
		}

		return [JsonView::class, XmlView::class];
	}
```

Or is this expected to be used as such, rendering it basically impossible to not have this ext check in there?

That cannot be the solution though? I would expect routing-based control over it from extension level not just magic switching because browsers send a specific type along.

### CakePHP Version

5.x

### PHP Version

8.1

**Comment by dereuromark** [comment]
Maybe the docs here are missing the warning that if you want extension based routing, that "trick" above is needed to avoid it being too eagerly even for non-ext routing
https://book.cakephp.org/5/en/controllers.html#content-type-negotiation
There is clearly then something missing here to clarify this.

**Comment by ADmad** [comment]
> But in effect it now also tries to render even basic index actions (/export) with the overview as XML

That would happen only if the request has `Accept` header set to `application/xml`. Even RequestHandler would switch the view class based on the header.

**Comment by markstory** [comment]
> As it has some routes/actions in this controller with .json and .xml to respectively render this kind of type.
But in effect it now also tries to render even basic index actions (/export) with the overview as XML:

If you only need some actions to do content type negotiation, the `viewClasses` method can return different results for different action names.  The docs for [content-type negotiation](https://book.cakephp.org/5/en/controllers.html#content-type-negotiation) are a bit light, I can expand them.

**Comment by dereuromark** [comment]
For me it isnt about action names, as the same action can both return normal HTML and if used with extensions (xml, json, ...) it will return the table data as such data instead.
But without the `if (!$this->request->getParam('_ext')) {` part it would always only load the ext part already, even if not desired for normal non-ext call.

**Comment by markstory** [comment]
> But without the if (!$this->request->getParam('_ext')) { part it would always only load the ext part already, even if not desired for normal non-ext call.

Is the client sending an `Accept` header of the type it wants?

**Comment by dereuromark** [comment]
Well, it is a browser, but I would assume Chrome does that, yeah.

**Comment by dereuromark** [comment]
Docs are adjusted, closing then.
I still dont like the way the browser can hijack this too easily.
