### ISSUE TITLE
5.x: Restore $this->paginate()->toArray()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17312]
### Description

I have tons of code that uses paginate() and expects the result to be an array in the following code and templates.
Just removing to Array() doesnt often work or introduces hidden bugs (e.g. empty() usage).

In some older code also the iteration includes

    $images[$key]['...'] = ...;
    
etc, so direct array usage which blows up as

> Error: Cannot use object of type Cake\Datasource\Paging\PaginatedResultSet as array

So it would be best for easier upgrading and less timebombs in code if we could just have the array possibility of the result set back.

### CakePHP Version

5.x

### PHP Version

8.1

**Comment by ADmad** [comment]
There's nothing preventing you from using `$this->paginate()->toArray()`, it works just fine. Or you can do `$this->paginate()->items()->toArray()` or `iterator_to_array($this->paginate())`.

**Comment by ADmad** [comment]
By the way, by converting the PaginatedResultSet to an array you are going to lose all paging info and the paginator helper won't be able to generate any paging/sorting links.

**Comment by dereuromark** [comment]
`$this->paginate()->toArray()` didnt work for me, or least PHPStan mentioned it shouldnt work.
But I will try the alternatives where it is appropriate.
I will then leave things be, thx.
