### ISSUE TITLE
EntityTrait::hasErrors and ::getErrors produce infinite recursion on cyclic entity references

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#17318]
### Description

Right now (as of version 5.0.0, and in 4.x) calling `hasErrors()` or `getErrors()` on an Entity with cyclic entity references (i.e. via associated entities) results in an endless loop.

# Cause

`EntityTrait::hasErrors()` and `EntityTrait::getErrors()` by default recurse into associated entities looking for errors, without checking for cyclic references, thus resulting in an endless loop.

# Steps to reproduce

In a fresh skeleton app, the following code produces the endless loop (with debug=true):

```
$user = new \Cake\ORM\Entity([]);
$profile = new \Cake\ORM\Entity([]);
$user->set('profile', $profile);
$profile->set('user', $user);
$user->hasErrors(); // or $user->getErrors();
```

This produces the following error, or a similar error depending on which operation the memory actually runs out.

> Fatal error: Allowed memory size of 134xxxxxx bytes exhausted (tried to allocate 26xxxx bytes) in [ROOT]/vendor/cakephp/cakephp/src/Utility/Hash.php on line 660

# Proposed improvement

`EntityTrait::hasErrors()` and `EntityTrait::getErrors()` could keep a list of entities already visited, and not visit an entity instance more than once.

Since all entities get still visited, the behaviour of both methods would stay the same (while avoiding infinite recursion).

Major drawback: EntityInterface would have to change since we would need to pass an SplObjectStorage to both `hasErrors()` and `getErrors()`.

I'd be happy to write a fix plus some tests and send a merge request, if you don't have any better ideas or concerns.

### CakePHP Version

5.0.0

### PHP Version

8.2

**Comment by LordSimal** [comment]
Refs: https://github.com/cakephp/cakephp/issues/16707 and https://github.com/cakephp/cakephp/issues/16588

**Comment by markstory** [comment]
> Major drawback: EntityInterface would have to change since we would need to pass an SplObjectStorage to both hasErrors() and getErrors().

We'd need to have a solution that doesn't expand the method signatures. A visited set could be stored as a static attribute for the duration of the `getErrors()`/`hasErrors()` operation. There is likely also a solution that uses a 'queue' of entities to visit instead of recursion.

**Comment by LordSimal** [comment]
How about an additional property in the entity which states something like `isChecked`
Then whenever we recursivly go through all fields and sub-entities we can just skip entities which have already been checked.

**Comment by advitum** [comment]
I gave those solutions some thought, but there are some problems with each of them:

For any attribute (be it a static set of visited entities, or a state `isChecked` on each entity), we'd still need a way to make the *original* call to `getErrors()` or `hasErrors()` clear those attributes in the end, but the recursive calls to `getErrors()` or `hasErrors()` must not clear those attributes. And we need to most definitely clear those attributes, or subsequent calls to `getErrors()` or `hasErrors()` might return stale information.

The other solution would be to give the responsibility of recursing through the entities to the original call of `hasErrors()` or `getErrors()`. The entity could visit all entities and call `getErrors(false)` or `hasErrors(false)` on them. This however has the drawback of modifying the behavior of those methods. For example: Someone might have inherited form the Entity class to overwrite the getErrors method to restrict which associated entities it recurses into. Since the root entity would traverse all entities by itself, this implementation might break stuff.

I don't have any better solution. So we can either expand the method signatures while keeping the behaviour mostly the same, or we can alter the behaviour while keeping the method signature the same.

**Comment by advitum** [comment]
Okay, nevermind my previous answer. I took another look at #16588 and that solution should work. I didn't think to do it that way. I'll write a fix and some tests next week, and will also check if that fixes #16707 too.

**Comment by brenoroosevelt** [comment]
Sorry for the intrusion, but I'd like to share an idea. I don't have an in-depth knowledge of the implementation, but I think it's similar to this:"
```php
// implementation with recursion problem:
public function getErrors(): array
{
    $errors = $this->errors;
    foreach ($this->linkedEntities as $innerEntity) {
        array_push($errors, ...$innerEntity->getErrors());
    }
    return $errors;
}
```
You can refactor it as follows, maintaining the previous compatibility without using static properties or an internal state within the class:

```php
public function getErrors(): array
{
    $storage = new \SplObjectStorage(); // start new "context" to collect errors
    $this->internalGetErrors($storage);

    $errors = []; // process collected errors
    $storage->rewind();
    while ($storage->valid()) {
        array_push($errors, ...$storage->getInfo());
        $storage->next();
    }
    return $errors;
}

// collecting errors: make private for internal use only
private function internalGetErrors(\SplObjectStorage $storage): void
{
    if ($storage->contains($this)) { //checks if this has been visited
        return;
    }
    $storage->attach($this, $this->errors);
    foreach ($this->linkedEntities as $innerEntity) {
        $innerEntity->internalGetErrors($storage);
    }
}
```

This is only an idea and, obviously, does not reflect the current implementation.

**Comment by advitum** [comment]
While this would work, it would have the drawback of modifying the behavior quite significantly. As I wrote in my previous comments:

> This however has the drawback of modifying the behavior of those methods. For example: Someone might have inherited form the Entity class to overwrite the getErrors method to restrict which associated entities it recurses into. Since the root entity would traverse all entities by itself, this implementation might break stuff.

Are there any benefits I am missing?

**Comment by brenoroosevelt** [comment]
> While this would work, it would have the drawback of modifying the behavior quite significantly. As I wrote in my previous comments:
> 
The behavior has not been retained? The method would still fulfills the responsibility of returning its own errors and those of related entities, but now avoids circular dependencies. Whoever overrides the method should understand that they need to deal with the same challenges, but on their own.

Maybe I'm talking nonsense because I don't understand the implementation details, but my idea is just a suggestion focused on avoiding static properties and extra attributes that would need to be cleaned up. Here's a simplified version that might help you (but, the previous one seems more interesting):
```php
public function getErrors(?SplObjectStorage $visited = null): array
{
    $visited ??= new SplObjectStorage();
    if ($visited->contains($this)) {
        return [];
    }
    $visited->attach($this);
    $errors = $this->errors;
    foreach ($this->linkedEntities as $innerEntity) {
        array_push($errors, ...$innerEntity->getErrors($visited));
    }
    return $errors;
}
```

**Comment by advitum** [comment]
Your first solution, as I said, does not call `getErrors` on the linked entities, which breaks the behavior if someone happened to overwrite that method in their entity classes.

Your second solution would require expanding the method's signature, which @markstory explicitly said should be avoided.

In my opinion, the solution in #16588 would be the simplest and cleanest approach. I'll write an implementation and some tests today and send over a merge request, than you can check it out and propose changes if necessary.
