### ISSUE TITLE
Cakephp 5.0.1 , Version number not updated in VERSION.TXT

### ISSUE THREAD

**Issue by prbt2016** [cakephp/cakephp#17329]
### Description

Hello,

I was in the process of manual installation of Cakephp 5.0.1 downloaded from 
https://github.com/cakephp/cakephp/releases/download/5.0.1/cakephp-5-0-1.zip on Centos7 with Apache 2.2, MYSQL 5.7, PHP 8.1.9 . 

However, after successful manual installation, I found that version number isn't updated it's still 5.0.0. Please check screenshot.

![image](https://github.com/cakephp/cakephp/assets/17871448/04d865cf-ed97-4c19-8d81-1dec5c95fe9b)

On inspecting further, under /vendor/cakephp/cakephp/VERSION.txt I found that the version is 5.0.0 , i.e not updated .

Could you please fix and update this ?.

Regards.

### CakePHP Version

5.0.1

### PHP Version

8.1.9

**Comment by othercorey** [comment]
This should be fixed in 5.0.2. Don't think we will re-release 5.0.1.

**Comment by prbt2016** [comment]
Hello @othercorey ,

> This should be fixed in 5.0.2. Don't think we will re-release 5.0.1.

Okay thanks for notifying . !!!

**Comment by infoliv** [comment]
Same issue for Cakephp 4.4.18 (4.4.17 is shown)

**Comment by markstory** [comment]
Unfortunately, I couldn't use the standard release tooling for these releases as I didn't have my GPG keys with me at Cakefest. Version numbers will be correct in the next release.
