### ISSUE TITLE
Update CMS example application to 5.x

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#17330]
### Description

The CMS tutorial in the documentation links to [this repository](https://github.com/cakephp/cms-tutorial) as a completed example. We should update this project to use Cake 5.x

**Comment by sukuasoft** [comment]
@markstory Posso trabalhar nesta issue?

@aosccode

**Comment by markstory** [comment]
@sukuasoft Yes, help on this would be greatly appreciated.

**Comment by dereuromark** [comment]
Should this be moved to cakephp/docs?

**Comment by othercorey** [comment]
Did the recent doc updates resolve this?

**Comment by ADmad** [comment]
Done in https://github.com/cakephp/cms-tutorial/pull/13
