### ISSUE TITLE
5.0.1 - Invalid serialization data for DateTimeImmutable object

### ISSUE THREAD

**Issue by robertannett** [cakephp/cakephp#17342]
### Description

When upgrading from 5.0.0 to 5.0.1 and using the Authentication plugin I get the message `Invalid serialization data for DateTimeImmutable object`.

Issue caused by Chronos getting updated with cakephp using `composer update cakephp/cakephp -w`

### CakePHP Version

5.0.0

### PHP Version

8.1.13

**Comment by wojtekLs** [comment]
Ditch it please........Scam this is. Nothing more

**Comment by othercorey** [comment]
Do you have a callstack for this exception?

**Comment by othercorey** [comment]
Are you able to test with 5.0.1? Chronos dependency was updated which might affect this.

**Comment by robertannett** [comment]
@othercorey Here is a screenshot of the exception and the installed dependancies: https://imgur.com/a/Ur2OmQz

**Comment by othercorey** [comment]
Ah ok. I was confused by the different version numbers. This was caused by 5.0.0 to 5.0.1.

**Comment by othercorey** [comment]
I think the only solution for this is going to be clearing session data. This is likely best for a major upgrade anyway. The 5.0.1 release was to fix the initial release and we intend to keep the behavior in 5.0.1 going forward.

@markstory Looks like the Chronos change was not fully BC.

**Comment by robertannett** [comment]
Thanks @othercorey, one further note, I just noticed that if you upgrade without dependancies or update specifically to 5.0.1 (composer update cakephp/cakephp:5.0.1), it wont update because Cake requires cakephp/chronos ^3.0.2 so the upgrade path from a fresh install of CakePHP 5.0 to 5.0.1 isn't actually working (at least for me!).

`cakephp/cakephp 5.0.1 requires cakephp/chronos ^3.0.2 -> found cakephp/chronos[3.0.2, 3.0.3] but the package is fixed to 3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by othercorey** [comment]
Composer is correct, cakephp 5.0.1 requires Chronos 3.0.2. This was part of a post-release fix that require changes in both packages.

Unfortunately, it seems you hit our edge case, but we felt it was important to make the change early in a bug fix release to avoid  users not getting the changes.

**Comment by robertannett** [comment]
Not a bother, thanks @othercorey
