### ISSUE TITLE
composer issue with laminas mail

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#17355]
### Description

1. Add To composer
```
"cakephp/cakephp": "5.*",
"laminas/laminas-mail": "^2.23.0"  
```

2. run `composer update`

3. result:

Problem 1
    - Root composer.json requires laminas/laminas-mail 2.23.0 -> satisfiable by laminas/laminas-mail[2.23.0].
    - Conclusion: don't install psr/container 2.0.2 (conflict analysis result)
    - cakephp/cakephp[5.0.0, ..., 5.0.1] require psr/container ^2.0 -> satisfiable by psr/container[2.0.0, 2.0.1, 2.0.2].
    - Conclusion: don't install psr/container 2.0.1 (conflict analysis result)
    - Root composer.json requires cakephp/cakephp 5.* -> satisfiable by cakephp/cakephp[5.0.0, 5.0.1].

If I change cakephp 5.* to * than cakephp 4.5 is installed.
if I change laminas-mail from ^2.23.0 to * than laminas 2.5.2 (very, very old) is installed

solution:
if you remove for example (maybe not the solution) the
`"psr/container": "^2.0"` constraint than it works again or change it to `1.1.2 | ^2.0`

at the moment I solve this by adding in the composer:
`"psr/container": "1.1.2 as 2.0.2"`
which is only a quick fix for a short period of time

### CakePHP Version

5.0.1

### PHP Version

8.2.4

**Comment by dereuromark** [comment]
This seems to be more a problem with your laminas code
See also https://github.com/laminas/laminas-mail/issues/249 , https://github.com/cakephp/cakephp/issues/16046 etc

**Comment by markusramsak** [comment]
> This seems to be more a problem with your laminas code See also [laminas/laminas-mail#249](https://github.com/laminas/laminas-mail/issues/249) etc

it is just the latest version which depends on psr container 1.x
CakePHP 4.5.0 has a contraint which allows to install the latest laminas-mail package version with psr-container 1.x but CakePHP 5.0 requires 2.x
Is psr-container 2.x really required? Couldn't it be relaxed a little bit to "1.1.2 | ^2.0" to allow the latest laminas-mail version like CakePHP 4.5.0?

**Comment by dereuromark** [comment]
Well, looking into the code, it seems indeed possible
If the Cake dependency "league/container" can do it ( "psr/container": "^1.1 || ^2.0" ), then we should be able, too.

    class Container extends LeagueContainer implements ContainerInterface

**Comment by dereuromark** [comment]
I have seen a few similar complaints and I cannot see a reason for the limitation if the dependency doesnt restrict.

https://github.com/cakephp/cakephp/pull/17356
Lets see what the builds say, and the others.
