### ISSUE TITLE
`$modelClass` incorrectly marked as deprecated

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#17379]
### Description

`ModelAwareTrait::$modelClass` is incorrectly marked as deprecated on 4.x branch
https://github.com/cakephp/cakephp/blob/4.x/src/Datasource/ModelAwareTrait.php#L48

This deprecation was reversed in 5.x
https://github.com/cakephp/cakephp/blob/5.x/src/Datasource/ModelAwareTrait.php#L46

### CakePHP Version

4.5.0

**Comment by othercorey** [comment]
@ADmad What is expected here?

**Comment by ADmad** [comment]
The deprecation was reverted and `ModelAwareTrait` has been retained in 5.x, so removing the `@deprecated` tag makes sense.

Though it's no longer used by the `Controller` class by default in 5.x, but I guess that's something for the migration guide.
