### ISSUE TITLE
TypeError when using Form::time() with Cake\I18n\Time

### ISSUE THREAD

**Issue by DBnR1** [cakephp/cakephp#17378]
### Description

I would expect `Form::time()` to accept `Cake\I18n\Time` but instead I get a TypeError:
`Cake\View\Widget\DateTimeWidget::formatDateTime(): Argument #1 ($value) must be of type Cake\Chronos\ChronosDate|DateTimeInterface|string|int|null, Cake\I18n\Time given, called in .../vendor/cakephp/cakephp/src/View/Widget/DateTimeWidget.php on line 124`

Works fine on CakePHP 4 but now getting this error when updating a large-ish application to CakePHP 5.

### CakePHP Version

5.0.1

### PHP Version

8.2

**Comment by dereuromark** [comment]
What version of Chronos are you using Are you using [3.0.2](https://github.com/cakephp/chronos/releases/tag/3.0.2)+?

**Comment by DBnR1** [comment]
> What version of Chronos are you using Are you using [3.0.2](https://github.com/cakephp/chronos/releases/tag/3.0.2)+?

Yes, 3.0.4 at the moment.
