### ISSUE TITLE
Cake4 apps and plugins not testable with PHP8.3

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17387]
### Description

```
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp[4.4.17, ..., 4.5.0] require laminas/laminas-diactoros ^2.2.2 -> satisfiable by laminas/laminas-diactoros[2.2.2, ..., 2.25.2].
    - laminas/laminas-diactoros[2.2.2, ..., 2.4.1] require php ^7.1 -> your php version (8.3.0-dev) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.5.0, ..., 2.6.0] require php ^7.3 || ~8.0.0 -> your php version (8.3.0-dev) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.7.0, ..., 2.14.0] require php ^7.3 || ~8.0.0 || ~8.1.0 -> your php version (8.3.0-dev) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.15.0, ..., 2.17.0] require php ^7.4 || ~8.0.0 || ~8.1.0 -> your php version (8.3.0-dev) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.18.0, ..., 2.[25](https://github.com/dereuromark/cakephp-queue-scheduler/actions/runs/6652968031/job/18077982216#step:8:26).2] require php ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.3.0-dev) does not satisfy that requirement.
    - Root composer.json requires cakephp/cakephp ^4.4.17 -> satisfiable by cakephp/cakephp[4.4.17, 4.4.18, 4.5.0].
```

We need to find a way to make them testable IMO

https://github.com/dereuromark/cakephp-queue-scheduler/actions/runs/6652968031/job/18077982216

It shows that laminas/laminas-diactoros in all compatible versions to cake 4.4 and 4.5 do not offer 8.3 support due to their bad way of constraining.
We might have to make a patch for them, if they dont do it themselves for 2.25.x series.

8.3 will be released in a few weeks, it should now already be clear if the package is compatible or not.

### CakePHP Version

4.5

### PHP Version

8.2/8.3

**Comment by LordSimal** [comment]
Personally I'd be fine if we stop PHP Support for 4.x on PHP 8.2
This would be another reason for people to upgrade to Cake5
Then we don't need this.

**Comment by dereuromark** [comment]
Thats not a viable or responsible strategy as 4.x will be around some time on a lot of Apps, especially also in critical Business ways.
And even 8.2 will some day be EOL, and security will be an issue

**Comment by LordSimal** [comment]
We already defined, that Cake4 will get Security Updates [till September 2026](https://github.com/cakephp/cakephp/wiki) which would align pretty well with PHP 8.3 EOL - therefore this is needed, yes

My previous message was just my personal opinion but I have always been more on the up2date train so excuse me 😉

**Comment by dereuromark** [comment]
This has been resolved though dependencies getting fixed. Tested and confirmed.

**Comment by ishanvyas22** [comment]
@dereuromark Does it mean CakePHP 4.x will support 8.3?

Looks like support for PHP 8.3 is under progress because tests are not running PHP 8.3 in CI and documentation also says "8.2 supported". However in [version map](https://github.com/cakephp/cakephp/wiki#version-map) it says "latest" as PHP max.

**Comment by dereuromark** [comment]
Try it yourself. You are free to provide PRs to update test matrix as well
Technically there shouldnt be a reason it wouldnt run on 8.3
