### ISSUE TITLE
Calling $this->configRequest() multiple times does not reset sub-keys

### ISSUE THREAD

**Issue by DBnR1** [cakephp/cakephp#17390]
### Description

According to the documentation, calling `$this->configRequest()` multiple times should reset sub-keys such as `headers`. Instead they are appended.

    $headers = [
        'Authorization' => 'Bearer token1',
    ];

    $this->configRequest(
        [
            'headers' => $headers,
        ]
    );

    $headers = [
        'Authorization' => 'Bearer token2',
    ];

    $this->configRequest(
        [
            'headers' => $headers,
        ]
    );

    debug($this->_request['headers']['Authorization']);

I would expect this code to return 

    [
          (int) 0 => 'Bearer token2',
    ]

Instead it returns

    [
          (int) 0 => 'Bearer token2',
          (int) 1 => 'Bearer token1',
    ]

It worked as expected in CakePHP 4.

### CakePHP Version

5.0.1

### PHP Version

8.2

**Comment by LordSimal** [comment]
As far as I can tell what is described in the docs was actually never true... we never removed any data from the request when calling `configRequest()`. We just reset the request property in `tearDown()` which is expected to get a clean state for the next test.

So the only way you can currently reset that config is calling `$this->cleanup()` manually before doing your consecutive `configRequest()` call.

**Comment by DBnR1** [comment]
I see, maybe why it worked for us on Cake 4 was because of something else. Maybe CakePHP 4 or version 2 of the Authentication plugin worked with multiple values in the Authorization header.

Anyway, calling `$this->cleanup()` helped with this problem. Thanks!

**Comment by markstory** [comment]
Which docs state or imply that data is reset? We can get that corrected.

**Comment by LordSimal** [comment]
The configRequest() method phpdoc at the end
https://api.cakephp.org/5.0/trait-Cake.TestSuite.IntegrationTestTrait.html#configRequest()
