### ISSUE TITLE
Driver::quote() has been removed in 5.0 (needed to quote a string / int to avoid being interpreted as column identifier)

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#17408]
### Description

Up until CakePHP 5.0.0 when building a condition or select query by default values have been quoted as string.

```php
                $responseObjects->select([
                    'response_object_id' => $hierarchyNodesTable->aliasField('id'),
                    'response_object_type' => 'hierarchy_node',
                    'lft' => $hierarchyNodesTable->aliasField('lft'),
                    'rght' => $hierarchyNodesTable->aliasField('rght'),
                ]);
```
This now returns the following issue:

`Undefined column: 7 ERROR:  column hierarchy_node does not exist`

The SQL is generated assuming hierarchy_node is an identifier but it is a fixed string value. Happens in PostgreSQL here.

### CakePHP Version

5.0.2

### PHP Version

8.2

**Comment by markstory** [comment]
> Up until CakePHP 5.0.0 when building a condition or select query by default values have been quoted as string.

Are you sure? In the [documentation](https://book.cakephp.org/4/en/orm/query-builder.html#aggregates-group-and-having) and [in tests](https://github.com/cakephp/cakephp/blob/4.x/tests/TestCase/ORM/QueryTest.php#L3365-L3385) we have coverage that the values of select() with an array are treated as identifiers. In your example, if array values were treated as strings, then the result of `$hierarchyNodesTable->aliasField('rght')` would also be a string, and not a column reference.

If you could provide a test showing the behavior you're seeing in 4.x that behaves differently in 5.x that would be helpful.

**Comment by swiffer** [comment]
@markstory - see that i've used Connection::quote() in CakePHP 4.0 - sorry. that must have been slipped through when migrating to CakePHP 5.0 - tests haven't failed locally as sqlite is working just fine without quoting while mariadb/postgres are failing.

As Connection::quote() is no longer there - what could be used instead ?

In 4.5.0 quote() has been moved to the driver class but in 5.0 it's missing

**Comment by ADmad** [comment]
> As Connection::quote() is no longer there - what could be used instead ?

`$connection->getDriver()->quoteIdentifier()`

**Comment by swiffer** [comment]
@ADmad - I'm not sure conn->quote() used PDO->quote() which allows a  string to be quoted. Isn't quoteIdentifier used for Column / Table Names instead?

The Driver->quote() method is not marked depreacated in 4.5 but is missing in 5.0

To get the same functionality I would have to call $conn->getDriver()->getPdo()->quote(...) but getPdo() is protected currently.

**Comment by markstory** [comment]
> In 4.5.0 quote() has been moved to the driver class but in 5.0 it's missing

We don't currently have a public API for this as all of the queries that the ORM/Database layers make are intended to be prepared statements. You could likely get what you want with `QueryExpression` as it allows you to embed SQL snippets into queries, however it doesn't offer quoting so it is unsafe to be used with user input.

We could potentially add `Driver::quote()` back to cover scenarios like needing to put string values into select clauses.

**Comment by swiffer** [comment]
As I'm not dealing with User Input and *all DBMS are supporting string literals / constants quoted via `'` I'll just add that to the query myself.

- https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
- https://sqlite.org/lang_keywords.html
- https://mariadb.com/kb/en/string-literals/

I've seen that there is StringExpression in recent versions which could work as well but a collation is required as second parameter currently.

If there is interest in adding the method back I'm happy to open a PR.

**Comment by othercorey** [comment]
StringExpression was added specifically for strings with a non-default collation otherwise it's not needed. The string is passed as a bound parameter and not quoted.
