### ISSUE TITLE
BetweenExpression: possible missing nullable 

### ISSUE THREAD

**Issue by andrewlavens** [cakephp/cakephp#17402]
### Description

I tried using the between expression but received the following error message: 

> Cake\Database\Expression\BetweenExpression::_bindValue(): Argument # 3 ($type) must be of type string, null given, called in [...]/vendor/cakephp/cakephp/src/Database/Expression/BetweenExpression.php on line 94

I've had a look at /src/Database/Expression/BetweenExpression.php and how $type is used. It originates as the object property $_type which is a mixed value (line 51). During the constructor it's assigned the nullable string value $type (line 71) but the _bindVlue function argument $type is defined as a string (line 123). Should it be nullable too i.e. _?string $type_ ?

### CakePHP Version

5.0.2

### PHP Version

8.1.2

**Comment by dereuromark** [comment]
What kind of data are you using for it?
Can you maybe make an example?

**Comment by andrewlavens** [comment]
I'd used code similar to the example in the doc:
```php
->where(function (QueryExpression $exp, SelectQuery $q) {
        return $exp->between('publication_date', 1850, 2023);
    });
```
...but the constructor for BetweenExpression has an additional argument $type that is mixed or nullable apart from in _bindValue.

**Comment by dereuromark** [comment]
PR open now.
