### ISSUE TITLE
Ajax requests are not rendered with ajax layout

### ISSUE THREAD

**Issue by calcosta** [cakephp/cakephp#17415]
### Description

With the old RequestHandler Ajax requests (X-Requested-With:XMLHttpRequest) were automatically rendered using the ajax layout.
With CakePHP 5 this does not work any more.

A request with the Header `X-Requested-With:XMLHttpRequest` and `Accept:text/html` or `Accept:*/*` is correctly identified as an ajax request as `$this->request->is('ajax')` is `true`.
However it seems that `Controller::chooseViewClass()` does not set the ViewClass to AjaxView because it only considers extension and the Accept Header (which is default `text/html`).

`$this->addViewClasses([App\View\AjaxView::class])` in my Controller does not make any difference.

If I set the AjaxView that comes with Cake Core (`$this->addViewClasses([Cake\View\AjaxView::class])`) all views are rendered with the ajax layout because the AjaxView class sets it matching contentType to text/html
```
public static function contentType(): string
{
    return 'text/html';
}
```

### Expected behavior
When `$this->request->is('ajax')` is `true` I would expect that `App\View\AjaxView` is used.

### CakePHP Version

5.0.2

### PHP Version

8.2

**Comment by markstory** [comment]
Yeah, there isn't a great place to put ajax layout swapping in the framework with `RequestHandlerComponent` not around anymore.  Having `Controller::chooseViewClass()` could be a place to add that logic though.

**Comment by dereuromark** [comment]
I feel like for those cases having such a component back would be cleaner and more dry than adding so much logic into all the Controllers

**Comment by markstory** [comment]
> I feel like for those cases having such a component back would be cleaner and more dry than adding so much logic into all the Controllers

A component is another way to approach this. My thought was that we re-integrate AjaxView usage into the framework like we did with content-negotiation.

**Comment by ADmad** [comment]
I would rather not add more AJAX specific stuff to the core. `XMLHttpRequest` is a dying API. The new Javascript Fetch API doesn't set this header. So long term it's better people start modifying their code to not reply on checking the `X-Requested-With:XMLHttpRequest` header.

**Comment by markstory** [comment]
@ADmad What do you think about including a Component to help folks who were using `RequestHandler` to upgrade?

The alternative would be users need to add a block of code similar to

```php
if ($this->request->is('ajax')) {
    $this->viewBuilder()->setLayout('ajax');
}
```

To their `AppController::beforeRender()`

**Comment by ADmad** [comment]
I would prefer we suggest using that 2 liner in the migration docs, instead of adding a component for BC.

**Comment by calcosta** [comment]
As a user :), I would also suggest that the two lines in the controller are the better solution. This is easy to understand and can be quickly applied on a controller basis or via the AppController for the entire application.
The AjaxView class would then also be obsolete, wouldn't it?

**Comment by dereuromark** [comment]
I am not a big fan of throwing the slim controller paradigm overboard.
Especially since the logic is starting to pile up, see also https://github.com/cakephp/cakephp/issues/17314
The whole logic in each controller quickly becomes quite an unDRY.

Sure, I could add more logic to the Ajax plugin and https://github.com/dereuromark/cakephp-ajax/blob/master/src/Controller/Component/AjaxComponent.php
But it still feels a bit weird to have to rely on 3rd party stuff to have AJAX work out of the box without the need of such controller-logic.
Especially coming from 4.x world.

I was more hoping for a RequestHandler component or alike that would again negogative it smartly
So in my case of "too eager" above would just decide on the correct way based on the controller's view classes available, etc.
And also in this case based on the headers.

**Comment by markstory** [comment]
>  The AjaxView class would then also be obsolete, wouldn't it?

No, we could have the snippet be

```php
if ($this->request->is('ajax')) {
    $this->viewBuilder()->setClassName('Ajax');
}
```

as well. We also need to keep it around for backwards compatibility.

**Comment by markstory** [comment]
Closing as the docs have been updated now.
