### ISSUE TITLE
Cake\Console\Arguments getOption/getOptions should allow for array return value in method signature

### ISSUE THREAD

**Issue by crifpeguy** [cakephp/cakephp#17428]
### Description

When using the `multiple` option for `Cake\Console\ConsoleOptionParser::addOption` we should be able to get back an array of all the values set for that option with the `getOption` method of `Cake\Console\Arguments`.

I think the function still does this, but the signature is too restrictive.

### CakePHP Version

5.0.2

### PHP Version

8.2.12

**Comment by othercorey** [comment]
Looks like the type hints for an option is missing array everywhere so we didn't add it when auto-generating type declarations for cake 5.

**Comment by dereuromark** [comment]
And tests seem then to be missing, too

**Comment by markstory** [comment]
Expanding the signature will make userland code less typesound as our previously scalar/stringable type now includes `array`. Should we add `getOptionArray` or `getOptionList` instead? A new method could have a return or `array | null`.

**Comment by othercorey** [comment]
Maybe getArrayOption or getMultipleOption makes sense as it's only valid for `multiple` options.
