### ISSUE TITLE
Overriding plugin translations not working since 4.5.0

### ISSUE THREAD

**Issue by jmischer** [cakephp/cakephp#17423]
### Description

Prior to 4.5.0 I used to override plugin translations by creating a .po file in `resources/locales/en/my_plugin.po`. Since 4.5.0 this is no longer possible due to MessagesFilesLoader::translationFolders returning the plugin folders first.

I have written two tests demonstrating this issue.

```
    /**
     * Testing MessagesFileLoader::translationsFilder array sequence
     */
    public function testTranslationFoldersSequence(): void
    {
        $this->loadPlugins(['TestPlugin']);
        $loader = new MessagesFileLoader('test_plugin', 'en');
        $expected = [
            ROOT . '/tests/test_app/resources/locales/en_/',
            ROOT . '/tests/test_app/resources/locales/en/',
            ROOT . '/tests/test_app/Plugin/TestPlugin/resources/locales/en_/',
            ROOT . '/tests/test_app/Plugin/TestPlugin/resources/locales/en/'
        ];
        $result = $loader->translationsFolders();
        $this->assertEquals($expected, $result);
    }
    
    /**
     * Testing plugin override from app
     */
    public function testPluginOverrideFromApp()
    {
        $this->loadPlugins(['TestPlugin']);
        $loader = new MessagesFileLoader('test_plugin', 'en');
        $package  = $loader();
        $messages = $package->getMessages();
        $this->assertSame('Plural Rule 1 (from test app)', $messages['Plural Rule 1']['_context']['']);
    }
```

You need to add the `test_plugin.po` file to `tests/test_app/resources/locales_/en`.

```
msgid "Plural Rule 1"
msgstr "Plural Rule 1 (from test app)"
```

The tests pass in 4.4.18 and fail in 4.x.

Please correct me if I am suppose to override plugin translations some other way.

### CakePHP Version

4.5.0

### PHP Version

7.4.33

**Comment by markstory** [comment]
This looks like a side-effect of #16969 being implemented and us not having test coverage for this scenario. I'm not currently able to find a way that plugin resources can both be first as required by #16969 and last as was the previous behavior.

The only solution that is coming to mind is to have a configure value for toggling the order of plugins in locale search paths.

**Comment by jmischer** [comment]
That seems to be the reason. Right now I dont see the requirement for plugin resources being first, i will dig deeper.
A configure value might work but I am not quite sure how to provide/get them except maybe use `Configure::read(...)` in MessagesFileLoader. I will also check `\Cake\I18n\I18n::setTranslator` in bootstrap.

Sorry, some quick questions.
What should be the default behavior? The actual or the previous behavior?
Should a possible pull request be based on 4.next or 4.x?

**Comment by ADmad** [comment]
With the release of 5.0, a 4.6 is unlikely to happen so I think PR against 4.x is fine. Also I see this as a regression so the previous behavior should be the default IMO.

But let the other team members weigh in.

**Comment by markstory** [comment]
>  Right now I dont see the requirement for plugin resources being first, i will dig deeper.

I took another look as well. The failing test is being caused because a string from `test_plugin` is expected, but the test-app override is applying instead. If we had more tests earlier, we would have caught/prevented this regression.

**Comment by jmischer** [comment]
Same fix but different testing. I feel like changing the test `testPluginMesagesLoad`  should be avoided.
[4.x-fix/17423](https://github.com/jmischer/cakephp/tree/4.x-fix/17423)
I also tested an configurable approach, but it doesn't seem right.

**Comment by markstory** [comment]
@jmischer If you want to open a pull request with those changes we can go forwards with those changes instead of mine.
