### ISSUE TITLE
Flags for Mysql

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17425]
### Description

Cake\Database\Driver:createPdo() contains
```php
        $action = fn () => new PDO(
            $dsn,
            $config['username'] ?: null,
            $config['password'] ?: null,
            $config['flags']
        );
```

which for Mysql accepts string flags.

The config that is working is:
```php
'flags' => [
		PDO::MYSQL_ATTR_INIT_COMMAND => "SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))",
	],
```
which gets passed to that PDO class then as
```php
  'flags' => [
    (int) 1002 => 'SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))',
    (int) 12 => false,
    (int) 20 => false,
    (int) 3 => (int) 2
  ],
```

But when also adding SQlite to test harness that one fails hard with

> Error in bootstrap script: TypeError:
Attribute value must be of type int for selected attribute, string given
#0 /home/runner/work/...vendor/cakephp/cakephp/src/Database/Driver.php(185): PDO->__construct()

Maybe we should check the flags case of Sqlite and then remove those that are not matching?
Or does one need to conditionally set them in the bootstrap/config themselves?

### CakePHP Version

5.x

### PHP Version

8.2

**Comment by dereuromark** [comment]
For now I used
```php
if (str_contains(getenv('DB_URL'), 'mysql')) {
	$config['flags'][PDO::MYSQL_ATTR_INIT_COMMAND] = "SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))";
}
```

If thats the way here, we can close.

**Comment by ADmad** [comment]
I would expect users to properly set the required/valid config depending on the db engine, whether in testing or production.

Passing mysql flags to sqlite is just wrong and it shouldn't be the job of the connection manager/driver class to mitigate that.
