### ISSUE TITLE
Confirmation Message for FormHelper doesn't support newline characters

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#17449]
### Description

In CakePHP 3 the kind of the confirmation message implementation supported newline charcters.

Now in CakePHP 4 it is not possible anymore to integrate newline characters or I simply don't know how.

In CakePHP 3 the following code:
```
<?= $this->Form->postLink(
    'Delete',
    ['action' => 'delete', $article->id],
    ['confirm' => 'Text in the first line.\nSome text in the next line'])
?>
```
generated a JS dialog which supported newlines in the confirmation dialog, because the generated HTML was like:
```
<a href="#" onclick="if (confirm(&quot;Text in the first line.\nSome text in the next line&quot;)) { document.post_6560f918b6034460798220.submit(); } event.returnValue = false; return false;">Delete</a>
```
but now there will be generated the following piece of code:
```
<a href="#" data-confirm-message="Text in the first line.\nSome text in the next line" onclick="if (confirm(this.dataset.confirmMessage)) { document.post_6560f91ecb213856330014.submit(); } event.returnValue = false; return false;">Delete</a>
```
So what is the correct way to implement newlines in the messages or does the cakephp code has to be edited?

My current workaround is to replace all \n ind my confirmation messages with `&#10;`

### CakePHP Version

4.5.1

### PHP Version

8.2

**Comment by LordSimal** [comment]
I personally have an overwritten FormHelper to adjust that postLink behavior with [Sweetalert](https://sweetalert2.github.io/) since its a much nicer modal than the default browser one.

If we can fix this new line behavior bug in Cake I am fine with putting that in, but in the end I would recommend everyone who needs more functionality from what the default Helpers provide to overwrite or even write their own Helpers to get exactly what they need.

**Comment by dereuromark** [comment]
For me those worked afaik, if those are actual newline characters, using " instead of ' in PHP.
But otherwise I would recommend using spaces for your case, or str_replace() those into spaces at runtime.

**Comment by ADmad** [comment]
Put the `\n` in double quotes instead of single quotes.
