### ISSUE TITLE
Form->control empty=>false ignored

### ISSUE THREAD

**Issue by WTFDuck** [cakephp/cakephp#17450]
### Description

`$this->Form->control('thing', $somethings, ['empty' => false]);`

Still creates an empty option in my form selects, even though forced to empty=>false.

When using empty=>false in a Form->select instead of a Form->control the empty=>false feature works properly.

Thanks everyone!

### CakePHP Version

5.0.2

### PHP Version

8.2.12

**Comment by dereuromark** [comment]
What is inside $somethings?

**Comment by dereuromark** [comment]
Are you using an IDE?
It would tell you that control() only has two arguments
```php
    public function control(string $fieldName, array $options = []): string
```

As such, it doesnt see and use your empty config here.

You need to, as documented, use the 2nd options arg as nested one
```php
$options = [
    'empty' => false,
    'options' => $somethings,
]
```

**Comment by WTFDuck** [comment]
I see it now, shame on me.  Thank you.
https://api.cakephp.org/5.0/class-Cake.View.Helper.FormHelper.html#control()
