### ISSUE TITLE
DatabaseException : "Cannot describe requests. It has 0 columns" after Cakephp update

### ISSUE THREAD

**Issue by infoliv** [cakephp/cakephp#17466]
### Description

I just updated Cakephp 5.0.2 => 5.0.3 and now a database exception is thrown at anytime : "Cannot describe requests. It has 0 columns"

Is there a problem with v5.0.3 ?

### CakePHP Version

5.0.3

### PHP Version

8.2

**Comment by othercorey** [comment]
Do you have a callstack?

**Comment by infoliv** [comment]
![callstack - Error Cannot describe requests  It has 0 columns](https://github.com/cakephp/cakephp/assets/4060838/b97e4c09-998c-46ec-acca-d824a78ccac9)

**Comment by dereuromark** [comment]
It might be unrelated. It basically just means It cannot access the database (table) for some reason.
Did u also clear the Cache?

**Comment by infoliv** [comment]
> Did u also clear the Cache?

I did

**Comment by dereuromark** [comment]
Looks like debug kit has an issue here 
Maybe your sqlite is not working anymore?

**Comment by infoliv** [comment]
You're right it seems the issue disappears when debug kit is disabled.
Anyway, I have this DatabaseException even when I try to access to the "home" static page

**Comment by ADmad** [comment]
Try deleting the `tmp/debug_kit.sqlite` file.

**Comment by infoliv** [comment]
> Try deleting the `tmp/debug_kit.sqlite` file.

Same problem

**Comment by ADmad** [comment]
What's your sqlite version?

**Comment by infoliv** [comment]
Server type: MySQL
Server connection: SSL not used
Server version: 5.7.42-0ubuntu0.18.04.1 - (Ubuntu)

Database client version: libmysql - mysqlnd 8.2.7
PHP extension: mysqli  curl  mbstring 
PHP version: 8.2.7

**Comment by ADmad** [comment]
I asked for the sqlite version :)

**Comment by infoliv** [comment]
SQLite Library 3.22.0

**Comment by ADmad** [comment]
The problem is caused by this change https://github.com/cakephp/cakephp/pull/17441.

`table_xinfo` is available since SQLite [3.26.0](https://www.sqlite.org/releaselog/3_26_0.html), so we need to switch the method based on a version check.
