### ISSUE TITLE
Cake\I18n\DateTime changes value when converted to JSON if the year is "0000"

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17477]
### Description

Hi all

### What I have

For a specific reason, I store some dates as `0000-00-02 19:56:48`. This allows reusing the same database column to store dates that need to be handled differently – as well as being storing legit datetimes. 

### What I tried and what happened
1. First, trying `find()` followed by `debug()` outputs `-0001-12-02 19:56:48.000000`.
2. Then, setting `Cake\I18n\DateTime::setJsonEncodeFormat('yyyy-MM-dd HH:mm:ss')` and outputting as JSON gets me `0002-12-04 19:56:48`
    So the whole date gets changed to `0002-12-04`

I understand that the original date in the database is invalid (the month `00` does not exist), which could be confusing the parser. So as an experiment, I tried `0000-01-02 19:56:48` - which, while still unusual, I would argue is formally valid.

1. `find()`, `debug()`: 
        
        'datetime' => object(Cake\I18n\DateTime) id:6 {
            'hasFixedNow' => false
            'time' => '0000-01-02 19:56:48.000000'
            'timezone' => 'UTC'
        }
        
    So far so good.
2. `Cake\I18n\DateTime::setJsonEncodeFormat('yyyy-MM-dd HH:mm:ss')`:
        
        "datetime": "0001-01-04 19:56:48"
        
    So the year got increased to `0001` and the day got increased to `04`.

### What I expected to happen

Getting exactly the value I have stored in my database.

----

I found cakephp/cakephp#1528 from 2013 which is close, but not exactly the same issue. 

Are there any hopes of having the built-in JSON Response handler output exactly the date I have without changing it?

To be clear: it's not that I feel like the core should be changed for this. If there's a way to accomplish this by modifying my `find()` query to disable `Cake\I18n\DateTime` on dates starting with `0000-`, I think that would be enough for me to move on. But this is a working approach I have been using for years just fine on a custom-coded website which I'm now trying to move to CakePHP.

### CakePHP Version

5.0.2

### PHP Version

8.3.0

**Comment by mehov** [comment]
> I tried `0000-01-02 19:56:48` - which, while still unusual, I would argue is formally valid.

Alright, apparently not: https://en.wikipedia.org/wiki/Year_zero

> Historians have never included a year zero. In common usage anno Domini 1 is preceded by the year 1 BC, without an intervening year zero.

You live, you learn.

But still, gotta have my `0000-00-02 19:56:48`

**Comment by dereuromark** [comment]
That date Format is just not valid.
I recommend changing your requirements.

**Comment by markstory** [comment]
> Are there any hopes of having the built-in JSON Response handler output exactly the date I have without changing it?

I don't think so, as CakePHP isn't really doing much with formatting these values. I think you might be running into limitations of PHP's datetime libraries as we don't have any logic to adjust or change datetimes with the year 0000.

**Comment by dereuromark** [comment]
If not storing valid datetimes for both the DB and PHP, I suggest using string (char) and apply your own type class and logic then.
Closing as there is nothing the framework itself can do here.

**Comment by mehov** [comment]
Thank you gentlemen for your comments.

This is indeed a PHP issue:

- https://stackoverflow.com/questions/10450644/how-do-you-explain-the-result-for-a-new-datetime0000-00-00-000000
- https://stackoverflow.com/questions/29917598/why-does-0000-00-00-000000-return-0001-11-30-000000

Solution: 

1. [`disableResultsCasting()`](https://api.cakephp.org/4.0/class-Cake.ORM.Query.html#disableResultsCasting()) to stop automatic casting of everything into a DateTime.
2. Use [`formatResults()`](https://book.cakephp.org/5/en/orm/query-builder.html#adding-calculated-fields) to check if the year starts with `0000`; cast to DateTime if not.
