### ISSUE TITLE
CakePHP 5.0 PHPUnit support causing fatal errors

### ISSUE THREAD

**Issue by chartjes** [cakephp/cakephp#17484]
### Description

I have a test that is using `IntegrationTestTrait` that was previously working with CakePHP 4.x and an older version of PHPUnit and it now is generating a fatal error.

Here is the test:

```
<?php

declare(strict_types=1);

namespace App\Test\TestCase\Controller;

use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

class IndexControllerTest extends TestCase
{
    use IntegrationTestTrait;

    /**
     * @test
     */
    public function index(): void
    {
        $this->get('/');
        $this->assertResponseOk();
        $this->assertResponseContains('<!-- navbar element -->');
        $this->assertResponseContains('<!-- schedule element -->');
        $this->assertResponseContains('<!-- rotations element -->');
        $this->assertResponseContains('<!-- standings element -->');
        $this->assertResponseContains('<!-- results element -->');
        $this->assertResponseContains('<!-- results element -->');
        $this->assertResponseContains('<!-- boxscores element -->');
        $this->assertResponseContains('<!-- free agent priority element -->');
    }
}

```

and it reports the following error:

```
PHP Fatal error:  Cannot override final method PHPUnit\Framework\Assert::assertDirectoryDoesNotExist() in /Users/chartjes/Sites/ibl/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 159
```

### CakePHP Version

5.0

### PHP Version

8.1

**Comment by markstory** [comment]
What versions of cake and phpunit do you have? We don't currently have an `assertDirectoryDoesNotExist` method in our repo. We did have one, but it was removed in 5b4873c3eef4322c2710ea96ea46db87cf84f10c

**Comment by chartjes** [comment]
I am running PHPUnit 10.1.17 and I have migrated from Cake 4.x to Cake 5.x using the migration guide. Am I missing a step like a `composer update` at the end of things?

**Comment by dereuromark** [comment]
Try using a more modern version of phpunit, 10.3, 10.4 or recommended 10.5

**Comment by chartjes** [comment]
> Try using a more modern version of phpunit, 10.3, 10.4 or recommended 10.5

How is that supposed to fix a fatal error happening in Cake's test helper?

**Comment by chartjes** [comment]
Looks like it has been fixed by going through my `composer.json` and upgrading things as recommended in `https://github.com/cakephp/app/blob/5.x/composer.json`. Thanks for looking into this for me
