### ISSUE TITLE
5.x typo in enum value

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17522]
### Description

https://github.com/cakephp/cakephp/blob/d3b0274fe3d8c4ce145a0dcad9849d13415abc15/src/Database/DriverFeatureEnum.php#L29
I guess no one saw that one

Based on BC we can only fix this in 6.0? Or is 5.1 viable?

### CakePHP Version

5.x

**Comment by othercorey** [comment]
I don't think value is expected to be used without the constant. The constants were used before we had enums.

**Comment by dereuromark** [comment]
Well, my concern is that if someone stores the actual value in a DB or otherwise, and then tries to compare with our updated (fixed) core code, it would not match anymore, right?

**Comment by othercorey** [comment]
These are only used in code to check permissions. Would be very unlikely to store our internal config name.

We can leave it until next major though.

**Comment by dereuromark** [comment]
Then it seems fine to fix up at least in 5.1, maybe before.
