### ISSUE TITLE
5.next: Add version of installed plugin to `bin/cake plugin list`

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17541]
### Description

If someone doesn't know how to get along with composer and has no working frontend to check the debug_kit it would be easiest to just put the installed version of the plugin into the already existing `bin/cake plugin list` command.

The main question is just how do we get the installed version from the plugin name / namespace.

As far as I can tell this can only work for composer packages because private plugins don't really have a version (unless we want to load the composer.json of the private plugin as well and/or load private plugins via composer)

Because via [this API ](https://getcomposer.org/doc/07-runtime.md#knowing-the-version-of-package-x) of composer we can easily get the installed version number if we know the package name.

```
+-------------------------+-----------+------------+----------+----------+
| Plugin                  | Is Loaded | Only Debug | Only CLI | Optional |
+-------------------------+-----------+------------+----------+----------+
| ADmad/Sequence          | X         |            |          |          |
| AlfredCovid             | X         |            |          |          |
| AlfredDashboard         | X         |            |          |          |
| AlfredDbIntegrity       | X         |            |          |          |
| AlfredDeploy            | X         |            |          |          |
| AlfredDns               | X         |            |          |          |
| AlfredDocumentations    | X         |            |          |          |
| AlfredDriversLogbook    | X         |            |          |          |
| AlfredEasybill          | X         |            |          |          |
| AlfredGoogle            | X         |            |          |          |
| AlfredMaintenances      | X         |            |          |          |
| AlfredMealOrders        | X         |            |          |          |
| AlfredProjects          | X         |            |          |          |
| AlfredStaffMembers      | X         |            |          |          |
| AlfredStandBy           | X         |            |          |          |
| AlfredTemplates         | X         | X          |          |          |
| AlfredTools             | X         |            |          |          |
| Authentication          |           |            |          |          |
| Authorization           |           |            |          |          |
| Bake                    | X         |            | X        | X        |
| CakeDC/Auth             |           |            |          |          |
| CakeDC/Users            | X         |            |          |          |
| CakeDumpSql             | X         |            |          |          |
| CakeSentry              | X         |            |          |          |
| Cake/TwigView           | X         |            |          |          |
| CakephpFixtureFactories | X         |            | X        | X        |
| CakephpTestSuiteLight   |           |            |          |          |
| DebugKit                | X         | X          |          |          |
| Duplicatable            | X         |            |          |          |
| IdeHelper               | X         |            | X        | X        |
| IdeHelperExtra          | X         |            | X        | X        |
| Migrations              | X         |            | X        | X        |
| Muffin/Footprint        | X         |            |          |          |
| Queue                   | X         |            |          |          |
| Search                  | X         |            |          |          |
| Setup                   | X         | X          |          |          |
| Shim                    |           |            |          |          |
| Tools                   | X         |            |          |          |
| LordSimal/CakephpDbml   |           |            |          |          |
+-------------------------+-----------+------------+----------+----------+
```

### CakePHP Version

5.1

**Comment by ADmad** [comment]
> The main question is just how do we get the installed version from the plugin name / namespace.

`vendor/cakephp-plugins.php` gives you the plugin name to path mapping.

**Comment by dereuromark** [comment]
Not sure if this could maybe add too much data and complexity into this?
For me

   composer show
   
 already gives my the info, especially

    composer show | grep dereuromark
    
etc
So there is already quite a useful tool available out of the box for the version topic

Without composer as versioning tool no doubt this would be invaluable to have :)

**Comment by dereuromark** [comment]
For me also the outdated info of

    composer outdated

is quite valuable to see where updates might be in order

**Comment by LordSimal** [comment]
Yea, I am also not sure if we want to add this kind of complexity into this command...

**Comment by LordSimal** [comment]
> `vendor/cakephp-plugins.php` gives you the plugin name to path mapping.

Unfortunately this doesn't contain the package name, otherwise this would be perfect. And I don't know a straight forward way to retrieve the composer package name from a given path.

**Comment by ADmad** [comment]
> Unfortunately this doesn't contain the package name

You can read the `composer.json` from the path.

**Comment by dereuromark** [comment]
```php
$content = (string)file_get_contents($composerFile);
$array = json_decode($content, true);
// Should be in $array['name']
```
We are doing this a lot in the toolbox already to introspect (plugin) packages

**Comment by LordSimal** [comment]
so we go from the package path to the `composer.json` to retrieve the package name so we can then check the installed version via the composer API mentioned above... quite the elaborate path to get a simple version number 😁

**Comment by ADmad** [comment]
> ...so we can then check the installed version via the composer API mentioned above

You can get the installed version from the app's `composer.lock`, no need for API.

**Comment by LordSimal** [comment]
> You can get the installed version from the app's `composer.lock`, no need for API.

By Composer API I mean the static `\Composer\InstalledVersions::getVersion('vendor/package');` which is available in all composer enabled PHP projects, not a HTTP API. 

But sure, I could just parse the composer.lock as well and read the data from there.

**Comment by markstory** [comment]
> But sure, I could just parse the composer.lock as well and read the data from there.

We already have some usage of the composer wrappers. Lets use those here as well if we can.

**Comment by markstory** [comment]
To riff on how to show more data and trying to manage complexity, should we have all the info available, but as a `plugin show <name>` command? I agree that it is a bit redundant as you could use the right composer commands, but at the same time we can provide porcelain methods if it helps us provide support easier and give people help.
