### ISSUE TITLE
 Issue with Security::decrypt() in App\Model\Entity\Member

### ISSUE THREAD

**Issue by MobileSkys** [cakephp/cakephp#17544]
### Description

1. **Environment:**
- CakePHP version: 5.0.4
- PHP version: 8.2
- Database type and version: MySQL 5.7.39
- Server type and version: Apache 2.4.54

2. **Description:**
- I'm experiencing an issue where the Security::decrypt() method seems to be ignored within the App\Model\Entity\Member class.
- The Member entity includes a method _getAddress1($value) intended to decrypt a value stored as a blob in MySQL.
- The decryption logic seems not to execute or fails silently.

3. **Steps to Reproduce:**

- Create a Member entity with the following method:
```
use Cake\Utility\Security;

protected function _getAddress1($value)
{
    if (is_resource($value)) {
        $value = stream_get_contents($value);
        fclose($value); // Close this resource after reading
    }
    return Security::decrypt($value, Security::getSalt());
}
```

- Store a blob value in the address field of a Member record.
- Attempt to access the decrypted address using $member->address1.

4. **Expected Behavior:**
- The address should be decrypted and returned correctly.

5. **Actual Behavior:**
- The decryption does not occur, or there is no visible output or error.
- Inserting a dd('STOP'); for debugging does not interrupt the execution, suggesting the method might not be called.

6. **Attempts to Resolve:**
- Ensured the method is named correctly and follows the naming conventions.
- Cleared the cache.
- Checked for errors in the logs.

7 **Additional Information:**
- The _getFullName() method in the same entity works as expected.

### CakePHP Version

5.0.4

### PHP Version

8.2

**Comment by LordSimal** [comment]
if your `$value` actually is a resource then `stream_get_contents` will [return a string](https://www.php.net/manual/en/function.stream-get-contents.php).

Therefore doing `fclose($value);` should result in an TypeError.
But since you are not even encountering that problem your accessor is not being called as you expect it or your value is not a resource.

From a naming perspective it should be fine because a Entity/DB field called `address1` will be mapped to the `_getAddress1` accessor.

Since you already cleared the cache it can't be related to the ORM caching the schema.

Therefore I am not really able to reproduce your problem currently...

**Comment by othercorey** [comment]
What value is returned by $member->addres1 ?

**Comment by MobileSkys** [comment]
[othercorey](https://github.com/othercorey)
```
<!-- /templates/Members/edit.php -->
<?= $member->address_1 ?>
```
Result : Resource id #395

**Comment by MobileSkys** [comment]
7 **Additional Information 2 :**

Possible related Issue with Baked Templates and Encrypted Fields:

Run `bin/cake bake template Members` in the terminal.

- The generated templates (edit.php, add.php, index.php, view.php) do not display encrypted fields as expected.

- Adding manually adding decryption logic to the edit.php file works as expected. For example:

```
 <!-- /templates/Members/edit.php -->
<?php
$address1 = $this->Decryption->decryptField($member->address_1);
echo $this->Form->control('address_1', ['type' => 'text', 'value' => $address1]);
?>

```
```
<?php
//App\View\Helper\DecryptionHelper.php
    public function decryptField($value)
    {
        return Security::decrypt(stream_get_contents($value), Security::getSalt());
}
?>
```
- This code successfully displays the decrypted data ('83 The Avenue').
- This discrepancy suggests that the bake console's template generation may not be handling encrypted fields appropriately or the entity's decryption method is not being invoked correctly in the baked templates.

**Possible Areas of Concern:**

- The bake console's template generation logic and its handling of encrypted fields.
- The interaction between the Entity methods and the baked templates, specifically for encrypted data.

**Comment by othercorey** [comment]
> [othercorey](https://github.com/othercorey)
> 
> ```
> 
> <?= $member->address_1 ?>
> ```
> 
> Result : Resource id #395

If the field is `address_1` not `address1` then the method name conversion might not be working.

Can you try _getAddress_1 ?

**Comment by MobileSkys** [comment]
> > [othercorey](https://github.com/othercorey)
> > ```
> > 
> > <?= $member->address_1 ?>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Result : Resource id #395
> 
> If the field is `address_1` not `address1` then the method name conversion might not be working.
> 
> Can you try _getAddress_1 ?

That worked the method is now recognised :

```
<?php
     protected function _getAddress_1($value)
     {
         if (is_resource($value)) {
             $value = stream_get_contents($value);
         }
         return Security::decrypt($value, Security::getSalt());
     }
 ?>
```

However will look into error "The data to decrypt cannot be empty" resulting from :

```
<?php
return Security::decrypt($value, Security::getSalt());
?>
```

**Comment by MobileSkys** [comment]
> > > [othercorey](https://github.com/othercorey)
> > > ```
> > > 
> > > <?= $member->address_1 ?>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Result : Resource id #395
> > 
> > 
> > If the field is `address_1` not `address1` then the method name conversion might not be working.
> > Can you try _getAddress_1 ?
> 
> That worked the method is now recognised :
> 
> ```
> <?php
>      protected function _getAddress_1($value)
>      {
>          if (is_resource($value)) {
>              $value = stream_get_contents($value);
>          }
>          return Security::decrypt($value, Security::getSalt());
>      }
>  ?>
> ```
> 
> However will look into error "The data to decrypt cannot be empty" resulting from :
> 
> ```
> <?php
> return Security::decrypt($value, Security::getSalt());
> ?>
> ```

**UPDATE For Completeness - Working Code** 
```
   //App\Model\Entity\Member.php

use App\Utility\EncryptionHelper;
    
protected function _getAddress_1($value)
    {
        $decryptedValue = EncryptionHelper::decrypt($value);
        return $decryptedValue;
    }
```
Created a App\Utility\EncryptionHelper.php

```
<?php

declare(strict_types=1);

namespace App\Utility;

use Cake\Utility\Security;
use Cake\Log\Log;

class EncryptionHelper
{
    public static function encrypt($value)
    {
        return Security::encrypt($value,  Security::getSalt());
    }

    public static function decrypt($value)
    {
        // First, read the content from the stream resource
        $encryptedData = stream_get_contents($value);

        // Check if the $encryptedData is not false or empty
        if ($encryptedData === false || empty($encryptedData)) {
            // Handle the error - the stream could not be read or is empty
            Log::error('Failed to read encrypted data or data is empty.');
            return null;
        }

        // Now, decrypt the data
        try {
            $decryptedData = Security::decrypt($encryptedData, Security::getSalt());
            return $decryptedData;
        } catch (\Exception $e) {
            // Handle the exception if decryption fails
            Log::error('Decryption failed: ' . $e->getMessage());
            return null;
        }
    }
}
```
