### ISSUE TITLE
Wrong DocComment for Cake\Routing\Route\Route::setPatterns()

### ISSUE THREAD

**Issue by Mapiiik** [cakephp/cakephp#17568]
### Description

From CakePHP 5.0.5 PHPStan reports the following:
Parameter #1 $patterns of method Cake\Routing\Route\Route::setPatterns() expects array<int, string>, array<string, string> given.

Example of code that causes an error:
```
    $builder
        ->connect('/customers/{customer_id}/contracts/{contract_id}', [
            'controller' => 'Contracts',
            'action' => 'view',
        ])
        ->setPatterns([
            'customer_id' => RouteBuilder::UUID,
            'contract_id' => RouteBuilder::UUID,
        ])
        ->setPass(['contract_id']);
```
The problem was caused by this pull request:
https://github.com/cakephp/cakephp/pull/17529

### CakePHP Version

5.0.5

### PHP Version

8.3.1

**Comment by LordSimal** [comment]
This has already been fixed via https://github.com/cakephp/cakephp/pull/17567 and will be released in the next patch release.
If you need it right now, you can adjust your composer.json to 
```
"require": {
    "cakephp/cakephp": "5.x-dev as 5.0.6",
},
"minimum-stability": "dev",
"prefer-stable": true,
```
and do a `composer update -W` to fetch the current state of `5.x` instead of the latest patch release.
