### ISSUE TITLE
Modifying Date object results in wrong date

### ISSUE THREAD

**Issue by scarabedore** [cakephp/cakephp#17571]
### Description

# How to reproduce
```php
$d = new Date('2024-01-31');
debug($d->modify('-2 month'));
```

outputs
```
object(Cake\I18n\Date) id:0 {
  'hasFixedNow' => false
  'date' => '2023-12-01'
}
```

# Expected behavior
The modified date to represent the 2023-11-30.

# Notes
This behavior is also happening on CakePHP 4.4.17 with the `FrozenDate` class.

### CakePHP Version

5.0.4

### PHP Version

8.1.17

**Comment by fabian-mcfly** [comment]
The November does not have a 31st, so PHP's date class overflows. See Example #3 on https://www.php.net/manual/en/datetime.examples-arithmetic.php

**Comment by scarabedore** [comment]
Are you writing me that `\Cake\I18n\Date` is based on PHP's `DateTimeImmutable` class, that this bug comes from `DateTimeImmutable`, and that nothing is planned to change this behavior in CakePHP?

I find very confusing that `->modify` and `->subMonths` can result in different dates:
```php
$d = new Date('2024-01-31');
$d->modify('-2 month'); // 2023-12-01
$d->subMonths(2);       // 2023-11-30
```

**Comment by fabian-mcfly** [comment]
I'm not saying anything about planned changes; I'm just a user. :)

The equivalent of `$d->modify('-2 month');` is `$d->subMonthsWithOverflow(2)` (https://api.cakephp.org/chronos/3.x/class-Cake.Chronos.Chronos.html#subMonthsWithOverflow()).

Imho there is no right or wrong in such cases, especially when doing something like this:

```php
$d = new Date('2023-03-31');
$d->modify('-1 month');

$d = new Date('2023-03-30');
$d->modify('-1 month');

$d = new Date('2023-03-29');
$d->modify('-1 month');
```

Without overflow, all of them would result in `2024-02-28` which can be the desired result. Another one could argue that in those three examples, the results should be `2024-02-28`, `2024-02-27` and `2024-02-26`, depending on the POV and use case.

**Comment by othercorey** [comment]
Date extends ChronosDate which does use modify() to implement addMonths/subMonths, but it performs this fix-up afterwards:

```php
        if ($date->day !== $day) {
            return $date->modify('last day of previous month');
        }
 ````
 
 Chronos and ChronosDate use DateTimeImmutable::modify() so the behavior comes from PHP.

**Comment by markstory** [comment]
2024 is also a leap year, and your operation crosses February, so month manipulations get strange

**Comment by scarabedore** [comment]
Thank you for finding out PHP is the root cause. Just to make this clear to me: Is it expected behavior for ChronosDate?

**Comment by markstory** [comment]
Yeah, it is expected behavior for both ChronosDate and PHP's datetime library.
