### ISSUE TITLE
Add replace argument to IntegrationTestTrait::configRequest

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#17587]
### Description

If I have a common configured request in my `setUp` method such as

```php
    public function setUp(): void
    {
        parent::setUp();
        $this->requestAsJson();
        $this->configRequest([
            'headers' => [
                'Authorization' => 'Bearer ' . (new JwtHelper())->withSubscriptions([SubscriptionPlanEnum::STARTER]),
            ]
        ]);
```

And need to replace it only in a few instances such as:

```php
    public function test_index_with_growth_plan(): void
    {
        $this->configRequest([
            'headers' => [
                'Authorization' => 'Bearer ' . (new JwtHelper())->withSubscriptions([SubscriptionPlanEnum::GROWTH]),
            ]
        ]);
```

This adds two bearer tokens because `configRequest()` uses `array_merge_recursive()`. Adding a `$replace` bool argument that defaults to `false` but uses `array_replace_recursive()` if true would be a nice option here rather than having to manually clear the `$this->_request` property in these cases.

Unless there is another way to accomplish this... and yes I understand this is next level laziness, but this appears to be how it worked in CakePHP 4.

### CakePHP Version

5.0

**Comment by markstory** [comment]
> This adds two bearer tokens because configRequest() uses array_merge_recursive(). Adding a $replace bool argument that defaults to false but uses array_replace_recursive() if true would be a nice option here rather than having to manually clear the $this->_request property in these cases.This adds two bearer tokens because configRequest() uses array_merge_recursive(). Adding a $replace bool argument that defaults to false but uses array_replace_recursive() if true would be a nice option here rather than having to manually clear the $this->_request property in these cases.

What if we had a `$this->resetRequest();` method to reset the request? I think that would be clearer to read, and not much harder to write especially with autocomplete.

**Comment by cnizzardini** [comment]
This amounts to a wrapper around `$this->_request = []`. It is cleaner than working directly with an underscored property, but still requires rebuilding the entire request. I don't want to harp on this too much as this is a minor gripe. I leave this call to you.

**Comment by markstory** [comment]
> It is cleaner than working directly with an underscored property, but still requires rebuilding the entire request. 

That's fair. Would having a method that does the replacement work instead? Perhaps `replaceRequest`? 🤷

**Comment by cnizzardini** [comment]
`replaceRequest` is probably the cleanest approach of all rather than mangling an existing method.

**Comment by cnizzardini** [comment]
Would you say this method should clear the request and then add? Or should it do an array_replace_recursive?

**Comment by markstory** [comment]
> Would you say this method should clear the request and then add? Or should it do an array_replace_recursive?

A recursive replace is likely the most ergonomic solution. It emulates 'merging' without the tedious duplicate values that merging arrays can create.

**Comment by cnizzardini** [comment]
Is there a specific reason this is targeted as a 5.1 minor feature. Does Cake strictly put features into minors and fixes into revisions? Only curious.

**Comment by cnizzardini** [comment]
Also I briefly looked at doing this, the solution is obvious, the question is what kind of tests would be involved here. There doesn't seem to be tests specifically for configRequest, despite it clearly being covered via its use within tests.

**Comment by markstory** [comment]
> There doesn't seem to be tests specifically for configRequest, despite it clearly being covered via its use within tests.

I'm ok with the implicit testing. If the sample controller method would not generate the correct response if the tokens were present then we have a good integration test that can be documented as to what it covers.

**Comment by mcube27** [comment]
It it possible to ask why it was changed to a `array_merge_recursive`? Does it help in some tests ? If yes how ?

I have a lot of tests where I have simply overwritten the request with this->configRequest() in CakePhp4 and I don't understand the benefit of the change ?

**Comment by LordSimal** [comment]
It was changed in this PR https://github.com/cakephp/cakephp/pull/16942 to actually allow merging data when calling `$this->configRequest()` multiple times (which was needed to actually allow `requestAsJson()` to work)

If you desire to reset the request config you can easily call `$this->_request = []` yourself as well.
