### ISSUE TITLE
Consider adding an 'alwaysContain' or 'eagerLoad' property to associations

### ISSUE THREAD

**Issue by jamisonbryant** [cakephp/cakephp#17581]
## The Problem

In CakePHP, entity association properties will be null if the user did not elect to “contain” that association when the base entity was fetched from the database:

```php
$accessToken = $this->AccessTokens->get('some uuid');

isset($accessToken->user);    // true
isset($accessToken->client);  // true

$accessToken = $this->AccessTokens->get('some uuid', [
    'contain' => 'Users.Roles',
]);

isset($accessToken->user);          // false
isset($accessToken->user->role);    // false
isset($accessToken->client);        // true
```

The reason for this is that associations in Cake are “eager loaded”, meaning they aren’t loaded unless the user specifically requested them to be loaded (with methods/options like `contain` or `loadInto`).

But what if, according to business rules, that entity’s association should NEVER be null? In the case of an AccessToken (the model shown above), it can *never* exist in the database without an associated User (because who does the token belong to?). Along the same lines, a User can NEVER exist without a Role (because then how would we know what they can access?) These restrictions are enforced in the database by enforcing non-nullability on the database fields themselves:

```php
create table access_tokens
(
    oauth_token varchar(100) not null
        primary key,
    client_id   char(36)     not null,        /* NULL NOT ALLOWED */
    user_id     char(36)     not null,        /* NULL NOT ALLOWED */
    expires     int          not null,
    scope       varchar(255) null
);
```

So we have a quandary: if `$accessToken->client` is null, is it because the association was not *loaded* when the entity was fetched from the database? Or is it because *there is no association* to load because the entity’s foreign key for that association itself is null? This is especially problematic when making heavy use of type annotations in the entity classes:

```php
/**
 * AccessToken Entity
 *
 * ...other props and stuff
 *
 * @property \App\Model\Entity\User|null $user
 * @property \App\Model\Entity\Client $client
 * 
 * ...more props and stuff
 */
class AccessToken extends Entity
{
```

In the above code, you can see that we’ve annotated `AccessToken::$user` to be nullable, because the property may indeed be null if we haven’t loaded it, but the database column is strictly not-nullable. The only reason that `AccessToken::$client` isn’t similarly labeled is because we don’t reference the client much in our code, so we haven’t needed to update it yet.

(as an aside, we manage most/all of our entity annotations with Mark’s [cakephp-ide-helper](https://github.com/dereuromark/cakephp-ide-helper) plugin, which [I believe] checks the schema field’s nullability to determine if the associated entity should be marked nullable or not)

This causes all kinds of confusion with static analysis tools like PHPStan. Consider this code:

```php
protected function _getRoleType(): ?RoleType
{
    $slug = $this->user?->role?->slug;
    if (!$slug) {
	return null;
    }

    $role = RoleType::fromSlug($slug);
    if (!$role) {
        return null;
    }

    return $role;
}
```

In the above code, `$this->user?->role->...` is using [null coalescing](https://www.tutorialspoint.com/php7/php7_coalescing_operator.htm) to handle if any object in the chain is null, return null for the whole chain. This is necessary because the user *might* be null, but our database says it should *never* be. If we annotate the `$user`  property to be non-nullable (like the database says) and we were to remove the `?` after `user` (because it can “never” be null) we get PHPStan complaining with messages like this:

```php
------ --------------------------------------------------------------------------------------------
  Line   Model/Entity/AccessToken.php
 ------ --------------------------------------------------------------------------------------------
  89     Using nullsafe property access on non-nullable type App\Model\Entity\User. Use -> instead.
 ------ --------------------------------------------------------------------------------------------
```

### Just Eager Load Everything

Some in the Cake community believe that you should just `contain()`  what you need, ALWAYS. The problem arises with applications that rely heavily on type safety/nullability checks. In other words, if I am Service X and I require an AccessToken to do my job, how do I KNOW that the token has the associations already loaded? Just to be safe, should I load them again? What if I load them again but they were already loaded to begin with? And furthermore, if the property is NOT null, how do I know it’s the correct data? The freshest?

### Community Plugins

There are some community plugins out there, like [cakephp-lazyload](https://github.com/jeremyharris/cakephp-lazyload), that will detect when an entity association property is accessed, is null, and has a non-null foreign key and if so will load it for you automatically. The problem with this type of plugin is 1) it can be VERY overzealous…unintentional loads all over the place and 2) the extra queries being executed are quite hidden from the user which can make it confusing to track down where these extra queries originate.

### Specify Which Associations to ‘Always Load’

What if, when configuring the associations for a Table, you could specify an optional key like `alwaysLoad`  or `eagerLoad` which tells Cake to ALWAYS contain/join that record if the foreign key is non-null, and if an associated entity fails to exist, an exception is thrown? I believe this solution is a decent one because it gives the power to the developer to *ensure* the association is loaded always as it should be, in other words “if this association is not loadable, the database/entity is in an invalid state and something needs to be done about it”.

## Summary

Developers need a way to know if a particular entity property is null because it wasn't loaded, or if it is null because the association cannot be made because of a foreign key being null. An additional key on the association configuration methods like `belongsTo()` or `hasMany()` that would allow the developer to say "always load this when I pull the main entity, and if you can't then throw an exception" would be very beneficial for applications like mine that make heavy use of type checking and null safety.

### CakePHP Version

5.1

**Comment by dereuromark** [comment]
There are quite a few topics in here.
I would say that using `?->` blindly is indeed a code smell, as PHPStan points out.
I never needed it in my code so far, trying to be more clear on the actual keys/props being present or not.

> which [I believe] checks the schema field’s nullability to determine if the associated entity should be marked nullable or not)

Yes, and I think that makes sense. As that would be the expected scenario if that relation is joined in or that entity present in general as a whole.
Indeed, any property/field even could always be null (e.g. partial write/read).
So those are of course only the base expectation in general.

Did you try using
- has() vs hasValue()

The former is exactly for this case: Where you might have a null value (and has Value() would return false), but a property has been set/loaded, as such has() actually makes exactly that distinction you aim at.
```php
    $loadedButNull = $entity->has($field) && !$entity->hasValue($field);
```
As for your solutions:
I dont think they are valid in this case, they would shoot over the target.

You will always either have the tools complaining here if you annotate it truthfully (`type|null`) or you will trip over the code in production despite proper validation and tests due to the hidden "lie".

My tip: Try to use the `getOrFail` pattern as much as possible where you expect a not-null return value and otherwise explicitly check on `!== null` and throw respective exceptions here.

Especially around entities and their fields it is often impossible to have the annotations be "correct" for all cases.
Even "required" fields can be empty (null) if not pulled (selected fields) from the DB. So for cases like these it can be useful to leverage the [Shim plugin enhancements](https://github.com/dereuromark/cakephp-shim/blob/master/docs/Model/Entity.md):
```php
use Shim\Model\Entity\GetSetTrait;

class MyEntity extends Entity {

    use GetSetTrait;
```
Now you can use these methods on values that are expected to be present:
```php
$entity->getOrFail('field'); // Cannot be null
$entity->getFieldOrFail(); // Cannot be null
```

With chaining now both the PHPStan analyzer is happy, and your code would throw a clear exception in the case that never should happen: It not being there despite the clear logical requirement in this case.

**Comment by markstory** [comment]
> An additional key on the association configuration methods like belongsTo() or hasMany() that would allow the developer to say "always load this when I pull the main entity, and if you can't then throw an exception" 

I think the concept of 'always eager load an association' makes sense in the small scale but creates opportunities for cyclic dependencies. The ORM will not be able to solve these scenarios in a performant way.

> But what if, according to business rules, that entity’s association should NEVER be null? In the case of an AccessToken (the model shown above), it can never exist in the database without an associated User (because who does the token belong to?).

If your application domain has these constraints you will likely need to build abstractions on top of the ORM to ensure these invariants are upheld. By having wrappers around the ORM you can ensure that your required relations are always loaded.

**Comment by markstory** [comment]
A potential way you can help improve your type safety and find and diagnose loading errors is to make them fatal errors. If you make your relation attributes nullable, I think there is a path to getting static typing to work and have runtime assertions that you can validate your application with during tests or in production.

First you would need to make the relation attribute nullable, as that is what it really is, even if the column is not null, the *relation is*.

```php
/**
 * @property \App\Model\Entity\Client|null $client
 */
```

Then before you use a property include an assertion: 

```php
assert(isset($user->client));
```

Using `assert` allows you to indicate to static analysis that this property does exist.
If you have decent test coverage you can enable assertions to raise during tests, and be able to validate that your application is running correctly and doesn't regress.

I can see the assertion needing to be used being tedious as it could be needed in many places, but it is a nice way to solve both static and runtime errors.

**Comment by jamisonbryant** [comment]
> There are quite a few topics in here.

Yes, although they all circle around a central theme, in my view, which is: "What do we do when the business logic says something cannot be nullable but Cake doesn't load it unless specifically requested, therefore it is null?"

I appreciate everyone's feedback, there are a lot of good ideas in here.

> I think the concept of 'always eager load an association' makes sense in the small scale but creates opportunities for cyclic dependencies.

True, I didn't consider this point. Well said.

> If your application domain has these constraints you will likely need to build abstractions on top of the ORM to ensure these invariants are upheld

This is pretty much the solution we're using now, although more as a service layer than an ORM wrapper. It make me wonder, as a 10+ year Cake user, if there is a "Cakier" way to solve this problem. If the answer is no/not yet, that's fine!

> First you would need to make the relation attribute nullable, as that is what it really is, even if the column is not null, the relation is.

I think this is an important point: everything everywhere is null, because you can't count on `contain()` being called.

> Then before you use a property include an assertion ...

This is a good idea, and something we tried, except we shied away because the PHP docs explicitly state "[Assertions should be used as a debugging feature only.](https://www.php.net/manual/en/function.assert.php#:~:text=Assertions%20should%20be%20used%20as%20a%20debugging%20feature%20only)" I know the Cake codebases use `assert()` pretty frequently, so I'm curious if other devs think that maybe we shouldn't follow PHP's advice on this and/or if folks are disabling `assert()` in production like it's "designed to be"?

> So for cases like these it can be useful to leverage the [Shim plugin enhancements](https://github.com/dereuromark/cakephp-shim/blob/master/docs/Model/Entity.md)

This is really intriguing, as I was not aware of this plugin prior to your comment. It seems like it would be an alternative to heavy `assert()` usage _if_ PHPStan is OK with it. Certainly something to try.

I can see there's nothing for Cake to do here because my suggestions don't work at scale and there are a myriad of alternative solutions available, so I'm OK to close this ticket or continue the discussion in support forums if desired :)

**Comment by markstory** [comment]
> This is pretty much the solution we're using now, although more as a service layer than an ORM wrapper. It make me wonder, as a 10+ year Cake user, if there is a "Cakier" way to solve this problem. If the answer is no/not yet, that's fine!

I think this is the solution for now. We've been avoiding making framework abstractions around application domain as it isn't consistent and doesn't have good interfaces that we can provide. Using the DI container and framework traits to create domain services is the current 'best' solution.

> This is a good idea, and something we tried, except we shied away because the PHP docs explicitly state "[Assertions should be used as a debugging feature only.](https://www.php.net/manual/en/function.assert.php#:~:text=Assertions%20should%20be%20used%20as%20a%20debugging%20feature%20only)" I know the Cake codebases use assert() pretty frequently, so I'm curious if other devs think that maybe we shouldn't follow PHP's advice on this and/or if folks are disabling assert() in production like it's "designed to be"?

If you have sufficient test coverage wouldn't the usage of `assert()` be for debugging? I can't speak for others, but personally I leave `assert` off in production and aim to have high enough test/scenario coverage that I know my asserts are working.

**Comment by dereuromark** [comment]
Sounds like we can close this as this has been discussed, and nothing to be done here now for the core.
A few more tips are added @ https://www.dereuromark.de/2024/03/19/cakephp-and-static-analyzers/

**Comment by jamisonbryant** [comment]
Thanks for the discussion, and for the link. Very interesting read.
