### ISSUE TITLE
Problem formatting milliseconds using i18nFormat

### ISSUE THREAD

**Issue by freefri** [cakephp/cakephp#17604]
### Description

I am facing similar problem to https://github.com/cakephp/cakephp/issues/10439 when formatting using the function `i18nFormat`

This line https://github.com/cakephp/cakephp/blob/1daf3c0854c139bac85d3535505cef6154f9d164/src/I18n/DateFormatTrait.php#L104 could be changed to `return (string)static::$formatters[$key]->format($date->format('U.u'));` to allow microseconds when formatting. This should not be a breaking change, since the date us already formatted again within the same line, but I am not sure if this could cause any new problem. 

This is a quick test:

```
$time = new FrozenTime('2014-07-06T13:09:01.523000+00:00');
$this->assertEquals('2014-07-06 13:09:01.523000', $time->format('Y-m-d H:i:s.u'));
$i18nFormat = $time->i18nFormat("yyyy-MM-dd'T'HH':'mm':'ss.SSSxxx", null, 'en-US');
$this->assertEquals('2014-07-06T13:09:01.523+00:00', $i18nFormat); // this will fail returning 2014-07-06T13:09:01.000+00:00
```

This is hapening in many different cakephp versions including 4.x and 5.x and it is independent from php version used

### CakePHP Version

4.4.0

### PHP Version

7.4

**Comment by ADmad** [comment]
The ticket you have referenced relates to saving value to datetime columns with milliseconds. Have you mapped your column to the `datetimefractional` type in table schema?  (This type didn't exist in CakePHP 3.x).

**Comment by ADmad** [comment]
NVM, I see now that the issue is limited to just formatting. The change looks fine to me.

**Comment by freefri** [comment]
Fix released in released in https://github.com/cakephp/cakephp/releases/tag/5.0.6 waiting for future release 4.5.5
