### ISSUE TITLE
Schema setColumnType silent no-op

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17618]
### Description

For an upgrade script I wanted to dynamically switch the column type after fetching and before saving.
After debugging why things don't work I found out that setColumnType() is actually a silent no-op if already built.
```php
// was "json"
$table->getSchema()->setColumnType($column, 'json_new');

// still "json"
dd($table->getSchema()->getColumnType($column));
```

There must be reason, otherwise we could have allowed this overwrite here.
        
While it might not be possible to dynamically do this, maybe it should throw an exception instead?
So that the developer knows this will not do anything?
Or maybe at least if the type mismatches the currently configured one?

### CakePHP Version

5.x

### PHP Version

8.2

**Comment by ADmad** [comment]
Looking at the code, the method is a no-op only if the column doesn't already existing in the schema, the specified type is always set if it exists.

Given your use case it might be possible you are trying to set that type before the schema has been read from the db, making your call a no-op and later it gets populated based on the db type.

**Comment by dereuromark** [comment]
I found a different way for me

So only issue left is to check if we need to be more verbose in feedback here, otherwise we can close

**Comment by ADmad** [comment]
Given that we have a `hasColumn()` method, making `setColumnType()` throw an exception for a non existent column seems reasonable to me. If there's a consensus we can do so for 5.1.
