### ISSUE TITLE
Strpos result comparison

### ISSUE THREAD

**Issue by yannouche34490** [cakephp/cakephp#17625]
https://github.com/cakephp/cakephp/blob/fe40e4f94c151c734768b93860634adfc4750688/src/Console/BaseCommand.php#L49

### Description

Hello,

when you make comparison between strpos result and 1, PHP will cast the result to a int even if function returns false. It can result an unexpected true comparison. 

Best regards.

### CakePHP Version

4.4.0

### PHP Version

8.2

**Comment by dereuromark** [comment]
Is it actually a Bug? From what I understand this is intentional here

**Comment by ADmad** [comment]
The check is to throw an exception if a space is found at the first position (strpos will return 0) or if the name does not have a space (strpos will return false) and it works as intended.

**Comment by yannouche34490** [comment]
> The check is to throw an exception if a space is found at the first position (strpos will return 0) or if the name does not have a space (strpos will return false) and it works as intended.

If strpos returns false, it will be casted as int
You can find a simple workaround here https://onlinephp.io/c/3d888

**Comment by dereuromark** [comment]
We know :) And as just explained to you in detail, this is intended here as part of the condition. So all is good.

**Comment by yannouche34490** [comment]
> The check is to throw an exception if a space is found at the first position (strpos will return 0) or if the name does not have a space (strpos will return false) and it works as intended.

Oh by mad, I didn't think things like that.
