### ISSUE TITLE
Double loading of plugin

### ISSUE THREAD

**Issue by mike-kelly** [cakephp/cakephp#17627]
Due to a user error, I had `$this->addPlugin('Authorization');` at the end of my `getAuthenticationService` function in Application.php, as well as in its correct location in the `bootstrap` function. This caused errors complaining about the lack of authorization policies defined for various entity tables. I am using entity authorization policies but not table policies in my app.

Obviously this is a wholly avoidable error but I thought I would share this info in case others report similar errors, or if there was a way of preventing the plugin from being added twice.

**Comment by dereuromark** [comment]
Maybe adding a plugin twice should throw an exception or at least warning in general.
But that would be sth that should be done in the core then.
