### ISSUE TITLE
Strange side effects of 5.0.7

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17655]
### Description

https://github.com/dereuromark/CakePHP-DatabaseLog/actions/runs/8582848427/job/23521405236
```
1) DatabaseLog\Test\TestCase\Controller\LogsControllerTest::testDelete
Failed asserting that 4 is identical to 0.

/tests/TestCase/Controller/LogsControllerTest.php:107
```
Those started to fail with the release of 5.0.7 now

Nothing changed, it also only seems to happen for SQlite

From the changes I cannot directly see how this makes sense.
https://github.com/cakephp/cakephp/compare/5.0.6...5.0.7

But it seems there is some unintended side effect here in the changes.

### CakePHP Version

5.0.7

### PHP Version

8.2

**Comment by dereuromark** [comment]
Looking into what those extra logs are it seems super weird ones:
```
MissingTemplateException - Failed to render error template `error400`. Error: Template file `Admin/Error/error400.php` could not be found.

The following paths were searched:

- `/work/devilbox/data/www/sandbox/vendor/dereuromark/cakephp-databaselog/tests/test_app/templates/plugin/DatabaseLog/Admin/Error/error400.php`
- `/work/devilbox/data/www/sandbox/vendor/dereuromark/cakephp-databaselog/templates/Admin/Error/error400.php`
- `/work/devilbox/data/www/sandbox/vendor/dereuromark/cakephp-databaselog/tests/test_app/templates/Admin/Error/error400.php`
- `/work/devilbox/data/www/sandbox/vendor/dereuromark/cakephp-databaselog/vendor/cakephp/cakephp/templates/Admin/Error/error400.php
```

I did create the actual templates in `tests/test_app/templates/Error/`
The Admin prefix seems weird here.

**Comment by dereuromark** [comment]
So the issue was already there before, just not visible without the logs being written.
Now that they are these issues show up.
https://github.com/dereuromark/CakePHP-DatabaseLog/pull/51 fixes it, so it begs the question why the Admin/ prefixed ones are necessary in the first place.
So far usually the templates for error logs are always without the prefix.

If we allow Admin/ ones to be looked for first, the fallback should still be the former ones (normal, without prefix) I imagine.

**Comment by markusramsak** [comment]
A similar weird issue exists if you use the FormProtection Component in the initialize() method.
If it throws (i.e. make a POST request with wrong data) I always get a log entry like:
Failed to construct or call startup() on the resolved controller class of `App\Controller\ErrorController`. Using Fallback Controller instead. Error Form tampering protection token validation failed.

```
public function initialize() {
      $this->loadComponent('FormProtection');
}
```

my error controller looks like:

```
declare(strict_types=1);

namespace App\Controller;

use Cake\Core\Configure;

class ErrorController extends AppController
{
    public function beforeRender($event)
    {
        $this->viewBuilder()->setTemplatePath('Error');
    }
}
```

I solved this by changing the ErrorController to:

```
declare(strict_types=1);

namespace App\Controller;

use Cake\Core\Configure;

class ErrorController extends AppController
{
    public function initialize(): void
    {
        Configure::write('isErrorController', true);
        parent::initialize();
    }

    public function beforeRender($event)
    {
        $this->viewBuilder()->setTemplatePath('Error');
    }
}
```

and my AppController to:
```
public function initialize() {
      if (!Configure::read('isErrorController')) {
          $this->loadComponent('FormProtection');
      }
}
```

Is there a better to solve this or is this the only solution if I want to use my custom AppController?

**Comment by markstory** [comment]
> Is there a better to solve this or is this the only solution if I want to use my custom AppController?

There isn't a significantly better solution. If you have `FormProtectionComponent` enabled it wants to do its thing on every controller action and `ErrorController` is a controller. I personally don't include components that will cause problems in error handling in `AppController`. Another solution that I prefer is

```php
class ErrorController extends AppController
{
    public function initialize(): void
    {
        parent::initialize();
        $this->components()->unload('FormProtection')
    }

    public function beforeRender($event)
    {
        $this->viewBuilder()->setTemplatePath('Error');
    }
}
```

I prefer this solution as it doesn't introduce additional global state.

**Comment by markstory** [comment]
Going to close this as there hasn't been any further discussion and two solutions have been proposed.
