### ISSUE TITLE
Adding ORM rules with the same name overrides previous one without warning

### ISSUE THREAD

**Issue by nicosp** [cakephp/cakephp#17669]
### Description

We have a lot of ORM rules with duplicate names which is not ideal but it used to work until 4.5. On upgrade to 5.0 rules with the same name get replaced and we get strange behavior with rules not being triggered. The ORM should give an indication that a rule was overriden with an exception to avoid hard to detect bugs.

### CakePHP Version

5.0

### PHP Version

8.2

**Comment by nicosp** [comment]
I can help with this but I don't want to start working unless there is an agreement. My preference is to simply throw an exception for duplicate names. IMO it's preferable to have easily detectable failures rather than subtle business logic failures.

**Comment by ADmad** [comment]
Throwing an exception sounds reasonable,  you can make a PR targeting the 5.next branch.
