### ISSUE TITLE
The 'selected' option has been removed from FormHelper.

### ISSUE THREAD

**Issue by EduardPDB** [cakephp/cakephp#17661]
### Description

Until cakephp 3 in cakephp 2 'selected' could be used as an option for the select, checkbox and radio inputs.
Now this option doesn't exist on cakephp 3 and above.

### CakePHP Version

3.9.0

### PHP Version

7.4

**Comment by markstory** [comment]
Why is this a bug? `selected` was replaced with `value`.

**Comment by EduardPDB** [comment]
Thank you for clarification.
