### ISSUE TITLE
CakePHP Cookbook outdated?

### ISSUE THREAD

**Issue by woodholly** [cakephp/cakephp#17667]
### Description

I am new to cakephp and CakePHP Cookbook Documentation examples are half-working.
Page 60-68, tags are not saved, selected tags are not shown.
Please don't ask me to fix it, I have no idea what I am doing there.

### CakePHP Version

5.1

### PHP Version

8.2

**Comment by othercorey** [comment]
What is the link to the page with this bad example.

**Comment by woodholly** [comment]
https://book.cakephp.org/5/_downloads/en/CakePHPCookbook.pdf
Tags and users, page 61+

**Comment by dereuromark** [comment]
For Tags you can also look into
https://github.com/dereuromark/cakephp-tags
Maybe that offers also some insights.

**Comment by markstory** [comment]
I went through the process of upgrading the cms-tutorial example app and got a working tag workflow. I've mentioned this issue with a specific commit. Could you double check that you have all of that code and test again?

**Comment by markstory** [comment]
Going to close this as it has been a while and we haven't heard back about the changes that were made. I've posted a link to the completed sample application. If you try it and it doesn't work, please open an issue there and we'll figure it out.
