### ISSUE TITLE
jsonSerialize that runs into an Exception does not keep the Exception message, shows generic error instead

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17689]
### Description

What I have
--

I have a custom class that implements `\JsonSerializable`.

In a controller that initialises and uses this class, I pass it to the view with the `_serialize` option.

```
$this->set([
    'report' => $report,
    '_serialize' => 'report',
]);
```

The route is configured to look for `.json` extension. 

- If the request is `/controller/action.json`, the response will be in JSON, serialising the class, i.e. triggering its `jsonSerialize()` method.
- And if the request is simply `/controller/action`, I have the class rendered in a corresponding view template.

What is the problem
--

I added some if/else checks to this class, and if one of them fails, it throws a `new \Cake\Http\Exception\InternalErrorException()` with a detailed error message explaining what went wrong.

If I access it via `/controller/action`, I do get the red page with the error message I wrote. So far so good.

If I, however, access my URL as `.json`, the resulting JSON does not carry over the error message:

```
{
    "message": "Failed calling My\\Class\\Path::jsonSerialize()",
    "url": "/controller/action.json",
    "code": 500,
    "file": "\/var\/www\/app\/vendor\/cakephp\/cakephp\/src\/View\/JsonView.php",
    "line": 152
}
```

What I want
--

Is there any way to have the error message carried over to JSON output?

(I do understand I'm on an older version - has this been fixed in the recent versions?)

### CakePHP Version

3.10

### PHP Version

5.6

**Comment by othercorey** [comment]
Is it throwing a JsonException? If so, is the previous exception set?

There is a new wrapper exception in 4.0, but I suspect it's just wrapping the same exception you're seeing.

**Comment by mehov** [comment]
Hi and thank you for taking a look at this

> Is it throwing a JsonException?

My custom class is throwing `\Cake\Http\Exception\InternalErrorException`.

After reading your comment, I wanted to try and have it throw the `\JsonException` you mentioned, but PhpStorm says *'JsonException' is available starting with 7.3 PHP version*. So I haven't even tried.

**Comment by mehov** [comment]
I poked around `JsonView.php:152` in `3.x`.

https://github.com/cakephp/cakephp/blob/ffe95db83c37e1039c97664125d604363faf1a08/src/View/JsonView.php#L152

For debugging purposes, I changed that to:

    try {
        $encode_result = json_encode($data, $jsonOptions);
    } catch (\Exception $e) {
        debug($e->getPrevious()->getMessage());
        exit;
    }
    return $encode_result;

As a result, I am getting my '*original*' error message. But I am not sure how do I have it forwarded to the JSON output.

**Comment by othercorey** [comment]
I think you'll have to customize it to encode the previous error message if the previous is the custom exception.

In 4.0, it throws a SerializationFailureException that we might be able use to custom the rendering:
https://github.com/cakephp/cakephp/blob/4.x/src/View/SerializedView.php#L116

For 3.0, I think you have to try to catch the exception thrown by json_encode() in the exception handling/rendering.

**Comment by mehov** [comment]
> For 3.0, I think you have to try to catch the exception thrown by json_encode() in the exception handling/rendering.

This is what I ended up doing: just manually catch the `\Exception`, get the original, and re-throw it. Gets the job done for now. Thank you for leading me to the solution!

My current hotfix solution for 3.x:

    /*
     * If there's an exception thrown somewhere during serialisation,
     * _serialize will front with a generic error message that says
     *
     * > Failed calling KPI\Reports\Results\Example::jsonSerialize()
     * > \Exception
     *
     * Do json_encode manually, to catch original exception (if any) here
     */
    try{
        $result_json = json_encode($obj);
    } catch(\Exception $e) {
        // Re-throw the original exception here, stopping the action
        $original_error_msg = $e->getPrevious()->getMessage();
        throw new \Cake\Http\Exception\InternalErrorException($original_error_msg);
    }
    if ($this->getRequest()->isJson()) {
        // Reply with resulting JSON that we already have from manual encode
        // (This is kinda ugly and loses JSON indentation in debug mode, but
        // not stopping here and serializing the usual way below would
        // unnecessarily re-process the object one more time)
        return $this->getResponse()
            ->withType('application/json')
            ->withStringBody($result_json);
    }

The above replaces serialising the 'usual' way:

    $this->set([
        // Encoding to JSON triggers jsonSerialize() on the object
        'obj' => $obj,
        '_serialize' => 'obj',
    ]);

**Comment by mehov** [comment]
I was too fast closing the issue. If I'm re-reading it right, in 4.0 while yes this is doable, it is still not implemented. So then passing over the underlying exception message to the outside JSON exception would be helpful to have. I'll reopen, and you guys can close on your discretion.

**Comment by othercorey** [comment]
I'm not sure what the expected behavior is for exceptions thrown here. 4.0 simply wraps the exception caught, so you'd have a more specific exception to configure in the new handler.

Basically, it's unserializable.

maybe @markstory knows

**Comment by markstory** [comment]
> I'm not sure what the expected behavior is for exceptions thrown here. 4.0 simply wraps the exception caught, so you'd have a more specific exception to configure in the new handler.

The wrapping exception contains the previous/source error. That should be included in stack traces that are logged and development error pages.

**Comment by ADmad** [comment]
Given that a `JsonException` is thrown now if `json_encode()` fails, there's nothing to be down here. It's up to PHP to include the previous exception if any in the `JsonException` it throws.
