### ISSUE TITLE
Official way to setup global events which are testable out of the box

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17694]
### Description

As just discussed in Slack/Discord there is no proper/official place to setup global event listeners which are also testable out of the box.

Why? Bootstrapping is done for each integreation method being called inside a test as you can see [HERE](https://github.com/cakephp/cakephp/blob/5.x/src/Http/Server.php#L122-L125)

Because the `config/bootstrap.php` is loaded via a `require_once` in [HERE](https://github.com/cakephp/cakephp/blob/5.x/src/Http/BaseApplication.php#L183) and the EventManager is being reset on each test in [HERE](https://github.com/cakephp/cakephp/blob/5.x/src/TestSuite/TestCase.php#L210)

---

A "workaround" has been found by Zuluru via adding the Listeners to the `pluginBootstrap` hook instead of the "usual" bootstrap hook since [it doesn't have a require_once call](https://github.com/cakephp/cakephp/blob/5.x/src/Http/BaseApplication.php#L197-L199). But thats not really ideal imho.

---

Another workaround would be to require the `config/events.php` (or wherever you put your global event listener) inside the `Application::bootstrap` like right bellow [HERE](https://github.com/cakephp/app/blob/5.x/src/Application.php#L56)

Its just confusing and maybe a bit weird that you should NOT put initialization code inside the `config/bootstrap.php` since its only loaded once per execution and therefore won't work/do its job in a full PHPUnit test run.

---

Sure, its a special case because in "normal" request situations this is not a problem. But for testing purposes its pretty confusing imho. 

--- 

My proposal would be another method inside the `Application` class since its the "mother of basically everything" and already defines other shared resources like `services` which are shared across the application (Web and CLI based of course).

### CakePHP Version

5.next

**Comment by markstory** [comment]
> My proposal would be another method inside the Application class since its the "mother of basically everything" and already defines other shared resources like services which are shared across the application (Web and CLI based of course).

We could have a new hook method on `Application` and `Plugin` for attaching global events, it could be triggered after services are registered.
