### ISSUE TITLE
\Cake\Core\env() does not return the same value as written in the .env file.

### ISSUE THREAD

**Issue by yu46** [cakephp/cakephp#17695]
## Description.
In CakePHP 4.5, there seems to be an inconsistency in the `env()` function when retrieving values from `.env` files. If a boolean value false is written in the `.env` file without quotes, the `env()` function returns an empty string ('') instead of the boolean value false as expected.

## Steps to reproduce

1. Write a boolean value `false` without quotes in the `.env` file, e.g., `DEBUG=false`.
2. Attempt to retrieve this value using `env('DEBUG')`.
3. Instead of returning false, the function returns an empty string.

## Expected Behavior
The expected behavior is for the `env() ` function to accurately reflect the values specified in the `.env `file. Therefore, if the `.env `file contains the value false, it is expected that the `env()` function returns false, rather than an empty string.

In CakePHP 4.2 it returned false

## Suggested Solution

This problem may be caused by a comparison error in the env() function. Maybe the comparison $val == null is causing the problem. Perhaps $val === null might be better used. Therefore, the suggested fix is to change the comparison statement from:

```
if ($val == null && $_ENV[$key] !== false)
```

to:

```
if ($val === null && $_ENV[$key] !== false)
```

https://github.com/cakephp/cakephp/blob/4.5.5/src/Core/functions.php#L199

### CakePHP Version

4.5.5

### PHP Version

8.0.30

**Comment by markstory** [comment]
What is in `$_ENV` and your `$_SERVER` when your `.env` file contains `DEBUG=false`? I looked at our tests and we have coverage for 

```php
        $_ENV['EMPTY_VALUE'] = '';
        $this->assertSame('', env('EMPTY_VALUE'));
        $this->assertSame('', env('EMPTY_VALUE', 'default'));
```

Which seems similar to your scenario. This test has been in-place for [many years](https://github.com/cakephp/cakephp/commit/f3f716eda66), and we can't change the behavior at this point without causing breakage in other people's applications. Perhaps the value you're using is different though?

**Comment by yu46** [comment]
The test should work well, even if you change to a strict comparison.

The problem arises when a value is set to an environment variable with putenv().
In config/bootstrap.php, the .env file value is set to three different environment variables.

```
if (!env('APP_NAME') && file_exists(CONFIG . '.env')) {
     $dotenv = new \josegonzalez\Dotenv\Loader([CONFIG . '.env']);
     $dotenv->parse()
         ->putenv()
         ->toEnv()
         ->toServer();
 }
```

In CakePHP 4.2, env() returned false when using `$dotenv->parse()->putenv()`  if the `.env` file contained `DEBUG=false`. However, in CakePHP 4.3, this behavior seems to have changed and the env() function now returns an empty string.

The following code is part of the .env function in CakePHP 4.2

```
        $val = null;
        if (isset($_SERVER[$key])) {
            $val = $_SERVER[$key];
        } elseif (isset($_ENV[$key])) {
            $val = $_ENV[$key];
        } elseif (getenv($key) !== false) {
            $val = getenv($key);
        }
```

The following code is part of the .env function in CakePHP 4.3
The above code has been changed to the following code.

`if ($val == null && $_ENV[$key] ! == false)` looks like a typo to me.

```
        $val = $_SERVER[$key] ?? $_ENV[$key] ?? null;
        if ($val == null && getenv($key) !== false) {
            /** @var string|false $val */
            $val = getenv($key);
        }
```

Everything works as expected if i don't use putenv(), but the env() function was easier to use in 4.2

**Comment by markstory** [comment]
> The test should work well, even if you change to a strict comparison.

I'm interested in getting a test case that *fails* with the current code, and was hoping there was a simple way to set `ENV` or `SERVER` to trigger this scenario.

**Comment by markstory** [comment]
I took a look into what dotenv is doing. Within the `Loader::putenv()` method `putenv()` is being called with `DEBUG=` which is not deterministically false. It could be null/false/empty string. Using getenv/putenv directly has similar results

```php
> putenv('THINGS=')
= true

> getenv('THINGS')
= ""
```

I think this is a case of previous versions being wrong, as environment variables cannot store booleans, only strings.

**Comment by dereuromark** [comment]
I also think storing 0 vs 1 seems better here

**Comment by yu46** [comment]
OK. I didn't think the previous version was wrong.
