### ISSUE TITLE
`Inflector::classify` phpdoc is ambiguous

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17718]
### Description

Phpdoc for `Inflector::classify` says:

https://github.com/cakephp/cakephp/blob/63c5f1c6bfb4d7584e7e5a91e5f26e762af86501/src/Utility/Inflector.php#L486

Saying *model class name* is ambiguous. Shouldn't it be `Entity` specifically? I ran a bunch of made up table aliases through https://inflector.cakephp.org/ and `classify` result is always singular. Where else in the Model part would you need a singular class name, if not for an entity?

The documentation is not helping.

- https://book.cakephp.org/3/en/core-libraries/inflector.html#Cake\Utility\Inflector::classify
- https://book.cakephp.org/4/en/core-libraries/inflector.html#Cake\Utility\Inflector::classify
- https://book.cakephp.org/5/en/core-libraries/inflector.html#Cake\Utility\Inflector::classify

### CakePHP Version

3, 4, 5

**Comment by mehov** [comment]
@markstory thank you for taking a look at this. Can you help me understand what `Inflector::classify` was meant for? It's unclear how is it different from `Inflector:: singularize` and why we need both

**Comment by ADmad** [comment]
@mehov You can easily check yourself https://github.com/cakephp/cakephp/blob/b0613035d024f288e26e7b063fdfd77aea9d82be/src/Utility/Inflector.php#L497

**Comment by markstory** [comment]
classify will take a table name and create a 'model class' name for it. This used to mean a 2.x style model class, but now means the Entity classname.
