### ISSUE TITLE
$builder->setExtensions not working for me after cakephp 5.0 upgrade

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#17710]
### Description

I upgraded to cakephp 5.0 and found the $builder->setExtensions for me not to be working.

I've been digging into the cakephp sourcecode and I dont get whats happening here. I dont get how the extensions would be set at all ...

my routes look something like this:
```
$routes->setRouteClass(DashedRoute::class);
$routes->scope('/api', function (RouteBuilder $builder): void {
        $builder->setExtensions(['json']);

        $builder->prefix('admin', function ($builder) {
            $builder->resources('Token', [
                'map' => [
                    'getToken' => [
                        'action' => 'getToken',
                        'method' => 'POST'
                    ]
                ],
                'inflect' => 'underscore'
            ]);
        }
}
```

Cakephp 5 always complains about a missing template, since there are no viewClasses set when `Cake\Controller\Controller` tries to render. Implementing the method `viewClasses` on the controller is working, however that should not be the solution here, since this method (setExtensions) is well documented for Cake4 and Cake5.

### CakePHP Version

5.0.8

### PHP Version

8.3

**Comment by ADmad** [comment]
Setting the extension in the router only enables the parsing of extensions, nothing more. In 5.x the RequestHandlerComponent which auto selected view classes based on extensions has been removed and you need to explicitly setup the view classes to use for content negotiation as [documented](https://book.cakephp.org/5/en/views/json-and-xml-views.html#defining-view-classes-to-negotiate-with).
