### ISSUE TITLE
Can't bake Entity with specific name

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17719]
### Description

I'm baking model for a Wordpress database table that's called `Commentmeta`. The automatic Entity name for it is detected as `Commentmetum` (#17717). I would like the Entity to be called `Commentmeta`, but I can't find a way to accomplish that without having to edit the entity file.

- Providing required entity name when baking together with model isn't possible. If baked as a part of the model, the entity will get whatever Inflector decides as the name.

    <details>
        <summary>bin/cake bake model --help</summary>
        
        Bake table and entity classes.
        
        Usage:
        cake bake model [options] [<name>]
        
        Options:
        
        --connection, -c           The datasource connection to get data from.
                                   (default: default)
        --display-field            The displayField if you would like to choose
                                   one.
        --fields                   A comma separated list of fields to make
                                   accessible.
        --force, -f                Force overwriting existing files without
                                   prompting.
        --help, -h                 Display this help.
        --hidden                   A comma separated list of fields to hide.
        --no-associations          Disable generating associations.
        --no-entity                Disable generating an entity class.
        --no-fields                Disable generating accessible fields in the
                                   entity.
        --no-fixture               Do not generate a test fixture skeleton.
        --no-hidden                Disable generating hidden fields in the
                                   entity.
        --no-rules                 Disable generating a rules checker.
        --no-table                 Disable generating a table class.
        --no-test                  Do not generate a test case skeleton.
        --no-validation            Disable generating validation rules.
        --plugin, -p               Plugin to bake into.
        --primary-key              The primary key if you would like to manually
                                   set one. Can be a comma separated list if you
                                   are using a composite primary key.
        --quiet, -q                Enable quiet output.
        --skip-relation-check      Generate relations for all "example_id"
                                   fields without checking the database if a
                                   table "examples" exists.
        --table                    The table name to use if you have
                                   non-conventional table names.
        --theme, -t                The theme to use when baking code.
                                   (choices: Bake|Migrations)
        --update                   Update generated methods in existing files.
                                   If the file doesn't exist it will be created.
        --verbose, -v              Enable verbose output.
        
        Arguments:
        
        name  Name of the model to bake (without the Table suffix). You can use
              Plugin.name to bake plugin models. (optional)
        
        Omitting all arguments and options will list the table names you can
        generate models for.
        
    </details>

- Baking the Entity separately (after baking model with `--no-entity`) isn't possible
  
  >     # bin/cake bake entity --help
  >     Could not find bake command named `entity`. Run `bake --help` to get a list of commands.

### CakePHP Version

5

**Comment by markstory** [comment]
I think you'll need custom inflector rules to get the resulting classnames you want. Once you have inflection rules setup, bake will use them.

> Baking the Entity separately (after baking model with --no-entity) isn't possible

Yes it is. `cake bake model --no-table --no-test` will generate only the entity class (without a test).

**Comment by mehov** [comment]
> `--no-table`

How did I miss this... Thank you

And thanks again for the custom Inflector rules tip (googlers: https://github.com/cakephp/cakephp/issues/17717#issuecomment-2184910139)
