### ISSUE TITLE
Cannot convert Date to DateTime using toDateTimeImmutable

### ISSUE THREAD

**Issue by mcube27** [cakephp/cakephp#17716]
### Description

When trying to convert a date to a datetime using toDateTimeImmutable, it returns an empty object :
`object(DateTimeImmutable) id:0 {}`

I did a test to try that :
```
public function testDateToTime()
    {
        $date = Date::now();
        dd($date->toDateTimeImmutable());
    }
```

Is it expected ?

### CakePHP Version

5.0.8

### PHP Version

8.1

**Comment by markstory** [comment]
> Is it expected ?

Yes. The same thing happens if you dd() other DateTimeImmutable objects. PHP doesn't implement any of the debug hooks like `__debugInfo` so we can't pull any properties out of the object.
