### ISSUE TITLE
Incompability with PSREXT and CakePHP 

### ISSUE THREAD

**Issue by winstrand** [cakephp/cakephp#17711]
### Description

When doing a fresh installation with composer and after that tries to open page I'll get :
Fatal error: Declaration of Cake\Http\ServerRequest::getAttribute(string $name, mixed $default = null): mixed must be compatible with PsrExt\Http\Message\ServerRequestInterface::getAttribute($name, $default = <default>) in /var/local/websites/development/framworks/cake-example/vendor/cakephp/cakephp/src/Http/ServerRequest.php on line 1567

This is repeated for several times ( hasHeader, getHeader, getHeaderLine, withHeader, withAddedHeader, withoutHeader, withMethod, withProtocolVersion, withAttribute, withoutAttribute, getAttribute, withUri, withRequestTarget in the Http\ServerRequest file, withStatus in Http\Resonse, log in Log\Enging\FileLog and ConsoleLog)

There is some errors in laminas\laminas-diactoros\src\MessageTrait ...Stream and ...Uri as well, same type of issue

The problem is reprodusable,
command used "composer create-project --prefer-dist cakephp/app:~5.0 cake-example"
I've tried it on Linux(Ubuntu  Ubuntu 20.04.6 LTS)
On my Windows enviroment it works like wounder (php ver 8.2.12 XAMPP installation)

And if I do the instalation on Linux and then move it to Windows it works on the Windows env. and the other way around install it on Windows (works) copy the installation to Linux (do not work)

### CakePHP Version

5.0.8

### PHP Version

8.3.8

**Comment by winstrand** [comment]
When I added Configure::write('DebugKit.safeTld', ['dev', 'local', 'priv']);
Folowing files also needed to be corrected:
Cache\Engine\FileEngine
Cache\CacheEngine
Log\Engine\ArrayLog

debug_kit\src\Cacshe\Engine\DebugEngine
...Database\Log\DebugLog
...Log\Engine\DebugKitLog

**Comment by ADmad** [comment]
Please check the PHP version used by your webserver on Linux, I doubt it's PHP 8.3.8 as you claim.

**Comment by winstrand** [comment]
![screenshot_2024-06-17_19_13_17](https://github.com/cakephp/cakephp/assets/16792692/52c157cd-79ef-4274-ba42-2b31dc0ec6aa)
Screenshot of phpinfo from webserver
In short:
PHP Version 8.3.8
System  Linux hoknar 5.4.0-177-generic #197-Ubuntu SMP Thu Mar 28 22:45:47 UTC 2024 x86_64
Build Date  Jun 8 2024 21:33:58
Build System    Linux
Server API  FPM/FastCGI 

marwin@:/vHosts/marwin/www/framworks$ php -v
PHP 8.3.8 (cli) (built: Jun  8 2024 21:33:58) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
marwin@:/vHosts/marwin/www/framworks$  Ubuntu 20.04.6 LTS

**Comment by othercorey** [comment]
> And if I do the instalation on Linux and then move it to Windows it works on the Windows env. and the other way around install it on Windows (works) copy the installation to Linux (do not work)

You are copying the vendor/ directory as well when you do this? 

I think this means copying the php 8.2 dependencies to a php 8.3 environment does not work.

**Comment by winstrand** [comment]
I have been running the installation in the 8.3 environment and copied to 8.2, and it's therefore I can't understand why it works in the Windows environment and not in Linux.
After your comment I have tried and done installation in resp environment an then copied them to each other but I still get the same issue. 
Could it be that there is some other things that is interrupting the installation.
It isn't a issue for me, but I thought that is should be an out of the box to have basic CakePHP up an running in 8.3, for me it seams that it is the PSR that is the problem.
Sines all of the naming and declaration conventions are followed in the Cake code.

**Comment by garas** [comment]
Does `ext-psr` is installed on both Linux and Windows? What version of extension?

`ext-psr` v1 has defined interfaces of PSR version 1.0, but CakePHP expects PSR version 1.1 or 2.0.

Disable or uninstall extension, this extension has more problems than advantages. Composer installs correct compatible versions of PSR interfaces.

[Symfony](https://github.com/symfony/symfony/blob/v7.1.1/composer.json#L164) and [many projects](https://github.com/search?q=ext-psr+path%3Acomposer.json&type=code) has marked it as conflict. I suggest to do the same on CakePHP.

**Comment by winstrand** [comment]
I have PSR 1.2.0 on my Linux, and did not have it on the Windows env. but when I enable it on windows it crashed too.

So to mark it as an conflict would be a good thing.
Thanx

**Comment by othercorey** [comment]
I might have an idea. Are the error reporting levels in php.ini for the windows and linux the same? Perhaps one is hiding the warnings?

**Comment by winstrand** [comment]
> I might have an idea. Are the error reporting levels in php.ini for the windows and linux the same? Perhaps one is hiding the warnings?

Yes, and the problem is PSR extention in PHP.
When I added it on windows I got same result as on linux. It also cease to exist when I remove it from the Linux config.
Ergo, the problem is not in the Cake code but in the implementation of PSR in the extention. The version I tried was/is PHP-PSR 1.2.0.

**Comment by othercorey** [comment]
ah, ok. I didn't know that extension could be installed!

**Comment by markstory** [comment]
> Yes, and the problem is PSR extention in PHP.

I'll take this as a signal to close this issue. We can't help much with the incompatibility in that extension. If I've misread the situation let me know and we can reopen this.
