### ISSUE TITLE
Inflector singularizes `meta` as `metum`

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17717]
### Description

https://inflector.cakephp.org/Commentsmeta

> singularize | => | Commentsmetum
> classify | => | Commentsmetum

 Shouldn't it just stay `meta`?

### CakePHP Version

5

**Comment by markstory** [comment]
Because the 'meta' is embedded in another word the existing `Inflector` rules don't catch it. You could either add Inflector rules to your application to handle this, send a pull request to expand the core inflection rules, or use a name like `CommentsMetas` which will singularize to `CommentsMeta`

**Comment by mehov** [comment]
> add Inflector rules to your application to handle this

That's what I'll go with. Thank you!

https://book.cakephp.org/4/en/core-libraries/inflector.html#inflection-configuration

    Inflector::rules('singular', ['/(meta)$/i' => '\1']);
