### ISSUE TITLE
`ErrorHandlerMiddleware` passes outdated request object to `ExceptionRenderer`

### ISSUE THREAD

**Issue by fabian-mcfly** [cakephp/cakephp#17731]
### Description

When not in debug mode, I want to show a 404 page when a controller does not exist inside the regular layout of my application.
This layout calls a cell to render the menu, which depends on an identity - set via the `AuthenticationMiddleware` and requested via `$this->request->getAttribute('identity')` - to determine which menu entries are visible to the user.

This is currently an empty attribute and happens because the `ErrorHandlerMiddleware` uses the intially passed request object to render exceptions, even though other (successfully processed) middlewares might have set attributes, creating a new one each time in the process.
The result is a request object without the `identity`-attribute inside the `ExceptionRenderer` resp. `ErrorController` if the `ErrorHandlerMiddleware` runs before the `AuthenticationMiddleware`. 

The code responsible for (Line 119):
https://github.com/cakephp/cakephp/blob/2eecad68ca9d957f41a0cd2a76c6e111cb019d4e/src/Error/Middleware/ErrorHandlerMiddleware.php#L112-L121

Adding a `dd($request, Router::getRequest());` in Line 119 shows that those are two different request objects, one without and one with all attributes.

It this intended behavior?
Using `Router::getRequest() ?? $request` in the `handleException`-call seems to fix it without any failing tests but I wonder if that's the best way to get the latest request object and if it might cause other issues.

### CakePHP Version

5.0.9

### PHP Version

8.2

**Comment by ADmad** [comment]
> It this intended behavior?

Not really intended but an unfortunate known limitation of the PSR-7 (request immutability) + PSR-15 (single pass middleware queue) combo. The single pass implementation doesn't have a way to send the modified request instance back up the chain.

> Using Router::getRequest() ?? $request in the handleException-call seems to fix it ...

Fetching the updated request instance from the `Router` class is a reasonable hack. Another option would be have the `RoutingMiddleware` add the updated request instance to the container and then get that instance from the container in `ErrorHandlerMiddleware`.

**Comment by ADmad** [comment]
This has been an annoyance for quite a while so it will be a welcome change once we decide between the 2 options I stated above.

**Comment by othercorey** [comment]
> Fetching the updated request instance from the `Router` class is a reasonable hack. Another option would be have the `RoutingMiddleware` add the updated request instance to the container and then get that instance from the container in `ErrorHandlerMiddleware`.

I think I prefer the ~RoutingMiddleware~ (any update container) approach because it's something others could follow instead of having a detailed comment around why we use Router as storage.

**Comment by markstory** [comment]
> Fetching the updated request instance from the Router class is a reasonable hack. Another option would be have the RoutingMiddleware add the updated request instance to the container and then get that instance from the container in ErrorHandlerMiddleware.

Couldn't we have `BaseApplication` update the container? That would allow `ErrorHandlerMiddleware` to use DI to construct `ErrorController`.

**Comment by ADmad** [comment]
> Couldn't we have BaseApplication update the container?

When would the BaseApplication do that? BaseApplication::handle() is run when the middleware queue is exhausted, so if an exception is thrown earlier, for e.g. the AuthorizationMiddleware, the ErrorHandlerMiddleware would still get the outdated request instance.

**Comment by markstory** [comment]
> When would the BaseApplication do that? BaseApplication::handle() is run when the middleware queue is exhausted, 

I was thinking it could be done in `handle()`. You're right that it would be too late for errors from middleware though. Wouldn't the request stored in `RoutingMiddleware` be too 'early' though? Any middleware in the stack can modify the request and pass the modified request to the 'next' layer and we don't have a way to get the most recent request modifications until we get to a checkpoint like `BaseApplication::handle()` or in `RoutingMiddleware`.

I don't think using `Router::getRequest()` is that big of a hack, it is a solution for immutable request objects + global shared state. We already use it in a few places and this scenario feels similar to the other places we're using `Router::getRequest()`.

**Comment by othercorey** [comment]
> I don't think using Router::getRequest() is that big of a hack, it is a solution for immutable request objects + global shared state. We already use it in a few places and this scenario feels similar to the other places we're using Router::getRequest().

Certainly better than not having a solution until we think of something else.
