### ISSUE TITLE
Calling FormHelper::unlockField() throws an exception if the FormProtectionComponent is not loaded

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#17736]
### Description

`FormHelper::getFormProtector()` throws an exception if the `FormProtector` instance is not created, which is the case when `FormProtectionComponent` is not loaded.

When developing a publicly available plugin it's not possible to know whether the `FormProtectionComponent` will be loaded in the app, so `FormHelper::unlockField()` should become a no-op and not throw any exception if the form protector is not available.

So there are 2 ways to address this:

1. Make the return type of `FormHelper::getFormProtector()` nullable and remove the exception it throws.
2. Wrap the `$this->getFormProtector()` call in `FormHelper::unlockField()` in a try-catch block.

I am leaning towards option 1.

### CakePHP Version

5.0

**Comment by dereuromark** [comment]
Maybe option 2 for 5.0 and option 1 for 5.1
As someone could extend the signature or depend on current usage.
Even thought this is quite a specific functionality.
