### ISSUE TITLE
Argument #1 ($salt) must be of type string, null given

### ISSUE THREAD

**Issue by aymardkouakou** [cakephp/cakephp#17732]
### Description

Hello,
I have create a new project and connected it with success to a database.

When I tried to run a command like `.\bin\cake bake model all`, I have the following error.

```
.\bin\cake bake model all
[TypeError] Cake\Utility\Security::setSalt(): Argument #1 ($salt) must be of type string, null given, called in PROJECT_ROOT\config\bootstrap.php on line 181 in PROJECT_ROOT\vendor\cakephp\cakephp\src\Utility\Security.php on line 303

Stack Trace:

Cake\Utility\Security::setSalt() - ROOT\config\bootstrap.php, line 181
PROJECT_ROOT\vendor\cakephp\cakephp\src\Http\BaseApplication.php - CORE\src\Http\BaseApplication.php, line 183
Cake\Http\BaseApplication->bootstrap() - APP/Application.php, line 49
App\Application->bootstrap() - CORE\src\Console\CommandRunner.php, line 190
Cake\Console\CommandRunner->bootstrap() - CORE\src\Console\CommandRunner.php, line 137
Cake\Console\CommandRunner->run() - ROOT\bin\cake.php, line 10
[main] - [main], line 0

```

### CakePHP Version

5.0.9

### PHP Version

8.1.17

**Comment by dereuromark** [comment]
Make sure to set up your app_local.php with a salt.
https://github.com/cakephp/app/blob/9a7f511ed5f10dac993051cb1ecad79ab7cc93e5/config/app_local.example.php#L28
Currently you seem to skip this, and not using a salt will fail here hard.

Side note for team:
I think we should assert the salt is being set in the bootstrap and throw a meaningful exception if not.
As this type error might not be clear for people onboarding on the framework.
