### ISSUE TITLE
Attachment Japanese filename will be unexpected automatically.

### ISSUE THREAD

**Issue by T-Kisaku** [cakephp/cakephp#17751]
Hi, cakephpers!! Thank you all who relate this project!!!

### What happens to me
I was implementing a feature that sends email with attachment files according [this article](https://book.cakephp.org/5/en/core-libraries/email.html#sending-attachments).

If the filename is Japanese, it won't work well.

```
$mailer->setAttachments([
 // Japanese filename
    '日本語の名前' => [
        'file' => '/full/some_hash.png',
        'mimetype' => 'image/png',
        'contentId' => 'my-unique-id',
    ],
]);
```
 
The filename will be `語` which is expected `日本語の名前`

### Reason that this bug happens

This line makes the bug

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Utility/Text.php#L1102

Because $transliterator will be `Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove`, my Japanese filename will be unexpected form.

Try this code in your environment to debug.
```
echo transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove', '日本語の名前');
```

<details>
<summary>Tracks</summary>

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Mailer/Message.php#L1420

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Http/Client/FormDataPart.php#L195

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Http/Client/FormDataPart.php#L226

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Utility/Text.php#L1102

</details>

### Solution
I changed filename to alphabet, otherwise wait this project to be fixed.

### My environment with dockerfile
```dockerfile

FROM php:fpm-alpine3.17

#############
##   PHP   ##
#############

COPY --from=composer:2.6.5 /usr/bin/composer /usr/bin/composer

RUN apk update \
 && apk add --no-cache icu-dev icu-data-full nodejs npm \
 && docker-php-ext-install mysqli pdo pdo_mysql \
 && docker-php-ext-configure intl && docker-php-ext-install intl \
    # GD
 && apk add --no-cache \
    freetype \
    freetype-dev \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libwebp-dev \
    imagemagick-dev \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install -j$(nproc) gd \
    # Exif
 && apk add --no-cache libexif-dev \
 && docker-php-ext-install exif

#####################
##  Japanese font  ##
#####################
# Reference: https://zenn.dev/takashiaihara/articles/e6e5a64cb4e790

RUN apk update \
 && apk add --no-cache curl fontconfig \
 && curl -O https://moji.or.jp/wp-content/ipafont/IPAexfont/IPAexfont00301.zip \
 && mkdir -p /usr/share/fonts/ipa \
 && unzip -o -d /usr/share/fonts/ipa/ IPAexfont00301.zip "*.ttf" \
 && fc-cache -fv

```

### CakePHP Version

5.0.1

### PHP Version

8.3.0

**Comment by ADmad** [comment]
Does the filename get changed in the received email?

Checking the code that transliteration is done only to ascertain the character set. The transliterated string is not actually used.

**Comment by T-Kisaku** [comment]
> Q. Does the filename get changed in the received email?

Yes, it does.

> Checking the code that transliteration is done only to ascertain the character set. The transliterated string is not actually used.

In the below part, it is used. 

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Mailer/Message.php#L1420

When `$part` is converted as string, it will fire the below codes

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Http/Client/FormDataPart.php#L195



https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Http/Client/FormDataPart.php#L226

https://github.com/cakephp/cakephp/blob/bc0ca01b6368a4fb6dafcb3eeef650fcca74bcb6/src/Utility/Text.php#L1102

**Comment by dereuromark** [comment]
@T-Kisaku Do you want to make a PR with the suggested fix?

**Comment by markstory** [comment]
@T-Kisaku Could you take a look at #17761? I'm not able to reproduce the corruption issue and I want to know if there is something I'm missing. Perhaps we have different default encodings, or libicu/intl versions?
