### ISSUE TITLE
PHPStan regex failure

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17759]
### Description

The current builds are red - the regexp issue comes from
https://github.com/phpstan/phpstan/releases/tag/1.11.9

>   128    Regex pattern is invalid: Compilation failed: lookbehind assertion is not fixed length at offset 0 in pattern:  
         /(?<!.*)\{([a-z0-9-_]+)\}/i    

```php
        preg_match_all(
            '/(?<!' . preg_quote('\\', '/') . ')\{([a-z0-9-_]+)\}/i',
            $message,
            $matches
        );
```

According to chatGTP:

The issue arises from the lookbehind assertion in your regex pattern, which is not of fixed length. In PHP, lookbehind assertions need to have a fixed length, but your pattern `(?<!.*)\{([a-z0-9-_]+)\}` has a variable length `.*` in the lookbehind, which is not allowed.

To fix this, you can use an alternative approach that avoids lookbehind assertions with variable lengths. One common method is to use a negative lookahead assertion instead.

Here is the modified code:

```php
preg_match_all(
    '/(?<!\\\\)\{([a-z0-9-_]+)\}/i',
    $message,
    $matches
);
```

In this code:

- `(?<!\\\\)` ensures that the curly braces `{` and `}` are not preceded by a single backslash `\`. The backslash itself is escaped in the regex pattern and in the PHP string, resulting in four backslashes.
- The rest of the pattern `\{([a-z0-9-_]+)\}` remains unchanged, matching the placeholders `{...}`.

Alternatively, you can achieve the same goal using a negative lookahead approach:

```php
preg_match_all(
    '/\\\{([a-z0-9-_]+)\}(?!\\\)/i',
    $message,
    $matches
);
```

In this code:

- `\\\{([a-z0-9-_]+)\}` matches the placeholders `{...}`.
- `(?!\\\)` ensures that the curly braces `{` and `}` are not followed by a single backslash `\`.

Choose the approach that best fits your needs. The first approach is usually preferred for checking what comes before the matched text, while the second approach is better for checking what comes after.

### CakePHP Version

5.x

**Comment by markstory** [comment]
I know that phpstan thinks this regex is invalid, but it works and has worked for a long time.
