### ISSUE TITLE
RFC: Implement API Mode

### ISSUE THREAD

**Issue by itosho** [cakephp/cakephp#17753]
### Description

I feel the need for an API mode similar to Ruby on Rails, and I would like to propose this idea 💪 
This RFC seeks feedback from the CakePHP community to refine and implement this proposal 🙏 

## Introduction
This RFC proposes the introduction of an API mode in CakePHP, similar to Ruby on Rails' API mode. The purpose of this feature is to streamline the development of API-only applications by providing a lightweight and optimized framework configuration tailored specifically for building APIs.

## Background
The current trend in web development is the separation of frontend and backend. Modern web applications often use frontend frameworks like React or Vue to communicate with backends via RESTful APIs or GraphQL. This separation improves scalability, maintainability, and development flexibility.

- Separation of Frontend and Backend
  - Modern frontend frameworks rely on APIs to exchange data. This separation allows frontend and backend development to proceed in parallel and makes it easier to adopt different technology stacks. By having an API mode, CakePHP can better support this separation, allowing for efficient construction of API-only backends.
- Demand for Mobile Applications
  - Mobile applications communicate with servers via APIs. With a dedicated API mode, CakePHP becomes well-suited as a backend for mobile applications. Providing unified API endpoints simplifies access for multiple client applications (web, iOS, Android, etc.).
- Microservices Architecture
  - Many organizations are adopting Microservices architectures, where each service offers its own API. An API mode in CakePHP provides a lightweight and flexible framework for building such Microservices.

### 1. Create a New API Mode for CakePHP
Introduce an API mode option that can be specified during application creation. This mode will configure CakePHP with settings optimized for API development.

### 2. Command Line Interface Enhancements
Add a new `api` option to enable API mode

```bash
$ composer create-project --prefer-dist cakephp/app:"6.*" my_app_name --api
```

### 3. Default Configuration Changes
When API mode is enabled, the following default configurations will be applied:

- Disable View Rendering
  - Disable the default view rendering mechanism since API responses will primarily be JSON or XML.
- Remove Unnecessary Middleware
  - Exclude middleware related to session handling, CSRF protection, and cookie parsing, which are not typically needed for APIs.
- Enable JSON Response
  - Configure the default response format to be JSON.
- Optimize Router for API Endpoints
  - Simplify and optimize the routing configuration for defining API endpoints.

### 4. Controller Modifications
Introduce a base API controller that extends AppController but includes API-specific functionalities

```php
namespace App\Controller\Api;

use Cake\Controller\Controller;

class ApiController extends Controller
{
    public function initialize(): void
    {
        parent::initialize();
        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false,
        ]);
        $this->viewBuilder()->setClassName('Json');
    }

    public function beforeRender(\Cake\Event\EventInterface $event)
    {
        if (!array_key_exists('_serialize', $this->viewVars)) {
            $this->set('_serialize', true);
        }
    }
}
```

### 5. Routing Enhancements
Provide a simplified way to define API routes

```php
Router::prefix('api', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->resources('Posts');
});
```

### 6. Authentication and Authorization
Recommend the use of token-based authentication (e.g., JWT) for securing API endpoints. Provide default integration for popular authentication libraries.

## Benefits

- Improved Performance
  - By removing unnecessary components, API mode will reduce overhead and improve the performance of API requests.
- Simplified Configuration
  - Developers will have a ready-to-use configuration optimized for API development, reducing setup time and potential errors.
- Security Enhancements
  - By omitting session management and cookie handling, the risk of certain security vulnerabilities is reduced. Additionally, API authentication and token-based authentication can be more easily implemented.
- Extensibility
  - API mode is simple and lightweight, allowing additional features and middleware to be added minimally. Only necessary features are added, maintaining an efficient architecture.
- Consistent Responses
  - With JSON as the default response format, clients can receive consistent data formats, making frontend integration easier.

### CakePHP Version

6.0

**Comment by ADmad** [comment]
The framework already supports everything needed to run in an "API mode", it's just a matter of configuring your app accordingly. To begin with you can just create a community managed app template for it.

**Comment by markstory** [comment]
> $ composer create-project --prefer-dist cakephp/app:"6.*" my_app_name --api

I don't think we can do this because we can't add additional parameters to `composer create-project`.  We could have a separate application skeleton that comes with the streamlined application configuration as you've suggested. We could even go as far as to include a token based authentication setup.

I'd be up for working on an API focused application skeleton.

**Comment by dereuromark** [comment]
> The framework already supports everything needed to run in an "API mode", it's just a matter of configuring your app accordingly. To begin with you can just create a community managed app template for it.

I agree. And once that app template is fine, feel free to share and communicate it via entry in the awesome list:
https://github.com/FriendsOfCake/awesome-cakephp?tab=readme-ov-file#web-applications

**Comment by markstory** [comment]
I've generated a new repo tonight, you can find it here https://github.com/cakephp/api-app

**Comment by itosho** [comment]
Thank you all for the feedback. I understand it now. 

I will check the new repository and send a Pull Request 🙏
