### ISSUE TITLE
You must set a pagination instance using `setPaginated()` first

### ISSUE THREAD

**Issue by rjssaini** [cakephp/cakephp#17835]
### Description

You must set a pagination instance using `setPaginated()` first

```php
<?php if ($this->Paginator->total() > 1) { ?>

<ul class="pagination pull-right">
   <li><?php  echo $this->Paginator->first('First'); ?></li>
    <li><?php echo $this->Paginator->prev(__('<i class="fa fa-angle-left"></i>'), array('tag' => false, 'escape' => false)); ?></li>
    <li><?php echo $this->Paginator->numbers(array('separator' => '', 'tag' => 'li', 'currentClass' => 'active', 'currentTag' => 'a', 'escape' => false)); ?></li>
    <li><?php echo $this->Paginator->next(__('<i class="fa fa-angle-right"></i>'), array('tag' => false, 'escape' => false)); ?></li>
    <li><?php  echo $this->Paginator->last('Last'); ?></li>
</ul>
    <?php echo $this->Html->css('pagination'); ?>
<?php } ?>
```

### CakePHP Version

5

### PHP Version

8.2

**Comment by markstory** [comment]
How could someone reproduce the issue you're having? The error message in the title of this issue implies that your controller action hasn't done pagination, or hasn't put the paginated result into the template variables.

**Comment by ADmad** [comment]
Closing as help has already been provided on our support forum https://discourse.cakephp.org/t/you-must-set-a-pagination-instance-using-setpaginated-first/12170/2
