### ISSUE TITLE
Installing Authentication Plugin Not Install

### ISSUE THREAD

**Issue by ghanshyam-wadaskar** [cakephp/cakephp#17834]
### Description

![Screenshot 2024-08-06 145737](https://github.com/user-attachments/assets/c413dd21-7007-40c8-9971-c54bdc4ef043)
![Screenshot 2024-08-07 143357](https://github.com/user-attachments/assets/fc72665b-a3a6-4863-9c09-2dacc74dc930)

### CakePHP Version

0.2.9

### PHP Version

 8.3.9

**Comment by ravage84** [comment]
@ghanshyam-wadaskar Composer was not properly set up on your machine.

Please refer to the [official installation documentation of Composer for Windows](https://getcomposer.org/doc/00-intro.md#installation-windows).

**Comment by ravage84** [comment]
@ghanshyam-wadaskar Composer was not properly set up on your machine.

Please refer to the [official installation documentation of Composer for Windows](https://getcomposer.org/doc/00-intro.md#installation-windows).
