### ISSUE TITLE
INTERSECT queries via ORM

### ISSUE THREAD

**Issue by ryanolton** [cakephp/cakephp#17857]
### Description

I have found the `union` SelectQuery method quite useful, but I was curious if an `intersect` (and `intersectAll`) method could be added to SelectQuery as well?

### CakePHP Version

5.x

**Comment by ADmad** [comment]
Support for `insert`/`insertAll` can surely be added, would you like to submit a patch for it?

**Comment by ryanolton** [comment]
@ADmad sure, I'll give it a shot. To be clear, you responded with `insert` and `insertAll`, but I intend to add support for `intersect` and `intersectAll`, companions of sort to `union` and `unionAll`.

**Comment by ADmad** [comment]
Yes, sorry, I meant `intersect` and `intersectAll` :)

**Comment by ADmad** [comment]
Please target your pull request to the `5.next` branch.
