### ISSUE TITLE
Paginate on collections (non DB)

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17854]
### Description

There were already tickets like https://github.com/cakephp/cakephp/issues/14741 but for other motivations.
When dealing with non-DB collections, e.g. from XML or array source, there is currently no good way to provide an easy out of the box solution using the CakePHP paginators and helpers.

In the old days we used an array datasource to "fake" it and return it just as if it was a DB collection (result set).
With Cake5 we can now go a more clean way maybe.

I suggest to add a CollectionPaginator besides SimplePaginator that would allow this.
See my demo https://sandbox.dereuromark.de/sandbox/cake-examples/paginate-non-database?limit=1

```php
$collection = new \Cake\Collection\Collection($items);

$paginator = new \Sandbox\Controller\Paginator\CollectionPaginator($this->request->getQuery());
$results = $paginator->paginate($collection);
```

And the view template and pagination helper would also work out of the box using the query string params.

Things to be done for this to be ported to core:
- [ ] Discuss if sorting is useful (e.g. on existing collection fields)
- [ ] Clarify if scoping is needed

What do people think?

### CakePHP Version

5.1

**Comment by LordSimal** [comment]
Just to be clear: You are actually talking about paginating those results in a web request to show them in a e.g. table.

Otherwise I thought [chunking](https://book.cakephp.org/5/en/core-libraries/collections.html#Cake\Collection\Collection::chunk) is all one needs to split up a big collection into smaller parts.

**Comment by dereuromark** [comment]
I guess the interest here is low, I keep it as app specific then for now.
