### ISSUE TITLE
Cake\Http\Client\FormData::add(): Argument #1 ($name) must be of type Cake\Http\Client\FormDataPart|string, int given

### ISSUE THREAD

**Issue by cartman8648** [cakephp/cakephp#17872]
### Description

Hello, 

When following this example:
https://book.cakephp.org/5/en/core-libraries/httpclient.html#building-multipart-request-bodies

My Code:
```
$data = new FormData();
$image = $data->newPart('file', $file);
$image->filename($meta['foto']);
$image->type('image/jpeg');
$data->add($image);
```

I get the following Error: 
![image](https://github.com/user-attachments/assets/9e871a29-9169-4c6f-b546-65b34ac428e3)

Seems to be as similar Bug as: #17094 

### CakePHP Version

5.0.10

### PHP Version

8.1

**Comment by markstory** [comment]
> My Code:

Is there more to your code? How does your `$data` instance get attached to the request?

**Comment by cartman8648** [comment]
Hi,

So i am not able to recreate the Bug... 
After a restart everything works as expected. 

Sorry about that.
