### ISSUE TITLE
6.0:  Allow preserving keys for CollectionInterface::groupBy()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#17870]
### Description

Currently if for e.g. you do a `Collection::indexBy()` followed by `Collection::groupBy()` the indexes set by the 1st call would be lost.

I propose adding a `bool $preserveIndex` option to `groupBy()` so preserve the existing indexes when grouping items.

### CakePHP Version

6.0

**Comment by dereuromark** [comment]
Couldnt this be done in 5.1 using optional param and annotation Signature?

**Comment by ADmad** [comment]
That would require updating the interface method `CollectionInterface::groupBy()`, don't think that would qualify as a backwards compatible change.

**Comment by dereuromark** [comment]
no I meant there in annotation signarture only. an optional param should be fine only in class afaik
But fair enough

**Comment by ADmad** [comment]
> no I meant there in annotation signarture only. an optional param should be fine only in class afaik

Done in #17874 :)
