### ISSUE TITLE
Make the structure of Locale folder configurable

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#17887]
> The problem I stumbled is that the path to po files used by CakePHP is not compatible with [gettext](https://www.php.net/manual/en/book.gettext.php) paths.
Cake path: src/Locale/de_DE/frontend.po
Gettext path: src/Locale/de_DE/LC_MESSAGES/frontend.po
So I wonder whether it would be possible to add some configuration variable or function that would add LC_MESSAGES folder to the translation paths so that it would be possible to quickly switch between gettext implementation and CakePHP implementation without removing LC_MESSAGES folder. Something like `I18n:configPaths('Locale/{locale regex}/LC_MESSAGES/{*.po}');`.

_Originally posted by @bancer in https://github.com/cakephp/cakephp/issues/16265#issuecomment-1054100103_
            
The goal is to be able to enable and disable gettext without moving any folders inside of Locale folder every time after gettext is enabled or disabled so that CakePHP would recognize gettext paths after they have been configured with `I18n:configPaths` or some other way.

**Comment by ADmad** [comment]
You can create your custom version of `MessagesFileLoader` and then use that in the fallback loader callbable `I18n::translator->registerLoader('_fallback', function () {...})` in the [translator registry](https://github.com/cakephp/cakephp/blob/5.0.10/src/I18n/TranslatorRegistry.php#L112-L123).
