### ISSUE TITLE
6.0 RFC: Change `FormHelper` option `type` to `method` to align with generated HTML

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17902]
### Description

If one wants to generate a GET Form its possible via
```
<?= $this->Form->create(null, ['type' => 'get']) ?>
<?= $this->Form->control('search') ?>
<?= $this->Form->end() ?>
```
and it generates
```
<form method="get" accept-charset="utf-8" action="/">                
    <div class="input text">
        <label for="search">Search</label>
        <input type="text" name="search" id="search">
    </div>
</form>
```
which some may seem odd since specifying `['type' => 'get']` results in `method="get"`

This surely has some ancient, Cake specific reason but I don't see it now.

So how about this gets changed to be 
```
<?= $this->Form->create(null, ['method' => 'get']) ?>
```
in Cake 6 (or at least allow `method` to be an alias for `type` in the next minor)?

### CakePHP Version

5.0

### PHP Version

8.3

**Comment by ADmad** [comment]
> This surely has some ancient, Cake specific reason but I don't see it now.

It's because `type` can be set to `file` which the helper translates to appropriate values for `method` and  `entype` attributes.

**Comment by LordSimal** [comment]
True, thats pretty handy, and I forgot about that usecase 😅 

So then how about just aliasing `method` to `type`?

**Comment by ADmad** [comment]
I am on the fence for allowing usage like `'method' => 'file'`. That would be confusing for someone new to the framework as `file` is not a valid value for the corresponding HTML attribute.

We could instead check if `method` is set and give it precedence over the method value auto inferred if `type` is not explicit provided.

**Comment by LordSimal** [comment]
I'd also be fine if we show a warning if we detect a valid form method inside the `method` option and point the user to use `type` instead.

**Comment by dereuromark** [comment]
I have been fine with this little bit of abstraction so far. So imo we could also keep it as is.
Most wouldn't find it too weird to have it called type from the PHP side

**Comment by ADmad** [comment]
`method` set is options is already given precedence, so I don't think we need to change anything

https://github.com/cakephp/cakephp/blob/eb61f6b7b7e9c39f91ccd5c48c82336128217e73/src/View/Helper/FormHelper.php#L452-L454

**Comment by ADmad** [comment]
The issue @cnizzardini mentioned on Slack might be due to this

https://github.com/cakephp/cakephp/blob/eb61f6b7b7e9c39f91ccd5c48c82336128217e73/src/View/Helper/FormHelper.php#L459

The value of `method` isn't taken into account when setting the property.

**Comment by ADmad** [comment]
PR #17907
