### ISSUE TITLE
looks like the wiki and site still shows 5.0 rather than 5.1

### ISSUE THREAD

**Issue by chenrui333** [cakephp/cakephp#17917]
### Description

looks like the wiki and site still shows 5.0 rather than 5.1
- https://github.com/cakephp/cakephp/wiki
- https://cakephp.org/

And also what is the codename for 5.1 release?

relates to https://github.com/endoflife-date/endoflife.date/pull/5857

### CakePHP Version

5.1

**Comment by markstory** [comment]
The wiki pages have been updated now. I'll get the website updated soon

**Comment by chenrui333** [comment]
thanks @markstory do you know the codename for 5.1 release? thanks!

**Comment by ADmad** [comment]
@chenrui333 Codename changes only for a new major.

**Comment by chenrui333** [comment]
got you, thanks!
