### ISSUE TITLE
Upgrade Tool Error @ CommandRunner.php:323

### ISSUE THREAD

**Issue by yosus** [cakephp/cakephp#17923]
### Description

Tested on Php8.1.2  and Php8.3.6

Installed upgrade tool as per [guide](https://book.cakephp.org/5/en/appendices/5-0-upgrade-guide.html)

Error when calling `bin/cake upgrade rector --rules cakephp50 /var/www/html/cakesample/src`

```
PHP Fatal error:  Uncaught Error: Call to undefined method Cake\Upgrade\Application::pluginEvents() in /var/www/upgrade/vendor/ca
Stack trace:
#0 /var/www/upgrade/vendor/cakephp/console/CommandRunner.php(167): Cake\Console\CommandRunner->runCommand()
#1 /var/www/upgrade/bin/cake.php(12): Cake\Console\CommandRunner->run()
#2 {main}
  thrown in /var/www/upgrade/vendor/cakephp/console/CommandRunner.php on line 323

Fatal error: Uncaught Error: Call to undefined method Cake\Upgrade\Application::pluginEvents() in /var/www/upgrade/vendor/cakephp
Stack trace:
#0 /var/www/upgrade/vendor/cakephp/console/CommandRunner.php(167): Cake\Console\CommandRunner->runCommand()
#1 /var/www/upgrade/bin/cake.php(12): Cake\Console\CommandRunner->run()
#2 {main}
  thrown in /var/www/upgrade/vendor/cakephp/console/CommandRunner.php on line 323


```

Works fine when using the older [CommandRunner.php](https://github.com/cakephp/cakephp/blob/238c8b37ee79020f2287b44d37ca32fc076c8eb9/src/Console/CommandRunner.php) 

### CakePHP Version

4

**Comment by ADmad** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/17912. Please wait for the next patch release of the core.

**Comment by robertpustulka** [comment]
In the meantime you can try using upgrade tool with Cake 5.0: `composer r cakephp/console:~5.0.0`
