### ISSUE TITLE
Number padded with zeros should be convertable to number

### ISSUE THREAD

**Issue by Harfusha** [cakephp/cakephp#17935]
### Description

When zero padded number is passed to controller action that have typed argument int, error is thrown:
[Cake\Controller\Exception\InvalidParameterException] Unable to coerce "0139127" to `int` for `id` in action Tickets::view(). in /var/www/gigaserver.cz/www/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php on line 204

Expected behaviour is that all numeric strings should be convertable to int

### CakePHP Version

4.5.7

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/cakephp/pull/17979
