### ISSUE TITLE
Possible regression on CLI Command API

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17939]
### Description

My plugin exposes a command as
```php
	public function console(CommandCollection $commands): CommandCollection {
		$commands = parent::console($commands);
		$commands->add('scheduler run', RunCommand::class);

		return $commands;
	}
```
And it definitely gets invoked on startup of cli bootstrap, so this is added to the commands list

But then on output, it says
```
Queue:
 - bake queue_task
 - queue add
 - queue info
 - queue job
 - queue run
 - queue worker

QueueScheduler:
 - run
```

And no sign of `scheduler run` as expected.

This is confusing as "run" itself isnt clear really on the API level.
Maybe it takes the shortcut preferred over the actual long name?

### CakePHP Version

5.1

### PHP Version

8.2

**Comment by dereuromark** [comment]
Turns out the parent::call() is doing this.
Removing that seems to make it work.

I wonder if there should be some kind of feedback/warning that adding both the "autoresolved" and "manual" will "silence" the latter apparently? Doesn't even show up in the command list basically.

**Comment by dereuromark** [comment]
The problem is worse if the command exists also in app
I just accidently executed a different command because of it

Plugin FileStorage:
```php
    public function console(CommandCollection $commands): CommandCollection
    {
        // Add your commands here

        $commands = parent::console($commands);

        return $commands;
    }
```
So no custom commands

The result in the output in 5.1:
```
FileStorage:
 - cleanup
 - image_variant_generate
```

But it happens to also have one in app already:
```
App:
 - cleanup
```
So when you execute `bin/cake cleanup` it happens to use the one from app now unexpectectly.

Only when you experiment around you notice that
```
FileStorage.cleanup -h
```
is the commend you are looking for and only that one invokes it, the other one displayed is invoking the app one and is wrongly showing here as such.

**Comment by ADmad** [comment]
> And no sign of `scheduler run` as expected.

I believe that's because the names listed as based on the value returned by `BaseCommand::defaultName()`. Overriding that method to return `scheduler run` would fix your problem.

I think we should update the bake template to generate that method.

**Comment by dereuromark** [comment]
Sure, but I thought the whole idea of having Application or Plugin files setting custom names would make them take precedence over any defaults.
https://github.com/dereuromark/cakephp-queue-scheduler/blob/72d78cac8d36c48697bcad7c4b845e0bba8620c2/src/QueueSchedulerPlugin.php#L60
```php
	public function console(CommandCollection $commands): CommandCollection {
		$commands->add('scheduler run', RunCommand::class);

		return $commands;
	}
```

So the expectation would rather be to always display this one for the same command, but maybe also allow invocation through the default if not otherwise already taken (which in this case is).

Sounds like there needs to be currently then a duplication of setting the verbose name both inside each command class and then on top also for the console() hook.

**Comment by dereuromark** [comment]
As for FileStorage: Here was no console() hook to manually set them.
https://github.com/dereuromark/cakephp-file-storage/blob/2dfbdaabf6a0f2911fe71cd672e0d405338ad314/src/FileStoragePlugin.php
There is a high chance of collision with app names here generally.

Could we maybe always auto prefix with the plugin name here if not otherwise set for the output?
And instead of the dot, maybe just space?

    bin/cake file_storage cleanup

Or to keep current BC

    bin/cake FileStorage.cleanup

Then it would be clear that this is the default plugin command and the app command would still be

    bin/cake cleanup

itself.

**Comment by ADmad** [comment]
> Sure, but I thought the whole idea of having Application or Plugin files setting custom names would make them take precedence over any defaults.

I am pretty sure using `scheduler run` would work as expected, it's just that the `CommandScanner` which generates the list doesn't use the `CommandCollection` but rather scans the directories containing command files and calls the `defaultName()` static method.

**Comment by ADmad** [comment]
Digging further the issue is the use of `HelpCommand::getShortestName()` to decide what name to display in the help text.  Since the default name `run`  (generated by `BaseCommand::defaultName()`) is shorter than your custom name `scheduler run` that former is shown.

Perhaps we should show all possible names in the help instead of just the shortest ones?

**Comment by ADmad** [comment]
The root cause is that the command gets added to the CommandCollection twice, 1st by the `CommandScanner` (due to the `parent::console()`) call with name `run` and then added again with the name `scheduler run`.

**Comment by ADmad** [comment]
The `CommandCollection` tries to give the longer names preference but `HelpCommand` does the opposite and shows the shorter names 🤦 

https://github.com/cakephp/cakephp/blob/4f3aea0e3ccf8be76822166c6c03fc9f28663355/src/Console/CommandCollection.php#L200-L205
