### ISSUE TITLE
Test failures for addPlugins()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17940]
### Description

```
	protected function setUp(): void {
		parent::setUp();

		$this->loadPlugins(['Bake', 'Cake/TwigView', 'Migrations', 'Shim']);
		$this->task = new PluginTask();
	}
```

If now a plugin, e.g. the Bake plugin, starts to load one of the plugins inside, and through composer update this comes in, the tests now fail.

> 1) IdeHelper\Test\TestCase\Generator\Task\PluginTaskTest::testCollect
Cake\Core\Exception\CakeException: Plugin named `Cake/TwigView` is already loaded

I wonder if loadPlugins() should maybe do a loaded check before it actually tries to reload the plugin(s)?

### CakePHP Version

5.1

### PHP Version

8.2

**Comment by LordSimal** [comment]
This is still better than double bootstrapping the app/plugins when the test runs like it was in the past.

If you run into this situation then you know you can adjust the `addPlugins()` method to remove the duplicate plugin.

**Comment by dereuromark** [comment]
Also the order is important here, the wrong order wouldnt work.
But yes, it can be done manually.

**Comment by LordSimal** [comment]
I would be fine with an optional `$strict` param on the `loadPlugins()` method to indicate if it should perform the check before adding or not.

**Comment by ADmad** [comment]
There's no need to continue supporting bad usage. Just avoid duplicate plugin loading in your tests as you would do in your app.
