### ISSUE TITLE
$connection->disableQueryLogging() not available anymore

### ISSUE THREAD

**Issue by PaulHendriks** [cakephp/cakephp#17951]
### Description

I'd like to disable query logging in runtime.
This code doesn't work anymore in CakePHP5:
```
$connection = $query->getConnection();
$connection->disableQueryLogging()
```
Was deprecated in 4.5: https://github.com/cakephp/cakephp/blob/4.x/src/Database/Connection.php#L1076

This suggestion was made in Slack:
```
$connection = ConnectionManager::get('default');
/** @var \Cake\Database\Driver $driver */
$driver = $connection->getDriver();
$driver->logger = null;
```
However, there is no ```$connection->setDriver($driver)``` possibility.

### CakePHP Version

5.1

### PHP Version

8.1

**Comment by LordSimal** [comment]
the problem is more the fact, that this property is protected, therefore a separate method setting that to null would achieve the same behavior as before as far as i can tell

setting the driver back into the connection is not necessary (I believe) since everything is handled by reference
