### ISSUE TITLE
RFC: Deprecate/Remove `BaseCommand::initialize`

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#17950]
### Description

Due to the simple fact, that commands are directly hooked into the DI container, the `initialize` method doesn't really have much of a purpose anymore in my opinion.

Everything, that can be done in the `initialize` method, can easily be moved into the constructor.

This would remove one unnecessary hook from the BaseCommand abstract class.

### CakePHP Version

6.0

**Comment by markstory** [comment]
> This would remove one unnecessary hook from the BaseCommand abstract class.

The main reason we've historically has `initialize()` was for consistency with other classes (controllers, helpers, components etc). I agree that anything users are currently doing in `initialize()` could be done in the constructor. However, I don't know if we're helping users much by removing `initialize()` support.

**Comment by LordSimal** [comment]
That makes sense. Just going to check if there are mayve other classes which need this "hook" like method added but I guess all the important places are already setup with that.
