### ISSUE TITLE
5.2 - Improve workflow for custom exception classes

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#17958]
### Description

Currently to make custom error pages, you have to do a lot of work:

1. Create a [custom exception handler](https://book.cakephp.org/5/en/development/errors.html#custom-exceptionrenderer)
2. Add a method, and write logic to operate the controller from the outside
3. make a template.

Instead a better workflow would be to use controller actions. We package an `ErrorController` in each application so modifying this class will be lower friction. If `ErrorController` has a method that matches the exception type the method will be called. For example:

- The `MissingWidgetException` would call the `missingWidget` method. 
- The   `templates/Error/missing_widget.php` template would be rendered.
 
This is effectively lifting the exception renderer interface up to the controller. I think this will help simplify building custom error rendering.

**Comment by markstory** [comment]
@LordSimal Is this along the lines of what you were thinking?

**Comment by LordSimal** [comment]
Yes, this is exactly what I was thinking.
