### ISSUE TITLE
Ability to add `skipCheckCallback()` to CSRF middleware from within a plugin?

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17984]
### Description

I'm working on a plugin which introduces a route prefix that needs to be exempt from the CSRF checks. 

One way to do that would be [adding `skipCheckCallback()` to where the `CsrfProtectionMiddleware` is initialised in `src/Application.php`](https://book.cakephp.org/5/en/security/csrf.html#skipping-csrf-checks-for-specific-actions). However, because the new route prefix that needs to be excluded is set up in the plugin, it feels right to change CSRF also from within said plugin. This way it's consistent

I came up with this monster inside my `PLUGIN/src/Plugin.php`:

```
<?php

namespace MyPlugin;

use Cake\Core\BasePlugin;
use Cake\Core\PluginApplicationInterface;
use Cake\Http\MiddlewareQueue;

class Plugin extends BasePlugin
{

    public function bootstrap(PluginApplicationInterface $app): void
    {
        parent::bootstrap($app);
    }

    public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        $count = $middlewareQueue->count();
        for ($i = 0; $i < $count; $i++) {
            $middlewareQueue->seek($i);
            $layer = $middlewareQueue->current();
            if (!$layer instanceof \Cake\Http\Middleware\CsrfProtectionMiddleware) {
                continue;
            }
            $layer->skipCheckCallback(function ($request) {
                if ($request->getParam('plugin') === 'MyPlugin' && $request->getParam('prefix') === 'MyPrefix') {
                    return true;
                }
            });
            $middlewareQueue->insertAt($i, $layer);
        }
        return $middlewareQueue;
    }

}
```

However, I am getting:

> A CSRF token is already set in the request.
> Ensure you do not have the CSRF middleware applied more than once. Check both your `Application::middleware()` method and `config/routes.php`.
> Cake\Core\Exception\CakeException

Not only that, it just looks like an ugly approach. And probably not very effective too, if the loop gets executed on every page request handled by the plugin.

So does it make sense to introduce the ability to add exceptions to the CSRF layer that's already been initialised? Unless, of course, it already exists and I missed it.

### CakePHP Version

5

**Comment by markstory** [comment]
I don't think you need to re-insert the middleware back into the queue. You could just add the `skipCallback()` in place. With the `insertAt()` call you're likely getting two copies of the `CsrfMiddleware`.

**Comment by mehov** [comment]
Thank you, that did it. 

To those looking for something similar, here's what I ended up with in my `PLUGIN/src/Plugin.php`:

```php
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
    // Loop through queue directly using Iterator capabilities of MiddlewareQueue
    foreach ($middlewareQueue as $layer) {
        // Skip right away if this is not a CSRF layer
        if (!($layer instanceof \Cake\Http\Middleware\CsrfProtectionMiddleware)) {
            continue;
        }
        // Add the callback
        $layer->skipCheckCallback(function ($request) {
            // Adjust the condition to your needs; I had to allow specific prefix in current plugin
            if ($request->getParam('plugin') === $this->getName() && $request->getParam('prefix') === 'MyPrefix') {
                return true;
            }
        });
        // Once we found the CSRF layer, stop the loop as there's no need to continue
        break;
    }
    return $middlewareQueue;
}
```
