### ISSUE TITLE
new types to StringType mapping is missing

### ISSUE THREAD

**Issue by gcatania-wgs** [cakephp/cakephp#17988]
### Description

The doc claims it was added support for geospatial DB columns of type **linestring**, **polygon** and **geometry**.

The problem is that those column types are actually mapped somehow in the code BUT the respective classes are not present in folder `“src/Database/Type”`.

That means that a DB table, in which you have a GEOMETRY type field, worked fine in CakePHP 5.0.8 and now throws an error “unknown type “geometry” when marshaller is trying to build the respective type.

### CakePHP Version

5.1.1

### PHP Version

8.3.7

**Comment by markstory** [comment]
Could I know more about the error you're getting. Perhaps a stack trace or what database you using? I've added tests for both mysql and postgres and they pass locally for me.

**Comment by ADmad** [comment]
@markstory This is the line triggering the `Unknown type 'geometry'` error:

https://github.com/cakephp/cakephp/blob/ff7df0c75b91049ae3f5db70c035a738f401d081/src/ORM/Marshaller.php#L79

We need to ~~add~~ map the new types added to the TableSchema to `StringType` ( or appropriate) in `TypeFactory::$_types`.

**Comment by markstory** [comment]
> We need to add the new types added to the TableSchema to StringType ( or appropriate) in TypeFactory::$_types.

Oops, I missed that this was related to the marshaller 🤦
