### ISSUE TITLE
Accessing Table class from within Entity?

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#17981]
### Description

What I have
--

I'm in a view template and I have an Entity. I would like to display the name and the ID of the Entity

What I do now?
--

```
echo $entity->title;
```

What I want?
--

```
echo $entity->{$entity->getDisplayField()};
```

Alternatively, just have access to the whole table class:

```
$tableClass = $entity->getSourceTableClass(); // or a better method name
echo $entity->{$tableClass->getDisplayField()};
echo $entity->{$tableClass->getPrimaryKey()};
```

Although I can see how dragging a copy of a table along with each entity can be memory-consuming.

Shortcuts
--
- https://api.cakephp.org/5.0/class-Cake.ORM.Entity.html
- https://api.cakephp.org/5.0/class-Cake.ORM.Table.html#getDisplayField()

### CakePHP Version

5

**Comment by dereuromark** [comment]
Entities dont have that information.
If you need do something like this, first gather all the information before going into the view layer, e.g. in controller/model layer do:
```php
$displayfield = $myTable->getDisplayField();
```
and pass that down to do what you want to do.
Behaviors do something similar here usually.

In the view you usually don't want to access the tables directly anymore.

**Comment by mehov** [comment]
#10843

**Comment by mehov** [comment]
@dereuromark Thank you for a quick reply

> Entities dont have that information.
> If you need do something like this, first gather all the information before going into the view layer, e.g. in controller/model layer do:
> and pass that down to do what you want to do.
> In the view you usually don't want to access the tables directly anymore.

You're right. But here I want a reusable view for a navigation bar, that I will `$this->extend()` from other views. 

I'm looking for an elegant way to have this reusable view pick up everything it needs automatically. This is because I feel like passing each variable individually will both clutter controller actions and require consistency across those actions. 

So I figured I have to just agree on passing `$entity` only, and have it figure out the rest.

I feel rogue today, so I will probably use this in my reusable view.

```
$table = \Cake\ORM\TableRegistry::getTableLocator()->get($entity->getSource());
```

Nasty :D

**Comment by dereuromark** [comment]
Well, in those cases I would probably still not use entities themselves, but encapsulate them maybe within a different ([DTO like?](https://github.com/dereuromark/cakephp-dto)) structure to have meta data included.
Or use a view helper at least to wrap things a bit more.

All right, good luck then.

**Comment by mehov** [comment]
You're right. I will use a view helper. Thanks for the tip, and for introducing me to DTOs!
