### ISSUE TITLE
Add 2 mimetypes to Cake\Http\Response::$_mimeTypes for .cjs and .mjs asset files

### ISSUE THREAD

**Issue by glb-blg** [cakephp/cakephp#18004]
### Description

Hi everyone,

I have a problem with .cjs and .mjs assets (through AssetMiddleware). They are sent with a content-type "application/octet-stream", so that secure browsers won't execute them :-(

I searched everywhere for a workaround but this is complicated...

Is it possible to add 2 mimetypes to Cake\Http\Response::$_mimeTypes ?

```php
protected array $_mimeTypes = [
        'cjs' => 'application/javascript',
	'mjs' => 'application/javascript',
	...
];
```

Thanks by advance 👍
Rz

### CakePHP Version

5.1

**Comment by dereuromark** [comment]
I didnt know those file types exist.
https://dev.to/nipu/js-cjs-and-mjs-defference-5f21

Indeed, they can be added. 
You can make a PR to do so.

Until then you should be able to extend and set your own ones on top.

**Comment by ADmad** [comment]
For this specific use case an alternative would be use `mime_content_type()` to detect the type in `AssetMiddleware` if `Response::getMimeType()` fails. IMO that's a better option than continually bloating that mime type map.

**Comment by glb-blg** [comment]
We always can extend everything, for sure.  I want to say : no problem for me, I will manage.
But I think it could be a good idea, indeed, to allow developers to update this mimeTypeMap, eventually in the same way as for ServerRequest detectors ?
This solution would : 
- please developers as they don't have to ask each time they need a new extension
- please developers as they don't have to create new extending code
- please CakePHP team as they don't have to worry about updating this map

... ?

Anyway, thanks for all you do, guys !

**Comment by glb-blg** [comment]
> I didnt know those file types exist. https://dev.to/nipu/js-cjs-and-mjs-defference-5f21
> 
> Indeed, they can be added. You can make a PR to do so.
> 
> Until then you should be able to extend and set your own ones on top.

Yes, more and more JS libs are switching to cjs : recently chroma.js and SwipperJs

**Comment by ADmad** [comment]
> But I think it could be a good idea, indeed, to allow developers to update this mimeTypeMap, eventually in the same way as for ServerRequest detectors ?

Yes, that's a good idea. Currrently there is `Response::setTypeMap()` but a static interface would probably make more sense here.

**Comment by dereuromark** [comment]
With https://github.com/cakephp/cakephp/pull/18012#event-15096041782 merged for 5.next
Do we still want to patch 5.x for now for those 2 types?

**Comment by glb-blg** [comment]
Thank you for your responsiveness, guys 👍
Fyi, don't rush for me to patch !
🙏

**Comment by dereuromark** [comment]
Well you can make that patch yourself :)
Otherwise we can close

**Comment by dereuromark** [comment]
PR open.
