### ISSUE TITLE
ContentsContain error - "sprintf(): Too few arguments"

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#18003]
### Description

"sprintf(): Too few arguments" is the result of ContentsContain::toString() when the tested command console output (`$this->contents` in ContentsContain) contains string "%s".

A stacktrace to a call to `$this->assertErrorContains("my text");` :
```
/project/vendor/cakephp/cakephp/src/TestSuite/Constraint/Console/ContentsContain.php:44
/project/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestTrait.php:276
/project/tests/TestCase/Command/MyCommandTest.php:416
```

### CakePHP Version

4.0

### PHP Version

7.4

**Comment by markstory** [comment]
What version of Cake 4 are you using? I tried quickly to reproduce this error and couldn't with 4.5.8.

**Comment by dereuromark** [comment]
I remember we fixed something here in 5.x for https://github.com/cakephp/cakephp/pull/17341
And nothing has changed in 4.x for 2+ years here.

Upgrading should fix this automatically.

**Comment by bancer** [comment]
> Upgrading should fix this automatically.

Yeah, that's right.
