### ISSUE TITLE
Ability to set `_https` inside named configuration

### ISSUE THREAD

**Issue by mehov** [cakephp/cakephp#18019]
I am defining a named route inside `config/routes.php`. I want to force that route to be HTTP, not HTTPs.

The `_https` flag, listed under [Reserved Route Elements](https://book.cakephp.org/5/en/development/routing.html#reserved-route-elements), is what I'm looking for. And because that section is under [Connecting Routes](https://book.cakephp.org/5/en/development/routing.html#routes-configuration) (see Page Contents), that kind of implies I can use these Reserved Route Elements when connecting my routes.

What I did
--

```php
// config/routes.php
$routes->connect(
    '/example',
    [
        'controller' => 'Articles',
        'action' => 'example',
    ],
    [
        '_name' => 'example',
        '_host' => 'example.com',
        // tried everything, including the legacy `_ssl`
        '_https' => false,
        '_ssl' => false,
        '_scheme' => 'http',
    ]
);
```

```php
// elsewhere
echo Router::url(['_name' => 'example']);
```

What I expected to happen
--

> http://example.com/articles/example

What happened
--

> https://example.com/articles/example

**Comment by mehov** [comment]
I do get `http` when I call it as `Router::url(['_name' => 'example', '_https' => false])`.

And I can see in https://github.com/cakephp/cakephp/blob/19af8494b1f2fdef1ab405385a6fed0db7699ef7/src/Routing/Router.php#L408 that it decides on `_https` early on, seemingly before even resolving the named route, so not giving it a chance.

**Comment by mehov** [comment]
(Somewhat related: cakephp/cakephp#17971.)

**Comment by markstory** [comment]
Are you looking to define a route that is always generated with an http protocol, when the application and rest of the URLs are generated with https?  This isn't something that is possible today.

**Comment by mehov** [comment]
> Are you looking to define a route that is always generated with an http protocol, when the application and rest of the URLs are generated with https? This isn't something that is possible today.

Thank you for clarifying! Yep, that's what I was after.

My application runs on HTTPs, but I need to have a plain HTTP endpoint that responds to some other application. I don't expect it to be exposed to the public, and it doesn't serve any sensitive info anyway. It only receives some debugging data from said application and allows it to proceed. I can, of course, serve that endpoint as HTTPs, but my observation is that plain uncomplicated HTTP is much faster overall in this case, let alone there's 0% chance of having certificate problems.

For now, I will just be doing `Router::url(['_name'=>'my:path:name', '_https'=>false]))`.

Because this seems like an edge case that can be worked around with existing tools, I think I should close the issue. But I can see that you added some tags, so of course you can always reopen if you want :)
