### ISSUE TITLE
5.1: Runtime schema changes have no effect

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#18024]
### Description

When trying to change the schema for a single action, it always ignores (resets) the setting when reading the data, rendering it impossible.

    $this->QueuedJobs->getSchema()->setColumnType('data', 'string');

Right after this call it is still "json", as before, making any such call void all the time.

    $queuedJob = $this->QueuedJobs->get($id);

Will still fetch it as the type before.

The book says we should use getSchema() for default setup of our types, but I dont think that works, as this seems to cause this reset:

	/**
	 * @return \Cake\Database\Schema\TableSchemaInterface
	 */
	public function getSchema(): TableSchemaInterface {
		$schema = parent::getSchema();
		$schema->setColumnType('data', 'json');

		return $schema;
	}

https://book.cakephp.org/5/en/orm/database-basics.html#connecting-custom-datatypes-to-schema-reflection-and-generation

We either need to change the code, or the book here it seems.

### CakePHP Version

5.1

### PHP Version

8.3

**Comment by dereuromark** [comment]
Another place in the docs seem to refer still to initialize():
```php
public function initialize(array $config): void
{
    $this->getSchema()->setColumnType('status', EnumType::from(ArticleStatus::class));
}
```
That seems to be more correct as to the expectation of being able to change it on the fly later on in the app.

**Comment by ADmad** [comment]
I fail to understand how overriding `getSchema()` in the table class would cause any issue. The overrides in it are done *before* your on the fly call to `setColumn()`.

**Comment by dereuromark** [comment]
You can check.
In my tests it only started to work once I moved it to initialize()

```php
public function data(?int $id = null) {
    // currently json and thus returning it as array
    $this->QueuedJobs->getSchema()->setColumnType('data', 'string');
    // I need it unmodified here for edit mode
    dd($this->QueuedJobs->getSchema()->getColumnType('data')); // returns still json

    $queuedJob = $this->QueuedJobs->get($id);
    // and result on find/get is still the json array instead of the string
}
```

I have at least the following plugins beside Queue that could also need a fix here:
Captcha, Geo, Feedback, Decimal, FileStorage
They all use that getSchema() overwrite that seems to block the dynamic change.

**Comment by dereuromark** [comment]
@ADmad 
is it possible that the ORM itself at some point can call the getSchema(), maybe even some behaviors or alike in some beforeFind() callback?
Any such call, even as a pure "getter" would reset the custom set. And without the user knowing or suspecting that.
So it really seems counter productive to use that to set defaults.
Unless we cache the result in a property and reuse the cached defaults here instead of re-calling the internal calls.

The reason it didnt happen with the old method was exactly that: It was then cached internally in the property it seems
Refs https://github.com/cakephp/cakephp/pull/16739/files

Anyway, for now the docs change at least makes this more clear.
And at least I will adjust my plugin table classes to adhere to the proper defaulting, so that any user customizing it on project level wouldn't run into a no-op.

**Comment by ADmad** [comment]
@dereuromark Can you provide a minimal test case in the core testsuite to produce your problem? I then dig into it to figure out the cause and potentially fix it over the weekend.

**Comment by dereuromark** [comment]
tests/TestCase/ORM/TableTest.php
```php
    public function testSchemaTypeOverrideAfterGetSchema(): void
    {
        $table = new class (['alias' => 'Users', 'table' => 'users', 'connection' => $this->connection]) extends Table {
            public function getSchema(): TableSchemaInterface
            {
                $schema = parent::getSchema();

                $schema->setColumnType('username', 'foobar');

                return $schema;
            }
        };

        $this->assertSame('foobar', $table->getSchema()->getColumnType('username'));

        $table->getSchema()->setColumnType('username', 'string');
        $this->assertSame('string', $table->getSchema()->getColumnType('username')); // fails of course
    }
```
so basically getSchema() must always be empty or you shoot yourself in the foot.

**Comment by ADmad** [comment]
Okay, I understand now, the problem isn't with the `setColumnType()`, it does update the schema but since the `getColumnType()` isn't chained the update is lost when `getSchema()` is called again.

**Comment by markstory** [comment]
The changes aren't lost, they are overwritten by the contents of `getSchema()`. I don't think we can fix this at the framework level, the code is doing exactly what you've asked of it.

**Comment by dereuromark** [comment]
Exactly, it does what we ask.
Thus my doc change and more awareness not to recommend to ever overwrite getSchema() here with additional changes internally :)
