### ISSUE TITLE
Chronos' addMinutes and subMinutes doesn't work

### ISSUE THREAD

**Issue by marcdebus** [cakephp/cakephp#18058]
### Description

I would like to modify a DateTime instance with addMinutes(3) or subMinutes(4), but that didn't work.
It is only possible with $datetime->modify('3 minutes');

```php
        if ($group->before) {
            $begin->subMinutes($group->before); // not work
            $begin = $begin->modify('-2 minutes'); // works
        }

        if ($group->after) {
            $end = $end->modify('+5 minutes'); // works
            $end->addMinutes($group->after); // not works
        }
``` 

Same with addHours etc.

### CakePHP Version

5.1.2

### PHP Version

8.3

**Comment by dereuromark** [comment]
You need to properly use immutability here
Your subMinutes() call does work, but you never assign to a variable, so yes, only the 2nd example works where you do that.

    $modified = $begin->subMinutes($group->before);

and

    $modified = $end->addMinutes($group->after);

**Comment by marcdebus** [comment]
I thought I had checked that. The return value of that function is static, so I assumed it manipulates the DateTime object directly.

**Comment by marcdebus** [comment]
Sorry, my mistake. It works...

**Comment by dereuromark** [comment]
static means that it does not return the same object, but a different one of the same kind (with the different data), thats the key part of immutability, not to return it"self".
