### ISSUE TITLE
RFC: Easier Exception render customization

### ISSUE THREAD

**Issue by LordSimal** [cakephp/cakephp#18067]
### Description

Currently one either has to write their own [WebExceptionRenderer](https://book.cakephp.org/5/en/development/errors.html#custom-exceptionrenderer) or hook into the `Exception.beforeRender` event [to set a string result](https://github.com/cakephp/cakephp/blob/5.x/src/Error/Middleware/ErrorHandlerMiddleware.php#L147-L152) to have a custom exception page returned.

This could be improved in my opinion into an additional method inside the Application class which gets passed down all necessary information.

I was thinking of something like:
```
public function error(Throwable $exception, ServerRequestInterface $request) 
{
    // logic specific to that exception/request/whatever else can be determined at this point
}
```

* if a string is returned, render that string directly
  * would be nice if this can somehow be connected to the ErrorController which is present by default to have an easier time building a custom error page for specific (custom) Exceptions 
* if nothing is returned, continue with the already present logic which just renders either the error400.php or error500.php depending on the exception.

In the end it should be easier to 
* understand how the already present exceptions get rendered and maybe even adjust that behavior however one likes
* map custom exceptions to already present render logic or new ErrorController actions

### CakePHP Version

6.0

**Comment by markstory** [comment]
> map custom exceptions to already present render logic or new ErrorController actions

Isn't this something we already kind of support? In 5.2 #17960 will be released which will let custom exceptions be mapped to methods on the `ErrorController` which can either return a response or take control of the remaining render process.

If we added another `error` hook to `Application` could we also remove one of the existing paths? I feel like we're collecting many different ways to achieve the goal of 'custom error pages'.

**Comment by LordSimal** [comment]
In #17960 we are inflecting the method name from the exception classname which is fine if the exceptions are all named uniquely.

But what If a plugin has the same exception name as one already present in cake? What If I want to map specific exceptions with the same name but with different namespaces to different responses?

E.g. `Cake\Http\Exception\ForbiddenException` and `Authorization\Exception\ForbiddenException`

Sure, the first is a HTTPException and the second a an auth exception which gets caught by the Auth middleware anyway, but it shows, that Exception classnames can colide very easily.

We are not passing down the exception to the ErrorController method, therefore the user doesn't have all the necessary data to actually do the logic needed to render different responses.

---

The error hook was just an idea of mine since the Application class is the core which is used by both the web as well as cli part.
I can also see a separate ExceptionHandler class in the app template which contains all the necessary default configs and hooks.

**Comment by markstory** [comment]
> We are not passing down the exception to the ErrorController method, therefore the user doesn't have all the necessary data to actually do the logic needed to render different responses.

That was changed in #17963 and the error will be passed into the controller method, which would allow applications to refine the template selection if they want to have discrete error pages for plugins with overlapping classnames.

**Comment by LordSimal** [comment]
I missed that one, thanks. 

Seems like all that is needed then is proper documentation on how to use that new functionality with CakePHP 5.2

With that, this can definitely be closed.

**Comment by LordSimal** [comment]
It already is, its just not linked properly in Github.
https://github.com/cakephp/docs/pull/7972

**Comment by LordSimal** [comment]
There are already docs present in 5.next, I just couldn't find the PR since its not linked.

**Comment by markstory** [comment]
Cool. I'm assuming the new enhancements give enough control to cover your usecases? If not lets reopen and continue the discussion.
