### ISSUE TITLE
Expected type 'Cake\Datasource\RepositoryInterface|Cake\Datasource\QueryInterface|string|null'. Found 'Cake\ORM\Query'

### ISSUE THREAD

**Issue by squalltua** [cakephp/cakephp#18113]
#### Description
Got error form `VSCode` with `PHP Intelephense plug-in`. Error about `Expected type. intelephense(P1006)`. but code is working fine. run no error. just `VSCode` show intelephense error.
`
Expected type 'Cake\Datasource\RepositoryInterface|Cake\Datasource\QueryInterface|string|null'. Found 'Cake\ORM\Query'.intelephense(P1006)
`

![Image](https://github.com/user-attachments/assets/258c8eef-7f61-4f46-82a7-317b7f60fc3a)

### CakePHP Version

5.1.4

### PHP Version

8.3

**Comment by ADmad** [comment]
Change the return type of your `getAllProducts()` to `Cake\ORM\SelectQuery`.
