### ISSUE TITLE
Schema diff between primary key with and without AUTO_INCREMENT (MySQL)

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1844]
Created by **Šarūnas Dubinskas**, 29th Dec 2010. *(originally [Lighthouse ticket #1416](http://cakephp.lighthouseapp.com/projects/42648/tickets/1416))*:
- - - -

Currently i have table without AUTO_INCREMENT attribute on primary key column. I've added AUTO_INCREMENT attribute on column, but schema diff does not catch it as a change. How to solve this issue?

**Comment by markstory** [comment]
Closing as most migration issues that we've had in the past are fixed in 3.0 by using phinx.
