### ISSUE TITLE
Enhancement Request: Pass [USE|FORCE|IGNORE] INDEX as a Model::find() option

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1847]
Created by **Adam Friedman**, 26th Jan 2011. *(originally [Lighthouse ticket #1484](http://cakephp.lighthouseapp.com/projects/42648/tickets/1484))*:
- - - -

There are many complaints CakePHP's find method does not handle complex queries and joins very well, and their performance can become extremely slow.  The worst part is that the hapless developer has little way to modify the SQL syntax in order to optimize the query.  One brilliant way to optimize complex queries is to provide index hints to the database.  Below is a way to make that happen in find().

*** What I'd like to do:

Pass an 'index' option into the find options.  

*** What it will look like:

```php
$Story->find('all',array(
 'conditions'  => ...,
 'contain'     => array('Category','Keyword'),
 'order'       => ...,
 'index'       => array(
      'Category' => 'published_at',  
      'Story'    => array('force' => 'modified_at'), 
      'Keyword'  => array('ignore' => 'special')      
  )
));
```

*** What happens under the hood:

Then, in each DBO driver, this 'index' array would translate into the proper SQL syntax.  In MySQL, it would put the index clause after the JOIN table or FROM table statement for that Model.

So, to revisit the options:

```php
'index'       => array(
 'Category' => 'published_at', //no key here,so the default is USE INDEX (published_at)
 'Story'    => array('force' => 'modified_at'), // FORCE INDEX (modified_at)
 'Keyword'  => array('ignore' => 'special')     // IGNORE INDEX (special)
)
```

What do you think?

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.

**Comment by iglocska** [comment]
Despite this being old, this would be incredibly useful.

**Comment by markstory** [comment]
@iglocska Fair, but it hasn't been useful enough for anyone to build.
