### ISSUE TITLE
Do not use view cache when the user submits a form

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1884]
Created by **FelipePtChO**, 22nd Jul 2011. *(originally [Lighthouse ticket #1847](http://cakephp.lighthouseapp.com/projects/42648/tickets/1847))*:
- - - -

As far as I know, you can not cache actions that show a form, because the data submitted does not pass through the controller.

I don't know, but I think this can be solved if the cache is not taken into account when the user submits data.

**Comment by markstory** [comment]
Closing as CacheHelper is deprecated and won't be improved any further.
