### ISSUE TITLE
default order broken with model aliases

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1893]
Created by **[euromark](https://github.com/dereuromark)**, 29th Aug 2011. *(originally [Lighthouse ticket #1950](http://cakephp.lighthouseapp.com/projects/42648/tickets/1950))*:
- - - -

the message model has:

	public $order = array('Message.created' => 'DESC');

as well as 

	public $belongsTo = array(
		'ParentMessage' => array(
			'className' => 'Message',
			'foreignKey' => 'parent_id',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		), ...

so far so good.

but the edit method with

	$parentMessages = $this->Message->ParentMessage->find('list');

results in
	SQL Error: 1054: Unknown column 'Message.created' in 'order clause'
	Query: SELECT `ParentMessage`.`id`, `ParentMessage`.`subject` FROM `site_messages` AS `ParentMessage`   WHERE 1 = 1   ORDER BY `Message`.`created` DESC
It always uses Message.created - if set as default value in $order.

	public $belongsTo = array(
		'ParentMessage' => array(
			...
			'order' => array('ParentMessage.created' => 'DESC')
		),
	);
does not do the trick either.

and you cannot use $order = array('created' => 'DESC') right now as it results in ambiguous queries in the index and other views which have joins and belongsTo relations.

i propose:
changing the default var $order to expect a simple

	public $order = array('created' => 'DESC');

whose created key is then "completed" to Message.created or ParentMessage.created on runtime (always the current model if no specific model is given like "MyOtherMessage.created").
this way it will work with all aliases as well as all find statements.

of course you could hack around it using __construct()
but what good does var $order do if it cannot be used in such simple use cases.

**Comment by dereuromark** [comment]
For reference, for all those that need a proper aliasing for the $order property in 2.x, the respective branch of the [Shim plugin](https://github.com/dereuromark/cakephp-shim) does that for you. It has also been shimmed into 3.x in case one needs to upgrade his 2.x app and has those set (as do I).
