### ISSUE TITLE
Pagination sort link on translated columns

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1912]
Created by **Brendon Gleeson**, 3rd Nov 2011. *(originally [Lighthouse ticket #2214](http://cakephp.lighthouseapp.com/projects/42648/tickets/2214))*:
- - - -

#### What I did
I have a model using the Translate Behavior. I created a result set using the paginate() controller method and created a simple table in the view with header columns using PaginatorHelper::sort() method. 

#### What happened
The sort links/column headings which were specified in the Translate Behavior were not working, the "ORDER BY" clause was not being appended to the sql query, neither was the correct link being generated for the sort links.

I managed to fix this be commenting out a particular line in the CakePHP core controller.php, line 1136:
```
...
//unset($options['order'][$key]);
...
```

I am not sure what sort of repercussions this change makes but everything seems to work properly now as expected. I am using I18n__[column_name].content as the column in PaginatorHelper::sort()

**Comment by lorenzo** [comment]
Given the complexity of this feature, I doubt it will be implemented in 2.x. Closing for that reason.
