### ISSUE TITLE
Router should provide returning as array

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1926]
Created by **[euromark](https://github.com/dereuromark)**, 3rd Jan 2012. *(originally [Lighthouse ticket #2431](http://cakephp.lighthouseapp.com/projects/42648/tickets/2431))*:
- - - -

based on initial thread:
http://groups.google.com/group/cake-php/browse_thread/thread/887d78da3921dd68

current methods either return a string - Router::url - or a complex multilevel array with named and pass sub-arrays.

the router method should be able to return the url as a one-leveled (flat) array for post-processing before passing it on to Html::link() or doing sth else with it etc.
This is often the case when we want to add some named or pass params or some hash.
Especially since Cake is handling most of the internal urls as array such a functionality is missing.

example: 

    admin/authplugin/users/edit/2 

I would expect to find some router method to get 

    $url = array( 
        'admin' => 1,
        'plugin' => 'authplugin',
        'controller' => 'users',
        'action' => 'edit',
        2, 
        'key' => 'val'
    );

for example - maybe with a method Router::urlAsArray():

    $array = Router::urlAsArray('action'=>'edit', 2, 'key'=>'val');

which would be pretty much exactly what we normally pass on to the url generating methods.

it would also be similar to the result of Router::parse() but it already 
contains the passed and named params as expected to easily adjust it before passing it to Html::url() or Html::link(): 

    $url[#] = 'somehash'; 
    or 
    $url[] = 'somepassedparam'; 
    or 
    $url['key'] = 'somenamedparam'; 
    echo $this->Html->link('Title', $url);

currently we have to concatenate extra params with the final url string or resolve the complex url array manually.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
