### ISSUE TITLE
Use of td-specific class in $this->Html->tableCells() disregards $useCount 

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1927]
Created by **milsom**, 4th Jan 2012. *(originally [Lighthouse ticket #2436](http://cakephp.lighthouseapp.com/projects/42648/tickets/2436))*:
- - - -

#### What I did
``` php
echo $this->Html->tableCells(array(
  'Cell1',
  array('Cell2', array('class' => 'foo'))
), null, null, true);
```

#### What happened
``` html
<tr>
  <td class='column-1'>Cell1</td>
  <td class='foo'>Cell2</td>
</tr>
```

#### What I expected to happen
``` html
<tr>
  <td class='column-1'>Cell1</td>
  <td class='foo column-2'>Cell2</td>
</tr>
```

I've made a change to HtmlHelper.php so that the useCount class is merged with td-specific classes:
https://github.com/milsom/cakephp/commit/7201de9a256812701fc15b63d1801b63c9d26d88

**Comment by dereuromark** [comment]
Closing as PR is open for it.
