### ISSUE TITLE
Postgres schema definition to model

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1939]
Created by **Tymon**, 13th Feb 2012. *(originally [Lighthouse ticket #2573](http://cakephp.lighthouseapp.com/projects/42648/tickets/2573))*:
- - - -

#### What I did
Make database with multiple schemas and set default connection data

#### What happened
System cannot find tables form models in different schemas

#### What I expected to happen
Could set schema directly in model or explain how to set multiple schema support in doc :)

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
