### ISSUE TITLE
Tree Behavior enhancement request

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1941]
Created by **Tien Van Vo**, 21st Feb 2012. *(originally [Lighthouse ticket #2599](http://cakephp.lighthouseapp.com/projects/42648/tickets/2599))*:
- - - -

#### What I did

I have example : 

In TestTree Model

var $actsAs = array('Tree' => array('depth'=>3));

Data of table  test_trees :

+Node1
     - Node1.1
       - Node1.1.1
       - Node1.1.2
     - Node1.2
+Node2
     - Node2.1
       - Node2.1.1
     - Node2.2

For example : 
I want config the tree node depth ( tree paths) maximum is 3, then i can't add children for Node.1.1.1, Node.1.1.2 and Node2.1.1
Which can only add children for Node1.1, Node1.1, Node2.1 and Node2.2

#### What happened

I hope Tree Behavior become support that

Thanks

**Comment by AD7six** [comment]
This isn't directly implemented, but it is trivial to do. 3.x has [a getLevel function](https://github.com/cakephp/cakephp/blob/3.0.0-RC2/src/ORM/Behavior/TreeBehavior.php#L882) and support to [store the level in a field](https://github.com/cakephp/cakephp/blob/3.0.0-RC2/src/ORM/Behavior/TreeBehavior.php#L159-L165)

To limit the depth of a tree only needs a validation rule to read the parent level field (or call `$int = $table->getLevel($parentNode')`) and check that it's less than whatever you want it to be.

Closing as it's not something the tree behavior itself should be responsible for IMO (it's just a validation rule) and it's easy to implement in app land code.
