### ISSUE TITLE
Date, datetime and time validation

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1942]
Created by **JambaFun**, 21st Feb 2012. *(originally [Lighthouse ticket #2601](http://cakephp.lighthouseapp.com/projects/42648/tickets/2601))*:
- - - -

Hi!

I have replaced the core date, datetime and time validation rules with something along the lines of this:

``` php
function datetime($data, $format) {
    $value = array_pop($data);
    $time = strtotime($value);
    if ($time !== false) {
        return $value === strftime($format, $time);
    }
    return false;
}
```

For instructions on how to specify $format see [php.net](http://php.net/strftime).

I think my solution has the benefit of allowing the user to be more specific about the format of the date/time-string. There are also cases where the current validation rules doesn't work, e.g. 2012-02-21 11:38:40.

On the other hand, if you want to allow several different formats to be valid, this approach won't work very well. Therefore I don't see my solution replacing what we have now, but as a compliment I think it serves very well.

(PS. Is there a preferred forum for suggestions like these? Is this is?)

**Comment by markstory** [comment]
Closing as 3.x supports locale based format parsing and validation.
