### ISSUE TITLE
HttpSocket does not support connection keep-alive

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1961]
Created by **Christophe Vandeplas**, 4th May 2012. *(originally [Lighthouse ticket #2854](http://cakephp.lighthouseapp.com/projects/42648/tickets/2854))*:
- - - -

#### What I did
1. create an HttpSocket()
2. set the request parameters with 'Connection' => 'keep-alive'
3. do more than one request using the socket

#### What happened
Only one connection was performed.

#### What I expected to happen
The same socket/connection is reused.

#### Code example
``` php
$HttpSocket = new HttpSocket();
$uri = $this->Server->data['Server']['url'].'/events';
$request = array(
        'header' => array(
                'Accept' => 'application/xml',
                'Content-Type' => 'application/xml',
                'Connection' => 'keep-alive'
        )
);
for ($i=1; $i< 5; $i++) {
    $response = $HttpSocket->get($this->Server->data['Server']['url'].'/events/'.$i, '', $request);
    print_r($response);
}
$HttpSocket->disconnect();
```

This only prints one $response.
The subsequent $response are empty:
``` php
HttpResponse Object
(
    [body] => 
    [headers] => Array
        (
        )

    [cookies] => Array
        (
        )

    [httpVersion] => HTTP/1.1
    [code] => 0
    [reasonPhrase] => 
    [raw] => 
)
```

It seems that someone else had the same problem/feature-request in 2009: http://www.mail-archive.com/tickets-cakephp`@googlegroups`.com/msg01754.html

Thanks

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
