### ISSUE TITLE
Passive associations in Models

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1963]
Created by **Reuben Helms**, 17th May 2012. *(originally [Lighthouse ticket #2886](http://cakephp.lighthouseapp.com/projects/42648/tickets/2886))*:
- - - -

I've heard that Models might be getting some work done on them in CakePHP 3.0.  I've a request for passive associations.

Occasionally you may have a relationship between models that is not appropriate to load all the time.  A reason might be that it is a hasMany and there are far too many records to load without further conditions being placed on the join.

Currently, there are a few options for this.

First is to have the association in the model, but unbindModel in every place that doesn't need it.  Only practical if the association is used often.

Second is to document the association in the model, but comment it out, and perform a bindModel when you need it.  Only practical if the association is used rarely, but requires the location of the bindModel to perform the binding.  If it only happens once, then fine, but if you have to do it a couple of times, you start repeating yourself.  Ideally, the model should be the place where associations are documented and stored, not controllers or components.

My request is for passive associations.  A property would be stored on the association, called passive or active.  The default would be false for passive or true for active, to maintain current functionality.  If true for passive, or false for active, the association would be ignored when doing joins.  

If an association was initialized as passive to begin with, it could be activated via $this->Model->activateModel(array('hasMany' => 'AssociatedModel')); and deactivated using $this->Model->deactivateModel(array('hasMany' => 'AssociatedModel'));

This allowance for active and inactive associations would allow all associations to be put on the model, and activated as needed in a DRY fashion.  All you'd need to specify is the association type and model/relationship key, but the rest would be defined on the model.  Usage of bindModel() and unbindModel() would still be allowed.

I'm not sure if you would allow $this->Model->AssociatedModel->find() if the association was passive.  I'd probably like to, but that might break some fundamental conveniences with associations.

The current work around would be to use the conditions clause on the association, and set it to false.  The association would be there, and the join would be performed, but yield no results.  I haven't tested this method fully yet, so it many not be practical for certain types of relationships.  Further more, it would not be ideal if you wanted to have actual conditions on the association, since you'd need to set that condition instead of unsetting on the association when you wanted to use it.

**Comment by dakota** [comment]
Is this something we still want to look at? It is very easy to enforce strong/default relation loading with a beforeFind in user land code. Should the core have this as a feature? Would probably be a specific config on the association, and only for 1-1 relations?

**Comment by markstory** [comment]
@dakota I think the new contain() semantics in 3.x make this obsolete.
