### ISSUE TITLE
behavior that make a call to Model::schema() produces a "table missing" error inside testing suite, if the models have HABTM relationship

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1970]
Created by **Mauro Zadunaisky**, 13th Jun 2012. *(originally [Lighthouse ticket #2957](http://cakephp.lighthouseapp.com/projects/42648/tickets/2957))*:
- - - -

I found an issue when trying to test models with HABTM relationships. I’ve uploaded a little project into https://github.com/maurozadu/habtm_test_schema so you can see the problem in real code (you can find the sql dump in app/Config/Schema/schema.sql). Once you have the project settled you just need to run any test case and you will notice that a “table missing” error is shown, even when all the fixtures are in place.

The error only appears under the following conditions:

* Two models with a hasAndBelongsToMany relationship. If you don’t have HABTM relationships everything is ok.
* The two models’ fixtures import the table schema, the problem does not exists if the fixtures use field definition. The fixture for the HABTM relationship can use import or field definition without any impact with this issue.
* The models use a Behavior and that Behavior makes a call to Model::schema(). If you avoid the call to Model::schema() you won’t have any error.

I believe the issue is related to datasources. I’ve spent a couple of hours trying to solve the problem but my knowledge of the Cake core is pretty limited.

Thank you!

**Comment by lorenzo** [comment]
This is not an issue in 3.0 and I don't think it can be implemented differently in 2.x
