### ISSUE TITLE
Allow HasMany to have the append or replace strategy like BelongsToMany

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1993]
Created by **Marco Manieri**, 13th Sep 2012. *(originally [Lighthouse ticket #3209](http://cakephp.lighthouseapp.com/projects/42648/tickets/3209))*:
- - - -

#### What I did
Item hasMany ItemRows

ItemRows id 1,2,3 are related to Item.id 1 (ItemRow.item_id=1)

$this->Item->saveAssociated(array(
  'Item'=>array(
    'id' => 1,

  [...]
  ),

  'ItemRow' => array(
    0 => array(
      'id' => 3,
      [...]
    ),
    1 => array(
      'id' => null,
      [...]
    ),
    2 => array(
      'id' => null,
      [...]
    ),

  )
));

#### What happened
ItemRows records with id 1,2,3 still exists with addition of the 2 new created ones (i.e. id 4,5)

#### What I expected to happen
be able to specify an option to only leave the saved associated rows.
i.e.
$this->Item->saveAssociated(array([...]),array('deleteothers'=>true))
should delete ItemRows id 1 & 2 to leave id 3 + newly created 4 & 5...

**Comment by ninthvector** [comment]
Am I correct in that this feature has not been built into CakePHP 3? I've been reading through the 3.0 Book and I'm not finding a way to do it, but finding it hard to believe as it seems like a fairly standard need.

**Comment by markstory** [comment]
@ninthvector Yes it is still not supported for hasMany associations. It has been implemented for belongsToMany associations though. If it was a built-in feature of the ORM how would you expect to enable it on a per save() basis or as part of the relationship definition?

**Comment by dilab** [comment]
Can we have another another saveStrategy other than append or replace in hasMany relationship, which is to set the foreign-key to NULL or 0 by CakePHP.

**Comment by markstory** [comment]
@dilab `replace` mode does that if the foreign key is nullable and the association is not-dependent.

Closing as this is an oldie that is now implemented.
