### ISSUE TITLE
Suggestion for validating foreign keys

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1995]
Created by **JambaFun**, 15th Sep 2012. *(originally [Lighthouse ticket #3213](http://cakephp.lighthouseapp.com/projects/42648/tickets/3213))*:
- - - -

I call it isForeignKey and I use it all the time to verify that a field is a valid foreign key for a belongsTo relationship. Add to Model class.

    function isForeignKey($data) {
        foreach ($data as $key => $value) {
            foreach ($this->belongsTo as $alias => $assoc) {
                if ($assoc['foreignKey'] == $key) {
                    $this->{$alias}->id = $value;
                    return $this->{$alias}->exists();
                }
            }
        }
        return false;
    }

I would assume most of you validate foreign keys somehow and I don't see any reason why this shouldn't be built into CakePHP's core.

**Comment by lorenzo** [comment]
I think a plugin is the best solution we can have for the 2.x branch :)
