### ISSUE TITLE
Timezone with saved fields

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2007]
Created by **Ahmad**, 3rd Nov 2012. *(originally [Lighthouse ticket #3337](http://cakephp.lighthouseapp.com/projects/42648/tickets/3337))*:
- - - -

#### What I did
create new form or edit with date or time field

#### What happened
when you save the time or date field in the form it will save it without converting the time to the server timezone

#### What I expected to happen
currently I'm doing it manual
1. User will submit his alert time & date
2. before save I will convert it to UTC
3. will save it to the database.

It will be excellent if this can be done automatically (similar to create and modified fields).

**Comment by lorenzo** [comment]
This can actually be done with custom database types in 3.0
