### ISSUE TITLE
Build query strings, taking care of empty values.

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2010]
Created by **[Ber Clausen](https://github.com/bar)**, 5th Nov 2012. *(originally [Lighthouse ticket #3342](http://cakephp.lighthouseapp.com/projects/42648/tickets/3342))*:
- - - -

I don't know how to label this, feature suggestion?

#### What I did
Built an HTTP POST request using HttpSocket with this as data:
``` php
$data = array(
 'Post' => array(
  'group_id' => null,
  'name' => 'Tom',
  'slug' => 'tom'
 )
);
```

#### What happened
Empty values disappeared:
``` php
$body => 'Post%5Bname%5D=Tom&Post%5Bslug%5D=tom'
```

#### What I expected to happen
If I have done this with pure HTML, I would have been able to get something like this, from "w3.org":http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
``` php
$body => 'Post%5Bgroup_id%5D=&Post%5Bname%5D=Tom&Post%5Bslug%5D=tom'
```

#### Rationale
Lately, I have been building HTTP requests using HttpSocket. One thing I noticed when receiving a POST built this way, was the lack of some variables in the request body (they have disappeared). Once I started digging I ended up with the use of "http_build_query()":https://github.com/cakephp/cakephp/blob/master/lib/Cake/Network/Http/HttpSocket.php#L326 inside HttpSocket::request()

I saw it was ancient news, in fact this function does not take care of "empty arrays":http://www.php.net/manual/en/function.http-build-query.php#109466 or "null values":http://www.php.net/manual/en/function.http-build-query.php#60523 for example. Bug or not, I kept looking for an alternative and found "http_build_str()":http://php.net/manual/en/function.http-build-str.php from pecl_http which does a better job (at least with null values), but it was of no use inside Cake.

#### What I did afterwards
There is nothing out there, and I knew I could build this with curl directly, but I wanted to build it with Cake. It was also a bad suggestion to iterate the array converting those values to '' (empty string) before passing it to HttpSocket::request() because of deeper nesting.

So I ended up creating a function to accomplish this task. Quite easy, stealing most of "Hash::flatten()":https://github.com/cakephp/cakephp/blob/master/lib/Cake/Utility/Hash.php#L519 magic :P

I also saw there were 4 calls to http_build_query() which basically had the same issue, but particularly with GET requests.
lib/Cake/Routing/Router.php
lib/Cake/Network/CakeRequest.php
lib/Cake/Network/Http/HttpSocket.php

ADmad suggested placing this kind of functions, buildQuery() for the sake, in a global scope (aka basic.php), so I did that, just to realize HttpSocket::_parseQuery() could me moved there too and benefit from the code, so I renamed it to buildQuery(), and later documented/tested everything.

#### Sketch patch
https://github.com/bar/cakephp/commit/fd7c31a72f2586a4c08d845f3e1713f910461858

#### multipart/form-data
The next step could be implementing support for "'multipart/form-data' HTTP POST requests":http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 in HttpSocket, but I want to know if someone was actually into this. I believe there is some logic floating in Network/Email/CakeEmail.php

**Comment by lorenzo** [comment]
this works correctly in 3.x
