### ISSUE TITLE
"dependent" for model relations should support "empty"

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2027]
Created by **[euromark](https://github.com/dereuromark)**, 4th Dec 2012. *(originally [Lighthouse ticket #3430](http://cakephp.lighthouseapp.com/projects/42648/tickets/3430))*:
- - - -

currently, we can set "dependent" only to true or false.

when you delete a record and there are "hasMany" relations - and you want to remove it without removing the childs (dependend => false) - there is currently no option to just remove the IDs of the relation in the related records (set them to NULL).
the records itself should be kept.

allowing a third option "empty" would fix this issue. it would then set the foreign keys to NULL in those dependent records without removing them.

    public $hasMany = array(
        'Post' => array(
            'className' => 'Post',
            'dependent' => 'empty'
        )
    );

A simple updateAll() should do the trick.

IMO it should be the default as well.
but for BC we cannot really do that (and maybe for performance). but "empty" should at least be possible instead of just the two options true (complete delete) or false (keeping invalid rows).
we could also make NULL this empty behavior and use false to disable and true to remove the records. just a thought.

    public $hasMany = array(
        'Post' => array(
            'className' => 'Post',
            'dependent' => null, // maybe default in 3.x? false => same behavior as before, true => same behavior as before
        )
    );

**Comment by lorenzo** [comment]
Seems like no-one cared enough about this, so it might not be that important :)

**Comment by ravage84** [comment]
I'd love to see this, but it's not hard to implement anyway.

I had a requriement where you could "reserve" records from three different tables.
While the reservation data (person, text and date) is saved in the reservations table, I added a ``reservation_id`` to all three "reservable" tables.

Then I created a Reservable behavior which provides an ``unsetReservation()`` method, which gets called in ``afterDelete()`` of the three models and does nothing else but resets the ``reservation_id`` that match the deleted reservation ID.

I am fully aware that this could have been solved differently, like storing the model name in the reservations table, just like the CakeDC/Comments  plugin does it:

https://github.com/CakeDC/comments/blob/1.3.0/Config/Schema/schema.php#L66
