### ISSUE TITLE
Issues MySQL bit data type

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2028]
Created by **phpconnect**, 14th Dec 2012. *(originally [Lighthouse ticket #3464](http://cakephp.lighthouseapp.com/projects/42648/tickets/3464))*:
- - - -

#### What I did

In MySQL table i have created field bit data type with size on 1 like this "permission bit(1)".

#### What happened

When i execute query from cakePHP version 2 it will generate the sql query set clause like this 

"SET `permission` = '0' " which is not saving 0 in database.

#### What I expected to happen

Query clause should be like this "SET `permission` = 0 " then it'll execute properly.

**Comment by markstory** [comment]
Closing as the type system in 3.0 allows those who need bit fields to have access to them.

**Comment by dereuromark** [comment]
I still think we should at least support basic (non error) support for it to allow working with legacy DBs when migrating them to CakePHP. It doesn't have to be a complete support, just so it works somehow.
Same for the referenced issue above (enums).

**Comment by markstory** [comment]
Ok, interested parties are welcome to make pull requests. I have little interest in half supporting things. With ENUM and SET we have had issues in the past, and the past hasn't been that long.
