### ISSUE TITLE
Missing option to bake all prefixes in controller bake

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2038]
Created by **Asgraf**, 28th Jan 2013. *(originally [Lighthouse ticket #3572](http://cakephp.lighthouseapp.com/projects/42648/tickets/3572))*:
- - - -

#### What I did
In core.php:
```
Configure::write('Routing.prefixes', array('superadmin','admin','moderator'));
```
When trying to bake with:
```
app/Console/cake bake controller all --admin
```

#### What happened
There is no option to bake actions for all prefixes.
Currently all avaible options is to bake actions for only one selected prefix.

#### What I expected to happen
There should be extra option to bake actions for all prefixes defined in core.php

**Comment by markstory** [comment]
This has been implemented in 3.x bake.
