### ISSUE TITLE
Feature: Find by translated field

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2053]
Created by **func0der**, 14th Mar 2013. _(originally [Lighthouse ticket #3703](http://cakephp.lighthouseapp.com/projects/42648/tickets/3703))_:

---

Hey, I was searching for a way to filter by translated fields and found this ticket: https://cakephp.lighthouseapp.com/projects/42648/tickets/1199-find-by-translate-field

Since it is very old and Mark is right about his concern that too many conditions in existing applications needed to be changed it made sense you did not include a solution for this in cakephp by now. 

Like announced with version 3.0 cakephp is going through a loooot of changes. I would love to see that feature included in this version.
There will be an migration guide anyway and this changed can be included there. Everyone would know about it.

What do you think about it?

Greetings
func0der

**Comment by saeideng** [comment]
I think this can be done by `translationField()` , implemented in https://github.com/cakephp/cakephp/pull/9999

example 
```php
    $this->Articles->locale('es');
    $data = $this->Articles->find()->where([
        $this->Articles->translationField('title') => 'Otro Título'
    ]);
```

this issue can be close after 6 year :)
