### ISSUE TITLE
Undesirable results from breadcrumbs

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2058]
Created by **Dustin**, 5th Apr 2013. *(originally [Lighthouse ticket #3741](http://cakephp.lighthouseapp.com/projects/42648/tickets/3741))*:
- - - -

#### What I did

Using the HTML helper to generate a breadcrumb trail as prescribed with view blocks and routing prefixes.

/View/Orders/order_manager_view.ctp
```
    $this->Html->extend('Common/order_manager/two_column.ctp');
    $this->Html->addCrumb('Order #1234', '/order_manager/orders/view/1234');
```

/View/Common/order_manager/two_column.ctp
```
    $this->Html->extend('Common/order_manager/layout.ctp');
```

/View/Common/order_manager/layout.ctp
```
    $this->Html->addCrumb('Order Manager', '/order_manager');
```

/View/Layouts/default.ctp
```
    $this->Html->getCrumbList();
```

#### What happened

Breadcrumb trail was created correctly.

#### What I expected to happen

The breadcrumb methods of the HtmlHelper don't offer the ability to reverse the order or manipulate the HtmlHelper::$_crumbs array before the $startText is prepended and rendered. Using view blocks and routing prefixes I have created given prefix views their own mini-layouts. This means that any view which extends /View/Common/order_manager/layout.ctp would be expected to have a breadcrumb trail similar to: Home > Order Manager > Order #1234

I understand there are workarounds (e.g. creating a helper that extends HtmlHelper and aliasing it as Html, etc.) but this felt like a feature that should be added to the stock methods. Sorry if this has been suggested before; I searched here and the source code and was not able to find anything.

Thanks for your hard work!

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
