### ISSUE TITLE
Feature Request - Setting Bake/Schema Rules Through MySQL Comments

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2102]
Created by **ChaChaMan**, 4th Sep 2013. *(originally [Lighthouse ticket #4046](http://cakephp.lighthouseapp.com/projects/42648/tickets/4046))*:
- - - -

No idea if anybody else thinks this would be useful, but here we go:

Some form of "markup-language" to tell bake what to do to models.

For example, this is the comment of table "pre_users":
Blah blah...
---CAKE---
[username] = [displayField]
[HABTM] = [model:student,joinTable:teaches,className:Teaches, etc.] 
[HABTM] = [another relationship here]

Or here, a "pre_topics" in a forum:
Blah blah, blaaahhhh...
---CAKE---
[hasOne] = [model:Post,alias:FirstPost,foreignKey:first_post_id]
[hasOne] = [model:Post,alias:LastPost,foreignKey:last_post_id]

Now, the syntax is shit. But this could help during initial development. So you could change the schema and re-bake *everything* at high frequency without having to always manually edit a shed-load of models.

**Comment by lorenzo** [comment]
I would personally hate if we go this way and given the lack of interest in other for implementing it, I'll close.
