### ISSUE TITLE
Covers annotations for tests

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2109]
Created by **[euromark](https://github.com/dereuromark)**, 17th Sep 2013. *(originally [Lighthouse ticket #4074](http://cakephp.lighthouseapp.com/projects/42648/tickets/4074))*:
- - - -

We don't have ``@covers`` tags in core tests, which lead to incorrect coverage results. 

See
http://phpunit.de/manual/3.2/en/code-coverage-analysis.html and http://phpunit.de/manual/3.7/en/appendixes.annotations.html#appendixes.annotations.covers

This ticket can be grounds for discussion before getting into it for the alpha or beta release of 3.0.

**Comment by lorenzo** [comment]
Too difficult :dancer: 

If anyone with the motivation and time can do it, I'd be happy

**Comment by ravage84** [comment]
I will do it for 2.x... some day :laughing:
