### ISSUE TITLE
CakeRoute should be able to work with query strings

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#2120]
Created by **[euromark](https://github.com/dereuromark)**, 1st Oct 2013. _(originally [Lighthouse ticket #4117](http://cakephp.lighthouseapp.com/projects/42648/tickets/4117))_:

---
#### What I did

Custom Route class SlugRoute and URLs (coming from a CakeDC search filter plugin POST):

```
/category/?category=5123a6bf-d634-4d04-a5c6-2976566e4bcb
```

As Route connect call I tried

```
Router::connect('/kategorie', array('controller' => 'shop', 'action' => 'category'), 
    array('model' => 'Category', 'routeClass' => 'SlugRoute'));
```

and

```
Router::connect('/kategorie/:category', array('controller' => 'shop', 'action' => 'category'), 
    array('model' => 'Category', 'routeClass' => 'SlugRoute', 'pass' => array('category')));
```
#### What happened

The SlugRoute has no awareness of the query strings. But named params (deprecated) are supported, though.
#### What I expected to happen

It should also parse and provide the query strings on parse().

**Comment by markstory** [comment]
Closing as this will not likely be implemented in 2.x
