### ISSUE TITLE
Improve STEP attribute for NUMBER input type, for FLOAT & DOUBLE datatypes

### ISSUE THREAD

**Issue by kp2356** [cakephp/cakephp#2164]
This is just a usability wise feedback / suggestion :smile: 

For `FLOAT` & `DOUBLE` datatypes a `NUMBER` input type comes, that's perfect.
But setting the attribute `STEP` as `ANY` doesn't make any sense.

![image](https://f.cloud.github.com/assets/1989395/1366080/2c9c9288-38ae-11e3-8a53-a368180a6e93.png)

So changing the `STEP` value from `ANY` to `0.1` would help users to get a basic floating point step.

Solution : `FormHelper.php Line 1166` change `ANY` to `0.1`

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
