### ISSUE TITLE
CakeRequest should be able to lock query strings as scalar/array

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#2223]
Currently, the new 2.x query strings can actually be both array and string. 
For pagination for example, they are usually string (direction, sort, page, limit, ...).
But, if someone knows the Cake-way of forming query strings as array, he can easily make the application behave strangely, as most developers are not aware that the expected strings they are working with internally, can all of the sudden also be arrays.
Best case: Lots of warnings and notices thrown.
Worst case: Totally different and unexpected results.

In my case, though, there was a faulty external JS that just appended "page:2" (named param) etc all the time, thus creating thousands of lines in the error log this way:
E.g.

```
/some/controller/action/page:2/page:.../...
```

Same is possible using an array directly (usually not possible without some malicious intend):

```
/some/controller/action/page%5B0%5D:1/key%5B1%5D:2
```

But - seeing passed params as a thing that will soon be gone anyway - my main concern is regarding the "new " query strings:

```
/some/controller/action?page%5B0%5D=1&key%5B1%5D=2
```

Most either don't know about query strings and the possibility to be both array and scalar or don't want the additional overhead to assert the correct type.

It is already bad enough that PHP internally is not very type safe and we need to be careful how to treat variables. That we can manage, though.
But when data is coming from outside - and from untrusty sources (in this case a faulty JS script, a bot/search engine or even a user with malicious intend) - we should be better safe than sorry.

Example of an implementation that is sure widely used:

``` php
$result = 'string' . $this->request->query('key'); // Dangerous without checking if a stringish (=scalar) value
```

Ok, the example is not dangerous, but I bet there are other uses cases where that adjective would be suitable.

And here what it would currently need - quite the overhead:

``` php
$key = $this->request->query('key');
if (is_array($key)) { // Or: if (!is_scalar($key))
    throw new NotFoundException('Invalid query string'); // Simple 404
}
$result = 'string' . $this->request->query('key');
```

In this case restricting all query strings to scalar values would be the way to go.
Specific query strings can be whitelisted to be allowed either array only or even both.
If a querystring behaves incorrect, it should throw an Exception and end up as 404.

It would need to be part of the request object as this is mainly responsible for handling the data input.
We could use a similar syntax as Auth and ALL key to set default values controller-wide and then can allow/deny specific query string types (whitelisting).

For easy transition and BC I recommend to set the default to "both" right now in 2.5.
It is fairly easy to overwrite the default then via AppController if desired (e.g. if some app exclusively uses strings here that would be a quick fix).

And ideas on a more concrete implementation so far? I would love to see that going into the next minor release as part of an important step to restrict manipulation or triggering of wild behavior in Cake apps via query strings.

**Comment by dereuromark** [comment]
Symfony does something similar here with getInt() and other methods to enforce or assert the type here.

**Comment by markstory** [comment]
The consenus in #9670 was to not implement casting as casting to scalar values can be done in app code with existing PHP casts.

**Comment by inoas** [comment]
I do agree that for single values there is no point. However what about bulks of values coming in.

Could something like this also work well with the new PSR7ish interface?
```php
<?php
public function edit($id = null) {
    // $this->Caster = new Caster; // Could be loaded via a proxy CasterComponent, then this line isn't required
    $this->request->data = $this->Caster($this->request->data, [
        'users.profile_id' => $this->Caster::integer, // What about nested data?
        // 'comments.{n}.body' => $this->Caster::string // (default of course)
        'is_active' => $this->Caster::bool
    ])->cast(); // or use __invoke()?
```

**Comment by markstory** [comment]
If your request data is that complex is there a reason you wouldn't use `Cake\Form\Form` to do more thorough validation/sanitization?

**Comment by inoas** [comment]
So maybe we could put basic support for bulk type casts and maybe even bulk defaults (using this new api) in Cake\Form\Form?
