### ISSUE TITLE
Use fullTableName in Model->setSource()

### ISSUE THREAD

**Issue by andruhapx** [cakephp/cakephp#2242]
CakePHP v2
Please change Model->setSource() method to use
$db->fullTableName($this) instead copy/paste of $this->tablePrefix . $tableName

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.

**Comment by andruhapx** [comment]
This replacement is needed to allow customize table access by adding some unusual rules for some tables
$db->fullTableName($this) is the same as $this->tablePrefix . $tableName so it will be good to use this method instead copypasting $table = $model->tablePrefix . $model->table

**Comment by markstory** [comment]
Any chance you could send a pull request @andruhapx ?
