### ISSUE TITLE
Endles Request with Digest Authentication in SSL Context

### ISSUE THREAD

**Issue by jbaeckmann** [cakephp/cakephp#2331]
I use the current stable Release of CakePhp (2.4.2-0-g75624c0).

If I want to connect a digest secured side with Cake\Network\Http\HttpSocket I get an endles request which ends after 100 times.

I searched and found a solution for this problem. If you swap lines 332 and 333, the problem don't occur. This is because the realm and nonce are the before the next request begins:

This is the right order:

$this->request['auth'] = $this->_auth;
$this->_setAuth();

**Comment by markstory** [comment]
I tried again using request() and still wasn't able to reproduce the issue. I also don't understand how changing those two lines could remedy the issue. The request data needs the complete auth data which is generated when `_setAuth` is called.
