### ISSUE TITLE
cake schema update does not update lengths of existing mysql indexes

### ISSUE THREAD

**Issue by stefan-hausmann** [cakephp/cakephp#2420]
what I did in cakephp 2.4.1:

changed my schema.php from
```
'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
			'slug' => array('column' => 'slug', 'unique' => 1)
)
```

to
```
'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
			'slug' => array('column' => 'slug', 'unique' => 1, 'length' => array('slug' => '255'))
)
```

but no index length was added to the 'slug' index in the corresponding mysql table after running ```cake schema update```

However, manually removing the field's index in mysql and then running ```cake schema update``` again correctly added the index as well as setting its length.

**Comment by markstory** [comment]
Closing as I'm pretty sure that the migrations tool (phinx) will handle this for 3.0.
