### ISSUE TITLE
NULLS LAST when sort descending

### ISSUE THREAD

**Issue by baberuth22** [cakephp/cakephp#2625]
Either in the paginator component or in the core, I would love to see NULLS last appended to ORDER BY DESC.   

A majority of the time this would be the desired functionality.   

http://stackoverflow.com/questions/20956870/cakephp-pagination-helper-sort-nulls-last

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
