### ISSUE TITLE
3.0 cake bake working controller tests

### ISSUE THREAD

**Issue by josephzidell** [cakephp/cakephp#2674]
Testing is a good thing, and while CakePHP chose to make it optional, there's one thing we can do to help people who want to test, get started sooner. `cake bake` can generate passing tests instead of 

```php
$this->markTestIncomplete('testIndex not implemented.');
```

Testing controller actions is significantly more involved than testing models, and could some encouragement.

**Comment by dereuromark** [comment]
The fully working integration test can only work if we also include the required fixtures (including relations) etc in the test case.
Not sure how complicated it will be, but maybe someone can draft a PR for bake and we can see.
This should probably be moved to cakephp/bake then.

**Comment by markstory** [comment]
I'm still not sure this is a good idea. The passing tests we generate could easily be failing tests. Take an application that has access control, or authentication restrictions in place. Bake could never account for that custom application logic. Under these conditions any tests we generate would fail and become an annoyance for all 3 of the groups.

Closing as I'm not sure this is an idea that will play out well in practice.
