### ISSUE TITLE
hasMany throug and HABTM limitations in the view layer 

### ISSUE THREAD

**Issue by saidbakr** [cakephp/cakephp#3086]
CakePHP is limited in dealing with the following scenario:

1- Recipe model that has many Ingredient model and The Ingredient model has many Recipe. HABTM is not sufficient in the case of need adding amount attribute for the Ingredient for each Recipe, so documentation suggest use hasMany through but It also limited because it does not offer a view for Recipes add to select multiple Ingredients and set the amount for each selected Ingredient.

2- Cake bake does not able to offer automated solution for such scenario. I hope that is going to be fixed in CakePHP 3.0

**Comment by ADmad** [comment]
Seems you have have achieved what you needed.

Closing the issue as javascript based widget for handling hasmany through is likely to be included in core.
