### ISSUE TITLE
2.5 - jsonView should throw exception if json_encode fails.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#3141]
JsonView will produce an empty HTTP response if json_encode fails. This can create a lot of confusion for a developer trying to understand why the controller's action is executing correctly, but the response from the server is empty.

When json_encode fails the return value is just false.

The `_serialize` method could be changed to something like this.

```
		$json = version_compare(PHP_VERSION, '5.4.0', '>=') && Configure::read('debug')
			? json_encode($data, JSON_PRETTY_PRINT)
			: json_encode($data);
		if(json_last_error() !== JSON_ERROR_NONE)
		{
			throw new CakeException(json_last_error_msg());
		}
		return $json;
```

json_encode will fail if `$data` contains any non-UTF-8 character encoded strings.

**Comment by dereuromark** [comment]
Closing as a PR is now open for it.
