### ISSUE TITLE
Pagination for non-sql stores in 3.0

### ISSUE THREAD

**Issue by kminek** [cakephp/cakephp#3660]
Hi there,

i am playing with 3.0 and stuck when trying to paginate different datasources (array, csv, xml, remote webservice, you name it) using PaginatorComponent. This is currently possible in 2 by providing a class extending `DataSource`. 

My initial thought was to create custom class implementing `RepositoryInterface` and pass instance of that class as first param to `PaginatorComponent:paginate()` as per documentation but it complaints about missing `alias()` method.  It would be great if pagination was abstracted and not tied to SQL stores only. Pagination should consume some kind of adapters (new ORM layer should provide this kind of adapter and as a developer I could provide my own adapter for my custom datasource). Maybe Cake should use external general-purpose pagination library and wrap PaginatorComponent around it.

**Comment by lorenzo** [comment]
This is possible now, by using available plugis
