### ISSUE TITLE
3.0 RFC: Add better plugin and app readme to bake

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#3816]
Adding a dummy readme with some structure about how an app/plugin is to work would help increase documentation in the community, as well as potentially push people towards using stuff like composer/testing if we setup a proper initial version.

Here is the sample plugin one from [friendsofcake/travis](https://github.com/FriendsOfCake/travis/blob/master/templates/README.markdown) and here is one I use as a template for [personal plugins](https://gist.github.com/josegonzalez/903066).

Thoughts?

**Comment by dereuromark** [comment]
poke @josegonzalez

**Comment by dereuromark** [comment]
Closing due to lack of interest and due to wrong repo now, can be reopened or PRed at cakephp/bake if desired.
