### ISSUE TITLE
2.5 onError callback not called in behaviors

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#3856]
The onError callback isn't called on behaviors.  In the base datasource, the code appears to only call the onError method on the model, it doesn't trigger the event for the behaviors.

There is a test called "testBehaviorOnErrorCallback" in BehaviorCollectionTest, but it's directly calling the method on the behavior, it's not actually testing the circumstances that would trigger the callback.  So it looks like that test isn't really testing anything useful related to the "onError" callback.

I'd imagine changing/fixing this functionality could be breaking, so it should be considered for 2.6+.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
