### ISSUE TITLE
3.0 - Fixture insertion error on unique fields

### ISSUE THREAD

**Issue by luke83** [cakephp/cakephp#3869]
Running tests under phpunit, after fixture and test case generation using the console:

```
Unable to insert fixtures for "App\Test\TestCase\Model\Table\ArticlesTableTest" test case. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Lorem ip' for key 'code' in [vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 259]
```

where `code` is a field with unique constraint. Fixture generation tool generates same field content for all records' fields `code` even if it knows that filed must be unique:

```
// Test/Fixture/ArticleFixture.php
[..]
'_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
            'code' => ['type' => 'unique', 'columns' => ['code'], 'length' => []],
[..]
```

Appending `id` value (unique by design) to unique fields could be a quick fix for fixture generation tool.

**Comment by ADmad** [comment]
Closing as the issue has gone stale. If there is still interest a PR is welcome.
