### ISSUE TITLE
Datetime field with CURRENT_TIMESTAMP in fixture

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#4037]
In CakePHP 2.5, a default value of `CURRENT_TIMESTAMP` is not recognized as a valid value for field `DATETIME`.

```
'last_activity' => array('type' => 'datetime', 'null' => false, 'default' => 'CURRENT_TIMESTAMP'),
```

This is valid as of MySQL 5.6.

**Comment by dereuromark** [comment]
This seems to be related to https://github.com/cakephp/cakephp/issues/7393

**Comment by markstory** [comment]
Looks very related.
