### ISSUE TITLE
2.5: After calling ./cake schema update, cache files should be deleted

### ISSUE THREAD

**Issue by johannesnagl** [cakephp/cakephp#4067]
After deploying changes and calling ./cake schema update, we're often encountering problems with the then outdated cache files in tmp/cache/models (in debug 0).

we therefore have a custom script that we call afterwards:

rm ../app/tmp/cache/models/APPNAME_cake_*
rm ../app/tmp/cache/persistent/APPNAME_cake_*

unfortunately, if you forget to call this script, your app can (silently) break. so, wouldn't it be most reasonable to reset the cache directly within the schema update command?

what's your opionion on this one?

(ps: just stumbled upon this problem within a big migration, which we only tested on dev, where debug level = 2 and everything worked as expected. now on production, half of the custom sql-update-queries silently refused the updates because of the outdated schema-definitions).

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
