### ISSUE TITLE
PaginatorHelper::options() array_replace_recursive instead of array_merge?

### ISSUE THREAD

**Issue by schrolli** [cakephp/cakephp#4093]
hi,

i had issues due to setting the default page for sorting-links to page 1 by using

$this->Paginator->options(array('url'=>array('page'=>1)));

i encountered problems with the "other pages" links. they didn't had the sort-options set.

i teared the problem down: the array_merge in the options function overwrites the other options set in beforeHandler.

I would suggest to use array_replace_recursive() to do the job. But this isn't non-associative safe.

so my question is: are anywhere (htmlhelper::link and all other functions, that are used by paginatorhelper) non-associative array-items as option-array in use?

**Comment by lorenzo** [comment]
I think this can be closed already
