### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by php-engineer** [cakephp/cakephp#4112]
I run into problems when I use `DECIMAL(15,7) UNSIGNED NOT NULL DEFAULT '0.0000000'` for a MySQL column. I would expect that CakePHP set `0.0000000` as default value, if the given input field is empty but I get the following error message instead:

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'partner_commission_rate' cannot be null
```

Extract from my view file:
```
echo $this->Form->create('Partner');
echo $this->Form->input('partner_commission_rate');
echo $this->Form->end();
```

The view generates the following output:
```
<input name="data[Partner][partner_commission_rate]" type="text" id="PartnerPartnerCommissionRate">
```

Extract from my controller:
```
$this->Partner->create();
if ($this->Partner->save($this->request->data)) {
}
```

The query itself:
```
INSERT INTO `cake`.`app_partners` (`partner_commission_rate`) VALUES (NULL)
```

**Comment by lorenzo** [comment]
This is part of data validation/sanitization, empty values should be removed if that is not the intention. defaults are used when no value is provided, which is different that an empty value.
