### ISSUE TITLE
3.0 Enhancement - Expand PaginatorHelper::params() data

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#4172]
Consider the following table...

```
<table>
    <thead>
        <tr>
            <th class="text-center">#</th>

            <th>First Name</th>

            <th>Last Name</th>
        </tr>
    </thead>

    <tbody>
        <?php
            $i = 1;
            foreach ($users as $user):
        ?>
        <tr>
            <th class="text-center"><?php echo $i; ++$i; ?>.</th>

            <td><?= $user->first_name; ?></td>

            <td><?= $user->last_name; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
```

When I go to page 2, the row counter will start at 1 again. The information found in [PaginatorHelper::counter()](https://github.com/cakephp/cakephp/blob/3.0/src/View/Helper/PaginatorHelper.php#L534-L541) would be helpful to have in a `PaginatorHelper::params()` call so that I could offset the row counter to accurrately display the records they are viewing.

**Comment by dereuromark** [comment]
I like the idea of moving that logic up. I had to hack something similar in the view in order to get the desired results once.

**Comment by sdustinh** [comment]
Forgot about this issue. Sure, I'll take a stab at a PR.

**Comment by andraskende** [comment]
That counter can be used from: 

    <?php $i = $this->Paginator->counter('{{start}}') ; ?>
    <?php foreach ($users as $user): ?>
    <tr>
    <td><?php echo $i++; ?></td>

**Comment by markstory** [comment]
Closing as there is a reasonable solution to the problem using existing methods.
