### ISSUE TITLE
3.0 Enhancement - EventManager::$_listeners

### ISSUE THREAD

**Issue by quickapps** [cakephp/cakephp#4192]
I was working with cake's event system for creating plugin communication.
I usually organize my event keys using dot-syntax as follow `Cart.A.event1`, `Cart.A.event2`, `Cart.B.A.event1`, etc.

In certain cases a plugin may need to know if there is any listeners in a sub-group, for example check if there is any listeners registered under `Cart.A.*` or `Cart.B.A.*`... 

EventManager::listeners() returns all listeners for a specifyc eventKey, also EventManager::$_listeners is marked as protected... so there is not way to get a list of all registered eventKeys and look for a matching pattern.

What I propose is to create a new method, for example: `EventManager::eventKeys()` which sould return:

    array_keys($this->_listeners);

Or change `EventManager::listeners($eventKey)` definition to return the whole list if `$eventKey` argument is null.

PS: I managed to this by using Reflection API and changing `EventManager::$_listeners` visiblity to plublic... yea, a bit ugly...

**Comment by jeffblack360** [comment]
I started hacking on this. The function name I'm using is ```EventManager::matchingListeners(...)``` and wanted to get feedback for suggestions. I modeled the name after ```EventManager::prioritisedListeners```.

```php
    /**
     * Returns the listeners matching a specified pattern
     *
     * @param string $eventKeyPattern Pattern to match.
     * @return array
     */
    public function matchingListeners($eventKeyPattern)
```

**Comment by markstory** [comment]
@jeffblack360 I like the method name :+1:

**Comment by jeffblack360** [comment]
@markstory Thank you for the response. I'll wait a few days for some more for input.

**Comment by lorenzo** [comment]
@jeffblack360 that looks good to me

**Comment by jeffblack360** [comment]
I've been working on the implementation and associated unit-test and had a few questions:

1. Should we allow for a regex to be passed to the ```EventManager::matchingListeners(...)``` function and feed that into preq_grep? I'm using preq_grep to perform to search for matches.

2. Should we only accept a string without any regex and match only on the string by wrapping it with delimters (e.g. '/' . $eventKeyPattern . '/')?

Thanks!

**Comment by markstory** [comment]
> Should we allow for a regex to be passed to the EventManager::matchingListeners(...) function and feed that into preq_grep? I'm using preq_grep to search for matches

No. Lets keep it simple. Exact matches only.
