### ISSUE TITLE
[Postgres][UnitTest] Define custom sequence name in TestFixture

### ISSUE THREAD

**Issue by vietvq** [cakephp/cakephp#4226]
[Postgres]

I have table named `Entries` and model `Entry` related. And I want `entry_id_seq` instead of default `"{$table_name}_{$id}_seq"` (`entries_id_seq`) as sequence name.

In Model, I can define:
```php
class Entry extends AppModel {
    public $sequence = 'entry_id_seq'; // or 'public.entry_id_seq'.
    ...
}
```
And can't in:
```php
class EntryFixture extends CakeTestFixture {
    // public $sequence = 'entry_id_seq';
}
```

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
