### ISSUE TITLE
3.0 - FlashComponent Configuration

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#4296]
There are different ways to configure the FlashComponent but maybe it would be a nice improvement to be able to drag the configuration out of the AppController into the app configuration. Let me explain why, because there is maybe another way to do this:

I want to move my FlashComponent elements into a plugin to get the reusability for other projects later. Therefore I create the `Template/Element/Flash` directory in my plugin with 4 different template files. Now I want to use one of these templates as default template. Sure, I'm able to configure the default template in my AppController but when I use the AuthComponent, the configuration will be neglected and the FlashComponent search for the default template in my app directory.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
