### ISSUE TITLE
3.x - translate and map/reduce

### ISSUE THREAD

**Issue by darxmac** [cakephp/cakephp#4303]
When doing map/reduce on result set from a model with translated fields, the entity that gets passed to map/reduce does not have it's translations set to it `_translations` property

See this thread for more info: https://groups.google.com/forum/#!topic/cake-php/AvZQQ4uHplY

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
