### ISSUE TITLE
3.0 Adding assertResultArrayEquals to TestCase

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#4344]
While the second day of the CakeFest 2014 Workshop with @steinkel, the unit testing of find methods was covered, as documented here:
http://book.cakephp.org/3.0/en/development/testing.html#creating-a-test-method

Doing so, I felt the following two lines violate the DRY idea because you have to repeat them in each of your table tests.
````
$this->assertInstanceOf('Cake\ORM\Query', $query);
$result = $query->hydrate(false)->toArray();
````

So I was wondering if we could add a function like the following to ``TestCase``:
````
/**
 * Convenience function to test query results
 *
 * @param $expected
 * @param Object $result Should be an instance of Cake\ORM\Query
 * @param string $message
 */
	protected static function assertResultArrayEquals($expected, $result, $message = '') {
		self::assertInstanceOf('Cake\ORM\Query', $result);
		$result = $result->hydrate(false)->toArray();
		static::assertEquals($expected, $result, $message);
	}
````

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
