### ISSUE TITLE
Documentation: Add section on annotation order

### ISSUE THREAD

**Issue by thaJeztah** [cakephp/cakephp#4559]
Following a short discussion here https://github.com/cakephp/cakephp/pull/4505#discussion_r17324720

The [current section on coding standards](http://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#commenting-code) does not describe the order in which annotations, such as `@param`, `@throws` should appear.

Thinks to add/describe;

- in what order should annotations be included
- spacing / white-lines before/after `@param`, `@return` and `@throws`
- alignment; i.e. Should descriptions and/or parameter names be aligned or not?

**Comment by dereuromark** [comment]
Closing for now. We can soon have a draft for the cakephp codesniffer repo.
I actually already have existing sniffs incl. autofixer for [grouping](https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Commenting/DocBlockTagGroupingSniff.php) and [ordering](https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Commenting/DocBlockTagOrderSniff.php)

Without a sniffer to assert it it is pointless to propose sth here now.
So someone just has to port them and open a PR at our Cake sniffer repo.
