### ISSUE TITLE
Containing a virtualField

### ISSUE THREAD

**Issue by oldskool** [cakephp/cakephp#4589]
I tried do a find with Containable as follows:

``` php
$this->find('all', array(
    'fields' => array(
        'ContactLog.count',
        'ContactLog.date',
        'ContactLog.contact_id',
        'ContactLog.contact_alt',
        'ContactLog.contact_log_type_id'
    ),
    'contain' => array(
        'Contact.name',
        'ContactLogType.name',
    )
));
```

Note that the `name` field of the Contact model is a virtualField.
However, this gives me an SQL error:

> Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Contact.name' in 'field list'

However, if I drop the root `fields` key entirely (thus fetching all fields from the main ContactLog model), it suddenly starts working! Also, this workaround works (but is obviously a bit nasty and brings along the "0-prefixed field name problem"):

``` php
'contain' => array(
    'Contact' => array('fields' => $this->Contact->virtualFields['name'] . ' AS name'),
    'ContactLogType.name',
)
```

I'm confused as of why the query works when I don't define any root fields, but not when I do. I would expect the `autoFields` option of the Containable behavior to fetch anything it needs to successfully build the query?

Issue occurred in CakePHP 2.5.2.

**Comment by jeffblack360** [comment]
@markstory Just curious: Why do you change the milestone when a patch has been supplied?

**Comment by markstory** [comment]
@jeffblack360 That referenced commit never found its way into our repo. It only exists in @chinpei215's fork.

**Comment by chinpei215** [comment]
@jeffblack360 Sorry to confuse you. The patch can solve this issue, but I notice that it changes the `fields` option. That would break some applications that handle the beforeFind event and check the `fields` option. So I didn't make PR.

I came up with another fix at that time, but it is more complex. So I didn't make PR after all.
Now I have only the code snipet. I forgot where I used it though.

```php
if (empty($queryData['joins'])) {
	$associated = array_flip(array_merge($Model->getAssociated('hasOne'), $Model->getAssociated('belongsTo')));
	if ($associated) {
		$prefix = $this->startQuote . $Model->alias . $this->endQuote . '.';
		foreach ($queryData['fields'] as $i => $field) {
			if (strpos($field, $prefix) !== 0 && substr_count($field, '.') === 1) {
				list($alias, $field) = explode('.', $field);
				$alias = ltrim($alias, $this->startQuote);
				$alias = rtrim($alias, $this->endQuote);
				if (isset($associated[$alias]) && $Model->useDbConfig === $Model->{$alias}->useDbConfig) {
					$field = ltrim($field, $this->startQuote);
					$field = rtrim($field, $this->endQuote);
					if ($Model->{$alias}->isVirtualField($field)) {
						$field = $this->_constructVirtualField($Model->{$alias}, $alias, (array)$field);
						$query['fields'][] = $field[0];
					}
				}
			}
		}
	}
}
```

**Comment by jeffblack360** [comment]
@chinpei215 Thanks for educating me! :+1:

**Comment by chinpei215** [comment]
@jeffblack360 You are welcome.

**Comment by dereuromark** [comment]
@chinpei215 Does the patch have any side-effects or failing tests?
Because if not, this is a valid solution to the issue IMO, as complex as it may be, current functionality is broken without it from what I understand.

**Comment by chinpei215** [comment]
@dereuromark If I remember correctly, both patches would pass the test. But the second patch is also not good for the following reasons:

1. Not a perfect fix. If the `joins` option is specified, it is difficult to guess whether the field is virtual or not (because users can specify arbitrary aliases of the tables). Then it doesn't contain virtual fields.
2. Has a big effect because the patch is for `DboSource` instead of `ContainableBehavior`. That would slow down all `find` operations at least.

So I prefer the first patch personally. A possible solution might be adding a new option into `ContainableBehavior::$settings`, something like `containVirtualField`. If users set the option to `true`, it works. Defaults to `false`.

**Comment by markstory** [comment]
Closing as a pull request is now open that should resolve this issue.
