### ISSUE TITLE
Multiple flash messages.

### ISSUE THREAD

**Issue by moose51789** [cakephp/cakephp#4619]
I would love to see ability to set multiple flash messages with the same key of some sort.  I'm using flash message for a notification system and being limited to just one flash message makes it hard to show multiple messages.

Example: 
    $this->Flash->user_notification('New Private Message!');
    $this->Flash->user_notification('Thread Reply!');
    $this->Flash->general_notification('Message');

There are instances where a user might receive multiple notifications and when they navigate about the site i'd like for multiple of them to pop up that then fade away.  I can clarify more if need be.

**Comment by HavokInspiration** [comment]
So I can understand what you guys mean by "multiple flash messages". Do you mean this :

![screenshot from 2015-03-20 22 15 55](https://cloud.githubusercontent.com/assets/5243386/6761005/ca947478-cf4e-11e4-97c0-924e41ff0f6a.png)

If so, why not have a config option in the Component allowing to toggle the stacking of messages ?
If the stacking is enabled, messages will be stored in an array and each one will be rendered by the Helper.

Something like this :

```php
$this->Flash->enableStacking(); //we can also imagine its counter part "disableStacking()"
$this->Flash->error('This is an error message');
$this->Flash->success('This is a success message');
$this->Flash->warning('This is a warning message');
```

It just brings some changes in the way the message are stored (the session variable name needs to have an additionnal param to convert it as an array.), and the API changes would be minimal.
It should also not break compability, the default behavior being the current one (one message per key). It would also work well with a simple call to ``set()``.
One could even default the ``FlashComponent`` to stack messages if needed.

On the helper side, we could leverage the ``StringTemplate`` to provide a template to render stacked messages.

**Comment by markstory** [comment]
@HavokInspiration I understand what you described to be the same kind of thing as was previously discussed. If we have an append model for flash messages, we should also have a way to clear any set messages.

**Comment by HavokInspiration** [comment]
@markstory That makes sense. The simplier way would be to add a method ``FlashComponent::unset($index)`` that will clear message stored at $index (the implementation I have stores them in a numeric index array).
But that would mean the user have to manually track his messages index if he needs to delete them :

```php
$this->Flash->config('stacking.enabled', true);
$this->Flash->error('This is an error message');
$this->Flash->success('This is a success message');
$this->Flash->warning('This is a warning message');

//Do stuff

//That deletes the success message.
//Now we only have the error and warning messages in the Session.
$this->Flash->unset(1); 
```
The only thing I'm wondering is if, after a ``unset()`` call, the index sequence should be reset or left as is to allow the user to do a ``$this->Flash->unset(2)`` in the previous example, allowing the deletion of the warning message.

Or, we could make ``set()`` (and ``__call``) return the index in case of stacking (and ``null`` in a default setup).

```php
$this->Flash->config('stacking.enabled', true);
$errorIndex = $this->Flash->error('This is an error message');
$successIndex = $this->Flash->success('This is a success message');
$warningIndex = $this->Flash->warning('This is a warning message');

//Do stuff

//That deletes the success message.
//Now we only have the error and warning messages in the Session.
$this->Flash->unset($successIndex); 
```

This would resolve the "should we reset the index sequence" along the way.

**Comment by markstory** [comment]
I donty think you can use unset as a method name, but the general idea seems good. It might also be useful to clear a type if message for example, clearing all the success messages when an error is found. Something like `clear('success')` might work.

**Comment by mikescar** [comment]
I would be happy to work on this and submit a branch request.

I did this on my own when we needed both success and info messages for a client. Have a heard a lot of requests for this, but definitely know it could be screwy if done wrong.

**Comment by markstory** [comment]
@mikescar If you have a good idea on how it could be done well that would be a great help :smile:. Everyone has opinions, but battle tested code often has some wisdom that opinions do not.

**Comment by mikescar** [comment]
OK, not sure how it would be translated to the newest setup, but will pull newest cake and work on this weekend. It was not a very large change last time in 2.x

**Comment by zoghal** [comment]
@markstory I've implemented. If it is OK, I can add to the core.

https://github.com/RitaCo/cakephp-tools-plugin/blob/rita3/src/Controller/Component/FlashComponent.php
https://github.com/RitaCo/cakephp-tools-plugin/blob/rita3/src/View/Helper/FlashHelper.php

**Comment by dereuromark** [comment]
Looks like this was implemented. We could however think of backporting the multi flash to 2.7 and the FlashComponent there.

**Comment by ravage84** [comment]
:100: for a back port, one small thing more that will make the transition from 2.7 to 3.x easier
