### ISSUE TITLE
3.0 - RFC - Don't singularlize table name in foreignkey field names

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#4738]
Since our tables names and now even model names are plural it would be simpler if we use convention for foreignkeys where just "_id" is appended to the table name instead of singularizing it first. This would save us few extra inflections in code and make conventions easier to remember for new users.

TL;DR; Use foreignkey field names like `users_id` instead of `user_id`.

**Comment by ionas** [comment]
@thaJeztah MySQL Workbench does use SINGULAR-TABLE-NAME_id as the default for its design and its Reverse Engineering Tool (which luckily also detects foreign key constraints / association definitions in SQL if you fail to follow those conventions of SINGULAR-TABLE-NAME_id).

So I'd not be too sure about general conventions.

**Comment by thaJeztah** [comment]
> MySQL Workbench does use `SINGULAR-TABLE-NAME_id` as the default (...) So I'd not be too sure about general conventions. 

erm, but that's what I suggested, *keep* it `singular_id` (i.e. `user_id`)? Which is also the current convention?

**Comment by ionas** [comment]
I just wrote it wrongly. It is just TABLE-NAME independent of whether that (table name) is plural or singular.

**Comment by hmic** [comment]
Why not make the whole magic that happens behind the scenes in the Tables configurable?

Just have a class like the router classes InflectedRoute, DashedRoute, ...
So everybode could select their favorite naming schemes for foreign keys, table names, what ever...
This would make it very easy to adopt an app to a preexisting legacy databases too. Or database structures created by third party ERD tools, which is a (manual) pain in the a*** right know.

No BC breaks involved, as the current status could be factored out into the default class, like the InflectedRoute have been...

**Comment by jadb** [comment]
:+1: - am in favour of that. I don't think it will add much load (needs to be tested though), since there is already magic happening behind the scene using the inflector anyways.

I really like that and re-opening to give it a chance to be done in time for 3.0?

**Comment by dereuromark** [comment]
This is a huge BC break, and should not be done in any 3.x version.

**Comment by jadb** [comment]
@dereuromark - it's not, re-read @hmic's suggestion or maybe I have totally missed the point.

**Comment by hmic** [comment]
No, as I explicitely mentioned, no BC breakes involved!

**Comment by markstory** [comment]
Do most legacy databases you've worked with have conventions? The ones I've encountered have very little internal consistency, so having more flexibility around conventions wouldn't be of much use.

**Comment by hmic** [comment]
Like @ionas said, there are pleanty of ERD tools that do.
Look at mysqlworkbench e.g.
It's a pain to load a cake schema in to show or alter it, everytime you open it again. And it's a paint too, to make cake work with a generated schema from this tool too.

It could be automated both ways by allowing to overwrite the conventions used applicationwide by a TableEntityNameConventions class with the same porpose as the InflectedRoute or SlugRoute classes.

**Comment by rchavik** [comment]
:-1: even as configurable option.

**Comment by markstory** [comment]
If CakePHP had no conventions would setting up associations for schema generated by these tools be harder or simpler?

**Comment by hmic** [comment]
of course is this needed to be configurable, as i said, just like the router classes would be a good solution IMHO.

Why do you disagree? - No need is no answer!

**Comment by rchavik** [comment]
hmic,

Even as a non-native speaker, having a field named `users_id` does not feel right to me.

**Comment by hmic** [comment]
I dont want to change the *default* conventions. I am fine with those!
But think of having a db with many tables generated by one of theese tools and beeing used by some arbitrary other java app.
You would have to set the associations up in every table manually to match instead of having a class that holds the magic logic to do so in one place, once and forever...

The cake-default logic is already there, it would only have to be factored out to allow it beeing exchanged. This can only be a win!
You could even provide static, preconfigured classes with association mappings, no magic involved, and speed the whole thing up (even in the cake-default case) by doing so!

**Comment by hmic** [comment]
@rchavik its not about the actual names of fields, it refers to interoperability with other systems *only*.

Naming can be (naturally) right or wrong anyway, thats not the point of my suggestion for a solution.
Maybe I sould open another ticket to discuss it, if you fell like this is the wrong title for the discussion.

**Comment by ceeram** [comment]
Perhaps the current conventions trait could be converted into an injected
dependency. One could then configure their own conventions object, which
could perhaps also take care of prefixed tables then as a nice side effect,
which seems to be another desired possibility?
Op 7 mrt. 2015 14:40 schreef "Hans-Joachim Michl" <notifications@github.com

**Comment by hmic** [comment]
I like the direction @ceeram is taking here...

There seem to be pleanty of people interested and (possibly) willing to implement this in the described manner.
However, at least for me to get into, it needs te be decided upfront if this can be included in a coming release - the 3.1 milestone is a good one.
We have negative feedback too, so maybe someone can take a position on it.

**Comment by markstory** [comment]
A class that knows about conventions sounds interesting. How would app/plugin subclasses get injected into the associations/bake?

**Comment by ceeram** [comment]
*cough* DIC *cough* perhaps?
Op 7 mrt. 2015 16:04 schreef "Mark Story" <notifications@github.com>:

**Comment by markstory** [comment]
@ceeram Having to register every table in a generic DIC container sure sounds like a ton o fun :trollface:

**Comment by ravage84** [comment]
A foreign key references __a single record__ in a foreign table, thus singular.
So simple, so logic and that's why :-1:

**Comment by ionas** [comment]
@ravage84 totally on board, but then you have tool-sets and requirements in the real world. PSR2 IMHO sucks too, but it doesn't matter, the world is using it, and for the sake of ease of use, picking up and using this framework, having the option to use a different foreign key inflector would be awesome.

**Comment by thaJeztah** [comment]
*Ideally*, the foreign keys should be reflected from the actual foreign keys in the database (ignoring the name), but that would complicate things if multiple relations between a table exists.

**Comment by ionas** [comment]
The primary issue with real foreign keys is, as far as I understood, that not all db engines support those and that in production at least for mysql those can create lock tables issues and slower write performance.

I like the conventional approach cakephp is taking, i just think there are 2 sane conventions, and both should be supported by a switchable Inflector.

**Comment by ADmad** [comment]
My reason for posting this ticket was to totally avoid inflection and makes things simpler. Making the foreignkey convention configurable actually does the opposite and adds complexity.

**Comment by ionas** [comment]
I can see THAT reason and just for that I'd stick with TABLENAME_id in some upcoming release.
That being said, it is a strong BC break, how would you handle that?

**Comment by ceeram** [comment]
We wont need to handle BC breaks, as we are not gonna break BC. Nothing will be changed wrt to conventions of foreign keys.

**Comment by markstory** [comment]
If someone is interested/motivated they could explore how to extract the conventions the various association classes use into a single object that could be swapped out as required. I think we can theorize on how it could work but until someone takes a run at building something we won't actually know :smile:

**Comment by jhli** [comment]
Would have been great and even if its just for great back and forth between cake and mysql workbench reengeneering.
