### ISSUE TITLE
Feature: cake routes command line

### ISSUE THREAD

**Issue by TeckniX** [cakephp/cakephp#4810]
Rails has a pretty nifty command line which is `rake routes`:
_rake routes: will list all of your defined routes, which is useful for tracking down routing problems in your app, or giving you a good overview of the URLs in an app you're trying to get familiar with._

It would be neat to have a similar cake cli tool, where one would run ` ./Console/cake routes` and get a list of all possible routes created/available.

**Comment by coryjthompson** [comment]
CLImate looks pretty good to me.

**Comment by markstory** [comment]
Closing as a pull request is open now.
