### ISSUE TITLE
Wrong Autorization redirection

### ISSUE THREAD

**Issue by bouksou** [cakephp/cakephp#4812]
when i try to reach this link : "http://local.dev/cakephp/admin/tutorials" with my user account the IsAuthorized function return false which's totally right, but the redirect goes wrong because it redirect me to ""http://local.dev/cakephp/cakephp", i don't know what's wrong with this, thx !

```php  
//AppController.php
    public $components = [
        'Flash',
        'Auth' => [
            'authorize' => ['Controller'],
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email']
                ]
            ]
        ]
    ];
```

```php    
//AppController.php
public function isAuthorized($user = null) {

        if (!isset($this->request->params['prefix'])) {
            return true;
        }      

        // Admin can access every action
        if (isset($user['role']) && $user['role'] === 'admin') {
            return (bool)($user['role'] === 'admin');
        }

        // Default deny
        return false;
    }
```

**Comment by alaxos** [comment]
Hi Mark, any particular reason for not having applied the same fix in Cake 2 ? The issue seems to be still present in Cake 2.6 and your fix for Cake 3 seems to work in Cake 2 as well.

**Comment by dereuromark** [comment]
@alaxos Are you able to provide a PR pretty quick with your suggested changes for 2.x? That would be awesome.

**Comment by markstory** [comment]
I can backport. I didn't know it was a problem in 2.x as well.

**Comment by alaxos** [comment]
@markstory Great, thank you !

**Comment by DQPHP** [comment]
I have the same problem using the version 2.6.2.
@Xety Thank you, your solution is prefect!

**Comment by markstory** [comment]
@DQPHP You'll have to upgrade to a newer version of 2.6.
