### ISSUE TITLE
Subquery in virtual field query is not fully MySQL compartible

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#4818]
When I generate a virtual field by using subquery some backticks are missing.

        $options = array(
			'fields' => array(
				'COUNT(*) > 0'
			),
			'table' => 'orders',
			'alias' => 'Order',
			'conditions' => array(
				'Order.booking_id = Booking.id',
			)
		);
		$db = $this->getDataSource();
		$statement = $db->buildStatement($options, $this->Order);
		$this->virtualFields['count'] = $statement;

generates subquery

        (SELECT 
            COUNT(*) > 0
            FROM
            orders AS Order
        WHERE
            `Order`.`booking_id` = `Booking`.`id`
        ) AS `Booking__count`

Backticks around 'orders' and 'Order' are missing. In my case that results as invalid query. Of course I can use another alias, but...

CakePHP v.2.5.4

**Comment by lorenzo** [comment]
This is unfortunately a limitation that is not possible to solve in 2.x and one of the reasons identifier quoting is disabled by default in 3.0. Closing as it will not be possible to fix in the 2.x branch and is not a problem anymore for the newer versions.
