### ISSUE TITLE
3.0 RFC find('list') should use different key names for specifying option keys and values instead of idField and valueField

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#4832]
Regarding: http://book.cakephp.org/3.0/en/orm/table-objects.html#finding-key-value-pairs

```php
$query = $articles->find('list', [
    'idField' => 'slug',
    'valueField' => 'title',
    'groupField' => 'author_id'
]);
```
valueField is, without digging into the API/book, ambiguous. The regular html option's tag uses a value attribute and thus that could be meant. I know, this is no HtmlHelper or FormHelper but I think labelField or even displayField would be much better.

By default displayField is what valueField is set to if you don't specify anything.

So my suggestion would be:

```php
$query = $articles->find('list', [
    'idField' => 'slug',
    'displayField' => 'title',
    'groupField' => 'author_id'
]);
```

**Comment by ionas** [comment]
This is indeed low prio but it does not make much sense adding in 3.1. displayField makes a lot of sense anyway.

**Comment by markstory** [comment]
Closing as #5927 is open now.
