### ISSUE TITLE
Prefix routing should be able to distinguish between an url prefix and the function name prefix in the controllers

### ISSUE THREAD

**Issue by hmic** [cakephp/cakephp#4881]
As requested from others on irc, I would like to be able to have different url-prefixes from the function prefixes in my controllers.

e.g.
```php
Configure::write('Routing.prefixes', array('manager' => 'admin');

UsersController:
public function admin_index() { ... }
```
and beeing able to access `http://localhost/manager/users/index`

That looks easily achievable from the routers perspective though.

Will provide PR with tests.

**Comment by markstory** [comment]
Closing as the related pull request was also closed.
