### ISSUE TITLE
posixy_isatty throws a warning

### ISSUE THREAD

**Issue by trichins** [cakephp/cakephp#4901]
I just recently upgraded from 2.5 to 2.5.5 and I'm now seeing a warning error:

Warning Error: posix_isatty(): could not use stream of type 'Output' in [lib/Cake/Console/ConsoleOutput.php, line 166]

I'm using a ConsoleOutput with the stream of "php://output" and it looks like the posix_isatty function doesn't like that stream.  There needs to be a check before calling posix_isatty to make sure it isn't php://output.

**Comment by markstory** [comment]
Pull request #5743 fixes this.
