### ISSUE TITLE
3.0 i18n Forms

### ISSUE THREAD

**Issue by Soswald** [cakephp/cakephp#4902]
Shouldn't there be an easy DRY way of patching multiple translations of an entity's fields at once?
I don't know if there is, but I didn't find one.

Say I have an model "Page/PagesTable" where i18n is set up according to the book.
This model has the fields "title" and "content" where I want to save an german translation (with locale "deu") and an englisch default one. 
If I have an edit view, in order to get the translation automatically in an own input i have to make a input like
```php
$this->Form->input('_translations.deu.title');
```

But trying to save that via "patchEntity($page, $this->request->data);" results in the translation being thrown away.

My goal is to have "add/edit" forms for me, which allow me to edit both localized contents at one.

I know I could do it manually with the method described in the book.
```php
foreach ($translations as $lang => $data) {
    $article->translation($lang)->set($data, ['guard' => false]);
}
```
but populating the inputs in views and iterating over $this->request->data... by hand in the Controller doesn't seem DRY to me.

**Comment by burzum** [comment]
> so that fields without the _translation.{lang} prefix go into the pages table and the ones with _translations.{lang} go into pages_i18n table, regardless of the currently used language / i18n::locale. This way if, say I introduce a 'fra' language, but with entitys not yet translated, it would fetch the fallback fields from pages.

:+1: 

This is pretty much exactly how our custom Cake 2.x translation solution works.

**Comment by lorenzo** [comment]
@Soswald sounds like a great idea! Would you like to implement this feature?

**Comment by berarma** [comment]
I've implemented something like this, at least for patchEntity, in PR #6663. It's lacking tests and maybe it's not the way it should be done but it works for what I need now. I'm too busy right now to do more. I thought I should share it in case it helps someone.

**Comment by OopsDoh** [comment]
:+1: +1 for this request, this sounds very usefull! The translate behaviour is currently a simple and quite easy approach but gets tricky if you really want to provide all contents of your app in multiple languages...

**Comment by markstory** [comment]
As of 3.3.0 (#9225) TranslateBehavior can have a validator option set. This validator will be used to validate translated records, and the errors are propagated up to the root entity so `article._translations.deu.title` will work as you'd expect in a Form field.

**Comment by berarma** [comment]
Thanks to everyone that contributed to the progress of this enhancement.
