### ISSUE TITLE
HtmlHelper favicon

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#5023]
A small note...

When I use Themed in Cake 2, method from HtmlHelper like script and css works fine with path to webroot in Themed dir, but problem is with `$this->Html->meta('icon');` It's always get favicon from main webroot.

I think, it should be find favicon in main webroot when we not used $this->theme, and otherwise in Themed/NameTheme/webroot

**Comment by chrisvogt** [comment]
Should this ticket be closed? Was about to look into this, but seems it has already been taken care of.

**Comment by markstory** [comment]
@chrisvogt Yes, my mistake.
