### ISSUE TITLE
3.x RFC: pre-fill forms for new Entities with database defaults (mainly relevant for boolean values / checkboxes)

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#5065]
3.0 beta 2 seems not to pre-fill forms for new entities with defaults from the database.

For instance if you set a mysql ```TINYINT 1``` field like ```is_enabled``` to ```UNSIGNED NOT NULL DEFAULT 1``` it does not reflect this setting in the checkbox generated by the ```FormHelper``` on action ```add```

I think this feature really helped and is very convenient and should be reintroduced in 3.0 or later.

**Comment by markstory** [comment]
Pull request open for 3.3.0 now.

**Comment by ionas** [comment]
I love you guys <3.
