### ISSUE TITLE
3.0 - Tables don't save new entities when translating

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5106]
This may be an edge case but I thought I'd throw it out there. Right now if you try to save new entities without including a defined field, Cake doesn't do it.

Table..
```
CREATE TABLE `straplines` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `foo` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;
```

Class..
```
class StraplinesTable extends Table {
	public function initialize(array $config) {
		$this->addBehavior('Translate', ['fields' => ['strapline']]);
	}	
}
```

This fails...
```
$strapline = $this->Straplines->newEntity();
$strapline->translation('en_us')->set('strapline', 'test');
if (!$this->Straplines->save($strapline)) {
	die('no good');
}
```

But if you add the `foo` field, it all works. A new strapline record is created and my i18n table has the strapline text...
```
$strapline = $this->Straplines->newEntity(['foo' => 10]);
$strapline->translation('en_us')->set('strapline', 'test');
if (!$this->Straplines->save($strapline)) {
	die('no good');
}
```

I'd expect to be able to create new entities without having to pass in that `foo` part. I don't get any SQL errors and Cake doesn't attempt an INSERT. In addition to this would it be at all possible to get some kind of error when saving fails? My entity has no errors on it and there are no Exceptions thrown.

Thanks!

**Comment by mdlouhy** [comment]
@patrickconroy would you try to reproduce the error with the current cakephp version (and don't forget to include the translated field in the schema to exclude this error)

**Comment by patrickconroy** [comment]
Hi @mdlouhy, it's still the same behavior for me. With this schema:

```
CREATE TABLE `straplines` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `strapline` varchar(100) DEFAULT NULL,
  `foo` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;
```

You can't do this, no INSERT attempted, no errors on that entity.
```
# request data = Array
#(
#    [strapline] => test
#    [locale] => en_us
#)
#
public function add() {
	$strapline = $this->Straplines->newEntity();
	if ($this->request->is(['put', 'post'])) {
		$this->Straplines->patchEntity($strapline, $this->request->data());
		if ($this->Straplines->save($strapline)) {
			die('ok');
		}
	}
	$this->set(compact('strapline'));
}
```

(The reason I think this is a bug) If you add an arbitrary field when creating the entity, it works.
```
# request data = Array
#(
#    [strapline] => test
#    [locale] => en_us
#)
#
public function add() {
	$strapline = $this->Straplines->newEntity(['foo' => 1]);
	if ($this->request->is(['put', 'post'])) {
		$this->Straplines->patchEntity($strapline, $this->request->data());
		if ($this->Straplines->save($strapline)) {
			die('ok');
		}
	}
	$this->set(compact('strapline'));
}
```

I tried digging into why this is happening but came up empty.

**Comment by patrickconroy** [comment]
Just checked on this, it's still happening with 3.0.6.

```
$strapline = $this->Straplines->newEntity();
$strapline->translation('en_us')->set('strapline', 'test');
if (!$this->Straplines->save($strapline)) {
	pr($strapline->errors());
	// empty
    die('no good');
}
die('ok!');
```

```
CREATE TABLE `straplines` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `strapline` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8;
```

Still always `no good`.

**Comment by markstory** [comment]
I can take a poke at this, see if I can find a solution.

**Comment by markstory** [comment]
I think with the [simplified translations workflow](http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations) I think this issue can be closed. You will still need to set at least 1 field on the root table, but that is a restriction I don't think we necessarily want to remove as it can cause other issues.
