### ISSUE TITLE
cakephp 3.0 database credentials output in debug mode if there is a db error

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#5136]
cakephp 3.0 database credentials output in debug mode if there is a db error

I think it would be safer to never display db username password in error messages..

In cakephp 2.0 its done by replacing output with ***\* :
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Utility/Debugger.php#L451-L463

Thank you,
Andras

**Comment by mdlouhy** [comment]
This is not an issue anymore or am I wrong?

**Comment by dereuromark** [comment]
Is this still an issue?

**Comment by markstory** [comment]
Yes, the arguments are still visible if you know where to click and what to look for.

**Comment by markstory** [comment]
Closing as you can now mask values from Debugger using `Debugger::setOutputMask()`.
