### ISSUE TITLE
3.0 - Contain examples unclear/not working properly

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#5143]
The examples in the docs and the doc block for `Query::contain()` are a little unclear if you ask me:

```php
// Set options for the articles that will be eagerly loaded for an author
$query->contain([
	'Articles' => [
		'fields' => ['title']
	]
]);
```

Without any additional information, I would assume this to be a `Authors hasMany Articles` association, and that would trigger an error saying that is required to select the `Articles.author_id`. Assuming this is the correct behavior, I guess the example should either mention that and include the foreign key column, or it should use an association that can be clearly identified as `belongsTo`.

---

```php
// Use special join conditions for getting an article author's 'likes'
$query->contain([
	'Likes' => [
		'foreignKey' => false,
		'queryBuilder' => function ($q) {
			return $q->where(...); // Add full filtering conditions
		}
	]
]);
```

Again the association has to be guessed, and to me it sounds like `hasMany`, ie `Authors/Articles hasMany Likes`. That would however result in an SQL error, as the `WHERE` part would look somewhat like this:

```SQL
WHERE (Likes. in (:c0,:c1,:c2) AND custom_filtering_conditions_here) 
```

having an `IN()` condition without a column name.

**Comment by mdlouhy** [comment]
Isn't this already solved?

**Comment by markstory** [comment]
I am not sure. It is worth a second look.

**Comment by markstory** [comment]
Closing as #5560 is open.
