### ISSUE TITLE
PaginatorComponent  is a necessity to sort by primary key.

### ISSUE THREAD

**Issue by aokazu** [cakephp/cakephp#5148]
When you sort without including the primary key problem occurs.
(Double display , non-display)

Always last there is a necessity to sort by primary key.

Insert after line 377  of /lib/Cake/Controller/Component/PaginatorComponent.php

```
if ( $options['sort']<>"$object->name.$object->primaryKey" && $options['sort']<> $object->primaryKey ){
        $options['order'] = array_merge( $options['order'] , array( "$object->name.$object->primaryKey"=>'ASC' ));
}
```

**Comment by lorenzo** [comment]
Closing as the best solution will still be passing the right order clause for your specific query.
