### ISSUE TITLE
3.0 - JSONP Exceptions

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5194]
For JSONP requests, would it be possible to have exceptions know if the controller expects JSONP responses? Consider a request of `site/foo.json?callback=hey`

```
public function foo() {
	$_jsonp = true;
	$this->set(compact('_jsonp') + ['_serialize' => ['_jsonp']]);
	if (!$this->request->is('ssl')) {
		throw new CakeException("Access denied");
	}
}
```

If the request is SSL, the response has the callback wrapper. If it's non-SSL, I get a json response without the callback wrapper (the SSL thing is just an example - any Exception will illustrate this).

The only ways I can think to make this work are:
1. Updating the Core ExceptionRenderer to merge the calling controller's viewVars into its controller's viewVars.
2. Tell people who need this to create a custom ExceptionRenderer and have that class's render function set _jsonp to viewVars. 
3. Set a config var in the controller/elsewhere, `Configure::write('_jsonp', true);` and have Cake's Core ExceptionRenderer check for that.
4. Have jsonp on by default.
5. Wrap the entire contents of an action in a try/catch block and set the error/jsonp there for the view.

Having a way to mutate any json errors would be great, too. Right now it's message, URL, and code, which work 90% of the time but sometimes you'd want other arbitrary things in there for debugging, or whatever.

If someone thinks this isn't worth it, close it out. It's not impossible to do right now with 2 above, but I think it should be easier than that.

Thanks

**Comment by patrickconroy** [comment]
Yeah it's still happening. I think the middleware would need to be the thing setting the callback, since the script doesn't know what's happening after an Exception. Obviously this can't work:
```
public function add() {
	$_jsonp = true;
	$comment = ['foo' => 'bar'];
	throw new \Exception('hi');
	$this->set(compact('comment', '_jsonp'));
	$this->set('_serialize', 'comment');
}
```

I think setting `Configure::write('_jsonp', true);` in the controller would work, since that value can then be checked in the `JsonView`.

**Comment by ADmad** [comment]
@patrickconroy You can use a custom detector as suggested earlier.

```php
// 1. Add custom request detector
$request->addDetector('jsonp' => function () {
    // Check for required condition and set $this->params['_jsonp'] => true;
});

// 2. Map type jsonp to JsonpView
$RequestHandler->viewClassMap('jsonp', 'JsonpView');

// 3. Make JsonpView which extends JsonView. Override it's render() method to check for '_jsonp' request params along with view var.

**Comment by josegonzalez** [comment]
@ADmad is the detector bound to the request object?

**Comment by lorenzo** [comment]
@josegonzalez it is class method, so it will be available in all instances

**Comment by josegonzalez** [comment]
His example does the following:

```php
$request->addDetector('jsonp' => function () {
    // Check for required condition and set $this->params['_jsonp'] => true;
});
```

So I'm assuming that anonymous function has `$this` bound to the `$request` object.

**Comment by patrickconroy** [comment]
Thanks for your help guys. It's a little tricky changing the `viewClassMap` for a json request since the core seems to be using the json declaration even if I've created a jsonp one.

App logic. Doing it this way, the request for `test.json` is still using `JsonView`:
```
'RequestHandler' => [
	'viewClassMap' => ['jsonp' => 'Jsonp']
]

$this->request->addDetector('jsonp', function ($request) {
	if (!$request->is('json')) {
		return false;
	}
        // other stuff maybe, not sure yet..
	return true;
});
```

I *could* make different URLs for this like `test.jsonp` but I'd rather not do that. It would help if in core's `JsonView::render` there was this, which would negate the need for me to specify/create a new `View` class:
```
if ($this->request->is('jsonp')) {
    $this->viewVars['_jsonp'] = true;
}
```

So, at the moment, I can't keep the URLs consistent with only using app code.

**Comment by patrickconroy** [comment]
I could override all json views with: ``'viewClassMap' => ['json' => 'Jsonp']`` and then things will work, `JsonpView extends JsonView`. Is that the best way to do it?

**Comment by lorenzo** [comment]
I think that is a fair way to do it @patrickconroy

**Comment by patrickconroy** [comment]
Awesome thanks, @lorenzo!
