### ISSUE TITLE
3.0: Config merge is unexpected/error-prone

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5245]
This specific case is from a behavior config, but I think this applies to all configs.

We have a behavior that is added with these configs:

	$this->articles->addBehavior('Tools.Slugged', ['label' => ['title', 'another_title']);

At some point we want to modify the config key "label":

	$params = ['label' => ['title', 'another_cool_title']];
	$this->_table->behaviors()->Slugged->config($params);

One would think that adding the new label would overwrite the first one.
But in fact the array_merge/Hash::merge in the InstanceConfigTrait::_configWrite() probably is responsible that the configs stack up:

        'label' => [
                (int) 0 => 'title',
                (int) 1 => 'another_title',
                (int) 2 => 'title',
                (int) 3 => 'another_cool_title'	

This happens after applying config() with the above example code.
It only happens to config keys that have arrays as values.

Looking at the underlying config class it seems that it merges too eagerly.
The merge param of `config($key = null, $value = null, $merge = true) {}` should probably default to false for these scenarios, as it most cases this is quite unexpected and undesired behavior. The configs are a flat list.

**Comment by markstory** [comment]
Closing as we have configShallow() now.
