### ISSUE TITLE
3.0: Include symfony/intl

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#5356]
We're going to have users on shitty PHP 5.4 hosts who cannot install ext-intl. We should just require it in instead of ext-intl and be done with this problem. I had hoped this would not be the case, but I've already seen it crop up a few times in IRC, and I can imagine once we go GA it'll be a bigger issue :|

**Comment by lorenzo** [comment]
The amount of people having problems related to missing intl in both stackoverflow and irc has decreased considerably, I think it is safe to say that people actually have the ability to install the extension.

**Comment by Tomicapo** [comment]
I just tried to install CakePHP 3 on the grid service provided by mediatemple.net (shared hosting).
I believe it's not a shitty provider. But anyway, I just couldn't do it due to this intl extension problem.
Can someone tell me if the only way I'm going to be able to use CalePHP 3 is to change my provider (or my plan for a much more expensive one) ???

**Comment by markstory** [comment]
Duplicated in #6908. We're going to continue relying on ext/intl as it is the best option there is for internationalization, however the discussion in #6908 gives some alternative plugins that might help patch the intl methods you will need with stubs.

**Comment by dakota** [comment]
@tomicapo, as a first step. I would suggest contacting mediatemple's support and asking them to enable Intl. If they are not willing then they are (in my opinion) a shitty provider. For the cost of a mediatemple shared hosting you can get quite a decent box from digital ocean.

**Comment by Tomicapo** [comment]
Thanks @dakota I had already done that but they couldn't install it... So, they have their shitty aspects. But taking into account other things, they're actually quite good. For now, I just got a VPS with WHM from IntoVPS, but I'll check Digital Ocean as well.
