### ISSUE TITLE
3.0 - Associations and different connections

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5369]
If I have the following setup:
```
class ItemsTable extends Table {
	public function initialize(array $config = []) {
		$this->belongsTo('Posts');
	}
	public static function defaultConnectionName() {
		return 'custom';
	}
}

class PostsTable extends Table {
	public static function defaultConnectionName() {
		return 'default';
	}
}
```
And I try to get `Items`..
```
$items = TableRegistry::get('Items')->find('all')->contain(['Posts'])->toArray();
```

It errors out, complaining that the `Posts` table does not exist in the `custom` connection. Am I doing something wrong? I thought there might be a way to specify the connection in the association directly..
``
$this->belongsTo('Posts', ['connection' => ['default']);
``
but there isn't. And I really don't think I should need to specify `default` as the connection for `Posts`, as I'd expect Tables to use `default` by default even if their parent uses a custom one.

It will also error out if my `Posts` table is translated, since the Query doesn't know that my i18n table isn't in my custom connection, it's in the default one.

Is there a DataSource config option to make every Table use their connection's DB as a prefix? That would halfway solve this, but the i18n issue would still happen.

Thanks.

**Comment by patrickconroy** [comment]
I updated the TranslateBehavior @ https://github.com/patrickconroy/cakephp/commit/2bea4c11637fcb9aef8fe9cb073aff9a6d208493 with the changes that will make this work. Let me know if I should make a PR for that (it kind of diverges from the subject of this issue - it's to allow setting Tables for I18n purposes).

Thanks

**Comment by lorenzo** [comment]
Yeas, please. Make it a PR

**Comment by lorenzo** [comment]
Closing as the PR for translate behavior was merged
