### ISSUE TITLE
3.0: Include DI and/or Service Registry/Locator

### ISSUE THREAD

**Issue by jameswatts** [cakephp/cakephp#5378]
Given that this topic has been in my head for a while, and has also been discussed by @rchavik, @markstory, @lorenzo and others, I thought I'd at least put it out there, to see where the community stands on this. It can be an opinionated topic, which suites us CakePHP developers well :smiley: 

Right now, contrary to popular belief, CakePHP has had some form of [Dependency Injection](http://en.wikipedia.org/wiki/Dependency_injection) and [Service Locators](http://en.wikipedia.org/wiki/Service_locator_pattern) in the framework, they just haven't been built on a definitive abstract or API which facilitates this for re-use by developers, or when extending the framework. Undeniably, in **3.0** this has improved quite a bit by using events more to allow new functionality to be hooked up. But populating an event stack is not **DI**.

However, it would be good to know what the community thinks of CakePHP introducing a formal DI and/or Service Registry/Locator interface, as other frameworks do have this as a *feature*. There are existing options out there and available already, I even created something more *Cake-ish* for **2.x** code [here](https://github.com/jameswatts/cake-dependency).

So, this is an RFC, so speak your mind and let us know what you think. Thanks!

:fire:

**Comment by dereuromark** [comment]
We can close this one then.

**Comment by Krafcu** [comment]
@Schlaefer, @robertpustulka, @ADmad any chance sharing those 'trivial' 3rd party implementations of DI/SL ;)? I'm sceptic about using annotations for this purpose myself and got stuck on that for a few days now. Any help appreciated.

**Comment by ADmad** [comment]
@Krafcu https://github.com/lorenzo/piping-bag

**Comment by Krafcu** [comment]
@ADmad already got that one but like I said... no annotations.

**Comment by robertpustulka** [comment]
@Krafcu I've implemented my own IOC plugin for our company, but I cannot share this, not for now

**Comment by Schlaefer** [comment]
@Krafcu Also no public code. But if need I something trivial I setup a [simple static wrapper](https://gist.github.com/Schlaefer/e2e25eb3eb8b1b1ae541) for Aura.Di and call it a day.

**Comment by josegonzalez** [comment]
@Krafcu have you seen performance issues with ^ plugin re: annotation parsing?

**Comment by robertpustulka** [comment]
@josegonzales, it's not about performance. It's just that you shouldn't *code* inside your docblock.

**Comment by josegonzalez** [comment]
I mean at that point you could just use something like what @Krafcu mentioned :)
