### ISSUE TITLE
Shell not using correct tmp

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#5399]
When you reconfigure a 2.x application to use Composer and you try to use the Shell it will try and write to the `vendor/cakephp/cakephp/lib/Cake/Console/Templates/skel/tmp/cache` folder instead of your application `tmp`.

**What I tried**
```bash
/app $ Console/cake
```

**What happened**
```bash
vendor/cakephp/cakephp/lib/Cake/Console/Templates/skel/tmp/cache/very_short/ is not writable
```

**What I expected**
I expected the Console to run and return a list of commands.

**My hack**
I fixed this by editing my `app/Console/cake.php` to include.
```php
if (!defined('CACHE')) {
	define('CACHE', '..' . $ds . 'tmp' . $ds . 'cache' . $ds);
}
```

@hmic solves this problem by always defining the `-app` flag.

**Comment by markstory** [comment]
I tried to reproduce this and was unsuccessful. I did the following:

* Used a new clone of 2.6 to generate a project `Console/cake bake ~/Sites/composer-cake`
* Followed [the documentation for setting up composer](http://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-cakephp-with-composer)
* Ran `Console/cake bake model --help` in the newly created app.
* Ran `tree tmp/`, saw the files I was expecting.
* Ran `tree vendor/cakephp/cakephp/lib/Cake/Console/Templates/skel/tmp/` saw no additional files.

**Comment by davidyell** [comment]
When I am back in the office on Monday, I'll double check my setup to see if I can find any anomalies.
