### ISSUE TITLE
3.0 - FlashHelper feature request

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#5434]
Currently the FlashHelper has a single [render](https://github.com/cakephp/cakephp/blob/3.0/src/View/Helper/FlashHelper.php#L66-L82) method that is used to display a flash message. I have recently come into a situation where I would prefer not to render an element and instead get the flash message. Would it be possible to have a `get($key = 'flash', array $options = [])` method that behaves the exact same as `render()` without actually rendering the element?

**Comment by markstory** [comment]
Given there is a consume() method on Session is there anything else to do here?

**Comment by ADmad** [comment]
Nope, with Session::consume() added there's nothing more to do.
