### ISSUE TITLE
I18n should have its own cache key

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5472]
Currently, clearing cache for I18n would also clear/affect other `_cake_core_` caches.
It would be wise to change the key to something like

    _cake_i18n_

inside the persistent folder.

Then I18n::clear() or Cache::clear() can clear it without affecting other caches.

Does the proposed name sound good?

**Comment by tersmitten** [comment]
I like this feature.

**Comment by dereuromark** [comment]
So what approach do we wanna take?
I had this scenario where I wanted to clear the i18n, but it seems not trivial right now as there are many other things cached in _cake_core_.

**Comment by lorenzo** [comment]
Cache groups require another config as well

**Comment by markstory** [comment]
Could we do something like, use `_cake_i18n_` if its defined, and if not fallback to `_cake_core_`?

**Comment by markstory** [comment]
Closing as a pull request is up now.

**Comment by Spriz** [comment]
I see PR was closed @markstory

I'm rather confused on what the continous approach is for this issue :smile:

**Comment by markstory** [comment]
You could use a shell to clear the `_cake_core_` config which in 3.0 only contains translations. There is an open RFC for adding a core cache shell. #7368
