### ISSUE TITLE
saveAll does not work with non numeric primary keys

### ISSUE THREAD

**Issue by klickagent** [cakephp/cakephp#5481]
When I want to save a model and its association, it does not work when the associated model contains a non numeric primary key. E.g. when saving a new tenant and trying to add a relation in a habtm relation to a client with the primary key XYZ (primaryKey in model is set correctly).

$this->Tenant->saveAll(array(
	'Client' => array(
		'XYZ'
	),
	'Tenant' => array(
		'name' => 'newtenant'
	)
))

This only inserts the new tenant. The relation to the client is not being made. For debugging purpose only I changed XYZ to a numeric value. After that the record in the clients_tenants is being correctly created.

**Comment by markstory** [comment]
Closing its been a few weeks with no replies.
