### ISSUE TITLE
3.0 - Paginator dumps associations as arrays

### ISSUE THREAD

**Issue by oldskool** [cakephp/cakephp#5484]
Using CakePHP 3.0.0-beta3 I noticed something in the Paginator results which I find odd.
When doing a very basic Pagination (as the bake template for controllers does):

```php
public function index()
    {
        $this->paginate = [
            'contain' => ['ParentForums']
        ];
        $this->set('forums', $this->paginate($this->Forums));
    }
```

I noticed that the resulting `$forums` object has a `parent_forum` node, as you would expect. Although, this is an array of data, rather than an object.

![image](https://cloud.githubusercontent.com/assets/567664/5549970/4ee9b6ac-8b98-11e4-9de7-df75a740c449.png)

Any reason as of why? To me, it would seem cleaner to return that as an object as well, rather than an array.

**Comment by markstory** [comment]
I will look into the find threaded issue as that could be an issue.

**Comment by markstory** [comment]
I took a look into the find('threaded') issue and didn't see any problems:

```bash
[1] app > $categories = \Cake\ORM\TableRegistry::get('Categories');
// object(Cake\ORM\Table)(
//
// )
[2] app > $categories->find('threaded')->toArray()[0]->children;
// array(
//   0 => object(Cake\ORM\Entity)(
//
//   ),
//   1 => object(Cake\ORM\Entity)(
//
//   )
// )
```

Which shows the child objects coming back as entities as expected. The reason child entities show up as 'array' in debug kit is that the HTML formatting will call `toArray()` on any object that implements it. Entities implement this method and it converts all child objects into arrays.

**Comment by jadb** [comment]
I believe `var_dump` also calls `toArray()` and thus why @oldskool was getting an array for threaded children.

**Comment by markstory** [comment]
I'm not sure about var_dump() calling toArray(), however var_dump() in PHP5.6 will use `__debugInfo` which is something the entities also implement to change the actual data output.

**Comment by oldskool** [comment]
@markstory Good to know it's only a DebugKit display issue. Thanks for verifying.
