### ISSUE TITLE
Add setter to Console\HelpFormatter

### ISSUE THREAD

**Issue by bravo-kernel** [cakephp/cakephp#5499]
The Cake3 HelpFormatter generating the console help message currently uses two hardcoded 'cake' references and it would be more than nice if this could be made settable.

Console help currently always outputs:

```
cake command [subcommand] [-h] [-v] [-q]
To see help on a subcommand use `cake command [subcommand] --help`
```

A real world use case for this feature request would be a system wide `alias` pointing to a cake console where 'cake' as the command simply does not make sense. E.g.

```
 mamekit roms [subcommand] [-h] [-v] [-q]
 commercial-tool [subcommand] [-h] [-v] [-q]
```

**Comment by dereuromark** [comment]
@bravo-kernel Are you still interested in getting the basic PR here set up for it?

**Comment by cleptric** [comment]
Would be a new property in the `ConsoleOptionParser` which defaults to `cake` and is been injected into the `HelpFormatter ` a way to solve this?
In your `Shell::main` you could do sth like this:

```
$this->OptionParser->setHelpAlias('bravo');
```

which will output sth like:

```
Welcome to CakePHP v3.4.5 Console
---------------------------------------------------------------
App : src
Path: /Users/cleptric/Sites/app/src/
PHP : 7.1.4
---------------------------------------------------------------
Usage:
bravo foo [-h] [-q] [-v]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
```

**Comment by cleptric** [comment]
PR is open
