### ISSUE TITLE
3.0 - Implement MySQL RLIKE() expression

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#5515]
Hello,
It should be nice if the MySQL `rlike()` expression can be implementing, because i'm actually developing a "related posts" and i search it by their title, and i split each word in the title.
For exemple, i have a title like that `Test title 3`, and i wanted this SQL request :
```sql
SELECT * FROM posts AS Posts WHERE (Posts.id != 1 AND Posts.title RLIKE 'Test|title|3');
```
So, i can split each word into an array and after implode this array to get that `'Test|title|3'`. But actually, i can't use it to search my related posts.
I have tried many things, but without result, for exemple : 
```php
$keywords = preg_split("/[\s,]+/", $article->title);

$articles = $this->BlogArticles
		->find()
		->select([
			'title'
		])
		->where([
			'BlogArticles.is_display' => 1,
			'BlogArticles.id !=' => $article->id
		])
		->andWhere(function ($q) use ($keywords) {
			foreach ($keywords as $keyword) {
				$keyword = trim($keyword);

				if (!empty($keyword)) {
					$q->like('BlogArticles.title', "%$keyword%");
				}
			}
			return $q;
		});
```
It generate this request :
```sql
'sql' => 'SELECT BlogArticles.title AS `BlogArticles__title` FROM blog_articles BlogArticles WHERE (BlogArticles.is_display = :c0 AND BlogArticles.id != :c1 AND (BlogArticles.title LIKE :c2 AND BlogArticles.title LIKE :c3 AND BlogArticles.title LIKE :c4))',
	'params' => [
		':c0' => [
			'value' => (int) 1,
			'type' => 'integer',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => (int) 3,
			'type' => 'integer',
			'placeholder' => 'c1'
		],
		':c2' => [
			'value' => '%Test%',
			'type' => null,
			'placeholder' => 'c2'
		],
		':c3' => [
			'value' => '%article%',
			'type' => null,
			'placeholder' => 'c3'
		],
		':c4' => [
			'value' => '%3%',
			'type' => null,
			'placeholder' => 'c4'
		]
	],
```

But i don't want :
```sql
(BlogArticles.title LIKE :c2 AND BlogArticles.title LIKE :c3 AND BlogArticles.title LIKE :c4)
```
but this one :
```sql
(BlogArticles.title LIKE :c2 OR BlogArticles.title LIKE :c3 OR BlogArticles.title LIKE :c4)
```

So, the `rlike()` condition should solve all this related problems and would be easy to drequest like that.

**Comment by dereuromark** [comment]
Also, if RLIKE is supported via method, ILIKE might have to, as well.

**Comment by markstory** [comment]
So while `LIKE` is implemented consistently across the board regexp matching is unique on every platform:

* MySQL - `RLIKE` and `REGEXP` operators
* Postgres - `~` and `SIMILAR TO` operators.
* SQLServer - Supports Regexp in `LIKE`.
* SQLite - `REGEXP` operator.

Given that there is no common ground, and I'm not really convinced that RLIKE is commonly used enough to warrant both a function and query translation hook, I'd prefer to leave the method unimplemented and continue to recommend using the array conditions like @Xety is currently doing.
