### ISSUE TITLE
3.0 - Missing default templates for baking - src/Template/Bake/default

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#5533]
The default templates should not be in this directory? src/Template/Bake/default

**Comment by AD7six** [comment]
Nope.

Bake was made into [a plugin](https://github.com/cakephp/bake) - please see [the migration guide](http://book.cakephp.org/3.0/en/appendices/3-0-migration-guide.html#bakeshell-templatetask).

**Comment by andtxr** [comment]
Thanks @AD7six. Going to update the docs.
