### ISSUE TITLE
validateUnique no params possible

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5534]
fails:
```
['rule' => ['validateUnique', ['scope' => 'filter_id']], 'provider' => 'table']
```
Undefined index: data
Undefined index: newRecord
Undefined index: field

works:
```
['rule' => 'validateUnique', 'provider' => 'table']
```

THE FOLLOWING IS A DIFFERENT ISSUE BUT HAS MAYBE THE SAME OR A SIMILAR SOLUTION
you also can't pass params to function without losing $value and $context params
```
'rule' => [$this, 'customRule', 5, 6]
```
you have to do the following:
```
'rule' => [$this, 'customRole'], 'pass' => [5, 6]
```
and even if you use the 'pass' key, the params are passed between $value and $context
like:
public function customRole($value, $pass1, $pass2, $context) {}
I think that it would be better the following way:
public function customRole($value, $context, $pass1 = null, $pass2 = null) {}

so it would be more like using a static function call (i.e. Validation::naturalNumber)

**Comment by lorenzo** [comment]
This method is not meant to be called directly, although it _could_. What are you using it for?

**Comment by mdlouhy** [comment]
which method do you mean? I don't get it.

**Comment by lorenzo** [comment]
sorry, I misunderstood your issue since I only read the title :(

You you paste the code you are using for creating the validator and the data you are trying to validate?

**Comment by mdlouhy** [comment]
```
public function validationDefault(Validator $validator)
    {
        return $validator
                        ->add('number', [
                            ['rule' => ['validateUnique', ['scope' => 'filter_id']], 'provider' => 'table', 'message' => 'exists already']
                        ])

        ;
    }
```

**Comment by lorenzo** [comment]
Ok, I'll see if I can reproduce the error

**Comment by mdlouhy** [comment]
In the controller I did:
$data = $this->Model->get($id);
$data = $this->Model->patchEntity($data, $this->request->data);

**Comment by mdlouhy** [comment]
I confused data 'Application Rules' and basic validation when converting into entities. I'm sorry for wasting your time. I haven't understood the new validation concept until now.

What I wanna do shall be placed in buildRules() and not in validationDefault()
