### ISSUE TITLE
beforeRules callback not fired when newEntity(), patchEntity()

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5535]
Until now I modified some rules in 'beforeValidate' callback which I just wanted to replace by 'beforeRules' event but it isn't fired when using patchEntity or newEntity() for validation.
How can I modify the validation rules when using patchEntity with ['validate' => true]?
the event 'buildValidator' event is the only event which is fired when creating the validator.

**Comment by lorenzo** [comment]
No, it is fired for save() and delete(). Can you explain how do you change the validation rules?

**Comment by mdlouhy** [comment]
yes, of course.
It's pretty simple what I want to do:
I have a checkbox "Change Password". If it is NOT checked then the fields "old password", "new password" shouldn't be validated or saved.
In 'beforeValidate' callback I did the following:
```
public function beforeValidate(Event $event, Entity $entity, ArrayObject $options, Validator $validator)
    {
        if (isset($entity->change_password) AND empty($entity->change_password)) {
            $removeFields = ['passwd', 'old_passwd', 'passwd_confirm'];
            foreach ($removeFields AS $field) {
                if ($entity->has($field)) {
                    $entity->unsetProperty($field);
                }
            }
        }
    }
```

**Comment by lorenzo** [comment]
Ok, the right way of handling this is using "conditional validation"

```php
$validator->add('passwd_confirm', 'check', [
  'rule' => [...],
  'on' => function ($context) {
    return empty($context['data']['change_password']);
  }
])
```

**Comment by mdlouhy** [comment]
thanks! I haven't thought about that.

**Comment by mdlouhy** [comment]
But modifying validation rules before validating in patchEntity is not planned to be implemented?

**Comment by lorenzo** [comment]
@mdlouhy just assign the closure to a variable and pass it to all rules that may need it.

**Comment by mdlouhy** [comment]
oh yeah :P I am thinking complicated at the moment :P

**Comment by lorenzo** [comment]
@mdlouhy is it assigning a variable more complicated than creating a full method that removes validation rules?

There is no plan yet to re-add the callbacks. I personally thing there are more than enough building blocks that makes validation super flexible, but we can see how this evolves and re-add them if needed

**Comment by mdlouhy** [comment]
I don't understand why patchEntity cannot call 'checkRules' internally for doing validation...

**Comment by mdlouhy** [comment]
I confused data 'Application Rules' and basic validation when converting into entities. I'm sorry for wasting your time. I haven't understood the new validation concept until now.
