### ISSUE TITLE
passing params to custom validation rule without requiring using 'pass' param

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5536]
you also can't pass params to function without losing $value and $context params
```
'rule' => [$this, 'customRule', 5, 6]
```
you have to do the following:
```
'rule' => [$this, 'customRule'], 'pass' => [5, 6]
```
and even if you use the 'pass' key, the params are passed between $value and $context
like:
public function customRule($value, $pass1, $pass2, $context) {}
I think that it would be better the following way:
public function customRule($value, $context, $pass1 = null, $pass2 = null) {}

so it would be more like using a static function call (i.e. Validation::naturalNumber)

**Comment by markstory** [comment]
You are defining your custom rule incorrectly. You should use:

```
[
'provider' => 'table',
'rule' => ['customRole', 5, 6]
]
```

Did you see the form you were using in the docs? If so on what page as I'd like to correct the mistake.

**Comment by mdlouhy** [comment]
This helps to avoid 'pass' using param. Thanks.
But the actual problem for me is the method argument order of $context param.
$pass1 and $pass2 are both optional therefore the $context param is at position 2 oder 3 oder 4 depending on whether $pass1 and/or $pass2 is passed.

Therefore I would like to change the order of of the params, so $context is always at position two and $value is always at position one and other params can have default values by using simply defining them in the method signature.

I hope you understand what I mean.

**Comment by markstory** [comment]
Do your custom validators have varying number of arguments? I don't understand why 2nd is a better position over last.

**Comment by mdlouhy** [comment]
```
public function validateInteger($value, $min, $max, $context) {}
```
I think that it would be better the following way:
```
public function validateInteger($value, $context, $min = null, $max = null) {}
```
I want to call without any param or just with $min param or with $min and $max.
validateInteger does some misc checking and additionally the method checks $min and $max optionally.

**Comment by dereuromark** [comment]
The suggested change sounds somewhat reasonable to me.
Adding more arguments later would not break BC / the api of it.

**Comment by lorenzo** [comment]
If you want to do that then register a provider this way in your table:

```php
$validator->provider('simple', new \Cake\Validation\RulesProdiver($this));
$validator->add('my_field', 'rule_name', ['rule' => ..., 'provider' => 'simple']);
```

When doing this, the "$context" argument will not be passed as it is the case with the `Validation` class.

I'd rather not add more ways of doing the same thing, so for that reason I'm closing this.

**Comment by mdlouhy** [comment]
I have another suggestion which would allow passing params without caring about the order because there is an associative options array:
```
$args = array_merge([$value], [$context], [$this->_pass]);
```

```
public function validateInteger($value, $context, $options = []) {}
```

**Comment by lorenzo** [comment]
@mdlouhy the only problem with that last suggestion is that it would break the way parameters are passed to the `Validation` class, but I guess that could be worked around. Let us know if using another provider did the trick for you.

**Comment by mdlouhy** [comment]
okay I did it now - here is my working solution:

src/ORM/Table.php
```
    public function validator($name = 'default', Validator $validator = null)
    {
        $validator = parent::validator($name, $validator);
        if ($validator->provider('simple') === null) {
            $validator->provider('simple', new \App\Validation\RulesProvider('\App\Validation\CustomValidation'));
        }
        return $validator;
    }
```

src/Validation/RulesProvider.php
```
namespace App\Validation;

class RulesProvider extends \Cake\Validation\RulesProvider
{

    public function __call($method, $arguments)
    {
        $value = current($arguments);
        $context = array_pop($arguments);

        $arguments = array_merge([$value], [$context], array_slice($arguments, 1));
        return call_user_func_array([$this->_class, $method], $arguments);
    }

}
```

src/Validation/CustomValidation.php
```
namespace App\Validation;

class CustomValidation extends \Cake\Validation\Validation
{

    public static function validateInteger($value, $context, $min = null, $max = null)
    {
    }
}
```
