### ISSUE TITLE
3.0 - Rename String class

### ISSUE THREAD

**Issue by jrbasso** [cakephp/cakephp#5537]
Since 3.0 is not in RC/GA stage, I guess we should consider to rename or split the methods from the class String.

In PHP 7 string will not be allowed as class name. It means that people that upgrade to CakePHP 3.0 (and maybe all the 3.x block) will be incompatible with PHP 7. Changing the class name between minor releases to be compatible with a new PHP version is bad for backward compatibility and bumping the major version sometimes is also hard because we could be working on that for long time, like on 3.0 that we are working for over 2 years.

Reference: https://wiki.php.net/rfc/scalar_type_hints
> No new reserved words are added. The names int, integer, float, string, bool and boolean are recognised and allowed as type hints, and prohibited from use as class/interface/trait names.

PS: The RFC is not approved yet, but from comments on PHP internals list it is being refined and probably it will be approved.

PS 2: String name is incompatible with other PHP-related things, such as Zephir and HHVM for a long time (not sure if still).

Someone has suggestions for the new class name(s)?

**Comment by markstory** [comment]
The class name isn't string though. Its `Cake\Utility\String`. While we had issues with `String` in 2.x + HHVM, HHVM does not have the same issues with the namespaced version in Cake3.

**Comment by josegonzalez** [comment]
What if you call `use` on the class? Wouldn't that also result in issues?

**Comment by markstory** [comment]
Yeah that might cause issues. As for alternative names, we could always ape CI/Kohana/Laravel and use `Str`

**Comment by jrbasso** [comment]
But it will be an issue with that RFC from PHP. The typehint will be
string, but is that native or a class in the same namespace or alias (not
sure if you can use scalar type names as alias)?! I guess it will cause
some sort of problem that we can avoid anyway.

I will try to compile PHP code with the change (
https://github.com/php/php-src/pull/972) and test if classes with
namespaces are fine. In either case I will add a consideration to PHP
internals and probably add a test case to cover it on that PR.

**Comment by josegonzalez** [comment]
Yeah I think the best route is to rename to not String. What's the string class currently do? Is there a better name than Str?

**Comment by ADmad** [comment]
> we could always ape CI/Kohana/Laravel and use `Str`

This sounds good to me

**Comment by milesj** [comment]
I had to rename `String` to `Str` since it does fail in HHVM when importing. It's the easiest solution.

**Comment by thaJeztah** [comment]
Perhaps "Text", to prevent using an abbreviation?

**Comment by dereuromark** [comment]
`Text` sounds good to me.

**Comment by thaJeztah** [comment]
Yes, `Text` isn't perfect either, but thought I'd add it to the list of options to consider.

Looking at `String`, most things are "text" related, so it (kind of) makes sense, although `String::uuid()` is the odd one out (imo), perhaps that method should be moved to a different class with a better name, but I'm not sure there.

**Comment by dereuromark** [comment]
Maybe move uuid() and alike to `Str` class. and make the more "text"like ones then Text for the helper to access them then.

**Comment by thaJeztah** [comment]
Not sure 'uuid' is something really "String-y". I just did a quick lookup; other frameworks seem to be giving it a class of its own; [Symfony](http://symfony.com/doc/current/reference/constraints/Uuid.html), [.Net](http://msdn.microsoft.com/en-us/library/system.guid.newguid(v=vs.110).aspx), which doesn't sound bad I think.

**Comment by dereuromark** [comment]
`Uuid::generate()` and `Uuid:validate()` so to speak.

**Comment by thaJeztah** [comment]
Sounds good, bit hesitant to introduce a config (because that may require a config lookup for each uuid generated?). Passing the type of UUID to generate as a parameter may be a good start though.

**Comment by markstory** [comment]
I don't think we really need config options or multiple versions of uuid. In the rare case someone needs that they can use an existing implementation.

Renaming to Text sounds better than str to me. I would also keep the String alias around as this won't be an issue until php7 which is a way out.

**Comment by jrbasso** [comment]
I like the `Text` name too. The only 2 odd methods are `uuid` and `parseFileSize`. I think we can create a class `Uuid` on utility namespace and just have a generate method, as @dereuromark suggested. We don't need to have the other versions on this class, but it is easy to implement/extend in case someone wants to and makes very simple to keep backward compatibility in future releases.

For `parseFileSize` it is weird, but not terrible, so probably we can keep on `Text` class.

@markstory Having alias with autoload is complicated sometimes, unless we keep the `String` class extending the `Text` class.

**Comment by jrbasso** [comment]
For now I created the branch [`3.0-string-class`](https://github.com/cakephp/cakephp/compare/3.0...3.0-string-class) with the class rename only until we discuss the future of uuid.

Once we define it I will update cakephp/upgrade and cakephp/docs repos too.

**Comment by markstory** [comment]
@jrbasso We have used class_alias() in the past to good results.

**Comment by dereuromark** [comment]
@jrbasso Looks good, but you should probably keep a `String extends Text` class for all that already use `3.0.0` to not break it right away for them. You can trigger a `deprecated` notice in the constructor to alert them to update their code.

**Comment by lorenzo** [comment]
@jrbasso class alias has worked super nice for us so far

**Comment by jrbasso** [comment]
I'm out for lunch, will update it in soon.

**Comment by ADmad** [comment]
Doh, I just removed all class_alias() yesterday and you guys are adding it back again. Screw y'all :trollface:

**Comment by lorenzo** [comment]
haha

**Comment by markstory** [comment]
@ADmad This is a new/different use for class_alias though :smile:

**Comment by jrbasso** [comment]
Changes in place. I opened the PR, so we can discuss there if we need more changes.

@ADmad sorry. You will have the opportunity to remove it later on. :)
