### ISSUE TITLE
Still password in plain texts

### ISSUE THREAD

**Issue by harikt** [cakephp/cakephp#5538]
Hi , 

Nice work! Trying out cake 3.0 for the first time. Really excited seeing the easy way of baking things.

One thing I noticed is passwords were not hashed. http://book.cakephp.org/3.0/en/quickstart.html#adding-password-hashing

The method seems not getting called 

```php
    protected function _setPassword($value)
    {
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($value);
    }
```

Thanks

**Comment by ADmad** [comment]
Did you do some debugging and confirm your entity class is being loaded? Most likely you made a mistake in named it incorrectly or placed it at wrong location due to which the default Entity class is being used.

Closing as this sounds more like a support question than an actual issue. Please use stackoverflow or cake-php google group for such questions.

**Comment by harikt** [comment]
Thank you @ADmad :) .

**Comment by harikt** [comment]
By the way @ADmad if you wrote the documentation try yourself and see if things work. So others may not need to repeat the same ? Who knows.

**Comment by lorenzo** [comment]
it did work for me @harikt, if you put your code in a git repo I can review it for you.

**Comment by harikt** [comment]
@lorenzo Thank you. This is what I have https://github.com/harikt/try-cakephp3

**Comment by lorenzo** [comment]
I'll take a look

**Comment by lorenzo** [comment]
@harikt I just cloned you repo and connected it to an already existing database that I had. Passwords seem to be updated just fine. Out of curiosity... do you have the mcrypt or openssl php extensions installed?

![screen shot 2015-01-02 at 10 45 29](https://cloud.githubusercontent.com/assets/37621/5595195/921545ba-926c-11e4-8f3a-9dc920f1da9f.png)

**Comment by mdlouhy** [comment]
maybe password is not updated because of $_accessible variable which restrict converting request data to entities

**Comment by lorenzo** [comment]
No, we already figured out the problem in IRC. To prevent his problem from happening we may need to do some minor changes in the marshaller class.

**Comment by mdlouhy** [comment]
what is/was the problem? I am curious :P
