### ISSUE TITLE
3.0 - Hidden inputs being affected by customized form templates

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#5546]
The hidden inputs auto generated by FormHelper are being affected by customized form templates.
Follows a configuration example:

```php
$config = [
    'input' => '<div class="div-class"><input class="input-class" {{type}}{{name}}{{attrs}}></div>',
];
```

Fields like 'active' that have a hidden input will receive it too. Is this how it should be?

**Comment by ADmad** [comment]
The `input` template should not have a wrapping div. Modify the `inputContainer` and `inputContainerError` templates to customize the wrapping div.

**Comment by andtxr** [comment]
Forgetting the div, the problem I had mentioned is the class attribuition.
For example, creating a specific template for a css framework as foundation, bootstrap, or even something personal, the class will be attached to hidden inputs too.

**Comment by ADmad** [comment]
Well in the past people have complained about being able to add classes to hidden input. Given that the input is hidden any attached classes are not going to affect display.

**Comment by andtxr** [comment]
A new template item for the hidden inputs would be good to avoid some CSS troubles. Thanks @ADmad

**Comment by ADmad** [comment]
Have you encountered any actual issues due to css classes being applied to hidden inputs?

**Comment by jonlachmann** [comment]
I have encountered an issue with this. I have set the 'input' template as below, to put the input in one column and the label in another one (using bootstrap for css framework).

Whenever i create a hidden field it breaks my layout because the hidden field also gets the col-xs-10 container div. A specific template for the hidden input would be great!

```
'input' => '<div class="col-xs-10"><input class="form-control" type="{{type}}" name="{{name}}"{{attrs}}></div>',
```

**Comment by markstory** [comment]
Having a hidden input template is doable, are there other input types that justify having their own templates? Having all the inputs share one template except for hidden inputs is a bit inconsistent.

**Comment by jonlachmann** [comment]
I can see the benefit in having all inputs having their own templates, it might be necessary for some css frameworks. With this in mind, the hidden input is the one that will probably most often differ from the others.

My vote is for different templates for all input types!

**Comment by ADmad** [comment]
@jonlachmann Why are you putting the wrapping divs in the `input` template instead of `inputContainer` ?

**Comment by jonlachmann** [comment]
@ADmad because i want the div to wrap only the input and not the label. Using bootstrap and wanting to have a form with labels on the left of the input. Another solution would be to have the container have different tags for the label and input? Maybe this is the best solution?

**Comment by AD7six** [comment]
I suggest showing the html you want to achieve - rather than "I changed the input template to contain divs and now things are broken"

**Comment by jonlachmann** [comment]
@AD7six that is a good suggestion, I was in a hurry before and apologize for the incomplete comment. Below you find the html i require.

```
<div class="form-group">
	<label for="email" class="control-label col-xs-2">Email</label>
	<div class="col-xs-10">
		<input class="form-control" type="email" name="email" required="required" maxlength="255" id="email">
	</div>
</div>
```

**Comment by ADmad** [comment]
@jonlachmann You can achieve what you want by modifying `formGroup` template.

**Comment by jonlachmann** [comment]
@ADmad please smack me in the head for wasting your time and not realizing that!

**Comment by ADmad** [comment]
@jonlachmann With pleasure :smile:

**Comment by ADmad** [comment]
@jonlachmann I suggest checking out the [bootstrap-ui](https://github.com/FriendsOfCake/bootstrap-ui) plugin.

**Comment by jonlachmann** [comment]
@ADmad That surely is a more convenient way to do it than what I am doing, next revision of this project will surely use that. I'm not sure it is a good thing that you reward me with this for asking stupid questions ;P

**Comment by ADmad** [comment]
@jonlachmann I am hoping using that plugin will avoid you asking stupid questions :stuck_out_tongue:
