### ISSUE TITLE
3.0: Better debug output for missing Locale class

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5553]
I saw a lot of those so far:
http://stackoverflow.com/questions/26153837/class-locale-not-found-issue-on-cakephp-beta

What about a 

    if (!class_exists('\Locale')) {
        throw \Exception('Locale class cannot be found. Please make sure you have the intl extension enabled.');

for the bootstrap in debug mode?
This way it would be visible to those that do not know the Locale class is part of the intl extension. We could give better feedback on what needs to be done.

**Comment by markstory** [comment]
I can add something to that effect.

**Comment by antograssiot** [comment]
I agree this is anoying, one solution might be : 
```php
if (!extension_loaded('intl')) {
	trigger_error('You must enable the intl extension', E_USER_ERROR);
}
```
just before the 
```
require ROOT . DS . 'vendor' . DS . 'autoload.php';
```

but still I don't understand why composer managed to install cakephp as it requires "ext-intl" !?

**Comment by dakota** [comment]
If you directly download the release zip then you don't install via
composer.

**Comment by ADmad** [comment]
We should remove the download link from cakephp.org homepage unless we have a stable release for 3.0 :)

**Comment by antograssiot** [comment]
sure @dakota but back when I was using xamp on windows I got this exact the same problem install it by composer only. I can still give it a try.

**Comment by markstory** [comment]
@ADmad The zip packages are on the github release pages.

**Comment by ADmad** [comment]
@markstory Yup, which we can't hide, can only document not to use them.

**Comment by dereuromark** [comment]
Closing as a PR is now open.
