### ISSUE TITLE
3.0 - Add a JsonConfig engine for Configure

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#5563]
Given the popularity of json files these days to store config data, a JsonConfig engine would be useful.

**Comment by hdogan** [comment]
I think YAML is more popular than JSON for configuration purposes. Lots of frameworks use YAML instead of JSON. It can use yaml extension (if exists/installed) or https://github.com/symfony/Yaml package (like `intl` support).

**Comment by ADmad** [comment]
I personally am not in favor of adding external dependencies nor maintaining non trivial parsers for something that isn't needed in core itself.

A JsonConfig engine on the other hand is extremely simple.

**Comment by markstory** [comment]
I personally really hate json for configuration. Not being able to use comments is super annoying.
