### ISSUE TITLE
Problem with date format.

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5567]
Hello,
I have a datetime field named eventstartdate.
I edit it in a form like follows:

```
	<div class="form-group">
		<?= $this->Form->input('eventstartdate', ['label' => __("Date de début d'évènement :"), 'type' => 'text', 'class' => 'form-control', 'placeholder' => __("Cliquez pour faire apparaître le calendrier")]); ?>
	</div>
```

So when the form is displayed, the date (with a french locale) is displayed in the format dd/MM/yyyy HH:mm:
![sitemessages](https://cloud.githubusercontent.com/assets/9322571/5606515/09e9e9f2-9433-11e4-8853-4a8f91a6f287.png)

But when I submit the form, I get a validation error, certainly caused by the format because if I enter the date with the format yyyy/mm/dd HH:mm, I don't get any error.

So to resume it seems that the dates are curently correctly converted in read but not in write.

Alain.

**Comment by markstory** [comment]
When you are validating the data are you setting the format?

**Comment by lorenzo** [comment]
@markstory the format in validation is one problem, the other is getting the date to be marshalled correctly. I'm thinking to add an option to DataTimeType to alway interpret strings in the locale format, would that be a reasonable solution?

**Comment by markstory** [comment]
Either locale format or a static format would be good.

**Comment by caBBAlainB** [comment]
@markstory, I'm unfortunately unable to answer you... :( I could just suppose that the format is set somewhere as the conversion is done during read..... 
I think that Jose is about of the problem so, I'l let him take care of it....
Thanks to you.

**Comment by lorenzo** [comment]
Closing as there is a pull request to fix the problem

**Comment by caBBAlainB** [comment]
Ok, good luck.... ;-)
