### ISSUE TITLE
Problem while updating a field (3.0.0-RC1)

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5568]
I encounter a problem which is maybe not an issue or maybe an issue with bake, my low knowledge about SQL pevents me to guess what's wrong here..

I have a table where I declared the field **registration** as an index because I will mainly look for the records based on this field: so the index table looks like:
http://i.imgur.com/oxO4Xeu.png

When I created my application with cake bake, it generated the table defining registration field as a primaryKey.
But that prevent any update on that field and the resulting sql log looks like that:
http://imgur.com/z22VaLJ
The gists, give you all details on my code.
https://gist.github.com/caBBAlainB/ff028a2bbf02918efff5

For info, Jose had a look at  the problem.

Regards,
Alain

**Comment by lorenzo** [comment]
This turned out to be a problem in how the primaryKey of the table was defined.
