### ISSUE TITLE
Redis class not exists

### ISSUE THREAD

**Issue by kimegede** [cakephp/cakephp#5570]
Cake 2.5.8 - if `Redis` class doesn't exists, this error will be thrown:

```php
PHP Fatal error:  Uncaught exception 'CacheException' with message 'Cache engine _cake_core_ is not properly configured.' in /var/www/cake258/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php:181
Stack trace:
#0 /var/www/cake258/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')
#1 /var/www/cake258/App/Config/core.php(282): Cache::config('_cake_core_', Array)
#2 /var/www/cake258/Vendor/cakephp/cakephp/lib/Cake/Core/Configure.php(72): include('/var/www/cake258/...')
#3 /var/www/cake258/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)
#4 /var/www/cake258/App/webroot/index.php(85): include('/var/www/cake258/...')
#5 {main}
  thrown in /var/www/cake258/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php on line 181
```

Should this part be tested a bit before?
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Cache/Engine/RedisEngine.php#L57

**Comment by dereuromark** [comment]
Sounds reasonable to have a basic check on it prior to using it. That would make the error message a little bit less cryptic.

**Comment by kimegede** [comment]
If I can get some pint points, I'm willing to look into this :)

**Comment by markstory** [comment]
The error message you're seeing is the error message that indicates something is wrong with the cache configuration. I can add an additional

**Comment by markstory** [comment]
The error message you're seeing is the error message that indicates something is wrong with the cache configuration. A similar error is used for memcache/memcached.

**Comment by markstory** [comment]
Pull request up to improve the error message.

**Comment by kimegede** [comment]
Cool @markstory ! :)
