### ISSUE TITLE
Problem with the new validation mechanism

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5575]
Hello,
That's not really an issue, more a general problem concerned by the new validation mechanism.

1. Entity creation:
Maybe I had to change my method but before, I declared my UsersController (for example) like that:
We suppose that it's associated to a view which contains a Form:

    public function add() {

        $user = $this->Users->newEntity($this->request->data);

        if ($this->request->is('post')) {
             if ($this->Users->save($user)) {
                $this->Flash->success("Wonderfull");
                return $this->redirect(['action' => 'view']);
            } else {
                $this->Flash->error("Bad luck!");
            }
        }
        $this->set(compact('user'));
    }

The problem is about newEntity() which fills in the entity with 'This field is required' errors and display it for all concerned input in the form when this one is just displayed, so before any submit.

How do deal with it??

Do we now have to write:

    $user = $this->Users->newEntity($this->request->data, ['validate' => false]);

    if ($this->request->is('post')) {

        $user = $this->Users->patchEntity($user, $this->request->data);
        ...
    }

2. The second problem concerns the way that the validations are done now.
Before RC1, validations were done by save() call, or validate() call. 
The new mechanism has maybe some advantages that I didn't really realize again but also, few disavantages I think.

The big advantage we had before, was the call to setters BEFORE the validation began.

Consider a text input where I can enter a latitude.
A latitude can be entered as 48.858528 or 48°51'30.7"N.
Before it was really easy to call a setter to convert 48°51'30.7"N to 48.858528 and then validation was done by the rule:
    ->add('latitude', 'valid', ['rule' => 'numeric')]),

With the new validation mechanism, I cannot validate this kind of input!

I have to transfer the validation in RulesChecker, called by save(), where the setters are called.
But the RulesChecker is normally no supposed to be used for that, right?

So, I really think that setters calls should ALSO be done by patchEntity() and newEntity().
Also by save()? Certainly, but maybe not if they have been called first by patchEntity() or newEntity()... I don't know...

If you don't implement getters/setters calls in patchEntity() and newEntity(), I'm afraid that little by little, all validations will be done in the RulesChecker() and entities validation mechanism could be not used at all.

I already had the same problem with date, ok, just because date format conversion is not ok again and so, I had to make the date validation in RulesChecker() (Thanks to Jose again), just to convert a dd/mm/yyyy format to yyyy/mm/dd. What a pity!
But I guess that we will have many situations where we would enter 'human' readable datas and convert it to 'storage' format. Not so convenient with the new mechanism.

What's your opinion?

**Comment by lorenzo** [comment]
Change you add action to this:

```php
$user = $this->Users->newEntity();

if ($this->request->is('post')) {
    $user = $this->Users->patchEntity($user, $this->request->data);
     if ($this->Users->save($user)) {
        $this->Flash->success("Wonderfull");
        return $this->redirect(['action' => 'view']);
    } else {
        $this->Flash->error("Bad luck!");
    }
}
$this->set(compact('user'));
```

Bake templates have changed to reflect this change in how validation is done.


> Before it was really easy to call a setter to convert 48°51'30.7"N to 48.858528 and then validation was done by the rule:
> ->add('latitude', 'valid', ['rule' => 'numeric')]),

Don't validate the field as only numeric. Validate the formats that you allow and use a setter in the entity or beforeSave method to changed it to a number value.

> If you don't implement getters/setters calls in patchEntity() and newEntity(), I'm afraid that little by little, all validations will be done in the RulesChecker() and entities validation mechanism could be not used at all.

It is fine to have a lot of validation in RulesChecker. The first validation step is for data from the user, which can be in a lot of different formats that may not be too friendly. RulesChecker is used to assert that the data was normalized and cleaned so that is friendly for the machine.

**Comment by caBBAlainB** [comment]
Ok, thanks a lot lorenzo. 
How to put a 'question' label ??
How can I use a setter for entity?

**Comment by lorenzo** [comment]
You already do know how to use entity setters. You just talked about them!

There is no way for people to set the question label on their own.

**Comment by caBBAlainB** [comment]
yes but they are not called by patchEntity() or newEntity().

**Comment by lorenzo** [comment]
@caBBAlainB They are not called because they failed your validation. Change your validation or remove it if you accept the formats that you actually care for. Then, when the setter is called with the data you can do any transformations you may need

**Comment by caBBAlainB** [comment]
ok. I try that. thanks a lot.
I don't see how to declares several formats.

**Comment by lorenzo** [comment]
You will need a custom validation rule @caBBAlainB

**Comment by caBBAlainB** [comment]
Please could you just tell me if the following code is the right way to do because I saw in the doc that all rules are evaluated even if the previous one failed.
But, it seems that they are also all evaluated even if the previous one was sucessfull :-(

    ->add('longitude', 'validCoordinates', [
        'rule' => function ($value, $context) {
            if (is_numeric($value) || preg_match('/^([0-9]+)\&deg;([0-9]+)\'([0-9,.]+)\&quot;[a-z]?$/i', htmlentities($value))) {
                return true;
            }
            return false;
        },
        'message' => __('La donnée indiquée est incorrecte')
    ])

**Comment by lorenzo** [comment]
Yeah, that is the idea of validation... that all rules are checked until one fails. I you case I would suggest putting all the checks inside the same callable.

```php
function ($value, $context) {
  if (is_good_format($value)) {
     return true;
  }

 if (is_another_good_format($value)) {
     return true;
  }
  return false;
}
```

**Comment by caBBAlainB** [comment]
ok thanks
