### ISSUE TITLE
Default $_accessible = ['*' => true] Documentation wrong

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5577]
http://book.cakephp.org/3.0/en/orm/entities.html#entities-mass-assignment

**Comment by lorenzo** [comment]
Can you help us identify what is wrong about it?

**Comment by markstory** [comment]
Good catch, the default was changed when we made bake generate the field list. I'll update the docs.

**Comment by mdlouhy** [comment]
I know that the default changed - that's what I meant.
I could have written/described it more clearly.

**Comment by mdlouhy** [comment]
#2227

**Comment by mdlouhy** [comment]
https://github.com/cakephp/docs/pull/2227

**Comment by mdlouhy** [comment]
check proposed change

**Comment by dereuromark** [comment]
Closing as a PR is now open.
