### ISSUE TITLE
3.0 - FixtureManager uncovered edge cases

### ISSUE THREAD

**Issue by jadb** [cakephp/cakephp#5579]
```diff
diff --git a/tests/TestCase/TestSuite/FixtureManagerTest.php b/tests/TestCase/TestSuite/FixtureManagerTest.php
index 4b8c9b7..fafc201 100644
--- a/tests/TestCase/TestSuite/FixtureManagerTest.php
+++ b/tests/TestCase/TestSuite/FixtureManagerTest.php
@@ -72,4 +72,23 @@ class FixtureManagerTest extends TestCase
             $fixtures['plugin.test_plugin.articles']
         );
     }
+
+    public function testFixturizeCustom()
+    {
+        $test = $this->getMock('Cake\TestSuite\TestCase');
+        $test->fixtures = ['custom.articles'];
+        $this->manager->fixturize($test);
+        $fixtures = $this->manager->loaded();
+    }
 }
```

Fails:

```
..E

Time: 487 ms, Memory: 8.00Mb

There was 1 error:

1) Cake\Test\TestSuite\FixtureManagerTest::testFixturizeCustom
Undefined variable: baseNamespace

/Users/jad/Projects/Contrib/cake/src/TestSuite/Fixture/FixtureManager.php:164
```

Another one that fails hard (undefined offset) is with plugins that use vendor name, like gourmet/faker (i.e. `$fixtures = 'plugin.gourmet/faker.articles'`). I had to use: `plugin.gourmet/faker/articles` for it to work.

**Comment by ADmad** [comment]
In your test case in string 'custom.articles' what is "custom" supposed to be?  If it's mean to be vendor name then the usage is incorrect. It should be `custom/articles` or rather `Custom/Articles`.

For you second eg. instead of  'plugin.gourmet/faker.articles'  try 'plugin.Gourmet/Faker.Articles'.

**Comment by jadb** [comment]
Does not work.

I understand that for custom you're wondering what it is for but I wondered the same when i saw this: https://github.com/cakephp/cakephp/blob/3.0/src/TestSuite/Fixture/FixtureManager.php#L159-L161

I was just trying to tell you guys that there is an edge case you guys seem to want to cover that fails hard (undefined variable). Maybe these lines should throw an exception instead?

**Comment by ADmad** [comment]
That "else" case you pointed out is interesting. I never knew fixtures were meant to use any prefix besides 'app', 'core', 'plugin'. I'll let someone who does know about it look into it :)

**Comment by ADmad** [comment]
`plugin.Gourmet\Faker.Articles` will work :) Found an example usage [here](https://github.com/FriendsOfCake/Authenticate/blob/cake3/tests/TestCase/Auth/MultiColumnAuthenticateTest.php#L19).  Though given that we use forward slash at all other places in plugin name it should be changed.

**Comment by jadb** [comment]
Thanks! This worked, but ya - some things need to be ironed out:

- the `else`: if to be supported then it's triggering an undefined variable.
- Gourmet/Email: why different notation than everywhere else.

**Comment by ADmad** [comment]
Would you like to submit a PR to fix the second point?  Should be an easy fix.

**Comment by markstory** [comment]
Closing as there is a pull request up.

**Comment by jadb** [comment]
@markstory PR only resolves the second point (Gourmet/Email instead of Gourmet\Email) but not the 1st point.

**Comment by markstory** [comment]
Ok, I can take care of handling the missing prefix case.

**Comment by markstory** [comment]
Closing as the remaining issue has a pull request now.
