### ISSUE TITLE
3.0 RC1 - Invalid dates changed 

### ISSUE THREAD

**Issue by rsflatt** [cakephp/cakephp#5581]
If a user enters an invalid date in a date field (eg 31 Feb), it correctly fails validation with rule:
      ->add('date_of_birth', 'valid', ['rule' => 'date'])

However, when the form is displayed again with the error, it has changed it to 3 March (or 2nd if it's a leap year). The object should contain the original, invalid date.

**Comment by dakota** [comment]
Closing as PR is open.
