### ISSUE TITLE
ACO/ARO nodes are saved always even if nothing changed

### ISSUE THREAD

**Issue by dcaravana** [cakephp/cakephp#5592]
This is more a question than a bug: why `AclBehavior::afterSave()` always saves ACO/ARO nodes even they didn't change?

Since it reads the nodes from db before saving, it would be easy to check if something changed and then decide if to save or not (saving a write-to-db call), but we would like to hear from you if this wasn't done on purpose.

**Comment by dcaravana** [comment]
I thought the same but I wanted to double check with you.

I could be working on it in the next days or so, in case I'll make a pull request, but basically could be a matter of comparing in-memory ACO/ARO data with conterparts freshly read from db.

All this comes from our research to reproduce a weird and rare bug (sometimes a variable number of ACO/ARO records are eaten away basically breaking record authorization) so lowering the number of db writes will lower also the number of write locks on the table and so lower the possibility of transactions broken cause of write locks (which seems to be the root of the problem).

**Comment by markstory** [comment]
Are you by any chance using myisam tables?

**Comment by dcaravana** [comment]
No we aren't, we're using InnoDB type.

**Comment by markstory** [comment]
Ok, MyISAM has horrific locking problems. :)

**Comment by tanuck** [comment]
Could you just revert `afterSave` to saving ARO/ACO nodes only when a record is created?

**Comment by dcaravana** [comment]
I've got the same idea, but I think it could not be generic enough, because `parent_id` could change (example: a user is moved from the "users" group to the "administrators" group).

As an alternative, a new save-only-on-create mode could be introduced for the entire ACL system that will save lots of db calls (reads and writes) and, if one has to change a node ACO/ARO, it could code it using directly the associated node calls, but this would impact the simplicity of the system a bit.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
