### ISSUE TITLE
Add /plugins/* to gitignore

### ISSUE THREAD

**Issue by DSchalla** [cakephp/cakephp#5596]
When using your CakePHP root as installation as git repository, it might lead to issues that the /plugins folder by default is not in the .gitignore, since the most addons are managed by composer. I talked with @jadb yesterday in IRC after having some errors with pushing after using composer update because of the missing line.

Might it be an idea to make a separate folder inside src, like src/Plugins/ to manage custom plugins which are not managed by composer and /plugins for Plugins which are managed by composer to avoid the trouble or is it recommended to add every composer managed plugin in the .gitignore?

**Comment by jadb** [comment]
My suggestion is not for cakephp/cakephp - it was for cakephp/app.

```
// should be ignored (for composer packages)
plugins/*
vendor/*
```

and 

```
// should be added for local plugins 
// (of course, in config/app.php the path should also be defined)
src/Plugin/
```

**Comment by DSchalla** [comment]
Sorry, I might have mixed up the Github Structure of the Project.
