### ISSUE TITLE
3.0 - Wrong release tag in readme

### ISSUE THREAD

**Issue by antograssiot** [cakephp/cakephp#5598]
![image](https://cloud.githubusercontent.com/assets/4977112/5650634/6098702e-96a0-11e4-832d-bfd7ac19d334.png)

I just figure that the badges in the README for cake 3.0.0-rc1 are wrong.
It's not a big issue but it can totally confuse people as 3.0.0-rc1 is promoted and 3.0.0-dev3 was 6 month ago.

**Comment by dereuromark** [comment]
`dev3` was 17 Nov 2014 actually :) So only a few weeks.
But yeah, it should be changed. Looks more like an issue with that img badge lib to me, though.

**Comment by antograssiot** [comment]
@bcrowe was it working before RC1 when you did update badges ?

**Comment by bcrowe** [comment]
@antograssiot I forget what the situation was before. But that's pretty odd that it's stuck back to dev3, not sure why. I've never had problems w/ shields.io before.

**Comment by dereuromark** [comment]
Is it possible that it has to do with the branch aliases in the composer file? Looking at other ones [here](https://github.com/laravel/framework/blob/master/composer.json#L92) or [here](https://github.com/symfony/symfony/blob/master/composer.json#L90) they do that and then the badges seem to work here:
[![Latest Unstable Version](https://poser.pugx.org/laravel/framework/v/unstable.svg)](https://packagist.org/packages/laravel/framework) / [![Latest Unstable Version](https://poser.pugx.org/symfony/symfony/v/unstable.svg)](https://packagist.org/packages/symfony/symfony)
But then again they use a different branching system alltogether (master branch being the dev branch so to speak).

**Comment by ADmad** [comment]
It's still showing "v3.0.0-dev3". I would suggest just removing that badge since it doesn't seem there's anything we can do to fix it.

**Comment by antograssiot** [comment]
a PR is opened to remove this badge.
I'll open an issue to shield.io to see if they have an expalaination, we can still try after the next tag
