### ISSUE TITLE
Security.salt and Security.cipherSeed, Why ? and for what ?

### ISSUE THREAD

**Issue by Boussarhane** [cakephp/cakephp#5599]
Hello,
I started using CakePHP today :) and i really didn't find an answer for my questions.
What Security.salt and Security.cipherSeed are ?
Where/when/for what Security.salt and Security.cipherSeed are used ?

Thanks.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by Boussarhane** [comment]
I'm really sorry.
thanks
