### ISSUE TITLE
TranslateTrait not found

### ISSUE THREAD

**Issue by neoPix** [cakephp/cakephp#5600]
I got the following error since the last composer update i've done :
Trait 'Cake\Model\Behavior\Translate\TranslateTrait' not found 

I'm using it as follow :

````php
<?php
namespace App\Model\Entity;
use Cake\Model\Behavior\Translate\TranslateTrait;
use Cake\ORM\Entity;

// ...

class Category extends Entity {
	use TranslateTrait;

// ...
````

using php 5.5.9

**Comment by ADmad** [comment]
The trait has now been moved to namespace `Cake\ORM\Behavior\Translate\`.

**Comment by neoPix** [comment]
Ok, thanks :+1: .
Not documented yet.
