### ISSUE TITLE
mapReduce not working in association with custom finder

### ISSUE THREAD

**Issue by mchiron** [cakephp/cakephp#5601]
Got a little problem with custom finder in the belongsTo association. Here an example of what I try to make: 
A House as a Client who as Datas.
Houses belongsTo Clients With finder => "datas"
Clients hasMany Datas
Datas belongsTo Fields

I then do something like:
Houses - contain('Clients')

For the function findDatas(...) in Clients, I set a contain Datas => ['Fields'] and a mapReduce with only a mapper. This mapper is not called.

**Comment by lorenzo** [comment]
Can you show the code you are using and the results you are getting?

**Comment by mchiron** [comment]
Not the exact code but close to what I have.

```
// Controller Houses action view
$house = $this->Houses->find()
    ->contain(["Clients"])
    ->where(['Houses.id' => $id])
    ->first();

// HousesTable associations
$this->belongsTo('Clients', [
    "finder" => "datas"
]);

// CustomFinder
public function findDatas($query, array $options)
{
    // I know that I get here
    $mapper = function ($data, $key, $mapReduce) {
        // Doing a die here would do nothing since this is never called.
        // Doing something with the data that should never be talked about.
        $mapReduce->emit($data);
    };
    $query->contain(['Datas' => ['Fields']]);
    $query->mapReduce($mapper);
    return $query;
}
```

The problem is not really with the data, I get back everything that I need including the Datas and Fields, but the mapper is not used and so my datas are not formatted as I need them to be.

**Comment by lorenzo** [comment]
Yeah, mapReduce can only be used in the main query, not in the associations. The reason is that mapReduce is usually for heavily modifying the results structure, whereas the original structure is required for matching the associations with the results in the main query.

Instead, please use `formatResults` which is a friendlier method if you just instead to use `map`. For example:

```php
$query->formatResults(function ($results) {
    return $results->map(function ($row) {
        // ... modify your row here ...
    });
});
```

**Comment by lorenzo** [comment]
An alternative, would be to set the contain to use the `select` strategy for that association. But you will need to take special care of not altering the structure so heavily that results could not be mapped

**Comment by mchiron** [comment]
I converted to a formatResults, this is gonna work for me.

We should reflect the inability to use mapReduce in a association custom finder in the documentation http://book.cakephp.org/3.0/en/orm/associations.html#default-association-conditions

**Comment by lorenzo** [comment]
@mchiron are you be willing to contribute the changes in the docs?

**Comment by mchiron** [comment]
I would, but I am not sure what the current documentation is trying to say on this.
"Only the following aspects of the query will be applied to the root query:"
Is it the root query or the association query that this is referring to?

**Comment by markstory** [comment]
'The query' in this situation is the association query.

**Comment by markstory** [comment]
Pull request for the docs is up now.

**Comment by dnypinkesh** [comment]
how can be use in controller??

// CustomFinder
    public function findDatas($query, array $options)
    {
        // I know that I get here
        $mapper = function ($data, $key, $mapReduce) {
            // Doing a die here would do nothing since this is never called.
            // Doing something with the data that should never be talked about.
            $mapReduce->emit($data);
        };
        $query->contain(['Datas' => ['Fields']]);
        $query->mapReduce($mapper);
        return $query;
    }
