### ISSUE TITLE
Config file issue with template file

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#5605]
Commit 470a649cd330e383c48fad3bdea877d10056a984 produces this error for me:

> Error: The application is trying to load a file from the app_form plugin.
> Make sure your plugin app_form is in the /../app/plugins/ directory and was loaded.

The app_form isn't a plugin, it's a file in config/app_form.php, but it's only used in AppController to load new templates in FormHelper as suggested in the book.

By the backtrace it seems like the problem happens before reaching the code app.

**Comment by ADmad** [comment]
Specify your custom template as `'template' => 'app_form'` without `.php` extension. The docs will be updated shortly.

**Comment by berarma** [comment]
Good, it's working again.
