### ISSUE TITLE
FormHelper does not get validation errors from the new Form object

### ISSUE THREAD

**Issue by andrecavallari** [cakephp/cakephp#5606]
I am creating a contact form with the new Form object, using the ContactForm extends Form, and i´ve created some validations. The validations work fine, but if I try to get the validation errors using:

$this->Form->isFieldError('field') returns always false (no error)
$this->Form->error('field') doesnt return the validation error

The validation erros are shown correctly, just these two functions doesnt work with Form object, but works with Entity

**Comment by lorenzo** [comment]
Can you show the code you are using? Show the form object, your controller and the view

**Comment by andrecavallari** [comment]
Sure...
https://gist.github.com/andrecavallari/290364e758bb7077483b

**Comment by markstory** [comment]
I can take a look, I remember seeing errors at some point when building the Forms out.

**Comment by andrecavallari** [comment]
When I use the $this->Form->input('field') it shows the error, but $this->Form->isFieldError or $this->Form->error doesnt catch the error. I´ve tryed to fix it by myself, but didnt work.

**Comment by markstory** [comment]
Interesting as input() just uses those methods under the hood.

**Comment by markstory** [comment]
I wasn't able to reproduce this, and everything worked as expected. This [gist](https://gist.github.com/markstory/2da2042a5e487ee110c1) has the working code I used.

**Comment by andrecavallari** [comment]
very curious, this was exactly the code I had before, but now i´ve changed it to get this working, but thanks anyway.
