### ISSUE TITLE
Fatal error after composer update 1/8/2015

### ISSUE THREAD

**Issue by isaacaskew** [cakephp/cakephp#5609]
Fatal error: Uncaught exception 'Cake\Core\Exception\MissingPluginException' with message 'Plugin userConfig could not be found.' in C:\xampp\htdocs\example\vendor\cakephp\cakephp\src\Core\Plugin.php:260 Stack trace: #0 C:\xampp\htdocs\example\vendor\cakephp\cakephp\src\Core\Configure\FileConfigTrait.php(51): Cake\Core\Plugin::configPath('userConfig') #1 C:\xampp\htdocs\example\vendor\cakephp\cakephp\src\Core\Configure\Engine\PhpConfig.php(68): Cake\Core\Configure\Engine\PhpConfig->_getFilePath('userConfig.php', true) #2 C:\xampp\htdocs\example\vendor\cakephp\cakephp\src\Core\Configure.php(262): Cake\Core\Configure\Engine\PhpConfig->read('userConfig.php') #3 C:\xampp\htdocs\example\config\bootstrap.php(76): Cake\Core\Configure::load('userConfig.php', 'default') #4 C:\xampp\htdocs\example\webroot\index.php(27): require('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\example\vendor\cakephp\cakephp\src\Core\Plugin.php on line 260

This happens on any config file that's loaded on the site. Is it trying to read this as a plugin?

**Comment by antograssiot** [comment]
Quite likely to be linked to #5564 .
Remove the `.php` from the configuration file name

**Comment by dereuromark** [comment]
Or linked to https://github.com/cakephp/cakephp/issues/5605
Closing as for the mentioned solutiones here and there.

**Comment by isaacaskew** [comment]
That was it; removed .php and it worked.
