### ISSUE TITLE
CakeTime tests are failing when PHP's locale is not en_US

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#5612]
For my app I've changed a time locale to russian (`setlocale(LC_TIME, 'ru_RU.utf8');`) in `Config/bootstrap.php` and now CakeTime are failing.

I suggest adding a locale reset to the setUp() method of CakeTimeTests class.

**Comment by lorenzo** [comment]
That is normal. Tests are designed to run under a certain configuration and also configuration is changed during the tests to cover more cases. Closing this as this is not an actual problem. Thanks anyway!
