### ISSUE TITLE
Behaviors not available when using TableRegistry

### ISSUE THREAD

**Issue by vonboth** [cakephp/cakephp#5618]
I try to use the Tree-Behavior for a model. It works fine, when using it in the 'normal' Controller.
E.g. MenusController, MenusTable.
When instantiating the model this way: $this->Menus one can use the tree behavior.

If one tries to instantiate the model in another controller in the suggested ways: loadModel('Menus') or TableRegistry::get('Menus') the behavior is not available.

If one instantiates the model with 'new Menus()' the model contains the behaviors but the connection array is empty

**Comment by ADmad** [comment]
Is you model in a plugin?

**Comment by vonboth** [comment]
Hi ADmad. Yes it is

**Comment by vonboth** [comment]
Hi ADmad. Yes it is

**Comment by ADmad** [comment]
Then you need to use the plugin name prefix like  loadModel('MyPlugin.Menus') or TableRegistry::get('MyPlugin.Menus')  even the controller you are calling from is within same plugin.

**Comment by vonboth** [comment]
Thanks ADmad = Hero!
