### ISSUE TITLE
Restore before/aftervalidate events

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5622]
Sometimes you need to modify the raw request data before validating or marshalling.
There could be two simple events.
One to modify i.e. request->data before validating when calling ->newEntity or ->patchEntity
And one for do post processing 
These events wouldn't break anything.
Shall I implement it?

**Comment by dereuromark** [comment]
Those would then basically correspond to the 2.x `beforeValidate/afterValidate`, if I understand you correctly? Whereas the 3.x `beforeRules/afterRules` now more address the save itself only.

**Comment by mdlouhy** [comment]
Correct! Some things could be solved later in beforeRules but not all of it.
Those two events wouldn't hurt anyone :P

**Comment by lorenzo** [comment]
I would like to understand your case before taking any action. Most of the times it can be solved with the tools we already have in a clean way

**Comment by mdlouhy** [comment]
You are right. "most" of the time. Like a mentioned above. There may be some use cases where it would be easier using these events than finding other ways. For example I want to change request data before validating in some cases (or removing/adding).
I could do it in the controller too or even create own events for this.
Like mentioned above - these two events wouldn't break anything or hurt anyone :P 
It just may make the love in some (maybe yet unknown) cases easier.

**Comment by markstory** [comment]
While more events don't break anything, they do add complexity and maintenance costs. If the current buildValidator event also got the data being validated wouldn't you be able to use that for the example case?

I think having a few good use cases is important before we go and add features. There are endless features we could add, but many we should not. The tricky part is finding a balance.

**Comment by mdlouhy** [comment]
buildValidator has the problem that it is only called once.
when calling ->newEntity and then ->patchEntity, then buildValidator is not called twice because there is a static cache that avoids building the validator multiple times.

**Comment by mdlouhy** [comment]
I now implemented it for MY needs. (only beforeValidate)

Table.php
```
    public function implementedEvents()
    {
        $events = parent::implementedEvents();
        $eventMap = [
            'Model.beforeValidate' => 'beforeValidate',
        ];
        foreach ($eventMap as $event => $method) {
            if (!method_exists($this, $method)) {
                continue;
            }
            $events[$event] = $method;
        }
        return $events;
    }

    public function marshaller()
    {
        return new Marshaller($this);
    }

    /**
     * @param Event $event
     * @param array $data
     * @param bool $isNew
     * @return void
     */
    public function beforeValidate(Event $event, $data = [], $isNew = false)
    {
        // i.e. change data before marshalling and before validating
        // $event->data['data']['test'] = 4;
    }
```

Marshaller.php
```
namespace App\ORM;

class Marshaller extends \Cake\ORM\Marshaller
{
    protected function _validate($data, $options, $isNew)
    {
        if ($options['validate']) {
            $event = $this->_table->dispatchEvent('Model.beforeValidate', compact('data', 'isNew'));
            $data = $event->data;
        }
        return parent::_validate($data, $options, $isNew);
    }
}
```

it seems really easy to implement such requirements therefore I suggest to close this issue. (Although I still think "it wouldn't hurt to be in the cake core" :P)

**Comment by hdogan** [comment]
@mdlouhy how about pluginize your implementation? So we can use mdlouhy\ORM\Table and mdlouhy\ORM\Marshaller if we need (before|after)Validate events working like 2.x :)

**Comment by mdlouhy** [comment]
this wouldn't restore the behavior of 2.x - I think that the requirements differ too much therefore everyone who needs it should restore a "slim" version for themselves.
Most things can be replaced by "rules" or "conditional validation" or different validators.

**Comment by markstory** [comment]
Not caching validators could be a possibility. I suspect it will degrade performance a bit as validators will be built multiple times per request.

**Comment by lorenzo** [comment]
I still think there are enough tools to accommodate the use cases that have been presented to us. There seems to be a pattern, though, that we have not covered and people keep asking for it. That is the ability to modify the request data before it is marshalled.

Maybe a goal for 3.1?

**Comment by markstory** [comment]
@lorenzo But you can easily modify the request data before marshalling by implementing methods on your table classes.

```php
$data = $this->Articles->mangleData($this->request->data);
$article = $this->Articles->newEntity($data);
```

I don't think the proposed beforeValidate hook would really provide the ability to modify request data before it was marshalled/validated as things stand.

**Comment by dereuromark** [comment]
@markstory The use case here is mainly for behaviors that want/need to hook into here. Those cannot just declare methods on the table class after all.

**Comment by markstory** [comment]
But there exists a `buildValidator` event that behaviors can use to define validation rules. However, as @mdlouhy pointed out they don't have access to the request data and cannot add different validation rules based on the contents of the request.

**Comment by dakota** [comment]
Perhaps what is needed here is a `beforeMarshall` event?

**Comment by dereuromark** [comment]
:+1: to that @dakota

**Comment by robertpustulka** [comment]
@dakota, what kind of data should `beforeMarshall` use? `$data` and `$options` passed to `Marshaller:one()`? How should listeners modify this data? Perhaps in `$event->result`?

Just before validating:
```php
$event = $this->_table->dispatchEvent('Model.beforeMarshall', compact('data', 'options'));
if (is_array($event->result)) {
    $data = $event->result;
}
```

What about failures?

**Comment by lorenzo** [comment]
Closing as there is a candidate pull request
