### ISSUE TITLE
Plugin app could not be found.

### ISSUE THREAD

**Issue by mchiron** [cakephp/cakephp#5624]
Just did a composer update, now I got this error.
Plugin app could not be found.

Any idea or instruction on how to correct this?

**Comment by ADmad** [comment]
Make sure the [Configure::load()](https://github.com/cakephp/app/blob/master/config/bootstrap.php#L66) statement in your bootstrap specifies the key as `app` not `app.php`.

**Comment by mchiron** [comment]
Solved it. Thank you.

**Comment by pranav887** [comment]
pl['pl'

**Comment by pranav887** [comment]
Config file "app.php" did not return an array
