### ISSUE TITLE
3.0 - Question - Contain filtering through find and get

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#5625]
I had tried the following approach, but it only worked through find:

https://gist.github.com/andtxr/7c3cb3b65d8ad39c1242

Shouldn't the get method nesting contain method?

**Comment by lorenzo** [comment]
`get()` returns the found entity. Please refer to the manual for more information on how to use `get` `find` and `firstOrFail`. In the future, please use the official support channels for asking questions as this is just an issue tracker.

**Comment by andtxr** [comment]
I was just thinking about the method nesting. It would be beautiful filter associations from get(). Thanks! :+1:

**Comment by lorenzo** [comment]
You actually can, using the second parameter of `get()` which is an array of options for the query, including `contain`
