### ISSUE TITLE
3.0 - Leaking finder options

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5626]
It's possible this is as intended, but right now if you do this, `findDrafts` will get the (mutable) options from `findPublished`
```
$this->Posts->find('published', ['id' => 10])->find('drafts');
public function findDrafts(Query $query, array $options) {
	// $options = ['id' => 10]
	return $query;
}
```
```
$this->Posts->find('published', ['id' => 10])->find('drafts', ['id' => 55]);
public function findDrafts(Query $query, array $options) {
	// $options = ['id' => 55]
	return $query;
}
```

To me, it seems like the `$options` in `findDrafts` should be an empty array in that first example. If it's a bug let me know and I'll try to track it down.

Thanks

**Comment by markstory** [comment]
Finders are supposed to get the options. While the arrays are mutable, the changes shouldn't propagate to the original query.

**Comment by lorenzo** [comment]
Actually that is a feature that is working as intended. Options will persist from finder to finder, this is important as some of the options can be (and are) used by multiple finders at the same time.

**Comment by patrickconroy** [comment]
Thanks guys.
