### ISSUE TITLE
3.0 UrlHelper -  build method is returning a escaped url

### ISSUE THREAD

**Issue by golgher** [cakephp/cakephp#5630]
UrlHelper is escaping html when build an url. 
Example:
```
echo $this->Url->build(array('action'=>'some_action','param1'=>1,'param2'=>'teste'));
```
Url expected:
/admin/users/add?param1=1**&**param2=teste
Url returned:
/admin/users/add?param1=1**\&amp;**param2=teste

In my application was easy to fix this error using html_entity_decode, but the build method must return a unescaped url, or at least a possibility of configure the escape option.

**Comment by markstory** [comment]
Why? UrlHelper is for use in HTML. HTML requires `&` to be encoded.

**Comment by golgher** [comment]
Sorry and thanks for the explanation. I will use Router::url

**Comment by markstory** [comment]
Cool, that was going to be my recommendation as well :smile:
