### ISSUE TITLE
2.x - Use ob_end_clean() on error

### ISSUE THREAD

**Issue by Adnan0703** [cakephp/cakephp#5632]
defaultLayout.ctp

```<html>
<html>
<head>
</head>
<body>
<div id="container"> 
	<h1> default_layout </h1>
	<?php echo $this->SomeHelper->doSometing(); ?>
</div>
</body>
</html>
```

errorLayout.ctp

```<html>
<head>
</head>
<body>
<div id="container"> 
	<h1> error_layout </h1>
</div>
</body>
</html>
```
If I do not add “SomeHelper” in the controller’s helpers and I use “SomeHelper” in the defaultLayout file, I get MissingHelperException as I should. But the layout of the page will be broken.
Here’s what you’ll get if you reproduce it.

```<html>
<head>
</head>
<body>
	<div id="container"> 
		<h1> default_layout </h1>
<html>
<head>
</head>
<body>
	<div id="container"> 
		<h1> default_layout </h1>
<html>
<head>
</head>
<body>
	<div id="container"> 
		<h1> error_layout </h1>
	</div>
</body>
</html>
```

And if I change the layout to “errorLayout” in MyExceptionRenderer like this.

 ```
protected function _outputMessage($template) {
		$this->controller->layout = 'errorLayout';
		parent::_outputMessage($template);
	}
```
I get this html.
```
<html>
<head>
</head>
<body>
	<div id="container"> 
		<h1> default_layout </h1>
<html>
<head>
</head>
<body>
	<div id="container"> 
		<h1> error_layout </h1>
	</div>
</body>
</html>
```

So, I get (last buffered layout content before error) + (current content).
It is because of `ob_start()` that gets called in `View::_evaluate()`.
I think there should be a try > catch > ob_end_clean() > throw again, or `ob_end_clean()` in ExceptionRenderer.

**Comment by markstory** [comment]
I took a brief look at this and I wasn't able to find a good solution that didn't also break the test suite. Perhaps someone else will have better luck with this than I did.

**Comment by Adnan0703** [comment]
mark, can you suggest any temporary solution until good solution or I should just leave it as it is?

**Comment by markstory** [comment]
Fix the code causing the helper error :smile:?

**Comment by Adnan0703** [comment]
already did that :smile:
