### ISSUE TITLE
Email issues in rediffmail

### ISSUE THREAD

**Issue by shidhu40** [cakephp/cakephp#5642]
Hi,

When I send mail to rediffmail account by html format. It will shows the format type in body .

I have done following coding.

 $email = new CakeEmail('smtp');
			$email->to(''shidhu047@rediffmail.com);
			$email->subject('Password Recovery');
			$email->from(array('shidhu047@gmail.com'=>'No Reply'));
			$email->replyTo('shidhu047@gmail.com');
			$email->emailFormat('both');
			$email->template('recover');
            
            $email->send(); 

This is the result.
![email issues](https://cloud.githubusercontent.com/assets/7380722/5699892/81b5b0e4-9a58-11e4-8c6b-af31b82e9cff.png)

**Comment by markstory** [comment]
If you view the raw email contents is that text there? I don't think that cakephp is including the template type as it doesn't happen in the test cases.

**Comment by shidhu40** [comment]
If I want to use html email template. How can I resolve this .

**Comment by markstory** [comment]
Is Emails/html in your template or layout?

**Comment by shidhu40** [comment]
I have put recovery template .
I have make template inside html Email
I have put the template in app > view > email > html.

**Comment by rchavik** [comment]
I think this is more of a "How to use" problem and not an actual bug.

**Comment by shidhu40** [comment]
It only appears in rediffmail body not in other account such as yahoo, gmail.

**Comment by rchavik** [comment]
Interesting.

If provide the raw contents of the email as requested, it may shed a light on the issue.

**Comment by shidhu40** [comment]
I have done above coding & use the html template.

**Comment by josegonzalez** [comment]
@shidhu40 can you provide the raw html contents from your email client?

**Comment by markstory** [comment]
The raw message body would actually be more useful.

**Comment by shidhu40** [comment]
<p>Dear <?php echo $User['firstname'] ?>,</p>
<p>Your account has been successfully created.</p>
<p>  To confirm your email address please click on the following link:</p>
<p><a href="<?php echo Router::url(array('controller' => 'users', 'action' => 'verifyEmail',$User['email_activation_token']), true); ?>">Activate your account</a></p>


I have use this in html templates

**Comment by rchavik** [comment]
That's not the raw message body.   I think what mark wants is something like:

- https://support.google.com/groups/answer/75960?hl=en
- http://www.electrictoolbox.com/gmail-view-raw-email-message/

You'd need to find the equivalent way to do that in rediffmail.

**Comment by shidhu40** [comment]
Return-Path: <bounce+ca863c.5d77b-shidhu047=rediffmail.com@mg.valuehire.com>
Delivered-To: shidhu047@f5.p28.mail.in.rediffmail.com
Received: (qmail 12180 invoked from network); 9 Jan 2015 06:56:07 -0000
X-IN-CTCH-Spam: Suspect
X-IN-CTCH-VOD: Unknown
X-IN-CTCH-Flags: : 0
X-IN-CTCH-RefID: str=0001.0A150207.54AF7B87.03ED,ss=2,re=2.200,recu=0.000,reip=0.000,cl=2,cld=1,fgs=0
X-REDIFF-SENDER-VERIFY: D=1, P=D
Received: from rs250.mailgun.us (209.61.151.250)
by 0 with SMTP; 9 Jan 2015 06:56:07 -0000
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=mg.valuehire.com; q=dns/txt;
s=pic; t=1420786562; h=Sender: Content-Transfer-Encoding: Content-Type:
Mime-Version: Subject: Message-Id: Date: To: Reply-To: From;
bh=7nuPQ9/jOXSDMmJSO8LPlTWcxhnDOmU2eQoHCsaDaI4=; b=jLhN9MTkjjcIjXDGt1eIbYUSbtHieyTOLdItOdxrIsu8mUC/FO0hATliX4XvRyJLx39jNLV3
azJZpPzQX6bx3dPJweyz8mLtUY7GfsxU2qWJW9XePMuGKJIEoi8f7vp3bLG61Gz+NSAaapzz
/9yHlWNzdT81Ph6Yhii+nA5YXLw=
DomainKey-Signature: a=rsa-sha1; c=nofws; d=mg.valuehire.com; s=pic;
q=dns; h=From: Reply-To: To: Date: Message-Id: Subject: Mime-Version:
Content-Type: Content-Transfer-Encoding: Sender;
b=bs3cfuLG9E9ECPYG3FrO1+8UkVcvGVKlVWJWOMeoLEfbEjP4FCot0LY1Pf05ZzHc1bjKST
CHkC7Q4oUuY/d5ACQAnR3JpnTzXDBDTOPm+eSePTghVAx9md2G290JhFKoMcmPdHA5V0wAAy
ur2BoTRCMpHkaFdDKdMdK6UZIvFOU=
Received: from localhost
(abts-north-dynamic-134.224.69.182.airtelbroadband.in [182.69.224.134]) by
mxa.mailgun.org with ESMTP id 54af7b6e.7fa2e9d7a3f0-in7; Fri, 09 Jan 2015
06:55:42 -0000 (UTC)
From: Valuehire <resumes@valuehire.com>
Reply-To: resumes@valuehire.com
To: shidhu047@rediffmail.com
X-Mailer: CakePHP Email
Date: Fri, 09 Jan 2015 06:55:50 +0000
Message-Id: <54af7b76cc404a7685290e300f724e6d@localhost>
Subject: Valuehire Resume Builder - Account Activation
Mime-Version: 1.0
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit
X-Mailgun-Sid: WyI5Njg3ZCIsICJzaGlkaHUwNDdAcmVkaWZmbWFpbC5jb20iLCAiNWQ3N2IiXQ==
Sender: resumes=valuehire.com@mg.valuehire.com

**Comment by AD7six** [comment]
The encoded message body is missing.

[this is an example of a raw email](https://gist.github.com/AD7six/2d2bbae2b7dac36a22e3) and [this is what we're waiting for](https://gist.github.com/AD7six/2d2bbae2b7dac36a22e3#file-gistfile1-txt-L94-L300).

**Comment by shidhu40** [comment]
Delivered-To: sudhir@gmail.com
Received: by 10.60.92.101 with SMTP id cl5csp1127546oeb;
        Mon, 12 Jan 2015 02:21:21 -0800 (PST)
X-Received: by 10.182.153.133 with SMTP id vg5mr16933036obb.20.1421058081016;
        Mon, 12 Jan 2015 02:21:21 -0800 (PST)
Return-Path: <bounce+5cc025.5d77b-sudhir=gmail.com@mg.gmail.com>
Received: from rs250.mailgun.us (rs250.mailgun.us. [209.61.151.250])
        by mx.google.com with ESMTPS id r11si9630251oif.29.2015.01.12.02.21.20
        for <sudhir@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Mon, 12 Jan 2015 02:21:20 -0800 (PST)
Received-SPF: pass (google.com: domain of bounce+5cc025.5d77b-sudhir=gmail.com@mg.gmail.com designates 209.61.151.250 as permitted sender) client-ip=209.61.151.250;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of bounce+5cc025.5d77b-sudhir=gmail.com@mg.gmail.com designates 209.61.151.250 as permitted sender) smtp.mail=bounce+5cc025.5d77b-sudhir=gmail.com@mg.gmail.com;
       dkim=pass header.i=@mg.gmail.com
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=mg.gmail.com; q=dns/txt;
 s=pic; t=1421058080; h=Sender: Content-Transfer-Encoding: Content-Type:
 Mime-Version: Subject: Message-Id: Date: To: Reply-To: From;
 bh=AGz/cJYv9Qr9G+ETlZyUU0wlRYjTtQSMmByvj6aToBQ=; b=oEkwxcHUNjj3L79Ugd2J1v39rMAplDgTGJ6e6E0aCWhOdZkEOw7cYgQhx32aOJ7n7nDLHsnA
 KRtplvhuhCe2PlPstf4APcLpJsp1nN+PW9aNmjCMrclEMrIFk5D1jLmpj741q71w3PtMT8xe
 wNg96ojScRBgBjU+4K/E9SP0n/4=
DomainKey-Signature: a=rsa-sha1; c=nofws; d=mg.gmail.com; s=pic;
 q=dns; h=From: Reply-To: To: Date: Message-Id: Subject: Mime-Version:
 Content-Type: Content-Transfer-Encoding: Sender;
 b=hSzI9qHEzoAMkRU1KM0oo5BGPHa3FnG3Jjm246hMdT403V+VGU/HigClC8V1spATW3m9GX
 skab3ao85cRBzLQ6Gj/j4JvfmNwr76hcE1QTQuSYqYvOrFtIpAlPoV9OQV6Tdoi9Et6xNSoe
 nxo1n8ZxholrXm5tkn+i1dntTEPV0=
Received: from localhost
 (abts-north-dynamic-055.227.69.182.airtelbroadband.in [182.69.227.55]) by
 mxa.mailgun.org with ESMTP id 54b3a01f.62e9bd0-in7; Mon, 12 Jan 2015
 10:21:19 -0000 (UTC)
From: Sudhir <resumes@gmail.com>
Reply-To: resumes@gmail.com
To: sudhir@gmail.com
X-Mailer: CakePHP Email
Date: Mon, 12 Jan 2015 10:21:19 +0000
Message-Id: <54b3a01fe82045ac81610e640f724e6d@localhost>
Subject: Sudhir Resume Builder - Account Activation
Mime-Version: 1.0
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 8bit
X-Mailgun-Sid: WyJjODlmNSIsICJzdWRoaXJAdmFsdWVoaXJlLmNvbSIsICI1ZDc3YiJd
Sender: resumes=gmail.com@mg.gmail.com

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
	<title>Emails\html</title>
</head>
<body>
	<p>Dear Sudhir,</p>
<p>  To confirm your email address please click on the following link:</p>
<p><a href="http://localhost/prodvcv/users/verifyEmail/597f6dad0da7f95a19cb3caa930e2cb6a79226df3dcde0e288f37bee0160a331">Activate your account</a></p>


<p>Regards,<br/>
Sudhir</p>
</body>
</html>

**Comment by dakota** [comment]
I see you've got your template already here. Can you add in your email layout (View/Layouts/Emails)?

**Comment by dereuromark** [comment]
@shidhu40 I updated your post with fences. Please use those to display code (and prevent it from rendering as HTML or something else).

**Comment by lorenzo** [comment]
In your template you have this:

```html
 <title>Emails\html</title>
```

Remove that tag as you don't need it to be displayed in that email client. You can also set a proper title tag if you wish.
