### ISSUE TITLE
2.x: RFC Improve prefix (for caches etc)

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#5645]
I think I ran into a real issue lately. I have been running multiple instances of an app modified in some ways, equal in others on the same webserver in different path's and on different domains.

I was getting strange log errors that appA was reading/writing (pdfs) in appB's folders and other way around. Then things only errored "sometimes" but most of the time were fine. One of the apps was in production the other in development. It seems that whenever the "development" appB created cache files and the production appA read them things got really hairy. I was also using the same cipherSeed which I should not have (but I am not sure if it would have made any difference).

Therefor I suggest that: https://github.com/cakephp/cakephp/blob/master/app/Config/core.php#L362 should better be:
```php
$prefix = Inflector::slug(APP); // where APP is the absolute path to your application
```

**Comment by ADmad** [comment]
Closing as related PR is also closed.
