### ISSUE TITLE
Folder creation with relative path does not work with 2.6.0

### ISSUE THREAD

**Issue by jeco123** [cakephp/cakephp#5646]
Hi All,

I've just updated from 2.5.4 to 2.6. Here is what i observe:

When i try to create a folder like the code below, the folder is not created where it is expected.
$dir = new Folder('root', true);
=>should be created to my WWW_ROOT folder. The root folder is created at the root of my disk F: (where apache and cakephp is intalled). This is a regression from 2.5.4.

by doing
$dir = new Folder(WWW_ROOT.DS.'root', true); it works.

**Comment by markstory** [comment]
The directory creation was recently changed in #4990 to fix other issues. Relying on cwd is not a good idea given that it can lead to non-deterministic results.

Personally I think being explicit as to where you want the directory created is a _good_ thing.
