### ISSUE TITLE
2.x - Problem saving correct value for set-field

### ISSUE THREAD

**Issue by codeworks** [cakephp/cakephp#5649]
I have a MySQL table with several fields, one of them has the type "set('1', '2', '3')". In order to update a row i would do something like:

$this->Example->save(array('id' => 123, 'my_field' => '3'), false);

Up to 2.5.5 this worked as expected and my_field had the value '3' after the update. Since 2.5.6 the value '3' passed to the save() method gets converted from string to integer during the save-operation, which results in the value '1,2' in the database.

Removing the 3 lines added to lib/Cake/Model/Datasource/Database/Mysql.php in this commit ( https://github.com/cakephp/cakephp/commit/579b16d90b45e9994ef4394bba391830791cc982 ) restores the old behavior, but maybe it's an issue worth discussing?

**Comment by markstory** [comment]
The change you're point out came from #4489, which shouldn't have modified how data is saved. Perhaps another change caused the issue?

**Comment by codeworks** [comment]
Made my way through the core now and actually it also effects saving data. In lib/Cake/Model/Datasource/DboSource.php there's a method **value($data, $column = null)**

Before the change pointed out was applied, the value of $column for set fields was 'text'. Now $column is "set('1', '2', '3')". So, at the end of the value() method, there's a switch statement, which makes the difference:

```
switch ($column) {
  [...]
  case 'string':
  case 'text':
    return $this->_connection->quote($data, PDO::PARAM_STR);
  default:
    [...]
    if ((is_int($data) || $data === '0') || (
      is_numeric($data) && strpos($data, ',') === false &&
      $data[0] != '0' && strpos($data, 'e') === false)
    ) {
      return $data;
    }
    return $this->_connection->quote($data);
}
```

When $column was 'text', $data got quotes. Now, as $data is numeric in my case (value is '3'), it gets returned without quotes, causing the unexpected behavior.

**Comment by markstory** [comment]
Pull request open now.
