### ISSUE TITLE
Setting response headers for a non GET request on a rest api

### ISSUE THREAD

**Issue by ruhley** [cakephp/cakephp#5655]
I am using CakePHP 3 RC 1 for a rest api. For non GET requests (PUT and POST confirmed) if I set a response header like

```php
$this->response->header('Access-Control-Allow-Origin', '*');
```
or 
```php
$this->response->header(['Access-Control-Allow-Origin' =>  '*']);
```

then it wouldn't actually send the header. However if I set it like the following then it would work.

```php
$this->response->header('Access-Control-Allow-Origin: *');
$this->response->header(['Access-Control-Allow-Origin: *']);
```

The documentation (http://api.cakephp.org/2.2/class-CakeResponse.html#_header) says you can use any of those formats

**Comment by bcrowe** [comment]
First, from your link to the docs, you are looking at the 2.2 docs, please make sure to refer to the 3.0 docs if you are working with 3.0 RC1. Second, I was able to get the headers from all 4 examples, for both POST and PUT requests. Could you possible provide some more context or the code you've written?

**Comment by markstory** [comment]
You won't see headers if you've already stated the output. Make sure you haven't done that.

**Comment by ruhley** [comment]
Inside of invokeAction I am calling this function (this is the working version). Maybe it only occures when setting the headers during invokeAction?

```php
        protected function preflight() {
			$headers = [
				'Access-Control-Allow-Origin: *',
				'Access-Control-Allow-Methods: GET, POST, PUT, DELETE',
				'Access-Control-Allow-Headers: Accept, Content-Type'
			];

			if ($this->request->is('options')) {
				header('HTTP/1.1 200 OK');

				foreach ($headers as $header) {
					header($header);
				}
				exit;
			}

			$this->controller->response->header($headers);
		}

```

**Comment by markstory** [comment]
The response object isn't really aware of where its methods are being called from, after setting the headers, can you read them back from the response?

**Comment by ruhley** [comment]
I am getting some weird stuff happening now. I will try to set up an example project with the error when I get some free time.

**Comment by markstory** [comment]
Ok.

**Comment by ruhley** [comment]
I found a stragling exit that only ran for POST and PUTS, sorry for the wasting your time.
