### ISSUE TITLE
3.0: Invalid URLs in requestAction() when using AJAX and redirects

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5661]
This bug only happens, when you have relative "localhost" setups:

    http://localhost/work/cake3app/controller/action...

Normally accessing an action is fine.
When AJAX requesting (e.g. a POST) an action that contains a redirect, the RequestHandler tries to prevent that redirect and uses requestAction() go retrieve the follow up content.
Here it breaks, as this method internally doesn't resolve the path to the application anymore, so the controller is suddenly "work":

    RequestHandlerComponent.php(302): Cake\Controller\Controller->requestAction('/work/cake3app/...', ...
    Error: [Cake\Routing\Exception\MissingControllerException] Controller class Work could not be found.

You can easily replicate this issue when trying to run [this](http://sandbox3.dereuromark.de/sandbox/ajax_examples/redirecting) in a localhost env.

**Comment by markstory** [comment]
Oh Requesthandler you so crazy.

**Comment by dereuromark** [comment]
Either we remove the URL part before the controller before passing it on, or that trait needs to be able to resolve both.

From looking into the code it seems that this is the part, where the URL is formed in the component:

    if (is_array($url)) {
        $url = Router::url($url + ['base' => false]);
    }

I wonder why some code has `base`, and others `_base` as key. Is that the route cause maybe?
