### ISSUE TITLE
Custom path to Plugin without trailing slash

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#5665]
Just recently I found something annoying: I had to specify a custom path to a Plugin: https://github.com/morrislaptop/AirbrakeCake/issues/7

The problem was that I did not add a trailing slash to the path specified to the `CakePlugin::load()` function. This causes the plugin to load fine, but a call to:
```php
App::uses('AirbrakeError', 'AirbrakeCake.Lib');
```
failed.

The path CakePHP constructed was something like: `/path/to/CakephpAirbrakeLib/AirbrakeError`.

Fix: Automatically add a trailing slash, if not already present.

**Comment by markstory** [comment]
We don't add trailing slashes to any other paths, why is this special?

**Comment by dereuromark** [comment]
@markstory afaik all paths have the trailing slash except for ROOT which is somewhat special. I wonder why this one dont then.

**Comment by davidsteinsland** [comment]
The problem/issue isn't that you have to add the trailing slash: the bug is that CakePHP doesn't check for this when loading files from the plugin, when it's as simple as:

```php
$path = rtrim($path, DS) . DS;
// or
$path = realpath($path) . DS;
```

**Comment by dereuromark** [comment]
@davidsteinsland It would be cleaner if CakePHP didn't have to check on that because they would always be trailing in the first place. Personally, I would rather find the root cause of this issue and fix it there.

**Comment by markstory** [comment]
@dereuromark What I meant was that all the user supplied paths don't get trailing slashes added to them either.

@davidsteinsland The framework expects that you put paths in correctly. I'm sure we could go around fixing paths, but I'm not sure the overhead is worth it when the solution is documented.

**Comment by dereuromark** [comment]
@markstory Now I understand. Yeah, the user needs to take care of that.

**Comment by davidsteinsland** [comment]
It should be clearly documented then, because I did not figure this thing out until I realized the plugin wasn't loaded.

There isn't a big difference in writing the path with/without a trailing slash, but when one of them leads to an error it's kinda confusing.

**Comment by dereuromark** [comment]
I agree.
Alternatively in debug mode it could check on a slash present and if not throw an exception.

**Comment by markstory** [comment]
Why? Documentation solves the problem I think.

**Comment by dereuromark** [comment]
@davidsteinsland Can you maybe make a docs PR with the suggested note?

**Comment by dereuromark** [comment]
I also just had the case that somewhere someone included App::build() additions with hardcoded / which lead to problems along the way on WIN os, for example.
But I think this could be solvable as user-land-implementation that only takes effect in debug mode (similar to DebugKit), so there is probably no need to act other than documentation.

**Comment by markstory** [comment]
API docs updated in 56143c663e14b810965da8146a9bde50ddf8b857
