### ISSUE TITLE
CakeSession::destroy() should check for existence of session

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#5666]
This is to prevent warnings saying:

```
PHP Warning: session_destroy(): Trying to destroy uninitialized session
```

One could handle it as:
```php
if (session_status() === PHP_SESSION_ACTIVE) {
    session_destroy();
} else {
    // one might also log to CakeLog or something here.
}

$_SESSION = null;
// etc.
```

`CakeSession::destroy()` tries to start a session if it isn't started, but it does not check if a session was actually started.

**Comment by dereuromark** [comment]
Closing as a PR is now open.

**Comment by davidsteinsland** [comment]
Is there a reason why this was added to 3.0 only?

**Comment by dereuromark** [comment]
You reported it for 3.0.
Is the same issue present in 2.x?

**Comment by davidsteinsland** [comment]
Did I? Hmm..

Anyways, yes: same case present in 2.x. Only problem is that `session_status()` function is new, so one would have to check for:

```php
if (session_id() === '') {
    // session not active
}
```

**Comment by dereuromark** [comment]
So please always specify the exact version you report it in :)
I could have guessed better, though, as "CakeSession" is 2.x specific.

**Comment by dereuromark** [comment]
Are you able to produce a PR for 2.x and note in there that it is a backport of the above linked 3.x one?

**Comment by dereuromark** [comment]
@davidsteinsland We are releasing 2.6.1 today or tomorrow at the latest, so it would be nice if that fix was in there, as well.

**Comment by davidsteinsland** [comment]
I'm working on the PR. Hold on tight. :+1:

**Comment by dereuromark** [comment]
:+1: Awesome.

**Comment by dereuromark** [comment]
Closing as PR for 2.x is now open as well: https://github.com/cakephp/cakephp/pull/5670
