### ISSUE TITLE
plugin-installer error

### ISSUE THREAD

**Issue by ea-liwei** [cakephp/cakephp#5669]
![20150115115151](https://cloud.githubusercontent.com/assets/6028737/5752285/586e014e-9cad-11e4-9436-c5cb3970d3c9.jpg)

**Comment by markstory** [comment]
Thanks, we'll get this fixed up soon. A mistake was made with the plugin installer. You can require `0.0.1` to restore the old behavior until this issue is fixed.

**Comment by simkimsia** [comment]
i had the same problems. was lead here by rchavik in irc.  how do we require 0.0.1 on the composer.json?

right now, my composer.json looks like this:
```
```

**Comment by dakota** [comment]
@simkimsia It should be fixed now that https://github.com/cakephp/plugin-installer/pull/5 has been merged.

**Comment by simkimsia** [comment]
@dakota ahhh... just when I figured out how to explicitly call 0.0.1 for plugin-installer. :)

Okay 0.0.2 works. :+1:

**Comment by dakota** [comment]
This has been corrected in the `0.0.3` tag.
