### ISSUE TITLE
3.0 - Plugins can't be loaded when using namespaces

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5671]
Since the new plugins-being-in-vendor mechanism was set in place, `Plugin::load` fails to respect namespaces.

This stopped working and needs to work again:
```
Plugin::load('Company/Plugin', ['bootstrap' => true]);
```

It works if you make the namespace separator a backslash:
```
Plugin::load('Company\Plugin', ['bootstrap' => true]);
```

Refs: https://github.com/cakephp/app/pull/206

**Comment by ADmad** [comment]
Closing as a PR to fix this is opened.
