### ISSUE TITLE
Empty List Bug

### ISSUE THREAD

**Issue by Minnifutzi** [cakephp/cakephp#5676]
Hello guys,
I got a problem with CakePHP and the method find('list').
Here are some pictures, which show you the case.
PIC1: http://i61.tinypic.com/ma9bmx.png
PIC2: http://i57.tinypic.com/157i4d2.png

In pic1.png the 2nd line, 'count_id' is a virtual Field.
I can't understand, why the output differs - is this a bug, or a feature. ;)
Also, i tried different things like COUNT(`Question`.`id`) - with aliases i.e., but nothing works.

Greatings from Germany

**Comment by lorenzo** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by lorenzo** [comment]
And yes, you need to use virtualFields for that find of stuff :)

**Comment by Minnifutzi** [comment]
That wasn't a help request - i just wanted to ask, if this is a bug or a feature. I have already solved it at this point. But Thanks

**Comment by AD7six** [comment]
@Minnifutzi for future reference pictures of text are no helpful - _just put the text_.  It's hard to read any of the text in your images because they are too small or obscured by spammy adverts.
