### ISSUE TITLE
cakePHP 3: entity translation with locale different of the default

### ISSUE THREAD

**Issue by mLicorn** [cakephp/cakephp#5678]
Hi,

First, sorry for my english.

I have a problem when I want to add translations for entity's fields when my application  doesn't use default locale.

I want INSERT translations for an entity's field "label".
If my application uses default locale, it's ok.

<i>www.mysite.com/myController/add</i>

But if I uses another locale I have an SQL error DUPLICATE KEY.

<i>www.mysite.com/fr/myController/add</i>

I have 2 availables locales "en_EN" and "fr_FR". The default locale is "en_EN".
I uses a specific table for my entity's translations.

I traced and I found  the reason:

In <i>Cake\ORM\Table</i> in method <i>_processSave</i> the Model method <i>beforeSave</i> is called:

<code>
$event = $this->dispatchEvent('Model.beforeSave', compact('entity', 'options'));
</code>

In <i>Cake\ORM\Behavior\TranslateBehavior</i> the method <i>beforeSave</i> check set property <i>_i18n</i> if is not the default locale.
<code>

        $this->_bundleTranslatedFields($entity);

        $bundled = $entity->get('_i18n') ?: [];

        if ($locale === $this->config('defaultLocale')) {
            return;
        }

        $values = $entity->extract($this->_config['fields'], true);
        $fields = array_keys($values);
        $primaryKey = (array)$this->_table->primaryKey();
        $key = $entity->get(current($primaryKey));
        $model = $this->_table->alias();

        $preexistent = TableRegistry::get($table)->find()
            ->select(['id', 'field'])
            ->where(['field IN' => $fields, 'locale' => $locale, 'foreign_key' => $key, 'model' => $model])
            ->bufferResults(false)
            ->indexBy('field');

        $modified = [];
        foreach ($preexistent as $field => $translation) {
            $translation->set('content', $values[$field]);
            $modified[$field] = $translation;
        }

        $new = array_diff_key($values, $modified);
        foreach ($new as $field => $content) {
            $new[$field] = new Entity(compact('locale', 'field', 'content', 'model'), [
                'useSetters' => false,
                'markNew' => true
            ]);
        }

        $entity->set('_i18n', array_merge($bundled, array_values($modified + $new)));
</code>

<i<$new</i> contains one entity to insert (for "fr_FR").
The problem is that my property <i>_i18n</i> already contains one entity to insert for "fr_FR".
The "array_merge" doesn't replace it but add the entity wich is in <i>$new</i>.
So the system try to add two entity with same key and throw an dusplicate key exception.

I hope my explanations are understandable.
Can you help me please ?

Thanks

**Comment by Xety** [comment]
Hello,

Like i see you're french, and i have an awesome tutorial for I18n in french :
http://cakeinwonderland.oliviersazos.fr/i18n-avec-cakephp-3/
I have implemented I18n with this tutorial and it work like a charm.

Also, if you still need help, you can take a look in my application :
The configuration : https://github.com/Xety/Xeta/blob/master/config/bootstrap.php
The controller where i use the I18n : https://github.com/Xety/Xeta/blob/master/src/Controller/Admin/ArticlesController.php#L53-L117
The behavior used to set the translations to be saved : https://github.com/Xety/Xeta/blob/master/src/Model/Behavior/AppTranslateTrait.php
The view "add" : https://github.com/Xety/Xeta/blob/master/src/Template/Admin/Articles/add.ctp#L59
The view "edit" : https://github.com/Xety/Xeta/blob/master/src/Template/Admin/Articles/edit.ctp#L59
The helper used in view : https://github.com/Xety/Xeta/blob/master/src/View/Helper/I18nHelper.php

**Comment by mLicorn** [comment]
Thank you for your quick response.

I uses this tutorial and it's work when my application uses default locale ("en_EN").
Maybe it's when I set my application's locale I make a mistake.

My config bootstrap.php
<code>
/**
 * Set the default locale. This controls how dates, number and currency is
 * formatted and sets the default language to use for translations.
 */
ini_set('intl.default_locale', 'en_US');

//available languages
Configure::write('I18n.locales', [
    'fr' => 'fr_FR',
]);
</code>

Current language setting: <i>App\Controller\AppController</i>
<code>
$languages = Configure::read('I18n.locales');
$this->set('lang', null);
if (isset($this->request->params['lang']))
{
   $this->set('lang', $this->request->params['lang']);
   I18n::locale(Configure::read('I18n.locales.'.$this->request->params['lang']));
}
</code>

In your project, can you add/update/delete translations when you uses "en_EN" language (not default locale) ?

Thanks a lot.

**Comment by Xety** [comment]
Yes i can. But when you add/update translations with the not default locale, you must set the default locale to your table before to find your translation :
https://github.com/Xety/Xeta/blob/master/src/Controller/Admin/ArticlesController.php#L81

**Comment by mLicorn** [comment]
Thank you for your help cause I found the real problem.

In my AppController I set locale like that:

<code>
I18n::locale("fr_FR");
</code>

So normally when I do:
<code>
I18n::defaultLocale()
</code>

I must retrieve "fr_FR" but I have "en_EN".

I traced in the method "I18n::locale" and the "Locale::setLocale" is done correctly.
I don't understand why my locale configuration is not saved.
Problem of scope or process ?

Do you have an idea please ?

Thanks a lot.

**Comment by Xety** [comment]
The locale defined in `ini_set('intl.default_locale', 'fr_FR');` is modified when you change the locale with `I18n::locale('en_US')`. So, to have the default locale not modified, i have just setup a new locale :
https://github.com/Xety/Xeta/blob/master/config/bootstrap.php#L106
And i use this locale to set the default locale to my table :
https://github.com/Xety/Xeta/blob/master/src/Controller/Admin/ArticlesController.php#L81

**Comment by Xety** [comment]
`I18n::defaultLocale()` give you the value of ` ini_set('intl.default_locale', 'en_US');` and that's why you got `en_US`.

**Comment by ADmad** [comment]
Closing as it seems to be a mistake in understanding rather than a bug. A PR to docs would be welcome if required to clarify things.

**Comment by mLicorn** [comment]
Thank you very much.
I begin in cakePHP so I did not even logical.
It's work for me.
Thank you again.
