### ISSUE TITLE
2.x - Backport plugin-name short aliases

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#5679]
What about backporting #4364?

I have lot of PluginName.PluginName shells  in some of my apps  and it would be a lot easier to type PluginName just once :)

AFIK shells have changed in 3.0. Is there an easy way of implementing something similar in 2.x? I could do this if you pointed me in the right direction.

**Comment by lorenzo** [comment]
If you have time for doing a PR, go for it!

**Comment by AD7six** [comment]
3.x uses aliases to achieve that, 2.x doesn't have aliases - so, to have the same solution mean also implementing aliases.

Alternatively, just squeeze into [getShell](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Console/ShellDispatcher.php#L239-L257) a check for `X.X` if `X` doesn't exist.

**Comment by robertpustulka** [comment]
@AD7six 
>  just squeeze into getShell a check for X.X if X doesn't exist.

That's what I'm trying to do for now.

**Comment by AD7six** [comment]
Closing as there's an open PR for this now.
