### ISSUE TITLE
Cakephp 3.0 RC1 - No function to unload component previously loaded

### ISSUE THREAD

**Issue by galerienv** [cakephp/cakephp#5688]
hello,

on Cakephp 2.0, you are the possibility to unload a component with  $this->Components->unload('Auth') for example.

Now on Cakephp 3.0, you have no function to unload. 

Is it again possible to implement in  Vendor\cakephp\src\Controller\Controller.php an unloadComponent() function ?

**Comment by ADmad** [comment]
```
$this->components()->remove('Foo');
unset($this->Foo);
```

**Comment by galerienv** [comment]
To save memory and/or reset a decoder plugin

**Comment by markstory** [comment]
Given that unloading a component is a less frequent operation than loading one, I think the code @ADmad gave is sufficient. If this comes up more frequently in the future we can consider adding a method. For now, if this is something you need, you can create a method on your AppController :smile:.

**Comment by mehov** [comment]
> ```
> $this->components()->unload('Foo');
> unset($this->Foo);
> ```

Hi, was this deprecated in favour of `getComponents()` (in accordance with `getData()`, `getRequest()` etc.), or is it still `components()`?
