### ISSUE TITLE
3.0 ORM Saving cyclic associations

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5690]
When associations are manually added to form a cycle the infinite loop occures when saving:

```PHP
$article = $articles->find()->contain(['Comments']);

foreach ($article->comments as $comment) {
    $comment->article = $article;
}

$articles->save($article);
```

So the article references to the comments and each comment has a back-reference to the article.
I know that the solution is not to use it, but sometimes in a sophisticated application it is easier to have objects bind like this.

**Comment by lorenzo** [comment]
I have tried to avoid cyclic object graphs as much as possible. I'll add this to the list of enhancements

**Comment by Laykou** [comment]
:+1: Thanks.

If I explicitly set the associations to save, should that solve the problem so far?

```PHP
$articles->save($article, ['associated' => ['Comments']]);
```

I haven't tried it yet but I think so. But if having maaany associations the best way is to let the ORM to handle it :)

**Comment by lorenzo** [comment]
Another way is to mark the "article" property of the comments as not dirty before saving.

**Comment by Laykou** [comment]
Probably neither of the solution is correct, because the fatal error (max level of nested functions calling in PHP) occurs when checking `$entity->errors()`. And as I see, there is no way how to stop it.

**Comment by lorenzo** [comment]
@Laykou Interesting, that should be solved... Treating this as a bug, then

**Comment by Laykou** [comment]
What should prevent the cyclic loop?

I see that here is done the calling on each (association) parameter:
https://github.com/cakephp/cakephp/blob/3.0/src/Datasource/EntityTrait.php#L652

and here is the recursive calling:
https://github.com/cakephp/cakephp/blob/3.0/src/Datasource/EntityTrait.php#L733

**Comment by lorenzo** [comment]
I'm closing this as no one else has com up with the same problem and fixing it would require significant effort.

**Comment by ionas** [comment]
Is this explained in the book, if not, would you consider adding a note to the book @Laykou ?
