### ISSUE TITLE
collection->extract callback matcher is not working

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5691]
http://book.cakephp.org/3.0/en/core-libraries/collections.html
```
(new Collection($array))->extract(function($row) { return $row->column; });
```
The extract method doesn't except a callback although it is allowed in the docs

**Comment by lorenzo** [comment]
Whoops, a recent refactor broke it...

**Comment by lorenzo** [comment]
Closing as there is a PR open
