### ISSUE TITLE
3.0 - Question : AuthComponent::allow()

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#5695]
Hello,

I'm actually working with the plugin ACL, i have setup it with group-only and it work well, expect for unauthenticated users.

In the doc it's written :
```
By marking actions as public, AuthComponent, will not check for a logged in user, nor will authorize objects be checked:
```

Hmm ok but how can i do if i want to allow unauthenticated users to execute somes actions and for somes users logged-in not (Exemple if the user is in the group banned) ?

I have found this solution to apply the `allow()` method only to the unauthenticated users :
```php
public function beforeFilter(Event $event) {
	parent::beforeFilter($event);

	if (!$this->Auth->user()) {
		$this->Auth->allow(['index', 'category', 'article', 'go', 'archive', 'search']);
	}
}
```

But it there a way to do it better and automatically ? Because with this method i must set it in all my controllers...

Also, we can have a similar method to `allow()` and `deny()` who is applied to unauthenticated users only, like `allowGuest()` or something else.

**Comment by jadb** [comment]
@Xety - I don't use ACL myself but 2 suggestions come to mind in order to allow the same actions on all controllers and some specific ones on other.

Something along those lines:

```php
// in your controllers
protected $_guestActions = ['index'];

// in appcontroller
public function beforeFilter(Event $event)
{
    parent::beforeFilter($event);
    $this->Auth->allow($this->_guestActions);
}
```

**Comment by ADmad** [comment]
> Hmm ok but how can i do if i want to allow unauthenticated users to execute somes actions and for somes users logged-in not (Exemple if the user is in the group banned) ?

This doesn't make sense to me. If a user in a banned group is not allowed to access a particular action but unauthenticated users can, the user could just logout and access that action. So what's the point?

**Comment by Xety** [comment]
No, because for example if i ban an user when he is logged-in, he won't be able to logout because the ACL won't allow him to execute the logout action. (I know he can delete his cookies, but a random user doesn't know that.)
XenForo for example does exactly that.

**Comment by ADmad** [comment]
>  (I know he can delete his cookies, but a random user doesn't know that.) XenForo for example does exactly that.

I have no idea what XenForo is but "security by ignorance" isn't the smart way to handle auth.

You have a pretty uncommon use case and I don't think AuthComponent and related classes should be modified to support it.

**Comment by Xety** [comment]
@ADmad Yes i know, but as you know, we can't really ban an user permanently on a website. So i prefer to "discourage" the user by a few different actions like this one for example.

I have found my solution :
http://book.cakephp.org/3.0/en/controllers/components.html#aliasing-components
I will rewrite the action `allow()` for my need, and it will be good. Thanks anyway. :stuck_out_tongue:
