### ISSUE TITLE
CakePHP3.0.0 RC1: Admin CRUD Not Populated while baking

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/cakephp#5698]
Cake bake  is  not asking for admin CRUD  while baking the  Controllers/Views. It should  be there as it was  in previous versions.

**Comment by jadb** [comment]
Please open an issue under [cakephp/bake](/cakephp/bake/issues/new) - it is not part of cake's core anymore.

**Comment by ib-anurag-mishra** [comment]
Thanks Jadb , I have opened this ticket  under cakephp/bake.
