### ISSUE TITLE
3.x loadFixtures doesn't work

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#5699]
So I created two new core fixtures in `vendor/cakephp/cakephp/tests/Fixture` and decided I'd like to load it for a single test case only.

```php
public function testSomethingWithAFixture()
{
    $this->loadFixtures('core.article_categories', 'core.category_authors');
}

// UnexpectedValueException: Referenced fixture class core.article_categories not found
```

To get around it, I used the  `public $fixtures` array and it worked fine.

**Comment by markstory** [comment]
That's not how `loadFixtures()` works though. Its not used to load new new fixtures, but only used to load fixtures when you've turned off automatic fixture loading.

**Comment by davidyell** [comment]
Ah, perhaps the Docs need an update?

**Comment by markstory** [comment]
[The cookbook](http://book.cakephp.org/3.0/en/development/testing.html) is accurate. And the API docs seem correct as well. What needs to be updated.

**Comment by davidyell** [comment]
Ah yes, my apologies. I've obviously misread the page :balloon:
