### ISSUE TITLE
CakePHP can not detect Blackberry Z10 or Blackberry Z30 as a mobile agent

### ISSUE THREAD

**Issue by richan-fongdasen** [cakephp/cakephp#5706]
I'm developing an application that require mobile detection. I've tested it on any Android and iOS devices, and it worked perfectly. But the problem came when i was testing it on Blackberry Z10 and Blackberry Z30.

This is the user agent of Blackbery Z10 and Blackberry Z30 :
Mozilla/5.0 (BB10; Touch) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.0.9.2372 Mobile Safari/537.10+

I acquired it using device mode in Google Chrome browser.

**Comment by coryjthompson** [comment]
I've noticed in your commit you added BB10 to the end. It should probably be alphabetical order like the rest of the user agents.

A unit test should also be added. 

Good work, and if you need any help let me know.

**Comment by ADmad** [comment]
Closing as related PR is open.
