### ISSUE TITLE
Consolidate typehints on beforeMarshal()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5711]
Currently:

    beforeMarshal(Event $event, ArrayObject $data, $options)

http://book.cakephp.org/3.0/en/orm/table-objects.html#beforemarshal

As per comment on https://github.com/cakephp/docs/pull/2308#discussion_r23308892
and @ndm2 s reasonings in https://github.com/cakephp/cakephp/pull/5621 it should rather be

    beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)

I think.

**Comment by markstory** [comment]
Typehints added. `$options` is just a basic array and not an ArrayObject.

**Comment by markstory** [comment]
Fixed in cadda5103ec1cd5b57087ce9f4c772b52975bc97
