### ISSUE TITLE
Model::set() with no datasource throws exception on complex fields.

### ISSUE THREAD

**Issue by AlexMax** [cakephp/cakephp#5712]
I have run into an issue where I cannot call `Model::set()` on a Model that has `$useTable = false` if one of the fields in question is a complex type - such as a file-upload field.  This occurs even though I have `Model::$_schema` defined - Cake seems to decide that it wants to try and get a datasource anyway, and since I have no datasources defined, Cake throws an exception.

Here's a backtrace:

```
Missing Datasource Configuration

Error: The datasource configuration default was not found in database.php.

Notice: If you want to customize this error message, create app\View\Errors\missing_datasource_config.ctp

Stack Trace

CORE\Cake\Model\ConnectionManager.php line 91 → ConnectionManager::_getConnectionObject(string)
CORE\Cake\Model\Model.php line 3643 → ConnectionManager::getDataSource(string)
CORE\Cake\Model\Model.php line 1431 → Model->getDataSource()
CORE\Cake\Model\Model.php line 1298 → Model->getColumnType(string)
CORE\Cake\Model\Model.php line 1235 → Model->deconstruct(string, array)
APP\Controller\SamplesController.php line 15 → Model->set(array)
[internal function] → SamplesController->index()
CORE\Cake\Controller\Controller.php line 490 → ReflectionMethod->invokeArgs(SamplesController, array)
CORE\Cake\Routing\Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE\Cake\Routing\Dispatcher.php line 167 → Dispatcher->_invoke(SamplesController, CakeRequest)
APP\webroot\index.php line 118 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

Here is a sample that will trigger the bug:

    class Sample extends AppModel {
        public $useTable = false;
        public $_schema = [
            'filefield' => [
                'type'    => 'string',
                'length'  => 254,
                'default' => null,
                'null'    => true,
                'comment' => null
            ],
        ];
    }
    
    class SamplesController extends AppController {
        public function index() {
            $this->Sample->set([
                'Sample' => [
                    'filefield' => [
                        'name' => '',
                        'type' => '',
                        'tmp_name' => '',
                        'error' => 4,
                        'size' => 0
                    ]
                ]
            ]);
        }
    }

`CakePHP: 2.6.1`
`PHP: 5.4`
`Platform: Windows 2008 R2`

**Comment by ceeram** [comment]
See #5713
