### ISSUE TITLE
saveAssociated always returns invalid fields

### ISSUE THREAD

**Issue by panchazo** [cakephp/cakephp#5716]
Tested on cake 2.4 and also 2.6 and PHP Version 5.5.9-1ubuntu4. 

In cake version 2.6 file lib/Cake/Model/Model.php line 2497 the "if" condition is not working as expected due to the condition over the "$this->save" :

```
if ($validates && !($this->create(null) !== null && $this->save($data, array('atomic' => false) + $options))) {...}
```

But it works correcly if the condition is checked against the function outcome assigned to a variable like this (propsed fix):

```
$saveResult = $this->save($data, array('atomic' => false) + $options);

if ($validates && !($this->create(null) !== null && $saveResult)) {... }
```

**Comment by ceeram** [comment]
What exactly does this fix? so we can add a testcase for this. Also i don't understand how assigning to a variable first would change the behavior of the `if` condition.

**Comment by ceeram** [comment]
Nvm that last remark, i understand now, as the save() operation behaves differently when not calling create(null) first.
Do you have example data that would expose the issue?

**Comment by panchazo** [comment]
I have a running project  if you have time now I can show you via skype how
it fails and then it works after this fix and all the models, db, etc
associated to the project (as it is private project I cannot publish the
code in this moment). Let me know if that helps

2015-01-22 13:21 GMT-03:00 ceeram <notifications@github.com>:

> Nvm that last remark, i understand now, as the save() operation behaves
> differently when not calling create(null) first.
> Do you have example data that would expose the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/cakephp/issues/5716#issuecomment-71047493>.
>



-- 
Ing. Francisco Clariá
*Inauguramos nueva web, visitanos en www.Axones.com.ar
<http://www.axones.com.ar/>*

**Comment by ceeram** [comment]
You could perhaps write a testcase or give some example code that
reproduces the issue. We don't need your exact projects code, just
something similar that proves the bug or perhaps exposes something
incorrect in your application

2015-01-22 17:31 GMT+01:00 panchazo <notifications@github.com>:

**Comment by panchazo** [comment]
Hi Marc, preparing the code to submit to you a testcase I found a save()
that was being overriden in AppModel and was calling the parent method with
$this->data instead of the submited $data to the method... so to make a
long story short, it was our mistake. Please close this issue. Thank's for
your assitance and my apologies for submiting this issue wrongly.

Best,




2015-01-22 13:37 GMT-03:00 ceeram <notifications@github.com>:

> You could perhaps write a testcase or give some example code that
> reproduces the issue. We don't need your exact projects code, just
> something similar that proves the bug or perhaps exposes something
> incorrect in your application
>
> 2015-01-22 17:31 GMT+01:00 panchazo <notifications@github.com>:
>
> > I have a running project if you have time now I can show you via skype
> how
> > it fails and then it works after this fix and all the models, db, etc
> > associated to the project (as it is private project I cannot publish the
> > code in this moment). Let me know if that helps
> >
> > 2015-01-22 13:21 GMT-03:00 ceeram <notifications@github.com>:
> >
> > > Nvm that last remark, i understand now, as the save() operation
> behaves
> > > differently when not calling create(null) first.
> > > Do you have example data that would expose the issue?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cakephp/cakephp/issues/5716#issuecomment-71047493>.
>
> > >
> >
> >
> >
> > --
> > Ing. Francisco Clariá
> > *Inauguramos nueva web, visitanos en www.Axones.com.ar
> > <http://www.axones.com.ar/>*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cakephp/cakephp/issues/5716#issuecomment-71049422>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/cakephp/issues/5716#issuecomment-71050555>.
>



-- 
Ing. Francisco Clariá
*Inauguramos nueva web, visitanos en www.Axones.com.ar
<http://www.axones.com.ar/>*
