### ISSUE TITLE
3.0 Query "first()" does not work after setting "bufferResults(false)"

### ISSUE THREAD

**Issue by snelg** [cakephp/cakephp#5720]
This works:
````
$query = $clubs->find()->where(['id' => 1]);
$club = $query->first();
````

This does not:
````
$query = $clubs->find()->where(['id' => 1]);
$query->bufferResults(false);
$club = $query->first();
````

$club is null in that second example. Something to do with ResultSet->valid() getting called twice, but I haven't stepped through at a low enough level to follow the logic.

**Comment by markstory** [comment]
I can look into this, I was able to reproduce it.

**Comment by markstory** [comment]
Closing as a pull request it up now.
