### ISSUE TITLE
Entity should be compatible with PSR2

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#5722]
Accessors methods begin with "_get" or "_set", but PSR2 says "Method names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility". We should we remove the underscore.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/4499

This cannot be done until 4.0 due to BC breaks.

**Comment by josegonzalez** [comment]
Heh I like that we might do this now, given that we made a conscious decision to use underscores :P

**Comment by markstory** [comment]
Should not is not must not. Removing the underscores will break api compatibility which is something we have promised with the rc release.

**Comment by rochamarcelo** [comment]
We could be more flexible, permintindo accessor methods begin with or not "_".

I didn't saw #4499 .

**Comment by markstory** [comment]
@rochamarcelo We totally could, but there are a number of other 'hook methods' that would continue to retain their `_` for compatibility reasons. While the underscores aren't ideal in light of PSR-2, maintaining consistency across the various points developer code interacts with framework is something worth holding onto.

**Comment by lorenzo** [comment]
I prefer not to go back to that. The reason they have underscores now is that people were concerned about having real getters and setters colliding with the magic hooks that we have right now, which I had to agree it is a fair concern.

For me a coding standard should not dictate your architectural decisions.

**Comment by rochamarcelo** [comment]
@lorenzo Thats a good point, I really had not looked in that way.

**Comment by markstory** [comment]
Closing then, as I too forgot about the overlap with userland get/set methods.
