### ISSUE TITLE
3.0 Problem with 'cake bake controller' about newEntity

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5725]
Hello,
I found a little problem in 'cake bake controller' regarding the new validation mechanism. 
In add() method, It creates the following line of code:

    $myEntity = $this->myEntities->newEntity($this->request->datas);

which causes the fields to be in error in the Form. 

It should create the line:

    $myEntity = $this->myEntities->newEntity();

**Comment by lorenzo** [comment]
The latest version of bake does exactly that. Please update it.

**Comment by caBBAlainB** [comment]
Surprinsing, I updated it yesterday.

**Comment by lorenzo** [comment]
You can see here: https://github.com/cakephp/bake/blob/master/src/Template/Bake/Element/Controller/add.ctp#L25

**Comment by dereuromark** [comment]
@caBBAlainB  Make sure you use dev-master (and not 0.1.*) ;)

**Comment by caBBAlainB** [comment]
is it correct?

    {
        "name": "cakephp/cakephp",
        "version": "3.0.x-dev",
        "version_normalized": "3.0.9999999.9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/cakephp/cakephp.git",
            "reference": "da10b6b33a58cc4640b202d8458f34bfbf802b37"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/cakephp/cakephp/zipball/da10b6b33a58cc4640b202d8458f34bfbf802b37",
            "reference": "da10b6b33a58cc4640b202d8458f34bfbf802b37",
            "shasum": ""
        },
        "require": {
            "aura/intl": "1.1.*",
            "ext-intl": "*",
            "ext-mbstring": "*",
            "ircmaxell/password-compat": "1.0.*",
            "nesbot/carbon": "1.13.*",
            "php": ">=5.4.16",
            "psr/log": "1.0"
        },
        "replace": {
            "cakephp/cache": "self.version",
            "cakephp/collection": "self.version",
            "cakephp/core": "self.version",
            "cakephp/database": "self.version",
            "cakephp/datasource": "self.version",
            "cakephp/event": "self.version",
            "cakephp/i18n": "self.version",
            "cakephp/log": "self.version",
            "cakephp/utility": "self.version",
            "cakephp/validation": "self.version"
        },
        "require-dev": {
            "cakephp/cakephp-codesniffer": "dev-master",
            "phpunit/phpunit": "*"
        },
        "time": "2015-01-21 08:58:55",
        "type": "library",
        "installation-source": "source",
        "autoload": {
            "psr-4": {
                "Cake\\": "src"
            },
            "files": [
                "src/Core/functions.php",
                "src/Collection/functions.php",
                "src/I18n/functions.php"
            ]
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "CakePHP Community",
                "homepage": "https://github.com/cakephp/cakephp/graphs/contributors"
            }
        ],
        "description": "The CakePHP framework",
        "homepage": "http://cakephp.org",
        "keywords": [
            "framework"
        ]
    },

**Comment by dereuromark** [comment]
I am talking about your app composer json not the core one.

**Comment by caBBAlainB** [comment]
{
	"name": "cakephp/app",
	"description": "CakePHP skeleton app",
	"homepage": "http://cakephp.org",
	"type": "project",
	"license": "MIT",
	"require": {
		"php": ">=5.4.16",
		"cakephp/cakephp": "3.0.*-dev",
		"mobiledetect/mobiledetectlib": "2.*",
		"cakephp/debug_kit": "3.0.*-dev",
		"gourmet/twitter_bootstrap": "dev-master",
		"codemonkeys-ru/gcm-message": "dev-master",
		"holt59/cakephp3-bootstrap3-helpers": "dev-master",
		"imagine/imagine": "dev-master"
	},
	"require-dev": {
		"d11wtq/boris": "1.0.*"
	},
	"suggest": {
		"phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
		"cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
	},
	"autoload": {
		"psr-4": {
			"App\\": "src"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"App\\Test\\": "tests",
			"Cake\\Test\\Fixture\\": "./vendor/cakephp/cakephp/tests/Fixture"
		}
	},
	"scripts": {
		"post-install-cmd": "App\\Console\\Installer::postInstall"
	},
	"minimum-stability" : "dev",
	"prefer-stable": true
}

**Comment by dereuromark** [comment]
You don't have to paste all your code.
All you need to verify is that you use `"cakephp/bake": "dev-master"` and that you `composer update`.

**Comment by caBBAlainB** [comment]
It seems that bake is missing!


[
    {
        "name": "aura/installer-default",
        "version": "1.0.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/auraphp/installer-default.git",
            "reference": "52f8de3670cc1ef45a916f40f732937436d028c8"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/auraphp/installer-default/zipball/52f8de3670cc1ef45a916f40f732937436d028c8",
            "reference": "52f8de3670cc1ef45a916f40f732937436d028c8",
            "shasum": ""
        },
        "time": "2012-11-26 21:35:57",
        "type": "composer-installer",
        "extra": {
            "class": "Aura\\Composer\\DefaultInstaller"
        },
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Aura\\Composer\\": "src/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "BSD-2-Clause"
        ],
        "authors": [
            {
                "name": "Paul M. Jones",
                "email": "pmjones88@gmail.com",
                "homepage": "http://paul-m-jones.com"
            }
        ],
        "description": "Installs Aura packages using the Composer defaults.",
        "keywords": [
            "aura",
            "installer"
        ]
    },
    {
        "name": "psr/log",
        "version": "1.0.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/php-fig/log.git",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/php-fig/log/zipball/fe0936ee26643249e916849d48e3a51d5f5e278b",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b",
            "shasum": ""
        },
        "time": "2012-12-21 11:40:51",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Psr\\Log\\": ""
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "PHP-FIG",
                "homepage": "http://www.php-fig.org/"
            }
        ],
        "description": "Common interface for logging libraries",
        "keywords": [
            "log",
            "psr",
            "psr-3"
        ]
    },
    {
        "name": "aura/intl",
        "version": "1.1.1",
        "version_normalized": "1.1.1.0",
        "source": {
            "type": "git",
            "url": "https://github.com/auraphp/Aura.Intl.git",
            "reference": "c5fe620167550ad6fa77dd3570fba2efc77a2a21"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/auraphp/Aura.Intl/zipball/c5fe620167550ad6fa77dd3570fba2efc77a2a21",
            "reference": "c5fe620167550ad6fa77dd3570fba2efc77a2a21",
            "shasum": ""
        },
        "require": {
            "aura/installer-default": "1.0.*",
            "php": ">=5.4.0"
        },
        "time": "2014-08-24 00:00:00",
        "type": "aura-package",
        "extra": {
            "aura": {
                "type": "library",
                "config": {
                    "common": "Aura\\Intl\\_Config\\Common"
                }
            },
            "branch-alias": {
                "dev-develop": "1.1.x-dev"
            }
        },
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Aura\\Intl": "src/"
            },
            "psr-4": {
                "Aura\\Intl\\_Config\\": "config/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "BSD-2-Clause"
        ],
        "authors": [
            {
                "name": "Paul M. Jones",
                "email": "pmjones88@gmail.com",
                "homepage": "http://paul-m-jones.com"
            },
            {
                "name": "Aura.Intl Contributors",
                "homepage": "https://github.com/auraphp/Aura.Intl/contributors"
            },
            {
                "name": "Pascal Borreli",
                "email": "pascal@borreli.com"
            },
            {
                "name": "Mapthegod",
                "email": "mapthegod@gmail.com"
            },
            {
                "name": "José Lorenzo Rodríguez",
                "email": "jose.zap@gmail.com"
            }
        ],
        "description": "The Aura.Intl package provides internationalization (I18N) tools, specifically\npackage-oriented per-locale message translation.",
        "homepage": "http://auraphp.com/Aura.Intl",
        "keywords": [
            "g11n",
            "globalization",
            "i18n",
            "internationalization",
            "intl",
            "l10n",
            "localization"
        ]
    },
    {
        "name": "d11wtq/boris",
        "version": "v1.0.8",
        "version_normalized": "1.0.8.0",
        "source": {
            "type": "git",
            "url": "https://github.com/d11wtq/boris.git",
            "reference": "125dd4e5752639af7678a22ea597115646d89c6e"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e",
            "reference": "125dd4e5752639af7678a22ea597115646d89c6e",
            "shasum": ""
        },
        "require": {
            "php": ">=5.3.0"
        },
        "suggest": {
            "ext-pcntl": "*",
            "ext-posix": "*",
            "ext-readline": "*"
        },
        "time": "2014-01-17 12:21:18",
        "bin": [
            "bin/boris"
        ],
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Boris": "lib"
            }
        },
        "notification-url": "https://packagist.org/downloads/"
    },
    {
        "name": "ircmaxell/password-compat",
        "version": "v1.0.4",
        "version_normalized": "1.0.4.0",
        "source": {
            "type": "git",
            "url": "https://github.com/ircmaxell/password_compat.git",
            "reference": "5c5cde8822a69545767f7c7f3058cb15ff84614c"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/ircmaxell/password_compat/zipball/5c5cde8822a69545767f7c7f3058cb15ff84614c",
            "reference": "5c5cde8822a69545767f7c7f3058cb15ff84614c",
            "shasum": ""
        },
        "require-dev": {
            "phpunit/phpunit": "4.*"
        },
        "time": "2014-11-20 16:49:30",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "files": [
                "lib/password.php"
            ]
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Anthony Ferrara",
                "email": "ircmaxell@php.net",
                "homepage": "http://blog.ircmaxell.com"
            }
        ],
        "description": "A compatibility library for the proposed simplified password hashing algorithm: https://wiki.php.net/rfc/password_hash",
        "homepage": "https://github.com/ircmaxell/password_compat",
        "keywords": [
            "hashing",
            "password"
        ]
    },
    {
        "name": "nesbot/carbon",
        "version": "1.13.0",
        "version_normalized": "1.13.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/briannesbitt/Carbon.git",
            "reference": "5cb6e71055f7b0b57956b73d324cc4de31278f42"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/briannesbitt/Carbon/zipball/5cb6e71055f7b0b57956b73d324cc4de31278f42",
            "reference": "5cb6e71055f7b0b57956b73d324cc4de31278f42",
            "shasum": ""
        },
        "require": {
            "php": ">=5.3.0"
        },
        "require-dev": {
            "phpunit/phpunit": "~4.0"
        },
        "time": "2014-09-26 02:52:02",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Carbon": "src"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Brian Nesbitt",
                "email": "brian@nesbot.com",
                "homepage": "http://nesbot.com"
            }
        ],
        "description": "A simple API extension for DateTime.",
        "homepage": "https://github.com/briannesbitt/Carbon",
        "keywords": [
            "date",
            "datetime",
            "time"
        ]
    },
    {
        "name": "mobiledetect/mobiledetectlib",
        "version": "2.8.11",
        "version_normalized": "2.8.11.0",
        "source": {
            "type": "git",
            "url": "https://github.com/serbanghita/Mobile-Detect.git",
            "reference": "c68901fb09227dcf04872f0d6a27b9f6e75ecf1f"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/serbanghita/Mobile-Detect/zipball/c68901fb09227dcf04872f0d6a27b9f6e75ecf1f",
            "reference": "c68901fb09227dcf04872f0d6a27b9f6e75ecf1f",
            "shasum": ""
        },
        "require": {
            "php": ">=5.0.0"
        },
        "require-dev": {
            "johnkary/phpunit-speedtrap": "~1.0@dev",
            "phpunit/phpunit": "*"
        },
        "time": "2014-11-23 13:08:17",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "classmap": [
                "Mobile_Detect.php"
            ],
            "psr-0": {
                "Detection": "namespaced/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Serban Ghita",
                "email": "serbanghita@gmail.com",
                "homepage": "http://mobiledetect.net",
                "role": "Developer"
            }
        ],
        "description": "Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with specific HTTP headers to detect the mobile environment.",
        "homepage": "https://github.com/serbanghita/Mobile-Detect",
        "keywords": [
            "detect mobile devices",
            "mobile",
            "mobile detect",
            "mobile detector",
            "php mobile detect"
        ]
    },
    {
        "name": "codemonkeys-ru/gcm-message",
        "version": "dev-master",
        "version_normalized": "9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/CodeMonkeysRu/GCMMessage.git",
            "reference": "5f08de1a390df1e429c9e1fd28b16efc0c0f94ea"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/CodeMonkeysRu/GCMMessage/zipball/5f08de1a390df1e429c9e1fd28b16efc0c0f94ea",
            "reference": "5f08de1a390df1e429c9e1fd28b16efc0c0f94ea",
            "shasum": ""
        },
        "require": {
            "php": ">=5.3.2"
        },
        "time": "2014-10-09 12:37:22",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "CodeMonkeysRu\\GCM": "library/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Vladimir Savenkov",
                "email": "ivariable@gmail.com",
                "homepage": "http://ivariable.ru",
                "role": "Developer"
            }
        ],
        "description": "Google Cloud Messaging (GCM) PHP Server Library",
        "keywords": [
            "android",
            "gcm",
            "push message"
        ]
    },
    {
        "name": "gourmet/twitter_bootstrap",
        "version": "dev-master",
        "version_normalized": "9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/gourmet/twitter_bootstrap.git",
            "reference": "3a7c03114724d85a1d7717be5b8cbb80bb2bd4bb"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/gourmet/twitter_bootstrap/zipball/3a7c03114724d85a1d7717be5b8cbb80bb2bd4bb",
            "reference": "3a7c03114724d85a1d7717be5b8cbb80bb2bd4bb",
            "shasum": ""
        },
        "require": {
            "cakephp/cakephp": "3.0.*-dev",
            "cakephp/plugin-installer": "*"
        },
        "require-dev": {
            "phpunit/phpunit": "4.1.*"
        },
        "time": "2014-12-31 04:27:29",
        "type": "cakephp-plugin",
        "extra": {
            "installer-name": "Gourmet/TwitterBootstrap"
        },
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "Gourmet\\TwitterBootstrap\\": "src"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Jad Bitar",
                "homepage": "http://jadb.io",
                "role": "Author"
            },
            {
                "name": "Others",
                "homepage": "https://github.com/gourmet/twitter_bootstrap/graphs/contributors"
            }
        ],
        "description": "Twitter Bootstrap 3 support for CakePHP 3",
        "homepage": "http://github.com/gourmet/twitter_bootstrap",
        "keywords": [
            "bootstrap",
            "cakephp",
            "twitter"
        ]
    },
    {
        "name": "holt59/cakephp3-bootstrap3-helpers",
        "version": "dev-master",
        "version_normalized": "9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/Holt59/cakephp3-bootstrap3-helpers.git",
            "reference": "dcf0f2d6883dcfc257bbff3cf5250474c5f91f7b"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/Holt59/cakephp3-bootstrap3-helpers/zipball/dcf0f2d6883dcfc257bbff3cf5250474c5f91f7b",
            "reference": "dcf0f2d6883dcfc257bbff3cf5250474c5f91f7b",
            "shasum": ""
        },
        "require": {
            "composer/installers": "*"
        },
        "require-dev": {
            "cakephp/cakephp": "3.0.x-dev"
        },
        "time": "2014-12-06 20:21:54",
        "type": "cakephp-plugin",
        "extra": {
            "installer-name": "Bootstrap3"
        },
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "Bootstrap3\\": "src"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "Apache"
        ],
        "description": "Bootstrap 3 Helpers for CakePHP 3.0",
        "keywords": [
            "bootstrap",
            "cakephp"
        ]
    },
    {
        "name": "cakephp/plugin-installer",
        "version": "0.0.6",
        "version_normalized": "0.0.6.0",
        "source": {
            "type": "git",
            "url": "https://github.com/cakephp/plugin-installer.git",
            "reference": "376c15c687f256225f6ec3d7248746966bf33f15"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/cakephp/plugin-installer/zipball/376c15c687f256225f6ec3d7248746966bf33f15",
            "reference": "376c15c687f256225f6ec3d7248746966bf33f15",
            "shasum": ""
        },
        "require-dev": {
            "cakephp/core": "dev-master",
            "composer/composer": "1.0.*@dev"
        },
        "time": "2015-01-17 04:31:50",
        "type": "composer-installer",
        "extra": {
            "class": "Cake\\Composer\\Installer\\PluginInstaller"
        },
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "Cake\\Composer\\": "src/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "CakePHP Community",
                "homepage": "http://cakephp.org"
            }
        ],
        "description": "A composer installer for CakePHP 3.0+ plugins."
    },
    {
        "name": "composer/installers",
        "version": "v1.0.20",
        "version_normalized": "1.0.20.0",
        "source": {
            "type": "git",
            "url": "https://github.com/composer/installers.git",
            "reference": "1bff8aa77a18f3616f468ed8000cf86a5725bac3"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/composer/installers/zipball/1bff8aa77a18f3616f468ed8000cf86a5725bac3",
            "reference": "1bff8aa77a18f3616f468ed8000cf86a5725bac3",
            "shasum": ""
        },
        "replace": {
            "roundcube/plugin-installer": "*",
            "shama/baton": "*"
        },
        "require-dev": {
            "composer/composer": "1.0.*@dev",
            "phpunit/phpunit": "4.1.*"
        },
        "time": "2015-01-11 03:51:11",
        "type": "composer-installer",
        "extra": {
            "class": "Composer\\Installers\\Installer",
            "branch-alias": {
                "dev-master": "1.0-dev"
            }
        },
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Composer\\Installers\\": "src/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Kyle Robinson Young",
                "email": "kyle@dontkry.com",
                "homepage": "https://github.com/shama"
            }
        ],
        "description": "A multi-framework Composer library installer",
        "homepage": "http://composer.github.com/installers/",
        "keywords": [
            "Craft",
            "Dolibarr",
            "Hurad",
            "MODX Evo",
            "OXID",
            "SMF",
            "Thelia",
            "WolfCMS",
            "agl",
            "annotatecms",
            "bitrix",
            "cakephp",
            "chef",
            "codeigniter",
            "concrete5",
            "croogo",
            "dokuwiki",
            "drupal",
            "elgg",
            "fuelphp",
            "grav",
            "installer",
            "joomla",
            "kohana",
            "laravel",
            "lithium",
            "magento",
            "mako",
            "mediawiki",
            "modulework",
            "moodle",
            "phpbb",
            "piwik",
            "ppi",
            "puppet",
            "roundcube",
            "shopware",
            "silverstripe",
            "symfony",
            "typo3",
            "wordpress",
            "zend",
            "zikula"
        ]
    },
    {
        "name": "cakephp/cakephp",
        "version": "3.0.x-dev",
        "version_normalized": "3.0.9999999.9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/cakephp/cakephp.git",
            "reference": "da10b6b33a58cc4640b202d8458f34bfbf802b37"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/cakephp/cakephp/zipball/da10b6b33a58cc4640b202d8458f34bfbf802b37",
            "reference": "da10b6b33a58cc4640b202d8458f34bfbf802b37",
            "shasum": ""
        },
        "require": {
            "aura/intl": "1.1.*",
            "ext-intl": "*",
            "ext-mbstring": "*",
            "ircmaxell/password-compat": "1.0.*",
            "nesbot/carbon": "1.13.*",
            "php": ">=5.4.16",
            "psr/log": "1.0"
        },
        "replace": {
            "cakephp/cache": "self.version",
            "cakephp/collection": "self.version",
            "cakephp/core": "self.version",
            "cakephp/database": "self.version",
            "cakephp/datasource": "self.version",
            "cakephp/event": "self.version",
            "cakephp/i18n": "self.version",
            "cakephp/log": "self.version",
            "cakephp/utility": "self.version",
            "cakephp/validation": "self.version"
        },
        "require-dev": {
            "cakephp/cakephp-codesniffer": "dev-master",
            "phpunit/phpunit": "*"
        },
        "time": "2015-01-21 08:58:55",
        "type": "library",
        "installation-source": "source",
        "autoload": {
            "psr-4": {
                "Cake\\": "src"
            },
            "files": [
                "src/Core/functions.php",
                "src/Collection/functions.php",
                "src/I18n/functions.php"
            ]
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "CakePHP Community",
                "homepage": "https://github.com/cakephp/cakephp/graphs/contributors"
            }
        ],
        "description": "The CakePHP framework",
        "homepage": "http://cakephp.org",
        "keywords": [
            "framework"
        ]
    },
    {
        "name": "cakephp/debug_kit",
        "version": "3.0.x-dev",
        "version_normalized": "3.0.9999999.9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/cakephp/debug_kit.git",
            "reference": "153285444901853853f8a63deb658716350738b5"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/cakephp/debug_kit/zipball/153285444901853853f8a63deb658716350738b5",
            "reference": "153285444901853853f8a63deb658716350738b5",
            "shasum": ""
        },
        "require": {
            "cakephp/cakephp": "3.0.*-dev",
            "cakephp/plugin-installer": "*"
        },
        "require-dev": {
            "cakephp/cakephp-codesniffer": "dev-master",
            "phpunit/phpunit": "4.1.*"
        },
        "time": "2015-01-18 16:09:28",
        "type": "cakephp-plugin",
        "extra": {
            "installer-name": "DebugKit"
        },
        "installation-source": "source",
        "autoload": {
            "psr-4": {
                "DebugKit\\": "src",
                "DebugKit\\Test\\Fixture\\": "tests\\Fixture"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Mark Story",
                "homepage": "http://mark-story.com",
                "role": "Author"
            },
            {
                "name": "CakePHP Community",
                "homepage": "https://github.com/cakephp/debug_kit/graphs/contributors"
            }
        ],
        "description": "CakePHP Debug Kit",
        "homepage": "https://github.com/cakephp/debug_kit",
        "keywords": [
            "cakephp",
            "debug",
            "kit"
        ]
    },
    {
        "name": "imagine/imagine",
        "version": "dev-master",
        "version_normalized": "9999999-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/avalanche123/Imagine.git",
            "reference": "10e9522f11a6e846061226b7e54347909a849e09"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/avalanche123/Imagine/zipball/10e9522f11a6e846061226b7e54347909a849e09",
            "reference": "10e9522f11a6e846061226b7e54347909a849e09",
            "shasum": ""
        },
        "require": {
            "php": ">=5.3.2"
        },
        "require-dev": {
            "sami/sami": "dev-master"
        },
        "suggest": {
            "ext-gd": "to use the GD implementation",
            "ext-gmagick": "to use the Gmagick implementation",
            "ext-imagick": "to use the Imagick implementation"
        },
        "time": "2014-08-26 11:26:34",
        "type": "library",
        "extra": {
            "branch-alias": {
                "dev-develop": "0.7-dev"
            }
        },
        "installation-source": "source",
        "autoload": {
            "psr-0": {
                "Imagine": "lib/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Bulat Shakirzyanov",
                "email": "mallluhuct@gmail.com",
                "homepage": "http://avalanche123.com"
            }
        ],
        "description": "Image processing for PHP 5.3",
        "homepage": "http://imagine.readthedocs.org/",
        "keywords": [
            "drawing",
            "graphics",
            "image manipulation",
            "image processing"
        ]
    }
]

**Comment by Xety** [comment]
Just add `"cakephp/bake": "dev-master"` in the `require-dev` and do a `composer update`. That's all.

**Comment by caBBAlainB** [comment]
Xety, That's I did. Thanks
