### ISSUE TITLE
Cake\Utility\Text is missing from cakephp 3.0

### ISSUE THREAD

**Issue by gveranis** [cakephp/cakephp#5726]
The http://api.cakephp.org/3.0/class-Cake.Utility.Text.html presents the class Text , but this class is missing from the code when this installed on a machine. Also ii's missing from the code on github. Something wrong is happen or with code or with documentation. 
 "name": "cakephp/cakephp",
            "version": "3.0.x-dev",
Debian 7

**Comment by lorenzo** [comment]
It is here: https://github.com/cakephp/cakephp/blob/3.0/src/Utility/Text.php

Update your version of cakephp :)
