### ISSUE TITLE
How to create a multiple of login with Tables Different ?

### ISSUE THREAD

**Issue by luuckx2** [cakephp/cakephp#5729]
I'm trying to create a login system with using two different tables one for the board administrator othe apar customer and am having a problem because both logins use by default the Users table and I'm unable to change ..
If they can deem a look at my code

https://github.com/luuckx2/cakephp3-MultipleAuth/blob/master/src/Controller/AppController.php

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
