### ISSUE TITLE
Cannot redeclare class debugger 

### ISSUE THREAD

**Issue by aderiver** [cakephp/cakephp#5730]
Hi;

I'm using php 5.4.36, when running my project, show me cakephp this error

Error: include(): Cannot redeclare class debugger
File: /var/www/dev/estratificacion/lib/Cake/Core/App.php
Line: 547

thanks

**Comment by aderiver** [comment]
I'm using cakephp 2.6.1

**Comment by josegonzalez** [comment]
Do you have a second `Debugger` class specified somewhere?

**Comment by aderiver** [comment]
Hi josegonzalez

no, i not have second Debugger

**Comment by biesbjerg** [comment]
I had this issue, after updating cake (can't remember if I updated to 2.6 or it was an issue with a 2.5.x version as well).

I solved it by setting this APC option:

```
apc.include_once_override = 0
```

**Comment by aderiver** [comment]
Hi biesbjerg

thank you very much, it worked me

**Comment by dereuromark** [comment]
Maybe that is a useful info for the docs somewhere?

**Comment by thaJeztah** [comment]
+1 to documenting it; issues like this are hard to resolve if you don't think of APC

**Comment by markstory** [comment]
Using zend_opcache is a good way to fix the issue to.

**Comment by thaJeztah** [comment]
>Using zend_opcache is a good way to fix the issue to.

True, also APC is deprecated. Still, I have a couple of servers using it, and it can be a PITA to track this kind of things down.
