### ISSUE TITLE
IntegrationTestCase reports test as risky

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5731]
The controller action that is tested contains:

    $this->request->allowMethod(['post', 'delete']);

So if one would access it as GET, it should throw an exception.
If we test on that using

    $this->get(array('controller' => 'Attendance', 'action' => 'delete', $id));
    $this->assertResponseError(); // 405

the test passes, but it is marked as "risky" (R).
Risky means that no assert has been executed, but in fact at least 2 have been here.

It seems that some of the internal handling of the caught exception is causing this.

**Comment by markstory** [comment]
What makes you think it has something to do with the dispatcher error handling?

**Comment by dereuromark** [comment]
Right now I don't really have a clue what it could be.
But it does happen for other (similar) asserts of other code ranges too that result from exceptions being thrown (e.g. 404). OK (2xx and 3xx) dont have that issue.

**Comment by markstory** [comment]
I wasn't able to reproduce this with a basic baked controller + test case. My test case looked like:

```php
    public function testDelete()
    {
        $this->get('/bookmarks/delete/1');
        $this->assertResponseError();
    }
```

**Comment by dereuromark** [comment]
That is interesting. You can see the Rs in the test suite above? You can also check out that branch and it will most likely be reproducable. 
I used PHPUnit 4.x by the way, as with a normal Cake3 install.

**Comment by lorenzo** [comment]
@markstory phpunit 3.7 does not have the concept of risky tests

**Comment by markstory** [comment]
I'll try again with PHPUnit 4 then :smile:

**Comment by markstory** [comment]
Same result with PHPUnit 4.4.5, no risky test.

**Comment by dereuromark** [comment]
But it is here to be reproduced (3 days ago for example): https://travis-ci.org/dereuromark/cakefest/jobs/48453370
So sth must be up.

**Comment by markstory** [comment]
It is very possible that there are things in the app code triggering a `R` result. I don't really have time to comb through an app looking for why though.  I wasn't able to trigger the risky result on a baked app, which makes me think it is either a plugin or app code.
