### ISSUE TITLE
Fatal error on non-existing association

### ISSUE THREAD

**Issue by oldskool** [cakephp/cakephp#5738]
On Cake3.0.0-RC1, when trying to do a find with a contain to a model that is not associated to the current one, a fatal error occurs. Using this code in my Table model:

```php
public function findLatestPost($forumId)
{
    $query = $this->Threads->find('all', [
            'contain' => ['Posts'],
            'conditions' => ['Threads.forum_id' => $forumId],
            'order' => ['Posts.created' => 'DESC']
     ]);
    return $query->first();
}
```

I got this error:

> Fatal error: Method Cake\ORM\Query::__toString() must not throw an exception in vendor\cakephp\cakephp\src\Database\Driver\Mysql.php on line 0

As it turned out I forgot to associate the `Posts` model to the `Threads` model. Once I associated them properly, the error disappeared. But the error message is not clear and I'm not sure why this is a fatal error and the ORM doesn't just "skip" this query (or return an empty result set) when it can't do the join.

Note that even when wrapping the `$query` bit into a try/catch block, a fatal error is still thrown.

**Comment by josegonzalez** [comment]
Do you have a stacktrace for this?

**Comment by oldskool** [comment]
@josegonzalez Here it is:
```
#	Time	Memory	Function	Location
1	0.0010	142440	{main}( )	..\index.php:0
2	0.0840	2538896	Cake\Routing\Dispatcher->dispatch( )	..\index.php:37
3	0.1080	3208616	Cake\Routing\Dispatcher->_invoke( )	..\Dispatcher.php:87
4	0.1200	3468008	Cake\Controller\Controller->invokeAction( )	..\Dispatcher.php:114
5	0.1200	3468312	call_user_func_array ( )	..\Controller.php:405
6	0.1200	3468456	App\Controller\ForumsController->index( )	..\Controller.php:405
7	0.1300	4105008	App\Model\Table\ForumsTable->findLatestPost( )	..\ForumsController.php:25
8	1.1491	4960384	Cake\ORM\Query->first( )	..\ForumsTable.php:80
9	1.1491	4960488	Cake\ORM\Query->all( )	..\QueryTrait.php:340
10	1.1491	4960592	Cake\ORM\Query->all( )	..\Query.php:592
11	1.1491	4960664	Cake\ORM\Query->_execute( )	..\QueryTrait.php:218
12	1.1491	4960808	Cake\Database\Query->execute( )	..\Query.php:637
13	1.1491	4960848	Cake\Database\Connection->run( )	..\Query.php:174
14	1.1491	4960888	Cake\Database\Connection->prepare( )	..\Connection.php:272
15	1.1491	4960952	Cake\Database\Driver\Mysql->prepare( )	..\Connection.php:220
```

**Comment by Laykou** [comment]
:+1:  This happens to me as well. Some time ago there was a nice error - something like `Threads is not associated with Posts`.

**Comment by markstory** [comment]
@Laykou That is error I remember as well.

**Comment by lorenzo** [comment]
Closing as there is a pull request to fix this.

**Comment by oldskool** [comment]
:+1: Thanks @lorenzo
