### ISSUE TITLE
Add compare fields validator (to be used like password repeats)

### ISSUE THREAD

**Issue by peterhofman** [cakephp/cakephp#5746]
I thing it should be a good thing to add a "compare fields" validator.
It can be used for password and password_repeat or other examples.

Compare field "a" with "b" and return error if the are equal.
Also good to add this in the docs as a good example.

**Comment by Xety** [comment]
I don't think that a rule is needed for that, because you can do this easily :
```php
->add('password_confirm', [
	'equalToPassword' => [
		'rule' => function ($value, $context) {
			return $value == $context['data']['password'];
		},
		'message' => __("Your password confirm must match with your password.")
	]
])
```

**Comment by peterhofman** [comment]
Would be better to just have a rule, cleaner and easier to use.
It is a rule that will be used a lot.

Or it needs to be added to the docs as an example how you can do it.
Think lots of people will be helped with it.

**Comment by dereuromark** [comment]
I agree that an update to the docs for this example would probably suffice.
@Xety Please compare strings with === :)

**Comment by Xety** [comment]
@dereuromark Thank, i edited my example. ^^

I also agree to add an example in docs. :+1:

**Comment by markstory** [comment]
@peterhofman What would be the ideal way to express a field equality validator to you?

**Comment by robertpustulka** [comment]
I think this rule could be a useful syntactic sugar :+1: 

Something like:
```php
'rule' => ['equalToField', 'pasword_confirm']
```
or even
```php
'rule' => ['equalToField', 'some.path.to.field']
```

**Comment by markstory** [comment]
@robertpustulka Ok, that is similar to what I was considering. I think having a shortcut for this kind of validator is a useful thing to have.

**Comment by peterhofman** [comment]
@robertpustulka Just what i wanted :) Think this will be a good add-on for CakePHP 3 :)

**Comment by robertpustulka** [comment]
@peterhofman Are you able to make a PR? If not, I could try to implement it later.

**Comment by robertpustulka** [comment]
I've looked into this and it seems this rule cannot simply reside in `Cake\Validation\Validation` as `RulesProvider` slices off `$context` from arguments and there is no access to the rest of the `$data` from Validation class anymore...

Any ideas how to do it besides creating another provider just for this single rule?

**Comment by markstory** [comment]
Closing as #5813 is open to address this.
