### ISSUE TITLE
3.0 ExistsIn array_combine() error

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#5752]
When using the `buildRules()` method both of these produce errors:

```php
$Rules->add($Rules->existsIn(
    ['some_id', 'another_id'],
    $this->RelatedTable,
    'Error message goes here.'
));

// ----

$existsIn = new ExistsIn(['some_id', 'another_id'], $this->RelatedTable);
$Rules->add(
    $existsIn,
    ['message' => 'Error message goes here.']
);
```

The error is triggered by the [array_combine()](https://github.com/cakephp/cakephp/blob/3.0/src/ORM/Rule/ExistsIn.php#L81-L84) call on the ExistsIn class and cascades down into the QueryExpression.

Book Reference: http://book.cakephp.org/3.0/en/orm/saving-data.html#foreign-key-rules

**Comment by markstory** [comment]
Are both the columns you're trying to use with ExistsIn part of the primary key? Currently all columns need to be part of the associated table's primary key.

**Comment by sdustinh** [comment]
No, they aren't. That didn't occur to me until after I created this issue. The error doesn't happen if I do something like:

```php
$Rules->add($Rules->existsIn(
    'user_id',
    $this->Users,
    'Message goes here'
));
```

So I suppose this works as intended but as you can see it takes very little to get it to throw a warning. I guess this may be more of a documentation issue unless it would be more beneficial to account for multiple primary keys.

**Comment by ADmad** [comment]
@markstory Is the limitation of only being able to use primary key fields necessary? This prevents someone using the rule for an index made up of 2 (or more) fields for example.

**Comment by lorenzo** [comment]
@ADmad if not checking against a primary key, what would you use?

**Comment by ADmad** [comment]
@lorenzo @markstory Excuse my stupidity. This is for `existsIn` not `isUnique`.

**Comment by markstory** [comment]
Ok, I'll update the docs tonight :smile:

**Comment by markstory** [comment]
Closing as docs pull request is open now.
