### ISSUE TITLE
3.0 - Possibly defunct classes

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#5755]
The following classes aren't documented in the manual. Are they defunct after the last round of changes to validation process and should be removed?

- `Cake\ORM\EntityValidator`
- `Cake\ORM\EntityValidatorInterface`
- `Cake\Validation\ValidatableInterface`

**Comment by markstory** [comment]
I know they are used internally. We should add docs for the interfaces at least.

**Comment by ADmad** [comment]
@markstory Apart from test cases they aren't used internally.
https://github.com/ADmad/cakephp/compare/cakephp:3.0...3.0-defunct-classes
https://travis-ci.org/ADmad/cakephp/builds/48441456

**Comment by markstory** [comment]
Hrm, perhaps double checking with @lorenzo would be best here, but from those changes the code does look unused.

**Comment by lorenzo** [comment]
They are unused inside the framework, but I have not made up my mind yet about their future. The interface can safely stay.

**Comment by markstory** [comment]
If we're not typehinting against the interface does it serve any purpose though?

**Comment by markstory** [comment]
Cleaned up in #5875
