### ISSUE TITLE
collection->extract hasMany properties cannot be extracted

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5758]
```
Hash::extract('{n}.ArticleItems.{n}.store_id');
```

I cannot extract has many properties like
```
$data->combine('article_items.store_id');
```

Is this somehow possible with the current Collection API or do I have to go back to Hash::extract()?

If it's not possible yet, then maybe it's interesting to implement it.

**Comment by lorenzo** [comment]
Can you explain what you would expect to see? Try putting an example of the data and the end result

**Comment by mdlouhy** [comment]
In the $data array there are a lot of articles and every article has many article items. Every article item has one store_id.
I want to get all store_id's of all article items in a simple way.
But I found a pretty good solution I think:
```
$storeIds = $data->reject(function ($row, $key) { return $row->store_id === null; })->combine('store_id', 'store_id')->toArray();
```
