### ISSUE TITLE
3.0 - Problem when generating fixture with an I18n table

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#5761]
Hello,
I think the screen say all :
![screenshot_10](https://cloud.githubusercontent.com/assets/8210023/5930151/13da7704-a68c-11e4-86f3-270100b48a14.png)

I think Cake must add an exception in `Inflector::pluralize()` for all tables who are finished by `I18n`.

**Comment by markstory** [comment]
You can use the `--table` option to use non-plural names. Adding specific workarounds in bake is something I'd like to avoid.
