### ISSUE TITLE
undefined method validatePresence

### ISSUE THREAD

**Issue by KieranYo** [cakephp/cakephp#5763]
After updating to latest version of CakePHP I'm getting this error message when creating a new record.

Error message: Call to undefined method Cake\Validation\Validator::validatePresence() 

code in Model/Table/CommentsTable.php
![image](https://cloud.githubusercontent.com/assets/410142/5935295/32ee5b8e-a6d1-11e4-82a2-7771c8be0ac2.png)

**Comment by dereuromark** [comment]
It is called `requirePresence()` now. Was that baked code? Or just legacy one from pre RC1?

**Comment by KieranYo** [comment]
Previously baked code.

**Comment by dereuromark** [comment]
http://book.cakephp.org/3.0/en/core-libraries/validation.html#requiring-field-presence

**Comment by KieranYo** [comment]
Ok thanks for getting back to me. The validatePresence must have only recently been removed then because it previously worked fine.

**Comment by dereuromark** [comment]
Maybe we should add a note to the migration guide.

**Comment by KieranYo** [comment]
Yes I think that's a great idea.

**Comment by ADmad** [comment]
>  (from version 3 but around 5 months ago)

5 months is a very long time for a version under active development. Besides this numerous other things have changed and it would be better if you just rebake.

It's not practical to document all changes between various dev, alpha, beta, RC releases.
