### ISSUE TITLE
Default config in CakeEmail

### ISSUE THREAD

**Issue by oldskool** [cakephp/cakephp#5764]
Hi guys,

I have a question about CakePHP 2.5.7. I'm a little bit in doubt about the way CakeEmail currently operates. I know it's not mandatory (anymore? I have a feeling it was required before) to have an `app/Config/email.php` file for e-mail configs. Once you do have such a file, it's easy to misinterpret it.

I have such a file in my project and based it off the `email.php.default` example file. In the config, there is one called `$default`, which would suggest that this configuration will be used by default. But that's an invalid assumption. For example, when doing:

```
$Email = new CakeEmail();
$Email->from('admin@example.com')
       ->to('user@example.com')
       ->send('Hello world');
```

This will send the e-mail with the Mail transport, without looking at your EmailConfig at all. However:

```
$Email = new CakeEmail('default');
// or
$Email = new CakeEmail();
$Email->config('default');
```

This will send the e-mail using the `$default` config from `app/Config/email.php`. In my opinion, in this case the name `$default` is very poorly chosen, as it's clearly not a "default" config at all. You still need to tell CakeEmail you want to use it.

The "problem" appears to be in the CakeEmail [constructor](https://github.com/cakephp/cakephp/blob/820d57213907d41dfb3bda2e18906745159320c1/lib/Cake/Network/Email/CakeEmail.php#L344). It has a `$config = null` parameter. I understand this is due to a config not being mandatory, but when you have one this causes it to be ignored entirely. Would it be possible to make the constructor check if an `app/Config/email.php` file is present and if so, use the `default` config from that (also if present)?

This would make much more sense in my opinion.

**Comment by dereuromark** [comment]
@oldskool That's why I have been using a [modified constructor](https://github.com/dereuromark/cakephp-tools/blob/master/Lib/EmailLib.php#L52-L54) since 2.0 :)

**Comment by markstory** [comment]
Closing as there is a pull request up now.
