### ISSUE TITLE
3.0 ORM Subquery not working correctly

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5769]
This relates to my previous issue #4484 which was unable to reporuduce.

I have following setup:
![image](https://cloud.githubusercontent.com/assets/2313005/5938744/24de536e-a6fe-11e4-9702-738ec83fdcc0.png)

```PHP
$article = $this->Articles->get(1,  [
    'contain' => ['Categories' => ['Tags']]
]);
```

The `$article->category->tags` property is not empty in the testing however in the production it is. The reason is that the `SQL query` is wrong, but in test where everything has ID = 1 it works.

This is from DebugKit:
```SQL
SELECT TOP 1 Articles.id AS [Articles__id], Articles.category_id AS [Articles__category_id], Articles.title AS [Articles__title], Articles.color_id AS [Articles__color_id], Categories.id AS [Categories__id], Categories.title AS [Categories__title] 
FROM articles Articles 
LEFT JOIN categories Categories ON Categories.id = (Articles.category_id) 
WHERE Articles.id = 1

SELECT CategoriesTags.tag_id AS [CategoriesTags__tag_id], CategoriesTags.id AS [CategoriesTags__id], CategoriesTags.category_id AS [CategoriesTags__category_id], CategoriesTags.additional_id AS [CategoriesTags__additional_id], Tags.id AS [Tags__id], Tags.label AS [Tags__label] 
FROM tags Tags 
INNER JOIN categories_tags CategoriesTags ON Tags.id = (CategoriesTags.tag_id) 
INNER JOIN (
  SELECT TOP 1 (Articles.id) FROM articles Articles 
  LEFT JOIN categories Categories ON Categories.id = (Articles.category_id) WHERE Articles.id = 1
) Articles ON CategoriesTags.category_id = (Articles.id)
```

As you can see in the second query in the end there is `CategoriesTags.category_id = (Articles.id)` which doesn't seem to be correct. I was able to simulate this with fresh installation of cake. ~~If you need I can share this project, I think you should be reproduce it.~~ Below is my testing repo. So the problem is it works when testing because `category id = 1` and `article id = 1`.

The other thing that frustrates me is: can we rely on the unit testing? Because there are probably all the database IDs set to 1 and they might return good results even if the query is not correct.

// EDIT:
To make it easier here is the repo: https://github.com/Laykou/cakephp-test and
the only app logic is here [PagesController](https://github.com/Laykou/cakephp-test/blob/master/src/Controller/PagesController.php)

**Comment by markstory** [comment]
I think we can rely on the test suite, but perhaps we need to make joins not always 1=>1, and instead do things like 1=>3 so these issues show up.

**Comment by Laykou** [comment]
Yep, that's what I wanted to point out :+1:

**Comment by markstory** [comment]
So the correct subquery query would end in `Articles ON CategoriesTags.article_id = (Articles.id)` ?

**Comment by Laykou** [comment]
There is no article_id in that table. It should be INNER JOIN (SELECT Categories.id FROM articles INNER JOIN categories... )  CAtegories ON CategoriesTags.category_id = Categories.id.

Or something like that

**Comment by lorenzo** [comment]
The test added for #4484 produces this SQL:

```sql
SELECT ArticlesTags.tag_id AS `ArticlesTags__tag_id`, ArticlesTags.article_id AS `ArticlesTags__article_id`, Tags.id AS `Tags__id`, Tags.name AS `Tags__name` FROM tags Tags INNER JOIN articles_tags ArticlesTags ON Tags.id = (ArticlesTags.tag_id) INNER JOIN (SELECT (Articles.id) FROM articles Articles WHERE Articles.author_id in (1,2,3,4)) Articles ON ArticlesTags.article_id = (Articles.id)
```

Which is the correct one. How can we reproduce your error?

**Comment by lorenzo** [comment]
@Laykou Do you have a sql file I can load for the project you uploaded?

**Comment by Laykou** [comment]
The difference is that the test case in #4484 is for
`Authors hasMany Articles hasMany Tags`
while this issue is for
`Articles belongsTo Categories hasMany Tags`

I pushed the init migration into my project.. There is really nothing interesting. btw: I use MSSQL - I don't think it might be a part of the issue, but one never knows :)

**Comment by Laykou** [comment]
I added also the test from #4484 into my repo, so you can compare those two queries:

```SQL
-- My not working (belongsTo with belongsToMany)
SELECT TOP 1 Articles.id AS [Articles__id], Articles.category_id AS [Articles__category_id], Articles.title AS [Articles__title], Articles.author_id AS [Articles__author_id], Categories.id AS [Categories__id], Categories.title AS [Categories__title] FROM articles Articles LEFT JOIN categories Categories ON Categories.id = (Articles.category_id) WHERE Articles.id = 1

SELECT CategoriesTags.tag_id AS [CategoriesTags__tag_id], CategoriesTags.id AS [CategoriesTags__id], CategoriesTags.category_id AS [CategoriesTags__category_id], CategoriesTags.additional_id AS [CategoriesTags__additional_id], Tags.id AS [Tags__id], Tags.label AS [Tags__label] FROM tags Tags INNER JOIN categories_tags CategoriesTags ON Tags.id = (CategoriesTags.tag_id) INNER JOIN (SELECT TOP 1 (Articles.id) FROM articles Articles LEFT JOIN categories Categories ON Categories.id = (Articles.category_id) WHERE Articles.id = 1) Articles
ON CategoriesTags.category_id = (Articles.id)
-- Here the last line from the query is problem


-- The one from #4484 is working (hasMany with belongsToMany)
SELECT TOP 1 Authors.id AS [Authors__id], Authors.name AS [Authors__name] FROM authors Authors WHERE Authors.id = 1

SELECT Articles.id AS [Articles__id], Articles.category_id AS [Articles__category_id], Articles.title AS [Articles__title], Articles.author_id AS [Articles__author_id] FROM articles Articles WHERE Articles.author_id in (1)

SELECT ArticlesTags.tag_id AS [ArticlesTags__tag_id], ArticlesTags.id AS [ArticlesTags__id], ArticlesTags.article_id AS [ArticlesTags__article_id], Tags.id AS [Tags__id], Tags.label AS [Tags__label] FROM tags Tags INNER JOIN articles_tags ArticlesTags ON Tags.id = (ArticlesTags.tag_id) INNER JOIN (SELECT (Articles.id) FROM articles Articles WHERE Articles.author_id in (1)) Articles
ON ArticlesTags.article_id = (Articles.id)
-- Here the last line from the query is OK
```

So you can see the difference

**Comment by lorenzo** [comment]
@Laykou The associations are exactly the same. `Articles belongsTo Categories` is equivalent to `Categories hasMany Articles`.

I will investigate if this issue is actually about SQL Server. What version of sql server are you using?

**Comment by Laykou** [comment]
SQL 2014 but the same issue I experience also on SQL 2008.

You are correct, the associations are exactly the same but the query is built from the other side. You are probably using PostgreSQL right? Do you experience similar problem running `Articles belongsTo Categories`?

And really thank you for your time and help. :smile:

**Comment by lorenzo** [comment]
The query is built from the same side @Laykou :dog:

I tried using mysql, sqlite and postgres. I'll try it in SQL Server as soon as I can

**Comment by lorenzo** [comment]
I'm saying it is the same side as your code example above is:

```php
$article = $this->Articles->get(1,  [
    'contain' => ['Categories' => ['Tags']]
]);
```

Which is the `Article hasMany Categories`

**Comment by Laykou** [comment]
Ahhh right, sorry. I understand. Well then this is really weird. I will try to investigate what's going on. Because I had this issue in my production code and than I was able to simulate it in this very easy project. So I thought there must be some issue in the core ORM.

Well, I tried postgres and I'm having the same issue:
```SQL
 ON CategoriesTags.category_id = (Articles.id)
```
My configuration: Win7, IIS7, PHP 5.6, PostgreSQL 9.3/SQL 2014

**Comment by lorenzo** [comment]
@Laykou Just installed your project, I can see the issue there. Thanks :)

**Comment by Laykou** [comment]
Great. And I realized its not the same. But the picture in the desc of this issue is wrong. The first arrow has opposite direction. :P So there is a difference :)

**Comment by lorenzo** [comment]
Closing as there is a pull request open

**Comment by Laykou** [comment]
@lorenzo There is still problem with SQL server as the ORM produces the `SELECT TOP 1 DISTINCT` syntax which is not valid... however in other DB the `SELECT DISTINCT ... LIMIT 1` works.

As I've [found out](http://stackoverflow.com/questions/20086243/sql-server-top1-with-distinct) the correct syntax for using `limit + distinct` in SQL Server is `SELECT DISTINCT TOP 1`. Or you can use `group by` instead of `distinct` if it is possible in this case.

Here comes the query generated in my test project (mentioned in the description of this issue):
```SQL
SELECT CategoriesTags.tag_id AS [CategoriesTags__tag_id], CategoriesTags.id AS [CategoriesTags__id], CategoriesTags.category_id AS [CategoriesTags__category_id], CategoriesTags.additional_id AS [CategoriesTags__additional_id], Tags.id AS [Tags__id], Tags.label AS [Tags__label] FROM tags Tags INNER JOIN categories_tags CategoriesTags ON Tags.id = (CategoriesTags.tag_id)
INNER JOIN (SELECT TOP 1 DISTINCT (Categories.id) FROM articles Articles LEFT JOIN categories Categories ON Categories.id = (Articles.category_id) WHERE Articles.id = 1) Categories ON CategoriesTags.category_id = (Categories.id)
-- Here is the not-working part in SQL Server
```
