### ISSUE TITLE
3.0 Custom exception handling method name

### ISSUE THREAD

**Issue by glafarge** [cakephp/cakephp#5770]
I used a vendor API (=Mailchimp) which had it's own Exception naming conventions.

I want to change how Mailchimp_List_AlreadySubscribed (exception) is rendered and I used a custom exception handler.

```php
namespace App\Error;

use Cake\Error\ExceptionRenderer;

class AppExceptionRenderer extends ExceptionRenderer
{
    public function mailchimpListAlreadySubscribed($error)
    {
        return 'Oops the user is already subscribed to the list !';
    }
}
```

Never called.

When I saw how CakePHP gets the method name, I understand why it doesn't works...

https://github.com/cakephp/cakephp/blob/e236933544d52e7a16d5c77ecf9834ae38e4c6fa/src/Error/ExceptionRenderer.php#L201
```php
	protected function _method(\Exception $exception) {
        list(, $baseClass) = namespaceSplit(get_class($exception));
        $baseClass = substr($baseClass, 0, -9);
        $method = Inflector::variable($baseClass) ?: 'error500';
        return $this->method = $method;
	}
```

It searches for `mailchimpListAlreadyS()` method instead of the complete name because of `substr()`. 

What do you think about this ?
I have already made a change to it but I don't know if it's a good approach.

**Comment by jadb** [comment]
Closing as #5771 is now open.
