### ISSUE TITLE
3.0 - Inconsistent validation errors array structure

### ISSUE THREAD

**Issue by hdogan** [cakephp/cakephp#5779]
requirePresence and notEmpty rules return numeric keys with messages but other rules return error messages indexed with given `name` parameter of `Validator->add()` method.

It would be nice to have consistent errors array structure (especially for API backend) so it can be easily parsed when developing API client (suppose that API client uses message keys to determine error).

requirePresence error message can be indexed with "presence" or "requirePresence" key and notEmpty error message can be indexed with "empty" or "notEmpty" key as a default. But it can create a conflict if developer use these keys for other rules (i.e. passing 2nd argument to Validator add() method).

```
array(1)
    ["username"]=> 
    array(1) {
        [0]=> // $validator->notEmpty() validation rule
        string(31) "This field cannot be left empty"
    }
}
```

```
array(1)
    ["username"]=>
    array(1) {
        ["customRule"]=> // $validator->add('username', 'customRule', [ .... ]) rule
        string(29) "The provided value is invalid"
    }
}
```

**Comment by hdogan** [comment]
`RulesChecker` returns numeric indexes too.

**Comment by lorenzo** [comment]
Yes, rules in RulesChecker cannot be named for now.

**Comment by markstory** [comment]
We could always remove the names from the validation rules. That would at least make userland validation, rules and generated validation messages consistent.

**Comment by ADmad** [comment]
> Yes, rules in RulesChecker cannot be named for now.

@lorenzo On drawback of RulesChecker not being named is they can't be removed after adding like validator rules set can be.

> We could always remove the names from the validation rules.

@markstory Do you mean totally removing usage of names for validation rules or just remove the name key in errors array?  Totally getting rid of names would mean getting rid of `Validator::remove()` too, which wouldn't be nice.

**Comment by markstory** [comment]
@ADmad Yes if consistency was the most important thing I think removing the names would be prudent. I'm not sure consistency between validation and rules is that important.

What if `notEmpty()` and `requirePresence()` created names like `_empty` and `_required`? We've used `_` prefixed names in a few place as framework provided values. The Router is one example that comes to mind.

**Comment by markstory** [comment]
Closing as `notEmpty()` and `requirePresence()` now include keys for their validation errors.
