### ISSUE TITLE
3.0: Behaviors and validator() issues.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5785]
Removing and adding validation on the fly works just fine.

Either via table:
````
public function validationDefault(Validator $validator) {
                $validator
                        ->add('confirm', 'notEmpty', [
                                'rule' => function ($value, $context) {
                                        return !empty($value);
                                },
                                'message' => __('Please select checkbox to continue.'),
                                //'provider' => 'table',
                                'requirePresence' => true,
                                'allowEmpty' => false,
                                'last' => true,
                        ])
 ```
or directly in the action via `$this->TableName->validator()->add(...)`.

But once you involve a behavior it get's problematic.

### Problem A
Once I use the validator() anywhere before (which should be totally OK to do so), the result of the add is incomplete (only rule with name, no message or anythin else).
```php
        public function confirmable() {
                $Animals = TableRegistry::get('Sandbox.Animals');
                $Animals->validator()->remove('confirm');
                $Animals->addBehavior('Tools.Confirmable');
 
                $animal = $Animals->newEntity();
 
                if ($this->request->is('post')) {
                        $animal = $Animals->patchEntity($animal, $this->request->data);
```
Gets me
```
                'confirm' => object(Cake\Validation\ValidationSet) {
                        [protected] _rules => [
                                'notEmpty' => object(Cake\Validation\ValidationRule) {
                                        [protected] _rule => object(Closure) {
                                               
                                        }
                                        [protected] _on => null
                                        [protected] _last => true
                                        [protected] _message => null
                                        [protected] _provider => 'default'
                                        [protected] _pass => []
                                }
                        ]
                        [protected] _validatePresent => true
                        [protected] _allowEmpty => false
```
I could also not add a rule in the first place and omit the "remove" part above. The result is the same.
This was using the behaviors initialize() method:
```
	public function initialize(array $config) {
		$validator = $this->_table->validator($this->_config['validator']);
		$field = $this->_config['field'];
		$message = $this->_config['message'];
		$validator->add($field, 'notEmpty', [
				'rule' => function ($value, $context) {
					return !empty($value);
				},
				'message' => $message,
				//'provider' => 'table',
				'requirePresence' => true,
				'allowEmpty' => false,
				'last' => true]
		);
		$validator->requirePresence($field);
	}
```

This should work. But then again there is a method exactly for setting up validations, buildValidator().

### Problem B
But once you do anything with validator() in Behavior::initialize() - OR any usage of validator() before in the action - this event isnt even triggered.
So I can't add validation rules via behavior either way in this case.

I think when adding behaviors on the fly, they should always at least try to call the buildValidator() method when there is a validator to work with.
And if validators are modified in initialize it should still do that, or at least make the add() workable there.

**Comment by dereuromark** [comment]
I made a test that proofs the problem:
https://github.com/dereuromark/cakephp-tools/blob/cake3/tests/TestCase/Model/Behavior/ConfirmableBehaviorTest.php#L54-L65

Once you comment that in, it will break the test and the result of the validation rule will be the empty array above, resulting in the different message `'The provided value is invalid'` instead of `'Please confirm the checkbox'`.

**Comment by markstory** [comment]
The `Model.buildValidator` event is fired *when* a validator is built, which you are forcing to occur when you call `validator()`. Why are you not using the event and instead attaching rules during initialize?

**Comment by lorenzo** [comment]
I'll have to ask the same question again. If an event is called "buildValidator" how do you expect it to be called if the validator was already built?

The Table class has enough hooks to prevent you from modifying validators in the initialize method of the table, why do that?

**Comment by dereuromark** [comment]
> Why are you not using the event and instead attaching rules during initialize?

I am not saying one has to use initialize(). Above I noted that I "tried" it that way.
After the "actual" way of doing it failed - using buildValidator().

I expect a behavior to be able to add validation on top - even if validator() has been built before.
How that is done, I don't care at all. I simply tried different ways and all failed.

**Comment by dereuromark** [comment]
Note that my tests which I linked above also use a behavior that already does it the way you propose ( https://github.com/dereuromark/cakephp-tools/blob/cake3/src/Model/Behavior/ConfirmableBehavior.php#L40 ) but as soon as I comment in the commented out code lines it fails (as to be expected by the current way of how things work).

**Comment by markstory** [comment]
What fails? In the test case you linked to the buildValidator event has already been triggered, so it makes sense that the behavior rules are not applied.

**Comment by dereuromark** [comment]
They are applied, just not right. Only the validation rule itself, not its message or any other of its properties, making the result incomplete.

**Comment by markstory** [comment]
Given that you are trying to rely on events that have already happened in the past and won't be re-fired, I'm not sure this will ever work the way you're expecting.

**Comment by ADmad** [comment]
I agree with @markstory. There's nothing to be done here.
