### ISSUE TITLE
3.0 - Add 'status' to Exception Response for REST APIs

### ISSUE THREAD

**Issue by DSchalla** [cakephp/cakephp#5788]
When working the first time with JSON and Cake, I took a look at the behavior on exceptions etc. While it throws an message and a code, it doesn't provide a 'status' field in the response.

Since it is quite common in public APIs and some specifications[1] to provide the status field like 'status: error', 'status: success' , .. it might make sense to add this as default parameter to the ExceptionRendered, if nothing speaks against it. I wanted to get some feedback if I am overseeing a problem/issue with it, when nobody sees an issue with it I would ofc volunteer to make the biggest PR of 1 1/2 Lines. :D

[1] http://labs.omniti.com/labs/jsend

**Comment by markstory** [comment]
You can easily create custom formatted error responses with an ExceptionRenderer. I don't think including the status message in the response really makes sense given you can use the HTTP status code.

**Comment by jadb** [comment]
Even though there are plugins for that (i.e. CRUD), I'd always vote for better default behaviour and less work for users (even without a plugin). So yes, :+1: for this.

Here's a list of [JSON APIs 'standards'](http://stackoverflow.com/a/14538774/2020428).

**Comment by markstory** [comment]
Given that there are multiple competing 'standards', I'd rather not do anything unless it satisfies all the 'standards'.

**Comment by josegonzalez** [comment]
So it's just jsend atm. Are there other "standards" that follow this status/error format? Would we show a message or an object with the code as well?

**Comment by DSchalla** [comment]
The current response behavior follows pretty much JSend, but not completely, since its missing the Status field. That's why I am making the suggestion to follow it completely, since the addition would also not break any other conventions when I am not wrong?

**Comment by dereuromark** [comment]
The status field is pretty useless IMO, as it is a string, and not localized.
It is a nice gadget for dev output when you don't know what status codes are, but other than yet..
I would also rather use the HTTP status code to see if the response is valid or not.
And you could always make your own exception renderer etc.

**Comment by jameswatts** [comment]
I second @dereuromark's point, HTTP status codes exist for a reason. Personally, I think the **Jsend** spec is a poor standard. Making all responses 200 OK and forcing the client to parse the response body to determine if it was successful is bad practice and a needless overhead, even if popular. It's important to make the distinction between the *protocol* and the *transport*, where **Jsend** tries to be both.

**Comment by AD7six** [comment]
> Making all responses 200 OK and forcing the client

The spec does not say that.

> it is advised that server-side developers use both: provide a JSend response body, **and whatever HTTP header(s) are most appropriate to the corresponding body**.

I've found the status field in crud to be pretty useful; but I don't think there's a need for the framework to assume/implement that for users.

**Comment by dereuromark** [comment]
@DSchalla jsend uses 3 status codes: success, error, fail. So you propose to also use that? How would you map that to the actual reponse codes? 5xx => fail, 4xx => error and the 2xx/3xx success?

**Comment by DSchalla** [comment]
I would just revoke the suggestion, since the average feedback is to rely on the Response Code, which is the better suggestion I guess, especially after @dereuromark pointed out that the solution would be quite application related.
