### ISSUE TITLE
Custom validation problem

### ISSUE THREAD

**Issue by Aaarrrgggh** [cakephp/cakephp#5791]
Hi all,

I have a problem with custom validations of Cakephp 3.

Here, my code : 

in usersController.php :

if ($this->Users->save($user, ['validate' => 'register'])) {
// some code
}

in UsersTable.php : 

public function validationRegister(Validator $validator) {
// some code
}

In this case, the validationRegister method is not called. If I rename validationRegister by validationDefault, this method is called and verifications are executed.

Someone has an idea ?

Thanks !

**Comment by jadb** [comment]
You pass `validate` when creating the entity (`newEntity()`).

```php
$user = $this->Users->newEntity($data, ['validate' => 'register']);
if ($this->Users->save($user)) {
...
}
```
