### ISSUE TITLE
Filtering and Routing Problem

### ISSUE THREAD

**Issue by chrisatsc** [cakephp/cakephp#5794]
Hi,
I have an issue with filters and routing -- where the controller is not being found after the filter -- and I'm wondering if perhaps I'm just not doing something correctly.

I have a filter setup on /api, which is expecting a client certificate. Inspecting the request results in the addition of a couple of request params for use with detectors, so these are set appropriately in the filter's beforeDispatch handler and $event->stopPropagation() is called. I am not returning anything from the handler:

    public function beforeDispatch(Event $event)
    {
        $request = $event->data['request'];
        $request->params['isRest'] = true;

        $remote1Requestor = $request->env('HTTP_X_REMOTE1_REQUESTOR');
        $remote2Requestor = $request->env('HTTP_X_REMOTE2_REQUESTOR');
        if ( ! empty($remote1Requestor) )
        {
            DebugLog::log('Remote1 request');
            $request->params['isRemote1'] = true;
            $request->params['isRemote2'] = false;
            $event->stopPropagation(); // No need for more filters
        }
        else if ( ! empty($remote2Requestor) )
        {
            DebugLog::log('Remote2 request');
            $request->params['isRemote2'] = true;
            $request->params['isRemote1'] = false;
            $event->stopPropagation(); // No need for more filters
        }
    }

The URL the remote system is requesting is /api/users/all/245. It passes through the filter as expected.

I have a routing prefix setup:

    Router::prefix('api', function($routes) {
        $routes->connect('/users/all/:id', [ 'controller' => 'Users', 'action' => 'all' ], [ 'pass' => [ 'id' ] ]);
    });

The response I am receiving is:

    "message": "Controller class Users could not be found.",
    "url": "\/api\/users\/all\/245",
    "code": 404

Hoping someone can shed some light on what I am doing wrong here.

**Comment by jadb** [comment]
Where are you defining the `:id` in your `connect()`? You are just passing it but not telling the route how it should match it (using regex):

http://book.cakephp.org/3.0/en/development/routing.html#passing-parameters-to-action

Also, if you are trying to create a REST api, then you should read this: 

http://book.cakephp.org/3.0/en/development/routing.html#resource-routes

**Comment by chrisatsc** [comment]
I sort of figured it out, actually, but not sure it's quite proper. I need to *not* stop event propagation in the filter's beforeDispatch handler, otherwise the controller object never gets properly set.

I'm porting a fairly large CakePHP 1.3 app directly to 3.0. It's been quite a task.

**Comment by jadb** [comment]
I'd call that a re-write :)

I will close this as it's been resolved.
