### ISSUE TITLE
3.0 - TranslateBehavior hide a field if it's empty

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5795]
Hi guys. I ran into a situation where I needed to hide a field if it's `content` was empty in the `i18n` table. The INNER join that was added by using ``Table->find('translations', ['filterByCurrentLocale' => false])`` was producing this:
``
INNER JOIN `i18n` `Posts_title_translation` ON (`Posts_title_translation`.`model` = 'Posts' AND `Posts_title_translation`.`field` = 'title' AND `Posts_title_translation`.`locale` = 'en_us' AND `Posts`.`id` = (`Posts_title_translation`.`foreign_key`))
``
Which would return records that had empty/null `content`.

I added this in `TranslateBehavior`:
```
protected $_defaultConfig = [
 ..
    'hideFieldIfEmpty' => false
];
public function setupFieldAssociations($fields, $table, $model, $strategy)
{
  ..
    foreach ($fields as $field) {
      ..
        $conditions = [
            $name . '.model' => $model,
            $name . '.field' => $field
        ];
        if ($this->config('hideFieldIfEmpty')) {
            $conditions[] = $name . ".content <>''";
        }
      ..
        $this->_table->hasOne($name, [
            'targetTable' => $fieldTable,
            'foreignKey' => 'foreign_key',
            'joinType' => $filter ? 'INNER' : 'LEFT',
            'conditions' => $conditions,
            'propertyName' => $field . '_translation'
        ]);
    }
..
}
```

Which produces the SQL I need:
``
INNER JOIN `i18n` `Posts_title_translation` ON (`Posts_title_translation`.`model` = 'Posts' AND `Posts_title_translation`.`field` = 'title' AND Posts_title_translation.content <>'' AND `Posts_title_translation`.`locale` = 'en_us' AND `Posts`.`id` = (`Posts_title_translation`.`foreign_key`))
``

With the default finder which uses a LEFT join, the field won't be there if there's no translation. If it's INNER, the condition does what you'd expect.

1. Let me know if I should make PR/test if you're ok with this update.
2. Should that content check be the default behavior? Not returning translated fields if there's no translation available?

Thanks

**Comment by markstory** [comment]
What was the scenario where you needed to hide the empty fields? Is this perhaps something that can be turned into a more generic conditions option for the translated columns?

**Comment by patrickconroy** [comment]
If a field has its record in i18n but its `content` is NULL, I'd like that to mean the main record shouldn't come back when using `filterByCurrentLocale` on `findTranslations`. I think it makes sense to have that `content` check to be the default behavior, since getting a nonexistent property of an Entity returns `false`, and when a translated field with empty `content` comes back it would make the value also `false`.

**Comment by markstory** [comment]
Ok, would having a more generally applicable condition options also allow you to do what you want?

**Comment by patrickconroy** [comment]
I think that'd be good actually. Would you think adding values in the `fields` declaration become those values' conditions? Like..
```
fields => [
    'title' => ['locale IN' => ['de', 'zh']],
    'something' => ['content' => "<>''"],
    'somethingelse'
]
```

Or a more general..
```
'fields' => ['title', 'something', 'somethingelse'],
'fieldConditions' => [
    'content' => '<>'''
]
```

I think the first way would give you more options, maybe someone would need to return only titles in those locales but somethingelses with all locales?

**Comment by markstory** [comment]
Yeah I was thinking it could work like the `fieldConditions` example you pasted.

**Comment by patrickconroy** [comment]
Hi @markstory I just started this and realized that with this change the `config['model']` is superfluous. If you set a model it'll use that value..
``
'fields' => ['title'], 'fieldConditions' => ['model' => 'Posts1', "content <> ''"]
``

Is going to be the same as
``
'fields' => ['title'], 'fieldConditions' => ["content <> ''"], 'model' => 'Posts1`
``

If I continue I think the best way to do it is to remove that `model` part in the config and just rely on `fieldConditions`, but it would break anyone's stuff currently using that. Another way to do it is I can check for `config['model']` and set that to `fieldConditions['model']` upon initialize. How do you think I should handle that?
I also see an unearthed bug in `beforeSave` that won't properly respect the set `model` when saving records which I'll fix.

**Comment by patrickconroy** [comment]
This is what I have right now.. https://github.com/patrickconroy/cakephp/commit/39abf18dbf78ad3ce96c0823fd3a689012d1aaef 

The is_numeric part in `setupFieldAssociations` is the only way I could think of to allowing 
``"content <>''"`` since it can't be `'content' => "<>''"` but I also wanted to allow more normal stuff like `'content' => 'exactly this one'`.

**Comment by markstory** [comment]
I would name `fieldConditions` to be just `conditions` as that is more commonly used across the framework. I would leave the model option as it stands, removing it will be confusing, and cause errors when people want to add additional conditions. Wouldn't

```php
'conditions' => ['content <>' => '']
// or
'conditions' => ['content !=' => '']
```
Cover the case you are hoping to address?

I think what you have is looking good otherwise.

**Comment by patrickconroy** [comment]
Thanks @markstory I just updated that. I'm not sure how removing the `model` part would cause errors though, since you'd be able to add them in the conditions.. `'conditions' => ['model' => 'Posts']` .. but maybe I'm missing something there.

**Comment by patrickconroy** [comment]
This has been merged, closing this.
