### ISSUE TITLE
3.0 SQLServer MultipleActiveResultSets

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5797]
Hi, I have this error when iterating `bufferResults(false)` and doing some query inside the loop.

```
The connection cannot process this operation because there is a statement with pending results.
To make the connection available for other queries, either fetch all results or cancel or free
the statement.  For more information, see the product documentation about the
MultipleActiveResultSets connection option.
```

```PHP
$articles = $this->Articles->find()->bufferResults(false);
foreach ($articles as $article) {
    $this->Articles->updateAll( ... );
    TableRegistry::get('Tags')->find();
    ...
}
```

```
Win7, PHP 5.6, CakePHP 3.0, SQLServer 2008 and 2014
```

According to the documentation it has something to do with the `MultipleActiveResultSets=false` parameter in the connection, but setting it to true might not solve the problem. I'm reporting this also because I haven't had this problem until I updated the cake code via composer four days ago.

I saw there were some failing tests on appveyor due to this, but maybe you can advise more or how to solve such problems.

The use case is that this script is a cron job which iterates over 300 000 rows so it's quite unwise to load it into memory (if possible at all) and then I need to load some extra information from other tables for each row.

**Comment by markstory** [comment]
This isn't just a SQLServer issue, its also an issue on MySQL. You cannot start additional queries when there are open cursors.  The changes in the last four days were to fix accidentally omitted options from SqlServer query execution.

**Comment by lorenzo** [comment]
There is no real fix for this other than manually creating a new connection and executing the statement separately. Closing as we have to live with the limitations PDO imposes us.
