### ISSUE TITLE
3.0 Validation:  Muliple column as unique

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/cakephp#5802]
if I have declared collectively 'Column 1' and 'Column 2' and 'Column 3' as Unique index , so there should be a rule  'ValidateMultipleUnique' same as  'validateUnique'

**Comment by ADmad** [comment]
Use `RulesChecker::isUnique()` which takes array of fields as argument.

**Comment by ib-anurag-mishra** [comment]
Thanks Admad
