### ISSUE TITLE
Family tree

### ISSUE THREAD

**Issue by Avemaar** [cakephp/cakephp#5803]
I am fresh in the cakephp.I would like to implement a family tree structure.
I store in the database the id,father_id,mother_id.
I know the tree behavior but it is not fit for it, cuz I can not use the left and right fields in that case.
Is there a way to this which is built in cakephp or should i write a code myself?

thank you for your help

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
