### ISSUE TITLE
fullBase option for HTML image helper

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5804]
Hello,
Did you intentionnaly choose the option 'fullbase' for '$this->Html->image("logo.png", ['fullBase' => true]);' where as other helpers use '_full'?

**Comment by ADmad** [comment]
The key `_full` is used in url arrays, while the second param of HtmlHelper::image() is not a url.

**Comment by caBBAlainB** [comment]
ADmad, 
It seems that '_full' in:
$this->Html->link('Dashboard',['controller' => 'Dashboards', 'action' => 'index', '_full' => true]);
(Doc: *Use '_full'=>true option for absolute URLs:*)

has the same meanning than 'fullbase' in:
$this->Html->image("logo.png", ['fullBase' => true]);
(Doc: *If you are creating images in emails, or want absolute paths to images you can use the fullBase option:*)

I.e. To create a full based url. no?

**Comment by dereuromark** [comment]
@caBBAlainB In the link() and url() methods it is directly part of the URL array and as such needs the underscore to avoid clashes with user defined keys.

For image() it is simply an option.
So not sure if that really needs to be unified.

**Comment by caBBAlainB** [comment]
Ok, it was just to know if it was intentional or a mistake.
