### ISSUE TITLE
3.0 - TimeHelper should display invalid if date is null

### ISSUE THREAD

**Issue by erichowey** [cakephp/cakephp#5807]
In Cake3 using the TimeHelper in the following manner:

```php
<?= $this->Time->format($set->set_start_date, 'M/d/Y', 'Start Date Not Set', $timezone) ?>
```

There will be times where ```$set->set_start_date``` is null if the date hasn't been decided on in my app. In this case, I believe that ```$invalid``` would be the most appropriate data to display on the screen if the entity is null. Instead of ```$invalid``` being displayed, ```Time::now()``` is being displayed. I can propose a fix for this and update the docs if I'm correct of the desired behavior of TimeHelper in this case.

**Comment by jadb** [comment]
Go ahead. Unless others oppose it, I think that you are correct about the desired behaviour. 

Looking forward to your PR.

**Comment by dereuromark** [comment]
@erichowey I agree with you.

The current `format()` is just a very lazy way of saying `format(new Time())`.
So always providing some time object when saying "now" is almost no overhead and will make the method's behavior more transparent - just as you suggested.

**Comment by erichowey** [comment]
Thanks for the feedback guys! PR created. Let me know if it meets your standards :smile_cat:

**Comment by markstory** [comment]
Related to #5809

**Comment by dereuromark** [comment]
Closing as a PR is now open.
