### ISSUE TITLE
joinData order problem

### ISSUE THREAD

**Issue by mrezagolestan** [cakephp/cakephp#5808]
hi.
i want to have join data in my XREF table but after patchEntity entity order will be changed and my join data assigned to incorrect entity.

```php
$estate = $this->Estates->newEntity($this->request->data);
$specifications = [
                'estates_spec_values' => [
                    '_ids'=>[8,7]
                ]
            ];
$this->Estates->patchEntity($estate, $specifications);
 $estate->estates_spec_values[0]->_joinData = new EstatesSpecValue(['value' => 4]);
            $estate->estates_spec_values[1]->_joinData = new EstatesSpecValue(['value' => 3.5]);
```

i expect to record with id 8 has 4 value and other 3.5 but after patchEntity entity order by id and 8 id change to second entity and 7 goes to first entity and joinData assigment are incorrect.
what can i do?

**Comment by mrezagolestan** [comment]
@dereuromark what is solution?!!!!

**Comment by markstory** [comment]
Can you not make the _joinData part of the $specifications data instead of relying on implicit ordering?

**Comment by mrezagolestan** [comment]
it is the best choice, but i didn`t know how to do that.
and didn`t find any document for that

**Comment by markstory** [comment]
Ok, I can add an example to the documentation.

**Comment by mrezagolestan** [comment]
where in the document i can found that?!!

**Comment by markstory** [comment]
You can't because I've not written it yet.

**Comment by markstory** [comment]
Docs pull request up now.

**Comment by markstory** [comment]
I bet id is not in he _accessible fields.

**Comment by mrezagolestan** [comment]
you said right. but when i write code in this form:

```php
        $data = [
            'realstate_id' => 1,
            'area_id' => 1,
            'user_id'=>1,
            'esspecvalues' => [
                ['id'=>2],
                ['id'=>1]
            ]
        ];
        $estate = $this->Estates->newEntity($data);

        echo($estate);
        $this->Estates->save($estate);
```

my $estate output is in this form:

```php
{
    "realstate_id": 1,
    "area_id": 1,
    "user_id": 1,
    "esspecvalues": [
        {
            "id": 2
        },
        {
            "id": 1
        }
    ]
}
```
ids comes into entity but relation part o f entity is not complete (not including other fields). so it is not saved.

**Comment by markstory** [comment]
So are you wanting to add/modify only some of fields in to the _joinData?

**Comment by mrezagolestan** [comment]
i want to add some field to _joinData. my XREF table that now is esspecvalues_estates contain value field that should be field when belongstomany records inserted in this table

**Comment by mrezagolestan** [comment]
i`m coding in estates controller
estates table:
```php
id,realstate_id,user_id,area_id
```
esspecvalues is some specifications for estates that should be inserted with estates record.

esspecvalues
```php
id,esspecattributes_id,title
```


and esspecvalues_estates is XREF table for belongstomany that i`m trying to insert my data
```php

id, estate_id,esspecvalues_id,value
```

value is my _joinData

**Comment by markstory** [comment]
Ok, I tested the documented code and it works as I would expect, here is an interactive console showing what I did.  Given that Bookmarks belongsToMany Tags and the `bookmarks_tags` table has a `starred` column:

```php
[1] app > $data = ['title' => 'testing', 'url' => 'http://example.com', 'user_id' => 1, 'tags' => [['id' => 1, '_joinData' => ['starred' => 1]]]];
// array(
//   'title' => 'testing',
//   'url' => 'http://example.com',
//   'user_id' => 1,
//   'tags' => array(
//     0 => array(
//       'id' => 1,
//       '_joinData' => array(
//         'starred' => 1
//       )
//     )
//   )
// )
[2] app > $bookmarks = \Cake\ORM\TableRegistry::get('Bookmarks');
// object(App\Model\Table\BookmarksTable)(
//
// )
[3] app > $b = $bookmarks->newEntity($data, ['associated' => ['Tags._joinData']]);
// object(App\Model\Entity\Bookmark)(
//
// )
[4] app > $bookmarks->save($b);
// object(App\Model\Entity\Bookmark)(
//
// )
[5] app >
```

After this the `bookmarks_tags` table has the correct data including the starred column.

**Comment by mrezagolestan** [comment]
it means you had 1 record inserted in 'bookmarks_tags' ?

i do the same but i hadnt expected result

```php
        $estates = \Cake\ORM\TableRegistry::get('Estates');
        $data = [
            'realstate_id' => 1,
            'user_id' => 1,
            'area_id' => 1,
            'esspecvalues' => [
                [
                    'id' => 1,
                    '_joinData' => [
                        'value' => 'test'
                    ]
                ]
            ]
        ];


        $estate = $estates->newEntity($data, ['associated' => ['Esspecvalues._joinData']]);

        echo($estate);
        $estates->save($estate);

```

so i think it is a problem in the entity or table prefrences.
but what it can be? i add id to accessible fields too

**Comment by mrezagolestan** [comment]
tnx @markstroy i got that. i use your code with bookmarks+tags example and change it step by step to my case and it works.
thank you man ;)
