### ISSUE TITLE
2.6 - Error views from plugin

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#5816]
I had posted on StackOverflow for a long time. I try to ask here, although it isn't the best place.

I'm trying to use views error from a plugin, in other words common error views for all my apps. So, the error views can be found here:

`app/Plugin/MyPlugin/View/Errors/`

Instead, I would use the layout from the application ("default.ctp" or better "error.ctp"). Only the error views should be taken from the plugin.

I tried, but I could not find any examples, and I understand that I maybe have to rewrite the ExceptionRenderer class, but I have not found good examples. Can anyone give me some tips?

Thanks

**Comment by markstory** [comment]
You won't find this in the docs as its not something that really belongs there. You can probably achieve what you want with a custom exception renderer. You will want to change the `template` property, to contain something like `MyPlugin.$name`.
