### ISSUE TITLE
2.7 Backport the v3 Flash component

### ISSUE THREAD

**Issue by tanuck** [cakephp/cakephp#5823]
Title is fairly self explanatory. Do you think we could back-port the custom flash methods to v2? Maybe not a new component but possibly adding the `__call()` method to the Session component so we can do the following:

```php
$this->Session->successFlash();
$this->Session->errorFlash();
```
Thanks

**Comment by ADmad** [comment]
@tanuck Do you want to give it a go?  There's no need to make any changes to the SessionComponent. Just make a new FlashComponent similar to 3.0's FlashComponent.

**Comment by dereuromark** [comment]
@tanuck Actually, I had the same ideas. But I would rather use the 3.x way directly, by backporting the FlashComponent and FlashHelper.
So the syntax would be

    $this->Flash->success($message);
    $this->Flash->error($message);

etc.

Refs [2.7-Roadmap](https://github.com/cakephp/cakephp/wiki/2.7-Roadmap) + https://github.com/dereuromark/cakephp-shim#flashcomponent-and-flashhelper and my implementation of a stackable version @ https://github.com/dereuromark/cakephp-tools/blob/master/Controller/Component/FlashComponent.php

**Comment by tanuck** [comment]
Well I had extended the SessionComponent in my own app for this reason. But I can understand the logic for moving it to a new Component. Having the Helper as well would be useful.

I guess it just needs a port of those 2 classes from 3.x and add 2.7 compatible tests?

**Comment by tanuck** [comment]
@dereuromark yeah I totally agree! I can take a look at porting the component + helper...

**Comment by markstory** [comment]
:+1: to an API compatible backport. It will help people ease into 3.x and fits well with the goals of 2.7.

**Comment by burzum** [comment]
I'm nearly done with the component. :) Just one test fails, trying to fix it at this moment.

**Comment by markstory** [comment]
Pull request #5855 covers this I think.

**Comment by markstory** [comment]
Closing as #5855 has been merged.
