### ISSUE TITLE
[RFC] 3.0 - Add to HtmlHelper::link() an activeClass option

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#5827]
Sounds good? It would help save some unecessary comparisons for menus generation.

* The 'activeClass' option is set
* The current link generated by HtmlHelper::link() is compared to $this->request->here
* If they are equal, the defined 'activeClass' would be merged with previous defined 'class' and then applied to the link

Got it done here.
If approved I can do the pull request.

**Comment by markstory** [comment]
Would every link start comparing against the current URL?

**Comment by andtxr** [comment]
No, the link is compared if the 'activeClass' option is defined.

**Comment by markstory** [comment]
Would query string arguments participate in the matching? If they did it would be pretty easy to cause the active link highlighting to break.

**Comment by ADmad** [comment]
I don't think we should try HtmlHelper:url() into a lazy man's menu helper.

**Comment by dereuromark** [comment]
I guess we can all agree that the Html helper should stay the simple and generic part, and that you should rather create a specific Menu helper that leverages the Html one to generate the links, not the opposite way.

This wheel has already been invented a few times this way, by the way:
https://github.com/FriendsOfCake/awesome-cakephp#navigation (See plugins listed here)

**Comment by andtxr** [comment]
I have considered the following params for matching:

* prefix name
* plugin name
* controller name
* action name

So there is no crash about params, pagination, etc. But would be necessary to compare full URLS sometimes. Maybe an array like that should work::

```php
'active' => [
    'class' => 'current-class',
    'full_url' => true
]
```

**Comment by jadb** [comment]
No need for this in HtmlHelper. As others have mentioned, that type of functionality is better left for plugins to implement.
