### ISSUE TITLE
Run tests form composed plugin fails

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#5828]
It seems it's not possible to run tests from a plugin loaded by composer. I found out by running tests from my own plugins. I tried it by cake's plugins too, but failed again.

Examples:

- I tried to test the plugin DebugKit: `vendor\cakephp\debug_kit>phpunit tests\TestCase\Controller\PanelsControllerTest.php`

```
Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\path\vendor\cakephp\debug_kit\tests\bootstrap.php on line 21
```

- I tried to test the plugin Bake: `vendor\cakephp\bake>phpunit tests\TestCase\Shell\BakeShellTest.php`

```
Fatal error: Class 'Bake\Test\TestCase\TestCase' not found in C:\path\vendor\cakephp\bake\tests\TestCase\Shell\BakeShellTest.php on line 23
```

- I tried to run tests from my own plugin: `vendor\cakemanager\cakephp-cakemanager>phpunit tests/TestCase/Controller/UsersControllerTest.php`

```
Exception: Referenced fixture class "CakeManager\Test\Fixture\UsersFixture" not found. Fixture "plugin.cake_manager.users" was referenced in test case "CakeManager\Test\TestCase\Controller\UsersControllerTest". in [C:\path\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 180]
```

It looks like its not possible to run tests from a 'composed' plugin?

**Comment by dereuromark** [comment]
You need to
- nagivate into the plugin
-. run "composer update"
- then run "phpunit"

You probably failed to do the 2nd.

**Comment by bobmulder** [comment]
Hi Mark,

The plugins are up-to-date. I also runned the `phpunit`-command. See:

_I tried to run tests from my own plugin: `vendor\cakemanager\cakephp-cakemanager>phpunit tests/TestCase/Controller/UsersControllerTest.php`_

**Comment by dereuromark** [comment]
Please re-read my previous comment.

**Comment by bobmulder** [comment]
So I need to do an `composer update` on my plugin-folder? I'll check it out, sorry ;)

**Comment by bobmulder** [comment]
Running the `composer update` command gives:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Running the `phpunit` command:

```
Configuration read from C:\xampp\htdocs\projects\freshmedia\makelshop\vendor\cakemanager\cakephp-cakemanager\phpunit.xml

Exception: Referenced fixture class "CakeManager\Test\Fixture\RolesFixture" not found. Fixture "plugin.cake_manager.roles" was referenced in test case "CakeManager\Test\TestCase\Controller\Admin\RolesControllerTest". in [C:\path\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 180]
```

**Comment by dereuromark** [comment]
I think we really should add this part to the documentation @ http://book.cakephp.org/3.0/en/development/testing.html#running-tests
From there it is really not clear that this is necessary.

Regarding your issue: Are you sure that the plugin you are using is up to date? Looks like that is the reason it fails, not CakePHP.

**Comment by bobmulder** [comment]
Yeah that would be great.

My app and plugin is up-to-date. If I run the plugins tests on it's source (location where I build the plugin) the tests pass.

Still not working :S. Are you sure it is possible, because I am not able to run the tests of the Bake-plugin and DebugKit-plugin....

**Comment by jadb** [comment]
@bobmulder - @dereuromark asked you follow some specific steps.

The second step with `composer update` should be `composer install` and you should run this in every plugin's folder (the plugins you want to test of course, or any other PHP library you get using composer).

```
$ cd vendor/cakephp/bake
$ composer install
$ phpunit
```

This works flawlessly for me.

**Comment by jadb** [comment]
Remember, you're running both commands (composer and phpunit) from within the plugin's directory under vendor.

**Comment by dereuromark** [comment]
@jadb Plugins don't have a lock file, thus using install is as good as using update directly.

**Comment by jadb** [comment]
Right - and I don't think that was the reason he wasn't able to run the tests either. I just mentioned it as it is a habit I have to advice people to stay on the safe side of things as the more experienced ones will know which to use when they are reading (not just this issue but when helping on composer matters in general).

**Comment by dereuromark** [comment]
That is a fair point. But in this case using install can result in pulling outdated repos. Once you already have a (oudated) tmp lock file in your system it will only grab those from there on, and as such the tests might be incorrect after a short while.
Thus it is better to always stick to update for testing envs, and leaving the rest up to composer documentation and the responsibility of each developer.

**Comment by jadb** [comment]
@dereuromark when inside a plugin directory, running install will install the versions defined in the plugin's composer.json, ignoring the root dir's lock file - that is the safest way to run tests and composer in general IMO (unless you know exactly what you are doing of course).

**Comment by dereuromark** [comment]
I am talking about the generated lock file inside each plugin dir - as they are independent things at this point.

**Comment by dereuromark** [comment]
Closing as user dev error.

**Comment by ravikanthhtnakivar** [comment]
hi sir,
i followed the above comments but iam not able to run the tests.
