### ISSUE TITLE
3.1 ORM Order by in subquery

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5830]
This is a minor bug.

I've noticed that at least in SQL server it is forbidden to use `ORDER BY` clause inside of subquery.
The error:

```
SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]The ORDER BY clause is
invalid in views, inline functions, derived tables, subqueries, and common table expressions,
unless TOP, OFFSET or FOR XML is also specified.
```

This might be the usecase: using the query as the main query and then as the subquery

``` PHP
$users = $this->Users->find()->order(['name']);

$usersSub = clone $users;
$usersSub->select(['id'], true);
$articles = $this->Articles->find()->where(['user_id IN' => $usersSub]);

$this->set(compact('users', 'articles'));
```

So the ORM should probably remove the `order by` **if** there is no `limit` nor `offset`. What do you think?

**Comment by dereuromark** [comment]
Sounds like a good idea to remove it if that makes the query valid - should be an easy fix.

@lorenzo s feedback would be valuable here, as to if this should be fixed or improved.

**Comment by inoas** [comment]
I'd personally not remove it:
- Works on other RBMS - doesn't it, so it would be a specific fix
- May thus work on future MSSQL builds
- `...unless TOP, OFFSET or FOR XML is also specified.` already points at a solution IMHO and says that it can be valid

A quick search brought this up: http://stackoverflow.com/questions/985921/sql-error-with-order-by-in-subquery
