### ISSUE TITLE
afterFind() called twice with PaginatorComponent

### ISSUE THREAD

**Issue by kongkannika** [cakephp/cakephp#5835]
Paginator Component called `afterFind()` 2 times.

* `find('all')`
* `find('count')`

In `ArticlesController` :

```
public function index() {
    $this->Article->recursive = 1;
    $articles = $this->Paginator->paginate();
    $this->set(compact('articles'));
}
```

In `Article` Model :

```
function afterFind($results, $primary = false) {
	if ($primary) {
		debug(count($results));
	}
	return $results;
}
```

The result will be :

```
/thmeythmey/Model/Article.php (line 43)
(int) 20
/thmeythmey/Model/Article.php (line 43)
(int) 1
```

**Comment by ADmad** [comment]
Given that it makes two finds calls it's expected that afterFind() is called twice. The find('all') fetches the records for current page and the find('count') is done to get total number of records which is required to generate the paging links.

What's your issue?

**Comment by kongkannika** [comment]
Why `find('count')` need to callback to method `afterFind()`? It means nothing there.

**Comment by dakota** [comment]
@kongkannika some people do use it even for a find('count').

**Comment by dereuromark** [comment]
Closing as there is no issue here. The afterFind() needs to both function for find(all) and find(first) to have a consistent behavior if used.
