### ISSUE TITLE
App::_packageFormat returning incorrect Vendor paths when using Composer

### ISSUE THREAD

**Issue by snsmurf** [cakephp/cakephp#5838]
Tried this on CakePHP 2.5.8 and the latest 2.6.1 and issue occurs on both.

We were using this to load in the composer autoload file:
App::import('Vendor', 'autoload');

Used this as we were familiar with it's implementation from non-composer based CakePHP sites we manage.
However it cannot find the root vendor directory due to that the App::_packageFormat() method returning the vendor paths incorrectly. For the current site it returned the following pages for Vendor:

	[Vendor] => Array
	(
		[0] => /var/www/app/Vendor/
		[1] => /var/www/Vendor/cakephp/cakephp/vendors/
	)

Would expect the second one in this instance to be `/var/www/Vendor` and not `/var/www/Vendor/cakephp/cakephp/vendors/` in order to map properly, but it seems it just generates it relative to the location of CakePHP which has obviously now changed when installing via Composer.

Given I'm not fully fluent on Cakes Core yet I wouldn't really know what to suggest as the best potential fix so hopefully someone with better Core knowledge might be able to give a solution.

**Comment by markstory** [comment]
You shouldn't use App::import() for basic files like `/vendor/autoload.php`. require is simpler and faster.

**Comment by snsmurf** [comment]
FYI, despite being tagged for 2.6.2 it doesn't look like the path was actually fixed.

**Comment by markstory** [comment]
I closed because you shouldn't be using App::import() to load vendor/autoload. Just use require.

**Comment by snsmurf** [comment]
I have done but the issue is that App::build is still returning an incorrect vendor path.

    /var/www/Vendor/cakephp/cakephp/vendors/

That should surely be returned as 

    /var/www/Vendor/

The vendors directory inside app folder is being returned correctly but the top level Vendors cannot be accessed due to this bug.

**Comment by markstory** [comment]
Ah ok, I get what you're saying now.
