### ISSUE TITLE
Error: Class 'App\Controller\NotFoundException' not found 

### ISSUE THREAD

**Issue by jrobertsvml** [cakephp/cakephp#5847]
```
public function syncRackspaceDns($client = null) {
    	if(is_null($client)){
			throw new NotFoundException('Invalid Rackspace client');
        }
```

**Comment by josegonzalez** [comment]
You need to call `use Cake\Network\Exception\NotFoundException` at the top of your class, or use the fully-qualified namespace when throwing it:

```php
throw new \Cake\Network\Exception\NotFoundException('Invalid Rackspace Client');
```

Classes not specified in either of these ways will default to being loaded from the namespace of the current class.

**Comment by jrobertsvml** [comment]
Thank, Jose. Got it working now.
