### ISSUE TITLE
_translateTime function in I18n returns a (too deep nested) array

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#5852]
The _translateTime function in I18n returns (nested) array since the introduction of context-support (CakePHP 2.6.x) in translate. The function returns an array instead of a string (and a nested array instead of a normal array): array('' => 'string') instead of 'string'

If it is possible to pass a context to a translation of time then the translate function should pass a context parameter to _translateTime, so _translateTime can use this for the lookup in the translation strings.

Otherwise we could better skip the extra level of nesting for the context in the translation strings array ($_domains) for strings in LC_TIME category.

**Comment by markstory** [comment]
Closing as #5854 is open.
