### ISSUE TITLE
edit action fails on saving empty field with integrity check

### ISSUE THREAD

**Issue by pHAlkaline** [cakephp/cakephp#5853]
I have 
   public function buildRules(RulesChecker $rules) {
      $rules->add($rules->existsIn(['supplier_id'], 'Suppliers'));
    }

but supplier_id is not required

->add('supplier_id', 'valid', ['rule' => 'numeric'])
->allowEmpty('supplier_id')

On edit action, supplier_id has a value but when i try to change this field to empty as i save it this will fail.

this seems to be omission when dealing with nullable columns.
http://stackoverflow.com/questions/28299012/cakephp-3-fails-on-edit-action-saving-empty-field-with-integrity-check

**Comment by markstory** [comment]
How would you expect to declare that an exisitsIn rule was optional?

**Comment by ADmad** [comment]
Would need an extra argument `$allowNull` for `ExistsIn`.

**Comment by lorenzo** [comment]
I would read the nullable flag from the schema for that property

**Comment by markstory** [comment]
I can implement reading the nullable schema check.

**Comment by pHAlkaline** [comment]
until you implement it , i made this temporary solution , it worked for me ... 
at ExistsIn.php
public function __invoke(EntityInterface $entity, array $options){
......................
line 80 i added -> 
$source=$options['repository'];
        foreach ($this->_fields as $key=>$field){
                if ($entity->$field===null && $source->schema()->column($field)['null']){ 
                        unset($this->_fields[$key]);
                }
        }
        if (count($this->_fields)==0){
                return true;
        }
...................
}

and maybe is needed a similar for IsUnique.php i'm not sure..

**Comment by markstory** [comment]
Thanks for the help @pHAlkaline I've got a pull request open.
