### ISSUE TITLE
3.0 Saving HasOne / HasMany associations

### ISSUE THREAD

**Issue by sarrala** [cakephp/cakephp#5862]
I'm not sure if even using this right way but for me it seems that current 3.0 docs suggests that this should work.

### Tables I used:

ParentsTable init `hasOne('ChildValues', ['foreignKey' => 'parent_id']);`
ChildValuesTable init `belongsTo('Parents', ['foreignKey' => 'parent_id']);`

### What I did:

```php
$data = [
    'name' => 'FooBar',
    'child_value' => [
        'data' => 'Testing'
    ]
];

$entity = $parentTable->newEntity();
$entity = $parentTable->patchEntity( $entity, $data, [
    'associated' => ['child_value']
]);
$parentTable->save( $entity, ['associated' => ['ChildValues']] );
```

### Expected results / Actual results:
I excepted this to save both parent and childvalues but it will only save parent discarding child data.

### How did I make it do what I wanted it to do:
To make it save children data I made following addition to `ORM\Associations\HasOne::saveAssociated(...)` just before it checks for `empty($targetEntity)`:

```php
if (is_array($targetEntity)) {
    $targetEntity = $this->target()->newEntity($targetEntity);
}
```

I tried to strip it down to very basic form but there's also question about this in StackOverflow with little bit additional information: http://stackoverflow.com/questions/28393995/cakephp-3-saving-hasone-association

**Comment by markstory** [comment]
Your patchEntity call is wrong. You have to use the alias name, not the propert name in the associated option list.

**Comment by sarrala** [comment]
Ok, I've changed patchEntity to:

```php
$entity = $parentTable->patchEntity( $entity, $data, [
    'associated' => ['Parents.ChildValues']
]);
```

after that HasOne still gets plain array and requires Entity to be created or it wont push row to db.
Giving it only `'ChildValues'` as association won't work at all.

**Comment by markstory** [comment]
I am pretty certain that hasMany/hasOne saving works as there are tests covering it. I will double check though.

**Comment by markstory** [comment]
I just tried hasOne locally, and everything worked as expected:

```php
[1] app > $data = ['email' => 'mark@example.com', 'password' => 'secret', 'profile' => ['twitter' => 'mark_story']];
// array(
//   'email' => 'mark@example.com',
//   'password' => 'secret',
//   'profile' => array(
//     'twitter' => 'mark_story'
//   )
// )
[2] app > $users = \Cake\ORM\TableRegistry::get('Users');
// object(App\Model\Table\UsersTable)(
//
// )
[3] app > $user = $users->newEntity($data, ['associated' => ['Profiles']]);
// object(App\Model\Entity\User)(
//
// )
[4] app > $users->save($user, ['associated' => ['Profiles']]);
// object(App\Model\Entity\User)(
//
// )
[5] app > $fetch = $users->get($user->id, ['contain' => ['Profiles']]);
// object(App\Model\Entity\User)(
//
// )
[6] app > $fetch->profile->twitter;
// 'mark_story'
```

The code I used is [can be found in this gist](https://gist.github.com/markstory/8f1d4e24a3d0609ad79d).

**Comment by sarrala** [comment]
I've found actual problem which was validator error, but still I feel that framework should take care of this.

Validation error happened on ChildValues.parent_id because it should be set (_shouldn't it skip this rule when creating with parents?_):

```php
[
     'child_value' => [
        'parent_id' => [
            '_required' => 'This field is required'
        ]
    ]
]
```

Validation rule that prevented creating child row, this rule should be in place when creating child rows on their own but should be omitted if parent fk row is associated for create:
```php
->add('parent_id', 'valid', ['rule' => 'numeric'])
->requirePresence('parent_id', 'create')
->notEmpty('parent_id')
```

Why I think that framework should take care of this is simply that parent_id is fk and should not be required when data for new parent row is present, you'll get all required data if parent is created successfully and after that above validation rule should pass without any modifications:

```php
$this->belongsTo('Parents', [
    'foreignKey' => 'parent_id'
]);
```

There's more code, validators, tables, how I finally solved this one:
http://stackoverflow.com/q/28393995/1338846

**Comment by ADmad** [comment]
@sarrala Use [application rules](http://book.cakephp.org/3.0/en/orm/saving-data.html#application-rules) instead of validators for foreignkey check.
