### ISSUE TITLE
2.x on update data to database there are 3 other queries before save it to database mysql

### ISSUE THREAD

**Issue by kongkannika** [cakephp/cakephp#5872]
After run `$this->Model->save();` to update data to MySQL, we expect that there are 2 queries will be executed. but there are 5 queries in the log. see an example of my scripts.

Method in `NotificationsController`
```
public function edit($id = null) {
	if (!$this->Notification->exists($id)) {
		throw new NotFoundException(__('Invalid notification'));
	}
	if ($this->request->is(array('post', 'put'))) {
		if ($this->Notification->save($this->request->data)) {
			$log = $this->Notification->getDataSource()->getLog(false, false);
			debug($log);
			exit;
			$this->Session->setFlash(__('The notification has been saved.'), 'default', array('class' => 'message success'));
			$this->redirect(array('action' => 'index'));
			return;
		}
		else {
			$this->Session->setFlash(__('The notification could not be saved. Please, try again.'));
		}
	}
	else {
		$options = array('conditions' => array('Notification.' . $this->Notification->primaryKey => $id));
		$this->request->data = $this->Notification->find('first', $options);
	}
}
```

Log in browser :
```
/thmeythmey/Controller/NotificationsController.php (line 105)

array(
	'log' => array(
		(int) 0 => array(
			'query' => 'SELECT COUNT(*) AS `count` FROM `thmeythmey`.`tbl_notifications` AS `Notification`   WHERE `Notification`.`id` = 6',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 0
		),
		(int) 1 => array(
			'query' => 'SELECT COUNT(*) AS `count` FROM `thmeythmey`.`tbl_notifications` AS `Notification`   WHERE `Notification`.`id` = 6',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 0
		),
		(int) 2 => array(
			'query' => 'SELECT COUNT(*) AS `count` FROM `thmeythmey`.`tbl_notifications` AS `Notification`   WHERE `Notification`.`id` = 6',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 0
		),
		(int) 3 => array(
			'query' => 'SELECT COUNT(*) AS `count` FROM `thmeythmey`.`tbl_notifications` AS `Notification`   WHERE `Notification`.`id` = 6',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 0
		),
		(int) 4 => array(
			'query' => 'UPDATE `thmeythmey`.`tbl_notifications` SET `id` = 6, `title` = 'Sed bibendum sodales venenatis odio orci', `published` = '2015-02-11 16:25:00', `content` = '<p>Sed bibendum sodales venenatis. Vestibulum odio orci, luctus in tellus ut, pellentesque consectetur nunc.</p>', `modified` = '2015-02-11 18:08:53'  WHERE `thmeythmey`.`tbl_notifications`.`id` = '6'',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 0
		)
	),
	'count' => (int) 5,
	'time' => (float) 0
)
```

Model of `Notification`:
```
App::uses('AppModel', 'Model');
class Notification extends AppModel {
	public $validate = array(
		'title' => array(
			'notEmpty' => array(
				'rule' => array('notEmpty'),
				'message' => 'Please enter title',
			),
		),
		'message' => array(
			'notEmpty' => array(
				'rule' => array('notEmpty'),
				'message' => 'Please enter alert message',
			),
		),
	);
}
```

**Comment by markstory** [comment]
You are forcing one of those queries by calling exists(). Saving requires an exists() call as well. Do you have any behaviors or event listeners that may be calling find()?

**Comment by kongkannika** [comment]
There are not any behaviors in my model (see my model). i try to remove the `exists()` but it still have 4 queries. and i already tried the other projects of CakePHP, it is the same log of 3 queries of `COUNT(*)`. it's bug.

**Comment by AD7six** [comment]
* one - in the ticket description (`if (!$this->Notification->exists($id)) {`) 
 * [two](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Model/Model.php#L1818)
 * [three](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Model/ModelValidator.php#L260)
 * [four](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Model/Datasource/DboSource.php#L2423)

Each call can be accounted for, I don't think any of them can be removed easily either. You could enable query-caching if it's a problem, but if it's a problem you probably do actually need them (if there is sufficient traffic on the site such that the count queries cause an impact, there's more probability of the race conditions they are, I suppose, trying to account for).

Why do you consider that a bug?

**Comment by kongkannika** [comment]
if i want to save a updating data, i just use my specific id and save it. you could just test the field ID (or Primary Key of ID) is assign or not without check it with database directly. and I don't mean to remove it, just change the way to get those without query to database again and again.

I'm not good of writing in English but i can read and understand it. maybe it is not bug but something else that i don't know what it called ;)

**Comment by markstory** [comment]
I don't feel at all comfortable with removing the additional exists calls. Each one was added to solve specific concurrency issues as many people use CakePHP with database servers that do not have strong transactional safety (MySQL, older SQLServer) and we had a number of painful issues because of this.

While I can see how seemingly duplicate queries appear to be a problem, I don't think we can easily remove them without possibly introducing concurrency issues, or breaking functionality.

**Comment by kongkannika** [comment]
I wish this issue is not happending in version 3.x

**Comment by markstory** [comment]
It isn't. We rely on hydrated entity state to indicate to validation whether or not a record existed in the past. There is still however one last check before the record is saved so the ORM can decide between an insert an update query.
