### ISSUE TITLE
Hash::combine grouping failure

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#5873]
Cake 2.5.8

My array:

    [Param] => Array
        (
            [0] => Array
                (
                    [name] => Additional functions
                    [id] => 3
                    [ParamValue] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 44
                                    [name] => Cube
                                    [param_param_id] => 3
                                )
                            [1] => Array
                                (
                                    [id] => 45
                                    [name] => Distributor
                                    [param_param_id] => 3
                                )
                        )
                )
            [1] => Array
                (
                    [name] => Control
                    [id] => 7
                    [ParamValue] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 33
                                    [name] => Mechanic
                                    [param_param_id] => 7
                                )

                            [1] => Array
                                (
                                    [id] => 34
                                    [name] => Electronic
                                    [param_param_id] => 7
                                )
                        )
                )
        )
)

I use Hash::combine:

    pr(Hash::combine($params['Param'], '{n}.ParamValue.{n}.id', '{n}.ParamValue.{n}.name', '{n}.name'));

And my results are:

    Array
        (
            [Additional functions] => Array
                (
                    [44] => Cube
                )
            [Control] => Array
                (
                    [45] => Distributor
                )
            [0] => Array
                (
                    [33] => Mechanic
                    [34] => Electroni
                )
        )

But should be:

    Array
        (
            [Additional functions] => Array
                (
                    [44] => Cube
                    [45] => Distributor
                )
            [Control] => Array
                (
                    [33] => Mechanic
                    [34] => Electroni
                )
        )

**Comment by markstory** [comment]
Thanks I can take a look.

**Comment by markstory** [comment]
The issue is that your group key is not present in either the key or the value, so Hash cannot sanely stitch the data back together again.  I was able to get the data into the structure you expected minus the title names :cry: with

```php
$result = Hash::combine($a, '{n}.ParamValue.{n}.id', '{n}.ParamValue.{n}.name', '{n}.ParamValue.{n}.param_param_id');
```

The result of $key, and $groupPath must intersect for Hash to be able to re-assemble the data.
