### ISSUE TITLE
3.x: __toString() must not throw an exception

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#5874]
Hello,
It seems this error shouldn't occur but I don't understand why it happens on my hosting and not on my local server.
It concerns the following query:

        	$query = $this->Sites->find()
        				->contain(
        				    [
            					'Sitedescriptions' => function ($q) use ($language_request) {
           							return $q
    					                             ->where(['country_id' => $language_request])
    					                             ->orWhere(['country_id' => 'en']);
        						},
        						'Siteopeningdates' => function ($q) use ($language_request) {
           							return $q
    					                             ->where(['country_id' => $language_request])
    					                             ->orWhere(['country_id' => 'en'])
           							     ->contain(['Countries'])
           							;
        						},
        						'Siteprices' => function ($q) use ($language_request) {
           							return $q
    					                            ->where(['country_id' => $language_request])
    					                            ->orWhere(['country_id' => 'en'])
           							    ->contain(['Countries'])
           							;
           						},
        						'Countries'
        					]
        	           )
        				->where(['Sites.id' => $site_id]);

The full error message is:
Error: Method Cake\ORM\Query::__toString() must not throw an exception
File /home/modulwoo/www/2ndGuide/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php
Line: 193 

The error desappears if I remove 'Siteopeningdates' from contain[].

Any idea on the cause of the problem?

Regards,
Alain.

**Comment by markstory** [comment]
What is different about the two environments? That is probably a good place to start given the code works in one place but not the other.

**Comment by dakota** [comment]
I remember this being a problem in RC1. Ensure that both environments are using RC2 (or newer)

**Comment by caBBAlainB** [comment]
@marstory local server is running on windows whereas I suppose that hosting should run Linux. Maybe a problem of character cases but I still didn't find.
@dakota. I'm probably not really up to date...

**Comment by dakota** [comment]
I would first update to the latest HEAD. Any exceptions that are thrown during query execution are now actually displayed, instead of being eaten up by the __string() error.

**Comment by caBBAlainB** [comment]
@dakota COOLLLLL!!!!
I've updated cake and the error has gone!
Thanks friend.

**Comment by AD7six** [comment]
Already fixed in https://github.com/cakephp/cakephp/pull/5741
