### ISSUE TITLE
Wrong redirect with $loginRedirect if user is unauthorized

### ISSUE THREAD

**Issue by Holger2** [cakephp/cakephp#5878]
If the cake project is located in a subdirectory and `$loginRedirect` is set, the redirect via `redirectUrl` after login works fine. But if a user types in an URL he is not allowed to see, he gets redirected to /subdir/subdir/loginredirect. 

In my case (cake 2.5.5) I define `$loginRedirect` as an array and `AuthComponent::redirectUrl` adds the special parameter `'base' => false` before sending it to `Router::url`. This parameter removes the base path from the generated URL. Unfortunately in AuthComponent's function `_unauthorized` the URL from `$loginRedirect` is converted from an array to a string by the use of `Controller::referer` and the special parameter `'base' => false` is not used.

The solution could be to assure that the base path is always removed and define `$loginRedirect` in AppController with the special parameter, e.g.

    $this->Auth->loginRedirect = array(
            'controller' => 'posts',
            'action' => 'index',
            'base' => false
            );

Another solution could be to add the special parameter as in `redirectUrl` in AuthComponent's function `_unauthorized`:

    $default = $this->loginRedirect;
    if (is_array($default)) {
		$default = ($default + array('base' => false));
    }
			
I'm not sure, if this is a bug. I would suggest the second solution, but I don't know if it has implications beyond my scope.

**Comment by markstory** [comment]
I wasn't able to reproduce this on 2.6.1. You should probably upgrade and see if that fixes the issue, as this issue sounds very similar to #4812
