### ISSUE TITLE
Undefined index: level (TreeBehavior)

### ISSUE THREAD

**Issue by isaacaskew** [cakephp/cakephp#5886]
I recently started getting this error after a composer update, and after some initial tinkering with my code I still can't resolve it. Is this a Cake issue or likely something wrong with my code?

Every time I try to save an entity in my tree table, I get this issue:

Notice (8): Undefined index: level [CORE\src\ORM\Behavior\TreeBehavior.php, line 92]
Notice (8): Undefined index: level [CORE\src\ORM\Behavior\TreeBehavior.php, line 152]

Also, the Cake-baked models for my table throw errors on 'lft' and 'rght' if I leave the validation on. Take them away, and I can save it with the errors above. Refreshing the page shows everything saved correctly. Any ideas?

**Comment by ADmad** [comment]
Can you please show you table class code?

**Comment by isaacaskew** [comment]
It was an issue with my code; another tree behavior was included to extend the Cake TreeBehavior, and the issue seems to be resolved by placing 'level' => 'level' in the protected $_defaultConfig variables of the extended class.
