### ISSUE TITLE
I18N extraction: make POT-Creation-Date optional

### ISSUE THREAD

**Issue by mfn** [cakephp/cakephp#5887]
The `POT-Creation-Date` changes everytime the command `i18n extract` is run.

This creates headaches when working with multiple feature branches, each getting their own translations and constantly changes the same line on all files.

It's in general also annoying to have this noise in the diff.

Suggestion: make the addition of this timestamp optional or, if required for other tools, allow to fixate it at e.g. 1970-01-01

**Comment by markstory** [comment]
Well the POT file did change, so the date is accurate at least.

**Comment by mfn** [comment]
I think it also matters what "did change" means.

If you run this command multiple times, even if **no** language string changes, the POT file is written and the creation date is updated. So in that sense, it "did change" but because of the date; not of that content.

Thing is, the files are written every time, there's no check whether content has changed, thus the creation date changes even if no content changes are present.

This is getting a hassle when using a VCS because all the files are marked changed/dirty just because of the creation date.

Optionally disabling this sounds sensible to me.

**Comment by markstory** [comment]
Closing as there is a pull request up.
