### ISSUE TITLE
3.0 - Distinguish authenticate vs authorize error in AuthComponent

### ISSUE THREAD

**Issue by PGBI** [cakephp/cakephp#5888]
When configuring the AuthComponent, there is the authError option to display a flash message when a user attempts to access an object or action to which he does not have access.

However I think it would be more useful to split this option in 2:
- authError['authenticate'] => "You need to login to access this page",
- authError['authorize'] => "You are not allowed to see this!"

If you also think it could be useful, I can try to work on it and submit a pull request.

**Comment by markstory** [comment]
I would rather we don't disclose this level of detail from the framework. Information disclosure can often be used by attackers to further refine their attack patterns.

**Comment by PGBI** [comment]
I see your point.

However not being authorized and not being authenticated are two completely different situations. I don't see what kind of error message would cover both of them:
- "you can't access this page" is not relevant if you're not authenticated and just need to authenticate to access the page,
- "you need to login to access this page" does not make sense if you're authenticated but are not authorized.

**Comment by markstory** [comment]
There are generic ways of doing it:

* You do not have sufficient access to view this page.
* You are unauthorized.
* You cannot access the page you are trying to view.

They may not be as user-friendly, but I'm sure a proper copy-editor could do better.

**Comment by ionas** [comment]
Even GitHub shows 404 pages for private repositories when you want to access them but don't have privileges. That's just a security measurement and falls into the same category as not telling a user that his email-address wasn't in the database or that a password was incorrect but rather despite being not that helpful just tell that the login did not succeed.

**Comment by PGBI** [comment]
Displaying a 404 or 403 error when not authorized is fine for me. This is what the option `'unauthorizedRedirect' => false`of AuthComponent actually does. But in this case, having also the authError message flash message displayed is kind of redondant.

So is there a way not to instantiate the authError flash message when the user gets the 403 error page when not being authorized?

**Comment by ADmad** [comment]
@PGBI If you set `'unauthorizedRedirect' => false` in config no flash message is set. The specified `authError` is used as exception message.

**Comment by PGBI** [comment]
Indeed, but the pb is still the same: the message displayed in 403 page when not authorized is the same as the flash message displayed when not authenticated, which I still think is not ideal.

But since I feel i'm the only one thinking this, I guess you can close this issue!

On my side, i guess i'll just modify the error400.ctp template not to display the exception message.
