### ISSUE TITLE
Text->autoLink fails on url without protocol

### ISSUE THREAD

**Issue by LACabeza** [cakephp/cakephp#5889]
The code:

        $this->Text->autoLink($text, array( 'escape' => false));

Fail when you use links like

        $text = 'Text with a partial <a href="//www.cakephp.org">link</a> link';
        $text = 'Text with a partial <iframe src="//www.cakephp.org"></iframe> link';

(I used version 2.7 to test)

**Comment by LACabeza** [comment]
If i change [the regex](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/View/Helper/TextHelper.php#L117) 
from:

        '#(?<!href="|">)(?<!\b[[:punct:]])(?<!http://|https://|ftp://|nntp://)www.[^\n\%\ <]+[^<\n\%\,\.\ <](?<!\))#i'

to:

        '#(?<!href="|">)(?<!\b[[:punct:]])(?<!http://|https://|ftp://|nntp://|//)www.[^\n\%\ <]+[^<\n\%\,\.\ <](?<!\))#i'

fix the problem, but i don't know if this break something else.

**Comment by markstory** [comment]
Thanks for the help on getting the issue fixed. I've opened a #5890.
