### ISSUE TITLE
Missing plugin controller after an update to 3.0.0-RC2

### ISSUE THREAD

**Issue by mongramosjr** [cakephp/cakephp#5891]
After updating to rc2, the plugin controller is not anymore accessible by using lowercase strings and I got a "Missing Controller" error. But it is still working if I capitalized the first character of the controller. Seems the behavior of a plugin controller doesnt work as documented in http://book.cakephp.org/3.0/en/plugins.html#plugin-controllers

Also tried adding plugin controller using the new cakephp/bake plugin, Still got the missing controller error if I visit the site in lowercase string.

![missing plugin controller](https://cloud.githubusercontent.com/assets/620400/6198554/142de1b2-b444-11e4-8f04-c161b52c8deb.png)

**Comment by ADmad** [comment]
Please show the routes you have setup.

**Comment by mongramosjr** [comment]
Here's the route of the plugin

<?php
use Cake\Routing\Router;

Router::plugin('Catalog', function($routes) {
	$routes->extensions(['json', 'xml']);
	$routes->fallbacks();
});

**Comment by ADmad** [comment]
You need to change `$routes->fallbacks();` to `$routes->fallbacks('InflectedRoute');`

**Comment by mongramosjr** [comment]
It works now. Much thanks
