### ISSUE TITLE
2.3.x Ability to version control / manage cache of JS

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#5893]
I ran into a condition where the browser would not refresh to the latest version of JS - Often a condition everybody faces whilst using CDN.

```html
<script type="text/javascript" src="/js/custom.js"></script>
```
Alternatively, we pass parameter to let browser know that cache has to be refreshed.

```html
<script type="text/javascript" src="/js/custom.js?version=2"></script>
```

When we use Html helper - it does not provide support to pass versions (paramters) and as a result the option left is to disable cache or set Pragma: no-cache per every request.

**Comment by AD7six** [comment]
If the webserver is configured to prevent validation requests for static files and the url doesn't change - that's to be expected.

That duplicates [assetTimestamp](https://github.com/cakephp/cakephp/blob/master/app/Config/core.php#L232-L240), which is already there for this purpose.

However, you are better off _not_ using get args for cache busting and instead always change the url.

E.g.:

 * prefix the url with a version string e.g. `/v2/js/custom.js` 
 * use a rewrite rule ala `/v\d+/(.+)$` -> `\1`

You can do that by [modifying core.php](https://github.com/cakephp/cakephp/blob/master/app/Config/core.php#L118-L134) or overriding [AppHelper::assetUrl](https://github.com/cakephp/cakephp/blob/master/lib/Cake/View/Helper.php#L298-L341).

**Comment by markstory** [comment]
You can also look at assetcompress (a plugin I wrote to help manage assets better)

**Comment by karmicdice** [comment]
Hi @AD7six  ,

Thanks and yes, I knew about that.

Well, this propose is like a swiss knife... Passing parameters to JS is what I have seen many people doing - not just for version.
We are following this answer for implementation: http://stackoverflow.com/questions/2190801/passing-parameters-to-javascript-files#answer-2191433
Also, it may come in handy if I were to create a tracking system... remember how Google's utm is implemented?
It would help me create a script like so...
```html
myscript.js?utm_category=awesomeframeworks&utm_name=cakephp
```
I don't want to go direct html tag just for this script. :(

Not just for version control but wide range of things it could help developers with. I request that passing parameters to js be discussed?

**Comment by karmicdice** [comment]
Can we rename this thread to : Passing parameters to JS via HtmlHelper::script , please?

**Comment by AD7six** [comment]
Well, js has no reliable means to read those variables, they can be read server side, but can only be guessed from a script file. E.g. how could you handle this:

    <script src="/js/my.js?maybe=this&one=1">
    <script src="/js/my.js?you=have&to=guess">

That aught to hint that you're following the wrong solution.

> I don't want to go direct html tag just for this script. :(

Why would you need to, you could for example either: 

 * put the get args in the script url: `$this->Html->script('example.js?foo=bar');`
 * creating/override a method in your app to do whatever you want

> it may come in handy if I were to create

I suggest worrying about such things **when** you create a foo, not before =).

The "thread" title is the ticket title btw, but this isn't a forum.
