### ISSUE TITLE
debugkit css file not fount 

### ISSUE THREAD

**Issue by serjon** [cakephp/cakephp#5896]
start cakephp server dev - cake server -p 2000
localhost:2000 - run my site
add plugin debugkit where css, js file not found;

if run site apache example - localhost/mysite/ - debugkit work and include files correctly

Thanks

**Comment by markstory** [comment]
What version of cakephp are you using?

**Comment by serjon** [comment]
2.6.1 - stable

**Comment by markstory** [comment]
Thanks I see if I can reproduce the issue.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue.

* Cloned cakephp/cakephp - master(c8ca7cbfd9c082a73822dc8a573a71244c29d0dd)
* Install DebugKit with composer.
* Run `Console/cake server -p 8000`.
* Ensure plugin is loaded and component is loaded.

The toolbar displayed as expected. Perhaps double check that your `app/webroot/index.php` matches the current master branch. I know there were some issues with plugin assets in the past.
