### ISSUE TITLE
3.0 - Failing test for belongsTo needs to pass

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5898]
Hi guys. I made a test that currently fails, but can't. It sets a custom alias on a `belongsTo`, and currently the wrong thing is being set onto the `Entity` after finding.

Test is on the branch https://github.com/patrickconroy/cakephp/tree/3.0-failing-entity-belongsto @  https://github.com/patrickconroy/cakephp/commit/9a7792edc56a25106e1491f0e563b272bd0ab8bb

Refs PR #5836

**Comment by mdlouhy** [comment]
seems to be the same issue as #5882

**Comment by AD7six** [comment]
Closing as there's a PR for this particular problem now.
