### ISSUE TITLE
3.0 PostgresSchema class ignores table-specified lengths

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#5901]
For `'int', 'integer', 'tinyint', 'smallint', 'mediumint', 'bigint'`, MysqlSchema [correctly uses](https://github.com/cakephp/cakephp/blob/3.0/src/Database/Schema/MysqlSchema.php#L107) the parsed `$length` attribute, while [PostgresSchema](https://github.com/cakephp/cakephp/blob/3.0/src/Database/Schema/PostgresSchema.php#L88) ignores it and hardcodes numbers. Not sure what the best route here would be, though this seems to me like a bug in length handling.

**Comment by josegonzalez** [comment]
Note: I caught this in the Migrations plugin, where I'm comparing bake output under different datasources [here](https://travis-ci.org/cakephp/migrations/jobs/50809325).

**Comment by josegonzalez** [comment]
Linking cakephp/migrations@105f26d077a4409b22414dc4d02a7faa39019b90

**Comment by markstory** [comment]
Postgres doesn't support lengths on int columns which is probably part of the problem. The same is true for sqlserver from what I remember.

**Comment by markstory** [comment]
Given that postgres does not provide as flexible length options as MySQL, I did a quick test and created the following table:

```sql
create table ints (
  id serial,
  small smallint not null,
  medium integer not null,
  big bigint not null
);
```
When reflecting this table with CakePHP I got the following:

```php
'small' => [
			'type' => 'integer',
			'length' => (int) 5,
			'default' => null,
			'null' => false,
			'comment' => null,
			'precision' => null,
			'unsigned' => null,
			'autoIncrement' => null
		],
		'medium' => [
			'type' => 'integer',
			'length' => (int) 10,
			'default' => null,
			'null' => false,
			'comment' => null,
			'precision' => null,
			'unsigned' => null,
			'autoIncrement' => null
		],
		'big' => [
			'type' => 'biginteger',
			'length' => (int) 20,
			'default' => null,
			'null' => false,
			'comment' => null,
			'precision' => null,
			'unsigned' => null,
			'autoIncrement' => null
		]
```

Which seems pretty reasonable to me given [postgres' numeric types](http://www.postgresql.org/docs/9.1/static/datatype-numeric.html).

**Comment by josegonzalez** [comment]
Yeah but if you manually set the length of the field to 11 (for integer) it'll override to 10. Which does not seem reasonable.

**Comment by markstory** [comment]
But when you reflect the schema out of postgres, the 11 is totally lost, as postgres has no way of storing the 11. It only have `INTEGER`.

**Comment by markstory** [comment]
Closing as I don't think this is actually solvable given how postgres works.
