### ISSUE TITLE
As opposed to all the other association options, Association::$_className is unavailable.

### ISSUE THREAD

**Issue by anghazi** [cakephp/cakephp#5907]
How can I retrieve Association::$_className in appController?
http://stackoverflow.com/questions/28524208/how-can-i-get-the-classname-of-my-table-in-cakephp-3/28537689#28537689

**Comment by AD7six** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by anghazi** [comment]
I don't want help. I just report a bug :)

**Comment by AD7six** [comment]
> How can I retrieve Association::$_className in appController?

That sure looks like a help request =). 

If you want to report a bug, please don't just copy and paste a question into a ticket.

The code you're asking for is probably:

    $association->target()->registryAlias();

**Comment by anghazi** [comment]
OK. I will.
& thanks :)
