### ISSUE TITLE
FormHelper - Not compliant with XHTML Strict

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#5910]
Hi everybody, I am enjoying a lot the new CakePHP 3.0, but it seems that the FormHelper is not following the XHTML strict rules, unless I change the template manually to insert the trailling "/" in the generated "<input>" tag. Shouldn't it be compliant with the doctype you specify in HtmlHelper or the doctype present in the page you are using Formhelper?
Thanks a lot!

**Comment by ADmad** [comment]
3.0 generates HTML5 complaint html. If you want to be complaint with another standard update the templates are required. The generated html is independent of doctype generated by helper methods.
