### ISSUE TITLE
TreeBehavior - can't contain with parent (unique table/alias error)

### ISSUE THREAD

**Issue by isaacaskew** [cakephp/cakephp#5912]
I have a Tree structure table called 'Teams', and I want to contain with Teams again to find the name of my parent team.

The default CakePHP bin/cake bake model Teams gave me this:

    $this->belongsTo('ParentTeams', [
        'className' => 'Teams',
        'foreignKey' => 'parent_id'
    ]);

Naturally I assumed that I would just contain on this alias, so I tried this:

    public function findMyTeams($user_id){
    return $this->findByUserId($user_id)
        ->contain('ParentTeams')
        ->toArray();
    }
This yields the error:

    Error: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'Teams'

The documentation for TreeBehavior doesn't show this specifically, but all other contains are generally done using the same method. Does anybody know what I'm doing wrong here?

**Comment by AD7six** [comment]
That's a problem currently in 3.0 only, it's fixed by #5911
