### ISSUE TITLE
php composer.phar create-project --prefer-dist -s dev cakephp/app bookmarker

### ISSUE THREAD

**Issue by flik** [cakephp/cakephp#5914]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakephp/cakephp 3.0.*-dev -> satisfiable by cakephp/cakephp[3.0.x-dev].
    - cakephp/cakephp 3.0.x-dev requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - cakephp/cakephp 3.0.x-dev requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/bake dev-master requires cakephp/cakephp 3.0.x-dev -> satisfiable by cakephp/cakephp[3.0.x-dev].
    - Installation request for cakephp/bake dev-master -> satisfiable by cakephp/bake[dev-master].

**Comment by jadb** [comment]
@flik you are missing the [PHP intl extension](http://php.net/manual/en/intl.installation.php).

**Comment by flik** [comment]
After install extension and whole application but getting blank page without any error.

**Comment by ADmad** [comment]
Check the error logs, web server error logs and Cake's error logs in `logs` folder.
