### ISSUE TITLE
Impossible to render layout only.

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#5917]
I'm trying to render specific view like this:

$this->render(null, 'login');

the prob is if i don't create a "login.ctp" in the "users" folder, it never work. Also i got trouble when I debug $view and $layout in Cakephp/src/Controller/Controller.php @render.

If my useless view doesn't exist i got [null, null], but if it's created i got [null, 'login'] and it's work well.

Hope u got a solution, continue this way and thx for this great framework.

**Comment by AD7six** [comment]
What's the use case to render the layout only?

**Comment by GLacourt** [comment]
Well i was trying to render just the layout. After some search in src I understood the logic matched view  overwrite the $view arg in render function.

I guess we can pass pass through like this:
$this->autoRender = false;
$this->layout = 'login';

**Comment by AD7six** [comment]
> Well i was trying to render just the layout.

I'm asking you to clarify _why_ - because that's not normal.

**Comment by GLacourt** [comment]
Because i have a 'login' page who needs a different layout than the whole of my app. So i wouldn't create a specific layout + a single view for this layout.

I wanted to merge layout and view. I thought it's should be better to create layout only.

**Comment by AD7six** [comment]
it's normal to render a view without a layout, it's not normal to render a layout without a view.

Personally, I'd still create a view and a layout even if it were to be used once.

**Comment by GLacourt** [comment]
Ok nice advice thx for yours explainations.
