### ISSUE TITLE
3.0: Allow theming of flash messages

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#5920]
Currently it is only possible to override the elements used for flash messages in the app itself. It is AFAIK not possible to make the Flash system _always_ use elements from plugins.

I know you can do things like `Flash::set('test', ['element' => 'MyTheme.info']`, but this is obviously very tedious. Why not add a `$theme` property to the Flash system as the View has?

This would work great with all the Bootstrap themes out there that need to change the elements used for flash messages.

**Comment by jadb** [comment]
While I totally see the benefit of having an extra `plugin` (since themes are plugins now) config option to the `FlashComponent`. 

In the meantime, you could re-define the default element using config:

```php
$components = ['Flash' => ['element' => 'MyTheme.info']];
// or
$this->loadComponent('Flash', ['element' => 'MyTheme.info']);
```

While I understand this might not be sufficient for what you are trying to get to, it might help until this is implemented.

Another way would be to subclass the core FlashComponent:

```php
<?php
namespace App\Controller\Component;

class FlashComponent extends \Cake\Controller\Component\FlashComponent
{
    public function set($message, array $options = [])
    {
        $options += $this->config();
        list($plugin, $element) = pluginSplit($options['element']);
        if (!$plugin) $plugin = 'MyTheme';
        parent::set($message, $options);
    }
}
```

Lastly, if you are using [Crud](/friendsofcake/crud) for example, you can add something like this after you load the `CrudComponent` in the `AppController::initialize()` for example:

```php
        $this->Crud->on('setFlash', function (Event $event) {
            $event->subject->element = 'BootstrapUI.success';
            if (strpos($event->subject->params['class'], 'error') !== false) {
                $event->subject->element = 'BootstrapUI.danger';
            }
            unset($event->subject->params['class']);
        });
```

**Comment by AD7six** [comment]
You would ordinarily do that by aliasing the flash component. 

E.g., [here's how the boostrap-ui plugin does it](https://github.com/FriendsOfCake/bootstrap-ui#install):

    public $components = ['BootstrapUI.Flash'];

I don't really see a need for more than that.

**Comment by burzum** [comment]
I agree with @AD7six.

**Comment by nrother** [comment]
Sounds a bit inconvenient to me to sub-class the flash component just to change a search path. I thought that what configuration is for ;) Or: Why has the View than this `$theme` option, when you could just sub-class it?

**Comment by ADmad** [comment]
I believe this simple change would achieve what @nrother wants https://gist.github.com/ADmad/475a483ecfc6782c6160

**Comment by nrother** [comment]
Yes, that looks really good. Taking the theme from the view is even better that having an extra setting just for flash.

**Comment by ADmad** [comment]
Closing as there is a PR open now.
