### ISSUE TITLE
Query builder and contain with a plugin's Table

### ISSUE THREAD

**Issue by stefanozoffoli** [cakephp/cakephp#5921]
Hi, if for example I do this:

```php
$article = $this->Article->get($id, [
    'contain' => [
        'Users.Users',
    ]
]);
```
I get the error "Users is not associated with Users", but i used the dot notation because UsersTable is in a plugin named Users.

I read in the docs that one can use dot notation to express nested associations, but then how can i use dot notation to express a plugin table?

**Comment by ADmad** [comment]
You just need to use the alias you used for the association.
