### ISSUE TITLE
Path comparison is broken for Themes in WIN

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#5923]
In the View class there is a check

    if (strpos($path, DS . 'Plugin' . DS) === false) {}

When using Windows, the $paths array looks like this: 

	(int) 0 => 'D:\...\cakephp2\app\View\Themed\Responsive\Plugin\Websites\',
	(int) 1 => 'D:\...\cakephp2\app\View\Themed\Responsive\',
	(int) 2 => 'D:\...\cakephp2\app/Plugin/Websites/View\Themed\Responsive\Plugin\Websites\',
	(int) 3 => 'D:\...\cakephp2\app/Plugin/Websites/View\Themed\Responsive\',
	(int) 4 => 'D:\...\cakephp2\app\View\Plugin\Websites\',
	(int) 5 => 'D:\...\cakephp2\app/Plugin/Websites/View\Plugin\Websites\',
	(int) 6 => 'D:\...\cakephp2\app\Plugin\Websites\View\',
	(int) 7 => 'D:\...\cakephp2\app\View\',
	(int) 8 => 'D:\...\cakephp2\app/Plugin/Websites/View\',
	(int) 9 => 'D:\...\cakephp2\vendors/cakephp/cakephp/lib\Cake\View\',
	(int) 10 => 'D:\...\cakephp2\vendors/cakephp/cakephp/lib\Cake\Console\Templates\skel\View\'

This makes it jump into the condition, as it cannot match any value due to some `/` instead of `\` (DS) here.
It creates weird behavior as suddendly it looks in totally different folders (and not where it should at).
We should normalize this somewhere sooner than the view file (where I quick-fixed it, but not ideal).

**Comment by markstory** [comment]
Why do the paths have mixed slashes?

**Comment by dereuromark** [comment]
Is it possible they always did? It is just not noticeable on non-WIN. See the last vendors ones.
I will try to look into it some more. Only scratched the surface for now.

**Comment by dereuromark** [comment]
On detailed examination it looks like an app specific thing. Somwhere people introduce hardcoded / for App::build().
I feel like this should really throw exceptions in debug mode ;) Anyway, with proper configuration there is no issue here it seems. Closing then until I can prove otherwise.

**Comment by dereuromark** [comment]
As a side note: The `\vendors/cakephp/cakephp/lib\` issue I could not resolve, that is probably from composer path creation. But this is most likely not a big deal as you wouldn't compare against this path string anyway.
