### ISSUE TITLE
Cake 3.0 Cache Configuration for OPcache and APCu

### ISSUE THREAD

**Issue by johnlanz** [cakephp/cakephp#5924]
I'm a bit confused on how to configure caching in cakephp 3.0. I'm using PHP 5.6 with Zend OPcache And APCu.
The built-in caching engines in cake are FileCache, ApcCache, Wincache, XcacheEngine, MemcachedEngine, and RedisEngine. Which one should I choose?
Any sample configuration?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
