### ISSUE TITLE
3.0: No custom REST-routes available

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#5929]
Hey guys,

I want to set custom REST-routing for my applicaton.
In 2.x it seems to work this way: http://book.cakephp.org/2.0/en/development/rest.html#modifying-the-default-rest-routes
It looks like it's not available for 3.0 (http://api.cakephp.org/3.0/class-Cake.Routing.Router.html).
Will this become available, or won't we be able to add custom REST-routing?

Kind regards,

Bob

**Comment by josegonzalez** [comment]
It is possible, just documented under [Routing](http://book.cakephp.org/3.0/en/development/routing.html#creating-restful-routes).

Might make sense to move those docs to the REST docs...

**Comment by bobmulder** [comment]
Yeah I found that page too (after a long search) but it's not clear how to define extra actions. It seems it's possible in cake 2.x: http://book.cakephp.org/2.0/en/development/rest.html#modifying-the-default-rest-routes.

Just to explain my problem: beside the default `index`, `add`, `view`, `edit`, `delete` actions (for my rest-api) i need custom actions like `deleteAll` or something... In cake 2 we were able to add them?

**Comment by josegonzalez** [comment]
What function are you specifically referring to that is missing?

**Comment by markstory** [comment]
@bobmulder You can only currently remap the 5 default actions. I was not really excited about keeping the static methods around, and left the feature un-implemented. Would being able to pass additional methods as parameters into `resources()` work? Something like:

```php
Router::scope('/api', function($routes) {
  $routes->resources('Articles', [
    'map' => ['deleteAll' => ['action' => 'deleteAll', 'method' => 'DELETE']]
  ]);
});
```

**Comment by bobmulder** [comment]
Hey Mark,

Your example would be great. Is there a way to implement this?

**Comment by markstory** [comment]
@bobmulder Yes someone has to write the code :smile:. I can take a shot at it.

**Comment by bobmulder** [comment]
Haha thank you! It's really nice to be connected with the developpers so close...

I've found a quick fix. Don't know if it clean or dirty... After loading the resource I added an an 'connect'. 

I am on mobile, so Will explain in a few hours ;)

**Comment by markstory** [comment]
Closing as I think #5934 addresses this.
