### ISSUE TITLE
Session modifications ignored if dooing a redirect after

### ISSUE THREAD

**Issue by mdelorimier** [cakephp/cakephp#5930]
It seems that if you do a Redirect after setting a session variable, the modification is ignored.
For example : 
$redirect = $this->request->session()->consume('redirect');
return $this->redirect($redirect, null);

**Comment by jadb** [comment]
@mdelorimier - sorry, which modification are you trying to do? The example doesn't show any.

**Comment by ADmad** [comment]
You say "setting a session variable" but you example using method "consume()" which reads and deletes values from session, doesn't set anything.

Regardless any changes changes to session are not lost after redirection.

**Comment by mdelorimier** [comment]
Well, consume should modify the session by deleting the session Key right?

But currently, after redirection, the session key is still there which in my opinion is a failiure to apply a modification to the session.

Previously i had : 
$redirect = $this->request->session()->read('redirect');
$this->request->session()->write('redirect', '');
return $this->redirect($redirect, null);

And the same issue applyed.

To be noted that this happens in a page displayed immedialty after login.

**Comment by jadb** [comment]
@mdelorimier consume should delete the session key, yes.

As for the second example, `write('redirect', null)` != `delete('redirect')`.

**Comment by AD7six** [comment]
@mdelorimier it seems much more likely that the session key "redirect" is written after the redirect is issued - possibly by a different request.

You can verify you're looking at the wrong problem (or prove me wrong) by doing:

    $redirect = $this->request->session()->consume('redirect');
    debug($this->request->session()->read());
    die;
    return $this->redirect($redirect, null);
