### ISSUE TITLE
Entity $_accessible property

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#5932]
My baked entity has ``protected $_accessible`` which is wrong regards to PSR-2

**Comment by AD7six** [comment]
PSR2 generates a warning about this, it's not an error. The wording of [the standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#42-properties) is:

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.
    
Where should is a recommendation, not a requirement. We're not able to adopt that rule without substantial changes, which won't be implemented at this time.

Note that CakePHP projects use [the cakephp-codesniffer](https://github.com/cakephp/cakephp-codesniffer) standard, which obeys psr2 restrictions, suppressing some warnings.
