### ISSUE TITLE
cake i18n extract task extracts to app/Locale/LC_TIME/cake.pot

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#5933]
As far as I know PO files are not supported (since 2.6.*) anymore for LC_TIME. What's the use of extracting to `app/Locale/LC_TIME/cake.pot`?

Also see [this](https://github.com/cakephp/cakephp/pull/5854) related issue.

**Comment by markstory** [comment]
Yeah its probably not super useful. I can fix that.

**Comment by tersmitten** [comment]
Thanks

**Comment by markstory** [comment]
Fixed with #5933.
