### ISSUE TITLE
3.0 Translation of singular forms in __dn() does not work

### ISSUE THREAD

**Issue by fub-frank** [cakephp/cakephp#5940]
I think there is a bug in the __dn() function of cakephp 3.0 (or one of the functions that is called in the process of __dn()) with the singular forms of strings. I tried to translate the \Cake\I18n\Time::timeAgoInWords when I encountered this problem.

The __dn() function is used to, e.g., translate the String '{0} hour':
```php
$relativeDate .= ($relativeDate ? ', ' : '') . __dn('cake', '{0} hour', '{0} hours', $hours, $hours);
```
where `{0} hour` is the singular form and `{0} hours` is the plural form. Within the translate method of `\Aura\Intl\Translator` only the plural form is translated.
```php

    public function translate($key, array $tokens_values = [])
    {
        // get the message string
        // HERE ONLY THE PLURAL MESSAGE IN $key is translated
        // BUT NOT THE SINGULAR IN $tokens_values['_singular']
        $message = $this->getMessage($key);

        // do we have a message string?
        if (! $message) {
            // no, return the message key as-is
            $message = $key;
        }

        // are there token replacement values?
        if (! $tokens_values) {
            // no, return the message string as-is
            return $message;
        }

        // run message string through formatter to replace tokens with values
        return $this->formatter->format($this->locale, $message, $tokens_values);
    }
```
While the singular form of the translated string is in the array $tokens_values['_singular'] is never translated. Then the IcuFormatter formats the untranslated singular form in its format method
```php
if (!is_string($message)) {
            $count = isset($vars['_count']) ? $vars['_count'] : 0;
            unset($vars['_count'], $vars['_singular']);
            $form = PluralRules::calculate($locale, $count);
            $message = $message[$form];
        }
```

It can be fixed by adding the following code to \Aura\Intl\Translator translate method:
```php
if (isset($tokens_values['_singular'])) {
    $singular = $this->getMessage($tokens_values['_singular']);
    if ($singular !== false) {
        $tokens_values['_singular'] = $singular;
    }
}
```

**Comment by markstory** [comment]
If someone was going to try and reproduce this issue would trying to create a translated value for `{0} hour` be enough and then call `__dn('cake', '{0} hour', '{0} hours', $hours, $hours);` where `$hours` == 1?

**Comment by fub-frank** [comment]
I am trying to translate to german, so in `config/bootstrap.php` i have this line
```php
ini_set('intl.default_locale', 'de_DE');
```
I create the File `src/Locale/de/cake.po` with the following content
```php
msgid "{0} hour"
msgstr "{0} Stunde"

msgid "{0} hours"
msgstr "{0} Stunden"
```

Now you can try this in a template for example
```php
<?php
$hours = 1;
echo __dn('cake', '{0} hour', '{0} hours', $hours, $hours);
?>
```

The output is `1 hour` but it should be `1 Stunde`

**Comment by ADmad** [comment]
Plural message need to be declared in format as shown below:

```
msgid "{0} hour"
msgid_plural "{0} hours"
msgstr[0] "{0} hours"
msgstr[1] "{0} Stunden"
```

**Comment by fub-frank** [comment]
thanks this works
