### ISSUE TITLE
query for join some tables

### ISSUE THREAD

**Issue by mrezagolestan** [cakephp/cakephp#5941]
my tables structure:

```php

estates (id)
estates_esspecvalues (estate_id,esspecvalue_id)
esspecvalues(id,esspecattribute_id,title)
esspecattributes(id,title)
```
i want to have a query for join this 4 table , i need output as an array to manipulate that.

output array should have
```php
estates.id , esspecvalues.title , esspecattributes.(id , title)
```

when i`m using find and contain esspecvalues it`s done because my estates table have association with esspecvalues but i can`t contain esspecattributes

**Comment by AD7six** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by markstory** [comment]
I would first figure out how to write the sql you need. After that you can use the querybuilder to replicate that sql.
