### ISSUE TITLE
Quoting not working for SQL Server

### ISSUE THREAD

**Issue by stmeyer** [cakephp/cakephp#5949]
Hello,

i have enabled Quoting for Microsoft SQL Server, and "bake" the Model, Controller and Templates for a Database Table "User". When updating or inserting a dataset, i get an error "Wrong syntax at user-keyword". But showing all users, a single user and delete a user is working.

Best regards

**Comment by stmeyer** [comment]
The Issue is for cakephp 3.

**Comment by jadb** [comment]
Is this issue about bake? If so, please close here and open one [here](/cakephp/bake/issues/new) instead.

**Comment by AD7six** [comment]
I don't think this is bake related.

@stmeyer what is the executed code, what is the executed sql, and what sql are you expecting?

**Comment by markstory** [comment]
Table names are supposed to be plural in CakePHP. This is partly a conventions thing and partly a way to avoid keyword conflict in database servers. You should also make sure that 'quoteIdentifiers' is enabled for your connection if you cannot rename your User table.

**Comment by stmeyer** [comment]
The database table is:
```sql
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[SurName] [nvarchar](100) NULL,
	[LoginName] [varchar](100) NULL,
	[Password] [varchar](64) NULL,
	[Email] [varchar](100) NULL,
	[DateCreate] [datetime] NULL,
	[DateLastVisit] [datetime] NULL
 CONSTRAINT [PKUser] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```
Then i bake everything for the table:
```
cake.bat bake model user
cake.bat bake controller user
cake.bat bake template user
```
After this, i visit https://url.tld/user/add and fill out all field. By saving, the executed query object is:
```
object(Cake\ORM\Query) {

	'sql' => 'INSERT INTO [user] ([FirstName], [SurName], [LoginName], [Password], [Email], [DateCreate], [DateLastVisit]) OUTPUT INSERTED.* VALUES (:c0, :c1, :c2, :c3, :c4, :c5, :c6)',
	'params' => [
		':c0' => [
			'value' => 'test',
			'type' => 'string',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => 'test',
			'type' => 'string',
			'placeholder' => 'c1'
		],
		':c2' => [
			'value' => 'test',
			'type' => 'string',
			'placeholder' => 'c2'
		],
		':c3' => [
			'value' => 'test',
			'type' => 'string',
			'placeholder' => 'c3'
		],
		':c4' => [
			'value' => 'test@mail.com',
			'type' => 'string',
			'placeholder' => 'c4'
		],
		':c5' => [
			'value' => object(Cake\I18n\Time) {},
			'type' => 'timestamp',
			'placeholder' => 'c5'
		],
		':c6' => [
			'value' => object(Cake\I18n\Time) {},
			'type' => 'timestamp',
			'placeholder' => 'c6'
		]
	],
	'defaultTypes' => [
		'User.ID' => 'integer',
		'ID' => 'integer',
		'User.FirstName' => 'string',
		'FirstName' => 'string',
		'User.SurName' => 'string',
		'SurName' => 'string',
		'User.LoginName' => 'string',
		'LoginName' => 'string',
		'User.Password' => 'string',
		'Password' => 'string',
		'User.Email' => 'string',
		'Email' => 'string',
		'User.DateCreate' => 'timestamp',
		'DateCreate' => 'timestamp',
		'User.DateLastVisit' => 'timestamp',
		'DateLastVisit' => 'timestamp'
	],
	'decorators' => (int) 0,
	'executed' => false,
	'hydrate' => true,
	'buffered' => true,
	'formatters' => (int) 0,
	'mapReducers' => (int) 0,
	'contain' => [],
	'matching' => [],
	'extraOptions' => [],
	'repository' => object(App\Model\Table\UserTable) {

		'registryAlias' => 'User',
		'table' => 'user',
		'alias' => 'User',
		'entityClass' => 'App\Model\Entity\User',
		'associations' => [[maximum depth reached]],
		'behaviors' => [[maximum depth reached]],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	}

}
```
Is it possible, that DateTime-Columns habe to the a PHP-DateTime-Object, like described in  https://msdn.microsoft.com/en-us/library/cc296193%28v=sql.105%29.aspx
@markstory it is currently not possible to rename the user table. 'quoteIdentifiers' is enabled

**Comment by markstory** [comment]
Ok, what do the executed queries look like?

**Comment by stmeyer** [comment]
Hm. After updating to the newest release (```composer update```), i can not reproduce this error. Maybe I have to wait until #5951 is closed, because I allways get the error message from that issue.

**Comment by AD7six** [comment]
@stmeyer can you please indicate your code, the executed sql and the sql you are expecting?

Otherwise we have no idea what problem you're looking at without guessing (which I'm not going to do).

**Comment by markstory** [comment]
Closing as it has been several days with no updates and from what I can gather the error has been resolved in the most recent CakePHP updates.
