### ISSUE TITLE
cake bake error

### ISSUE THREAD

**Issue by rfos** [cakephp/cakephp#5950]
In version 2.6.2 there is a problem for generation of " views" using cake bake

**Comment by AD7six** [comment]
Please give some details - how can someone reproduce whatever problem it is you're seeing?

**Comment by rfos** [comment]
1) Create a table:

CREATE TABLE `notes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo_nota` varchar(255) DEFAULT NULL,
  `descricao_nota` longtext,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `data_pedido` datetime DEFAULT NULL,
  `data_entrega` datetime DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


2. Bake All
cake bake all 
choose the model "notes" 

3. go to http://localhost/notes

the error: 
Fatal Error
Error: syntax error, unexpected ';'	
File: /Users/Rey/Sites/cakephp/app/View/Notes/index.ctp	
Line: 31

line 31:
<?php echo $this->Form->postLink(__('Delete'), array('action' => 'delete', $note['Note']['id']), array('confirm' => __('Are you sure you want to delete # %s?', $note['Note']['id'])); ?>

**Comment by AD7six** [comment]
Thanks for clarifying - closing as there's a PR open now.
