### ISSUE TITLE
Paginate Count Query in Cakephp 3.0: Speed Issue

### ISSUE THREAD

**Issue by johnlanz** [cakephp/cakephp#5955]
Hi,

I have more than 3,000 records on my table and the pagination count seems too slow
The $this->paginate() code execute 2 queries:
1st query runs in: 31 milliseconds
2nd query which is counting all the records: 2,563 milliseconds
This is the sample query produced by the pagination count which includes field names:
SELECT (COUNT(*)) AS `count`, fieldname1, fieldname2, fieldname3, etc from table left join table 1, table 2 where condition1;

When I run the query on phpmyadmin and remove the fields:
SELECT (COUNT(*)) AS `count` from table left join table 1, table 2 where condition1;

The query runs in: 1,518 milliseconds that's a 1,000 ms difference.

So what's the purpose of including field names in counting the records?

For temporary fixed how can we modify the paginate Count so that field names will not be included in the query?

Thanks

**Comment by lorenzo** [comment]
Can you show the code for the query that does that?

**Comment by johnlanz** [comment]
Hi Lorenzo,
This is the code:

    $this->paginate = [
        'fields' => [
            'id', 'user_id', 'role_id', 'athlete_id', 'coach_id', 'service_provider_id', 'staff_id',
            'club_id', 'nso_id', 'pso_id'
        ],
        'contain' => [
            'Users' => ['fields' => ['id', 'first_name', 'last_name']],
            'Nso' => ['fields' => ['id', 'name']],
            'Pso' => ['fields' => ['id', 'name']],
            'Clubs' => ['fields' => ['id', 'name']],
            'SportInformations' => ['fields' => ['id', 'status', 'expiry_date']]
        ],
        'conditions' => $conditions,
        'sortWhitelist' => [
            'id', 'Users.last_name', 'Pso.name', 'Clubs.name',
            'SportInformations.expiry_date, SportInformations.status'
        ]
    ];
        
    $registrations = $this->paginate();

Paginate Count Query:

    SELECT (COUNT(*)) AS `count`, Users.id AS `Users__id`, Users.first_name AS `Users__first_name`, Users.last_name AS `Users__last_name`, Nso.id AS `Nso__id`, Nso.name AS `Nso__name`, Pso.id AS `Pso__id`, Pso.name AS `Pso__name`, Clubs.id AS `Clubs__id`, Clubs.name AS `Clubs__name`, SportInformations.id AS `SportInformations__id`, SportInformations.status AS `SportInformations__status`, SportInformations.expiry_date AS `SportInformations__expiry_date` FROM registrations Registrations LEFT JOIN users Users ON Users.id = (Registrations.user_id) LEFT JOIN organisations Nso ON Nso.id = (Registrations.nso_id) LEFT JOIN organisations Pso ON Pso.id = (Registrations.pso_id) LEFT JOIN organisations Clubs ON Clubs.id = (Registrations.club_id) LEFT JOIN sport_informations SportInformations ON Registrations.id = (SportInformations.registration_id)

**Comment by markstory** [comment]
Replacing all the fields in count query should be doable.

**Comment by markstory** [comment]
I think I got this fixed in #5961

**Comment by quimr** [comment]
Hi. 

I have a problem with the count() of paginate still in cakephp version 3.3:

My table has 6,000,000 records.
The fields involved here are name and cityf. Both have index in MySQL

I'm showing 10 and 10 and despite the query is very fast, the count() of paginate is taking more than 50 seconds.

How to solve this in version 3.3 of cakephp. Follows the two SQL statements and times below:


SELECT 
  Rr.id AS `Rr__id`, 
  Rr.idn AS `Rr__idn`, 
  Rr.aniver AS `Rr__aniver`, 
  Rr.pessoa AS `Rr__pessoa`, 
  Rr.name AS `Rr__name`, 
  Rr.phoner AS `Rr__phoner`, 
  Rr.tipolf AS `Rr__tipolf`, 
  Rr.addressf AS `Rr__addressf`, 
  Rr.num_endf AS `Rr__num_endf`, 
  Rr.complem AS `Rr__complem`, 
  Rr.bairrof AS `Rr__bairrof`, 
  Rr.cityf AS `Rr__cityf`, 
  Rr.statef AS `Rr__statef`, 
  Rr.cepf AS `Rr__cepf`, 
  Rr.n1 AS `Rr__n1`, 
  Rr.n2 AS `Rr__n2`, 
  Rr.smerc AS `Rr__smerc`, 
  Rr.n3 AS `Rr__n3`, 
  Rr.n4 AS `Rr__n4`, 
  Rr.fone AS `Rr__fone`, 
  Rr.numero AS `Rr__numero` 
FROM 
  `MG` Rr 
WHERE 
  (
    Rr.name like 'MARCOS%' 
    AND Rr.cityf like 'BELO HORIZONTE%'
  ) 
ORDER BY 
  name asc 
LIMIT 
  10 OFFSET 0

= 10 ms

SELECT 
  (
    COUNT(*)
  ) AS `count` 
FROM 
  `MG` Rr 
WHERE 
  (
    Rr.name like 'MARCOS%' 
    AND Rr.cityf like 'BELO HORIZONTE%'
  )

= 51.247 ms


I appreciate any help.

Marcos

**Comment by lorenzo** [comment]
Please don't post in old tickets asking for help. You can use any of our help channels to solve your issue

**Comment by quimr** [comment]
Sorry for it.  Already I deleted.

**Comment by benzo12** [comment]
Hello,

Apologies if this isn't the right place for this, but I am still having this exact issue with the latest cakephp (3.3.7).  The paginate select (with fields) retrieves 100 records in 243ms, but the select count query takes 48116ms. The left joins are still in the select count query.  

Is this still being worked on?

**Comment by lorenzo** [comment]
Opened a new ticket, please don't' comment on closed ones
