### ISSUE TITLE
FormHelper::allInputs should ignore hidden fields

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#5957]
FormHelper::allInputs generates the html code for every field, even if they are in Entity::_hidden

in my opinion this is an undesirable behavior.

a $_protected Entity var could be useful.
a protected field can be viewed (fetched in finds) but not edited (ignored in FormHelper)

**Comment by luke83** [comment]
I think fields in $_hidden are only for output skip, so you want a password field hidden for output to avoid security issue, but you want to have form field (maybe only in the user profile) to insert/change it.

**Comment by markstory** [comment]
Yes FormHelper does not look at the exposed fields in an entity, and instead looks at the schema. We can't really rely on the entity's `visibleProperties()` when building forms either as visible properties often includes virtual fields which also shouldn't have inputs generated for them. Looking at which fields can be mass-assigned (accessible fields) could be a sane approach though.

**Comment by ADmad** [comment]
Closing as the issue has gone stale. Feel free to open a PR if you are still interested in the feature.
