### ISSUE TITLE
3.0 Can't choose fields on releations

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#5959]
Hey Guys,

In Cake 2.x we were able to choose the fields to select for relations. See http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#belongsto (under keys) for documentation.

In Cake 3.x this feature isn't implemented. Will this be build soon, is there a fix, or what's the reason if this is a bad idea? With the feature of Entities I understand it could be dirty...

**Comment by bobmulder** [comment]
Note: There is a way to do this but it's very dirty:

**Comment by markstory** [comment]
Limiting the fields can often result in non-functioning entities which is one of the reasons the specific field loading was removed. The association builder option will likely be the only way to do this for quite some time.

**Comment by markstory** [comment]
I forgot that you can also use the `fields` key when including an association in contain(). This isn't in the book, but is in the API.

**Comment by bobmulder** [comment]
@markstory Thanks, adding a field-array to `contain()` works! 

I guess you are using configurations from the association builder when defining  `contain

**Comment by lorenzo** [comment]
I don't think having the option of defining the fields in the association builder is a good idea, since it would make it super difficult to override in other finders.

**Comment by markstory** [comment]
@bobmulder Yeah, I generally write finder methods to package up all my queries and try to avoid sql-ish things in the controllers.

Closing as there are existing solutions and adding/restoring old 2.x functionality can make the ORM harder to work with.
