### ISSUE TITLE
3.0 Bake all plugin entity

### ISSUE THREAD

**Issue by vttn** [cakephp/cakephp#5960]
We are using 3.0 RC2.

We are trying to bake a complete MVC skeleton using bake:

`bin/cake bake all -p ContentManager pages`

`Error: Unknown short option p`

The `ContentManager` plugin has already been created.

Is it possible to use the bake all option for plugins entities?

**Comment by markstory** [comment]
Looks like `bake all` is missing many of the options that the tasks have. I can fix that up.

**Comment by markstory** [comment]
Closing as a pull request is up for bake now.
