### ISSUE TITLE
Pagination Multiple Field Ordering

### ISSUE THREAD

**Issue by MichaelHoughton** [cakephp/cakephp#5964]
This has been an issue throughout various releases of CakePHP.  I wanted to mention it to first get some feedback if it is infact a bug.

If you Paginate by multiple fields, then the ordering of each field MUST be specified.  This isn't required for a normal $this->find query.

For example:

    $this->Paginator->settings['order'] = array('position', 'name');
    $this->Paginator->paginate();

Will give a different ordering to:

    $this->Paginator->settings['order'] = array('position' => 'asc', 'name' => 'asc');
    $this->Paginator->paginate();

The first example, the ordering effectively doesn't work, but it would be great if it would order by 'asc' by default in this case (i.e. without needing to specify 'asc').  It DOES this on a find query at the moment.

**Comment by markstory** [comment]
How is the second example different from a normal find() operation?

**Comment by MichaelHoughton** [comment]
Hey @markstory  - you may have misunderstood me.

The first example would work and order correctly if it was a normal find query.

The first example does NOT order correctly if it is paginated.

The second example works the same for both a find query and if paginated - the results would be ordered correctly.

The issue is with paginating data via the first example which does not order the data correctly.

Thanks again.
Michael

**Comment by markstory** [comment]
Ah ok, I'll find out why.

**Comment by markstory** [comment]
Fixed with #5970
