### ISSUE TITLE
AssetDispatcher including JS and CSS files

### ISSUE THREAD

**Issue by tehboris** [cakephp/cakephp#5966]
I'm writing an application using CakePHP and I came across [these lines of code](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Routing/Filter/AssetDispatcher.php#L157).

Any JavaScript or CSS file that contains a php opening tag will (usually) result in a syntax parsing error. This may seem unlikely until you consider that short tags might be enabled at which point it only takes <? to trigger the problem.

I couldn't think of a reason why .js and .css files would be treated like this. I did try to find where this code came from and why it was like that. Trying to follow it lead me all the way back to CakePHP 1 (as far back as 2009).

If some one knows a reason why it's like that I would be very interested to know. Other wise it might just want to use readfile for all assets.

**Comment by ADmad** [comment]
This issue has been reported before but due to backwards compatibility reason cannot be changed in 2.x. The issue has been fixed in 3.0.
