### ISSUE TITLE
Non-link WWW is changed to link by TextHelper's autoLink

### ISSUE THREAD

**Issue by anguswoodman** [cakephp/cakephp#5968]
The word AWWWARD appeared in some autolinked output. It was rendered as a link with an href of "WWWARD"

Fix is simple: the regex in TextHelper needs an escape on the . after www on line 117 (as of 2.6.2)

**Comment by dereuromark** [comment]
@anguswoodman Are you able to provide a fix with a test case maybe? That would be awesome.

**Comment by markstory** [comment]
If not I can take care of it tonight :smile:

**Comment by markstory** [comment]
Fixed in 2.x and 3.x

**Comment by anguswoodman** [comment]
Awesome, thanks @markstory! Figured someone would knock it off before I even got the code set up :)
