### ISSUE TITLE
3.0 - Save updated associated data

### ISSUE THREAD

**Issue by Testtestom** [cakephp/cakephp#5969]
Hi, I want to update data from a model and one association(*HasOne*) but data from the model associated are not updated in database. However, values of inputs are corrects.
So my form is just like it :
```php
<?= $this->Form->create($participation); ?>
    ... // Ex first model :
    <?= $this->Form->email('EventsParticipations.email', ['id'=>'email']); ?>
    ... // Ex model associated :
    <?= $this->Form->select('events_participations_meal.drink', $selects, ['id'=>'drink']); ?>
    ...
<?= $this->Form->end(); ?>
```

My controller :
```php
$participation = $this->EventsParticipations->get($id, [
    'contain' => [
        'EventsEvents',
        'EventsParticipationsMeals'
    ]
]);
// ...
if ($this->request->is('put')) {
    
    $participation = $this->EventsParticipations->patchEntity($participation, $this->request->data, [
        'associated' => ['EventsParticipationsMeals']
    ]);
    
    // $participation doesn't contains updated data of model associated
    
    if ($this->EventsParticipations->save($participation, ['associated' => ['EventsParticipationsMeals']])) {
        // ...
    }
}
```

My tables :
```php
$this->hasOne('EventsParticipationsMeals', [
    'foreignKey' => 'participation_id',
    'dependent' => true,
]);
```
*Model associated :*
```php
$this->hasOne('EventsParticipations', [
    'foreignKey' => 'EventsParticipationsMeals.participation_id',
]);
```
I looked issue #5292, but it doesn't work.
ps : Validator only works for EventsParticipations data.

**Comment by markstory** [comment]
Your input is incorrect. 

```php
<?= $this->Form->email('EventsParticipations.email', ['id'=>'email']); ?>
```

should be


```php
<?= $this->Form->email('events_participations.email', ['id'=>'email']); ?>
```

Have you checked that all the data from the request is ending up in the entities as you expect? Often times people forget to list their association properties in their entity's `_accessible` property which results in the relations not saving. Also your patchEntity() and save() call do not have `EventsParticipations` in the list of associated models which will affect saving.

**Comment by lorenzo** [comment]
It should be:

`<?= $this->Form->email('email', ['id'=>'email']); ?>`

No need to prefix the field name from the main entity.

**Comment by Testtestom** [comment]
Really thank you @markstory, in EventsParticipation and EventsParticipationsMeal entities, I just add :
```php
protected $_accessible = [
    '*' => true
];
```
And this is solve my issue.

But something seems strange to me when I submit the form without change. The 'ORM' updates `UPDATE events_events SET participation_count = 1 WHERE id = 11` and `UPDATE events_participations_meals SET participation_id = 78 WHERE id = 28`. It's normal?

**Comment by markstory** [comment]
It sounds normal if those fields are changing their values.
