### ISSUE TITLE
3.0 Caching the whole view

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5971]
Hi,

I think that it would help the performance if the whole HTML output for given query could be cached so that also the controller logic would be skipped. At least I was unable to find it in documentation.

Something like this:
```PHP
//Controller
public function index()
{
  $key = md5(json_encode($this->request->query));
  if ($this->cache($key)) {
    return $this->cache($key);
  } else {
    // ... some other expensive logic
    $this->set('articles', $this->paginate($this->Articles));
    $this->respond->saveCache($key);
  }
}
```

My idea of how it could work is that the controller could check the `$this->cache` which could return either HTML ouput or the `Respond` object which would contain the HTML output. And I could tell the Respond object to *save* the HTML to the cache when it's rendered.

Or maybe it can be done automatically in `beforeFilter` that I could tell what key to use, and if the key exists the *action* method would not be triggered. But this is not good because calculating all keys for various actions in the `beforeFilter` is for me not a good idea.

The naming is up to you. This was just for the demo.

I know about the `$this->cache(function() { })` in the view but that is not the same because the controller would be executed anyway.

My main problem is with **pagination**. In my case I find caching the whole `Query` too expensive, and also building a HTML view takes more time. It would be much faster to cache the pure HTML so it can be rendered immediately by next request.

**Comment by lorenzo** [comment]
Given how difficult this was to do in previous versions of cake, I'm not keen on this idea

**Comment by jippi** [comment]
You can do this in a routing filter instead if you really want to implement full view caching :)

**Comment by AD7six** [comment]
You are probably better off handling things like that with e.g. varnish and ESI (if html !== the whole page, in which case you don't need ESI) IMO; the app's responsibility would in that case, more or less, only be to set appropriate cache headers.

[Funky-caching](https://github.com/mcurry/html_cache) is another alternative.

**Comment by markstory** [comment]
I would use varnish or nginx. They yield more signifcant savings than any php implementation ever could.

**Comment by lorenzo** [comment]
Closing as a big group of the core team seems to be in favor of more robust solutions :)
