### ISSUE TITLE
maxLength in FormHelper is too short for decimals

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#5977]
If field type in database is decimal(6,3) and a text input (options: array('type' => 'text')) is generated with maxLength of 6. This makes it impossible to enter for example 123.456

I think there should atleast be space for a decimal separator and probably even for thousand separator(s).

Maybe it is even better to set no maxLength in this special case (decimal using text input). That would be better than a too short maxLength which makes it impossible to enter some valid decimals.

**Comment by ADmad** [comment]
For which version is this?

**Comment by tersmitten** [comment]
2.6.2

**Comment by markstory** [comment]
I'm good for ignoring the maxLength. The HTML is using the scale part of the decimal column as previously it was just generating invalid HTML like `maxlength="6,3"`.

**Comment by markstory** [comment]
Fixed with #5980
