### ISSUE TITLE
Authentication error - Session was already started

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#5978]
I added login functionality in a plugin as described here: http://book.cakephp.org/3.0/en/controllers/components/authentication.html#authentication-objects

My setup in plugin AppController:

```php
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'login', 'password' => 'password'],
                    'userModel' => 'Plugin.CustomUsers'
                ]
            ],
            'authError' => false,
            'authorize' => ['Plugin.Custom'],
            'loginAction' => ['controller' => 'CustomUsers', 'action' => 'login']
        ]);
```

Login action in CustomUsersController:

```php
    public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);

                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
    }
```

When I provide correct credentials, I get RuntimeException 'Session was already started'.

**Comment by segy** [comment]
To be more specific, there is a missing condition `if (!$this->started()) {` in *Cake\Network\Session* on line 559

**Comment by markstory** [comment]
Do you know where the session is being started? I've used similar code numerous times before without issue.

**Comment by AD7six** [comment]
Pocket-closed

**Comment by segy** [comment]
Hi. I am not starting session explicitly. I use this code in *bootstrap.php*:

```php
$request = Request::createFromGlobals();
if (!$request->session()->check('applocale')) {
    $request->session()->write('applocale', $defaultLocale);
}
I18n::locale($request->session()->read('applocale'));
```

**Comment by markstory** [comment]
That implicitly will start the session, and the two session objects will not know that the other started the session. You should make this a dispatcher filter instead of code run in global scope.

**Comment by segy** [comment]
thank you. dispatcher filter was the right choice.
