### ISSUE TITLE
Containable not working for deep relationship

### ISSUE THREAD

**Issue by jodinathan** [cakephp/cakephp#5992]
Hi,

I asked this on stackoverflow: http://stackoverflow.com/questions/28802632/containable-not-working-correctly-with-deep-association

CakePHP 2.6.1 and tried CakePHP 2.6.2 but ended at the same.

I have a Produto(Product) model that belongsTo Titulo(Title). Pedido(Order) hasMany Itens and the Itens belongsTo Produto(Product). however, after I use find(all) using the model Pedido containing Itens with Produto, the next find of Produto, the contain nor the recursive function works, here is an example:

        $proModel = ClassRegistry::Init('Produto');
        pr($proModel->find('first', array('conditions' => array('pro_cod' => 650), 'contain' => 'Titulo')));
        $cart = $pedModel->find('first', array(
            'conditions' => array('ped_cod' => $cart['Pedido']['ped_cod']),
            'contain' => array(
                'Itens' => array(
                    'Produto' => array(
                        'Estadia' => array('Atributo', 'Numero'), 'Produtoplataformas'
                    ), 
                    'Troca', 'Locado', 'Tipo', 
                    'Locacao' => array('Plano', 'Itens')
                ),
                'Usuario'
            ),
            'recursive' => -1
        ));
        pr($proModel->find('first', array('conditions' => array('pro_cod' => 650), 'contain' => 'Titulo')));
        exit;

My debug is level 2 and I switched pr to debug with no difference.
The first pr of $proModel->find works ok and prints the 'Titulo' that is associated, however, after the $pedModel->find, the very same $proModel->find doesn't print the 'Titulo' association.
I have no afterFind method.
I pr($proModel->belongsTo) and it changes after $pedModel->find. All associations vanish except the ones used in the contain section of $pedModel->find.
If I use a new Produto instead of ClassRegistry::Init('Produto'), it worked fine, but I guess this is not a good thing, right?

**Comment by AD7six** [comment]
> If I use a new Produto instead of ClassRegistry::Init('Produto')

That probably indicates that `ClassRegistry::Init('Produto')` isn't an instance of the class you expect (and will be put there indirectly by unshown code). There is no debug output in the description which makes saying more a bit difficult.

**Comment by jodinathan** [comment]
ClassRegistry::Init('Produto') works untill I use the ClassRegistry::Init('Pedido') finding with teh Produto in the containing clause.
pr(Produto->belongsTo) also prints all associations until the Pedido->find mentioned above.

What can I do to help resolve this?

**Comment by AD7six** [comment]
> What can I do to help resolve this?

A good place to start is to **show** any of the debug output that you're referring to.

**Comment by jodinathan** [comment]
The belongsTo of Produto:
Array
(
    [Produtoclassificacoes] => Array
        (
            [className] => Produtoclassificacoes
            [foreignKey] => pro_prcl_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [Produtoplataformas] => Array
        (
            [className] => Produtoplataformas
            [foreignKey] => pro_prpl_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [Titulo] => Array
        (
            [className] => Titulo
            [foreignKey] => pro_tit_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [CI] => Array
        (
            [className] => Classificacoesindicativas
            [foreignKey] => pro_br_cin_cod
            [label] => Classificação Brasileira
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [ESRB] => Array
        (
            [className] => Classificacoesindicativas
            [foreignKey] => pro_esrb_cin_cod
            [label] => Classificação Norte Americana
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [Estadia] => Array
        (
            [className] => Atributovalores
            [foreignKey] => pro_diarias_atva_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

)
The find(first) of Produto with 'contain' => 'Titulo':
/app/Controller/Component/CarrinhoComponent.php (line 134)
array(
	'Produto' => array(
		'pro_cod' => '650',
		'pro_nome' => 'The Last of Us',
		'pro_label' => 'The Last of Us',
		'pro_sku' => 'the-last-of-us-seminovo-ps3',
		'pro_pesquisa' => 'The Last of Us Playstation 3 PS3',
		'pro_slug' => 'the-last-of-us-playstation-3',
		'pro_valor' => '199.00',
		'pro_valorusado' => null,
		'pro_vendastempqnt' => '5',
		'pro_prcl_cod' => '1',
		'pro_barcode' => 'lastofus',
		'pro_criacao' => '2013-07-12 17:31:38',
		'pro_prpl_cod' => '1',
		'pro_diarias_atva_cod' => null,
		'pro_diashabilitados' => null,
		'pro_trocas' => '0',
		'pro_tit_cod' => '1',
		'pro_tempmainimg' => '/img/Produto/2015/01/30/54cc043ea5ccd.jpg',
		'pro_bannerimg' => '/img/Produto/2015/02/16/54e243b7bc9e1.jpg',
		'pro_giant_release_id' => '122697',
		'pro_giant_lastsynced' => '2015-02-02 00:52:13',
		'pro_br_cin_cod' => '1',
		'pro_esrb_cin_cod' => '1',
		'pro_idademinima' => '0',
		'pro_ativo' => '1',
		'pro_flags' => '214023',
		'pro_votosqnt' => '0',
		'pro_votosmedia' => '0.00',
		'pro_releasedate' => '2013-06-14 00:00:00',
		'pro_expectedrelday' => '30',
		'pro_expectedrelmonth' => '6',
		'pro_expectedrelyear' => '2015',
		'pro_expectedrelquarter' => '2',
		'pro_controles' => '{"474":"Controle por Voz"}',
		'pro_multijogador' => '{"485":"Competitivo Online"}',
		'pro_cooperativo' => '{"480":"Co-op Local"}',
		'pro_resolucoes' => '{"503":"720p","505":"1080i"}',
		'pro_valormaximo' => null,
		'pro_descricao' => null,
		'pro_videosqnt' => '0',
		'pro_imgsqnt' => '2',
		'pro_categorias' => '|1||30011||30012||471||474||472||485||470||505||503||29975||480||4||38||98||105|',
		'pro_atributos' => '{"2":"2","1":"5","6":"35","7":"39","8":"41"}'
	),
	'Titulo' => array(
		'tit_cod' => '1',
		'tit_nome' => 'The Last of Us',
		'tit_prti_cod' => '2',
		'tit_giant_game_id' => '36989',
		'tit_giant_lastsynced' => '2015-02-20 16:41:52',
		'tit_flags' => '104',
		'tit_lastupdate' => '2013-12-23 17:52:41',
		'tit_releasedate' => null,
		'tit_expectedrelyear' => null,
		'tit_expectedrelmonth' => null,
		'tit_expectedrelday' => null,
		'tit_expectedrelquarter' => null,
		'tit_criacao' => null,
		'tit_imagem' => null,
		'tit_bannerimg' => '/img/Titulo/2015/02/16/54e243361a5f1.jpg',
		'tit_qntprods' => '1',
		'tit_votosqnt' => '0',
		'tit_votosmedia' => '0.00',
		'tit_generos' => '{"4":"A\u00e7\u00e3o-aventura","38":"Tiro"}',
		'tit_temas' => '{"98":"Horror","105":"P\u00f3s-apocal\u00edptico"}',
		'tit_franquias' => '[]',
		'tit_videosqnt' => '0',
		'tit_imgsqnt' => '11',
		'tit_videosmain' => '44'
	)
)
Executed pedModel->find mentioned in the issue.
Again belongsTo of Produto:
Array
(
    [Produtoplataformas] => Array
        (
            [className] => Produtoplataformas
            [foreignKey] => pro_prpl_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

    [Estadia] => Array
        (
            [className] => Atributovalores
            [foreignKey] => pro_diarias_atva_cod
            [conditions] => 
            [fields] => 
            [order] => 
            [counterCache] => 
        )

)
Again the find(first) of Produto with 'contain' => 'Titulo':
/app/Controller/Component/CarrinhoComponent.php (line 154)
array(
	'Produto' => array(
		'pro_cod' => '650',
		'pro_nome' => 'The Last of Us',
		'pro_label' => 'The Last of Us',
		'pro_sku' => 'the-last-of-us-seminovo-ps3',
		'pro_pesquisa' => 'The Last of Us Playstation 3 PS3',
		'pro_slug' => 'the-last-of-us-playstation-3',
		'pro_valor' => '199.00',
		'pro_valorusado' => null,
		'pro_vendastempqnt' => '5',
		'pro_prcl_cod' => '1',
		'pro_barcode' => 'lastofus',
		'pro_criacao' => '2013-07-12 17:31:38',
		'pro_prpl_cod' => '1',
		'pro_diarias_atva_cod' => null,
		'pro_diashabilitados' => null,
		'pro_trocas' => '0',
		'pro_tit_cod' => '1',
		'pro_tempmainimg' => '/img/Produto/2015/01/30/54cc043ea5ccd.jpg',
		'pro_bannerimg' => '/img/Produto/2015/02/16/54e243b7bc9e1.jpg',
		'pro_giant_release_id' => '122697',
		'pro_giant_lastsynced' => '2015-02-02 00:52:13',
		'pro_br_cin_cod' => '1',
		'pro_esrb_cin_cod' => '1',
		'pro_idademinima' => '0',
		'pro_ativo' => '1',
		'pro_flags' => '214023',
		'pro_votosqnt' => '0',
		'pro_votosmedia' => '0.00',
		'pro_releasedate' => '2013-06-14 00:00:00',
		'pro_expectedrelday' => '30',
		'pro_expectedrelmonth' => '6',
		'pro_expectedrelyear' => '2015',
		'pro_expectedrelquarter' => '2',
		'pro_controles' => '{"474":"Controle por Voz"}',
		'pro_multijogador' => '{"485":"Competitivo Online"}',
		'pro_cooperativo' => '{"480":"Co-op Local"}',
		'pro_resolucoes' => '{"503":"720p","505":"1080i"}',
		'pro_valormaximo' => null,
		'pro_descricao' => null,
		'pro_videosqnt' => '0',
		'pro_imgsqnt' => '2',
		'pro_categorias' => '|1||30011||30012||471||474||472||485||470||505||503||29975||480||4||38||98||105|',
		'pro_atributos' => '{"2":"2","1":"5","6":"35","7":"39","8":"41"}'
	)
)

**Comment by AD7six** [comment]
I don't know what to make of that output. I would start with:

    debug($proModel);
    debug($preModel);
    .. stuff ...
    debug($proModel);
    debug($preModel);

If that doesn't show anything - to get help _here_ you need to provide enough info to reproduce the problem. At the moment you have a problem with your app - app problems are bugs.

**Comment by jodinathan** [comment]
This is the code:

                        pr('Debuging pro and pedmodel');
			debug($proModel);
			debug($pedModel);
			$cart = $pedModel->find('first', array(
				'conditions' => array('ped_cod' => $cart['Pedido']['ped_cod']),
				'contain' => array(
					'Itens' => array(
						'Produto' => array(
							'Estadia' => array('Atributo', 'Numero'), 'Produtoplataformas'
						), 
						'Troca', 'Locado', 'Tipo', 
						'Locacao' => array('Plano', 'Itens')
					),
					'Usuario'
				),
				'recursive' => -1
			));
			pr('AGAIN - Debuging pro and pedmodel');
			debug($proModel);
			debug($pedModel);

Here is the output. I read it and couldn't find anything to add.
Another thing that I didn't mention earlier is that the 'Troca', 'Locado' and 'Plano' are also Produto.

http://meuwebinar.com.br/debug.txt

**Comment by AD7six** [comment]
The purpose of debugging the model instances is to ensure/verify they are of the class you expect and not `AppModel`.

The problem you have is in your model files, which is nowhere in the question - but tickets aren't a debugging service. If you can provide a means to reproduce your problem (that isn't "install my app") we can take a look, but otherwise I suggest identifying the problem _before_ reporting it as a bug.

**Comment by jodinathan** [comment]
Hi,

this is my appmodel as of now for testing purposes

class AppModel extends Model {
	public $actsAs = array('Containable');
}

the result is the same.

I took care of the main problem by creating my own version of contain, as we are only using belongsTo and hasMany for relationship and cakephp's use too many queries with deep relationship. 
I am here to help. I really like Cakephp. 
I guess the best thing to do is to create a new app with nothing but those models with problem to try to reproduce the problem.
I will probably do it by night and paste it here.

**Comment by jodinathan** [comment]
Hi,

I got a fresh install of cakephp, recreated the models without code except the relationships and primaryKeys. It still happens.
Here is the model directory and the test controller.

http://meuwebinar.com.br/files.zip

This is the relationship:

Pedido hasMany Pedidoitens and belongsTo Usuario
Itens belongsTo Produto, Troca(Produto), Locado(Produto), Estoque, Locacao
Locacao belongsTo Plano(Produto) and hasMany Itens(Locacaoitens)
Produto belongsTo Estadia(Atributovalores), Numero(Unidadenumeros) and Produtoplataformas.

What else can I do to help?

**Comment by AD7six** [comment]
Writing a test case. However what I can see is that you duplicate association aliases, pointing at different models:

```
class Locacao extends AppModel {
	public $useTable = 'locacoes';
	
	public $belongsTo = array(
		'Usuario' => array(
			'className' 	=> 'Usuario',
			'foreignKey'	=> 'usu_id'
		),
		'Plano' => array(
			'className'		=> 'Produto',
			'foreignKey'	=> 'pro_id'
		)
	);
	
	public $hasMany = array(
		'Itens' => array( <---
			'className' 	=> 'Locacaoitens',
			'foreignKey'	=> 'loc_id'
		)
	);
```

```
class Pedido extends AppModel {
	
	public $belongsTo = array(
		'Usuario' => array(
			'className' 	=> 'Usuario',
			'foreignKey'	=> 'usu_id'
		)
	);
	
	public $hasMany = array(
		'Itens' => array( <---
			'className' 	=> 'Pedidoitens',
			'foreignKey'	=> 'ped_id'
		)
	);
}
```

That simply won't work and is likely the direct cause of your problems. Rename all aliases to be unique and it'll almost certainly "just work".

**Comment by jodinathan** [comment]
Hi,

Yeah, it is it.
Good, you identified the bug quickly.
Will this be fixed?

**Comment by AD7six** [comment]
The bug is in the zip file - make the aliases unique. Closing as there are no core changes required here.

**Comment by jodinathan** [comment]
Well, I could have fixed the bug, but I guess it is not an error, it is a "feature".

**Comment by AD7six** [comment]
It's not a feature (or a bug), it's a known limitation of how the class registry works.

**Comment by jodinathan** [comment]
Would you mind point me where this limitation is documented please?

**Comment by AD7six** [comment]
[in the book](http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#relationship-types), emphasis also in the book:

> In the above example, the first instance of the word ‘Recipe’ is what is termed an ‘Alias’. This is an identifier for the relationship, and can be anything you choose. Usually, you will choose the same name as the class that it references. However, **aliases for each model must be unique across the app**. For example, it is appropriate to have:

**Comment by jodinathan** [comment]
Thanks.

I searched through containable a lot and couldn't find the reason, I guess it can trouble me in other places.
