### ISSUE TITLE
The tests don't check if Redis is running

### ISSUE THREAD

**Issue by bauerj** [cakephp/cakephp#5993]
I upgraded the CakePHP version that [HHVM's OSS framework test runner](http://hhvm.com/frameworks/) uses: facebook/hhvm#4928 With the new version (3.0.0-RC2) your Travis tests report 100% passing tests. With my local tests I only got like 99%.

I tracked the discrepancy down to the Memcached and Redis tests. You do test whether it is enabled in PHP but not if there is any server running.

This leads to errors like the following:

    There were 13 errors:
    
    1) Cake\Test\TestCase\Cache\Engine\RedisEngineTest::testConfig
    unable to connect to 127.0.0.1:6379 [111]: Connection refused
    cakephp3/tests/TestCase/Cache/Engine/RedisEngineTest.php:82

As this could be quite confusing for anyone running the tests, it would be great if you could make the tests skip if there is no Memached/Redis server running on the standard port.

**Comment by markstory** [comment]
Good idea. :smile:

**Comment by markstory** [comment]
Closing as there is a pull request open now.
