### ISSUE TITLE
Cake Aros_Acos issue

### ISSUE THREAD

**Issue by abraham-homer-j-simpson** [cakephp/cakephp#5997]
hi i have next situation
for some reason i want to add new column to standard Cake aros_acos table
i added _log column and basic logic in cake auth component stop working correctly
i found where it may be bug
\lib\Cake\Model\Permission.php Line: 247
function Get the crud type keys
getAcoKeys($keys) {

there is line in foreach statement:
if (!in_array($key, array('id', 'aro_id', 'aco_id'))) {

so when i add column to the table, Auth component also starts using it in `check` function and i guess this is not correct.

**Comment by lorenzo** [comment]
What does it mean that it stopped working?

**Comment by abraham-homer-j-simpson** [comment]
/**
 * Get the crud type keys
 *
 * @param array $keys Permission schema
 * @return array permission keys
 */
	public function getAcoKeys($keys) {
		$newKeys = array();
		$keys = array_keys($keys);
		foreach ($keys as $key) {
			if (!in_array($key, array('id', 'aro_id', 'aco_id'))) {
				$newKeys[] = $key;
			}
		}
		return $newKeys;
	}

**Comment by abraham-homer-j-simpson** [comment]
it's start to watch to my new added column value to, that mean if in new column `_log` value is not 1 then Auth component deny access to aco

**Comment by abraham-homer-j-simpson** [comment]
now it is:
		foreach ($keys as $key) {
			if (!in_array($key, array('id', 'aro_id', 'aco_id', '_log'))) {
				$newKeys[] = $key;
			}
		}

i think it should be something like this

		foreach ($keys as $key) {
			if (in_array($key, array('_create','_read','_update','_delete'))) {
				$newKeys[] = $key;
			}
		}

**Comment by lorenzo** [comment]
I don't think we have support for adding more columns into that table. What is the usecase that you have?

In the worst case, you can have your own `Permission.php` file in your `app/Model` folder with the custom logic that you need.

**Comment by ceeram** [comment]
iirc, you could add your own columns, and they would work exactly like the
existing crud columns. This sounds more like incorrect storing or checking
of permissions.

2015-03-03 15:00 GMT+01:00 José Lorenzo Rodríguez <notifications@github.com>
:

**Comment by abraham-homer-j-simpson** [comment]
so i it's bad idea to store my own columns in aros_acos table, right?

**Comment by markstory** [comment]
Not if you want them to become permissions.

**Comment by markstory** [comment]
Closing as adding columns add more permissions that are being correctly checked by AclComponent.
