### ISSUE TITLE
3.x File upload field arrays being cast to string

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#5998]
**Back story**
I have a few users now using my upload plugin and have had a bug reported.
https://github.com/davidyell/CakePHP3-Proffer/issues/28#issuecomment-76752224
The gist of which is that instead of the filename being saved to the database it's just storing 'Array'.

**Scenario**
I have setup my form correctly in my test application with `type => form` and my input `type => file`. When I submit my data the request data contains the array of upload information from `$_FILES` as expected.

When I dump the entity, after `$team = $this->Teams->patchEntity($team, $this->request->data());` I can see that in my example the `image` field just contains `Array`.

**Possible bug point**
When debugging I can see this `Notice (8): Array to string conversion [CORE/src/Database/Type.php, line 193]`. I think this is because the field in the db for me is `VARCHAR(255)` so the data type is string in the db. This is causing the datatype class to cast the array to string.

**Sidestep**
It seems I can sidestep this by creating my own data type which doesn't cast the data in any way.

**Expectation**
As you can create a file upload field with the FormHelper I think this will potentially affect any file fields, and also anyone trying to get array data to any callback after the marshaller has done it's work, because the field will already be cast.

**Comment by ADmad** [comment]
In my opinion your behavior is wrongly architectured. Don't use the same entity property for the db value as well as uploaded file. Use a separate field in form for file upload and then after processing update the db field with the filename.

**Comment by davidyell** [comment]
Does this cover your concerns @ADmad https://github.com/davidyell/CakePHP3-Proffer/issues/46 ?

**Comment by ADmad** [comment]
No

**Comment by davidyell** [comment]
Feel free to open an issue for the plugin to outline your thoughts, so we don't sidetrack this ticket.

**Comment by ADmad** [comment]
If/when I get the time i will :)   

Coming to the particular issue at hand of "Array" being saved in field, the problem lies in your behavior not the core code. You need to ensure that the field gets set to a string before cake tries to save the issue.

**Comment by davidyell** [comment]
So I should be dealing with my data handling in `beforeMarshal()`?

**Comment by ADmad** [comment]
Ideally you should be using a separate field for the file upload imho.

**Comment by hmic** [comment]
davidyell: if your file-upload field from the form which holds the array is not in the accessible list, it will not get marshalled IMHO. but maybe it does not make it through to your callback at all.

**Comment by lorenzo** [comment]
Either a separate field or using a different Type class for that column should de done. For example dates are sent as an array from the forms, but the DateTimeType class converts it into the right object, this is what needs to happen in your case.

**Comment by davidyell** [comment]
Either of provided solutions don't actually solve the problem. They merely sidestep it. Even using a different field it would still need to be processed in the `beforeMarshal()` so that it doesn't get cast to a string.

I think that this kind of behaviour forces people to move their logic up the event chain. My first reaction was to move all my `beforeSave` data processing into `beforeMarshal` which causes even more problems.

So the real solution seems to be actually store the upload details in the session and then process it much later. Which seems more valid, but my expectation was that data would survive intact before reaching `beforeSave` whereas it seems that the framework changes my request data when it's merged with an entity. My entity doesn't know what sort of data it's properties hold, so why are rules which are for translation into a database, therefor to do with persistence, being imposed on my entity object?

If I wasn't persisting my entity to a database, but transmitting it to somewhere else the data would already by munged through the marshalling process.

**Comment by lorenzo** [comment]
You have plenty options, you can either handle the upload in the controller, you can use the beforeMarshal hook, you can use custom database Type class or you can have a different field name and use a beforeSave.

I think the amount of possible solutions is enough, specially given that we'd like people using more the Type classes than handle form data in the Table classes.

**Comment by CauanCabral** [comment]
You can see how to use different Entity field for upload here https://github.com/Xety/Cake3-Upload

**Comment by ADmad** [comment]
@davidyell Checkout the plugin @CauanCabral linked. You won't get any issues if you use the same approach.

**Comment by markstory** [comment]
I use different fields in my uploads as well. Using 'mapped' properties invokes the fury of the marshaller - which is a good thing imo.

**Comment by davidyell** [comment]
![Marhal's Fury](http://i.imgur.com/9ZKJNn6.png)

**Comment by markstory** [comment]
:clap:

**Comment by lorenzo** [comment]
You win the internet today @davidyell
