### ISSUE TITLE
3.0 Missing 'modelClass' in Bake TemplateTask

### ISSUE THREAD

**Issue by djamesfar** [cakephp/cakephp#6003]
function _loadController in TemplateTask lists in it's compact statement 'modelClass', but doesn't actually define it in the function. Shell/Task/TemplateTask.php:line286.
I added the following to correct it:
```
$modelClass = $this->modelName;
```
just before the compact() is returned.

v 3.0.0RC2

**Comment by markstory** [comment]
How can someone reproduce the error you're getting?

**Comment by djamesfar** [comment]
I was creating a theme template that includes an update variable in all
views(view, index, form), to expose the current model name to the layout,
so it can set the value in a cell used to update a menu:

<?= $this->assign('activeMenu', $modelClass)  ?>

In the default layout I then set it in a call to a cell that creates the
menu.  The menu in the cell's display.ctp has all the menu elements' id's
set to the model names.  I call some js to add an 'active' class to the
<li> whose id matches the 'activeMenu' (modelClass) value.

The only place I can see that informs what variables are available in the
template is in TemplateTask, which says that modelClass is in the compact()
list returned by that function.  It lists it, but it isn't actually set in
the function.
I can't really use any of the others ($singularHumanName, etc.).

$modelClass was available in 2.6 and prior, I'm pretty sure.

Regards,
DJ Far

**Comment by markstory** [comment]
Thanks, I'll take a look.

**Comment by markstory** [comment]
Closing as cakephp/bake#52 is open now.
