### ISSUE TITLE
3.0 bake creates fake associations in Table classes

### ISSUE THREAD

**Issue by djamesfar** [cakephp/cakephp#6004]
When a foreign key is created in a hasMany table and it is renamed from the naming conventions, Bake creates a fake model class for it.  This breaks when baking view templates.

Our example:
We have users and blogs.  blogs has two references to users id field: blog_author_id and intro_author_id (two different people in the users table).  When baked, the BlogsTable will have:
```
$this->belongsTo('BlogAuthors', [
            'foreignKey' => 'blog_author_id',
            'className' => 'BlogAuthors'
        ]);
        $this->belongsTo('IntroAuthors', [
            'foreignKey' => 'intro_author_id',
            'className' => 'IntroAuthors'
        ]);
```
Neither BlogAuthors nor IntroAuthors have tables and therefore no classes, as none are needed.
When baking the views for Blogs (or *templates* in 3.0), bake hurls the following:
>SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx.blog_authors' doesn't exist in (...)

and the same for the other non-table.
In Cake 2.6, I just had to go into the Blogs model and change 
```
->belongsTo('BlogAuthors',
```
to:
```
->belongsTo('Users',
```
but that no longer cuts it in 3.0.0RC2.

I believe the errant code is in ModelTask::findBelongsTo function (line 255):
```
 $tmpModelName = $this->_modelNameFromKey($fieldName);
                $assoc = [
                    'alias' => $tmpModelName,
                    'foreignKey' => $fieldName
                ];
```
Look closely at the _modelNameFromKey() function which simply infers from conventions the name of the model - fine, but it never checks to see if this is an actual table.  Perhaps this is why it is assigned to a variable named 'tmp'; maybe it was intended to check whether it was a table before adding it to the associations table:
```
[line 265] $associations['belongsTo'][] = $assoc;
```

**Comment by markstory** [comment]
Why are you not changing the 'className' key? That tells the ORM which table class it should be using for the association.

Historically bake has never checked association table names. If it did would you prefer that bake omitted associations it could not recognize?

**Comment by djamesfar** [comment]
I'm changing the className to 'Users'.  I thought it would check the actual
references for the foreign key in the information_schema table, and replace
the className with the actual table that foreign key is referencing (in
this case the Users table).

DJ

**Comment by markstory** [comment]
Bake _could_ do that but doesn't do that presently. Relying on foreign keys is a bit dicey though as tons of people don't use them - which is one of the main reasons bake uses conventions instead.

**Comment by djamesfar** [comment]
I see what you mean, Mark.  I would think it should only go fetch the
actual table referenced by the foreign key if it found the table derived by
the conventions didn't exist.

We've got a social website with around 120 tables, and I'm having great
success heavily modifying the bake templates so they create exactly the
forms, views, etc. that we want (even putting in all the User controller
login methods and stuff we use).  That way if I make database changes and
sync my model to the database, I can run bake again against the whole
database (I have a script that executes a mysql 'show tables' and runs bake
model, controller, views on all 122 of them).
I'm taking it up to 3.0 and learning a lot.  Having the most growing pains
on the ORM, I'm afraid, but I'll figure it out...

Thanks for your prompt response!

Regards,
DJ Far

**Comment by jhli** [comment]
Take a look at CRUD and CRUD view

**Comment by markstory** [comment]
@djamesfar I think looking at the other table names could work, but in your scenario it would have resulted in _no_ associations. Is that better or worse than having associations that are not 100% correct?

**Comment by djamesfar** [comment]
No, clearly it is better to have something created so there is at least a
stub that you can update to the correct class model.
I think I'll have a go at writing a bit of code that checks whether the
association inferred by the foreign key maps to an actual table, and if
not, check information_schema's indexes to find what table the foreign key
references. This would be a MySQL-only solution; eventually it should
abstract the database.
By the way, in 2.x when I made a change to Cake's modelTask, etc., I copied
my changed version into the app/ directory, and bake would look there first
and use that version before the lib/ version.  That way I don't lose my
changes when updating Cake core.
But in 3.0 when I copy the file to the equivalent directory under src/,
bake throws an error that I can't redeclare the class.  Where do I put
modified tasks under src/,  and do I have to configure something?

Thanks.

**Comment by djamesfar** [comment]
Mark,

Actually, in my scenario it would have resulted in setting 'Users' as the
className instead of BlogAuthors and IntroAuthors, as it would have found
the correct reference of those two foreign keys (Blogs.intro_author_id and
Blogs.blog_author_id) to the Users table in the information schema.

DJ

**Comment by djamesfar** [comment]
Mark,
I updated ModelTask::findBelongsTo function to check whether the inferred table name exists in the database, if not, calls a  function that queries the information_schema database to find the actual table.  ModelTask then correctly updates the belongsTo in the modelTable file.
It checks the connection and bails if the driver is not MySQL.

All told it is about 11 lines of code:
Here's the check in findBelongsTo (line 257)
```
     // check to see that this is an actual table
    $tableName = Inflector::tableize($tmpModelName);

    if (!in_array($tableName, $this->_tables)){     // if tableized modelName not in table list
        // find who it actually references
        $tableName = $this->findActualTableReferencedBy($fieldName);
        if (!empty($tableName)){                            // if a table was found,
            $tmpModelName = Inflector::camelize($tableName);// inflect it back to className
        }
    }
```
And here's the function:
```
/**
 * findActualTableReferencedBy
 *  table inferred by the keyfield in modelNameFromKey doesn't exist (keyfield didn't/couldn't follow naming conventions);
 *  this will find and return the actual table it references.
 *
 * @param $keyField
 * @return string
 */
public function findActualTableReferencedBy($keyField){
    $sql =  "select REFERENCED_TABLE_NAME from information_schema.KEY_COLUMN_USAGE where COLUMN_NAME='$keyField'";
    $conn = ConnectionManager::get($this->connection);
    if (!preg_match('/Mysql/',$conn->driver()['driver'])) return '';  // sql only guaranteed for MySQL
    $table = $conn->execute($sql)->fetch();
    return $table[0];   // if no results returns empty, else table name
}
```
DJ

**Comment by markstory** [comment]
Instead of directly referencing information_schema you should be able to use a Table's schema() method to access reflected schema inclusive of foreign keys.

As for replacing bake, it is now a plugin so simply dropping files in src/ won't work as well. At least not until cakephp/bake#50 is resolved.

**Comment by djamesfar** [comment]
What table's schema would you look in?  The problem with using the Table's
schema is that you don't know which table to look in to search for a
matching key field.  The reason we're searching for it is because it was
created without the conventions, so we're not able to infer the table by
the key field name (if it were instead eg. user_id)  We need
information_schema because it allows us to search it's KEY_COLUMN table by
column_name, showing us which table this key exists in.

In looking into CakeSchema, it looks like the ::read() method builds a list
of all table objects for the schema in the give connection, complete with
columns and indexes.  That would be a preferable approach as it would work
for any driver (not just MySQL).  I'll check that out.

DJ

**Comment by djamesfar** [comment]
Here is the function, re-written using Cake schema classes, so it's database-independent:

```
/**
 * findTableReferencedBy
 *   finds the actual table in database referenced by the passed keyField string
 *   returns empty if not found
 *
 * @param null $keyField
 * @return mixed
 */
public function findTableReferencedBy($keyField = null){
    $db = ConnectionManager::get($this->connection);
    $schema = $db->schemaCollection();
    $tables = $schema->listTables();
    if (empty($tables)) return null;

    foreach ($tables as $table){
        $meta = $schema->describe($table, ['forceRefresh'=>true]);  // get meta data for this table
        if (!in_array($keyField, $meta->columns())) continue;       // if field isn't in this table, go to next table

        $constraints = $meta->constraints();                        // get list of constraints for table

        foreach ($constraints as $constraint){
            $constraint_info = $meta->constraint($constraint);      // get info about each constraint
            if(in_array($keyField, $constraint_info['columns'])) {
                return $constraint_info['references'][0];           // found it, pass back the table name
            }
        }
    }
    return null;
}
```
Regards,
DJ Far

**Comment by markstory** [comment]
@djamesfar Looks like that would work ok. We would need to coalesce the foreign key check with basic conventions if the foreign key lookups missed.

**Comment by djamesfar** [comment]
Mark,
Actually, if the search finds no referenced table, the function behaves as
it does now, producing the class name using conventions.  This only returns
a result if a table referenced by that keyfield was actually found.

So if a field named 'blog_author_id' returned no referenced table, then the
function would create the class BlogAuthors, as it currently does.

DJ

**Comment by markstory** [comment]
Good point, I didn't re-read the previous code snippets.

**Comment by lorenzo** [comment]
@djamesfar would you be able to create a pull request out of this code?

**Comment by djamesfar** [comment]
Sure, I may need a bit of guidance the first time through.  Can I just pull
the ModelTask.php file, do I pull from the 3.1 branch?
DJ

**Comment by djamesfar** [comment]
created a pull request in cakephp/bake

**Comment by markstory** [comment]
Closing as cakephp/bake#54 is open now.
