### ISSUE TITLE
3.0 save in afterSave causes infinite loops

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#6006]
In my situation I need to update the just saved entity in the `afterSave` callback.
This causes an infinite loop in phpunit.

I have searched for a way to disable the callbacks via the save-options but couldn't find it.
Is there a solution, or is it an idea to create a disable-option for the callbacks?

**Comment by lorenzo** [comment]
Pass an option in the save array to hint your event that it should not be executed next time.

**Comment by bobmulder** [comment]
I think that's a dirty solution but yeah, it would work....

**Comment by lorenzo** [comment]
@bobmulder If you don't need any events at all, use `updateAll`

**Comment by bobmulder** [comment]
@lorenzo Thanks ;)

**Comment by MrXavierLin** [comment]
Errr, i think it is a very dirty solution
```
    public function afterSave($event, $entity, $options)
    {
       	if($entity->skipAfterSave) return;
    	//Rebuild full names
    	$this->eventManager()->off('Model.afterSave');
    	$data = $this->find();
    	foreach($data as $datum) {
    		$datum->full_name = $this->getFullName($datum->id);
    		$datum->skipAfterSave = true;
    		$this->save($datum);
    	}
    }
```

**Comment by augusto-cdxs** [comment]
I solved this issue creating this helper method in my base table class:
```
public function saveNoCallbacks($entity)
{
    $dirtyFields = $entity->extract($this->schema()->columns(), true);
    $result = (boolean) $this->updateAll($dirtyFields, ['id' => $entity->id]);
    $entity->clean();

    return $result ? $entity : false;
}
```
