### ISSUE TITLE
3.0 Call AuthComponent::user() in a view set AuthComponent $this as Cake\View

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#6007]
if you call AuthComponent::user() in a view, in the user function $this is set as a Cake\View Object and throw a missing helper exception

**Comment by lorenzo** [comment]
There is no usage of `$this` in `AuthComponent::user()`

**Comment by lorenzo** [comment]
Oh this was for 3.0... In that case `AuthComponent::user()` is not a static class function, so it cannot be sued that way.

**Comment by doshu** [comment]
thanks for reply, but this is a strange behavior. calling AuthComponent::user() statically should be throw an error for the using of $this, insted $this is replaced by a Cake\View object.

**Comment by lorenzo** [comment]
@doshu I entirely agree, that is one of the most awkward things that PHP does and that I think they will remover in version 7
