### ISSUE TITLE
3.0 Tree behavior throws error with level config option

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#6010]
```php
// Table
public function initialize(array $config)
{
    $this->addBehavior('Tree', ['level' => 'depth']);
}

// Controller
$entity = $this->Table->newEntity([ ... ]);
$this->Table->save($entity);
```

Error is thrown on [line 117](https://github.com/cakephp/cakephp/blob/3.0/src%2FORM%2FBehavior%2FTreeBehavior.php#L117) because it is looking for `$config['depth']` instead of `$config['level']`.

**Comment by ADmad** [comment]
Closing as PR is opened.
