### ISSUE TITLE
$this->request should be accessible in components

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#6014]
Hello,
the request should be accessible directly from a component's method. 
At the moment the only way is:
```
$this->_registry->getController()->request
```
why not $this->request ?

**Comment by ADmad** [comment]
:+1: That would be a nice convenience to have. Even in helpers you have reference to request instance using `$this->request` and don't have to use `$this->_View->request`.

**Comment by ADmad** [comment]
Closing as PR is opened.
