### ISSUE TITLE
Cake server not working

### ISSUE THREAD

**Issue by dhiman252** [cakephp/cakephp#6025]
I tried to start working with the cake server but it issues the following error when i try to access it from 
http://localhost:8765/

moreover the link http://localhost:8889/ shows a white screen.

I have installed the application through composer-> php composer.phar create-project --prefer-dist -s dev cakephp/app bookmarker
 and after installation i changed the database configuration
return [
    // More configuration above.
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => 'localhost',
            'username' => 'root',
            'password' => '',
            'database' => 'cake',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
        ],
    ],
    // More configuration below.
];

Still it issues the following error

[Sat Mar 07 12:16:12 2015] PHP Fatal error:  Trait method _defaultOptions has no
t been applied, because there are collisions with other trait methods on Cake\OR
M\Association\HasMany in D:\xampp\htdocs\bookmarker\vendor\cakephp\cakephp\src\O
RM\Association\HasMany.php on line 157

**Comment by markstory** [comment]
What version of php are you using? Is there a reason your ports do not match?

**Comment by dhiman252** [comment]
I  am using cakephp v 3.0  RC2

**Comment by markstory** [comment]
Ok, but what version of PHP are you using? Also why do your ports not match?

**Comment by dhiman252** [comment]
PHP version 5.5

**Comment by markstory** [comment]
Odd, I don't get the same error locally with PHP 5.5.19.

**Comment by dhiman252** [comment]
I have the PHP version 5.6.3
i have downloaded fresh cakephp 3.0 RC2 and installed it and changed the database config still i get this error http://prntscr.com/6g8t8o

**Comment by dhiman252** [comment]
I am facing Same Issue is with PHP Version 5.4.12
http://prntscr.com/6g8ypo

and with PHP Version 5.6.3
http://prntscr.com/6g8zsf

Error Screen
http://prntscr.com/6g908p

**Comment by lorenzo** [comment]
It looks like you are running an old version of CakePHP 3, also make sure
you have at least PHP 5.4.16

**Comment by dhiman252** [comment]
I have installed the cakephp via composer and also downloaded the from github but still the same issue occurs irrelevant of PHP version, since the same issue is with  PHP Version 5.6.3(i have added the screens shots also)
http://prntscr.com/6g8zsf

Error Screen
http://prntscr.com/6g908p

**Comment by ceeram** [comment]
latest 3.0 does not have anything on line 157 of that class, so it seems you didnt install latest version of 3.0: https://github.com/cakephp/cakephp/blob/3.0/src/ORM/Association/HasMany.php#L157

**Comment by dhiman252** [comment]
I have now installed a fresh cakephp using the following command:
php composer.phar create-project --prefer-dist -s dev cakephp/app [app_name]

From this link http://book.cakephp.org/3.0/en/installation.html

Following are the screenshots
http://prntscr.com/6gabml
http://prntscr.com/6gac9q
http://prntscr.com/6gaddy
http://prntscr.com/6gadr9

Still the same issue.

**Comment by bravo-kernel** [comment]
There must be something wrong with your setup. I just created a fresh Cake3 app two seconds ago and it runs exactly as expected and the browser displays all pages good too:

```bash
 bin/cake server -H 0.0.0.0 -p 8765
```

**Comment by dhiman252** [comment]
Its not working at all at my end.
