### ISSUE TITLE
`Model::$whitelist` no longer available in `afterSave` in Cake 2.6

### ISSUE THREAD

**Issue by ElteHupkes** [cakephp/cakephp#6028]
I have some code which uses `Model::$whitelist` to check in `afterSave` whether a certain field was included in the last save. With the upgrade to CakePHP 2.6, this behavior all of a sudden stopped working. After inspecting the changes to `Model.php`, the reason for this has become clear. Up to Cake 2.5.8, resetting the whitelist to its pre-save state would be the [last statement in `Model::save()`](https://github.com/cakephp/cakephp/blob/2.5.8/lib/Cake/Model/Model.php#L1896). As of Cake 2.6 however, [the whitelist is cleared before `afterSave` is called](https://github.com/cakephp/cakephp/blob/2.6.2/lib/Cake/Model/Model.php#L1944). 

The statement to reset the whitelist should to be called after `afterSave` again, if only for consistency with earlier Cake versions.

**Comment by markstory** [comment]
Fix in #6030

**Comment by ElteHupkes** [comment]
Woah, that was fast; awesome job guys!

**Comment by markstory** [comment]
Welcome. It was a pretty simple fix.

**Comment by ElteHupkes** [comment]
Haha well, I often find the correlation between the complexity of the fix and the time it takes to fix it to be weaker than one would expect - especially if creating a pull request on GitHub is essentially more work than the fix itself ;).
