### ISSUE TITLE
3.0 - Router's url filters could be improved

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#6038]
URL filters were added as a more generic replacement for 'persist' option for routes in 2.x. It does it's job nicely allowing one to modify the url as required before it's matched.

But the caveat is each filter is run for every call to Router::url() with a url array which can be wasteful. It also means you have to add conditions in the filter if one wants the url to be modified only for some url schemes. eg. check for particular controller or prefix.

So it would be nice if one could also set filter per route.

**Comment by markstory** [comment]
If you could set a filter per route, why not use custom route classes?

**Comment by ADmad** [comment]
Because making a custom route class won't be as convenient as potentially doing:

```php
$routes->connect(
    '/foo/bar',
    [...],
    ['filter' => function() { ... }]
);
```

Also say I want to make a plugin which adds a route which persists `:lang` route element and I made the custom route class by extending `DashedRoute`, anyone who prefers using `InflectedRoute` would be unhappy.

**Comment by markstory** [comment]
I would rather we restore the `persist` option than add per route filters.

**Comment by ADmad** [comment]
I am okay with restoring `persist` option :)

**Comment by markstory** [comment]
Closing as the persist option was re-added and I think that solves the major concern that @ADmad had.
