### ISSUE TITLE
3.0 Entity - Cannot detect dirty when using associated entities

### ISSUE THREAD

**Issue by trungtan** [cakephp/cakephp#6039]
Here is my example code of update a User associated with Language
```
$user = $this->Users->get($page, [
            'contain' => ['Languages']
        ]);
        if ($this->request->is(['post', 'put'])) {
            $this->Users->patchEntity($user, $this->request->data, [
                'associated' => [ 'Languages' ]
            ]);
            //checking dirty here
         }
```
While I don't change anything in edit form:
* ``` $user->dirty() ``` would be True, while all properties have dirty is False except **language** field has dirty is True.
* ```$user->language->dirty()`` would be False

I think it because, right at the **$user** entity, CakePHP cannot detect **language** property is dirty or not. I expect a flag to allow the **entity** function work recursively or not.

**Comment by lorenzo** [comment]
It is not a bad idea to check a last time the dirty status of the related entity before marking the property as dirty as well. I'll take a look and see if this is something that can be done before the stable release
