### ISSUE TITLE
3.0: PluginAssetsShellTest.php invalid?

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#6040]
Hey,

Just a check. I run the tests for the PluginAssets (forked by me): `phpunit tests\TestCase\Shell\PluginAssetsShellTest.php`. 

The result:
Tests: 6
Assertions: 0
Skipped: 6

Is that right?

**Comment by ceeram** [comment]
Those tests are skipped on Windows:

https://github.com/cakephp/cakephp/blob/3.0/tests/TestCase/Shell/PluginAssetsShellTest.php#L42
