### ISSUE TITLE
Treebehavior getPath 

### ISSUE THREAD

**Issue by japita-se** [cakephp/cakephp#6044]
Cake 2.5
In getPath() method, there is (around line 520)

$result = $Model->find('first', array(
			'conditions' => array($Model->escapeField() => $id),
			'fields' => array($left, $right),
			'order' => false,
			'recursive' => $recursive
		));

Where $left and $right are defined?
To me, it seems they aren't.

**Comment by AD7six** [comment]
[Here](https://github.com/cakephp/cakephp/blob/2.5.8/lib/Cake/Model/Behavior/TreeBehavior.php#L479).

In future please note:

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by japita-se** [comment]
Thank you!
