### ISSUE TITLE
Controller Subdirectories

### ISSUE THREAD

**Issue by ninja4826** [cakephp/cakephp#6045]
Is there currently a workaround for CakePHP 3 to include custom subdirectories in the various src/ folders?

For example: 
```
src/
    Model/
        Entity/
            Parts/
                Part.php
                Category.php
        Table/
            Parts/
                PartsTable.php
                CategoriesTable.php
    Controler/
        Parts/
            PartsController.php
            CategoriesController.php
    etc..
```

**Comment by markstory** [comment]
Yes. There is both [prefix routing](http://book.cakephp.org/3.0/en/development/routing.html#prefix-routing) and [plugins](http://book.cakephp.org/3.0/en/development/routing.html#plugin-routing). Plugins do not necessarily have to be external repositories and can live in the `/plugins` directory of your application.
