### ISSUE TITLE
\Cake\Cache\Cache::groupConfigs cause exception

### ISSUE THREAD

**Issue by DnSu** [cakephp/cakephp#6048]
Below is straight from the Cake 3 documentation. Cache::groupConfigs() throws an "Invalid cache group article" exception.
```
\Cake\Cache\Cache::config('site_home', [
	'className' => 'File',
	'duration' => '+999 days',
	'groups' => ['comment', 'article']
]);
$configs = \Cake\Cache\Cache::groupConfigs('article');
foreach ($configs['article'] as $config) {
	Cache::clearGroup('article', $config);
}
```

**Comment by markstory** [comment]
That code works fine for me with the current head of 3.0. There was a similar issue #5894 reported that has since be fixed. Please try updating you copy of CakePHP.

**Comment by DnSu** [comment]
thanks. updated to latest commit, the problem seems to be gone. appreciate the hard work.
