### ISSUE TITLE
Dynamic mutators for entities?

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#6052]
It would be nice if tables and mostly behaviours would allow me to modify an entity on the fly.

I would propose to add a method like `EntityTrait::addMutator($property, $mutator)` that would allow dynamic mutators. Inside EntityTrait::get() we can do this:

```php
        if (isset($this->_mutators[$property])) {
            return $this->_mutators[$property]($value);
        }
```

It would be even possible to have multiple mutators for a single property if we do a check if is_array() for `$this->_mutators[$property]` and iterate over them. The order would be determined by the order in which the callables were put into the array.

**Comment by davidyell** [comment]
What are the potential use-cases for this? Just so I understand it better.

**Comment by burzum** [comment]
I ran into the problem that I needed to dynamically add something like this to the entity.

https://github.com/burzum/tags/commit/fa58f1230d7a5b452ae45f2fd7858873618dd530.

This was done in the afterFind() callback in CakePHP2 but the afterFind() callback is gone now.

**Comment by josegonzalez** [comment]
You can maybe use `query->formatResults()`?

**Comment by davidyell** [comment]
Wouldn't your plugin provide a custom find method which used a results formatter?

**Comment by markstory** [comment]
Result formatters or mapReduce callbacks are the way to do afterFind in 3.x

**Comment by burzum** [comment]
I'll try that today, hopefully, got another task in my way.

**Comment by burzum** [comment]
I think we can close this.
