### ISSUE TITLE
Non existing controller action errror message on normal & scaffolded controller

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#6061]
CakePHP 2.6.2
Calling a non existing controller action
http://localhost/cakephp_app/ports/foo

On a scaffolded controller produces a different errror message than on a non-scaffolded one.
With scaffolding __Ports__ instead of __PortsController__.

```` php
class PortsController extends AppController {
	/**
	 * Scaffold
	 *
	 * @var mixed
	 */
	public $scaffold;
}
````

> __Missing Method in *Ports*__
Error: The action foo is not defined in controller Ports
Error: Create Ports::foo() in file: app\Controller\Ports.php.
```` php
<?php
class Ports extends AppController {
	public function foo() {
	}
}
````

```` php
class PortsController extends AppController {
}
````

> __Missing Method in *PortsController*__
Error: The action foo is not defined in controller PortsController
Error: Create PortsController::foo() in file: app\Controller\PortsController.php.
```` php
<?php
class PortsController extends AppController {
	public function foo() {
	}
}
````

I presume this could be intended though.
It's just a bit surprising...

**Comment by markstory** [comment]
I can get this fixed.
