### ISSUE TITLE
Error: SQLSTATE[70100]: <<Unknown error>>: 1317 Query execution was interrupted

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#6062]
Hi,
I quite often have this kind of error on my online website.
I'm hosted at OVH so I doubt that could be caused by a technical problem on their side.

Any idea?

**Comment by markstory** [comment]
Sounds like your queries are being interrupted :)

A quick google search turns [up some](http://stackoverflow.com/questions/17354229/query-execution-was-interrupted-error-1317) results [for this error](https://www.drupal.org/node/756580). Sounds like you have timeout issues with MySQL.
