### ISSUE TITLE
3.0 belongsToMany association without cascade deletion

### ISSUE THREAD

**Issue by Tietew** [cakephp/cakephp#6063]
When I delete an entity which have a blongsToMany association,
CakePHP always DELETE the "through" data.
Because BelongsToMany::cascadeDelete() method doesn't check dependent flag.

I want to use belongsToMany association WITHOUT cascade deletion like normal hasMany associations.
The reason is same as hasMany. I use database constraints.

**Comment by markstory** [comment]
We have to delete the joint table data because of constraints. If your constraints don't cascade (often times they don't) then the ORM needs to remove data or constraints would fail.

**Comment by markstory** [comment]
I guess it is reasonable for the association to give the option to have the ORM manage the dependent associations, or the constraints though.
