### ISSUE TITLE
2.6.2: cake bake ignores DECIMAL(10,2) NOT NULL (missing validation by convention)

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#6066]
My schema:
```mysql
CREATE TABLE `tariff_group_option_values` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `created_by` int(11) unsigned NOT NULL,
  `updated_by` int(11) unsigned NOT NULL,
  `tariff_group_option_key_id` int(11) unsigned NOT NULL,
  `label` varchar(1024) NOT NULL DEFAULT '',
  `value` varchar(50) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `sorting` int(11) unsigned NOT NULL,
  `is_deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
```

cake bake -p Fooplugin TariffGroupOptionValue
Successfully bakes model... also controller and view bakery are not of an issue.
Issue: the field ```price```misses entirely. @hmic did a cross check and it seems to be the same issue on his side. 

Debugging:
It seems ModelTask::fieldValidation() does not treat type decimal.
I did a dirty debug($metaData['type']) and in my cake bake output it shows "decimal" e.g. the type is correctly detected but not correctly handled.

It should:
1. decimal should be detected
2. I can't figure out how to set it to decimal with digit quantity set to whatever defined in sql (2, 3, 4 etc)... just adding $guess = $methods['decimal']; does work, it adds 'rule' => array('decimal'), to my model. It does not correctly add digits but for generated template it works fine allowing integers and decimals (validated) - mysql treats those integers as decimal by adding .00

I will setup a PR.

**Comment by markstory** [comment]
Closing as there is a pull request now.
