### ISSUE TITLE
entity's dirty being reset before afterSave is called

### ISSUE THREAD

**Issue by aydot** [cakephp/cakephp#6069]
is there a reason for resetting the dirty properties before the afterSave is called?
I want to use the data that were successfully saved in my afterSave logic but 
```
$newData = $entity->extract($entity->visibleProperties(), true);
```
 returns empty.

**Comment by markstory** [comment]
Because the entity has been saved, and is no longer dirty?

**Comment by aydot** [comment]
how do i access the saved data in the afterSave function ?

**Comment by markstory** [comment]
Well the entity contains all the saved data. If you need to know which specific columns were changed, you can track them in a beforeSave and then act on that data in the afterSave.

**Comment by dakota** [comment]
You also have access to getOriginal() and its friends.
