### ISSUE TITLE
User login and redirect to page where previous user in.

### ISSUE THREAD

**Issue by nizam27391** [cakephp/cakephp#6071]
Hi. 
I faced this issue in many projects built in CakePHP.
So the issue is this, let say I have two user.

When UserOne logout, then a new UserTwo login, the new UserTwo is redirected to previous page where UserOne left.

I implement the login and logout as in the documentation :
http://book.cakephp.org/2.0/en/core-libraries/components/authentication.html

Is there any additional thing that I have to clear like clearing the Session or anything?

I know that this is not really a major issue as one people should only be responsible to one account in real life. But we as developer did the training and this issue pops up to the client and they question the security.

Thanks.

**Comment by markstory** [comment]
You can clear all the session data in your logout method if you need to. Seethe session component docs for how to use delete() or clear().

**Comment by ADmad** [comment]
@markstory `AuthComponent::logout()` already deletes the `Auth.redirect` session key but if in your `logout()` action you redirect back to `login()`, the referrer stays the same as the page you logged out from and `Auth.redirect` again gets set to that URL.

**Comment by markstory** [comment]
Ok. Is that really an issue though? I don't know if it is worth trying to fix when you can just ignore Auth.redirect in your application if you find how it behaves to be problematic.

**Comment by ADmad** [comment]
Probably not an issue. Just providing explanation for why the "issue" occurs :)

**Comment by nizam27391** [comment]
@ADmad .. yes.. the logout redirect back to login().. 
@markstory .. so to fix this.. I will just need to clear all the session manually is it . That will fix the issue?

Thanks very much. :)

**Comment by markstory** [comment]
@nizam27391 I think so, or not use the auto redirect feature of AuthComponent when people log in.

**Comment by ruby164** [comment]
Unable to navigate the Standing page, when we login how can i
