### ISSUE TITLE
PHP Fatal error:  Call to undefined method I18n::insertArgs()

### ISSUE THREAD

**Issue by niekutis** [cakephp/cakephp#6072]
Updating cakephp version from 2.5.6 to 2.6.1 i got error:
PHP Fatal error:  Call to undefined method I18n::insertArgs() in cakephp-2.6.1/lib/Cake/basics.php on line 638

script is executed from shell:
php /var/www/cakephp-2.6.1/lib/Cake/Console/cake.php -app path/to/app nameapp

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by niekutis** [comment]
Found where was problem. 
I uses for apps CAKE_CORE_INCLUDE_PATH to point cakephp version
In my app Config/core.php Configure::write('debug', 0);
In my app Config/bootstrap.php Configure::write('debug', 1);
When i changed in core.php debug to 1 when problem fixed. 
Maybe it is not issue, but in previews cakephp version upgrades i did not had such situations.

**Comment by adduc** [comment]
We experienced this updating an app from Cake 2.5 to 2.8. Turns out we had a cron running using the Console from Cake 2.5 (causing cache files with paths pointing to the older Cake version). Switching the cron to the newer version and clearing cache fixed the issue.

**Comment by didagu** [comment]
i am trying to run this command "/var/www/tender.ng/public_html/app/Console/cakeshell bgproc processEmailQueue -cli /usr/bin -console /usr/local/src/cake_2_5/Cake/Console -app /var/www/tender.ng/public_html/app/'" on an ubuntu VPS but this is the [error ](https://drive.google.com/open?id=0BzTCqluhj5kqd3Z0NXV2TllGVGM)i get .
