### ISSUE TITLE
CakePHP3-RC2 Custom Cache Storage

### ISSUE THREAD

**Issue by ChristianYeah** [cakephp/cakephp#6073]
the document about create the custom storage may not work well.

the doc suggest to configure the Cache like
```
Cache::config('custom', [
    'className' => 'CachePack.MyCustomCache',
    // ...
]);
```

Im not sure about the meaning of CachePack , but it doesnt work for me. it shows that my custom cache storage engine doesnt exist
I used the namespace instead , and it works
could you plz check this?

**Comment by lorenzo** [comment]
`CachePack` is a fictional plugin. The `dot` notation is used in that example to show how to load a cache engine from a plugin. Using a namespace is also a fine option :)
