### ISSUE TITLE
3.0 View cells render() does not respect plugin dot syntax

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#6076]
If I have a view cell `PageHeader` and I am rendering a template from a plugin a missing template exception will be thrown. When it lists all of the template locations it looked in the template I am trying to render is listed but the exception is still thrown.

```php
// These don't work
echo $this->cell('PageHeader')->render('user');
echo $this->cell('PageHeader')->render('Users.user'); // users.user.cpl

// This does work
$cell = $this->cell('PageHeader');
$cell->plugin = 'Users';
echo $cell->render('user');
```

**Comment by markstory** [comment]
Fixed with #6079
