### ISSUE TITLE
Error: Table 1 for model File was not found in datasource default.

### ISSUE THREAD

**Issue by BondITSolutions** [cakephp/cakephp#6078]
The following error is thrown when I try to render a PDF with the CakePdf plugin (https://github.com/FriendsOfCake/CakePdf) using the DomPdf engine:

    Error: Table 1 for model File was not found in datasource default.

This occurs at the following line:

    $CakePdf->write(APP . 'webroot' . DS . 'files' . DS . 'filename.pdf');

Which calls the following function in CakePdf.php:

    public function write($destination, $create = true, $html = null) {
        $output = $this->output($html);
        $File = new File($destination, $create);
        return $File->write($output) && $File->close();

    }

And fails on the return statement which (wrongfuly) calls `Model->getDataSource()`. Obviously `App::uses('File', 'Utility');` is used at the top of the CakePdf file. Why is it trying to load a (non-existing) model called File rather than using the File utility..? I'm not sure whether to report this issue here or at the plugin repo. Ultimately chose to report it here.

I'm using CakePHP 2.5.4.

Stacktrace: http://oi60.tinypic.com/2qbvbqc.jpg

**Comment by ceeram** [comment]
can you include the stack trace. This does not look like a bug in cakephp or cakepdf. Maybe you try to retreive the pdf file through a files controller, which in its turn tried to load a File model class. This is just a wild guess, so a stacktrace will be helpfull to determine what exactly is wrong.

**Comment by BondITSolutions** [comment]
@ceeram I've added the stacktrace to the OP, I hope it can help.

**Comment by markstory** [comment]
Do you have a File model in your app or any plugin?

**Comment by BondITSolutions** [comment]
Yes, there is a File model in the application! I was completely unaware of that, I'll start renaming it. I assume it will solve this problem.

**Comment by markstory** [comment]
Yes that will fix the issue.

**Comment by BondITSolutions** [comment]
Yep, fixed it!
