### ISSUE TITLE
Casting throws notices in Type class

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6083]
"Array to string conversion"

See https://travis-ci.org/dereuromark/cakephp-tools/jobs/54070435

In the case no custom type is used, trying to use scalar-only functions on non-scalar arrays isn't sound.
In this specific case the `_basicTypeCast` method functionality shouldn't be invoked, but either [this](https://github.com/cakephp/cakephp/compare/3.0...dereuromark:3.0-type) or better yet the content transformed to `null` etc instead.

**Comment by markstory** [comment]
I don't passing the array without changing it is reasonable. I would expect scalar type classes to convert the values. I'll put together something.

**Comment by markstory** [comment]
Closing as I think #6087 solves this.
