### ISSUE TITLE
3.0 - Cake don't want to validate a specific rule

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#6084]
Hello,

I'm having a weird problem with my validation rules.
Before to expose my problem, i just want to say that worked 2 months ago.
It **work on my website** : 
![gn7mzdm](https://cloud.githubusercontent.com/assets/8210023/6659070/ae97e80c-cb7c-11e4-8ef7-c2e7a9b1e31c.png)
But **not anymore** in testcases.

I have my table `Users` with this validation rules :
https://github.com/Xety/Xeta/blob/master/src/Model/Table/UsersTable.php#L137-L208

I have this testcase :
https://github.com/Xety/Xeta/blob/master/tests/TestCase/Model/Table/UsersTableTest.php#L191-L238

As you can see, the validation must return an array of errors. I got it, **but** not as expeted. The validation rules for the field **avatar_file** are not validated :
Debug of the `$users` variable **after** the `patchEntity()`:
![znkvdas](https://cloud.githubusercontent.com/assets/8210023/6658935/cafd3dde-cb78-11e4-9563-7e1c7a8d43d1.png)

The validator **must** return errors for the `mimeType` and `fileExtension` rules but it doesn't.

I'm on those errors since 3 days and to be honest, i really don't know what's wrong because that worked 2 months ago and i didn't changed something in that code.

And i have this problem for **all** validation rules releated to a file in my application.

I just see, if i change this rule : https://github.com/Xety/Xeta/blob/master/src/Model/Table/UsersTable.php#L151 to `notEmpty` it give me this result :
![rhqhhcb](https://cloud.githubusercontent.com/assets/8210023/6658998/79bdc428-cb7a-11e4-802c-3402d8032516.png)
So, it look like the file is empty, but it is not !!

**Comment by markstory** [comment]
The issue here likely related to `allowEmpty()` being aware of empty/missing files since #5800.

**Comment by Xety** [comment]
Yeah you're right, i commented your change in #5800 , and it work well again. :+1:
