### ISSUE TITLE
3.0 - Weird error in testcases with Controllers test

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#6092]
Hello,

I have a **very weird** problem.

For my application, i have written this testcase (Related to an `afterSave()` event) :
https://github.com/Xety/Xeta/blob/8b1d8f67c390c063eb1151b3318c7c9b647b3487/tests/TestCase/Model/Table/ForumPostsTableTest.php#L120-L150

It work well, as expected. Now i want to create testcases for my Controllers.

I created the `UsersControllerTest` with bake, but now when i re-run my testcases, the previous tests fail, the event isn't fired : https://github.com/Xety/Xeta/blob/b5fa26bcdcee044771aeb439e2a211edf4b0490f/src/Model/Table/ForumPostsTable.php#L70-L73

**IF** i renamme the file and the class name `UsersControllerTest` to `BlogControllerTest`, the test work well again !

WTF is this bug ??!! :open_mouth: 

The UsersControllerTest generated with bake :
```php
<?php
namespace App\Test\TestCase\Controller;

use App\Controller\UsersController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\UsersController Test Case
 */
class UsersControllerTest extends IntegrationTestCase
{

	/**
	 * Fixtures
	 *
	 * @var array
	 */
	public $fixtures = [
		'Users' => 'app.users'
	];

	/**
	 * Test beforeFilter method
	 *
	 * @return void
	 */
	public function testBeforeFilter()
	{
		$this->markTestIncomplete('Not implemented yet.');
	}

	/**
	 * Test index method
	 *
	 * @return void
	 */
	public function testIndex()
	{
		$this->markTestIncomplete('Not implemented yet.');
	}

	/**
	 * Test login method
	 *
	 * @return void
	 */
	public function testLogin()
	{
		$this->markTestIncomplete('Not implemented yet.');
	}

	/**
	 * Test logout method
	 *
	 * @return void
	 */
	public function testLogout()
	{
		$this->markTestIncomplete('Not implemented yet.');
	}
}

```

**Comment by markstory** [comment]
Have you thought to check that TableRegistry contains the correct instances?

**Comment by Xety** [comment]
Yes and all look right.

I also noticed, when i have this code the testcases fail:
```php
<?php
namespace App\Test\TestCase\Controller;

use App\Controller\UsersController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\UsersController Test Case
 */
class UsersControllerTest extends IntegrationTestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'Users' => 'app.users'
    ];

    /**
     * Test login method
     *
     * @return void
     */
    public function testLogin()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }
}
```

But when i remove the `testLogin()` function the testcases work again :
```php
<?php
namespace App\Test\TestCase\Controller;

use App\Controller\UsersController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\UsersController Test Case
 */
class UsersControllerTest extends IntegrationTestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'Users' => 'app.users'
    ];
}
```

That's really weird.

**Comment by markstory** [comment]
Perhaps state is not being reset on the incomplete test?

**Comment by Xety** [comment]
Ok, problem solved.

I had to attach the EventListener `Badges` `$this->eventManager()->attach(new Badges());` before to dispatch the event.
```php
public function afterSave(Event $event, Entity $entity, ArrayObject $options) {
	if ($entity->isNew()) {
		$this->eventManager()->attach(new Badges());
		$event = new Event('Model.ForumPosts.reply', $this, [
			'post' => $entity
		]);
		$this->eventManager()->dispatch($event);
	}

	return true;
}
```

But in the doc, in the exemple, they don't show that : http://book.cakephp.org/3.0/en/core-libraries/events.html#example-event-usage they dispatch directly the event.
Also i still don't understand why it worked/failed when i written testcases for the UsersController because it's unrelated i think. Anyways, all work well now. Thanks for your help Mark ! :smile:
