### ISSUE TITLE
3.0 Exceptions with code 400-505

### ISSUE THREAD

**Issue by Tietew** [cakephp/cakephp#6094]
ExceptionRenderer sets HTTP response code to exception code (returned from `Exception->getCode()`) if the code is in 400-505.
But some extensions, i.e. imagick, provide exceptions in this range.

```php
$img = new imagick;
try {
    $img->readImageBlob('PNG');
} catch(ImagickException $e) {
    echo $e->getCode();  # => 420
};
```

In this case, CakePHP will respond invalid HTTP status code 420.

Suggestion:
- If the exception is derived from `Cake\Core\Exception\Exception`, use exception code as status code.
- Otherwise use 500 always.

Pros:
- Valid status code will be used always

Cons:
- Backward incompatibility

**Comment by markstory** [comment]
We can't really break the error code conversion as there are very likely userland exceptions that rely on error codes without extending core exception classes.

**Comment by Tietew** [comment]
The word "error code" is confusing.
What does "error code conversion" mean?

**Comment by dereuromark** [comment]
He means that if you suddenly change the error code that the browser receives this might break existing applications. You would need to do this in a minor or even a major version change where this can be communicated.

A workaround until then would be to have your own custom error handler that converts them as you like them.

**Comment by dereuromark** [comment]
You could also rethrow then with the proper and expected code:
```php
catch (ImagickException $e) {
    throw new ProperException(...);
};
```

**Comment by markstory** [comment]
@dereuromark I think that's a reasonable desirable approach.
