### ISSUE TITLE
Incorrect dates when using local with Cakephp3 RC2

### ISSUE THREAD

**Issue by Bzounourz** [cakephp/cakephp#6095]
I explain my problem, I'm French and therefore works with local. 

So I use "Type::build('datetime')->useLocaleParser();" in my AppController to parse my dates. 
It's works well except that all my dates are set one hour ahead. 

For exemple: 18/03/2015 becomes 17/03/2015 23:00:00

My edit form is: echo $this->Form->input('created', ['type' => 'text']);
(i use Jquery timepicker with french locale)

Debug request->data = 'created' => '12/03/2015',

But save 11/03/2015 in database.

Yet I have set my bootstrap: date_default_timezone_set (Europe / Brussels'); 
ini_set ('intl.default_locale', 'fr_BE'); 

And changed the configuration of my database with:  'timezone' => '+01:00'

Someone an idea?  

Thank you in advance :)

**Comment by markstory** [comment]
Are you storing dates into a timestamp field or datetime field? If you are using MySQL these columns behave very differently.

**Comment by Bzounourz** [comment]
Lorenzo has solved the problem with me.
It was indeed a concern in the framework.

**Comment by lorenzo** [comment]
sorry I could not find time to submit a fix yesterday @Bzounourz, I will do today :)

**Comment by Bzounourz** [comment]
No problem, your solution works very well, I would wait just one more day to put my core to date.
Another big thank you for your help yesterday!

**Comment by markstory** [comment]
Closing as there is a pull request now.
