### ISSUE TITLE
2.6.2 saveAll() fails to validate associated model's data in plugin context

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#6096]
Example: FooPlugin
Association: FooKey HasMany FooValue, FooValue BelongsTo FooKey

Calling ```saveAll()``` deep=true, validate=first fails to validate associated model's data while primary and associated models are both in a plugin.

I did hunt this issue throughtout ```Model``` to ```ModelValidator``` and then back to ```Model```. 
In ModelValidator ```_parseRules()``` the rules from the assoc model are not added because of 
```if ($this->_validate === $this->_model->validate)``` ... ```return true```. Here both are empty array().
In my cause though, ```$this->_model->validate``` should have an array of validations.

This is not the case because ```_model``` is an instance of ```AppModel``` for associated models where as it is an instance of the primary model's class (say FooKey) for the primary model.

Tracing the issue back to Model.php adding ```debug(get_class($this));``` to ```public function validator()``` shows AppModel class for associated models so thatthis: ```$this->_validator = new ModelValidator($this);``` creates a ModelValidator with a wrong model class:
From ModelValidator:
```php
	public function __construct(Model $Model) {
		$this->_model = $Model;
	}
```

The issue is apparent already in ```saveAssociated()```. ```saveMany()``` is just a wrapper for ```saveAssociated()``` in my use case and thus in ```saveAssociated()``` when I do:
```php
debug($this->name);
debug(get_class($this));
```
It does list the primary model's name twice, e.g. FooKey but then for the associated model FooValue it lists FooValue and then AppModel.

**Comment by ionas** [comment]
Seems that I have missed the Plugin Prefix in classNames of Associations (missing in cake bake, at least in croogo). Closing for now.

**Comment by LuMAXW3B** [comment]
@ionas I run into the same 'issue' right now AND I have the 'className' => 'PluginPrefix.Model' set in both classes ($belongsTo and $hasMany); in my case:

Example: Kasse
Association: GoodsReceipt HasMany GoodsReceiptItem, GoodsReceiptItem BelongsTo GoodsReceipt

public $hasMany = array(
	'GoodsReceiptItem' => array(
		'className' => 'Kasse.GoodsReceiptItem',
		'foreignKey' => 'goods_receipt_id',
		'dependent' => true,
	),
);

public $belongsTo = array(
	'GoodsReceipt' => array(
		'className' => 'Kasse.GoodsReceipt',
		'foreignKey' => 'goods_receipt_id',
		'counterCache' => true,
		'conditions' => '',
		'fields' => '',
		'order' => '',
	),
);

Everything works as expected cool but then I was confused that my

if ($this->{$this->modelClass}->saveAll($this->request->data, array('validate' => 'first', 'deep' => true)))

didnt validate the GoodsReceiptItem rules... maby im stupid in some way or overlook sthn.

Ideas?

**Comment by jhli** [comment]
Try to save the model directly to make sure that validation works basically.

Use irc, groups, stackoverflow.
