### ISSUE TITLE
newEntity - update with primary key

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#6097]
```
$this->Articles->newEntity([
    'id' => 2,
    'title' => 'updated title',
    'text' => 'updated text'
]);
```
I would suspect that the entity contains the primary key and the updated title and text but it contains the record from the database with all fields.
This is done in ORM/Marshaller.php::one() since the fix #6086

**Comment by mylux** [comment]
In fact it changed, but I don't think this is an issue, once you should use patchEntity to merge request and database fields. And you know that this is an update, because the id field (that certainly is your primary key) is present in the data structure.

**Comment by markstory** [comment]
@mylux I still think newEntity() should work if you provide the primary key values. This scenario could prove more problematic if there are associations being added/updated as well.

**Comment by markstory** [comment]
Closing as #6099 is open now.
