### ISSUE TITLE
Implement Query::joinWith()

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6101]
`contain()` and `matching()` solve most of the cases where filtering by association data is required, but they usually force the developer to load the fields from the target association. In some circumstances the filtering is the only requirement and loading the association's fields may actually change the result in a undesirable way.

Implementing `innerJoinWith($associationName, $conditions)` and `leftJoinWith($associationName, $conditions)` would solve this problem by applying the same filtering logic as `contain()` but leaving the field loading aside.

**Comment by markstory** [comment]
Sounds like a great improvement.

**Comment by lorenzo** [comment]
Closing as there is a PR open
