### ISSUE TITLE
Implement `Query::notMatching()`

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6102]
Filtering rows when that don't match an association is a common requirement, but is not something most people is confortable with coding themselves in SQL.

Offering a `Query::notMatching($association, $queryBuilder)` would be a nice addition to the ORM. It can be implemented using 2 strategies:

* Doing a LEFT JOIN on the target association and adding a WHERE target.primary_key is NULL
* Using a WHERE NOT EXISTS subquery

In general the first approach is more performant, but it cannot be applied in all situations, specially when the same association is added to `contain()`

**Comment by markstory** [comment]
The subquery sounds like it will work better in various situations. I have uswd the left join + null approach before and it can have some limitations.
