### ISSUE TITLE
Make `Query::select()` accept a Table instance

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6103]
Selecting all the fields in a table's schema is usually cumbersome, but can be a common task after adding calculated fields to the `select()` clause.

This problem can be solved by making `Query::select()` accept a `ORM\Table` and/or a `Schema\Table` instance. When passing these objects, all fields in the schema should be copied to the select clause

**Comment by markstory** [comment]
Would this be only for ORM\Query or Database\Query as well? I could see orm\query accepting an orm\table or a schema\table.

**Comment by lorenzo** [comment]
`Datababe\Query` could accept the schema object and `ORM\Query` could enhance that by accepting the Table

**Comment by markstory** [comment]
Sounds great.
