### ISSUE TITLE
Implement late eager loading of associations

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6104]
Loading associations beforehand using `Table::find()` has proven to be quite easy and flexible, but currently there is no options for loading data from associations to an already existing result set. For example, something like this should be possible:

```php
$articles  = $this->Articles->find()->all();
$enrichedArticles = $this->Articles->eagerLoad($articles, ['Users', 'Tags']);
```

**Comment by markstory** [comment]
Would this method work with a single entity, collection, array or query object, or all of the above?

**Comment by lorenzo** [comment]
I would limit it for `Entity` and `Traversable`

**Comment by markstory** [comment]
Sounds good. That covers the things I would want this for.

**Comment by mylux** [comment]
Why not implementing this in the Resultset instead?

So you could do something like:

$articles  = $this->Articles->find()->all();
$articles->eagerLoad( ['Users','Tags'] );

**Comment by lorenzo** [comment]
@mylux It is very easy to lose the reference to the resultset. For example $results = $articles->find()->map($mapper) is not a result set anymore.

**Comment by markstory** [comment]
Closing as there is a pull request now.
