### ISSUE TITLE
patchEntity with null values not possible

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#6108]
Is there any chance to set a field to "null" using patchEntity? I overwrote patchEntity to allow this...

**Comment by markstory** [comment]
How does null get sent in POST data?

**Comment by mdlouhy** [comment]
I have a routine that generates a PDF.  In the database I have a field "pdf_generated_date" which needs to be set to null before starting the generation process.
I wanna do.
```
$order = $this->Orders->get($orderId, ['fields' => ['id']]);
$order = $this->Orders->patchEntity($order, [ 'pdf_generated_date' => null], ['validate' => false]);
```

before newEntity() method was changed I could even do
```
$order = $this->Orders->newEntity([ 'id' => $orderId, 'pdf_generated_date' => null], ['validate' => false]);
```

but now I have to do
```
$order = $this->Orders->get($orderId, ['fields' => ['id']]);
$order->pdf_generated_date = null;
```

Database operations do not always depend on data sent by forms.
Think of having routines (for example triggered by cronjobs) which just does some updates, inserts, deleted based on data NOT sent by forms.

**Comment by markstory** [comment]
You don't need patchEntity to set a single field though. You can just update the field. If you need to set multiple fields, Entity::set() can do that too.

**Comment by mdlouhy** [comment]
I understand. So basically patchEntity is designed to work only with form data?! I didn't know that. In the docs there is no mention of that. Thanks. I think this solves my problem.

**Comment by lorenzo** [comment]
@mdlouhy Would you add that to the docs?

**Comment by mdlouhy** [comment]
I am not so good in English - I don't think that this is what you really want :P

**Comment by markstory** [comment]
@mdlouhy The headings for those methods are under [Converting request data into entities](http://book.cakephp.org/3.0/en/orm/saving-data.html#converting-request-data-into-entities) what would make that more clear.

**Comment by dereuromark** [comment]
Wasn't there recently a change regarding null and patching?

**Comment by markstory** [comment]
Yes, but it was for a regression that was introduced. #9389

**Comment by mehov** [comment]
As stupid as this sounds, if someone googles this like I just did, make sure your database column isn't set to `NOT NULL`
