### ISSUE TITLE
Saving HasMany Associations and foreign_key validation

### ISSUE THREAD

**Issue by stefanozoffoli** [cakephp/cakephp#6109]
Hi,
i have two tables: `ProductsTable` and `PriceRulesTable`. There is an association `ProductsTable->hasMany(PriceRulesTable)`.

`PriceRulesTable` has this validation rule (made by bake):
```php
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create')
            ->add('product_id', 'valid', ['rule' => 'numeric'])
            ->requirePresence('product_id', 'create')
            ->notEmpty('product_id');

        return $validator;
    }
```

I tried to save a new product with his price rules as stated here:
http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-hasmany-associations

So i have for example this data:
```php
$data = [
    'title' => 'Product name',
    'price_rules' => [
        ['alias'=>'purchase', 'value' => 15],
        ['alias'=>'sale', 'value' => 20]
    ]
];
```
When i put this data to `ProductsTable->newEntity();` i get validation errors:
```php
$new_product = $productsTable->newEntity($data);

if ($new_product->errors()) {
    pr($new_product->errors());
    exit;
}
```
`$new_product->errors()` returns this:
```php
Array (
    [price_rules] => Array (
            [0] => Array (
                    [product_id] => Array (
                            [_required] => This field is required
                        )
                )
            [1] => Array (
                    [product_id] => Array (
                            [_required] => This field is required
                        )
                )
        )
)
```
But I can't have product_id value before saving the new product to the database.

By commenting `requirePresence('product_id', 'create')` and `notEmpty('product_id')` in `PriceRulesTable` the save process goes well, but I need these rules in other circumstances.
Do I need to create two validation function in PriceRulesTable?

Thank you!

**Comment by lorenzo** [comment]
Remove the validation rules for `product_id`. You don't send that data in the form, so the validation fails with a reason. You can add a `Rule` for `product_id` in the `buildRules()` method to make sure that before saving that information is present.

**Comment by stefanozoffoli** [comment]
Ok, thank you! ;)
