### ISSUE TITLE
Fix last slash in constant

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#6118]
Hello!

Please use the same logic for the last slash in constant.

In my case:

*APP* returns `/vagrant/app/src/`       
*ROOT* returns `/vagrant/app`

why the first ends with a slash and the second no?

**Comment by markstory** [comment]
I'm not sure what the original reason is, but they've been that way for a long time and changing them creates a bunch of busy work. Both these constants are defined in your application and can easily be changed there :smile:
