### ISSUE TITLE
JsonView::_serialize and NAN

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#6121]
I ran into an issue trying to serialize data that contained NAN (not a number) values.  I know this is *actually* an issue with `json_encode()`, and more specifically the JSON spec itself, but I thought I'd bring it up just in case.

Would there be any argument for handling this in `JsonView::_serialize()` ?

I know in Issue #5602, there was discussion of making PHP 5.5 a minimum requirement and if so it seems you would have access to some newer 5.5+ [json constants](http://php.net/manual/en/json.constants.php):  `JSON_ERROR_INF_OR_NAN` and `JSON_PARTIAL_OUTPUT_ON_ERROR`, specifically.

I'm honestly not sure if anything should be done about this or not since this is technically user error.

**Comment by markstory** [comment]
We could handle it once we have access to the new constants.

**Comment by ADmad** [comment]
Closing as related PR has been opened.
