### ISSUE TITLE
json view is not rendered if debug is false

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#6122]
CakePHP 3

I have an autocompleter input whih calls a controller method via json (jquery)

If debug is on it works perfectly, if debug is set to false it fails with 500 error.
Request headers are the same.

It seems if debug set to true cake renders `/src/Template/Exampes/json/example.ctp` but if it set to false cake tries to render `/src/Template/Exampes/example.ctp` - so not the json view. As this view is not exist I get the 500 error.

The response header gives an application/json type if debug is true and text/html if debug is false.

**Comment by Xety** [comment]
I had an error like that also.
Can you post the code from your controller please ?

**Comment by rrd108** [comment]
~~~~~
public function search(){
   $query = $this->Zips->find()
         ->select(['id', 'zip', 'name'])
         ->where(['zip LIKE "'.$this->request->query('term').'%"'])
         ->orWhere(['name LIKE "'.$this->request->query('term').'%"']);

   foreach($query as $row){
      $result[] = array('value' => $row->id,
                    'label' => $row->zip . ' ' . $row['name']
                    );
   }

   $this->set('result', $result);
}
~~~~~

**Comment by ceeram** [comment]
Are you including RequestHandler component in your (App)Controller and have  `Router::extensions(['json']);` in your routes.php?

**Comment by Xety** [comment]
Why you don't use the `_serialize` option ?

In `config\routes.php` (After all use statements) add `Router::extensions(['json']);`:
```php
<?php

use Cake\Core\Plugin;
use Cake\Routing\Router;

Router::extensions(['json']);

Router::scope('/', function ($routes) {
//...
```

```php
public function search() {
	$query = $this->Zips->find()
		->select(['id', 'zip', 'name'])
		->where(['zip LIKE "' . $this->request->query('term') . '%"'])
		->orWhere(['name LIKE "' . $this->request->query('term') . '%"']);

	$json = [];

	foreach ($query as $row) {
		$json[] = [
			'value' => $row->id,
			'label' => $row->zip . ' ' . $row['name']
		];
	}

	$this->set(compact('json'));

	$this->set('_serialize', 'json');
}
```

With that you don't need to create the view search.ctp.

**Comment by ceeram** [comment]
@rrd108 add extensions as i described to your routes.php and it will work:
https://github.com/rrd108/sanga/blob/master/config/routes.php
I noticed you do have RH component enabled.
Alternatively you could indeed skip view files using _serialize, which is often easier, although not required

**Comment by rrd108** [comment]
@ceeram @Xety Thanks. Now it works. Still this behaviour is strange.
