### ISSUE TITLE
bake not found

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#6123]
Cake 3

Part of my composer.json

````javascript
    "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "3.0.*-dev",
        "cakephp/migrations": "dev-master",
        "cakephp/plugin-installer": "*",
        "cakephp/bake": "dev-master",
        "mobiledetect/mobiledetectlib": "2.*",
        "phpunit/phpunit": "*",
        "rrd/rbruteforce": "*",
        "google/apiclient": "1.0.*@beta"
    },

````
But calling `bin/cake bake` gives me the following error:
Exception: Shell class for "Bake" could not be found. in [/home/rrd/public_html/sanga/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 278]

**Comment by markstory** [comment]
You'll need to load the plugin as well. The [app skeleton](https://github.com/cakephp/app/blob/master/config/bootstrap_cli.php) has an example of how to do this.
