### ISSUE TITLE
2.6.3 won't load plugins (and vendors?) in shared Cake installations

### ISSUE THREAD

**Issue by davehensley** [cakephp/cakephp#6124]
In 2.6.3, the following change was introduced as part of commit aec0241a4cbad40ff80f4de46aeff679cddac7b5:

    diff cakephp-2.6.2/lib/Cake/Core/App.php cakephp-2.6.3/lib/Cake/Core/App.php
    877c877
    < 					dirname(dirname(CAKE)) . DS . 'vendors' . DS,
    ---
    > 					ROOT . DS . 'vendors' . DS,
    881c881
    < 					dirname(dirname(CAKE)) . DS . 'plugins' . DS
    ---
    > 					ROOT . DS . 'plugins' . DS

I have several sites that all share the same version of Cake, so for each of these I uncommented the CAKE_CORE_INCLUDE_PATH line in app/webroot/index.php and pointed it to my Cake directory:

define('CAKE_CORE_INCLUDE_PATH', DS . 'opt' . DS . 'cakephp-2.6.3');

My plugins live in /opt/cakephp-2.6.3/plugins/. This works great on 2.6.2 and earlier, but 2.6.3 won't find my plugins unless I revert back to the 2.6.2 version of lib/Cake/Core/App.php (I get this error: "The application is trying to load a file from the Foo plugin / Make sure your plugin Foo is in the app/Plugin directory and was loaded").

Presumably, this would affect vendors as well, although for this project I'm not using any.

**Comment by dereuromark** [comment]
Closing as PR got merged.
