### ISSUE TITLE
Cake 3.x: Spread $conn to associated Tables during Eager Load

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#6126]
Well I have several databases with the same tables. they are being used in that way by design, to separate continents information.
So I need to change dynamically the connection depending on the user server requested.

Initially I am using something like this:
        ``$conn = ConnectionManager::get($server);``
        ``$this->connection($conn);``
but, of course, this change does not spread to the associated Tables.

Is it possible to add this functionality?

**Comment by markstory** [comment]
I'm not sure this is a good idea. As it is hard to know which associations should be updated. An alternative way to approach this is to use connection aliases and alias the active user's shard to a connection name that doesn't exist. I [recently did a blog post](http://mark-story.com/posts/view/using-cakephp-and-a-horizontally-sharded-database) on how to do this.

**Comment by Tzaoh** [comment]
Well I have just got it while I was waiting your response. But I am not sure how "good/bad" are these changes. I will try to explain them.

I identify the Table Object adding a non-existing datasource to the static defaultConnectionName() function.

File: ``<Name>Table.php``

    public static function defaultConnectionName()
    {
        return 'parent';
    }

Because this datasource does not exist I need to patch it in order CakePHP does not complain about it.
File: ``ConnectionManager.php`` line 183

    public static function get($name, $useAliases = true)
    {
        if ($name == 'parent') {
            $name = 'default';
        }
        .
        .
        .
    }

And finally we need to tell CakePHP "ey if you see a defaultConnection named 'parent' in a class before instantiate it, modify the arguments (which contains the connection stuff) we pass to its __constructor class with the connection stuff of the parent. This was tough for me.
File: ``TableRegistry.php`` line 196

    public static function get($alias, array $options = [])
    {
    .
    .
        if ($options['className']::defaultConnectionName() == 'parent') {
            $parentConn = end(static::$_instances)->connection();
            $options['connection'] = $parentConn;
        }
    .
    .

**Comment by markstory** [comment]
I don't think patching ConnectionManager & TableRegistry is a good idea. It requires hardcoding a name or hardcoding sharding concepts into CakePHP, when many applications are not sharded. 

Using an undefined connection and then aliasing an existing connection to the active shard name feels less intrusive.

**Comment by Tzaoh** [comment]
I agree with you. My app will need Shell cronjobs with this behavior.
Is there any method which allows me to make this behavior from CLI shells too?

**Comment by markstory** [comment]
In shell commands you could use cli flags to set the active shard.

**Comment by lorenzo** [comment]
Closing as I think the framework already offers a solution for this kind of cases. As a side note, you could also use `TableRegistry::config()` to pre-configure table instances before they are created.
