### ISSUE TITLE
Hash::nest() handles unrecognized parent_ids strangely

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#6127]
I recently got some unexpected output from `find('threaded')` in CakePHP 2.6.3.

The setup:
-----
 - I have a tree of tags
 - Tags have the boolean field `listed`
 - There's a parent tag called "delete" where tags are moved before being deleted
 - "delete" is **not** listed, but some of its children **are**. (The intended effect is that the view doesn't mention the "delete" category or anything underneath it.)
 - I moved some new tags underneath "delete", and now the alphabetically-lowest tag under "delete" is "allergy-free". The alphabetically-lowest root-level tag (sibling of "delete") is "art".

The innocuous call to find():
-----
    $this->find('threaded', array(
		'conditions' => array(
			'Tag.listed' => 1
		),
		'recursive' => -1,
		'fields' => array('Tag.name', 'Tag.id', 'Tag.parent_id', 'Tag.selectable'),
		'order' => 'Tag.name ASC'
	));

The weird:
-----
I found that this was only returning the children of "delete" and nothing else, where it had previously returned the whole tree, except for any unlisted tags or any of their children. All of the sibling tags of "delete" were left off. Even more strangely, this was **fixed by removing the `order` option**.

The reason:
----
I dug around and figured out the cause, and I'm not sure if this counts as a bug or the anticipated result of a weird edge case.

 - The SQL query was being formed correctly and returning all of the anticipated tags.
 - It was `Hash::nest()`, called at the end of `Model::_findTheaded()` that removes everything but the child tags of "delete"
 - When `order` is **not** specified, `$root = self::get($return[0], $parentKeys);` in `Hash::nest()` correctly sets `$root` to `null` because the arbitrarily-first tag added to `$return` has a `parent_id` of `null`.
 - When `order` **is** specified, that same line sets `$root` to the ID of "delete" because the first tag added to `$return` happened to be an alphabetically-low child of "delete". It was added first because it matches the condition of `(!$parentId || !in_array($parentId, $ids))` because its parent was filtered out by the `'Tag.listed' => 1` condition. Because "allergy-free" comes before "art", the `parent_id` of "art" (null) is ignored in favor of the `parent_id` of "allergy-free".
 - Consequently, with `$root` being the ID of "delete", every root-level tag in `$return` that is not a child of delete matches the condition `($id !== $root && $parentId != $root)` and is a victim of `unset($return[$i]);` at the end of the method.

So is this 
-----
 - **a bug** because `Hash::nest()` should instead be discarding array members with unrecognized parents (or placing them in the root), or
 - **expected behavior** because a malformed array is being fed to `Hash::nest()`?

**Comment by markstory** [comment]
I think its somewhat expected behavior as malformed data is going into Hash::nest(). If you need to sort and nest the data, you might want to use TreeBehavior instead, or sort on a column(s) that will not cause incorrect parenting.

**Comment by PhantomWatson** [comment]
I can remove sorting from the database query to sidestep this error (because some tag with a valid parent then arbitrarily comes before any tags with invalid parents), but it doesn't really feel like a fix.

`TreeBehavior::children()` with `$id = null` seems like a winner, but that method doesn't take any conditions. `TreeBehavior::generateTreeList()` does, but then I can't get any additional fields other than ID and name.

I can think of a *bunch* of workarounds to accomplish what I'm going for, but I want to make sure that there isn't a cake-ier way to go about it, and that `Hash::nest()` shouldn't be modified to prevent the "if an invalidly-parented item comes first, that parent becomes the new root" situation.

**Comment by markstory** [comment]
If you can come up with a change for Hash::nest() that doesn't break any of the existing tests, it could likely be merged in.

**Comment by PhantomWatson** [comment]
I'll give it a shot!

**Comment by PhantomWatson** [comment]
Currently looking into the failed tests.

**Comment by PhantomWatson** [comment]
Turns out the last test in `ModelReadTest::testFindAllThreaded()` expects the specific behavior that was causing my issue. In case the modified behavior is considered more desirable, I've thrown an updated test case into the pull request.

**Comment by lorenzo** [comment]
Closing as the related pull requests were closed too.
