### ISSUE TITLE
Cake 3.x: Memory Leak in Email Sending

### ISSUE THREAD

**Issue by Mirelath** [cakephp/cakephp#6128]
In Cake3, When using SMTP in a simple email loop, there appears to be a memory leak, at least when using attachments (or large message bodies)

Each email which is sent increases the memory foot-print, even though they should be individual emails and there shouldn't be anything building anywhere. Eventually, after around 100 emails, the PHP memory limit is reached and is shut down.

Keeping the code as simple as possible, I am able to reproduce this issue with this block of code:
```
 $attachments = ['/tmp/attachment.png'];
 foreach($recipients as $recipient) {                             
                                $email = new Email('smtp');
                                $email->from($from)
                                        ->sender($sender)
                                        ->to($recipient)
                                        ->subject($subject)
                                        ->emailFormat('html')
                                        ->attachments($attachments)
                                        ->replyTo($sender)
                                        ->send($body);
                        }
```

The memory error is in the following:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1107147 bytes) in /home/www/app/vendor/cakephp/cakephp/src/Network/Socket.php on line 280

Which is the line (in the write() function)
```
$rv = fwrite($this->connection, substr($data, $written));
```

I have narrowed down the problem as best as I am able to - for example, it is definitely in the sending part which is causing the issue (removing the ->send() call works fine). It's not an issue with the $data being passed to the write function, as that is consistent with each iteration, so there's got to be something else somewhere building up.

Watching the process with a process monitor shows that with each email sent, the memory increases and is never released (including the full size of the attachment, so with larger attachments, the issue happens faster). With no attachment, the issue doesn't arise (but that could just be because the emails are then much smaller).

By setting the memory limit low and putting a large message body, it is possible to cause the same issue using only a large message body, so it's not an issue with the attachments.

**Comment by markstory** [comment]
If you set a small memory limit are you able you trigger the memory error without attachments?

**Comment by Mirelath** [comment]
Confirmed that it occurs without using attachments

**Comment by ndm2** [comment]
Oh I remember this one, I was about to report that some time ago but forgot about it. Somehow the memory used for the transport instance is not being released, despite the object being destructed (at least the destructor is being invoked).

AFAIR this is unrelated to the socket, as the memory wasn't released even when no socket is being constructed, and thus no data being sent at all. If I remember correctly nulling `SmtpTransport::$_cakeEmail` (especially this one) and `SmtpTransport::$_content` on disconnect, or `Email::$_transport` on destruction fixed it.

On a side note, you can also reuse transports, wich might be a good idea for mass mailings, that way you can keep the connection alive to avoid running into possible rate-limits.


```php
	'EmailTransport' => [
		'smtp' => [
			'className' => 'Smtp',
			// ...
			'keepAlive' => true
		],
	],
```

---

```php
$config = Email::configTransport('smtp');
$transport = new SmtpTransport($config);

foreach($recipients as $recipient) {                             
	$email = new Email();
	$email
		->transport($transport)
		->from($from)
		->sender($sender)
		->to($recipient)
		->subject($subject)
		->emailFormat('html')
		->attachments($attachments)
		->replyTo($sender)
		->send($body);
}

$transport->disconnect();
```

**Comment by Mirelath** [comment]
Thank you @ndm2, that seems to be exactly what is happening.

Switching to using a constant SmtpTransport has provided a helpful workaround, many thanks!

**Comment by lorenzo** [comment]
@Mirelath A change intended to fix this issue was applied, please report if that helped you.
