### ISSUE TITLE
Allowing multiple finders in paginate component

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#6130]
Hello,
at the moment if i want to use a custom find in paginate I do:

```
        $this->paginate = [
            'finder' => [
                'tagged' => $customFinderOptions
            ]
        ];
```
as reported in the DOC. It should be good to allow multiple finders, like:

```
        $this->paginate = [
            'limit' => 10,
            'finder' => [
                'one'    => [], // Options custom find
                'two'    => ['custom_param' => [2]],
                'three'  => [],
            ]
        ];
```
To do the same thing now we must do:

```
$query = $this->MyTable->find('one')->find('two')->find('three');
$this->paginate($query);
```

I think the first solution is better.

**Comment by dereuromark** [comment]
I like that. :+1: 
Simply foreach() over it as we do in other places should do the trick.

**Comment by markstory** [comment]
That seems like a reasonable syntactic short cut.

**Comment by dereuromark** [comment]
It looks like a non trivial change, though, as the $options of the paginator itself are possible used in the finder now as well:

        list($finder, $options) = $this->_extractFinder($options);

        if (empty($query)) {
            $query = $object->find($finder, $options);
        } else {
            $query->applyOptions($options);
        }

**Comment by dereuromark** [comment]
@tigrang You found a feasible solution?

**Comment by lorenzo** [comment]
This feature was rejected in the past, I'll try to find the conversation.

**Comment by ADmad** [comment]
@lorenzo You are probably referring to #4949.

If implementing this feature requires lot of array juggling then I too am not in favor of implementing it.

**Comment by markstory** [comment]
Closing this issue for the same reasons :smile:
