### ISSUE TITLE
removing dateWidget for date input

### ISSUE THREAD

**Issue by cyberbobjr** [cakephp/cakephp#6131]
Hi,
how can i disable dateWidget for date input ?

I want to have a simple input like this :
<input type="datetime">
but if put this in my view :
<?= $this->Form->input('test',['type'=>'datetime'])?> i have all select input for year, month and day.

Many thanks for your help.
Best regards.
BM

**Comment by markstory** [comment]
Yes. You can [replace the widget](http://book.cakephp.org/3.0/en/views/helpers/form.html#adding-custom-widgets) with a BasicWidget.
