### ISSUE TITLE
3.0: Routing and mixing Route classes.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6136]
With prefix and plugin the Routing does not consistently work with different Route classes right now.

If I set the app's routes config to `Router::defaultRouteClass('InflectedRoute');`
and have a plugin config that looks like this:
```
Router::prefix('admin', function ($routes) {
	$routes->plugin('AuthSandbox', function ($routes) {
		$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
		$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
	});
});
Router::plugin('AuthSandbox', function ($routes) {
			$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
			$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
});
```
Then the resulting URL is still containing the InflectedRoute part in the plugin (not the controller/action).

If we can set a different route class for plugins it should then completely overwrite, not just partially IMO.

See https://github.com/dereuromark/cakephp-sandbox/blob/3.0/src/Plugin/AuthSandbox/config/routes.php and the result `/auth_sandbox/auth-sandbox`

**Comment by markstory** [comment]
Which route is generated wrong in the example above?

**Comment by dereuromark** [comment]
`/auth_sandbox/auth-sandbox` vs expected `/auth-sandbox/auth-sandbox`

**Comment by ADmad** [comment]
The plugin name is not inflected using the Route class. Quoting the docblock:

```
The plugin name will be inflected to the underscore version to create
the routing path. If you want a custom path name, use the `path` option.
```

**Comment by markstory** [comment]
Closing as the plugin name is not inflected via the route class as per @ADmad's note.
