### ISSUE TITLE
TimeHelper format method expects date formats in the ICU format

### ISSUE THREAD

**Issue by rawroland** [cakephp/cakephp#6137]
The documentation for the [format method] (http://api.cakephp.org/3.0/class-Cake.View.Helper.TimeHelper.html#_format) does not mention the expected format, which is the [ICU format](http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details). This may lead to confusion.

**Comment by lorenzo** [comment]
Actually the format for `format()` is the default PHP one. The format from ICU is only valid for the methods that output locale-aware strings. I will try to make this more clear in the docs.
