### ISSUE TITLE
ask about this error plz help me?

### ISSUE THREAD

**Issue by blackoutro** [cakephp/cakephp#6144]
what i can  do this error and can help me to fix it?
[IMG]http://i59.tinypic.com/1zganmp.jpg[/IMG]

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by ADmad** [comment]
The solution to your problem is [here](https://github.com/cakephp/cakephp/blob/2.6/app/Config/core.php#L267)
