### ISSUE TITLE
Cake 3.x - Translation Functions don't parse special markers preceded by '

### ISSUE THREAD

**Issue by st3ph** [cakephp/cakephp#6145]
When using translation function, if you precede special markers with ' (single quote) character the marker isn't parsed.

Ex:
`<?= __("I'm going to l'{0}", 'hopital');?>` will return `I'm going to l{0}`
`<?= __("I'm going to l' {0}", 'hopital');?>` will return `I'm going to l' hopital`

**Comment by lorenzo** [comment]
The single quote character is actually the escape character. So your need to double escape it in order to get a single quote: http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping

**Comment by st3ph** [comment]
good to know, thank you and sorry for the wrong issue

**Comment by lorenzo** [comment]
No problem :)

**Comment by AD7six** [comment]
This is going to be the new #2589, we should probably try to handle that.
