### ISSUE TITLE
Exception when applying a baked migration snapshot

### ISSUE THREAD

**Issue by mamchenkov** [cakephp/cakephp#6147]
Steps to reproduce
-------------------------

```
# Create a new CakePHP 3 project
composer create-project --prefer-dist cakephp/app app
cd app
mysql -u root -e 'create database cakephp_test'
# Update db details
vim config/app.php
# Create table with id column set to binary(36) for UUID use
mysql -u root cakephp_test -e 'create table foo( id binary(36) not null unique, created datetime, modified datetime, primary key (id))'
# Bake snapshot
./bin/cake bake migration_snapshot initial
# Drop table
mysql -u root cakephp_test -e 'drop table foo'
# Apply snapshot
./bin/cake migrations migrate
```

Expected result
----------------------

Any baked migration should be usable.  In this case, a table should be correctly created and no exception should be triggered.

Actual result
-----------------

An exception is triggered, no table created:

```
$ ./bin/cake migrations migrate
Welcome to CakePHP v3.0.0 Console
---------------------------------------------------------------
App : src
Path: .../app/src/
---------------------------------------------------------------
using migration path .../app/config/Migrations
using environment default
using adapter mysql
using database cakephp_test

 == 20150323101149 Initial: migrating
                                                                                                                                
  [PDOException]                                                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'id' used in key specification without a key length 

migrate [-t|--target="..."] [-p|--plugin="..."] [-c|--connection="..."] [-s|--source="..."]
```

Additional Notes
---------------------
* If I use ```char(36)``` as column type, everything works as expected.
* The idea to use ```binary``` instead of ```char``` came up after [this StackOverflow thread](http://stackoverflow.com/questions/12646498/using-uuid-in-cakephp-what-datatype-is-recommended)

**Comment by AD7six** [comment]
What is the type of the id field _after_ the attempted migration? The error message says it's a blob, not binary.

**Comment by mamchenkov** [comment]
@AD7six the migration file has ```binary```.  Here it is:

```
<?php
use Phinx\Migration\AbstractMigration;

class Initial extends AbstractMigration
{
    public function up()
    {
        $table = $this->table('foo', ['id' => false, 'primary_key' => ['id']]);
        $table
            ->addColumn('id', 'binary', [
                'default' => null,
                'limit' => 36,
                'null' => false,
            ])
            ->addColumn('created', 'datetime', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->create();
    }

    public function down()
    {
        $this->dropTable('foo');
    }
}
```

**Comment by mamchenkov** [comment]
There is no table at all after the migration.  I'm assuming that's because migration fails and Phinx rolls back the creation of the table.

**Comment by AD7six** [comment]
If I use that migration but a different field name (so it succeeds) I get this table:

```
CREATE TABLE `foo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bin` tinyblob NOT NULL, -- <- The primary key in the above migration
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

So it's not understood by phinx.

**Comment by dakota** [comment]
Phinx currently only understands `char(36)` for uuid columns (If you set the column type to `uuid`). This sounds like a Phinx bug to me.

**Comment by mamchenkov** [comment]
Technically, yes, it's probably Phinx.  However, user-wise it's still CakePHP. :smiling_imp: .

**Comment by dereuromark** [comment]
If that doesn't work, sure sounds like a phinx issue then.

By the way:
Binary should definitely be the (documented) default over char(36) (it currently is still not, uuid will create char36.. http://book.cakephp.org/3.0/en/migrations.html#creating-custom-primary-keys ).
We should really change this and make this more clear IMO.

**Comment by AD7six** [comment]
@mamchenkov sure - but for phinx/rob to fix it, it needs to know about the problem.

@dereuromark dunno about that, since we know for sure it won't work.

Related https://github.com/robmorgan/phinx/issues/85

**Comment by dereuromark** [comment]
Afterwards - as soon as we know it works (again) - I would really like to point out the more sane default value (regarding performance).

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#62
