### ISSUE TITLE
Cake 2.2.3 Router::url() return not complete http protocol string

### ISSUE THREAD

**Issue by okaprinarjaya** [cakephp/cakephp#6148]
Hello ,

When i call Router::url('/') or $this->Html->url('/') both method returning "http:/" NOT returning "http://" 
less "/". I'm using sub domain.

Example:
echo Router::url('/')
output: http:/mysub.myhost.com

**Comment by dereuromark** [comment]
I think you are misunderstanding the return value of this method.
Without second argument (set to true) it will always return an absolute URL without protocol, in your case:

    // Output of Router::url('/')
    /

    // Output of Router::url('/', true)
    http::/mysub.myhost.com/

Maybe you're setup is wrong then as it should only be this single char here.

**Comment by markstory** [comment]
You may have an incorrectly defined base url. Also you may want to try upgrading to a more recent CakePHP and see if that resolves your issue.

**Comment by okaprinarjaya** [comment]
Hi all.. thank you @dereuromark @markstory 
thank you for your responses..  :)

Finally.... i've found the cause after looonggg...looonggg.. tracing and testing :(
It turns out that someone in the team has override $this->params->base into static value such as http://mysub.myhost.com inside AppController::beforeFilter().
$this->params->base = 'http://mysub.myhost.com';

So.. i change $this->params->base value into empty string '' value. 
$this->params->base = '';
and... the problem solved!

i think someone in the team not know how to get base address of the app using cakephp. 
Yes, you're right @dereuromark , passing true as second parameter in method Router::url() will returning full base address / hostname --> http://mysub.myhost.com --> Router::url('/', true);

**Comment by okaprinarjaya** [comment]
i'm so sorry i've been post my problem here.. because i think the problem is core related.
