### ISSUE TITLE
SQLSTATE[HY000]: General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#6149]
after the error already related about my db few days ago, I know have the following one.

I tried to imported an older DB backup, same. It seems that the problem doesn't come from the content but the DB (file?) itsell.

I begin to be very worried about all these DB problems and I really wonder why I have it as I already use sqL DB on my OVH hosting with different application and I never had such problems!
Are you sure that CakPHP cannot be responsible about it ?? (just a question...)

<h2>An Internal Error Has Occurred</h2>
<p class="error">
<strong>Error: </strong>
SQLSTATE[HY000]: General error: 11 database disk image is malformed</p>

<br />
<b>Fatal error</b>:  Call to a member function getTrace() on a non-object in <b>/home/modulwoo/www/2ndGuideTest/vendor/cakephp/cakephp/src/Template/Element/exception_stack_trace.ctp</b> on line <b>21</b><br />
<h2>An Internal Error Has Occurred</h2>
<p class="error">
<strong>Error: </strong>
Call to a member function getTrace() on a non-object</p>

<br />
<b>Fatal error</b>:  Call to a member function getTrace() on a non-object in <b>/home/modulwoo/www/2ndGuideTest/vendor/cakephp/cakephp/src/Template/Element/exception_stack_trace.ctp</b> on line <b>21</b><br />

**Comment by lorenzo** [comment]
Nope, as you can read in the error the issue comes directly from mysql. Maybe you exceeded your disk quota?

**Comment by lorenzo** [comment]
Actually the error may come from debugkit and not your mysql. Check your tmp folder and delete the debugkit sqlite database and try again.

**Comment by caBBAlainB** [comment]
Thanks Lorenzo
The problem was just solved by a cakePHP update. 
I breath more easily!

**Comment by lomholdt** [comment]
Had the same issue. It was complaining about SqLite, and i'm all like "I'm not even using SqLite!'. Deleting the debugkit sqlite file in the tmp directory fixed this! :) Thanks!
