### ISSUE TITLE
3.0 utf-8 problem

### ISSUE THREAD

**Issue by krystianprzybyla** [cakephp/cakephp#6152]
There seems to be a strange problem with utf8 special chars.
<pre>
class PagesController extends AppController
{
    public function display1()
    {
        $this->set('test', 'ąąą');
    }

    public function display2()
    {
        2/0; //This is just to show cake-error box
        $this->set('test', 'ąąą');
    }
}
</pre>

<pre>
// View: display1.ctp and display2.ctp
&lt;? echo $test ?>
</pre>

And result is:

display1: ÄÄÄ - which is wrong.
display2: ąąą - this is as expected.

This leads to serious problems while displaying texts with special chars from database.

**Comment by antograssiot** [comment]
@krystianprzybyla  Is this a problem with 2.x or 3.x, because I wasn't abble to reproduce it with a fresh 3.0 install

**Comment by ADmad** [comment]
Neither 2.x or 3.x has problem with utf8. Make sure you have set `encoding` to `utf8` in your database connection config.

**Comment by lorenzo** [comment]
The issue could be a space before an opening `<php` tag in your code

**Comment by dereuromark** [comment]
He probably just forgot to save the file properly as UTF8 (without bom). Instead it was most likely saved as ANSI.

**Comment by krystianprzybyla** [comment]
Thanks for your suggestions. This is not problem of file save encoding, additional space or connection encoding settings. I set utf8 wherever required and spent some hours on research before I posted the issue to ensure I didn't "probably just forgot"...

The example I gave is not the best one. The point is that I cannot get the test-string from database and display it properly.

In example I modified fresh installation PagesController.php and home.ctp with following code and I got the error I described.

<pre>
public function display()
    {
        $path = func_get_args();

        $count = count($path);
        if (!$count) {
            return $this->redirect('/');
        }
        $page = $subpage = null;

        if (!empty($path[0])) {
            $page = $path[0];
        }
        if (!empty($path[1])) {
            $subpage = $path[1];
        }
        
        // Here the modification comes
        $page1 = $this->Pages->get(9);  // this is page with content with special chars like: łąś etc.

        //echo $page1->content;  
        // ^^^^^  Please note - if I only uncomment above line everything is displayed well
        // I mean both: echo from the controller and echo from the view.

        $this->set('test1', $page1->content);

        // end of modification

        $this->set(compact('page', 'subpage'));

        try {
            $this->render(implode('/', $path));
        } catch (MissingTemplateException $e) {
            if (Configure::read('debug')) {
                throw $e;
            }
            throw new NotFoundException();
        }
    }
</pre>

Any ideas?

**Comment by ceeram** [comment]
Did you also check if you have utf8 encoding in your database connection as @ADmad suggested?
https://github.com/cakephp/app/blob/master/config/app.default.php#L225

**Comment by krystianprzybyla** [comment]
Yes, I didn't change it and it is utf8 by default.

Here is part of my app.php

<pre>
            'username' => '***',
            'password' => '***',
            'database' => '***',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
</pre>

**Comment by krystianprzybyla** [comment]
Anyway, if there is a simple way to make it readable by using controller-echo-trick then what's wrong?

**Comment by krystianprzybyla** [comment]
Conclusion: I thing it is some kind of <b>server configuration issue</b>. The same code and database is not working at hosting provider platform but does work at my windows iis/php installation. If anybody has any suggestions I'm open to it.

**Comment by jhli** [comment]
Coalition? Try setting db and table and fields to utf8 bin.

**Comment by jhli** [comment]
... Use vagrant/vbix linux for local dev boxes

**Comment by krystianprzybyla** [comment]
Coalition is utf8 bin for fields, tables and db. And beside of that chars are coming from database in ISO-8859-2.

**Comment by lorenzo** [comment]
Maybe the data was saved in the wrong encoding the first time.. Have you tried displaying data saved using cakephp?

**Comment by krystianprzybyla** [comment]
Data is entered in phpMyAdmin using utf8 encoding and also has been displayed by cakephp 1 with utf8 with no problems.

**Comment by lorenzo** [comment]
Have you also tried not doing "echo" in your controller? You should be doing echo in your views, not the controllers.

**Comment by dereuromark** [comment]
I think this discussion is pointless. He should be dicussion this in a help forum (google or SO) and not in a bugtracker.
