### ISSUE TITLE
New website isn't rendering well on smart phones

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#6156]
Hello,

The new website http://cakephp.org/ is not rendering well on smart phones.
Kindly check the below image
![screenshot_2015-03-24-08-47-55](https://cloud.githubusercontent.com/assets/3768012/6797840/7c642bae-d20f-11e4-8829-2e4432f38e76.jpg)

**Comment by ionas** [comment]
Same thing happend on my iphone 5s (not sure after zooming back and forth or not)

**Comment by ionas** [comment]
iPhone 5S.
![img_0616](https://cloud.githubusercontent.com/assets/106845/6799148/aaba6a14-d213-11e4-9453-a2dfa483799e.PNG)
![img_0617](https://cloud.githubusercontent.com/assets/106845/6799149/aac3be34-d213-11e4-81b0-cd32e8f0303b.PNG)
![img_0618](https://cloud.githubusercontent.com/assets/106845/6799150/aac94aca-d213-11e4-9a75-56a1abb136d2.PNG)

**Comment by markstory** [comment]
@ionas Yea, the public website is in a private repo for now. But I can let the people working on it know about this.

**Comment by markstory** [comment]
The site was updated tonight, and looks much better on my Nexus7, and in a resized firefox/chrome browser.
