### ISSUE TITLE
3.0 - Markers not replaced in translation messages

### ISSUE THREAD

**Issue by PGBI** [cakephp/cakephp#6163]
Hi,

I just noticed the following bug:
`__("Click <a href='{0}'>here</a>", ['http://url.tld'])` returns `Click <a href={0}>here</a>` instead of `Click <a href='http://url.tld'>here</a>`

As a workaround, `__("Click <a href=\"{0}\">here</a>", ['http://url.tld'])` works as expected.

**Comment by markstory** [comment]
See #6145

**Comment by PGBI** [comment]
Arf, sorry. I had checked the opened issues, but not the already closed ones.

I suspect I won't be the last to open this issue. On #6145 the explanation given is that "The single quote character is actually the escape character". This is not something obvious. Shouldn't we mention it in the documentation?

**Comment by markstory** [comment]
Yeah it should probably be in the documentation now that you mention it.
