### ISSUE TITLE
Q: How to load a Facebook PHP SDK 4.1 into CakePHP 2.3.1

### ISSUE THREAD

**Issue by rvarbanov** [cakephp/cakephp#6169]
Hi,

I have been using the Facebook PHP SDK 3.x for some time on my site without any issues.

Now I am trying to upgrade the SDK to 4.1, but am having some issues loading the Facebook class into the AppController. 

The Facebook SDK is located in `app/Lib/Facebook/Facebook.php` and I am using `App::uses('Facebook', 'Lib/Facebook');` to load the class.

And this is how I am calling it:
```
    protected function createFacebookObject() {
        $facebook = new Facebook\Facebook([
            'app_id'  =>  FB_APP_ID,
            'app_secret' =>  FB_SECRET,
            //'default_graph_version' => 'v2.2',
            //'default_access_token' => '{access-token}', // optional
        ]);

        return $facebook;
    }
```

I have been following the instructions on this page: https://github.com/facebook/facebook-php-sdk-v4/blob/master/README.md

Also above the `App::uses(...);` I have `App::import('Lib/Facebook', 'autoload');`

No matter what I try I keep getting this error:
```
Error: Class 'Facebook\Facebook' not found  
File: /path/to/www.sitename.com/app/Controller/AppController.php    
Line: XXX
```

What I am doing wrong and how do I fix it

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
