### ISSUE TITLE
Paginator link je bad

### ISSUE THREAD

**Issue by MaxoMatos** [cakephp/cakephp#6170]
Hi,

I have Windows server with IIS and Paginator (in controler) get bad link.
Link is http://example.com/index.php/tabs?page=2

How to fix this URL to http://example.com/tabs?page=2

web.config je set like http://book.cakephp.org/3.0/en/installation.html#iis7-windows-hosts

**Comment by MaxoMatos** [comment]
this: $this->Html->link('Export files',['controller' => 'ExportFiles', 'action' => 'index'])
get link: /index.php/export_files
I want: /exportfiles
how to fix?

**Comment by lorenzo** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

* [The CakePHP Manual](http://book.cakephp.org)
* [The CakePHP online API](http://api.cakephp.org)
* [The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
