### ISSUE TITLE
3.0 - RulesChecker::_addError() treats string return value as success

### ISSUE THREAD

**Issue by cwbit** [cakephp/cakephp#6181]
RulesChecker callables should be able to return a string value to be used as the error `message` for `errorField` of the application rule.

Currently, returning an error message (string) from a RulesChecker callable is treated as a [success condition](https://github.com/cakephp/cakephp/blob/master/src/ORM/RulesChecker.php#L380) and does not mark the field as errored.

This behavior is inconsistent with validation rules which allow you to return a customized string from the callable which is treated as an error condition, with the string being used as the error message.

See: https://github.com/cakephp/cakephp/blob/master/src/ORM/RulesChecker.php#L377-L392

**Comment by markstory** [comment]
This doesn't sound too crazy to me. The additional consistency is nice.

**Comment by Laykou** [comment]
:+1:  Customizing messages based on the concrete mistake would be appreciated. General error sometimes cannot contain enough information to explain what is wrong.

**Comment by markstory** [comment]
Closing as a pull request is up now.
