### ISSUE TITLE
3.0 It should be possible to save new entities with a pre-defined primary key

### ISSUE THREAD

**Issue by robertscherer** [cakephp/cakephp#6185]
For a distributed system, in certain cases the clients of our CakePHP API generate UUIDs for records they want to create in our system.

`Table::newEntity()` handles this fine - if the `id` field is made accessible, the generated entity has the pre-defined UUID in its properties. 

However, when saving the entity, a new UUID is generated in `Table::_newId()` and the existing one is overwritten. 

This behavior is unexpected and in regard to the UUID definition makes no sense, what do you think?

Thanks,

**Comment by ionas** [comment]
I think it does make sense but I can see that you like to set your own UUIDs PKs that apply to the UUID version of your liking.

**Comment by lorenzo** [comment]
We could allow setting the primary key directly for non auto-increment keys.

**Comment by markstory** [comment]
Or just in general. If people using postgres/sqlserver set serial values directly they'll have to deal with the consequences.

**Comment by thaJeztah** [comment]
> Or just in general. If people using postgres/sqlserver set serial values directly they'll have to deal with the consequences.

+1. Sounds reasonable; Cake shouldn't be "holding hands" here

**Comment by markstory** [comment]
Fixed with #6188
