### ISSUE TITLE
Table::findList SELECT all the fields in the table(not only "keyField" and "valueField")

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#6186]
Hi,

Sorry for my bad english :(

I tried to get a list of establishments(name of my table) to use it on a **html select tag**.

Like on the v2.x i use the method **find('list')**. 
It works(the results is correct) but when i look at the sql query i notice that **all the fields are selected**(like i execute a **SELECT * FROM establishments**).

I open the [src/ORM/Table.php](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php) and i tried to fix the [findList method](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L954) by adding this line before the [return](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L973)

    $query->select([$options['keyField'], $options['valueField']]);

now the query selects only the **keyField** and **valueField**

before

    SELECT Establishments.id AS `Establishments__id`, Establishments.title AS `Establishments__title`, Establishments.state AS `Establishments__state`, Establishments.mail AS `Establishments__mail`, Establishments.phone AS `Establishments__phone`, Establishments.mobile AS `Establishments__mobile`, Establishments.fax AS `Establishments__fax`, Establishments.zip_code AS `Establishments__zip_code`, Establishments.address AS `Establishments__address`, Establishments.created AS `Establishments__created`, Establishments.modified AS `Establishments__modified`, Establishments.deleted AS `Establishments__deleted`, Establishments.deleted_date AS `Establishments__deleted_date`, Establishments.groupestablishment_id AS `Establishments__groupestablishment_id`, Establishments.city_id AS `Establishments__city_id`, Establishments.created_by AS `Establishments__created_by`, Establishments.modified_by AS `Establishments__modified_by`, Establishments.deleted_by AS `Establishments__deleted_by` FROM establishments Establishments
after

    SELECT Establishments.id AS `Establishments__id`, Establishments.title AS `Establishments__title` FROM establishments Establishments

**Comment by lorenzo** [comment]
This could be an enhancement. The way it could work is checking if the keys passed are actually properties in the table schema. If they are then it is safe to issue a `select()` otherwise proceed as it is working now

**Comment by flashios09** [comment]
Sorry @lorenzo i didn't understand 
This is a **bug** or not ! I'm confused :(
If it's not a bug why i have to select all the others fields on the table when i need only two ?

**Comment by lorenzo** [comment]
No, it is not a bug. You will need to select the fields yourself. For a future version in can be made more intelligent so you don't always have to do it.

**Comment by lorenzo** [comment]
To answer you question: Currently it is a dumb implementation because it does not look into what the fields are. The reason it does not blindly select the fields you pass is because the list is constructed out of entity properties, which can include virtual properties.

**Comment by flashios09** [comment]
Ok i understand now :)
So everytime that i want to use the **find('list')** on controller/table i have to chain it with 
**->select(['keyField', 'valueField'])**.

**Comment by lorenzo** [comment]
correct

**Comment by flashios09** [comment]
@lorenzo  thanks :)

**Comment by lorenzo** [comment]
I'm going to reopen as I think it can be a good enhancement for 3.1

**Comment by markstory** [comment]
We would have to check the schema and fallback to selecting all columns if the key/value are not present in the schema.
