### ISSUE TITLE
3.0 - find doesnt use backtick when building query

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#6189]
ie. it gives query like this:

```mysql
SELECT Languages.id AS `Languages__id`, Languages.full AS `Languages__full`, Languages.ISO-639-1 AS `Languages__ISO-639-1`, Languages.ISO-639-2 AS `Languages__ISO-639-2` FROM languages Languages WHERE NOT (Languages.id = :c0)
```

fields like ISO-639-1 breaks a bit of things

**Comment by antograssiot** [comment]
You probably turn on identifier quoting by adding
```php
'quoteIdentifiers' => true
```
in you database config as stated [here](http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration) in the documentation.

**Comment by AD7six** [comment]
Duplicate: https://github.com/cakephp/cakephp/issues/4028

Docs: http://book.cakephp.org/3.0/en/orm/database-basics.html#identifier-quoting
