### ISSUE TITLE
Nginx rewriting doesn't work out of the box.

### ISSUE THREAD

**Issue by drewmassey** [cakephp/cakephp#6194]
Maybe the 3.0 Documentation could reflect the recommended way for doing it, with a 301?

http://nginx.org/en/docs/http/converting_rewrite_rules.html

**Comment by markstory** [comment]
Since you seem to know what's wrong and how to fix it would you be able to update the documentation?

**Comment by drewmassey** [comment]
Ok, submitted a pull request.
