### ISSUE TITLE
add an option to disable type-casting for result set

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#6198]
For reading a few hundred database-entries the ORM is not very fast. Disabling hydration helps, but the type casting is very slow too. From what I can see there's no main culprit, it's just the abstraction overhead and gazillions of method calls. Nonetheless casting `DateTimeType` deserves a honorary mention.

It would be nice to have something like `->typeCast(false)` analog to `->hydrate(false)` to disable type-casting as early as possible.

**Comment by lorenzo** [comment]
I think this could make sense, giving how heavy the process of typecasting is.

**Comment by markstory** [comment]
Why not  use the lower level database APIs if you don't want the overhead of the orm?

**Comment by Schlaefer** [comment]
By lower level database API you mean bypassing Cake completely?

**Comment by lorenzo** [comment]
No @Schlaefer, he meas using the `$connection->newQuery()->select()....`

**Comment by Schlaefer** [comment]
> $connection->newQuery()->select() …

Ok, that works. But having associations makes it verbose and you end up with what is essentially a copy of `ResultSet::_groupResults()` that omits hydration and typecasting.

I'm rolling with that now. But I still would prefer a single line switch over 40 lines of custom code.

**Comment by lorenzo** [comment]
@Schlaefer have you tried after the recent performance improvements?

**Comment by Schlaefer** [comment]
@lorenzo no, wasn't on latest

time in ms:


388debb localhost

```
190	† cake full
138	† cake without hydration
59	† $this->connection()->newQuery()
```

15dc559 localhost
```
90	† cake full
75	† cake without hydration
57	† $this->connection()->newQuery()
```

---

388debb server

```
60	† cake full
38	† cake without hydration
18	† $this->connection()->newQuery()
```

15dc559 server
```
29	† cake full
21	† cake without hydration
17	† $this->connection()->newQuery()
```


There seems to be a significant improvement. :+1: I think this puts the performance into the good enough range for me.

**Comment by lorenzo** [comment]
Thanks for the benchmarks, I see the changes made a big difference!

**Comment by Schlaefer** [comment]
@lorenzo But one of my test cases is failing with the latest changes. See #6214 :umbrella:

**Comment by markstory** [comment]
Closing as the performance is much better, and #6214 has been opened.
