### ISSUE TITLE
cakephp 2.6.3 Digest Auth-Error: Class 'DigestAuthenticate' not found	

### ISSUE THREAD

**Issue by gerrymcdonnell** [cakephp/cakephp#6201]
Digest Auth-Error: Class 'DigestAuthenticate' not found

in the manual is states;
http://book.cakephp.org/2.0/en/core-libraries/components/authentication.html

class User extends AppModel {
    public function beforeSave($options = array()) {
        // make a password for digest auth.
        $this->data[$this->alias]['digest_hash'] = DigestAuthenticate::password(
            $this->data[$this->alias]['username'],
            $this->data[$this->alias]['password'],
            env('SERVER_NAME')
        );
        return true;
    }
}

workaround fix;
Add to user model.php
App::uses('DigestAuthenticate', 'Controller/Component/Auth');

**Comment by dereuromark** [comment]
Your "workaround" is actually the solution. Each class you want to use in a file must be included this way at the top of the file (as per docs).

The example expects you to know that, but if you look an example below you will see that there the statement has been added. We could also add it to yours for clarification, though.
Could you please make a PR for the docs?
Closing this issue then as invalid.

**Comment by ADmad** [comment]
I updated the manual
