### ISSUE TITLE
Inflector::rules seem to ignore irregular extra configuration

### ISSUE THREAD

**Issue by pedro-stanaka** [cakephp/cakephp#6219]
Hello, I'm trying to upgrade (to cake3) a [plugin](https://github.com/pedro-stanaka/cake_ptbr/tree/3.0) that has some files for L10n and I18n of Cake in Pt_BR.

One of these files is [inflections.php](https://github.com/pedro-stanaka/cake_ptbr/blob/3.0/config%2Finflections.php) which add new rules of plural and etc for brazilian portuguese.
The problem that is occurring to me is that I require this file in my test bootstrap and when I try to run my tests concerning about Inflections all the assertions about irregulars plurals/singulars present failures.

```php

<?php

    /**
     * teste plural irregular
     * @return void
     */
    private function testPluralIrregular()
    {
        $this->assertEquals('Alemaes', Inflector::pluralize('Alemao'));
        $this->assertEquals('Maos', Inflector::pluralize('Mao'));
        $this->assertEquals('Caes', Inflector::pluralize('Cao'));
        $this->assertEquals('Repteis', Inflector::pluralize('Reptil'),);
        $this->assertEquals('Sotaos', Inflector::pluralize('Sotao'));
        $this->assertEquals('Paises', Inflector::pluralize('Pais'));
        $this->assertEquals('Pais', Inflector::pluralize('Pai'));
    }
```

Am I doing something wrong or this is a bug in Inflector class?

**Comment by markstory** [comment]
There are a [few test cases](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Utility/InflectorTest.php#L496-L547) for custom rules that are passing. Are you sure that your rules are being loaded in your test?

**Comment by pedro-stanaka** [comment]
Yeah, I made a mistake somewhere, I just have to find it. I put one rule just above my test and it worked, for some mysterious reason my file (inflections.php) is not being loaded before my tests, even though I required it.
Thanks anyway, you guys always answer soo fast.

**Comment by pedro-stanaka** [comment]
I managed to get it to work. Thanks @markstory.
