### ISSUE TITLE
Find edgecase does not generate valid query conditions

### ISSUE THREAD

**Issue by dogmatic69** [cakephp/cakephp#6222]
My Code (latest 2.x branch)
```

$conditions = array(
	array($this->alias . '.salesman_member_id != ' => (array)$this->SalesmanMember->AdminSecurity->find('members', 'external-sales')),
	array($this->alias . '.salesman_member_id != ' => (array)$this->SalesmanMember->AdminSecurity->find('members', 'consulting-sales')),
);
```
that is generating something like the following
```
'conditions' => array(
array('ShopOrder.salesman_member_id != ' => array(1, 2, 3)),
array('ShopOrder.salesman_member_id != ' => array(4)),
)
```
which is rendered as SQL 

```
(((`ShopOrder`.`salesman_member_id` NOT IN (1, 2, 3)) AND (`ShopOrder`.`salesman_member_id` != = ('4'))))
```

It seems that with only one item in the list it does not generate the `NOT IN` but instead keeps the `!=` and adds a second `=` to the query.

Hacked it by adding  `+ array(-1 => -1)` so there is an extra entry in the array and it works fine then.

**Comment by dereuromark** [comment]
Why is there an empty space in `!= '`? Should be `!='`.

**Comment by dogmatic69** [comment]
White space is not the problem here.

**Comment by dereuromark** [comment]
Whitespace at the end is still not officially supported, nor are there any tests for it. So please remove it and check if the issue still persists then.

There are however tests for the non-whitespace version:
`'Article.id !=' => array(1)`
They seem to pass so far.

**Comment by dereuromark** [comment]
The resulting query is `AS `Article` WHERE `Article`.`id` NOT IN (1) ORDER BY `Article`.`id` ASC` by the way.
So I disagree and say that the invalid whitespace is the issue here.

**Comment by dogmatic69** [comment]
ok, the first one is generated correctly but the second is not. Seems to work ok without the white space, but should be the same regardles (eg: the first condition should render as != = or the second should be NOT IN

**Comment by dereuromark** [comment]
If it works OK without the space, we should close this is "works for me".
Trimming every key is quite the overhead that should not be necessary, as this is clearly a developer's fault IMO.

**Comment by ADmad** [comment]
I agree with @dereuromark, if there's whitespace in field name it's developer's fault not a framework bug. We cannot add the overhead of trimming whitespace.
