### ISSUE TITLE
Implement Cake\Collection\Collection::count for semantics and simplicity

### ISSUE THREAD

**Issue by ramiroaraujo** [cakephp/cakephp#6225]
I plan on doing this for semantics. Actually the ArrayIterator already has count method. Would probably call that if it's the case, or iterate and count. 

Not sure if I can do this, but this would go to the 3.1.0 milestone :)

**Comment by HavokInspiration** [comment]
Closing. The decision to disable the ``count()`` method for ``Collection`` was taken in #7565 and implemented in #7598.
