### ISSUE TITLE
RFC 3.x: Make "static classes" not static

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#6227]
Currently we have many classes in the core containing only static methods, ie: factories, registries, cache etc. But static calls to static methods are very hard to swap or replace in some places, where we could extend their functionality, and obviously hard to mock in tests. And feel very dated.

I was thinking about some way of reducing the number of these static methods or eliminating them at all. For now the easiest would be just to "un-static" methods and allow them to be called statically via _callStatic() on a singleton (probably being a static property of the class). 

This change shouldn't break a BC and should be introduced painlessly. And it would provide an easy way to swap instances with custom ones extending core functionality.

Feel free to comment on this idea and tell me what's wrong with it if nessesary :)

**Comment by markstory** [comment]
Which classes do you think could benefit the most from a static proxy/facade?

**Comment by robertpustulka** [comment]
TableRegistry - I was thinking of a way to "inject" some IOC logic into
model layer in my plugin. While I could override TableRegistry and use my
own Registry where nessessary, association tables wouldn't be injected.

>   Same goes for dispatchers - for shells and controllers.


-- 
Pozdrawiam,
Robert Pustułka

**Comment by lorenzo** [comment]
You can actually pass the fully-built associations object into the table constructor using the `associations` key

**Comment by lorenzo** [comment]
Also, you can pre-configure table aliases before they are built using `TableRegistry::config()`

**Comment by robertpustulka** [comment]
@lorenzo maybe, but I don't want to manually configure things, I want it to be done by my IOC.

Anyway that's not the point. The point is entirely static classes are not very OOP and even considered an anti-pattern. It's ok for grouping some utility methods, but IMO factories and registries should be objects so they could be easily mocked and used in many different contexts.

**Comment by lorenzo** [comment]
I'm not opposed to that, I'm just pointing out what you can use now.

**Comment by robertpustulka** [comment]
@lorenzo sorry if that sounded a little bit defensive on my side :)

I just think that's an idea worth pursuing. It could benefit in making CakePHP more flexible and modern framework.bene

**Comment by josegonzalez** [comment]
@robertpustulka would you like to contribute an initial pr demonstrating how it might work?

**Comment by robertpustulka** [comment]
@lorenzo sure, I'll start doing it tomorrow

**Comment by robertpustulka** [comment]
@josegonzalez sure, I'll start doing it tomorrow

**Comment by jadb** [comment]
:+1: Looking forward to it @robertpustulka!

**Comment by markstory** [comment]
DispatcherFactory is static only because it has to maintain state between the primary and any sub-requests that may happen.

While a singleton is possibly more oop, I don't think we should change until we have real use cases that could be facilitated by the proposed changes. It sounds like you have some good ones for TableRegistry.
