### ISSUE TITLE
CakePHP 3.0 - Xml::build() isn't working for remote URL

### ISSUE THREAD

**Issue by maurymmarques** [cakephp/cakephp#6229]
I'm not being able to build a Xml for remote URL

```php
namespace App\Controller;
use Cake\Utility\Xml;

class ReadersController extends AppController 
{
    public function index() 
    {
        $url = 'http://bakery.cakephp.org/articles.rss';
        $xml = Xml::build($url);
        debug($xml);
    }
}
```
I'm getting the following exception:
`XML cannot be read. Cake\Utility\Exception\XmlException`

It seems that the remote URL reading was not implemented yet but it's in documentation
http://book.cakephp.org/3.0/en/core-libraries/xml.html
http://api.cakephp.org/3.0/class-Cake.Utility.Xml.html

**Comment by josegonzalez** [comment]
No, it says local files, not remote files.

```php
// Local file
$xml = Xml::build('/home/awesome/unicorns.xml');
```

**Comment by maurymmarques** [comment]
You can see it in the API documentation...
http://api.cakephp.org/3.0/class-Cake.Utility.Xml.html

It was working for CakePHP 2.x

**Comment by Xety** [comment]
I don't know if it's a bug in the function or in the doc function, but you can still use the `Http Client` :
```php
use Cake\Network\Http\Client;

$http = new Client();
$response = $http->get('http://example.com/example.xml');

$xml = Xml::build($response->body());
```

**Comment by maurymmarques** [comment]
That works using `Http Client`, @Xety. Thank you.
@dereuromark added it to milestone 3.0.1. 
Thank you.

**Comment by lorenzo** [comment]
The support for remote files was removed for security reasons. You can use the Http Client class that comes bundled with CakePHP

**Comment by maurymmarques** [comment]
@lorenzo but it should be removed from the API, or the comments in the Xml Class.
http://api.cakephp.org/3.0/source-class-Cake.Utility.Xml.html#46
Thank you.

**Comment by lorenzo** [comment]
@maurymmarques would you like to take that task? You can do it by going to the source code for that class, removing the obsolete parts from the function doc block and sending us a pull request.

**Comment by maurymmarques** [comment]
Yes, I would like to help you, but I have some questions. May I contact you? My Skype: maurymaddog

**Comment by lorenzo** [comment]
You can add your questions related to that task here :)
