### ISSUE TITLE
CakePHP 3.0 Undefined index: on_update

### ISSUE THREAD

**Issue by StanekP** [cakephp/cakephp#6230]
Sometimes get those errors:
Notice (8): Undefined index: on_update [CORE/src/Database/Schema/SqliteSchema.php, line 214]
Notice (8): Undefined index: on_delete [CORE/src/Database/Schema/SqliteSchema.php, line 215]

I use mysql and php 5.5

Logs from debug.log:
2015-03-31 15:02:20 Notice: Notice (8): Undefined index: on_update in [/home/users/muzyczni/public_html/vendor/cakephp/cakephp/src/Database/Schema/SqliteSchema.php, line 214]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\Database\Schema\SqliteSchema::convertForeignKeyDescription() - CORE/src/Database/Schema/SqliteSchema.php, line 214
Cake\Database\Schema\Collection::_reflect() - CORE/src/Database/Schema/Collection.php, line 133
Cake\Database\Schema\Collection::describe() - CORE/src/Database/Schema/Collection.php, line 102
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 65
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 422
Cake\ORM\Marshaller::one() - CORE/src/ORM/Marshaller.php, line 107
Cake\ORM\Table::newEntity() - CORE/src/ORM/Table.php, line 1953
Cake\ORM\Association::__call() - CORE/src/ORM/Association.php, line 835
Cake\ORM\Association\HasMany::newEntity() - ROOT/vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php, line 207
DebugKit\Routing\Filter\DebugBarFilter::afterDispatch() - ROOT/vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php, line 207
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 351
Cake\Routing\Dispatcher::dispatchEvent() - CORE/src/Event/EventManagerTrait.php, line 78
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 92
[main] - ROOT/webroot/index.php, line 37

2015-03-31 15:02:20 Notice: Notice (8): Undefined index: on_delete in [/home/users/muzyczni/public_html/vendor/cakephp/cakephp/src/Database/Schema/SqliteSchema.php, line 215]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
Cake\Database\Schema\SqliteSchema::convertForeignKeyDescription() - CORE/src/Database/Schema/SqliteSchema.php, line 215
Cake\Database\Schema\Collection::_reflect() - CORE/src/Database/Schema/Collection.php, line 133
Cake\Database\Schema\Collection::describe() - CORE/src/Database/Schema/Collection.php, line 102
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 65
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 422
Cake\ORM\Marshaller::one() - CORE/src/ORM/Marshaller.php, line 107
Cake\ORM\Table::newEntity() - CORE/src/ORM/Table.php, line 1953
Cake\ORM\Association::__call() - CORE/src/ORM/Association.php, line 835
Cake\ORM\Association\HasMany::newEntity() - ROOT/vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php, line 207
DebugKit\Routing\Filter\DebugBarFilter::afterDispatch() - ROOT/vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php, line 207
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 351
Cake\Routing\Dispatcher::dispatchEvent() - CORE/src/Event/EventManagerTrait.php, line 78
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 92
[main] - ROOT/webroot/index.php, line 37

**Comment by markstory** [comment]
What version of SQLite do you have?

**Comment by StanekP** [comment]
Version of SQLite is 3.5.9 (if is too old for DebugKit, u could add info about it on welcome screen)

**Comment by markstory** [comment]
I don't think that's tool old, but I would have also expected that reflecting foreign keys would work too.

**Comment by jhon312020** [comment]
Any update on the above issue?  I am too getting the same issue.

**Comment by lorenzo** [comment]
Foreign keys are supported since SQLite 3.6.19

I would suggest looking into updating your sqlite or PHP version while this issue is investigated.

**Comment by markstory** [comment]
@jhon312020 DebugKit uses SQLite which is probably why you are seeing this error even though you are using MySQL for your application.

**Comment by jhon312020** [comment]
PHP Version 5.4.10 - Will cakephp 3.0.1 will work with this php version?
Mysql Client API version 5.0.77  - Will cakephp 3.0.1 will work with this mysql version?
Upgraded to latest 3.0.1 version of cakephp too.
mbstring extension is enabled.
intl extension is enabled.
SQLite Library 

On making app.php "debug" value to true - I am getting the issue "unable to server this request".
When I change  "debug" value to true - I am getting the same issue
Notice (8): Undefined index: on_update [CORE/src/Database/Schema/SqliteSchema.php, line 214]
Notice (8): Undefined index: on_delete [CORE/src/Database/Schema/SqliteSchema.php, line 215]

**Comment by lorenzo** [comment]
@jhon312020 read my comment here: https://github.com/cakephp/cakephp/issues/6230#issuecomment-90133750

**Comment by jhon312020** [comment]
I am not even created a database it is just a fresh copy and I am going to use only mysql.  I have also commented the plugin debugkit which uses sqlite by default.

**Comment by lorenzo** [comment]
@jhon312020 You can also configure debugkit to sue mysql if you are having troubles with sqlite http://book.cakephp.org/3.0/en/debug-kit.html#database-configuration

**Comment by jhon312020** [comment]
@lorenzo - Thanks for your timely responses.

PHP Version 5.4.10 - **Will cakephp 3.0.1 will work with this php version?**
Mysql Client API version 5.0.77 - **Will cakephp 3.0.1 will work with this mysql version?**

**Comment by dakota** [comment]
@jhon312020 
http://book.cakephp.org/3.0/en/installation.html#requirements states PHP 5.4.16 minimum, as far as I know this is due to a bug in earlier versions of PHP 5.4

Your MySQL Client doesn't matter too much (The server version is the important one), requirements document states 5.1.10.

Easiest way to find out if it will work is to try it!

**Comment by jhon312020** [comment]
@dakota I tried but getting the following
On making app.php **debug** value to **true** - I am getting the issue **unable to server this request**.
When I change **debug** value to true - I am getting the issue
**Notice (8): Undefined index: on_update [CORE/src/Database/Schema/SqliteSchema.php, line 214]
Notice (8): Undefined index: on_delete [CORE/src/Database/Schema/SqliteSchema.php, line 215]** 
or sometimes this
**unable to server this request**.

**Comment by dakota** [comment]
@jhon312020 That's got nothing to do with MySQL, see https://github.com/cakephp/cakephp/issues/6230#issuecomment-90133750

You need to updated your Sqlite version, or configure DebugKit to use MySQL.

**Comment by jhon312020** [comment]
@dakota I added the debug_kit to app.php pointing to mysql.  Then also getting the same result

**Notice (8): Undefined index: on_update [CORE/src/Database/Schema/SqliteSchema.php, line 214]**
Notice (8): Undefined index: on_delete [CORE/src/Database/Schema/SqliteSchema.php, line 215]**
or sometimes this
**unable to serve this request.**

**Comment by ceeram** [comment]
@jhon312020 perhaps drop by on irc to get support on getting things to work and keep this issue tracker for actual bugs.

**Comment by markstory** [comment]
Fixed in #6302
