### ISSUE TITLE
Inflector issues with singularization of singular words not matching their plural form: Analysis and Sieve

### ISSUE THREAD

**Issue by jtyost2** [cakephp/cakephp#6236]
Analysis: http://inflector.cakephp.org/analysis
vs.
Analyses: http://inflector.cakephp.org/analyses

Analysis singularizes down to analysi - which isn't a word: http://dictionary.reference.com/misspelling?term=analysi&s=t and doesn't match the singularize version of it's matching plural form (analyses).

Sieve: http://inflector.cakephp.org/sieve
vs.
Sieves: http://inflector.cakephp.org/sieves

Sieves singularizes down to sief - which isn't a word: http://dictionary.reference.com/misspelling?term=sief&s=t and doesn't match the pluralize version of it's matching singular form (sieve).

Edit: corrected sieves vs sieve in the example for inflection.

**Comment by markstory** [comment]
Many singular words cannot be re-singularized. Given that pluarlize(analysis) = analyses, and singularize(analyses) = analysis, I don't see an issue there.

Sieves does seem to be an issue though, as the plural form does not singularize properly.

**Comment by jtyost2** [comment]
I don't know (obviously) Cake's intended behavior for singularizing an already singular word. I can say I'm using it to ensure a word that I don't know is singular or plural is singular for when I need it. For most words I've come across, minus these cases, it's worked as I expect.

**Comment by jtyost2** [comment]
In other words, if that is the expected behavior of Cake's Inflector: re-singularizing an already singular word may not work, and I assume the same with plural words. Should the docs be updated to reflect that?

**Comment by jtyost2** [comment]
I'll also note: Analysis is broken not just for the singularize when it tries to classify Analysis, it breaks as well: `Inflector::classify("analysis") -> "Analysi"`

**Comment by jtyost2** [comment]
Again here the docs don't explicitly state you can't use a singular word when using classify (though all the examples in singularize and classify are plural formats), but it general it at least seems to "just work".

**Comment by markstory** [comment]
I don't think we've ever published any promises that Inflector::singularize() will do the right thing with singulars, but I know that both it and pluralize() are not safe to use on nouns in those formats. Perhaps that should be something that is made more clear in the documentation.

**Comment by jtyost2** [comment]
Fair enough, I'll work on a Docs PR to hopefully clarify this case.

Thank you.

**Comment by ADmad** [comment]
Closing as docs PR are open.

**Comment by jtyost2** [comment]
@ADmad I believe `sieves` is still an issue, the singularize version is incorrect: http://inflector.cakephp.org/sieves

As noted earlier: https://github.com/cakephp/cakephp/issues/6236#issuecomment-88306102

If you want I can open an issue tied to just that one case, to clear out all this other cruft.

**Comment by ADmad** [comment]
@jtyost2 Sure, PR fixing singularization of plural words is welcome.
