### ISSUE TITLE
Can't call cake command

### ISSUE THREAD

**Issue by NeroGnine** [cakephp/cakephp#6242]
I'm installing cakephp 3.0 for 2 hours and still get errors.  
I don't know what to do .... 
![2015-04-01_10-45-02](https://cloud.githubusercontent.com/assets/11030549/6934516/31ef726a-d85c-11e4-82db-0122a300770e.png)

**Comment by antograssiot** [comment]
@NeroGnine  seems that you're trying to load Migrations without installing it.
did you require cakephp/migrations "@stable" with composer ??

**Comment by antograssiot** [comment]
@NeroGnine did you require cake globally on your system  ? what did you add to your $PATH ?
