### ISSUE TITLE
Cake 3.x: Ability to manipulate recipients separate to To/CC/BCC headers

### ISSUE THREAD

**Issue by Mirelath** [cakephp/cakephp#6248]
Hi there,

When using Cake3's email class, I'd like to be able to separate modifying the envelope and modifying the email, in particular the behaviour of specifying the recipients independently from specifying the To/CC addresses. When using Cake to facilitate any kind of email forwarding, it's necessary to keep the original to address and CC addresses while forwarding on to a new recipient (and without those in the CC line getting multiple copies). At the moment, this isn't possible as the recipients are built from the lists directly

`function _prepareRecipientAddresses()
    {
        $to = $this->_cakeEmail->to();
        $cc = $this->_cakeEmail->cc();
        $bcc = $this->_cakeEmail->bcc();
        return array_merge(array_keys($to), array_keys($cc), array_keys($bcc));
    }`

If it'd be possible to use a function to override the recipient list (e,g. $email->setRecipients()) and use that instead of building it from the headers, that'd be very handy! This would allow manipulation of the envelope, as well as the email, which is useful sometimes.

Many thanks

**Comment by markstory** [comment]
I'm not sure the envelope recipient being different than the To address will supported by `mail()`. This might end up only being supported by Smtp which would be a little inconsistent.

**Comment by markstory** [comment]
Closing for lack of interest.
