### ISSUE TITLE
Bookmarker Tutorial Part 2 issue

### ISSUE THREAD

**Issue by andrewrguy** [cakephp/cakephp#6249]
I am going through the Cake 3.x Bookmarker Tutorial Part 2 and I believe I have found an issue either in the documentation or with the code. Specifically, I updated the add() method in BookmarksController like it suggests in the documentation to automatically assign the user_id to the logged in user. The code is like this:
```php
public function add()
{
    $bookmark = $this->Bookmarks->newEntity();
    $bookmark->user_id = $this->Auth->user('id');
    if ($this->request->is('post')) {
        $bookmark = $this->Bookmarks->patchEntity($bookmark, $this->request->data);
        if ($this->Bookmarks->save($bookmark)) {
            $this->Flash->success('The bookmark has been saved.');
            return $this->redirect(['action' => 'index']);
        }
        $this->Flash->error('The bookmark could not be saved. Please, try again.');
    }
    $tags = $this->Bookmarks->Tags->find('list');
    $this->set(compact('bookmark', 'tags'));
}
```
I also removed input(user_id) from the form. However, it does not save and $bookmark->errors() contains:
```php
Array
(
    [user_id] => Array
        (
            [_required] => This field is required
        )
)
```
I noticed I can fix it by moving the $bookmark->user_id assignment below the patchEntity() call, like this:
```php
$bookmark = $this->Bookmarks->patchEntity($bookmark, $this->request->data);
$bookmark->user_id = $this->Auth->user('id');
```
It appears the edit() method works like this, so, again I don't know if this is just a documentation problem or a problem with patchEntity()

**Comment by dereuromark** [comment]
Documentation issues should be posted in https://github.com/cakephp/docs

**Comment by dereuromark** [comment]
Yes, you can just make a quite PR that fixes the issue. It is still some left overs from pre-stable. Thank you.

**Comment by markstory** [comment]
What do the generated validation rules on your table look like?

**Comment by andrewrguy** [comment]
Is this what you mean?
```php
public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create')
            ->add('user_id', 'valid', ['rule' => 'numeric'])
            ->requirePresence('user_id', 'create')
            ->notEmpty('user_id')
            ->allowEmpty('title')
            ->allowEmpty('description')
            ->allowEmpty('url');

        return $validator;
    }
```

**Comment by markstory** [comment]
Yeah that's it. In the newest version of bake, validation rules are not created for foreign key columns anymore. Instead rules checkers are used which is another solution to this problem. In any case, thank you for the docs pull request in cakephp/docs#2590

**Comment by neetagit** [comment]
how  to save data in bookmark_tags table?
