### ISSUE TITLE
Transactions not rolled back on exception in 2.6

### ISSUE THREAD

**Issue by jtv4k** [cakephp/cakephp#6251]
DboSource introduced its own destructor on commit 762ebd4b939d510720590d34ce29bda858eb7d0d long, long ago. The parent's destructor, DataSource::__destruct, rolls back any started transactions. 

Before 762ebd4b939d510720590d34ce29bda858eb7d0d, exceptions caused a rollback via calling DataSource::__destruct. The newer destructor does not call the parent's destructor, so transactions are no longer rolled back.

I doubt the intention of introducing DboSource::__destruct included removing this behavior. I request it be re-introduced.

**Comment by markstory** [comment]
Fixed in b2958dad79926f46c366a28ce5e4d31028a1d782
