### ISSUE TITLE
FormHelper default dateWidget template should vary based on the current localization

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#6257]

**Comment by lorenzo** [comment]
Would you like to implement this feature?

**Comment by efanzini** [comment]
i can try

**Comment by markstory** [comment]
I don't even really understand what this feature is? Could you provide an example of how it would work or what the output would be?

**Comment by efanzini** [comment]
i coded this in a hurry.

```php
public function __construct(View $View, array $config = [])
{
	
	$replacements = [
		'y' => '{{year}}',
		'M' => '{{month}}',
		'd' => '{{day}}',			
		'h' => '{{hour}}',
		'H' => '{{hour}}',
		'm' => '{{minute}}',
		's' => '{{second}}'
	];
	
	$idf = new IntlDateFormatter(I18n::locale(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM);
	
	$pattern = $idf->getPattern();
	$pattern = str_replace(['/', ':', ' ', ','], '', $pattern);
	
	foreach ($replacements as $search => $replacement) {
		$pattern = preg_replace('/' . $search . '+(?![^{]*})/', $replacement, $pattern);
	}

	$config['templates']['dateWidget'] = $pattern;
	
	parent::__construct($View, $config);

}
```

**Comment by markstory** [comment]
Oh ok. Auto localizing the date pickers should be optional as well if we implement this. But it seems like a useful addition for multilingual sites.

**Comment by efanzini** [comment]
i think it should be enabled by default if i18n is in use

**Comment by markstory** [comment]
@efanzini i18n is always in use :smile:

**Comment by CauanCabral** [comment]
I think its great not only for multilingual sites, but all sites/applications where 'mdY' is not default.

Also, it can be enabled like i18n for DateTime in ORM[1], or maybe in FormHelper configs.

[1] - http://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html#parsing-localized-datetime-data

**Comment by efanzini** [comment]
@markstory so it should be enabled by default :smile:

**Comment by markstory** [comment]
@efanzini Yes :smile:

**Comment by markstory** [comment]
Closing as `FormHelper` has been updated to use HTML5 inputs in 4.0. See #12934
