### ISSUE TITLE
Q: Are there alternatives to "echo" in views?

### ISSUE THREAD

**Issue by rvarbanov** [cakephp/cakephp#6260]
Are there alternatives to `echo`? 

I currently to do this:
```
// in /view.ctp
<h1><?php echo $pageTitle; ?></h1>
```
Is there an option to do something like this:
```
<h1>{{$pageTitle}}</h1>
```

I read the docs but could not find anything like that. I was just wondering about that and not really looking to add that as a feature to CakePHP. I am totally fine using `echo` as is if similar feature is not available at the moment :smile: 

PS: I am aware of shorthand `<?=$pageTitle?>`, but and that is not what I am looking for.

**Comment by josegonzalez** [comment]
Our templating is just plain old php - no need to reinvent that - so the shorthand is the way to go (and honestly I can't see why `{{}}` is okay but `<?= ?>` isnt). 

You can also swap the view class with something like twig if that is more to your liking, but the core's templating language is staying in plain php :)

**Comment by rvarbanov** [comment]
Thank you @josegonzalez for the quick reply. Yes, it is the same thing for the most post. 

I was just wondering.

**Comment by josegonzalez** [comment]
No problem! :)
