### ISSUE TITLE
Password rehash fails after rehash

### ISSUE THREAD

**Issue by Jnesselr** [cakephp/cakephp#6267]
I followed the guide in the book, and I think there's an issue with using the default password hasher. My app rehashes correctly, but then the next login attempt fails.

App: https://github.com/Hoektronics/BotQueue/tree/ece3938593805c52f69efe7ddf284b1945ffd45d

**Comment by markstory** [comment]
Are you sure you're not hashing a hash?

**Comment by Jnesselr** [comment]
Nope, not sure at all. What part of the code gives you that indication? I
guess there's an easy way to test it.

**Comment by markstory** [comment]
I didn't read your entire application, my time is limited. But I do know that authentication works as I have a few apps working with bcrypted passwords.

**Comment by lorenzo** [comment]
Your password column is to short: https://github.com/Hoektronics/BotQueue/blob/ece3938593805c52f69efe7ddf284b1945ffd45d/config/Migrations/20150323192043_initial.php#L28

Give it at least 60 characters

**Comment by Jnesselr** [comment]
That works perfectly, thank you very much!
