### ISSUE TITLE
patchEntities() fails with csrfToken

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#6271]
Hello,

I encounter a persistent error while trying to a apply patchEntities() with request->data containing a csrfToken.

The error is:
errorUnserializable object - InvalidArgumentException. Error: Passed variable is not an array or object, using empty array instead in /home/modulwoo/www/2ndGuideTest/vendor/cakephp/cakephp/src/ORM/Marshaller.php, line 200.

Jose found a workaround adding unset($this->request->data['_csrfToken']); before the call to patchEntities().

Code and datas are here: https://gist.github.com/caBBAlainB/77d6e939a7a2a0a48a32.

Regards.

**Comment by markstory** [comment]
Normally I would put the multiple entities under a top level key to avoid this issue. However, an annoying person could add additional string inputs in that key and trigger the same error.
