### ISSUE TITLE
Make Shell::dispatchShell() not output welcome message

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/cakephp#6272]
Hi there !
Do you think it would be possible to make a call to ``Shell::dispatchShell()`` not output the welcome message ?
Because I need to dispatch a Shell from inside a Shell and the second welcome message feels kind of noisy.
It currently renders as this :

```
Welcome to CakePHP v3.0.0 Console
---------------------------------------------------------------
App : src
Path: /home/yves/PhpStormProjects/cakephp-app/src/
---------------------------------------------------------------

First Shell output
Need to dispatch another shell inside this one

Welcome to CakePHP v3.0.0 Console
---------------------------------------------------------------
App : src
Path: /home/yves/PhpStormProjects/cakephp-app/src/
---------------------------------------------------------------

Second shell output
```

By the looks of ``Shell::runCommand()``, it would seem that it is not possible to do it right now.

**Comment by markstory** [comment]
Your second shell could override `_welcome()` to suppress the message. Another option might be to include additional parameters - like 'requested' - when sub shells are executed, and have the default welcome message turn itself off when the requested parameter is present.

**Comment by HavokInspiration** [comment]
I did not think of the simplest way, looking for a parameter... I'll do your first option for the moment.
About your second idea, do you think of something like this :

```sh
./bin/cake my_shell my_command --requested
```

And the welcome message would be turned off ?
I like this idea.

**Comment by markstory** [comment]
@HavokInspiration That could work, dispatchShell() could splice that parameter in automatically too.

**Comment by jadb** [comment]
Maybe `--no-welcome` would better reflect what it does?

**Comment by HavokInspiration** [comment]
@jadb It does better reflect what the parameter would do by default in the core, but in my opinion, I think having a more "general" name might be better since it could be used by users' shells to detect if a shell was dispatched using ``dispatchShell()`` and have specific actions based on that (like logging or whatever, I don't really have an example that comes to mind).
About the specific word ``requested``, I do not know if it really fits or if another one might be better though.

I started working on this. I have the feature working okay (just the call with ``--requested`` in a "classic" shell call) but I have a hard time adding tests (mocks do not really like me). I'll take another try at this tonight if I find the time.

**Comment by bravo-kernel** [comment]
+1 on this feature as it would be really useful for my cakebox project. As far as naming preferences go I would prefer:

+ the ``--no-welcome`` option if that's all the switch will do
+ the ``--requested`` option if it does more (or is intended to do more in the future)

**Comment by HavokInspiration** [comment]
Done in #6292
