### ISSUE TITLE
3.x How to not save existing saved data?

### ISSUE THREAD

**Issue by Adnan0703** [cakephp/cakephp#6275]
$data = [
            'title' => 'Movie title',
            'stars' => [
                'name' => 'mark',
            ]
        ];
How can I save this data without saving mark  again? It should get mark id instead of saving mark again. Is there any existing method/way of doing this?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
