### ISSUE TITLE
Cakephp 3.0 - Url to the plugin without slashes gives an error message

### ISSUE THREAD

**Issue by salines** [cakephp/cakephp#6279]
I bake a fresh application, also bake a plugin, call it Admin. When in the web browser type the URL http://localhost/myapp/admin I get an error message; Error: WebrootController could not be found

But if I type a slash at the end of the url (http://localhost/myapp/admin/), I normally access the first page of the plugin, also all the other links within the plugin work properly, for example.
myapp/admin/users
myapp/admin/users/edit/1

I tried to turn off the plugin routing, and create rules within the main route.php, but without success.

**Comment by markstory** [comment]
This sounds like an issue with URL rewriting. Do you also have issues displaying CSS or accessing Javascript files?

**Comment by salines** [comment]
No, there is no problem with the display css and js datototeka. Only problem is access plugin without slashes in url

**Comment by markstory** [comment]
I can see if I can reproduce this.

**Comment by markstory** [comment]
I wasn't able to reproduce this locally. I tried:

1. Create a new in-app plugin by hand. I called my plugin ContactManager.
2. Update my composer.json for the new plugin and re-generate the autoloader.
3. Add routes for that plugin. The routes I added were ```php
Router::plugin('ContactManager', function ($routes) {
    $routes->connect('/', ['controller' => 'Contacts', 'action' => 'index']);
    $routes->fallbacks('InflectedRoute');
});
4. Create `plugins/ContactManager/src/Controller/ConctactsController.php`, with a basic debug & die index. method.
5. Go to `cake3.localhost/contact_manager` and see the debug output from step 4.

Is there anything I'm missing or you did differently?
```

**Comment by salines** [comment]
What have I done,
1- bake fresh plugin, call it Admin
2- bake Users MVC within the Admin plugin
3- put the path in the admin/config/routes.php
```
// myapp\plugins\Admin\config\routes.php

<?php
use Cake\Routing\Router;

Router::plugin('Admin', function ($routes) {
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);
    $routes->fallbacks('InflectedRoute');
});
```
4. visit http://localhost/myapp/admin, SUCCESS!
But, my Admin plugin has own theme assets, called 'admin'
5- within myapp\webroot i create admin folder for css, js and img (theme assets)

And error commes here.

**Comment by salines** [comment]
OK, i move css and js to plugin webroot, and now all work.

**Comment by ADmad** [comment]
@salines Do you have `MultiViews` enabled in your apache config?

**Comment by salines** [comment]
# Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks Includes ExecCGI

**Comment by markstory** [comment]
Sounds like you have some webserver configuration issues and that CakePHP is working fine.

**Comment by salines** [comment]
No, I use xampp, now I tried with WAMP server, the same is happening.

I tried in different browsers, there is an interesting situation, when I remove Webroot / admin folder, the error still appears, but if I open a link in incognito window, errors will not be until re-create the admin folder (this I began to frustrate )

Here are some pictures, maybe we do not understand.

http://s22.postimg.org/8vce86ovl/Capture.png
http://s22.postimg.org/gcllneeep/Capture2.png

**Comment by markstory** [comment]
It sounds like your webserver is confusing the directory in your webroot and your plugin name. Generally webroot should not be in your URLs ever, as you should be making the DocumentRoot for your applications the webroot directory.

**Comment by novasdream** [comment]
@salines use your like something like
'''
yourdomain.com/admin/
'''
not 
'''
yourdomain.com/admin
'''

**Comment by szel** [comment]
I've just stumbled on the same error.

Perhaps the .htaccess file from default CakePHP install could be removed or replaced with error message about incorrectly configured DocumentRoot?

I'm referring to the following .htaccess file:
<pre>
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule    ^$    webroot/    [L]
    RewriteRule    (.*) webroot/$1    [L]
</IfModule>
</pre>

**Comment by markstory** [comment]
@szel Wouldn't removing the .htaccess file in the app root, cause URL rewriting to not work out of the box for everyone?

**Comment by szel** [comment]
@markstory Sorry to bother you. It seems that I cannot replicate the error from yesterday :-(

In short - I had a plugin with routes.php:
```php
Router::plugin(
    'TestPlugin',
    ['path' => '/test-plugin'],
    function (RouteBuilder $routes) {
        $routes->connect('/', ['controller' => 'Main', 'action' => 'index']);
        $routes->fallbacks(DashedRoute::class);
    }
);
```
Html helper generated link with '/test-plugin' (no '/' on end of the link).

When I was navigating to:
- /test-plugin/ - everything worked properly;
- /test-plugin - I was redirected to /webroot/test-plugin/ and error page was displayed;

I've found this thread and it seemed that my DocumentRoot did not include webroot/ directory - after fixing this:
- /test-plugin started to redirect to /test-plugin/ and everything worked properly;

**Comment by shahvirag07** [comment]
Hi,

Run your application with cake command:
**bin/cake server** OR with **make virtual host**

Your application might have same folder as your route prefix inside webroot directory.

Thanks,
Virag Shah

**Comment by Tomicapo** [comment]
This happend to me today. 
I'm using a plugin named: "backend"
Also using prefix named: "backend"

Had to change the document root to webroot (wich, on cPanel is not simple to do).
But that did fix the issue.
