### ISSUE TITLE
Cakephp3 can't load plugin

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [cakephp/cakephp#6282]
Hi,
I'm trying to load my component plugin into cakephp3.
I have this files:
/plugins/CurrencyConverter/src/Controller/Component/CurrencyConverterComponent.php

The file now is only:
```
namespace CurrencyConverter\Controller\Component;

use Cake\Controller\Component;

class CurrencyConverterComponent extends Component
{   
}
```

So I have edit bootstrap.php file in this way:
```
Plugin::load('CurrencyConverter');
```

In Controller I have load the plugin in this way:
```
namespace App\Controller;

use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;

class ExampleController extends AppController {
    public $components = array(
        'CurrencyConverter.CurrencyConverter'
    );

    public function index () {
        $amount = '2100,00';
        $price = $this->CurrencyConverter->convert('GBP', 'EUR', $amount, 1, 1);

        $this->set('original_price', $amount.' GBP');
        $this->set('converted_price', $price.' EUR');
    }
}
```

When I launch the site return me this error:
```
CurrencyConverter.CurrencyConverterComponent could not be found.

Make sure your plugin was loaded from config/bootstrap.php and Composer is able to autoload its classes, see Loading a plugin and Plugins - autoloading plugin classes

Error: Create the class CurrencyConverterComponent below in file: /Users/myuser/Sites/cakephp3/plugins/CurrencyConverter/src/Controller/Component/CurrencyConverterComponent.php


<?php
namespace CurrencyConverter\Controller\Component;

use Cake\Controller\Component;

class CurrencyConverterComponent extends Component
{

}
```

I have also tried to load plugin in this way but doesn't solve:
```
public $components = array(
        'CurrencyConverter'
    );
```

How can I solve this?

Thanks

**Comment by ADmad** [comment]
You are most probably missing the namespace to path mapping in your app's composer.json for your plugin.

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
