### ISSUE TITLE
Rename Validation::notEmpty()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#6284]
Due to the presence of `Validator::notEmpty()`, `Validation::notEmpty()` can no longer be used as a validation rule. This creates confusion for newbies who try using `notEmpty` as a validation rule and don't get the expected result. 

Since this method also checks for whitespace it would be useful to users and instead of removing it altogether it would be better to rename it to `Validation::notBlank()` (or any other suitable name).

**Comment by lorenzo** [comment]
whoops, fat fingers... Closed the issue by mistake.

**Comment by lorenzo** [comment]
I think it is a good idea to rename it

**Comment by ADmad** [comment]
Closing as PR is open.
