### ISSUE TITLE
Add interfaces for Fixtures and Connections

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#6288]
When working on fixture support for cakephp/elastic-search I bumped into a few places where having interfaces instead of implementation/base classes would have helped. Both fixtures and Connection objects have implicit interfaces that formalizing can help with.

### Fixtures

Fixtures have a fairly small public interface:

```php
class FixtureInterface
{
  public function create(ConnectionInterface $db);
  public function insert(ConnectionInterface $db);
  public function drop(ConnectionInterface $db);
  public function truncate(ConnectionInterface $db);
}
```

In addition the above fixtures should have methods added for `connectionName()`, `activeConnections()` and `table()`. Right now these are public properties that need methods.

### Connections

This interface is far less clear to me, but currently includes the following based on how fixture interact with connections:

* logQueries()
* schemaCollection()->listTables() - This should be abstracted to something like `availableCollections()`.
* configName()
* config()
* logger()
* beginTransaction()
* disableForeignKeys()
* enableForeignKeys()
* transactional()

I'm sure there are other implicit dependencies and more importantly methods we want in the interface that are not in the above list.

I think these interfaces can be introduced in a backwards compatible way and am proposing these interfaces be part of 3.1.

## TODO

* [x] Create interface for fixtures. #6321 
* [ ] Create interface for connections and refactor fixture code.

**Comment by lorenzo** [comment]
Looks good to me

**Comment by markstory** [comment]
I'll start with adding the fixture interface. The connection one I think could still be refined. Having sql methods in an abstract interface still feels funny/wrong.

**Comment by lorenzo** [comment]
Yeah, I agree

**Comment by markstory** [comment]
Closing as a pull request for the connection interface is up now.
