### ISSUE TITLE
3.0 "'id' in where clause is ambiguous" error when using findById()

### ISSUE THREAD

**Issue by PGBI** [cakephp/cakephp#6295]
Let's say Posts belongs to Users and that both tables have an id column.

`$postsTable->findById('some id')->contain('Users')->first()` will throw the following error:
`Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous`

I guess this is because `findById('some id')` acts like `where(['id' => 'some id'])` and not like `where(['Posts.id' => 'some id'])`

**Comment by PGBI** [comment]
My bad, I just saw in the documentation : "Other query options like contain are also not supported with dynamic finders".

**Comment by PGBI** [comment]
Quick question: is it because of this error only ("xxx in where clause is ambiguous") that dynamic finders are not compatible with contain()?
Cause if it's the case, I can have a look at it and propose a PR. Just let me know.

**Comment by markstory** [comment]
The documentation was more regarding the options array, not that you couldn't chain a contain() call off of the generated query object (which should be possible). Sounds like we are just missing an table alias step.

**Comment by PGBI** [comment]
Yes I had come to the same conclusion. I can work on a PR to fix this and add a relevant test case for this scenario.

**Comment by dereuromark** [comment]
Closing as a PR is now open.
