### ISSUE TITLE
Error $this->fetch('title'); in default.ctp

### ISSUE THREAD

**Issue by fixounet** [cakephp/cakephp#6296]
Hello,

In version 2.6.3, default.ctp file, line 26 ... it says this :

```php
<?php echo $this->fetch('title'); ?>
```

However, when I do this from a controller :

```php
public function index() {
   $this->set('title', 'my title');
}
```
This does not work.

Must be replaced

```php
<?php echo $this->fetch('title'); ?>
```

by

```php
<?php echo $title; ?>
```

In default.ctp file.

In addition, the documentation is erroneous.

Bye.

**Comment by markstory** [comment]
The docs are not wrong, the default layout is fetching a [block](http://book.cakephp.org/2.0/en/views.html#using-view-blocks) while you are using a view variable. By using a block you can leave setting the page title as a view concern and omit it from your controller. In your view you can use 

```php
$this->assign('title', 'My awesome app');
```

To make the default fetch() work.

**Comment by fixounet** [comment]
If you try, there will be an error.

So the documentation is unclear, as it says to use the $this->set() and not $this->assign()

**Comment by markstory** [comment]
Where are the docs wrong?

**Comment by fixounet** [comment]
In the literature, it is stated that:

```
The $title_for_layout is deprecated as of 2.5, use $this->fetch('title') in your layout and $this->assign('title', 'page title') instead.
```

However , a little further, it says this:

```
$this->set('title_for_layout', $titleContent);
```

This implies that it is still possible to use both solutions. For me it is not clear .

Perhaps there should be in blocks identified codes that are valid for a particular release.

**Comment by markstory** [comment]
@fixounet Both approaches still work. `title_for_layout` used to be a magic view variable in earlier versions of 2.x. This view variable has been deprecated, and instead we _recommend_ you use blocks. However, if you want to use view variables you still can.

I can update the documentation so it doesn't mention the view variables for page titles.

**Comment by fixounet** [comment]
However, we do agree, it's not possible to make a $ this-> assign (...) from the controller. Only from the view ?

For documentation another solution would be to display tabs depending on the version. See example :

![capture d ecran 2015-04-09 a 14 30 15](https://cloud.githubusercontent.com/assets/3490680/7066681/4b91a782-dec5-11e4-95a4-de1e6fba0ee1.png)

**Comment by markstory** [comment]
@fixounet Tabs for the various versions could work if the docs were close to the same, unfortunately large parts of the documentation are not remotely close between the version.

You are right though, there is no way to assign a block from the controller. The page title is generally a view concern and really makes little sense in your controller if you are providing both an API and HTML interface.
