### ISSUE TITLE
Related to - Loading fixtures from plugin #3318

### ISSUE THREAD

**Issue by netusco** [cakephp/cakephp#6303]
Cake loads fixtures from plugins using
public $fixtures = [ 'plugin.pluginName.myTable']

to: pluginName\Test\Fixture\pluginNameFixture
instead of: pluginName\Tests\Fixture\pluginNameFixture

Following the basic plugin structure of the documentation http://book.cakephp.org/3.0/en/plugins.html the folder Tests is plural so the external loading of fixtures from a plugin should be looking at Tests folder plural instead of Test singular, or we should change the documentation. Isn't it?

**Comment by dakota** [comment]
The documentation is correct in this case. The folder structure is `tests` folder (Lowercase, plural), however the namespace is `pluginName\Test\`. The fixture loader looks for the a class with FQN of `pluginName\Test\Fixture\pluginNameFixture`, which is autoloaded (by composer, or the build in plugin autoloader) to `plugins\PluginName\tests\Fixture\pluginNameFixture`

**Comment by netusco** [comment]
ok then in my case the namespace was the problem and I was mislead by the error message of the phpunit I guess:
Exception: Referenced fixture class "PhotoCrop\Test\Fixture\PhotocropsFixture" not found.
thanks!
