### ISSUE TITLE
FormHelper::select interprets default as index instead of value

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#6305]
Suppose I render a select input like this:

	echo $this->Form->input('category', [
		'type' => 'select',
		'multiple' => 'multiple',
		'options' => [
			['value' => 1, 'text' => 'Option 1'],
			['value' => 4, 'text' => 'Option 4'],
			['value' => 3, 'text' => 'Option 3'],
			['value' => 2, 'text' => 'Option 2']
		],
		'default' => [1, 2]
	]);

This produces the following output:

	<div class="input select">
		<label for="category">Category</label>
		<input type="hidden" name="category" value="">
		<select name="category[]" multiple="multiple" id="category">
			<option value="1">Option 1</option>
			<option value="4" selected="selected">Option 4</option>
			<option value="3" selected="selected">Option 3</option>
			<option value="2">Option 2</option>
		</select>
	</div>

The value-option-pairs are correct, but the selected options are not. I intended to mark Option 1 and Option 2 as selected, but the Options 3 and 4 are selected instead, as they have the index 1 and 2.

**Comment by ADmad** [comment]
The `options` is supposed to be an associative array like:
```
[
  1 => 'opt 1',
  2 => 'opt 2'
]
```
