### ISSUE TITLE
3.0.x - PDO::__construct(): MySQL server has gone away

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6307]
Hi guys, this is a weird one. I made an app and dev'd it in 5.6.2. Everything was fine. When I deployed it live it went onto a box with 5.6.7 on it. Suddenly I kept seeing:
```
WARNING (2): PDO::__CONSTRUCT(): MYSQL SERVER HAS GONE AWAY [CORE/SRC/DATABASE/DRIVER/PDODRIVERTRAIT.PHP, LINE 48]
``` 

Trace:
```
2015-04-09 15:16:58 Warning: Warning (2): PDO::__construct(): MySQL server has gone away in [APP/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 138
PDO::__construct() - [internal], line ??
Cake\Database\Driver\Mysql::_connect() - CORE/src/Database/Driver/PDODriverTrait.php, line 48
Cake\Database\Driver\Mysql::connect() - CORE/src/Database/Driver/Mysql.php, line 86
Cake\Database\Schema\BaseSchema::__construct() - CORE/src/Database/Schema/BaseSchema.php, line 46
Cake\Database\Driver\Mysql::schemaDialect() - CORE/src/Database/Dialect/MysqlDialectTrait.php, line 62
Cake\Database\Schema\Collection::__construct() - CORE/src/Database/Schema/Collection.php, line 52
Cake\Database\Schema\CachedCollection::__construct() - CORE/src/Database/Schema/CachedCollection.php, line 44
Cake\Database\Connection::schemaCollection() - CORE/src/Database/Connection.php, line 319
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 424
Cake\ORM\Query::addDefaultTypes() - CORE/src/ORM/Query.php, line 141
Cake\ORM\Query::__construct() - CORE/src/ORM/Query.php, line 123
Cake\ORM\Table::query() - CORE/src/ORM/Table.php, line 1147
Cake\ORM\Table::find() - CORE/src/ORM/Table.php, line 882
App\Controller\VideosController::getVideos() - APP/Controller/VideosController.php, line 95
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 404
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
require - /Users/pconroy/Work/DAL/cake/start.php, line 34
[main] - ROOT/webroot/index.php, line 6
```

It happens whenever I use any queries, even really really simple ones. I thought it was just the server since I hadn't seen it locally. Then, today, I updated my MAMP to use 5.6.7. And the same error showed up for the first time. We spent a few days trying to debug the code when we saw the error live and the only way that seemed to fix it was setting `persistent=false` in the datasource configs, it *was* `persistent=true`.

1. If any of you are able to use 5.6.7 can you see if this error happens for you in any test apps?
2. It's very hit or miss. It happens if the schema is cached or if it's not cached.
3. We tried to look into PDO changes between 5.6.2 and 5.6.7 but didn't see anything glaring.
4. Changing MAMP back to 5.6.2 also fixes the problem.
5. I'm using MySQL 5.6.21 locally.

Let me know if you need more info and I'll try to get it.
Thanks

**Comment by patrickconroy** [comment]
I should have also mentioned.. this doesn't actually break anything. The queries always work and I always get my data. It's just in the error log, or on screen if `debug=1`.

**Comment by markstory** [comment]
Sounds like your MySQL connection is timing out. Have you checked the client timeouts in MySQL?

**Comment by patrickconroy** [comment]
Yeah my timeouts are pretty standard, and this error happens after the connection is done. It seems elusive but my 3.0 app is pretty simple. There's a call to a json file, which does a single query, and that query always works but sometimes before it runs I get this error. Turning off persistent connections fixes it, but it seems strange that I'd have to do that? Maybe it's a strange PDO bug, it's happening in 3 completely separate environments.

**Comment by markstory** [comment]
I bet the persistent connections are timing out across many requests.

**Comment by lorenzo** [comment]
@patrickconroy That would also happen if mysql decided to kill your connection before it completes. A common case a is query that is taking log time, or one that causes a deadlock and ends up being killed by the detection mechanism.

**Comment by lorenzo** [comment]
Closing as there seem to be no more activity here
