### ISSUE TITLE
Custom templates for button not works

### ISSUE THREAD

**Issue by salines** [cakephp/cakephp#6308]
Hello,

http://book.cakephp.org/3.0/en/views/helpers/form.html#list-of-templates

I make a form template and everything works except the button and submit.

my template
``` 
'button' => '<button {{attrs}}>{{text}}</button>',
'inputSubmit' => '<input {{type}} {{attrs}}>'
 ```
in my view:

```<?= $this->Form->button(__('Submit'),['templates' => 'Admin.admin_form']) ?>```

result:
```
<button templates="Admin.admin_form" type="submit">Submit</button>
or
<input type="submit" templates="Admin.admin_form" value="Submit">
```

**Comment by markstory** [comment]
Neither of those methods supports a templates option, which would explain the the templates property being added. You'll have to use the `templates()` method to modify the templates, or set the templates when creating the form until those methods support the templates option.

**Comment by jadb** [comment]
I don't think `templates` should be supported by all form elements' methods. One can use `input()` for that since single element methods (i.e. button) rely on only one template. 

If, like in this case, it's to be used (apparently) for admin forms, then configure the helper accordingly from the admin controllers to use that template for buttons by default.

**Comment by markstory** [comment]
I'm good with that option too @jadb It seems like you would end up with less duplication if you set the templates per form anyways.

**Comment by jadb** [comment]
Yup @markstory.

@salines, right now, already 3 options are available:

```php
// in the Controller
public function initialize()
{
    parent::initialize();
    if (!$this->_components->has('Form')) {
        $this->loadComponent('Form');
    }
    $this->Form->config(['templates' => 'Admin.admin_form']);
}

// or in the view,
// using the `FormHelper::create()`
$this->Form->create($entity, ['templates' => 'Admin.admin_form']);

// using the `FormHelper::input()`
$this->Form->input('Submit', ['type' => 'button', 'templates' => 'Admin.admin_form']);
```

Unless others think we should support `templates` for `button()`, `radio()`, etc.?

**Comment by salines** [comment]
Hi, thanks for your answers.

I prepare plugin that will help you quickly bake admin plugin, with high quality Bootstrap 3 Theme.

For this purpose, in baked Admin Plugin we will have a form template located in its own config folder. Developer will be able to from one place to change attributes, etc.

In a few days, when it's ready, I'll set up the plugin on github.

Thank You.

**Comment by markstory** [comment]
Given there are a few ways to accomplish this already, create(), templates(), input(), I'm going to close this as I don't think it will be very common to load new templates for single buttons.
