### ISSUE TITLE
A small typo is creating a duplicate entry in pot files

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#6312]
'An Internal Error Has Occurred'
'An Internal Error Has Occurred.' <--- notice the ending dot

**Comment by ADmad** [comment]
The pot file has comments stating the file and line number from which the strings are extracted. So can you please provide that info so that we don't need to dig into the code to find this?

**Comment by efanzini** [comment]
#: Error/ExceptionRenderer.php:227

i also found those places where the dot is missing.

Line 341 in vendor\cakephp\cakephp\tests\TestCase\Error\ErrorHandlerTest.php
Line 463 in vendor\cakephp\cakephp\tests\TestCase\Error\ExceptionRendererTest.php
Line 17 in vendor\cakephp\cakephp\tests\test_app\TestApp\Template\Error\error500.ctp

**Comment by ADmad** [comment]
Since there's only one location where dot is used i would rather change that :)  Would you like to make a pull request to fix it?

**Comment by efanzini** [comment]
All the other statements are ending with a dot, i'll prefer to add it where it's missing :)

**Comment by ADmad** [comment]
Okay :)
