### ISSUE TITLE
Again, BTM _joinTable id problem

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#6315]
Well I am trying to save a belongsToMany relation between two tables, specifying the primaryKeys in the data I want to save for both models: source and target.
The two foreignKey of the "middle" table are the composite primaryKey too. So no autonumeric primaryKey.

But it does not save anything apart of the source model. This is because in``\vendor\cakephp\cakephp\src\ORM\Marshaller.php`` it is assuming that if the primaryKey in the target model is specified, the entity already exists in the table.
```php
// Accept [ [id => 1], [id = 2] ] style.
        $primaryKey = array_flip($assoc->target()->schema()->primaryKey());
        if (array_intersect_key($primaryKey, current($data)) === $primaryKey) {
            $primaryCount = count($primaryKey);
            $query = $assoc->find();
            foreach ($data as $row) {
                $keys = array_intersect_key($row, $primaryKey);
                if (count($keys) === $primaryCount) {
                    $query->orWhere($keys);
                }
            }
            $records = $query->toArray();
        } else {
            $records = $this->many($data, $options);
        }
```

I could imagine a possible solution would be to add an autonumeric primary key to the middle table and set the currently composite primaryKey to be only foreignKeys, but I prefer to not create an extra field here.

I tried the version of the file 3.0.0-RC1 and it works because the code commented above was included later. Is possible to have this in mind?

**Comment by markstory** [comment]
What does your form data look like? You can totally use joint tables that do not have autoincrement id columns.

**Comment by Tzaoh** [comment]
Data:
```PHP
        $data = [
            [
                'summonerId' => 1,
                'name' => 'Tzaoh',
                'games' => [
                    [
                        'gameId' => 1,
                        'gameMode' => 'WHATEVER_1x1',
                        '_joinData' => [
                            'teamId' => 200
                        ]
                    ]
                ]
            ],
            [
                'summonerId' => 2,
                'name' => 'Berto',
                'games' => [
                    [
                        'gameId' => 1,
                        'gameMode' => 'WHATEVER_1x1',
                        '_joinData' => [
                            'teamId' => 100
                        ]
                    ]
                ]
            ]
        ];
```

Models:
https://gist.github.com/Tzaoh/c27db0cef35475b17e29

**Comment by markstory** [comment]
Shouldn't `gameMode` be inside `_joinData`?

**Comment by Tzaoh** [comment]
No, it is an atribute from the game and there is a field with that name in "games__" table

**Comment by markstory** [comment]
Your changes break a few tests that were added to fix regressions/add functionality in earlier releases. See #6097 and #6261.  From what it looks like you are using newEntity() to update entities. This was never supposed to be a feature of newEntity(), have you tried using patchEntity() instead?

**Comment by Tzaoh** [comment]
Well I am a bit lost right now :) first of all [here](https://gist.github.com/Tzaoh/5a3f2a5384e6419e42a8) how I am trying to save.
The fact is that I am trying to create a new record in the DB with a specified primaryKey. I guess I can do it with newEntity/newEntities functions right?

If the answer is "yes, you should do it that way", Marshaller is thinking I want to update a record, because I am specifying the primaryKey of the target. IMHO  this is checking in the ``Marshaller.php``
```PHP
# Do you have a primaryKey here?
if (array_intersect_key($primaryKey, current($data)) === $primaryKey) { 
    $primaryCount = count($primaryKey);
    $query = $assoc->find();
    foreach ($data as $row) {
       $keys = array_intersect_key($row, $primaryKey);
       if (count($keys) === $primaryCount) {
           $query->orWhere($keys);
       }
   }
   # this return an empty array because DB does not have any.
   $records = $query->toArray(); 
} else {
       $records = $this->many($data, $options);
}
```

Because ``$records`` is an empty array
```PHP
foreach ($records as $i => $record) {
    if (isset($data[$i]['_joinData'])) {
        $joinData = $jointMarshaller->one($data[$i]['_joinData'], $nested);
        $record->set('_joinData', $joinData);
    }
}
```
It is not calling ->one method to save the rest of the fields.
If you agree with that I can try to create little patch

**Comment by lorenzo** [comment]
@Tzaoh Specifying a primary key has been reserved for updating.... what is the reason you want to create new records with a specified primary key?

**Comment by Tzaoh** [comment]
hi @lorenzo 
Well, the rest of associations create new rows if the passed primaryKey does not exist.
So for me it is logic that this part can have the same behavior.

In my specific case, the data I save in my database is requested from a third-webservice and I can create an unique primary key (composite in this case) with two of the fields they send to me, instead of create a surrogate (I think that is the name) primary key without meaning.

I think is easy to merge both behaviors in the version i was testing (3.0.1) 

```PHP
// Accept [ [id => 1], [id = 2] ] style.
$primaryKey = array_flip($assoc->target()->schema()->primaryKey());
if (array_intersect_key($primaryKey, current($data)) === $primaryKey) {
    $primaryCount = count($primaryKey);
    $query = $assoc->find();
    foreach ($data as $row) {
        $keys = array_intersect_key($row, $primaryKey);
        if (count($keys) === $primaryCount) {
            $query->orWhere($keys);
        }
    }
    $records = $query->toArray();
}# else {
#    $records = $this->many($data, $options);
#}

if (empty($records))){
    $records = $this->many($data, $options);
}
```

but not so easy in the following ones.

**Comment by lorenzo** [comment]
@Tzaoh One of the reasons is that it would entirely break how SQL Server work, and since we support that database driver I'd rather not change it. Databases are good at generating ids for you... why do you need to do it yourself?

**Comment by Tzaoh** [comment]
@lorenzo 
Sorry but I do not see your point.
The behavior of creating a new row if an ID is sent in the data and it does not exists in the database is already "included" in Cake associations.

So in any case, the question should be, Why can I do in hasMany association and not in BTM?

Why does it breaks how SQL Server work? If that were the case, SQL servers would force us to use AI keys when they were integer types.

Yes databases can create IDs automatically for me but the fact is that I dont need them because I already have fields which grants me each record will be unique. The webservice is returning me its primary keys (which have bussiness logic/meaning too) and I wish to use them instead of wasting space in my server with an unnecesary field.

**Comment by lorenzo** [comment]
@Tzaoh Inserting a row with a given id when the row is auto incremental cannot be done in SQL Server without a lot of hackery.

**Comment by Tzaoh** [comment]
Not my case, the three models I attached at the beginning dont have AI primary keys. All of them are provided from the webservice. Games, Summoners and SummonersGames

**Comment by Tzaoh** [comment]
Does any decision being taken about this?

**Comment by lorenzo** [comment]
@Tzaoh If you want to provide a patch for making this work it would be greatly appreciated!

**Comment by Tzaoh** [comment]
Just to my knowledge, once I have my modification done, I guess I should download the official test cases? how should i run them? i guess you will redirect me to a getting started testing web page

**Comment by lorenzo** [comment]
after you clone the cakephp repo, and run `composer install` you can just execute `vendor/bin/phpunit`

**Comment by kaffee-kocher** [comment]
I had the same bug and i solved it with this snippet:

foreach ($primaryKey as $key => $value) {
            if ($entity->dirty($key)) {
                $primaryKey[$key] = $entity->getOriginal($key);
            }
        }

Insert this code after line 1513 in the file /vendor/cakephp/cakephp/src/ORM/Table.php (after line $primaryKey = $entity->extract($primaryColumns);) 
I hope it can help you.

**Comment by kaffee-kocher** [comment]
I had the same bug and i solved it with this snippet:

       foreach ($primaryKey as $key => $value) {
            if ($entity->dirty($key)) {
                $primaryKey[$key] = $entity->getOriginal($key);
            }
        }

Insert this code after line 1513 in the file /vendor/cakephp/cakephp/src/ORM/Table.php (after line $primaryKey = $entity->extract($primaryColumns);) 

And you must delete/comment out the following lines:
        $data = array_diff_key($data, $primaryKey);
        if (empty($data)) {
            return $entity;
        }


I hope it can help you.

**Comment by Tzaoh** [comment]
Hi @lorenzo . I am having a hard time trying to code what I want so I will try to explain while pasting the small pieces of code I am testing. Of course this will far disoptimized. It is just to ilustrate my case.

So. I am in in a N:N (belongsToMany) relation. The relation is between: Champion and Tag.
The tables about them are already created.

Now in my database I have one tag saved and associated with a champion. Like this:
![initialtablesstates](https://cloud.githubusercontent.com/assets/5722357/8192994/26e7212c-1472-11e5-9459-df8f634d62f4.png)

The data I mocked is this: 
https://gist.githubusercontent.com/Tzaoh/18b94d2a8c5340519742/raw/afa22c41c2be1ebdd0a135035c0254e2b58b7b45/mockChampion

Now I am trying to save the same structure but with one more tag. So now i will have
https://gist.github.com/Tzaoh/31acc1fe89d77af737d6

Because of the behavior of CakePHP, 2 new rows will be created in the tags table. I would like that CakePHP look into the table the values of $data and IF they exist update the data like this:

![img2](https://cloud.githubusercontent.com/assets/5722357/8193172/80456ebc-1473-11e5-8c75-10bec107dfef.png)

To accomplish that I have to filter by ['name' => 'Support'].

In Marshaller.php. _belongsToMany() function
```PHP
.
.
.
if ($hasIds) {
    return [];
}
$data = array_values($data);

// $data = [
//    ['name' => 'Support'],
//    ['name' => 'Fighter']
//];
$primaryKey = $assoc->target()->schema()->primaryKey();
$filter = new TupleComparison(array_keys(current($data)), array_values($data), [], 'IN');
$array_entities = $assoc->target()->find()->where($filter)->toArray();
```

at this point $array_entities will contain the Tags that exists in DB.
(
    [0] => Cake\ORM\Entity Object
        (
            [properties] => [
                    [id] => 1
                    [name] => Support
            ]
            .
            .
            .
            [repository] => Tags
        )
)

Now I should intersect the entiti(es) with the $data array, but I am a bit stuck here because of having to have in mind composite keys and probably other stuff I hadnt even considered. How can I continue?

I hope I was enough clear and thanks in advanced @lorenzo

**Comment by markstory** [comment]
How is CakePHP supposed to know how to filter the tags? The `name => Support` data isn't enough for the marshaller to resolve the correct tag 100% of the time. In more complex scenarios unless you give the primary key value to the tags table it is impossible for the ORM to find an existing record without ambiguity. This is why it defaults to creating new records when there isn't primary key.

**Comment by Tzaoh** [comment]
Hi @markstory,

I think I understood your explanation, but could be possible to give me an example of it?

What do you think about creating a new record in Tags, specifying an ID (primaryKey) ?

**Comment by markstory** [comment]
Sure, in your example `name` is not a unique field, so there very well could be multiple tags with the same name. The same situation is true for tables with multiple columns. Imagine a customers table, the belongsToMany data contains only first name and last name. The marshaller cannot assume there is only one `Jane Smith` in the app, and creates a new one.

We cannot support creating new records with pre-determined primary key values as SQLServer and Postgres do not support this in their implementation of 'auto increment'.

**Comment by mylux** [comment]
Is there any development being made in this topic? I am also not so sure if everybody is agreeing with what was proposed.
If I understood correctly,I am totally in favor of having the possibility of not having a mandatory id field in joint tables, once you are able to specify th real primary key there inside (the too foreign keys are able to identify each record).

**Comment by markstory** [comment]
> If I understood correctly,I am totally in favor of having the possibility of not having a mandatory id field in joint tables, once you are able to specify th real primary key there inside (the too foreign keys are able to identify each record).

@mylux You can already have junction tables without a synthetic primary key.

The last few updates on this post were aiming to have the ORM resolve records on non-unique columns, or specify autoincrement values, both of which we cannot support.

**Comment by mylux** [comment]
Ah, OK. That's why I've got a bit lost. Thanks @markstory
About this subject (non unique columns) I don't have a good feeling about this. If the Marshaller becomes so "smart", the possibility of unexpected behavior increases. And its maintenance can become really painful.

**Comment by markstory** [comment]
I too, don't want the marshaller being too smart.

**Comment by Tzaoh** [comment]
oh forgot to close the topic as far as you answer it. Thanks btw
