### ISSUE TITLE
afterFind not working with recursive level 2  ( 2.x)

### ISSUE THREAD

**Issue by yogeshsaroya** [cakephp/cakephp#6316]
sse with aterFind.

current code for User model >>

```php
public function afterFind($results, $primary = false) {
        foreach ($results as $key => $val) {
            if (isset($val['User']['country_code']) && isset($val['User']['mobile'])) {
                $results[$key]['User']['mobile'] = trim($val['User']['country_code']).trim($val['User']['mobile']);}
        }
        return $results;
    }
```

it working with "User->find".

but not working with other model. i have 3 model.

Room,Place,User.

```
$this->Place->bindModel(array('belongsTo' => array('User')));
$this->Room->bindModel(array('belongsTo' => array('Place')));  (with ,false also )
```

when i try to find room data >

```
$data = $this->Room->find('first');

array (
[Room]>array()
[Place]>array(
 [User]=>array(
[mobile] => /* here after find not working it should content country code + mobile */
)
)

)
```

Please help

**Comment by markstory** [comment]
After find callbacks are not fired for related models. This is a limitation of the 2.x model layer, and one of the many reasons we rebuilt the ORM for 3.x. The only solutions to this are workarounds where your primary model's afterFind can call methods on associated models.
