### ISSUE TITLE
FormHelper Customized Templates - checkboxFormGroup

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#6318]
checkboxFormGroup is generating a Notice for {{input}} -> Notice (8): Array to string conversion [CORE\src\View\StringTemplate.php, line 216]

My code attached...
![formhelper customized templates - checkboxformgroup](https://cloud.githubusercontent.com/assets/11887260/7101269/5c066e54-e06e-11e4-94dc-66f4c10b8adc.png)

Secondly, there is no way to customize the label of the checkbox. Any possibility for that?

**Comment by gauravmak** [comment]
Ohh, sorry. I did not know HTML wont work here.. Attaching the screenshot of the code..
![formhelper customized templates - checkboxformgroup](https://cloud.githubusercontent.com/assets/11887260/7101263/03943ee0-e06e-11e4-940e-a176fdea0bb3.png)
.

**Comment by ADmad** [comment]
For checkbox the input gets nested inside the label so you shouldn't have `{{input}}` placeholder in your `checkboxFromGroup` template.

Seems you are trying to customize the templates for bootstrap. I would suggest using the [Bootstrap UI](https://github.com/friendsofcake/bootstrap-ui) plugin.

**Comment by gauravmak** [comment]
Thank you @ADmad,

The doc needs an update then I guees - http://book.cakephp.org/3.0/en/views/helpers/form.html#list-of-templates

Yes am using bootsrap, but I already have a template which I need to integrate with the app.
I will wait for the update to be able to customize the checkbox label then.
It is already doing 2 jobs though - Adding hidden element and the checkbox input.

**Comment by ADmad** [comment]
For checkboxes by default the ``nestingLabel`` template is used. It currently not listed on the manual page you link but I have opened a PR to fix it.

If you don't want the the checkbox input to be nested inside the label set the option `nestedInput` to `false` when using `FormHelper->input()`.

**Comment by gauravmak** [comment]
Thanks man. perfect.
I meant to say the checkboxFormGroup options on the link should be updated not to include {{input}}, right?

checkboxWrapper doesn't seem to be anything. Is that so?

When we use Form->input, the div with the class input and input type (file, text, checkbox, etc.) is inevitable, correct? Need to go for specific type of option? - http://book.cakephp.org/3.0/en/views/helpers/form.html#generating-specific-types-of-inputs

**Comment by ADmad** [comment]
> I meant to say the checkboxFormGroup options on the link should be updated not to include {{input}}, right?

I have fixed `checkboxFormGroup` template.

> checkboxWrapper doesn't seem to be anything. Is that so?

By default it does a wrapper div.

> Need to go for specific type of option to avoid that top div?

No, you can customize the `inputContainer` template using `templates` option for the `Form->input()` call and remove the wrapping div.

**Comment by zkalinic** [comment]
It looks like FormHelper->input() or FormHelper->checkbox() are not using checkboxWrapper.
Is it implemented at all?

**Comment by markstory** [comment]
@zkalinic It is in use [see right here](https://github.com/cakephp/cakephp/blob/master/src/View/Widget/MultiCheckboxWidget.php#L207-L211)

**Comment by zkalinic** [comment]
Thanks markstory for pointing out where it is in use, but can you give me an example how to use it?

Just FormHelper->checkbox() or FormHelper->input(['type' => 'checkbox']) doesn't render checkboxWrapper...

**Comment by markstory** [comment]
You need to be making a multipleCheckbox so `Form->input('things', ['type' => 'checkbox', 'multiple' => true]);`
