### ISSUE TITLE
3.0 - patchEntity ignores accessibleFields setting

### ISSUE THREAD

**Issue by brabeji** [cakephp/cakephp#6320]
Hello,
I just noticed unexpected behavior (using dev-master). Assuming Posts belongsTo Category - I am trying to patchEntity of (actual entity class debug data stripped for brevity)
```
$post = [
  'title' => 'foo title',
  'category' => [
    'id' => 1,
    'title' => 'cat 1 title'
  ]
]
```
with
```
$post = [
  'title' => 'foo title edited',
  'category' => [
    'id' => 2
  ]
]
```
there are two different results depending on where accessibility of category id is declared:

in Category entity
```
$post = [
  'title' => 'foo title edited',
  'category' => [
    'id' => 2,
    'title' => 'cat title 1' // this is wierd, actually title of cat 1
  ]
]
```
or by `['associated' => ['Category' => ['accessibleFields => ['id' => true]]]` passed to patchEntity
```
$post = [
  'title' => 'foo title edited',
  'category' => [ // not changed at all
    'id' => 1,
    'title' => 'cat title 1'
  ]
]
```

**Comment by markstory** [comment]
In the patch operation are you trying to connect the post with a new category, and also update the category properties?

**Comment by brabeji** [comment]
No, I am passing only "id" field set to id of already existing category.

**Comment by markstory** [comment]
Why do the examples also include the title of the category? If you only need to link the post with a category why not just pass the `category_id` field?

**Comment by brabeji** [comment]
1. as they are results of the patchEntity. Only second code block is an actual array, the rest are meant to represent instances of entity so they include title.

2. I don't want to bother users of my api with foreign keys, they should post entities to create associations in the same form as they are getting them. It seems beautiful to me.

**Comment by markstory** [comment]
Those are fair points, I'll take a look into why the accessibleFields option isn't being forwarded properly.

**Comment by markstory** [comment]
On a more detailed look `patchEntity()` doesn't have an accessibleFields option. This would explain why the option isn't working as you're expecting. Perhaps you intended to use `fieldList`, or alternatively, you can set specific fields as accessible before patching your entities.

**Comment by brabeji** [comment]
Docs should be fixed here
https://github.com/cakephp/docs/blame/923cc3a2e15bb0c2b6e9f579717a29fd8c26b5b5/en/orm/saving-data.rst#L481

Also of course I did my own debugging prior to posting this issue so I know that `accessibleFields` does get propagated here:
https://github.com/cakephp/cakephp/blob/bdd170425cd4d2064372481e87c19a5c0e6c21c3/src/ORM/Marshaller.php#L113
and still have two different results as noted above. That might be a sign of deeper issue which I want to investigate as I have time to do so. Thank you for your effort!

**Comment by markstory** [comment]
I will update the docs.

The options do get propagated, but they are never used by merge()/mergeMany()
