### ISSUE TITLE
How I can extend view from regular View directory in my current theme?

### ISSUE THREAD

**Issue by K4T** [cakephp/cakephp#6322]
Hi! Let`s say I have following structure:

Regular view: /View/Layouts/default.ctp
Theme: /View/Themed/ThemeA/Layouts/default.ctp
Theme: /View/Themed/ThemeB/Layouts/default.ctp

In my themes I want to extend default.ctp from regular view but I can not.
When I try to do:

/View/Themed/ThemeA/Layouts/default.ctp
```php
$this->extend('/Layouts/default');
echo $this->fetch('content');
```

I will receive error "You cannot have views extend themselves.". And of course it is true. But how I can solve that problem? I really need to extend my regular views (not only layouts templates) in my themes because I don`t want to duplicate code. Is it possible?

What I am trying to do?
In my regular views I defined some blocks, for example:

View/Products/index.ctp
```php
...
   echo $this->fetch('theme_banner');
...
```

Now I want to fill that block, which is defined in regular view, with data from current THEME, but I can not because I can not extend that regular view. I tried this:

View/Themed/ThemeA/Products/index
```php
$this->extend('/Products/index');

$this->start('theme_banner');
    echo 'TEST';
$this->end();
```

Of course I will get error again. Any help, please?

Solution proposition:
Add some kind of flag to extend() method which allow developers to choose that they want to use view from reguler View directory or just from current theme.

**Comment by lorenzo** [comment]
Please don't post question in the issue tracker :)
