### ISSUE TITLE
cakephp 3.0 find('all')  can't find the Associations's field only

### ISSUE THREAD

**Issue by zx4357685** [cakephp/cakephp#6326]
Table1 belongsTo Table2

    $this->Table2s->find('all',['contain'=>['Table1s']])->select(['Table1s.name']);

if I only select Table1s' field the cake will say

    Undefined index: Table2s [CORE\src\ORM\ResultSet.php, line 476]

if I do like this

    $this->Table2s->find('all',['contain'=>['Table1s']])->select(['Table2s.id','Table1s.name']);

it will be success

could some one tell me how to do it  if I only want to find the Table1s.name

**Comment by dakota** [comment]
If you just want the name field from the Table1, then you should do a query only on table1:

```
$this->Table2s->Table1s->find('all')->select(['Table1s.name']);
```

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by zx4357685** [comment]
Thank you very much!

**Comment by biesbjerg** [comment]
Shouldn't the ORM check for the array key before attempting to access it to avoid undefined index warnings?

**Comment by markstory** [comment]
@biesbjerg It should. I'll reopen so someone can take a look at why the notice error was triggered.

**Comment by markstory** [comment]
Closing as a pull request to fix this was merged.
