### ISSUE TITLE
Misleading comment in /config/paths.app

### ISSUE THREAD

**Issue by miguelarcher** [cakephp/cakephp#6330]
Where the ROOT constant is defined the comment is still referencing the "App" folder from previous versions

/**
 * The full path to the directory which holds "App", WITHOUT a trailing DS.
 */
define('ROOT', dirname(__DIR__));

**Comment by miguelarcher** [comment]
Not sure if I'm posting this in the proper place as it's not exactly a bug. Let me know. I just found it to be confusing for people coming from previous versions.

**Comment by markstory** [comment]
Thanks?
