### ISSUE TITLE
Database Encoding seems to be ignored in 3.0

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#6332]
I am having trouble getting the database connection to work with the correct encoding. After some research and debugging, I think this could be a bug in cake, not in my code. Please correct me if I am wrong.

This is my debugging code:

	 use Cake\Datasource\ConnectionManager;
	
	$db = new mysqli('localhost', 'USERNAME', 'PASSWORD', 'DATABASE', null, '/tmp/mysql5.sock');
	$db->set_charset('utf8');
	
	#Output Listing 1
	debug($db->query("SELECT * FROM information WHERE id = 33")->fetch_row());
	
	#Output Listing 2
	debug(ConnectionManager::get('default')->execute("SELECT * FROM information WHERE id = 33")->fetchAll());
	
	
	ConnectionManager::get('default')->execute("SET NAMES utf8");
	
	#Output Listing 3
	debug(ConnectionManager::get('default')->execute("SELECT * FROM information WHERE id = 33")->fetchAll());

This is the used database configuration in config/app.php:

	[
		'className' => 'Cake\Database\Connection',
		'driver' => 'Cake\Database\Driver\Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'unix_socket' => '/tmp/mysql5.sock',
		
		'username' => 'USERNAME',
		'password' => 'PASSWORD',
		'database' => 'DATABASE',
		'encoding' => 'utf8',
		'timezone' => 'UTC',
		'cacheMetadata' => true,
		
		'quoteIdentifiers' => false,
	]

This is the output of the three debug calls:

	/src/Template/Contractors/display.ctp (line 12)
	[
		(int) 0 => '33',
		(int) 1 => '1',
		(int) 2 => '8',
		(int) 3 => 'Musterstraße 0, 12345 Musterstadt'
	]
	/src/Template/Contractors/display.ctp (line 15)
	[
		(int) 0 => [
			(int) 0 => '33',
			(int) 1 => '1',
			(int) 2 => '8',
			(int) 3 => 'Musterstra�e 0, 12345 Musterstadt'
		]
	]
	/src/Template/Contractors/display.ctp (line 21)
	[
		(int) 0 => [
			(int) 0 => '33',
			(int) 1 => '1',
			(int) 2 => '8',
			(int) 3 => 'Musterstraße 0, 12345 Musterstadt'
		]
	]

The problem here:

1. When I fetch the data from the database **without** Cake, the special chars are rendered correctly. This confirms that the content in the database, the charset of the database itself and of the output in the browser all is UTF-8.
2. When I fetch the same data using Cake, the special chars are not rendered correctly.
3. After manually setting the encoding on the Cake database connection, the special chars are rendered correctly again, which seems to confirm that the Cake connection was not set to UTF-8 before, although configured to be.

The same problem occurs when I regularly fetch my data through the Table class.

Is this a bug or am I doing it wrong?

**Comment by markstory** [comment]
It could be an issue with the unix_socket connection variant, I've used the TCP connection with encoding fine in the past. In any case it doesn't look like you are doing things wrong.

**Comment by markstory** [comment]
@advitum Could you try applying the changes in #6338 to your vendor/cakephp/cakephp and see if that resolves the issue you're having?
