### ISSUE TITLE
Post-install error setting permissions on tmp/ and log/ directories

### ISSUE THREAD

**Issue by s-d-p** [cakephp/cakephp#6335]
I don't recall this being an issue on my local environment, but when I pushed to circleci, the build was failing:

```
Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception
                                                            
  [ErrorException]                                              
  fileperms(): stat failed for /home/ubuntu/MyApp/logs  
                                                               
composer install --prefer-source --no-interaction returned exit code 1
```

I had to add:
```
tmp/empy
log/empty
```

and  `!empty` in my `.gitignore` file for it to work.

Not sure if this issue is specific to the `install` options circleci is using.

**Comment by markstory** [comment]
It might be as we use travis quite extensively for testing the app repo and it doesn't have the same permissions issues.
