### ISSUE TITLE
Stubbed Response objects in controller unit tests do not set their magic headers

### ISSUE THREAD

**Issue by jellehenkens** [cakephp/cakephp#6340]
Because [TestSuite/Stub/Response](https://github.com/cakephp/cakephp/blob/master/src/TestSuite/Stub/Response.php) overwrites the send(), methods like _setContentType never get executed.

This affects controller unit tests with false data. Content-Type for example never gets set if it got configured with Response->type().

**Comment by lorenzo** [comment]
Woah! welcome back @jellehenkens

**Comment by dereuromark** [comment]
@jellehenkens Baby steps :) I first got the status code fixed so far, but I agree, it would be nice if we could further get closer to the actual output. Maybe by not stubbing send(), but a submethod _send() which then does the actual sending then. So the other methods before this one will still be executed fine.

**Comment by jellehenkens** [comment]
Hehe, I kinda went off the grid in the open source community for a while. Let's catch up on irc some day :)

@dereuromark I was thinking something similar, refactor build into 2 methods, one that prepared magic stuff and a sub method that sends it. Then we can mock the sub method for testing.

**Comment by lorenzo** [comment]
We could just mock the `_sendContent` and `_sendHeader` methods

**Comment by jellehenkens** [comment]
We still have to mock send() though, we don't really want `fastcgi_finish_request` to happen within a unit test.

**Comment by lorenzo** [comment]
@jellehenkens The function will not be called in CLI

**Comment by markstory** [comment]
I can take a look at this.

**Comment by jellehenkens** [comment]
I found another somewhat related issue in the context of Controller unit testing.

I'm unable to mock the Request object to be a Basic authorization. I'm doing this:

```php
$this->configRequest([
    'headers' => [
        'Authorization' => 'Basic ' . base64_encode($username . ':' . $password)
    ],
    'environment' => [
        'PHP_AUTH_USER' => $username,
        'PHP_AUTH_PW' => $password
    ]
]);
```

and inside the `IntegrationTestCase::_buildRequest()` method the following logic prevents me from setting mocked environment variables in the Request object that gets passed to the dispatcher:

```php
$env = [];
if (isset($this->_request['headers'])) {
    foreach ($this->_request['headers'] as $k => $v) {
        $env['HTTP_' . str_replace('-', '_', strtoupper($k))] = $v;
    }
    unset($this->_request['headers']);
}
$env['REQUEST_METHOD'] = $method;
$props['environment'] = $env;
```

**Comment by markstory** [comment]
Closing as the issues detailed above both have pull requests now.
