### ISSUE TITLE
Cake 3.0 How to use deleteAll method

### ISSUE THREAD

**Issue by penndiatna** [cakephp/cakephp#6341]
Hello,
How to use deleteAll method to remove multiple ID from a table? 
$this->Model->deleteAll();

Thanks

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
