### ISSUE TITLE
$this->table in Table object not taking in consideration

### ISSUE THREAD

**Issue by anouarcharif** [cakephp/cakephp#6342]
Hi,

I was building a Plugin in cakephp3 until i found i problem with $this->table("my_table");

SQLSTATE[42S02]: Base table or view not found: 1146 "table" doesn't exist, even if i specify my_table in ModelsTable class ... so i think it's an issue ...

**Comment by dereuromark** [comment]
Where did you put this statement? Can you please paste your Table code?

**Comment by anouarcharif** [comment]
It's a plugin so here's my Table code:

namespace Media\Model\Table;

use Cake\ORM\Table;

class PicturesTable extends Table
{

    public function initialize(array $config)
    {
        $this->table('medias');
    }

}

**Comment by anouarcharif** [comment]
The following Table objects used Cake\ORM\Table instead of a concrete class:
Pictures

And of course i have PicturesTable.php under Model/Table and Picutre.php under Model/Entity

**Comment by dereuromark** [comment]
Sounds to me like you are using it wrongly. Maybe you forgot the plugin syntax when loading it?
Always use `PluginName.TableName` :)

**Comment by anouarcharif** [comment]
I load it like that in beforeFilter of my controller : 

$this->loadModel("Media.Pictures"); and i tried $this->loadModel("Pictures");

i get always the some error ... i will check what's going wrong ...

**Comment by anouarcharif** [comment]
It was a wrong call from the AppController of my app who was loading "Pictures" without "PluginName.TableName" ...

Thank you

**Comment by jhli** [comment]
Why isn't there a 'table class not found' error then?

**Comment by markstory** [comment]
@jhli There is, if you try to describe a table that doesn't exist an exception should be raised.

**Comment by jhli** [comment]
Then I wonder why @anouarcharif got an SQL error instead of that. But I did not see the whole code, I was just commenting cause I fell into some nice traps in 2.x where things weren't consistent with plugins and missing prefixes and exceptions/errors.
