### ISSUE TITLE
3.x adding new datasources?

### ISSUE THREAD

**Issue by chrisShick** [cakephp/cakephp#6352]
Are there any plans on adding more datasource type that will be native? Such datasources such as csv, etc. 

If not, where should I start my research to get ideas on how I would go about building my own? I couldn't find anything in the documentation.

**Comment by lorenzo** [comment]
We are currently working on a elastic search datasource https://github.com/cakephp/elastic-search

**Comment by markstory** [comment]
Building an ORM datasource for a CSV sounds like an abstraction mismatch. Are you looking for a way to wrap application domain logic around a CSV file?

**Comment by chrisShick** [comment]
@markstory isn't a csv file ultimately a database table, albeit comparatively inefficient? Following that logic, I just presumed that I could go about building a datasource that reads from it. A developer would be able to continue to do the basics of the QueryBuilder and fetch the results into an entity.

**Comment by markstory** [comment]
@chrisShick True, I guess you could implement a query builder and 'statement' for the CSV data. We've had to take a different approach with the elastic search plugin as elastic search doesn't fit many sql-isms well.
