### ISSUE TITLE
Problem accessing Configure in multiple elements

### ISSUE THREAD

**Issue by anouarcharif** [cakephp/cakephp#6354]
Hello,

When i try to access Configure class in element witch included in another one ... the class Configure not found is shown, here's a example:

// Elements/tables.ctp

use Cake\Core\Configure;
foreach ($tables as $table) {
      echo $this->element("path/to/element", ["var" => $table]);
 }

in "path/to/element" i access to Configure::read and it throw a exception "class not found", but when i bring that "use Cake\Core\Configure;" to the "path/to/element" it work fine ... so "include the file in  each iteration it's really not good" ... in perfet world only the "use Cake\Core\Configure;" in the controller must be enough ... now we need to put in every file ...

**Comment by jippi** [comment]
Thats PHP .. You need to `use` it in that element as well - its basic PHP stuff, unrelated to Cake

**Comment by anouarcharif** [comment]
Yes i know it's a PHP a stuff, but Cake have to make it as a global variable ... it's very weird to make a call for use Configure each time we need it ...
