### ISSUE TITLE
Is there a way to transform a button to a link in CakePHP?

### ISSUE THREAD

**Issue by vitorpre** [cakephp/cakephp#6358]
I am using cakephp and i'm trying to put a link on a button to show the glyphicon in this way:

 <?php echo $this->Html->link(__('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'), array('action' => 'view', $imovel['Imovel']['id'])); ?> 

but it shows this:

![image](https://cloud.githubusercontent.com/assets/8645639/7210296/122ddee4-e527-11e4-871d-476860185653.png)

Anyone knows how to solve this problem?

Ps: sorry for my bad english...

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
