### ISSUE TITLE
Warning in Router::scope('/', function ( Router $routes) { for type paramenter

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#6359]
Hi, because a warning is generated when defining the type parameter in Router ..? I should not give warnings.

In **CakePHP 3**:
```php
Router::scope('/', function ( Router $routes) {
```
**Print code:** http://s25.postimg.org/ph23y1svj/Print_de_pantalla_503.jpg

**Show Error:**
Print: http://s25.postimg.org/8ukjoyzxr/Print_de_pantalla_504.jpg

Yo I use it to autocomplete the code in PhpStorm, and is simpler to program and recall of internal methods CakePHP or any other framework.

**Comment by markstory** [comment]
Your typehint is incorrect. If you are going to use a typehint it should be `Cake\Routing\RouteBuilder` not Router.

**Comment by EOM** [comment]
Ok if successful in this way does not give me more warnings error.
Print: http://s25.postimg.org/9dgwq4tin/Print_de_pantalla_529.jpg

```
Router::scope('/', function (\Cake\Routing\RouteBuilder $routes) {
```

Ok if successful in this way does not give me more warnings Error
and PhpStorm working properly and respond well autocomplete.

One question, because in CakePHP not use such techniques for better result with the IDE standard manner, always detailing the type of data.

Greetings and thanks, and apologies for the false issus.
