### ISSUE TITLE
Writing a Cakephp 3 Polymorphic Media Behavior

### ISSUE THREAD

**Issue by whitep4nther** [cakephp/cakephp#6360]
Hi,

I'm currently trying to write a polymorphic Cakephp 3 Media Behavior, in order to attach any type of Media to any model entry and I'm having some issues on the way to go.

Code : 
[Media Behavior](http://pastebin.com/XgUD1uKV)
[MediasTable](http://pastebin.com/J1CYp6cQ)

What I'm currently doing : 
- Accepting a configuration arrays, each key = one field
- Adding file validation rules for fields in the buildValidator function of the behavior
- In the beforeSave callback, processing the entity : 
        - For each field in the behavior configuration, if the field is present on the entity : 
                - Creating new `Media` Entity (for `MediasTable`) entity with file information + model name
                - Uploading the file
                - Saving the entry to the `MediasTable` and returning the freshly created entity
                - Creating thumbnails if specified in the configuration
                - For each saved file (field can be multiples), we add the id to the field in the entity (in the end the `entity->{$field}` contains the array of added entry to the `MediasTable`

- In the afterSave callback, we check all the configurations field and if it is present, we update the corresponding entries in the `MediasTable` in order for them to correctly point back to the newly created entry

That way to do it allows me to simply upload files if present in the data, or update which Medias point to which entry if the field by specifying and id in the entity->{$field}.

But I do feel I don't do it the CakePHP way, or even the good way. I should probably create some type of object, entity to handle file uploads ?

Btw, I got an issue. In initialize function, I create association in order for data to be retrieved easily with contain(). But by doing so, when I upload a file, Cake thinks it's an association and converts the field to the corresponding association Class ! The entry still gets saved but I get this warning : 

![CakePHP Warning]
(http://image.noelshack.com/fichiers/2015/16/1429312426-screen-shot-2015-04-18-at-01-12-25.png)

In this example, I got and `ArtistsTable` with the `Media Behavior`. The Photo field is configured so then everytime the behavior sees the photo field on the entity, it tries to upload it.

Thanks a lot for the insights.

**Comment by markstory** [comment]
What does the field/association that triggers the above warnings look like? From the looks of that error/context you are putting association objects onto the request data/entity which sounds odd.

**Comment by whitep4nther** [comment]
Theses are like "virtual associations" I set up in the behavior for convenience. As the association has the same name than the property I'm trying to handle (upload), I think this is causing the problem.
I set up the association here : 
```
      foreach($this->_config as $field => $c)
            if ($c['unique'] === true)
                $this->_table->hasOne(Inflector::camelize($field), [
                    'className' => 'Media.Medias',
                    'foreignKey' => 'model_id',
                    'conditions' => ['model' => $this->_table->alias(), 'field' => $field],
                ]);
            else
                $this->_table->hasMany(Inflector::camelize($field), [
                    'className' => 'Media.Medias',
                    'foreignKey' => 'model_id',
                    'conditions' => ['model' => $this->_table->alias(), 'field' => $field],
                ]);
```
And then I later use the field of the same name of the association. I don't think that's an issue at all but I couldn't figure out someone to help me out on this, cause I'm clearly doing something wrong in building this behavior. All was working perfectly before I set up the associations, but I clearly need them.

**Comment by lorenzo** [comment]
@whitep4nther have you looked at how the Translate behavior implements the polymorphism?

**Comment by whitep4nther** [comment]
Had a look, Went over this. Thanks.
