### ISSUE TITLE
JsonView::_serialize serializes numbers as strings

### ISSUE THREAD

**Issue by Cameri** [cakephp/cakephp#6365]
JsonView::_serialize() serializes numbers as strings instead of numbers.
This can be fixed by OR'ing the current flags passed to json_encode() with JSON_NUMERIC_CHECK.

**Comment by jrbasso** [comment]
This only happens if your numbers are string variables on PHP. Can you tell from where the data is coming from? Directly from a Model::find? Which version of CakePHP are you using?

**Comment by Cameri** [comment]
Yes, data is coming directly from a Model::find(). I am using CakePHP 2.6.
    public function view($name) {
        $player = $this->Player->findByName($name);
        $this->set('player', $player);
        $this->set('_serialize' => [ 'player' ]);
    }
The table fields are numeric (either integers or floats), not text/varchar holding numbers. However, a var_dump() shows that Model::find() returns only strings for numeric fields.

**Comment by markstory** [comment]
If this is in 2.x, all model data comes back as stringy data. This is mostly a limitation in how PDO works across the various databases we support from what I remember.

**Comment by ADmad** [comment]
Yes this is a limitation of PDO.

@Cameri I suggest you checkout the [Crud](https://github.com/FriendsOfCake/crud/tree/3.0) plugin. It has [ApiTransformationListener](https://github.com/FriendsOfCake/crud/blob/3.0/Controller/Crud/Listener/ApiTransformationListener.php) which casts numeric string to integer for serialization.

**Comment by markstory** [comment]
Closing. Due to limitations in PDO this cannot be easily fixed. If you need the correct types, I suggest using afterFind callbacks to cast result sets accordingly. For 3.0 we've include automatic type casting as part of the ORM.

**Comment by carlezzo** [comment]
The same here, the response number are strings, any suggestion?
 ```
            $stm = "select * from clients";
            $response = $conn->execute($stm)->fetchAll('assoc');
            $this->set([
                'success' => $success,
                'code' => $code,
                'response' => $response,
                'errors' => $errors,
                '_serialize' => ['success', 'code', 'response', 'errors'],
            ]);
```
