### ISSUE TITLE
String offset cast occurred in I18n.php

### ISSUE THREAD

**Issue by ava007** [cakephp/cakephp#6377]
After upgrading from CakePHP 2.5.4 to 2.6.4 the following error messages appears iteratively:

String offset cast occurred in [/usr/local/www/locavores.co/www242/dev/lib/Cake/I18n/I18n.php, line 261]
Trace:
I18n::translate() - CORE/Cake/I18n/I18n.php, line 261
__ - CORE/Cake/basics.php, line 587
include - APP/View/Elements/footer2015a_default.ctp, line 31
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::_renderElement() - CORE/Cake/View/View.php, line 1217
View::element() - CORE/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 194
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

Calling line 31 in footer2015a_default.ctp is:
<?php echo __('Register a farmshop, farmstand or farmers market') ?>

PHP 5.5.23

Thank for helping

**Comment by markstory** [comment]
How could someone reproduce this issue? What do your po files look like?

**Comment by ava007** [comment]
../Locale/eng/LC_MESSAGES\default.po starts with this content:

msgid "Image upload"
msgstr ""
msgid "Validation Error"
msgstr ""
msgid "Use the following link to login for updating your information"
msgstr ""

**Comment by ava007** [comment]
../Locale/deu/LC_MESSAGE/default.po starts with this content:

msgid "Title of the Image"
msgstr "Titel des Bildes"
msgid "Products"
msgstr "Produkte"
msgid "Please select a Country"
msgstr "Bitte wählen Sie ein Land aus."

**Comment by markstory** [comment]
As part of the upgrade did you try clearing your application's cache files? PO files are serialized and the format likely changed between 2.5 and 2.6 as the context options were added.

**Comment by ava007** [comment]
clearing the cache files resolved this problem.   

Thank you Mark for your help!
