### ISSUE TITLE
In Cake\I18n\Time::timeAgoInWords the timezone option doesn't make any difference.

### ISSUE THREAD

**Issue by icaroscherma** [cakephp/cakephp#6388]
If I try to use the `` Cake\I18n\Time::timeAgoInWords`` and give the option ``timezone``, it will not make any difference in the end result.
Let's say that I have this scenario:

```
    // I created a Variable called $test_time, in the App configs, the default timezone is UTC
    $test_time = new Time('-1day');

    // Now I will use the timeAgoInWords function.
    // The "end" is only one minute so we can easily troubleshoot
    $test_time->timeAgoInWords([
        'timezone' => 'America/Vancouver',
        'end' => '+1minute',
        'format' => 'hh:mmaa dd-MM-YYYY'
    ]);
```
The variable is ``on 08:53PM 20-04-2015`` instead of ``on 01:53PM 20-04-2015``, so basically the timezone is useless. I also noticed inside the ``cakephp/src/I18n/Time.php`` that ``timezone`` property is not even being used... I expected something like:

```
    // Inserted in the line 274, before: $now = $from->format('U');
    if (isset($timezone)) {
        $from->timezone = $timezone;
    }
    // But since the calculation is based in seconds since the Unix Eppoch,
    // I'm not sure if the formula must be different.
```

Am I using it wrong or getting the wrong idea about the ``timezone`` option in this function or is it really not working?

EDIT:
Ahhh, I forgot to say, if I do something like:
```
    $test_time = new Time('-1day');
    $test_time->timezone = 'America/Vancouver';
    $test_time->timeAgoInWords([
        'end' => '+1minute',
        'format' => 'hh:mmaa dd-MM-YYYY'
    ]);
```
This works. So, why is not working if ``timezone`` is used inside the function?

**Comment by icaroscherma** [comment]
I was able to fix by adding the following code to the line ``274`` of the file ``cakephp/src/I18n/Time.php``:
```
        if ($timezone) {
            $this->timezone = $timezone;
        }

```
I will check another Time Functions to see if they have the same issue before making a pull request.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
