### ISSUE TITLE
Non application of unique rule on associated data during save 

### ISSUE THREAD

**Issue by aydot** [cakephp/cakephp#6390]
office_members table has fields: id, dealership_id, user_id, tag_identifier, created
users table has fields: id, first_name, last_name, created

dealership_members belongs to users
dealership_members belongs to dealerships

rules in the OfficeMembersTable:
```
public function buildRules(RulesChecker $rules)
{
    $rules->add($rules->isUnique(['dealership_id', 'user_id']));
    return $rules;
}
```
in my controller, I have
```
$officeMember = $this->OfficeMembers->newEntity();

$data = ['tag_identifier' => 'ABC1234', 'dealership_id' => '2',
         'user' => ['first_name' => 'ay', 'last_name' => 'dot']
];
$officeMember = $this->OfficeMembers->patchEntity($clubMember, $data, ['associated' => ['Users']]);
$officeMember->user->id = '3';//valid id

$this->OfficeMembers->save($officeMember);
```
- if I had existing dealership_id and user_id in the office_members table, I expect the save call to fail due to the isUnique rule in my OfficeMembersTable class. But the save call is successful, and it saves the already existing values(that are meant to be unique).
- If I set, ```$officeMember->user_id = '3';``` before calling save, I get the expected failure behavior.

If the first case is the expected behavior, I think the documentation should make it clear.

**Comment by markstory** [comment]
The first case is expected, as your unique constraint is on the columns in the `office_members` table. Setting `$officeMember->user->id` does not also populate `$officeMember->user_id`.

A pull request has been opened to clarify the docs. If you have a chance could you look at cakephp/docs#2659 and let me know if that would have helped you?

**Comment by aydot** [comment]
@markstory Thank you! that certainly would have helped.

**Comment by markstory** [comment]
Thanks for double checking the docs :+1:
