### ISSUE TITLE
UUID Fields with Binary(36) are not handled correct

### ISSUE THREAD

**Issue by beinbm** [cakephp/cakephp#6393]
I found two solutions. 
First I changed the type detection in MysqlSchema.php to match all binary 36 to UUID, which i dont like.
Second solution was to return unconverted strings in the BinaryType.php if they already match to a UUID.

I attached both patches
```
--- src/Database/Schema/MysqlSchema.php    (revision d77ffad6ee45aa0edf5d3b4bf8ed32f94d7ae5ce)
+++ src/Database/Schema/MysqlSchema.php    (revision )
@@ -110,6 +110,9 @@
         if ($col === 'char' && $length === 36) {
             return ['type' => 'uuid', 'length' => null];
         }
+        if ($col === 'binary' && $length === 36) {
+            return ['type' => 'uuid', 'length' => null];
+        }
         if ($col === 'char') {
             return ['type' => 'string', 'fixed' => true, 'length' => $length];
         }
```

```
--- src/Database/Type/BinaryType.php	(revision d77ffad6ee45aa0edf5d3b4bf8ed32f94d7ae5ce)
+++ src/Database/Type/BinaryType.php	(revision )
@@ -56,6 +56,10 @@
             return null;
         }
         if (is_string($value)) {
+            // return string if it matches to a uuid
+            if(preg_match('/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i', $value)) {
+                return $value;
+            }
             return fopen('data:text/plain;base64,' . base64_encode($value), 'rb');
         }
         if (is_resource($value)) {
```

**Comment by dereuromark** [comment]
I prefer the convention driven approach (the first), as it very well fits to the cake way, and its done this way for char(36) as well. It is also the fastest of all (performance wise).

**Comment by dereuromark** [comment]
At this point I also want to outline what I said before: We should default type `uuid` to binary for performance reasons in upcoming CakePHP releases, and better promote the binary type.

Currently the docs state
```
uuid
    Maps to the UUID type if a database provides one, otherwise this will
    generate a CHAR(36) field.
```

**Comment by lorenzo** [comment]
@beinbm The actual recommendation from the mysql community is to use `BINARY(16)` for UUIDs to actually improve space and query time over char, but that would mean that you always need to hex/unhex the value yourself. I'd like to keep CakePHP 3 out of recommending `BINARY(36)` as there are no resources in the web supporting they are better in any way

You can read more about it here:

http://iops.io/blog/storing-billions-uuid-fields-mysql-innodb/
http://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
http://www.percona.com/blog/2007/03/13/to-uuid-or-not-to-uuid/

**Comment by lorenzo** [comment]
@beinbm If you are migrating from a 2.x app, I'd suggest creating your own UuidType class and implement your logic there, `BINARY(36)` was a bad idea in the 2.x series that I'd wish not to continue.

**Comment by beinbm** [comment]
thanks

**Comment by dereuromark** [comment]
For reference in case other people upgrade and run into similar issues: https://github.com/dereuromark/cakephp-shim/blob/3.0/docs/Features.md#uuid-as-binary36
