### ISSUE TITLE
set() method in FlashComponent doesn't allow to pass variables to rendered elements.

### ISSUE THREAD

**Issue by Phillaf** [cakephp/cakephp#6394]
Passing variable to the elements rendered by flash messages was a pretty handy feature in cake 2.

Here is a use case  
http://slywalker.github.io/cakephp-plugin-boost_cake/bootstrap3.html#alerts

I don't think there's any way to achieve that with cake3 without resorting to the creation of a multitude of slightly different elements for every variation.

**Comment by ADmad** [comment]
You can still set any key => value pair you want in `$options` argument for FlashComponent::set() and they key will be available as var in your element. Can you provide an example which doesn't work like you expect?

**Comment by dereuromark** [comment]
The docs (and docblock) specify for $options:
```
- `params` An array of variables to make available when using an element
```

**Comment by Phillaf** [comment]
You guys are right, I didn't realise that all of the variables were wrapped inside $params even from the element

// This works like you said    
echo $params['helptext'];

// What I was trying was   
echo $helptext;

This effectively solves my issue. thanks!
