### ISSUE TITLE
Missing layout error message with prefix

### ISSUE THREAD

**Issue by adayth** [cakephp/cakephp#6401]
The template missing_layout.ctp shows an incorrect path when using a prefix.

```
Error: The layout file Admin/Layout/dashboard.ctp can not be found or does not exist.

Confirm you have created the file: Admin/Layout/dashboard.ctp in one of the following paths:

    /var/www/cakephp/cake3/src/Template/Admin/Layout/dashboard.ctp

If you want to customize this error message, create src/Template/Error/missing_layout.ctp
```

The right suggested path should be /var/www/cakephp/cake3/src/Template/Layout/dashboard.ctp

**Comment by ADmad** [comment]
The message is correct. For prefixed controllers Cake will first check for layout under the prefixed folder and if that does not exist the layout from main layout folder is used.

**Comment by adayth** [comment]
Why not suggest the two paths then? I found the message confusing.

**Comment by ADmad** [comment]
The message could suggest both paths but I don't see how the existing message is confusing. If you make a file at the suggested path things will work.

**Comment by adayth** [comment]
Coming from CakePHP 2, to me is more clear to put the Layout in its "old"
location.

Even in the book I can't find information about storing layouts in that
path.

Maybe is just a personal issue but I thinking in the newcomers to the
framework.

2015-04-23 14:48 GMT+01:00 ADmad <notifications@github.com>:

> The message could suggest both paths but I don't see how the existing
> message is confusing. If you make a file at the suggested path things will
> work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/cakephp/issues/6401#issuecomment-95591782>.
>



-- 
Aday Talavera Hierro - Consultoría y desarrollo informático
Web: http://www.felfo.com  -  Email: aday.talavera@gmail.com

**Comment by markstory** [comment]
We could suggest that the dashboard.ctp be created on one of the layout paths instead?
