### ISSUE TITLE
how i do do get session in model ? cakephp 3.x

### ISSUE THREAD

**Issue by sinanbayraktutan** [cakephp/cakephp#6404]
i want to do my captcha custom validation. but I can not access a session.

my code :

$validator->notEmpty('securityCode', __('not empty message'))
        ->add('securityCode','custom', 
        ['rule' => function ($value, $context) use ($extra) {
                     if($this->request->Session()->read('captcha') != $value){
                       return false;
                     }
                     return true;
                  },
                  'message' => 'error securty code']);
        return $validator;
or can i my custom validation function give custom parameter?

public function validationLogin(Validator $validator,$customParameter)
{//bla bla }
Thank you for your interest :)

i am use : http://book.cakephp.org/3.0/en/core-libraries/validation.html#custom-validation-rules

my questions : http://stackoverflow.com/questions/29821765/how-i-do-do-get-session-in-model-cakephp-3-x

**Comment by markstory** [comment]
Since you have a SO question open and this isn't a bug report I'm closing this.

**Comment by sinanbayraktutan** [comment]
i am sorry. i don't know :(
