### ISSUE TITLE
lowercase table names MySQL

### ISSUE THREAD

**Issue by leighmackay** [cakephp/cakephp#6406]
Hello,

CakePHP 3.0.2 using MySQL 5.5.41 on Ubuntu 14.04.1

If the MySQL .my.cnf  has "lower_case_table_names = 0" so table names are case sensitive certain conditions fail.

This one for example

```
"CONCAT(TRIM(Users.first_name), ' ', TRIM(Users.last_name)) LIKE" => '%'. $q .'%',
```

Can see strtolower being used in the new ORM. Not sure if this is intended behaviour, if so I can update book.

Also CakePHP 3 is very fun to use.

The error is below.

```
ERROR
Exception
Documentation API
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.last_name' in 'where clause'
```

If you are using SQL keywords as table column names, you can enable identifier quoting for your database connection in config/app.php.

If you want to customize this error message, create src/Template/Error/pdo_error.ctp

toggle vendor stack frames
```
⟩ PDOStatement->execute
CORE/src/Database/Statement/MysqlStatement.php, line 36
⟩ Cake\Database\Statement\MysqlStatement->execute
CORE/src/Database/Connection.php, line 274
⟩ Cake\Database\Connection->run
CORE/src/Database/Query.php, line 175
⟩ Cake\Database\Query->execute
CORE/src/ORM/Query.php, line 645
⟩ Cake\ORM\Query->_execute
CORE/src/Datasource/QueryTrait.php, line 218
⟩ Cake\ORM\Query->_all
CORE/src/ORM/Query.php, line 596
⟩ Cake\ORM\Query->all
CORE/src/Controller/Component/PaginatorComponent.php, line 169
⟩ Cake\Controller\Component\PaginatorComponent->paginate
CORE/src/Controller/Controller.php, line 642
⟩ Cake\Controller\Controller->paginate
APP/Controller/UsersController.php, line 488
⟩ App\Controller\UsersController->search
[internal function]
⟩ call_user_func_array
CORE/src/Controller/Controller.php, line 412
⟩ Cake\Controller\Controller->invokeAction
CORE/src/Routing/Dispatcher.php, line 114
⟩ Cake\Routing\Dispatcher->_invoke
CORE/src/Routing/Dispatcher.php, line 87
⟩ Cake\Routing\Dispatcher->dispatch
ROOT/webroot/index.php, line 37
```

**Comment by lorenzo** [comment]
What is the query that you built?

**Comment by leighmackay** [comment]
Hello Lorenzo 

 $this->paginate = [
   'conditions' => [
     'Users.account_type !=' => 'page',
     'OR' => [
       "CONCAT(TRIM(Users.first_name), ' ', TRIM(Users.last_name)) LIKE" => '%'. $q .'%',
       "Users.bio LIKE" => '%'. $q .'%'
     ]
   ]
 ];
 $users = $this->paginate($this->Users);

Not sure if it would happen in a table model, have not tried.. will when I can.

**Comment by jhli** [comment]
I might be wrong but you can create virtual like field in your cake User entity instead of using Concat and my guess is CONCAT is the issue here (i hope for a cross rdbms abstraction for concat in future cake3)

**Comment by lorenzo** [comment]
I think you may need to activate `quoteIdentifiers => true` in your database configuration, and build your queries without the string concatenation that you are doing bu using the functions in the ORM (like `$query->func()->concat()`
