### ISSUE TITLE
Implement a sort of indipendent Query::where() condition

### ISSUE THREAD

**Issue by stefanozoffoli** [cakephp/cakephp#6407]
Hi,
i'm using a soft delete trait ( https://github.com/PGBI/cakephp3-soft-delete ) that overrides `find()` call to add a condition: https://github.com/PGBI/cakephp3-soft-delete/blob/master/src/Model/Table/SoftDeleteTrait.php#L30
Because of this I encountered a problem with queries that calls `orWhere()`.

If for example I make this simple query:
```php
$this->loadModel('Products');
$query = $this->Products->find();
$query->where([
		'Products.type' => 1,
	])
	->orWhere([
		'Products.type' => 2,
	]);
debug($query);
```
The query builder generates this wrong SQL query:
```sql
SELECT Products.id AS `Products__id`, ..., Products.deleted AS `Products__deleted`
FROM products Products
WHERE (
	Products.type = :c0
	OR (
		Products.deleted IS NULL
		AND Products.type = :c1
	)
)
```

Is it possible to implement some sort of `where()` condition that makes an indipendent where statement like this?
```sql
SELECT Products.id AS `Products__id`, ..., Products.deleted AS `Products__deleted`
FROM products Products
WHERE (
	Products.deleted IS NULL
	AND (
		Products.type = :c0
		OR (
			Products.type = :c1
		)
	)
)
```

(This problem gave me troubles also while marshalling belongsToMany data: https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php#L294 )

Thank you!
/cc @PGBI

**Comment by lorenzo** [comment]
`where()` should always be `andWhere()`

**Comment by stefanozoffoli** [comment]
Yes, but the problem is due to the fact that find() adds first a condition:

step 1:
`$query->find()` adds `Products.deleted IS NULL`

after step 1 the SQL is correct:
```sql
WHERE (
	Products.deleted IS NULL
)
```

step 2:
`$query->where(['Products.type' => 1])` adds `Products.type = 1`

after step 2 the SQL is correct:
```sql
WHERE (
	Products.deleted IS NULL
	AND Products.type = 1
)
```

step 3:
`$query->orWhere(['Products.type' => 2])` adds `OR Products.type = 2`

after step 3 the SQL became conceptually wrong because it returns me also deleted products of type '2':
```sql
WHERE (
	Products.type = 2
	OR (
		Products.deleted IS NULL
		AND Products.type = 1
	)
)
```

**Comment by lorenzo** [comment]
I would suggest that you use a `beforeFind()` instead of a trait, that is currently the best way of ensuring your conditions are applied to the full set of conditions

**Comment by stefanozoffoli** [comment]
I'll open a ticket to the soft delete plugin to suggest that :smile:

**Comment by markstory** [comment]
Sounds like this issue is caused by misuse of where(), when andWhere shouldl have been used.

**Comment by GuidoHendriks** [comment]
It uses an `andWhere` now for quite a while, so the problem doesn't exist any longer. Still not recommended because of it uses a trait?
