### ISSUE TITLE
Cannot pass a driver instance?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#6410]
**TL;DR**
I tried to pass my own driver class instance to the connection class and I'm getting a 'Driver not found' error.

**What I'm trying to do**
I'm trying to create a datasource to connect to a remote api.

**What I've done**
```php
// MyPlugin/config/bootstrap.php
<?php
namespace ApiUpdatable\config;

use ApiUpdatable\Database\Driver\Api;
use ApiUpdatable\Database\Dsapi;
use Cake\Datasource\ConnectionManager;

ConnectionManager::config('dsapi', [
    'className' => '\ApiUpdatable\Database\Dsapi'
]);

$driver = new Api([
    'url' => 'http://example.co.uk/api/v1/',
    'username' => 'exampleUser',
    'key' => 'someKeyGoesHere'
]);

$connection = new Dsapi([
    'driver' => $driver
]);

// Api driver class
class Api extends Driver {
  protected $_connection;
  // Implemented all the other method stubs
}

// Dsapi connection class
class Dsapi extends Connection {
  // Nothing in here
}
```

**What is happening**
Database driver could not be found.
`Cake\Database\Exception\MissingDriverException`

Generated from `Cake\Database\Connection::driver()` method

**Comment by davidyell** [comment]
Or should I be dealing with the connection in the plugin behaviours `initialize()`?

**Comment by lorenzo** [comment]
The issue description makes little sense to me, can you show the actual code and the stacktrace that you are getting?

**Comment by davidyell** [comment]
I am trying to connect to a remote API. In order to achieve this I'm trying to create my own driver and connection classes. So that I can have a transparent interface with the rest of my code.

In order to achieve this I've created an `Api` driver class, and also a `Dsapi` connection class.

The context of this work is in a plugin which allows api data to be cached to a local database.

I have a number of questions around this.
* I can't find anything definitive in the book about creating your own connection and driver classes. Is this right? This brief section (http://book.cakephp.org/3.0/en/orm/database-basics.html#connection-classes) details just the methods, but I can extend `Connection` and just implement the stub methods. However I can't find anything about creating Driver classes. I found these though (https://github.com/cakephp/cakephp/blob/master/src/Database/README.md).
* Where should I configure my api connection details? I don't want to put them in my connection class because I'll need to use the connection with different apis. As with Cake 2, I would like to use a database configuration to pass.
* If I change the table connection to a new connection class, how persistent is that? Will I need to change it back to the default afterwards? I'm switching the datasource in my behaviours `beforeFind` based on if `'api' => true` is passed in the find query.
* If I am connecting to a remote API do I need a Connection class, or can I just make my own driver?

Hope this makes more sense and gives some ideas for updating the docs.

**Comment by markstory** [comment]
You didn't provide a driver name to the ConnectionManager::config() call, is that a mistake or intentional? I would have expected that the driver would need to be defined.

**Comment by HavokInspiration** [comment]
You should try :

```php
$driver = new Api([
    'url' => 'http://example.co.uk/api/v1/',
    'username' => 'exampleUser',
    'key' => 'someKeyGoesHere'
]);

ConnectionManager::config('dsapi', [
    'className' => '\App\Database\Dsapi',
    'driver' => $driver
]);

// Get your Dsapi connection instance
$Connection = ConnectionManager::get('dsapi');
```

When a Connection object is instanciated, it defaults the ``driver`` parameter to an empty string before trying to use the one passed in the ``ConnectionManager::config()`` second argument.
The exception message you have actually returns it, but since it is an empty string, you can not see it ([see link](https://github.com/cakephp/cakephp/blob/master/src/Database/Exception/MissingDriverException.php#L25)).

Note that to be used, the ``Driver::enabled()`` method (well ``Api::enabled()`` in your case) must return ``true``, otherwise you will get a ``MissingExtensionException``.

**Comment by davidyell** [comment]
> You didn't provide a driver name to the ConnectionManager::config() call, is that a mistake or intentional? 

I did not know that I had to.

Thanks @HavokInspiration, I'll give this a go this morning and see how I get on.

**Comment by davidyell** [comment]
@lorenzo mentioned in irc that I should be using a Repository class.

Would it be worth updating the docs to mention the separation between the ORM and the Repositories and their intended uses?

**Comment by markstory** [comment]
> Would it be worth updating the docs to mention the separation between the ORM and the Repositories and their intended uses?

It totally would, I am hoping to finalize the connection interface while building out the elasticsearch plugin and after that I can update the docs on Repository vs. ORM.

**Comment by davidyell** [comment]
Excellent @markstory, good news. Thanks for the update.
