### ISSUE TITLE
3.0 Modelless Forms Validator method error without data[ prefix in input name

### ISSUE THREAD

**Issue by ukkpower** [cakephp/cakephp#6414]
I have followed the Modelless Forms example in the cookbook and get an error if I do not have the data[] prefix around the input name.

I do not use the form helper to generate the form but rather have it coded as html myself. It works fine with the data[ prefix.

error.log:
`
2015-04-25 14:28:30 Error: [ReflectionException] Method minLenght does not exist
Request URL: /pages/request.json
Stack Trace:
#0 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Validation/RulesProvider.php(64): ReflectionClass->getMethod('minLenght')
#1 [internal function]: Cake\Validation\RulesProvider->__call('minLenght', Array)
#2 [internal function]: Cake\Validation\RulesProvider->minLenght('23423423423', 5, Array)
#3 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Validation/ValidationRule.php(138): call_user_func_array(Array, Array)
#4 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Validation/Validator.php(567): Cake\Validation\ValidationRule->process('23423423423', Array, Array)
#5 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Validation/Validator.php(131): Cake\Validation\Validator->_processRules('phone', Object(Cake\Validation\ValidationSet), Array, true)
#6 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Form/Form.php(142): Cake\Validation\Validator->errors(Array)
#7 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Form/Form.php(173): Cake\Form\Form->validate(Array)
#8 /home/i554246/public_html/hotelieracademy.com/src/Controller/PagesController.php(102): Cake\Form\Form->execute(Array)
#9 [internal function]: App\Controller\PagesController->request()
#10 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Controller/Controller.php(412): call_user_func_array(Array, Array)
#11 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 /home/i554246/public_html/hotelieracademy.com/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PagesController))
#13 /home/i554246/public_html/hotelieracademy.com/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}
`

My updated code in the ContactForm.php

    protected function _buildValidator(Validator $validator)
    {
        return $validator->add('name', 'length', [
        'rule' => ['minLength', 10],
        'message' => 'A name is required'
        ])->add('email', 'format', [
        'rule' => 'email',
        'message' => 'A valid email address is required',
        ])->add('phone', 'length', [
        'rule' => ['minLenght', 5],
        'message' => 'A phone number is required']);
    }

**Comment by dereuromark** [comment]
`Method minLenght does not exist` => `minLenght` => `minLength`.
Looks like you made a typo.

**Comment by ADmad** [comment]
The typo in method name is evident from the error message.

**Comment by ukkpower** [comment]
my bad, sorry. I am just getting up to speed with 3.0 so things are a little different. Strange the adding of data[ prefix made the error go away and the form send an email as intended.
