### ISSUE TITLE
Oracle Driver - Incorrect Display

### ISSUE THREAD

**Issue by pirouet** [cakephp/cakephp#6418]
Currently Connection::connect looks like this:

```php
public function connect()
{
    try {
        $this->_driver->connect();
        return true;
    } catch (\Exception $e) {
        throw new MissingConnectionException(['reason' => $e->getMessage()]);
    }
}
```

I am looking to develop an Oracle driver and the above slice of code will still report that a connection is successful (when viewing Pages::home and I suspect this is because oci_connect is handling the exception thrown so the connect method completes fine and returns true) however the connection fails (purposely failing to test connectivity). I have slightly modified this to be as follows:

```php
public function connect()
{
    try {
        return $this->_driver->connect();
    } catch (\Exception $e) {
        throw new MissingConnectionException(['reason' => $e->getMessage()]);
    }
}
```

By doing so it correctly shows when the connection to the database fails (as I would expect) and all the tests are passing in travis on my personal fork; AppVeyor fails for comparing strings. Do you see this breaking anything that isn't showing in the tests or could it be something considered for a future versions?

P.S. When it fails to connect to the database (MySQL for example) it still correctly shows the error message on screen 

What's your thoughts?

**Comment by pirouet** [comment]
Travis CI Build Passing: https://travis-ci.org/pirouet/cake/builds/60053417

**Comment by markstory** [comment]
Could the oracle driver not raise an exception when `oci_connect()` returns false as well?

**Comment by pirouet** [comment]
I've tried to play around and get the correct output without modifying the Connection class but it didn't seem to work; It still showed as connected but I'll have another shot at it.

**Comment by lorenzo** [comment]
I'm ok with the change @pirouet if you want to send a PR. Although it would make your driver more consistent if it threw an exception.

Is the code available anywhere?

**Comment by pirouet** [comment]
I don't have the code available on GitHub yet; just locally for now as it's very early in the development stage

However, I will be uploading to my own repository soon with the view of, hopefully, proving this driver for the cake community to use
