### ISSUE TITLE
SQL debug outputs not showing in English

### ISSUE THREAD

**Issue by jowusu837** [cakephp/cakephp#6421]
I recently updated the library of my application from version 2.3 to 2.6 and my sql outputs are not showing in English. How do I fix that?

**Comment by ADmad** [comment]
I can't help being curious, in what language are they shown now?

**Comment by jowusu837** [comment]
Here is a sample code of response I get:

{
  "code": 500,
  "name": "SQLSTATE[42S22]: Column not found: 1054 Champ &#039;User.parent_id&#039; inconnu dans where clause",
  "message": "SQLSTATE[42S22]: Column not found: 1054 Champ &#039;User.parent_id&#039; inconnu dans where clause",
  "error":   {
    "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[42S22]: Column not found: 1054 Champ 'User.parent_id' inconnu dans where clause in C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Datasource\DboSource.php on line <i>460</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0010</td><td bgcolor='#eeeeec' align='right'>148192</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp\www\my-ekklesia-online\app\webroot\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.1650</td><td bgcolor='#eeeeec' align='right'>1967432</td><td bgcolor='#eeeeec'>Dispatcher->dispatch(  )</td><td title='C:\wamp\www\my-ekklesia-online\app\webroot\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.2410</td><td bgcolor='#eeeeec' align='right'>2706240</td><td bgcolor='#eeeeec'>Dispatcher->_invoke(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Routing\Dispatcher.php' bgcolor='#eeeeec'>..\Dispatcher.php<b>:</b>167</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.8664</td><td bgcolor='#eeeeec' align='right'>5975256</td><td bgcolor='#eeeeec'>Controller->invokeAction(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Routing\Dispatcher.php' bgcolor='#eeeeec'>..\Dispatcher.php<b>:</b>193</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.8664</td><td bgcolor='#eeeeec' align='right'>5975576</td><td bgcolor='#eeeeec'><a href='http://www.php.net/ReflectionMethod.invokeArgs' target='_new'>invokeArgs</a>
(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Controller\Controller.php' bgcolor='#eeeeec'>..\Controller.php<b>:</b>490</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.8664</td><td bgcolor='#eeeeec' align='right'>5975744</td><td bgcolor='#eeeeec'>UsersController->delete(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Controller\Controller.php' bgcolor='#eeeeec'>..\Controller.php<b>:</b>490</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.8674</td><td bgcolor='#eeeeec' align='right'>5976024</td><td bgcolor='#eeeeec'>Model->delete(  )</td><td title='C:\wamp\www\my-ekklesia-online\app\Controller\UsersController.php' bgcolor='#eeeeec'>..\UsersController.php<b>:</b>211</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.8944</td><td bgcolor='#eeeeec' align='right'>5981768</td><td bgcolor='#eeeeec'>Model->_deleteDependent(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>2689</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>1.0608</td><td bgcolor='#eeeeec' align='right'>6159312</td><td bgcolor='#eeeeec'>Model->delete(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>2768</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>1.0608</td><td bgcolor='#eeeeec' align='right'>6161864</td><td bgcolor='#eeeeec'>Model->_deleteDependent(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>2689</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>1.4664</td><td bgcolor='#eeeeec' align='right'>6896840</td><td bgcolor='#eeeeec'>Model->find(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>2764</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>1.4664</td><td bgcolor='#eeeeec' align='right'>6910512</td><td bgcolor='#eeeeec'>Model->_readDataSource(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>2994</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>1.4664</td><td bgcolor='#eeeeec' align='right'>6910512</td><td bgcolor='#eeeeec'>DboSource->read(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Model.php' bgcolor='#eeeeec'>..\Model.php<b>:</b>3022</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>1.4820</td><td bgcolor='#eeeeec' align='right'>6912488</td><td bgcolor='#eeeeec'>DboSource->fetchAll(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Datasource\DboSource.php' bgcolor='#eeeeec'>..\DboSource.php<b>:</b>1106</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>1.4820</td><td bgcolor='#eeeeec' align='right'>6912824</td><td bgcolor='#eeeeec'>DboSource->execute(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Datasource\DboSource.php' bgcolor='#eeeeec'>..\DboSource.php<b>:</b>668</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>1.4820</td><td bgcolor='#eeeeec' align='right'>6913024</td><td bgcolor='#eeeeec'>DboSource->_execute(  )</td><td title='C:\wamp\www\my-ekklesia-online\lib\Cake\Model\Datasource\DboSource.php' bgcolor='#eeeeec'>..\DboSource.php<b>:</b>426</td></tr>
",
    "errorInfo":     [
      "42S22",
      1054,
      "Champ 'User.parent_id' inconnu dans where clause"
    ],
    "queryString": "SELECT `SubAccount`.`id` FROM `my-ekklesia-online`.`users` AS `SubAccount`   WHERE `SubAccount`.`organization_id` = 8 AND `User`.`parent_id` = 4"
  },
  "url": "/users/19.json"
}

**Comment by ADmad** [comment]
The [error message language](https://dev.mysql.com/doc/refman/5.5/en/error-message-language.html) for your MySQL server has been changed. It has nothing to do with CakePHP.

**Comment by jowusu837** [comment]
OK. I will check that. Thanks!

**Comment by dereuromark** [comment]
This is more a bug in the default download package of WAMPserver and alike.
Had the same thing, just add the "en_GB" etc as language to your Mysql my.ini file etc.
Nothing with CakePHP.

**Comment by jowusu837** [comment]
Thank you so much. I love cakephp!
