### ISSUE TITLE
3.0: We need better IntegrationTestCase 5xx debugging

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6422]
Currently, the result of an unexpected 5xx error would just show as 
```
1) App\Test\TestCase\Controller\AccountControllerTest::testEdit
Status code is not 200 but 500
Failed asserting that 500 is equal to 200 or is less than 200.
```

No logs entry, no additional data on what went wrong. Impossible to debug at that point.

One way would be `file_put_contents(TMP . 'x' . rand(1, 1000) . '.html', $this->_response->body());` from within `IntegrationTestCase ::_assertStatus()`
to actually find the error via generated body HTML content.

Turns out it was 
```
An Internal Error Has Occurred

Error: The "Passwordable" alias has already been loaded with the following config: array...
```

Any way to capture that in integration tests and let it bubble up somewhere?

**Comment by dereuromark** [comment]
Example: https://travis-ci.org/dereuromark/cakephp-sandbox/jobs/60151328
It only fails for a specific case, and the actual error is hidden away.

**Comment by markstory** [comment]
I'm not sure there should be logs when an assertion fails, could you not also inspect the response in the testcase that is failing?

**Comment by dereuromark** [comment]
And look for what exactly?
After the exception has been processed into output it seems only possible via stacktrace.

**Comment by dereuromark** [comment]
Closing as PR is open.
