### ISSUE TITLE
model file cant accessible 

### ISSUE THREAD

**Issue by JahYusuff** [cakephp/cakephp#6424]
<b>am planning to use cake php as webservice<b>
i bulid the url like this (host/al_ecom_service/Category/getCategoryDetails/id/1/)
here i can get the output as a json.(did some chenges in while return.)
it working perfectly in localhost.
its not working after moved to the live, am getting following error
		Missing Database Table
		Error: Table categories for model Categories was not found in datasource default.
i assume that model $useTable is not working here.

Controller
----------------------
<?php 
class CategoryController extends AppController {
	var $name = 'Categories'; 
	var $uses = array('Categories', 'Products');
	function getCategoryDetails() {
        	$categories = $this->Categories->find('all', array(
			'conditions' => array('Category.sub_category_status' => 1, 'Category.sub_category_id' => 1 ),
			'fields' => array('Category.sub_category_name,Category.sub_category_status, Category.sub_category_id, Category.main_category_id, Category.sub_category_status')
		));
	    echo json_encode($categories);
        exit;
	}		
	}
Model
------------------
<?php
class Categories extends AppModel {
  var $useTable = 'al_data_categories_subs';
}  

My Error log
-------------------
2015-04-27 05:35:20 Error: [MissingTableException] Table categories for model Categories was not found in datasource default.
Exception Attributes: array (
  'table' => 'categories',
  'class' => 'Categories',
  'ds' => 'default',
)
Request URL: /al_ecom_service/Category/getCategoryDetails/id/1/
Stack Trace:
#0 /home/affordablear/public_html/al_ecom_service/lib/Cake/Model/Model.php(3496): Model->setSource('categories')
#1 /home/affordablear/public_html/al_ecom_service/lib/Cake/Model/Model.php(2900): Model->getDataSource()
#2 /home/affordablear/public_html/al_ecom_service/lib/Cake/Model/Model.php(2872): Model->_readDataSource('first', Array)
#3 /home/affordablear/public_html/al_ecom_service/app/Controller/CategoryController.php(63): Model->find('first', Array)
#4 [internal function]: CategoryController->getCategoryDetails('id', '1')
#5 /home/affordablear/public_html/al_ecom_service/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoryController), Array)
#6 /home/affordablear/public_html/al_ecom_service/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /home/affordablear/public_html/al_ecom_service/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(CategoryController), Object(CakeRequest), Object(CakeResponse))
#8 /home/affordablear/public_html/al_ecom_service/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by JahYusuff** [comment]
Please help..
My collage project is in critical COndition..
Thanks In advance

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
