### ISSUE TITLE
Function that builds and executes the query without returning the result set

### ISSUE THREAD

**Issue by cithukyaw** [cakephp/cakephp#6426]
I'm using CakePHP 2.1.3. I have a performance problem of looping a large set of array data returned from [`find('all')`][1]. I want to retrieve a query result row by row to eliminate this expensive array processing. I don't want the result set of array returning from [`find()`][2] or [`query()`][3]. The Cake's `find()` has an internal array processing and the returned result set has to be looped again explicitly. I want to optimize the code by avoiding those array processing of large data twice.

What I'm trying to do is like below: 

    $db = $this->Model->getDataSource();

    $sql = 'SELECT * FROM my_table';
    if($result = $db->execute($sql){
      $db->resultSet($result);
      while($row = $db->fetchResult()){
         // do something with $row
      }
    }

However, I don't want to write the raw query here and I want to let Cake build the query. Is there any Cake function that just builds the query according to the association set and executes it without returning the result set?

I'm currently implementing the above script in a controller. My model has no associations now and so I don't need to use `recursive = -1`. It is the whole table fetching for the purpose of CSV export.

If there is no such kind of facility in Cake, the following would be my workaround in AppModel.php
```
  public function exeQuery($type = 'all', $query = array()){
    $queryData = $this->buildQuery($type, $query);
    if (is_null($queryData)) {
      return null;
    }

    $sql = $this->getQueryStatement($queryData);
    if (!$sql) {
      return null;
    }

    $db = $this->getDataSource();
    if ($result = $db->execute($sql)) {
      $db->resultSet($result);
    } else {
      return null;
    }
    return $db;
  }

  public function getQueryStatement($queryData = array()){
    $dbSource = $this->getDataSource();
    
    // Here, some code copied from [the Cake core class DboSource.php][4]
    // from line [1010][5] to line [1054][6]
    
    $query = trim($dbSource->generateAssociationQuery($this, null, null, null, null, $queryData, false, $null));
    return $query;
  }
```
[4] https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php#L1007
[5] https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php#L1010
[6] https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php#L1054

Then in my controller, just call `exeQuery`,
```
$query = $this->MyModel->exeQuery('all', array());
if ($query) {
   while ($row = $query->fetchResult()) {
      // do something with $row
   }
}
```
However, I know it is not a good idea to duplicate the core code. I wish I could have a modular function such `exeQuery` and `getQueryStatement()` in DboSource.php. It will be great if this kind of update included in **2.6+**. It may not be suitable to update **2.1.x**. We have planned to upgrade **2.6.x**, but we are not sure to upgrade to **3.x** as it is backward-incompatible.

If I have a chance to contribute, it is possible to add this feature and DboSource.php is a right place to have this function(s)? The line [1008](https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php#L1008) to [1056](https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php#L1056) of DboSource.php will be replaced with a function call `$this->getQueryStatement()`.

  [1]: https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Model.php#L2689
  [2]: https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Model.php#L2689
  [3]: https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Model.php#L2689

**Comment by lorenzo** [comment]
It could be included in 2.7 if you want to contribute such a function

**Comment by cithukyaw** [comment]
I'm not sure where [Model.php][1] and [DboSource.php][2] is moved in 3.x. Since Cake 3.x has been released, how to get a code based on 2.6.x in the forked repo?

[1]: https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Model.php
[2]: https://github.com/cakephp/cakephp/blob/2.1.3/lib/Cake/Model/Datasource/DboSource.php

**Comment by ADmad** [comment]
@cithukyaw It's branch `2.6`.

**Comment by ADmad** [comment]
Though you need to make your patch against branch `2.7`.

**Comment by cithukyaw** [comment]
I've added this in my local clone. According to [2.6 contributing guideline](https://github.com/cakephp/cakephp/blob/2.6/CONTRIBUTING.md#test-cases-and-codesniffer), I had to install PHPUnit 3.7.x and run all tests using `./lib/Cake/Console/cake test core AllTests --stderr`. A lot of debug outputs are shown in the terminal so I couldn't check them all. When I changed to `Configure::write('debug', 0);` in ./app/Config/core.php, I see this

```
sithu@sithu-kubuntu:/var/www/html/cakephp$ ./lib/Cake/Console/cake test core AllTests --stderr

Welcome to CakePHP v2.6.0-beta Console
---------------------------------------------------------------
App : app
Path: /var/www/html/cakephp/app/
---------------------------------------------------------------
CakePHP Test Shell
---------------------------------------------------------------
PHPUnit 3.7.38 by Sebastian Bergmann.

.......................FSF.SF................................   61 / 3723 (  1%)
....................................2015-04-30 22:53:00 Notice: This is a notice error in [/some/file, line 275]
.2015-04-30 22:53:00 Error: This is a fatal error in [/some/file, line 275]
........................  122 / 3723 (  3%)
......................................SSF............SSSS....  183 / 3723 (  4%)
.............................................................  244 / 3723 (  6%)
................S..S.........................................  305 / 3723 (  8%)
..................................................E.EEEEEEEE.  366 / 3723 (  9%)
.S..........................................................E  427 / 3723 ( 11%)
EEE........E....E..EEEE...E.EEE.EEEEEEEEEEEEEEEEEEES.EFE.EEEE  488 / 3723 ( 13%)
EEEEEEEEEEE.EE.EFEE.E.EEE.....EEEEEEEEEEEEEEEEEEEEEEEE.......  549 / 3723 ( 14%)
..EE.EEEEE.....EE....EE.EEFE.EEEEEEEEEE......................  610 / 3723 ( 16%)
..SSSSSSSSSS.............S......SSSSSSSSSSSSSSSSSSSSSSSSSSSSS  671 / 3723 ( 18%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........  732 / 3723 ( 19%)
......E........................this is the test element.E................E......EEEE.  793 / 3723 ( 21%)
...E...................EE.E.E...........E.EEEEEE.............  854 / 3723 ( 22%)
.............................................................  915 / 3723 ( 24%)
.............................................................  976 / 3723 ( 26%)
..........................E.EEEEEE.........FFE........EEEEEEE 1037 / 3723 ( 27%)
................E.EFEEEEEEEEEEE.............................. 1098 / 3723 ( 29%)
..............S.............................................. 1159 / 3723 ( 31%)
....E.E...........F.........................................E 1220 / 3723 ( 32%)
........................EEEEFE.......S....................... 1281 / 3723 ( 34%)
..................EE......E...............EE.E.S.EE.....E.... 1342 / 3723 ( 36%)
........F.................................................... 1403 / 3723 ( 37%)
..................E.E....ESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1464 / 3723 ( 39%)
SSSSSSSSSSSSSSSSSSSS<!DOCTYPE html>
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />   <title>
                CakePHP: the rapid development php framework:
                Errors  </title>
        <link href="/var/www/html/cakephp/lib/Cake/Console/favicon.ico" type="image/x-icon" rel="icon" /><link href="/var/www/html/cakephp/lib/Cake/Console/favicon.ico" type="image/x-icon" rel="shortcut icon" /><link rel="stylesheet" type="text/css" href="/var/www/html/cakephp/lib/Cake/Console/css/cake.generic.css" /></head>
<body>
        <div id="container">
                <div id="header">
                        <h1><a href="http://cakephp.org">CakePHP: the rapid development php framework</a></h1>
                </div>
                <div id="content">


                        <h2>An Internal Error Has Occurred.</h2>
<p class="error">
        <strong>Error: </strong>
        An Internal Error Has Occurred.</p>
                </div>
                <div id="footer">
                        <a href="http://www.cakephp.org/" target="_blank" id="cake-powered"><img src="/var/www/html/cakephp/lib/Cake/Console/img/cake.power.gif" alt="CakePHP: the rapid development php framework" border="0" /></a>                    <p>
                                CakePHP 2.6.0-beta                      </p>
                </div>
        </div>
        </body>
</html>
```
I'm not sure what this mean `Error: This is a fatal error in [/some/file, line 275]` and Internal Error. Can you please advise something?

**Comment by dereuromark** [comment]
Usually you should run the console relative from your app dir, not directly from that Console dir. That might fix the issue.

**Comment by cithukyaw** [comment]
It was at `/var/www/html/cakephp` where `.travis.yml` exists. You can see it at the first line of my above code snapshot. Is it not a correct location? 

I re-tried it with `Configure::write('debug', 1);`. Then, I got an error `SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist` atop of long debug output.

**Comment by dereuromark** [comment]
That is the root dir

**Comment by cithukyaw** [comment]
I got the tests running successfully. I'm ready to commit. Could we have it included as earliest as possible in the milestone 2.6.x? Though I know it is not a bug fix, but it is likely to be enhancement.

**Comment by markstory** [comment]
Closing as this is implemented in 3.x and from the existing patches it is a fairly risky change in 2.x. I'm not sure the risk is worth the reward here.
