### ISSUE TITLE
Inheritance issue when loading Auth component

### ISSUE THREAD

**Issue by Phillaf** [cakephp/cakephp#6427]
I have a class named Users in my project

        namespace App\Controller;                                               
        use MyPlugin\Controller\UsersController as MyPluginUsersController;     

        class UsersController extends MyPluginUsersController                   
        {                                                                          
            public function login(){                                               
                parent::login();                                                
                debug($this->Auth->redirectUrl());                              
                exit;                                                           
            }                                                                   
        }

And it overrides the Users class in a plugin

        namespace MyPlugin\Controller;
        use MyPlugin\Controller\AppController;

        class UsersController extends AppController                             
        {                                                                          
            public function login()                                             
            {                                                                   
                $user = $this->Auth->identify();                                
                if ($user) {                                                       
                    $this->Auth->setUser($user);                                   
                    debug($this->Auth->redirectUrl());                          
                    return $this->redirect($this->Auth->redirectUrl());         
                }                                                               
            }                                                                   
        }

My plugins controllers inherit the plugins App Controller

        namespace MyPlugin\Controller;                                                                                
        use App\Controller\AppController as BaseController;                     

        class AppController extends BaseController                                 
        {                                                                          
            public function initialize()                                           
            {                                                                   
                parent::initialize();                                              
                //debug($this->Auth->redirectUrl());                               
            }                                                                      
        }

Which inherits the main application's AppController

        namespace App\Controller;                                                                                                                               
        use Cake\Controller\Controller;                                         

        class AppController extends Controller                                  
        {                                                                                                                                             
            public function initialize() {                                      
                $this->loadComponent('Auth', [                                  
                    'authorize' => 'Controller',                                
                    'loginRedirect' => 'http://google.com',                     
                ]);                                                             
            }                                                                   
        } 

If I run it like above I get:

        /plugins/MyPlugin/src/Controller/UsersController.php (line 183)
        '/pages/home'
        /src/Controller/UsersController.php (line 91)
        'http://google.com'

This is weird, I would expect both to show the values defined in my Auth config. However if I uncomment the "debug" line in my plugin's AppController, I get the following output

        /plugins/MyPlugin/src/Controller/AppController.php (line 27)
        'http://google.com'
        /plugins/MyPlugin/src/Controller/UsersController.php (line 183)
        'http://google.com'
        /src/Controller/UsersController.php (line 91)
        'http://google.com'

**Comment by ADmad** [comment]
`AuthComponent::redirectUrl()` checks for `Auth.redirect` session value and if available returns it and **deletes** it. If the session values if not available it returns values of `loginRedirect` config. So the different return values you get for consecutive calls is expected.
