### ISSUE TITLE
2.6, Redis session/cache being destroyed on redirect

### ISSUE THREAD

**Issue by bringerofrain** [cakephp/cakephp#6435]
I'm in the process of upgrading our project from Centos-6/Apache 2.0/PHP5.3/Cake 2.0/File Cache (6/0/3/0/F) to Centos-7/Apache 2.4/PHP5.6/Cake 2.6/Redis Cache & Session (7/4/6/6/R).

The upgrade works great and as intended if I leave the 7/4/6/6/R with File Caching and php sessions. But I've installed Redis following a few tutorials and everything works as intended from PHP 5.6 recognizing Redis (phpinfo dump), CakePHP gets 18 for 18 tests passes in test.php, yet the Redis Sessions are being destroyed on redirects.

Core.php
---------------------------------
    //Replaces standard
    Configure::write('Session', array(
    'defaults' => 'cache',
    'timeout' => '100',
    'start' => true,
    'checkAgent' => false,
    'handler' => array(
    'config' => 'session'
    )
    ));
    //Engine
    $engine = 'Redis';

    //Bottom of Core
     Cache::config ('session', array (
     'Engine' => $engine,
    'Prefix' => $prefix . 'cake_session_',
    'Duration' => $duration
    ));

Bootstrap.php

    Cache::config('default', array('engine' => 'Redis'));

AppController.php

    public $components = array(
    'Session',
    'Auth' => array(
        'loginRedirect'=>array('controller' => 'companies', 'action' => 'view'),
        'logoutRedirect'=>array('controller' => 'users', 'action' => 'login'),
        'loginAction'=>array('controller' => 'users', 'action' => 'login'),
        'authenticate' => array(
            'Form' => array(
                'userModel' => 'User',
                'fields' => array('username' => 'email', 'password' => 'password')
            )
        )
    ));

UsersController.php - Login Function - C&P'd from Blog example

    if ($this->request->is('post')) {

    if ($this->Auth->login()) {
        //print_r($_SESSION);die();
        return $this->redirect($this->Auth->redirectUrl());
    }
    $this->Session->setFlash(__('Invalid username or password, try again'));
    }

Will print the intended and entire Session Array key=>values. PERFECT!!! Now If I let the redirect through.

CompaniesController.php

    public function view($id = null) {
        print_r($_SESSION);
    }

Contains no key=>values.

**Comment by markstory** [comment]
Did you remember to start the session before trying to print out $_SESSION?

**Comment by ADmad** [comment]
Better to use the SessionComponent or CakeSession to read session values instead of using $_SESSION directly.

**Comment by bringerofrain** [comment]
Is the Session_Start not called when the component is called at the top of AppController; or when 
    $this->Auth->deny('*');

is the first line of AppCont's beforeFilter?

And when using:
    $sesres = $this->Session->read(null);
     print "After redirect";print_r($sesres);die();

Before the Redirect and After the Redirect produce the same results as $_SESSION.

**Comment by markstory** [comment]
Is there session data in redis?

**Comment by bringerofrain** [comment]
TY, I had to backtrack even further.  Wasn't expecting [httpd's] php.conf local value to overwrite php.ini's master value.
