### ISSUE TITLE
3.0.2 - Custom variables are not set in a flash view when using Routing prefix

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#6436]
Hello,

I'm trying to use the flash message with a routing prefix, but the variables are not passed to the view. I can access to the special variable `$message`, but not my custom variables :

*src\Controller\Forum\ThreadsController.php*
```php
$this->Flash->set('Validation errors', [
    'key' => 'ThreadReply',
    'element' => 'thread_reply',
    'params' => [
        'errors' => ['foo' => 'bar']
    ]
]);
```
*src\Template\Forum\Element\Flash\thread_reply.ctp*
```php
debug($errors);
```
=> `Undefined variable: errors`

I tried to look if there was some tests about that, but there is no test, maybe add one ?

**Comment by ADmad** [comment]
`debug($params['errors']);`

**Comment by Xety** [comment]
Omg, i'm so noob, sorry about that and thanks.
