### ISSUE TITLE
CakePHP 3 Prefix routing on some controllers only

### ISSUE THREAD

**Issue by webmoose** [cakephp/cakephp#6439]
I'm trying to set up prefix routing but only on certain controllers where I would want a separate admin version but I only seem to be able to make it work for all or nothing.

    $routes->prefix('admin', function ($routes) {
        $routes->connect('/:controller/:action/*', [], ['routeClass' => 'Cake\Routing\Route\InflectedRoute']);
    });

The above creates an admin prefix on every controller such that all links created with the HTML helper have the admin prefix added to them and even when I'm redirected to login it is prefixed with /admin/. I would need to create admin version of every controller or specify on every link prefix=>false.

I assumed it would be something like:

    $routes->prefix('admin', function ($routes) {
        $routes->connect('/projects/:action/*', ['controller' => 'Projects'], ['routeClass' => 'Cake\Routing\Route\InflectedRoute']);
    });

but with this code when accessing a page within /admin/projects i get the error: Error: A route matching "array ( 'controller' => 'Users', 'action' => 'login', 'prefix' => 'admin', 'plugin' => NULL, '_ext' => NULL, )" could not be found.
As if it is trying to redirect me to login, even though if i revert the code back the page loads and I have not been logged out.

Thanks in advance for your help.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
