### ISSUE TITLE
 Fatal error: Unsupported operand types

### ISSUE THREAD

**Issue by geof62** [cakephp/cakephp#6442]
Hello, 

I've a problem with this files : 
( ! ) Fatal error: Unsupported operand types in [...]\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 108
Call Stack
	Time	Memory	Function	Location
1	0.0015	235136	{main}( )	..\index.php:0
2	0.0022	244792	require( ' [...]\webroot\index.php' )	..\index.php:16
3	0.0033	280024	require( ' [...]\config\bootstrap.php' )	..\index.php:27
4	0.0381	1636768	Cake\Error\ErrorHandler->__construct( )	..\bootstrap.php:107

how can I solve this problem ? 

cordially

**Comment by markstory** [comment]
How did you get here?

**Comment by markstory** [comment]
Alternatively how could someone else reproduce this issue?

**Comment by dereuromark** [comment]
It would be best to debug()  line 108 and paste the content of the variables there.

**Comment by geof62** [comment]
@markstory the code is very minimalist : https://github.com/geof62/Aviornis

**Comment by geof62** [comment]
@dereuromark : 

var_dump($options);
 var_dump($defaults);

null

array (size=3)
  'log' => boolean true
  'trace' => boolean false
  'exceptionRenderer' => string 'Cake\Error\ExceptionRenderer' (length=28)


so $options isn't an array, I'm going to search why

**Comment by geof62** [comment]
line 110 config/bootstrap.php : 
```
var_dump(Configure::read('Error'));
```
-> NULL

config of config/app_default.php : 
```
'Error' => [
        'errorLevel' => E_ALL & ~E_DEPRECATED,
        'exceptionRenderer' => 'Cake\Error\ExceptionRenderer',
        'skipLog' => [],
        'log' => true,
        'trace' => true,
    ],
```

**Comment by markstory** [comment]
Well getting Null would be the problem. Perhaps you should ensure that you have an app.php file, as there isn't one in your code repo.

**Comment by geof62** [comment]
yes i've an app.php, but there is in the gitignore

content : 
```
<?php
return [
'yop' => 'yop'
];
```

**Comment by ADmad** [comment]
Your `config/app.php` should have all configs shown in [config/app.default.php](https://github.com/cakephp/app/blob/master/config/app.default.php)

**Comment by dereuromark** [comment]
And that one should ideally not be in gitignore, better use a second one on top with custom overwrites that you then exclude.

**Comment by geof62** [comment]
I'm so stupid...
Thanks, it works ;)
