### ISSUE TITLE
Validator method arguments inconsistency?

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#6444]
In `Cake\Validation\Validator`, why do these methods have a different order of arguments?

```php
public function requirePresence($field, $mode = true, $message = null) { //... }
public function notEmpty($field, $message = null, $when = false) { //... }
```

In these two methods, `$mode` and `$when` serve a similar purpose, except that in the case of `notEmpty()`, `$when` can be a callable.  Does this cause the order of arguments to be different for technical reasons?

I just thought it was a bit confusing that the order of arguments are inverted, ie - usage could look like:

```php
$validator
    ->requirePresence('foo', 'create', 'A foo be required son.')
    ->notEmpty('foo',  'A foo cannot be empty, ya dingus!', 'create');
```

I know this is trivial, and probably not worth it to 'fix' (if it's even considered broken), but I thought I'd bring it up anyway.

**Comment by markstory** [comment]
I think the reasoning was that we thought people would be modifying the mode in `requirePresence()` more than they would the error message.

We could possibly support a short more consistent form of `notEmpty('field', $when)`. It might also be possible to support the $when and $message arguments in both orders, but it would would mean that 'create' and 'update' could never be used as messages.

**Comment by kevinquinnyo** [comment]
> It might also be possible to support the $when and $message arguments in both orders, but it would would mean that 'create' and 'update' could never be used as messages.

I was wondering about that, and that answers it.  Obviously not ideal, but in a practical sense, would someone ever really *want* to supply a message that literally just says 'update' or 'create'?  I don't really have an opinion on what's best though, except that I think in this case, "if it's documented, it's feature not a bug" kind of holds true here.  I had considered also that you did that because modifying the mode in `requirePresence()` and just using the default message would be more common.

**Comment by markstory** [comment]
Having multi-mode functions isn't great but it would let us get more consistency between the methods which is a win I think.  I agree that 'create' and 'update' are very useless as error messages and if someone bumps into that they have probably made a few other suboptimal decisions.

**Comment by lorenzo** [comment]
This is something we cannot change now, unfortunately as it would be a sad breaking change. Will keep it in mind for future changes to the Validator.
