### ISSUE TITLE
LoggerPlugin

### ISSUE THREAD

**Issue by kallep87** [cakephp/cakephp#6445]
hey, 
i want to create a Logger Plugin

my Path to the File:
plugins/DatabaseLogger/src/Log/Engine

my php-File DatabaseLog.php
```php
<?php

namespace App\Log\Engine;

use Cake\Log\Engine\BaseLog;
use Cake\ORM\TableRegistry;

class DatabaseLog extends BaseLog{

  private $Model;

  public function __construct(array $config = []){
    parent::__construct($config);
  }

  public function log($level, $message, array $context = []){
    
    //Laden des Models
    if(!$context || !array_key_exists('model', $context)){
       $context['model'] = 'SystemLogs';
    }
    $this->Model = TableRegistry::get($context['model']);
    
    $log_data = [
      'level' => $level,
      'message' => $message
    ]; 

    $entity = $this->Model->newEntity($log_data);
    $this->Model->save($entity);
    
    return true;
  }
}
```

my composer.json:
```json
"autoload": {
        "psr-4": {
            "App\\": "src",
            "DatabaseLogger\\": "./plugins/DatabaseLogger/src"
        }
    },
```

and my app.php
```php
'Log' => [
      'debug' => [
          'className' => 'DatabaseLogger.DatabaseLog'
      ]  
    ],
```

When I open my application, I get the following error: Error: Could not load class DatabaseLog
Fatal error: Uncaught exception 'RuntimeException' with message 'Could not load class DatabaseLog' in /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/LogEngineRegistry.php:57 Stack trace: #0 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(86): Cake\Log\LogEngineRegistry->_throwMissingClassError('DatabaseLog', 'DatabaseLogger') #1 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/Log.php(198): Cake\Core\ObjectRegistry->load('debug', Array) #2 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/Log.php(180): Cake\Log\Log::_loadConfig() #3 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/Log.php(360): Cake\Log\Log::_init() #4 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/Log.php(462): Cake\Log\Log::write('error', '[RuntimeExcepti...', Array) #5 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(245): Cake\Log\Log::error('[RuntimeExcepti...') #6 /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(156): Cake\Error\Base in /Users/patrick/Sites/vz/vendor/cakephp/cakephp/src/Log/LogEngineRegistry.php on line 57

Where here is my fault?

Patrick

**Comment by kallep87** [comment]
Where here is my fault

**Comment by burzum** [comment]
For questions like this please use stackoverflow.com or one of the community resources like the Google groups or the IRC channel. *This is a bug / issue tracker and not a help forum.*

However, your class can't be loaded, the error message is pretty clear. I think your namespace is wrong. Instead of App use DatabaseLogger.
