### ISSUE TITLE
Fatal error: Exception thrown without a stack frame

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#6446]
Exception thrown while running test shell by calling dispatchShell(). 

```php
class UnitTestsTask extends Shell {

	public function execute() {
		$this->dispatchShell('-app ' . APP . ' test app --debug');
		$this->out('Done.');
	}
}
```

Time: 419 ms, Memory: 11.50Mb

OK, but incomplete or skipped tests!
Tests: 3, Assertions: 2, Skipped: 1.

Fatal error: Exception thrown without a stack frame in Unknown on line 0

Call Stack:
    0.0005     340160   1. {main}() C:\...\Cake\Console\cake.php:0
    0.0021     463672   2. ShellDispatcher::run() C:\...\Cake\Console\cake.php:54
    0.0647    4608800   3. ShellDispatcher->dispatch() C:\...\Cake\Console\ShellDispatcher.php:66
    0.0712    5174880   4. Shell->runCommand() C:\...\Cake\Console\ShellDispatcher.php:209
    0.0774    5526864   5. UtilShell->main() C:\...\Cake\Console\Shell.php:447
    1.8755    5555760   6. UnitTestsTask->execute() C:\...\app\Console\Command\UtilShell.php:29
    1.8755    5555864   7. Shell->dispatchShell() C:\...\app\Console\Command\Task\UnitTestsTask.php:11
    1.8756    5557600   8. ShellDispatcher->dispatch() C:\...\Cake\Console\Shell.php:385
    1.8900    6938016   9. Shell->runCommand() C:\...\Cake\Console\ShellDispatcher.php:209
    1.8945    7012976  10. TestShell->main() C:\...\Cake\Console\Shell.php:447
    1.8948    7013448  11. TestShell->available() C:\...\Cake\Console\Command\TestShell.php:256
    8.2428    7106880  12. TestShell->_run() C:\...\Cake\Console\Command\TestShell.php:317
    8.2471    7345616  13. CakeTestSuiteCommand->run() C:\...\Cake\Console\Command\TestShell.php:274

**Comment by markstory** [comment]
Neato.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue using the latest 2.6 on OSX with PHP5.5.40. Here is a [gist](https://gist.github.com/markstory/8aefc51d36498bf980df) of the code and output I got.
