### ISSUE TITLE
QueryTrait FormatResults: missing arguments

### ISSUE THREAD

**Issue by HoiJean** [cakephp/cakephp#6457]
I was following a tutorial then i got stuck because there was an error within QueryTrait class.
I don't know for sure if this is an error or my mistake, i had to add edit the QueryTrait to get it work.

File: QueryTrait.php on line 436

$result = $formatter($result);

should be

$result = $formatter($result, 0);

See the images below:
http://i.imgur.com/HSes1hU.png
http://i.imgur.com/dufsbHS.png

**Comment by markstory** [comment]
How can someone reproduce the error you were having?

**Comment by HoiJean** [comment]
By calling formatResults method, i have sample code:

public function findRecent(Query $query, array $options = ['status' => 0])
{
		return $query->where(['is_done' => $options['status'] ])
					 ->order(['modified' => 'DESC'])
					 ->formatResults(function ($results, $query)
					 {
					 	return $results->map(function ($row)
					 	{
					 		$timeCreated = new Time($row->created);
					 		$timeUpdated = new Time($row->modified);

					 		$row->created = $timeCreated->timeAgoInWords();
					 		$row->modified = $timeUpdated->timeAgoInWords();
					 		$row->todo = htmlspecialchars($row->todo);

					 		return $row;
					 	});
					 }, null);
	}

**Comment by markstory** [comment]
Thanks I will try reproducing the error.

**Comment by lorenzo** [comment]
formatResults does not take the query as second argument, you need to remove that
