### ISSUE TITLE
Found unused parameter in Query::update()

### ISSUE THREAD

**Issue by StewEucen** [cakephp/cakephp#6458]
I found unused parameter in Query::update() of CakePHP 3.0.2.
$table of param is not used in the method.

File: Cake\ORM\Query.php
Line: 740

original source:

    public function update($table = null)
    {
        $table = $this->repository()->table();
        return parent::update($table);
    }

should be as follows.

    public function update($table = null)
    {
        $table = $table ?: $this->repository()->table();
        return parent::update($table);
    }

**Comment by dereuromark** [comment]
That sounds about right. Can you make a PR with the suggested change please?

**Comment by StewEucen** [comment]
@dereuromark
Thank you for your reply. I use GitHub for the first time, and learn GitHub's custom in here.
I make a pull requests about this issue.

**Comment by StewEucen** [comment]
@dereuromark
I made pull requests about this issune.

https://github.com/cakephp/cakephp/pull/6460
Is it correct? If so, I will close this issue.

**Comment by ndm2** [comment]
Isn't the ORM query builder ment to be kind of bound to a specific repository (even though it can be changed on the fly)? I mean, if a query is created from table `X`, then why would one use it to update or delete (has an unused table parameter too) something in table `Y`? If one needs to act on table `Y`, then why not simply create a query from that specific table instead?

**Comment by lorenzo** [comment]
The reason the is an argument is that it extends the lower-level Database\Query class. In the future I want to use this parameter to allow the multi-table update sql variation

**Comment by StewEucen** [comment]
Thanks.
