### ISSUE TITLE
@return $this is not proper phpDoc declaration of return type.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#6461]
There are 129 occurrences of `@return $this` being used in the source code.

    /**
     * @return $this
     */
    public function foo()
    {
        return $this;
    }

The `@return` phpDoc tag *only* supports *types*.

A list of allowed types can be found on phpDocumentor's website for the type declaration.

http://phpdoc.org/docs/latest/references/phpdoc/types.html

The correct way to return `$this` is to use the type `self`.

    /**
     * @return self
     */
    public function foo()
    {
        return $this;
    }

Now, I would like to make a pull request to fix this, but with 129 occurrences it wasn't something I wanted to resolve in a pull requests comments.

If you accept this issue. I'll make the pull.

**Comment by ADmad** [comment]
If users of popular IDEs like phpstorm, netbeans etc. can confirm the `@return self` works then I don't see a problem updating.

**Comment by thinkingmedia** [comment]
I can only confirm phpStorm 8.0.3 works. Would love feedback from other IDE users.

Has anyone tried generating HTML docs from the source code? Maybe we need a composer task that does this.

**Comment by ADmad** [comment]
> Has anyone tried generating HTML docs from the source code? Maybe we need a composer task that does this.

http://api.cakephp.org/3.0/   Check link in footer :wink:

**Comment by thinkingmedia** [comment]
@ADmad yup, that was stupid question. lol

I'm wondering if phpDocumentator can be added to the build process for the API. So that it logs any discovered issues. I think this would have been flagged by phpDoc as invalid.

I'll have to take a look at the api-doc repo to see how it works internally.

**Comment by ADmad** [comment]
[cakephp-api-docs](https://github.com/cakephp/cakephp-api-docs) is just a fork of an old version of apigen with couple of hacks and our custom [theme](https://github.com/cakephp/cakephp-api-docs/tree/master/templates/cakephp). I am pretty sure apigen can also generate log of build process and report errors.

We would like to use the latest version of apigen but that requires updating the templates as they are not compatible with newer version of "latte" templating engine which latest version of apigen uses.

Any help with updating the templates would be appreciated.

**Comment by markstory** [comment]
If we can get a few other IDE users to let us know if `self` works, I'm fine with changing the return types documentation.

**Comment by ndm2** [comment]
@thinkingmedia Actually PhpStorm has many many many problems around return types, especially when it comes to fluent chaining.

**https://youtrack.jetbrains.com/issue/WI-17801**

Don't let the status fool you, many of the problems there still exist in one form or another.

I just gave it a go and replaced `$this` with `self` in the `ORM`, `Datasource` and `Database` packages, and pretty much immediately stumbled over problems.

For example

```php
$Articles->find()->where(['x' => 'y'])->count();
```

`count()` will be marked as non-existing as the type is being lost when invoking `where()`, it's no longer `Cake\ORM\Query`, but `Cake\Database\Query`.

```php
$Articles->find()->defaultTypes(['id' => 'integer'])->
```

After `defaultTypes()` only methods of `TypeMapTrait` are being suggested.

**Comment by lorenzo** [comment]
Yeah, I remember we changed from `self` to `$this` because of PHPStorm

**Comment by antograssiot** [comment]
initial discussion was here : https://github.com/cakephp/cakephp/issues/3787

**Comment by ADmad** [comment]
Given the previous discussion and detailed info provided by @ndm2 it seems nothing seems to change.

**Comment by ADmad** [comment]
@thinkingmedia The page from phpDoc's [manual](http://phpdoc.org/docs/latest/guides/types.html#keywords) does actually list `$this` as a keyword and any of those keywords can be used for hinting.
