### ISSUE TITLE
"composer install --optimize-autoloader" causes error

### ISSUE THREAD

**Issue by kenjis** [cakephp/cakephp#6463]
CakePHP v3.0.2

~~~
$ composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception


                                                        
  [InvalidArgumentException]                            
  Maximum number of attempts must be a positive value.  
~~~

Composer version 1.0-dev (619948864421c942dd095dfe0d5b84d805b44dc0) 2015-05-01 09:17:30

I found my previous version works fine:
Composer version 1.0-dev (2e73811211b7ea6de8de578fa50746fe679f2297) 2015-04-21 20:02:17

Is this a bug of Composer?

**Comment by ceeram** [comment]
If you have an existign application, apply this commit:
https://github.com/cakephp/app/commit/68cfee97f0d8cd8fd4b1b3a27840ca4be60a6582
else just create a new project.

2015-05-02 0:25 GMT+02:00 kenjis <notifications@github.com>:

**Comment by markstory** [comment]
Closing as this has been fixed in the app skeleton.

**Comment by kenjis** [comment]
Thank you!

I applied the commit and works fine.
