### ISSUE TITLE
Allow update on database primary keys, when specified.

### ISSUE THREAD

**Issue by jhawkwind** [cakephp/cakephp#6465]
I request that the ORM/Table allow the update of the primary key column for a row in a table, especially in cases where the primary key is a composite key that is part of a foreign key. This is useful when you want to re-assign an object and not change a parent object.

For example, if a table has "customer_id", "order_id", and "product_id" as a composite primary key in an OrderItems table, it would be more efficient to issue an UPDATE where primary key is the old one and set the new primary key for product_id if a user entered and saved the wrong product by mistake, without wiping out existing entries (in cases where there are further child table objects beyond one step) through having to do an insert/delete two step operation.

I request that in \Cake\ORM\Table in the _update() function, the following line be removed.
```php
$data = array_diff_key($data, $filterPrimaryKeys);
```

Alternatively, provide some kind of definition to allow the Primary Key filtering behavior to be overriden on update, perhaps some code in the _update() function. For example:
```php
    protected function _update($entity, $data)
    {
        $primaryColumns = (array)$this->primaryKey();
        $primaryKey = $entity->extract($primaryColumns);

        // Allow definition of Primary Keys that are updatable.
        // First obtain the list and make a copy of the primary key list.
        $writablePrimaryColumns = (array)$this->writablePrimaryKey();
        $filterPrimaryKeys = $primaryKey;
        
        foreach($writablePrimaryColumns as $primaryColumn) {
            // Put the original value where appropriate.
            $primaryKey[$primaryColumn] = $entity->getOriginal($primaryColumn);
            // Unset the filtering as we are allowing the key to be updated.
            unset($filterPrimaryKeys[$primaryColumn]);
        }
        
        $data = array_diff_key($data, $filterPrimaryKeys);
```
NOTE: I wanted to use the "extractOriginal", but it does not behave the same way as "getOriginal".

Recursion considerations may have to be made to ensure that recursive updates are also done on further child objects where appropriate and defined. Further input on this aspect is requested.

If there is some other way that CakePHP team prefers it done that achieves the same thing and the implementation of this feature would be redundant to that method, then I request, instead, that the documentation be updated to elaborate on such other method.

**Comment by markstory** [comment]
If we allow updates on primary keys how would the ORM know which parts of the composite key are safe to update and which are not? As you mentioned propagating composite key changes will also be challenging.

**Comment by thaJeztah** [comment]
>which parts of the composite key are safe to update and which are not?

If the database is designed properly, any part could be updated (and If not, should result in an error from the database). Updating the PK sounds safer to me than a delete/insert, which could lead to related records being deleted as well.

**Comment by jhawkwind** [comment]
Specifically for defining whether which composite key is safe or not, in my example, I have:
```php
$writablePrimaryColumns = (array)$this->writablePrimaryKey();
```
Which I expect it to behave like
```php
$primaryColumns = (array)$this->primaryKey();
```
except that list for ```writablePrimaryKey()``` would be for indicating what would be allowed.

I agree with both markstory and thaJeztah in their respective points. A properly designed database should then enforce the appropriate rules, be it to CASCADE the chances, block or RESTRICT the chances, or SET NULL.

However, the propagating composite key changes will still need to be handled because CakePHP is supposed to be able to handle a pseudo database kinda emulation in its own Models.

How does CakePHP handle records propagation (even without the key changes) with delete actions should probably be treated similarly. But because I haven't wrapped my mind around the whole DB/table code base, I don't have a clear picture of the pitfalls or "gotchas", and hence why I am asking for advise and insight into this regard from the experts and community.

**Comment by lorenzo** [comment]
I would not like cake to go that way, updating primary keys is always tricky and full of pitfalls. For example, in SQL Server, changing the primary key of a row requires special statements to be executed before the value is changed.

Why not use an `updateAll()` in your case instead of the save method?

**Comment by jhawkwind** [comment]
Several reasons why `updateAll()` is not the same, while it is possible that way.
* With `updateAll()` you are passing the array of parameters not the entity object.
* You cannot define associations to save associated objects.
* You cannot do a one shot that will fork the results between INSERT and UPDATE.
* Bypasses the rule checking to update child entities and relies on a DB to do it in the background.
* Of course, as documented, no event handling.
* All of the above will result in the reinvention of code for users of the framework.

However, if the CakePHP team feels that the risks outweighs the benefits of allowing it, I can understand.

**Comment by AD7six** [comment]
> For example, if a table has "customer_id", "order_id", and "product_id" as a composite primary key in an OrderItems table

A more appropriate schema for that example is for `order_items.id` to exist.

:-1: to any primary key change handling in the framework itself.

**Comment by markstory** [comment]
@AD7six I don't think a surrogate key is a great solution either. In a multitenant app that uses composite keys, adding surrogate keys negatively impacts performance with Mysql at least.

**Comment by jhawkwind** [comment]
Even if we ignore the consideration of updating child objects on a Primary Key update, I feel that at least the PrimaryKey change filtering should be allowed to be bypassed if the application programmer demands it. At the least, CakePHP should provide an option for the programmer to decide whether they want to handle the possible data integrity mess and allow updating the Primary Key, rather than just not even an option at all.

Though, as mentioned prior, a properly structured foreign key constraint on the DB side should keep things in order for a programmer asking for an override without having CakePHP do the work.

**Comment by markstory** [comment]
One option would be to allow all primary key fields to be mutable. This would remove any impediments to modifying primary key values. It would also put all of the onus around SQLServer compatibility and avoiding 'bad things' onto the end developer as well.

**Comment by lorenzo** [comment]
I'm closing this as this is not an use case we are interested in supporting. The query builder already has the tools for updating a row using arbitrary conditions and values. If there is a specific case the ORM does not cover, you can fallback to using this.
