### ISSUE TITLE
Entity methods behavior inconsistency?

### ISSUE THREAD

**Issue by jhawkwind** [cakephp/cakephp#6467]
This involves four methods in `\Cake\Datasource\EntityTrait` and how each works, their naming seem to have an unexpected behavior.

`get()` function returns the value of a single property, if a property has been changed the new values will be presented. Unchanged values are also presented.
```php
    /**
     * Returns the value of a property by name
     *
     * @param string $property the name of the property to retrieve
     * @return mixed
     * @throws \InvalidArgumentException if an empty property name is passed
     */
    public function &get($property)
```

`extract()` function returns an array of properties from the requested array of properties. Allows you to get multiple properties all at once, but same as `get()` where changed properties get the new values, and unchanged values are also presented.
```php
    /**
     * Returns an array with the requested properties
     * stored in this entity, indexed by property name
     *
     * @param array $properties list of properties to be returned
     * @param bool $onlyDirty Return the requested property only if it is dirty
     * @return array
     */
    public function extract(array $properties, $onlyDirty = false)
```

`getOriginal()` function returns the original value of a single property if changed, **and the current value if was not changed.** Behaves like `get()` in that it is a single value, but ensures only the original data is presented.
```php
    /**
     * Returns the value of an original property by name
     *
     * @param string $property the name of the property for which original value is retrieved.
     * @return mixed
     * @throws \InvalidArgumentException if an empty property name is passed.
     */
    public function getOriginal($property)
    {
        if (!strlen((string)$property)) {
            throw new \InvalidArgumentException('Cannot get an empty property');
        }
        if (isset($this->_original[$property])) {
            return $this->_original[$property];
        }
        return $this->get($property);
    }
```

Then it is expected that `extractOriginal()` would be an extension of `getOriginal()` but with the `extract()` output. Meaning, I would expect `extractOriginal()` to return an array of properties with their original values if they were changed, otherwise present me with the current value, from the requested array list of properties.

However, `extractOriginal()` only gives the original of the changed values, **and null/unset for where the values remained the same**, not as you would expect it to behave like `getOriginal()`.

```php
    /**
     * Returns an array with the requested original properties
     * stored in this entity, indexed by property name
     *
     * @param array $properties List of properties to be returned
     * @return array
     */
    public function extractOriginal(array $properties)
    {
        $result = [];
        foreach ($properties as $property) {
            $original = $this->getOriginal($property);
            if ($original !== null && $original !== $this->get($property)) {
                $result[$property] = $original;
            }
        }
        return $result;
    }
```

While I like the ability of `getOriginal()` to be able to return a value regardless of its changed state, the inconsistency and the lack of mention in some areas of the code documentation is a bit confusing. Perhaps `getOriginal()` and `extractOriginal()` can be uniformed in its behavior to be one way (provide only the original values of changed properties), and then an optional parameter flag would flip its operation the other way (provide all requested values, and the original one where it was changed)?

**Comment by markstory** [comment]
I agree that having `extractOriginal()` behave similar to `extract()` is a good idea. I can see why unmodified properties being missing is not expected.

**Comment by markstory** [comment]
Closing as I think #6472 solves the issue here. Instead of parameters that introduce modes, I've made a separate method.
