### ISSUE TITLE
Query with LIKE and OR conditions for biginteger and int types problem

### ISSUE THREAD

**Issue by dayvsonsales** [cakephp/cakephp#6470]
I have a problem when I try to run a query with LIKE and OR conditions for biginteger and int types.
In MySQL is entirely possible to make a query like this ```
"SELECT * FROM products WHERE (name LIKE '%5%' OR id LIKE '%5%')" ```
but when I run the same query through the ORM, it does not return me any data.
```php
$this->Products->find('all')->where(['id LIKE' => '%5%'])-> orWhere(['name LIKE' => '%5%'])
```
I've been watching as the query comes in MySQL and it seems that BigInteger types and int are turned into zero and therefore does not return anything. It became into something like:
```"SELECT * FROM products WHERE (id LIKE 0 OR name LIKE '%5%')"```

**Comment by markstory** [comment]
The string value is being cast into an integer by PDO as the column type and prepared statement parameter type is an int. I suspect this is the issue you're running into. You might want to try redefining the type for your where clause

```php
$query->where(['id LIKE' => '%5%'], ['id' => 'string'])
```

**Comment by dayvsonsales** [comment]
Thanks, that helped me a lot. But I tried to use this type of change in the "condition" of the find method and not getting the same result, the problem continued.
I tried:

```php
$this->Products->find('all', [
		    'conditions' => [['id LIKE' => '%5%', ['id' => 'string']], ['name LIKE' => '%5%']]
]);
```
 and
```php
$this->Products->find('all', [
		    'conditions' => [['id LIKE' => '%5%', 'id' => 'string'], ['name LIKE' => '%5%']]
]);
```
I did not get the same result, the debug realized that he identified as another condition to the WHERE. Anyway, your reply has helped me a lot. Thank you.

**Comment by lorenzo** [comment]
Type hinting does not work when using the options array, only when calling the specific methods that accept a `$types` parameter. Keep in mind that what you are doing is probably only possible in MySQL, which cares very little about strict types, but to other databases that would be almost impossible to do.

Please use the `where()` method if you still want to force a different type for your condition.
