### ISSUE TITLE
Can't add the Html attributes to the radio button

### ISSUE THREAD

**Issue by zx4357685** [cakephp/cakephp#6478]
Hi gays,

When I add the 'style' attribute into the radio button like this:

    echo $this->Form->radio('demo',['y', 'n'],['style'=>'width:20px;','default' => 0])

then cake will show me:

    <label for="demo-0"><input type="radio" name="demo" value="0" id="demo-0" checked="checked">y</label><label for="demo-1"><input type="radio" name="demo" value="1" id="demo-1">n</label>

the 'style' is disappeared 

So it is with the other Html attributes

And I think the problem in Cake\View\Widget\RadioWidget.php function _renderInput()

Check it, please ,thank you!

**Comment by markstory** [comment]
Closing as arbitrary attributes can only be included in the expanded format of options. I'll update the documentation to include an example of this as there isn't one right now.

**Comment by zx4357685** [comment]
@markstory

**Comment by markstory** [comment]
Docs updated in cakephp/docs#2698
