### ISSUE TITLE
Association and custom finder

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#6480]
Hi guys, got an issue with custom finders when i try to call them directly on an association table.

if i'm trying this:
```php
// in my controller
$this->Zones->ZoneTypes->find('all')
  ->where(['customer_id' => 1])->andWhere(['name' => 'City'])->first()->toArray();
```

this code above works fine but if i package the query in a custom finder like this:

```php
// in my controller
$this->Zones->ZoneTypes->find('city');

// in ZoneTypesTable
public function findCity(Query $query, array $options)
    {
        $options += [];
        return $query->find('all', $options)
            ->where(['customer_id' => 1])
            ->andWhere(['name' => 'City'])
            ->first()
            ->toArray();
    }
```

it send me a Fatal error **Call to a member function where() on a non-object**

Hope you are able to understand my poor english, ty

**Comment by lorenzo** [comment]
Finders are required to return the Query object, you are returning an array in that example.

**Comment by GLacourt** [comment]
Ok it seems clear, also it was the `first()` method who kill me :) thx
