### ISSUE TITLE
3.x returning ajax requests require view rendered, many iterations

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#6484]
I figured that per https://github.com/cakephp/cakephp/issues/3135 the response has to be response object. However, when a request is sent via ajax and a string is returned, it get's things done.
Psuedo :

    if ( this->request->is 'Ajax' )
          then do computation
          return JSON string
    stop executing further.

Currently, we have to set the layout to ajax and then set variable in views and that view is further rendered.

Did we profile?

**Comment by ADmad** [comment]
Returning json strings does not require any template rendering if you use serialization feature of JsonView.
