### ISSUE TITLE
Datetime i18n issue

### ISSUE THREAD

**Issue by a-wenzel** [cakephp/cakephp#6486]
Hi,

i got a rly strange 'bug'. i store my dates as datetime in my db in my debugkit i got the right value but if i output it i got my date +1 Year but only when my date is:

2014-12-29 00:00:00 got 2015-12-29 00:00:00
2014-12-30 00:00:00 got 2015-12-30 00:00:00
2014-12-31 00:00:00 got 2015-12-31 00:00:00

is it 2014-12-28 00:00:00 or 2015-01-01 00:00:00 my output is right.

Any ideas?

Thanks

Edit: My CakePHP Version is 3.0.3.

![code](https://cloud.githubusercontent.com/assets/7287128/7471615/8b2bd58e-f329-11e4-9297-2c737d4112f5.JPG)
![db](https://cloud.githubusercontent.com/assets/7287128/7471616/8b30742c-f329-11e4-9cac-92896f6bb36d.JPG)
![debugkit](https://cloud.githubusercontent.com/assets/7287128/7471617/8b35dd90-f329-11e4-9837-2687f1481cbb.JPG)
![output](https://cloud.githubusercontent.com/assets/7287128/7471618/8bbf0b4c-f329-11e4-812d-8cee0faac060.JPG)

**Comment by markstory** [comment]
Have you tried using any of the other formatting methods on the datetime object? Are they consistent with the database value or the current output you are seeing?

**Comment by thinkingmedia** [comment]
What version of PHP are you using?

**Comment by a-wenzel** [comment]
@markstory ive tried many other formatting methos same result.

@thinkingmedia PHP Version 5.3.28-nmm2

**Comment by thinkingmedia** [comment]
I haven't looked at the code, but I'm thinking this is a timezone issue.

What timezone do you have set in the config for CakePHP, and what timezone do you have set in your PHP.INI.

Reference: http://php.net/manual/en/datetime.configuration.php#ini.date.timezone

**Comment by a-wenzel** [comment]
hi @thinkingmedia,

both are UTC.

![timezone](https://cloud.githubusercontent.com/assets/7287128/7473968/e8d9e8d2-f33e-11e4-944c-047a9361c44e.JPG)
![timezone_cake](https://cloud.githubusercontent.com/assets/7287128/7473969/e8ddf2a6-f33e-11e4-8934-2bf717c11716.JPG)
![bootstrap](https://cloud.githubusercontent.com/assets/7287128/7474099/82c429f8-f33f-11e4-9497-36ca453426ff.JPG)

**Comment by lorenzo** [comment]
What is the value that is stored in your database? Can you also paste the code you are using to display the date, I'd like to see what is around that code.

**Comment by lorenzo** [comment]
did you set your own  `Time::toStringFormat()` ?

**Comment by thinkingmedia** [comment]
@lorenzo he already shared that code in the original post.

**Comment by a-wenzel** [comment]
@lorenzo i didnt set any custom things. only placed

use Cake\I18n\Time;

in every controller but it also didnt work without that line.

**Comment by thinkingmedia** [comment]
@a-wenzel can you do this where you output the date in the view

      <?= date('e') ?>

That will tell use what timezone date is using.

**Comment by lorenzo** [comment]
@thinkingmedia I asked again because I suspect there is more.

@a-wenzel Waiting for the actual values from the database :)

**Comment by a-wenzel** [comment]
@thinkingmedia 
![date-e](https://cloud.githubusercontent.com/assets/7287128/7474407/80aa0b18-f341-11e4-9ca4-f158aa742a29.JPG)

@lorenzo 
The Database value is still "2014-12-31 00:00:00" my code around is not very spectacular

<code>

                                <p><span>Kundennummer:</span> <?= $customer->id; ?></p>

                                <p><span>Außendienst:</span> <?= $customer->sales_force; ?></p>

                                <p><span>Vertragsstatus:</span> <?= $customer->contract; ?></p>

                                <p><span>Profilseite:</span><?php if ($customer->profile_url) { ?>
                                    <a href="http://<?= $customer->profile_url; ?>" target="_blank">Hier
                                        Klicken</a>
                                </p>
                                <?php } ?>

                                <p><span>Vertragsbeginn:</span> <?= $customer->contract_start; ?></p>

                                <?php if (isset($customer->contract_end)) { ?>
                                    <p><span>Vertragsende:</span> <?= $customer->contract_end; ?></p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
</code>

![db](https://cloud.githubusercontent.com/assets/7287128/7474601/b42b1f80-f342-11e4-8122-eea75f6d5285.JPG)

**Comment by lorenzo** [comment]
Something is not clear to me, how are you doing for displaying the date without the time?

**Comment by a-wenzel** [comment]
@lorenzo sorry guys my bad you are right i had in my appcontroller.php

<code>

use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\I18n\Time;
Time::$defaultLocale = 'de-DE';
Time::setToStringFormat('dd.MM.YYYY');
</code>

if i kick setToString out my output gets right... mhmm... why doenst that work?

Thanks

**Comment by lorenzo** [comment]
YYYY means "year of week year" which is not what you want. Use a single `y` instead

http://userguide.icu-project.org/formatparse/datetime

**Comment by a-wenzel** [comment]
... im so sorry.

Thank u guys!
