### ISSUE TITLE
3.x FormHelper no way to create form without action

### ISSUE THREAD

**Issue by btaens** [cakephp/cakephp#6488]
There doesn't seem to be a way to create an actionless form short of not using FormHelper.

**Comment by dereuromark** [comment]
Can you elaborate what you mean? All forms are inside a view, which needs an action to be invokable.

**Comment by btaens** [comment]
Ah, term confusion. I'm sorry, I meant the form's attribute action, as in ``<form action="url">``, not a controller action.
In my case, I'm trying to wire up a CakePHP back-end to an AngularJs front-end. AngularJs however requires me to give the form an ``ng-submit`` attribute instead of an action attribute, otherwise it won't prevent the browser from posting as it would in a normal form.

**Comment by josegonzalez** [comment]
Seems in HTML4 its [required](http://www.w3.org/TR/html401/interact/forms.html) but not in [HTML5](https://html.spec.whatwg.org/multipage/forms.html#attr-fs-action).

**Comment by thinkingmedia** [comment]
@btaens call `$this->Form->create()` but don't output the results, then create a `<form ng-submit>` tag in the view.

I would also like to disable actions for forms as well. This should be an allowed feature. It has nothing to do with valid HTML markup. It's about having control.

**Comment by dereuromark** [comment]
I am sure we can find a less hacky solution. IMO bool `false` passed for "action" could easily deactivate that part of the form attributes.

**Comment by ADmad** [comment]
@btaens Why use the form helper instead of just straight up HTML?  If the angular frontend communicates with REST backend none of the features provided by FormHelper are going to be useful.

Also in general a form without action attribute won't be usable with SecurityComponent. The request will be blackholed as the url is used when generating token.

**Comment by dereuromark** [comment]
@ADmad I think the ease of the FormHelper can still be valuable.
Also, in that case one wouldn't use the security component anyway :)

**Comment by ADmad** [comment]
> Also, in that case one wouldn't use the security component anyway :)

True, though there isn't a need to use any PHP to make a angularjs frontend :)

**Comment by btaens** [comment]
@ADmad From a templating standpoint, I can use FormHelper to decide what type of inputs should be created based on the model, and do a whole bunch of custom templating. This is an application with over 200 controllers, so doing it by hand gets very problematic if I wanna modify a widget later on.

CakePHP actually makes a great back-end for AngularJS, after some wiring I've managed to set up.
I understand keeping to HTML standards, but when someone specifically turns off actions or url, sets it to false, I think they're doing it on purpose, and aren't worrying about specifications.

**Comment by dereuromark** [comment]
Closing as PR is open.
