### ISSUE TITLE
Handle validation for nested inputs in modelless Forms

### ISSUE THREAD

**Issue by evxzibit** [cakephp/cakephp#6496]
Good day,

I will be nice if we could validate nested inputs with modelless forms.
For example: $this->Form->input('comments.0.comment');

'comment' can not be validated at the moment.

Thank you

**Comment by lorenzo** [comment]
This would also help with validating properties for the elastic-search plugin

**Comment by markstory** [comment]
It certainly would.

**Comment by markstory** [comment]
Closing as #6510 is open now.
