### ISSUE TITLE
The Cakephp 3 Translate Behavior does not save value '0' into i18N table.

### ISSUE THREAD

**Issue by bahamastudio** [cakephp/cakephp#6497]
I have couple of fields that needs to be translated. When content of translated field is set to 0 translate behavior does not save 0 value into i18n table. When I am changing content of translated field to 1 or any other sign everything is ok. It seems that the Translate behavior treats 0 like empty value.

**Comment by dereuromark** [comment]
Probably a `notEmpty()` instead of a `isset()` or `=== ''` check somewhere along the line.

**Comment by lorenzo** [comment]
@bahamastudio would you be able to submit a fix for this?

**Comment by bahamastudio** [comment]
It seems that this issue was related with #6498 Please create Invalid label for this issue.
