### ISSUE TITLE
Cakephp 3 Fatal error: Cannot redeclare class Cake\Model\Behavior\TranslateBehavior 

### ISSUE THREAD

**Issue by bahamastudio** [cakephp/cakephp#6498]
I have two models Products and ProductMedias inside products plugin.  Products hasMany ProductMedias
I need both of them to use Translate Bheavior
When translate behavior is attached to the Products Table and ProductMedias Table I receive 
Fatal error: Cannot redeclare class Cake\Model\Behavior\TranslateBehavior in \src\Model\Behavior\TranslateBehavior.php on line 463

When Translate behavior is not attached to the ProductMedias Table everything is ok.
Product Entity and ProductMedia Entity are using TranslateTrait.

## Products Table:
<?php
namespace Products\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Products\Model\Entity\Product;

class ProductsTable extends Table
{

    public function initialize(array $config)
    {
        $this->table('products');
        $this->displayField('title');
        $this->primaryKey('id');
	$this->addBehavior('Translate', [
			'fields' => ['title',content','description']
	]);

## ProductMedias Table:
<?php
namespace Products\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Products\Model\Entity\ProductMedia;

class ProductMediasTable extends Table
{

    public function initialize(array $config)
    {
        $this->table('product_medias');
        $this->displayField('title');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
		$this->addBehavior('Translate', [
			'fields' => ['title','description']
		]);

**Comment by lorenzo** [comment]
It looks like you copied the TranslateBehavior class to your application.

**Comment by ADmad** [comment]
Also line [463](https://github.com/cakephp/cakephp/blob/3.0.3/src/ORM/Behavior/TranslateBehavior.php#L463) is a comment in latest 3.0.3 release so you seem to be using an older release. Please upgrade.

**Comment by bahamastudio** [comment]
Thank you lorenzo. Yes I did. After removing TranslateBehavior from application everything is ok.
