### ISSUE TITLE
RFC - Console macros

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#6499]
Creating reusable blocks of console output code is not easy right now, and with a few improvements we can provide a simple, extensible API for building console output macros. [CLImate](http://climate.thephpleague.com/terminal-objects/table/) is a good example of how I think this could be approached.

## Console Macro classes

Console macros would be simple classes that implement an ``output`` method. The arguments to this method would depend on the macro object, and no interface would be enforced. Macro classes would be accessed from the `ConsoleIo` instance that all shells have access to:

```php
// In a shell or task
$this->_io->macro('table', $headers, $rows);

// or via __call
$this->_io->table($headers, $rows);
```

Under the hood the `macro` does the following:

* Uses the ConsoleMacroRegistry to locate the macro class.
* The class of the macro would be expected to be `App\Shell\Macro\${name}Macro`.
* An instance would be created with the current ConsoleIo instance and added to the registry.
* The instance's `output()` method would be called.

### Built in Macros

We could provide a small selection of macros to start with and expand as the community needs more. To start with I propose:

* Table - Create well formatted tables. This is already needed in the RouteShell.
* Progress - Create single line progress bars.

### Macro Conventions

* Macros would live in `App\Shell\Macro` and have the `Macro` suffix.
* Macros need to implement `output($args)`
* Macros get the ConsoleIo instance in their constructor.

## Todo

* [x] Build TableHelper.
* [x] Build ProgressHelper.
* [x] Update documentation.

**Comment by lorenzo** [comment]
Could we map the macro name to a method name?

**Comment by markstory** [comment]
@lorenzo What do you mean? Would macros have multiple methods that render output?

**Comment by lorenzo** [comment]
Instead of `$this->_io->macro('table', $args)` do `$this->_io->table(...$args)`

**Comment by antograssiot** [comment]
I was thinking also to what @lorenzo suggest. Sounds nicer to use...

**Comment by jippi** [comment]
Is macro a good name for them? Seem like its just a Shell element ? :) or Shell Partial

**Comment by lorenzo** [comment]
@markstory Actually I think I agree  with @jippi 
 We could use another name for this feature, maybe Shell helpers?

**Comment by markstory** [comment]
I called them macros as they reminded me of twig macros. However, I am happy to rename them. I worry that reusing Helpers will create some confusion between view helpers.

**Comment by lorenzo** [comment]
@markstory ShellHelpers?

**Comment by markstory** [comment]
I'm ok with ShellHelper. So we would end up with

```php
namespace App\Shell\ShellHelper;

class TableShellHelper extends ShellHelper
{}

$this->_io->helper('table', $stuff);
$this->_io->table($stuff);
```

Does that seem decent?

**Comment by jadb** [comment]
I personally prefer @jippi's 'Partial' over 'ShellHelper' because it's shorter and doesn't sound like the view 'Helper'. Thoughts?

**Comment by markstory** [comment]
Is reusing Helper all that bad? I was originally not for it, but there will be a Shell namespace in front of it. We currently have 2 `Request` classes and that doesn't seem to confuse people. Perhaps two parallel Helper trees won't either.

**Comment by lorenzo** [comment]
@markstory I'm ok with just Helper.

**Comment by jippi** [comment]
I'm fine with Helper too, for the record :)

**Comment by jadb** [comment]
Good, at least we agree on it being too long. I can live with Helper, does similar job as for the view and namespace should be enough as @markstory pointed out.

**Comment by markstory** [comment]
Ok, I'll update the code to use Helper then.

**Comment by markstory** [comment]
ProgressHelper done in #6618, docs done in cakephp/docs#2775.

**Comment by garethellis36** [comment]
I would find this concept useful in 2.x as well - would you consider a PR to back-port this feature?

**Comment by markstory** [comment]
@garethellis36 Sure if someone were to do the work, this would be a good candidate for 2.8.

**Comment by garethellis36** [comment]
See PR #7767
