### ISSUE TITLE
RFC - Make serialization the default behavior for JsonView

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#6500]
Currently you need to explicitly set `_serialize` to turn on serialization in JsonView. IMO serialization should be default behavior and one should have to optout instead of optin if they need template rendering.

Also a lot of newbies struggle to understand how to properly set the actual view vars and the `_serialize` var. Perhaps we can make setting `_serialize` optional and default all view vars expect the special ones prefixed with underscore should be used for serialization. This will greatly simply usage. If that's not desirable at least allow setting `_serialize` to `true` to achieve same. Allowing to set `_serialize` to `true` could be done in 3.0 itself.

**Comment by bravo-kernel** [comment]
That would be awesome, even more lean controllers

**Comment by markstory** [comment]
Setting `_serialize` to `true` seems reasonable to me. Serializing all view variables by default and not using views would have to wait until 3.1.0 at the earliest.

**Comment by ADmad** [comment]
Boo.. There's  a [test case](https://github.com/cakephp/cakephp/blob/3.0.3/tests/TestCase/View/JsonViewTest.php#L114) which expects return value to be null if `_serialize` is `true`. Though I don't see why someone would actually use that.

**Comment by ADmad** [comment]
Closing as PR is open.
