### ISSUE TITLE
Sqlserver driver cannot describe View

### ISSUE THREAD

**Issue by cburch-mmsd** [cakephp/cakephp#6501]
MSSQL in Cakephp 3. I defined a UsersTable class to use a view in Sqlserver called 'vUser'. I receive the error "Cannot describe vUser. It has 0 columns." Looking at the generated SQL, this is because it is only looking in the sys.[tables] system view to query the metadata. Here is the original SQL:

```
SELECT DISTINCT
 AC.column_id AS [column_id]
,AC.name AS [name]
,TY.name AS [type]
,AC.max_length AS [char_length]
,AC.precision AS [precision]
,AC.scale AS [scale]
,AC.is_identity AS [autoincrement]
,AC.is_nullable AS [null]
,OBJECT_DEFINITION(AC.default_object_id) AS [default] 
FROM sys.[tables] T 
    INNER JOIN sys.[schemas] S ON S.[schema_id] = T.[schema_id]
    INNER JOIN sys.[all_columns] AC ON T.[object_id] = AC.[object_id]
    INNER JOIN sys.[types] TY ON TY.[user_type_id] = AC.[user_type_id]
WHERE T.[name] = 'vUser' AND S.[name] = 'dbo'
ORDER BY column_id
```

Here is SQL that instead looks at the sys.[objects] system view first and then joins to the table or view based on the [object_id]:

```
SELECT DISTINCT
 AC.column_id AS [column_id]
,AC.name AS [name]
,TY.name AS [type]
,AC.max_length AS [char_length]
,AC.precision AS [precision]
,AC.scale AS [scale]
,AC.is_identity AS [autoincrement]
,AC.is_nullable AS [null]
,OBJECT_DEFINITION(AC.default_object_id) AS [default] 
FROM sys.[objects] O
    INNER JOIN (
        SELECT [object_id], [schema_id] from sys.[tables]
        UNION
        SELECT [object_id], [schema_id] from sys.[views]
    ) AS T on O.[object_id] = T.[object_id]
    INNER JOIN sys.[schemas] S ON S.[schema_id] = T.[schema_id]
    INNER JOIN sys.[all_columns] AC ON O.[object_id] = AC.[object_id]
    INNER JOIN sys.[types] TY ON TY.[user_type_id] = AC.[user_type_id]
WHERE O.[name] = 'vUser' AND S.[name] = 'dbo'
ORDER BY column_id
```

I'm not sure if joining to sys.[tables] or sys.[views] is even necessary; here is SQL that just uses sys.[objects]:

```
SELECT DISTINCT
 AC.column_id AS [column_id]
,AC.name AS [name]
,TY.name AS [type]
,AC.max_length AS [char_length]
,AC.precision AS [precision]
,AC.scale AS [scale]
,AC.is_identity AS [autoincrement]
,AC.is_nullable AS [null]
,OBJECT_DEFINITION(AC.default_object_id) AS [default] 
FROM sys.[objects] O
    INNER JOIN sys.[schemas] S ON S.[schema_id] = O.[schema_id]
    INNER JOIN sys.[all_columns] AC ON O.[object_id] = AC.[object_id]
    INNER JOIN sys.[types] TY ON TY.[user_type_id] = AC.[user_type_id]
WHERE O.[name] = 'vUser' AND S.[name] = 'dbo'
ORDER BY column_id
```

I write my apps against legacy/third party databases, so I use views a lot. It would be nice if I could continue using CakePHP but I don't know enough about it to fix this myself.

**Comment by markstory** [comment]
Does sys.views provide the same column names as sys.tables?  If it does we can easily reflect on both. I'm not very fluent in SQLServer, but am happy to update the schema reflection query if your queries will work with views + tables.

**Comment by cburch-mmsd** [comment]
Unfortunately sys.objects, sys.tables and sys.views do not have the same columns; they do all have the columns used in Database/Schema/SqlserverSchema (name, object_id, schema_id, is_ms_shipped). I don't know if that's enough.

Also in SqlserverSchema, the SQL in listTablesSql($config) would have to be changed to:
```
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = ?
    AND TABLE_TYPE = 'BASE TABLE'
UNION
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = ?
ORDER BY TABLE_NAME
```

I was able to successfully run all the SQL in SqlserverSchema by replacing sys.tables witih sys.objects and then limiting sys.objects.[type] IN ('U','V') to limit access to USER_TABLEs and VIEWs.

**Comment by markstory** [comment]
One reason we couldn't use `information_schema.tables` was that it was lacking necessary information, notably the autoincrement property if I remember correctly. If all the columns we need for schema reflection are present in sys.objects for both views and tables, that should be enough.

**Comment by tgr0ss** [comment]
I'm able to call views now using TableRegistry::get by using the above slightly modified Cake\Database\Schema\Sqlserver  which can be found @ http://pastebin.com/fvTQQVJm

While this appears to have completely broken the cmd line bake(see below)  it's a small price to pay i suppose.

---BAKE Error----

E:\cake3\app>bin\cake bake controller


Welcome to CakePHP v3.0.3 Console
---------------------------------------------------------------
App : src
Path: E:\cake3\app\src\
---------------------------------------------------------------
Possible controllers based on your current database:
Exception: SQLSTATE[07002]: [Microsoft][SQL Server Native Client 11.0]COUNT field incorrect or syntax error in [E:\cake
3\app\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php, line 169]
2015-05-12 16:44:41 Error: [PDOException] SQLSTATE[07002]: [Microsoft][SQL Server Native Client 11.0]COUNT field incorrect or syntax error
Stack Trace:
#0 E:\cake3\app\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): PDOStatement->execute(NULL)
#1 E:\cake3\app\vendor\cakephp\cakephp\src\Database\Connection.php(243): Cake\Database\Statement\StatementDecorator->ex
ecute()
#2 E:\cake3\app\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(64): Cake\Database\Connection->execute('SELEC
T TABLE_NA...', Array)
#3 E:\cake3\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(807): Cake\Database\Schema\Collection->listTables()
#4 E:\cake3\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(782): Bake\Shell\Task\ModelTask->_getAllTables()
#5 E:\cake3\app\vendor\cakephp\bake\src\Shell\Task\ControllerTask.php(246): Bake\Shell\Task\ModelTask->listAll()
#6 E:\cake3\app\vendor\cakephp\bake\src\Shell\Task\ControllerTask.php(58): Bake\Shell\Task\ControllerTask->listAll()
#7 [internal function]: Bake\Shell\Task\ControllerTask->main()
#8 E:\cake3\app\vendor\cakephp\cakephp\src\Console\Shell.php(391): call_user_func_array(Array, Array)
#9 E:\cake3\app\vendor\cakephp\cakephp\src\Console\Shell.php(386): Cake\Console\Shell->runCommand(Array, false)
#10 E:\cake3\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, tru
e)
#11 E:\cake3\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()

#12 E:\cake3\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#13 E:\cake3\app\bin\cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#14 {main}

**Comment by markstory** [comment]
Having a totally broken CLI is not really a viable option unfortunately. Thanks for the patch though the modified queries might be adaptable into code that can work in all the contexts we need it to work in.

**Comment by tgr0ss** [comment]
I don't disagree, I switch the file to do any scaffolding. Since I don't use it completely.  What I can tell you though is the above mentioned is working with both loadModel and TableRegistry with sql tables/views
Also have not had any issues today with the  FOC Crud Plugin or AdMad's JWT.
At least it's a start

**Comment by cburch-mmsd** [comment]
I'm sorry, I wish I could contribute but I really don't know how.

If someone could just change sys.[tables] to sys.[objects] in /vendor/cakephp/cakephp/src/Database/Schema/SqlserverSchema.php I'd be super happy.

**Comment by markstory** [comment]
@cburch-mmsd I don't think the change is that simple, as from the other comments in this thread that will cause bake to fail which isn't acceptable as a solution.

**Comment by tgr0ss** [comment]
@markstory I finally got annoyed enough to make it work with tables and views and now you can fully use it to bake views and tables as well as assign all the proper associations.   Also I should note that this is working 'dbo' schema, and don't think it'll apply to other schemas w/out modification.  Can clean up if need be.. <b>Link to working version: http://pastebin.com/snVM3sFd </b>

**Comment by markstory** [comment]
@tgr0ss Looks like the hardcoded 'dbo' strings could be replaced with placeholders.  I'm guessing that your changes are the blocks of commented out code?

Using a UNION is a nice solution. Would you be willing to open a pull request with these changes? I could help add some tests.

**Comment by tgr0ss** [comment]
@markstory Will do as soon as I can, commented out was some of the original and some trial and error.  Was a long day, will clean up and submit as soon as I can.

**Comment by markstory** [comment]
@tgr0ss Awesome!

**Comment by tgr0ss** [comment]
@markstory pull request submitted, please let me know if there's anything else I can do.

**Comment by tgr0ss** [comment]
@markstory Took me a minute to get the pull request stuff down, anyway I've resubmitted finally and it's working with Wildcards now.

**Comment by markstory** [comment]
@tgr0ss Awesome. Closing as a pull request is open now.

**Comment by qdkid** [comment]
when will tgr0ss' awesome change be included in CakePHP 3 distribution? I have same trouble with 3.2.8. I used his solution and it works!

**Comment by markstory** [comment]
@qdkid The pull request needs some tests, but otherwise looks reasonable.
