### ISSUE TITLE
Add non-recursive option to Folder::copy() and Folder::move()

### ISSUE THREAD

**Issue by daniel-lang** [cakephp/cakephp#6505]
I have a folder structure that looks like this:
```
import
  +- new
  |     +- file1111.json
  |     +- task1
  |     |     +- file100024.json
  |     +- task2
  |           +- file200024.json
  |
  +- finished
        +- root
        |     +- 2015-05-06_10:00:00
        |     |    +- file1.json
        |     +- 2015-05-07_12:17:00
        +- task1
        |     +- 2015-05-06_10:02:00
        |     +- 2015-05-07_12:17:00
        +- task2
              +- 2015-05-07_12:17:00
            
```

Now, I would like to move all the json files in the import directory to `/import/finished/root/2015-05-07_12:17:00`, the files for task1 to `/import/finished/task1/2015-05-07_12:17:00` and the files for task2 to`/import/finished/task2/2015-05-07_12:17:00`.

With the `Folder::move()` method, I would move the complete structure to `/import/finished/root/2015-05-07_12:17:00` instead of only the files in the directory.

It would be great if `Folder::copy()` and `Folder::move()` had an option `recursive` with is by default `false`.

**Comment by dereuromark** [comment]
In that case it might be easier to just use Folder::find() and iterate over them manually.
Alternatively you can also use the iterators directly.

**Comment by daniel-lang** [comment]
That is true, I just thought while looking at the code that powers copy() and also move() that it should be easy to add this option and it might be useful for other things/people.

**Comment by dereuromark** [comment]
Closing as PR is now open.
