### ISSUE TITLE
Stop using Carbon?

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6509]
I went to the Carbon project to see what's new there and found this jewel:

https://github.com/briannesbitt/Carbon/blob/master/composer.json#L21

As it stands now I'm not too happy with our dependency on carbon for several reason:

* We have failed a communicating the API that is available
* Bugs are fixed at a slow pace
* It could definitely be faster
* Introduces a big chain of dependencies

I also have some ideas of how it could be done better:

* Move all methods to a trait
* Implement our own DateTime (and in the future DateTimeImmutable) using the trait
* Reduce  internal method calls that make it slow
* Offer I18n as a separate thing as we already do.

This will also give us the excuse to properly document the API in our docs.

**Comment by josegonzalez** [comment]
Can we offer this as a standalone datetime library? Is there an alternative to carbon that we can use?

**Comment by lorenzo** [comment]
That was my idea @josegonzalez

**Comment by dereuromark** [comment]
Awesome idea. Just what I had in mind from the beginning :) Carbon was a great library, but yeah, way too slow pace and not necessarily going in the right directions. Having a `cakephp/carbon` or sth is the way to go :+1:

**Comment by markstory** [comment]
I am ok with forking carbon and optimizing/simplifying the internals. Reimplementing an API compatible alternative is also a good option and would allow us to provide immutable variants like @lorenzo mentioned.

In either scenario we should aim to have a library with 0 dependencies.

**Comment by kicaj** [comment]
:+1: for @lorenzo idea:)

**Comment by jadb** [comment]
:+1:  just because it started relying on other dependencies.

**Comment by sukihub** [comment]
:+1: for immutable `Time` (I just hate that I have to `->copy()` it every time I want to add an hour or change the timezone or ...). I'm however not a big fan of creating yet another PHP (DateTime) library. We all would benefit from 1 really good DateTime library more than from 5 different ones. Can't we just contribute to Carbon? Maybe suggest them to split it into two libraries (core and i18n stuff)?

**Comment by dereuromark** [comment]
@sukihub The problem so far was that is was a one-man show with months (> 4 even with critical bugs) of activity break, which is unacceptable for such a widely used library of that magnitude IMO.
We reached out multiple times in the past, offered help and even co-management. To be fair, it got better, but it is still far from ideal. Thus branching off might be a justified solution.

**Comment by sukihub** [comment]
@dereuromark Oh, I guess I just never imagined that somebody wouldn't want help with an open-source project, silly me :-) Glad to hear you already tried that and sorry I doubted you all :-)

**Comment by zoghal** [comment]
:+1: good idea

**Comment by ionas** [comment]
The fewer dependencies the better.
If at the same time you CAN decouple things without having to add too much glue, great.

**Comment by markstory** [comment]
@ionas I wouldn't expect any more glue than we currently have with carbon.

**Comment by davidyell** [comment]
As long as it doesn't break BC, I'm :+1:

**Comment by burzum** [comment]
:+1:

**Comment by ravage84** [comment]
Sad to see this failing, but  :+1:

**Comment by drmonkeyninja** [comment]
:+1:

**Comment by andrecavallari** [comment]
So... will this standalone lib be created?

Using CakePHP 3.0 with PHP7 I get this error:

Warning (2): Declaration of Carbon\Carbon::createFromFormat() should be compatible with DateTime::createFromFormat($format, $time, DateTimeZone $object = NULL) [ROOT/vendor/nesbot/carbon/src/Carbon/Carbon.php, line 2203]

I fixed it my own hand, but just want to know more about this standalone plugin

**Comment by lorenzo** [comment]
it will, when someone gets the time to do it. Maybe you are interested @andrecavallari ?

**Comment by andrecavallari** [comment]
I already started something here, if it works I will share it

**Comment by lorenzo** [comment]
great!

**Comment by lorenzo** [comment]
@andrecavallari any progress on this?

**Comment by andrecavallari** [comment]
Not yet, still using Carbon ;(

**Comment by sdustinh** [comment]
I haven't looked into this at all (just casually commenting on an issue in my notifications) but if we are kicking around RFC ideas I would *love* support for the FormHelper datetime format in the [API Instantiation](http://carbon.nesbot.com/docs/#api-instantiation) so something like this would be easier...

```php
public function validationDefault(Validator $Validator)
{
    return $Validator
        ->add('expires', [
            'in-future' => [
                'rule' => function ($value, $context) {
                    /*
                    $value = [
                        'year' => '2015',
                        'month' => '06',
                        'day' => '15',
                        'hour' => '19',
                        'minute' => '22'
                    ];
                    */
                   
                    return $value->isFuture();
                },
                'on' => function ($context) {
                    return !empty($context['data']['expires']);
                },
                'message' => 'Expiration must be set to a future date.'
            ]
        ]);
}
```

**Comment by wisamhussain** [comment]
A standalone CakePHP Date/Time library with 0 dependencies would be ideal.

**Comment by dereuromark** [comment]
With https://github.com/cakephp/cakephp/pull/7263 limitation it is even more important to speed up this process IMO to avoid bugs being production-blockers as we cannot use the newer bugfix versions.

**Comment by lorenzo** [comment]
@markstory is there anything missing before closing this?

**Comment by markstory** [comment]
Nope.
