### ISSUE TITLE
SMTP START TLS

### ISSUE THREAD

**Issue by aritmukherjee** [cakephp/cakephp#6511]
Hi I am trying to set up smtp configuration in cakeemail. When I use phpmailer class it runs perfectly but in case of cakephp 2 it shows "SMTP Error: 530 5.7.0 Must issue a STARTTLS command first" issue.
I can't figure out the solution.
Please suggest me with a solution if possible.

**Comment by ADmad** [comment]
Show the configuration you are using.

**Comment by aritmukherjee** [comment]
Below is my smtp configuration code
public $smtp = array(
  'transport' => 'Smtp',
  'from' => array('audit.tool@ccscleaning.com' => 'My Site'),
  'host' => 'mail.securesuite.io',
  'port' => 587,
  //'timeout' => 30,
  'username' => 'audit.tool@ccscleaning.com',
  'password' => 'secret',
  'client' => null,
  'log' => false,
  'tls' =>false,
  //'charset' => 'utf-8',
  //'headerCharset' => 'utf-8',
 );

**Comment by ADmad** [comment]
Since your smtp server expects `STARTTLS` shouldn't the `tls` config be `true`?

**Comment by aritmukherjee** [comment]
So how can I ignore that issue. The smtp is enbled with tls. So I have to set TLS. Can you suggest the code I would follow. From same server I managed to send smtp mail but not with cakeemail.

**Comment by ADmad** [comment]
> So how can I ignore that issue. 

You can't just ignore it. Set `tls` true in your config.

**Comment by aritmukherjee** [comment]
I have tried with tls true. It still shows
"STARTTLS command first" error

**Comment by markstory** [comment]
What mailserver are you using? The current TLS code was developed against gmail and I've used it with postfix in the past.

**Comment by dereuromark** [comment]
We can probably close this as for all others and those email providers it works fine.
