### ISSUE TITLE
Marshaller _belongsToMany() scrambles joinData

### ISSUE THREAD

**Issue by jc-vogel** [cakephp/cakephp#6512]
When I try to merge post (with _joinData) with an existing entity, the _joinData in the entity gets scrambled. 
EG:
POST data (in $this->request->data('products')):
```
(
    [0] => Array
        (
            [id] => 40405baa-f4bc-11e4-9403-7c0507bf6b45
            [_joinData] => Array
                (
                    [price] => 10
                    [quantity] => 10
                )
        )
    [1] => Array
        (
            [description] => 100
            [price] => 100
            [_joinData] => Array
                (
                    [price] => 100
                    [quantity] => 100
                )
        )
)
```
The first one should find the correct product and update the joindata. 
The second one should create a product, and save the joindata. 

The existing project entity is found:
```
$data = $this->Projects->get($id,
            'associated' => ['Products']
        ]);
```
It is updated:
```
$data = $this->Projects->patchEntity(
                $data,
                $this->request->data(),
                ['associated' => ['Products._joinData']]
            );
```
But now the product with id: 40405baa-f4bc-11e4-9403-7c0507bf6b45 has the following joindata:
```
(
        [price] => 100
        [quantity] => 100
)
```

I found that the Marshaller creates a $records array by first adding the new rows and then the result of the query of the existing rows 
the two are merged in Marshaller.php line 302:  $records = array_merge($records, $query->toArray());
The order of this array is different from the original $data array, BUT:
line 313 and 314 expect them to be in the same order. 

I think the problem is in line 302, where the records are merged, regardless of their original order. 

I think this is a bug and could be fixed with something like: 

line 284: 
```
foreach ($data as $i => $row) { //get key from data
```
line 297:
```
$records[$i] = $this->one($row, $options); //insert new join with correct $i in $records
```
line 301+:
```
if (isset($query)) {
    $queryData = $query->toArray(); // execute query
    foreach($queryData as $queryItem){
        foreach($data as $i => $row){ // find correct key in $data for all primary keys
            $match = 0;
            foreach($primaryKey as $key => $value){
                if(isset($row[$key]) && $row[$key] == $queryItem->$key){
                    $match++;
                }
            }
            if($match === count($primaryKey)){ // if all primary keys match, insert with correct $i in $records
                $records[$i] = $queryItem;
            }
        }
    }
}
```
I guess this is a bit too nested, but something like this would result in a $records array with the same keys as the original $data array, so line 313+ would not be a problem.

**Comment by lorenzo** [comment]
Would you be able to submit a patch for this?

**Comment by jc-vogel** [comment]
yes, but my solution has three foreach loops nested... Not the nicest one...

**Comment by jc-vogel** [comment]
I have created a pull request, https://github.com/cakephp/cakephp/pull/6514
