### ISSUE TITLE
patchEntity doesn't save _joinData in the first time, but it does the second time

### ISSUE THREAD

**Issue by p3140** [cakephp/cakephp#6513]
When i do a $this->{Tablename}->patchEntity with _joinData, the first time ( when it creates the assocciation for the very first time) the _joinData doesn't save, but if i call it again for update, it does.

I fixed it hacking ORM/Table.php:

    public function patchEntity(EntityInterface $entity, array $data, array $options = [])
    {
        if (!isset($options['associated'])) {
            $options['associated'] = $this->_associations->keys();
        }
        $marshaller = $this->marshaller();
        $ret = $marshaller->merge($entity, $data, $options); // The hack
        return $marshaller->merge($entity, $data, $options);
    }

but i think this is not the propper way.

**Comment by markstory** [comment]
This is most certainly not the right solution. What request data would help reproduce this issue?

**Comment by p3140** [comment]
Before parsing:
[
	'descripcion' => 'P1',
	'cliente_id' => '1',
	'comuna_id' => '1101',
	'direccion' => '---',
	'tipo_propiedad_id' => '1',
	'operacion_id' => '1',
	'latitud' => '-10',
	'longitud' => '-10',
	'caracteristicas' => [
		(int) 0 => [
			'id' => '1',
			'_joinData' => [
				'caracteristica_id' => '1',
				'propiedad_id' => '1',
				'valor' => '1'
			]
		],
		(int) 1 => [
			'id' => '2',
			'_joinData' => [
				'caracteristica_id' => '2',
				'propiedad_id' => '1',
				'valor' => '1'
			]
		],
		(int) 2 => [
			'id' => '3',
			'_joinData' => [
				'caracteristica_id' => '3',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 3 => [
			'id' => '4',
			'_joinData' => [
				'caracteristica_id' => '4',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 4 => [
			'id' => '5',
			'_joinData' => [
				'caracteristica_id' => '5',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 5 => [
			'id' => '6',
			'_joinData' => [
				'caracteristica_id' => '6',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 6 => [
			'id' => '7',
			'_joinData' => [
				'caracteristica_id' => '7',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 7 => [
			'id' => '8',
			'_joinData' => [
				'caracteristica_id' => '8',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 8 => [
			'id' => '9',
			'_joinData' => [
				'caracteristica_id' => '9',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 9 => [
			'id' => '10',
			'_joinData' => [
				'caracteristica_id' => '10',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 10 => [
			'id' => '11',
			'_joinData' => [
				'caracteristica_id' => '11',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 11 => [
			'id' => '12',
			'_joinData' => [
				'caracteristica_id' => '12',
				'propiedad_id' => '1',
				'valor' => ''
			]
		],
		(int) 12 => [
			'id' => '18',
			'_joinData' => [
				'caracteristica_id' => '18',
				'propiedad_id' => '1',
				'valor' => ''
			]
		]
	]
]

I have to parse data with this code before it can work:
$unset = [];
          foreach($this->request->data["caracteristicas"] as $k=>$v)
          {
            if(!isset($v["_joinData"]["valor"])|| $v["_joinData"]["valor"] == ""  )
            {
              $unset[] = $k;
            }
          }
          foreach($unset as $k=>$v){
            unset($this->request->data["caracteristicas"][$v]);
          }

Data after parsing:
[
	'descripcion' => 'P1',
	'cliente_id' => '1',
	'comuna_id' => '1101',
	'direccion' => '---',
	'tipo_propiedad_id' => '1',
	'operacion_id' => '1',
	'latitud' => '-10',
	'longitud' => '-10',
	'caracteristicas' => [
		(int) 0 => [
			'id' => '1',
			'_joinData' => [
				'caracteristica_id' => '1',
				'propiedad_id' => '1',
				'valor' => '1'
			]
		],
		(int) 1 => [
			'id' => '2',
			'_joinData' => [
				'caracteristica_id' => '2',
				'propiedad_id' => '1',
				'valor' => '1'
			]
		]

**Comment by markstory** [comment]
Why are you removing the values with valor = ''?

**Comment by p3140** [comment]
valor is an optional parameter for the user, if it is filled in the form then the join table must be filled too, if it is not filled in the form then it needs to be removed from the data array (and from the join table too, but this is part of cake's magic).

**Comment by markstory** [comment]
If you remove the valor filtering does the issue persist?

**Comment by p3140** [comment]
Yes sir.

**Comment by p3140** [comment]
If i remove the valor filtering, nothing works.

**Comment by markstory** [comment]
Does valor being '' trigger validation errors? Is that why nothing works when the filtering is not included?

**Comment by p3140** [comment]
No, as far i know.

**Comment by markstory** [comment]
Ok before I try and reproduce the issue, what is the result you are currently expecting out of patchEntity()?

**Comment by p3140** [comment]
![captura de pantalla 2015-05-09 a la s 1 44 24 pm](https://cloud.githubusercontent.com/assets/10925077/7551098/e1ea716a-f652-11e4-9b93-cde4e1a5bf08.png)
I expect from this method that saves habtm's _joinData.
In the screenshots, part 1 of the form is data for table Propiedades. Part 2 of the form is data for the join table CaracteristicasPropiedades. If the value is empty or 'null', in any field of the second part of the form, then that record is ignored or deleted in case that already exists (this is the part when i parse data)
![captura de pantalla 2015-05-09 a la s 1 44 00 pm](https://cloud.githubusercontent.com/assets/10925077/7551097/da4be830-f652-11e4-8c56-4406e8d1e1f3.png)
.

**Comment by p3140** [comment]
I expect from this method that saves habtm's _joinData.
In the screenshots:
part 1 of the form is data for table Propiedades.
![captura de pantalla 2015-05-09 a la s 1 44 00 pm](https://cloud.githubusercontent.com/assets/10925077/7551133/ae908d58-f653-11e4-8308-2961f543a5b0.png)

**Comment by p3140** [comment]
Part 2 of the form is data for the join table CaracteristicasPropiedades. If the value is empty or 'null', in any field of the second part of the form, then that record is ignored or deleted in case that already exists (this is the part when i parse data)
![captura de pantalla 2015-05-09 a la s 1 44 24 pm](https://cloud.githubusercontent.com/assets/10925077/7551136/bb538a4a-f653-11e4-8a56-092088320243.png)

**Comment by p3140** [comment]
BTW, i have all this working, but with the hack mentioned in the first post. Thanks for your time.

**Comment by markstory** [comment]
Ok, I can try and reproduce the issue with what's here.

**Comment by markstory** [comment]
I wasn't able to reproduce the issue. If I used the 'parsed' data in a save operation, your modifications were not required to get the data saved correctly.
