### ISSUE TITLE
Controller doesnt get correct table for routed urls

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/cakephp#6515]
Aftear upgrading to cake php 3.0 my routes stoped to work.

Here is the route:

 $routes->connect(
        '/products/:id-:slug',
        [
            'controller' => 'products',
            'action' => 'view'
        ],
        [
            'pass' => ['id', 'slug'],
            'id' => '[0-9]+'
        ]
    );

The error: 

Error: Call to a member function get() on a non-object 
File /www/app/src/Controller/productsController.php 
Line: 29

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by rochamarcelo** [comment]
I'm not looking for help. I think it's a bug.

**Comment by ADmad** [comment]
The error shown has nothing to do with routing.

**Comment by rochamarcelo** [comment]
My normal url is /products/19393 that URL works as expected.

The routed url is /products/19393-product-name.html that URL does not work as expected, the controller does not identify the table, so $this->Products is a non-object.

**Comment by ADmad** [comment]
In routes config and file name, controller name is supposed to be in CamelCase. So `'controller' => 'Products'` and `ProductsController.php` which you don't have.

**Comment by dereuromark** [comment]
@rochamarcelo http://book.cakephp.org/3.0/en/development/routing.html

**Comment by rochamarcelo** [comment]
Ok. But I think others will get same thing when upgrading, maybe it's worse to inform in the post release  http://bakery.cakephp.org/2015/05/03/cakephp_3_0_3_released.html

**Comment by ADmad** [comment]
This is how it's supposed to work right from dev releases of 3.0 and it's documented accordingly. It's just luck that what you had worked.
