### ISSUE TITLE
QueryLogger interpolate

### ISSUE THREAD

**Issue by Baffos** [cakephp/cakephp#6516]
While Logging, Queries are going through Cake\Database\Log\QueryLogger.

Everything seems fine on smaller queries.
But caused by preg_replace() every Query with more than 10 Params seems wrongly while _interpolate()

The failure is that :c10 to :c19 gets wrongly replaced by :c1 + last number from original placeholder
same for from :c20 to :c29 replaced with :c2 + number

**Comment by lorenzo** [comment]
Closed b https://github.com/cakephp/cakephp/pull/6517
