### ISSUE TITLE
DateTime Form input: minutes to seconds, 0 to 60, 0 to empty, null to true?

### ISSUE THREAD

**Issue by jhawkwind** [cakephp/cakephp#6518]
When you enable the Form input type DateTime, and you enable the seconds field, the minutes display 00 to 59, but the seconds display is 01 to 60. It needs to be one, or the other; though 00 makes more sense in general.

```php
                <?= $this->Form->input('test',[
                    'type' => 'datetime',
                    'second' => null,
                    'label' => 'TEST',
                    'title' => 'This is the start time.',
                    'empty' => '-',
                    'default' => ''
                ]) ?>
```

![0to60_minutestoseconds](https://cloud.githubusercontent.com/assets/5790556/7546622/b9e761c8-f594-11e4-844c-d349590c5c2a.png)

Also, documentation here (http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-date-and-time-inputs) says:
> * `second` Set to `true` to enable seconds drop down.

But when you attempt to do so, you get a RuntimeException that
> Options for "second" must be an array|false|null

Though it seems `null` is the correct answer, not `true`? Or is this a different invocation path?

Also, with the above option, after a form submit, the minute field defaults to the `empty` rather than `00` field if the user select exactly `3:00:00 PM`. This issue does not occur for the hour, and obviously not for the seconds, since the seconds go from 1 to 60 rather than 0 to 59.

**Comment by lorenzo** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/6519

**Comment by xavier83ar** [comment]
Although second's options have been fixed to be the same of minutes, it still there is an issue with the correct value to set for the "second" option key. 
Although documentation indicates that 'second' => true is required to show seconds selector, doing it ends up with a RuntimeException. I know that this could be only a documentation outdated issue, but I think that it's far more intuitive having to put 'true' instead of 'null' for showing the selector. I think that this issue should be taking into consideration.

**Comment by markstory** [comment]
The following works fine for me in a cake3 app.

```php
echo $this->Form->input('created', ['second' => []]);
```

Where does the documentation say `second => true` should work?

**Comment by jhawkwind** [comment]
This was mentioned in the original issue ticket. That at the documentation here: http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-date-and-time-inputs

It says:
> * `second` Set to `true` to enable seconds drop down.

**Comment by xavier83ar** [comment]
Yeah, setting `'second' => []` works, but again, I still think that having to set an option to an empty array to making it appear isn't very intuitive.
Anyway, that's my opinion and could be subject of discussion, the issue here is to have documentation fixed to be updated with how it works.

**Comment by markstory** [comment]
Shouldn't be hard to make `second => true` work. I'll take a look.
