### ISSUE TITLE
3.x: missing email template for plugin

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#6520]
I would like to know if I found a bug or if I'm doing something wrong.
I'm trying to send an email from my plugin.

I set the template and the layout:

    $email->template('Users/change_password', 'default')

obviously the files `APP/plugins/MyPlugin/src/Template/Email/html/Users/change_password.ctp` exists. 

In this case I get the "Missing template error":

     Error: The view for UsersController::change_password() was not found.
    
    Confirm you have created the file: "Email/html/Users/change_password.ctp" in one of the following paths:
    
        APP/src/Template/Plugin/MyPlugin/Email/html/Users/change_password.ctp
        APP/plugins/MyPlugin/src/Template/Email/html/Users/change_password.ctp
        APP/src/Template/Email/html/Users/change_password.ctp

Yet it exists right where it asks me to check.

Instead, if I do so, it works:

    $email->template('MyPlugin.Users/change_password', 'default')

**Comment by lorenzo** [comment]
That is how it is supposed to work. Emails cannot be aware of the plugin in which they are being used or were generated.

**Comment by markstory** [comment]
I think the mailer feature for 3.1 fixes this as mailers are plugin aware.

**Comment by mirko-pagliai** [comment]
Thanks guys.

**Comment by mirko-pagliai** [comment]
The problem is that, as it stands, if I use a plugin that contains email templates, I cannot overwrite them from my app.

**Comment by matheusdelima** [comment]
This is simple, look this:
`` $this->set([
              'my_response' => $monthCustomer,
              '_serialize' => 'my_response'
]); ``
``$this->RequestHandler->renderAs($this, 'json');``
