### ISSUE TITLE
CollectionTrait::append call to _unwrap

### ISSUE THREAD

**Issue by sukihub** [cakephp/cakephp#6523]
This is how `CollectionTrait::append` is implemented now:

    1. public function append($items)
    2. {
    3.     $items = $items instanceof Iterator ? $items : new Collection($items);
    4.     $list = new AppendIterator;
    5.     $list->append($this);
    6.     $list->append($items->_unwrap());
    7.     return new Collection($list);
    8. }

And there are two issues with `$items->_unwrap()` call on line 6:
  1. if `$items` is an instance of `Iterator` (see line 3), it crashes, because Iterator instances usually don't have public `_unwrap` method (only `Collection` instances do),
  2. `CollectionTrait::_unwrap` method is protected, which means it can only be invoked if `$this` and `$items` are instances of same class (I wanted to append something to `\Cake\ORM\ResultSet`, it's not possible to invoke `Collection::_unwrap` from `ResultSet`).

Therefore `append` basically only works on `Collection` instances and only if an array or another `Collection` instance is being appended.

Easily solvable if call to `_unwrap` on line 6 is deleted (see https://github.com/sukihub/cakephp/commit/3a0d548e1a69eecafb788a0abe530a735238cc17). Could there be any unexpected side effects? All tests pass after the change.

**Comment by markstory** [comment]
I think the `_unwrap` call was to optimize the inner iterators. The method sniff should probably be a bit safer, as I agree its not very safe right now.

**Comment by sukihub** [comment]
I was also thinking of doing unwrap on `$items` manually if it's an instance of `IteratorIterator`. But it might make more sense to just make `_unwrap` public (and implement it like this: `while ($iterator instanceof \IteratorIterator) { ...`).

Is there a reason to optimize inner iterators? How often is there more than 1 nested? Just asking :)

**Comment by markstory** [comment]
With unwrap there is never more than one. The problem was before unwrap was added, yoy could often end up with 2 or 3 wrapped instances. Making unwrap public sounds like a reasonable solution.

**Comment by dereuromark** [comment]
Closing as PR is open.
