### ISSUE TITLE
Fixture generation broken with length defined

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6526]
But baked or not, the following should not make SQLite error:

    public $fields = [
        'id' => ['type' => 'integer', 'length' => 10],

The error thrown:
```
Warning Error: Fixture creation for "sandbox_animals" failed "SQLSTATE[HY000]: G
eneral error: 1 AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY" in
[...\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php, line 233]

Exception: Unable to insert fixtures for "Sandbox\Test\TestCase\Controller\Boots
trapControllerTest" test case. SQLSTATE[HY000]: General error: 1 no such table:
sandbox_animals in 
[...\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 254]
```

Removing the length makes it work again:

    public $fields = [
        'id' => ['type' => 'integer'],

The key difference is the (10) part, which SQLite doesnt seem to like.
```
//  working fixture
INTEGER PRIMARY KEY AUTOINCREMENT

// broken fixture
INTEGER(10) PRIMARY KEY AUTOINCREMENT
```
We should remove the length in the case of SQLite then.

**Comment by dereuromark** [comment]
Side note: Adding `'null' => false, 'default' => null` is also not a problem it seems, but adding `'unsigned' => true` is.

**Comment by dereuromark** [comment]
Possible fix: https://github.com/cakephp/cakephp/compare/master-fixture
Maybe there is a better solution, though?

**Comment by markstory** [comment]
That seems reasonable @dereuromark . Primary keys in sqlite are always a bit funny.
