### ISSUE TITLE
Containable not working with 'group' option in 2.6.x

### ISSUE THREAD

**Issue by InfinityVoid** [cakephp/cakephp#6528]
I use such containable schema:

    Rubric->hasMany->RubricCategoryNoveltiesView
    RubricCategoryNoveltiesView->belongTo->Rubric

    Array
    (
        [Category] => Array
            (
                [conditions] => Array
                    (
                        [Category.id] => 12
                    )
    
            )
        [Article] => Array
            (
                [0] => Photo
                [1] => MainCategory
            )
        [0] => Novelty
        [Slider] => Array
            (
                [0] => Photo
            )
        [RubricSliderArticlesView] => Array
            (
                [order] => RubricSliderArticlesView.article_order DESC
            )
        [RubricCategory] => Array
            (
            )
        [RubricCategoryNoveltiesView] => Array
            (
                [limit] => 4
                [order] => RubricCategoryNoveltiesView.created DESC
                [group] => RubricCategoryNoveltiesView.id
            )
    )

and there is a problem with RubricCategoryNoveltiesView, when I try to use aggregation function `'group'`. When I use it, it gaves me an error `Warning: Model "RubricCategoryNoveltiesView" is not associated with model "RubricCategoryNoveltiesView" in lib\Cake\Model\Behavior\ContainableBehavior.php on line 342`.

So I tried to debug `ContainableBehavior.php`. At line `270` I have tried to add an option `'group'` to `$options = array('className', 'joinTable', 'with', 'foreignKey', 'associationForeignKey', 'conditions', 'fields', 'order', 'limit', 'offset', 'unique', 'finderQuery');`

It made Warning dissapear, but SQL querry still don't use GROUP BY statement.

    SELECT `RubricCategoryNoveltiesView`.`rubric_id`, (...) FROM (...) AS `RubricCategoryNoveltiesView` WHERE `RubricCategoryNoveltiesView`.`rubric_id` = (107) ORDER BY `RubricCategoryNoveltiesView`.`created` DESC LIMIT 4

I don't have any guess where to debug further.

**Comment by lorenzo** [comment]
What is the find call that triggers this behavior?

**Comment by InfinityVoid** [comment]
`$contain` is equal to the schema given in first post

$this->contain($contain);
$this->find('all', ['order' => 'Rubric.position ASC']);

**Comment by lorenzo** [comment]
Oh, you mean that you tried to pass 'group' in contain?

**Comment by InfinityVoid** [comment]
Yes. I'm sorry, now I see that my description could be misleading.

**Comment by lorenzo** [comment]
That's a feature that is not supported by contain, and I'm not sure if it would be wise trying to implement it  at this point.

**Comment by InfinityVoid** [comment]
You mean that there is no point in implementing, because it is implemented in 3.0 and 2.6 branch is coming to a EOL point?

**Comment by lorenzo** [comment]
2.6 is not accepting new features, if it were to be implemented it would be 2.7.

**Comment by InfinityVoid** [comment]
So what would you suggest? Aggregation is not supported in containable and callback beforeFind() is not called when I use containable. I need this GROUP BY.

Anyway I think you can close this ticket if there is nothing more to do with GROUP BY support in containable.

**Comment by lorenzo** [comment]
hmm, maybe split the find in two? Get the parents, extract the primary keys and do the find in the other table with the group by

**Comment by InfinityVoid** [comment]
Thanks for advice. That's what I'll do.
