### ISSUE TITLE
Web runner doesn't display proper code coverage

### ISSUE THREAD

**Issue by ovidiupruteanu** [cakephp/cakephp#6533]
The web runner always displays code coverage for app even if you run core or plugin tests.

I tracked this down the the 'app' parameter being set to true by default in CakeTestSuiteDispatcher

```php
	public $params = array(
		'codeCoverage' => false,
		'case' => null,
		'core' => false,
		'app' => false,
		'plugin' => null,
		'output' => 'html',
		'show' => 'groups',
		'show_passes' => false,
		'filter' => false,
		'fixture' => null
	);
```

Setting it to false solves the issue since it's being set to true in the CakeTestSuiteDispatcher::_parseParams when not running plugin or core tests
```php
	if (empty($this->params['plugin']) && empty($this->params['core'])) {
		$this->params['app'] = true;
	}
```

Tested in 2.6 branch

**Comment by markstory** [comment]
Thanks, fixed in 6c21e6
