### ISSUE TITLE
Inflector pluralize() changes "Purple Cow" to "Purple Tow" (irregular issue)

### ISSUE THREAD

**Issue by VaelVictus** [cakephp/cakephp#6538]
Look in Utility/Inflector.php for 'irregular' and find cows. Whatever's in that array will cause a peculiar issue:

http://inflector.cakephp.org/The%20Purple%20Cow returns "The Purple Tows"
http://inflector.cakephp.org/Purple%20Cow returns "Purple Pows"
http://inflector.cakephp.org/The%20Purple%20Goose returns "The Purple Teese"
http://inflector.cakephp.org/Purple%20How returns "Purple Hows" as expected

For some reason it's substituting the **last** word's **first** letter with the **first** word's **first** letter, *then* adding an S as expected. I think the problem lies around line 371 in cakephp 2.4.6.

**Comment by markstory** [comment]
This seems like a pretty big edge case. If you really need to inflect purple things add specific Inflections in your application.

**Comment by VaelVictus** [comment]
I'll rephrase it: when the inflector inflects multiple words, the last of which is in the irregular list, your substr()s are off. This has nothing to do with purple.

Take, for instance, **Mark Story Sex:**
http://inflector.cakephp.org/Mark%20Story%20Sex

**Comment by dereuromark** [comment]
@VaelVictus Directly making a PR with the suggested changes is the quickest way to fix it usually. And to see if your changes are good ones.

**Comment by markstory** [comment]
Multi-word nouns have never been officially supported from what I remember.

**Comment by VaelVictus** [comment]
I have no git setup and do not wish to configure one so that I may make a pull request in a library whose internals I'm unfamiliar with. You very likely have a bug in the code; if any core developer would like to open Inflector and see the lines I described may be useless and harmful, they'd be more equipped than me to tell you why the lines *are* useless. From the moment Mark misread my post and quickly closed it, I've had the feeling this issue is not cared for, and Cake will forever process an insignificant preg_match in a harmful if statement.

**Comment by dereuromark** [comment]
You still have to be more concrete. Those lines refer to nothing that you could be meaning, that's why I was asking. https://github.com/cakephp/cakephp/blob/2.6/lib/Cake/Utility/Inflector.php#L370-L373

**Comment by ndm2** [comment]
@dereuromark He's referring to 2.4.6:

https://github.com/cakephp/cakephp/blob/2.4.6/lib/Cake/Utility/Inflector.php#L370-L373

From looking at the regex it seems to be made to explicitly handle multiple words, or maybe the intention was to match stuff like `foo-cow`, but then again why not `foo_cow` too, or was it maybe ment to avoid matching `FooCow`, that however could be assured by simply starting with `^`, I really don't know, there are no tests covering this, and I guess nobody really remembers what this was good for initially (**https://github.com/cakephp/cakephp/commit/e51b3d4915196c3389a4b3b449dbbd2a60bdab32**)? However, substringing `$regs[2]` instead of `$word` could probably fix it.

**Comment by dereuromark** [comment]
If removing that part doesn't break any tests, we could apply this to 2.7 maybe.

**Comment by markstory** [comment]
My mistake, I was wrong about multi-word nouns, and the issue has been fixed in the head of `2.6`.

**Comment by ndm2** [comment]
@markstory I'm afraid the tests don't cover the changes, as `_` is considered a word character, and thus the `\b` won't match. The regex will need some more tweaks in case irregulars with `_` should be supported.

**Comment by markstory** [comment]
@ndm2 Odd the tests were failing before I modified the code. If you have alternate cases perhaps you can propose them as a pull request.

**Comment by markstory** [comment]
The tests also pass with `blue-octopus` and `blue octopus` as the value.

**Comment by ndm2** [comment]
@markstory I'll give it a shot in a minute.

`blue-octopus` and `blue octopus` do cover the changes and are expected to pass, the underscore variant should have passed even before the changes (it does for me), as the `'/us$/i' => 'uses'` and `'/([^a])uses$/' => '\1us'` rules should catch it. Not sure whether `octopus` needs to be an irregular at all with these rules in place?

**Comment by dereuromark** [comment]
The original issue already came up 2 years ago, and was dismissed: https://github.com/cakephp/cakephp/issues/2042
Glad we finally solved it.
