### ISSUE TITLE
3.0.4 - Associations now can't call Table::table without erroring out

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6539]
Hi guys. I have a master `Table` that my Tables extend. That class overrides Cake's `Table::table`, since my plugins can't associate with each other unless they have the full DB address.

```
public function table($table = null)
{
	if ($table === null) {
		$conn = ConnectionManager::config($this->defaultConnectionName());
		$table = parent::table();
		if (strpos($table, '.') !== false) {
			return $table;
		}
		return $conn['database'] . '.' . $table;
	}
	return parent::table($table);
}
```

Table1..
```
$this->addAssociations([
	'hasMany' => [
		'Vendor/Plugin.TableAlias2'
	]
]);
```

Then..
```
$sections = $table1->find()->contain(['TableAlias2']);
```
Errors out with:
``"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'TableAlias2.database_name.foreign_key' in where clause"``

3.0.3 works without any problems. It looks like the change in `ExternalAssociationTrait` for foreignKeys did this. Changing it back to this works:
```
public function foreignKey($key = null)
{
...
            $this->_foreignKey = $this->_modelKey($this->source()->alias());
...
}
```
The return from `MySuperTable::table` is always right. I'm not sure what part of the core is adding the funky table alias directly to the SQL. If a `Table` calls `Table::table`, I'd expect the SQL that queries use would use that table, and not try to reconstruct it at another point. Not sure what that change in the core is for so I don't know if I should try to debug as it stands or change that back..?

Thanks

**Comment by markstory** [comment]
This issue was likely introduced in #6344. Where the foreign key names are now generated from the table name instead of the alias name.

**Comment by patrickconroy** [comment]
Thanks @markstory. Let me know if you need me to help debug.

**Comment by markstory** [comment]
I don't know if we can fix this without re-opening #6344. One possibility would be to have `_modelKey()` remove values followed by `.` but I feel that will cause some other issue.

**Comment by patrickconroy** [comment]
Looking at this more today. I'm stuck now since I need _modelKey to be correct. I don't think this should ever be taken from the `table` value:
```
$this->_foreignKey = $this->_modelKey($this->source()->table());
```
I don't know how else to do this other than checking the value of `table()`, if it has a `.` then use the right side of it as the physical table.

Should a cleaner method be added to repositories that gets the *real* table after `Table::table` is processed?

Should a `Table::use` method be added that sets the DB, which is originally inferred from the DB config but mutable, and `Table::table` only accepts the table name?

**Comment by markstory** [comment]
The simplest option is to set the `foreignKey` option in all your relationships. Another option would be to redefine `_modelKey()` in your base class that is prefixing the table name.

**Comment by patrickconroy** [comment]
I'm not sure if the `foreignKey` thing would work - I have associations across databases and so right now it's assuming the tables are in the same DB. And I don't know if I can override `_modelKey` in a base `Table` since that method comes in from the `Association`.

**Comment by markstory** [comment]
Why wouldn't cofiguring the foreignKey option work? It gives you full control over the column name and removes the problematic generated key name.

**Comment by patrickconroy** [comment]
Thanks, that seems to work. I was assuming the foreignKey only dealt with the right side of the association, and this seemed to be prepending the alias to the left.
However, I'm not crazy about changing dozens of files for this and having to now specify all my foreignKeys. It's also a non-BC change in a patch version (@jadb pointed that out). I'll close out for now and hope this is solved better in the future so that I don't need to specify foreignKeys and have associations across DBs work as expected.

**Comment by markstory** [comment]
@patrickconroy Do you often use relations/joins across databases?

**Comment by patrickconroy** [comment]
Yeah that's most of what I have to work with. We have data segmented off so that it's easier to deal with / manage DB ACL. I don't know how else to reconcile this code thing, since dots are allowed in table names (right?), so `_modelKey` would have no idea what to do it is sees a dot..
1. Assume it's part of the table name
2. Assume it's separating the DB/table

Maybe a config thing? `Configure::write('mytableshavedots', true);` and parse `_modelKey` better? Or a `Table` property that `ExternalAssociationTrait::foreignKey` can use before setting `$this->_foreignKey` ?
`Table::$usesDotsInName`, defaults to false. I think if something like that could work, it would solve it all. Although I haven't tried it, I don't know how any of this would react with a table with a dot in its name.. it should be giving off the same error I'm seeing.

**Comment by markstory** [comment]
I think we can safely say we don't support table names with `.` in them. That doesn't seem unreasonable to me. At least not as far as conventions are concerned. Popping off the table dot path might be a reasonable approach.

**Comment by patrickconroy** [comment]
So if `_modelKey` detects a dot, use the right side as the table name for the foreignKey? Should I make a PR with that change?

**Comment by markstory** [comment]
@patrickconroy Yeah, I think that's a reasonable approach. We can see if anyone else thinks its a bad idea :tm:

**Comment by patrickconroy** [comment]
OK thanks. I should have that up tomorrow morning and reference this.

**Comment by patrickconroy** [comment]
Closing with the PR.
