### ISSUE TITLE
HttpClient: string input allows injection attack

### ISSUE THREAD

**Issue by MikkelPaulson** [cakephp/cakephp#6540]
http://book.cakephp.org/3.0/en/core-libraries/httpclient.html#creating-multipart-requests-with-files

This "feature" allows maliciously-crafted requests to attach arbitrary files to any HTTP request based on user input. There is currently no support for escaping strings beginning with "@". Escaping functionality could be added, but the feature is non-obvious, so most developers would be unlikely to know that escaping is necessary. Better would be to remove this feature completely, as the alternative form using file handles isn't much more complicated:

    $response = $http->post('http://example.com/api', [
        'file' => fopen('/my/file', 'r'),
    ]);

**Comment by markstory** [comment]
Dumping un-sanitized user data into HTTP adapters is asking for trouble. Similar [features are offered by ext/curl](http://php.net/manual/en/book.curl.php) which is why it was implemented the way it was.

**Comment by MikkelPaulson** [comment]
It's a bad idea in cURL as well, which is why it is now deprecated:

http://php.net/manual/en/function.curl-setopt.php

<blockquote>As of PHP 5.5.0, the @ prefix is deprecated and files can be sent using CURLFile. The @ prefix can be disabled for safe passing of values beginning with @ by setting the CURLOPT_SAFE_UPLOAD option to TRUE.</blockquote>

In vanilla PHP, I would use http_build_query to handle sanitation. My assumption, before I started investigating more closely, was that Cake would handle sanitation in the same way.

If you want to use the '@' syntax, there needs to be a way for me to make user-inputted strings safe. I don't see a mechanism allowing for any sort of sanitation.

**Comment by MikkelPaulson** [comment]
The discussion regarding the change to php-curl can be found here:

https://wiki.php.net/rfc/curl-file-upload

**Comment by markstory** [comment]
I'm not sure we can _remove_ the feature in a bugfix release. We could deprecate it now with warnings and remove the `@` syntax in a future release and recommending people use file handles instead.

**Comment by MikkelPaulson** [comment]
That's a valid concern, for sure. I take it from your shift in focus that you share my concerns at this point?

I kind of doubt that many people are using such an obscure feature of a brand new release (I'm not aware of an equivalent in Cake 2.x), but I suppose it's better to do it right.

Your initial argument that sanitization should always be a consideration has some validity, but I have to point out that there is presently no way of sanitizing user input without potentially changing its content. The best I can do is `ltrim($foo, '@')`. This does need to be added as a stopgap.

Unfortunately, belatedly adding escaping may do more damage than good. Backslash escaping would require backslashes to be escaped as well, which may do more collateral damage than dropping `@` support immediately would. Adding escaping to the mix also makes things even messier when it's no longer needed.

Three options come to mind:

# Interpret `"@myfile"` as `fopen("myfile","w")` and `"@@mystring"` as `"@mystring"`. I'm not a big fan of this as it's not exactly intuitive, but it's probably the least destructive you can get with the sanitization option.
# Accept string as well as array input in the second field, allowing users to use `http_build_query()` to construct a safe query string to pass to the function.
# As was done with php-curl, add a configuration option to disable the functionality, defaulting first to enabled, then to disabled, then removed.

I should mention that I don't mind making any of the above changes myself, assuming there's community support for them.

**Comment by markstory** [comment]
Accepting a string for request body data might be the simplest way to sidestep the issue for those who want to take arbitrary user data and use it in a subsequent request. I agree that adding escaping will only complicate matters both now and later.

I think if we deprecate with an `E_DEPRECATED` warning and recommend people use strings when accepting untrusted data we can consider removing the '@' syntax in a future release.

Sending a string payload should already work, if the content-type is set. However, we could smooth over a missing content-type by defaulting to `application/x-www-form-urlencoded`.

**Comment by MikkelPaulson** [comment]
Agreed on all points.

**Comment by MikkelPaulson** [comment]
Passing a string as the second parameter does not currently work, at least for `get()`.

<blockquote>Warning (4096): Argument 2 passed to Cake\Network\Http\Client::get() must be of the type array, string given, called in /home/vagrant/inventory2/plugins/CakeREST/src/REST/API.php on line 79 and defined [CORE/src/Network/Http/Client.php, line 193]<br/>
Warning (2): http_build_query() [function.http-build-query]: Parameter 1 expected to be Array or Object.  Incorrect value given [CORE/src/Network/Http/Client.php, line 351]</blockquote>

The documentation states:

<blockquote>The type key can either be a one of ‘json’, ‘xml’ or a full mime type. When using the type option, you should provide the data as a string.</blockquote>

However, setting `type` to `x-www-form-urlencoded` results in an "Unknown type alias" error, so I have to specify Content-type explicitly. Here's the workaround that's required in Cake 3.0.4:

    // Have to use http_build_query to bypass security vulnerability - see:
    // https://github.com/cakephp/cakephp/issues/6540
    if ($method == 'get') {
        $response = $http->$method(
            "{$this->_config['urlBase']}/$resource?" . http_build_query($arguments),
            [],
            [
                'headers' => $headers,
            ]
        );
    } else {
        $headers['Content-type'] = 'x-www-form-urlencoded';
        $response = $http->$method(
            "{$this->_config['urlBase']}/$resource",
            http_build_query($arguments),
            [
                'headers' => $headers,
            ]
        );
    }

**Comment by markstory** [comment]
I didn't test get(), I only looked at post() which did support string data.

**Comment by MikkelPaulson** [comment]
Yes, the other methods seem to work fine, so long as the `Content-type` header is explicitly specified. Hence the condition in my code snippet.

**Comment by markstory** [comment]
I can put together a pull request tonight to add the default content-types and deprecation warnings.

**Comment by markstory** [comment]
Closing as I think #6550 addresses this. If not let me know and I can massage it some more.
