### ISSUE TITLE
Date(time) default NULL field not respected

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6541]
The fields of type date(time) that are `DEFAULT NULL` (=optional) should not be auto-converted to a Datetime object with the time "now". This auto-fills the forms on add/edit and by accident saves non-empty datetime values:
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L2246

Currently, a not so nice workaround is to force the fields to be empty strings in the controller for example:

    $this->request->data['published'] = '';

That prevents NULL being converted into the current time and the form to be prefilled.

As a more robust approach it should better read the schema and decide on that whether the Time object should be created or the value kept NULL. Otherwise it is impossible for the Widgets to know if this value is now coming from the db as real value, or if it is just the newly created dummy value to prefill the form with "now".
And if in question it better be kept blank by default.

- DEFAULT NULL or unknown: no change
- DEFAULT NOT NULL: new Datetime() as "now"

**Comment by markstory** [comment]
We could use `array_key_exists()` instead. That would let us separate exists + null, vs. doesn't exist and is not defined at all.

**Comment by dereuromark** [comment]
But exists and null should also be excluded since those are datetime field values coming from optional input, so defaulting them to today would accidentally store dates that shouldn't (on their own).

**Comment by lorenzo** [comment]
I agree with @dereuromark nullable fields should have empty by deafault

**Comment by markstory** [comment]
I don't think I was clear, I was thinking:

* key exists + null => empty.
* key exists + value => value
* no key => $now.

**Comment by dereuromark** [comment]
Hm, that would fail for all non-schema fields, like custom added ones.
But that might be fine. I still prefer to opt-in defaults via `default` rather than having to try to remove them again afterwards by some black magic :P

**Comment by dereuromark** [comment]
Would it be bad to not auto-today? And only do that as opt-in with `'default' => true` on the input()?
I tested it and I would rather have the 2.x way here:

    echo $this->Form->input('published', ['type' => 'date']);

stays empty as the entity is empty and we dont pass request data for it.

But

    echo $this->Form->input('published', ['type' => 'date', 'default' => true]);

This defaults to NOW.
Or:

    echo $this->Form->input('published', ['type' => 'date', 'default' => $customDate]);

Change needed is minimal: https://github.com/cakephp/cakephp/compare/master-datetime

**Comment by markstory** [comment]
I think that sounds reasonable @dereuromark . We would need to update the docs as well. I could see the behaviour change being interpreted as a bug as well.

**Comment by dereuromark** [comment]
I think I would be OK with holding of until 3.1, but  the change only removes the auto-now filling of forms, which itself could be interpreted as the bigger bug. And the change itself doesn't break anything.
So if all others are fine, a doc and migration guide / release note might suffice here for 3.0.5.
