### ISSUE TITLE
FormHelper don't display thrown errors from controller.

### ISSUE THREAD

**Issue by basteyy** [cakephp/cakephp#6547]
First my code example:

```php
// Inside my controller
$Users = TableRegistry::get('Users');
$user = $Users->find()->contain([
    'UserProfiles'
])->where([
    'username' => $username
])->first();
$this->set('user', $user);
```
```php
// The template
echo $this->Form->create($user);
echo $this->Form->input('user_profile.vita', [
    'type' => 'textarea'
]);
echo $this->Form->submit();
echo $this->Form->end();
```

Displaying the containing data "vita" works well. Also saving. 
But when I try to throw a custom error in my controller, it wont work.
```php
// Back inside the controller
// Throw the error
$user->errors('UserProfiles.vita', __('My error message.'));
// I also already tried 
$user->errors('UserProfile.vita', __('My error message.'));
$user->errors('user_profile.vita', __('My error message.'));
$user->errors('user_profiles.vita', __('My error message.'));
```

Perhaps the bug is located here:
https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L708

I hope I make it clear what I want to say/do.

I use Cake 3.0.3

**Comment by markstory** [comment]
If you are setting errors on nested objects, you need to set the errors on those objects directly. Did you try

```php
$user->user_profile->errors('vita', 'Should work');
```

**Comment by basteyy** [comment]
```php
$user->user_profile->errors('vita', 'Should work');
```
.. works well. Thank you! Can I find this in the docs? 

I guessed it here http://book.cakephp.org/3.0/en/orm/entities.html#validation-errors or here http://book.cakephp.org/3.0/en/core-libraries/form.html#invalidating-individual-form-fields-from-controller but nothing there about nested errors.
