### ISSUE TITLE
3.0 - Entity toArray weirdness

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6548]
Hello. This might be the an edge case, but I noticed:
1. If I'm trying to serialize an `Entity`.
2. The first thing in the array extends `EntityInterface`
3. The second thing in the array is anything else (so that `toArray` is not a method).

This will error out, since the check in `EntityTrait::toArray` only makes sure the first thing in the input array is an `Entity`.

```
$posts = new Entity([
	'id' => 1,
	'foo' => [
		new Entity(['hi' => 'test']),
		'notentity' => 1
	]
]);

$this->set(compact('posts'));
$this->set('_serialize', 'posts');
```
Fatals with:
``Fatal error: Call to a member function toArray() on integer in SITE/vendor/cakephp/cakephp/src/Datasource/EntityTrait.php on line 433``
(ignore that line number, I'm mid-debug)

I can think of solving it in a couple ways.

1. Making sure the quote/unquote `$entity` is an actual `Entity`.
```
if ($entity instanceof EntityInterface) {
    $result[$property][$k] = $entity->toArray();
} else {
    $result[$property][$k] = $entity;
}
```

or 2. Check whatever `$entity` is an object and that it has the method `toArray`.

This came up randomly after using `ShadowTranslate`, but since it *seems* like I should be able to serialize my example `$posts`, I think this is more a bug with the core. If it seems like a bug to you guys I can make a PR/test.

Thanks,
Patrick

Edit - Couple typos.

**Comment by markstory** [comment]
I totally agree this is a bad thing that should be fixed.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
