### ISSUE TITLE
loadAll() method core CakePlugin class

### ISSUE THREAD

**Issue by Jayaramki** [cakephp/cakephp#6552]
Actually `lib/cake/core/CakePlugin` class having `loadAll()` method to load all plugins in `app/plugins` directory. right? But the bad thing I found in that method is loading bootstrap, routes. In some plug-ins developers may or may not use bootstrap.php, routes.php and etc., config files.

When working with plugins, I don't want to edit each time app/bootstrap.php for set `bootstrap=>true`. If You suggest a way to use `CakePlugin::loadAll(array(array('bootstrap' => true)));`, If I am not using bootstrap.php in my plugin cake will throw the error.  So, make this loadAll() method more intelligent to find is there any config files available in `plugin/MyPlugin/Config` directory then set it to `true`, else leave it for `false`.

I don't think you guys missed this scenario. If you guys ignored this feature explain me reason to ignore please.

**Comment by markstory** [comment]
If you need to load different plugins differently, then don't use loadAll(), or use [the documented options](http://api.cakephp.org/2.6/class-CakePlugin.html#method-CakePluginloadAll).

**Comment by ceeram** [comment]
or use the undocumented: `'ignoreMissing' => false` option for loadAll()

**Comment by markstory** [comment]
I will add that ti the api docs tonight.

**Comment by Jayaramki** [comment]
After created, this issue only I was seen the source code `_includeFile()` method and understood the use of `ignoreMissing` parameter. I was wasted some hours... :(.
@ceeram `'ignoreMissing' => true` Solved this.
@markstory thanks... :)

**Comment by Jayaramki** [comment]
@markstory  And please Update in 2.x api docs too..

**Comment by markstory** [comment]
Docs are already updated for 2.6. :)
