### ISSUE TITLE
Blog tutorial isAuthorized() isn't missing a return false?

### ISSUE THREAD

**Issue by ag-secret** [cakephp/cakephp#6554]
Maybe this could be a misunderstanding but here:

    // src/Controller/ArticlesController.php

    public function isAuthorized($user)
    {
        // All registered users can add articles
        if ($this->request->action === 'add') {
            return true;
        }

        // The owner of an article can edit and delete it
        if (in_array($this->request->action, ['edit', 'delete'])) {
            $articleId = (int)$this->request->params['pass'][0];
            if ($this->Articles->isOwnedBy($articleId, $user['id'])) {
                return true;
            }
        }

        return parent::isAuthorized($user);
    }

Need I return false if the isOwnedBy() test fail? like this:

    // src/Controller/ArticlesController.php

    public function isAuthorized($user)
    {
        // All registered users can add articles
        if ($this->request->action === 'add') {
            return true;
        }

        // The owner of an article can edit and delete it
        if (in_array($this->request->action, ['edit', 'delete'])) {
            $articleId = (int)$this->request->params['pass'][0];
            if ($this->Articles->isOwnedBy($articleId, $user['id'])) {
                return true;
            }
            return false;
        }

        return parent::isAuthorized($user);
    }

I found this code at:
http://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html#authorization-who-s-allowed-to-access-what

**Comment by dereuromark** [comment]
Looks like you are right. Please make a PR for it in the "correct" repo :) https://github.com/cakephp/docs

**Comment by ag-secret** [comment]
`isAuthorized()` at the `AppController` is return false so when I call `return parent::isAuthorized($user);` will return false if is needed. So theres no error at documentation.

**Comment by dereuromark** [comment]
ok
