### ISSUE TITLE
Bug in attribute minimization.

### ISSUE THREAD

**Issue by NaranjaWeb** [cakephp/cakephp#6560]
Attribute minimization 
(like < .... disabled="disabled">  => < .... disabled>)
does not work as is written in documents and I found an apparent bug in
cakephp\src\View\StringTemplate.php
\Cake\View\StringTemplate::_formatAttribute()

if ($isMinimized && in_array($value, $truthy, true)) {
            return "$key=\"$key\"";   <<<<< Not Minimized!
        }

Also, I would like to add some attributes to minimize.
How can I add (override) members to $_compactAttributes?

**Comment by markstory** [comment]
What attributes would you like to add?

**Comment by NaranjaWeb** [comment]
Thank you for your response.

I wanted add 'async'.

According to https://github.com/kangax/html-minifier, the followings
seems to be minimizable attributes, fyi. 

allowfullscreen
async
autofocus
autoplay
checked
compact
controls
declare
default
defaultchecked
defaultmuted
defaultselected
defer
disabled
enabled
formnovalidate
hidden
indeterminate
inert
ismap
itemscope
loop
multiple
muted
nohref
noresize
noshade
novalidate
nowrap
open
pauseonexit
readonly
required
reversed
scoped
seamless
selected
sortable
spellcheck
truespeed
typemustmatch
visible

**Comment by markstory** [comment]
Ok. I don't see any reason we couldn't update the list in CakePHP to match the current attribute set.

**Comment by NaranjaWeb** [comment]
Thank you and happy to see the progress.

**Comment by dereuromark** [comment]
@NaranjaWeb Would you be able to make a PR (Pull request) with the suggested changes? That would be awesome.

**Comment by NaranjaWeb** [comment]
I made my first PR in my life and I hope it works.

**Comment by dereuromark** [comment]
Closing as PR for this is open.
