### ISSUE TITLE
Getting non-related error when trying to make new entity because of bad data

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#6562]
Hi!

When trying to put the following data:

https://gist.github.com/Spriz/3d76313473f180acc424

into a new Entity it dies with the error: https://gist.github.com/Spriz/50270a74888abe7485d4

I guess it should give a more descriptive message - at least IRC ( @lorenzo ) sent me here :-)

**Comment by Spriz** [comment]
... weird errors whether I include ['associated' => ['Industires']] in the newEntity() happened...

**Comment by markstory** [comment]
Is the problematic key industries or contact_person?

**Comment by Spriz** [comment]
industries @markstory

**Comment by markstory** [comment]
Thanks, I will take a look into this.

**Comment by markstory** [comment]
Pull request up.
