### ISSUE TITLE
Returning empty query expressions for association conditions generates invalid SQL

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#6568]
I'm note quite sure whether this is a bug, as this usage seems neither documented nor tested (at least I couldn't find any explicit tests). I've seen it on Stackoverflow here

**http://stackoverflow.com/a/29781726/1392379**

and noticed that returning the expression object like

```php
$TableA->hasOne('TableB', [
	'className' => 'TableB',
	'foreignKey' => 'table_a_id',
	'conditions' => function ($e, $query) {
		// ...
		return $e;
	}
]);
```

will result in an error as it will generate invalid SQL, specifically it will compile an empty set of parentheses into the `WHERE` clause, something like

```sql
... WHERE (() AND x = y)
```

When adding conditions to the expression object it works fine, so I guess this just needs an empty check somewhere.

**Comment by markstory** [comment]
So you're returning an empty query expression?

**Comment by ndm2** [comment]
Yep, that's what I did. As mentioned, this is neither documented, nor explicitly tested, so I had/have no clue how it is ment to be used correctly (if at all), I've just played with the SO example, which seems to receive an empty expression by default and returns that.

**Comment by markstory** [comment]
Cool, I'll figure out a fix.

**Comment by markstory** [comment]
Fix up now.
