### ISSUE TITLE
When injecting `hasOne` results, they are being picked in reverse order

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#6569]
There's a good chance that this one is invalid, as it seems generally wonky to achieve the desired result this way, and right now I cant think of any other use cases, but I thought I'd bring it up just to make sure.

This also stems from **http://stackoverflow.com/a/29781726/1392379**, and came up in **http://stackoverflow.com/q/30241975/1392379**.

Say we'd use an association like the following to attach the most popular comment to the corresponding article like

```php
$Articles->hasOne('MostPopularComments', [
	'className' => 'Comments',
	'foreignKey' => 'article_id',
	'strategy' => 'select',
	'conditions' => function ($e, $query) {
		$query->order(['MostPopularComments.votes' => 'DESC']);
		return [];
	}
]);
```

This will select all associated comments, and the pick the first matching one and add it to the article. Since this fetches way more data then necessary, it's a rather bad idea, as mentioned initially. 

Anyways, in case this is considered a valid use case, I would expect that this would pick the comment with the most votes, but the opposite will happen, it will pick the one with the least votes, which makes me think that the results are being iterated in reversed order, as it picks the correct one when using `ASC` ordering.

**Comment by lorenzo** [comment]
Your solution is missing a `limit(1)`

**Comment by ndm2** [comment]
Nah, using a limit will select only 1 single result, als the select strategy uses a single additional query only, not a speparate one per result, so _not_ using limit is actually the trick here to make this working at all :)

**Comment by lorenzo** [comment]
you are using the select strategy, you NEED a limit(1)

**Comment by lorenzo** [comment]
As an optimization/improvement I will avoid constructing a full result map after fetching. The hasOne association was though as an identity type of association (1-1) so it didn't account for this "clever" type of usages.

In the future, a more correct answer to those kind of questions, would be to suggest creating a custom association type. For example `class TopOne extends HasOne`

The association would only allow a select strategy and automatically add the `limit`

**Comment by ndm2** [comment]
So the select strategy, when used for `hasOne` associations, is explicitly ment to be used for retrieving a single result only? ie, one single result that may or may not fit for the other side of the association?

With the example of a top comment, that comment would only fit for a single article, where the other articles will be left with no top comment attached, even if there actually might be one in the database?

**Comment by lorenzo** [comment]
It is implicitly meant to select only one as the assumption of this type of association is that there is an identity between the 2 records. It is only if the identity does not have a matching record in the other side, so it would be ok to have a null top comment

**Comment by ndm2** [comment]
Mmm, sorry for harping on about this, but I'm still not quite sure whether I understand this correctly. With that requirement implied, it seems that using the select strategy only makes sense when fetching a single main record, ie one single article, so that it's ok that the query for the associated records only fetches a single result?

**Comment by lorenzo** [comment]
You are kind of right. The suggestion of using `limit(1)` is incomplete. The right answer is to `group by article id having votes = max(votes)`. That way no limit is required

**Comment by ndm2** [comment]
I've tried similar stuff on may way to a solution too, but none of this worked. Note sure if this is maybe specific to MySQL, or whether I did something wrong, but `group by` and `having max` won't work like that, this will yield 0 results. As far as I understand, there are pretty much only two options

**http://dev.mysql.com/doc/refman/5.6/en/example-maximum-column-group-row.html**

I couldn't get it working at first, so I headed for the join strategy with a subquery. Not sure what I was doing wrong, but I now got both solutions working with the select strategy.


```php
'conditions' => function (QueryExpression $exp, Query $query) {
	$query->leftJoin(
		['CommentsFilter' => 'comments'],
		[
			'MostPopularComments.article_id = CommentsFilter.article_id',
			'MostPopularComments.votes < CommentsFilter.votes'
		]);
	return ['CommentsFilter.id IS NULL'];
}
```

and

```php
'conditions' => function (QueryExpression $exp, Query $query) {
	$query->innerJoin(
			[
				'CommentsFilter' => $query
					->connection()
					->newQuery()
					->select(['article_id', 'votes' => $query->func()->max('votes')])
					->from('comments')
					->group('article_id')
			],
			[
				'MostPopularComments.article_id = CommentsFilter.article_id',
				'MostPopularComments.votes = CommentsFilter.votes'
			]
		);
	return [];
}
```

**Comment by lorenzo** [comment]
It does work like that let me show you an example:

![screen shot 2015-05-16 at 20 54 20](https://cloud.githubusercontent.com/assets/37621/7667583/ccbebd8a-fc0d-11e4-826d-e5ee1a755fa2.png)

Not sure what the inner join is for... btw you need the select strategy for that

**Comment by ndm2** [comment]
is that MySQL? Because what I get is this

0 results: http://sqlfiddle.com/#!9/bde33/1
1 result: http://sqlfiddle.com/#!9/69924/1 (one of the highest values inserted first)

**Comment by lorenzo** [comment]
yes, it is. Maybe is a mysql 5.6 thing?

**Comment by lorenzo** [comment]
Yeah, again I may be mistaken on the query I made. I'll just stop giving advice in the issue tracker :)

**Comment by ndm2** [comment]
Hehe, ok, so I can stop fiddling with this then and finally have some :pizza:, the oven is just heating air for 45 minutes already and about to catch :fire:
