### ISSUE TITLE
PaginatorHelper::numbers() does not reflect url options.

### ISSUE THREAD

**Issue by NaranjaWeb** [cakephp/cakephp#6576]
PaginatorHelper::numbers() function does not merge $option['url'], while
prev and next functions do.

You can jump to the anchor when you set an option like

PaginatorHelper::prev('prev', ['url' => ['#' => 'comments'] ]);

But this does not work for PaginatorHelper::numbers() function.

I look into the source and found why.

Should I make pull requests?

**Comment by dereuromark** [comment]
Yes, a PR would be very nice. Ideally including test cases to proof this.

**Comment by dereuromark** [comment]
Closing as PR is open.
