### ISSUE TITLE
Plugin naming problem

### ISSUE THREAD

**Issue by mataw** [cakephp/cakephp#6577]
Hello.

I want to create plugin which have same name like controler in it. For example i want plugin with name **Users** (for managin users ;) and in it will be controllers for **Users** and **SocialProfiles**....

### my routing file
```php
<?php
use Cake\Routing\Router;

Router::plugin('Users', function ($routes) {
    $routes->fallbacks('InflectedRoute');
});
```
### Plugins/Users/src/controller/UsersController.php
```php
<?php
namespace Users\Controller;

use Users\Controller\AppController;

/**
 * Users Controller
 *
 * @property \Users\Model\Table\UsersTable $Users
 */
class UsersController extends AppController
{
```

every time i gettin error **Error: Create the class UsersController below in file: D:\bakery\cerise3/plugins/User/src\Controller\UsersController.php**

### from documentation
When loading plugins, the plugin name used should match the namespace. For example you have a plugin with top level namespace Users you would load it using:
```php
Plugin::load('User');
```
i tried create plugin with name **User** but still getting same error, but what is interesting, for example plugin **Taxonomy** and controler *taxonomies* working (serveraddress:port/taxonomy/taxonomies)...
### working
Taxonomy.taxonomies (or any other in-plugin controler)
### not working
Users.users, User.users
Menus.menus

*btw in cakephp 2.x wasn't problem.*

Any options?

**Comment by dereuromark** [comment]
What is your controller code? Sure you got the namespaces right?

**Comment by mataw** [comment]
Another not working controller Menus.menus (plugin**Menus**)

plugin route file
```php
<?php
use Cake\Routing\Router;

Router::plugin('Menus', function ($routes) {
    $routes->fallbacks('InflectedRoute');
});
```
### Menus - AppController.php

```php
<?php

namespace Menus\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{

}
```
### and menus Controller
```php
<?php
namespace Menus\Controller;

use Menus\Controller\AppController;

/**
 * Menus Controller
 *
 * @property \Menus\Model\Table\MenusTable $Menus
 */
class MenusController extends AppController
{

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->set('menus', $this->paginate($this->Menus));
        $this->set('_serialize', ['menus']);
    }

    /**
     * View method
     *
     * @param string|null $id Menu id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $menu = $this->Menus->get($id, [
            'contain' => ['Links']
        ]);
        $this->set('menu', $menu);
        $this->set('_serialize', ['menu']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $menu = $this->Menus->newEntity();
        if ($this->request->is('post')) {
            $menu = $this->Menus->patchEntity($menu, $this->request->data);
            if ($this->Menus->save($menu)) {
                $this->Flash->success('The menu has been saved.');
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error('The menu could not be saved. Please, try again.');
            }
        }
        $this->set(compact('menu'));
        $this->set('_serialize', ['menu']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Menu id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $menu = $this->Menus->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $menu = $this->Menus->patchEntity($menu, $this->request->data);
            if ($this->Menus->save($menu)) {
                $this->Flash->success('The menu has been saved.');
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error('The menu could not be saved. Please, try again.');
            }
        }
        $this->set(compact('menu'));
        $this->set('_serialize', ['menu']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Menu id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $menu = $this->Menus->get($id);
        if ($this->Menus->delete($menu)) {
            $this->Flash->success('The menu has been deleted.');
        } else {
            $this->Flash->error('The menu could not be deleted. Please, try again.');
        }
        return $this->redirect(['action' => 'index']);
    }
}
```
Plugin is loaded but not working...

**Comment by markstory** [comment]
You have not connected a route for /users only /users/users. You'll need to connect additional routes for /users to work.

**Comment by mataw** [comment]
ok i'll try.... thanx

but
```php
<?php
use Cake\Routing\Router;

Router::plugin('Taxonomy', function ($routes) {
    $routes->fallbacks('InflectedRoute');
});
```
and taxonomy\taxonomies is working...

**Comment by markstory** [comment]
That has two route segments, matching the plugin and controller. Unless I misread your issue you were going to `/users` not `/users/users`.

**Comment by mataw** [comment]
/menus/menus
***Error: Create the class MenusController below in file: D:\bakery\cerise3/plugins/Menus/src\Controller\MenusController.php***

/menus
***Error: Create the class MenusController below in file: src\Controller\MenusController.php***

Users controller and menus controller are in that plugin with same name not alone....

Cotnrollers are created in plugins/Plugin_name/src/Controller/ControllerNameController.php

for example 

i have users controller in

plugins/Users/src/Cntroller/UsersController.php.... if controller is in src/Controller/UsersController.php there is no problem...

**Comment by markstory** [comment]
Ok, I'll take a look as what you have should work.

**Comment by dereuromark** [comment]
Are those composered standalone plugins? Or in the same application? Because for the latter you also need a small composer.json part you might be very well missing. See [here](https://github.com/dereuromark/cakephp-sandbox/blob/3.0/composer.json#L58-L59) for an example.

**Comment by mataw** [comment]
OK.... its working now but i dont understand :/

cake bake plugin Users ... last questions was if i wan to make change at composer.json... 

i deleted all plugin engenerated it again with answer yes and it's working now...

**Comment by markstory** [comment]
The reason the classes weren't being found previously was that the class autoloader (generated from the composer.json file) hadn't been updated. Because of this the controller classes couldn't be foud.

**Comment by mataw** [comment]
composer dumpautoload....

thank you very much
