### ISSUE TITLE
Calling $Model->schema() in mocked model's behavior connects to default database connection

### ISSUE THREAD

**Issue by tmazur** [cakephp/cakephp#6578]
In CakePHP 2.6.4 I have a Model which has a behavior. The behavior's setup method looks like this:

    public function setup(Model $Model, $settings = array()) {
        ...
        $schema = $Model->schema();
        ...
    }

In my unit tests, when I try to get a mock of the model, the following fails:

    $this->getMockForModel('Expense', array('anyMethod')); // fails

with the following error:

    MissingConnectionException: Database connection "Mysql" is missing, or could not be created.

Interestingly enough, calling the same without any mocked methods works fine. Mocking schema() seems to fix the issue.

    $this->getMockForModel('Expense', array()); // ok
    $this->getMockForModel('Expense', array('anyMethod', 'schema')); // ok

**Comment by markstory** [comment]
From looking at the getMockForModel() code the test datasource isn't set until _after_ the constructor. However, behavior setup() hooks are fired _in_ the constructor.

If you do not want to mock the schema() method you should pass the 'ds' option to your mock:

```php
$mock = $this->getMockForModel('Expense', ['anyMethod'], ['ds' => 'test']);
```

This should resolve the issue. Unfortunately, I don't think there is a better solution right now.

**Comment by tmazur** [comment]
Unfortunetely getMockForModel does 

    unset($config['ds']);

So the only solution is to mock schema.
