### ISSUE TITLE
2.7: Dont include deprecated options in bake

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6581]
After https://github.com/cakephp/cakephp/pull/6579 is merged, we should also exclude the following validation methods from bake as they have been deprecated:

- **between** (is now included/available as lengthBetween)

No need to show up in bake twice.

To be discussed regarding deprecation / removal from bake in 2.7:
- ssn
- blank
- userDefined

Maybe even phone and postal, as they are also highly localized and as such better suited in the Localized plugin and not part of 3.x.

**Comment by markstory** [comment]
Removing ssn, blank, and user defined makes sense to me.

**Comment by ravage84** [comment]
Agree with @markstory but I would keep ``postal`` and ``phone`` for the moment.
And yes, only show ``lengthBetween``.

**Comment by markstory** [comment]
Pull request open now.
