### ISSUE TITLE
Query builder error on LIKE operator

### ISSUE THREAD

**Issue by rodrigomvf** [cakephp/cakephp#6588]
When you set LIKE operator to a number field the query builder change the value to 0.

**Comment by rodrigomvf** [comment]
version 3.0.x

**Comment by markstory** [comment]
What does your query look like? It is very likely that your data is being cast by either the database type system, or PDO. See #6470 for a similar issue that was reported in the past.

**Comment by rodrigomvf** [comment]
Hi markstory

It is the same problem #6470 .
So I think the problem is resolved.
thank you
