### ISSUE TITLE
Delete Deep Associations

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#6596]
Hi guys, i certainly misunderstood something but i'm trying to delete an entity with deep associations:
item -> elements -> values

When i delete an item, all elements are also deleted with him but values not.

I initialized table elements like this:
```
$this->hasMany('Values', [
    'dependent' => true
]);
```

and items table:
```
$this->hasMany('Elements', [
    'dependent' => true
]);
```

But it doesn't work like i figure it, it's just a question to know if i'm doing it wrong or if it's just impossible

Thanks,

**Comment by lorenzo** [comment]
You are missing `'cascadeCallbacks' => true` in your config.
