### ISSUE TITLE
About using requestAction in the view with CakePHP 3.x

### ISSUE THREAD

**Issue by zx4357685** [cakephp/cakephp#6598]
His guys,

In my project I want to include the view 'ajax_list' into the 'index',and it has been displayed but the url of image and link was wrong.

The detail of the problem in

http://stackoverflow.com/questions/30318793/how-should-i-use-requestaction-in-the-view-with-cakephp-3-x

Now I have used the Dispatcher Filters to fix the problem , but I dont know if it's a bug on the requestAction,So please check it.

Thank you!

**Comment by markstory** [comment]
I'm guessing this happens when your application is running in a sub-directory? The requested action should have the correct base/webroot properties even in that situation though.

**Comment by zx4357685** [comment]
@markstory  

The File structure of my application is like:

    /Pro
        /src
            /Controller
                ActivitiesController.php
                ProjectsController.php
                ...
            /Template
                /Activities
                    index.ctp
                    ajax_list.ctp
                    ....
                /Projects
                    ...
                ...
            ...
        /vender
       ...

**Comment by markstory** [comment]
Fixed in #6610

**Comment by zx4357685** [comment]
@markstory Thank you!
