### ISSUE TITLE
3.0.5 - Problem with the _dn() function.

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#6599]
Hello,

As it say in the function doc : https://github.com/cakephp/cakephp/blob/master/src/I18n/functions.php#L100 :
```php
function __dn($domain, $singular, $plural, $count, $args = null) {}
```
to use this function, we should do :
```php
_dn('domaine', 'Topic {0}', 'Topics {0}', 6)
```

But if i use it like that, it doesn't work, it render like that :
```php 
Topics {0}
```
To get it work, i must specify **2 times** the `$count` variable :
```php
_dn('domaine', 'Topic {0}', 'Topics {0}', 6, 6)
```

I'm not sure if it's a bug or not, but it look weird. If someone can confirm this, to be sure it's a bug.
(Maybe the same bug with the `_n()` function)

**Comment by lorenzo** [comment]
One argument is the count and the other the prams. This works as expected.
