### ISSUE TITLE
save without validation. How?

### ISSUE THREAD

**Issue by kailsazerland** [cakephp/cakephp#6601]
I am calling 
$this->Users->save($entity, ['checkRules' => false]);
I don't want the validation will be called, but it is called!!

**Comment by dereuromark** [comment]
The validation is two-stepped as documented.
The first part is already happening on patching the entity.
So you need to, as documented, adjust that:

    $entity = $this->TableName->patchEntity($entity, $this->request->data, ['validate' => false]);

See https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1964-L1966
