### ISSUE TITLE
Problem with Configure::write

### ISSUE THREAD

**Issue by jamensonalvarez** [cakephp/cakephp#6603]
I have the next code and works fine:

        Configure::load('formats');
        debug(Configure::read());
        Configure::write('sep_decimal', '-');
        debug(Configure::read());

But when i do the next code in another controller:

        Configure::load('formats');
        debug(Configure::read());

It doesn't make the change and no modify the file in formats.php

**Comment by markstory** [comment]
Configure is not a persistent global variable. Each request runs in a separate process and the changes made from one request don't persist to another. If you need to change configuration at runtime [you can write configuration data to files/cache storage](http://book.cakephp.org/3.0/en/development/configuration.html#reading-and-writing-configuration-files).
