### ISSUE TITLE
select in contain on deep association

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#6606]
Hi, i'm trying to select a field in deep association and it fail:

```
$item = $this->Items->find('all')
  ->contain(['Elements.Values' => function ($q) {
    return $q->select(['Values.name']);
  })->toArray();
```

The "values" property of Elements entity is an empty array but if i remove the callback function "values"  is well defined by an array of all "Values" entities associated with "Elements"

I tried the code below and it works fine:
```
$item = $this->Items->find('all')
  ->contain(['Elements' => function ($q) {
    return $q->select(['Elements.name']);
  })->toArray();
```

What goes wrong ? Deep associations ? Type of association ? Or both ?

**Comment by lorenzo** [comment]
You need to select the foreign keys of the association so it can be matched in PHP. There used to be an exception warning users about it, I'll check why it is not working

**Comment by GLacourt** [comment]
Exact it works but i didn't get a single warning
