### ISSUE TITLE
2.6.3 inconsistent request->data

### ISSUE THREAD

**Issue by brianally** [cakephp/cakephp#6629]
I'm using a filter to deserialize JSON input from an Ember app. The model name key comes in as lowercase and the filter adjusts that to titlecase. However, the array is being switched back somewhere between beforeFilter() and the action. The data looks fine in Dispatcher::_invoke, until right after it calls $controller->startupProcess().

I created a temp component to help in debugging. Here's a stripped-down version of the code:
```
class UsersController extends AppController {

	public function invokeAction(CakeRequest $request) {
		$this->log(__METHOD__, 'debug');
		$this->log($request->data, 'debug');
		return parent::invokeAction($request);
	}

	public function beforeFilter() {
		parent::beforeFilter();
		$this->log(__METHOD__, 'debug');
		$this->log($this->request->data, 'debug');
	}

	public function add() {
		$this->log(__METHOD__, 'debug');
		$this->log($this->request->data, 'debug');
	}
}

class FooComponent extends Component {
	
	public function initialize( Controller $controller ) {
		$this->log(__METHOD__, 'debug');
		$this->log($controller->request->data, 'debug');
	}

	public function startup( Controller $controller ) {
		$this->log(__METHOD__, 'debug');
		$this->log($controller->request->data, 'debug');
	}
}
```
And debug.log:
```
2015-05-24 17:56:16 Debug: FooComponent::initialize
2015-05-24 17:56:16 Debug: Array
(
    [User] => Array
        (
            [name] => foo
            [email] => foo@bar.net
            [agency] => 6
        )
)

2015-05-24 17:56:16 Debug: UsersController::beforeFilter
2015-05-24 17:56:16 Debug: Array
(
    [User] => Array
        (
            [name] => foo
            [email] => foo@bar.net
            [agency] => 6
        )
)

2015-05-24 17:56:16 Debug: EmberComponent::startup
2015-05-24 17:56:16 Debug: Array
(
    [user] => Array
        (
            [name] => foo
            [email] => foo@bar.net
            [agency] => 6
        )
)

2015-05-24 18:48:27 Debug: UsersController::invokeAction
2015-05-24 18:48:27 Debug: Array
(
    [user] => Array
        (
            [name] => foo
            [email] => foo@bar.net
            [agency] => 6
        )
)

2015-05-24 17:56:16 Debug: UsersController::add
2015-05-24 17:56:16 Debug: Array
(
    [user] => Array
        (
            [name] => foo
            [email] => foo@bar.net
            [agency] => 6
        )
)
```
Note how "User" changes back to "user". What am i missing? Why/where would $request->data revert?

Please ignore "agency". An Ember-Data issue. That gets switched to "agency_id" elsewhere.

**Comment by markstory** [comment]
I would start removing components and dispatcher filters/callback methods until the issue goes away. Then readd them to find the culprit(s).

There isn't anything in CakePHP's code that would recase array keya however it is possible that something like requesthandler is overwriting the request data.

**Comment by brianally** [comment]
It's not that the case was being changed (my code does that) but that the data was then being reset. The problem is indeed with RequestHandler. I'll switch to Plan B, which is to do what i want in a component that loads after that one. Please feel free to close this. Although, one might consider a warning in the docs for filters that changing request->data at that point might not work so well.
