### ISSUE TITLE
Correct SQL statement generates an error when I try to fetch the result with all()

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#6630]
Hello,
i have a strange situation, this is my custom find:

```
public function findTurnover(Query $query, array $options)
{
        return $query
            ->select(['turnover' => $query->func()->sum('Payments.amount')])
            ->matching('Users', function ($q1) {
                return $q1->matching('Ads', function ($q2) {
                    return $q2->matching('Payments');
                });
            })
            ->group('Companies.id');      
}
```
The ORM generates this SQL:
```
SELECT (SUM(Payments.amount)) AS `turnover` 
FROM companies Companies 
INNER JOIN users Users ON (Users.role_id = 2 AND Companies.id = (Users.foreign_key)) 
INNER JOIN ads Ads ON Users.id = (Ads.user_id) 
INNER JOIN payments Payments ON Ads.id = (Payments.ad_id) 
GROUP BY Companies.id
```

If i copy and paste this sql on mysql workbench it works correctly! I get the expected result.

The problem is when i need to fetch the result:
```
->find('turnover')->all()
```
cause an error:

**Companies is not associated with Ads**

That's correct too because Companies is not directly associated with Ads, but I have used nested `matching()` (and as I wrote above the **SQL statement is perfect**)

**Comment by markstory** [comment]
Did you try setting the matching as a dot path? I would expect that `matching('Users.Ads.Payments', ...)` would work.

**Comment by damianoporta** [comment]
@markstory it works! This is the custom find
```
public function findTurnover(Query $query, array $options)
{
        $query
            ->select(['turnover' => $query->func()->sum('Payments.amount')])
            ->matching('Users.Ads.Payments')
            ->group('Companies.id');
        return $query;
}
```
In this case, if needed, how can I specify particular `->where()` for a table? I mean, now I am using `Users.Ads.Payments` if i need to add something like `->where(['Ads.state' => 1])` how can i do? I should put it into a specific matching, no?

**Comment by markstory** [comment]
@damianoporta Inside the query builder callback for the matching() call you have, you should be able to define the conditions. If that doesn't work the following should also work:

```php
$query->matching('Users.Ads', function ($q) {
  return $q->where(['Ads.state' => 1]);
})
->matching('Users.Ads.Payments');
```

**Comment by markstory** [comment]
Closing as this seems to have come to a reasonable conclusion.
