### ISSUE TITLE
Error when Postgres column alias length is greater than 64

### ISSUE THREAD

**Issue by aydot** [cakephp/cakephp#6631]
FYI -
If I have a table name: `ArticlePaymentGatewayProfiles` and 
column name: `show_number_of_payments_in_total_count`
 By doing a find on the table, Cake sets the alias as `ArticlePaymentGatewayProfiles__show_number_of_payments_in_total_count` which fails here [http://api.cakephp.org/3.0/source-class-Cake.ORM.ResultSet.html#518] due to Postgres NAMEDATALEN which has a max length of 64 [http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS]

**Comment by markstory** [comment]
How would you suggest we resolve this? Having an additional layer of column mapping would work but will likely impact performance.

**Comment by Laykou** [comment]
What if this layer would be optional? By default it would be `null` meaning Cake would work as usual. But you can configure it (by array or custom class) with the mapping.

**Comment by markstory** [comment]
@Laykou That could work. Do you know if SQLServer also has limits on column aliases?

**Comment by jadb** [comment]
@markstory 128 according to [SO](http://stackoverflow.com/a/5808368)

**Comment by ADmad** [comment]
Closing as the issue has gone stale. If there is still interest a PR is welcome.
