### ISSUE TITLE
2.6 - CakeSocket: stream_socket_enable_crypto failure

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#6633]
I suspect commit https://github.com/cakephp/cakephp/commit/bb8e0ae83524f2ab7ffbd9b330cb39f34ed640a7 introduced a bug with ssl connections. 

After the update from 2.6.2 to 2.6.5 https connections started to throw a `SocketException` ("Unable to perform enableCrypto operation on CakeSocket") preceded by a warning:
`stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number in [/srv/ssd/www/zanobot/vendor/cakephp/cakephp/lib/Cake/Network/CakeSocket.php, line 395]`

Edit: Https connections fail every time while trying to post wordpress.com blogs for example.

**Comment by markstory** [comment]
I will take a look.

**Comment by markstory** [comment]
The following code fails differently for me:

```php
		$http = new HttpSocket();
		$res = $http->get('https://wordpress.com/');
		debug($res->body);
```

This fails with 

```
Error: stream_socket_client(): Peer certificate CN=`*.wordpress.com' did not match expected CN=`wordpress.com'
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://wordpress.com:443 (Unknown error)
```

However, requests to https://github.com and https://mail.google.com both work correctly for me locally. Is it possible that wordpress.com has a cert error? If I disable SSL host checking I can do a request to wordpress.com.

```php
		$http = new HttpSocket(['ssl_verify_host' => false]);
		$res = $http->get('https://wordpress.com/');
		debug($res->body);

```

**Comment by robertpustulka** [comment]
Seems like I had some mess on my local setuo. But thanks.
