### ISSUE TITLE
Adding translate behaviour to an Entity is always joining with i18n

### ISSUE THREAD

**Issue by adayth** [cakephp/cakephp#6634]
Maybe the title isn't the best to describe my problem.

When I attach Translate behavior to an Entity it automatically joins with i18n in all queries. That's good and was the intended functionality. However this is also causing me some issues.

1 - While testing, if I don't add i18n fixture, the table doesn't exist and cause Exceptions.

2 - If I do a find('list') to retrieve two fields that are not managed by Translated, the query is still joined with i18n table. ¿Why? ¿Is intended? ¿Can avoid it?

3 - RulesChecker->existIn() in models associated with Translated models also joins it with i18n table when search foreign_key id of Translated model.

**Comment by markstory** [comment]
When testing, you should add the required fixtures.

For a find(list), the join is done because the behavior doesn't check which fields are included in the query and assumes that translated fields are always included. The same is true for the queries emitted by RulesChecker methods.

**Comment by adayth** [comment]
Thank you for your answer. 
Would be great if the behavior don't do unneeded joins or maybe only join when using find('translate')

**Comment by markstory** [comment]
But the joins are necessary to fetch the translated content. If the current locale matches the behaviors defaultlocale, then no joins are performed. Perhaps that is a way you can avoid the joins when you don't need them.

**Comment by AD7six** [comment]
> 2 - If I do a find('list') to retrieve two fields that are not managed by Translated, the query is still joined with i18n table. Why? Is intended? Can I avoid it?

Ideally that shouldn't happen, though it's (using a similar behavior) [not that simple to determine when a join is not required](https://github.com/AD7six/cakephp-shadow-translate/blob/master/src/Model/Behavior/ShadowTranslateBehavior.php#L108-L114).

The simplest solution is to remove the behavior of set the locale to the default before calls you know don't require a join.

**Comment by adayth** [comment]
> If the current locale matches the behaviors defaultlocale, then no joins are performed.

That should be advertised in the manual as a potential performance problem.
I did a mess setting up app locale as 'es_ES' and using Translate locales as 'es' and 'us'.
