### ISSUE TITLE
PHP Fatal error:  Call to undefined method Cake\Core\Configure\Engine\PhpConfig::_getFilePath()

### ISSUE THREAD

**Issue by tox777** [cakephp/cakephp#6636]
Cake php not working.
I found the logs server and this's the problem
 PHP Fatal error:  Call to undefined method Cake\Core\Configure\Engine\PhpConfig::_getFilePath()

The server  show me a blank page, or error 500.

I tried to debug error.
On my localhost PhpConfig.php 
        $file = $this->_getFilePath($key, true);
        var_dump($file);die;

Always show the path of the config default (app). But when i try to debug on server production not always show the path of config.

On booststrap.php when cake php invoke 

try {
    Configure::config('default', new PhpConfig());
    Configure::load('app', 'default', false);
} catch (\Exception $e) {
   die($e->getMessage() . "\n");
}

This code not catch the error, show error 500.

The code always broken when try to load the config.

**Comment by AD7six** [comment]
That class [uses the file config trait](https://github.com/cakephp/cakephp/blob/master/src/Core/Configure/Engine/PhpConfig.php#L33) which [implements that method](https://github.com/cakephp/cakephp/blob/master/src/Core/Configure/FileConfigTrait.php#L42).

> But when i try to debug on server production not always show the path of config

I suspect your production server is in an inconsistent state - what version of CakePHP are you using, and (please verify) do the two linked files look the same as the linked code?

**Comment by tox777** [comment]
I'm using CakePHP 3.0.5.

FileConfigTrait, extract of code
*******************************************************************************************************************************
/**
 * Trait providing utility methods for file based config engines.
 */
trait FileConfigTrait
{
    /**
     * The path this engine finds files on.
     *
     * @var string
     */
    protected $_path = null;
...
*****************************************************************************************************************************

And PhpConfig.php extract code:

/**
 * PHP engine allows Configure to load configuration values from
 * files containing simple PHP arrays.
 *
 * Files compatible with PhpConfig should return an array that
 * contains all of the configuration data contained in the file.
 *
 * @deprecated 3.0.0 Setting a `$config` variable is deprecated. Use `return` instead.
 */
class PhpConfig implements ConfigEngineInterface
{

    use FileConfigTrait;

    /**
     * File extension.
     *
     * @var string
     */
    protected $_extension = '.php';

**************************************************************************************************************************

The version of PHP server production is:  PHP Version 5.4.10


phpinfo file (http://batoobah.com/webinfo.php)

**Comment by ADmad** [comment]
Try regenerating composer's autoload file using `composer dump-autoload`.  Also the min. PHP version required by Cake is [5.4.16](http://book.cakephp.org/3.0/en/installation.html#requirements)
