### ISSUE TITLE
TreeBehavior: Conditional deleting of children

### ISSUE THREAD

**Issue by isaacaskew** [cakephp/cakephp#6637]
I'm working with a function to load a parent and delete specific children beneath it, rather than just all children underneath it. The code is similar to this:

    $children = $this->find('children', ['for' => $id])->select('id')->toArray();

    foreach ($children as $child) {
        $team = $this->get($child->id);
        if ($team->external == 1) {
            $team->parent_id = null;
            $this->save($team);
        } else {
            // check to see if child has children; if it does, call this function recursively, otherwise...
            $this->delete($team);
        }
    }

The table doesn't seem to like me after running this function. I have to run a recover afterwards to fix the table. Is the way I'm going about this conditional orphaning the correct way?

Another function I have 'adopts' children, given a new parent id. I remove one team and give all of the children to another node:

    foreach ($children as $child) {
        $team = $this->get($child->id);
        $team->parent_id = $id;
        $this->save($team);
    }

    $this->delete($parent_team);

I think this function might have caused some errors as well. I suppose my main question is, "Is this the correct way to change the parent_ids of a large group of entities without breaking the lft and rghts of the entries and needing a recover() to fix it?"

**Comment by AD7six** [comment]
There's nothing obviously wrong there.

Though probably unrelated, this isn't logical:

```
$children = $this->find('children', ['for' => $id])
    ->select('id')
    ->toArray(); // make an array

foreach ($children as $child) {
    $team = $this->get($child->id); // then look the same row up again
```

Should simple be:

```
$children = $this->find('children', ['for' => $id]);
foreach ($children as $team) {
```

Or similar.

What's the table state before the function runs, what is the exact state after your function has run, and what's the sql log for your function when it runs? Is it deleting or orphaning that is invalidating the table structure? Any means to reproduce the problem you're seeing would help diagnose and fix a problem is there is one.

**Comment by isaacaskew** [comment]
That's true. I think I had written it assuming that I had to 'get' to find the most recent entity with the correct lft and rght values, where if I loaded the children previous and iterated through them and deleted some one at a time, the lft and rght would be accurate to the next 'get'. I might just have had a poorer understanding of how the TreeBehavior works though. :0

**Comment by AD7six** [comment]
> That's true. I think I had written it assuming that I had to 'get' to find the most recent entity with the correct lft and rght values

Good point - when deleting it reads the lft and rght values off the entity. Depending on what you're doing with regards to transactions, that _might_ be a factor in what's happening.

**Comment by isaacaskew** [comment]
I'm fairly certain this was the case; one of my variables was still referencing the for loop 'child' when I should have been using the get variable 'team' - so far I haven't had any more of these issues. A 'maybe' on this resolved status.

If this is indeed the case when it comes to looping conditional children deletes, we might want to post some documentation on that on the TreeBehavior CakePHP 3 page so that others don't run into the same 'expired lft & rght' issues.

**Comment by markstory** [comment]
@isaacaskew Could you put together a change for the docs? It sounds like you have a good understanding of the problem and solution.

**Comment by isaacaskew** [comment]
Absolutely! Let me keep trying to break this to make sure that what I've 'fixed' was an actual solution and not just happenstance, then I'll push up documentation for it.

**Comment by markstory** [comment]
With the docs updated, can this be closed?

**Comment by isaacaskew** [comment]
Sure thing.
