### ISSUE TITLE
Trouble using patchEntity on a many-to-many relationship

### ISSUE THREAD

**Issue by clomil** [cakephp/cakephp#6638]
I have `songs`, `artists`, and the joining/pivot table is `artists_songs`.

An artist can be either a singer (`artist_type=0`) or a writer (`artist_type=1`).

The problem is that I can't save the same artist as **both** a singer and writer to a song.

----

Saving this data works fine because the artist IDs are different.

    artists_songs example data:
    id    song_id     artist_id    artist_type
    1     53          20           0
    2     53          32           1

But if I tried to save this:

    song_id     artist_id    artist_type
    53          20           0
    53          20           1

The end result in the database would actually be:

    song_id     artist_id    artist_type
    53          20           0

----

Here's how I'm saving the above in the database:

        $id = 53;
        $song = $this->Songs->get($id, [
            'contain' => ['Artists']
        ]);

        $this->request->data['artists'][0] = ['id' => 20,'_joinData' => ['artist_type' => 0]];
        $this->request->data['artists'][1] = ['id' => 20, '_joinData' => ['artist_type' => 1]];

        $song = $this->Songs->patchEntity($song, $this->request->data, [
            'associated' => [
                'Artists.*', 'ArtistsSongs.*'
            ]
        ]);

        if ($this->Songs->save($song)) {
            echo('The song has been saved.');
        } else {
            echo('The song could not be saved. Please, try again.');
        }

----

Debugging the save call confirms it.

    debug( $this->Songs->save($song) );

There is only one artist, the first one (`artist_type=0`), in the array:

    object(App\Model\Entity\Song) {
    ...
        'properties' => [
        ...
            'artists' => [
            ...
                (int) 0 => object(App\Model\Entity\Artist) {
                ...
                }
            ]

**Comment by markstory** [comment]
Your associated property definition in the `patchEntity()` call is invalid. That might be part of the issue. Because you are only defining one association (ArtistsSongs) you will not be able to define two joint table records. Instead you should create _two_ associations - one for Artists and one for Singers. That should allow you to save two joint table records with different values for the artist_type column.

**Comment by clomil** [comment]
There is no such thing as Singers. Just Artists.

**Comment by robertpustulka** [comment]
You need two BTM associations: Singers and Writers, both pointing to Artists table but throught different joint tables. Its the matter of your app's design.

**Comment by clomil** [comment]
So if I had:

`songs`
`artists`
`singers_songs`
`writers_songs`

What would the saving code change to? I don't get how to refer to two different joining tables, because in the current saving code it doesn't even refer to the single joining table (`artists_songs`)

**Comment by robertpustulka** [comment]
You wouldn't need to do anything with join tables. 

```php
    $this->request->data['singers'][0] = ['id' => 20];
    $this->request->data['writers'][1] = ['id' => 20];

    $song = $this->Songs->patchEntity($song, $this->request->data, [
        'associated' => [
            'Singers', 'Writers'
        ]
    ]);
```

**Comment by clomil** [comment]
I ended up deleting everything (models, templates, controllers) and baked again.

When the Song Model was baked, it removed the association with `Artists`. So I manually put them in like this:

        $this->belongsToMany('Artists', [
            'foreignKey' => 'song_id',
            'targetForeignKey' => 'contributor_id',
            'joinTable' => 'singers_songs'
        ]);

        $this->belongsToMany('Artists', [
            'foreignKey' => 'song_id',
            'targetForeignKey' => 'contributor_id',
            'joinTable' => 'writers_songs'
        ]);

And it's still having the same problem. It's only recognizing the second belongsToMany relationship (`writers_songs`):

        $song = $this->Songs->get($id, [
            'contain' => ['Artists']
        ]);
        
        print_r($song->artists);

That code shows the associated writers, but not the singers.  If I swap the above order in the Song Model, putting `singers_songs` after `writers_songs`, then it shows the associated singers, but not the writers.

**Comment by robertpustulka** [comment]
You should define seperate associations. 

```php
    $this->belongsToMany('Singers', [
        'className' => 'Artists',
        'foreignKey' => 'song_id',
        'targetForeignKey' => 'contributor_id',
        'joinTable' => 'singers_songs'
    ]);

    $this->belongsToMany('Writers', [
        'className' => 'Artists',
        'foreignKey' => 'song_id',
        'targetForeignKey' => 'contributor_id',
        'joinTable' => 'writers_songs'
    ]);
    
      $song = $this->Songs->get($id, [
        'contain' => ['Singers', 'Writers']
    ]);

    print_r($song->artists);
```

Please read the associations section in CakePHP book carefully.

**Comment by ADmad** [comment]
Closing as there's not issue that needs to be solved.

**Comment by clomil** [comment]
Yep, my mistake. Thanks for your help.
