### ISSUE TITLE
Saving belongsTo association

### ISSUE THREAD

**Issue by hecerinc** [cakephp/cakephp#6639]
I was trying to save a belongsTo association. I have a Quotes table and a Clients table where Clients hasMany Quotes (saving from the quotes controller). I was trying to save the quotes and the client using the FormHelper and then

    $quote = $this->Quotes->patchEntity($quote, $this->request->data, ['associated'=>['Clients']]);

The data array was something like
```php
[ 
   'client' => [
            'key' => 'value'
             ...
   ],
   'quoteProperty' => 'value',
]
```
Patching the entity would ignore the client completely, but I managed to make it work by setting `'client' => true` in the `$_accessible` property of the Quote entity as per the documentation. The whole thing was baked with the bake script, which had originally only set `'client_id'=>true` in the entity. I did manage to make it work, but, shouldn't the bake script set the alias of the parent model instead of the foreignKey in these associations?

**Comment by markstory** [comment]
Bake will set the association properties as accessible in newer versions of bake. It does require that your associations be defined in the table classes first though.
