### ISSUE TITLE
the Auth Class and config method

### ISSUE THREAD

**Issue by minsec** [cakephp/cakephp#6640]
'Form' => [
	'userModel' => 'Admins',
	'fields' => ['username' => 'user_name', 'password' => 'pass_word'],
	'passwordHasher' => ['className' => 'Legacy']
]

with this, I think there's  soming ambiguity.

first view, I think the 'username' means Form input item, and the 'user_name' means Table column name.
so I think it's not friendly.

**Comment by dereuromark** [comment]
Why? You dont have to name your field "user_name". Most of us, including myself, always used "username" as fieldname, and "password" als field name for the password. I don't think this ticket is valid.

**Comment by markstory** [comment]
I don't really understand the ambiguity either. The fields array is mapping the field roles to concrete fields in your table.

**Comment by jhli** [comment]
I do. But you will have to live with it that hash keys are strings rather than for instance rubies symbols. That in result creates code looking like 'username' => 'username'.

**Comment by minsec** [comment]
By this way. I have to let the input element's name attribute of login form same as the Data table'column. If there's SQL Injection attack, they can get the data table's column name directly.

**Comment by jhli** [comment]
Again, I do get your point. Use a SQL view to mask that or understand that obstrufication helps only little. I'd focus on SSL, csrf protection, hashing, salting and OPs security rather than obstrufication.

**Comment by jhli** [comment]
... And not having sql injection holes.

**Comment by minsec** [comment]
I have just start learning the Cake. So when I saw the 'fileds'. I think the key is the input name attribute and the value is the Table column.  I traced all the related function. So embarrassed! I am chinese.T

**Comment by jhli** [comment]
Don't worry. Try to use the google group, stackoverflow and IRC, though. This is no support forum.
