### ISSUE TITLE
How can I include an out php file in the project? 

### ISSUE THREAD

**Issue by minsec** [cakephp/cakephp#6641]
I have an other SDK file, how can I include it.

**Comment by Xety** [comment]
Cake3 ?

**Comment by markstory** [comment]
Use `require` or composer to autoload the library.

**Comment by markstory** [comment]
Use `require` or composer to autoload the classes in the library.

**Comment by minsec** [comment]
require can't New Instance

**Comment by ADmad** [comment]
> require can't New Instance

So create one yourself after including the file.
