### ISSUE TITLE
CakePHP 2.x: Model::saveAll() gets the associations reset before actually saving

### ISSUE THREAD

**Issue by TamasBarta** [cakephp/cakephp#6643]
When I create a model, and call `unbindModel` on it, and just after it a `saveAll`, I get MySQL errors telling me that the ON clause is erroneous, containing fields that are not present (of course not present, that's why I want to unbind the related model).

I started to dig in the `Model` class, and found that in the validation process some `exists` checks are running, and that translates in our project to `SoftDeleteBehavior::existsAndNotDeleted` which runs a `find`, that somewhere calls `Model::resetAssociations`. Wow. That just ruins the whole purpose of running `unbindModel` before `saveAll`. I might be missing something, but now I have to manually unset associations from `Model::belongsTo` the PHP way, so that doesn't get into a temporary container that later even before the first call resets `belongsTo`.

I think this is a bug, but since now I saw so many so strange things in CakePHP, I just don't really know how it should work, or how it should be used.

**Comment by markstory** [comment]
You can unbind permanently for the remainder of the request instead of just for the next operation by setting the second argument to false.

Unfortunately, I don't think there is a way to solve this problem without causing other issues.

**Comment by TamasBarta** [comment]
I also saw that there won't be an easy way, but at least mentioning it in the documentation would be nice. (I'm sure the second parameter of unbind is documented, I mean the strange behaviour)
I've been googling and debugging for hours to solve this mystery.
At least now this issue might be found if someone has the same issue, and your answer gives a decent workaround, but I don't understand your intentions you declared by closing this issue.
Thanks for your fast response though, I appreciate it.

**Comment by markstory** [comment]
I closed the issue because there isn't a code fix we can do to resolve this. Having piles of bugs in the issue tracker that we will never close makes the project harder to manage.
