### ISSUE TITLE
Wrong missing_controller information

### ISSUE THREAD

**Issue by converge** [cakephp/cakephp#6644]
When we try to reach an unknown controller, we get this error warning message:

![captura de tela 2015-05-26 as 18 27 47](https://cloud.githubusercontent.com/assets/188671/7823866/f98cd1f2-03d4-11e5-8948-f6c78093b738.png)

The problem is that, the information says:

If you want to customize this error message, create src/Template/Error/missing_controller.php

And the right information is:

If you want to customize this error message, create src/Template/Error/missing_controller.ctp

**Comment by converge** [comment]
fast guys

**Comment by markstory** [comment]
@converge :smiley:
