### ISSUE TITLE
2.6 Bug: $this->prepend('...') doesn't actually prepend

### ISSUE THREAD

**Issue by SimonEast** [cakephp/cakephp#6647]
In CakePHP 2.6.5 I get the following strange behaviour inside views...

```php
$this->prepend('a', 'a');
$this->prepend('a', 'b');
debug($this->fetch('a'));
// Returns 'ba' as it should
```
```php
// But when using a buffered call
$this->prepend('a', 'a');
$this->prepend('a');
echo 'b';
$this->end();
debug($this->fetch('a'));
// Returns 'ab' and doesn't prepend :-(
```

Forgive me if this has already been discussed or resolved in another version.

**Comment by markstory** [comment]
There is no capturing mode for prepend. When used in capture mode prepend() turns into append(). That could probably be better documented or require that prepend() have a value. If you want to 'prepend' with a capture block you can do it with:

```php
$this->start('region');
// Output here.
echo $this->fetch('region');
$this->end();
```
