### ISSUE TITLE
Customize from address in cakephp while sending sending emails through SMTP

### ISSUE THREAD

**Issue by purnarao** [cakephp/cakephp#6648]
hi,
im using cakephp 2.4.3, i want to send emails using gmail smtp.

my environnement configuration :
WampServer 2.4 64bits on windows 8.1
cakephp 2.4.3
openssl module activated
sending emails using Free SMTP Server works very well
when using this configuration for gmail :

```
public $default = array(
               'host' => 'ssl://smtp.gmail.com',
               'port' => 465,
               'timeout' => 30,
               'username' => 'abc@gmail.com',
               'password' => 'password',
               'transport' => 'Smtp' 
        ); 
```

Here is my Cakephp's Controller code - 

```
        App::uses('CakeEmail', 'Network/Email');
        $email = new CakeEmail('default');
        $email->subject("Testing code");
        $email->body("Hello Purna");
        $email->from("pqr@gmail.com");
        $email->to("purnarao.g@gmail.com");
        $email->send();
```

Now, everything is working fine. The problem is that I am getting email from abc@gmail.com instead of getting from pqr@gmail.com. My requirement is that I will set up smtp with a fixed username and password in email configuration file(email.php) and then need to customize the from address from the controller. If any one have any solution, then please help me out.

Thanks in advance,
Purna.

**Comment by AD7six** [comment]
You need to determine if it's a code/config problem - or whether gmail is simply ignoring your from header (because e.g. you don't own that account).

What are the headers of the received email?

Note that if you [turn logging on](https://github.com/cakephp/cakephp/blob/2.6/lib/Cake/Network/Email/CakeEmail.php#L1159) - the [outbound message and headers will be logged](https://github.com/cakephp/cakephp/blob/2.6/lib/Cake/Network/Email/CakeEmail.php#L1162-L1178),

**Comment by purnarao** [comment]
Thanks @AD7six for your kind reply. I am also guessing that gmail is ignoring from header. But still searching for further solutions. 
The headers that I am getting in the received mail is simply - 
from: abc@gmail.com
to: purnarao.g@gmail.com
date and subject.

**Comment by AD7six** [comment]
@purnarao that text is not what I asked for - it's the whole text when you click "show original" in gmail.

**Comment by imagra** [comment]
Gmail will replacing (ignore) pqr@gmail.com and change FROM field to abc@gmail.com on the server side. No way to avoid it. It seems, it is theirs anti-spam policy.

**Comment by purnarao** [comment]
@AD7six , I got lot of headers in the email. But, following are some of required headers that may you are asking for - Please look the header "X-Google-Original-From".

Delivered-To: purnarao.g@gmail.com
Received: by 10.202.200.130 with SMTP id y124csp129644oif;
        Wed, 27 May 2015 02:45:38 -0700 (PDT)
X-Received: by 10.50.18.39 with SMTP id t7mr2699283igd.3.1432719938194;
        Wed, 27 May 2015 02:45:38 -0700 (PDT)
From: abc@gmail.com
X-Google-Original-From: pqr@gmail.com
To: purnarao.g@gmail.com

**Comment by AD7six** [comment]
> X-Google-Original-From: pqr@gmail.com

That seems to indicate you tried to send an email from `pqr`, and gmail prevented that. Afaik, you can only do things like that if you're trying to send mail from an account already listed in "Send mail as" - but that's gmail specific anyway.

Enabling logging as I indicated previously would help you to confirm that the outbound email headers are match what you ar expecting to see. Closing as this doesn't look like a code problem.
