### ISSUE TITLE
Unable to locate widget class "App\View\Widget\BasicWidget"

### ISSUE THREAD

**Issue by imagra** [cakephp/cakephp#6649]
I have tried to create my own form widgets and got this error. After some research I have tried to check this on fresh and clean installation. Result is the same. Below you can see the steps to reproduce. 

1) Run ``composer create-project --prefer-dist cakephp/app dev-03``
2) Copy ``/www/cake-3/dev-03/vendor/cakephp/cakephp/src/View/Widget/BasicWidget.php``
to  ``/www/cake-3/dev-03/src/View/Widget/BasicWidget.php``
3) Add to AppController.php
```
...
class AppController extends Controller {
	public $helpers = [
		'Form' => [
			'widgets' => [
				'_default' => ['App\View\Widget\BasicWidget'],
			],
		],
	];
...
```
4) Insert into ``/www/cake-3/dev-03/src/Template/Pages/home.ctp``
```
<?php 
    echo $this->Form->create($page);
    echo $this->Form->input('test');
    echo $this->Form->end();
 ?>
```
5) Error 500: Unable to locate widget class "App\View\Widget\BasicWidget"

**Comment by robertpustulka** [comment]
Have you changed a namespace of the copied class?

**Comment by imagra** [comment]
Robertpustulka, thank you! Changing namespace to ``namespace App\View\Widget;`` fixed the error. 
The issue can be closed, shame on me!
