### ISSUE TITLE
Element with empty key added to properties during save when foreign key is set to false

### ISSUE THREAD

**Issue by aydot** [cakephp/cakephp#6652]
Ran into an issue I thought to comment on.

Save associated on hasOne with foreign key set to false adds elements with empty key here 
[https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/HasOne.php#L124]

This will eventually give an error when you try to use a get() on the element with the empty key.

If this is not clear enough, I can try to recreate the error and post it later on.

**Comment by markstory** [comment]
It looks like saving associated records should just be skipped if the foreignKey is falsey. I don't think the ORM could easily figure how to save the associated records.

**Comment by aydot** [comment]
I set the foreignKey to false because I wanted my join to happen on a different condition passed into the hasOne association. It did save the record, but it was a weird output. Basically took the joined key value and made it the primary key value. I didn't research on it further though as I shouldn't really be saving through such association.
If it was an hasMany however, I might want the save to happen, as it still saves the record, and I won't care what the primary key values are.

**Comment by markstory** [comment]
In the case of a hasMany with no foreign key, the ORM cannot associate the records together as it doesn't know which column to seed with the parent record's primary key. I guess we could implicitly trust that the end developer has not made a mistake though.

**Comment by aydot** [comment]
Can we make it known in the documentation that this could happen?

**Comment by markstory** [comment]
We could, I think the newish 'bindingKey' option might help, or using 'conditions' in the association definition instead of foreignKey = false.

**Comment by aydot** [comment]
:+1: 'bindingKey' option

**Comment by markstory** [comment]
@aydot Is a fix still needed now that bindingKey exists?
