### ISSUE TITLE
Make BaseAuthenticate::_findUser() return a query object?

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#6656]
When extending the BaseAuthenticate class I find myself sometimes wanting to do things with the result before it converts it to an array, and if so I end up having to rewrite the `_findUser()` method in my extended class instead of calling it.

I was thinking a simple workaround that would preserve compatibility would be to break `_findUser()` into two methods:

`_find()` (behaves much like an ORM find method and returns a query)
`_findUser()` (calls `_find()` internally)

Untested gist of how this might work:  https://gist.github.com/kevinquinnyo/96ff4130f882101e24d5#file-gistfile1-php

This would allow developers to call `$this->_find()` from an extended class and have the option to do additional things with the query before returning a record array in their custom class's `authenticate()` method.

Good idea?  Bad idea?  Terrible idea, gtfo?

**Comment by kevinquinnyo** [comment]
Basically this:  https://github.com/kevinquinnyo/cakephp/tree/3.0-base-authenticate

I don't have tests for it but I could add them.   Anyway I know this isn't super critical, but let me know if it's something you all are interested in.  I think it would simplify a custom Authenticate class I've written for a private project.

**Comment by markstory** [comment]
The diff you have doesn't seem unreasonable to me. Separating the query build + data conversion steps gives the methods nicer separation and makes it easier for developers to extend the code like you mentioned.

**Comment by kevinquinnyo** [comment]
Cool!  Thanks for the reply.  FYI I believe the diff I have breaks nothing, and I assume actually requires no additional tests as it's just a protected function calling another protected function that (should) produce the same end result.

Let me know if there's anything I can do to help.

**Comment by ADmad** [comment]
I like this change but given that the signature of `_findUser()` is changed it won't be backwards compatible and I am sure there are many custom authenticate classes out that which override it.

**Comment by kevinquinnyo** [comment]
Oh right.  That's a good point @ADmad.  Maybe there's a clever workaround that I can't see right now.

**Comment by kevinquinnyo** [comment]
Just following up on this since I got sidetracked and forgot about it.  If there's no way to do this without breaking the signature of `_findUser()` then it should probably either be put on the backburner for a major release, or just closed if there is expected to be a lot of refactoring on the Authenticate and friends classes for the next major release.

It's really not a big deal to overload `_findUser()` anyway to be honest.  I only opened this issue because I thought I had an easy fix that wouldn't break BC.

**Comment by markstory** [comment]
Is there no way to make it backwards compatible?

**Comment by ADmad** [comment]
There should be, I'll look into it.

**Comment by markstory** [comment]
Closing as #6690 looks like backwards compatible way to solve this.
