### ISSUE TITLE
Internationalization bug

### ISSUE THREAD

**Issue by Kwaadpepper** [cakephp/cakephp#6660]
I just saw that changing I18n::locale() at run time change intl fields (on ctp) but doesn't changes the Active records fields to translate them, it makes a mix between different languages.

So if 
  in bootstrap : ini_set('intl.default_locale','fr');
  in controller : I18n::locale('en')

i will also have to do in controller : ini_set('intl.default_locale', I18n::locale());

Is this a wanted behavior ?

**Comment by markstory** [comment]
Are you fetching the records before changing the default locale? From looking at the behavior code, each find should use the locale name returned from `I18n::locale()` and not the defaultLocale.

**Comment by Kwaadpepper** [comment]
I'm setting the I18n::locale('en') in the AppController::initialize

with this code
```
if (!empty($this->request->lang)) {
			I18n::locale($this->request->lang);
		}

		if ($this->request->session()->check('lang') and empty($this->request->lang)) {
			I18n::locale($this->request->session()->read('lang'));
		}
```

**Comment by markstory** [comment]
Closing until we have a reasonable way to reproduce this.

**Comment by AD7six** [comment]
There's some general confusion here. The I18n class only refers to that ini setting [the very first time it it used](https://github.com/cakephp/cakephp/blob/master/src/I18n/I18n.php#L243)

Thereafter, changing the ini setting won't do anything.
