### ISSUE TITLE
3.x Q) Why are table classes lowercase and CapsCase?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#6661]
I'm interested to know why in my application I define my table classes using CapsCase, but internally in the table class, the alias is lowercase and in the association collection they are lowercase.

Here is what I'm doing, which led me to my question to give it some context. I'm containing related tables by traversing the tables associations.

```php
// src/Model/Behavior/ExampleBehavior.php

    foreach ($this->_table->associations()->getIterator() as $table => $association) {
         pr($table->alias()) // 'examples'
         pr(Inflector::humanize($table->alias()); // 'Examples'

        // However if we assume that the table class is `AttributeTypes`
         pr($table->alias()) // 'attributetypes'
         pr(Inflector::humanize($table->alias()); // 'Attributetypes'
    }
```

So if you are configuring table classes, I would follow the table class association and use CapsCase, but it seems that once it's in the `AssociationCollection` that CapsCase is lost, and it's very hard to get back.

**Potential solutions?**
For me currently I'm using this to make my behaviour config lowercase.
```php
$this->config('omittedTables', array_map('strtolower', $this->config('omittedTables')));
```

Alternatively I'd quite like the `AssociationCollection` to store the CapsCase version as defined in the table class relationship.

**The issue**
The issue I hit was that when checking tables `'Examples' !== 'examples'`, `'AttributeTypes' !== 'attributetypes'`

**Comment by markstory** [comment]
Table aliases shouldn't be lowercase by default. By default the aliases are generated based on the class names. How are you constructing your table instances/making associations?

**Comment by davidyell** [comment]
I'm working on my Packages endpoint, so my PackagesTable has.

```php
// Cut down example
class PackagesTable extends Table {
    public function initialize(array $config)
    {
        //etc
        $this->belongsTo('Broadbands');
        $this->belongsTo('Calls');
        $this->belongsTo('Providers');
        $this->belongsTo('PackageTypes');
       // More tables
    }
}
```

**Comment by davidyell** [comment]
I've just tried adding a specific `$this->alias('Broadbands')` to my table and it's still being returned in lowercase by `var_dump($this->_table()->associations()->keys());`

**Comment by davidyell** [comment]
Could it be this?
https://github.com/cakephp/cakephp/blob/master/src/ORM/AssociationCollection.php#L56

**Comment by markstory** [comment]
Oh I misread, I thought the table's alias() method was wrong. The internal keys of the collection are lowercased to prevent case dependent typos.

**Comment by davidyell** [comment]
Oh I see, in which case, how do I get the actual table class name from the AssociationCollection?

Glad you replied, I'd just changed the class and updated the test and was about to submit a PR :sos:

**Comment by markstory** [comment]
`$this->associations()->get($name)->alias();`

**Comment by davidyell** [comment]
Ace, thanks!
