### ISSUE TITLE
4.x Add Typehinting Hack to allow PHP7 Typehints

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#6665]
Ref A: http://php.net/manual/en/language.oop5.typehinting.php#83442
Ref B: http://www.phpclasses.org/blog/post/269-PHP-7-Scalar-Type-Hinting-Finally-Approved.html
Basic idea: once PHP 7 is released and stable, if there is the will to migrate faster the hack above (Ref A) could be utilized to keep backwards compatibility with older PHP versions and still have all the nice typehints without errors. Only speed would be the question (but the hack would only need to be enabled if the PHP version is < 7)

**Comment by markstory** [comment]
Interesting idea. We would need to profile how slow a typehint hack would actually be, but the possibility to do scalar typehints in a backwards compatible way could be really neat.

**Comment by robertpustulka** [comment]
:+1: 

I'm wondering - if speed wouldn't be much of a problem - whether this hack could be applied to the future 3.x versions (>=3.2)?

**Comment by ravage84** [comment]
Has this Typehint hack ever been implemented in a larger code base (except the author's)?

Also according to the php.net page, the comment with the Typehint hack is seven years old.

> 7 years ago

Not sure we really should pursue this...

**Comment by dereuromark** [comment]
I think the main issues arise where a lot of iterations are, e.g. the Routing, Hash class and CO.
Those, on a complete framework basis this could have quite the negative impact as a total sum of "overhead".
But someone should first confirm before we close this too fast.
I like the idea, though.

**Comment by markstory** [comment]
@dereuromark I agree we should evaluate the impact of this kind of 'hack'. My gut/past experience around error handlers leads me to believe that it will be prohibitively slow.

**Comment by ionas** [comment]
This was basically meant as a ticket for the far future to allow to migrate to PHP 7.x faster once it is stable and well tested/used and not be bottle-necked by having to support PHP 5.4+ and thus not utilizing scalar typehints cause of that. Question is how important what margin of loss of speed is for those being able to migrate to a newer cake version but not a newer PHP version, then.

**Comment by dereuromark** [comment]
I don't think Cake4 will be PHP7, more like PHP5.6+. But I get what you mean and it is nice to have this option once it becomes clear to switch to PHP7.

**Comment by robertpustulka** [comment]
@markstory A comment [below](http://php.net/manual/en/language.oop5.typehinting.php#111411) presents some benchmarking and two much faster alternatives.

**Comment by HavokInspiration** [comment]
Maybe, as a starting point, it could be tried on one of the split, like Utility. The code base is rather small.
It might gives us some hints about the impact on performance. It would not necessarily be the real picture, but if just on Utility, performances collapse, it would be a good indicator.

**Comment by dereuromark** [comment]
Closing as too theoretical - if this becomes more concrete we can still evaluate if it is useful for shimming.
Other than that we have to wait till 7.1 features are fully usable anyway.

**Comment by inoas** [comment]
As 7.1 is no targeted I do think we can move away from this idea entirely and just require 7.1. minimum and whatever typehints that offers.
