### ISSUE TITLE
Syntax erro after update to cake 2.6.6

### ISSUE THREAD

**Issue by igorpadovan** [cakephp/cakephp#6667]
I have many server, where the php is PHP 5.3.3-7+squeez the following error ocurred, where it's PHP 5.4.39-0+deb7u2 I didn't have problem.
```php 
syntax error, unexpected '[' in Vendor/cakephp/cakephp/lib/Cake/Controller/Component/RequestHandlerComponent.php on line 232
```

**Comment by markstory** [comment]
I'm a tool.

**Comment by markstory** [comment]
I'll make a new release with the correct array() call.

**Comment by josegonzalez** [comment]
http://didmarkbreakthebuild.com/

**Comment by markstory** [comment]
2.6.7 has been tagged.

**Comment by tersmitten** [comment]
Great work @markstory, not even cakefest is stopping you from fixing bugs :-)
