### ISSUE TITLE
3.0 - incorrect table definition during fixture creation

### ISSUE THREAD

**Issue by PGBI** [cakephp/cakephp#6668]
I have the following table:

    CREATE TABLE `users` (
    `id` BIGINT UNSIGNED NOT NULL,
    `other_field` INTEGER(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`id`),
    UNIQUE KEY `other_field` (`other_field`)
    ) ENGINE=InnoDB

I have defined UsersFixtures with `public $import = ['table' => 'users'];`

When running phpunit, testing fails during fixture generation because I get the following mysql error: "Incorrect table definition; there can be only one auto column and it must be defined as a key".

After checking the sql command generated by cakephp to create the table users, I found this:

    `CREATE TABLE `users` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `other_field` INTEGER(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`id`),
    UNIQUE KEY `other_field` (`other_field`)
    ) ENGINE=InnoDB

If I understand, Cakephp is automatically adding a AUTO_INCREMENT to Primary fields which makes setups like mine (where primary field is not auto incremented, but generated in `beforeSave()` and where an other field is auto incremented) fail.

**Comment by ADmad** [comment]
I am curious, what's the point of having an auto increment field which is not primary key?

**Comment by markstory** [comment]
Having the autoincement not involved in the primary key at all is somewhat odd. Like @ADmad I wonder why one would do this?

**Comment by AD7six** [comment]
I was surprised it's valid. Another curious++.

**Comment by PGBI** [comment]
Since Mysql allows this kind of setup, shouldn't cakephp cope with it?

Okay, I recognize my setup is a bit odd. At first, I decided not to have an autoincrement but a randomly generated primary id because in my app the id is public. Latter, for internal purpose, it seemed to me convenient to still have an auto increment field ("yeah, you are the 1000th subscriber!!"). Hope this answers your question :)

My turn to ask you one! This is where cakephp adds the auto increment in the table schema generation:
http://api.cakephp.org/3.0/source-class-Cake.Database.Schema.MysqlSchema.html#335-339
Why would cakephp add the auto increment option to a primary field even if `$data['autoIncrement']` is not set to true? I just don't understand.

**Comment by ADmad** [comment]
> At first, I decided not to have an autoincrement but a randomly generated primary id because in my app the id is public. Latter, for internal purpose, it seemed to me convenient to still have an auto increment field ("yeah, you are the 1000th subscriber!!"). Hope this answers your question :)

Mind == blown

**Comment by ADmad** [comment]
> Since Mysql allows this kind of setup, shouldn't cakephp cope with it?

Not necessarily, Mysql allows other stupidity too like all zero values in date/datetime fields which we don't cope with.

> http://api.cakephp.org/3.0/source-class-Cake.Database.Schema.MysqlSchema.html#335-339
Why would cakephp add the auto increment option to a primary field even if $data['autoIncrement'] is not set to true? I just don't understand.

I don't really have an answer to that, maybe cause no one considered usage like yours. You can provide a patch fixing it if it doesn't break any existing tests.

**Comment by PGBI** [comment]
> I don't really have an answer to that, maybe cause no one considered usage like yours. You can provide a patch fixing it if it doesn't break any existing tests.

I have a patch ready (https://github.com/PGBI/cakephp/commit/bd890be4d2572414b71e5c844f75749b8bd5eec7) but it does break existing tests. I don't know if there is a good reason why cakephp would automatically add auto increment to primary field, which is why I haven't submitted any PR yet.

**Comment by markstory** [comment]
@PGBI The main reason that we put autoincrement onto primary keys that are also integers is because generally the conventions of CakePHP indicate that integer primary keys are autoincrements.

The existing code checks for `column == primary key || autoIncrement == true` which should let this column definition through but clearly isn't.

**Comment by PGBI** [comment]
Thanks!
