### ISSUE TITLE
Cake PHP Blog Tutorial MySQL Error

### ISSUE THREAD

**Issue by pckrishnadas88** [cakephp/cakephp#6669]
The posts insert query for the blog tutorial in the cake cook book throws mysql error. Please fix it. Corrected query is given below.

INSERT INTO posts (title, body, created)
VALUES ('The title', 'This is the post body.', NOW());
INSERT INTO posts (title, body, created)
VALUES ('A title once again', 'And the post body follows.', NOW());
INSERT INTO posts (title, body, created)
VALUES ('Title strikes back', 'This is really exciting! Not.', NOW());

**Comment by ADmad** [comment]
Please provide the generated query and error and what code generates it.

**Comment by ADmad** [comment]
I tried the queries provided in [this](http://book.cakephp.org/2.0/en/tutorials-and-examples/blog/blog.html#creating-the-blog-database) tutorial section and did not get any errors.

**Comment by AD7six** [comment]
Also: wrong repo.

**Comment by ADmad** [comment]
@AD7six I was tempted to use https://github-issue-mover.appspot.com/  by then thought: "Meh.." :stuck_out_tongue:

**Comment by pckrishnadas88** [comment]
![screenshot from 2015-05-29 13 19 25](https://cloud.githubusercontent.com/assets/5269476/7878549/5f9d93f0-0605-11e5-88a5-2b3281430b40.png)
Copied the query from
![screenshot from 2015-05-29 13 20 25](https://cloud.githubusercontent.com/assets/5269476/7878558/7ef1fd36-0605-11e5-9a74-7fa7c5820438.png)

**Comment by pckrishnadas88** [comment]
Query is correct in the website HTML.. try copying from the pdf.

**Comment by AD7six** [comment]
@pckrishnadas88 thanks for providing enough detail to see what problem you're looking at - it's still the wrong repo to report this though.

**Comment by ADmad** [comment]
As you can see in the PDF the single quotes are replaced by backticks. It's probably and issue with latex to pdf conversions and I don't think it can be easily fixed.

**Comment by pckrishnadas88** [comment]
Thanks for the fast response.. I just started with cake.. If this is the wrong repo.. Please report it to the correct repo so that we can improve the quality of the cake. A beginer may ran away if he sees error in the very first example.

**Comment by ADmad** [comment]
> I just started with cake.

Then you should be trying out CakePHP 3.0 instead of 2.x :)

The repo for the manual is https://github.com/cakephp/docs

**Comment by AD7six** [comment]
Doesn't look like there is anything to fix

![screenshot from 2015-05-29 10 01 28](https://cloud.githubusercontent.com/assets/33387/7878725/bb0741ee-05e9-11e5-83b5-f793265414e7.png)

**Comment by pckrishnadas88** [comment]
@AD7six  The quotes in the VALUES are different in my pdf and your's. I don't know how it came. Watch it closely :)

**Comment by AD7six** [comment]
@pckrishnadas88 I see the difference, I'm saying I do not observe the current pdf version of the docs having the problem you report. Anyway, if there's further input please create a new ticket on the docs repo with enough info for someone/anyone to observe/reproduce the problem in the _current_ downloads.
