### ISSUE TITLE
Pagination component can't sort on associated tables

### ISSUE THREAD

**Issue by pgmassari** [cakephp/cakephp#6670]
My models:
`Products belongsTo Suppliers`
`Suppliers hasOne Products`

In my Products controller i set the pagination like this:
```php
public $paginate = [
    'Products' => [
        'contain' => [
            'Suppliers',
         ],
        'sortWhitelist' => [
            'Products.id',
            'Suppliers.id',
        ],
    ]
];`
```

In my view:
```php
$this->Paginator->sort('Purchases.id', 'Product id', ['model' => 'Products']);
$this->Paginator->sort('Suppliers.id', 'Supplier id', ['model' => 'Products']);
```

Because of this
https://github.com/cakephp/cakephp/pull/6611/files#diff-2cfd461b09a4f24b6b577d6df6fc068aR347
https://github.com/cakephp/cakephp/pull/6611/files#diff-2cfd461b09a4f24b6b577d6df6fc068aR358

I can't sort anymore on Suppliers.id 

I found out that `$tableAlias === 'Products'` and `$alias === 'Suppliers'`.
I was expecting `$tableAlias === 'Suppliers'`.

This used to be working in 3.0.5

EDIT: changed 'hasMany' to 'hasOne'

**Comment by AD7six** [comment]
> `$this->Paginator->sort('Suppliers.id', 'Supplier id', ['model' => 'Products']);`

Are you _sure_ that used to work? What was the generated sql? It's not possible to sort on a hasMany anything - as the Supplier's table won't be in the main query.

**Comment by AD7six** [comment]
Ah nvm I read it the wrong way round, that should work and needs looking at.

FWIW you don't need to use the supplier's alias at all this would work for your given example:

    $this->Paginator->sort('Purchases.supplier_id', 'Supplier id');

**Comment by ADmad** [comment]
Looks like #6611 caused this issue.

**Comment by pgmassari** [comment]
@AD7six I confirm it used to work. The example I provided is 'dumbed down', so I might have left something behind. Sorry about this.

@ADmad I think so. If i paste the previous code for PaginatorComponent from the previous milestone, it works as expected.

**Comment by dereuromark** [comment]
Indeed. We have to return early in case we don't validate and a prefix is already given.

**Comment by markstory** [comment]
Closing as there is a pull request up now.
