### ISSUE TITLE
checkbox label attribute glitch

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#6672]
What was done:
```php
<?= $this->Form->input('active', ['type' => 'checkbox', 'label' => 'Activate']); ?>
```

Expected output:
```html
<label for="active">Activate</label>
<input type = 'checkbox' name="active" id="active" />
```

Rendered output:
```html
<label for='active'>
<input type = 'checkbox' name="active" id="active" />
</label>
```

**Comment by ADmad** [comment]
This is the expected output not a glitch. 

It's done this way to easily support ui frameworks like bootstrap. If you don't want the input to be nested inside the label customize the form templates.
