### ISSUE TITLE
Question: update field(s) using model

### ISSUE THREAD

**Issue by Kwaadpepper** [cakephp/cakephp#6675]
I know to ways to update a model field(s) : 

	// using query builder
	$this->loadModel('Messages');

	$query = $this->Messages->find()->update()
	->set(['`message`' => $this->request->data['message']])
	->where(['`id`' => $this->request->data['id']]);
	$query->execute();

OR

	// using model
	$message = $this->Messages->find()->where(['id' => $this->request->data['id']])->first();
	$this->Messages->patchEntity($message, ['message' => $this->request->data['message']]);
	$this->Messages->save($message));

the first one uses query Builder, so no model behaviors etc, the second force us to find the model and then updated it.

Is there anyway the use the second method but doing and update .. where ... ?
This is because of the need of the behaviors (intl, etc), i could not found anymore info on the docs.

**Comment by dereuromark** [comment]
updateAll() - http://book.cakephp.org/3.0/en/orm/saving-data.html#bulk-updates
But this is a bugtracker, not a support forum.

**Comment by Kwaadpepper** [comment]
Thanks, sry for that
