### ISSUE TITLE
slim down the cakephp.org homepage

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#6676]
This is a little bit nitpicking, I know, but not everyone visits cakephp.org on a big pipe. Even with a decent connection the cold cache hero loading brings back Netscape 3.0 memories.

On a glance images and esp. the hero background over the fold have a lot of potential of compressing them down without compromising visual fidelity.

It's not a real bug, but cake could leave a better first impression here and it looks like a low hanging fruit.

**Comment by markstory** [comment]
I'll see what can be done.

**Comment by markstory** [comment]
Closing this up as I've got a pull request to update the website to optimize the assets a bit.

**Comment by josegonzalez** [comment]
Actually closing because @markstory needs moar coffee.

**Comment by markstory** [comment]
@josegonzalez :clap:
