### ISSUE TITLE
3.0: New design for generated files.

### ISSUE THREAD

**Issue by mtkocak** [cakephp/cakephp#6679]
Currently the design for generated views looks ugly not feels ready to use. I can write schemas ready for foundation with the ready designs I use at my commercial projects. 

If you have some other ideas about this please tell.
![screen shot 2015-05-29 at 20 40 48](https://cloud.githubusercontent.com/assets/545472/7889997/57ee2294-0643-11e5-9ee2-920c390a0c3a.png)

**Comment by dakota** [comment]
I quite like the default bake layout. It's clean and simple. It's not meant to be used for production.

That said, it is very simple to create custom a bake theme that you can release open source.

**Comment by markstory** [comment]
If we can get an improved layout, that is even better, I would be :+1: for it. The last attempt at this didn't go super well because the resulting HTML and CSS was looking like it was going to be challenging/complex to maintain.

I think any new styles for bake need to strike a balance between visually pleasing and simple enough that it isn't daunting for new developers to grok or difficult to maintain.

**Comment by mtkocak** [comment]
Let's start with concepts. Define them and design comes after. I am doing a little research about it now. 
What are common elements, what is needed for optimization. (for now foundation is used right? so it should be responsive) Common elements could be something like navigation or footers etc. Also, what people's opinion? Are easier to use, accessible? Despite looking ugly and having hospital surgery room colors, In my opinion they are a little difficult to hack too.
Do we have any statistics about how people use cakephp views, any specific audience etc? I am thinking also to pay attention some of usability principles for screen readers etc.

I am willing to work on this now and I can create some alternatives... (by the way I started to study design as second major :) I finished my first semester today)

**Comment by dakota** [comment]
It seems like you've got some ideas floating around in your head (And based on your screenshot, in code already). May I suggest creating a bake theme (http://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme) and linking to it here.

I'm quite a fan of the hospital colour scheme, but I'm open to improvements :)

**Comment by mtkocak** [comment]
@dakota thank you for your encouraging comments! I already know how to create a bake and create bake themes for a long time. You can check them at: https://github.com/mtkocak/Cakephp-Bootstrappifier https://github.com/mtkocak/bootstrap2cake

Here I recommend to brainstorm all together, instead of hard coding everything by myself and pulling it. I think latter way is more appropriate. Do you have any ideas to add? If not thank you for your advices.

**Comment by markstory** [comment]
The current colors come from the CakePHP brand palette which is where they originally came from.

I don't think we have much data on who/how uses the baked views. My hunch is that they are only used for admin facing UI's or temporarily as people are in the early stages of application development. However, I have no data to back any of those assumptions up.

**Comment by mtkocak** [comment]
Current design screenshots.
![hnsgjnsc5taaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/545472/7893694/8d76b8fa-0660-11e5-997e-a4c81cc6cc80.png)
![8ftotrwwakxawaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/545472/7893695/8d77ad64-0660-11e5-8585-d55c68bb9ad0.png)
![xc203xyakk2vqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/545472/7893697/8d7b1dfa-0660-11e5-9d63-6d7c87c5cf04.png)
![gxgaeeeeaaaqqqqaabbbbaaaeeeeaaaqqqqaabbbbyawecurntmohcifhyjaaccccaaaiiiiaaaggggaaccccaaaiiiiaaagisgqcb3ik2 b8bzal40zv8yzmaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/545472/7893696/8d7950ce-0660-11e5-80f3-5aca0b016990.png)
![hxg5tyownhniaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/545472/7893698/8d7b365a-0660-11e5-8901-1eb30e361d7e.png)

**Comment by mtkocak** [comment]
problems at first sight:

1. Paddings, margins are not equal
2. There is not a grid on the design.
3. Elements are distributed
4. No information hierarchy at all
5. Actions Sidebar header is unnecessary

**Comment by bravo-kernel** [comment]
:+1: for the initiative

**Comment by jhli** [comment]
:+1:

Did you look st the last approach.
Also the basic cake bake views and its layout do bad practise by dom pollution.

**Comment by ionas** [comment]
Here are some shots from the old initiative to add some inspiration maybe:

![screen shot 2014-09-29 at 10 10 41](https://cloud.githubusercontent.com/assets/106845/4439249/5c951222-47b6-11e4-9ef5-79967fc5558b.png)
![screen shot 2014-09-29 at 10 10 56](https://cloud.githubusercontent.com/assets/106845/4439250/5c99aeb8-47b6-11e4-8401-f170c2494c99.png)
![screen shot 2014-09-29 at 10 12 12](https://cloud.githubusercontent.com/assets/106845/4439252/5ca4cb36-47b6-11e4-83fa-21e05dfa6b00.png)
![screen shot 2014-09-29 at 10 12 39](https://cloud.githubusercontent.com/assets/106845/4439251/5ca39a5e-47b6-11e4-9027-dc437ee6a67f.png)
![screen shot 2014-09-29 at 10 14 12](https://cloud.githubusercontent.com/assets/106845/4439254/5cb1036a-47b6-11e4-8c97-ab37d9a11d04.png)
![screen shot 2014-09-29 at 10 14 15](https://cloud.githubusercontent.com/assets/106845/4439253/5caeb0a6-47b6-11e4-82bb-b708f3d493f1.png)
![screen shot 2014-09-29 at 10 14 38](https://cloud.githubusercontent.com/assets/106845/4439255/5cb46d52-47b6-11e4-82ab-1a0fcae5d894.png)
![screen shot 2014-09-29 at 10 14 46](https://cloud.githubusercontent.com/assets/106845/4439256/5cbf5fe6-47b6-11e4-9ee9-86a4b4000f78.png)
![screen shot 2014-09-29 at 10 15 22](https://cloud.githubusercontent.com/assets/106845/4439258/5cc42f30-47b6-11e4-9004-fbcf1936fcbb.png)
![screen shot 2014-09-29 at 10 26 49](https://cloud.githubusercontent.com/assets/106845/4439257/5cc26786-47b6-11e4-859b-ad59de0b64df.png)
![screen shot 2014-09-29 at 10 27 18](https://cloud.githubusercontent.com/assets/106845/4439260/5cd3a42e-47b6-11e4-8fee-1298acd9d0c9.png)
![screen shot 2014-09-29 at 10 27 47](https://cloud.githubusercontent.com/assets/106845/4439261/5cd5ef22-47b6-11e4-96cd-0ae74074458a.png)
![screen shot 2014-09-29 at 10 27 52](https://cloud.githubusercontent.com/assets/106845/4439259/5cd21a78-47b6-11e4-9760-1b75f90955ce.png)
![screen shot 2014-09-29 at 10 27 58](https://cloud.githubusercontent.com/assets/106845/4439264/5ce6e886-47b6-11e4-9b5c-ba5d92a62a3a.png)
![screen shot 2014-09-29 at 10 32 45](https://cloud.githubusercontent.com/assets/106845/4439262/5cdf404a-47b6-11e4-8597-e016eb4cbc9d.png)
![screen shot 2014-09-29 at 10 33 50](https://cloud.githubusercontent.com/assets/106845/4439263/5ce0c762-47b6-11e4-9d88-e1b1acbf47ee.png)
![screen shot 2014-09-29 at 10 34 14](https://cloud.githubusercontent.com/assets/106845/4439265/5cf4813a-47b6-11e4-8844-b5d7e65068eb.png)
![screen shot 2014-09-29 at 10 35 06](https://cloud.githubusercontent.com/assets/106845/4439266/5cf55c54-47b6-11e4-8752-b8d9e8a00e21.png)
![screen shot 2014-09-29 at 10 36 06](https://cloud.githubusercontent.com/assets/106845/4439267/5cfd6f52-47b6-11e4-8ffe-68ca108ec469.png)
![screen shot 2014-09-29 at 10 48 28](https://cloud.githubusercontent.com/assets/106845/4439269/5d023000-47b6-11e4-9204-98e034bd5cb5.png)
![screen shot 2014-09-29 at 10 48 38](https://cloud.githubusercontent.com/assets/106845/4439268/5d01e096-47b6-11e4-8e75-5346ba1892d5.png)
![screen shot 2014-09-29 at 10 48 41](https://cloud.githubusercontent.com/assets/106845/4439270/5d0d23f2-47b6-11e4-92b5-2f13665501a2.png)

**Comment by mtkocak** [comment]
:+1:

**Comment by mtkocak** [comment]
@ionas valuable experience

**Comment by mtkocak** [comment]
@markstory is there any official brand identity guideline?

**Comment by mtkocak** [comment]
current color scheme extracted from cake.css
![29aginubzbzeaaqiecbagqiaaaqiecbagqiaaaqiecbagqiaaaqiecbagqibapqicqpxkmueaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecgaqt fz25maxhbq1maaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/545472/7896391/eccaa6d8-06b8-11e5-8203-f43b9510bc52.png)

**Comment by mtkocak** [comment]
Colors extracted from logo wallpaper
![screen shot 2015-05-30 at 10 43 06](https://cloud.githubusercontent.com/assets/545472/7896395/09483a96-06b9-11e5-9a43-2df2b8d83d36.png)

**Comment by mtkocak** [comment]
Official logo colors.

![screen shot 2015-05-30 at 10 52 56](https://cloud.githubusercontent.com/assets/545472/7896443/1c9d51ac-06ba-11e5-938d-11ae76992064.png)

**Comment by mtkocak** [comment]
adequate completemntary colors generated by paletton.com 
![img](https://cloud.githubusercontent.com/assets/545472/7896467/c94b7d98-06ba-11e5-962d-4d439936c11d.png)
![screen shot 2015-05-30 at 10 56 52](https://cloud.githubusercontent.com/assets/545472/7896466/c94a616a-06ba-11e5-8479-6c8452c62095.png)
http://paletton.com/#uid=33k0u0krEtvhbBXmbv9uanOyPiP

**Comment by mtkocak** [comment]
Shades with color codes

![screen shot 2015-05-30 at 11 00 15](https://cloud.githubusercontent.com/assets/545472/7896480/6c6b1178-06bb-11e5-84bf-815055f82b81.png)

**Comment by mtkocak** [comment]
generated css file https://gist.github.com/mtkocak/3c8551f1d4f565e1f946

**Comment by mtkocak** [comment]
http://hexpreview.com/(15848F)(1798A5)(0097a7)(DCE47E)(8D6E65)(7A6058)(C3232D)(626262)(6F6F6F)(B7E3EC)(747474)(000000)() hexpreview codes of cake.css

**Comment by mtkocak** [comment]
current color scheme and text fails almost each case according to http://www.w3.org/TR/WCAG20/

![screen shot 2015-05-30 at 11 17 16](https://cloud.githubusercontent.com/assets/545472/7896525/a2bc2d78-06bd-11e5-94bf-33c8f525d4bf.png)
![screen shot 2015-05-30 at 11 15 34](https://cloud.githubusercontent.com/assets/545472/7896526/a2bc7cce-06bd-11e5-93f0-e36b0f3c8253.png)
![screen shot 2015-05-30 at 11 14 43](https://cloud.githubusercontent.com/assets/545472/7896524/a2bb4ac0-06bd-11e5-9f80-64fa3b25de8a.png)

anlysis made using: http://www.paciellogroup.com/resources/contrastanalyser/

**Comment by mtkocak** [comment]
contrast test advises changing color based on wcag2

 http://contrast-finder.tanaguru.com/result.html;jsessionid=18E64D20141AC8FDB94C5AB67E95A41A?foreground=%23ffffff&background=%2315858F&isBackgroundTested=true&ratio=4.5&algo=HSV

![screen shot 2015-05-30 at 11 24 04](https://cloud.githubusercontent.com/assets/545472/7896609/78b6fd86-06be-11e5-8ae1-3812f9ac9378.png)

**Comment by mtkocak** [comment]
text color for secondary color 1

![screen shot 2015-05-30 at 11 26 44](https://cloud.githubusercontent.com/assets/545472/7896613/db401302-06be-11e5-95ff-df9b063c9719.png)

**Comment by mtkocak** [comment]
advised color for white text based on secondary color 2
![screen shot 2015-05-30 at 11 28 02](https://cloud.githubusercontent.com/assets/545472/7896621/06aa3950-06bf-11e5-8cd7-29116cd58b74.png)

**Comment by mtkocak** [comment]
draft palette examples optimized for WACG2

![palette-2](https://cloud.githubusercontent.com/assets/545472/7896756/5ea38238-06c4-11e5-951b-d759903880d0.png)
![palette-1](https://cloud.githubusercontent.com/assets/545472/7896757/5ea65134-06c4-11e5-915d-a6013dd50ead.png)

**Comment by markstory** [comment]
>  is there any official brand identity guideline?

Not really. We've not really needed one as very few people have ever taken an interest in the visual design aspects of the project. I like the where the palette is going in [these screenshots](https://github.com/cakephp/cakephp/issues/6679#issuecomment-107018230).

**Comment by mtkocak** [comment]
Current status (Should analyze colours again) What do you say?


![l1hzy7 qq5jlaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/545472/7897286/c0bdf284-06d6-11e5-8ed3-0968078fa98e.png)
)

**Comment by mtkocak** [comment]
Second Working Alternative
![gxgaeeeeaagduwibiw2vxj6hfaaaeeeeaaaqqqqaabbbbaaaeeeeaagssjqdbgqvitdfikj8uiiiaaagistgdbgnwuh1epaaiiiiaaaggggaaccccaaaiiiiaaaghcgqgcauuv v8aewmzzo08rhmaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/545472/7897295/4a9d0328-06d7-11e5-8563-70d56a0d3350.png)

**Comment by mtkocak** [comment]
Form
![ehqspd6xuzyaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/545472/7897366/a6e1c2a2-06d9-11e5-8e15-bbd16d5c7e5d.png)

**Comment by bravo-kernel** [comment]
I prefer staying close to the current design

**Comment by jhli** [comment]
I like it but would keep button controls and pagination to the left.

**Comment by lorenzo** [comment]
I really like the look of this: https://github.com/cakephp/cakephp/issues/6679#issuecomment-107032851

**Comment by markstory** [comment]
I also like the more [muted scheme](https://github.com/cakephp/cakephp/issues/6679#issuecomment-107032851)

**Comment by CauanCabral** [comment]
Impressive work :+1:

**Comment by mtkocak** [comment]
finished
![wqgwxn pwzjigaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/545472/7898306/4c2d7360-06fc-11e5-82fd-4853e83914ac.png)

**Comment by mtkocak** [comment]
muted scheme

![uveqy4dunmqaabbbbaaifdayivxaueeeaaaqqqqaabbbbaaaeeeeaaaqqqqaabbozqggdflr0kwypb4unhbbbaaaeeedgqqlcc 4aaaggggaaccccaaaiiiiaaaggggaaccccawbwkeky4pumhwhflfdymaaiiiiaaakcfcfzwhxbaaaeeeeaaaqqqqaabbbbaaaeeeeaaaqqqmembghw3dcgek26jj4crqaabbbba4kgawqruawiiiiaa](https://cloud.githubusercontent.com/assets/545472/7898311/568e5efa-06fc-11e5-8a2a-c4f6a44ab513.png)

**Comment by mtkocak** [comment]
index has h3
![u95aaabgeleqvqca1mivhylj4mrqaabbbba4kgawqrubwqqqaabbbbaaaeeeeaaaqqqqaabbbbaaaeetqaawypjbqrbimpxctaccccaaaiihbugwmh9gaaccccaaaiiiiaaaggggaaccccaaaiiiidacrqgwhgstsfycsw dkyaaqqqqacbowiek7gfeeaaaqqqqaabbbbaaaeeeeaaaqqqqaabbba4gqiek461kqqrjsxhwqgggaacccb](https://cloud.githubusercontent.com/assets/545472/7898312/607051b2-06fc-11e5-8db0-d891743f26fb.png)

**Comment by mtkocak** [comment]
Please check;

https://github.com/cakephp/app/pull/251

https://github.com/cakephp/bake/pull/102

**Comment by Xety** [comment]
I like the "muted scheme" : https://github.com/cakephp/cakephp/issues/6679#issuecomment-107060805. Great work !

**Comment by jhli** [comment]
I do think a lot more peeps that don't even are in gh use it for admin panels of smaller apps!

**Comment by josegonzalez** [comment]
I'm +1 on the changes, they look great and make the new bake templates look a lot more modern while still keeping our look and feel.

**Comment by classoutfit** [comment]
Sounds shallow I know, but the first thing newcomers do is bake something and see how it looks/feels. So even if they are not used in anger, this is important for onboarding new fans. I also like this; https://github.com/cakephp/cakephp/issues/6679#issuecomment-107032851

**Comment by mtkocak** [comment]
I have to update colors for accessibility again and I am going to propose those as official brand colors. If I find sometime I could also create brand identity guidelines for future designs created by other people.

what do you say people? by the way, who is designing the front page of cakephp.org? The design is very funny and good looking. Maybe he or she could cooperate about this.

**Comment by markstory** [comment]
@mtkocak Having the palette/guidelines you used would be great so we can re-use it any future work.  The designs for the current homepage were done by a designer @phpnut hired. He probably has contact details.

**Comment by mtkocak** [comment]
hmm. but we cannot demand volunteer work from him I think. I can move on alone. I did not want to crush someone else's work, but if was professional it was ok.

**Comment by markstory** [comment]
Fair point, I don't think there will be any overlap with existing work then. If the bake output and websites vary a bit I think that's ok and possibly good, as they are separate entities.

**Comment by ionas** [comment]
I don't think this should be a blocker. I do think that next time a cakephp.org overhaul comes around I'd love to see the use of one constant color palette/corporate identity.

@mtkocak how would https://github.com/cakephp/cakephp/issues/6679#issuecomment-107060805 look with a text data field? What about responsive? Will you keep the underlying DOM soup?
Then the yellow headers on white background are too much. Also to my taste a little too many colors. 

How would form errors look like? What about error pages?

That aside I like both themes, the muted and colorful. Great work.

**Comment by phpnut** [comment]
@mtkocak as mark said I hired someone to redesign the site. The redesign is planned to be used on all of the CakePHP assets (other sites). All of the work you have shown above is very impressive and you have a +1 vote from me. Great contribution!

**Comment by look4raymond** [comment]
Coming from a graphic design background & looking for my 1st PHP MVC framework, I was contemplating between Yii and CakePHP. I eventually went with Yii as the generated templates were more visually appealing and semantic. I didn't really dig on CakePHP's generated templates, it just feels _half-baked_. No offense to the designer, it's just a personal opinion.

@mtkocak is doing a really great work! :heart: 

Some of us freelancers are in a hurry to finish up projects, so an excellent baked templates help a lot in that we can just do very minimal tweaking and serve it to clients. Maybe someday when CakePHP or the community has produced these, I'll revisit CakePHP.

FWIW, I tried to produce my own bake templates but the codes just make me :astonished: .

**Comment by ionas** [comment]
@look4raymond I can totally feel your pain. It is exactly the reason I did try to push a semantic, responsive ergonomic basic bake look.

**Comment by mtkocak** [comment]
new layout is going to be totally responsive without any div soup. just can't find time to write tests. Any volunteers?

**Comment by AD7six** [comment]
@mtkocak do you mean for https://github.com/cakephp/bake/pull/104, did you see [my comment there](https://github.com/cakephp/bake/pull/104#issuecomment-107087170#issuecomment-107087170) ?

**Comment by jadb** [comment]
I haven't looked at the exact palette used in the new PRs you submitted @mtkocak but I like how the https://github.com/cakephp/cakephp/issues/6679#issuecomment-107060805 looks like. Not a fan of the yellow sidebar in the other one.

**Comment by mtkocak** [comment]
test are OK.

https://github.com/cakephp/bake/pull/104
https://github.com/cakephp/app/pull/252

Please check for merge.

**Comment by mtkocak** [comment]
Proud of merged requests. Future opts would be:
- Deeper color analysis
- Alternative color scheme
- Accessibility tests
etc?

**Comment by ionas** [comment]
Aside my comments in the PRs:
- I did not check responsive behavior, I think that's important (also for the side bar menu as a top menu)
- Accessibility (tab index, screen readers, etc) is a nice thing too (I like if things are done right as this is not only a foundation for RAD but also a basis to learn from for many).
- If the colors and margins/paddings/grid looks like on the shots, I think its great!

**Comment by markstory** [comment]
Going to close this as the changes for both the app & bake have been merged. If there is interest in refining the new templates further we can do that in separate issues :smile:

**Comment by davidyell** [comment]
Having just found this thread from the other Bake theme threads, please can we link to the merged PR here so that people can follow the thread.

Otherwise this all looks great. Not too over complex which is nice.

**Comment by mtkocak** [comment]
I will analyze again and update colors sometime in the future.

**Comment by AD7six** [comment]
@davidyell You only need to put a link to whatever in your comment

e.g.:

![screenshot from 2015-06-23 12 52 28](https://cloud.githubusercontent.com/assets/33387/8304507/c473d140-19a6-11e5-8e04-f42a127e1749.png)

**Comment by mtkocak** [comment]
By the way, how can I install 3.1 version? @markstory sorry about asking here.

**Comment by mtkocak** [comment]
after changing composer.json to 

    "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "~3.1",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.0",
        "cakephp/bake": "~1.1"
    },

I have this:

Midori-MacBook-Pro:universale mtkocak$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakephp/cakephp ~3.1 -> satisfiable by cakephp/cakephp[3.1.x-dev].
    - cakephp/bake 1.1.x-dev requires cakephp/cakephp dev-master -> satisfiable by cakephp/cakephp[dev-master].
    - Can only install one of: cakephp/cakephp[dev-master, 3.1.x-dev].
    - Installation request for cakephp/bake ~1.1 -> satisfiable by cakephp/bake[1.1.x-dev].

Midori-MacBook-Pro:universale mtkocak$

**Comment by mtkocak** [comment]
I did something like composer create-project --prefer-source cakephp/app universale 3.1.x-dev hope it's gonna work.

**Comment by markstory** [comment]
You'll have to set the minimum-stability to dev as well in composer.json. And use the various dev branches.

**Comment by ionas** [comment]
Did set cakephp, bake to 3.1 and manually imported 3.1 app skeleton css files.
https://gist.github.com/ionas/7505988a068f208e1373
I have following issue with Flashes not rendering like they did in 3.0 (full width above main content):
<img width="1083" alt="screen shot 2015-08-12 at 13 30 42" src="https://cloud.githubusercontent.com/assets/106845/9223009/b61fc924-40f6-11e5-9cec-9e20c1eac819.png">
Is that an intentional change?

And: Is there a way to enable the beautiful colorful scheme (at least the basic grid background colors and side menu looks a lot more beautiful)?
