### ISSUE TITLE
3.0: Router::url(null, true) returns double base path

### ISSUE THREAD

**Issue by Casmo** [cakephp/cakephp#6681]
When using CakePHP 3 in a subfolder e.g. `/my_app/` the `Router::url(null, true)` returns two times `my_app/`.

**Steps to reproduce.**
1. Create and install CakePHP 3.x in a subfolder in your webroot. e.g. `/my_app/`;
2. Edit `src/Template/Pages/home.ctp` and add the following code: `echo $this->Url->build(null, true);`

**Result**
`http://localhost/my_app/my_app/`

**Expected result**
`http://localhost/my_app/`

Edit the following lines in [src/Routing/Router.php](https://github.com/cakephp/cakephp/blob/master/src/Routing/Router.php#L571-L577) from:
```php
        if (empty($url)) {
            $output = isset($here) ? $here : '/';
            if ($full) {
                $output = static::fullBaseUrl() . $base . $output;
            }
            return $output;
        } elseif (is_array($url)) {
```
to:
```php
        if (empty($url)) {
            $output = isset($here) ? $here : $base . '/';
            if ($full) {
                $output = static::fullBaseUrl() . $output;
            }
            return $output;
        } elseif (is_array($url)) {
```

to solve the issue.

**Comment by markstory** [comment]
Closing as a pull request is open now #6682.
