### ISSUE TITLE
[3.0] Cakephp 3.0 cannot auto display form errors? 

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6684]
In CakePHP 2.0, Form errors can auto display on every input bottom.
Cakephp 3.0 cannot auto display form errors? 
if cannot, how can i display form errors on template.ctp .

#Controller
<addr>
if($this->request->is('post')){
            //
            $this->loadModel('Manages');
            $validator = new Validator();
            $Manages = $this->Manages->newEntity($this->request->data);
           
            $this->set('errors',$Manages->errors());
        }
</addr>
#Table
<addr>
public function validationDefault(Validator $validator)
    {
        return $validator
            ->requirePresence('username')
            ->notEmpty('username', 'user name is required')
            ->notEmpty('password', 'A password is required')
            ->notEmpty('role', 'A role is required')
            ->add('role', 'inList', [
                'rule' => ['inList', ['admin', 'author']],
                'message' => 'Please enter a valid role'
            ]);
    }
</addr>
#Template
<addr>
<div class="col-lg-6 col-lg-offset-3">
            <h1 class="text-center"><?=SITE_NAME?></h1>
            <?=$this->Form->create('Manage',['class'=>'form-horizontal','errors'=>$errors])?>
            <?=$this->Form->input('username',['class'=>'form-control input-lg','placeholder'=>'username','label'=>false])?>
            <?=$this->Form->input('password',['type'=>'password','class'=>'form-control input-lg','placeholder'=>'password','label'=>false])?>
            <?=$this->Form->input('submit',['type'=>'submit','class'=>'btn btn-info btn-lg btn-block'])?>
            <?=$this->Form->end()?>
        </div>
</addr>

**Comment by ADmad** [comment]
FormHelper in 3.0 can also automatically display errors below inputs. You need to pass the entity as first argument to `$this->Form->create()` not a string like you have done. Please refer to the manual.

**Comment by macnie** [comment]
thx. I got it
