### ISSUE TITLE
3.x Logging of context

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#6685]
Is the `context` somewhere logged?

```PHP
log($level, $message, array $context = [])
```

In the `FileLog` the output is formatted with the `BaseLog@_format` but in this method the `$context` is ignored.

**Comment by ADmad** [comment]
As you can see in the code it's not used. `$context` array can have any arbitrary data so it left upto devs to use in their custom log engines as desired.

**Comment by Laykou** [comment]
Shouldn't it be at least mentioned in the functions docs? For example for FileLog there is stated

```
* @param array $context Additional information about the logged message
```

and I would say it will log the $context, but it wont... And since the $context can havy an data what about json_encode if possible? Or do say think as with the `$data` in `BaseLog@_format`. Try to call `__toString`, `json_encode` or `print_r`. Why is it not ok to be part of the BaseLog?

Or at least there should be stated that the developer must implement it in order to use it.

**Comment by Laykou** [comment]
... ok I understand that in the $context array there can be nested any object which is not serializable or anything..... So just try it with try-catch blocks... hmm?
