### ISSUE TITLE
patchEntity() and Validation

### ISSUE THREAD

**Issue by daniel-lang** [cakephp/cakephp#6686]
I don't know, if this is an intended behaviour or not, but when creating an entity with `$table->newEntity()` but not specifying every column needed to validate, the validation fails but the specified fields get copied. Up to this point everything runs as expected. But when I call `patchEntity()` with the created entity to add the other columns, the validator validates the columns I just added but complaints about the existing columns not existing.

This might be a strange use case but the entities get created as part of a template pattern.

Interestingly, when I call `$entity->isNew(false)` before patching it the validation works.

**Comment by markstory** [comment]
If I'm understanding you right, the validation is failing and that is a problem? Do you have different validation rules for create/update? Knowing a bit more about how your validation is setup might help in diagnosing the issue further. Right now I don't totally understand what your doing or what the problem is.

**Comment by daniel-lang** [comment]
I'm sorry for not giving you enough details. I have a table, that looks like this:

groups |
---|
id |
name |
link |
customer_id |
changed_on |
deleted |

There is just one validation for the table (`validationDefault()`).
I have a method inside the table that creates a new entity and returns it:

```php
function newEntityForImport(ImportEntity $importEntity)
{
    $entity = $this->newEntity([
        'customer_id' => $importEntity->customer->id,
        'link' => \App\Util\LinkUtil::newLink()
    ]);
        
    return $entity;
}
```

Since I have multiple tables that are similar (id, changed_on, deleted) and they are created during an import process I wrote one class that works for all of them and override specific methods in the specific table class to deal with the differences ([template pattern](http://www.tutorialspoint.com/design_pattern/template_pattern.htm)).
Inside the import function I add the id, name, changed_on and deleted columns and try to patch the entity  that I got from the `newEntityForImport` method:

```php
//data is set with id and name by another method that is overridden by the GroupsTable class
$data += [
    'change_date' => Time::now(),
    'deleted' => ($importEntity->command === ImportCommandUtil::delete)
];

$importEntity->table->patchEntity($entity, $data);
```

After the call to `patchEntity` I expect the entity to be valid since it now has every field I require to be present in the default validation but instead customer_id and link are believed to be empty.

I hope, that made it a little bit clearer.

**Comment by lorenzo** [comment]
What are your validation rules?

**Comment by daniel-lang** [comment]
This is how the validationDefault for this table looks like:

```php
public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmpty('id', 'create')
            ->requirePresence('name', 'create', 'name is not set')
            ->notEmpty('name')
            ->requirePresence('link', 'create', 'link is not set')
            ->notEmpty('link')
            ->add('changed_on', 'valid', ['rule' => 'datetime'])
            ->requirePresence('changed_on', 'create', 'changed_on is not set')
            ->notEmpty('changed_on')
            ->add('deleted', 'valid', ['rule' => 'boolean'])
            ->requirePresence('deleted', 'create', 'deleted is not set')
            ->notEmpty('deleted')
            ->requirePresence('customer_id', 'create', 'customer_id is not set')
            ->notEmpty('customer_id');

        return $validator;
    }
```

**Comment by dakota** [comment]
I think that what you want to do is ignore/bypass validation with your `newEntity` since you are passing some default data there. 

Change your `newEntity` call to be

```php
$entity = $this->newEntity([
        'customer_id' => $importEntity->customer->id,
        'link' => \App\Util\LinkUtil::newLink()
    ], [
        'validate' => false
   ]);
```

**Comment by daniel-lang** [comment]
If I disable the validation for `newEntity` it will accept the unfinished entity without errors. But it still complains about the finished entity at `patchEntity`.
I don't care about the validation errors when calling `newEntity` because I know why they are there. I don't understand, that the result of calling `errors()` after `patchEntity` looks like this:

```php
array(3) {
   'link' => array(1) {
      '_required' => string(15) "link is not set"
    }
    'customer_id' => array(1) {
      '_required' => string(22) "customer_id is not set"
    }
}
```
link and customer_id are set before calling `patchEntity` and the validation at `newEntity` accepted the values for these fields.

**Comment by markstory** [comment]
The validation errors are not cleared between the `newEntity()` and `patchEntity()` calls. I bet if you were to look you would see the validation errors in the entity before `patchEntity()`.

**Comment by daniel-lang** [comment]
If I turn the validation back on I get validation errors before calling `patchEntity()` but they are different. They contain the columns that are actually missing when I call `newEntity()`:

```php
array(3) {
    'name' =>
    array(1) {
      '_required' =>
      string(15) "name is not set"
    }
    'changed_on' =>
    array(1) {
      '_required' =>
      string(22) "changed_on is not set"
    }
    'deleted' =>
    array(1) {
      '_required' =>
      string(18) "deleted is not set"
    }
  }
```

**Comment by markstory** [comment]
@daniel-lang What I was trying to say earlier is that the errors tracked in entity are not cleared by patchEntity(). Any errors that are in the entity when patchEntity() is called will still be there after.

Your validation rules define a number of fields that are required. Many of those fields are not present, which is why validation is failing. It sounds like your import process should have separate validation rules from the other processes in the app. The [documentation](http://book.cakephp.org/3.0/en/orm/validation.html#validating-data-before-building-entities) shows how to use different validation rule sets.

**Comment by daniel-lang** [comment]
I get that the errors are not cleared between checks.But I think that is not the problem here.
For the first check it complains about the missing fields, like it should, and the second time it complains about the fields that weren't changed by the patch, but existed in the entity at the time the second check was done. No errors are duplicate, it just complains about fields missing that are present when I do a var dump and validated the first time.

I can split it up and put it in different validations which will work for me but I still think that this is not the expected behaviour when revalidating an entity.

**Comment by markstory** [comment]
Right but in the patchEntity() call, there are required fields missing from the data that is being patched in. Validation is applied to the request data _before_ the data is merged into the entity data. Your 'request' data is missing a bunch of required fields, and the validation is letting you know.

**Comment by daniel-lang** [comment]
Okay, I thought that `patchEntity()` patches the data into the object and then validates the changed object. But in this case the result is the expected result.

**Comment by LaaHudra** [comment]
@daniel-lang 
http://book.cakephp.org/3.0/en/orm/saving-data.html#merging-request-data-into-entities

In order to update entities you may choose to apply request data directly to an existing entity. This has the advantage that only the fields that actually changed will be saved, as opposed to sending all fields to the database to be persisted. You can merge an array of raw data into an existing entity using the patchEntity() method:

This description looks incoirrect:

Case:
I have jobs table with technician_id field required:
My Code:
`$job = $this->Jobs->get( $jobId );
        
        if ($this->request->is(['post', 'put'])) {
            $job->isNew(false);
            $this->Jobs->patchEntity($job, $this->request->data());
            var_dump($this->Jobs->save($job));
            pr($job->errors());
            pr($this->request->data());
            die();
        }`

Results:
`C:\wamp\www\Cherrie\ChinoX\src\Controller\JobsController.php:440:boolean false
Array
(
    [technician_id] => Array
        (
            [_required] => This field is required
        )

)
Array
(
    [chargeable] => 1
    [price] => 199.96
    [payment_onsite] => 0
)`

Why?! It is wroten I am merging only changed field, so why it throws an error becuase of validation. In my opinion it should valid entity after data is marged and marge only changed field. I made a small workaround

$base = $job->toArray();
$base = array_marge($base, $this->request->data());
and I am putting $base as data for patchEntity, but it is "dirty dianna" style.

**Comment by ChrisTolmeijer** [comment]
@markstory I don't think it makes sense to validate the data like that on patchEntity. When I do `$entity->errors()` I want it to validate the entity and not the last data I have been patching it with. Wouldn't I use a Form if I wanted to validate the request data independently from the entity?

I agree with @LaaHudra. I can not just have one action that uses patch entity to update the entity from a set of fields. I would have to trick it in to thinking that all the properties in the entity are dirty or update the entity myself and check the presence of every field.

**Comment by markstory** [comment]
>  I don't think it makes sense to validate the data like that on patchEntity.

Ok, but the point of validation is to prevent domain objects (entities) from getting into an invalid state. If you are marking fields as 'required' in your validator, wouldn't it be unexpected if that requirement isn't enforced?

It sounds like you might need different validators for your various edit actions which validate each of the operations you offer to users.

**Comment by gitgaatachal** [comment]
@markstory, just now I have come across exactly same problem while updating an entity. 

Would be really helpful if you could provide a clean solution (differential update) to updated selected fields keeping other fields(already there in the table row) intact.
