### ISSUE TITLE
Adding the required css class automatically like on cakephp2

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#6687]
Hi,
Sorry for my bad english :(
In Cakephp2 when i add the key ``'required' => true`` on the validation rule:

	'name' => array(
		'notEmpty' => array(
			'rule' 		 => 'notEmpty',
			'required' => true,
			'message'	 => "Required field"
		)
	)

I will get the required class automatically in the wrapper div:

	<div class="input text required">
		<label for="name">Name:</label>
		<input type="text" name="name" required id="name">
	</div>

I don't need to specify the param in the **FormHelper::input** option array

In the cakephp 3, i create the **validationDefault Method** on the **ArticlesTable.php**:

	public function validationDefault(Validator $validator){
	    $validator
	        ->requirePresence('name')
	        ->notEmpty('name');

	    return $validator;
	}

I create the form on the **add view** like this:

	<?= $this->Form->create() ?>
		<?= $this->Form->input('name') ?>
		<button type="submit">Submit</button>
	<?= $this->Form->end() ?>

The generated Html doesn't have the required css class !

	<form method="post" accept-charset="utf-8" action="/admin/Articles/add">
	    <div style="display:none;">
	        <input type="hidden" name="_method" value="POST">
	    </div>
	    <div class="input text">
	        <label for="name">Name</label>
	        <input type="text" name="name" id="name">
	    </div>
	    <button type="submit">Submit</button>
	</form>

P.S:
I updated the framework today with composer

Thanks

**Comment by ADmad** [comment]
You need to pass an entity as first param to `FormHelper::create()`.  Refer to baked code of [blog](http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-two.html#data-validation) tutorial for exmaple.
