### ISSUE TITLE
Composing multiple contain()s for the same relationship

### ISSUE THREAD

**Issue by beporter** [cakephp/cakephp#6696]
Just getting this documented. As discussed at Cakefest, the ORM is not currently able to compose together multiple [`Query::contain()`](https://github.com/cakephp/cakephp/blob/3a8e70ef46c633ed09e34fb19bb3a75e066d04cd/src/ORM/Query.php#L266) clauses _for the same relationship_. This issue is more fully documented (with sample code and failing tests) in a sample repo here: https://github.com/beporter/cake3-tests#composing-contain-clauses

Loadsys intends to work on a PR to provide this functionality (if the core team doesn't beat us to it.)

The tl;dr version follows: 

The following code only filters the `Comments` association by `Comments.published_date`, but not **also** by `Comments.author`.

```php
$this->Posts->find()
    ->contain(['Comments' => function ($q) {
        return $q->andWhere([
            'Comments.author' => 'John Doe',
        ]);
    }])
    ->contain(['Comments' => function ($q) {
        return $q->andWhere([
            'Comments.published_date >=' => new Time('7 days ago'),
        ]);
    }]);
```

Now obviously this is a contrived example since both `andWhere()`s could be consolidated into the same closure, but what if we had two different custom finder methods that tried to do this separately?

```php
class PostsTable extends Table
{
    public function findCommenter(Query $query, array $options)
    {
        if (!count($options)) {
        	return $query;
        }
        $authorName = array_shift($options);

        $query->contain(['Comments' => function ($q) use ($authorName) {
            return $q->andWhere([
                'Comments.author' => $authorName,
            ]);
        }]);
        return $query;
    }

    public function findRecent(Query $query, array $options)
    {
        $query->contain(['Comments' => function ($q) {
            return $q->andWhere([
                'Comments.published_date >=' => new Time('7 days ago'),
            ]);
        }]);
        return $query;
    }
}
```

Now when you try to compose these together, you end up with only the _last_ `contain()` used:

`$this->Posts->find('commenter', ['John Doe'])->find('recent');`

In this example, we will end up with **only** the `recent` conditions being met.

**Comment by lorenzo** [comment]
I'm going to move this to 3.1

**Comment by beporter** [comment]
Better bump the milestone back again-- I have too much client work. Even my weekends are spent working on paying projects at the moment. Thanks for your patience.

**Comment by markstory** [comment]
Closing as #7799 addresses this.
