### ISSUE TITLE
RFC - Entity Presenter

### ISSUE THREAD

**Issue by alecho** [cakephp/cakephp#6698]
### Problem

With entity objects in CakePHP 3 it's tempting to put presentation logic in an entity. It is very easy with the magic getter to add virtual fields with presentation logic. One solution is to create a helper for each entity. On large applications with many models, creating a helper for each entity becomes tedious and smells. 
### Proposed Solution

Create a presenter class like that in the original [View Cells RFC](https://github.com/cakephp/cakephp/issues/3052) that would decorate an entity object.

Presenters should be:
- Opt in
- Configurable with a presenter field => entity field mapping
- Loaded by convention (User -> UserPresenter) or configuration (User -> CustomerPresenter)

Usual pseudo code disclaimer here.

```
// In the view class
public function present($entity, $presenter = null) {
    $class = get_class($entity) . 'Presenter';
    if ($presenter != null) {
         $class = $presenter . 'Presenter';
    }
    return new $class($entity);
}

// In a view template
$user = $this->present($user);
// Or
$user = $this->present($user, 'Customer'); // Uses CustomerPresenter

// Or opting in to using a presenter could be done in the controller
// which I like better
$this->set('_present', ['user' => 'Customer', 'orders']);
```

```
// Or even
$this->set('_present', true);
```

to align with [Make serialization the default behavior for JsonView](https://github.com/cakephp/cakephp/issues/6500)

**Comment by markstory** [comment]
What kind of API do you think the Presenters would have? Would they proxy attribute and method access to the entity?

**Comment by alecho** [comment]
Yes, I'm thinking the entity would be held in a property so that you could proxy access to the entity and also remap property access.

**Comment by markstory** [comment]
@alecho Cool, having a rough sketch of the Presenter class' API would probably help with the discussion.

**Comment by sdustinh** [comment]
:+1:

I have been tempted to put an issue like this in many times. Instead I keep creating helper classes (and now have a library). If you need any help with this @alecho I would be happy to assist.

**Comment by alecho** [comment]
@sdustinh Our work is here: https://github.com/loadsys/cakephp/tree/6698-Entity-Presenters. Feel free to fork and claim issues (if you can). If you can't assign an issue to yourself because of permissions, just comment on the issue that you're working on it and I'll assign it to you.

@markstory See the above link for our in-progress Presenter class API.

@loadsys please claim or create issues as you work on them.

**Comment by josegonzalez** [comment]
@alecho You should probably make this change targeting the 3.1 branch (new features go in minor releases, not patch). The other thing is that it currently has `debug` statements ;)

**Comment by alecho** [comment]
I'll target the 3.1 when ready to merge. The PR that was opened was a mistake.

**Comment by josegonzalez** [comment]
Gotcha.

**Comment by jhli** [comment]
Another solution might be rails like partials as these take entities and/or collections and thus can be re-used.

**Comment by alecho** [comment]
@jhli I don't see why a presenter couldn't have shared logic either from a helper, it's parent, or a special "mini-presenter". Partials in Rails are closer to Cake's elements in that they rely on a template. With the proposed presenter class a template isn't needed.

**Comment by lorenzo** [comment]
@alecho Any progress on this?

**Comment by beporter** [comment]
Lots actually, but we've been swamped with work and haven't been able to carry it over the finish line yet. :sweat_smile:

**Comment by dereuromark** [comment]
We are all quite excited about the results, though :)

**Comment by ADmad** [comment]
Monthly ping :)

**Comment by Marlinc** [comment]
Any news on this?

**Comment by alecho** [comment]
@beporter Can I help with this in any way?

**Comment by beporter** [comment]
I apologize; We've still been up to our necks in client work, (un)fortunately. We don't want to retain "dibs" on the feature though, so we'd definitely welcome any contributions to the branch at the center of the PR here: loadsys/cakephp/pull/10

We're definitely anxious to get the minimum viable PR submitted to the core so we can let the rest of the community contribute and improve on the concept more. It will be difficult for any of us at Loadsys to take point on completing that work right now, but I'll happily facilitate and we'll provide timely feedback wherever we can. (The topic branch in our fork needs to be retargeted against the next Cake release, for example.)

We've been tracking the work left to do in our fork's Issues, if you're looking for a place to start: https://github.com/loadsys/cakephp/issues

**Comment by dereuromark** [comment]
Maybe we should close this and let a plugin solution surface first. If that gets traction one can still discuss core relevance?

**Comment by beporter** [comment]
No objection from me.

**Comment by cleptric** [comment]
I talked with @markstory a while ago and created a super rough sketch of this feature https://github.com/cleptric/entity-presenter

#10993 just brought this to my attention again.

**Comment by inoas** [comment]
* Would the entity presenter also be usable to create different visibility maps (different presenters)? Similar to $_hidden but switchable (cause then it solves two things that are often required: transformation and filtering)?
* What happens with nested entities? Is there a way to define a presenter schema (nested presenters) - say you want to present a user, his profile and his preferences (3 tables, 1 hasMany, 1 hasOne relationship)

**Comment by cleptric** [comment]
- Yes, this is possible and could be improved even further. Maybe the `__get` could be made opt-out and accessing entity data only works by calling `$this->_entity->foo` directly.
- It would try to present them as well.

**Comment by dereuromark** [comment]
Closing for plugin and awesome-list presentation then.
