### ISSUE TITLE
[3.0] Cakephp 3.0 Validation notBlank cannot display my custom message

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6703]
# My Validation Rule

public function validationLogin(Validator $validator)
    {
        $extra = '';
        return $validator
            ->add('username',[
                'notBlank'=>    ['rule'=>'notBlank','message'=>'ab'],
                'minLength'=>   ['rule'=>['minLength',5],'message'=>'cd'],
            ])
            ->add('password',[
                'notBlank'=>    ['rule'=>'notBlank','message'=>'ef'],
            ]);
    }

# Also display error :This field cannot be left empty

**Comment by ADmad** [comment]
That error message is being generated by `Validator::notEmpty()` as it's run before your rules. So either use `$validator->notEmpty('fieldname', 'message')` to customize the message or use `$validator->allowEmpty('fieldname')` to prevent the not-empty check since you are already using `notBlank` rules.

**Comment by davo3** [comment]
@ADmad , what is the reason that `notEmpty` is separated as another function and is being run before `notBlank` ? If I want to apply the rules like
```
$validator->add('title', [
	'notBlank' => [
		'rule' => 'notBlank',
		'message' => 'not blank message',
		'last' => true 
	],
	'minLength' => [
		'rule' => ['minLength', 10],
		'last' => true,
		'message' => 'Min 10 characters',
	],
	'maxLength' => [
		'rule' => ['maxLength', 50],
		'last' => true,
		'message' => 'Max 50 characters',
	],
]);
```

then `notBlank` is useless in here, because of the above-mentioned. So I have to add another line before `add`, like this
```
$validator->notEmpty('title', 'custom empty message');
```

what is the possible problem of allowing `notEmpty/notBlank` inside rule list as it was in cake 2.x ?

Thanks

**Comment by ADmad** [comment]
> then notBlank is useless in here, because of the above-mentioned

So don't use pointless combination of rules :)  Just use `$validator->notEmpty()` and `minLength`, `maxLength` rules. 

Using `Validator::notEmpty()` is synonymous with adding `required` attribute to form's input element and the validation rules are for achieving validation that can be got using combination of various input element attributes like `type, `pattern`, `min`, `max` etc. (Using `notBlank` rule is same as setting `pattern` regex which prevents value with only whitespace)

**Comment by davo3** [comment]
@ADmad  months later I still bumped into this issue and cant get over it :)

why e.g. for `minLength` validation I can do both 

```
$validator->minLength('name', 10, __('Name is too short'));

and

$validator->add('name', [
      'minLength' => [
        'rule' => ['minLength', 10],
        'last' => true,
        'message' => __('Name is too short')
    ]
]);
```

and they both work fine and the same way(AFA I noticed)

however for checking about being empty I can do

```
$validator->notEmpty('name', __('Name can not be empty'));
```

but this does NOT work

```
$validator->add('name', [
    'notEmpty' => [
        'rule' => 'notEmpty',
        'last' => true,
        'message' => __('Name can not be empty')
    ],
]);
```

I read this
https://github.com/cakephp/cakephp/issues/6752#issuecomment-109792352

I mean I understand that `Validation::notEmpty()` is deprecated, but just to keep consistency so whatever validation rule we use by `$validator->myRule` , to be able to use it in array, cant we add a feature e.g.

```
$validator->add('name', [
    'isNotEmpty' => [
        'rule' => 'isNotEmpty',
        'last' => true,
        'message' => __('Name can not be empty')
    ],
   ... // another rules
]);
```

which would do exactly the same as if we would have written 
```
$validator->notEmpty('name', __('Name can not be empty'));
```

So, the point I am making is just about way of writing: to be able to write all the validation rules of the field inside same array, like this (kinda to keep the way of writing as we had with cake 2.x)
```
$validator->add('name', [
     'isNotEmpty' => [
        'rule' => 'isNotEmpty',
        'last' => true,
        'message' => __('Name can not be empty')
    ],
     'minLength' => [
        'rule' => ['minLength', 10],
        'last' => true,
        'message' => __('Min length')
    ],
     'maxLength' => [
        'rule' => ['maxLength', 100],
        'last' => true,
        'message' => __('Max length')
    ],
   ... // another rules
]);
```

Thanks

**Comment by ADmad** [comment]
> to be able to write all the validation rules of the field inside same array...

You can already do that. Use `notBlank` instead of your custom `isNotEmpty` or add your custom `isNotEmpty()` method in table / behavior.

**Comment by davo3** [comment]
Thanks a lot for your reply,

> You can already do that

I assume you meant this
```
$validator->add('name', [
    'notBlank' => [
        'rule' => 'notBlank',
        'message' => __('Name can not be empty')
    ]
]);
```
this still has the problem as the current issue had - I mean showing the default validation message. Tried this code with `notEmpty` instead of `notBlank`, but same message thing exists - I mean shows the standard `This field cannot be left empty` instead of my custom message.

> or add your custom isNotEmpty() method in table / behavior

if I'm having
```
$validator->add('name', [
    'isNotEmpty' => [
        'rule' => 'isNotEmpty',
        'message' => __('Name can not be empty')
    ]
]);

public function isNotEmpty($value, $context) {
    echo "custom rule";die;
}
```
If I submit data with `name` as empty it never gets inside `isNotEmpty` function, and I am guessing because as the submitted field is empty it does not even bother getting to that function and at once shows not default empty message.
Is this worth making a feature request ? - I mean a possibility to define everything(notEmpty, allowEmpty and everything else) inside the array.

Thanks

**Comment by davo3** [comment]
it seems the same thing exists for `requirePresence` I mean e.g. these code from cake 2.x
```
'name' => array(
    'notBlank' => array(
        'rule' => array('notBlank'),
        'message' => 'Name can not be empty',
        'required' => true,
    )
)
```
was enough to make sure name is provided and is not empty(and different than whitespace)

Now for cake 3 we have to have this(please correct me if im wrong)
```
$validator->notEmpty('name', __('Name can not be empty'));
$validator->requirePresence('name', true, __('Name can not be empty'));
$validator->add('name', [
    'notBlank' => [
        'rule' => 'notBlank',
        'message' => __('Name can not be empty')
    ],
]);
```

would not it be better/shorter/nicer to have this code, which would handle exactly the same thing above

```
$validator->add('name', [
    'isNotEmpty' => [
        'rule' => 'isNotEmpty',  // considers for the field to be provided and other than whitespace
        'requirePresence' => true,
        'message' => __('Name can not be empty')
    ],
]);
```

Thanks

**Comment by davo3** [comment]
I just found another issue that addresses the same thing:

in the first sentence of this comment
https://github.com/cakephp/cakephp/issues/5856#issuecomment-73367624
he makes the same point I do.

if this is something, that will be considered I could give it a try and make a PR - for requirePresence to be able to set inside the rule's array, as well as to allow `notEmpty` to be added in rule list: of course renaming it to smth else, e.g. `isNotEmpty` or anything else(to prevent the old confusion issues that brought to `notEmpty` deprecation) - and either make it equivalent to `$validator->notEmpty` or to `notEmpty` and `notBlank` combined as in my previous comment (TBD)

Thanks

**Comment by ADmad** [comment]
> for requirePresence to be able to set inside the rule's array,

Having `'requirePresence' => true` as key inside rule options array would be logically wrong as it applies to the field not any particular rule. It was a mistake doing so in 2.x.

> If I submit data with name as empty it never gets inside isNotEmpty function, and I am guessing because as the submitted field is empty it does not even bother getting to that function and at once shows not default empty message.

Use your own Validator class which overrides `Validator::add()` and calls `$this->allowEmpty($field)`. That will disable the separate not empty check and your rules will be always triggered. Similarly you could also check for `requirePresence` key in rule options and call `$this->requirePresence()` if thats how to want things to work. But a change like this won't be accepted in core itself.

**Comment by davo3** [comment]
ok, thanks a lot, I appreciate that
