### ISSUE TITLE
redirect in beforeFilter is not working

### ISSUE THREAD

**Issue by klickagent** [cakephp/cakephp#6705]
In CakePHP2 it was possible to do a redirect within the beforeFilter method of a controller. In CakePHP3 on the other hand no redirect occurs anymore and the controller's action gets executed.
To reproduce:
Create a controller with a default action:

public function index(){
	echo 'here';
}

Create a beforeFilter, like the following:

public function beforeFilter(Event $event) {
    if( true ){ //if a sample condition is true
        $this->redirect([
            'controller' => 'test',
            'action' => 'index'
        ]);
        return;
    }
}

When the controller is called, the text "here" appears on the screen whereas the page should have been redirected to the action index of the controller test (test/index).

Is there a known issue, or am I doing something wrong here?
Thanks for your help.

**Comment by ADmad** [comment]
`Controller:redirect()` now return a response object, you are supposed to return that response object from your method.

**Comment by klickagent** [comment]
I tried that already. I changed the example above. Do you think this code should work now?

**Comment by klickagent** [comment]
I forgot to mention that I am trying to redirect inside the beforeFilter of the AppController and not the beforeFilter of the controller itself. (The beforeFilter is being executed within the beforeFilter of the controller with parent::beforeFilter($event); ).

**Comment by dereuromark** [comment]
In that case, logically, you need to "return" your parent call, as well.
```php
public function beforeFilter(Event $event) {
	...
	return parent::beforeFilter($event);
}
```
Otherwise you lose the return value.
In 3.x those methods can return sth else than just "void", as such you need to make sure you always use `return` here.

**Comment by klickagent** [comment]
Thanks a lot for your help!

**Comment by trante** [comment]
Dear dereuromark, Although code below works, shouldn't we put ```parent::beforeFilter()``` on top of ``beforefilter()`` function ?

public function beforeFilter(Event $event) {
       ...
      ...
      return parent::beforeFilter($event);
}
```

**Comment by dereuromark** [comment]
Isn't that what the code example above does?

**Comment by trante** [comment]
Sorry if I understand wrong, I mean this. Shouldn't we use parent's beforefilter like this? 

public function beforeFilter(Event $event) {
      return parent::beforeFilter($event);
      ...
      ...
      ...
}

**Comment by josegonzalez** [comment]
@trante that would return immediately since you have your return there at the stop. It's really up to the requirements of the application, so whichever works for you.

**Comment by trante** [comment]
As far as I know, one should call parent's same name method on top of the method. This type of usage breaks this ?

**Comment by markstory** [comment]
@trante It doesn't 'break' it, but does require you check return values.

```php
$result = parent::beforeFilter($event);
if ($result) {
   return $result;
}
...
```

If you find yourself doing this, you probably should consider extracting common code into a component or dispatch filter so you can avoid the duplication and inheritance chain.

**Comment by trante** [comment]
We have 2-3 redirects in beforeFilter methods. So duplication not so much.

So is it a safe way to do this in controller's beforeFilter method ?

````
$this->response = $this->redirect('/mycontroller/myAction') ;
$this->response->send () ;
die ();
````
Or is there a proper way to redirect from the inherited controller's beforeFilter method ?

**Comment by markstory** [comment]
Die() is not something I would use as it makes writing tests impossible and furthermore means any dispatch middleware or components hooked up to the shutdown event will not be triggered.

The proper way would be to return a response object (which redirect does) and check the return of parent in subclasses.
