### ISSUE TITLE
redirect in beforeFilter is not working

### ISSUE THREAD

**Issue by klickagent** [cakephp/cakephp#6707]
I am sorry to opening another ticket on this issue (https://github.com/cakephp/cakephp/issues/6705). I actually tried many different things and posted the wrong code according to the documentation. The issue still persists even when returning the response object from the beforeFilter:

In CakePHP2 it was possible to do a redirect within the beforeFilter method of a controller. In CakePHP3 on the other hand no redirect occurs anymore and the controller's action gets executed.
To reproduce:
Create a controller with a default action:

public function index(){
echo 'here';
}

Create a beforeFilter, like the following:

public function beforeFilter(Event $event) {
if( true ){ //if a sample condition is true
return $this->redirect([
'controller' => 'test',
'action' => 'index'
]);
}
}

When the controller is called, the text "here" appears on the screen whereas the page should have been redirected to the action index of the controller test (test/index).

Is there a known issue, or am I doing something wrong here?
Thanks for your help.

**Comment by ADmad** [comment]
Don't open multiple tickets for the same issue.
