### ISSUE TITLE
Cakephp 3.0 Upgrading FullCalendar plugin, but no results on Calendar

### ISSUE THREAD

**Issue by curtisblack2004** [cakephp/cakephp#6709]
I have almost everything up and running in CakePhp 3.0 with the FullCalendar plugin, but when I load the calendar, no events appear on the page.

Here is my feed method:

    public function feed($id=null) {
        $this->layout = "ajax";
        $vars = $this->params['url'];
        $conditions = array('conditions' => array('UNIX_TIMESTAMP(start) >=' => $vars['start'], 'UNIX_TIMESTAMP(start) <=' => $vars['end']), 'contain' => ['EventTypes']);
        $events = $this->Events->find('all', $conditions);
        foreach($events as $event) {
            if($event->all_day == 1) {
                $allday = true;
                $end = $event->start;
            } else {
                $allday = false;
                $end = $event->end;
            }
            $data[] = array(
                    'id' => $event->id,
                    'title'=>$event->title,
                    'start'=>$event->start,
                    'end' => $end,
                    'allDay' => $allday,
                    'url' => Router::url('/') . 'full_calendar/events/view/'.$event->id,
                    'details' => $event->details,
                    'className' => $event->event_type->color
            );
        }
        $this->set("json", json_encode($data));
    }

I had to change the url in full_calendar/index.ctp in order to not have an error in the console. This is what I have: 

	<script type="text/javascript">plgFcRoot = "/<site name>/" + "full_calendar";</script>

**Comment by markstory** [comment]
How is this an issue with CakePHP? From a cursory glance it looks like an issue with whichever plugin you are using.

**Comment by curtisblack2004** [comment]
Hey Mark,
This plugin works on cake 2.x. It was made for cakePHP (https://github.com/silasmontgomery/CakePHP-Full-Calendar-Plugin) not sure why it wouldn't work on 3.x which makes me think it is a cakePhp issue. I have it on a 2.x version and it displays the events on the calendar, but updating it to work with 3.x is proving difficult. As CakePHP 3.x is new, there isn't much information on the net to correct this issue. I am not getting any errors anymore, just no events to display on the calendar. If if isn't a cakePHP issue, do you know where I can look to try and find an answer to this question? Any help would be greatly appreciated.
Thanks,
Curtis 


     On Monday, June 1, 2015 7:42 PM, Mark Story <notifications@github.com> wrote:
   

 Closed #6709.—

**Comment by lorenzo** [comment]
Try http://stackoverflow.com/questions/tagged/cakephp-3.0 please

**Comment by curtisblack2004** [comment]
I just solved my issue... and that link didn't help, I just used a process of elimination and found that the conditions array that I had was set up incorrectly for cakePHP 3.0, so it was a cake issue. Instead of 
CakePHP 2.x Syntax $conditions = array('conditions' => array('UNIX_TIMESTAMP(start) >=' => $vars['start'], 'UNIX_TIMESTAMP(start) <=' => $vars['end'])); $events = $this->Event->find('all', $conditions);
it is:
CakePHP 3.x Syntax
$conditions = ['UNIX_TIMESTAMP(start) >=' => $vars['start'], 'UNIX_TIMESTAMP(start) <=' => $vars['end']];$events = $this->Events->find('all', $conditions)->contain(['EventTypes']); 
There isn't a conditions setting in the array, you just set the conditions which I got from this example in the documentation:
$this->loadModel('Articles');
$recentArticles = $this->Articles->find('all', [
    'limit' => 5,
    'order' => 'Articles.created DESC'
]);So my code could have used a more thorough look than a cursory one. Thanks anyways.
-Curtis


     On Tuesday, June 2, 2015 3:24 PM, José Lorenzo Rodríguez <notifications@github.com> wrote:
   

 Try http://stackoverflow.com/questions/tagged/cakephp-3.0 please—

**Comment by markstory** [comment]
@curtisblack2004 There are huge differences between cake2 and cake3. It is highly unlikely that code will 'just work' between the 2 versions. You will likely run into a number of issues in using a plugin intended for version 2 inside a v3 app, as the model layer/ORM is very different.

**Comment by curtisblack2004** [comment]
I understand that... It was just a little irritating that you cursory glanced at the code and then closed it... I understand that you guys are really busy and I still appreciate the time you guys take to build the framework and offer support so anyway thank you. It could also help someone else who is trying looking for a similar solution.
Thanks Again,
-Curtis 


     On Tuesday, June 2, 2015 7:47 PM, Mark Story <notifications@github.com> wrote:
   

 @curtisblack2004 There are huge differences between cake2 and cake3. It is highly unlikely that code will 'just work' between the 2 versions. You will likely run into a number of issues in using a plugin intended for version 2 inside a v3 app, as the model layer/ORM is very different.—
