### ISSUE TITLE
[3.0] Acl.AclBehavior could not be found.

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6711]
# My web file tree:

/plugins/Acl/src/

# composer.json
"autoload": {
		"psr-4": {
			"Acl\\": "./plugins/Acl/src"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"Acl\\Test\\": "tests",
			"Cake\\Test\\": "vendor/cakephp/cakephp/tests"
		}
	}
# bootstrap.php
Plugin::loadAll();

CakePHP 3 plug-in installation and use is too difficult, can write a detailed tutorial?

**Comment by markstory** [comment]
Did you install the [acl plugin](https://github.com/cakephp/acl] with composer? If you didn't,

```
php composer.phar require cakephp/acl
```

Will correctly install the plugin.

**Comment by macnie** [comment]
thx. I don't know how to use this ACL plugin, can you write a detailed tutorial? Thank you too much.!

**Comment by markstory** [comment]
I don't really have the time available to write a detailed tutorial. However, the documentation [from the 2.x acl code](http://book.cakephp.org/2.0/en/core-libraries/components/access-control-lists.html) still apply as the functionality of the code has not dramatically changed since then.
