### ISSUE TITLE
form->input minYear doesnt work

### ISSUE THREAD

**Issue by Jurrieb** [cakephp/cakephp#6715]
echo $this->Form->input('birth_dt', [
    'label' => 'Date of birth',
    'minYear' => date('Y') - 70,
    'maxYear' => date('Y') - 18,
]);
creates a form with minYear of 00

**Comment by markstory** [comment]
Odd, the following test passes fine.

```php
        $this->Form->request->data = [];
        $this->Form->create($this->article);
        $result = $this->Form->input('birthday', [
            'label' => false,
            'type' => 'date',
            'minYear' => 2006,
            'maxYear' => 2008,
            'default' => true
        ]);
        $this->assertContains('value="2008" selected="selected"', $result);
        $this->assertContains('value="2006"', $result);
```

**Comment by ADmad** [comment]
@markstory It might have something to do with year before epoch `'minYear' => date('Y') - 70,`

**Comment by markstory** [comment]
Very possible. I'll try to reproduce tonight.

**Comment by markstory** [comment]
I wasn't able to reproduce. However, I suspect that you might have `0000-00-00` in your database, which will extend the valid range to include year 0. If that's the case you should disable this 'feature' in MySQL and use nullable date/datetime columns instead.
