### ISSUE TITLE
3.x ORM Add DATEPART functions

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#6716]
Add the DATEPART SQL functions into dialect traits to extract the week, weekday, quarter, etc. from dates.

I can try to make PR for this.

**Comment by lorenzo** [comment]
a PR would be definitely nice!

**Comment by markstory** [comment]
Sounds good to me :+1:

**Comment by ravage84** [comment]
What is the use case for this?
Isn't it enough to get the full date back from the DB and process the parting part [sic!] in PHP?

**Comment by Laykou** [comment]
The problem is if you want to do groupping and aggregations

**Comment by Laykou** [comment]
Closing because of PR.
