### ISSUE TITLE
question: assertTemplate and View Cells?

### ISSUE THREAD

**Issue by jc-vogel** [cakephp/cakephp#6718]
In some Unit tests I used the assertTemplate method. But after I created a View Cell, assertTemplate() always returns the name of the cell template. 
I guess this is because the 'beforeRender' event is fired by the Cell, and the ControllerSpy in IntegrationTestcase overwrite the original _viewName property in IntegrationTestcase. 

Is this intended behavior? Is there a (normal) way to test the original templateName, not the templateName of the Cell?

A possible solution would be to skip the ControllerSpy while rendering View Cells, but I guess that makes testing a Cell a bit difficult..
Another solution could possibly be to just skip setting the viewname in the ControllerSpy when rendering a Cell?

**Comment by markstory** [comment]
We could skip storing the viewname if the spy already has a value. That would let us capture the first view rendered (which should generally be the controller's view).

**Comment by markstory** [comment]
Pull request up.
