### ISSUE TITLE
3.0 Paginator sort cant be used with fields outside of table

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#6725]
https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L345-L368 will always prefix sort field with table alias but when using fields not existing in table
ie
```
$this->paginate = [
                            'limit' => 10,
                            'sortWhitelist' => [
                                'Businesses.votes',
                                'score',
                                'Businesses.name'
                            ],
                            'order' => [
                                'Businesses.name' => 'asc'
                            ]
                        ];

$query = $businesses->find()
       ->select(['score' => 'Businesses.total_score/Businesses.votes'])
       ->autoFields(true);

$results = $this->paginate($query);
```
when trying to sort by 'score' it will give query error unknown column 'Businesses.score' in 'order clause'

maybe add another option to settings like 'sortLiteral' and check if the field is in it to bypass alias prefixing

**Comment by lorenzo** [comment]
Use the "whitelist" in the paginator options. http://book.cakephp.org/3.0/en/controllers/components/pagination.html#control-which-fields-used-for-ordering

**Comment by lorenzo** [comment]
oops, fat fingers. Did not mean to close it

**Comment by markstory** [comment]
This issue was introduced in #6611 as a solution to #6597

**Comment by markstory** [comment]
Closing as #6740 is open now.
