### ISSUE TITLE
Do plugins work with prefix just with basic config?

### ISSUE THREAD

**Issue by aleixfabra** [cakephp/cakephp#6726]
In the book you can read:

"If your application defines routing prefixes, CakePHP’s default routing will also connect routes that use the following pattern:"

`/:prefix/:plugin/:controller`
`/:prefix/:plugin/:controller/:action`

Is it true? Because I added 
```php
Router::prefix('admin', function ($routes) {
    $routes->connect(
        '/',
        ['controller' => 'Users', 'action' => 'index'],
        ['_name' => 'admin']
    );
    $routes->fallbacks('InflectedRoute');
});
```
and I can't do it `admin/myplugin/mypuguincontroller/index`

Thanks!

**Comment by lorenzo** [comment]
You nee to call `$routes->plugin(...)` inside the prefix block. Please use stackoverflow for help or the IRC channel so you can get more direct support.
