### ISSUE TITLE
Error on cli-error.log says Permission Denied to Open Stream

### ISSUE THREAD

**Issue by mariobalca** [cakephp/cakephp#6729]
Hello,

I'm using the CakePHP 3 on a LAMPP system, I'm pretty sure that I have all the file permissions and ownership right but I'm constantly getting these two warnings:

Warning: file_put_contents(/opt/lampp/htdocs/testproject/logs/cli-error.log): failed to open stream: Permission denied in /opt/lampp/htdocs/testproject/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 135 

Warning: file_put_contents(/opt/lampp/htdocs/testproject/logs/cli-error.log): failed to open stream: Permission denied in /opt/lampp/htdocs/testproject/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 135

The screenshot is attached to the post for more information

Anyone can help?
[screenshot from 2015-06-04 17 47 07](https://cloud.githubusercontent.com/assets/4289045/7989504/be94d982-0ae1-11e5-8e55-5de967f4e7b7.png)

**Comment by AD7six** [comment]
> I'm pretty sure that I have all the file permissions and ownership right

Well, obviously that's not the case =). Solution: fix the permissions for /opt/lampp/htdocs/testproject/logs

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by AD7six** [comment]
Wait, what? you're writing the the cli log from a web request? What is your setup?

**Comment by ADmad** [comment]
When the app is accessed through web server it shouldn't be trying to `cli-log.log`. Check your config in `bootstrap.php` and make sure it looks similar to [this](https://github.com/cakephp/app/blob/master/config/bootstrap.php#L105-L115).

**Comment by mariobalca** [comment]
I didn't even opened the config folder, I just installed the CakePHP 3 from the composer and that was it. 

My bootstrap.php is exactly like that!

**Comment by AD7six** [comment]
What is the output of:

    <?php
    echo php_sapi_name();
    

During a web request?

**Comment by mariobalca** [comment]
The output of php_sapi_name(); is

apache2handler

**Comment by mariobalca** [comment]
[screenshot from 2015-06-04 19 27 12](https://cloud.githubusercontent.com/assets/4289045/7991393/beb468fc-0aef-11e5-9088-5e795779f58f.png)

**Comment by mariobalca** [comment]
I even tested giving 777 to both folders (tmp and logs) and I still get the same error

[screenshot from 2015-06-04 19 29 22](https://cloud.githubusercontent.com/assets/4289045/7991452/0ebb1562-0af0-11e5-913e-aa71cf00a3ba.png)

**Comment by lorenzo** [comment]
Please contact your server administrator to figure out where the php-cli executable is installed. When you do that, change `bin/cake` so that it executes that binary instead of the current cgi-handler that you are using.

**Comment by lorenzo** [comment]
ah crap, I fell into the same trap as @AD7six by closing this too fast. I think the key is to determine why cake thinks you are running under a CLI. Try debugging the server vars and see what you can get out of it.

**Comment by mariobalca** [comment]
I'm sorry, this is my first time using cake can you be a little more specific?

**Comment by lorenzo** [comment]
I think it would be better if you go to the IRC channel where we can offer better help than here
