### ISSUE TITLE
Issue with label for the group of radio buttons; radioContainer and radioFormGroup not working

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#6732]
Hi masters, I tried all the possible ways but couldn't bring the label for group of radio buttons.

Here is the gist - https://gist.github.com/gauravmak/97e005de27fe8bab1443

Label for checkbox is shown but no luck for radio buttons :(

radioContainer and radioFormGroup do not seem to be affecting the output at all.

**Comment by markstory** [comment]
There is no way to get a label for a group of radio buttons. Each radio button gets its own label.  What output are you expecting/trying to get?

**Comment by gauravmak** [comment]
It works with checkboxes so I expected the same with radios as well. Check the screenshot please ![Screenshot](https://cloud.githubusercontent.com/assets/11887260/8005839/dd38c8d8-0bab-11e5-9ad2-598d88059409.png)

**Comment by markstory** [comment]
Ok the issue is that you are using `radio()` and not `input()`. `radio()` only generates the radio buttons. If you want the input wrapper and label block you need to use `input()`

**Comment by gauravmak** [comment]
Thank you so much. Appreciable. I will take care next time.
