### ISSUE TITLE
No work default types in TypeMap

### ISSUE THREAD

**Issue by StewEucen** [cakephp/cakephp#6737]
I found the problem of TypeMap.

# Steps to reproduce
* Overview<br>
Use SQL function with types.
* MySQL table
```
CREATE TABLE `samples` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `level` int(11),
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8
;
```
* Code
```PHP
$theTable = $this->Samples;
$res = $theTable->find()
    ->select([
        'id',
        'coalesced_value' => $theTable->query()->func()->coalesce(
            ['level' => 'literal', -1],
            ['integer']
        )
    ])
    ->all()
;
```

# Wrong result
Got wrong SQL query as follow. Second param of COALESCE() must be integer, but it is string.
The given types is not working in TypeMap.
```
SELECT
    Samples.id AS `Samples__id`,
    (COALESCE(level, '-1')) AS `coalesced_value`
FROM
    samples Samples
```

# Cause
Default types are passed to set $this->_defaults by TypeMap::__construct(), but TypeMap::types() does not use it for return value.

# Fix
TypeMap::types() should use $this->_defaults for backup of $this->_types.
file: Cake\Database\TypeMap.php
line: 96

around the code
```
public function types(array $types = null)
{
    if ($types === null) {
---     return $this->_types;
+++     return $this->_types ?: $this->_defaults;
    }
    $this->_types = $types;
    return $this;
}
```

# Result
Got to work types as follow
```
SELECT
    Samples.id AS `Samples__id`,
    (COALESCE(level, -1)) AS `coalesced_value`
FROM
    samples Samples
```

# Side effect
Maybe none, Other method of TypeMap (=type()) has same style to use $this->_default as backup.
Therefore $this->_defaults can be backup to $this->_types in any cases.

TypeMap::type()
```
public function type($column)
{
    if (isset($this->_types[$column])) {
        return $this->_types[$column];
    }
    if (isset($this->_defaults[$column])) {
        return $this->_defaults[$column];
    }
    return null;
}
```

**Comment by StewEucen** [comment]
@ADmad When Defect label was affixed, I can execute pull request?

**Comment by lorenzo** [comment]
yes, you can send a pull request @StewEucen

**Comment by StewEucen** [comment]
@lorenzo Thank you for your reply.
I will use the criterion as tacit consent to pull request from now.

**Comment by StewEucen** [comment]
I excuted to PHPUnit for 'tests/TestCase/DatabaseSuite', and got 10 errors (5 kinds each 2).
Now I seek the causes in test cases. I will send pull request after solving. Please wait a while.

@lorenzo Should I paste the errors here?

**Comment by markstory** [comment]
@StewEucen If you start the pull request it will be easier for us to see the failing tests and help get them fixed.

**Comment by StewEucen** [comment]
@markstory Thank you for reply.
I send pull request. Please wait.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
