### ISSUE TITLE
3.0 ORM insert into ... select

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#6741]
ive found myself in need of writing query where value of field would have to be unique each day so the solution ive came up with looks close to
```
INSERT INTO tests (transaction_id, message) SELECT count("*"), 'test' AS `count` FROM tests Tests
```
but guys on IRC said that cake ORM doesnt do this is there plans in future to make it?

**Comment by lorenzo** [comment]
It is possible. Pass a query object in the values() function of the insert query object

**Comment by markstory** [comment]
Closing as this is already possible and even works on sqlite :smile:

**Comment by Graziel** [comment]
wow incredible cake ORM has gained once more in my eyes in being so well designed!
