### ISSUE TITLE
AjaxView should extend AppView instead of View

### ISSUE THREAD

**Issue by Casmo** [cakephp/cakephp#6743]
Situation:
In my `AppView::initialize();` I check a few parameters and session variables to decide whether I would show a theme or not.
This all works great until one of the requests is an ajax call.

This is because the `AjaxView.php` in `/cakephp/src/View/AjaxView.php` extends `View` and not `AppView`.

**Comment by ADmad** [comment]
Making a core class extend app class might not be a good idea though. We could add an `AjaxView` to the app skeleton to resolve this.

**Comment by markstory** [comment]
We can't have core classes extend classes that don't exist in the repo. Subclass the AjaxView if you need it to behave differently.

@ADmad I don't think moving the AjaxView will work. RequestHandlerComponent relies on AjaxView.

**Comment by ADmad** [comment]
@markstory Hence I suggested adding instead of moving :)

**Comment by ADmad** [comment]
That said those I don't think it's wrong to expect those wanting to return html fragment for ajax requests to ensure they have `AjaxView` in their app to get the auto layout switching. Based on [this](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/RequestHandlerComponent.php#L551-L564) code I don't think `RequestHandler` would throw and error if `AjaxView` does not exist.

**Comment by markstory** [comment]
It doesn't rely on it, but moving AjaxView out into the App skeleton will break all the existing applications when they upgrade to a CakePHP without an AjaxView.

XmlView and JsonView also do not extend AppView, and will have similar issues. Similarly we don't have the concept of an AppHelper anymore either. Is copying AjaxView into an app so it can be customized an unacceptable solution?

**Comment by ADmad** [comment]
> Is copying AjaxView into an app so it can be customized an unacceptable solution?

It surely is but many users wont figure that out easily which is why I suggested adding (not moving) an AjaxView to app skeleton.

**Comment by markstory** [comment]
Ok, I misread your earlier comments, adding an AjaxView to the app skeleton works for me.

**Comment by Casmo** [comment]
Doesn't this break any future updates to the `AjaxView::__construct();` in the Cake core?

**Comment by ADmad** [comment]
No. The signature of all view class constructor would be identical to `View::__construct()` and that won't change (if at all) until next major release because that would be a BC break.
