### ISSUE TITLE
Containable behavior between two different databases.

### ISSUE THREAD

**Issue by lucianoqueiroz** [cakephp/cakephp#6744]
Let's suppose that I have two databases configs: $default and $foo. The $default config is used by the application and the $foo is used by a plugin named Foo.

I'm able to make relationships between the configs, like ModelA belongsTo Foo.ModelF and etc. But when I try to use the containable behavior like $this->Model->contain('Foo.ModelF') I get a message that Model is not related with Foo Model, but Foo is a Plugin.

Some tip or help?

Thanks in advance!

**Comment by ADmad** [comment]
Argument to `contain()` doesn't take model name with prefix. If you have setup proper association between ModelA and Foo.ModelF just do `$this->Model->contain('Foo.ModelF')`.

**Comment by lucianoqueiroz** [comment]
Thanks man! I haven't realized that it's that simple. :)
