### ISSUE TITLE
baking Views in 2.6.7 does finish correctly if "default" connection is invalid

### ISSUE THREAD

**Issue by reinweb** [cakephp/cakephp#6745]
if "default" database connection is not a working connection, it is not possible to bake Views correctly
(model and controller baking works find)

**Comment by markstory** [comment]
Ok. Bake can't really work well without the connection as it will not be able to reflect the columns in the database. I think having a working connection is a reasonable prerequisite for bake to have.

**Comment by reinweb** [comment]
Basically agree - so I describe with all details::
I do not use a default connection (for "safety" reasons i configure the connection "default" with invalid Valued), so I configure other db connections in database.php.
Starting to bake the mode I choose the correct dbconfig and select the table of the list.
But when I try to bake the View (after successful baking the Model and Controller) I get an Error.
To success, I have to define a working "default" db-connection ( even if I select another dbconfig during bake process).
It seems that the view-baking process tries (also) to connect to the "default" - independent of the choosen db-config.
Hope to have described it less confusing now!

**Comment by markstory** [comment]
I don't think there was any confusion earlier. Why is making a connection to the default source an issue? Instead of using a broken connection, perhaps you should use a read only login.

In any case I don't think there is anything that can be fixed here. View generation needs a database connection.

**Comment by reinweb** [comment]
I am very sorry to have tried to move the error to the Cake-side. The mistake was on my side [of course].
The reason was a wrong model association. This was the reason, why bake process tried to use the "default" connection.
However:: Cake rules - I'm loving it!
