### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by phpraven** [cakephp/cakephp#6748]
Hello,
Can sameone help me, I have all the time 502 Bad Gateway when I make pr or similar functions. Besides this everything works fine.

error.log
2015/06/06 14:34:20 [error] 11591#0: *15 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 83.238.276.91, server: domena.pl, request: "POST /users/login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "domena.pl", referrer: "http://domena.pl/users/login"

nginx
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /www/domena.pl/htdocs/webroot;
	index index.php index.html index.htm;

	server_name domena.pl www.domena.pl;

	access_log /www/domena.pl/logs/access.log;
	error_log /www/domena.pl/logs/error.log;

   location / {
        index  index.php index.html index.htm;
        try_files $uri $uri/ /index.php?$uri&$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
	}
}

**Comment by AD7six** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
