### ISSUE TITLE
Validation: notEmpty vs. notBlank

### ISSUE THREAD

**Issue by php-engineer** [cakephp/cakephp#6752]
I'm a bit confused about the usage of `notEmpty` and `notBlank` and the usage of custom error messages. It seems that you can use `notEmpty` in two different ways:

(1) Not possible to set the error message. You always get the default one.
```
$validator
    ->add('username', [
        'notEmpty' => [
            'rule' => 'notEmpty',
            'message' => 'My custom message.'
   ]);
```

(2) Possible to set a custom error message.
```
$validator
    ->notEmpty('username', 'My custom message');
```

Since 3.0.2 it's recommended to use `notBlank` instead of `notEmpty`. As far as I can see there is only one way for `notBlank`.

(1) Also not possible to set a custom error message.
```
$validator
    ->add('username', [
        'notBlank' => [
            'rule' => 'notEmpty',
            'message' => 'My custom message.'
   ]);
```

Both ways (`notEmpty` and `notBlank`) are documented in the docs so know I'm quite unsure which one I should use. I preferred the `notBlank` because the other one is deprecated but there it wasn't possible to set a custom error message.

There is an issue about consistency at the validation rules, so I will reference it here but is not really related. Refs: https://github.com/cakephp/cakephp/issues/6444

**Comment by lorenzo** [comment]
where is it recommended to use `notBlank` ?

**Comment by php-engineer** [comment]
`notEmpty` is deprecated so I thought it's better to use `notBlank` or I'm on the wrong way?

**Comment by ADmad** [comment]
> (1) Not possible to set the error message. You always get the default one.

The reason why that happens is stated #6284. That's the reason `Validation::notEmpty()` was deprecated and `Validation::notBlank()` added in #6285.

**Comment by ADmad** [comment]
So if want to ensure a field is not empty use 
```php
$validator->notEmpty('username', 'custom mesage');
```
and if you want to ensure a field is not empty and also does not contain only whitespace use 

```php
$validator
    ->add('username', [
        'notBlank' => [
            'rule' => 'notBlank',
            'message' => 'My custom message.'
   ]);
```

**Comment by ADmad** [comment]
> I preferred the notBlank because the other one is deprecated but there it wasn't possible to set a custom error message.

It is possible. Your usage in the example you provided is incorrect. You need `'rule' => 'notBlank'` instead of `'rule' => 'notEmpty'`.

**Comment by php-engineer** [comment]
Thanks for your quick response. I understand the difference between them now. They are two different things and that was probably the reason for renaming. So in general I could use both togehter?

```
$validator
    ->notEmpty('username', 'custom mesage') // check if field is empty
    ->add('username', [
        'notBlank' => [ // check if field contains more than whitespaces
            'rule' => 'notBlank',
            'message' => 'My custom message.'
   ]);
```

**Comment by ADmad** [comment]
>  So in general I could use both togehter?

Yes you can.
