### ISSUE TITLE
Error installing Bake with composer

### ISSUE THREAD

**Issue by Tomicapo** [cakephp/cakephp#6754]
I tried to install bake as documented at: http://book.cakephp.org/3.0/en/bake.html but I got the following error:
> 
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: cakephp/cakephp[dev-master, 3.0.6].
>     - Can only install one of: cakephp/cakephp[dev-master, 3.0.6].
>     - Can only install one of: cakephp/cakephp[dev-master, 3.0.6].
>     - cakephp/bake dev-master requires cakephp/cakephp dev-master -> satisfiable by cakephp/cakephp[dev-master].
>     - Installation request for cakephp/bake dev-master -> satisfiable by cakephp/bake[dev-master].
>     - Installation request for cakephp/cakephp == 3.0.6.0 -> satisfiable by cakephp/cakephp[3.0.6].
> 
> Installation failed, reverting ./composer.json to its original content.

Here's a copy of my composer.json:
```javascript
{
	"name": "cakephp/app",
	"description": "CakePHP skeleton app",
	"homepage": "http://cakephp.org",
	"type": "project",
	"license": "MIT",
	"require": {
		"php": ">=5.4.16",
		"cakephp/cakephp": "~3.0",
		"mobiledetect/mobiledetectlib": "2.*",
		"cakephp/migrations": "~1.0",
		"cakephp/plugin-installer": "*",
		"cakephp/debug_kit": "~3.0"
	},
	"suggest": {
		"phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
		"cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
	},
	"autoload": {
		"psr-4": {
			"App\\": "src"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"App\\Test\\": "tests",
			"Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
		}
	},
	"scripts": {
		"post-install-cmd": "App\\Console\\Installer::postInstall",
		"post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump"
	},
	"minimum-stability": "dev",
	"prefer-stable": true
}
```

**Comment by ADmad** [comment]
This issue was moved to cakephp/app#257

**Comment by ADmad** [comment]
This issue was moved to cakephp/app#258
