### ISSUE TITLE
Cache engine Cake\Cache\Engine\MemcachedEngine is not properly configured.

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6758]
My Memcached Installed Success.

Use PHP connect memcached success.

But Use CakePHP connect memcached fail.

This is My Cache Config:

'Cache' => [
        'memcached'=>[
            'className'=>'Memcached',
        ],
        'default' => [
            'className' => 'File',
            'path' => CACHE,
        ],
];

My Controller:

<?php

namespace App\Controller;

use App\Controller\AppController;
use Memcache;
class HomeController extends AppController
{
    public function index(){
        
        \Cake\Cache\Cache::write('a','b','memcached');
    }
}

**Comment by macnie** [comment]
yes, That's because cakephp\cakephp\src\Cache\Engine\MemcachedEngine.php line:105 ,return false.

if (!extension_loaded('memcached')) {
            return false;
        }

but i use this code return true:
if (extension_loaded('memcache')) {
            $mem = new Memcache();
            $mem->connect("127.0.0.1",11211);
            $mem->set('a','macnie');
            echo $mem->get('a');
            // putout  macnie
        }else{
              
        }

**Comment by dakota** [comment]
CakePHP uses the `php_memcached` extension, not the older `php_memcache` extension (Note the missing **d**). Which means that you probably installed `php_memcache`. Try removing `php_memcache` and installing `php_memcached`. Let us know if that works.

**Comment by macnie** [comment]
I can't find the windows php_memcached.dll for PHP 5.5 in whole internet...  but php_memcache.dll has more.

**Comment by rchavik** [comment]
http://php.net/manual/en/memcached.installation.php

**Comment by ADmad** [comment]
@macnie If for whatever reason you cannot install the Memcached extension for your environment, copy the MemcachedEngine to your app and make required changes to use memcache intead of memcached.

**Comment by macnie** [comment]
@ADmad Fine! I was just going to do this! because my web server system is windows. I will share my MemcacheEngie.php .

**Comment by ADmad** [comment]
You can publish your MemcacheEngine as a plugin.

**Comment by dakota** [comment]
@drailanjohngss 

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
