### ISSUE TITLE
Custom attributes/substitutions in FormHelper templates

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6759]
Currently you can set custom templates for generating form control, as documented here:
http://book.cakephp.org/3.0/en/views/helpers/form.html#customizing-the-templates-formhelper-uses

However I have found that it is not flexible enough as there is no way of passing custom replacement to the new template, something like this:
```php
// The template:
['inputContainer' => '<div class="form-control" id="{{customId}}">{{content}}</div>']
//Then from the view:
$this->Form->input(...., ['customId' => 'my-id'])
```
Which should produce the following output:

    <div class="form-control" id="my-id">...</div>

Possibly the template parameters could be passed within thier own array to distinguish between input and template properties:
````php
$this->Form->input(...., ['class' => 'input-class', 'templateParams' => ['customId' => 'myId']])
````

**Comment by ADmad** [comment]
The reason view templates were introduced was to avoid having tons of options for helper methods as it makes code maintenance difficult.

The templates can be overriden per `FormHelper::input()` call too,  so you can do:

```php
$this->Form->input(...., ['templates' => ['inputContainer' => '<div class="form-control" id="my-id">{{content}}</div>']]);
```

**Comment by cmann1** [comment]
For this feature you would only need one extra option: `templateParams`, and at the moment the templates are not very customizable at all.

I feel that the solution you provided is not very elegant, and also, in my opinion, goes against the concept of a *template* if I have to copy the template any where that I need to use it.

**Comment by markstory** [comment]
We could pass all the options to the wrapper/container templates. It would allow people to template arbitrary attributes. I don't think this would work for label/input templates though as they already convert unknown attributes into html attributes. I have some concern that adding inconsistent behavior will make the helpers harder to understand and reason about.

**Comment by cmann1** [comment]
Another example of what I would need this for is that I would like to add hints to certain inputs on some forms.
So first what I did was:
```php
$this->Form->input(...., ['templates' => 'label' => '<label{{attrs}}>{{text}}<span class="hint"> - This is  hint text</span></label>']]);
```
But having to repeat that for every single input was annoying, so what I did is used a placeholder in the template and used str_replace:
```php
// At the top of my view
$hintTpl = ['label' => '<label{{attrs}}>{{text}}<span class="hint"> - _HINT_</span></label>'];
// Then to output an input
echo str_replace(
	'_HINT_',
	__('This is the hint'),
	$this->Form->input(..., ['templates' => $hintTpl]));
```
I thought that this was a bit better but it still requires me to re-declare the template in every single view that I want to use this in.
I guess that could maybe be helped by adding a `hintInput` method to `AppView` that will automatically add the template option and call `str_replace`.

**Comment by HavokInspiration** [comment]
I had a similar need for a "hint" or "help" element.
What I did was extend the original ``BasicWidget`` (that deals with rendering basic inputs for the ``FormHelper``) to redefine the ``render()`` method :

```php
//in src/View/Widget/BasicWidget.php
namespace App\View\Widget;

use Cake\View\Form\ContextInterface;
use Cake\View\Widget\BasicWidget as BaseBasicWidget;

/**
 * Subclass of the BaseWidget.
 */
class BasicWidget extends BaseBasicWidget
{

    public function render(array $data, ContextInterface $context)
    {
        $data += [
            'name' => '',
            'val' => null,
            'type' => 'text',
            'escape' => true,
            'help' => ''
        ];
        $data['value'] = $data['val'];
        unset($data['val']);

        return $this->_templates->format('input', [
            'name' => $data['name'],
            'type' => $data['type'],
            //next line adds the ability to my input template to use a {{help}} variable
            'help' => $this->formatHelp($data['help']),
            'attrs' => $this->_templates->formatAttributes(
                $data,
                ['name', 'type', 'help'] //exclude the help variable
            )
        ]);
    }

    public function formatHelp($data)
    {
        if (empty($data)) {
            return '';
        }

        $default = [
            'tag' => 'span',
            'text' => '',
            'classes' => ''
        ];

        if (!empty($data['classes'])) {
            $data['classes'] = ' ' . $data['classes'];
        }

        $data = array_merge($default, $data);

        return $this->_templates->format('help', $data);
    }
}
```

Then told the FormHelper to use my BasicWidget :

```php
//in src/View/AppView.php
$this->loadHelper('Form', [
    'widgets' => [
         '_default' => ['App\View\Widget\BasicWidget']
    ]
]);
```

Then configured my new "help" template with my others Form templates and told the input template to use a "help" template :

```php
$config = [
    'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}>{{help}}',
    'help' => '<{{tag}} class="help-block{{classes}}">{{text}}</{{tag}}>',
];
```

Now it is possible to easily add a help block when creating an input :

```php
$this->Form->input(..., [
     //core options goes here
	'help' => [
		'tag' => 'div',
        'classes' => 'very-important blink',
		'text' => 'This is a hint message.'
	]
]
```

This is not the full code (which do other stuff) : I rearranged it to make it smaller, so it might triggers errors since I did not tested it. But the basic idea is here.

As for the original issue, maybe we need a way of defining new template variables without the need to rewrite the Widgets ? And make this list of variables excluded when ``formatAttributes()`` is called ? But that might be tricky because we need to find a way to define what parameters will be given to ``format()``.
Off the top of my head, something like that :

```php
$this->loadHelper('Form', [
    'variables' => [
        //"help" is the  variable name and the array value is the list of params to pass to format().
        //Anything else will be passed to formatAttributes() 
        'help' => [ 
            'tag',
            'classes',
            'text'
        ]
    ]
]);
```

This way, when devs do the Form input call I wrote above, the list of parameters is matched to the one passed and everything is formatted following the "help" template defined by the dev.

Hope I'm clear enough.

**Comment by markstory** [comment]
Is having to build widgets to get custom functionality a bad thing though?

**Comment by HavokInspiration** [comment]
You mean to add that "help" block we are talking about for instance ? Not really, no.
It's more cumbersome though.
The process to "just" add something like that is not really obvious to make it easy to manage and use.

**Comment by cmann1** [comment]
> Is having to build widgets to get custom functionality a bad thing though?

If you want some more advanced functionality, then I would say there's no problem with building a widget, but, in my opinion, having to do all of the above just so that you can add a class or id to you container div seems like too much.
And as HavokInspiration said you have to do this for every type of input.

I also found this behaviour unintuitive, I was surprised to find that there was no way to pass custom parameters to templates.

**Comment by markstory** [comment]
Rereading the original issue, the additional `templateParams` idea could work well. Each template interpolation could get the normal parameters plus anything defined in the templateParams. Having the additional key lets us ensure the custom keys don't get smushed into html attributes.

**Comment by ADmad** [comment]
Closing as PR has been opened.
