### ISSUE TITLE
2.x dynamically set validation rule

### ISSUE THREAD

**Issue by Avemaar** [cakephp/cakephp#6762]
I was looking for a lot to find an official explanation how can i dynamically set validation rule.
The only thing i know is: 
unset($this->Group->Person->validate['firstName']);

In my case i have 2 models on the same page.
If the second fields are empty i don't want that the validation rules are set.
But if the first field is not empty than the rest of the fields are required.
(and other validation rules like custom validation rules matchpasswords also activated)

**Comment by Avemaar** [comment]
it is some kind of conditional validation.I saw it is implemented in 3.x

**Comment by markstory** [comment]
unset() won't set validation rules, it will only unset them. If instead you want to add validation rules you can either modify the validate property, or use `$model->validator()` to get a validator instance and use its methods to set validation methods.

If you need help with CakePHP the bug tracker is not the best place for it. Instead try and use stackoverflow or IRC :smile:
