### ISSUE TITLE
RFC:  How hard would it be for me to use Cake\Network\Http\Client outside of a CakePHP context?

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#6763]
To clarify, I use `Cake\Core` for a few CLI scripts and other mini-projects, especially for `InstanceConfigTrait` which is really handy.

I also tend to write a lot of Api client classes from time to time, and when I'm in the context of a CakePHP application or plugin I always just extend/utilize `Cake\Network\Http\Client` because it's awesome.  But when I'm not, I have to build an Api connector class from scratch usually.

Is there any way for me to use `Cake\Network\Http\Client` in some standalone php CLI script (for example)?  If there's a way to do this, I would _love_ to.  It would allow me to standardize the way I write api connector classes in general, and allow me to more easily merge/cannibalize disparate mini-projects in the future into bigger projects, (usually a bigger CakePHP project).  It would also allow me to maybe build Api interfaces and adapters for the things I work on and keep things consistent.

Is it too coupled to CakePHP to be reasonably released as a standalone, unlike some of the other sections of the project that you've decoupled, like Core, ORM, etc?

**Comment by markstory** [comment]
No its not hard to split out the http\client code. We've just not done it as no one has ever requested it before. The Http\Client doesn't have many dependencies from what I remember (but its been a while).

If you want to help with this you'll need to put a composer.json and readme together for the network\http package. There are a few examples already in the existing subtree splits.

**Comment by kevinquinnyo** [comment]
@markstory Thanks.  I'll see what I can do to help on this.  I've been so busy lately I can't even follow up on the other PR #6712 I submitted...  I do really want to help in releasing your `Client

**Comment by josegonzalez** [comment]
@markstory The Client was moved from `Network\Http` to `Http` - I guess because of PSR-7 - but are there other things we should do here?

**Comment by markstory** [comment]
I briefly attempted making a standalone package for `cake/http` however, because of the RequestTransformer and ResponseTransformer the package is still very much intertwined with the rest of the framework. One of my side goals for the PSR7 work is to break up those dependencies a bit and end up with a more standalone `http` package.

**Comment by dereuromark** [comment]
Is this something we want to look into for 4.x?
Or are we closing this?

**Comment by markstory** [comment]
I'd like to get it done as part of 4.x

**Comment by dereuromark** [comment]
OK, Added to roadmap then: https://github.com/cakephp/cakephp/wiki/4.0-Roadmap
