### ISSUE TITLE
3.x - FormHelper->radio() does not print hiddenField when value is set but does not exist in options

### ISSUE THREAD

**Issue by alaxos** [cakephp/cakephp#6771]
I have some documents that can have 3 different statuses. I'm trying to build a form that allows to update documents from status 1 to status 2 or 3. Therefore I'd like to use two radio buttons with status 2 and 3 respectively.

In this situation, the document has got status_id = 1, but this value is not in the radio options. So when the form loads, no radio button is selected. If the form is submitted like this, the request is black-holed by the SecurityComponent as no hiddenField is used.

By looking at the code it seems that the problem comes from a test in the FormHelper->radio() method that checks that the Entity doesn't have any value for the field:

```php
if ($hiddenField && (!isset($value) || $value === '')) {
   ...
}
```
But if the entity has a value that does not exist in the options, shouldn't the hidden field be used as well ?

**Comment by markstory** [comment]
I don't think this scenario has come up before. Putting the unknown option into a hidden input would make radio() work differently than select(), and checkbox() which I'm not a fan of. If we made all the methods consistent we could make a change.

**Comment by alaxos** [comment]
@markstory The idea wouldn't be to put the unknown option into the hidden field, but to effectively get the hidden field with an empty value in order to prevent the black-hole. 

Currently as the hidden field is missing, if no option is manually selected, the field is not posted at all, making the Security component block the request. Thus clicking the submit button just after the page has loaded results in a black-hole.

**Comment by dereuromark** [comment]
@alaxos I agree. The input should always at least post an empty string here.

**Comment by markstory** [comment]
@alaxos ok I wasn't clear on what you wanted/expected. I agree that including the empty input is reasonable.

**Comment by markstory** [comment]
Pull request up now.

**Comment by alaxos** [comment]
Thanks Mark !
