### ISSUE TITLE
Find query should support FOR UPDATE for mysql

### ISSUE THREAD

**Issue by klickagent** [cakephp/cakephp#6772]
Could you please add the mysql FOR UPDATE functionality to the find method for models (https://dev.mysql.com/doc/refman/5.0/en/innodb-locking-reads.html). Eg:
$article->find('first')->where('id', 10)->for('update'); 

(example from a similar feature request: https://github.com/cakephp/cakephp/issues/3136#event-213462937)

**Comment by lorenzo** [comment]
I'm reluctant to add this feature. But you can still have it today without code change in cakephp:

```php
$article->find('first')->where(['id' => 10])->epiloge('FOR UPDATE');
```

**Comment by markstory** [comment]
Yeah, I'd like to not have funny MySQL things added either.

**Comment by klickagent** [comment]
Thanks for your advice. After some searching I figured out that it is actually called epilog (without an e)
$article->find('first')->where(['id' => 10])->epilog('FOR UPDATE');
It works fine. Thanks!
