### ISSUE TITLE
Automatic Route name prefixes

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6773]
The idea is to help you build route names easier by letting the scopes have name prefixes, this would probably remove the tedium of having to define the all manually and would encourage people a bit more of using named. For example:

```php
Router::scope('/articles', ['controller' => 'Articles' , '_namePrefix' => 'Admin::'], function ($routes) {
    $routes->connect('/add', ['action' => 'add'], ['_name' => 'add']);
})
```

It would create a route with the name `Articles::add`

**Comment by markstory** [comment]
I can work on this.

**Comment by markstory** [comment]
Did you mean the name would be `Admin::add` or `Admin::Controller::add`?

**Comment by jadb** [comment]
@markstory if I go by @lorenzo's talks at CakeFest, I think `Admin::add`.

**Comment by lorenzo** [comment]
Closing as https://github.com/cakephp/cakephp/pull/6797 was opened
