### ISSUE TITLE
Boolean conditions not properly generated in contains

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6775]
I have three tables: `books`, `books_languages` and `languages` using a BelongsToMany association.

The `books` and `books_languages` both have a deleted column `TINYINT(1)` used for a soft delete.
When searching the `books` table this works as expected:
```
$this->Books->find()->where(['Books.deleted' => false]);
```
which generates the following sql:
```
SELECT Books.id AS `Books__id`, Books.title AS `Books__title`
FROM books Books
WHERE Books.deleted = 0
```

However doing the same thing in a contain does not correctly convert `false` into a `0` in the sql:
```
$book = $this->Books->find()
	->contain(['Languages' => function($query){
		return $query->where(['BooksLanguages.deleted' => false]);
	}])
```
SQL:
```
SELECT BooksLanguages.language_id AS `BooksLanguages__language_id`, BooksLanguages.id AS `BooksLanguages__id`, BooksLanguages.book_id AS `BooksLanguages__book_id`, BooksLanguages.deleted AS `BooksLanguages__deleted`, Languages.id AS `Languages__id`
FROM languages Languages INNER JOIN books_languages BooksLanguages ON Languages.id = (BooksLanguages.language_id)
WHERE (BooksLanguages.book_id in ('53') AND BooksLanguages.deleted = '')
```

**Comment by markstory** [comment]
I suspect this stems from the BooksLanguages table columns not being selected, and therefore aren't having their type info set into the TypeMap. As a workaround, you can pass the type information as the second parameter.

```php
->where(['column' => false], ['column' => 'boolean']);
```

**Comment by cmann1** [comment]
Thanks, that worked.
I have also found that giving a plain string also works if you don't need any other logic for the value:
```
$query->where(['BooksLanguages.deleted = 0']);
```

**Comment by markstory** [comment]
Pull request up now.
