### ISSUE TITLE
Request using HttpSocket hangs when webserver doesn't close connection

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#6776]
HttpSocket reads until EOF, so when the webserver doesn't close the connection, HttpSocket hangs (until timeout). For example Apache 2.4 doesn't close the connection when using https

**Comment by markstory** [comment]
How do you propose the client handles this?

**Comment by mvdriel** [comment]
@markstory I think the client should use the Content-Length (if set in the response header) to determine the end of the message body.

**Comment by markstory** [comment]
Ok, that will require big changes to the code as headers will need to be parsed before the body is read.

**Comment by markstory** [comment]
I think fixing this issue is outside the scope of how HttpSocket works. If you're interacting with misbehaving servers, you should look at more robust/fully featured solutions like ext/curl.
