### ISSUE TITLE
Is there any way to limit the selected columns in a belongs to many join table?

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6777]
Assuming I have the following related tables:
```
TableA
	id
TableB
	id
TableAB
	a_id
	b_id
	extra_1
	extra_2
	...
```

I then want to find all items in TableB that belong to a record in TableA like so:
```php
$this->TableA->find()
    ->contain(['TableB'])
	->where(['TableA.id' => 1])
```
In this case I am only interested in the data in TableB but all columns from TableAB are automatically selected.
I have looked through the documentation, tried Google and tried different things but it doesn't seem like there is way to specify which fields must be fetched from the joining table.

**Comment by markstory** [comment]
Use the `select()` method to explicitly list the fields you want.

**Comment by cmann1** [comment]
I do, but the join table fields ares unaffected.

**Comment by markstory** [comment]
You can use `$query->autoFields(false)` to disable additional fields from being added into the query. Calling `select($field, true)` after `contain()` should also avoid the duplicate fields.

**Comment by cmann1** [comment]
I'm pretty sure I tried that, but I suppose I should try again and give some example code.

**Comment by cmann1** [comment]
OK, here are my tables:
```
Books
	id, title
Languages
	id, name,
	code, iso_code // < Fields I don't need
BooksLanguages
	id, book_id, language_id,
	deleted, book_font // < Extra join data fields I don't need
```
So what I want is to fetch a single book from `Books` and all associated `Languages`.
But in this case I only need the book details, `Languages.name`, and `BooksLanguages.delete`.
Running the following code as you suggested using `select()` and `autoFields(false)`:
```php
$query = $this->Books->findById($bookId)
	->select(['id', 'title', 'language_id'], true)->autoFields(false)
	->contain('Languages');
$book = $query->first();
````
I get the following results and sql (This is copied straight from the DebugKit console):
```
books(array)
	id 53
	title Title
	languages(array)
		0(object)
			id 13
			name 34v43534g5
			code 34
			iso_code g34		// < I don't want this
			deleted (false)		// < or this
			_joinData (array)
				language_id 13
				id 1
				book_id 53
				book_font		// < or this
				deleted (false)
		1(object)
			id 7
			name English
			code en
			iso_code eng
			deleted (false)
			_joinData (array)
				language_id 7
				id 2
				book_id 53
				book_font
				deleted (false)
```
```sql
SELECT Books.id AS `Books__id`, Books.title AS `Books__title`, Books.language_id AS `Books__language_id`
 FROM books Books
 WHERE Books.id = 53 LIMIT 1	1	1
SELECT BooksLanguages.language_id AS `BooksLanguages__language_id`, BooksLanguages.id AS `BooksLanguages__id`,
	 BooksLanguages.book_id AS `BooksLanguages__book_id`, BooksLanguages.book_font AS `BooksLanguages__book_font`,
	 BooksLanguages.deleted AS `BooksLanguages__deleted`, Languages.id AS `Languages__id`, Languages.name AS `Languages__name`,
	 Languages.code AS `Languages__code`, Languages.iso_code AS `Languages__iso_code`, Languages.deleted AS `Languages__deleted`
 FROM languages Languages INNER JOIN books_languages BooksLanguages ON Languages.id = (BooksLanguages.language_id)
 WHERE BooksLanguages.book_id in ('53')
```
As you can see the `select()` call has had no affect on `Languages` or `BooksLanguages`.
After some searching I found that you can pass options to the contain statement so I changed it to this:
```php
->contain(['Languages' => [
	'fields' => ['BooksLanguages.book_id', 'Languages.id']
]]);
```
This successfully limited the selected fields in `Languages`, but all fields from `BooksLanguages` were still selected, it now gave something like this:
```
books(array)
	id 53
	title Title
	languages(array)
		0(object)
			id 13
			_joinData (array)
				language_id 13
				id 1
				book_id 53
				book_font			// < Still there
				deleted (false)		// < Still there
```

**Comment by markstory** [comment]
Ok, because your associations decompose into multiple queries you'll have to set fields in the contain() as you found out. I originally thought your associations were being loaded from a single query with a join - my mistake.

I'm not sure there is an easy way to elide fields from the junction table, that will require some more digging I think.

**Comment by gauravmak** [comment]
I was facing the same issue. However, using the **->autoFields(false)** worked for me in *contain()*.
But, I am not sure how to specify the columns to be fetched from parent table as well as associated table. Is I specify the columns in parent table, nothing gets fetched from associated table. I even tried to specify the column names prefixed with the respective model names (plugin syntac) at both the places but not working.
