### ISSUE TITLE
3.0.6 - Subquery w/hasMany creating bad SQL

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6781]
Hi guys. When defining a `hasMany` relationship with a `strategy` of `subquery` it tries to use an undefined column as the `foreignKey` (ignoring the `foreignKey` I'm trying to use).  As I understand it, either way should work without having to change anything. I'd prefer to use `subquery` since I'm dealing with a lot of data.

I have this..
```
$ft = TableRegistry::get('FeaturedTags');
$ft->belongsTo('Tags');

$t = TableRegistry::get('Tags');
$t->hasMany('_i18n', [
    'foreignKey' => 'id',
    'className' => 'TagsTranslations',
    'strategy' => 'subquery'
]);

$featuredTags = $ft
    ->find()
    ->contain(['Tags' => ['_i18n']])
    ->toArray();
```
This produces..
```
SELECT `_i18n`.`id` AS `_i18n__id`, `_i18n`.`locale` AS `_i18n__locale`, `_i18n`.`name` AS `_i18n__name` FROM `tags_translations` `_i18n`
INNER JOIN (
    SELECT (`Tags`.`tag_id`) FROM `featured_tags` `FeaturedTags`
    LEFT JOIN `tags` `Tags` ON `Tags`.`id` = (`FeaturedTags`.`tag_id`)
    GROUP BY `Tags`.`tag_id`
) `Tags` ON `_i18n`.`id` = (`Tags`.`tag_id`)
```

However, ``Tags.tag_id`` doesn't exist. It should be ``Tags.id``. I think in the past something like this came up. I checked out everything back to 3.0.0 and it didn't fix it. Changing it to `select` gets me the data I need.

Schema..
```
CREATE TABLE `featured_tags` (
  `tag_id` int(11) NOT NULL,
  `priority` int(11) NOT NULL,
  PRIMARY KEY (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `family` int(11) NOT NULL DEFAULT '0',
  `priority` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=711 DEFAULT CHARSET=latin1;

CREATE TABLE `tags_translations` (
  `id` int(10) unsigned NOT NULL DEFAULT '0',
  `locale` varchar(5) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `name` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  PRIMARY KEY (`id`,`locale`),
  FULLTEXT KEY `title` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by markstory** [comment]
It looks like the subquery is getting confused between the `featured_tags` and `tags` table columns.

**Comment by patrickconroy** [comment]
It looks like `SelectableAssociationTrait::_buildSubquery` is doing this incorrectly..
```
$keys = (array)$query->repository()->primaryKey();
```
Since my situation is a find on a table that contains a `belongTo` which `hasMany`, it's getting the primaryKey for the head query instead of the parent. My case has a PK that isn't `id`, which means this error comes out. If my PK was `id`, it would work but serendipitously so instead of on purpose.

If I make that this, it works, phpunit seems fine with it.
```
$keys = (array)$this->source()->primaryKey();
```

Also, shouldn't that be singular `key`? Or can a Table have multiple PKs..? If that change looks ok to you I can make a PR.

**Comment by markstory** [comment]
We support composite keys in the ORM so primaryKey() is always converted into an array so that composite keys and single keys are treated the same.

That fix seems reasonable to me, a pull request would be great.

**Comment by patrickconroy** [comment]
Thanks @markstory, closing this with the PR.
