### ISSUE TITLE
Association Alias vs. className

### ISSUE THREAD

**Issue by grossrucker** [cakephp/cakephp#6783]
I am trying to setup a multiple belongsTo association on the same table. one table contains api keys and the second contains privileges assigned by one api key to a second api key:

extract from my tables:

table:api_keys
INT id (primary key)
VARCHAR api_key_str

table:privileges
INT id (primary key)
INT owner_api_key_id (foreign key api_keys:id)
INT target_api_key_id (foreign key api_keys:id)
TEXT data

Next I defined the two association inside the privileges table:
$this->belongsTo('OwnerApiKeys', [
            'className' => 'ApiKeys',
            'foreignKey' => 'owner_api_key_id',
            'joinType' => 'INNER'
]);
$this->belongsTo('TargetApiKeys', [
            'className' => 'ApiKeys',
            'foreignKey' => 'target_api_key_id',
            'joinType' => 'INNER'
]);

Baking the controller and templates worked fine. I can now open the privileges/add form, choose my api keys from the drop down fields and enter the data. So far, everything seems good.

However, an error occurs when saving the new dataset. It states that there is no schema for the table. What it is supposed to do here is to get the schema of the ApiKeys table. What it really does is trying to find a schema for the not existing "OwnerApiKeys"/"TargetApiKey" Tables during the RuleChecking procedure.

Workaround: When I change the alias of both associations to "ApiKeys" the error does not occur. But I believe, since I indicated the corresponding className inside the "belongsTo" statement that there is a bug somewhere referring to the associations alias as table/class name instead of the indicated "className" (which, in the case where I don't specifically define the className would be ok).

**Comment by lorenzo** [comment]
What is the code that is triggering the error?

**Comment by grossrucker** [comment]
Error: Call to a member function schema() on a non-object 
File /homepages/19/d566885631/htdocs/security-as-a-service/cloud/vendor/cakephp/cakephp/src/ORM/Rule/ExistsIn.php 
Line: 83

here is the line:
$schema = $this->_repository->schema();

**Comment by grossrucker** [comment]
$this->_repository is "NULL" here

**Comment by lorenzo** [comment]
Can you show your `buildRules` method?

**Comment by grossrucker** [comment]
public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['owner_api_key_id'], 'ApiKeys'));
        $rules->add($rules->existsIn(['target_api_key_id'], 'ApiKeys'));
        $rules->add($rules->existsIn(['element_type_id'], 'ElementTypes'));
        return $rules;
    }

**Comment by grossrucker** [comment]
I have found out, that when I comment out the two rules the whole thing seems to work fine.
This supports my theory that there might be an issue with the RuleChecker, always referring to the association's alias instead of the className where it is provided.

**Comment by lorenzo** [comment]
Ok, so the issue was that you changed the alias in the `initialize()` but not in `buildRules()`. Closing as it was just an oversight.

**Comment by guyandy** [comment]
@grossrucker was this really an oversight? Did you get it working by correcting the buildRules()? Or did you just remove the rules?

I have run across a very similar situation documented here: http://discourse.cakephp.org/t/using-actual-table-alias-in-buildrules-causing-problems/757
