### ISSUE TITLE
Simpler DebugKit Sql query out

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6784]
Perhaps an option to output simpler queries could be helpful when debugging, currently if you open `Sql Log` tab your queries will be extremely verbose:
```sql
SELECT Languages.id AS `Languages__id`, Languages.name AS `Languages__name`, Languages.code AS `Languages__code`, Languages.iso_code AS `Languages__iso_code`, Languages.is_default AS `Languages__is_default`, Languages.deleted AS `Languages__deleted` FROM languages Languages WHERE deleted = 0 ORDER BY Languages.id desc LIMIT 20 OFFSET 0
```
All of the `Table.col AS Table__col` can be difficult to look through and, in my experience at least, most of the time is not needed.
Maybe the debug kit could format the query, stripping out unnecessary information such as the default `AS` statements.
The above statement would be a lot easier to read and still provide the same information if the `SELECT` part was just: `Languages.id, Languages.name, ...`

If you need to see the original full query maybe it could be shown when you hover over it?

**Comment by markstory** [comment]
I don't really know if that is a good idea. SQL is non-trivial to parse and manipulate, and logging different SQL than was actually executed seems like it could cause as many problems as it solves.

**Comment by ndm2** [comment]
I'd rather like to optionally see the queries in a highlighted, maybe even formatted fashion, or an easier way too hook into the output generation.

For now I've created a plugin with a custom panel extending `SqlLogPanel`, which grabs the `DebugLog` logger, and uses a copy of the `sql_log_panel.ctp` element, where the query output is being formatted using https://github.com/jdorn/sql-formatter.

While this works, it would be nice if something similar would be supported out of the box, or easier to achieve, ie without having to "reimplement" too much code, namely the element in this case.

**Comment by markstory** [comment]
Formatting the queries sounds like a good option.

**Comment by markstory** [comment]
This issue was moved to cakephp/debug_kit#349
