### ISSUE TITLE
Update counter cache on demand

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#6786]
Hello!
there should be an easy way to update counter cache on demand, like Model::updateCounterCache() in Cake 2.6

**Comment by markstory** [comment]
How would you see that being used?

**Comment by damianoporta** [comment]
@markstory using `updateAll()` and `deleteAll()` do not update the counter, so we need a method to update it manually. Should we need to follow Model::updateCounterCache() of Cake2 ?

**Comment by markstory** [comment]
We don't have to be API compatible with 2.x, that's why I asked how you would see this working? If you had to write code in the above scenario, what code would you want to write? What would it do?

**Comment by dereuromark** [comment]
Wouldn't it suffice to make the behaviors' `protected function _processAssociations()` a public method? So you can invoke it manually?

**Comment by damianoporta** [comment]
@dereuromark yes i like this solution

**Comment by markstory** [comment]
I don't think you can _just_ do that as you'll be shy an event object. The current `processAssociations()` method wants entities, but originally you mentioned that you wanted a way to sync the counters for records being modified through updateAll(). Using the current method would require loading up all the modified entities and re-saving them.

**Comment by cleptric** [comment]
This was added with https://github.com/cakephp/cakephp/pull/9960, so I guess we can close this.

**Comment by simonbuehler** [comment]
hi, how can i force the countercache to be recalculated?

**Comment by saeideng** [comment]
> hi, how can i force the countercache to be recalculated?

custom shell + cronjob :)

**Comment by simonbuehler** [comment]
https://gist.github.com/hmic/f38b409bb483de8d5b85bec1e0334abe

works perfect!

**Comment by challgren** [comment]
For those using 2.x I wrote a Shell that allows me to update all the available counters.

```
public function update_counters()
    {
        $this->out('Update all associated counters');
        $this->hr();
        $Model = App::objects('Model');
        $m = $this->in('Model');
        if (!is_null($m) && in_array($m, $Model)) {
            $Model = [$m];
        }
        foreach ($Model as $model) {
            if (in_array($model, ['AppModel', 'QboAppModel'])) {
                continue;
            }
            $update = [];
            $Model = App::objects('Model');
            foreach ($Model as $m) {
                if (in_array($m, ['AppModel', 'QboAppModel'])) {
                    continue;
                }
                $result = ClassRegistry::init($m);
                foreach ($result->belongsTo as $parent => $assoc) {
                    if ($assoc['className'] == $model && !empty($assoc['counterCache'])) {
                        $update[$model][$m][] = $assoc['foreignKey'];
                    }
                }
            }
            foreach ($update as $parent => $assoc) {
                $this->out('Processing counter for ' . $parent);
                $c = ClassRegistry::init($parent);
                foreach (array_keys($c->find('list')) as $id) {
                    foreach ($assoc as $k => $v) {
                        $k = ClassRegistry::init($k);
                        $data = [];
                        foreach ($v as $d) {
                            $data[$d] = $id;
                        }
                        if (!empty($data)) {
                            $k->updateCounterCache($data);
                        }
                    }
                }
            }
        }
    }
```

**Comment by chopstik** [comment]
Here's a Shell to make use of @simonbuehler 's [UpdateCounterCache.php gist](https://gist.github.com/chopstik/2c370a42080b4c97ea4c7c95f449433a):
https://gist.github.com/chopstik/d695d089976012137501c4136513450d
