### ISSUE TITLE
3.x Network\Request::_extensionDetector() dead code (?)

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#6793]
While solving a extension routing setup issue I read through the code and noticed that `Network\Request::_extensionDetector()` seems to be dead code. Running the test cases (with a few skipped) it's never called either.

**Comment by dereuromark** [comment]
Interesting, because there is still a test case here:
```php
    /**
     * Test the accept header detector.
     *
     * @return void
     */
    public function testExtensionDetector()
    {
        $request = new Request();
        $request->params['_ext'] = 'json';
        $this->assertTrue($request->is('json'));

        $request = new Request();
        $request->params['_ext'] = 'xml';
        $this->assertFalse($request->is('json'));
    }
```

**Comment by markstory** [comment]
It does look dead to me as well, it is an uncalled protected method. I'll remove it.
