### ISSUE TITLE
Bug: I18n translation fails join after TreeBehavior->recover()

### ISSUE THREAD

**Issue by Bl00per** [cakephp/cakephp#6794]
I use a  I18n on my table. 
But it throws a DB error after TreeBehavior->recover(); 
It says the following message: "Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous"

See the screenshot for more details. 

How can I fix this? 

cakeversion: 3.0.6

![image](https://cloud.githubusercontent.com/assets/12530269/8130581/d0a06226-1113-11e5-9984-1fbbcee3b23c.png)

**Comment by dereuromark** [comment]
You need to always add the exact version you are using, e.g. `3.0.5` etc.

**Comment by Bl00per** [comment]
I edited my post :-)

**Comment by ADmad** [comment]
@Bl00per Are you adding containments through a beforeFind() callback?

**Comment by Bl00per** [comment]
@ADmad nope! This table only has a beforeSave callback and some containments in the init

**Comment by dereuromark** [comment]
I think it is reasonable to always add the table for the order statement in order for the query to not be ambiguous.

**Comment by ADmad** [comment]
> I think it is reasonable to always add the table for the order statement in order for the query to not be ambiguous.

Yes it is but I want to understand how the joins got into the query. Ideally that query should be done without any joins since they are not needed.

**Comment by ADmad** [comment]
> and some containments in the init

@Bl00per "init" ?

**Comment by Bl00per** [comment]
@ADmad aren't the joins generated by the I18n? 
The table has a Translate Behavior 

And I ment there are belongsTo + hasMany functions in the initialize() within the table class

**Comment by ADmad** [comment]
> aren't the joins generated by the I18n? 

Right, they are. I didn't ready the query carefully. 

I'll fix the ambiguity though for efficiency I would suggest you to detach the behavior before running recover().

**Comment by ADmad** [comment]
Closing as PR is done.
