### ISSUE TITLE
CakePhp 2.6.7 Syntax error Baking validation

### ISSUE THREAD

**Issue by atomCode** [cakephp/cakephp#6796]
I baked a Model with some validations rules and the validation rules array was baked with syntax errors in the validation array. Extra parenthesis:

    $this->validate = array(
		'user_id' => array(
			'notEmpty' => array('rule' => array('notEmpty'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a User', true))),
			'uuid' => array('rule' => array('uuid'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a User', true))) //***extra parenthesis***
    );
**ERRORS**:heavy_exclamation_mark: :
*PHP Parse error:  syntax error, unexpected ',' in /..../app/Model/RepMonthlyCost.php* 

*Parse error: syntax error, unexpected ',' in /.../app/Model/RepMonthlyCost.php*  :heavy_exclamation_mark:
*Fatal Error Error: syntax error, unexpected ',' in [/var..../app/Model/RepMonthlyCost.php*

**Comment by dereuromark** [comment]
Is that current 2.x bake code?
The `__('Please enter a User', true)` part looks bogus to me, too and is actually 1.x syntax (where it didnt return by default).

**Comment by atomCode** [comment]
That's just the message that just got generated from the bake I just did 10 minutes ago, I didn't touch it. I'm running CakePhp 2.6.7.

**Comment by atomCode** [comment]
I'm not sure if the order in which the validation rules I selected matters to replicate this issue with the bakery but as shown on the bake code I selected notEmpty then uuid on the user_id field.

**Comment by ADmad** [comment]
That code is definitely not generated by core's bake template.

**Comment by atomCode** [comment]
@ADmad what do you mean? BTW I just replicated the issue and got the same syntax error again. I have more validation rules that I did not include on the original post. Here is the complete validation array including extra parenthesis:

    $this->validate = array(
			'user_id' => array(
				'notEmpty' => array('rule' => array('notEmpty'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a User', true))),
				'uuid' => array('rule' => array('uuid'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a User', true))),
			'user_compensation_profiles_id' => array(
				'numeric' => array('rule' => array('numeric'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a User Compensation Profiles', true))),
			'bet_network_id' => array(
				'uuid' => array('rule' => array('uuid'), 'required' => true, 'allowEmpty' => false, 'message' => __('Please enter a Bet Network', true))),
		);

**Comment by ADmad** [comment]
@atomCode I mean what I said. [This](https://github.com/cakephp/cakephp/blob/2.6/lib/Cake/Console/Templates/default/classes/model.ctp) is the bake template for models. There's no way that template can generate the code you are showing.

**Comment by atomCode** [comment]
Agreed! I am using a different template indeed.
