### ISSUE TITLE
Routes decouple Table from Controllers.

### ISSUE THREAD

**Issue by genellern** [cakephp/cakephp#6798]
After modifying the route so that I can access files from an URL like this: example.com/3fd9sfd98sdfdf98d/dsf8df8f78

The controller missed the model object, I had to reload it from the controller.
I kept getting this error:
Call to a member function find() on boolean

My route
Router::connect('/:id/:token', ['controller' =>'files', 'action'=>'access'],
	['id' => '[0-9a-z]+', 'token' => '[0-9a-z]+', 'pass' => ['id', 'token']], ['routeClass' => 'InflectedRoute']);

My controller:
$this->loadModel('Files'); // Didn't work without this line.
$file = $this->Files->find('all')->first();

**Comment by lorenzo** [comment]
`'controller' =>'files', ` should have been `'controller' =>'Files',`

**Comment by markstory** [comment]
Yes, your controller name is miscased.
