### ISSUE TITLE
[3.0.6] Duplicate entries in joint table

### ISSUE THREAD

**Issue by fquffio** [cakephp/cakephp#6799]
Hi,
I have two tables (Categories and Contents) with a BTM relation between them configured as such:
```php
// CategoriesTable.php
class CategoriesTable extends Table
{
    public function initialize(array $config)
    {
        $this->table('categories');

        $this->primaryKey('id');
        $this->displayField('title');

        $this->belongsToMany('Contents', [
            'through' => 'CategoriesContents',
            'foreignKey' => 'category_id',
            'targetForeignKey' => 'content_id',
            'joinTable' => 'categories_contents'
        ]);
    }
}

// ContentsTable.php
class ContentsTable extends Table
{
    public function initialize(array $config)
    {
        $this->table('contents');

        $this->primaryKey('id');
        $this->displayField('title');

        $this->belongsToMany('Categories', [
            'through' => 'CategoriesContents',
            'foreignKey' => 'content_id',
            'targetForeignKey' => 'category_id',
            'joinTable' => 'categories_contents'
        ]);
    }
}

// CategoriesContentsTable.php
class CategoriesContentsTable extends Table
{
    public function initialize(array $config)
    {
        $this->table('categories_contents');

        $this->primaryKey('id');
        $this->displayField('id');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Contents', [
            'foreignKey' => 'content_id',
            'joinType' => 'INNER'
        ]);
    }

    public function buildRules(RulesChecker $rules)
    {
        // $rules->add($rules->isUnique(['category_id', 'content_id']));
        $rules->add($rules->existsIn(['category_id'], 'Categories'));
        $rules->add($rules->existsIn(['content_id'], 'Contents'));
        return $rules;
    }
}
```

On new entities all is well, but if I try to update an existing entity in many cases I have issues because the marshaller ignores the fact that a pair of Content / Category are already associated, thus duplicating the entry in the joint table, and I end up with a lot of junk in that table that I really don't want.
I have also tried to add a unique key to `category_id, content_id` columns (either via SQL itself or mocking it with a rule in CategoriesContentsTable — see commented line), but doing so the save just fails.

If I look in the SQL log, I see this line:
```sql
SELECT 1 AS `existing` FROM categories_contents CategoriesContents WHERE (CategoriesContents.category_id = 2 AND CategoriesContents.content_id = 14) LIMIT 1
```
If I run this manually (it's within a transaction, but the table is not-modified, so it should be the same result) I get `existing = 1`, but then the marshaller seems to ignore this and goes on like:
```sql
INSERT INTO categories_contents (category_id, content_id) VALUES (2, 14)
```

I must say that this is pretty a strange case, 'cause Contents have a lot of related models and behaviors attached, but this issue happens only with Categories, that is way simpler. If necessary I can provide you the full code of those models.
Looking at the stack trace it seems that the CategoriesContent entity is marked as new as of
```php
$saved = $junction->save($joint, $options);
```
(`CORE/src/ORM/Association/BelongsToMany.php`, line 551), and then handled as such.

**Comment by markstory** [comment]
How are you converting request data into entities when doing updates? Knowing what code your using to do updates is helpful for someone trying to reproduce this issue. Also what does the schema of your joint table look like?

**Comment by fquffio** [comment]
First of all, thank you for your attention.

The controller method is this:
```php
class ContentsController extends AdminController
{
    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->setAction('edit');
    }

    /**
     * Edit method
     *
     * @param string|null $id Content id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $content = is_null($id) ? $this->Contents->newEntity() : $this->Contents->get($id, [
            'contain' => ['Images', 'Files', 'Videos', 'Categories', 'Authors', 'Users', 'Tags']
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            // All this part is needed to update related models as well.
            $content->files = $this->Contents->Files->patchEntities($content->files ?: [], $this->request->data['files']);
            $content->images = $this->Contents->Images->patchEntities($content->images ?: [], $this->request->data['images']);
            foreach ($content->files as $file) {
                $ok = $this->Contents->Files->save($file);
            }
            foreach ($content->images as $image) {
                $ok = $this->Contents->Images->save($image);
            }

            // This is the failing part: standard patchEntity() + save().
            $content = $this->Contents->patchEntity($content, $this->request->data);
            if ($content->isNew()) {
                $content->user_id = $this->Auth->user('id');
            }
            if ($this->Contents->save($content)) {
                $this->Flash->success('The content has been saved.');
            } else {
                $this->Flash->error('The content could not be saved. Please, try again.');
            }
        }
        $this->set(compact('content'));
        $this->set('_serialize', ['content']);
    }
}
```

The structure of my joint table (MySQL) is this (directly from PMA, sorry if looks ugly):
```sql
CREATE TABLE `categories_contents` (
  `id` int(10) unsigned NOT NULL,
  `category_id` int(10) unsigned NOT NULL,
  `content_id` int(10) unsigned NOT NULL,
  `main` tinyint(1) unsigned NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Categories / Contents associations.';

ALTER TABLE `categories_contents`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `content_id` (`content_id`,`category_id`) USING BTREE,
  ADD KEY `content_id_2` (`content_id`,`main`),
  ADD KEY `category_id` (`category_id`,`content_id`) USING BTREE;

ALTER TABLE `categories_contents`
  MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT;

ALTER TABLE `categories_contents`
  ADD CONSTRAINT `categories_contents_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `categories_contents_ibfk_2` FOREIGN KEY (`content_id`) REFERENCES `contents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
```

This is an example request payload: https://gist.github.com/fquffio/08bbe645003067033c95
(It is to be pointed out that many of those fields are actually virtual properties that were given to the JS application, and then return back to the server — where hopefully will be just ignored — hence the JS app doesn't know how to filter them out, so the meaning part should be restricted to the `"category"` key. No validation error occurs with the payload above.)

**Comment by markstory** [comment]
Thanks, the additional information should help to reproduce the issue.

**Comment by fquffio** [comment]
Ok, the issue seems to be mainly originated by the `id` key in the joint table. Adding a unique key to the foreign columns `content_id, category_id` isn't enough: it must be primary. By doing this, and deleting the `id` column, the save is eventually performed without errors (as far as I could test this morning), even though already existing joint data isn't updated, but I guess this is another issue, or perhaps even intentional at all.

**Comment by lorenzo** [comment]
That is expected. Having an "id" column will allow the others to be duplicated, specially when saving if you do not provide that "id" column in the data array

**Comment by fquffio** [comment]
I see, but I find this a counter-intuitive behavior anyway: the marshaller **always** queries the datasource to find out if a relation between such entities exists, then it happily ignores the information he obtained and tries to perform the save anyway, unless a unique key is present, in which case he leads the save to a fail.

Also, I can not understand why if no additional columns are present in the joint table apart from the primary `id`, all works fine. No doubt I did it wrong, but this is still puzzling me a bit. :smile: Thank you for your help anyway! Not sure if this is still to be considered an issue, then.

**Comment by markstory** [comment]
> I see, but I find this a counter-intuitive behavior anyway: the marshaller always queries the datasource to find out if a relation between such entities exists, then it happily ignores the information he obtained and tries to perform the save anyway, unless a unique key is present, in which case he leads the save to a fail.

Existing entries are identified by primary key. The marshaller doesn't know how to find records based on arbitrary conditions. We built the code around primary keys, as those define the 'identity' for records.
