### ISSUE TITLE
Automatically creating entities from custom joins

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6801]
I have something like this:
```php
$language = $this->Languages->find()
			->select(['id', 'BookLanguage.id'])
			->join(
				['BookLanguage' => [
					'table'			=> 'books_languages',
					'type'			=> 'INNER',
					'conditions'	=> ['BookLanguage.book_id' => $book->id, 'BookLanguage.language_id = Languages.id'],
				]],
				['BookLanguage.book_id' => 'integer'])
			->where(['code LIKE' => $data['language']])
			->first();
```

`$language` will be an instance of the `Language` entity but `$language->BookLanguage` is just a plain array.
It might be helpful if you could tell the join to return BookLanguage as an entity instead.
Maybe you could pass a parameter to the join options and CakePHP will try to create an entity of that type: `'as' => 'BooksLangaugeEntity'`

**Comment by markstory** [comment]
That could be a nice improvement. Is there a reason you don't use contain() on the association? Doing that would let you do the filtering operations and get entities in the result set?

**Comment by cmann1** [comment]
I'm not too familiar with CakePHP so I'm not sure the best way to do it but I couldn't get the results I wanted with contain.
I have a belongs to many relation ship with Languages > BooksLanguages < Books.
If I tried `contain('BooksLanguages')` it would just give the error `Languages is not associated with BooksLanguages`

**Comment by lorenzo** [comment]
What you have done here is already a feature. It is called `mathing()` http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#filtering-by-associated-data

**Comment by markstory** [comment]
You could create the additional relationships that would be needed to do the filtering and use `matching()` like @lorenzo suggested.

**Comment by cmann1** [comment]
Thanks, that worked out, I added `$this->hasMany('BooksLanguages');` and then used `matching` instead of `join` and it worked out.

**Comment by markstory** [comment]
Great to hear @cmann1
