### ISSUE TITLE
3.0 PHPUnit + Integration + Bootstrap events

### ISSUE THREAD

**Issue by mattboothman** [cakephp/cakephp#6802]
Hi

I have an issue where I require an event listener to be registered in bootstrap. The event listens for Controller.initialize and then attaches AuthComponent to the controller and configures it.

Because IntegrationTestCase::setUp() replaces the EventManager instance, this effectively removes the event and prevents it from being dispatched.

I'm not sure how to suggest a fix so I haven't produced one. However, I guess bootstrap could be re-included on setUp which would solve my issue. This seems logical but I wanted to get advice first.

Anyone have any pointers?

Ta

**Comment by markstory** [comment]
We can't easily re-include the bootstrap code as it can easily define functions that will cause errors on re-inclusion.

If you need the global event manager to not be replaced, I would suggest not calling the parent setup() method.

**Comment by mattboothman** [comment]
Ah, yes, I didn't think about that. Thanks Mark.
