### ISSUE TITLE
Cakephp3 : How do Cakephp3 handle   translations  for js  file

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/cakephp#6811]
Cakephp3 : How do Cakephp3 handle   translations  for js  file while  following all set standards of cakephp3.0

**Comment by lorenzo** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
