### ISSUE TITLE
incorrect belongsToMany data saving fails without an error

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#6817]
Tags belongsToMany posts and vica versa.

Trying to save 

    ['title' => 'Post title', 'post' => 'Post body', 'tags' => ''] 

will fail but there are no error messages in `$post->errors()`

The cookbook clearly states how we should form the associated data for saving, but an error message would be helpful. I made a form, I have an autocompleter input, and where the user could select from existing tags and can create new ones, so I create the tags array by javascript. When the user left the tags empty my request data looked like that above. It took me more than 1 hour to find out what is the problem as I did not get any validation error, no debug error, nothing. It just does not save.

**Comment by markstory** [comment]
Why doesn't the record save?

**Comment by rrd108** [comment]
@markstory I do not know why and I do not have time now to dig in more.

This one do not saves

    ['title' => 'Post title', 'post' => 'Post body', 'tags' => '']

And this one saves

    ['title' => 'Post title', 'post' => 'Post body', 'tags' => []]

**Comment by markstory** [comment]
Empty array/empty string working differently makes sense as one is valid for a belongsToMany, and one is not. I can see what is going on.

**Comment by markstory** [comment]
Fixed with #6857
