### ISSUE TITLE
404 when tmp/cache/views not found

### ISSUE THREAD

**Issue by jsenin** [cakephp/cakephp#6820]
Hi

I just found a strange 404 response at one of my proyects, all pages are being processing properly but status code is 404.
After some traces and checkings I created by hand missing tmp/cache/views dir and sudenly stops to return 404 to 200 status code.

my cackephp version i v2.6.7 

I hope this would helpfull for someone !

P.d. Occurs when debug = 0 at core.php and Cache.check =  true

**Comment by markstory** [comment]
I think that is expected, but I will double check.

**Comment by markstory** [comment]
I wasn't actually able to reproduce the error. Whether the directory existed or not, I always got a 200 status code. I checked with a freshly baked application skeleton on a list page. Is there something else I should be trying?

**Comment by jsenin** [comment]
Hi Mark


I'll try to build a demo where you could test it . Is there any service
like runnable.com or similar for testing propurses ?

thanks


2015-06-17 5:49 GMT+02:00 Mark Story <notifications@github.com>:

**Comment by markstory** [comment]
I don't understand why something like runnable.com would be needed. If you have a gist of the files you changed, or even a demo app repo I can checkout that would would work.
