### ISSUE TITLE
Debugger is setting properties as accessible without rolling back the change

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#6822]
For example, it makes the timezone property of a DateTime accessible after debugging:

```php
$date = new DateTime;
debug($date);
echo $date->timezone; // !!!!
```

**Comment by lorenzo** [comment]
This is a bug in 2.x as well

**Comment by markstory** [comment]
Neato, i guess after dumping a property we should restore the accessible state of a property.
