### ISSUE TITLE
3.0.7 - Update does not honor 'quoteIdentifiers' setting

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#6825]
I have "values" table in my db. As `values` is a reserved word, I've set `quoteIdentifiers` to true in my db config.

Trying to update records in a "values" table (using baked `Values` ORM Table) produces similar query:
```sql
UPDATE values SET `modified` = :c0 WHERE `id` = :c1
```

Select, insert and delete seem to work correctly.

**Comment by lorenzo** [comment]
I'm happy identifier quoting is not a feature that is enabled by default :P

**Comment by HavokInspiration** [comment]
Maybe we could make the database test suite more robust by having the third param (that defines if the quotation around identifiers is optional or not in the regex check) of ``assertQuotedQuery`` depend on whether the ``quoteIdentifiers`` is set to ``true`` or not.

Right now, in ``Database\QueryTest``, all checks with ``assertQuotedQuery`` pass the third param at true. If you pass [https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Database/QueryTest.php#L2189](this test), set the third param to ``false`` and run the test suite, the test will fail and prove this PR.

So if  ``quoteIdentifiers`` is set to ``true``, quoting should be mandatory in the tests.

**Comment by lorenzo** [comment]
I think that is a good idea @HavokInspiration, want to take on this task?

**Comment by HavokInspiration** [comment]
Already working on it :)

**Comment by markstory** [comment]
Closing as #6828 is open now.
