### ISSUE TITLE
3.x - patchEntity and translation

### ISSUE THREAD

**Issue by aleixfabra** [cakephp/cakephp#6826]
I have a similar problem like @darxmac #5044 had, but patching the entity like this:

```php
<?php

$data = [
    'title' => 'new page'
    'tags'  => [
        ['id' => 1]
        ['id' => 2]
    ]
];
```

and both the main model and `Tags` are translated, and i set the app state to a given locale with I18n::local('spa'). 

`Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous`

Is it fixed?

**Comment by lorenzo** [comment]
@aleixfabra What version of cakephp are you running?

**Comment by aleixfabra** [comment]
3.0.7

**Comment by lorenzo** [comment]
Ok, what is the code that triggers this error?

**Comment by aleixfabra** [comment]
```php
public function edit($id = null)
{
    $page = $this->Pages->get($id);
    if ($this->request->is(['patch', 'post', 'put'])) {

        /* where
        $this->request->data['tags'] = [
            ['id' => 1]
            ['id' => 2]
        ]
        */

        $page = $this->Pages->patchEntity($page, $this->request->data);

        if ($this->Pages->save($page)) {
            $this->Flash->success(__('The page has been saved.'));
            return $this->redirect(['action' => 'index']);
        } else {
            $this->Flash->error(__('The page could not be saved. Please, try again.'));
        }
    }
    $this->set(compact('page'));
    $this->set('_serialize', ['page']);
    $this->render('add');
}
```

Where `Pages` and `Tags` have `Translate` Behavior (both).

**Comment by lorenzo** [comment]
Could you also please include the SQL log for that request?

**Comment by aleixfabra** [comment]
SELECT Tags.id AS `Tags__id`, Tags.name AS `Tags__name`, Tags.slug AS `Tags__slug`, Tags.created AS `Tags__created`, Tags.modified AS `Tags__modified`, Tags_name_translation.id AS `Tags_name_translation__id`, Tags_name_translation.locale AS `Tags_name_translation__locale`, Tags_name_translation.model AS `Tags_name_translation__model`, Tags_name_translation.foreign_key AS `Tags_name_translation__foreign_key`, Tags_name_translation.field AS `Tags_name_translation__field`, Tags_name_translation.content AS `Tags_name_translation__content`, Tags_slug_translation.id AS `Tags_slug_translation__id`, Tags_slug_translation.locale AS `Tags_slug_translation__locale`, Tags_slug_translation.model AS `Tags_slug_translation__model`, Tags_slug_translation.foreign_key AS `Tags_slug_translation__foreign_key`, Tags_slug_translation.field AS `Tags_slug_translation__field`, Tags_slug_translation.content AS `Tags_slug_translation__content` FROM tags Tags LEFT JOIN i18n Tags_name_translation ON (Tags_name_translation.model = :c0 AND Tags_name_translation.field = :c1 AND Tags_name_translation.locale = :c2 AND Tags.id = (Tags_name_translation.foreign_key)) LEFT JOIN i18n Tags_slug_translation ON (Tags_slug_translation.model = :c3 AND Tags_slug_translation.field = :c4 AND Tags_slug_translation.locale = :c5 AND Tags.id = (Tags_slug_translation.foreign_key)) WHERE (id = :c6 OR id = :c7)

**Comment by lorenzo** [comment]
Thanks, that should be enough info to fix the issue :)

**Comment by aleixfabra** [comment]
:+1:

**Comment by markstory** [comment]
Closing as #6867 is open now.
