### ISSUE TITLE
CAKE 3.X Database driver Cake\Database\Driver\Sqlserver cannot be used due to a missing PHP extension or unmet dependency

### ISSUE THREAD

**Issue by edvano** [cakephp/cakephp#6829]
* Microsoft SQL driver installed php_pdo_sqlsrv_55_ts.dll
* Php.ini extension=php_pdo_sqlsrv_55_ts.dll enable

Still have the error message
Database driver Cake\Database\Driver\Sqlserver cannot be used due to a missing PHP extension or unmet dependency
Cake\Database\Exception\MissingExtensionException
Can anyone help me out on this

**Comment by dakota** [comment]
Ensure the extension is loaded by checking the output of `phpinfo`. Chances are that you are running the `NTS` version of PHP, or you are using PHP 5.6.

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by edvano** [comment]
A use a wampserver on windows 7 and indeed the extension is not loaded even if
the driver is installed in  C:\wamp\bin\php\php5.5.12\ext and the extension is enabled in the php.ini file

**Comment by edvano** [comment]
Thanks figured it out.

**Comment by mdunham** [comment]
how'd you solve it because I'm trying to use Sqlserver on centos 6 with php 5.6 with all pdo and mssql extensions installed and still saying now installed. I tried switching php version all the same issue.

**Comment by lorenzo** [comment]
You need this extension installed https://github.com/Microsoft/msphpsql/blob/master/README.md

**Comment by atekelt** [comment]
> Thanks figured it out.

how? need help tried everything, by the way using xammp on windows 10.
