### ISSUE TITLE
3.0.7 - TranslateTrait and empty translations' entities

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#6833]
Seems like `TranslateTrait` sets an empty `Cake\ORM\Entity` instance when translation is not found. But found translations are instances of an entity class defined in a source table.

This may be an issue while trying to fill empty translations for more complex entities. I'm aware that it may be difficult to make a trait be aware of entity's class or source table default entity class but maybe something will come up...

**Comment by markstory** [comment]
Pull request up now.
