### ISSUE TITLE
3.x _ids syntax and belongsToMany associations

### ISSUE THREAD

**Issue by pulse14** [cakephp/cakephp#6835]
I have a security issue. I link belongsToMany data with the _ids syntax. 

I saw in the markstory issue #2510 the _ids syntax has been created to only request the entities before linking them.

**The problem is**: nothing tell cake that the _ids syntax must be used to marshall. Anyone can replace/tamper _ids with an array and cake will create entities.
I think this must be handled by entities creation/patching and and not by us.

We can add a parameter in 'associated' to force cake using only '_ids' ? What do you think about that ?

Thank you

**Comment by markstory** [comment]
If you have a security issue, we kindly request that you [follow our security issue process](http://book.cakephp.org/2.0/en/contributing/tickets.html#reporting-security-issues).

What makes this a security issue? There are a number of ways to prevent any abuse of `_ids`:

* Validation/Application rules can make sure that only permitted records are linked.
* SecurityComponent will prevent form tampering.

How would you see belongsToMany association marshalling working when `_ids` was disabled?

**Comment by pulse14** [comment]
The idea is not to disable _ids but to add an option in 'associated' to force cake to use only _ids and ignore if there is something else.

I don't think this should be Validation/Application rules for the same reason we don't do that for fieldList.
SecurityComponent to prevent form tampering can't always be used.

It's not really a security issue because it's how marshaller works. However I think it's not really 'security oriented', I regularly see code without protection for this.

**Comment by lorenzo** [comment]
What would you propose to enhance the security aspect of this feature?

**Comment by pulse14** [comment]
Hi,
Example here :
pulse14@7361974529d26d9d9f18bcb6140467ba3d6b5927

**Comment by markstory** [comment]
That could work. Do you also think that hasMany associations should behave like this? That association type also supports `_ids`. Having consistency between the various association types is one reason they code behaves the way it does.

**Comment by pulse14** [comment]
Yes, it must work everywhere _ids is used and data can easily injected. It's a very simple feature but so usefull. 
Another which handle marshall/merge and belongsToMany/hasMany :

https://github.com/cakephp/cakephp/compare/master...pulse14:issue-6835

**Comment by lorenzo** [comment]
@pulse14 Can you submit that as a pull request?

**Comment by pulse14** [comment]
Ok,
I'm not sure if all is ok. And I'm not very good at writing tests, so there is no tests in the commit.

**Comment by antograssiot** [comment]
closing as

**Comment by antograssiot** [comment]
closing as #6846 is open now
