### ISSUE TITLE
Flash loading -> error at Undefined variable: _SESSION [CORE/src/Network/Session.php, line 440]

### ISSUE THREAD

**Issue by peswanibros** [cakephp/cakephp#6838]
Hi I've facing this problem from 2 days and I don't know how to solve it. I am using cakephp 3.0

http://stackoverflow.com/questions/30896248/cakephp-flash-error-at-undefined-variable-session-core-src-network-session-ph

**Comment by markstory** [comment]
Make sure that sessions are functioning on your server/environment. Unfortunately this is not an issue with CakePHP, but something with your server environment. I would check to make sure there is no trailing/leading whitespace in any of your PHP files as that can cause headers to be sent early making sessions not work. Also try building a very simple php script that uses the session functions and make sure that works.
