### ISSUE TITLE
Error after placing files on server.

### ISSUE THREAD

**Issue by nitiniyer** [cakephp/cakephp#6839]
I have downloaded the latest cakephp-3-0-7.zip and have uploaded the files to my server. I can confirm that the PHP version is above 5.4.16, MBString is enabled, intl is enabled. Permissions are set properly to log and tmp folders. But when I try to access the website, I get the following error:  Call to undefined method Cake\Datasource\ConnectionManager::_config() in /home/xxxxxx/public_html/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php on line 80

Call to undefined method Cake\View\StringTemplate::get() in /home/xxxxxx/public_html/vendor/cakephp/cakephp/src/View/StringTemplate.php on line 154

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
