### ISSUE TITLE
3.0: Allow deep options for radio() just as for select()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6841]
I just put it here so we don't forget
https://github.com/cakephp/cakephp/pull/6821 needs a 3.x port.

We should also add a doc snippet then for both versions.

**Comment by markstory** [comment]
Looks like [past me already thought of this](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/View/Widget/RadioWidgetTest.php#L160-L194).
