### ISSUE TITLE
PDO PostgreSQL databse driver error on OS X

### ISSUE THREAD

**Issue by jnemecz** [cakephp/cakephp#6842]
I'm experiencing this issue:

`Warning (2): PDO::__construct(): SQLSTATE[IM001]: Driver does not support this function: driver does not support setting attributes [CORE/src/Database/Driver/PDODriverTrait.php, line 48]`

My configuration:

- OS X Yosemite
- PHP Version 5.5.20
- CakePHP 3.0.7
- PostgreSQL(libpq) Version	9.4.1, Module version	1.0.2, Revision	$Id: pdo_pgsql.c,v 1.7.2.11 2006/03/14 10:49:18 edink Exp $

What am I doing wrong?

**Comment by lorenzo** [comment]
Duplicate of https://github.com/cakephp/cakephp/issues/3642
