### ISSUE TITLE
3.x PaginatorComponent defect

### ISSUE THREAD

**Issue by Adnan0703** [cakephp/cakephp#6843]
If this is sortWhitelist: `sortWhitelist => []`,
and this is the url: `/controller/action?sort=field`.
The PaginatorComponent will sort by that field, ignoring that we don't want to allow sorting any field.

Instead of empty sortWhitelist, if the sortWhitelist isn't empty like this: `sortWhitelist => ['even_invalid_field']`,
then the sortWhitelist gets used by the PaginatorComponent.

```
    public function validateSort(Table $object, array $options)
    {
        ...
        if (!empty($options['sortWhitelist'])) {
            $field = key($options['order']);
            $inWhitelist = in_array($field, $options['sortWhitelist'], true);
            if (!$inWhitelist) {
                $options['order'] = [];
                return $options;
            }
            $validate = false;
        }
		...
    }
```
It doesn't care about empty sortWhitelist.

**Comment by dereuromark** [comment]
Neverending story, that sortWihtelist :)

I agree that an empty list should probably not allow any sorting.
That means, though, that we need to set it to `false` if we don't wont whitelisting, and that could break existing apps. Maybe we should do that fix in 3.1 then?

**Comment by Adnan0703** [comment]
@dereuromark , that means lots of apps has to allow sorting of at least one indexed field or has to use that "imaginary_field" hack.

**Comment by dereuromark** [comment]
Why do you think that? Not passing in any whitelist will just make it work as it used to.

**Comment by Adnan0703** [comment]
You just fixed that. I posted before looking at your commit.

**Comment by dereuromark** [comment]
Closing as PR is open.
