### ISSUE TITLE
3.x - Table and BehaviorRegistry dependencies

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#6845]
Currently the `Table` constructor allows to inject `BehaviorRegistry` instance. But `BehaviorRegistry` itself depends on a table, so there's no way to prepare behaviors prior to table creation. Thus there's no other way to swap `BehaviorRegistry` implementation. Even if there existed a setter for behaviors, there would be no point swapping it on runtime, as behaviors are usually added in `initialize()` during construction of an object.

I'm wondering how to design it better. Maybe if there was some factory for table dependencies which could be reimplemented...

Or maybe I am missing something?

**Comment by lorenzo** [comment]
Or maybe it does not make set at all to inject the behaviors registry? An option could be to remove the constructor from the registry and add a `setTable()` method

**Comment by robertpustulka** [comment]
So Table constructor could look something like that?
```php
        $this->_behaviors = $behaviors ?: new BehaviorRegistry();
        ...
        $this->_behaviors->setTable($this);

        $this->initialize($config);
```

That could do the trick...

**Comment by markstory** [comment]
I included the parameter originally so people could use mocks if they wanted. Adding a `setTable()` seems reasonable to me.

**Comment by robertpustulka** [comment]
PR is open
