### ISSUE TITLE
How to run the cake back in cakephp 3.x 

### ISSUE THREAD

**Issue by cismanish** [cakephp/cakephp#6851]
Hello

when i run cakebake

By using `cake bake [name]` you can invoke a specific bake task.
root@CISM290:/opt/lampp/htdocs/cakephp3demo# cake bake model
PHP Warning:  include(/opt/lampp/htdocs/cakephp3demo/config/core.php): failed to open stream: No such file or directory in /usr/share/php/cake/libs/configure.php on line 400

Warning: include(/opt/lampp/htdocs/cakephp3demo/config/core.php): failed to open stream: No such file or directory in /usr/share/php/cake/libs/configure.php on line 400
PHP Warning:  include(): Failed opening '/opt/lampp/htdocs/cakephp3demo/config/core.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/php/cake/libs/configure.php on line 400

Warning: include(): Failed opening '/opt/lampp/htdocs/cakephp3demo/config/core.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/php/cake/libs/configure.php on line 400
PHP Fatal error:  Can't find application core file. Please create /opt/lampp/htdocs/cakephp3demo/config/core.php, and make sure it is readable by PHP. in /usr/share/php/cake/libs/configure.php on line 401

Fatal error: Can't find application core file. Please create /opt/lampp/htdocs/cakephp3demo/config/core.php, and make sure it is readable by PHP. in /usr/share/php/cake/libs/configure.php on line 401
root@CISM290:/opt/lampp/htdocs/cakephp3demo# cake bake model
PHP Warning:  Cache not configured properly. Please check Cache::config(); in APP/config/core.php in /usr/share/php/cake/libs/configure.php on line 408

because in cakephp 3.x don't have config/core.php

Thanks
Manish

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
