### ISSUE TITLE
Save associations foreign_key

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#6852]
As described in the docs you can save `hasMany`, `hasOne` or what else like the following `hasOne` example:

Model/Entity/Post.php
```
protected $_accessible = [
    'tag' => true
];
```

Model/Table/Posts.php
```
$this->hasOne('Tags', [
    'className' => 'Tags'
]);
```

Template/Posts/add.ctp
```
$this->Form->input('tag.name', [
    'type' => 'hidden',
    'value' => 'test'
]);
```

Controller/PostsController.php
```
$post = $this->Posts->newEntity();
...
$post = $this->Posts->patchEntity($post, $this->request->data);
...
$this->Posts->save($post);
```

The example shown above does not make sense it's only to clarify things. As long as the `tags` table has a field `post_id` all works fine. Imagine your tags table has the fields `model` and `foreign_key`, you need to change your association configuration to:

Model/Table/Posts.php
```
$this->hasOne('Tags', [
    'className' => 'Tags',
    'foreign_key' => 'foreign_key'
    'conditions' => [
        'Tags.model' => 'Posts'
    ]
]);
```

This way you can save tags from different models in the same table. The problem that now occurres is that the `foreign_key` isn't filled automatically with a save operation.

EDIT:
Same occurrs if you straggle from the conventions. For example you want to name your `foreign_key` as `my_foreign_key` instead of `post_id` for whatever reasons.

**Comment by markstory** [comment]
So what is the issue here? Does `$post->tag` not get set? Or that the tag that does get set is incorrect? The marshaller doesn't use the conventional names but uses the association objects to get key information. Do you have some schema snippets that would help someone reproduce the issue you're having locally?

**Comment by steefaan** [comment]
It's independent from the schema but I have the following tag table (only an example):

```
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 10, 'unsigned' => true, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
        'post_id' => ['type' => 'integer', 'length' => 10, 'unsigned' => true, 'null' => true, 'default' => null, 'comment' => '', 'precision' => null, 'autoIncrement' => null],
        'name' => ['type' => 'string', 'length' => 255, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
        ],
        '_options' => [
            'engine' => 'InnoDB',
            'collation' => 'utf8_unicode_ci'
        ],
    ];
```

As long as I name the field `post_id` all works fine but if I want to change it to `foreign_key` and  also change my association configuration to `'foreign_key' => 'foreign_key` the field isn't filled automatically when I do an association save like:

```
$data = [
    'title' => 'the title',
    'content' => 'the content',
    'tag' => [
        'name' => 'test tag'
    ]
];
``` 

It's a `hasOne` in this case, as I said above it's not the best idea to have a `hasOne` association for tags but this is only for demo reasons.

**Comment by markstory** [comment]
Thanks for the schema, I'll try to reproduce this locally.

**Comment by markstory** [comment]
In your configuration, you mentioned you used the config option `foreign_key`. Was that a typo? As the actual configuration key should be `foreignKey` with no underscore.

**Comment by steefaan** [comment]
Yes you're right, it was a typo but I overlooked it completly. Sorry for that and thanks for your help.
