### ISSUE TITLE
3.x - Entity Accessors called on save() and various Table methods

### ISSUE THREAD

**Issue by Grafikart** [cakephp/cakephp#6856]
I'm not sure this is an issue but this behaviour seems a bit strange to me for the `Entity`

## Problem

The getters _getXXX are called when saving an entity. For instance I want to get the price I would do something like that

```php
class Entity{

    public function _getPrice($price){
        return number_format($price, 2, ',', ' ') . " €";
    }

    public function _setPrice($price){
        return floatval(str_replace(',', '.', $price)); 
    }

}
```

If I do `$entity->price = 2000` for instance I expect the setter to be used, but not the getter when I do `Table->save($entity)`. 

## Solution 

I know my example is not the best (a `getFormattedPrice()` method would do the job) but in my opinion this behaviour is a bit odd. 
The save process should get the attribute without calling the accessor. The solution would be to change the signature of the get method : `get($key, $with_accessor = true)` in `Cake\Datasource\EntityTrait` and set this new parameter to false when data are saved (basically when `extract()` is called)

## Caveat

This change could break a lots of thing if people take advantage of this behaviour. We could put a configuration key to enable or disable this feature.
Another idea would be to create a trait, that people could load if needed.

I can do a PR, but I want to be sure this feature is interesting before working on it ^^

**Comment by Grafikart** [comment]
If someone wants this behaviour without having to change the core you can create an entity class that would be inherited by all yours entities and change these 2 methods :  

```php

    public function extract(array $properties, $onlyDirty = false)
    {
        $result = [];
        foreach ($properties as $property) {
            if (!$onlyDirty || $this->dirty($property)) {
                $result[$property] = $this->get($property, false);
            }
        }
        return $result;
    }

    public function &get($property, $getter = true)
    {
        if (!strlen((string)$property)) {
            throw new InvalidArgumentException('Cannot get an empty property');
        }

        $value = null;
        $method = '_get' . Inflector::camelize($property);

        if (isset($this->_properties[$property])) {
            $value =& $this->_properties[$property];
        }

        if ($getter && $this->_methodExists($method)) {
            $result = $this->{$method}($value);
            return $result;
        }
        return $value;
    }
```

**Comment by lorenzo** [comment]
Yes this is by design. The idea is that you use getters for returning value objects instead of formatted values. You can of course have getters such as `getFormattedPrice`

**Comment by markstory** [comment]
I've always thought of the point of accessor methods, was to provide uniform access to properties from outside the object. Given that the Table is outside of the Entity, not using accessors seems strange to me.

Changing things now is going to be tricky like you said as there are probably people relying on the current behavior.

The issues around formatting have come up before, and there has been some discussion around [adding presenters](https://github.com/cakephp/cakephp/issues/6698) to help keep the formatting logic out of entities, but that work is not complete yet.

**Comment by dereuromark** [comment]
I think using the setters and getters this way is currently not a good idea.
You limit yourself unnecessarily and introduce wacky behavior.
E.g. output always as `number_format($price, 2, ',', ' ')`. What if you want to work with the data in the normal PHP way and don't plan on outputting it? That would break.
IMO you shouldn't be putting localization and output formatting in the model layer, but leave that to the presentation layer. So adding a presenter in 3.1+ would be sure a nice thing, but until then it would be wiser to just use the view layer or helpers to format data.

**Comment by Grafikart** [comment]
I was just surprised by this behaviour (maybe it's cause of rails) maybe we could add some mention on the documentation "Accessors are also used when data are persisted"

Ok indeed the presentation layer seems a much better way to handle this use case. ^^

**Comment by markstory** [comment]
@Grafikart Where would you expect to find that mention in the docs?

**Comment by Grafikart** [comment]
I would add this mention here http://book.cakephp.org/3.0/en/orm/entities.html#accessors-mutators at the end of the paragraph about the getter

The getter showed in the documentation is doing an ucwords($title), that's why I thought accessors weren't used when entities are persisted. Indeed if the accessor is used while persisting data we could put the logic explained in the doc inside a mutator. 

Another problem I encountered was trying to do something like this, converting data

```php
public function _getInfo($info){
    if(is_string($info)){
        return json_decode($info); 
    }
    return $info; 
}

public function _setinfo($info){
    if(is_array($info)){
        return json_encode($info);
    }  
    return $info;   
}
```

So I would also add a link to http://book.cakephp.org/3.0/en/orm/entities.html#storing-complex-types (in fact we could use the same phrasing).

> Accessors and Mutators are not intended to contain the logic for serializing and unserializing complex data. Refer to the Saving Complex Types section to understand how your application can store more complex data types like arrays and objects.

**Comment by markstory** [comment]
Thanks @Grafikart I'll update the docs.

**Comment by markstory** [comment]
Docs updated now.
