### ISSUE TITLE
3.x Cannot hide pagination query params from the url

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#6859]
**Scenario**
News index page paginated and sorted by `publish_date DESC`. 

```php
        $articles = $this->Paginator->paginate($this->Articles, [
            'conditions' => [
                'status_id' => 1,
                'article_type_id' => $type->get('id')
            ],
            'order' => ['publish_date' => 'DESC'],
            'limit' => 10
        ]);
```

In my template I use the PaginatorHelper to generate my pagination links. However the sorting is being passed in the url, which would allow someone to find out all the fields in my database table by just trying different fields in the `sort` param.

**The issue**
The paginator helper is generating links such as `/news?page=3&sort=Articles.publish_date&direction=desc`, so an attacker could try and sort by `Articles.id` to order the records by id, and if assuming you were using `autoincrement` then you'd be easily able to guess the `id` of the articles. I don't feel comfortable exposing the database schema in this manner.

**Whitelisting**
Perhaps there needs to be some control over which params are 'enabled' or similar in the Paginator. In the component you can use the `validateSort` method, but it always merges with the default options, which means that `['limit', 'sort', 'page', 'direction']` are always available.

**Comment by ADmad** [comment]
You can use [sortWhiteList](http://api.cakephp.org/3.0/class-Cake.Controller.Component.PaginatorComponent.html#_paginate).

**Comment by davidyell** [comment]
Urgh geez, how did I miss that! Thanks @ADmad.

**Comment by AD7six** [comment]
That said, if the sort order is the - the params don't need to be, and shouldn't be, in the url.

**Comment by dereuromark** [comment]
@davidyell Especially with like 5 tickets and tons of PRs around that sortWhitelist opion the last weeks :P It was probably the most actively touched code piece these days. Hopefully it now covers all use cases.

**Comment by davidyell** [comment]
It was entirely my own fault, I was busy reading the source code and getting caught up in the multiple different ways to configure the component. I didn't even think to check the book, in which it's spelt out!

"More haste, less speed."

**Comment by dereuromark** [comment]
I have to agree that you can easily trip over this, though.

    'order' => ['publish_date' => 'DESC']

vs

    'order' => ['Articles.publish_date' => 'DESC']

Only the latter works as expected by default.
Both sort just fine, but the first requires the sortWhiteList() config on top to make the default ordering disappear on the generated links.
