### ISSUE TITLE
Flash component - return breaks flash message

### ISSUE THREAD

**Issue by isaacaskew** [cakephp/cakephp#6861]
For some of my code I've been going back through and making it strictly PSR-2 compliant. This requires that the lines never be more than 120 characters, so long Flash errors like the one below has to be changed to have a 'return' space in them.

    $this->Flash->error(__('We are sorry. We could not find any account associated with your email 

    provided. Please check that your email has been typed correctly.'));

I've tested it with and without this enter and it seems to work if no enter is in the message and breaks if an enter is present.

**Comment by dereuromark** [comment]
That is invalid PHP, nothing to do with the Flash component or CakePHP in general I would say.

**Comment by isaacaskew** [comment]
Using returns in any other fashion works fine. 

<?php
    echo 'this is a simulation of a
    very long message';
?>

displays: 'this is a simulation of a very long message'

So is the preferred method to make a variable with the message inside it, then place it inside the Flash message?

**Comment by dereuromark** [comment]
I think the i18n `__()` cannot work with multiline translation strings. You should instead use "\n" inside of them to make new lines.

**Comment by isaacaskew** [comment]
Will do, thanks.

**Comment by isaacaskew** [comment]
I'm not trying to make new lines, I'm trying to get the break the code into multiple lines so it doesn't go over the 120 character limit for a line.

**Comment by dereuromark** [comment]
In general, you can also concatenate strings: `"one " . "sentence" . ...` but not sure about how i18n extract likes this.

**Comment by isaacaskew** [comment]
Looks a little goofy, but that works! I'll just do it that way from now on.
