### ISSUE TITLE
Clarification on Unique rule behaviour

### ISSUE THREAD

**Issue by caBBAlainB** [cakephp/cakephp#6865]
Hello,
I got a problem while updating an entity where I defined a unique rule on the field 'company'.
I was in fact updating 'email' field and patchEntity told me that company was existing already!
Of course, it was itself!
So jose told me to add 'on' => 'create' to the rule.
First I was satisfied by the answer and I had the intention to propose to update the doc but something disturbs me now: With 'on'=> 'create' behaviour what will prevent to modify the 'company' field and set it the a really existing other company?

**Comment by ADmad** [comment]
Adding `'on' => 'delete'` shouldn't be necessary. The rule check if it's [not a new record](https://github.com/cakephp/cakephp/blob/master/src/ORM/Rule/IsUnique.php#L58) and adds required condition to not consider record with particular primary key. 

If you are not getting this behavior provide some example code to reproduce your issue.

**Comment by caBBAlainB** [comment]
I try to check if I'm in a particular case but strangely, 'on' => 'create' solved my problem.

**Comment by caBBAlainB** [comment]
I'm sorry but the situation is still not very clear.
Here is my patchEntity() debug

[
    'site_name' => '...',
    'datas' => object(App\Model\Entity\User) {

       'id' => (int) 653,
        **'owner_id' => (int) 611,**
        'extraemails' => [
        ],
        'owner' => object(App\Model\Entity\Owner) {

           ** 'id' => (int) 611,**
            'company' => 'This is the Company name',
            'created' => object(Cake\I18n\Time) {

                'time' => '2015-06-06T18:07:17+0000',
                'timezone' => 'UTC',
                'fixedNowTime' => false

            },
            'modified' => object(Cake\I18n\Time) {

                'time' => '2015-06-17T02:44:36+0000',
                'timezone' => 'UTC',
                'fixedNowTime' => false

            },
           ** '[new]' => false,**
            '[accessible]' => [
                'email' => true,
                'phone' => true,
                'phone2' => true,
                'fax' => true,
                'company' => true,
                'tva_number' => true,
                'address' => true,
                'postcode' => true,
                'city' => true,
                'country_id' => true,
                'users' => true,
                'username' => true,
                'origin' => true
            ],
            '[dirty]' => [
                'email' => true,
                'phone' => true,
                'postcode' => true,
                'city' => true
            ],
            '[original]' => [
                'email' => '...',
                'phone' => '...',
                'postcode' => '...',
                'city' => '...'
            ],
            '[virtual]' => [],
            '[errors]' => [
                **'company' => [**
                   **'unique' => 'This company name exists already.'**
                ]
            ],
            '[repository]' => 'Owners'

        },
....

So it seems that conditions are here not met to fire the 'unique' rule.
I don't understand why I get it.

**Comment by lorenzo** [comment]
What is the code you are using to save?

**Comment by caBBAlainB** [comment]
In fact I don't get it on save but on patchEntity():
    $user = $this->Users->patchEntity($site->users[0], [

        'email' => $this->siteDatas['userEmail'],
        'phone' => $this->siteDatas['ownerPhone'],
        'role' => 'owner',
        'active' => 1,
        'extraemails' => $this->siteDatas['extraemails'],
        'owner' => [
            'company' => $this->siteDatas['ownerName'],
            'email' => $this->siteDatas['ownerEmail'],
            'phone' => $this->siteDatas['ownerPhone'],
            'address' => $this->siteDatas['ownerAddress'],
            'postcode' => $this->siteDatas['ownerPostcode'],
            'city' => $this->siteDatas['ownerCity'],
            'country_id' => $this->siteDatas['countryId'],
            'web' => $this->siteDatas['ownerWeb'],
        ],
    ],
    [
        'validate' => 'import',
        'associated' => [
            'Extraemails',
            'Owners' => [
                'validate' => 'import'
            ]
        ]
    ]);

    if ($user->errors()) {

        // Here is where I get the 'unique' error
    }

And the validator is:

    public function validationImport(Validator $validator) {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create')
            ->notEmpty('company')
            ->add('company', 'unique', ['rule' => 'validateUnique', 'provider' => 'table', 'message' => __("This company exists already.")])

            ...

                ])
            ;

        return $validator;
    }

**Comment by dakota** [comment]
I think you should rather use ApplicationRules for unique validation, http://book.cakephp.org/3.0/en/orm/validation.html#creating-unique-field-rules

**Comment by caBBAlainB** [comment]
well, well, you may be right!

**Comment by markstory** [comment]
Closing again, as the isUnique validation rule isn't smart enough to handle create/update scenarios. The application rule however is.

**Comment by caBBAlainB** [comment]
Sorry, just to end, should http://book.cakephp.org/3.0/en/core-libraries/validation.html#unique-fields disappear from the doc?

**Comment by ADmad** [comment]
@caBBAlainB It should. Can you make a PR removing that section.

**Comment by caBBAlainB** [comment]
ok Admad, thanks
