### ISSUE TITLE
3.0 Check character in default page (Question)

### ISSUE THREAD

**Issue by dsandi** [cakephp/cakephp#6868]
I have an issue with a character.

When I see the default page in my local server I see this:

.home .checks .success:before {
  content: "✓";
  color: green;
  margin-right: 9px;
}
![screen shot 2015-06-23 at 3 13 04 pm](https://cloud.githubusercontent.com/assets/3586450/8317392/689dd37a-19ba-11e5-8490-4a2a6e936e75.png)

But in my server hosted in amazon to test I see this:

.home .checks .success:before {
  content: "âœ“";
  color: green;
  margin-right: 9px;
}

![screen shot 2015-06-23 at 3 14 35 pm](https://cloud.githubusercontent.com/assets/3586450/8317410/91f24120-19ba-11e5-946b-cc278d947ad8.png)

Maybe it could be something related to the files under /tmp/cache/persistent?

How can I fix this issue without having to edit the css file manually, and making sure it is not a major issue that will affect my project late?

Thank you

**Comment by markstory** [comment]
Looks like an encoding issue. Make sure that all the encodings are in utf8 and that when you deploy you are not accidentally mangling into latin-1.

Closing as this is not an issue with CakePHP, but an issue with the environments you are using.
