### ISSUE TITLE
Validation rule boolean

### ISSUE THREAD

**Issue by mo-ba** [cakephp/cakephp#6869]
I just had some problems with form validation

in Cake\Validation:
there is this method to validate booleans (line 450)

public static function boolean($check)
    {
        $booleanList = [0, 1, '0', '1', true, false];
        return in_array($check, $booleanList, true);
    }

$booleanList = [0, 1, '0', '1', true, false, "true", "false"];
works fine for me, but I'm not sure if its a good idea to allow strings of booleans

**Comment by markstory** [comment]
Ok, but both 'true' and 'false' are actually truthy in PHP. That might cause some additional confusion too.

**Comment by ADmad** [comment]
:-1:  If one needs to check strings 'true', 'false' they can do so using custom rule.

**Comment by mo-ba** [comment]
@markstory i understand your concerns with truthy strings ('0' and '' are the only strings which evaluate false in php), but cakephp also accepts 'false' as false (in most cases)

best example is class Type in Cake\Database
> Encapsulates all conversion functions for values coming from database into PHP and
> going from PHP into database.
 
and the mighty function:

> Type converter for boolean values.
> Will convert string true/false into booleans.
> @param mixed $value The value to convert to a boolean.
> @return bool

    public static function boolval($value)
    {
        if (is_string($value) && !is_numeric($value)) {
            return strtolower($value) === 'true' ? true : false;
        }
        return !empty($value);
    }


so there is maybe some inconsistency?

@ADmad I tried the custom rule approach, but then I realized that for cakephp 'false' IS false (at least for database values)

**Comment by ADmad** [comment]
I wasn't aware of `Type` class' handing of string true and false.

**Comment by markstory** [comment]
The string handling is because of Postgres from what I remember.

**Comment by mo-ba** [comment]
am I supposed to make a pull request? what's your decision in this case? is 'false' false for cake? I used the modification the last view month, had no issues with it, cant tell if there are any side-effects. Some people might rely on 'false'==true, in my opinion its dirty coding style to rely on that.

**Comment by dereuromark** [comment]
I don't think it's a good idea.

**Comment by jhli** [comment]
In case there is a PR it should be a wrapper around filter var and should behave exaclty like that (even be mentioned in the docs); even the flag support @ null should go in http://stackoverflow.com/questions/4775294/parsing-a-string-into-a-boolean-value-in-php/10645030#10645030

**Comment by markstory** [comment]
Having this method accept 'on' and 'yes' would not be good. Using `filter_var()` is probably not going to work.

**Comment by thinkingmedia** [comment]
Isn't this something that could be resolved using a mutator on the Entity, and what if we had a way to make mutators reusable?

**Comment by dereuromark** [comment]
Besides https://github.com/cakephp/cakephp/blob/master/src/Validation/Validation.php#L529 there will now be truthy() and falsey() with https://github.com/cakephp/cakephp/pull/9563
They both support a custom values array.
The same comes for boolean() - with `array $booleanValues = []` you can customize.

I think this can be closed.
