### ISSUE TITLE
2.7.0-RC Auth doesn't use the new Flash component

### ISSUE THREAD

**Issue by Highstrike** [cakephp/cakephp#6874]
I've recently upgraded from 2.6.x to 2.7.0 RC and I'm trying to fix all of the deprecated code in my project but I have an issue.

Currently, [the Auth component is still using Session->setFlash instead of Flash->set](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Controller/Component/AuthComponent.php#L843)

I've replaced `echo $this->Session->flash('auth');` to `echo  $this->Flash->render('auth');` in my layout file but auth error messages no longer appear.

`Session->setFlash` stores the message into `Message.{$key}`
The new Flash component stores the message into `Flash.{$key}`

`$this->Flash->render('auth')` tries to read the message from `Flash.auth` but the message is actually stored in `Message.auth` instead.

I don't know how to fix this for people that rely on the deprecated functions. Obviously replacing [this  line](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Controller/Component/AuthComponent.php#L843) in the Auth component will break existing functionality with `Session->setFlash` and vice-versa.

**Comment by dereuromark** [comment]
Are you able to make a PR with the suggested changes?
I think we could keep the flash key "Message" instead of "Flash". This way it would be more BC.

**Comment by Highstrike** [comment]
ok, I'm going to do a PR with the key Message instead of Flash and also the fix for Auth component

**Comment by tanuck** [comment]
Surely changing the key to "Flash" will ease the future transition to 3.x though?

**Comment by dereuromark** [comment]
That is less relevant, though, as it is a major version change. Additionally, the Session key is only internal.

**Comment by tanuck** [comment]
Okay, I see. It will save us having to alter all the mocks of SessionComponent::setFlash() in the AuthComponentTest class as well.

**Comment by ADmad** [comment]
Closing as PR has been opened.
