### ISSUE TITLE
SplFileInfo

### ISSUE THREAD

**Issue by dsandi** [cakephp/cakephp#6876]
I get these errors everyday:

Warning (512): SplFileInfo::openFile(/var/www/unnamed-pro/koticr/tmp/cache/persistent/myapp_cake_core_translations_cake_en__u_s): failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 391]

Warning (512): SplFileInfo::openFile(/var/www/unnamed-pro/koticr/tmp/cache/persistent/myapp_cake_core_translations_default_en__u_s) [splfileinfo.openfile]: failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 391]

Warning (512): SplFileInfo::openFile(/var/www/unnamed-pro/koticr/tmp/cache/persistent/myapp_cake_core_translations_default_en__u_s) [splfileinfo.openfile]: failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 391]

Warning (512): SplFileInfo::openFile(/var/www/unnamed-pro/koticr/tmp/cache/persistent/myapp_cake_core_translations_cake_en__u_s) [splfileinfo.openfile]: failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 391]

I run chmod 777 in the tmp folder and it gets fixed, but the next day i keep getting the error.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by str** [comment]
I don't think it's a question, but a bug.

I also have the same error, daily.

**Comment by lorenzo** [comment]
@str just go to the official hip channels where some of us can help you understand why you see those errors.
