### ISSUE TITLE
Bug in Postgres due to non escaped regex

### ISSUE THREAD

**Issue by atmacola** [cakephp/cakephp#6877]
Trying to upgrade from v2.2.4 to v2.6.7, I found a major problem in some SQL requests.
Some conditions with SQL functions do not make a good SQL string with Postgres plugin.

Here a string I added to lib/Test/Case/Model/Datasource/PostgresTest.php
```
public function testRegexpOperatorConditionsParsing() {
    $this->assertSame(' WHERE EXTRACT( \'YEAR\' FROM "User"."birthday" ) = 2015', $this->Dbo->conditions(array( 'EXTRACT( \'YEAR\' FROM User.birthday )' => 2015 )));
}
```
At this state, the result is ' WHERE EXTRACT( \'YEAR\' FROM User.birthday ) 2015'

Here the commit that make this bug :
https://github.com/cakephp/cakephp/commit/84725993e56b184e40e808eaffadfa3bc934b85c

Now, to solve the problem, I just have to change a single line in lib/Cake/Model/Datasource/Database/Postgres.php
```
//protected $_sqlOps = array('like', 'ilike', 'or', 'not', 'in', 'between', '~', '~*', '!~', '!~*', 'similar to');
protected $_sqlOps = array('like', 'ilike', 'or', 'not', 'in', 'between', '~', '~\*', '\!~', '\!~\*', 'similar to');
```
And the result now is ' WHERE EXTRACT( \'YEAR\' FROM "User"."birthday" ) = 2015'

**Comment by atmacola** [comment]
Or you can solve this problem with add preg_quote() in lib/Cake/Model/Datasource/DboSource.php#_parseKey() in $operatorMatch

**Comment by markstory** [comment]
@atmacola Thank you very much for the great issue report. I've got a pull request up to fix this now.
