### ISSUE TITLE
SQLite datasource incorrectly parses fields with multiple occurances of 'as'

### ISSUE THREAD

**Issue by larryb82** [cakephp/cakephp#6878]
The following code snippet does not work properly when using an SQLite datasource.  The field name is parsed as **bigint)) as WeldCheck__avg_diameter** instead of **WeldCheck__avg_diameter** which changes the structure of the $records array.  The SQL executes without any issues.

```php
// cast will prevent overflow errors on MS SQL Server
$Inspection->WeldCheck->virtualFields['avg_diameter'] = 0;
$records = $Inspection->find('all', array(
  'fields' => array(
    'avg(cast (WeldMeasurement.circle_diameter as bigint)) as WeldCheck__avg_diameter',
    ..
  )));
```

I already have a solution for this, I'll try to create a pull request later today.

**Comment by dereuromark** [comment]
Did you try the documented "virtual fields" approach? You are not using virtual fields here. Also make sure the space around `cast (` does not affect the result.

**Comment by markstory** [comment]
@larryb82 You did a pull request against your fork. We cannot merge that code into this repo. Perhaps you can open the diff you made against _this_ repository instead?

**Comment by larryb82** [comment]
Sorry about that.
https://github.com/cakephp/cakephp/pull/6887

**Comment by markstory** [comment]
Closing this issue as a pull request is up now.
