### ISSUE TITLE
Redirect loop with ajax and AuthComponent

### ISSUE THREAD

**Issue by cjquinn** [cakephp/cakephp#6880]
I'm experiencing a redirect loop issue when using ajax requests with controller actions that are protected by Auth when the user is not logged in. I am using AuthComponent with default settings and not using $this->Auth->allow() on any controller actions.

**Comment by dereuromark** [comment]
You should a) reference the original issue/commit/PR b) mention the exact Cakephp version you are using. Otherwise it will be hard to reproduce with the information you gave us here.

**Comment by cjquinn** [comment]
I am using version 3.0.7, and I think that the issue started after this commit https://github.com/cakephp/cakephp/commit/be1e20c896fce6f1b57bc9cd80dab1d773baca0c.

**Comment by markstory** [comment]
How could someone reproduce this? Would requesting any action that requires authentication do it?

**Comment by cjquinn** [comment]
Yes you could reproduce this by requesting any action that requires authentication with ajax and no ajaxLogin configured in AuthComponent. I tried writing a test for this but couldn't work out how to simulate the ajax request!

**Comment by dereuromark** [comment]
See https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Controller/Component/AuthComponentTest.php#L958 for how to simulate ajax.

**Comment by markstory** [comment]
Pull request open now.
