### ISSUE TITLE
cake cli does not list app shell if existent in core

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#6883]
While playing around with a shell, I noticed that once you put a shell into app namespace, it will be used instead of the core one, but not be listed.
It should be the other way around, since it is being run instead of the core one, the core one should not be listed, but the app one (which takes execution precedence) should.
```
Welcome to CakePHP v3.0.7 Console
---------------------------------------------------------
App : src
Path: ...\site\src\
---------------------------------------------------------
Current Paths:

* app:  src
* root: ...\site
* core: ...\site\vendor\cakephp

Available Shells:

[Bake] bake

[Migrations] migrations

[Tools] i18n, inflect

[CORE] i18n, orm_cache, plugin, server

[app] console, i18m
```

After renaming it to i18m it displayed again.
This does not happen to plugin shells, though.

I would expect:
```
...

[Tools] i18n, inflect

[CORE] orm_cache, plugin, server

[app] console, i18n, i18m
```

**Comment by HavokInspiration** [comment]
I can give it a look

**Comment by HavokInspiration** [comment]
Pull request opened #6893
