### ISSUE TITLE
Allow relative time values in CSRF-cookie.

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#6889]
CookieComponent allows relative time values as cookie expire time ('expires'), while CsrfComponent requires absolute timestamps ('expiry') for its cookie.

While not the same name it would be nice if both behave the same and accept the same input values?

**Comment by markstory** [comment]
Sounds reasonable to me. Supporting strtotime() values is always a nice option as well.

**Comment by Schlaefer** [comment]
I'll open a PR later after master was merged into 3.1 again. Otherwise #6888 will prevent auto-merging.

**Comment by markstory** [comment]
Ok.
