### ISSUE TITLE
Bake recreates tmp templates for files.

### ISSUE THREAD

**Issue by genellern** [cakephp/cakephp#6892]
After I bake the first module, I have some new files inside tmp folder, which are supposed to be the templates used to generate my files.
Then I modify those templates to make them match what my code will look like, when I go back to the console and run the same command (bake all) it also recreates the templates, therefore I lose my changes.
> bin/cake bake all Roles (for my case) 

If I want to keep my changes and still use the templates, I have to remove a permission like 
> chmod -w tmp/*.php

And then I get this error:
>  Permission denied in [/Library/WebServer/Documents/Platform/vendor/cakephp/bake/src/View/BakeView.php, line 173]

**Comment by rchavik** [comment]
This is expected, don't you think?  Files in `tmp` are volatile.  You should not modify anything in `tmp` by hand.

It seems that you should create a bake 'theme' for your needs: http://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme
