### ISSUE TITLE
3.0 - Table::findOrCreate could be better

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6896]
Hi guys. I just ran into a situation where I needed to use `Table::findOrCreate`. However, if you're searching on something possibly ambiguous like an `id`, (if there are behaviors on the table who add associations) you have to specify the `$search` with the `Table` alias. `findOrCreate` then tries to make a new entity with that same search, which won't work..

```
$this->Table->findOrCreate(['Table.id' => 88]);
\Table Object
(
    [Table.id] => 2003685873
    ....
```
That of course won't persist, since there's no `Table.id` field in `Table`, it's `id`.

This method right now also doesn't let you add finder options, which help when a table has special conditions in their `findAll`s.

I thought about maybe having the beginning of that method go through `Table::get` but that's obviously different.
Maybe a 3.1 change would be that `findOrCreate` is moved to the `Query`, so it's part of the normal query chain? Or a new `Table::getOrCreate` method?

Thanks

**Comment by markstory** [comment]
Having a chainavle query method could be nice. I don't know how it would work with setting up the new entity, as the query builder could define complex conditions that cannot be converted into properties on the entity.

**Comment by patrickconroy** [comment]
Hey @markstory .. I think this was fixed when `firstOrFail` was implemented. I've been using that and it's what I was looking for originally. Feel free to close this if you think it's ok.
