### ISSUE TITLE
AJAX post request not recognized

### ISSUE THREAD

**Issue by ArakTaiRoth** [cakephp/cakephp#6900]
I've simplified the code to the bare essentials just to get a handle on what's going wrong. Basically I have this in my javascript:
```javascript
$('a#delete').on('click', function(e) {
    e.preventDefault();
    $.post($(this).attr('href'), $('input.delete:checked').serialize());
})
```
This works on a button click from a button I've created with Cake:
```php
echo $this->Html->link(__('Delete Selected'),
    ['controller' => 'Portfolios', 'action' => 'delete'],
	['id' => 'delete', 'class' => 'btn btn-danger hidden margin-left',
          'confirm' => 'Are you sure you want to delete the selected portfolios?'
	]
);
```
It works on the following input elements which are created dynamically:
```php
'<input type="checkbox" name="delete_portfolio" class="delete" value="' . $result->id . '">'
```
As such I have CSRF protection turned off for this action:
```php
if ($this->request->action === 'delete') {
	$this->eventManager()->off($this->Csrf);
}
```
And it all submits to this action:
```php
public function delete() {
    debug($this->request->is('ajax'));
    debug($this->request->is('post'));
    debug($this->request->data);
    die();
}
```
The first debug statements returns `TRUE` as expected. The second debug statement however returns `FALSE`, and the third debug statement returns an empty array.

I have verified with Fiddler that a `POST` request is being sent and so is the correct data. Indeed if I add:
```php
debug($_SERVER['REQUEST_METHOD']);
debug($_POST);
```
I get `POST` as expected, and I get the data as expected.

I'm just trying to figure out if I'm doing something incorrectly here, or if this is a bug in CakePHP.

**Comment by markstory** [comment]
Does your form include a `_method` input? This input has special meaning in CakePHP and can convert POST requests into DELETE ones.

**Comment by ArakTaiRoth** [comment]
No, technically no form was created. The javascript is just serializing all the inputs I've dynamically created that are checked, and submitting them as data. The inputs are not inside a form, and the button is not a submit button.

According to Fiddler, the only data is in the form of `inputName=inputValue`.

**Comment by markstory** [comment]
I think you might be hitting an edge case others have not encountered, as I'm quite confident that both the POST data handling and ajax parts of CakePHP work, something must be different here, I can try and reproduce the issue with the information that is here.

**Comment by ArakTaiRoth** [comment]
So, I have more info to add to this now. I was continuing on with programming my delete functionality, just utilizing the actual server variables `$_SERVER['REQUEST_METHOD']` and `$_POST`. But I noticed that in the same action `public function delete()`, reading Cookies wasn't working either, but it worked in every other action in the controller.

So I looked at what I was doing different for this action, and the only thing was disabling CSRF:
```php
if ($this->request->action === 'delete') {
	$this->eventManager()->off($this->Csrf);
}
```
So I removed the Csrf component from being loaded in the AppController.

And lo and behold reading from Cookies worked, and `$this->request->is('post')` returned `TRUE` and I could read the data from `$this->request->data`.

So it seems that disabling Csrf also disables a fair amount of base functionality. I would consider this a bug, as it was completely unintended.

**Comment by markstory** [comment]
Where/when are you disabling the csrf component?

**Comment by ArakTaiRoth** [comment]
Initially I had the Csrf component enabled in the initialize function in my AppController:

```php
public function initialize()
{
      $this->loadComponent('Flash');
      $this->loadComponent('RequestHandler');
      $this->loadComponent('Csrf', ['secure' => TRUE]);
```
And then I had it disabled in my beforeFilter function in my PortfoliosController:
```php
public function beforeFilter(Event $event) {
	parent::beforeFilter($event);
        if ($this->request->action === 'delete') {
                $this->eventManager()->off($this->Csrf);
        }
	$this->layout = 'dashboard';
}
```
But after I removed the `loadComponent('Csrf')` everything worked as expected.

I'm not sure this is related to the above issue that was referenced. I'm getting a 200 status code back like I should be, just certain cake functionality isn't working like reading Cookies (they always return null even when I know they're set), and a messed up $this->request (no data, not giving the proper action, etc...).

**Comment by markstory** [comment]
And the request only acts incorrectly when the csrf component is enabled?

**Comment by ArakTaiRoth** [comment]
Well, that's what I thought initially, as I had removed the Csrf component from ever being enabled and it all worked. But I believe that testing wasn't accurate, as I believe I was submitting from a dud form I had creating using the FormHelper, instead of through my ajax.

Submitting via ajax with Csrf removed, still causes the problems. Submitting with Csrf enabled and manually adding the csrf token to the data submitted also causes the stated issues.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue CSRF component entirely absent from the controller.  Nor with the CsrfComponent enabled. I created [this gist](https://gist.github.com/markstory/687276adeaead6458e19) of the files I used in a freshly created app skeleton via `composer create-project cakephp/app`. Is there something I've missed?

**Comment by ArakTaiRoth** [comment]
This is using https for everything, perhaps that has something to do with this?

**Comment by markstory** [comment]
It could, but CakePHP does very little the differences in HTTP/HTTPs. The only thing it really does is set cookie values and generate URLs.

If you use a non-SSL setup do you have the same issues?

**Comment by ArakTaiRoth** [comment]
So, I removed the whole SSL setup, and the Csrf component. Upon doing so I was given a new error when trying to submit, everything was getting blackholed. I quickly figured this out and used:
```php
$this->Security->config('unlockedActions', ['delete']);
```
To unlock the action. Once I did this, everything worked fine. So I restored the SSL setup and the Csrf component, and everything is working now.

So it appears I was actually being blackholed, yet was not being told that I was, instead everything went through to the action just fine but most of Cake's functionality was broken.

**Comment by markstory** [comment]
Ok, you never mentioned before that you had SecurityComponent enabled - that is an important piece of information.

How do you have SecurityComponent configured?

**Comment by ArakTaiRoth** [comment]
Fairly basically:
```php
$this->loadComponent('Security', ['blackHoleCallback' => 'forceSSL']);
```
And the forceSSL function:
```php
public function forceSSL() {
  return $this->redirect('https://' . env('SERVER_NAME') . $this->request->here);
}
```

**Comment by lorenzo** [comment]
I knew a redirect was involved, that was the only thing that could explain this behavior. But I could not find any redirects in csrf :P

I think you need to avoid the redirect on Post requests, as it would not make sense as a redirect is always GET

**Comment by ArakTaiRoth** [comment]
Yea, I just find it odd that I was never given a blackhole error, even thought that's exactly what was happening. It appeared like I was getting through to the function as debug statements in the function were running, but in reality I wasn't.

**Comment by markstory** [comment]
You won't get an error, as you've asked for a redirect.

Debug statements get buffered by php based in your settings and discarded when there are redirects run.

Closing as we figured out why your code wasn't working.

**Comment by ArakTaiRoth** [comment]
Just wanted to say thanks guys, I appreciate the help in figuring this out.
