### ISSUE TITLE
Query deselect function

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6904]
Currently you can specify an entirely new list of columns or you can append columns to the already selected one, it might be helpful to be able to individually remove columns from the select statement.

**Comment by markstory** [comment]
When would you need to do this?

**Comment by cmann1** [comment]
Well for example I have a table with a fair amount of columns and when loading an entry from it I need most of the columns, but not all of them.
Currently, in order to exclude those columns I have to reselect all of the other one:
```php
$this->find()->select(['column_a', 'column_c', 'column_d', 'column_e', ...])
```
Whereas it would be far more convenient to simply say:
```php
$this->find()->deselect(['column_b']);
```

**Comment by mylux** [comment]
To me, it seems something nice to have.

**Comment by markstory** [comment]
Would you deselect complex expression based fields by alias?

**Comment by greew** [comment]
Couldn't this "just" be fixed with the following extra line?

    $query = $this->find()->select($this);
    $query->select(array_diff($query->select(), ['column_b']));

I know it requires some extra work each time, but it's quite easy to do..

**Comment by ionas** [comment]
I'd very much love to see a good range of support for removing composition elements towards 4.0. `deselect()` would be one of those. I am however not sure if that interface is the best. How would you remove an `innerJoinWith()`

**Comment by markstory** [comment]
@greew It can. This issue is asking for a higher level API to do that.

@ionas Perhaps `withoutInnerJoin()`?

**Comment by burzum** [comment]
@markstory another use case is that when you have a complex custom finder and want to re-use it in another finder but don't want one or two of the fields or assocs. So removing stuff from the query would be nice to have IMHO.
