### ISSUE TITLE
RFC - Change AuthComponent::startup() to AuthComponent::beforeFilter()

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#6905]
At times i have seen devs trying to get logged in user info in controller's `beforeFilter()` when using stateless authenticators. That doesn't work since AuthComponent checks for user record availability through stateless authenticators from it's `startup()` callback which is run after controller's `beforeFilter()`.

So changing `AuthComponent::startup()` to `AuthComponent::beforeFilter()` would fix this issue as component's `beforeFilter()` callbacks are triggered before controller's `beforeFilter()`. The component can be configured through controller's `initialize()` so there's no real need delay the authentication.

Though this change would affect those setting up Auth in `beforeFilter()` and hence would not be backwards compatible.

**Comment by lorenzo** [comment]
> Though this change would affect those setting up Auth in beforeFilter() and hence would not be backwards compatible.

That's our biggest problem

**Comment by ADmad** [comment]
I know :(  Most users updating from 2.x might be habituated to configuring Auth in beforeFilter().

How about we retain current behavior as default and add a config option to do the auth process in component's beforeFilter() instead of startup() ?

**Comment by markstory** [comment]
I think a config option might be the best way to solve this without breaking compatibility. It feels awkward but changing the behavior will cause application issues as you mentioned.

**Comment by dereuromark** [comment]
+1 for the config option.

**Comment by ADmad** [comment]
Closing as PR is opened.
