### ISSUE TITLE
Response streams

### ISSUE THREAD

**Issue by reinink** [cakephp/cakephp#6907]
Hey all, was hoping to your help on something. I'm currently making a Cake adapter for my [Glide](http://glide.thephpleague.com/1.0/) 1.0 release, and ran into an issue with the responses. Glide uses streams when outputting images, which is especially useful when pulling down images from Amazon S3, or other remote file systems.

Looking through `Cake\Network\Response`, I see that I can stream a local file using the `file()` method, but I don't see anyway to pass in my own stream. I can only provide a path. Since the stream in my situation is in memory, this doesn't work.

Is there a way to do this that I'm not seeing?

**Comment by lorenzo** [comment]
Is your stream a file resource handle or an object?

**Comment by reinink** [comment]
It's a file resource handle.

**Comment by lorenzo** [comment]
I think adding support for file resources should be easy. Would you like to submit a pull request with the enhancement?

**Comment by reinink** [comment]
Yeah, if I have a chance I'll try do this. I see this being done one of two ways:

First, we could add support for file resources. Maybe this is added to the `file()` method somehow.

Alternatively, we could do what Symfony has done with HttpFoundation, where you simply provide a callback. Then, when the response is sent, this callback is invoked. This design is very flexible, and can be used for file resources, or really anything. I could see this feature being added to the `body()` method, which would then accept either a `string` or a `callable`. For example:

```php
$this->response->body(function () use ($resource) {
    rewind($resource);
    fpassthru($resource);
    fclose($resource);
});
```

Or you could use a `bodyCallback()` method if you don't like mixed parameter methods.

What approach do you think is best?

**Comment by lorenzo** [comment]
I like that idea as well @reinink :)

**Comment by lorenzo** [comment]
The ideal solution would be to have both features. We can start with the simplest one which is the callback.

**Comment by reinink** [comment]
Agreed!

**Comment by lorenzo** [comment]
@reinink Let me know if you want to take care of any of the tasks, otherwise I will try to start on them somewhere this week

**Comment by reinink** [comment]
Thanks, I'll let you know. I'm hoping this will be a very simple addition, but I'll let you know if I run into any snags. ;)

**Comment by reinink** [comment]
This is what I had in mind: https://github.com/reinink/cakephp/commit/259ecb42a09050364c5ab66da092a4ed9bde2e6d

I tried to write tests for this, but it's very hard to do without `@runInSeparateProcess`, which is triggering many "constant already set" errors.

Note that the `__toString` method simply returns a blank string. The other option is to use output buffering, and actually call the callable, and then return it. However, that just doesn't feel right, and if we use HttpFoundation as the example again, it also doesn't allow this. Also, you cannot throw an exception within the `__toString`, so returning a blank string seemed the most appropriate.

Let me know what you think.

**Comment by markstory** [comment]
Code looks good so far, couldn't you test this by having a callback return a string? If the test is to ensure that a callback is invoked that should be enough.

**Comment by reinink** [comment]
@markstory Unfortunately not, since callback doesn't return, it echos. And normally you could just use output buffering in your tests to catch this, but in this situation headers are also sent (via `send()`). PHPUnit freaks out if you send headers, which is why the `@runInSeparateProcess` option exists. However, Cake's test bootstrap generates errors when using this PHPUnit option.

**Comment by markstory** [comment]
In other tests, we've used mocks to stub out the protected method that wraps `header()`. That might be a way to get around needing a separate process as well.

**Comment by reinink** [comment]
Yeah, I was looking at those tests, and to be honest I'm not sure they're really testing anything beyond calling the methods with the correct parameters. They don't actually test any method behaviour, because their only stubs. For [example](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Network/ResponseTest.php#L224):

```php
$response->expects($this->once())->method('_sendContent')->with('the response body');
```

That only checks that `_sendContent` was called with the content "the response body", but doesn't actually test that `_sendContent` echos it out, or in the case of this update, invokes the callable.

And, again for clarity, since the response class sends the header and content in the same method (`send()`), we have no way to tests that `_sendContent` is actually working without also sending the headers.

Testing real output sucks.

**Comment by markstory** [comment]
> Testing real output sucks.

It sure does.

The method I was thinking you could stub was `_sendHeader()`. That would at least remove the header issues phpunit has. Output buffering could be used to get the real output. There are a few places in our test suite we use `ob_start()` to test methods that output.

**Comment by reinink** [comment]
Ahhh...I hadn't considered that. So smart.

**Comment by reinink** [comment]
And we've got a test: https://github.com/reinink/cakephp/commit/e4089565dd0d645321b71f9a9b75aacb780c61ad

Share I submit the PR now?

**Comment by markstory** [comment]
Looks good, a pull request against `3.1` would be awesome.

**Comment by reinink** [comment]
Done, but it didn't merge very well. See #6912.

**Comment by ADmad** [comment]
@reinink Looking forward to your Cake adapter for Glide :)

**Comment by markstory** [comment]
Closing as there iis a pull request open now.

**Comment by reinink** [comment]
@ADmad Same! I've got his working locally, and it works great!

**Comment by ADmad** [comment]
@reinink Good to hear. Coincidentally I was browsing through your enhancements list today :)
