### ISSUE TITLE
Translations in contain with self relation occur fatal error

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#6909]
If my Table has no result for parent relation with translations that occurs the following error

    Fatal error: Call to a member function get() on a non-object in \vendor\cakephp\cakephp\src\ORM\Behavior\TranslateBehavior.php on line 441

If i remove the translations in my contain, that's work nice and parent relation return null, my children relation work nice and return results with translations, but obviously because my id is 1 and have children.

So do the same test but in my children (id = 2), children relation return null, ok, and parent relation return parent with translations....

The bug occurs when i try to get parent translations with belongsTo relation type.

Here my Table

    class ContentbuildersTable extends Table {

        public function initialize(array $config)
        {
            $this->addBehavior('Tree');
            $this->addBehavior('Timestamp');
            $this->addBehavior('Translate', [...]);
    
            $this->belongsTo('ParentContentbuilders', [
                'className' => 'Contentbuilders',
                'foreignKey' => 'parent_id'
            ]);
    
            $this->hasMany('ChildrenContentbuilders', [
                'className' => 'Contentbuilders',
                'foreignKey' => 'parent_id'
            ]);
    
        }

    }

Here my controller
    
    $contentbuilder = $this->Contentbuilders
        ->find('all', [
            'conditions' => [
                'Contentbuilders.id' => $id
            ],
            'contain' => [
                'ParentContentbuilders' => function($query) {
                    return $query->find('translations', ['locales' => [I18n::getLocaleBySubDomain()]]);
                },
                'ChildrenContentbuilders' => function($query) {
                    return $query->find('translations', ['locales' => [I18n::getLocaleBySubDomain()]]);
                }
            ]
        ])
        ->find('translations', ['locales' => [I18n::getLocaleBySubDomain()]])
        ->first();

    debug($contentbuilder->toArray());
    die();

**Comment by AD7six** [comment]
> Fatal error: Call to a member function get() on a non-object in \vendor\cakephp\cakephp\src\ORM\Behavior\TranslateBehavior.php on line 441

What is `$row` [on the line throwing the error](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TranslateBehavior.php#L441) ?

**Comment by Angyo** [comment]
\src\ORM\Behavior\TranslateBehavior.php (line 442)
    null

**Comment by markstory** [comment]
@Aerue Is this issue still happening in newer releases?

**Comment by lorenzo** [comment]
This was in another similar ticket ticket some time ago
