### ISSUE TITLE
3.0 - FileEngine failing with deep collections

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6910]
Right now it looks like if you have a deep collection somewhere in some data and you try to cache it, it fails when writing to a file. This is despite it working fine outside the cache flow. I'm not sure if it's the same with other engines.

This fails since it's not really writing that to cache, so when reading it back you get the old ``Failed calling Cake\\Collection\\Collection::jsonSerialize()``.
```
$test = Cache::remember('test', function() {
    return ['a', 'b' => collection(['c', 'd'])];
});
$this->set(compact('test') + ['_serialize' => ['test']]);
```

Outside cache, it's fine..
```
$test = ['a', 'b' => collection(['c', 'd'])];
$this->set(compact('test') + ['_serialize' => ['test']]);
```

This came up since I have a table that can interact with an API, I have it return collections, and I got to the point where I needed to cache the API response. I haven't had time to debug any further than this, but seems like something that should work.

Thanks

**Comment by markstory** [comment]
You'll have to convert the collections to an array before trying to cache/serialize them. Iterators do not serialize well.

**Comment by markstory** [comment]
With that said, CakePHP could either raise an error or handle this conversion for you.

**Comment by patrickconroy** [comment]
Thanks @markstory, I ended up with `toArray`ing.. but yeah it seems like something that should just work since collections are pretty powerful and could be used in a lot of places like this.

**Comment by markstory** [comment]
@patrickconroy Collections are super powerful, but iterators in general serialize very poorly.

**Comment by lorenzo** [comment]
PHP makes me sad. Should I resurrect the branch were I implemented collections as a serializable object?

**Comment by markstory** [comment]
@lorenzo I am not sure. It was pretty complex. And while it solves the issue for collections there are lots of othe unserializable object in php that will also fail in this same way.

**Comment by markstory** [comment]
Closing as José has figured out a simple way to serialize collections.
