### ISSUE TITLE
Integrate different configurations into CakePHP core for popular cloud providers

### ISSUE THREAD

**Issue by oussamac** [cakephp/cakephp#6914]
I've been using CakePHP for almost 5 years now and in the last couple of years I've deployed many Cake based apps in the cloud, mainly Google App Engine. The problem with such cloud providers is that they impose a certain set of rules and restrictions which come in conflict with the framework.

The solution is to "hack" around those conflicts to make the app compatible, which is totally fine by me. But trust me I've seen some ugly workarounds that are added in the Core of the framework and therefore make updating the Core a nightmare.

My idea is to incorporate different configuration sets (Cache, tmp files, supported database methods,...) for popular cloud providers (Google App Engine, AWS, Azure,...) and make it that the user specifies the desired configuration through the Config file which is, I think a more elegant solution (The same as specifying the options of the database or cache engine).

I'm waiting for your feedback and proposal. And, ready to help with this.

**Comment by lorenzo** [comment]
What sort of hacks did you have to implement? We could  document them or offer the changes as plugins

**Comment by markstory** [comment]
Could the configurations for different hosting providers be provided as part of the documentation? Or perhaps as commented out code in the application skeleton?

**Comment by HavokInspiration** [comment]
Documentation and a note in the app skeleton sounds better to me (something like : "Using a cloud provider ? Check out the CakePHP cookbook (_with link_)").

I fear having it commented out in the app skeleton will generate an awful lot of comments, especially if there are a lot of instructions and / or a lot of cloud providers examples.

**Comment by markstory** [comment]
@HavokInspiration I would lean towards documentation too. We have a similar section in the docs for configuring various webservers.

**Comment by ADmad** [comment]
@oussamac Can you provide any actual info regarding the hacks your claim are needed to get Cake 3.0 running on provider of your choice?

**Comment by oussamac** [comment]
@lorenzo  @ADmad Well, for Google App Engine you have to : 

- Change the default Caching engine to either APC or Memcache (otherwise the app will break)
- Change TMP path, Logging file PATH, Errors File path, ... because GAE only allows to store data through its Data Storage component (Buckets)
- Switch to a unix-socket based connection for databases when deployed and switch back to a standard connection when in localhost.

- Preferably use database based sessions.

These are the mandatory things, of course we can do this now, but it's just a little bit nasty I think.

Furthermore, CakePHP could add some more features for a tighter integration, like : 
- Integrate the Mail component with GAE's one (Since GAE's doesn't allow php mail function, and allows only to send emails through a Google account)
- Integrate the AuthComponent with GAE's users API (Google accounts)
- Redirect CakePHP logging features directly to GAE's since there is a great UI to consult them.
- Configure the Cloud Storage Buckets used by the App when deployed and when not.
- There is also the Task Queue API which permits Apps to execute code in the background and I think CakePHP could benefit from this concept and even greatly if integrated with GAE's one.

@markstory @HavokInspiration I agree with you, documentation sounds better with a hint comment in the configuration section.

For these features I'm thinking either to integrate them as part of CakePHP core or provided as officially supported plugins such as DebugKit?

Any suggestions.

**Comment by lorenzo** [comment]
@oussamac Starting with a plugin seem like a better idea to me :)

**Comment by ADmad** [comment]
@oussamac I don't see any "hacks" in your list, all configuration changes. How is configuring your app to suit the deployment environment a nasty thing? The framework can't guess the configuration required for various environments.

You are welcome to make a PR to the manual for listing these specific configurations for GAE. For the additional features as @lorenzo suggested a plugin would be the way to go.

**Comment by burzum** [comment]
:+1: for @ADmad suggestion!

**Comment by beporter** [comment]
@oussamac: Another possibility is to create your own version of the `cakephp/app` skeleton that contains your customizations "by default". When you use `composer create-project`, you reference your skeleton instead of the core team's skeleton, and you get a new Cake 3 app with everything set up as you expect right out of the box. You could maintain a single one with code for all providers, or one a piece tuned for each specific provider. This also has the benefit of creating a single spot that acts as a "reference" for "how you do it" that you can go back to, allowing your projects to stay more consistent.

As an example that works well for my team, see [loadsys/skeleton](https://github.com/loadsys/CakePHP-Skeleton).

**Comment by ADmad** [comment]
Closing as no actual changes are required in cake core to address this issue.
