### ISSUE TITLE
Http Adapter _send() issue

### ISSUE THREAD

**Issue by DavidGiannetto** [cakephp/cakephp#6915]
When _send() in Network\Http\Adapter\Stream.php checks the wrapper_type of the response to se the headers properly, it uses a case sensitive comparison on the string 'curl'.  Therefore, if the wrapper_type is something along the lines of 'cURL', the comparison fails and the headers are not properly set.

**Comment by markstory** [comment]
When does this happen?

**Comment by DavidGiannetto** [comment]
I came across it trying to do a Cake\Http\Client->get() on php 5.4.41 with curl 7.26.0.  Not really sure of what other particulars might contribute to this.

**Comment by markstory** [comment]
Fixed with #6916
