### ISSUE TITLE
PSR2 Additions and Creating behaviors

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#6917]
This is just questions:

1. CakePHP 3 useing PSR2 coding standards, but in https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#php-open-tags says avoid using `<?= ... ?>`.
It will be replaced?

2. I create some behavior with beforeSave callback. But when not set any arguments, i think sould be return error like: it's not compatibilie with parent, there is no Enity and Event arguments. It's ok?

**Comment by lorenzo** [comment]
1. We follow PSR-2, not the specification you linked to

2. There is no parent for any of the callbacks in behaviors. They are dynamically attached and we don't enforce any signature for them. In fact, they don't have to have the suggested names. You can name the callbacks anything you like and tell the behavior where to fin your methods
