### ISSUE TITLE
3.0 MysqlSchema::describeForeignKeySql(...) returns constraints from other schemas

### ISSUE THREAD

**Issue by augustas** [cakephp/cakephp#6918]
When database instance has several different schemas with the same table/constraint names, then `Database\Schema\MysqlSchema::describeForeignKeySql(...)` built query will return constraints from those other schemas.

Then `Database\Schema\Collection::describe()` builds a `Database\Schema\Table` instance with wrong constraints and in my case, test fixture initialization will fail when schema is imported from the database.

Code: https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/MysqlSchema.php#L225

My suggestion on the query improvement would be to add a constraint schema check, ` AND kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA`:

```php
    public function describeForeignKeySql($tableName, $config)
    {
        $sql = 'SELECT * FROM information_schema.key_column_usage AS kcu
            INNER JOIN information_schema.referential_constraints AS rc
            ON (kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME AND kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA)
            WHERE kcu.TABLE_SCHEMA = ? AND kcu.TABLE_NAME = ? and rc.TABLE_NAME = ?';

        return [$sql, [$config['database'], $tableName, $tableName]];
    }
```

**Comment by lorenzo** [comment]
Would you like to submit a pull request for this?

**Comment by markstory** [comment]
Closing as #6943 is open now.
