### ISSUE TITLE
3.x Can't use dot in a cache config

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#6919]
**What I did**
```php
\Cake\Cache\Cache::config('CurrencyExchange.ratesCache', [
    'className' => 'File',
    'path' => CACHE,
    'duration' => '+1 year',
    'prefix' => 'currency_exchange_'
]);
```

**What happened?**
I got a PHP Fatal for trying to use `write()` on a non-object.

**What's going on?**
The Cache class `write()` method calls `engine()` to build the cache engine, which calls `_buildEngine()`, which in turn calls [`static::$_registry->load($name, $config);`](https://github.com/cakephp/cakephp/blob/master/src/Cache/Cache.php#L135)`.

In the [`ObjectRegistry` class, the `$objectName` is parsed using `pluginSplit()`](https://github.com/cakephp/cakephp/blob/master/src/Core/ObjectRegistry.php#L72) which removes the first part of the cache config name. This means that the loaded object never matches with the config in the cache class. `CurrencyExchange.ratesCache != ratesCache`

**How I got around it**
I updated my cache config from `CurrencyExchange.ratesCache` to `CurrencyExchange_ratesCache`

**Comment by robertpustulka** [comment]
Isn't that desired behavior?

**Comment by davidyell** [comment]
@robertpustulka Quite possibly, as it's using the `ObjectRegistry` class which loads pretty much everything. However when naming plugin specific things, I tend to use the plugin notation to denote that it's associated with a plugin.

**Comment by robertpustulka** [comment]
Maybe CacheRegistry could check for class existance and fallback to default engine eventually?

**Comment by lorenzo** [comment]
@robertpustulka that should be the right thing to do

**Comment by markstory** [comment]
We could try not splitting on . but I think it might cause issues with plugin objects. As we support `Plugin.Thing` as a shortcut to populate the `Thing` key.

**Comment by lorenzo** [comment]
@markstory we just need to avoid the splitting if there is a className already

**Comment by markstory** [comment]
Ok. That should be doable I think.

**Comment by markstory** [comment]
Closing as I have a pull request up now.
