### ISSUE TITLE
Form Templates Make people crazy!!

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6920]
CakePHP 3 It's not convenient to use. No argument can be introduced. Each input needs a custom template. 

I need a input like this:

label    input   addon

But i can't custom addon on one input.   Unless i write a custom templates.php in config dir. one input one templates...    oh~~ my god ~

I suggest that we can pass the parameters in the template.

**Comment by AD7six** [comment]
I don't know what this ticket means since there's no code in it.

**Comment by lorenzo** [comment]
@macnie You know you can set the templates in the `Form->create()` call and even in the `input()` call?
There is no need to use a template config file.

Related to this, we are working on a solution to let users add custom parameters to their templates. It should be released with CakePHP 3.1: https://github.com/cakephp/cakephp/pull/6850

**Comment by macnie** [comment]
@lorenzo  thx!    i hope we can pass the parameters in the template.

**Comment by dakota** [comment]
The fact that you are referring to `addon` makes me think that you are using bootstrap (If I'm wrong then ignore the rest of this!)

If you are using bootstrap, take a look at https://github.com/FriendsOfCake/bootstrap-ui, it includes templates for all bootstrap form elements, and has support for bootstrap `addon` elements.

e.g.

```php
echo $this->Form->input('price', [
'label' => false,
'placeholder' => 'Amount'
'prepend' => '$'
'append' => '.00'
]);
```

To output the bootstrap example.

```html
<div class="form-group">
    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
      <div class="input-group-addon">.00</div>
    </div>
  </div>
```

**Comment by markstory** [comment]
@macnie Does the addition of templateVars in #6850 look like it will help address  at least some of the problems you have with input templates?

**Comment by ADmad** [comment]
Closing as #6850 has been merged and you can now add custom vars to templates.
