### ISSUE TITLE
[RFC] Auth refactor, better separation

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#6925]
The goal of this proposal is better separation and modularity. It would be nice if we could decouple the auth system from relying on the AuthComponent.
- [x] Separate the whole Auth related logic from the component (`\Cake\Auth\Manager.php` maybe?) and if possible Cake. In an ideal world this could become a split like the ORM and work without other components from the CakePHP framework.
- [x] For BC make the AuthComponent a proxy to the new Auth
- [x] Move the authorization and authentication adapters into sub namespaces `\Cake\Auth\Authorization` and `\Cake\Auth\Authentication`
- [x] Figure out a way to stay BC for the adapters, maybe implement a method to pass an object that implements an interface that can be called by the AuthManager to get the credentials / authorization info from?

A few of the proposed changes are already WIP in this branch here. https://github.com/burzum/cakephp/tree/feature/auth-refactor

## Update

The plan for now is a separate implementation in a plugin which has already been started here https://github.com/burzum/cakephp-middleware-auth and moving it the CakePHP org when it's done. Let it mature as a plugin and integrate it probably in 3.4 or 3.5 into the core.

## Update 2

The authentication part has been completely refactored into a plugin until it's mature enough to go into the core. https://github.com/cakephp/authentication

The current roadmap for it is to have it as a plugin until 3.5 and then add it to the core.

**Authorization** can be discussed here https://github.com/cakephp/cakephp/issues/9835

**Comment by ADmad** [comment]
It would be surely nice to get rid of the strong coupling authentication related classes have with controller layer and allow it be used independently or as middleware.

But I am skeptical whether it can be achieved in a backward compatible way. For eg. the authentication and authorization class constructor receives component registry as argument, changing the signature would break all custom one out there.

**Comment by burzum** [comment]
@ADmad we could try keep the old classes in place and make them a proxy to the new classes. That would allow people to migrate and we can deprecate them some time in the future.

**Comment by ADmad** [comment]
@burzum Yup that's an option.

**Comment by markstory** [comment]
What if there was a new middleware option that was built on top of something like PSR-7, and in addition to that the current AuthComponent for backwards compatibility. Having a new auth system, and one for compatbiliity isn't too gross to me.

**Comment by jhli** [comment]
Just in general for this as well as the PSR ticket I do like the approach of do-it-new + keep the old codebase to be used which will later be removed entirely. :+1:

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/6247

**Comment by burzum** [comment]
@dereuromark well, these getters referenced in #6247 would be redundant to getAttribute() of the request object? The best they're convenience methods? They would just wrap a call to getAttribute().

I'm not totally against it but I don't see a huge benefit either. @markstory what is your opinion on this?

**Comment by dereuromark** [comment]
Future components and helpers could still wrap it this way if needed. I am fine with a first basic request solution :)

**Comment by markstory** [comment]
I think having wrapper methods is kind of nice as it makes for less typing/more expressive code and keeps IDE folks happy. However, wrapper methods will need to wait until the new plugin is integrated into CakePHP.

**Comment by burzum** [comment]
I'll add them at a later point when the authentication stack becomes part of the core? getSession() could be already added.

**Comment by markstory** [comment]
@burzum That sounds good to me.

**Comment by skie** [comment]
I propose during this refactoring to remove tight coupling between Authorize layer and Controller object. This allow to use Authorize layer not only for Controller.

**Comment by burzum** [comment]
@skie this has already been done for the authentication layer of it. See https://github.com/cakephp/authentication

**Comment by skie** [comment]
Yes, I know about cakephp/authentication. But I saying about separate thing - Authorization layer. Right now if you take a look into BaseAuthrize class, you will see that constructor getting ComponentRegistry, which in its turn getting Controller as argument. This what i mean under tight coupling between Authorize layer and Controller object.

**Comment by burzum** [comment]
@skie I'm aware of it and the authorization layer is on my agenda as well. The problem is that you're very likely not able to provide a generic interface for all kinds of authorization concepts. So the API should just provide the actors to a class that then passes them to the specific implementation. Something like that might work. If you wan't to discuss this topic please start a new RFC issue.

**Comment by burzum** [comment]
@skie continue the discussion here #9835 if you like to

**Comment by ADmad** [comment]
Closing this issue as development of [cakephp/authentication](https://github.com/cakephp/authentication) is well under way, which addresses the authentication related recommendations. Separate issue has been opened to address authorization.

**Comment by burzum** [comment]
@ADmad just that we don't forget it: We should flag the old authentication as deprecated when we merge the plugin into to core some time next year and encourage the use of the new code. As soon as we tag 1.0.0-alpha we should create some buzz around it and make clear that this will be the future way of doing it so people have time to adept and get used to it.

**Comment by dereuromark** [comment]
Not sure if we should have closed this (or the parent issue), as the main part needed for view layer (request extension) is not yet shipped.
