### ISSUE TITLE
->select['field'] not selecting

### ISSUE THREAD

**Issue by Kitcat711** [cakephp/cakephp#6928]
Context:
Leases belongstoMany NaturalPeople through LeasesNaturalPeople
$query = $this->Leases->find();
$query->matching('NaturalPeople')
	->where(['LeasesNaturalPeople.role IN' => ['holder','guarantor']])
	->distinct(['Leases.id'])
	->contain(['NaturalPeople' => function($q) {
		return ** $q->select(['name']) **
		->where([ 'LeasesNaturalPeople.role IN' => ['holder','guarantor']]);
	]);

Select(['name']) is inoperant : all fields are returned.

**Comment by robertpustulka** [comment]
Try setting `$q->autoFields(false)`

**Comment by Kitcat711** [comment]
Thanks Robert, it fixed it.
