### ISSUE TITLE
markNew option when init a newEntity doesn't work

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#6930]
Hi,
I want to init an entity and set the **[new]** property to **false** ```'[new]' => false``` using the **markNew** option
```php
$Table->newEntity($my_data_array, ['markNew' => false]);
```
The options **validate**  and **accessibleFields** works but **markNew** doesn't work and it returns always ```'[new]' => true```

**Comment by ADmad** [comment]
`markNew` is not a value key for the `$options` param of `Table::newEntity()`. These options are passed on the marshaller method, not entity constructor. 

So if you data array contains primary key value `'new'` will be set to `false`.  Use `$entity->isNew(false)` after entity is constructed.

**Comment by dereuromark** [comment]
I wonder if it would be useful to add such an option key.

**Comment by rchavik** [comment]
I'd say the same too.

this is the third instance ive come across this expectation.

**Comment by flashios09** [comment]
@ADmad thanks for your reply,
I know how to set **'[new]'** to **false** using the **isNew** method with **boolean** param after init the entity(**$Table->newEntity**), i take a look at the source and i notice that the **one** method in the **Marshaller** Class init the the entity without passing any option. 
```php
// Cake\ORM\Marshaller.php:110
$entity = new $entityClass();
```
Why we can't pass the options directly to the entity like this
```php
// Cake\ORM\Marshaller.php:110
$entity = new $entityClass($data, $options);
```

**Comment by ADmad** [comment]
@flashios09 `new` is already `true` by default when entity is constructed. It's the data that is set afterwards that causes  'new' set to `false` due to presence of primary key value.

**Comment by flashios09** [comment]
@ADmad  Even if i passed an array with the **primary key** to the entity like this
```php
$data = [
    'id' => 5,
    'purchase_regime' => 'S',
    'sell_regime' => 'F'
];
$this->Table->newEntity($data, ['validate' => false, 'accessibleFields' => ['*' => true]]);
```
i will always have the **'[new]'** key with **true** value
```php
object(App\Model\Entity\MyEntity) {

	'id' => (int) 5,
	'purchase_regime' => 'S',
	'sell_regime' => 'F',
	'[new]' => true,
	'[accessible]' => [
		'name' => true,
		'purchase_regime' => true,
		'sell_regime' => true,
		'min' => true,
		'by_default' => true,
		'max' => true,
		'state' => true,
		'*' => true
	],
	'[dirty]' => [
		'id' => true,
		'purchase_regime' => true,
		'sell_regime' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Table'

}
```

**Comment by ADmad** [comment]
Apologies, guess my explanation is incorrect. I'll let @markstory or @lorenzo weigh in on this.

**Comment by lorenzo** [comment]
Maybe adding a `markNew` option to the `newEntity()` method could work. I'm not too keen on it, though, since `newEntity()` is meant for creating actually new entities.

**Comment by markstory** [comment]
Why not use patchEntity() if you want to update an existing entity?

**Comment by jhli** [comment]
patchOrNewEntity() ? But I have my douts as I had with findOrCreate().

**Comment by flashios09** [comment]
@markstory Thanks for your reply :)
I didn't understand why i can use the **markNew** option with 
```php
$entity = new Entity($data, ['marknew' => false]);
```
and i can't use it with the **newEntity** method
```php
$Table->newEntity($data, ['markNew' => false]);
```

**Comment by markstory** [comment]
@flashios09 Well `new Entity()` lets you use the constructor options, while `newEntity()` does not. There are separate options for each method, and very few are shared. We don't support the `associated` option in `new Entity()` for example.

Given that we have a patchEntity() method for updating existing entities, why did you want to use newEntity() instead?

**Comment by dereuromark** [comment]
For consistency's sake we could add those 2 lines in the Marshaller if that makes people happy :)

**Comment by flashios09** [comment]
@markstory I created a Versionable Behavior, every time i add or update an entity i save a new Version in a versions table(id, entity_id, model, version_id, json_entity) where json_entity has the content(all fields), then i have a versions action in the controller to get a specific(or all) entity version 
```php
// ArticlesController.php::versions
// Just add the _versions key to the entity 
$article = $this->Articles->get(8, ['fields' => 'id'])->versions();
// or get a specific version(add the _version key to the entity)
$article = $this->Articles->get(8, ['fields' => 'id'])->version(3);
// Now i can format the _version key
// -> extract it then create a new Entity/new Entities from the json_entity key
$version = $article->format();
```
I want just to convert this
```php
object(App\Model\Entity\Article) {
	'id' => (int) 8,
	'_version' => object(Cake\ORM\Entity) {
		'id' => (int) 1,
		'model' => 'Articles',
		'entity_id' => (int) 8,
		'version_id' => (int) 3,
		'json_entity' => [
			'id' => (int) 8,
			'field1' => 'Value1',
			'field2' => 'Value2',
			// Other fields ...
		],
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[repository]' => 'Version.Versions'
	},
	'[new]' => false,
	'[accessible]' => [
		'field1' => true,
		'field2' => true
	],
	'[dirty]' => [
		'_version' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Articles'
}
```
to this:
```php
object(App\Model\Entity\Article) {
	'id' => (int) 8,
	'field1' => 'value1',
	'field2' => 'value2',
	'version_id' => 3
	// Other fields...
	'[new]' => false,
	'[accessible]' => [
		'field1' => true,
		'field2' => true,
		'*' => true
	],
	'[dirty]' => [
		'id' => true,
		'field1' => true,
		'field2' => true,
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Articles'
}
```
After that i can set the version entity(or all the versioned entities) to the view, overwrite the entity 8 in the Articles table with an existing  version in the Versions table.
that's the code of the format method
```php
// VersionTrait::format();
/**
 * Return a formatted entity/entities
 *
 * Create new entity/entities using the _version/_versions key
 * @return entity|entities
 */
public function format(){
    $ver = $this->_extract();

    if(is_null($ver))
        return null;

    // $Entity->versions()->format()
    if(is_array($ver)){
        $model = $ver[0]->model;
        $Table = TableRegistry::get($model);
        $entities = $Table->newEntities(Hash::extract($ver, "{n}.{s}.json_entity"), ['validate' => false, 'accessibleFields' => ['*' => true]]);
        foreach($entities as $key => $entity)
            $entities[$key]->isNew(false);

        return $entities;
    }

    // $Entity->version($version_id)->format()
    $model = $ver->model;
    $Table = TableRegistry::get($model);
    $entity = $Table->newEntity($ver->json_entity, ['validate' => false, 'accessibleFields' => ['*' => true]]);
    $entity->isNew(false);

    return $entity;
}
```
Every time that i want to set ['new'] to false i have to use the isNew method, i don't have an array to patch with an existing entity so i don't need patchEntity. That's why i want to use directly the markNew option with the newEntity method
```php
// From this
$entity = $Table->newEntity($ver->json_entity, ['validate' => false, 'accessibleFields' => ['*' => true]]); $entity->isNew(false);
// To this
$entity = $Table->newEntity($ver->json_entity, ['markNew' => false, 'validate' => false, 'accessibleFields' => ['*' => true]]);
```

**Comment by dereuromark** [comment]
@flashios09 Why don't you make a PR with your suggested change and 1-2 tests? :)
I bet this would get it merged way sooner than discussing it here more.

**Comment by flashios09** [comment]
@dereuromark i don't know how to do a PULL REQUEST :(
I suggest adding this lines to the Marshaller.php::one(line 119):
```php
if (isset($options['markNew'])) {
    $entity->isNew((bool)$options['markNew']);
}
```
It works for me

**Comment by dereuromark** [comment]
Always a first time for everything.
Fork, push the changes to a new branch, and make the PR.

**Comment by flashios09** [comment]
@dereuromark I will try, i have to learn how to create a new branch then push the changes and finally make a PR. 
Thanks

**Comment by markstory** [comment]
Thanks for the additional detail @flashios09. Given that you are turning off most of the features of the marshaller, wouldn't using new be simpler?

I am hesitant to add this option as I don't know if it makes sense given the method name and the intention behind it.

**Comment by flashios09** [comment]
@markstory Sorry i didn't understand your last reply :(
What do you mean by **using new be simpler** and whats **the features of the marshaller that will be turned off**?

**Comment by markstory** [comment]
You've turned off validation, and aren't using any association marshalling. If I'm understanding the code you currently have, it is effectively:

```php
/* This is replaced with the following.
$model = $ver->model;
    $Table = TableRegistry::get($model);
    $entity = $Table->newEntity($ver->json_entity, ['validate' => false, 'accessibleFields' => ['*' => true]]);
    $entity->isNew(false);
*/ 
$model = $ver->model;
$table = TableRegistry::get($model);
$className = $table->entityClass();

$entity = new $className($ver->json_entity, ['markNew' => false]);
```

**Comment by flashios09** [comment]
@markstory Thanks for the ```entityClass()``` method, before i didn't know how to get the entityClass (eg. **App\Model\Entity\Article**), with ```new Entity()``` i loose the entityClass(return **Cake\ORM\Entity**).
I have just another question, to replace the ```$Table->newEntities($array, $options)``` i have to loop the $array and create an entity for each item like this:
```php
if(is_array($ver)){
    $model = $ver[0]->model;
    $Table = TableRegistry::get($model);
    $className = $Table->entityClass();
    $jsonEntities = Hash::extract($ver, "{n}.{s}.json_entity");
    foreach($jsonEntities as $key => $jsonEntity)
    	$entities[$key] = new $className($jsonEntity, ['markNew' => false]);

    return $entities;
}
```
or there is a better solution ?

**Comment by markstory** [comment]
Yes you would need a loop. But you could also extract the common code to get the entity class out of both sides of the conditional.

In either case, I think there are existing options that don't require adding a new option that will likely muddle the differences between updating an existing record and creating new ones.

**Comment by flashios09** [comment]
@markstory I don't think it's possible to extract the common code to get the entity class out of both sides of the conditional.
I have to get the ```$model``` before i do
```php
$Table = TableRegistry::get($model);
$className = $Table->entityClass();
```
If i have ```_version``` key -> the ```$model``` is ```$ver->model```
If i have ```_versions``` key -> the ```$model``` is ```$ver[0]->model```
-> ```'_versions'``` key contain **an array** not **an object** like ```'_version'``` key

How can i get the ```$model``` without testing if the ```$ver``` **is an array or not** !
That's the code of the format method(VersionTrait::format()):
```php
/**
 * Return a formatted entity/entities
 *
 * Create new entity/entities using the '_version'/'_versions' key
 * (!) '_versions' key contain an array not an object like '_version' key
 * @return entity|entities
 */
public function format(){
    $ver = $this->_extract();

    if(is_null($ver))
        return null;

    // $Entity->versions()->format()
    if(is_array($ver)){
        $model = $ver[0]->model;
        $Table = TableRegistry::get($model);
        $className = $Table->entityClass();
        $jsonEntities = Hash::extract($ver, "{n}.{s}.json_entity");
        foreach($jsonEntities as $key => $jsonEntity)
            $entities[$key] = new $className($jsonEntity, ['markNew' => false]);

        return $entities;
    }

    // $Entity->version($version_id)->format()
    $model = $ver->model;
    $Table = TableRegistry::get($model);
    $className = $Table->entityClass();
    $entity = new $className($ver->json_entity, ['markNew' => false]);

    return $entity;
}
```

**Comment by markstory** [comment]
You're right you wouldn't be able to get the modelname without a type check.

Given that there is a good alternative to adding what could be a confusing and inconsistent option, I'm going to close this issue.

**Comment by flashios09** [comment]
@markstory Thanks for all the help, i will finish the Version Package and ask @dereuromark to add it to the https://github.com/FriendsOfCake/awesome-cakephp

**Comment by markstory** [comment]
@flashios09 Awesome :+1:
