### ISSUE TITLE
ResultSet::_calculateColumnMap using wrong association alias

### ISSUE THREAD

**Issue by QuanticPotato** [cakephp/cakephp#6931]
I don't know if it is an expected behavior, but the `ResultSet::_calculateColumnMap()` function creates the `ResultSet::_map` array according to the table alias (if set).

For example, if we consider the table :
```
class CategoriesTable {
    public function initialize(array $config) {
        $this->alias('Foobar');
        // ...
    }
    // ...
}
```
and another table with a `BelongsTo` association :
```
class ItemsTable {
    public function initialize(array $config) {
        $this->belongsTo('Category', [
            'className' => 'Categories'',
            'foreignKey' => 'category_id'
        ]);
    }
    // ...
}
```
Then when `ResultSet` will skip the association ... 
And after a lot of code-browsing I found it was because the `ResultSet::_calculateTypeMap` function has this condition : 
```
if (isset($this->_types[$alias]) || !$assoc['canBeJoined'] || !isset($this->_map[$alias])) {
    continue;
}
```
which would have the values : 
* `$this->_map` : `['Foobar' => ...]`
* `$alias` : `'Category'`

I hope this is not an expected behavior because I'm using table alias because of Table Models in sub directories ... :worried: 

Thanks for your help !

**Comment by lorenzo** [comment]
Than is the expected behavior.  It is usually not very wise to set the table Ali's yourself, but set it in the association definition, the first argument of belongsTo is automatically used as the table alias

**Comment by markstory** [comment]
@lorenzo Should we emit warnings in the alias() method if the alias is being overwritten?

**Comment by lorenzo** [comment]
Yeah, I think that could be a good idea, but not secure where to place the warning

**Comment by markstory** [comment]
Maybe in the alias() method?

**Comment by lorenzo** [comment]
And check in table registry if the alias exists?

**Comment by markstory** [comment]
Maybe, or we could error if alias() is changing the alias from a non-null value.
