### ISSUE TITLE
bin/cake i18n initdb doesn't work on PHP 5.6.10

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#6933]
Hi!

When I'm running bin/cake i18n initdb - only that happens is that the menu for bin/cake i18n opens.

Issue is with Cake v3.0.8

Example on command: 
https://gist.github.com/Spriz/042c52f7cce719d8be85

I'm running PHP 5.6.10
php -v:

https://gist.github.com/Spriz/128133db587bba2a12f0

**Comment by lorenzo** [comment]
Because there is no initdb command. :)

**Comment by ADmad** [comment]
Reopening until the manual page is fixed http://book.cakephp.org/3.0/en/console-and-shells/i18n-shell.html#create-the-tables-used-by-translatebehavior

**Comment by lorenzo** [comment]
Closing as I created a ticket elsewhere :D
