### ISSUE TITLE
[2.x] deep saving cannot handle hasMany validation correctly

### ISSUE THREAD

**Issue by hiromi2424** [cakephp/cakephp#6935]
### Define
A hasOne B hasMany C.

### The Problem
I would like to save A->saveAssociated() with data containing A[B][C][n] records and `'deep' => true` option.
When some records of C raise validation errors, the saveAssociated() actually returned true and records are saved to db.

### Solution
https://github.com/cakephp/cakephp/blob/0b28c2e83959cb6066cca772d9878facd7328947/lib/Cake/Model/Model.php#L2342
(above url relates 2.7 branch commit tree)
This line expected $saved as return of belongsTo And hasOne associations.
I rewrite it to:
`$validates = ($saved === true || (is_array($saved) && !in_array(false, Hash::flatten($saved), true)));`
I replaced `$saved` with `Hash::flatten($saved)` in `in_array()`.
That might cause decrease performance but quite easy to resolve this problem.

I don't have test cases updated yet.
How do you think?

**Comment by hiromi2424** [comment]
This caused at saveMany() too..

**Comment by markstory** [comment]
Closing as there is a pull request open now.
