### ISSUE TITLE
Login Authentication Problem

### ISSUE THREAD

**Issue by nishascorpsoft** [cakephp/cakephp#6936]
I am a new in cake php and i use 3.0 version and i face a issue is that in login I will not redirected to a page which i set in initialize function in app controller and also user is not authenticated .Please help me or give me simple login mvc structre in cake php so i can resolve my problem
url   http://blockhunt.com/newblockhunt/pages/login

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by nishascorpsoft** [comment]
I used this URL for my login module
 The CakePHP Manual



I write a code in a files for Login module I attached this files code
In this files I make a login module in MVC strucure of cake php 3.0 
The issue is that i am not authenticate the user in PagesController but i follow this url of Authentication
http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuring-authentication-handlers



![appcontroller](https://cloud.githubusercontent.com/assets/12963336/8501132/39d86c54-21c0-11e5-9e21-0102defb060a.png)
![loginctp](https://cloud.githubusercontent.com/assets/12963336/8501137/4b756d68-21c0-11e5-852a-0986dbb4b469.png)
![pagescontroller](https://cloud.githubusercontent.com/assets/12963336/8501138/4b7c8238-21c0-11e5-8ac0-f0cb29aab617.png)
![pagestable](https://cloud.githubusercontent.com/assets/12963336/8501139/4b86ffe2-21c0-11e5-89b7-216ca90cd387.png)

**Comment by ADmad** [comment]
@nishascorpsoft Post your question on stackoverflow or ask on IRC channel. As stated earlier this is not a help forum.
