### ISSUE TITLE
Inflector doesn't work well with "address(es)"

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#6941]
See http://sandbox3.dereuromark.de/sandbox/inflector?string=Address

```
Method	Result
pluralize	=>	Addresses
singularize	=>	Addres
camelize	=>	Address
underscore	=>	address
dasherize	=>	address
humanize	=>	Address
delimit	=>	address
tableize	=>	addresses
classify	=>	Addres
slug	=>	Address
```

This caused me some headache when trying to work with a fixture and table object for the "addresses" table...

**Comment by ADmad** [comment]
Singularizing an already singular word has never worked perfectly. I don't think we should strive to achieve it either.

What exactly were you trying to do?

**Comment by burzum** [comment]
Well, just create an addresses table and bake "all".

I agree that this won't ever work perfectly or cover all cases, but at least the English ones should work more or less OK and it's not like "addresses" is an uncommon name for a table unlike some others I see in the tests.

Already trying to fix it but struggle with the regex.

**Comment by ADmad** [comment]
This issue has come up before. The fix needs to be done in piece of code that is trying to singularize already singular string not the inflector imo.

**Comment by burzum** [comment]
Any idea how to work around that? The problem is this screws almost everything up around "addresses"?

```
 Class 'App\Model\Table\AddressTable' not found in C:\xampp\htdocs\wa-crm\vendor\cakephp\cakephp\src\ORM\Locator\TableLocator.php on
```

* Fixture file
* Fixture name
* Table class name
* Table name in the db
* Entity association property names
* ...

It's pretty annoying and blocking me from getting the tests to run without fixing almost everything above.

**Comment by jhli** [comment]
I'd love to see MVC yo use plural all the way and just the flas/validation messages and /templates to use the Inflector.

**Comment by ADmad** [comment]
@jhli Only entity class names and foreign key field names are singular as naming name as plurals would not be logical.

**Comment by ADmad** [comment]
I had made an RFC to name foreign key fields too using plural table name to avoid inflections but it was rejected.

**Comment by ionas** [comment]
Ref: https://github.com/cakephp/cakephp/issues/4738

**Comment by ionas** [comment]
114 "Inflector" tickets: https://github.com/cakephp/cakephp/issues?q=Inflector
101 "Plural" tickets: https://github.com/cakephp/cakephp/issues?q=Plural
75 "Singular" tickets: https://github.com/cakephp/cakephp/issues?q=Singular

So why not switch ```Inflector``` and a new ```SingularInflector``` around (```Configure::```, defaulting to ```SingularInflector```) to remove the dependency of pluralization and singularization for all but representational strings (messages, e.g.validation, flash and view templates, etc.)?

**Comment by dereuromark** [comment]
The inflection is only for conventional approaches, if you customize the foreign keys there is no inflection afaik. Thus is not really an issue, is it?

**Comment by ADmad** [comment]
@ionas Let's stay on topic here. This issue is not about changing the inflection conventions. Just fixing a particular error.

**Comment by markstory** [comment]
Address is one of the many problematic words in english as it looks like a plural and a singular at the same time. We could always throw it in the irregular list and call it a day :smile:

**Comment by markstory** [comment]
Worked fine for me:

```
$ bin/cake bake all addresses

Welcome to CakePHP v3.0.8 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
---------------------------------------------------------------
Bake All
---------------------------------------------------------------
One moment while associations are detected.

Baking table class for Addresses...

Creating file /Users/markstory/Sites/cakephp-app/src/Model/Table/AddressesTable.php
Wrote `/Users/markstory/Sites/cakephp-app/src/Model/Table/AddressesTable.php`
Deleted `/Users/markstory/Sites/cakephp-app/src/Model/Table/empty`

Baking entity class for Address...

Creating file /Users/markstory/Sites/cakephp-app/src/Model/Entity/Address.php
Wrote `/Users/markstory/Sites/cakephp-app/src/Model/Entity/Address.php`
Deleted `/Users/markstory/Sites/cakephp-app/src/Model/Entity/empty`

Baking test fixture for Addresses...

Creating file /Users/markstory/Sites/cakephp-app/tests/Fixture/AddressesFixture.php
Wrote `/Users/markstory/Sites/cakephp-app/tests/Fixture/AddressesFixture.php`
Deleted `/Users/markstory/Sites/cakephp-app/tests/Fixture/empty`
Bake is detecting possible fixtures...

Baking test case for App\Model\Table\AddressesTable ...

Creating file /Users/markstory/Sites/cakephp-app/tests/TestCase/Model/Table/AddressesTableTest.php
Wrote `/Users/markstory/Sites/cakephp-app/tests/TestCase/Model/Table/AddressesTableTest.php`

Baking controller class for Addresses...

Creating file /Users/markstory/Sites/cakephp-app/src/Controller/AddressesController.php
Wrote `/Users/markstory/Sites/cakephp-app/src/Controller/AddressesController.php`
Bake is detecting possible fixtures...

Baking test case for App\Controller\AddressesController ...

Creating file /Users/markstory/Sites/cakephp-app/tests/TestCase/Controller/AddressesControllerTest.php
Wrote `/Users/markstory/Sites/cakephp-app/tests/TestCase/Controller/AddressesControllerTest.php`

Baking `index` view file...

Creating file /Users/markstory/Sites/cakephp-app/src/Template/Addresses/index.ctp
Wrote `/Users/markstory/Sites/cakephp-app/src/Template/Addresses/index.ctp`

Baking `view` view file...

Creating file /Users/markstory/Sites/cakephp-app/src/Template/Addresses/view.ctp
Wrote `/Users/markstory/Sites/cakephp-app/src/Template/Addresses/view.ctp`

Baking `add` view file...

Creating file /Users/markstory/Sites/cakephp-app/src/Template/Addresses/add.ctp
Wrote `/Users/markstory/Sites/cakephp-app/src/Template/Addresses/add.ctp`

Baking `edit` view file...

Creating file /Users/markstory/Sites/cakephp-app/src/Template/Addresses/edit.ctp
Wrote `/Users/markstory/Sites/cakephp-app/src/Template/Addresses/edit.ctp`
Bake All complete.
:) 20:18:16 markstory:cakephp-app (master)
:) 20:19:51 markstory:cakephp-app (master)
$ vendor/bin/phpunit tests/TestCase/Model/Table/AddressesTableTest.php
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

II

Time: 214 ms, Memory: 9.50Mb

OK, but incomplete, skipped, or risky tests!
Tests: 2, Assertions: 0, Incomplete: 2.
:) 20:19:55 markstory:cakephp-app (master)
```

I was using the cakephp 3.0.8 and bake 1.0.10
