### ISSUE TITLE
Text::autoLink generate error link

### ISSUE THREAD

**Issue by lequy1010** [cakephp/cakephp#6945]
Dear sir,
I'm using TextHelper (cakephp 2.6.7) for auto detecting url in content
in view i use: $this->Text->autoLink($content, array('escape' => false));
i have 3 links in content, 2 links are ok, 1 link is wrong
this is url that i want to say [http://rao5s.vn/4748-0-may-do-ph-cam-tay-hanna-hi-8424.html]
i has attach 2 images(evidence site and text that stored in database), please see it!
![url](https://cloud.githubusercontent.com/assets/7949193/8506027/3498934a-2229-11e5-806d-e6677c77364b.PNG)
![database](https://cloud.githubusercontent.com/assets/7949193/8506032/8ea75ac4-2229-11e5-8c26-68a094a95f70.PNG)

**Comment by dereuromark** [comment]
Looks like the following `<br>` tag is sucked into it.

**Comment by tanuck** [comment]
@dereuromark wouldn't TextHelper::autoParagraph() have to be used in order to insert the `<br>` tag?

**Comment by dereuromark** [comment]
It is not about inserted. Those tags are already there.
I wonder why it contains HTML, though, and the html => true option is not bveing used.
That might fix the issue, because without that it tries to see the text as non-HTML.

**Comment by lequy1010** [comment]
@tanuck @dereuromark  that's right, i have use nl2br() function to insert <br> tag into content 
but if i don't use nl2br() function then looks it is tangled
![nb](https://cloud.githubusercontent.com/assets/7949193/8536123/16f60c50-2477-11e5-94d4-1ae21a77f79c.PNG)

**Comment by lequy1010** [comment]
I think in _linkUrls() function should remove all html tags from the url
and then return url

**Comment by markstory** [comment]
@lequy1010 Have you tried using the `html => true` option? That generally helps solve links being incorrectly generated when HTML input is involved. Alternatively, you could nl2br() the linked text.

We cannot simply remove HTML from URLs, as many things that _look_ like HTML are ok in URLs. For example `http://example.com/some<text>here.html` could be a valid URL.

**Comment by dereuromark** [comment]
You must either use nl2br() after the autoLink() call, or make autoLink() aware of HTML using the option I mentioned above which is also documented.

**Comment by lequy1010** [comment]
@dereuromark  @markstory  thank you for answer,
I have try idea of you but can not solve it
          <?php
            $auto_link = $this->Text->autoLink($content, array('html' => true, 'escape' => false));
            echo nl2br($auto_link);
            ?> 
and that is result after i use bottom source(have not solve it yet)
[http://rao5s.vn/4748-0-may-do-ph-cam-tay-hanna-hi-8424.html]

**Comment by markstory** [comment]
@lequy1010 Could you paste a plain text copy of the relevant text in this issue? I'd like to try and reproduce the issue, but the screen shots don't have enough information.

**Comment by lequy1010** [comment]
@markstory ok you,
here is raw content that visitor have posted from input form
-----
Máy đo pH cầm tay Hanna Hi 8424 Hãng sx: Hanna - USA Sản xuất tại Rumani Máy HI 8424 máy đo pH phổ biến trên thị trường, máy có chức năng đo pH, ORP, nhiệt độ với độ chính xác cao và cho kết quả phản hồi nhanh. Máy được thiết kế nhỏ gọn, an toàn và dễ sử dụng… - Khoảng đo pH: -2.00 to 16.00 pH - Khoảng đo ORP: ±699.9 mV; ±1999 mV - Khoảng đo nhiệt độ: -20.0 to 120.0 oC / -4.0 to 248.0 oF - Độ phân giải: 0.01 pH / 0.1 mV; 1 mV / 0.1oC / 0.1oF - Độ chính xác: ±0.01 pH / ±0.2 mV; ±1 mV / ±0.4oC / - Hiệu chuẩn tự động 1 hoặc 2 điểm với 3 giá trị buffer được nhớ (4.01, 7.01 và 10.01) - Bù nhiệt tự động -20 to 1200C (-4 to 2480F) - Pin: 9V / sử dụng gần 150 giờ liên tục; auto-off sau 20 phut không sử dụng - Cung cấp bao gồm: Máy đo pH HI 8424, đầu dò pH HI 1230B, đầu dò nhiệt độ HI 7662, dung dịch hiệu chuẩn HI 70004 pH 4.01 và HI 70007 pH 7.01, dung dịch rửa điện cực HI 700661, pin, hộp cứng và hướng dẫn sử dụng. Liên hệ: Phòng kinh doanh (Điện thoại : 04 62855023 / 04 62650050) CÔNG TY TNHH CÔNG NGHỆ MAI VŨ (MVTEK) Địa chỉ : P.201, Nhà B6C, KĐT Nam Trung Yên, Đường Nguyễn Chánh, Cầu Giấy, Hà Nội Email: info@mvtek.vn- Hotline : 091 704 5555 Website: www.mvtek.vn - www.maivu.vn - www.thietbikythuat.net	Kho hàng HCM : Lô P27, đường E2, Khu TĐC 38ha, P. Tân Thới Nhất, Q. 12, HCM. Tìm kiếm: Máy đo pH, Máy định vị GPS, Thước cặp điện tử, Thước cặp cơ, Thước panme, Dưỡng đo lỗ, Máy đo cường độ ánh sáng, Đồng hồ vạn năng, Máy đo pH đất, Máy đánh sọc inox, máy đo khoảng cách, máy đo góc nghiêng, máy cân mực laser, máy chiếu, máy scan, máy in, máy photocopy, thước lá
----

**Comment by markstory** [comment]
@lequy1010 That content doesn't have any newlines, should it?

**Comment by lequy1010** [comment]
@markstory  that's right,
that content is a free style of visitor that they input and submit from form
and then in view, i use nl2br() function to add newline for it

**Comment by dereuromark** [comment]
It should still contain newlines, even though "invisible" to you directly. Your pasted code does not.

**Comment by markstory** [comment]
Without the text content that is causing the issue, I don't think I'll be able to solve this. I tried the following, which worked fine.

```php
public function testAutoLinkNewlines() {
	$text = "Some text www.example.net\nmore text";
	$result = $this->Text->autoLink($text);
	$expected = "Some text <a href=\"http://www.example.net\">www.example.net</a>\nmore text";
	$this->assertEquals($expected, $result);

	$text = "Some text www.example.net<br>more text";
	$result = $this->Text->autoLink($text, array('escape' => false));
	$expected = "Some text <a href=\"http://www.example.net\">www.example.net</a><br>more text";
	$this->assertEquals($expected, $result);
}
```

**Comment by lequy1010** [comment]
in fact, in content that i have show it's have issues
I think the ability is have a issues in content

**Comment by markstory** [comment]
@lequy1010 I'm not trying to refute that you are having an issue. However, without the content that _causes_ the issue I cannot reproduce the issue and therefore cannot fix the issue.

**Comment by markstory** [comment]
@lequy1010 I still don't know how to reproduce this error. Is there a way you could send us even a section of the problematic input?

**Comment by HavokInspiration** [comment]
What about a non breaking space ? (Cmd Shift Space on a Mac I believe)
I can't find a way to do one on my Ubuntu but could that cause problems ?

**Comment by lequy1010** [comment]
@markstory 
i have not solve it yet,
have a the post same issues
http://rao5s.vn/5805-0-khong-khi-mat-lanh-canh-sac-da-lat.html
you can think about what can become reason ?

**Comment by lequy1010** [comment]
@markstory 
this is it's content that store in db,
i copy it from db as bellow

ĐÀ LẠT – THÀNH PHỐ  NGÀN HOA
Chi tiết: www.anhduongtourist.vn
===================================
Tìm một nơi nào đó có để thay đổi bầu không khí sau những ngày làm việc và mở rộng tầm nhìn về sự giàu có của thiên nhiên. Đà Lạt là điểm du lịch nổi tiếng sẽ cho bạn những trải nghiệm mới…
----------------------------------------------------
GIÁ TOUR TRỌN GÓI (ÁP DỤNG CHO ĐOÀN TỪ 40 KHÁCH TRỞ LÊN):
*  Khách sạn 2 sao:  1.250.000 VNĐ/ Khách
* Khách sạn 3 sao:  1.450.000 VNĐ/ Khách
=============================
THÔNG TIN LIÊN HỆ:
CÔNG TY TNHH DV DU LỊCH ÁNH DƯƠNG
Địachỉ: 52, Đường 7A, CưXáBìnhThới, Phường 8, Quận 11, TpHcm
Emai: lethu@anhduongtourist.vn – lethu1971anhduongtourist@gmail.com
Điệnthoại: 0918 56 2299 (Mrs Thu)
Website: www.anhduongtourist.vn

**Comment by markstory** [comment]
Thanks @lequy1010

**Comment by markstory** [comment]
That input still doesn't trigger the issue for me locally. Running the above through autoLink() yields:

```
ĐÀ LẠT – THÀNH PHỐ  NGÀN HOA
Chi tiết: <a href="http://www.anhduongtourist.vn">www.anhduongtourist.vn</a>
===================================
Tìm một nơi nào đó có để thay đổi bầu không khí sau những ngày làm việc và mở rộng tầm nhìn về sự giàu có của thiên nhiên. Đà Lạt là điểm du lịch nổi tiếng sẽ cho bạn những trải nghiệm mới…
----------------------------------------------------
GIÁ TOUR TRỌN GÓI (ÁP DỤNG CHO ĐOÀN TỪ 40 KHÁCH TRỞ LÊN):
*  Khách sạn 2 sao:  1.250.000 VNĐ/ Khách
* Khách sạn 3 sao:  1.450.000 VNĐ/ Khách
=============================
THÔNG TIN LIÊN HỆ:
CÔNG TY TNHH DV DU LỊCH ÁNH DƯƠNG
Địachỉ: 52, Đường 7A, CưXáBìnhThới, Phường 8, Quận 11, TpHcm
Emai: <a href="mailto:lethu@anhduongtourist.vn">lethu@anhduongtourist.vn</a> – <a href="mailto:lethu1971anhduongtourist@gmail.com">lethu1971anhduongtourist@gmail.com</a>
Điệnthoại: 0918 56 2299 (Mrs Thu)
Website: <a href="http://www.anhduongtourist.vn">www.anhduongtourist.vn</a>
```
Which does not include an `<br>` elements inside the href attributes.
