### ISSUE TITLE
Where clause breaking query on case sensitive mySQL instances

### ISSUE THREAD

**Issue by danglee** [cakephp/cakephp#6950]
When creating a where clause that looks like this, it will not run on a case sensitive mySQL instance:

$this->Bars->find()->where(['Bars.open - Bars.close' => 0])

This fails as it queries as " ... WHERE Bars.open - bars.close .... "

Note that ->order(['Bars.open - Bars.close']) does not have this issue

**Comment by markstory** [comment]
Condition keys should generally not contain SQL expressions. It not only has issues with case-sensitive configurations, but also fails when identifier quoting is enabled/required. Instead you should be using expression objects:

```php
$this->Bars->find()->where(function($exp) {
  return $exp->add('Bars.open - Bars.close = 0');
});
```

Expression objects are not quoted or manipulated by the `IdentifierQuoter` so if you require that feature you will need to quote identifiers manually.
