### ISSUE TITLE
targetForeignKey in belongsToMany should default based on className

### ISSUE THREAD

**Issue by danglee** [cakephp/cakephp#6951]
When creating an association, the default 'targetForeignKey' to create the join should be based on the className (therefore statement_id) instead of invoice_id. Currently we have to add 'targetForeignKey' => 'statement_id' to make this work.

    $this->addAssociations([
			'belongsToMany' => [
				'Statements',
				'Invoices' => [
					'className' => 'Statements',
					'conditions' => ['Invoices.type' => 'I']
				],
				'Quotes' => [
					'className' => 'Statements',
					'conditions' => ['Quotes.type' => 'Q']
				]				
			]		
    ]);

**Comment by Tzaoh** [comment]
Hello @danglee,
Similar problem was already reported and closed here #6837 (and even before #6539). If I did not forget it, it was taking the table name (through table() function)

**Comment by markstory** [comment]
Closing this as changing the conventions is painful, and some group is always upset with the changes.
