### ISSUE TITLE
Cake3 Feature: Automagic postLinks on open FormHelper forms

### ISSUE THREAD

**Issue by sarrala** [cakephp/cakephp#6953]
Currently there's that block option for postlinks, I don't have anything against it but it would be great if you don't need to give any options for postlinks that goes inside form.

Could it be done with internal state that tells if form is open when ::postLink is called and postLinks forms would then be automagically put on queue. FormHelper::end() could then write that queue out.

```
1. FormHelper::create() {
    form_open = true
}

2. FormHelper::postLink(): 
     form_open === true
         ? output link WITHOUT hidden form
         : output postlink normally.
}

3. FormHelper::end() { 
    close form
    output all hidden forms created while form was open.
}
```

What do you think about it?

**Comment by dereuromark** [comment]
I think it could make sense to have some state check.
Would it even be useful to throw an exception if you try to use create() a second time without closing the form first? Or is that a use case that could actually be valid, form in form?

**Comment by sarrala** [comment]
@dereuromark 

Form element is not valid inside another form.
http://www.w3.org/TR/html5/forms.html#the-form-element
http://www.w3.org/TR/html4/interact/forms.html#h-17.3
http://www.w3.org/TR/xhtml1/#prohibitions

It would make sense to check that.

**Comment by ADmad** [comment]
@sarrala The suggestion is to output those hidden form tags __after__ closing the primary form.

**Comment by sarrala** [comment]
@ADmad yes, hidden forms should be flushed out just after main form's closing tag. Just as you probably would do with postlinks "block" option. I do also feel that this magic would be good as some browsers (chrome at least) refuses to submit nested forms.

So this magic would not steal your code, if someone still really want to make nested forms (maybe as protest or just being evil) he could still do that with block (controlled buffering) option.

This also should not change behavior if another form is not already open when calling postLink. Only between ::create and ::end.

**Comment by markstory** [comment]
'Magic' features have generally been problematic in the past. Given that this feature makes 2 different methods (postLink(), and end()) behave totally different based on source order and no additional parameters, makes me believe that this would ultimately be a confusing feature.

By simply refactoring code, the generated HTML could be totally different, and that isn't something I think anyone would initially expect.

**Comment by ADmad** [comment]
I agree with @markstory.

**Comment by sarrala** [comment]
@markstory 

Maybe you are right, it could be confusing.

And while I mostly think about fixing invalid markup, then after all that's also app developers responsibility.

Now I understand why this change would cause problems too, maybe someday there's a way to fix this without confusing others. Or maybe it won't really need any fixing.

**Comment by sarrala** [comment]
And then about throwing exceptions like @dereuromark suggested could possibly break someones code as it seems that people will nest forms and then they'll be creative with different workarounds to keep their forms submitting something. (googling revealed that web is also full of questions like Nested form work-around?)

Of course throwing exception would not be as confusing as auto-buffering and would force valid html otuput from FormHelper, but then comes that question: Do we want valid code or do we want code that user asks.

I think that ultimately it would be whatever users asks. Also I used to think that with cake 2 there was too many restrictions around things you'll use.

**Comment by markstory** [comment]
@sarrala When I use libraries, I prefer ones that allow me to understand/guess the output based on the code that I wrote.

If developers ask for incorrect html that's what they should get. Silently attempting to massage the user's intent has always gone wrong eventually when we've done it in the past.

**Comment by sarrala** [comment]
@markstory Agreed and case closed. Ultimately it will be best to get consistent output even if it won't follow some external specifications.
