### ISSUE TITLE
Magic Loading of Javascript files

### ISSUE THREAD

**Issue by nycomar** [cakephp/cakephp#6954]
I have never contributed to CakePHP before, but I created a functionality within my Cake Projects that I think might be useful for the community.

Basically, in Cake 3.0, in my AppView file, I've added functionality that automatically loads javascript files, if they exist in the /js folder with the proper folder structure that I created.

Basically, I wanted the ability to have a certain javascript file loaded accross every action in a controller, but no in any other controller.

But then I wanted to have a javascript file loaded for every individual action only, and then a separate one for every view that the action uses (in case a certain action loads a different view based on certain parameters).

And then, I had an element that required a certain javascript file, so I added functionality to auto-load that file so that I wouldn't have to manually add it into my element.

I eventually added this functionality to all my projects to make it a lot easier for me to just drop my custom js files into the appropriate folders, naming them appropriately as well, and they would get auto loaded.

The folder structure is as follows:
```
/js
    /c
        lowercase_underscored_controller_name/
            action_name.js
        lowercase_underscored_controller_name.js
    /v
        lowercase_underscored_controller_name/
            view_name.js
    /e
        element_name/
            element_file.js
```

So the action_name.js is the file that loads for that action regardless of view.
The view_name.js is the file that loads for that view regardless of the action
The element_file.js is the file that loads for that element file. I only tested this with Flash/Success so the folder structure for that would be webroot/js/e/flash/success.js

I've created the functionality by extending the View and overloading the functions, however, in order to contribute to the project, I've cloned the cakephp repo and modified the functions in View, and I intend to push my changes to the repo.

Again, since this is my first time, please be gentle if I'm doing anything wrong. I tried my best to follow the contirbution guide.

**Comment by josegonzalez** [comment]
@omarbutt I've sen this sort of feature in the past, and think it would be best sorted in a community plugin - not everyone will follow this convention for loading js files. Others might disagree, but that's my initial thought.

Note: I first saw this around 2009 in a bakery post by @predominant. It was in an element if I recall correctly :)

**Comment by omarbutt** [comment]
@josegonzalez Thanks for the insight.

Yes, I agree, I'm not sure if the everyone would follow this convention. However, I've already put in the pull request, so I guess we'll see how it goes. I don't mind changing the folder structure however, as long as the auto-magic loading still occurs.

The way I see it, if you don't wish to auto load this way, then that is why I made the folder structure organized in that way, so that files won't get auto-loaded by accident. If you don't want them auto-loaded, you can still load them the old way and not put them in that folder structure.

**Comment by sarrala** [comment]
This kind of feature would be very nice but I think that this feature should also go into "Don't hurry, Think twice"-category.

As a side note: I've been thinking about hiding js under template directory, this would be more complex and would require additional download handler but would also force consistent directory structures and would open a lot more cake stuff for js control.

**Comment by rchavik** [comment]
This is a nice feature. However, these days I usually use a build tool to compile/minify/combine javascript files.

**Comment by ADmad** [comment]
I too think this belongs in a community plugin not in core. Also if one follows such structure combining them for production use becomes a must.

**Comment by burzum** [comment]
Yes, it should be a community plugin.

We changed from the proposed way of loading JS files to compiling it into a single or just a few files as well using Robo for that task.

**Comment by dereuromark** [comment]
Closing as multiple people confirm that this should be a plugin solution to opt-in for those who want to use this feature.
