### ISSUE TITLE
Cake 3.x : Error Logging, disable Exception Attributes. 

### ISSUE THREAD

**Issue by micha3lbrown** [cakephp/cakephp#6957]
Regardless of debug condition, exception attributes are always shown in the error log. 

Recreating:
* debug => true or false
* request invalid route (e.g. '/derp' throws MissingControllerException)
* check error log, no way to disable Exception Attributes
 
``` 
Exception Attributes: array (
  'class' => 'Derppppp',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)  
```
There is a toggle for disabling stack trace, but not for any of the other data.

**Comment by ADmad** [comment]
I doubt there might be many who want to hide those attributes. What you want can be easily achieved by using custom error handle and overriding `BaseErrorHandler::_getMessage()`, so I am not in favor of adding any more switches.

**Comment by micha3lbrown** [comment]
The problem I ran into on a production push was a huge error log from old routes and crawlers. 
```
$debug = Configure::read('debug');
 if (method_exists($exception, 'getAttributes') && $debug) {
            $attributes = $exception->getAttributes();
            if ($attributes) {
                $message .= "\nException Attributes: " . var_export($exception->getAttributes(), true);
            }
        }
```

This change works for me and allows me to have a much better perspective on what is failing, and what is just outdated information.

**Comment by lorenzo** [comment]
I think it may be a good idea to change the information that is logged on the files, it is too verbose now

**Comment by markstory** [comment]
I'm happy to take out exception attributes in non-debug modes.

**Comment by markstory** [comment]
#6959 is open now.
