### ISSUE TITLE
Argument 1 passed to Cake\ORM\Query::addDefaultTypes() must be an instance of Cake\ORM\Table

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#6958]
I'm getting this for some reason when I include the `Tags` in my contain. This association is automatically created by @jadb [Tags plugin](https://github.com/UseMuffin/Tags).

```
Argument 1 passed to Cake\ORM\Query::addDefaultTypes() must be an instance of Cake\ORM\Table, instance of Cake\ORM\Association\HasMany given, called in C:\xampp\htdocs\crm\vendor\cakephp\cakephp\src\ORM\Association\BelongsToMany.php on line 960
```

I've realized that this started happening after updating the core of my project. The change from 3.0.6 => 3.0.7 is causing the notice. The problem can be solved by reverting this commit 46c3106694424ea2d00a1d57f5ff58fbef4785b3 of CakePHP. Actually reverting the single change in ORM/Association/BelongsToMany.php is fixing this for me.

```php
->addDefaultTypes($assoc->target())
```

I'm not yet sure if this is a regression of https://github.com/cakephp/cakephp/issues/6775 and if we have to change the behavior or the core.

Original issue report: https://github.com/UseMuffin/Tags/issues/13

**Comment by markstory** [comment]
I wonder if the Tags plugin is generating associations incorrectly, as the target() method of an association should return a table, not another association.

**Comment by burzum** [comment]
@markstory I don't see anything strange here and it was working before.

https://github.com/UseMuffin/Tags/blob/master/src/Model/Behavior/TagBehavior.php#L88

**Comment by markstory** [comment]
Sure but before the types weren't being mapped, and thus custom datatypes were broken. I'm not saying there isn't a problem here, I just think the issue is in the Tags plugin. For example, [this line](https://github.com/UseMuffin/Tags/blob/master/src/Model/Behavior/TagBehavior.php#L116) looks suspect, and is likely to be passing an association object and not a table.
