### ISSUE TITLE
js as built in request detector 

### ISSUE THREAD

**Issue by leighmackay** [cakephp/cakephp#6962]
Hello,

I'm still returning eval'd JavaScript in my apps and hoping I'm not the only one. All of them have this in the app controller initialize method.

```
 Request::addDetector(
          'js', [
            'env' => 'HTTP_ACCEPT', 
            'pattern' => '/application\/javascript/i'
           ]
   ); 
```

Maybe this should be a default detector.

My real issue is Cake is so awesome at eval'd javascript and doing that makes it hurt a little bit.

Everything else is really great, load the RequestHandler component, enable js extension in routes, create a new layout js/default.ctp it's just perfect, Cake even moves the view path /js/add.ctp and changes the response type, but then... in the App Controller we need to add that.

Cake 3 is so darn awesome, it makes me happy everyday and I can live with this not being added, but just thought I'd say something and maybe other people feel that same..

**Comment by markstory** [comment]
The code you've pasted looks simple enough to include in the applications that need it. Why does it _need_ to be in the default app skeleton?

**Comment by ADmad** [comment]
I doubt dynamically generating js is that common. Like @markstory said it's simple enough to add just a single statement to your apps.

**Comment by leighmackay** [comment]
@markstory It's friends are in there "ajax",  "json" and "xml". jQuery allow you to send (xml, json, script, or html) they treat it as an equal. Feels like it's missing, I'm hoping other people feel the same way.

@ADmad It's used in many frameworks and I've seen this technique used in Cake and blogged about since 1.3.

You are both right that Cake makes what I'm doing pretty darn easy and maybe it's just me :D

**Comment by ADmad** [comment]
> since 1.3

The web dev best practices has come a long way since Cake 1.3 :)  These days the suggested practice is to just return json from server and decorate it as required for representation on client side.

**Comment by leighmackay** [comment]
Cake has the most amazing view layer I've ever seen, it's a masterwork. If Cake just becomes an json API that is the saddest thing I've ever heard :(

**Comment by ADmad** [comment]
> If Cake just becomes an json API that is the saddest thing I've ever heard :( 

No one said that :)  What you want can be achieved by adding a single statement in your app.

**Comment by leighmackay** [comment]
Just giving an example of this technique.

https://gist.github.com/leighmackay/c2df6218bfc3d36d5b03

This is from jQuery.ajax() manual
dataType (default: Intelligent Guess (xml, json, script, or html))

I use "json", "script" and "html" in my ajax requests and "script" is the only one I need to add a detector for.

@ADmad Admad yes it's very easy to add the Detector and Cake makes doing this a snap anyway, I'm fine with it not being added.

**Comment by markstory** [comment]
Closing then as this is a pretty simple one time modification to an application for those who need it.
