### ISSUE TITLE
extractOriginalChanged on entity does not return null values when changed

### ISSUE THREAD

**Issue by blieb** [cakephp/cakephp#6966]
When I do extractOriginalChanged() on an entity I never gets the old values when the old value was NULL. I think it should always return the field, even when the value is NULL.

I've checked the code, and I think that $original should not be checked for null on line 566 at http://api.cakephp.org/3.0/source-class-Cake.Datasource.EntityTrait.html#_extractOriginalChanged

**Comment by markstory** [comment]
That seems reasonable, I can see if that causes any existing tests to fail.

**Comment by markstory** [comment]
Pull request up now.
