### ISSUE TITLE
FormHelper - Textarea fail

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#6967]
Hey guys,

Just noticed the following:

When calling 
``` 
$this->Form->textarea('notes');
```
I get the following:
![image](https://cloud.githubusercontent.com/assets/5465074/8556449/53f8f66e-24f7-11e5-8a88-a187d60d6092.png)

But, when calling it with:
```
$this->Form->input('notes', [
     'type' => 'textarea'
])
```
I get the following:
![image](https://cloud.githubusercontent.com/assets/5465074/8556434/3cd37ab8-24f7-11e5-9d7e-7c3bc3e2c584.png)

I suggest the second image is right ;)

**Comment by ADmad** [comment]
FormHelper::textarea() will generate ONLY the textarea and nothing else.
