### ISSUE TITLE
Inconsistent accessibility of _joinData

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/cakephp#6971]
I'm using `_joinData` to save some data along with relations. When creating a new item, a new record is created in the join table and the join data is saved correctly as well. When updating an item, I'm able to update the join data for existing relations as well. But when creating new relations for an existing item, the relation is created with no join data.

I checked the entity in the `beforeSave` all situations, and the problem seems to be the accessibility of `_joinData`. It's accessible when:
- Adding new relation to new item
- Updating relation to existing item

But not when:
- Adding a new relation to an existing item

It can be solved by marking `_joinData` as accessible. But it could be something to look at, since it's fairly inconsistent in my opinion.

**Comment by ADmad** [comment]
Please provide example to reproduce the issue.

**Comment by GuidoHendriks** [comment]
Quick example, please let me know if it’s enough. Here are the relevant parts of my models:

**ProductsTable.php**
```
class ProductsTable extends Table
{
    public function initialize(array $config)
    {
        $this->table(‘products’);
        $this->belongsToMany(‘CategoryProperties’, [
            ‘foreignKey’ => ‘product_id’,
            ‘targetForeignKey’ => ‘category_property_id’,
            ‘joinTable’ => ‘category_properties_products’
        ]);
    }
}
```

**CategoryPropertiesTable.php**
```
class CategoryPropertiesTable extends Table
{
    public function initialize(array $config)
    {
        $this->table(‘category_properties’);
        $this->belongsToMany(‘Products’, [
            ‘foreignKey’ => ‘category_property_id’,
            ‘targetForeignKey’ => ‘product_id’,
            ‘joinTable’ => ‘category_properties_products’
        ]);
    }
}
```

Now this happens when creating / patching the entities:

```
$product = $this->Products->newEntity([
    ‘name’ => ‘Foo’,
    ‘price’ => 123,
    ‘category_properties’ => [
        [
            ‘id’ => 1,
            ‘_joinData’ => [
                ‘value’ => ‘foo’
            ]
            // Added like it should. :)
        ]
    ]
]);

$this->Products->patchEntity($product, [
    ‘name’ => ‘Foo’,
    ‘price’ => 123,
    ‘category_properties’ => [
        [
            ‘id’ => 1,
            ‘_joinData’ => [
                ‘value’ => ‘foo-123’
            ]
            // Updated like it should. :)
        ],
        [
            ‘id’ => 3,
            ‘_joinData’ => [
                ‘value’ => ‘foo’
            ]
            // Added without the join data… :(
        ],
    ]
], [
    ‘associated’ => [‘CategoryProperties._joinData’]
]);
```

**Comment by markstory** [comment]
Thanks, I was able to reproduce this and will have a fix soon.

**Comment by markstory** [comment]
Pull request open now.
