### ISSUE TITLE
unbindModel in neighbors

### ISSUE THREAD

**Issue by Valonix** [cakephp/cakephp#6974]
$this->Company->unbindModel(array('hasMany' => array('Like')));
$neighbors = $this->Company->find(
     'neighbors',
     array(
             'field' => 'number', 'value' => $company['Company']['number'])
            );

after in neighbors i have fields from related Model. How to unbindModel ?

**Comment by dereuromark** [comment]
Please read the docs regrading unbindModel(() and the 2nd param which needs to be set to false to not reset.
