### ISSUE TITLE
jointable not found when using additional datasource

### ISSUE THREAD

**Issue by brandher** [cakephp/cakephp#6978]
Hi there,

I prefer to us a separate database for user handling(registration, passwords, roles and permissions).
SO my application data is in the default database connection and my user realted tables are in the 'appuser' datasource.

I added:

	public static function defaultConnectionName() {
		$result = Configure::read('MyConf.userDatabase');
		return $result;
	}
to my table classes to use the correctdaatsource forthese tables.

but the problem is that cakephp will not find
'joinTable' => 'users_roles'

any idea how to solve that?
Is this a feature request?

I appreciate any help.

regards

Herbert

**Comment by lorenzo** [comment]
In what database is the `users_roles` table?

**Comment by brandher** [comment]
Hi, as usual the fact is: good questions are better, than answers.

the users_roles table is defined in the 'appuser' datasource, since it belongs to users data.

Usually you do not have to define the tables which are used for the many-2-many relationships in the application.

I did it right now. and its working perfectly.

thx for giving me the hint

**Comment by lorenzo** [comment]
no problem!
