### ISSUE TITLE
timeAgoInWords() sometimes doesn't include the 'ago' word

### ISSUE THREAD

**Issue by hakermania** [cakephp/cakephp#6980]
I noticed that while using the `timeAgoInWords` method of `I18/Time`, sometimes the 'ago' word didn't show up.

To be honest, I didn't test it a lot, but I think that it is a bug on the last line of `timeAgoInWords`:

    return $relativeDate;

I think that it should be 

    return sprintf($relativeString, $relativeDate);

I would do a pull request, but I am not 100% sure that this is the solution to the problem and I am not fluent enough with git, yet.

**Comment by markstory** [comment]
What is the output you are getting that you feel is incorrect?

**Comment by hakermania** [comment]
I had those options for my `Time` instance:

    private $_options = [
        'accuracy' => [
            'year' => 'year',
            'month' => 'month',
            'week' => 'day',
            'day' => 'day',
            'hour' => 'hour',
            'minute' => 'minute',
            'second' => 'second'
        ],
        'end' => '+200 years' //always use the 'ago'
    ];

And I created some `Entities`. I called `timeAgoInWords` in the `created` field, with the specified options, from within a `Helper` and I got these results, for 3 different entities:

`2 hours ago`
`1 hour ago`
`1 hour`

I didn't keep the exact datetimes, though.

**Comment by markstory** [comment]
Thanks, I'll see if I can get the same error to crop up.

**Comment by hakermania** [comment]
I don't seem to be able to reproduce it. The following code echoes nothing:

    use Cake\I18N\Time;
    
    $options = [
        'accuracy' => [
            'year' => 'year',
            'month' => 'month',
            'week' => 'day',
            'day' => 'day',
            'hour' => 'hour',
            'minute' => 'minute',
            'second' => 'second'
        ],
        'end' => '+200 years' //always use the 'ago'
    ];
    
    $time = new Time();
    for ($i = 0; $i <= 1.5*DAY; $i++) {
        $time->modify('-1 seconds');
        if (substr($time->timeAgoInWords($options), -3) !== 'ago') {
            echo $time->timeAgoInWords().' '.$time->getTimestamp().'<br>';
        }
    }

But in this case, I manually created the Time instance. The error showed up with an automatically created Time instance from a datetime field.

On a side note, in which case `timeAgoInWords` would just return `$relativeDate` as is? It doesn't make much sense. That's why I thought that this `return` at the end is the source of the problem.

**Comment by markstory** [comment]
What we the timestamp that originally caused the issue?

**Comment by hakermania** [comment]
Sorry, but as I mentioned earlier, I didn't keep the exact datetimes.

**Comment by markstory** [comment]
Ok. I'll see what I can come up with.

**Comment by markstory** [comment]
The ago suffix is intentionally omitted as the code branch you mentioned is used for future dates.  For example:

```
>>> $time = new \Cake\I18n\Time('+1 day 1 hour');
=> Cake\I18n\Time {#207
     +"time": "2015-07-11T01:32:47+0000"
     +"timezone": "UTC"
     +"fixedNowTime": false
   }
>>> $time->timeAgoInWords();
=> "1 day"
```

Since this time is in the future, including 'ago' would be incorrect.
