### ISSUE TITLE
Schema Shell not working for Views, Triggers, StoredProcedures

### ISSUE THREAD

**Issue by bohrasankalp** [cakephp/cakephp#6981]
Though cake schema shell create is working successfully for DB Schemas updations and creations as well but its not working for my saved Procedures. I wish to geneate to chanegs for procedures, triggers, & Views as well. Is any external shell or present that helps me implement same with schema shelll ?

**Comment by lorenzo** [comment]
No, it does not work with all the advanced database features. It is better if you use SQL dumps or other more advanced migration systems. The goal of the Schema shell was never to support all the possible database features.

Look into http://www.liquibase.org/ for example

**Comment by bravo-kernel** [comment]
:bulb:
