### ISSUE TITLE
netbeans is showing error

### ISSUE THREAD

**Issue by dhananjayve** [cakephp/cakephp#6982]
i had install cakephp 3.x. All things are working fine. but my netbeans editor is showing error in every core file wherever <%= $var %> is used. I am unable to understand this line.
some examples are: 
class <%= $name %>Form 
namespace <%= $namespace %>\Controller\Component;

Please explain what is meaning of above symbol and how can i resolve this issue in my netbeans editor.

**Comment by tersmitten** [comment]
It's short syntax for echoing.

http://stackoverflow.com/questions/2020445/what-does-mean-in-php

**Comment by majna** [comment]
Select project in NB, right-click on Properties and set "Allow ASP tags"

**Comment by dhananjayve** [comment]
i have updated php ini file 
short_open_tag = On
asp_tags=on
But code in file is diffrent 
file location is cake3\vendor\cakephp\bake\src\Template\Bake\Controller
code is
<?php
namespace <%= $namespace %>\Controller<%= $prefix %>;

use <%= $namespace %>\Controller\AppController;
class <%= $name %>Controller extends AppController
{
<%
echo $this->Bake->arrayProperty('helpers', $helpers, ['indent' => false]);
echo $this->Bake->arrayProperty('components', $components, ['indent' => false]);
foreach($actions as $action) {
    echo $this->element('Controller/' . $action);
}
%>
}

whole thing is in <?php tag and usages asp like tag in middle. netbeans is showing error
