### ISSUE TITLE
CakePHP saveAssociated fails if a foreignkey validation rule is set

### ISSUE THREAD

**Issue by Serginho** [cakephp/cakephp#6983]
I think the problem is in the validateAssociated function. I don't underestand why both models are validated at the same time.

In my opinion saveAssociated would be better whether follows that steps:
1. validate Model
2. save Model
3. set key Model to foreignkey RelatedModel
4. validate RelatedModel
5. save RelatedModel

With this flow it's prevented that saveAssociated fails if RelatedModel foreignkey is required => true.

**Comment by ADmad** [comment]
Use [application rules](http://book.cakephp.org/3.0/en/orm/validation.html#foreign-key-rules) not validation rules for enforcing foreign key constraints.

**Comment by tanuck** [comment]
@ADmad from the post he has on stackoverflow regarding this, it seems he's using 2.6 rather than 3.x.

**Comment by lorenzo** [comment]
@ADmad I think this was for cake 2. In any case... that is a feature that was not implemented for that version and will probably not be implemented at this point in time, given that we have version 3

**Comment by ADmad** [comment]
Oops sorry, I mistake the mention of `saveAssciated` which pointed to the fact that it relates to 2.x.

**Comment by Serginho** [comment]
Yes lorenzo, I'm using cake 2.6.3
I don't think that request was Works For Me. it's for everyone. I'm using cakePHP as a REST api, It's so easy use it when we use cake views. But it isn't the case.
saveAssociated is a very cool function, but only can be used for updating, not for adding cause foreignKey validation rules.

**Comment by lorenzo** [comment]
I would remove the fk validation from the validator and move them to the beforeSave() @Serginho 

That is the way I have done it always in cake 2 since having the feature in the current code base is quite complex.

**Comment by tanuck** [comment]
The scale of changes needed to `saveAssociated/validateAssociated` would be too big. Shame because it's really frustrating!

**Comment by ADmad** [comment]
IIRC another alternative is to use option `'validate' => true` instead of default `'validate' => 'first'`.

**Comment by Serginho** [comment]
I'm removing the rule on-the-fly before use saveAssociated. That's the way I solved it

@tanuck the change would be: don't use validateAssociated, and validate first Model and after validate  independently each RelatedModel
