### ISSUE TITLE
add class to all selects of datepicker

### ISSUE THREAD

**Issue by repher** [cakephp/cakephp#6984]
Hello!

I would like to add a class to all selects of an automagic created datepicker formgroup.
```php
<?= $this->Form->input('published', ['class'=>'classtoadd' ]); ?>
```
The result ist:
```html
<div class="form-group">
    <label class="control-label">Published</label>
    <select name="published[year]">
        ... options ...
    </select>
    <select name="published[month]">
        ... options ...
    </select>
    <select name="published[day]">
        ... options ...
    </select>
</div>
```
This workes perfectly on simple inputs. Is this an expected behaviour or am I doing something wrong?

Im usingc cakephp 3.0.8.

Thanks!

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by repher** [comment]
Sorry. On the one hand I had a custom FormHelper loaded, on the other hand the problem persists with cakephp's own FormHelper.

I will head over to stackoverflow!

Thanks!
