### ISSUE TITLE
Loading Plugin assets in Plugin view page

### ISSUE THREAD

**Issue by Jayaramki** [cakephp/cakephp#6987]
Hi guys...
The plugin assets path was not expected. I have tried the way mentioned in documentation. But the out put path was not expected. 
Created myScript.js at `myCake/plugins/firstPlug/webroot/` directory. I need this `javascript` file in `myCake/plugins/firstPlug/src/Template/myFunc/index.ctp.

So, I used this code, `echo $this->Html->script('firstPlug.myScript');`

But the output is,
`<script src="/~cjramki/myCake/webroot/firstPlug/js/myScript.js"></script>`

I was expected,
`<script src="/~cjramki/myCake/firstPlug/webroot/js/myScript.js"></script>`

I don't think it is a bug. Because you people created lot of plugins. So, you guys may worked under this situation. I could not find the proper document or blog posts to solve this issue. Can you guys point out where I missed?

**Comment by ADmad** [comment]
The problem is with your base url. Cake isn't able to properly guess it since you are using the path provided by mod_userdir. Explicitly set the proper value for `App.baseUrl` config in your `config/app.php`.

**Comment by Jayaramki** [comment]
@ADmad I think it is not related to `mod_userdir`. I have also checked in my windows machine (wamp). I am getting the same out put. When I digged into the source, https://github.com/cakephp/cakephp/blob/master/src/View/Helper/UrlHelper.php#L78-L81 those 4 lines are constructing the url in `<cakeDirectory>/webroot/pluginName/js/myscript.js`. So, `mod_userdir` is not a problem at all.

**Comment by ADmad** [comment]
What's the url you get for an app asset?

**Comment by Jayaramki** [comment]
I am getting `/~cjramki/myCake/webroot/js/myAppScript.js` like this. 

I have put break point to check where went wrong in UrlHelper's webroot method. My `$this->theme` value is empty. So, the condition at https://github.com/cakephp/cakephp/blob/master/src/View/Helper/UrlHelper.php#L154 this line goes to false block always for my app resources and also for plugin resources. 

And My https://github.com/cakephp/cakephp/blob/master/src/View/Helper/UrlHelper.php#L172 also goes to false block.

**Comment by ADmad** [comment]
>  I am getting /~cjramki/myCake/webroot/js/myAppScript.js like this. 

You should never have "webroot" in your urls. It is a url rewriting issue. So as I already stated earlier manually set proper value for `App.baseUrl` config.

**Comment by Jayaramki** [comment]
I can't each time change my hardcoded url. So, is there any way to solve url rewriting issue?

**Comment by ADmad** [comment]
All you have to do is set the `App.baseUrl` config and use helpers to generate your urls.

 There is no bug here that needs to be fixed. If you need further assistance post your issue your stackoverflow.com. This issues tracker is not a help forum.

**Comment by Jayaramki** [comment]
ok thanks for your response... :D

**Comment by Jayaramki** [comment]
Got it worked Now. I have enabled 'mod_rewrite` module in my wamp, and commented the `baseUrl` in `app.php` file. 

Now I'm getting `/myCake/myPlugin/js/myScript.js`
