### ISSUE TITLE
Use sql function as a value with $Table->save(entity) doesn't work !

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#6989]
Hi,
When i want to save an entity that contain a **value with a sql function** it always treat it like a **string**.
I take a look at the documentation and i found that the **sql functions** can be used only with **find()**
```$Table->find()->func()->sql_func()``` http://book.cakephp.org/3.0/fr/orm/query-builder.html#utiliser-les-fonctions-sql !
That's my code:
```php
// NotificationsTable
public function saveNotification($action, $model, $entity_id, $version_id = 1, $role = 'user'){
    $user_id = Hash::get($_SESSION['Auth'], 'User.id');
    $entity = $this->newEntity([
        'action' => $action,
        'model' => $model,
        'entity_id' => $entity_id,
        'version_id' => $version_id,
        'role' => $role,
        'read_dc' => "COLUMN_CREATE($user_id, NOW())",
        'seen_dc' => "COLUMN_CREATE($user_id, NOW())"
    ]);
    $this->save($entity);
}
```
That's the generated sql:
```sql
INSERT INTO notifications 
(action, model, entity_id, version_id, role, seen_dc, read_dc, created, created_by) 
VALUES ('ADD', 'Articles', 6, 1, 'user', 'COLUMN_CREATE(1, NOW())', 'COLUMN_CREATE(1, NOW())', '2015-07-09 16:06:49', 1)
```
If i change the generated query ```...'COLUMN_CREATE(1, NOW())'...``` to this ```...COLUMN_CREATE(1, NOW())...``` ( just remove the quote ```'``` ) it works

**Comment by flashios09** [comment]
I found the solution(i'm not sure but it works)
```php
// NotificationsTable
public function saveNotification($action, $model, $entity_id, $version_id = 1, $role = 'user'){
    $user_id = Hash::get($_SESSION['Auth'], 'User.id');
    $func = $this->query()->func();
    $entity = $this->newEntity([
        'action' => $action,
        'model' => $model,
        'entity_id' => $entity_id,
        'version_id' => $version_id,
        'role' => $role,
        'read_dc' => $func->COLUMN_CREATE([$user_id => 'literal', $func->now()]),
        'seen_dc' => $func->COLUMN_CREATE([$user_id => 'literal', $func->now()])
    ]);
    $this->save($entity);
}
```
That's the generated sql:
```sql
INSERT INTO notifications 
(action, model, entity_id, version_id, role, seen_dc, read_dc, created, created_by) 
VALUES ('ADD', 'Articles', 6, 1, 'user', (COLUMN_CREATE(1, (NOW()))), (COLUMN_CREATE(1, (NOW()))), '2015-07-09 16:42:18', 1)
```
The function isn't treated as a string any more :)

**Comment by dereuromark** [comment]
Side note: You should never access the session directly, and especially not in the model layer. Pass it in as part of the method signature.

**Comment by flashios09** [comment]
@dereuromark Do you mean that i have to change ```Hash::get($_SESSION['Auth'], 'User.id');``` with ```Hash::get($_SESSION, 'Auth.User.id');``` or ```$auth = $_SESSION['Auth']; Hash::get($auth, 'User.id');``` ! 
and what about using a sql function with $Table->save($entity) ?

**Comment by markstory** [comment]
Closing as you found the solution I was going to recommend. If you don't want to build a query that is then thrown away, you can directly construct `Cake\Database\FunctionsBuilder`.

**Comment by flashios09** [comment]
@markstory  Thanks, you always give me a **better** solution, i don't want to build a query(i just follow the example in the documentation with ```$Table->query()->func()->sql_func()```) and change it with ```$Table->save($entity)```
I replace ```$func = $this->query()->func();``` with ```$func = new FunctionsBuilder();``` and it works like you said :+1: 
@dereuromark  say that i shouldn't use **$_SESSION** in the model layer ! Before with **cakephp2** i used the static method ```Auth::user('id')``` in the model to get the **user id**, what i have to do with cakephp3 to get the **user id** without using ```$_SESSION``` ? I didn't found anything in the documentation

**Comment by ADmad** [comment]
@flashios09 https://github.com/UseMuffin/Footprint

**Comment by flashios09** [comment]
@ADmad for the fields **created_by** and **modified_by**, i use already the **WhoDidIt** plugin and there i find the solution to get the **user id** inside the model layer using the **$_SESSION** ! I will try the Footprint plugin and gave you a feedback :+1:
