### ISSUE TITLE
problem with rawQuery

### ISSUE THREAD

**Issue by nayibor** [cakephp/cakephp#6992]
i just noticed in the Cakephp 2.6.7 [/lib/Cake/Model/Datasource/DboSource.php](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/DboSource.php#L397-L436) the rawQuery method has a line
 
`return $this->execute($sql, $params);`
 
isn’t this supposed to accept 3 parameters instead of two with the second one being an options array . 
had to write a query and noticed this .
also i needed to run a parametrized query and i put the parameters in the $params section.
the query was however not sent to the mysql server i was using .
i had to look in the DboSource.php file and then modify the rawQuery method to below which worked
 
from:
 
``` php
public function rawQuery($sql, $params = array()) {
    $this->took = $this->numRows = false;
    return $this->execute($sql, $params);
}
```
 
to:
 
``` php
public function rawQuery($sql, $params = array()) {
    $this->took = $this->numRows = false;
    return $this->execute($sql,array(), $params);
}
```
 
Kindly assist if the way i am doing this is wrong .

**Comment by HavokInspiration** [comment]
Maybe ``rawQuery()`` should have the same signature as ``execute()`` and allow for values to be bound ?

**Comment by HavokInspiration** [comment]
@nayibor In which context are you using the ``rawQuery()`` method ? Can you give us an example ?

**Comment by nayibor** [comment]
i am using  it for a parametrized query  for example  .

 $query=" SELECT id,stock_available FROM products WHERE  (id = ? and stock_available >= ?)or   (id  = ? and stock_available >= ?) FOR UPDATE";
 $query_params=array(1,50,2,30);
 $response = $this->Product->getDataSource()->rawQuery($query,$query_params);

the above should work  but  no sql statements  gets sent to the server  when i run it .
the signature may have to be changed as you suggested cuz right now it seems that the execute function which gets called is  using the params variable  for the options

**Comment by markstory** [comment]
Yep, the code was wrong. Pull request open now.
