### ISSUE TITLE
Tests on repos will be good

### ISSUE THREAD

**Issue by harikt** [cakephp/cakephp#6994]
Hi Guys, 

I have a humble request, if you guys can keep the tests on the read only split of the repos.

I have installed `cakephp/validation` and was looking for the tests. If the tests are there it will be easy to look more. I came across same for `cakephp/orm` . The difficulty is when you are using the components standalone.

An alternative approach is as Symfony keeping the tests inside `Test` folder namespace ( https://github.com/symfony/symfony/tree/2.8/src/Symfony/Component/Yaml/Tests ) . Advantage is users can create and run test and make sure the error is not part of the library and app.

Thank you.

/ cc @josegonzalez

**Comment by harikt** [comment]
Sorry @josegonzalez I was trying to mention @lorenzo and tagged wrongly.

Thank you.

**Comment by dereuromark** [comment]
That sure makes sense, if we want to encourage people to use the standalone split-offs.

**Comment by markstory** [comment]
Should be doable, just needs more gitfu I think. Each subsplit will probably get a duplicate copy of the fixtures, test_app and other related directories too. Trying to keep exact dependencies straight will be a huge time sink.

**Comment by harikt** [comment]
Hi all, 
Any ideas how we can achieve this ?
Thank you.

**Comment by dereuromark** [comment]
@harikt We can add travis for the split repos and activate them.

**Comment by harikt** [comment]
@dereuromark what I love is in case I find some issue with my code, and think it is related to a component we should be able to write a test case against it and run unit test. In the current setup I don't think it is doable. But if it is changed to something like what Symfony does it is doable. Not a fan to keep all Tests in the same place within the source as Symfony. But it helps a lot for people to test things.

Thank you

**Comment by dereuromark** [comment]
You can do that by adding the Test to the main repo.

**Comment by harikt** [comment]
@dereuromark By test in main repo do you mean adding to  https://github.com/cakephp/cakephp repo ?

If that's the case I know you are not working with components but only with cakephp framework ie why the comments are :-) .

**Comment by dereuromark** [comment]
Yeah this is just a workaround of course. Until we can find a better architecture.

**Comment by dereuromark** [comment]
We can close this now as no further action here can be taken at this point until we can revisit test splitting.
