### ISSUE TITLE
3.0 ORM retrieves wrong result when the ID is larger then PHP_INT_MAX

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#6997]
On 32-bit operating system,

<code>
$articles->get('2147483648')
</code>

executes a query like this:

<code>
SELECT ... FROM articles Article WHERE Article.id = 2147483647 LIMIT 1
</code>

'2147483648' has been cast to 2147483647.
This will particularly be a problem when the ID is declared as INT UNSIGNED or BIGINT.

CakePHP 2.x works correctly.

**Comment by lorenzo** [comment]
What is the column type?

**Comment by chinpei215** [comment]
int unsigned.

**Comment by lorenzo** [comment]
You need to set the type as bingint or string if you want it to work :)

You can read in the manual about `_initializeSchema()`, it will help you to re-map the type of a column. Obviously, it will not work to store a bigint into an integer field

**Comment by chinpei215** [comment]
Thanks.
But int unsigned field can store 2147483648 :)
This issue causes even if ID is declared as bigint on 32-bit operating system.

This will works:
<pre>protected function _initializeSchema(Schema $schema)
{
     $schema->columnType('id', 'string');
      return $schema;
}
</pre>
But <code>$schema->columnType('id', 'biginteger')</code> doesn't work.

If it's a feature, I think it should be documented :)

**Comment by lorenzo** [comment]
Ok, there is not much we can do about it. PHP 32 bit cannot represent such numbers, I would suggest in your case to use a string type, then.

**Comment by chinpei215** [comment]
Thanks :)
