### ISSUE TITLE
Select without any option

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#7001]
Cake 2.5.8

There is no field name in `$this->request->data` after submit when field input select hasn't any option.

Now I must use `required` to `true` on this validation rules but I would like skip this...

**Comment by ADmad** [comment]
> There is no field name in $this->request->data after submit when field input select hasn't any option.

That's not possible if you are using FormHelper to generate the select. It adds a hidden field by default which ensure an empty string is POSTed if no option is selected.

**Comment by kicaj** [comment]
Select is created by FormHelper:


	<?php
		echo $this->Form->input('post_category_id', array(
			'class' => 'column-9',
			'label' => array(
				'text' => 'Kategoria',
				'class' => 'column-3'
			)
		));
	?>

When I set `empty` works good. But problem is when is without any option or without `empty`...

**Comment by kicaj** [comment]
And $postCategories is empty

**Comment by ADmad** [comment]
Ah this is a normal select not a multi-select. Wonder if html skips the select input in POSTed data if it does not have any options.

**Comment by markstory** [comment]
@ADmad Yes it does. @kicaj This is more an issue with HTML/browsers than with CakePHP.

**Comment by ADmad** [comment]
@markstory We do take care of this wackiness for multi selects so I don't think it's wrong for people to expect the same for single value selects too.

**Comment by markstory** [comment]
Multiselects don't submit even of they have options and none are selected though. This seems like a far less likely case.

**Comment by jhli** [comment]
If you are relying on what users send (e.g. Default/hidden data) instead of doing something like validators required true, then users might tinker with your app/from data to manipulate data and/or crash the app; imho.

**Comment by ADmad** [comment]
> and/or crash the app

Woah, that escalated quickly.
