### ISSUE TITLE
Impossible to use CSS block into View Cells

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#7003]
In CakePHP 3.0 I am trying to build a Dynamic menu based on user profiles.
I just noticed that it is impossible to do:

<code>
$this->Html->css('menupan.css',['block'=>true]);
</code>

It seems like the View Cells are loaded after the View Blocks were already rendered.

Is this the real purpose of View Cells, or we may consider this a bug?

Thanks in advance.

**Comment by markstory** [comment]
Cells are not loaded after, but they do use separate view instances that do not share state with the enclosing view. This is intentional as cells are a lightweight replacement for requestaction.
