### ISSUE TITLE
Mongodb driver

### ISSUE THREAD

**Issue by omidahn** [cakephp/cakephp#7007]
Will there be Mongodb support for cakephp 3?

**Comment by jhli** [comment]
You can simply use it but the ORM is SQL oriented, so you ll have to figure out form and data validation, data filtering/retieval and writing. as far as I know.

**Comment by omidahn** [comment]
But there is no Mongo DB Driver out of the box

**Comment by lorenzo** [comment]
@okinaka there are currently no plans for creating a mongo db ODM. Let us know if you are interested in creating one so we can guide you in the process

**Comment by tanuck** [comment]
@omidahn @lorenzo I brought this up on IRC sometime last week with the same outcome. So I've started on my own mongo DS plugin, I'd be happy with any help once I've pushed up the initial commits!

**Comment by lorenzo** [comment]
@tanuck great, just copy the link to your repo when you have it public!
