### ISSUE TITLE
Permissions reset to log and tmp dir?

### ISSUE THREAD

**Issue by alexkleinubing** [cakephp/cakephp#7011]
I have got some error of permissions.

![captura de tela de 2015-07-13 13 02 19](https://cloud.githubusercontent.com/assets/2112389/8655515/a8fd81b8-295f-11e5-867e-c1a5717d07a1.png)

I have set full 777 permission to directory and this work, but hours later, it need to set again, on file of persistent and model folders, on tmp directory...
I have set all day, again and again and again, i dont understand it, the cake create the file with wrong permissions, but dont modify? 

Sorry for bad english.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
