### ISSUE TITLE
Support for treating BINARY(36) in CakePHP 3.x

### ISSUE THREAD

**Issue by adduc** [cakephp/cakephp#7013]
Hello,

As I understand it, CakePHP 1.x and 2.x had support for treating both CHAR(36) and BINARY(36) database fields as UUID. While CakePHP 3.x supports treating CHAR(36) as UUID, it does not appear to offer the same behavior for BINARY(36) fields. Could this feature be added back in a future 3.x release? I would be willing to develop it.

**Comment by markstory** [comment]
I'm assuming you're using mysql? I don't think we ever supported binary(36) in sqlserver or postgres.

In addition to handling the column reflection, we'd also need to solve how this uuid type is different from the string one. Right now all the uuid implementations use ascii encoded data. I don't think that is going to be feasible if we also have to handle binary blobs.

**Comment by lorenzo** [comment]
Binary(36) has only disadvantages over CHAR(36), that is why it is not supported.

Supporting BINARY(16) would be interesting, but requires important changes in how the Type system works (specifically using custom SQL each time the column is used in a query)

**Comment by dereuromark** [comment]
I think I tried with binary(16) and had to use https://github.com/dereuromark/cakephp-shim/blob/master/src/Database/Type/BinaryType.php for it.

**Comment by markstory** [comment]
@dereuromark Ideally we'd have a binaryUuid type so we wouldn't be running regexp on potentially megabytes of binary data.

**Comment by voycey** [comment]
This is being discussed in the channel now - did this go anywhere?

**Comment by markstory** [comment]
Nope. @adduc never submitted a pull request, and I guess others haven't wanted the feature enough to implement it.

**Comment by dereuromark** [comment]
:( would have loved to see that

**Comment by voycey** [comment]
Looks like it is still happening from lorenzo's ticket :)

**Comment by inoas** [comment]
Now did this go into 3.4 yet?

**Comment by lorenzo** [comment]
The changes are there, and there are also tests showing how it would work in theory. But there is no automatic support for it
