### ISSUE TITLE
problem rewrite url under xampp or wampserver with debug to false

### ISSUE THREAD

**Issue by jc-developpement** [cakephp/cakephp#7014]
HI
i try actually cake 3 and i have a problem when i change debug to false in the config file. It does not find webroot but when the debug mode is enable, it's OK

I don't understant why ?

Thx 

Jerem

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by antograssiot** [comment]
@jc-developpement the home page is not accessible when debug is false by default.
See https://github.com/cakephp/app/blob/master/src/Template/Pages/home.ctp#L23-L25
