### ISSUE TITLE
Add UrlHelper as property comment in Cake\View\View

### ISSUE THREAD

**Issue by adayth** [cakephp/cakephp#7018]
UrlHelper could be added to Cake\View\View to enable property autocompletion.

Related to: junichi11/cakephp3-netbeans#29

```php
@property      \Cake\View\Helper\UrlHelper $Url
```

**Comment by lorenzo** [comment]
@adayth would you like to submit a pull request?

**Comment by adayth** [comment]
Sure, I'll do it.

**Comment by adayth** [comment]
Done. I hope you find it useful ;)
