### ISSUE TITLE
inputContainer should be ignored by hidden inputs

### ISSUE THREAD

**Issue by richerlariviere** [cakephp/cakephp#7025]
It could be a great enhancement to avoid hidden inputs from being wrapped by an inputContainer. In my case, I can see the div in the DOM. If it is impossible I guess we can add a new template type for hidden inputs.

**/config/app_form.php**
```php
return [
    'formStart' => '<form class="form-horizontal" role="form" {{attrs}}><fieldset>',
    'formEnd' => '</fieldset></form>',
    'label' => '<label class="control-label col-sm-2" {{attrs}}>{{text}}</label>',
    'select' => '<div class="col-sm-10"><select class="form-control" name="{{name}}" {{attrs}}>{{content}}</select></div>',
    'inputContainer' => '<div class="form-group" {{required}} form-type="{{type}}">{{content}}</div>',
    'input' => '<div class="col-sm-10"><input class="form-control" type="{{type}}" name="{{name}}" {{attrs}}></div>',
    'inputContainerError' => '<div><input type="{{type}}" required="{{required}}" value="{{content}} - {{error}}"></div>'

];
```

**Comment by ADmad** [comment]
Can you provide a usage example which generates hidden input wrapped with input container?

**Comment by richerlariviere** [comment]
Of course! I removed the useless code, like classes and other non-input elements. My form is using a form template located in `/config/app_form.php``.

**Input declaration**
```php

<?php echo $this->Form->hidden('company_id', ['value' => '1']); ?>
```

**Generated code**
```php

<div class="col-sm-10">
    <input class="form-control" type="hidden" name="company_id" value="1">
</div>
```

**Comment by richerlariviere** [comment]
Oh, I'm feeling stupid. There is no problem with inputContainer...

However, the hidden input is wrapped with the input template. Is it useful considering the fact that this input is invisible?

**Comment by ADmad** [comment]
You should not be adding wrapper to the `input` template. [BootstrapUI](https://github.com/friendsofcake/bootstrap-ui) achieves layouts using bootstrap without adding any wrapper to the `input` template :)
