### ISSUE TITLE
.editorconfig and stander for HTML * .ctp according to "w3schools" or "Bootstrap" similar to "PSR-2"

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#7027]
Hi,
This is not a bug, is a pleanteo on https://github.com/cakephp/cakephp/blob/master/.editorconfig
or standard HTML and JS in CakePHP.

CakePHP 3 does not set a standard for HTML .ctp * or * .js files ..?
As "w3schools"
http://www.w3schools.com/html/html5_syntax.asp
or "Bootstrap"
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#code-guidelines

There is a standard style "CODE http://www.php-fig.org/psr/psr-2/ in PHP, but HTML and JS, for the community adheres ..?

Example:
[* .ctp]
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[* js]
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

The CakePHP community, define the standard for working with CakePHP has to be all with "4 Space" ..?
The problem that Space can modify the render in the browser running small spaces added the <DIV> or other <TAG>, unlike "indent_style = tab" for HTML.

Whenever we generate linia break to have a more comfortable reading code without affecting the output in the browser.

**Comment by bcrowe** [comment]
I'd totally be cool with having these settings for .ctp and .js files since they do follow the standards at-large. Do you want to make a quick PR first and we can let the bikeshedding begin? :laughing:

**Comment by ADmad** [comment]
`.ctp` are essentially php files and hence follow same indentation standard as php files. Even if you consider them as HTML we would prefer using a consistent indentation. Core does not have any javascript files to setting a style for it is irrelevant.

That said these standards are for the cakephp core. You are free to follow whatever standard you like for your app.

**Comment by bcrowe** [comment]
@EOM You might've wanted to put this issue on the cakephp/app repo instead of this one.

**Comment by ADmad** [comment]
@bcrowe It will have the same fate there too :)

**Comment by EOM** [comment]
I look for a standard type "PSR-2" but for all that is HTML, JS, JSON, CSS.
But found nothing, as similar as people of "w3schools"
http://www.w3schools.com/html/html5_syntax.asp
and "Bootstrap"
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#code-guidelines

And I think it would be good to have one sinseramente for all to respect them.

Especially considering the problem of "4 space vs Tab" in HTML code.

I would like to see that the community thinks about having a "code style" for HTML * .ctp, js, css, etc ..

**PS: It is true "bcrowe" would have to aver been in cakephp / app, but I think it is for us to consider not ..?**

**Comment by ADmad** [comment]
@EOM As I already stated earlier you are free to choose whatever standard you like in your app. No one is forcing you to use Cake's standards.

**Comment by EOM** [comment]
OK @ADmad and @bcrowe ,
I saw maybe my approach wrong with the file * .ctp.
As thanks for his opinion.

**Comment by dereuromark** [comment]
@EOM That's (not only) why [PSR2-R](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide.md) uses tabs consistently throughout the code base. Feel free to use this community standard (and the former Cake 1,2 one) instead of the official one. As I and others do.
But there will be no changes here on the official side regarding your inquiry, I am pretty sure.
