### ISSUE TITLE
Unable to read Cookie created in Cakephp 2 from Cakephp 3

### ISSUE THREAD

**Issue by tonypresnow** [cakephp/cakephp#7030]
Is it possible to read a cakephp 2 cookie from within cakephp 3? 

If not, I would like to request the feature to be included in a future release.

This is a particularly important issue for me, as I store an encrypted login cookie that I use to identify the user between several different cakephp applications.

**Comment by markstory** [comment]
Yes it is if you use the AES mode. The rijndael mode is not supported by the SSL crypto set and should be avoided.

There are limitations in what cookie data can be read back from cake2 as cake2 only allows one cookie. However, simple keys should be portable.

**Comment by tonypresnow** [comment]
I'm still having trouble reading cakephp 2 cookies with aes encription from cakephp 3. I've updated the salt values so they match, and I'm using the aes type as indicated in the documentation.

Cakephp2
$this->Cookie->type('aes');
$this->Cookie->write('test1', 'tony', TRUE, '15 years');

Cakephp3
$this->Cookie->config('path', '/');
debug($this->Cookie->read('test1'));  // returns null

What do you mean by "one cookie"?
What do you mean by "simple keys"

**Comment by markstory** [comment]
@tonypresnow All of the cookies stored by 2.x will be under a top level key. (The default is CakeCookie). In your 3.x code you would need to read `CakeCookie.test1`.

By simple keys, I mean cookie values that only store scalars. Complex array structures can be stored in cookies in both versions, however complex structures are not as portable.

**Comment by tonypresnow** [comment]
Thanks for getting back to me so quick! I see in debugkit that cakephp 3 can see the cookies created in cakephp 2 on the request tab. I've attempted to read the cookies with $this->Cookie->read('CakeCookie.test1') but all that is returned is an empty string.

$this->Cookie->check('test1') returns true. 
If I disable encryption when writing the cookie in cakephp 2 and disable encryption when reading the cookie in cakephp 3, I can read the cookie successfully.
