### ISSUE TITLE
Router::promote phpdoc

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#7031]
Look at this line:

https://github.com/cakephp/cakephp/blob/f6a2e355348c8c5d45e04addc0242a60aeb73f1b/src/Routing/Router.php#L33

Looks like it's not existing anymore. Will this come back, or whats an alternative?

**Comment by markstory** [comment]
There is no promote() and it cannot come back as the scope trees make it impossible to move a route 'up' anymore. I will fix the doc block.

As for alternatives, you can either use scope() to make matches prioritized or actually connect your routes in the order you want.
