### ISSUE TITLE
SQL Server DSN Flags

### ISSUE THREAD

**Issue by zmonteca** [cakephp/cakephp#7033]
Is there a reason why 'MultipleActiveResultSets' is hard coded to false in the DSN connection string in the SqlServer driver (\Cake\Database\Driver\Sqlserver.php)?

```
$dsn = "sqlsrv:Server={$config['host']};Database={$config['database']};MultipleActiveResultSets=false";
```

**Comment by markstory** [comment]
Yes, because without it SQLServer queries frequently fail with errors related to open result sets.

**Comment by zmonteca** [comment]
Got it. I just experienced this inconsistent failure you mentioned. The reason I was playing with it was because I was reading about another CakePHP issue (https://github.com/cakephp/cakephp/issues/5797). 

I'm current doing this insertion into SQL Server and every time the insertion works, but all subsequent requests fail. 

This is with MultipleActiveResultSets=false, but if I toggle MultipleActiveResultSets=true, it consistently works, but then other queries randomly fail as you mentioned above.

```
                                $connection = ConnectionManager::get('default');
                                $ballotItemVoteInsertQuery = new Query($connection);
                                $ballotItemVoteInsertQuery->into($ballotItemVote->table());
                                $ballotItemVoteInsertQuery->insert($column_keys)
                                    ->values($column_array)
                                    ->execute();
```

**Comment by zmonteca** [comment]
Solved this.

The code above needed to be rejiggered to close open cursors that apparently remained open from the execute. The problem was resolved using the following code instead: 

```
$connection = ConnectionManager::get('default');
$ballotItemVoteInsertQuery = new Query($connection);
$ballotItemVoteInsertQuery->into($ballotItemVote->table());
$statement = $ballotItemVoteInsertQuery->insert($column_keys)
                                    ->values($column_array)
                                    ->execute();
$statement->closeCursor();
