### ISSUE TITLE
Bug with Hash::diff in at least 2.6.9 and 2.7.0

### ISSUE THREAD

**Issue by evoluted** [cakephp/cakephp#7039]
I first noticed this in 2.6.9 but have just upgraded to 2.7.0 and the issue still happens or at least it appears to be an issue to me.

I have two arrays:
````
array(
	(int) 2 => array(
		(int) 6 => '6',
		(int) 8 => '8'
	),
	(int) 3 => array(
		(int) 13 => '13',
		(int) 15 => '15'
	)
)
````
and
````
array(
	(int) 2 => array(
		(int) 6 => '6',
		(int) 8 => '8',
		(int) 10 => '10'
	),
	(int) 3 => array(
		(int) 13 => '13',
		(int) 15 => '15'
	)
)
````
Doing a simple Hash::diff on them
````
$diff = Hash::diff(
    $data['CurrentOptions'],
    $data['Options']
);
````
But when I output $diff, it's giving me the following array.
````
array(
	(int) 2 => array(
		(int) 6 => '6',
		(int) 8 => '8'
	)
)
````
I was expecting to be outputted
````
array(
	(int) 2 => array(
		(int) 10 => '10',
	)
)
````
Is this not a bug or do I just not understand what Hash::diff is suppose to do? Description from the docs "Computes the difference between two arrays:" to me says that this is a bug.

**Comment by HavokInspiration** [comment]
Looking at the code of ``Hash::diff()`` and running some tests, the result is expected.
The ``diff()`` method actually returns you the elements that are different between your two arrays.
In your case ``$data['CurrentOptions'][2]`` and ``$data['Options'][2]`` are different, so it returns you the elements from the first array you pass to ``diff()``.
It will not filter the result further than the first dimension of your arrays.

You can however take advantage of the ``Hash::flatten()`` method, use ``Hash::diff()`` with your flat arrays and expand the result back to a real array. It has a bit more overhead but should achieve what you need :

```php
$fa = Hash::flatten($data['CurrentOptions']);
$fb = Hash::flatten($data['Options']);
$diff = Hash::diff($fa, $fb);

$result = Hash::expand($diff);
```

``$result`` should be : 

```php
array(
    (int) 2 => array(
        (int) 10 => '10',
    )
)
```

**Comment by GuidoHendriks** [comment]
I think @HavokInspiration is right. It compares the elements in two arrays, not recursively.

**Comment by markstory** [comment]
Yes it is a non-recursive difference. The method is working as it always has.
