### ISSUE TITLE
$this->render('custom_view') view variables problem CakePHP 3

### ISSUE THREAD

**Issue by cercos** [cakephp/cakephp#7044]
When using $this->render('custom_view') the custom view only has view variables set if $this->set() is called before $this->render().  

Doesn't work:
$this->render('custom_view');
$this->set('data');

Works:
$this->set('data');
$this->render('custom_view');

**Comment by markstory** [comment]
Yes. The render() method renders the view when called. Variables set after that point will not be set as those lines have not executed yet.

Closing as you have to set view variables before render is called.
