### ISSUE TITLE
enctype of post requests

### ISSUE THREAD

**Issue by NaranjaWeb** [cakephp/cakephp#7047]
As is written in Upgrading to CakePHP 3.0(http://mark-story.com/posts/view/upgrading-to-cakephp-3-0), I found the integrations of web services in cakePHP3 is very useful and secure.

Some services require "multipart/form-data"(like validator.nu). On the other hand, my credit card company only accepts "application/x-www-form-urlencoded" for post request.

It seems that cakePHP3 always converts the header information to multipart/form-data even if it is set as following;

$response = $http->post(
    $url,
    $data,
    [
        'headers' => [
    		'Content-Type' => 'application/x-www-form-urlencoded'
		]
    ]
);

Is this what you meant?
Could you please think about we could select the Content-Type 
to make the integration more perfect.

**Comment by NaranjaWeb** [comment]
Or this could be a bug that 
Cake\Network\Http\Adapter\Stream::
_contextOptions['content']  is set to "multipart/form-data" format even when 
headers['Content-Type'] is set to 'application/x-www-form-urlencoded'.

I changed Stream::_buildContent function to use http_build_query() when
headers['Content-Type']  ===  'application/x-www-form-urlencoded', and
it worked for my purpose.

I am looking forward to 3.0.10.

**Comment by markstory** [comment]
This was fixed in #6854. Because the change could potentially break applications it was put into 3.1.
