### ISSUE TITLE
"cake bake all" still use $this->Session-setFlash('message'); in 2.7.0

### ISSUE THREAD

**Issue by kongkannika** [cakephp/cakephp#7048]
In `cake bake all` of Cake 2.7.0, is using `$this->Session->setFlash("message");`

I read the change log that it is deprecated.

It is replaced by `$this->Flash->set("message");`

**Comment by ADmad** [comment]
Would you like to make a PR updating it?

**Comment by kongkannika** [comment]
yes

**Comment by markstory** [comment]
Closing as there is a pull request open now.
