### ISSUE TITLE
ConsoleLog::write() <=> ConsoleOutput::write() incompatibility - Cake 2.x / 3.x

### ISSUE THREAD

**Issue by sam56483** [cakephp/cakephp#7049]
Hello,

I have found an incompatibility between ConsoleLog::log() call to ConsoleOutput::write() and its prototype.

[cake 3.0.9] src/Log/Engine/ConsoleLog.php:line 93 "return $this->_output->write(sprintf('<%s>%s</%s>', $level, $output, $level), false);"
Look at the second parameter, it's a boolean.

[cake 3.0.9] src/Console/ConsoleOutput.php:line 186 "return $this->_write($this->styleText($message . str_repeat(static::LF, $newlines)));"
The second parameter of the prototype is an integer.

"false" should be replaced with "0" then depending on the server configuration, str_repeat() could behave unexpectedly.

Best regards,

**Comment by markstory** [comment]
#7056 is open now.
