### ISSUE TITLE
ORM: Select fields from subquery

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7050]
Maybe it's not an issue and works as expected but I have problem to select fields from a subquery. Let me give you a simplified example which not make sense for a real usecase but shows the problem I have for another, more complex query.

These two lines:

```
$subQuery = $this->find();
$query = $this->find()->from(['sub' => $subQuery]);
```

will produce a query like:

```
SELECT 
    Geolocations.id AS `Geolocations__id`, 
    Geolocations.user_id AS `Geolocations__user_id`, 
    Geolocations.longitude AS `Geolocations__longitude`, 
    Geolocations.latitude AS `Geolocations__latitude`, 
    Geolocations.created AS `Geolocations__created` 
FROM (
    SELECT 
        Geolocations.id AS `Geolocations__id`, 
        Geolocations.user_id AS `Geolocations__user_id`, 
        Geolocations.longitude AS `Geolocations__longitude`, 
        Geolocations.latitude AS `Geolocations__latitude`, 
        Geolocations.created AS `Geolocations__created` 
    FROM 
        geolocations Geolocations
) sub
```

As you can see this query will result in an error like:

```
#1054 - Unknown column 'Geolocations.id' in 'field list' 
```

Theoretically I'm able to modify my query to:

```
        $subQuery = $this->find();
        $query = $this->find()
            ->select([
                'id' => 'Geolocations__id',
                'user_id' => 'Geolocations__user_id',
                'longitude' => 'Geolocations__longitude',
                'latitude' => 'Geolocations__latitude',
                'created' => 'Geolocations__created'
            ])
            ->from(['sub' => $subQuery]);
```

But this looks and feels wrong.

**Comment by lorenzo** [comment]
That is usually what I do: give nice aliases to fields in the subquery as I plan to use them in the main query

**Comment by steefaan** [comment]
You mean like this?

```
$subQuery = $this
    ->find()
    ->select([
        'latitude_test' => 'latitude'
    ]);
$query = $this->find()->select(['latitude' => 'latitude_test'])->from(['sub' => $subQuery]);
```

It will produce:

```
SELECT latitude_test AS `latitude` FROM (SELECT latitude AS `latitude_test` FROM geolocations Geolocations) sub
```

But this way I need to rewrite the selects from both queries. If I only would do:

```
$subQuery = $this
    ->find()
    ->select([
        'latitude_test' => 'latitude'
    ]);
$query = $this->find()->select(['latitude'])->from(['sub' => $subQuery]);
```

It would produce a query like:

```
SELECT Geolocations.latitude AS `Geolocations__latitude` FROM (SELECT latitude AS `latitude_test` FROM geolocations Geolocations) sub
```

and wouldn't work.

**Comment by markstory** [comment]
I am not sure that the orm should be trying to auto resolve field aliases in subqueries. I would much rather we stay closer to you get what you type as it makes debugging easier, and makes userland code more direct.

**Comment by lorenzo** [comment]
I'm not sure what you mean, why do you need to change anything in the outer query?

**Comment by steefaan** [comment]
@lorenzo I don't want to change something in the query. I want to calculate the distance inside the subquery (not a part of the example) and I want all the other fields from the table. Best would be to change nothing in `select()`  but then I get an invalid query desribed in my first comment. As answer for my first comment you told me that you give nice aliases for the subquery but if you do so, you also need to change the `select()` from the main query or I'm wrong? That is what I tried to show with my second comment. Seems that I'm on a wrong way so it's probably not an issue for cakephp itself. If you agree, you can close the ticket but it would be nice if you could give me short example what you meant in you first comment.

**Comment by lorenzo** [comment]
```php
$columns = $this->schema()->columns();
$subQuery = $this->find();
$subquery->select(array_combine($columns, $columns));
$query = $this->find()->from(['Geolocations' => $subQuery]);
````

**Comment by steefaan** [comment]
Thanks, but this is more or less what I meant. This means I need to rewrite all fields from `select()` in my subquery to be able to get these fields in my main query because the example you provided generates the following query:

```
SELECT 
    Geolocations.id AS `Geolocations__id`, 
    Geolocations.user_id AS `Geolocations__user_id`, 
    Geolocations.longitude AS `Geolocations__longitude`, 
    Geolocations.latitude AS `Geolocations__latitude`, 
    Geolocations.created AS `Geolocations__created` 
FROM (
    SELECT 
        id AS `id`, 
        user_id AS `user_id`, 
        longitude AS `longitude`,
        latitude AS `latitude`, 
        created AS `created` 
    FROM 
        geolocations Geolocations
) Geolocations
```

Maybe a possibility to tell the ORM that aliasing is not desired in the subquery or even in the main query, if someone needs it, would be nice. What do you think?

**Comment by lorenzo** [comment]
Yes you do need to rewrite the fields in the subquery, as I said in my frist message. Currently it is not possible to tell the ORM that the aliasing is not desired, but if you have an idea of how that could be implemented, I think I would be interested in the feature.

**Comment by steefaan** [comment]
`$subQuery = $this->find()->autoAlias(false);` maybe?

**Comment by jhli** [comment]
I had the same problems in my custom subquery and defined inner fields as aliased to the same name and it felt strange. At least the docs about from should hint at that (not sure, currently on gprs train mobile).

**Comment by thi012** [comment]
`$distance=30.89;`
`$fields=array('id','distance'=>$distance);`
`$conditions['AND']['distance >'] = 4;`
`$this->paginate=array('fields'=>$fields,'conditions' => $conditions);`
`$result=$this->paginate()->toArray();`

But get unknown column "distance", I cant use alias field in condition or anywhere

**Comment by lorenzo** [comment]
please don't add comments to issues that are not related to the code you are using
