### ISSUE TITLE
3.0.9 - Retrieveing plugin behavior from Table object fails

### ISSUE THREAD

**Issue by adayth** [cakephp/cakephp#7053]
After updating to 3.0.9 this line of my app started to fail:

```php
abstract class AppEntity extends Entity
{
    public function dummy()
    {
        \Cake\ORM\TableRegistry::get($this->source())->behaviors()->get('Proffer');
        // More code here
    }
}
```

Looking for loaded behaviors in that Table in the same context with ```->behaviors()->loaded()``` returns me the following:

```php
[
	(int) 0 => 'Translate',
	(int) 1 => 'Proffer.Proffer'
]
```

If you don't know it yet, Proffer is a behavior inside Proffer plugin, so it's added to Table as follow:

```php
class ConfigsTable extends AppTable
{
    public function initialize(array $config)
    {
        $this->addBehavior('Proffer.Proffer', [
              // Behavior config goes here
        ]);
    }
}
```

Executing ```->behaviors()->loaded()```  after adding that behavior in that context also returns 'Proffer.Proffer'.

**Comment by markstory** [comment]
The fix for this is in #7051. This regression was added in #6942.
