### ISSUE TITLE
Notice in 3.0.9 using FormHelper::input in a belongsToMany field

### ISSUE THREAD

**Issue by daniouyea** [cakephp/cakephp#7061]
When I update from 3.0.8 to 3.0.9 I am notified: **Notice (8): Undefined index: _ids [CORE/src/View/Form/EntityContext.php, line 226]**

### How to reproduce:
In a template, when I edit a post (Posts belongsToMany Tags).
```
    echo $this->Form->create($post);
    echo $this->Form->input('tags._ids', ['options' => $tags]);
    echo $this->Form->end();
```
If the post has tags works fine. If the post hasn't tags fails.

**Comment by markstory** [comment]
Pull request open now.
