### ISSUE TITLE
AuthComponent::logout() doesn't execute when session expire

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#7063]
Hi,
I want to add some logic(eg. update the field logged to 0 in the users table) every time that i logged out an user.
I overwrite the ```AuthComponent::logout()``` method by creating an alias: ```App\Controller\Component\MyAuthComponent.php.```

```MyAuthComponent::logout()``` will be executed **only manually**:
An action in the controller has the ```$this->Auth->logout();``` method like the ```UsersController::logout```. 

If the session expire and i refresh the page(an **automatic** logout), i will be redirected to the logoutAction **without executing** the ```MyAuthComponent::logout()``` method and the logged field in the users table isn't updated !

**Comment by markstory** [comment]
This is expected. Sessions can time out in a few different ways that are hard/impossible for server code to catch:

* Cookies can expire and the browser will stop sending the sessionid. This we cannot catch.
* The client can clear their cookies, effectively expiring their session. This we cannot catch.
* The server timeout can expire a cookie. This we could catch, but given the other gaps there is no point.

I would recommend you don't rely on specifically handling logout. Or write additional code to manually garbage collect stale session data and do your book keeping there. 

I don't think these scenarios are something that CakePHP will ever handle out of the box, so I'm closing.

**Comment by flashios09** [comment]
@markstory Thanks for the explanations :+1: 
I want just to treat the case when the session expire after x seconds of inactivity. I didn't understand why the ```AuthComponent::logout``` isn't executed. What's the method that will be called in this case to force the logout and redirect the user to the logoutAction ?

**Comment by markstory** [comment]
>  What's the method that will be called in this case to force the logout and redirect the user to the logoutAction ? 

You can't really force the logout, as the session has expired, and you no longer know who the user is. However,  the `unauthenticated()` method of each authentication adapter is fired when unauthenticated users are found.

**Comment by flashios09** [comment]
@markstory ah ok now i think that i understand how it works(please correct if i'm saying something wrong), when the session expire there is no $_Session['User'] anymore and because we call the ```unauthenticated()``` method each time we open a page, an unauthenticated user is found so we will have a redirection to the login action. That's why the AuthComponent::logout isn't executed.

**Comment by markstory** [comment]
Correct. Also because the code can't tell how recently a user's session has expired we don't know if this is their first or 100th request since their session expired.
