### ISSUE TITLE
RFC 3.x EventDispatcherInterface and Registries

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#7066]
I think `ObjectRegistry` should check itself whether it implements `EventDispatcherInterface` instead of checking if it has `_eventManager` property and [blind guess](https://github.com/cakephp/cakephp/blob/master/src/Core/ObjectRegistry.php#L285) it implements `eventManager()` method.

This of course would require all registries implement `EventDispatcherInterface`.

BTW I think that `EventManagerTrait` could be also renamed to `EventDispatcherTrait` to better reflect that it implements methods required by `EventDispatcherInterface`.

**Comment by markstory** [comment]
Why does checking the interface require all registries to implement the interface?

**Comment by robertpustulka** [comment]
Sorry, I meant all registries which use `EventManagerTrait`.

**Comment by markstory** [comment]
Renaming the trait with an alais sounds like a good idea to me.

**Comment by markstory** [comment]
Closing as both halves of this have been addressed.
