### ISSUE TITLE
XmlView handles missing viewVars in _serialize differently than JsonView

### ISSUE THREAD

**Issue by catearcher** [cakephp/cakephp#7067]
Consider the following example:
```php
public function foobar() {
  $this->set("_serialize", ["foo", "bar", "extraInfo"]);
  $this->set("foo", 1);
  $this->set("bar", 27);

  $extraInfo = $this->getExtraInfo();
  if ($extraInfo) {
    $this->set("extraInfo", $extraInfo);
  }
}
```

In this snippet, `_serialize` is set to an array of all fields this view *can* return. The `extraInfo` field is omitted if there is no extra info to be included in the response.

If this method is called as `foobar.json`, we always get a valid response. If it is called as `foobar.xml`, and `$extraInfo` is empty, an error is raised because the XmlView does not check whether the view var is actually set.

Is this a bug? Or is `_serialize` expected to contain only keys of view vars that have actually been set?

Personally, I prefer the behaviour of JsonView, because it makes your code much easier to write and understand: It allows you to exit early from methods without having to call `$this->set("_serialize")` every single time, setting it to the names of all view vars that have been actually defined up to this point.

Fixing this - if it really is a valid bug - is easy:
```php
// in XmlView.php
if (array_key_exists($key, $this->viewVars)) {
  $data[$rootNode][$alias] = $this->viewVars[$key];
}
```

**Comment by markstory** [comment]
I agree it shouldn't be possible to trigger a notice error from userland code. XmlView should work like JsonView. @catearcher Would you be able to do a pull request to remedy the issue since you already know what to fix?

**Comment by catearcher** [comment]
@markstory Done!

**Comment by ADmad** [comment]
Closing as PR is opened.
