### ISSUE TITLE
4.0 - RFC - A new folder for controllers actions and prefix

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#7074]
_From @andtxr on July 20, 2015 17:39_

4.0 - RFC - A new folder for controllers actions?

I was wondering about the possibility of adding a new folder to keep the controller actions templates separated from the others.

Right now the agglomeration of similar named folders prevent some prefix naming. For example:

There will be a restriction if someone has decided to use a route prefix like element, email, or any other name that already exists as default template folder.

Another separation that I think may be interesting is to create a folder for prefixed templates.

Sometimes we have folders named like `Admin` for the prefixed templates, and `Admins` for the default admins controller actions.

This is someway visually confusing.

What do you think about the following structure for the action templates?

```
app
|____src
     |____Template
          |____Action
```

And this following one for the prefix folders?

```
app
|____src
     |____Template
          |____Action
               |____Prefix
```

I was wondering about it and I would share with you.

I don`t know if it breaks some MVC patterns that you guys had chosen. If it does, sorry.

_Copied from original issue: cakephp/app#267_

**Comment by jhli** [comment]
So if you got an AdminsController and an admin prefix it would be two folders named Admin and Admins?

**Comment by andtxr** [comment]
Right now it works that way @jhli 

The folder for prefixed actions would keep existing, but inside a Prefix folder.

Following your example, in the current structure we should have:
 
src/Template/Admin/ (the folder for every /admin prefixed actions)
src/Template/Admin/Admins/ (the folder for every /admin prefixed actions of AdminsController)
src/Template/Admins/ (the folder for unprefixed actions of AdminsController)

RFC:

src/Template/Prefix/Admin/ (the folder for every /admin prefixed actions)
src/Template/Prefix/Admin/Admins/ (the folder for every /admin prefixed actions of AdminsController)
src/Template/Admins/ (the folder for unprefixed actions of AdminsController)

But it is just a suggestion. Actually increasing the number of folders do not makes me so much happy too, but I believe that we can discuss and find a nice way.

**Comment by markstory** [comment]
There are a total of 4 conflicting names:

* Cell
* Element
* Layout
* Email

Have you ever actually used any of those as a prefix or are we solving a hypothetical problem?

**Comment by jhli** [comment]
It is about consistency, too. Consistency makes things evident without exceptions. I do like the Action subdir! I am just not sure about the prefix one?

**Comment by andtxr** [comment]
Particularly I never experienced this kind of conflict, but as it is possible to happen and minor view components like the ones mentioned by @markstory has a special treatment, I am inclined to support the Action folder, or any other possible chosen name for it. But I am also in doubt about the Prefix folder.

**Comment by markstory** [comment]
@jhli What is inconsistent about the current state though? The 'special' directories also contain templates, and theoretically you could reuse templates from a Cell and standard action as well. I'm not sure there is an actual problem here that causes people pain in their day to day work. Adding more directories adds complexity and right now feels like change for change's sake to me.

**Comment by ADmad** [comment]
Closing as there doesn't seem to be any support for the suggested changes. We haven't had any other reports of someone being unsatisfied with current folder structure.
