### ISSUE TITLE
Additional find conditions (limit etc) ignored when paginating custom finder method

### ISSUE THREAD

**Issue by voycey** [cakephp/cakephp#7075]
CakePHP Version 2.7.0-dev

Possibly a duplicate of https://github.com/cakephp/cakephp/issues/6047

I'm not quite sure what this issue is - or whether it is simply a non-feature but I have spent a fair amount of time debugging it and I think I can see the reason but don't know the solution:

I have a custom finder that basically mangles some results for me:
```php
protected function _findScopes($state, $query, $results = array()) {
			if ($state === 'before') {
				$query = array_merge($query,
					array(
						'recursive' => -1,
						'contain' => array('User.UserDetail'),
						'conditions' => array(
							'type' => "certification",
							'paid' => 1,
							'archived' => 0,
							'private' => 0
						)
					)
				);
				return $query;
			}

			foreach ($results as $pathway) {
				$pathway['Pathway']['completion'] = $this->calculate_completion($pathway['Pathway']['id']);

				if ($this->PathwaysAnswer->has_completed_scope($pathway['Pathway']['id'], $pathway['Pathway']['level'])) {
					//Only show pathways with completed scope
					if (!empty($pathway['Pathway']['description'])) {
						//Only show pathways with completed scope
						$processed_pathways[] = $pathway;
					}
				}
			}
			return $processed_pathways;
		}
```
I'm guessing it isnt wise to have the query conditions inside the actual custom finder, but rather have them passed in from the controller and ```$this->paginate = ... ``` - but this is where my problem lies, I don't seem to be able to:

At a basic level I call it in the controller as the documentation says:

```php
$this->paginate = array('scopes');
$processed_pathways = $this->paginate();
```

So this part is ok, it returns 8 items (under the standard 20 that is set for pagination so no pagination on this resultset).

However if I now try and add some conditions to the pagination for this custom finder:

```php
$this->paginate = array('scopes' => array('limit' => 1));
$processed_pathways = $this->paginate();
```

I can see that with this the 'scopes' variable is added to the pagination options array:
![image](https://cloud.githubusercontent.com/assets/1065098/8793957/0942d7a0-2fc1-11e5-87dd-ed08a0f8de33.png)

But it never seems to get integrated into the find command, and what's more is my custom finder is never hit and it seems to just default back to a find 'all'.

So I assume that the syntax for ```$this->paginate = array('scopes' => array('limit' => 1))``` is probably wrong (as it just seems to be adding it to the end of the array rather than overriding the defaults) so I tried a bit of hacking such as:

```php
$this->paginate = array('limit' => 1);
$processed_pathways = $this->paginate('scopes');
```
And I get a model not found.

I have also tried loading the Paginator component and setting ```$this->Paginator->settings(array('limit' => 1));```

So is it even possible to paginate a custom finder in this way? If I put the limit into the array in the custom finder it will return the correct number of items but without pagination (I guess it thinks that is the entire result set).

If not - how do I go about paginating anything in a custom finder that requires a different limit than the default? 

Thanks guys

**Comment by voycey** [comment]
After looking at the pull request for the Cake3 version I think this needs to be handled in PaginatorComponent L334:

```php
public function getDefaults($alias) {
		$defaults = $this->settings;
		if (isset($this->settings[$alias])) {
			$defaults = $this->settings[$alias];
		}
		$defaults += array(
            'page'      => 1,
            'limit'     => 20,
            'maxLimit'  => 100,
            'paramType' => 'named'
        );
		return $defaults;
    }
```

I'm just not sure how - is there a detector at this point to check that this has come from a custom finder, because at this point ```$this->settings``` shows my custom finder name + the limit: 

![image](https://cloud.githubusercontent.com/assets/1065098/8794305/b3a48f1e-2fc5-11e5-8782-1bff53f23368.png)

**Comment by voycey** [comment]
I feel like it should be lines
154 - 159 that should be handling this - but I am not sure how to get $options[0] populated.

I have needed a quick fix for this for my project so I have replaced the above lines with the following:

```php

		if (!isset($options['finder'])) {
			$type = 'all';
		} else {
			$type = $options['finder'];
		}
```

This necessitates a change in the paginate call for my custom finder to:

```php 

$this->paginate = array('scopes' => array('limit' => 2, 'contain' => array('User', 'User.UserDetail'), 'finder' => 'scopes'));
$processed_pathways = $this->paginate();
```

I'm sure there is a better way of doing this external to this file but hopefully this will help someone until a proper fix can be put in place.

**Comment by markstory** [comment]
There is no 'finder' option in the [current code](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Controller/Component/PaginatorComponent.php#L154-L159); only 'findType'. Is there a reason you're not using `'findType' => 'scopes'` instead of the 0th value? 

The current code you have where you use the finder name as a key is very unlikely to work as you want. You can completely set additional options for custom finders as they are no different than 'all'. Here is a working example:

```php
// Controller code.
	public function index() {
		$this->Task->recursive = 0;
		$this->Paginator->settings = [
			'Task' => [
				'findType' => 'completed',
				'limit' => 1,
			]
		];
		$this->set('tasks', $this->Paginator->paginate());
		$this->set('_serialize', ['tasks']);
	}

// Model finder
	public $findMethods = ['completed' => true];

	protected function _findCompleted($state, $query, $results = array()) {
		if ($state === 'before') {
			$query['conditions'] = [
				'Task.completed' => true
			];
			return $query;
		}
		return $results;
	}
```

The above all works as it should.

**Comment by voycey** [comment]
This information was tucked away on the pagination page and there was conflicting code on the custom finder types documentation - have submitted a pull request for change - thanks Mark!
