### ISSUE TITLE
'updated (modified)' field not changing when injected in form and $fieldList is provided

### ISSUE THREAD

**Issue by mohsen-ekhtiari** [cakephp/cakephp#7076]
If SecurityComponent is not used and $fieldList array without 'updated' field is set for saving request data and user submits a form with 'updated' field, Cakephp does not change the 'updated' field value. I checked this from the UPDATE query.
It the form is not tampered with 'updated' field, there is no problem. Also if this field is added to $fieldList array, it will be changed with the request data provided.

**Comment by ADmad** [comment]
Please provide the data array, save() statement and resultant query showing the issue.

**Comment by mohsen-ekhtiari** [comment]
```
$data = array(
	'Article' => array(
		'title' => 'test',
		'summary' => 'summary',
		'description' => 'description',
		'category_id' => 1,
		'updated' => '2000-01-01 00:00:00',
	)
);
$this->Article->id = 11;
$this->Article->save($data, true, array('title', 'summary', 'description', 'category_id'));
```
resulted query:
```
UPDATE `db`.`articles` SET `title` = 'test', `summary` = 'summary', `description` = 'description', `category_id` = 1 WHERE `db`.`articles`.`id` = 11
```

**Comment by mohsen-ekhtiari** [comment]
also if I replace `$this->Article->id = 11;` with `$this->Article->create();` to create a new article, I get an error for not providing the field (it is a Not Null field in db):
```
 Error: SQLSTATE[HY000]: General error: 1364 Field 'updated' doesn't have a default value

SQL Query: INSERT INTO `db`.`articles` (`title`, `summary`, `description`, `category_id`, `created`) VALUES ('test', 'summary', 'description', 1, '2015-07-21 12:02:36')
```

**Comment by ADmad** [comment]
Well the error says "'updated' doesn't have a default value" so either you haven't set default null as you claim or you need to clear model cache.

**Comment by ADmad** [comment]
If the `updated` field is explicitly set in data array then you need to include it in `fieldList` too.

**Comment by mohsen-ekhtiari** [comment]
Also I forgot to say if I remove the 'updated' field:
```
$data = array(
	'Article' => array(
		'title' => 'test',
		'summary' => 'summary',
		'description' => 'description',
		'category_id' => 1,
	)
);
$this->Article->id = 11;
$this->Article->save($data, true, array('title', 'summary', 'description', 'category_id'));
```
result query is:
```
UPDATE `db`.`articles` SET `title` = 'test', `summary` = 'summary', `description` = 'description', `category_id` = 1, `updated` = '2015-07-21 12:28:52' WHERE `db`.`articles`.`id` = 11
```
So if someone tampers the form with 'updated' field it will not be changed.
And also I've had not any problem with setting 'created' and 'updated' as Not Null. As you see the create query has 'created' field but not 'updated' field.

**Comment by ADmad** [comment]
For the code provided above the sql query is expected. 

Form tampering is a totally unrelated issue. Use Security component if you want to avoid form tampering.

**Comment by mohsen-ekhtiari** [comment]
So if the sql query is expected, why does cakephp add the 'updated' field to sql query when it does not exist in $data? And removes it from sql query when it exists in $data? This is obviously not a consistant way.

**Comment by ADmad** [comment]
> And removes it from sql query when it exists in $data?

It removed it because you provided a `fieldList` and did not include `updated`. 

If you don't provide `updated` in data it is auto handled for you. If you explicitly provide value for it in data then you also need to explicitly include it in `fieldList`. The behavior is consistent and logical.

**Comment by mohsen-ekhtiari** [comment]
You're right but I think if this field is auto magical and has special meaning it would be more logical if its meaning was preserved even if wrong efforts were made. Or else, simply this behavior could be turned off.
@markstory, could you please inform me of your idea?

**Comment by ADmad** [comment]
> ... would be more logical if its meaning was preserved even if wrong efforts were made.

So you want the framework to just ignore user input and do stuff magically? Good luck having @markstory agree with your opinion.

**Comment by mohsen-ekhtiari** [comment]
> So you want the framework to just ignore user input and do stuff magically?

Yes! When updated filed is not listed in $fieldList, it simply means we want to ignore it. Do you have other opinion?
Documentation says:

> For added security, you can limit the saved fields to those listed in $fieldList.

**Comment by markstory** [comment]
> So you want the framework to just ignore user input and do stuff magically?

Every single time we've done this in the past it has blown up in our (the maintainers of CakePHP) faces. I much prefer interfaces and code that does what it is told. If you are manually setting the updated field, that is the value you should get. There are use cases where the updated field should be manually set and having magic that overwrites user input makes those use cases impossible. By following explicit input we allow both use cases to exist and the way each scenario is accommodated is clear and easy to understand.

**Comment by mohsen-ekhtiari** [comment]
@markstory, I'm only talking about saving model with $fieldList (third parameter of save method) provided.
 I mean when updated is not listed in $fieldList (so it is not expected to be passed in $data) simply ignore its value (as it is done now) but also fill it with the magic value (instead of removing it totally which is done now). Currently if $data has not updated field and it is not listed in $fieldList, cakephp adds this updated automagically.
And when it is expected to set and save updated field as input $data and also $fieldList is provided, simply add updated field to $fieldList.

**Comment by markstory** [comment]
If you are using a `fieldList` then only the fields you whitelist should be saved. No magic. FieldList is a security related option, and I don't feel comfortable adding any conventions or magic around those kinds of features. If you really want, you could use an application behavior to modify the whitelist used for the save operation as it is in a mutable array that is passed to `Model.beforeSave`.

**Comment by lorenzo** [comment]
I think @mohsen-ekhtiari is kind of right in what he expects, `fieldList` is mainly meant for preventing mass assignment, I find it odd that it would prevent automatic timestamp setting.

**Comment by mohsen-ekhtiari** [comment]
@markstory , @lorenzo , I've prepared a comparison:
Please compare these cases (which is current cakephp behavior).
In both the same policy is applied in saving (not whitelisting 'updated' through save's third arument: $fieldList=array('title')).
In the first case, $data contains 'updated' and in the second case not.
But cakephp's generated sql query does not contain 'updated' in first case, and contains in second case.

* Case 1:
```
$data = array(
	'Article' => array(
		'title' => 'test',
		'updated' => '2000-01-01 00:00:00',
	)
);
$this->Article->id = 1;
$this->Article->save($data, true, array('title'));
```
resulted sql query:
```
UPDATE `db`.`articles` SET `title` = 'test' WHERE `db`.`articles`.`id` = 1
```

* case 2:
```
$data = array(
	'Article' => array(
		'title' => 'test',
	)
);
$this->Article->id = 1;
$this->Article->save($data, true, array('title'));
```
resulted sql query:
```
UPDATE `db`.`articles` SET `title` = 'test', `updated` = '2015-07-22 04:16:52' WHERE `db`.`articles`.`id` = 1
```

**Comment by ADmad** [comment]
> I find it odd that it would prevent automatic timestamp setting.

@lorenzo But it's not automatic if `updated` field is provided in data array.

**Comment by ADmad** [comment]
@mohsen-ekhtiari Why are you not using SecurityComponent? 

Apart from this issue there can be other problems if you only rely on `fieldList`. E.g. Form can be tampered to remove a field or modify value of hidden field. Just using `fieldList` is not going to prevent either of those.

**Comment by mohsen-ekhtiari** [comment]
> Why are you not using SecurityComponent? 

@ADmad I do use SecurityComponent for some users actions (even using CAPCHA is some). But I do not use it for administrative actions which are mostly bulk AJAX post operations. Furthermore, I do not use it for mobile app submitting post requests.
Tampering a form to remove a field is not a concern for me. If the field value is required and could not be calculated, the whole request is invalid and throws error.
Changing hidden fields like id are also checked or validated. for example if a user is not allowed to edit an article with some id, he/she is prevented to do so by checking some logic such as being the owner. And if he/she is allowed to do so, he/she can do it any way, as long as not trying to change not-allowed fields like publish_status.
Although CRF is a concern in this way, but logging important changes of database, prevents a possible calamity.

> Form can be tampered to remove a field or modify value of hidden field.

So I do not want someone sending a post request with injected updated field and this action - although not destructive - causes me to lose track of database records' update time.

**Comment by ADmad** [comment]
> So I do not want someone sending a post request with injected updated field and this action

That means you need SecurityComponent, period.

**Comment by mohsen-ekhtiari** [comment]
> That means you do need SecurityComponent.

I think you either not read what I said or not understood my previous comment.
Consider a page listing articles and each article has a button next to it which makes that article either published or unpublished. How do you implement it simply without using an iframe or a GET (!!) reuest with security token? 

And how about api calls or RESTful web services for mobile apps interactions? Do you you of how to implement their POST or PUT actions?

**Comment by markstory** [comment]
@lorenzo I don't completely agree. If a specific value is provided for `updated` we should use that value and not overwrite it.

**Comment by mohsen-ekhtiari** [comment]
@markstory I don't mean to ignore user input. I mean if cakephp drops part of the user input (updated and created fields) because it is not allowed in fieldList array, why not return to its original behavior and fill them with the values it was supposed to and did if those ignored values were not provided?
And if the user is supposed to change these fields (updated and created), why not he/she adds these fields to fieldList array?

Finally, do you mean user can change these fields even if not listed in fieldList array? If so you should not drop it from the query, at least.

**Comment by mohsen-ekhtiari** [comment]
@markstory I don't mean to ignore user input. I mean if cakephp drops part of the user input (updated and created fields) because it is not allowed in fieldList array, why not return to its original behavior and fill them with the values it was supposed to and did if those ignored values were not provided?
And if the user is supposed to change these fields (updated and created), why not he/she adds these fields to fieldList array?

Finally, do you mean user can change these fields even if not listed in fieldList array? If so you should not drop it from the query, at least.

**Comment by markstory** [comment]
@mohsen-ekhtiari Fields not in the `fieldList` cannot be modified by user input.

**Comment by mohsen-ekhtiari** [comment]
@markstory But do you confirm one of the cases 1 and 2 (I mentioned in https://github.com/cakephp/cakephp/issues/7076#issuecomment-123513279) is not desirable? If your answer yes, which one?

**Comment by markstory** [comment]
@mohsen-ekhtiari I think case 1 and 2 are fine with the current behavior. I could see how someone would expect that in case one the updated value would be ignored, and the automatic value would be used instead though.

**Comment by mohsen-ekhtiari** [comment]
@markstory In fact I came to this behavior by an accidental test! I was testing the $fieldList feature to see how it works. And by chance I thought what if someone add an updated field to the form (which all my models have). I expected the newly added updated field by tampering the form (or originally a POST) does not have effect on current behavior of the action because it was banned by $fieldList array.

Although I could and did simply add lines to unset updated and created fields from the request data before saving (not lying on $fieldList array for these two fields) to get the updated field changing with current timestamp, I think it is not intuitive (I found it by chance). And If no actions are to be taken and this should be accepted, I recommend following lines to be added to $fieldList behavior for others:
"Although $fieldList could be used to prevents user from changing updated and created fields, you should remove these fields manually in order to make automatic updating of these fields working".

**Comment by lorenzo** [comment]
@markstory 

* If the value is provided, and allowed in fieldList, the value should be used
* If the value is not provided, the automatic timestamp should be used, regardless of the fieldList
* If the value is provided and is blocked by fieldList, the automatic timestamp should be used. The user is preventing malicious users from manually passing the timestamp, but is definitely not opting out of the feature.

**Comment by markstory** [comment]
@lorenzo OK, lets reopen the issue so we don't forget. I'm guessing the same rules should be applied for `created` fields as well?

**Comment by jhli** [comment]
It means though that you have no easy way of doing blackLists including automatic field as used to (as schema array diff blacklist) and would need to instead manually disable the auto timestamping behaviour.

**Comment by markstory** [comment]
#7357 fixes this issue.

**Comment by mohsen-ekhtiari** [comment]
Thank you. Would you mind doing this for created field too?

**Comment by mohsen-ekhtiari** [comment]
Sorry I was wrong. You did great. I did not see 'created' field in your test code, so I thought you have missed it.
Thanks a lot. The issue is fully resolved.
