### ISSUE TITLE
2.7 JsonView throw warning with PHP < 5.3

### ISSUE THREAD

**Issue by arilia** [cakephp/cakephp#7083]
Just upgraded from 2.6.3 to 2.7 and I get this warning

    json_encode() expects exactly 1 parameter, 2 given in /var/www/sic/lib/Cake_2_7_0/View/JsonView.php, line 164]

I'm using PHP 5.2.9

**Comment by ADmad** [comment]
The fact that PHP version requirement for 2.7 has been bumped to PHP 5.3 isn't mentioned anywhere besides [composer.json](https://github.com/cakephp/cakephp/blob/2.7/composer.json#L21) :(

**Comment by ADmad** [comment]
Fixed in cakephp/docs#2978

**Comment by ADmad** [comment]
Reopening issue since as stated [here](https://github.com/cakephp/docs/pull/2978#issuecomment-123370571) problem exists in 2.6.5 also.

**Comment by josegonzalez** [comment]
Technically its fine for 2.7 to have this issue, but not 2.6. Should we make a new release of 2.6?

**Comment by ADmad** [comment]
We should.

**Comment by markstory** [comment]
Fixed with 2.6.10
