### ISSUE TITLE
cake 3.0.9 Conflicting view variables ($event and $events) creates very obtuse error

### ISSUE THREAD

**Issue by glkaup** [cakephp/cakephp#7084]
I made a mistake in a Table Function trying to create a ->find('list') for an view select input.  The error was using an Object as an integer.  But during debug, the ->find('list', $params) was performed creating a new object.  

Proceeding to the view, when trying to create a select using the same object, I got the following error log.  Since the ORM delayed the execution of the sql until it actually needed data, it reports the error in the view creation instead of when executing the query build in the Model(Table) function.

 The DebugKit log follows:

`Notice (8): Object of class App\Model\Entity\Event could not be converted to int in [E:\ezshoot.git\vendor\cakephp\cakephp\src\Database\Type\IntegerType.php, line 44] Trace: Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139 Cake\Database\Type\IntegerType::toDatabase() - CORE\src\Database\Type\IntegerType.php, line 44 Cake\Database\Statement\StatementDecorator::cast() - CORE\src\Database\TypeConverterTrait.php, line 37 Cake\Database\Statement\PDOStatement::bindValue() - CORE\src\Database\Statement\PDOStatement.php, line 70 Cake\Database\Statement\StatementDecorator::bindValue() - CORE\src\Database\Statement\StatementDecorator.php, line 103 Cake\Database\Log\LoggingStatement::bindValue() - CORE\src\Database\Log\LoggingStatement.php, line 96 Cake\Database\Statement\StatementDecorator::bind() - CORE\src\Database\Statement\StatementDecorator.php, line 288 Cake\Database\ValueBinder::attachTo() - CORE\src\Database\ValueBinder.php, line 125 Cake\Database\Connection::run() - CORE\src\Database\Connection.php, line 273 Cake\Database\Query::execute() - CORE\src\Database\Query.php, line 175 Cake\ORM\Query::_execute() - CORE\src\ORM\Query.php, line 657 Cake\ORM\Query::_all() - CORE\src\Datasource\QueryTrait.php, line 218 Cake\ORM\Query::all() - CORE\src\ORM\Query.php, line 608 Cake\ORM\Query::getIterator() - CORE\src\Datasource\QueryTrait.php, line 132 iterator_to_array - [internal], line ?? Cake\View\Widget\SelectBoxWidget::_renderContent() - CORE\src\View\Widget\SelectBoxWidget.php, line 146 Cake\View\Widget\SelectBoxWidget::render() - CORE\src\View\Widget\SelectBoxWidget.php, line 115 Cake\View\Helper\FormHelper::widget() - CORE\src\View\Helper\FormHelper.php, line 2545 Cake\View\Helper\FormHelper::select() - CORE\src\View\Helper\FormHelper.php, line 1885 Cake\View\Helper\FormHelper::_getInput() - CORE\src\View\Helper\FormHelper.php, line 1114 Cake\View\Helper\FormHelper::input() - CORE\src\View\Helper\FormHelper.php, line 1037 include - APP/Template\Admin\EventClasses\edit.ctp, line 29 Cake\View\View::_evaluate() - CORE\src\View\View.php, line 834 Cake\View\View::_render() - CORE\src\View\View.php, line 794 Cake\View\View::render() - CORE\src\View\View.php, line 465 Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 582 Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120 Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87 [main] - ROOT\webroot\index.php, line 37	`

**Comment by ADmad** [comment]
So what do you expect the framework to do?

**Comment by markstory** [comment]
This doesn't seem like an issue with CakePHP but more how you've used it.

**Comment by GuidoHendriks** [comment]
Although I get that you just shouldn't use reserved keywords, I feel like this is going to be an issue for more people. Events is quite a general term to use, pretty sure I have used it in some project before. 

Isn't there anything we could do to make it a bit easier to know what's going wrong? When in debug, checking for reserved names when setting variables and giving a notice if they use one. Sounds like something that could help some people out. 

Just my two cents. :)

**Comment by ADmad** [comment]
There are no "reserved" view var names enforced by the core.

**Comment by markstory** [comment]
From the stack trace it looks like you have something wrong with your query conditions, as an event object could not be cast into an int when binding the parameters for the query that was going to be executed.

**Comment by glkaup** [comment]
@markstory Yes Mark you're right... however... my real issue here is why does the stack trace start at index.php and go down thru FormHelper to SelectBoxWIdget::render when the actual invalid use of an Object was performed in a Table Function used by the controller.  The stack trace is of no real value since there are over 12 other queries and a half dozen select boxes in the view.

I did try to change the subject of this message, and even tried to delete it altogether when I finally found MY illegal use of an Object... but ... here we are.  Sorry to have wasted your time.

**Comment by markstory** [comment]
The stack trace starts in index.php as that's the origin of all request handling in CakePHP apps. As for why the stack trace ends in the selectbox. This is a result of query objects lazily evaluating. A query object doesn't execute until you start to fetch results from it. In your case this happened in the selectbox generation. You can force query evaluation by using `all()`, or `first()` as an example.

**Comment by glkaup** [comment]
On last question... would it be possible for cakePHP to have a "debug" mode or other setting that would turn off lazy evaluating?

**Comment by markstory** [comment]
@glkaup Possible, but I don't think its a good idea. Just imagine how frustrating your scenario would be if you only ran into it in production?
