### ISSUE TITLE
How does cakephp deal with models that don't end with 's' (as plural)?

### ISSUE THREAD

**Issue by ahmedtabrez** [cakephp/cakephp#7094]
<div class="post-text" itemprop="text">

<p>Let's say we want to create a model for entities like <code>children</code> and <code>indices</code> whose singulars are <code>child</code> and <code>index</code> respectively and not something we get by simply removing 's' from the end.</p>

<p><strong>Are such models compatible with cakephp ?</strong>
 Can <code>ChildrenController</code> be the controller of <code>Child</code> model?</p>

<p><strong>If not, How to work around such models?</strong> provided that we aren't allowed to disturb the singular/plural words of english language? (eg. we can't pluralise <code>child</code> by making it <code>childs</code>.)</p>
    </div>

**Comment by ADmad** [comment]
Normal English singularization / pluralization rules are used. Plural of `child` is `children` and vice versa, so that's what should be used in naming.

**Comment by ahmedtabrez** [comment]
@ADmad, thanks .... I request the developers to make a mention of this in the docs. Thankyou.

**Comment by ADmad** [comment]
It already [is](http://book.cakephp.org/3.0/en/intro/conventions.html). The examples using  `person` to `people` makes it pretty clear that normal English grammar rules are followed.

**Comment by ADmad** [comment]
Whenever in doubt you can also use http://inflector.cakephp.org/ to check inflections for a word.

**Comment by ahmedtabrez** [comment]
Yup got it .... Thanks again @ADmad. Does Cakephp maintain a copy of such words in the core? or how does it deal with such exceptions?

**Comment by ADmad** [comment]
Check the code for `Cake\Utility\Inflector` class. 

If you have further queries please ask on stackoverflow or the IRC channel. This issue tracker is not a help forum.

**Comment by ahmedtabrez** [comment]
Got it ... Thanks ...
