### ISSUE TITLE
Cake\I18n\Time numeric sorting in collection

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/cakephp#7095]
Not sure if this is is a framework issue or I'm doing something wrong with the ORM. I'm querying a couple different models and using a collection to display them sorted by the `modified` property to make a makeshift news feed. This is on the latest Cake release, 3.0.9.

The problem is in the sortBy method for the Collection. The expected behavior is all the various models to be in the `$recent` collection and sorted by their `modified` date descending. 

The only sort method that returns as expected is `SORT_NUMERIC`, but it throws the error: `Object of class Cake\I18n\Time could not be converted to double` twice. Changing to `SORT_NATURAL`, `SORT_STRING`, `SORT_LOCALE_STRING` or leaving the sort option off will display the wrong entities based on the date. 
 
```php
        $recent_uploads     = $this->Users->Uploads->find('recent')->limit(10)->all();
        $recent_charts      = $this->Users->Clients->Charts->find('recent')->limit(10)->all();        
        $recent_users       = $this->Users->find('recent')->limit(10)->all();

        $recent = (new Collection([]))
            ->append($recent_charts)
            ->append($recent_uploads)
            ->append($recent_users)
            ->sortBy('modified', SORT_DESC, SORT_NUMERIC)
            ->take(10);

        $feed = $recent->toArray();
```

Suppressing the error will also cause the incorrect sort order. I tried also just passing the result sets into the new collection, but the sort ordering was incorrect as well. 

Any help or direction would be greatly appreciated. Thanks!

**Comment by lorenzo** [comment]
Hmm, this is annoying... I'll take a look at it

**Comment by antograssiot** [comment]
Closing as #7153 is open now
