### ISSUE TITLE
Disabling plugin behavior

### ISSUE THREAD

**Issue by yskkin** [cakephp/cakephp#7098]
I'm using SoftDelete behavior https://github.com/CakeDC/utils with CakePHP 2.7.0.

`$actsAs = array('Utils.SoftDelete');` works fine for setting up behavior and
`$this->MyModel->Behaviors->unload('Utils.SoftDelete');` in controller works fine for unloading behavior.

However, `$this->MyModel->Behaviors->disable('Utils.SoftDelete');` does not work and instead,
`$this->MyModel->disable('SoftDelete');` works.

**Comment by markstory** [comment]
Fixed with #7106
