### ISSUE TITLE
CakePHP 3 weird BTM errors

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#7099]
Have a new error after an update of CakePHP (3.0 > 3.0.10). i've got 3 models:

### Model : ClasseOuvragesTable.php

    class ClasseOuvragesTable extends Table
    {
        /**
         * Initialize method
         *
         * @param array $config The configuration for the Table.
         * @return void
         */
        public function initialize(array $config)
        {
            $this->primaryKey('id');
            $this->displayField('nom');
    
            $this->hasMany('Ouvrages');
    
            $this->belongsTo('Couches');
    
            $this->belongsTo('CompteClients');
    
            $this->belongsToMany('ClasseElements', [
                'through'   => 'classe_elements_classe_ouvrages',
                'dependent' => true,
                'cascadeCallbacks' => true
            ]);
    
            $this->addBehavior('Timestamp');
        }
    }

### Model : ClasseElementsTable.php

    class ClasseElementsTable extends Table
    {
        /**
         * Initialize method
         *
         * @param array $config The configuration for the Table.
         * @return void
         */
        public function initialize(array $config)
        {
            $this->primaryKey('id');
            $this->displayField('nom');
    
            $this->belongsToMany('ClasseOuvrages', [
                'through'   => 'classe_elements_classe_ouvrages',
                'dependent' => true,
                'cascadeCallbacks' => true
            ]);
    
            $this->hasMany('Caracteristiques', [
                'dependent'        => true,
                'cascadeCallbacks' => true
            ]);
    
            $this->hasMany('Elements', [
                'dependent'        => true,
                'cascadeCallbacks' => true
            ]);
        }
    }
    
### Model : ClasseElementsClasseOuvragesTable.php

    class ClasseElementsClasseOuvragesTable extends Table
    {
        /**
         * Initialize method
         *
         * @param array $config The configuration for the Table.
         * @return void
         */
        public function initialize(array $config)
        {
            $this->table('classe_elements_classe_ouvrages');
    
            $this->belongsTo('ClasseOuvrages');
            $this->belongsTo('ClasseElements');
        }
    }
    
when i'm trying to do this query:

    $this->ClasseElements->find('list')
        ->matching('ClasseOuvrages', function ($q) use($someCdt) {
            return $q->where($someCdt);
        })
        
it fail and give me those errors:

> Warning (4096): Argument 1 passed to Cake\Database\Expression\QueryExpression::_addConditions() must be of the type array, null given, called in C:\wamp\www\SagaV2\vendor\cakephp\cakephp\src\Database\Expression\QueryExpression.php on line 124 and defined [CORE\src\Database\Expression\QueryExpression.php, line 503]
> Warning (2): Invalid argument supplied for foreach() [CORE\src\Database\Expression\QueryExpression.php, line 509]

but if i'm doing a contain it's all good:

    // It works
    $this->ClasseElements->find('list')
        ->contain(['ClasseOuvrages' => function ($q) use($someCdt) {
            return $q->where($someCdt);
        }])

**Comment by ADmad** [comment]
"through" option is supposed to be a table class name, not actual db table name.

**Comment by GLacourt** [comment]
Sure you rigth however i wrote my tables above to give u a lot of information, actually i'm respecting the conventions so i don't really need the third model but at least it's declared.

I'm trying to solve it but i don't know what i'm doing wrong really. it worked last week.

**Comment by lorenzo** [comment]
@GLacourt You just need to use the right class name for that option, or just leave it empty

**Comment by GLacourt** [comment]
I really don't understand, i'm using the right name, and the generated query is good, it's just those warnings. When i'm using contain i don't have this issue.

**Comment by lorenzo** [comment]
Do you have a class named "classe_elements_classe_ouvrages"? It should probably be "ClasseElementsClasseOuvrages"

**Comment by GLacourt** [comment]
Yeah i declared one, i made a mistake i wanted use `joinTable` key and not `through`. As i said i'm respecting the conventions so if i just use `$this->belongsToMany('ClasseElements');` it works also.

the worst here (or i'm missunderstand something) it's if i'm doing this:
    $this->ClasseElements->find('list')
        ->matching('ClasseOuvrages', function ($q) use($someCdt) {
            return $q->where($someCdt);
    });

I got those warnings but if i'm doing this:

    $this->ClasseElements->ClasseOuvrages->find('list')
        ->matching('ClasseElements', function ($q) use($someCdt) {
            return $q->where($someCdt);
    });

got nothing, the association is well built

**Comment by lorenzo** [comment]
What is the configuration that makes the error happen?

**Comment by ndm2** [comment]
@lorenzo It seems that empty conditions passed to `where()` cause `null` to end up in `Query::join()` when associations are being attached. This happens in `attachTo`, where the dummy query will return the default value for the `where` part, which is `null`.

**https://github.com/cakephp/cakephp/blob/3.0.10/src/ORM/Association.php#L545-L549**

**Comment by GLacourt** [comment]
Database config:

![diagram](https://cloud.githubusercontent.com/assets/9000415/8852208/1efd7700-3154-11e5-989d-a11144d319e1.png)
![diagram1](https://cloud.githubusercontent.com/assets/9000415/8852209/1eff28a2-3154-11e5-8395-4b9df4f702c1.png)
![diagram2](https://cloud.githubusercontent.com/assets/9000415/8852210/1f020644-3154-11e5-9683-04bb5ee05cd6.png)

the query:

    $customerIds = $this->CompteClients
        ->find('path', ['for' => $compteClientId])
        ->select(['CompteClients.id'])
        ->listNested()
        ->printer('id', 'id')
        ->toList();
        
    $classeElements = $this->ClasseElements
        ->find($type, $options)
        ->matching('ClasseOuvrages.CompteClients')
        ->where(['CompteClients.id IN' => $clientsIds]);
        
the query built: (works well)

    SELECT 
        ClasseElements.id AS `ClasseElements__id`, 
        ClasseElements.nom AS `ClasseElements__nom` 
    FROM classe_elements ClasseElements 
        INNER JOIN classe_ouvrages ClasseOuvrages 
            ON 1 = 1 
        INNER JOIN classe_elements_classe_ouvrages ClasseElementsClasseOuvrages 
            ON (ClasseElements.id = (ClasseElementsClasseOuvrages.classe_element_id) 
            AND ClasseOuvrages.id = (ClasseElementsClasseOuvrages.classe_ouvrage_id)) 
        INNER JOIN compte_clients CompteClients 
            ON CompteClients.id = (ClasseOuvrages.compte_client_id) 
    WHERE CompteClients.id in (:c0)

**Comment by lorenzo** [comment]
@ndm2 do you have an example?

**Comment by ndm2** [comment]
Sure, here's a test

```php
public function test7099()
{
    $table = TableRegistry::get('articles');
    $table->belongsToMany('tags');

    $table
        ->find()
        ->matching('tags', function ($q) {
            return $q->where([]);
        })
        ->all();
}
```

**Comment by lorenzo** [comment]
@ndm2 please open another ticket with that test case, That will help having a clean track of the error

**Comment by ndm2** [comment]
@lorenzo Done so...
