### ISSUE TITLE
Attaching associations trips over empty conditions 

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#7102]
Empty conditions for `matching()` are causing `null` to be passed to `QueryAssociation::_addConditions()`, resulting in an error as an array is being expected.

> Argument 1 passed to Cake\Database\Expression\QueryExpression::_addConditions() must be of the type array, null given, called in \src\Database\Expression\QueryExpression.php on line 124

Here's a test case that triggers the error:

```php
public function test7099()
{
    $table = TableRegistry::get('articles');
    $table->belongsToMany('tags');

    $table
        ->find()
        ->matching('tags', function ($q) {
            return $q->where([]);
        })
        ->all();
}
```

The `null` value stems from the dummy query, where `clause()` will return the default value, which is `null`.

**https://github.com/cakephp/cakephp/blob/3.0.10/src/ORM/Association.php#L545-L549**

Refs #7099

**Comment by markstory** [comment]
I can take a look at this.

**Comment by markstory** [comment]
This issue was caused by #7028.

**Comment by markstory** [comment]
Pull request with a fix is up now.
