### ISSUE TITLE
Setter method call in EntityTrait

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#7115]
Hello,
I would like to know what's the reason to have the following piece of code in the way it is, in EntityTrait:

https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L252-L256

In these lines of code, it calls the setter method of an entity (if it exists) and then expects the property being set to be returned by the setter to, again, force a manually property setting into properties data structure. What's the meaning of that?

If there is an already defined a setter, the responsibility to set the properties should be entirely relied into the setter, shouldn't it? 

I understand that it should be some defensive programming to avoid the property not being set if the setter doesn't actually set the property properly, but if it does but doesn't return the property which was just set, it will be set to null. This kind of thing is annoying and can cause undesired effects, such as in patchEntity method with associations.

**Comment by markstory** [comment]
> In these lines of code, it calls the setter method of an entity (if it exists) and then expects the property being set to be returned by the setter to, again, force a manually property setting into properties data structure. What's the meaning of that?

The setter methods are expected to return the property value to be set, not set them directly. This was done to help reduce repetitive code in each/every setter method.

> I understand that it should be some defensive programming to avoid the property not being set if the setter doesn't actually set the property properly, but if it does but doesn't return the property which was just set, it will be set to null. 

Null is a valid state for properties. The setter code cannot assume that null means the property shouldn't be modified.
