### ISSUE TITLE
HttpSocket chocks on 0 in data stream

### ISSUE THREAD

**Issue by nfedyk** [cakephp/cakephp#7121]
When ```$this->read()``` returns a string of 0 while loop exists without fetching the rest of stream data.
There should be a check for proper boolean false on data read.
![screen shot 2015-07-27 at 5 44 32 pm](https://cloud.githubusercontent.com/assets/223364/8918665/7365ca32-3487-11e5-8a25-9f0110de89c1.png)

**Comment by nfedyk** [comment]
I fixed it with the following code, instead of 
```php
		while ( $data = $this->read() ) {
```
I used
```php
		while ( true ) {
		    $data = $this->read();
		    if ( $data === false ) break;
```

**Comment by markstory** [comment]
What version of CakePHP are you using?

**Comment by markstory** [comment]
Pull request open now.

**Comment by nfedyk** [comment]
Thank you for quick response.
