### ISSUE TITLE
Missing Memcached->add() method

### ISSUE THREAD

**Issue by nebojsac** [cakephp/cakephp#7122]
I needed this today as it's very useful for atomic Memcached setting that helps avoid overwriting the same key. Ended up adding it to my core files, and it works as advertised so I thought I'd send it this way.

I'm a bit new to how this contributing on github works, so please let me know if I need to do something differently, if this is even something you'd want to add.

It adds an add() method to Cache.php and an add() method to MemcachedEngine.php.

This is the commit: https://github.com/nebojsac/cakephp/commit/06dc2eb32c41ce22558ca0b187822737f84e7550

**Comment by markstory** [comment]
Having a method that is only supported by one backend is generally something we avoid as it makes the interface/abstraction less useful. Backends are supposed to be swappable, which stops working if methods simply don't work in the majority of backends.

If we could come up with implementations for the other backends, even if the guarantees around atomic set were looser, there would be a better chance of this getting merged.

**Comment by nebojsac** [comment]
Makes sense. From what I can see, Redis, Memcache and APC have the equivalent "add only if not exists" method built in so it's worth adding it in, and implementations for the rest shouldn't be a problem.

The bigger issue for me would be testing some of them(like WinCache) after I've added them. But since I'd basically just be re-using the already implemented get/set stuff it might be fine. I'll come back with an update soon.

**Comment by nebojsac** [comment]
Added equivalent add() methods to other Cache engines, where available(Redis, APC, Memcache). Otherwise made non-atomic implementations.

https://github.com/nebojsac/cakephp/commit/f95e1e2392a442180915790dd7951d475d01dbfb

**Comment by nebojsac** [comment]
Updated Cache and CacheEngine https://github.com/nebojsac/cakephp/commit/596b7fad7e974d852661ce730aa2a90d34e95776

**Comment by markstory** [comment]
Looking pretty good. If you fixed up the coding standards, and added some tests, this would make a good pull request now.

**Comment by nebojsac** [comment]
Thanks for the feedback! Finally got back to this. Fixed coding standards(sorry if I missed any of them) and added tests:
https://github.com/nebojsac/cakephp/commit/bb3e69fa9e850593d8f346069706c81fa82a9f74

**Comment by markstory** [comment]
@nebojsac Could you make a pull request with those changes?

**Comment by nebojsac** [comment]
@markstory done!
https://github.com/cakephp/cakephp/pull/7165

**Comment by nebojsac** [comment]
Should I have merged it into the master branch first?

**Comment by markstory** [comment]
Closing as we can continue discussion in  #7165
