### ISSUE TITLE
Regression with date year dropdown and empty value

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7123]
The form itself has a (upgraded from 2.x to have 0 as empty value key)
```php
echo $this->Form->input('birthday', ['empty' => [0 => '- -']]);
```
The form is just fine, 3 dropdowns and the year range is as expected:
```html
...
<select name="birthday[year]" class="form-control">
<optgroup label="">
    <option value="0">- -</option>
</optgroup>
<option value="2020">2020</option>
<option value="2019">2019</option>
<option value="2018">2018</option>
<option value="2017">2017</option>
<option value="2016">2016</option>
<option value="2015">2015</option>
<option value="2014">2014</option>
<option value="2013">2013</option>
<option value="2012">2012</option>
<option value="2011">2011</option>
<option value="2010">2010</option>
</select>
```

But once posted the range becomes huge, adding in all values from 0. Whereas it should just stay at the first empty value of the form).

Not sure if the optgroup part is necessary or desired, that wasn't the case with 2.x.

**Comment by markstory** [comment]
Why isn't the empty value a string?

**Comment by dereuromark** [comment]
As mentioned above that was the 2.x way of defining the key as not `''` but `'0'`.
But if that is now a limitation that is on purpose, I am fine with always sticking to `''`.

**Comment by markstory** [comment]
But why is a key needed at all? Are you trying to set the empty state of just one input?

**Comment by chinpei215** [comment]
Is that a way to specify the value of an 'empty' option? I have just learned it :)
```php
echo $this->Form->input('field', [
	'options' => [1, 2, 3],
	'empty' => [ -2147483648 => '(choose one)' ]
]);
```
```html
<option value="-2147483648">(choose one)</option>
```
Indeed, 3.x outputs an unnecessary optgroup.
```html
<optgroup label=""><option value="-2147483648">(choose one)</option></optgroup>
```

**Comment by markstory** [comment]
Ok, I understand what is going on here now. I will look into a fix.

**Comment by markstory** [comment]
Pull request up now.
