### ISSUE TITLE
3.x TranslateBehavior::groupTranslations fails for empty hasOne properties.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#7127]
Following example:
```php
    public $fixtures = [
        'core.translates',
        'core.attachments',
        'core.comments',
    ];

    public function testTranslations()
    {
        $locator = new TableLocator;
        
        $attachments = $locator->get('Attachments');
        $comments = $locator->get('Comments');
        $attachments->addBehavior('Translate');
        $comments->addBehavior('Translate');

        $comments->hasOne('Attachments', [
            'targetTable' => $attachments
        ]);

        $query = $comments->find('translations')->contain(['Attachments' => function($q){
            return $q->find('translations');
        }]);

        $query->toArray();
    }
```

fails with:
> Fatal error: Call to a member function get() on a non-object in ROOT/vendor/cakephp/cakephp/src/ORM/Behavior/TranslateBehavior.php on line 451

`$row` in `TranslateBehavior::groupTranslations()` appears to be `null`. I think it fails when a `$comment` has no `$attachment` associated with it.

Using 3.1 dev branch.

**Comment by lorenzo** [comment]
Do you have an idea for how to fix this?

**Comment by robertpustulka** [comment]
Simple check for `if ($row instanceof EntityInterface)` in groupTranslations seems like a quick fix, but I'm not sure it's the right solution.

**Comment by lorenzo** [comment]
That actually sounds like a good solution

**Comment by dereuromark** [comment]
Closing as PR is now open.
