### ISSUE TITLE
[RFC] PHP 7 use assert() where we expect user errors to happen

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#7128]
An idea for the future, when we decide using PHP 7 features.

The more we maintain the code, the more defensive error we add, this improves the user experience as developers get informed of their errors before finding them in production. We should add more, but one of the reason I have not added a lot of them is that some are expensive to calculate.

The idea then is to migrate all developer error handling to use `assert()` instead of normal code + custom exceptions. This will help us add more and without negatively affecting performance in production.

**Comment by markstory** [comment]
Is the thinking that we would disable assert() in production environments or rely on php server config?

**Comment by lorenzo** [comment]
For now I would rely on server config, but we could look into offering a way for conditionally toggle it.

**Comment by markstory** [comment]
I bet lots of people will make a mistake in their server config and leave assert() enabled :cry:. Perhaps it could be an opportunity for us to educate people though.

**Comment by ADmad** [comment]
> Perhaps it could be an opportunity for us to educate people though.

I hope it doesn't require educating shared hosting providers too :stuck_out_tongue:

**Comment by dakota** [comment]
> I hope it doesn't require educating shared hosting providers too :stuck_out_tongue:

Luckily that's something we won't need to worry about for a couple of years :trollface:

**Comment by lorenzo** [comment]
@markstory Well, as long as they have `debug => false` the only downside to doing that is a performance hit

**Comment by markstory** [comment]
I wonder how many cases there are where people are catching defensive errors and ignoring them. It looks like the assert handler could use debug to toggle exceptions/logging which is nice.

**Comment by jippi** [comment]
please, please don't sacrifice speed for people being stupid :)

**Comment by lorenzo** [comment]
That is exactly what this ticket is about, have the benefits of defensive programming without the performance hit

**Comment by AD7six** [comment]
This sounds like a good idea to me.

**Comment by markstory** [comment]
From the docs, assert() allows you to put assertion conditions as strings, which are only evaluated if assert() is turned on. That would help improve performance if assert() was disabled @jippi

**Comment by ADmad** [comment]
Setting `zend.assertions` to `-1` makes it zero cost for production use.  [Ref](https://github.com/tpunt/PHP7-Reference#expectations)

**Comment by ravage84** [comment]
:+1: to the idea and :sunglasses: to use the opportunity to educate people.

**Comment by Marlinc** [comment]
That sounds like a great improvement over things like ```trigger_error``` :+1:

**Comment by inoas** [comment]
> this improves the user experience as developers get informed of their errors before finding them in production

Great! Looking forward to PHP 7.x based CakePHP ;)

**Comment by ADmad** [comment]
Is this something we want to do in Cake 4?

**Comment by markstory** [comment]
I think we can hold off for 4.0. I think we should see how folks react to the additional typehints and strict_types behavior that have been added in 4.0 before layering more on.
