### ISSUE TITLE
i18nFormat() on a non-object

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7130]
I have the following column in my database:

```
birthday date DEFAULT NULL
```

As you can see the value for the field can be `NULL` for example if a user don't want to provide the birthday date. Now I want to show all users in my admin area in a list. Some users have a valid birthday date, others have `NULL`. The problem is that `i18nFormat` will result in a fatal error when you call it with a `NULL` value. For sure this will fail but use an if condition before feels wrong:

```
if ($user->birthday) {
     $user->birthday->i18nFormat();
}
```

**Comment by lorenzo** [comment]
Yes, that is standard PHP, you need to check if there is a value before calling method on it. You can use `$entity->has('field') ? $entity->field->method()` in your templates
