### ISSUE TITLE
Possible Paginator sort bug?

### ISSUE THREAD

**Issue by jeanbez** [cakephp/cakephp#7132]
Hello,

When I try to define the default order in the pagination using the 'order' key alone everything works ok, the same can be said when using the pagination sort in the view by defining the 'sortWhitelist'. However those two options do not work correctly when combined. The code is bellow, please let me know if I am  doing something wrong.

```php
        $this->paginate = [
            'contain' => [
                'Authors', 
                'Origins'
            ],
            'order' => [
                'Problems.id' => 'ASC'
            ],
            'sortWhitelist' => [
                'id',
                'name',
                'subject',
                'solved',
                'level'
            ],
            'limit' => 30
        ];
```

**Comment by markstory** [comment]
What isn't working the way you expected?

**Comment by jeanbez** [comment]
Well, I expected the results to be order by id when first opening the page, however that i not true, they appear on random order. Only when I click on the id they get sorted.

**Comment by markstory** [comment]
Well Problems.id is not in the whitelist.

**Comment by dereuromark** [comment]
Yep, the 'sortWhitelist' does not contain the `Problems.id`, only the primary id. Closing as invalid.

**Comment by jeanbez** [comment]
Got it! But I found quite strange since both id and Problems.id refer to the primary key (primary id) for that table. And if you only use the Problems.id in the 'order' option without setting the 'sortWhitelist' Cake sorts it...

**Comment by dereuromark** [comment]
I wonder if we can make it less strict here (Primary.id === id). But as of right now the outcome is as expected.
