### ISSUE TITLE
[2.7.1] Console throws error when mb_ functions emulated

### ISSUE THREAD

**Issue by boshrin** [cakephp/cakephp#7135]
It appears that sometime between 2.6 and 2.7.1 Inflector::underscore and some other functions were made multibyte aware. However, when the native PHP functions are not available, this generates an error with Console:

    % ./Console/cake
    PHP Fatal error:  Call to undefined function mb_strtolower() in /mnt/hgfs/src/comanage/git/registry/lib/Cake/Utility/Inflector.php on line 487
    
    Fatal error: Call to undefined function mb_strtolower() in /mnt/hgfs/src/comanage/git/registry/lib/Cake/Utility/Inflector.php on line 487

Tracing through the code, this appears to be because Configure::bootstrap() is called before the mb emulation functions are defined. Configure::bootstrap() calls App::init(), which calls Cache::read(), which calls FileEngine::key(), which calls Inflector::underscore(), which calls mb_strtolower(), which hasn't yet been defined, throwing the error above.

A simple fix appears to be to move the call to Configure::bootstrap() to the end of bootstrap.php:

    % diff lib/Cake/bootstrap.php lib.old/Cake/bootstrap.php 
    174a175,176
    > Configure::bootstrap(isset($boot) ? $boot : true);
    > 
    439,440d440
    < 
    < Configure::bootstrap(isset($boot) ? $boot : true);

though I don't know if that has some other ramifications...

**Comment by markstory** [comment]
Seems pretty safe given the code in the middle of those lines. Pull request open now.
