### ISSUE TITLE
Add a toRaw() function to a query result

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#7137]
when working with a very big query resultset, disable marshalling is not enough to improve performance.
disabling marshalling will not create a new entity but the fields like datetime will be always parsed.

for example calling toArray() on a big resultset with some datetime fields, will always parse all datetime fields to create a Time object. this is not always necessary.

this can be resolved create a toRaw method that return directly the result taken from the datasource layer (for example the result of PDOStatement::fetchAll)

**Comment by markstory** [comment]
Have you tried using unbuffered queries? That at least defers loading all the data into memory.

**Comment by markstory** [comment]
Also if you don't want all the typecasting features you can use the connection class to execute queries and get low level statement objects.

```php
$conn = ConnectionManager::get('default');
$statement = $conn->execute('SELECT * FROM users');
```

**Comment by doshu** [comment]
Using ConnectionManager is not bad, but doesn't allow to use the power of query builder

**Comment by lorenzo** [comment]
I think having a feature to disable type casting (the actual slow part of the result set class) could be handy... something like `$query->castResults(false)`

**Comment by markstory** [comment]
@doshu You should be able to use the Cake\Database\Query class to get a query builder for the lower level APIs I think.

@lorenzo How would that mode interact with hydrate()?

**Comment by lorenzo** [comment]
@markstory they are not actually related, hydration does not depend on casting. I would expect that in most of the cases someone wanting raw values would also opt-out of object hydration

**Comment by markstory** [comment]
Would it be useful to have casting off, and hydration on? I'm not sure re-saving those entities will always work well.

**Comment by doshu** [comment]
$query->castResults(false) should be for speed up query. enable hydration and disable object casting have no sense. In some cases could be usefull to use hydration with no object casting, but this is not the main goal of this proposal

**Comment by markstory** [comment]
Sure, but the orm would have to continue working correctly even when modes that shouldn't be used together are. What I want to avoid is adding modes that create more issue reports than they solve.

I feel like there are a few different suggestions here already that would allow you to address the performance issues you are experiencing. Each solution is not without tradeoffs, but adding modes also has tradeoffs.

**Comment by jhli** [comment]
Should be named raw() simular to sql() imho
