### ISSUE TITLE
3.0 PaginatorHelper::numbers() doesn't work well with option 'modulus'

### ISSUE THREAD

**Issue by yskm** [cakephp/cakephp#7143]
```php
echo $this->Paginator->numbers([
    'first'   => 1,
    'last'    => 1,
    'modulus' => 0
])
```

I expect that this code output like this:
`1...5...10`

but, PaginatorHelper::numbers() outputs all numbers.
 Setting `0` to option `modulus`, this method doesn't work well.

**Comment by markstory** [comment]
Why wouldn't you just output the first and last links? I don't see how a modulus of 0 would ever work.

**Comment by dereuromark** [comment]
@markstory I suspect it works with prev and next links. At least it did in my tests.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
