### ISSUE TITLE
3.0 CounterCacheBehavior and belongsToMany

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#7144]
`CounterCacheBehavior` seems to be working only with `belongsTo` associations. Which isn't a surprise as old 2.x `counter_cache` option also worked only with that type of association AFAIR.

I think that it could be worth trying to implement that behavior also for `belongsToMany`. I'm aware that there's a workaround using this behavior on belongsTo in a custom `through` table. The downside of this method is that it works only when an operation on a joint table is involved. So it cannot detect soft deletes etc.

There's currently no mention of either of these in the docs. We could try to implement this behavior for other types of association or update the docs with an example how to cache counters of BTM associations.

**Comment by markstory** [comment]
So are you suggesting we add docs, or improve the code?

**Comment by robertpustulka** [comment]
Maybe update the docs for now and try to upgrade the behavior for 3.1? 
I could try to do this but right now I don't have time for it :(

**Comment by markstory** [comment]
I'm fine with updating the docs for now.

**Comment by markstory** [comment]
Docs have been updated now - closing.
