### ISSUE TITLE
3.0 Paginator count() throws SQL error

### ISSUE THREAD

**Issue by jc-vogel** [cakephp/cakephp#7148]
After using the 'matching' method in a subquery the paginator component throws an error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
This happens when the paginatorcomponent tries to count the total results. 
- Subscription belongsToMany Statuses
- Subscription belongsTo Routes
- Routes belongsTo RouteDepartures && RouteDestionations

In controller: 
```
        $filter = array_filter([
            'route_departure_id' => $this->request->query('route_departure_id'),
            'route_destination_id' => $this->request->query('route_destination_id')
        ]);

        $this->paginate = [
            'finder' => [
                'report' => ['filter' => $filter]
            ]
        ];

        $report = $this->paginate();
```
Custom finder (in RoutesTable):
```
    public function findReport($query, array $options = [])
    {
        $subscriptions = $this->Subscriptions->find();
        $subscriptions
            ->select([
                $subscriptions->func()->count('Subscriptions.id')
            ])
            ->where(['route_id = Routes.id'])
            ->matching('Statuses', function ($q) {
                return $q->where(['Statuses.code' => 302]);
            });

        return $query
            ->select([
                'RouteDepartures.name',
                'RouteDestinations.name',
                'subscriptions' => $subscriptions
            ])
            ->contain([
                'RouteDepartures',
                'RouteDestinations'
            ])
            ->where($options['filter']);
    }
```

As long as I don't use the filter, the paginator works like it should. But as soon as I use the where condition it falls flat on its face. 
Is there a problem in my custom finder?
It seems to me that the number of parameters is not reset before calling count() in paginator component. The query that throws the error has the original two parameters from the custom finder, but uses only one (and thus trhows an error):
```
SELECT (COUNT(*)) AS `count` FROM routes Routes INNER JOIN route_departures RouteDepartures ON RouteDepartures.id = (Routes.route_departure_id) INNER JOIN route_destinations RouteDestinations ON RouteDestinations.id = (Routes.route_destination_id) WHERE (route_destination_id = :c0 AND Routes.deleted IS NULL)
```

I'll try to create a failing test, but I'm not yet sure if the problem is mine or in Cakephp...

**Comment by lorenzo** [comment]
Seems like a bug in `count()`. It should detect that the finder is complex enough to choose another counting strategy.

**Comment by markstory** [comment]
matching() doesn't feed into the 'complex' check in Query::count(). Only group/distinct/union do. Perhaps the presence of matching clauses should too.

**Comment by lorenzo** [comment]
The actual problem is the sub query in select.

**Comment by choma** [comment]
When was this issue introduced?
3.0.1 works ok for me.
3.0.11 has the issue

**Comment by markstory** [comment]
@choma Is your issue also caused by queries that use matching()?

**Comment by choma** [comment]
Nope. My issue happen when trying to use contain() and where() on the same query. They both work separately

**Comment by markstory** [comment]
@choma Ok, what does your query look like?

**Comment by markstory** [comment]
I wasn't able to reproduce this issue by using a subselect or matching(). Neither yielded the error described here. I built the following test case:

```php
        $table = TableRegistry::get('Articles');
        $table->belongsTo('Authors');
        $table->hasMany('ArticlesTags');

        $counter = $table->ArticlesTags->find();
        $counter->select([
                'total' => $counter->func()->count('*')
            ])
            ->where(['ArticlesTags.tag_id' => 1])
            ->where(['ArticlesTags.article_id = Articles.id']);

        $result = $table->find('all')
            ->select([
                'Articles.title',
                'tag_count' => $counter
            ])
            ->matching('Authors', function ($q) {
                return $q->where(['Authors.id' => 1]);
            })
            ->count();
        $this->assertSame(2, $result);
```

**Comment by choma** [comment]
@markstory, sorry for my late answer.
I did some tests, and now I'm not sure if my issue is related to this one. It seems to be more related to the stupid way I'm using a calculated fields. Here is my code:

    public function index()
    {
        $query = $this->Members->find()
               ->contain(['Clubs'])
               ->where(['club_id' => 1]);
        $this->paginate['fields'] = $this->Members->schema()->columns();
        $this->paginate['fields']['name'] = $query->func()->concat([
            'first_name' => 'literal',
            ' ',
            'middle_name' => 'literal'
        ]);

        $this->set('members', $this->paginate($query));
        $this->set('_serialize', ['members']);
    }

The error message I get is the same as jc-vogel one. But, if I remove where() OR calculated field, then it works.

**Comment by markstory** [comment]
Are you able to reproduce your issue outside of pagination? Perhaps with a query that you call `$query->count()` on? I have a fix up for #7272, but I wasn't able to reproduce the issue described here.

**Comment by choma** [comment]
Nope!, there is not issue if I do it like this:
```php
        $query = $this->Members->find()
               ->contain(['Clubs'])
               ->where(['club_id' => 1]);
        $query->select($this->Members->schema()->columns());
        $query->select(['name' =>
                        $query->func()->concat([
                            'first_name' => 'literal',
                            ' ',
                            'middle_name' => 'literal'
                        ])
        ]);
        $count = $query->count();
        $all = $query->all();
```

**Comment by markstory** [comment]
@choma Ok, that looks very similar to the issue that is going to be resolved in #7283

**Comment by choma** [comment]
great! and I'm sorry about the confusion

**Comment by markstory** [comment]
@jc-vogel Could you see if the changes in #7283 resolve the issue you were having?

**Comment by jc-vogel** [comment]
@markstory Yes, problem seems to be gone. Thanks!
