### ISSUE TITLE
3.X ORM, distinct() should behave like select() and allow a single string

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7150]
```php
        $query = $this->Geodata->find()
            ->select('iso_3166_1_alpha_2_country_code')
            ->distinct('iso_3166_1_alpha_2_country_code');
```
... does not work cause distinct expected an array. Encapsulating both field strings in an array of 1 element works. Select allows a single string, but distinct not. Is there a reason for this?

**Comment by antograssiot** [comment]
closing as a PR is open now

**Comment by ionas** [comment]
Thanks!
