### ISSUE TITLE
Tree behaviour recover

### ISSUE THREAD

**Issue by rahulgupta1** [cakephp/cakephp#7151]
Hi,
In tree behaviour there are 3 possibilities to run recover function

$this->Model->recover();
$this->Model->recover('parent');
$this->Model->recover('tree');

By mistake i passed 13456 inside function and it gets executed and it corrupted all the table.
$this->Model->recover('13456');
Please explain about this? and why it did not shown error.

**Comment by lorenzo** [comment]
Because we trusted developers to only pass the specified options. You can recover your table by calling `recover()` again
