### ISSUE TITLE
Single test failure on master

### ISSUE THREAD

**Issue by JeroenDeDauw** [cakephp/cakephp#7155]
Steps taken:

* git clone https://github.com/cakephp/cakephp.git
* cd cakephp
* composer install
* phpunit

Error output:

```
Time: 1.14 minutes, Memory: 187.75Mb

There was 1 failure:

1) Cake\Test\TestCase\I18n\TimeTest::testTimeAgoInWordsNegativeValues
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2 years, 5 months, 2 days ago'
+'2 years, 4 months, 4 weeks, 2 days ago'
```

PHP 5.6.9-1+deb.sury.org~trusty+2 (cli) (built: May 24 2015 15:46:23)
PHPUnit 4.7.3

After encountering the error I looked at the instructions in the readme, copied `phpunit.xml.dist` to `phpunit.xml` and re-ran the tests. Same result.

**Comment by markstory** [comment]
Yes, I think this is related to the time of year it is and strtotime() shenanigans. As without any code changes this test has started to fail.

**Comment by markstory** [comment]
Tests are passing now :+1:
