### ISSUE TITLE
3.x - Authentication - Validate and notify about invalid hashes?

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#7161]
Seeing that regulary questions pop up on SO regarding login problems, and that in many cases the problem is that the hash wasn't stored correctly (column length too short, password not being hashed at all, etc), I was wondering whether it might be helpful to check the hash for validity before trying to compare it, and spit out a warning that makes developers aware in case there's something wrong with the hash?

I guess it's debatable how helpful this would generally be, whether it's a good idea to expose such information that make it possible to draw conlusions about the stored data (even though these information wouldn't be visible when not in debug mode), and whether the core should care that much about user errors at all...

**Comment by markstory** [comment]
If only MySQL would fail queries when data is truncated.

**Comment by Marlinc** [comment]
@markstory how about changing the SQL mode on runtime? https://dev.mysql.com/doc/refman/5.1/en/sql-mode.html

**Comment by markstory** [comment]
I don't think changing the SQL mode in the ORM is a good idea, it might not be surprising to developers and dba's.

**Comment by ravage84** [comment]
May be a small note/hint in the docs at the right place(s) could help those lost souls? :smiling_imp: 

Or something like this https://github.com/cakephp/docs/pull/3067/files ?

**Comment by markstory** [comment]
A note in the docs sounds reasonable @ravage84.

**Comment by jhli** [comment]
I think it is okay to change the mode or put an out commented in the datasource config. Question is if the mode can easily be changed with little previleges?

**Comment by markstory** [comment]
@jhli My issue is that changing SQL modes varies greatly between each dbms. Is this really a common enough problem where we need platform abstraction and code to support what is generally a self-inflicted issue?

**Comment by sdustinh** [comment]
I've always wondered why bake wasn't extended for common database fields. This is probably a good example. Something like:

```bash
bin/cake bake db_column --type password --connection default --table users column_name
```

... but then I just made a migration.

**Comment by dereuromark** [comment]
With moving this to docs we can probably close this.
