### ISSUE TITLE
[Enhancement] Add a 'select' key to the AuthComponent config

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#7162]
I'm using the **AuthComponent** and i want to specify the **Users Table fields**. 
By default the **BaseAuthenticate::_query($username)** select all the fields from the Users Table:
```php
$query = $table->find('all')
            ->where($conditions);
```
We can't specify the fields to select in the AuthComponent config like this:
```php
$this->loadComponent('Auth', [
	// ...
    'authenticate' => [
        'Form' => [
             // eg. add the 'select' key to the config
            'select' => ['id', 'email', 'fullname', 'phone', 'fax', 'lastlogin', 'ip', 'role_id'],
            'fields' => ['username' => 'email', 'password' => 'password'],
            'scope' => ['Users.state' => 1, 'Users.deleted' => 0],
            'contain' => ['Roles' => ['fields' => ['id', 'name']]]
        ],
    ]
]);
```
So i override the **BaseAuthenticate::_query($username)** by creating a custom **MyFormAuthenticate::_query($username)** in the **src/Auth** folder like this:
```php
<?php

namespace App\Auth;

use Cake\Auth\FormAuthenticate;
use Cake\ORM\TableRegistry;

class MyFormAuthenticate extends FormAuthenticate
{

    /**
     * Get query object for fetching user from database.
     *
     * @param string $username The username/identifier.
     * @return \Cake\ORM\Query
     */
    protected function _query($username)
    {
        $config = $this->_config;
        $table = TableRegistry::get($this->_config['userModel']);

        $conditions = [$table->aliasField($config['fields']['username']) => $username];
        if ($config['scope']) {
            $conditions = array_merge($conditions, $config['scope']);
        }

        $query = $table->find('all')
            ->where($conditions);
        
        // I add this lines
        if($config['select']){
            $query = $query->select($config['select']);
        }

        if ($config['contain']) {
            $query = $query->contain($config['contain']);
        }

        return $query;
    }
}
```
I modified also the config of the AuthComponent like this:
```php
$this->loadComponent('Auth', [
	// ...
    'authenticate' => [
        // 'Form' to 'MyForm'
        'MyForm' => [
             // eg. add the 'select' key to the config
            'select' => ['id', 'email', 'fullname', 'phone', 'fax', 'lastlogin', 'ip', 'role_id'],
            'fields' => ['username' => 'email', 'password' => 'password'],
            'scope' => ['Users.state' => 1, 'Users.deleted' => 0],
            'contain' => ['Roles' => ['fields' => ['id', 'name']]]
        ],
    ]
]);
```
Now it works and i can specify the fields to select from the Users Table.

I think this config option must exist by default :)

**Comment by markstory** [comment]
> I think this config option must exist by default :)

Why?

**Comment by flashios09** [comment]
@markstory to prevent selecting all the fields in the users table. We can specify the **contain** option but we can't specify the fields to select from the users table ! 
What do you think ?

**Comment by josegonzalez** [comment]
@markstory I feel as though I mentioned this before, but perhaps a better option would be to allow a user to specify a custom finder. Would be simpler than adding new query options to the list and allows as much flexibility as the user needs in querying for data imo.

**Comment by ADmad** [comment]
@flashios09 Sounds like you are cramming too many fields into users table which should otherwise be moved into a separate profile table.

@josegonzalez Adding `finder` options is a very good idea.

**Comment by Marlinc** [comment]
I like adding a ```finder``` option as well. I don't think the component should be responsible for manipulating the query to such great of a detail.

**Comment by markstory** [comment]
:+1: to a finder.

**Comment by markstory** [comment]
Closing as a pull request is up, that will let you limit the fields that are loaded.

**Comment by flashios09** [comment]
@ADmad Even if i separate the users table into two tables(adding a profile table) i will need a **JOIN** to  select the profile table fields and store it in the Session when connecting a user. 
That's why i merge the two tables(users and profile) into one table and i prefer to specify the fields to select.
+1 for the **custom finder** suggested by @josegonzalez

**Comment by ADmad** [comment]
@flashios09 Your statement sound pretty contradictory to me. On one hand you want to be able to select only some fields (which will be stored in session) and on other hand you say you would still have to join the profile table to store all profile fields too in session.

But never mind, I don't want to get into that discussion. I have already opened a pull request to help you achieve what you need :)

**Comment by flashios09** [comment]
@ADmad  There is a **misunderstanding**,  i don't want to have **two tables** (users and profile) that's why i want to **specify the fields to select from the users table**. If i have two tables i can just **add the profile table to the contain config** option like this:
```php
'Form' => [
    'fields' => ['username' => 'email', 'password' => 'password']
    'contain' => [
    	'Profile' => ['fields' => ['phone', 'fax', 'ip', 'lastlogin', 'other_fields']]
	]
]
```
I prefer merging the users and the profile tables into one table, you like to separate them into two tables :)
 
Thanks for the pull request
