### ISSUE TITLE
Create intermediary 'ControllerEvent'

### ISSUE THREAD

**Issue by Marlinc** [cakephp/cakephp#7166]
I think it would be useful to create a intermediary `ControllerEvent` that would be used in Components instead of the regular `Event`. This would allow easy autocompletion of the return value of the `subject` method.

**Comment by lorenzo** [comment]
This sounds like a good idea to me

**Comment by Marlinc** [comment]
The same could possibly be applied to table events as well? Although I'm not sure if it would make as much sense in that case.

**Comment by markstory** [comment]
Couldn't the same be done for the View events too?

**Comment by jhli** [comment]
:+1: for consistency across MVC.

**Comment by Marlinc** [comment]
Is there any other use case were this could be useful?

**Comment by Marlinc** [comment]
I've opened a pull request for this #7173

**Comment by ADmad** [comment]
Closing as PR is open.

**Comment by josegonzalez** [comment]
Was this ever implemented? If not, it should be re-opened...

**Comment by dereuromark** [comment]
Any interest in finishing this for 4.0?

ping @Marlinc   etc
