### ISSUE TITLE
Is there any reason why the Marshaller can't work with entity objects?

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#7169]
I'm trying to "copy" an associated record to another, I have to use $entity->toArray() because the marshaller won't take the entity object which implements array interface.

Doing this 

```php
$entity = $accounts->newEntity($lead, ['associated' => ['Addresses']]);
```

will result in:

> Argument 1 passed to Cake\ORM\Marshaller::one() must be of the type array, object given.

while this will work

```php
$entity = $accounts->newEntity($lead->toArray(), ['associated' => ['Addresses']]);
```

So why not changing the marshaller to work with entity objects as well? Entity implements the array interface and can be treated as array. One minor stumbling block less to care about.

**Comment by lorenzo** [comment]
Because it is meant to convert entity data into entities, not entities to entities.

**Comment by lorenzo** [comment]
On changing the method internals: I wouldn't personally like repurposing the method for anything else that is not just plain request data conversion. The method is not a cloning tool

**Comment by burzum** [comment]
The data is not coming from a request. The user wants to turn a Leads record / entity into an account, contact or both. If the validation for the account/contact + associated data doesn't fail the Leads record is deleted. The lead is looked up by id, there is not even a POST involved.

If you have a better idea how to do that I'm open for suggestions. However, the need to call toArray() here just feels awkward.

**Comment by lorenzo** [comment]
I understand you have a specific use case for your app that can be solved wither by calling `newEntity()` or `$entity->set()`, but I don't think your specific case means that the framework should support it by default.

If this were to be added, the only option that would guarantee that everything will be working as usual is to internally convert the entity to an array.
