### ISSUE TITLE
3.x: Baked models does not contain validation for required FK's

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#7174]
Having Users and Comments table, with a User hasMany Comments relationship:

If the `user_id` on a in the `comments`-table is required, I'd expect it to also include following when baking the model:

`
$validator
  ->add('user_id', ['rule' => 'uuid'])
  ->notEmpty('user_id');
`

Is that just me being wrong?

**Comment by davidyell** [comment]
I'd think this would be a domain rule for the `RulesChecker`.

Something like this,
```php
// src/Model/Table/CommentsTable
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        return $rules;
    }
```

**Comment by markstory** [comment]
From what I remember bake adds domain rules for each foreign key field. Using a validator is tricky, as foreign keys are not always populated from request data, which would cause validation to fail.

**Comment by Spriz** [comment]
It does indeed add domain rules, I just think it's weird it doesn't add the validator on the "not null"-fields from mysql - and I'm pretty sure it did at some point.

Even though it's not populated from request data, it should still be filled in the entity between the request data and the conversion to an entity - but I guess that would be up to the programmer to do in the controller? At least we do that with some fields.. If the FK's are not selected by the user of some kind, we do it in the controller actions.

**Comment by chinpei215** [comment]
@markstory @Spriz It seems an implementation bug for me. The concept would be correct.

When <code>Articles belongsTo Categories</code>, bake generates an application rule for FK in <code>ArticlesTable</code>:

```php
$rules->add($rules->existsIn(['category_id'], 'Categories'));
```
Look at the arguments carefully. <code>['category_id']</code> and <code>'Categories'</code>. They would be passed to the ExistsIn class.

```php
public function __construct($fields, $repository)
{
    $this->_fields = (array)$fields;
    $this->_repository = $repository;
}
```
(Source: https://github.com/cakephp/cakephp/blob/master/src/ORM/Rule/ExistsIn.php#L48-L52)

And the 'category_id' field would be checked whether nullable or not.
```php
$schema = $this->_repository->schema();
foreach ($this->_fields as $field) {
    if ($schema->isNullable($field) && $entity->get($field) === null) {
        $nulls++;
    }
}
if ($nulls === count($this->_fields)) {
    return true;
}

```
(Source: https://github.com/cakephp/cakephp/blob/master/src/ORM/Rule/ExistsIn.php#L82-L90)

But <code>$schema</code> is <code>'Categories'</code>.
There's no way <code>'Categories'</code> has <code>'category_id'</code>. Thus, this check  would return true always.
I think <code>$schema</code> should be 'Articles'.

What do you think?

**Comment by Spriz** [comment]
I think you misunderstood what Schema::isNullable() is doing - check out: http://api.cakephp.org/3.0/class-Cake.Database.Schema.Table.html#_isNullable :smile:

**Comment by chinpei215** [comment]
@Spriz I thought L82-90 were written for nullable foreign keys. I mean a table like this:

```sql
CREATE TABLE articles(
  ...
  category_id int unsigned NULL,  -- Nullable
  ...
  FOREGIN KEY (category_id) REFERNCES categories(id)
)
```

Then, it seems reasonable to me that checking whether or not Articles.category_id is nullable. However, it seems not reasonable checking Categories.category_id.

But I might misunderstand as you said :)
Thanks and I'm sorry for my broken English.

**Comment by markstory** [comment]
> It does indeed add domain rules, I just think it's weird it doesn't add the validator on the "not null"-fields from mysql - and I'm pretty sure it did at some point.

Yes it did, but a number of people had issues saving associations as validation would always fail if you saved an article and its comments for example.

**Comment by lorenzo** [comment]
You are right,  the nullable checking part seems to be wrong

**Comment by dereuromark** [comment]
PR: https://github.com/cakephp/cakephp/pull/7183
