### ISSUE TITLE
2.x Unable to use persistent connections in beforeSave callbacks

### ISSUE THREAD

**Issue by SanderSander** [cakephp/cakephp#7178]
The beforeSave callback is called in the middle of the saving operation so when the transaction allready has begun, instead BEFORE the transaction begins. 

I had some issues with some transactions in the beforeSave, and with the session_write_close method  (only when sessions are stored in the database). The session_write_close method is also called when an exception is thrown in the beforeSave method. 

The exception:
PDOException: There is already an active transaction in /vagrant/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 2294

https://github.com/cakephp/cakephp/blob/2.6.10/lib/Cake/Model/Model.php#L1748

                $db = $this->getDataSource();
		$transactionBegun = $db->begin();
                try {
			$success = $this->_doSave($data, $options);

In the _doSave the callbacks are triggered.

I would aspect that the beforeSave callback is triggered prior to the $db->begin() transaction.  

This is at least the case for version 2.6.* and 2.7.*

**Comment by markstory** [comment]
I would expect that all the before events happen in the same transaction. This is important with higer levels of transaction isolation as you want to have a consistent snapshot of the data base for the whole 'operation' which in this case is `save()`.

Closing as won't fix as I don't think having separate transactions is a good idea and will likely lead to more problems than it solves.
