### ISSUE TITLE
View variables not available when not explicitly calling getView

### ISSUE THREAD

**Issue by Marlinc** [cakephp/cakephp#7180]
View variables are not being set in the ```View``` class unless ```getView()``` is explicitly called before the rendering of the template starts.

This is happening in CakePHP 3.1 beta 1 and is possibly due to the setting of view variables being moved into https://github.com/cakephp/cakephp/blob/3.1/src/View/ViewVarsTrait.php#L61-L85

**Comment by ADmad** [comment]
Well the view vars are copied from controller to view class on each call of getView(). Please provide example code to reproduce the issue.

**Comment by Marlinc** [comment]
I found out what the problem is. It has to do with the ```beforeRender``` in the ```Controller``` class. Croogo plugins set view variables when the ```beforeRender``` event gets called. The new version of CakePHP however only calls ```getView()``` before the event gets dispatched.

This can be seen in: https://github.com/cakephp/cakephp/blob/3.1/src/Controller/Controller.php#L555-L565

**Comment by markstory** [comment]
Setting view variables in the beforeRender callback seems quite reasonable. Perhaps Controller::render() can re-fetch the view after that event?

**Comment by Marlinc** [comment]
That's what I thought as well. Re-fetching could definitely be an acceptable solution.

**Comment by ADmad** [comment]
Sounds good to me too. @Marlinc Would you like to make a PR?

**Comment by Marlinc** [comment]
Sure, will do

**Comment by Marlinc** [comment]
A pull request has been opened: #7195
