### ISSUE TITLE
CakePHP 3 -  Plugin with admin prefix association error

### ISSUE THREAD

**Issue by cercos** [cakephp/cakephp#7181]
It seems that the table associations when inside plugin with prefix routing are not being associated properly.  It throws an error that my current table is not associated with the table in the contain clause.  It works when outside of the prefix route

**Comment by ADmad** [comment]
Table associations unrelated to routing. Please provide example code or test case to reproduce the issue you are having.

**Comment by markstory** [comment]
Closing - no followup.
