### ISSUE TITLE
Inflector::slug is not returning the formatted string

### ISSUE THREAD

**Issue by ashwanisinghh** [cakephp/cakephp#7182]
I am using Inflector::slug to convert the string into slug.
but it just returns some short form slug.
 e.g-\
       Inflector::slug('Test Category','-');
returns 't-t-o';

can anyone help on this

**Comment by dereuromark** [comment]
You should always mention the exact CakePHP version you are using.
Are you sure you didnt change the inflection rules of the Inflector somewhat? Never seen that issue before with such "normal" ascii strings.

**Comment by ashwanisinghh** [comment]
no i havn't changed anything in Inflector and my version is 2.6

**Comment by ashwanisinghh** [comment]
public static function slug($string, $replacement = '_') {
		$quotedReplacement = preg_quote($replacement, '/');

		$merge = array(
			'/[^\s\p{Zs}\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}]/mu' => ' ',
			'/[\s\p{Zs}]+/mu' => $replacement,
			sprintf('/^[%s]+|[%s]+$/', $quotedReplacement, $quotedReplacement) => '',
		);

		$map = self::$_transliteration + $merge;
		return preg_replace(array_keys($map), array_values($map), $string);
	}
this is my Inflectors slug method

**Comment by markstory** [comment]
What version is your PCRE library? This reminds me of the problems people had with old versions of PCRE.

**Comment by markstory** [comment]
Closing - No follow up.
