### ISSUE TITLE
bug:DBOSource isConnected method doesn't check the real status of connection

### ISSUE THREAD

**Issue by pbaire** [cakephp/cakephp#7185]
In 2.x version the isConnected method doesn't check the real status of connection but returns an instance value setted when the connection is created.
I maked a simple workaround to effectively check the presence of connection by executing a "dumb" query (SELECT 1) 
pull request @ https://github.com/cakephp/cakephp/pull/7184

**Comment by markstory** [comment]
Closing as there is a pull request open now.
