### ISSUE TITLE
3.x - ORM - func->case return a string to func->sum()

### ISSUE THREAD

**Issue by Tresmollo** [cakephp/cakephp#7186]
When using a case expression inside a sum expression, the case return the result as a string

```php
$billableTime = $query->newExpr()->addCase($query->newExpr()->add(['billable' => 1]), ['Jobs.duration'], 'time');
$nonBillableTime = $query->newExpr()->addCase($query->newExpr()->add(['billable' => 0]), ['Jobs.duration'], 'time');
```
```php
$query->select([
    'billable_time' => $query->func()->sum($billableTime),
    'non_billable_time' => $query->func()->sum($nonBillableTime),
    'total_time' => $query->func()->sum('Jobs.duration'),
])
```
the generated SQL request is :
```sql
SELECT (SUM((CASE WHEN billable = 1 THEN 'Jobs.duration' END))) AS `billable_time`, (SUM((CASE WHEN billable = 0 THEN 'Jobs.duration' END))) AS `non_billable_time`, (SUM(Jobs.duration)) AS `total_time` FROM jobs Jobs 
```
Due to the 'quotes' around the `SUM` for the `billable_time` and `non_billable_time` doesn't work and output `0`

when manualy sending this request (without the single quotes around `Jobs.duration` :
```sql
SELECT (SUM((CASE WHEN billable = 1 THEN Jobs.duration END))) AS `billable_time`, (SUM((CASE WHEN billable = 0 THEN Jobs.duration END))) AS `non_billable_time`, (SUM(Jobs.duration)) AS `total_time` FROM jobs Jobs 
```
MySQL return the correct values

**Comment by lorenzo** [comment]
You need to use `['column_name' => 'literal']` if you want the ORM to not safely escape the values you pass to it. Another option is using an expression object instead.

**Comment by Tresmollo** [comment]
Thanks for the tips, I've  tried with `['column_name' => 'literal']` but it doesn't work either, the query outputed is
```sql
SELECT (SUM((CASE WHEN billable = 1 THEN '00:00:01' END))) AS `billable_time`, (SUM((CASE WHEN billable = 0 THEN '00:00:01' END))) AS `non_billable_time`, (SUM(duration)) AS `total_time` FROM jobs Jobs 
```
I guess I will try my luck with the expression object

**Comment by lorenzo** [comment]
I would personally use a QueryExpression, specifically a `IdentifierExpression` for that case. I will check if the CaseExpression supports literals.

**Comment by lorenzo** [comment]
I see there is support for literals: https://github.com/cakephp/cakephp/blob/master/src/Database/Expression/CaseExpression.php#L128

I guess it should be used like this:

```php
 $query->newExpr()->addCase(
    $query->newExpr()->add(['billable' => 1]),
   [ ['Jobs.duration' => 'literal'] ], // Notice That the value is an array (Have not tried this in real life :P)
   'time'
);
```

**Comment by Tresmollo** [comment]
Well, adding the englobing array did something, now I've got a fatal error xD
```
Error: Call to a member function format() on a non-object 
File /vendor/cakephp/cakephp/src/Database/Type/DateTimeType.php 
Line: 94
```

**Comment by lorenzo** [comment]
Ok, so I don't know... just wrap your identifier in an IndentifierExpression. I will look into what is the actual syntax for literals in the CaseExpression and document it

**Comment by Tresmollo** [comment]
The `IdentifierExpression` did the trick !
```php
$query->newExpr()->addCase(
	$query->newExpr()->add(['billable' => 1]),
	[new IdentifierExpression('Jobs.duration')],
	'time'
);
```
Thanks a lot for the help !
