### ISSUE TITLE
source() method on aliased plugin Entity

### ISSUE THREAD

**Issue by arilia** [cakephp/cakephp#7187]
about this question I opened in stackoverflow

http://stackoverflow.com/questions/31848771/cakephp-3-0-get-table-object-from-aliased-plugin-entity

what I did

    //plugins/Users/src/Model/Table/GroupsTable.php

    $this->belongsTo('Parents', [
        'className' => 'Users.Groups',
        'foreignKey' => 'parent_id'
    ]);

---
    // Some controller

    $groupsTable = TableRegistry::get('Users.Groups');
    $group = $groupsTable->get($some_id, ['contain' => 'Parents']);
    $className =  $group->parent->source();

what I expected

`$className` contains `Users.Parents`

what I get

`$className` contains `Parents` without the reference to the plugin name

**Comment by markstory** [comment]
But the source() method returns the 'alias' of the association/class, not the class name. Is this causing you problems?

**Comment by arilia** [comment]
I have an entity, and I need to instantiate its table.

If I use `TableRegistry::get();` with the alias I don't get the right table if the entity comes from a plugin. How can I get the entity table? Is there another way than unig `source()`?

**Comment by markstory** [comment]
Pull request up now #7188
