### ISSUE TITLE
2.X Response->Vary() should be cumulative

### ISSUE THREAD

**Issue by quantum-x** [cakephp/cakephp#7192]
Problem: Response->vary() is not cumulative. IE, if called multiple times, the previously set value is discarded instead of being placed into an array.

Suggestion: Response->vary() should exhibit consistant behaviour as Response->header()

**Comment by quantum-x** [comment]
If deemed important, please let me know, and I will send in my PR

**Comment by markstory** [comment]
If each call adds, how would someone replace the set values? Currently you can 'add' with

```php
$response->vary('Cookie');
$response->vary(array_merge(['Accept-Language'], $response->vary());
```

**Comment by quantum-x** [comment]
Hi @markstory 
Presumably by doing manually unsetting the particular array value.
In reality, it would mirror the behaviour of $response->header():

```
// Set a single header
$this->response->header('Location', 'http://example.com');

// Set multiple headers
$this->response->header(array(
    'Location' => 'http://example.com',
    'X-Extra' => 'My header'
));

$this->response->header(array(
    'WWW-Authenticate: Negotiate',
    'Content-type: application/pdf'
));

http://book.cakephp.org/2.0/en/controllers/request-response.html#setting-headers
```

Again, I'm not sure if this is important, but I would expect that a header that could take multiple options would behave in a similar manner to its sibling methods - I got caught out with this.

Thanks kindly.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
