### ISSUE TITLE
3.x - Unable to set reusable formatter with custom pattern

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#7193]
## The what

I wanted to set a non-default number format for a particular currency so I did:

```php
Number::formatter([
    'type' => 'currency',
    'locale' => 'en_IN',
    'pattern' => '¤ #,##,##0'
]);
```
`Number` class stores and reuses the formatter for each locale and type pair so I expected the new pattern to be uses when using 

```php
$number->currency(15000, 'INR', ['locale' => 'en_IN']);
```
But the returned string still used the default pattern for `INR`.

## The why

The reason for this is, though formatter instance for locale and type pair are cached in `Number::$_formatters`, the patter and other attributes are set after [cloning](https://github.com/cakephp/cakephp/blob/master/src/I18n/Number.php#L289) the formatter object, hence they don't persist and are not used in call.

## The solution

So to resolve the issue either the code should be refactored  to not clone the formatter the 1st time it's created for a locale, type pair or add a extra option which prevents the cloning.

Perhaps the class should also have methods to explicitly set / clear formatters in `Number::$_formatters`.

**Comment by markstory** [comment]
The proposed solution sounds good to me. One thing that doesn't make sense to me is why the pattern is overwritten. In your example, your options don't define `options['format']` so I would have expected the formatter to remain unchanged.

**Comment by lorenzo** [comment]
I don't really understand this issue... What `$number` in your case?
