### ISSUE TITLE
Add ViewConfig proxy

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#7201]
As discussed in #7195. The deprecation of the controller properties is nice, as it makes the contracts between controllers and views explicit and based on methods not properties. However, the current getView() based code is problematic as view instances are cemented a bit too early often. To keep the separation that we've gained and fix the usability issues that have been introduced a view configuration data object could be introduced. This object would:

* Store view configuration before a view was created.
* Absorb methods related to defining the theme/layout/viewPath etc.
* Would be used by Controller, and injected into the View.

```
// Example controller code
$this->viewConfig()->layout('admin'); 
$this->viewConfig()->theme('shop');
```

View code could also benefit from this class as we could deprecate the properties there, and formalize the contract between Controller & View to be the ViewConfig object.

The new class could be `Cake\View\ViewConfig` and method to get proxy instance could be `Cake\View\ViewVarsTrait::viewConfig()`.

**Comment by lorenzo** [comment]
I like this :+1:

**Comment by markstory** [comment]
Cool, I'll try implementing in the next few days.

**Comment by Marlinc** [comment]
Looking good indeed.

Could the same be applied to email sending as well possibly? At the moment
there's a special method for assigning a template.

**Comment by markstory** [comment]
Closing as #7223 is open now.
