### ISSUE TITLE
Problem with plural and i18n translate function

### ISSUE THREAD

**Issue by shingosama** [cakephp/cakephp#7203]
Hello, I have a problem concerning translation and plurality. All functions that I try to use, but they go back only singular. I did several tests trying to see what was going on in the source code of cakephp, but I did not find anything wrong.

````php
<?php
echo $feed->status->created->timeAgoInWords();
// display 13 hour, 55 minute ago
?>
````

````php
<?php
echo __dn('cake', '{0} car', '{0} cars', 2, 2);
// display 2 car
?>
````

```php
<?php
function __dn($domain, $singular, $plural, $count, $args = null)
    {
        if (!$singular) {
            return;
        }

        $arguments = func_num_args() === 5 ? (array)$args : array_slice(func_get_args(), 4);
        return I18n::translator($domain)->translate(
            $plural,
            ['_count' => $count, '_singular' => $singular] + $arguments
        );
    }
````

Am I the only one to experience this issue?

Thank you for your help.

**Comment by markstory** [comment]
What do your translation files look like? There are quite a few tests that cover the plural forms that work. Also plurals are working fine locally:

```php
>>> $t = new Cake\I18n\Time('2015-08-07 23:10:10');
=> Cake\I18n\Time {#222
     +"time": "2015-08-07T23:10:10+0000",
     +"timezone": "UTC",
     +"fixedNowTime": false,
   }
>>> $t->timeAgoInWords();
=> "16 hours, 37 minutes ago"
```

**Comment by shingosama** [comment]
Thanks for your answer. The problem was with my setup. I set "fr-FR" inftead of fr_FR in my bootstrap.php file:

````
I18n::locale('fr_FR');
````

and have generated new translation files. The plural now works.
