### ISSUE TITLE
3.x - AuthComponent - _unathorized() - Redirect problem when user has no access to referer()

### ISSUE THREAD

**Issue by JustDoItSascha** [cakephp/cakephp#7205]
I'm struggling with a problem in cake 3 and I don't know if it's my fault or a bug. When I have two users with different authorization configs  and User A logs out and User B logs in right after, but has no access to the referer location, the redirect is not correct.

Because the redirecting method tries to access the location from loginRedirect, but the url which is generated is not correct, because my app lies in a subfolder and the name of the subfolder is used two times, like localhost/appdir/appdir/controller/action/home.

**Comment by markstory** [comment]
What does your auth component configurarion look like?

**Comment by JustDoItSascha** [comment]
```
$this->loadComponent('Auth', [
            'loginRedirect' => [
                'controller' => 'pages',
                'action' => 'display',
                'plugin' => false,
                'home'
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'login',
                'plugin' => 'UserManagement'
            ],
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login',
                'plugin' => 'UserManagement'
            ],
            'flash' => [
                'element' => 'error',
                'key' => 'auth'
            ],
            'authenticate' => [
                AuthComponent::ALL => [
                    'contain' => 'Groups',
                    'userModel' => 'UserManagement.Users'
                ],
                'Form'
            ],
            'authorize' => [
                'UserManagement.Action'
            ]
        ]);
```

In the _unauthorized Method you call referer() with default route and second parameter true. This returns /subdir/ROUTE/TO/REFERER and then the redirect() or better the Router::url() prepends this string with the actual subdir.

Either the referer() method should return the url without the basedir or the Router::url() has to be detained from prepending the basedir a second time.

**Comment by markstory** [comment]
Thanks, I'll try reproducing and seeing if the change you made has any other side-effects.

**Comment by JustDoItSascha** [comment]
You're welcome. If you need some other Information, just ask. I think the logical error behind the issue is, that the url goes through router::url() two times in this special case...

**Comment by HavokInspiration** [comment]
@markstory Might be the same issue as here https://github.com/cakephp/cakephp/issues/5878

**Comment by markstory** [comment]
@HavokInspiration Agreed, but this time in 3.x

**Comment by steji113** [comment]
Is this the same issue as #4812 ? I have been able to reproduce the same issue even with the fix for #4812 present.

**Comment by markstory** [comment]
@steji113 That issue was for string URLs. This sounds related but not the same. I've not had a chance to take a look at this one yet though.

Are you also able to reproduce with similar settings as @JustDoItSascha used?

**Comment by steji113** [comment]
At first glance it seems our configurations are pretty similar. On any unauthorized redirect, if you are running out of a subdirectory on your web server we will start to see URLs with the subdirectory duplicated.

```
$this->loadComponent('Auth', [
			'authenticate' => [
				'Yalp.Ldap' => null
			],
            'authorize' => [
                'Acl.Actions' => ['actionPath' => 'controllers/']
            ],
			'loginAction' => [
				'plugin' => false,
				'controller' => 'Users',
				'action' => 'login'
			],
			'loginRedirect' => [
				'plugin' => false,
				'controller' => 'Cameras',
				'action' => 'index'
			],
			'logoutRedirect' => [
				'plugin' => false,
				'controller' => 'Users',
				'action' => 'login'
			],
			'authError' => 'You are not authorized to access that location.',
			'flash' => [
				'element' => 'error'
			]
		]);
```

**Comment by markstory** [comment]
Thanks for the help on this. #7239 is open now.
