### ISSUE TITLE
LocaleSelectorFilter shouldn't set default locale

### ISSUE THREAD

**Issue by pperejon** [cakephp/cakephp#7208]
Hello!
Recently I had some problems with the *Translate behavior* in a new app I'm developing using CakePHP 3.0. The prob was that translations queries were never executed because of this two reasons:
* [the comparison between the current locale and the default locale at the beginning of the *beforeFind*](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TranslateBehavior.php#L195-L199).  
* I loaded the *LocaleSelectorFilter* in my bootstrap, and this filter [sets the default locale to the one in the HTTP header](https://github.com/cakephp/cakephp/blob/master/src/Routing/Filter/LocaleSelectorFilter.php#L67).

So, in this case, current locale and default locale will never differ. If you don't call explicitly `I18n:locale('whatever')`, or `$model->local('whatever')` in your code, i18n tables will never be accessed.

My suggestion is to change [this line](https://github.com/cakephp/cakephp/blob/master/src/Routing/Filter/LocaleSelectorFilter.php#L67) to be `I18n:locale($locale)`. Actually, when you make a request with an accept language header, it shouldn't affect the default locale that (AFAIK) should be a static configuration parameter.

Thanks in advance and congrats for your good work!

**Comment by lorenzo** [comment]
Would you like sending us a pull request with your proposed fix?

**Comment by pperejon** [comment]
Sure! This is going to be my first collaboration to open source using git, github, unit tests, and so on. The pull request will be ready in a few minutes. Though is an ultra-simple change I hope I make no mistakes :)

**Comment by Marlinc** [comment]
@pperejon don't worry. Its easy to do and very rewarding :smile:

**Comment by ADmad** [comment]
Closing are related PR is open.
