### ISSUE TITLE
Hash::sort to support ignore case

### ISSUE THREAD

**Issue by aygee** [cakephp/cakephp#7211]
Hi,

I think Hash::sort should support ignore case. I'm proposing to take a new parameter $ignoreCase. If this is set to true, we can combine the $type flag with SORT_FLAG_CASE using the bitwise OR to make the sort case insensitive.

It's easy to implement and I can create a pull request.

**Comment by jippi** [comment]
boolean arguments are terrible for readability imo. Rather see an options array with 'ignoreCase' => true'

**Comment by markstory** [comment]
We could expand the $type option to allow new states as well. We don't already have an options parameter.

**Comment by aygee** [comment]
I agreed. Adding $options just for 'ignoreCase' is overkill. @markstory, do you reckon expand the $type to have regular_case, string_case, natural_case for the case insensitive options?

Also, can this be added to v2 as well please?

**Comment by markstory** [comment]
@aygee We can totally add this kind of thing into 2.8. Other than using names like `regularCase` etc. I think adding more type options seems like a good idea.

**Comment by aygee** [comment]
I created a pull request in #7217. I created an extra parameter instead of expanding the $type because the solution will be simpler, rather than having to check the $type for regular_ignore_case, string_ignore_case, natural_ignore_case, etc...

What do you think?

Sorry this is my first time contributing so please bear with me

**Comment by aygee** [comment]
Also, I noticed that AppVeyor build failed. What have I missed there?

**Comment by antograssiot** [comment]
@aygee don't worry, appveyor faillure is normal, it is not configured to work on 2.x branches.

**Comment by markstory** [comment]
Closing as there is a pull request open now that we can continue to discuss and work on.
