### ISSUE TITLE
RequestHandlerComponent should have a config for the automatic view types

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#7212]
Currently the `RequestHandlerComponent` responds automatically to json and xml depending on the Accept header, but there are cases were you do not want to support both formats, as it involves more testting and edge cases.

The RequestHandler should be able to get a configuration array with the possible automatic view types that should be inspected for.

**Comment by Marlinc** [comment]
Would it make sense to look at the extensions in the ```Router``` to determine what formats to support?

**Comment by lorenzo** [comment]
no much @Marlinc, extensions are only for lazy developers. The actual feature is header detection, but we could make sure that if the extension is supported then it would make sense to respond to that format as well.

**Comment by Marlinc** [comment]
That's what I thought, as it would generally be expected

**Comment by markstory** [comment]
What if there were no default types?

**Comment by lorenzo** [comment]
@markstory that could work as well, but I see it more difficult to implement because of BC

**Comment by markstory** [comment]
Good point a config option with a compatible default value makes sense then.

**Comment by markstory** [comment]
How do people feel about `RequestHandlerComponent::viewClassMap()` and `RequestHandlerComponent::addInputType()`? I feel like these methods could be deprecated and their options replaced with the generic `config()` method. We would have to do additional run-time validation when these config options are used, but customizing these mappings becomes more consistent and I think using `config()` lets people limit which types are automatically handled.

**Comment by lorenzo** [comment]
That could work nicely
