### ISSUE TITLE
3.x Apache environment variables aren't loaded for CLI scripts

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#7216]
The main discussion for this was over on cakephp/migrations#107.

Basically I have environment variables that are set in my apache config. When I use any of the CLI scripts they won't have access to those environment variable settings because apache is never used. I'm not sure there is anything that can be done about this on the framework side (at least easily) but I figured I would at least open an issue incase you guys wanted to document it on the book or somewhere.

**Comment by jadb** [comment]
My preferred method for env vars is to use https://github.com/josegonzalez/php-dotenv - makes it trivial to share them between CLI and web.

**Comment by markstory** [comment]
We can't make apache environment variables available in your terminal environment. You'll have to solve this one on your own :smile:

**Comment by jhli** [comment]
@jadb i can only hope to see this land in 3.2 or some 3.1.x?

**Comment by jhli** [comment]
Ref https://github.com/cakephp/cakephp/issues/4396
