### ISSUE TITLE
Deep associations returns null on ngnix

### ISSUE THREAD

**Issue by alexlambson** [cakephp/cakephp#7220]
Hello, 

We are on CakePHP 3.0.7

I am using Apache and my coworker is using ngnix. We found that deep associations using dot notation in ->contain() do not work on his ngnix server, but they work on my Apache server. I wish I had an error code to give, but it simply returns a null object when we execute the query. 

I can get any info you guys think will be helpful.

**Comment by markstory** [comment]
I suspect there are other differences than nginx/apache.  There isn't anything in the ORM that is using environment variables or server related features so the issue must be somewhere else.

**Comment by jadb** [comment]
Turn on your database logs maybe?

From my Vagrant machine (edit to fit your environments):

```
mysql -u root -p123 -e "SET global general_log = 1;" && sudo tail -f /var/lib/mysql/local.log /vagrant/logs/*
```

**Comment by alexlambson** [comment]
Alright. I'll post everything I can get when I get back to work tomorrow. SQL logs as well. I'll also post if I find out the issue. For now we are just nesting ->contain()

**Comment by markstory** [comment]
Closing - No follow up.
