### ISSUE TITLE
paginator custom URL

### ISSUE THREAD

**Issue by Kepro** [cakephp/cakephp#7221]
Hi all,
i have problem i have route 
```
    $routes->prefix('my',function ($routes) {
        $routes->resources("Houses", function($routes) {
            $routes->resources("Cars");
        });
    });
```
i have url /my/houses/1/cars but paginator still want to go to /my/cars :/ and there is no way to change it

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by Kepro** [comment]
@ADmad i think this is missing feature from the latest cake php for 1.3 and 2.x i find this option but in 3.x they doesn't exist
http://book.cakephp.org/3.0/en/views/helpers/paginator.html#creating-sort-links

**Comment by ADmad** [comment]
Exactly what feature are you referring to? You have linked `PaginatorHelper::sort()` which has the same signature and works similarly in 2.x and 3.x.

**Comment by markstory** [comment]
The sort method works fine. Your URLs are probably missing the required parameters to match your resource routes. Make sure you set the various id properties using options().

**Comment by Kepro** [comment]
@markstory  i read all documentation and i don't find how to change url, still go to /my/cars and not to /my/houses/1/cars where yo set correct property, thanks for sample 

really sorry for this

**Comment by markstory** [comment]
The [options method](http://book.cakephp.org/3.0/en/views/helpers/paginator.html#modifying-the-options-paginatorhelper-uses) lets you set the required URL parameters so your routes will match. I suspect that you need house_id there.

**Comment by Kepro** [comment]
@markstory but this is query params, still i can't use /my/houses/1/cars
i think still this is a missing feature... you create greate resource in resource but i think this is not a good...

**Comment by ADmad** [comment]
It's not just query params. You can use the url array the same way you it anywhere else and set keys like `controller` etc. and your custom route elements too.

**Comment by ADmad** [comment]
The description below the example code even states _"The above adds the `en` route parameter to all links the helper will generate."_

**Comment by Kepro** [comment]
och.. one big thx guys.. sorry one more time, also one last question
this is working
$this->Paginator->options(['url' => ['controller' => 'houses/1/cars']]);
also
$this->Paginator->options(['url' => ['controller' => 'measurers', 'action' => '1/usages']])

but is ugly it's only one way hot to use custom url? Big Thanks for your great work

**Comment by ADmad** [comment]
In future please use the resources I linked earlier if have problem figuring something out.
