### ISSUE TITLE
Cake\I18n\Time has setToStringFormat but json_encodes as ISO8601

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#7226]
Not sure if this is a defect. I would like to modify the way *Cake\I18n\Time* is json_encoded and for me the logical behavior would be to return json_encoded __toString value. But it is set to ISO8601.

I would suggest changing it to:

    public function jsonSerialize()
    {
        return $this->i18nFormat(); // maybe better to $this->__toString()
    }

but if this is a desired behavior, I would suggest adding a method to modify it, something like *setJsonEncodeFormat*. Let me know which one is better (or if none of them and I should create subclass) and I can create pull request.

**Comment by lorenzo** [comment]
I think adding a method to control the format is the best idea. Do you want to contribute that?

**Comment by markstory** [comment]
This new method should probably be static. Calling it on every `Time` instance would suck.

**Comment by markstory** [comment]
Closing. This was fixed in #7231

**Comment by lilHermit** [comment]
Sorry to reopen this, I've tried asking the question in Slack support! 

As far as I can tell with this mechanism there is no way to get unix timestamp in serialised json. Maybe we could add something like Time::setJsonEncodeFormat(null) for unix timestamp.

**Comment by lilHermit** [comment]
Also it seems the default `bootstrap.php` breaks Time::setJsonEncodeFormat

```
Type::build('time')
    ->useImmutable();
Type::build('date')
    ->useImmutable();
Type::build('datetime')
    ->useImmutable();
```

due to `useImmutable()`

**Comment by markstory** [comment]
> Also it seems the default `bootstrap.php` breaks Time::setJsonEncodeFormat

It should work if you `setJsonEncodeFormat()` after changing to immutable objects.

**Comment by markstory** [comment]
> As far as I can tell with this mechanism there is no way to get unix timestamp in serialised json. Maybe we could add something like Time::setJsonEncodeFormat(null) for unix timestamp.

Please open a new issue if you'd like to see improvements to existing functions. Conversations on closed issues are easily lost.

**Comment by lilHermit** [comment]
> It should work if you setJsonEncodeFormat() after changing to immutable objects.

No it doesn't work before or after.

> Please open a new issue if you'd like to see improvements to existing functions. Conversations on closed issues are easily lost.

I'll do that now thanks
