### ISSUE TITLE
add checking of "naughty strings" to the security component

### ISSUE THREAD

**Issue by danielzzz** [cakephp/cakephp#7227]
maybe it would be a good idea to add some option to validate user input against this list of bad strings from this other gh project
https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by hdogan** [comment]
I think you can use [your own validation provider](http://book.cakephp.org/3.0/en/core-libraries/validation.html#adding-validation-providers) (or custom validation rule) which implements this feature. It's not necessary to include it in core.

**Comment by ADmad** [comment]
As @hdogan stated it can be easily done using custom validator in app/plugin. Doesn't need to be in core.

**Comment by jhli** [comment]
And the list itself... 50%+ meh or even too opinionated.

**Comment by ravage84** [comment]
@danielzzz If you think the CakePHP community could benefit from such a functionality, I recommend you to implement it as a CakePHP  plugin. This way others can include the functionality on demand in their project.
Not everything should  end up in a framework...
