### ISSUE TITLE
[Cakephp 3.x] Custom Datasource

### ISSUE THREAD

**Issue by taurus49** [cakephp/cakephp#7230]
Hello everybody,

i need to create an ldap datasource but don't find any help on how creating custom datasource. Someone to help me ? Tnx

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
