### ISSUE TITLE
Update datetime fields doesn't set the entity as modified

### ISSUE THREAD

**Issue by fheider** [cakephp/cakephp#7232]
If you modified a datetime field in an entity, e.g. addDays, the entity would not be set as modified and so nothing would be saved.

Reproduce:
    $item = $tbl->get($id);
    $item->datetime->addDays(2);
    ==> nothing will be saved, because the entity doesn't get, that something has modified

My current workaround:
    $item->datetime = (new Time($item->datetime))->addDays(2);

I don't know if it's bug or a feature. :-)

**Comment by markstory** [comment]
The ORM is unable to track property changes in nested objects. You _can_ use methods on the datetime instances, but you'll need to hint the ORM with `$item->dirty('datetime', true);` This is the same behavior as associations have.
