### ISSUE TITLE
3.1 RFC: Convenience methods for extracting request data / query strings (from form submits)

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7233]
So I came across this and thought about why there was the wish to get back the old findAllByX magic. Ref: https://github.com/cakephp/cakephp/pull/7209

I think it is simply less typing.

Too shorten the code required to filter data I'd much more like to see some convenience controller methods like ```->pd()``` ```->qs()``` for example. pd for post-data and qs for query-string.
Typing comparison:
```php
// Current Verbose
$this->Users->find()->where(['username' => $this->request->data('username')])->all();
// findAllByX suggestion in https://github.com/cakephp/cakephp/pull/7209
$this->Users->findAllByUsername($this->request->data('username'));
// Suggested convenience method
$this->Users->find()->where($this->pd('username'))->all();
```
Pseudo code / untested:
```php
/**
  * Acts similar to compact() but supporting dot notation and matching against $this->request->data
  *
  * @param $lookup is either a string or an array of strings. Those strings are either fieldnames or dot-notation.
  */
public function pd($lookup)
{
    if (!is_array($lookup)) {
        $lookup = [$lookup];
    }
    $conditions = [];
    foreach ($lookup as $string) {
        if (mb_strpos($string, '.') !== false) { // checks for any dot-notation nesting
            $modelfield = explode('.', $string), 1); // Only supports nesting 1 level deep
            $conditions[] = [$string => $this->request->data[$modelfield[0]]$modelfield[1]];
        } else {
            $conditions[] = [$string => $this->request->data[$string];
        }
    }
    return $conditions; // where condition array
}
// public function qs($lookup) would do the same/similar for query strings / http get data.
```

Also allows more ways to get post-data and query strings
```php
$this->Users->find()->where($this->pd('Comment.username'))->all();
$this->Users->find()->where($this->pd(['Article.id', 'Comment.username']))->all();
$this->Users->find()->where($this->pd(['id', 'Comment.username']))->all();
// For code length comparison / verbosity comparsion
$this->Users->find()->where(['Comment.username' => $this->request->data('Comment.username')])->all(); // unsure if it works
$this->Users->find()->where(['Article.id' => $this->request->data('Article.id'), 'Comment.username' => $this->request->data('Comment.username')])->all(); 
$this->Users->findAllByArticleIdAndCommentUsername($this->request->data('Article.id'), $this->request->data('Comment.username')); // unsure if this would even work
```
All of that is a ton shorter and more flexible than: findByX
It is also a lot shorter (yet less flexible) than the current verbose way of doing it.

(This issue assumes something about dot-notation that I know from 2.x - not sure how it works in 3.x - bear with me)

**Comment by markstory** [comment]
What if the shorthand was on the ORM instead of request data reading? I'm not a fan of the proposed names, but I think the idea is reasonable, and reminds me of Rails' [Controller::params](http://guides.rubyonrails.org/action_controller_overview.html#parameters).

**Comment by ionas** [comment]
* I'd say its a transformation of request data/params and thus this is inherently a job that the controller should do. If you agree I can try to prep a PR for this next week. Are there any helpers for transforming Dot Notation to conventional Array Access in the framework already?
* I don't care about the names, they just should be ***very short*** (2-3 charactes) - I am not sure if PHP can do it nowadays but I'd did even consider variable functions like $qs('username') or $pd('username');
http://php.net/manual/en/functions.variable-functions.php 
* In case people overwrite those variables/methods they will simply not be able to use the new feature (e.g. should be BC ok).

p.s.: Maybe all the global functions should be injected by a base object abstract static class that injects variable functions in a future version... like $debug() and $pr() $__())

**Comment by ADmad** [comment]
> they just should be very short (2-3 charactes)

They should be proper descriptive names which don't kill readability.

**Comment by ionas** [comment]
so ```$param('username')```?

**Comment by ADmad** [comment]
> Are there any helpers for transforming Dot Notation to conventional Array Access in the framework already?

You can already do `$this->request->data('user.profile.field')`

**Comment by markstory** [comment]
I'd prefer not to add global variables/global functions that proxy instance objects. The instance resolution and context binding can be complicated.

**Comment by sdustinh** [comment]
What about an opt-in behavior? I've done something similar to this on a lot of my models to solve that problem and avoid using `findAllByX` functions: `$this->Users->findAllByRequest($this->request);`

The only thing that really stopped me from moving forward with developing it more was that the `implementedFinders` key on behaviors don't support regex snippets like the router class (now i'm wondering why I didn't put an issue in) and it was just quicker for me to hardcode a method and move on.

I've used it where the finder method on the model takes the request object, grabs the schema object and checks for columns in the request data. You could use the configuration to limit the type of request to check in (no need to create `qs` and family methods). If the `implementedFinders` key supported regex you could gain your magic method functionality and that could be taken out of the table itself. Anyone who wanted to maintain that behavior... would add the behavior to their table/AppTable. :smile:

**Comment by jhli** [comment]
Takes away control and relies on mass assignment and accessible. Not bad but not close to what is proposed here (separat issue/ticket?. Also meh without AppTable. Possibly a core behavior then?)

**Comment by ionas** [comment]
I really like the short variable names $qs() and $pd() in particular but I get it... like this then?
```php
public function params($lookup, Array $options = array())
{
    if (array_key_exists('type', $options) === false || in_array($options['type'], ['merged', 'get', 'post']) === false) {
        $options['type'] = 'merged';
    }
    $conditions = [];
    foreach ($lookup as $dotnotation) {
        if ($options['type'] === 'merged') {
            $conditions[] = [$dotnotation => $this->request->query($dotnotation)];
            $conditions[] = [$dotnotation => $this->request->data($dotnotation)];
        } else if ($options['type'] === 'get') {
            $conditions[] = [$dotnotation => $this->request->query($dotnotation)];
        } else if ($options['type'] === 'post') {
            $conditions[] = [$dotnotation => $this->request->data($dotnotation)];
        }
    }
    return $conditions;
}

public function postParams($lookup)
{
    return $this->params($lookup, ['type' => 'post']);
}

public function getParams($lookup)
{
    return $this->params($lookup, ['type' => 'get']);
}
```
(Still untestet code)

**Comment by lorenzo** [comment]
I think this belongs in a plugin, look at https://github.com/friendsofcake/search for reference

**Comment by markstory** [comment]
@lorenzo I can see how a sugar interface could help keep controller code succinct. I have concerns with defaulting to reading merged parameters though as it enables sloppy practices like POST requests with all the parameters in the query string.

**Comment by ionas** [comment]
I agree that the merging is not optimal, I was merely looking for short calling statements. Do you have better suggestions than:
1. ```$this->pd()```
2. ```$this->qs()```
3. ```$postdata()```
4. ```$querystring()```
5. ```$this->data()``` would be okay too but ```$this->query()``` is kinda bad cause to newbies it implies something else and it is also hard to read/differentiate if someone dares to create query objects off of table objects in the controller context.
6. ```$this->params()``` seems generic and also collides with whatever params already do (a lot of different things?).

Any suggestions?

**Comment by markstory** [comment]
`$this->data()` and `$this->qs()` could work.

**Comment by josegonzalez** [comment]
Why can't we leave those methods on the request object?

**Comment by ionas** [comment]
Any better and **concise** suggestion?

**Comment by burzum** [comment]
What about a generic transformation of the request into something else? The transformation itself would be a class or anonymous function that would deal with the processing.

Pseudo code:

```php
$query = $this->request->transform('query', $query, [
    'field1', // creates an AND
    'field2' => [
        'type' => OR, // could be a callback as well
    ],
    'field3' => 'OR' // maybe a shortform?
]);
```

Question is how to deal with complex and nested conditions.

**Comment by berarma** [comment]
I'd prefer the more verbose code since it's more readable for me. Anyway, this kind of functionality could be useful for any data array, not just the request parameters, and I think it would fit very well in the Collection class rather than solving just a very specific use case.

**Comment by ionas** [comment]
The collection class thing suggested could be implemented (in that case not by me sorry :/.) and then a convenience method could be added that shortens the calling signature and adds some conventions?

**Comment by ionas** [comment]
I ll close this for now cause I am not happy with two-fold dot-nations that diverge:
* a.) multi-depth dot notation for accessing request data/query
* b.) single-depth dot notation for specifying modelname/fieldname on the ORM

I really liked the findByX and findAllByX things but they lacked a lot of flexibility (like: no logical parentheses). I'd be happy if there was a VERY CONCISE WAY to put request info into the ORMs conditions because:
```php
$this->Users->find()->where(['User.username' => $this->request->data('User.username')])->all();
```
... is long and verbose and has quite some duplication.
