### ISSUE TITLE
3.1 - Don't set layout based on mailer name

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#7234]
Having used the new mailer a bit I would prefer if it didn't auto set layout based on [mailer name](https://github.com/cakephp/cakephp/blob/3.1/src/Mailer/Mailer.php#L120). 

I could have all my mailers extend a custom mailer which sets the layout to avoid this issue, but imo existing behavior is not a good default. I don't think it's common enough to have multiple layouts for emails. Whatever changes in content are required are generally done through template itself.

**Comment by HavokInspiration** [comment]
I agree.
I generally have one layout with logos / footer / etc. and whatever needs to change is done within my templates.

**Comment by ionas** [comment]
:+1:  As long as there is a way to manually set the email template layout I think there should be no convention that sets it to something else than the 'default' html/text email template layout.

**Comment by markstory** [comment]
Closing as a pull request is up.
