### ISSUE TITLE
cakephp 3 fresh installation issue

### ISSUE THREAD

**Issue by Sonik511** [cakephp/cakephp#7238]
I have php 5.4.42 on Linux with Apache and mysql. All the required extensions are loaded and I did a fresh install of cakephp 3 using the command 
>composer create-project --prefer-dist cakephp/app c3

It installed everything but when I went to the URL instead of opening the page it showed me following error
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in c3/config/bootstrap.php on line 107

**Comment by AD7six** [comment]
What's the contents of your config/bootstrap.php file?

**Comment by Sonik511** [comment]
I did not change anything in any of the files. This is the default file which comes with installation

**Comment by Sonik511** [comment]
the line 107 is as marked below
/**
 * Register application error and exception handlers.
 */
$isCli = php_sapi_name() === 'cli';
if ($isCli) {
line 107 ------>>>>>>  (new ConsoleErrorHandler(Configure::read('Error')))->register();
} else {
    (new ErrorHandler(Configure::read('Error')))->register();
}

**Comment by lorenzo** [comment]
You need php 5.4 for running cakephp

**Comment by ADmad** [comment]
Your PHP version is definitely not what you claim it to be.

**Comment by Sonik511** [comment]
$ php -v
PHP 5.4.42 (cli) (built: Jun 16 2015 00:23:52)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by ADmad** [comment]
Check using `phpinfo()`, your web server might be using different version than CLI.

**Comment by Sonik511** [comment]
Thanks a lot. You are right. Php info is showing 5.3.29. Need to check with my hosting provider to correct this.

**Comment by jhli** [comment]
Couldn't we test the minimum pho version in the frontcontroller / before shell buildup?

**Comment by AD7six** [comment]
@jhli how would that be helpful?

**Comment by jhli** [comment]
We won't have tickets like this. To many (newboes) it is also not clear that cli and webserver php may differ and they wonder why the framework crashes despite php -v reporting a good version.
