### ISSUE TITLE
Dashed Route, why not ctp files?

### ISSUE THREAD

**Issue by NaranjaWeb** [cakephp/cakephp#7240]
Cake 3.1.0 beta2:
I followed your suggestion and installed Dashed Route for our standard routing rule.

After changed all the view template files into dasherized ones,
I found that the ctp files still should have to be underscored.

I traced the source and found the line which determines the file name.

3.1.0 beta2 \Cake\View\View::_getViewFileName line 986

	$name = $viewPath . $subDir . Inflector::underscore($name);

If the dashed route is your standard in the future, then I feel comfortable if 
the name of template files can be dasherized.

Is it possible to adopt some kind of options to make this happen?

**Comment by Marlinc** [comment]
I kind of like using underscores for template files more than using dashes

**Comment by NaranjaWeb** [comment]
Yes, this is the matter of preference.

I don't object underscore templates to be the cakePHP3's standard,

but it would be nice if I can choose the format.

Those who don't hesitate to use hyphens in the file name may feel
natural to put the template name same as its url.

Previous rule:
http://example.com/my_controller/my_action <-> my_action.ctp

Current rule:
http://example.com/my-controller/my-action <-> my-action.ctp

**Comment by AD7six** [comment]
I don't think that's a good idea.

Historically the templates matched the controller method name, and the controller method name matched the url action parameter by default.

So whereas before you'd have

    underscored -> underscored -> underscored

Now with dashed route you've got:

    dashed -> underscored -> underscored

(The Dashed route class _still_ produces an underscored `action` parameter by default). 

So Before and now, the template used, by default, matches the controller method name it corresponds to.

I don't see a need/benefit to make the core's behavior configurable, you _could_ use your own view class which does not underscore file names, though I'd suggest to reflect on doing that - it seems to be a change for the sake of being different.

**Comment by ADmad** [comment]
> The Dashed route class still produces an underscored action parameter by default

Nope, it produces `camelCased` action name. PSR2 doesn't like underscored method names.

**Comment by ADmad** [comment]
I don't see the need for changing or making the file name inflection configurable either. 

At best we can just put that particular line which underscores  $name in a separate method and people can override if they like.

**Comment by NaranjaWeb** [comment]
Overridable is fair enough.

All of actions in my project are camelCased to follow PSR-2 rules.
(By setting Custom Route)
dashed -> camelCase -> underscored

Thus, template names are no longer same as action names.
It is just the manner how we change, from camelCase to
snake_style or dash-style.

In my case, myAction becomes my-action in url, 
but the template(content itself) name should be my_action. 

If you start cakePHP from now, from 3.1, and use camelCase to
their actions (by setting customized route as I did) there may be
some people who think the same way as I do.

Anyway, overridable is more than enough.

**Comment by ADmad** [comment]
@NaranjaWeb Would you like to make a pull request with suggested change?

**Comment by NaranjaWeb** [comment]
I am very happy that @ADmad suggested a pull request,

I tried a couple of hours and I feel at a loss.

I blame my ability.
To be very honest, making a pull request is a big challenge to me. Also, I have few experience writing tests. I am glad if someone supports my opinion and write some codes. Anyway, I will try. Thank you.

**Comment by NaranjaWeb** [comment]
I made a pull request, which just put the underscoring $name line in a separate method.
This is just extracting one line and I have no idea how I can write tests. I feel sorry but this is what I can achieve for now.
