### ISSUE TITLE
Not possible to stop login redirect anymore

### ISSUE THREAD

**Issue by jmenges** [cakephp/cakephp#7243]
Hello there,
i've been using cakephp for a while and have recently upgraded my platform the 3.* branch (Current version: 3.0.10).
Now i have run into a problem that is quite unexpected to me.

When i authenticate a user, e.g post to /users/login i always get 302 found redirects. Before i had a setup, where i had a ajax submit of my form to the login action and depending on the results i'd return some json data, which would than be consumed by the success function of the jquery form submission.

I dont know if i am missing a parameter, or if there is a better way to do this in 3.x.

Thanks in advance,
Jonas

**Comment by ADmad** [comment]
The AuthComponent does not have any automatic redirects anymore after authentication. The redirect is being done by your app code.

**Comment by jmenges** [comment]
Oh my. I'd been searching everywhere.
My Ldap Authenticator was redirecting on unauthenticated, even for ajax requests.
Thanks for the heads up!
