### ISSUE TITLE
cakedc search Use AND/OR connector 

### ISSUE THREAD

**Issue by kostalihas** [cakephp/cakephp#7244]
in my query request i have this surprise: LEFT JOIN dcsearch.competences AS Competence ON (CompetencesUser.competence_id = Competence.id) WHERE ((((Competence.competence LIKE '%First\%%') AND (Competence.competence LIKE '%Second\%%'))) OR (Competence.competence LIKE '%Third\%%')))

this is my model user.php

public $hasAndBelongsToMany =

array(
        'Competence' => array(
            'with' => 'CompetencesUser',
            'className' => 'Competence',
            'joinTable' => 'competences_users',
            'foreignKey' => 'user_id',
public $filterArgs = array(

'competences' => array(

            'type' => 'subquery',
            'method' => 'findByCompetences',
            'field' => 'User.id',

         'connectorsAnd' => '+', 
         'connectorOr' => ',',
          'before' => true,
           'after' => false)

);
public function findByCompetences($data = array()) {

$this->CompetencesUser->Behaviors->attach('Containable', array( 'autoFields' => false ) );

$this->CompetencesUser->Behaviors->attach('Search.Searchable');
//$data = array('competences' => 'Cake');

$data = array('competences' => 'First%+Second%, Third%');

$result = $this->CompetencesUser->parseCriteria($data);

$expected = array(0 => array('OR' => array(
    array('AND' => array(
        array('Competence.competence LIKE' => '%First\%%'),
        array('Competence.competence LIKE' => '%Second\%%'),
    )),
    array('AND' => array(
        array('Competence.competence LIKE' => '%Third\%%')
    )),
)));

$query = $this->CompetencesUser->getQuery('all', array(

   'conditions' =>array(
    $expected,
    $result),

    'fields' => array(
      'user_id'
   ),
    'contain' => array(
       'Competence'
)));

 return $query;
}

**Comment by josegonzalez** [comment]
As this is not an issue with the CakePHP core, I would file an issue with the plugin you are using [here](https://github.com/cakedc/search/issues).

**Comment by kostalihas** [comment]
this is my project and my databases​
 DcSearch.rar
<https://drive.google.com/file/d/0Bz7Z2Rmt3ts5N3p2MGFsODg4WTQ/view?usp=drive_web>
​

2015-08-17 18:16 GMT+01:00 Jose Diaz-Gonzalez <notifications@github.com>:

**Comment by kostalihas** [comment]
i want search by competence java+oracle,sql
then the method of the request competence must know java is first oracle is
second and sql is thirth
thank you.

2015-08-17 18:31 GMT+01:00 kostali hassan <med.has.kostali@gmail.com>:
