### ISSUE TITLE
Paginate by virtual fields?

### ISSUE THREAD

**Issue by jeanbez** [cakephp/cakephp#7246]
Is it possible to paginate by a virtual field? If not, is this possible or planned?

**Comment by markstory** [comment]
No it is not possible, nor can it ever be done. Virtual properties are synthesized in the entity objects and thus cannot be used in based SQL operations like pagination.

**Comment by ionas** [comment]
Yes you can, by using SQL Views and creating virtual fields in there, not by using cake3 virtual fields.
