### ISSUE TITLE
Time defect

### ISSUE THREAD

**Issue by Adnan0703** [cakephp/cakephp#7248]
Here's how to reproduce it.

````
		$time = '6-Jan 1900';
		$time = new \Cake\I18n\Time($time);
		debug($time->i18nFormat('d MM. yyyy'));
````
`output: false`

````
		$time = '6-Jan 1900';
		$time = new \Cake\I18n\Time($time);
		debug((string)$time);
````
 `output: ''`

````
		$time = '6-Jan 1900';
		$time = new \Cake\I18n\Time($time);
		debug($time->format('j M. Y'));
````
 `output: 6 Jan. 1900`

Why `i18nFormat` doesn't give the same date as `format`?

**Comment by antograssiot** [comment]
@Adnan0703 for me the following code 
```php
$time = '6-Jan 1900';
$time = new \Cake\I18n\Time($time);
debug($time->i18nFormat('d MM. yyyy'));
```
outputs the expected code
```
'6 01. 1900'
```

**Comment by Adnan0703** [comment]
I tested it on Windows 8, PHP 5.5.0.
It also gives the following warning.
````
Method Cake\I18n\Time::__toString() must return a string value [APP/Controller\SomeController.php

````

**Comment by lorenzo** [comment]
@Adnan0703 Looks like you have a broken intl extension or an outdate php version. Try updating to at least the latest php 5.5

**Comment by chinpei215** [comment]
@lorenzo I could reproduce this issue on Windows 10, PHP 5.6.12.
On windows, intl seems to only work for timestamps in a 32-bit signed integer.
(`1901-12-13T20:45:52+00:00` to `2038-01-19T03:14:07+00:00`)

```php
ini_set('intl.error_level', E_WARNING);
$fmt = datefmt_create('en_US',null,null,'UTC',null,'yyyy-MM-dd HH:mm:ss');
echo $fmt->format(new DateTime('1901-12-13T20:45:52+00:00'));
//1901-12-13 20:45:52
echo $fmt->format(new DateTime('1901-12-13T20:45:51+00:00'));
//Warning: IntlDateFormatter::format(): datefmt_format: error calling ::getTimeStamp() on the object in ...
```

**Comment by Adnan0703** [comment]
@lorenzo I upgraded to php 5.6.11 by installing latest xampp. The result is same. 
`static::$_formatters[$key]->format($date)` returns `false`.

**Comment by markstory** [comment]
@chinpei215 Are you using 32bit windows, or a 32bit build of PHP?

**Comment by chinpei215** [comment]
@markstory I am using 64bit windows and I tested this on [experimental 64bit build of PHP](http://windows.php.net/download#php-5.6-ts-VC11-x64).
According to the [php maunal](http://php.net/manual/en/language.types.integer.php#example-82), windows might not support for 64bit integer.

> The size of an integer is platform-dependent, although a maximum value of about two billion is the usual value (that's 32 bits signed). 64-bit platforms usually have a maximum value of about 9E18, except for Windows, which is always 32 bit.
