### ISSUE TITLE
Cake 3 disable callbacks in Table save()

### ISSUE THREAD

**Issue by stefanozoffoli** [cakephp/cakephp#7249]
Hi all,
I'd like to disable `beforeSave()` and `afterSave()` callbacks in a Table `save()`.
In cake 2 I could add a `'callbacks'` parameter to `false` in save options to achieve that ( http://book.cakephp.org/2.0/en/models/saving-your-data.html#model-save-array-data-null-boolean-validate-true-array-fieldlist-array )

Is it a good idea to port this to cake 3?

**Comment by lorenzo** [comment]
No, disabling callbacks was a common source of bugs in applications. Use `updateAll`, `$table->query()->update()` or a new instance of `Table` if you need this.

**Comment by avneeshroks** [comment]
@lorenzo 

I am using this approach to create a new record : 

1. creating a new entity
2. Patching that entity with array
3. doing $this->Model->save($pachedEntity);

In this case i've some associated model which are also getting created while doing save. and those models have some afterSave code that i want to bypass.

How can i achieve this. Please help.

And not able to achieve this with updateAll(). 

Thanks

**Comment by thinkingmedia** [comment]
@avneeshroks 

You have two options:

1. Create another model in your `app/Models/Table` folder, and point it at the same database table. Don't give this new model any of the associations that are causing you trouble.
2. Remove the association from the model before you call save.

**Comment by avneeshroks** [comment]
@thinkingmedia : I've tried like this - 

1st one works for me :) thanks a lot. 

Also i've tried this: 
public function afterSave(Event $event, EntityInterface $entity, ArrayObject $options) {
        if(!empty($options['_sourceTable'])) {
            return true;
        }
       // Other logic here
}

this also worked for me. 

Just curious, is this a good way?

**Comment by ADmad** [comment]
@avneeshroks There's no need for `return true`, just `return` is fine.

**Comment by avneeshroks** [comment]
@ADmad : Ohh cool Thanks ...

**Comment by Xymanek** [comment]
The way I've done something similar before is that I would pass a option (eg. `disableMyOwnLogic`) and set it to true. Then in event handler I would check if that option is set to `true` and `return` if it is, preventing my own logic from running

**Comment by thinkingmedia** [comment]
@avneeshroks checking for options in the `afterSave` can work, but it creates this small piece of logic in your source code that is hard to find later on.

**Comment by Xymanek** [comment]
@thinkingmedia This is the way I've done it to work around that inconvenience:

```php
// Inside afterSave()
if (isset($options[self::UPDATE_POLL]) && $options[self::UPDATE_POLL] === false) {
    return;
}
```

By using constants I'm able to utilize PhpStorm's find usages feature in order to see where I invoke my logic

**Comment by markstory** [comment]
If you need to disable callbacks, perhaps your callbacks are doing too much work? I find using callbacks leads to a bunch of awkward situations as an application grows. Instead of using callbacks you could use service classes that do your 'callbacks'.

**Comment by styks1987** [comment]
I commonly need this for testing purposes. In my test case I usually have a private function that disables all callbacks, listeners, ect.

I just pass the instantiated class from my test case in my setUp method

```
    private function _removeAllListeners($class)
    {
        foreach($class->eventManager()->matchingListeners('') as $event => $values) {
            $class->eventManager()->off($event);
        }
    }
```
