### ISSUE TITLE
"count" variable inside pagination is grater than expected if you are using MapReduce

### ISSUE THREAD

**Issue by warriorkitty** [cakephp/cakephp#7250]
Line of code which causes the problem:
http://api.cakephp.org/3.0/source-class-Cake.Controller.Component.PaginatorComponent.html#174

If you use MapReduce inside your query (and you reduce some of your records), the $count variable will not be correct.

Effect:
Paginator shows 3 pages in result, and not 1 (in my case).

**Comment by lorenzo** [comment]
Pagination happens in the database server, mapReduce in PHP. The mapReduce phase has no effect on the pagination

**Comment by warriorkitty** [comment]
Your answer **still** doesn't solve the problem with the wrong $count inside Paginator. It shows different result count in View.

**Comment by markstory** [comment]
We can't really make the count 'right' though as the map reduce filters are applied after the count is generated.

**Comment by warriorkitty** [comment]
OK, thank you for your answers. One *hackish* way I'm going to try is to count($query->toArray()) and try to put that number inside Paginator (I don't know if there is a "public" way of changing the count, I need to look at the source code).

I know that count() will "prematurely" execute the query and that (maybe) I'm executing the query twice (once for the count and the second time for the actual ResultSet) but I only have this one example and Pagination is a must.
