### ISSUE TITLE
ORM: Unexpected behavior with 'WHERE  IN' and array only has one element. 

### ISSUE THREAD

**Issue by glkaup** [cakephp/cakephp#7252]
I'm using the following conditions for a where clause:
`    $conditions = [ 'Things.id' => $id, 'Things.something_id' => $smt_id_array];`
This produces sql that correctly reads:
`    Things.something_id = :c1`    which would seem to be correct.

If $smt_id_array has more than one element, the select produces the correct results.  However, if it contains a single element, the results will return only one record of the expected result set of 7.  

I have not tested what happens if the $smt_id_array is an array but has NO elements or if it is NULL!  I have seen other items discussing the NULL case, but have not historically allowed that unless I wanted an IS NULL (or IS NOT NULL), but that is another discussion!

As a work around, I have changed the $conditions line above:
`    $tmp_ids = (count($smt_id_array) > 1) ? $smt_id_array : $smt_id_array[0];`
`    $conditions = [ 'Things.id' => $id, 'Things.something_id' => $tmp_ids];`
which can properly handle both cases... The first generating an = and the second generating IN (...).

Cake tries to get it right by using the = or IN, but does not handle the = correctly.  Is this the desired behavior?  Seems that it should handle the single item array... even if it still produces an IN (:c1) instead of an = :c1

**Comment by GuidoHendriks** [comment]
If I remember correctly, you should use this condition instead:

    'Things.some_id IN' => $aray

**Comment by markstory** [comment]
@GuidoHendriks is right. You must opt into the `IN` behavior. We do not want to allow automatically convert `=` into `IN` as it can lead to unexpected query manipulation if malicious users are crafty.

**Comment by glkaup** [comment]
@markstory does the 3.0.12 milestone mentioned above mean that there will be a fix the array containing a single item?

**Comment by dereuromark** [comment]
No it was just filed in that version. There is no fix to be applied as this is intentional behavior - as mentioned above.

**Comment by glkaup** [comment]
Then why can't you make the special case of a single item array still do an IN ($id) clause!  For crying out loud, a single item array is still an array!  Just because it only has one item is not the fault of the situation is it?

**Comment by dereuromark** [comment]
Single Item array being `count($array) > 1`?
So far you only mentioned empty arrays.

**Comment by glkaup** [comment]
Sorry, but I think I did!
 However, if it contains a single element, the results will return only one record of the expected result set of 7.  
Seems that it should handle the single item array... even if it still produces an IN (:c1) instead of an = :c1

Now, since then I've added the IN clause, but and arrays work as expected... BUT the single item array picks up ALL records.

**Comment by glkaup** [comment]
NO single item array is $an_array = array 1234 );

**Comment by dereuromark** [comment]
After reading your initial report again I now understand what you mean.
And sry, that was a typo, === 1 it is, yes.

But what I don't understand is how in your case the result differs. For me `IN ('x')` is essentially the same as `= 'x'`. The results of that query are identical. And that would be the result of your single item array.

**Comment by glkaup** [comment]
I'm NOW using the following on a table setup with 33 test records:

    'contain' => [ 'AttendeesEventSpecialCategories' => function ($q) use ($wantedArrayCatgId) {
                        return $q->where('AttendeesEventSpecialCategories IN' => $wantedArrayCatg)
                   }
                 ]
 
This becomes part of the $params to:

    $ans = $this->find('all', $params);
    $ans_count = $ans->count();
    debug($ans_count);

Now... If the wantedArray is empty, NULL, or has a count of 1 that is NULL, I don't even execute this find.

The find is executed on count > 0 only, and I get the correct results (usually 3 to 7 records) every time when the array has 2 or more items.  But when the array has a count == 1, cakePHP 3.0.9 returns all 33 records of my test database instead of the 4 that I expect.

Now... if I have a count == 1 such as $tarray = array( 1234 ); I can get it to work if I turn it into $tarray = array( 1234, 1234)!

**Comment by markstory** [comment]
I'm not able to reproduce the issue you're having with the single element array.

```
>>> $users = Cake\ORM\TableRegistry::get('Users');
=> App\Model\Table\UsersTable {#214
     +"registryAlias": "Users",
     +"table": "users",
     +"alias": "Users",
     +"entityClass": "App\Model\Entity\User",
     +"associations": [
       "bookmarks",
       "profiles",
     ],
     +"behaviors": [
       "Timestamp",
     ],
     +"defaultConnection": "default",
     +"connectionName": "default",
   }
>>> $users->find()->where(['Users.id IN' => [1]])->count();
=> 1
>>> $users->find()->where(['Users.id IN' => [1]])->toArray();
=> [
     App\Model\Entity\User {#271
       +"id": 1,
       +"email": "test@test.com",
       +"password": "$2y$10$YiRxChYE8AEDTVu8D5yWMOe/AeUSC6ENfRrtTCt3cZa9pUrPzCir6",
       +"dob": null,
       +"created": Cake\I18n\Time {#270
         +"time": "2014-10-05T03:27:39+0000",
         +"timezone": "UTC",
         +"fixedNowTime": false,
       },
       +"updated": null,
       +"digest_hash": "4a52741fdff0f68907ab7c5efe5c4d77",
       +"[new]": false,
       +"[accessible]": [
         "email" => true,
         "password" => true,
         "bookmarks" => true,
         "profile" => true,
         "digest_hash" => true,
       ],
       +"[dirty]": [],
       +"[original]": [],
       +"[virtual]": [],
       +"[errors]": [],
       +"[repository]": "Users",
     },
   ]
>>> $users->find()->where(['Users.id IN' => [1, 2]])->count();
=> 2
>>> $users->find()->where(['Users.id IN' => [1, 2]])->toArray();
=> [
     App\Model\Entity\User {#294
       +"id": 1,
       +"email": "test@test.com",
       +"password": "$2y$10$YiRxChYE8AEDTVu8D5yWMOe/AeUSC6ENfRrtTCt3cZa9pUrPzCir6",
       +"dob": null,
       +"created": Cake\I18n\Time {#308
         +"time": "2014-10-05T03:27:39+0000",
         +"timezone": "UTC",
         +"fixedNowTime": false,
       },
       +"updated": null,
       +"digest_hash": "4a52741fdff0f68907ab7c5efe5c4d77",
       +"[new]": false,
       +"[accessible]": [
         "email" => true,
         "password" => true,
         "bookmarks" => true,
         "profile" => true,
         "digest_hash" => true,
       ],
       +"[dirty]": [],
       +"[original]": [],
       +"[virtual]": [],
       +"[errors]": [],
       +"[repository]": "Users",
     },
     App\Model\Entity\User {#309
       +"id": 2,
       +"email": "derp@derpy.com",
       +"password": "$2y$10$Ac5vGXjAL6xMzm3Iu2Hw2utEuBZNOpsRdmgdr0NC6RVPZrsr5NZc.",
       +"dob": null,
       +"created": Cake\I18n\Time {#305
         +"time": "2014-10-05T03:28:36+0000",
         +"timezone": "UTC",
         +"fixedNowTime": false,
       },
       +"updated": null,
       +"digest_hash": null,
       +"[new]": false,
       +"[accessible]": [
         "email" => true,
         "password" => true,
         "bookmarks" => true,
         "profile" => true,
         "digest_hash" => true,
       ],
       +"[dirty]": [],
       +"[original]": [],
       +"[virtual]": [],
       +"[errors]": [],
       +"[repository]": "Users",
     },
   ]
>>>
```

Both the single element array and multiple elements work as expected for me.
