### ISSUE TITLE
Customizing Datetime Inputs - Form Helper

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#7254]
-> Cannot place label in the 'dateWidget' to customize the layout of input.
-> 'datetimeContainer' is mentioned on [This page](http://book.cakephp.org/3.0/en/views/helpers/form.html#list-of-templates) but not working.
-> Cannot keep label with day() and other related options [Link](http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-day-inputs)

**Comment by markstory** [comment]
> Cannot place label in the 'dateWidget' to customize the layout of input.

Correct. You'll need to make a custom datetime widget to do that.

> Cannot keep label with day() and other related options Link

No the label has to be created separately when using day() etc.

> 'datetimeContainer' is mentioned on This page but not working.

What did you try? It works for me.

```php
$this->Form->templates(['datetimeContainer' => '<marquee>{{content}}</marquee>']);
$this->Form->input('created', ['type' => 'datetime']);
```

**Comment by gauravmak** [comment]
Oh, I didn't know I have to mention type (as datetime) because it was already converting it to a date select options based on the datatype of the column. Thank you.
