### ISSUE TITLE
TimeAgoInWords formatter

### ISSUE THREAD

**Issue by Bl00per** [cakephp/cakephp#7257]
I would like to see an option to format the output string TimeAgoInWords is rendering. 

Right now it is possible to translate everything except the words between.
For example:
Current state output: 17 minutes, 45 seconds
Wanted output: 17 minutes and 45 seconds

Is it possible that everything in the generated string is editable?

**Comment by lorenzo** [comment]
Please keep questions to IRC or StackOverflow. This is the issue tracker.

If you have requests about improving the code or ideas on how to do it, you can use this tracker :)
