### ISSUE TITLE
3.x ORM modifier() does not work as expected

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7259]
```modifier()``` is being ignored on these two calls:

```php
$this->query()
    ->delete()
    ->modifier('LOW_PRIORITY')
    ->where(['valid_thru <' => new Time()])
    // ->sql(): 'DELETE FROM tokens WHERE valid_thru < :c0'
    ->execute();
```
```php
$this->query()
    ->update()
    ->modifier('DELAYED')
    ->set(['valid_thru' => $validThru])
    ->where(['identifier' => $identifier])
// ->sql(): 'UPDATE tokens SET valid_thru = :c0 WHERE identifier = :c1'
    ->execute();
```
By ignored I mean... it does not trigger any error but does neither appear in the SQL statement, but should.

**Comment by dereuromark** [comment]
Careful, are you having a space after `<`? There should be none.
So

    ->where(['valid_thru < ' => new Time()])

should be

    ->where(['valid_thru <' => new Time()])

**Comment by ionas** [comment]
the queries do actually work WITH the space already. but I will try. :)

**Comment by ionas** [comment]
The queries do actually work WITH the space already (at least in my 3.1.x). I did change it. Same issue.

**Comment by dereuromark** [comment]
OK, I just wanted to make sure.

**Comment by markstory** [comment]
Modifiers are only applied to select queries. I'm not sure modifier() is the correct name for the MySQL specific extensions like delayed/low_priority.

**Comment by jhli** [comment]
Low priority exists for SELECT and UPDATE.
https://mariadb.com/kb/en/mariadb/high_priority-and-low_priority-clauses/

IGNORE is another one:
https://dev.mysql.com/doc/refman/5.0/en/update.html.

Mode or modifer sounds right to me. modifier() exists already.

DELAY is another one:
http://dev.mysql.com/doc/refman/5.6/en/insert.html

@lorenzo suggested to add an issue. Furthermore I'd really like to be able to add those to update statements for low prio token/session updates.
