### ISSUE TITLE
Issue with cache and permissions in a vagrant environment

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#7261]
Hi!

I'm trying to setup an environment where I can use vagrant and have the source code in a shared NFS folder on my computer, and then have cake access it through the NFS system. I have an issue with file permissions in NFS, where they're not reported correctly, so if you do a chmod - it doesn't actually change anything on the host machine - and even though permissions seems like 0644 - they're actually 0777 on the guest OS

Quote: 

>>> Vagrant configures NFS in such a way that no matter who writes to the disk in the guest, it is mapped to the correct user on the host, so you generally don't need to worry about the permissions. They're effectively 0777 in the guest (though they SAY otherwise).

>>> So, the only problems happen if the software actually checks the permission bits rather than testing the permissions by writing. I don't think Apache/Nginx do this, so you should be okay.

(See author of Vagrant's answers here: https://github.com/mitchellh/vagrant/issues/2928)

Because of this error (I think) I'm getting an warning every time I'm trying to create a cache file, (or by using bin/cake orm_cache build) - errors following:

Doing `bin/cake orm_cache clear && bin/cake orm_cache build` spits out lots of these errors:

```
Warning Error: chmod(): Operation not permitted in [/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 396]

2015-08-19 16:25:47 Warning: Warning (2): chmod(): Operation not permitted in [/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 396]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 139
chmod - [internal], line ??
Cake\Cache\Engine\FileEngine::_setKey() - CORE/src/Cache/Engine/FileEngine.php, line 396
Cake\Cache\Engine\FileEngine::write() - CORE/src/Cache/Engine/FileEngine.php, line 130
Cake\Cache\Cache::write() - CORE/src/Cache/Cache.php, line 213
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 68
Cake\Shell\OrmCacheShell::build() - CORE/src/Shell/OrmCacheShell.php, line 51
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 380
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 204
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 175
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 126
[main] - ROOT/bin/cake.php, line 20



Warning Error: Could not apply permission mask "/var/www/dev/apacta-2/tmp/cache/models/myapp_cake_model_default_users_roles" on cache file "0777" in [/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 401]

2015-08-19 16:25:47 Warning: Warning (512): Could not apply permission mask "/var/www/dev/apacta-2/tmp/cache/models/myapp_cake_model_default_users_roles" on cache file "0777" in [/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 401]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 139
Cake\Cache\Engine\FileEngine::_setKey() - CORE/src/Cache/Engine/FileEngine.php, line 401
Cake\Cache\Engine\FileEngine::write() - CORE/src/Cache/Engine/FileEngine.php, line 130
Cake\Cache\Cache::write() - CORE/src/Cache/Cache.php, line 213
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 68
Cake\Shell\OrmCacheShell::build() - CORE/src/Shell/OrmCacheShell.php, line 51
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 380
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 204
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 175
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 126
[main] - ROOT/bin/cake.php, line 20
```

First time I'm trying to access an action after clearing cache, I get the following:
```
Warning (2): chmod(): Operation not permitted [CORE/src/Cache/Engine/FileEngine.php, line 396]
Warning (512): Could not apply permission mask "/var/www/dev/apacta-2/tmp/cache/models/myapp_cake_model_default_users" on cache file "0777" [CORE/src/Cache/Engine/FileEngine.php, line 401]
```

So - same, same.

Weird thing is that the files are made correctly after I visit the page (and get the error message) - with following result from the guest OS:

```
$ ls -lah tmp/cache/models/
total 32K
drwxrwxr-x 7 www-data www-data  238 Aug 19 16:27 ./
drwxrwxr-x 5 www-data www-data  170 Aug 18 22:18 ../
-rw-rw-r-- 1 www-data www-data 4.1K Aug 19 16:27 myapp_cake_model_default_companies
-rw-rw-r-- 1 www-data www-data 2.9K Aug 19 16:27 myapp_cake_model_default_contacts
-rw-rw-r-- 1 www-data www-data 1.8K Aug 19 16:27 myapp_cake_model_default_roles
-rw-rw-r-- 1 www-data www-data 4.0K Aug 19 16:27 myapp_cake_model_default_users
-rw-rw-r-- 1 www-data www-data 1.7K Aug 19 16:27 myapp_cake_model_default_users_roles
```

Is it just me that's misunderstanding, or is the error caused by this line: https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/FileEngine.php#L396 and composer/nfs being weird?

**Comment by markstory** [comment]
The permissions you are getting in `ls` do not reflect `0777`, they are `0664`. So the code is correct as the files have not has the correct permissions applied.

Does removing that check resolve the issue you're having? Removing that check is not ideal as it means we may silently fail to write cache files on non NFS based filesystems.

**Comment by Spriz** [comment]
Removing the check seems to make everything work, but I agree on you that it's not ideal to remove it! :smile: 

I ended up just using Redis for the cache rather than filesystem..... :+1:

**Comment by jhli** [comment]
I am having similar issues with the same basic setup but as it also affects pure filew for me (e.g. syncing sometimes delayed) - I did not consider cake (or any other franework part) to be the problem. I ll try again with filew that don't go through cake.

**Comment by markstory** [comment]
I'm going to close this as I don't think removing that check is wise. Perhaps trying non-NFS ways of mounting shared directories will yield fewer issues, but I can't think of anything we could do at the library level to address this.

**Comment by jhli** [comment]
Thats fair. Seems redos can easily be installed via puphpet, too - doesn't it @ spriz ?

**Comment by Spriz** [comment]
Yes, it was actually a one click thing... Didn't even have to state ports,
username, password or ip :-)
fre. 21. aug. 2015 kl. 00.50 skrev HT-Studios <notifications@github.com>:
