### ISSUE TITLE
RFC - config() should merge shallow by default.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7267]
As per https://github.com/cakephp/cakephp/pull/5629#issuecomment-132560262

config() should be merging "shallow"ly by default in 4.0+, and configDeep() should merge deeply.
Currently it is the other way around in 3.x and this leads to unexpected behavior in behavior config for example.

```
$this->articles->behaviors()->Slugged->config('label', ''); // Hack necessary for config() to avoid title showing up twice
$this->articles->behaviors()->Slugged->config(['mode' => 'ascii', 'unique' => true, 'label' => ['title', 'long_title']]);
```

Without the first overwrite the label would be [title, title, long_title] here because it was [title] before.

Merging shallow (string key based) is most likely the default in 99% of all cases.

**Comment by ADmad** [comment]
You can use a comma separated list instead of array :troll:

**Comment by ADmad** [comment]
Why do you need 2 call to `config()` instead of single call to `shallowConfig()` as:

```php
$this->articles->behaviors()->Slugged->shallowConfig(['mode' => 'ascii', 'unique' => true, 'label' => ['title', 'long_title']]);
```

**Comment by dereuromark** [comment]
The root issue is not about config() where you can use the different config method, but when you use `$this->addBehavior()` etc where you cannot just switch configs.

Also, the above just showed the issue with config() and the intuitive expectation and how it fails.

**Comment by ADmad** [comment]
> The root issue is not about config() where you can use the different config method, but when you use $this->addBehavior() etc where you cannot just switch config merge types afaik.

Okay, you should have provided a more relevant example :)

**Comment by dereuromark** [comment]
@ADmad Probably. Using deep by default you expect well knowledge of what merge type to use (or not to use) for configs where as in default case it would not be necessary as almost all the string based config is shallow.
Just saying.

**Comment by ADmad** [comment]
I was just pointing out that the e.g. you provided didn't adequately highlight the issue. I don't mind changing the default.

**Comment by ADmad** [comment]
To clarify I would prefer keeping behavior of `config()` the same but when loading objects `configShallow()` can be used instead of `config()` so that shallow merge is done.

**Comment by dereuromark** [comment]
I would rather make it consistent in both ways. To avoid further confusion then from there on.

**Comment by lorenzo** [comment]
Changing the default merge type makes sense to me

**Comment by markstory** [comment]
Changing the default merge strategy will make working with AuthComponent more difficult I think. Not a blocker, but something to be aware of.

**Comment by dereuromark** [comment]
Yes, I agree.
Once we change to the shallow by default in the next major version we can add (and also BC before) a config key with underscore to allow customizing this when initializing.

    _shallow => false/true
    // or
    _mergeDeep => true/false


example config then passed into the $config array:

    'MyNamespace' => [
         '_mergeDeep' => true,
        'label' => ['title' => '...', 'long_title' => ...]
        ...
    ]

This could easily allow switching based on this config option passed then as a convenience way at runtime.

**Comment by saeideng** [comment]
do you think we should have `setConfigShallow` in 3.6?

**Comment by markstory** [comment]
We could, but it will create another hard to detect breaking change. The existing behavior while not ideal is documented and we have merge options and configShallow() for when shallow configuration changes need to be made.

**Comment by dereuromark** [comment]
So moving to 5.x then to discuss there? Fair enough.
