### ISSUE TITLE
[Enhancement]Adding an option to disable the creation of virtual properties in the entity

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#7269]
Hi,
With CakePhp 2.x we can disable the callback **beforeFind**, **afterFind** even **both** by adding a key in the **find array** like this:
```php
'callbacks' => true //other possible values are false, 'before', 'after'
```
In Cakephp 3 the callback **afterFind** was replaced by creating/updating **virtual properties** in the **Entity** using magic **setters/getters**.
Sometimes we don't need to create/update this virtual properties !

**Comment by ADmad** [comment]
Since virtual fields are generated in PHP it's rarely enough overhead to warrant disabling them. You might as well disable hydration if you don't want virtual fields.

**Comment by ADmad** [comment]
Regarding beforeFind() and formatResults() put them in a custom finder and use the finder only when required.

**Comment by lorenzo** [comment]
I'm not following, what does `callbacks` have to do with virtual properties?

**Comment by flashios09** [comment]
@lorenzo 
I want to compare the request data(after submitting an edit form) and the preexistent entity to check if there is at least a change. I patch the entity and check  ```$entity->dirty()```.
If it returns false -> I display a flash message to the user **"No modifications found"**
```php
// ArticlesController.php::edit($id)
$requestData = $this->request->data;
// debug $requestData
['name' => "Single", 'state' => '1']

$preexistentEntity = $this->Articles->get($id, ['fields' => ['name', 'state']]);
// debug $preexistentEntity
object(App\Model\Entity\Article) {
	'name' => 'Single',
	'state' => true,
	'[new]' => false,
	'[accessible]' => [
		'name' => true,
		'state' => true
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Articles'
}

// debug $preexistentEntity->state
(int) 1
```
I have a method **_getState** in **Entity\Article.php** that change the value of the **state** property:
```php
protected function _getState(){
    return ($this->_properties['state']) ? 1 : 0;
}
```
Now when i patch the $requestData and the $preexistentEntity
```php
// always in the same action ArticlesController::edit($id)
$patchedEntity = $this->Articles->patchEntity($preexistentEntity, $requestData);
// debug $patchedEntity
object(App\Model\Entity\Article) {
	'name' => 'Single',
	'state' => true,
	'[new]' => false,
	'[accessible]' => [
		'name' => true,
		'state' => true
	],
	'[dirty]' => [
		'state' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Articles'
}
// debug $patchedEntity->dirty()
true
```
That's why i need the original entity without the created/updated property in the Entity

**Comment by markstory** [comment]
So is state a virtual property or one that exists in the schema?

**Comment by flashios09** [comment]
@markstory State exists in the schema not a virtual field, i update his value using the _getState() getter in the Entity.
I just want to get the original entity, compare it with request data to avoid unnecessary 'Save'(update) if the user click on the submit button without changing any thing.

**Comment by lorenzo** [comment]
Sounds like you could use `equalsTo()` method in your entities for doing such comparisons. I'm closing this ticket as it seems something mainly relevant to applications and the specifics of how the frameworks is used and is not related at all with callbacks.

**Comment by flashios09** [comment]
@lorenzo I can't find the ```equalsTo()``` method to compare the **request data** with the **$preexistentEntity**, the ```patchEntity($preexistentEntity, $requestData, $options)``` method call the merge method in the marshaller. 
Can you tell me please what do you do when you want to check if the user made a change in a form before submitting it ?

**Comment by lorenzo** [comment]
You need to create it yourself, according to your won logic. You can of course pass the request data to the entity to be compared.

Let's try to keep the hel requests out of the issue tracker. I can gladly guide you in IRC or create a question in StackOverflow so it can be answered

**Comment by flashios09** [comment]
@lorenzo Sorry, can you give me the cakephp IRC to continue our conversation ?

**Comment by lorenzo** [comment]
the `#cakephp` channel in freenode.net

**Comment by flashios09** [comment]
@lorenzo what's your nickname on IRC ?

**Comment by lorenzo** [comment]
@flashios09 it is `jose_zap`
