### ISSUE TITLE
Error Unable to locate an object compatible with paginate.

### ISSUE THREAD

**Issue by kailash1991** [cakephp/cakephp#7270]
i have created a controller using cakebake console so its created  controller correctly but it's showing 

Unable to locate an object compatible with paginate. [error] 

my code is given below

<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * ProductCategory Controller
 *
 * @property \App\Model\Table\ProductCategoryTable $ProductCategory
 */
class ProductCategoryController extends AppController
{
    
    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        parent::initialize();
        $this->loadComponent('Paginator');

        $this->set('productCategory', $this->paginate($this->ProductCategory));
        $this->set('_serialize', ['productCategory']);

    }

**Comment by ADmad** [comment]
Controller and Table names are supposed to be plural. So use plural form when baking.

**Comment by gurpreetkaur87** [comment]
I have provided table names in pural form, still facing same issue. Please help me.
