### ISSUE TITLE
Invalid parameter number: number of bound variables does not match number of tokens

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#7272]
This piece of code:
```php
        $query = $this->Users->find();
        $query->select([
            'admin' => $query->func()->if([$query->newExpr()->add(['Users.name' => 'admin']), 0, 1 ], ['literal', 'integer', 'integer']),
        ]);
        $query->where(['Users.id' => 1]);
        $query->all();
        $query->count();
```

throws this error:
```
Error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

If you are using SQL keywords as table column names, you can enable identifier quoting for your database connection in config/app.php.

SQL Query:

SELECT (COUNT(*)) AS `count` FROM users Users WHERE Users.id = :c0
```

The error is triggered when calling the count() method after the all() method in a query with parameters in the select field list.

Calling the paginate() controller method triggers the same error since these same methods are called inside of it.

**Comment by markstory** [comment]
Seems to be very similar to #7148, but this time with expression objects in the select clause.

**Comment by lorenzo** [comment]
It is the same as #7148, closing as duplicate

**Comment by berarma** [comment]
After reading that ticket it seemed like the same error but in a different situation. There are no subqueries/matchings here.

**Comment by markstory** [comment]
@berarma I'm hoping to look at this and that issue later this week. I think they are both require expanding the 'is complex' scope more.
