### ISSUE TITLE
2.x form field tampering protection issue

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7274]
In a 2.x app I was doing this (below) and SecurityComponent was blocking those post requests.

I could for some time not figure out why it would block. Then I removed bits by bits until I removed Address.street and it worked. Then I took a precise look and saw that I had defined that as hidden up before.

Browsers so take the last definition and that will get taken into the form data (post, get)
SecurityComponent should in this case behave the same.

This behavior is "probably" in cake 2.x for ages. If there is no will to fix it in 2.x:
- It should be checked and/or fixed in 3.x.
- I can supply a note to the 2.x documents making sure that IN CASE you read the docs you might get to the issue without hunting through the form tampering protection code.

```php
<?=$this->Form->create(false)?>
<!-- lots of code and bootstrap soup here *sigh * -->
<?=$this->Form->hidden('Address.street') ?> <!-- first input form, same name attribute -->
<!-- lots of code and bootstrap soup here *sigh * -->
<?=$this->Form->input('Address.street', array( /* second input form, same name attribute */
    'type' => 'select',
    'options' => array(
        $corrected_street =>  $corrected_street . ' ' . $this->request->data['Address']['street_number'] . ' [Autokorrektur]',
        $this->request->data['Address']['street'] => $this->request->data['Address']['street'] . ' ' . $this->request->data['Address']['street_number'] . ' [Ihre Eingabe]',
    ),
    'selected' => $corrected_street,
))?>
<!-- lots of code and bootstrap soup here *sigh * -->
<?=$this->Form->submit('Submit')?>
<?=$this->Form->end()?>
```

**Comment by markstory** [comment]
You were effectively 'tampering' with the form at time of generation. :smile: In this situation would you expect that the hidden field value is removed and `Address.street` be treated like a normal input value?

**Comment by jhli** [comment]
I'd expect only the last formhelper definition of a data field (same html name= attribute) to go into the tampering check mimicking browser behavior, instead of the first on.

So yes to your question.

**Comment by markstory** [comment]
I think right now both fields are tracked.  Keeping only the last field should be doable though.

**Comment by jhli** [comment]
If both fields are tracked, why do I see security component errors?

**Comment by markstory** [comment]
Because the field that was submitted does not match the hidden field value. SecurityComponent hashes include the value of every hidden input in a secured form.

**Comment by jhli** [comment]
Makes sense.

**Comment by jhli** [comment]
If you want me to add infos to the docs for 2.x and/or 3.x , tell me.
