### ISSUE TITLE
Windows: File utility reads wrong files

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#7275]
Both 2.x and 3.x.

On *nix:
```php
var_dump( (new File('/path/to/foo.txt'))->exists() );
//true
var_dump( (new File('file:///path/to/foo.txt'))->exists() );
//true
```

On Windows:
```php
var_dump( (new File('\path\to\foo.txt'))->exists() );
//true

var_dump( (new File('/path/to/foo.txt'))->exists() );
//false, as reading \\path\to\foo.txt

var_dump( (new File('file:///path/to/foo.txt'))->exists() );
//false, as reading \file:\\\path\to\foo.txt
```

`file_exists()` would return `true` against every notation but `File::exists()`.
Especially, `\\path\to\foo.txt` means `FOO.TXT` in the shared folder `TO` on the remote computer `PATH`. That is a totally wrong file.

**Comment by dereuromark** [comment]
@chinpei215 Do you have an idea for a fix?

**Comment by chinpei215** [comment]
@dereuromark I think that fixsing substr checks in `Folder::isAbsolute()` and `Folder::isWindowsPath()` will give us the correct result in the case of a leading backslash.
```php
//Before
substr($path, 0, 2) === '\\\\'

//After
$path[0] === '\\'
```

In the case of `scheme://...` syntax, it may be a bit complex fix.
```php
public function realpath($path)
{
    // Remove all `schema://...` parts here.
    // `compress.zlib://file://localhost/path/to/file` should be `/path/to/file`.
    
    $path = str_replace('/', DIRECTORY_SEPARATOR, trim($path));
    if (strpos($path, '..') === false) {
        if (!Folder::isAbsolute($path)) {
            $path = Folder::addPathElement($this->path, $path);
        }

        // Restore all `schema://...` parts here.
        // `\path\to\file` should be `compress.zlib://file://localhost/path\to\file`.

        return $path;
    }

    ...

    // Restore all `schema://...` parts here.
    // `\path\to\file` should be `compress.zlib://file://localhost/path\to\file`.
    
    return Folder::slashTerm($newpath);
}
```
But sorry, I have no time to contribute :sob:

**Comment by markstory** [comment]
I've fixed `file://` not working. I don't think its reasonable to change how `//` paths work on windows as that prefix already means something specific on windows.

Closing as there is a pull request up to correct the parts I think we can correct.
