### ISSUE TITLE
3.1 - Mailer issues

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#7278]
There are couple of issues with the new mailer class which need to be addressed:

1. **Using `$this->foo` vs `$this->_email->foo()` :**
While the mailer has access to `Email` instance and the manual shows examples setting various config using the `$this->_email` config instance, doing so can create problems. For e.g. currently if you set template using `$this->_email->viewBuilder()->template()` it get overridden by value of `$this->template`.

2. **Configuring the mailer using `$this->foo` in a method can cause the config to spill over to another method**:
While the `Email` instance is reset after sending mail in `Mailer::send()` mailer properties are not. So for e.g. when calling 2 mailer methods one after another other `$this->layout` set in 1st method call will get used by second method too. This is not desirable.

So we need to rethink how mailer config should be handled.

**Comment by jadb** [comment]
Hmm, interesting. 

What do you suggest: getting rid of mailer config properties or maybe resetting them to defaults of mailer class after method is done?

**Comment by markstory** [comment]
I don't think there will be an easy way to reset object state on send. Perhaps we should recommend people not use those properties or remove them entirely?

**Comment by ADmad** [comment]
Keeping the mailer properties means there would still be the ambiguity about which one takes precedence: Using property/method of `Mailer` or directly that of `Email` and issue no. 1 stands. 

So I guess it would be best not have any properties/methods on the `Mailer` class itself but instead either proxy them to `Email` or directly use `$this->_email`.

**Comment by markstory** [comment]
Could we use __get()/__set() for the 'nice' interface without the duplication of data?

**Comment by jadb** [comment]
I like the __get()/__set() option - want me to give it a try?

**Comment by ADmad** [comment]
@jadb Please do :)

Another improvement I would suggest is storing the state of `Email` instance in `Mailer` constructor and restoring it at the end of `Mailer::send()` instead of call `Email::reset()`. This will help preserve the default config that is now set when Email instance is created (ref #7279). `Email`'s serialization feature can be used to backup and restore it's state.

**Comment by ADmad** [comment]
Sorry @jadb, I wanted to get this fixed before 3.1 RC and wasn't sure if you would have time to take care of it before that. So took care of it myself :)

**Comment by jadb** [comment]
haha @ADmad! by my guest! :stuck_out_tongue_winking_eye:

**Comment by markstory** [comment]
Closing as #7311 is open.
