### ISSUE TITLE
Cakephp returns 404 Not Found in a PDF File

### ISSUE THREAD

**Issue by tiago-gomes** [cakephp/cakephp#7280]
Cakephp returns 404 Not Found in a PDF File, even if the file exists and is sent on the body.
Firefox and Safari serves the file but not chrome.

**Comment by markstory** [comment]
Is this for the documentation?

**Comment by bcrowe** [comment]
@markstory Looks like this is supposed to be connected to https://github.com/FriendsOfCake/CakePdf/issues/120.

**Comment by markstory** [comment]
Well we don't need a dupe if its tracked there.
