### ISSUE TITLE
New flash component causes Undefined variable: key

### ISSUE THREAD

**Issue by sgunnersen-pixelcube** [cakephp/cakephp#7281]
On a base install of cake 2.7.2, following the simple authentication tutorial implements form based authentication which in turn causes an error when not logged in and attempting to access a secured URL:

    Notice (8): Undefined variable: key [CORE/Cake/View/Elements/Flash/default.ctp, line 1]Message" class="message">You are not authorized to access that location.

On investigation it seems that AuthComponent::flash() now uses the code `$this->Flash->set($message, $this->flash);` (where previously it used `$this->Session->flash`). In turn, FlashComponent::set() has the line of code `$options['element'] = 'Flash/' . $element`, which means $options['element'] is now set to 'Flash/default'.

This would be fine, except that SessionHelper::flash() has the line of code `$flash['element'] === 'default'` (which doesn't match 'Flash/default'), and therefore a different block of code runs than normal and results in the error above.

This appears to be a problem with any usage of `$this->Flash->set()`, for example if in a random Controller I add `public $components = array('Flash');` and `$this->Flash->set('test')` I get a similar notice:

    Notice (8): Undefined variable: key [CORE/Cake/View/Elements/Flash/default.ctp, line 1]Message" class="message">Test

It appears other people have come across this problem (http://stackoverflow.com/questions/32041587/how-to-define-flashhelper-component-element-for-general-autherror-message) where the recommended solution it to have a custom flash element that doesn't use $key, but this doesn't address the underlying problem with the default code base.

**Comment by markstory** [comment]
You should either set a key, or modify the template if you don't want to use a key. I'll look into making the core uses of FlashComponent not trigger the notice error with the default templates.

**Comment by markstory** [comment]
I wasn't able to reproduce the issues with AuthComponent or flash messages in general with 2.7.x-HEAD. I can do a release for 2.7.3 this weekend and see if that resolves the issue.

**Comment by GuimaJF** [comment]
I'm having the same problem. When i reproduce the tutorial with the 2.7.3 version got this message:

Notice (8): Undefined variable: key [CORE\Cake\View\Elements\Flash\default.ctp, line 7]Message" class="message">You are not authorized to access that location.

In this test i was trying access non authorized page...

**Comment by JaviSabalete** [comment]
Same problem here

**Comment by markstory** [comment]
#7365 is probably related to this.
