### ISSUE TITLE
Auth error message when accessing an unauthorized page since 3.0.12

### ISSUE THREAD

**Issue by cake17** [cakephp/cakephp#7284]
after #7239, I get this error message `Warning (2): Illegal string offset '_base' [CORE/src/Controller/Component/AuthComponent.php, line 409]`.

This happens since CakePHP 3.0.12, when a user tries to reach an unauthorized page.

My config for Auth is as follow:

    $this->loadComponent('Auth', [
            'loginRedirect' => '/',
           ....
    ]);

Seems that it's not possible to redirect to '/' ? Passing an array makes it work but I'd rather keep '/' for my `loginRedirect` option. (For not having to rewrite tests...)

**Comment by markstory** [comment]
Pull request open now.

**Comment by cake17** [comment]
Thanks !
