### ISSUE TITLE
CakePHP console is broken in 2.7.1 and 2.7.2

### ISSUE THREAD

**Issue by HowardBraham** [cakephp/cakephp#7286]
In CakePHP versions 2.7.1 and 2.7.2, the console is broken.

In 2.7.1, running it produces this error:

    PHP Parse error:  syntax error, unexpected T_STATIC in cakephp/lib/Cake/Utility/Hash.php on line 766

In 2.7.2, we get this error:

    PHP Parse error:  syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in cakephp/lib/Cake/Core/App.php on line 221

In 2.7.0, everything works.

**Comment by lorenzo** [comment]
CakePHP 2.7 require at least PHP 5.3, give that there is no more support for PHP 5.2 from upstream

**Comment by nodejquery11** [comment]
Hi, 
Am also getting the above issue and my requirement is application must be run into PHP 5. Will it possible to rectified the above issue with the same .
Thanks

**Comment by markstory** [comment]
@nodejquery11 we longer support <5.3 you will need to upgrade php or downgrade cake.

**Comment by dereuromark** [comment]
"no" longer support :) but yeah.
