### ISSUE TITLE
  FormHelper generates wrong Sercurity hash for urls with '[' and ']' characters

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#7287]
This issue is very similar to #3634

Here is dump of $hashParts[0] array from FormHelper:
````
'/en/international_proxy/custom?currency=PLN&georegion[98]=2'
````
Here is dump of $hashParts[0] array from SecurityComponent:
````
'/en/international_proxy/custom?currency=PLN&georegion%5B98%5D=2'
````

Tested on CakePHP 2.7.2

**Comment by markstory** [comment]
I was not able to reproduce this issue on current 2.7 HEAD (0dbabce792cf3ff04f68a5ecadefb7659113f5e3). Could you try upgrading to 2.7.3?

I used the following Form->create() call:

```php
<?php echo $this->Form->create('Task', [
	'url' => ['?' => ['testing' => 'test', 'georegion' => [2, 21]]]
]); ?>
```

Which created the following URL:

```
<form action="/tasks/add?testing=test&amp;georegion%5B0%5D=2&amp;georegion%5B1%5D=21"
```

**Comment by Asgraf** [comment]
This bug report can be deleted.
this was problem with my CustomFormHelper that was extending orginal FormHelper
