### ISSUE TITLE
3.x: __debugInfo() should not cause any fatal errors

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#7290]
I am using 3.0.12 with PHP5.6. And I am using [Vdebug](https://github.com/joonty/vdebug) (Xdebug client for Vim) for debugging.
When I am debugging with Vdebug, I get a fatal error caused by __debugInfo() sometime.
For example, when a thread execution suspends in the constructor of `Cake\ORM\Table`, 
```php
   122 class Table implements RepositoryInterface, EventListenerInterface, EventDispatcherInterface
   123 {
   ...
   242     public function __construct(array $config = [])
   243     {
B> 244         if (!empty($config['registryAlias'])) {
   245             $this->registryAlias($config['registryAlias']);
   246         }
   ...     
   283         $this->_associations = $associations ?: new AssociationCollection();
   284     
   285         $this->initialize($config);
   286         $this->_eventManager->on($this);
   287         $this->dispatchEvent('Model.initialize');
   288     }
```
Vdebug shows me the context variables by using [Xdebug's context_get commmand](http://xdebug.org/docs-dbgp.php#context-get). Then Xdebug seems to execute `var_dump()` internally. Therefore `Cake\ORM\Table::__debugInfo()` will be called, and the method calls `$this->_associations->keys()` at [line 2198](https://github.com/cakephp/cakephp/blob/9d98905e2e547a161d4d59ae1d9fe7444b7a1015/src/ORM/Table.php#L2198), but `$this->_associations` is not initialized yet in this case. As a result, I get a fatal error and Vdebug crashes.
```
Error: [Cake\Error\FatalErrorException] Call to a member function keys() on null
```
As far as I know, `Cake\ORM\Query` causes a similar issue.
I am happy if `__debugInfo()`s cause no fatal errors.

**Comment by lorenzo** [comment]
Do you want to contribute a fix for this?

**Comment by chinpei215** [comment]
Yes, I want :)

**Comment by markstory** [comment]
Pull request up now.
