### ISSUE TITLE
Virtual fields in select box

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#7293]
Is it still possible to use the virtual fields in a select box like in Cake 2?

**Comment by markstory** [comment]
Only if those fields can be expressed in SQL. You can put expression objects into the `valueField` option in find('list').

**Comment by urionlinejudge** [comment]
I am not sure if I understand... I am migrating my app and on Cake 2 I used a virtual field to represent a foreing key like name + lastname and its value is customer_id. Could you please provide an example of how to do this in Cake 3?

**Comment by markstory** [comment]
```
$func = new Cake\Database\FunctionsBuilder;
$query = $this->Articles->find('list', [
  'valueField' => $func->concat(['first_name' => 'literal', 'last_name' => 'literal'])
]);
```

See [find(list)](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#finding-key-value-pairs) docs and [function builder](http://book.cakephp.org/3.0/en/orm/query-builder.html#using-sql-functions) docs.

**Comment by jhli** [comment]
'Virtual' entity field might work too I guess.
