### ISSUE TITLE
belongsToMany associations not working with paginate

### ISSUE THREAD

**Issue by surjit** [cakephp/cakephp#7295]
belongsToMany associations not working with paginate, but it works when i do 

```
$this->Businesses->get()
    $this->paginate = [
			'contain' => ['Cities', 'Categories' ]
		];
		foreach( $this->paginate( $this->Businesses ) as $bus ) {
			pr( $bus );
		}
```

this one working, above not working

```
		$business = $this->Businesses->get( $id, [
				'contain' => ['Cities', 'Categories' ]
		] );

		pr( $business );
```

**Comment by markstory** [comment]
What isn't working? Are you not getting the correct results? Are no results being loaded?

**Comment by surjit** [comment]
......
[categories] => Array
        (
        )
.........

this getting on paginate

**Comment by surjit** [comment]
it should do as 
 $business = $this->Businesses->get( $id, [
                'contain' => ['Cities', 'Categories' ]
        ] );

        pr( $business );
[categories] => Array
        (
            [0] => Dummy\Model\Entity\Category Object
                (
                    [id] => 2276
                    [parent_id] => 2212
                    [category_slug] => protective-coatings
                    [category_name] => Protective Coatings
                    [lft] => 4449
                    [rght] => 4450
                    [level] => 2
                    [_joinData] => Cake\ORM\Entity Object
                        (
                            [category_id] => 2276
                            [business_id] => 1
                            [[new]] => 
                            [[accessible]] => Array
                                (
                                    [*] => 1
                                )

                            [[dirty]] => Array
                                (
                                )

                            [[original]] => Array
                                (
                                )

                            [[virtual]] => Array
                                (
                                )

                            [[errors]] => Array
                                (
                                )

                            [[repository]] => BusinessesCategories
                        )

                    [[new]] => 
                    [[accessible]] => Array
                        (
                            [*] => 1
                        )

                    [[dirty]] => Array
                        (
                        )

                    [[original]] => Array
                        (
                        )

                    [[virtual]] => Array
                        (
                        )

                    [[errors]] => Array
                        (
                        )

                    [[repository]] => Dummy.Categories
                )

        )

**Comment by lorenzo** [comment]
What are the queries generated for the pagination request?

**Comment by surjit** [comment]
SELECT 
      Businesses.id AS `Businesses__id`, 
      Businesses.city_id AS `Businesses__city_id`, 
      Businesses.postal_id AS `Businesses__postal_id`, 
      Businesses.slug AS `Businesses__slug`, 
      Businesses.business_name AS `Businesses__business_name`, 
      Businesses.category AS `Businesses__category`, 
      Businesses.categories_json AS `Businesses__categories_json`, 
      Businesses.reviewList AS `Businesses__reviewList`, 
      Businesses.images AS `Businesses__images`, 
      Businesses.opening_hours AS `Businesses__opening_hours`, 
      Businesses.logo AS `Businesses__logo`, 
      Businesses.street_address AS `Businesses__street_address`, 
      Businesses.address_locality AS `Businesses__address_locality`, 
      Businesses.address_region AS `Businesses__address_region`, 
      Businesses.postal_code AS `Businesses__postal_code`, 
      Businesses.latitude AS `Businesses__latitude`, 
      Businesses.longitude AS `Businesses__longitude`, 
      Businesses.description AS `Businesses__description`, 
      Businesses.phone AS `Businesses__phone`, 
      Businesses.website AS `Businesses__website`, 
      Businesses.canonicalUrl AS `Businesses__canonicalUrl`, 
      Businesses.order_by AS `Businesses__order_by`, 
      Businesses.last_modified AS `Businesses__last_modified`, 
      Businesses.status AS `Businesses__status`, 
      Cities.id AS `Cities__id`, 
      Cities.city_slug AS `Cities__city_slug`, 
      Cities.city_name AS `Cities__city_name` 
    FROM 
      businesses Businesses 
      INNER JOIN cities Cities ON Cities.id = (Businesses.city_id) 
    LIMIT 
      20 OFFSET 0
	<hr>
    SELECT 
      BusinessesCategories.category_id AS `BusinessesCategories__category_id`, 
      BusinessesCategories.business_id AS `BusinessesCategories__business_id`, 
      Categories.id AS `Categories__id`, 
      Categories.parent_id AS `Categories__parent_id`, 
      Categories.category_slug AS `Categories__category_slug`, 
      Categories.category_name AS `Categories__category_name`, 
      Categories.lft AS `Categories__lft`, 
      Categories.rght AS `Categories__rght`, 
      Categories.level AS `Categories__level` 
    FROM 
      categories Categories 
      INNER JOIN businesses_categories BusinessesCategories ON Categories.id = (
        BusinessesCategories.category_id
      ) 
    WHERE 
      BusinessesCategories.business_id in (
        '21648', '21649', '21650', '46186', 
        '52016', '58012', '58013', '79251', 
        '50', '2432', '2433', '2434', '6245', 
        '6360', '9500', '13389', '13390', 
        '13391', '13392', '13393'
      )
	<hr>
    SELECT 
      (
        COUNT(*)
      ) AS `count` 
    FROM 
      businesses Businesses 
      INNER JOIN cities Cities ON Cities.id = (Businesses.city_id)

**Comment by surjit** [comment]
and result of single in foreach loop

    Dummy\Model\Entity\Business Object
    (
        [id] => 21648
        [city_id] => 1
        [postal_id] => 690601
        [slug] => skappaks-farm-supply-acadia-valley-ab-ca-21648
        [business_name] => Skappak's Farm Supply
        [category] => {"0":"Home","1":"Farm & Ranch Services","2":"Skappak's Farm Supply"}
        [categories_json] => {"Directory":["Drumheller"]}
        [reviewList] => {}
        [images] => {}
        [opening_hours] => {}
        [logo] => 
        [street_address] => 10 Railway Ave E
        [address_locality] => Acadia Valley
        [address_region] => AB
        [postal_code] => T0J 0A0
        [latitude] => 51.158213
        [longitude] => -110.20756
        [description] => 
        [phone] => ["403-972-3881"]
        [website] => []
        [order_by] => 
        [last_modified] => Cake\I18n\Time Object
            (
                [time] => 2015-03-12T00:00:00+0530
                [timezone] => Asia/Calcutta
                [fixedNowTime] => 
            )
    
        [status] => 1
        [categories] => Array
            (
            )
    
        [city] => Dummy\Model\Entity\City Object
            (
                [id] => 1
                [city_slug] => acadia-valley
                [city_name] => Acadia Valley
                [[new]] => 
                [[accessible]] => Array
                    (
                        [*] => 1
                    )
    
                [[dirty]] => Array
                    (
                    )
    
                [[original]] => Array
                    (
                    )
    
                [[virtual]] => Array
                    (
                    )
    
                [[errors]] => Array
                    (
                    )
    
                [[repository]] => Dummy.Cities
            )
    
        [[new]] => 
        [[accessible]] => Array
            (
                [*] => 1
            )
    
        [[dirty]] => Array
            (
            )
    
        [[original]] => Array
            (
            )
    
        [[virtual]] => Array
            (
            )
    
        [[errors]] => Array
            (
            )
    
        [[repository]] => Dummy.Businesses

**Comment by markstory** [comment]
If you execute those queries outside of CakePHP do you get the results you're expecting?

**Comment by surjit** [comment]
yes

**Comment by surjit** [comment]
sorry for trouble, it was my fault, issue solved

**Comment by surjit** [comment]
but I will test it another way using model load, it works that way then all good

**Comment by surjit** [comment]
now all goods finw, if i found issue again, i get track with better details
