### ISSUE TITLE
Joining 3 tables with a junction table

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#7297]
I am not sure if a solution for this is available or this would be feature request.

We have 3 tables - `items`, `locations` and `taxes`. **items_locations** and **locations_taxes** are already associated. But, there is a need to connect all of them - **items_locations_taxes**
database schema is already in place. When I baked locations model, it did something like this : 

```
$this->belongsToMany('LocationsTaxes', [
            'foreignKey' => 'location_id',
            'targetForeignKey' => 'locations_tax_id',
            'joinTable' => 'items_locations_taxes'
        ]);
        $this->belongsToMany('Items', [
            'foreignKey' => 'location_id',
            'targetForeignKey' => 'item_id',
            'joinTable' => 'items_locations'
        ]);
        $this->belongsToMany('Taxes', [
            'foreignKey' => 'location_id',
            'targetForeignKey' => 'tax_id',
            'joinTable' => 'locations_taxes'
        ]);
```

I think that is not a correct way. Now, how can these 3 be connected through join and can we make the 'Bake' capable of doing it automatically?

And, take a note that junction tables are using composite primary keys and do not contain id column.

**Comment by lorenzo** [comment]
What is the problem you are having? Please reserve questions and help requests to IRC or stackoverflow.

**Comment by gauravmak** [comment]
Okay, I will ask in stackoverflow. Thanks.

**Comment by jhli** [comment]
Create a model that makes sense (maybe local_item_taxes) that uses standard hasMany/belongsTo?

**Comment by jhli** [comment]
Related: @gauravmak, check if the book has a paragraph on when to avoid (HA)BTM, why and how. If not and if the core agrees I might add an example to the 3.x book when not to use.

**Comment by ADmad** [comment]
@jhli If you want to help him find his question on SO, this isn't a help forum.
