### ISSUE TITLE
Ability to set your own ComponentRegistry implementation for Controller objects

### ISSUE THREAD

**Issue by korotovsky** [cakephp/cakephp#7300]
After some discuss with @lorenzo we've decided to add `setController()` to the `ComponentRegistry` and make `Controller` able to accept `ComponentRegistry` as the constructor argument.

PR #7301

**Comment by lorenzo** [comment]
Closing as there is a pull request open

**Comment by jhli** [comment]
Is there any docs up for how and why to use this feature?

**Comment by korotovsky** [comment]
@jhli Actually, it's not a "complete feature". It just makes cake3 more friendly for any DependencyInjection library.
