### ISSUE TITLE
cake created form will not work inside a bootstrap modal

### ISSUE THREAD

**Issue by jtbratcher** [cakephp/cakephp#7302]
I'm running Cake 3 and Bootstrap 3.3.2.
The form generated by Cake's formhelper is not in the bootstrap modal it works just fine. As soon as I placed in the modal dialog box it refuses to do anything. It acts like it submits but nothing changes.
The modal works just like it should, so I'm not sure which is causing the problem. Any suggestions
```
 echo '<div class="modal fade" id="userphoto" tabindex="-1" role="document" aria-labelledby="userphoto">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">';
        echo $this->Form->create('Pages', array('type' => 'file'));
        echo $this->Form->input('File',array( 'type' => 'file'));
        echo $this->Form->end('Submit') . '
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="userphotosubmit">Submit</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by dereuromark** [comment]
This is not valid CakePHP 3 code, create() does not take a string. end() does not take a string.
Please use valid code before reporting bug tickets.

**Comment by jhli** [comment]
2.x did @ Strings. Suggestions:
- RTF3.0M
- IRC, Stackoverflow
- Use PHP's templating (why echos the horrofic bootstap soup?)
- Isolate issues: create a view template with form helper that works and incrementally make changes (html/dom, js/bootstrap)

**Comment by jtbratcher** [comment]
Sorry, typo. Using Cake 2.x. The code is valid and works just fine while not in the modal window.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
