### ISSUE TITLE
CakePHP 3 : multiple checkboxes (select) + js event

### ISSUE THREAD

**Issue by Marecages** [cakephp/cakephp#7306]
Hello !

I notice a gap with forms under cakePHP 3. 
I try to use a select multiple checkboxes, with any event js, like this : http://pastie.org/private/dqsqqaamlof5ivolzrfa ; but it doesn't work (it doesn't recognize the event, which doesn't appear in the source code). 
So, we tried to find an alternative ( http://pastebin.com/V6z9mbGK ) but it doesn't work too...  
I'm a bit surprised because this solution was OK with CakePHP 2 (I think?)... 
Why did it work in the previous version and not in this one ? is it a bug, an oblivion or a conscious choice?

Thanks in advance for your answer,

Reka

**Comment by lorenzo** [comment]
Please don't use the issue tracker for help requests. You may post your question in StackOverflow or IRC.
