### ISSUE TITLE
3.x RFC Elements to be inside template's named folders (more like rails partials)

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#7307]
This is just a little idea on how to improve the elements - to behave more like `partials` in Rails. Currently the

``` PHP
// src/Template/Users/index.ctp
$this->element('helpbox');
```

searches for `Template/Element/helpbox.ctp`. But what if it could search for `Template/Users/_helpbox.ctp` first? So that the view files related to `Users` model are in the same directory. The file would start with an underscore to visually separate it from other templates. If no such file is found, then the `helpbox` would be searched in `Element` folder as it is now.

Also when called from other view file (inside other model name):

``` PHP
// src/Template/Articles/view.ctp
$this->element('Users/helpbox');
```

Would search for `Template/Users/_helpbox.ctp` and then for `Template/Element/Users/helpbox.ctp`?

What do you think?

**Comment by ADmad** [comment]
We already have enough multiple paths for searching templates. I wouldn't want to add more. You can achieve what you want by overriding relevant method(s) of View class in your custom class to add additional paths.

**Comment by markstory** [comment]
I can see how looking in the current template path for elements first could be useful. Would we be checking the additional path in all of the path search locations? That would effectively double the search space for elements which might get a bit hairy.

Asking for `Users/helpbox` but having `Users/_helpbox` rendered is a bit counter-intuitve to me. It feels like yet another convention people would have to learn vs. having a more literal implementation.

**Comment by Laykou** [comment]
Ok, we can skip the underscore prefix. It is just convention from rails, but we don't have to copy everything.

And not all paths would be checked, just the current folder from where the request comes. E.g. if the element is `helpbox` is requested from any `Users/*.ctp` file the `Users/helpbox.ctp` will be checked only.

But it would support loading elemnts also from other template folders using `Article/helpbox` inside any ctp.

Hopefully you understand. The benefit is that all template files related to one domain/model should be together.

**Comment by markstory** [comment]
Are you saying there would just be one additional path? How would that work for themes or plugin overrides?

**Comment by Laykou** [comment]
I am not using them but the  basic idea is to look into Template folder and
then into Template/Element folder.

**Comment by jhli** [comment]
Or create rails' partials and leave elements to be global... But in case not :+1: local the global lookup. There is also a closed issue on rails partials.

**Comment by jhli** [comment]
https://github.com/cakephp/cakephp/issues/2574

**Comment by Laykou** [comment]
I would just again discuss this:

Because my worry is that the code that belongs together is on many different places.

Let's say I have `form.ctp` and then `add.ctp` and `edit.ctp` inside `Articles`. I would like the `form.ctp` to be partial because I want to use the same code from the other two files.

Currently the structure would be like this

```
Template
 |
 +-- Elements
 |  |
 |  +-- form.ctp
 |
 +-- User
   |  
   +-- add.ctp
   +-- edit.ctp 

// calling $this->element('form')
```

or to "namespace" the form.ctp inside Elements:

```
Template
 |
 +-- Elements
 |  |
 |  +-- Users
 |      |
 |      +-- form.ctp
 |
 +-- User
   |  
   +-- add.ctp
   +-- edit.ctp 

// calling $this->element('Users/form')
```

**But wat I would like to is this:**
```
Template
 |
 +-- User
   |  
   +-- form.ctp
   +-- add.ctp
   +-- edit.ctp 

// calling $this->element('form')
```

If you do not want to do this in cakephp framework, can you please recommend how can I adjust my project to work like this? Maybe override some CakePHP methods or something?

**Comment by ADmad** [comment]
> can you please recommend how can I adjust my project to work like this? Maybe override some CakePHP methods or something?

Extends the `View` class and override `View::_subPaths()` and/or `View::_getElementFileName()` method(s).

**Comment by Laykou** [comment]
@ADmad Thanks. How can I make Cake 3.x to use my own View class? What do I need to do in the AppController?

**Comment by ADmad** [comment]
You already have [AppView](http://book.cakephp.org/3.0/en/views.html#the-app-view) so you can override the methods there.

A better option would be add your own `partial()` method which looks for template file in the same folder using `_getViewFileName()`.

**Comment by Laykou** [comment]
Awesome, thanks, I've almost forgot the `AppView` :)

**Comment by Xety** [comment]
> E.g. if the element `helpbox` is requested from any `Users/*.ctp` file the `Users/helpbox.ctp` will be checked only.

If i understand well, your system won't work if we want to import 2 templates with the same name:
``` 
Template
 |
 +-- Elements
 |  |
 |  +-- Users
 |  |   |
 |  |    +-- helpbox.ctp
 |  |
 |  +-- helpbox.ctp
 +-- User
   |  
   +-- add.ctp
```

What happend if in my **User/add.ctp**, i want to add **Elements/helpbox.ctp** *and* **Elements/Users/helpbox.ctp** ?
Because, with your exemple, if i do `$this->element('helpbox');` it will always import the `Elements/Users/helpbox.ctp`.

**Comment by ADmad** [comment]
@Xety He probably doesn't want to use elements from `Element` at all :)  Also using a new method `partial()` like i suggested would allow both.

**Comment by Laykou** [comment]
All I wanted is to check the `Template/Users/helpbox.ctp` path first and then  `Template/Element/Users/helpbox.ctp` or `Template/Element/helpbox.ctp`. This would apply also to plugins. I didn't want to change current logic, just add one more path to be checked, so that all my views connect to `Users` model are in one folder and not two.

So the order for `$this->element('helpbox')` would be:
1. Check `element.ctp` inside `Template/ModelName` folder
2. Check `element.ctp` inside `Template/Element/ModelName` folder
3. Check `element.ctp` inside `Template/Element` folder

The step 2. and 3. is basically what happens now. I just wanted to add the step 1.

**Comment by ionas** [comment]
:+1: For partial() vs element() as ADmad suggests if there is a strive for a framework implementation.

**Comment by Xety** [comment]
@Laykou Ah yeah, I misunderstand.

Why not,  but the elements inside a `Template/ModelName` folder, should have a different name pattern, so that we can be able to detect them directly when you see the folder.

**Comment by Laykou** [comment]
Yes there was an idea of `_` prefix as it is in Rails: `Template/Users/_helpbox.ctp` then using `$this->element('helpbox')` would firstly lookup `_helpbox.ctp` inside the Users directory and then check for the standart `Elements` path.

The question is: Would you like to have this as part of `elements`, or do we need second method `$this->partial('helpbox')`?

The difference:

  1. partial - would look into the `Template/ModelName` folder
  2. element - would look into `Element` folder.

But the funcionality and everything would be the same. It is just about the file location. Therefore I do not see any benefit of having additional method `partial`. Becuase with `partials` I expect to do the same as with elements, e.g. caching or passing variables.

**Comment by Laykou** [comment]
I understand the benefit of having `Elements` folder - when different views, e.g. `Articles` and `Users` use the same `helpbox.ctp` than it is pretty reasonable that the file resides in `Element/helpbox.ctp`.

But when I have `Articles/add.ctp`, `Articles/edit.ctp`, `Articles/third.ctp` and all of them are using `form.ctp` and this `form.ctp` is not being used from other views, then I do not see a reason to put it outside of this folder. It only makes more mess in the folder structure for me. Therefore I would like to keep it together in `Articles/` folder as `Articles/form.ctp` or `Articles/_form.ctp` or whatever works for the core team.

I do not have any requirements for this but to have all files view for one Model in one folder to keep the code clean. Any other conventions are up to the core team :smile: and I just propsed some suggestions in the discussions but it is still open for any changes

**Comment by ionas** [comment]
As discussed in #2574 the point of a partial could/should be what deemed to be doable by Cake3's cells. 

I do still think that mimicking rails' behavior would be a great thing because it is easy to use, convenient and a well understood concept (see the issue for a link to the rails documentation about partials).

The basic idea implementing rails like partials would be (AFAIR) that:
* if you supply a string it would lookup a local template that behaves exactly like an element.
* If you pass an entity or a collection of entities, it would lookup the entity partial (say _user.ctp) or collection of entities partial (say _comments.ctp), again locally.

Note:
* There is a lot of discussions about that in the other ticket already that deals with how to get/point to entity/collection of entities
* There seemed to be the wish to let partials only do the entity/collection of entities rendering, keeping elements as "simple snipplets"

p.s.: I am using _form.ctp all the time for a shared for for add/edit.ctp

**Comment by Laykou** [comment]
@ionas Could you please explain where do you store your `_form.ctp` and how is it linked to `add.ctp` ? Are you using somehow modified `elements` or any workaround or do you store it in `Elements/Model/_form.ctp` ?

**Comment by ionas** [comment]
php's ```require()``` - it is fast on the server. It does not do engine based caching though (any ```HTTP GET``` based proxy like varnish should work though, the place where I'd do caching to KISS)

**Comment by ionas** [comment]
I am also on #cakephp @IRC (so if you want to discuss more without me adding to much noise to ADmad precious ears, feel invited)

**Comment by markstory** [comment]
Having a second method lets us change the path semantics without breaking compatibility. We can't really make assumptions around 'conventions' and element() as it already has conventions, and we're likely to break compatibility by layering on new conventions.

**Comment by inoas** [comment]
I would not overload `element()` anyway but let it do what it does.
If the requirement comes back to do something beyond a simple `require` then I will prep a PR for `partial()`

**Comment by dereuromark** [comment]
Then this could be plugin or app based for now.

**Comment by xavier83ar** [comment]
I was about to propose this same thing for cakephp 4, and doing a mandatory previous search on issues I end up here.

I've been doing this in all my cakephp 3 project, overriding `\App\View\AppView::_getElementFileName()` method allowing to find "local" elements.

As someone may find it usefull, this is the code I use:

```php
    protected function _getElementFileName($name, $pluginCheck = true)
    {
        $name = str_replace('/', DS, $name);
        if ($name[0] === DS) {
            $name = substr($name, 1);
        }
        $file = dirname($this->_current) . DS . $name . $this->_ext;
        if (file_exists($file)) {
            return $file;
        }

        return parent::_getElementFileName($name);
    }
```

The thing is that I was thinking on proposing it for cakephp 4. The motivation is pretty much the same that's been told.

In my projects, many times, the form part of edit and add are indetical, and to keep it DRY, I put that code on an element, the things is that those form elements are not shared elements, only have sense there, so being unable to place them in the same folder, I should create namespace folders en Element/ folder  ... and it's the situation mencioned by @Laykou. 

Facing these issue, I ended up overriding `_getElementFileName` in `AppView`, without adding any magic convention in my case, I just prepend the underscore to the element names to remind me that are local templates, but I include them the same way, the method does not nothing about it.

```php
// file src/Template/Users/_form.ctp
echo $this->element("_form");
```

That being said, I'm in favor of this feature, either way is ok for me: adding a partial method, or adding the search path to element method.

**Comment by xavier83ar** [comment]
In fact, with this feature we could encourage this behavior by doing that bake console create templates this way. Internally, bake has a partial template for the form, which uses in add and edit.

**Comment by markstory** [comment]
Having a leading `_` completely change how elements are located concerns me as it adds complexity and cognitive load when reading templates. The `partial()` method that has been proposed here adds more API surface area but makes it simpler to understand which template file would be used, and doesn't require that people prefix partials with `_`.

**Comment by xavier83ar** [comment]
Yeah @markstory, I am not in favor of any "magic" logic locating elements with a prepended `_`. 
I have named "local" templates with an initial underscore only as a convention, to remember it when I work with the template and to avoid name colitions with methods templates, but I include them the same way, including the underscore, there is no magic logic behind.

```php
// current file src/Template/Users/add.ctp
// this line would include element in src/Template/Users/_form.ctp
echo $this->element('_form');
```

That's how I'm using it right now, overriding `View::_getElementFileName()` in `AppView`. 

Finally, while either way is ok for me: adding a partial() methods or adding this feature to element() method, I'm a bit in favor of the last one, as I think that having a new method only to search elements in other folders would be a bit confusing and hard to maintain two different methods that end up doing pretty much the same.
