### ISSUE TITLE
hasOne association with different connections

### ISSUE THREAD

**Issue by pauloandreget** [cakephp/cakephp#7308]
I have the following tables:

```php
class PostsTable extends Table {
    public static function defaultConnectionName() {
        return 'default';
    }

    public function initialize(array $config) {
        $this->hasOne('Attachments');
    }
}

class AttachmentsTable extends Table {
    public static function defaultConnectionName() {
        return 'app';
    }

    public function initialize(array $config) {
        $this->belongsTo('Posts');
    }
}
```
Notice I have **two connections**, but what happens is that the query generated by finding all posts there is no reference to the second table and I get error 500.

If I set `$this->table('table2.attachments');` to *AttachmentsTable*, it works, but this does not seem right.

**Comment by lorenzo** [comment]
Add `['strategy' => 'select']` to the options of both associations. You will no be able to do joins between those tables, for obvious reasons.

**Comment by lorenzo** [comment]
`$this->table('table2.attachments');` is the right thing if you want joins between the two tables
