### ISSUE TITLE
2.* Security::Decrypt not working when setting db encoding to utf8

### ISSUE THREAD

**Issue by xhs345** [cakephp/cakephp#7309]
Setup:CakePHP 2.7.2, Apache/2.4.12 (Win32) and MySQL 5.6.25. Server charset: UTF-8 Unicode (utf8). Table collation: utf8_general_ci

After I changed my db settings from default (empty) to 'encoding' => 'utf8' I noticed that I no longer got results displayed when using the decrypt function (data was still getting encrypted). After removing the setting everything is working fine again. Thought I might report it here in case anyone else runs into the same problem..

**Comment by markstory** [comment]
I bet the blob data is being cast by MySQL into characters. You might want to consider either storing binary data in blob columns or base64 encoding if you must use TEXT columns.

Closing as there is not much CakePHP can do here.

**Comment by jhli** [comment]
Could you add a note to the book @xhs345?

**Comment by xhs345** [comment]
I can do that. As mark guessed it was my fault choosing the wrong data type for the field (VARCHAR, now using BLOB)
