### ISSUE TITLE
3.0.x Network\Http\Adapter\Stream: Proxy Settings for HTTP Stream

### ISSUE THREAD

**Issue by JustDoItSascha** [cakephp/cakephp#7313]
I've wondered about how to pass proxy information into the stream context of fopen when using Network\Http\Client()->get().

First I saw http://book.cakephp.org/3.0/en/core-libraries/httpclient.html#proxy-authentication, but it didn't do the trick. So I followed the breadcrumbs and find out, that just username and password are used to create a proxy header, but there is no information passed through the context.

The stream context is generated in Network\Http\Adapter\Stream() in _buildContext() line 119. But when I look into the three function _buildContent(), _buildHeaders() and especially in _buildOptions() there is no proxy parameter passed through $this->_contextOptions (which is used for stream_context_create() in line 131.

So shouldn't it be possible to pass the proxy parameter to stream context? For example if we add to line 213:

    if (isset($options['proxy']['proxy'])) {
        $this->_contextOptions['proxy'] = $options['proxy']['proxy'];
    }

And in the documentation the port parameter should be removed due to the fact it is used nowhere and we replace it with 'proxy' => 'proxy' parameter, which can be a string that is passed through context...

Before I create a pull request I want to hear your opinion.

Cheers,
Sascha

**Comment by markstory** [comment]
The proxy authentication should be added as headers to the request via `Cake\Network\Http\Auth\Basic::proxyAuthentication()`. Why would they also need to go into the stream context?

**Comment by JustDoItSascha** [comment]
Because it works just this way? I don't mean the authentication. Not every proxy needs a authentication. 


But when you try to fopen an external source and the Server is behind a proxy, you have to pass the proxy url to the context...

**Comment by JustDoItSascha** [comment]
To make it more clear, 


one thing are the authorization credentials for the proxy -> these stand in the header 




But the other thing is the url of the proxy itself and this belongs to the context. 




I have tested it and it worked just the way I've written in the first Post...

**Comment by markstory** [comment]
Ok. If you could open a pull request that would be great :)

**Comment by JustDoItSascha** [comment]
Pull request with testing is opened, https://github.com/cakephp/cakephp/pull/7326

**Comment by markstory** [comment]
Thanks.
