### ISSUE TITLE
Restfull XML problem

### ISSUE THREAD

**Issue by ironbone** [cakephp/cakephp#7319]
Following the instruction in:
http://book.cakephp.org/3.0/en/development/rest.html
I created the simplest application. Without creating the templates. I just wanted to use/get the serializable variables.
It works well when I send the 
Accept: application/json
header. I get the json version of the serializable variable.
Unfortunately when sending
Accept: application/xml
or 
Accept: application/xml, text/xml
I get just the html page not the xml version of the serializable variable what I expected.
The returned type is just text/html

**Comment by markstory** [comment]
Is there any additional detail on what your routes, or controller, or request data look like? In testing locally XML request payloads worked fine, are you having issues with the rendered responses?

**Comment by markstory** [comment]
I took at look at the default code that comes out of cakephp/app. The reason JSON works and XML doesn't is that the JSON extension is not enabled by default. DebugKit enables the JSON extension in debug mode. To ensure both types are always enabled you should add the following to your routes.

```php
Router::scope('/', function ($routes) {
    $routes->extensions(['xml', 'json']);
    // Other routes.
});
```
