### ISSUE TITLE
Basic authentication will not use api key

### ISSUE THREAD

**Issue by dystopiavirus** [cakephp/cakephp#7321]
Attempted using Basic authentication numerous times, and CakePHP Auth just ignores the change in field and keeps returning false, 

current config:
   ` $this->loadComponent( 'Auth' , [`
    `            'authenticate' => [`
     `              'Basic' => [`
      `                'fields' => ['password' => 'api_key' ],`
       `               'scope' => ['enabled' => 1]`
        `           ]`
         `       ]`
         ` ] );`

MySQL query generated makes no reference to the api_key field and CakePHP keeps returning Unauthorized, can anyone help with this or update BasicAuthenticate to allow it?

**Comment by markstory** [comment]
You also need to map the username field.  The [documentation](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#using-basic-authentication) has a working example.

**Comment by ADmad** [comment]
> MySQL query generated makes no reference to the api_key field

That's expected as the password check is done in PHP not through query conditions.

Also by default Auth expects the password to be blowfish hashed, is the value in your `api_key` field a blowfish hash?  If not configure appropriate password hasher.

**Comment by dystopiavirus** [comment]
Tried mapping the username field and no change and there is no reference in any documentation about hashing the api key, is this required?

**Comment by ADmad** [comment]
[Hashing passwords](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#hashing-passwords)

**Comment by dystopiavirus** [comment]
There still doesn't seem to be any reference to hashing the API key, this is hashing a password, which I have already done.

**Comment by markstory** [comment]
Generally basic authentication uses an ascii based hash, which [has a section in the docs](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#creating-api-keys-for-basic-authentication).
