### ISSUE TITLE
Always not authorized when use session with database engine

### ISSUE THREAD

**Issue by adiramardiani** [cakephp/cakephp#7325]
I following all tutorial in documentation, all function is fine and working well, but when I use database as session engine, create table and change session engine. I cannot access page, give message not authorized. If my username and password wrong give message username or password incorrect, but when all username and password valid, give message not authorized

**Comment by ADmad** [comment]
>  but when all username and password valid, give message not authorized

It means authentication works fine but the user is not authorized of access the action. Check your authorization config.

**Comment by adiramardiani** [comment]
All config is same and following tutorial, if change session engine with `php` again, everting work fine again
