### ISSUE TITLE
Some core methods currently don't account for string zero value `'0'` input.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7329]
After https://github.com/cakephp/cakephp/issues/7328#issuecomment-136407682 it seems that several core methods would false positive !empty() and thus return `false` where they should actually return `true`:

- Cache::writeMany(): `if ($success === false && !empty($data[$key])) {`
You can't store `'0'`

- ConsoleInput::read(): `if (!empty($line)) {`
You can't read `'0'`

- ConsoleInputOption::usage(): `if (!empty($this->_default)`
You can't default to `'0'`

There might be more.
They should use a "more sane" not-empty check.

**Comment by markstory** [comment]
Fixed with #7331
