### ISSUE TITLE
Big issue in recover for tree

### ISSUE THREAD

**Issue by cyberbobjr** [cakephp/cakephp#7330]
for CakePHP v2.7.3 (and 2.7.1 too).

I have a table which start with id = 4454
The model have the tree behavior.
If i want to recover my lft/rght value, the lft/rght field is miscalculated (see screenshot below).
<img width="1528" alt="capture d ecran 2015-08-31 a 18 33 42" src="https://cloud.githubusercontent.com/assets/607648/9584026/f96a3ed6-500e-11e5-919f-c936c7aa5002.png">

This is an extract of my table (i put 0 in lft/rght field for you to test)
--
-- Table structure for table `stocks`
--

CREATE TABLE `stocks` (
  `id` int(11) NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `level` int(11) NOT NULL,
  `transport_id` int(11) DEFAULT NULL,
  `inventaire_id` int(11) DEFAULT NULL,
  `materiel_id` int(11) NOT NULL,
  `article_id` int(11) NOT NULL,
  `localisation_id` int(11) NOT NULL,
  `entree` int(11) NOT NULL DEFAULT '0',
  `sortie` int(11) NOT NULL DEFAULT '0',
  `date` date NOT NULL,
  `incomplet` tinyint(1) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4938 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `stocks`
--

INSERT INTO `stocks` (`id`, `parent_id`, `lft`, `rght`, `name`, `level`, `transport_id`, `inventaire_id`, `materiel_id`, `article_id`, `localisation_id`, `entree`, `sortie`, `date`, `incomplet`, `created`, `modified`) VALUES
(4454, NULL, 0, 0, NULL, 0, NULL, 90, 16005, 1278, 75, 1, 0, '2015-08-31', 0, '2015-08-30 22:37:52', '2015-08-30 22:37:52'),
(4455, 4454, 0, 0, NULL, 1, NULL, 90, 16006, 1279, 75, 10, 0, '2015-08-31', 0, '2015-08-30 22:37:52', '2015-08-30 22:37:52'),
(4456, NULL, 0, 0, NULL, 0, NULL, 90, 16007, 1278, 75, 1, 0, '2015-08-31', 0, '2015-08-30 22:37:52', '2015-08-30 22:37:52'),
(4457, 4456, 0, 0, NULL, 1, NULL, 90, 16008, 1279, 75, 10, 0, '2015-08-31', 0, '2015-08-30 22:37:52', '2015-08-30 22:37:52'),
(4458, NULL, 0, 0, NULL, 0, NULL, NULL, 16005, 1278, 75, 1, 0, '2015-08-31', 0, '2015-08-30 22:37:52', '2015-08-30 23:26:27'),
(4459, NULL, 0, 0, NULL, 0, NULL, NULL, 33, 18, 20, 1, 0, '2015-08-30', 0, '2015-08-30 22:43:09', '2015-08-30 22:43:09'),
(4460, 4459, 0, 0, NULL, 1, NULL, NULL, 34, 19, 20, 1, 0, '2015-08-30', 0, '2015-08-30 22:43:09', '2015-08-30 22:43:09'),
(4461, 4460, 0, 0, NULL, 2, NULL, NULL, 35, 20, 20, 4, 0, '2015-08-30', 0, '2015-08-30 22:43:09', '2015-08-30 22:43:09'),
(4462, 4460, 0, 0, NULL, 2, NULL, NULL, 36, 21, 20, 1, 0, '2015-08-30', 0, '2015-08-30 22:43:09', '2015-08-30 22:43:09'),
(4463, 4460, 0, 0, NULL, 2, NULL, NULL, 37, 22, 20, 1, 0, '2015-08-30', 0, '2015-08-30 22:43:09', '2015-08-30 22:43:09');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `stocks`
--
ALTER TABLE `stocks`
  ADD PRIMARY KEY (`id`),
  ADD KEY `localisation_id` (`localisation_id`),
  ADD KEY `parent_id` (`parent_id`),
  ADD KEY `lft` (`lft`),
  ADD KEY `rght` (`rght`),
  ADD KEY `materiel_id` (`materiel_id`),
  ADD KEY `article_id` (`article_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `stocks`
--
ALTER TABLE `stocks`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4938;

**Comment by dereuromark** [comment]
You need to set up your table as documented, lft/right need to be default null for example.

**Comment by cyberbobjr** [comment]
Ouch, sorry, i've made a big mistake :(
I always think that lft/rght was for indexing to id index.... shame on me, really sorry :(

**Comment by AD7six** [comment]
Please state the problem also - looking at your screenshot the only thing wrong is that two records (4459, 4460) have wrong rght field values, consistent with 2 rows with parent id 4460 having been deleted without using the tree behavior.
