### ISSUE TITLE
cakePHP 3.0 - Why can't an input field be both required and disabled? 

### ISSUE THREAD

**Issue by glkaup** [cakephp/cakephp#7333]
I've an add action that fills in some of the fields before the user sees the input form.  These fields have validators with ->requirePresesnce() so I should expect them to always be in the submitted data of the form.

But, I don't want to allow the user to change these fields, so I have specified  'disabled' = 'disabled' for each of the fields in the template view.

The user sees exactly what I want them to see...  A field, with its value, but they cannot change its value.  But... The data "submitted" does not contain these fields.

I can use hidden and they will be returned... but user does not get any info shown.  Of course the view could display the hidden fields without the "input" boxes, but I don't understand why I should have to?

I believe this used to work in 2.6.7, since I am converting that code to 3.0

Thanks in advance for any assistance, or even if this is "just the way it is"...

**Comment by dereuromark** [comment]
I think you are confusing "readonly" and "disabled". The latter makes the form input completely being ignored by the browser when sending.
So this is not a CakePHP issue, but normal behavior to be expected by all browsers as per HTML specs afaik.

**Comment by glkaup** [comment]
Thank you... readonly solves most of my question...  It does not work on <select> statements though... funny that... it would seem that a select field could be readonly until some other checkbox had been set.  But I guess this will work. 

Thank you
