### ISSUE TITLE
Time timezone conversion wrapping from September 1 to September 30

### ISSUE THREAD

**Issue by Jozomby** [cakephp/cakephp#7335]
Disclaimer - I'ver never submitted an issue here before, so I'm not certain what's required, but I thought I'd post this just in case no one's aware of it.  I found a work-around so it's not urgent.

I'm using CakePHP 3.0.12.  I create a new Time object, with the following parameters: (year doesn't matter), month->9, day->1, hour->5, minute->59, second->59, timezone->America/Denver.

When I display the time, it appears -6 hours, like it should, but instead of wrapping back to August 31, it wraps to September 30.  The timezone conversion appears to work correctly for other months; if I set month->8 then it displays July 31.  My temporary workaround has been to set month->8 and day->32.

**Comment by markstory** [comment]
How are you wrapping the datetime backwards?

**Comment by Jozomby** [comment]
The server and CakePHP and everything are all set to UTC time, so I just create my `Time()` object, set the object's timezone to `America/Denver`, then display it with `i18nFormat(\IntlDateFormatter::FULL)`.  At that point it displays the datetime converted into `America/Denver` time, which in this case wraps it backwards across the month boundary.

**Comment by markstory** [comment]
Ok. so what does that code look like? Basically I don't know enough about the problem you're having to reproduce it.

**Comment by Jozomby** [comment]
In a template:
```
$august = new Time();
		$august->year($info['created']->year+1)
				->month(8)
				->day(32)
				->hour(5)
				->minute(59)
				->second(59)
				->timezone('America/Denver');
		?>
		<p>The final report for your project entitled <?= $info['title'] ?> is due <?= $august->i18nFormat(\IntlDateFormatter::FULL) ?></p>
```

**Comment by markstory** [comment]
What timezone does the time object start off in? Depending on the origin timezone/time going back across the date boundary is perfectly normal as the original timestamp could be in a different calendar day in different timezones.

**Comment by Jozomby** [comment]
I'm sorry for being unclear with my question.  The original timezone is UTC, and as you can see in the provided code, I'm setting it to Mountain Time.  At the end of August and beginning of September, there is a 6 hour difference between UTC time and Mountain Time, so September 1 5:59:59 UTC should convert to August 31 11:59:59 Mountain Time.  The problem is that it is instead converting to September 30 11:59:59 Mountain Time.  I'm not sure how adding an entire month during timezone conversion qualifies as normal behavior.

Just to be clear, the expected output from the above code is:
`The final report for your project entitled TEST is due Monday, August 31, 2015 at 11:59:59 PM Mountain Daylight Time`
Instead, it's displaying:
`The final report for your project entitled TEST is due Wednesday, September 30, 2015 at 11:59:59 PM Mountain Daylight Time`

This behavior does not repeat with other months; August 1 5:59:59 UTC converts correctly to July 31 11:59:59 Mountain Time.

**Comment by lorenzo** [comment]
I just tried this, but could not reproduce the problem:

![screen shot 2015-09-02 at 09 37 34](https://cloud.githubusercontent.com/assets/37621/9625428/4d61ce12-5156-11e5-8ba7-2db201dca05b.png)

**Comment by rchavik** [comment]
Try updating your timezonedb. When I was doing abbr for  Time::listTimezones(), I had some problems due to outdated timezone database in php 5.3.

**Comment by dereuromark** [comment]
@Jozomby Also try to always provide version numbers regarding your PHP in use as well as any other library involved. Otherwise it is almost impossible to reproduce.

**Comment by Jozomby** [comment]
It's good to hear that it might just be an issue with timezone configuration on my end.  Thank you for all the help and patience!  I'm sorry to have bothered you with this.  Just for reference, I'm running PHP 5.6.12.
