### ISSUE TITLE
Issue in list record

### ISSUE THREAD

**Issue by dipeshcct** [cakephp/cakephp#7338]
Hello,

I want to find list record with particular column "id" and "name". 
I try to find using below query 
$this->Users->find('list')->select(['id', 'name']);
but it return only "id" for both key and value
Array
(
    [1] => 1
    [13] => 13
    [14] => 14   
).
So is there any problem in my query?

**Comment by antograssiot** [comment]
As stated in the [doc](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#finding-key-value-pairs) you should use 
```
$query = $articles->find('list', [
    'keyField' => 'id',
    'valueField' => 'name'
]);
```

please use SO or IRC for such questions.

**Comment by dipeshcct** [comment]
Thank you for your valuable time. It is working now.
