### ISSUE TITLE
Problem in migrations

### ISSUE THREAD

**Issue by edsonmgoz** [cakephp/cakephp#7340]
I'm using CakePHP 3.0.12. I'm creating migration as always but this time I run bin/cake migrations migrate and generates the following exception: [InvalidArgumentException] The "date" option does not exist - and does not create migration.. I did not pass this with previous versions, please let me know that it may be happening. 
Thank you.

**Comment by antograssiot** [comment]
closing as duplicate of https://github.com/cakephp/migrations/issues/117 and will be solved in https://github.com/cakephp/migrations/pull/118
