### ISSUE TITLE
Migrations date options problem

### ISSUE THREAD

**Issue by lottietoday** [cakephp/cakephp#7341]
Migrations stopped working today (dont know if its global problem or only in our project)

all migrations returning this error

```bash
 [InvalidArgumentException]
 The "date" option does not exist.
```

from yesterday (it was all ok) project was not changed... only thing was composer update.

Clean install (empty project) returning same error

**Comment by ADmad** [comment]
Wrong repo. Issue has already been reported on the cakephp/migrations repo.
