### ISSUE TITLE
3.0.x on Ajax POST request the "initialize" method in AppView Class is not triggered (or the whole class not loaded)

### ISSUE THREAD

**Issue by carloamoroso** [cakephp/cakephp#7344]
Hi everyone.
This is my first ticket. So be kind if I'm wrong :-)

I did multiple tests and I have always the same issues. 

The version I'm using is 3.0.12.

I customized Form errors templates this way:

```php
***********in View/AppView.php *****************
    public function initialize()
    {   
        $this->loadHelper('Time');
        $this->loadHelper('Form', [
            'templates' => 'app_form'
        ]);
    }

************in config/app_form.php**********
<?php 
return [
    'error' => '....custom_formatting...{{content}}.../custom_formatting....,
];
```

This configuration works flawlessly with standard "POST" request, so I see form errors with my custom template.

When calling an "Ajax POST" request (i.e. with jquery) the "initialize()" method in View/AppView.php is bypassed someway, so the html code I get back haven't the custom error formatting (if there is some error). I just get the standard error formatting.

So, using something like this:

```javascript
$.ajax({
  method: "POST",
  url: "...the same url used with standard POST...",
  data: { ....the same data of the standard POST....}
})
.done(function( msg ) {
  console.log(msg)
});
```

gives back what I expect but the custom error template.

When using the ajax call I also put random raw syntax errors in AppView.php and they are not triggerd at all.

**Comment by antograssiot** [comment]
does your AjaxView class extends your AppView and do you call the parent::initialize() in it ?

**Comment by carloamoroso** [comment]
No, actually there is not a specific ajax view. When I see in the console.log(msg) content I get just what I need, the plain view related to the called controller method containing the form. And that form is just fine, but without the custom templating.

**Comment by ADmad** [comment]
Core's [AjaxView](https://github.com/cakephp/cakephp/blob/master/src/View/AjaxView.php) is being used which does not extend your `AppView`. So add a `AjaxView` to your app which extends `AppView`.

**Comment by carloamoroso** [comment]
Thanks very much! This solved my issue. 
Sorry for my mistake
