### ISSUE TITLE
When extracting i18n with merge option, the cake.pot file is still created

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#7345]
When doing ``bin/cake i18n extract --app ./ --paths src,plugins --merge yes --output ./src/Locale/ --exclude test,vendors --overwrite --extract-core yes --no-location``

The file called cake.pot is still generated inside ``src/Locale/`` - while it's also contained inside the ``default.pot`` - is there any reason to include the file, when using the --merge yes?

**Comment by markstory** [comment]
I'm not sure there is a good reason to continue generating the cake.pot when merging. However, I'd be interested in testing out how changing that will work for plugin pot files.

**Comment by markstory** [comment]
Pull request open now #7354.
