### ISSUE TITLE
3.x ORM Using custom column type creates empty associated entity even if foreign key is null

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#7346]
Having custom type which always returns non-empty value forces the ORM to create empty associated entity for `null` foreign keys.

```PHP
class UserSettingsType
{
    public function toPHP($value, Driver $driver)
    {
        if ($value === null) {
            return new CustomClass; // I forces the property to be always an object
        }
        return new CustomClass($value);
    }
}
```

```PHP
// UsersTable.php
protected function _initializeSchema(Schema $schema)
{
    $schema->columnType('settings', 'user_settings');
    return $schema;
}
```

Now when running query:
```PHP
$this->Articles->find()->contain(['Users']);
```

all articles will have the `$article->user` object, even if `$article->user_id === null`. But when I change the `UserSettingsType` to return `null` if the $value is null, than the `$article->user` will be correctly null.

The `$article->user[$i]->settings` is always there even if the `$article->user[$i]->id` is null. This happens directly after executing the query. The ORM must somehow create the model entity object if not all attributes are empty.

**Comment by markstory** [comment]
The orm has to make the user entity as one of the fields is not null. Given that queries don't always include primary key values for associations we have rely on all fields being null to omit the association.

**Comment by Laykou** [comment]
Ah ok, I see. Maybe you should mention this in the custom types docs, that returnin a non-null value will create the model entity.

What do you suggest as workaround-solution? Should I return null, and handle the forcing of `CustomClass` in the protected `User@_getSettings()` method?

**Comment by lorenzo** [comment]
I would use an entity instead of a type class for this. Type classes are usually for value objects and not entities.

**Comment by Laykou** [comment]
The settings is an atribute which will be json string in database but have
CustomClass to support custom functions. Is this a wrong approach?

**Comment by lorenzo** [comment]
It is not too bad, but I'm not sure using an entity to represent the value is the best idea. In general I just  don't like storing json in the database :P

**Comment by Laykou** [comment]
CustomClass is just standalone class, not model entity. But I understand
that you don't like json in db :)
