### ISSUE TITLE
RFC Add Headers reset functionality to the Email class

### ISSUE THREAD

**Issue by BorislavSabev** [cakephp/cakephp#7348]
Currently (in 3.x) it is not possible to clear only the To: or Cc: or Bcc: but you can use the reset() function to clear all email fields/headers. Is it not feasible to have a new method that provides the ability for us to clear/unset certain headers of the Email?
  For example if I want to have a master send() method for my application and if I am in debug mode, send all emails to a specific email I cannot do this right now because by the time the email is ready for sending the To: is set and there is no way to clear it without clearing all other fields/options.

 This could be as simple as having reset() take a the header name or array of header names that you want it to reset. If nothing is passed the current functionality should be preserved. Or a separate method, anyway this is useful in different scenarios.

  I'd be happy to submit a pull rquest for this but I wanted to first discuss it here.

Cheers,
   Borislav Sabev.

**Comment by ADmad** [comment]
You can have a `profile` with defaults and after calling reset set that `profile` again.

**Comment by BorislavSabev** [comment]
What if one wants to change stuff on the fly? 
Not all my Cc's, Bcc's or To's can be set as defaults.... Most emails are sent to different users.

**Comment by ADmad** [comment]
Have you checked Mailer class of 3.1?

**Comment by BorislavSabev** [comment]
I just did and saw no such functionality there. 
The Mailer looks more concerned with formatting and reusability. I am talking about being able to reset individual header fields.

**Comment by markstory** [comment]
Setting a new to/cc/bcc address already overwrites the existing ones. Why would we need additional reset methods?

**Comment by BorislavSabev** [comment]
@markstory I was under the impression that that was not the case. Now when I looked at the code in more details it is the case. No need for such reset method(s).

This RFC is at its EOL.
Thanks for all your replies.

**Comment by jhli** [comment]
@BorislavSabev can you confirm the use case is well documented/hinted at in the book/docs? If not, could you add a PR to the book?

**Comment by BorislavSabev** [comment]
@jhli I don't think it is. I create the following pull rq:
https://github.com/cakephp/docs/pull/3224

**Comment by BorislavSabev** [comment]
@ADmad https://github.com/cakephp/docs/pull/3225
Sorry I thought it should be against the master.
