### ISSUE TITLE
Incorrect determination of "required" for boolean fields in related models

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#7349]
When generating inputs for fields, the isRequired function of EntityContext calls $this->type with the short field name, not the dot separated field name provided. In the case of related models, this tries to look up the field name in the "main" table that the form is for, not the related table. When the field has a validator and is boolean, the incorrect parameter to $this->type results in a return type of null instead of 'boolean', and it calls isEmptyAllowed instead of simply returning false.

The solution is to pass the original field value into $this->type instead of the result of array_pop($parts). Apologies for not including a patch or test case for this; haven't yet found the time to figure that stuff out. Hope the description and solution are clear.

**Comment by markstory** [comment]
How can someone reproduce the issue you are having.

**Comment by Zuluru** [comment]
If A hasMany B, B has a boolean field x with a validator (e.g. `$validator->add('x', 'valid', ['rule' => 'boolean'])`), and you use `$this->Form->input('bs.0.x')` in the edit page for A, the resulting input will have the "required" property, even though it's a boolean field.

**Comment by markstory** [comment]
Thanks, I'll try to reproduce based on that.

**Comment by markstory** [comment]
Pull request up now.
