### ISSUE TITLE
3.x Session write should accept a hash

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7352]
Ref: http://book.cakephp.org/3.0/en/development/sessions.html#Session::write
Current interface:
```php
$session->write('Config.language', 'eng');
```
Suggested *additional* interface:
```php
$session->write(['Config.language' => 'eng']);
```

Benefits:
A. One may save multiple values at once like such:
```php
$session->write([
    'Config.direction' => 'right-to-left',
    'Config.language' => 'eng',
]);
```
B. I came across this when thinking about how to make it easier to fetch data from the request context to the orm and noticed I might as well store those values in sessions

If you think this is sane, I would prep a PR.

**Comment by ADmad** [comment]
Using array is already [supported](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Network/SessionTest.php#L213)
