### ISSUE TITLE
After img header can't write session

### ISSUE THREAD

**Issue by minseclab** [cakephp/cakephp#7359]
public function validcode()
{
	$_vc = new VarcodeController();
	$_vc->doimg();
	$session = $this->request->session();
	$session->write('authnum_session', '111');
}

//输出
private function outPut() {
	header('Content-type:image/png');
	imagepng($this->img);
	imagedestroy($this->img);
}
	
//对外生成
public function doimg() {
	$this->createBg();
	$this->createCode();
	$this->createLine();
	$this->createFont();
	$this->outPut();
}

when the img had created, the after Session can't be used.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
