### ISSUE TITLE
$_accessible accepting common arrays

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#7362]
Hello everybody,
I've just noted that the special variable $_accessible in the Entity only accepts associative arrays, setting each property for true of false.
Once the properties not set as accessible are not accessible by default, I would like to propose to have this variable also accepting a list of field names and set them all to true.
Just like the example below:

<code>
$_accessible=['name','age'];
</code>

Would be the pretty same as

<code>
$_accessible=['name'=>true,'age'=>true];
</code>

I am ok to make a PR in case you approve. Once it is backward compatible, is this OK to enter in the current version?

**Comment by lorenzo** [comment]
I think it is better if it just accepts associative array. It is easier to have it in a single syntax

**Comment by mylux** [comment]
Well, we have a bunch of cases where methods accept different data structures in CakePHP. I think it will be only one more case.
I have to confess I have caused trouble to myself a couple of times when I have set this variable to a common array and association marshaling didn't work. I have spent a lot of time to figure it out, mainly because there is another variable ($_virtual) that works this way, so I replicated one structure into the other.
I totally understand that there is no reason to have associative arrays in the $_virtual variable.

**Comment by lorenzo** [comment]
The main reason it is associative is because setting properties to `false` actually has a meaning

**Comment by mylux** [comment]
Isn't it the same as not include a field into the $_accessible variable?

**Comment by ADmad** [comment]
@mylux Not if you have `'*' => true` in the list.

**Comment by mylux** [comment]
@ADmad , if you have '*'=>true it is the same as having all attributes set to true, no?
This cause no conflict in what I am proposing.

**Comment by ADmad** [comment]
I was just responding to your last comment about not including a field being same as it being set to false.

I too am in favor of just keeping the listing associative. Allowing non-associative would be confusing. You can use the non-associate form if your like and in constructor or initialize() normalize it to the associative form that cake requires.

**Comment by mylux** [comment]
Ok, I understand your point, but mine is that if you insert a '*', in the list, it is pretty the same as adding manually each of the fields and set them to true, so my statement still remains valid, because in this case the field is included (using a special operator that includes it).

**Comment by lorenzo** [comment]
`* => true` also means properties not in the schema

**Comment by markstory** [comment]
>  if you have '*'=>true it is the same as having all attributes set to true, no?

Not necessarily. You can have:

```php
$_accessible = [
  'id' => false,
  'password' => false,
  '*' => true,
];
```

Which means 'all fields other than id & password are accessible'.

**Comment by jhli** [comment]
I don't see the benefit. If you want to autofill things it is easy to create an assoc array set to true from a non assoc list.

**Comment by mylux** [comment]
Alright. By the way, nothing happens if you fill the list with a common array. If this type of value is not allowed, I think it would be fair to have at least, an exception for this case

**Comment by lorenzo** [comment]
Closing as this particular enhancement seems like more trouble than it is worth
