### ISSUE TITLE
cake flash, wrong var in source code

### ISSUE THREAD

**Issue by matben** [cakephp/cakephp#7365]
in cakephp 2.7.3. the error by unauthorized access. 

variable in CORE\Cake\View\Elements\Flash\default.ctp on line 7 must be $class instead of $key

error that shows up:
Notice (8): Undefined variable: key [CORE\Cake\View\Elements\Flash\default.ctp, line 7]Message" class="message">You are not authorized to access that location.

**Comment by matben** [comment]
variable in CORE\Cake\View\Elements\Flash\default.ctp on line 7 must be $class instead of $key

**Comment by markstory** [comment]
How can someone reproduce the issue you're seeing?

**Comment by matben** [comment]
in cake 2.7.3. i cake baked all.
and then i included Auth class. and when i want to enter to page that is
not allowed without login, i get next error (something is wrong with
flash). picture 1.
and than i changed $key to $class and everything works fine.. picture 2.

maybe only i have problem with that, but i  thought that it is universaly
error becouse it comes when i cake bake all.





2015-09-08 18:40 GMT+02:00 Mark Story <notifications@github.com>:

**Comment by matben** [comment]
![error](https://cloud.githubusercontent.com/assets/6535949/9759790/00b286fc-56f0-11e5-94d2-ea548d853aa9.png)
![noerror](https://cloud.githubusercontent.com/assets/6535949/9759792/0235257a-56f0-11e5-988c-95fb6b564b8c.png)

**Comment by JaviSabalete** [comment]
Thanks @matben works fine!

**Comment by markstory** [comment]
For me `$key` is set to `'flash'` or `'auth'`. I'm using a clean clone of the `2.7` branch. I tried both flash message errors from AuthComponent (with stock configuration), and 

```php
$this->Flash->set('testing');
```

In a controller.

**Comment by markstory** [comment]
Are you using FlashHelper to render flash messages, or the SessionHelper?

**Comment by markstory** [comment]
Fixed with #7379

**Comment by matben** [comment]
i think that there is session manager by default.

2015-09-10 4:05 GMT+02:00 Mark Story <notifications@github.com>:

**Comment by matben** [comment]
nope. i looked now.
there is:

$this->flash($this->AuthError);

best regards.
m

2015-09-10 4:05 GMT+02:00 Mark Story <notifications@github.com>:
