### ISSUE TITLE
Validation does not work when delete HTML code of fields on browser

### ISSUE THREAD

**Issue by trungtan** [cakephp/cakephp#7367]
My blog tutorial app has article table
```
CREATE TABLE IF NOT EXISTS `articles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(50) DEFAULT NULL,
  `body` text,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;
```
and validator
```
class ArticlesTable extends Table {
    public function validationDefault(Validator $validator)
    {
        return $validator
            ->notEmpty('title')
            ->notEmpty('body');
    }
```
It worked fine when I inputed nothing. But when I tried to hack by deleting html code of title and body fields, using Firefox inspector, that submission had passed validation and added new record into database.
Did I miss something or it's a bug?
I'm using version 3.0.8.

**Comment by ADmad** [comment]
You need to use $validator->requirePresence() to ensure existence of a field in data array.

**Comment by jhli** [comment]
Maybe the blog tutorial should show that.

**Comment by markstory** [comment]
Docs change up now.

**Comment by trungtan** [comment]
Can I use callable function to validate presence by condition?
I've tried 
```
...
        $validator
            ->requirePresence('title', FALSE)
            ->requirePresence('body', function ($context){
                return FALSE;
            })
...
```
But the body is still required.

**Comment by antograssiot** [comment]
@trungtan no you can't

http://api.cakephp.org/3.0/class-Cake.Validation.Validator.html#_requirePresence
