### ISSUE TITLE
RFC proposal - Cache shell for cache invalidation/removal

### ISSUE THREAD

**Issue by BorislavSabev** [cakephp/cakephp#7368]
Hello.

It be good to be able to have the means to clear caches out of the box with a one-liner.
I know you can use `Cache::clear(true);` or `Cache::clear(false);`  (and the orm_cache shell for query cache) but this RFC is not about that. It is about providing such functionality in a Shell bundled with the framework so at the end one could: `cake cache clear --all` for example.

This would be of good use as a deployment step. All this RFC is about is creating a Cache Shell with the one clear method that just calls Cache::clear(). Of course we can add all kinds of options like: clear only expired cache, clear all cache, clear only specific sections rather than everything and so forth.

It may not be a separate cache shell - it could be a part of a bigger "Utility Shell" that could contain all kinds of deployment or framework maintenance stuff like this.

What is the Core Team's opinion on this? No doubt in my mind that such a thing has been discussed.
I am not asking the core team to develop this - If there is approval for it I am going to submit a pull request .

**Comment by dereuromark** [comment]
This is already developed as plugin solution afaik.
See https://github.com/ceeram/clear_cache and https://github.com/fahad19/clear_cache .

**Comment by BorislavSabev** [comment]
Ok, I do know those 2 plugins.
However my idea is to have this in the CORE and be distributed with the framework.

**Comment by ADmad** [comment]
Having a shell for clearing cache in core itself sounds good to me.

**Comment by Marlinc** [comment]
I like having this in core. It could be called ```CachesShell``` and could in the future do even more.

**Comment by BorislavSabev** [comment]
My idea is to start with a CachesShell and provide basic functionality:

- clear all cache (force invalidate)
- clear expired cache
- clear all cache for a specific Group (specified as a param)

Then more exotic functionalities could be added.

**Comment by bravo-kernel** [comment]
:thumbsup:

**Comment by markstory** [comment]
> clear expired cache (default action)

This will be problematic as most cache backends auto expire data. However, the other operations should be simple enough to implement.

**Comment by BorislavSabev** [comment]
Ok. I will draft this Shell by the end of next week. I have some questions though: 
1. Against which branch should I make this? I imagine it will have to be 3.1. (I am not saying that I am going to make it in for the release of 3.1.)

2. Also I will have to provide a "full-package":
- the Shell source that is passing CakePHP Code Sniffer
- unit tests for all calls
- some initial documentation in a separate commit to the docs repo

So am I missing something that I need to provide?

**Comment by ADmad** [comment]
You can target 3.1 branch. The todo list you have shown pretty much covers everything :)

**Comment by markstory** [comment]
@BorislavSabev Don't worry about hitting 3.1.0, this is the kind of thing we can roll into any of the 3.1.x releases.

**Comment by BorislavSabev** [comment]
@markstory exactly my point. I just wanted to be sure you all understood my target was not the 4.1 release.
Thanks I will be working on this draft.

**Comment by BorislavSabev** [comment]
@ADmad  @markstory is it correct that if you set a Shell's option's *default* param to NULL the option will not be available at all in $this->params. Example:

```php
public function getOptionParser()
{
    $parser = parent::getOptionParser();
    $parser->addOption('groups',[
                'short' => 'g',
                'help' => 'Whatever...',
                'default' => NULL
            ]);
    return $parser;
}

// Then in a function:
    $grp = $this->params['groups'];
```
This last line Raises an _**Error: Undefined index: groups...**_.
Isn't `$this->params` supposed to always contain the option key especially since a 'default' value is specified? Just wondering if this is a feature or BUG.

**Comment by HavokInspiration** [comment]
Having default to ``null`` will result in the param having no default (``null`` being the default value for the ``default`` option). See ref in source [here](https://github.com/cakephp/cakephp/blob/master/src/Console/ConsoleOptionParser.php#L352-L358) and [here](https://github.com/cakephp/cakephp/blob/master/src/Console/ConsoleOptionParser.php#L604-L606).

Depending on what you need / want to do, can a ``isset($this->params['group'])`` do the trick ?

**Comment by BorislavSabev** [comment]
@HavokInspiration  of course a ternarry `isset()` check will do the trick in handling this.
My question however aims at the default's desired behavior.

**Comment by biesbjerg** [comment]
As far as I know it's not possible to clear web apc/opcache from cli without hacks(or running php-fpm), so I'm not sure how useful this feature is in practice?

**Comment by BorislavSabev** [comment]
@biesbjerg there is a function in APC: [apc_delete](http://php.net/manual/en/function.apc-delete.php) deleting should work. 
OPsache is totally unrelated since it is not a cache back end in Cake and it is not runtime. OPcache caches precompiled script bytecode which is something totally different from the [CakePHP/Cache layer](https://github.com/cakephp/cache).

**Comment by majna** [comment]
@BorislavSabev APC *is* one of cache backends in CakePHP. As @biesbjerg pointed out, cache entries stored by web server process will be in different memory space and thus cannot be cleared from CLI process (or vice versa).

Anyway, APC is dead, last version is released 3 yrs ago, PHP 5.4 is beta-supported (segfaulting, open bugs) and it doesn't work with 5.5+. We can just add a note in the docs about APC cache engine limitations.

**Comment by ceeram** [comment]
Would such a shell not better fit debugkit instead of core
Op 23 sep. 2015 19:56 schreef "Ivan Majnaric" <notifications@github.com>:

**Comment by ADmad** [comment]
@ceeram Clearing cache isn't just a development related task. We have orm_cache shell too in core.

**Comment by burzum** [comment]
@BorislavSabev are you still working on this?

**Comment by chris48s** [comment]
I also think it would be really useful if this was included in core and this issue has been open for a while so I had a go at putting together something based on the discussion in this thread.

I've not submitted a PR to core before so thought I would post here for comments first:
https://github.com/chris48s/cakephp/commit/4ce2da2e486d97c62e0ab7c5268fcc955f506d67
Would it seem reasonable to submit this as a PR targetted at `3.next`?

Thanks

**Comment by markstory** [comment]
Looks like a good start @chris48s. I would call the shell `CacheShell` instead of `CachesShell` though.

**Comment by chris48s** [comment]
> call the shell `CacheShell` instead of `CachesShell`

There are only 2 hard problems in computing... ;)

**Comment by markstory** [comment]
I thought there were 3? Or did you forget off by one errors :trollface:

**Comment by bravo-kernel** [comment]
Aside from [documenting](https://github.com/cakephp/cakephp/issues/7368#issuecomment-142679829), I think it would be nice if the shell would inform users about APC limitations/expectations when `ApcEngine` is detected (shell will only clear cli cache, not web server cache). 

Maybe even suggest to gracefully reload their web server if they persist on clearing web server cache from cli.Took me half a day to realize :scream:

**Comment by markstory** [comment]
@bravo-kernel Printing errors warnings for wincache/apc sounds like a great idea. As they work very differently than other caching backends.

**Comment by chris48s** [comment]
Thanks for the feedback. Based on those comments I have updated my branch and submitted PR #8900

**Comment by bravo-kernel** [comment]
I see you incorporated the Apc and Wincache informationals. 💯

**Comment by markstory** [comment]
Closing as there is a pull request now.

**Comment by BorislavSabev** [comment]
@chris48s  I am very happy that someone picked this one up and did something. 
I did also develop the Shell but didn't write the tests and thus didn't submit it back then.
Very stupidly bad of my side. Anyway I am happy someone did it. Thanks.
