### ISSUE TITLE
2.x Debugger class not found 

### ISSUE THREAD

**Issue by SanderSander** [cakephp/cakephp#7376]
Hey,

In Error/ErrorHandler.php on line 233 (and few lines above) the Debugger class is used, but there is an issue in some PHP versions (it's fixed in http://php.net/ChangeLog-5.php#5.4.21). Note that E_STRICT is also a compile time error.

The issue is that the autoload functionality doesn't work when an error is triggered. Therefor the Debugger class isn't always available and you will get errors like "Class 'Debugger' not found in [EOF]" 

So the debugger class should be loaded manually if the phpversion is lower then 5.4.21 to prevent this from happening. (I encountered this issue on an old system with cakephp 2.6.x)   

Cheers,
Sander

**Comment by markstory** [comment]
Since you understand the issue pretty well, would you be able to open a pull request with the correct changes?

**Comment by SanderSander** [comment]
@markstory  Ofcourse, I will make PR this weekend

**Comment by markstory** [comment]
Closing as a pull request is up now.
