### ISSUE TITLE
FormHelper input inserts multiple class="..." attributes to html element

### ISSUE THREAD

**Issue by sarrala** [cakephp/cakephp#7381]
CakePHP 3
When I call:
```
echo $this->Form->input('some.thing', [
		'options' => $input_options,
		'class' => 'testclass'
]);
```

Opening tag looks like this:
```
<select class="form-control" name="some[thing]" class="testclass form-control">
```

And I think that it should look like this:
```
<select name="some[thing]" class="testclass form-control">
```

I think that problem is in `select` template as `StringTemplate::_compiled['select']` contains following:
```
<select class="form-control" name="%s"%s>%s</select>
```

And data attrs contains:
```
class="testclass form-control" id="some-thing"
```

I'm not sure if it is problem with Template containing class="form-control" attribute or FormHelper that generates class="form-control" attribute but won't merge class attributes together.

**Comment by sarrala** [comment]
Looked a little bit further and it seems that this could be problem with FriendsOfCake/Bootstrap-UI templates.

If anyone could confirm this before I could do it then please just close this issue and I'll reopen another for bootstrap-ui.

**Comment by markstory** [comment]
The [core templates](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L93-L122) don't define any class names. So its probably your templates.
