### ISSUE TITLE
Fertile Forest Model for storing hierarchical data in a database

### ISSUE THREAD

**Issue by StewEucen** [cakephp/cakephp#7382]
We know four models to store hierarchical data in a database.
* Adjacency List Model
* Path Emuneration Model
* Nested Sets Model and Nested Intarvals Model.
* Closure Table Model

I had discovered the 5th-model, and named it "Fertile Forest Model". It is referred to "FF model" or "FFM" as abbreviation.

Now I think FF model is better than Nested Sets Model. I had finished to create behavior of FF model for CakePHP 3.x and 2.x.

Do you want to see about it?
If so, I will show it.

**Comment by markstory** [comment]
Are you thinking this could be an alternative to the TreeBehavior?

**Comment by ADmad** [comment]
@StewEucen Why not just publish it as a plugin first so users and try it out and give feedback?

**Comment by dakota** [comment]
Some links and information on it would be nice as well.

**Comment by StewEucen** [comment]
I have just arrived my home. Sorry for reply late.

@markstory
I think so. After you know about FF model, maybe you will got same thinking as me.
My plan is that CakePHP 4.x includes ForestBehavior.

@ADmad
I am sorry, I had no idea for showing my tech.
You gave me hint about plugin. Thanks for your advice.
Hereafter, I will try to create plugin or other way for showing FF model.

@dakota
Now I am readying some links and information about FF model.
To write Japanese language is so easy, but it needs to write English.
It is very hard for me. I need a time for writing them.

---

But all, FF model is very simple. You do not require effort to understand it.
Please wait a while. I will give you gold experience.

**Comment by ADmad** [comment]
> To write Japanese language is so easy, but it needs to write English.
> It is very hard for me. I need a time for writing them.

In that case it would be very useful if you create a plugin so that people can review the code with minimal description in natural language :)

**Comment by StewEucen** [comment]
@ADmad Your icon has very scary impression, but you are so kindly. Thank you for your advices.

I started to create FertileForestBehavior from April 2015. Firstly for 2.x, and then for 3.x.
I found some probrems in CakePHP library in my creative activity, and sent some pull requests.
These are for FertileForestBehavior. Soon later, you will know the means of my pull requests. :)

**Comment by ADmad** [comment]
> Soon later, you will know the means of my pull requests. :)

Keep you focus on making a standalone plugin rather than a pull request.

**Comment by StewEucen** [comment]
@ADmad Yes, I am doing so. My first mission is to create plugin.
In my post, "means of pull requests" is past things.
It is must be written "means of pull requests in past".
My English is so poor, I am sorry.

**Comment by dereuromark** [comment]
As discussed this should first be a plugin solution.
Please advertise it then to the community by publishing it in https://github.com/FriendsOfCake/awesome-cakephp#orm-and-datamapping .
You can also discuss it further in the IRC channel group `#cakephp`.
Thank you - we can close this then.

**Comment by StewEucen** [comment]
@dereuromark Thank you for giving the information!
I did not know FriendsOfCake/awesome-cakephp.
Now I got correct procedure for including new idea into CakePHP.
I create plugin and will advertise it there.

I have made a mistake here. However, mistake is our friend.
It sometime give us treasures and pleasures.

**Comment by dereuromark** [comment]
Refs https://github.com/StewEucen/fertile-forest-cakephp-plugin

**Comment by StewEucen** [comment]
@dereuromark 
Thanks for your introduction.

I wrote about structure of Fertile Forest Model in my website.
Maybe it can help understanding.

If I can post URL of my website here, I will write it.
Is it OK?

**Comment by ADmad** [comment]
You should add any extra info to the readme of your repo not here.

**Comment by StewEucen** [comment]
@ADmad  I see.
Please consider about new model.
