### ISSUE TITLE
Retrieving not necessary translations

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#7383]
I have several models associated and some of their fields are Translated in a general table called i18n.
I am trying to get the translation of some of them, not all. Unfortunately CakePHP is creating a SQL with the LEFT JOINS of every field that has a translation without having in mind my select method.
Is there any way of accomplish this? Am I doing something wrong?

My query:
```PHP
$champions = $this->Champions->find()
    ->select(['id', 'name', 'title'])
    ->order(['Champions.name'])
    ->contain(['Images' => function($q){
        return $q
            ->select(['group', 'full', 'sprite', 'x', 'y', 'w', 'h'])
            ->where(['group' => 'champion']);
    }]);
```

SQL generated:
![sql generated](https://cloud.githubusercontent.com/assets/5722357/9814169/2ce257d2-588c-11e5-9b9f-1ebaf22ad984.png)

Note that I did not ask for a field called "lore" or "blurb" so of course I did not want their respective translations.

**Comment by lorenzo** [comment]
No, it is not currently possible. You can temporarily modify the configuration for the behavior to only bring back a few fields.

**Comment by Tzaoh** [comment]
Ok Lorenzom thanks for your quick answer
