### ISSUE TITLE
Php Intl loaded, enabled but cake cannot cake

### ISSUE THREAD

**Issue by psydack** [cakephp/cakephp#7385]
Hi, I'm new with cakephp and I'm trying to cake my first app but I cant because this error:

requires ext-intl * -> the requested PHP extension intl is missing from your system.`

I know what it's say, but my `INTL` is enabled and loaded. I recompile my php ( with last version > 5.6.x ) ( intl 1.1.0 ) on OSX Yosemite and nothing. I reinstalled with macport and still throwing this error. I've tried all "stackoverflows" around but nothing.  
My php (with intl loaded & enabled ), apache and mysql is running but I can't figure out what I'm missing.

Can you guys help me ?

![screen shot 2015-09-12 at 03 25 33](https://cloud.githubusercontent.com/assets/961971/9830270/ae90100e-58fe-11e5-93de-d93d18f614a5.png)
![screen shot 2015-09-12 at 03 30 25](https://cloud.githubusercontent.com/assets/961971/9830271/ae93481e-58fe-11e5-8e02-b015eb17cded.png)

**Comment by psydack** [comment]
Okay, my environment is wrong. I never ever think this system can have a php pre-installed. Whatever, sorry for create more one ticket. Who have the same error : just go to `/usr/bin/php` (rename or delete) create a symlink for your php (in my case : `sudo ln -s /opt/local/bin/php56 /usr/bin/php`). =)

**Comment by HavokInspiration** [comment]
Thanks for getting back and giving a solution that might be useful to others !
