### ISSUE TITLE
Url Helper link generation prepends 'app' upon redirecting from document_root

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#7386]
DocumentRoot of the application is: `/var/www/`
Application is under `/var/www/app`

So I have placed the following in my `.htaccess` file which is under /var/www/ (outside app) ::

```apache
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /
    RewriteRule (.*) app/webroot/$1 [L]
</IfModule>
```

I am using [UrlHelper](http://book.cakephp.org/3.0/en/views/helpers/url.html#generating-urls) for building URLs.

On every link it is appending `/app/` for every route.

Example: `/users/login` when hovered on the link shows : `/app/users/login`

tried adding true to get full path URL - still prepends app.

**Comment by ADmad** [comment]
If your app is under a subfolder of DocumentRoot ("app" in your case) then having the subfolder name in the url is expected based on default config. You can specify `App.baseUrl` config explicitly to '/'.  

If you have more queries please post your question on stackoverflow.com or ask on IRC channel.
