### ISSUE TITLE
automated cpanel install issue v 3.012

### ISSUE THREAD

**Issue by GreenPortal** [cakephp/cakephp#7388]
I have installed cake using GoDaddy cpanel automated install. Install is fine but I keep seeing an error about missing SrcController.pho

I tried to create using code in error message but then get more errors
![error1](https://cloud.githubusercontent.com/assets/14260361/9836930/60998494-59f2-11e5-9930-58b153933629.png)

**Comment by ADmad** [comment]
The path `/src/Console/Installer.php` is never meant to be accessed as URL.

I suggest you follow the official [installation guide](http://book.cakephp.org/3.0/en/installation.html#installing-cakephp). The CakePHP team does not manage the cPanel installer.
