### ISSUE TITLE
$this->requestAction inside a controller should be able to return the headers of the answer

### ISSUE THREAD

**Issue by klickagent** [cakephp/cakephp#7389]
I would recommend implementing a return content like 'return' => 'header' in the extras for requestAction. Otherwise requestAction returns Null if the called action is returning a redirect object.

In Dispatcher.php the following code would return the header accordingly:
if (isset($request->params['return']) && $request->params['return'] === 'header' ) {
    return $response->header();
}

Perhaps an even better solution would be if it is possible to specify the return value as an array with the desired return values eg. 'return' => array('header','body')

**Comment by markstory** [comment]
I don't think that `requestAction` is likely to see many improvements. Internal sub-requests are often better implemented through other means.

**Comment by josegonzalez** [comment]
This should be closed as `requestAction` is deprecated.
