### ISSUE TITLE
Datetime current_timestamp issue

### ISSUE THREAD

**Issue by kyoclover** [cakephp/cakephp#7393]
Cakephp 2.x

```sql
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Related to issue 4184
https://github.com/cakephp/cakephp/issues/4184
and pull 4386
https://github.com/cakephp/cakephp/pull/4386/files

Since The `DEFAULT CURRENT_TIMESTAMP` support for a `DATETIME` datatype was added in MySQL 5.6 and cakephp only checks `CURRENT_TIMESTAMP` for a `TIMESTAMP datatype like this:

```php
if ($fields[$column->Field]['type'] === 'timestamp' && strtoupper($column->Default) === 'CURRENT_TIMESTAMP') {
	$fields[$column->Field]['default'] = '';
}
```

So it will not work with a DATETIME datatype.

I know there is a lot of word around and cakephp will do everything if I remove CURRENT_TIMESTAMP but may be it will be better work with  a DATETIME datatype.

**Comment by markstory** [comment]
Given that you understand the change that is needed, would you be able to submit a pull request that adds the desired behavior?

**Comment by markstory** [comment]
Closing as a pull request is open now.
