### ISSUE TITLE
Finder option in BelongsToMany association

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#7397]
HI!
in the book i see a `finder` option for BelongsToMany association. In the API, not.

http://book.cakephp.org/3.0/en/orm/associations.html#belongstomany-associations
http://api.cakephp.org/3.0/class-Cake.ORM.Table.html#_belongsToMany

**Comment by markstory** [comment]
Pull request open.

**Comment by damianoporta** [comment]
@markstory I am looking for the test case with custom finder method. Does it exist?

**Comment by markstory** [comment]
@damianoporta I don't think there is an explicit one, however there are many implicit tests, as the default 'finder' is 'all'.
