### ISSUE TITLE
'class' and other options to date inputs are ignored

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#7398]
I tried to create a date input with a class and custom data on it, like so:

    echo $this->Form->input('birthdate', [
        'class' => 'test',
        'data-whatever' => 'whatever',
    ]);

(birthdate is obviously a date column) with the expectation that the resulting inputs would be like so:

    <select name="birthdate[year]" class="test" data-whatever="whatever">
        <option...>
    </select>

But neither the class nor data-whatever attributes are present on the various selects created. I should be able to accomplish what I want by wrapping the whole thing in a div with the required attributes, but this will require some JavaScript changes, and I didn't want to head down that path unless I know that the attributes are not being added on purpose.

I'm using version 3.0.9 at the moment (an update I ran a while ago broke some things and I didn't have time to chase them down so I just downgraded for the moment), but I don't see any changes since then in View\Widget\DateTimeWidget or View\Helper\FormHelper that would have affected this.

**Comment by markstory** [comment]
Classes and other attributes need to be set on a per-select box basis. For example:

```php
echo $this->Form->dateTime('Contact.date', [
    'year' => [
        'class' => 'my-class',
    ],
    'month' => [
        'data-test' => 'value',
    ]
]);
```
This gives more control on how custom attributes are applied compared to previous versions. If you need custom attributes applied to all pickers you will need to customize the DateWidget.

**Comment by Zuluru** [comment]
Very cool! Now that I know what to look for, I found an example in the "Creating Time Inputs" section of the book; I was looking in the more general areas, and didn't look there because my inputs are dates not times. Perhaps a little improvement to be made there?

**Comment by markstory** [comment]
Sure, I can update the docs :smile:
