### ISSUE TITLE
Support for all possible CORS headers

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7402]
Hey guys (been a while!). Right now the `Response::cors` method accepts domains, methods, and headers. There are 3 other possible headers for full CORS support, `Access-Control-Expose-Headers`, `Access-Control-Max-Age`, and `Access-Control-Allow-Credentials`. It seems like the `cors` method should deal with all 6 so that app-side we don't have to also do an `Origin` check and set those other headers.

Specifically with my app, we need `Access-Control-Allow-Credentials` set to `true`, and it'd be great to do something like this in a controller:
```
$this->response->cors(
    $this->request,
    [$this->request->host()],
    ['PUT', 'GET', 'POST', 'DELETE', 'OPTIONS'],
    ['origin', 'x-requested-with', 'content-type'],
    true
);
```
Where that `true` sets the `Access-Control-Allow-Credentials`. I can make this change / add a test for it if it's something you guys think would benefit everyone. I realize this is one of those things that it's easy enough to do outside the core but I like all-or-nothing when it comes to stuff like this.

Thanks

**Comment by markstory** [comment]
Seems pretty reasonable to me.

**Comment by ionas** [comment]
Oh nice, I did set all the CORS stuff manually for my public APIs of my webservice. https://www.google.com/search?q=cors+site:http://book.cakephp.org/3.0/en&ie=utf-8&oe=utf-8 Seems the book does not feature documentation on CORS. Should it?

**Comment by jadb** [comment]
While I like having the extra options for CORS, am not sure this should be done at the controller level at all. Have a look at this implementation https://github.com/snelg/cakephp-cors using the a `DispatchFilter`.

Here's something I digged from code I had written to work with an AngularJS app using JWT (all routes are API endpoints in that one):

```php
<?php
namespace App\Routing\Filter;

use Cake\Event\Event;
use Cake\Routing\DispatcherFilter;

class CorsFilter extends DispatcherFilter
{
    /**
     * {@inheritdoc}
     * @param \Cake\Event\Event $e Event.
     * @return mixed
     */
    public function beforeDispatch(Event $e)
    {
        $request = $e->data['request'];
        $response = $e->data['response'];

        if (!$origin = $request->header('Origin')) {
            return;
        }

        $response->cors(
            $request,
            '*',
            [
                'GET',
                'PATCH',
                'POST',
                'PUT',
                'DELETE',
                'OPTIONS',
            ],
            [
                'x-csrf-token',
                'Keep-Alive',
                'User-Agent',
                'X-Requested-With',
                'If-Modified-Since',
                'Cache-Control',
                'Content-Type',
                'Accept',
                'Authorization',
            ]
        );

        $response->header('Access-Control-Allow-Credentials', 'true');

        if ($request->is('options')) {
            $response->header('Access-Control-Max-Age', '172800');
            return $response;
        }
    }
}
```

**Comment by patrickconroy** [comment]
Thanks @jadb .. I like that as a Filter much better than in the controller.

**Comment by jadb** [comment]
Agreed @patrickconroy! Unless only for a single endpoint, then it would be overkill but otherwise, for APIs, I wouldn't do it in controller.

**Comment by bravo-kernel** [comment]
:tractor:

**Comment by markstory** [comment]
Reopening as the pull request didn't get merged. Ideally we'd use a [builder instead of making the cors method huge](https://github.com/cakephp/cakephp/pull/7405#issuecomment-140942012).

**Comment by markstory** [comment]
Closing as another pull request is up.
