### ISSUE TITLE
CakePHP3 Cells caching always calls display action

### ISSUE THREAD

**Issue by pperejon** [cakephp/cakephp#7410]
I'm creating a plugin that will provide my application of some CMS Cells I will be able to re-use application wide.

The problem I've found is that when you create a Cell that you want to cache, the cache file is created as you'd expect, and it's also returned if it exists, or recreated if it doesn't. Everything is working fine, except for the fact that the Cell display action is being called and executed, even when its results are not going to be used 'cause there is a valid cached element for it.

    $cell = $this->cell('Cms.CmsPage', 
        ['id' => 1], 
        [
            'cache' => [
                'config' => 'cms',
                'key' => 'page_1'
            ]
        ]
    );

    echo $cell->render();
When the cell is created and assigned to $cell the cache is not checked, so the action is executed. Then in the render() action, CakePHP sees there is already a valid cache file and simple returns it (as usual).

The result is still correct but I think that Cell display action shouldn't be called if you are using the cache and there is an active cache element. This way we could use Cells as we did with Cake2.x elements with requestAction where if you cache the element you could save a lot of requests and processing.

BTW, I think Cells are awesome. THX!!!

**Comment by markstory** [comment]
I agree it would be better if cells skipped their methods if the result would end up cached. That would require some significant changes to the cell internals to make that happen though.

**Comment by ADmad** [comment]
So I have managed to avoid calling action if cached cell exits: https://github.com/cakephp/cakephp/compare/master...ADmad:cell-cached

Couple of noteworthy things:

1. The CellTrait::cell() no longer invokes the action after creating cell instance. Instead the action and args are set as cell properties and the action is invoked by Cell::render(). Need opinions whether this is a good idea.

2. The early check for cached content will fail Cell::$template is modified in action and is not same as action name as by default the template name is used to generate cached key. Problem can be avoided by using custom cache key.

**Comment by markstory** [comment]
@ADmad Not invoking the action right away will defer the creation of any properties if userland code relies on properties/state in the cell we could break that.

I think this is a net positive change, perhaps we could put it in 3.2?

**Comment by ADmad** [comment]
@markstory Yup putting it in 3.2 sounds good. I'll make the PR.

**Comment by markstory** [comment]
Closing as there is a pull request open now, that further discussion can be around.
