### ISSUE TITLE
Cake\ORM\Query::contain() $override doesn't work as expected

### ISSUE THREAD

**Issue by MikkelPaulson** [cakephp/cakephp#7412]
The `$override` flag in `Cake\ORM\Query::contain()` doesn't reset existing associations as expected unless `contain()` is first called with no associations and then repopulated:

    class MyController extends AppController {
        public function index() {
            $query = $this->MyModel->find();
            $query->contain(['OtherModel1', 'OtherModel2']);
            
            // case 1 (broken):
            $query->contain(['OtherModel1'], true); // OtherModel2 should be removed by this
            debug($query->contain()); // OtherModel2 is still present - unexpected behaviour
            
            // case 2 (working/workaround):
            $query->contain(null, true); // trigger if (empty($associations) && $override) condition to remove all associations
            $query->contain(['OtherModel1']);  // repopulate with only the associations we want
            debug($query->contain()); // now OtherModel2 is gone as expected
        }
    }

Affects version: 3.0.13
Reference: http://api.cakephp.org/3.0/class-Cake.ORM.Query.html#_contain

**Comment by markstory** [comment]
pull request up now.
