### ISSUE TITLE
commandline disable log output to screen

### ISSUE THREAD

**Issue by blieb** [cakephp/cakephp#7417]
Hi,

I'm working in command line with cake shell. But I have to disable output to cli. You can do that by calling shell with -q flag. But when you want to log something to file (with $this->log('text', 'debug')). It also appears on the screen. I think this should not be happen when you use the -q flag.

I need it to be quiet because the process is included in an other php process as child. and it only needs to send correct data to the parent and no logs.

**Comment by markstory** [comment]
In quiet mode, would you expect that error logs still go to stderr?

**Comment by blieb** [comment]
I think that is the only what I expect. (But maybe that should be an option)

**Comment by lorenzo** [comment]
In quite mode I would actually expect no output. You can disable the stdout logger by calling  `Cake\Log\Log::drop('stdout');` at the start of your shell.

**Comment by ravage84** [comment]
In quiet mode, I expect that I get no output to the "monitor", neither stdout, nor stderr.
But the quiet mode should have no further implications, such as whether or not to log anything to a file, IMHO.

**Comment by markstory** [comment]
But no stderr, and no logging at all seems pretty useless in an operational context. I can see how no data to stdout could be useful, but silencing stderr means silent failures.

**Comment by dereuromark** [comment]
I am with @markstory in that one.
Failures overwrite silent mode IMO.

**Comment by lorenzo** [comment]
True, stderr should still be there

**Comment by ravage84** [comment]
@markstory not sure you misunderstood me, with no further implications, I meant that it should log to a file, if it was configured to do so.

I'm OK with outputting stderr in quiet mode, but I think there are errors and (fatel/exceptional) errors. While a "normal" error might not be displayed, a fatal or exceptional error probably should. With fatal and exceptional I do not necessarily mean PHP fatal errors and PHP exceptions but fatal and exceptional to the shell processing and the logic the shell should run. Unfortunately we don't distinguish between them for the shell at the moment.

On the other hand there is still the execution return code. So if you execute a shell in quiet mode and have it configured to log errors you would get: a) a return code 1 and b) some error messages to be logged.

Last but not least I guess we should orientate ourselves by how most *nix CLI shell programs behave if they supply a quiet mode.

[ rsync](http://linux.die.net/man/1/rsync), for example states:

````
 -q, --quiet                 suppress non-error messages
...
--log-file=FILE         log what we're doing to the specified FILE
````

So if I try to execute the shell with a fatal error it sill puts it to the screen, but also logs it to the configured file:
`````bash
user@host:~$ rsync -q --log-file ~/rsync.log /foo/bar /foo/baz
rsync: change_dir "/foo" failed: No such file or directory (2)
rsync: change_dir#3 "/foo" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.0]
rsync error: errors selecting input/output files, dirs (code 3) at io.c(1642) [sender=3.1.0]
````

If i execute it with no error, it shows ne output but still logs to the configured file:
```` bash
user@host:~$ rsync -q --log-file ~/rsync.log /home/orca /tmp/rsync_temp
````

**Comment by markstory** [comment]
I did misunderstand you @ravage84. We currently don't support `--log-file` options and have no reasonable way of knowing whether or not a user has configured logging in a funny way, which is why I recommended we leave the stderr output enabled even when `-q` is used.

**Comment by ravage84** [comment]
Sure we have no way to define a log file output through CLI parameter, but one can configure his app/shell to log stuff. We should respect that and the quiet mode should not disable that.

Yeah, under these circumstances, the stderr should stay enabled.

**Comment by markstory** [comment]
Pull request up now.
