### ISSUE TITLE
Query WHERE IN

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#7422]
Is it still possible to use the an array directly in the condition of a query or should we use the function in()? 

I tried both options and both failed. The first one translate the array to 1 and in the second one I do not have access to the result of previous queries (even when I attempt to use global). Is this the expected behaviour?

**Comment by markstory** [comment]
> Is it still possible to use the an array directly in the condition of a query

Yes it is possible to use an array in query conditions. What did the code you tried look like?

**Comment by ADmad** [comment]
Using array to generate `IN` clause works as described in [manual](http://book.cakephp.org/3.0/en/orm/query-builder.html#automatically-creating-in-clauses).
