### ISSUE TITLE
CakePHP warning and Notice after installation

### ISSUE THREAD

**Issue by CzarMich** [cakephp/cakephp#7425]
After installing my cakephp successfully, on first time running, am getting these warnings at the bottom. How can i fix them..Please help me.. am totally new to Baking. Thank you so much.

Warning (2): Missing argument 1 for View::element(), called in /Users/michaelanywar/Sites/cakephp/app/View/Layouts/default.ctp on line 61 and defined [CORE/Cake/View/View.php, line 398]

Notice (8): Undefined variable: name [CORE/Cake/View/View.php, line 416]

Notice (8): Undefined variable: name [CORE/Cake/View/View.php, line 422]

Notice (1024): Element Not Found: Elements/.ctp [CORE/Cake/View/View.php, line 425]

My section of the view.php in question looks like this.

LINE398 public function element($name, $data = array(), $options = array()) {
    $file = $plugin = null;

    if (isset($options['plugin'])) {
        $name = Inflector::camelize($options['plugin']) . '.' . $name;
    }

    if (!isset($options['callbacks'])) {
        $options['callbacks'] = false;
    }

    if (isset($options['cache'])) {
        $contents = $this->_elementCache($name, $data, $options);
        if ($contents !== false) {
            return $contents;
        }
    }

  
LINE 416 $file = $this->_getElementFilename($name);
    if ($file) {
        return $this->_renderElement($file, $data, $options);
    }

    if (empty($options['ignoreMissing'])) {
LINE422    list ($plugin, $name) = pluginSplit($name, true);
        $name = str_replace('/', DS, $name);
        $file = $plugin . 'Elements' . DS . $name . $this->ext;
LINE425      trigger_error(__d('cake_dev', 'Element Not Found: %s', $file), E_USER_NOTICE);
    }
}

**Comment by lorenzo** [comment]
What version of CakePHP did you install? and how did you install it?

**Comment by CzarMich** [comment]
Hello Lorenzo, thanks for the reply.. Am using 2.7.3..

**Comment by CzarMich** [comment]
I used manual installation. Couldn't get composer working on my Snow leopard..... So I just downloaded and unpacked..then did the rest of the missing plugins tell I cleared all missing dependencies .. But now those warnings am getting have tied me down..

**Comment by lorenzo** [comment]
We will investigate the issue.

Any reason you chose using 2.7 over version 3.1?

**Comment by CzarMich** [comment]
Hello Lorenzo, what I did was to remove the  <?php echo $this ->element();?> line from the default.ctp and the error disappeared, but won't that have an effect in the future for any other works I'll do..

**Comment by CzarMich** [comment]
I realized, I don't have default template in the view/Element  folder..

**Comment by CzarMich** [comment]
Moving the default.ctp to Elements folder was the best thing and then calling it <?php echo $this ->element('default');?>
I removed the default.ctl in the layout folder..
