### ISSUE TITLE
Authentication setUser 

### ISSUE THREAD

**Issue by ditoskas** [cakephp/cakephp#7434]
Hello,

i use the default authentication of cake, after upgrading to version 3.1 the setUser of Auth object doesn't allow me to set an object (it worked in previous versions) and i receive the below messages

Argument 1 passed to Cake\Controller\Component\AuthComponent::setUser() must be of the type array, object given
Argument 1 passed to Cake\Auth\Storage\SessionStorage::write() must be of the type array, object given

Is this by plan ? will this be like this from now on ?

**Comment by ADmad** [comment]
The `$user` argument of  `AuthComponent::setUser()` has been type hinted as `array` since [3.0.0](https://github.com/cakephp/cakephp/blob/3.0.0/src/Controller/Component/AuthComponent.php#L597).  So so nothing has changed in that respect and you would have got an error earlier too.
