### ISSUE TITLE
wrong INNER JOIN on an self-referencing belongsToMany Association

### ISSUE THREAD

**Issue by schrolli** [cakephp/cakephp#7439]
a wired effect: a parent-entity will fetch itself, when it should fetch the contained child-entities

# Database Layout

table "articles" hold items to sell. one item can include other items (e.g. a crate includes 20 beers)

the table "contains" has four fields: id, article_id, contained_article_id, amount.

so the "article_id" holds "amount" times "contained_article_id".

the ArticlesTable has this Associations (unrelated assocs are stripped):

```
$this->belongsToMany('ChildArticles', [
	'className' => 'Articles',
	'through' => 'Contains',
	'foreignKey' => 'article_id',
	'targetForeignKey' => 'contained_article_id',
]);
$this->belongsToMany('ParentArticles', [
	'className' => 'Articles',
	'through' => 'Contains',
	'foreignKey' => 'contained_article_id',
	'targetForeignKey' => 'article_id',
]);
```
# retrieving queries
now when i fetch an Article with `'contain' => ['ChildArticles']`, the article (a crate) itself is fetched normal, but it has an another Entity of itself in its child_articles property.

here is the controller-code:
```
$article = $this->Articles->get($id,[
	'contain' => ['ChildArticles'],
]);
debug($article);
```

and here is the Debug-output:
```
object(App\Model\Entity\Article) {

	'id' => (int) 4,
	'name' => 'Loscher Export Kasten',
	'sales_price' => (float) 0,
	'purchase_price' => (float) 0,
	'refund' => (float) 3.5,
	'active' => true,
	'no_fixed_price' => false,
	'log' => '',
	'created' => null,
	'modified' => object(Cake\I18n\Time) {

		'time' => '2015-09-20T02:23:10+0200',
		'timezone' => 'Europe/Berlin',
		'fixedNowTime' => false
	
	},
	'article_category_id' => (int) 3,
	'child_articles' => [
		(int) 0 => object(App\Model\Entity\Article) {

			'id' => (int) 4,
			'name' => 'Loscher Export Kasten',
			'sales_price' => (float) 0,
			'purchase_price' => (float) 0,
			'refund' => (float) 3.5,
			'active' => true,
			'no_fixed_price' => false,
			'log' => '',
			'created' => null,
			'modified' => object(Cake\I18n\Time) {

				'time' => '2015-09-20T02:23:10+0200',
				'timezone' => 'Europe/Berlin',
				'fixedNowTime' => false
			
			},
			'article_category_id' => (int) 3,
			'_joinData' => object(App\Model\Entity\Contain) {

				'article_id' => (int) 4,
				'id' => (int) 1,
				'amount' => '20',
				'contained_article_id' => (int) 1,
				'[new]' => false,
				'[accessible]' => [
					'*' => true
				],
				'[dirty]' => [],
				'[original]' => [],
				'[virtual]' => [],
				'[errors]' => [],
				'[repository]' => 'Contains'
			
			},
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => 'ChildArticles'
		
		}
	],
	'[new]' => false,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Articles'

}
```

The _joinData is correct, but the fetched Article is wrong.

Checking the Sql-Queries, i found the error. First the main-Article is fetched with its own Query, then all "ChildArticles" connected with the main-Article are fetched. The complete Query is correct, except for the ON-statement of the inner-join. The wrong Query:

```
SELECT 
  Contains.article_id AS `Contains__article_id`, 
  Contains.id AS `Contains__id`, 
  Contains.amount AS `Contains__amount`, 
  Contains.contained_article_id AS `Contains__contained_article_id`, 
  ChildArticles.id AS `ChildArticles__id`, 
  ChildArticles.name AS `ChildArticles__name`, 
  ChildArticles.sales_price AS `ChildArticles__sales_price`, 
  ChildArticles.purchase_price AS `ChildArticles__purchase_price`, 
  ChildArticles.refund AS `ChildArticles__refund`, 
  ChildArticles.active AS `ChildArticles__active`, 
  ChildArticles.no_fixed_price AS `ChildArticles__no_fixed_price`, 
  ChildArticles.log AS `ChildArticles__log`, 
  ChildArticles.created AS `ChildArticles__created`, 
  ChildArticles.modified AS `ChildArticles__modified`, 
  ChildArticles.article_category_id AS `ChildArticles__article_category_id` 
FROM 
  articles ChildArticles 
  INNER JOIN contains Contains ON ChildArticles.id = (Contains.article_id) 
WHERE 
  Contains.article_id in ('4')
```

# Solution?
The Join should look like this:
```
  INNER JOIN contains Contains ON ChildArticles.id = (Contains.contained_article_id) 
```
so my specified targetForeignKey is not used. I verified, that not the foreignKey is used, so probably it is generated from the model-name directly? It's not an issue with the Table->get() function alone. i'm getting the same wrong query with this construction:
```
$article = $this->Articles->find()->contain(['ChildArticles'])->where(['Articles.id' => $id])->first();
```

btw: the other way round(fetching all ParentArticles) is working out of the box. but only probably because the targetForeignKey is the correct default name "article_id"...

I started with cakephp 3 some days ago and haven't dug so deep in the core to figure out where i should start searching. Whether it is in the "Cake\Database"-namespace or in the mysql-specific part? i don't know.

i'm using 3.0.13 with the connection to a mysql-server

thanks in advance! Despite this little bug, the new ORM is so awesome!!! especially the matching() function :D

**Comment by markstory** [comment]
The belongsToMany queries are generated inside `Cake\ORM\Association\BelongsToMany::attachTo()`. That methods appears to be using `targetForeignKey()` correctly. The issue could also be coming from how the associations on `Contains` are being defined in `Cake\ORM\Association\BelongsToMany::junction()`.

Does your `Contains` table class define any associations?

**Comment by schrolli** [comment]
Yes, here they are:

```
$this->belongsTo('ParentArticles', [
	'className' => 'Articles',
	'foreignKey' => 'article_id',
	'joinType' => 'INNER'
]);
$this->belongsTo('ChildArticles', [
	'className' => 'Articles',
	'foreignKey' => 'contained_article_id',
	'joinType' => 'INNER'
]);
```

But testing with these associations commented out just has the same problem...

I checked `BelongsToMany::junction()` with some debug-echoes and all is setting up correctly. The joinTable `Contains` gets its two associations and the correct foreignKey `contained_article_id` for its `hasMany` assoc `ChildArticles`.

`BelongsToMany::attachTo()` isn't even called.

**Comment by markstory** [comment]
Ah yes, I was wrong about attachTo(). That is only used in the subquery loading strategy. The default strategy is select which will call `ORM\Association\SelectableAssociationTrait::eagerLoader()` and `BelongsToMany::_buildQuery()`. The `BelongsToMany::_linkField()` method looks like it might be the culprit of this issue, but I've not had a chance to verify that.

**Comment by schrolli** [comment]
yea, so `options['foreignKey']` holds the wrong key, namely `article_id`. I couldn't find a key in the options, which would hold the `targetForeignKey`... I found it in the `$this->_targetForeignKey` property, but i do not understand `_linkField()` into detail to tell if that is a good idea. In my Test-action `_linkField` get called two times with the same options array from _buildQuery. I didn't get where the options array comes from and if there should be an additional `targetForeignKey`-key or if `foreignKey` should have the `contained_article_id`-value...

**Comment by markstory** [comment]
Ok, thanks for looking at this, I'll try to reproduce this issue locally and see if I can come up with a solution.

**Comment by schrolli** [comment]
thanks!

**Comment by markstory** [comment]
I don't think I fully understand the problem as I wasn't able to reproduce it. I created a test database, with 2 tables (items, and contains). In these tables, I put the following data:

```sql
mysql> insert into items (title, created, modified) values ('first', now(), now()), ('second', now(), now()), ('third', now(), now());
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> insert into contains (item_id, contained_item_id) values (1, 2), (1, 3);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0
```

I defined only a single model with only the child/parent associations

```php
class ItemsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('items');
        $this->displayField('title');
        $this->primaryKey('id');

        $this->belongsToMany('ChildItems', [
            'className' => 'Items',
            'through' => 'Contains',
            'foreignKey' => 'item_id',
            'targetForeignKey' => 'contained_item_id'
        ]);
        $this->belongsToMany('ParentItems', [
            'className' => 'Items',
            'through' => 'Contains',
            'foreignKey' => 'contained_item_id',
            'targetForeignKey' => 'item_id'
        ]);
    }
}
```

The following code retrieves the correct data:

```php
$t = \Cake\ORM\TableRegistry::get('Items');
$e = $t->get(1, ['contain' => ['ChildItems']]);
```

And the correct query is generated:

```sql
SELECT `Contains`.`contained_item_id` AS `Contains__contained_item_id`, `Contains`.`item_id` AS `Contains__item_id`, `Contains`.`amount` AS `Contains__amount`, `ChildItems`.`id` AS `ChildItems__id`, `ChildItems`.`title` AS `ChildItems__title`, `ChildItems`.`created` AS `ChildItems__created`, `ChildItems`.`modified` AS `ChildItems__modified`
FROM `items` `ChildItems`
INNER JOIN `contains` `Contains` ON `ChildItems`.`id` = (`Contains`.`contained_item_id`)
WHERE `Contains`.`item_id` in ('1')
```

Have you tried removing the associations defined on the Contains table?

**Comment by schrolli** [comment]
hm... now i don't know any further... now, it's working....

the only difference between your and my setup was, that i have the ContainsTable and ContainsEntity-files in place. I renamed them to have them out of my way and loaded the test-action and now the correct inner-join on-clause is built... and even after moving back the `Contains`-Model files, all is working. what could have aroused that? caching? I have debug on in my app-config and didn't tweaked something on the caching directives.

Sorry that i have consumed your time. So this issue can be closed, i think...

**Comment by markstory** [comment]
If you figure out how to reproduce the issue, post back and we can re-examine the issue.
