### ISSUE TITLE
3.x Set Log scope globally

### ISSUE THREAD

**Issue by btaens** [cakephp/cakephp#7443]
Hello,
I think it would be useful to be able to set something like `Log::scope('purchases')`.
This way, we could separate log files based on which part of our app is being run.
In my example, I run a Ratchet WebSocket server through a Shell.
If I could set `Log::scope('websocket')`, it could set any future `Log::write()` command's scope to be websocket unitl I reset scope to default, and it could also log errors to said scope.

I could technically do it by `Log::drop()` in my bootstrap file and later reactivate the websocket config and drop the others, but the Log config is consumed in bootstrap, and I would have to modify it every time I want to add a new logger. I think setting scope globally would be a simpler and more intuitive way of doing it.

**Comment by lorenzo** [comment]
I think what you are looking after is having a custom LogEngine that is capable of accepting this kind of configuration, and that you can inject using configuration depending on what part of the application you are at.

**Comment by markstory** [comment]
> If I could set Log::scope('websocket'), it could set any future Log::write() command's scope to be websocket unitl I reset scope to default, and it could also log errors to said scope.

To me this infers that there is hidden global state. I'd really like to avoid this kind of thing as it makes code comprehension much harder.

**Comment by btaens** [comment]
An alternative solution could possibly be deactivating and reactivating logs? Like `Log::disable('websocket')` then later `Log::enable('websocket')`.

**Comment by markstory** [comment]
Does `websocket` map to a logger name or a scope in that code?

**Comment by btaens** [comment]
WebSocket throws errors. Specific lines I want to write to the log I can just set the scope when I do, but I mainly want to capture the thrown errors in that specific Shell script, because I want to see the errors thrown by Ratchet.

Though, now that you mention it, I could just do a try-catch block around the server instantiation. Huh.
Though a disable function might still be useful.

**Comment by dereuromark** [comment]
Can we close this as works-for-me as a possible solution has been pointed out.
