### ISSUE TITLE
3.1: "year" form field not detected as datetime part

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7444]
MySQL `YEAR(4) default null` field shows up as textarea instead of dropdown year select (part of DateTime widget).
I think since the manual way works, the FormHelper's schema auto-detection should also reflect this.

Also, unknown field types should better show up as text instead of textarea IMO.

**Comment by lorenzo** [comment]
Only mysql supports YEAR as a type. How do you think we should address this?

**Comment by dereuromark** [comment]
Sounds like this would be a similar issue like enum support for MySQL.
What alternatives can the documentation point out to use?

**Comment by markstory** [comment]
We don't support lots of non-portable types. This feels like just the thing that we implemented custom schema types for.

**Comment by markstory** [comment]
> Also, unknown field types should better show up as text instead of textarea IMO.

This sounds like a pretty reasonable change to make in FormHelper.

**Comment by jhli** [comment]
Input text sounds good.

**Comment by dereuromark** [comment]
I managed to use a custom YearType class, but I had to make the following core change:
https://github.com/cakephp/cakephp/compare/master-mysql-year

**Comment by dereuromark** [comment]
If no one beats me to it, I can add the default text fallback as we discussed.

**Comment by dereuromark** [comment]
So we will not be supporting https://github.com/cakephp/cakephp/compare/master-mysql-year then?

**Comment by markstory** [comment]
@dereuromark I don't think anyone said that explicitly. I don't think there was ever a pull request for those changes. Personally I never use `YEAR` columns so them not working doesn't effect me :smile:

**Comment by dereuromark** [comment]
I also don't expect for importing legacy or having crud interim code. So it might be worth to at least support it basically.

**Comment by markstory** [comment]
MySQL has a pile of non-standard types. I'm not sure we should add support for all of them.

**Comment by ravage84** [comment]
I only found this related issue:
https://github.com/cakephp/cakephp/issues/1779

And this partly related issue:
https://github.com/cakephp/cakephp/issues/1982#issuecomment-26173322

**Comment by dereuromark** [comment]
I am also meeeh, but if it is a low hanging fruit to support it it might be worth it.
In the end, the only important thing to support is the ORM layer, because here we could deal with importing from legacy systems.
If the frontend (forms) don't work fine, that is acceptable IMO.

**Comment by dereuromark** [comment]
Final PR open.
