### ISSUE TITLE
3.1: Custom (plugin) View class regressions

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7452]
With the upgrade to viewBuilder() calls there is a regression in the way (plugin) View classes can be loaded.

Inside the action:

    $this->viewClass = 'Ajax.Ajax';

is now

    $this->viewBuilder()->className('Ajax.Ajax');

But the RequestHandler always overwrites and it ends up to be Json view again.

I managed to fix those issues - see https://github.com/cakephp/cakephp/compare/master-view-class-fixes#diff-025d59b0b75625e9fd100cc44fae82f7R550
I still got the issue, that the templatePath is not properly built:

    Error: [Cake\View\Exception\MissingTemplateException] Template file "ajax\.ctp" is missing.

    'file' => 'ajax/.ctp',

It should be

    'file' => 'AjaxExamples/ajax/country_provinces_ajax.ctp',

Side-note:
I don't think the request handler should also set the layoutPath:

    $builder->layoutPath($type);

It would be better to leave it null, and if null the view class can then set its default value.
Right now I end up with `AjaxExamples/json` right away. And that probably leads to the unset path.

**Comment by markstory** [comment]
I think RequestHandler has to set the layoutPath or subdirectory templates for extensions won't work.

**Comment by dereuromark** [comment]
In either way people experience now a regression with using custom (plugin) views and the view class variables set. My fixes above only make RequestHandler not break it, it does not yet solve the issue around the missing view variables.

**Comment by markstory** [comment]
What does the `Ajax.Ajax` view look like? Is `renderAs()` being called with `ajax`?

**Comment by dereuromark** [comment]
With the above RequestHandler changes, the Ajax View is called (and not overwritten by Json View). But the view variables are not set as expected.

**Comment by dereuromark** [comment]
![debug_1](https://cloud.githubusercontent.com/assets/39854/10148005/6fc13dc2-6631-11e5-9d13-9a8cde8cdce2.PNG)
and
![debug_2](https://cloud.githubusercontent.com/assets/39854/10148012/73c529f6-6631-11e5-8f56-031773f332f7.PNG)
show that $this->template is not properly set and thus it cannot find the template it used to find.

**Comment by markstory** [comment]
Ok. It looks like both the properties have values defined in the data passed into the view constructor though.

**Comment by ADmad** [comment]
@dereuromark  The problem is you haven't updated [$_passedArgs](https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L29) in your View class to include `'template'` and `'templatePath'`.

**Comment by dereuromark** [comment]
That fixes almost the problem, it now looks for

    'AjaxExamples\\json\\ajax\\country_provinces_ajax'

The json too much I was talking earlier. As it gets appended too soon IMO.

**Comment by ADmad** [comment]
The problem with template path is because you are setting [$this->subdir](https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L66) which gets appended to `templatePath`. Don't set it and just modify `$this->templatePath` since it already includes sub folder.

`View::$subdir` looks like a relic of 2.x to me since now the subdir always get directly appended to `View::$templatePath`, but that's a separate issue.

**Comment by dereuromark** [comment]
@ADmad I tried that, without the suffix setting and the template streplace fix it will simply just look for the concatenated string I showed above:

    AjaxExamples\\json\\ajax\\country_provinces_ajax

So this is not related to the subdir relict, at least not itself.

**Comment by ADmad** [comment]
Well of course you will need to modify `$this->templatePath` since it already includes sub directory `/json`. Request handler detected your request type as `json` and set the default path for you like it's supposed to. So if you don't want that path you need to modify it in your View class.

**Comment by markstory** [comment]
Do the changes in #7479 resolve this issue?

**Comment by dereuromark** [comment]
Apart from the manual templatePath joggle that is necessary now, yes.
If that part is an intentional and acceptable small BC break, then this is all good now.

**Comment by markstory** [comment]
@dereuromark What is the templatePath joggle that is necessary? Is the templatePath being manipulated in RequestHandler too early?

**Comment by dereuromark** [comment]
Sth like https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L67-L68 to restore old behavior.
Or completely generating it from the available vars.
But no big deal.
