### ISSUE TITLE
Duplicate entry on INSERT for concurrent database sessions

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7458]
I'm jumping right to the case:

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9f70oia4imp4uiuvfntf4c7770' for key 'PRIMARY'
```

Using CakePHP 2.6.8, the error is thrown from Model.php line 1928:
```php
if (!$db->create($this, $fields, $values)) {
```

Right up until the point of the `db->create()` call, every `find()` query returns nothing on that ID. I.e., it *should not* exist, but it does.

This leads me to all but one fix:

```php
try {
    if (!$db->create($this, $fields, $values)) {
        $success = false;
    } else {
        $created = true;
    }
} catch (PDOException $e) {
  if (isset($e->errorInfo[1]) && $e->errorInfo[1] === 1062) {
    /* perform UPDATE instead */
  }
  throw $e;
}
```

The `1062` is PDO's error code for DUPLICATE ENTRY.

Performing an UPDATE in the catch-block fixes the errors.

Before you say anything: This has nothing do to with model cache, db cache or any other caching. This is not a bug, but it should be fixed anyways.

The `$exists` variable in `_doSave()` is set very early on. This gives room for another thread that inserts the session before `create()` gets called.

If the try-catch block is not your cup of tea, then you **must** wrap the _doSave in a table lock.

**Comment by markstory** [comment]
Is this related to database sessions?

**Comment by davidsteinsland** [comment]
Yes.

**Comment by ADmad** [comment]
> If the try-catch block is not your cup of tea, then you must wrap the _doSave in a table lock.

2.7 already uses transaction for save() too.

**Comment by davidsteinsland** [comment]
@ADmad why isn't this backported to 2.6? 2.7 is not BC with 2.6, in my view it should really be backported.

**Comment by davidsteinsland** [comment]
Pretty useless having BC-breaking features in a minor build. Remember that upgrading is not always a dance in the park. It cost time and money, and important fixes like these should be backported.

**Comment by davidsteinsland** [comment]
PS. The bug exists i 2.7.3 also. So you did not fix it.

**Comment by ADmad** [comment]
> 2.7 is not BC with 2.6

It is.

**Comment by ADmad** [comment]
> Remember that upgrading is not always a dance in the park. It cost time and money, and important fixes like these should be backported.

Backporting fixes is not always a dance it the park either. It also costs time and effort we don't even get paid for it :)

**Comment by dereuromark** [comment]
@davidsteinsland The recommended approach is to always upgrade to latest minor version of the major version anyway. So you should be using 2.7 since it became stable.

**Comment by markstory** [comment]
> PS. The bug exists i 2.7.3 also. So you did not fix it.

Ok, then lets fix it there. Is there a way someone could reproduce the conditions that cause this error?

**Comment by davidsteinsland** [comment]
All I know is that it is spawning from `session_write_close` and the session exists in DB, but every call to `find()` or `exists` yield nothing. I also suspect that `session_write_close` gets called twice.

The action in question is sending a file response.

https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Network/CakeResponse.php#L1462

**Comment by jippi** [comment]
wrap your session in a serialized transaction :) or don't use database sessions 

99/100 of the cases where i see this issue, its due to a 404 or other internal error in a sub-request causing havoc

**Comment by davidsteinsland** [comment]
Eh, what? DatabaseSession are supported in the core of CakePHP, and I have no control over it in my application. It should just work. If not, what's the point?

**Comment by davidsteinsland** [comment]
I can now confirm that commenting out the `session_write_close` call in `CakeResponse::_sendFile` fixes the issue. Why is this even called?

**Comment by davidsteinsland** [comment]
It was introduced in 2013 with no tests whatsoever:
https://github.com/cakephp/cakephp/commit/ab96ed56f34b5b88c5b50f17956154bec7507a96

Funny thing. If I remember correctly, it was just after this commit things started happening in our applications: #2801 and #2808 

You should really be more reluctant about what you are merging in …

**Comment by rchavik** [comment]
> Why is this even called? 

Ref: https://github.com/cakephp/cakephp/pull/2219

**Comment by markstory** [comment]
Interesting. if sending the file is writing the session, why can't the shutdown function see the row? I would expect those two operations to be in separate transactions, and thus be able to see the data.

I tried a very naive setup using a new clone of 2.7. I setup database sessions, put some data into the session, and had a separate action that looked like:

```php
	public function files() {
		$this->autoRender = false;
		$this->response->file(ROOT . '/composer.json', ['download' => false]);
	}
```

I didn't see any PDO errors in either the app logs, apache logs or on screen. I feel like I must be missing something to reproduce this issue.

**Comment by davidsteinsland** [comment]
I haven't been able to isolate and reproduce it, but I'm not too far away. In the meantime, here's how you trigger it:

- Configure database sessions
- `Controller/UsersController`
```php
<?php
App::uses('AppController', 'Controller');

class UsersController extends AppController {
	public $components = array(
		'Auth'
	);

	public function beforeFilter() {
		/* Trigger session start */
		CakeSession::write('foo', 'bar');
		$this->Auth->allow('thumbnail');
	}

	public function thumbnail() {
		$this->response->file(__FILE__);
		return $this->response;
	}
}
```
- `Model/Session.php`:
```php
<?php
App::uses('AppModel', 'Model');

class Session extends AppModel {

	public function exists() {
		return false;
	}
}

```

The Session model is a hack to trigger the error, since I haven't been able to reproduce it yet. However, it is exactly what happens in my apps. `exists()` returns false, even when the session exists in the db.

**Comment by lorenzo** [comment]
The session needs to be closed before sending a file because it is a potentially time consuming operation. That means that we need to store the info and release the lock, if any, as soon as possible

**Comment by davidsteinsland** [comment]
@lorenzo At that point, the session should not be locked. CakeSessions are implemented as lazy, so that function call should not be needed.

On another note, now I'm able to spawn the PDOException in SecurityComponent::blackHole as well.

![screen shot 2015-09-28 at 08 27 13](https://cloud.githubusercontent.com/assets/125661/10129123/f2ecd6ce-65ba-11e5-824a-e8ab5c0c592d.png)

**Comment by lorenzo** [comment]
The concurrency problems of the session are a known problem, specially when dealing with too fast ajax requests. Limiting the calls for `session_wite_close` is not a solution. The real solution would be to use some sort of `UPSERT` in the model, but I'm not sure the code in 2.x is actually ready for that.

**Comment by markstory** [comment]
The [DatabaseSesssion](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/Session/DatabaseSession.php#L125-L129) attempts to handle the duplicate key issue, but with exists() always returning false, even that code will fail.

**Comment by garethellis36** [comment]
Hi

Our application has just switched from file to DB sessions (we're on 2.10) and we have started getting this error in our logs:

`PHP Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a7eb8d083abf80df681a43fef9ae47e1' for key 'PRIMARY' in C:\inetpub\itrans\versions\20190908181659_build_1329\app\Vendor\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php:502`

I take it the original bug mentioned in this issue was never resolved?

**Comment by markstory** [comment]
I don't think we found a way to reproduce the problem.
