### ISSUE TITLE
Adding save strategy for HasMany Associations

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#7462]
Hello,
I would like to discuss about this. To maintain backwards compatibility, we should keep the default strategy to keep, but also allow the data to be replaced.
It could be a new option to be set in the association definition.
This would be better than having to manually delete records first and would let the application code less "noisy".
I would like to have feedback about this. I could implement it and make a pull request if it is acceptable.

Thanks.

**Comment by markstory** [comment]
So are you imagining a replace/append saveStrategy like BelongsToMany has?

**Comment by mylux** [comment]
Exactly, @markstory

**Comment by markstory** [comment]
Seems useful to me. An append mode could be useful if an association has a huge list and you don't want to hydrate the whole list just to add one new object.

**Comment by mylux** [comment]
That could be a good idea as well.
Why do you think it should only be deployed into 3.2.0 and not for 3.0?

**Comment by markstory** [comment]
We're not doing any more releases of 3.0, but it could go into a 3.1.x release.

**Comment by mylux** [comment]
If I had to choose, I'd rather 3.1, unless you have any specific reason to let this for 3.2

**Comment by markstory** [comment]
As currently described, this change fits under the net new minor feature with no backwards compatiblity implications we aim for in features that target patch releases.

**Comment by mylux** [comment]
Sorry dude, I didn't get what you just said.

**Comment by markstory** [comment]
Adding the new save strategy into 3.1.x is fine :+1:

**Comment by mylux** [comment]
Alright, then. I have already coded this change. I just need to add some tests and then I can send a PR for you to check.
Could you assign this issue to a 3.1.x release?
Thanks

**Comment by lorenzo** [comment]
Closing as there is a pull request open
