### ISSUE TITLE
Plural of virus isn't really viri

### ISSUE THREAD

**Issue by etfb** [cakephp/cakephp#7466]
I'll quote chapter and verse from a dictionary if required, though I don't think it should be necessary. lib/Cake/Utility/Inflector.php in the latest 2.x build (apparently in 3.x too) includes "virus" as one of the words that has its "us" changed to "i". It should be left out of the regexp (line 50, starting with '/(alumn|bacill|cact' etc) since the correct English plural of virus is viruses, so will be caught by the catch-all on line 51.

Here's a polite explanation of the error: http://dictionary.reference.com/help/faq/language/g63.html

Apropos of nothing: I love that this file exists, and that it's so comprehensive. Oxen! Testes! Lice! Someone has gone to a lot of trouble, and appears to have had a lot of fun. Excellent work all round!

**Comment by markstory** [comment]
This is also an issue in 2.x. I can fix it in both branches.

**Comment by markstory** [comment]
Fixed in 2.7 and master branches.
