### ISSUE TITLE
Deprecation Workarround Failure: ViewBuilder does not have a method name view()

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#7468]
Part of the deprecation workaround logic for the "magic" controller properties `$layout`, `$view` etc. is to call the method of the same name in the view builder in the controller's `__set()`method. This is done for the following properties: `['layout', 'view', 'theme', 'autoLayout', 'viewPath', 'layoutPath']`.

The class `ViewBuilder` has method of the same name, **except** for *view* and *viewPath*, the matching methods are called *name* and *templatePath* (?)

In the current version the "fix" creates a fatal error (happened to me after upgrade to 3.1)

**Comment by nrother** [comment]
Ok, the correct partner for *view* is *template*, not *name*.

I'm not quite sure what *name* is for, the method's comment says "The name of the view", the property's "The view variables to use" (which is also the comment for `$_className` and `$_options`, but that might be another issue). In the class `View` it's commented as "name of the controller", but never used.

**Comment by markstory** [comment]
I can update the deprecation warnings to suggest the correct methods.

**Comment by markstory** [comment]
I've updated the error messages and fixed the documentation errors I could find in #7475.
