### ISSUE TITLE
Form templates don't merge attributes

### ISSUE THREAD

**Issue by mfrascati** [cakephp/cakephp#7470]
I'm experiencing some problems with form templates; I defined a custom one for textareas
```php
'textarea' => '<textarea name="{{name}}" class="form-control"{{attrs}}>{{value}}</textarea>',
```

then I'd like to add another class via the input
```php
$this->Form->input('my_textarea', ['class' => 'autosize']);
```

but this 'class' attribute is discarded and not merged, nor overwritten. What should be a good approach for handle this kind of situation? Of course I'm not defining the class in the template because I don't need it on every textarea...

For now the best I came up with is using templateVars, defining a custom {{class}} var

```php
'textarea' => '<textarea name="{{name}}" class="form-control {{class}}"{{attrs}}>{{value}}</textarea>',
...
$this->Form->input('my_textarea', ['templateVars' => ['class' => 'autosize']]);
```
it works, but it doesn't look a clean approach to me. Any suggestions? Thanks

**Comment by markstory** [comment]
templateVars is how I would do it too.
