### ISSUE TITLE
Missing restore_exception_handler

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7472]
Missing `restore_exception_handler` here:
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Core/Configure.php#L99

**Comment by markstory** [comment]
How does this manifest as an issue?

**Comment by davidsteinsland** [comment]
Try setting `Exception.handler` to null, in order to use PHP's.

**Comment by markstory** [comment]
Ok, but why would you do that? PHP's default behavior is generally pretty undesirable.

**Comment by markstory** [comment]
Closing as its been a while with no follow up.
