### ISSUE TITLE
Collection::Extract broken?

### ISSUE THREAD

**Issue by RaXaR** [cakephp/cakephp#7473]
Using CakePHP 3.1.0
I can't seem to get Collection::extract() to work with even a simple Parent/Child relationship. Try with a Group/Users setup for instance. If I extract('name'), then I get the group names,  if I try extract('users.name') I get incorrect results. I've tried using {n} and {*}, still fails. I tried using camelCase and I've mixed a bunch of these. All failed.

**Comment by markstory** [comment]
There are a bunch of tests showing it working, so it does work. What does your data structure and extract call look like?

**Comment by RaXaR** [comment]
DB Table structure is here [Pastebin](http://pastebin.com/z1naLTQ1)
Here is some code I put into a controller method:
```
        // The test data has 2x Groups with 2x Companies 
        // associated with each. (4x Companies total)
        $t = TableRegistry::get('Groups')
            ->find('all')
            ->contain(['Companies' => function($q){
                return $q->select(['id', 'group_id', 'name']);
            }])
            ->select(['id', 'name'])
            ;
        debug($t->toArray());
        debug($t->extract('name')->toArray()); // This works fine.
        debug($t->extract('companies.name')->toArray());
        debug($t->extract('companies.{n}.name')->toArray());
        debug($t->extract('companies.{*}.name')->toArray()); // This gives the wrong number of results.
        exit();
```

**Comment by lorenzo** [comment]
You need to use `toList()` as shown in the documentation, as you will get duplicate keys for  the extracted elements... When converted to a PHP array, the duplicate keys will be collapsed as a single element. To avoid this gotcha, use `toList()`

**Comment by RaXaR** [comment]
I really didn't see an instance of using toList() in the docs, if it's there then apologies, I must've overlooked it, if not then can you please add it. Thanks again.

**Comment by RaXaR** [comment]
Still a problem, in the code above, I changed all instances of "toArray()" to "toList()". The following still failed:
```
debug($t->extract('companies.{n}.name')->toList());
```
Is this expected/correct?

**Comment by lorenzo** [comment]
No, it is not. Please check the docs for the function
