### ISSUE TITLE
Shared core

### ISSUE THREAD

**Issue by scofield-ua** [cakephp/cakephp#7474]
Hello. I have a question for you guys. Is it possible to have one core files folder for multiple apps (like it was in CakePHP 2)?

Something like this (files structure):
/cores/cakephp-3 (core files here)
/example.com (website 1)
/example2.com (website 2)

Or I need just copy (with composer) core files for every website.

**Comment by dereuromark** [comment]
You should not have done that in 2.x either.
Use composer and do not mix multiple apps with one core. Mixing vendors is usually a ticking timebomb.

**Comment by markstory** [comment]
Possuble, but not worth the effort. We don't support shared libs any more as an install method, but can't stop you if you are determined :-)

**Comment by scofield-ua** [comment]
Thanks, I just wanted to hear official answer.

**Comment by scofield-ua** [comment]
@dereuromark ok, you said that I should not, but here is quote from [docs](http://book.cakephp.org/2.0/en/installation.html#using-one-cakephp-checkout-for-multiple-applications)
>If you are developing a number of applications, it often makes sense to have them share the same CakePHP core checkout.

**Comment by ADmad** [comment]
@scofield-ua The manual section you have linked is for Cake 2.x not 3.x.

**Comment by ADmad** [comment]
Sorry I see you are referring to @dereuromark's comment which was regarding 2.x.

**Comment by dereuromark** [comment]
I think that sentence is from way before composer was the de facto standard, so probably early 2.x versions. It can be removed IMO.

**Comment by ravage84** [comment]
Yep, I think we should not (officially) support and document this anymore. Not even for 2.x anymore.

**Comment by markstory** [comment]
If someone could make the docs change, I'll be happy to merge it.
