### ISSUE TITLE
3.1: missing Cake\Database\StatementInterface::fetchColumn

### ISSUE THREAD

**Issue by adael** [cakephp/cakephp#7478]
I miss a lot this function.
Reference: http://php.net/manual/es/pdostatement.fetchcolumn.php

In tables I would like execute simple queries like this:

```
public function hasTag($article_id, $tag_id)
{
    return $this->connection()->execute("
        SELECT count(*) FROM article_tag 
        WHERE article_id = ? AND tag_id = ?
    ", [$article_id, $tag_id])->fetchColumn();
}
```

Perhaps it's there a simpler way to do this with Table relationship but I cannot figure out.

**Comment by markstory** [comment]
You can do the same thing with `$stmt->fetchRow()[0]`

**Comment by dereuromark** [comment]
Is there something to be done here for e.g. 4.x.?

**Comment by markstory** [comment]
Looks like `fetchColumn` was added in #11886
