### ISSUE TITLE
3.1 Request shows controller in lowercase when using prefix route

### ISSUE THREAD

**Issue by bravo-kernel** [cakephp/cakephp#7480]
Cake 3.1 Request is giving me lowercased controller name where I expected these to (always) be uppercased. My `$request->params`:

```
    [plugin] => 
    [controller] => countries
    [action] => index
    [_ext] => 
    [pass] => Array
        (
        )

    [prefix] => editor
    [isAjax] => 
```

I'm using Cake 3.1 with a plain basic prefixed route:

```php
    // Create nested prefix used by the Editor
    $routes->prefix('editor', function ($routes) {
        $routes->connect('/:controller');
        foreach (API_RESOURCES as $apiResource) {
            $routes->resources($apiResource, [
                'inflect' => 'dasherize',
        }
    }
```

Also tested without the foreach loop and without the dasherized inflection, still lowercase.

**Comment by dereuromark** [comment]
I agree that this should be consistent througout the framework to make comparison and working with the values easier.

**Comment by ADmad** [comment]
@bravo-kernel This occurs only for prefixed routes?

**Comment by ADmad** [comment]
@bravo-kernel What the value of `API_RESOURCES` constant?

**Comment by bravo-kernel** [comment]
The constant is an array with controller names @ADmad:

```php
const API_RESOURCES = [
    'Countries',
    'Currencies',
    'Users'
];
```

And yes, this only happens in the prefixed route, using most basic AppController, the show request params dumped during `initialize()`

**Comment by ADmad** [comment]
That looks fine. I checked in my app and for url with prefixed route the controller name is camel cased in request params as expected.

**Comment by bravo-kernel** [comment]
Hmmm, must be a bug somewhere in my app then.

- the URL `http://api.ecloud.app/editor/countries` shows up lcase in request params
- the URL `http://api.ecloud.app/editor/Countries` shows up ucase in request params

Thanks for looking into it, at least I know I won't be hunting down a mirage.

**Comment by markstory** [comment]
I wasn't able to reproduce this either. I added

```php
Router::prefix('editor', function ($routes) {
    $routes->connect('/:controller');
    foreach (['Countries', 'Currencies'] as $apiResource) {
        $routes->resources($apiResource, [
            'inflect' => 'dasherize',
        ]);
    }
});

```

to my `routes.php`

```shell
$ bin/cake routes check /editor/countries

Welcome to CakePHP v3.1.0 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.5.27
---------------------------------------------------------------
+-------------------+-------------------+---------------------------------------------------------------------------------------+
| Route name        | URI template      | Defaults                                                                              |
+-------------------+-------------------+---------------------------------------------------------------------------------------+
| _controller:index | /editor/countries | {"controller":"Countries","pass":[],"action":"index","prefix":"editor","plugin":null} |
+-------------------+-------------------+---------------------------------------------------------------------------------------+
```

**Comment by bravo-kernel** [comment]
Sorry, should have closed this. I will update once I find the root cause. Thanks again.

**Comment by bravo-kernel** [comment]
For the record... this was caused by me never updating the `defaultRouteClass`  in an old version of the app-skeleton. Changing the default route from `Route` to `DashedRoute` solved my troubles. Sorry for the disturbance and thanks for the help.
