### ISSUE TITLE
2.7.4 Unit tests HTML reporter broken

### ISSUE THREAD

**Issue by pdata** [cakephp/cakephp#7481]
On the latest 2.7.4, the unit tests when accessed via HTML are broken due to two variables not being set. This is fixable by reverting the changes made in lib/Cake/TestSuite/Reporter/CakeHtmlReporter.php to paintDocumentStart() and paintTestMenu() (commit ID 1ede742d926e3b8a060fcfb1a6dda2eb3e5c10c7).

**Comment by dereuromark** [comment]
Indeed, those occurrences should be changed back.

**Comment by markstory** [comment]
Fixed in 17c3358d772cd0459431105207e0041297bbbc70
