### ISSUE TITLE
3.1 - _serialize = true unexpected results 

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7482]
(From #6502)

Hey guys. With the way `_serialize=true` is working it doesn't seem possible to have it work when you have a single var.

```
$status = 1;
$this->set(compact('status') + ['_serialize' => true]);
```

If you do the above right now, you get this response, which isn't valid JSON:
```
1
```

However, if you have more than one var, it works as expected:
```
$status = 1;
$a = 'b';
$this->set(compact('status', 'a') + ['_serialize' => true]);
```

Returns:
```
{
    "status": 1,
    "a": "b"
}
```

The unexpectedness of that makes me think this is a bug, but it's possible that's as intended.

**Comment by ADmad** [comment]
Using `'_serialize' => true` with only one view var is considered equivalent to `'_serialize' => 'status'` hence the result you get is intended.

The problem is with a single view var set it's not possible to differentiate whether user meant `'_serialize' => 'status'` or `'_serialize' => ['status']`.

**Comment by patrickconroy** [comment]
Thanks @ADmad, that's what I figured was happening. But I think if I'd see multiple vars to behave one way then I'd expect a single var would behave the same way. I've never done `'_serialize' => 'status'` since to me it's simpler to know that anything I set/serialize is going to be in the JSON the same way...

**Comment by ADmad** [comment]
Fair enough, people can explicitly use `'_serialize' => 'status'` if they want the contents of a variable to be serialized and not have the variable name itself be used as key. I'll submit a patch.

**Comment by patrickconroy** [comment]
Thanks!
