### ISSUE TITLE
test.php is broken in 2.7.4

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#7486]
![screenshot from 2015-09-30 12 42 46](https://cloud.githubusercontent.com/assets/3392962/10191066/4f7ce656-6771-11e5-9f7f-ff7451bb78f0.png)

[This change](https://github.com/cakephp/cakephp/commit/1ede742d926e3b8a060fcfb1a6dda2eb3e5c10c7#diff-13c04ddad517ba05de14f47eccf17b51) (in `lib/Cake/TestSuite/Reporter/CakeHtmlReporter.php`) may be the cause

**Comment by ravage84** [comment]
Mea Culpa.
@markstory already fixed this in https://github.com/cakephp/cakephp/commit/17c3358d772cd0459431105207e0041297bbbc70

Gomenasai!

**Comment by tersmitten** [comment]
Thanks @ravage84

**Comment by markstory** [comment]
I'll be doing a 2.7.5 release tonight/tomorrow :smile:
