### ISSUE TITLE
Nested contain doesn't work across servers

### ISSUE THREAD

**Issue by plopzer** [cakephp/cakephp#7489]
In cake2 I could use containable to associate tables across servers like this and it would run seperate queries and stitch it together in php.

    class User extends AppModel {
        public $useDbConfig = 'server1';
        public $hasMany = array('Point');
    }
    class Point extends AppModel {
        public $useDbConfig = 'server2';
        public $belongsTo = array('Region');
    }
    class Region extends AppModel {
        public $useDbConfig = 'server1';
    }

    $this->User->find('all', array('contain' => array('Point' => array('Region'))));

But in cake3 when I try the same thing it tries to do a join in sql which obviously throws an error "Base table or view not found: 1146 Table 'server2.regions' doesn't exist".

    class UsersTable extends Table {
        public static function defaultConnectionName() {
            return 'server1';
        }
        public function initialize(array $config) {
            $this->hasMany('Points');
        }
    }
    class PointsTable extends Table {
        public static function defaultConnectionName() {
            return 'server2';
        }
        public function initialize(array $config) {
            $this->belongsTo('Regions');
        }
    }
    class RegionsTable extends Table {
        public static function defaultConnectionName() {
            return 'server1';
        }
    }

    $this->Users->find()->contain(['Points' => ['Regions']]);

It does work when you only go 1 level deep though

    $this->Users->find()->contain(['Points']);

**Comment by lorenzo** [comment]
You need to use the select strategy of you plan to get data across different connections.

**Comment by plopzer** [comment]
Oh, thanks. So cake isn't smart enough to determine when to use select or join?

**Comment by lorenzo** [comment]
It is not, but that is by design. Since you can actually force it to do joins if your database supports cross database communication

**Comment by plopzer** [comment]
Oh I see, if they were on the same host you could join them. Is it possible to specify the strategy in the relationship definition?

**Comment by lorenzo** [comment]
@plopzer in case you wanted to have joins, it is possible when running MySQL in the same server.

Instead of declaring a different connection name for your tables, just change the table name to contain the full name, like this:

    $this->table('my_database.my_table_name');

You can do that in the initialize method of your table class

**Comment by jhli** [comment]
@plopzer if this resolved it for you, could you add it to the book (cakephp/docs)?

E.g. On strategy in this case as well as cross database queries on mysql on the same server
