### ISSUE TITLE
[3.x] PaginatorComponent does not resolve finder option when Query object was passed

### ISSUE THREAD

**Issue by hiromi2424** [cakephp/cakephp#7492]
`finder` option for `PaginatorComponent` works fine when passed object was not `Query` object.
On the other side, `Query` object given it does not work.

Example here:
```php
class KeywordsController extends AppController
{

    public function index($keywordTypeId = null)
    {
        $this->Prg->commonProcess();
        $keywordType = $this->Keywords->KeywordTypes->get($keywordTypeId);
        $this->paginate = [
            'contain' => [],
            'finder' => [
                'keywordType' => compact('keywordType'),
            ],
        ];
        $query = $this->Keywords->find('searchable', $this->Prg->parsedParams());
        $this->set('keywords', $this->paginate($query));
        $this->set(compact('keywordType'));
        $this->set('_serialize', ['keywords']);
    }

}
```

Other options works fine e.g. `order`, `contain` and etc.
The solution of this now is only `$query->find()` directly.

Is it a bug or designed behavior?
I did not find any explanation of this in the [Book](http://book.cakephp.org/3.0/en/controllers/components/pagination.html#using-controller-paginate).

**Comment by lorenzo** [comment]
That was intentional, maybe we just need to add it to the book?

**Comment by markstory** [comment]
:+1: to this being intentional.

**Comment by markstory** [comment]
Docs pull request open now.
