### ISSUE TITLE
Database type classes should throw exception for objects

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#7494]
When providing an object  or array to any of the database Type classes, and the class does not know how to convert this object to the right representation, we should throw an exception.

I have run into a few problems where we were too friendly by converting anything to a string, for example an array.

It is not immediately obvious that the developer passed a wrong data type as often there is no SQL error.

**Comment by ADmad** [comment]
:+1: This would also help new users trying to use input with same name as db field for file uploads and wondering way the file array vanishes.

**Comment by markstory** [comment]
> When providing an object or array to any of the database Type classes,

The date, time, and datetime types need to allow arrays. However, I agree that string, integer, float, bool and other scalar types could fail more loudly.

**Comment by lorenzo** [comment]
This is for the toDatabase() method by the way, not for data mashaling from form

**Comment by markstory** [comment]
Oh. Then exceptions make alot more sense.

**Comment by ravage84** [comment]
:+1:

**Comment by Marlinc** [comment]
Great idea :+1: I can see this avoiding a lot of frustration.
