### ISSUE TITLE
Scaffold HTML Inputs for Postgresql numeric types in IE

### ISSUE THREAD

**Issue by pyrite357** [cakephp/cakephp#7497]
Internet Explorer (IE8 and IE11) won't let me submit a scaffold form that uses the Postgresql (8.4.20) numeric type in the backend when the values have a scale of 8 and a precision of 6. It complains with "You must enter a valid value", most likely due to the step attribute in the HTML. Setting scale or precision in the database seems to have no effect.

I have temporarily fixed (read: band-aid'ed) this by modifying the lib/Cake/View/Helper/FormHelper.php

```php
diff -aur cake273orig/lib/Cake/View/Helper/FormHelper.php cakephp/lib/Cake/View/Helper/FormHelper.php
--- cake273orig/lib/Cake/View/Helper/FormHelper.php     2015-08-23 21:22:27.000000000 -0500
+++ cakephp/lib/Cake/View/Helper/FormHelper.php 2015-09-29 11:29:02.513338106 -0500
@@ -1211,10 +1211,14 @@
                        ) {
                                if ($type === 'decimal') {
                                        $decimalPlaces = substr($fieldDef['length'], strpos($fieldDef['length'], ',') + 1);
-                                       $options['step'] = sprintf('%.' . $decimalPlaces . 'F', pow(10, -1 * $decimalPlaces));
+                                        if ($decimalPlaces == '') {
+                                               $options['step'] = 'any';
+                                        } else {
+                                               $options['step'] = sprintf('%.' . $decimalPlaces . 'F', pow(10, -1 * $decimalPlaces));
+                                        }
                                } elseif ($type === 'float') {
                                        $options['step'] = 'any';
-                               }
+                                }
                        }
                }


```

My fix probably isn't the best way, but it works. The issue probably lies in the Model's schema describing functionality, but I'm not an experience Cake core developer.

This is not a problem for me in Firefox, only IE. However, since the code is scaffolded, I think it is something that Cake should consider fixing, at least as long as you are offering Scaffold functionality.

This wasn't a problem on CakePHP 2.5.8, however it is on 2.7.3 and 2.7.4.

This may or may not be related to: https://github.com/cakephp/cakephp/issues/2164

**Comment by markstory** [comment]
What does the column definition that causes the issue look like?

**Comment by pyrite357** [comment]
It is the longitude/latitude columns in this table schema:

The values I'm using for example are:
latitude = 32.399506
longitude = -94.856071

```sql
CREATE TABLE equipment
(
  id serial NOT NULL,
  name character varying(75) NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  created timestamp without time zone,
  modified timestamp without time zone
 )
WITH (
  OIDS=FALSE
);
```

**Comment by pyrite357** [comment]
Didn't mean to close this? weird

**Comment by markstory** [comment]
Pull request up now.
