### ISSUE TITLE
Transports in "Network/Email" are deprecated, use "Mailer/Transport" instead

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#7502]
Hi,
I noticed this error in my error.log:

```
2015-10-02 12:35:13 Warning: Warning (512): Transports in "Network/Email" are deprecated, use "Mailer/Transport" instead. in [/home/damiano/app/vendor/cakephp/cakephp/src/Mailer/Email.php, line 1017]
```

**Comment by damianoporta** [comment]
(using Cake 3.1)

**Comment by antograssiot** [comment]
http://book.cakephp.org/3.0/en/appendices/3-1-migration-guide.html#email

**Comment by damianoporta** [comment]
@antograssiot I read it. But sounds weird that official release uses deprecated namespace. I did not say to remove it completly, only to upgrade the core because this warning is core related.

**Comment by antograssiot** [comment]
@damianoporta i might be wrong but I don't think that there's deprecated namespace usage in the release. You should probably check in your app (config/bootstrap and every places where you use email) as the app skeleton has been updated accordingly

**Comment by damianoporta** [comment]
@antograssiot @ADmad 
We should upgrade the doc http://book.cakephp.org/3.0/en/core-libraries/email.html#creating-custom-transports

I see the old namespace and the file should be in another location

from:
`src/Network/Email/ExampleTransport.php`
to:
`src/Mailer/Transport/ExampleTransport.php`

**Comment by ADmad** [comment]
@damianoporta Would you like to make a PR for the docs fixing it?

**Comment by markstory** [comment]
Docs fixed in cakephp/docs@4c3da1484ec150157c086149cb39c5a310b65418

**Comment by damianoporta** [comment]
@markstory thanks :)

**Comment by Oxicode** [comment]
thanks. Me había pasado lo mismo
