### ISSUE TITLE
SMTP mail via TLS over postfix (iRedMail) not working

### ISSUE THREAD

**Issue by vacuphase** [cakephp/cakephp#7505]
Hi guys,
I´m absolutely desperate I can´t get going my mail service :(
I have a standard installation of iRedMail 0.9.2 and CakePHP 3.1.
After setting up email data in app.php Cake shows me the error:
`SMTP server did not accept the connection or trying to connect to non TLS SMTP server using TLS.`

My mail setup in app.php:

    EmailTransport' => [
        'default' => [
            'className' => 'Smtp',
            // The following keys are used in SMTP transports
            'host' => 'smtp.domain.tld',
            'port' => 25,
            'timeout' => 30,
            'username' => 'blabla',
            'password' => 'blabla',
            'client' => null,
            'tls' => true
        ],
    ],

     'Email' => [
        'default' => [
            'transport' => 'default',
            'from' => 'blabla',
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ],
    ],

When I tell Cake `"tls => false"` and in postfix comment out `"smtpd_tls_auth_only=yes"` it works. But I don´t want to use the unsecure connection. Honestly I´m not sure if it´s a Cake- or a postfix-problem. iRedMail installs a self signed SSL certificate. Could this be the problem? Thanks

**Comment by markstory** [comment]
>  Honestly I´m not sure if it´s a Cake- or a postfix-problem. iRedMail installs a self signed SSL certificate. Could this be the problem? 

Yes. The current socket options disallow self-signed certificates. However, #7496 will add them. Going to close this as there is an open pull request that should resolve the self-signed certificate issue.

**Comment by vacuphase** [comment]
OK, thanks for clearing that up :)
