### ISSUE TITLE
I need examples of multilingual sites

### ISSUE THREAD

**Issue by vnt** [cakephp/cakephp#7507]
Hello,
There are examples to understand how to create a multilingual site with Cakephp 3?
With Saving in in db with Another Language and Saving Multiple Translations.
I hope you can help me.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
