### ISSUE TITLE
RFC - Move database Type classes to Datasource component

### ISSUE THREAD

**Issue by Marlinc** [cakephp/cakephp#7509]
I'd like to propose moving the database types to the `\Cake\Datasource` namespace and decoupling from the database.

The mean reasons for this being that converting things like integers, booleans, times, dates, etc... is not specific to databases. API's can return those types as well and being able to take advantage of types would be amazing.

I think this is kind of difficult as types are wired quite deeply into the Database and ORM components.

Here's some of the idea's I have for this change:
- For the `Driver` class being passed to the types I think its good to create a `DriverInterface` in `\Cake\Datasource`. This interface could for example contain a method that can return the format datasource specific types. For example: a `datetime` in field uses the `Y-m-d H:i:s` format. The type could ask the `Driver` the format supported for dates.
- In case of the `toStatement` method. I think its to expect most types to return a `string` type. In case of a type that returns something else it could be extended in the `\Cake\Database` containing database specific methods like `toStatement`.

**Comment by markstory** [comment]
Using PDO constants wouldn't make much sense in Datasources I don't think. Perhaps that's not important though, as most non-SQL datasources don't have as stringent requirements around data binding.

I'm not sure how a DriverInterface would work. Generally I wouldn't expect alternative datasources to be making drivers. Instead they'd be making Connection classes.

**Comment by Marlinc** [comment]
The UseMuffin/Webservice plugin for example uses ```Driver``` classes. It contains a general ```Connection``` which gets used by all webservices. A webservice would create a ```Driver```. That would provide the stuff related to that webservice.

**Comment by Marlinc** [comment]
What are the overall thoughts on moving the types to the ```Datasource``` component and my reasons why this would be useful?

**Comment by markstory** [comment]
I think moving them sounds reasonable at a highlevel. We'll need to add additional class aliases, so any existing extensions continue to work. But otherwise it sounds mostly like a code shuffle.

**Comment by Marlinc** [comment]
I'll open a pull request for this :smile:

**Comment by dereuromark** [comment]
Is this planned for 3.4 or 4.x?

**Comment by ravage84** [comment]
I guess, if we do this for 4.x, we do not *need* to do any class aliasing.

**Comment by markstory** [comment]
I don't know. I can see why folks might want to use them outside of a database context, but I would have expected more activity on this issue if it was a problem people faced in practice.

**Comment by ADmad** [comment]
I too see the value in having type classes for non-database datasource but have no actual need for it right now. So let's leave until somebody does require this and wants to implement the changes :slightly_smiling_face:.

**Comment by dereuromark** [comment]
Should we close this then?
