### ISSUE TITLE
Removing inline javascript and style in Core CakePHP to support Content Security Policy

### ISSUE THREAD

**Issue by TheFRedFox** [cakephp/cakephp#7511]
Hey guys,

I was just implementing some configurations for the new Content Security Policy (CSP) header to protect against XSS attacks. But there are some in built cakephp methods which uses or rather creates inline javascript and style.

For example the postLink method in the FormHelper, which creates javascript for the 'confirm' resp. 'submit' actions.

However I was able to change some parts ('FormHelper::postLink' and DebugKit variables) to support CSP. But I don't think I can find all places where changes have to be done. And these changes brings some naming conventions and js file(s) for data attributes resp. to separate the inline javascript code. And also for inline styles.

Surely I can show/commit my changes if it is wanted.
I hope this request wasn't done yet, I didn't find anything about CSP in the release infos for 3.1 and also no issue requesting this here.

Kind regards

**Comment by dereuromark** [comment]
Why are you using the FormHelper::postLink() and other inline JS tools then?
Just don't use them and your site will not have any such issues. You are free to use any other custom postLink() functionality to replace it with.
Does that solve your issues?

**Comment by josegonzalez** [comment]
I'd actually be +1 on this. More security is better for our users, and if it can be given to them for free, awesome.

**Comment by Marlinc** [comment]
I like anything that can improve overall security of the framework and applications using it.

**Comment by dereuromark** [comment]
@TheFRedFox How would your proposed changes for postLink() and alike look like? It would be best to show some actual code or open a PR with your suggested changes.

**Comment by markstory** [comment]
If we can provide CSP features without breaking compatibility, I'd be :+1: for it.

**Comment by TheFRedFox** [comment]
@dereuromark I am using FormHelper::postLink() because I think in built methods are supposed to be used. :P I know I can code my own custom methods, but it seems Content Security Policy is most probably the future main security policy. And for me CakePHP seems to be a lightweight but really modern framework and therefore I think CSP support would be really really nice for CakePHP. :wink: 
And for debug kit. Don't worry, the DebugKit is not running in production. But I have to check if my own things are working with the right CSP configurations in development, too. And in development I want to see the DebugKit Toolbar .. why? .. because it is awesome! :heart_eyes:

Just a few points for general changes for the guys who are interested:
* All inline javascript and style have to be separated in an own or existing js resp css files
* if inline javascript was dynamically created by php with some dynamic values, use the html data attribute to store these values and get them via javascript again (e.g. the confirm message in postLink)

As I said inline javascript code has to be separated into an own file, and there is my problem .. I don't know where to put this new "core" js file. Maybe you want to force to load this js file, or rather have it in your app skeleton, so the user can check it and copy the code. But I think that is something I can't tell so far. ;)

Sorry guys, but CSP is also quite new for me and I was just requesting this, because I would love CakePHP to directly support this. But I also guess it is not done with one simple pull request. :wink:

As I read it here ( https://github.com/blog/1477-content-security-policy ) and if I understand it correctly Rails 3 doesn't create inline js code anymore but providing specific information in the html data attribute and you have to load this file (https://github.com/rails/jquery-ujs) so the javascript is working.

I can make a pull request for DebugKit as there is already an exisiting js file which is loaded and therefore I can use it.

**Comment by TheFRedFox** [comment]
The changes in FormHelper::postLink()
```php
$url = '#';
        //$onClick = 'document.' . $formName . '.submit();';
        if ($confirmMessage) {
            //$options['onclick'] = $this->_confirm($confirmMessage, $onClick, '', $options);
            if (isset($options['escape']) && $options['escape'] === false) {
                $confirmMessage = h($confirmMessage);
            }
            $options['data-cake-confirm'] = $confirmMessage;
        } else {
            //$options['onclick'] = $onClick . ' ';
        }
        //$options['onclick'] .= 'event.returnValue = false; return false;';

        $options['data-cake-form'] = $formName;

        $out .= $this->Html->link($title, $url, $options);
        return $out;
```

the javascript code (right now in jQuery, but I will make a native javascript solution too)
```javascript
$(document).ready(function () {
    $("[data-cake-form]").on('click', function (event) {
        var formName = $(this).data("cake-form");
        if ($(this).data('cake-confirm') !== undefined) {
            var confirmMessage = $(this).data("cake-confirm");
            if (confirm(confirmMessage)) {
                document[formName].submit();
                return false;
            }
            else {
                return true;
            }
        }
        document[formName].submit();
        event.returnValue = false;
        return false;
    });
});
```

**Comment by ADmad** [comment]
@TheFRedFox Please provide you changes through a pull request not as code blocks in comments.

**Comment by dereuromark** [comment]
OK, that approach indeed seem to make sense. I take back my initial criticism ;)

**Comment by TheFRedFox** [comment]
@dereuromark No problem, although I could feel the criticism. But nevermind, glad that you are into it now. :wink: 

@ADmad As I said, I have to add a new javascript file, that I really don't know where to put. I can make a pull request and just store the js file into a new webroot directory in cakephp, so you can see my changes now. But it won't work automatically as the js file has to be loaded into the website.

I just made a pull request in debug_kit with changes to support CSP. :wink: [#382](https://github.com/cakephp/debug_kit/pull/382)
But I just see there are some failured tests. Sry, I will see that I change the tests, too.

**Comment by Marlinc** [comment]
My idea is the following:

* Add a special ```DispatchFilter``` for assets needed by things like JavaScript for ```postLink```. A user could then include that dispatch filter incase they wanted to use the included JavaScript for for example ```postLink```.
* Create a helper that include the JavaScript into the site. This helper can be again loaded by the user when wanted.
* Instead of adding a ```onclick``` to the link a ```class``` could be added to mark the link as a ```postLink```, it would also contain a ```data-form-name``` containing the name to the inline form used to submit the data. The JavaScript provided by the methods above could search for links denoted by the postLink class and add a onclick handler to those.

**Comment by TheFRedFox** [comment]
@Marlinc To be honest I am not familiar to the DispatchFilter, but with the Helper I think it would be fair enough. To the 3rd point, I already showed my solution, it is without an extra class, as I was thinking about name duplicates. But maybe with a good prefix like ```cake-postLink``` or something similar it is possible.

One other solution I was thinking about instead of using the data attribute was to dynamically create js files with a request. But I am totally against it. :smile: It would create too many requests. Think about a list with delete buttons. Requests for 100 js files.
And beside I really don't know how to implement dynamic loading js files either. :wink: 

But another question is: Would you load jQuery too in default or do you prefer native javascript in default?

**Comment by markstory** [comment]
Not requiring jquery would be nice. But the library wars are mostly over now.

Requiring a standalone js file is going to make backwards compatibility more challenging. The additional static asset would be best added into cakephp/app as serving assets out of a vendor lib is going to be tricky.

**Comment by TheFRedFox** [comment]
Maybe it is possible to support both ways, identifying by an Configuration value just like ```inline```:
* creating inline scripts and styles ```if inline==true```
* creating data attributes and load the js and css file (automatically or manual) ```if inline==false```

I will try to change my jquery code to native javascript and make a pull request for postLink and just put the js file in a new webroot/js file in core cakephp. We can then discuss where the js file shall be stored finally. :wink:

**Comment by TheFRedFox** [comment]
Hey guys. I finally made a pull request (right now just for FormHelper::postLink() ). I added the separated js and css files in the webroot/js resp. webroot/css folder as I mentioned before.
As the jQuery ready function is hard to rebuild in native javascript (some different events and window.onload is not called with CSP), I just add the js code in the root scope.
The idea was to force (automatically or manual by the user) to load the js file at the end of the website.

**Comment by markstory** [comment]
@TheFRedFox There is a 'link' right above your previous comment :smile:

**Comment by TheFRedFox** [comment]
@markstory :smile: Thanks .. but I rather meant to convert that issue into a pull request, so it is not just 'linked' but completely connected to each other. :wink:

**Comment by ADmad** [comment]
Closing this issue as related PR is open. Further discussion can continue there.

**Comment by chinpei215** [comment]
I closed the related PR, as that approach seems not secure. I would like to show you an idea of the implementation.

1. Create `CspHelper` to manipulate CSP headers.
2. Add new option to `Helper::_confirm()` method so that it generates a script tag with nonce or hash, and appends it into CSP header via `CspHelper`.  
3. Update `HtmlHelper` and `FormHelper` for using the new option.

If you have any thoughts, please tell me. Honestly, I am not familiar with CSP.

**Comment by dereuromark** [comment]
We should look into this again.

**Comment by inoas** [comment]
For 4.0 maybe we should get a delete_view in which can then be loaded by xhr into a small confirmation window. The javascript require will still be minimal and it can be done unobtrusive, aka if no js/xhr it will simply load the delete view (confirmation view) as a regular action?

**Comment by markstory** [comment]
@dereuromark We could take a route similar to what rails did with their 'ujs' projects (minus the pluggable adapter bits). The [ujs wiki](https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery) has some more context.
