### ISSUE TITLE
Logs directory is not created when not in debug mode

### ISSUE THREAD

**Issue by davehensley** [cakephp/cakephp#7512]
The logs directory is only created when in debug mode, so on my production servers I end up with a bunch of these in my webserver logs:

`[Mon Oct 05 18:54:08.369739 2015] [:error] [pid 28603] [client xxx.xxx.xxx.xxx:47378] PHP Warning:  file_put_contents(/tmp/xxxxxx/logs/error.log): failed to open stream: No such file or directory in /var/app/current/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 135, referer: https://xxxxxxxxxx`

**Comment by dereuromark** [comment]
Closing as https://github.com/cakephp/cakephp/pull/7513 is open for discussion.
