### ISSUE TITLE
Bi-directional belongsToMany association to the same Model

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#7514]
This `EntitiesTable` has a belongsToMany association with itself:

	class EntitiesTable extends AppTable
	{
		public function initialize(array $config) {
			parent::initialize($config);
			
			$this->belongsToMany('LinkedEntities', array(
				'className' => 'Entities',
				'through' => 'Links',
				'foreignKey' => 'from_id',
				'targetForeignKey' => 'to_id'
			));
		}
	}

However, this association only works in one direction. When the table `links` only contains an entry `[from_id: 1, to_id: 2]`, `$this->Entities->findById(1)->contain('LinkedEntities')` correctly fetches the linked entity, but `$this->Entities->findById(2)->contain('LinkedEntities')` does not.

One solution would be to duplicate every entry in the table `links` and swap `from_id` and `to_id`, but this is not desirable. I much rather would like a belongsToMany association considering `from_id` as `foreignKey` and `to_id` as `targetForeignKey` and vice versa.

**How can a bidirectional belongsToMany self-association be implemented?**

**Comment by markstory** [comment]
You need two associations one in each direction.

**Comment by advitum** [comment]
Well, that would be a solution, but a bad one! The association is is meant to be bi-directional, symmetric or whatever you want to call it. It is not like an asymmetrical association (example: Teacher - Student) where you have one association containing Students and one containing Teachers.

I would end up with two properties, linked_entities and linked_entities_2, that should be one single property. There is no logical separation between the two association, I would always have to merge them, sort them manually etc.

I was hoping there was an existing solution (creating the association manually or something) that I simply did not know. If there is not a solution yet, this is not a question, but a feature request!

**Comment by ADmad** [comment]
You can make a custom finder and use the `'finder'` option in association config to fetch associated records.

**Comment by dakota** [comment]
Custom finder seems to be the best solution here. This is the first use-case I've seen for this kind of self-belongsToMany-bidirectional association. Obviously you've got a use-case for it, so perhaps submitting a PR that adds a `bidirectional` option to belongsToMany associations is a good idea?

**Comment by advitum** [comment]
I sure will do. In the meantime: How would I implement the solution using a custom finder?

	public function initialize(array $config) {
		parent::initialize($config);
		
		$this->belongsToMany('LinkedEntities', array(
			'className' => 'Entities',
			'through' => 'Links',
			'foreignKey' => 'entity_id',
			'targetForeignKey' => 'target_id',
			'finder' => 'allLinksForAssociation'
		));
	}
	
	public function findAllLinksForAssociation(Query $query) {
		$query->select(array(
			'entity_id' => 'Links.from_id',
			'target_id' => 'Links.to_id'
		))->select($this);
					
		return $query;
	}

This is where I am stuck right now. My intent is to add the fields `entity_id` and `target_id` aliasing the `from_id` and `to_id` and then doing a `UNION` with the same query where `from_id` and `to_id` are swapped, so the ORM can use `entity_id` and `target_id` as the foreignKeys.

However, I am stuck at using `entity_id` as foreignKey. The resulting query:

    SELECT Links.from_id AS `entity_id`, Links.to_id AS `target_id`, LinkedEntities.id AS `LinkedEntities__id`, LinkedEntities.type AS `LinkedEntities__type`, LinkedEntities.title AS `LinkedEntities__title`, LinkedEntities.user_id AS `LinkedEntities__user_id`, LinkedEntities.created AS `LinkedEntities__created`, Links.entity_id AS `Links__entity_id`, Links.id AS `Links__id`, Links.from_id AS `Links__from_id`, Links.to_id AS `Links__to_id`, Links.role AS `Links__role` FROM entities LinkedEntities INNER JOIN links Links ON LinkedEntities.id = (Links.entity_id) WHERE Links.entity_id in (:c0)

As you can see at the end of the query, Cake now tries to use `Links.entity_id` as the foreignKey while the actual alias is called `entity_id`. How would one remove the table-alias `Links`?

Thanks for your help!
