### ISSUE TITLE
Error: SQLSTATE[HY000]: General error: 5 database is locked

### ISSUE THREAD

**Issue by gtrias** [cakephp/cakephp#7517]
I'm having this error sometimes with no aparent reason.

I think is related to debugkit because is the only part using sqlite to data storage in my project and all the info I've found on internet about this error is related to sqlite.

I don't know what steps are needed to reproduce this error because it happends random times when I make a reload of site.

PHP version 5.5.12
Cakephp version 3.0.13
Debugkit version 3.1.10

**Comment by dakota** [comment]
This is related to debug kit, and can happen if your debugkit database gets to big. Simplest solution is to delete the `tmp/debug_kit.sqlite` file.

**Comment by gtrias** [comment]
Yes, you're right, indeed the database increased it's size to 1.9G. But anyway, why debugkit needs to store so huge amount of information and why It don't handle some data cleaning to avoid this issue?
I'm developing a small app with only 4 pages, so I can figure this could happen more frequently in a big project.

**Comment by dakota** [comment]
The latest master branch now only keeps the last 20 requests (rather than the last 2 weeks worth of requests as currently).

**Comment by gtrias** [comment]
nice this sounds much better. Thank you for the reply :)
