### ISSUE TITLE
FileEngine::increment and ::decrement

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#7522]
I see that these are not implemented at present. I got caught out recently when I switched a 2.x app over from using Wincache to using File and our tests didn't cover some usage of `Cache::increment()` and `Cache::decrement()`.

Is there a reason this isn't implemented for `FileEngine` as something like:

```php
public function increment($key, $offset = 1) {
    $value = $this->read($key);
    if (!$value) {
        return false;
    }
    return $this->write($key, $value + $offset);
}
```

This is essentially the code that I am using in our app after switching away from Wincache. Happy to submit a PR if appropriate.

**Comment by AD7six** [comment]
Have you [looked at the code](https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/FileEngine.php#L353-L364) ?

**Comment by garethellis36** [comment]
@AD7six Yes, I did look at the code. Maybe I don't understand the meaning of "atomically", but I just wondered why something like above couldn't be used when it has the same outcome.

**Comment by AD7six** [comment]
OK, the let's say it's a view counter and it's 0.

You and I both load a page incrementing that counter, at the same time. If we loaded the page at exactly the same time, the counter's value would be 1.

Does this help explain why it's not implemented?

**Comment by ADmad** [comment]
@garethellis36 What happens when another request updates the file between the read() and write() statement calls in the method? :)

**Comment by garethellis36** [comment]
OK that makes sense. Thanks for your patience.
