### ISSUE TITLE
Theme names get screwed up by the inflector if they're uppercased

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#7523]
PSA or DDHF is just an abreviation and used in namespaced themes:

They'll become p_s_a and d_d_h_f. The reason is this line in the UrlHelper:

```php
$theme = Inflector::underscore($this->theme) . '/';
```

@ADmad suggested to put it in a protected method so that it can be overridden.

**Comment by Marlinc** [comment]
This is the reason why use ```CvoTechnologies``` as vendor for most of our packages instead of ``` CVOTechnologies```.

**Comment by HavokInspiration** [comment]
PR #7597 opened.
