### ISSUE TITLE
Virtual Properties + find + fields options

### ISSUE THREAD

**Issue by gubartz** [cakephp/cakephp#7526]
I defined a virtual property: 
App\Model\Entity\Turma

protected function _getAnoSemestre(){
    return $this->_properties['ano'] . '  ' .
    $this->_properties['semestre'];
} 

When I try to use it as a field in controller I get "Unknown column 'Turma.ano_semestre' in 'field list'"

//Controller code
        $turma = $this->Aluno->Turma->find( 'list'
                                          , ['limit' => 200
                                          , 'fields' => array( 'id_turma'
                                                             , 'ano_semestre'
                                                             )
                                            ]
                                          );

**Comment by markstory** [comment]
Virtual fields only exist in the entity and are calculated at runtime. They cannot be used in find() at all.
