### ISSUE TITLE
[3.1] Translate behaviour: 'allowEmptyTranslations' leads to orphaned records

### ISSUE THREAD

**Issue by OopsDoh** [cakephp/cakephp#7531]
I'm not sure if this is a desired behavior or an issue, but I tend to say it's an error:

```
$this->addBehavior('Translate', [
  'fields' => ['title'],
  'allowEmptyTranslations' => false
]);
```

Setup: `allowEmptyTranslations` is set to `false` so empty i18n fields are ignored when retrieving data & results sets as described [here](http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#preventing-retrieval-of-empty-translations). This works as expected.

**But** with `'allowEmptyTranslations' => false` the empty i18n records are **also ignored** when the original entry is getting **deleted**. That leads to orphaned empty database records in the i18n table. Or am I missing something?

---

I also discovered another problem here: I have a form to add and edit new entries including multiple translations. Translations are optional, input fields look like this:

```
echo $this->Form->input('title');
echo $this->Form->input('_translations.es.title', ['required' => false]);
echo $this->Form->input('_translations.fr.title', ['required' => false]);
```

Without  `'allowEmptyTranslations' => false` the translation fields are created as empty entries in the i18n table and these fields are updated and deleted correctly when I edit or delete the entry.

Now I added `'allowEmptyTranslations' => false` in the table class and edit the entry multiple times without entering any translations (leave the translation fields empty). The result: **Each time** I click on 'Save' there are new empty records added in the i18n table.

So I end up with a lot of duplicate empty i18n fields in the database that are not deleted when the main record is deleted... I think that's an issue?

**Comment by markstory** [comment]
Generating additional empty records in the database sounds like an issue to me. I don't think the save/delete scenarios for `allowEmptyTranslations` were thought through. 

Would it be reasonable to not save new empty records when `allowEmptyTranslations` is on?

**Comment by markstory** [comment]
Closing as a pull request is open now.
