### ISSUE TITLE
[3.1] $query->cleanCopy() does not clone 'where' statements

### ISSUE THREAD

**Issue by polchky** [cakephp/cakephp#7533]
When trying to clone a query object, it seems that the 'where' statements are not cloned properly:

		$query1 = $Articles
			->find()
			->select('id')
			->where(['created >' => new DateTime('-10 days')])
			->order(['publication_date' => 'DESC']);

		$query2 = $query1->cleanCopy();
		$query1->where(['title' => 'First']);
		$query2->where(['title' => 'Second']);
		
		debug($query1);
		debug($query2);
		
		// $query1:  SELECT [...] WHERE (created > '2015-10-02 18:38:02' AND title = 'First' AND title = 'Second') ORDER BY publication_date DESC
		// $query2:  SELECT [...] WHERE (created > '2015-10-02 18:38:02' AND title = 'First' AND title = 'Second')
The only way I found to get around this is to overwrite the previous 'where' statements by setting the third parameter of the where() function to true, but all the previous conditions are lost.

I'm not entirely sure whether this is an issue or a wanted behavior, but it seemed odd to me.

**Comment by markstory** [comment]
Cloning/cleaning the where clause is not [part of the documented behavior](http://api.cakephp.org/3.1/class-Cake.ORM.Query.html). However, given that `__clone` has the same behavior, it would be nice to have a quick way to clone a query.

Perhaps `__clone` should do a recursive deep clone, while `cleanCopy()` can do the quicker/shallow clone we rely on for count() operations.

**Comment by lorenzo** [comment]
I think `__clone` can be changed to be a deep clone

**Comment by markstory** [comment]
@lorenzo Agreed.

**Comment by markstory** [comment]
Pull request up now.
