### ISSUE TITLE
Postgres expression typecast

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7534]
It took me a while to figure it out so hopefully I can provide you all necessary information about this issue. Keep in mind that this example does not make sense, it's a simplified but also non-working version.

How I build the query:
```php
        $query->update()->set([
            'priority' => $query->newExpr()->addCase(
                [
                    $query->newExpr()->add(['id' => '52852e5c-5761-4b87-91d3-456f1dff1469'])
                ],
                [
                    2
                ],
                [
                    'integer'
                ]
            )
        ]);
        $query->where(['id IN' => ['52852e5c-5761-4b87-91d3-456f1dff1469']]);
```

The query object (debug($query)):
```
'(help)' => 'This is a Query object, to get the results execute or iterate it.',
	'sql' => 'UPDATE categories SET priority = (CASE WHEN id = :c0 THEN :c1 END) WHERE id in (:c2)',
	'params' => [
		':c0' => [
			'value' => '52852e5c-5761-4b87-91d3-456f1dff1469',
			'type' => 'string',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => (int) 2,
			'type' => 'integer',
			'placeholder' => 'c1'
		],
		':c2' => [
			'value' => '52852e5c-5761-4b87-91d3-456f1dff1469',
			'type' => 'string',
			'placeholder' => 'c2'
		]
	],
	'defaultTypes' => [
		'Categories.id' => 'string',
		'id' => 'string',
		'Categories.name' => 'string',
		'name' => 'string',
		'Categories.slug' => 'string',
		'slug' => 'string',
		'Categories.description' => 'text',
		'description' => 'text',
		'Categories.priority' => 'integer',
		'priority' => 'integer',
		'Categories.deleted' => 'timestamp',
		'deleted' => 'timestamp',
		'Categories.modified' => 'timestamp',
		'modified' => 'timestamp',
		'Categories.created' => 'timestamp',
		'created' => 'timestamp'
	],
	'decorators' => (int) 0,
	'executed' => false,
	'hydrate' => true,
	'buffered' => true,
	'formatters' => (int) 0,
	'mapReducers' => (int) 0,
	'contain' => [],
	'matching' => [],
	'extraOptions' => [],
	'repository' => object(App\Model\Table\CategoriesTable) {

		'registryAlias' => 'Categories',
		'table' => 'categories',
		'alias' => 'Categories',
		'entityClass' => 'App\Model\Entity\Category',
		'associations' => [],
		'behaviors' => [
			(int) 0 => 'Timestamp',
			(int) 1 => 'Search',
			(int) 2 => 'Slug'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	}
```

If I run this query with `$query->execute();` I get the following error message:
```
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "priority" is of type integer but expression is of type text
LINE 1: UPDATE categories SET priority = (CASE WHEN id = $1 THEN $2 ...
                                          ^
HINT:  You will need to rewrite or cast the expression.
```

If I build the query manually like:
```
UPDATE categories SET priority = (CASE WHEN id = '10e36a3e-e99c-4444-866c-7ed789b56b25' THEN 1 END) WHERE id IN ('10e36a3e-e99c-4444-866c-7ed789b56b25');
```

and execute the query directly in Postgres CLI I get no error message.

Cake: ~3.1
Postgres: 9.3
PHP: 5.5 - 7.0

**Comment by markstory** [comment]
What happens if the `2` has the type of string instead of integer? Part of the issue might be related to our drivers using the prepared statement APIs while psql is just sending SQL strings.

**Comment by steefaan** [comment]
@markstory Same error.

**Comment by markstory** [comment]
Very strange.

**Comment by steefaan** [comment]
@markstory Can you try to reproduce it, maybe it's an issue in my code but I don't think so.

**Comment by markstory** [comment]
@steefaan I can do that tomorrow :smile:

**Comment by markstory** [comment]
I was able to reproduce this issue. However, it seems to be a limitation in the pgsql driver and not an issue specific to CakePHP. The following error can also be reproduced with the following PDO code:

```php
$db = new PDO('pgsql:host=localhost;dbname=cake_test_db;user=markstory');

$stmt = $db->prepare('UPDATE comments SET user_id = (CASE WHEN published = :c0 THEN :c1 END) WHERE published in (:c2)');
$stmt->bindValue('c0', 'N', PDO::PARAM_STR);
$stmt->bindValue('c1', 2, PDO::PARAM_INT);
$stmt->bindValue('c2', 'Y', PDO::PARAM_STR);

$out = $stmt->execute();
var_dump($out);
var_dump('Error code', $stmt->errorCode());
var_dump('Error info', $stmt->errorInfo());
```

Because of postgres's casting rules you might want to use a SQL snippet to work around the casting issues.

**Comment by steefaan** [comment]
I opened an issue on php.net:
https://bugs.php.net/bug.php?id=70789

**Comment by mbeccati** [comment]
From the PHP bug report I just closed:

> I'm happy to report it's not a PDO_pgsql bug. Nor a PostgreSQL bug, to be fair.
> 
> In fact if you try to prepare such a query from psql you will see the very same error.
> 
> postgres=# PREPARE foo AS UPDATE categories SET priority = (CASE WHEN id = $1 THEN $2 END) WHERE id in ($3);
> ERROR:  column "priority " is of type integer but expression is of type text
>
> You just need to cast the CASE expression, e.g.
>
> (CASE WHEN id = $1 THEN $2 END)::int, or
> (CASE WHEN id = $1 THEN $2::int END), or
> (CASE WHEN id = $1 THEN $2 ELSE 0 END)
>
> for Postgres to know it's an integer and accept it.

**Comment by dereuromark** [comment]
Should we add such a complex example to the docs?

**Comment by lorenzo** [comment]
I'll investigate if the value binder can do this automatically

**Comment by steefaan** [comment]
@lorenzo Maybe reopen the issue unit you have investigated?

**Comment by skie** [comment]
What if we implement CastExpression that will handle everything relatated to value::type cast syntax. In this case ORM provide way for developers to define type casts. CastExpression should accepts Expression and type.

**Comment by markstory** [comment]
A CastExpression sounds like a nice solution @skie
