### ISSUE TITLE
How to upgrade from 3.0.x to 3.1.1?

### ISSUE THREAD

**Issue by JayWalker512** [cakephp/cakephp#7542]
Sorry if this seems like a dumb question, but I can't seem to figure out a way to upgrade my application to the latest CakePHP core version. Currently I'm at 3.0.14 and was able to upgrade to that using composer:

```bash
php composer.phar require cakephp/cakephp:"~3.0"
```

That's all well and good, but when I try:

```bash
php composer.phar require cakephp/cakephp:"~3.1.1"
```

There's lots of errors about missing/unsatisfiable packages. Specifically:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/debug_kit 3.1.7 requires cakephp/cakephp 3.0.* -> no matching package found.
    - cakephp/debug_kit 3.1.7 requires cakephp/cakephp 3.0.* -> no matching package found.
    - cakephp/debug_kit 3.1.7 requires cakephp/cakephp 3.0.* -> no matching package found.
    - Installation request for cakephp/debug_kit == 3.1.7.0 -> satisfiable by cakephp/debug_kit[3.1.7].
```

Is this just to be expected/can't go straight from 3.0.x to 3.11? Would it be easier to just clone a fresh CakePHP app and paste in all of my custom code? Or is there something I'm missing with Composer? I'm still pretty new to Composer in general, so any help here is appreciated.

**Comment by ADmad** [comment]
You also need to update debugkit version to 3.2. Check the [composer.json](https://github.com/cakephp/app/blob/master/composer.json) from  latest  app skeleton.

**Comment by JayWalker512** [comment]
For anyone coming along with the same question, I figured I'd post my solution. I didn't realize I could tell composer to install multiple packages simultaneously, as prior to that I had a circular dependency issue when trying to install debugkit 3.2. So here's what I did to upgrade from CakePHP 3.0.14:

```
php composer.phar require cakephp/debug_kit:"~3.2" cakephp/cakephp:"3.1.0-RC1"
php composer.phar require cakephp/cakephp:"3.1.1"
```
This solved my issues.
