### ISSUE TITLE
Cake 3 missing controller error in plugin after baking plugin

### ISSUE THREAD

**Issue by ashu1459** [cakephp/cakephp#7544]
Platform: Windows 7 64-bit
Browser: chrome

When I try to bake a plugin in small case, it gives and error of missing controller while accessing that plugin.
For eg: 
I made a plugin named 'api' using the command 'cake bake plugin api'.
It created plugin folder with the name 'Api'(camel case) and created the namespaces with name 'api'(all small case) such as "namespace api\Controller;" and "use api\Controller\AppController;".
When I tried accessing the plugin it gave me an error of missing controller inside plugin.

What I did to fix it was to change the namespace declaration to "namespace Api\Controller;" and its use to "use Api\Controller\AppController;"(notice a capital A in Api). Then it worked fine!!.

I think the bug lies where the the directory name is created as camel case and namespace created as small case. Of course I intentionally baked it in small case.

Please fix this issue.
Thanks

**Comment by AD7six** [comment]
This issue was moved to cakephp/bake#166
