### ISSUE TITLE
[2.7] MemcachedEngine::clear() with no keys

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7546]
```
Invalid argument supplied for foreach()
[...] lib/Cake/Cache/Engine/MemcachedEngine.php:285
```

Fix: Before foreach, check that `$keys` is of type `array` and not `false`.

https://secure.php.net/manual/en/memcached.getallkeys.php:
> Returns the keys stored on all the servers on success or **FALSE on failure**.

**Comment by markstory** [comment]
Fixed with #7552
