### ISSUE TITLE
cakePHP 3.1 - PHP Fatal error not reported by cake...  Found only in php_error_log.. Table Object

### ISSUE THREAD

**Issue by glkaup** [cakephp/cakephp#7551]
The following error:

    [14-Oct-2015 16:47:52 UTC] PHP Fatal error:  Call to undefined method Cake\Validation\Validator::notBlank() in E:\membership\src\Model\Table\MemberControlsTable.php on line 45

Was reported by my app, but only to the php_error_log.  The error occurred after download v3.1 which I thought REQUIRED the use of notBlank() instead of notEmpty().

Any way, why is the error not reported by the cakePHP.  Is it related to the fact that it is coming out of a Table object?

**Comment by ADmad** [comment]
You are confusing the `Validator::notEmpty()` with `Validation::notEmpty()`.

You are still supposed to use `$validator->notEmpty()` in `validationDefault()` of your class. Only the usage of rule like `$validator->add('name', 'somealias', ['rule' => 'notEmpty'])` needs to be changed to  `$validator->add('name', 'somealias', ['rule' => 'notBlank'])`.

**Comment by glkaup** [comment]
Ok, thanks for the clarification of what caused the error... but that is NOT the answer to my question...

WHY does the php error only get reported to the log file in this case.  Most php errors are reported as part of the response and this one is NOT!  The script just quit running and there was absolutely no response at all.
