### ISSUE TITLE
Every plugin I test fails due to the aura/intl vendor, and I don't understand why

### ISSUE THREAD

**Issue by elboletaire** [cakephp/cakephp#7553]
Hi guys! I'm having issues trying to test any plugin of CakePHP. When I try to test them all of them crash due to a not found error:

```
PHP Fatal error:  Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /home/elboletaire/www/github/crud/vendor/aura/intl/tests/WiringTest.php on line 8

Fatal error: Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /home/elboletaire/www/github/crud/vendor/aura/intl/tests/WiringTest.php on line 8
```

Some of the plugins I've tried to test so far:

https://github.com/elboletaire/less-cake-plugin [![Build status](https://img.shields.io/travis/elboletaire/less-cake-plugin.svg?style=flat-square)](https://travis-ci.org/elboletaire/less-cake-plugin)
https://github.com/FriendsOfCake/bootstrap-ui [![Build Status](https://img.shields.io/travis/FriendsOfCake/bootstrap-ui/master.svg?style=flat-square)](https://travis-ci.org/FriendsOfCake/bootstrap-ui)
https://github.com/FriendsOfCake/search [![Build Status](https://img.shields.io/travis/FriendsOfCake/search/master.svg?style=flat-square)](https://travis-ci.org/FriendsOfCake/search)
https://github.com/FriendsOfCake/crud [![Build Status](https://img.shields.io/travis/FriendsOfCake/crud/master.svg?style=flat-square)](https://travis-ci.org/FriendsOfCake/crud)

I've added the build status badge to clearly show that they are properly building, which makes me think that I'm having some local problem on my computer (though I've tried it on different machines using different PHP versions...).

Process I'm following to test them:

```bash
git clone PROJECT
cd project
composer install
phpunit .
```

All of them give me the same error described above:

```
PHP Fatal error:  Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /home/elboletaire/www/github/crud/vendor/aura/intl/tests/WiringTest.php on line 8

Fatal error: Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /home/elboletaire/www/github/crud/vendor/aura/intl/tests/WiringTest.php on line 8
```

I opened the aura/intl and could confirm that there isn't a `WiringAssertionsTrait` and that this trait is in their aura/framework package (which is not included in the aura/intl composer dependencies). That's why [I opened an issue in aura/intl](https://github.com/auraphp/Aura.Intl/issues/17).

But apart from the Aura/intl issue there's something I cannot understand. Why is Cake trying to load the aura/intl test files?? Many of the plugins listed above use an exclude option in their `phpunit.xml` file which (in my opinion) should be excluding the vendors folder from running tests:

```xml
    <filter>
        <blacklist>
            <directory suffix=".php">./vendor/</directory>
            <directory suffix=".ctp">./vendor/</directory>

            <directory suffix=".php">./tests/</directory>
            <directory suffix=".ctp">./tests/</directory>

            <directory suffix=".php">./src/TestSuite/</directory>
            <directory suffix=".ctp">./src/TestSuite/</directory>
        </blacklist>
    </filter>
```

What confuses me even more is that nobody opened an issue for this and this makes me think (again) that I'm doing something wrong.

Can someone get me out of this black hole, please? :sob:

**Comment by markstory** [comment]
Why are you running tests for the vendor libs?

**Comment by lorenzo** [comment]
You should not run tests in vendors

**Comment by lorenzo** [comment]
Can you show your phpunit.xml file?

**Comment by elboletaire** [comment]
Any `phpunit.xml` file from the plugins listed above could be an example.

That's why I'm getting crazy because I know these tests should work but they don't! xD

Here's the process I try to do (click on the image to see the recording):

[![asciicast](https://asciinema.org/a/0m6dgbjl7vd4m7tuw46cklm6v.png)](https://asciinema.org/a/0m6dgbjl7vd4m7tuw46cklm6v)

I'm pretty sure I'm doing something wrong but I did this a lot of times before without any problem until now.. :cry:

**Comment by Marlinc** [comment]
@elboletaire could you try running ```vendor/bin/phpunit``` after doing the ```composer install``` instead of just ``` phpunit```?

**Comment by elboletaire** [comment]
Sure, but it does exactly the same:

[![asciicast](https://asciinema.org/a/9if1q3e080osc51cews6u6n80.png)](https://asciinema.org/a/9if1q3e080osc51cews6u6n80)

**Comment by dakota** [comment]
@elboletaire Don't run `vendor/bin/phpunit .`, but rather `vendor/bin/phpunit` (without the dot).

See
[![asciicast](https://asciinema.org/a/8xcw44ebi63zyyhyx5j9v94ay.png)](https://asciinema.org/a/8xcw44ebi63zyyhyx5j9v94ay)

**Comment by elboletaire** [comment]
I said it! I know I was doing something wrong (and very stupid, as I did this a lot of times before).

What a dot can do....

@dakota many thanks for taking the time to see where I was failing.

**Comment by elboletaire** [comment]
I feel very newbie right now :flushed:

**Comment by Marlinc** [comment]
The dot shouldn't matter really mmm :open_mouth:

**Comment by markstory** [comment]
@Marlinc The dot matters very much, as you are telling phpunit to run tests from cwd.

**Comment by elboletaire** [comment]
> @Marlinc The dot matters very much, as you are telling phpunit to run tests from cwd.

Yup, that's it.. after @Marlinc said me the dot issue I thought about it... adding the dot runs every test available from the current path, recursively :sweat_smile:

**Comment by elboletaire** [comment]
BTW, at least this has served to troubleshot the `aura/intl` tests issue.
