### ISSUE TITLE
_ext='json' Url generation does not allow for passed parameters.

### ISSUE THREAD

**Issue by heavykevy** [cakephp/cakephp#7554]
If I generate a Url with parameters, the Router does not detect the .json in the url as the Router.php file expects .json to be the end of the URL.

For example:

    url = "<?= $this->Url->build(['controller' => 'Purchases', 'action' => 'getDealerDefaultState','id'=> 47,'_ext'=>'json']) ?>";
	        targeturl = url;
	        $.ajax({
	            type: 'get',
	            url: targeturl,
	            beforeSend: function(xhr) {
	                xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
	            }
Generates a url such as:
Controller/getDealerDefaultState.json/id=47

I modified my Cakephp/src/Routing/Route/Route.php file as follows

        preg_match('/\.([0-9a-z]*)/', $url, $match); // modified the RegExp  to search for an '_ext' globally in the URL

        if (empty($match[1])) {
            return [$url, null];
        }
        $ext = strtolower($match[0]);  //gets the match including the '.'
        /*$len = strlen($match[1]);
        foreach ($this->_extensions as $name) {
            if (strtolower($name) === $ext) {
                $url = substr($url, 0, ($len + 1) * -1);
                return [$url, $ext];
            }
        }*/
        $url = str_replace($ext, '', $url);  //remove the found ext (e.g. '.json' )from the URL
        return [$url, null];

This solved my problem and allows multiple parameters to be sent via the URL.

**Comment by dereuromark** [comment]
Did you forget to enable this extension maybe?
http://book.cakephp.org/3.0/en/development/routing.html#Cake\Routing\Router::extensions

**Comment by heavykevy** [comment]
No sir, it was enabled.

**Comment by markstory** [comment]
I can take a look at this.

**Comment by markstory** [comment]
What does your route definition look like? I attempted to reproduce this issue in the test suite, and was not able to reproduce the incorrectly generate URL of `Controller/getDealerDefaultState.json/id=47`.  

The suggested modifications cannot be applied as it will remove the ability to use `.` in path segments which will break existing applications.

**Comment by heavykevy** [comment]
Mark,

I am not sure I understand your question...

My application tracks the sales of vehicles by a dealer.
The sales person field is an autocomplete field.
If a dealer is adding a purchase, the autocomplete list is generated by the
add method, but if an admin account adds the purchase for a dealer, the
dealer needs to be selected and an AJAX call used to filter the sales
people.

When I generated the url as such:
Purchases/getSalesPersonList.json/47

the .json was not detected and the application complained that it could not
find the getSalesPersonList.json() method.

If the URL is passed without the parameter, then the .json was found and
removed by the code that I pointed out.
I don't understand why the suggested modification breaks anything if the
current code would remove the .json anyway?

**Comment by markstory** [comment]
My question was _how_ did you generate the `Purchases/getSalesPersonList.json/47` URL? What route definition lead to that output? That URL is not typical of CakePHP and that is why the extension parsing 'failed'.

We cannot pull extensions out of arbitrary path segments as it will break existing applications. Instead I think the issue is with how that URL was generated.

The reason your change would break existing apps is the following are all valid URLS presently:

* /articles/view/the.best.thing.ever
* /articles/tagged/cats.dogs
* /foo.bar/en/bookmarks/view/the-world-is.flat

With your changes all of these URLs will be parsed incorrectly.

**Comment by heavykevy** [comment]
Mark, 
the URL is generated by the code at the top of my first post.
The full url would be something like:
example.com/Purchases/getSalespersonList.json/47

Obviously, I didn't consider the examples you mentioned...

I actually was able to make my application work without using the json extension, so I don't need it, However in that the '.json' is ignored and not removed by the route.php when parameters are passed in the URL, such that the application complains about missing actions, I thought it best to submit an issue ticket.


If you build the URL as follows:
$this->Url->build(['controller' => 'Purchases', 'action' => 'edit',$id,'_ext'=>'json']);
Is this not a valid method for generating a URL?
Am I making a mistake by building the URL in this way?

**Comment by markstory** [comment]
What does your config/routes.php file look like?

The way you are building your URLs is fine. What I can't reproduce is the output you are getting which is why I asked about what your route definitions look like.

**Comment by heavykevy** [comment]
My Routes.php has nothing added except the line to enable extensions for
json:
Router::extensions(['json']);

Which I placed just before the Scope('/' ... route.
That is the only change I made to my config/routes.php file.

**Comment by heavykevy** [comment]
I'm sorry Mark,
I just did some testing, and discovered that the .json is tacked on to the end of the URL if I build the URL not in the JS select event.

I because the selected value is not known when the template is compiled, the select event is adding the value at the end of the generated URL such that '/47' is added after the '.json' yet if the URL is built entirely by the URL generator, the '.json' is added to the end and the standing code is working correctly as is.

Thank you for your time and looking in to this...
