### ISSUE TITLE
[2.7.5] Notice: Undefined variable: mergeAssocTmp

### ISSUE THREAD

**Issue by Pablushka** [cakephp/cakephp#7563]
Notice (8): Undefined variable: mergeAssocTmp [APP\Vendor\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php, line 1582] 

Hi, this error happend when **recursive is set to 2** in the controller. May be I misunderstood the use of recursive and there are a better method to use. I use recursive = 2 because I need a description field for each Detalle.egreso_cuenta_id and Detalle.ingreso_cuenta_id. The description field is stored in the Detalle associated model called Cuenta. The final result is ok, I receive in mi view the spected array with all the data but the annoying notice breaks the page layout.

The controller code:

    public function view($id = null) {
		if (!$this->Movimiento->exists($id)) {
			throw new NotFoundException(__('Invalid movimiento'));
		}
    
        $this->Movimiento->recursive = 2;
		$options = array('conditions' => array('Movimiento.' . $this->Movimiento->primaryKey => $id));
		$this->set('movimiento', $this->Movimiento->find('first', $options));
	}

This is the only code that trigger this error, so I think is a problem with the associations definitions, but I can't figure out what's wrong.

Movimiento Model:

    // Movimiento model associations
	public $belongsTo = array(
		'Empresa' => array(
			'className' => 'Empresa',
			'foreignKey' => 'empresa_id'
		),
		'Relacionada' => array(
			'className' => 'Empresa',
			'foreignKey' => 'relacionada_id'
		)
	);

	public $hasMany = array(
		'Detalle' => array(
			'className' => 'Detalle',
			'foreignKey' => 'movimiento_id',
			'dependent' => false
		)
	);

Detalle Model

    // Detalle Model associations
    public $belongsTo = array(
		'Movimiento' => array(
			'className' => 'Movimiento',
			'foreignKey' => 'movimiento_id'
		),
		'CuentaIngreso' => array(
			'className' => 'Cuenta',
			'foreignKey' => 'ingreso_cuenta_id'
		),
		'CuentaEgreso' => array(
			'className' => 'Cuenta',
			'foreignKey' => 'egreso_cuenta_id'
		)
	);

Cuenta Model:

    // Cuenta model associations
    public $hasMany = array(
		'Ingresos' => array(
			'className' => 'Detalle',
			'foreignKey' => 'ingreso_cuenta_id',
			'dependent' => false
		),
		'Egresos' => array(
			'className' => 'Detalle',
			'foreignKey' => 'egreso_cuenta_id',
			'dependent' => false
		)		
	);

**Comment by dereuromark** [comment]
As a (not so relevant) side note: You should not be using recursive anymore, and especially nothing above 0. Instead you should use contain.
But the issue will most likely be there in either case and needs to be fixed.

**Comment by Pablushka** [comment]
Thank you dereuromark. You are right. I'm refactoring the code to use the contain method right now.

**Comment by markstory** [comment]
Even though recursive should be avoided, the core code should not emit notice errors under normal circumstances.

**Comment by markstory** [comment]
Fixed in e2a1094
