### ISSUE TITLE
FilterIterator returning wrong count()

### ISSUE THREAD

**Issue by LACabeza** [cakephp/cakephp#7565]
Look at this example:
```php
>>> $collection = new \Cake\Collection\Collection([['value'=>1],['value'=>2],['value'=>null]]);
=> Cake\Collection\Collection {#217
     +"count": 3,
   }
>>> $collection->count()
=> 3
>>> $valid = $collection->reject(function($item){ return empty($item['value']); });
=> Cake\Collection\Iterator\FilterIterator {#203
     +"count": 2,
   }
>>> $valid->toList();
=> [
     [
       "value" => 1,
     ],
     [
       "value" => 2,
     ],
   ]
>>> $valid->count();
=> 3
```

Why $valid->count() returns not 2 but 3 ?
I'm using cake 3.1

**Comment by markstory** [comment]
Its very odd that the internal state is right, but count() is wrong.

**Comment by LACabeza** [comment]
Even if I create a new object the problem continues

```php
>>> $v1 = new \Cake\Collection\Collection( $valid );
=> Cake\Collection\Collection {#204
     +"count": 2,
   }
>>> $v1->count()
=> 3
```
While this works:
```php
>>> $v2 = new \Cake\Collection\Collection( $valid->toArray() );
=> Cake\Collection\Collection {#203
     +"count": 2,
   }
>>> $v2->count()
=> 2
```

**Comment by lorenzo** [comment]
Collections don't actually have a `count()` method.

http://api.cakephp.org/3.1/class-Cake.Collection.CollectionInterface.html

The fact you can call count() on a collection object is a side-effect of how php works internally.  I've been a bit reluctant on implementing `count()` for collections since the method will have several side effects in the collection itself, but if we can live with the side effects then we can revisit the decision.

**Comment by markstory** [comment]
Is the main side-effect that the collection has to be evaluated/applied?

**Comment by lorenzo** [comment]
@markstory Yes, that means that if you iterate the collection again, the same changes will be applied again (for certain operations). Another side effect is that some collections cannot be rewinded, so after issuing the `count()` it become unusable.

**Comment by markstory** [comment]
Those sound pretty annoying/bad.

**Comment by ADmad** [comment]
How about we throw and error if someone tries to use count() on collection?

**Comment by LACabeza** [comment]
I agree. I was using that count() method and if i didn't notice the problem, it could give a big trouble.

**Comment by jhli** [comment]
+1: for disabling count with error msg.

**Comment by markstory** [comment]
Disabling count() sounds ok to me. It is better than incorrect results.

**Comment by markstory** [comment]
Closing as a pull request is up now.

**Comment by manofirmz** [comment]
Hey, see: http://www.objectpac.com/2012/09/29/making-an-spl-filteriterator-countable
