### ISSUE TITLE
Problem with using a single table for 2 junctions

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#7568]
I have asked my question in StackOverflow. Here's the link : 
http://stackoverflow.com/questions/33173725/defining-relationships-for-common-junction-table

**Comment by lorenzo** [comment]
Please don't use this issue tracker for asking questions about the framework. Keeping questions in stackoverflow is better

**Comment by gauravmak** [comment]
I thought this is something(as a feature) that should be doable with the framework so. Anyway, thank you.
