### ISSUE TITLE
[2.7] PHP7 Error :  'String' class name is reserved

### ISSUE THREAD

**Issue by aymanrb** [cakephp/cakephp#7573]
Today I was testing my CakePHP v2.7.5 application against PHP7 to check on its compatibility and get it ready with the final stable release of php when it arrives.

I got this error when I tried to run some migration files:

```
Fatal Error Error: Cannot use 'String' as class name as it is reserved in 
[.../lib/Cake/Utility/String.php, line 26]
```

Didn't test it over with CakePHP v3 but I guess the utility class name "String" should be changed in older versions.

**Comment by ADmad** [comment]
2.x is not compatible is PHP 7. We cannot change the class name `String` without breaking backwards compatibility.

The class has already been renamed in 3.x which is compatible with PHP 7.

**Comment by josegonzalez** [comment]
You should be using the `CakeText` class instead of String.

**Comment by ADmad** [comment]
Ah I forgot we did rename the class in 2.x too. But we don't run the testsuite for 2.x on PHP 7 (probably due to phpunit issues) so can't claim compatibility with PHP 7 even though it will probably run.

**Comment by markstory** [comment]
@ADmad it is also unlikely that all the community plugins have or will switch to CakeText.

**Comment by aymanrb** [comment]
Thank you @ADmad & @josegonzalez. I didn't notice it was changed, it worked fine with CakeText now.

@markstory I totally agree with you, but changing it in the Migrations plugin wasn't a bit deal, it's only there in the Console/Command/MigrationShell.php

I know maintaining the compatibility won't always be that easy, but it's worth it, looking into the number of Cake2.x apps and the expected performance enhancements of PHP7.

Thank you all for the efforts

**Comment by abhilashlohar** [comment]
I was getting same issue.
What i did:-
**I just download the cakephp 2.8 and copy the lib folder from it and replaced to my project.**

and Problem Solved

**Comment by diyfr** [comment]
@abhilashlohar  I have the same problem and apply your solution, but for static text  (i18n) only the first character is displayed. An idea ?

**Comment by abhilashlohar** [comment]
@diyfr have your problem resolved ?

**Comment by ADmad** [comment]
Guys this is not a help forum and your issue is unrelated to this ticket. Please take your discussion to the official forum or stackoverflow.

**Comment by diyfr** [comment]
@abhilashlohar Yes.
@ADmad sorry for the inconvenience

**Comment by chinmay235** [comment]
@josegonzalez thank your for your comment. I have used CakeText insted of String. Not this is working fine. But I am not sure that right way or not.

**Comment by dereuromark** [comment]
CakeText is the right way for Cake2

**Comment by chinmay235** [comment]
@dereuromark  thanks

**Comment by chinmay235** [comment]
@dereuromark I am getting same error. Can you please hlep me.

I am getting this error in my controller.
{
    "code": 500,
    "url": "\/2016\/TPO\/project\/orders\/new_order.json",
    "name": "Cannot declare class CakeText, because the name is already in use"
}

**Comment by dereuromark** [comment]
It must be a dev error on your side. Make sure you only have a single CakeText class (the one CakePHP offers).

**Comment by chinmay235** [comment]
`CakeText` working fine. But while I am fetching data from my MySQL db. This won't work

**Comment by PiyushNagwani** [comment]
> CakeText

thanks bro you don't know how much time you saved

**Comment by PiyushNagwani** [comment]
> I was getting same issue. What i did:- **I just download the cakephp 2.8 and copy the lib folder from it and replaced to my project.**
> 
> and Problem Solved

thanks you saved my time
