### ISSUE TITLE
Unable to delete first row from record when postlink is used inside loop in view

### ISSUE THREAD

**Issue by bhishmaRlx** [cakephp/cakephp#7575]
Here is my code in view file:

```
<?php foreach ($Itemdetails as $itemdetail): ?>

	<tr>		
		<td class="actions">
			<?php echo $this->Html->link('<span class="glyphicon glyphicon-pencil"></span> Edit', array('controller' => 'itemdetails', 'action' => 'edit', $itemdetail['id']),array('escape'=>false)); ?>
		
                  	<?php echo $this->Form->postLink('<span class="glyphicon glyphicon-remove"></span> Remove', array('controller' => 'itemdetails', 'action' => 'delete', $itemdetail['id']), array('escape'=>false), __('Are you sure you want to delete "%s" from order list?', $itemdetail['name']." ".$itemdetail['type'])); ?>
		</td>
	</tr>
<?php endforeach; ?>
```

From above code, I am able to delete all records but not the FIRST ONE.

On inspecting element in brower, I get html codes same as I attaced a file with this issue.
![html code on inspect element](https://github-cloud.s3.amazonaws.com/assets/15183517/10565241/a0612100-75e9-11e5-947b-699fa47fb3b7.png)

CakePHP version:2.5.7
Plugins: bootstrap,jquery
OS: Windows 7

**Comment by ADmad** [comment]
> CakePHP version:2.5.7

Upgrade to latest 2.7 release and check.

**Comment by bhishmaRlx** [comment]
Thanks ADmad, but is there any other solution within cakePHP 2.5.7. version which can fix this problem without shifting my whole project from 2.5.7 to 2.7.
And if there is no other solution then please tell me any quick way to shift my project from one version to another cakePHP version, as I have never shift any project to another cakePHP version.

**Comment by markstory** [comment]
@bhishmaRlx We're not doing any additional bugfix releases for 2.5.x. If you cannot go to 2.7, you might want to try upgrading to 2.5.9, or at least seeing if the changelogs have any relevant fixes.

**Comment by bhishmaRlx** [comment]
@markstory & @ADmad Thanks you guys.
Upgraded to 2.7
Problem solved. :)

**Comment by dereuromark** [comment]
You are supposed to use latest. That means 2.7.5.

**Comment by bhishmaRlx** [comment]
UPDATED TO cakePHP 2.7.5 BUT YET PROBLEM NOT SOLVED.

I think this bug has not been resolved yet in cakephp 2.X.

Thanks you friends.

**Comment by kantsverma** [comment]
I am getting the same issues in cakephp 3.0 , first entry not generating the form tag  :( .

**Comment by kantsverma** [comment]
Worked for me now . I was using the  $this->Form->create()  and then i was using $this->Form->postLink() inside of form tag so it was not working for first entry then i remove the post link outside of form tag and it start working :)

**Comment by inspectorman** [comment]
hello, 
Same issue on cakephp version 3.x. 
The first form tag in a list from form->postLink() is not being created.

**Comment by motsmanish** [comment]
The issue is neither with 2.x nor with 3.x, it happens when the postLink is placed inside another form.

**Comment by Soufiane974** [comment]
Hi, I still have this issue on cakephp 4.3.9. 

My PHP code : 

` <?= $this->Form->postLink(__('Supprimer'), ['controller' => 'Activities', 'action' => 'delete', $activity->id], ['block' => true,  'confirm' => __('Etes vous sûr de vouloir supprimer l\'activité ? L\'activité sera aussi retirée du planning.'), 'class' => 'btn btn-default btn-sm']) ?>
`


My HTML table code : 
![image](https://user-images.githubusercontent.com/6583981/169980931-4cf2b0f6-6c10-4352-9bfd-6cab8f4cf865.png)


Below the generated postlink code : 
![image](https://user-images.githubusercontent.com/6583981/169980767-19b006d5-da38-4255-adc7-9fd3283a97e5.png)

The first link doesn't have <form> tag. A temporary solution is to add a first postlink with display none. The next links generates properly then.

**Comment by othercorey** [comment]
@Soufiane974 Can you create a new issue for this?
