### ISSUE TITLE
JS scriptblock example is not clear

### ISSUE THREAD

**Issue by raymak23** [cakephp/cakephp#7576]
Hi,

I am trying to create a link and assign the link value to a JavaScript variable. Apprently the cakephp 3 document for script block is not clear on how to add custom script block in a page. Here is the link to the document http://book.cakephp.org/3.0/en/views/helpers/html.html#creating-inline-javascript-blocks. 

Here is what I am trying to do:
```
<?php
    $this->Html->scriptStart(['block' => true]);
    echo 'var loginurl = ' . $this->Html->url(array('controller' => 'users', 'action' => 'login'));
    $this->Html->scriptEnd();

?>
```

**Comment by markstory** [comment]
What isn't clear? In addition to making the script block it needs to be output.

```php
echo $this->fetch('script');
```

**Comment by markstory** [comment]
The requirement to output the block isn't in the docs, so I'll add that.

**Comment by raymak23** [comment]
@markstory - What I am trying to do is create script block that will look like this by using Cakephp $this->Html->ScriptBlock();
```
<script type="text/javascript">
    var loginurl = /Users/Login;
</script>
```

**Comment by raymak23** [comment]
I already have a ```echo $this->fetch('script');``` in html head section.

**Comment by markstory** [comment]
Ok, so what are you getting if not that? Because locally, the following works fine for me:

```php
// In the layout 
<?= $this->fetch('script') ?>

// In a view
<?php $this->Html->scriptStart(['block' => true]); ?>
alert('hi');
<?php $this->Html->scriptEnd(); ?>
```

**Comment by markstory** [comment]
Docs updated in cakephp/docs#3411

**Comment by raymak23** [comment]
The above code example you provided, wasnt generating JS script block in default.ctp head.

So i had to use it like this:

```
<?php
    $loginurl = $this->Url->build(['controller' => 'Users', 'action' => 'login']);
        echo $this->Html->scriptBlock('var loginurl = "' . $loginurl . '";', array('inline' => false));  
?> 
```

**Comment by markstory** [comment]
There is no `inline` option in cake3. Perhaps you are using cakephp 2.x and reading the 3.x documentation?
