### ISSUE TITLE
Unknown setter 'date'  on my Ubuntu + apache2 + HHVM instance

### ISSUE THREAD

**Issue by himanverma** [cakephp/cakephp#7578]
if i do Cache::disable() in AppController then this is resolved .. it seems issue is with serialization of Carbon Object

```
2015-10-19 16:24:12 Error: [InvalidArgumentException] Unknown setter 'date'
Request URL: /
Stack Trace:
#0 (): Carbon\Carbon->__set()
#1 (): DateTime->__sleep()
#2 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php(148): serialize()
#3 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Cache/Cache.php(234): Cake\Cache\Engine\FileEngine->write()
#4 /var/www/zakoopi.com/releases/1/src/Controller/AppController.php(180): Cake\Cache\Cache::write()
#5 /var/www/zakoopi.com/releases/1/src/Controller/PagesController.php(75): App\Controller\AppController->beforeFilter()
#6 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Event/EventManager.php(385): App\Controller\PagesController->beforeFilter()
#7 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Event/EventManager.php(355): Cake\Event\EventManager->_callListener()
#8 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch()
#9 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Controller/Controller.php(491): Cake\Controller\Controller->dispatchEvent()
#10 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 /var/www/zakoopi.com/releases/1/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke()
#12 /var/www/zakoopi.com/releases/1/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch()
#13 /var/www/zakoopi.com/releases/1/index.php(16): include()
#14 {main}
```

Please guy if carbon lib is no longer maintained then please find an alternative... so cake 3 can work on HHVM

**Comment by markstory** [comment]
@himanverma We've already started work on an [alternative for carbon](https://github.com/cakephp/chronos). It will likely land in 3.2.0.

**Comment by markstory** [comment]
Moving to 3.2 as we will not be able to address this until then.

**Comment by himanverma** [comment]
thanks @markstory for consideration and informing me ..
i'll be waiting for 3.2 so that i can test it over HHVM

**Comment by markstory** [comment]
@himanverma 3.2-dev now has the replacement for carbon in place. If the issue with HHVM persists, we can actually fix it now.

**Comment by himanverma** [comment]
thanks Mark I will update and verify it over my HHVM instance after that let you know if problem persists

happy coding



Sent from my Mi phoneOn Mark Story <notifications@github.com>, Nov 18, 2015 9:22 PM wrote:@himanverma 3.2-dev now has the replacement for carbon in place. If the issue with HHVM persists, we can actually fix it now.

**Comment by markstory** [comment]
Closing this as 3.2 is using chronos which will run correctly on the next version of HHVM.

**Comment by himanverma** [comment]
Once again issue on HHVM

Unknown setter 'date'
InvalidArgumentException
Documentation API
If you want to customize this error message, create src/Template/Error/error500.ctp

toggle vendor stack frames
⟩ Cake\Chronos\MutableDateTime->__set
[internal function]
⟩ DateTime->__sleep
[internal function]
⟩ serialize
CORE/src/ORM/ResultSet.php, line 310
⟩ Cake\ORM\ResultSet->serialize
[internal function]
⟩ serialize
CORE/src/Cache/Engine/FileEngine.php, line 148
⟩ Cake\Cache\Engine\FileEngine->write
ROOT/vendor/cakephp/debug_kit/src/Cache/Engine/DebugEngine.php, line 122

**Comment by jippi** [comment]
@himanverma can you please provide an isolated test case that we can use for debugging the issue?

**Comment by himanverma** [comment]
Hi Christian,if you need i can provide you access of my AWS instance so you can better debug the issue.send me your E-mail
Thanks,Himanshu

Date: Tue, 3 May 2016 08:42:48 -0700
