### ISSUE TITLE
3.x - stream_context_create on php 5.6.8 expect peer_name without transport

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#7579]
when using ssl:// in host Network\Socket throws error

```stream_socket_client(): Peer certificate CN=`smtp.gmail.com' did not match expected CN=`ssl://smtp.gmail.com' stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://smtp.gmail.com:465 (Unknown error)```

the peer_name is set as host:
https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L199

in http://book.cakephp.org/3.0/en/core-libraries/email.html#configuring-transports there is note about just adding 'ssl://' to host but on code it expects it on 'protocol' option
https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L133

also on side note

https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L131 
and can be still null on
https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L150

**Comment by markstory** [comment]
We should be able to split out the protocol from the host in connect().

**Comment by markstory** [comment]
Pull request is up now.
