### ISSUE TITLE
Call to a member function clearContain() on null

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#7580]
_From @shingosama on October 19, 2015 19:30_

Hello, i want override contain with second parameter on "true" on my query, but CakePHP return fatal error : Call to a member function clearContain() on null

Here my query :

```
$feeds = $this->Feeds->find()
                ->contain([
                    'Users.Profiles.Avatars',
                    'Questions.Categories',
                    'Statuses',
                    'Cities',
                        ], true)
                ->where(['Users.username' => $this->request->data['username']])
                ->order(['Feeds.created' => 'DESC']);
```

I tested with some query and CakePHP return same error. What is the problem ?

Thank you !

_Copied from original issue: cakephp/orm#5_

**Comment by markstory** [comment]
I can take a look, I suspect I caused this.

**Comment by markstory** [comment]
I'm not able to reproduce the issue you're having locally. I tried:

```php
        $table = TableRegistry::get('Articles', ['table' => 'articles']);
        $table->belongsTo('Authors');

        $query = $table->find();
        $query->contain(['Authors'], true);
```

And there was no fatal error. Before call `contain()` what does `$query->eagerLoader()` return?

**Comment by shingosama** [comment]
Before call contain(), $query->eagerLoader() return this :
```
object(Cake\ORM\EagerLoader) {
	[protected] _containments => []
	[protected] _normalized => null
	[protected] _containOptions => [
		'associations' => (int) 1,
		'foreignKey' => (int) 1,
		'conditions' => (int) 1,
		'fields' => (int) 1,
		'sort' => (int) 1,
		'matching' => (int) 1,
		'queryBuilder' => (int) 1,
		'finder' => (int) 1,
		'joinType' => (int) 1,
		'strategy' => (int) 1,
		'negateMatch' => (int) 1
	]
	[protected] _loadExternal => []
	[protected] _aliasList => []
	[protected] _matching => null
	[protected] _joinsMap => []
	[protected] _autoFields => true
}
```
after return null

**Comment by shingosama** [comment]
I have tested this query :

```
$table = TableRegistry::get('Feeds', ['table' => 'feeds']);
$table->belongsTo('Questions');
$query = $table->find();
$query->contain(['Questions'], true);
debug($query); die();
```
The result is fatal error :

Error: Call to a member function clearContain() on null
File /var/www/genku/public_html/vendor/cakephp/cakephp/src/ORM/Query.php
Line: 292

**Comment by markstory** [comment]
So subsequent calls to eagerLoader() after the first return `null`?

**Comment by shingosama** [comment]
CakePHP return the same error :

```
$table = TableRegistry::get('Feeds', ['table' => 'feeds']);
        $table->belongsTo('Questions');

        $query = $table->find();
        $query->contain(['Questions'], true);
        debug($query->eagerLoader()); die();
```
If i remove true on contain(), eagerLoader() return an array :
```
src/Controller/Ajax/FeedsController.php (line 34)

object(Cake\ORM\EagerLoader) {
	[protected] _containments => [
		'Questions' => []
	]
	[protected] _normalized => null
	[protected] _containOptions => [
		'associations' => (int) 1,
		'foreignKey' => (int) 1,
		'conditions' => (int) 1,
		'fields' => (int) 1,
		'sort' => (int) 1,
		'matching' => (int) 1,
		'queryBuilder' => (int) 1,
		'finder' => (int) 1,
		'joinType' => (int) 1,
		'strategy' => (int) 1,
		'negateMatch' => (int) 1
	]
	[protected] _loadExternal => null
	[protected] _aliasList => []
	[protected] _matching => null
	[protected] _joinsMap => []
	[protected] _autoFields => true
}
```

**Comment by markstory** [comment]
CakePHP and the ORM used independently will always yield the same results. The thing I'm struggling to reproduce is the fatal error. The code I pasted earlier does not create a fatal error in PHP 5.5 for me. 

What version of cakephp/orm are you using?

**Comment by shingosama** [comment]
CakePHP version : 

> cakephp/bake                          1.1.0              Bake plugin for CakePHP 3.0
  cakephp/cakephp                       3.1.1              The CakePHP framework
  cakephp/debug_kit                     3.2.1              CakePHP Debug Kit
  cakephp/migrations                    1.4                Database Migration plugin for CakePHP 3.0 based on Phinx
  cakephp/plugin-installer              0.0.12             A composer installer for CakePHP 3.0+ plugins.

How to get ORM version ?

**Comment by markstory** [comment]
The ORM version is the same as cakephp/cakephp.

**Comment by ADmad** [comment]
@shingosama Upgrade to 3.1.2 and the issue will be gone.

**Comment by shingosama** [comment]
Thank you ! I updated CakePHP and actually it works now . I recently performed an update , so I do not think the problem was there. thank you again.
