### ISSUE TITLE
2.7.5 Possible anomaly with Digest Authentication Response and Exception

### ISSUE THREAD

**Issue by plingo** [cakephp/cakephp#7582]
Accessing an endpoint protected with Digest Auth via cURL generates a first HTTP response of 401, followed by a second user+pass+realm request that authorize the client (HTTP 200).
This seems to be the correct "handshaking" process when using Digest Auth (RFC2617), but Cake Error will log the 401 (Unathorized) Exception in log files.
I don't think it has to be recorded as a real "Unathorized Request" and I don't know how to exclude this particular case from being logged.
Than you very much.

**Comment by markstory** [comment]
Use the `Error.skipLog` configuration option to blacklist logging of UnauthorizedException.
