### ISSUE TITLE
New booltype don't allow nullboolean

### ISSUE THREAD

**Issue by RignonNoel** [cakephp/cakephp#7583]
With the new version 3.1.2 we can't create a null boolean because Class BoolType line 43 don't allow nullBoolean.

It's a big problem, all test doesn't work because i've null in my fixtures :
```Exception: Cannot convert value to bool in [/home/rignonnoel/Documents/Code/OfficialRepository/Website/vendor/cakephp/cakephp/src/Database/Type/BoolType.php, line 47]```

And my site doesn't work when a user change his gender or other nullboolean.

Because of this issue, we can't upgrade to the 3.1.2.

Thanks.

**Comment by RignonNoel** [comment]
Change 

`if ($value === true || $value === false || is_null($value))`

by

`if ($value === true || $value === false || is_null($value))`

**Comment by markstory** [comment]
I'm guessing you have nullable boolean fields in your schema?

**Comment by RignonNoel** [comment]
Yes.
I've some boolean type in migraions file, authorized to be null if the user never use the form.

**Comment by RignonNoel** [comment]
And we authorize to reset to null if the user want delete information.

**Comment by markstory** [comment]
Ok, I can restore the `null` value :smile:

**Comment by markstory** [comment]
Fixed with #7585

**Comment by RignonNoel** [comment]
Thanks.

**Comment by markstory** [comment]
The reason we generally close tickets when the pull request is put up, is we were often forgetting to close tickets post merge and would be left with piles of dead tickets over time.

We also don't close issues on pull request open, unless there is a very good chance the change will be merged.
