### ISSUE TITLE
Marshaller not respecting the save strategy

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#7584]
When saving data with belongstomany associations, append strategy cannot be applied for adding new rows instead updating them when same foreign key is used. I have put the code in this gist.
https://gist.github.com/gauravmak/710e7a370ad6f55c2fc6

**Comment by markstory** [comment]
The marshaller has never been aware of save strategies as its not relevant to its role. In general the ORM attempts to prevent duplicate join records for belongsToMany associations with the same foreign keys.

From what's in the paste you might be better off modelling your association as Register HasMany RegisterPayments, and RegisterPayments BelongsTo PaymentTypes

**Comment by gauravmak** [comment]
@markstory, the relationship between them is that of "ArticlesTags" type actually. This statement from the docs applies to them perfectly - **The main difference between hasMany and BelongsToMany is that the link between the models in a BelongsToMany association are not exclusive.**

In fact, I am facing the same problem with other couple of relationships as well. They are also of type - *BelongsToMany*

**Comment by markstory** [comment]
The specific comment your referring to is referencing the idea that while the rows on both sides of the relationship are not exclusive, there can only be one link between each row combination in the current belongstomany implementation. This is because often time the junction table is a simple two column table, and duplicates are not logical or helpful. The fact that you want duplucates make me believe that using a has many association will provide less friction/trouble.

**Comment by gauravmak** [comment]
That's right. I am heartily thankful for your expert opinion over this topic. Following your suggested way...

**Comment by lorenzo** [comment]
I would not mind respecting the saving strategy in the marshaller, it kind of makes sense to do it.

**Comment by markstory** [comment]
@lorenzo That will get tricky as people could be marshalling associations that were not loaded.

**Comment by mylux** [comment]
Applying save strategy into the marshaller means to have a complexity that was only part of the Association now also present into the Marshaller. It seems weird to distribute the responsibility of the association into the Marshaller as well
Also, I think that the Marshaller has no commitment to treat duplicated keys.

**Comment by markstory** [comment]
@mylux I agree, the marshaller is already a very complex bit of code, and I have concerns that adding save strategies will create more opportunities for mistakes to happen and logic to not be in sync.

**Comment by markstory** [comment]
Closing as I think this will add a non-trivial amount of complexity and result in coupling the marshaller even more to the association classes.
