### ISSUE TITLE
3.1.2 Breaking Changes

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7586]
After the update to Cake 3.1.2 I get the following strange error.

![image](https://cloud.githubusercontent.com/assets/5982785/10616054/774dcfae-7763-11e5-8842-04e943f5995a.png)

It seems that Cake tries to load the fixtures in a non-test environment. Never seen such an issue before, so unfortunately I cannot provide more details right now... If you want to know something specific, let me know I will try to answer as soon as possible.

With Cake 3.1.1 everything works fine.

**Comment by ADmad** [comment]
For the time being don't load DebugKit and the error will be gone.

**Comment by markstory** [comment]
This is likely an issue in how debugkit was abusing fixtures. I would count the core changes as API breaking, as no methods changed. However, some semantics in how methods work totally did change and that is what is causing this issue. Debugkit does sime trickery with fixtures which is now failing. I will have a fix up tonight for debug kit.

**Comment by markstory** [comment]
Closing as there is a pull request open for debugkit now. I'll will do a release once it has been merged.
