### ISSUE TITLE
HasMany associations - Failures not being considered when replacing associations

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#7588]
When using the replace strategy, `HasMany::saveAssociated()` doesn't return `false` in case an error happens in the unlink/delete process (for example when a `delete` application rule fails, an event aborts the saving process, etc..)

**https://github.com/cakephp/cakephp/blob/3.1.2/src/ORM/Association/HasMany.php#L152**

thus making it impossible to handle failures and roll back changes.

Ping @mylux 
Refs #7477

**Comment by mylux** [comment]
Ok, I've got your point. It looks like we need another pull request to improve the application in this aspect. I am not sure if I can include these functionalities within the other pull request regarding link, unoink and replace methods that is already open.

**Comment by markstory** [comment]
@mylux A separate pull request to fix the issue would be good.

**Comment by mylux** [comment]
Hello, this is my next target. I will start working on it today!

**Comment by markstory** [comment]
@mylux Awesome!

**Comment by mylux** [comment]
@ndm2 , could you post here more details about this issue?

 I can see that if you have cascade callbacks, the deletions will happen one by one and that is one point in which some rules can affect the behavior of the replace process, so I will check for each one of the deletion results when they are performed to check whether the replace action is going on ok or not.

If cascade callbacks are not required, then the updates/deletions will happen in bulk.
I can also check by the result of those methods (they inform the amount of affected records) and if there were no affected records, it can be considered as a failure as well, do you agree?

But for this ones to work properly I will also insert an additional condition to not consider an empty set of records to be deleted as a failure.

Do you see more to be done there?

**Comment by markstory** [comment]
> I can also check by the result of those methods (they inform the amount of affected records) and if there were no affected records, it can be considered as a failure as well, do you agree?

No affected rows doesn't always mean a failure. There might be no rows to replace.

**Comment by mylux** [comment]
Indeed. But in this case I was assuming that if you are explicitly calling a replace method, you should be sure that there are entities to replace.
But even if there aren't, what I could do is to apply a find using the conditions and extracting the list of ids (primary keys). If there are 0 records, it just returns true. If there are one or more records, then apply a delete and analyze the amount of affected rows. Does it seem better?

**Comment by markstory** [comment]
I think checking the row count before replacing is a more robust solution.

**Comment by mylux** [comment]
OK. I will proceed this way, then.

**Comment by mylux** [comment]
@markstory , I have just implemented the change, but I don't have a good idea of a test for it. How could I test if the replace method returns false if it is not possible to delete/update the records in the database?

**Comment by markstory** [comment]
You could delete all the fixture data and then call replace(). If you are interested in testing more edge case failures, you might have to use mocks.

**Comment by mylux** [comment]
Provided a solution on PR #7632

**Comment by markstory** [comment]
Closing as a pull request is up now.
