### ISSUE TITLE
Way to disable base64 encode on CakeEmail

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#7594]
I'd like a way to disable the base64 encode of individual attachments in CakeEmail.

I'm having a hard time finding actual documentation stating this, but I've tried everything I can to verify this.  It seems ".eml" files are treated specially by at least a few email vendors.  They really want them encoded as plain text.

If I change the 2 lines (in the CakeEmail class) related to base64 encoding, the attachment works as expected.

**Comment by markstory** [comment]
You cannot disable the base64 encoding because it causes all sorts of issues with binary files. Email has a number of restrictions on line length that cannot be accommodated by binary blobs.

Are you looking for a way to optionally control encoding and content type headers on a per attachment basis?

**Comment by watermark** [comment]
I agree that it's necessary to base64 encode binary files.  I would like to see a method of controlling the encoding on a per attachment basis.  The method of setting the content-type that is already in place works fine for me.

Thunderbird seems to always use "7bit" encoding for ".eml" files.  The headers that it seems to always use for the mime body part of the ".eml" are:
Content-Type: message/rfc822; name="FW: file.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="FW: file.eml"

**Comment by markstory** [comment]
Ok. The attachment() method is probably the place you'll want to add the new feature :smile:

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
