### ISSUE TITLE
[3.1.2] Prefix Routing Exception

### ISSUE THREAD

**Issue by eAliwei** [cakephp/cakephp#7595]
### routers.php
```php
Router::defaultRouteClass('DashedRoute');

Router::prefix('services', ['_ext' => 'json'], function ($routes) {
    $routes->connect('/cities', ['controller' => 'Cities', 'action' => 'index']);
});
```
### routes 
```bash
sudo ./bin/cake routes
```
![image](https://cloud.githubusercontent.com/assets/6028737/10662936/52a647de-78ea-11e5-8b75-70d62dc4c845.png)

### home.ctp
```php
      $this->Html->link('Cities Url', [
        'controller' => 'Cities',
        'action' => 'index',
        '_ext' => 'json',
        'prefix' => 'services',
        'plugin' => null
      ])
```

### Missing Route

![image](https://cloud.githubusercontent.com/assets/6028737/10663042/0fe4b2a4-78eb-11e5-8a2a-5d6002264f9d.png)

### URL in browser 

![image](https://cloud.githubusercontent.com/assets/6028737/10663098/3ba6f00a-78eb-11e5-9633-79252f67d64c.png)

**Comment by Wouter0100** [comment]
```php
Router::defaultRouteClass('DashedRoute');

Router::prefix('services', function ($routes) {
    $routes->extensions(['json']);
    $routes->connect('/cities', ['controller' => 'Cities', 'action' => 'index']);
});
```

Why use `_ext`? Or don't you want the `.json` extension in the URL?

**Comment by eAliwei** [comment]
@Wouter0100 
yeah~!  I don't want the <code>.json</code> extension in the URL.
But i wanna get the return value of JSON.
I want render <code>"Template/Cities/json/index.ctp"</code>

http://book.cakephp.org/3.0/en/views/json-and-xml-views.html#using-a-data-view-with-template-files

**Comment by ADmad** [comment]
@eAliwei json extension parsing/matching will only work if you enable it using `$routes->extensions(['json'])`. If you want to use `json` subfolder without using json extension then you should manually set `$this->viewBuilder()->templatePath()` or use `$this->RequestHander->type($this, 'json')`.
