### ISSUE TITLE
Getter for original entity-property

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#7596]
It would be helpful, if there would be a getter, to receive all values stored in the original property of an entity. Of course, you could use `extractOriginal()` with all field names of the entity, but it might be more convenient if there is a method like `getErrors()`.

**Comment by markstory** [comment]
So something like `getOriginal()`?

**Comment by cleptric** [comment]
Yes, that would be fine.

**Comment by markstory** [comment]
@cleptric That [exact method exists already](http://api.cakephp.org/3.1/class-Cake.Datasource.EntityTrait.html#_getOriginal) :smile:

**Comment by cleptric** [comment]
Yes, but you have to pass the property name to this method. So, why not `getOriginals` and returning all values from the original property of the entity?

**Comment by markstory** [comment]
Ok, that method doesn't exist then.

**Comment by JD-Robbs** [comment]
Or, maybe, rather than throwing an InvalidArgumentException when passing no arguments to the existing method could return the original state.

**Comment by sdustinh** [comment]
That would be really useful for `dirty()` too.

**Comment by markstory** [comment]
@JD-Robbs That could work, I would want extract() to work the same way though.

**Comment by sdustinh** [comment]
If calling `extract()` without any parameters returns all properties then would it be reasonable to expect `extract(true)` to return all dirty properties? Otherwise you end up with something like `extract(null, true)`. If the shortcut way is preferred then there becomes a conflict with the [`EntityInterface`](https://github.com/cakephp/cakephp/blob/master/src%2FDatasource%2FEntityInterface.php#L110).

```php
public function extract($properties = null, $onlyDirty = false)
    {
        if ($properties === null) {
            $properties = array_keys($this->_properties);
        } elseif ($properties === true || $properties === false) {
            $onlyDirty = $properties;
            $properties = array_keys($this->_properties);
        }
        
        $result = [];
        
        foreach ((array)$properties as $property) {
            if (!$onlyDirty || $this->dirty($property)) {
                $result[$property] = $this->get($property);
            }
        }
        
        return $result;
    }
```

**Comment by markstory** [comment]
@sdustinh I would think to not cause interface issues, we would end up with something like `extract([], true)`.

**Comment by burzum** [comment]
@markstory how about `extractAll()` as a convince method for `extract([], true)`?

**Comment by markstory** [comment]
@burzum A separate method would be :+1: the original goal of this issue was to provide a way to get all the original values. Perhaps something like `getOriginalValues()` then?

**Comment by burzum** [comment]
Closing this now because we have a PR open.
