### ISSUE TITLE
Fix (Save and Validate) in CakePHP 2.6.11

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#7599]
Hi, problem in SAVE() model
Do not save the change, because it would be invalid because it would lack the parameters **"'habilitado' => false"**, but this is not correct, since it is clear that all the data are, if you look at the "Out Debug Vars"

**Model validation "ProductosStocks "**
```php
class ProductosStocks extends AppModel
{
public $validate = array(
.......
'habilitado' => array(
            'notEmpty' => array(
                'rule' => array('notEmpty'),
                'message' => 'Este campo no puede estar vació',
                //'allowEmpty' => false,
                //'required' => false,
                //'last' => false, // Stop validation after this rule
                //'on' => 'update', // Limit validation to 'create' or 'update' operations
            ),
            'boolean' => array(
                'rule' => array('boolean'),
                'message' => 'Se permite true o false',
                //'allowEmpty' => false,
                //'required' => false,
                //'last' => false, // Stop validation after this rule
                //'on' => 'create', // Limit validation to 'create' or 'update' operations
            )
        ),
.....
)
}
```

**Controller Test**
```php
(line 326): debug($ps_cambio);
(line 327): debug($ps->save($ps_cambio));
(line 328): exit(debug($ps->validationErrors));
```

**Out Debug vars:**
```php
/app/Model/Behavior/ProductosStocksMovExternosDetallesBehavior.php (line 326)
array(
	'ProductosStocks' => array(
		'id' => '116',
		'codigo' => 'SROENTK4SCL',
		'descripcion' => 'SALMON ROSADO - ENTERO 4/5 - CRUDO FRESCO  - CHILE - VENTA AL PESO',
		'descripcion_interna' => 'Import',
		'requiere_senasa' => true,
		'senasa_especies_id' => '1',
		'senasa_productos_id' => '1',
		'senasa_look_etiquetas_id' => '1',
		'senasa_temperaturas_id' => '1',
		'familia_productos_id' => '1',
		'grupo_productos_id' => '1',
		'tipos_unidades_id' => '1',
		'stock_real' => (float) 0,
		'stock_comprometido' => (float) 0,
		'stock_reposicion' => '150.00',
		'stock_minimo' => '150.00',
		'precio_compra' => '0.00',
		'habilitado' => false,
		'created' => '2015-09-21 13:23:32',
		'modified' => '2015-09-21 13:23:32'
	)
)

/app/Model/Behavior/ProductosStocksMovExternosDetallesBehavior.php (line 327)
false

/app/Model/Behavior/ProductosStocksMovExternosDetallesBehavior.php (line 328)
array(
	'habilitado' => array(
		(int) 0 => 'Este campo no puede estar vació³'
	)
)
```

Greetings and hope to be right.

**Comment by HavokInspiration** [comment]
Your field ``habilitado`` is ``false`` so considered "empty".

You should probably try :

```php
public $validate = array(
     'habilitado' => array(
          'boolean' => array(
                'rule' => array('boolean'),
                'message' => 'Se permite true o false',
                'required' => true
          )
     )
)
```

Having the rule ``required`` means that the array key must be present in the data you are validating.

**Comment by EOM** [comment]
Thanks HavokInspiration, if correct. with the validator as you believe it, I tried it and it works well. 
But I believe it would also have to be valid. Since CakePHP would have to verify that this validating a Boolean that way may be correct any of these "0", '0', 0, false, true, 1, '1',"1"

Is FIX entonce would be a mine or a logical problem in $ validate programming when I work with boolean ..?

Greetings and thanks again

**Comment by ADmad** [comment]
>  Since CakePHP would have to verify that this validating a Boolean that way may be correct any of these "0", '0', 0, false, true, 1, '1',"1"

`boolen` rule already does that.

**Comment by EOM** [comment]
Ok Ahmad, fart this also should not have valid data with the data happens to SAVE () and show no mistake as the debug out ..?

Thanks and sorry for my English but was traducio by Google Translator ;-(

```PHP
class ProductosStocks extends AppModel
{
public $validate = array(
.......
'habilitado' => array(
            'notEmpty' => array(
                'rule' => array('notEmpty'),
                'message' => 'Este campo no puede estar vació',
                //'allowEmpty' => false,
                //'required' => false,
                //'last' => false, // Stop validation after this rule
                //'on' => 'update', // Limit validation to 'create' or 'update' operations
            ),
            'boolean' => array(
                'rule' => array('boolean'),
                'message' => 'Se permite true o false',
                //'allowEmpty' => false,
                //'required' => false,
                //'last' => false, // Stop validation after this rule
                //'on' => 'create', // Limit validation to 'create' or 'update' operations
            )
        ),
.....
)
}
```

**Comment by HavokInspiration** [comment]
With the validate array you posted, it's expected that the ``habilitado`` field triggers the error. Because its value is ``false`` in the debug output you posted (and ``false`` means empty).

You are validating a "true or false" checkbox, am I correct ? 
If so, you should only have the ``boolean`` rule with ``required`` set to true as I posted in my initial comment : this will ensure that the ``habilitado`` key is present in your data array AND it will validate it as a boolean value.

**Comment by EOM** [comment]
If Right and work perfect for the Form, but when I want to make changes from the controller.
I have problems too, because I am obliged to recover the field **"habilitado"** or disable the validation to run save (), to have it **"'required' => true"**

So with that solution works well FORM way, but I have problem to use it from the controller.

**Example:**

```PHP
$d = array('ProductosStocks' => array(
            'id' => '116',
            'codigo' => 'SROENTK4SCL',
            'descripcion' => 'SALMON ROSADO - ENTERO 4/5 -....',
            'descripcion_interna' => 'Change TEST',
        ));
       // Debug
       (line 31): debug($this->ProductosStocks->save($d));
       (line 32): exit(debug($this->ProductosStocks->validationErrors));
```

**Debug Out:**
```PHP
/app/Controller/ProductosStocksController.php (line 31)
false
/app/Controller/ProductosStocksController.php (line 32)
array(
	'habilitado' => array(
		(int) 0 => 'Se permite true o false'
	)
)
```

But their response, not a logical FIX CakePHP, if not my problem how utiliso validator models, when it is a boolean field.

Greetings and thanks again

**Comment by HavokInspiration** [comment]
Oh ok, then, don't put the ``'required' => true``.
Validation on the field will be done only if you provide it in the data you are validating.
