### ISSUE TITLE
Validation rules cakephp 3, unique field and active column

### ISSUE THREAD

**Issue by kidach** [cakephp/cakephp#7607]
I have filed "type" that need to be unique and rule for the field "active" == 1.

```php
$validator
        ->notEmpty('type')
        ->add('type', [
            'unique' => [
               'rule' => ['validateUnique', ['scope' => ['active' => '1']]],
               'provider' => 'table', 
               'message' => 'Not unique']
            ]);
```

Example: 
If i have in database with two columns and values below.

type          |      active
admin       |          0

Validation need's to allow me insert if value of field "type" is same and active = 0

If type is same and active = 1 need's to return error(filed must be unique..).

**Comment by markstory** [comment]
You will need to write a custom validator for this. The default validateUnique will not be able to it.
