### ISSUE TITLE
3.1 - CounterCacheBehavior ignores bindingKey configuration

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#7609]
When setting up associations using the `bindingKey` option the CounterCacheBehavior will not utilize this setting in the `_processAssociation` method. This leads PHP to trigger a warning when `array_combine()` is run with arrays that do not have the same number of values.

**Comment by lorenzo** [comment]
Do you want to provide a fix for this issue?

**Comment by markstory** [comment]
Or some code to help reproduce the issue?

**Comment by sdustinh** [comment]
I'd be happy to patch this. It's just a single check to see if the binding key has been set. When I put this issue in yesterday I just didn't have time to take care of it. I'll put in a PR in a moment.

**Comment by sdustinh** [comment]
Oh and just to give an example on how to reproduce this...

```php
// StocksTable.php
public function initialize(array $config)
{
    // This table has an auto incrementing field called `id` that is normally
    // its primary key. Uncommenting this `primaryKey()` call will fix the issue
    // with the CounterCacheBehavior but will mess up all other associations.
    
    //$this->primaryKey(['facility_id', 'product_id', 'status_id']);
    
    $this->hasMany('Inventory.Assets', [
        'bindingKey' => ['facility_id', 'product_id', 'status_id'],
        'foreignKey' => ['facility_id', 'product_id', 'status_id']
    ]);
}

// AssetsTable.php
public function initialize(array $config)
{
    $this->addBehavior('CounterCache', [
        'Stocks' => ['quantity']
    ]);
    $this->hasOne('Inventory.Stocks', [
        'bindingKey' => ['facility_id', 'product_id', 'status_id'],
        'foreignKey' => ['facility_id', 'product_id', 'status_id']
    ]);
}
```

I still had to make my own version of the counter cache behavior to create a record that did not exist (new asset that was being tracked by the stocks table). Because I was modifying the keyed relationship with these tables the counter cache was not checking for that.

**Comment by markstory** [comment]
If you know how to fix this a pull request woild be awesome.

**Comment by sdustinh** [comment]
I got the work done on it yesterday but I haven't had time to add testing or even put the PR in. Job keeps getting in the way. :frowning:  I'll try to get it in today. It is a very simple fix.

**Comment by sdustinh** [comment]
Sorry for the hold up. Long days at work get longer. I put in a PR for this. Look it over and let me know if I missed anything. It's possible at the end of the day.

**Comment by markstory** [comment]
Pull request looks good. I'll manually merge it into `master` as this is more of a bug fix than a new feature.
