### ISSUE TITLE
3.1: Don't forget about invalidated data in entities

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7615]
I basically did
```php
$entities = $this->Examples->newEntities($array);

foreach ($entities as $entity) {
	$entityErrors = $entity->errors();
	if (!$entityErrors) {
		continue;
	}
	// Write error message of all fields incl input data that failed
```

But the entity does not contain the field data anymore (name and original_name):
```php
object(App\Model\Entity\Example) {
	'status' => (int) 2,
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'status' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [
		'name' => [
			'isUnique' => 'valErrRecordNameExists'
		],
		'original_name' => [
			'isUnique' => 'valErrRecordNameExists'
		]
	]
}

```

I would have at least expected to have the failed field data available to make the error message clear where (what data) it failed, e.g.

```php
	'[invalid]' => [
		'name' => 'Foo',
		'original_name' => 'Bar',
	],
```

Which each [errors] entry of validation error messages it could then get the [invalid] entry of the data that was trying to be patched and make this the display error message in the view.

**Comment by markstory** [comment]
Invalid data is not set into the entities.

**Comment by dereuromark** [comment]
That is *exactly* my point.

**Comment by lorenzo** [comment]
You do know why, you get error messages...

**Comment by dereuromark** [comment]
Yes "failed" not "data xyz failed". So the error message is not saying anything.. :/

**Comment by lorenzo** [comment]
What about using the validator for producing such messages? You have all the data you need there, and it also seems like a good place for doing it

**Comment by dereuromark** [comment]
It still sounds more logically to me to keep the entity complete, not losing information during the invalidation process (when patching). This makes it easier to access the invalidation data along with the reason even after validation if needed.
What is the reason you are reluctant to keep those?

**Comment by dereuromark** [comment]
And how exactly should your proposal work when using

    $entities = $this->Examples->newEntities($arrayOfRecords);

as everything is lost now somewhere between those lines.
I find it very important to also transport the information what data cannot be persisted due to validation errors. Right now one would have to use the numerical array keys and hope that you can make a matching between array (data) and entities this way..

**Comment by dakota** [comment]
I think having `$entity->invalid()` would be very useful. Does not need to be marshalled data, just simply a direct copy of the value that failed validation.

**Comment by dereuromark** [comment]
That's exactly what I was thinking. No processing of any sort, just a basic copy of the value.

**Comment by lorenzo** [comment]
I meant in the validator you have all the information you need to build the messages. No need to match indexes

**Comment by dereuromark** [comment]
But you cannot always enhance the validation this way - quite invasive. In this case they are also translated and can stay as simple as they are. We just need to also use the invalidated data to make a flash message or log entry that involves the details.

**Comment by markstory** [comment]
So we'd have `_properties`, `_invalid`, and `_original`, and methods to get/extract/set all 3?

**Comment by dereuromark** [comment]
`invalid` should not be set from outside, it can only be set when writing into `errors` and therefore is readonly. Original also should not be touched, as it never is added to properties.

**Comment by lorenzo** [comment]
It will be set from the outside, since it is the marshaller triggering the validation, not the entity itself

**Comment by dereuromark** [comment]
So writing invalid and errors together should suffice. No touching of properties or original.

**Comment by markstory** [comment]
I meant that there would be 3 places where properties would live.

**Comment by dereuromark** [comment]
Technically, invalid aint properties, but part of the errors message data block.

**Comment by dereuromark** [comment]
We could either do this:
https://github.com/cakephp/cakephp/compare/master-entity-invalid

Or we could try to make the errors to simple objects, to hold both the message and the data that caused it.
BC by falling back to the message on __toString() etc.

**Comment by markstory** [comment]
Errors being objects could work well, it might cause issues if people are doing string shenanigans with them though.

**Comment by dereuromark** [comment]
I'd probably go for objects for 4.0, and go with the invalid property for 3.x for BC.

**Comment by dereuromark** [comment]
PR is open.
