### ISSUE TITLE
$this->Html->meta forces meta/link without choice

### ISSUE THREAD

**Issue by elb98rm** [cakephp/cakephp#7616]
In an attempt to use best practice in CakePhp I'm attempting to use the $this->Html->meta() method to create matadata. As part of a varied favicon approach, it became clear that the function is missing the ability to manually choose between `<link .. />` and `<meta ../>`

There seems to be no way to create the following links:

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
```

All of these are valid code items. However, there is no way I can see to make the `meta()` method produce a `<link .. />` element. It either detects a certain type and switches, or sticks to `<meta .. />`.

I suggest an optional extra item to View/Helper/HtmlHelper.php (line 226):

`public function meta($type, $content = null, array $options = [], $element_type = 'auto') { .. }`

`$element_type = 'auto'` maintains existing behaviour. 
From here the function could either accept a variable and use it, or choose 'link' or 'meta'.

I'm happy to fork the repo in the future, but this seems like an omission to the functionality.

Can this be confirmed as desired functionality? Would you want me to look at this?

Thanks
Rick

**Comment by markstory** [comment]
Why wouldn't you just output the tags directly? There doesn't seem to be a need to use a helper for those meta tags.

**Comment by dereuromark** [comment]
You can always PR your proposed changes for easier discussion.

But it might be easier to output those tags as pure HTML - or use a plugin solution for it.
See [this](https://github.com/dereuromark/cakephp-meta/blob/master/tests/TestCase/View/Helper/MetaHelperTest.php#L215) for example as for your icon links.

**Comment by ADmad** [comment]
Method named meta() producing <link> tags doesn't sound intuitive.

Just directly write html or make your own helper as already suggested.

**Comment by elb98rm** [comment]
Thanks for the prompt feedback all.

@markstory : The documentation really pushes you to use helpers as much as possible. I know you don't specifically need to, and currently I'm just directly outputting them. 

I used the helper, as i'm attempting to copy the process in the the default template (Template/Layout/default.ctp). It uses the `$this->Html->meta()` to generate a `<link .. />` element.

I'd assume that this is best practice? @ADmad - I know it's not the most intuitive, but it is what is effectively recommended. The helper already generates a link item when `$type` is set to be 'html', 'rss', 'atom' or 'icon'... In particular I would argue that the exact changes I'm proposing are for more modern versions of the 'icon' property.

@dereuromark  I'll finish this project off over the next week (I need to actually deliver the system!), then look at this. I also just want to check; "You can always PR your proposed changes for easier discussion.".. do you mean pull request? Apologies - I've never used github as a bug tracking tool, the organisations I've been in always have other solutions. Obviously I'll have a read of the recommendations before I do anything.

Thanks all. I'll update shortly.

**Comment by markstory** [comment]
@elb98rm The documentation covers using the helpers, because that is its purpose. It is an assumed that the reader will know that they can still use HTML as well. Generating link elements could be one place where we cover not using the helpers though.

**Comment by elb98rm** [comment]
@markstory Thanks for responding.

I know the end user can use HTML to create the links... I'm saying that the documentation implies that they can and *should* use the helper. If using the helper is best practice, then I'm suggesting that the helpers should probably be a touch more flexible. I think this would be the best approach. 

In terms of documentation, I certainly didn't find it easy to understand that you can't do what I wanted. Now, the documentation isn't bad.. but it doesn't explain the limitations well. It personally took me a good hour to work out that I couldn't do what I wanted. 

Personally, I don't the end user shouldn't have to bypass CakePHP's approach for something that is relatively common... but this leads onto my question:

Do you WANT the flexibility, or do you want to be clearer in the documentation. I'm happy to have a look at the code soon if you think it's appropriate.

**Comment by markstory** [comment]
@elb98rm Fair point about the documentation not being clear that all types of 'meta' tags couldn't be generated through it. I took another look at the code, and found some fun undocumented behavior that I think gets you what you're looking for:

```php
echo $this->Html->meta(['link' => 'http://example.com/manifest', 'rel' => 'manifest']);
// <link href="http://example.com/manifest" rel="manifest"/>
```

**Comment by markstory** [comment]
Docs updated in cakephp/docs#3458
