### ISSUE TITLE
Session wiped off upon redirect via Apache

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#7621]
Hi,

I was trying to help here: http://stackoverflow.com/questions/31801557/cakephp3-redirects-back-to-login-page-immediately-after-successfully-logging-in

I was able to replicate it and upon doing `composer update` on my Cake3 apps - even I started facing this issue.

Upon login it takes you back to the login page. However, when I tried via `php -S localhost:8888` it seemed to work but with EOF notice upon ever request after the sign in.

I am yet to figure if something is up with dispatcher. Just reporting.

**Comment by markstory** [comment]
How can someone reproduce this issue. I run apache on a number of machines and haven't had this issue. Given that the issue doesn't happen with the built in php server, I suspect something is up with the webserver configuration.

**Comment by jigardhaduk** [comment]
Same issue but Cakephp 3.0x - did composer update.
I am running apache 2.4.7 on Ubuntu.
It is working on fine with php built in server but when opened with Apache it looses session when redirected to another controller.
Also tried manually entering the URL. Still redirects to login page without login errors.

**Comment by jigardhaduk** [comment]
@karmicdice EOF issue that you are seeing is due to incomplete / incorrect HTML tags

Example : `<script /> vs <script></script>`

EOF has nothing to do with session getting reset, I think. Maybe something else.

**Comment by ADmad** [comment]
@karmicdice @jigardhaduk Are you guys using mod_php or fastcgi ?

**Comment by jigardhaduk** [comment]
`echo php_sapi_name();` returned `apache2handler`.

mod_php

**Comment by ADmad** [comment]
I am using linux mint 17.2 based on ubuntu 14.04 LTS with up to packages. I don't have any problem with sessions using latest cake 3.1.2 with apache and mod_php. I don't remember doing any custom settings.

It shouldn't matter but just for info if am using PHP's default session name instead of Cake's  `'CAKEPHP'`.

**Comment by jigardhaduk** [comment]
I tried checking under Resources tab of Chrome's inspect element.

It listed CAKEPHP session when using php's built-in server but for apache it does not list.

I will create create-project based on Cake 3.1.2 and let me see if changing files worked. I am using Cake 3.0x not sure if composer updated to 3.1.2.
I will also change session to database and see if it works - A/B?

Will update here.

**Comment by jigardhaduk** [comment]
Hi, it worked.
We might have compatibility issues when doing composer update from 3.0 to 3.1.
Performing a fresh composer create-project for cake 3.1.2 stable did the trick.

**Comment by ADmad** [comment]
In 3.1 storage class was added for AuthComponent. Maybe that's causing problems for you. But the change is meant to be backwards compatible and things should still work unless you have overridden defaults of AuthComponent.

**Comment by karmicdice** [comment]
Thanks @jigardhaduk I tried as you did and fresh installation upgrade worked.

@ADmad I have followed as-is from Cake doc:

```php
public function initialize()
{
    parent::initialize();
    $this->loadComponent('Auth', [
        'loginAction' => [
            'controller' => 'Users',
            'action' => 'login',
            'plugin' => 'Users'
        ],
        'authError' => 'Did you really think you are allowed to see that?',
        'authenticate' => [
            'Form' => [
                'fields' => ['username' => 'email']
            ]
        ],
        'storage' => 'Session'
    ]);
}
```

Even my colleague had the same issue, he did composer update today but performing a fresh upgrade helped.

Guess we need a patch for the community?

**Comment by ADmad** [comment]
You guys need to put your heads together and provide a way to reproduce the issue :) Only then it can be fixed. 

I would be really surprised if it's auth config issue since problem doesn't occur when using php's inbuilt server.

**Comment by karmicdice** [comment]
**To reproduce:**

1. Create project version 3.0 minimum stability dev
2. Do the code work.
3. Two way to do this:
    * Perform composer update I reckon it will change the branch
    * Manually change composer.json and change version to 3.1 and minimum stability to stable. Perform composer update.

Auth stops working via Apache but works great with php's built-in server.

Yep : Equally shocked like this guy...

![Image of shocked cat]
(http://i.imgur.com/p4q5mLU.jpg)

**Comment by markstory** [comment]
@karmicdice With the same AuthComponent configuration?

**Comment by karmicdice** [comment]
Yes. With the same AuthComponent configuration.
