### ISSUE TITLE
Marshaller doesn't use fieldList for validation

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/cakephp#7625]
When passing a `fieldList` to one of the marshal methods, the used fields are only used for setting the properties. If you use a field list with and there's a `requirePresence` for a property that's not on list, it would still return an error for that property.

I would expect it to ignore the fields that are not `fieldList`. Any thoughts on this?

**Comment by lorenzo** [comment]
I think I would prefer to keep it simple and let the validator decide whether the field is important or not, based on the last argument of `requirePresence`

**Comment by markstory** [comment]
I'm with @lorenzo `fieldList` should only control which fields are marshalled. You can use alternate validator objects if you need different rules in different places.

**Comment by jhli** [comment]
A graphical representation of how cake3 works in regards to marshalling validation and rules, similar to request-respnse-cycle, would help at pointing where (how) sonething should be done.

**Comment by markstory** [comment]
@jhli That's good feedback, I can add a diagrams for the marshalling / save process.

**Comment by jhli** [comment]
If you send me a non grapical document of the purposal I can do the svg/png for you.

**Comment by markstory** [comment]
I still plan on getting to this. New bug reports have been keeping me busy though.

**Comment by markstory** [comment]
Does something like this help, or were you thinking of something different?

![validation-diagram-1](https://cloud.githubusercontent.com/assets/24086/11231954/7c825d18-8d7b-11e5-8093-3ad38933c3d9.png)

**Comment by lorenzo** [comment]
Looks good to me :)

**Comment by jhli** [comment]
So what part or process is the marshaller? (In-memory to storage ready data structure?) - only the 'persisted data' box?

**Comment by lorenzo** [comment]
@jhli `newEntity()`

**Comment by ionas** [comment]
A) I assume the process is (within this diagram) the same.
Above the line:
"Marshalling"
Below the line
"newEntity()
patchEntity()"

A1) Does save() actually do something like newEntity/patchEntity do, e.g. any data transformation.

A2) What is a Table Object? Is it an Table Entity Object (it is not a Table Class object, is it) ?

B) For Validator the same (one side a description like "Applying validation rules") and on the other some Class or method names?

C) At the bottom it should be Business rules or business logic or data constraints or something - application logic is a bit generic term for what Rules do?

D) Persisted Entity should also have a note that it is actually saved to the storage layer?

**Comment by GuidoHendriks** [comment]
Although the diagram looks good, it doesn't explain what this issue was about. You don't see where `fieldList` is used, so it wouldn't take away that confusion.

**Comment by markstory** [comment]
@jhli I didn't include the marshaller explicitly originally, as its not part of the public interface most people interact with. I'll try updating the diagram given your feedback.

@GuidoHendriks You're correct, I was planning on making that a textual change.

**Comment by ionas** [comment]
Just noticed it is called "application rules" in the docs at multiple places (http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-entities as well) so even if the term is not perfect that's the current one.

Then there is a list of steps http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-entities ... that should either be a graphic or be included in the top chart... e.g. all the default hooks.

**Comment by markstory** [comment]
@ionas I can include the event hooks as well in the next revision of the diagram.

**Comment by markstory** [comment]
Is this diagram for validation clearer than the last one?
![validation-diagram-2](https://cloud.githubusercontent.com/assets/24086/11277902/8c255c8e-8eb6-11e5-9612-07ffa6e9b0de.png)

**Comment by ionas** [comment]
I don't understand when @lorenzo says newEntity is the marshaller, but the hook "beforeMarshal" is later in the flow chart?

**Comment by markstory** [comment]
@ionas This diagram would be what happens inside newEntity() at a high-level.  The `newEntity()` method is on the table objects, but the implementation is in the marshaller. Is that level of detail important for this diagram?

**Comment by ionas** [comment]
Not sure, I'd make clear that newEntity() is the whole thing after the first arrow, not just the first arrow. As I said I'd like to see a diagram like request/response to understand the internal flow (for referencing on IRC, for myself, etc). If you think this chart fulfills that purpose (or have something other/better) in mind, then we (you - thanks!) are done.

**Comment by markstory** [comment]
@ionas Well these diagrams are not for me. If you don't think its clear, I'd like to fix that.

**Comment by ionas** [comment]
Well the Marshall prepares the horses. E.g. transforms in memory data to store-able data if I got that one right.

As far as the new diagram looks like (opposed to how I understood @lorenzo) by just looking at the diagram http://api.cakephp.org/3.0/class-Cake.ORM.Marshaller.html methods must be invoked directly after beforeMarshal (and maybe there should be some "thing" representing that process).

As the whole thing happens as part of newEntity I'd use a big box around everything and maybe put a legend at the top border of the box naming it ArticlesTable::newEntity(). And then put the requestData at a border (the method interface) and the rest inside.

But thats just me, maybe I am still off. I am also on IRC atm.

**Comment by lorenzo** [comment]
I'll close this ticket. You can reopen a ticket in the docs repo about the diagram if you like. I know that @bravo-kernel was doing a similar diagram too, maybe he is able to help.

**Comment by markstory** [comment]
I forgot about this and didn't finish the diagram off. @lorenzo I'll reopen this and finish the diagram off in the next few days.

**Comment by markstory** [comment]
Another attempt at making the boundaries of newEntity() clearer.
![validation-cycle](https://cloud.githubusercontent.com/assets/24086/11675449/ec2cb7da-9df7-11e5-87be-a3f4a14531bf.png)

And one of the save cycle:

![save-cycle](https://cloud.githubusercontent.com/assets/24086/11675742/458af20e-9dfa-11e5-864b-5d05d1012649.png)

**Comment by jeremyharris** [comment]
Those look great to me! Makes those cycles super clear.

**Comment by jhli** [comment]
Great stuff!

- Should it say 'Article Entity Object' at ghe bottom of the top chart AND the top of the bottom chart?
- Could it say 'Persisted Article Entity Object' at the bottom of the second chart?
- As an introduction, before the graph is embedded in the book, it could it say something along: *"Example of an Article (possibly including some Tags @ save Children) in request data becoming a validated Entity and then, after checking Buissness Rules, being saved (persisted) to the Database, possibly alingside its Tags."*? 

Thanks again - this is and will be an awesome helper and guide! It could also be linked to from the 2.x => 3.x migration docs.

**Comment by lorenzo** [comment]
@markstory good stuff!

**Comment by markstory** [comment]
Pull request up for the docs now.

**Comment by andruhapx** [comment]
I can not understand: what is the reason to validate field if it is not added in field list?
