### ISSUE TITLE
PDO exeception and json view

### ISSUE THREAD

**Issue by kevinliteon** [cakephp/cakephp#7628]
If I do a save with a request Ajax/JSON and PDO throws an exception, I have this error : 

```
Fatal Error (256): [Exception] Failed calling App\Model\Entity\Tag::jsonSerialize()
#0 /var/www/app/vendor/cakephp/cakephp/src/View/JsonView.php(0): json_encode()
#1 /var/www/app/vendor/cakephp/cakephp/src/View/SerializedView.php(87): Cake\View\JsonView->_serialize(Array)
#2 /var/www/app/vendor/cakephp/cakephp/src/View/JsonView.php(110): Cake\View\SerializedView->render('error500', 'error')
#3 /var/www/app/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(340): Cake\View\JsonView->render('error500', 'error')
#4 /var/www/app/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(319): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#5 /var/www/app/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(180): Cake\Error\ExceptionRenderer->_outputMessage('pdo_error')
#6 /var/www/app/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(144): Cake\Error\ExceptionRenderer->render()
#7 /var/www/app/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(155): Cake\Error\ErrorHandler->_displayException(Object(PDOException))
#8 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(PDOException))
#9 {main} in [/var/www/app/vendor/cakephp/cakephp/src/Error/ErrorHandler.php, line 156]
```

I've forgotten something?

cakephp 3.1.3

**Comment by lorenzo** [comment]
That means that an exception was generated during the json encoding of your entity.

**Comment by kevinliteon** [comment]
Have you any idea why an exception is thrown? my Entity and my Controller were gendered with bake. 
if it can help you, I have a unique constraint on two fields in my table and I use PostgreSQL with uuid.

**Comment by lorenzo** [comment]
Nope, I suggest catching the exception and debugging it to see what the problem could be

**Comment by lorenzo** [comment]
Closing as there was no more activity on this.

**Comment by vmiloshev** [comment]
I had the same issue, check if some of the columns a sql command or reserved word

**Comment by rohan-mishra-sf** [comment]
I am also having this issue. Attempting the save method on my REST API, the entity returned has no errors. When proceeding to save, it throws this error. Nothing gets captured in a try catch block either

**Comment by rohan-mishra-sf** [comment]
Well, while debugging i observed that one of the request parameters in my JSON object had a key  named "long", when i change the key name to anything else, the save method works like a charm.

**Comment by jacintoo** [comment]
I have the same issue when i have the key "start_time", when i changed it to something else it worked.

**Comment by iamdavidheartmercado** [comment]
Having the same issue here, the error occurred because I'm having duplicate keys in MySQL
