### ISSUE TITLE
Respecting the dashed action name while authorizing

### ISSUE THREAD

**Issue by gauravmak** [cakephp/cakephp#7629]
I am using *ControllerAuthorize* to allow access to only specific actions in my application.
One of the actions is - *bulkAdd()*
Authorization works well with **bulkAdd** but not with **bulk-add**
Though, I am not sure whether it should support the dashed url format or not.

**Comment by ADmad** [comment]
You are supposed to authorize your action method names your the inflected url string. Plus you can't have method names with dash in PHP.
