### ISSUE TITLE
Cakephp 3 Transaction management on multiple model operation

### ISSUE THREAD

**Issue by karimcse** [cakephp/cakephp#7630]
I have a code block where multiple table database operation are done. I need to keep this code block in transaction. I am trying in following way in cakephp 3.

    $saveStatus = 1;
    $conn = ConnectionManager::get('default');
    $conn->begin();
    $tableArticles = TableRegistry::get('Articles');
    $tableUsers = TableRegistry::get('Users');
    $articlesEntity = $tableArticles->newEntities($categoriesArray);
    foreach ($articlesEntity as $entity) {          
        if(!$tableArticles->save($entity))
        {
            $saveStatus = 0;
        }
    }
    $usersEntity = $tableUsers->newEntities($usersArray);
    foreach ($usersEntity as $entity) {
        if(!$tableUsers->save($entity))
        {
            $saveStatus = 0;
        }
    }
    if($saveStatus ==1)
    {
        $conn->commit();

    }
    else
    {
        $conn->rollback();         

    }

But the transaction works for only one table.I want multiple table operation should be in transaction.

In cake 2, we do transaction using begin() and commit() on each model data source like following.

   $mealOptionDataSource = $this->MealOptionFood->getDataSource ();
    $foodExtrasDataSource = $this->FoodExtras->getDataSource ();
    $complexOptionDataSource = $this->ComplexOptionFood->getDataSource ();

    $mealOptionDataSource->begin ();
    $foodExtrasDataSource->begin ();
    --- Code here---
    $mealOptionDataSource->commit ();
    $foodExtrasDataSource->commit ();
    $complexOptionDataSource->commit ();

I can't find a way how to do it in cake 3.

**Comment by lorenzo** [comment]
Use the transactional function in the connection object.

```php
$table->connection()->transactional(function () {
});
```

And please, don't use the issue tracker for help requests :)

**Comment by oanhnn** [comment]
I have a same problem with transaction:

```
<?php
// In controller
        $mailLog = \Cake\ORM\TableRegistry::get('MailLog');

        $mails = $mailLog->newEntities([
            [
                'sender_id'      => 6,
                'receiver_id' => 1,
                'body'    => 'test transaction 111111',
                'created_at'   => '2016-01-20 12:00:00',
                'delete_flag'  => 0,
            ],
            [
                'sender_id'      => 6,
                'receiver_id' => 1,
                'body'    => 'test transaction 111111',
                'created_at'   => '2016-01-20 12:00:00',
                'delete_flag'  => 0,
            ]
        ]);
        

        $mailLog->connection()->transactional(function ($conn) use ($mailLog, $mails) {
            foreach ($mails as $mail) {
                $mailLog->save($mail, ['atomic' => false]);
            }

            return false;
        });
```

But two new mail records still inserted in DB.
Can you help me?

My project run with:
CakePHP 3.1.5 (bfc9cfbb8508e1014e183f35aff082fd584c00d7)
MariaDB 10.0.21
Table engine: MyISAM

**Comment by ADmad** [comment]
@oanhnn MyISAM doesn't support transactions, you need to use InnoDB

**Comment by oanhnn** [comment]
Thank you for reply!
