### ISSUE TITLE
Documentation of callbacks wrong

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7631]
I suspect the documentation of the callbacks in Controller (and maybe other places) to be incorrect:

    @return void

for

    public function beforeFilter(Event $event)
    public function beforeRender(Event $event)
    public function beforeRedirect(Event $event, $url, Response $response)

etc should probably be

    @return \Cake\Network\Response|null

as it can return a redirect response object and then redirect away early, right?

    return $this->redirect(...);

Currently, if you try to use redirects in those callbacks, the IDE would tell you that this is not allowed as returning void may not return anything. We should probably fix this for all callbacks of that type.

**Comment by markstory** [comment]
The proposed return type looks good to me.
