### ISSUE TITLE
[3.1] Automatic datatime schema type for 'created' / 'modified' fields on SQLite

### ISSUE THREAD

**Issue by quantum-x** [cakephp/cakephp#7635]
Current Behavior:
 - Cake 3.X determines its schema from the ORM schema
 - 'created' and 'modified' fields with 'DATETIME' type in MySQL are automatically instantiated as Time fields in Cake

Problem:
 - Some DB Engines, specifically SQLite do not have DATETIME types.
 - In this instance, created / modified fields are not automatically set to Time fields, they have to be manually specified, ie:
```php
    protected function _initializeSchema(Schema $schema)
    {
        $schema->columnType('created', 'datetime');
        $schema->columnType('modified', 'datetime');
        return $schema;
    }
```

Proposed behavior:
 - For SQLite databases, 'created' and 'modified' fields are automagically instantiated as Time fields.

If accepted as an issue, I will try to provide a PR + Tests

**Comment by lorenzo** [comment]
What is the schema of your SQLite table?

**Comment by quantum-x** [comment]
Digging into the source, it seems that in: 
https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/SqliteSchema.php

The `_convertColumn` function refers to column types that do not exist in SQLite ( https://www.sqlite.org/datatype3.html )

**Comment by quantum-x** [comment]
@lorenzo SQLite schema is as follows:
```sql
CREATE TABLE "users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`auth_hash`	TEXT NOT NULL,
	`timezone`	TEXT,
	`last_login`	TEXT,
	`created`	TEXT NOT NULL,
	`modified`	TEXT
)```
As SQLite3 does not provide any DATETIME column times ( https://www.sqlite.org/datatype3.html#datetime )

**Comment by quantum-x** [comment]
@lorenzo - Not a bug.
If anyone else happens across this issue, SQLite allows arbitrary column types via 'Affinity', which wil translate to one of the base column types.

Which is to say:
```
CREATE TABLE "users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`auth_hash`	TEXT NOT NULL,
	`timezone`	TEXT,
	`last_login`	DATETIME,
	`created`	DATETIME NOT NULL,
	`modified`	DATETIME
)
```
is perfectly valid in SQLite
