### ISSUE TITLE
[2.7.5] Console Fail on bake

### ISSUE THREAD

**Issue by nilsonpena** [cakephp/cakephp#7638]
There is something wrong with cakephp 2.7.5. when using the console, for example:
cakephp/lib/Cake/Console/cake AclExtras.AclExtras aco_sync

I get the following error:

PHP Parse error:  syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in /home/myDomain/public_html/cakephp/lib/Cake/Core/App.php on line 221

If I switch to version 2.6.11 everything works well!!!

**Comment by dereuromark** [comment]
Note the `"php": ">=5.3.0"` for 2.7+
Just use the appropriate version for your machine (and you shouldn’t be using anything below PHP5.4 these days). You are probably not using composer (which you also should), that would have shown you the issue sooner.

**Comment by markstory** [comment]
Sounds like an incorrect PHP version to me.

**Comment by nilsonpena** [comment]
I am using PHP 5.4.28!!!!

**Comment by dereuromark** [comment]
Are you 100% positive? The error message above can only happen with PHP5.2 and below. There is no other explanation for it afaik.

**Comment by nilsonpena** [comment]
It's a shared host. phpinfo() tells me it is on version 5.4.28, but the cake script uses PHP CLI that possibly is using another version (5.2?) from the "master" server :( 
Thank you
