### ISSUE TITLE
Weird issue formatting a date

### ISSUE THREAD

**Issue by ArakTaiRoth** [cakephp/cakephp#7640]
So I'm having a really weird issue, perhaps I'm just missing something really stupid, I'm not sure, I've stared at this for so long I'm going cross-eyed. Anyways, here it is.  I have the following 3 lines of code:

```php
debug($historical_data[0]->date);
debug($historical_data[0]->date->i18nFormat('YYYY-MM-dd'));
die();
```

There is code before these lines and after, but I don't believe any of it is important, there is no other code between these 3 lines anywhere.

That first debug statement outputs:

```php
object(Cake\I18n\Time) {
	'time' => '2015-01-02T00:00:00+0000',
	'timezone' => 'UTC',
	'fixedNowTime' => false
}
```

The second debug statement outputs:

```php
'2014-01-02'
```

These aren't the same dates. If I change the array value it's accessing to 1 from 0, I get the same dates (2015-01-05) in both debug lines, but not for this item. I can do anything I want to the date before formatting it, add a day, add a year, add 3 years, etc.... But once formatted, it's always returning exactly one year before the actual date.

**Comment by antograssiot** [comment]
@ArakTaiRoth this is expected as you are using ``YYYY``. You probably wan't to use ``yyyy``.
ref: http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details

**Comment by ArakTaiRoth** [comment]
Thanks, that worked, what I find as odd though is I've been using YYYY throughout my entire application for the better part of a year and haven't seen this issue come up until now, and it only happened on one date within an array of about 300 dates.

**Comment by antograssiot** [comment]
@ArakTaiRoth yeah but the second of january is in the first/last week of a year so as ``YYYY`` `refers to Year (in "Week of Year" based calendars, I think it make sense

**Comment by ArakTaiRoth** [comment]
@antograssiot Ah, fair enough, thanks very much for the explanation and the help.
