### ISSUE TITLE
Entity::toArray() only converts Entity objects to array, not other objects

### ISSUE THREAD

**Issue by waltervos** [cakephp/cakephp#7643]
I ran into this issue as I was trying to convert a query result to a collection (`new Collection($result->toArray())`) and then trying to `Collection::extract()`. When I follow that with a `Collection::toList()` or `Collection::toArray()` call, I get the following error:

> Cannot use object of type Cake\I18n\Time as array in (..)/vendor/cakephp/cakephp/src/Collection/ExtractTrait.php on line 84

As far as I can see, this is because of `Cake\I18n\Time` objects present in the collection. These don't get converted to an array in `Entity::toArray()`.

I hope this is just my failure to grasp the workings of collections fully ;), but otherwise I think we should make sure that other objects get converted to array values as well.

**Comment by lorenzo** [comment]
Yes, this is is the expected behavior, specially since there is a vast amount of objects that cannot be converted to arrays in a sane way. What where you trying to do?

**Comment by waltervos** [comment]
I was trying to use extract from a result set. From some associated tables, actually. Something like:

    $result = $this->Model->find()->where()->contain(['OtherModel.OtherOtherModel'])->first();
    $collection = new Collection($result->toArray());
    $extracted = $collection->extract('other_model.{*}.other_other_model.{*}.field');

There are timestamp fields in all of these tables, and those seem to be causing the problem.

**Comment by lorenzo** [comment]
Could you use a real example and the data you used? I'm failing to see the problem here.

**Comment by waltervos** [comment]
This is my actual code:

    $user = $this->Users->find()->where()->contain(['PinterestAccounts.PinterestBoards'])->first();
    $user_collection = new Collection($user->toArray());
    $hashtags = $user_collection->extract('pinterest_accounts.{*}.pinterest_boards.{*}.hashtag');
    debug($hashtags->toList());

Here is the SQL: http://5.101.97.14/tag2pin.sql

**Comment by mylux** [comment]
I have not tried to reproduce this issue, but thinking in a situation in which:

<code>
$hashtags = $user_collection->extract('pinterest_accounts.{*}.pinterest_boards.{*}.hashtag');
</code>

Will return a Collection of datetime objects, then toList method must not convert Time objects into array, but generate an array of Time objects, no?

**Comment by waltervos** [comment]
@mylux I'm not entirely sure what Time object have to do with it, since there is no time object in the hashtag field. But even when I tried something simpler, like extract('username'), I get the same error.

**Comment by lorenzo** [comment]
@waltervos I think the problem is that you are passing the collection an array that is actually a dictionary, not an iterable array. Can you try this?

    $user_collection = new Collection([$user->toArray()]);

**Comment by mylux** [comment]
Good point, @lorenzo !

**Comment by waltervos** [comment]
Huh, that does it, thanks!

**Comment by lorenzo** [comment]
@waltervos alternatively you can do this:

$hashtags = collection($user-> pinterest_accounts)->extract('pinterest_boards.{*}.hashtag');
