### ISSUE TITLE
3.1 - Helper initialize method

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#7645]
I'm sorry if there has already been an issue about this. I searched but wasn't able to find it.

I almost feel guilty about putting this in but I have been pampered by the rest of the framework API. Is there a reason that helpers do not use the `initialize()` method that the rest do? It has become so handy to have that so I don't have to add additional `use` cases.

I'd be happy to put a PR in since it is only a few lines of code but I just wanted to check if there was a reason this was left out before I did it.

**Comment by markstory** [comment]
No actual reason it was omitted other than 'we forgot'. :smile:. Closing as there is a pull request open now.
