### ISSUE TITLE
Allow location of tmp directory to be specified in app_local

### ISSUE THREAD

**Issue by birdy247** [cakephp/cakephp#7651]
It would be great to allow the location of the tmp directory to be specified in app_local

**Problem:** As a cakebox user, when running debug kit, this can result in very slow response times due to the fact that the app dir is located on shared storage that's mounted inside the cakebox from my host system (how cakebox is provisioned).

By moving the tmp dir to that of cakebox itself, it should reduce the latency to rebuild the cached files on the shared storage.

The tmp dir can very well change from system to system, so its a local dependency and should be able to be changed from the app(_local) config, not the paths.php (only)

**Comment by hmic** [comment]
:+1:

As there is a paths key in the App config already, it would be nice to be able to use this to change or even setup the paths altobether from a single/central place.

This would make it possible to cater for local path differences from the App_local.php file and not need to change a second file for local dependencies - i thought of the paths.php file to only hold path information beeing applicable to the concrete cake installation after all.

Maybe skip the whole paths.php file and move them all over the App.php?

**Comment by markstory** [comment]
Couldn't this be done in applications that need it? I don't really know what would need to be changed in CakePHP, it sounds like you could move TMP out of paths.php.

I worry about moving one constant out, as it begs the question, why not move more/all of them?

**Comment by lorenzo** [comment]
Closing in the hope we'll get some more feedback :D
