### ISSUE TITLE
json with templates do not work anymore

### ISSUE THREAD

**Issue by MuhKuh7** [cakephp/cakephp#7653]
When I upgraded from cakePHP 3.0 to 3.1.3 the json templates stopped working.

In the controller:
  $this->set('article', $article);
  //$this->set('_serialize', ['article']);

In 3.1.3 it made no difference if the _serialize line was there or not, in both cases the variable was serialized and the ctp template file was completely ignored.

Now I updated to 3.1.4 and having _serialize set still serializes the object without the template, which is correct. But without _serialize set, the return is just "null". It does not matter what is in the template file, without the _serialize set it always shows "null".

What is going on here?

**Comment by markstory** [comment]
To have views rendered, you must not define the `_serialize` key at all. There is [an existing test](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/View/JsonViewTest.php#L299-L324) that covers templates being rendered.

**Comment by MuhKuh7** [comment]
As I wrote, I did NOT define _serialize.
Result in 3.1.3: It renders the json but ignores the template
Result in 3.1.4: It renders "null"

**Comment by markstory** [comment]
Oddly the tests are still passing in both versions. I can take a look though.

**Comment by markstory** [comment]
I wasn't able to reproduce your issue. In `config/routes.php` I put the following
```php
Router::scope('/', function ($routes) {
    $routes->extensions(['json']); 
    $routes->fallbacks('DashedRoute');
});
```
I made a controller `app/Controller/BookmarksController.php`. In that file, I put the following:
```php
namespace App\Controller;

use App\Controller\AppController;

class BookmarksController extends AppController
{
    public $components = ['RequestHandler'];

    public function chunked()
    {
        $data = ['test' => str_repeat('a', 11)];
        $this->set(compact('data'));
    }
}
```
I then created `src/Template/Bookmarks/json/chunked.ctp`, and put the following in it:

```php
<?= json_encode(['something' => 'else']) ?>
```

Going to `http://localhost/bookmarks/chunked.json` returned `{"something":"else"}` as expected.

**Comment by MuhKuh7** [comment]
ok, there IS something wrong with the 3.1.4!

This is what I get after a clean install from the zip file:
Error: Class 'Cake\Mailer\Email' not found 
File /var/www/virtual/patchworkstatt.ch/api/htdocs/api/config/bootstrap.php 
Line: 138

With 3.1.3 there is no such error. So going to try the json again with the 3.1.3

**Comment by MuhKuh7** [comment]
So I did a clean install of 3.1.3 now and used your code above.
Result:
{
    "data": {
        "test": "aaaaaaaaaaa"
    }
}

**Comment by MuhKuh7** [comment]
Back to version 3.0.13, everything works.

**Comment by dereuromark** [comment]
The only view-related change in 3.1.4 to 3.1.3 seems to be 
https://github.com/cakephp/cakephp/compare/3.1.3...master#diff-cfb68b778e2105931c37743c65812a51L1037
Where it returns early if a file is found.
Maybe that relates to it?
But you would need to give more details on how your code looks like in order for anyone else to reproduce it.

**Comment by MuhKuh7** [comment]
I think we have 2 issues here. One is that the 3.1.4 shows an error after a clean install. Just extract the zip file and go to the index page. This did not happen with 3.1.3

The second one with the templates is easy to reproduce.
1. Do a clean install of 3.1.3 (extract the zip)
2. Add this to the `routes.php` as a first line of the existing scope function
`    $routes->extensions(['json']); `
3. Create `BookmarksController.php` exactly as in your post (I added the opening php tag though)
4. Create `chunked.ctp` exactly as in your post
5. Go to the URL mentioned in your post

**Comment by dereuromark** [comment]
You shoudn't extract it as zip, but use the recommended composer install process.
This way your composer file would not be outdated/wrong and then the first error would not show up.
If you really do want to use the zip file, you need to manually assert that your file map is up to date.

**Comment by MuhKuh7** [comment]
Ok, using composer at least the initial error and the "null" problem is gone. The template however is still ignored doing steps 2-5 from above after installing via composer.

**Comment by lorenzo** [comment]
Maybe the zip package is broken?

**Comment by markstory** [comment]
Which ZIP file are you using @MuhKuh7 ?

**Comment by MuhKuh7** [comment]
This one: https://github.com/cakephp/cakephp/releases/download/3.1.4/cakephp-3-1-4.zip

But as I said, by using the Composer install method at least the error is gone. The ignored template file however remains. Only if I go back to 3.0.13 it works.

**Comment by markstory** [comment]
Ok, I can work on getting future zip files working. However, as I mentioned earlier, the JSON templates are working for me.

**Comment by MuhKuh7** [comment]
So when installing 3.1.4 with Composer:

    php composer.phar create-project --prefer-dist cakephp/app [app_name]

 * I get a version where the templates do not work

When I download the 3.0.13 ZIP file, extract it and then update with composer like this:

    php composer.phar update

* I end up with a version that says it is 3.1.4 (in `vendor/cakephp/cakephp/VERSION.txt`) even though the `composer.jar` clearly says `~3.0`
* Many files however are different to the 3.1.4 version installed directly
* And what a surprise, the templates still work after the upgrade

So, what is happening here?
* Why is Composer updating to the 3.1.x versions when `~3.0` is set?
* Why is this update different to a clean install?

**Comment by markstory** [comment]
I took another look, and created a new project using composer. When I did this, I was able to reproduce the issue. By default the updated app skeleton *adds* `_serialized`. This behavior is [injected by the AppController](https://github.com/cakephp/app/blob/master/src/Controller/AppController.php#L48-L61). This behavior was introduced in #244 to solve cakephp/cakephp#6500.

**Comment by MuhKuh7** [comment]
Yes, removing that clearly helps, thx :) This should go into the documentation!

**Comment by markstory** [comment]
@MuhKuh7 I'll make note of it.
