### ISSUE TITLE
ORM confused about datetime column types

### ISSUE THREAD

**Issue by darxmac** [cakephp/cakephp#7655]
I just had a very strange thing happen after the last update. Things started failing with 

```
[PDOException] SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '11/7/15, 4:22 PM' for column 'created' at row 1
```

errors, until i cleared the orm cache. Is this expected and should i just clear the orm_cache after each update, or is there something else going on ?

I couldn't reproduce this on my local dev vagrant box, but it was the same problem on two production machines.

**Comment by lorenzo** [comment]
How did you update the schema that you were expecting the cache to be cleared automatically?

**Comment by darxmac** [comment]
I didn't update the schema, i just updated to 3.1.4 via composer.

**Comment by lorenzo** [comment]
I'll close this as I did a couple things to reproduce this problem with no success. If you have an idea of what could have gone wrong.

In general, it is a very good ida to clear the cache after any changes in the code. I usually do that as a part of my deployment scripts.
