### ISSUE TITLE
http client "Transfer-Encoding:  chunked" not supported

### ISSUE THREAD

**Issue by blieb** [cakephp/cakephp#7657]
Hi,

I'm currently trying to use some external api. This gives me the content in chunks. But looks like the cakephp http client does not support this. (more info at: https://en.wikipedia.org/wiki/Chunked_transfer_encoding)

I have the full content, but it has some numbers every xx lines (after every chunk) in my content so I can't read the xml.

I this an known issue/todo?

response example:
00006000
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;Stations&gt;
	&lt;Station&gt;
		&lt;Code&gt;HT&lt;/Code&gt;

**Comment by blieb** [comment]
found a workaround for this issue, I added an header for accepting gzip:

'headers' => ['Accept-Encoding' => 'gzip']

why is this not enabled by default? maybe an other item to think about. Response class supports gzip.

**Comment by markstory** [comment]
What version of CakePHP are you using? How are you doing your request?

**Comment by blieb** [comment]
I'm using cakephp 3.1.4. Using it for a webservice:
https://github.com/Qarox/cakephp-nsapi/blob/master/src/Webservice/Driver/NsApi.php
https://github.com/Qarox/cakephp-nsapi/blob/master/src/Webservice/StationsWebservice.php

Here is a small example what I'm doing. Without the 'Accept-Encoding' header the server sends the response in chunks.

$client = new Client([
            'host' => 'webservices.ns.nl',
            'scheme' => 'https',
            'auth' => [
	            'username' => $this->config('username'),
	            'password' => $this->config('password') 
            ],
            'headers' => ['Accept-Encoding' => 'gzip']
        ]);

$client->get('/ns-api-stations-v2');
pr($response->body);

**Comment by markstory** [comment]
Ok, I can try and reproduce locally.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. My own site uses chunked encoding, and works fine with the Http\Client code. The following curl headers

````
$ curl -v http://mark-story.com
* Rebuilt URL to: http://mark-story.com/
*   Trying 173.255.203.165...
* Connected to mark-story.com (173.255.203.165) port 80 (#0)
> GET / HTTP/1.1
> Host: mark-story.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 10 Nov 2015 03:05:20 GMT
< Server: Apache/2.4.10 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
```

Show the chunked encoding, and the following script shows a page being downloaded:

```php
<?php
require 'vendor/autoload.php';
$http = new Cake\Network\Http\Client(['host' => 'mark-story.com']);
$res = $http->get('/');
print_r($res->body());
```

You might want to ensure that your webservice is not sending a chunked encoding with an HTTP 1.0 response. Given that I don't have access to the webservice you're having issues with, I can't effectively reproduce the issue, and am presently unable to replicate it.

**Comment by jbrunink** [comment]
There does seem to be an issue. I've tried your bit of code with the NS API. (CakePHP 3.1.4) Please find the raw output from the NS attached. The second attachment is the output of var_dump($res->body()). Does this help?

[outputcake.txt](https://github.com/cakephp/cakephp/files/31782/outputcake.txt)
[raw_dump.txt](https://github.com/cakephp/cakephp/files/31783/raw_dump.txt)

**Comment by markstory** [comment]
That response looks incorrect. The trailing `00000000` should be `0`. CakePHP code doesn't actually parse the chunks as we are relying on the PHP stream API to do that work for us.

**Comment by davidyell** [comment]
I can confirm that this is happening to me also. Using Cake `3.2.3` and trying to read from the Steam API. `http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/`

**Comment by markstory** [comment]
@davidyell What would we document? That the server has to not reply with invalid HTTP responses?

**Comment by davidyell** [comment]
I would document that the Cake HTTP client doesn't work with this format of return. It's the first time using the framework that I've hit an issue!

Perhaps I misunderstand, as I was pointed to this issue from irc.

**Comment by blieb** [comment]
The problem is that the server does not sent the chunked parts right, The number you are seeing is the length of a chunk. 
My solution was to use the secure connection (https) this makes the internet a little bit saver, and it does not works in chunks. :)

I your api is also available on https:
https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/ 

I think this should be fixed in php (or the server)

**Comment by markstory** [comment]
@blieb I agree, there is nothing we can do about remote servers being bad at HTTP. The chunked decoding _does work_ when the server correctly implements chunked encoding.
