### ISSUE TITLE
mail priority

### ISSUE THREAD

**Issue by lecas93** [cakephp/cakephp#7659]
how to use custom header on mail class in v3.1 ?
I tested
->addHeaders([
                           "X-Priority"=>" 1 (Highest)\n",
                           "X-MSMail-Priority"=>"High\n",
                           "Importance"=>"High\n"
                       ])

leandrofreire [9:34 PM]
->headers([
                           "X-Priority"=>" 1 (Highest)\n",
                           "X-MSMail-Priority"=>"High\n",
                           "Importance"=>"High\n"
                       ])

return Error: Call to undefined method Cake\Mailer\Email::headers()

**Comment by markstory** [comment]
Looks like the [API says you can use addHeaders](http://api.cakephp.org/3.1/class-Cake.Mailer.Email.html#_addHeaders).
