### ISSUE TITLE
Component Loading 

### ISSUE THREAD

**Issue by vttn** [cakephp/cakephp#7660]
As of Cakephp 3.1.4, it seems like when a Plugin's component shares the same name as a component in the App base, the App base component is loaded when calling the component from within the plugin.

**Comment by lorenzo** [comment]
Yes. To make sure you are loading classes from the plugin, either use the plugin notation:

```php
$this->loadComponent('MyPlugin.Thing');
```

Or use the full class name as an argument ti the loader:

```php
$this->loadComponent('Thing', ['className' => ThingComponent::class]);
```

**Comment by vttn** [comment]
Hi, 

`$this->loadComponent('MyPlugin.Thing');`

Does not load the MyPlugin component in 3.1.4, previous versions would load the component.

For my application the case is when my App has a Component named Thing, and the Plugin has a component Thing.

Instead of Loading `plugin/MyPlugin/src/Controller/Component/ThingComponent`
 `src/Controller/Component/ThingComponent` is loaded

**Comment by lorenzo** [comment]
I was not able to reproduce this problem. The things I did:

1. Baked component `Thing`
2. Baked plugin `Stuff`
3. Baked component Stuff.Thing`
4. Added the following plugin component

```php
<?php
namespace Stuff\Controller;

use Stuff\Controller\AppController;

/**
 * Test Controller
 *
 * @property \Stuff\Model\Table\TestTable $Test
 */
class TestController extends AppController
{

    public function initialize()
    {
        $this->loadComponent('Stuff.Thing');
    }

    public function index()
    {
        debug($this->Thing);
        die;
    }
}
```

The output of that controller was:

```
/plugins/Stuff/src/Controller/TestController.php (line 21)
object(Stuff\Controller\Component\ThingComponent) {

	'components' => [],
	'implementedEvents' => [],
	'_config' => []

}
```

**Comment by vttn** [comment]
Thanks for looking into this. 

At first I thought this might be something to with the component, it might be a bug when saving to the Datetime field in 3.1.4 .

For now we have reverted to 3.1.2 to avoid the Datetime bug.

Before the datetime expected 
 `[ 
				'year' => date ( 'Y' ),
				'month' => date ( 'm' ),
				'day' => date ( 'd' ),
				'hour' => date ( 'H' ),
				'minute' => date ( 'i' ),
				'second' => date ( 's' ) 
		];`
just in case someone runs into the same problem

**Comment by markstory** [comment]
What is the issue with saving a datetime?
