### ISSUE TITLE
[2.7] Set error handler to Console

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7661]
In the shell dispatcher, the `ConsoleErrorHandler` is set *after* bootstrapping is done in `Configure::bootstrap()`.

If there is an error during that process (for example in APP/Config/core.php, APP/Config/bootstrap.php, or any files included in these two), the output will be HTML, even though the environment is CLI.

Fix:
- In Configure::bootstrap(), set error handler to console if `php_sapi()` equals `cli`.

**Comment by dereuromark** [comment]
Sounds reasonable to me.

**Comment by markstory** [comment]
I can take a look.

**Comment by markstory** [comment]
Pull request up now.
