### ISSUE TITLE
[3.1] How to use subdomain dynamicly in cakephp 3.1 ?

### ISSUE THREAD

**Issue by Sh1n1x** [cakephp/cakephp#7666]
Hi all,

Thanks you so much for your best PHP framework !

I'm trying to configure subdomain with routing (i've read this post https://github.com/cakephp/cakephp/issues/7140#issuecomment-127076842 ) and it's working fine with the "admin" prefix.

But i would like have a dynamic prefix for example (i create a blog system for my users) : 
- johndoe.website.com/news/index
- gerard.website.com/news/index
[...]

how can i make that with the routing ?

Thanks you for your help and sorry for my english ^^

**Comment by chinpei215** [comment]
Perhaps, I think it would work if you change the code like the following:
```php
//        $parts = explode('.', $host, 2);
//        if (in_array($parts[0], $this->prefixes)) {
        if (preg_match('/^([-a-z0-9]+)\.(EXAMPLE\.COM)$/', $host, $matches)) {
            return [$matches[1], $matches[2]];
        } else {
            return [false, $host];
        }

```
But if it doesn't work, then please contact me directly, as this issue tracker is not a help forum.
chinpei215 [at] hotmail.com

**Comment by markstory** [comment]
Closing for the reasons @chinpei215 mentioned.
