### ISSUE TITLE
Expression empty list throws error - breaks compatiblity

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#7667]
```
$articlesWithComments = $this->Articles->find()
->select(['id'])
->where(['Articles.id IN' => $this->Articles->Comments->find()->select(['article_id'])->toArray()]);
```
everything works find if the subquery returns at least one row - but otherwise it throws an exception: "Impossible to generate condition with empty list of values for field (Articles.id)"
It's a change which was made in 3.1.4 -> it breaks my existing code...

**Comment by mdlouhy** [comment]
I think this issue only exists when using such a subquery condition in paginator component. But I am not sure...

**Comment by dereuromark** [comment]
The change responsible would be https://github.com/cakephp/cakephp/commit/e196c1d2f106263dbcba61e0d0430c0d3328265f .

**Comment by mdlouhy** [comment]
exactly!

**Comment by AD7six** [comment]
This is the side-effect of intentional changes, it's [explicitly mentioned in the release announcement](https://github.com/cakephp/cakephp/releases/tag/3.1.4).


The previous behavior was considered more ambiguous/dangerous since it could easily cause queries returning (or modifying) data in unexpected ways. There's more discussion in https://github.com/cakephp/cakephp/issues/7092

**Comment by mdlouhy** [comment]
I think that there should not be such breaking changes in a minor update. I just updated my code and a lot of exception are thrown suddenly...
Why not putting this to 3.2 branch?
At the moment, when I have an "IN (...)" where sql clause then I have to add !empty checks before. And PaginatorComponent has a problem even if you have "IN (SELECT foreign_key FROM xy)" because the PaginatorComponent executes the subquery separately and only recognize the issue if the subquery returns an empty result. I think that it is more confusing then helpful in a minor release. 

Instead of throwing an exception you could call a method of a class which can be overwritten. This class has a method which throws a exception by default but can be overwritten to return the "old" behavior "1 != 1".

**Comment by lorenzo** [comment]
Can you better explain the problem with the subquery? I feel I'm missing something here as the changes made for empty lists should have nothing to do with subqueries

**Comment by mdlouhy** [comment]
I was wrong - there is nothing wrong with subqueries -> the pagination just failed because the "IN ()" clause was empty.
If you really want to keep that change then just close this issue as "invalid"...
I'm personally not happy with it because I have to check every "IN ()" clause and only add the clause if the query result is empty.

I have to change the following:
```
$conditions = ['some_condition' => 'some value'];
$articlesWithComments = $this->Articles->find()
->select(['id'])
->where($conditions + ['Articles.id IN' => $this->Articles->Comments->find()->select(['article_id'])->toArray()])
->all();
```
to:
```
$conditions = ['some_condition' => 'some value'];
$articleIds = $this->Articles->Comments->find()->select(['article_id'])->toArray();
if (!empty($articleIds)) {
    $conditions += ['Articles.id IN' => $articleIds];
}
$articlesWithComments = $this->Articles->find()
->select(['id'])
->where($conditions)
->all();
```

**Comment by lorenzo** [comment]
Ok, that's not a subquery.... You can avoid the problem altogether by doing this:

```php
$conditions = ['some_condition' => 'some value'];
$articlesWithComments = $this->Articles->find()
->select(['id'])
->where($conditions + ['Articles.id IN' => $this->Articles->Comments->find()->select(['article_id'])])
```

**Comment by mdlouhy** [comment]
I know now but all existing queries need to be changed. And I cannot use your solution if there is a limit clause in the subquery...

**Comment by lorenzo** [comment]
I'm really sorry for the inconvenience, but unfortunately what seemed to be a great feature, and a time saving one (as it is clearly time saving for you), also resulted in one that can lead to really dangerous bugs. Despite it actually being one of my favourites things about the query builder, we had to remove the feature and I don't think there is a good way of bringing it back....

On limit clauses in the subquery. I think we can look into automatically removing it if we detect it is used in a subquery. Meanwhile, it is possible for you to just call `->limit(null)` as the last part of your subquery instruction if you think it contains a limit clause.

I offer my help for creating a script for finding the uses of `IN` in your code, hopefully, this search will also make your code more reliable and less prone to accidental errors or attacks from malicious users.

**Comment by mdlouhy** [comment]
I will "just" update my code - I don't wanna cause issues if it is not an issue in CakePHP. If you think that it helps more than it causes pain then I will take the time.
I have been using CakePHP for five years now and I really like what you do with CakePHP -> this change I just haven't understood before I created this ticket. Now I do. Thanks for your help.

**Comment by lorenzo** [comment]
Thanks for your understanding @mdlouhy, I really appreciate that. Just as a closing not on why this was necessary: It was really difficult for us to detect whether the comparison was negated or not. For example conversing empty array to `1 != 1` was great for `IN` comparisons, but a complete disaster for `NOT IN`, since it actually would find absolutely all the rows when converted to `NOT 1 != 1`.

**Comment by CHOUKI-Mouhssine** [comment]
Worked for me. (CakePHP 3.6.5)
you can use this line : 
->whereInList('Articles.id', $this->Articles->Comments->find()->select(['article_id'])->toArray(), ['allowEmpty' => true]);
