### ISSUE TITLE
[Suggestion] Adding '_named' option to Router

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#7670]
Hi,
I know that the named params was removed in cakephp3 but we can parse them **manually** using ```Router::parseNamedParams(Request $request)``` so the params that have a separator "**:**" will be moved from ```$this->request->params['pass']``` to  ```$this->request->params['named']```.

I have a suggestion:
Adding a new option **'_named'** to the ```Router::url($url = null, $full = false)``` like the options **'_base'**, **'_port'**, **'_name'** ...
eg. ```Router::(['controller' => 'Articles', 'action' => view, $id, '_named' => ['lang' => 'en', 'sort' => 'titleDesc']]);``` will be converted to **/Articles/view/1/lang:en/sort:titleDesc** and the named params will be parsed **automatically** 
```php
// Debug $this->request->params['pass']
[
   (int) 0 => 1
]
// Debug $this->request->params['named']
[
   'lang' => 'en',
   'sort'  => 'titleDesc'
]
```
I have already added the ```Router::parseNamedParams($this->request)``` in the ```AppController::beforeFilter(Event $event)```, created a new route **App\Routing\Route\MyRoute** extending from the **Cake\Routing\Route\Route**, changed the ```Route::_writeUrl($params, $pass = [], $query = [])``` method like this to parse the **'_named'** option:
```php
protected function _writeUrl($params, $pass = [], $query = [])
    {
        $pass = implode('/', array_map('rawurlencode', $pass));
        $out = $this->template;

        $search = $replace = [];
        foreach ($this->keys as $key) {
            $string = null;
            if (isset($params[$key])) {
                $string = $params[$key];
            } elseif (strpos($out, $key) != strlen($out) - strlen($key)) {
                $key .= '/';
            }
            $search[] = ':' . $key;
            $replace[] = $string;
        }

        if (strpos($this->template, '**') !== false) {
            array_push($search, '**', '%2F');
            array_push($replace, $pass, '/');
        } elseif (strpos($this->template, '*') !== false) {
            $search[] = '*';
            $replace[] = $pass;
        }
        $out = str_replace($search, $replace, $out);
        
        // parse the _named param
        if(isset($query['_named'])){
            $named = [];
            foreach($query['_named'] as $key => $value){
                $named[] = $key . ':' . $value;
            }

            $out .= '/' . implode('/', array_map('rawurlencode', $named));
            unset($query['_named']);
        }

        // add base url if applicable.
        if (isset($params['_base'])) {
            $out = $params['_base'] . $out;
            unset($params['_base']);
        }

        $out = str_replace('//', '/', $out);
        if (isset($params['_scheme']) ||
            isset($params['_host']) ||
            isset($params['_port'])
        ) {
            $host = $params['_host'];

            // append the port if it exists.
            if (isset($params['_port'])) {
                $host .= ':' . $params['_port'];
            }
            $out = "{$params['_scheme']}://{$host}{$out}";
        }
        if (!empty($params['_ext']) || !empty($query)) {
            $out = rtrim($out, '/');
        }
        if (!empty($params['_ext'])) {
            $out .= '.' . $params['_ext'];
        }
        if (!empty($query)) {
            $out .= '?' . http_build_query($query);
        }
        return $out;
    }
```

**Comment by dereuromark** [comment]
What's wrong with using query strings?
Named params have been removed for a reason: they are and always will be broken by design (invalid chars in URL).

**Comment by flashios09** [comment]
@dereuromark Thanks for your reply :)
I know that the named params have been removed but there is a **fallback** to parse them **when we want**, i have just suggested to parse them **automatically** if we have the **'_named'** option in the **Router::url**. 
I don't know about the invalid chars in URL, even the passed params can have invalid chars in URL, i think we can encode/remove them.

**Comment by ADmad** [comment]
The fallback was kept only to help migration from 2.x. No features should be added which make using named params easier.

**Comment by flashios09** [comment]
@ADmad It's just a suggestion using an **existing method** ```Router::parseNamedParams($request)```, i didn't suggest **adding new features**, we can write named params in the url as string **'lang:en'** without adding a new param **'_named'** ```['_named' => ['lang' => 'en']]``` :)

**Comment by ADmad** [comment]
Updating even an existing method to do something it doesn't right now is also a feature addition.

**Comment by markstory** [comment]
Is there a reason you want to continue generating named parameters? I only included a way to parse incoming URLs as I could see a clear need to have compatibility with existing URLs, but couldn't really see a case where generating URLs with named parameters would be helpful.

**Comment by flashios09** [comment]
@markstory it's just a suggestion, the ```parseNamedParams($request)``` already exist and we can write named params as a string eg. "**lang:en**" so i thought that we can automate the process. 
Why i continue generating the named params ?
eg. of urls :
- **/Articles/search/foo/sort:titleDESC/deleted:with**
- **/Articles/search/foo/sort:titleDESC**
- **/Articles/search/foo/deleted:with**
- **/Articles/search/foo**

in the ArticlesController i have a search action
```php
public function search($q){
  // some logic here
}
```
using the named params ```$this->request->named``` i can know if the second param is for **'deleted'** or **'sort'** or **there is no a second param**

**Comment by markstory** [comment]
Named parameters can easily be replaced with query string parameters in most applications though. I would prefer to not make it easy for people to use named parameters. They were a pretty big mistake in my opinion and something I would rather forget.

**Comment by flashios09** [comment]
@markstory Ok Sir, i respect the cakephp **"philosophy"** to not use the named params any more.
I don't like the query string(ugly) so i have already created my custom ```Route``` and a custom ```parseNamedParams``` method.
Thanks for all the explanations :)

**Comment by markstory** [comment]
The issue with named parameters was that _no other_ tool in any web stack/toolchain understands them. Unlike query parameters working with named parameters requires special consideration and handling.
