### ISSUE TITLE
[2.x] Enhancement: Backporting magic call with custom finders

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#7674]
In 2.x, we still cannot use magic call with custom finders.

```php
// OK
$users = $User->findAllByGroupId($groupId);

// NG
$users = $User->findListByGroupId($groupId);
$posts = $Post->findPublishedByUserId($userId);
```

If there is no reason that we cannot backport this feature into 2.x, I wanna do it.

**Comment by markstory** [comment]
@chinpei215 Only reason is time. If you have the time, a pull request against 2.x would be fantastic.

**Comment by chinpei215** [comment]
Pull request up now.
