### ISSUE TITLE
api documentation for FormHelper has inaccurate information

### ISSUE THREAD

**Issue by freedomfflow** [cakephp/cakephp#7678]
http://api.cakephp.org/3.1/source-class-Cake.View.Helper.FormHelper.html#_select

lines 1817 and 1818:
1816:      * $options = [
1817:      *     ['name' => 'United states', 'value' => 'USA'],
1818:      *     ['name' => 'USA', 'value' => 'USA'],
1819:      * ];

'name' is not valid, it should be 'text'.

Using 'name' causes undesired output as the select options are not created properly.

**Comment by ADmad** [comment]
@freedomfflow Would you like to make a pull request fixing the docblock for the method?

**Comment by freedomfflow** [comment]
Yes... I wasn't sure how to do that for api documentation.  Can you point
me in the right direction?  Thank you

**Comment by ADmad** [comment]
Just modify the text you pointed out in `FormHelper.php` file. Check github docs on how to fork a repo, modify required file and submit a pull request thereafter.
