### ISSUE TITLE
[question] 3.1.x How to write correct subquery for the same table?

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#7679]
I have `articles` table, and i need to get 10 last articles from this table and output 3 random rows from this.
I wrote following SQL query:
```sql
SELECT *
FROM
  (SELECT *
   FROM `articles`
   ORDER BY `created` DESC LIMIT 10) AS t
ORDER BY RAND() LIMIT 3
```
So, i want to make the same query by CakePHP ORM, i wrote following code:
```php
$lastArticles = $this->Articles->find()
    ->orderDesc('created')
    // there will appear additional conditions
    ->limit(10);

$related_articles = $this->Articles
    ->find()
    ->from(['sub' => $lastArticles])
    ->limit(3)
    ->order($query->newExpr('RAND()'))
    ->toArray();
```
But i am getting errors, because subquery making table fields as aliases, and it cannot be disabled.
I tried to make something like this in subquery:
```php
$query->select($query->newExpr('*'));
// but it generates - (*) and this making SQL syntax error
```
What is the correct way to make subquery to the same table?

**Comment by lorenzo** [comment]
You will need to select the columns from the subquery, it is not currently possible to use `*`

```php
->select(['id' => 'sub.id', 'title' => 'sub.title' ....])
```

You can save some time by using the `schema()` function:

```php
$columns = collection($table->schema()->columns())
    ->unfold(function ($column) {
        yield $column => "sub.$column"
    });

$query->select($columns->toArray());
```

**Comment by jhli** [comment]
Should there be some advanced chapter on subqueries, select(), from()? Etc?

**Comment by Daou** [comment]
I actually still don't have a solution to the following query:

`SELECT *
FROM change_logs ChangeLogs 
WHERE ChangeLogs.id = (SELECT ChangeLogs2.id AS `ChangeLogs2__id` FROM change_logs ChangeLogs2 WHERE ChangeLogs2.text_id = ChangeLogs.text_id LIMIT 1)`

I understand to change the alias via `select` but what if I need to use a different alias in `where`?

**Comment by lorenzo** [comment]
@Daou the easiest is to create another Table instance with a different alias:

```
$table2 = TableRegistry('ChangeLogs2', ['className' => ChangeLogsTable::class]);
$table->select()->where(['ChangeLogs.id' => $table2->select(..)->where(..)])
```

**Comment by Daou** [comment]
@lorenzo Thank you, works great! Even though you probably wanted to write `TableRegistry::get` ;-)
