### ISSUE TITLE
[RFC] Catch errors as early as possible

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#7683]
There are a few inconvenient things about letting the exception handler catch the exception:

* We lose reference to the current request and response objects
* Thorwing an exception inside the handler becomes a fatal error
* It is more difficult to keep a stack of handlers

For those reasons I think it would be better to catch the exceptions as early as possible in the dispatching cycle:

```php
// ... inside the dispatcher
try {
    return $this->handle($request, $response);
} catch (Exception $e) {
    return get_handler()->handleException($e);
}
```

Of course, this still means that we need to register the default exception handler in case we fail to catch new exceptions or thy happen during the bootstrap process. But I think this will give more reliability to the dispatching process.

**Comment by markstory** [comment]
Wouldn't we also have to change the contract around exception handlers to include the request/response as parameters?

I feel like this could also factor into the psr7 approach too.

**Comment by markstory** [comment]
Closing as #8722 solves this.
