### ISSUE TITLE
[RFC] Have real validation methods in Validator

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#7684]
I have seen many people struggle with how validators work in cake, and I think it is due to the fact that validation methods are actually in the `Validation` class instead of the `Validator`. I think we could have real methods in the validator for directly bridging to their implementation. For example:

```php
$validator
    ->naturalNumber('position')
    ->url('href', 'This is not a valid URL')
    ->between('salary', 1000, 2000);
```

The implementation of such rules can be done this way:

```php
public function url($field, $message, $when)
{
    return $this->add($field, ['rule' => 'url', 'message' => $message, 'on' => $when]);
}
```
I think this will make the validation rules more readable, easier to find and easier to document.

**Comment by jeremyharris** [comment]
I like this. Discoverability in IDEs will be very nice. No more looking up docs :)

**Comment by markstory** [comment]
Seems like a good idea to me. Would we add methods for all the Validation methods? Is there a way we can provide an extensible API for these validator methods.

**Comment by davidyell** [comment]
:+1: 

Will this break BC for people who implemented their own validation providers?

**Comment by lorenzo** [comment]
@davidyell no, they will work exactly the same :)

**Comment by bravo-kernel** [comment]
:+1:

**Comment by jeremyharris** [comment]
@lorenzo this can be closed :)
