### ISSUE TITLE
3.1 - [Feature] Implement a Router::load() function to load several routes files

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7687]
Hello,

I'm actually doing a "big" application with Cake3, and i noticed that my `routes.php` file has more than 1500 lines, and searching in it is a waste of time.
So, like i have doing with the configuration files (with `Configure::load()`), i have think about to split my `routes.php` into many files. For example, splitting them by prefix, because my application has 5 majors prefix :
* `/` (base)
* `forum`
* `chat`
* `admin`
* `blog`

But i saw that in the doc, there's no `build in` method to do this like `Configure` do. I know i can still split them, and doing a `include` in my `routes.php`, but it would be prettier if I could do something like this :
**config/routes.php :**
```php
use Cake\Core\Plugin;
use Cake\Routing\Router;

Router::extensions(['json', 'xml', 'pdf']);
Router::defaultRouteClass('DashedRoute');

Router::load('base');
Router::load('forum');
```

**config/routes_base.php :**
```php
Router::scope('/', function ($routes) {

    $routes->connect(
        '/',
        [
            'controller' => 'pages',
            'action' => 'home'
        ]
    );

    //etc
    $routes->fallbacks();
});
```

**config/routes_forum.php :**
```php
Router::prefix('forum', function ($routes) {

    $routes->connect(
        '/',
        [
            'controller' => 'forum',
            'action' => 'index'
        ]
    );

    //etc
    $routes->fallbacks();
});
```

* And the routes files, should be prefixed by **routes_**.
* Or, the routes files should be in the directory **config/Routes/forum.php**

That is just an example to show you the possibilities.

What do you think about this feature ? Of course it can be more improved than my example.

The actual loader : https://github.com/cakephp/cakephp/blob/master/src/Routing/Router.php#L971-L975

**Comment by ADmad** [comment]
Why can't you use a simple `include()` to load all the separate files in your `routes.php`?

**Comment by lorenzo** [comment]
As @ADmad, just `include` the files in your routes.php. I think that's elegant and easy to understand

**Comment by Xety** [comment]
@ADmad I can, but what i'm talking about is to do a system similar to the `Configure::load()`.

For example, it would be more helpful to load several files on one line, instead of 5 `include()`:
Before :
```php
include "base.php";
include "forum.php";
include "blog.php";
include "chat.php";
include "admin.php";
```

After:
```php
Router::load(['base', 'forum', 'blog', 'chat', 'admin']);
```

Here's something of what i'm trying to explain (It's for Laravel, but it work as well for Cake) : 
http://laravel-tricks.com/tricks/organize-routes-with-route-partials

I'm actually using this method, you can see the code there : https://gist.github.com/Xety/147ea6dd8ad6290e4429  but if i posted here, is to include it in the core. ^^

**Comment by ADmad** [comment]
> For example, it would be more helpful to load several files on one line, instead of 5 include()

Use an array of names with a loop or array_map and you can do it it 2 lines.

I am not in favor of fancy solutions for simple file includes.

**Comment by markstory** [comment]
What would `Router::load()` do beyond `include()`? If its just a wrapper, I'm :+1:, but if it adds more than just array syntax I could be persuaded.

**Comment by Xety** [comment]
Actually my code is just a wrapper of the `include()` function.

I can use it to include only one file :
```php
Router::load('base');
```
Or for include many files :
```php
Router::load(['base', 'forum', 'blog', 'chat', 'admin']);
```

I have extended a bit the system to use a custom routes directory `config/Routes/` for having an organized structure.

If i wanted this solution, it's because i was familiar with the `Configure::load()` and i wanted to use something similar with the route files, and when i checked the Router documentation about how to organize routes into many files (Like i have doing with Configure), i saw nothing about it.

**Comment by sdustinh** [comment]
I personally use the array map method but I would definitely be interested in conditional loading of route similar to [dispatch filters] (http://book.cakephp.org/3.0/en/development/dispatch-filters.html#conditionally-applying-filters).

**Comment by jippi** [comment]
using include / require would be faster anyway, the opcode cache would easily optimize that away

**Comment by Xety** [comment]
I will show you what i'm actually using in my application. For information, i'm using a custom `src\config\Routes` directory for having an organized structure.
**src\config\paths.php**
```php
/**
 * Path to the routes directory.
 */
define('ROUTES', CONFIG . 'Routes' . DS);
```

**src\config\routes.php**
```php
<?php

use App\Routing\Routes;
use Cake\Core\Plugin;
use Cake\Routing\Router;

Router::extensions(['json', 'xml', 'pdf']);
Router::defaultRouteClass('DashedRoute');

//The new function
Routes::load(['base', 'forum', 'chat', 'admin']);

Plugin::routes();
```

**src\config\Routes\base.php**
```php
<?php

use Cake\Routing\Router;

//Public routes.
Router::scope('/', function ($routes) {

    $routes->connect(
        '/',
        [
            'controller' => 'pages',
            'action' => 'home'
        ]
    );
}
```

**src\Routing\Routes.php**
```php
<?php
namespace App\Routing;

use App\Routing\Exception\MissingFileException;

class Routes
{
    /**
     * Load one or more routes files.
     *
     * ### Usage
     *
     * Loading one file:
     *
     * ```
     * Routes::load('base');
     * ```
     *
     * Loading many files at once:
     *
     * ```
     * Routes::load(['base', 'blog', 'admin']);
     * ```
     *
     * @param string|array $files The file(s) to load.
     *
     * @return void
     */
    public static function load($files)
    {
        if (is_string($files)) {
            static::_includeFile($files);

            return;
        }

        if (is_array($files)) {
            foreach ($files as $file) {
                static::_includeFile($file);
            }
        }
    }

    /**
     * Verify if the file exist and if yes, include it.
     *
     * @param string $file The file to verify.
     *
     * @throws \App\Routing\Exception\MissingFileException When the file doesn't exist.
     *
     * @return void
     */
    protected static function _includeFile($file)
    {
        if (empty($file)) {
            return;
        }

        $path = ROUTES . strtolower($file) . '.php';

        if (!file_exists($path)) {
            $msg = sprintf('The Route file "%s" could not be found.', $path);

            throw new MissingFileException($msg);
        }

        include $path;
    }
}
```

I have created a new class `Routes` to not overwrite the `Router` code class, i prefer.
But my plan is to add the function `load()` to the `Router` class `Router::load()`

**Comment by Xymanek** [comment]
A bit off-topic, but... Instead of `if (is_string($files))` why not cast to `(array)` the `$files` and then proceed with looping like it's done in many places in Cake?

**Comment by dereuromark** [comment]
@Xymanek Sounds like a good improvement to me :)

**Comment by Xety** [comment]
@Xymanek Nice improvement, thanks ! I will update the code in my comment.

**Comment by markstory** [comment]
Closing as there doesn't seem to be much traction on this. Until it becomes a more common scenario, using the code provided in [this comment](https://github.com/cakephp/cakephp/issues/7687#issuecomment-164103565) is a good solution.
