### ISSUE TITLE
Css not loading corectly

### ISSUE THREAD

**Issue by elarion83** [cakephp/cakephp#7688]
Hi. 

I'm trying to setup my app online and I'm facin an issue with my css loading path.

When I use Html->css(bake.css) he don't succed to find my css, he seem to look : 

      http://myappurl/css/bake.css

And when I use Html->(css(webroot/css/bake.css) he look for : 

  http://myappurl/webroot/css/bake.css

which is okay but when i'm browsing to a controller the webroot/css don't work because cake look for

 http://myappurl/mycontroller/myview/webroot/css/bake.css

So.. what can I do ? Maybe a trouble with my .Htaccess files ?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
