### ISSUE TITLE
[2.7] beforeFilter returning false

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7694]
Let's say you have a `beforeFilter` function that checks whether the user is logged in, and redirects if he isn't. This will trigger a `redirect` call with `exit = true` and finally a `_stop()`. This will stop the request and redirect properly.

Now, imagine you are testing this action in a unit test. What happens? Well, the action is executed because `_stop()` is mocked.

Not a bad idea at all, but why isn't this implemented (seeing that `beforeFilter` is indeed a CakeEvent):
- beforeFilter returns false or cancels the `startup` event
- dispatcher checks if the event is stopped, and returns / does not invoke action

Why is it that you have events for `startup()` and `initialize` in `Controller`, but you don't even check if the event is stopped?

By checking if the event is stopped, you don't even need a `_stop()` in the redirect. The dispatcher would return immediately, and the request is finalized anyways.

Also, by exiting the request in redirects, `shutdown` process events will not be triggered. We have to explicitly listen for the `beforeRedirect` event. What was the idea behind this? It makes the code very messy, indeed.

Even worse: what if the user gives the `exit` argument of `redirect` to `false`? Well, the action would then be called!

A perhaps simple and BC solution would be to return `false` in `Controller::startupProcess()` if any of the events are cancelled. `Dispatcher::_invoke()` would then check the return value, and return accordingly.

**Comment by lorenzo** [comment]
This was is so for historic reasons, since the implementation of Events came in between the 2.x releases, so we could not break the old behavior. CakePHP 3 pretty much works as you expect: returning a response object from the callback breaks the dispatching cycle and immediately returns.

**Comment by davidsteinsland** [comment]
Is there any plans to backport some of this functionality, or at least making it BC? Upgrading to next major will be so much work, for a lot of users, that choosing another framework will probably be just as equal.

**Comment by dereuromark** [comment]
@davidsteinsland I disagree. Upgrading is painful, but switching to something else is factor 10...100 of pain, at least :P
Use/Write upgrade shells to automate a lot of things, and it is doable in a reasonable timeframe.

**Comment by markstory** [comment]
@davidsteinsland We can't really backport the behavior you're describing and be backwards compatible. Previously the return value of callback methods was ignored, and changing the semantics of those methods is a compatibility break.

I completely agree that what you're describing is more logical, and is why we made 3.x work that way.

**Comment by markstory** [comment]
Closing as we can't reasonably fix this in 2.x without breaking compatibility and the suggested changes have already been implemented in 3.x
