### ISSUE TITLE
3.1.4 - [Question] Can't call $this->Flash->sucess in Controller

### ISSUE THREAD

**Issue by ykeisuke** [cakephp/cakephp#7696]
Hello,

I got Error  ` Error: Call to a member function success() on boolean ` in simple Controller method.

And I use CakePHP 3.4.1 and `bake all`. 
next I developed controller method after pushed button function.

How to fix this Error? (May be my bad :sa)

# Source Code

## View(layout/default)

```
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

$cakeDescription = 'CakePHP: the rapid development php framework';
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?= $cakeDescription ?>:
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>

    <?= $this->Html->css('base.css') ?>
    <?= $this->Html->css('cake.css') ?>

    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
</head>
<body>
    <nav class="top-bar expanded" data-topbar role="navigation">
        <ul class="title-area large-3 medium-4 columns">
            <li class="name">
                <h1><a href=""><?= $this->fetch('title') ?></a></h1>
            </li>
        </ul>
        <section class="top-bar-section">
        </section>
    </nav>
    <?= $this->Flash->render() ?>
    <section class="container clearfix">
        <?= $this->fetch('content') ?>
    </section>
    <footer>
    </footer>
</body>
</html>
```

## View(edit.ctp)

```
none

```

## Controller
```
    public function edit($id = null)
    {

        $this->Flash->success('sample');

    }
```

# Enviroment
* MAMP(Apache, PHP 5.6.10)
* CakePHP 3.1.4

Thank you. And Sorry my English.

**Comment by chinpei215** [comment]
@ykeisuke I would suggest you to ask in other place, as this issue tracker is not a help forum.
If you want to ask in Japanese (and if you don't mind unpleasant ads), how about 2ch.net?

And I would also suggest you to follow the quick start guide at first. I think it might be your best first step :)
http://book.cakephp.org/3.0/en/quickstart.html

**Comment by markstory** [comment]
If you `var_dump($this->Flash);` what do you get?

**Comment by ykeisuke** [comment]
@chinpei215 Thank you for advice.
I will try ask in other place. And I'm sorry, I used issue tracker by help. :pensive:
(And I need ask and question in Japanese...)

@markstory Thank you for question.
`var_dump($this->Flash);`  result is `boolean false`.

**Comment by ykeisuke** [comment]
I'm sorry. I understand in cause.
Cause is override `initialize` function.
But `parent::initialize();`  is not existed in override `initialize` function.

@chinpei215 @markstory Thank you. Your comment have trrigerd notice.

**Comment by chinpei215** [comment]
@ykeisuke You can close this issue by yourself.

**Comment by ykeisuke** [comment]
Thank you

**Comment by sagar12jan** [comment]
Add this line in function initialize() of your controller : $this->loadComponent('Flash');
and your problem will be surely resolve.
