### ISSUE TITLE
Negative Integers are interpreted as "string" in marshaller

### ISSUE THREAD

**Issue by NaranjaWeb** [cakephp/cakephp#7697]
Post data of negative integers are patched to the entity as string.

This happened after I upgraded to 3.1.4.

I found where you convert the data;

\Cake\Database\Type\IntegerType::mashal($value) {
...
}

also, I confirmed negative integers are not recognized as integers.

This seems to be the problem because all integer field of all databases accept negative integers,
and there are no reason to exclude negative integers from this function.

These days no one recommends == instead of ===, 
and using === cause errors when negative integers are set to the post data.

Is this already argued?

**Comment by dakota** [comment]
Proven with [this](https://github.com/cakephp/cakephp/compare/master...dakota:7697?expand=1) test case.

**Comment by dakota** [comment]
PHP's `is_int()` returns false for negative stringy integers

Which means that the following assert fails:
```php
        $result = $this->type->marshal('-105', $this->driver);
        $this->assertSame(-105, $result);
```

So, the simple fix that I thought of for this was to add a `is_numeric` check. However, this causes these two asserts to fail.
```php
        $result = $this->type->marshal('1.25', $this->driver);
        $this->assertSame('1.25', $result);

        $result = $this->type->marshal('2 monkeys', $this->driver);
        $this->assertSame('2 monkeys', $result);
```

So it seems like the expected behaviour is to only typecast to integer if phps internal type check is that of integer, otherwise return the same string as was passed in.

**Comment by ADmad** [comment]
How about changing the last `return $value;` in the method to `return intval($value);` ?

**Comment by dereuromark** [comment]
You could also do `is_int(abs($number))` I guess.
PS: For intval() it would rather use `(int)$number` cast.

**Comment by ADmad** [comment]
Though using intval() will also turn `'2 monkeys'` to `2`;

**Comment by markstory** [comment]
Closing as there is a good looking pull request up.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/7697

**Comment by jhli** [comment]
Should there be an internal utility class/bunch of methods that help with number data types juggeling - the cases listed by dereuromark/Admad alone seem to be painful pits to fall into. Maybe a well tested foundstion could be a good thing to be reused by the orm, the validations but also in app userland code?

**Comment by dereuromark** [comment]
@jhli That would also go for in_array() by the way or any of those strange methods that use type casting internally.

**Comment by ionas** [comment]
I am not sure how far it should/would go but the weak php types are really problematic and a solution on the framework side that is well tested and offers transparent/clean/obvious method interfaces and parameter lists would be very very welcomed.
