### ISSUE TITLE
About Email on CakePHP 3.0.15

### ISSUE THREAD

**Issue by zx4357685** [cakephp/cakephp#7702]
Hi guys，

I think the code in row 1866 of src\Network\Email\Email.php 

    $View->viewPath = $View->layoutPath = 'Email/' . $type;

should be change to 

    $View->viewPath = $View->layoutPath = 'Email' . DS . $type;

**Comment by dereuromark** [comment]
Can you make a PR with this change?

**Comment by ionas** [comment]
is there a (legacy?) reason this is named ```viewPath``` rather than ```templatePath``` (or ```viewTemplatePath```)?

**Comment by markstory** [comment]
We should avoid DS in the core code, as `DS` is not defined in CakePHP itself. Instead you must use `DIRECTORY_SEPARATOR`.

**Comment by dereuromark** [comment]
I thought using it in the core bundle is fine. Unfortunately, the PHP one is a very long constant.

**Comment by markstory** [comment]
@dereuromark We've stopped using DS in any of the packages that get split out, because we can't assume that DS will exist.

**Comment by markstory** [comment]
Fixed with #7706. Since we are only doing security releases for 3.0.x, this change had to be applied to 3.1.x
