### ISSUE TITLE
3.1.4 - XML::build not preserving nodes with arrays of 1 length

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7705]
Say I have this string:
```
<Response>
    <Status>1</Status>
    <Things>
        <Thing>...</Thing>
    </Things>
</Response>
```

Calling `XML::build` on that will give you:
```
SimpleXMLElement Object
(
    [Status] => 1
    [Things] => SimpleXMLElement Object
        (
            [Thing] => ...
        )

)
```

However, if you have multiple things, you get a different results:
```
<Response>
    <Status>1</Status>
    <Things>
        <Thing>...</Thing>
        <Thing>...</Thing>
    </Things>
</Response>
```
```
SimpleXMLElement Object
(
    [Status] => 1
    [Things] => SimpleXMLElement Object
        (
            [Thing] => Array
                (
                    [0] => ...
                    [1] => ...
                )

        )
)
```

This means if I use a service and try to loop through the 'things' I have to first figure out if it's singular or plural in order to know where my keys start. (Or I could use an isse for the foreach but that's the same issue.)

```
$foo = Xml::toArray(Xml::build($s));
$count = is_array($foo['Response']['Things']['Thing']) ? count($foo['Response']['Things']['Thing']) : 1;
foreach ($count === 1 ? $foo['Response']['Things'] : $foo['Response']['Things']['Thing'] as $thing) {
    pr($thing);
}
```

Do you guys see that as a problem, or is that something that should be addressed?

**Comment by markstory** [comment]
What happens when you feed your XML to `new SimpleXmlElement()`?

**Comment by jhli** [comment]
Should be addressed - I had troubles exactly with these kinds of array/xml transformations on my last cake3 webservice project.

**Comment by jhli** [comment]
Eg inconsistencies.

**Comment by markstory** [comment]
@jhli Ok, but some of those inconsistencies come from SimpleXmlElement and XML itself really, and can't really be addressed in a sane way. For example, one way we could 'fix' this issue is by treating every nested tag as an array, but I feel that creates an awkward to use structure.

**Comment by patrickconroy** [comment]
Hey @markstory, yeah unfortunately it looks the same if I pass that to `new \SimpleXMLElement` so I have no idea if this is something that can be changed without a bunch of manual string manipulation before sending it to `XML::build`.

**Comment by markstory** [comment]
Given that this is a 'feature' of XML, and SimpleXmlElement, I don't think this is something we can normalize in a reasonable way unfortunately.

**Comment by ionas** [comment]
Hm, I'd like to see every node level be represented as a numerical array. It is consistent then. Though as this is BC it should go against 3.2 - in case this is revived for consistency sake (<3)

**Comment by markstory** [comment]
@ionas Sure, but that might be something you'd have to take up with SimpleXmlElement. Rejigging an XML document of unknown width and depth is not something I'm interested in writing or maintaining long term.
