### ISSUE TITLE
Cannot enable/disable spellchecking via FormHelper

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#7708]
Both 2.x and 3.x.

According to WHATWG, `spellcheck` attribute is not like other boolean attributes such as `selected`.
Source: https://blog.whatwg.org/the-road-to-html-5-spellchecking#examples

Valid:
```html
<textarea spellcheck="true">
<textarea spellcheck="false">
```
Invalid:
```html
<textarea spellcheck>
```

But `FormHelper` doesn't work correctly.

```php
echo $this->Form->text('text', ['spellcheck' => true])
echo $this->Form->text('text', ['spellcheck' => false])
```
Output:
```html
<input type="text" name="text" spellcheck="spellcheck"/>
<input type="text" name="text"/>
```

Related: #6560

**Comment by markstory** [comment]
You'd have to use `'spellcheck' => 'true'` to get the results you want. Given that `true`/`false` are used for the more common boolean attribute case.

**Comment by chinpei215** [comment]
@markstory No, I couldn't. Because `spellcheck` attribute is contained in  [`_compactAttributes`](https://github.com/cakephp/cakephp/blob/5f5d1e19dbacdb95de523aade4835a6325b15e6c/src/View/StringTemplate.php#L78), we can only get `spellcheck=spellcheck` or nothing.

Source: https://github.com/cakephp/cakephp/blob/5f5d1e19dbacdb95de523aade4835a6325b15e6c/src/View/StringTemplate.php#L315-L322

**Comment by markstory** [comment]
Ah, ok. That is something I can fix then. Thank you for the clarification.

**Comment by chinpei215** [comment]
Thanks.

**Comment by markstory** [comment]
Pull request up now.
