### ISSUE TITLE
RFC Allow for Immutable date/datetime objects to be used.

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#7713]
In applications I've worked on, I've often made accidental side effects on date/time objects. This creates a number of problems:

1. Modifying a datetime object attached to an entity in place means that the changes are no persisted.
2. Modifying a datetime object is really easy, and thus 1. happens more than I'd like.
3. Having Immutable objects, better reflects the concept of [Value Objects](http://martinfowler.com/bliki/ValueObject.html) which complex mapped properties should be in my opinion.

With Chronos in place for 3.2 in a backwards compatible way, I'd like to discuss how we can enable *immutable* date/datetime objects for new applications, or existing applications that want to opt in. Because using immutable objects to be an opt-in process we cannot re-use the existing `Time`/`Date` classes. I propose that we add 2 new classes for to solve this problem:

* `Cake\I18n\FrozenDate` An Immutable Date object, that implements the same methods as `Cake\I18n\Date`.
* `Cake\I18n\FrozenTime` An Immutable DateTime object, that implements the same methods as `Cake\I18n\Time`.

These classes could achieve method parity by leveraging traits, or delegating to common objects.

### Opt-In process

Opting into immutable objects feels like a global setting to me. This feels like a responsibility of the Date/time/datetime type mappers. I'm proposing something like:

```php
// in config/bootstrap.php
Type::build('date')->useImmutable();
Type::build('datetime')->useImmutable();
Type::build('time')->useImmutable();
```

This allows developers to opt into immutable objects for the types that matter to them, and more importantly lets us enable immutable objects for new applications going forwards.

### Open Questions

* [x] Do the classnames make sense? Are there better classnames we could use.
* [x] The `timeAgoInWords()` methods are quite hairy, putting them into traits will require 2 additional new traits. Is it better to use a 'helper' object instead?

**Comment by lorenzo** [comment]
:+1:

* The class names make sense
* A helper object would be best. Ideally, the injector for the helper object should live in Chronos. So we can better replicate how Carbon works if needed

**Comment by markstory** [comment]
> Ideally, the injector for the helper object should live in Chronos. So we can better replicate how Carbon works if needed.

The `timeAgoWords()` is a CakePHP only extension to chronos. Why would we need an injector?

**Comment by lorenzo** [comment]
@markstory because carbon has their own version. Not providing a replacement will probably hinder their users switching to ours :D

**Comment by markstory** [comment]
@lorenzo Are you referring to the [translator object](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L2207-L2274) in this code?

**Comment by lorenzo** [comment]
@markstory I'm referring to their `diffForHumans` we are offering nothing to them if they switch to chronos. Ideally there should be a way for them to have that method back, and the best way I can think of is by having an injectable helper object with the implementation.

**Comment by markstory** [comment]
Ok, I can start on building an english only (but extensible) `diffForHumans()` in chronos. Hopefully we can build on that when doing `timeAgoInWords()` which is significantly more complex than `diffForHumans()`

**Comment by jhli** [comment]
I'd like the immutable once being defaul for Time:: etc. further down the line.

**Comment by markstory** [comment]
@jhli I would as well, but its a non-trivial break in behavior.

**Comment by lorenzo** [comment]
Already implemented
