### ISSUE TITLE
Composite key support is inadequate

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7720]
The Bookmarker tutorial proudly says that "CakePHP supports composite keys almost everywhere".
- The Documentation only mentions composite keys in one place, when using it for a primary key.
- There are no naming conventions for composite keys defined in the documentation.
- Cake Bake generates scaffolding code fine, for models using composite primary keys, but any models referencing such a model, using composite foreign keys, are not supported by bake. I can't find any documentation for using composite keys for foreign keys.

If CakePHP 3.\* supports Composite keys, lets support it properly, and document it, and set naming conventions.

I would suggest using the same format in the belongsTo array, as we use for the primary key when it is composite:
$this->primaryKey(['id1', 'id2']);

Use the same syntax for composite foreign keys:
        $this->belongsTo('Parent', [
            'foreignKey' => ['parent_id1', 'parent_id2'],
        ]);

**Comment by lorenzo** [comment]
The code in your example is exactly how it works. The only limitation we have right now is in bake, as no one has done the work to detect and generate the associations.

**Comment by lorenzo** [comment]
I think I can add to the book some examples of using composite keys with the associations

**Comment by half2me** [comment]
Thanks for the fast reply, this would be a great help.

**Comment by lorenzo** [comment]
@half2me for now, just try your own example. That is how it is supposed to work :)

**Comment by half2me** [comment]
It works, just like you said, I just had to adjust the belongsTo and hasMany parameters.
Hoping that helpers will support composite keys as well.

**Comment by lorenzo** [comment]
@half2me helpers?

**Comment by half2me** [comment]
@lorenzo http://book.cakephp.org/3.0/en/views/helpers.html
FormHelper in particular...

**Comment by lorenzo** [comment]
@half2me what about the form helper?

**Comment by jhli** [comment]
I did work on bake composite key sipport for actions/templates - only tests missing and still clueless about those.

**Comment by half2me** [comment]
@lorenzo my bad, formhelper is working fine, its Bake which is generating strange scaffolding code.
When I run bake on most models (not using composite keys) It generates templates i.e: "Add.ctp"
If I take the following model (A hasMany B)
On this template, When I want to add a new instance of the B, it gives me a dropdown list to choose which existing A model should be the owner of this new B model.

But when using composite keys the results are very strange:
This is my model: A hasMany B; B hasMany C
A(id, name) - Primary key 'id'
B(id, a_id, name) - Primary key is ('id', 'a_id') - Foreign key is 'a_id' Referencing A(id)
C(id, b_id, b_a_id, name) - Primary key is 'id' - Foreign key is (b_id, b_a_id) Referencing B(id, a_id)

Bake gives me code with the templates, but uppon added a model with add.ctp I get:
Model A - All is fine!
Model B - There is no dropdown menu to select an A model. (Left side 'Action' menu doesn't list C model)
Model C - There are two dropdown menus to select from B model.

I don't know what the expected result should be exactly, but this is what I experience.

**Comment by lorenzo** [comment]
Yeah, we currently know bake is not able to generate the correct templates and there are people working on that :)

**Comment by half2me** [comment]
@lorenzo Okay :)

**Comment by LACabeza** [comment]
I also had difficulty to deal with composite.
In the end i created a virtual property on entity to get the composite key concatenated with a semicolon (like "id1;id2"), on table class, then on form helper i used that virtual property on a select, and finally i used the beforeMarshal on table class to read the selected option split that value into 2 and set it on the fields i wanted.

**Comment by lorenzo** [comment]
@LACabeza That is actaully how the form helper and marshaller are working currently. What was the problem you were having?

**Comment by LACabeza** [comment]
It's not that i'm having problem, i only tried to help describing what i did to deal with the form helper (sorry for my poor english).

**Comment by lorenzo** [comment]
@LACabeza My question was more about why did you have to do all that, when it is done automatically by cakephp?

**Comment by half2me** [comment]
@lorenzo 
In the CakePHP Documentation:
http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html
"CakePHP provides a simple to use method for generating ‘lists’ of data:...
With no additional options the keys of $data will be the primary key of your table, while the values.."

What if the primary key of my table is a composite key? As far as I know you can't index an array with another array...

**Comment by LACabeza** [comment]
Oh i see. I just baked a new template here to check if same thing still happens (and it does). 
In my case, table A belongs B, and B is composite key.

The baked template generates 2 text fields, but i wanted a select option. I tried leave to cake deal with the data, but it didn't work. I didn't know what name the input should have. When it's some thing like `$thigs->Form->input('field_id', ['options' =>[]])`, it works fine, but composite key not.

And I couldn't find help on documentation, so as you say, i probably reinvented the wheel.

**Comment by LACabeza** [comment]
@half2me in that case you will get both values concatenated with semicolon, like this:

     [
         "a1;b1" => 'First post',
         "a2;b2" => 'Second article I wrote',
     ];

**Comment by LACabeza** [comment]
@lorenzo there is others things that should be documentated as well.
Like, the view action usually expect a single param `view ( id = null )`, so it don't work for composite keys. 
I added another param and create links like `$this->Html->link(__('View'), ['action' => 'view', $entity->first, $entity->second])`. (This don't works well for restfull controllers, but i don't know what else can i do).

**Comment by half2me** [comment]
@LACabeza What if my Primary key is of type VARCHAR, and I have a ';' in my key. Will cake escape this value automatically?

**Comment by LACabeza** [comment]
I don't know. I also have varchar keys, but in my case i'm sure i won't have ; in my keys...
you may want to use \Cake\Utility\Text::tokenize to handle your data, since it can escape it
```
>>> \Cake\Utility\Text::tokenize('"a1;b1";"x1;y1"',';','"','"');
=> [
     ""a1;b1"",
     ""x1;y1"",
   ]
```

**Comment by markstory** [comment]
@half2me CakePHP will not escape `;` if you have string primary keys that also contain `;`.

**Comment by neo21181** [comment]
@lorenzo I am currently working on a REST API application that requires to create a record with a "composite foreign primary key" from two tables, as in Phonebooks table, where my primary key is customer_id from customers table and dial_id from dials table
i get the following error 
> Cannot insert row, some of the primary key values are missing. Got (, ), expecting (user_id, dial_id)

when i tried the following "JSON":

`{      "user_id": 1,
      "dial_id": 4,
      "fname": "neo",
      "lname": "test",
      "nickname": "one"}`

while POSTing in order to insert
using the following piece of code

`        $User_var = $this->getUser($id);
        $phoneBook = $this->PhoneBooks->newEntity();
        if ($this->request->is('post')) {
            $phoneBook = $this->PhoneBooks->patchEntity($phoneBook, $this->request->data);
            if ($this->PhoneBooks->save($phoneBook)) {
                //some code
            }
               //error handling
        }
        $this->set(compact('phoneBook'));
        $this->set('_serialize', ['phoneBook']);`

can you help me identify what went wrong with my syntax!

**Comment by lorenzo** [comment]
@neo21181 please go to the slack channel and we willl help you there

**Comment by dereuromark** [comment]
This is super stale, anything to be done or can we close?

**Comment by lorenzo** [comment]
@dereuromark it can be closed, this has always been a bake-related issue
