### ISSUE TITLE
how to create the admin panel

### ISSUE THREAD

**Issue by ashishseth89** [cakephp/cakephp#7723]
I am using cakephp 2.7 .

i want to create the admin of website url  like example.com/admin which open the login page.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
