### ISSUE TITLE
Trying to set CsrF and Cookie to secure and HttpOnly

### ISSUE THREAD

**Issue by ukkpower** [cakephp/cakephp#7727]
I have added my code to the AppController `initialize()` 

     public function initialize()
      {
        
        parent::initialize();

        $this->loadComponent('Csrf', ['secure' => true]);
        $this->loadComponent('Cookie',
            [
                'httpOnly' => true,
                'secure' => true
            ]
        );
    }

But the cookies to me seem like they are not secure or fully HttpOnly.  I am able to submit forms and login through a non secure http

Should these be restricted since I am only using http?

<img width="1273" alt="screen shot 2015-11-23 at 7 41 53 p m" src="https://cloud.githubusercontent.com/assets/1074922/11347880/401d248a-921b-11e5-8f40-c509c4aebcbf.png">

**Comment by lorenzo** [comment]
The secure flag can only be set if you send the cookie via https

**Comment by ukkpower** [comment]
Visiting via https is exactly the same results as screenshot.

Also my understanding of the documentation is if I set secure than non secure visit should be restricted/error?  "That is, the cookie will only be set on a HTTPS connection and any attempt over normal HTTP will fail. Defaults to false."

**Comment by lorenzo** [comment]
I actually just tried it myself. The csrf cookie was not set when I enabled the `secure` option. Try deleting your cookies and try again, please

**Comment by ukkpower** [comment]
Yes I had tried empty cache with hard reload and https://detectify.com scan should the same issue

**Comment by markstory** [comment]
The `CAKEPHP` cookie in your screen shot is not created by the CookieComponent. That is a session cookie, and its configuration is controlled by the `Session` configuration in your `config/app.php`.

Enabling the secure option on CsrfComponent worked for me, and curl shows the correct output:

```
$ curl -v cake3.localhost/
*   Trying 127.0.0.1...
* Connected to cake3.localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: cake3.localhost
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 24 Nov 2015 02:53:15 GMT
< Server: Apache/2.4.16 (Unix) PHP/5.5.27
< X-Powered-By: PHP/5.5.27
< Set-Cookie: csrfToken=c5bee260732605165015440c838dca133d9cb671; path=/; secure
< X-DEBUGKIT-ID: 276b0b2c-7272-4457-aaad-79d6c3bcecab
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
```

**Comment by ukkpower** [comment]
I have done the same and you are right, I get `secure` returned even though chrome dev tools tells me otherwise. The session cookie has both HttpOnly and Secure as expected.

`Set-CookiecsrfToken=831fe746a2d5748bd8dee527590567af4530da58; path=/; secure`

Is it possible to set the CsrF token to HttpOnly also? Security scanners highlight this as a possible place for attack.

What is setting `$this->loadComponent('Csrf', ['secure' => true]);` meant to do? I can still submit the form even though I am using http

**Comment by markstory** [comment]
Right now there isn't a way to make the CsrfToken httpOnly, but it should be simple enough to add.

**Comment by markstory** [comment]
Fixed with #7742

**Comment by ionas** [comment]
@ukkpower 
> Is it possible to set the CsrF token to HttpOnly also? Security scanners highlight this as a possible place for attack.
Which? Can you be more specific on the source?

**Comment by ionas** [comment]
Related: https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet#Bonus_Rule_.231:_Use_HTTPOnly_cookie_flag
