### ISSUE TITLE
invalid argument exception

### ISSUE THREAD

**Issue by kings360** [cakephp/cakephp#7733]
tried creating a new cakephp project using composer and it should invalid argument exception
could not find package cakephp/app with stability stable

i hv been creating projects without any issues earlier.

**Comment by lorenzo** [comment]
Can you show what you did and the full error you got?

**Comment by kings360** [comment]
composer create-project --prefer-dist cakephp/app filename
![errormsg](https://cloud.githubusercontent.com/assets/9676885/11394669/81134d6c-938c-11e5-907c-e276b760b91b.jpg)

**Comment by lorenzo** [comment]
I just tried that locally and it works for me. Try deleting the composer cache

**Comment by kings360** [comment]
i deleted cache, still same error

**Comment by ADmad** [comment]
Maybe it's a windows issue?

**Comment by lorenzo** [comment]
Could be... or maybe just a connectivity issue

**Comment by kings360** [comment]
composer create-project --prefer-dist cakephp/cakephp filename
installs cakephp 2.7.7,

**Comment by ADmad** [comment]
`create-project` needs to be done for `cakephp/app` not `cakephp/cakephp`

**Comment by lorenzo** [comment]
@ADmad I think his point it that there was no connectivity issue by trying to install something else

**Comment by burzum** [comment]
Works for me as well (Win 8.1.)

![screenshot 2015-11-25 14 30 40](https://cloud.githubusercontent.com/assets/162789/11398731/02cc5fec-9383-11e5-9fff-41f595367972.png)

**Comment by chinpei215** [comment]
@burzum Me too (Win 10).
@kings360 Maybe, do you have `G:\xampp\htdocs\composer.json`? If you run the same command in some other directory, what do you get?

**Comment by ADmad** [comment]
Please share your PHP version too everyone :)

**Comment by burzum** [comment]
PHP 5.6.0 - I should update it...

**Comment by kings360** [comment]
im able to create project in another machine. but the issue still persists in the old machine. I use PHP Version 5.6.14

**Comment by markstory** [comment]
Sounds like a machine specific issue that we're not going to be much help with.

**Comment by kings360** [comment]
The issue has been resolved. PHP in composer has been pointing to the php settings in IIS. Changed to the latest xampp settings and everything worked fine

**Comment by pardeep7387** [comment]
There are two commands to install CakePhp App on Windows......
