### ISSUE TITLE
When Many-to-Many table is associated to many, Marshaller marshals incorrectly

### ISSUE THREAD

**Issue by heavykevy** [cakephp/cakephp#7735]
I have Students attending colleges with the college has many states and am storing the attendance dates in the join table.

```php
$student = $this->Students->patchEntity( $student, $this->request->data, ['associated'=>['Colleges' => ['States', '_joinData']]] );

creates an invalid property map with 4 array items
[
assoc => [belongs to many],
0 => 'States',
1=> '_joinData'.
associated => []
]
```

I was able to solve my issue by changing the _buildPropertyMap() method from:

to:
```php
foreach ($include as $key => $nested) {
            if (is_int($key) && is_scalar($nested)) {
                $key = $nested;
                $nested = [];
            }
            $assoc = $this->_table->association($key);
            if ($assoc) {
            	if (count($nested) > 1) {
            		$map[$assoc->property()] = ['association' => $assoc] + ['associated' => $nested ];
            	} else {
            		$map[$assoc->property()] = ['association' => $assoc] + $nested + ['associated' => []];
            	}
            }
        }
        return $map;
```

**Comment by lorenzo** [comment]
Your issue is not clear... But I can see the syntax of your `associated` array is incorrect as well. Please try:

```php
 ['associated' =>  ['Colleges.States._joinData']]
```

The syntax above will save you some typing and possible errors too

**Comment by heavykevy** [comment]
Okay, I will try that.

Thanks...

**Comment by heavykevy** [comment]
Jose,
That did not throw any errors, however the _joinData was lost.
Also, it does not make sense to me...
If students has and belongs to many colleges
and colleges has many states,
then why would _joinData be attached on states?

**Comment by heavykevy** [comment]
Jose,
I reversed the order:
'Colleges._joinData.States'
and that seems to have worked.

Thank you for your help.
Best regards,
--Kevin
