### ISSUE TITLE
TimeHelper i18nFormat gives always UTC

### ISSUE THREAD

**Issue by didderot** [cakephp/cakephp#7736]
*Ubuntu 14.04, PHP 5.5.9, MySQL 5.5.4, CakePHP 3.0-3.2*

I have dates saved as UTC in my DB. When I call in my template:

`$this->Time->nice($date, 'Europe/Berlin');`

times get correctly converted into GMT+1.

But when I use:

`$this->Time->format($date, 'HH:mm', null, 'Europe/Berlin') ;`

it is still UTC, which is not correct.

I think, the source of this problem lies in View/Helper/TimeHelper.php::i18nFormat:336:

>$time = new Time($date, $timezone);
>return $time->i18nFormat($format, $timezone);

here the Time object is constructed with the target timezone, which is wrong. I think it should be:

`$time = new Time($date);`

Bye

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. The following test passes for me locally.

```php
public function testFormatTimeInstance()
{
    $time = new Time('2010-01-14 13:59:28', 'UTC');
    $result = $this->Time->format($time, 'HH:mm', null, 'America/New_York');
    $expected = '08:59';
    $this->assertTimeFormat($expected, $result);
}
```

The default timezone for me is UTC.

**Comment by lorenzo** [comment]
@markstory I think the problem is when a string date is passed instead of an object

**Comment by markstory** [comment]
@lorenzo You were right. Fix is up now.

**Comment by didderot** [comment]
Thanks guys! And sorry for my "fault" - the $date in my code was really a string. I bypassed the ORM in this special case and didn't get a Time object as usual. But now with the fix even this works.
