### ISSUE TITLE
3.x: find('list', ['keyField' => 'id', 'valueField' => 'assoc.value']) issues

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#7737]
Hi!

I have a relation from `Companies` to `CompanySettings` that are `BelongsToMany` - so I have a table called `CompanySettingsCompanies` (why u no follow standard join table names?! - No good answer)

A `CompanySetting` has a property called `identifier` - and the `CompanySettingsCompanies` has a property called `value`

now what I want is a list of `CompanySettings` with values for a specific company - so I do:

## Doesn't work

```
$companySettingsQuery = $this->CompanySettings
            ->find()
            ->contain([
                'CompanySettingsCompanies' => function ($q) use ($companyId) {
                    return $q->where(['CompanySettingsCompanies.company_id' => $companyId]);
                }
            ]);
```

and it returns something like:
```
0 => object(App\Model\Entity\CompanySetting) {
		'identifier' => 'allow_employees_to_add_new_products',
		'company_settings_companies' => [
			(int) 0 => object(App\Model\Entity\CompanySettingsCompany) {

				'id' => 'e70bfb7e-20ec-4ee6-a12f-a60ffb5530f9',
				'company_setting_id' => '19f7a36c-8b40-42a2-81ba-d942967b472e',
				'company_id' => 'e44f293e-5395-46fa-9d0e-947956a44f4a',
				'value' => 'Nej',
			}
		],

	},
```
(Extra properties removed)

Well - that all looks good (kinda)

If i do fire off following instead:

```
$companySettingsQuery = $this->CompanySettings
            ->find('list', [
                'keyField' => 'identifier',
                'valueField' => 'company_settings_companies.value'
            ])
            ->contain([
                'CompanySettingsCompanies' => function ($q) use ($companyId) {
                    return $q->where(['CompanySettingsCompanies.company_id' => $companyId]);
                }
            ]);
```

it returns following list:
```
<?php
$result = [
	'allow_employees_to_add_new_products' => null,
];
```

(the `valueField` is not really the `company_settings_companies.value` property)

## Does work

If I however do the following instead:
```
$companySettingsQuery = $this->CompanySettingsCompanies
            ->find('list', [
                'keyField' => 'company_setting.identifier',
                'valueField' => 'value',
            ])
            ->where(['CompanySettingsCompanies.company_id' => $companyId])
            ->contain(['CompanySettings']);
```

It returns 

```
$result = [
	'allow_employees_to_add_new_products' => 'Nej',
];
```

Which is correct - but then I do only get the values of the `CompanySettings` that has actually been made - where it would be more awesome to just have included all company_settings and then a value if it exists, or null if not (which I would think would be the first thing done...)

I can't make it do that even with 2nd try with right joining the `CompanySettings` table to `CompanySettingsCompanies`

## So why u make issue?

I think it should be clarified in the docs what you can, and what you can in terms of using assoc in 'keyField' and 'valueField' - and I'll happily to write it if anyone clears out if this is just me, and issue in cake or an issue in the docs...

**Comment by Spriz** [comment]
It would make sense to me if only `belongsTo` and ´hasOne´ could be used as assoc - since otherwise it's something like `'keyField' => 'assoc.[0].value'` - but I think it needs to be stated if that's the reason :smile:

**Comment by lorenzo** [comment]
If you know how to explain what is possible in the docs, please send us a PR. I would appreciate that :)

**Comment by lorenzo** [comment]
@Spriz Can you explain what would be your expected result in the first example?

**Comment by Spriz** [comment]
@lorenzo - I do not know how to explain it before I realise it myself :laughing: 

I'd expect/hope that it would work as `['keyField' => 'CompanySettings.identifier', 'valueField' => 'company_settings_companies[0].value']`...

It would be fine with just the 1st record in `company_settings_companies` since I know by design that a the CompaniesCompanySettings are unique on company_id and company_settings_id - so only one setting per company exists.

I expect/want it to output `'[allow_employees_to_add_new_products' => 'false', allow_employees_to_add_new_projects' => 'true']`

**Comment by lorenzo** [comment]
why not use the path for the first, then? `company_settings_companies.0.value`

**Comment by Spriz** [comment]
> Takes his hat an leaves...
