### ISSUE TITLE
3.1 Auth Adapter 'Storage' key defaults

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7739]
Ref: http://book.cakephp.org/3.0/en/controllers/components/authentication.html#creating-stateless-authentication-systems

**A)** The defaults should be:
```'storage' => 'session'``` for form/cookie based authentication adapter setups.
```'storage' => 'memory'``` for static (http basic auth etc) based authentication adapter setups.
This will take away a lot of pain combining both (having admin panels and web service users) and will also help with accidental security holes in applications mixing both.

**B)** cake book documentation about **'storage'** is lackluster. I'd take care about that myself but I am not convinced that I know enough about Auth adapters and the storage key to add a passage.

**Comment by ADmad** [comment]
A) There can be only one default value and that's set to `Session`. There really isn't way to guess and auto select appropriate storage class.

B) There really isn't much to say about the `storage` config besides "Use 'Session' for cookie based and use `Memory` for stateless" which is already stated. I have updated the code examples for Basic and Digest auth to show setting to 'storage' to 'Memory'.

**Comment by lorenzo** [comment]
@ADmad I think a code example is due. It is almost impossible to understand how to use the storage for the wall of text in that section of the docs

**Comment by ADmad** [comment]
The code examples have been updated to included 'storage' key.

**Comment by ionas** [comment]
About **A)**, would this be possible?
- If 'authenticate' is set to Basic or Digest and 'storage' is not set by the application, then 'storage' should be set to 'Memory'.
- If 'authenticate' is set to Form, and 'storage' is not set by the application, then 'storage' should be set to 'Session'.

**Comment by ionas** [comment]
Related: Why is 'storage' not inside of 'authenticate'?

**Comment by markstory** [comment]
> Related: In terms of configuration hashes, why is 'storage' not inside of 'authenticate'?

Because storage is not only used by authentication.

**Comment by ionas** [comment]
By what else? Authorization (ini based ACL?). If that's the case it should be inside a hash key related to that feature?

**Comment by markstory** [comment]
Its used by `Auth::user()` for one, which is not solely related to authentication.

**Comment by ADmad** [comment]
Closing as there's nothing more to be done here. Any further issues/PRs related to docs can goto docs repo.

**Comment by ionas** [comment]
@ADmad could answer my question or should I open up a new Issue?


About A), would this be possible?

> If 'authenticate' is set to 'Basic' or 'Digest' and 'storage' is not set by the application, then 'storage' should be set to 'Memory'.
> If 'authenticate' is set to 'Form', and 'storage' is not set by the application, then 'storage' should be set to 'Session'.
> Can you think of a better convention?

**Comment by ADmad** [comment]
Even if we were to do what you suggest  we wouldn't be able to guess the storage for custom authenticate classes. So we can't implement half solutions. 

I am not in favor of any implicitly juggling of `storage` value in any case. Devs should set proper value based on authenticate classes they are using.

**Comment by ionas** [comment]
Sounds like things are mixed a bit too much. Won't pursue anything further. Thanks for explaining :).
