### ISSUE TITLE
->toArray() non recursive when ->contain & ->matching

### ISSUE THREAD

**Issue by Kitcat711** [cakephp/cakephp#7746]
Bonjour,
Here is my query, from PropertiesController

		$query
			->contain(['Leases' => function($q) {
				return $q
					->matching('NaturalPeople')
					->where(['LeasesNaturalPeople.role IN' => ['holder']])
					->select([ 'property_id','id','name'])
					->select(['NaturalPeople.id', 'NaturalPeople.firstname'])
					;				
				}]
			);

when calling:
$properties = $query->first()->toArray();
the result is recursive and I got no entities in $properties

When calling:
$properties = $query->all()->toArray();
Only the first entity level (aka "Properties" here) is converted to an array. No recursivity, the contain and matching results are still CakePHP entities.

Since, I use a Json afterward, my frontend has to handle the entities.
Thank you for your support.

Kitcat711

**Comment by lorenzo** [comment]
`toArray()` in the context of collections (and queries) means: return the results as an array list. It does not mean all the internal variables will be converted to arrays.

May I ask what is the realation between calling toArray() and json?

**Comment by Kitcat711** [comment]
No relation between the calling of to Array() and JSON, just that I want my JSON with only arrays.

May I ask why then, the $query->first()->toArray returns the internal variables as an array?

**Comment by lorenzo** [comment]
@Kitcat711 because the return value of first() is an entity. An entity->toArray() is actually an array.

You don't need to convert to array before converting to json. Doing `json_encode($query->all())` is enough.
