### ISSUE TITLE
REQUIRE FAILED error 

### ISSUE THREAD

**Issue by bigworkspace** [cakephp/cakephp#7756]
please see screenshot.
![cakephp error](https://cloud.githubusercontent.com/assets/15920104/11458452/5645d5e8-96e6-11e5-883e-d573e2cd016d.PNG)

Help me with this spent hours already.
Totally new begginer.

**Comment by ADmad** [comment]
Follow the [installation](http://book.cakephp.org/3.0/en/installation.html#installing-cakephp) guide.

Please don't the issues tracker for help request. Post your question on stackoverflow.com or ask on #cakephp IRC channel.
