### ISSUE TITLE
run application rules from associated table before saving

### ISSUE THREAD

**Issue by chipco** [cakephp/cakephp#7758]
I've been searching [the book] (http://book.cakephp.org/3.0/en/orm/validation.html#applying-application-rules) for a way to avoid getting in a situation where the main entity is saved and it's association is not due to failing an application rule.

Is there a way to tell the main `Table` to run the rules in the `buildRules` function of the associated `Table` before saving?

**Comment by lorenzo** [comment]
I does that automatically if you are saving associations. Since the save is run inside a transaction, if any of the rules fail, in an association or a main table, none of the changes will be applied

**Comment by chipco** [comment]
If it did it automatically I wouldn't be asking.

Here's a [gist] (https://gist.github.com/chipco/a7ca8e1465ca1937d276) with my models, controller and add template.

Saving a `Machine` with a `ComModule` property `IDModul` that already exist, leaves me with a new Machine, no new ComModule, and the browser shows the edit page indicating the unique error on the field IDModul.

**Comment by ADmad** [comment]
If you are using Msyql make sure your tables are using Innodb engine. MyISAM engine does not support transaction.

**Comment by chipco** [comment]
I'm working with a legacy app database and indeed it's MyISAM. Thanks for the info.
