### ISSUE TITLE
UTF8 database text not working on cakephp3

### ISSUE THREAD

**Issue by mohsinkabir** [cakephp/cakephp#7760]
i upgrade my application to cakephp3 . it is working perfectly on lower versions of cakephp3 . But on cakephp3 utf8 text which are comming from mysql db is not showing perfectly . 

I changed the encoding on app.php file and also change the db encoding config . Please help me to figure it out.

**Comment by ADmad** [comment]
CakePHP works perfectly fine with utf8 encoded database text.

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
