### ISSUE TITLE
Calling requestAction from console

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#7763]
Hello

I just want to ask, since this is not clear from the documentation. Is it possible to add RequestActionTrait on the class used from the Shell and request a controller action? It behaves strange in my app and I just want to be sure this is possible.

Thanks

**Comment by markstory** [comment]
Possible, but probably not going to work. The CLI sapi has a number of quirks that are not present in a web context like requestAction. I would generally recommend putting logic you need in both a CLI/and HTTP context into 'service' classes that are simple wrappers over the various models that need to be combined.

**Comment by segy** [comment]
Thank you
