### ISSUE TITLE
Route scopes don't work without calling fallbacks();

### ISSUE THREAD

**Issue by timhoeppner** [cakephp/cakephp#7764]
Simple example, routes.php

```php
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function ($routes) {
    $routes->connect("/test", ["controller" => "Projects", "action" => "index"]);
    $routes->connect("/test/:action/*", ["controller" => "Projects"]);
});

Plugin::routes();
```

opening http://localhost/test results in a routing error and a strange one at that. It reports that it can't find a route for controller "Requirements" (another controller in my project). Also, in the debug output, the system is reporting that my /test route exists but for some reason it won't connect. See http://imgur.com/s3cPoYx 

The only way I can get things to work is by adding a call to fallbacks() as shown below.

```php
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function ($routes) {
    $routes->connect("/test", ["controller" => "Projects", "action" => "index"]);
    $routes->connect("/test/:action/*", ["controller" => "Projects"]);

    $routes->fallbacks();
});

Plugin::routes();
```

I can't find anywhere in the documentation that this is required. According to http://book.cakephp.org/3.0/en/development/routing.html#fallbacks-method all the fallbacks method does is add some default routes.

**Comment by ADmad** [comment]
> It reports that it can't find a route for controller "Requirements" (another controller in my project)

That's your problem. The stack trace on the error page shows that in your `Projects/index.ctp` template you have a url for `['controller' => 'Requirements', 'action' => 'index']`  and since you haven't set an explicit route for it you need the fallback routes for the router to be able to generate URL for it.

**Comment by timhoeppner** [comment]
Thanks admad, I hadn't looked close at my stack trace to notice that was the issue. Much appreciated for the clarification.
