### ISSUE TITLE
CakePHP 3.1: SQL Server with Replication

### ISSUE THREAD

**Issue by stmeyer** [cakephp/cakephp#7765]
Hello,

I think there is a bug with SQL Server with enabled replication. Before starting the replication CakePHP 3.X works well. After starting the replication I get the following error, by inserting a dataset:

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The target table 'dbo.*' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause. 
```
```
INSERT INTO [dbo].[*] ([..., ..., ..., ...) OUTPUT INSERTED.* VALUES (:c0, :c1, :c2, :c3)
``` 

SQL Server replication works allways with triggers. It would be hard, if CakePHP would not support it.

Thanks...

**Comment by lorenzo** [comment]
Unfortunately, in order to avoid race conditions, the output of the insert is necessary. If you are knowledgable of SQL Server, I would be interested in getting help for finding an alternate solution that could work for replication.

**Comment by lorenzo** [comment]
What exactly is `[dbo].[*]` and why are you inserting into that table?

**Comment by dakota** [comment]
@lorenzo What confuses me is that the error message says ` enabled triggers if the statement contains an OUTPUT clause without INTO clause. `, however the statement very clearly has an `INTO`.

Wonder if it's related to the `[dbo].[*]`? Sounds like a "Insert into all tables"?

**Comment by stmeyer** [comment]
Thanks, for the fast response. Maybe I can help to find a solution. I hope Cake is using the output to get the generated ID of a new row. Maybe a soulution is somethink like this:
```sql
declare @tmptalbe table (id int)
INSERT INTO [dbo].[users] (
	[firstname]
	,[surname]
	,[username]
	,[email]
	,[language]
	,[date_last_visit]
	,[comment]
	,[active]
	,[created]
	,[modified]
	,[created_by_user_id]
	,[modified_by_user_id]
	)
OUTPUT INSERTED.id INTO @tmptalbe
VALUES (
	'test'
	,'test'
	,'test'
	,'test@domain.dtl'
	,'en'
	,getdate()
	,'test'
	,1
	,getdate()
	,getdate()
	,1
	,1
	)
select * from @tmptalbe
```
The temporary table can be generated automaticaly. The ORM should have the column informations.

@dakota  Yes, you are right. ```[dbo].[*]``` is for every table in the database with enabled replication.

**Comment by lorenzo** [comment]
Is that a known workaround in SQL server for having output in insert clauses when replication is involved?

**Comment by stmeyer** [comment]
I found the soulution at http://blogs.msdn.com/b/sqlprogrammability/archive/2008/07/11/update-with-output-clause-triggers-and-sqlmoreresults.aspx and at http://www.sql-server-helper.com/error-messages/msg-334.aspx. It works well, without the case, if the trigger is changing the inserted data. Example: A table with columns ID (auto generated), Username, DateChange (Automatically set by Trigger on Insert and Update). When I run
```sql
declare @tmptalbe table (id int, Username varchar(50), DateChange datetime)
INSERT INTO [dbo].[Table_1]
           ([Username])
OUTPUT INSERTED.* INTO @tmptalbe
VALUES ('testname')
select * from @tmptalbe
```
The result would be: ID: 1234, Username: testname, DateChange: NULL

**Comment by lorenzo** [comment]
That is quite a complex solution, sadly... but I guess we have no other choice

**Comment by stmeyer** [comment]
If you need further informations or any help, feel free to ask. And thanks for your work!

**Comment by lorenzo** [comment]
@stmeyer Would you be willing to submit a patch for this? I can guide you in the process. I cannot commit to working on this soon because I don't own any windows license at the moment

**Comment by stmeyer** [comment]
Okay, I'm using Cake for some month and i never used Git(Hub), but I will try to help. I find out, that the statement is built in ````\Cake\Database\SqlserverCompiler::_buildInsertPart```. Additionally the affected columns are in the parameter ```$parts[1]```. But for the solution i need the column types. Can I load them from TableRegistry?

**Comment by lorenzo** [comment]
Yes, in theory you could use the schema in the table for that

**Comment by stmeyer** [comment]
I have a litte problem to map from the internal data type 
```
`[
	'type' => 'string',
	'length' => '100',
	'null' => false,
	'default' => null,
	'precision' => null,
	'comment' => null,
	'fixed' => null
]
```
to the SQL Server data type. I tried to create a ```SqlserverSchema``` Object to use the method ```columnSql```, but I was not able to create a ```Cake\Database\Schema\Table``` Object. Do yo have any hints for me?

**Comment by lorenzo** [comment]
The schema class can be used to re-create tables. Check the `TestFixture` class for an example of how the schema is used to create tables.

**Comment by markstory** [comment]
Are temp tables per connection in sqlserver? How would that interact with persistent connections or pooling?

Could the more complex insert mode be a configuration option?

**Comment by stmeyer** [comment]
@markstory the ```declare @tmptalbe table (id int, Username varchar(50), DateChange datetime)``` is a TSQL variable. It is only declared for one query. 

I have seen, that in the ```QueryCompiler``` class the method ```_buildInsertPart``` is not using any ```OUTPUT```. How is it done in other drivers, such as MySQL? How do you get the ID there?

**Comment by HavokInspiration** [comment]
@stmeyer I think you are looking for the SqlserverCompiler class : https://github.com/cakephp/cakephp/blob/master/src/Database/SqlserverCompiler.php

**Comment by markstory** [comment]
All other database vendors provide driver methods we can use to get the last increment value.

**Comment by stmeyer** [comment]
Okay, so this could also be used:
````sql
INSERT INTO [dbo].[users] (
    [firstname]
    ,[surname]
    ,[username]
    ,[email]
    ,[language]
    ,[date_last_visit]
    ,[comment]
    ,[active]
    ,[created]
    ,[modified]
    ,[created_by_user_id]
    ,[modified_by_user_id]
    )
VALUES (
    'test'
    ,'test'
    ,'test'
    ,'test@domain.dtl'
    ,'en'
    ,getdate()
    ,'test'
    ,1
    ,getdate()
    ,getdate()
    ,1
    ,1
    ); 
SELECT SCOPE_IDENTITY() AS id;
```
This has to be send as one query. ```id``` could be the column name of the primary key.

See: https://msdn.microsoft.com/en-gb/en-en/library/ms190315%28v=sql.120%29.aspx
"Returns the last identity value inserted into an identity column in the same scope. A scope is a module: a stored procedure, trigger, function, or batch. Therefore, two statements are in the same scope if they are in the same stored procedure, function, or batch."
It works fine, without the case if a GUID is used as primary key.

**Comment by dakota** [comment]
Would that work for a composite PK where one column is a identity column? In fact, is that even possible in Sql Server?

**Comment by stmeyer** [comment]
```sql
CREATE TABLE [dbo].[compositePK](
	[col1] [int] IDENTITY(1,1) NOT NULL,
	[col2] [int] NOT NULL,
	[col3] [int] NOT NULL,
 CONSTRAINT [PK_Table_2] PRIMARY KEY CLUSTERED 
(
	[col1] ASC,
	[col2] ASC
)
GO

INSERT INTO [dbo].[compositePK]
           ([col2]
           ,[col3])
     VALUES
           (1
           ,2)
SELECT SCOPE_IDENTITY() AS col1;
-- col1 = 1
INSERT INTO [dbo].[compositePK]
           ([col2]
           ,[col3])
     VALUES
           (1
           ,2)
SELECT SCOPE_IDENTITY() AS col1;
-- col1 = 2
```

**Comment by lorenzo** [comment]
So you need a different query for each of the columns in the key?

**Comment by stmeyer** [comment]
I think it will be one query with 2 statements in it. In SQL Server you can only have one identity column per talbe. https://msdn.microsoft.com/en-us/library/ms174979.aspx says: "Only one identity column can be created per table."

**Comment by stmeyer** [comment]
SqlSrv has also suport for the lastInsertId-Method: https://msdn.microsoft.com/en-us/library/ff628155%28v=sql.105%29.aspx

Sorry, I will be out of office for some weeks.

**Comment by stmeyer** [comment]
Is there a reason, why you are not using lastInsertId-Method with MS SQL Server? If it works with e.g. MySQL it should work with MS SQL Sever, too.

**Comment by markstory** [comment]
We used to use lastInsertID, however it had issues in server setups with high concurrency and lower transaction isolation levels. See #5104

**Comment by stmeyer** [comment]
I'm able to generate the following query now
```sql
DECLARE @tmptalbe TABLE (
	[id] INTEGER IDENTITY(1, 1)
	,[firstname] NVARCHAR(100) NOT NULL
	,[surname] NVARCHAR(100) NOT NULL
	,[username] NVARCHAR(100) NOT NULL
	);

INSERT INTO [dbo].[users] (
	[firstname]
	,[surname]
	,[username]
	)
OUTPUT INSERTED.*
INTO @tmptalbe
```
The code is
```php
protected function _buildInsertPart($parts, $query, $generator)
{
    $table = $parts[0];
    list(,$tableWithoutSchema) = explode('.', $table);
    $tableWithoutSchema = str_replace(['[', ']'], '', $tableWithoutSchema);
    $db = $query->connection();
    $driver = $db->driver();
    $dialect = $driver->schemaDialect();
    $collection = $db->schemaCollection();
    $columnNames = [];
    foreach($collection->describe($tableWithoutSchema)->columns() as $columnName) {
        $columnNames[] = $dialect->columnSql($collection->describe($tableWithoutSchema), $columnName);
    }
    $columns = $this->_stringifyExpressions($parts[1], $generator);
    return sprintf('DECLARE @tmptalbe TABLE (%s);INSERT INTO %s (%s) OUTPUT INSERTED.* INTO @tmptalbe', implode(', ', $columnNames), $table, implode(', ', $columns));
}
```
But I was not able to find a way, to remove the primary key ```[id] INTEGER IDENTITY(1, 1)``` from the column, if one exists. Does anyone have a hint for me?

**Comment by lorenzo** [comment]
What about doing something like this? http://stackoverflow.com/a/616130/684965

Some pseudo code:

```sql
SELECT * (INSERT INTO ... OUTPUT) a INTO #My_temp
```

**Comment by stmeyer** [comment]
I have tested it, too:
```sql
IF OBJECT_ID('dbo.testTable', 'U') IS NOT NULL
	DROP TABLE dbo.testTable;

CREATE TABLE [dbo].[testTable] (
	[id] [int] IDENTITY(1, 1) NOT NULL
	,[col1] [varchar](50) NOT NULL
	,[col2] [datetime] NOT NULL
	,[col3] [int] NOT NULL
	) ON [PRIMARY]

SELECT TOP 0 *
INTO #tmp
FROM [dbo].[testTable]

INSERT INTO [dbo].[testTable] (
	[col1]
	,[col2]
	,[col3]
	)
OUTPUT inserted.*
INTO #tmp
VALUES (
	'asdf'
	,getdate()
	,1
	)

DROP TABLE #tmp
```
The identity column is also copied to ```#tmp```, so sql server returns the error ```Error 8101 Severity Level 16 An explicit value for the identity column in table '#tmp' can only be specified when a column list is used and IDENTITY_INSERT is ON.``` I do not find a generall way, to remove the identity column of the ```#tmp```-Table.

**Comment by stmeyer** [comment]
Does anyone have a hint for my last question "But I was not able to find a way, to remove the primary key [id] INTEGER IDENTITY(1, 1) from the column, if one exists. Does anyone have a hint for me?" Or is the solution to complicated?

**Comment by lorenzo** [comment]
I think the solution is very complicated, I'd like to read a bit more about working around this issue to see f there are alternatives that do not involve creating a new table for each insert query made.

**Comment by stmeyer** [comment]
Microsoft is planning to release a new sql server driver in January: https://github.com/Azure/msphpsql/issues/58. Hopefully the issue #5104 will be fixed.
Maybe, it is possible to create a solution like mine in an easier way, but i do not know the internal functions of Cake.

**Comment by djjohnjosephuk** [comment]
Try running this before you run your INSERT statements on the temp table (or any other table where you need to insert ID values)

IF OBJECTPROPERTY(OBJECT_ID('YOUR_TABLE_NAME_HERE'), 'TableHasIdentity') = 1
					SET IDENTITY_INSERT {YOUR_TABLE_NAME_HERE} ON;

-- RUN INSERTS

-- MAKE SURE YOU TURN OFF ONCE DONE
IF OBJECTPROPERTY(OBJECT_ID('YOUR_TABLE_NAME_HERE'), 'TableHasIdentity') = 1
					SET IDENTITY_INSERT {YOUR_TABLE_NAME_HERE} OFF;

**Comment by stmeyer** [comment]
This is still not working:
```sql
IF OBJECT_ID('dbo.testTable', 'U') IS NOT NULL
    DROP TABLE dbo.testTable

CREATE TABLE [dbo].[testTable] (
    [id] [int] IDENTITY(1, 1) NOT NULL
    ,[col1] [varchar](50) NOT NULL
    ,[col2] [datetime] NOT NULL
    ,[col3] [int] NOT NULL
    ) ON [PRIMARY]

SELECT TOP 1 *
INTO #tmp
FROM [dbo].[testTable]


IF OBJECTPROPERTY(OBJECT_ID('#tmp'), 'TableHasIdentity') = 1
SET IDENTITY_INSERT #tmp ON


INSERT INTO [dbo].[testTable] (
    [col1]
    ,[col2]
    ,[col3]
    )
OUTPUT inserted.*
INTO #tmp
VALUES (
    'asdf'
    ,getdate()
    ,1
    )

select * from #tmp

IF OBJECTPROPERTY(OBJECT_ID('#tmp'), 'TableHasIdentity') = 1
SET IDENTITY_INSERT #tmp OFF

DROP TABLE #tmp
```
The same error: ```Error 8101 Severity Level 16 An explicit value for the identity column in table '#tmp' can only be specified when a column list is used and IDENTITY_INSERT is ON. ```

**Comment by lorenzo** [comment]
Maybe we should not create the temporary table with an identity column, just with another column of the same numeric type.

**Comment by stmeyer** [comment]
I tried this with a TSQL variable in https://github.com/cakephp/cakephp/issues/7765#issuecomment-165080240, but I am not able to remove the IDENTITY and as you @lorenzo said, the solution is complicated.

**Comment by lorenzo** [comment]
I mean, if you make a small example where you hardcode the table structure, and the id column is set as just a number and no primary key set for the table, do you think that would work?

**Comment by stmeyer** [comment]
I'm not shure, if we realy speak about the same. But if you do not have a primary key, it should work. For example, if there is a table in the database:
```sql
CREATE TABLE [dbo].[testTable] (
    [id] [int] IDENTITY(1, 1) NOT NULL
    ,[col1] [varchar](50) NOT NULL
    ,[col2] [datetime] NOT NULL
    ,[col3] [int] NOT NULL
    ) ON [PRIMARY]
```
CakePHP can create a INSERT like this. ```@var``` is a variable and will be unset, if the query finished:
```sql
DECLARE @var TABLE (
    [id] [int] NOT NULL
    ,[col1] [varchar](50) NOT NULL
    ,[col2] [datetime] NOT NULL
    ,[col3] [int] NOT NULL
    );

INSERT INTO [dbo].[testTable] (
    [col1]
    ,[col2]
    ,[col3]
    )
OUTPUT inserted.*
INTO @var
VALUES (
    'asdf'
    ,getdate()
    ,1
    )

select * from @var
```
Output example:
```
id          col1                                     col2                    col3
----------- ---------------------------------------- ----------------------- -----------
68          asdf                                     2016-01-05 10:52:39.170 1
```

**Comment by lorenzo** [comment]
yeah, that's what I mean... I don't think it is necessary to add an identity to the `@var` table

**Comment by stmeyer** [comment]
This was my final goal in https://github.com/cakephp/cakephp/issues/7765#issuecomment-165080240 :+1:  The code from my comment is building this statement **with** the INDENTITY:
```php
protected function _buildInsertPart($parts, $query, $generator)
{
    $table = $parts[0];
    list(,$tableWithoutSchema) = explode('.', $table);
    $tableWithoutSchema = str_replace(['[', ']'], '', $tableWithoutSchema);
    $db = $query->connection();
    $driver = $db->driver();
    $dialect = $driver->schemaDialect();
    $collection = $db->schemaCollection();
    $columnNames = [];
    foreach($collection->describe($tableWithoutSchema)->columns() as $columnName) {
        $columnNames[] = $dialect->columnSql($collection->describe($tableWithoutSchema), $columnName);
    }
    $columns = $this->_stringifyExpressions($parts[1], $generator);
    return sprintf('DECLARE @var TABLE (%s);INSERT INTO %s (%s) OUTPUT INSERTED.* INTO @var', implode(', ', $columnNames), $table, implode(', ', $columns));
}
```
I do not know how to remove the IDENTITY and if it is possible to do it easier. Additinally the ```select * from @var``` is missing. Maybe @lorenzo or someone else has an idea?

**Comment by lorenzo** [comment]
I would remove the autoIncrement flag from the column in the schema object

**Comment by lorenzo** [comment]
Also I think that you cannot have more than one statement returned there, per PDO limitations

**Comment by stmeyer** [comment]
Now it is even more complicated, but all identity columns from the table variable should be removed:
```php
    protected function _buildInsertPart($parts, $query, $generator)
    {
        $table = $parts[0];
        $talbeParts = explode('.', $table);
        if (count($talbeParts) > 1) {
            list(,$tableWithoutSchema) = $talbeParts;
        } else {
            $tableWithoutSchema = $parts[0];
        }
        $tableWithoutSchema = str_replace(['[', ']'], '', $tableWithoutSchema);
        $db = $query->connection();
        $driver = $db->driver();
        $dialect = $driver->schemaDialect();
        $collection = $db->schemaCollection();
        $description = $collection->describe($tableWithoutSchema);
        $constraints = $description->constraints();
        foreach ($constraints as $constraintName) {
            $constraint = $description->constraint($constraintName);
            if ($constraint['type'] === \Cake\Database\Schema\Table::CONSTRAINT_PRIMARY) {
                $description->dropConstraint($constraintName);
            }
        }
        $columnNames = [];
        foreach($description->columns() as $columnName) {
            $descriptionOfSingleColumn = $description->column($columnName);
            if (isset($descriptionOfSingleColumn['autoIncrement']) && $descriptionOfSingleColumn['autoIncrement']) {
                $descriptionOfSingleColumn['autoIncrement'] = false;
            }
            $description->addColumn($columnName, $descriptionOfSingleColumn);
            $columnNames[] = $dialect->columnSql($description, $columnName);
        }
        $columns = $this->_stringifyExpressions($parts[1], $generator);
        return sprintf('DECLARE @var TABLE (%s);INSERT INTO %s (%s) OUTPUT INSERTED.* INTO @var', implode(', ', $columnNames), $table, implode(', ', $columns));
    }
```
This generates something like
```sql
DECLARE @var TABLE (
  [id] BIGINT IDENTITY(1, 1), 
  [part_id] BIGINT DEFAULT NULL, 
  [order_id] BIGINT NOT NULL, 
  [serial_no] NVARCHAR(50) NOT NULL, 
  [interim_serial_no] NVARCHAR(50) DEFAULT NULL, 
  [status_id] BIGINT NOT NULL, 
  [parent_device_id] BIGINT DEFAULT NULL, 
  [palette] NVARCHAR(50) DEFAULT NULL, 
  [created] DATETIME NOT NULL, 
  [modified] DATETIME DEFAULT NULL, 
  [created_by_user_id] INTEGER NOT NULL, 
  [modified_by_user_id] INTEGER DEFAULT NULL
); INSERT INTO [devices] (
  [part_id], [order_id], [serial_no], 
  [interim_serial_no], [status_id], 
  [palette], [created], [modified], 
  [created_by_user_id], [modified_by_user_id]
) OUTPUT INSERTED.* INTO @var 
VALUES 
  (
    1, 1, '1234', '1234', 
    1, '123', '2016-01-25 13:58:19', 
    '2016-01-25 13:58:19', 1, 1
  )
```

Now in the last step, i do not know how to add ```;SELECT * FROM @var``` to the end of the statement.

**Comment by stmeyer** [comment]
Any news here?

**Comment by lorenzo** [comment]
No, I don't have access to a SQL Server instance and will be difficult for me to change the code around. You seemed close to getting there... did you figure out how to run the select statement?

**Comment by stmeyer** [comment]
So, i found it:
```php
    /**
     * Generates the INSERT part of a SQL query
     *
     * To better handle concurrency and low transaction isolation levels,
     * we also include an OUTPUT clause so we can ensure we get the inserted
     * row's data back.
     *
     * @param array $parts The parts to build
     * @param \Cake\Database\Query $query The query that is being compiled
     * @param \Cake\Database\ValueBinder $generator the placeholder generator to be used in expressions
     * @return string
     */
    protected function _buildInsertPart($parts, $query, $generator)
    {
        $table = $parts[0];
        $talbeParts = explode('.', $table);
        if (count($talbeParts) > 1) {
            list(,$tableWithoutSchema) = $talbeParts;
        } else {
            $tableWithoutSchema = $parts[0];
        }
        $tableWithoutSchema = str_replace(['[', ']'], '', $tableWithoutSchema);
        $db = $query->connection();
        $driver = $db->driver();
        $dialect = $driver->schemaDialect();
        $collection = $db->schemaCollection();
        $description = $collection->describe($tableWithoutSchema);
        $constraints = $description->constraints();
        foreach ($constraints as $constraintName) {
            $constraint = $description->constraint($constraintName);
            if ($constraint['type'] === \Cake\Database\Schema\Table::CONSTRAINT_PRIMARY) {
                $description->dropConstraint($constraintName);
            }
        }
        $columnNames = [];
        foreach($description->columns() as $columnName) {
            $descriptionOfSingleColumn = $description->column($columnName);
            if (isset($descriptionOfSingleColumn['autoIncrement']) && $descriptionOfSingleColumn['autoIncrement']) {
                $descriptionOfSingleColumn['autoIncrement'] = false;
            }
            $description->addColumn($columnName, $descriptionOfSingleColumn);
            $columnNames[] = $dialect->columnSql($description, $columnName);
        }
        $columns = $this->_stringifyExpressions($parts[1], $generator);
        return sprintf('DECLARE @var TABLE (%s);INSERT INTO %s (%s) OUTPUT INSERTED.* INTO @var', implode(', ', $columnNames), $table, implode(', ', $columns));
    }

    /**
     * Builds the SQL fragment for INSERT INTO.
     *
     * @param array $parts The values parts.
     * @param \Cake\Database\Query $query The query that is being compiled
     * @param \Cake\Database\ValueBinder $generator the placeholder generator to be used in expressions
     * @return string SQL fragment.
     */
    protected function _buildValuesPart($parts, $query, $generator)
    {
        $result = implode('', $this->_stringifyExpressions($parts, $generator)) .
                ';SELECT * FROM @var';
        return $result;
    }
```
this is working fine for me.

**Comment by lorenzo** [comment]
@stmeyer That's great news!

We could add that to another compiler class and inside the driver we could detect if replication is enabled. Depending on replication we can select one compiler or the other. What do you think?

**Comment by lorenzo** [comment]
@stmeyer Also, since we only need the primary key column of the table, we could spare creating a temporary table with all the columns and inserting all values. I guess that would make it a bit faster

**Comment by stmeyer** [comment]
@lorenzo Writing a different compilier sounds good to me. With the following SQL one can check if there are enabled trigger on a table:
```sql
SELECT count(*) as QuantityOfTriggers
FROM sys.triggers tr
INNER JOIN sys.tables t ON tr.parent_id = t.object_id
WHERE t.schema_id = SCHEMA_ID('dbo') 
and t.name = 'WorkOrder'
and tr.is_disabled = 0
```
Additionally I changed the method, so that only the primary key columns are added to the variable:
```php
    /**
     * Generates the INSERT part of a SQL query
     *
     * To better handle concurrency and low transaction isolation levels,
     * we also include an OUTPUT clause so we can ensure we get the inserted
     * row's data back.
     *
     * @param array $parts The parts to build
     * @param \Cake\Database\Query $query The query that is being compiled
     * @param \Cake\Database\ValueBinder $generator the placeholder generator to be used in expressions
     * @return string
     */
    protected function _buildInsertPart($parts, $query, $generator)
    {
        $table = $parts[0];
        $talbeParts = explode('.', $table);
        if (count($talbeParts) > 1) {
            list(,$tableWithoutSchema) = $talbeParts;
        } else {
            $tableWithoutSchema = $parts[0];
        }
        $tableWithoutSchema = str_replace(['[', ']'], '', $tableWithoutSchema);
        $db = $query->connection();
        $driver = $db->driver();
        $dialect = $driver->schemaDialect();
        $collection = $db->schemaCollection();
        $description = $collection->describe($tableWithoutSchema);
        $constraints = $description->constraints();
        $primaryKeyColumns = [];
        foreach ($constraints as $constraintName) {
            $constraint = $description->constraint($constraintName);
            if ($constraint['type'] === \Cake\Database\Schema\Table::CONSTRAINT_PRIMARY) {
                $primaryKeyColumns = $constraint['columns'];
                $description->dropConstraint($constraintName);
            }
        }
        $sqlCreateColumns = [];
        $primaryKeyColumnsForSql = [];
        foreach($description->columns() as $columnName) {
            if (in_array($columnName, $primaryKeyColumns)) {
                $descriptionOfSingleColumn = $description->column($columnName);
                if (isset($descriptionOfSingleColumn['autoIncrement']) && $descriptionOfSingleColumn['autoIncrement']) {
                    $descriptionOfSingleColumn['autoIncrement'] = false;
                }
                $description->addColumn($columnName, $descriptionOfSingleColumn);
                $sqlCreateColumns[] = $dialect->columnSql($description, $columnName);
                $primaryKeyColumnsForSql[] = $columnName;
            }
        }
        $columns = $this->_stringifyExpressions($parts[1], $generator);
        return sprintf('DECLARE @var TABLE (%s);INSERT INTO %s (%s) OUTPUT INSERTED.%s INTO @var', implode(', ', $sqlCreateColumns), $table, implode(', ', $columns), implode(' , INSERTED.', $primaryKeyColumnsForSql));
    }

    /**
     * Builds the SQL fragment for INSERT INTO.
     *
     * @param array $parts The values parts.
     * @param \Cake\Database\Query $query The query that is being compiled
     * @param \Cake\Database\ValueBinder $generator the placeholder generator to be used in expressions
     * @return string SQL fragment.
     */
    protected function _buildValuesPart($parts, $query, $generator)
    {
        $result = implode('', $this->_stringifyExpressions($parts, $generator)) .
                ';SELECT * FROM @var';
        return $result;
    }
```

**Comment by stmeyer** [comment]
Instead of checking by query if there are enabled triggers to one table, it could be an option to make the compiler configurable. If no compiler is configurated, the standard compiler `\Cake\Database\SqlserverCompiler` is used. If the `\config\app.php` one can insert somethink like:
```php
<?php
return [
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Sqlserver',
            'compiler' => 'Cake\Database\SqlserverWithTriggerCompiler'
            ...
        ],
]
```
This should be faster than allways running the query, to check, if there are enabled triggers on the table.

**Comment by jadb** [comment]
Closing, PR #8263 now opened.
