### ISSUE TITLE
Line feeds in log message results in multiple Syslog messages

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#7768]
Line feeds in message will create multiple Syslog messages. Those Syslog messages are very difficult to process, because they contain only parts of the full message.

The message is split on new lines in the Syslog engine. See: https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Log/Engine/SyslogLog.php#L117

Do you have any idea why it is done this way?

**Comment by lorenzo** [comment]
Because syslog has a limit on the line lenght

**Comment by mvdriel** [comment]
Thanks. The default maximum message size of syslog is 1k. It is probably better to truncate (or split) when this limit is reached instead of always creating lots of unusable messages.

**Comment by tersmitten** [comment]
@lorenzo Are you open to making the split behavior configurable?

Parsing a multi lines exception seems really tedious. I rather have the first 2097 characters. Do you have any recommendations?

**Comment by lorenzo** [comment]
It cannot exceed 1k, so I would accept any pull request for splitting the line at the length.

@teramitten it would be easier if you use your own logger and override the splitting function

**Comment by tersmitten** [comment]
Thanks for the suggestion. We will try that.

**Comment by markstory** [comment]
Truncation seems pretty terrible to me. Logs can be critical data for some apps and throwing the data away when there is an easy way to keep it seems severe.
