### ISSUE TITLE
re-execute query

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7770]
Not sure if this is the desired behavior but I didn't find something in the docs about the issue.

The following example will end in an endless loop:

```php
        $this->loadModel('Variations');
        $query = $this->Variations->find()
            ->contain(['Products', 'Crawlers'])
            ->limit(100);

        $page = 1;
        while($variations = $query->page($page)->toArray()) {
            $page++;
        }
```

**Comment by steefaan** [comment]
I tested it again I can not imagine that this is the desired behavior. If I debug the query in the loop, the offset is correct but the result of the query is always the same.

**Comment by ADmad** [comment]
Changing query after it has executed won't do anything. You need to clone it to get a new query object preserving the previous query and then modify it as required.

**Comment by lorenzo** [comment]
Hmm, we actually do support modifying the query in some cases. Although it is usually discouraged. I'll take a look at this case

**Comment by ADmad** [comment]
Okay, will reopen the issue in that case.
