### ISSUE TITLE
3.0 - Weird Entity comportement

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7774]
Setting a `setter` and a `getter` for the `same` field result that the `setter` doesn't work.

```php
class UsersTfa extends Entity
{
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];

    /**
     * Encrypt the secret key.
     *
     * @param string $secret The secret key to be encrypted.
     *
     * @return string
     */
    protected function _setSecret($secret)
    {
        return base64_encode(Security::encrypt($secret, Configure::read('Security.key')));
    }

    /**
     * Decrypt the secret key.
     *
     * @param string $secret The secret key to be decrypted.
     *
     * @return string
     */
    protected function _getSecret($secret)
    {
        return Security::decrypt(base64_decode($secret), Configure::read('Security.key'));
    }
}
```

```php
$data = [
    'user_id' => $this->Auth->user('id'),
    'secret' => $secret, //NOT encrypted
    'username' => $user->username
];
$entity = $this->UsersTfa->newEntity($data);
debug($entity); // The "secret" IS encrypted here.
$this->UsersTfa->save($entity);
```

But in the database the secret ISN'T encrypted.

The behavior expected was that the `secret` should be encrypted in the database, and when i use `$userTfa->secret` it should be decrypted. Is that a bug or... i must use a getter with a different name ?

For information, if i comment the getter, the setter work well again and the data is encrypted in the database.

**Comment by dakota** [comment]
Getters are intentionally used by the ORM when persisting the data. You'll need to use a different named getter to do what you are trying to do.

**Comment by lorenzo** [comment]
The entity is not really the best place for doing this type of work. The current behavior was made to actually discourage doing it. Please use a custom database type for this.

There is an example for a json custom type. here http://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-types

You can use that example to build a EncryptedStringType or similar.

**Comment by Xety** [comment]
Oh, i didn't know about that, it will help me alot since i'm encrypting a lot of data in my database.

Thanks @lorenzo.
