### ISSUE TITLE
3.1 - Using CounterCache and other Behaviors together

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7777]
Hello. I have a Behavior that switches the connection between a master/slave on beforeSave (change to master) and beforeFind (change back to slave). I'm also using CounterCache on a table at the same time. `CounterCache::_processAssociation` calls `$assoc->target()->updateAll` which, as stated in the docblock, doesn't call any `Model.beforeSave` events. Since it's not getting called, my M/S Behavior isn't changing the connection on its associated Table, which also has the behavior. Is it possible to update the `CounterCache` behavior to use a save method other than `updateAll` so hooks in other behaviors can be used?
To get around this, I've tried to get my `beforeSave` to loop through the associations and update their connections, but it doesn't seem to work. This is the basic M/S logic:

```
public function __construct(Table $table, array $config = [])
{
    $this->_table = $table;
    $tableConnectionName = $table->connection()->config()['name'];
    $connectionConfig = ConnectionManager::config($tableConnectionName);
    $hosts = isset($connectionConfig['hosts']) ? $connectionConfig['hosts'] : [];
    if (empty($hosts) || !isset($hosts['master']) || !isset($hosts['slave'])) {
        return false;
    }
    unset($connectionConfig['hosts']);

    $masterName = sprintf('%s_master', $tableConnectionName);
    $slaveName = sprintf('%s_slave', $tableConnectionName);

    if (ConnectionManager::config($slaveName) === null) {
        ConnectionManager::config(
            $slaveName,
            $hosts['slave'] + $connectionConfig
        );
    }
    if (ConnectionManager::config($masterName) === null) {
        ConnectionManager::config(
            $masterName,
            $hosts['master'] + $connectionConfig
        );
    }

    $config['connections']['master'] = ConnectionManager::get($masterName);
    $config['connections']['slave'] = ConnectionManager::get($slaveName);
    parent::__construct($table, $config);

    if ($this->config('connections.master') === null || $this->config('connections.slave') === null) {
        throw new \Exception(sprintf("Master or slave not found in conenction config for %s.", $tableConnectionName));
    }

    $this->_table->connection($this->config('connections.slave'));
}
public function beforeSave(Event $event, Entity $entity, ArrayObject $options)
{
    if ($this->config('connections.master') !== null) {
        $this->_table->connection($this->config('connections.master'));
    }
}
public function beforeFind(Event $event, Query $query, ArrayObject $options, $primary)
{
    if ($this->config('connections.slave') !== null) {
        $this->_table->connection($this->config('connections.slave'));
    }
}
```

**Comment by patrickconroy** [comment]
Assuming this is a change that people are ok with, would changing it to this be ok? Or there a simpler way?

This:
```
$assoc->target()->updateAll([$field => $count], $updateConditions);
```
Becomes:
```
$entity = $assoc->target()
    ->get($updateConditions)
    ->set($field, $count);
$assoc->target()->save($entity);
```

And
```
$assoc->target()->updateAll([$field => $count], $updateOriginalConditions);
```

Becomes:
```
$entity = $assoc->target()
    ->get($updateOriginalConditions)
    ->set($field, $count);
$assoc->target()->save($entity);
```

**Comment by markstory** [comment]
One reason we went with updateAll() originally was it emits fewer queries than loading up entities. I also have concerns that `get()` will not work because association conditions can include more than just the primary key. I think you would have to use find() proper.

**Comment by patrickconroy** [comment]
Thanks @markstory. Do you think I should make a PR with that change? Or am I trying to do something I shouldn't? Changing the connection before things happen is the only way I could think to do this.. is there some other event I should be listening for maybe?

**Comment by markstory** [comment]
I don't think there is another event that would be better. Using `find()` would be preferrable to `get()` for the reasons I mentioned earlier like association conditions.

While `find()` seems reasonable on the surface, I suspect there may be edge cases where find() + save() + other callbacks + CounterCache can lead to infinite loops, which the current updateAll() implementation can never encounter.

**Comment by dereuromark** [comment]
Also, updateAll() is an atomic operation. whereas with find() + save() and without transaction support this can lead to wrong data being persisted.
