### ISSUE TITLE
3.x - Plugins configuration file conflicts with composer install

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#7778]
This *might* be an issue with https://github.com/cakephp/plugin-installer instead of the framework. If it is I'll put an issue in over there.

I moved the section that loads plugins out of the `config/bootstrap.php` and moved them into `config/plugins.php`. When I run `composer install` something funny happens. The contents from `config/plugins.php` appears in `vendor/cakephp-plugins.php` throwing a fatal error that `Cake\Core\Plugin` was not found.

This only happens when I have a file named `plugins.php` in the config directory of my application.

**Comment by sdustinh** [comment]
Ah, I might have jumped the gun on this issue.

https://github.com/cakephp/plugin-installer/blob/master/src/Installer/PluginInstaller.php#L400-L441

I assume this is BC/expected behavior so this is probably a non-issue.

**Comment by markstory** [comment]
It is a compatibility feature for the early RC versions of 3.x
