### ISSUE TITLE
Support for systems with read only session ini configuration

### ISSUE THREAD

**Issue by sedninja** [cakephp/cakephp#7779]
It seems that the latest `Cake\Network\Session` object fails to load if CakePHP is unable to set certain values in the PHP ini, even if the value is already set in a read only fashion. Specifically the default Session is configured with `session.cookie_secure` and `session.cookie_httponly` being set to true which will fail if php is unable to modify the configuration for these values as would be the case if the server is configured using php-fpms `php_admin_value` syntax. It would be better IMO if the value of these settings was checked prior to the attempt to update them.

**Comment by markstory** [comment]
Pull request merged.
