### ISSUE TITLE
Error: Transport config “Smtp” is missing in cakephp 3.x

### ISSUE THREAD

**Issue by bkhushang** [cakephp/cakephp#7781]
Transport config "Smtp" is missing in cakephp 3.x

I have tried some of the configuration which are as follows:

    'EmailTransport' => [
        'default' => [
            'className' => 'Smtp',
            'host' => 'ssl://smtp.gmail.com',
            'port' => 465,
            'username' => 'xxxxxxxxx@gmail.com',
            'password' => 'xxxxx',
        ],
    ],
    
    'Email' => [
        'default' => [
            'from' => array('site@localhost' => 'Data Mining'),
            'transport' => 'Smtp',
            'charset' => 'utf-8',
            'headerCharset' => 'utf-8',           
        ],
    ],

And i have used below code to send email.

    $mail = new Email('default');

    $mail->emailFormat('html');
    $mail->template($template, null)->viewVars(array('body' => $mailBody));
    $mail->to($email_to);
    $mail->subject($subject);
    $mail->replyTo(Configure::read('config.NOREPLY_EMAIL'));
    
    $headers = array(
        'X-MC-MergeVars' => '{"NAME": "Khushang", "REGARDS":"Khushang"}',
        'X-MC-Template' => 'test-by-Khushang'
    );
    
    $mail->setHeaders($headers);
    $mail->send();

Thank you so much...

**Comment by ADmad** [comment]
You have set `'transport' => 'Smtp'` in your email config but your `EmailTransport` does not have any config named `Smtp`. It only has `default` transport config so change `'transport' => 'Smtp'` to ``'transport' => 'default'`.
