### ISSUE TITLE
3.2 "The CsrfComponent now supports an httpOnly option." should be default

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7783]
From the 3.1.5 notes: “The CsrfComponent now supports an httpOnly option. Enabling this option makes the CSRF cookie inaccessible to client side scripting”

Should this be the default for 3.2?

**Comment by lorenzo** [comment]
No, having access to the cookie is quite handy in scripts. In fact one of the cookie's main purposes is so it can be read using javascript

**Comment by markstory** [comment]
Also changing the defaults could break existing client side scripting.

**Comment by jhli** [comment]
That's the reason I was requesting it for 3.2 - 4.0 would be okay, too.

Doesn't this improve default security?

**Comment by ADmad** [comment]
3.x needs to maintain backwards compatibility, so it's out of question changing it for 3.2.

I wouldn't change it for 4.0 either. As @lorenzo said cookie's main purposes is so it can be read using javascript. That allows js code to get the csrf token and add the `X-CSRF-Token` to ajax requests.

**Comment by ionas** [comment]
I cannot grasp the security implications of allowing those modifications, yet.

For those having a better understanding, just as a reference @ CakePHP4 future:
Rails4 (and Rails3) sets it as a meta tag (meta name="csrf-token") which can then be read/updated by javascript if required. http://stackoverflow.com/questions/7203304/warning-cant-verify-csrf-token-authenticity-rails

**Comment by markstory** [comment]
I can't think of a way that a meta tag is better than a cookie.

**Comment by ionas** [comment]
@markstory That's another issue than the original opening post and I am sorry for bringing it up here (What about authenticating via HTTP/stateless/in other ways and disabling cookies?).

**Comment by markstory** [comment]
The current cookie based implementation is stateless. I don't have a good grasp of why the cookies are an issue that requires fixing, any further detail you can provide there?
