### ISSUE TITLE
hasOne marshalling null value = Passed variable is not an array or object, using empty array instead

### ISSUE THREAD

**Issue by ifunk** [cakephp/cakephp#7786]
I am using patchEntity to update a deeply nested entity, but running into issues when trying to "remove" a hasOne object from an entity.

Here's a simple example.

```
class UsersTable extends Table
{
    public function initialize(array $config)
    {
        $this->hasOne('Addresses');
    }
}
```

```
object(App\Model\Entity\User) {
    'id' => (int) 1,
    'name' => 'Dummy user',
    'address' => object(App\Model\Entity\Address) {
        'id' => (int) 2,
        'user_id' => (int) 1,
        'street' => '56 Cake St'
        '[new]' => false,
        '[accessible]' => [
            '*' => true
        ],
        '[dirty]' => [],
        '[original]' => [],
        '[virtual]' => [],
        '[errors]' => [],
        '[repository]' => 'Addresses'
    },
    '[new]' => false,
    '[accessible]' => [
        '*' => true
    ],
    '[dirty]' => [],
    '[original]' => [],
    '[virtual]' => [],
    '[errors]' => [],
    '[repository]' => 'Users'
}
```

I have tried the following, all of which give the error `Passed variable is not an array or object, using empty array instead`.

```
$this->Users->patchEntity($user, ['address' => null], ['associated' => ['Addresses']);
```

```
$this->Users->patchEntity($user, ['address' => ''], ['associated' => ['Addresses']);
```

```
$this->Users->patchEntity($user, ['address' => false], ['associated' => ['Addresses']);
```

However when I pass an empty array, it is merged into the address (ie no-op) and the address remains.

One dodgy workaround is merging in a magic variable like this, and delete it later in a beforeSave handler, however this feels pretty gross.

```
public function beforeMarshal(\Cake\Event\Event $event, \ArrayObject $data, \ArrayObject $options)
{
    if (array_key_exists('address', $data) && !$data['address']) {
        $data['address'] = ['delete_me' => 1];
    }
}
```

Alternatively, can Marshaller be amended to handle null or empty string properties?

**Comment by markstory** [comment]
When you're detaching the Address, should the address be deleted or just detached?

**Comment by ifunk** [comment]
I think for a HasOne it should be deleted by default, but have an option to override.

**Comment by ifunk** [comment]
However this behaviour should be consistent with HasMany relationships.

**Comment by lorenzo** [comment]
Should that be controller by `dependent => true` ?

**Comment by ADmad** [comment]
Being controlled by 'dependent' sounds good

**Comment by ifunk** [comment]
:+1:
