### ISSUE TITLE
Add Session Cookie HttpOnly feature

### ISSUE THREAD

**Issue by ukkpower** [cakephp/cakephp#7788]
Could I ask that a future update include allowing HttpOnly flag for Session Cookies.

Any cookies that are created with the `httponly` attribute will not be present in JavaScript's `document.cookie` variable on browsers where HttpOnly is supported. Browsers will still send HttpOnly cookies when making AJAX calls or XMLHttpRequest calls, however their values still cannot be accessed from your JavaScript code.

Thanks

**Comment by ADmad** [comment]
You can already do that by using `session.cookie_httponly`  ini flag for session config in [app.php](https://github.com/cakephp/app/blob/master/config/app.default.php#L311).

**Comment by ADmad** [comment]
[httponly](https://github.com/cakephp/cakephp/blob/master/src/Network/Session.php#L115) flag is already enabled by default.
