### ISSUE TITLE
[2.8] creat new record with HABTM

### ISSUE THREAD

**Issue by rifton007** [cakephp/cakephp#7792]
Hello everyone,

Is it possible to create a new recording with HABTM relationships?
For example, a new post with new or old tags?

Thanks for your help.

**Comment by rifton007** [comment]
I did several tests, it is possible.
But only the first letter of the key is capitalized.

it works with this table.
```php
array('Post' => array('content' => 'blablabla'),
                                'Tag' => array('Tag' => array('1', '2' ,'3'))
                               );
```
But not with this table.
```php
array('post' => array('content' => 'blablabla'),
                                'tag' => array('tag' => array('1', '2' ,'3'))
                               );
```

So to correct the problem I do:
```php
<?= $this->Form->create('Post', array('action' => 'newPost')) ?>
```
But by doing this, it's validation that no longer works.
What can I do ?
Thx,

**Comment by markstory** [comment]
Association names should be Capitalized as the post data needs to match the datastructure that find() returns.

What is not working with validation?

**Comment by rifton007** [comment]
Thank you Marksotry,

With this version validation works, but not saving links. Only the post is save.
```php
 <?= $this->Form->input('tag.tag', array('label' => 'Tag', 'multiple' => 'multiple' , 'required' => false)) ?> //view of post
$this->Store->Tag->set($data['tag']); //controller post
```
But with this version works HABTM.
But not validation, $this->validationErrors return "empty"
```php
 <?= $this->Form->input('Tag.Tag', array('label' => 'Tag', 'multiple' => 'multiple' , 'required' => false)) ?> //view of post
$this->Store->Tag->set($data['Tag']); //controller post
```

**Comment by markstory** [comment]
Normally you wouldn't set the list of ids to the Tag model as that data can't be persisted.

**Comment by rifton007** [comment]
Yes I agree.
But the problem is not backup, but validation.
My current release,
```php
//view
$this->Form->create('Post', array('action' => 'newpost')); //capital letter
$this->Form->input('content', array('label' => false));
$this->Form->input('Tag.Tag', array('label' => 'Tag', 'multiple' => 'multiple')) //capital letter

//controller
if ($this->request->is('post')) {

    if (!empty($this->request->data)){

        $data = $this->request->data;
        $this->Post->set($data['Post']); //capital letter   
        $this->Post->Tag->set($data['Tag']); //capital letter

    if($this->Post->validates() && $this->Post->Tag->validates()){
            debug('validation ok');
                } else {debug('validation not ok');}

    $this->Post->create();
    $this->Post->save($data, array('validate' => false));
}
```
Here no backup problem.
But validation is not working, why?
if I go back to lowercase, the validation will work.

The convention in cakephp, is?

```php
$this->Form->create('Post', array('action' => 'newpost')); //capital letter
//OR
$this->Form->create('post', array('action' => 'newpost')); //lowercase letter
```

Thanks you Markstory,

**Comment by markstory** [comment]
I don't know what your validation rules are, or how they would apply to a list of ids.

**Comment by sebastienbarre** [comment]
Something I've been struggling with as well. Saving HABTM works, but validation errors just don't get propagated properly for some reasons. @rifton007, did you ever solve this?

**Comment by sebastienbarre** [comment]
I'm referring to 2.8.2 above. I'm looking at `Model/Model.php` and `Model/ModelValidator.php`, and it is unclear how validations errors are propagated. `ModelValidator::_validateWithModels()` does go down the HABTM chain, trigger the validation rules, but I don't see where the error messages are being propagated up...

**Comment by sebastienbarre** [comment]
BTW I've:
```
          'validate' => 'first',
          'deep' => true,
          'atomic' => false,
```
In that context, if you look at [`saveAssociated` line 2453](https://github.com/cakephp/cakephp/blob/2.8.3/lib/Cake/Model/Model.php#L2453), it seems that any error triggers a return, and the `try` block below is never hit; it seems though that this is the block that affects all the `validationErrors`.
