### ISSUE TITLE
Postgres SQL allows from in update

### ISSUE THREAD

**Issue by stevetauber** [cakephp/cakephp#7801]
[Per documentation](http://www.postgresql.org/docs/current/static/sql-update.html), a from clause can be included in a postgres update:

```
UPDATE employees SET sales_count = sales_count + 1 FROM accounts
WHERE accounts.name = 'Acme Corporation'
AND employees.id = accounts.sales_person;
```

This isn't supported by cakephp because updateParts doesn't allow it: 
vendor/cakephp/cakephp/src/Database/QueryCompiler.php:59

```
protected $_updateParts = ['update', 'set', 'where', 'epilog'];
```

What's the best way to go about fixing this?

**Comment by lorenzo** [comment]
Currently the `from` part is reserved for the main table to update. We would need to add another method in order to support this. If you'd like to implement it, I can help you

**Comment by stevetauber** [comment]
After manually patching that line to include 'from' my query was successful:

            //In EmployeesTable.php
            $query = $this->query();
            $conditions = [
                'Accounts.name' => 'Acme Corporation',
                'Employees.id' => 'accounts.sales_person'
            ];
            $query->update()
            ->set(['sales_count' => 'sales_count + 1'])
            ->from('accounts')
            ->where($conditions)
            ->execute();

Adding the from is VERY intuitive based on psql. Could you explain what you mean by adding another method?

**Comment by lorenzo** [comment]
Well, the minimum thing we could do is having a different QueryCompiler for Postgres, since I don't think the other databases work the same

**Comment by stevetauber** [comment]
I think that is a very valid solution. I checked MySQL and it does not support this. I did not check MSSql however.

Also, I wanted to note that I don't consider this an Enhancement because it is functionality that is missing and should be corrected.

**Comment by lorenzo** [comment]
Functionality that is missing and then added is called an enhancement :D

There is little value in discussing the category this falls in, though

**Comment by markstory** [comment]
The `FROM` clause in postgres is ~= to joins in an update statement. This feature was intentionally not implemented, as there is no vendor agnostic way to implement updates with joins. Each vendor that does support it requires wildly different syntax. My concern with adding support to postgres, will then require adding support for the mysql flavor.

If you need this behavior now, it would be simplest to use a [prepared statement](http://book.cakephp.org/3.0/en/orm/database-basics.html#preparing-a-statement).
