### ISSUE TITLE
Character encoding exception on Query

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7805]
I parse json data from curl. Usually I have no problems, but today I had to parse the following string:
`ﾅｲｷ ｳｨﾒﾝｽﾞ ｴｱ ｽﾞｰﾑ ﾍﾟｶﾞｻｽ`
I have everything set to use UTF-8 (So I guess this is in a different encoding)

Anyway the problem is that when I try to save my Entity, using the default Save() method, I get the following PDOException:
`SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xEF\xBE\x85\xEF\xBD\xB2...' for column 'name' at row 1`
Is this normal? I was under the impression that I can pass any value to Save() and CakePHP will filter it out for me. :(
![screen shot 2015-12-07 at 12 15 47](https://cloud.githubusercontent.com/assets/6759894/11625587/4e12c2d6-9cdc-11e5-84ad-8f37a6c5039d.png)
My structure that I'm making an entity out of: 
![screen shot 2015-12-07 at 12 23 52](https://cloud.githubusercontent.com/assets/6759894/11625745/8b353be8-9cdd-11e5-9076-98e5e8abc16c.png)
![screen shot 2015-12-07 at 12 12 57](https://cloud.githubusercontent.com/assets/6759894/11625523/e5e7cd78-9cdb-11e5-98f3-e978a59e7636.png)
![screen shot 2015-12-07 at 12 12 11](https://cloud.githubusercontent.com/assets/6759894/11625508/c70a507e-9cdb-11e5-9b7e-76afa75cf4dd.png)

**Comment by lorenzo** [comment]
This is usually a problem in how you have created/configured your table and columns in mysql.

- First make sure that you have the right encoding configuration set for the connection in `app.php`
- Second, make sure the encoding for the table is correct
- Third you need to make sure that the columns in your table are also in the right encoding
- Finally, you actually need to provide data in the right encoding. Try converting the string to utf-8 before saving it (use utf8_encode)

CakePHP will no do encoding conversion for you, since that would not be transparent for the user. In fact we would risk losing data

**Comment by half2me** [comment]
@lorenzo You are absolutely right! Turns out my test database was using LATIN encoding :) Switched to UTF8, and everything is working fine! Thank you!

**Comment by lorenzo** [comment]
:100: great!

**Comment by ionas** [comment]
@half2me Going over http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration it might be great that you add what you learned to the book so that the issue does not come up/hit other users in future.

**Comment by half2me** [comment]
@lonas I'd be glad to, but my problem was not in my configuration of the Framework, but the default Char encoding of my MySQL server being LATIN, and me not specifying explicitly to use UTF-8 when creating the database. I modified the `src/Shell/Installer.php` to automatically create the needed database and create the tables needed for my app when installing with composer. It saves me lots of time, because I don't need to configure the `app.php` file every time I do an install on a new system, I just do a composer install. And in my script, I forgot to add UTF-8 on the `CREATE DATABASE` statement.

**Comment by ionas** [comment]
A hint in the docs may help others. Sadly MySQL (afaik) still sets latin1 as a default often.
