### ISSUE TITLE
3.1.x SoftDelete as part of ORM

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#7812]
Hello, guys!
Are you planning to make SoftDelete as part of ORM in future releases of framework?

**Comment by dereuromark** [comment]
I don't think it has to be. Most of these things are perfectly fine as community driven plugin solutions.
So why would you want that to go into the core?

**Comment by codercms** [comment]
I think this future is very usefull in many projects. And comunity plugins may be out dated if ORM arch will be changed. For example in most of popular PHP frameworks this feature is implemented.

**Comment by markstory** [comment]
Is the reason you want a core provided implementation primarily because the community plugins are not maintained, and you expect that a core behavior will be better maintained?

**Comment by codercms** [comment]
Yes, i think. And i think too - the soft delete is primary part of modern web apps. And if CakePHP will support this feature it would be really great :+1:

**Comment by josegonzalez** [comment]
[Here](https://github.com/usemuffin/trash) is a well-maintained version for CakePHP 3.

**Comment by dereuromark** [comment]
Someone should add this to https://github.com/FriendsOfCake/awesome-cakephp and we can close this.
In general, there must be more than the risk of oudating to warrant core integration. Otherwise the community has the responsibility of keeping those things up to date. Everyone can help do that.

**Comment by ADmad** [comment]
@dereuromark What's "this"?  `Muffin/Trash` is already on the awesome list.

**Comment by dereuromark** [comment]
Hah, was looking for "SoftDelete" ;) My bad.

**Comment by ADmad** [comment]
> Soft-delete behavior for CakePHP

I ain't gonna bother putting in every combination of "soft" and "delete" :)

**Comment by codercms** [comment]
Currently this plugin is best for soft-deleting, but there is not behavior, there is trait - https://github.com/PGBI/cakephp3-soft-delete

**Comment by dakota** [comment]
@codercms Actually that plugin is probably the worst implementation you can find.

https://github.com/usemuffin/trash is a million times better and is actively maintained by some of the CakePHP core developers. It works as a behaviour and is actually tested and testable.

**Comment by dereuromark** [comment]
Closing as the discussion has to be continued somewhere else now.

**Comment by bravo-kernel** [comment]
:bulb:
