### ISSUE TITLE
3.0 - Use `LOGS` constance as default value for `path` in FileLog Engine

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7822]
https://github.com/cakephp/cakephp/blob/master/src/Log/Engine/FileLog.php#L47
```php
'path' => LOGS
```

I think it's better to have this as default value, since (i think) we are all using the `logs` directory with the `FileLog` engine. It will be more DRY for people like me who use several logs configuration. :stuck_out_tongue_closed_eyes:

**Comment by markstory** [comment]
The `LOGS` constant isn't defined in cakephp. We can't use constants that don't exist.

**Comment by Xety** [comment]
Hmm, https://github.com/cakephp/app/blob/master/config/paths.php#L67
