### ISSUE TITLE
Should QueryTrait check that the entity being returned in FirstOrFail is of type Entity?

### ISSUE THREAD

**Issue by voycey** [cakephp/cakephp#7823]
https://github.com/cakephp/cakephp/blob/master/src/Datasource/QueryTrait.php#L407

I'm using the ORM with a custom datasource that in this case returns the object as an array, it quite happily returns this as an array:

```$contact = $this->SalesforceContact->get('0039000001UmfFO');```

If it is expecting an Entity on Line 407 should it cast /convert it to an Entity (Or fail if not)?

**Comment by markstory** [comment]
Requiring an entity or casting would break `$query->hydrate(false)->first()` though.

**Comment by voycey** [comment]
No problem then - I didn't think having Array results was a thing for the ORM anymore?

**Comment by markstory** [comment]
They totally are if you use `->hydrate(false)`.
