### ISSUE TITLE
3.1 route prefix CamelCase name

### ISSUE THREAD

**Issue by chipco** [cakephp/cakephp#7824]
The [docs](http://book.cakephp.org/3.0/en/development/routing.html#prefix-routing) describe routing for prefixes formed of one word. How can I use a multi-word prefix, like `SmartControl`?

In routes:
```php
Router::prefix('smartcontrol', function ($routes) {
	$routes->fallbacks('DashedRoute');
});
```
Creating a link:
```php
$this->Html->link(__('Real Time'), [
	'prefix' => 'smartcontrol',
	'controller' => 'RealTime',
	'action' => 'index',
	'plugin' => false
]);
```
results in: `src/Controller/Smartcontrol/RealTimeController.php`.

Note what happens for the controller `RealTime`. I want the same functionality for the prefix, `SmartControl` instead of `Smartcontrol`.

On windwos it works with `src/Controller/SmartControl/RealTimeController.php` since it's case insensitive, but on linux it doesn't.

**Comment by chipco** [comment]
Somewhere else in the [dosc](http://book.cakephp.org/3.0/en/intro/conventions.html#url-considerations-for-controller-names) it's suggested to use CamelCase for prefix names but if I try to get a link with `'prefix' => 'SmartControl'` I get a missing route error.

**Comment by markstory** [comment]
You can use

``php
Router::prefix('SmartControl', function ($routes) {
  // define routes here.
});
```

This enables routes like `/smart_control/bookmarks/view/1`. You can generate routes for this prefix using:

```php
        debug(\Cake\Routing\Router::url([
            'prefix' => 'smart_control',
            'controller' => 'Bookmarks',
            'action' => 'view',
            1
        ]));
```

If you really need CamelCase prefixes, you should not use the prefix() helper and instead use `Router::scope()` to define the route parameters exactly as you want. Keep in mind that `DashedRoute` does not mangle the 'prefix' key so you may need a subclass if you want dashed prefix names in URLs.

**Comment by chipco** [comment]
Thanks for your answer, I solved my problem. For consistency reasons, I think it would be better if prefix and controller naming conventions would work the same by default.

Using @markstory's example, calling:
```php
debug(\Cake\Routing\Router::url([
            'prefix' => 'SmartControl',
            'controller' => 'RealTime',
            'action' => 'view',
            1
        ]));
```
should result in `/smart-control/real-time/view/1`.

**Comment by markstory** [comment]
They originally were the same. One challenge is that the prefix parameter has historically been underscored, and changing that now could break compatibility.
