### ISSUE TITLE
Subdomain problem for cakephp 3 

### ISSUE THREAD

**Issue by Penergy** [cakephp/cakephp#7826]
I have been trying to use cakephp 3. However, I met with a problem.

I have a domain: example.com and subdomain: admin.example.com. When I tried to configure the apache on my server and appointed admin.example.com to cakephp3 project, the cakephp 3 didn't work. The controller and webroot didn't read js and css files. Also I gave the permissions to cakephp3 project.

I didn't know why it happened. 

Could anyone give me some advices?

**Comment by Xety** [comment]
Hey,
You can have a look there https://github.com/cakephp/cakephp/issues/7140

**Comment by ionas** [comment]
If it is about routing prefixes: Setting up an admin route to be fired off a sub domain should be in the book - is it not?
If it is about setting up Apache: Try #httpd on IRC Freenode or #cakephp or some Google Groups / Stackoverflow.

**Comment by Penergy** [comment]
@Xety  thx for your suggestion. It works perfectly.
