### ISSUE TITLE
Pagination with total results limit

### ISSUE THREAD

**Issue by aledefreitas** [cakephp/cakephp#7827]
I stumbled upon this necessity during one of my projects using Cake. 

### How I need it to work
- I have a 1500 records table;
- I need to paginate it, and show only 5 results per page;
- **Maximum total results paginated must be 50** (this is where CakePHP can't help me as of now);

### Long story short
Users will see paginated results as if there were 50 records inside that table, so pagination will stop at 10th page (which is the 50th record limit), and the 11th should throw a \Cake\Network\Exception\NotFoundException

### Solution
By adding a custom attribute named "total_limit" to the $setting param from [\Cake\Controller\Component\PaginatorComponent::paginate()](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L149), and adding the following code to [this line](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L170):

```php
    if(isset($options['total_limit'])) {
        $offset = ($options['page']-1) * $options['limit'];
            if($options['total_limit'] < $offset + $options['limit']) {
                $force_limit = max(0, $options['total_limit'] - $offset);
                $query->limit($force_limit);
            }		
    }
```

and adding the following code to [this line](https://github.com/aledefreitas/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L174):
```php
    $count = isset($options['total_limit']) ? min($options['total_limit'], $count) : $count;
```

This will do the trick, and people will be able to choose the maximum size for the resultset which will be paginated, giving more flexibility to [PaginatorComponent](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php) without affecting any of its functionalities.

**Comment by dereuromark** [comment]
Isnt there already limit and maxLimit?
https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L41-L42

Seems like you are reinventing the wheel here.

**Comment by aledefreitas** [comment]
The concept for maxLimit doesn't quite solve the problem I described above, though @dereuromark!
See, if I set my $settings to:
```php
[ "limit" => 5,
  "maxLimit" => 50 ]
```

And the user tries to reach for ?page=11, it will show records from 50th to 55th. "maxLimit" would only prevent the user to get more than 50 **results per page**, and not 50 **total results**.

The solution I presented above would make ?page=11 throw a NotFoundException, cause it wouldn't let the result set be larger than 50 when "total_limit" is set to 50. Got it?

**Comment by dereuromark** [comment]
AFAIK it already throws a 404 when you try to go out of bounds, with limit 5 and page 11 (50th to 55th) that is the case. with maxLimit of 50 and limit 50 even page 2 already throws 404.

**Comment by aledefreitas** [comment]
Well, as of my project, running CakePHP 3.0.11, using PaginatorComponent as following:
```php
$most_read = $this->Paginator->paginate($this->Series->getMostReadSeries(), [ "maxLimit" => 50, "limit" => 5, "whitelist" => [] ]);
```

It allowed me to go above page 11.
See Picture:
!(Picture)[http://i.imgur.com/tIPzG8C.png]

**Comment by aledefreitas** [comment]
Just adding:
As far as my debbuging goes, this is caused because [this line](https://github.com/aledefreitas/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L173) returns the count for my entire table, which is 1899 right now, hence not triggering the NotFoundException on [line 214](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L214).

Perhaps adding to [line 174](https://github.com/aledefreitas/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L174):
```php
$count = isset($options['maxLimit']) ? min($options['maxLimit'], $count) : $count;
```
would do the trick to solve this?

**Comment by dereuromark** [comment]
Is it possible that you misunderstand the purpose of maxLimit?
It means the maximum of records for a single page (pagination max limit so to speak).
It is there to secure the pagination from an attack to read all records at once for huge DBs.

**Comment by aledefreitas** [comment]
Well, looks to me you're right. I might have misunderstood on which level it should be treated.
You're completely right, it should be handled on project level.

Sorry for all the fuzz about this :/

**Comment by wenbert** [comment]
I am interested on how OP got this solved. Even with `->limit(1000)` on the query, the paginator is continuing to display pages which are supposed to be "out of bounds".

**Comment by dereuromark** [comment]
Don't forget to also adjust the maxlimit.
And you can Also Set it to 99999 etc.
