### ISSUE TITLE
GET and POST input field names differ

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#7829]
I am not sure if this is a bug or intended behavior:
 `echo $this->Form->input('MyModel.my_column');` generates input with `name="data[MyModel][my_column]"` when the form is POST and `name="my_column"` when the form is GET. I didn't find that anywhere documented. CakePHP 2.6.12.

**Comment by markstory** [comment]
Yes that behavior is intentional, and has been around since the 1.2 days. I can add it to the documentation, but where would you expect to find this kind of information? Perhaps in the input creation docs?

**Comment by jhli** [comment]
Is this a good choice for the future or should that be changed for 4.x?

**Comment by bancer** [comment]
> Perhaps in the input creation docs?

Yes.

> Yes that behavior is intentional.

Why is that different for GET and POST? What is the idea behind that?

> Is this a good choice for the future or should that be changed for 4.x?

I find this non-intuitive and unexpected. In a project I am working on we have many POST forms that do not change any content of the database and we would like to change them to GET forms. Some of them have the same fields from different models, f.ex. `OneModel.title`, `AnotherModel.title`. So, it seems now we need to find some workaround.

**Comment by ionas** [comment]
As long as you don't use PRG you will always run into issues like that. I do also see a form based Paginator filter having issues with that, especially if you do multiple filtering in one page (assocs on entity view template)

As PRG is actually quite hackish in terms of HTTP (so you POST data but no change on the server happens ever within PRG) maybe it should be changed IN FUTURE for good. Until then maybe FormHelper::create() should have an option that disables/enables model alias prefixes appearing in $_PST and _GET?

**Comment by dereuromark** [comment]
@bancer I imagine it to be different for the following reason:
In the POST it does not matter if it is full or short, but for the URL there is a difference in length and visibility then.

**Comment by ADmad** [comment]
@jhli 3.x already doesn't use input names like `data[Model]['field']`. Regardless of GET or POST it's just `field`. Please don't stir up discussions for non-issues :)

**Comment by dereuromark** [comment]
Non-issues for the 3.x branch anyway, regarding get vs post difference.
But I am included to agree that this is maybe on of the "add missing documentation and it works for me" things. It is not a critical issue remaining in the 2.x line.

**Comment by ADmad** [comment]
Yes docs for 2.x should be updated.

**Comment by markstory** [comment]
@bancer If you want to fixate the name attributes, you can specify the desired names in the input() calls. For example `$this->Form->input('Model.field', ['name' => 'Model.field']);` should be consistent in both GET and POST forms.

**Comment by bancer** [comment]
`'name' => 'Model.field'` would require too many changes to the existing code. `'name' => sprintf('data[%s][%s]', 'Model', 'field')` works for me.

**Comment by markstory** [comment]
Docs pull request open now.
