### ISSUE TITLE
Backport stacking flash messages from 3.1 to 2.x

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#7830]
As mentioned by @dereuromark  in https://github.com/cakephp/cakephp/pull/6161#issuecomment-88437085 it would be useful to backport the stacking flash messages from 3.1 to 2.x.

Today I wanted to use stacking flash messages in a 2.x project and was suprised it's not implemented yet :laughing:

**Comment by jippi** [comment]
a PR is always welcome!

**Comment by dereuromark** [comment]
In 2.x one could use my components and helpers for it, existing since 2009+ :)

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.

**Comment by xhs345** [comment]
Spent some time today to implement the feature. See PR for more details
