### ISSUE TITLE
Rename current "2.x"  branch to "2.x"

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#7831]
At the time of writing this, the current 2.x branch is developed in the "2.7" branch.
https://github.com/cakephp/cakephp/tree/2.7

This introduces problems like https://github.com/cakephp/docs/issues/3546

Could we rename the current/stable branch for the 2.x release channel to "2.x" instead of iterating through the minor versions?
This could make pointing to it more permanent.

**Comment by markstory** [comment]
We could make that change for 2.8.0+

**Comment by ADmad** [comment]
Closing, we now have a `2.next` branch.

**Comment by rchavik** [comment]
What's the difference between `2.x` and `2.next` ?

**Comment by markstory** [comment]
2.x is the current stable 2.x release. While 2.next is the 'next' 2.x release.
