### ISSUE TITLE
Cakephp Plugin Unit Testing

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [cakephp/cakephp#7835]
Hi,
This is not an issue.Can any body provide the steps to that how to do the unit test for user defined plugins.
Ex: my plugin called "sampleplugin".In that i have one controller and many components.components are called from cotroller.
Here i dontknw how to do the unit testing for controller and components.
Please provide with example for plugin unit testing

**Comment by dereuromark** [comment]
This is indeed not an issue for this bugtracker.
Please look at the huge list of plugins and user-land-apps @ https://github.com/FriendsOfCake/awesome-cakephp/ and how they all managed to get unit testing to work.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
