### ISSUE TITLE
3.0 - Can't use Paginator::last() & Paginator::first() with a number and the original template

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7842]
Hello,

I wanted to use a custom template with the helper function `Paginator::last()` & `Paginator::first()` **and** with a number :

```php
'Paginator' => [
        'templates' => [
                'last' => '<li class="last"><a href="{{url}}" data-original-title="Last Page" data-toggle="tooltip" data-placement="top" data-container="body">{{text}}</a></li>',
                'first' => '<li class="first"><a href="{{url}}" data-original-title="First Page" data-toggle="tooltip" data-placement="top" data-container="body">{{text}}</a></li>'
        ]
]
```
Note that the `first` and `last` templates are different.

```php
<?php if ($this->Paginator->hasPrev()): ?>
        <?= $this->Paginator->first(1); ?>
        <?= $this->Paginator->prev('«'); ?>
<?php endif; ?>
<?= $this->Paginator->numbers(['modulus' => 4]); ?>
<?php if ($this->Paginator->hasNext()): ?>
        <?= $this->Paginator->next('»'); ?>
        <?= $this->Paginator->last(1); ?>
<?php endif; ?>
```

But i can't because when we use the functions `Paginator::last()` & `Paginator::first()` with a number it use the `number` template, ref : https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L968-L974
and there's no option to specify a custom template.

**Comment by markstory** [comment]
You should use a string number eg. `$this->Paginator->first('1');` to get the behavior you want.

**Comment by Xety** [comment]
That will work only with the `Paginator::first()`, but won't work for the `Paginator::last()`, because the text will always be `'1'`.

**Comment by markstory** [comment]
Well I don't think there is a solution then. Making a change to use different templates will break existing applications as the templates would change. 

If you need first and last to use custom templates you might have to override the templates for `number` before your first/last calls, and reset the templates afterwards.

**Comment by Xety** [comment]
Well, i worked on it, and found something interessant.

With `Paginator::last()` i can get it working with :
```php
$this->Paginator->last((string)$this->Paginator->counter('{{pages}}'));
```

### New bug found
I also tried with `Paginator::numbers()` and found a new bug :
```php
$this->Paginator->numbers([
    'modulus' => 2,
    'first' => '1',
    'last' => (string)$this->Paginator->counter('{{pages}}')
]);
```

I saw that it work for `Paginator::first()` because the first page is always `1`, but it doesn't work for `last`, because the value is converted to an interger without checking the type before : https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L824

After some tests, i have found a fix to get the `last` option working with a `'9'` value
```php
protected function _lastNumber($ellipsis, $params, $end, $options)
{
    $out = '';
    $last = is_int($options['last']) ? $options['last'] : 0;
    if ($options['last'] && $end < $params['pageCount']) {
        $offset = ($params['pageCount'] < $end + $last) ? $params['pageCount'] - $end : $options['last'];
        if ($offset <= $options['last'] && $params['pageCount'] - $end > $last) {
            $out .= $ellipsis;
        }
        $out .= $this->last($offset, $options);
    }
    return $out;
}
```

**Comment by markstory** [comment]
You could send a pull request to make last() and first() to work the same for string values :smile:

**Comment by Xety** [comment]
Added a PR with the fix  + testcases. :stuck_out_tongue:
