### ISSUE TITLE
Allow HasMany to have the  another save strategy other than append or replace

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#7844]
Sometimes, in a hasMany relationship:

```
Group hasMany Persons
```

A person can exist without a group, so the group_id of Person can be 0 or NULL. 

So I want to propose another save strategy in a hasMany relationship, which is to set the foreign key to 0 or NULL.

**Comment by ADmad** [comment]
I believe currently if you use `replace` strategy existing association not provided in new list will be unlinked by setting foreignKey null. Only if `dependent` option is set to `true` then the associated records are deleted.

**Comment by dilab** [comment]
@ADmad Thanks a lot for clarification. I forgot to clear model persistence cache files.

**Comment by dilab** [comment]
Issue is closed
