### ISSUE TITLE
Allow SecurityComponent to check fields that are optional, but must have a specific value if included

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#7848]
I have a number of places in my application where JavaScript on the edit page can change the list of fields that are sent. For input fields, I can just mark them as unlocked, but for hidden fields I need a way to ensure that the value doesn't change _if_ the field is included. An example would be the ID of a related record that might be removed. SecurityComponent does not have a way to handle this.

I could handle these situations on a case-by-case basis. Various people have posted similar questions on StackOverflow, and this seems to be the most common recommendation, but it feels like this clutters my controllers, and is not DRY.

I could overload some of the key functions in FormHelper and SecurityComponent, but then I have to monitor each of those functions for changes in the core and keep them updated to match any new features or bug fixes.

Or I could suggest changes to the core to handle this. This seems like the best route to me, but I don't want to work on such changes if it's unlikely that a pull request would be accepted. Is this something that would be considered a useful enhancement but nobody has put in the leg work yet, or would there be reluctance to change security features?

**Comment by markstory** [comment]
How do you see the optional fields being flagged or indicated when creating the inputs?

**Comment by Zuluru** [comment]
Not sure whether you mean how the resulting HTML would differ, or how the PHP calls to generate it would change.

For the former, either there would need to be a hash added for each optional field (which can start to get long quickly if there are many such fields), or else we serialize and then encrypt (instead of hash) the optional fields (in which case we are exposing ciphertext which has largely known plaintext, which can aid in cracking the key).

For the latter, I was thinking that either an optional parameter could be added to `unlockField` to control this, or else a new analogous `optionalField` function could be added.

**Comment by markstory** [comment]
> Not sure whether you mean how the resulting HTML would differ, or how the PHP calls to generate it would change.

I am mostly interested in what the PHP method interface would look like for the enhancements you'd like to see.

I would avoid encrypting values, giving it to the client, and then decrypting it. Instead checksums are often a simpler way to prevent message tampering without the risks of sending encrypted data to untrusted clients.

**Comment by Zuluru** [comment]
I agree about encrypting the data being the worse choice. Just wanted to throw it out there as an option, to show that I've put a least a modicum of thought into it. :-) And maybe it triggers a different idea from someone else that ends up being an even better way.

Would you have a preference on the PHP method interface? I'm thinking that a new parameter to unlockField might even take three possible values: `true` to unlock it as happens now, `false` to relock it (maybe the component is initialized with a field unlocked, but one particular use case requires it to be locked? I don't have a need for this, but it seems like an easy add that someone might benefit from...), or `'optional'` to invoke the new functionality. (Not at all convinced that "optional" is the right word to use here; it describes my use case, but maybe there's a better term.)

**Comment by markstory** [comment]
Boolean flag parameters are less preferable to separate methods. While boolean flags are easier to implement, they are harder to read and understand later. If there are multiple states that need to be reached we should consider separate methods for each state.

**Comment by Zuluru** [comment]
Fair enough. I was thinking of things like the "validate" flag to `save` which could take `true`, `false`, `'only'`, etc. But that is a different sort of situation. I'll do a bit of work on this and see how it goes.

**Comment by Zuluru** [comment]
In looking at the implementation, I've come across a couple of things that look a little strange. Not harmful in any way, so no immediate fixes needed. Just perhaps leftovers from some past functionality that could be cleaned up. If they are indeed strange, I can fix them in my eventual pull request.

1. `FormHelper::_secure` includes the line `return $this->fields[$field] = $value;`, but the return value is never used, and if it doesn't hit this one particular condition then nothing is returned. And the PHPDoc says `@return void`. Safe to remove the return?

2. `FormHelper::secure` defines a `$locked` variable, but never uses it. Safe to remove the variable?

**Comment by markstory** [comment]
Unused variables should always be safe to remove. The return should not be removed, but it should probably be just `return` instead. That return prevents line 639 from running.

**Comment by Zuluru** [comment]
Yep, should have said "safe to remove the return *value*".

I believe that I have the changes completed. At least, it's working for me in limited test scenarios. Still need to put it into use in my real code and make sure it holds up there, as well as writing tests for it. Between this, other work, and vacation, it will likely be January before I get the pull request in.

**Comment by markstory** [comment]
Ok.

**Comment by Zuluru** [comment]
I haven't had enough test scenarios yet to be completely confident in my changes, hence why I haven't yet put in a pull request. Getting close, though, I think! Today, I came across a new situation. It seems that when you create a hidden input, it's included in the security token, even if you say ['secure' => false]. Is this intentional? I have a page that this breaks, because the form inputs are all hidden, but values are changed by JavaScript in response to user actions. I have a potential fix for that situation included in what I'm working on, but want to make sure that it's wanted, because the code in FormHelper::hidden seems to go out of its way to work like this.

**Comment by Zuluru** [comment]
Note, I'm changing that broken page to use regular inputs that are hidden by CSS, but still wonder whether the `hidden` function ignoring the `secure` setting is on purpose or a bug to be resolved.

**Comment by markstory** [comment]
@Zuluru That sounds like a mistake/undesirable to me. Forcing the secure option to false, should not add the field to the secured input list. From [this code it doesn't look like that would happen](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L1523-L1535).

**Comment by Zuluru** [comment]
Not sure which part you mean sounds like a mistake. Let me clarify with some code. This creates a form with a single, hidden, unsecured input, and then changes the value of that input.

    echo $this->Form->create(false);
    echo $this->Form->hidden('test', ['value' => 1, 'id' => 'test', 'secure' => false]);
    echo $this->Form->submit();
    echo $this->Form->end();
    echo $this->Html->scriptBlock('document.getElementById("test").value = 2;');

Should this result in a black hole or not?

**Comment by markstory** [comment]
I would think that form submission should succeed. My previous comment was towards the secure option not working, as from reading the code it _should_ work.

**Comment by Zuluru** [comment]
I would agree that this form should work, but it does not for me. I have even undone my local changes for the optional fields, in case I broke something in doing them. But as far as I can tell, there's not really a list of secured fields, but rather a list of unsecured fields, updated by calling `_secure` with a `false` parameter. In the code you've highlighted, `_secure` is not called at all, and hence hidden fields are always considered to be secure, regardless of whether you want them to be or not.

It seems to me that `_secure` should always be called here, passing in the `$secure` parameter instead of `true`. But there may be a knock-on effect in how Cake's extra hidden fields (e.g. for checkboxes) are created.

**Comment by markstory** [comment]
>  But as far as I can tell, there's not really a list of secured fields, but rather a list of unsecured fields, updated by calling _secure with a false parameter.

The list of secured fields is in the helper. The `_secure` method appends the locked fields and for hidden inputs includes their value. I'll try to reproduce this issue tonight.

**Comment by markstory** [comment]
So I took a look, and the behavior you're observing is _intentional_. One of the goals of SecurityComponent is to prevent the manipulation of forms. Both adding and removing fields is disallowed. You'll need to use `$this->Form->unlockField('test')` to allow clientside manipulation of fields, or to allow a specific field to be removed.

The `'secure' => false` option lets you mark a field as one that _will_ be unlocked later, and gives you the flexibility to use `unlockField()` after the input has be been created. Without this option you'd need to mark fields as unlocked before creating them.

**Comment by Zuluru** [comment]
I'll have to come back to this a little later, but my experience (albeit limited) has been that I never have to explicitly call `unlockField()`, I just pass `'secure' => false` in the options array to `$this->Form->input()`, and it works how I expect. Maybe my expectation is wrong. :-)

**Comment by Zuluru** [comment]
Okay, if I understand correctly, you're saying that this code *should* cause a black hole, because the `test` field is not submitted (as a result of JS disabling it), but I never explicitly call `unlockField()`?

    echo $this->Form->create(false);
    echo $this->Form->input('test', ['type' => 'text', 'id' => 'test', 'secure' => false]);
    echo $this->Html->scriptBlock('document.getElementById("test").disabled = true;');
    echo $this->Form->submit();
    echo $this->Form->end();

**Comment by markstory** [comment]
No that will not be blackholed as the 'additional' field was not submitted. If that field was not disabled, the form would be blackholed.

**Comment by Zuluru** [comment]
The PR implementing this for the 3.x line was rejected as being of minimal benefit compared to the potential complexity of maintaining the code. Any reason to think that would change in the future?
