### ISSUE TITLE
Unexpected output when naming multiple file upload fields

### ISSUE THREAD

**Issue by leighmackay** [cakephp/cakephp#7849]
Hello

When creating a multiple file upload field that has a prefix "attachments.whatever[]" the field is named weird.

```
echo $this->Form->file('attachments.file[]', ['label' => 'Attach file', 'multiple' => true, ]);
// expected "attachments[file][]" but came out "attachments[file[]]"
```

without prefix it works great.

```
echo $this->Form->file('file[]', ['label' => 'Attach file', 'multiple' => true]);
// works file[]
```

The fix is to set the name using the "name" attribute which works great, but it does seem strange doing that.

Maybe an enhancement? or can document fix in book.

**Comment by markstory** [comment]
I'm not sure `thing.field[]` works in most input types. From a quick check it also fails in text and hidden inputs.

Seems like an opportunity for the code to do what you're expecting vs. documentation. I suspect `FormHelper::_initInputField()` is at fault here.

**Comment by leighmackay** [comment]
Thank you @markstory. I'll try and patch it tonight.

**Comment by markstory** [comment]
@leighmackay :+1:

**Comment by leighmackay** [comment]
Thank you @markstory. Closing ticket.
