### ISSUE TITLE
Generating Migrations From Existing Databases In plugin fail

### ISSUE THREAD

**Issue by visonforcoding** [cakephp/cakephp#7851]
I want  generating migrations to the plugin config dir from existing database,
when i use the command
```
bin/cake bake migration_snapshot --plugin Admin Initial

```
Admin is my plugin .
the migrations file has been created .bug the up and down function is empty!

**Comment by lorenzo** [comment]
Can you please open the issue report in this repo? https://github.com/cakephp/migrations

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#172
