### ISSUE TITLE
[3.0][Enhancement] Implement `Auth::loginActionRedirect` function to redirect to the `loginAction` option URL

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7852]
Hey,

I have maybe missed something in the doc, but it look like there's no method to redirect an user to the login action dynamically, i means without calling the `controller/action` name :
```php
$this->redirect(['controller' => 'users', 'action' => 'myCustomLogin']);
```
I expected to use a function (build with the `AuthComponent`) like that :
```php
$this->redirect($this->Auth->loginActionRedirect());
//OR
$this->redirect($this->Auth->loginActionUrl());
```

Calling this function will redirect to the `loginAction` option URL.
That means, if for X or Y reason, we change the URL in the option `loginAction`, and we use this function, the URL will change automatically.

I know there's 2 methods to do it actually :
```php
$this->redirect($this->Auth->_config['loginAction']);
```
And with a custom `named` route :
```php
$this->redirect(['_name' => 'users-myCustomLogin']);
```

But those methods are ugly, and for the named routes, we use generally the pattern `:controller-:action`, so if we change the route, without changing the name of the route, it will result to some confusion.

**Comment by ADmad** [comment]
None of the existing alternatives seem ugly to me.

I don't see how existing alternative `$this->redirect($this->Auth->config('loginAction'));` is any worse than your proposed `$this->redirect($this->Auth->loginActionUrl());`.  With the exception of the former requiring an argument they are the same.

> so if we change the route, without changing the name of the route, it will result to some confusion.

Then I would suggest rethinking your conventions. It beats the point of using named routes if changing a route name also requires you to change the route itself.

**Comment by ADmad** [comment]
You can always extend `AuthComponent` and add your extra one line method.

**Comment by Xety** [comment]
I didn't know about :
```php
$this->Auth->config('loginAction')
```
I thought it was only a `setter` (to define our config), but not a `getter` like you showed me. It's not written in the doc that we can get the value of an option with the `config()` method.

With your method, yes, it's better than :
```php
$this->Auth->_config['loginAction']
```
Because accessing to the `$_config` variable directly sound a bit weird for me, that is why i searched a function in the `AuthComponent` and i found nothing, then i opened the issue.

Maybe add a note about it in the doc, that we can also use this function to get a property value ?

Something like :
> Also, the `$this->Auth->config()` allow you to get a configuration value by calling only the configuration option. i.e `$this->Auth-> >config('loginAction')`. Without option, the full configuration will be returned.

http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuration-options

**Comment by ADmad** [comment]
You wouldn't have been able to actually use `$this->Auth->_config['loginAction']` since `_config` is a protected property. [InstanceConfigTrait::config()](http://api.cakephp.org/3.1/class-Cake.Core.InstanceConfigTrait.html#_config) is a combined getter/setter.

You are welcome to make a PR for the docs to make things clearer.

**Comment by Xety** [comment]
I will do a PR in the docs, thanks for your explanation. :+1:
