### ISSUE TITLE
Postgres index error

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#7853]
Hello,

I noticed that in the since version 3 when I try to access the data of a table that has an index with NULLS LAST or NULLS FIRST Cake gives me this error:

Columns used in index "my_test_index" in table "tests" must be added to the Table schema first. The column "total DESC NULLS LAST" was not found.

Cake\Database\Exception

Sure, the column 'total' exists on the table schema, however something is not quite right...

**Comment by markstory** [comment]
What does the create table statement for your table look like?

**Comment by urionlinejudge** [comment]
Hi!

I noticed this problem with other tables as well. Here is a sample:

CREATE TABLE tests
(
  id serial NOT NULL,
  user_id integer NOT NULL,
  group_id integer NOT NULL,
  grade double precision,
  CONSTRAINT tests_pkey PRIMARY KEY (id),
  CONSTRAINT tests_group_id_fkey FOREIGN KEY (group_id)
      REFERENCES groups (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT tests_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT tests_unique_key UNIQUE (user_id, group_id)
)
WITH (
  OIDS=FALSE
);

-- Index: tests_problem

CREATE INDEX tests_problem
  ON tests
  USING btree
  (group_id, grade NULLS FIRST);

**Comment by markstory** [comment]
Closing as #7861 is open now.
