### ISSUE TITLE
Problem Hashing password when the password field contains underscore 

### ISSUE THREAD

**Issue by YassineKhadouch** [cakephp/cakephp#7855]
Hi,

I have a custom password field called user_hash before i activate the password hashing in the user entity i couldn't authenticate at all the $this->Auth->identify() always return false and when i add the password hashing it did not work so i manually hashed the password and save it to the db using this 
   $hasher = new \Cake\Auth\DefaultPasswordHasher();
   $hasher->hash($this->request->data['user_hash']));

when i authenticate with a user that has the password hashed it works fine but not when using a normal user and hashing disabled on the entity

Here is my password setter on the entity:
-------------
    protected function _setuser_hash($password) {
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($password);
    }
----------------
Login Function in UsersController:
----------------
    public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();  // This alwas return false
            var_dump($user);
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
    }
----------------
initialize() function in AppController (loading Auth Component):
----------------
        $this->loadComponent('Auth', [
            'loginRedirect' => [
                'controller' => 'Coaches',
                'action' => 'index'
            ],
            'logoutRedirect' => [
                'controller' => 'home',
                'action' => 'index'
            ],
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login'
            ],
            'authenticate' => [
                'Form' => [                                  
                    'fields' => ['username' => 'user_name', 'password' => 'user_hash']
                ]
            ],
            'authError' => 'You do not have access to this page'
        ]);
----------------
Login view:
----------------
<div class="users form">
        <?= $this->Flash->render('auth') ?>
        <?= $this->Form->create(null, [
            'url' => ['controller' => 'Users', 'action' => 'login']
              ]); ?>
            <fieldset>
                <legend><?= __('Please enter your username and password') ?></legend>
                <?= $this->Form->input('user_name', array('label' => 'Login')) ?>
                <?= $this->Form->input('user_hash', array('label' => 'Password')) ?>
            </fieldset>
        <?= $this->Form->button(__('Login')); ?>
        <?= $this->Form->end() ?>
    </div>

**Comment by YassineKhadouch** [comment]
By the way i know it should be like this: _setUser_hash but it i tried all of them (_setuser_hash, _setUser_hash, _setuserhash, _setUserhash ...)
this the property in the user entity @property string $user_hash

**Comment by ionas** [comment]
For the fieldname 'user_hash' Did you actually try the setter ```public function _setUserHash```?

**Comment by ADmad** [comment]
The setter method should be `_setUserHash()` since the field name is [camelized](https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L252) to generate method name.

**Comment by YassineKhadouch** [comment]
Awesome this works _setUserHash($password) i did try this setter _setUserhash but not this one _setUserHash($password) 
Thank you ionas and ADmad
