### ISSUE TITLE
Virtual fields are not fetched properly

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#7858]
Virtual fields are not fetched properly when one model's alias conflicts with another model's name. Let's say there are two models: `Bird` and `Duck` and `Duck::$alias = 'Bird'`. I would like to have finds from both models to return data with the same 'Bird' key. Is it a bug or there is missing documentation?

 CakePHP 2.6.12, MySQL.

**Comment by markstory** [comment]
I don't think I understand the issue, could you give some more detail as to what is not working?

**Comment by ADmad** [comment]
Given the fact that alias is used for array key it's no surprise that all fields end up under same key. What else would you expect? That's why model aliases should be unique through out your application.

**Comment by bancer** [comment]
The problem is not that 'Bird' alias is used. The problem is that virtual fields are not fetched. F.ex. `$this->Duck->virtualFields = array('my_column' => 'SELECT ....' );` do not produce 'Duck.my_column' value but produces '0.my_column' value.

**Comment by lorenzo** [comment]
Cake does not allow having model with the same alias. You need to post-proces the results to merge the fields from the two models

**Comment by bancer** [comment]
It does allow. The only problem is virtual fields that are not fetched properly. I do not need to merge the fields from two models as `find()` is called only on one model.
