### ISSUE TITLE
Cake 2.6.12: Bug in cake_core_file_map cache

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#7859]
Not sure if this bug is fixed in a more recent version than 2.6.12 if yes it would be nice to provide a 2.6.13 version. I noticed the following issue after I enabled the sidewide cache.

I have the following controllers:
app/Plugin/Affiliate/SaleStatisticsController.php
app/Plugin/Feeds/SaleStatisticController.php

If I run an action in the `app/Plugin/Affiliate/SaleStatisticsController.php` controller first, that controller is cached to `cake_core_file_map`. If I try to run an action of the other controller (`app/Plugin/Feeds/SaleStatisticController.php`) afterwards, cake will use the already cached one, `app/Plugin/Affiliate/SaleStatisticsController.php` in this case.

This issue always occurrs if you have a model/controller (probably other things also)  more than once in different plugins.

**Comment by biesbjerg** [comment]
Hi Steefaan.

This issue has been brought up several times actually. CakePHP 2.x does not support duplicate controller names - even if they belong to different plugins. 

You could name them AffiliateSaleStatisticsController and FeedsSaleStatisticsController to work around this.

**Comment by steefaan** [comment]
@biesbjerg Thanks for your reply I do it this way currently but feels wrong why I opened this issue :) But if there is no solution for cake2 I will stick to this.

**Comment by markstory** [comment]
This has been reported numerous times, and will not be fixed. Duplicate class names make testing, requestAction() and other operations unsafe. See #6423, #5345
