### ISSUE TITLE
Database session PHP7 2.8 forcing bool

### ISSUE THREAD

**Issue by XYG6** [cakephp/cakephp#7860]
I'm trying to run latest stable cakePHP 2.7.6 on PHP7 and I got some errors with database session handling.

I'm aware of the 2.8-PHP7 branch latest commit "Forcing bool" which fixes session callback return value type compatibility with PHP7 and which was quickly reverted: https://github.com/cakephp/cakephp/commits/2.8-PHP7

I'm wondering why, since it fixed some of my issues. Is there some logic that will completely be rewritten?

**Comment by phpnut** [comment]
@XYG6 I reverted it but will be adding some of those changes back. I did not test on some of the previous versions of PHP before pushing to the branch
