### ISSUE TITLE
Create Database dynamically at run time and dump sql file into that database  in Cakephp

### ISSUE THREAD

**Issue by vinithac** [cakephp/cakephp#7863]
Requirement : Need to create database dynamically at run time. 
                       Need to dump a sql file into that created database.

Following Approach : 

```php
 public function createDatabase($database_name)
    {
        $cn = ConnectionManager::getDataSource('default')->config;    
        $servername = $cn['host'];
        $username = $cn['login'];
        $password = $cn['password'];

        // Create connection
        $conn = new mysqli($servername, $username, $password);
        // Check connection
        if ($conn->connect_error) {
            return false; //die("Connection failed: " . $conn->connect_error);
        }

        // Create database
        $sql = "CREATE DATABASE ".$database_name;
        if ($conn->query($sql) === TRUE) {
            $conn2 = new mysqli($servername, $username, $password,$database_name);
            App::uses('File', 'Utility');
            $file = new File( APP . 'config/testsql.sql', true, 0755);
            $file->open('r',false);
            $sql = $file->read();  
            $conn2->query($sql);
           // pr(ConnectionManager::getDataSource('admin')->config);    
            return true; // "Database created successfully";
        } else {
            return false; // "Error creating database: " . $conn->error;
        }
    }
```

Defined above function in model.
Above is the manual approach in Mysql. Is there any cakephp function to create database and also  dumps sql file into that database at run time.

How to execute a sql file dynamically in specific database ? Any functions which takes file path as paramater to execute...??

**Comment by markstory** [comment]
> Is there any cakephp function to create database and also dumps sql file into that database at run time

Nope. You'll have to write that if you need it.

Closing as this is a question. I don't think that creating databases, and loading dump files is something that is generally required at runtime for many web applications, and therefore isn't something we'd implement in CakePHP. It does however sound like something that could be handled by migrations, or a plugin.

**Comment by dakota** [comment]
This sounds like something that can already be handled by the migrations
plugin.

**Comment by justinmoh** [comment]
@dakota too bad I couldn't find it documented anywhere. Phinx provide limited use case on its documentation, Cake's documentation on Migrations Plugin doesn't help much as well.

It's a working feature sits at the corner, quietly.

**Comment by HavokInspiration** [comment]
This could be done using the ``Migrations`` class that allows migrations to be run in a non-shell environment.

[Documentation in the cookbook](http://book.cakephp.org/3.0/en/migrations.html#running-migrations-in-a-non-shell-environment)

The table creation part could be done using a migration ([with a migration looking like this](http://book.cakephp.org/3.0/en/migrations.html#creating-a-table) for example)
The data seeding into that newly created table could be done 

- [using the seed feature](http://book.cakephp.org/3.0/en/migrations.html#seed-seeding-your-database).
- or by executing a query stored in a SQL file by loading its content and [executing the raw query](http://docs.phinx.org/en/latest/migrations.html?highlight=execute#executing-queries) directly from the migration file.

**Comment by HavokInspiration** [comment]
Ah well I misread.
Creating a database at runtime with the migration plugin is not possible.

The connection absolutely needs to be established on an existing database.
But you can create the database manually, set up a connection to connect to it and then use the various proposal I made in my previous post to populate the said database specifying the said connection that you just set up as a parameter for the various method call of the ``Migrations`` class you'd made.

**Comment by justinmoh** [comment]
@HavokInspiration That's what is happening, it needs an established database connection, thus the database must exist before it's been called.

Often I want make something automated for my (junior) team member, I'd like it to work as `one-click` as possible, also thought about something like `auto-deploy` kind of stuffs.

I came by just wondering if Cake itself already handles some of these features, or I'll have to do it in an external script file.

Have a good day.

**Comment by HavokInspiration** [comment]
Except for the database creation, everything can be done using the migrations plugin.

But the need for an existing database is due to the way Cake creates a connection to the database server.
