### ISSUE TITLE
How to get connected with remote Mysql server from CakePHP ?

### ISSUE THREAD

**Issue by vinithac** [cakephp/cakephp#7868]
I need to connect with remote mysql server having different Ip address and host(not localhost).

Is there any option to provide Ip address in database config settings ?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by vinithac** [comment]
No I have tried with below settings 

My remote server login details as follows :+1:  
Host name : HPS###
Ip adress : 192.##.##.###
login : root
password:A#####X

public $default = array(
        'datasource' => 'Database/Mysql',
        'persistent' => true,
        'host' => 'HPS###',
	'port' => '3306',
        'login' => 'root',
        'password' => 'A#####X',
        'database' => 'remote_db',
        'prefix' => '',
        'encoding' => 'utf8',
    );

By giving above settings.Following error has been raised

Error: A Database connection using "Mysql" was missing or unable to connect.
The database server returned this error: SQLSTATE[HY000] [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 

Where should I provide Ip address? As I dont find any options in settings in manual as well. I would like to know whether we have possiblity in cakephp to connect with remote server.

**Comment by vinithac** [comment]
Host :The database server’s hostname (or IP address).

I know host parameter is used to provide hostname. But in my case host name and Ip address both are different.

**Comment by ADmad** [comment]
You can use either IP address of hostname for the `'host'` key.

**Comment by vinithac** [comment]
ADmad..I have tried with both ways. By giving Ip address as hostname.

Following error raised

Warning (2): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: The requested name is valid, but no data of the requested type was found. [CORE\Cake\Model\Datasource\Database\Mysql.php, line 184]


A Database connection using "Mysql" was missing or unable to connect.
The database server returned this error: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: The requested name is valid, but no data of the requested type was found.

**Comment by ADmad** [comment]
Use one of the help forums stated above.

**Comment by vinithac** [comment]
I have IP address where 3 host servers exists. I need to connect with 2 second server with name HPS#### among 3 servers.

**Comment by vinithac** [comment]
If we give Ip address in host parameter..then where is the option to choose specific host server among three in database config settings? How can Cakephp detects the specific server..it should have parameter to findout the specific once. There is not specific parameter to detect the server.

**Comment by jippi** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
