### ISSUE TITLE
Look at Postgres index reflection

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#7871]
See @LACabeza's comment on #7861 for more information.

**Comment by markstory** [comment]
Pull request up.

**Comment by LACabeza** [comment]
Thanks. This fixed my issue, but i have one more question.
With this fix, describeIndexSql won't fetch [indexes on expression](http://www.postgresql.org/docs/9.1/static/indexes-expressional.html). Is this a problem?

**Comment by markstory** [comment]
We don't currently have a way to rebuild indexes on expressions so I don't think capturing them in the reflected schema is going to be a problem.
