### ISSUE TITLE
Paginating a query with orderDesc and addCase raises an error

### ISSUE THREAD

**Issue by LACabeza** [cakephp/cakephp#7872]
In the code works fine:

```php
$query->orderDesc(
    $query->newExpr()->addCase(
        [
            $query->newExpr()->add(['Users.role' => 'admin']),
        ],
        [ 1, 0 ],
        [ 'integer', 'integer' ]
    )
);
$results = $query->all();
```
the generated sql is `ORDER BY CASE WHEN Users.role = 'admin' THEN 1 ELSE 0 END DESC` and `$results` is ok.
But if instead I call `$this->paginate($query)`, it raises an error

    SQLSTATE[HY093]: Invalid parameter number: :c0

**Comment by markstory** [comment]
This is likely due to the count query being incorrect after cloning.

**Comment by LACabeza** [comment]
Yes. When i debugged, i saw that on PaginatorComponent, this error is raised on line

    $count = $numResults ? $query->count() : 0;

But i don't know why $query->count() don't works.

**Comment by markstory** [comment]
`count()` clones the query and does a few other tricks to try and make arbitrary queries countable. I suspect we're not cloning an object correctly somewhere down the way.

**Comment by LACabeza** [comment]
I think the problem could be that `cleanCopy()` clones the query without order statements `$clone->order([], true);`, but keep the original `_valueBinder` property.

**Comment by markstory** [comment]
@LACabeza That sounds like the problem to me as well.

**Comment by lorenzo** [comment]
A PR to fix this is open
