### ISSUE TITLE
RFC 3.2: Deprecate action in favor of url in Form::create()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7885]
Currently, if you need to change the URL the form should post to, you can use `action` and `url`, which kind of makes `action` key itself redundant.
We should remove the `action` part in favor of directly using `url`. Makes it less confusing - and `url` always works, whereas if you got `action` and need to add anything else, you would have to move it anyways.

https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L319-L321

```php
// Former syntax
$this->Form->create(null, ['action' => 'foo'])

// Former syntax. People now assume this will work (but does not of course)
$this->Form->create(null, ['action' => 'foo', 'controller' => 'Bar'])

// Former syntax. At some point you learn that it should should have been
$this->Form->create(null, ['url' => ['action' => 'foo', 'controller' => 'Bar']])

// New syntax then (force always correct one right away)
$this->Form->create(null, ['url' => ['action' => 'foo']])
$this->Form->create(null, ['url' => ['action' => 'foo', 'controller' => 'Bar']])
```

A basic trigger_error() with E_USER_DEPRECATED should do it with BC.

PS: We should then also do that for 2.8.

**Comment by ionas** [comment]
I am not so sure URL is a good hashkey. 
https://en.wikipedia.org/wiki/Uniform_Resource_Locator
It is not really an url you are targeting but rather it is an action. My first gut suggestion is:

**Comment by ionas** [comment]
I am not so sure URL is a good hashkey.
https://en.wikipedia.org/wiki/Uniform_Resource_Locator

**Comment by dereuromark** [comment]
We use that `url` key everywhere in the framework for exactly this thing, switching to anything else now is nonsense IMO :)

**Comment by Spriz** [comment]
:+1:

**Comment by ionas** [comment]
```Form::create(string $modelName = null, mixed $url = null, array $options =[])```

**Comment by ionas** [comment]
As soon as breaking changes are allowed (4.0?) I'd like to see ```FormHelper::create()``` have an interface very similar to ```HtmlHelper::link()```: http://book.cakephp.org/3.0/en/views/helpers/html.html#Cake\View\Helper\HtmlHelper::link
e.g.: ```FormHelper::create(string $modelName = null, mixed $url = null, array $options =[])```
This makes the interface work like expected when working with the framework, as it is consistent.

Making this change between now and then is possibly hurting not helping as the then to be used interface means the old syntax will work, e.g.::

```$this->Form->create(null, ['action' => 'foo'], $options)```

**Comment by dereuromark** [comment]
Again: Why are you going off topic here? You can make a separate issue with your suggested changes.
Totally out of scope of this RFC issue.

**Comment by ionas** [comment]
I emboldened the relevant passage for you.

**Comment by ionas** [comment]
:-1:

**Comment by dereuromark** [comment]
Yes, but that is 4.0, and we are talking about 2.x and 3.x, you cannot just add a new argument in the middle without breaking everything (NON BC).
Please stop this counterproductive noise.

And as for your suggestment: Using url from my experience is not that common and does not justify its own 2nd param. Being part of options is totally sufficient IMO.

**Comment by ionas** [comment]
A) We are talking about a 3.2 deprecation warning that **targets 4.0** teaching people to use a different interface. I suggest we should *not* as the current interface is fine but should change like suggested above and *not* like you suggest. The whole point here is preparing for **4.0**

B) Consistency is much more important than having to type ```[]``` especially if you want to have a framework that is friendly to new people, joining. In any case changing the parameters of ```create()```
Having to type ```'url' => []``` btw is also more verbose.

**Comment by dereuromark** [comment]
And I still think breaking BC that hard is even for 4.0 a change that is in no way worth doing, it is a use case only rarely needed and fine in options. There is a reason a form defaults to itself.

**Comment by ionas** [comment]
I’d deprecate nothing as long as there isn't a plan on how the interface should look for 4.0. If you are keen on being BC you could introduce ```FormHelper::begin()``` which would work like ```HtmlHelper::link()``` (e.g. similar signature) and keep ```FormHelper::create()``` (then deprecated) like it is and thus even keep ```‘action’ => ‘foo’``` so that people migrating have little hassle.

**Comment by markstory** [comment]
Deprecating an effectively redundant parameter seems fine to me. Changing the method signature is something that can be discussed in the context of 4.0.

Having an explicit url parameter would depend on how frequently it is used. Having done no research, my gut feel is that many forms submit to the originating action.

**Comment by dereuromark** [comment]
PR is up.
