### ISSUE TITLE
Use fixtures in Component

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [cakephp/cakephp#7886]
Hi,
Iam writing test cases for one component ,need to use fixtures in compoment.
my code is

```php
Class SampleComponentTest extends TestCase
{
    public $component = null;
    public $controller = null;
    public $fixtures = ['app.cities','plugin.sampleplugin.states'];
    public function setUp()
    {
        parent::setUp();
        $request = new Request();
        $response = new Response();
        $this->controller = $this->getMock(
            'Cake\Controller\Controller',
            [],
            [$request, $response]
        );
        $registry = new ComponentRegistry($this->controller);
        $this->component = new SampleComponent($registry);
    }
}
```

And i need to use two fixtures ,one is from app and another is from plugin.
when i run the code i got followign exception
"Exception: Referenced fixture class "SamplePlugin\Test\Fixture\StatesFixture" not found. Fixture "plugin.sampleplugin.states" was referenced in test case "App\Test\TestCase\Controller\Component\SampleComponentTest". in [D:\Projects\xampp\htdocs\testapp\vendor\
cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 213]".

please provide the solutions to that how to use fixtures in component with sample code/
doubts
1)$this->component is mock object or direct object>
2)what is second parameter of getMock() method(if i provide empty it giving the error,above i replaced with empty)
3)

**Comment by dereuromark** [comment]
Sure you got the casing right?
Woudnt' it be `'plugin.SamplePlugin.States'` or at least 'plugin.sample_plugin.states'?

**Comment by markstory** [comment]
>  1)$this->component is mock object or direct object>

It is a concrete object as you did not call getMock().

> what is second parameter of getMock() method(if i provide empty it giving the error,above i replaced with empty)

[PHPUnit has documentation for getMock](https://phpunit.de/manual/current/en/test-doubles.html).

Check the casing/names of your fixture file, path and classname/namespace.

**Comment by ravikanthhtnakivar** [comment]
thanks for reply.
i tried with "plugin.sample_plugin.states",also giving the same exception.

**Comment by dereuromark** [comment]
Dont use private, use protected.
There is also Reflexion.

**Comment by ravikanthhtnakivar** [comment]
thank you...
i tried with "plugin.sample_plugin.states",also giving the same exception.

**Comment by dereuromark** [comment]
Most likely your fixture is invalid and therefore cannot be found.
Sure your use statements are correct?
You can bin your code in that file, but it would be best if you consult other places.
This is an issue tracker, not a debugging help forum.

**Comment by ravikanthhtnakivar** [comment]
while executing the plugin test cases iam gettign following error plz send the solutions asap
1) Cake\Test\TestCase\Controller\UsersControllerTest::testIndex
include(D:\xampp\htdocs\myapp\plugins\UserEngine\vendor\
cakephp\cakephp\tests\test_app\config\routes.php): failed to open stream: No suc
h file or directory

D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\Routing\Router.php:974
D:\xampp\htdocs\myapp\plugins\UserEngine\vendor\cakephp\
cakephp\src\Routing\Router.php:974
D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\Routing\Router.php:547
D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\TestSuite\IntegrationTestCase.php:452
D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\TestSuite\IntegrationTestCase.php:392
D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\TestSuite\IntegrationTestCase.php:312
D:\xampp\htdocs\myapp\plugins\UserEngine\Vendor\cakephp\
cakephp\src\TestSuite\IntegrationTestCase.php:233
D:\xampp\htdocs\myapp\plugins\UserEngine\tests\TestCase\
Controller\CustomerDiscountsControllerTest.php:48
D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
D:\\xampp\php\pear\PHPUnit\TextUI\Command.php:129

**Comment by ravikanthhtnakivar** [comment]
please help me for the above

**Comment by dereuromark** [comment]
You need to create missing files.
Please refer to other help resources for details.
This issue is closed - as already mentioned this is not a framework bug/issue.

**Comment by ravikanthhtnakivar** [comment]
thank you dereuromark
