### ISSUE TITLE
newEntity removes the id in the associated table

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/cakephp#7888]
Hello, I was trying to save the following data:

```
[
	'descricao' => 'asd asd asd asd',
	'cliente_id' => '',
	'data_vencimento' => '23/12/2015',
	'valor' => '23,23',
	'ccusto_id' => '',
	'pagar' => '0',
	'repetir' => '0',
	'tipo' => '2',
	'arquivos' => [
		(int) 0 => [
			'id' => (int) 275,
			'caminho' => 'files/fl-mapa-a4.pdf',
			'nome' => 'fl-mapa-a4'
		],
		(int) 1 => [
			'id' => (int) 276,
			'caminho' => 'files/bemean-v3.pdf',
			'nome' => 'bemean-v3'
		]
	]
]
```

This is the result of debug ($this->request->data);

After passing through the newEntity accounts $ this->Contas->newEntity ($ this->request->data ['associated' => ['file' => ['accessibleFields' => true]]]) ;
it looks like this:

Notice that the new Entity removed the ID field in 'arquivos' => [], this behavior is normal?

If so, what should I do to make this not happen, if not words, will provide the changes.

object(App\Model\Entity\Conta) {

	'descricao' => 'asd asd asd asd',
	'cliente_id' => null,
	'data_vencimento' => object(Cake\I18n\Time) {

		'time' => '2015-12-23T00:00:00+0000',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'valor' => (float) 23.23,
	'ccusto_id' => null,
	'pagar' => '0',
	'repetir' => '0',
	'tipo' => '2',
	'arquivos' => [
		(int) 0 => object(App\Model\Entity\Arquivo) {

			'caminho' => 'files/fl-mapa-a4.pdf',
			'nome' => 'fl-mapa-a4',
			'[new]' => true,
			'[accessible]' => [
				'*' => true,
				(int) 0 => true
			],
			'[dirty]' => [
				'caminho' => true,
				'nome' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => 'Arquivos'
		
		},
		(int) 1 => object(App\Model\Entity\Arquivo) {

			'caminho' => 'files/bemean-v3.pdf',
			'nome' => 'bemean-v3',
			'[new]' => true,
			'[accessible]' => [
				'*' => true,
				(int) 0 => true
			],
			'[dirty]' => [
				'caminho' => true,
				'nome' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => 'Arquivos'
		
		}
	],
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'descricao' => true,
		'cliente_id' => true,
		'data_vencimento' => true,
		'valor' => true,
		'ccusto_id' => true,
		'pagar' => true,
		'repetir' => true,
		'tipo' => true,
		'arquivos' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'Contas'

}

**Comment by lorenzo** [comment]
`accessibleFields => true` is not a valid value. Also, do those ids you are trying to pass exist in the database?

**Comment by alexsmonte** [comment]
The accessibleFields => true was an attempt to desperate, but ARQUIVOS => [] data exists in the database actually believe he does not update precisely because he remove the ID field is this normal?

**Comment by markstory** [comment]
What kind of association is `arquivos`? Your entity classes probably don't include `id` in their `_accessibleFields` property, which will be one reason the `id` is not included in the created entity.

Also if you are using `newEntity()` to update existing entities you will have a hard time. You might want to consider using patchEntity() instead of modifying existing records.

**Comment by alexsmonte** [comment]
I did so ['associated' => ['file' => ['accessible Fields' => ['id' => true]]]] and it worked, sometimes used as well ['associated' => ['file' = > ['accessibleFields' => true]]] and worked ...

I used patchEntity

**Comment by markstory** [comment]
Sounds like you have a solution then :smile:
