### ISSUE TITLE
Validation problem when using  JQuery to add element

### ISSUE THREAD

**Issue by Penergy** [cakephp/cakephp#7889]
Hi all,

I am creating an add.ctp, which includes two model forms. One input form used cakephp Formhelper. The other used JQuery to add elements to create a cakephp form data. However, the validation of the second form and its model didn't work. I would like to know whether Cakephp 3 provides some mechanisms. Otherwise, I have to use JQuery validation plugin to realize.

**Comment by markstory** [comment]
What is the validation problem? You can certainly add fields to existing forms client side and have everything work. The one caveat will be that if you are using SecurityComponent, you will run into form tampering failures, as you are tampering with the form.
