### ISSUE TITLE
[2.7] virtualFields in associations

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#7891]
Lets say I have a User model with virtualField `name`. The user model belongs to itself (as Manager) via `manager_id`.

In a `$this->User->find()` call I can fetch `User.name`, but not `Manager.name`. Instead I have to use this work-around:

```php
$this->Manager->virtualFields['name'] = 'foo'; // yes, it does not matter what the value is
$this->User->find('all', [
    'fields' => [
        'CONCAT(Manager.firstname, " ", Manager.lastname) as Manager__name'
    ]
]);
```

Note that if I try to fetch `Manager.name` I will get "Column not found" SQL error, but when I manually set the field alias to `Manager__name`, CakePHP will format it correctly as `Manager.name` in the result array.

This leads me to conclude that virtualFields is somewhat buggy. It works after the result has been fetched, but not when parsing the SQL expression.

**Comment by markstory** [comment]
How is the virtualField originally being defined? VirtualFields have [some limitations around aliases](http://book.cakephp.org/2.0/en/models/virtual-fields.html#virtual-fields-and-model-aliases).

**Comment by josegonzalez** [comment]
@davidsteinsland friendly *bump* :)

**Comment by davidsteinsland** [comment]
@josegonzalez I got my "answer" from @markstory, and then I would believe it's up to you guys on whether or not this is a wanted behavior.
