### ISSUE TITLE
I18n init creates folder with incorrect name.

### ISSUE THREAD

**Issue by LACabeza** [cakephp/cakephp#7895]
Hi, i don't know if i'm doing something wrong since my problem seems more like a wrong configuration than a bug, but when i run i18n init, it creates the locale folder all lower case:

    $ bin/cake i18n init
    Please specify language code, e.g. `en`, `eng`, `en_US` etc.
    > pt_BR
    What folder?
    [/var/www/main/src/Locale] > 
    Creating file /var/www/main/src/Locale/pt_br/default.po
    Wrote `/var/www/main/src/Locale/pt_br/default.po`
    ...
    Generated 3 PO files in /var/www/main/src/Locale/pt_br/

That `pt_br` is a problem because the loader expect `pt_BR`

    >>> $loader = new Loader('default','pt_br','po');
    >>> debug($loader->translationsFolders())
    /vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code (line 1)
    ########## DEBUG ##########
    [
    	(int) 0 => 'var/www/main/src/Locale/pt_BR/',
    	(int) 1 => 'var/www/main/src/Locale/pt/'
    ]
    ###########################
    >>> is_file( "/var/www/main/src/Locale/pt_BR/default.po" )
    => false

What this can be?

**Comment by LACabeza** [comment]
i'm using the latest cakephp version and debian 7.

**Comment by markstory** [comment]
Looks like a mistake to me as well.

**Comment by markstory** [comment]
Pull request open. See #7896
