### ISSUE TITLE
Problem with _serialize and return 'domdocument'

### ISSUE THREAD

**Issue by rlems** [cakephp/cakephp#7897]
In version 2.6.8 I found that when you return a `_serialize` value in your `viewVars` the `_serialize()` function in `lib/Cake/View/XmlView.php` will return:

    Xml::fromArray($data, $options)->asXML();`
Earlier in the `_serialize()` function it does the following:

	if (isset($this->viewVars['_xmlOptions'])) {
		$options = $this->viewVars['_xmlOptions'];
	}
for the `_xmlOption` you can pass an array which can contain the 'return' value, specifying what to return (SimpleXML, DOMDocument). I set this value to 'domdocument' and get the following error:
**Fatal error: Call to undefined method DOMDocument::asXML() in lib/Cake/View/XmlView.php on line 145**
DOMDocument doesn't have a function `asXML()`.

As a solution I would propose to return 

    Xml::fromArray($data, $options)->saveXML()
if the `_xmlOption` contains a 'return' key which value is 'domdocument', since that is how I get the right XML from a DOMDocument.

**Comment by markstory** [comment]
Closing as a pull request is up now.
