### ISSUE TITLE
Cache limiters normally set by PHP's session.cache_limiter option are never sent

### ISSUE THREAD

**Issue by GMMan** [cakephp/cakephp#7906]
I've been playing around with a project that I've inherited, and one of the things that aggregated me a lot was pages are always being cached on the browser, requiring me to refresh every time after I change some entry to see the changes. The original project on production (running on the ancient CakePHP version 2.1.1) behaved fine, while my local copy (upgraded to CakePHP version 2.7.3) was not. Looking at the difference in headers, I noticed that the production version was sending headers that were the result of PHP's `nocache` cache limiter, while no such thing was being sent for my local version. Despite trying different values for the option in my php.ini, nothing happened.

Filing through CakePHP's source code, I noticed in `CakeSession::_startSession()`, it was setting the cache limiter to `must-revalidate` (an invalid value, mind you, as pointed out by commit 4a6159c), and hence overriding what I have set in php.ini. The reason for overriding the cache limiter was apparently for IE <= 8 to work properly, but I don't use that old of a version of IE (and ideally, neither should anyone else). I think this overriding should be configurable rather than enforced, and if needed, perhaps some smart detection for the IE version and any possible workarounds so other browsers' caching behavior aren't affected.

(On the topic of `must-revalidate`, it really isn't a valid value, at least not one that does what people think it's doing. Looking through PHP's source code, there is no reference to it for setting cache limiters, and the value behaves the same as any invalid value (such as `none`), by not sending any cache limiter headers at all.)

**Comment by ADmad** [comment]
> I think this overriding should be configurable rather than enforced

As you see in the commit you pointed out setting of that invalid value has already been removed.

It's unclear to me what change you are expecting.

**Comment by ADmad** [comment]
Sorry, I see that it was added back and some point and does exist again in current [2.7 code](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/CakeSession.php#L693).

**Comment by ADmad** [comment]
The commit which added it back also has discussion https://github.com/cakephp/cakephp/commit/2fd15b6c7e21a8fcc29d66e759b8ec741fea81d1

**Comment by markstory** [comment]
> but I don't use that old of a version of IE (and ideally, neither should anyone else).

A lofty goal, but unrealistic for many folks.

> I think this overriding should be configurable rather than enforced, and if needed, perhaps some smart detection for the IE version and any possible workarounds so other browsers' caching behavior aren't affected.

This sounds far more reasonable to me. Having a config option define the headers to use follows patterns we use elsewhere.

**Comment by markstory** [comment]
Configuration option added in #8067 targeting 2.8.0
