### ISSUE TITLE
i18n validation

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#7909]
Hi,

Should validation work when saving input for multiple languages at the same time? I could not find any mention of this on the docs and my attempts (use the i18n field name, field name + language prefix) failed. Am i missing something?

Thanks!

**Comment by lorenzo** [comment]
There is nothing automatic right now. It depends on what exactly you want to validate. What are you doing?

**Comment by urionlinejudge** [comment]
Hmm, I have 3 inputs for the 'title' field in 3 distinct languages plus other fields. I want to validate if they are empty, maxLength,, things like that.

**Comment by dereuromark** [comment]
@urionlinejudge You should also always include your exact CakePHP version you are using. And maybe also be more specific in your ticket itself, like what did you try so far, what does the code currently look like? This will make it easier to answer you.

**Comment by urionlinejudge** [comment]
Sure! Sorry for that. I am using version 3.1.6 obtained via composer.

The input fields are: 
echo $this->Form->input('pt.title');
echo $this->Form->input('es.title');
echo $this->Form->input('en.title');

My add function looks like this:

```
public function add()
    {
        $news = $this->News->newEntity();

        if ($this->request->is('post')) {
            $translations = $this->request->data;
            
            foreach ($translations as $language => $data) {
                $news->translation($language)->set($data, ['guard' => false]);
            }

            if ($this->News->save($news)) {
                $this->Flash->success(__('The news have been published!'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The news could not be published! Please, try again.'));
            }
        }

        $this->set(compact('news'));
    }
```

The news entity is using TranslateTrait. I have also included in the inicialization of the NewsTable class:

```
$this->addBehavior('Translate', [
    'fields' => [
        'title',
        'description'
    ],
    'translationTable' => 'NewsI18n'
]);
```

Now, for the validation:

```
$validator
	->requirePresence('title', 'create')
	->notEmpty('title')
	->add('title', [
	    'length' => [
	        'rule' => ['minLength', 10],
	        'message' => 'Titles need to be at least 10 characters long.',
	    ]
	]);
```

I already tried title, pt.title, _translations.pt.title but the validation fails for not finding the field.

**Comment by markstory** [comment]
You might be able to use [nested validators](http://book.cakephp.org/3.0/en/core-libraries/validation.html#nesting-validators) to do what you need. However, #7532 will make displaying validation errors in generated forms difficult.

**Comment by urionlinejudge** [comment]
Ok, I have tried this, but the validation is now ignored when I force the input to be invalid, i.e. the data is saved and no error is detected. Is there anything else I could do? 

```
public function validationDefault(Validator $validator)
{
    $validator
        ->add('id', 'valid', ['rule' => 'numeric'])
        ->allowEmpty('id', 'create');

    // I18n Validator
    $I18nValidator = new Validator();

    $I18nValidator
        ->requirePresence('title', 'create')
        ->notEmpty('title')
        ->add('title', [
            'length' => [
                'rule' => ['minLength', 10],
                'message' => 'Titles need to be at least 10 characters long.',
            ]
        ]);

    $I18nValidator
        ->requirePresence('description', 'create')
        ->notEmpty('description')
        ->add('description', [
            'length' => [
                'rule' => ['minLength', 50],
                'message' => 'News must have a substantial description.'
            ]
        ]);

    // Connect the nested validators
    $validator->addNested('pt', $I18nValidator);
    $validator->addNested('es', $I18nValidator);
    $validator->addNested('en', $I18nValidator);

    return $validator;
}
```

My suggestion is, if possible, that the validation rules are also applied to the fields defined by i18n as if they were local (which makes more sense), instead of having to manually do something like this.

**Comment by markstory** [comment]
@urionlinejudge What you're suggesting does sound more ideal, but we're quite a ways off from that right now.

I think TranslateBehavior might be able to use the `Model.buildValidator` hook to create nested rules out of the rules defined in the model, but there are most certainly some sharp edges hiding out there.

**Comment by urionlinejudge** [comment]
@markstory I also tried to use the `buildValidator` but the validation for the i18n fields seems to be ignored as well. I do not know what I could do in this case.

**Comment by lorenzo** [comment]
@urionlinejudge how do you know the validations rules are being ignored?

**Comment by lorenzo** [comment]
Sorry, I meant the "application rules" (from buildRules)

**Comment by urionlinejudge** [comment]
@lorenzo Both are being ignored because I am providing input with less characters and empty values for descriptions and the records are being saved this way. Thus, I assume the validation is simply being bypassed somehow.

**Comment by markstory** [comment]
Closing as this works as of #9225 (3.3.0)
