### ISSUE TITLE
3.1.x i18n output of non localized string error

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#7912]
Hello!
I have the following code:
```php
echo __dx('enum', 'UserStatus', 'verified');
```
And it's generating - `msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR`
Why it doesn't render unlocalized message like __() ?
Should I really create translation for those message?
P.S. my locale is ru_RU. And i don't have translations for those message in po/mo.

**Comment by lorenzo** [comment]
I justo tried your example. I have no translations at all in my project. This is what I got:

<img width="530" alt="screen shot 2015-12-27 at 18 25 20" src="https://cloud.githubusercontent.com/assets/37621/12011278/52d5e30c-acc7-11e5-92fd-13e652889ca8.png">

Are you sure you have no translations for that string? Not even in the default.po file?

**Comment by codercms** [comment]
@lorenzo i don't have the default.po file, but i have the enum.po file with translations for other enum values.

**Comment by lorenzo** [comment]
Can you share the content of that file?

**Comment by codercms** [comment]
@lorenzo sure
[enum.zip](https://github.com/cakephp/cakephp/files/72760/enum.zip)

**Comment by codercms** [comment]
@lorenzo sure
[enum.zip](https://github.com/cakephp/cakephp/files/72762/enum.zip)

**Comment by lorenzo** [comment]
So, the string is actually translated... The problem is that the string was not translated with the context:

```
#: Model/Enum/UserStatus.php:15
msgctxt "UserStatus"
msgid "verified"
msgstr "Проверен"
```

I suggest using the extract tool for generating the `.pot` file and then use `poedit` for translating the mesages

**Comment by codercms** [comment]
@lorenzo okay, thanks, i will use `poedit` for translation.
