### ISSUE TITLE
Selecting columns via an association object when using a join table

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7913]
According to the documentation I can select columns via an association object.
The code in /Model/Table was all baked.
My database works fine, because if I run a WebsitesTable->get($id, contain...) and contain the Products, then I get all the Products returned. Its only when I try to filter out the fields, that I get this error.

``` php
// in src/Controller/WebsitesController.php
$website = $this->Websites->find()->where(['id' => $id])
                ->select($this->Websites)
                ->select($this->Websites->Products)
                ->contain(['Products']);
```
``` php
// in src/Model/Table/WebsitesTable.php
public function initialize(array $config)
    {
        // ...
        $this->belongsToMany('Products', [
            'foreignKey' => 'website_id',
            'targetForeignKey' => 'product_id',
            'joinTable' => 'products_websites'
        ]);
    }
```
``` php
// in src/Model/Table/ProductsTable.php
public function initialize(array $config)
    {
        // ...
        $this->belongsToMany('Websites', [
            'foreignKey' => 'product_id',
            'targetForeignKey' => 'website_id',
            'joinTable' => 'products_websites'
        ]);
    }
```

My join table:
![image](https://cloud.githubusercontent.com/assets/6759894/12011230/ac51c092-acc5-11e5-93f1-1ff202c8c994.png)

I get this error: 
![image](https://cloud.githubusercontent.com/assets/6759894/12011225/7ced8408-acc5-11e5-92cc-0709363800d0.png)

**Comment by lorenzo** [comment]
You can, when using the `fields` option of contain of the query builder closure:

```php
$website = $this->Websites->find()->where(['id' => $id])
                ->select($this->Websites)
                ->contain(['Products' => ['fields' => $this->Websites->Products]]);
```

```php
$website = $this->Websites->find()->where(['id' => $id])
                ->select($this->Websites)
                ->contain(['Products' => function ($q) {
                    return $q->select($this->Websites->Products);
                }]);
```

You can only use `select()` directly for `belongsTo` and `hasOne` associations, when using the `join` strategy.

**Comment by half2me** [comment]
Thanks! Could we add this to the documentation? Or better yet, can we (in the absence of the fields parameter) automatically select all the fields in the Table?

**Comment by lorenzo** [comment]
Sure, do you want to add it yourself in the docs repo?

Yes, the reason is that `belongsToMany` and `hasMany` associations require a second `SELECT` clause for fetching the results. For this reason, the columns cannot be placed in the main query, but in the query for fetching the association.

**Comment by half2me** [comment]
@lorenzo I tried your code (the first one) and got the following error:
![bug2](https://cloud.githubusercontent.com/assets/6759894/12011312/c0429c0e-acc8-11e5-8fb0-2b609d52071d.png)

**Comment by lorenzo** [comment]
I suggest you try the second one... I'm afraid the first one I added has a mistake... you can open a new ticket with that error if you prefer

**Comment by half2me** [comment]
@lorenzo The seccond one works, but what I am trying to do is filter out which rows are selected.

I have working code:
``` php
$website = $this->Websites->find()->where(['id' => $id])
                ->select($this->Websites)
                ->contain(['Products' => ['fields' => $this->Websites->Products]]);
```
But my problem is that I get lots of data back, which I don't need. And since I'm working on an API, and I just _serialize the data I get, it would be nice to be able to select which fields are selected not only in the primary model, but also in associated models.
I tried using:
```
$website = $this->Websites->find()->where(['id' => $id])
            ->select('id', 'Products.ean')
            ->contain(['Products' => function ($q) {
                return $q->select($this->Websites->Products);
            }]);
```
But this will return all rows from Products. Can I filter this out some other way?

**Comment by lorenzo** [comment]
What columns do you want to select?

**Comment by half2me** [comment]
@lorenzo Products.ean, and Products.size
I tried: 
``` php
->contain(['Products' => function($q) {
                    return $q->select('Products.id');
                }]);
```
But it still returns all columns in Products

**Comment by lorenzo** [comment]
`return $q->select(['Products.ean']);` will only return that column. Can you show the code, generated queries and result?

**Comment by half2me** [comment]
@lorenzo Sure!

Here is the result:
![resultbug](https://cloud.githubusercontent.com/assets/6759894/12011482/52f9981c-accf-11e5-81b2-f35422d21c59.png)

And the SQL Log:
![sql1](https://cloud.githubusercontent.com/assets/6759894/12011490/a118c0d6-accf-11e5-989f-513a126f77d7.png)
![sql2](https://cloud.githubusercontent.com/assets/6759894/12011491/a11c9e86-accf-11e5-9257-823412c2eb9a.png)
![sql3](https://cloud.githubusercontent.com/assets/6759894/12011492/a122b9c4-accf-11e5-81a2-da7e9a6d1d10.png)
