### ISSUE TITLE
Can I catch query exceptions?

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7914]
I would like to catch exceptions like such:

``` php
// in my controller
use Cake\Core\Exception\Exception;

public function myAction($id = null)
{
        $data = [];
        try {
            $people = $this->People->get($id);
            $data['result'] = $people;
        }
        catch(Exception $e){
            $data['error']['code'] = $e->getCode();
            $data['error']['message'] = $e->getMessage();
        }
        $this->set('data', $data);
        $this->set('_serialize', 'data');
    }
```

Unfortunately I can't catch the exception, I get an error page rendered instead. Is there some way I can make this work?

**Comment by lorenzo** [comment]
Yes, you jus need to catch the right exception. use `catch (\Exception $e)` so you can check the type of the exception you are getting.

**Comment by half2me** [comment]
@lorenzo Geez, thanks! I thought that if I specified which exception I want in the 'use', then it would automatically choose that. :)

**Comment by lorenzo** [comment]
That's how it works, but you need to name the right exception class

**Comment by half2me** [comment]
I just use the generic core Exception, since all other Exceptions extend it. For my purposes (getMessage, and getCode) its enough...
