### ISSUE TITLE
patchEntity with object instead of object

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/cakephp#7919]
Hello,
I made this mistake:

    $order = $this->Orders->patchEntity($order, [
         'agplan' => $this->Agplans->newEntity(['product_id' => $product->id]),
 				]);

instead of `$this->Agplans->newEntity(['product_id' => $product->id])->toArray()` and the marshaller didn't report any error. Is it normal?

I think an error was generated in 3.0.

Regards,
Alain

**Comment by markstory** [comment]
Yes no error should be generated. Your 'data' was wrapped in an array which is enough to satisfy the patchEntity() type hints. After that the Marshaller has to treat all data as 'normal' and expected. It handles user supplied data, which can have totally arbitrary format and structure so it should ideally never emit an error.

**Comment by 2ndGAB** [comment]
Hello Markstory,
If I discovered the error, it's because the associated is not created if I don't add `toArray()`.
