### ISSUE TITLE
(ORM) query()->update() giving error

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7922]
I am just trying out the example code in the documentation for my own data:

``` php
$query = TableRegistry::get('Products')->query();
$result = $query->update()
  ->set(['ean' => '111111111'])
  ->where(['id' => '1'])
  ->execute();
```
I get the following error:
![error you cannot call all on a non select query use execute instead](https://cloud.githubusercontent.com/assets/6759894/12042909/fc5c2b8e-ae7f-11e5-8f36-27df1d278fa9.png)
I don't understand, I am not using 'all' I am using 'execute'. Why doesn't it work?

**Comment by lorenzo** [comment]
Could you open this bug in the debugkit repo please?

**Comment by markstory** [comment]
This issue was moved to cakephp/debug_kit#397
