### ISSUE TITLE
Bake All when Primary Key is named <tablename>_id

### ISSUE THREAD

**Issue by rakefs** [cakephp/cakephp#7923]
If you create a table and name the primary key with the convention <tablename>_id then when you "bake all" the automagic machinations will think that this table is associated to itself.

For example, the following tables will all have some belongsTo associations in their Table classes, similar to $this->belongsTo('Bookmarks', [ 'foreignKey' => 'bookmark_id', 'joinType' => 'INNER' ]);

Note that the Primary Keys used below have been changed from the originals:
CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created DATETIME,
    modified DATETIME
);
CREATE TABLE bookmarks (
    bookmark_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(50),
    description TEXT,
    url TEXT,
    created DATETIME,
    modified DATETIME,
    FOREIGN KEY user_key (user_id) REFERENCES users(user_id)
);

CREATE TABLE tags (
    tag_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    created DATETIME,
    modified DATETIME,
    UNIQUE KEY (title)
);

CREATE TABLE bookmarks_tags (
    bookmark_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (bookmark_id, tag_id),
    FOREIGN KEY tag_key(tag_id) REFERENCES tags(tag_id),
    FOREIGN KEY bookmark_key(bookmark_id) REFERENCES bookmarks(bookmark_id)
);

**Comment by markstory** [comment]
That is intended behavior. If you want to deviate from the CakePHP conventions, you won't be able to use `bake all` instead you can build your models first with `bake model` and from there bake the controllers and templates.
