### ISSUE TITLE
bootstrap_cli.php can`t define in plugin when i want add a bake template

### ISSUE THREAD

**Issue by visonforcoding** [cakephp/cakephp#7924]
Today i want to add a bake controller action template in my plugin .I read the doc and do as it say.
when define the bake event . i found i must add the event code in the application bootstrap_cli.php.
i think it`s not convenience.the bake theme is in plugin .but event code must define in application .
is there a way to solve it?

**Comment by markstory** [comment]
The event bootstrapping doesn't _have_ to be in bootstrap_cli.php. The documentation suggests that as it is reasonable place that will exist for everyone.

If your theme is in a plugin you could also bind the events in your plugin's bootstrap file, which can be loaded with the plugin.

```php
// in app config/bootstrap.php
Plugin::load('MyBakeTheme', ['bootstrap' => true]);
```

The plugin's bootstrap could look like:

```php
if (PHP_SAPI === 'cli') {
  // Attach bake events here.
}
```
I can update the documentation to be clearer on other locations for the bake event bindings.

**Comment by visonforcoding** [comment]
@markstory cool! I can go on my plugin .thank you ,thank everyone in cake team.
