### ISSUE TITLE
RFC: Configure::get()

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7925]
Would this make sense for the core? https://gist.github.com/ionas/62fc3f7f00a1f291d2c5

**Comment by markstory** [comment]
That would probably cause a lot of apps to break. I think having a way to get or fail a config option could be useful to ensure that critical configuration values do exist.

**Comment by bravo-kernel** [comment]
:tractor:

**Comment by ionas** [comment]
Why would it cause apps to break? `get()` does not exist yet. It is specifically a shorthand to check if a value is defined and else crash the app (because it would not run without the configuration value setup)?

**Comment by markstory** [comment]
Derp, I misread the method name as `Configure::read()` my mistake.

**Comment by ionas** [comment]
PR: https://github.com/cakephp/cakephp/pull/7935

**Comment by jhli** [comment]
Is 'consumeOrFail()' used often?
Should I setup a PR, too?
Makes all(?) the direct read methods consistent?

**Comment by markstory** [comment]
Lets wait and see if people need consumeOrFail(). Its easier to add new methods than it is to remove un-used ones.

**Comment by jhli** [comment]
I meant is consume() used often. But I do agree!
