### ISSUE TITLE
CounterCache behavoiur with nested associations

### ISSUE THREAD

**Issue by Xymanek** [cakephp/cakephp#7926]
Consider this:
`Polls HasMany Options`
`Options HasMany Votes`
Both Polls and Options have `votes_count` field that needs to be updated when I create or delete a vote. CounterCache properly updates immediate parent (`Options`), however I couldn't find a way for it to work with grandparent (`Polls`). Whichever way I try to configure it, it looks for `Options.Polls` field to update.

### What I tried
```php
$this->addBehavior('CounterCache', [
    'Options' => ['votes_count'], // Fine
    'Options.Polls' => ['votes_count'] // Looks for Options.Polls field
]);
```
```php
$this->addBehavior('CounterCache', [
    'Options' => [
        'votes_count', // Fine
        'Polls' => ['votes_count'] // Again looks for Options.Polls field
    ]
]);
```
P.S. I'm adding behaviour on `Votes` table

**Comment by lorenzo** [comment]
I don't understand this. The Counter cache behavior is used only for one-level associations. Just add the behavior to the `Options` table

**Comment by Xymanek** [comment]
I thought about that but won't that simply count number of options, while I need the sum of votes for all options?

**Comment by Xymanek** [comment]
Also CounterCache uses updateAll (line 159 `$assoc->target()->updateAll([$field => $count], $updateConditions);`) therefore CounterCache isn't called on parent table

**Comment by lorenzo** [comment]
No, it is not. Counter cache works for what it is advertised, not cascading updates, not nested association sums. I suggest you to implement your own behavior out of the original code, so that it would satisfy your needs.
