### ISSUE TITLE
RFC 3.x: Add HTTP 503 ServiceUnavailableException

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7927]
Useful if you write applications that depend on multiple services and/or may go into maintenance mode.

See: https://gist.github.com/ionas/e5ff6a523dc20c8beae1

**Comment by ADmad** [comment]
Having it in your app is just as good.

**Comment by jhli** [comment]
Anyone in favour, else I'll close it.

**Comment by josegonzalez** [comment]
:+1: Only so that people stop asking for us to implement the 400/500 http status codes as exceptions.

**Comment by jrbasso** [comment]
:+1: This is useful in the microservice/load balancer world. This is a simple thing and will avoid hundreds of blogs doing the same thing in a different way, confusing developers.

**Comment by ionas** [comment]
I think the pro argument is that newbies would use HTTP500 (InternalServerError) instead of 503... this might at least make it obvious what to use.

**Comment by markstory** [comment]
@ionas Having a few more exception classes sounds good to me. I agree with @jrbasso that having a simple will save the community lots of work coming up with different creative solutions.

**Comment by ADmad** [comment]
Closing as PR is opened.
