### ISSUE TITLE
Allow to set guard to false when calling newEntity() and patchEntity()?

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#7928]
I can do this [directly on the entity object](http://book.cakephp.org/3.0/en/orm/entities.html#avoiding-mass-assignment-protection) but I can't do this when contructing entities using the tables `newEntity()` method. Any specific reason why I can't do this? I don't see how this would affect security, you'll still have to do it explicitly. My personal use-case is constructing entities in tests using the newEntity() method.

**Comment by steefaan** [comment]
Maybe you're searching for: http://book.cakephp.org/3.0/en/orm/saving-data.html#changing-accessible-fields ?

**Comment by markstory** [comment]
Use the `accessibleFields` option as @steefaan pointed out.

**Comment by JelmerD** [comment]
I would like to re-open this issue. Because I have often code like this:

```
// user insted data
$message = $this->Messages->patchEntity($message, $this->request->data);
// my own un-hijackable data
$message = $this->Messages->patchEntity($message, [
    'user_id' => $this->Permission->user('id'),
    'created' => new Date(),
], [
    'accessibleFields' => [
        'user_id' => true,
        'created' => true,
    ]
]);
```

I don't want to have to change the 'accessibleFields' option every single time I am changing my own inserted data. I would like to be able to set `guard` to `false`, to just simply skip the guarding of the fields. I think it makes sense to have this option as `set()` has it as well.

**Comment by markstory** [comment]
Why are you using `patchEntity()` in that scenario? If you have trusted data you can use

```php
$entity->set(['user_id' => $this->Permission->user('id'), 'created' => new Date()]);
```

**Comment by JelmerD** [comment]
Did not know to use it like that. Thanks!
