### ISSUE TITLE
Add uuid data type support for 2.x

### ISSUE THREAD

**Issue by roll4life** [cakephp/cakephp#7929]
I've been doing some testing with PostgreSQL native uuid datatype vs varchar(36) and have found that uuid datatype has substantial performance and storage improvements over varchar(36).  3.x supports the uuid datatype already and I think that adding this functionality 2.x would be fairly straight forward.  In my testing with PostgreSQL getting this working has required two changes to the cake core.

Add uuid to the list of supported data types the $columns array Postgres.php line 71
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/Database/Postgres.php#L71
<pre>
                'inet' => array('name' => 'inet'),
                'uuid' => array('name' => 'uuid')
</pre>

Modify the string case in the value function in DboSource.php line 3467 to have blank strings '' marshall as NULL.
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/DboSource.php#L347
<pre>
                        case 'boolean':
                                return $this->_connection->quote($this->boolean($data, true), PDO::PARAM_BOOL);
                        case 'string':
                                if ($data === '') {
                                        return 'NULL';
                                } else {
                                        return $this->_connection->quote($data, PDO::PARAM_STR);
                                }
                        case 'text':
                                return $this->_connection->quote($data, PDO::PARAM_STR);
</pre>

I have not written any unit tests for this yet, but I would be happy to create a pull request and write some tests if others agree that this would be a useful enhancement to the 2.x branch, and that the proposed approach makes sense.  I have tested the code against a moderate size cakephp 2.x project that uses a PostgreSQL database, and have not encountered any issues yet.

**Comment by markstory** [comment]
Are there any considerations that need to be taken for FormHelper? Or the SchemaShell?

**Comment by dereuromark** [comment]
With varchar(36) I hope you mean char(36). Only the latter of those should ever be used.
If you actually compared to varchar(36) than your findings are invalid.

It would be even faster to use binary32 or better yet binary16, but that is not that trivial.
Refs https://github.com/cakephp/cakephp/issues/7013
That would be the best approach IMO - and to deprecate char usage alltogether.

**Comment by roll4life** [comment]
@markstory I have not looked into potential impact that this would have on form helper or schema shell. If someone can point me in the right direction, I can take a look.  I am not very familiar with the code for either of these features.  

@dereuromark PostgreSQL has a native uuid datatype http://www.postgresql.org/docs/current/static/datatype-uuid.html
the performance differences that I noticed were mostly in the time that it took to index "uuid" columns  uuid datatype took 50% less time to index and the amount of space required to store the indexes varchar(36) required about 25% more disk space to store the indexes this would be pretty much the same for char, and text.

here is a good article that looks at uuid datatype vs text in postgres
http://www.simononsoftware.com/how-to-store-uuids-in-postgresql/
as for varchar vs char, when using the cakedc migrations plugin, if you specify that you want a column type string with length 36, it will create a varchar(36) column.  I believe that char(36) and varchar(36) have identical performance in postgres, the difference being that char always allocates 36 characters worth space, meaning that it will have more storage requirements for columns where cakephp marshalls a column that should be null as ''

In the article above the author explains that:
char is almost never recommended in postgres.  Both char and varchar are suboptimal in PostgreSQL when compared to text
http://blog.jonanin.com/2013/11/20/postgresql-char-varchar/

All that to say, I agree that char should be deprecated, for postgres varchar should be deprecated as well in favor of text.  One of the problems with text (at least in cakephp 2.x) is that the form helper does automagic based on the database type, so if you bake a project full of text fields you will end up with a bunch of text input, rather than form fields.

**Comment by lorenzo** [comment]
This had a pull request already merged
