### ISSUE TITLE
3.1: DISTINCT issues

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7945]
When upgrading a 2.x find(all) I found the DISTINCT functionality not working as documented:
http://book.cakephp.org/3.0/en/orm/query-builder.html#selecting-data
It silently ignores the array argument `distinct(['OnlineActivities.user_id'])`.
I also tried as string: `->distinct('OnlineActivities.user_id')`.
No DISTINCT word in the resulting query.

It only works without argument:

```
		$records = $this->find()
			->where(['OnlineActivities.modified >' => $time])
			->contain(['Users'])
			->select(['OnlineActivities.user_id', 'OnlineActivities.id', 'OnlineActivities.session_id', 'OnlineActivities.created', 'OnlineActivities.modified', 'OnlineActivities.last_page_url', 'OnlineActivities.clicked_from'])
			->distinct() // Only works without field name
			->order(['OnlineActivities.modified'=>'desc']);
```
But without field name it does a distinct on all records 

    DISTINCT `OnlineActivities`.`id` AS `OnlineActivities__id`, 
    `OnlineActivities`.`session_id` AS `OnlineActivities__session_id`, 
    `OnlineActivities`.`user_id` AS `OnlineActivities__user_id`, ...

whereas the 2.x query did just `DISTINCT('OnlineActivities.user_id')`.

So I suspect that there is a bug when working with specific distinct fields.
And if ignored for some reason, it should throw an exception maybe.
Just silently ignoring the distinct setting makes the issue not visible to the developer.

PS: The query before was
```php
		$records = $this->find('all', [
			'conditions' => ['OnlineActivities.modified >' => $time],
			'contain' => ['Users'],
			//'fields' => ['DISTINCT(OnlineActivities.user_id)', 'OnlineActivities.id', 'OnlineActivities.session_id', 'OnlineActivities.created', 'OnlineActivities.modified', 'OnlineActivities.last_page_url', 'OnlineActivities.clicked_from'], // Commented out to work
			'fields' => ['OnlineActivities.user_id', 'OnlineActivities.id', 'OnlineActivities.session_id', 'OnlineActivities.created', 'OnlineActivities.modified', 'OnlineActivities.last_page_url', 'OnlineActivities.clicked_from'], // Removed DISTINCT part
			'order' => array('OnlineActivities.modified'=>'desc'),
		])->distinct('OnlineActivities.user_id'); // Only added this line
```
I slightly modified it first, but it didnt work, so I completely rewrote it to 3.x style.

**Comment by lorenzo** [comment]
Are you using Postgres? Otherwise I don't think you are doing what you think you are doing :P

What is the generated query she passing an array to distinct() ?

**Comment by dereuromark** [comment]
MySQL.
The generated SQL then is just

    'SELECT `OnlineActivities`.`user_id` AS `OnlineActivities__user_id`, `OnlineActivities`.`id` AS `OnlineActivities__id`,  ....

So no DISTINCT in there at all.

**Comment by lorenzo** [comment]
Please show the full query

**Comment by dereuromark** [comment]
```sql
SELECT `OnlineActivities`.`user_id` AS `OnlineActivities__user_id`, `OnlineActivities`.`id` AS `OnlineActivities__id`, `OnlineActivities`.`session_id` AS `OnlineActivities__session_id`, `OnlineActivities`.`created` AS `OnlineActivities__created`, `OnlineActivities`.`modified` AS `OnlineActivities__modified`, `OnlineActivities`.`last_page_url` AS `OnlineActivities__last_page_url`, `OnlineActivities`.`clicked_from` AS `OnlineActivities__clicked_from` FROM `online_activities` `OnlineActivities` LEFT JOIN `users` `Users` ON `Users`.`id` = (`OnlineActivities`.`user_id`) WHERE (`OnlineActivities`.`modified` > :c0) GROUP BY `OnlineActivities`.`user_id`  ORDER BY `OnlineActivities`.`modified` desc'
```

I see that it adds it as a group by clause. But shouldnt that happen with a `->group($field)` clause?

**Comment by lorenzo** [comment]
It happens when you pass arguments to distinct(). That is the only way to emulate the feature in mysql

**Comment by dereuromark** [comment]
Makes sense, thank you for the clarification.

**Comment by lorenzo** [comment]
No problem :)

**Comment by dereuromark** [comment]
I got confused by the comment in the docs example
```php
// Results in SELECT DISTINCT country FROM ...
$query = $articles->find();
$query->select(['country'])
    ->distinct(['country']);
```
Maybe we can add sth to the docs or modify it to say that here it will be a GROUP BY clause for single fields if there are more fields selected.

**Comment by lorenzo** [comment]
Sure, that would be nice
