### ISSUE TITLE
Joins in Cakephp find doesnot fetching data across multiple databases

### ISSUE THREAD

**Issue by vinithac** [cakephp/cakephp#7948]
Hi I'm using joins to fetch data across multiple database. Here my scenario goes..

I have 2 database connections in database.php

class DATABASE_CONFIG {    
   public $default = array(
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'login' => 'Testing',
        'password' => 'Test',
        'database' => 'dynamic_db1',
        'prefix' => '',
        'encoding' => 'utf8',
    );
    
    public $second_db = array(
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'login' => 'Testing',
        'password' => 'Test',
        'database' => 'dynamic_db2',
        'prefix' => '',
        'encoding' => 'utf8',
    );  

Jobs table locates in dynamic_db1
users table locates in dynamic_db2
 
 My query goes like this

$users = $this->Jobs->find('all',array(
            'joins' => array(                
                array(
                    'table' => 'users',
                    'alias' => 'User',
                    'type' => 'left',
                    'fields' => array('id', 'name'),
                    'conditions' => array(
                        'Jobs.created = User.id'
                    )
                )                
            ),
            "conditions" => array('id'=>1))); 

   On execution  It stating error like

   Base table or view not found :1146 Table 'dynamic_database1.users' doesn't exist.

I have created users model in Models there I have stated 

class users extends AppModel {
    public $useDbConfig = 'second_db';   
}

Where as it fetching data from dynamic_db2 while using bindmodel. Why it is not working for Joins ??

**Comment by ADmad** [comment]
> Why it is not working for Joins ??

Because custom joins don't use your model. In your joins array instead of `'table' => 'users'` use `'table' => 'dynamic_db2.users'

**Comment by vinithac** [comment]
Thanks for your quick response.

Yes by placing database name prefixed with table it works.
But I need to change across entire application.
I'm looking for a solution while building query why doesn't it looks for database settings where as it is checking for bindmodel ?

**Comment by vinithac** [comment]
Can we change any settings in library DBosource file while building query? because implementing this change across entire application is a tedious process.

**Comment by ADmad** [comment]
> Can we change any settings in library DBosource file while building query?

No you can't. Instead of directly using `'joins'` config use model associations to generate joins if you want your model config to be used.
