### ISSUE TITLE
Installing cakephp found few Errors on default setup

### ISSUE THREAD

**Issue by superstarrajini** [cakephp/cakephp#7955]
cakedev@uber1:~/webprojects/srccake$ sudo php composer.phar create-project --prefer-dist cakephp/app appleapp1
Installing cakephp/app (3.1.2)
  - Installing cakephp/app (3.1.2)
    Loading from cache

Created project in appleapp1
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.1.6 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.5 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.4 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.3 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.2 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.1.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - Installation request for cakephp/cakephp ~3.1 -> satisfiable by cakephp/cakephp[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6].

**Comment by ADmad** [comment]
> cakephp/cakephp 3.1.6 requires ext-intl * -> the requested PHP extension intl is missing from your system

The error message clearly states what the problem is. You need the `intl` extension installed.

**Comment by superstarrajini** [comment]
Thankyou ADmad

**Comment by superstarrajini** [comment]
$Apache: sudo service apache2 restart
$sudo apt-get install php5-intl

**Comment by DiegoProtec** [comment]
thank you so much!!!

**Comment by LucasMMota** [comment]
This may seem trivial, but in fact about 2 months ago some clever guys made changes in brew repository, so doing just:
brew install php71-intl
will show you error with message that such recipe doesn’t exists. Also XAMPP comes without intl extension so is there any working solution which does not require full and manual php compilation?

Fortunately, there is. There is temporary fix in another brew repo, so all you have to do is:
brew tap kyslik/homebrew-php
brew install kyslik/php/php71-intl

And this works. Really. Enjoy.
src="http://blastar.biz/2018/04/14/how-to-enable-php-intl-extension-for-php-7-1-using-xampp-on-macos-high-sierra/"

**Comment by ADmad** [comment]
> Also XAMPP comes without intl 

XAMPP does have `intl` extension but it's not enabled by default. So you just have to enable it.

Regarding the macos/brew problem please contact the relevant maintainers.

**Comment by hiten2112** [comment]
not working at all

**Comment by markstory** [comment]
homebrew should install intl by default if you `brew update`. My installs of `php@72` include intl with no additional options/flags.
