### ISSUE TITLE
Mysql Colnum Type is decimal 9,2，but puout number is int

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#7957]
Mysql Colnum Type is decimal 9,2

###table:orders

id(int 11)    price(decimal 9,2)
22              78.00

but, use $data = $this->Orders->find('all')->first();

the entity $data->price is : 78  ， why not display 78.00?

**Comment by lorenzo** [comment]
How are you formatting the number?

**Comment by lorenzo** [comment]
The way PHP works is that it will output the numbers without decimals if there are no decimals. Use the `Number` class or the `Number` helper for formatting your numbers in the view.
