### ISSUE TITLE
Allow additional template variables in submitContainer

### ISSUE THREAD

**Issue by Holt59** [cakephp/cakephp#7958]
Currently, it is possible to [add additional variables to templates](http://book.cakephp.org/3.0/en/views/helpers/form.html#adding-additional-template-variables-to-templates) for all input containers **except** hidden inputs and submit inputs due to [this conditional](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L1021) statement.

Could it be possible to support additional variables for the `submitContainer`  template? 

I started writing a patch [here](https://github.com/Holt59/cakephp/tree/submit-container-additional-vars) but don't know if it is an acceptable pull-request for Cake.

**Comment by dereuromark** [comment]
I think it is worth opening a concrete PR with your suggested changes in https://github.com/cakephp/cakephp/compare/master...Holt59:submit-container-additional-vars .
This makes it more easy to discuss the value of it. You can then close this ticket once the PR is open and linked to this one.

**Comment by Holt59** [comment]
@dereuromark Thanks, I have opened [a pull request](https://github.com/cakephp/cakephp/pull/7959) so I am closing this ticket.
