### ISSUE TITLE
Cake php authentication issues

### ISSUE THREAD

**Issue by kantsverma** [cakephp/cakephp#7960]
I have install the cakephp 3.o using composer and bake the user section using command but i am getting few issues with authentication when i add the users its successfully adding the users in database but password is not in form of hash password its in plain text and then i follow the documentation and start integrate the FormAuthenticate method but its giving me error "You are not authorized to access that location" login not working .

Is there issues with cakephp 3.0 or m i missing anything ?

Regards
Kantsverma

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by kantsverma** [comment]
Dereuromark, 

I did not understand what you want to explain can you explain it to me ?

Kind regards
kantsverma

**Comment by dereuromark** [comment]
The above answer states that you should be asking help questions somewhere else.
This is not a bug and thus should not be asked in this github ticket system.

You issue is most likely a too short password field length in your schema, as documented you should be using varchar(255).
But please respect that we cannot answer support questions here.

**Comment by kantsverma** [comment]
Ok Dereuromark thank you but my password fields is varchar 255 already.

**Comment by dereuromark** [comment]
When it is not hashed in the db, you didnt follow the documentation on how to save it with hashing in beforeSave() etc.
