### ISSUE TITLE
Fatal error with cakephp 3.2 RC1

### ISSUE THREAD

**Issue by deepacitpl** [cakephp/cakephp#7966]
I have downloaded cakephp-3-2-0-RC1.zip from this link
https://github.com/cakephp/cakephp/releases/tag/3.2.0-RC1

While running the application Im getting error
Class 'Cake\Chronos\MutableDate' not found in /vendor/cakephp/cakephp/src/I18n/Date.php on line 26

I can't find Cake\Chronos\ in src folder.

**Comment by antograssiot** [comment]
you are missing cakephp/chronos
https://github.com/cakephp/chronos

did you make any use of composer ?

**Comment by lorenzo** [comment]
A new package has just been generated. We're sorry for the confusion, please let us know if the new zip file is fully working.
