### ISSUE TITLE
ExistsIn should apply association conditions

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/cakephp#7968]
I'm using an `ExistsIn` build rule with one of my association which has conditions. Since I'm explicitly checking for the existence in an association - not in a table - I would expect `ExistsIn` to use the association conditions to check for the existence.

My suggestion would be respecting the association conditions, so data integrity will be enforced. If there are conditions on an association which shouldn't be checked (I can't think of a reason for that, to be honest), you could still pass an instance of a table instead of the association name.

What are the opinions on this matter? I would be happy to implement this if you agree on this.

**Comment by lorenzo** [comment]
how did you setup the rule?
