### ISSUE TITLE
Debugger::formatTrace should not serialize Query instances

### ISSUE THREAD

**Issue by jippi** [cakephp/cakephp#7970]
Giving the following example 

`$this->Table->find()->find('custom')` 

and `custom` throwing an exception - during a JSON/XML api request in e.g. CRUD / CrudAPi - pushing the exception and trace to the view for easier debugging will cause the `find()` method to be executed and the result passed as argument in the trace output - basically causing a `find('all')` to be outputted to the view 

I would like `Debugger::formatTrace` to not include Query instances in arguments - as they can leak secret data, as well as accidentally execute half-structured SQL query.

cc @lorenzo

**Comment by jippi** [comment]
Implementation example can be found here: https://github.com/FriendsOfCake/crud/blob/master/src/Error/ExceptionRenderer.php#L103

**Comment by markstory** [comment]
Couldn't any object have potentially sensitive data in it? What if instead of special casing Query objects, we only exported arguments with a depth of 1 instead of 3? That would prevent traversal into the connection object which solves the issue here I think.
