### ISSUE TITLE
Query giving column not found even though it exists.

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7971]
I have a query which I am running on my local machine, and it is working perfectly. I have a production server where I upload code when I finished testing it. I never had any problems till now. But running the Task on the server gives back the following error: `Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Products.id' in 'where clause'`
I have tried running the task from my OSX, linux, and even windows, and its working fine. Only on the production server, it is giving me this error. All my other tasks are working fine, and the website is also working fine, its only this one task thats giving me the problem. So I dumped the query object, and its the same query that runs on my local machine.

``` php
object(Cake\ORM\Query) {

	'(help)' => 'This is a Query object, to get the results execute or iterate it.',
	'sql' => 'UPDATE products SET Products.delivery_id = :c0 WHERE Products.id in (:c1)',
	'params' => [
		':c0' => [
			'value' => (int) 5,
			'type' => 'biginteger',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => (int) 3648,
			'type' => 'biginteger',
			'placeholder' => 'c1'
		]
	],
	'defaultTypes' => [
		'Products.id' => 'biginteger',
		'id' => 'biginteger',
		'Products.product_info_id' => 'biginteger',
		'product_info_id' => 'biginteger',
		'Products.order_id' => 'biginteger',
		'order_id' => 'biginteger',
		'Products.delivery_id' => 'biginteger',
		'delivery_id' => 'biginteger',
		'Products.package_id' => 'biginteger',
		'package_id' => 'biginteger',
		'Products.reservation_id' => 'biginteger',
		'reservation_id' => 'biginteger',
		'Products.carton_number' => 'biginteger',
		'carton_number' => 'biginteger',
		'Products.size' => 'string',
		'size' => 'string',
		'Products.price' => 'decimal',
		'price' => 'decimal',
		'Products.ean' => 'string',
		'ean' => 'string',
		'Products.bad' => 'boolean',
		'bad' => 'boolean'
	],
	'decorators' => (int) 0,
	'executed' => false,
	'hydrate' => true,
	'buffered' => true,
	'formatters' => (int) 0,
	'mapReducers' => (int) 0,
	'contain' => [],
	'matching' => [],
	'extraOptions' => [],
	'repository' => object(App\Model\Table\ProductsTable) {

		'registryAlias' => 'Products',
		'table' => 'products',
		'alias' => 'Products',
		'entityClass' => 'App\Model\Entity\Product',
		'associations' => [
			(int) 0 => 'productinfo',
			(int) 1 => 'orders',
			(int) 2 => 'deliveries',
			(int) 3 => 'packages',
			(int) 4 => 'reservations',
			(int) 5 => 'websites'
		],
		'behaviors' => [
			(int) 0 => 'CounterCache'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	}

}
```
Stack Trace:
``` php
2016-01-05 17:40:48 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Products.id' in 'where clause'
Stack Trace:
#0 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Database/Connection.php(270): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Database/Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /var/www/clients/client1/web7/web/src/Model/Table/DeliveriesTable.php(167): Cake\Database\Query->execute()
#4 /var/www/clients/client1/web7/web/src/Shell/Task/ParseEmailTask.php(88): App\Model\Table\DeliveriesTable->addDelivery(Array, Array)
#5 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Database/Connection.php(557): App\Shell\Task\ParseEmailTask->App\Shell\Task\{closure}(Object(Cake\Database\Connection))
#6 /var/www/clients/client1/web7/web/src/Shell/Task/ParseEmailTask.php(90): Cake\Database\Connection->transactional(Object(Closure))
#7 [internal function]: App\Shell\Task\ParseEmailTask->main()
#8 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Console/Shell.php(448): call_user_func_array(Array, Array)
#9 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Console/Shell.php(442): Cake\Console\Shell->runCommand(Array, false)
#10 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(212): Cake\Console\Shell->runCommand(Array, true, Array)
#11 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(179): Cake\Console\ShellDispatcher->_dispatch(Array)
#12 /var/www/clients/client1/web7/web/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch(Array)
#13 /var/www/clients/client1/web7/web/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#14 {main}
```
My code:
``` php
$query= $this->Products->query()->update()
                ->set(['Products.delivery_id' => $delivery->id]) // Link to delivery
                ->where(['Products.id IN' => $idList]);
```
I'm using PHP 5.6.11-1ubuntu3.1
mysql  Ver 14.14 Distrib 5.6.27, for debian-linux-gnu (x86_64) using  EditLine wrapper
Scripts are all running as root, permissions are all setup right.
The database is exactly the same as I use on my local machine, I double cheked, and the Products table is there, all other Tasks can see it, just not this one.

I'm out of ideas...

**Comment by markstory** [comment]
I bet you have case sensitive identifiers on in one environment and not in the others. See [the mysql docs have more information](http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html)

**Comment by ionas** [comment]
This looks like a question. To debug that it has nothing to do with cakephp. Utilize DebugKit to get the query that runs fine on your machines. Execute that query on your production. See what the issue is.

Please try using gists, irc, stackoverflow, etc frist.

**Comment by half2me** [comment]
@ionas sorry about that, next time I'll use gists first.
@markstory I'll check that out.

However I still don't understand why this query won't run when every other query runs on the system. If I do have case sensitive identifiers turned on, shouldn't the Query object return the query with the right case? (It seems to do this fine with other queries.)

**Comment by markstory** [comment]
Your query is mixing cases

```sql
UPDATE products SET Products.delivery_id = :c0 WHERE Products.id in (:c1)
```.

**Comment by half2me** [comment]
@markstory I see that, but my query was generated with the QueryBuilder. Shouldn't query builder take care of using the correct case?

**Comment by half2me** [comment]
This problem is only on UPDATE statements because CakePHP usually aliases tables on queries, but not on update(). In this case it would be nice if the convention of using (Model.field) could be converted to simply the field in proper case...

**Comment by markstory** [comment]
> This problem is only on UPDATE statements because CakePHP usually aliases tables on queries, but not on update().

That's a fair point, I can look into adding aliases on update.

**Comment by half2me** [comment]
@markstory Thanks!

**Comment by markstory** [comment]
Because update queries don't ever have joins you can safely omit the alias/model name from the query entirely.

I was thinking about this more. Adding an alias automatically will break existing applications as they will generally rely on aliases that no longer exist. For that reason I don't think its a good idea to add aliases.

**Comment by half2me** [comment]
@markstory I used joins on update() where I had a query like update modelA.field set bla... where ModelB.field LIKE something.

**Comment by half2me** [comment]
but I'll write a note in the documentation on update() to make sure everyone knows that you should only use the field name instead of the modelname.fieldname

**Comment by markstory** [comment]
Ok that would be great!
