### ISSUE TITLE
RFC: FormHelper::create() change "type" to "method" for convenience. Deprecate type in future.

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7975]
Ref: http://book.cakephp.org/3.0/en/views/helpers/form.html#changing-the-http-method-for-a-form

**Comment by dereuromark** [comment]
Since we also use allowMethod() and the HTML attribute is method I think this makes sense :+1:

**Comment by ADmad** [comment]
Currently you can also use `'type' => 'file'` which sets `enctype`. If we rename the option we would have to use `'method' => 'file'` thus actually setting an invalid value `method` attribute which morphs into another attribute `enctype`.

This would be worse than what we currently have. So I am :-1: on this.

**Comment by ionas** [comment]
Can't file upload happen with not just `HTTP POST` but `PUT`, `PATCH` as well - AFAIK you can? An app that allows REST and browser access could benefit from this transparency.

* We can offer another hash key for that. Possibly `enctype` or `encType`
* "type" won't get removed until 4.0.
* We should allow encType or enctype to be set: https://developer.mozilla.org/en/docs/Web/HTML/Element/form#attr-enctype
* We can make it easier if you like and:
```
'enctype' => 'default': application/x-www-form-urlencoded: The default value if the attribute is not specified.
'enctype' => 'file': multipart/form-data: The value used for an <input> element with the type attribute set to "file".
'enctype' => 'plaintext': text/plain (HTML5)
```
* If none of those keys are found, then just take the value the user supplies (future proof)

**Comment by dereuromark** [comment]
Oh, I forgot about enctype. I have to agree with @ADmad in that case. `type` so far seems to be clear enough for people.

**Comment by ADmad** [comment]
> It hit me today cause I was trying the obvious (setting method hashkey), and I am possibly not the only one.

This is the only think we should probably fix. If `method` is provided it should override whatever is set through `type`.

**Comment by ionas** [comment]
We can leave in type for BC and convenience and just say:
a.) type
b.) http attribute possibly overwritten by method hashkey
c.) enctype attribute possibly overwritten by enctype hashkey
Wouldn't that work?
