### ISSUE TITLE
2.7: NOT IN bug in conditions

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7978]
I think I found a bug in 2.7.8 while trying to make 2.x queries 3.x ready:

Before:

    ->find('all', ['conditions' => ['NOT' => ['username' => ['aaa']]]]);

This would break in 3.x when upgrading.

After modifying to what should be valid in both:

    ->find('all', ['conditions' => ['username NOT IN' => ['aaa']]]);

This results in this exception though:
```
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near 
'= ('aaa') ORDER BY `User`.`username` ASC' at line 1

SQL Query: 
SELECT `User`.`id`, `User`.`active`, `User`.`created`, `User`.`username`, `User`.`password`, `User`.`email` 
FROM `table`.`users` AS `User` 
WHERE username NOT IN = ('aaa') 
ORDER BY `User`.`username` ASC 
```

It should be transformed to `username NOT IN ('aaa')` as  in 3.x.

**Comment by dereuromark** [comment]
I might have found a possible fix:

    if ($count === 1 && !preg_match('/\s+(?:NOT|\!=)$/', $key)) {

to

    if ($count === 1 && !preg_match('/\s+(?:NOT( IN)?|\!=)$/', $key)) {

But why are we changing it for arrays and count 1 anyway?
IMO it should behave like 3.x and always output `(NOT) IN ('aaa')`.
I don't think there is performance issue with `field = (value)` vs `field IN (value)`.
And both return the exact same output.

**Comment by dereuromark** [comment]
I just found out that the positive case is also not working:

    ['username IN' => ['aaa']]

=> Error: SQLSTATE[42000]: `WHERE username IN = ('aaa')`

**Comment by markstory** [comment]
I think the code you found is for handling `'field !=' => ['a value']` but I could be mistaken. In any case, I think making `NOT IN` operators forward compatible makes sense.

**Comment by markstory** [comment]
Closing as a pull request is up now.
