### ISSUE TITLE
VENDOR constant in paths.php

### ISSUE THREAD

**Issue by makallio85** [cakephp/cakephp#7982]
Is there some reason why ```paths.php``` does not contain VENDOR constant?

I think ``` VENDOR . 'cakephp-plugins.php'``` would be more readable than ```dirname(dirname(dirname(dirname(__DIR__)))) . DS . 'cakephp-plugins.php'``` 

See this line as an example:
https://github.com/cakephp/cakephp/blob/master/src/Core/Plugin.php#L189

**Comment by markstory** [comment]
CakePHP core files don't define `VENDOR`, therefore we can't rely on it.
