### ISSUE TITLE
Entity display bigint data type is error

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#7983]
My mysql has a table name is trades ,  trades has colnum id with bigint (50) . but use $this->Trades->fidn('all')->all();

all result display  trades id is  2147483647

**Comment by ionas** [comment]
bigint
int
etc depends on your host architecture (32, 64bit) and rdbm bit version, and rdbms design. the "lenght" in brackets is for zerofill - in case of integers.

**Comment by ADmad** [comment]
You are using a 32bit system on which max integer value possible is 2147483647. You can confirm by checking output of `intval(PHP_INT_MAX);`

**Comment by ADmad** [comment]
Duplicate of #6997

**Comment by macnie** [comment]
I using 64x windows 10

**Comment by ADmad** [comment]
What output do you get for `intval(PHP_INT_MAX);` ?

**Comment by chinpei215** [comment]
@macnie The x64 builds of PHP 5 for Windows doesn't support 64-bit integers even if you are using 64-bit windows. According to windows.php.net, PHP 7 supports 64-bit integers.
http://windows.php.net/#x64

**Comment by macnie** [comment]
thanks @chinpei215
