### ISSUE TITLE
3.1 Session => ['defaults' => 'cake'] should try to auto-create tmp/sessions if not existing

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#7987]
When switching from A:
```php
    'Session' => [
        'defaults' => 'php',
    ],
````
to B:
```php
    'Session' => [
        'defaults' => 'cake',
    ],
```
... because of the existence of an application cluster, the session path in tmp was not found and resulted in an error:
```
Warning (2): session_start(): open(/var/www/app/tmp/sessions/sess_4tkdpateu38p9l9n7iolj4qta1, O_RDWR) failed: No such file or directory (2) [CORE/src/Network/Session.php, line 324]
```
**Should switching from A to B try to auto-create tmp/sessions path if not existing?**

**Comment by markstory** [comment]
I am not so sure we want to try and create directories that don't exist. Unless we did some special casing, we'd be trying to ensure that `session.save_path` existed if it wasn't defined and we could run into issues around filesystem permissions or open_basedir limitations.

**Comment by jhli** [comment]
Within ROOT/tmp/ it should be okay? 
Don't we do the same for cache, models, persistent etc?

**Comment by ADmad** [comment]
[tmp/sessions](https://github.com/cakephp/app/blob/master/src/Console/Installer.php#L105) is already created as install time. We should definitely not try to create directories at runtime.

**Comment by ionas** [comment]
The gap that surprises is, following directories get setup on install time:
`ROOT/logs`
`ROOT/tmp`
`ROOT/tmp/cache`
`ROOT/tmp/cache/models`
`ROOT/tmp/cache/persistent`
`ROOT/tmp/cache/views`
`ROOT/tmp/sessions`

> "We should definitely not try to create directories at runtime" (@ADmad)

**Following directories *are* created at runtime**.
Thus they will be re-created (tested just now) if they got deleted throughout the deployment process:
`ROOT/logs`
`ROOT/tmp`
`ROOT/tmp/cache`
`ROOT/tmp/cache/models`
`ROOT/tmp/cache/persistent`
`ROOT/tmp/cache/views`
~~```ROOT/tmp/sessions```~~

Did not test for `ROOT/tmp/tests`, e.g. if it gets recreated on demand.

p.s.: I'd have preferred to discuss this in short on IRC.

**Comment by dereuromark** [comment]
@ionas Folders are only created in debug mode, not production.
Also, tmp, logs, cache and tmp/sessions for CakePHP itself is fine, but another outside is not OK and should be done automatically.

**Comment by ionas** [comment]
In case there is a will for consistency let me know and I will try to fix it ASAP.

**Comment by dereuromark** [comment]
Please make a PR. I think that will make the discussion easier as it will be more code hands-on and less theoretical.
