### ISSUE TITLE
"Tdrs" is not associated with "Departaments" InvalidArgumentException

### ISSUE THREAD

**Issue by lpalacin** [cakephp/cakephp#7988]
Sorry I need some help. I don't know what is wrong in this simple (has many / belongs to) association.

There is the code:

[DepartamentsTable.txt](https://github.com/cakephp/cakephp/files/81507/DepartamentsTable.txt)

[TdrsTable.txt](https://github.com/cakephp/cakephp/files/81512/TdrsTable.txt)

[TdrsController.txt](https://github.com/cakephp/cakephp/files/81490/TdrsController.txt)

Thank you very much

**Comment by lpalacin** [comment]
Solved
It was a Typo.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
