### ISSUE TITLE
3.2.0-RC1 - Entity getOriginal not working as expected

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7990]
Hey guys. Unless I'm missing something really simple, `getOriginal` should return the value of the property outside any `Entity` getters, right? When trying to use `getOriginal` right now I see the value of the property after it's run through the getter, only if I don't first set it explicitly..

Say I have a post with name='test'.

Post.php
```
public function _getName()
{
    return 'updated name';
}
```
Then..
```
pr($post->get('name')); // 'updated name' .. like you'd expect
pr($post->getOriginal('name')); // 'updated name' .. when it should be 'test'
```

However, check this out..
```
$post->set('name', 'foo');

pr($post->get('name')); // 'updated name' .. like you'd expect
pr($post->getOriginal('name')); // 'test' .. like you'd expect
```

It looks like `EntityTrait::set` is what updates the `_original` values, so you have to first set something before it works. Is there a way I can get that to work without doing a dummy set first?

**Comment by patrickconroy** [comment]
It looks like it works by adding the property to `_original` in `EntityTrait::get`..

```
public function &get($property)
{
    if (!strlen((string)$property)) {
        throw new InvalidArgumentException('Cannot get an empty property');
    }

    $value = null;
    $method = '_get' . Inflector::camelize($property);

    if (isset($this->_properties[$property])) {
        $value =& $this->_properties[$property];
    }
    if (!isset($this->_original[$property])) {
        $this->_original[$property] = $value;
    }

    if ($this->_methodExists($method)) {
        $result = $this->{$method}($value);
        return $result;
    }
    return $value;
}
```

If that looks ok I can make a PR/test.

**Comment by markstory** [comment]
`getOriginal()` will return the current value (including getter modifications) if the property has not yet been modified. Having a 'getter' create side-effects could be pretty surprising to some people I suspect.

I think the API docs for getOriginal() could be clearer about using the present value if the property has not been modified yet.

**Comment by patrickconroy** [comment]
Hm, wouldn't someone expect something named `getOriginal` to get the original value? What about modifying it so it allows to skip getters..

```
public function getOriginal($property, $getters = true)
{
    if (!strlen((string)$property)) {
        throw new InvalidArgumentException('Cannot get an empty property');
    }
    if (array_key_exists($property, $this->_original)) {
        return $this->_original[$property];
    }
    return $this->get($property, $getters);
}

public function &get($property, $getters = true)
{
    if (!strlen((string)$property)) {
        throw new InvalidArgumentException('Cannot get an empty property');
    }
    $value = null;
    $method = '_get' . Inflector::camelize($property);
    if (isset($this->_properties[$property])) {
        $value =& $this->_properties[$property];
    }
    if ($getters && $this->_methodExists($method)) {
        $result = $this->{$method}($value);
        return $result;
    }
    return $value;
}
```

**Comment by markstory** [comment]
> What about modifying it so it allows to skip getters..

I don't know what that would to existing applications.

**Comment by patrickconroy** [comment]
The thing is that getters are really powerful but if you use them there's no easy way to get the original value. I guess adding an extra virtual property which returns the original is ok.. I'll close this since that'll work but I really think `getOriginal` should return the value without getters..
