### ISSUE TITLE
2.6.1 - Memcached Cache configs only use the first server in a multi-config setup with amazon-elasticache-cluster-client driver

### ISSUE THREAD

**Issue by solidspark** [cakephp/cakephp#7992]
We've came across a puzzling situation in our production environment where our multiple cache configs under `Memcached` only use the _first_ server parameter and ignore the rest. We assume it's because the Cache object gets created and the connection pool is behaving like singleton, never to be recreated.

#### Setup:
CakePHP version 2.6.1
PHP version 5.5.12
Ubuntu 14.04
amazon-elasticache-cluster-client

#### Example core.php config:

```
Cache::config('banana',
              array(
                  'engine' => 'Memcached',
                  'duration'=> 3600,
                  'probability'=> 100,
                  'prefix' => 'bb_',
                  'servers' => array (
                      'banana.zomcip.cfg.use1.cache.amazonaws.com:11211'
                  ),
                  'persistent' => true
                )
);

Cache::config('apple',
              array(
                  'engine' => 'Memcached',
                  'duration'=> 21600,
                  'probability'=> 100,
                  'prefix' => 'aa_',
                  'servers' => array (
                      'apple.zomcip.cfg.use1.cache.amazonaws.com:11211'
                  ),
                  'persistent' => true
                )
);
```

When we added apple, `aa_` keys were getting written to banana. And vice versa. No connections would be opened to `apple.zomcip.cfg.use1.cache.amazonaws.com` unless it was the first item in the config. There are no exceptions or errors in the logs.

**Comment by markstory** [comment]
Have you tried not using persistent connections? I suspect persistent connections are causing the Memcached extension to do the wrong things.

Also based on the code above there is only _one_ server in each configuration, is that a mistake?

**Comment by solidspark** [comment]
@markstory We are unable to run non-persistent connections because of the CPU overhead involved. And yes, there is _one_ server in each configuration - and that server is the configuration node for an AWS Elasticache cluster, pointing to N servers.

**Comment by markstory** [comment]
Sounds like you might have hit an issue in the memcached driver. The [cakephp code](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Cache/Engine/MemcachedEngine.php#L110-L114) relies on the driver doing the right thing.

**Comment by jrbasso** [comment]
@solidspark I use AWS ElastiCache on my company with Cake 2.x and I can see my keys being distributed across the nodes via CloudWatch.

Double check that you are using the write PHP extension. The regular memcached must be disabled and only load the AWS one. You can verify by checking the value of `defined('Memcached::DYNAMIC_CLIENT_MODE')`. If that's true, your extension is probably loaded correctly. Also, check if [this `if`](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Cache/Engine/MemcachedEngine.php#L172-L175) is being satisfied. This is very important.

@markstory FYI, AWS has a special memcached library that "extends" PHP's memcached and add a feature when the client mode is set to dynamic the library will change the single registered node (which is the aggregator (by default it is just a round robin DNS, but via their API you can get the list of all nodes on the memcached cluster) by the nodes on the extension itself, so after your finish setting up the mecached, if you do getServers it will return all the nodes from your cluster.

**Comment by solidspark** [comment]
@jrbasso The use of a single cluster is not the issue, we have a 4 node cluster and the keys are being evenly distributed. We wanted to split the cluster into two concerns - one for short-lived TTL's and the other for long lived TTL's so the LRU could reclaim more efficiently, and when we did this, Cake would only connect to the first cluster in the cache config, never the others.

**Comment by lorenzo** [comment]
Closing as this ticket has been inactive for some time and it seems an issue in the php extension for memcache, and not a problem in cake's code
