### ISSUE TITLE
Want a counterCache behavior which will update when child records are updated

### ISSUE THREAD

**Issue by jessicamarx** [cakephp/cakephp#8000]
I have a table Personas:

**id    parent_id     persona     impressions_count    [total_impressions_count]**

The field 'total_impressions_count' is one I want to add. I would like to have a counterCache behavior which will update the 'total_impressions_count' field with a sum of the 'impressions_count' fields for the child records.

So for example:

```
**id    parent_id     persona        impressions_count    [total_impressions_count]**
  1     NULL           human          NULL                         24
  2     1                  neanderthal  13                              NULL
  3     1                  cromagnon   11                              NULL
```

In this case, the parent records total_impressions_count field is the sum of the two impressions_count fields of its child records.

Hope this helps!

-aro

**Comment by lorenzo** [comment]
If you want to help implement this, the easiest way to do it is by having a `TouchBehavior`. This behavior will touch a column (like the modified timestamp) so that the parent is forced to save and trigger its callbacks. Let me know if you want help or guidance if interested in doing it
