### ISSUE TITLE
[FatalErrorException] Call to a member function format() on array

### ISSUE THREAD

**Issue by mkornatzki** [cakephp/cakephp#8001]
Hi,
i do create all the neccessary files for a table "updates" with "cake bake all updates".
If i want to edit the data with the automatically created screens i get the following eror:
in Logfile: Error: [Cake\Error\FatalErrorException] Call to a member function format() on array
on Website: Error: Call to a member function format() on array
  File C:\Work\webserver\site\vendor\cakephp\cakephp\src\Database\Type\DateTimeType.php
  Line: 97 

Other sites baked like the site above worked without problems.

I try to find the problem (i am new to cakePhp) and found out that the unique validation makes the problem.
        $validator
            ->add('release_dat', 'valid', ['rule' => 'datetime'])
            ->allowEmpty('release_dat')
            ->add('release_dat', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);
If i comment out the line with "unique" i can add and edit entities.

I use cakePhp 3.1.5, php 5.6.16 and mySQL 5.0.11.
In the database a unique index is defined "UNIQUE INDEX release_dat_UNIQUE (release_dat)"

Is this a bug or do i have to configure something?

cheers, michael

**Comment by lorenzo** [comment]
Can you find the full stack trace of the error by adding the xdebug extension in your php? The stracktrace will automatically show up in the error page.

**Comment by mkornatzki** [comment]
Hi lorenzo,
sorry but in my php.ini i cn not enable xdebug. In this version zendebug is as far as i understand enabled in default (; This setting is on by default.
;report_zend_debug = 0)
Did you see that i edited my first request and put some more debug information in it?
If this is not enough i will try to give you more information.

**Comment by lorenzo** [comment]
It would just be nice to have the full stack trace to save us some time debugging from our side :)

**Comment by lorenzo** [comment]
It actually looks like you are validating the uniqueness of a date filed, that was posted as an array. I don't think that is currently supported. While this bug is being investigated, I suggest moving your validation to have a `isUnique()` call in the `buildRules` method of your table.

It will have the same effect, but won't trigger any errors.

**Comment by mkornatzki** [comment]
I only want to inform that there was an error in the generated classes and sites.
The datetime gets generated in multiple fields and therefor it gets validated as an array.
Later i want to use a datetime field with a datepicker for the dates.
If you want you can close this issue.
Thanks for your quick response.
