### ISSUE TITLE
CakePHP 3.1: Authentication Issues

### ISSUE THREAD

**Issue by nls90** [cakephp/cakephp#8004]
Hi, I am new to cakephp 3.1 so having trouble authenticating using Auth component.
I dont have username and password columns in the DB table 'users', instead, have usr_email, usr_mobile, usr_pass fields. I am storing passwords by hashing them with defaultPasswordHasher->Hash method.

On the UI form, I have a text field named "usr_token" & password field named "usr_pass", wherein user can enter either email id or mobile number under usr_token field and password in usr_pass field.

In UserController, I am configuring auth like this:
```php
$this->loadComponent('Auth',
'authenticate' => [
'Form' => [
       'Fields' => ['usr_token'=>'usr_email','usr_pass'=>'usr_pass'],
     ]
]);
```
However, the identify() method is always returning false, so failing to authenticate user. Anyone has any idea, why? Also, the usr_pass column has length of 300, so no issues of length here.

How can I use usr_token field to authenticate user with either usr_email or usr_mobile?

Any hint is greatly appreciated. Thank you!

**Comment by dereuromark** [comment]
You need to respect casing. That is a very important thing in coding.
As documented your `Fields` would actually be `fields`.

And I think the keys must match the documented ones, whereas you changed them completely.

**Comment by jhli** [comment]
This is not a help forum. Try: The Book, API/Source, IRC, Stackoverflow, Google Groups, Web Search Engines.

http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuring-authentication-handlers
