### ISSUE TITLE
Baking with Sql Server uppercase transformed to snake case

### ISSUE THREAD

**Issue by ebenmoha** [cakephp/cakephp#8006]
Hello,

I want to generate the mvc pattern of my sql server database that is defined like this for example: XX_Entity. The problem is that the baking stops with the first table and it reports this error:
Cannot describe x_x_entity. It has 0 columns. In [C:\....\Collection.php line 98 ]

I noticed that the table name was modified from XX_Entity to x_x_entity. Is it normal ? Also, I tried to bake entities one by one. It hangs a lot at the message "One moment while associations are detected" and finally It worked but the associations are not there. I found one issue that talks about this error but I think that it's not the same problem. Thanks for your help.

**Comment by lorenzo** [comment]
Bake is a tool that works thanks to conventions. Unnfortuanately, it will not detect associations unless you have followed the conventions in your tables

**Comment by markstory** [comment]
Bake will only detect associations that follow the conventions. From the examples you've posted your tables don't. While we have support for custom table names with the `--table` option similar options do not exist for associations as it would be quite unwieldy.

Closing as we can't reasonably fix this.

**Comment by ebenmoha** [comment]
Hello, thanks for your answers. For every database system (MySql, Sql Server, ... ), there's some tables that define the other tables and their relationships (information_schema for the mysql example). I know that this solution can be weird to implement but at least we will not be obliged to follow any convention. Thanks for your help.
