### ISSUE TITLE
cakephp 3.0 unit testing

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [cakephp/cakephp#8007]
hi,when i execute phpunit through command in the plugins/sampleplugin folder.the below exception is appearing.please resolve the issue.And in my controller the testcase is 

public function testIndex()
    {
        $this->get('/discount-engine/customer_discounts');
        $this->assertResponseOk();
    }

and exception is 

1) sampleplugin\Test\TestCase\Controller\TestsControllerTest::test
Index
include(D:\xampp\htdocs\test\vendor\cakephp\cakephp
\tests\test_app\config\routes.php): failed to open stream: No such file or direc
tory

D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Rou
ting\Router.php:974
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Rou
ting\Router.php:974
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Rou
ting\Router.php:547
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Tes
tSuite\IntegrationTestCase.php:451
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Tes
tSuite\IntegrationTestCase.php:392
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Tes
tSuite\IntegrationTestCase.php:312
D:\xampp\htdocs\test\vendor\cakephp\cakephp\src\Tes
tSuite\IntegrationTestCase.php:233
D:\xampp\htdocs\test\plugins\sampleplugin\tests\T
estCase\Controller\testsControllerTest.php:29
D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
