### ISSUE TITLE
Issue with Cakephp 3.0 Unit testing Behavior

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [cakephp/cakephp#8010]
Hi,
Iam writing unit test cases for my application using cakephp 3.0 documentation.
But it behaving differently.when i execute plugins/testplugin test cases i got following error.
please address the issue.

1) TestPlugin\Test\TestCase\Controller\SampleControllerTest::test
Index
include(D:\xampp\htdocs\test\vendor\cakephp\cakephp
\tests\test_app\config\routes.php): failed to open stream: No such file or direc
tory

**Comment by dereuromark** [comment]
Your test_app currently should at least contain an empty routes.php file at this location.
Then it should work.

**Comment by markstory** [comment]
Looks like you've done something funny with paths. Applications and plugins generally should not be referencing `D:\xampp\htdocs\test\vendor\cakephp\cakephp
\tests\test_app\config\routes.php` as that is a file deep within CakePHP's test suite.

**Comment by ravikanthhtnakivar** [comment]
hi dereuromark,
thanks for reply.I did same as u said but still iam getting same error.please address the issue.iam struggling lot with this issue.

**Comment by ravikanthhtnakivar** [comment]
thanks markstory for reply,
from the above path 'test' is the application folder name.
here i have to know ,
do i need to maintain the vendor folder in plulgins/testplugin folder?
please address the above issue.
