### ISSUE TITLE
requirePresence() validation adds required HTML attribute to checkbox in FormHelper

### ISSUE THREAD

**Issue by AlexMax** [cakephp/cakephp#8021]
Currently using CakePHP 3.1.4.

This seems to be somewhat related to #5168.  If I have a Form with validation like:

```php
class UserProfileForm extends Form {
	public function _buildValidator(Validator $validator) {
		// ...other validation...
		$validator->requirePresence('pref_gui');
		$validator->add('pref_gui', 'boolean', [
			'rule' => ['boolean'],
		]);
		// ...validation continues...
```

This seems like the correct validation to apply, since I want to ensure that the postback contains `pref_gui` and it is set to a boolean value.  However, when I use FormHelper like so:

```php
$body .= $this->Form->inputs([
	'pref_gui' => ["type" => "checkbox", "label" => "Use WYSIWYG Editor", 'hiddenField' => true],
	'pref_notifications' => ["type" => "select", "options" => $options],
], [
	'legend' => 'Preferences'
]);
```

I get HTML like so:

```html
<div class="input checkbox required">
	<label for="pref-gui">
		<input type="hidden" name="pref_gui" value="0">
		<input type="checkbox" name="pref_gui" value="1" required="required" id="pref-gui" checked="checked">
		Use WYSIWYG Editor
	</label>
</div>
```

This prevents me from submitting the form unless I have the checkbox checked.

Is there something I'm missing?

**Comment by jhli** [comment]
Depends on how you interpet requirePresence, I am with you; interim you can change the validation to boolean - that should hopefully work.

**Comment by markstory** [comment]
If we make those validation rules not 'require' the checkbox to be checked, how would we express that condition?

**Comment by ADmad** [comment]
The "required" attribute is set based on "allowEmpty" not "requirePresence". The fix done in #5216 should already take care of this issue.

Is "pref_gui" a db field?

**Comment by markstory** [comment]
@AlexMax Is the column you're making an input for typed as a boolean?

**Comment by dereuromark** [comment]
Please show us the SQL in that field.

**Comment by markstory** [comment]
I wasn't able to reproduce this in 3.2.3. I did the following

1. Added a `starred BOOLEAN` column to my table.
2. Added `$validator->requirePresence('starred');` and `$validator->add('starred', 'bool', ['rule' => 'boolean']);` to my validator class.
3. Added an input for the boolean field.

The generated field did not have the required attribute set.
