### ISSUE TITLE
Unknown type "" 

### ISSUE THREAD

**Issue by laxman1223** [cakephp/cakephp#8023]
When i trying  save data using new Enity 
Error in Table.php
 $type = Type::build($typeName);
![capture](https://cloud.githubusercontent.com/assets/1289975/12287219/d8b394fc-b9f0-11e5-879c-b617825e05f6.JPG)

**Comment by ADmad** [comment]
Please provide some code example to reproduce the issue. The data you are trying to save and your table schema.

**Comment by laxman1223** [comment]
$this->autoRender = false;
          if ($this->request->is('ajax')) 
		   {
		       $PatientData=$this->request->data;
	           $Email=$PatientData['PatientEmail'];
	           $Phone=$PatientData['PatientPhone'];
	           $FirstName=$PatientData['PatientFirstName'];
	           $LastName=$PatientData['PatientLastName'];
			   $Gender=$PatientData['PatientGender'];
			   $DOB=$PatientData['PatientDob'];
	           $Password=$this->Get->getRandomStrN(8);
               $Insert=$this->Ex->InsertUser($FirstName,$LastName,$Gender,$Email,$Phone,'Default.jpg',$Password,$DOB,'self');
	           if($Insert)
	           {
		       $MailFlag=$this->Ex->SentConfirmMail($PatientData['PatientFirstName'],$PatientData['PatientLastName'],trim($PatientData['PatientEmail']),$Password,"d");
	           if($MailFlag)
	           {
			       $UserId=$this->Get->findUserId('UserID',$Email);
				   $Update=$this->Get->updateUserData($UserId,'MobileFlag',1);
                echo  $this->Ex->InsertAppointment($PatientData['AppPatientName'],$PatientData['AppPatientAge'],$PatientData['AppPatientReason'],$PatientData['AppDate'],$PatientData['AppTime'],$PatientData['AppDr'],$UserId);
	           }
	         }  
		   }

**Comment by laxman1223** [comment]
what you want exactly  ?

**Comment by laxman1223** [comment]
$AppointmentTable=TableRegistry::get('Appointments');
		  $AppointmentEntity=$AppointmentTable->newEntity();
		  $AppointmentEntity->Users_UserId = (int)$UserId;
          $AppointmentEntity->Doctors_DoctorId =(int)$DoctorId;
          $AppointmentEntity->AppointmentPatientName = $AppPatientName;
          $AppointmentEntity->AppointmentPatientAge = (int)$AppPatientAge;
		  $AppointmentEntity->AppointmentReason = (string)$AppPatientReason;
          $AppointmentEntity->AppointmentDate = (string)$AppDate;
		  $AppointmentEntity->AppointmentTime = (string)$AppTime;
		  $AppointmentEntity->PaymentStatus = 'No';
          $AppointmentEntity->BookingStatus = 'No';
		  $AppointmentEntity->AppointmentStatus = 'No';
		  $Insert=$AppointmentTable->save($AppointmentEntity);

![capture1](https://cloud.githubusercontent.com/assets/1289975/12288040/c4bd6684-b9f6-11e5-949e-111ba3a162dc.JPG)

**Comment by markstory** [comment]
What does the `CREATE TABLE` statement look like for this table?

**Comment by laxman1223** [comment]
CREATE TABLE `appointments` (
`AppointmentId` int(11) NOT NULL AUTO_INCREMENT,
`AppointmentDate` varchar(45) DEFAULT NULL,
`AppointmentTime` varchar(45) DEFAULT NULL,
`AppointmentPatientName` varchar(100) NOT NULL,
`AppointmentPatientAge` int(11) NOT NULL,
`AppointmentReason` varchar(45) DEFAULT NULL,
`PaymentStatus` varchar(45) DEFAULT NULL,
`BookingStatus` varchar(45) DEFAULT NULL,
`AppointmentStatus` varchar(45) DEFAULT NULL,
`Users_UserId` int(11) NOT NULL,
`Doctors_DoctorId` int(11) NOT NULL,
PRIMARY KEY (`AppointmentId`),
KEY `fk_Appoinments_users1` (`Users_UserId`),
KEY `fk_Appoinments_DoctorsData1` (`Doctors_DoctorId`),
CONSTRAINT `fk_Appoinments_DoctorsData1` FOREIGN KEY (`Doctors_DoctorId`) REFERENCES
`doctors` (`DoctorId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `fk_Appoinments_users1` FOREIGN KEY (`Users_UserId`) REFERENCES `users` (`UserId`)
ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=ut

**Comment by laxman1223** [comment]
Cake\Database\Type::buildCORE/src/ORM/Table.php, line 1570 
 Cake\ORM\Table->_newIdCORE/src/ORM/Table.php, line 1503 
 Cake\ORM\Table->_insertCORE/src/ORM/Table.php, line 1450 
 Cake\ORM\Table->_processSaveCORE/src/ORM/Table.php, line 1381
 Cake\ORM\Table->Cake\ORM\{closure}CORE/src/Database/Connection.php, line 557
 Cake\Database\Connection->transactionalCORE/src/ORM/Table.php, line 1382
 Cake\ORM\Table->saveAPP/Controller/Component/ExComponent.php, line 113 
 App\Controller\Component\ExComponent->InsertAppointmentAPP/Controller/BookAppointmentController.php, line 144 
 App\Controller\BookAppointmentController->InsertNewUser[internal function]
 call_user_func_arrayCORE/src/Controller/Controller.php, line 429
 Cake\Controller\Controller->invokeActionCORE/src/Routing/Dispatcher.php, line 114
 Cake\Routing\Dispatcher->_invokeCORE/src/Routing/Dispatcher.php, line 87
 Cake\Routing\Dispatcher->dispatchROOT/webroot/index.php, line 37

**Comment by markstory** [comment]
I'll see if I can reproduce this issue.

**Comment by markstory** [comment]
I wasn't able to reproduce this. I used the following schema (I had to remove foreign key definitions)

```sql
CREATE TABLE `appointments` (
`AppointmentId` int(11) NOT NULL AUTO_INCREMENT,
`AppointmentDate` varchar(45) DEFAULT NULL,
`AppointmentTime` varchar(45) DEFAULT NULL,
`AppointmentPatientName` varchar(100) NOT NULL,
`AppointmentPatientAge` int(11) NOT NULL,
`AppointmentReason` varchar(45) DEFAULT NULL,
`PaymentStatus` varchar(45) DEFAULT NULL,
`BookingStatus` varchar(45) DEFAULT NULL,
`AppointmentStatus` varchar(45) DEFAULT NULL,
`Users_UserId` int(11) NOT NULL,
`Doctors_DoctorId` int(11) NOT NULL,
PRIMARY KEY (`AppointmentId`)
) ENGINE=InnoDB
```

And the following code in a shell. I did not define the table or entity classes:

```php
        $t = TableRegistry::get('Appointments');
        $e = $t->newEntity();
        $e->AppointmentPatientName = 'tester';
        $e->AppointmentPatientAge = 22;
        $e->Users_UserId = 1;
        $e->Doctors_DoctorId = 1;
        $t->save($e);
```

This code ran find and the appointment was persisted to the database. You might want to look at the output of `debug($AppointmentTable->schema());` and ensure that all the columns have 'type' populated correctly.

**Comment by laxman1223** [comment]
why i need to remove foreign keys ?

**Comment by laxman1223** [comment]
below table schema not produs\ing any issues .it was working fine  then above tale producing issue ?
CREATE TABLE `doctoradditionals` (
`DoctorAdditionalDataID` int(11) NOT NULL AUTO_INCREMENT,
`Speciality` varchar(100) DEFAULT NULL,
`Qualification` varchar(45) DEFAULT NULL,
`Address` varchar(1000) DEFAULT NULL,
`ConsultationType` varchar(45) DEFAULT NULL,
`Hospital` varchar(200) DEFAULT NULL,
`City` varchar(45) DEFAULT NULL,
`Doctors_DoctorId` int(11) NOT NULL,
PRIMARY KEY (`DoctorAdditionalDataID`),
KEY `fk_DoctorsAdditionalData_DoctorsData1` (`Doctors_DoctorId`),
CONSTRAINT `fk_DoctorsAdditionalData_DoctorsData1` FOREIGN KEY (`Doctors_DoctorId`)
REFERENCES `doctors` (`DoctorId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8

**Comment by markstory** [comment]
You don't need to remove foreign keys. *I* needed to remove them as I don't have schema for those tables and I'm too lazy to guess at their schema.

**Comment by laxman1223** [comment]
-----USERS TABLE-----

CREATE TABLE `users` (
 `UserId` int(11) NOT NULL AUTO_INCREMENT,
 `FirstName` varchar(45) DEFAULT NULL,
 `LastName` varchar(45) DEFAULT NULL,
 `Gender` varchar(45) DEFAULT NULL,
 `DateOfBirth` varchar(45) DEFAULT NULL,
 `Email` varchar(45) DEFAULT NULL,
 `PhoneNumber` varchar(45) DEFAULT NULL,
 `Password` varchar(45) DEFAULT NULL,
 `ProfilePath` varchar(45) DEFAULT NULL,
 `PasswordFlag` int(45) DEFAULT NULL,
 `MobileFlag` int(11) NOT NULL,
 PRIMARY KEY (`UserId`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf


------DOCTORS TABLE-----

CREATE TABLE `doctors` (
 `DoctorId` int(11) NOT NULL AUTO_INCREMENT,
 `FirstName` varchar(45) DEFAULT NULL,
 `LastName` varchar(45) DEFAULT NULL,
 `Gender` varchar(45) DEFAULT NULL,
 `Email` varchar(45) DEFAULT NULL,
 `PhoneNumber` varchar(45) DEFAULT NULL,
 `Password` varchar(45) DEFAULT NULL,
 `PasswordFlag` int(11) DEFAULT NULL,
 `ProfilePath` varchar(45) DEFAULT NULL,
 `ProfileFlag` int(11) DEFAULT NULL,
 `StatusFlag` int(11) DEFAULT NULL,
 `VerificationFlag` varchar(45) DEFAULT NULL,
 `ViewsFlag` varchar(45) DEFAULT NULL,
 `MobileFlag` int(11) NOT NULL,
 PRIMARY KEY (`DoctorId`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8
