### ISSUE TITLE
Bindmodel with multiple database tables

### ISSUE THREAD

**Issue by purnarao** [cakephp/cakephp#8025]
I have two tables "table_x" under database "db_x" and another table "table_y" under database "db_y". Now, when I tried to bind these two tables in CakePHP with some conditions on the binded model, then its throwing "Unknown column" sql error.

```
$this->TableX->bindModel(array(
        'belongsTo' => array(
            'TableY' => array(
                'className' => 'table_y',
                'foreignKey' => 'table_y_id'
                )
            )
        ));
```
TableX has default db configuration and for TableY, I have created a model

```
<?php
class TableY extends AppModel {
    public $useDbConfig = 'db_y_conf';
    public $useTable = 'table_y';   
}
?>
```
Now, here is my query - 

```
$result = $this->TableX->find('all', array('conditions' => array( 'TableY.id !=' => 0)));
```

I have checked the query, its running like below - 

```
SELECT COUNT(*) AS `count` FROM `db_x`.`table_x` AS `TableX` WHERE `TableY`.`id` != 0;
```

There is no joining here. But when I changed the $useDBConfig to 'default' for the model "TableY", then query running like below which is working fine- 

```
SELECT COUNT(*) AS `count` FROM `db_x`.`table_x` AS `TableX` LEFT JOIN `db_x`.`table_y` AS `TableY` ON (`TableX`.`table_y_id` = `TableY`.`id`) WHERE  `TableY`.`id` != 0;
```

In both databases we have table "table_y". My question is when I bind this between different database table, why the query is not binding in Cakephp. Any solutions for this, please share with me.

**Comment by markstory** [comment]
Associations in different databases are not 'joinable' by default as CakePHP cannot make any assumptions that different connections live in the same physical machine.

**Comment by purnarao** [comment]
Thank you @markstory . Its working when I tried with joinings instead of binding model.
