### ISSUE TITLE
Unable to create a ::postLink with a confirm containing \n

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#8030]
When using `HtmlHelper::postLink` with the `confirm`option (which generates a message box), you can't include a new line (\n) in the confirm text, it will be always escaped. Setting the `escape` option to `false` (or even `true`) has no impact on this.

New lines in alert-style boxes are supported by browsers, see http://stackoverflow.com/questions/1841452/new-line-in-javascript-alert-box

(This was the original problem that lead to #8009)

The problem is that the message is run through `json_encode` for escaping, which kills the new line. (See https://github.com/cakephp/cakephp/blob/master/src/View/Helper.php#L167)

**Comment by markstory** [comment]
Fixed with #8038
