### ISSUE TITLE
3.2.0-RC1 - Entity::errors after Table::patchEntity weirdness

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8036]
Hi guys. I just realized something about patching which seems way off.

CommentsTable
```
$validator->requirePresence('post_id', true, "You must provide a post ID");
```

Controller
```
$comment = $this->Comments->get(1);
Comment Object
(
    [id] => 1
    [post_id] => 10
    [content] => something
    ...
)
```

```
$this->Comments->patchEntity($comment, [
    'content' => 'test'
]);
pr($comment);
Comment Object
(
    [id] => 1
    [post_id] => 10
    [content] => test
    ...
)
```
At this point, $comment is an object containing a valid `post_id` and `content`. But when you then run `errors()`..
```
$comment->errors();
// You must provide a post ID
```

Why doesn't `errors` recognize fields that are already on the `Comment`? A patch should merge the given data on top of what's there and *then* validate, right? The only way to get this to work is adding that required field to the patch data.
```
$this->Comments->patchEntity($comment, [
    'content' => 'test',
    'post_id' => $comment->post_id
]);
```

Is this a bug or just how patching is supposed to work?

Thanks

**Comment by dereuromark** [comment]
Please see http://book.cakephp.org/3.0/en/core-libraries/validation.html#requiring-field-presence
The requirePresent really means it has to be present at patching time (both create or update).
If you want to only require this for creating new records, there is an `create` option to set.

**Comment by patrickconroy** [comment]
Thanks @dereuromark. I know that option is available to turn off the presence requirement for updates. My thing is that the field *is* present since it's already in the entity and it's unchanged. It seems like `Entity::errors` shouldn't be given just the patch data, but the result of the `Entity::toArray` after the patch was merged onto it. It's probably too late in the game to request that since it might not be BC.. but the way this works now is kind of unexpected.

**Comment by dereuromark** [comment]
You are right about the BC part.
What you are suggesting could maybe be a new config option `entity`, but not sure if that's a good idea.

**Comment by markstory** [comment]
If you are setting a single property using `patchEntity()` is un-necessary. Instead you can set the property onto the entity directly `$comment->set('content', $stuff)`. If the single field is coming from an untrusted source and you want to apply validation rules, you should make a separate validator for this use case.

**Comment by patrickconroy** [comment]
Thanks guys that cleared it up, I ended up making a second validator.
