### ISSUE TITLE
Associations with alias and cascade callbacks

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#8039]
I found an issue on cakephp 3.0 i have a specific configuration of associations on my project

when i want to delete an entity type of 'Ville' i also want to delete every object linked to this entity:

### in ZonesTable.php
```php
$this->hasMany('VilleOuvrages', [
            'className' => 'Ouvrages',
            'foreignKey' => 'ville_id',
            'dependent'  => true,
            'cascadeCallbacks' => true
        ]);
```

### OuvragesTable.php
```php
$this->hasMany('Elements', [
            'dependent'        => true,
            'cascadeCallbacks' => true
        ]);
```

i got an error when i try to delete a zone entity: *Column not found: 1054 Unknown column 'ville_ouvrage_id' in 'where clause'*

when i inspect the query i found this:

> SELECT VilleOuvrages.id AS `VilleOuvrages__id`, VilleOuvrages.classe_ouvrage_id AS `VilleOuvrages__classe_ouvrage_id`, VilleOuvrages.ville_id AS `VilleOuvrages__ville_id`, VilleOuvrages.zone_id AS `VilleOuvrages__zone_id`, VilleOuvrages.compte_client_id AS `VilleOuvrages__compte_client_id`, VilleOuvrages.numero AS `VilleOuvrages__numero`, VilleOuvrages.parent_id AS `VilleOuvrages__parent_id`, VilleOuvrages.parentalite AS `VilleOuvrages__parentalite`, VilleOuvrages.type AS `VilleOuvrages__type`, VilleOuvrages.latitude AS `VilleOuvrages__latitude`, VilleOuvrages.longitude AS `VilleOuvrages__longitude`, VilleOuvrages.coords_wkt AS `VilleOuvrages__coords_wkt`, VilleOuvrages.couleur AS `VilleOuvrages__couleur`, VilleOuvrages.longueur AS `VilleOuvrages__longueur`, VilleOuvrages.created AS `VilleOuvrages__created`, VilleOuvrages.modified AS `VilleOuvrages__modified`, VilleOuvrages.remarques AS `VilleOuvrages__remarques` FROM ouvrages VilleOuvrages WHERE ville_id = 478

> SELECT Elements.id AS `Elements__id`, Elements.ouvrage_id AS `Elements__ouvrage_id`, Elements.classe_element_id AS `Elements__classe_element_id`, Elements.latitude AS `Elements__latitude`, Elements.longitude AS `Elements__longitude`, Elements.coords_wkt AS `Elements__coords_wkt`, Elements.nom AS `Elements__nom`, Elements.indice AS `Elements__indice` FROM elements Elements WHERE ville_ouvrage_id = '1163'

The first query is ok but the second should not be 'ville_ouvrage_id' in where clause but only 'ouvrage_id'

can u give me some tips to go through ?

thank you

**Comment by markstory** [comment]
You mentioned you were using 3.0. Can you try upgrading to 3.1.7?

**Comment by markstory** [comment]
Any news on whether or not an upgrade solved this?
