### ISSUE TITLE
Custom types does not allow custom SQL Expressions

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8041]
Just like in topic. 
What I want to achieve is to save spacial data to mysql types. I know there was issue for this, but the solution is unacceptable - why should I keep my entits' property as `Expression` Object ?? I want it to hold value. Transformation while attempting to save to DB should be transparent. 

What I would expect to work:
```php
class PointType extends Type {

 
    public function marshal($value) {
        if($value==null || $value===''){
            return null;
        }
        return Point::jsonUnserialize($value);
    }
    public function toDatabase($value, Driver $driver) {
        return new \Cake\Database\Expression\QueryExpression("POINT(1,2)");//just example
    }

    public function toPHP($value, Driver $driver) {
        if ($value === null) {
            return null;
        }
        if($value instanceof Point){
            return $value;
        }
        $results=array();
        preg_match("/\w+\((-?\d+)\s(-?\d+)\)/", $value, $results);
        return new Point([(float)$results[1],(float)$results[2]]);
    }
```

But this does not work, as toDatabase is invoked on actual PDO value binding phase whitch is too late - it should be invoked when the actual INSERT/UPDATE query is built.

Now, why providing mechanism to acccept `QueryExpression` as field is unnaceptable?? Because I want to access the value after entity is saved eg. to broadcast an event where subject is that entity. Using afterSave method to modify the actual value, well works, but value is no longer available as QueryExpression object will take the place. 

In current state this is simply useless and allows only to handle "custom types" that in fact are only strings, integers, and nothing more.

Can you please provide such functionality? Or at least please tell me how to solve my problem.

Here is data manipulation code, please notice points 1) and 2) in the comments

```php
   $result = false;
        try {
            if ($entity) {
                // 1) $entity->position is a custom type Point (geojson)
                $entity = $table->patchEntity($entity, $data); 
                if (count($result = $entity->errors()) == 0) {
                    $table->save($entity, [
                        'associated' => $saveAssociated
                    ]);
                }
            } // 2) AFTER SAVE, $entity->position is a QueryExpression
              // should be still position
            if ($entity == null) {
                $this->errorResponse(["Entity not found"]);
            } else if (count($entity->errors()) > 0) {
                $this->errorResponse($entity->errors());
            } else {
                $this->successResponse();
            }
            return $entity;
```

and this is preSave method on related table - it transforms Point object to proper SQL expression, but it changes actuall field value - how to avoid that permanent change and actually use Expression (this is required for MySQL to store data as mysql`s Point type?

```php
    public function beforeSave(Event $event, \Cake\Datasource\EntityInterface $entity, ArrayObject $options) {
        $coords = $entity->position->getCoordinates();
    // here $entity->position field is permanentyly changed. Data stores fine to db, 
    //but $entity object is required to still hold Point type not QueryExpression
    //this should be rather transparent
        $entity->position = new \Cake\Database\Expression\QueryExpression('POINT(' . $coords[0] . ',' . $coords[1] . ')');
    }
```

**Comment by markstory** [comment]
> But this does not work, as toDatabase is invoked on actual PDO value binding phase whitch is too late - it should be invoked when the actual INSERT/UPDATE query is built.

Couldn't you bind the string representation instead of an object?

**Comment by markstory** [comment]
> In current state this is simply useless and allows only to handle "custom types" that in fact are only strings, integers, and nothing more.
> 
> Can you please provide such functionality? Or at least please tell me how to solve my problem.

Have you looked at how the DateTimeType works? It handles non-string data.

**Comment by Marlinc** [comment]
We're currently using the following:
Database type: https://github.com/ICT-College/stage-selector/blob/master/src/Database/Type/PointType.php
Point class: https://github.com/ICT-College/stage-selector/blob/master/src/Database/Point.php

I wish that there was a way to adjust the select query so I could add a `ASTEXT` statement to the query. That way we wouldn't need the `unpack` which is kind of a hack.

**Comment by Antoniossss** [comment]
@markstory 
I think you have missunderstood. String representation does not address this issue, because RDBMS (mySQL in my case) requires inserted valie to be an expression. In this case eg. INSERT INTO someTable VALUES(POINT(10,40)) So string representtion is no go. It would simply quote and escape POINT(10,40) because that is how PDO works. 

As for date time - again this is not an issue as PDO itself accepts datetime paremter. 

This problem has to be solved during query building phase, and methods from Type class (toDatabase,toStatement) ale called during binding phase - where prepared statement is already prepared and no way to inject additional expression. 

I have tried multiple aproaches, but it is just simply NO GO. This is missing feature and I just dont see reliable workaround for this. 

IMHO: methods toDatabase and toStatement are missnamed. Especialy that toDatabase creates POD binding value and toStatement (wttf??) returns only PDO value bind type.

**Comment by Antoniossss** [comment]
@Marlinc 

does this even work? What RDBMS you are using? This is exactly what i tried to do and this does not work because `canot cast QueryExpression to string`. Are you sure that this code is even executed ??


```php
 public function toDatabase($value, Driver $driver)
    {
        if ($value === null || $value === '') {
            return null;
        }
        if (is_string($value)) {
            $coordinates = explode(',', $value);
            $x = (float)$coordinates[0];
            $y = (float)$coordinates[1];
            $value = new Point($x, $y);
        }
        if ($value instanceof Point) {
            return $value;
        }
        return new QueryExpression('GeomFromText(\'POINT(' . $value . ')\')');
    }

```

**Comment by Marlinc** [comment]
@Antoniossss it does work indeed, we're using MySQL. Or rather MariaDB and its working on a application that we use. It should work as expressions are internally being converted into the required SQL.

**Comment by Antoniossss** [comment]
@Marlinc
But can you confirm that `toDatabase` gets invoked??  As you can see in my example I have already do the same, and this does not work at all!

I think that what is doing the trick probably doing the trick may be inside  inside Point class

```php
    public function sql(ValueBinder $generator)
    {
        $expression = new FunctionExpression('POINT', [$this->x(), $this->y()]);
        return $expression->sql($generator);
    }
```

**Comment by Marlinc** [comment]
@Antoniossss I can't check that at the moment. Haven't got an environment in which I can check that atm.

**Comment by Antoniossss** [comment]
I am 100% sure, that the fact the Point is implementing ExpressionInterface makes Cake to Inject custom SQL - this would be the exact situation like I have described: When property is ExpressionInterface then it works. 

I can bet that if you remote whole toDatabase method, system will still work, as this is not the magic-doer here :)

Anyway thanks for the putting me on (hopefully) right track to get decent woraround. Anyway, this should be done in `PointType` class, and not forcing Property types to implement ExpressionInterface. Docs would be nice as well. In docs there is only json datatape whitch is STRING so that is not a problem - this is not custom datatype.

**Comment by markstory** [comment]
@Antoniossss If you have specific changes you'd like to see done to the documentation I'm happy to merge those in. It also sounds like @Marlinc has at least solved your 'impossible NO-GO' problem for his use case.

**Comment by Antoniossss** [comment]
@Marlinc 
@markstory 

I have developed viable workaround. Now half of the job is done by Point class and half is done via PointType.

I'v created another Type that extends MyCustomType and implements ExpressionElement. Thanks to this, I can thread this type as MyCustomType and CakePHP threats it as ExpressionElement thus injects actual SQL into prepared statement. 
@Marlinc 
I can confirm - PointType#toDatabase is not the method that does the trick, it is the Point#sql (from ExtensionInterface) that injects actual SQL expression
@markstory 
This is a workaround not a solution - this should be done in single class - CustomType extends Type, just like docs says. I must say that at the first glance I was thinking that it is going to do the job here. So i think that the designer's idea was to implement suche mechanism (common to other ORMs) but someone did missimplement/missused it.

I strongly suggest to add conditional invokation `toExpression($value)` if such method exists in CustomType class to allow enclosing all DB->PHP and PHP->SQL in single class just like it should be. 
I leave decision up to you - i think this needs an enhancement.

Following code worksaround the issue, should be wrapped in single CustomType extends Type class.

```php
/**
 * Description of Point
 *
 * @author Antoniossss
 */
 
namespace App\Database\Type;

class Point extends \GeoJson\Geometry\Point implements \Cake\Database\ExpressionInterface{
    
    public function sql(\Cake\Database\ValueBinder $generator) {
        $expr=new \Cake\Database\Expression\FunctionExpression("POINT",$this->coordinates);
        return $expr->sql($generator);
    }

    public function traverse(callable $visitor) {
        $visitor($this->coordinates[0]);
        $visitor($this->coordinates[1]);
    }
    
    public static function jsonUnserializeExpr($json){
        $rawPoint=\GeoJson\Geometry\Point::jsonUnserialize($json);
        
        $point=new self($rawPoint->coordinates);
        return $point;
    }
}
```

```php
namespace App\Database\Type;

use Cake\Database\Driver;
use Cake\Database\Type;



class PointType extends Type {

 
    public function marshal($value) {
        if($value==null || $value===''){
            return null;
        }
        return Point::jsonUnserializeExpr($value);
    }
    
    /**
     * Convert point values to PHP string
     *
     * @param null|string|resource $value The value to convert.
     * @param Driver $driver The driver instance to convert with.
     * @return resource
     * @throws \Cake\Core\Exception\Exception
     */
    public function toPHP($value, Driver $driver) {
        if ($value === null) {
            return null;
        }
        if($value instanceof Point){
            return $value;
        }
        if(is_string($value)){
            $results=array();
            preg_match("/\w+\((-?\d+)\s(-?\d+)\)/", $value, $results);
            return new Point([(float)$results[1],(float)$results[2]]);
        }
    }

}

```php

**Comment by markstory** [comment]
Nice to see that you were able to find a solution. I'm not entirely sure how what you currently have is not 'DRY', as I don't see any duplicate code.

I can see how the conversion of value objects into SQL expressions could be more logical if it was contained within the type object. I'm not sure how amenable that approach would be to the current query compilation process as the type system is not used during query compilation. Presently having value objects implement `ExpressionInterface` is the simplest/best way to integrate with the query compiler.

**Comment by Qrokqt** [comment]
This seems like a defect as previously both @markstory [here](https://github.com/cakephp/cakephp/issues/1757#issuecomment-57561339) and @lorenzo [here](https://github.com/cakephp/cakephp/issues/4671#issuecomment-56265170) seem to have made the assumption that this could be done within the Type class. It also seems spatial fields are the perfect use case for the Type class.

**Comment by lorenzo** [comment]
It is a missing feature. I will be working on this soon
