### ISSUE TITLE
Database schema not present in query tests Fixture

### ISSUE THREAD

**Issue by paulop** [cakephp/cakephp#8042]
Running tests with phpUnit I have a error, see pic.

Query debugging, I see that missing the schema name.
this is a bug?

thanks!

test data source
```
        'test' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'host' => 'localhost',
            //'port' => 'nonstandard_port_number',
            'username' => 'postgres',
            'password' => '****',
            'database' => 'db1',
            'schema' => 'paje_test',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'log' => false,
        ]
```

![image](https://cloud.githubusercontent.com/assets/1051668/12354430/a8206efc-bb74-11e5-9ab6-b8a23850b7ec.png)

E:\wamp\www\pageonlinecake>vendor\bin\phpunit
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

\src\TestSuite\Fixture\TestFixture.php (line 245)
########## DEBUG ##########
'CREATE TABLE "users" (
"id" SERIAL,
"ativo" BOOLEAN DEFAULT NULL,
"nome" VARCHAR(100) DEFAULT NULL,
"email" VARCHAR(100) DEFAULT NULL,
"password" VARCHAR(100) DEFAULT NULL,
"created" TIMESTAMP DEFAULT NULL,
"modified" TIMESTAMP DEFAULT NULL,
PRIMARY KEY ("id")
)'
###########################
Warning Error: Fixture creation for "users" failed "SQLSTATE[3F000]: Invalid sch
ema name: 7 ERRO:  nenhum esquema foi selecionado para cri├í-lo(a)" in [E:\wamp\
www\pageonlinecake\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php,
 line 256]

Exception: Unable to insert fixtures for "App\Test\TestCase\Controller\UsersCont
rollerTest" test case. SQLSTATE[25P02]: In failed sql transaction: 7 ERRO:  tran
sa├º├úo atual foi interrompida, comandos ignorados at├® o fim do bloco de transa
├º├úo in [E:\wamp\www\pageonlinecake\vendor\cakephp\cakephp\src\TestSuite\Fixtur
e\FixtureManager.php, line 304]

E:\wamp\www\pageonlinecake>

**Comment by markstory** [comment]
Does your desired schema already exist?

**Comment by paulop** [comment]
I understand now. The table was set , but after running the tests she was excluded .
I need to create the database every time I run the tests?

This is a UsersControllerTest.

```
<?php
namespace App\Test\TestCase\Controller;

use App\Controller\UsersController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\UsersController Test Case
 */
class UsersControllerTest extends IntegrationTestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'app.users',
    ];
    
    //public $autoFixtures = false;
    
    
    public function testAddUnauthenticatedFails()
    {
        // No session data set.
        $this->get('/users/add');

        $this->assertRedirect(['controller' => 'Users', 'action' => 'login']);
    }

    public function testAddAuthenticated()
    {
        // Set session data
        $this->session([
            'Auth' => [
                'User' => [
                    'id' => 1,
                    'email' => 'paulo@email.com.br',
                    // other keys.
                ]
            ]
        ]);
    
        $this->get('/users/add');

        $this->assertResponseOk();
        // Other assertions.
    }    

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndex()
    {
        
        // Set session data
        $this->session([
            'Auth' => [
                'User' => [
                    'id' => 1,
                    'email' => 'paulo@email.com.br',
                    // other keys.
                ]
            ]
        ]);
    
        $this->get('/users');

        $this->assertResponseOk();
        // More asserts.
    }    
}
```

**Comment by markstory** [comment]
CakePHP relies on the database and schema existing before the tests are run.

**Comment by paulop** [comment]
My mistake, sorry.
I'm using schema name test_
but need a database test_
I'm still learning.
Thanks
