### ISSUE TITLE
Setting to create row in target entity with belongsToMany assoc when primaryKey especified

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#8044]
Hello, 

I would like to have a setting inside Marshaller in belongsToMany associations that allows me to create rows with a specified primaryKey on the target table in case they does not exists.

**Comment by Tzaoh** [comment]
Sorry I will do a pull request, because I have so code to propose.

**Comment by Tzaoh** [comment]
https://gist.github.com/Tzaoh/63911df776fa23154994/revisions#diff-81c7c0b78a299aadb2a10cec4109df01R292

I realized I try from 3.1.7 and @markstory updated the file

**Comment by Tzaoh** [comment]
Pull request with last version files on #8046

**Comment by markstory** [comment]
> I would like to have a setting inside Marshaller in belongsToMany associations that allows me to create rows with a specified primaryKey on the target table in case they does not exists. 

Why? What scenarios is this helpful in? Are there reasons that patchEntity() isn't working?

**Comment by Tzaoh** [comment]
Hi @markstory 
Well i am saving information from a 3rd webservice, and because of the data nature I alreadyd have primaryKeys, so because it is a lot of data I do not want to create an autonumeric primaryKey

**Comment by markstory** [comment]
Yes. If you are patching an existing 'summoner' and overwriting the games association via `patchEntity()` might work better. Overwriting existing objects with `newEntity()` is likely not going to work as `newEntity()` assumes most of the objects you're marshaling are 'new' and don't already exist.

**Comment by Tzaoh** [comment]
Well, in the cases I summoner and games dont exist. Their tables are empty, but I will have that in mind in future scenarios

**Comment by markstory** [comment]
Implemented in #8057
