### ISSUE TITLE
Occasional fails in travis

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8050]
We still have those
https://travis-ci.org/cakephp/cakephp/jobs/101130429
happening in some branches.

```
1) Cake\Test\TestCase\Database\QueryTest::testSelectFieldsFromTable
false does not match expected type "array".
/home/travis/build/cakephp/cakephp/tests/TestCase/Database/QueryTest.php:112
/home/travis/build/cakephp/cakephp/tests/TestCase/DatabaseSuite.php:68
```

From what I understand, those should never fail, as they do sth not related to datetime leap second issues or dependencies.
Any idea whats going on here?

**Comment by markstory** [comment]
No idea. I'm guessing that these issues come from bad combinations of mysql, and php, as these issues only happen on mysql builds.

**Comment by markstory** [comment]
Closing as the problematic test has been skipped and builds have been far more stable from what I've seen.
