### ISSUE TITLE
autoFields() in association queryBuilder fails to fetch autoFields with select()

### ISSUE THREAD

**Issue by hiromi2424** [cakephp/cakephp#8052]
### What's happened
I upgrade 3.1.6 to 3.1.7.

    $Table->find()->contain('BelongsToMany' => function ($q) {
        return $q->select(/* some expression */)->autoFields(true);
    });

All of implementations such like above failed to fetch automatic fields for `BelongsToMany` associations.

### Why?
https://github.com/cakephp/cakephp/commit/c300915
This commits (maybe) introduced such a situation.

### What should I do?
I don't know it is intentional.
I want to fetch all fields from BelongsToMany table and + specific expression like SubQuery.
I made

    $Table->find()->contain('BelongsToMany' => function ($q) {
        return $q->select(/* some expression */)->select($table->schema()->columns());
    });

and works perfectly, but feel weird.
I think this is some bug or breaking BC.. thoughts?

**Comment by markstory** [comment]
Sounds like an unintended side effect of fixing #7913 in #7930. We probably should not overwrite auroFields if it already set.

**Comment by markstory** [comment]
Pull request up now.
