### ISSUE TITLE
Hash::extract() is transforming values.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8053]
I think Hash::extract() does too much, it should maybe not convert the value itself into an array, but rather return it completely.
This would allow for string casts afterwards, whereas right now it would need information on how the array structure of each transformed object looks like.

Example case: https://github.com/FriendsOfCake/cakephp-csvview/pull/55

We just want the User.created DateTime object from the entity, so we can pass it to _renderRow().
But instead the array of it is returned and we can never transform it again as string without deep knowledge of the structure of this specific array.

Might be a side effect of recent changes, maybe a regression even.

**Comment by markstory** [comment]
I don't see how this is a defect. It sounds like a change in behavior that would break existing applications. There haven't been any changes to Hash since Oct 2015, so the behavior has been consistent for quite some time.

**Comment by dereuromark** [comment]
Is there an alternative to not force the objects to break into arrays upon simple Hash read?
It will blow up in the future with custom objects in the entities, that supply a toString version but don't have the chance to do so.

**Comment by markstory** [comment]
What do you mean by 'force the objects to break into arrays'? Are you getting the array cast of an object instead of the object? Does the object in question implement `toArray` by any chance?

**Comment by dereuromark** [comment]
It is our CakePHP Time object, see the linked issue in CsvView.
There we get an array back with "date" as one key. We would have expected the Time object itself which then can safely output itself as string. The array itself cannot anymore.

**Comment by markstory** [comment]
Odd, I don't really get what is going on in that other issue, but are you attempting to extract a property out of an entity and the property's value is a Time instance?

**Comment by dereuromark** [comment]
And after extracting it is an array, not a Time instance, making it impossible to work on it anymore.

**Comment by josegonzalez** [comment]
Might be because of this [line](https://github.com/FriendsOfCake/cakephp-csvview/blob/master/src/View/CsvView.php#L303).

**Comment by dereuromark** [comment]
@josegonzalez No, it doesnt even run into the isset() check
https://github.com/FriendsOfCake/cakephp-csvview/blob/master/src/View/CsvView.php#L301 already has the array instead of the object.

**Comment by dereuromark** [comment]
The problem is
```
                if (is_object($item) && method_exists($item, 'toArray')) {
                    $item = $item->toArray();
                }
```
This should only be done for iterable items we whitelist, not for all possible objects IMO.
Or at least should only do so if the lookup key goes beyond the current level.
E.g. `User.created` => No need to array the created object, as this is already what w need to return. We would only need to further array it if we were looking for `User.created.date`.

But this cannot be changed in 3.x, unless we add an additional option to prevent this from happening to any object.

**Comment by dereuromark** [comment]
I added a small test case to show the intuitive ("late toArray transformation") expectation: https://github.com/cakephp/cakephp/compare/3.2...3.2-hash

**Comment by ADmad** [comment]
For the test cases you have shown 

```
                if (is_object($item) && method_exists($item, 'toArray')) {
                    $item = $item->toArray();
                }
```
isn't executed.

This is what's executed:

```
        if (!preg_match('/[{\[]/', $path)) {
            return (array)static::get($data, $path);
        }
```

So when using `Hash::extract($data, 'User.created')` you get an array instead of time object because the return values is cast to an array.

**Comment by dereuromark** [comment]
Thank you, you are right. This makes it more complicated. I guess virtual field hacks are the only viable workaround I can think of so far.

We would need a new method otherwise that does not cast to array but keeps the found value as is.

**Comment by dereuromark** [comment]
Hash::get() is available and works as expected, from what I just tried.
I guess this ticket can now either be closed as works-for-me or kept for 4.0 as RFC to avoid casting to array if not needed.

**Comment by ADmad** [comment]
Probably instead of `return (array)static::get($data, $path);` it should be `return (static::get($data, $path));`

**Comment by dereuromark** [comment]
That sounds reasonable, but a too harsh BC break for a 3.x release I am afraid.

**Comment by ADmad** [comment]
IMO existing behavior is a bug, but yeah people could be relying in this behavior.

**Comment by markstory** [comment]
@dereuromark Your suggestion sounds like it should work well.

**Comment by dereuromark** [comment]
Is this fixable in 3.x? Or shall this wait until 4.x?

**Comment by inoas** [comment]
Turn the "correct behavior" it on by a an option flag. Set the flag as default in 4.x?

**Comment by dereuromark** [comment]
Unfortunately it does not seem trivial to fix.. Any ideas?

**Comment by markstory** [comment]
Leave it alone? :smile:

**Comment by dereuromark** [comment]
Naaaaah ;) That's still an ugly bug - as ugly as those new smileys.

**Comment by dereuromark** [comment]
@ADmad After some trying around I finally found a viable solution that can land in 3.5.0.
