### ISSUE TITLE
Paginator + i18n

### ISSUE THREAD

**Issue by urionlinejudge** [cakephp/cakephp#8058]
Hi,

Is the new paginator supposed to work with i18n? I wanted to be able to use the paginator sort in i18n fields like name, for instance, but if I do so Cake says the field does not exists. Also the URL uses Model.name, but the field name only "exists" in the i18 table. Am I missing something?

**Comment by markstory** [comment]
It can, but doing so requires you to use `sortWhitelist` and include the aliased names of the i18n columns you want to sort on. For example `Model_name_translation`

**Comment by urionlinejudge** [comment]
@markstory I already did that! But Cake says the field does not exists. When you try to order by a field that is not white listed, Cake does not give an error, it just don't sort but the page is displayed.

**Comment by markstory** [comment]
Is the field you want to sort on joined into the query for the data you are paginating? You can't sort on fields that have not been joined to the primary query.

**Comment by urionlinejudge** [comment]
I tried both ways (to join by using contain and without it), since it is not clear on the docs how the i18n fields are treated when making queries. 

I have a separate i18n table for this table, I have also set the attached the translation behavior in the main table and I am using the normal queries (the translation is taken by setting I18n::locale('en'), for example). 

But I noticed that the i18n table is joined in the query...

**Comment by markstory** [comment]
If the i18n table is joined, you should be able to sort on it with the right field name.

**Comment by urionlinejudge** [comment]
@markstory I clear the cache, just to be sure, but now Cake gives `column reference "name" is ambiguous` even if the URL contains the Categories.name (name is in CategoriesI18n table) the SQL is generated just with `ORDER BY name asc LIMIT 25 OFFSET 0`.

**Comment by dereuromark** [comment]
@urionlinejudge You should probably post your code, what kind of pagination query you are building and how you are feeding it the request data etc.

**Comment by urionlinejudge** [comment]
@dereuromark Sure! 

This is the code from the initialize method in the Table class:

```
$this->addBehavior('Translate', [
    'fields' => [
        'name',
        'subject'
    ],
    'translationTable' => 'BooksI18n'
]);
```

This is the controller:
```
$this->paginate = [
    'finder' => 'translations',
    'contain' => [
        'Authors'
    ],
    'conditions' => [
        'Books.category_id' => $categoryID,
        'Books.visible' => true
    ],
    'order' => [
        'Books.id' => 'ASC'
    ],
    'sortWhitelist' => [
        'Books.id',
        'Books.name',
        'Books.subject',
        'Books.created'
    ],
    'limit' => $limit
];

$this->set('books', $this->paginate($this->Books));
```

I want to be able to sort by name, for instance. The SQL query generated includes the join to the i18n table for this model, but now it gives this ambiguous error.
