### ISSUE TITLE
File error.ctp serves in reality to nothing !

### ISSUE THREAD

**Issue by hozelock** [cakephp/cakephp#8061]
I just lost one hour to understand something in Cake 3.1.7 ...

My goal was to customize the layout of the default error messages. I thought that it had to change the error.ctp file (in src/Template/Layout) ... but nothing to do.

After more research, I realized that Cake PHP used the default.ctp file (in src/Template/Layout) when the debug is false and used dev_error.ctp (in the core) when the debug is true.

It's entirely possible to customize the error display (when the debug is true), creating a new file named dev_error.ctp (in src/Template/Layout).

My question is simple ... the error.ctp file (in src/Template/Layout) is not used ... why ? It seems that this file is never used.

Thank you

**Comment by markstory** [comment]
The error layout is used. It is used as a fallback for when an exception is raised during the rendering of an error page. This can happen when helpers used in the default layout are missing/broken.

**Comment by hozelock** [comment]
Sorry, but I don't understand.

I just did a test, I voluntarily removed the default.ctp. The error.ctp not loaded !

Is it necessary to empty the cache?

Thank you.

**Comment by ADmad** [comment]
Did you turn off debug? With debug enabled dev_error.ctp will be always used.

**Comment by hozelock** [comment]
Indeed... 

Thanks
