### ISSUE TITLE
Use cases of actual nested rest routes

### ISSUE THREAD

**Issue by pulse14** [cakephp/cakephp#8063]
```php
Router::scope('/test', function ($routes) {
    $routes->resources('Articles', function ($routes) {
        $routes->resources('Comments');
    });
});
```
If we do this and get /test/articles/1/comments, it routes to CommentsController. And I find it useless because we need to check everytime in this controller the previous resources(EDIT and combine different logic). For one previous resource it's not always easy and for 3 or 4...

A better way, above example routes to ArticlesCommentsController.

The best way for me (it's the way i build rest resources currently) is to route in Articles\CommentsController.

And 67d1c98 force me to inherit the factory. Prefix is an example of awesome things we can do with namespace routing.

So, we can't break actual design I think. Maybe another name for resource routing in namespace ?
The first thing can be to revert this commit ?

**Comment by ionas** [comment]
ArticlesCommentsController sounds really bad. For 4 ressources it is then FoosBarsQuuxBatzsController? ... and for any combination you need a new controller? What's the point then? Yes you will need to check if the uplevel ressources exist.

I do agree that it would be cool if you could pass stuff up the chain and the relevant controller does the work and checks if the resource exists.

**Comment by pulse14** [comment]
Yes for 4 ressources it's long, and some other frameworks do like this. 

Namespace is beter with low nested level but with lot of controller per level. Name is better for deep level with few controller. 

The point is not to check if uplevel resources exist but to not combine different logic (i've edited my first message). A comment in article context is not a comment in another context. And sometimes a resource do exist only in a specific context.

The combinaison will always be a problem in this classic routing we have, we need to change too much thing to avoid that. 

The actual ->resource is not the best always the best thing to do. And we need to put too much different and complex logic inside the controller or inside models.At the end we don't know what context the controller handle, it's difficult to authorize,... My suggestion is totally useless in small app, that's why we need to keep the actuel ->resource but make some enhancement.

Thank you

**Comment by ionas** [comment]
I don't really understand your complain. The last time I did nested resources was in Rails3 though.
http://blog.8thcolor.com/en/2011/08/nested-resources-with-independent-views-in-ruby-on-rails/

The basic thoughts I have on your issue are:
- Only one resource category should be handled by one controller.
- There should be no chaining of the controllers. The resource logic is being build up by the routes. That's where the URLs structure for HTTP calls is being defined.
- I can see that you might want to have a trait or something for controllers that automatically traverses up and checks stuff... Doing it that way however (instead of having similar logic in your model layer) will create multiple checking queries (instead of inner joins).
- It is true that your models would inherit the REST compatible nesting of resources (e.g. of tables/associations) build up as a tree. Again if that's the problem maybe then there should be methods that make it more easy out of the box.

**Comment by markstory** [comment]
The commit in question will not be reverted. It prevents a security vulnerability, which allows any resolvable class to be used as a controller. That exposes a risk around objects with side-effects in their constructors.

I'm sorry you find nested resource routes useless. It sounds like your use-cases are more complex and may require specialized abstractions. The simple nested resources work pretty well for scenarios similar to those described in the article @ionas linked to.

Closing as this seems like a question, and the requested revert will not happen.

**Comment by pulse14** [comment]
@markstory  Sorry, but it's not a question. That actual functionnality is only useful in simple. 

One simple exemple not so complex :

**Comment by pulse14** [comment]
10 controller exists only in user context, you want to do something in beforeFilter of childrens... I don't think a way better than mine exist...

**Comment by lorenzo** [comment]
@markstory I also miss the feature removed by that commit. Why if we added a special key to the route that can be used by the factory to whitelist or prefix the controllers namespace?

Since the security problem is only possible by routes with the :controller token, we could require that key to be present for setting a fully namespaces controller.

Do you think that is a possible solution?

**Comment by markstory** [comment]
@pulse14 Other than the classname mapping I don't see how the laravel implementation is different from ours.

**Comment by markstory** [comment]
@lorenzo Could the `prefix` key be used as a way to get subnamespaces in?

**Comment by markstory** [comment]
@pulse14 Would something like 

```php
$routes->resources('Articles', function($routes) {
   $routes->resources('Comments', ['controller' => 'ArticlesComments']);
});
```

Help solve the requirements around making nested resource classes separate?

**Comment by lorenzo** [comment]
@markstory do you have an example for that idea?

**Comment by pulse14** [comment]
@markstory thank you for reopening.
Yes it will be a good start. I think we need something like in your example and something to connect to namespaces with $routes->connect. 
And why not enhance ::Scope to handle a namespace, and all routes inside will be scopeNamespace + routeNamespace + routeController.I don't know if it's a good design but it's an idea.

You are right the only thing that change between cake and the other framework is that we can create a rest resource with a particular classname, but that solve a lot of problem...

Sorry if I was unclear. I'll try to explain what it is a good idea to route to namespace for rest ressources. 

- First it's useless for simple application like in the example.... 
- It's a fact that Rest and a traditional MC model is not the best way to handle this use cases. It's difficult to make combinaison of contexts,...

Given these facts we need to enhance this functionnality because we can't easily create context without namespaces. And it's not my invention take a look how this project is organised https://github.com/gitlabhq. Before cake 3 we didn't 
have namespace, so some of us use plugin to easily create context. But now it's possible so we need to use it. Why the prefix option routes to a different namespace ? because a controller inside a prefix context is not a controller inside another context...

**One example**

We have an user, UsersController can easily handle the admin/management context and the defaut context (when we get this user). We do it without thinking about it, nothing strange here.

Now we have a profile, adress, and so many controllers that ONLY exist in the user context. So we need an Users namespace. Now we have :

- UsersController
- Users\ProfilesController
- Users\AdressesController

The response to this : it's useless. Yes **it's useless if we think like in classic cakephp MVC app**. Users controller deserialize the whole thing and the model save the associations, we maybe only need one controller etc...

So now think Rest. Ok, we use the actual thing ->resource . We create all the controllers in the same namespace and in each we check if we are inside the user context, since the resource only exist in this context.

Now, I want a common logic to all controllers in user context (and no, trait is not a good choice I think), I want to easily beforeFilter for this context, I want to multiply the number of these cotnroller by 10 without probelm.

I understand nothing to ruby but what I understand is that the gitlab example seems like what I want to do (and what I already do in large app).

So my solution is :

- Add support for classic namespace routing with ->connect
- Add support for Controller name option for rest nested
- Add support for rest nested namespace routing

With these three things we cover a lot of situations.

Thank you

**Comment by markstory** [comment]
I think #8493 addresses this issue. I decided to go down the route of using namespace prefixes. This is congruent with other routing features we have and by using namespaces/prefixes we can get different classnames for nested resources without requiring a lot of configuration.
