### ISSUE TITLE
issues with  several uses of debug

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#8073]
hi,
After several uses of debug(),
this method crash and page reload
for example:
```
//in controllers
$this->loadModel('Articles');
$f = $this->Articles->find();
debug($f);
debug($f);
debug($f);
```
debug is crashed and page reloaded (redirect)
but if i use with 2 debug() it is  Works well and page not redirect
```
$this->loadModel('Articles');
$f = $this->Articles->find();
debug($f);
debug($f);
//debug($f);
```
or with this code is page reloaded(redirect) and controller's action  2 times  executed
```
$e = $this->Articles->newEntity();
debug($e);//1
debug($e);//2
debug($e);//3
debug($e);//4
debug($e);//5
debug($e);//6
debug($e);//7
debug($e);//8
debug($e);//9
```
after crash ,in debug_kit this  `Headers already sent at file {project}/vendor/cakephp/cakephp/src/basics.php and line 93.` Warning appear

**Comment by dereuromark** [comment]
If you use debug, you should also always halt the script using `exit();`.
Failing to do so will create the mentioned side-effects, especially with headers being sent from the response class.

**Comment by markstory** [comment]
@dereuromark Is right. At the very least you can always expect the headers sent warning, as you are sending output outside of the normal response object which is responsible for sending headers.
