### ISSUE TITLE
Cakephp 3.0 Shell Progress bar offset incorrectly

### ISSUE THREAD

**Issue by jessicamarx** [cakephp/cakephp#8076]
When I am using the cake3 progress bar in the shell, it 'works', but it is displaying it starting on the far right of my screen:

![cakeshell](https://cloud.githubusercontent.com/assets/1263821/12472243/ecaf21b8-bfd3-11e5-9583-217ef793e6d1.jpg)

it seems to be either:
   - indenting my progress bar by 116 px
   - backspacing two spaces (causing it to appear on the previous line of the page to the far right), and then printing my progress bar

Thanks.

JM

**Comment by markstory** [comment]
How could someone reproduce this issue? Do you have a small shell task that triggers the issue? I ask because the simple examples I tried all worked as they should.

**Comment by HavokInspiration** [comment]
Are you using a specific console tool ? Like Putty, or PowerShell or anything like that.

**Comment by jessicamarx** [comment]
Putty

**Comment by HavokInspiration** [comment]
PR #8204 opened.
