### ISSUE TITLE
Log query execution time and number of rows affected/returned

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#8077]
I'm testing some heavy database operations from the console and I'd like to have the same information I'm used to see in DebugKit but from the console. I see we already have this information but the LoggedQuery object returns just the query. Could we just add this information to the string representation of the LoggedQuery object?

This is really easy, I tried:

```php
public function __toString()
    {
        return "[{$this->took}ms, {$this->numRows}] " . $this->query;
    }
```

The output looks like this:
```
2016-01-21 10:41:57 Debug: [0ms, 1] INSERT INTO...
```

Anything against it? Suggestions for the output format?

**Comment by markstory** [comment]
Seems reasonable to me.

**Comment by dereuromark** [comment]
:+1:

**Comment by markstory** [comment]
`duration=$time rows=$rows` might be a nice format as it is somewhat structured making it easier to parse with grep/awk.

**Comment by dereuromark** [comment]
@markstory Can we also add some note to the docs on how to enable sql logging for CLI, like in testing etc?

**Comment by markstory** [comment]
@dereuromark I don't see why not.

**Comment by ADmad** [comment]
Having duration and rows info would be nice but not if should be added to output of `__toString()`. If we do so how would one get just the sql?

**Comment by berarma** [comment]
@markstory OK, it's more descriptive.

@ADmad All properties are public: LoggedQuery::query.

**Comment by ADmad** [comment]
@berarma Ah, I miss understood. The proposed change is for `LoggedQuery::__debugInfo()` not `Query::__debugInfo()`. :+1: in that case.

**Comment by markstory** [comment]
Closing as a pull request is up now.
