### ISSUE TITLE
Cakephp 2.8-RC1 is blackholing all Form Submits

### ISSUE THREAD

**Issue by backstageel** [cakephp/cakephp#8078]
I have tried Cakephp 2.8-RC1 on my development server, and after doing composer update, all my form requests are being blackholed... Seems that there is a CSRF error in all Forms after update to this RC version.

I managed to get the forms working again by downgrading Cake to 2.7.8 Again.

I have not yet tried to figure out where the error is... I will try to do that and update this issue if i can.

**Comment by phpnut** [comment]
@backstageel please check #8069 this change should correct the bug you are seeing

**Comment by backstageel** [comment]
Thanks
