### ISSUE TITLE
Where find best joins of CakePHP 3.1.7 + Oracle or how to fix this errors 

### ISSUE THREAD

**Issue by mbhd90** [cakephp/cakephp#8079]
Welcome to CakePHP v3.1.7 Console
---------------------------------------------------------------
App : src
Path: /var/www/html/3.0/app-master/src/
PHP : 7.0.2-2+deb.sury.org~trusty+1
---------------------------------------------------------------
Bake All
---------------------------------------------------------------
One moment while associations are detected.
Exception: Cannot describe s_i18_n. It has 0 columns. in [/var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 98]
2016-01-21 15:07:24 Error: [Cake\Database\Exception] Cannot describe s_i18_n. It has 0 columns.
Stack Trace:
#0 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(64): Cake\Database\Schema\Collection->describe('s_i18_n', Array)
#1 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/ORM/Table.php(423): Cake\Database\Schema\CachedCollection->describe('s_i18_n')
#2 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/ORM/Table.php(499): Cake\ORM\Table->schema()
#3 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(194): Cake\ORM\Table->primaryKey()
#4 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(110): Bake\Shell\Task\ModelTask->getAssociations(Object(Cake\ORM\Table))
#5 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(96): Bake\Shell\Task\ModelTask->bake('SI18N')
#6 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/BakeShell.php(250): Bake\Shell\Task\ModelTask->main('SI18N')
#7 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php(51): Bake\Shell\BakeShell->Bake\Shell\{closure}('SI18N', 0)
#8 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/BakeShell.php(253): Cake\Collection\Collection->each(Object(Closure))
#9 [internal function]: Bake\Shell\BakeShell->all('SI18N')
#10 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/Shell.php(443): call_user_func_array(Array, Array)
#11 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(212): Cake\Console\Shell->runCommand(Array, true, Array)
#12 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(179): Cake\Console\ShellDispatcher->_dispatch(Array)
#13 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch(Array)
#14 /var/www/html/3.0/app-master/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#15 {main}

**Comment by ionas** [comment]
I am not sure if Oracle is supported out of the box, check the docs.
Looks like the ORM is trying to fetch the Schema. You would need to disable this auto fetching and define the schema per table in your app code - though that's just theory on my part (did not do that in 3.x only in 2.x).

Also this seems to either be a question or a feature request which should be supplemented by a PR (Oracle support) or an RFC Support for Oracle?

**Comment by markstory** [comment]
Oracle is not supported right now. If you're using an oracle driver and having issues you should talk to the maintainer of that driver.
