### ISSUE TITLE
Marshaller doesn't link needed associations if it contain the primary key

### ISSUE THREAD

**Issue by GLacourt** [cakephp/cakephp#8082]
I tried to create a complex entity with newEntity method and the result wasn't good:

i build data myself and it looks like that:

    $entity = [
        'id' => (float) 85,
        'couche' => [
            'nom' => 'EP'
        ],
        'nom' => 'ARMOIRE',
        'geometrie' => 'ponctuel',
        'parentalite' => (float) 1,
        'classe_elements' => [
            (int) 0 => [
                'id' => (float) 148,
                'nom' => 'ENVELOPPE',
                'multiple' => null,
                'indice' => (float) 1,
                'caracteristiques' => [
                    (int) 0 => [
                        'id' => (float) 1028,
                        'nom' => 'Date d\'installation',
                        'type' => 'Date',
                        'indice' => (float) 2
                    ]
                ]
            ]
        ]
    ]

then i simply call `$entity = $this->ClasseOuvrages->newEntity($entity, ['associated' => ['Couches', 'ClasseElements.Caracteristiques']]);`

But this method won't build the relation between ClasseElements and Caracteristiques, here the result:

    object(App\Model\Entity\ClasseOuvrage) {
        'id' => (int) 85,
        'couche' => object(App\Model\Entity\Couche) {
            'nom' => 'EP',
            '[new]' => true,
            '[accessible]' => [
                '*' => true
            ],
            '[dirty]' => [
                'nom' => true
            ],
            '[original]' => [],
            '[virtual]' => [],
            '[errors]' => [],
            '[repository]' => 'Couches'
        },
        'nom' => 'ARMOIRE',
        'geometrie' => 'ponctuel',
        'parentalite' => (int) 1,
        'classe_elements' => [
            (int) 0 => object(App\Model\Entity\ClasseElement) {
                'id' => (int) 148,
                'nom' => 'ENVELOPPE',
                'multiple' => (int) 0,
                'indice' => (int) 1,
                '[new]' => false,
                '[accessible]' => [
                    '*' => true
                ],
                '[dirty]' => [],
                '[original]' => [],
                '[virtual]' => [],
                '[errors]' => [],
                '[repository]' => 'ClasseElements'
            }
        ],
        '[new]' => true,
        '[accessible]' => [
            '*' => true,
            'classe_elements' => true
        ],
        '[dirty]' => [
            'id' => true,
            'couche' => true,
            'nom' => true,
            'geometrie' => true,
            'parentalite' => true,
            'classe_elements' => true
        ],
        '[original]' => [],
        '[virtual]' => [],
        '[errors]' => [],
        '[repository]' => 'ClasseOuvrages'
    }

I check related tables and entities try different things found in the doc but nothing works. so i tried this:

    $entity = $this->ClasseOuvrages->ClasseElements->newEntity($entity['classe_elements'][0], [
        'associated' => ['Caracteristiques']
    ]);

and it works:

    object(App\Model\Entity\ClasseElement) {
        'id' => (int) 148,
        'nom' => 'ENVELOPPE',
        'multiple' => null,
        'indice' => (int) 1,
        'caracteristiques' => [
            (int) 0 => object(App\Model\Entity\Caracteristique) {
                'id' => (int) 1028,
                'nom' => 'Date d'installation',
                'type' => 'Date',
                'indice' => (int) 2,
                '[new]' => true,
                '[accessible]' => [
                    '*' => true,
                    'classeElement' => true,
                    'full_name' => true
                ],
                '[dirty]' => [
                    'id' => true,
                    'nom' => true,
                    'type' => true,
                    'indice' => true
                ],
                '[original]' => [],
                '[virtual]' => [],
                '[errors]' => [],
                '[repository]' => 'Caracteristiques'
            }
        ],
        '[new]' => true,
        '[accessible]' => [
            '*' => true
        ],
        '[dirty]' => [
            'id' => true,
            'nom' => true,
            'multiple' => true,
            'indice' => true,
            'caracteristiques' => true
        ],
        '[original]' => [],
        '[virtual]' => [],
        '[errors]' => [],
        '[repository]' => 'ClasseElements'
    }

however if i delete the id of classe_element from the basic data it also works

    unset($entity['classe_elements'][0]['id']);

I think it's about the method _belongsToMany in Cake\ORM\Marshaller.php i'm not sure to get all this code but if i don't misunderstand, if the primary key is found in the data it check the existence in datasource but it never associate the extra associations passed in options and contained in `$associated` var.

Can someone help with this issue ?

Ty

**Comment by ionas** [comment]
This is a question - it seems to me.

Try `$entity = $this->ClasseOuvrages->newEntity($entity, ['associated' => ['Couches', 'ClasseElements', 'ClasseElements.Caracteristiques']]);`

Also try to use IRC, the Book, The Api, Google Groups, Web Search, Stackoverflow, as this is an issue tracker not a help forum.

**Comment by markstory** [comment]
Without knowing how the associations are defined it will be very difficult to diagnose this issue. If you are linking to existing belongsToMany associations is is generally better to use the `_ids` property, or a list of ids instead of supplying a full record. Giving the full record will often result in duplicated objects.

**Comment by GLacourt** [comment]
@ionas i understand but i think it's a real issue un \Cake\ORM\Mashaller. Also i searched for hours to find some answers but no results, so i check every process uses in entity creation.

@markstory here my tables:

### ClasseOuvragesTable.php

    public function initialize(array $config)
    {
        $this->displayField('nom');
        $this->hasMany('Ouvrages');
        $this->hasOne('Icones');
        $this->belongsTo('Couches', [
            'foreignKey' => 'couche_id',
            'propertyName' => 'couche'
        ]);
        $this->belongsTo('CompteClients');
        $this->belongsToMany('ClasseElements', [
            'through' => 'ClasseElementsClasseOuvrages',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);
        $this->addBehavior('Timestamp');
    }

### ClasseElementsTable.php

    public function initialize(array $config)
    {
        $this->primaryKey('id');
        $this->displayField('nom');

        $this->hasMany('Caracteristiques', [
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);

        $this->hasMany('Elements', [
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);

        $this->belongsToMany('ClasseOuvrages', [
            'through' => 'ClasseElementsClasseOuvrages',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);
    }

### ClasseElementsClasseOuvragesTable.php

    public function initialize(array $config)
    {
        $this->table('classe_elements_classe_ouvrages');

        $this->belongsTo('ClasseOuvrages');
        $this->belongsTo('ClasseElements');
    }

### CaracteristiquesTable.php

    public function initialize(array $config)
    {
        $this->belongsTo('ClasseElements');

        $this->hasMany('Valeurs', ['dependent' => true]);

        $this->hasMany('CatalogueCaracteristiques', [
            'foreignKey' => 'caracteristique_id',
        ]);
    }

Every entities have the following statement:

    protected $_accessible = [
        '*' => true
    ];

I tried everything with entities, tables and options in newEntity method every tips in doc have been tested but it doesn't work for this case

**Comment by markstory** [comment]
Thanks @GLacourt. So the problematic association is a HasMany inside a BelongsToMany association? I'll try to reproduce that situation and see what's up.

**Comment by GLacourt** [comment]
Yes it is, however be certain to nest the BelongsToMany association in an other entity. I did several test and it fail only when i tried to build an entity which contain a BTM association which contain a HasMany association. (2 lvl deep).

I inspect the Marchaller class all days and reproduce this class but with specifics needs for my own. I'm pretty sure it's about the _belongsToMany method if the passed data got a primary key it check in datasource if it exists then you build the entity and add extra _joinData but i think u should re run a $this->one($data[$i], $options); in the last foreach.

**Comment by markstory** [comment]
The data for both your `classe_elements` and `caracteristiques` associations include primary key values and other data. The `newEntity()` method is not intended for modifying existing entity data, which is why you're running into issues. Instead you should use `patchEntity()` to link & update existing entities. If you are building totally new records, you should not use `newEntity()`.

The reason your `caracteristiques` association is not getting updated, is because `classe_elements` has a primary key. When the marshaller sees this while creating a 'new' entity it assumes you want to link to an existing entity. Further associations are not updated/modified as the belongs to many association resulted in a 'link' operation.

I'll see how the marshaller behaves if nested associations are loaded for existing belongs to many associations.

**Comment by markstory** [comment]
A pull request is up now.
