### ISSUE TITLE
CakePHP 3.0 Add session key config in AuthComponent

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#8084]
It is possible to add session key config in the Auth.

    protected $_defaultConfig = [
        'key' => 'Auth.User',
        'redirect' => 'Auth.redirect'
    ];

Should it be possible to do somethings like that ?

    'authenticate' => [
        'Form' => ['key' => 'Auth.Administrator'],
        'storage' => 'Session'
    ]

**Comment by ADmad** [comment]
Per authenticator storage config would complicate checking for authenticated user info on each request.

Also since 3.1 session key is no longer a config of AuthComponent itself but rather SessionStorage so you should do:

```
[
	'authenticate' => ['Form'],
	'storage' => ['Session' => ['key' => 'Auth.Administrator']]
]
```

**Comment by Aerue** [comment]
I have just modified the AuthComponent, lines 839-850

    $config = $this->_config['storage'];
        if (is_string($config)) {
            $class = $config;
            $config = [];
        } else if (is_array($config)) {
            $key = key($config);
            $class = $key;
            $config = $config[$key];
        } else {
            $class = $config['className'];
            unset($config['className']);
        }

Now it's working with config like that

    'storage' => ['Session' => ['key' => 'Auth.Administrator']]

Do you wanna a Pull request ? Like u said per authenticator it's gonna be difficult to do, but having this config dynamic can be usefull to configure different Auth Session depending on wich appController you have. (AppController / AdminAppController / ManagerAppController) ?

**Comment by ADmad** [comment]
Exactly which version are you using? Config like `'storage' => ['Session' => ['key' => 'Auth.Administrator']]` already works in 3.1. 3.0 is not going to get updates anymore.

**Comment by ADmad** [comment]
Sorry, I see that it's not working as expected. A pull request would be welcome to fix it.

**Comment by ADmad** [comment]
Sorry again. To use a custom key you have to use `'storage' => ['className' => 'Storage', 'key' => 'Auth.Administrator']` which already works. I have submitted patch to add the info to docs.

**Comment by RiteshParyali** [comment]
in my cake 3.6 this one is working
`use Cake\Event\Event;

public function beforeFilter(Event $event){
$this->Auth->sessionKey='Auth.Admin';
}
`
