### ISSUE TITLE
--quiet does not work in the test runner

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#8086]
```
# ./Console/cake test app Plugin/Foo/Model/Bar --quiet
PHPUnit 3.7.38 by Sebastian Bergmann.

unrecognized option --quiet
```

We are using the latest 2.*

**Comment by markstory** [comment]
Yep. PHPUnit doesn't support quiet.

**Comment by tersmitten** [comment]
That explains a lot :-) Is there a work around?

**Comment by dereuromark** [comment]
@tersmitten Whats the use case you need it for? Usually it works for everyone just fine the way it currently works.

**Comment by markstory** [comment]
The only workaround I can think of is to pipe stdout to /dev/null.

Closing as there isn't much we can do to alter the behavior of PHPUnit.

**Comment by tersmitten** [comment]
I'm trying to suppress output from `CakeLog::error($foo, 'debug');`

**Comment by tersmitten** [comment]
Thanks for thinking along
