### ISSUE TITLE
[2.7] CakePHP on PHP7

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#8087]
- Warning about `srand` wanting an integer, got string:

https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Utility/Security.php#L190
```php
// Warning (2): srand() expects parameter 1 to be integer, string given
srand(Configure::read('Security.cipherSeed'));
```
This should be cast to int, no?

- Sessions:
I have a basic `DatabaseSession` configuration.
`Warning (4096): session_regenerate_id(): Failed to create(read) session ID: user (path: /var/lib/php/sessions)`

```
CakeSession::renew() - APP/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 756
SessionComponent::renew() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/SessionComponent.php, line 150
AuthComponent::login() - APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
```

- `Warning (2): session_write_close(): Session callback expects true/false return value in [Vendor/cakephp/cakephp/lib/Cake/Network/CakeResponse.php, line 1462]`

Fixed by casting return values of `DatabaseSession::write()` to `bool`. The return value was `model->save()`.

---

Is CakePHP 2.7 even tested on PHP 7 ... ?

**Comment by dereuromark** [comment]
@davidsteinsland As you can see from the travis files, only 2.8+ is PHP7 compatible.
Please upgrade to that if you need PHP7 compatibility.

**Comment by davidsteinsland** [comment]
No, I'm not upgrading to a non-stable RC version in our production environments.

**Comment by markstory** [comment]
> Is CakePHP 2.7 even tested on PHP 7 ... ?

No it is not. One of the goals for 2.8 is to resolve PHP7 compatibility issues. The 2.8 release is API stable, and we're hoping that people using 2.x and PHP7 try it out in non-production setups and help us flush out any remaining issues.
