### ISSUE TITLE
2.8 with php7 and Redis Session/Cache

### ISSUE THREAD

**Issue by bringerofrain** [cakephp/cakephp#8090]
Just upgraded from 2.7 to 2.8 and the Session is no longer carrying from page to page, as if Session_Start is not being performed correctly.  It works fine with php7 and cakephp2.7.x and php5.6 with cakephp2.6.x.

**Comment by phpnut** [comment]
@bringerofrain are you using most recent changes that have been pushed to the branch?

**Comment by bringerofrain** [comment]
No, I have the version attached to the Site: 2.8 RC1 Head a530414.

I'll pull that last commit in a few and try to see if that fixes it.

**Comment by bringerofrain** [comment]
TY appears the latest version had a patch for the issue.
