### ISSUE TITLE
2.x to 3.x: silent find(list) failures

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8097]
After upgrading to 3.x, a lot of find(list) clauses do not contain keyField or valueField, but instead a select with 1 or 2 custom fields.
In 2.x those would automatically populate instead of the fallbacks primaryKey and displayField.
in 3.x the result here now silently is:
```
	(int) 0 => null,
	(int) 1 => null,
	(int) 2 => null,
	(int) 3 => null,
	(int) 4 => null,
	(int) 5 => null,
	(int) 6 => null,
	(int) 7 => null,
	(int) 8 => null,
        ...
```
After applying this patch at the beginning of findList() it worked as it used to again:
```
        if (!isset($options['keyField']) && !isset($options['valueField'])) {
            $select = $query->clause('select');
            if ($select && count($select) <= 2) {
                $options['keyField'] = array_shift($select);
                $options['valueField'] = array_shift($select) ?: $options['keyField'];
            }
        }
        ...
```
Resulting in
```
	'22' => 'Chris',
	'34' => 'Domino',
	'41' => 'Helena',
	'12' => 'Jana',
        ...
```

Is this fallback worth implementing in 3.x, or should it reside with sth like Shim plugin?
I do find it quite useful to automatically use the select clause fields if provided, instead of having to set both key and value field on top.

The alternative could be to throw exceptions as soon as you have a select clause and the auto-selected key and value Fields are not part of it...

**Comment by ionas** [comment]
* Did you setup primaryKey and displayField in your table classes?
* It should also work if you just set primaryKey and no displayField. Internally then displayField should be === primaryKey.
* Shouldn't it pick primaryKey (or Keys with semicoli) => displayField (or displayFields with semicoli)
* Not sure if would be entirely BC

If you want to add any fields required to fetch primaryKeys and displayFields then why not add an option, that is by default set to true, which automatically adds primaryKeys and/or displayFields to the select? Like say autoFields => true...

**Comment by dereuromark** [comment]
We are not talking about primaryKey or displayField, but any other fields=>x, y case.

**Comment by dereuromark** [comment]
Actually, the primaryKey+displayField case also not works when using model prefixing:

    'fields' => ['Users.id', 'Users.username'],

also runs into the issue above right now - and is fixed with the suggested solution.

**Comment by ionas** [comment]
That's out of conventions then? Was that part of the 2.x convention (e.g. pick 1st and 2nd field in select) There is keyField and valueField to specify those?

If you specify those (keyField and valueField) - I hope they do get added to select clause automatically (if not, thats :+1: PR) - and possibly nothing else (if not inherited from other querys).

You want to say that in case primaryKey and/or displayfield is not selected you want to automatically populate keys and/or values by the first and/or second field that is part of the select clause? More Magic? :(.

I'd say instead of the fields hashkey you would want to use keyField and ValueField and then be done with it? The prefixing not working is weirdo though.

**Comment by dereuromark** [comment]
Yes, thats how it worked in 2.x
I am also OK with throwing an exception if you use valueField/keyField and a select clause that does not contain those, but we need to do something here, because otherwise you don't see that is broken unless you actually look into why the select fields are empty rows of nothing.

**Comment by ionas** [comment]
:+1: letting the user know that he did something that will obviously not work. <3

**Comment by lorenzo** [comment]
It is difficult to know if it will be an error, since we now have virtual properties in the entities and the finder supports extracting properties from nested entities

**Comment by ionas** [comment]
Is this possible?
* If keyField is set, upon shortly before executing the query, check if it is in the select clause?
* If valueField is setup, upon shortly before executing the query, check if is in the select clause?
* If no keyField is set, upon shortly before executing the query, check if the primaryKeys are in the select clause?
* If no valueField is set, upon shortly before executing the query, check if the displayField(s, should be Plural, no clue) are in the select clause?

**Comment by dereuromark** [comment]
@ionas The last two are invalid, as those must always be set (if not set the findList method does it for you).

**Comment by markstory** [comment]
Is there a reason the backwards compatible behavior should only be applied if there are 2 or fewer fields? Are you trying to avoid situations where there could be more ambiguity?

Given that virtual fields can be used with find(list) I don't think an error is a good idea. However, reading from the currently selected fields feels reasonable to me.

**Comment by dereuromark** [comment]
Yes, exactly @markstory .
