### ISSUE TITLE
3.x: Fallback error templates to non ext ones

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8099]
In 3.1 latest, when trying to work with extensions, one runs into:

```
Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing
```

When opening some `/controller/action.pdf` URL.

Sure, I don't want to have custom error templates for all extensions.
My assumption would be that it will fallback to non-ext ones (Error\error500.ctp) from Cake itself, when this specific layout is not found.
This would make it more DRY, because I only have to add error templates for the cases where I want to change error behavior (or stay inside the current type) based on the extension.

After some debugging I found out that it wanted to throw an error `'Error\pdf\missing_helper'` because of a missing helper, but ended up throwing fatals because of missing error layout it should not necessarily expect in the first place.

**Comment by ionas** [comment]
:+1:

**Comment by markstory** [comment]
Turning off extensions in `_outputMessageSafe` sounds reasonable to me. That method is only invoked when rendering the original error page has failed.

**Comment by markstory** [comment]
Is PDF rendering being handled by a view class? I tried to replicate this with the standard View class and didn't have any success. I did the following:

1. Enable RequestHandlerComponent
2. Add route extension `$routes->extensions(['json', 'csv']);`
3. Make `src/Template/Bookmarks/csv/index.ctp` that loads an invalid helper.

The MissingHelper page was rendered correctly as expected.

**Comment by dereuromark** [comment]
Yes PDFview class from foc.

**Comment by hmic** [comment]
:+1: 
This buggs me long time...

Whenever you use a custom viewclass with an extension, you cannot render the default html error templates and all exceptions thrown cascade to a 500 because of missing layout/template/...

**Comment by markstory** [comment]
> Yes PDFview class from foc.

Sounds like that view class needs fixing then.

**Comment by markstory** [comment]
There is not much that error handling can do if custom view classes are manipulating the view template paths.

**Comment by hmic** [comment]
Any custom view class I've seen does it this way.

So whats the correct option to do so?

Dakota/Excel does the same and suffers the same problems e.g.
This viewClass does binary output, like the pdf view too, whats the correct approach other than saying they need fixing? - Seems nobody has come up with a better approach or fix for now...

Shed light on us please!

**Comment by dereuromark** [comment]
And none of those custom view classes actually manipulate error handling.
It should just fallback on the default ones for exception handling in the case spefied above.

**Comment by markstory** [comment]
>  It should just fallback on the default ones for exception handling in the case spefied above.

That's not possible. The error handling code [resets the view template path](https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L348-L360). We could overwrite the templatePath after creating the view class, but we risk breaking any custom pathing that views do.

**Comment by hmic** [comment]
Why would that risk anything?

It's in an error rendering state before this happens anyways. Everything that needs to be done to actually display the error instead of cascading it further, should be done.

Why not just create the correct view class for the error message after all? - Not the custom one?

**Comment by dereuromark** [comment]
I am thinking of sth simple like

    try {
        // normal error handler
    } catch {
        // reset paths and use default one
    }

**Comment by markstory** [comment]
> Why would that risk anything?

I've learned not to make assumptions about what could be safe around application code.

> Why not just create the correct view class for the error message after all?

Getting the 'correct' view class is of course the challenge here. You might think that we could use `View` but I'm sure there exists an application out there that only has twig template for example.

**Comment by hmic** [comment]
If its not guessable, just make it configurable in the errorhandler configuration and app.php!

**Comment by markstory** [comment]
@hmic You can subclass the ExceptionRenderer already :smile:

**Comment by dereuromark** [comment]
I would like to reopen this issue.
It is a constant pain when developing with extensions...

> [Cake\View\Exception\MissingLayoutException] Layout file "Admin/Layout/ics/dev_error.ctp" is missing

a) admin prefix
b) ics extension

I cant and wont put error templates for all possible scenarios inside those many subfolders for each extension and prefix.
What I would like to see is the following:

- file_exists() on that one
- otherwise just fallback to main dev_error.ctp (without prefix and without ext).

Any objections?

**Comment by markstory** [comment]
>  It is only for this view rendering - and in this case even only for debug mode - so no harm IMO.

If you have a patch in mind, a pull request would be great. I think this isn't as simple as it initially seems and we run the risk of disrupting custom view classes.

**Comment by hmic** [comment]
This is a big issue with custom viewclasses and extensions ever since...
I'd be up for a proper fix finally!

👍

**Comment by othercorey** [comment]
I'm going to attempt to resolve this. Has anything changed?

**Comment by othercorey** [comment]
From what I've tested, this issue occurs with prefixed routes as well.
