### ISSUE TITLE
Question regarding $GLOBALS in CakePHP.

### ISSUE THREAD

**Issue by Maikuolan** [cakephp/cakephp#8100]
Hi,

I have a quick question regarding `$GLOBALS` in CakePHP, that I'm hoping someone with experience with CakePHP could possibly answer.

I've never used CakePHP, nor have I yet looked at the source code (this would be my logical next step in answering this question, failing a response here, but, I thought I'd ask here first, because asking would be the quicker and easier path to getting an answer, if someone has the answer).

I've briefly skimmed over the information available on the CakePHP homepage, so, I think I have a basic understanding of the purpose of CakePHP and how it's supposed to work, although I could be wrong, of course; I've had no prior exposure to it.

My question: Does CakePHP mess around at all with the `$GLOBALS` superglobal in PHP at any point during execution, and specifically, does it unset or destroy this superglobal at any point during execution?

The reason I'm asking is because this may possibly tie into an __*[issue](https://github.com/Maikuolan/phpMussel/issues/81)*__ currently being experienced by a user of one of my own software projects here on GitHub at the moment, whereby this user has encountered problems as a result of the `$GLOBALS` superglobal not being correctly set at the point where my software (which works by being hooked early in the execution chain of a user's CMS, framework, forum, etc, using a `require` statement) requires it [the superglobal].

I've been told that my software has been hooked to the *controller* part of CakePHP.

Thanks in advance.

Kind regards,
Caleb M / Maikuolan.

**Comment by jhli** [comment]
Take the PHP docs and look for super globals. 

Take your de facto cake version, recursive search your local files for those super globals and the 'globals' keyword and report back your findings and cakephp version in case something feels funny.

**Comment by AD7six** [comment]
There are no references to `$GLOBALS` in the code base:

![screenshot from 2016-01-25 10-30-14](https://cloud.githubusercontent.com/assets/33387/12547110/a2a6c4d0-c34e-11e5-9f1c-6696d6687ff3.png)

So: "no".

**Comment by Maikuolan** [comment]
Hm, interesting.

Thanks for the replies. I'm glad to hear that CakePHP doesn't seem to be doing this, because it would be a very unusual thing for a framework package to do.

In any case, for some reason, something in the user's setup seems to be doing this. I'll keep digging and hopefully get to the bottom of this somehow. :-)
