### ISSUE TITLE
Cakephp 3: cookie was not found in client's browser

### ISSUE THREAD

**Issue by Penergy** [cakephp/cakephp#8106]
I tried to use CookieComponents to generate cookie in  client's browser.

In Appcontroller, the codes are like: 
```php
public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Cookie');

    }

public function beforeFilter(Event $event){
        parent::beforeFilter($event);
        // no cookie, no user
        if(!$this->Auth&&!$this->Cookie->read('cart_info')){  
            // Cookie configuration
            $this->Cookie->configKey('cart_info', [
                'expires' => '1 month',
                'httpOnly' => true,
                'domain' => 'localhost'
            ]);
            $cart['cookie_id'] = md5(uniqid(microtime(true),true)); 
            $cart['user-agent'] = $this->request->header('User-Agent'); 
            $this->Cookie->write('cart_info', $cart); 
        }
    }
```
When i checked Chrome, I haven't found the cookie called cart_info. On the other hand, I used cakedc users plugin. The remember_me cookie was saved in the browser.

I wonder whether i missed some steps or it is a defect from cakephp 3.

regards,

**Comment by markstory** [comment]
Are you sure your code is being reached? If it is, you might want to try using `curl -vvv http://localhost/path/to/action`. This should expose the raw HTTP response, which should contain the `Set-Cookie` header. Also make sure that you are setting cookies to the same domain that you're viewing the site on.

I can however confirm that the CookieComponent _does_ work.

**Comment by Penergy** [comment]
@markstory you are right. My code isn't reached. But I don't know where the problem is.

**Comment by Penergy** [comment]
I had another try. Firstly, I wrote cookie information on one view. And then I checked the **set-cookie** header on the other view. The first request showed the **set-cookie**, but the second request didn't showed the same information.
