### ISSUE TITLE
3.x: Time::parseDateTime rejects unix time 0

### ISSUE THREAD

**Issue by ChrisDBrown** [cakephp/cakephp#8109]
Any combination of formats & times that results in IntlDateFormatter::parse returning 0 will cause Time::parseDateTime to return null. For instance:

```
// returns $time = null;
$time = Time::parseDateTime('1970-01-01 00:00:00', 'yyyy-MM-dd');
```

This is due to the if statement in Time::parseDateTime:
```
$time = $formatter->parse($time);
if ($time) { ... }
```

As 1970-01-01 is clearly a real date, this should not be rejected.

**Comment by markstory** [comment]
Closing as there is a pull request up now.
