### ISSUE TITLE
<meta http-equiv> vs <meta charset>

### ISSUE THREAD

**Issue by mizerydearia** [cakephp/cakephp#8111]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset

This &lt;meta&gt; element is a synonym for the pre-HTML5 &lt;meta http-equiv="Content-Type" content="text/html; charset=IANAcharset"&gt;

https://github.com/cakephp/cakephp/blob/master/src/View/Helper/HtmlHelper.php

77:            'charset' => '&lt;meta http-equiv="Content-Type" content="text/html; charset={{charset}}"/&gt;',

Suggested change to

77:            'charset' => '&lt;meta charset="{{charset}}"/&gt;',

**Comment by ADmad** [comment]
Sounds good, would you like to submit a pull request to update?

**Comment by markstory** [comment]
Closing as a pull request is open now.
