### ISSUE TITLE
Add HtmlHelper support for less/sass, minify and combine

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#8119]
i propose this enchantment, because a very common task in web development is minify and combine css/js assets.
it would be cool if cakephp htmlhelper can do that.

**Comment by dereuromark** [comment]
Everything needed here is provided and available as plugins already:
https://github.com/FriendsOfCake/awesome-cakephp#asset-management
IMO this is out of scope of the default HtmlHelper.

**Comment by doshu** [comment]
I have already seen the friendsofcake plugin but most of them should use workaround to integreate with the cakephp core.
the best way should be that cakephp itself can offers some other features.

**Comment by ADmad** [comment]
[AssetCompress](https://github.com/markstory/asset_compress) plugin is developed and maintained by one of the lead devs of Cake and works perfectly fine with Cake without any workarounds. Keeping it separate makes management easier and it won't be integrated in to core.

**Comment by markstory** [comment]
Like @ADmad said AssetCompress is a good medium-sized solution. If you need more robust asset pipeline tools, you'll likely want a node based tool like gulp, grunt or webpack.  Tightly integrating CakePHP with these tools is not something that we'll do as the javascript build tool space changes so rapidly its foolish for us to try and pick a 'winning horse'
