### ISSUE TITLE
Traversing collection more than once causes emptying translations

### ISSUE THREAD

**Issue by mirorac** [cakephp/cakephp#8121]
Hello,

I traversed and formatted (using formatResults) my result two times (two finders) - causing `TranslateBehavior::groupTranslations()` is called twice. This behavior empties `_translations` property in entity, because `_i18n` property is no longer available. 

I fixed it with condition.
```php
if(empty($translations)){
    return $row;
}
```
added on line 460 behind
```php
$translations = (array)$row->get('_i18n');
```
edit:
Please let me know, if the problem is in my code. 
I have my own finder which inserts formatter via `$query->formatResults();`
my format function is traversing `$results` collection in foreach loop 2 times. After the first foreach loop entity looks good but after second foreach (or `Collection::first()` call) `_translations` property becomes empty. Maybe I should eliminate formatter when traversing collection somehow.

I use my finder in combination with findTranslations
```php
//contoller
$this->Pages->find('myFinder')->find('translations');
```

Thanks.

**Comment by markstory** [comment]
What does your code look like? A snippet of what is causing the problem will help in reproducing and fixing the issue.

**Comment by mirorac** [comment]
hope this will help to resolve the issue
```php
    public function findTypeDataInjected(Query $query, array $options)
    {
        return $query->formatResults(function ($results){
            return $this->injectTypeData($results);
        });
    }

    public function injectTypeData(\Iterator $pages)
    {
        $index = [];
        $data = [];
        
        //fill the $index
        foreach($pages as $k => $page){
            $model = $page->type->model;
            $index[$model][$k] = $page->id;
        }
        //everything all right here, `_translations` property available

        //removed some stuff which fills $data array ($pages not manipulated)

        //put data to entity
        foreach($pages as $k => $page){
            $page->data = $data[$k];
        }
        //_translations property empty! already inside the foreach loop
        //groupTransations' trace: called after Collection::current(), which I think is called when iterating via foreach
        
        return $pages;        
    }
```

alternatively

```php
    public function injectTypeData(\Iterator $pages)
    {
        $index = [];
        $data = [];
        
        //$pages->count() == 1

        //fill the $index
        foreach($pages as $k => $page){
            $model = $page->type->model;
            $index[$model][$k] = $page->id;
        }

        //removed some stuff which fills $data array ($pages not manipulated)

        debug(spl_object_hash($page)); //page from the last foreach iteration
        debug($page->get('_translations')); //OK :)

        $page = $pages->first();
        debug(spl_object_hash($page));
        debug($pages->get('_translations')); //empty :(

        //put data to entity
        foreach($pages as $k => $page){
            $page->data = $data[$k];
        }
               
        return $pages;        
    }
```
_note: spl_object_hash() returns the same value for both_

**Comment by markstory** [comment]
Thanks. I'll see if I can reproduce the issue.

**Comment by markstory** [comment]
Thanks for the tip @mirorac I've put up a pull request - #8158

**Comment by mirorac** [comment]
What about some option to eliminate formatters and mapReduce or simply just _decorateResults. This could improve performance for cases, when it is not needed. For example result formatter mentioned above would appreciate it.

**Comment by markstory** [comment]
@mirorac I don't understand what you're suggesting.
