### ISSUE TITLE
Bug: allowMethod() and extensions

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8130]
This is happening in 3.1 and 3.2:

NewsletterController::add action:
```php
$this->request->allowMethod(['post', 'put']);
```

Controller test case:
```php
	/**
	 * @expectedException MethodNotAllowedException
	 * @return void
	 */
	public function testAdd() {
		$this->get(['controller' => 'Newsletter', 'action' => 'add', '_ext' => 'json']);

		$this->assertResponseContains('"code": 405');
	}
```
Test fails.

If you try to open the URL `/newsletter/add` in the browser, it will throw the exception,
but if you navigate to `/newsletter/add.json` it will have white screen of death (0 output).

Stepping through the dispatching, I can see that the exception is being thrown and the BaseErrorHandler invoked. But from there it somehow just dies away when using extensions.

The extension works, because using post will result in a 200 OK with JSON data:

    $this->post(['controller' => 'Newsletter', 'action' => 'add', '_ext' => 'json'], $data);

Could be related to https://github.com/cakephp/cakephp/issues/8099, but I doubt it since there is no reason to involve layouting for a JsonView response.

PS: debugging `debug($this->_response->body());` in the test case reveals boolean `false` as content.

**Comment by dereuromark** [comment]
Further debugging shows that it is still OK when running into ExceptionRenderer::render() and `$this->controller->set($unwrapped->getAttributes());`.

After `$this->_outputMessage($template)` then inside this method then JsonView calls parent::render() and for some reason returns false. This is the reason I get 0 output.

![2](https://cloud.githubusercontent.com/assets/39854/12695897/0b0295f2-c75c-11e5-96a9-e31bc3bc0232.JPG)

Everything is fine, and then json_encode returns false. Without any indication what's wrong.

**Comment by dereuromark** [comment]
I was able to modify the "return $this->_serialize" call to have some exception at least:

	$result = $this->_serialize($serialize);
	if ($result === false) {
		throw new InternalErrorException('JSON Result Invalid.');
	}

HAH, I found the solution. Adding the stack trace is a bad idea it seems.
Using `unset($serialize[3]);` and not outputting the stack trace makes it work again.
```
{
    "message": "Method Not Allowed",
    "url": "\/newsletter\/add.json",
    "code": 405
}
```

**Comment by markstory** [comment]
Odd. Do you have an unserializable object in your stack somewhere? From a simple local test, I don't have the same issue.

**Comment by markstory** [comment]
Pull request up now. See #8131
