### ISSUE TITLE
Lowercased prefixes instead of camelized

### ISSUE THREAD

**Issue by Wouter0100** [cakephp/cakephp#8134]
In 3.1.9 this commit, 351faea8640a72351bbc1bfc6f7757f422431a34, made it to the release. This currently breaks this [3.x project (Croogo)](https://github.com/croogo/croogo/tree/3.0) because all prefixes are camelized in the folder structure and the namespaces. When chancing a camelized prefix folder and namespace to lowercase, it works flawless. On the error page (thrown by the `MissingControllerException`) also shows camelized prefix folders and namespaces, so I don't think it should be lowercased.

When reverting the code in `ControllerFactoryFilter` it works flawless with camelized prefixes.

We're using the `DashedRoute`.

**Comment by dereuromark** [comment]
I can confirm that this issue is both present in 3.1.9 (3.1.8 is OK) and 3.2.0.
The issue is effecting all prefix URLs, e.g.

    /admin => routing to OverviewController::index()

Is now also not found anymore etc.
```php
Router::prefix('admin', function ($routes) {
	$routes->connect('/', ['controller' => 'Overview', 'action' => 'index']);
}
```
