### ISSUE TITLE
Cakephp 2.x doesnt import foreign key during fixture creation?

### ISSUE THREAD

**Issue by backstageel** [cakephp/cakephp#8136]
Hi,

I have tables with foreign key constraints in mysql. But these constraints are not imported during fixtures creation, both by setting model=true or table='table_name'.

Basically i want to make sure that there is no Profile with user_id set to 1000 when there is no User with id =1000.

MySQL has constraint for that, but in cakephp test i can't do that.

How cakephp is supposed to handle these constraints? do i have to check it programmatically on my code?

**Comment by jadb** [comment]
How are you loading your fixtures? Using bake or using import?

**Comment by jadb** [comment]
Also, which version of cake?

**Comment by backstageel** [comment]
using import.

Cakephp 2.8RC1

public $import = array('table' => 'alunos');

but created the records using 

public $records = array(
		array(
			'id' => '1',
			'codigo' => '20093821',
			'user_id' => '2',
			'data_ingresso' => '1900-01-01',
			'trabalhador' => 0,
			'area_trabalho_id' => null,
			'instituicao_id' => null,
			'curso_id' => '40',

There is a constraint in MySQL saing that curso_id is a foreign_key to cursos table.
And the tests should fail when i try to save a row in alunos with curso_id that doesnt exist in cursos table

**Comment by markstory** [comment]
Fixtures in 2.x do not handle foreign key constraints at all. This was implemented in 3.x though.

Closing as there are no plans to implement foreign keys in 2.x fixtures at this point in time.
