### ISSUE TITLE
Prefixrouting broken after upgrade to 3.2

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8143]
Using
`Router::prefix('admin', function ($routes) {`
`    $routes->fallbacks('DashedRoute');`
`}`

results in a `MissingControllerException` being thrown by the `Dispatcher` class. It tells me to create the class in the specific file, however the file exists and I even renamed the file and recreated it with the sample code - does not work at all.

**Comment by Wouter0100** [comment]
Fixed in #8137.

**Comment by boindil** [comment]
Hi,
thanks! I did search for the problem, but oversee it ... I can confirm this fix works for me. :+1:
