### ISSUE TITLE
Plugin routes are not matched when dashed

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8150]
Usually, `admin/plugin/controller/action` works just fine with DashedRoute and admin prefix + plugin name.
But when a CamelCase plugin, then it fails, and always sees the plugin as controller part:

```
/admin/setup-extra/uptime
or
/admin/setup-extra/uptime/index
```

gets

```
[
    'controller' => 'setup-extra',
    'action' => 'uptime',
    'pass' => [],
    'prefix' => 'admin',
    'plugin' => null
]
```

expected was

```
[
    'controller' => 'uptime',
    'action' => 'index',
    'pass' => [],
    'prefix' => 'admin',
    'plugin' => 'setup-extra'
]
```

The route config of the plugin is:

``` php
Router::prefix('admin', function ($routes) {
        $routes->plugin('SetupExtra', function ($routes) {
            $routes->connect('/', ['controller' => 'SetupExtra', 'action' => 'index'], ['routeClass' => 'DashedRoute']);
            $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
            $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
        });
});
```

Plugin is enabled using

``` php
Plugin::load('SetupExtra', ['routes' => true]);
```

Latest 3.2 branch, so after the recent fixes.

**Comment by dereuromark** [comment]
Debugging it I found out that all of those $this->paths elements in RouteCollection are underscored as

    /admin/setup_extra/

But the strpos comparison done is with the original URL part

    /admin/setup-extra/uptime

So this can't work.
We need to inflect the paths elements before trying to match here for dashed route.

**Comment by markstory** [comment]
The plugin scope always uses underscores as it is applied outside of route class customizations. The same is true for the prefix() scope method.

We would need to add more options to the various scope helpers to accomodate dashed inflections.

**Comment by dereuromark** [comment]
I just remembered how it got it work a few months back:
https://github.com/dereuromark/cakephp-sandbox/blob/3.0/plugins/AuthSandbox/config/routes.php

```php
Router::prefix('admin', function ($routes) {
		$routes->plugin('AuthSandbox', ['path' => '/auth-sandbox'], function ($routes) {
			$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
			$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
		});
});
Router::plugin('AuthSandbox', ['path' => '/auth-sandbox'], function ($routes) {
		$routes->connect('/', ['controller' => 'AuthSandbox', 'action' => 'index'], ['routeClass' => 'DashedRoute']);
		$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
		$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
});
```

While this works, it might still be valuable to look into a more native approach here for DashedRoute.
More importantly, though, the prefix should work with dashes, I did not try that yet.

**Comment by ADmad** [comment]
`inflect` option was added to `RoutesBuilder::resource()` to allow customization the inflector method. Same could be done for other methods.

**Comment by steinkel** [comment]
Would it make sense to make dashed routes the default for `RoutesBuilder::resources()` the same way we have `DashedRoute` generated as the fallback route in the cakephp/app project?

**Comment by markstory** [comment]
@steinkel I think the issue here is that the `$routes->plugin()` scope helper defaults to `_` and not `-` as it can't use the current default route class to inflect the static path segment that is generated.

**Comment by markstory** [comment]
Closing as #10037 implements this.
