### ISSUE TITLE
3.2 prefix routing not working

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#8153]
Hello there, i have a problem with prefix routing.
```php
<?php
use Cake\Core\Plugin;
use Cake\Routing\Router;
use Cake\Routing\RouteBuilder;

Router::defaultRouteClass('DashedRoute');

Router::prefix('api', function (RouteBuilder $routes) {
    $routes->prefix('v1', function (RouteBuilder $routes) {
        $routes->extensions('json');

        $routes->connect('/me', ['controller' => 'Users', 'action' => 'me']);
    });
});

Plugin::routes();
```

Controller location is `src/Controller/Api/V1/UsersController.php`.
```php
<?php
namespace App\Controller\Api\V1;

/**
 * Class UsersController
 * @package App\Controller\Api\V1
 *
 * @property \App\Model\Table\UsersTable $Users
 */
class UsersController extends ApiController
{
    public function me()
    {
        $this->set('user', $this->Auth->user());
    }
}
```

It always return `
Error: UsersController could not be found.
Error: Create the class UsersController below in file: src/Controller/Api/V1/UsersController.php`

Route params:
plugin: (null)
prefix: api/v1
controller: Users
action: me

**Comment by ADmad** [comment]
Are you using latest 3.2.1 release?

**Comment by codercms** [comment]
@ADmad just updated to 3.2.1
And now i have a new error: `Error: A route matching "array ( 'controller' => 'Users', 'action' => 'login', 'plugin' => NULL, 'prefix' => 'api/v1', '_ext' => NULL, )" could not be found.`

**Comment by ADmad** [comment]
What URL are you accessing?

**Comment by codercms** [comment]
@ADmad /api/v1/me

**Comment by ADmad** [comment]
Did such routing work for you in earlier in 3.0?

**Comment by codercms** [comment]
@ADmad yes, it works on 3.1.x

**Comment by saeideng** [comment]
`( 'controller' => 'Users', 'action' => 'login', 'plugin' => NULL, 'prefix' => 'api/v1', '_ext' => NULL, )" could not be found`
you have login action?

**Comment by ADmad** [comment]
Yeah looks like you have an authentication issue and you are being redirected to a non-existent "login" action.

**Comment by markstory** [comment]
Closing as it looks like you have an auth issue.

**Comment by codercms** [comment]
@markstory @ADmad yeah, thanks, in 3.2.1 that was just a auth issue :+1:

**Comment by maninderissingh** [comment]
Hello SIr,
My Routes prefixes are not working. May be it could be my mistake, but i followed the docs. only '/' route works.  My Route is :
`Router::prefix('admin', function($routes) {
 // $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
//});`

Controller is 
` */
namespace App\Controller\Admin;

use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use App\Controller\AppController;
use Cake\Error\Debugger;
use Cake\Utility\Sanitize;
use Cake\Utility\Security;
use Cake\Utility\Hash;
use Cake\Auth\AbstractPasswordHasher;
use Cake\View\Helper\SessionHelper;
/**
 * Static content controller
 *
 * This controller will render views from Template/Pages/
 *
 * @link http://book.cakephp.org/3.0/en/controllers/pages-controller.html
 */

//App::uses('Sanitize', 'Utility');
class UsersController extends AppController
{
 function login(){
    debug("great");
}

	}`
It has been never work. If i change '/' route to this it works else not .
I have created my controller as /src/Controller/Admin/UsersController.php .
