### ISSUE TITLE
cakephp3 bake console don't bake

### ISSUE THREAD

**Issue by mitra-razmara** [cakephp/cakephp#8154]
I got a problem and solve it by myself but I think I must tell you about problem. Perhaps it is a common problem.
[http://stackoverflow.com/questions/35092330/cakephp3-bake-console-dont-bake/35123923#35123923](url)

**Comment by mitra-razmara** [comment]
I find the problem is in src/Shell folder Because only diff between two versions of src folder, is that. and when I replaced this folder, the problem solved.

**Comment by markstory** [comment]
You should use composer to do upgrades. Zip files are fraught with peril.

**Comment by mitra-razmara** [comment]
thank you markstory.
I know and I like to use composer but as I mentioned when I use composer, I can not use cake bake. I think bake command has a problem.

**Comment by jhli** [comment]
I think your OS/composer might have issues. Try chmod +x bin/cake

**Comment by jhli** [comment]
And for further help join IRC or stack or google groups.
