### ISSUE TITLE
3.3: AppView needs to be non-optional

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8155]
We already ship with an https://github.com/cakephp/app/blob/master/src/View/AppView.php
but it seems we do not require it.
This being optional is a major problem with plugin development and the current way of documenting/recommending AppView for loading helpers.

Refs https://github.com/FriendsOfCake/CakePdf/pull/146
### tl;dr

Either we revert the current recommendation and declare helpers in controller again, or we need to make AppView always existent, so we can rely on it and extend it to leverage the helper config there for on-top View classes that need this information.
And all plugins should extend AppView (not View) then, if they need the helper information (which they usually do).

**Comment by ADmad** [comment]
Making `AppView` required in 3.3 sounds good to me. We missed the boat for 3.2.

**Comment by jhli** [comment]
Could we not patch the app and add a view loader in appcontroööer that defaults to appview or do I miss the point?

**Comment by ADmad** [comment]
> ..or do I miss the point?

You do. Problem is not class loading but class inheritance.

**Comment by renan** [comment]
This will kind of force applications to *always* use `App` namespace. I don't think that is a desired side-effect.

**Comment by dereuromark** [comment]
@renan Don't we have that constraint with other classes as well?
Whats a solution?

**Comment by markstory** [comment]
I don't think requiring AppView is that great of an idea. Custom namespaces will become basically impossible if we let plugins start making assumptions about the shape of the app classes.

I also think solving these problems through inheritance might not be the best design. How else could we solve the underlying problem?

**Comment by ADmad** [comment]
Hmm I overlooked the namespacing issue. I guess the alternative would be promoting use of composition instead of inheritance in custom views.

**Comment by burzum** [comment]
Couldn't we fire an event like `View.initialize`?

**Comment by dereuromark** [comment]
I think that kind of event would be fine, too.
But we need to make sure that the helpers for example are passed in with ease.

**Comment by dereuromark** [comment]
So what's the verdict? What kind of events are desired instead of the AppView itself? :)

**Comment by burzum** [comment]
I'll implement them if we're OK to do so.

**Comment by markstory** [comment]
We could start with a single event `View.initialize`.

**Comment by cleptric** [comment]
As the `View.initialize` event hasn't archived the goal of this Issue, I reopen this to discuss further actions needed.

**Comment by dereuromark** [comment]
Any ideas here? Otherwise we can also close this as "not possible to solve".
