### ISSUE TITLE
baseUrls issue

### ISSUE THREAD

**Issue by clthck** [cakephp/cakephp#8156]
Consider the following lines in `app.php`,
```php
'App' => [
    ...
    'imageBaseUrl' => 'img/',
    'cssBaseUrl' => 'css/',
    'jsBaseUrl' => 'js/',
   ...
],
```
This means I can customize the respective BaseUrls right?
The problem is, if I change the one of them above, say, `cssBaseUrl` to 'stylesheets/' from 'css/', my cake app itself works fine, but `DebugKit` plugin, which is loaded by default for debugging purpose, malfunctions.
If I inspect the assets in browser, the plugin's `cssBaseUrl` also changes to 'stylesheets/'.
Is this intended or a bug?

**Comment by markstory** [comment]
>  Is this intended or a bug?

Intended. By changing the paths you are changing the 'conventions' for your application. Plugins are assumed to be following the application, or have their assets symlinked/copied into directories that match the application's conventions.

**Comment by clthck** [comment]
But then customizing App baseUrls in `app.php` is meaningless as I can't use 3rd party plugins if I change them right?

**Comment by markstory** [comment]
@clthck Not true at all. Changing the URLs is _very_ useful if all your static assets are on a CDN, or if you have a suite of internally developed plugins that follow a different convention. You could also use the configuration options + plugin shell to change the directory names in a more seamless manner.

**Comment by clthck** [comment]
I think that's true only if I don't use any 3rd party CakePHP plugins from packagist.org that follows standard convention.

**Comment by markstory** [comment]
@clthck Or you use the PluginShell to create symlinks/copy files.

**Comment by clthck** [comment]
Thanks for the answer. I found `cake plugin assets symlink`  is very useful.

**Comment by Erwane** [comment]
using a CDN break the assets links : 

'cssBaseUrl' => 'https://static.myleadcorner.com/buyers-test/css/',

urls in debug_kit toolbar iframe become : 
<link rel="stylesheet" href="https://static.myleadcorner.com/buyers-test/css/toolbar.css">
instead of https://static.myleadcorner.com/buyers-test/debug_kit/css/toolbar.css

i've already do "cake plugin assets symlink"
