### ISSUE TITLE
3.2: FrozenTime + toRss()

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8157]
After updating to 3.2, I have this problem with the rss.

This is my code:

	echo $this->Rss->item([], [
		'description'	=> $text,
		'guid'			=> ['url' => $link, 'isPermaLink' => 'true'],
		'link'			=> $link,
		'pubDate'		=> $post->created,
		'title'			=> $post->title
	]);

And `post->created` contains this:

	object(Cake\I18n\FrozenTime) {
		'time' => '2016-01-30T11:01:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	}

As you know, CakePHP will automatically call the `TimeHelper::toRss()` method to generate the RSS feed. And I have this exception:

> DateTime::__construct(): Failed to parse time string (30/01/16, 11:01) at position 0 (3): Unexpected character 

Can you help me understand what is the problem?

This code works fine:

		$frozen = new \Cake\I18n\FrozenTime();
		debug($frozen);
		debug($this->Time->toRss($frozen));

**Comment by mirko-pagliai** [comment]
This works:

`$post->created->toUnixString()`

So:

	echo $this->Rss->item([], [
		'description'	=> $text,
		'guid'			=> ['url' => $link, 'isPermaLink' => 'true'],
		'link'			=> $link,
		'pubDate'		=> $post->created->toUnixString(),
		'title'			=> $post->title
	]);

**Comment by markstory** [comment]
Also related to #8132

**Comment by mirko-pagliai** [comment]
Yes, fixed in `dev-master`.

But I have the same issue just showing a group of post.

`Warning (2): DateTimeImmutable::modify(): Failed to parse time string (30/01/16, 11:01) at position 0 (3): Unexpected character [CORE/src/Database/Type/DateTimeType.php, line 125]`

	$value = object(Cake\I18n\FrozenTime) {
		'time' => '2016-01-30T11:01:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	}
	$driver = object(Cake\Database\Driver\Mysql) {
		'connected' => true
	}
	$instance = object(Cake\I18n\FrozenTime) {
		'time' => '2016-02-02T16:00:54+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	}



	DateTimeImmutable::modify() - [internal], line ??
	Cake\Database\Type\DateTimeType::toPHP() - CORE/src/Database/Type/DateTimeType.php, line 125
	Cake\Database\FieldTypeConverter::__invoke() - CORE/src/Database/FieldTypeConverter.php, line 77
	Cake\Database\Statement\CallbackStatement::fetch() - CORE/src/Database/Statement/CallbackStatement.php, line 58
	Cake\Database\Statement\StatementDecorator::fetch() - CORE/src/Database/Statement/StatementDecorator.php, line 193
	Cake\Database\Statement\BufferedStatement::fetch() - CORE/src/Database/Statement/BufferedStatement.php, line 92
	Cake\ORM\EagerLoader::_groupKeys() - CORE/src/ORM/EagerLoader.php, line 715
	Cake\ORM\EagerLoader::_collectKeys() - CORE/src/ORM/EagerLoader.php, line 701
	Cake\ORM\EagerLoader::loadExternal() - CORE/src/ORM/EagerLoader.php, line 564
	Cake\ORM\Query::_execute() - CORE/src/ORM/Query.php, line 921
	Cake\ORM\Query::_all() - CORE/src/Datasource/QueryTrait.php, line 272
	Cake\ORM\Query::all() - CORE/src/ORM/Query.php, line 871
	Cake\Controller\Component\PaginatorComponent::paginate() - CORE/src/Controller/Component/PaginatorComponent.php, line 171
	Cake\Controller\Controller::paginate() - CORE/src/Controller/Controller.php, line 689
	MeCms\Controller\PostsCategoriesController::view() - /home/mirko/Server/MeCms_Plugin/src/Controller/PostsCategoriesController.php, line 79
	Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 430

**Comment by mirko-pagliai** [comment]
home/mirko/Server/MeCms_Plugin/src/Controller/PostsCategoriesController.php, lines 66-79:

	$query = $this->PostsCategories->Posts->find('active')
		->contain([
			'Categories'	=> ['fields' => ['title', 'slug']],
			'Tags',
			'Users'			=> ['fields' => ['first_name', 'last_name']]
		])
		->select(['id', 'title', 'subtitle', 'slug', 'text', 'created'])
		->where(['Categories.slug' => $category])
		->order([sprintf('%s.created', $this->PostsCategories->Posts->alias()) => 'DESC']);

	if($query->isEmpty())
		throw new RecordNotFoundException(__d('me_cms', 'Record not found'));

	$posts = $this->paginate($query)->toArray();

**Comment by markstory** [comment]
I'll see if I can reproduce this. I've not been successful so far in getting this to happen again.

**Comment by markstory** [comment]
Pull request up to fix the fatal error when hydrating data.
