### ISSUE TITLE
ORM Slow - Cake 3.2.0 using postgresql 9.1.19

### ISSUE THREAD

**Issue by lukegithub23** [cakephp/cakephp#8160]
PostgreSQL 9.1.19 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 
(Red Hat 4.4.7-16), 64-bit

CakePHP 3.2.0
PHP 5.5.30

We've recently switched from Cake2.x to 3.2 for a new application.

However I am finding the performance to be quite slow when moving the application to our UAT and production server, linux/postgres as above.

cacheMetadata is set to true
With caching on it's usually only the initial hit that is slow but even then it's really slow.

---
The Debug SQL log shows the offending query as:

```
SELECT 
  rc.constraint_name AS name, 
  tc.constraint_type AS type, 
  kcu.column_name, 
  rc.match_option AS match_type, 
  rc.update_rule AS on_update, 
  rc.delete_rule AS on_delete, 
  kc.table_name AS references_table, 
  kc.column_name AS references_field 
FROM 
  information_schema.referential_constraints rc 
  JOIN information_schema.table_constraints tc ON tc.constraint_name = rc.constraint_name 
  AND tc.constraint_schema = rc.constraint_schema 
  AND tc.constraint_name = rc.constraint_name 
  AND tc.table_schema = rc.constraint_schema 
  JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = rc.constraint_name 
  AND kcu.constraint_schema = rc.constraint_schema 
  AND kcu.constraint_name = rc.constraint_name 
  AND kcu.constraint_schema = rc.constraint_schema 
  JOIN information_schema.key_column_usage kc ON kc.ordinal_position = kcu.position_in_unique_constraint 
  AND kc.constraint_name = rc.unique_constraint_name 
  AND kc.constraint_schema = rc.constraint_schema 
WHERE 
  kcu.table_name = 'any_table_trying_to_be accessed' 
  AND rc.constraint_schema = 'public' 
  AND tc.constraint_type = 'FOREIGN KEY' 
ORDER BY 
  rc.constraint_name, 
  kcu.ordinal_position
```

This query is run for every table being queried - on a simple page with just 3 tables being accessed it adds nearly 15 seconds for the page to render. Running the query directly in pgAdmin it usually takes around 4500ms.

With debug off and caching on, the problem is not as critical but I can't imagine this is working as intended.

using mysql locally the same pages are very quick. 
I notice the schema query is much more concise and quicker in regards to finding the constraints.
CakePHP 2.7 using that same database is also very quick.

Any suggestions/help?

**Comment by markstory** [comment]
CakePHP 2.x doesn't allow reflecting indexes or constraints. That might be part of why it runs faster.  If you know how to make that query run faster and get the same results I'd be more than happy to merge those changes in :smile:

**Comment by josegonzalez** [comment]
Note: you can avoid this by using some sort of centralized cache and running the following command on deploy to prime the cache:

```
bin/cake orm_cache build
```

**Comment by lorenzo** [comment]
Closing as we got no feedback after a couple weeks

**Comment by lukegithub23** [comment]
No feedback because nothing has changed from the above.

It's still a major problem - Cake 3 is essentially unusable with postgresql.

Sure I can turn debug off, but then I can debug while developing... with debug on it's painfully slow.

We might see if we can get some postgresql experts to optimise the query.

But if it's not being used in Cake2 is it absolutely necessary in Cake 3.x ? Maybe a config flag to turn it off or something could be a short term solution?

**Comment by ADmad** [comment]
In the default skeleton [this](https://github.com/cakephp/app/blob/master/config/bootstrap.php#L81) line of code updates the model cache config duration to `1 year` when debug is off. So you can just move that line out of the `if` block to prevent model cache being regenerated even when debug is turned on.

**Comment by lukegithub23** [comment]
Is the recommendation not to use Cake3 if you have postgresql databases?

**Comment by markstory** [comment]
@lukegithub23 Or have someone who is more fluent in postgres help optimize the queries we're using. I know that our testsuite is not orders of magnitude slower on postgres, could this issue be related to specific versions of postgres?

**Comment by lukegithub23** [comment]
On investigating this more I do not think this is an optimisation issue. I think the query is straight up wrong.

As an example: comparing mysql vs postgresql database with exactly the same table/field structure and same constraints:

The MYSQL equivalent query returns 5 rows, the constraints related to the one table in question.

Postgresql returns over 6000 rows, it returns all constraints related to ALL tables.

**Comment by markstory** [comment]
Are we missing a condition on a join clause that is causing too many constraints to be included? I'm not well versed in  the postgres' information_schema.

**Comment by lukegithub23** [comment]
We'll see what we can discover and report back.

**Comment by markstory** [comment]
@lukegithub23 Thank you :+1:

**Comment by donkeyx** [comment]
I am working on the query now and just wanted to confirm what you needed/wanted from the postgresql database. 

* Exactly what you are getting from the mysql query OR
* Just the items in the select list from your postgres version.

This will need to come from the catalog tables, as there is no way to do a valid join on the "referential_constraints" view. Anyway, if you respond with the answer to that, I can start dev on the new version.

**Comment by markstory** [comment]
@donkeyx The postgres version needs to get the equivalent metadata to what it fetches today. It does not need to be the same as the MySQL version, only similar with the current data used in the postgres adapter.

**Comment by donkeyx** [comment]
I have re-written the query to use the catalog tables and its very fast. It does not have the full names for constraint type etc.. as i was not sure if you do the conversion in the framework libs or the query, but just let me know either way. Also, I am still testing to be sure, but it seems ok so far:

`SELECT  c.conrelid::regclass::text AS table_name,
        c.contype AS constraint_type, --c = check constraint, f = foreign key constraint, p = primary key constraint, u = unique constraint, t = constraint trigger, x = exclusion constraint
        a.attname AS column_name, 
        c.confmatchtype AS match_type, --f = full, p = partial, s = simple
        c.confupdtype AS on_update, --a = no action, r = restrict, c = cascade, n = set null, d = set default
        c.confdeltype AS on_delete,  --a = no action, r = restrict, c = cascade, n = set null, d = set default
        c.confrelid::regclass AS references_table,
        ab.attname AS references_field
FROM pg_catalog.pg_constraint c, pg_catalog.pg_attribute a, pg_catalog.pg_attribute ab
WHERE conrelid::regclass = a.attrelid::regclass
AND conkey[1] = a.attnum
AND a.attrelid = ab.attrelid
AND a.attnum = ab.attnum
AND c.conrelid = 'products'::regclass
AND c.contype='f';`

**Comment by markstory** [comment]
We can do constraint action conversion in php code as the results are converted to arrays.

**Comment by donkeyx** [comment]
Coolies, so that should be good then and just needs a bit of testing. Do you need/want anything else form me or we we good?

**Comment by lorenzo** [comment]
@donkeyx If you want to contribute the code as a pull request that would be appreciated :)

**Comment by markstory** [comment]
Closing as a pull request is open now.
