### ISSUE TITLE
Segfault when calling table function from controller

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8162]
In the controller if I use `$this->myFunction()` instead of `$this->MyModel->myFunction()` I get a segfault. When calling non-existent functions I simply get an error, but when calling a function that exists in the Model, PHP 5.6 will segfault, while PHP7 will go into an endless loop, eating memory until it runs out of memory.
(CakePHP 3.2.1)

**Comment by half2me** [comment]
My bad, sorry. Just realized this was a neverending recursive function...

**Comment by jippi** [comment]
No worries :)

**Comment by half2me** [comment]
When I realized right after submitting this issue I had carefully reproduced, that my function was calling itself...
![funny-facepalm-meme-computer_zpsbb54a0ce](https://cloud.githubusercontent.com/assets/6759894/12752241/e0634d1a-c9c1-11e5-8f1e-af6b7167bd4a.jpg)
And I call myself a developer...
