### ISSUE TITLE
Fixtures not working with no $import nor $fields properties set.

### ISSUE THREAD

**Issue by Xoubaman** [cakephp/cakephp#8165]
The documentation states that:

> Finally, you can not load/create any schema in a fixture. This is useful if you already have a test database setup with all the empty tables created. By defining neither $fields or $import a fixture will only insert its records and truncate the records on each test method.

A fixture without these two properties is not setting the TextFixture->_schema property, and throwing a fatal error when calling truncateSql() in a non-object in TextFixture::truncate().

The _schema property seems to be only being set in the TextFixture::init() function, and only when the import or fields properties are set.

**Comment by HavokInspiration** [comment]
I can give this a look

**Comment by HavokInspiration** [comment]
PR #8175 opened.
