### ISSUE TITLE
Model callbacks conflicting with Tree Behavior.

### ISSUE THREAD

**Issue by lucianoqueiroz** [cakephp/cakephp#8166]
Let's suppose:

```
class Foo extends AppModel {
    public $actsAs = array('Tree');    

    public function beforeFind($queryData){
          //do something
    }

}
```

I hadn't have a tree before on my **foos** table, so I have created the fields **lft**, **rght** and tried to recover my tree based on **parent_id** value. The problem is on **recover** method inside TreeBehavior .php there are a lot of **$Model->find()** operations which use the callbacks defined on **Foo** model. I know that we have an option for **recursive** when setting up the use of a behavior but why not for **callbacks**? If there is another way to do it, I will be glad to learn.

Thanks!

**Comment by lucianoqueiroz** [comment]
What about we create a new setting for TreeBehavior.php called 'callbacks'? If we want that the searches performed inside TreeBehavior.php use callbacks we can set it to true if not we set it to false. We can let it true by default as 'recursive' is -1 by default.

What do you think about it?

**Comment by markstory** [comment]
So are your application callbacks causing issues with the tree recovery?

**Comment by lucianoqueiroz** [comment]
Yeah it is, I have some find callbacks defined on a model and when I run the TreeBehavior->recover(), some finds operations are using these callbacks... I think we could have at least a setting option to disabled it If we want to recover the whole tree, independent of callbacks that we had defined before.

I have tested setting the callbacks to false on find operations called inside **_setParent** and **recover** methods in TreeBehavior.php and it has worked, so I think it would be fine we have an option to disable callbacks on these find operations.

Thanks!

**Comment by lucianoqueiroz** [comment]
What would be better? The default callback settings value set to **true** or **false**?

**Comment by lucianoqueiroz** [comment]
I think it would be better set it to **false** since the recursive option is set to **-1** by default.

**Comment by markstory** [comment]
recursive and callbacks are not linked at all. To preserve current behavior, the default must be `true`.

**Comment by lucianoqueiroz** [comment]
Nice! I'm gonna do it as you said and make a pull request

**Comment by markstory** [comment]
@lucianoqueiroz Looking forward to it.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.
