### ISSUE TITLE
3.1 SecurityComponent doesnt handle input[] correctly

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8170]
When creating input fields with the HtmlHelper and `name => Articles[something][]`, the request is blackholed.
This is caused by FormHelper imploding the field name into Articles.something. and the SecurityComponent using Hash::flatten and after that adding the "multi"-field as Articles.something (without the trailing dot).
I didnt try with 3.2, as I did not update yet.

**Comment by markstory** [comment]
I'll take a look and see if I can reproduce the issue.

**Comment by markstory** [comment]
Pull request open now.
