### ISSUE TITLE
I can't use an existing model name as an association alias for another one

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#8173]
I'm trying to use Guests as an alias in a hasMany association for model SpecialGuests. The code:

```php
$this->hasMany('Guests', [
    'className' => 'SpecialGuests',
]);
```
Since model Guests exists the association uses this model instead of SpecialGuests.

I found the control block that checks that a model with the alias name exists, then ignores the _className_ option. I don't know if this is done on purpose.

Isn't the _className_ option intended to override the defaults on cases like this one?

**Comment by berarma** [comment]
I think I'm understanding it now, although I'm surprised. It seems alias names are globally registered so they shouldn't be duplicated neither by other aliases or model names. I think I can accomplish what I want with the _propertyName_ option but I wasn't aware I shouldn't be using _className_ since I think I'm cluttering the model/alias namespace. I though aliases were always local to the query/association where they were being used.

**Comment by ADmad** [comment]
Each aliased model instance in maintained in a global table registry to avoid creating duplicate instances. So your aliases need to be unique application wide.

**Comment by berarma** [comment]
Thanks for confirmation.
