### ISSUE TITLE
Hash::sort multi-dimensional array

### ISSUE THREAD

**Issue by Smetje** [cakephp/cakephp#8177]
Found a bug in sorting a multi-dimensional array if the $path (sorting key) isn't available in every element.
for example:

```
$array = array(
				array(
					'id' => 1,
					'title' => 'element 1',
					'extra' => 1,
				),
				array(
					'id' => 2,
					'title' => 'element 2',
					'extra' => 2,
				),
				array(
					'id' => 3,
					'title' => 'element 3',
				),
				array(
					'id' => 4,
					'title' => 'element 4',
					'extra' => 4,
				)
			);
```

$array = Hash::sort($array, '{n}.extra', 'desc', 'natural');`

As you see, element 3 doesn't have the 'extra' key, and because of that the sorting isn't done right.
If you print this, it will be:

```
Array
(
    [0] => Array
        (
            [id] => 3
            [title] => element 3
        )

    [1] => Array
        (
            [id] => 2
            [title] => element 2
            [extra] => 2
        )

    [2] => Array
        (
            [id] => 1
            [title] => element 1
            [extra] => 1
        )

    [3] => Array
        (
            [id] => 4
            [title] => element 4
            [extra] => 4
        )

)
```

Problem is caused by 
```
// Make sortValues match the data length, as some keys could be missing
		// the sorted value path.
		if ($sortCount < $dataCount) {
			$sortValues = array_pad($sortValues, $dataCount, null);
		}
```

Here you add the 'missing' values add the end of the array, not at there correct places.

**Comment by markstory** [comment]
What are you expecting in this case?

**Comment by Smetje** [comment]
Correct sorting on the choosen key, like this for descending:
`
Array
(

    [0] => Array
        (
            [id] => 4
            [title] => element 4
            [extra] => 4
        )

    [1] => Array
        (
            [id] => 2
            [title] => element 2
            [extra] => 2
        )

    [2] => Array
        (
            [id] => 1
            [title] => element 1
            [extra] => 1
        )

    [3] => Array
        (
            [id] => 3
            [title] => element 3
        )

)
`
Here it was sorted on the 'extra' key with values descending. Elements without the 'extra' key have a 'null' value, so they were added at the bottom. For Ascending directions the elements without the 'extra' key would be the first after sorting.

**Comment by Smetje** [comment]
In my project I only need the sorting for arrays with numeric keys, so this is how I have fixed it, until a better solution is presented:

`
// Make sortValues match the data length, as some keys could be missing
// the sorted value path.
if ($sortCount < $dataCount) {
	if ($numeric) {
		$sortValues = array();
		foreach($data as $key=>$value) {
			$extracted = self::extract($value, substr($path, 4));//Remove first {n}. from path, this can only with numeric keys
			if (!empty($extracted)) {
				$extracted = $extracted[0];
			} else {
				$extracted = null;
			}
			$sortValues[$key] = $extracted; 
		}
	} else {
		$sortValues = array_pad($sortValues, $dataCount, null);
	}
}
`

Its not the best solution, but it fixes my problem and I can finish my project.

**Comment by markstory** [comment]
I'll take a look.

**Comment by markstory** [comment]
@Smetje Thank you for the patch it was helpful. Closing now as a pull request is up.
