### ISSUE TITLE
Failed tests leave database in inconsistent state

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8187]
If I run my unit tests, but I have some problems with my fixture, causing an abort, for example:
`Insert value list does not match column list:` Upon exiting, it leaves the database in an inconsistent state, because it will have inserted some fixtures, created some tables, but not others. Then after I fix the problem in my fixtures, and run the tests again I get this error: `SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name` This is because it is trying to insert the foreign key constraints again.

My suggestion would be to use a transaction when inserting the fixtures, so upon an error, it can easily be rolled back, and I would not have to delete and re-create the test database in such a case.

**Comment by markstory** [comment]
This gets me all the time. I'll take a look at I routinely have to do silly things like `mysql -u root -e 'drop database testdb; create database testdb;`

**Comment by HavokInspiration** [comment]
Yeah, I usually have the problem, and it is bugging me as well.
My first hunch would be to wrap the ``FixtureManager::load()`` call from ``FixtureInjector::startTest()`` in a try/catch and find a way to wipe the db if an exception is caught. There might be a cleaner way to do it though.

**Comment by markstory** [comment]
I remember in 2.x the fixture manager would remove drop tables and recreate them the first time they were used. This might have gotten lost when foreign key management was improved to fix ordering issues.

**Comment by HavokInspiration** [comment]
Hm, I might have done it unintentionally indeed.
My memory might be failing me but I remember having the issue since I start contributing to the project.

However your solution is better. 

I can give it a look if you want.

**Comment by half2me** [comment]
Wouldn't it be easier to simply wrap it in a transaction? If using try/catch, we could just abort the transaction on failure. Let the database do the cleanup for us?

**Comment by ADmad** [comment]
@half2me Not all db engines support transactions.

**Comment by markstory** [comment]
MySQL for example does not support schema changes inside transactions.

**Comment by HavokInspiration** [comment]
PR #8232 opened.
