### ISSUE TITLE
FormHelper doesn't add a default id for specific input types

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#8189]
When you create specific input types, `FormHelper` doesn't add the default generated id (the one created with `_domId()` function). 

So, if we want to use `FormHelper` to create specific inputs intead of using the `input()` method (because the html structure for example, or some other reason), using also `label()` method for labels doesn't seems to work... or at least it's unintuitive.
Let's see this example:

```php
<div class="label-class"><?= $this->Form->label('somefield') ?></div>
<div class="input-class"><?= $this->Form->text('somefield') ?></div>
```

If I try to guess what the helper is going to do there, I'll bet that will create an input text an a label for it. But it doesn't, instead makes a label tag with its "for" attribute populated with an id done by `_domId()`, and makes an input text tag without id. So as result we have a label and an input that nothing have to do with each other.

**Comment by markstory** [comment]
Not including a DOM ID is intentional. If you want auto-generated ID attributes you'll need to use input().

Adding IDs at this point could break applications by introducing duplicate ID attributes on the page.

**Comment by xavier83ar** [comment]
Yes, I imagined that was intentional, but don't you think that the use case I've put as an example is at least inconsistent and unintuitive? Also, right now, if you use the `input()` method more than once, with the same name, you'll get duplicate ids. If you said that talking about to change the api, you're right, and I know that we can change it just like that. But, I think the real problem here is that we do not have access to the `_domId()` method, so we can't create automatically an id equal to the one that `label()` method has use in its "for" attribute.

So, I was thinking that and option could be that if "id" key is true, then the `formHelper` adds an auto-generated id. What do you think?

Something like this:
```php
<?= $this->Form->text('somefield', ['id' => true]) ?>
```

**Comment by markstory** [comment]
I think having `id` => true` is a reasonable backwards compatible way for people to opt into automatic ID generation.

**Comment by jhli** [comment]
Could we in any way make available 'FormHelper::domId()', too?

**Comment by jadb** [comment]
Closing this, PR #8206 opened to address it.
