### ISSUE TITLE
Combine migrations, fixtures and tests...

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#8190]
I have a plugin which has tests which works great. However, people started mention me because the migration failed. So that made me think:

- should I test my migrations?
- why aren't my migrations used as fixture, at least to initialize the table?

Please explain me what I am missing because the fact that migrations are not tested doesn't feel good... If I'm missing nothing we should think about a way to integrate migrations into fixtures...

**Comment by markstory** [comment]
> why aren't my migrations used as fixture, at least to initialize the table?

Not everyone uses CakePHP's migrations.

> should I test my migrations?

I would test backfills, but schema changes should be covered by the application/plugin's tests.

**Comment by HavokInspiration** [comment]
There's the possibility to test your migrations... in some way.
You can use the ``Migrations`` class which will allow you to run migrations in a non-shell environment. You can see [the doc for this class here](http://book.cakephp.org/3.0/en/migrations.html#running-migrations-in-a-non-shell-environment).

This should allow you to test that your migrations are correctly running in the various environments you are testing your plugin with.

**Comment by dereuromark** [comment]
Closing as a possible solution has been pointed out.
