### ISSUE TITLE
Truncate text function / inside html tags

### ISSUE THREAD

**Issue by marc60** [cakephp/cakephp#8193]
I use the latest function truncate from cakephp. 

This function truncate also words inside of html tags for example:

```
Text Text Text <a href="/test.php"><u>Linktext</u></a> Text Text
```

truncate to:

```
Text Text Text <a href="/test.php"><u>Lin...</u></a>
```

What I want is, skip all words inside of html tags

Is this possible?

**Comment by markstory** [comment]
No. That is not possible.
