### ISSUE TITLE
No way to get a single transaction in HasMany::link(), unlink()

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#8196]
hi
follow :https://github.com/cakephp/cakephp/pull/8194
for every $targetEntities entity, 1 transaction query per entity is run
for example:

```

BEGIN

UPDATE 
  articles 
SET 
  user_id = 2 
WHERE 
  id = 1

COMMIT
BEGIN

UPDATE 
  articles 
SET 
  user_id = 2 
WHERE 
  id = 2

COMMIT
BEGIN

UPDATE 
  articles 
SET 
  user_id = 2 
WHERE 
  id = 3

COMMIT
. . .
```

but: must just 1 BEGIN & COMMIT runs for all query

**Comment by asifameer** [comment]
Yes it is a problem here.

**Comment by markstory** [comment]
There does seem to be transactional() wrapper missing around the unlink and relink operations. The `unlink()` method also does not support doing all unlinks with a single transaction.

Does it make sense that in all of these methods the `$options['atomic']` key should enable doing all changes in a single operation?

**Comment by saeideng** [comment]
i think BelongsToMany::link()/unlink() just runs with a single transaction
in my code that work well

**Comment by saeideng** [comment]
why not use Table::save() ,Table::delete() for HasMany::link() or  unlink()?

**Comment by markstory** [comment]
@saeideng You're right it is only HasMany::link/unlink that are missing transactions.

Just using `save()` wouldn't let the old parent be updated in the same transaction.

**Comment by saeideng** [comment]
thanks @markstory 
in `unlink()` should not be removed  its dependence?
now, It can not be removed
also 'Application Rules' no check

**Comment by markstory** [comment]
@saeideng I think of link() and unlink() are more advanced features. Much like `deleteAll()` and `updateAll()` advanced features can easily bypass the domain rules as they are intended to be used when normal record based updates are not efficient.

**Comment by Zuluru** [comment]
Seems to me that unlink should also return a bool, false if any of the `delete()` calls fail (for example, if a beforeDelete returns false to stop the event)?

**Comment by saeideng** [comment]
i agree with @Zuluru  
@markstory ,Milestone is 3.3.0
This means that it will be corrected in version 3.3.0 ?

**Comment by markstory** [comment]
@saeideng Yes if someone comes forward with a patch/pull request.

**Comment by ADmad** [comment]
Closing as the issue has gone stale. If there is still interest a pull request to address the issue is welcome.
