### ISSUE TITLE
View Caching system ignores spaces between non-ascii characters in the url

### ISSUE THREAD

**Issue by mohsen-ekhtiari** [cakephp/cakephp#8197]
The following urls are treated the same by view caching system:

http://example.com/search?name=%CE%B1+%CE%B2 (plus between alpha and beta)
http://example.com/search?name=%CE%B1%CE%B2 (no plus between alpha and beta)

As I examined the _beforeDispatch_ method of _CacheDispatcher_, I found the problem in the slug generated by Inflector::slug() method which converts both _+%_ and _%_ to underscore.

**Comment by mohsen-ekhtiari** [comment]
I've created the pull request, too.

**Comment by AD7six** [comment]
It would be more appropriate to e.g. [hash the url, instead of slug it](https://github.com/cakephp/cakephp/blob/2.next/lib/Cake/Routing/Filter/CacheDispatcher.php#L53) than modify `Inflector::slug` to do something it's not expected to do.

**Comment by mohsen-ekhtiari** [comment]
But I think hashing the url makes it difficult to find and clear the cache.

**Comment by markstory** [comment]
But having spaces in filenames seems wrong for 'slugged' filenames.

**Comment by mohsen-ekhtiari** [comment]
It is not actually space character, it's a plus "+" in the url, which seperates words from each other.

**Comment by AD7six** [comment]
@mohsen-ekhtiari a plus is a url encode space.

**Comment by mohsen-ekhtiari** [comment]
@AD7six: Yes you're right. But the issue still exists. and I can't distinguish between words with non-ascii characters.

**Comment by mohsen-ekhtiari** [comment]
I think changing the plus(es) sign to underscore before passing it to Inflector::slug() is a good idea.

**Comment by AD7six** [comment]
@mohsen-ekhtiari that might work in your given example but a better solution would be to (as I mentioned previously) simply not use `Inflector::slug`. That method is being used to get a filename-safe string - it is IMO a better idea to use a method specifically designed to take a string and make it a "safe" filename; the characters that are not safe in a url (a slug) are not the same characters that are not safe in a filename.

That said this is a feature which was removed in 3.x - a patch would be considered, but I don't expect any change to come from the core team.

**Comment by mohsen-ekhtiari** [comment]
@AD7six You're right. It's generally better to use another method for generating filename-safe strings. That method may even decode the url in order to generate more readable filenames probably in unicode.

**Comment by markstory** [comment]
Closing as it has been many months and the proposed changes would have broken existing behavior.
