### ISSUE TITLE
assertHeader is asserting equality instead of containment

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8199]
I am writing unit tests for my API which always returns json responses.
I use `$this->assertHeader('Content-Type', 'application/json');` to make sure that the appropriate json headers are set. However I have the charset=UTF8 header also set. The test fails with:
``` php
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'application/json; charset=UTF-8'
+'application/json'
```

Instead of asserting if the two strings are equal, shouldn't it just assertContains?

**Comment by dereuromark** [comment]
Well, assertContains should return false positives for sth like

    application/js vs application/json

etc.
Might not be a valid example, but there might be some out there. Whatever you change it would also effect all header checks.

So it would maybe be better to split at `;` for `Content-Type`, making the first part the relevant comparison part here.

**Comment by markstory** [comment]
The behavior you're observing is intentional. We could add an `assertHeaderContains()` but I don't think changing `assertHeader()` is wise.

**Comment by half2me** [comment]
I understand. Still I think there could be a case where I would like to check if a key in the header has been set, without asserting the entite header. UTF-8 testing is out of the scope of the particular unit test I was running. I would simply like to test if the json key was set. Maybe we could have a function which can test for the presence of a key in the semicolon separated list of header key-value pairs, and see if one of them matches? Maybe have a assertHeaderKey or something, which would check only that particular one?

**Comment by dereuromark** [comment]
That is too specific for your headder, and will not fit to any other header types.
Adding `assertHeaderContains()` should suffice. Do you want to make a PR?

**Comment by half2me** [comment]
@dereuromark alright, assertHeaderContains() sounds good. I'll submit a PR.
