### ISSUE TITLE
[2.8] Validator::uploadedFile() fails on key checking

### ISSUE THREAD

**Issue by Dismounted** [cakephp/cakephp#8201]
The fix in #4567 needs to also be backported to 2.8.

The validator expects the format to be:
```
Array
(
    [0] => name
    [1] => tmp_name
    [2] => error
    [3] => type
    [4] => size
)
```

While (at least in my installation on Ubuntu 14.04) provides:
```
Array
(
    [0] => name
    [1] => type
    [2] => tmp_name
    [3] => error
    [4] => size
)
```

Hence validation fails.

**Comment by Dismounted** [comment]
Also began to port the fix for this, but not sure where to branch from? 2.x doesn't seem to contain 2.8 code, and 2.next has already been bumped to `2.9.0-dev`?

**Comment by markstory** [comment]
The `2.x` branch should have 2.8.0 now. I think I forgot to push a branch last night. Sorry about that.

**Comment by Dismounted** [comment]
Do you want me do the port? Not sure if you're already working on it.

**Comment by markstory** [comment]
I can take care of it tonight.

**Comment by markstory** [comment]
Pull request up now.
