### ISSUE TITLE
How about a database specific connection interface?

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#8210]
Whenever I'm working with connection objects retrieved from a table object, I need to type hint the returned object in order to get proper code completion, since `\Cake\Datasource\ConnectionInterface` doesn't include all the methods of the `\Cake\Database\Connection` class, which by default is being used for table objects.

The table class itself relies on the connection to be of type `\Cake\Database\Connection`, so I'm wondering if it would make sense to have a database specific connection interface that `Table::connection()` could use instead?

**Comment by markstory** [comment]
Any reason you don't hint on `Cake\Database\Connection`?

**Comment by ndm2** [comment]
That's exaclty what I do, using an inline type hint, or a doc block hint for an overridden `connection()` method in a base table class, both of which I'd like to avoid if possible.

Or did you ment changing the typehint for `Table::connection()` to `Cake\Database\Connection`?

**Comment by lorenzo** [comment]
in my mind, changing the typehint in `Table::connection` makes sense. Adding another interface is also a good option, if you want to take care of it :)

**Comment by ndm2** [comment]
Sure, I can give it a shot :)

**Comment by ndm2** [comment]
Despite also being kind of a fix, this would also be kind of a breaking change, signatures would change in any case, so I guess the earliest that this could target would be the next 3.x release? Or maybe even later?

**Comment by lorenzo** [comment]
This is one reason I don't like type hints a lot :(

I guess we will need to do it in a 3.x release and write the migration steps

**Comment by ndm2** [comment]
Solved by #10629
