### ISSUE TITLE
getMockForModel uses default datasource when cacheMethods are disabled

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#8225]
When cacheMethods are disabled in CakePHP 2.7.* getMockForModel makes atleast once use of default datasource instead of test datasource.

**Comment by markstory** [comment]
What is special about when cacheMethods is off?

**Comment by tersmitten** [comment]
If I'm correct (@mvdriel) `Model::_setSource` behaves differently

**Comment by mvdriel** [comment]
It is not totally clear to me what is going wrong, but when I disable cacheMethods the following code in UserTest with autoFixtures disabled fails (and succeeds when cacheMethods is enabled):

```
$this->loadFixtures('User');
$this->getMockForModel('User');
```

with the following error:

`MissingTableException: Table users for model User was not found in datasource test.`

**Comment by markstory** [comment]
I wasn't able to reproduce this issue . I tried to disable both `cacheMethods` and `cacheSources` but with no luck. The following test does not fail with an error.

```
App::uses('ConnectionManager', 'Model');
App::uses('Article', 'Model');

class ArticleTest extends CakeTestCase {

	public $fixtures = array(
		'app.article',
		'app.comment'
	);

	public $autoFixtures = false;

	public function setUp() {
		parent::setUp();
		ConnectionManager::getDataSource('test')->cacheSources = false;
		ConnectionManager::getDataSource('test')->cacheMethods = false;
	}

	public function testFind()
	{
		$this->loadFixtures('Article', 'Comment');
		$mock = $this->getMockForModel('Article', ['save']);
		$mock->find('all');
	}
}
```

Have I done something wrong with this test case?

**Comment by tersmitten** [comment]
What happens when you set `cacheMethods` in the constructor of `AppModel`? That how we have it.

**Comment by tersmitten** [comment]
Anything to add @mvdriel?

**Comment by markstory** [comment]
@tersmitten You disable `cacheMethods` in the Model constructor?

**Comment by tersmitten** [comment]
@markstory Yes

**Comment by markstory** [comment]
I don't see how that would provide different results than doing it before the mock is created. I'm also not seeing anywhere in `Model.php` that refers to `cacheMethods` though.

**Comment by mvdriel** [comment]
@markstory I think the main difference is that in your test cacheMathods is disabled for the test datasource and in our AppModel cacheMathods is disabled for the default datasource.

**Comment by markstory** [comment]
Ok. I'll try that.

**Comment by markstory** [comment]
Still no failing tests or errors:

```php
App::uses('ConnectionManager', 'Model');
App::uses('Article', 'Model');

class ArticleTest extends CakeTestCase {

	public $fixtures = array(
		'app.article',
		'app.comment'
	);

	public $autoFixtures = false;

	public function setUp() {
		parent::setUp();
		ConnectionManager::getDataSource('test')->cacheSources = false;
		ConnectionManager::getDataSource('test')->cacheMethods = false;

		ConnectionManager::getDataSource('default')->cacheSources = false;
		ConnectionManager::getDataSource('default')->cacheMethods = false;
	}

	public function testFind()
	{
		$this->loadFixtures('Article', 'Comment');
		$mock = $this->getMockForModel('Article', ['save']);
		$mock->find('all');
	}
}
```

**Comment by mvdriel** [comment]
@markstory But it does fail when you move the disable cacheMethods to AppModel by using the following file:

```
class AppModel extends Model {

	public function __construct($id = false, $table = null, $ds = null) {
		parent::__construct($id, $table, $ds);
		$this->getDataSource()->cacheMethods = false;
	}
}
```

**Comment by markstory** [comment]
I'll see if I can reproduce that way.

**Comment by markstory** [comment]
Closing as I was able to reproduce and put together a fix.

**Comment by mvdriel** [comment]
@markstory Thanks!
