### ISSUE TITLE
Cake Bake Plugin gives controller not found even if controller is baked.

### ISSUE THREAD

**Issue by incredibleX** [cakephp/cakephp#8229]
This is just because in cake php 3 the plugin named should always start with a capital letter, for example:
cake bake plugin contacts -> wrong
cake bake plugin Contacts is right
This is not written anywhere in the documentation, it took me 2 weeks to figure out whats wrong I'm doing.

**Comment by lorenzo** [comment]
Would you like to add that yourself to the docs?

**Comment by ADmad** [comment]
The examples in [manual](http://book.cakephp.org/3.0/en/plugins.html#creating-a-plugin-using-bake) already use CamelCased names.

**Comment by incredibleX** [comment]
Yes, can i do that?

**Comment by incredibleX** [comment]
Yeah but its not mentioned that it is not allowed to not to use smaller letters, I wasn't able to figure out what i'm doing wrong as i was following everything in the docs except i was using my name instead of ContactManager

**Comment by ADmad** [comment]
Well the manual would become pretty bloated if we go about mentioning various cases which don't work :)

**Comment by dereuromark** [comment]
But we could easily support underscored by inflecting the plugin input. I think we should do that as we do it for other cases like `cake PluginName.ShellName`.
It does not hurt and reduces friction.

**Comment by ADmad** [comment]
@dereuromark Sure, a patch for bake would be welcome.

**Comment by incredibleX** [comment]
Yeah you're right but don't you think the documentation should also take care of some pretty novice users? I've started learning it and right now I'm trying to figure out developing a theme and seriously the docx sucks. I can't figure out where to start first. There should also be a tutorial going through each phase developing a theme step by step.

**Comment by dereuromark** [comment]
@incredibleX What part of `bin/cake bake plugin ContactManager` is not understable?
It clearly shows to use CamelCase. Why are you trying to use something else than documented?

Please open a ticket or PR in https://github.com/cakephp/bake to also support under_scored via Inflection as mentioned, this should solve the issue and we can close this ticket here.

**Comment by incredibleX** [comment]
okay

**Comment by dereuromark** [comment]
I looked into it and the error message already says:

    <error>You must provide a plugin name in CamelCase format.</error>

As such I dont think there is any need for action here, either way.

But what's strange: It already camelizes in PluginTask:

    $plugin = $this->_camelize($name);

So it should have worked. And I tried myself and can confirm it works just fine:

    bin/cake bake plugin foo_bar

Results in

    Plugin Name: FooBar
    Plugin Directory: /.../app/plugins/FooBar
