### ISSUE TITLE
AuthComponent::identify() should allow ArrayObject

### ISSUE THREAD

**Issue by rfenner** [cakephp/cakephp#8240]
I recently updated to using the new mongodb php driver and library. After the update I was getting auth failures and tracked the problem to the returned data mongodb library returns a BsonDocument which extends ArrayObject. I could get around the issue by casting the returned result to array. The problem is
in identify in Authcomponent.php at line 765 this code
`            if (!empty($result) && is_array($result)) {`
doesn't recognize the ArrayObject because is_array only handles types of Array. ArrayObject should be considered valid since they are supposed to act like an array as well. 
I suggest the if statement should be changed to
`            if (!empty($result) && (is_array($result || $result instanceof ArrayObject))) {`

**Comment by rfenner** [comment]
Apparently chanfgin that line isn't the only thing needing to be done.
setUser has a type hint for array so I got a warning when I tried the above fix.
I also got a wanring in SessionStorage::write needing an array as well.

**Comment by markstory** [comment]
>  ArrayObject should be considered valid since they are supposed to act like an array as well. 

Except that all the `array_*` functions don't work on them.

**Comment by rfenner** [comment]
Thats a good point. it's a shame that they haven't made array an alias for an ArrayObject had all of the array function be able to operate on the ArrayObject.

**Comment by markstory** [comment]
One day :rainbow:

**Comment by dereuromark** [comment]
Yes one day

**Comment by lorenzo** [comment]
Maybe we could remove the typehint for setUser()

If people wants so badly to have objects in the session we could just allow it.

**Comment by markstory** [comment]
@lorenzo I'm fine with that.

**Comment by ADmad** [comment]
I too am fine with removing the typehint but that could potentially throw errors for someone who has overridden `setUser()`. Are we ok with that in a bugfix release?

**Comment by dereuromark** [comment]
This should go into the next minor IMO.

**Comment by lorenzo** [comment]
I agree with @dereuromark

**Comment by ADmad** [comment]
Closing as related PR is opened.
