### ISSUE TITLE
[Cake 2.4] Find List with CONCAT Returns Empty Data

### ISSUE THREAD

**Issue by KidA78** [cakephp/cakephp#8243]
For the following statement:

```
      $settings = [
         "fields" => [
            "CONCAT('company_', Company.id, '_branch_', b.branch_id)"
         ],

         "joins" => [
            [
                "table" => "branches",
                "alias" => "b",
                "type" => "INNER",
                "conditions" => [
                    "Company.id = b.company_id",
                    "b.branch_id" => $branch_id
                ]
            ]
         ]
      ];

    $this->Company->find('list',$settings);
```

The result set shows something like this
```
[
    '1' =>
     '2' =>
]

```

Upon investigation, the Model `findList` method does a `Hash::combine` to assemble the return array, however, the `valuePath` is generated incorrectly:

```
            [valuePath] => {n}.CONCAT('company_', Company.id, '_branch_', b.branch_id)
            [keyPath] => {n}.Company.id
```

Because in the actual result set, this key is nested under `0`, and the valuePath would have to be something like `{n}.0.Concat..` etc

We can work around this with a find('all') but this seems to clearly be a bug.

**Comment by dereuromark** [comment]
Did you try using the documented and recommended approach using virtual fields?
This approach should always work, as the field itself will be mapped to the right keys which are expected from find(list) to populate key/value pairs.

**Comment by KidA78** [comment]
@dereuromark thanks for the reply, a virtual field on the Model is something that we would use, except in this case, the concat is for a specific case, where we are concatenating values between the main model's fields, and the data returned from the join in this specific query.

**Comment by dereuromark** [comment]
You can set virtual fields on the fly. But without that they end up being numeric indexed and not string field name indexed.

**Comment by KidA78** [comment]
@dereuromark I did some more reading about virtualFields on the fly with joins, and the following DOES work with `find('list')`:

```
$this->Company->virtualFields['myField'] = "CONCAT('company_', Company.id, '_branch_', b.branch_id)";

$settings = [
         "fields" => [
            "myField"
         ],

         "joins" => [
            [
                "table" => "branches",
                "alias" => "b",
                "type" => "INNER",
                "conditions" => [
                    "Company.id = b.company_id",
                    "b.branch_id" => $branch_id
                ]
            ]
         ]
      ];

    $this->Company->find('list',$settings);
```

**Comment by dereuromark** [comment]
That is exactly how it is supposed to be done. So this is not a bug, as virtual fields like this are the only way really they can work in 2.x in combination with custom SQL snippets.

**Comment by KidA78** [comment]
@dereuromark thanks.  It may be useful, to put something in the docs that in order to get a result from the `find('list')` function, something like this would return no values.  That wasn't clear. 

Also the example I put above, involves the aliases of a join table.  It was a shot in the dark and I'm glad it worked.  Hopefully someone can come across this post and it can inform them as well.

Thanks for the quick responses.
