### ISSUE TITLE
3.2 __d() with {n} does not work where {n} is at the tail

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8250]
Broken, e.g. does not show the long title:
```php
<?= __d('api', 'Average retail price history for {0}', h($vc24_product->long_title)) ?>
```

Working, e.g. does show the long title:
```php
<?= trim(__d('api', 'Average retail price history for {0} ', h($vc24_product->long_title))) ?>
```
i.e. notice the space `'{0} '` (or any other character) behind {0} - only then the placeholder gets filled up.

Possibly a bug?

**Comment by markstory** [comment]
I will see if I can reproduce this.

**Comment by markstory** [comment]
I wasn't able to reproduce this. See 4d8a51f035becb5e289aaa5c4b2bec9b2867a4de. Could you help provide a failing test case/reproduction?
