### ISSUE TITLE
Logs: request url and referer url

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8252]
I have noticed that in the logs:
1) the request url is relative, but not at the app;
2) the referer url is absolute.

An example. Suppose my app is `http://localhost/mysite`.  
The request url will be something like `/mysite/mycontroller/myaction` and the referer url will be something like `http://localhost/mysite/referercontroller/refereraction`.

I believe that:
1) both should be relative to app url (the log will be more readable with shorter urls);
2) definitely, both should use the same syntax, even if you think that they should be absolute.

What do you think about?

**Comment by ADmad** [comment]
Referrer can be from external source so can't make it app relative nor in array syntax.

**Comment by dereuromark** [comment]
@mirko-pagliai We could maybe use [Request:.referer()](https://github.com/cakephp/cakephp/blob/master/src/Network/Request.php#L551) instead of env() that would fix it.

**Comment by mirko-pagliai** [comment]
Yes, I can do a pr, no problem.

Simply, I believe two things:
1) a relative url that is not relative to the app is simply useless. In this case, it appears to be related to the hostname. But what good is?
If I write a parser log or if I want to print my logs on screen, probably I'll want to use something like `TextHelper::autoLink()`. In this case, it does not work.
2) logs are often very long and full of data. Should be as readable as possible, so you should try to use relative url. Of course, if a referrer is external, in which case it must be absolute, it can not be otherwise.

In the next few days I'll try to make a pr, just I have a bit of time. Thank you.

**Comment by markstory** [comment]
Implemented in #8439
