### ISSUE TITLE
Strange error messages on matching() with HABTM

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8254]
I'm writing some Unit Tests
```php
// In my Unit test
public function testGetAffectedWebsitesAndProducts()
{
        $this->Reservation = $this->Table->get(2);
        $this->assertInstanceOf('App\Model\Entity\Reservation', $this->Reservation);
        // Tests pass till here:
        $affected = $this->Reservation->getAffectedWebsitesAndProducts();
        debug($affected);
}

// In my Entity
public function getAffectedWebsitesAndProducts()
{
        return TableRegistry::get('Websites')->find()
            ->where(['Websites.status' => 'UP'])
            ->matching(['Products', function ($q) {
                return $q->find('summarized')
                    ->where(['Products.reservation_id' => $this->id])
                    ->contain('ProductInfo');
            }]);
}
```
Websites HasAndBelongsToMany Products
Websites HasMany Reservations
Reservations HasMany Products
ProductInfo HasMany Products

I get the following error message on running the tests:

```php
Warning Error: explode() expects parameter 2 to be string, array given in [/home/.../vendor/cakephp/cakephp/src/ORM/EagerLoader.php, line 202]

Warning Error: array_pop() expects parameter 1 to be array, null given in [/home/.../vendor/cakephp/cakephp/src/ORM/EagerLoader.php, line 203]

Warning Error: Invalid argument supplied for foreach() in [/home/.../vendor/cakephp/cakephp/src/ORM/EagerLoader.php, line 210]

########## DEBUG ##########
object(Cake\ORM\Query) {
(unable to export object: Websites is not associated with )
 }
###########################

```

**Comment by half2me** [comment]
########## DEBUG ##########
object(App\Model\Table\WebsitesTable) {

	'registryAlias' => 'Websites',
	'table' => 'websites',
	'alias' => 'Websites',
	'entityClass' => 'App\Model\Entity\Website',
	'associations' => [
		(int) 0 => 'regions',
		(int) 1 => 'apimessages',
		(int) 2 => 'reservations',
		(int) 3 => 'products'
	],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'test'
}
###########################

**Comment by markstory** [comment]
You are calling matching() wrong. You have a wrapping array. You should use `matching('Products, function ($q) { .. })` instead.

**Comment by markstory** [comment]
See the [API docs for Query::matching](http://api.cakephp.org/3.2/class-Cake.ORM.Query.html#_matching)

**Comment by half2me** [comment]
Thanks guys, sorry for the false issue. Is there any reason though why this uses different syntax? I mean instead of using `(['something' => function ($q) {}])` as we do for modifying queries, we use `('something', ($q) {})` Is there some reason for this? If not, wouldn't it be better to use one kind of notation/syntax for these kind of overrides?

**Comment by half2me** [comment]
@markstory I changed it, that part is working, but the query seems to be generating bad SQL:
ProductInfo.sku is selected, but the table is never JOINed... :(
```php
return TableRegistry::get('Websites')->find()
            ->where(['Websites.status' => 'UP'])
            ->matching('Products', function ($q) {
                return $q->find('summarized')
                    ->where(['Products.reservation_id' => $this->id])
                    ->contain('ProductInfo');
            });
```
And this is giving me:
```sql
SELECT
  Websites.id                 AS `Websites__id`,
  Websites.region_id          AS `Websites__region_id`,
  Websites.name               AS `Websites__name`,
  Websites.url                AS `Websites__url`,
  Websites.status             AS `Websites__status`,
  Websites.local_token        AS `Websites__local_token`,
  Websites.remote_token       AS `Websites__remote_token`,
  Websites.ping_url           AS `Websites__ping_url`,
  Websites.push_stock_url     AS `Websites__push_stock_url`,
  Websites.update_stock_url   AS `Websites__update_stock_url`,
  Websites.get_stock_url      AS `Websites__get_stock_url`,
  ProductInfo.sku             AS `ProductInfo__sku`,
  Products.size               AS `Products__size`,
  (COUNT(Products.id))        AS `amount`,
  ProductsWebsites.product_id AS `ProductsWebsites__product_id`,
  ProductsWebsites.website_id AS `ProductsWebsites__website_id`
FROM websites Websites INNER JOIN products Products ON Products.reservation_id = :c0
  INNER JOIN products_websites ProductsWebsites
    ON (Websites.id = (ProductsWebsites.website_id) AND Products.id = (ProductsWebsites.product_id))
WHERE Websites.status = :c1
```
My custom finder summarized is just:
```php
return $query
            ->group(['Products.product_info_id', 'Products.size'])
            ->select(['ProductInfo.sku', 'Products.size'])
            ->select(['amount' => $query->func()->count('Products.id')])
            ->contain(['ProductInfo']);
```

**Comment by lorenzo** [comment]
You cannot use `contain()` inside `matching()`

**Comment by half2me** [comment]
@lorenzo I tried adding it outside of matching as well. It still gives the same result

**Comment by markstory** [comment]
Depending on the associations you won't get a join. HasMany and BelongsToMany never generate joins when using contain().

**Comment by markstory** [comment]
@half2me The main reason that matching and contain have different syntax is that you generally only use one association in matching() but contain() many.

**Comment by half2me** [comment]
@markstory, then how do I get the ProduktInfo.sku field into the resultset?

**Comment by half2me** [comment]
I need a query like the one I wrote. How can I change it to get the required fields into the result-set?

**Comment by markstory** [comment]
How is ProductInfo associated to the other models?

**Comment by half2me** [comment]
@markatory I wrote all the associations in the issue, a few lines up.

**Comment by markstory** [comment]
Ok, so HasMany associations don't use joins unless they are used in matching() clause.

**Comment by half2me** [comment]
@markstory So how can I write the equivalent of
"Select fields from a model MATCHING some other criteria on another mdoel. Select also fields from another third model associated to the first model"

For example: Select all articles and their associated authors, where the article has a comment by Dave.
How can I build this query?

**Comment by lorenzo** [comment]
Like this:

```php
$conditions = function ($q) {
    return $q->find('summarized')->where(['Products.reservation_id' => $this->id]);
};

 return TableRegistry::get('Websites')->find()
            ->where(['Websites.status' => 'UP'])
            ->matching('Products', $conditions)
            ->contain(['Products' => $conditions, 'Products.ProductInfo']);
```

The matching is for the `from a model MATCHING some other criteria on another mdoel` part. The contain is for the `Select also fields from another third model associated to the first model`

**Comment by half2me** [comment]
@lorenzo I just tried your code and I get:
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ProductInfo.sku' in 'field list'

SQL generated is:
```sql
SELECT
  Websites.id                                   AS `Websites__id`,
  Websites.region_id                            AS `Websites__region_id`,
  Websites.name                                 AS `Websites__name`,
  Websites.url                                  AS `Websites__url`,
  Websites.status                               AS `Websites__status`,
  Websites.local_token                          AS `Websites__local_token`,
  Websites.remote_token                         AS `Websites__remote_token`,
  Websites.ping_url                             AS `Websites__ping_url`,
  Websites.push_stock_url                       AS `Websites__push_stock_url`,
  Websites.update_stock_url                     AS `Websites__update_stock_url`,
  Websites.get_stock_url                        AS `Websites__get_stock_url`,
  ProductInfo.sku                               AS `ProductInfo__sku`,
  Products.size                                 AS `Products__size`,
  (COUNT(Products.id))                          AS `amount`,
  ProductsWebsites.product_id                   AS `ProductsWebsites__product_id`,
  ProductsWebsites.website_id                   AS `ProductsWebsites__website_id`
FROM websites Websites INNER JOIN products Products ON Products.reservation_id = :c1
  INNER JOIN products_websites ProductsWebsites
    ON (Websites.id = (ProductsWebsites.website_id) AND Products.id = (ProductsWebsites.product_id))
WHERE Websites.status = :c2
```

ProductInfo table is never actually used :(

**Comment by lorenzo** [comment]
Where is `ProductInfo.sku` coming from? Did you select the field manually?

**Comment by half2me** [comment]
@lorenzo from my custom finder method:
```php
public function findSummarized(Query $query, array $options)
{
        return $query
            ->group(['Products.product_info_id', 'Products.size'])
            ->select(['ProductInfo.sku', 'Products.size'])
            ->select(['amount' => $query->func()->count('Products.id')])
            ->contain('ProductInfo');
}

**Comment by lorenzo** [comment]
yeah, don't do that. Add the selected fields for ProductInfo in the contain instead

**Comment by lorenzo** [comment]
You will also need to select the fields that are needed for matching ProductInfo and Product (the primary key and foreignKey)

**Comment by half2me** [comment]
@lorenzo is there a way to use the fields needed for matching Models without having them put into the resultset by implicitly calling select() on them? I would like to keep the result clean without having to filter out the extra data all the time...

**Comment by lorenzo** [comment]
No, not currently, you are currently required to select those fields.... You can use the $_hiddenFields property in your entity for automatically removing those fields

 That said, if I recall correctly, you can tell contain to use the `subquery` strategy and in that case having the foreign keys selected will not be a requirement... But I cannot recall if that is how it works

**Comment by half2me** [comment]
@lorenzo I see. Do you think selecting the foreign key fields is something which could be done automatically in a future release? For example when I call a contain() on a HABTM model. These autoselected fields could be added to the $_hiddenFields by default if autofields is disabled, and only removed, when the user calls a select() on the foreign key field.
Or is this not something that we want to do?

**Comment by lorenzo** [comment]
@half2me possibly. I have been opposed to it for some time since adding more fields can alter the meaning of a query for certain types of queries
