### ISSUE TITLE
CakePHP 3.1.10: ORM return different datetime in dependense from debug

### ISSUE THREAD

**Issue by Sensetivity** [cakephp/cakephp#8269]
Hi all.
I've found an  interesting thing. When I disable debug ORM returns DATETIME field as string. When debug is enabled -  it returns DateTime object.

Other words, when you make site when debug enabled and you use something like this:

`$user->created->format('H:m:s'); `

Disabling debug mode causes  fatal error :"use property to non-object"

**Comment by lorenzo** [comment]
Can you provide a way to reproduce this issue? I just tried with a sample application and it worked as expected

**Comment by lorenzo** [comment]
Closing as a way to reproduce the issue was not provided.
