### ISSUE TITLE
Authentication redirection

### ISSUE THREAD

**Issue by sohail1050** [cakephp/cakephp#8270]
I am using cakephp 2.7.9
I am using controller named 'DistributorController' with Auth component its working fine.
In AppController I am using

public $components = array(
    'Flash',
    'Session',
    'Auth' => array(
        'loginRedirect' => array('controller' => 'distributors', 'action' => 'index'),
        'logoutRedirect' => array('controller' => 'distributors', 'action' => 'login'),
		'authError' => 'Did you really think you are allowed to see that?',
		'authenticate' => array( 'Form' => array( 'passwordHasher' => 'Blowfish', 'userModel' => 'Distributor'))
		
    ));

when I tried to visit a page which required authentication it redirects me on /users/login. I don't have Users controller in my app. I want to redirect to /distributors/login when authentication is required.
I am not able to fix this problem need your help.

**Comment by ADmad** [comment]
Use the 'loginAction' config key as stated in manual.

**Comment by sohail1050** [comment]
Thanks its working :)
