### ISSUE TITLE
Setting Cell Template Path Error

### ISSUE THREAD

**Issue by dcodadigital** [cakephp/cakephp#8271]
I completed a plug-in sometime ago which has been working great until composer did a few updates today. It appears to me the view builder template path setting has to now be referenced in a different way? I did the usual Google searches, checked the cook book / API and searched the issues section on Github and I could not find anything related to this.

So to explain I have attached a screenshot which shows the folder structure of the plugin so you can see where I am trying to call the display.ctp from and the reference to the display function:-
![cell-question](https://cloud.githubusercontent.com/assets/14294908/13088587/b7e8cb02-d4e4-11e5-9d3f-1265b0111262.PNG)

The error being shown is: Could not render cell - Cell view file "display" is missing. [CORE\src\View\Cell.php, line 262]

Any pointers would be great. Thanks

**Comment by ADmad** [comment]
Sounds related to #8163, which was fixed in #8182. Are you sure you are using the latest 3.2.2 release?

**Comment by dcodadigital** [comment]
Thanks for the response. Yeah the version I am using CakePHP v3.2.2

I spotted those tickets which do sound somewhat related to my issue. 

So out of interested I rolled the CakePHP version back to v3.2.1 and I can confirm it does work in that version. It just seems to be an issue on the latest version if that makes sense?

**Comment by ADmad** [comment]
@HavokInspiration Any idea about this?

**Comment by markstory** [comment]
I have a good idea on why this is failing.

**Comment by markstory** [comment]
Pull request up now.
