### ISSUE TITLE
[2.5.0] "Undefined index" in "Datasource/DboSource.php"

### ISSUE THREAD

**Issue by xhs345** [cakephp/cakephp#8277]
Hello, 

The issue occurred to me when trying to update my application from version 2.4 to 2.5. It seems to be closely related to [https://github.com/cakephp/cakephp/issues/4246](issue 4246). The setup in my application is a bit different to the one in the linked issue, so I wasn't able to fix it yet. The application is a bit more complex so I tried cutting down the code as much as possible.

The exact error message is: `Undefined index: id [CORE\Cake\Model\Datasource\DboSource.php, line 1498]`

It is looking as follows: I have a component 'StructuresComponent' that is using a model 'Structure'  to set validation for a model
```
// StructuresComponent
// This part can be found in the set() method. 
// $alias is in this example the 'users'
App::uses('Structure', 'Model');
$this->Component_Structure = new Structure;
				
$result = $this->Component_Structure->find('first', array(
    'conditions'	=> array( 'Structure.alias' => $alias ),
    'recursive' => 5
));
```
```
// Structure
class Structure extends AppModel {
    public $name = 'Structure';
    public $actsAs = array('Containable');

    public $hasMany = array('StructureFormat', 'Sfs')
   	
   function __construct(){
       parent::__construct();
       $this->contain(array('Sfs' => array('StructureValidation', 'StructureValueDomain')));
       App::uses('StructureValidation', 'Model');
       $this->StructureValidation = new StructureValidation();
    }
    ...
 }
```
Now the model that is apparently creating the problem is 'Sfs'. This model is using a view as a table, that doesn't have a 'id' field, only multiple foreign keys.
```
class Sfs extends AppModel {
	public $useTable = 'view_structure_formats_simplified';
	public $name = 'Sfs';
	public $hasMany = array(
		'StructureValidation' //fetched manually in model/structure
	);
}
```
One of the things I tried was setting the $primaryKey for 'Sfs' to one of the foreign keys that is unique in the table. But that caused a system error because Cake tried to create an invalid SELECT statement because it assumed the foreign key 'view_structure_formats_simplified_id' in the table 'StructureValidation'.

I would be thankful for any tips on what else to try or how to correctly implement this structure in CakePHP 2.5+.

**Comment by markstory** [comment]
2.5.0 is no longer maintained. Could you try upgrading to a current release and see if your issue is still present?

Composite primary keys are not well supported in 2.x. However, you might be able to set `$primaryKey = false` to avoid the notice error.

**Comment by xhs345** [comment]
I forgot to mention. I did actually upgrade all the way to 2.8 and then tried to fix all the issues that occurred. This one I couldn't, so I backtracked it to the specific upgrade 2.4->2.5. So yes, I'm testing with the latest 2.x release.

Regarding your advise: When I use `$primaryKey = false` then I get a different notice: `Undefined offset: 0`, which is still referencing the same part in the code (`$resultPrimaryKey = $result[$modelAlias][$primaryKey];` in DboSource.php, line 1498)

**Comment by markstory** [comment]
Hmm. Because you're loading records on a HasMany the datasources are going to really want a primary key. Composite keys will not fare well in 2.x unfortunately.

**Comment by xhs345** [comment]
I haven't finished testing yet, but I think I might have fixed it!

Here is what I did:

1. Defined a 'virtual' field `id` for the view by concatenating the composite keys
2. Manually set the correct foreignKey for the hasMany association of the view to StructureValidation

Thanks for the help, much appreciated!
