### ISSUE TITLE
[3.x] paginate component friendly not Found error

### ISSUE THREAD

**Issue by ayman-alkom** [cakephp/cakephp#8287]
Hi all

**The case:** the link has `page=x` and the x page not found, [ the link may be old ]
**The result :** break the app by `Cake\Network\Exception\NotFoundException`
**Suggest:** process this case with just a `Flash` error message like the authentication error, at least in the production case where `debug=0`.

just suggestion

**Comment by lorenzo** [comment]
You can also catch the exception and do this in your code. I do prefer the exception as the user is requesting a URL that does not exist

**Comment by markstory** [comment]
Catching the error in application code and doing the 'right' thing is something we leave up to developers as introducing default behavior means we have to take on more options/configuration to turn it off when people don't want it.
