### ISSUE TITLE
3.x Trailing slash at the end of URL

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#8289]
How to force certain route without a trailing slash at the end correspond to 404 Not Found page?
The code below doesn't work
```php
Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/simple/', ['controller' => 'Pages', 'action' => 'display', 'simple']);
}
```

**Comment by lorenzo** [comment]
Use a DispatcherFilter where you check for a trailing slash and throw a NotFoundException

**Comment by lorenzo** [comment]
Create a DispatcherFilter where you check for the trailing slash and throw a NotFoundException

**Comment by codercms** [comment]
@lorenzo but I want to make Router::url or $this-Url->build output like /simple/, not /simple. Or I should every time when I building route add trailing slash to the end manually?

**Comment by lorenzo** [comment]
You will need then a custom route class. This class will return the value of `parent::match()` after appending a trailing slash.

You can register the default route class to use using `Router:: defaultRouteClass()`
