### ISSUE TITLE
Number currency input

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#8290]
In CookBook about `Number::currency` (http://book.cakephp.org/2.0/en/core-libraries/helpers/number.html#NumberHelper::currency) is wrote two different information about first argument `$number`. First in arguments is `mixed`, but line below is `float`.

When I put in first param `Number::currency('12,34')` then I get `12,00`. Works fine with float.

This is only problem in documentation or maybe I can put strings?

Cake 2.8

**Comment by lorenzo** [comment]
You should not input strings to that function. It is a problem with the docs... Would you like to submit a pull request to fix it?

**Comment by kicaj** [comment]
https://github.com/cakephp/docs/pull/3764

**Comment by dereuromark** [comment]
PR open.
