### ISSUE TITLE
Allow options to be passed into Auth finder methods

### ISSUE THREAD

**Issue by curtisgibby** [cakephp/cakephp#8295]
Now that BaseAuthenticate's config option `scope` has been deprecated, there needs to be a way to pass options from the Controller into the Table's find method (whether that's the standard `all` or a custom finder method like the suggested `findAuth`). (In my case, I need to limit the User find conditions based on the `project_id` of the API token who's calling the UsersController::validate method.)

When I [asked about this on IRC](http://irc.cakephp.org/logs/link/3812540#message3812550), @josegonzalez suggested that I use the old `scope` option for now and that I should open an issue here to address this.

Theoretically, this could be accomplished by overriding **BaseAuthenticate::_query**  (and the **_findUser** that calls it) in my own custom Authenticate objects (similar to what @flashios09 suggested in https://github.com/cakephp/cakephp/issues/7162#issue-98631276), but I think this is a fairly common use-case, especially since you used to have the whole `scope` functionality to support it.

Speaking of which, what is the plan for the deprecation of the old `scope` option? Right now, using it doesn't throw any warnings/errors/exceptions. When might it go away forever?

**Comment by markstory** [comment]
What kind of options do you need to from the controller into the authentication finder?

**Comment by curtisgibby** [comment]
In this case, I need to pass conditions, like the old `scope` provided. I have a `project_id` that the Users Table doesn't know about that needs to be added to the Query.

**Comment by markstory** [comment]
Thanks. Are those options the kind of things that could become finder options? For example:

```php
'finder' => ['inProject', ['project_id' => $someid]]
```

**Comment by ADmad** [comment]
`PaginatorComponent` uses the finder name as key like `'finder' => ['author' => ['author_id' => 1]]` for [finder options](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Controller/Component/PaginatorComponentTest.php#L160). So would be better to use similar to `AuthComponent` too for consistency.

**Comment by curtisgibby** [comment]
I had not heard of the `PaginatorComponent` custom finder options that @ADmad referenced, but  :+1: for consistency. His additions to BaseAuthenticate work basically exactly how I would have imagined.

**Comment by markstory** [comment]
@ADmad I like a consistent solution :+1:

**Comment by markstory** [comment]
Closing as there is an open pull request.

**Comment by ADmad** [comment]
> His additions to BaseAuthenticate work basically exactly how I would have imagined.

Some say I might have psychic abilities :stuck_out_tongue:

**Comment by ionas** [comment]
:+1: for CakePHPForce

**Comment by curtisgibby** [comment]
How awesome that I could open this issue on a Friday afternoon, and on Monday morning come into work to find that the code to resolve it is waiting for me in a new release. Excellent! (I know that things don't always work this fast, but kudos to @ADmad for jumping on this issue.)
