### ISSUE TITLE
RedisEngine clearGroup doesn't seem to do anything related to clearing a group of keys

### ISSUE THREAD

**Issue by chrisjohnson** [cakephp/cakephp#8296]
Perhaps I am misunderstanding how cache engines are supposed to work. So let me start there.

I have a cache config created called 'short', it uses the Redis engine and there are no groups defined in the config.

I create a bunch of Cache entries as such: `Cache::write('foo_bar_123456', $data, 'short');`

I run `Cache::clearGroup('foo_bar', 'short');`, and I would expect it to do something roughly equivalent to this command: `redis-cli KEYS "foo_bar*" | xargs -n 100 redis-cli DEL`, only in PHP code.

However, I go to inspect the source code for RedisEngine::clearGroup, and it finds a key called 'foo_bar', and increments its value. It does nothing else. I issue a `KEYS foo_bar*` command and I see not only the keys I created via `Cache::write` but the new foo_bar key.

Is there some redis concept or group concept that I am missing here? The docs make clearGroup sound like it's for deleting a bunch of grouped keys, but the implementation here doesn't seem to match that.

**Comment by chrisjohnson** [comment]
It seems to me the body for clearGroup should actually be:

```
$keys = $this->_Redis->getKeys($this->settings['prefix'] . $group . '*');
$this->_Redis->del($keys);

return true;
```

**Comment by markstory** [comment]
What you've described is not how groups work. You can only clear groups if you have groups configured. Using `keys` is not something I would be comfortable in adding either.

**Comment by chrisjohnson** [comment]
Ok, can you explain a bit more on how the groups are meant to work then? Because I read through the entire RedisEngine file and the only other mention of group is in the function 'groups'. There is nothing else that reads, writes, or deletes based on the group in the file.

And even if we're pre-defining groups, I don't see how the current body of clearGroup actually does what it advertises, which is delete a bunch of keys that are in the given group. The current body of clearGroup is:

```
return (bool)$this->_Redis->incr($this->settings['prefix'] . $group);
```

**Comment by chrisjohnson** [comment]
Also, according to the docs here: http://book.cakephp.org/2.0/en/core-libraries/caching.html#using-groups

It makes it sound as though the 'groups' setting is more about applying groups to an entire Cache config, not for declaring which groups the cache entries are allowed to exist in. In the example, it says:

```
By adding the groups comment and post, we have effectively tagged any key stored into this cache configuration with both group names.
```

So how do I configure a new group without applying it to every key entered through that config?

**Comment by markstory** [comment]
> So how do I configure a new group without applying it to every key entered through that config?

You don't.

Groups are intended to make clearing data _across_ multiple configurations easier. For example if you have multiple cache durations you can use groups to clear keys in both configurations without needing to know the configuration names ahead of time. For example a `short` cache with a 1 min duration, and a `long` cache with a 5 day duration, can share a group, which can then be 'invalidated' with one call to clearGroup().

The incrementer doesn't 'clear' data but increments the generational key which allows redis/memcache to garbage collect/expire the keys on their own. This avoids costly and dangerous operations like `KEYS` in redis.

**Comment by chrisjohnson** [comment]
Got it. I still don't quite get the last bit, and it doesn't appear to actually work for me (I apply a group of 'foo' to my config 'short', I save a key with config 'short', then I call clearGroup('foo') and go to read the key again and it's still there), but I assume I just don't understand the system well enough to see why the key isn't invalidating when I call Cache::clearGroup

**Comment by lorenzo** [comment]
Cake relies on redis for evicting the keys from memory. What clearGroup() guarantees is that the following reads will not return that value.

**Comment by chrisjohnson** [comment]
@lorenzo: 

If I do:

```
		Cache::config('myconfig', [
			'engine' => 'Redis',
			'duration' => '+24 hours',
			'prefix' => '_mmmmmmmy_prefix_',
			'groups' => ['mygroup'],
		]);


		Cache::write('mykey', 'myvalue', 'myconfig');
		debug(Cache::read('mykey', 'myconfig'));

		Cache::clearGroup('mygroup');


		debug(Cache::read('mykey', 'myconfig'));
```

I get the same result twice. That's why I'm confused because it doesn't appear to work as you are suggesting. However if I explicitly delete the key, that works fine, or if I wait 24 hours, that works fine too. Am I missing something?

**Comment by lorenzo** [comment]
That seems to be a bug, then

**Comment by lorenzo** [comment]
Ok, I figured it out. You need to specify the config name where you want to clear the groups:

```php
Cache::clearGroup('mygroup', 'myconfig');
```

**Comment by chrisjohnson** [comment]
Ok, I promise I'm not trying to be difficult, just understand. But if that's true, then what Mark said about how groups behave is not. He suggests that groups are applied to all keys within a given cache, and that clearGroup is for mass-invalidating multiple caches at once, that match the specified group. Having to specify a specific cache would defeat that purpose, imo.

What you suggest makes it sound like groups are not for mass-invalidating entire caches, but for mass-invalidating only certain keys from within a cache. So which is the correct behavior?

**Comment by lorenzo** [comment]
No, it works as he suggested. It will invalidate the keys in the same server... do you have the 'default' cache config in redis as well?

**Comment by chrisjohnson** [comment]
No, default is not in redis.

Let me provide an example following that logic:

```
        Cache::config('myconfig', [
            'engine' => 'Redis',
            'duration' => '+24 hours',
            'prefix' => '_mmmmmmmy_prefix_',
            'groups' => ['mygroup'],
        ]);
        Cache::config('myconfig2', [
            'engine' => 'Redis',
            'duration' => '+24 hours',
            'prefix' => '_mmmmmmmy_prefix2_',
            'groups' => ['mygroup'],
        ]);


        Cache::write('mykey', 'myvalue', 'myconfig');
        Cache::write('myotherkey', 'myothervalue', 'myconfig2');
        debug(Cache::read('mykey', 'myconfig'));
        debug(Cache::read('myotherkey', 'myconfig2'));

        Cache::clearGroup('mygroup');

        debug(Cache::read('mykey', 'myconfig'));
        debug(Cache::read('myotherkey', 'myconfig2'));
```

I still end up with the same two results both times. So then I change it to be: `Cache::clearGroup('mygroup', 'myconfig');`

And *only* the keys from myconfig (not myconfig2) are removed. Which suggests that I'm not able to use Cache::clearGroup for clearing keys across multiple caches. And really what benefit does clearGroup server over clear in this case? You could just as easily issue: `Cache::clear('myconfig')` and have the same effect, if what you're saying is right.

**Comment by lorenzo** [comment]
In your specific case, the problem is the different prefixes. The groups will work only on the same "keyspace", that is, keys with the same prefix in the same server.

I understand what you are saying, and perhaps it may be better to open a new ticket and suggest how the groups could work better. I for one was surprised that groups were taking prefixes in consideration.

That said, it is also difficult not to take prefixes in consideration, since clashes could easily happen

**Comment by chrisjohnson** [comment]
Ok, I understand now. Group and prefix are linked, basically. If I change my test to use identical prefixes for both configs and use `clearGroup('mygroup', 'myconfig');` it deletes all entries from both configs. If I use `clear('myconfig'),` it only clears elements from myconfig, not myconfig2. So it does work after all, it's just not obvious that you have to ensure identical prefixes to both.
