### ISSUE TITLE
Cakephp 3.2.2 Response not forcing browser to cache image

### ISSUE THREAD

**Issue by nilsonpena** [cakephp/cakephp#8307]
In my menu, I have an action that shows the user´s avatar, that is outside my webroot.
usesrs/show-avatar
Everything works well, except the fact that the browser does not caches the image. I can see in firebug the the image is  always re-downloaded, every time a page get refreshed.

This is  my action:
```
public function showAvatar() {
$perfil = $this->perfil = $this->request->session()->read('Auth.User.perfil');
        $this->response->file(ROOT . "/files/funcionarios/avatars/{$perfil['id']}.jpg");
        $this->response->cache('-1 min', '+100 days');
        $this->response->sharable(TRUE, 24444);
        $this->response->maxAge(244444);

        if ($this->response->checkNotModified($this->request)) {
            return $this->response;
        }
}
```

bellow there is the response header that shows up in firebug:
Accept-Ranges	bytes
Cache-Control	 public, max-age=244444
Connection	close
Content-Length	41164
Content-Type	image/jpeg
Date	 Sun, 21 Feb 2016 22:19:38 GMT
Expires	Tue, 31 May 2016 22:19:38 GMT
Last-Modified	Sun, 21 Feb 2016 22:18:38 GMT
Pragma	no-cache
Server	Apache/2.2.15 (CentOS)
X-Powered-By	PHP/5.5.32

The status is allways 200 ok. It should be 304 (Not modified)!!

**Comment by lorenzo** [comment]
What were the request headers?

**Comment by nilsonpena** [comment]
Here it is:

Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate
Accept-Language	pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Cache-Control	max-age=0
Connection	keep-alive
Cookie	CAKEPHP=g860plbq1hohqr773eosoln516; toolbarDisplay=hide
Host	 192.168.88.10
User-Agent	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by lorenzo** [comment]
your request is missing a If-Modified-Since

**Comment by nilsonpena** [comment]
Am I generating the links in the wrong way on the menu template?
```
<?= 
$this->Html->image(['controller' => 'Usuarios', 'action' => 'showAvatar'], [
        'class' => ['profile-image', 'img-circle', 'special-img'],
        'width' => 35,
        'height' => 35
    ]);
?>
How can I fine tune my request?
Or it is a bug on Firefox, and Chrome???

Thanks

```

**Comment by nilsonpena** [comment]
But if I use Chrome, I can see the if-Modified-Since

Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Cookie:CAKEPHP=4a1spmv65po4fude0uad2qegu6
Host:192.168.88.10
If-Modified-Since:Sun, 21 Feb 2016 23:49:56 GMT
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by lorenzo** [comment]
And what was the response for that chrome request?

**Comment by nilsonpena** [comment]
This the chrome response:
HTTP/1.1 200 OK
Date: Sun, 21 Feb 2016 23:51:10 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.5.32
Expires: Tue, 31 May 2016 23:51:10 GMT
Cache-Control: public, max-age=244444
Pragma: no-cache
Accept-Ranges: bytes
Content-Length: 41164
Last-Modified: Sun, 21 Feb 2016 23:50:10 GMT
Connection: close
Content-Type: image/jpeg

**Comment by nilsonpena** [comment]
Now I get the 304 status!!
The problem was on:
```
$this->response->cache('-1 min', '+100 days');
```
I commented this line and put this one:
```
$this->response->modified('2015-01-20 16:53:32');
```
And it worked.
No matter the value I put at  '-1 min' place, the If-Modified-Since in request was allways greater than that! So the image was always downloaded with 200 status

**Comment by lorenzo** [comment]
Nice you figured it out :)
