### ISSUE TITLE
[3.2] - Router and Session

### ISSUE THREAD

**Issue by danieldesbesel** [cakephp/cakephp#8309]
In cakePHP3.2 how can I identify whether a user is logged in router.php?
The goal is to leave www.mysite.com -> forwarding the user which not logged in to a login page. But if he is logged in the user is redirected to a page with news. But the URL remains the same, instead of having /login or /news ...
In Cake2 I used the following:
https://gist.github.com/anonymous/a12028c2d7876e13f9f7
If someone has an idea to do the same but in a different way also accepted. Any help is always welcome.

Not logged = www.mysite.com/   ->login
logged = www.mysite.com/   ->list news

**Comment by markstory** [comment]
> In cakePHP3.2 how can I identify whether a user is logged in router.php?

You can't. Route connection doesn't have access to the request object. Instead, you could make your controller do different things based on whether the user is logged in or not.

**Comment by danieldesbesel** [comment]
But I do not see how give the same result.
Continue generating /login or /news

An example of what I want to accomplish: Visit www.facebook.com logged out and logged in.

**Comment by jhli** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by danieldesbesel** [comment]
OK, sorry, you can close.

**Comment by markstory** [comment]
@danieldesbesel For example couldn't a 'home' controller do different thing based on login state?
