### ISSUE TITLE
Expose $_className in Association class

### ISSUE THREAD

**Issue by ifunk** [cakephp/cakephp#8311]
Feature request for public getter method to access protected `$_className` value in `Cake\ORM\Association` instances.

**Comment by lorenzo** [comment]
What is your use case?

You can get the full class name using `get_class($table->MyAssociation->target())`

**Comment by ifunk** [comment]
I am trying to get the unaliased table name from a plugin model.

Given my association
```
$this->belongsTo('DesktopImage', [
    'foreignKey' => 'desktop_image_id',
    'className' => 'Tank.Assets',
]);
```

I want to extract the above className `Tank.Assets`
```
object(Tank\Model\Table\AssetsTable) {
	'registryAlias' => 'Tank.DesktopImage',
	'table' => 'tank_assets',
	'alias' => 'DesktopImage',
	'entityClass' => 'Tank\Model\Entity\Asset',
	'associations' => [],
	'behaviors' => [
		(int) 0 => 'Timestamp'
	],
	'defaultConnection' => 'default',
	'connectionName' => 'default'
}
```

`get_class()` will result in `Tank\Model\Table\AssetsTable` which means I need to do some string manipulation to transform to `Tank.Assets`

**Comment by lorenzo** [comment]
The manipulation you need is `App::shortName($longClassName)`

**Comment by ifunk** [comment]
OK that's great to know! Thanks.

**Comment by markstory** [comment]
Given that there are existing ways to do what you want, I'm not sure we need another way to do it.

**Comment by ifunk** [comment]
Yeh, I guess it works, but it's pretty verbose.

    $className = \Cake\Core\App::shortName(get_class($association->target()), 'Model/Table', 'Table');

vs

    $className = $association->className();

**Comment by markstory** [comment]
@ifunk Would you expect that Association::className() returned the original input, or would it normalize to the short form?

**Comment by ifunk** [comment]
@markstory I think original input would make sense? Is it even possible to consistently normalize to short form?

**Comment by markstory** [comment]
Returning the original input would be more transparent, so I like that. I think adding a method is reasonable. Do you want to put together a pull request for this?

**Comment by ifunk** [comment]
Can do. Does it make sense for it to be a setter as well? If so, would you want it to clear `$_targetTable` when `$_className` is changed?

**Comment by markstory** [comment]
A setter might be problematic, as the instances related to className() would need to change, and that gets more complicated with BelongsToMany associations.
