### ISSUE TITLE
I18n extract task doesn't catch namespaced domains

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#8316]
#### Preamble
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

## I18n extract task doesn't catch namespaced domains
CakePHP Version: 3.2

### What you did
I have a translation like `__d('burzum/user_tools', 'message');`. This is *required* in this form because it's coming from a namespaced plugin. See my PR https://github.com/burzum/docs/commit/d5efab42cd9c4b0e514b69aaa32a49433f7e0032 that adds this to the documentation as well.

### Expected Behavior
Having a translation file with my extracted values in my plugin folder.

### Actual Behavior
The file didn't contain my domain and was as well generated in ```\vendor\burzum\cakephp-user-toolsLocale``` instead of ```\vendor\burzum\cakephp-user-tools\src\Locale```

**Comment by markstory** [comment]
Pull request open now.
