### ISSUE TITLE
Email Address Validation issue and SmtpTransport issue

### ISSUE THREAD

**Issue by huhwatnou** [cakephp/cakephp#8322]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
### Versions
- CakePHP Version: 2.8.0
- MTA used: Exim version 4.86 (currently latest version)
### Issues

Two related issues:
- CakePHP's email validation allows non-ASCII letter characters, e.g. á, in the  local part of the email address (by the \p{L} unicode category construct in https://github.com/cakephp/cakephp/blob/2.8.0/lib/Cake/Utility/Validation.php#L472). This should not be allowed, see https://en.wikipedia.org/wiki/Email_address#Local_part, or is at least highly impractical since SMTPUTF8 is not universally or even widely implemented, see e.g. "Just don't try to encode local parts." in https://lists.exim.org/lurker/message/20150424.200939.83d6ec81.en.html. Exim will reject the address.
- It also allows non-ASCII letter characters in the domain part. This allows Internationalized Domain Names (IDN). The problem here lies in the fact that this is not supported by the SmtpTransport. An SMTP client should convert them to so called punycode ASCII, according to https://lists.exim.org/lurker/message/20140812.120609.bf764769.en.html. Exim does not accept the SMTP sequence. By the way, conversion to punycode can be done by PHP's idn_to_ascii() (PHP 5 >= 5.3.0).
  This issues have been tested in the current 2.8 branch, but a quick code inspection confirms that they are also present in the master branch. As a workaround I have switched back to validation by PHP's filter_var(), used in a wrapper validation method.

The first issue can be fixed easily, although the right (i.m.h.o. almost universally implemented) RFCs may have to be consulted. For the second issue, if decided to support IDN for email, support it (maybe not only in the SmtpTransport).
### Also See
- https://github.com/cakephp/cakephp/issues/3742
- https://github.com/cakephp/cakephp/pull/3840

**Comment by dereuromark** [comment]
I stated back then:

> You can always further limit the validation in user land code.
But maybe the core code should be as allowing as possible.

So in any case you can further validate and limit the allowed input here in your own application.
It might be difficult for the core itself to always be up to date to the current valid spectrum of email domains (e.g. every year there are tons of new TLDs) and local parts.
But if it currently allows too much even beyond the RFCs we probably want to also restrict this to be on the safe side.

**Comment by huhwatnou** [comment]
Thank you @dereuromark for your reply, labeling and adding to the 2.8.1 milestone. 

I agree that it might be hard to keep up with the changes in this domain. That said a practical solution is needed i.m.h.o. to prevent CakePHP applications to run into issues.
- Currently, because IDN domains are widely supported and becoming popular, it is important to support them.Thus the SmtpTransport should be able to handle this.
- Encoded local part is not widely supported and should be disallowed in validation.

**Comment by markstory** [comment]
Doing puny code conversion on hostnames before sending them across the SMTP socket seems pretty reasonable to me. I suspect removing non-ascii email addresses will cause issues for folks in europe/asia that rely on that behavior.

**Comment by huhwatnou** [comment]
Points taken @markstory. 

So if everybody agrees, we are waiting for wide SMTPUTF8 support and meanwhile will be doing puny code conversion on domain names before sending them across the SMTP socket. Maybe add a remark/warning in the documentation on email address validation? (E.g.: it allows utf8 letters in the local part which may not be supported by SMTP servers, but you can always do your own validation.)

### Current state of support of SMTPUTF8
Source https://en.wikipedia.org/wiki/Extended_SMTP#SMTPUTF8
#### List of supporting servers
- Postfix (version 3.0 and later)
- Momentum (versions 4.1 and 3.6.5, and later)
- Sendmail (Under development)
- Exim (experimental as of the 4.86 release)

#### List of supporting local servers
Local delivery servers (LMTP)
- None

#### List of supporting content filters
- Amavis (SMTP and LMTP) since version 2.10.0

**Comment by dereuromark** [comment]
@huhwatnou Sounds like a good approach to me.

**Comment by ravage84** [comment]
> Maybe add a remark/warning in the documentation on email address validation?

:+1:

**Comment by berarma** [comment]
I'm using CakePHP 3.3.11 and seeing this problem.

Firefox 50 and Chromium 55 seem to agree with my Amazon SMTP service that UTF8 inbox names are invalid. Yet CakePHP insists that they're valid. Perhaps some temporary solution could be possible while the transition lasts.

I think the best workaround would be to create my own Validation class since the core class can't use a global setting for this.
