### ISSUE TITLE
Improve Cake\Validation\Validation::date()

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#8323]
I am referring to the method in 3.2:
`public static function date($check, $format = 'ymd', $regex = null)`

Use case: I use a string form input for my dates so I can use bootstrap-datetimepicker.
`echo $this->Form->input("date", ['type' => 'text]);`

This results in a localized version of the date being inserted into the field by the ORM. Also the user expects a localized version and edits it accordingly. When processing the form (`patchEntity()`), the string is also converted into a `Date` object by the ORM in its localized version.

What I expect from date validation in this scenario: return true if the string would result in a `Date` object. Return false otherwise.
However, `Cake\Validation\Validation::date()` does not know anything about how a date is really parsed. It implements its own parsing. It might return false and a Date object would still be successfully created, it might also return true and the Date object creation fails.

A proper test is very simple to implement:
```php
$validator->add('date', 'parseable', [
    'rule' => function ($check, $context) {
        return (!is_null(Date::parseDate($check)));
    },
])
```

I thought about including this functionality in `Cake\Validation\Validation::date()`. However I do not see how to best approach this. I think the whole parsing code in date() is redundant. On the other hand, it uses a different, custom $format notation, so accepting IntlDateFormatter formats would not result in a drop-in replacement. Just adding the native parsing functionality with a custom $format (e.g. 'native' or 'parse') also wouldn't cut it as then you could not specify a date format for parseDate(). Which certainly some people might want to. Another function might be added instead, but how would you call it? dateParseable()?

Btw. all the date methods accept `string|array|\DateTime $check` but are documented as `string|\DateTime $check`.

**Comment by markstory** [comment]
Having a localizedDate validator would be handy.

**Comment by markstory** [comment]
Closing as there is a pull request to add the discussed validator.
