### ISSUE TITLE
Validation::extension() with composed extensions

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8325]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2

The `Validation::extension()` method doesn't work with composed extensions.
Example:

	$validator->add('filename', ['extension' => [
		'rule'	 => ['extension', ['sql', 'sql.gz', 'sql.bz2']]
	]])

This fails with `sql.gz` or `sql.bz2` values.

This happens because the method uses the `pathinfo()` function, which produces just this result (see the first example [here](http://php.net/manual/en/function.pathinfo.php), file `lib.inc.php` has extension `php` and not `inc.php`).
.
Perhaps is it better to use another type of control?

**Comment by mirko-pagliai** [comment]
This works:

	->add('filename', 'validExtension', [
		'rule' => function ($value, $context) {
			$extensions = ['sql', 'sql.gz', 'sql.bz2'];
				
			$extensions = array_map(function($v) { return preg_quote($v, '/'); }, $extensions);
					
			return (bool) preg_match(sprintf('/\.(%s)$/i', implode('|', $extensions)), $value);
		}
	])

What do you think about?

**Comment by hdogan** [comment]
I think the current behaviour is correct. File extension of `sample.sql.gz` is just `gz`. It could be easily done by custom validator as you wrote, no core validator behaviour change needed imho.

**Comment by markstory** [comment]
Yeah the last extension is the actual 'extension'. Stuff in the middle is just for humans.
