### ISSUE TITLE
HTML: <section> used incorrectly in Template Layouts

### ISSUE THREAD

**Issue by thisispaulcyr** [cakephp/cakephp#8326]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.11
* Platform and Target: Apache/2.4.6 (CentOS) PHP/5.4.16 PostgreSQL/9.4.5

### Problem
In the default Template Layout files, an HTML element is incorrectly used.

The `section` element is repeatedly used to organize various parts of the webpage into sections, such as navigation areas and content areas. However, although this is a reasonable inference from the name of the element, it is an incorrect use of the `section` element. The `section` element is _not_ equivalent to `header` and `footer`.

[As stated by the spec](https://www.w3.org/TR/html5/sections.html#the-section-element):

> The section element represents a generic section of a document or application... Examples of sections would be chapters, the various tabbed pages in a tabbed dialog box, or the numbered sections of a thesis...

> **Note:** The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element's contents would be listed explicitly in the document's outline.

This is a common error, and even [HTML5 Doctor](http://html5doctor.com/the-section-element/) had to issue a correction for their explanation of the element:

>What we’ve been doing wrong is using section to wrap content in order to style it, or to demarcate the main content area from the nav, header, footer etc. These are jobs for div, not section.

### Solution

I recommend that the offending `section` elements be changed to an appropriate element (likely `div` nine+ times out of ten).

**Comment by ionas** [comment]
:+1:

**Comment by ionas** [comment]
Note 1: this should probably go into https://github.com/cakephp/bake
Note 2: this will most likely be a non BC change - but I am fine doing it anyway - the templates still need *a lot* of non-BC work anyway.

**Comment by thisispaulcyr** [comment]
Sorry, I literally joined GitHub an hour ago. BC?

**Comment by ionas** [comment]
BC = Backwards compatible - here if someone re-styled the bake outputs and used `section {}` as a selector it is not backwards compatible. But as cakephp/cakephp is decoupled form cakephp/bake I don't see much of an issue, for now.

Please close and reopen this ticket in https://github.com/cakephp/bake, then add `Ref: https://github.com/cakephp/cakephp/issues/8326`

**Comment by ionas** [comment]
Wait... wrong... it is https://github.com/cakephp/app as you are talking about the layout.

**Comment by markstory** [comment]
This issue was moved to cakephp/app#340
