### ISSUE TITLE
Error Message Discussion

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/cakephp#8327]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.
* Platform and Target: nginx, mysql.

### What you did
Tried to install a skeleton plugin using composer and get a hello world.  I added the correct info to the apps `composer.json`, and ran `composer update`.  The plugin downloads successfully into the vendor/[username][pluginname] directory and updates cakephp-plugins.php correctly.  I go to visit the plugin (which is nothing more than `debug('hello');` within the index() function of the controller, and I get the error "MissingController".  This led me to believe that the paths were messed up somewhere and I spent 3 days trying to figure out if the plugin was in the wrong directory, or if cakephp-plugins.php had the wrong info, or if it was an error in plugin's composer.json, etc.  After discussing it for awhile on the chat room with "jadb", figured out that the actual problem was that the namespace was not defined correctly in the controller.

### Expected Behavior
If the file is found, but the namespace is wrong, I would expect to get some kind of "NamespaceError" (might not be the right name), instead of "MissingController", because to me (and maybe to other people trying to migrate to 3.x from 2.x, who don't know a lot about namespaces) "MIssingController" means that the controller file is missing or not found, (eg. a path issue).  

### Actual Behavior
The controller file is found, but the namespace being wrong throws a MissingController error.  Here's an illustration to help you visualize : https://www.evernote.com/shard/s13/sh/c98a69ed-9e3b-4bb9-8d4c-e99b2bd488a8/0bd315c741d8b55e1cf5f45a14ce807f

**Comment by markstory** [comment]
> If the file is found, but the namespace is wrong, I would expect to get some kind of "NamespaceError" (might not be the right name), instead of "MissingController", because to me (and maybe to other people trying to migrate to 3.x from 2.x, who don't know a lot about namespaces) "MIssingController" means that the controller file is missing or not found, (eg. a path issue). 

We can't actually know if the file exists and the namespace is wrong. All we can know is that the class is missing. Perhaps we could update the MissingController error page to include some common namespace related gotchas?

**Comment by markstory** [comment]
Taking a look at the error page, it includes a code sample of what your file should look like. Would a bulleted list of suggestions on how to fix the error have helped?

**Comment by CodeBlastr** [comment]
thinking out loud, something like...

```
if (file_exists(SkeletonController.php)) && !class_exists('CodeBlastr\Skeleton\Controller')) {
   throw NameSpaceException();
} else {
   throw MissingController();
}
```

I'm sure I'm not using the right syntax, hopefully it's clear that I'm just trying to communicate the concept.  I mean I'm assuming that since the namespace change is made inside of SkeletonController.php **only**, then it must be looking in that file even when the namespace is incorrect.

**Comment by CodeBlastr** [comment]
Being totally honest, as soon as I saw "MissingController", I immediately assumed that it was in fact "missing" and didn't read the rest.  (I've seen that error a million times and am probably mind-blind to it a bit).  Not saying I'm right but that was my actual behavior so to me it feels like it would be the typical reaction.

**Comment by markstory** [comment]
@CodeBlastr The issue is that the dispatcher has no way of knowing where on the filesystem a controller might be. Only the autoloader knows that.

Given that we can't really find the file and give different errors based on the file's existence, if you had read the error page, is there something that could be improved on it?

**Comment by CodeBlastr** [comment]
I suppose you could generalize the name of the exception so that it's more inclusive of all the issues it covers.  Just thinking out loud.... ControllerException

**Comment by markstory** [comment]
We can't really change the exception class name as people could be depending on it. We can however change the contents of the error pages that is rendered.

**Comment by CodeBlastr** [comment]
Okay I'll just agree to disagree :100: .

**Comment by markstory** [comment]
Changing the exception class name would break backwards compatibility which is why I said we couldn't change it. I'm more than happy to update the error page contents/title but it sounds like you don't think that would have helped you.
