### ISSUE TITLE
Parsing headers in HttpSocketResponse

### ISSUE THREAD

**Issue by felixmaier1989** [cakephp/cakephp#8330]
I ran into an issue while parsing headers in HttpSocketResponse

* CakePHP Version: 2.6.10
* Platform and Target: Apache/2.2.29

Trying to parse HTTP response header (\HttpSocketResponse::_parseHeader):

```
Date: Wed, 24 Feb 2016 06:35:43 GMT
Link: 
X-Total-Count: 19
```

results in this array:
`[
    'Date' => 'Wed, 24 Feb 2016 06:35:43 GMT',
    'Link' => 'X-Total-Count: 19',
]`
whereas I would have expected:
`[
    'Date' => 'Wed, 24 Feb 2016 06:35:43 GMT',
    'Link' => '',
    'X-Total-Count' => '19',
]`

I isolated the bug in a test case: https://gist.github.com/felixmaier1989/b0f94255cdd83192583f
Where you need this file: [header.txt](https://github.com/cakephp/cakephp/files/144039/header.txt)

I managed to make it work my way by replacing 
```
preg_match_all("/(.+):(.+)(?:(?<![\t ])\r\n|\$)/Uis", $header, $matches, PREG_SET_ORDER);
```

with

```
preg_match_all("/(.+):(.+)(?:(?<![\t ])\r?\n|\$)/Uis", $header, $matches, PREG_SET_ORDER);
```

in \HttpSocketResponse::_parseHeader

would it be legit?

Additional info:

My header has been generated by a REST API based on [Slim Framework 2.6.2](https://github.com/slimphp/Slim/tree/2.x). Meaning that my header has been generated by this class: [Slim\Http\Response](https://github.com/slimphp/Slim/blob/2.x/Slim/Http/Response.php)

**Comment by markstory** [comment]
Pull request up now.
