### ISSUE TITLE
RSSHelper elem-function bug

### ISSUE THREAD

**Issue by KillermenBE** [cakephp/cakephp#8331]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: Local CakePHP (cake server), MariaDB-server

### What you did
I wan't to make a Media RSS-feed of contents of my database. I'm trying to make a media:content-element. It fails on `$this->Rss->elem('media:content',['title'=>...]);` When I add the array of attributes I want to add to my element, it gives the error: Call to a member function setAttribute() on a non-object. The API says it must work this way.

```php
<?php

$this->set('documentData', [
    'xmlns:media'=>"http://search.yahoo.com/mrss/"
]);

$this->set('channelData', [
    'title' => "Brightsign Video Content",
    'link' => $this->Url->build('/', true),
    'description' => "Brightsign Video Content",
]);

foreach ($brightsignVideoContent as $content) {

   echo $content;
   echo  $this->Rss->item([], [
       'title' => $content->brightsign_content["name"],
       'link' => $content->brightsign_content["content"],
       'guid' => ['url' => $content->brightsign_content["content"], 'isPermaLink' => 'true'],
   ]);

    echo $this->Rss->elem('media:content',['title' => $content->brightsign_content["name"]]);
}
```

### Expected Behavior
Something in the lines of this:
```xml
<rss xmlns:media="http://search.yahoo.com/mrss/" version="2.0">
<channel>
<title>Custom Video MRSS template for BrightSign Players</title>
<link>
http://brightsignnetwork.com/download/MRSS/Video_Template.xml
</link>
<description>Video Test</description>
<ttl>30</ttl>
<item>
<title>Video1</title>
<link>...</link>
<description>video1</description>
<guid isPermaLink="false">0601</guid>
<media:content url="http://brightsignnetwork.com/download/MRSS/video1.mpg" fileSize="6313040" type="video/mp4" medium="video"/>
</item>
<item>...</item>
<item>...</item>
<item>...</item>
</channel>
</rss>
```

### Actual Behavior
Error: Call to a member function setAttribute() on a non-object

Call Stack:
	Time	Memory	Function	Location
1	0.0008	238360	{main}( )	..\index.php:0
2	0.0809	5987600	Cake\Routing\Dispatcher->dispatch( )	..\index.php:37
3	0.1161	7691256	Cake\Routing\Dispatcher->_invoke( )	..\Dispatcher.php:87
4	0.2453	10774648	Cake\Controller\Controller->render( )	..\Dispatcher.php:120
5	0.2630	12399624	Cake\View\View->render( )	..\Controller.php:611
6	0.2636	12403408	Cake\View\View->_render( )	..\View.php:587
7	0.2638	12404936	Cake\View\View->_evaluate( )	..\View.php:952
8	0.2642	12432080	include( 'C:\Users\davy.decoster\Documents\Ocularium\plugins\Rss\src\Template\BrightsignVideoContents\rss\view.ctp' )	..\View.php:992
9	0.2908	13661168	Cake\View\Helper\RssHelper->elem( )	..\view.ctp:22
10	0.3251	13662632	Cake\Error\BaseErrorHandler->Cake\Error\{closure}( )	..\BaseErrorHandler.php:0
11	0.3252	13664568	Cake\Error\BaseErrorHandler->handleFatalError( )	..\BaseErrorHandler.php:99
12	0.3821	14027984	Cake\Error\BaseErrorHandler->handleException( )	..\BaseErrorHandler.php:218
13	0.3821	14028184	Cake\Error\ErrorHandler->_displayException( )	..\BaseErrorHandler.php:180
14	0.3847	14189960	Cake\Error\ExceptionRenderer->render( )	..\ErrorHandler.php:144
15	0.3850	14196488	Cake\Error\ExceptionRenderer->_outputMessage( )	..\ExceptionRenderer.php:194
16	0.3891	14310272	Cake\Error\ExceptionRenderer->_outputMessage( )	..\ExceptionRenderer.php:329
17	0.3976	14443912	Cake\Error\ExceptionRenderer->_outputMessageSafe( )	..\ExceptionRenderer.php:337
18	0.3993	14516744	Cake\View\View->render( )	..\ExceptionRenderer.php:358
19	0.3999	14518992	Cake\View\View->_render( )	..\View.php:587
20	0.4000	14519880	Cake\View\View->_evaluate( )	..\View.php:952
21	0.4004	14552872	include( 'C:\Users\davy.decoster\Documents\Ocularium\src\Template\Error\error500.ctp' )	..\View.php:992
22	0.4014	14571544	xdebug_print_function_stack ( )	..\error500.ctp:31

**Comment by KillermenBE** [comment]
Already trying to fix it myself, it has something to do with the ':' i'm using in the element <media:content/> and these lines of code:

```php
if (strpos($name, ':') !== false) {
            list($prefix, $bareName) = explode(':', $name, 2);
            switch ($prefix) {
                case 'atom':
                    $xml .= ' xmlns:atom="http://www.w3.org/2005/Atom"';
                    break;
            }
        }
```

**Comment by dereuromark** [comment]
The RSS helper has a few other minor deficiencies, as well, particularly around using namespaces.
You might want to look into the [RssView ](https://github.com/dereuromark/cakephp-feed) class if you need more advanced RSS feeds.
Not sure if the mentioned bug would also be present here, too, though.

**Comment by KillermenBE** [comment]
@dereuromark check updated comment above

**Comment by dereuromark** [comment]
You can open a PR with your suggested fix and a test case. That would be great.

**Comment by markstory** [comment]
Closing as a pull request is open now.
