### ISSUE TITLE
Failed to update the database table if datetime type to be part of primary key

### ISSUE THREAD

**Issue by eryw** [cakephp/cakephp#8333]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: PHP 7 cli

### What you did
Create a model using `bake` base on test table
```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL,
  `others` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
Then I added this to the test code

`App\Test\TestCase\Model\Table\TestsTableTest`
```php
public function testUpdateRecord()
{
    $entity = $this->Tests->find()->first();
    $this->Tests->patchEntity($entity, ['others' => 'dummy']);
    $this->Tests->save($entity);
    $this->assertEmpty($entity->errors());
}
```
### Expected Behavior
Successfully passed test

### Actual Behavior
Test failed with the following error:
```php
########## DEBUG ##########
[
	'date' => [
		'dateTime' => 'The provided value is invalid'
	]
]
###########################
```

I guess this code that is causing can't pass validation:
`Cake\Validation\Validation.php`
```php
    public static function datetime($check, $dateFormat = 'ymd', $regex = null)
    {
        if ($check instanceof DateTime) {
            return true;
        }
```
because the date property of the Test entity is `FrozenTime` object that doesn't inherit from `DateTime` but implements `DateTimeInterface`

**Comment by markstory** [comment]
Pull request up now.
