### ISSUE TITLE
2.8 isUnique validation with beforeSave

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#8334]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.0
* Platform and Target: Nginx, MySQL, Chrome

### What you did
I installed the [CakeDC/Utils](https://github.com/CakeDC/utils) plugin and implemented the SoftDelete behaviour. Then I added an `isUnique` validation rule to my `Content` model validation. Then I tried to save an item with a non-unique `slug` field.

### Expected Behavior
I expected the item to fail validation because the slug had been used previously. 

### Actual Behavior
I got a MySQL constraint error because the slug existed in the database already.

### What's happening?
I believe that the `isUnique` validation rules `find()` call is still respecting callbacks and as such the SoftDelete behaviour's `beforeFind` was filtering out soft deleted items. This caused the soft deleted item not to be returned by the find, and as such the validation passed.

### Possible workarounds
Calling `saveAssociated()` with the `callbacks => false` option. However this isn't an ideal solution as it would prevent my slug field from being changed to lowercase, as well as other potential callbacks.

I guess it might be handy to specify the callbacks in the rule.

```php
'slug' => [
    'rule' => ['isUnique', false],
    'message' => 'Slug in use'
]
```

### How I side stepped it
```php
/**
 * Validate an items slug, to ensure that it's unique and take into account any soft deleted items
 *
 * @param array $check Array of validation data
 *
 * @return bool
 */
    public function isUniqueWithDeleted($check) {
        $this->softDelete(false);
        $item = $this->find('first', [
            'contain' => false,
            'conditions' => [
                'slug' => $check['slug']
            ]
        ]);

        if ($item) {
            return false;
        }

        return true;
    }
```

Hopefully this is useful as it's an odd edge-case which took me a few hours to figure out.
Thanks :+1:

**Comment by markstory** [comment]
Disabling callbacks can trigger other bugs and break code in existing apps. I think you're stuck living with this.

**Comment by davidyell** [comment]
Fair enough. I'll keep this custom validation function saved somewhere for the future.

**Comment by ravage84** [comment]
How about adding a parameter ``$noCallbacks`` to ``Model::isUnque()``?
http://api.cakephp.org/2.8/class-Model.html#_isUnique

This way one could decide for himself what's best in the current situation?

**Comment by davidyell** [comment]
That was my hope @ravage84

**Comment by markstory** [comment]
@davidyell That would work. All it needs is a pull request.
