### ISSUE TITLE
Backport CsrfComponent from 3.x

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#8336]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: Any
- Platform and Target: Irrelevant
### What you did
1. Open Chrome
2. Open preferences, `On startup` –> `Open a specific page or set of pages` -> `Set pages`
3. Add two (identical) URLs to a form with Security CSRF enabled
4. Close and re-launch Chrome
5. Focus is now on tab no. 1
6. Fill in the form, submit
7. "Blackholed"
8. Fill in the form in tab no. 2, submit
9. Tab no. 2 works OK.
### Expected Behavior

Both tabs should work just fine.
#### Tab 1

Session ID (on render): `tabqr5td0l96pghgb79ofjfd82`

**On submit:**
Session ID: `0g42vrlhmv4j2gtimg6b31eep2`

`Session[_Token]`:

```
0g42vrlhmv4j2gtimg6b31eep2" { 
  ["key"]=> "4d19024f45889ff37b9c20d3463f82b0c99e497f" 
  ["allowedControllers"]=> { } 
  ["allowedActions"]=> { } 
  ["unlockedFields"]=> { } 
  ["csrfTokens"]=> { 
    ["4d19024f45889ff37b9c20d3463f82b0c99e497f"]=> 1456327037
  } 
}
```

`Request[_Token][key]`:

```
9015838ebc8cf54468844091610efe4233c1765a
```
#### Tab 2:

Session ID (on render): `0g42vrlhmv4j2gtimg6b31eep2`

**On submit:**
Session ID: `0g42vrlhmv4j2gtimg6b31eep2`

`Session[_Token]`:

```
0g42vrlhmv4j2gtimg6b31eep2" { 
  ["key"]=> "4d19024f45889ff37b9c20d3463f82b0c99e497f" 
  ["allowedControllers"]=> { } 
  ["allowedActions"]=> { } 
  ["unlockedFields"]=> { } 
  ["csrfTokens"]=> { 
    ["4d19024f45889ff37b9c20d3463f82b0c99e497f"]=> 1456327037
  } 
}
```

`Request[_Token][key]`:

```
4d19024f45889ff37b9c20d3463f82b0c99e497f
```

---

Somehow, this should be fixed. It is not unusual that this happens daily at our company:
- The employees have configured chrome to open many pages on launch
- They use LastPass, so it's a simple "Click" and they should be logged in and redirected properly
- First tab (which is always the one in focus on launch), never succeeds.

**Comment by markstory** [comment]
You might want to consider not using one-time tokens, or using a session store that supports atomic writes. By using as multi-use CSRF token you'll avoid race conditions around session writes. It also seems like your users are getting multiple session tokens, and I don't think there is anything we can really do to make sure that never happens.

**Comment by ADmad** [comment]
AFAIK multiple tabs in a browser will end up using the same session even if you get 2 different session ids initially. Don't think there's anything we can do about that.

**Comment by davidsteinsland** [comment]
Perhaps you did not read close enough, but what happens is that:
- Chrome receives two different session IDs (since it opens two tabs)
- When you send the form (in tab no. 1), chrome suddenly *changes* the sessionID to whatever tab no. 2 got

Since CakePHP is solely relying on sessions for CSRF protection, what about a second (opt-able) approach?

See here: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#CSRF_Prevention_without_a_Synchronizer_Token

**Comment by markstory** [comment]
@davidsteinsland No I understood that. I don't think there is a way for CakePHP to should solve a browser asking for multiple sessions and then only using one. Given that each page can only know about the session that it had when it was rendered, how would you propose we solve this problem?

**Comment by davidsteinsland** [comment]
Yes, I don't believe this is a CakePHP bug per sè, but check out the link I referred to. If user chooses to, via settings, SecurityComponent should render a CAPTCHA field, check the `Origin` header or something.

One *could* also use another form for storage of the tokens (file, DB, keyvalue-db, ...), but this would cause tokens to be "shared" among the users (I'm of course assuming that tokens in this case are "picked and trashed", and not kept for re-use).

**Comment by davidsteinsland** [comment]
... to add a third option:
Set the hidden form field to a HMAC message, with secret only known to server. If the server can verify the authenticity of the message, the request is accepted. No need to do stateful checking here, and the same approach is also widely used all over.

**Comment by markstory** [comment]
Generating captchas is non-trivial and not something we'll ever include in CakePHP. Your other suggestions are all feasible, but change the behavior and requirements around SecurityComponent. While I agree they would offer more flexibility, I would rather see us adopt the cookie based solution we used in CakePHP 3.x.

Backporting the CsrfComponent from 3.x is an option that would help solve this problem at least.

**Comment by lorenzo** [comment]
@davidsteinsland would you like to backport the csrf component from 3.x?

**Comment by dereuromark** [comment]
It looks like the interest for backporting is rather small. We can close until a PR is provided for it.
