### ISSUE TITLE
No method available to check if new Configure engine file exists

### ISSUE THREAD

**Issue by SplicePHP** [cakephp/cakephp#8338]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.x.
- Platform and Target: Mamp, PHP 7
### What you did

I have a plugin that runs some installation functions.
This plugin needs to create a directives.json file in the app/config to keep track of what is installed and how global variables are configured. The problem with the Configure class is that there is no way to check if a given Configure key maps to a file.
If no file exists and you try to load it you get thrown with an error.
### Original attempt to avoid error

```
$path = 'directive';
$key = 'directives';
Configure::config($path, new JsonConfig());
try {
    Configure::load($key, $path);
} catch (Exception $ex) {
    $init = [
           'initialize' => 'variables',
           'go' => 'here'
    ];
    Configure::write($path, $init);
    Configure::dump($key, $path, [$path]);
}
```

The try catch method worked in the bootstrap but for some mysterious reason I kept getting error pages as soon as I pushed the initialization logic to a static class I created for handeling setup directives.

This is how I solved the issue for my project.
I just duplicated the json engine and appended the following method to the class:
### Modified Engine

```
    /**
     * Checks to see if given key exists in the filesystem
     *
     * @param string $key The identifier to write to. If the key has a . it will
     *  be treated as a plugin prefix.
     * @return bool Success
     */
    public function exists($key){
        $filename = $this->_getFilePath($key);
        if(is_file($filename)){
            return true;
        }
        return false;
    }
```
### Implementation:

```
       $path = 'directive';
       $key = 'directives';
       $engine = new JsonConfig();
        Configure::config($path, $engine);
        if($engine->exists('directives')){
            Configure::load($key, $path);
        } else {
            $init = [
                'initialize' => 'variables',
                'go' => 'here'
            ];
            Configure::write($path, $init);
            Configure::dump($key, $path, [$path]);
        }
```

This solves the problem for my project but I thought you should be made aware of the problem with the inability to auto create new configuration files without being thrown with errors.

It would probably be better to fix this in the Configure::load method but I didn't want to mess with the core logic of the framework just to get my installation method to work properly.

If I overlooked something, please let me know.

One additional request regarding the json engine.

Is it possible for you to enable pretty print for the dump method by default?
All configuration variables currently generated by this engine are very unfriendly for human consumption.

```
        return file_put_contents($filename, json_encode($data, JSON_PRETTY_PRINT)) > 0;
```

Regards,
Dieter Gribnitz.

**Comment by markstory** [comment]
Having an exists method seems reasonable to me. We won't be able to update the interface for backwards compatibility issues, but we can add implementations to each of the core engines.

**Comment by ADmad** [comment]
Closing as the issue has gone stale. Feel free to open a pull request if you are still interested in adding this feature.
