### ISSUE TITLE
Form->postLink with block option doesn't work from inside a Cell

### ISSUE THREAD

**Issue by pedrofs** [cakephp/cakephp#8342]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3

### What you did
I'm trying to use the `postLink` passing `'block' => true` from inside a `Cell` and fetching the block from outside it.

### Expected Behavior
Be able to fetch the block from outside the cell display.ctp

### Actual Behavior
I created a dummy test app for reproducing the issue [here](http://github.com/pedrofs/cakephp_cell_app)

**Comment by pedrofs** [comment]
FYI: If the fetch occurs inside the `display.ctp` from the cell it works.

**Comment by ADmad** [comment]
This is expected behavior. Cells are self contaibed and don't share context with outside template / layout.

**Comment by ionas** [comment]
It should at least work for `Html::meta()`, `Html::script*()`, `Html::css()`

**Comment by ADmad** [comment]
The self contained behavior of cells won't change for any case as it they use their own View class instance.

**Comment by ionas** [comment]
Did-not-test™ but loading additional css, javascript and html-head ressources should be possible - is it not? Beyond that I think the isolation is a great thing.
