### ISSUE TITLE
Caching in _readDataSource() - unexpected behavior

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8346]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.10
* Platform and Target: Apache, MySQL, Linux

### What you did
Caching as explained on http://api.cakephp.org/2.7/class-Model.html#__readDataSource

### Expected Behavior
Different queries should have different `$cacheName`.

### Actual Behavior
When a model has conditions array in associated model and that is the only difference then the `$cacheName` is the same for both queries.

**Examples.**
`$this->MyModel->find('all');` has the same `$cacheName`  as the query below although they should be different because generated SQL is different. 

```
$this->MyModel->bindModel(array(
	'hasOne' => array(
		'AnotherModel' => array(
                    'conditions' => array(
                        'AnotherModel.my_column_id' => $value
                    ),
                ),
	)
));
$this->MyModel->find('all');
```

**Comment by lorenzo** [comment]
Not sure I understand the problem. What is the error you are getting?

**Comment by bancer** [comment]
No error message but the result stored in cache is wrong. When `$this->MyModel->find('all');` is called first without binding model the result contains all records and it is written to the cache. If after that `find()` is called with bound model then no new SQL is executed and the cache value is used. So `'AnotherModel.my_column_id' => $value` condition is ignored.

**Comment by lorenzo** [comment]
Ok, so it seems more like a documentation issue. If you already have a working solution for the caching, please send a PR with the fix for the documentation block.

I would personally vote for removing that part of the docblock, as I think caching all queries is a bad idea

**Comment by markstory** [comment]
The queries in both those cases are the 'same'. The cache key would also have to factor in the current state of associations to cover the scenario you're facing. Are you hoping to have the documentation updated to provide a more robust example?

**Comment by bancer** [comment]
I fixed it with `$cacheName = md5(json_encode($query) . json_encode($this->hasOne) . json_encode($this->belongsTo));`. Perhaps updating the documentation would be enough.

**Comment by markstory** [comment]
@bancer Thanks! I've updated the docs.
