### ISSUE TITLE
Resources routes name not available ?

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#8349]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.3
- Platform and Target: apache 2.4 + php 5.6.11
### What you did

config/routes.php

```
$routes->resources('Customers');
```

Cake Command:

```

Welcome to CakePHP v3.2.3 Console
---------------------------------------------------------------
App : src
Path: /tank/www/tests/cakephp/src/
PHP : 5.6.11-1ubuntu3.1
---------------------------------------------------------------
+---------------------+------------------------+------------------------------------------------------------------------------------+
| Route name          | URI template           | Defaults                                                                           |
+---------------------+------------------------+------------------------------------------------------------------------------------+
| pages:display       | /                      | {"controller":"Pages","action":"display","0":"home","plugin":null}                 |
| pages:display       | /pages/*               | {"controller":"Pages","action":"display","plugin":null}                            |
| customers:index     | /customers             | {"controller":"Customers","action":"index","_method":"GET","plugin":null}          |
| customers:add       | /customers             | {"controller":"Customers","action":"add","_method":"POST","plugin":null}           |
| customers:view      | /customers/:id         | {"controller":"Customers","action":"view","_method":"GET","plugin":null}           |
| customers:edit      | /customers/:id         | {"controller":"Customers","action":"edit","_method":["PUT","PATCH"],"plugin":null} |
| customers:delete    | /customers/:id         | {"controller":"Customers","action":"delete","_method":"DELETE","plugin":null}      |
| _controller:index   | /:controller           | {"action":"index","plugin":null}                                                   |
| _controller:_action | /:controller/:action/* | {"action":"index","plugin":null}                                                   |
+---------------------+------------------------+------------------------------------------------------------------------------------+
```

Template/Customers/index.ctp :

```
var_dump($this->Url->build(['_name' => 'customers:index']));
```
### Expected Behavior

the route display in var_dump :
/customers/index
### Actual Behavior

Error: A route matching "customers:index" could not be found.

**Comment by Erwane** [comment]
Router::url() call RouteCollection::match().

if '_name' is set, match() check in RouteCollection::$_named array BUT RouteBuilder::resources() forgot to give a name to routes.

```
RouteBuilder::resources() -> RouteBuilder::connect() -> RouteBuilder::_collection->add()  
```
This last callback fail to fill correctly the RouteCollection::_named array().

**Comment by Erwane** [comment]
same thing with cakephp/cakephp (dev-master ca496e1)

**Comment by markstory** [comment]
Resource routes have never connected a name. So I think this is more a missing feature vs. a broken existing feature.

Setting a name could overlap with other names defined in userland code. If there was an overlap the last route would win.

**Comment by Erwane** [comment]
Ok thanks.

The weird thing is the shell returning a route name for resources.

Until resources routes have a name, i think it's better to remove name from the shell to avoid misunderstandings.

**Comment by markstory** [comment]
Yes, the shell shows the generated names, but generated names are not referencable when generating URLs. This was a precaution as multiple routes can end up with the same generated name.

**Comment by Erwane** [comment]
I understand the reason BUT i don't understand why displaying something wrong.
Resources routes have no name, shell should display nothing in name column (i can PR if sound good).

**Comment by markstory** [comment]
The route classes don't give you a way to determine if a route has a user supplied name though. The generated names are used to do internal bucketing to optimize route lookups when we're doing reverse routes.

I agree that having the RouteShell indicate whether or not a route has a generated name or not would be helpful. I'm also going to look into fixing resource routes so they are given names, as I feel people with resource routes likely use fewer routes so the chances of overlaps are much lower.

**Comment by stevenscg** [comment]
I have just run into this issue on 2.7.6. I was also confused both by the output from the routes shell and `Router::routes()` where `_name` is set.

@markstory I've seen suggestions to move away from resource routes if we want to use named routes. Is this still the best option?

**Comment by markstory** [comment]
>  I've seen suggestions to move away from resource routes if we want to use named routes. Is this still the best option?

Yes.

**Comment by dereuromark** [comment]
Is there anything to be done here still?

**Comment by markstory** [comment]
@dereuromark We could attempt to generate names for resource routes based on a template in the resourceMap + the plugin, prefix, leading path, controller and action names. I don't have a good grasp on what all of that would look like but it is in the realm of possibility just needs hands to do it :smile:
