### ISSUE TITLE
4.x Move Single/Tuple Attribute Validations from Table to Entity

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8350]
This is a (multiple allowed):
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.3
### What you did

Wanted to explain where to put validations and why.
### Expected Behavior

For the ORM model validations should only be in entities and model rules should only be in the table (latter already the case).
### Actual Behavior

For the ORM model validations are possible within the table class.
### Suggestion

We should deprecate the possibility to setup validations in the table class.
The table should be there for:
- Behaviors
- Associations
- Rules
- Finders

The Entity should be there for:
- Accessors and Mutators
- Mass Assignment, Read- and Write-Visibility
- Validation
#### Related
- Ref: https://gist.github.com/ionas/bcff952566272afb7783
- Bake should be updated to inject detected validations into the entity rather than the table.
- Calling single/tuple field validations from the Table should be deprecated to be removed in 4.0.0.

**Comment by dereuromark** [comment]
For me Table validation is basically the "DB part" of the validation after basic validation is done and before they are actually patched into the entity.
I would not like to remove those.

**Comment by markstory** [comment]
If entities have validation rules, how do you plan on getting the table context/finders into the validation rules?

**Comment by lorenzo** [comment]
One downside of doing this change is that the validation builder functions will need to be static functions in the entity classes.

**Comment by davidyell** [comment]
:-1: 

Perhaps I've misunderstood the ticket, but I don't see any benefits to making this change.

As an entity is an instance of data, I'd like the repository to know if it's able to be persisted. I don't understand why the object itself should know if it can be persisted to the repository or not.

I'm in favour of keeping entities as stupid as possible.

**Comment by ionas** [comment]
As far as I understood things I am not. The entity should know about field constraints.
This will also make it possible to easily create entities to pass around without utilizing the table at all. They could be validated as "being okay as themselves" - which would not mean that they would automatically fit into the schema (associations / foreign keys, unique, primary keys)

The table should know about schema constraints (those are application rules). The schema constraints can possibly only be enforced by knowing about associations, existing data (unique) and things like foreign keys, primary keys and whatnot.

**Comment by chinpei215** [comment]
@ionas Taking into consideration, perhaps, it is impossible in the Data Mapper pattern.
```php
$user = new User(); 
// This entity is not tied with any table yet. 
// How does it know the constraints of unknown table?

$this->Users->pathEntity($user); // This call would tie the entity with the table.
```

**Comment by ionas** [comment]
@chinpei215 it seems I fail to understand the implementation problem that @markstory, @lorenzo and you (seemingly) point at.

> // How does it know the constraints of unknown table?
It should not and need not know about it?

What we call application rules are, AFAIU, referential integrity constraints: primary Keys, foreign Keys, association existence, unique constraints. These belong into the table and the entity should and can't know about these.

What we call validations however do not need to know about the database at all. The entities - how they are designed in cakephp3 - don't know SQL (thanks for doing it that way @lorenzo) - they can be re-used with non-orm-sqlish repositories.

What I mean is that maybe the `public function validatorDefault() { /* ... */ }` declaration should be moved into the entity and should in the long run should only be declared in the entity and not in the table anymore.

**Comment by chinpei215** [comment]
@ionas
> It should not and need not know about it?

Probably. But I have not understood 3.x well yet. Maybe, I am wrong.
I don't know it is a correct usage, but perhaps, I can also use entities in the following way:
```php
$user = new User();
$this->ExternalUsers->patchEntity($user, $data); // For another table
```
In this case, entities cannot have any validations.

**Comment by ionas** [comment]
Why not?

**Comment by chinpei215** [comment]
@ionas The length of `username` field might be different users table and external_users, for example. Or I misunderstand something?

**Comment by dereuromark** [comment]
Entities are basically smarter arrays, DTOs (Data Transfer objects) of an always valid state (or at least with errors() then to report why they are not valid, if we can't support "always valid" ones).
Adding all this in them as proposed by you makes them more than DTOs and afaik couple them too much to the actual persistence layer, especially if you do SQL queries here for some validation rules.
That is all part of the Table class setting up those DTOs IMO.

**Comment by ionas** [comment]
@dereuromark If you need to do SQL queries for validation it is NOT validation in cakephp3 but instead application rules.

**Comment by dereuromark** [comment]
That is not always true, especially with the Cake way of how validation works this is not something to be easier done than said.

**Comment by ionas** [comment]
@chinpei215 yes, but the length definition in the entity takes precedence and if stuff does not fit in it should throw an exception / crash.

**Comment by ionas** [comment]
@dereuromark Is that not? I am on IRC for that.

**Comment by ionas** [comment]
This may also be relevant as a reference for giving control to "how far" validations will run:
http://auraphp.com/framework/1.x/en/filter/

**Comment by burzum** [comment]
> @dereuromark If you need to do SQL queries for validation it is NOT validation in cakephp3 but instead application rules.

So what if I want to calculate if a club has a limit of 100 members reached and deny adding one more member? This is not a DB constraint and doesn't fall into the domain of being a rule either then. It is validation that relies on the information coming from the DB.

If you start now adding this to the entity I would see it as the opposite of the separation of concerns. Because what you suggest requires you couple the entity with the DB and will make people do crazy things in the entities that should be done in the table classes.

**Comment by jhli** [comment]
No in fact it is a schema constraint. One you can catch with application rules and/or stored procedures. It does not belomg into the entity because it is not about single/tuple field validation.

**Comment by dereuromark** [comment]
I think the generic consensus is to not move to entities.
If anything we could use a new Validator namespace and have classes there to be easier reused.

Other than that we can probably close.
