### ISSUE TITLE
CakePHP 3: Association should have Table mixin typehinted

### ISSUE THREAD

**Issue by btaens** [cakephp/cakephp#8353]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.2
* Platform and Target: Apache2, MySQL, Arch Linux

### What you did
I was trying to retrieve an associated table's alias field name through its aliasField() method.
Specifically, in `UsersTable.php`:
```php
$this->UserProfiles->aliasField('first_name');
```

### Expected Behavior
The IDE I'm using (PHPStorm) should recognize that the association indeed has the aliasField() method. In execution, PHP does return the alias field without any problems.

### Actual Behavior
The associated table's methods are accessed via a magic method. Hence, the IDE does not see the aliasField() method, and I get unnecessary warnings.

`\Cake\ORM\Association` should have `\Cake\ORM\Table` as a mixin typehint, as such:
```php
/**
 * An Association is a relationship established between two tables and is used
 * to configure and customize the way interconnected records are retrieved.
 *
 * @mixin \Cake\ORM\Table
 */
abstract class Association
{
```

**Comment by lorenzo** [comment]
Do you want to send a pull request with this?

**Comment by btaens** [comment]
Alright, created the pull request.
