### ISSUE TITLE
Add flag which allow to turn off escaping in input labels

### ISSUE THREAD

**Issue by K4T** [cakephp/cakephp#8357]
Hi,

now there is no easy way to create form with checkbox which contain label with link inside because label content is always escaped. For example let's say you want to create registration form with checkbox labeled with text: "I agree to <a href="/terms-of-service">the terms of service</a>". Almost every registration form have such a checkbox so there should be an easy way to create it in CakePHP.

I think the good solution is to add escape flag to label configuration, example:

```php
echo $this->Form->input('tos', [
    'label' => [
        'value' => __('I agree to {0}', $this->Html->link(__('the terms of service'), ['_name' => pagesTOS'])),
        'escape' => false
    ]
);
```

or just

```php
echo $this->Form->input('tos', [
    'label' => __('I agree to {0}', $this->Html->link(__('the terms of service'), ['_name' => pagesTOS'])),
    'escapeLabel' => false
]);
```

What do you think?

As a workaround I created new template:

```php
'nestingLabel' => '
    {{hidden}}<label{{attrs}}>{{input}}{{text}}{{customLabel}}</label>
'
```

And now I can create checkboxes with links inside label:

```php
echo $this->Form->input('tos', [
                'templateVars' => [
                    'customLabel' => __(
                        'I agree to {0}',
                        $this->Html->link(
                            __('the terms of service'),
                            ['_name' => 'pagesTermsOfService']
                        )
                    )
                ],
                'label' => '',
            ]);
```

Ugly but working...

**Comment by chinpei215** [comment]
Sorry if I am wrong, but you need to specify `'text'` instead of `'value'`.
```php
echo $this->Form->input('tos', [
    'type' => 'checkbox',
    'label' => [
        'text' => __('I agree to {0}', $this->Html->link(__('the terms of service'))),
        'escape' => false
    ]
]);
```

**Comment by K4T** [comment]
Thank you.

**Comment by Tomicapo** [comment]
I'm trying to place a label for an image upload and I want an image placeholder inside the label.

I tried:
```PHP
<?= $this->Form->label('product_images.' . $key . '.id', [
	'text' => '<img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" class="back">',
	'escape' => false,
]) ?>
```
But it didn't work. 
Clearly, the "escape" option isn't implemented for Form->label().
Is there another way to do this?

**Comment by ADmad** [comment]
@Tomicapo The arguments of `FormHelper::label()` are not the same as `FormHelper::input()`, check the API.

**Comment by Tomicapo** [comment]
@ADmad I know. That's my problem. 
But I want to use Form->label() and enter HTML in my label. Is this a bad idea?

**Comment by ADmad** [comment]
> But I want to use Form->label() and enter HTML in my label.

So do it. What you want is already possible, read the [API](https://api.cakephp.org/3.6/class-Cake.View.Helper.FormHelper.html#_label) and pass `'escape' => false` for the `$options` argument.

**Comment by Tomicapo** [comment]
My bad. I was reading the book, not the api.

Thanks!

For anyone else confused as I was, the working code for this is:

```PHP
<?= $this->Form->label(
	'product_images.' . $key . '.file',
	$this->Html->image('/files/productimages/file/' . $image->file_dir . '/small_' . $image->file),
	['escape' => false]
) ?>
```
