### ISSUE TITLE
QueryInterface count() causes Database Error

### ISSUE THREAD

**Issue by ah8r** [cakephp/cakephp#8360]
I believe this is a bug, introduced in either the 3.1.x or 3.2.x versions.

I'm using CakePHP 3.2.3, but previously this code worked on 3.0.x or 3.1.x (not entirely sure which version I was using).

I have a rather complex query which uses matching with multiple depths:

```php
$skillsQuery = $this->Skills->find('all')->matching('Users', function ($q) use ($user_type_id) {
    return $q->matching('UserTypes', function ($q) use ($user_type_id) {
        return $q->where(['UserTypes.id' => $user_type_id]);
    })->where(['Users.id' => $this->Auth->user('id')]);
})->contain([
    'Users' => [
        'UserTypes'
    ]
])->where(['Skills.user_id' => $this->Auth->user('id')]);

if ($skillsQuery->count() === 1)
{
    $skill = $skillsQuery->first();
        ...   
}
```

This worked perfectly before I upgraded to the latest version of CakePHP, however now the code returns the following error:

> Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UserTypes.id' in 'on clause' 

The stack trace says that the error is caused by Cake\ORM\Query->first, however if I remove the "if ($skillsQuery->count() === 1)" block, the $skillsQuery->first() call works fine. As such, I believe the count() function is not working properly and is the actual cause of the issue.

Is this a bug, or am I not using the matching() function properly? Would appreciate an answer either way.

**Comment by markstory** [comment]
Likely related to #8314

**Comment by markstory** [comment]
In your situation, what does `$query->sql()` generate? I'm not sure that nested `matching()` calls have worked properly ever. Have you tried `matching('Users.UserTypes', function ($q) { ... })` ? That is the recommended way to do matching on deeply nested associations.

**Comment by lorenzo** [comment]
Yeah, nested matchings have a big number of limitations it is much better to use 'Table1.TAble2'

**Comment by ah8r** [comment]
@markstory The sql() function generates the following:

> SELECT Skills.id AS \`Skills__id\`, Skills.user_id AS \`Skills__user_id\`, Users.id AS \`Users__id\`, Users.user_type_id AS \`Users__user_type_id\`, UserTypes.id AS \`UserTypes__id\`, UserTypes.name AS \`UserTypes__name\` FROM skills Skills INNER JOIN users Users ON (Users.id = :c0 AND Users.id = (Skills.user_id)) INNER JOIN user_types UserTypes ON (UserTypes.id = :c1 AND UserTypes.id = (Users.user_type_id)) WHERE Skills.user_id = :c2

I've converted the code to use the recommended way of doing deeply nested associations and it seems to work.

**Comment by markstory** [comment]
@ah8r Are you ok with this being closed now that you have a working solution? nested matching() calls are very problematic and should be avoided.

**Comment by ah8r** [comment]
@markstory I'm happy with it being closed if it's expected behavior. I would suggest updating the documentation to make it clear that nested matching() is not recommended: http://book.cakephp.org/3.0/en/orm/query-builder.html#filtering-by-associated-data

The way the examples are written, I assumed that the $q variable could be used as a regular query builder.

**Comment by ah8r** [comment]
Just to make sure I'm certain, if I want to match on specific Users and UserTypes in the same query, I can just string together the matching() calls?

Like so:

```php
$skillsQuery = $this->Skills->find('all')->matching('Users', function ($q) {
    return $q->where(['Users.id' => $this->Auth->user('id')]);
})->matching('UserTypes', function ($q) use ($user_type_id) {
    return $q->where(['UserTypes.id' => $user_type_id]);
})->contain([
    'Users' => [
        'UserTypes'
    ]
]);
```

**Comment by markstory** [comment]
It would be something like:

```
$query->matching('Users', function ($q) {
  ...
})->matching('Users.UserTypes', function ($q) {
});
```

**Comment by ah8r** [comment]
Awesome, that's what I'm currently using and it appears to work. Thanks for the help.
