### ISSUE TITLE
Url validation returns false when emoji is used in url 

### ISSUE THREAD

**Issue by dashrat** [cakephp/cakephp#8368]
This is a (multiple allowed):
- [x] enhancement
- CakePHP Version: I am using 3.0.8 but I checked github for latest implementation in Validation.php and validation implementation is still same. So I think its not updated yet to accept emoji in valid url.
## In controller I am using validator as : 

```
$validator = new Validator();
            $validator
                ->requirePresence('old_url')
                ->add('old_url', 'validFormat', [
                    'rule' => 'url',
                    'message' => 'Url must be valid'
                ]);
            $errors = $validator->errors($this->request->data());
            if (!empty($errors)) {
                echo json_encode(['result' => 1, "status" => 0, "message" => "Please enter a valid url. Ex: http://example.com " ], true);
                exit;
            }
// more code
```

---
### Expected Behavior

http://hashtrax.com/👹 should be a valid url in validator
### Actual Behavior

error is being returned when emoji added in url and try to validate

**Comment by markstory** [comment]
Wouldn't the emoji be URL encoded, and then be able to pass validation?

**Comment by ndm2** [comment]
@markstory Not necessarily, that would only be realiably true for the current request URI. Data retrieved via GET/POST, or generally from external sources, doesn't necessarily have to be encoded.

**Comment by markstory** [comment]
Closing as a pull request is open now.
