### ISSUE TITLE
Returning response on beforeFilter

### ISSUE THREAD

**Issue by Xymanek** [cakephp/cakephp#8372]
This is a (multiple allowed):
* [x] enhancement

* CakePHP Version: 3.1.5
* Platform and Target: apache + mysql

### What you did
My goal was simple - redirect user to another page from a `beforeFilter` in a component.
```php
if (!$user->confirm) {
    $this->Flash->error("This user has not been activated");
    $this->Auth->logout();

    return $this->_controller->redirect([
        "controller" => "account",
        "action" => "login",
        "prefix" => false
    ]);
}
```

### Expected Behavior
As per docs, I expected that the page would instantly redirect with further code execution halted

### Actual Behavior
I kept getting errors from `beforeFilter` from other components, while I didn't except them to run at all

### Problem source
I've tracked the problem to [this part of EventManager](https://github.com/cakephp/cakephp/blob/3.1.5/src/Event/EventManager.php#L351):
```php
foreach ($listeners as $listener) {
            if ($event->isStopped()) {
                break;
            }
            $result = $this->_callListener($listener['callable'], $event);
            if ($result === false) {
                $event->stopPropagation();
            }
            if ($result !== null) {
                $event->result = $result;
            }
}
```
The problem here is that even if we have a result returned the looping over callbacks will continue.

### Solution
I was forced to add `$event->stopPropagation()` to my code.

### My proposition

1. I think it's a must to clarify in docs that returning response in an event doesn't cause it to stop (unless you do it yourself) as I couldn't find it anywhere
2. I don't understand the idea behind this lines:

```php
if ($result !== null) {
                $event->result = $result;
}
```
If a listener returns a result, shouldn't we stop propagation and return the result? Right now there is a chance that next listener might simply override it.

P.S. I do realize that I'm relatively new to cakephp and Events system has been long stable but this part was really a surprise for me

**Comment by ADmad** [comment]
I guess the docs could be made clearer. But returning a response instance shouldn't automatically stop event propagation. Doing so would prevent other listeners from for e.g. modifying redirect url.

**Comment by Xymanek** [comment]
The way it looked to me is the following:

- If I **return** anything, it means that I want the whole event to end up with that (eg. like in case with `false`)
- If I **need to work** (in other words, I'm not finished and other listeners should do something as well) with subject or the result, I should use `$event->subject()` or `$event->result` accordingly

The point here is that while Events system is powerful, it's not easy to understand by someone who is new to CakePHP but important to at the same time. Therefore it might be worth considering adding more clarification on this matter to docs

**Comment by lorenzo** [comment]
What if you had another event adding CORS headers, or cache headers to the response. Would returning a response there mean that you don't want those headers added?

> I should use $event->subject() or $event->result accordingly

Whatever you return in the callback becomes the value in `$event->result`

**Comment by markstory** [comment]
@Xymanek Where would you have expected the additional information in the documentation? Would it have been under the events docs, or under the controller hook method documentation?

**Comment by Xymanek** [comment]
@lorenzo My point is that `return false` and `return $response` behave differently

@markstory I think it's best to clarify the events docs and add a note in controller hook method documentation (returing a response doen't send it straight away, but allows all listeners to run) with link leading to event docs which explain it in more detail

**Comment by markstory** [comment]
Docs pull request up now.
