### ISSUE TITLE
Russian locale plural forms

### ISSUE THREAD

**Issue by arneefreeman** [cakephp/cakephp#8373]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: Linux/Osx PHP 5.6, nginx, cake server

### What you did
If you set locale to Russian:

`ini_set('intl.default_locale', 'ru_RU');`

..and for some some reasons have not yet translated cake built-in strings (cake.po) or have not yet created cake.po file under src/Locale/ru_RU and use this example:

`echo $this->Time->timeAgoInWords(strtotime('-5 seconds'))`

### Expected Behavior
it should return default english translation:

`5 seconds ago`

but..

### Actual Behavior
it throws:

`msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR`

which I believe is due to that english default translations for seconds/hours/etc does not have three plural forms like in Russian.

Sorry for my bad english, hope this helps somehow.

**Comment by lorenzo** [comment]
Do you have a translation file in russian for the Time class messages?

**Comment by arneefreeman** [comment]
Nope, composed new cakephp project and did what mentioned above.

**Comment by markstory** [comment]
Number formatting is also missing plural forms. See cakephp/app#345

**Comment by markstory** [comment]
Pull request up now.
