### ISSUE TITLE
PDOStatement with default fetch mode

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#8374]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: not relevant

### What you did
Getting results out of a query
```php
$results = $query->execute()->fetchAll('assoc');
```
### Expected Behavior

I need 'assoc' as default. 
Passing 'assoc' all the time is redundant code and hard to change in the future.
I want to set a default fetch style for all statements (like in PDO).
http://php.net/manual/en/pdostatement.setfetchmode.php

I expect that fetchAll() and fetch() returns my custom 'default' fetch style.

```php
$results = $query->execute()->fetchAll();
```
### Actual Behavior
At the moment fetchAll and fetch() has PDO::FETCH_NUM as default fetch mode.
https://github.com/cakephp/database/blob/master/Statement/PDOStatement.php

```php
public function fetch($type = 'num')
```
```php
public function fetchAll($type = 'num')
```

**Comment by lorenzo** [comment]
Would you like to provide the code for this change? I think it is a good idea

**Comment by odan** [comment]
Thank's! I provide code for this change.

**Comment by markstory** [comment]
Closing as #8415 has changes for this.
