### ISSUE TITLE
Inconsistent json in unit tests

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8378]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.10
* Platform and Target: Linux, MySQL

### What you did
```
// In the controller
public function my_function() {
   $result = true;
   $_serialize = array('result');
   $this->set(compact('result', '_serialize'));
}

// In the unit test
public function testMyFunction() {
		$expected = '{"result":true}';
		$url = Router::url(array(
			'controller' => 'my_controller',
			'action' => 'my_function',
			'ext' => 'json'
		));
		$params = array(
			'return' => 'contents',
			'method' => 'POST'
		);
		$result = $this->testAction($url, $params);
		$this->assertEquals($expected, $result);
}
```

### Expected Behavior
I would expect the test to pass.

### Actual Behavior
The test passes when unit tests are run from shell but fails when run from test.php.

**Comment by dakota** [comment]
What is the result you get when running through the web runner?

**Comment by dereuromark** [comment]
Sounds to me like in one case you have debug mode on and in the other not => different output based on that (human readable vs. compact).

**Comment by bancer** [comment]
Debug mode is different indeed. But the result of the controller action should not depend on that, shouldn't it?

**Comment by dereuromark** [comment]
Debug is enviroment, you are responsible for making sure you are using the same env for both when running it from CLI and non CLI.

**Comment by ADmad** [comment]
With debug on the output of JsonView is pretty printed for better readability and easy debugging.

**Comment by bancer** [comment]
That means that the same test will always fail when debug is on but will pass when debug is off. Sounds not too good.

**Comment by dakota** [comment]
@bancer That means that you need to update your test to not care about the result formatting. Maybe json_decode it as assert on that.
