### ISSUE TITLE
Issue with blowfish after updating from 2.8.0 to 2.8.1

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#8379]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.1.
* Platform and Target: Apache/2.4.18 (Ubuntu), MySQL 5.6.28, PHP Version 5.5.32

### What you did
```php
    function validate_current_password($check) {
        App::uses('BlowfishPasswordHasher', 'Controller/Component/Auth');
        $passwordHasher = new BlowfishPasswordHasher();
        $user = $this->findById($_SESSION['Auth']['User']['id']);

        if (!$passwordHasher->check($check['current_password'], $user['User']['password'])) {
            return false;
        }
        return true;
    }
```

### Expected Behavior
I expect to check the current password without any warning.

### Actual Behavior
I'm getting the below waning after updating to 2.8.1
`Warning (512): Invalid salt: 97847fede2b4cb3ea719134b660883eb4cd2d706 for blowfish Please visit http://www.php.net/crypt and read the appropriate section for building blowfish salts. [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/Security.php, line 321]`

**Comment by BassemN** [comment]
@markstory I got It and sorry for reporting this as a bug into 2.8.1 release.
I got this warning if the stored password hash(sha1) into database is checked against blowfish hash. I think it shouldn't fire a warning and the result should be `true` or `false` if we are going to check the hashes if they are equal or not.

**Comment by markstory** [comment]
I disagree. If there wasn't an error figuring this out would have been very hard. This error represents developer error and that is something the framework can help with.
