### ISSUE TITLE
ORM Slow - Cake 3.2.3 MySQL

### ISSUE THREAD

**Issue by waspinator** [cakephp/cakephp#8386]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: 
Apache 2.4.12 (Win32)
PHP 5.6.11
MySQL 5.6.25

The database tables are the following sizes 
- applications: 120 000 rows X 45 columns
- transactions: 500 000 rows X 13 columns
- letter_histories: 520 000 rows X 29 columns

### What you did
I'm trying to query the database. When using Cake's `$query->all()` function the query takes 3-4 seconds. When using the same SQL query generated by `find()` and `mysqli_query()` the same query takes ~0.5 seconds. I'm using the Timer tab in DebugKit to report the time. Both are run from the same controller. The only difference between them is the faster one doesn't call `$applications = $query->all();` but instead runs the second snippet.

This takes a long time (3-4 seconds)

    $query = $this->Applications->find()
        ->select([
            'transaction_id',
        ])
        ->contain([
            'Transactions' => function ($q) {
                return $q ->
                select([
                    'transaction_id',
                ]);
            },
            'Transactions.LetterHistories' => function ($q) {
                return $q ->
                    select([
                ]);
            }
            ])
            ->where(['id_number' => $id_number]);
    $query->hydrate(false)
    $applications = $query->all();

This takes a shorter time (~0.5 seconds)

    $conn = mysqli_connect('localhost', 'username', 'password', 'db_name');

    $sql = 'SELECT Applications.transaction_id AS `Applications__transaction_id`, Transactions.transaction_id AS `Transactions__transaction_id` FROM applications Applications LEFT JOIN transactions Transactions ON Transactions.transaction_id = (Applications.transaction_id) WHERE id_number = 444444';

    
    $result = mysqli_query($conn, $sql);
    $output_array = [];

    while($row = $result->fetch_assoc()) {
        $output_array[] = $row;
    }
    echo json_encode($output_array);                

This is fast as well

    $connection = ConnectionManager::get('default');
    $results = $connection->execute($sql)->fetchAll('assoc');

The result of the query is as follows:

ORM

    object(Cake\ORM\ResultSet) {

        'items' => [
            (int) 0 => [
                'transaction_id' => (int) 858755,
                'transaction' => [
                    'transaction_id' => (int) 858755,
                    'letter_histories' => [
                        (int) 0 => [
                            'transaction_id' => (int) 858755
                        ]
                    ]
                ]
            ]
        ]

    }

PHP json

    [{
        "Applications__transaction_id": "858755",
        "Transactions__transaction_id": "858755"
    }]

Cake execute

    [
        (int) 0 => [
            'Applications__transaction_id' => '858755',
            'Transactions__transaction_id' => '858755'
        ]
    ]

### Expected Behavior
The run times for both native php and cake queries should be similar. 

### Actual Behavior
Cake is much slower than native php.

**Comment by markstory** [comment]
I don't think that is a 'fair' comparison. For example your basic PHP example is not doing the following:

* Value casting - All data out of PDO is strings. If you want booleans or integers you need to handle that yourself.
* Object hydration - If you want anything other than stdClass you'll need to implement that your self.
* Joined record creation - You're getting flat arrays. The ORM handles nesting associated records.
* Query builder - You're comparing raw SQL queries to an object based interface for building queries. A fairer comparison would be to execute raw SQL from a Database\Query.
* Different queries - Your two example queries are totally different. The CakePHP based one includes additional joins.
* Callbacks - Going through the table mapper invokes behaviors and callbacks. Your PDO implementation lacks all those things.

I think if you built all the missing behavior into your PDO example you'd end up with equal performance.

**Comment by waspinator** [comment]
After looking into this some more, it seems there was an issue with the database. It was imported using a csv file and some int fields were set to text accidentally. After changing them to int the query performed normally.
