### ISSUE TITLE
Problem in HasMany::_unlink when using replace save strategy

### ISSUE THREAD

**Issue by greew** [cakephp/cakephp#8389]
This is a:

* [x] bug
* [x] enhancement

* CakePHP Version: 
  * Composer selected version: 3.1.x
  * Commit: 2930c3c0aeba6150cdbb67bf75bb31597efd614c 
* Platform and Target:
  * System: OS X 10.11.3
  * PHP: 
```
PHP 5.5.31 (cli) (built: Jan  8 2016 08:36:35) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Retinas
```
  * MySQL: `Server version: 5.7.10 Homebrew`

### What you did
The following is a very simplified version of our setup, but it should give you an idea of the bug:

I have the following tables:

```sql
-- Create syntax for TABLE 'a'
CREATE TABLE `a` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'b'
CREATE TABLE `b` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `a_id` int(11) unsigned NOT NULL,
  `name` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  CONSTRAINT `b_ibfk_1` FOREIGN KEY (`id`) REFERENCES `a` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'c'
CREATE TABLE `c` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `b_id` int(10) unsigned NOT NULL,
  `name` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  CONSTRAINT `c_ibfk_1` FOREIGN KEY (`id`) REFERENCES `b` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

... with the following data:

```
Table A:
-------------------------
| id | name             |
-------------------------
| 1  | First in A table |
-------------------------

Table B:
---------------------------------
| id | a_id | name              |
---------------------------------
| 1  | 1    | First in B table  |
| 2  | 1    | Second in B table |
| 3  | 1    | Third in B Table  |
---------------------------------

Table C:
-------------------------------
| id | b_id | name            |
-------------------------------
| 1  | 1    | Additional data |
-------------------------------
```

And the following files and functions

```php
// file: ATable.php

public function initialize(array $config)
{
    $this->hasMany('B', [
		'property' => 'b',
		'dependent' => true,
		'saveStrategy' => HasMany::SAVE_REPLACE,
		'cascadeCallbacks' => true
	]);
}

// file: BTable.php

public function beforeFind(Event $event, Query $query, ArrayObject $options)
{
	$this->hasOne('C', [
		'joinType' => 'LEFT',
		'propertyName' => 'c',
		'className' => 'CTable',
		'conditions' => [
			'C.b_id = B.id'
		],
	]);
	$query->contain('C');
}
```
Scenario:

```php
// file: AController.php

public function edit($id)
{	
	$entity = $this->ATable->get(1);
	$this->ATable->patchEntity($entity, [
		'b' => ['_ids' => [1]]
	]);
	$this->ATable->save($entity);
}
```

### Expected Behavior
When running the above save, I expect to have deleted entries 2 and 3 from table B, because of the replace save strategy.

### Actual Behavior
I get the following MySQL error:

    PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

### Problem
The problem here is, that the [$exclusions condition](https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/HasMany.php#L397) doesn't use aliases on the primary key in the condition, meaning that both the `id` field in table B and table C could match the `id` requested.

### Possible solution
Our solution currently is to change the [map function](https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/HasMany.php#L397) in [_unlinkAssociated](https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/HasMany.php#L393) to add alias to the keys: 

```php
->map(function ($ent) use ($target) {
	$fields = $ent->extract((array)$target->primaryKey());
	foreach($fields as $field => $value) {
		$fields[$target->aliasField($field)] = $value;
		unset($fields[$field]);
	}
	return $fields;
})
```

If the above would be an acceptable solution to the problem, I will happily create a PR for it.

Let's discuss :-)

Best regards
Jesper

**Comment by greew** [comment]
PS: I have tested it on both version 3.1.11 and 3.2.3.

**Comment by lorenzo** [comment]
Would you like to send a pull request with your proposed fix?

**Comment by greew** [comment]
Aaaand, there it is.. sorry for the confusion with lots of references above :)

**Comment by dereuromark** [comment]
PR is now open.

**Comment by ravipateldhg** [comment]
Thanks @greew 

You save my time. Time is value
