### ISSUE TITLE
Missing traverse option in UnaryExpression

### ISSUE THREAD

**Issue by greew** [cakephp/cakephp#8398]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: master

### What you did
Tried to traverse a `QueryExpression` that contained a `UnaryExpression`.

### Expected Behaviour
`UnaryExpression` values should've been traversed.

### Actual Behaviour
It didn't happen.

### Solution
Change `traverse` function in https://github.com/cakephp/cakephp/blob/master/src/Database/Expression/UnaryExpression.php#L99 from

```
    public function traverse(callable $callable)
    {
        if ($this->_value instanceof ExpressionInterface) {
            $callable($this->_value);
        }
    }
```

to

```
    public function traverse(callable $callable)
    {
        if ($this->_value instanceof ExpressionInterface) {
            $callable($this->_value);
            $this->_value->traverse($callable);
        }
    }
```

See greew/cakephp@2b120400e6d27b2a14a3fb560be8266d55cfe18a

Should I create a PR?

**Comment by lorenzo** [comment]
Yes, please

**Comment by markstory** [comment]
Closing as a pull request is open now.
