### ISSUE TITLE
Cakephp 2 and Cakephp 3 return database data differently

### ISSUE THREAD

**Issue by calubrious** [cakephp/cakephp#8406]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.2 and 2.6.3
* Platform and Target: 
Apache 2.2.31
MySQL 5.5
Database table:
Col=InnoDb
Engine=latin1_swedish_ci

### What you did
So here is the story
http://stackoverflow.com/questions/35801011/cakephp-2-and-cakephp-3-return-database-data-differently

So after alot of silence i started digging around myself and i "think" i stumbled on a "bug".
Below are the default database configs.

Version 3 config
```
mysql:host=*;port=3306;dbname=*;charset=utf8

Array
(
    [driver] => Cake\Database\Driver\Mysql
    [persistent] => 
    [host] => *
    [username] => *
    [password] => *
    [database] => *
    [name] => dynamic
    [port] => 3306
    [flags] => Array
        (
            [12] => 
            [1000] => 1
            [3] => 2
        )

    [encoding] => utf8
    [timezone] => 
    [init] => Array
        (
            [0] => SET NAMES utf8
        )

)
```

Version 2 config
```
mysql:host=*;port=3306;dbname=*

Array
(
    [persistent] => 
    [host] => *
    [login] => *
    [password] => *
    [database] => *
    [port] => 3306
    [flags] => Array
        (
        )
    [datasource] => Database/Mysql
    [prefix] => 
)
```

### Expected Behavior

Data returned the same way.

### Actual Behavior

Data returned another way.

### Things i found to get the same output

So i did some comparing in both versions of Mysql.php files and the only way i got v3 to return the same data as version v2 is by chaning these lines of code

Database/Driver/Mysql.php

i commented this line: 67:
`//$config['init'][] = sprintf("SET NAMES %s", $config['encoding']);`

i changed this line: 85:
`$dsn = "mysql:host={$config['host']};port={$config['port']};dbname={$config['database']};charset={$config['encoding']}";
`
to this:
`$dsn = "mysql:host={$config['host']};port={$config['port']};dbname={$config['database']}";`

and now i finnaly get the same data return back as in v2 and i cant seem to get this to work with changing the database config file.

**Comment by lorenzo** [comment]
Just configure the charset for your connection in your app.php file.

The default there is is UTF8 which you are apparently not using.

**Comment by calubrious** [comment]
That's the problem that does not work even if i put utf8 config as encoding in the config it stil returns different data see md5 hashes like the post on Stack says. The problem comes from the init var in conjunction with the charset encoding.

**Comment by markstory** [comment]
So by removing the charset your issue goes away? What is the connection charset if you're not defining one? What happens if you define a charset/encoding in the 2.x application? Are the columns binary or are they text? How can someone reproduce this issue?

**Comment by calubrious** [comment]
So by removing the charset your issue goes away?: Yes and also removing the init SET NAMES utf8 array

What is the connection charset if you're not defining one?: According to phpmyadmin utf8 (also shoudlnt it default to what the database uses if none is given?)

So my thought proccess was if i leave all in default on v3 i get the same results/output, but that is not happening.

```
$settings = [
  'className' => 'Cake\Database\Connection',
  'driver' => 'Cake\Database\Driver\Mysql',
  'persistent' => false,
  'host' => $user['connection']['server'],
  'username' => $user['connection']['username'],
  'password' => $user['connection']['password'],
  'database' => $user['connection']['database'],
];
ConnectionManager::config('dynamic', $settings);

Return wrong output: (with or without using 'enod
mysql:host=*;port=3306;dbname=*;charset=utf8 **<--- note v2 doesn't have charset like this**
Array
(
    [driver] => Cake\Database\Driver\Mysql
    [persistent] => 
    [host] => *
    [username] => *
    [password] => *
    [database] => *
    [name] => dynamic
    [port] => 3306
    [flags] => Array
        (
            [12] => 
            [1000] => 1
            [3] => 2
        )

    [encoding] => utf8
    [timezone] => 
    [init] => Array
        (
            [0] => SET NAMES utf8 **<---- cannot overrule this**
        )

)

Returns right output:
mysql:host=*;port=3306;dbname=*
Array
(
    [driver] => Cake\Database\Driver\Mysql
    [persistent] => 
    [host] => *
    [username] => *
    [password] => *
    [database] => *
    [name] => dynamic
    [port] => 3306
    [flags] => Array
        (
            [12] => 
            [1000] => 1
            [3] => 2
        )

    [encoding] => utf8
    [timezone] => 
    [init] => Array
        (
        )
)
```

As you can clearly see the difference between the wrong and right one.
And the documentation clearly states about encoding: "This defaults to the database’s default encoding for all databases" and i use MySQL so that should work.

The colums are text/varchar not binary.
You can reproduce it by creating a table with a field varchar(500)	latin1_swedish_ci.
Phpmyadmin says character set is utf8 

Open cake-v2 (all default settings no encoding) and use the Security::encrypt(); to encrypt any string i used a key with 58 letters and numbers and save it, this is only to create those pesky none latin characters. Now get the data and md5 the string.

Now open a cake-v3 to the same database and table and get the data also outputting the string as md5.

On my server and config both default setups end up with another output which i find really strange.
There are plans on updating the text/varchar to binary or to undo v3 to v2 to get rid of this entire problem but i have to work this setup for now.

**Comment by markstory** [comment]
Storing encrypted data into a latin1 encoded table is likely a source of your problem here. Using a binary column would solve this problem as you're aware, another solution would be to base64 encode the data before it goes into the database to prevent these encoding issues.

Given your specific requirements you might be best off creating an in-app modification of the Mysql Driver that removes the encoding configuration that is giving you grief. I cannot justify removing those settings as they generally solve encoding issues not cause them.

**Comment by calubrious** [comment]
Totally agree with your comment about my setup not being super but.

Is there any small change that you can acctually add an extra option via the database config
so that i can like force the above shown working config to get the data like i want? 
(Knowing fullwell it's not the best setup but i can atleast expect the data to return like i thought it would)

All be it an extremly rare case it would have saved me allot of hours finding out why Security::decrypt() alwas returned false.

Anyway i really appriciate you taking your time for this.

**Comment by markstory** [comment]
Wouldn't a subclass of the Mysql driver in your application let you configure the connection string exactly as you need it? If you have a change in mind that would be compatible with the existing implementation and allow you to cover your use case I'd be open to merging it.
