### ISSUE TITLE
dosen't show error on find treeList

### ISSUE THREAD

**Issue by mehdi-fathi** [cakephp/cakephp#8413]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.0.0
- Platform and Target: Local Apache 2.4 Windows 8
### What you did

i was working by tree today.I found a inconsistency this part.if you write wrong name of cloumn in valuePath on treeList then you will don't see any errors.indeed this return null. for example
 `$list = $this->Acos->find('treeList',[
                                    'valuePath' => 'abcdefg']);`
### Expected Behavior

I tried my best about this problem but i didn't find a good way for display error.becuase of i have a little Experience on this field
### Actual Behavior

Do i am right? I did handled treebehaivor but i couldn't.

**Comment by dereuromark** [comment]
Maybe this should throw an exeption then instead?
Sounds like a developer error if the valuePath is not existent.

**Comment by ADmad** [comment]
Checking the existence of `valuePath` can be tricky. It doesn't have to be an actual db field, it can be a virtual field provided by entity getter for example. I don't it would be reasonable to add such overhead of trying to figure out validity of `valuePath`.
