### ISSUE TITLE
Cakephp 3 - Translate behavior does not work for the default language

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#8416]
Sorry for my english, but I hope you will understand me. Simplified code looks like this:
//in bootstrap.php
>     ini_set('intl.default_locale', 'deu');

// MainMenusTable.php
> public function initialize(array $config) {
> parent::initialize($config); 
> ...
>  $this->addBehavior('Translate', ['fields' => ['title']]);  
>   ... 
> }

//in controller - THIS WORKS
>     public function add()
>     {
>         I18n::locale('eng');
>         $mainMenu = $this->MainMenus->newEntity();
>         if ($this->request->is('post')) {     
>             $mainMenu = $this->MainMenus->patchEntity($mainMenu, $this->request->data);
>             $this->MainMenus->save($mainMenu)
>         }
>         $this->set(compact('mainMenu'));
>     }

// **in controller BUT THIS DOESN'T WORK!!! 'Title' field has not been saved.**

>     public function add()
>     {
>         I18n::locale('deu');
>         $mainMenu = $this->MainMenus->newEntity();
>         if ($this->request->is('post')) {     
>             $mainMenu = $this->MainMenus->patchEntity($mainMenu, $this->request->data);
>             $this->MainMenus->save($mainMenu)
>         }
>         $this->set(compact('mainMenu'));
>     }

I have the same problem when I read the record:
//in controller - THIS WORKS!
>         I18n::locale('eng');      
>         $query = $this->MainMenus->find('all')->order(['MainMenus.id' => 'ASC'])->all();

// in controller **BUT THIS DOESN'T WORK:**
>         I18n::locale('deu');      
>         $query = $this->MainMenus->find('all')->order(['MainMenus.id' => 'ASC'])->all();
For 'deu' I manually entered records for testing. Do you know what the problem is? Thanks!

**Comment by lorenzo** [comment]
The behavior assumes that you store the records in the default language. If the current locale is the same as the default language, then it will just return the records in the database instead of fetching from the translations table

**Comment by lupuswwww** [comment]
I have removed I18n::locale('deu');  , but still does not work for the default language. The 'title' is not saved in the i18n table. It works for all other languages.

**Comment by lorenzo** [comment]
The title will not be saved in the i18n table for the default language, that is only done for other languages.

**Comment by lupuswwww** [comment]
Thanks:) I thought the multilingual field is saved in the i18n for all languages, even for default.

**Comment by lorenzo** [comment]
No problem :)
