### ISSUE TITLE
Nested Resource Routing does not work with DashedRoutes

### ISSUE THREAD

**Issue by simkimsia** [cakephp/cakephp#8419]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: Nginx, MySQL and Ubuntu 14.04

### What you did
I used nested resources like this:

```
    $routes->resources('PaymentTypesWithValues', function ($routes) {
        $routes->resources('PaymentsByMembers');
    });
```

and DashedRoutes like this

    Router::defaultRouteClass('DashedRoute');

and my url was:

     example.app/payment-types-with-values/2/payments-by-members

### Expected Behavior
I expect the nested resource to work as per normal.

### Actual Behavior
Instead I got an error saying that PaymentTypesWithValuesController does not have an action called 2.

### What I did that did work

The moment I switched to InflectedRoute and used `payment_types_with_values/2/payments_by_members`

It worked.

>Before you open an issue, please check if a similar issue already exists or has been closed before.

I am pretty sure that this does not exist. I searched within github using the key word `nested`.

P.S. Be happy to patch this bug myself, but I got lost inside `Routing/Dispatcher.php`. If you point me in the right and slightly more specific direction, I can try to write a patch for this.

Thank you.

**Comment by markstory** [comment]
With your connected routes, what does `bin/cake routes` output? Does it show the inflected routes you're expecting or something else?

**Comment by markstory** [comment]
Also I forgot to ask do you set the default route class before or after you connect the resource routes?

**Comment by markstory** [comment]
When you connect resource routes you need to use the `'inflect' => 'dasherize'` option to get dasherized resource routes. This is necessary because resource names need to be inflected outside of the route class so the controller names can be used in static portions of the route template.
