### ISSUE TITLE
Add option to ignore certain URLs with Auth.redirect

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#8420]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 2.*
### Expected Behavior

`Auth.redirect` should not be filled with current URL for any action, it should be possible to ignore certain actions.

``` php
public function beforeFilter() {
    Auth->ignoreRedirect([
        'download',
        'other_action'
    ]);
}
```

`AuthComponent.php`:

``` php
protected function _unauthenticated(Controller $controller) {
    // ....
        if ($controller->request->is('ajax')) {
            if (!empty($this->ajaxLogin)) {
                $controller->response->statusCode(403);
                $controller->viewPath = 'Elements';
                $response = $controller->render($this->ajaxLogin, $this->RequestHandler->ajaxLayout);
                $response->send();
                $this->_stop();
                return false;
            }
        } else if (!$this->isUrlIgnored($controller->request->here(false))) {
            $this->flash($this->authError);
            $this->Session->write('Auth.redirect', $controller->request->here(false));
            $controller->redirect($this->loginAction);
            return false;
        }

        $controller->response->statusCode(403);
        $controller->response->send();
        $this->_stop();
        return false;
}
```
### Actual Behavior

Let's say a session timeout causes the user to be logged out. While this happens, the browser makes a request to a resource (image served via controller, for example).

When the user logs back in, the user is redirected to the said resource.

**Comment by dereuromark** [comment]
I also always have to do that manually per app. So this sounds indeed quite useful.

**Comment by dereuromark** [comment]
@davidsteinsland Are you interested in making a PR for 3.next here with your suggested improvement?

**Comment by ADmad** [comment]
Closing as the issue has gone stale. Feel free to open a pull request if you are still interested in adding this feature.
