### ISSUE TITLE
Allow ValueBinder to bind multiple placeholders in one method call

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8426]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: apache 2.4 / nginx / mariadb 5.5

### What you did
Use `$table->find()->bind()`

### Expected Behavior
I would like to use
```
$stmt->bind(
    ['published' => true, 'created' => new DateTime('2013-01-01')],
    ['published' => 'boolean', 'created' => 'date']
);
```
but the actual behavior of the ValueBinder is more like
```
$stmt->bindValue('published', true, 'boolean');
$stmt->bindValue('created', new DateTime('2013-01-01'), 'date');
```

I think it would improve the ValueBinder if one can bind multiple values at once.

P.S.: It would be nice to also use `bind($param, $value, $ype)` with an array as `$value` (for IN clauses).

**Comment by lorenzo** [comment]
You can bind array arguments for IN clauses if you pass the $type argument as string[] or integer[] o whatever type it is and appending []

**Comment by boindil** [comment]
Hi @lorenzo, yes you're totally right, it works! Thanks! I've searched my way through the Docs but didn't find a hint for that....

Still I'm correct on the point that binding multiple params at once (as in the example) isnt possible, am I?

**Comment by markstory** [comment]
Yes there isn't a way to bind multiple parameters on a single method call currently.

**Comment by clementlanot** [comment]
> You can bind array arguments for IN clauses if you pass the $type argument as string[] or integer[] o whatever type it is and appending []


I believe this functionality is no longer possible?
