### ISSUE TITLE
Contains doesnt use correct alias if set manually

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8427]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: apache 2.4 / nginx / mariadb 5.5

### What you did
```
$table = TableRegistry::get('Table');
$table->alias('SomeAlias');
$table->find()->contain(['Somecontain with conditions']);
```

### Expected Behavior
Contain using correct alias on `ON` (`... LEFT JOIN ... othertable.id ON SomeAlias.foreign_id ...`)

### Actual Behavior
Contain using old alias (query created: `... LEFT JOIN ... othertable.id ON Table.foreign_id ...`)

Of course the query fails ...

**Comment by markstory** [comment]
Can you give a more concrete example?  Is the `contain()` call referencing an existing association or one that was renamed. Right now I'm not clear on how to go about reproducing this issue.

**Comment by boindil** [comment]
Hi,
this (simplified) example should (not) work.

```
$this->MyTables = TableRegistry::get('MyTables');
$this->MyTables->alias('NeatAlias');

$query = $this->MyTables->find()
	->select(['user_id'])
	->distinct()
	->where(['YEAR(MyTables.date)' => 2014])
	->contain([
		'Users' => function ($q) {
			return $q->select(['id', 'nick']);
		}
	])->all();
```

Without the contain everything works fine and the query is using the alias `NeatAlias`. The generated `ON` statement however is not aware of this alias and uses the standard Alias `MyTables` instead.

Btw: I tried to avoid this by using `foreignKey => false` and creating my own `queryBuilder`. However I'm not sure on how to generate the ON statement. Currently it does `ON 1 = 1` ...

**Comment by lorenzo** [comment]
Changing the table alias on the fly is actually not allowed. I think we should add an exception when the alias is set after the table has been built

**Comment by jhli** [comment]
So it is allowed on construct and inintialize (and any events before those)?

**Comment by boindil** [comment]
> Changing the table alias on the fly is actually not allowed. I think we should add an exception when the alias is set after the table has been built.

Well, everything else is working just fine ... and actually I like the way of modifying the alias :+1:

**Comment by markstory** [comment]
@lorenzo Raising an exception sounds like the best option we have here.

**Comment by boindil** [comment]
@markstory so how would I get my table object correctly? 
Using `TableRegistry::get('MyTables', ['alias' => 'NeatAlias']);` doesnt work as Cake throws `You cannot configure "MyTables", it already exists in the registry.: You cannot configure "MyTables", it already exists in the registry.`

**Comment by markstory** [comment]
`TableRegistry::get('NeatAlias', ['className' => 'MyTable']);` should work.

**Comment by boindil** [comment]
@markstory sadly it does not. I'm getting the same error as above.

**Comment by boindil** [comment]
@markstory yes that does work ...

**Comment by ionas** [comment]
http://book.cakephp.org/3.0/en/orm/table-objects.html#configuring-table-objects the className is fully namespaced. Should the docs be changed or is it good either way?

**Comment by markstory** [comment]
@ionas The classname option accepts a shortname, fully qualified classname or a plugin short name.

**Comment by markstory** [comment]
I don't think adding an exception is going to be feasible here. Doing so causes a 6 tests to fail, which makes me concerned about breaking existing applications.
