### ISSUE TITLE
3.2.4 - $routes->redirect not working as expected

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8429]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: PHP 5.6.10, MAMP running Apache on port 80

### What you did
```
Router::scope('/', function ($routes) {
    $routes->redirect('/foo', 'http://google.com', ['status' => 302]);
});
```

### Expected Behavior
A request to `http://localhost/foo` should be a 302 to `http://google.com`

### Actual Behavior
A request to `http://localhost/foo` is a 404, no redirect

**Comment by patrickconroy** [comment]
I went back in time, and looks like it was working in 3.1.11 tag but became broken in 3.2.0. Looking at https://github.com/cakephp/cakephp/compare/3.1.11...3.2.0 it seems like https://github.com/cakephp/cakephp/commit/93668043e7d044ec55587f1618792d3d49fdb434 *might* be related, but I'm not sure what that change was for.

**Comment by markstory** [comment]
That commit was part of #8072 which made it possible for dispatcher filters to interact with redirect routes, and made it possible to write tests for redirect routes.

I will take a look as I thought I checked this all working back then.

**Comment by markstory** [comment]
I just tried this on a fresh app install and the redirect routes _did_ work as expected. Do you have a custom `RoutingFilter` or other Dispatch filters that augment responses?

**Comment by patrickconroy** [comment]
Hm yeah that seems to have been it. I was extending the cake `RoutingFilter`. I just changed mine to extend `DispatcherFilter` and added the normal ``DispatcherFactory::add('Routing');`` to my bootstrap and things look fine.
My `RoutingFilter::beforeDispatch` looked like this..

```
public function beforeDispatch(Event $event)
{
    $request = $event->data['request'];
    $response = $event->data['response'];
    $request->addDetector(
        'office',
        function ($request) {
            if (in_array($request->clientIp(), [Configure::read('OfficeIP')])) {
                return true;
            }
            return false;
        }
    );
    parent::beforeDispatch($event);
}
```

Is there anything I could do to that to make it work better with Cake's `RoutingFilter`? Or should it be finalized?

**Comment by markstory** [comment]
Doing `return parent::beforeDispatch($event)` should fix your issue. Closing this now as the core code is fine and the issue was in an application subclass.

**Comment by patrickconroy** [comment]
Thanks! `return`ing made that work.
