### ISSUE TITLE
__xn() and __dxn() functions return singular form of message always

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#8431]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4 (master)
* Platform and Target: PHP 5.6.15 x32, Windows10

### What you did
I created a .po file for testing context dependent translation,
```po
#/src/Locale/de_DE/default.po

msgctxt "some context"
msgid "{0} second"
msgid_plural "{0} seconds"
msgstr[0] "{0} Sekunde"
msgstr[1] "{0} Sekunden"
```
and tried to use __xn() function.
```php
use Cake\I18n\I18n;

I18n::locale('de_DE');
$count = 10;

echo __xn('some context', '{0} second', '{0} seconds', $count, $count);
```

### Expected Behavior
Returns plural form of message.
```
10 Sekunden
```

### Actual Behavior
Returns singular form of message.
```
10 Sekunde
```

I'll send a pull request soon.

**Comment by markstory** [comment]
Closing as a pull request is up now.
