### ISSUE TITLE
CakePHP 3 showing white blank page

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#8433]
I have successfully installed CakePHP 3 on my local machine. I use WAMP server (http: // localhost /). Everything works fine.
When I have transferred the same files to a web server via FTP  http://example.com/ cakephp 3 does not work, it shows the white blank page.
Web server (example.com) uses php 5.6 version.
Where is the problem? What's wrong?

**Comment by lupuswwww** [comment]
These are my steps:
1. Download composer.phar in wamp/www/
2. Composer create-project --prefer-dist cakephp/app cakephp3
3. http://localhost/caketest/ - I received a welcome message. Everything works fine.
4. After successful installation I transferred the same files to a web server via FTP http://example1.com/
5. Cakephp 3 shows the white blank page.
6. I tried to do the same thing with other web servers (FTP transfer)  http://example2.com/
7. Cakephp 3 shows error massage: Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/username/public_html/test/config/bootstrap.php on line 107

**Comment by lupuswwww** [comment]
this is my 107 line: (new ConsoleErrorHandler(Configure::read('Error')))->register();

**Comment by lupuswwww** [comment]
It seems to be a problem in the version of PHP. PHP version should be greater than 5.4. It seems that the server example1.com not using version 5.6. I made a test on the third server example3.com. Cakephp 3 is installed successfully. Php version is 5.6

**Comment by ionas** [comment]
**Can you confirm** that you had something lower than 5.5.9 on your other server?

Cause this is from cakephp/app's composer.json:
```
        // ... 
        "php": ">=5.5.9",

**Comment by lupuswwww** [comment]
Yes, **I confirm** that the problem was in the version of PHP.

**Comment by ionas** [comment]
Which one.
On the server you had issues create a test.php with contents `<?php echo phpinfo() ?>` then check the php version. On the same server on the console type php -v
Same?

**Comment by HavokInspiration** [comment]
@ionas He installed Cake on a local machine which probably had a good enough PHP version and transferred everything through FTP on a server that probably did not have a good PHP version. No composer commands were ran on the server from what I can read.

**Comment by ionas** [comment]
@HavokInspiration now that's not a good idea ;).
I did not find any documentation about it - http://book.cakephp.org/3.0/en/deployment.html 

Is the best practice to have a git repository for your application. Then git pull (or capistrano or whatever) and then run composer install (which respects composer.lock) and would check for php version, then?

If so - worth adding to the docs? Should I setupa  PR?

**Comment by lupuswwww** [comment]
http://localhost/ - Everything works fine (PHP 5.5). 
http://example1.com/ - it does not work  (PHP 5.3).
http://example2.com/ - it does not work  (PHP 5.3).
http://example3.com/ - everything works fine  (PHP 5.6).
I tested three different web servers.

**Comment by ionas** [comment]
@lupuswwww that is to be expected!
Did you read @HavokInspiration 's comment - did you "FTP-deploy" your cake app?

**Comment by lupuswwww** [comment]
Yes, I have read @HavokInspiration's comment. I did just so. I made the installation locally and later I transferred all  files via FTP to server

**Comment by ionas** [comment]
PR #2 https://github.com/cakephp/docs/issues/3815
