### ISSUE TITLE
CorsBuilder don't add header in response

### ISSUE THREAD

**Issue by Draniu** [cakephp/cakephp#8434]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: PHP : 7.0.4-3+deb.sury.org~trusty+4

### What you did
here is my controller

```php
<?php
namespace App\Controller;

class TestController extends AppController {

    public function beforeFilter(\Cake\Event\Event $event) {
        $this->Auth->allow(['sample', 'ok']);
    }

    private function cors() {
        $this->response
                ->cors($this->request)
                ->allowOrigin(['*'])
                ->allowMethods(['GET', 'POST'])
                ->exposeHeaders(['Link'])
                ->maxAge(300)
                ->build();
    }

    public function ok() {
        $this->cors();
        echo '{"status":"OK"}';
        return $this->response;
    }


    public function sample() {
        $this->cors();
        echo $this->sampleData;  
        return $this->response;
    }

    private $sampleData = '[
  {
    "lots": "of data"
  }
] ';

}

```
### Expected Behavior
action `ok` works well
I expect that action `sample` have header `Access-Control-Allow-Origin:*`

### Actual Behavior
in action `sample` in response there is no header `Access-Control-Allow-Origin:*`
but if I cut some (about half ) data from `$this->sampelData` headers appears

**Comment by markstory** [comment]
Did your request include the `Origin` header? The CORS headers will only be set if the request includes an `Origin` header.

**Comment by markstory** [comment]
Also by using `echo` in your controller, the response object cannot send headers. Instead you should use `$this->response->body('{"status":"OK"}');`

**Comment by Draniu** [comment]
i know that i should not use echo in controller but i did this controller for testing purpose 

when i change `echo` to `$this->response->body()` it works like a charm 
but with `echo` even `$this->response->header()` wont work

**Comment by AD7six** [comment]
> but with echo even $this->response->header() wont work at all

Because if you do that - you're provoking "Cannot modify header information - headers already sent by `echo`"

**Comment by ADmad** [comment]
Stop echoing content from controller and just return the response object with header and body set and you won't have any problems.

**Comment by Draniu** [comment]
yes but why it  works for short strings? it should not work at all or it should work always...   
And there is no think in log, no warning or anything

**Comment by markstory** [comment]
It has to do with server API output buffering. Apache and php-fpm will buffer a few hundred bytes before flushing. This is why a small response works fine but a large one does not.  A larger response body will cause an implicit flush which outputs headers.

**Comment by Draniu** [comment]
Thank you very much for your detailed explanation :) 
I admire your work :)
