### ISSUE TITLE
3.2.4 - Saving BTM as entities with joinData not working as expected

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8440]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: PHP 5.6.10, MAMP running Apache on port 80

### What you did
So, I know I've brought up stuff like this in the past and it usually came down to a user error, but I've been trying to get something to work for about 12 hours and I'm pretty sure it's a bug. I can't get `_joinData` to persist when saving BTM entities.

For all examples, the `$this` context is inside `UsersTable`.

Using arrays works as expected, `users_crews` has two records, one with primary=1, one with primary=0.
```
$user = $this->get(287080);
$crews = [
    ['id' => 2688, '_joinData' => ['primary' => 0]],
    ['id' => 2696, '_joinData' => ['primary' => 1]]
];
$this->patchEntity($user, ['crews' => $crews]);
$this->save($user);
pr($user);
```

When doing it via entities, this doesn't save any joint records (not even dealing with _joinData):
```
$user = $this->get(287080);
$crew1 = $this->Crews->get(2688);
$crew2 = $this->Crews->get(2696);
$crews = [$crew1, $crew2];
$this->patchEntity($user, ['crews' => $crews]);
$this->save($user);
pr($user);
```

I thought to myself, hey maybe I should flatten the entity with `toArray`, and it works, this saves two joint records:
```
$user = $this->get(287080);
$crew1 = $this->Crews->get(2688);
$crew2 = $this->Crews->get(2696);
$crews = [$crew1->toArray(), $crew2->toArray()];
$this->patchEntity($user, ['crews' => $crews]);
$this->save($user);
pr($user);
```

But, I need that _joinData, and toArraying an entity removes the _joinData. This saves two records, but since it takes out the _joinData, primary=0 for both:
```
$user = $this->get(287080);
$crew1 = $this->Crews->get(2688);
$crew1->_joinData = ['primary' => 1];
$crew2 = $this->Crews->get(2696);
$crew2->_joinData = ['primary' => 0];
$crews = [$crew1->toArray(), $crew2->toArray()];
$this->patchEntity($user, ['crews' => $crews]);
$this->save($user);
pr($user);
```

The docs say to use the `link` method, so I tried that. This doesn't persist the _joinData, but saves two records:
```
$user = $this->get(287080);
$crew1 = $this->Crews->get(2688);
$crew1->_joinData = ['primary' => 1];
$crew2 = $this->Crews->get(2696);
$crew2->_joinData = ['primary' => 0];
$crews = [$crew1, $crew2];
$this->Crews->link($user, $crews);
```

However, when running the above twice, it throws an integrity error, since the joint records aren't being checked to already exist. I'd expect that to happen automatically, but I guess with link, you have to manually check and unlink? That seems messy.

### Expected Behavior
Patching an entity with BTM entities with _joinData should work as expected.

### Actual Behavior
Explained inline above.

**Comment by markstory** [comment]
So if I understand the issue correctly, when you are trying to update the `_joinData` on existing records that were loaded with `Table->get()` the joinData does not persist correctly?

The last example is probably your best option, but the `_joinData` property will need to be an Entity and not an array. The ORM won't persist array data that should be entities. Can you try:

```php
$crew2->_joinData = new Entity(['primary' => 0], ['markNew' => true]);
```

instead of the array data.

**Comment by patrickconroy** [comment]
Thanks @markstory.. That saves the `_joinData`, however you can only do it once. Running it twice fails my `user_id + crew_id` DB constraint since it's just trying to insert again.

**Comment by markstory** [comment]
I don't think we'll be able to fix the `_joinData` as an array case without causing a slew of other bugs. What does your code look like that does multiple updates?

**Comment by patrickconroy** [comment]
Hm, I don't think I explained everything then.. I'm not doing multiple updates in a single request. Right now in debugging this the only thing happening. I'm trying to save the BTM data with _joinData, and just once. This is my entire code right now to simplify things:
```
$user = $this->get(287080);
$crew = $this->Crews->get(2688);
$crew->_joinData = new Entity(['primary' => 1]);
$this->Crews->link($user, [$crew]);
```
So, say the crew someone is linked to changes from primary=1 to primary=0 after a few hours. The next time I run the code, it'll fail, since there's already a row in the joint table. Are you saying that once a joint record exists it shouldn't be editable?
I don't understand how/why this works fine with arrays but not entities. I *can* flatten the entity, then add a `_joinData` key to it, and it'll work:
```
$user = $this->get(287080);
$crew = $this->Crews->get(2688)->toArray();
$crew['_joinData'] = ['primary' => 0];
$this->patchEntity($user, ['crews' => [$crew]]);
$this->save($user);
```
If that works, I'd expect both entities using either patchEntity/save or link would work.

**Comment by markstory** [comment]
Ah ok. I didn't understand, but now I do. If the joinData exists you would have update the existing _joinData entity. Replacing it with a new entity will cause the primary key error you're running into, as the new entity doesn't know about the database record.

**Comment by patrickconroy** [comment]
Hm, well doesn't that mean no one can do this in app code without first doing checks for the joint record? That seems like logic that the core should take care of.

It also doesn't explain why this doesn't work, not even worrying about `_joinData`:
```
$user = $this->get(287080);
$crew = $this->Crews->get(2688);
$this->patchEntity($user, ['crews' => [$crew]]);
$this->save($user);
```
You'd expect that to save a joint record in `users_crews`, but it doesn't. Only when you call `$crew->toArray()` will it save.

It seems like all this means the docs are wrong since you can't reliably do this, since you'd first need to check that `through` table for existence:
```
$tag1 = $articlesTable->Tags->findByName('cakephp')->first();
$tag1->_joinData = $articlesTable->ArticlesTags->newEntity();
$tag1->_joinData->tagComment = 'The CakePHP ORM is so powerful!';
$articlesTable->Tags->link($article, [$tag1]);
```
 Shouldn't that be changed to be this? (Also adding the creation of `$article` since that's missing.)
```
$article = $articlesTable->get(12);
$tag1 = $articlesTable->Tags->findByName('cakephp')->first();
$tag1->_joinData = $articlesTable->ArticlesTags->findOrCreate([
    'article_id' => $article->id,
    'tag_id' => $tag1->id,
]);
$tag1->_joinData->tagComment = 'The CakePHP ORM is so powerful!';
$articlesTable->Tags->link($article, [$tag1]);
```
Another tangent, would ``$articlesTable->ArticlesTags`` ever work? If `ArticlesTable` belongsToMany `Tags`, there's no route to go directly from `ArticlesTable` to a `through` table. In my code I have to use the `TableRegistry` to get my `through` table instance.

**Comment by patrickconroy** [comment]
Is it that `patchEntity` doesn't work when patching with other `entities`? If I use `Table::set`, everything works.

Doesn't work:
```
$user = $this->get(287080);
$crew = $this->Crews->get(2688);
$this->patchEntity($user, ['crews' => [$crew]]);
$this->save($user);
```

Works:
```
$user = $this->get(287080);
$crew = $this->Crews->get(2688);
$user->set('crews', [$crew]);
$this->save($user);
```

If `patchEntity` isn't supposed to work, then there might be no bug (except I think the docs should probably be updated with my previous comment).

**Comment by ADmad** [comment]
Have you tried passing `['associated' => '_joinData']` in `patchEntity` options?

**Comment by markstory** [comment]
> Is it that patchEntity doesn't work when patching with other entities? If I use Table::set, everything works.

Yes. patchEntity() is intended to apply array/request data updates to existing entities. You can't 'patch' objects together as the marshaller is for converting array/request data into entities. If your request data used the `['id' => 2688, '_joinData' => ['primary' => 0]]` form you wouldn't run into any issues (as you know).

**Comment by patrickconroy** [comment]
Sorry for the delay..

@ADmad - So, strangely, sending literally anything to `associated` makes the `save` call work.. Is this indicative of another bug somewhere?
```
$this->Users->patchEntity($user, ['crews' => [$crew]], ['associated' => 'klfhgjjdfhg']);
```

@markstory - it seems like ideally `patchEntity` would work? Could the marshaller detect if something it's trying to marshal is already an Entity then continue onto the next thing?

**Comment by markstory** [comment]
I'm hesitant to add more complexity into the marshaller. It is already a very complex bit of code and increasing that complexity when we have reasonable alternatives (using the array data, or using updating the `_joinData` records through methods calls) seems like we'd be increasing the potential for future issues.

The marshaller does a few different checks with the `associated` key. Putting invalid associations shouldn't cause harm, and a non-empty value enables the normalization code paths which likely set the code up for 'success' later on.

**Comment by ADmad** [comment]
I agree with @markstory about not adding more complexity to the marshaller.

**Comment by patrickconroy** [comment]
OK thanks guys. I still think http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-data-to-the-join-table could be better, since that won't work twice (you'd have to do the `findOrCreate` for the joint entity).

**Comment by markstory** [comment]
@patrickconroy I can update the docs with a more resilient example.
