### ISSUE TITLE
Transliteration utility

### ISSUE THREAD

**Issue by glafarge** [cakephp/cakephp#8441]
This is a feature-discussion (RFC).

It can be useful to make a transliteration function to replace accented characters for example.
What do you think about this ?

```php
namespace Cake\Utility;

class Inflector
{
    /**
     * Returns a string with all accented characters converted to non-accented characters.
     *
     * @param string $string
     * @return string
     */
    public static function transliterate($string)
    {
        return str_replace(
            array_keys(static::$_transliteration),
            array_values(static::$_transliteration),
            $string
        );
    }
}
```

I can make a PR if needed.

**Comment by markstory** [comment]
Inflector::slug() does this to some degree.

**Comment by glafarge** [comment]
Stripping accented characters can be useful to :
- treat filenames (with support of extensions)
- transform keys in associative arrays to keep a correct order when sorting with `ksort()` for example

I think it can be useful for people that deal with accents in their projects.
Let me know your opinion...

**Comment by dereuromark** [comment]
So you mean a `Inflector::transliterate()` as a lightweight form of slug() then?
I wonder if slug() itself would maybe already suffice here, too.

**Comment by glafarge** [comment]
Exactly. It would make this possible for those who need it when they want to keep a file extension or spaces and transliterate only special characters.
But I know it also add a kind of complexity to Inflector class...

**Comment by burzum** [comment]
> Exactly. It would make this possible for those who need it when they want to keep a file extension or spaces and transliterate only special characters.

Why is something like this not good and easy enough?

```php
str_replace($arrayOfSpecialChars, $arrayOfReplacements);
````

**Comment by markstory** [comment]
@burzum I wonder if that would also be a good option for making `Inflector::slug()` simpler.

**Comment by ADmad** [comment]
Modifying `Inflector::slug()` to use `Transliterator` might not be good idea as it probably won't yield the same results for all cases and would cause problem with existing apps. If we were to use it it should be a nice method and deprecate `Inflector::slug()`.

I gave using `Transliterator` a shot and added a new method [Text::slug()](https://github.com/cakephp/cakephp/compare/master...ADmad:slug-transliterator). Using existing tests for `Inflector::slug` [this](https://travis-ci.org/ADmad/cakephp/jobs/115790137#L404) is the result.

The output can be various based on [transliterator id](https://github.com/cakephp/cakephp/compare/master...ADmad:slug-transliterator#diff-cd236edd88c12968d12fb93403d11d10R868) used. We could allow people to set their own default id string.

**Comment by glafarge** [comment]
@ADmad We could also use a per language mapping like [URLify](https://github.com/jbroadway/urlify/blob/master/URLify.php#L20) does.

**Comment by ADmad** [comment]
@glafarge `Inflector::slug()` already uses a common mapping list like this for replacements. The point of using `Tranliteration` class is to avoid having to maintain such a list ourselves and make maintenance easier.

**Comment by glafarge** [comment]
@ADmad in this case `Transliterator` class is not a good choice for the moment. I notice that [umlauts are not converted](https://travis-ci.org/ADmad/cakephp/jobs/115790137#L404) like `Inflector::slug()` does. Locales for germany seem not existing yet.
Also, I think it will be more simpler to keep things in their current state to avoid complications.

For specific cases, we can still use the `Transliterator` native class if we need to.

Furthermore, [ICU website](http://userguide.icu-project.org/transforms/general) was very interesting to read.

**Comment by glafarge** [comment]
As the commit 7beb1b42909a6cd59a3a0300c1a3b1355e496398 resolves this issue, i close the issue.
:+1: Thanks @ADmad for the good job on it !
