### ISSUE TITLE
Datasource not found

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/cakephp#8443]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: Mac, Nginx, Not relevant

### What you did
Created a file at plugins/Wholsalify/src/Datasource/Connection.php with the following content

```
<?php
namespace Wholsalify\Datasource;
class Connection {}
```

Added the following to config/app.php

```
    'Datasources' => [
        // other datasources
        'wholsalify' => [
            'className' => 'Wholsalify\Datasource\Connection',
            'driver' => 'Wholsalify\Datasource\Connection',
```

Added the following to config/bootstrap.php

``Plugin::load('Wholsalify');``

### Expected Behavior

Expected to have a datasource file that would be found automatically using the above settings. 

### Actual Behavior

I get the message ``Error: Datasource class Wholsalify\Datasource\Connection could not be found. Datasource class Wholsalify\Datasource\Connection could not be found.``

Please note: I also tried moving that Datasource folder around to various locations and get the same error no matter where I put it.

**Comment by ionas** [comment]
http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration Dot Syntax?

**Comment by markstory** [comment]
How did you configure the autoloader for you plugin?

**Comment by CodeBlastr** [comment]
I added ``, ['autoload' => true]`` to ``Plugin::load('Wholsalify');`` so that it looks like this ``Plugin::load('Wholsalify', ['autoload' => true]);`` and it works.  Closing the issue.

**Comment by markstory** [comment]
You could also update your composer.json and regenerate you autoloader with `composer dumpautoload`.
