### ISSUE TITLE
Form url - controller action parameter issue

### ISSUE THREAD

**Issue by AdamDomafoldi** [cakephp/cakephp#8445]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2.2

### What you did
I have some variables($category,$subcategory,$subsubcategory) which have been passed to the controller's action as a parameter. In the controller's action I pass these variables to the view again(They have value of course). When I create a form and place them there as parameters I receive a bug.
ProductsController/index
```
$this->set('category',$category);
$this->set('subcategory',$subcategory);
$this->set('subsubcategory',$subsubcategory);
```
ProductsView/index
`echo $this->Form->create('Product',['type'=>'GET','url'=>['controller'=>'products','action'=>'index',$category,$subcategory,$subsubcategory]]);`

### Expected Behavior
Normal get link with parameters.
One thing: If I declare these variables in the view it works like charm. However, In debugkit the variables looks fine with eligible value.

### Actual Behavior
` <form method="get" accept-charset="utf-8" action="/szakdolgozat/products/index/%7B%0A%20%20%20%20%22category_name%22%3A%20%22Tejterm%5Cu00e9kek%22%2C%0A%20%20%20%20%22category_link%22%3A%20%22tejtermekek%22%2C%0A%20%20%20%20%22subcategories%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subcategory_name%22%3A%20%22Sajtok%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subcategory_link%22%3A%20%22sajtok%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategories%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategory_name%22%3A%20%22Kecskesajtok%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategory_link%22%3A%20%22kecskesajtok%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subcategory_name%22%3A%20%22Tejek%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subcategory_link%22%3A%20%22tejek%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategories%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategory_name%22%3A%20%22Kecsketejek%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22subsubcategory_link%22%3A%20%22kecsketejek%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D/%7B%0A%20%20%20%20%22subcategory_name%22%3A%20%22Tejek%22%2C%0A%20%20%20%20%22subcategory_link%22%3A%20%22tejek%22%2C%0A%20%20%20%20%22subsubcategories%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22subsubcategory_name%22%3A%20%22Kecsketejek%22%2C%0A%20%20%20%20%20%20%20%20%22subsubcategory_link%22%3A%20%22kecsketejek%22%0A%20%20%20%20%7D%0A%7D/kecskesajtok">    <div class="form-group">`

### How I've solved it
I just declared some variables at the beginning of the view, but it remains a bug.
`  $category_param = $category;
  $subcategory_param = $subcategory;
  $subsubcategory_param = $subsubcategory;`

**Comment by markstory** [comment]
What is in those variables? It looks like complex arrays of data. Given the context here I don't know what the right output is or how to reproduce your issue.

**Comment by AdamDomafoldi** [comment]
They are simple strings, but I set them more clearly:
controller
`$this->set('category','alkoholos-italok');
$this->set('subcategory','sor');`
view
`  <?php echo $this->Form->create('Product',['type'=>'GET','url'=>['controller'=>'products','action'=>'index',$category,$subcategory]]); ?>`

And the result is the above mentioned problem.

**Comment by markstory** [comment]
Ok. If you create a Form url using hardcoded strings do you have the same issue? From the previous dump those variables appear to be containing arrays.

**Comment by AdamDomafoldi** [comment]
If I use hardcoded strings or declare these variables at the beginning of the view then it works fine. 

That's why my solution was to declare additional variables and give them as a value the previously passed variables from the controller. 

So In my controller:
`$this->set('category','alkoholos-italok'); $this->set('subcategory','sor');`
in my view:

>   $cat = $category;
>   $sub = $subcategory;
>   $subsub = $subsubcategory;
> 
> echo $this->Form->create('Product',['type'=>'GET','url'=>['controller'=>'products','action'=>'index',$category,$subcategory]]);

In this case it works fine but if I want to just place their  into the form explicitly then I receive error.

**Comment by ADmad** [comment]
Btw a string 'Product' is not a valid argument for 1st argument `FormHelper::create()`. Check API for valid value types.

**Comment by markstory** [comment]
Ok, but that takes me back to my original question. What _are those variables_? What comes out of `var_dump($category)` for example? Assigning a new variable name doesn't change the contents of a variable. My suspicion is that those variables contain types that don't fit into URLs nicely.

**Comment by AdamDomafoldi** [comment]
All right so in my view I've made these:
`  var_dump($category);
  var_dump($subcategory);`
results: 
`string 'tejtermekek' (length=11) 
string 'tejek' (length=5)`

I corrected the argument of FormHelper::create() to NULL

**Comment by markstory** [comment]
Ok, I'm unable to reproduce your problem with the following code:

```php
$category = 'tejtermekek';
$subcategory = 'tejek';
echo $this->Form->create(null, ['type' => 'GET', 'url' => ['controller' => 'Products', 'action' => 'index', $category, $subcategory]);
```

I decoded your 'bad' URL and it contains the following:

```
{
    "category_name": "Tejterm\u00e9kek",
    "category_link": "tejtermekek",
    "subcategories": [
        {
            "subcategory_name": "Sajtok",
            "subcategory_link": "sajtok",
            "subsubcategories": {
                "subsubcategory_name": "Kecskesajtok",
                "subsubcategory_link": "kecskesajtok"
            }
        },
        {
            "subcategory_name": "Tejek",
            "subcategory_link": "tejek",
            "subsubcategories": {
                "subsubcategory_name": "Kecsketejek",
                "subsubcategory_link": "kecsketejek"
            }
        }
    ]
}/{
    "subcategory_name": "Tejek",
    "subcategory_link": "tejek",
    "subsubcategories": {
        "subsubcategory_name": "Kecsketejek",
        "subsubcategory_link": "kecsketejek"
    }
}
```

Which confirms my earlier suspicions that your variables did not contain strings, but contained array data. Since I cannot reproduce your issue I'm going to close it. I suggest you look at your view variables a bit more closely and ensure that you are not passing complex data into the form URL.
