### ISSUE TITLE
Add factory methods to the Cake\Collection

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8446]
This is an enhancement:

* CakePHP Version: 3.2.3
* Platform and Target: Apache, MySQL, PHP 7

### What you did

```
        $collection = new Collection($arr);
        return $collection->map(function($value, $key) {
             return $value * 2;
        })->toArray();
```

To use the Collection library it has to be instantiated and assigned to a variable.

This creates *used once* assignments of temporary variables. I think it just added extra lines of code.

Alternatively, you could write

```
        return (new Collection($arr))->map(function($value, $key) {
             return $value * 2;
        })->toArray();
```

The above is valid, but it doesn't read very well. It looks like an expression when you're just trying to remove the temp variable.

### Expected Behavior

There are a couple of improvements that would help.

#### Factory Method

```
        return Collection::create($arr)->map(function($value, $key) {
             return $value * 2;
        })->toArray();
```

A factory method allows for easier one liners of code.

I would prefer to just a short cut function. I don't care what it's called but `c` is fine with me.

```
        return c($arr)->map(function($value, $key) {
             return $value * 2;
        })->toArray();
```

#### Static Starter Functions

Another approach would give a quicker starting point from the `Collection` class. It's just a factory method that also chains to a collection method.

```
        return Collection::map($arr, function($value, $key) {
             return $value * 2;
        })->toArray();
```

I know you guys like to keep things light and lean, but improvements in usability can save time in the long run.

**Comment by markstory** [comment]
Have you tried using the `collection()` function? It does the same thing as your proposed c() function.

**Comment by thinkingmedia** [comment]
@markstory I missed that one. It is in the docs but it's only in a few examples at the bottom. I can PR to update the docs for that.

**Comment by jeremyharris** [comment]
Oh cool, I never new about `collection()`.

**Comment by ADmad** [comment]
`collections()` is listed on the manual [here](http://book.cakephp.org/3.0/en/core-libraries/global-constants-and-functions.html#collection) but it's probably missing cross referencing on the [Collections](http://book.cakephp.org/3.0/en/core-libraries/collections.html) for greater visibility.

@thinkingmedia A PR to update the manual would be welcome.

Closing this PR as no code change is required.
