### ISSUE TITLE
matching() multiple times on deep associations with aliased models only appears to JOIN the first alias

### ISSUE THREAD

**Issue by ah8r** [cakephp/cakephp#8448]
This is a:
* [x] bug

* CakePHP Version: 3.2.4
* Platform and Target: Nginx, MySQL

### What you did

I have a Transfers model which belongsTo two different Accounts models:

```php
$this->belongsTo('FromAccounts', [
    'className' => 'Accounts',
    'foreignKey' => 'from_account_id'
]);
        
$this->belongsTo('ToAccounts', [
    'className' => 'Accounts',
    'foreignKey' => 'to_account_id'
]);
```

Accounts belongsTo a single User.

I want to create a query which only returns Transfers where both the FromAccount and the ToAccount match a certain username (e.g. internal transfers). The following query is what I came up with:

```php
$this->Transfers->find('all')->matching('FromAccounts.Users', function ($q) {
    return $q->where(['Users.username' => 'joe']);
})->matching('ToAccounts.Users', function ($q) {
    return $q->where(['Users.username' => 'joe']);
});
```

### Expected Behavior

Only Transfers where both the FromAccount and ToAccount are owned by the User 'joe' should be returned.

### Actual Behavior

The query only seems to match Transfers where the FromAccount is owned by the User 'joe', and ignores the ToAccount user completely. This is confirmed by using the sql() command to output the raw SQL:

```sql
SELECT Transfers.id AS `Transfers__id`, Transfers.from_account_id AS `Transfers__from_account_id`, Transfers.to_account_id AS `Transfers__to_account_id`, Transfers.amount AS `Transfers__amount`, FromAccounts.id AS `FromAccounts__id`, FromAccounts.user_id AS `FromAccounts__user_id`, FromAccounts.total AS `FromAccounts__total`, Users.id AS `Users__id`, Users.name AS `Users__name`, ToAccounts.id AS `ToAccounts__id`, ToAccounts.user_id AS `ToAccounts__user_id`, ToAccounts.total AS `ToAccounts__total` FROM transfers Transfers INNER JOIN accounts FromAccounts ON FromAccounts.id = (Transfers.from_account_id) INNER JOIN users Users ON (Users.name = :c0 AND Users.id = (FromAccounts.user_id)) INNER JOIN accounts ToAccounts ON ToAccounts.id = (Transfers.to_account_id)
```

As you can see from the above SQL, the Users.name field only appears in one JOIN (with FromAccounts) and the JOIN with ToAccounts does not appear to occur. This leads me to believe that this is a bug, or I perhaps have set up the associations incorrectly, though the CakePHP book had similar examples: http://book.cakephp.org/3.0/en/orm/associations.html

**Comment by lorenzo** [comment]
This is probably just how it is supposed to work. Supporting the same association alias in the the same query for different paths would be actually very difficult, but I'll take a look at how this could be implemented.

The best solution I have for you now is to create another association for the users stable with a different alias. This way you would not have repeated aliases in the query, which is the main problem

**Comment by ah8r** [comment]
> The best solution I have for you now is to create another association for the users stable with a different alias. This way you would not have repeated aliases in the query, which is the main problem

Thanks, that works perfectly.

**Comment by ah8r** [comment]
> This is probably just how it is supposed to work. Supporting the same association alias in the the same query for different paths would be actually very difficult, but I'll take a look at how this could be implemented.

On this issue, if it's too difficult to implement then I think at least there should be an exception thrown to let developers know, otherwise there may be instances where people are writing matching() statements like mine and assuming they are working when they don't.

The code in my case produces no errors; it runs fine and returns data, but the data itself is wrong, and I only noticed through testing with different datasets.
