### ISSUE TITLE
phpunit code coverage fails with No whitelist configured, no code coverage will be generated error

### ISSUE THREAD

**Issue by rrd108** [cakephp/cakephp#8451]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.11
* Platform and Target: Apache/2.4.12 (Ubuntu), PHP Version 7.0.4-1+deb.sury.org~wily+1

### What you did
bin/phpunit --coverage-html webroot/coverage tests

### Expected Behavior
PHPUnit supposed to cretae code coverage files

### Actual Behavior
I got this error messahe:
PHPUnit 5.2.10 by Sebastian Bergmann and contributors.
Error:         No whitelist configured, no code coverage will be generated

The tests starts to run but no coverage files are generated.

**Comment by saeideng** [comment]
`phpunit --coverage-html webroot/coverage` works for me
why use `bin/phpunit` ?

**Comment by ADmad** [comment]
[phpunit.xml.dist](https://github.com/cakephp/cakephp/blob/master/phpunit.xml.dist#L37) already has whitelist for coverage and coverage report is generated fine on [travis build](https://github.com/cakephp/cakephp/blob/master/.travis.yml#L76).
