### ISSUE TITLE
HtmlHelper breadcrumbs do not work with cells.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8454]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: Apache 2, MySQL, Windows 10, PHP 7

### Overview

HtmlHelper breadcrumbs do not work for cells.

### What you did

In template for controller's action.

```
    $this->Html->addCrumb('Documents', ['controller' => 'Documents', 'action' => 'index']);
```

In template for cell's action

```
    echo $this->Html->getCrumbs(' / ','Home')
```
### Expected Behavior

Should render the breadcrumbs for the `Documents` controller.

> Note: The cell is rendered by the layout. So breadcrumb data should be available.

### Actual Behavior

There are no breadcrumbs rendered.

#### Reason

A different HtmlHelper instance is used to render the View's for Cells.

#### Recommendations

- Update the docs to clarify that this is normal behavior. Make it a noticeable warning to save developers time later.
- Add a feature that allows developers to inject helpers into child cells.
- Remove breadcrumbs from HtmlHelper because it's tightly coupled to the current View instance, and Cake uses multiple view instances to render output.
- Add ViewData object that is injected into all views. This data object allows for sharing across multiple views (warning: How will this impact element/cell level caching?)
- HtmlHelper should only **render** HTML. It should not be used to store data. The `addCrumb` method should be deprecated, and `getCrumbs` changed to just `crumbs` and work like other helper methods.

**Comment by markstory** [comment]
This behavior is intentional. Cells are intentionally isolated and do not share state with the parent view.

**Comment by thinkingmedia** [comment]
@markstory yes, I understand that. The issue is that the HtmlHelper is being used to store data internally. That is counter to the helper pattern. Since helpers are recreated for each view. The feature of breadcrumbs pre-dates this change and was added when helpers were singletons.

I'm just asking that you think about that for a bit, or comment on it.

**Comment by markstory** [comment]
Where should HtmlHelper store its data instead of on the class?

**Comment by thinkingmedia** [comment]
@markstory I've been thinking about this for a few days. I've run into other areas of CakePHP 3 where data is tightly coupled with a view and I don't think it should be like that. Another example would be `loadModel` in cells. The model factory is unique to each cell/view, but this results in the model not caching SQL queries like it did in CakePHP 2.

As an example, I have a cell that renders a person's contact details. In my main view there could be a dozen contacts (each is a cell). Each cell hits the database with the same SQL queries because the models are being recreated and the caches are not shared.

So I was thinking that the solution is in the `Cake\Network\Request` object. This defines the context of the current HTTP request. Things like Helpers, Models, etc. that need to store data between views could attach their data to the current request. I'm not sure if these would be new methods, a new trait or interface. That part doesn't matter.

**Comment by lorenzo** [comment]
Query caching is independent of how cells work, I think you are experiencing another problem

**Comment by markstory** [comment]
If your cells are emitting duplicate queries, have you considered passing the entities into the cells instead of ids? While `loadModel` seems like it is creating duplicate objects, the underlying `TableRegistry` ensures that the same table objects are reused.

Using the request as a way to transport state between what are supposed to be isolated aspects of an application while viable seems to go against the spirit of cells.
