### ISSUE TITLE
Add support for nested translation domains, so plugins can contain domains

### ISSUE THREAD

**Issue by canon4o** [cakephp/cakephp#8455]
- [ ] bug
- CakePHP Version: 3.2.4.
- Platform and Target: Ubuntu 14.04 Server / php5
### What you did

I baked new plugin and add custom locale file in folder 'plugin_name/src/Locale/bg/months.po'. In both AppController's I have I18n::locale('bg'); and when try to translate month in plugin template, it doesn't work. 

I try to write __d('Administration.months', 3), but not work. Then I try to write __d('Administration/months', 3), but again not work. The only variant which work is when I put locale files outside the plugin folder and translate month with __d('months', 3).
### Expected Behavior

I expect when I write __d('Administration.months', 3), it can be translate and locale files destination is in plugin folder.

**Comment by markstory** [comment]
Each plugin _is_ a domain. We currently don't support nesting domains inside of plugins. Instead you'll have to use `Administration/src/Locale/bg/administration.po` as your file name, which will enable `__d('administration', 'a string')` to be correctly translated.

Given that nested domains are not something we currently support, we could possibly implement it in a future release.

**Comment by canon4o** [comment]
Okay. I hope. Thanks.

**Comment by burzum** [comment]
This plays into this issue as well I think https://github.com/cakephp/cakephp/issues/8316

I've added this to the docs as well:

> If you want to translate your plugins and they're namespaced, you **must** name your domain string `Namespace/PluginName`. But the related language file will become` plugins/Namespace/PluginName/src/Locale/plugin_name.po` inside your plugin folder.

I don't think that the dot syntax the way you use it here ```__d('Administration.months', 3)``` is a good ideas as it is *very* misleading because the dot is usually used for the plugin notation.

The way I think this should work is that a name spaced pluing like `MyFancyPlugin/WithNameSpace``` should become ```MyFancyPluginWithNameSpace``` by default and if you with another name name default.pot ```MyFancyPluginWithNameSpace.otherFileName```.

**Comment by canon4o** [comment]
Yes.  I know that dot is plugin notation, but this is a idea. My plugin name is Administration and my locale file name is months.po.

But your way with dash also will work. My idea with dot is to keep cake plugin notation. :)
