### ISSUE TITLE
dosen't send post helper Form

### ISSUE THREAD

**Issue by mehdi-fathi** [cakephp/cakephp#8459]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.0.0
* Platform and Target:Local Apache 2.4 Windows 8

### What you did
i was working on a project.I saw that form helper didn't send post when form have some default value.actually i use of this code 

`echo $this->Form->input('categories._ids', ['id'=>'list_add_categories']);`

i have option list html.but this didn't send default value.

### Expected Behavior
i think that is a bug.Because of  this is not logical !

**Comment by dereuromark** [comment]
How does your complete form setup look like?
Including create() etc?
What is the actual posted data array look like ($this->request->data)?

**Comment by mehdi-fathi** [comment]
Yes i did.I was surprised.my form do submit.i checked debug kit request data but i don't know list categories is empty!.this is my code.

`<div class="posts form large-10 medium-9 columns">

    <?= $this->Form->create($post, ['enctype' => 'multipart/form-data']); ?>

    <fieldset>

        <legend><?= __('Edit Post') ?></legend>

        <?php
            echo $this->Form->input('user_id', ['options' => $users, 'empty' => true]);

            echo $this->Form->input('title');

            echo $this->Form->input('body',array('type'=>'textarea','id'=>'editor1','rows'=>"10", 'cols'=>"80"));

           echo $this->Form->input('state');

           echo $this->Form->input('image', ['type' => 'file']);   

          echo $this->Html->image("/uploads/$post->image", ['alt' =>$post->alt_image,'width'=>"100%",'height'=>"350px"]);


                                                        
            echo $this->Form->input('lIST._ids', ['options' => $categories,'id'=>'list_categories',]);
            
            echo $this->Form->input('categories._ids', ['id'=>'list_add_categories']);//** My problem this  here  **//

        ?>
    <input id="button_category" type="button" value="Send to List" />

    <div style="float: left;margin-left: 20px;">
    <input id="button_add_category" type="button" value="Remove from list" />
    </div>

    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>`

**Comment by markstory** [comment]
Are you sure there is an option selected? It could be that the select box has no active option. I suspect that if you were to query the DOM the selectbox has no 'value' yet.
