### ISSUE TITLE
Ajax etc I like cascading select lists :-)

### ISSUE THREAD

**Issue by dcallagh** [cakephp/cakephp#8460]
This is a (multiple allowed):
* [x] feature-discussion (RFC)
I like cascading select lists :-) can some one post an example for V 3

* CakePHP Version:  3 - all versions
It used to be pretty simple to write a basic ajax enabled web app from web examples with 1 & 2. Version 3, however, seem sto have has buried this somewhere I cannot find it, I normally just code from examples as I *CANNOT BE BOTHERED* reading yet another round of release documentation.. So, with 3, there is no such luck, probably as there just ain't that many people posting these examples for this version of CAKEPHP any more I guess. 

I am an on and off cake user, from v 1 onwards. Not sure where 3 is going to be honest, it is no easier to create apps, but harder. However if any of us mere users mention this in the various query areas I have noticed the response from a few lords of creation (an 'Andrew' features prominently) is a stomp from a great height but with nary a resolution. This is normally known as bullying. Someone is feeling a bit defensive? Previously have used a great deal of Jquery/Ajax to make pages more responsive ( as opposed to MB of JS JSON Arrays etc, way to go, lets load up the front end). 

I may just use V 2, it works.... It seems to have more of a web app philosophy rather than this purist back-end V 3.0.

**Comment by dereuromark** [comment]
You might want to look into the [Chained Dropdowns](http://sandbox3.dereuromark.de/sandbox/ajax-examples) example in the sandbox as well as the linked source code.
This is not an issue for this bug tracker though.

**Comment by dcallagh** [comment]
Thanks... although I thought it was also a discussion area. 


Sent from Samsung Mobile

-------- Original message --------

**Comment by dakota** [comment]
@dcallagh, this is for tracking bugs or discussing potential new framework features. For help or examples on getting certain features or functionality working, or for general discussions, you should use [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) or the #cakephp channel on irc.freenode.net.
