### ISSUE TITLE
Template path ambiguity.

### ISSUE THREAD

**Issue by SplicePHP** [cakephp/cakephp#8461]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.x.
- Platform and Target: OSX El Capitan, Mamp PHP 7.0.

Okay, here goes. I have been racking my mind about this issue all morning.
It seems that the template paths are a bit overly ambiguous in some cases.
Here is an example of the paths readout for my current scenario:

```
Array
(
    [0] => /www/project/vendor/[THEME]/src/Template/Plugin/[PLUGIN]/
    [1] => /www/project/vendor/[THEME]/src/Template/
    [2] => /www/project/src/Template/Plugin/[PLUGIN]/
    [3] => /www/project/vendor/[PLUGIN]/src/Template/
    [4] => /www/project/src/Template/
    [5] => /www/project/vendor/cakephp/cakephp/src/Template/
)
```

Lets assume I have two plugins.
Each of them have a Dashboard controller and an index action.
The App itself has a Dashboard controller and index action as well.

If I were to create the directory Dashboard with index.ctp in it, it will override the views for both plugins and the App's Dashboard views as well.

This makes it impossible to override an app view from a template without polluting all the plugin views.
In addition if you have a controller and a view in the theme itself those will also pollute the other plugin views unless you put the template inside the Plugin directory of the theme:

```
[0] => /www/project/vendor/[THEME]/src/Template/Plugin/[PLUGIN==THEME]/
```

I do however understand that some ambiguity of this nature can also be a good thing. The same paths that cause the problem also allow the elements and common extend views to be globally overwritten in a single place. For this reason I believe the path order is correct because changing the path order would force you to have to create several copies of the same ctp file in order to override elements and common files that should be over-writeable by simply placing it in the corresponding directory eg:

```
   /www/project/vendor/[THEME]/src/Template/Element/example.ctp
```

If the order was changed it would result in a structure like this for a single override

```
   /www/project/vendor/[THEME]/src/Template/Plugin/[Plugin1]/Element/example.ctp
   /www/project/vendor/[THEME]/src/Template/Plugin/[Plugin2]/Element/example.ctp
   /www/project/vendor/[THEME]/src/Template/Plugin/[Plugin3]/Element/example.ctp
```

As I see it that leaves one option and that is add a Plugin path to the App as well.

Current output for app paths:

```
Array
(
    [0] => /www/projects/master/vendor/[THEME]/src/Template/
    [1] => /www/projects/master/src/Template/
    [2] => /www/projects/master/vendor/cakephp/cakephp/src/Template/
)
```

Suggested output for app paths:

```
Array
(
    [0] => /www/projects/master/vendor/[THEME]/src/Template/Plugin/App/
    [1] => /www/projects/master/vendor/[THEME]/src/Template/
    [2] => /www/projects/master/src/Template/
    [3] => /www/projects/master/vendor/cakephp/cakephp/src/Template/
)
```

With this structure you still have the ability to override basic app views in a theme without polluting the plugin views or losing ease of common element overridability in themes.

This can easily be accomplished by changing the _paths function like so:

From:

```
...
        if (!empty($this->theme)) {
            $themePaths = App::path('Template', Inflector::camelize($this->theme));

            if ($plugin) {
                for ($i = 0, $count = count($themePaths); $i < $count; $i++) {
                    array_unshift($themePaths, $themePaths[$i] . 'Plugin' . DIRECTORY_SEPARATOR . $plugin . DIRECTORY_SEPARATOR);
                }
            }
        }
...
```

To:

```
...
        if (!empty($this->theme)) {
            $themePaths = App::path('Template', Inflector::camelize($this->theme));

            $p = $plugin?:'App';
            for ($i = 0, $count = count($themePaths); $i < $count; $i++) {
                array_unshift($themePaths, $themePaths[$i] . 'Plugin' . DIRECTORY_SEPARATOR . $p . DIRECTORY_SEPARATOR);
            }
        }
...
```

**Comment by markstory** [comment]
Treating the 'app' like its a plugin is a neat idea. From your suggested change, wouldn't we be trading the `/www/projects/master/vendor/[THEME]/src/Template/` path with the new one or am I misreading the code?

**Comment by SplicePHP** [comment]
The problem with putting any templates for the app in /www/projects/master/vendor/[THEME]/src/Template/ is that it not only overrides the app's templates but simultaneously does that for all plugin views of the same controller / action as well. Because this path is called before the plugin's Template path, it makes it impossible to override app layouts without effecting all of the plugins with the same controller / action names . I do however think that this behaviour is correct because it allows global overrides from a single point that is useful for common layouts and elements. Adding App to the plugins would allow you to target the app unambiguously without effecting other plugins. The best thing about this approach is that it doesn't even break any backwards compatibility.

**Comment by markstory** [comment]
Wouldn't removing the existing path cause compatibility issues? Or would the change be adding one new path?

**Comment by SplicePHP** [comment]
I would just add the new one. The existing path is 100% necessary for global overrides. The new one just grants you the ability to override app views without effecting other plugins.

**Comment by dereuromark** [comment]
@SplicePHP Is this still valid? Do you want to try to PR this?

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
