### ISSUE TITLE
Lazy loading of models

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#8462]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: <= 2.8

Since `ClassRegistry::init('ModelName')` throws an `MissingTableException` if the db table doesn't exist, we don't have an option of lazy loading models unless we use some sort of proxy pattern.

The use case is that a global event listener is created (on each request) which takes a model as an constructor argument. Since the event listener is only called *sometimes*, it would be nice if the `MissingTableException` didn't get thrown until an actual `find()` was called.

This is also an issue if the table does exist, because we would then have to use the `ModelNameFixture` in *all* of our unit tests, since CakePHP would complain of the table didn't exist.

**Comment by markstory** [comment]
Is the underlying scenario here that you are creating tables at application runtime? Or are there other conditions that cause the table to be missing but then found?

**Comment by davidsteinsland** [comment]
The first problem is when migrations haven't run yet. However, the problem regarding unit tests will still exist, as we would need to add the fixtures to every single unit test.

**Comment by davidsteinsland** [comment]
Huh, sorry. For some weird reason, we have a call to `getDataSource()` in `AppModel::__construct()` which caused the error.
