### ISSUE TITLE
3.2.4 Validator::integer() vs isInteger()

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8464]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4

### What you did
```php
        $validator
            ->add('id', 'valid', ['rule' => 'integer'])
            ->allowEmpty('id', 'create');
```
Error **Method integer does not exist ReflectionException**
<img width="1275" alt="screen shot 2016-03-14 at 19 09 32" src="https://cloud.githubusercontent.com/assets/106845/13754717/54ec3054-ea18-11e5-80db-831fc7410bd6.png">

### Expected Behavior
It should work (tm) ;-).

### Actual Behavior
This works:
```php
        $validator
            ->add('id', 'valid', ['rule' => 'isInteger'])
            ->allowEmpty('id', 'create');
```

**Comment by lorenzo** [comment]
Was that code generated by bake? I remember that issue being fixed some time ago, try upgrading bake. Otherwise I'll chek if we ever made a release for the plugin

**Comment by ionas** [comment]
*Yes it is probably due to bake and it could be due to my old bake templates.*
But: should `integer()` not work the same `isInteger()` does?

**Comment by lorenzo** [comment]
Check this issue: https://github.com/cakephp/cakephp/issues/8286 and you will understand what is going on.

Closing as this is a duplicate

**Comment by davidyell** [comment]
Found this by a Google search, thanks! I'll double check my bake theme
