### ISSUE TITLE
CakePHP 2.6.12 - Bug input <select> value type "boolean" 1 Or 0

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#8468]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.6.12.
* Platform and Target: PHP 5.2.x, MySQL 5.5, Apache 2.2, Linux.

### What you did
The problem is that does not select the correct value.
I need to do with an input type "SELECT"

**Model:**
```
$validate = array(
...
'requiere_senasa' => array( // <= In Mysql is type 'tinyint' insert 1 or 0
            'boolean' => array(
                'rule' => array('boolean'),
            ),
        ),
...
);
```

$this->Form->value('ClientesDomicilios.requiere_senasa') **is 'false' not selected the option 'No'**
AND
$this->Form->value('ClientesDomicilios.requiere_senasa') **is 'true' not selected the option 'Si'**

**Failure of the 5 ways, an input type "select":**

```
echo $this->Form->input('ClientesDomicilios.requiere_senasa', array(  'type' => 'select',  'options' => array( '1' => 'Si', '0' => 'No' ) )); 
//OR
 echo $this->Form->input('ClientesDomicilios.requiere_senasa', array(  'type' => 'select',  'options' => array( 1 => 'Si', 0 => 'No' ) )); 
//OR
echo $this->Form->input('ClientesDomicilios.requiere_senasa', array(  'type' => 'select',  'options' => array( true => 'Si', false => 'No' ) )); 
//OR
echo $this->Form->input('ClientesDomicilios.requiere_senasa', array(  'type' => 'select',  'options' => array( true => 'Si', false => 'No' ), 'value'=> $this->Form->value('ClientesDomicilios.requiere_senasa') )); 
//OR
echo $this->Form->input('ClientesDomicilios.requiere_senasa', array(  'type' => 'select',  'options' => array( true => 'Si', false => 'No' ), 'default'=> $this->Form->value('ClientesDomicilios.requiere_senasa') )); 
```

### Expected Behavior
I hope you choose the right option.

### Actual Behavior
Never select the one that comes from the Database option.

PS: I remind you that what I have to do with a "select"

**Comment by markstory** [comment]
Is the issue that your validation is failing, or that the select box doesn't remember the selected option when editing a record?

**Comment by EOM** [comment]
**The problem is the rendering of HTML when creating the "SELECT"** but by making the Edit or Add. The data is saved correct way without giving any error.
The big problem is that by making the HTML render, the "SELECT" does not show what has really kept the DB.

**Note:** CakePHP Test in version 2.6.12 which is supporting PHP 5.2.x

**Comment by markstory** [comment]
The issue is coming from the values being booleans, and select box values being compared as strings. The `(string)false` is `''` which is the root of the issue. I'll look into getting this fixed.

**Comment by markstory** [comment]
Pull requests up for 2.x and 3.x
