### ISSUE TITLE
2.8  Calling testAction twice with a URL array fails

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#8480]
CakePHP 2.8.2
Windows
Apache2

When calling ``testAction()`` with a URL array instead of a URL string, it fails the second time with a ``MissingControllerException Controller class C*redacted*Controller could not be found.`` error message in the web test runner or  ``MissingControllerException Controller class ConsoleController could not be found.``error message in the console (C*redacted* = the app sub directory in the web root).

The problem seems to be, that the second time in ``Router::url()``, the ``Router::_requests`` property is not null anymore but contains a mocked request, which then let's the Router return a wrong URL, which then gets used to create a controller mock.

My (simplified) test code:

```` php
		$itemId = 3;
		$this->testAction(
			array('controller' => $this->_controllerName, 'action' => 'get_physical_slots_options', $itemId),
			array('method' => 'get')
		);

		$itemId = 8;
		$this->testAction(
			array('controller' => $this->_controllerName, 'action' => 'get_physical_slots_options', $itemId),
			array('method' => 'get')
		);
````

AutoMock is enabled and before calling the first time, there is already a manually generated mock.

First call to testAction:

![parse_route_first](https://cloud.githubusercontent.com/assets/625761/13824163/308b80de-ebad-11e5-8d53-597e62815122.png)

![automock_bug_first](https://cloud.githubusercontent.com/assets/625761/13824154/2bea70d0-ebad-11e5-83d0-059c0246c5d0.png)

Second call to testAction:

![parse_route_second](https://cloud.githubusercontent.com/assets/625761/13824196/466f1172-ebad-11e5-9258-53eccc0c0fa8.png)

![automock_bug_second](https://cloud.githubusercontent.com/assets/625761/13824353/f115d9da-ebad-11e5-9f00-118334cee65b.png)

**Comment by markstory** [comment]
It makes sense that in the second testAction() call the router would have a request, as you just completed a request. One possible solution would be to call `Router::popRequest()` inside `testAction()` once the result has been created.

**Comment by dereuromark** [comment]
I always used a single testAction() call per test method as workaround so far.
But fixing this would be the better solution for sure.

**Comment by markstory** [comment]
@dereuromark From reading the code it would also happen with string URLs. Has that been your experience as well?

**Comment by dereuromark** [comment]
Yes, of course.
But I never really used string URLs here anyway.

**Comment by ravage84** [comment]
I converted this test method with these two (actually more) calls from string to array. then it failed. reverted back to string and it works again.

**Comment by dereuromark** [comment]
Maybe I remember it differently then, as I said, never really used strings.

**Comment by ravage84** [comment]
@dereuromark I'm somewhat confused. The support for arrays in ``testAction`` was added to CakePHP 2.7, accoring to http://book.cakephp.org/2.0/en/appendices/2-7-migration-guide.html#controllertestcase.

> ``ControllerTestCase::testAction()`` now supports an array as URL.

How could you have used it before?

**Comment by dereuromark** [comment]
Hm, trying to remember.
I think I used Router::url(myArray) before that (manually making the array to string), so I must have used strings.
Since it wasn't too clear to me back then, what the issue was I just went with the one testAction per test and that worked.

**Comment by markstory** [comment]
I did a quick test and string URLs and multiple testAction() calls works :ok:. I was able to reproduce the issue with Array URLs. I'll dig some more tomorrow.

**Comment by markstory** [comment]
Pull request up now.
