### ISSUE TITLE
3.2.5 - Finding via a BTM association failing if either junction table contains a dot

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8486]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: PHP 5.6.10, MAMP running Apache

### What you did
When trying to run a `find` directly on a BTM association e.g. `$this->A->B->find()` (instead of using the `TableRegistry`), I'm seeing an error since the core doesn't know where the junction table is. I don't think this always happened.
I have two tables, `A belongsToMany B`. `A`'s `table()` value is `database.a` and `B`'s `table()` value is `database.b`. In `BelongsToMany::_junctionTableName` the `tableNames` array becomes `database.a_database.b`, when it should be just `a_b`. It seems like this:
```
$tablesNames = array_map('\Cake\Utility\Inflector::underscore', [
    $this->source()->table(),
    $this->target()->table()
]);
```
Should be this:
```
$tablesNames = array_map('\Cake\Utility\Inflector::underscore', [
    $this->source()->alias(),
    $this->target()->alias()
]);
```
For now I'm specifying the `throughTable` directly and it works.

### Expected Behavior
Finding via the association should work normally without needing to specify the `throughTable`.

### Actual Behavior
This tries to use `TableRegistry::get('database.a_database.b')` which doesn't exist.

**Comment by markstory** [comment]
We used to use `alias()` but has to switch to table names because of #6344. Changing this behavior now will result in a different group of sad folks. You'll need to set the `joinTable` option when your tablenames contain a database prefix.

**Comment by patrickconroy** [comment]
OK thanks @markstory. Do you think there's a chance the core will get an update that lets `Table::table()` only need to use the actual table name, and there be some other way for the ORM to prefix the DB name, with like a Table config option? I think that's been brought up in the past but not sure where it landed.

**Comment by markstory** [comment]
There has been some improved support added recently for automatically detecting cross schema joins (#8354) which might remove some of the need to include the database name in the table name.

**Comment by patrickconroy** [comment]
Thanks @markstory. Not messing with the `table()` method would be ideal. I just tried using that branch and it seems like deep joins don't work as expected, for e.g. this tries to use `posts_db.tags_translataions` when it should be `tags_db.tags_translations`. Should I add a note to that PR, or open an issue for it? 
```
$posts = TableRegistry::get('Posts')
    ->find()
    ->contain(['Tags' => ['TagsTranslations']])
    ->limit(4);
```

**Comment by markstory** [comment]
If your junction table could end up on a different database than one side of the relationship, it would be safest to define table name in a concrete Table class.

**Comment by patrickconroy** [comment]
Well it's in the DB of its parent.. `TagsTranslations` is in the `Tags` DB. It seems like #8354 should address that scenario and figure out that a deep association needs to have a DB prefix since it's not in the DB of the main query (which I think is what it's doing for the primary associations).
Quick question, why doesn't every join just prepend the DB by default? That might be an ignorant question since I only work with MySQL so I don't know how other systems work.. it's possible that could make everything else explode. Could there be something in the connection string that says "if this connection is used, always prepend with the DB"? From a logic / SoC perspective it doesn't make sense to me that the `Table::table` method would need to return the DB+table. I understand why that's currently the case, but maybe in a future version it'd be unnecessary?

**Comment by lorenzo** [comment]
After  #8354 it is not needed to return the DB + table name from the table() method.

**Comment by patrickconroy** [comment]
Hey @lorenzo, it's almost not needed but if you have a deep contain it doesn't work as expected. The last example (couple comments up) shows an error with that PR. If the main query contains something which contains something_b, then something_b won't have the full DB+table path.

**Comment by patrickconroy** [comment]
@lorenzo, should I bug that or are deep contains not supposed to work automatically?

**Comment by lorenzo** [comment]
not sure what you mean. Can you explain?

**Comment by patrickconroy** [comment]
With that PR, if you do this:
```
$posts = TableRegistry::get('Posts')
    ->find()
    ->contain(['Tags' => ['TagsTranslations']])
    ->limit(4);
```
The query will try to use `tags_translations` and the main `from` is on `posts.posts`, so the DB thinks you're trying to use `posts.tags_translations`, but that should be `tags.tags_translations`. Deep contains don't work with that PR without still explicitly overriding the `Table::table` method.

**Comment by patrickconroy** [comment]
Just pinging this again because the issue itself doesn't show up in searches (https://github.com/cakephp/cakephp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+patrickconroy) so I don't know if you saw the update, @lorenzo.

**Comment by patrickconroy** [comment]
I don't think anyone's seeing these updates, paging doctors @lorenzo & @markstory again..

**Comment by lorenzo** [comment]
Open a new ticket please, it seems like updates in this ticket are being ignored easily
