### ISSUE TITLE
Connection issues on SQL Server datasource

### ISSUE THREAD

**Issue by giamma93** [cakephp/cakephp#8489]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5 (3.x).
* Windows 7 Professional x64 (XAMPP php 5.6, sql server 2012, apache 2.4).

After i defined multiple datasource, and try to use sql server datasource, i get a fatal error:

2016-03-18 10:04:39 Error: Fatal Error (1): Call to a member function getAttribute() on null in [C:\xampp\htdocs\crm\vendor\cakephp\cakephp\src\Database\Dialect\SqlserverDialectTrait.php, line 85]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 215
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??

Dirty solution:
Before any operation by the datasource use connect() for the first time:
$connection = ConnectionManager::get('sqlserver_conn');
$connection->connect();
$connection->doStuff;

**Comment by lorenzo** [comment]
Note: This issue is present in the connection class and affects all drivers

**Comment by giamma93** [comment]
Sorry, but on my default connection (mysql), can call directy new query after getConnection and work without issue.

**Comment by markstory** [comment]
Pull request open now.
