### ISSUE TITLE
add option to persist query string with Router::redirect

### ISSUE THREAD

**Issue by kminek** [cakephp/cakephp#8491]
i think that such ability often occurs (Google Analytics params etc.)

**Comment by ADmad** [comment]
You can just include `'?' => $this->request->query` in the redirect url.

**Comment by kminek** [comment]
i'm referin to this functionality: http://book.cakephp.org/3.0/en/development/routing.html#redirect-routing

**Comment by Erwane** [comment]
what about this please ?

**Comment by markstory** [comment]
The `persist` option doesn't persist individual query parameters, it only persists routing keys or positional arguments.
