### ISSUE TITLE
May be true for EntityTrait::has('exist_empty_property')

### ISSUE THREAD

**Issue by kanonji** [cakephp/cakephp#8494]
I think there is a mismatch between doc block and code in `EntityTrait::has()`

>     /**
>      * Returns whether this entity contains a property named $property
>      * regardless of if it is empty.
>      *
>      * ### Example:
>      *
>      * ```
>      * $entity = new Entity(['id' => 1, 'name' => null]);
>      * $entity->has('id'); // true
>      * $entity->has('name'); // false
>      * $entity->has('last_name'); // false
>      * ```
> https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L318-L329

The Example in doc block is correctly expressed actual behavior.
But head of doc block is different.

```
$entity->not_associated; // property is not exists.
$entity->associated_has_one_but_no_record; // there is a property but null
```

I want discriminate two cases above with `EntityTrait::has()`.
I guess this is one of the reasons `EntityTrait::has()` is implemented.
Or could it be that head of doc block is wrong?

### Expected Behavior

```
$entity = new Entity(['id' => 1, 'name' => null]);
$entity->has('name'); // true
```

### Actual Behavior

$entity = new Entity(['id' => 1, 'name' => null]);
$entity->has('name'); // false

**Comment by lorenzo** [comment]
The current behaviour is the intended behaviour. I agree there is a need fo another method to check he presence of a field, regardless of its value.

**Comment by kanonji** [comment]
hmm...Do I misunderstand the first sentence in the doc block?
But anyway I'm glad if CakePHP has another method.

**Comment by markstory** [comment]
I think the use of 'empty' is confusing here. As 'empty' means something very specific in PHP which this method is not doing. I can change up the wording to be less confusing.

**Comment by markstory** [comment]
Pull request up now.
