### ISSUE TITLE
Missing multiple select validation method

### ISSUE THREAD

**Issue by Perzonallica** [cakephp/cakephp#8495]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: localhost, 5.6.11-1ubuntu3.1, Apache/2.4.12 (Ubuntu), Mysql 5.6.28-0ubuntu0.15.10.1

### What you did
Hello guys! I wanted to use the multiple select validation, which is explained here: http://api.cakephp.org/3.2/class-Cake.Validation.Validation.html#_multiple
I implemented it this way: 
`$validator->multiple('platforms', ['min' => 1], false);`

### Expected Behavior
I expected it will validate the multiple selectbox.

### Actual Behavior
But instead it threw a Fatal error, when I refreshed the "add" page: **Error: Call to undefined method Cake\Validation\Validator::multiple()** 
So I checked the method in the src/Validation/Validator.php and there is no "multiple" function. Am I doing something wrong, or is it really missing?

**Comment by Perzonallica** [comment]
Ah, SORRY guys, my bad, I need to use it this way:

`->add('platforms', [
                'multiple' => [
                    'rule' => ['multiple', ['min' => 1], false],
                    'message' => 'Min is 1',
                ]
            ]);`

**Comment by ADmad** [comment]
Looks like convenience methods like `money()`, `multiple()` of `Validation` class have not be added to the `Validator` class.

**Comment by markstory** [comment]
Pull request up to add the missing proxies.
