### ISSUE TITLE
Remove AuthComponent Class Definition

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/cakephp#8502]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: not relevant

### What you did
Added a bootstrap theme. 

### Expected Behavior
Expected the auth alerts to respect the theme settings. 

### Actual Behavior
I ended up having to spend 3-5 hours working on why they weren't being respected and opened multiple issues with those developers to come to the conclusion that AuthComponent shouldn't be setting the class like it is. 

I've confirmed that by removing this line 
https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L446

The theme settings are respected.  Here are the relevant issues opened on various plugins. 

https://github.com/FriendsOfCake/bootstrap-ui/pull/141#issuecomment-199117807

https://github.com/CakeDC/users/issues/326

**Comment by markstory** [comment]
Removing that default is a breaking change, so we can't do it.
