### ISSUE TITLE
Error when loading MSSQL database view model (Cannot describe xxx. It has 0 columns.)

### ISSUE THREAD

**Issue by aswzen** [cakephp/cakephp#8504]
I have experience in using cakephp 2 but i have no idea in cakephp 3.

My database admin keep creating database with uppercase name even in column name, so i have to make cakephp model with custom table/view name.

```
<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class ListCrewBooking extends Table
{
    public function initialize(array $config)
    {
        $this->table('VW_CREW_ON_DUTY');
    }
}
```
and then i want to preview it on a controller directly without a cake view (using die();)

```
class TestController extends AppController
{
    function index(){

        $this->viewBuilder()->layout = false;
        $this->loadModel('ListCrewBooking');

        $data = $this->ListCrewBooking->find('all');
        pr($data);
        die();
    }
}
```
and then an error come out

**# Cannot describe list_crew_booking. It has 0 columns.**

Why this is happened? and how to solve this? i have no clue whats going on.

_ps: the view have 5000 rows and many columns_

Thank you for any reply

as seen on: http://stackoverflow.com/questions/36127120/error-when-fetching-mssql-database-view-data-cakephp-3

 _Using 
CakePHP Version: 3.2.5
PHP 5.5 >_

**Comment by lorenzo** [comment]
I think the code for SQL server in cake 3 does not support Views currently. Maybe if you have knowledge of sql server you can take a look and make it work?

**Comment by markstory** [comment]
This pull request #7846 half implemented view support for SQLServer. However, it did not include tests and thus wasn't merged.

**Comment by markstory** [comment]
Views can now be reflected by cakephp/bake as of d45f6a62b629d322f23a2238c3aa809b2f0ebdee
