### ISSUE TITLE
AuthComponent isAuthorized is too late.

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/cakephp#8506]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2
- Platform and Target: not relevant
### What you did

Used Authentication
### Expected Behavior

I hoped it would be easier to control access to logged in users as well as public or guest access. 
### Actual Behavior

You cannot control guest access because Auth only works for logged in users.  I know the solution is to go into each controller and add allowedActions(['index', 'view']) etc.  (or something like that), but this makes for a very disjointed access system if you have a large number of controllers and/or would like to turn these on or off via a user interface of some kind.  (some permissions are in controllers, some are in the database or in a file like permissions.php - if you're using cakedc/users)

Why shouldn't guest access be controlled in a single location?  If isAuthorized could fire before a user session existed it would allow cakephp to have a much more cohesive access system, that could be controlled much easier and more consistently. 

I did a work around for this in Cakephp 2 which required making a fake user role, in the aros table, but it takes a lot of code and I probably some additional unnecessary overhead.  This screen shot of the system I built on Cakephp 2 might give you a good visualization of something that would be way easier if guests were accounted for in the AuthComponent : https://www.evernote.com/shard/s13/sh/1abf7c3b-6634-4b5c-bdf2-ab393dd08014/20d703025cb3db8c62274fabf4bf2b1e

**Comment by jadb** [comment]
So you'd like to have guests be a faked logged in user that can be returned by `$this->Auth->user()`?

**Comment by markstory** [comment]
And change it so that unauthenticated users go through the `isAuthorized()` method calls.

**Comment by CodeBlastr** [comment]
So... I submitted a pull request to the CakeDC/Users plugin to show how it could be altered in order to control guest/public access in a cohesive single point of access definitions. It turns out to be significantly easier than it was in CakePHP 2 (or maybe I just found a better way this time), but regardless you can check out the pull request here and see if its simple enough to not be part of the core, or if the idea of a single place to access permissions is useful enough to make it part of the core : https://github.com/CakeDC/users/pull/339/files

**Comment by dereuromark** [comment]
@markstory What do you think? closing here as works-for-me - or looking into the issue as part of a 3.next feature? I think it might be a bit out of scope, and could be implemented in plugin/app code.

**Comment by markstory** [comment]
Going to close as AuthComponent is being replaced by the cakephp/authorization plugin which will let people move their checks where they need them.
