### ISSUE TITLE
CakePHP 3.x: how to write validation rule in controller?

### ISSUE THREAD

**Issue by designskiller** [cakephp/cakephp#8507]
I cannot figure out how write a validation rule in my controller in CakePHP 3.0 when i do this earlier in cakePHP 2.5.

My case: I have 2 field "care_call" and "number_of_calls" i want to write validation rule on "number_of_calls" when "care_call" field is checked.

How to change the validation rule only for one action?

Thanks

**Comment by lorenzo** [comment]
Please join us in the slack channel here http://cakesf.herokuapp.com or in the #cakephp IRC channel in freenode.net where we can guide you.

This is an issue tracker and not a help forum :)

**Comment by designskiller** [comment]
Ok Thanks.
