### ISSUE TITLE
NumberHelper::currency option 'precision' is ignored

### ISSUE THREAD

**Issue by paulrwest** [cakephp/cakephp#8508]
* [x] bug
* CakePHP Version: 3.2.5
* Platform and Target: Windows 10 running xampp PHP Version 5.6.8

### What you did
I want to show a currency value with 4 numbers after the decimal point we are using half/quarter pence units.

`echo Number::currency(0.0050, 'GBP', ['precision' => 4]);` 

### Expected Behavior
I was hoping to see 

> £0.0050 

### Actual Behavior
The precision option is being ignored and setting format to standard currency format 

> £0.00

The precision option is listed as a valid option 
[Number API](http://api.cakephp.org/3.2/class-Cake.I18n.Number.html#_currency)
I have tested with setting other options and using pattern '#.####' shows the correct value but then I lose the currency symbol. As soon as I include the currency symbol in pattern  '¤#.####' it sets it to 2 decimal numbers.

**Comment by chinpei215** [comment]
I think you would need to specify the locale. Otherwise, intl doesn't work as expected.

```php
ini_set('intl.default_locale', 'en_GB');

echo $this->Number->currency(0.0050, 'GBP', ['precision' => 4]);
// £0.005
```
or
```php
echo $this->Number->currency(0.0050, 'GBP', ['precision' => 4, 'locale' => 'en_GB']);
// £0.005
```

**Comment by paulrwest** [comment]
Setting locale does indeed fix the format. thank you @chinpei215

**Comment by dereuromark** [comment]
This should also be addressed properly IMO.

**Comment by chinpei215** [comment]
Sorry, @paulrwest. I have never used `CakeNumber::currency()` in 2.x. This might be defect or at least should be documented.

**Comment by chinpei215** [comment]
@dereuromark By the way, I think it is not necessary to reopen though. Both issues are the same. It would be fixed at the same time.
