### ISSUE TITLE
DateTime validation loses time data

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/cakephp#8509]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: IIS / Windows Azure hosting, SQL Server (Azure)

### What you did
I'm using a datetimepicker widget to save a date & time to an entity with a DATETIME column. The widget formats the date as `m/d/Y h:i A` and the Table converts this to a Cake\i18n\Time object during the beforeMarshal() callback. 

### Expected Behavior
The time and date should be saved correctly to the database.

### Actual Behavior
The date is validating and saving, but the time is lost between beforeRules() and afterRules() on my DateReceived column. I included DateDue as well, which is validating/saving the date just fine.

This time data is also being lost whether or not the validator is enabled for the field.

### Code
	// Snippet of validation rules
	public function validationDefault(Validator $validator)
	{
		$validator->add('DateReceived', 'valid', ['rule' => 'datetime']); 
		$validator->add('DateDue', 'valid', ['rule' => 'date']);
	}

	/**
	 * Logic to execute before converting to entity
	 */
	public function beforeMarshal(Event $event, $data, $options)
	{
		// Parse Date Received
		if (!empty($data['DateReceived']) && is_string($data['DateReceived'])) {
			$data['DateReceived'] = Time::createFromFormat('m/d/Y h:i A', $data['DateReceived']);
		}

		// Parse Date Due
		if (!empty($data['DateDue']) && is_string($data['DateDue'])) {
			$data['DateDue'] = Time::createFromFormat('m/d/Y', $data['DateDue']);
		}
	}

	/**
	 * Before Validation Rules
	 */
	public function beforeRules(Event $event, Entity $entity, $options, $operation)
	{	
		// Has correct datetime format
		pr($entity->DateReceived);

		/* Output:
		Cake\I18n\Time Object
		(
		    [time] => 2016-03-21T14:03:00-04:00
		    [timezone] => America/Detroit
		    [fixedNowTime] => 
		)
		*/		
	}

	/**
	 * After Validation Rules
	 */
	public function afterRules(Event $event, Entity $entity, $options, $result, $operation)
	{	
		// Has date, but time is missing
		pr($entity->DateReceived);
		
		/* Output:
		Cake\I18n\Time Object
		(
		    [time] => 2016-03-21T00:00:00-04:00
		    [timezone] => America/Detroit
		    [fixedNowTime] => 
		)
		*/
	}

**Comment by lorenzo** [comment]
Can you try doing ``Type::build('datetime')->useImmutable()` in your boostrap.php? I suspect that there is somewhere in your app that you are modifying your date without knowing

**Comment by kyleweishaupt** [comment]
@lorenzo I just added that to my bootstrap file but I'm still having the same issue.

**Comment by markstory** [comment]
Does your application have any rules that effect these fields?

**Comment by kyleweishaupt** [comment]
@markstory It looks like I overlooked an application rule where I was comparing this to another field. The validation worked, but was causing the time to not save correctly in recent Cake version updates.

Here is the original validation code if it helps:

	$dateDueValidation = function($entity) {
		$dateReceived = clone $entity->DateReceived;
		$dateReceived->modify('today midnight');
		return $entity->DateDue->toUnixString() >= $dateReceived->toUnixString();
	};
	$rules->add($dateDueValidation, [
		'errorField' => 'DateDue',
		'message' => 'Date Due must be after Date Received.'
	]);

And here is what I'm using now in the entity:

    public function isDateDueValid()
    {
        return $this->_properties['DateDue']->toUnixString() > $this->_properties['DateReceived']->toUnixString(); 
    }

**Comment by markstory** [comment]
With immutable objects. that `modify()` call needs to be `$dateReceived = $dateReceived->modify('today midnight');` instead.

**Comment by kyleweishaupt** [comment]
The `$dateReceived` variable was just for comparing the time against the other time, `DateDue`. I did not mean for it to modify the entity - only to compare the DateReceived DATETIME as greater than the DateDue DATE. I just thought it was odd that everything worked except saving the time after validation.

**Comment by lorenzo** [comment]
Did you find the issue?

**Comment by kyleweishaupt** [comment]
Yes - even cloning the entity to calculate a date difference is causing the date to change and validation to lose the time.
