### ISSUE TITLE
BelongsToMany replaceLinks method does not alias foreign_key

### ISSUE THREAD

**Issue by mirorac** [cakephp/cakephp#8510]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5

### What you did
I have junction table with `foreign_key` table and this table is also using translate behavior. I cannot save any changes, because replaceLinks does not alias field - leads to ambigious column name.

### Expected Behavior
generate
```sql
where Alias.columnName
```
### Actual Behavior
generating
```sql
where columnName
```

### Fix
add this to Association/BelongsToMany.php:985
```php
$foreignKey = (array)$this->_junctionTable->aliasField($this->foreignKey());
```

**Comment by lorenzo** [comment]
Do you want to submit a pull request for this?

**Comment by markstory** [comment]
Pull request up now.
