### ISSUE TITLE
Europe/Moscow TZ has an incorrect time offset

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#8512]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Platform and Target: linux 3.16.0, nginx & php5.6-fpm

### What you did
```php
// in bootstrap.php
define('APP_TIMEZONE', 'Europe/Moscow');
```

```php
// in template file
echo $inquiry->created->timezone(APP_TIMEZONE);
echo $inquiry->created->timezone(APP_TIMEZONE)->format('d.m.y, G:i');
```
### Expected Behavior
```php
// 23.03.16, 4:19
// 23.03.16, 4:19
```
### Actual Behavior
```php
// 23.03.16, 5:19
// 23.03.16, 4:19
```

I think it's a little strange - output of the time object without `format` method called has an advance for a hour.

**Comment by markstory** [comment]
Do you have similar issues with other timezones or is this issue specific to Europe/Moscow?

**Comment by markstory** [comment]
I wasn't able to reproduce this in an interactive console session, but I might be missing something:

```php
$ bin/cake console

Welcome to CakePHP v3.2.5 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.5.33
---------------------------------------------------------------
You can exit with `CTRL-C` or `exit`

Psy Shell v0.7.2 (PHP 5.5.33 — cli) by Justin Hileman
>>> $dt = new \Cake\I18n\Time('2016-03-23 05:19:00');
=> Cake\I18n\Time {#202
     +"time": "2016-03-23T05:19:00+00:00",
     +"timezone": "UTC",
     +"fixedNowTime": false,
   }
>>> echo $dt->timezone('Europe/Moscow');
2016-03-23, 8:19 AM⏎
=> null
>>> echo $dt->timezone('Europe/Moscow')->format('d.m.y, G:i');
23.03.16, 8:19⏎
=> null
```

**Comment by ADmad** [comment]
@markstory Isn't the "problem" due to the fact that `$inquiry->created` is immutable?

**Comment by markstory** [comment]
Could be. But the original issue was using chained method calls which should be compatible with immutable objects.

**Comment by codercms** [comment]
@markstory yes, i have the same issue with Europe/Kaliningrad. Europe/Berlin and Europe/Samara are works fine.

**Comment by codercms** [comment]
@markstory i found one more strange issue.
```php
// in bootstrap.php
define('APP_TIMEZONE', 'GMT+03');
```

```php
// in template file
echo $inquiry->created->timezone(APP_TIMEZONE);
echo $inquiry->created->timezone(APP_TIMEZONE)->format('d.m.y, G:i');
```
Output is:
```php
// 23.03.16, 7:19
// 23.03.16, 4:19
```

**Comment by markstory** [comment]
I'm not really sure how to reproduce the issues you're having. For each of those timezones I get different results. You might need to update your timezone database.

**Comment by codercms** [comment]
@markstory I will check it on Linux 4.2 & PHP 7

**Comment by antograssiot** [comment]
@codercms what's the result of ``php --ri intl``
reminds me #6398

**Comment by codercms** [comment]
@antograssiot the result is:
```
coder@dev:~$ php --ri intl

intl

Internationalization support => enabled
version => 1.1.0
ICU version => 52.1
ICU Data version => 52.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0

```

**Comment by codercms** [comment]
@markstory The problem is solved.
The soultion is:
Installed latest ICU by this guide - http://www.linuxfromscratch.org/blfs/view/svn/general/icu.html
Installed latest PHP intl extension - `pecl install intl`

```
intl

Internationalization support => enabled
version => PECL-3.0.0
ICU version => 56.1
ICU Data version => 56.1
```

Thank you, @antograssiot.
