### ISSUE TITLE
mysql  Allowed memory exhausted on find All -( please try to use php generator )

### ISSUE THREAD

**Issue by zamaliphe** [cakephp/cakephp#8514]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5.
* Platform and Target: php ver 7 ,mysql database 5.7 ,apache 2.4.

##references 
http://php.net/manual/en/language.generators.overview.php
http://php.net/manual/en/class.generator.php

### What you did
run a find all query on large table 

### Expected Behavior
i expect to mysql query to run without eating up all php memory resource 
 Allowed memory size of 268435456 bytes exhausted
256 MB of ram is not enough to run this 

 
![cakephp _bug_ 2016-03-23 11-56-07-2](https://cloud.githubusercontent.com/assets/671318/13981742/99abaae4-f0ee-11e5-9003-307c2bc31858.png)

![cakephp _bug_ 2016-03-23 11-56-07](https://cloud.githubusercontent.com/assets/671318/13981749/ac15e636-f0ee-11e5-8053-de9d36ebc7b7.png)

**Comment by dereuromark** [comment]
If it is a large table what do you expect to do with a find(all) result? What is your intention as you sure don't want to process them all, do you?
Usually you would get them paginated in some loop and process them as batch data but not all at once.

**Comment by zamaliphe** [comment]
correct but i left  a reference to use  the php generator  so why don't we do some test to see if that would make cake php faster or use less memory ?

**Comment by zamaliphe** [comment]
Usually when you get a large set you access it using for-each loop one record at / time which make since to use the new ( php generator )

**Comment by jippi** [comment]
@zamaliphe tried to `bufferResults(false)` ( http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#working-with-result-sets ) 

please share your actual code on how you do things so we can help debug

At Bownty we do select(all) on 100+GB tables without running out of memory just fine :)

**Comment by lorenzo** [comment]
Generators are already used, but the way PHP works by default is by loading ALL results in memory first. You can avoid that by calling `$query->bufferResults(false)`, this will make the results stream directly from the database one by one.

Please keep in mind that hasMany or belongsToMany associations cannot be loaded from the same connection when using `bufferResults(false)`.

**Comment by zamaliphe** [comment]
thanks for your comment @lorenzo  yes $query->bufferResults(false) fixed memory limit problem 
it would be nice to know how to load associations with it OR work around it ?

**Comment by lorenzo** [comment]
Yes, what I do is creating a second connection object, and the pass that to the associations like this:

```php
$connection = ConnectionManager::get('replica');
$table->MyHasMany->connection($connection);
$table->MyBelongsToMany->connection($connection);
```

There is no need to do tat for belongsTo nor hasOne associations

**Comment by ionas** [comment]
Without having tried another option is possibly `->innerJoinWith()` / `->leftJoinWith()` + `select()` @zamaliphe as those calls should keep it one query (as belongsTo and HasOne do). You can either distinct/groupby in SQL or later in PHP.
