### ISSUE TITLE
Setters not working for title cased columns

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/cakephp#8516]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: IIS / Azure Web Server, SQL Server (Azure)
* Similar Issues: #8504, #8246 

### What you did
I have inherited a large database with existing column names that are title cased. The User table has fields such as UserId, Email, Password, PhoneNumber, Admin, etc. I wish they adhered to Cake's conventions but they don't.

After updating to the Cake 3.2 branch and having issues with virtual properties, I cannot get the password hashing setter to work correctly. After some testing, I noticed the setter method does not work with a capitalized field name. This did work in the 3.1 branch.

### Expected Behavior
`$user->Password = 'test';` should fire off the `_setPassword($password)` function in the User entity.

### Actual Behavior
`$user->password = 'test';` works correctly with `_setPassword()`, but it does not work with `$user->Password = 'test';`. 

### Code
Controller:

	public function changePassword()
	{
		$user = $this->Users->get(
			$this->Auth->user('UserId'),
			[
				'fields' => [
					'UserId',
					'Email'
				]
			]
		);

		$user->Password = 'TitleCased';
		$user->password = 'lowercase';

		// save, etc...
	}

Entity:

	protected function _setPassword($password)
	{
		die('Password: ' . $password);

		return (new DefaultPasswordHasher)->hash($password);
	}

Output:

    Password: lowercase

**Comment by dakota** [comment]
This is a definite bug in the core.

@lorenzo, should we treat the `Name` and `name` properties as two separate properties (Using the same accessor/mutator), or would we want them to behave internally as a single property? As it is now, `camelCase` and `camel_case` would behave as two separate properties, but run the same accessor/mutator method. I guess for BC we need to keep the current behaviour?

**Comment by markstory** [comment]
@dakota I think they should be separate properties. We can't make different accessor methods though as PHP method names are case-insensitive.

**Comment by markstory** [comment]
I'll take a look as I fixed a similar issue in virtual fields.

**Comment by markstory** [comment]
#8247 Was the pull request to update camelBacked virtual fields.

**Comment by dakota** [comment]
I've got a fix already :) Will open a PR in a moment

**Comment by markstory** [comment]
@dakota Awesome!

**Comment by dakota** [comment]
PR up, closing.
