### ISSUE TITLE
EntityContext modifies ResultSet data

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#8519]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: 7.0.4-6+deb.sury.org~trusty+5, MySQL 5.6.28, Ubuntu 14.04, Apache 2.4.18

### What you did

```php
// Controller
function batchEdit()
{
    $users = $this->Users->find();
    $this->set(compact('users'));
}

// batch_edit.ctp
<?php
echo $this->Form->create($users);

foreach ($users as $user) :
?>
<div class="edit-user-info">
    // Form stuff here...
</div>
<?php
endforeach;

echo $this->Form->submit();
echo $this->Form->end();
```

### Expected Behavior
Loop through all user records and display a form for each user using the default validation rules.

### Actual Behavior
According to the [docblock](https://github.com/cakephp/cakephp/blob/master/src%2FView%2FHelper%2FFormHelper.php#L331) you can use a ResultSet to create a form. All works great except when it hits that `foreach` block. Only one iteration of that loop is done. No errors or anything.

The reason for this can be traced to this line: https://github.com/cakephp/cakephp/blob/master/src%2FView%2FForm%2FEntityContext.php#L123

The actual query object is being modified before the loop begins which means that only one record will ever be displayed. This was confirmed with:

```php
$testClone = clone $users;
echo $this->Form->create($testClone);
```

The `EntityContext` just needs to be able to inspect the query object instead of modifying it.

**Comment by markstory** [comment]
It looks like the issue here is that in getting the first result to do schema inspection the query is executed and a `LIMIT 1` is applied to the query. Have you tried calling `$query->all()` and passing the ResultSet to the view instead of the Query?

I don't think we'll be able to clone the query, as that will result in SQL executing twice. We might be able to fetch all the results into the query before making the collection, but that will have issues with unbuffered queries. I'm not sure those are frequently used with forms though.

**Comment by sdustinh** [comment]
I get the same results with `$query->all()`. I guess a potential way to get it would be with `$query->repository()` but on a `Cake\ORM\ResultSet` you'd need to open up that `_defaultTable` property to make it work. Just to be complete I also tried `$this->Form->create($users, ['context' => ['table' => 'Users']]);` which didn't work either.

**Comment by lorenzo** [comment]
Can you try this?

```php
echo $this->Form->create($users->all());
```

**Comment by sdustinh** [comment]
@lorenzo Just tried it. Same problem.

**Comment by lorenzo** [comment]
I understand, the problem is that this piece of code is too optimistic:

https://github.com/cakephp/cakephp/blob/master/src/ORM/ResultSet.php#L288-L296

**Comment by markstory** [comment]
I bet `$query->toArray()` works fine because it will unwind the underlying iterators. I don't think that is a reasonable thing for developers to have to do though.
