### ISSUE TITLE
Cells inside subdirectory

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#8520]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: Apache 2, PostgreSQL 9.4

### What you did
I tried to use cells withing subdirectory, e.g. `src/View/Cell/Admin/AdminMenuCell.php` and call `<?= $this->cell('Admin/AdminMenu') ?>` inside of the view file.

The display file is: `src/Template/Cell/Admin/AdminMenu/display.ctp`

### Expected Behavior
It should load the cell.

### Actual Behavior
The error says `Could not render cell - Cell view file "display" is missing. [CORE/src/View/Cell.php, line 264`.

I would say an issue within in these lines: https://github.com/cakephp/cakephp/blob/master/src/View/Cell.php#L207

Currently it expects the display file to be in `src/Template/Cell/AdminMenu/display.ctp`

**Comment by thinkingmedia** [comment]
`$this->cell('Admin/AdminMenu')` is not a valid cell name.

You are assuming that cells are named the same way as elements, but they are classes and follow Cake's naming convention for `plugin.classname` patterns.

Someone correct me if I'm wrong.

**Comment by markstory** [comment]
@Laykou Is your Cell in the `App\View\Cell\Admin` namespace? Looking at how the [template paths are generated](https://github.com/cakephp/cakephp/blob/master/src/View/Cell.php#L204-L208) it won't handle sub-namespaced cells. Until this issue is fixed you can always set the templatePath manually:

```php
// In the cell action
$this->viewBuilder()->templatePath('Cell/Admin/AdminMenu');
```

**Comment by Laykou** [comment]
@markstory Yes, my namespace is `App\View\Cell\Admin`. Btw I needed to manually adjust it, because when calling `cake bake cell Admin/AdminMenu` it created class `Admin/AdminMenu` under namespace `App\View\Cell` which is obviously not a valid syntax.

Maybe that can be fixed too. It would be nice to have cells in sub-namespaces because elements work that way too.

**Comment by ADmad** [comment]
Using `Prefix/Name` style doesn't work for generating any class type except when generating plugins. Have you instead tried using option `--prefix Admin` when baking the cell?

**Comment by markstory** [comment]
Pull request up #8541
