### ISSUE TITLE
3.2: Wrong timezone

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8529]
My `bootstrap.php`:

    date_default_timezone_set('UTC');

My `php.ini`:

    date.timezone = Europe/Rome

So I expect that will be used UTC as timezone.  
Now I create a post. The "created" field is left blank.

    debug($post->created);
    debug($post->modified);
    
    if($this->Posts->save($post)) {
        debug($post->created);
        debug($post->modified);
    }

Output:

    null
    null
    object(Cake\I18n\Time) {
        
        'time' => '2016-03-24T17:25:43+01:00',
        'timezone' => 'Europe/Rome',
        'fixedNowTime' => false

    }
    object(Cake\I18n\Time) {

        'time' => '2016-03-24T17:25:43+01:00',
        'timezone' => 'Europe/Rome',
        'fixedNowTime' => false

    }

It's adds the timezone "Europe/Rome".

Now I get the same post. Debug for `$post->created`:

    object(Cake\I18n\FrozenTime) {

        'time' => '2016-03-24T17:25:43+00:00',
        'timezone' => 'UTC',
        'fixedNowTime' => false

    }

Other debug:

    debug(new \Cake\I18n\Time());
    debug(new \Cake\I18n\FrozenTime());

Output:

    object(Cake\I18n\Time) {

        'time' => '2016-03-24T17:32:12+01:00',
        'timezone' => 'Europe/Rome',
        'fixedNowTime' => false

    }
    object(Cake\I18n\FrozenTime) {

        'time' => '2016-03-24T17:32:12+01:00',
        'timezone' => 'Europe/Rome',
        'fixedNowTime' => false

    }

What's interesting:

    debug($post->created->isFuture());

is `TRUE`!

This obviously happens because the current date is in UTC, while the date of the post is +1.

Am I wrong in something? Why does this happen?

**Comment by lorenzo** [comment]
That's odd, according to this http://php.net/manual/en/function.date-default-timezone-get.php the date.timezone should not affect anything if you call `date_default_timezone_set`

**Comment by mirko-pagliai** [comment]
Yes, I reported for this reason. Can I do some other proof?

**Comment by lorenzo** [comment]
No, I will need to test this by myself first and report back :)

**Comment by mirko-pagliai** [comment]
Let me know. For now the only solution I found for me is to match bootstrap and ini.

**Comment by markstory** [comment]
Does changing the ini value at runtime with ini_set() fix your issue?

**Comment by mirko-pagliai** [comment]
I think this is more interesting. In the same action method:


        debug(date_default_timezone_get());
        date_default_timezone_set('UTC');
        debug(date_default_timezone_get());
        debug(new \Cake\I18n\Time());

Output:

'Europe/Rome'
'UTC'
object(Cake\I18n\Time) {

	'time' => '2016-03-25T10:40:07+00:00',
	'timezone' => 'UTC',
	'fixedNowTime' => false

}

So `date_default_timezone_set()` seems it works.

It seems as from bootstrap to action something changes the time zone again, using the INI value.

This doesn't work:

        debug(date_default_timezone_get());
        ini_set('date.timezone', 'UTC');
        debug(date_default_timezone_get());
        debug(new \Cake\I18n\Time());

Output:

        'Europe/Rome'
        'Europe/Rome'
        object(Cake\I18n\Time) {

	        'time' => '2016-03-25T11:45:24+01:00',
	        'timezone' => 'Europe/Rome',
        	'fixedNowTime' => false

        }

**Comment by markstory** [comment]
Well there are 0 calls to `date_default_timezone_set` in CakePHP.

```
$ ack 'date_default_timezone_set' src/
:( 09:54:12 markstory:cake3 (issue-8520)
$
```

Check your plugins and application code.

**Comment by mirko-pagliai** [comment]
Yes, I'm wrong. A plugin called `date_default_timezone_set`. Sorry.
