### ISSUE TITLE
Empty time fields 

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#8530]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: Unrelated to the problem.

### What you did

In the template:

	echo $this->Form->input('end_time', ['empty' => '---']);

Submit the form with the time left empty (a valid choice, indicating no specific end time) but errors in other fields.

### Expected Behavior

The end_time fields will still be empty.

### Actual Behavior

The end times will be shown as 12 --- pm.

### Cause

The `_deconstructDate` function in `DateTimeWidget` is not correctly accounting for this situation, adding a default meridian of "pm" and adding 12 to the hour if it's not "am" instead of if it is "pm".

**Comment by Zuluru** [comment]
I'm trying to come up with a patch to fix it, but I will want to make sure that it passes all the unit tests (plus any new tests I need to add to catch this situation), and I'm getting a lot of failures on the tests even before making any code changes. Is that normal? I'm running PHP 5.6.19.

**Comment by markstory** [comment]
No the test suites should all pass.

**Comment by Zuluru** [comment]
Should I open a separate issue for that, then?

**Comment by markstory** [comment]
No. The tests pass for me, and on travis-ci. Them failing is indicative of an issue with your setup.

**Comment by Zuluru** [comment]
Makes sense. I'll post that on StackExchange instead.

**Comment by markstory** [comment]
Pull request up.
