### ISSUE TITLE
Creating Model.TableAlias.afterSave instead of Model.afterSave

### ISSUE THREAD

**Issue by akkaweb** [cakephp/cakephp#8531]
This is a:
* [x] enhancement
* [x] CakePHP Version: 3.x

### What you did
I was trying to create code that listens to an `afterSave` event from a plugin that did not implement it. After trying different things, the only thing I could do was to create a Listener that listened to `Model.afterSave` event. The application I am trying this on is small, however, it could be expensive if the application was a bit bigger with many Saves.

### Expected Behavior
Beneficial specially when targetting plugin Models from within your own application

If CakePHP could create those events by default from within Core (Table.php), I think it would be helpful and would allow anyone to hook into a plugin's afterSave even when it is not implemented from within the plugin. It would also speed up development. I made the following change to within a forked version of  `cakephp\src\ORM\Table.php` to test it out and it actually works:

    protected function _processSave($entity, $options)
    {
        // a bunch of code omitted here.... to line 1473
        $this->dispatchEvent("Model.{$this->alias()}.afterSave", compact('entity', 'options'));
        // So this would translated into something like this Model.Users.afterSave
        // ....

Similar change would also be needed to other events like `Model.beforeSave` as well as View and Controller events.

**Comment by lorenzo** [comment]
An easy way is:

```php
TableRegistery::get('TheTable')->on($myListener)
```

**Comment by akkaweb** [comment]
@lorenzo This gives me "Unknown method 'on'". Also, I am not sure I follow how I can catch non-created events without the proposed change. Thanks!

**Comment by akkaweb** [comment]
Let's say I am using a plugin that saves Comments. Currently I can listen on `Model.afterSave`, with an If statement I will be able to get to the `afterSave` for Comments. However, I would have to list to all 'afterSave` fired by Model on any other table. Basically I just want to listen to Model.Comments.afterSave` when that event is not created within the Plugin

**Comment by lorenzo** [comment]
oops, sorry... wrong code. Here it comes again:

```php
TableRegistery::get('TheTable')->eventManager()->on($myListener)
```

**Comment by markstory** [comment]
I'm not clear on the use cases for this that aren't covered by local event managers.

**Comment by akkaweb** [comment]
@lorenzo I cannot get that to work for me. @markstory Perhaps I am either not explaining what I am looking to do correctly or I am getting it all wrong. 

Let's say you create a plugin, we can call it Feedbacks. You did not set it up with any events at all. I come along and I want to use your plugin in my application, but I want to know when a Feedback is added using the plugin so I can create a notification in my admin backend. How would you go about detecting this save, on what events is concerned?

**Comment by markstory** [comment]
I would bind events to the table classes.

```php
// Somewhere before the save happens.
TableRegistry::get('Feedbacks.Feedback')->eventManager()->on('Model.afterSave', function($event) {
  // Do something here.
});
```

**Comment by jhli** [comment]
I can't chrck right now, but if above example is not in the book, it should be (can prep PR, just say so).

**Comment by akkaweb** [comment]
This works great! @markstory and @lorenzo thanks so much for the help with it. I did not know about this possibility. This request can be closed and next time I will reach out before creating a request.

@jhli I agree that this example should be in the book. It would be great for new developers learning about CakePHP events.

**Comment by lorenzo** [comment]
Would you like to send a pill request to the docs with your example?

**Comment by akkaweb** [comment]
@lorenzo I can! I will do that this afternoon. Thanks

**Comment by akkaweb** [comment]
@lorenzo FYI, I submitted a patch the DOCS with my example. This is the first time contributing to the DOCS, so forgive me if not correctly done. I can make any updates if required. [#3863](https://github.com/cakephp/docs/pull/3863)

**Comment by markstory** [comment]
Thanks for updating the docs :+1:

**Comment by akkaweb** [comment]
No problem at all! Many thanks from me for such a great framework!
