### ISSUE TITLE
MySQL *TEXT column type

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/cakephp#8532]
When building a MySQL table with type ``TINYTEXT``, ``MEDIUMTEXT`` or ``LONGTEXT``, the schema description ends up reflecting the column as being of type ``TEXT``.

Which means that if you call a ``Collection::describe()`` then call a ``Table::createSql()`` with the resulting ``Table`` object, the column is reflected as ``TEXT`` and not the real value of the db.

This causes trouble in the migrations plugin where a column of type ``LONGTEXT`` is reflected as being ``TEXT`` which is unexpected : https://github.com/cakephp/migrations/issues/211

I can provide a fix for this but I'd like to know if there are any particular reasons for this to be implemented that way ? Problem is that it could bring breakage in apps if there are expecting that behaviour.

**Comment by lorenzo** [comment]
I think it is only historical reasons

**Comment by markstory** [comment]
We could add more abstract types. We'd have to handle the new types in all the vendors that don't support length based types.

**Comment by HavokInspiration** [comment]
I started implementing this for ``*text`` types, it seems to be working quite well as long as conversions for other db vendors are done (I just converted it to the same as ``text``).
Tests seems to run without problems (did not run the full testsuite though).

I'll try to submit a PR soon. From here, we'll be able to add something similar for ``*blob`` and ``*int`` types.

**Comment by markstory** [comment]
@HavokInspiration Awesome!

**Comment by thinkingmedia** [comment]
I happen across this in the Phinx documentation. It already supports this for MySQL.

http://docs.phinx.org/en/latest/migrations.html#limit-option-and-mysql

So why doesn't this do what is discussed here?

**Comment by markstory** [comment]
@thinkingmedia This is different because the migrations plugin uses CakePHP's schema reflection to generate new migrations, and that reflection process loses the length information.

**Comment by HavokInspiration** [comment]
PR #8543 closed.
