### ISSUE TITLE
Add new method Collection::compact that will filter collection.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8535]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5

### What you did

Created a filter that will remove empty values from the collection.

```
        $arr = collection([0, 1, false, "", 3])->filter(function ($value) {
            return !empty($value);
        });
        pr($arr->toArray());
```
The above outputs `[1,3]`.

Would be nice to simplify this to nothing more then.

```
        $arr = collection([0, 1, false, "", 3])->compact();
        pr($arr->toArray());
```

The benefits are shorter function chains and readability. The `compact` method exists in `lodash` and `underscore` which uses the JavaScript falsey compare. In PHP we would use the `empty()` compare.

**Comment by lorenzo** [comment]
I think that's exactly what filter() with no arguments does

**Comment by thinkingmedia** [comment]
@lorenzo cool, if that's the case I'll update the docs.
