### ISSUE TITLE
CakePHP 3.1 CLI should not require php 5.5

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#8538]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.12.
* Platform and Target: Ubuntu 15.10 & PHP 5.6.11 and CentOS 6.6 & PHP-CLI 5.4.42.

### What you did
Created a blank project via composer `php composer.phar create-project --prefer-dist cakephp/app my_app_name`
Downgraded cakephp 3.2 to 3.1.12 via modifying composer.json and running `composer update`
Then uploaded the app to a CentOS host.
Run a CakePHP 3.1.12 Cli on php 5.4.
`$ ./bin/cake`

### Expected Behavior
Console works as expected

### Actual Behavior
CakePHP's console refuses to launch. It prints the following:
`Minimum PHP version: 5.5.9. You are using: 5.4.42.`

As stated on composer.json of CakePHP 3.1.12 it's minimum required version is 5.4.16. While Cli-tool requires PHP 5.5+.

**Comment by markstory** [comment]
That error is coming from your app/bootstrap.php file. Delete the code emitting that error. This is not something that CakePHP or composer can do you for you.
