### ISSUE TITLE
Override HttpException Class

### ISSUE THREAD

**Issue by mdemblani** [cakephp/cakephp#8544]
I am unable to override HttpException class, using the App::uses functionality. The sole purpose of overriding the class, is to enable the support of passing an array to the exception which can then be rendered in the view. 
An alternate way is to write the extended code in the library itself, but that would cause a lot  of problems when updating the library.

**Comment by lorenzo** [comment]
This is not possible in cake 2, as all the exceptions are declared in a single file

**Comment by mdemblani** [comment]
OK, Thank You.
