### ISSUE TITLE
Include reason for 'blackholing' in SecurityComponent's default exception

### ISSUE THREAD

**Issue by dvlprs** [cakephp/cakephp#8545]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7, 2.next
* Platform and Target: irrelevant

### What you did
Enabled the Security component. 

### Actual Behavior
As per https://github.com/cakephp/cakephp/blob/2.next/lib/Cake/Controller/Component/SecurityComponent.php#L336, it just shows "The request has been black-holed" error message, which is too broad. While most likely, the reason note is accessible in that scope, it's in the `$error` variable.

### Expected Behavior
When available, knowing why exactly the request was blackholed would help

**Comment by lorenzo** [comment]
This was implemented in cake 3, maybe you want to help backport this feature?

**Comment by dvlprs** [comment]
Thank you for your fast response. I'm willing to submit the code I came up with, but I currently don't have git on my PC. Will need some time to get it set up. I'll update this ticket.
