### ISSUE TITLE
4.x: Log::write() and Log::debug() etc. should be chainable like debug() now is.

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8551]
This is a (multiple allowed):
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.4
### What you did

In https://github.com/cakephp/cakephp/pull/8534 `debug()`, `pr()` and `pj()` got changed to return their given `$val` thus that they can be 'chained' like return `debug($data);`
However while frontend debugging is convenient it messes with the output buffer which can be especially an issue when returning non html like json/xml etc.
### Expected Behavior

`Log::write()` could come to the rescue but should behave the same like the updated `debug()`.
Ref: http://book.cakephp.org/3.0/en/core-libraries/logging.html#Cake\Log\Log::write
As well as : http://book.cakephp.org/3.0/en/core-libraries/logging.html#convenience-methods
Ref: http://api.cakephp.org/3.2/source-class-Cake.Log.Log.html#304-399

However it returns true/false at the moment:
http://api.cakephp.org/3.2/source-class-Cake.Log.Log.html#355

Logger should use exceptions if logs could not be written?

**Note**: If desired, this is probably a non-BC "4.x" change - right?

Benefit would be that you could and are encouraged to use `Log::debug()` instead of `debug()` to not pollute your output buffer. You could also fire off warnings and notices "chained".

**Comment by thinkingmedia** [comment]
This would be good improvement. I admit that I have xdebug setup with PhpStorm but I'm still guilty of doing this all the time.

```
    $record = $this->Documents->get($id);
    pr($record);die;
```

Simply because it's faster.

With this change I suspect that the following would be possible.

```
    $record = Log::debug($this->Documents->get($id));
```

That wouldn't break anything and the log output would appear in DebugKit.

I don't know if you can log objects/array but that's a different issue.

**Comment by markstory** [comment]
> I don't know if you can log objects/array but that's a different issue.

Not unless that object implements `__toString()`.

**Comment by dereuromark** [comment]
This is quite old - I guess we can close?
