### ISSUE TITLE
Maximum execution time exceeded - find all execute

### ISSUE THREAD

**Issue by davo3** [cakephp/cakephp#8552]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5.
* Platform and Target: Debian 8.3,  Apache/2.4.10, PHP 5.6.17, Mysql  5.6.26, PHP memory limit - 512 MB

### What you did
Cakephp fresh installation, one table `articles`(just id, title and created fields) - with just one row of data, standard baked controller, model and templates. Have the following code in the index action
```
$articles = $this->Articles->find('all')->execute();
debug($articles);die;
```

### Expected Behavior
I expect to get the object for the list of articles (in this case one article only)

### Actual Behavior
Error: Maximum execution time of 30 seconds exceeded
File /home/tig/www/cake3/vendor/cakephp/cakephp/src/Error/Debugger.php
Line: 521 

Not sure if the problem has the same source, but I had similar issue in the past https://github.com/cakephp/cakephp/issues/7589

**Comment by markstory** [comment]
How can someone reproduce this issue? I'm not able to reproduce this given the current information.
