### ISSUE TITLE
Links to older versions of cookbook in subdomain websites of cakephp.org

### ISSUE THREAD

**Issue by MrSnoop** [cakephp/cakephp#8553]
This is a (multiple allowed):
* [x] bug

@  http://certification.cakephp.org/ &  http://my.cakephp.org/login : links in top navigation refer to old versions of cookbook ;)

**Comment by markstory** [comment]
The sites haven't been updated in a while. We'll have to figure that out soon :smile:

**Comment by markstory** [comment]
This issue was moved to cakephp/docs#3979
