### ISSUE TITLE
Find quick consultation with too much data

### ISSUE THREAD

**Issue by awilchesl** [cakephp/cakephp#8556]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5

### What you did
I want to make a report of all the information Posts example contains my table.

`$posts=$posts->find('all', ['contain'=>['Categories', 'FieldsPosts', 'Users']])->toArray();`

### Expected Behavior
Currently the database contains 300 Posts. when I make the find. 1. It takes too long to load and 2. if you have not enabled `memory_limit` 512M comes in the typical error `Allowed memory size` of cakephp

I worry when the platform has for example Posts 30.000. I like to run a report from the cakephp and not directly from MySql?

**Comment by thinkingmedia** [comment]
Either your post records contain a lot of data or the associations are very large. This isn't a bug with cake.

**Comment by ADmad** [comment]
There's nothing CakePHP can do if there's isn't enough memory to handle the data you are fetching.

You should either fetch large data sets in batching (i.e. use paging) or use [unbuffered queries](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#working-with-result-sets).

**Comment by ADmad** [comment]
For future reference please don't use the issues tracker for support questions. Use stackoverflow.com or #cakephp IRC channel or cakephp's slack channel.

**Comment by jhli** [comment]
If you still think it is a bug you should provide lots mite information such as a working stripped down copy of the issue. In general Admad is right, however :)
