### ISSUE TITLE
Custom database seeding

### ISSUE THREAD

**Issue by tolawho** [cakephp/cakephp#8559]
This is a (multiple allowed):
* [x] feature-discussion (RFC)

In `Laravel`, I easy seed database with any seeders and any order i want.
![screenshot_2](https://cloud.githubusercontent.com/assets/12527881/14103484/9f796d04-f5ca-11e5-9ecd-69b820c301d5.png)

But, `Cakephp ` will run all available seeders in the target directory and only support in alphabet order. That was inconvenient.

_Example _ In `Laravel`: I run `CitiesSeeder` after `CountriesSeeder ` because I need `country_id ` insert to `cities ` table. 
 
![screenshot_3](https://cloud.githubusercontent.com/assets/12527881/14103870/5178b1ee-f5cc-11e5-8ee1-c226c3066212.png)

**Comment by burzum** [comment]
Having seeds that can't rely or depend on each other makes them useless for some scenarios.

So :+1: from me.

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#212
