### ISSUE TITLE
Avoid entity cloning hasMany belongsToMany

### ISSUE THREAD

**Issue by pulse14** [cakephp/cakephp#8560]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: /

### What you did
```php
    public function testSaveHasManyWithErrorsAtomic()
    {
        $entity = new \Cake\ORM\Entity([
            'name' => 'Jose'
        ]);
        $entity->articles = [
            new \Cake\ORM\Entity([
                'title' => '1',
                'body' => 'A body'
            ]),
            new \Cake\ORM\Entity([
                'title' => 'Another Title',
                'body' => 'Another body'
            ])
        ];

        $table = TableRegistry::get('authors');
        $table->hasMany('articles');
        $table->save($entity);
    }
```

### Expected Behavior

Entities are cloned. When I instanciate an entity I expect to keep it, they are cloned without telling me and for no obvious reason. I think it's a bad practice since entities are objects and not wrapper for array.

If save don't fail we should keep the same instance by default or make an option.

**Comment by pulse14** [comment]
@markstory This is just an example of what I do. I edited it.

I know it because in hasMany and belongsToMany entities are cloned, and errors are set on the new object.

**Comment by markstory** [comment]
Ok. What problems does cloning the object cause?

> they are cloned without telling me ...

I admit that the documentation could explain that the entities will be cloned.

>  and for no obvious reason.

While it might not be obvious, the reason entities get cloned is that saving often requires the entities to be modified. If we are saving entities we need to assign the foreign key properties as the developer may have not done that. In order to keep the operation 'atomic' and be able to easily rollback the modified properties when saving fails we employ clones. You can disable/avoid this behavior my disabling the atomic option and manually managing transaction scope yourself.

**Comment by pulse14** [comment]
@markstory Cloning causes no problems when whe use patchEntity, etc... But when we manually create an entity as in my example, we expect to track it before and after the save. It's exactly what we do when we save one entity. We create the entity, we save it, and if on the same reference we check isNew, isnew changed. The key fact it's that is it on the same reference.

The main problem is that I think with this approach we use entities like we use arrays. It also makes entity behave differently depending how they are saved, and this is a real issue.

I understand the reasons but as you said it's mainly to keep the code simple, easily rollback. And not beacause there is a real reason, no ?

**Comment by lorenzo** [comment]
I can add an option to save for avoiding the cloning, if that helps

**Comment by pulse14** [comment]
@lorenzo it would be great. And it helps telling users that entities are cloned by default

**Comment by markstory** [comment]
> I understand the reasons but as you said it's mainly to keep the code simple, easily rollback. And not beacause there is a real reason, no ?

Being able to rollback changes safely and atomically *is* the reason for the cloning.

**Comment by markstory** [comment]
@lorenzo How would that option work with `atomic=true`? Instead of more options I would rather we try to do the required property rollbacks in place.

**Comment by lorenzo** [comment]
@markstory too difficult and not worth the time, imo, because you need to track more than just the properties in the entity, but also associations, custom fields in the class, etc.

**Comment by markstory** [comment]
Which is how we ended up using the clone in the first place.

**Comment by lorenzo** [comment]
Right... so I'm thinking that if it is so important for someone to sacrifice this rollback in exchange for preserving the entity reference, they might do the cloning themselves if needed

**Comment by markstory** [comment]
@lorenzo Which is why I suggested that @pulse14 do something like:

```php
$this->Articles->connection()->transactional(function ($conn) use ($article) {
  $this->Articles->save($article, ['atomic' => false ... ]);
});
```

Manually controlling the transaction boundary allows `atomic` to be disabled also disabling the cloning.

**Comment by lorenzo** [comment]
@markstory that has a different semantic, though. If any of the associations fail in the saving, it will still continue the save process

**Comment by lorenzo** [comment]
After some thought, I don't think adding the option is the right thing to do. Please create your own association class and make sure you manually override `atomic` and set it to `false` in the `saveAssociated` method.

This is a fix that would take you just a few lines, but that adding to the core would increase the complexity greatly.
