### ISSUE TITLE
Routing in 3.2.5 resulting in unexpected behavior (using plugin and prefix)

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8561]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5
* Platform and Target: apache 2.4, nginx, php 5.6

### What you did
```
Router::prefix('admin', function ($routes) {
		$routes->plugin('AclManage', function ($routes) {
			$routes->connect('/', ['controller' => 'AclManage', 'action' => 'index'], ['routeClass' => 'DashedRoute']);
			$routes->connect('/:controller/*', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
			$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
		});
	});
```

### Expected Behavior
I tried to use `/admin/acl_manage/controller/action`. It didn't work and always triggered the rule		`$routes->connect('/:controller/*', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`

When switching the rules and doing 
`$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
$routes->connect('/:controller/*', ['action' => 'index'], ['routeClass' => 'DashedRoute']);` instead, it works.

I thought that shouldn't matter ...

**Comment by jhli** [comment]
• Try /admin/acl-manage/......
Note the dash, e.g. '-'.
• use inflected route

**Comment by markstory** [comment]
Have you looked at what routes are connected?

```bash
bin/cake routes
```

Will show you the routes that have been connected.

**Comment by markstory** [comment]
Another issue is that your routes are incorrectly ordered. The `/:controller/*` should be *after* the `/:controller/:action/*` route as `/:controller/*` matches all the same things that `/controller/:action/*` does.
