### ISSUE TITLE
Phone validation fails a valid phone number

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#8567]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: Apache 2.4.7, PHP 5.5.9

### What you did
Tried to enter "8002114511" into a field with the validation rule "phone" enforced on it.  I've also tried several different iterations, such as "1-800-211-4511".  You're welcome to call the number if needed, it's an ISP support number that begins with a recorded message.

### Expected Behavior
The provided phone number to be accepted.

### Actual Behavior
The provided phone number is rejected.

**Comment by dereuromark** [comment]
Did you check the latest version of https://github.com/cakephp/localized - if it works there?
Localized validation inside the core is deprecated afaik.

**Comment by watermark** [comment]
I've never heard of that project before, but none-the-less, I just pulled that project in and added that number to the phone test case and it failed there too.  As I mentioned, I'm still using cake 2.x, so I used Localized 2.7.0.

**Comment by markstory** [comment]
The [test cases show some of the accepted formats](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Test/Case/Utility/ValidationTest.php#L2172-L2188).

I'll see where in the pattern this number is being rejected.

**Comment by ravage84** [comment]
> I've never heard of that project before

It seems to me, that our documentation is lacking on this.
