### ISSUE TITLE
Cakephp installation through cpanel

### ISSUE THREAD

**Issue by mallyg34** [cakephp/cakephp#8568]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* 2.8.3 and I also tried the newer version
* I'm using bluehost and uploading files through CPanel

     I've downloaded the cakephp directly from the website. Through my files in cpanel I've uploaded the zip and extracted the files. Moved the extracted files back into the root which is"public_html". When I go to my website it should bring me to the cakephp interface but instead I'm getting a "404: File Not Found". Any suggestions what could be causing this?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
