### ISSUE TITLE
2.x question - error output in debug mode

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#8570]
One of the apps I manage has both JSON views and HTML views as it functions both as a web app by itself and as an API server for a couple of other web apps.

When in dev mode with debug on, if I make an API request and something happens in PHP to trigger a non-fatal error (e.g. a warning), Cake's error handler automatically outputs the information about the error in HTML. This then breaks the JSON output and the client can't parse it.

My current workaround for this is to disable debug mode for all API requests so that warnings/notices etc are still logged but not output. I'd rather be able to leave debug mode on for other reasons though, so if there's another approach that I haven't thought of, I'd like to hear suggestions.

One idea I had was a small PR for the error handler. This is the code which outputs the debug info:
```php
<?php
//ErrorHandler.php
/** ... */
public static function handleError($code, $description, $file = null, $line = null, $context = null) {
        /** ... */
        $debug = Configure::read('debug');
        if ($debug) {
            $data = array(
                'level' => $log,
                'code' => $code,
                'error' => $error,
                'description' => $description,
                'file' => $file,
                'line' => $line,
                'context' => $context,
                'start' => 2,
                'path' => Debugger::trimPath($file)
            );
            return Debugger::getInstance()->outputError($data);
        }
       /** ... */
}
/** ... */
```

My idea was to add a configurable switch which allows an app to choose whether or not to output errors. This would replace the above snippet with something like:
```php
$debug = Configure::read('debug');
$outputErrorDebug = Configure::read("Error.outputDebug");
if ($debug && $outputErrorDebug) {
     //...
}
```

Thoughts?

**Comment by markstory** [comment]
You could also use the `Debugger::outputAs('log')` when doing API requests to force error output into the logs instead of the output.

**Comment by garethellis36** [comment]
Ah, I didn't realize that's what the `outputAs` method was for! That certainly does the job.
