### ISSUE TITLE
RFC 3.3 setting i18nFormat() timezone default

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8571]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.4

### What you did
Used `echo $now->i18nFormat(\IntlDateFormatter::FULL, 'Europe/Paris', 'fr-FR');`

### Expected Behavior
A way to set `'Europe/Paris'` globally or at least for the TimeHelper instance: http://book.cakephp.org/3.0/en/views/helpers/time.html
Like http://book.cakephp.org/3.0/en/core-libraries/time.html#setting-the-default-locale-and-format-string does for the formatting, just for the timezone.

**Comment by markstory** [comment]
How would you see this being implemented?

**Comment by ionas** [comment]
From the guts:
* `bootstrap.php`: `date_default_timezone_set('UTC')`
* `app.php`: ```Configure::write('DateTime.userZone', new DateTimezone('Europe/London'))```
* Calling `\Cake\I18n\Time::i18nFormat(...)` defaulting the 2nd parameter to ```Configure::readOrFail('DateTime.userZone')``` if not given.
* Calling `\Cake\View\Helper\TimeHelper::format(...)` last parameter to ```Configure::readOrFail('DateTime.userZone')``` if not given. (Ref: http://api.cakephp.org/3.2/class-Cake.View.Helper.TimeHelper.html#_format)

Things to consider:
* Datasource timezone (Ref: http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration). Automagic conversion? Yes/No? How?

**Comment by markstory** [comment]
Would setting up the helper be simpler if there was a setter to set the user's default timezone? That seems more explicit than addimg more global state in Configure. Would something like

```php
$this->Time->defaultTimezone($user->timezone);
```
Work?

**Comment by jhli** [comment]
That would work fior TimeHelper:: but not for ::i18nFormat, right?

What about outputting dates in json/xml via serialize in non UTC?

**Comment by lorenzo** [comment]
I can work on this

**Comment by markstory** [comment]
@jhli If your API is outputting specific timezones you should stop that :smile:

**Comment by jhli** [comment]
CsvView autoserialize? Angular pushes?
I get you ;)... But not sure.

**Comment by markstory** [comment]
Even in the context of a client side application its still better to do client side timezone conversion in my opinion.

**Comment by ionas** [comment]
I have tried to fix this and I won't pick this up again. At least not as long as there is a global static time class.

History:
https://github.com/cakephp/cakephp/pull/8588
https://github.com/cakephp/cakephp/pull/8753
https://github.com/cakephp/cakephp/issues/8935
https://github.com/cakephp/cakephp/pull/8976
