### ISSUE TITLE
Validator has requirePresence but not requireAbsent

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8572]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Apache 2, MySQL, Ubuntu 14, PHP 7

### Data Validation in Tables.

Besides creating a custom validator. I don't think there is a built in way to do the opposite of `$validator->requirePresence('fieldName');` in a Table.

### Expected Behavior

I would like to mark some fields as not allowed in create, update or both table actions. I apologize if this is already easily possible, but I could not find an alternative for `requireAbsent`. So I was thinking this would make a nice little improvement.

**Comment by jhli** [comment]
I like it for honypots ;)

**Comment by markstory** [comment]
Are you trying to prevent specific fields from getting into an entity? If yes, why not use the `accessibleFields` option when marshalling data?

**Comment by thinkingmedia** [comment]
@markstory I don't know if this is a documentation issue or not. I'll show what I mean.

According to the "Saving Data" section the accessible fields are not involved.

http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-entities

But I discovered this in the Entity files generated by bake. When you generate an Entity with the bake it produces this comment in the source code.

```
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
```

This isn't actually shown in the documentation in the section for "Saving Data".

http://book.cakephp.org/3.0/en/orm/saving-data.html#avoiding-property-mass-assignment-attacks

**BUT** there is a link to "Mass Assignment"

http://book.cakephp.org/3.0/en/orm/entities.html#entities-mass-assignment

That link is hidden in only one sentence in "Saving Data".

> There are two ways of protecting you against this problem. The first one is by setting the default columns that can be safely set from a request using the Mass Assignment feature in the entities.

Okay, but my confusion goes deeper than just the above.

- While I understand that the Entity implements this feature, it's in the "Saving Data" that people will look for this information.
- The term **bulk** and **mass** are repeatedly used in the documentation. These terms to me imply operations like `updateAll` and `deleteAll`. Those are bulk and mass operations. I don't understand why `patchEntity` would be involved in mass assignment.

Here are some more examples:

> The _accessible property allows you to provide a map of properties and whether or not they can be mass-assigned. The values true and false indicate whether a field can or cannot be mass-assigned:

What now? It says "whether or not they can be mass-assigned". I understand this to mean they can not be assigned during a for/loop or updateAll operation. Yeah, I know that isn't how Entities work but this is what it sounds like.

I think the section on "Mass Assignment" needs changes to help the beginner to understand, and there needs to be more indication of this feature in the "Saving Data" section.

Looks like I have some documentation to write and pull. :smile:

**Comment by markstory** [comment]
Mass-assignment is also a term used for bulk assigning properties to an entity. Both laravel and Rails use the same term for this concept. While I can see that the docs are not as clear as they could be, and we could better explain how everything fits together for the new user, I wouldn't want to remove that term as it is the correct one.

Bake creates less secure entities by default as we had a number of usability related issues reported when it defaulted to whitelisting specific fields.

**Comment by jhli** [comment]
As the validator can be used in modelless forms requireAbsense makes a lot of sense, still for honypots.

Not sure if/how you can xor validation rules but in case you can it also males sense for normal entity validation (requirePresence A and Absence B XOR Absence A and Presence B).

**Comment by thinkingmedia** [comment]
@markstory How can I track issues that I want to work on? Is it possible to assign me to those issues?

**Comment by ADmad** [comment]
@thinkingmedia Issues can only be assigned to team members who have commit rights to the repo.

**Comment by thinkingmedia** [comment]
I can just create issues in my fork. I should have thought of that at
first. I wish forks were more integrated with the upstream repo and issues.

**Comment by jhli** [comment]
Once you create a feature branch in your fork and setup a pull request, updating the fork afair will update the PR as well and people can comment!

**Comment by markstory** [comment]
I still don't understand how ensuring a field is absent is helpful, and why the existing mass-assignment tools aren't suitable for this scenario.

**Comment by ADmad** [comment]
@jhli Honey pot fields are checked for being empty (we already have "blank" rule for it), not that it's absent.

**Comment by thinkingmedia** [comment]
@markstory the problem here is that data integrity has been split across two classes. The entity and the table. The entity implements integrity with the mass-assignment feature, and the table has validators and rules. So to get a full understanding of how you can handle integrity using Cake you have to understand multiple places where it's handled. A single class that handled all the above would be easier to use and understand.

I think an RFC on how the ORM could be improved in this area would be a good thing for Cake 4.x

**Comment by ionas** [comment]
@markstory I don't understand how mass-assignment/non-mass-assignment helps with the honypot thing, but I do understand how blank does @ADmad (if there is notBlank as well as blank).

@thinkingmedia I still think **all** single/tuple-field validation belongs into entities and that defining it in the table is a dirty hack IMHO, where everything that cross checks between multiple entities, unique, composite unique, foreign-key and primary-key constraints, exist-in and whatnot belongs into the table (as a "Rule" instead of an "Validation")

**Comment by markstory** [comment]
> the problem here is that data integrity has been split across two classes. The entity and the table. The entity implements integrity with the mass-assignment feature, and the table has validators and rules. 

I guess the issue I have with `requireAbsent()` is that it ignores possibility of the effectively infinite fields you don't want applied to the entity. Should the presence of any of those infinite fields fail validation? I feel that disclosing to a bad guy that they found a 'secret' field is not ideal. I write my applications to ignore unwanted input without error.

Another issue I have with `requireAbsent()` is that it is effectively a blacklist. I think that whitelist based approaches are safer & simpler. The `accessibleFields` option provides this whitelist and does it at the same time as you use validation (via `newEntity()` & `patchEntity()`.

@ionas accessible fields doesn't help with honey-pot fields. I don't think the proposed `requireAbsent()` would help ensuring that a field stays present but blank either.

**Comment by jhli** [comment]
@markstory, yep 'blank' makes a lot more sense as Admad explained.

**Comment by thinkingmedia** [comment]
> Should the presence of any of those infinite fields fail validation? I feel that disclosing to a bad guy that they found a 'secret' field is not ideal.

Oh right, because validation gives feedback. I totally forgot about that. That's a very good point.

**Comment by markstory** [comment]
@thinkingmedia Yeah. And telling bad guys that they found hidden gold is a big no-no from my experience.

**Comment by thinkingmedia** [comment]
Closing as a security risk.

**Comment by inoas** [comment]
I came across implementing natural keys the last weeks and then having to fight against cake.
So I consider/opting to surrogate primary keys (id incrementing). The prior natural keys however should continue to exist as unique keys - furthermore they should be IMMUTABLE.

Considering the immutability case now I think I'd like `requireAbsense()` to exist for that on update it should be absent, whereas on create it should be required.

Does that make sense to you? Any better ideas?

**Comment by ADmad** [comment]
Unset the property in beforeSave for non new entity and be done.

**Comment by inoas** [comment]
Okay, that's the same for requirePresence then, check if the key exists, isn't it?
If I care about the PR would and its well tested and working, similar to requirePresence. Were you willing to merge it @markstory?

**Comment by ADmad** [comment]
No it's not, since if a value is required to be present and not provided by user then you have to ask the user to provide it.

In case of absense you don't require user to do anything.

**Comment by markstory** [comment]
I think `requireAbsent()` overlaps with field whitelists and accessible fields. I'm not sure we need all 3.

**Comment by inoas** [comment]
Well whitelists and accessible fields are both not really black lists. And in this case I'd like a black list. Anyway what ADmad suggested works just fine.
