### ISSUE TITLE
dosen't load shell of plugin

### ISSUE THREAD

**Issue by mehdi-fathi** [cakephp/cakephp#8573]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2 

### What you did
I have a plugin.it has a shell command.it runed good in cakephp 3.0.but today i was going to use in cakephp 3.2.it didn't load shell command ! i think my command is true.my command : `cake AclManager.acl` i guess cakephp v3.2 has a inside problem

**Comment by josegonzalez** [comment]
Did you load the plugin in your `config/bootstrap.php`?

**Comment by markstory** [comment]
How can someone reproduce this issue?
