### ISSUE TITLE
Allow configuring SQL Server cursor and scroll type

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/cakephp#8579]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.6
- Platform and Target: Microsoft Azure IIS / SQL Azure (MSSQL).
### What you did

I'm working on a fairly large web app that uses Azure for hosting and SQL Server. While doing some performance tuning, I noticed changing the cursor type had big performance gains when developing locally, but not so much on the production deployment. Using the client-side buffered cursor improved page loading times from upwards of 30 seconds down to 1-2 seconds.

It would help greatly if I was able to specify this cursor type somewhere in the `/config/app.php` file so local and production deployments can have different settings.
### Current Behavior

Line 107 of `Cake\Database\Driver\Sqlserver`

```
$options = [PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL];
```
### Changed Behavior

Line 107 of `Cake\Database\Driver\Sqlserver`

```
$options = [PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL, PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => PDO::SQLSRV_CURSOR_BUFFERED];
```
### References

I found an old discussion about basically this issue. I understand not being able to use the FWDONLY cursor due to row count and such with the ORM.
https://groups.google.com/forum/#!topic/cake-php/2Vqixc1UGCw

**Comment by kyleweishaupt** [comment]
Although performance is much better, this does break some of the booleans on my Users table. They are returning false when the value is true. I am using quoteIdentifiers as well.

**Comment by markstory** [comment]
You can already specify any additional flags you want using the `flags` option in the datasource configuration.

**Comment by kyleweishaupt** [comment]
I did miss the `flags` option in the documentation, but adding in the following is not working for me:

    'flags' => [
        PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => PDO::SQLSRV_CURSOR_BUFFERED
    ]

**Comment by kyleweishaupt** [comment]
I have an open MSDN forum thread as well referencing this issue as well. 

https://social.msdn.microsoft.com/Forums/en-US/9fa8e913-bff9-44dc-b4af-437b4ff5c0eb/better-performance-from-a-php-app-using-azure-sql?forum=ssdsgetstarted

**Comment by andremoniz** [comment]
@kyleweishaupt  Any news on this?

**Comment by lorenzo** [comment]
No, but if you want to go ahead and implement the feature, that would help for sure :)

**Comment by kyleweishaupt** [comment]
@andremoniz The boolean values returning false still occurs on CakePHP 3.2.8 on PHP 5.6.17. At the moment I cannot test on PHP 7 due to lack of support for UTF8 in the SQL Server driver (https://github.com/Azure/msphpsql/tree/PHP-7.0).

**Comment by kyleweishaupt** [comment]
I believe issue #8674 is pretty much the same issue I am having.

**Comment by kyleweishaupt** [comment]
I noticed 3.2.11 had a few updates for SQLServer. Any update on fixing boolean values or adding cursor option?

**Comment by lorenzo** [comment]
Nope, nothing in this area so far. If you have access to a Windows server, it would be nice to get some help

**Comment by stmeyer** [comment]
@kyleweishaupt please check if PR #10490 is fixing this RFC

**Comment by kyleweishaupt** [comment]
@stmeyer Just got a chance to check all this out. The extra options in the pull request are greatly appreciated. 

It looks like the latest SQL Server driver fixes the original boolean issue.
