### ISSUE TITLE
Caching - modify config instead of drop config to recreate

### ISSUE THREAD

**Issue by EdouardTack** [cakephp/cakephp#8580]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### What you did
[Caching::drop](http://book.cakephp.org/3.0/en/core-libraries/caching.html#removing-configured-cache-engines), we need to drop before configure with other parameters.
We can add a method to update parameters for Caching config ?

### Expected Behavior
In my case, I want to dynamically change the path of Cache File compared my vars. So i prefer change config instead of drop it.

```
Cache::config('short', [
    'className' => 'File',
    'duration' => '+1 hours',
    'path' => CACHE,
    'prefix' => 'cake_short_'
]);
```

And after get some vars, change the path for example

```
Cache::extendConfig('short', [
  'path' => CACHE . DS . 'user_' . $userid
]);
```

**Comment by markstory** [comment]
Sounds like you should be using two cache configs instead of 1. 

One reason we don't allow runtime mutation of cache configuration through the config() method is that it makes it easier to accidentally modify effectively hidden global state which can impact how an application works and makes it harder to understand/reason about what the application will do at any given point.

With that said, having a separate method would at least make it easier to find when someone is up to tricks.

**Comment by lorenzo** [comment]
What's the reason behind changing the file on the fly?

**Comment by EdouardTack** [comment]
I create a multi-websites system. So, i want to have one caching config but change the path dynamically. On website have one cache directory.

**Comment by jippi** [comment]
if we do something like this, then we need to support/detect host/port changes, so we properly reconnect as well - a simple prefix is quite easy to handle in its own though :)

**Comment by lorenzo** [comment]
@EdouardTack so, I guess the current website is known at some point doing the request and not changed afterwards?

**Comment by EdouardTack** [comment]
Yes @lorenzo the website is known before caching.
I understand why we can't override config on the fly like i want.
I Will find an other way to do what i want, with Component or something else.

**Comment by markstory** [comment]
@jippi These are all reasons why we don't support runtime config changes :smile:

**Comment by markstory** [comment]
@EdouardTack Could you define the site-specific cache config once the site has been determined? That would obviate the need to modify cache engines at runtime.

**Comment by EdouardTack** [comment]
@markstory Yes, i can do that. Thank you for response. I close.
