### ISSUE TITLE
Class 'Cake\Mailer\Email' not found 

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#8583]
I use cakephp-3.2.6 ,unzip this zip file, and put it in webroot,then display:
Error: Class 'Cake\Mailer\Email' not found 
File F:\www\macnie\tool\config\bootstrap.php 
Line: 148

**Comment by ADmad** [comment]
> unzip this zip file

What is **this**?

**Comment by ionas** [comment]
@macnie please join us on IRC (or Slack) and give this a thorough read: http://book.cakephp.org/3.0/en/installation.html

**Comment by markstory** [comment]
This is likely a duplicate of #8585. I've re-built the zip file for 3.2.6 and it should contain the correct file now.
