### ISSUE TITLE
Packaged releases containing the wrong CakePHP version

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#8585]
I've checked only a few, but those for example

https://github.com/cakephp/cakephp/releases/download/3.2.6/cakephp-3-2-6.zip
https://github.com/cakephp/cakephp/releases/download/3.1.13/cakephp-3-1-13.zip
https://github.com/cakephp/cakephp/releases/download/3.2.5/cakephp-3-2-5.zip

all contain version 3.0.18 (according to `VERSION.txt`).

**Comment by thinkingmedia** [comment]
These do not look like valid releases. They are apps with a vendor folder.

**Comment by ndm2** [comment]
@thinkingmedia That's actually correct, they are packaged application relases that contain all necessary dependencies, but (at least) the `cakephp/cakephp` dependency is incorrect.

**Comment by ADmad** [comment]
Looks like the [Makefile](https://github.com/cakephp/cakephp/blob/master/Makefile) which creates the download archives needs to be fixed. PR welcome :)

**Comment by thinkingmedia** [comment]
@ADmad debugging make on Windows is very difficult :disappointed:

**Comment by markstory** [comment]
Those packages are probably incorrect because they were from days when I did multiple releases at once.

I'll get them fixed up. I'll see what can be done with the `Makefile` too. There might not be anything we can do though. I don't really want to build artifacts that contain pinned dependencies.

**Comment by markstory** [comment]
I've corrected the packages @ndm2 pointed out. I've also put up a pull request that I think will solve building new packages in the future for 3.0.x and 3.1.x.
