### ISSUE TITLE
MySQL 5.5 Full column name bug on update query

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8592]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Running unit tests with PHPUnit and MySQL

### What you did
I am testing one of my Models, and the tests run fine on my local machine, but they fail on Travis.
I have MySQL 5.7 running on my OSX, and the unit tests run fine, but on Travis they fail.

I traced the source of the problem. I have an update query:
```php
$count = $this->Products->query()->update()
                        ->set(['reservation_id' => $reservation->id])// Add product to reservation
                        ->where(['Products.id IN' => Hash::extract($products, '{n}.id')])
                        ->execute()
                        ->rowCount();
```

This gives me an SQL error on travis saying that `Products.id` column was not found in the table Products. On my local 5.7 MySQL, it runs fine. However when changing it to `->where(['id IN' ` Everything runs fine on travis as well as my local machine. Travis runs MySQL v 5.5 I think.

**Comment by thinkingmedia** [comment]
Do you have `quoteIdentifiers` set to `true` for your `Datasources` settings in your `app.php`?

I've found this is often required with mysql.

**Comment by markstory** [comment]
I suspect that your 5.7 setup has [case-sensitive identifiers](http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html) turned on. This isn't an issue with CakePHP.

**Comment by lorenzo** [comment]
I think the reason for the problem is that MySQL does not allow aliasing like Products.id in update queries. You need to remove the aliasing
