### ISSUE TITLE
Saving an entity with a MySQL DB field type DATE saves as \Cake\i18n\Time format

### ISSUE THREAD

**Issue by jessicamarx** [cakephp/cakephp#8593]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.2
* Platform and Target: nginx, MySQL, centos 6.7

### What you did
I am attempting to save an entity, input field is:
	'starter_date' => '2016-04-25',

The database field type is **DATE**

Immediately after calling patchEntity() on my entity, the resulting data is this:

/src/Controller/Marketing/CampaignsController.php (line 66)
object(App\Model\Entity\Campaign) {

	'name' => 'This is a test campaign',
	'description' => '<p>sdfasd fsdfasd f</p>',
	'_wysihtml5_mode' => '1',
	'budget' => (int) 124124,
	'start_date' => object(Cake\I18n\Time) {

		'time' => '2192-12-04T00:00:00-0500',
		'timezone' => 'America/Detroit',
		'fixedNowTime' => false
	
	},
	'starter_date' => object(Cake\I18n\Time) {

		'time' => '2171-12-04T00:00:00-0500',
		'timezone' => 'America/Detroit',
		'fixedNowTime' => false
	
	},
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'name' => true,
		'description' => true,
		'_wysihtml5_mode' => true,
		'budget' => true,
		'start_date' => true,
		'starter_date' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => []
	],
	'[repository]' => 'Campaigns'

}

### Expected Behavior
Save field like this:
	'starter_date' => object(Cake\I18n\Date) {

### Actual Behavior
Field saves like this:
	'starter_date' => object(Cake\I18n\Time) {

This massively screws up the input into the database:
'2196-12-04'

**Comment by jessicamarx** [comment]
Updating to 3.2.6 changed the behavior:

    /src/Controller/Marketing/CampaignsController.php (line 59)
    [
	'id' => '',
	'name' => 'This is a test campaign',
	'description' => '<p>sdf asdsdf</p>',
	'_wysihtml5_mode' => '1',
	'budget' => '234243',
	'start_date' => '2016-04-25',
	'end_date' => '2016-04-29'
]
/src/Controller/Marketing/CampaignsController.php (line 64)
object(App\Model\Entity\Campaign) {

	'name' => 'This is a test campaign',
	'description' => '<p>sdf asdsdf</p>',
	'_wysihtml5_mode' => '1',
	'budget' => (int) 234243,
	'start_date' => object(Cake\I18n\Date) {

		'time' => '2192-12-04T00:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'end_date' => object(Cake\I18n\Date) {

		'time' => '2196-12-04T00:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'name' => true,
		'description' => true,
		'_wysihtml5_mode' => true,
		'budget' => true,
		'start_date' => true,
		'end_date' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Campaigns'

    }

**Note**
it uses the correct class, but still buggers the insert to MySQL. It inserts it in the database as: 2196-12-04

**Comment by lorenzo** [comment]
You are passing the wrong date format to patchEntity(). This is because your app is expecting the dates to be in the localized format. You can disable this feature in your bootstrap.php file, by removing the lines useLocaleParser()

**Comment by josegonzalez** [comment]
They are passing it as a string: `2016-04-29`. This makes it become detected as an integer, changing how the parsing works. If the data is passed as an array, it works fine. I somehow don't think it's the locale parser, but even if it was, I'm pretty sure @jessicamarx's locale is UTC, so that date format should work.

**Comment by markstory** [comment]
@josegonzalez How could we make it better. PHP handles most of the date shifting when the values are read from the 'localized' input.

**Comment by ndm2** [comment]
Not sure how common this issue actually is, but it popped up quite a few times on StackOverflow.

* http://stackoverflow.com/questions/36218846/in-mysql-date-field-saving-wrong-year
* http://stackoverflow.com/questions/34270890/cakephp-wrong-date-in-mysql
* http://stackoverflow.com/questions/33734683/cakephp-3-not-saving-datetime
* http://stackoverflow.com/questions/36366852/cakephp-3-date-input-and-database-issue
* ...

People seem to be unaware of what locale parsing means, respectively that it exists at all.

**Comment by markstory** [comment]
Perhaps we should remove the `useLocaleParser()` calls in the app skeleton if it is tripping people up?

**Comment by ndm2** [comment]
Maybe... I could imagine that the majority of people will use rather common date formats for their inputs, and that those that are using the uncommon ones, ie those that cannot be (properly) interpreted via `DateTime::__construct()`, are more aware of the possible need to tweak some configuration to get things working properly.

**Comment by markstory** [comment]
My thinking was that if we don't have localeParsing enabled by default, those that need it can find it in the docs and enable it.

**Comment by lorenzo** [comment]
I'm ok with removing it

**Comment by josegonzalez** [comment]
:+1:

**Comment by markstory** [comment]
I'll take care of that.

**Comment by thinkingmedia** [comment]
I just ran into this issue. To fix it I tried the following.

- check the date format used by the validator. It defaults to "Ymd" so the date was passing validation.
- I then tried creating a mutator in the entity since `Time::createFromFormat("Y-m-d")` works, but the passed value was already parsed to a date object.
- gave up and googled to here.

I've read the comments, but I'm still confused as to why this happen. What is `useLocaleParser` suppose to do?

**Comment by markstory** [comment]
@thinkingmedia It enables you to accept localized date formats and the ORM/Database layer will convert them into objects. So if your locale is polish, the `dd.mm.yyyy` format will be accepted in date/datetime fields and automatically handled. Sadly the default format for 'en-us' is `mm/dd/yy`.

**Comment by markstory** [comment]
Pull request up to remove locale parsing by default. @jessicamarx Does removing the calls to `useLocaleParser()` fix your issue?

**Comment by thinkingmedia** [comment]
Removing `useLocaleParser()` fixed my issue.

What I don't understand is why `useLocaleParser` forces an all or nothing formatting. When it is not used you can use a variety of date formats and Cake will parse it correctly, but when it's used it's that locale format always.

I find date parsing to be a little bit like a black box. Just curious what's going on inside. What source files handle this date processing?

**Comment by markstory** [comment]
@thinkingmedia Its in `Cake\Database\Type\DateTimeType`
