### ISSUE TITLE
Bake confused by "_id" field name.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8595]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Apache2, MySQL, Php 7

### What you did

Added a field named `_id` as an integer to the MySQL table. It was not the primary key of the table as it already had an `id` field that is uuid. 

The `_id` is just a field to store an reference value from a third-party source.

### Expected Behavior

Bake to treat this field as regular value field.

I understand that the field name "_id" does not follow Cake naming conventions. I needed the prefix since all field names mapped to  third-party JSON fields. This just made my job of processing data easier.

### Actual Behavior

Bake generated an empty `belongsTo` association in the table.

```
        $this->belongsTo('', [
            'foreignKey' => '_id',
            'joinType' => 'INNER',
            'className' => 'TheMovieDB.'
        ]);
```

Bake generated an empty `@property` in the table.

```
/**
 * Genres Model
 *
 * @property \Cake\ORM\Association\BelongsTo $
 * @property \Cake\ORM\Association\BelongsToMany $Movies
 * @property \Cake\ORM\Association\BelongsToMany $TvShows
 */
```

Bake generated an empty `@property` in the entity.

```
/**
 * Genre Entity.
 *
 * @property string $id
 * @property int $_id
 * @property \TheMovieDB\Model\Entity\ $
 * @property string $name
 * 
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 */
```

> Note: TheMovieDB is the name of my plugin.

I assume that this can be an easy fix. Bake just needs to validate the format of a field name before treating it as an associated. I think bake is just checking if it ends in `_id`. It needs to end with `_id` and be more then 3 characters.

**Comment by ADmad** [comment]
This issue was moved to cakephp/bake#236

**Comment by thinkingmedia** [comment]
@ADmad oh right. I forgot it was a plugin.
