### ISSUE TITLE
Running shell task directly from console displays welcome message twice

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8600]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

It is a minor bug i guess 

When I run shell task directly from the cli, weclome message shows twice:

```
Z:\git\x\php\CakeDS\bin>cake setup admin

Welcome to CakePHP v3.2.6 Console
---------------------------------------------------------------
App : src
Path: Z:\git\x\php\CakeDS\src\
PHP : 7.0.3RC1
---------------------------------------------------------------

Welcome to CakePHP v3.2.6 Console
---------------------------------------------------------------
App : src
Path: Z:\git\x\php\CakeDS\src\
PHP : 7.0.3RC1
---------------------------------------------------------------
Display name:
>
```

I am suppressing this behaviour by adding 
`    public function startup()
    {
        $this->params["requested"] = true;
        parent::startup(); // TODO: Change the autogenerated stub
    }`

to the task. 

I know that additional "welcome message" can be helpfull to introduce user into task, but IMHO it should be optional feature, and by default this should be disabled in case of direct CLI task invocation.

**Comment by thinkingmedia** [comment]
It's printed each time an options parser is executed. One for the shell and another for a child task. It should only be shown once (use a static flag?), but I agree it has little value as a default always on. I'm working on shell tasks now and my logs are peppered with these messages.

**Comment by markstory** [comment]
We could make the default implementation of `_welcome` suppress the message when `params['requested']` is true.

**Comment by markstory** [comment]
Pull request open now.
