### ISSUE TITLE
Support namespaces in migration files.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8603]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Apache2, MySQL, PHP 7

### What you did

- Create an app and bake a migration file called `CreateImages`.
- Create a plugin and bake a migration file called `CreateImages`.

### Expected Behavior

The classes `CreateImages` are unrelated to each other.

### Actual Behavior

PhpStorm warns that the class `CreateImages` is already defined for the project. Since the migration classes do not use a namespace they exist in the same global space.

Is this a limitation imposed by Phinx?

**Comment by dereuromark** [comment]
If this is a limitation maybe we should always prefix with the plugin or vendor name then?

**Comment by thinkingmedia** [comment]
I would prefix only plugins but that's a good idea.

**Comment by HavokInspiration** [comment]
Right now, migrations can not live under a namespace.
See https://github.com/cakephp/migrations/issues/139 and https://github.com/robmorgan/phinx/issues/168

So currently, only prefixing the migration classname as @dereuromark suggested would work.

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#213
