### ISSUE TITLE
Using find('list') within contain function will throw warning and array with contained results will be empty

### ISSUE THREAD

**Issue by K4T** [cakephp/cakephp#8606]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.1.13

### What you did
I tried to use $q->filter('list') within contain function. Example:

```php
$doc = TableRegistry::get('Documents')
->find()
->contain([
    'documentProperties' => function ($q) {
        return $q
            ->find('list', [
                'keyField' => 'name',
                'valueField' => 'value'
            ]);
    }])
->where([
    'Documents.id' => $docId
]);
```

### Expected Behavior
Contained results should be in key-value format.

### Actual Behavior
I am getting warning:
```
Warning (2): Illegal string offset 'document_id' [CORE\src\ORM\Association\ExternalAssociationTrait.php, line 115]
```
and contained results are empty. Generated SQL is ok and I can see in DebugKit that my query returned correct rows.

Is there a simple way to get contained results in list format?

**Comment by lorenzo** [comment]
Yes:

```php
$list = collection($query->first()->tags)->combine('id', 'tag_name');
```

**Comment by jhli** [comment]
Could contain and nested list be made to work and/or  above be added to the book?

**Comment by lorenzo** [comment]
@jhli nope, at least not without losing my head trying :P

**Comment by markstory** [comment]
The issue here is that your find(list) doesn't include any foreign keys. It is basically impossible to stitch the data back together.

Closing because as it stands your query results are impossible to put back together again.
