### ISSUE TITLE
2.x - probable conflict with future version of PHP7

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#8611]
I just noticed this PHP RFC: https://wiki.php.net/rfc/reserve_even_more_types_in_php_7

If I read this correctly, a future minor version of PHP7 will introduce the reserved keyword "Object", which will break CakePHP 2.x.

Presumably a future major version of the 2.x branch should rename the god class `Object` to something else.

Happy to PR this but I imagine there are some finer points to discuss first...

**Comment by dereuromark** [comment]
I agree, it should be deprecated and moved to `CakeObject` for example.

**Comment by thinkingmedia** [comment]
It's lower case `object`. I think that will prevent collision, but CakeObject is a way better name anyway.

**Comment by garethellis36** [comment]
@thinkingmedia I don't think it's case-sensitive. PHP7 added `string` as a reserved keyword and you can't name a class `string` or `String` for example.

**Comment by thinkingmedia** [comment]
@garethellis36 PHP is the funky dynamic type language from hell that will always leave you guessing.

**Comment by dereuromark** [comment]
See https://github.com/cakephp/cakephp/compare/2.next...2.next-php7comp WIP

**Comment by thinkingmedia** [comment]
@dereuromark I know that I have used the `Object` a few times because it has the `set` method. I would advise keeping around an `Object extends CakeObject` and marking it depreciated, and not removing it until it has to be removed. Just to avoid breaking Cake 2 builds that update for security reasons.

**Comment by dereuromark** [comment]
Did you see my branch? I did exactly that :)
Closing as PR is now open.

**Comment by thinkingmedia** [comment]
@dereuromark :+1:
