### ISSUE TITLE
Two datasource relations with Paginator

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#8614]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: Apache (Windows), PHP 5.5, MySQL and ORACLE

### What you did
I use app with two configuration on database (default as MySQL and ORACLE). I have relations between models from different datasource (eg. MySQL Model hasMany Oracle Model). It's works fine.
Problem is with `PainatorHelper::sort()`

### Expected Behavior
`Paginator::sort()` not using datasource config?

### Actual Behavior
Sort on Oracle `Model.field` i get SQL query in MySQL (because is default and is set `Paginator::paginate('MySQL model')` with `ORDER BY Oracle.field`

**Comment by markstory** [comment]
You can't sort on hasMany relationships even if they are in the same datasource. The paginator component is just doing what it's told here.
