### ISSUE TITLE
Using Alternate DateTime Class in Cake\Database\Type\DateTimeType 

### ISSUE THREAD

**Issue by darensipes** [cakephp/cakephp#8616]
I have created a class App\I18n\Time that adds some additional functions and class variables on top of Cake\I18n\Time. I can't seem to find a way to override `public static $dateTimeClass = 'Cake\I18n\Time';`

-- or --

``` php
public function useMutable()
{
    $this->_setClassName('Cake\I18n\Time', 'DateTime');
    return $this;
}
```

Now, I know I can create a Type in my App\Database\Type\ then in my tables everywhere I need to override do something like: 

``` php
protected function _initializeSchema(Schema $schema)
{
    $schema->columnType('my_date', 'cool_new_date_type');
    return $schema;
}
```

I would rather have a way to mass override all datetime column types. I tried tracing it though the code to figure out the best way to override and couldn't come up with a clean solution.

Thoughts?

**Comment by markstory** [comment]
We could add a method that allows an arbitrary class name to be injected.

**Comment by darensipes** [comment]
Sounds good to me.

**Comment by lorenzo** [comment]
@darensipes Would you like to implement this feature?

**Comment by ADmad** [comment]
Closing as the issue has gone stale. A pull request is welcome if you are still interested in this feature.
