### ISSUE TITLE
3.x add Validator::unequals() and Validator::equals()

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8618]
This is a:
* [x] enhancement
* [x] feature-discussion (RFC)
* CakePHP Version: 3.2.4

### What you did
Validation to check if fields equal / unequal.

### Expected Behavior
validation rules `Validation::equals()` and `Validation::unequals()` to be existing

### Actual Behavior
`Validation::compareWith()` exists, see: 
https://github.com/cakephp/cakephp/pull/5813/files#diff-b13ca847d0ea573e5909a8284f726a1bR272
The method name is not clear (you validate by comparing based on what condition? equalness, unequalness, whatever else, some regexp?) and the negation of it seems hard to find words for.

### Suggestion
* Keep `Validation::compareWith() ` for BC reasons. Deprecate.
* create `Validation::unequals()` which calls equals but negates the `return` statement `boolean`.
* For the new methods, add support for more than two field by making the first param `[]` and the second context (e.g. check if 3 fields match if you want to).

### Considerations
* `matching()`/`notMatching()` might do similar but possibly based on a given PREG regexp? Good/Bad?
* `compareWith()`, `equals()`/`unequals()` can be missunderstood as to match against a string (or regexp) instead of a field. 

### Conclusion
If you agree I can create a PR (minus `matching()`/`notMatching()`) including Testcases and cakephp/doc changes.

**Comment by dakota** [comment]
I think a better name would be `isEqualTo` and `isNotEqualTo`. `Unequal` just feels clumsy to me.

**Comment by Oxicode** [comment]
isEqualTo and isNotEqualTo +1

**Comment by thinkingmedia** [comment]
Can you post an example of how this would be used.

**Comment by dakota** [comment]
@thinkingmedia, `isEqualTo` can be used to compare password fields, and `isNotEqualTo` could be used to used to ensure that the username and passwords are not equal.

**Comment by ionas** [comment]
@dakota however:
http://api.cakephp.org/3.0/source-class-Cake.Validation.Validation.html#553-563

... which can't be used to compare field values but one field to a value.

What is missing is a negated compareWith() - what I'd also like to see is the ability to assign multiple fields so that none within the list match and/or none as a complete set match against each other.

### Example
```php
$validator
    ->requirePresence('title', 'create')
    ->notEmpty('title')
    ->isEqual('status', 'DONE'), // already implemented (should be named something like isEqualToValue?
    ->notMatchingInContext(['title', 'sub_title', 'header_1']) // Neither of these match to each other (both in context)
    ->notMatchingInContext('username', 'password') // Neither of these match to each other (both in context)
    ->matchingInContext(['email', 'email_confirm']); // These need to match against each other
```

**Comment by ionas** [comment]
Closing as PR is open.
