### ISSUE TITLE
3.x Getting entity nested attribute (via dot notation)

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#8619]
This is a (multiple allowed):
* [x] enhancement

* CakePHP Version: 3.x

### Expected Behavior
What if it was possible to get nested attributes/associations by calling `$article->get('user.name')`?

It would check if all associations exists and if not, it will return null.

It would simlify this type of code in views where are need to manually check if all associations exist. So instead of
```
Recently commented by: <?= $article->last_comment && $article->last_comment->user ? $article->last_comment->user->username : '' ?>
```

I could just write
```
Recently commented by: <?= $article->get('last_comment.user.username') ?>
```

What do you think?

**Comment by chinpei215** [comment]
The PR has already been opened by @beporter.
