### ISSUE TITLE
Option to check NULL values for IsUnique

### ISSUE THREAD

**Issue by JayPHP** [cakephp/cakephp#8620]
This is a:
* [x] enhancement
* CakePHP Version: 3.2.5

### What you did
Tried to save a duplicate record in the database with a NULL value.
Example here http://stackoverflow.com/questions/36031664/cakephp-3-multiple-isunique-allowing-null-duplicate

### Expected Behavior
The save to fail due to the IsUnique rule or an option to tell IsUnique to check for NULL values.

### Actual Behavior
Save was successful. 

### Suggestion
I've opened a pull request here https://github.com/cakephp/cakephp/pull/8621 with my suggestion

**Comment by markstory** [comment]
Closing as a pull request has been opened.

**Comment by saeideng** [comment]
cake 3.2.X need to these changes :)
