### ISSUE TITLE
3.x How to set the Connection Timeout

### ISSUE THREAD

**Issue by ayman-alkom** [cakephp/cakephp#8626]
In my app I allow the users to enter a connection string and I am setting the configs on the fly.
but when the $user_config['server'] is not valid it takes about **60** second to response 
how can we set the time out.
I am using PDO_SQLSRV

**Comment by markstory** [comment]
You'd have to use [a pdo option](http://php.net/manual/en/pdo.constants.php). There isn't much CakePHP related to this though as you're effectively giving the user direct access to PDO::__construct().
