### ISSUE TITLE
Forms no longer respect 'Model' for creating the submission url since 2.8 upgrade

### ISSUE THREAD

**Issue by voycey** [cakephp/cakephp#8628]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: Ubuntu 14.04 PHP 5.5.9

### What you did
Upgraded core to 2.8.3 from 2.7.7

### Expected Behavior
Forms maintain the action url's and not break all forms created using the 'action' parameter

### Actual Behavior

Form Creation Code: (in Posts/view.ctp)

```
<?php
    echo $this->Form->create('Comment', array('action' => 'addComment', 'id' => 'addCommentForm', 'div' => false, 'label' => false, 'id' => 'addCommentForm', 'type' => 'POST'));
    echo $this->Form->input('Comment.body', array('type' => 'textarea', 'class' => 'ckeditor', 'label' => false, 'div' => false));
    echo $this->Form->input('Comment.post_id', array('type' => 'hidden', 'div' => false, 'value' => $post['Post']['id']));
    echo $this->Form->input('Comment.parent_id', array('type' => 'hidden', 'div' => false, 'value' => 0, 'id' => 'commentParentID'));
    echo $this->Form->input('Comment.post_slug', array('type' => 'hidden', 'div' => false, 'value' => $post['Post']['slug']));
    echo $this->Form->input('Comment.tag_pathway', array('type' => 'checkbox', 'before' => "<br />", 'label' => "&nbsp; Add this to my Implementation / Certification Pathway"));
    echo $this->Form->submit('Submit', array('type' => 'submit', 'onclick' => 'submitComment();', 'id' => 'addComment', 'label' => false, 'div' => false, 'class' => ''));
    echo $this->Form->end();
?>
```
2.7.7:

Creates form as:
```<form action="/comments/addComment" id="addCommentForm" method="post" accept-charset="utf-8">```

2.8.3:

Creates form as:
```<form action="/posts/addComment" id="addCommentForm" method="post" accept-charset="utf-8">```

I saw the entry in the [Migration Guide ](http://book.cakephp.org/2.0/en/appendices/2-8-migration-guide.html) but it only seems to reference the actual creation of the ID's - nothing to do with the actual submission url. The majority of code uses 'url' internally if submitting to a different controller, however if submitting to a different action there are a lot of plugins that are using 'action' still.

If this is a removal of this functionality then the documentation on this could be clearer specifying that this is a removal rather than a deprecation.

Thanks

**Comment by lorenzo** [comment]
I think the feature that was changed is that it expects the url key instead of action. Interestingly enough I did not remember that automatic controller from model name was a feature it had :)

**Comment by ADmad** [comment]
> Interestingly enough I did not remember that automatic controller from model name was a feature it had

It was a wacky feature since 1.x which we kept dragging on for backwards compatibility :)

**Comment by voycey** [comment]
It could well have been a leftover from a relic of 1.x, a lot of plugins have 'action' in them rather than 'url' and up until this release they would be fine. 

If this has been dragged forward should it keep being after being deprecated until 2.9? I'd rather get rid of the ambiguity of it but I guess its a breaking change if you are deprecating it but the functionality is actually different?

**Comment by dereuromark** [comment]
If you can make a PR to continue to support this old and undocumented behavior, that would be awesome.
Otherwise we should ammend the migration guide to include that it is now not possible anymore to auto-use the forms model here.
Either way it is highly recommended to not rely on this automagic and somewhat broken functionality of action key and instead always use the clear and verbose `url` key instead from 2.8+ on forward.

**Comment by markstory** [comment]
@dereuromark Could you take this on? If I remember correctly you did the change around FormHelper action/url keys.

**Comment by dereuromark** [comment]
> Interestingly enough I did not remember that automatic controller from model name was a feature it had

Me neither.
It also sounds like exactly the wrong thing we do NOT want to have. A form by design should always post to itself by default, unless specifically told otherwise via `url` key.
 
There is no test covering the above use case, and I am not sure we should continue to drag this wacky and wrong behavior along any further... It is a hidden and dangerous thing that only existed because action wasnt removed earlier.

But if @voycey or someone is able to provide a patch this can be fixed none the less.
I am still in favor of adjusting the migration guide to mention the change here as lightweight approach to overcome this issue in a more reasonable way - and be future-proof as a side-bonus.

**Comment by ADmad** [comment]
We are all in agreement that automatically changed controller named based on model name was a bad idea. But that's not the issue sure. The problem is such a thing was done and people were relying on it, hence the wackiness should be restored.

**Comment by markstory** [comment]
@voycey Does the following test represent what was working in 2.7.7?

```php
/**
 * Test that the action key still uses the model as the implicit controller
 * when the url option is undefined.
 *
 * @return void
 */
	public function testCreateUrlImpliedController()
	{
		$this->Form->request['controller'] = 'posts';
		$result = $this->Form->create('Comment', array(
			'action' => 'addComment',
			'id' => 'addCommentForm',
			'type' => 'POST'
		));
		$expected = array(
			'form' => array(
				'action' => '/comments/addComment',
				'id' => 'addComment',
				'method' => 'post',
				'accept-charset' => strtolower(Configure::read('App.encoding'))
			),
			'div' => array('style' => 'display:none;'),
			'input' => array('type' => 'hidden', 'name' => '_method', 'value' => 'POST'),
			'/div'
		);
		$this->assertTags($result, $expected);
	}
```

This test fails both in `2.7.7` and current `2.x`. Did you by any chance use `null` as the model name? Not having a model name used to implicitly use the controller, but that's not what you described above.

**Comment by markstory** [comment]
Pull request up now.
