### ISSUE TITLE
Contains with deep hasOne or belongsTo asociations

### ISSUE THREAD

**Issue by DIDoS** [cakephp/cakephp#8629]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: 

### What you did
Having a "deep" hasOne and/or belongsTo association (e.g. Upload-belongsTo->User-hasOne->Profile) and querying the data with the help of containable (in Upload Model contain => ['User'=>['Profile']]).

### Expected Behavior
The DboSource recognises the first belongsTo relation (DboSource.php:1082) and joins the User Model correctly to the Upload Model. Though the next association is not checked recursively if it might be a hasOne or belongsTo Association. Expected: check the chain of hasOne or belongsTo associations to use joins.

### Actual Behavior
The first belongsTo association is joined the second hasOne association is queried (one select per row). Which is not very performance optimized (DboSource.php:1130).

**Comment by chinpei215** [comment]
@DIDoS It is difficult to fix without breaking backward compatibility.
I think my plugin would solve your issue.  I would be happy if you try it.
https://github.com/chinpei215/cakephp-eager-loader

**Comment by ADmad** [comment]
This a limitation of 2.x ORM which won't be fixed. (It's no longer an issue in 3.x).

**Comment by DIDoS** [comment]
@chinpei215 Cheers. I will give it a try.
