### ISSUE TITLE
Define constant for Config directory

### ISSUE THREAD

**Issue by ghost** [cakephp/cakephp#8630]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.3.
* Platform and Target: easy custom directory structure of project. With my project, it can move out all configuration informations from 'app' directory.

### What you did
To load a configuration file, current use `include APP . 'Config' . DS . 'config_file.php'`

### Expected Behavior
But if use CONFIG constant, only need `include CONFIG . 'config_file.php'`, and 'Config' directory can be moved out 'app' directory

### Actual Behavior
the 'Config' directory is fixed in 'app' directory

**Comment by ionas** [comment]
Well, if by default CONFIG is set to `APP . 'Config' . DS` then BC is given and I think I like it.
This would also require to be implemented in CakePHP 3.x
However to achieve whatever you want to do take a look at env loading.

**Comment by markstory** [comment]
What is stopping you from defining the necessary constant in your application?

**Comment by vinh014** [comment]
The CONFIG constant can be defined in the application but the Config directory can not moved out  from app Directory and renamed. Currently, the Config directory is fixed in app directory and can not be modified any thing.

In example,  the Config directory is moved up to root directory and renamed to 'config' (in lowercase).

```
project (root)
      app
      config
      lib
      plugins
      vendors
      ...
```

**Comment by markstory** [comment]
We don't allow moving directories around in general.

**Comment by jippi** [comment]
this can be done in userland :)

**Comment by vinh014** [comment]
It's ok.
There is an other small note which in `ShellDispatcher.php` file. See two code lines:
```
$boot = file_exists(ROOT . DS . APP_DIR . DS . 'Config' . DS . 'bootstrap.php');
require CORE_PATH . 'Cake' . DS . 'bootstrap.php';
```
The `$boot` variable currently is not used. If can, it should be removed. Otherwise, `ROOT . DS . APP_DIR . DS . 'Config' . DS` is replaced by new `CONFIG` constant.

**Comment by dereuromark** [comment]
Indeed, I am also not sure what that is doing here: https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Console/ShellDispatcher.php#L137
I think we can just remove it?
