### ISSUE TITLE
__call() for HtmlHelper

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8631]
I was thinking: why not add a `__call()` method for `HtmlHelper`?

Something like this:

	public function __call($method, $params) {
		if(count($params) <= 2) {
			return self::tag($method, $params[0], empty($params[1]) ? [] : $params[1]);
        }
		
		parent::__call($method, $params);
	}

**Comment by thinkingmedia** [comment]
I too would like this, but a white list of allowed tags would help safe guard future methods.

**Comment by mirko-pagliai** [comment]
1) have a list of allowed tags is difficult. Both because they are man and because with the new standards I can use the tags that I want;
2) do this:

    echo $this->Html->h19('hello!');

It is not different to do this:

    echo $this->Html->tag('h19', 'hello!');

In short, it would be a kind of alias. If the method `tag()` allows me to create the tags I want, I do not see why I could not do it so well.

**Comment by mirko-pagliai** [comment]
In other words: if we really need a list of allowed tags, then this must be in the `tag()` method and not here. But I think it still is wrong.

**Comment by thinkingmedia** [comment]
I would be happy with just adding more tags to the HtmlHelper and just call `tag()`. Things like `<div>` and `<span>` would be extra helpful.

**Comment by sdustinh** [comment]
This would be awesome to push all tag generation into the `tag()` method but would be tricky with the existing `style()`, `div()`, etc. method signatures. I would expect `$this->Html->div($content)` to behave like `$this->Html->tag('div', $content);`.

Maybe a way to handle standardizing the helper would be to give it the same treatment as the entity checking for a `_getDiv()` method or something like the widget system on the `FormHelper`? I'm all :+1: on this. The `HtmlHelper` has constantly been the most useful and most frustrating helper for me.

**Comment by markstory** [comment]
I could see this being useful if there was a whitelist of tags and we didn't try to handle automatically building URLs out of the related attribute keys.

**Comment by mirko-pagliai** [comment]
Wait, wait, wait. From PHP docs:

> __call() is triggered when invoking inaccessible methods in an object context.

So methods as `div()` or `link()` continue to work as always.

Of course, if I do something like this:

    echo $this->Html->a('my link', ['href' => 'site.com']);

is a bad idea, because it is better if I use the `link()` method.

But I can do this even now:

    echo $this->Html->tag('a', 'my link', ['href' => 'site.com']);

and this is just as wrong.

So, for now, this **is only an alias** of the `tag()` method. Just that this is much more direct and easier to read, because I can do something like:

    echo $this->Html->h1('Main title');
    echo $this->Html->h2('Subtitle');

(this is a right use)

So we do not need a whitelist, because the `tag()` method does not have a whitelist!

This is for now (eg 3.2.8).

**In the future** we can:

1. remove all useless methods (as `div()`);
2. standardize methods (I think it is wrong that some have a different order of arguments. This creates confusion);
3. centralize all methods, so that all pass through a single generic method. Eg:
`link()` calls `tag()`. `div()` is removed, but `__call()` allows me to use it anyway, calling `tag()`. `tag()` is a protected method.

But these are only scattered ideas...

**Comment by thinkingmedia** [comment]
I almost want to see this as a new helper. There would be no risk of future collision since this new helper would have only one usage (all methods are tags).

You could also do something creative by returning a chainable object instead of a string. That object would implement the `__toString` method and be aware of nesting.

Here is an example of what I'm saying.

```
   echo $this->Tag->h1()->span('Hello');
```

Would output this:

```
    <h1><span>Hello</span></h1>
```

This would also make it easier to create procedural links, or at least more readable close.

Right now you have to do this.
```
     $title = $this->Html->tag('span','Hello');
     echo $this->Html->link($title,$url, ['escapeTitle'=>true]);
```

Using a chainable object would make it possible to write this instead and escaping should not be required. Since only `<span>` has user input.

```
    echo $this->Tag->a($url)->span('Hello');
```

I guess when it is chained the content parameter is deferred to the last member of the chain.

I'm just thinking outside the box. :smile:

**Comment by ADmad** [comment]
I don't the idea of maintaining a whitelist of tags. It could potentially be a PITA to maintain. There are just too many HTML tags and every once in a while there will be someone trying to generate a tag not on the list and will end up cursing us and/or submitting an issue for it to added to the list.

**Comment by ADmad** [comment]
@thinkingmedia That's an interesting idea :smile:

**Comment by ADmad** [comment]
Terminating the chain with a `render()` would probably be easier to implement. Something like 

```php
echo $this->Tag
    ->a($url)
    ->span('Hello')
    ->render();
```

**Comment by thinkingmedia** [comment]
The return type of `a` and `span` would be a new object that implements `__toString`. `echo` would call that on the last object returned in the chain. So I assume `render` wouldn't be needed. Of course, you could just have `__toString` call `$this->render`.

I'm just thinking of more ideas, but what if you could access attributes using the array access?

```
   $div = $this->Tag->div($contents);
   $div['class'] = 'panel';
   $div['id'] = 'my-div';
   echo $div;

   // outputs
   <div id="my-div" class="panel">contents</div>
```

That could open up more programming possibilities.

You could also access `data` attributes using a data property.

```
   $div = $this->Tag->div($contents);
   $data->data['tooltip'] = 'This is helpful';
   echo $data;

   // outputs
   <div data-tooltip="This is helpful">contents</div>
```

**Comment by thinkingmedia** [comment]
Passing an array of these new objects would wrap those objects.

```
   $a1 = $this->Tag->a($url)->span('Menu 1');
   $a2 = $this->Tag->a($url)->span('Menu 2');
   $a3 = $this->Tag->a($url)->span('Menu 3');

   echo $this->Tag->ul()->li([$a1, $a2, $a3]);

   // outputs
   <ul>
     <li><a href="#"><span>Menu 1</span></a></li>
     <li><a href="#"><span>Menu 2</span></a></li>
     <li><a href="#"><span>Menu 3</span></a></li>
   </ul>

```

**Comment by mirko-pagliai** [comment]
This seems to me a great idea.

**Comment by markstory** [comment]
What is the advantage of having an HTML builder over just using static HTML strings/templates?

**Comment by burzum** [comment]
I agree with @markstory. If you look at @thinkingmedia last comment, this won't reduce the amount of code to write. The only benefit I can see here is that the php'ish implementation would avoid that you write wrong HTML by accident (typos).

If somebody really wants something like that he can use https://github.com/jameswatts/cake-toolkit This is exactly doing what @thinkingmedia proposes. What would need to be done there is to make it a framework agnostic lib + a CakePHP plugin. The actual HTML building is not tied to a framework IMHO. Alternatively just upgrade it to Cake3.

**Comment by jeremyharris** [comment]
I agree with @burzum here. Having worked with CTK myself I also agree it's a pain to read and write, so going down a similar path is a bad idea. When writing simple HTML becomes difficult, it's no longer a helper.

I think if people really want to write all their HTML with PHP, they can extend the helper or use a tool like CTK.

**Comment by ADmad** [comment]
The consensus seems to be that such a helper won't be much help :)  So let's close the issue.

**Comment by dereuromark** [comment]
I should first be built as plugin solution and can still be adapted later on in a minor cakephp version if it is becoming popular.

**Comment by thinkingmedia** [comment]
@dereuromark I agree with you on this. I also lost interested in making a PR for this.

**Comment by mirko-pagliai** [comment]
But, for now, adding the `__call()` method and leaving a new helper? :-)
