### ISSUE TITLE
Hash::contains should return true for empty needle

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#8632]
``` php
Hash::contains(['a'], []); //false
Hash::contains([], []); //false
```

This is contradictory to the mathematical definition to a subset. I currently don't see a reason why `contains` should work this way. (This bug might exist due to a mixup of `&&` and `||` [here](https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L554))

**Comment by markstory** [comment]
Changing this would mean that all datasets contain all empty needle values. I'm not convinced that this is a good idea.

**Comment by ADmad** [comment]
Making this change is also likely to affect existing apps.

**Comment by markstory** [comment]
Yes. It changes the behavior in a backwards incompatible way.

**Comment by thinkingmedia** [comment]
If this is important, and I don't think it is. You could add a third parameter called `strict` that enables this check, but you know it's just extra code that most people won't use.

**Comment by nrother** [comment]
I tried to use this code to detect if one user has all rights another user has, and this failed, when the first user did not had any rights. I found this very confusing. I might be interesting to find out how often this method is really called with `[]` for the second parameter and someone is really expecting this to return false. But this might be just me, as I'm from a kind-of-mathematical background.

I'd vote (at least) for a `strict` parameter.

**Comment by nrother** [comment]
FYI: Currently all tests pass with my proposed modification. Don't know what is about real-world-applications, though.

**Comment by markstory** [comment]
@nrother Sounds like we're missing a test case :smile:

**Comment by lorenzo** [comment]
Arrays are not sets in the mathematical definition, so this is completely counter intuitive to how the rest of the language works

**Comment by nrother** [comment]
@lorenzo Do you have an example of this "rest of the language"? A quick search only reveals `array_intersects`, which works the way I'd expected it to: `array_intersect(['a'], []); //[]`

Still can't come up with a use-case where the current behaviour is useful...

**Comment by lorenzo** [comment]
Yes this, for example:

```php
in_array([], ['a', []]); // true

in_array([], ['a']); // false
```

**Comment by nrother** [comment]
`in_array([], ['a', []]); // true` is a good point, but the import thing there is, that `in_array` threats the first parameter as a _single_ value to search for, so `[]` is just any kind of value. I expected `Hash::contains` as "check if every value from `$needle` can be found in `$haystack`". I now found that the [documentation](http://book.cakephp.org/3.0/en/core-libraries/hash.html#Cake\Utility\Hash::contains) says "Determines if one Hash or array contains the exact keys and values of another", which might be a slight different thing, as it does not say "contains all keys and value of another".

I found some other inconsistencies (IMHO) in the framework:
```php
Hash::numeric(['1']) //true
Hash::numeric([]) //false
collection(['1'])->every(function($item) {return is_numeric($item);}) //true
collection([])->every(function($item) {return is_numeric($item);}) //true
```
But this might be due to the fact that a collection is more a (mathematical) set than a hash. But somehow there seems to be a bit of confusion how to handle empty needles.

**Comment by lorenzo** [comment]
I agree the second collection example is a bug.

**Comment by nrother** [comment]
Ok, that was not what I wanted to reach :smile:. In the meantime I did some research:
```java
//Java
Arrays.stream(new int[] {1}).allMatch(x -> false); //false
Arrays.stream(new int[] {}).allMatch(x -> false); //true
```
```csharp
//C#
new int[]{1}.All(x => false); //false
new int[]{}.All(x => false); //true
```
```python
#Python
all([False for x in [1]]) #false
all([False for x in []]) #true
```
```php
//CakePHP (with 64669a9)
collection([1])->every(function() {return false;}) //false
collection([])->every(function() {return false;}) //false
```
That not what I'd expect as a developer! So for me #8670 clearly made the situation worse. and I could imagine that that even breaks someones code. (It would break mine).

**Comment by dereuromark** [comment]
Did the PR 8670 resolve the issue here?

**Comment by lorenzo** [comment]
From the a point of view, it did. OP's suggestion is that we conform to other collection implementations by adopting the mathematical definition of `every` for empty lists.

**Comment by dereuromark** [comment]
Do we want to address this for 4.0?

**Comment by markstory** [comment]
I think that would be our next opportunity to do it.

**Comment by othercorey** [comment]
I don't think there is anything to do here though.
