### ISSUE TITLE
bootstrap_cli.php does not load config.php for plugins

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8634]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: Apache 2, MySQL, PHP 7.0.5

### What you did

I have two plugins for my app. The first is called `Sync` and the second is called `TheMovieDB`. I need to be able to read the config of `TheMovieDB` from the shell task in `Sync`.

I added a file `plugins/TheMovieDB/config/config.php` that contains this:

```
   return [
        'TheMovieDB'=>[
               // ....
        ]
   ];
```

When I execute a shell that belongs to `TheMovieDB` the following will output the config.

```
     var_dump(Configure::read('TheMovieDB')); // <- works inside the plugin
```

Executing the same code in the `Sync` plugin dumps `null`.

### Expected Behavior

Added the following to the `app/config/bootstrap_cli.php` file should fix the problem.

```
    Plugin::load('TheMovieDB');
```

### Actual Behavior

Bootstrapping the plugin in the `bootstrap_cli.php` does not force the config to be loaded. Only the config for the currently executing plugin (in shell context) is loaded.

**Comment by ADmad** [comment]
`plugins/TheMovieDB/config/config.php` is a custom config file. Simply loading the `TheMovieDB` plugin isn't going to automatically load that config file. You need to explicitly load it using `Configure::load('TheMovieDB.config')`.
