### ISSUE TITLE
Switch language within plugins

### ISSUE THREAD

**Issue by Penergy** [cakephp/cakephp#8637]
This is a : feature-discussion (RFC)

* CakePHP Version: 3.1.0
* Platform and Target: LAMP

I tried to switch two language for the website. However, the url I implemented for plugin doesn't work. The example is like: 
www.example.com/en/users/users/profile (CakeDC/Users plugin)

However, I couldn't find any solution to access to the above link.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
