### ISSUE TITLE
Entities property hiding should work as property accessibility

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#8640]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.x.
- Platform and Target: irrelevant.
### What you did

i was playing around with Entity's hidden and accessible fields
### Expected Behavior

in my opinion Entity::_hidden should work as _accessible.

```
$_hidden = [
    'field1' => true,
    '*' => false
];
```

hide/unhide fields on the fly
$this->hide('field2', true);
$this->hide('field1', false);
### Actual Behavior

```
$_hidden = [
    'field1',
    'field2'
];
```

**Comment by markstory** [comment]
Why? Setting hidden = false seems redundant when it could just be elided from the list. What use cases does having hidden = false enable?

**Comment by lorenzo** [comment]
It would make possible to use '*` as a value, but I think this would be too difficult to implement in a backwards compatible way

**Comment by markstory** [comment]
So a very wide table where you have more hidden properties than visible ones?

**Comment by efanzini** [comment]
@markstory yes.
I usually block all the properties by default and then unlock just the one i need.

**Comment by lorenzo** [comment]
@markstory Yeah, that may be one of the cases

**Comment by efanzini** [comment]
should i try to code a new hiddenProperties ?

**Comment by ethanpooley** [comment]
Controlling property visibility (for arrays/JSON) via a whitelist rather than a blacklist would be a welcome security feature in my project. This is a place where we would appreciate the framework adding a layer of security against the leakage of sensitive data. We've been thinking about how it should be implemented, and I quite like this proposal from @efanzini.

**Comment by markstory** [comment]
@ethanpooley I'm not a huge fan of `hidden` containing false values. What if there was another property (`_visible`) that let you do a whitelist approach?  This new property could default to `*`, and the list of output fields would be calculated as `visible fields - hidden fields`.

**Comment by ethanpooley** [comment]
@markstory Oh. Yes I agree. I missed that this was integral to his approach. A `_visible` field operating as you suggest sounds great.

**Comment by dereuromark** [comment]
@ethanpooley Any interesting in providing a PR here for 3.next or 4.0?

**Comment by dereuromark** [comment]
Quite a stale ticket, anything to be done for e.g. 4.x? Or shall we close?
