### ISSUE TITLE
Easier integration with Let's Encrypt

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#8642]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Any
* Platform and Target: Apache

### Summary
Let's Encrypt is out of beta now.  I think we can all agree that more HTTPS is a good thing.  I'd like to suggest a modification to CakePHP to better support Let's Encrypt.

### Issue
The automated verification that the letsencrypt client does places a file at "/.well-known/acme-challange/filename", where filename is a name set by the letsencrypt verification process.  CakePHP redirects all requests to the webroot directory, which can interfere with this process.

Technically, it is possible to setup the let's encrypt client to place the challenge file structure in the webroot directory; however, many of the automated utilities that are coming out don't expose this setting.  You might argue that it's a failing of those utilities, but it's also an easy fix in CakePHP.

### Recommendation
Add lines to the top of the default htaccess such that it passes the request on to Apache, bypassing cakephp.

Add "RewriteRule ^(\\.well-known/.*)$ $1 [L]" as the first rewrite rule in the root htaccess and the app/.htaccess

### The .well-known directory
The ".well-known" directory is defined in RFC 5785.  Given my understanding of the RFC, I believe it's appropriate to expose the entire directory as suggested above.

**Comment by markstory** [comment]
Seems reasonable to me. Could you send a pull request to cakephp/app with the requested changes?

**Comment by markstory** [comment]
This issue was moved to cakephp/app#368
