### ISSUE TITLE
Notice error in Database\FieldTypeConverter.php

### ISSUE THREAD

**Issue by DinoSane** [cakephp/cakephp#8648]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: WAMP all new versions.

### What you did
Just run composer update 

### Expected Behavior
The project was working fine.

### Actual Behavior
After update all query execution cause debug.log

```
Notice: Notice (8): Undefined index: Categoria__id in [C:\...\vendor\cakephp\cakephp\src\Database\FieldTypeConverter.php, line 79]
```

An insert of

```
   if (isset($row[$field]))
```

just before the line 79

```
   if (isset($row[$field]))
       $row[$field] = $type->toPHP($row[$field], $this->_driver);
```

stopped the Notice as it should and no other consequence has been detected.

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by DinoSane** [comment]
I'm unable to reproduce. I create a brand new project with brand new tables and even with the old ones and nothing happened. My main project is are in production environment so it has lot of other stuff on it who may causing this (Crud for instance).

What I can tell is that the $row variable which was suppose to have an named array haven't.
For users table it is this

[1,"name@whatever","Full name of SomeOne"]

instead of the expected
['Users__id"=>[1,"name@whatever","Full name of SomeOne"]]

**Comment by lorenzo** [comment]
Are you still able to observe this problem? What's the code that is producing this issue?

**Comment by DinoSane** [comment]
Yes the problem is there. I will copy my project and cut it to the minimum to try to corner the "how to reproduce". For now I can tell you the call stack of when the problem occurs:

 Called from APP\vendor\cakephp\cakephp\src\Database\FieldTypeConverter.php:103
  1. Cake\Database\FieldTypeConverter->__invoke() -:-
  2. array_map() APP\vendor\cakephp\cakephp\src\Database\Statement\CallbackStatement.php:71
  3. Cake\Database\Statement\CallbackStatement->fetchAll() APP\vendor\Aplicar\src\bootGrid.php:284

            $res['rows'] = $this->query
                                ->order($this->query->newExpr()->add($this->getOrderBy()))
                                ->limit($_REQUEST['rowCount'])
                                ->page($res['current'])
                                ->execute()
                                ->fetchAll();

**Comment by markstory** [comment]
Any ideas on how someone can reproduce this issue? Are there any other result decorators or beforeFind callbacks that unselect fields? or remove fields from result set?

**Comment by markstory** [comment]
Closing as we don't have a way to reproduce this and there have been no further reports.

**Comment by felipevr** [comment]
I am experiencing the same problem at the lastest cakephp version (3.3.11), runing on php 5.5

**Comment by felipevr** [comment]
It happens when the table name plus the column name is larger than 64 characters.
I don't know why Cake truncate the name at 64 characters.
The solution I found was to reduce the name of the column.

**Comment by felipevr** [comment]
Aparently the postgresql is truncating the identifier =/

**Comment by DinoSane** [comment]
I just update from cakephp 3.1 to 3.4 and the problem persists. But now I found out what happens:

when FieldTypeConverter.__construct is ran the $typeMap provided contains all fields from model. 

Later, if you execute a query (of the same model, of course) with any less fields on select, the FieldTypeConverter.__invoke use the previously filled $this->_typeMap which has some field info that is not in $row var.

So:

**What you did**
	this->query
		->select([less,fields,than,all] ,true)
		->execute()
		->fetchAll()
**Expected Behavior**

all rows with the fields less,fields,than,all

**Actual Behavior**

Notice: Notice (8): Undefined index: **_AnyFieldLeftOutOfSelection_** in [C:\...\vendor\cakephp\cakephp\src\Database\FieldTypeConverter.php, line 79]

fixed adopted:
    public function __invoke($row)
    {
        foreach ($this->_typeMap as $field => $type) {
            **if (isset($row[$field]))**
                $row[$field] = $type->toPHP($row[$field], $this->_driver);            
        }
        return $row;
    }

**Comment by markstory** [comment]
Are you re-using the query objects for 2 different selects?

**Comment by DinoSane** [comment]
Well, yes but with the proper overwrite value

	this->query
		->select([less,fields,than,all] ,**true**) 
		->execute()
		->fetchAll()

**Comment by markstory** [comment]
Not sure you should be re-using queries in general. We have no testing our guarantees that will ever work as you may expect.
