### ISSUE TITLE
CakeFixtureManager: Don't use transactions to load fixtures

### ISSUE THREAD

**Issue by Mensler** [cakephp/cakephp#8652]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.11
* Platform and Target: Apache, MySQL, Master-/Slave replication, PHPUnit tests

### What you did
Running PHPUnit tests with fixtures.

### Expected Behavior
Using transactions (BEGIN/COMMIT) only for the INSERT statements in fixture loading so no replication lag is caused.

### Actual Behavior
Loading fixtures is done in one big transaction, as begin() is called before CREATE TABLE, TRUNCATE and INSERTs (CakeFixtureManager::load()). This causes replication lags. Additionally CREATE TABLE and TRUNCATE are not transaction safe (at least in MySQL). The INSERT statements are done in one transaction anyways by DboSource::insertMulti(), which is OK.

[CakeFixtureManager.patch.txt](https://github.com/cakephp/cakephp/files/219548/CakeFixtureManager.patch.txt)

**Comment by markstory** [comment]
I don't think removing the transaction is an option. Removing the transaction would cause tables with foreign key constraints to not work in mysql.

**Comment by Mensler** [comment]
Hmm, moving the begin() after the truncate() would also solve the replication lag problem. But I think even this isn't necessary because of the begin/commit in insertMulti().

**Comment by markstory** [comment]
Moving the begin after truncate might work. While schema changes are not transactional in mysql, they are in postgres and sqlserver.

**Comment by bancer** [comment]
Having in mind that insertMulti() uses a single query to insert many records in MySQL (the recent [changes](https://github.com/cakephp/cakephp/pull/9412/files)) the insertion of records may require no transaction I think. At least in MySQL.

**Comment by markstory** [comment]
@bancer True. I'm going to close this out.
