### ISSUE TITLE
FormHelper::unlockField can't unlock fileds, when call after the FormHelper::input

### ISSUE THREAD

**Issue by nojimage** [cakephp/cakephp#8654]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x

### What you did

I want to get multiple checked data, like this

```
[
    'Foo' => [
    	'checkbox' => [
    		'11', '22', '33', ...
    	]
    ]
]
```

and I write the view template file, like this

```
$this->Form->unlockField('Foo.checkbox');
$this->Form->input('Foo.checkbox.');
$this->Form->input('Foo.checkbox.'); // <-- Correct, unlocked Foo.checkbox.
```

But, when I write unlockField() after input(), the unlockField can't unlock.

```
$this->Form->input('Foo.checkbox.');
$this->Form->input('Foo.checkbox.');
$this->Form->unlockField('Foo.checkbox'); // <-- Wrong, Can't unlock Foo.checkbox.
```

If the writing of the above, I know that there is no problem. but I want to be able to unlock write as the below.

**Comment by nojimage** [comment]
test code
https://gist.github.com/nojimage/96fe19932ce8ed8aaf8292327565b36c

**Comment by markstory** [comment]
@nojimage Would you be willing to put together a pull request for this? We already have a similar feature in 3.x that you could base your patch off of.

**Comment by nojimage** [comment]
OK, I'll try it.

**Comment by markstory** [comment]
:+1: If you need help let me know.

**Comment by markstory** [comment]
Pull request up now.
