### ISSUE TITLE
Compare two fields: WHERE table1.field1 > table2.field2

### ISSUE THREAD

**Issue by flashios09** [cakephp/cakephp#8655]
This is a:
* [x] bug

* CakePHP Version: 3.1.13

I want to compare two fields 
```sql
    ...
    WHERE
       table1.field1 > table2.field2
```
Using an array like this 
```php
->where(['Table1.field1 >' => 'Table2.field2'])
``` 
or a query expression like this
```php
->where(function($q){
   return $q->gt('Table.field1', 'Table2.field2');
})
```
The value is always treated as **string** not a **field**
this is the generated sql
```sql
   ...
  WHERE table1.field1 > 'table2.field2'
```

**Comment by jeremyharris** [comment]
At the bottom of the [Advanced Conditions][1] section there is an example on comparing fields. It should look something like this:

    ->where(['Table1.field1 > Table2.field2'])

[1]: http://book.cakephp.org/3.0/en/orm/query-builder.html#advanced-conditions

**Comment by flashios09** [comment]
@jeremyharris it's not possible using **gt** query expression ?

**Comment by jeremyharris** [comment]
I believe it is with the `$type` key but I can't quite remember how, and can't find it in the docs. If you do find out how in IRC or something, a PR to the docs would be really helpful!

**Comment by markstory** [comment]
You can do with with `IdentifierExpression`. I didn't include that example as its more complex, and could potentially lead to unsafe code as putting user data into IdentifierExpression() is a good way to have SQL injection holes.
