### ISSUE TITLE
Array fields validation

### ISSUE THREAD

**Issue by NoczCore** [cakephp/cakephp#8664]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

**Hello,**
I want to validate a form with the validation system, but the form is **particularly**.

**The form looks like this:**
```
<?php for($i = 0; $i < 3; $i++): ?>
    <?= $this->Form->input('players.'.$i.'.name']); ?>
    <?= $this->Form->input('players.'.$i.'.start_price'); ?>
    <?= $this->Form->input('players.'.$i.'.buy_price'); ?>
<?php endfor; ?>
```

But this is **not a hasMany relationship**, this is stored in JSON.

**I tried to like this:**
 ```
$validator->add('players[].name', [
    'length' => [
        'rule' => ['minLength', 4]
    ]
]);
```

How to do ? Do you have a solution ?

Thank you.

**Comment by lorenzo** [comment]
Did you read this? http://book.cakephp.org/3.0/en/core-libraries/validation.html#nesting-validators

**Comment by NoczCore** [comment]
Yes, but i've not tried this. Now, i've tried and this is work (I've error in `$entity->errors()`), however this do not show error in form, unlike other fields that show their error.

Thanks for your help,
Sorry for my bad english.

**Comment by lorenzo** [comment]
For entities I would suggest using validators in associations. For example if you have a Players table, you can add the validation in that class and it will work automatically.

**Comment by NoczCore** [comment]
Okay, thanks for your help and your reactivity.
