### ISSUE TITLE
please merge pr #7867 in 3.0

### ISSUE THREAD

**Issue by eAliwei** [cakephp/cakephp#8666]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.0.18.
* Platform and Target: PHP 7.0.5 Memcached

### What you did
config session save in memcached

https://github.com/cakephp/cakephp/pull/7867

**Comment by markstory** [comment]
@eAliwei The 3.0.x branch is only receiving security fixes now. That pull request was merged into 3.1.6. You will either need to upgrade or backport that fix yourself.
