### ISSUE TITLE
CSRF token failures in production

### ISSUE THREAD

**Issue by NoczCore** [cakephp/cakephp#8668]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Hello,

I put my app in production, however I have the **odd bug**.

**Versions:**
- CakePHP 3.2
- PHP 5.6

When I **submit** a form, I have the **exception** ```Cake\Network\Exception\InvalidCsrfTokenException``` with the message:

> Missing CSRF token cookie

A second bug, when there is a **redirect** I obtien a **blank page**.

Would you have a solution?

I remain at your disposal for any questions.
Sorry for my bad English.

Good bye !

**Comment by markstory** [comment]
How is this an issue with CakePHP? How can someone reproduce your issue?

**Comment by NoczCore** [comment]
I do not know if it comes from CakePHP, not necessarily because I do not have that worry on my docker machine. I realize an issue to have any tracks because I have an error message telling me what the problem originates.

Thanks you.

**Comment by ADmad** [comment]
None of your issues sound like a bug in CakPHP but rather developer / user errors. 

Use one of the resources listed below to get help fix your problems:

[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
or the #cakephp channel on irc.freenode.net

Thanks!
