### ISSUE TITLE
Make Table::findOrCreate() more flexible

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#8671]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
Wanted to implement [findOrCreate()](http://api.cakephp.org/3.2/source-class-Cake.ORM.Table.html#1222) and realized it is limited on customizing the find() call.

### Expected Behavior
I would like to be able to define my own finder or query object.

### Actual Behavior
I can only pass conditions, not define contains or use a finder as first arg.

### Suggestion
Allow the first arg to be a query object or a string that is used as a finder.

The only problem I see is that the method has just 2 args for now, but it would be useful to have another one to pass something to the options of the finder.

**Comment by lorenzo** [comment]
Would you like to submit a pull request for this?

**Comment by burzum** [comment]
I can do that, but you know that I'll never write code before discussing it to avoid wasting my time with something that is not accepted at the end. :smile:

**Comment by markstory** [comment]
Isn't a query object 'better' than a finder?

```php
$articles->findOrCreate($articles->find('published'), function () { ... });
```

**Comment by jhli** [comment]
- what about a 'orCreate()' that picks up a query object?
- why is it named findOrCreate when it implies ->first() - should it be getOrCreate()?
- finder option is consistent with how get() work, right?

**Comment by burzum** [comment]
@markstory I'm OK with just the query object as well, just one question: How do we pass the search conditions then? Maybe like this?

> findOrCreate($queryObject, $search, callable $callback = null)

And make the search optional? The problem I ran into in my case was that the $search is used for the entity / save as well but that I had to prefix the fields with the alias, which then made the entity fail. So I ended up with doing this in my case.

```php
		$project = $this->Projects->findOrCreateProject([
			'Projects.is_draft' => true,
			'Projects.company_id' => $companyId,
			'Projects.profile_id' => $profileId
		], function($entity) use($companyId, $profileId) {
			$entity->name = '';
			$entity->is_draft = true;
			$entity->profile_id = $profileId;
			$entity->company_id = $companyId;
		});
```

**Comment by markstory** [comment]
Closing as the proposed changes are in a pull request form.
