### ISSUE TITLE
newEntity() with associations ignoring associations' ID fields and tries to create new child record

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8672]
This is a (multiple allowed):
* [x] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

I have found (what I think) a simmilar issue here:
https://github.com/cakephp/cakephp/issues/5862

What i want to do is to create a "history" of record modification. So basicly what I want is to copy some fields from the original entity along with some associations. 

``$applicant` - entity to "copy"`

How I wanted to do it:
`  $archived = $this->ManualApplicantArchives->newEntity($applicant->toArray(), ["associated"=>["Countries"]]);`

 but this does not work, as marshalled dependency - `country` in this case - is marked as "new" causing unique validation errors thus resulting in error on save.

How I am doing it right now:
```
            $archived = $this->ManualApplicantArchives->newEntity($applicant->toArray(), ["associated"=>["Countries"]]);
            $archived->country=$applicant->country;
```
portion of ManualApplicantArchivesTable mapping: 
```
        $this->belongsTo('Countries', [
            'foreignKey' => 'country_id'
        ]);
```
ManualApplicantArchives entity :
```
    protected $_accessible = [
        'address' => true,
        'city' => true,
        'name' => true,
        'zipCode' => true,
        'vat' => true,
        'country' => true,
//        '*'=>true,
    ];

```
this seems to be working as well

`$archived = $this->ManualApplicantArchives->newEntity($applicant->toArray(), ["associated"=>["Countries"=>["validate"=>false]]]);`
 I am not sure if this is a bug, intended behavior or I am doing something wrong.

Result of newEntity:
```
object(App\Model\Entity\ManualApplicantArchive) {

	'address' => 'Kennemerstraatweg 117',
	'city' => 'ALMSDASddasdasdsdasdadadgddfggdasfafsasfaaaaa',
	'name' => 'Alpha Hypotheken B.V.',
	'zipCode' => '1814 GE',
	'vat' => null,
	'country' => object(App\Model\Entity\Country) {

		'id' => (int) 21,
		'name' => 'Niederlande',
		'polishName' => 'Niderlandy',
		'englishName' => 'Netherlands',
		'dateFormat' => 'd-m-Y',
		'locale' => '',
		'[new]' => true,
		'[accessible]' => [
			'*' => true,
			'id' => true
		],
		'[dirty]' => [
			'id' => true,
			'name' => true,
			'polishName' => true,
			'englishName' => true,
			'dateFormat' => true,
			'locale' => true
		],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [
			'iso3166' => [
				'unique' => 'The provided value is invalid'
			]
		],
		'[invalid]' => [
			'iso3166' => 'NL'
		],
		'[repository]' => 'Countries'
	
	},
	'[new]' => true,
	'[accessible]' => [
		'address' => true,
		'city' => true,
		'name' => true,
		'zipCode' => true,
		'vat' => true,
		'country' => true
	],
	'[dirty]' => [
		'address' => true,
		'city' => true,
		'name' => true,
		'zipCode' => true,
		'vat' => true,
		'country' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [
		'isModifiedVat' => [
			'_required' => 'This field is required'
		]
	],
	'[invalid]' => [],
	'[repository]' => 'ManualApplicantArchives'

}
```

**Comment by markstory** [comment]
Why are you copying the country instead of just the ID? `newEntity()` is doing what its supposed to. Which is marking request data as 'new'. Because you've cast the association into an array, the ORM loses track that the country already exists in the database.

**Comment by Antoniossss** [comment]
So in general I should not assign whole managed object, only its _id and ommit "associated" marshalling in `newEntity()` call? 

Maybe in future releases `newEntity()` could accept entity interface do to a copy of  matching properties. This way such relations would not be lost.

**Comment by markstory** [comment]
@Antoniossss newEntity() is for marshalling request data into objects. How would request data contain entities?

**Comment by Antoniossss** [comment]
So this would be a feature request to mass assign fields in one entity with
covering properties of another covering including present associations as
well.
19 kwi 2016 19:25 "Mark Story" <notifications@github.com> napisał(a):
