### ISSUE TITLE
Deep associations not constructing database queries as expected

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8679]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: PHP 5.6.10 MAMP

### What you did
As discussed at the bottom of #8486, the PR #8354 was supposed to remove the need to override the `Table::table()` method, which is used primarily to prepend the database name to the table name. The PR *almost* works as expected, except when dealing with deep contains. Consider this:
```
$posts = TableRegistry::get('Posts')
    ->find()
    ->contain(['Tags' => ['TagsTranslations']])
    ->limit(4);
```
1. The `posts` table is in the `posts` DB, `tags` and `tags_translations` are in the `tags` DB.
2. The main query is on `posts`.
3. `tags` properly gets prepended with `tags`, so the query uses `tags.tags`.
4. `tags_translations` gets no prefix, so MySQL thinks it's in the `posts` DB.

### Expected Behavior
Any and all tables should be checked to exist in the main DB. If not, they should get auto-prefixed. (Although I still don't know why everything can't just be prefixed always since that would be valid... obviously not BC but maybe for a major version bump?)

### Actual Behavior
Query errors out since the query isn't constructed with the proper DB names when dealing with deep contains.

**Comment by markstory** [comment]
Does the `TagsTranslations` model correctly define its table? And is the concrete table class being used?

**Comment by patrickconroy** [comment]
Yeah the `TagsTranslations` table has the correct `defaultConnectionName`, and it's definitely using the concrete table class, since I can override that specific `table` method with the full DB+table path and it works.
I removed everything from the `Tables` themselves to make it easier to debug, and got it down to this:

```
$this->Videos->belongsTo('Games');
$this->Videos->Games->hasOne('GamesTranslations', ['foreignKey' => 'id']);
$videos = $this->Videos
    ->find()
    ->contain(['Games' => ['GamesTranslations']])
    ->limit(1);
pr($videos->toArray());
```
``Base table or view not found: 1146 Table 'videos.games_translations' doesn\u0027t exist"``

**Comment by markstory** [comment]
I'm assuming that if `Games` is the root table, the `GamesTranslation` association uses the correct table?

**Comment by patrickconroy** [comment]
Well, since `games` and `games_translations` are in the same DB, the query doesn't prepend the DB name. If I change the 1st-level contain to be in another DB, it prepends the correct DB.

Since the `foreignKey=id` field exists in both `VideosTranslations` and `GamesTranslations`, this doesn't error out, and shows that the contain works as expected.
```
$this->Games->hasOne('VideosTranslations', ['foreignKey' => 'id']);
$foo = $foo = $this->Games  
    ->find()
    ->contain(['VideosTranslations'])
    ->limit(1);
pr($videos->toArray());
```

**Comment by markstory** [comment]
Ok. I bet that the prefix is being elided in the deep association as Games and GamesTranslations are in the same database as well :smile:

**Comment by patrickconroy** [comment]
I think that's the case, @markstory. It seems to check if it's in the same DB as its parent, when it should be checking the main table's DB.

**Comment by lorenzo** [comment]
@Marlinc Would you like to take a stab at this, given that you are the author of the CrossSchema feature?

**Comment by patrickconroy** [comment]
Just pinging this. I can try to help if @Marlinc doesn't have time..

**Comment by patrickconroy** [comment]
I guess I'll take a stab / open a PR for this.

**Comment by Marlinc** [comment]
Wait, I haven't even seen I was mentioned in this issue. I wish I got a special email in that case. I'm sorry for replying this late.

**Comment by lorenzo** [comment]
Ping @patrickconroy @Marlinc

**Comment by patrickconroy** [comment]
Sorry, this summer has been pretty crazy, plus just got back from vacation..
So, 3.3.0 is broken because of this. The deep contain doesn't have a prefix so the query is assuming it's in the same DB as the main query.. and I can't override the `table` method since the table doesn't know where in the query it's being inserted.
@Marlinc where would you suggest I start?

**Comment by patrickconroy** [comment]
To get this to break, do this (my earlier examples might be messy):
```
$m = TableRegistry::get('MarqueeItems');
$m->belongsTo('Videos');
$m->Videos->belongsTo('Games');
$m->Videos->Games->hasOne('GamesTranslations');
$items = $m->find()->contain(['Videos' => ['Games' => ['GamesTranslations']]])->limit(4);
pr($items->toArray());
die();
```

1. MarqueeItems, Videos, and Games are all in their own DB and have their own `defaultConnectionName`.
2. GamesTranslations is in the Games DB, and that Table class has the correct `defaultConnectionName`.
3. The query this makes is ``
SELECT `MarqueeItems`.*, `Videos`.*, `Games`.*, `GamesTranslations`.*
FROM `marquee_items` `MarqueeItems`
LEFT JOIN `videos`.`videos` `Videos` ON `Videos`.`id` = (`MarqueeItems`.`foreign_key`)
INNER JOIN `games`.`games` `Games` ON `Games`.`id` = (`Videos`.`game_id`)
LEFT JOIN `games_translations` `GamesTranslations` ON `Games`.`id` = (`GamesTranslations`.`game_id`)
WHERE MarqueeItems.deleted IS NULL
ORDER BY `MarqueeItems`.`priority`
LIMIT 4``
4. `games_translations` needs a prefix, it should be `games`.`games_translations`.

**Comment by markstory** [comment]
Closing as the CrossSchemaTableExpression was removed.

**Comment by patrickconroy** [comment]
Thanks @markstory, I really wanted this to work.

**Comment by markstory** [comment]
I did too, but as with many magic features they have lots of bothersome scenarios that don't always work right.
