### ISSUE TITLE
Rendering radio inputs individually

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#8681]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)

CakePHP 3.2.

Sometimes I need to render radio buttons at different places in the page, instead of rendering them all together I need to put some content between them.

I'd like to do it using the FormHelper to avoid rewriting functionality. I've managed doing it by calling FormHelper::input() once for every radio button passing the same field name and just one item in options. I think using FormHelper::radio() would get me the same. But this feels clunky:

``` php
...
$this->Form->input('field', ['type' => 'radio', 'options' => [1]]);
...
$this->Form->input('field', ['type' => 'radio', 'options' => [2], 'hiddenField' => false]);
...
```

I've thought about using templates. The resulting HTML would be a bit different but still more flexible than now and would be good for most cases while easier to get right.  This is an example with very simple content:

``` html
<div class="input radio">
  <label>
    <input type="radio" name="field" value="1">
    My option
  </label>
  <p>this is some more content</p>
  <label>
    <input type="radio" name="field" value="2">
    My other option
  </label>
  <p>this is some other content different thant the previous one</p>
</div>
```

The added content can change for every radio button, so I'd need to be able to use different templates or using template variables per item. The item list can already be an array comprised of value, label and attributes, I'm thinking about adding a temporary templates option to that array and/or template variables:

``` php
// Changing templates
$this->Form->input('field', ['type' => 'radio', 'options' => [
  ['value' => 1, 'label' => 'My option', 'templates' => ... ],
  ['value' => 2, 'label' => 'My option', 'templates' => ... ],
]]);
// Using template variables
$this->Form->input('field', ['type' => 'radio', 'options' => [
  ['value' => 1, 'label' => 'My option', 'templateVars' => [...]],
  ['value' => 2, 'label' => 'My option', 'templateVars' => [...]],
]]);
```

Is there some other way?

EDIT: changed structure a bit to better explain what I've tried.

**Comment by markstory** [comment]
Any reason you're not using the `radio()` method?

**Comment by berarma** [comment]
No reason. I think I could do exactly the same using the `radio()` method, but I don't see any advantages.

**Comment by markstory** [comment]
Well its 'another way' to do what you want. Given that you can create inputs individually, and use templates/templateVars I'm not sure what you would like to see added.

**Comment by berarma** [comment]
I couldn't find how to create inputs individually with the `radio()` method. I'm sorry if I'm missing something obvious.

**Comment by markstory** [comment]
@berarma I was incorrect about radio() making it easier to generate a single radio button. You would still need to slice out options one by one.

**Comment by andruhapx** [comment]
It seems to be partially implemented regarding to [documentation](https://book.cakephp.org/3.0/en/views/helpers/form.html#checkbox-radio-select-options):
```
echo $this->Form->radio(
    'favorite_color',
    [
        ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
        ['value' => 'u', 'text' => 'Blue', 'style' => 'color:blue;'],
        ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
    ]
);
```
Also it should support 'label' options array for each options item:
```
echo $this->Form->radio(
    'favorite_color',
    [
        ['value' => 'r', 'text' => 'Red', 'label' => ['style' => 'color:red;']],
        ['value' => 'u', 'text' => 'Blue', 'label' => ['style' => 'color:blue;']],
        ['value' => 'g', 'text' => 'Green', 'label' => ['style' => 'color:green;']],
    ]
);
```
