### ISSUE TITLE
Fixtures manually loaded don't remove generated tables by default

### ISSUE THREAD

**Issue by c88lopez** [cakephp/cakephp#8683]
In my test setUp methods I have this:

```
$this->fixtureManager = new CakeFixtureManager();
$this->fixtureManager->fixturize($this);

$this->loadFixtures('Feed');
```

but the generated tables by the fixture are not being dropped when the test ends.

I have made a quick edit in CakeFixtureManager class by adding a destructor which calls the method 'shutDown' which solves this behavior.

If you think this approach is correct, I will make a pull request. Otherwise a hint will be great.

Thanks in advance.

**Comment by markstory** [comment]
Why are you creating a new instance of the fixture manager in your tests?

**Comment by c88lopez** [comment]
@markstory I didn't found a suitable way to do it clearner:

In order to run all my test, I've made an AllTest class where which it's only method 'suite' add each directory where test files are. For some reason i didn't understand, fixtures defined in the array property 'fixtures' weren't loaded, but in this way it works.

The AllTest class:

```
public static function suite()
    {
        $suite = new CakeTestSuite('All Tests');

        $suite->addTestDirectory(TESTS . 'Case/Model');
        $suite->addTestDirectory(TESTS . 'Case/Lib');
        $suite->addTestDirectory(TESTS . 'Case/Controller');
        $suite->addTestDirectory(TESTS . 'Case/Console/Command');

        return $suite;
    }
```

By running `Console/cake test app All`, all test in those folders will be executed.

**Comment by markstory** [comment]
Are you defining the fixtures on the 'suite' class? Fixtures can't be defined on a suite and instead need to be defined on each and every test case.

**Comment by c88lopez** [comment]
No, each test defines the fixture it actually needs. A class example:

```
class RobotTest extends CakeTestCase
{
    /**
     * fixtures to load
     * @var array
     */
    public $fixtures = [
        'Alert',
        'AlertsSource', 'Source',
        'AlertFrequency',
        'AlertLog',
    ];

    ...

}
```

The 'suite' class only has that method, none properties.

**Comment by markstory** [comment]
Ok. Then I'm confused as to why your fixtures aren't automatically being loaded and having their records inserted. You should never have to manually load fixtures. Do you happen to set `autoFixtures` to false in your test cases?

**Comment by c88lopez** [comment]
I understand that being the fixture loaded in my setUp method of my test case class is enough to get the table created, but, as this operation is manual, the drop should be manual as well... the `autoFixtures` property is not overrided.

I will make some more research to have a full aknowledge of this behaviour.

Leaving this scenario for a second, which problems or bad design topic do you find?

Thanks!!

**Comment by markstory** [comment]
> Leaving this scenario for a second, which problems or bad design topic do you find?

Generally the proposed destructor is not necessary as the test harness handles cleaning up fixture records and fixture schema automatically. You might want to look at `CakeFixtureManager::load()` and `CakeFixtureManager::unload()` to figure out why the automatic fixture management isn't working for you.
