### ISSUE TITLE
Make Date::jsonSerialize() consistent with ISO8601

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#8688]
As described in cakephp/chronos#93 the default JSON encode format should be compatible with ISO-8601, and not the approximate format it is using now.

Targeting this for `3.next` as changing the default format requires communication to developers as they might not want to have their date formats changed.

**Comment by ADmad** [comment]
Seems you missed PR #8685 I have already opened earlier today :)

**Comment by markstory** [comment]
I totally did.
