### ISSUE TITLE
Validate new mastercard credit card numbers

### ISSUE THREAD

**Issue by psaintjust** [cakephp/cakephp#8690]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x, 3.x
* Platform and Target: n/a

### Expected Behavior
Correctly validate new Mastercard credit card BIN numbers.  The new cards will be starting with range (222100-272099) and are effective October 2016.
Link with additional details: https://www.forte.net/blog/mastercard-bin-range-coming/

### Actual Behavior
Validation regex for mc ('/^5[1-5]\\d{14}$/') only validates existing range (510000-559999).
2.x: Cake\Utility\Validation.php
3.x: Cake\Validation\Validation.php

**Comment by ADmad** [comment]
Would you like to submit a fix for this?

**Comment by dereuromark** [comment]
This should also be ported to https://github.com/cakephp/localized then. As the other two are somewhat deprecated.

**Comment by ADmad** [comment]
Credit card numbers validation isn't region specific, don't see why it needs to go into localized plugin.

**Comment by dereuromark** [comment]
Ah you are right.
