### ISSUE TITLE
[2.X] Create fixture with option --schema, -s  not working

### ISSUE THREAD

**Issue by kittinan** [cakephp/cakephp#8693]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: Ubuntu, Nginx, Mysql, PHP 5.5.9

### What you did
I want to create Fixture from command line without interactive mode and need to import schema from Model but  option --schema, -s dose not work for me.  Interactive mode work very well

Example command : 

```bash
app/Console/cake bake fixture employee -s -r -n 100
```

### Expected Behavior
Create fixture with import model.

### Actual Behavior
Option -s not do anything

**Comment by markstory** [comment]
Pull requests open now.
