### ISSUE TITLE
Call to a member function format() on a non-object

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#8697]
My CakePHP 's version is 3.2.7
My TableClass:
```php
class TopicsTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('Timestamp');
     }
}
```

Then,  run this code throw error:
```php
<?php echo $topic->created->format('Y-m-d H:i:s')?>
```
Error: Call to a member function format() on a non-object 

why?

**Comment by markstory** [comment]
Is the created field null?

**Comment by macnie** [comment]
@markstory  the created field not null. 

Very strange!

display this error's server is ubuntu 14.04, php version 5.5.9

but run my windows ,it's run ok !

my windows install wampserver.  php version is 5.5.12

**Comment by macnie** [comment]
The problem is solved.

**Comment by slince** [comment]
@macnie  请问这个问题你是怎么解决的

**Comment by macnie** [comment]
你的是什么问题？@slince

**Comment by slince** [comment]
Error: Call to a member function format() on null 
File E:\www\slshop\vendor\cakephp\cakephp\src\I18n\DateFormatTrait.php 
Line: 226


```
'modified_at' => object(Cake\I18n\FrozenTime) {

		'time' => '2017-08-23T14:03:43+08:00',
		'timezone' => 'Asia/shanghai',
		'fixedNowTime' => false
	
	},
```
这个字段在json encode之后就报了上面那个错，跟你的问题原因应该是一致的

**Comment by macnie** [comment]
你的Cake版本号？

**Comment by slince** [comment]
3.4.13

**Comment by macnie** [comment]
@slince 我的原因是因为3.2版本不支持format方法。不是你这个问题。3.4支持format方法的。可能是你modified_at->format()，就不是一个对象。

**Comment by slince** [comment]
是的 大概是创建datefmt_create 失败了； 算了 提了个问题 看看他们给不给解答

**Comment by macnie** [comment]
你的问题描述的不清楚。不是太好判断。建议你说清楚你的问题来龙去脉，多贴代码。 
 
------------------ 原始邮件 ------------------
发件人: "Taosikai"; 
发送时间: 2017年8月23日(星期三) 下午2:54
收件人: "cakephp/cakephp"; 
抄送: "macnie"; "Mention"; 
主题: Re: [cakephp/cakephp] Call to a member function format() on anon-object (#8697)

 

是的 大概是创建datefmt_create 失败了； 算了 提了个问题 看看他们给不给解答
