### ISSUE TITLE
Cakephp 3 - 'Find where id' does not work

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#8700]
use Cake\ORM\TableRegistry;

**This works**
$shortInfos = TableRegistry::get('ShortInfos');
$shortInfo = $shortInfos->get(1);

**This does not work**
$shortInfos = TableRegistry::get('ShortInfos');
$shortInfo = $shortInfos
    ->find()
    ->where(['id' => 1])
    ->first();

**A text error**
Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous 
SELECT ShortInfos.id AS `ShortInfos__id`, ShortInfos.title AS `ShortInfos__title`, ShortInfos.text AS `ShortInfos__text`, ShortInfos.doc1 AS `ShortInfos__doc1`, ShortInfos.position AS `ShortInfos__position`, ShortInfos_title_translation.id AS `ShortInfos_title_translation__id`, ShortInfos_title_translation.locale AS `ShortInfos_title_translation__locale`, ShortInfos_title_translation.model AS `ShortInfos_title_translation__model`, ShortInfos_title_translation.foreign_key AS `ShortInfos_title_translation__foreign_key`, ShortInfos_title_translation.field AS `ShortInfos_title_translation__field`, ShortInfos_title_translation.content AS `ShortInfos_title_translation__content`, ShortInfos_text_translation.id AS `ShortInfos_text_translation__id`, ShortInfos_text_translation.locale AS `ShortInfos_text_translation__locale`, ShortInfos_text_translation.model AS `ShortInfos_text_translation__model`, ShortInfos_text_translation.foreign_key AS `ShortInfos_text_translation__foreign_key`, ShortInfos_text_translation.field AS `ShortInfos_text_translation__field`, ShortInfos_text_translation.content AS `ShortInfos_text_translation__content` FROM short_infos ShortInfos LEFT JOIN i18n ShortInfos_title_translation ON (ShortInfos_title_translation.model = :c0 AND ShortInfos_title_translation.field = :c1 AND ShortInfos_title_translation.locale = :c2 AND ShortInfos.id = (ShortInfos_title_translation.foreign_key)) LEFT JOIN i18n ShortInfos_text_translation ON (ShortInfos_text_translation.model = :c3 AND ShortInfos_text_translation.field = :c4 AND ShortInfos_text_translation.locale = :c5 AND ShortInfos.id = (ShortInfos_text_translation.foreign_key)) WHERE id = :c6 LIMIT 1

Why? Am I doing something wrong?

**Comment by ADmad** [comment]
The error message tell you what the problem is `Column 'id' in where clause is ambiguous`.

So add table alias to your 'id' field in your `where()` clause: `->where(['ShortInfos.id' => 1])`

**Comment by lupuswwww** [comment]
Thank you!
