### ISSUE TITLE
Method to retrieve time left of Cache to expire

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#8705]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.8.
- Platform and Target: xampp, PHP 7, maria-db.
### What you did

I am implementing a functionality which requires me to know how much time does any CacheEngine left to expires
### Expected Behavior

something like `$time = Cache::left($key, $config = null)` being the returned variable in milliseconds for example.
### Actual Behavior

There is no method that allows to show time left

**Comment by markstory** [comment]
Wouldn't you need both the key and the config name to check the time to live of a given key?

**Comment by Tzaoh** [comment]
You are completely right

**Comment by jorisvaesen** [comment]
@Tzaoh this shouldn't be to hard to implement (at least for FileCache). Wondering how this would be useful?

**Comment by Tzaoh** [comment]
Hi @jorisvaesen , You are right, I do not think this will cost a lot, I just posted here in case someone wants to code this first than me. Otherwise I will do it on my free time.

I will try to explain briefly.
I have a Behavior I use to download huge amount of data from a third web-service. Like a google spider / crawler using the builtin Client class.

That WebService has some restrictions about the quantity of connections each 10 seconds and each 10 minutes. I configured two caches to those times (10 secs and 10 mins). And I am using cache to store the incremental count of connections I am doing and once I am close to the limit I sleep the crawler for the time left.

I want this to optimize my connections but respecting their limits (I could get more "accounts" to have more connections allowed). We could say this is like a balancer? dont know

Apart of this case I think this could be useful somewhere else.

**Comment by markstory** [comment]
In the above scenario, could you read from the cache until the data expires/is purged and only when the cache data is missing would you go back to the remote service?

**Comment by Tzaoh** [comment]
That is what I was doing initially (and it was fair ok), but once the script reached the limit, it did not stop and keep reading from the cache unnecesarily.

**Comment by markstory** [comment]
@Tzaoh Getting the TTL of a key will also require reading the cache data for some engines. Getting the TTL out of FileCache for example, will require reading the entire cache file just as we would for getting the data.

**Comment by jorisvaesen** [comment]
@markstory I might be wrong but isn't it possible to read only the first line of the cache file without loading the whole? Something like `$time = fgets(fopen($file, 'r'));` ?

**Comment by markstory** [comment]
@jorisvaesen Good point I didn't think of that.

**Comment by ADmad** [comment]
Closing as this feature can't be easily implemented for all cache engines. Having just `FileEngine` behavior differently is not desirable. You can make a custom engine with extra feature.
