### ISSUE TITLE
Inconsistent 'locale'?

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8712]
`L10n::_l10nCatalog` contains an array of languages. The value of 'locale' key seems to be inconsistent. Sometimes it is 3 letters code, in other cases it is 4 letters. Is there a good reason why, it is `'locale' => 'dan', 'localeFallback' => 'dan'` for example but not `'locale' => 'da_dk', 'localeFallback' => 'dan'`?

According to the [cookbook](http://book.cakephp.org/2.0/en/core-libraries/internationalization-and-localization.html):
> The three-character locale codes conform to the ISO 639-2 standard, although if you create regional locales (en_US, en_GB, etc.) cake will use them if appropriate.

But that does not work with da_DK locale.

**Comment by ADmad** [comment]
You can make a PR to add `da_dk` to the list.

**Comment by bancer** [comment]
@ADmad AppVeyor build failed. Have I used a wrong branch?

**Comment by ADmad** [comment]
Nope, the failure is unrelated. Closing this as related PR is open.
