### ISSUE TITLE
`Undefined variable: baseDir` when installing some plugins

### ISSUE THREAD

**Issue by elboletaire** [cakephp/cakephp#8714]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: linux.

### What you did
The problem comes with one of my plugins, but can also be reproduced with plugins from `friendsofcake`. 

Steps to reproduce it with my plugin:

~~~bash
composer create-project cakephp/app testing
cd testing
composer require elboletaire/twbs-cake-plugin
~~~

If you wanna reproduce this with plugins from `friendsofcake` you need to install a few at once:

~~~bash
composer create-project cakephp/app testing
cd testing
composer require friendsofcake/crud friendsofcake/search friendsofcake/bootstrap-ui friendsofcake/crud-view
~~~

Please, note that installing `friendsofcake` plugins one by one will NOT throw the error!

### Expected Behavior
Generate the expected `cakephp-plugins.php` file instead of the one is currently generated (the problem is when it replaces the `$baseDir` variable)

### Actual Behavior
The `cakephp-plugins.php` file re-generated when running the steps above has an incorrect `$baseDir` definition. Here's the file generated after running the above steps:

~~~php
<?php
$baseDir = dirname(dirname($baseDir . '/vendor/cakephp/plugin-installer/src/Installer/PluginInstaller.php'));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'BootstrapUI' => $baseDir . '/vendor/friendsofcake/bootstrap-ui/',
    ]
];
~~~

When it should be...

~~~php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'BootstrapUI' => $baseDir . '/vendor/friendsofcake/bootstrap-ui/',
    ]
];
~~~

I'm not sure about what's going on here, but seems to be a bug in the `cakephp/plugin-installer` module.

**Comment by markstory** [comment]
Neat looks like the `__FILE__` reference inside the here doc was being replaced with the actual path when the file was included multiple times per run.

**Comment by markstory** [comment]
This issue was moved to cakephp/plugin-installer#30
