### ISSUE TITLE
Rename the Schema\Table class

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8715]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Apache 2, Ubuntu 14.04, PHP 7.0.5

### What you did

Added a custom schema type to a table.

```
    protected function _initializeSchema(Table $schema)
    {
        $schema->columnType('keywords','json');
        return parent::_initializeSchema($schema);
    }
```

### Expected Behavior

Be able to overload the `_initializeSchema` method without any difficulties.

### Actual Behavior

Have to alias the class name because `Table` is already used.

```
    use Cake\Database\Schema\Table as Schema;

    protected function _initializeSchema(Schema $schema)
    {
        $schema->columnType('keywords','json');
        return parent::_initializeSchema($schema);
    }
```

I would like to have the `Schema\Table` deprecated and a new name given to the class. Seems like the schema and table model are colliding often enough that renaming the class would be a benefit.

**Comment by markstory** [comment]
> I would like to have the Schema\Table deprecated and a new name given to the class. Seems like the schema and table model are colliding often enough that renaming the class would be a benefit.

Any proposals?

**Comment by ADmad** [comment]
`TableSchema` would be one option since lot of our classes have type suffix.

**Comment by ionas** [comment]
TableDefinition

**Comment by thinkingmedia** [comment]
List of possible alternative class names. Keep in mind the namespace.

`Cake\Database\Schema\Blueprint`
`Cake\Database\Schema\DbTable`
`Cake\Database\Schema\TableDesign`
`Cake\Database\Schema\TableSchema`
`Cake\Database\Schema\TableView`
`Cake\Database\Schema\TableDesc`
`Cake\Database\Schema\TableInfo`

> Represents a single table in a database schema.

`Cake\Database\Schema\SingleTableSchema`
`Cake\Database\Schema\STDS`

**Comment by thinkingmedia** [comment]
@ionas `TableDef` or `SchemaDef` could work as well.

**Comment by josegonzalez** [comment]
I like TableSchema.

**Comment by josegonzalez** [comment]
@lorenzo does elasticsearch use the Schema class? If so, maybe SchemaDef is better?

**Comment by burzum** [comment]
@josegonzalez it is using Cake\ElasticSearch\Datasource\MappingSchema. This class is not extending anything else.

**Comment by ionas** [comment]
`TableSchema` or `TableDefinition` sound good to me cause it is about Tables here. SchemaDef is too board of a term.

**Comment by markstory** [comment]
`TableSchema` works for me. Anyone want to do a pull request for `3.next`?

**Comment by thinkingmedia** [comment]
I can do a PR tomorrow.

**Comment by thinkingmedia** [comment]
I'm going to go with `TableSchema` because when this class is used elsewhere it is always aliased as Schema. So this is consistent with expectations.

**Comment by markstory** [comment]
Pull request up now.
