### ISSUE TITLE
PHP 5.5 and 5.6 builds failing on travis (as of April 27, 2016)

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8720]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: PHP 5.5.21, PhpUnit 4.8.24, MySql
* Platform and Target: PHP 5.6.5, PhpUnit 5.3.2, MySql

### What you did

Created a couple of PRs and noticed the builds on travis for the above platforms are failing.

### Expected Behavior

The following tests should pass.

```
 Cake\Test\TestCase\Database\QueryTest::testSelectWhereOperatorLessThan
 Cake\Test\TestCase\Database\QueryTest::testSelectWithJoinsConditions
```

### Actual Behavior

I'm going to configure a machine with PHP 5.5 and see if I can reproduce the problem, and make a PR to fix the issue.

**Comment by thinkingmedia** [comment]
Can not reproduce with Php 5.5.9, PhpUnit 4.8.24 and MySQL 5.7.12

I will try down grading to MySQL 5.5

**Comment by lorenzo** [comment]
@thinkingmedia you are unlikely to reproduce it, they happen only in travis under mysterious conditions.

**Comment by thinkingmedia** [comment]
@lorenzo I've produced some failures but not the same ones, but what is very concerning is that I can not reproduce the same "skipped" tests. All you get in the output is the letter "S" even when --verbose is enabled.

**Comment by lorenzo** [comment]
Are the failures happening in the Database tests?

**Comment by thinkingmedia** [comment]
Yes, a couple of failures with mysql 5.5 and php 5.5. I suspect the issue is with the mysql version running on travis. This isn't logged in the travis output, but I think it's an issue in the minor version number of mysql. Example; it works in 5.5.6 but not in 5.5.7.

I'm finding it hard to navigate all the tests. So I think I'll make a PR that add text groups, and I want to see a log of what tests are skipped and why. So maybe I'll tweak the report a bit as well.

I've had issues on other projects with travis failing tests because of cpu timing and threading issues. I can only guess that the travis container is single threaded and that is a very hard setup to reproduce locally.

Later tonight, I'm going to setup a virtual box with Ubuntu 14.04.4. I'll then try installing different versions of things, rollback to a snapshot and repeating. This will let me run the tests on different versions of php/mysql.

**Comment by thinkingmedia** [comment]
@markstory  @lorenzo do you know why cake is testing with HHVM on travis?

**Comment by josegonzalez** [comment]
@thinkingmedia because, generally speaking, we support HHVM. They tend to fix support for issues we've found in the past when they are reported. Atm it seems like they may have not implemented DateTime functionality, hence the current fails.

**Comment by thinkingmedia** [comment]
If I isolate the problem tests, then those tests pass on travis. I think this is a house keep issue or timing issue. That's why it might be hard to reproduce locally.

**Comment by thinkingmedia** [comment]
I have a small update on the problem.

The errors appear to be caused by empty fixture data. When the test function starts the tables contain no data, but the tables do exist.

I tried to validate this bug by bypassing the ORM. For a trouble test I ran the below code.

```
        /**
         * @var \Cake\Database\Driver\Mysql $d
         */
        $d = $this->connection->driver();
        $r = $d->_connection->query('SELECT * FROM `articles`')->fetchAll();
        var_dump($r);die;
```

This dumps an empty array without any SQL errors. The code directly below it (not shown) will fail asserts because the table `articles` is empty.

I'm now going to dig into the fixture code to see more of what is happening.

**Comment by thinkingmedia** [comment]
I have confirmed that the fixtures are being created and data inserted as expected. Everything on the fixture side is working fine.

Between the time that the fixture manager is finished updating the fixture, and the test function is called the table is truncated.

It does not look like the fixture manager is doing the truncating.

If I call `$this->loadFixtures()` in the test function. The tests pass as expected.

**Comment by lorenzo** [comment]
great findings! I'm glad you could actually reproduce the issue, let us know if you find more clues

**Comment by thinkingmedia** [comment]
@lorenzo thanks, I'm getting closer to the root of the problem.

**Comment by thinkingmedia** [comment]
I'm able to narrow this down to constraints on fixtures. It looks like this was introduced around version 3.1.2 and afterwards this bug started to appear on travis.

It looks to me that MySQL is enforcing some constraints by deleting records. There are no SQL commands sent to the database to delete or truncate the `articles` table, but it ends up empty when the `QueryTest` is running.

I also found that this bug appears on unit tests that have multiple fixtures. I could make the bug go away by changing the order of the fixtures in the `$fixtures` variable.

This leads me to think that constraints are being applied to fixtures in the wrong order. As a result, MySQL attempts to enforce the constraints against missing data and opts to delete records to enforce the constraint. I have verified that the data is correctly inserted into the tables. It disappears by the time the test runs. So I think this happens when the constraints kick in.

Now, I can not reproduce this on PHP7 or locally with PHP5. Only on travis. Which makes me think their mysql config is not the default or is in some strange error handing more.

So far I don't have an exact cause and effect, but I've narrowed it down to constraints on fixtures. If anyone can provide me with details on how that works, that would be great. I read the docs and it's not very clear. The `articles` fixture only has the primary constraint on it. So I don't see why records would be deleted.

**Comment by thinkingmedia** [comment]
I've  now logged all the SQL statements to see what was happening, and there isn't anything that I can see that would cause this. While there are constraints there aren't any on the `articles` table.

So I think I'm back to the beginning.

**Comment by markstory** [comment]
Having the rows be removed by mysql is pretty strange. Are there any rollback commands lurking about that might cause the fixture insertion to be removed.

**Comment by thinkingmedia** [comment]
@markstory No rollbacks that I can see. Also, if I select from the `articles` table in the test before it the test starts working.

Here's some more details I've uncovered about Travis.

Ubuntu: 12.04
PHP: 5.5.33
MySQL: 5.5

Dumping `/var/logs/mysql/error.log` shows no SQL errors. I'm going to dump the mysql.cnf next and see what settings Travis is using.

MySQL 5.5 is pre-installed on Ubuntu 12, but if you select Ubuntu 14 it has to be manually installed.

I think this is why no one is reproducing this issue locally, because no one uses Ubuntu 12 any more (at least not for desktop). I'm going to give 12 a try tomorrow in virtual box to see if I can reproduce this outside of Travis.

I also want to try using MySQL 5.6 with Ubuntu 14 on Travis.

**Comment by ADmad** [comment]
All builds are passing with recent changes done to fixture loading for tests.
