### ISSUE TITLE
Tree Behavior with custom parent name

### ISSUE THREAD

**Issue by DanielGasperoni** [cakephp/cakephp#8721]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: Linux, MySql.

### What you did
I change the parent_id to another name 
```
$this->addBehavior('Tree', [
        'parent' => 'ancestor_id', // Use this instead of parent_id
]);

```
### Expected Behavior
On method find('threaded') I was expecting working as same as parent_id.
With "parent_id" worked, but another name didn't.

### Actual Behavior
Instead of a nested in a hierarchy result. It was returning everything in the same level, like everything with parent_id as null.

but the method find(''treeList") is working as expected.

**Comment by markstory** [comment]
`find(threaded)` isn't provided by the `TreeBehavior`, and won't ever read those settings. You'll need to use the `parentField` option when calling `find(threaded)`.
