### ISSUE TITLE
Undefined offset: 1 in [CakeResponse.php, line 1410]

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#8723]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.3
* Platform and Target: Ubuntu 14.04, Apache 2.4.20, PHP 5.6.20-1+deb.sury.org~trusty+1 

### What you did
Serve files with CakePHP.

### Expected Behavior
See no errors in my log

### Actual Behavior
See errors in my log:

```
Apr 28 08:48:54 web-01 cakephp-x-x: notice: Notice (8): Undefined offset: 1 in [/var/www/x/x/releases/20160414192429Z/app/Vendor/cakephp/cakephp/lib/Cake/Network/CakeResponse.php, line 1410]
Apr 28 08:48:54 web-01 cakephp-x-x: notice: Notice (8): Undefined offset: 1 in [/var/www/x/x/releases/20160414192429Z/app/Vendor/cakephp/cakephp/lib/Cake/Network/CakeResponse.php, line 1411]
```

Lines `1410` and `1411` are the explodes:
```
	protected function _fileRange($file, $httpRange) {
		list(, $range) = explode('=', $httpRange);
		list($start, $end) = explode('-', $range);
```

It looks like `_fileRange` gets an invalid `env('HTTP_RANGE')` passed.

**Comment by tersmitten** [comment]
I'm not (yet) able to pinpoint it to a specific browser / device, since this is not a general problem.

**Comment by dereuromark** [comment]
We can probably make this a little bit more defensive in general.

**Comment by thinkingmedia** [comment]
The notice means that `list(A,B)` did not get an array with 2 elements.

Changing `explode('=',$httpRange)` to `explode('=',$httpRange,2)` should silence the notice, but that means `$range` now has a chance to contain unexpected values.

**Comment by tersmitten** [comment]
I'm just really curious what the client is sending

**Comment by tersmitten** [comment]
@dereuromark I've seen snippets using `preg_match`. Do you think that's the way to go.

**Comment by dereuromark** [comment]
Or simple str_pos checks etc.

**Comment by markstory** [comment]
I have some ideas on how to fix this. I fixed a similar issue in 3.x and forgot to backport the changes.

**Comment by tersmitten** [comment]
This might be useful:

* https://github.com/aaronstephanus/byte-range-audio/blob/master/AudioController.php
* http://stackoverflow.com/a/30529584/138779
* https://bitbucket.org/thomthom/php-resumable-download-server/src/8713d54809617b24a63065ef3e5afd998288ad36/index.php?fileviewer=file-view-default

**Comment by markstory** [comment]
Pull request open now.

**Comment by tersmitten** [comment]
Look more durable @markstory
