### ISSUE TITLE
FormHelper Radio buttons function is bugged

### ISSUE THREAD

**Issue by gerrymcdonnell** [cakephp/cakephp#8724]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8

### What you did
I added a radio button to a form using the form helper; (as per the example in the book)

```
echo $this->Form->radio(
		    'favorite_color',
		    [
		        ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
		        ['value' => 'u', 'text' => 'Blue', 'style' => 'color:blue;'],
		        ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
		    ]
			);
```

### Expected Behavior
That the variable "favorite_color" contains "r" when i submit the form after selecting red.

### Actual Behavior
When i submit the form, the value for the selected radio buttons is blank.

The error is in the radio function in;
vendor\cakephp\cakephp\src\View\Helper\FormHelper.php

```
    public function radio($fieldName, $options = [], array $attributes = [])
    {
        $attributes['options'] = $options;
        $attributes['idPrefix'] = $this->_idPrefix;
        $attributes = $this->_initInputField($fieldName, $attributes);

        $hiddenField = isset($attributes['hiddenField']) ? $attributes['hiddenField'] : true;
        unset($attributes['hiddenField']);

        $radio = $this->widget('radio', $attributes);

        $hidden = '';
        if ($hiddenField) {
            $hidden = $this->hidden($fieldName, [
                'value' => '',//ERROR value is blank
                'form' => isset($attributes['form']) ? $attributes['form'] : null,
                'name' => $attributes['name'],
            ]);
        }

        return $hidden . $radio;
    }
```

**Comment by markstory** [comment]
If you don't want a hidden field then disable it.

**Comment by gerrymcdonnell** [comment]
There is no hidden field in the above example, i dont understand what you mean. Its from the manual;
http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-radio-buttons

```
echo $this->Form->radio(
    'favorite_color',
    [
        ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
        ['value' => 'u', 'text' => 'Blue', 'style' => 'color:blue;'],
        ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
    ]
);

// Will output
<input type="hidden" name="favorite_color" value="">
<label for="favorite-color-r">
    <input type="radio" name="favorite_color" value="r" style="color:red;" id="favorite-color-r">
    Red
</label>
<label for="favorite-color-u">
    <input type="radio" name="favorite_color" value="u" style="color:blue;" id="favorite-color-u">
    Blue
</label>
<label for="favorite-color-g">
    <input type="radio" name="favorite_color" value="g" style="color:green;" id="favorite-color-g">
    Green
</label>
```

**Comment by markstory** [comment]
Ok. That HTML looks fime to me. What is the problem? Is it that when the form is submitted without a selection being made that you are getting '' instead of one of the values?

**Comment by gerrymcdonnell** [comment]
No when a selection is made its value is blank.

![2016-04-29 1](https://cloud.githubusercontent.com/assets/1525657/14917983/9ebe5458-0e19-11e6-85ed-2235155e1a7b.png)
![2016-04-29 2](https://cloud.githubusercontent.com/assets/1525657/14917982/9ebe1bdc-0e19-11e6-9fab-e5e6a211797b.png)

**Comment by markstory** [comment]
I'll see if I can reproduce that issue.

**Comment by gerrymcdonnell** [comment]
Thanks, it seems that hiddenField is default to true, not sure if that helps.

**Comment by gerrymcdonnell** [comment]
I think i found the solution;

The error is in the radio function in;
vendor\cakephp\cakephp\src\View\Helper\FormHelper.php

   ```
 public function radio($fieldName, $options = [], array $attributes = [])
    {
		$attributes['options'] = $options;
        $attributes['idPrefix'] = $this->_idPrefix;
        $attributes = $this->_initInputField($fieldName, $attributes);		

        $hiddenField = isset($attributes['hiddenField']) ? $attributes['hiddenField'] : true;		
		
        unset($attributes['hiddenField']);

        $radio = $this->widget('radio', $attributes);

        $hidden = '';
        if ($hiddenField) {
            $hidden = $this->hidden($fieldName, [
                'value' => '',
                'form' => isset($attributes['form']) ? $attributes['form'] : null,
                'name' => $attributes['name'],
            ]);
        }

        return $hidden . $radio;
    }
```

The error is here;
its set to default as true for hiddenfield;

` $hiddenField = isset($attributes['hiddenField']) ? $attributes['hiddenField'] : true;	`

Fix is to just set it to default as false;

` $hiddenField = isset($attributes['hiddenField']) ? $attributes['hiddenField'] : false;	`

**Comment by ADmad** [comment]
That's not a fix :)  You are disabling generating the hidden field by default which shouldn't be done.

You can use `'hiddenField' => false` in options if you don't want the hidden field yourself. But doing so would mean if user does not select any value you won't get the `favorite_color` key in `request->data`.

**Comment by gerrymcdonnell** [comment]
Can you give an example of how to use `hiddenField' => false` please?

**Comment by markstory** [comment]
```php
echo $this->Form->radio(
            'favorite_color',
            [
                ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
                ['value' => 'u', 'text' => 'Blue', 'style' => 'color:blue;'],
                ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
            ],
            ['hiddenField' => false]
            );
```

**Comment by gerrymcdonnell** [comment]
Ok if the hiddenfield is set to true i get no value even when i pick an option and submit the form;

```
	echo $this->Form->radio(
            'favorite_color',
            [
                ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
                ['value' => 'b', 'text' => 'Blue', 'style' => 'color:blue;'],
                ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
            ],
            ['hiddenField' => true]
            );
```
			
if i set it to false it works i,e the picked value is correct

**Comment by markstory** [comment]
I'm not able to reproduce this issue by copying and pasting your form input into a working form. Perhaps there are other inputs in your form lower down that are overwriting the value of `favorite_color`?  You can use the following form to see that radio buttons _do_ work


```php
<?php
echo $this->Form->create();
echo $this->Form->radio(
'favorite_color',
[
    ['value' => 'r', 'text' => 'Red', 'style' => 'color:red;'],
    ['value' => 'b', 'text' => 'Blue', 'style' => 'color:blue;'],
    ['value' => 'g', 'text' => 'Green', 'style' => 'color:green;'],
]
);
echo $this->Form->button('Submit');
echo $this->Form->end();
```

**Comment by gerrymcdonnell** [comment]
Nope there are no ther inputs over writing that value. Ill post my xamp and php versions later since i i cant think of what else it could be to cause this.

**Comment by dipposh** [comment]
I get the same issue.

```
<ul>
<li>
<input name="player" value="" type="hidden">
<label for="player-0d53c433-5dfa-4987-9a3c-bbe0bf13cc26">
</li>
<li>
<input name="player" value="" type="hidden">
<label for="player-772c93e9-9640-4642-9e22-ec7385ff1a39">
<input id="player-772c93e9-9640-4642-9e22-ec7385ff1a39" name="player" value="772c93e9-9640-4642-9e22-ec7385ff1a39" type="radio">
Dave Dave
</label>
</li>
</ul>
```
Result when spitting out $this->request->data
[
	'player' => ''
]
 If you look at the POST parameters passed when you submit, that may be a clue - I get _method=POST&player=&player=0d53c433-5dfa-4987-9a3c-bbe0bf13cc26&player=
