### ISSUE TITLE
Add 'webroot' in the middle of url, or appears blank page

### ISSUE THREAD

**Issue by TiagoSilvestre** [cakephp/cakephp#8725]
Hello, i've been tried to create a view with data from database, but iam have 2 sames issues:

-> The page stay blank with the message: 

No Data Received
ERR_EMPTY_RESPONSE

-> When I make click in the link to controller that i want, cakephp pass in the url the following url:

myDomain/webroot/controller

I dont know why cakephp is puting webroot in the url.....

In the apache's error.log I have this error:

[Thu Apr 28 16:47:23.169213 2016] [core:notice] [pid 1619] AH00052: child pid 4737 exit signal Segmentation fault (11)
[Thu Apr 28 16:47:23.169217 2016] [core:notice] [pid 1619] AH00052: child pid 4738 exit signal Segmentation fault (11)
[Thu Apr 28 16:47:23.169222 2016] [core:notice] [pid 1619] AH00052: child pid 4800 exit signal Segmentation fault (11)

-----------------------------------------------------------------------------------------------------------------
THIS IS MY CONTROLLER - CurriculosController.php

<?php
namespace App\Controller;

use App\Controller\AppController;

class CurriculosController extends AppController
{

    public function index()
    {
       $this->loadModel('Curriculo');
       $curriculos = $this->Curriculos->find()->all();
       $this->set('cur', $curriculos);
    }
}
--------------------------------------------------------------------------------------------------------------------
THIS IS MY MODEL/TABLE – Model/Table/CurriculosTable.php

<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class CurriculosTable extends Table
{
}
---------------------------------------------------------------------------------------------------------------------
THIS IS MY MODEL/ENTITY - Model/Entity/Curriculo.php

<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Curriculo extends Entity
{
    public $_accessible = [
        'id' => true,
        'nome' => true,
        'created' => true
    ];
}

---------------------------------------------------------------------------------------------------------------------
THIS IS MY VIEW - Template/Curriculos/index.ctp

<form action="index" method="post" enctype="multipart/form-data">
        <input type="text" name="nome" id="fileToUpload">
        <input type="submit" value="Enviar" name="submit">
</form>
----------------------------------------------------------------------------------------------------------------------
I hope someone can help me because this error already appears in 3 differents computers with differents SO(Linux and Windows), but always with apache.
Thanks

**Comment by TiagoSilvestre** [comment]
THIS IS MY VIEW - Template/Curriculos/index.ctp

<form action="index" method="post" enctype="multipart/form-data">
        <input type="text" name="nome" id="fileToUpload">
        <input type="submit" value="Enviar" name="submit">
</form>



I

**Comment by TiagoSilvestre** [comment]
THIS IS MY VIEW - Template/Curriculos/index.ctp 

<form action="index" method="post" enctype="multipart/form-data">
        
        <br><br>
        <input type="text" name="nome" id="fileToUpload">
        <input type="submit" value="Enviar" name="submit">
    </form>

**Comment by TiagoSilvestre** [comment]
/* THIS IS MY VIEW - Template/Curriculos/index.ctp

*/

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
