### ISSUE TITLE
3.x/4.x RFC Schema/bake conventions to automagically differentiate betwen hasMany and hasOne

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8727]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2

### What you did
Toyed with bake tool and realized (or rather got reminded) that you cannot bake hasOne associations.

### Expected Behavior
Be able to differentiate between hasOne and hasMany

### Actual Behavior
For 4.x I'd like singular foreign keys to be no more for hasMany/belongsTo (and HABTM). 
Instead the only singular foreign keys should be those linking belongsTo/hasOne.
However: I am not sure if keeping the singular/plural Inflector in the ORM core for just that is worth it.

### Backwards compatibility
1. This won't touch existing projects, just those where you bake things.
2. Because of 1. I'd like to see this as an opt-out feature (opted-in by default) somewhere during 3.x. A NullInflector would be used when opting out and cake/bake will treat singular foreign keys (with the good old inflector) as hasOne relationships unless opted out of this feature.

**Comment by markstory** [comment]
Having two conventions adds complexity. Do you find yourself using hasOne associations frequently enough that this is a large problem?

**Comment by chinpei215** [comment]
A simple solution would be to check unique constraints [here](https://github.com/cakephp/bake/blob/ae9aac72c91186fa2ec3b90d5bfe60146da68a56/src/Shell/Task/ModelTask.php#L366). If ` $foreignKey` is a unique field, then the association would be `hasOne`. Probably, this change can be done by adding a few lines without introducing new conventions.

**Comment by jhli** [comment]
That is an awesome idea.

I am still thinking we should have TABLENAME_id by default instead of singular but thats indepenend then.

If my PRs for bake (2 open atm) go through I ll look at FK + Unique detection and hasMany bake generation.

**Comment by chinpei215** [comment]
@jhli
> I am still thinking we should have TABLENAME_id by default instead of singular

It would be a lot of work :unamused:
(Fix bake, existing tests, document, FormHelper (maybe), upgrade tool, etc...)

> I ll look at FK + Unique detection and hasMany bake generation.

Thanks :)

**Comment by ionas** [comment]
@chinpei215 all those tools should listen to the ORM's primary and foreign key definitions. These again should match real schema primary and foreign key definitions and bake should (does AFAIK not entirely, not yet) respect those and ignore conventions if primary and foreign keys are setup in the table schema.

That should be the first step. It might (can't say) involve fixing FormHelper, tests, etc, like you say. It will make sure that you can setup whatever foreignKeys you like (see https://github.com/cakephp/bake/issues/236#issuecomment-215687091). If that's the case you can use your 3.x code in 4.x because the primary and foreignKeys are defined in the table classes already, then.

Let's see if I can complete https://github.com/cakephp/bake/pull/242 and https://github.com/cakephp/bake/pull/241 first.

But first I ll take a look at hasOne.

**Comment by ionas** [comment]
It is not beautiful but here you go @chinpei215 https://github.com/cakephp/bake/pull/242/files#diff-04107a214f01287dee44cfd8bdfc462cR385
