### ISSUE TITLE
default_locale Plugin var i18n

### ISSUE THREAD

**Issue by awilchesl** [cakephp/cakephp#8729]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.5

### What you did
I have a problem with the translation of i18n when I define the default language in my boostrap

### Expected Behavior

Look:

Bootstrap:
`ini_set('intl.default_locale', 'en_US');`

App Controller:
```
$this->request->params['language']='es';
if(isset($this->request->params['language']) and $this->request->params['language']!=''){
            I18n::locale($this->request->params['language']);
			I18n::defaultLocale('es'); 
			ini_set('intl.default_locale', 'es');
        }else{
        	I18n::defaultLocale();
        	I18n::defaultLocale('en_US');
        	I18n::locale('en_US');
        	ini_set('intl.default_locale', 'en_US');
        }
```

Layout:

```
$extra['prueba' => __d('administrator', 'Total publicaciones'),]
echo $extras['prueba'];
```

es .po
```
msgid "Total publicaciones"
msgstr "Publicaciones"
```

en_US .po
```
msgid "Total publicaciones"
msgstr "Posts"
```

when printing variable `$extras['prueba']` default throws me the en_US language and I did not throw the language ES

If I remove the variable and income directly translation: `__d('administrator', 'Total publicaciones')` It works but in this case I need to translate the variable. 

when removing default language bootstrap I can see that changing the language is but stop the en_US language function by their respective variable

**Comment by markstory** [comment]
> when printing variable $extras['prueba'] default throws me the en_US language and I did not throw the language ES
>
> If I remove the variable and income directly translation: __d('administrator', 'Total publicaciones') It works but in this case I need to translate the variable. 

So the code behaves correctly if you output the translated message directly, but fails if you assign the results to a variable?

**Comment by lorenzo** [comment]
Closing as there was no answer in a while
