### ISSUE TITLE
MySQL BIT Datatype is treated as Text instead of Boolean or Integer

### ISSUE THREAD

**Issue by VeryCrazyDog** [cakephp/cakephp#8730]
* CakePHP Version: 3.2.3
* Platform and Target: MySQL 5.7.10

### What you did
Insert a record to MySQL table which contains BIT datatype column.

### Expected Behavior
Insert successfully.

### Actual Behavior
Error returned. Below is the sample error.
> Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'is_enabled' at row 1 

### Suggested Fix
For handling with boolean datatype, in file [`cakephp/src/Database/Schema/MysqlSchema.php`](https://github.com/cakephp/cakephp/blob/3.2.3/src/Database/Schema/MysqlSchema.php), function `protected function _convertColumn($column)`, modify line
```php
if (($col === 'tinyint' && $length === 1) || $col === 'boolean') {
```
to
```php
if (($col === 'tinyint' && $length === 1) || $col === 'boolean' || ($col === 'bit' && $length === 1)) {
```

### Current Workaround

Manually change the data type in table class.

```php
<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class MyTable extends Table {
	protected function _initializeSchema(\Cake\Database\Schema\Table $schema) {
		$schema->columnType ( 'is_enabled', 'boolean' );
		return $schema;
	}
}
```

**Comment by jhli** [comment]
For BIT(1) I can see this, for BIT(M) M > 1 I can't (same with TINYINT).

**Comment by jhli** [comment]
https://dev.mysql.com/doc/refman/5.7/en/bit-type.html

**Comment by VeryCrazyDog** [comment]
Thanks and I didn't notice that there is a length for BIT datatype. I have updated the title and suggested fix.

**Comment by markstory** [comment]
`BIT` columns are not supported right now.

**Comment by ionas** [comment]
I am not sure what the core team thinks but would you consider doing a PR @VeryCrazyDog?
Caveat:
- While BIT(1) could be rendered and treated as a boolean, I am not sure what BIT(>1) would map to. Partial support seems strange.
- Does the core team want support for BIT? A quick look did not reveal that Sqlite supports it (https://www.sqlite.org/datatype3.html) but MySQL/Maria/Percona (see above) Postgres (http://www.postgresql.org/docs/8.2/static/datatype-bit.html) support it whereas a quick look seems to suggest that SQLServer's BIT datatype only stores one bit and thus is a boolean store: https://msdn.microsoft.com/de-de/library/ms177603

**Comment by markstory** [comment]
Unless we are going to figure out how to store all the flavours of `BIT` I see no reason to add special support for `BIT(1)`. People who really need BIT support can extend the type system.

**Comment by VeryCrazyDog** [comment]
For MySQL 5.7.10, actually `BIT` is treated as integer. I tried to create a `BIT(3)` column, and my SQL statement can only insert up to integer value `7` and inserting `8` will cause an error.

I guess CakePHP can also do the same and treat BIT as integer or boolean, just like handling integer such as SMALLINT, but effort is needed to make sure the handling for different type of database and database version is correct.

I also recommend updating the document to stated clearly that BIT datatype (and also JSON datatype) is not supported by CakePHP at this moment.

**Comment by markstory** [comment]
JSON datatypes will be supported in 3.3.0.

**Comment by ionas** [comment]
@VeryCrazyDog could you update the docs/api docblocks to reflect that BIT() is not supported?

**Comment by VeryCrazyDog** [comment]
I never tried this before (create any pull request and update CakePHP docs). Anyway I just created one [here](https://github.com/cakephp/docs/pull/4004), please take a look of that fit the standard.

**Comment by dereuromark** [comment]
Looks like the docs PR is merged. Anything else to be done?
