### ISSUE TITLE
3.x Flash Component: index messages by hash 

### ISSUE THREAD

**Issue by ayman-alkom** [cakephp/cakephp#8731]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: All.

### What I did
for some reason I set the flash message several times but all are the same message.

### Expected Behavior
the same messages will be merged in one .

### Actual Behavior
the same messages repeated 

now [in this position](https://github.com/cakephp/cakephp/blob/9899909363e80ad4c160d1e136dfa754d4f05401/src/Controller/Component/FlashComponent.php#L107) :
```php
        $messages[] = [
            'message' => $message,
            'key' => $options['key'],
            'element' => $options['element'],
            'params' => $options['params']
        ];
```
suggestion:
```php
        $hash = custom_hash($message, $options['key'], .....);
        $messages[$hash] = [
            'message' => $message,
            'key' => $options['key'],
            'element' => $options['element'],
            'params' => $options['params']
        ];
```
the hash method must accepts the message at least

**Comment by AD7six** [comment]
Please do not destroy the [new issue template](https://github.com/cakephp/cakephp/issues/new)

**Comment by markstory** [comment]
I don't really understand what you're asking here. The `hash()` function in PHP doesn't work on arrays.

**Comment by ayman-alkom** [comment]
I have edit the function name, in fact I didn't mean the php hash function.
I just wanted to refer to any function can return a hashed value from the message or from the message and other values like element name or key value etc

**Comment by thinkingmedia** [comment]
I don't think we can change cake to drop repeated messages because some people might need to show repeated messages. This is more of a business logic issue than a limitation on cake. You can either change the flash template to not render duplicates or fix your logic to not flash duplicates.

**Comment by markstory** [comment]
This does feel like a change that could break people's apps and would need to be documented in minor release if we were to move ahead with it.

**Comment by ayman-alkom** [comment]
@thinkingmedia you are right, but let 's say that we can resolve that.
for example we may made it optional to be merged or not or relational to the debug mode whereas enabled just when debug is false.

it just a basic idea and not completed yet, we may also passed a variable like `count` to the flash elements representing the repeating times of the message.
