### ISSUE TITLE
Wrong documentation or localization bug?

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8732]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.3.
* Platform and Target: Linux, Apache, MySQL.

### What you did
[Cookbook](http://book.cakephp.org/2.0/en/core-libraries/internationalization-and-localization.html) says:
> To change or set the language for your application, all you need to do is the following:
Configure::write('Config.language', 'fra');

Although that seems to be false. The language is not switched:
```
Configure::write('Config.language', 'fr-fr');
echo __d('admin', 'Submit');
Configure::write('Config.language', 'en-us');
echo __d('admin', 'Submit');
```
But it works when the session is used:
```
CakeSession::write('Config.language', 'fr-fr);
echo __d('admin', 'Submit');
CakeSession::write('Config.language', 'en-us');
echo __d('admin', 'Submit');
```

### Expected Behavior
I would expect that `Configure::write('Config.language', 'en-us');` would be enough to change the language

**Comment by chinpei215** [comment]
Probably, you would need to use `_` instead of  `-` for the locale name. It works fine for me.
```php
Configure::write('Config.language', 'de_DE');
echo __d('admin', 'Submit');
//

Configure::write('Config.language', 'ja_JP');
echo __d('admin', 'Submit');

Configure::write('Config.language', 'en_US');
echo __d('admin', 'Submit');
```

**Comment by bancer** [comment]
> Probably, you would need to use _ instead of - for the locale name.

Nope. 'en_US' locale doesn't work. The problem is not in the locale name. Changing the language with `CakeSession::write('Config.language', 'en-us');` works as expected.

**Comment by chinpei215** [comment]
@bancer Strange:confused: The above code really works for me. What is your directory structure? Here is my structure:
```
├─de_DE
│  └─LC_MESSAGES
│          admin.po
│          default.po
│
└─ja_JP
    └─LC_MESSAGES
            admin.po
            default.po
```

**Comment by bancer** [comment]
My structure is:
```
├─da_dk
│  └─LC_MESSAGES
│          admin.po
│          frontend.po
│
└─en_us
    └─LC_MESSAGES
            admin.po
            frontend.po
```
Did you test on the same version of Cake on Linux?

**Comment by chinpei215** [comment]
I tested it on windows. Probably case-sensitive?

**Comment by chinpei215** [comment]
The same version of Cake. (2.8.3)

**Comment by markstory** [comment]
If a session value is set, it is preferred over the `Configure` value. Using the session is documented in the snippet that follows the cited one.

**Comment by bancer** [comment]
> If a session value is set, it is preferred over the Configure value.

That is not documented there. And the statement "To change or set the language for your application, all you need to do is the following: Configure::write('Config.language', 'fra');" is misleading.

**Comment by ADmad** [comment]
Please submit an update to the docs to make that fact clearer.
