### ISSUE TITLE
Cache/Engine/FileEngine.php: Optimize memory when saving large cache files

### ISSUE THREAD

**Issue by psaintjust** [cakephp/cakephp#8741]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8, 2.8.3
* Platform and Target: PHP 5.6.20

### Enhancement
The write method in Cache/Engine/FileEngine.php is using twice as much memory as necessary which can result in PHP crashing.

Change line:
$contents = $expires . $lineBreak . $data . $lineBreak;
to
$contents = implode([$expires, $lineBreak, $data, $lineBreak]);
This avoid a temporary copy of the data string before concatenating the final lineBreak.

### What you did
My myapp_cake_core_method_cache file grew to 37Mb and would cause PHP to terminate on write.  Unfortunately on the PHP version I tested, this crash did not produce any error logs (PHP bug?).  Increasing the memory allocated to PHP or changing the line I mentioned solved the issue.

**Comment by psaintjust** [comment]
Additional reading: http://arr.gr/blog/2014/05/php-memory-usage-unnecessary-string-concatenation/

**Comment by markstory** [comment]
Closing as a pull request is up now.
