### ISSUE TITLE
4.x Table::displayField() fallback should reflect composite primary keys

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8747]
This is a non-BC change.
Ref: https://github.com/cakephp/cakephp/pull/8744#event-646561291

**Comment by dereuromark** [comment]
> That might be a better idea. Having an array as the display field complicates things like making select boxes or find(list).

as @markstory pointed out this is not trivial.

@ionas What are you takes on this, how should this be done?

**Comment by dereuromark** [comment]
The only thing I can think of is using some kind of separator

    key1:value2;key2:value2

would be the key then.

**Comment by inoas** [comment]
The value in FormHelper's selects for composite foreign keys is "value-1;value-2;...;value-n" so I think key1:value;key2:value2 is pretty sane. It is just a default, one can always change it.
In general it would be cool to be able to setup an array or message such as:
```php
$this->setDisplayField(__('Foo {0} / Bar {1}'), [0 => 'id', 1 => 'parent_id'])
// or 
$this->setDisplayField(__('Foo {id} / Bar {parent_id}'), ['id', 'parent_id']).
```
I do this in entities at the moment.
