### ISSUE TITLE
3.x Bug/Enhance: ExistsIn Application Rule and NULL values

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8749]
This is a (multiple allowed):
* [x] enhancement
* [x] bug

* CakePHP Version: 3.2.4

### What you did
When teaching cake/bake composite foreign keys these are existsIn rules being created:
```php
$rules->add($rules->existsIn(['project_id'], 'Projects'));
$rules->add($rules->existsIn(['project_id', 'parent_id'], 'ParentCategories'));
```
Ref: https://github.com/cakephp/bake/pull/242

### What you expected
ExistsIn should do 4 things IMHO but only does 1:
1. enforce existence unless all keys given are NULL despite what the schema says (@hmic's concerns)
2. enforce existence unless all keys given are NULL **and** all these keys are allowed to be NULL by the schema. (**current implementation**)
3. enforce existence only if no keys given are NULL and these are allowed to be NULL by the schema (**case above**).
4. enforce existence only if no keys given are NULL ignoring whatever the schema says (relaxed case where you trust the data coming in and don't need to define anything in your schema)

### Suggestion
@lorenzo suggested that we opt for new rules.

Here is a suggestion for the interfaces:
1: `existsInIgnoreSchemaNulls()`
2. `existsInRespectSchemaNulls()` (current `existsIn()` should alias that)
3. `existsPartiallyInRespectSchemaNulls()`
4: `existsPartiallyInIgnoreSchemaNulls()`

Can you think of better naming?

Differences between those rules would be in how http://api.cakephp.org/3.2/source-class-Cake.ORM.Rule.ExistsIn.html#123-133 works.

**Edit #1:** Related https://github.com/cakephp/cakephp/pull/8621
**Edit #2:** Changed to Bug/Enhancement.

**Comment by markstory** [comment]
Is there an option where we take a more opinionated stance on how we think database schemas should be designed/used and only accommodate that use case? The other use cases could be handled by application specific rules.

**Comment by jhli** [comment]
Issue is with self joins AND composite primary keys, case 3 is required abd not a design choice. E.g. Parent Id can be NULL where project never is...

**Comment by ionas** [comment]
What about a syntax like:
```$rules->add($rules->existsIn(['project_id' => 'NOT NULL', 'parent_id' => 'NULL'], 'ParentCategories'));``` which would allow parent_ID to be NULL (or UNIQUE in set with project_id), project_id however never may be NULL.

**Comment by markstory** [comment]
Being able to define the constraints is an interesting approach.

**Comment by ionas** [comment]
@markstory I am not entirely sure but I think this is no Enhancement but a bug.
In ExistsIn.php I changed this:

### New Check:
```php
    /**
     * Check whether or not the entity fields are nullable and null.
     *
     * @param \Cake\Datasource\EntityInterface $entity The entity to check.
     * @param \Cake\ORM\Table $source The table to use schema from.
     * @return bool
     */
    protected function _fieldsAreNull($entity, $source)
    {
        $schema = $source->schema();
        foreach ($this->_fields as $field) {
            if ($schema->isNullable($field) === false && $entity->get($field) === null) {
                return false;
            }
        }
        return true;
    }
```

### Old Check:
```php
    /**
     * Check whether or not the entity fields are nullable and null.
     *
     * @param \Cake\Datasource\EntityInterface $entity The entity to check.
     * @param \Cake\ORM\Table $source The table to use schema from.
     * @return bool
     */
    protected function _fieldsAreNull($entity, $source)
    {
        $schema = $source->schema();
        foreach ($this->_fields as $field) {
            if ($schema->isNullable($field) === false && $entity->get($field) === null) {
                return false;
            }
        }
        return true;
    }
```
# Explanation
Old:
1. count all fields that are nullable AND null, of the fields specified when evoking `ExistsIn()`
2. in case the count matches with the amount of keys specified when evoking `ExistsIn()` then the constraint is met.

New:
1. loop through all fields specified when evoking `ExistsIn()`. In case any of the fields specified are null but are not allowed to be null, the constraint will not be met.
2. In any other case, the constraint will be met.

For the Old behavior two things are weird:
1. the comparision itself and b checking if something is null and can be null. What if it is allowed to be set to null but is not null.... e.g. there is some further 'logic bug' hidden ATM, IMHO.

**Comment by ionas** [comment]
When running the test cases I realized that now when you supply an invalid foreign key for instance that is part of ExistsIn (like parent_id 9001 where that doesnt exist) that will pass through despite that it should only pass through on NULL and any existing (parent) id.

**Comment by ionas** [comment]
e.g. testExistsInDomainRuleWithObject... debug(is_bool($table->save($entity))); returns an entity instead of bool false.

**Comment by ionas** [comment]
**Edit:**

`return $target->exists($conditions);` there is still something wrong about that as it needs to say for example ParentNode.id IS NULL OR ParentNode.id IS NOT NULL for InExist constraints where a key may be null (or a valid value)

**Comment by ionas** [comment]
This seems to work as a quick workaround:
class ExistsIn: http://hastebin.com/vuzidexaxo.php
class NodesTable (Example): http://hastebin.com/jisuniteqi.php
class NodesController (Example): http://hastebin.com/ipedoyakol.php
instances CakePHP3 Table Migration: http://hastebin.com/uwapehiqug.php
nodes CakePHP3 Table Migration: http://hastebin.com/emubewidad.php

```
$ vendor/bin/phpunit tests/TestCase/ORM/RulesCheckerIntegrationTest.php 
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.
OK (32 tests, 114 assertions)
```

**Comment by ionas** [comment]
Closing as there is a PR open.
