### ISSUE TITLE
SQLite database path configuration bug

### ISSUE THREAD

**Issue by K4T** [cakephp/cakephp#8755]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.1.13.
* Platform and Target: Windows, Apache, SQLite

### What you did
I created simple migration script for my SQLite database and I added following db config:
```php
'sqliteDefault' => [
    'className' => 'Cake\Database\Connection',
        'driver' => 'Cake\Database\Driver\Sqlite',
            'persistent' => false,

            'encoding' => 'utf8',

            'database' => 'db/rp.db'
        ]
```

Running migration procedure from CLI will create rp.db file under app root directory and this is ok.
Problem is when I want to use the same db configuration in my CakePHP application - I will get error that database file could not be found. I can solve this by creating second database configuration with different path to database file:
```php
'sqliteDefaultForAPP' => [
    'className' => 'Cake\Database\Connection',
        'driver' => 'Cake\Database\Driver\Sqlite',
            'persistent' => false,

            'encoding' => 'utf8',

            'database' => '../db/rp.db'
        ]
```

### Expected behavior
sqliteDefault configuration should work from CLI and also in App. Now I have to create separated configs for each (only path to database file will be different, but it is still the same file).

**Comment by ADmad** [comment]
Use absolute paths instead of relative paths.
