### ISSUE TITLE
3.4: Defining relations improvements with fluent interface

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8757]
So far bake outputs:

``` php
$this->belongsTo('Cities', [
    'foreignKey' => 'city_id',
    'joinType' => 'INNER',
    ...
]);
```

If you where to define it yourself (adding new ones after baking) and there was a typo in one of the keys like `foreingKey` or `'joinTyp'`, it would silently not do anything here.

Wouldn't the following fluent interface way be a more robust approach then?

``` php
$this->belongsTo('Cities')
   ->foreignKey(...)
   ->joinType(...)
    ...;
```

Otherwise I recommend providing class consts for people to use here in app user land code.

Currently the limitation seems to be the (bad) getter/setter combinations (`foreignKey()` and alike are not return void/$this yet for setting), but once they are cleaned up in 4.x, we could start using this less error-prone fluent interface approach in 5.x then?
If we deprecated things early in 3.x for the relation classes, maybe even for 4.x then.

``` php
$this->belongsTo('Cities')
   ->setForeignKey(...)
   ->setJoinType(...)
    ...;
```

**Comment by jhli** [comment]
Great idea!

**Comment by markstory** [comment]
The current return value of the association methods is the association. Adding fluent builders on top shouldn't be too difficult.

**Comment by burzum** [comment]
Do I get this right, this ticket is about adding the getter and setter methods? Because the other methods already existed or have been added meanwhile.

**Comment by dereuromark** [comment]
@burzum Yes.
So many upvotes but so far no one wanted to do it.
Anyone up for the job?

**Comment by burzum** [comment]
@dereuromark I might do it after the auth refactor.

**Comment by dereuromark** [comment]
I already started the branch and added the first basic test :)
https://github.com/cakephp/cakephp/compare/3.next...3.next-table-relations#diff-86fa34cb4cbb9b221b8f5ae43d850236R3965
