### ISSUE TITLE
Cake 3 - Postgresql - UUID as PK using char(32) issue. Cake is not automatically setting a UUID for a row

### ISSUE THREAD

**Issue by zgambino** [cakephp/cakephp#8764]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: RHEL 6, PostgreSQL 9.4.7

When using a char(36) column as the PK, Cake doesn't seem to generate a UUID, and PDO errors out because the PK is a require field.
`Error: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint DETAIL: Failing row contains (null, test).`

Attached are a sample Schema, Controller and Model files.
[SampleController.txt](https://github.com/cakephp/cakephp/files/247681/SampleController.txt)
[SampleTable .txt](https://github.com/cakephp/cakephp/files/247682/SampleTable.txt)
[Sample.txt](https://github.com/cakephp/cakephp/files/247683/Sample.txt)

While testing, I noticed that in ORM/Table.php, on line 1579, the `$typeName = $this->schema()->columnType($primary[0]);` function returns "string" instead of "uuid" for the PK column.

I'm not sure if this is it, but it's a place to start I guess?

Or, I'm just an idiot. At this point, I can't tell. ;)

**Comment by lorenzo** [comment]
I think in postgres you need to set the column as `uuid` instead of `char(32)`. If you cannot change your database, then add this to your table:

```php
protected function _initializeSchema(\Cake\Database\Schema\Table $schema)
{
    $schema->columnType('id', 'uuid');
    return $schema;
}
```

**Comment by zgambino** [comment]
Yes, changing the column does fix the issue, but the documentation and previous versions of Cake suggests you should be able to use char(32). I have a bunch of legacy tables I'm converting to use v3, and you can't just convert from char(32) to uuid without a bunch of mess.

Did I miss something in the docs or changelogs?

**Comment by lorenzo** [comment]
That is definitely in the changelogs, but not sure it is actually easy to find. I will close this issue since there is a suitable way to make your use case work.

I would personally encourage using a uuid type in postgres, as it is more efficient

**Comment by leandrofreires** [comment]
this should be in the documentation "I think in postgres you need to set the column as uuid instead of char(32)"

**Comment by markstory** [comment]
@leandrofreires Would you be willing to make a pull request for cakephp/docs?

**Comment by leandrofreires** [comment]
@markstory yes I will provide
