### ISSUE TITLE
Add patchOrCreate that works like findOrCreate

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8772]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8

### What you did

```
        $entity = $this->Posts->findOrCreate([
            'id' => $id
        ], function ($entity) {
            $entity->category = $this->request->data('category');
        });
        if (!$entity->isNew()) {
            $this->Posts->patchEntity($entity, $this->request->data);
            if (!$this->Posts->save($entity)) {
                throw new BadRequestException();
            }
        }
```

I have a REST end point that patches a record, and if the record doesn't exist it will be created.

### Expected Behavior

If we have a `patchOrCreate` method that worked the same as `findOrCreate`. Except that the callback is always called. It would have made the above easier.

```
        $entity = $this->Posts->patchOrCreate([
            'id' => $id
        ], function ($entity) {
            $entity->category = $this->request->data('category');
        });
```

Technically, the name `createOrPatch` is more accurate, but `patchOrCreate` is what people would look for.

**Comment by markstory** [comment]
Do you frequently have resources where you need to update an existing record, or create a new one? Creating records with pre-determined primary keys is not possible when using auto increment keys with SQLServer and Postgres.

**Comment by thinkingmedia** [comment]
Think of HABM join tables. The primary key is a compound of the primary
from two tables. It doesn't need it's own primary key because the compound
key can act as the primary.

So for example you have tags and blogs. These two tables have a HABM join
table called tags_blogs. Now what if the join table also stores data. When
the user edits this you can simplify the process using patchOrCreate. Since
you know what the two ids are for the join table record.

That's the case I've run into.

MySQL has insert or update. I'm just wanting to add some thing like that.

**Comment by jhli** [comment]
I'd say if this feature makes it, there should be an exception thrown ahead saving in case one or more of your prinary key fields is setup as a sequence/auto increment in SQL/schema.

**Comment by markstory** [comment]
Do you edit junction table records directly with a controller? Personally, I implicitly edit those records when working on root entities.

**Comment by thinkingmedia** [comment]
I have some other examples that are not join tables, but need to be edited directly.

`Posts` and `Users` tables have data tables called `Post_Clicks` and `Post_Views`. Only authorized users can click or view a post. Both tables have a compound key `['post_id','user_id']` so they don't need their own ID as they is unique to each user and post.

When a user views or clicks I could just call `patchOrCreate` to update those tables.

**Comment by markstory** [comment]
I'm a bit hung up on the 'patch' part of this method. It doesn't leverage `patchEntity()` at all, which is something I would have expected. Do you forsee people using patchEntity() in the closure they provide?

**Comment by thinkingmedia** [comment]
@markstory the closure is just to prepare the entity. Just like `findOrCreate` does. The `partchOrCreate` calls `patchEntity` and `save` on it's own. The function should do all the work as does `findOrCreate`.

I can post a sample code block.

**Comment by thinkingmedia** [comment]
The first parameter is the ID, and the second the callback. If the ID is not found a new entity is created, the callback is fired and it's save. If the ID is found the callback is fired and the entity is patched and saved.

**Comment by thinkingmedia** [comment]
Oh sh#t. I see the problem now.

Hmm... I guess I forgot how patch works.

**Comment by thinkingmedia** [comment]
Closing as not practical to implement.
