### ISSUE TITLE
able to find root nodes

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#8774]
This is a (multiple allowed):
* [x] bug
* [x]  enhancement

### Expected Behavior
able to find root nodes

### Actual Behavior
if we set for=null ,Happens a error
https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TreeBehavior.php#L440
and
wronge root test 
root value is `null` not `1`
https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/Behavior/TreeBehaviorTest.php#L222-L225

**Comment by ADmad** [comment]
If you need root nodes you can just do a normal find with condition `'parent_id' => null`.

**Comment by saeideng** [comment]
yes i can use normal find 
but sometime people use scope on tree
i think this is not expected behavior
like this line https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TreeBehavior.php#L430
in that line i expected default argument ('for= null ) for returned root nodes but bellow that check empty(null)

**Comment by ADmad** [comment]
> but sometime people use scope on tree

So include the scope in conditions

> i expected default argument ('for= null ) for returned root nodes

The docblock clearly states it needs to be an id: "- for: The id of the record to read."
