### ISSUE TITLE
Error with cache

### ISSUE THREAD

**Issue by RodriguezJaime** [cakephp/cakephp#8775]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP 2.7.5
* Platform and Target: 
Windows 7
PHP Version 5.6.3
Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3

### What you did
I'm trying change the code of the views, but I can't see the changes.

I set
Configure::write('Cache.check', false);
Configure::write('Cache.disable', true);
Configure::write('debug', 2);

but It's the same.

**Comment by markstory** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
