### ISSUE TITLE
Pagination with DISTINCT fields

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#8778]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.8.3
- Platform and Target: Apache 2.4, MySQL, Oracle, PHP 5.5
### What you did

Pagination with DISTINCT field.
### Expected Behavior

Return correct pages.
### Actual Behavior

`PaginatorHelper` return more pages then is it. 
Because `paginateCount();` always use `COUNT(*) as count`.

In documentation is wrote:
http://book.cakephp.org/2.0/en/core-libraries/components/pagination.html#custom-query-pagination 
_"In CakePHP 2.0, you no longer need to implement paginateCount() when using group clauses. The core find('count') will correctly count the total number of rows"_.

Maybe should be work with `DISTINCT` fields too?

Actual my solution:

```
/**
 * Modyfikacja paginacji
 *
 * @see http://book.cakephp.org/2.0/en/core-libraries/components/pagination.html#custom-query-pagination
 * @param ...
 */
public function paginate($conditions, $fields, $order, $limit, $page = 1, $recursive = null, $extra = array()) {
    if (!empty($fields)) {
        foreach ($fields as $field) {
            if (stripos($field, 'DISTINCT') !== false) {
                $this->__paginateDistinct = $field;

                break;
            }
        }
    }

    if (isset($extra['contain'])) {
        $contain = $extra['contain'];
    }

    if (isset($extra['joins'])) {
        $joins = $extra['joins'];
    }

    return $this->find('all', compact('conditions', 'fields', 'order', 'limit', 'page', 'recursive', 'group', 'contain', 'joins'));
}

/**
 * Modyfikacja zliczania przy paginacji
 *
 * @see http://book.cakephp.org/2.0/en/core-libraries/components/pagination.html#custom-query-pagination
 * @param ...
 */
public function paginateCount($conditions = null, $recursive = 0, $extra = array()) {
    $params = compact('conditions', 'recursive');

    if (isset($this->__paginateDistinct)) {
        $params['fields'] = $this->__paginateDistinct;
    }

    return $this->find('count', array_merge($params, $extra));
}`
```

**Comment by markstory** [comment]
Closing as 2.10 was the last feature release for 2.x and this wasn't ready for that release.
