### ISSUE TITLE
RFC: Event filters

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#8779]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
## Why would this be useful?

To filter the same kind of event that gets triggered with different subjects and data. For example very often you have the choice to either implement a specific event, for example 'UsersTable.created' in the `afterSave()` callback _or_ you have the option to filter the events by the subject and checking it for the `UsersTable` class.

The filtering becomes especially handy in cases when you can't clearly predict the event but have in interest in all kinds of event of a specific type but you only want to do something with it when a specific condition is met.
## How it (could) work

The event manager will detect if an event listener implements the filterable interface. If the interface is implemented the event manager will call the `filterEvent` method that is implemented and must return an EventFilter instance.

The event manager will then call the `checkEvent` method on the eventfilter class. If the result of the method call is true the event manager will call the actual method of the listener. If not it won't call it.
## FilterableInterface for event listeners

An interface that **must** be implemented by listeners that want to use event filtering.

``` php
interface Filterable {

    /**
     * Returns an event filter instance with configured checks
     *
     * @return \Cake\Event\EventFilter;
     */
    public function eventFilter();

}
```
## EventFilter class

The event filter class would work similar like the rule builders code wise: Taking callables to check the event.

``` php
/**
 * Filters an event object by given properties.
 *
 */
class EventFilter {

    /**
     * Subject filter
     *
     * @param \Cake\Event\Event $event
     * @param string|array One class as string or multiple classes to check for.
     * @return callable
     */
    public function subject(Event $event, $classes) {
        return function() use ($event, $classes) {
            $subject = $event->subject();

            if (is_string($classes)) {
                $classes = [$classes];
            }

            foreach ($classes as $class) {
                if ($subject instanceof $class) {
                    return true;
                }
            }

            return false;
        };
    }

    /**
     * Compare a value of the event data.
     *
     * @param \Cake\Event\Event $event
     * @param string $field
     * @mixed string $compareValue
     * @return callable
     */
    public function dataEquals(Event $event, $field, $compareValue) {
        return function() use($event, $field, $compareValue) {
            if (!is_array($event->data)) {
                return $event->data == $field;
            }
            $fieldValue = Hash::get($event->data, $field);
            if (is_object($fieldValue)) {
                return ($fieldValue instanceof $compareValue);
            }
            return ($fieldValue == $compareValue);
        };
    }

    public function checkEvent(Event $event) {
        foreach ($this->_filters as $filter) {
            if (is_callable($filter)) {
                if (!$filter($event)) {
                    return false;
                }
            }
        }
        return true;
    }

    public function add(callable $filter) {
        $this->_filters[] = $filter;
        return $this;
    }
}
```
## Example

``` php
class SomeListener implements FilterableInterface, EventListener {
    public eventFilter() {
        $filter = new EventFilter($this);
              ->add($filter->subject($this, '\App\Model\Table\UsersTable')
              ->add(function($this) {
                   return $this->data['role'] === 'Some Role';
              });
         return $filter;
    }
}
```

**Comment by burzum** [comment]
@markstory on my way  to BBQ, I'll review this when I have time this weekend.

**Comment by burzum** [comment]
@markstory #8657 seems to be similar but implementing a stack of conditions instead of a simple filter mechanism? Also there are lot's of changes to the controller? This seems to be more related to controller events and their filtering than being generic.

Honestly, I don't like it much because it seems to make thing more complicated than necessary. If I want to check something after some specific action was executed I can use the beforeRender() callback / event for example and check the passed request data for the action name.

**Comment by markstory** [comment]
The two ideas/approaches seemed similar as the example you provided of 

```php
class SomeListener implements FilterableInterface, EventListener {
    public eventFilter() {
        $filter = new EventFilter($this);
              ->add(function($this) {
                   return $this->data['role'] === 'Some Role';
              });
         return $filter;
    }
}
```
Is very similar to the `if`, `unless` mechanic added in #8657. I agree there is a bunch of additional controller code in that pull request. The [ConditionalCallable](https://github.com/cakephp/cakephp/pull/8657/files#diff-ef081da2cd604ef42e00c05b8f4f4216R24) and the example of

```
$eventManager->on('Controller.startup', ['if' => function () use ($entity) {
     return $entity->shouldRedirect();
 }], $redirect);
```
Is what I thought was similar to the proposal here.

**Comment by ADmad** [comment]
I too don't like the implementation of #8657 even though it does seem to try to achieve the same that is proposed here.

@burzum Check @markstory's original suggestion for implementing conditional filters https://github.com/cakephp/cakephp/issues/8105#issuecomment-174792521

**Comment by sukihub** [comment]
Apologies for the delay, I just pushed some changes to #8657 and found this.

Actually, @markstory's suggestion https://github.com/cakephp/cakephp/issues/8105#issuecomment-174792521 is implemented completely (or am I missing something?) and can be used without everything else. The rest of the PR is just code sugar, so that the usage of conditional listeners is less verbose.

I also just extracted a bit of that code sugar from Controller class to EventDispatcherTrait.

> If I want to check something after some specific action was executed I can use the beforeRender() callback / event for example and check the passed request data for the action name.

Checking the request data for the action name was exactly what I was trying to solve in the first place - see #8105. I just don't like it, declarative approach is just so much easier to read. 

I agree that ConditionalCallable is simiar to event filter proposed here. And having an API that would enable to add/manipulate conditions/filters (which is only possible through constructor's `$options` now) seems like a good idea to me.

> I too don't like the implementation of #8657

:-) Can you be more specific?

**Comment by markstory** [comment]
Can this be closed now?

**Comment by burzum** [comment]
@markstory I would still like to have a more specific class for doing the filtering than the decorators but OK, if you like to close it. Maybe I can just add an event filter decorator that allows to filter by the subject class via checking an array of allowed (or denied) classes via instanceof against the subject?

**Comment by markstory** [comment]
Another decorator sounds reasonable. It might be nice to have a higher-level API for using the event decorators as well.
