### ISSUE TITLE
Csrf component option csrfUseOnce - default false

### ISSUE THREAD

**Issue by hashmode** [cakephp/cakephp#8781]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.8

There was a feature that I liked a lot in cake 2.x Security component - `csrfUseOnce` which would generate unique token for each request, though in some applications it could create trouble(so had to be set as false), but in some cases it would provide better security and prevent double form submission.

Though I admit, that this can be implemented manually, but I think it would be nice to have it in core - however with default as false.

What are the cons of adding this option in `CsrfComponent` but **by default having it as false** - to not break the compatibility.

Thank you

**Comment by markstory** [comment]
The issue with the `useOnce` option was that it relies on a storage solution that provides atomic actions. In 2.x the storage was in the session which frequently does not have atomic storage semantics, reducing the protection they provide. I'm not sure that conflating one-time use tokens and multi-use CSRF tokens was a good idea, and isn't something I'd like to repeat.

With that said providing a single-use token solution could be handy.

**Comment by hashmode** [comment]
@markstory so do you mean making separate token that would validate only whether form was submitted - and would work independently from `csrf_token` ?

**Comment by markstory** [comment]
@hashmode Yes.

**Comment by zledwon** [comment]
I was told by security expert (hired to check my web app) that it is much safer to store CSRF Token is session than in a cookie. @markstory Should I be worried about this?

**Comment by markstory** [comment]
Why is it safer? Sessions are also backed by a cookie value. Wouldn't compromised cookies break both scenarios?

**Comment by zledwon** [comment]
That's exactly what I think too, but this security guy messed up in my head... :)
