### ISSUE TITLE
Array input on HtmlHelper::images

### ISSUE THREAD

**Issue by ross-chater** [cakephp/cakephp#8782]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: Not relevant

### HtmlHelper::images

Allow array to be passed as optional, for iterating through multiple images.

I'm working on it as we speak. See what you think.

**Comment by jhli** [comment]
Why if you can doba foreach and every img must take an alt and could take an title, not to mention css size and other stuff?
