### ISSUE TITLE
Session::renew() triggers "Session object destruction failed"

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8785]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Apach2, Ubuntu 16, PHP 7.0.5

### What you did

I wrote a "remember me" component that restores the authorized user via a cookie when the session has expired.

Set session time-outs to 30 minutes, allowed session to expire and then called `AuthComponent::setUser` from `beforeFilter` in Component.

My session config from app.php

```
    'Session' => [
        'cookie' => 'ahtag',
        'defaults' => 'database',
        'timeout' => 30,
        'handler' => [
            'model' => 'UserSessions'
        ]
    ],
```

### Expected Behavior

Should be able to write the auth data to session storage without any errors.

### Actual Behavior

Triggers the following error.

```
session_regenerate_id - [internal], line ??
Cake\Network\Session::renew() - CORE/src/Network/Session.php, line 576
Cake\Auth\Storage\SessionStorage::write() - CORE/src/Auth/Storage/SessionStorage.php, line 101
Cake\Controller\Component\AuthComponent::setUser() - CORE/src/Controller/Component/AuthComponent.php, line 631
App\Controller\Component\UserSessionComponent::beforeFilter() - APP/Controller/Component/UserSessionComponent.php, line 153
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 386
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 356
Cake\Controller\Controller::dispatchEvent() - CORE/src/Event/EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE/src/Controller/Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 36
```

So I've read the previous issues that have reported this, but there doesn't appear to be a work around. I saw the PR that added this logic to fix it previously.

```
        if (session_id()) {
            session_regenerate_id(true);
        }
```

All other references to this error mention temp files used by PHP, but I'm using the database for storing sessions. So I figure there might be something wrong with the database handler.

**Comment by thinkingmedia** [comment]
I suspect this is the problem in `DatabaseSession.php`.

```
    public function destroy($id)
    {
        return (bool)$this->_table->delete(new Entity(
            [$this->_table->primaryKey() => $id],
            ['markNew' => false]
        ));
    }
```

The above returns `false` if the record was missing, but take a look at the `gc` function.

```
    public function gc($maxlifetime)
    {
        $this->_table->deleteAll(['expires <' => time() - $maxlifetime]);
        return true;
    }
```

The above deletes all expired records.

So, I am thinking that after a session has expired it's deleted by `gc`, and then the `session_regenerate_id(true)` triggers a call to the delete method which returns false for failure. Thus the error is trigger.

How on earth do you even unit test this?

**Comment by markstory** [comment]
Closing as a pull request is open now.
