### ISSUE TITLE
Postgres IDs collide with fixture records if unit tests perform inserts

### ISSUE THREAD

**Issue by emersonthis** [cakephp/cakephp#8799]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1.
* Platform and Target: hosted on Heroku php/apache2 instance, using Postgres DB.

### What you did

First, create a ThingFixture in ThingFixture.php...
```
public $records = [
    [
        //'id' => 1,
        'name' => 'Foobar',
        'width' => 800,
        'height' => 600,
     ],
];
```
Note: this problem occurs with and without specifying the id of the fixture record.

Then try to write a unit test that inserts a record...

```
    public function testValidationDefault()
    {
        $newThingData = [
            'name' => 'Barfoo',
            'height' => 111,
            'width' => 222,
        ];
        $thing = $this->thingTable->newEntity($newThingData);
        $savedThing = $this->thingTable->save($thing);
        $this->assertInstanceOf('App\Model\Entity\Thing', $savedThing);
        ...
```
 
### Expected Behavior
If the insert data is valid the test should pass.

### Actual Behavior
Instead, a unique violation will be thrown...

`PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "things_pkey"`

...and the test will fail.

I think this means that the postgres sequence is being broken when the fixture data is being inserted.

The only way I know to avoid this is to delete all the records within the test, before doing an INSERT, or to manually reset the sequence (as discussed in [this SO question](http://stackoverflow.com/questions/33678689/cakephp-3-model-unit-test-fails-duplicate-key-value), both of which are icky.

**Comment by ADmad** [comment]
Fixtures shouldn't have values set for auto increment / sequence field. So error when specifying `id` are expected. But without `id` things should work fine. Can you please show you full actual fixture class.

**Comment by emersonthis** [comment]
Here's the complete fixture file. I do see the autoIncrement setting on some fields. So I should remove that?

For what it's worth, I didn't add those settings. The fixture was generated with `bake` command: `./bin/cake bake fixture --quiet --records --count 1000 --force Devices`

```
<?php
namespace App\Test\Fixture;

use App\TestSuite\Fixture\TestFixture;

/**
 * DevicesFixture
 *
 */
class DevicesFixture extends TestFixture
{

    /**
     * Fields
     *
     * @var array
     */
    // @codingStandardsIgnoreStart
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 10, 'autoIncrement' => true, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null, 'unsigned' => null],
        'nickname' => ['type' => 'text', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'hash' => ['type' => 'text', 'length' => null, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null],
        'width' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        'height' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        'screen_id' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        'last_checkin' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null],
        'created' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'modified' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'hardware_id' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
            'hash_uniq_key' => ['type' => 'unique', 'columns' => ['hash'], 'length' => []],
        ],
    ];
    // @codingStandardsIgnoreEnd

    /**
     * Records
     *
     * @var array
     */
    public $records = [
        [
            'id' => 1,
            'nickname' => 'Foo bar',
            'hash' => 'v56r5',
            'width' => 800,
            'height' => 600,
            'screen_id' => 1,
            'last_checkin' => '2016-05-06 17:14:00',
            'hardware_id' => 1
        ],
    ];
}
```

**Comment by emersonthis** [comment]
I made `'autoIncrement' => null` for the `id` field and removed the `id => 1` from the $records. Now it works! But I'm still confused why. It's counter-intuitive to me that *removing* autoIncrement would prevent collisions (I would have expected to have to add it). Also I'm confused about why `bake`ing the fixture caused it to be that way in the first place. Is that perhaps a bug with `bake`?

**Comment by markstory** [comment]
The thing you need to remove is `'id' => 1` in the fixture record.

**Comment by emersonthis** [comment]
Thanks Mark. The error happens with and without the id in the fixture record of the autoIncrement is true. I have to remove both to get it to work.  Is that expected?

**Comment by ADmad** [comment]
Does removing `'autoIncrement' => true` for `id` field fix the problem?

**Comment by ADmad** [comment]
The `id` field value definitely needs to be removed from `$records`.

**Comment by emersonthis** [comment]
@ADmad It seems to be that I need `'autoIncrement' => null` and the `id` field removed from records. The combination makes things work. I'm still a bit fuzzy on why... seems like omitting the `id` and *not* using `autoIncrement` is what makes autoIncrementing actually work... unless maybe that `autoIncrement` setting is designed for MySQL or something? Is this a Postgres-specific issue?

**Comment by ADmad** [comment]
The core fixtures don't have `'autoIncrement' => true` for `id` field and things work fine for MySQL and Postgres, so I guess the fix is to make bake not add 'autoIncrement' => true`.

**Comment by markstory** [comment]
We need autoIncrement => true for mysql. Perhaps the postgres schema generation needs to be updated instead?

**Comment by emersonthis** [comment]
Yea that’s what I was thinking. Sounds like my original problem was more of a side-effect from a sub-optimal default when baking fixtures for Postgres. Would it be helpful for me to open a new issue to address that? Or maybe update this one?

**Comment by lorenzo** [comment]
@emersonthis open a new one please
