### ISSUE TITLE
Collection::unfold does not continue collection chain

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8806]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Apache 2, PHP 7, MySQL

### What you did

The following raises an exception that collection requires an array or iterator.

```
        (new Collection(['foo']))->unfold()->filter()->toArray();
```

### Expected Behavior

Expect the `unfold` function to flatten the array and continue the `Collection` chain.

### Actual Behavior

Throws the following exception.

```
Exception: Only an array or \Traversable is allowed for Collection in [C:\work\tags\web\vendor\cakephp\cakephp\src\Collection\Collection.php, line 47]
2016-05-10 19:29:20 Error: [InvalidArgumentException] Only an array or \Traversable is allowed for Collection
Stack Trace:
#0 C:\work\tags\web\vendor\cakephp\cakephp\src\Collection\Iterator\UnfoldIterator.php(84): Cake\Collection\Collection->__construct('foo')
#1 [internal function]: Cake\Collection\Iterator\UnfoldIterator->getChildren()
#2 [internal function]: FilterIterator->rewind()
#3 [internal function]: IteratorIterator->rewind()
#4 C:\work\tags\web\vendor\cakephp\cakephp\src\Collection\CollectionTrait.php(480): iterator_to_array(Object(Cake\Collection\Iterator\FilterIterator), true)
#5 C:\work\tags\web\lib\Sync\src\SyncResource.php(95): Cake\Collection\Collection->toArray()
```

Am I misunderstanding what `unfold` is suppose to do?

I thought it would work like `flatten` in Lodash.

https://lodash.com/docs#flatten

**Comment by thinkingmedia** [comment]
Oh, the exception goes away if I force the array to have a nested array.

```
    (new Collection([['foo']]))->unfold()->filter()->toArray();
```

Looks like unfold just assumes the elements are also arrays. That makes it very limited to use.

**Comment by markstory** [comment]
>    Looks like unfold just assumes the elements are also arrays. That makes it very limited to use.

To a degree. The documentation states that

> Creates a new collection where the items are the  concatenation of the lists of items generated by the transformer function applied to each item in the original collection.
>
> The transformer function will receive the value and the key for each of the items in the collection, in that order, and it must return an array or a  Traversable object that can be concatenated to the final result.
>
> If no transformer function is passed, an "identity" function will be used. This is useful when each of the elements in the source collection are lists of items to be appended one after another.

Given that you did not provide a transformer, the code is working exactly as it is documented.

**Comment by thinkingmedia** [comment]
Okay, I was looking for something that worked like the `flatten` function in lodash. I guess I misunderstood what it does.

**Comment by markstory** [comment]
We could add a flatten() method to recursively flatten() a collection.

**Comment by thinkingmedia** [comment]
Turns out that flattening an array is easy. I have this little function that does it.

```
    /**
     * Flattens an array
     *
     * @param array $items
     * @return array
     */
    public static function flatten(array $items)
    {
        $arr = [];
        array_walk_recursive($items, function ($a) use (&$arr) {
            $arr[] = $a;
        });
        return $arr;
    }
```

**Comment by thinkingmedia** [comment]
I'm afraid that I find the `Collection` code a little confusing, but here is my attempt at a `flatten` function for the `CollectionTrait`.

```
    public function flatten()
    {
        $arr = [];
        array_walk_recursive($this->unwrap(), function ($a) use (&$arr) {
            $arr[] = $a;
        });
        return new Collection($arr);
    }
```

That seems to simple to be correct, lol.

**Comment by markstory** [comment]
Generally we'd not eagerly evaluate the collection. Instead of walking the data with array_walk_recursive, we would use RecursiveIterators that would flatten the dataset as it is iterated later on.

**Comment by mirko-pagliai** [comment]
I re-open this discussion. Even to me it seems that the `unfold()` method does not work as I would expect, maybe is it the case to rethink?

In any case, the `Hash::flatten()` method works fine.
