### ISSUE TITLE
Bug: Flash set in AppController::beforeFilter does not clear when rendered in layout

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#8813]
This is a bug in CakePHP Version: 3.2.3.

### What you did
In the AppController, I set a Flash message:
```
<?php
	namespace App\Controller;
	use Cake\Controller\Controller;
	use Cake\Event\Event;
	
	class AppController extends Controller
	{
		public function initialize() {
			$this->loadComponent('Flash');
		}
		
		public function beforeFilter(Event $event) {
			parent::beforeFilter($event);
			
			$this->Flash->success('Test.');
		}
	}
?>
```

In the default layout, it render the Flash message:
```
<?php echo $this->Flash->render(); ?>
```

### Expected Behavior
Every time I request the page, there should be one visible Flash message. After removing the `$this->Flash->success('Test.');` from the Controller, the Flash message should not be visible when next viewing the website.

### Actual Behavior
On the first view, there is one Flash message. However, when viewing the page again, there are two Flash messages visible. From then on, on every request, two Flash messages are rendered, as if the previous request was not correctly cleared. When `$this->Flash->success('Test.');` is removed from the Controller, a single Flash message is still displayed on the next request.

The problem seems only to occur when the Flash message is set in the AppController, in either the initialize, beforeFilter or beforeRender method.

**Comment by dereuromark** [comment]
Sounds to me like you are having some redirect in there that causes this issue.
Please confirm using Firefox/Firebug and checking what is going on there.
Your expecation is exactly how it currently works for me, and probably all others.

**Comment by AD7six** [comment]
Probably you are going to have a broken asset link( to a css, js or image) that is reaching your application (because the file doesn't exist) - and since you're setting the flash message on all requests, that's where the behavior you're experience is coming from.

**Comment by markstory** [comment]
I'm not able to reproduce this. I put a flash message in my controller's `initialize()` and only ever saw one message. Please make sure you don't have any 404 messages, and are not using `requestAction()` anywhere.

**Comment by advitum** [comment]
Sorry about that. I indeed had a broken asset link.
