### ISSUE TITLE
2.x 'fields' relation option neglected by Containable behavior

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#8814]
When containing a HABTM relation with Containable, it returns all fields of the join table.

For example for `Port` hasAndBelongsToMany `Iface` through `PortsInterrface`.

Tables
- ports
- interfaces
- ports_interfaces

So when I contain `Iface` in a query on the `Port` model, I will get back all fields from `PortsInterface`.

Since I keep additional, informational fields on this table, which I don't need for most queries, I would like to query only the necessary fields, like `port_id`, `interface_id` and may be `id`.

So I found the `fields` option for relations, which states:

> **fields**: A list of fields to be retrieved when the associated model data is fetched. Returns all fields by default.

http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#hasandbelongstomany-habtm

But obviously, this option has no influence on Containable.

I guess this is a less known limitatoin of Containable, but I didn't see any not about this in the docs.
So this is probably more of a documentation issue, than anything else.

**Comment by dereuromark** [comment]
Should this be moved to docs repo instead?

**Comment by ravage84** [comment]
@dereuromark  Fixing it would be nicer but I guess it's OK to just document it.

**Comment by dereuromark** [comment]
The motivation for 2.x fixes of this kind of level is rather small these days I would imagine.

**Comment by ADmad** [comment]
Closing as the issue has gone stale and hasn't had any activity in a long time.
