### ISSUE TITLE
Query::insert() doesn't reset previous data values

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#8815]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Apache 2.4, MySQL 5.5

### What you did

```php
$c = \Cake\Datasource\ConnectionManager::get('default');
$q = $c->newQuery();
$q->into('tmp');
$q->insert(['a', 'b']);
$q->values['a' => 1, 'b' => 2]);
$q->insert(['a', 'b']);
debug($q);
```

### Expected Behavior
The query shouldn't have any values because the `insert()` method should reset them according to the API docs.

### Actual Behavior

As shown here, it still has the values assigned before the second `insert()` call.

```
########## DEBUG ##########
object(Cake\Database\Query) {

	'(help)' => 'This is a Query object, to get the results execute or iterate it.',
	'sql' => 'INSERT INTO tmp (a, b) VALUES (:c0, :c1)',
	'params' => [
		':c0' => [
			'value' => (int) 1,
			'type' => null,
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => (int) 2,
			'type' => null,
			'placeholder' => 'c1'
		]
	],
	'defaultTypes' => [],
	'decorators' => (int) 0,
	'executed' => false

}
###########################
```

**Comment by lorenzo** [comment]
This is exactly how it is supposed to work, calls to the method are supposed to be additive. That said, there is no easy method for clearing the values. Would adding an `overwrite` argument to `insert` work for you?

**Comment by berarma** [comment]
I don't need this behavior. It's just that it seemed an inconsistency in the docblock and wanted to report it. I hope I haven't misunderstood it.

The docs for this method say: "Note calling this method will reset any data previously set with Query::values()."

I think removing the lines commented here would be enough to make the code follow the docs:
```php
        //REMOVE if (!$this->_parts['values']) {
            $this->_parts['values'] = new ValuesExpression($columns, $this->typeMap()->types($types));
        //REMOVE }
```

Anyway, I don't mind, I'm just suggesting to fix either the docs or the code in case I'm right.

**Comment by ADmad** [comment]
It's the docblock that needs to be fixed, not the code.

**Comment by markstory** [comment]
The documentation used to be accurate, but was changed in d2f7819e as part of the work to do automatic identifier quoting. I'm not sure just updating the docs is a good idea. Right now the method only does half its work the second time it is invoked, as the `ValuesExpression` doesn't get updated.

**Comment by markstory** [comment]
Pull request up now.

**Comment by berarma** [comment]
Well spotted @markstory, I didn't thought about what would happen when calling `insert()` with different arguments the second time.
