### ISSUE TITLE
get leaf in tree behavior

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#8817]
This is a (multiple allowed):
- [x] enhancement

new method to extract Leaves from tree behavior
If you agree, I will open a new PR
Comments and suggestions are welcome

**Comment by markstory** [comment]
What would the method look like? What kind of scenarios would it be useful in?

**Comment by saeideng** [comment]
> What would the method look like? 
> 
like this
```
public function findLeaf(Query $query, array $options){
        return $this->_scope($query)
            ->where([
                "$left +1 =$right "
                    . . .
            ])
}
```
another option (maybe)
'for' => leaf(s) of a node

**Comment by ADmad** [comment]
What's your use case which requires getting leaves?

**Comment by saeideng** [comment]
for example some stores  need to add product just into leaves 
this behavior not needed often But it is useful

**Comment by ADmad** [comment]
Rarely needed features are not good candidates for being added to core, especially when they can be easily achieved through app / plugin code.

**Comment by ADmad** [comment]
Closing for reason stated above.
