### ISSUE TITLE
Hash raises php error when merging nested array with string

### ISSUE THREAD

**Issue by hkuclion** [cakephp/cakephp#8819]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Windows, PHP 5.6

### What you did

```php
Hash::merge(
	array('hkuc'=>array('lion')),
	array('hkuc'=>'lion')
);
Hash::merge(
	array('hkuc'=>array('lion')),
	array('hkuc'=>array('lion')),
	array('hkuc'=>'lion')
);
```

### Expected Behavior

both should return
array('hkuc'=>'lion')

### Actual Behavior
the first works properly, the second raises a PHP error saying
Fatal error: [] operator not supported for strings in Hash.php on line 753

### Possible Reason and Solution

```php
Line 753:$curMerge[1][] = $val;
```

uses [] without checking whether $curMerge[1] is an array
I tried change it to

```php
if(is_array($curMerge[1]))$curMerge[1][] = $val;
else $val=$curMerge;
```

and it worked

-----------------------edit------------------------
later checked Line 755 has the same problem

**Comment by markstory** [comment]
Pull request up.
