### ISSUE TITLE
Add support for EXISTS conditions in WHERE clouse.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8820]
* [x] enhancement
* [x] feature-discussion (RFC)

This can be RDMBS specific issue.

For example:
Lets say User hasMany Articles. Association is made trought additional join table. 
Now lets say, that user can have large articles collection and can have no article at all. 

I want to get all users that have at least one article (association is not empty)

In SQL efficient way to do this is to include EXISTS in where clouse like this:
`
SELECT * FROM users WHERE EXISTS (SELECT * FROM users_aricles WHERE user_articles.users_id=users.id)`

This is much more efficient then JOINS. 

This cannot be done trought $query->matching() nor $query->contains() as both will include joins.
In my case it is taking over 10s for query as all joins must be made for all relations, while using EXISTS shortends the same task in less then 10ms.

What I am doing now in cake is:
```
        $query = $this->PrintedMails->find();
        $query->mapReduce($mapper, $reducer)
            ->orderDesc("printDate")
            ->distinct("PrintedMails.id")
            ->where($query->newExpr("EXISTS (SELECT * FROM printed_mails_$tableSuffix pme WHERE pme.mails_id=PrintedMails.id)"));
```

So the point is to add the possibility to only check for connection between tables as condition. 

If DB driver would not support EXISTS-alike syntax, it could always fallback to joins and child-not-null check

**Comment by jhli** [comment]
Take a look if you can achieve the same via IN in cakephp3

**Comment by Antoniossss** [comment]
@jhli can you elaborate how can I sute IN insteed of JOINS os EXISTS? 
Do you mean SQL's IN or some other IN in Cake's ORM that I am not aware of ?

**Comment by jhli** [comment]
Pseudocode where(user_id IN => $subquery)

**Comment by jhli** [comment]
Eh Users.id in...

**Comment by Antoniossss** [comment]
@jhli I dont have IDS's of those users as I need to get those. I think you have misunderstood the issue here.

**Comment by jippi** [comment]
@Antoniossss could `->having()` be what you are looking for?

**Comment by Antoniossss** [comment]
Matching will perform JOIN operation whitch is expensive in case where collection is large.
I didnt say it is not possible using cake (I have pointed out already that `matching` and `contain` are the bottlenecks here). I need only to check if association is not empty for every user in the db - this is what EXISTS is ideal for.

**Comment by jippi** [comment]
@Antoniossss sorry, missed it in your ticket description :) 

`EXISTS` could be a nice add-on, depending on what other databases support

if its supported by all of them, it should be fairly trivial to add in :)

**Comment by Antoniossss** [comment]
@jippi Just as I tought. If we would have `$query->exists(AssiciationName)` then it would be driver dependent, but translator can change this into EXISTS subquery or fallback to `$query->matching()` implementaion if this clause is not supported by used RDBMS. 
I am glad that we are on the same wavelenght now ;)

**Comment by jippi** [comment]
@Antoniossss want to give it a stab at implementing it ? :)

**Comment by Antoniossss** [comment]
It is not like I want everybody do the work for me, but I dont feel that I am able to implement such feature in a decent way as my knowlage of cake internals is still poor. However I can give it a shot next week. I am asked to do minor change on the other issue so I guess that forking cake is just a matter of time anyway.

**Comment by jippi** [comment]
I think the approach would be to look at `Database/Query.php` in `_conjugate` and the methods calling it 

Also `Database/Expression/QueryExpression.php` which have the methods present you want to add `exists` to

**Comment by thinkingmedia** [comment]
@Antoniossss I think this could be a great performance addition to cake.

**Comment by ionas** [comment]
@Antoniossss 

jhli was me from my mobile (I need to rename the accounts!)
I took another look and isn't this giving you the same output?

Possible with IN and subquery in CakePHP3:
```sql
SELECT *
FROM customers
WHERE customers.id IN (
    SELECT addresses.customer_id
    FROM addresses
    WHERE addresses.customer_id = customers.id
);
```

vs your desired EXISTS support, AFAIU:
```sql
SELECT *
FROM customers
WHERE EXISTS (
    SELECT NULL
    FROM addresses
    WHERE addresses.customer_id = customers.id
);
```

In case it does, could you run it on your large data sets, compare performance and also compare `EXPLAIN` and `EXPLAIN ANALZYE` (PG) / `EXPLAIN EXTENDED` (MARIA)

**Comment by ionas** [comment]
On tables with around 5000 records each this you are *spot on* for performance:
**70ms** for `SELECT * FROM customers WHERE EXISTS (SELECT NULL FROM addresses WHERE addresses.customer_id = customers.id);` vs **700ms** for `SELECT * FROM customers WHERE customers.id IN (SELECT addresses.customer_id FROM addresses WHERE addresses.customer_id = customers.id);`

**Comment by thinkingmedia** [comment]
Oh I would be very careful about making performance claims when comparing `IN` and `EXISTS` because the two are handled differently by MySQL. There are cases where `IN` is faster, and cases where `EXISTS` are faster. The problem here is that the two are not the same thing internally. MySQL added `EXISTS` to handle big data problems where `IN` would perform poorly.

Reference: http://stackoverflow.com/questions/14190788/subqueries-with-exists-vs-in-mysql

**Comment by ionas** [comment]
I'd say I'd love a PR minus the automagic in case the adapter does not support exists (then it should simply fail).

**Comment by thinkingmedia** [comment]
@ionas I don't even know how this should be added. Is it a new method for query or a new type of contain?

I've also been thinking about the idea of adapter specific query builders. Maybe something like this.

```
    $query = $this->Model->find();
    if($query instanceof MysqlQuery) {
         $query->exists(.....);
    } else {
         throw new Exception("MySQL data source required for this feature.");
    }
```

The above would be an example of how a developer would work with the query object, but also gain access to data provider specific features.

**Comment by markstory** [comment]
If we're going to add support for `EXISTS` please do it as an extension to the `Cake\Database\QueryExpression` class. It provides all of the existing behavior for platform agnostic operators. From a quick look `EXISTS` seems to be fairly consistent across database vendors so we won't need a new expression class at least.

**Comment by skie** [comment]
To be honest use of EXISTS already possible in client code like this

`                return $query->where(function ($expr) use ($subquery) {
                    return $expr->add(new UnaryExpression('EXISTS', $subquery, UnaryExpression::PREFIX));
                });`

Only the issue here that UnaryExpression marked for internal usage, that IDE highlighted.

so final solution would be adding into ЙгукнУчзкуыышщт class next methods:

    /**
     * Adds a new condition to the expression object in the form
     * "EXISTS (...)".
     *
     * @param array $query the inner query
     * @param string|null $type the type name for $value as configured using the Type map.
     * @return $this
     */
    public function exists(ExpressionInterface $query)
    {
		return $this->add(new UnaryExpression('EXISTS', $query, UnaryExpression::PREFIX));
    }

and

    public function notExists(ExpressionInterface $query)
    {
		return $this->add(new UnaryExpression('NOT EXISTS', $query, UnaryExpression::PREFIX));
    }
