### ISSUE TITLE
FormHelper error message options not used

### ISSUE THREAD

**Issue by pperejon** [cakephp/cakephp#8821]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: detected on 3.0.18, master also has it.
* Platform and Target: not relevant

### What you did
I have a field "vat_number" which returns a validation message that contains HTML I don't want to be escaped, so I write:
`<?= $this->Form->input('vat_number', ['error' => ['escape' => false]]) ?>`
It keeps escaping the HTML, but if I write directly:
`<?= $this->Form->error('vat_number',null,['escape' => false]) ?>`
... it works.

### Expected Behavior
Validation message is not escaped when you set the options from the input function of FormHelper.

### Actual Behavior
It keeps escaping the message.

### Fix proposed
The fix is to change FormHelper 'cause it's not passing the parameters in the right order to the "error" function. Also if the "error" option is not passed it should be converted to an empty array.
```
...
        if ($options['type'] !== 'hidden' && $options['error'] !== false) {
            $options['error'] = isset($options['error']) ? $options['error'] : [];
            $error = $this->error($fieldName, null, $options['error']);
            $errorSuffix = empty($error) ? '' : 'Error';
            unset($options['error']);
        }
...
```

I'm preparing a pull request.

Regards,
Pedro.

**Comment by markstory** [comment]
Related to #8809 which is about the same issue.

**Comment by markstory** [comment]
Your proposed fix has the same issues as #8809, which is it looks like it will break translated error messages. Be careful about that when doing your fix. You might want to consider a whitelist of 'error options' that should be extracted into proper options.

**Comment by pperejon** [comment]
Sorry for the delay. I've had to learn how to use phpunit :)

@markstory, I haven't seen any impact with the translated errors functionalities. 

This solution is not very ellegant. I think error options in the input function should be separated in two different structures, to pass them separately to the error function as well, but it would break the backwards compatibility.

btw, I have a project running in 3.0 branch (current 3.0.18), will you merge the change on that branch too?

Thanks and regards.

**Comment by ADmad** [comment]
> btw, I have a project running in 3.0 branch (current 3.0.18), will you merge the change on that branch too?

No, bugfixes and enhancements are only done for current 3.2 branch.
