### ISSUE TITLE
Fatal error: Class 'Cake\Core\App' not found 

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#8825]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: PHP5.9 + Ngnix 1.4.9

### I use  git clone this repository from my server which system is ubuntu 14.04. config nginx server successful,and run my website ,then display:

Fatal error: Class 'Cake\Core\App' not found in /var/www/macnie/blog/vendor/cakephp/cakephp/src/Log/LogEngineRegistry.php on line 42

**Comment by thinkingmedia** [comment]
There are installation instructions associated with this project at the cakephp website.

http://book.cakephp.org/3.0/en/installation.html
