### ISSUE TITLE
New issue with cascading delete

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/cakephp#8826]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2
- Platform and Target: Apache, PHP 5.6, MySQL 5.5.

Hello,
Sorry to come back to this but there is again something I find strange in `delete/deleteAll` functionnality.
I created a [Gist](https://gist.github.com/2ndGAB/eba374c4f3638d4db21c0cef32df6e6c), but basically I have this structure:

Sitemessages hasMany SitemessageTitles
SitemessageTitles hasOne SitemessageTexts
SitemessageTitles hasOne SitemessageImages

So we discussed already [here](https://github.com/cakephp/cakephp/issues/8348) how to delete everything when I delete a Sitemessages and it works according to what's done in SitemessageControllers.php line 109.

But now if want to delete one of the SitemessageTitles as done in SitemessagesController.php line 76, it doesn't delete associated SitemessageTexts and SitemessageImages, despite dependent => true and cascadeCallbacks => true are set.

So I think that cascading deletes are problematic as it only work`s from the top level and not from intermediate levels. Why?

**Comment by markstory** [comment]
> But now if want to delete one of the SitemessageTitles as done in SitemessagesController.php line 76, it doesn't delete associated SitemessageTexts and SitemessageImages, despite dependent => true and cascadeCallbacks => true are set.

It looks like you are using [deleteAll](https://gist.github.com/2ndGAB/eba374c4f3638d4db21c0cef32df6e6c#file-sitemessagescontroller-php-L76) which doesn't honor any of the association callbacks.

**Comment by 2ndGAB** [comment]
The doc is maybe not precise enough here as it's only specified that deleteAll doesn't trigger `beforeDelete/afterDelete` events.

so we have to use `delete` here?

Not as easy to use as `deleteAll' where we can specify delete conditions.

**Comment by jhli** [comment]
I think it is fine how deleteAll works, however its name is not. updateAll and deleteAll dont carry that they are rather bare low level operations compared to find() validate() and save().

Would it be possible to add ->delete() as a query chain call that would delete all records of the built in finder as a subquery?

Similar for update() (however not sure how one could do bulk updates that way)?

**Comment by markstory** [comment]
> Would it be possible to add ->delete() as a query chain call that would delete all records of the built in finder as a subquery?

These methods already exist, but they provide the callback-less behavior we have today. Deleting with callbacks can be complicated, as it requires loading all the records up. Often times this can be expensive resource/time wise, and sometimes the entities have already been loaded. Perhaps the 'macro' methods could be `findAndDelete()` and `findAndUpdate()` to not overload the semantics of existing methods.

**Comment by 2ndGAB** [comment]
Ok Markstory but as I said already, the job has to be done. We cannot just delete top level records and let all associated as orpheans in DB because it takes time to remove these.  
It's always possible to reply immediately and do the job in background if necessary.

**Comment by ionas** [comment]
@markstory 👍 `findAndDelete()` and `findAndUpdate()`

How would they execute? When calling `->first()` or `->all()`?
Could `findAndUpdate()` get a callable as an optional argument, thus that one can do iterated inserts when executing via `->all()`?

**Comment by markstory** [comment]
> Ok Markstory but as I said already, the job has to be done. We cannot just delete top level records and let all associated as orpheans in DB because it takes time to remove these.

I agree, and there exist APIs that do this. But they require you to load the entities and using `delete()` on them. I understand that this is not the ideal API as it requires developers to iterate a record set and call delete. Which is where the suggestion of `findAndDelete()` comes from.

> It's always possible to reply immediately and do the job in background if necessary.

Sure in userland code that is always an option. In the framework side, we can't expect or rely on users running background job queues.

**Comment by saeideng** [comment]
how can implement `findAndDelete()`?
