### ISSUE TITLE
Adding "dependent" like feature to BelongsTO association

### ISSUE THREAD

**Issue by mylux** [cakephp/cakephp#8830]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Hello Everybody,
I would like to have your feedback about having a feature very similar to "dependent" option for BelongsTo associations. That should work pretty much the same as it works for HasMany. Considering the association: User HasMany Posts and Posts BelongsTo Users

If you set dependent = true in the HasMany association, than all posts should be deleted together with the user, but what if we had the possibility of adding the functionality in which the opposite is possible?

It might seem strange at a first look, but I have a good example:

I have a "MessagesTable", but every message should have ONLY ONE attachment.

So I've set a column Messages.attachment_id to ensure only one attachment would be possible for a message.

Although is a bit strange to do that, the only association that fits in this case is BelongsTo, so:

Messages BelongsTo Attachments

But as long as I delete a message, the attachments remain.

It would be nice to have a "dependent" option in this association to.
What do you think?

**Comment by markstory** [comment]
Couldn't you use a hasOne association?

**Comment by ADmad** [comment]
Why do you have attachment_id in messages table instead of message_id in attachments table and using HasOne association?

**Comment by ravage84** [comment]
@markstory  and @ADmad ask valid questions.

http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#hasone 2.x
http://book.cakephp.org/3.0/en/orm/associations.html#hasone-associations 3.x
``hasOne`` would provide you a ``dependent`` key.

So, I see no need for this feature.

**Comment by lorenzo** [comment]
I agree with everyone here, the feature already exists if you use the right associations classes.
