### ISSUE TITLE
Make https://cakephp.org (and subdomains) work or redirect to port 80

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#8832]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

### What you did
I put https://cakephp.org into my browser and got sad.

### Expected Behavior
https://cakephp.org should work!

### Actual Behavior
It tries to connect to port 443 and eventually times out.
```
$ telnet cakephp.org 443
Trying 173.203.218.184...
telnet: connect to address 173.203.218.184: Connection refused
```

I'm not sure if this is something on the backburner, but I didn't see an issue about it.  I know it's kind of trivial (so please tag the issue as such).  Is there a better place to put this issue?  I know this is not a cakephp code issue.

I just think it's a bit unprofessional when you go to https://cakephp.org and it just spins until timeout.

I don't know if https://letsencrypt.org/ supports wildcard certificates yet, but you'll need one because of api.cakephp,org, book.cakephp.org, etc...

One rebuttal might be "Why do we need SSL/TLS for what is essentially documentation?"  And that's a valid rebuttal.  But cakephp.org doesn't even redirect 443 to 80.  At the *very least* it should just do that.

**Comment by markstory** [comment]
Redirecting 443 to 80 sounds a like a good short term solution until we figure out how to get all the required certificates.

**Comment by kevinquinnyo** [comment]
For comparison (just similar MVC framework pages):

https://rubyonrails.org/  (same as https://cakephp.org -- just doesn't respond at all :( not cool)
https://laravel.com/ (works, and also redirects http to https)
https://www.djangoproject.com/ (works, and also redirects http to https)

I personally think that cakephp.org and *.cakephp.org should redirect from http:// to https:// by defualt.

I also know this is a "bikeshedding" issue and not that important, but it might actually help for SEO reasons too.

**Comment by josegonzalez** [comment]
@kevinquinnyo It's been brought up a few times, it is a bikeshedding issue, and we're working on getting it fixed.

In any case, pretty sure if you don't have a valid cert, you cannot issue a redirect to non-http from https.

**Comment by kevinquinnyo** [comment]
@josegonzalez Sorry for bringing it up again, then.

Although, I don't understand what you said:

> In any case, pretty sure if you don't have a valid cert, you cannot issue a redirect to non-http from https.

I read that a few times and I have no idea what you meant.  I'm gonna guess that you mean you can't redirect a port 443 request to port 80 without a valid cert?  If so I would dispute that.  It's just a port.  nginx or apache can redirect 443 to 80 very easily -- no actual certificate needs to be involved.

**Comment by kevinquinnyo** [comment]
Feel free to close this issue if it's being worked on, or isn't that important (maybe it just doesn't matter, i don't know).  I was just making an observation about [https://cakephp.org](https://cakephp.org) not working at all.

**Comment by josegonzalez** [comment]
I *think* - and I've been wrong before - the browser will pick up that it is trying to reach an https endpoint, ask for a cert, not get one, and then immediately bork. Again, could be wrong, and maybe it does the right thing.

I'll keep this open to take a look at potentially adding at least redirects tomorrow.

**Comment by AD7six** [comment]
@kevinquinnyo the problem is the sequence of events. the cert is checked _by the client_ before doing anything:

![screenshot from 2016-05-17 14-54-28](https://cloud.githubusercontent.com/assets/33387/15322855/60825f3e-1c3f-11e6-96c5-e47525ad915b.png)

It's of very limited use/value to handle https requests without a valid cert.

**Comment by kevinquinnyo** [comment]
@AD7six @josegonzalez Yeah actually you are both right about that.  :flushed:  That's a shame.  I thought that would be a quick fix.

**Comment by thinkingmedia** [comment]
Guys, you should **never** redirect from HTTPS to HTTP. Even if you have a valid cert. If you don't support HTTPS and you have a valid cert the server should return status 503.

If you do not have a cert then the server should refuse the connection. Accepting insecure connections on HTTPS will get you flagged by the google webcrawler (not the browser). They could remove you from search results as it looks like your server has been compromised by an attacker.

Further more, you can redirect from HTTP to HTTPS because it never violates any HTTP protocols. But with that said, you should only redirect **GET** requests to HTTPS. Never redirect a POST from insecure to secure as this exposes the message body. Sometimes people place `http://www.foo.com/` in the action of a form by mistake. This is why browsers will flag pages as insecure if they contain partial HTTPS content.

**Comment by dereuromark** [comment]
@thinkingmedia In theory that sounds right, but for example very popular apps like Whatsapp have a bug where you just post `www.xyx.de` and they would autocomplete this to `https://www.xyx.de` - effectivly breaking the link when there is no https for this domain. In that case IMO its OK to 301 to non https for the time being (tmp!) until you can provide an HTTPS cert (which you should in a sensitive time frame).

**Comment by thinkingmedia** [comment]
@dereuromark that's one way a man in the middle attack works. Depending upon how you go from HTTPS to HTTP. You risk flagging the web server as compromised to the google bot.

You guys are trying to fix something that is not broken.

If you want HTTPS to work then get a valid cert. I'll buy one for you if you want. You can get one for $17 at https://www.rapidsslonline.com and have it ready in 5 minutes.

**Comment by tersmitten** [comment]
What about using let's encrypt?

Or buying a wildcard (for about 75 euro a year)

**Comment by tersmitten** [comment]
@josegonzalez if you need any help on "getting it done" I'd like to lend a hand

**Comment by Wouter0100** [comment]
There are also SSL certificates available starting from ~4 euro a year (single domain). And free if using Let's Encrypt. Should't be a problem.

**Comment by josegonzalez** [comment]
Like I said before, we'll take care of it. Thanks for bumping the issue everyone.

**Comment by karmicdice** [comment]
When I am reading the CakePHP docs, why should I be worried about eavesdropping?
Unless it is discourse - which takes in the creds...

Use v/s Feature

**Comment by jorisvaesen** [comment]
I also posted this in a related issue but I rhink it's important because Google is using HTTPS as a positive value in pagerank.

Source: http://searchengineland.com/google-starts-giving-ranking-boost-secure-httpsssl-sites-199446

**Comment by inoas** [comment]
@josegonzalez Is this being resolved?

**Comment by dereuromark** [comment]
Unfortunately not yet, but it really should happen rather sooner than later to have https access here.

**Comment by phpnut** [comment]
This issue was moved to cakephp/cakephp.org#66
