### ISSUE TITLE
__ function returns array when a term exists as both a singular an plural key

### ISSUE THREAD

**Issue by Zuluru** [cakephp/cakephp#8833]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.8
- Platform and Target: n/a, I think

I'm running into a problem with the `__` function, and I'm not sure whether it's a bug in Cake, Aura\Intl, or my code. I've tried the same thing in Cake 1.3, and it works as I expect it to, but it's possible that my expectations are simply that way because that's how it worked in 1.3. :-)
### What you did

When I am building my menus, I use things like `__('Teams')`, but I also have pages that use things like `__n('Team', 'Teams', count($player->teams))`. The i18n shell extracts these into the default.pot separately, so when I translate it to French, it's like this:

```
msgid "Teams"
msgstr "Équipe"

msgid "Team"
msgid_plural "Teams"
msgstr[0] "Équipe"
msgstr[1] "Équipes"
```
### Expected Behavior

`__('Team')` should return 'Équipe' and `__('Teams')` should return 'Équipes'.
### Actual Behavior

If I call `__('Team')`, I correctly get 'Équipe' returned, and if I call `__n('Team', 'Teams', $x)`, I correctly get 'Équipe' or 'Équipes' returned, depending on the value of `$x`. But if I call `__('Teams')` I get back

```
Array
(
    [0] => Équipe
    [1] => Équipes
)
```

This is the case even if I eliminate the `msgid "Teams"` section, leaving only the plural definition.

In Cake 1.3, `__('Teams')` would simply return 'Équipes'. (Don't know what it might do in 2.x, as I skipped over that entirely.) So, whose bug is this? Posted this on [StackOverflow](http://stackoverflow.com/questions/37245525/cakephp-i18n-function-returns-array), and it was suggested that it looks like a bug to be reported here.

**Comment by lorenzo** [comment]
The only sensible thing would be to throw an exception or an error in that case. Since you cannot call a translation for plurals without specifying how many there are of the object

**Comment by thinkingmedia** [comment]
@lorenzo no, I think you misunderstand his issue. His translation file has duplicate keys. One used for a word, and one used for a plural.

`__` is matching the wrong ID.

The documentation shows that you can use plurals without using `__n`.

```
<h2><?= __('Popular Articles') ?></h2>
```

Greg's problem is that he defined both `__('Popular Articles')` and `__n('Popular Article','Popular Articles', $x)` in his templates. Afterwards `__('Popular Articles')` broke for translations. It should still work if he used a different ID for `__n`.

**Comment by lorenzo** [comment]
...or `__()` can also throw an exception to warn you about it

**Comment by thinkingmedia** [comment]
That will just tell you that the translation file is invalid. This should be fixed in the script that extracts the IDs. That's when the exception should be thrown.

**Comment by dereuromark** [comment]
@thinkingmedia Maybe someone can make a PR to show a possible fix here?

**Comment by thinkingmedia** [comment]
@dereuromark oh I see what you did there....

**Comment by Zuluru** [comment]
Is it intentional that one can never use `__()` to directly get the plural translation? As I said, this did work in 1.3.

Also, note that this problem occurs even if I remove the "solo" definition of "Teams" from the translation file, so it's not exactly an "invalid translation file" problem.

**Comment by thinkingmedia** [comment]
@Zuluru the argument for `__` is called singular.

```
    function __($singular, $args = null)
    {
        if (!$singular) {
            return null;
        }

        $arguments = func_num_args() === 2 ? (array)$args : array_slice(func_get_args(), 1);
        return I18n::translator()->translate($singular, $arguments);
    }
```

You should use `__n` for plural, and if you don't know the count pass it a large number (I guess).

**Comment by ndm2** [comment]
I think the question is to what extend CakePHP should stick to the behavior of `gettext` (the behavior most people are used to), which handles the exact same situation gracefully, ie it treats identical `msgid` and `msgid_plural` as separate IDs, that is `gettext('Teams')` will return `Équipe` and won't touch the plurals (tested using a different message to figure where exactly the message stems from), which will only be looked up when using `ngettext`.

**Comment by markstory** [comment]
If 'Teams' exists as a msgid, we should be try to honor and reflect that when `__()` is used in my opinion.

**Comment by Zuluru** [comment]
@thinkingmedia, using the `__n` function with a large number is not a good workaround, IMO; there are languages with multiple plural forms, where the one selected depends on the actual number. In such cases, I think it's useful to be able to specify a "generic plural", rather than me having to know the specifics of all such languages when I'm choosing what number to pass to `__n`.

As @ndm2 points out, this behaviour is supported by `gettext`, which it seems to me has probably had more i18n experts work on it in its lifetime than Cake has. Surely there's a reason they support it!

**Comment by markstory** [comment]
I took at look into why this happens tonight, and because of how `Aura\Intl\Translator` handles messages, we parse this po file:

```
msgid "Teams"
msgstr "Teams (translated)"

msgid "Team"
msgid_plural "Teams"
msgstr[0] "Team (plural 0)"
msgstr[1] "Teams (plural 1)"
```


Into a structure that looks like:

```php
[
	'Teams' => [
		(int) 0 => 'Team (plural 0)',
		(int) 1 => 'Teams (plural 1)'
	],
	'Team' => 'Team (plural 0)'
]
```

This means we not only lose the ability to preserve the singular translation for `Team`, but also `Teams` as a msgid. I'm considering changing the internal structure to prefix message keys with additional prefixes so we can more easily discern plural msgids, However, this translated messages where people have used `I18n::translator()->translate(..)` directly. It will also require changing the cache key names so that people don't have a bad time when upgrading.

In IRC @AD7six suggested using `\0` (null byte) for singular messages, but any arbitrary sigil value will work as long as it is consistently applied. Any thoughts or reservations on that approach?

**Comment by markstory** [comment]
One problem with prefixing msg keys is how to handle missing translations.

**Comment by lorenzo** [comment]
The best way we could do this is by changing the internal structure so we have many top level keys: normal, pluralized, and with context. That way you don't need to dynamically remove prefixes, and the lookups are easier to make depending of the function that was called. 

It is still for me a bad idea to support this case, even if gettext does it, and is more a call to action to encourage people to use the pluralization from intl instead of plural forms from gettext.

**Comment by AD7six** [comment]
> In IRC @AD7six suggested using \0 (null byte) for singular messages, but any arbitrary sigil value will work as long as it is consistently applied. Any thoughts or reservations on that approach?

Actually my suggesition was to suffix with `\0singular` or `\0plural`, i.e. the internal structure for the ticket scenario would become:

```
[
    'Teams\0singular' => 'Teams (translated)',
    'Team\0singular' => 'Team (plural 0)'
    'Teams\0plural' => [
        (int) 0 => 'Team (plural 0)',
        (int) 1 => 'Teams (plural 1)'
    ],
]
```

The suffix/prefix itself doesn't matter so long as there's no risk of collisions.

> The best way [...]

I'm in two minds as to whether that's a good idea or not, it's likely a cleaner result but more effort.

> It is still for me a bad idea to support this case [...]

I agree, collisions shouldn't exist, and indicate overloading the same context (or no context) with different meanings.

Regarding "well just assume `__('plural')` means `__(x, 'plural', some number)`" or similar suggestions - there are (in use) languages for which plural nouns (houses) differ from when there's a number (n houses) - doing that only works for a subset of languages, and is therefore not a solution/possibility.

**Comment by chinpei215** [comment]
No, we should fix this bug. I think you are talking about i18n things from the view point of English speakers. Because, for example, Japanese language doesn't have grammatical number. If a Japanese user developed an application, and if he want to translate it into English, the PO file would be like the following:
```
msgid "チーム"
msgid_plural "チーム"
msgstr[0] "Team"
msgstr[1] "Teams"
```
How does he avoid *collisions*? It would mean that any Japanese users cannot translate their applications into other languages right now.

But I understand the difficulty in implementing. Probably we would need to refactor I18n features.

**Comment by markstory** [comment]
> The best way we could do this is by changing the internal structure so we have many top level keys: normal, pluralized, and with context. That way you don't need to dynamically remove prefixes, and the lookups are easier to make depending of the function that was called. 

@lorenzo This is what I'm thinking as well. It will require changing internal structures, and how the Formatter classes work though.

**Comment by lorenzo** [comment]
Yeah, it would a big change indeed

**Comment by markstory** [comment]
@lorenzo Could it be something we fit into 3.3 though?

**Comment by lorenzo** [comment]
I think so @markstory 

@chinpei215 I was thinking more that everyone should use the intl message selector instead. I think the plural forms from gettext are not as powerful and flexible as using intl. That's what I was trying to get at before

**Comment by Zuluru** [comment]
Just wondering if anyone is still thinking about this. Doesn't look like a consensus reached on the path to take, and it's not assigned to anyone.

**Comment by markstory** [comment]
@Zuluru Thinking about but not doing much about it. All the solutions I've come up with so far cause other things to break.

**Comment by markstory** [comment]
Pull request up now.

**Comment by Zuluru** [comment]
I had a chance to update to 3.3.12 tonight, and while it's much better (it's no longer returning an array as per the issue name), it seems that there's still something not quite right. Haven't spent enough time with it to get a minimal example, or determine whether it will affect my project in the near term, but it looks like something that will bite someone eventually, so maybe now (while it's fresh) is the time to sort it out fully. What is the best way for me to report that? A brand new issue? A further comment here with details? A PR updating the tests with an example that should work but fails? I can try to find some time to dig into the implementation and see if I can come up with a fix, but not sure when that might happen, so it seems that getting it reported would be the first step.

**Comment by ADmad** [comment]
Any example showing the problem would be best way to start.

**Comment by markstory** [comment]
And a new issue :smile:

**Comment by Zuluru** [comment]
Spent some time reading up on various languages' plural rules in order to be able to fully describe the issue that I'm seeing, and I'm coming to the conclusion that it's actually a problem in how I'm building a few of my strings, so please consider this resolved. If I come across anything that I can't explain away or which requires unreasonable linguistic hacks to work around, I'll post a new issue at that time.

**Comment by markstory** [comment]
Soinds good!
