### ISSUE TITLE
3.x Regarding the deprecation and later removal of mcrypt_*

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#8835]
All ``mycrypt_`` functions wil be depcrecated in PHP 7.1 and in PHP 7.1+1 removed from the PHP core.

[PHP RFC: Deprecate (then Remove) Mcrypt](https://wiki.php.net/rfc/mcrypt-viking-funeral)

> In PHP 7.1, all mcrypt_* functions will raise an E_DEPRECATED notice. 

>  In PHP 7.1+1 (be it 7.2 or 8.0), the mcrypt extension will be moved out of core and into PECL, where people who *really* want to install it may still do so if they can install PHP extensions from PECL. 

For CakePHP **3.x**, only the ``Mcrypt`` class is affected:
https://github.com/cakephp/cakephp/blob/3.2.9/src/Utility/Crypto/Mcrypt.php

The tests already take account for missing ``mcrypt_`` functions:
https://github.com/cakephp/cakephp/blob/3.2.9/tests/TestCase/Utility/Crypto/McryptTest.php#L34
https://github.com/cakephp/cakephp/blob/3.2.9/tests/TestCase/Utility/SecurityTest.php#L80

**Comment by markstory** [comment]
Closing as users in 3.x can start using openssh instead of mcrypt. Generally people on newer versions of PHP [will already be using openssh](https://github.com/cakephp/cakephp/blob/3.2.9/src/Utility/Security.php#L144-L150) as it is preferred over mcrypt.
