### ISSUE TITLE
why select tinyint(1) only get 0 or 1?  

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#8839]
# My MySQL Table

id(int 11) username(varchar 50) status(tinyint 1)

1              macnie                            4

use CakePHP ORM SELECT:

```php
$data = $this->Users->find('all')->first();
```
then $data->status 's  value  is 1

why?

how can i get the true status value.

**Comment by ADmad** [comment]
tinyint(1) is used to emulate boolean in Mysql since it doesn't have type boolean. You can use tinyint(2).

**Comment by NitinPrakash** [comment]
LOL - NOT a solution :)

Could we have better solution ??

**Comment by rchavik** [comment]
Submit a patch to mysql to support boolean columns :)

**Comment by AD7six** [comment]
![screenshot from 2016-11-10 12-23-39](https://cloud.githubusercontent.com/assets/33387/20174914/8892065a-a740-11e6-8aa7-efbe7f8564d3.png)

From http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html @NitinPrakash

**Comment by NitinPrakash** [comment]
TINYINT[(M)] [UNSIGNED] [ZEROFILL]

A very small integer. The signed range is -128 to 127. The unsigned range is 0 to 255.

i Hope TINYINT can store values in range 0-10 ???

**Comment by inoas** [comment]
- The number within the type definition in the SQL schema for integers is for zerofill padding as far as I remember.
- CakePHP Schema only treats `tinyint(n)` where n = 1 as a boolean, as far as I remember
- You can easily use any other tinyint like `tinyint(2)` for the same efficient unsigned range. It will still be 256 steps. If you want more you will have to use mediumint, int, bigint etc.


> LOL - NOT a solution :)

Why is that not a solution?

>> Could we have better solution ??

> Submit a patch to mysql to support boolean columns :)

👍 (however the gain is minimal)

**Comment by NitinPrakash** [comment]
AT this point in my project i cant request my DBA to change tinyint(1) to tinyint(2) on an already LIVE Project with numerous online users ..

HOPE you understand the gravity of the situation..

**Comment by inoas** [comment]
Why can't you request your DBA to change tinyint(1) to tinyint(2)? Do you realize that it does not change the datatype AT ALL, nor the data being stored. It only affects you if you use the ZEROFILL flag, which at least I have never seen being used anywhere so far. **Do you?**

IMHO, the gravity of the situation is to either change the field or to submit a PR.

**Comment by thinkingmedia** [comment]
@NitinPrakash 

You can cast the TINYINT(1) to other types using an expression.

```
        $q = $this->Users->query();
        $this->Users
            ->find()
            ->select(['int_status' => $q->newExpr('CAST(status AS UNSIGNED INTEGER)')])
            ->all();
``` 

When you write to the database you can bind a value as integer.

```
        $q = $this->Users->query();
        $q->update()
            ->set(['status'=>$q->newExpr(':status')])
            ->bind(':status', 2, 'integer')
            ->where()
            ->execute();
```

If you don't want to do the above, then you can override the data type for a column in a table.

```
class UsersTable extends Table {
       protected function _initializeSchema(Schema $schema)
       {
               $schema->columnType('status','integer');
               return parent::_initializeSchema($schema);
       }
}
```

**Comment by GaganTiwari** [comment]
Thanks @NitinPrakash and @thinkingmedia for a good answer. 

I was also facing the same issues for TINYINT(1) situtaion. Finally I got solution.

THanks
