### ISSUE TITLE
Numbers localization for paginator

### ISSUE THREAD

**Issue by Sensetivity** [cakephp/cakephp#8840]
This is a (multiple allowed):
* [x] enhancement

* CakePHP Version: 3.2.9
* Platform and Target: Open Server 5.2.2

### What you did
In controller method I set I18n::locale('ar');

### Expected Behavior
I expected what numbers become to arabic.

### Actual Behavior
It displays normal European number insted of Hindu–Arabic

**Comment by markstory** [comment]
I'm not sure this is a feature that intl supports, but it might be.

**Comment by Sensetivity** [comment]
But we can do somethings like this.
```
for ($i = $start; $i < $params['page']; $i++) {
            $out .= $this->_formatNumber($templater, [
                'text' => $this->Number->format($i, ['locale' => Locale::getDefault()]),
                'page' => $i,
                'model' => $options['model'],
                'url' => $options['url'],
            ]);
        }
```

Instead of 

```
for ($i = $start; $i < $params['page']; $i++) {
            $out .= $this->_formatNumber($templater, [
                'text' => $i,
                'page' => $i,
                'model' => $options['model'],
                'url' => $options['url'],
            ]);
        }
```

**Comment by dereuromark** [comment]
A PR would be very welcome here.

**Comment by markstory** [comment]
@Sensetivity Yes that would work. I didn't completely understand what this issue was getting at.

**Comment by dereuromark** [comment]
@Sensetivity Are you able to provide PR here? Let us know if you need any help getting started.

**Comment by Sensetivity** [comment]
Okay, I`ll.

**Comment by markstory** [comment]
Closing as a pull request is open now.
