### ISSUE TITLE
3.2.9 existsIn causing saves to fail

### ISSUE THREAD

**Issue by birdy247** [cakephp/cakephp#8841]
This commit https://github.com/cakephp/cakephp/commit/66c4011 from this PR https://github.com/cakephp/cakephp/pull/8788/files is causing saves to fail (which I believe is wrong).

https://gist.github.com/birdy247/d424dd6a5bc08a66010e9af43e166999 Shows an example.

If I set a value in the beforeSave that was not passed in when patching the entity, the existsIn rule fails.  For example, a "User" has a "role_id".  I currently assign the role_id in the beforeSave.  This worked fine until version 3.2.9.  Now it fails as the role_id does not exist when checking the rules (even though I never set it before checking the rules).

**Comment by lilHermit** [comment]
I too experience problems with this commit since upgrading to 3.2.9. 

Code to replicate
```
$user = $this->Users->newEntity();

   if ($this->request->is('post')) {
       $user = $this->Users->patchEntity($user, $this->request->data);

       debug($user, false);
       if ($this->Users->save($user)) {
       } else {
         debug($user->errors, false);
       }
```

$this->request->data
```
[
    'name' => 'new user',
    'email' => 'dummy@dummy.com',
    'password' => 'mypass',
    'organisation' => [
        'name' => 'my second org',
        'min_size' => (int) 1,
        'max_size' => (int) 44
    ]
]
```

$user after patchEntity (notice both user and organisation have `new: true`
```
object(App\Model\Entity\User) {

    'name' => 'new user',
    'email' => 'dummy@dummy.com',
    'password' => 'mypass',
    'organisation' => object(App\Model\Entity\Organisation) {

        'name' => 'my second org',
        'min_size' => (int) 1,
        'max_size' => (int) 44,
        '[new]' => true,
        '[accessible]' => [
            '*' => true
        ],
        '[dirty]' => [
            'name' => true,
            'min_size' => true,
            'max_size' => true
        ],
        '[original]' => [],
        '[virtual]' => [],
        '[errors]' => [],
        '[invalid]' => [],
        '[repository]' => 'Organisations'
    
    },
    '[new]' => true,
    '[accessible]' => [
        '*' => true
    ],
    '[dirty]' => [
        'name' => true,
        'email' => true,
        'password' => true,
        'organisation' => true
    ],
    '[original]' => [],
    '[virtual]' => [],
    '[errors]' => [],
    '[invalid]' => [],
    '[repository]' => 'Users'

}
```

Errors after save
```
[
    'organisation_id' => [
        '_existsIn' => 'This value does not exist'
    ]
]
```

This works correctly if a) I comment out the existsIn rule or rollback to 3.2.8

**Comment by birdy247** [comment]
Rolling back to 3.2.8 also works for me

**Comment by markstory** [comment]
@lilHermit Are you also setting the `organization_id` during `beforeSave()`?

**Comment by lilHermit** [comment]
No because I want it to create a new organisation as http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-with-associations does with `$firstComment` in the example. Both user and organisation data is coming in via json (API endpoint)

**Comment by markstory** [comment]
I can see how the old behavior was helpful, but the current behavior is not 'incorrect' as when the rules run the field is empty and thus it should fail. Have you considered making your rule only apply on updates?

**Comment by stmeyer** [comment]
I have the same error. I set some values in beforeSave event and the rule ExistsIn stops saving. Only using the rule on updates is no option because in same cases the value can be set by a user. Is a second rule ExistsInOrEmpty possible?

**Comment by beporter** [comment]
> Have you considered making your rule only apply on updates?

That doesn't work if the relationship between the tables is optional (`NULL` is allowed), but you want to enforce referential integrity _when the foreign key **is** present_. What is the approach to perform that kind of check now?

Another question that I have to ask is why a breaking change was merged into a point release instead of (at least) saved for a minor version bump. Seems like this should have been a 3.3.0 thing.

**Comment by markstory** [comment]
> Another question that I have to ask is why a breaking change was merged into a point release instead of (at least) saved for a minor version bump. Seems like this should have been a 3.3.0 thing.

The fix was not intended to be breaking. Given the amount of grief this is giving people, I'll revert the change.

**Comment by beporter** [comment]
Just to be clear, I (we) are definitely not trying to cause you grief. 

As an alternative solution, could the core offer a **new** rule that enforced more strict restraint that the previous PR was after?

**Comment by markstory** [comment]
I'm not sure what we would call the new rule. The scenario in the problematic pull request seemed bad to me and lorenzo which is why the fix was merged.

> I found a bug with existsIn rule when testing that in my app (cake 3.2.8) with a Products, Sales and SaleDetails models, with SaleDetails belongsTo Products and Sales, allowed me to save a new Sale with new SaleDetails associated when sale_detail.product_id was null (not selected and the required attribute was missing in the browser).
> An SQL exception was raised. The existsIn rule were not applied. Because the patchEntity did not touch the product_id, so it was not marked as dirty.

From the discussion here, it sounds like people rely on trying to sneak around their own application rules. As for nullable fields, they are handled later in the `ExistsIn` rule as part of `$this->_fieldsAreNull()`.

**Comment by beporter** [comment]
That description to me sounds like the lack of use of the `requirePresence()` validator though, not something that needs to change in the core. Am I wrong in thinking that would have also caught the OP's problem?

**Comment by markstory** [comment]
@beporter That is fair, requiring presence would have caused a validation failure higher up.

**Comment by markstory** [comment]
Closing as a revert pull request is up now.
