### ISSUE TITLE
Content-Type check for HTTP code "PATCH" requests are not supported

### ISSUE THREAD

**Issue by icyrizard** [cakephp/cakephp#8843]
To be able to support `HTTP PATCH` requests we need to be able to check the `Content-Type` for these requests. However in `lib/Cake/Controller/Component/RequestHandlerComponent.php` in function `requestedWith` on l. 508 it returns null when the request type is 'patch', and stops right after executing the check for the type check of the request (see example below). This prevents us from building support for the PATCH HTTP request needed in order to comply to the SCIM ( simplecloud.info ) RFC.

I'm currently working on a small patch and am going to submit this through a pull request in Cake 2.x. Note that I did see support for this is in the 3.x CakePHP versions. It is well known that 3.x imposes a lot of breaking changes so migrating to the new version is not an option currently.

This is a:
* [x] enhancement

* CakePHP Version: 2.8.4
* Platform and Target: N/A

### What you did
Checking the Content-Type of the request.

### Expected Behavior
Also check the Content-Type for PATCH requests.

### Actual Behavior
Stopping if the request is anything other than a 'post', 'put', 'delete'
~~~PHP
if (!$this->request->is('post') && !$this->request->is('put') && !$this->request->is('delete')) {
   return;
}
~~~

### What I'm going to do
Add patch in  `lib/Cake/Controller/Component/RequestHandlerComponent.php`. 
~~~PHP
if (!$this->request->is('patch') &&
    !$this->request->is('post') &&
    !$this->request->is('put') &&
    !$this->request->is('delete')
   ) {
   return;
}
~~~
Add `patch` to the $_detectors in `lib/Cake/Network/CakeRequest.php` around l.99
~~~
protected $_detectors = array(
    ...,
    'patch' => array('env' => 'REQUEST_METHOD', 'value' => 'PATCH'),
    ...,
);
~~~

**Comment by dereuromark** [comment]
PR is now open for it: https://github.com/cakephp/cakephp/pull/8836
