### ISSUE TITLE
How  to apply Role based authorization after login in cakephp 2.7?

### ISSUE THREAD

**Issue by kishanjvns** [cakephp/cakephp#8845]
Hii Seniors ,I'm new on cakephp . I have implementd a code for login and I m trying to providing Role based action for differecnt users.
Such as I have a table in which i store id and role (Admin,Normal,SubAdmin).
I want that super admin can add delete update and edit and view everones record.
Admin can only edit and delete add users and cant delete/edit his record.
How could i achieve this.

**Comment by dereuromark** [comment]
Please see the documentation and also https://github.com/FriendsOfCake/awesome-cakephp#authentication-and-authorization

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
