### ISSUE TITLE
Http client stalls on get request for given domain, while cURL works well

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8846]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Ubuntu 14.04, MySQL 5.7, PHP 7.0.6

### What you did

I am not sure what is going on, because I get different results on my Windows workstation.The DNS lookup for `safefinder.info` fails which makes me think that my ISP has blocked it for some reason.

```
> ping safefinder.info
Ping request could not find host safefinder.info. Please check the name and try again.
```

On my production server (Ubuntu 14) the DNS resolves to an IP.

```
$ dig safefinder.info

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> safefinder.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17041
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;safefinder.info.               IN      A

;; ANSWER SECTION:
safefinder.info.        599     IN      A       199.34.228.100

;; Query time: 38 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed May 18 12:21:12 EDT 2016
;; MSG SIZE  rcvd: 60
```

I can also ping the address and get responses.

```
$ ping safefinder.info
PING safefinder.info (199.34.228.100) 56(84) bytes of data.
64 bytes from pages-custom-16.weebly.com (199.34.228.100): icmp_seq=1 ttl=57 time=76.2 ms
```

When I try a `get` to this DNS the Http client hangs, and that's all that happens.

```
   $http = new Client([
            'ssl_verify_peer' => false,
            'ssl_verify_peer_name' => false,
            'redirect' => 3
   ]);
   $http->get('http://www.safefinder.info');
```

My problem is that there is no error or response. I'm not sure what else I can do to get past this. After running the code I have to `kill` the process.

### Expected Behavior

`get` should throw an exception or return a response.

### Actual Behavior

PHP process hangs with 0% CPU usage, and no matter how long I wait the % of memory never increase. It's stuck at 0.1% (or 20908 bytes).

When I run `netstat` there remains an open socket for `pages-custom-16.weebly.com` which was shown in the `ping`.

```
$ netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 ahtag.com:57935         pages-custom-16.we:http ESTABLISHED
```

The send and receive counts are `0`.

So I don't know why `get` does not time-out?

**Comment by chinpei215** [comment]
What if you change [these lines](https://github.com/cakephp/cakephp/blob/339bbe7cccbd57c992b3afd5c2f0167c4facb12d/src/Network/Http/Adapter/Stream.php#L262-L265) to the following?

```php
// $content = '';
// while (!feof($this->_stream)) {
//     $content .= fread($this->_stream, 8192);
// }

// Use stream_get_contents instead
$content = stream_get_contents($this->_stream);
```

**Comment by thinkingmedia** [comment]
@chinpei215 It looks like `Stream.php` never calls `stream_set_timeout`

http://php.net/manual/en/function.stream-set-timeout.php

Also, that method will not produce an error. It just sets a flag in the stream that it timed out. If Cake is using sockets the above won't work either. You can have to use `socket_set_option`

```
socket_set_option($socket, SOL_SOCKET, SO_RCVTIMEO, array('sec'=>$sec, 'usec'=>$usec));
socket_set_option($socket, SOL_SOCKET, SO_SNDTIMEO, array('sec'=>$sec, 'usec'=>$usec));
```

**Comment by chinpei215** [comment]
> It looks like Stream.php never calls stream_set_timeout

The `timeout` option will be passed to `stream_context_create()` [here](https://github.com/cakephp/cakephp/blob/339bbe7cccbd57c992b3afd5c2f0167c4facb12d/src/Network/Http/Adapter/Stream.php#L131). Wouldn't it the same as passing the value to `stream_set_timeout()`?

I was guessing that [a limitation of feof()](http://jp2.php.net/manual/en/function.feof.php#refsect1-function.feof-notes) was related with this issue. But `stream_get_contents()` also seems to hang as long as the server continues to respond, even after it passed the time being specified with the `timeout` option. I don't know the way to limit the total execution time for `stream_get_contents()`.

To be honest, I prefer `cURL`. It works as I expected. Adding the `cURL` adapter may be a good idea.

> If Cake is using sockets the above won't work either. You can have to use socket_set_option

Sorry if I misunderstand what you say, but I think Cake is not using sockets. Or are you suggesting to use `socket_create()` instead of `fopen()`?

**Comment by thinkingmedia** [comment]
@chinpei215 okay, thanks for the reply. I could try setting a timeout in the options.

I'm using cURL elsewhere with without any issues, but I'm going to be switching to C# for this "specific" part of my web app. I just thought I would give Cake's HTTP a try since I was coding shell tasks at the time.

**Comment by chinpei215** [comment]
Are you trying to execute C# from Cake for the workaround? Wouldn't cURL work for you?
```php
$ch = curl_init($url);
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_MAXREDIRS => 3,
    CURLOPT_TIMEOUT => 10,
]);
$body = curl_exec($ch);
curl_close($ch);
```

**Comment by markstory** [comment]
Implementing a cURL adapter shouldn't be too hard. I can take a look at that once I'm finished the bulk of the PSR7 work.

Given that this is an issue with a specific website that seems to not close its connections, I'm going to move to enhancement.

**Comment by thinkingmedia** [comment]
@chinpei215 thank you for the code snippet. I'm going to give that a try, and no I wouldn't use C# inside PHP. I was going to write Mono CLI tool in C#, but I've done most of this app in Cake with PHP. Having two languages on the back-end can be hard to maintain later.

@markstory If you could add a cURL wrapper that would be awesome. I wouldn't worry about it for now, but I think it would be more reliable than the current way it's done.

**Comment by chinpei215** [comment]
@thinkingmedia thank you for the clarification :)

@markstory thanks! I am looking forward to it.

**Comment by chinpei215** [comment]
@markstory May I fix `Cake\Network\Http\Adapter\Stream.php`? Aside from cURL, I have an idea to solve this issue.

**Comment by markstory** [comment]
@chinpei215 Of course, I've not had a chance to look at this.

**Comment by lorenzo** [comment]
Closing as the related pull request was merged. Please confirm if the patch actually solved your issue
