### ISSUE TITLE
CakePHP 2.8.4 Fix in ORM (MSSQL 2008 Express) to "field" AND "findByxxx" AND "count"

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#8849]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4
* Platform and Target: Windows 2008 R2 64Bit, PHP 5.3.9 x86 MSVC9 (Visual C++ 2008), MSSQL 2008 Express, pdo_sqlsrv.dll V2.0

### What you did
**Function in Controller:**
```
protected function _getExisteCodVendedor($usuario_vendedor_cod_tango = null) {
        // Si es NULL
        if ( is_string($usuario_vendedor_cod_tango) == true ) {

            // Hay un resultado solo ..?
            $COD_VENDEDOR = $this->CTA_VENDEDOR->field('COD_VENDEDOR', array( 'CTA_VENDEDOR.COD_VENDEDOR' => trim($usuario_vendedor_cod_tango) ));
            $COD_VENDEDOR2 = $this->CTA_VENDEDOR->findByCodVendedor(trim($usuario_vendedor_cod_tango));
            $COD_VENDEDOR3 = $this->CTA_VENDEDOR->find('count', array('conditions'=> array( 'COD_VENDEDOR' => trim($usuario_vendedor_cod_tango)) ));

            debug($this->CTA_VENDEDOR->getDataSource()->getLog(false, false));

            debug($usuario_vendedor_cod_tango); // OK is 'LS'     (line 690)
            debug($COD_VENDEDOR); // FIX 0 row                        (line 691)
            debug($COD_VENDEDOR2); // FIX 0 row                      (line 692)
            exit(debug($COD_VENDEDOR3)); // FIX 0 row               (line 693)

            // Hay resultados..?
            if ( strlen(trim($COD_VENDEDOR)) >= 1 ) {
                return trim($COD_VENDEDOR);
            }
        }
        return false;
    }
```

**Model is easy:**
```
class CTA_VENDEDOR extends AppModel {
    public $useTable = 'CTA_VENDEDOR';
    public $primaryKey = 'ID_CTA_VENDEDOR';
}
```

**Show Data in MSSQL 2008 Express:**
Print: http://s19.postimg.org/brx6vi49v/Print_De_Pantalla_520.jpg

**SQL Scheme Table:**
```
CREATE TABLE [dbo].[CTA_VENDEDOR](
	[ID_CTA_VENDEDOR] [dbo].[D_ID] NOT NULL,
	[FILLER] [varchar](20) NULL,
	[COD_VENDEDOR] [varchar](10) NOT NULL,
	[DESC_VENDEDOR] [varchar](30) NULL,
 CONSTRAINT [PK_CTA_VENDEDOR] PRIMARY KEY CLUSTERED 
(
	[ID_CTA_VENDEDOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

```

**Show Test Query Generator for CakePHP is OK in DB.**
Test OK get data for "SQLServer Management Studio"

**Test SQL 6:** http://s19.postimg.org/4frqpym1v/Print_De_Pantalla_523.jpg
**Test SQL 7:** http://s19.postimg.org/4ehswjk83/Print_De_Pantalla_522.jpg
**Test SQL 8:** http://s19.postimg.org/yhwbohnhf/Print_De_Pantalla_521.jpg

**SQL Generator for CakePHP:**
```
        (int) 6 => array( //Test Sql 6
			'query' => 'SELECT  TOP 1 [CTA_VENDEDOR].[COD_VENDEDOR] AS [CTA_VENDEDOR__COD_VENDEDOR] FROM [CTA_VENDEDOR] AS [CTA_VENDEDOR]   WHERE [CTA_VENDEDOR].[COD_VENDEDOR] = N'LS'  ORDER BY (SELECT NULL)',
			'params' => array(),
			'affected' => (int) 0,
			'numRows' => (int) 0,
			'took' => (float) 1
		),
		(int) 7 => array(  //Test Sql 7
			'query' => 'SELECT  TOP 1 [CTA_VENDEDOR].[ID_CTA_VENDEDOR] AS [CTA_VENDEDOR__ID_CTA_VENDEDOR], [CTA_VENDEDOR].[FILLER] AS [CTA_VENDEDOR__FILLER], [CTA_VENDEDOR].[COD_VENDEDOR] AS [CTA_VENDEDOR__COD_VENDEDOR], [CTA_VENDEDOR].[DESC_VENDEDOR] AS [CTA_VENDEDOR__DESC_VENDEDOR] FROM [CTA_VENDEDOR] AS [CTA_VENDEDOR]   WHERE [CTA_VENDEDOR].[cod_vendedor] = N'LS'  ORDER BY (SELECT NULL)',
			'params' => array(),
			'affected' => (int) 0,
			'numRows' => (int) 0,
			'took' => (float) 15
		),
		(int) 8 => array(  //Test Sql 8
			'query' => 'SELECT  COUNT(*) AS [count] FROM [CTA_VENDEDOR] AS [CTA_VENDEDOR]   WHERE [COD_VENDEDOR] = N'LS'',
			'params' => array(),
			'affected' => (int) 1,
			'numRows' => (int) 1,
			'took' => (float) 20
		)
```
### Expected Behavior

>$COD_VENDEDOR == 'LS'
> $COD_VENDEDOR2 == All data in Array()
> $COD_VENDEDOR3 == 1

### Actual Behavior
**Out DEBUG:**

```
\app\Controller\ImportarController.php (line 690)
'LS'

\app\Controller\ImportarController.php (line 691)
false

\app\Controller\ImportarController.php (line 692)
array()

\app\Controller\ImportarController.php (line 693)
(int) 0
```

**Comment by EOM** [comment]
**New Test for:**

CakePHP Version: 2.8.4
Platform and Target: Windows 2008 R2 64Bit, **PHP 5.6.21 x86 MSVC11 (Visual C++ 2012)**, MSSQL 2008 Express, **pdo_sqlsrv.dll V3.2**

**Equal Error ;-(**

**Comment by markstory** [comment]
I'm a bit unclear. Do the generated queries run fine in SQLServer Management Studio but fail when CakePHP runs them?

**Comment by EOM** [comment]
_Sorry, my English is not good._

I run the SQL generated by CakePHP in **"SQLServer Management Studio" and it works perfect, retrieves data from the DB.**

So I rule out that the generated SQL are wrong, the problem has to be when you retrieve that information.

But the problem seems this when the **ORM, CakePHP or PDO** has to retrieve the information. Does not deliver any results. therefore gives **False, empty Array, the counter gives "0"** results.

Look at the Debug OUT.

**Comment by EOM** [comment]
The scheme with the DB of my client, could affect the behavior of ORM for failure and does not recover information.?

**Information scheme**, MSSQL 2008:

**DB:** "MDM-QA" or "Manjares_del_Mar_SRL-QA"
**Table:** CTA_VENDEDOR
**Field:** COD_VENDEDOR

**Comment by markstory** [comment]
> Sorry, my English is not good.

That's ok. Thank you for clarifying what's not working for you. I don't have a windows VM setup right now, but hope to remedy that in the upcoming days so I can look at this and another SQLServer related method.

**Comment by EOM** [comment]
**Markstory**, perhaps helps you **download a VM Free for 90 days, from here, 100% legal and created by Microsoft**, sure you will win long;-)

**Link:** [https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/)

**Comment by ravage84** [comment]
@EOM could you please provide a reproducable example. If you provide me a schema.php and some small amount of code, I can try tro reproduce that on my Windows machine.
I have SQL Server 2008 R2 installed.

**Comment by EOM** [comment]
Hi @ravage84 link code:
https://bitbucket.org/snippets/eom/L674g

Strengthen me if you need anything useful or more.

**Comment by EOM** [comment]
Hi @markstory @ravage84  can close the issus, it was my mistake, detect where the problem was.
Sorry for the inconvenience and thank you very much for the same response.

Print OUT DEBUG: http://s19.postimg.org/ewm3gw65f/Print_De_Pantalla_536.jpg
