### ISSUE TITLE
AuthComponent _unauthenticated with ajaxLogin

### ISSUE THREAD

**Issue by littleylv** [cakephp/cakephp#8854]
CakePHP Version: 3.2.8

In my Auth config I set 'ajaxLogin' => 'some_element'.
I would like it return html only in the 'some_element' codes with 'ajax' layout, but it comes with other codes in my 'default' layout .

In AuthComponent.php function _unauthenticated : 
```php
    if (!empty($this->_config['ajaxLogin'])) {
              $controller->viewBuilder()->templatePath('Element');
              $response = $controller->render(
                  $this->_config['ajaxLogin'],
                  $this->RequestHandler->ajaxLayout
              );
              $response->statusCode(403);
              return $response;
      }
```

`$this->RequestHandler->ajaxLayout` is null (may be excepted 'ajax' but not defined in RequestHandlerComponent.php), so the layout is 'default'.

Is this a bug or where am I wrong?

Thank you~

**Comment by markstory** [comment]
Normally the `AjaxView` in your application would be end up being used, as RequestHandler will automatically set `RequestHandler->ext` to `ajax`. Are you customizing the ViewClass at all? This will disable the automatic behavior in RequestHandler.

**Comment by littleylv** [comment]
@markstory  Thank you!
As you said, I figure out that I have `$this->viewBuilder()->layout('admin');` in `beforeFilter`.
In my `AdminController` I want all the actions use 'admin' layout (some 'ajax') so I add  `$this->viewBuilder()->layout('admin');` in `beforeFilter`.

Where or which function should I properly put `$this->viewBuilder()->layout('admin');` please~

Or could you find some better ways to deal with `$this->RequestHandler->ajaxLayout` :)

**Comment by ADmad** [comment]
You can just set `$this->layout` in your ajax login element.

**Comment by littleylv** [comment]
Thanks. It works.
