### ISSUE TITLE
Unable to use PostgreSQL JSON expression in virtual field

### ISSUE THREAD

**Issue by erjiang** [cakephp/cakephp#8856]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.2
* Platform and Target: PostgreSQL

### What you did

Creating a virtual field for a PostgreSQL JSON column field gets botched by the CakePHP SQL engine.

Example:

`public $virtualFields = array('color' => 'Thing."misc_fields"->>\'color\'');`

### Expected Behavior

CakePHP should generate something like the following SQL:

`("Thing"."misc_fields"->>'color') AS "Thing__color"`

### Actual Behavior

CakePHP, when re-quoting the fields, includes the hyphen in the column name and generates:

`("Thing"."misc_fields-">>'color') AS "Thing__color"`

which of course doesn't work because "misc_fields-" is not a column that exists.

### Proposed fix

Our patch that seems to fix this one issue is here: https://github.com/doublemap/cakephp/tree/exclude-column-trailing-hyphen

But it seems like there could be a more general fix, such as not re-quoting already quoted column names or disallowing hyphens in columns (since neither mysql nor pgsql allow hyphens in bare column names).

**Comment by markstory** [comment]
> But it seems like there could be a more general fix, such as not re-quoting already quoted column names or disallowing hyphens in columns (since neither mysql nor pgsql allow hyphens in bare column names).

I don't think this is an option. MySQL will accept `-` in column names as long as you quote them.

```sql
create table test (`test-column` varchar(255) );
```

In either case your fix looks reasonable. Would you be willing to open a pull request for it?

**Comment by erjiang** [comment]
> I don't think this is an option. MySQL will accept - in column names as long as you quote them.

Yes, postgres and mysql will both accept almost any character for a column name if you quote it, but I think the whole regex method falls apart at that point.

Will open a PR shortly, thanks.

**Comment by markstory** [comment]
Closing as there is a pull request open.
