### ISSUE TITLE
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: id

### ISSUE THREAD

**Issue by elboletaire** [cakephp/cakephp#8857]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Platform and Target: Linux (but probably all of them)

### What you did

Created a fixture for a table that has an id with `BIGINT` instead of `INT`; using SQLite for tests.

### Expected Behavior

Properly run the tests.

### Actual Behavior

Using `BIGINT` (in the fixture, that's `'type' => 'biginteger`') with `'null' => false` on the ID crashes with an `Integrity constraint violation`:

    1) Stats\Test\TestCase\Model\Table\StatsTableTest::testIncrease
    PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: stats.id

Changing the `type` to just `integer` or setting `null` to `true` does the trick (obviously I can't change either of them).

**Comment by markstory** [comment]
How can someone reproduce this issue? Could you paste the fixture that is giving you trouble?

**Comment by ADmad** [comment]
Are you using a 32bit or 64bit OS?

**Comment by elboletaire** [comment]
Sorry for the delay, here was very late when I saw your comments.

Answering @ADmad, I'm using a x64 Ubuntu (16.04), but how could that affect?

I've created an entire app to reproduce this and I've ensured that this only occurs with sqlite (well, I've not tested postgreesql, but with MySQL works as expected).

[sqlite-issue.zip](https://github.com/cakephp/cakephp/files/274331/sqlite-issue.zip)

The zip file only has the required files to reproduce the issue:

- config/app.default.php (configured test db to work with sqlite using `:memory:` as db)
- src/Model/Entity/Stat.php
- src/Model/Table/StatsTable.php
- tests/TestCase/Model/Table/StatsTableTest.php

phpunit output:

    ~/fixture-sqlite-issue ❯❯❯ phpunit
    PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

    ...IIIIIIE                                                        10 / 10 (100%)

    Time: 97 ms, Memory: 12.00MB

    There was 1 error:

    1) App\Test\TestCase\Model\Table\StatsTableTest::testValidationDefault
    PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: stats.id

    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php:171
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php:171
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Statement/BufferedStatement.php:74
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Statement/SqliteStatement.php:41
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Connection.php:272
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Query.php:188
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/ORM/Table.php:1545
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/ORM/Table.php:1461
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/ORM/Table.php:1392
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/Database/Connection.php:559
    /home/elboletaire/fixture-sqlite-issue/vendor/cakephp/cakephp/src/ORM/Table.php:1393
    /home/elboletaire/fixture-sqlite-issue/tests/TestCase/Model/Table/StatsTableTest.php:77

    FAILURES!
    Tests: 10, Assertions: 18, Errors: 1, Incomplete: 6.

**Comment by elboletaire** [comment]
Oh God! I forgot the fixture! xD

Here's the updated file: [sqlite-issue.zip](https://github.com/cakephp/cakephp/files/274351/sqlite-issue.zip)

I've also updated the previous post, but if you received the notification by e-mail ensure to open this instead of the previous one.

**Comment by ADmad** [comment]
> I'm using a x64 Ubuntu (16.04), but how could that affect?

A 64bit wouldn't, a 32bit might, but that's not your case :)

**Comment by lorenzo** [comment]
Sqlite does not allow BIGINT + autoincrement, is it that what your are doing?

**Comment by elboletaire** [comment]
> Sqlite does not allow BIGINT + autoincrement, is it that what your are doing?

Yes.. :cry: 

So.. I should change to test using MySQL or simply change the fixture to use `integer` instead of `biginteger`.

Thanks @lorenzo, and apologies to all for any inconvenience, I was unaware of this sqlite limitation.

**Comment by lorenzo** [comment]
You can make the fixture use integer. In reality sqlite will use a bigint if your platform is 64 bits

**Comment by elboletaire** [comment]
In fact in my tests there's no need for a big int, as probably never will insert such number of rows in my fixtures.
