### ISSUE TITLE
CLI Options added in subcommand does not work.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8858]
This is a (multiple allowed):
* [x] bug

I want to run a subcommand of Elasticsearch (my) console with custom, task specific option.
How i want to do it:
In shell:
` $parser->addSubcommand("create_index", ["help" => "Creates related indexes if not exist"]);`

Task:
```
class CreateIndexTask extends Shell
{
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();
        $parser->addArgument("fooArg", [
            "required" => true]);
        $parser->addOption('connection', [
            'short' => 'c',
            'required'=>true,
            'help' => 'connection',
            'default' => 'default',
        ]);
        return $parser;
    }
}
```

How I try to call it:
`
cake elasticsearch create_index --connection=foobar`

What I get:
```

Error: Unknown option `connection`
Usage:
cake elasticsearch [subcommand] [-h] [-q] [-v]

Subcommands:

create_index  Creates related indexes if not exist
drop_index    Drops related indexes

To see help on a subcommand use `cake elasticsearch [subcommand] --help`

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.

```

Crucial line is here: 
`Error: Unknown option `connection``

If i remove `--connection=foobar` parser, as expected, will raise exception about missing `foo` argument. 
```

Error: Missing required arguments. fooArg is required.
Usage:
cake create_index [-c default] [-h] [-q] [-v] <fooArg>

Options:

--connection, -c  connection (default: default)
--help, -h        Display this help.
--quiet, -q       Enable quiet output.
--verbose, -v     Enable verbose output.

Arguments:

fooArg

```

Note that option is listed here.

All in all, looks like adding arguments from subcommand works, but adding options does not.

**Comment by markstory** [comment]
> All in all, looks like adding arguments from subcommand works, but adding options does not.

I have to disagree with that. Bake uses subcommand extensively and arguments work fine there.

Is there a reason you're not linking the option parsers together? The

```php
$parser->addSubcommand("create_index", ["help" => "Creates related indexes if not exist"]);
```

Should be

```php
$parser->addSubcommand("create_index", [
  "help" => "Creates related indexes if not exist",
  'parser' => $this->CreateIndex->getOptionParser()
]);
```

This isn't entirely clear from the documentation, so I'll get that updated.

**Comment by markstory** [comment]
Docs are updated now.

**Comment by Antoniossss** [comment]
@markstory 
> Is there a reason you're not linking the option parsers together?
No, no reason, just didnt know it has to be done that way - my approach was only intuitive for me;)

Thanks for the help.
