### ISSUE TITLE
leftJoinWith with belongsTo generates an incorrect query

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#8859]
This is a _bug_.

* CakePHP Version: 3.2.9
* Platform and Target: Database: MySQL 5.7.12-0ubuntu1 .

I have a `Group` which `belongsTo` `Users` (the members). I want to have a list of all groups with the member count of each group. I tried the following code, [as per docs](http://book.cakephp.org/3.0/en/orm/query-builder.html#using-leftjoinwith):
```php
$query = $this->Groups->find();
$query
     ->where(['project_id' => $projectId])
     ->select(['id', 'name',
            'user_count' => $query->func()->count('Users.id')
        ])
     ->leftJoinWith('Users')
     ->group('Groups.id');
```

This generates the following SQL:
```sql
SELECT 
  Groups.id AS `Groups__id`, 
  Groups.name AS `Groups__name`, 
  (
    COUNT(Users.id)
  ) AS `user_count` 
FROM 
  groups Groups 
  LEFT JOIN users Users ON 1 = 1 
  LEFT JOIN groups_users GroupsUsers ON (
    Groups.id = (GroupsUsers.group_id) 
    AND Users.id = (GroupsUsers.user_id)
  ) 
WHERE 
  project_id = 7 
GROUP BY 
  Groups.id 
```

The SQL is incorrect. The `1 = 1` clause causes every user to be joined with every group, so that `user_count` is the same for every group (the total count of users).

I'm not totally sure, whenever this is a bug, or if this scenario is not supported (the doc uses a `has` realationship), but it's either a bug in the ORM or the docs are unclear.

**Comment by ADmad** [comment]
Does adding `->autoFields(true)` change the generated query?

**Comment by nrother** [comment]
No :(

Von meinem iPad gesendet

**Comment by Antoniossss** [comment]
@nrother Can you please run `EXPLAIN` and show us the output? IMHO there should not be extra product joins due to SQL query optimizer.

**Comment by markstory** [comment]
What does the association definition for Groups -> Users look like? `leftJoinWith()` generally uses the association forieign keys.

**Comment by markstory** [comment]
Also from the query it looks like the above is running in the context of the Users table which means the association conditions are already applied by the association proxy finder. I'm not sure why another leftJoinWith is necessary.

**Comment by lorenzo** [comment]
The generated joins look correct, but it seems like you need to change the `count()` call slightly:

```php
'user_count' => $query->func()->count('GroupsUsers.user_id')
```

That would be the right code of a belongsToMany association. The count always needs to be done in the hasMany assoc. Which means that the leftJoin to users is not necessary, doing `leftJoinWith('GrouspUsers')` would be good enough, you just need to set the association yourself.

**Comment by nrother** [comment]
Ok, my original problem was fixed by using `GroupsUsers.user_id` in the count. But I still think there is something wrong: Suppose I want the sum of the postal codes from all users for every group (stupid example, I know...).

Code:
```php
$query = $this->Groups->find();
$query
    ->where(['project_id' => $projectId])
    ->select(['id', 'name',
        	'dummy' => $query->func()->sum('Users.postal_code')
    	])
    ->leftJoinWith('Users')
    ->group('Groups.id');
```
Generated query:
```sql
SELECT 
  Groups.id AS `Groups__id`, 
  Groups.name AS `Groups__name`, 
  (
    SUM(Users.postal_code)
  ) AS `dummy` 
FROM 
  groups Groups 
  LEFT JOIN users Users ON 1 = 1 
  LEFT JOIN groups_users GroupsUsers ON (
    Groups.id = (GroupsUsers.group_id) 
    AND Users.id = (GroupsUsers.user_id)
  ) 
WHERE 
  project_id = 7 
GROUP BY 
  Groups.id 
```
The result shows the same problem as above: All groups have the sum of _all_ users postal codes in their `dummy` field.

Association definition in Groups:
```php
$this->belongsToMany('Users', [
    'foreignKey' => 'group_id',
    'targetForeignKey' => 'user_id',
    'joinTable' => 'groups_users'
]);
```
Association definition in Users:
```php
this->belongsToMany('Groups', [
    'foreignKey' => 'user_id',
    'targetForeignKey' => 'group_id',
    'joinTable' => 'groups_users'
]);
```
EXPLAIN:
![bildschirmfoto 2016-05-21 um 11 32 07](https://cloud.githubusercontent.com/assets/6770775/15447583/b348126c-1f47-11e6-9cc5-6890f83aab8f.png)

I think something is wrong here:
```sql
LEFT JOIN users Users ON 1 = 1 
LEFT JOIN groups_users GroupsUsers ON (
	Groups.id = (GroupsUsers.group_id) 
    AND Users.id = (GroupsUsers.user_id)
) 
```
It works correctly this way:
```sql
LEFT JOIN groups_users GroupsUsers ON (
	Groups.id = (GroupsUsers.group_id)
)
LEFT JOIN users Users ON (Users.id = GroupsUsers.user_id)
```

**Comment by lorenzo** [comment]
There was already a ticket about this, and I actually locally implemented your suggestion, only to realize that it broke several other use cases where it was important not to filter on one of the associations immediately.

I will, though, revisit my code and see if those cases can somehow be rewritten in another way. The problem here is that there are multiple valid interpretations of what a left join to a belongsToMany should be
