### ISSUE TITLE
App Cell cannot render view located in plugin

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#8860]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Platform and Target: Apache webserver; No database

### What you did
I have a Cell in my App, named `src/View/Cell/CountCell.php`:
```
    public function display()
    {
        $this->template = 'Plugin2.TestPlugin1/test_plugin_1';

        // OR:

        $this->plugin = 'Plugin2';
        $this->template = 'TestPlugin1/test_plugin_1';
    }
```

I have the following cell view named `plugins/Plugin2/src/Template/Cell/TestPlugin1/test_plugin_1.ctp`

> To be sure my plugin was loaded correctly I created a component, loaded it in the `AppComponent` and It worked; so I can approve that the plugin is loaded correctly.

### Expected Behavior
I expect that the cell view `plugins/Plugin2/src/Template/Cell/TestPlugin1/test_plugin_1.ctp` should be loaded.

### Actual Behavior
I get the following error on my page:

> Warning (512): Could not render cell - Cell view file "TestPlugin1/test_plugin_1" is missing. [CORE\src\View\Cell.php, line 268]

**Comment by markstory** [comment]
I'll take a look. As Cells in plugins can render their templates just fine.

**Comment by markstory** [comment]
Because your Cell is named `CountCell`, CakePHP will look for `plugins/Plugin2/src/Template/Cell/Count/TestPlugin1/test_plugin_1.ctp` by convention. If you want to render the template you've outlined, you'll need to do the following:

```php
        $this->plugin = 'Plugin2';
        $this->template = '/Cell/TestPlugin1/test_plugin';
```

**Comment by bobmulder** [comment]
Thanks @markstory!
