### ISSUE TITLE
Cake's handling of unique NULL values is no longer compatible with SQL's

### ISSUE THREAD

**Issue by davehensley** [cakephp/cakephp#8873]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9, specifically 02c8f32
* Platform and Target: Ubuntu 16.04, CLI, PHP 7.0.4, MySQL 5.7.12

### What you did
Let's say I have two models (Posts belongsTo Users), and let's say that I want some Posts to be unowned (meaning the posts.user_id column can be null). So my SQL to create the Posts table looks like this:

`CREATE TABLE posts (id CHAR(36) NOT NULL, user_id CHAR(36), title VARCHAR(255) NOT NULL, PRIMARY KEY(id), UNIQUE(user_id, title));`

As you can see, I have a unique index that makes sure no two posts that are owned by the same user share the same title. So in PostsTable::validationDefault() I put this:

```
$validator                                                     
  ->add('title', 'unique', ['provider' => 'table', 'rule' => ['validateUnique', ['scope' => ['user_id']]]])
  ->notEmpty('title')                                                                                   
  ->requirePresence('title', 'create');
```

### Expected Behavior
Two unowned Posts can have the same title. The unique index on my SQL table allows this. This worked up through 3.2.8.

### Actual Behavior
In 3.2.9, the validation fails when two unowned Posts share the same title. Reverting 02c8f32 restores the old behavior. I guess this was the intention of the commit, but it breaks backward compatibility, and it will confuse people who expect Cake to handle the uniqueness of null values the same way that the underlying SQL indexes do (as was the case prior to 3.2.9).

Perhaps it would be better to add an option to activate the new behavior if desired, but still default to the old (at least until version 3.3)? I'm sure lots of other people's apps also rely on the old, SQL-style  behavior, and I think it would be preferable to not have to switch to custom providers and manually write new validation methods just to get them working again with 3.2.9+.

**Comment by jhli** [comment]
This has already been rolled back - however for Unique and ExistsIn we need to have more flexibility through options/flags, INHO.

**Comment by davehensley** [comment]
Hmm can you please provide a link to the commit for the rollback? I'm testing against the master branch and it's still failing for me.

**Comment by ionas** [comment]
Sorry mixed it up with this one https://github.com/cakephp/cakephp/pull/8862

**Comment by ionas** [comment]
Here is the relevant PR instead: https://github.com/cakephp/cakephp/pull/8807

**Comment by davehensley** [comment]
Yeah, that's the PR for the commit that I referred to in the issue description. As far as I can tell, it has not been rolled back.

**Comment by lorenzo** [comment]
This was reverted, it should be in the next release really soon, sorry for the inconvenience

**Comment by markstory** [comment]
#8807 was not reverted. The recent revert was #8862.

> In 3.2.9, the validation fails when two unowned Posts share the same title. 

The old code was working by 'accident' as the generated queries were `column = NULL` which is always false. This is why I felt making the code functional was better that omitting null values (which is effectively what this issue is requesting).

While I can see the point that SQL unique keys treat `NULL` values as not equal. This behavior is rooted in `NULL != NULL` in SQL. I'm not sure that is a logical position to take for PHP code. Where `null == null`.

@jhli I'd rather not add more, options, and instead add more rules that capture the most common use-cases. Having options makes individual rule classes more complex.

**Comment by ionas** [comment]
I am fine with more rule names too instead of options. I am just saying that for ExistsIn and IsUnique alike there should be ways to treat double NULLs as unique/non-unique, existing/non-existing, especially in multi column constraints.

**Comment by markstory** [comment]
@ionas I took another look at  #8749, and I'm left wondering if we need more classes or options. Couldn't we use the database schema to decide what the valid states are? In the case where fields are nullable, then most of the current behavior is correct. The not-null case isn't handled as well currently though. Without putting a ton of thought into it, I think that we could update `ExistsIn` and `IsUnique` to build logic around whether or not a column has `NOT NULL` and be able to handle all the routine scenarios. There would still exist scenarios where what the schema defines and what the developer wants differ, but I feel like those use cases could be handled in the applications that need that flexibility.

**Comment by markstory** [comment]
Pull request up now to revert the problematic change.
