### ISSUE TITLE
Custom finder not working with HABTM association?

### ISSUE THREAD

**Issue by ah8r** [cakephp/cakephp#8876]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Platform and Target: Nginx / MySQL

### What you did
I have three classes, Jobs, Users, and UserTypes.
Users hasMany UserTypes, and UserTypes hasMany Users (think of UserTypes more like groups).
Jobs belongsTo Users

What I want to do is set up the Jobs belongsTo Users relationship so that a Job can only belong to a User with a certain UserType ("Account Managers"). From reading the documentation I thought I could do this with a custom finder, but it doesn't seem to work:

In JobsTable.php (note the relationship is called AccountManagers but it uses the Users table for the join):
```php
$this->belongsTo('AccountManagers', [
    'className' => 'Users',
    'foreignKey' => 'account_manager_id',
    'joinType' => 'LEFT',
    'finder' => 'accountManagers'
]);
```

In UsersTable.php:
```php
public function findAccountManagers(Query $query, array $options)
{
    return $query->innerJoinWith('UserTypes', function ($q) {
        return $q->where([
            'UserTypes.name' => 'Account Manager'
        ]);
    })
}
```

In the JobsController.php file, in the add() method, the following is used to fetch the AccountManagers for the view:

```php
$accountManagers = $this->Jobs->AccountManagers->find('list', ['limit' => 200]);
```

### Expected Behavior
When I go to /jobs/add I expect the drop down to be populated with only Users who have a UserType "Account Manager".

### Actual Behavior
The drop down contains a full list of users, regardless of their UserTypes.

**Comment by markstory** [comment]
Because you're finding with a specific type ('list'). The associations default finder type is not applied. The relevant code is [here](https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/BelongsToMany.php#L883-L885). To do what you want you should do the following:

```php
$accountManagers = $this->Jobs->AccountManagers->find()->find('list', ['limit' => 200]);
```

**Comment by ah8r** [comment]
Thanks, that fix worked. However now I'm getting a separate error when using the Paginator.

In JobsController.php index function:

```php
public function index()
    {
        $this->paginate = [
            'contain' => ['AccountManagers']
        ];
        $jobs = $this->paginate($this->Jobs->find());

        $this->set(compact('jobs'));
        $this->set('_serialize', ['jobs']);
    }
```

When I visit /jobs I get the following error:

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UserTypes.name' in 'on clause'

**Comment by markstory** [comment]
@ah8r You'll have to sort out the missing associations/joins. That isn't a bug with CakePHP :smile:

**Comment by ah8r** [comment]
That's the thing, most of this code is generated via cake bake, and as far as I can tell the associations exist. The error message isn't the standard one about missing associations, rather it's a generic "Database Error".

If I change the paginate query to one which should fetch the same data, the data loads perfectly well:

```php
$jobs = $this->Jobs->find()->contain(['AccountManagers']);
```

I'm not sure why Paginator is trying to associate with UserTypes to begin with when it's not part of the query. I'm guessing it's to do with the finder method I defined before, but since that works for loading AccountManagers directly I'm not sure why it's breaking down here.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by ah8r** [comment]
Thanks for the links, sorry for mis-using the ticket tracker.
