### ISSUE TITLE
HtmlHelper should handle embedded Images in CakePHP Email

### ISSUE THREAD

**Issue by Bird87ZA** [cakephp/cakephp#8877]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: CentOS, MySQL, Email

### What you did
I tried embedding an image into an email while using the Mail Aware trait. This is the function I used to send the email:

    public function forgotPassword($user,$password)
    {
        $this
            ->from(['no-reply@deltabec.com' => 'DeltaBEC Intraweb'])
            ->emailFormat('html')
            ->to([$user->email => $user->name . ' ' . $user->surname])
            ->subject('New Intraweb Password')
            ->template('Users' . DS . 'forgot_password', 'default')
            ->attachments([[
                'file' => WWW_ROOT . 'img' . DS . 'logo-light.png',
                'mimetype' => 'image/png',
                'contentId' => 'company_logo'
            ]])
            ->viewVars(compact('user','password'));
    }

In my email, I had the following line to add that image to the email:

    <?= $this->Html->image('cid:company_logo'); ?>

### Expected Behavior
Expected behaviour would be that it embeds the image in the email.

### Actual Behavior
It simply added a image holder and attached the image to the email.

[![enter image description here][1]][1]

Upon further inspection, it parsed (?) the line, and added it like so to the email:

    <img id="_x0000_i1025" src="/cakeapp/img/cid%3Acompany_logo">

I asked a question here regarding this issue. Hardcoding the image into the email as `<img src="cid:company_logo">` solves the issue.

I've added it as both a bug and a feature discussion as it's not working as you'd expect, but then again, I'm not sure if it would add a lot of value to Cake.

  [1]: http://i.stack.imgur.com/v179L.jpg

**Comment by markstory** [comment]
Right now you'd have to make image links to contentid references by hand. It should be possible to have `UrlHelper` understand `cid:*` and treat those differently though.

**Comment by burzum** [comment]
@markstory can't we add a check for if the image starts with `cid:` and if yes simple use the string as it is? Another solution might be to add a `cidImage()` method to the helper?

**Comment by markstory** [comment]
@burzum I think checking the prefix would work quite well.

**Comment by markstory** [comment]
Pull request up now.
