### ISSUE TITLE
Can we use filed name inf Form ?

### ISSUE THREAD

**Issue by ravigupta112** [cakephp/cakephp#8881]
Can we use different field name than the database column name in cakephp2?

For example:
The database has  user_name, email, pass, etc.
now I want to use this in Form with the name like 
user_name as name ,
email as email
pass as password

Can anyone help me for this, It is Cakephp 2

**Comment by AD7six** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
