### ISSUE TITLE
RFC: Middleware Interface

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#8883]
Just came across this [new blog post by ircmaxell](http://blog.ircmaxell.com/2016/05/all-about-middleware.html) about the [recently proposed PHP-FIG Middleware interface](https://github.com/php-fig/fig-standards/pull/755).

He mainly criticises the use of the ``$repsonse`` as included Middleware interface parameter.

Personally, I have no strong opinion about that, but wanted to have a discussion about our Middleware implementation as long as it is not stable yet.

Probably relevant CakePHP interfaces:
https://github.com/cakephp/cakephp/commit/91234f42b03054136d05dee14fa2427fb7cd4b34#diff-6371be2dd9e52fde8f9442bf3652c456R76
https://github.com/cakephp/cakephp/commit/91234f42b03054136d05dee14fa2427fb7cd4b34#diff-3c0078b14477bb74d0a45a7691791fc0R70
https://github.com/cakephp/cakephp/commit/b89a84565a92fd67ea11406581ea2d8439d6e16b#diff-3786397ed795411940a2f208f015eb17R46

**Comment by markstory** [comment]
I'll take a look at the blog post. Given that that the interface hasn't been accepted yet, and those things generally take a while. Implementing this interface might have to be done post 3.3.0.

**Comment by ravage84** [comment]
@markstory  my intention for this GH issue was less the proposed but not yet accepted interface, but more about ircmaxell's issues with it.
Your implementation is very similar to that proposed interface, so I was interested in your and others point of view on ircmaxell's issues.
But as I understood through your comments during your [Future of HTTP in CakePHP](http://de.slideshare.net/markstory/future-of-http-in-cakephp/) presentation, you are quite convinced of the current implementation.

Works for me, case closed.

**Comment by ravage84** [comment]
For interested parties:
Woody Gilk,  author of the [poposed interface](https://github.com/php-fig/fig-standards/pull/755) (presumably PSR-15), wrote [a response to ircmaxell's concerns](http://shadowhand.me/all-about-psr-7-middleware/).
