### ISSUE TITLE
Associated Model IDs are not recognized anymore

### ISSUE THREAD

**Issue by EuMMCR** [cakephp/cakephp#8887]
Hello,

since I updated via composer to version 3.2.9, my Application shows strange behaviour.

An example:
I have the entity "Book" with the fields "id", "name", "author_id", "author", where "author" references to the "Author" entity.
The "Author" entity, however has the fields "id" and "name".
So both entities follow the CakePHP conventions.

In earlier versions, I just made the following:
`$book = new Book();`
`$book->author = $this->Authors->get(XX);`
`$this->Books->save();`
Which worked perfectly.

Since I updated to version 3.2.9, I get the error:
> 'author_id' => This Value does not exist.

Could someon explain that to me?

Thank you
Joachim

**Comment by Tzaoh** [comment]
> I have the entity "Book" with the fields "id", "name", "author_id", "author", where "author" references to 
Should not be "author_id" the one who references Authors instead "author" ?

**Comment by TheFRedFox** [comment]
It may be that this is a result by this PR https://github.com/cakephp/cakephp/pull/8788.
It seems it will be reverted in 3.2.10 again (see PR https://github.com/cakephp/cakephp/pull/8862), after other people also had trouble with this change. (Me too btw. ^^)

`author_id` have to be set if it has an association.

**Comment by markstory** [comment]
This sounds like the issue @TheFRedFox mentioned. I'll get a 3.2.10 release packaged up this week to make the reverts more widely available.

**Comment by markstory** [comment]
3.2.10 has been released, this release contains the fixes that should resolve this issue. If not please let me know.
