### ISSUE TITLE
Adds RSA-SHA1 method for the OAuth Authentication

### ISSUE THREAD

**Issue by TheFRedFox** [cakephp/cakephp#8889]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.9

### What you did
Using the OAuth Authenticator `Cake\Network\Http\Auth\Oauth` and wanted to use the [`RSA-SHA1`](http://oauth.net/core/1.0/#anchor19) method.

### Expected Behavior
Oauth class build the signature for the authentication with `RSA-SHA1`.

### Actual Behavior
`RSA-SHA1` method is not supported yet.

I already extended the Oauth class with an own one with such a `RSA-SHA1` method. So I could easily create a pull request in the next days (would have to add tests for it). However I wanted to ask first, if it is wanted or if there is a reason why `RSA-SHA1` was not supported yet.

**Comment by thinkingmedia** [comment]
RSA-SHA1 is not secure and depreciated. I'm speaking in general terms, because I have no idea how OAuth is using SHA1.

If possible you should be using SHA256.

As an example, Google Chrome now flags public keys encrypted with SHA1 as untrusted, and red flags websites using them.

**Comment by markstory** [comment]
> if there is a reason why RSA-SHA1 was not supported yet.

I've never come across/used a site that needed SHA1 which is why it isn't already built. However, a pull request to add it would be :+1:

**Comment by TheFRedFox** [comment]
> If possible you should be using SHA256.

@thinkingmedia It is not possible, at least I don't know any possibility of that. To be honest, I also don't know for what SHA1 is really needed. The whole OAuth process was completely new for me, too. I needed it for the OAuth Authentication to Atlassian Jira.
For your interest: There are three common signature methods for OAuth:
* Plaintext
* HMAC-SHA1
* RSA-SHA1

For the whole signature process you can read [here](http://oauth.net/core/1.0/#signing_process) more. :smiley:

@markstory Alright. I will see that I create a PR in the next days. FYI I needed it for Atlassian Jira. :wink:

**Comment by thinkingmedia** [comment]
It's all part of your basic encryption security tactics. Basically, you take a secret key and some data. You generate a hash using an algorithm (i.e. RSA-SHA1). You send the data and hash to a third-party. The third-party reverses the hash and if that value matches a public key they know the data originated from someone that has the secret key. You can even include the data has part of the algorithm to show that no man-in-the-middle has altered it. This allows oauth to work over regular HTTP get requests which are very open.

That's basically how oauth grants sign in permissions to other websites (i.e. prove you have the right secret key and I'll log the user in for you).

The reason SHA1 as been depreciated is that someone figured out how to calculate the secret key after getting sample data and the public key. While it's not really practical (i.e. you need a super computer) but it is technically possible.

**Comment by TheFRedFox** [comment]
In my understanding, when I implemented the OAuth authentication, it is a bit different to your explanation.

> You generate a hash using an algorithm (i.e. RSA-SHA1). You send the data and hash to a third-party.

Being strict in terms, it is not a `hash` but a `signature`. The data is signed with the `private key` and is sent besides the original data in the request. So the `SHA1` algorithm is never used on the client side.
The server then decrypt the `signature` and validate it with the original data to prevent MITM attacks and to check if it was signed "with the correct private key".

But I just read that normally/originally/sometimes (I don't know when) the data is first hashed by `SHA1` and then signed with a private key. However this seems not to be part for the `OAuth` authentication as I never read about it while implementing it and it works without `SHA1`.

If I am wrong with that, please correct me. I wanna learn more about it. :smiley: 

Besides, I guess the issue can be closed as there is a PR now, right?
