### ISSUE TITLE
Add --version to the bin/cake console

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#8891]
This is a (multiple allowed):
* [ ] bug  
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Platform and Target: Shell console

### What you did
`$ bin/cake --version`

### Expected Behavior
`3.2.9`

### Actual Behavior
`Exception: Shell class for "--version" could not be found.`

I looked in the code and it seems easy to implement. If you guys allow me i can make a pull request.

**Comment by markstory** [comment]
If you know how/where to add in the `--version` flag, a pull request would be awesome. I think adding it in the same place as `bin/cake --help` (ShellDispatcher::_dispatch) makes sense.

**Comment by alysson-azevedo** [comment]
Isn't the CommandListShell better? Since the `--help` is parsed there.

**Comment by markstory** [comment]
@alysson-azevedo Yes, the ShellDispatcher delegates to `CommandList` for `--help` as well. I didn't read enough code 😊

**Comment by alysson-azevedo** [comment]
i'll close this since there's the pull request open.
