### ISSUE TITLE
Required transaction isolation level

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#8899]
CakePHP: 3.2.9
Database: MySQL 5.5

I was looking at the `Table::save()` code to see how it checked that the record exists and then inserting or updating. I see it uses a simple transaction, thus, I guess this code will only be safe if the isolation level is set to serializable. But I couldn't find anywhere in the internet any mention to this.

Since this is not the default setting I think it should be mentioned in the docs. Besides, changing this setting globally can have a big impact on performance, so it should be told how to change it just when it's needed.

Issue #3136 is relevant.

**Comment by markstory** [comment]
> I see it uses a simple transaction, thus, I guess this code will only be safe if the isolation level is set to serializable. But I couldn't find anywhere in the internet any mention to this.

If your application isn't doing deletes, or foreign key changes frequently, you may also be safe with `repeatable-read`.

> Since this is not the default setting I think it should be mentioned in the docs. 

I'm not sure we should get into documenting/suggesting how to configure one's database. I think at best we could suggest that people ensure they have the isolation level they are comfortable with.

**Comment by berarma** [comment]
> If your application isn't doing deletes, or foreign key changes frequently, you may also be safe with repeatable-read.

In case there were two concurrent processes doing a save with the same multi-column primary key, couldn't we end up doing two inserts if we don't set serializable? Both processes could do the check before any of the inserts were executed then try to insert. I guess the second insert would trigger an error in this case.

> I'm not sure we should get into documenting/suggesting how to configure one's database. I think at best we could suggest that people ensure they have the isolation level they are comfortable with.

I know, but I think the code is assuming the serializable isolation level is set, isn't it? We could argue that this level setting is the only one safe and should always be used but it's actually avoided where possible because of performance.

**Comment by markstory** [comment]
> In case there were two concurrent processes doing a save with the same multi-column primary key, couldn't we end up doing two inserts if we don't set serializable?

Yes, but one will be rejected by the database as the primary key constraint will be violated.

> I know, but I think the code is assuming the serializable isolation level is set, isn't it?

I don't think we've assumed that. We are assuming that people are setting up their constraints in a sane way though :smile:

**Comment by berarma** [comment]
Please, define "sane". :smile:

Do you mean using the serializable isolation level by default? Setting serializable globally might not be always sane.

Like I said, it's usually not the default because of the big performance penalty. I'm upset that I had to read the source code to know that there's a problem with transactions that has to be dealt outside of the framework. Maybe it's my fault because I couldn't guess it without reading the source code. Sorry then. :smile:

Seriously, I think it wouldn't hurt warning about this in the docs unless I'm making wrong assumptions.

**Comment by ADmad** [comment]
@berarma You can open a PR for the docs adding the info you think will help users better understand how transactions work by default, without having to read the source code :)

**Comment by berarma** [comment]
I don't think the docs should explain how transactions work by default, that was not the point. It's maybe just me that thinks there's something that needs to be pointed out in the way framework works. If so you can close the issue. Sorry for wasting your time.

**Comment by ADmad** [comment]
By "how transactions work by default" I meant how the framework does transactions.

**Comment by markstory** [comment]
I don't think you're wasting our time :smile:

> I don't think the docs should explain how transactions work by default, that was not the point. It's maybe just me that thinks there's something that needs to be pointed out in the way the framework works. 

What do you think needs to be explained better? I'm not completely clear on that. Are you looking for recommendations around what isolation level people should use, or some of the caveats around using weaker isolation modes?

**Comment by berarma** [comment]
I guess my expectations might be the problem. I didn't expect the serializable isolation level to be the commonly used setting, and so I didn't expect the framework to rely on this instead of setting the isolation level per transaction. I'm probably lacking some experience with ORMs here.

**Comment by ADmad** [comment]
So do you want to update the docs or simply continue adding comments here? :)
