### ISSUE TITLE
Tree Behavior error on initial save

### ISSUE THREAD

**Issue by Modicrumb** [cakephp/cakephp#8906]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10.
* Platform and Target: Apache 2.4.2, MariaDB.

### What you did
I simply wanted to edit a user entity and after selecting a parent for tree behavior. I got the following error:
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND -1)' at line 1 
UPDATE users SET lft = ((lft + 1)) WHERE (lft  BETWEEN  AND -1)

On line 265 of TreeBehavior there is the line $min = $parentRight; In my case $parentRight is null.

My controller code for saving
 ```
   /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);

        $parentList = $this->Users->find('treeList',['valuePath'=>'username']);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));
                return $this->redirect(['action' => 'manage']);
            } else {
                $this->Flash->error(__('The user could not be saved. Please, try again.'));
            }
        }

        $this->set(compact('user','parentList'));
        $this->set('_serialize', ['user']);
    }
```

### Expected Behavior
I expect the User to be saved and parent id added

### Actual Behavior
I got an error with no save going through. I think it can be fixed with a $min = (!empty($parentRight)) ? $parentRight : 0;, however I'm not sure if 0 is an alright rght value for saving if it's a root node? I never had to deal with lft and rght values and am not sure how they are meant to work.

**Comment by ADmad** [comment]
lft and right values should always be positive integers. Looks like your tree is corrupt. Use `TreeBehavior::recover()` to try and fix it.

**Comment by ADmad** [comment]
Btw here's a good explanation of how MPTT (which TreeBehavior implements) works https://www.sitepoint.com/hierarchical-data-database-2/

**Comment by Modicrumb** [comment]
Thanks, the recover function worked, I was just confused since I only had two entries in the database and made one the parent of the other, with no db values for parent_id lft or rght filled up. I thought I wouldn't have needed to run a function like that. Will read up on what you posted.
