### ISSUE TITLE
Bake test for controller with prefix returns error

### ISSUE THREAD

**Issue by tzvio** [cakephp/cakephp#8907]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Platform and Target: Ubuntu 16.04  Apache 2.4.18 Postgresql 9.5.2 
using cake bake from console.

### What you did
I'm having an admin section in my app , 
and some of the controllers use admin prefix.
run this command from console:

`bin/cake bake test Controller --prefix admin CustomersController`

### Expected Behavior
Generate test for CustomersControllerTest in TestCase/Controller/Admin

### Actual Behavior
Received error:

_Error: Unknown option `prefix`_

**Comment by markstory** [comment]
This issue was moved to cakephp/bake#254
