### ISSUE TITLE
RFC: NotExistsIn()

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#8909]
This is a:
* [X] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: 3.2.10

### Request for Comments
Does `NotExistsIn()` make any sense to you guys? e.g.
```php
$rules->add($rules->notExistsIn(['user_id'], 'Memberships'));
```

**Comment by markstory** [comment]
How would you see it being used? I'm not doubting that it could be theoretically useful, just wanted to know where it could be in apps folks are building today. 😄

**Comment by Xymanek** [comment]
At first I thought "who needs this?" but now I'm building a forum on cake and I've found a good use for this:

`Threads HasMany Replies` and `Replies BelongTo Threads`. In `threads` table I have `threads.op_reply` field

I would like to `$rules->addDelete()` to make sure that the first reply (opener) is not deleted by admins by accident

**Comment by ionas** [comment]
While I like it `in theory` I couldn't find a use case yet. Closing for now.
