### ISSUE TITLE
Does pear.cakephp.org down completely or temporarily?

### ISSUE THREAD

**Issue by garex** [cakephp/cakephp#8910]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: pear-pear.cakephp.org/cakephp, v2.5.8
* Platform and Target: doesn't matter.

### What you did

Opened pear.cakephp.org

### Expected Behavior

Site is working

### Actual Behavior

The service is temporarily unavailable. Please try again later.

**Comment by rchavik** [comment]
I believe someone from the infrastructure team will look into this.

Thanks for reporting.

**Comment by garex** [comment]
@rchavik We just need to know if there are plans to remove PEAR support someday?

**Comment by ADmad** [comment]
Yes PEAR support will be removed in future. I would suggest you switch to using composer.

**Comment by garex** [comment]
@ADmad We already in process of switching to it, but currently we need to know some more concrete dates.

**Comment by markstory** [comment]
@garex 3.x does not publish pear packages at all. So that is certainly the end. The pear• was not intentionally shut down, it was an accident as we're in the process of moving hosting around a bit.

**Comment by phpnut** [comment]
fixed DNS
