### ISSUE TITLE
Proposal : Add `theme-color` meta tag

### ISSUE THREAD

**Issue by amitmerchant1990** [cakephp/cakephp#8911]
* [x] feature-discussion (RFC)

Add `theme-color` meta tag to set the toolbar color in mobile browsers for all of the newly designed CakePHP sites for better mobile viewing experience.

For example, `<meta name="theme-color" content="#db5945">`

And it would look like below:
![theme-color-ss](https://cloud.githubusercontent.com/assets/3647841/15654288/8ca5ad02-26b0-11e6-8cc5-c72d9c1fb80e.png)

Hope it will enhance the UI experience for users!

**Comment by thinkingmedia** [comment]
It's already supported.

```
echo $this-Html->meta('theme-color','#db5945');
```

**Comment by markstory** [comment]
Great idea! As @thinkingmedia mentioned, we already have this feature :smile:
