### ISSUE TITLE
ViewBlock::set() accepts only strings

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#8921]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Why [ViewBlock::set()](http://api.cakephp.org/3.2/source-class-Cake.View.ViewBlock.html#154-165) changes `$value` into a string?
This causes [View::assign()](http://api.cakephp.org/3.2/source-class-Cake.View.View.html#734-746) can accept only strings and not arrays.

I believe it is absolutely wrong. But even if it was right, in this case we have to correct the documentation, because it seems that `assign()` can accept arrays.

**Comment by dereuromark** [comment]
As you can see the doc block states what is valid:

    @param string $name Name of the block

And the reason can be found further up in the class. See the concat() method, which can concatenate view block content. This is all based on basic string operations.
If you want to set arrays, you would either need a new method like setFromArray() or you would need to adjust the set() method in case of array to loop over it and concact() it.

**Comment by mirko-pagliai** [comment]
With `concat()` I can do something similar:

```
$this->concat('an_array', 'first value of array');
$this->concat('an_array', 'second value of array');
```

But it's not the same!  
Suppose I have an array that comes from another way. What should I do?

```
foreach($my_array as $value) {
    $this->concat('an_array', $value);
}
```

This is horrible inside a template!

**Comment by ADmad** [comment]
View blocks are meant to work with strings only. I have opened a PR updating docs mentioning the type casting.
