### ISSUE TITLE
Inconsistent type used for event data

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8923]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Apache2, Ubuntu, PHP 7

### What you did

Reviewed the usage for the `Event` class to see how to use the $data parameter.

### Expected Behavior

Consistent documentation and type hinting for the $data parameter.

### Actual Behavior

Data property is documented as mixed type.

```
    /**
     * Custom data for the method that receives the event
     *
     * @var mixed
     */
    public $data = null;
```

No type hinting on constructor parameter.

```
    public function __construct($name, $subject = null, $data = null)
    {
        $this->_name = $name;
        $this->data = $data;
        $this->_subject = $subject;
    }
```

Type casting on access method (but property is already public?)

```
    public function data()
    {
        return (array)$this->data;
    }
```

This is kind of confusing. Data can be of any type during the broadcasting of events, but than there is this `_callListener` method in the manager.

```
    /**
     * Calls a listener.
     *
     * Direct callback invocation is up to 30% faster than using call_user_func_array.
     * Optimize the common cases to provide improved performance.
     *
     * @param callable $listener The listener to trigger.
     * @param \Cake\Event\Event $event Event instance.
     * @return mixed The result of the $listener function.
     */
    protected function _callListener(callable $listener, Event $event)
    {
        $data = $event->data();
        $length = count($data);
        if ($length) {
            $data = array_values($data);
        }
        switch ($length) {
            case 0:
                return $listener($event);
            case 1:
                return $listener($event, $data[0]);
            case 2:
                return $listener($event, $data[0], $data[1]);
            case 3:
                return $listener($event, $data[0], $data[1], $data[2]);
            default:
                array_unshift($data, $event);
                return call_user_func_array($listener, $data);
        }
    }
```

Should data be forced as an array parameter in events, but wouldn't this change the event API? is that going to break people's code?

**Comment by markstory** [comment]
While I agree its inconsistent. I'm worried about changing it at this point in time. Public properties can be very fickle and I'd rather not create issues.

We can however, deprecate all the public properties and recommend people use the methods instead. This will give us the opportunity to remove the public properties/inconsistency in 4.x

**Comment by thinkingmedia** [comment]
I was able to work around it by using this method to broadcast events. It uses the `EventDispatcherTrait` but maybe it could be added as `dispatchEventData` or something like that.

```
    /**
     * @param string $name
     * @param mixed $data
     * @return mixed
     */
    public function trigger($name, $data = null)
    {
        return $this->dispatchEvent($name, [$data])->data()[0];
    }
```

**Comment by dereuromark** [comment]
Do you want to provide a PR here?

**Comment by thinkingmedia** [comment]
@derekperkins Sure, but what do you expect to see in the PR.

I would add some methods to read/write the data property, and label the public property as depreciated so that it can transition to protected.

Cake's pattern has been to add a method named `data($key, $value)` that would work like the config trait. So it's one method to read and write.

Is that still the pattern given that PSR-7 has a different approach? I'm still not sure what PSR-7 really is to be honest.

**Comment by ADmad** [comment]
@thinkingmedia We already have `Event::data()` which is a getter. So we can add a complimenter setter method `Event::setData()`. In general we are moving away from combined getter/setter methods as they cause problems.

**Comment by ADmad** [comment]
PSR-7 has nothing to do with events btw :)

**Comment by thinkingmedia** [comment]
@ADmad lol, that's what I figured, but I wasn't sure if I had to add a funky new `withData` method instead of easy to understand `setData`. Oh maybe I'll add `setWithData` just to play it safe.

**Comment by ADmad** [comment]
> Oh maybe I'll add setWithData just to play it safe.

Not sure if you are serious or joking :smile:

**Comment by markstory** [comment]
Unless events are going to become immutable, I wouldn't use `withData` :smile:

**Comment by ADmad** [comment]
Closing as related PR is opened.
