### ISSUE TITLE
Warning (2): Division by zero in PaginatorComponent.php#L214

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#8926]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4.
* Platform and Target: Linux, Apache 2.4.x PHP 5.5.x

### What you did
Test in parameter **limit=null and maxLimit=null**  Or **limit='' and maxLimi=''** Or **limit=0 and maxLimi=0** show error.
cakephp not clean or ignored if any of these parameters.
```
...
...

$where = array(
                    'recursive' => -1,
                    'maxLimit' => null,     //#  'maxLimit' => '',    //#  'maxLimit' => 0,
                    'limit' => null,             //#  'limit' => '',    //#  'limit' => 0,
                    'conditions' => array(
                        'Clientes.tipo_cliente2' => '1',
                        'Clientes.habilitado' => '1' 
                    ),
                    'fields' => array(
                        'Clientes.id_cliente'
                    )
           );

// Set Paginate
$this->paginate = $where;

// Get data
$p = $this->Paginator->paginate();

// View out Test
exit(debug($p)); // Data out is OK, but with a warning Warning (2): Division by zero ;-(

...
...
```

### Expected Behavior
Without warning division if **maxLimit and Limit are equal to NULL or " " or ZERO**

Only the output of the data without error PHP since **CakePHP would have to detect if NULL or " " or ZERO ignoral parameters** and take without **default Limit and maxLimit**

### Actual Behavior
**Warning (2): Division by zero** [CORE/Cake/Controller/Component/PaginatorComponent.php, **line 214]**

Out data ok
.....
.....

> Sorry translation by google translator

**Comment by dereuromark** [comment]
So far a maxLimit has been required for security purposes. You can set it to a very large number though (999999 etc).
But we could make it work for null as well if we want to.

**Comment by thinkingmedia** [comment]
@dereuromark I think zero for unlimited would be the expected behavior by most developers. Null on an integer parameter is kind of strange.

**Comment by EOM** [comment]
CakePHP is highly recommended that ignore the parameters when they are.
```
"límite" => null,  
"límite" => '', 
'límite' => 0,
or
'maxLimit' => nula, 
'maxLimit' => '', 
'maxLimit' => 0,
```

And take the default parameters for each of them.
Do not you think.? That way there is never a warning from PHP.

**Comment by dereuromark** [comment]
@thinkingmedia We are not talking about nullish/falsey values and their differences, but if it is OK in general to completely remove the maxLimit functionality. So far you HAD to set a value >= 1 for security reasons. Allowing 0 (or anything else < 1) does overwrite the security feature here, so that's why I am hesistent to just "agree".

@EOM I agree we need to fix the warning one way or another :) The other way would be to throw a clear exception "Please set a valid maxLimit value >= 1".

**Comment by thinkingmedia** [comment]
@dereuromark I absolutely agree.

If you need to **dump** your database. You shouldn't be using pagination.

**Comment by dereuromark** [comment]
Exactly, as such we just need to make sure we throw an exception if the maxLenght value is < 1 :)
A PR from anyone would be very welcome.

**Comment by EOM** [comment]
I do to show all the data from the DB, for that I use find ('all', ...).
I only test to see if by a merge, cakephp to detect parameters not valid velores was returning to the default.

**Example:**
In this way a whole driver I use. limit => '350' and MaxLimit = '350' but in an action X always mind you step limit => null and MaxLimit => null or the like, so that the pager ignore it and take the default data page.

So I think I would have to clean cakephp not an exception. Since it would make no fexible in performance.?

**Comment by ionas** [comment]
... then do count and set maxlimit to your rowcount - for small tables this will work, for larger it will hit you hard.
for exports and backups see bufferResults=false and streaming row by row

**Comment by markstory** [comment]
Does raising an exception on a limit/maxLimit of '', null, 0 sound reasonable? To me that feels like a NotFoundException as the thing you've asked for will never be found.

**Comment by dereuromark** [comment]
I would only go for maxLimit, as  limit 0 = none might be a valid DRY case to just respect the maxLimit.

**Comment by markstory** [comment]
I'm not sure I follow how limit=0 is ever a productive thing to do.

**Comment by dereuromark** [comment]
As the code shows, this basically means use maxLimit ;)

**Comment by jhli** [comment]
MaxLimit 0 Exception sounds sane if it helps.
limit = 0 => limit = maxLimit also sounds sane.

**Comment by EOM** [comment]
I think the same thing @markstory not have to be an "Exception". CakePHP has only to please ignore if "limit" and "MaxLimit" parameter is not valid and take those who are by default.
Or if you want you can also gener an error in the log file; but no Exception.

CakePHP ORM, just have to ignore if the parameters are not correct, when one overwrites it with arraymerge, so in that case to be NULL, take the defaults.

> I hope this clear idea through google traslartor.

**Comment by markstory** [comment]
@EOM Why wouldn't you want an exception. Silently ignoring programmer error is generally not how we handle those cases.

**Comment by EOM** [comment]
@markstory In this case, I understand that it would be better, see if the parameters are not valid. Using the default parameters. Instead of generating an Exception, which is very determinte in PHP processes.
That's what I think, but they can handle as you think best.

**Comment by markstory** [comment]
Pull request up now.
