### ISSUE TITLE
Event on afterSave

### ISSUE THREAD

**Issue by gustavokataoka** [cakephp/cakephp#8927]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Cake ORM system.

In the _processSave method from Table object, something like the 'Model.beforeSave' event should be done with the 'Model.afterSave' when you triggered the dispatch event. But the event object returned is ignored. Why this is done? The afterSave suggest something I could 'extra' save in this event with external transaction. But I cannot get the event result to trigger the rollback in case of error.

**Comment by lorenzo** [comment]
Can you explain what you are doing? It is not very clear from the ticket description

**Comment by gustavokataoka** [comment]
Here is a example:

I have two tables objects, like this:

// CountUsersTable.php
class CountUsersTable extends Table {
   // all the staff of a table object ...
}

// UsersTable.php
class UsersTable extends Table {
   // all the staff of a table object ...
   function afterSave(...) {
      $countUsers = TableRegistry::get('CountUsers');
      $count = $countUsers->get(1); // Assuming that the id 1 has the count of my list of users
      $count->value += 1;
      if (!$countUsers->save($count)) {
         return false; // HERE IS MY PROBLEM
      }
   }
}

And in my controller class I have this:

// UsersController.php
class UsersController extends Controller {
   function add() {
     $user = $this->User->newEntity();
        if ($this->request->is('post')) {
            $user = $this->User->patchEntity($user, $this->request->data);
            $this->User->connection()->query('BEGIN');
            if ($this->User->save($user, ['atomic'=>false])) {
                $this->Flash->success(__('user saved.'));

                 // Some other things to save ...

                $this->User->connection()->query('COMMIT');
                return $this->redirect(['action' => 'index']);
            } else {
                $this->User->connection()->query('ROLLBACK');
                $this->Flash->error(__('error.'));
            }
        }
        $this->set(compact('user'));
   }
}


Well... the point is: if $countUsers->save($count) fails to save, I want to cancel the save of the user.
This is a simple example, in my real system I have a more complex logic.

Did you understand?

**Comment by markstory** [comment]
We ignore the results of all `after*` events. Because the 'event' is already in the past. In your case you might be better off throwing an exception.

**Comment by Juna22** [comment]
same problem
