### ISSUE TITLE
Enable termination after a single validation error occurred model wide

### ISSUE THREAD

**Issue by markvdlaan93** [cakephp/cakephp#8928]
This is a (multiple allowed):
* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8
* Platform and Target: Apache 2.2.9, MySQL 5.5.42, PHP 5.6.10

### What you did
I tried to enable termination after a single validation error has occurred. Currently, this can be done by using the following snippet of code:

```php
$validator
->add('body', [
    'minLength' => [
        'rule' => ['minLength', 10],
        'last' => true, // this particular line
        'message' => 'Comments must have a substantial body.'
    ]
]);
```

### Expected Behavior
This does the job as expected.

### Actual Behavior
Is there any possibility to enforce this for every validation rule in every model? (or for every validation rule within a model) The documentation doesn't state anything like that. More context: I'm using CakePHP as REST api for an Android and iOS app and requirements enforces me to use the validation error messages directly in the app. Therefore, I only need one single message per time.

**Comment by dereuromark** [comment]
I'd be also very interested in that.
For be this always should have been the default anyway.
Right now having to set it everywhere works, but is cumbersome in a way.

**Comment by markvdlaan93** [comment]
Do you have any advice how to properly deal with this in the meantime? Should I loop through the $entity->errors() array (and pick the first message), make a variable that injects the value in every validation rule or maybe another strategy?

**Comment by markstory** [comment]
Couldn't you write your own validator subclass that overrides add() splicing in 'last' onto ever rule?

**Comment by markvdlaan93** [comment]
I didn't even think about that ;). I will look into that soon, thanks for the feedback.

**Comment by ADmad** [comment]
Like @markstory said one can extend and override the code. Don't see any need to make changes in core validator. The ticket should be closed IMO.

**Comment by dereuromark** [comment]
Maybe this can be documented as a potential frequent use case around validator message behavior changes.

**Comment by markstory** [comment]
Closing as its been a few months and no one has taken the initiative to update the documentation. I take this as an indication that it is either low priority, or not an issue anymore.
