### ISSUE TITLE
Empty Translation-String error __x()  

### ISSUE THREAD

**Issue by DMO-L** [cakephp/cakephp#8932]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: LAMP

### What you did
Try to translate a string by using the __x() function. 

`<?php $link = $this->Html->link(__x('Homepage','art'),'/linkuri'); ?>`

### Expected Behavior
An Empty string or the msgid from the .po file.

### Actual Behavior
When I use the __x() function for translating, and the msgstr is empty in the Locale/XX/default.po file a "Constructor failed" error appears.

**Comment by lorenzo** [comment]
how does your .po file look like?

**Comment by DMO-L** [comment]
```
#: Template/Pages/home.ctp:23
msgctxt "Homepage"
msgid "art"
msgstr ""
```
When i change it to
 ```
#: Template/Pages/home.ctp:23
msgctxt "Homepage"
msgid "art"
msgstr "art"
```
it works without the error.

**Comment by micdobro** [comment]
I can confirm this is also an issue. Basically the moment I started using ``__x()`` in my code the translation machinery in cake takes down the whole app and nothing works. Apparently not only having just an empty translation, but also the same message with and without context is making the ``.po`` reader collapse.

**Comment by markstory** [comment]
Pull request open now.
