### ISSUE TITLE
Pagination 'NOT' notation fails with i18n

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8933]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.8.4.
- Platform and Target: Linux, Apache, MySQL.
### What you did

In the controller:

```
$this->Paginator->settings['conditions'] = array(
    'NOT' => array(
        'I18n__title.content' => ''
    ),
);
```
### Expected Behavior

Properly paginated page
### Actual Behavior

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'I18n__title.content' in 'where clause'
### Solution

I fixed it with:

```
$this->Paginator->settings['conditions'] = array(
    'I18n__title.content !=' => ''
);
```

but it would be good if array notation with 'NOT' would not fail.

**Comment by lorenzo** [comment]
Can you try this? 

```php
NOT' => array(
        array('I18n__title.content' => '')
    ),
```

I think that is the correct usage for `NOT`

**Comment by bancer** [comment]
```
$this->Paginator->settings['conditions'] = array(
    'NOT' => array(
        array(
            'I18n__title.content' => ''
        )
    ),
);
``` 
generates the same SQL error.

**Comment by markstory** [comment]
Closing as a pull request is open now.

**Comment by bancer** [comment]
The problem seems to exist only when limit is set.
