### ISSUE TITLE
Room for one more badge?

### ISSUE THREAD

**Issue by bravo-kernel** [cakephp/cakephp#8934]
It looks like the readme has room for one more badge, how about this one?

[![Slack Status](https://cakesf.herokuapp.com./badge.svg)](https://cakesf.herokuapp.com)

Found [here](https://github.com/rauchg/slackin)

**Comment by ionas** [comment]
Can we then also have https://camo.githubusercontent.com/11cbf2e80af31ece15f2f8f41264eec4173994ec/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636861742d6f6e253230667265656e6f64652d627269676874677265656e2e737667
Ref: https://github.com/badges/shields/issues/69

**Comment by bravo-kernel** [comment]
I figured this might be one of the replies but I was under the impression Slack was/is being positioned as the main support entrance. If so, the badge might be justified. If not, we at least know there is no preferred support channel.

ps: FWIW I have totally changed my opinion and am all :+1: for Slack now, must be the giphy support

**Comment by ravage84** [comment]
I would prefer to see such badges rather on the main website.
They don't belong to the development process, compared to other badges like Travis etc.

Let's not add badges that don't help the development process more or less directly.

**Comment by tersmitten** [comment]
I agree with @ravage84

**Comment by ionas** [comment]
The badges are already on the main site.
However, as I reported by email already http://book.cakephp.org/3.0/en/index.html misses slack icon where on http://book.cakephp.org it is present.

**Comment by ionas** [comment]
I don't think buttons for social/docs on the repo readme would hurt linking to:
docs, api, discourse, stackoverflow, irc, slack

**Comment by ADmad** [comment]
The readme of this repo already has links to slack, forum etc. Let's keep badges for development purposes only.
