### ISSUE TITLE
add dynamic prefix into url

### ISSUE THREAD

**Issue by anyway111** [cakephp/cakephp#8937]
Dear guys,<br>
I want to add dynamic prefix into url<br>
How do it by cakephp?<br>
Sorry if i have post mistake.<br> 
Example: <br>when user choose location en-us or ja-jp. url or category-machine, category-sport became as bellow<br>
```
xxx.com/en-us/category-machine/ads/  
xxx.com/ja-jp/category-sport/ads/ 
```

**Comment by ionas** [comment]
It is not a mistake but this is not a help forum.

You can take a look at cakefest2016 repositories by @lorenzo and/or @steinkel in those routes.php files.
Furthermore try http://discourse.cakephp.org/ stackoverflow and irc or slack.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
