### ISSUE TITLE
Cakephp empty Associations on Linking Tables Together

### ISSUE THREAD

**Issue by fgagneten** [cakephp/cakephp#8940]
I want to do this: http://book.cakephp.org/3.0/en/orm/associations.html1 but it's not working the cell in my complejo table is empty when I want to show the name of the another model (ciudad name). I want to show the name, not the Id of Ciudad. Here you can see the empty column:[ Click Me](http://oi68.tinypic.com/2h4cqbr.jpg)
here you can se my question and my code:[Click Me](http://stackoverflow.com/questions/37625943/cakephp-empty-associations-on-linking-tables-together)

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
