### ISSUE TITLE
Can't use a custom redirect route

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#8942]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: Win 8.1, Nginx php 5.6

### What you did

I wanted to extend the redirect route but  I can't modify it...

```php
    public function redirect($route, $url, array $options = [])
    {
        $options['routeClass'] = 'Cake\Routing\Route\RedirectRoute';
        if (is_string($url)) {
            $url = ['redirect' => $url];
        }
        $this->connect($route, $url, $options);
    }
```

### Expected Behavior

Being able to pass my own `$options['routeClass']` redirect route class without getting it overriden by the default.

### Actual Behavior

`$options['routeClass']` is overriden.

I'm aware that I can just use Router::connect() but this was just like a trap.

**Comment by markstory** [comment]
Should there be any errors when someone uses an incompatible custom route class? The function will 'not work' then.

**Comment by Xymanek** [comment]
Maybe force that class to extend `Cake\Routing\Route\RedirectRoute` and otherwise throw an exception?

**Comment by markstory** [comment]
@Xymanek Userland extensions could still 'break' the redirect behavior if they wanted to. Perhaps no action is required. Users who want to hurt themselves will always find a way :smile:

**Comment by Xymanek** [comment]
True. Yet still two things bother me about this:

- Currently `$routes->redirect()` is basically a shortcut to `$routes->connect()` which takes away the job of typing the class name for redirect routes
- However it also makes it easier to read `routes.php` and understand that line x actually connects and the one after causes a redirect. And when half redirects are `$routes->redirect()` and other are `$routes->connect()`, the file becomes very confusing

As a solution to keep both usages how about adding `Router::defaultRedirectClass()` (similar to `Router::defaultRouteClass('DashedRoute')`) which will be used by `$routes->redirect()` function

**Comment by lorenzo** [comment]
The default redirect class is a goo idea

**Comment by burzum** [comment]
@lorenzo I'll implement it some time soon.

**Comment by markstory** [comment]
I'm not a huge fan of adding more global state which is what I assume `Router::defaultRedirectClass()` would do. Just allowing a `routeClass` option in `redirect()` feels simpler to me.

**Comment by burzum** [comment]
@lorenzo @markstory which one of both possible implementations do you want? Router::defaultRedirectClass() or the routeClass option? Please decide before I spend time on implementing one of both and getting told to implement the other one then.

**Comment by lorenzo** [comment]
Let's go with @markstory suggestion, do the routeClass

**Comment by burzum** [comment]
Closing this because of the pending PR.
