### ISSUE TITLE
Tuning Hash::merge

### ISSUE THREAD

**Issue by odan** [cakephp/cakephp#8946]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

### What you did
Merging config values with: Cake\Utility\Hash::merge($defaults, $config, $environment);

### Expected Behavior
Replaced elements from passed arrays into the first array recursively.

### Actual Behavior

The merge function does the same like the internal PHP function: "array_replace_recursive"
http://php.net/manual/de/function.array-replace-recursive.php

The only difference is that array_replace_recursive returns null if an array is empty. Maybe there could be  a big performance benefit by wrapping the native array_replace_recursive function instead of the custom logic.

**Comment by dereuromark** [comment]
Please look into the source code and read https://github.com/cakephp/cakephp/blob/master/src/Utility/Hash.php#L714-L716 etc.
There is more logic involved, thus we cannot change anything here.

If you worry about speed, you can yourself try to use less of this method and more PHP core functionality.
But I think this ticket should be closed as works-for-me.
