### ISSUE TITLE
Nested "restful"-route doesn't work when adding an extension like .json

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#8947]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: 5.6.21-9+donate.sury.org~trusty+1 and simple chrome/postman/firefox HTTP get

### What you did
Added following nested "restful"-url to routing.php: https://gist.github.com/Spriz/df18b6f411271970738dbda5277f042f#file-routes-php-L5

### Expected Behaviour
that /api/items/:item_id/variants would work with `$this->request->params('item_id')` in the `VariantsController` (like the book explains)

### Actual Behaviour
Without `.json` extension, it works - but when adding a `.json` extension, I get this error: https://gist.github.com/Spriz/df18b6f411271970738dbda5277f042f#file-response-json-L4
(it's looking for an action with the id rather than using the routes)

If I `var_dump()` the `$route` variable here: https://github.com/cakephp/cakephp/blob/master/src/Routing/Route/Route.php#L276 it's already "wrong": 
```
[
	(int) 0 => '/api/items/000443c8-cd07-35a9-a3f1-74b61ac8f233/variants',
	'controller' => 'items',
	(int) 1 => 'items',
	'action' => '000443c8-cd07-35a9-a3f1-74b61ac8f233',
	(int) 2 => '000443c8-cd07-35a9-a3f1-74b61ac8f233',
	'_args_' => 'variants',
	(int) 3 => 'variants'
]
```

I figured it should be somewhere before this it's going wrong.

It's matching the following route: 
`'#^/api/(?:(?P<controller>[^/]+))/(?:(?P<action>[^/]+))(?:/(?P<_args_>.*))?[/]*$#'`

instead of one of the previous ones: `'#^/api/items/(?:(?P<item_id>[^/]+))/variants[/]*$#'`

**Comment by Spriz** [comment]
This is how the book describes it: http://book.cakephp.org/3.0/en/development/routing.html#creating-nested-resource-routes

**Comment by lorenzo** [comment]
You need to call extensions() first, then connect your routes

**Comment by markstory** [comment]
The docs also state

> Setting the extensions should be the first thing you do in a scope, as the extensions will only be applied to routes connected after the extensions are set.

**Comment by Spriz** [comment]
Wow, I totally missed that - but it makes sense. Thanks.
