### ISSUE TITLE
Bug in InflectedRoutes for Router::prefix in RESTFUL routes.

### ISSUE THREAD

**Issue by cpierce** [cakephp/cakephp#8949]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Vagrant with NGINX.

### What you did
While creating a restful API using cakePHP 3 I noticed that trying to use 'only' in inflected routes doesn't work.

```
Router::scope('/', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Homes', 'action' => 'index']);
    $routes->fallbacks('InflectedRoute');
});

Router::prefix('api', function($routes) {
    $routes->resources('Feeds', [
        'only' => ['add', 'delete'],
    ]);
    $routes->resources('ApiKeys', [
        'only' => ['add'],
    ]);
});
```

In the above example 'only' works fine for `Feeds` but not for `ApiKeys`.  This gives an error `Error: ApiController could not be found.` however if I remove the 'only' from the ApiKeys so that the code looks like:

```
    $routes->resources('ApiKeys');
```

the function works as expected and I do not get the error.  Note again this only happens on inflected routes such as /api/api_keys/ and both ways work on /api/feeds/

### Expected Behavior
I would expect both inflected (ApiKeys) and non inflected (Feeds) routes to work the same.

### Actual Behavior
Only the non inflected (Feeds) works correctly.

**Comment by markstory** [comment]
There is no `'add'` action by default. Did you mean to use `'create'` instead?

**Comment by cpierce** [comment]
ahhh this is why ... it's odd though it actually worked to allow 'add' in the cases where it was singular.  (shrug) oh well, changing it did fix my stuff.
