### ISSUE TITLE
\Cake\I18n\Date() return bad date.

### ISSUE THREAD

**Issue by Sensetivity** [cakephp/cakephp#8952]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: OpenServer 5.2.2, PHP 5.6, Mysql 5.5

### What you did
I have string with date like this: "2016-06-14". I have table and model. In table field is DATE. And I try save it.

### Expected Behavior
Correct date.

### Actual Behavior
So when I create new Entity and set data entity return me Entity object with wrong data in Date object.

```
....................
'start_date' => object(Cake\I18n\Date) {

		'time' => '1909-09-23T00:00:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	}

```

**Comment by lorenzo** [comment]
How are you constructing the date?

**Comment by Sensetivity** [comment]
simple. I have input with type text and Bootstrap datepicker. Date come to back-end as string with next format: yyyy-mm-dd.
``
$book = $this->Bookings->findByTrackingHash($hash)->first();
        if ($book) {

            $book = $this->Bookings->patchEntity($book, $data);
            $this->Bookings->save($book, ['validate' => 'StepOne']);

        }
``

Dump of $data:
``
\src\Controller\BookingsController.php (line 117)
[
	'traveling' => 'traveling',
	'country_id' => '207',
	'number_tickets' => '5',
	'start_date' => '2016-06-07',
	'end_date' => '2016-06-23',
	'accommodation' => 'accommodation',
	'fans_number' => '5',
	'room_number' => '2',
	'hotel_stars' => '4',
	'filled_completely' => (int) 0,
	'tracking_hash' => 'af7ab1629acad48b1adc8d4c84e03885'
]
``

**Comment by lorenzo** [comment]
do you bay chance have `useLocaleParser()` in bootstrap.php?

**Comment by Sensetivity** [comment]
No. In bootstrap I just have:
Type::build('date')->useLocaleParser();
Type::build('datetime')->useLocaleParser();

But I have setted locale in my controller:
I18n::locale('en');

**Comment by lorenzo** [comment]
When having `useLocaleParser()` the date will be expected to come from the user in the format for his language (which rarely is `yyyy-mm-dd`. You can remove those two calls from bootstrap.php if you don't need it.
