### ISSUE TITLE
Add new method transpose to collection class

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#8955]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.0

### What you did
Add an new method **transpose** to collection class, which will transpose rows and columns into columns and rows. 

e.g.

 ```
      $items = [
            ['Products', '2012', '2013', '2014'],
            ['Product A', '200', '100', '50'],
            ['Product B', '300', '200', '100'],
            ['Product C', '400', '300', '200'],
      ]
     
      $transpose = (new Collection($items))->transpose()->toList();
```
     
Returns results as shown below
```
      [
          ['Products', 'Product A', 'Product B', 'Product C'],
          ['2012', '200', '300', '400'],
          ['2013', '100', '200', '300'],
          ['2014', '50', '100', '200'],
      ]
```

This is a very handy method for processing array data. Which exists in ruby.

**Comment by burzum** [comment]
@markstory can we close this? The PR has been merged. I don't mind doing it as well but I think you have the last word on it. :)
