### ISSUE TITLE
URL http://book.cakephp.org/3.0/en/installation.html add new warning

### ISSUE THREAD

**Issue by galerienv** [cakephp/cakephp#8958]
This is a :
* [x] bug
* [x] enhancement

* CakePHP Version: 3.2.10
* Platform and Target: i have tested only on WAMPServer 3.0.4 X64 with Windows 10 up to date

When you create a project with "php composer.phar create-project --prefer-dist cakephp/app" command, you obtain systematically an error.

```
C:\wamp64\www>php composer.phar create-project --prefer-dist cakephp/app Test
Installing cakephp/app (3.2.6)
  - Installing cakephp/app (3.2.6)
    Downloading: 100%

Created project in Test
Loading composer repositories with package information
Updating dependencies (including require-dev)


  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/cakephp/cakephp%248b31ddac510d167fe642064c07b27b90b8152c95d883ae1a5802eeda98815cdf.json
  " file could not be downloaded: failed to open stream: HTTP request failed!


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] `[<version>]`
```

To solve the problem, you must go in project directory and add to end of composer.json file, following instruction :

```
"repositories": [
		{
         "type": "composer", 
         "url": "https://packagist.org"
		},
		{ "packagist": false }
	]
```

Save new composer.json and execute a php composer.phar update. After you have in cache all packages and you can install correctly other project if needed.

After pass many hours to find a solution, i think that can help many people.

Regards.

**Comment by markstory** [comment]
I've never seen that error before, is there anymore detail on why the HTTP request failed to packagist?

**Comment by chinpei215** [comment]
@galerienv Can you reproduce this issue yourself even now? By executing composer with `-vvv` option, you can see more detail about what is happening in you computer.

Reading output, I am guessing that you would have gotten a corrupt or outdated `p-provider-latest.json` from packagist, for some unknown reasons.

Now, the content of `p-provider-latest.json` being cached in my computer is like the follwoing:
```javascript
{
    "providers": {
        ...
        "cakephp\/app": {
            "sha256": "661670b185eb18196cf90ce563f3f93020102108a02fb56b0c579e58fb6019df"
        },
        "cakephp\/cache": {
            "sha256": "b8eee63a5b6b7408dc7f448b77766f475052c3c49bf7f7972186e66c7b10bd19"
        },
        "cakephp\/cakephp": {
            "sha256": "aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875"
        },
        ...
    }
}
```
So composer should download `cakephp%24aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875.json`. But, in your case, composer tried to download `cakephp%248b31ddac510d167fe642064c07b27b90b8152c95d883ae1a5802eeda98815cdf.json`, and failed to do it. Indeed, the url seems no longer available.

Probably, it would be a temporary issue of packagist or your proxy cache server (if you are using). I think there is not much we can do about it.

**Comment by galerienv** [comment]
Hi all,

the problem is packagist.org accept only HTTPS usage and config use only HTTP.

In attachment, the execution with -vv switch, my composer.phar if it need you and PHP -i command
[config_php.txt](https://github.com/cakephp/cakephp/files/306607/config_php.txt)
[composer.zip](https://github.com/cakephp/cakephp/files/306600/composer.zip)

![with vv switch](https://cloud.githubusercontent.com/assets/10227016/15925557/eaff5428-2e37-11e6-963e-e156b44783c3.jpg)

**Comment by chinpei215** [comment]
Thanks. This time your hash value is correct. But packagist seems busy. Now I got an error like the following:
```
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json
Reading C:/Users/chinpei/AppData/Local/Composer/repo/https---packagist.org/packages.json from cache
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: 
```
But failure to download `https://packagist.org/packages.json` three times wouldn't our fault. What if stop clearing cache before executing composer? Then you can use cache, like my case.

**Comment by galerienv** [comment]
i have try to generate an output text file with a DOS redirection but it's failed to generate output..

To have correct output information, i have clear cache before rexecute command but it's not mandatory.

**Comment by chinpei215** [comment]
> i have try to generate an output text file with a DOS redirection but it's failed to generate output..

If you want to redirect std error, you can do it in the following way:
```bat
dosomething > output.txt 2>&1
```

Aside from that, reading your output generated with `-vvv`, you succeeded to download `https://packagist.org/packages.json` at line 13-14, unlike me.
```
Downloading https://packagist.org/packages.json
Writing C:/Users/galerien/AppData/Local/Composer/repo/https---packagist.org/packages.json into cache
```
But failed to download `http://packagist.org/p/cakephp/cakephp%24aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875.json` at line 61-63
```
Downloading http://packagist.org/p/cakephp/cakephp%24aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875.json
Downloading http://packagist.org/p/cakephp/cakephp%24aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875.json
Downloading http://packagist.org/p/cakephp/cakephp%24aee872b5e4bc8b20614d5822198ee029b8a314b5d9cea8c5eae09bf36225c875.json
```
So If you retry without clearing cache, I think you would succeed to install.
