### ISSUE TITLE
routes from the baked plugin are not working.

### ISSUE THREAD

**Issue by sasilen** [cakephp/cakephp#8960]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.6 (latest stable via composer)
* Platform and Target: Debian/Apache/Sqlite3

### What you did
I started cakephp project
```
composer create-project --prefer-dist cakephp/app www
cd www
./bin/cake bake plugin Attribute
./bin/cake migrations migrate -p Attribute 
./bin/cake bake all Attributes -p Attribute
composer dumpautoload
./bin/cake plugin load Attribute
```
### Expected Behavior
Accessing the url "https://DOMAIN/Attribute/attributes" should give me an index view

### Actual Behavior
> Error: AttributeController could not be found.
> Error: Create the class AttributeController below in file: src/Controller/AttributeController.php

After I tried to start numerous times from the scratch I always ended up in the same error. Today I found out a case from the stackoverflow which did the trick ([http://stackoverflow.com/questions/33897415/cant-create-simple-cakephp-plugin/33915384](http://stackoverflow.com/questions/33897415/cant-create-simple-cakephp-plugin/33915384)). After I replaced my plugin routes.php accordingly everything worked.

**Comment by markstory** [comment]
Thanks for the detailed steps, I'll see if I can reproduce the same issue.

**Comment by markstory** [comment]
Your URL should be `/attributes/attributes` all lowercase. The `Router::plugin()` helper inflects the plugin name when generating the URL path segment. Alternatively, you can use the `path` option to define the path you want.

**Comment by sasilen** [comment]
I reverted old routes back and tried again that  `/attributes/attributes`, still didn't work. My original routes looks like this 
> Router::plugin(
>     'Attribute',
>     ['path' => '/attribute'],
>     function (RouteBuilder $routes) {
>         $routes->fallbacks('DashedRoute');
>     }
> );

I haven't figured out the URL which could work for this plugin (i've tried many).

**Comment by markstory** [comment]
With the snippet you pasted, your URL would be `/attribute/attributes`.
