### ISSUE TITLE
Number format helper displays NULL as 0

### ISSUE THREAD

**Issue by buraiadam** [cakephp/cakephp#8961]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.2.10
* Platform and Target: php7

### What you did
```php
$this->Number->format(null)
```

### Expected Behavior
If parameter is null output should be empty 

### Actual Behavior
`$this->Number->format(null)` displays 0 instead of nothing.

When there is no data assigned to an attribute it is not a same as assigning 0.
For example I use this helper to display prices sometimes prices are not defined, in this case it does not mean they are free.
I could check for null every time but this helper is designed to remove boilerplate code.

**Comment by half2me** [comment]
I agree. :)

**Comment by ADmad** [comment]
`number_format(null)` return `0`.  So it's intuitive to have `NumberHelper` behave similarly.

**Comment by ADmad** [comment]
The engine used by `NumberHelper` is configurable so if you want `NumberHelper::format()` to behave differently use your own engine.
