### ISSUE TITLE
ExceptionRenderer doesn't handle custom status code as expected 

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#8962]
(The original issue was reported from @nojimage)

This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.10 / 2.8.4
- Platform and Target: non-related
### What you did

Throw an exception with a custom error code.

``` php
$this->response->httpCodes([
   509 => 'Bandwidth Limit Exceeded',
]);

throw new HttpException('We are sorry', 509);
```
### Expected Behavior

Get an error page with http code 509.
### Actual Behavior

Get an error page with http code 500. 
Because ExceptionRenderer [only allows HTTP codes within range 400 to 506](https://github.com/cakephp/cakephp/blob/2224d73f86ff6a13e7bb276791a1651089d60170/src/Error/ExceptionRenderer.php#L304-L308):

``` php
$errorCode = $exception->getCode();
if ($errorCode >= 400 && $errorCode < 506) {
    $code = $errorCode;
}
return $code;
```

But I think it would be better to allow any status code if a caught exception is an instance of `HttpException`.
### Solution

Change the above to the following:

``` php
$errorCode = $exception->getCode();
if ( $errorCode >= 400 && $errorCode < 506
    || $exception instanceof HttpException && $this->controller->response->httpCodes($errorCode)
) {
    $code = $errorCode;
}
return $code;
```

Do you think this change is backward compatible?

**Comment by markstory** [comment]
@chinpei215 I think that's a pretty safe looking change.

**Comment by chinpei215** [comment]
Thanks. I'll open a pull request later. Probably, tonight.

**Comment by markstory** [comment]
Awesome 🌈

**Comment by chinpei215** [comment]
@markstory After implementing this feature, I noticed another issue. Even if I registered a custom http code into the `Response` class via the `httpCodes()` method, they were not available in the `ExceptionRenderer`, because after an exception was thrown, the `ExceptionRenderer` would instantiate a different `Response` object [here](https://github.com/cakephp/cakephp/blob/2224d73f86ff6a13e7bb276791a1651089d60170/src/Error/ExceptionRenderer.php#L120).
Since `ErrorController` is not a subclass of `AppController`, I couldn't register any custom http codes into the response object of the `ErrorController` by handling controller events. A workaround would be to create my `AppErrorController`. But it's annoying little bit.

So what do you think about adding a new configuration to allow users to register custom http codes? The configuration and implementation would be like the following code:
```php
// In config/app.php
[
    'App' => [
        'customHttpCodes' => [
            509 => 'Bandwidth Limit Exceeded',
        ]
    ]
]
```
```php
// In src/Newtork/Response.php

public function __construct(array $options = [])
{
    ...

    $codes = Configure::read('App.customHttpCodes');
    if ($codes) {
        $this->httpCodes($codes);
    }
}
```

**Comment by ADmad** [comment]
@chinpei215 That sounds a bit of an overkill something that is rarely needed.

Would there be any drawbacks/problems if we just relaxed the check `$errorCode < 506` to `$errorCode < 600`?

**Comment by chinpei215** [comment]
@ADmad Thank you for your comment.

> Would there be any drawbacks/problems if we just relaxed the check $errorCode < 506 to $errorCode < 600?

See #6094. To be honest, I want to remove the `$errorCode >= 400 && $errorCode < 506` check in the future release.

Aside from that, `Response` class only allows status codes defined in the `_httpCodes` properties. So we would need some way to register custom http codes into the `Response` object created in the `ErrorRenderer`.

**Comment by ADmad** [comment]
That fact that exception renderer using a new `Response` instance has been an issue in the past too. For example the `WWW-Authenticate` being lost when throwing a `401 Unauthorized` exception from `BasicAuthenticate`.  To remedy that we added `Exception::responseHeader()` which allows setting response header which are then passed on to the new `Response` object by `ExceptionRender`. We could use a similar approach to set custom error codes too.

**Comment by chinpei215** [comment]
Interesting. I didn't know the method. I'll take a look tomorrow. If you have any ideas, please let me know. Now I am thinking of the following:
```php
// In the Response class
public function httpCodes($code = null)
{
    // Calling HttpException::registerErrorCode() method if $code contains unknown error code.
}
```

**Comment by ADmad** [comment]
I am not particularly thrilled about my proposal either but don't have anything better for now :)

**Comment by markstory** [comment]
>  I want to remove the $errorCode >= 400 && $errorCode < 506 check in the future release.

Why can't we do that now?

**Comment by chinpei215** [comment]
If we remove `$exception instanceof HttpException` cehck, we can do it?
```php
if ($erroCode >= 400 && $this->controller->response->httpCodes($errorCode)) {
    $code = $errorCode;
}
```

But I mean that it doesn't solve #6094. Actually, we are using 404 for the error code of `RecordNotFoundException`. But theoretically, I think datasources should not be related with HTTP. It would be better to wrap `RecordNotFoundException` with `NotFoundException` in the dispather:
```php
try {
    // invokeAction
} catch (RecordNotFoundException $e) {
    throw NotFoundException::wrapException($e);
}
```

Or to add a feature to let `ExceptionRenderer`know which exceptions should be rendered as 404:
```php
ExceptionRenderer::mapExceptions([
    'Cake\Datasource\Exception\RecordNotFoundException' => 'Cake\Network\Exception\NotFoundException',
]);
```

**Comment by inoas** [comment]
I'd still like see this change, as the limit should not be "509"

```
$errorCode >= 400 && $errorCode < 506
    || $exception instanceof HttpException && $this->controller->response->httpCodes($errorCode)
``` 

Looks okay. I wonder however if we cannot have a static list of supported http error codes + allow anything where $exception instanceof HttpException?

**Comment by markstory** [comment]
Isn't a static list similar to the range we currently have?  I am onboard with the change @chinpei215 suggested.

**Comment by chinpei215** [comment]
> \+ allow anything where $exception instanceof HttpException

@ionas We cannot. Respoinse can send supported http error codes only. See [here](https://github.com/cakephp/cakephp/blob/0e6a509ea02081ac17250612d78ed82101c8ca51/src/Network/Response.php#L668-L670).

Re-thinking this issue, the following check may be more better.

```php
if ($errorCode >= 400 && $this->controller->response->httpCodes($errorCode) && ($code < 506 || $exception instanceof HttpException)
    $code = $errorCode;
}
```

Reasons:
- At the moment, if an exception is thrown with code 499 (not listed in supported http codes), another exception will be thrown during exception rendering. It should be fixed. = `$this->controller->response->httpCodes($errorCode)`
- If a user throws an exception not derived from HttpException, but the value of $code property is 404 (like RecordNotFoundException), we should send HTTP 404 to the client. = `$code >= 400`
- If a user throws an exception not derived from HttpException, and the value of $code property is 506 or greater, we should send HTTP **500** (not 506) to the client. Because I don't want to increase the hole size of #6094. = `$code < 506`
- But if a user throws an instance of HttpException, we should allow to send HTTP code 506 or greater. = `$execption instanceof HttpException`

**Comment by markstory** [comment]
Could a solution be to map out the remaining HTTP status codes in `Response` and remove most of the need to define 'custom' HTTP status codes? Wouldn't that solve some of the code range issues at least for `HttpException`. For other exception types we should emit 500 unless we know the exception type.

**Comment by dereuromark** [comment]
@chinpei215 Are you still interested in providing a PR here to fix things? The approach so far seems to be acceptable.

**Comment by chinpei215** [comment]
@dereuromark Sorry for my late reply. I totally forgot about this issue. Since cakephp/app#432 has been already merged, the original approach could work. I will re-think this issue when I have time.
