### ISSUE TITLE
CakeTime utility translates the day but not the month when using timehelper's niceShort() method.

### ISSUE THREAD

**Issue by Tomicapo** [cakephp/cakephp#8968]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4
* Platform and Target: Windows, Xampp (1.8.1), I think any platform would be the same.

### What you did
I set my locale in core.php this way:

```PHP
	date_default_timezone_set('America/Argentina/Buenos_Aires');
	$os = env('OS');
	if (!empty ($os) && strpos($os, 'Windows') !== false) {
		setlocale(LC_ALL, 'Spanish (Argentina)');
	} else {
		setlocale(LC_ALL, 'es_AR');
	}

	Configure::write('Config.language', 'esp');
```

Then I echo a date using Time Helper's method niceShort() this way:
```PHP
<?= $this->Time->niceShort($object['Product']['modified']); ?>
```

### Expected Behavior
I expect to see the dates in spanish.

### Actual Behavior
I see the day in spanish but the months are in english.
Example: 	
> Miércoles **June** 08, 19:52

Should be:
> Miércoles **08 de Junio**, 19:52

Or at least:
> Miércoles **Junio** 08, 19:52

**Comment by Tomicapo** [comment]
It also happens when date is further away:

> **Jan** 23rd, 18:29

should be:
> **Ene** 23rd, 18:29

**Comment by Tzaoh** [comment]
Hello, I think you need to use a custom "cake.po" file.
CakePHP have several for differents languages.

https://github.com/cakephp/localized/tree/master/src/Locale/es

**Comment by Tomicapo** [comment]
Hi, Tzaoh. Thanks for your comment. I do have that same file in: app\Locale\esp\LC_MESSAGES\cake.po
Apart from the main issue, that file doesn't even include translations for 3 letter day and month abbreviations.

For what I've seen, the translation is simply not implemented in the file:
[/lib/Cake/Utility/CakeTime.php](https://github.com/cakephp/cakephp/blob/2.8.4/lib/Cake/Utility/CakeTime.php)

I can see the days get translated on line 407 but not months.

**Comment by markstory** [comment]
Closing as tests are passing showing this code is working as expected. Be sure to ensure that you have the necessary locale features installed from your operating system package manager. For example on debian you may need to run `sudo locale-gen es_AR`.
