### ISSUE TITLE
request->data is always empty when I'm using content-type

### ISSUE THREAD

**Issue by titom59280** [cakephp/cakephp#8969]
I work with cakePhp for a couple of month and so far I have no problem, but today I tried to send some data from my android application and it's not working.

So I saw that the request->data is filled with my parameters when I did not set the content-type but when I set it with application/json, because I need to see if the request came from android, the request->data is empty instead all parameters is on input

How can I have the parameters in request->data with the content-type?

Thanks for your help

**Comment by lorenzo** [comment]
I'm currently using this dispatcher filter to implement this requirement:

```php
<?php

namespace App\Routing\Filter;

use Cake\Event\Event;
use Cake\Routing\DispatcherFilter;

class JsonInputFilter extends DispatcherFilter
{
    public function beforeDispatch(Event $e)
    {
        $request = $e->data['request'];
        if (!$request->is(['put', 'post', 'patch'])) {
            return;
        }

        if (strpos($request->header('Content-Type'), 'application/json') === false) {
            return;
        }

        $request->data = json_decode($request->input(), true);
    }
}

```

The add it to in bootrstrap.php:

```php
DispatcherFactory::add('JsonInput');
```

**Comment by dereuromark** [comment]
This should probably be a core or plugin disaptcher filter with some docs along with it :)

**Comment by markstory** [comment]
RequestHandlerComponent generally handles this kind of work. What is the content-type that android browsers are sending? We could add that as a content-type that maps to JSON.

**Comment by mattmemmesheimer** [comment]
I'm a bit confused on this one.  If you're sending JSON data, you should be setting the content type to reflect that in the `Content-Type` header (which is `application/json` as defined in [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt)).  Otherwise, how will the server know how to interpret that data?  If you are sending form data, the content type header should reflect that.  Consider the following example I just ran

```php
class UsersController extends AppController
{
   public function test()
   {
      debug($this->request->data);
      die;
   }
}
```

POSTing with no or incorrect `Content-Type` header
```bash
$ curl --data "{\"hello\":\"world\"}" http://mysite.com/users/test
[]
$ curl --data "{\"hello\":\"world\"}" -H "Content-Type: text/html" http://mysite.com/users/test
[]
$ curl --data "{\"hello\":\"world\"}" -H "Content-Type: bogus/type" http://mysite.com/users/test
[]
```
POSTing with `Content-Type: application/json` header
```bash
$ curl --data "{\"hello\":\"world\"}" -H "Content-Type: application/json" http://mysite.com/users/test
[
   'hello' => 'world'
]
```

If you are trying to infer that the client is an Android application simply by detecting that the `Content-Type` header is `application/json`, you are going about it the wrong way.  If this is the case, you should consider using a custom header.

**Comment by annuh** [comment]
Nice, I just wanted to create a issue for this problem.

I'm having to same problem with CakePHP v2.8.3. Is it possible to apply the same fix to the 2.x branch?

**Comment by markstory** [comment]
@annuh Do you have RequestHandler enabled, and are your clients sending content-type headers?

**Comment by annuh** [comment]
@markstory Yes, and it only happens if the content-type header is set to 'application/json'.

**Comment by markstory** [comment]
Ok, I will see if I can reporduce with that content type header.

**Comment by markstory** [comment]
I'm not able to reproduce this issue in 2.x or in 3.x.

```php
class ArticlesController extends AppController {
	public $components = ['RequestHandler', 'Flash'];

	public function index() {
		$this->autoRender = false;
		print_r($this->request->data);
	}
}
```

I have a 2.x application setup at `cake.localhost`, and the following curl request works fine:

```
$ curl -XPOST -d '{"hello":"world"}' http://cake.localhost/articles/
Array
(
    [{"hello":"world"}] =>
)
```

As mentioned earlier in the thread you need to have the correct header and controller setup similar to how I set my controller up above.

**Comment by pascualbayo** [comment]
> I'm not able to reproduce this issue in 2.x or in 3.x.
> 
> ```
> class ArticlesController extends AppController {
>     public $components = ['RequestHandler', 'Flash'];
> 
>     public function index() {
>         $this->autoRender = false;
>         print_r($this->request->data);
>     }
> }
> ```
> 
> I have a 2.x application setup at `cake.localhost`, and the following curl request works fine:
> 
> ```
> $ curl -XPOST -d '{"hello":"world"}' http://cake.localhost/articles/
> Array
> (
>     [{"hello":"world"}] =>
> )
> ```
> 
> As mentioned earlier in the thread you need to have the correct header and controller setup similar to how I set my controller up above.

I was missing the definition of the RequestHandler component. So much time spent looking for this response. Thanks!
