### ISSUE TITLE
cannot filter in BTM by null with notMaching

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/cakephp#8970]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.11.1.
* Platform and Target: PHP7 apache2.

### What you did
I have a BTM relationship and I am trying to get the rows in A that arent referenced in B
A = Summoners
B = Games.

I tried:

```PHP
$summoners = $this->Summoners->find()
	->select(['Summoners.id'])
	->leftJoinWith('Games')
	->where(['Games.gameId IS NULL']);
			
SELECT 
    Summoners.id AS `Summoners__id`
FROM
    summoners__ Summoners
        LEFT JOIN
    games__ Games ON 1 = 1
        LEFT JOIN
    summoners_games summoners_games ON (Summoners.id = (summoners_games.summonerId)
        AND Games.gameId = (summoners_games.gameId))
WHERE
    Games.gameId IS NULL
```
and 

```php
$summoners = $this->Summoners->find()
	->select(['Summoners.id'])
	->distinct(['Summoners.id'])
	->notMatching('Games');

SELECT 
    Summoners.id AS `Summoners__id`
FROM
    summoners__ Summoners
        LEFT JOIN
    games__ Games ON 1 = 1
        LEFT JOIN
    summoners_games summoners_games ON (Summoners.id = (summoners_games.summonerId)
        AND Games.gameId = (summoners_games.gameId))
WHERE
    ((summoners_games.summonerId) IS NULL
        AND (summoners_games.gameId) IS NULL)
GROUP BY Summoners.id
```

None of the results were correct (both have IDs which actually have games in the targetTable).

### Expected Behavior
to get returned summonersIds which doesnt have games saved in the database.
Maybe any of this SQLs.

```PHP
SELECT
	summoners__.id
FROM
	summoners__
LEFT JOIN
	summoners_games ON summoners__.id = summoners_games.summonerId
WHERE
	summoners_games.summonerId IS NULL;
```
```PHP
SELECT
	summoners__.id
FROM
	summoners__
LEFT JOIN summoners_games ON
	summoners__.id = summoners_games.summonerId
LEFT JOIN games__ ON
	summoners_games.gameId = games__.gameId
WHERE
	summoners_games.summonerId IS NULL;
```
```PHP
SELECT
	summoners__.id
FROM
	summoners__
LEFT JOIN summoners_games ON
	summoners__.id = summoners_games.summonerId
LEFT JOIN games__ ON
	summoners_games.gameId = games__.gameId
WHERE
	games__.gameId IS NULL;
```
### Actual Behavior
getting a mix of results, with summoners that has and has not games.

**Comment by markstory** [comment]
Have you tried using `matching()` and using an `IS NULL` condition? That seems to be what you're trying to do?

**Comment by Tzaoh** [comment]
Hi @markstory, I tried, but the joins are built with inners joins so cannot filter with NULLs values.

**Comment by jhli** [comment]
try leftJoinWith and IS NULL and explicilty go through the assoc table e.g Games ~> GamesSummoners ~> Summoners.

**Comment by jhli** [comment]
Also join IRC and maybe we can help out.

**Comment by Tzaoh** [comment]
Thanks for your interest @jhli, ok, I will connect on some minutes. Meanwhile can you give me an example of going explicity through the joint table? If I try leftJoinWith(jointTableName) it will say that they do not have relationship between them

**Comment by ionas** [comment]
HABTM should be underscore joined plural names in alphabetical order e.g. `games_summoners`. Yours is `summoners_games`.
Try this:
```php
$summoners = $this->Summoners->find()
    ->select(['Summoners.id'])
    ->leftJoinWith('SummonersGames')
    ->where(['SummonersGames.game_id IS NULL']);
```
If its not available you may need to set a `hasMany` assoc.

**Comment by Tzaoh** [comment]
hi @ionas :) 

I am not following the conventions so I specified `summoners_games` with extra options in the relationship. I think is not about how the relationship is done but that I am unable to create the correct query (maybe because of my own fault).

I know I could make the plain SQL or change the relationship, but I think/guess that it should be possible to generate that SQL (which i think is a common case) with the BTM relation instead of modify to hasMany.

**Comment by Tzaoh** [comment]
As @ionas recommended I tried adding and extra hasMany relation between Summoner and the joinTable (SummonersGames) and that worked like a charmp.
Nevertheless i think this workaround shouldnt be needed.

I think I should be able to apply conditions to any of the tables (the target or the joint).
This case is not the only sharp border I found. If I want to select only some fields of the joint table or even if this joint table is associated with other tables I will have difficulties.

At least this 3 cases can be resolved at the moment with the workaround described by @ionas.
THANK YOU MATE :D

**Comment by ionas** [comment]
@Tzaoh like suggested on IRC you might want to check the book and if its not explained well enough add a docs example and close this issue or specify how and what exact magic you expect to see happening.
http://book.cakephp.org/3.0/en/orm/associations.html
http://book.cakephp.org/3.0/en/orm/associations.html#using-the-through-option
