### ISSUE TITLE
marshal() for integer type on empty values results in not dirty fields on add- action

### ISSUE THREAD

**Issue by bpanet** [cakephp/cakephp#8971]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10

# Behavior
If we allow empty on a integer foreign key input field with `NOT NULL` in database and want to check with ExistsIn rule if the given value exists in database and is not empty, the marshal for IntegerType returns null for this empty value.
The input field is not marked as dirty if the entity is new, because the value from the entity is `null` (because it is not set yet) and the value from the form is `null`, too.
Because of this behavior, no errors are shown and the entity is saved in database with the invalid value `0`.

Only method to prevent this, is adding the foreign key field to the validation and defines that the value does not have empty values or set `empty` for input field to `[ 0 => '' ]`.
```php
$validator
            ->notEmpty('store_id');
```

## Example code to reproduce this behavior:
in Template:
```php
<?= $this->Form->input('store_id', ['label' => __('Kaufort'), 'empty' => true]); ?>
```

in Table::buildRules():
```php
$rules->add($rules->existsIn(['store_id'], 'Stores'));
```

**Comment by markstory** [comment]
It sounds like you have figured out a way to get the behavior you're looking for. What kind of changes are you expecting to be made in CakePHP?

**Comment by bpanet** [comment]
Hi,

I think this behavior is not correct. This behavior does not apply for associations:

```php
<?= $this->Form->input('subjects.0.product_id', ['label' => __('Artikel'), 'empty' => true]); ?>
```
For this code the `product_id` field is dirty and the existsin rule returns a error for this field.
Why does this not apply for the main entity?

I think that all fields should always be dirty for new entities.

**Comment by markstory** [comment]
I don't see why adding the `notEmpty()` validation rule isn't acceptable. It sounds like what you're aiming to do is prevent null values, which a validation rule will do.
