### ISSUE TITLE
Trying out Nitpicking CI?

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#8972]
This issue is dedicated to @ADmad  :heart: 

In https://github.com/cakephp/cakephp/pull/8954 we added configuration for integrating the [Stickler CI](https://stickler-ci.com/).

Aparently there is a need for a CS checking CI.
May be it's a good time to compare Stickler CI with other solutions.

https://nitpick-ci.com/

I have no experience with the Nitpicking CI, but may be it makes sense to integrate both of them side by side for some time for better comparison and then decide on one of them.

**Comment by markstory** [comment]
It only checks PSR2 which is a limitation. Also I run stickler-ci so I'm quite biased :smile:

**Comment by ravage84** [comment]
I see, Nitpicking CI could only become an interesting solution to us, if this limitation goes away.
Then, still, it would have to face @markstory's bias :smirk_cat:

**Comment by markstory** [comment]
@ravage84 My plan for stickler-ci is to make it useful for the community for more than just PHP projects. All of the PHP projects I work on also involve CSS and JS which to me makes narrowly scoped services like nitpick less attractive.

**Comment by ADmad** [comment]
Thanks @ravage84. Hopefully your future dedications will be more well researched and fruitful :)
