### ISSUE TITLE
JWTAuth

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/cakephp#8973]
It is possible to implement "native" JWT factor authentication without the need for plugins?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by alexsmonte** [comment]
It was never my intention.
The idea was to propose an improvement to add JWT as an option for authentication.

**Comment by ADmad** [comment]
Your post was in form of a comment not a suggestion :)

JWT based authentication can work just fine through a plugin so there's no need to have it in core itself. We try to keep the core lean for efficiency and easier management.
