### ISSUE TITLE
Add `limit` support for `contain` 

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8974]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I came into the use case where I need to fetch only the most recent user activities into User entity. If `contain` supports custom `conditions` to filter associated data as well as `sort`, IMHO logical followup would be to support `limit` as well. So if `User hasMany UserActionLogs` following snipped would come in handy in my situation:
```
    public function short(User $user, $count = 25)
    {
        $this->loadModel("Users")->loadInto($user,
            ["UserActionLogs" =>
                ["sort" =>
                    ["id" => "DESC"],
                    "limit" => $count
                ]]);

        $this->set("user", $user);
    }
```

Right now it yelds:
`UserActionsCell::__toString() must not throw an exception, caught Error: Unsupported operand types` exception.

**Comment by Antoniossss** [comment]
And i just bumped onto http://stackoverflow.com/questions/29775766/using-limit-on-contained-model Jose Lorenzo's answer on SO. So this is possible via conditions, but limit would be handy shortcut.

**Comment by ionas** [comment]
Ref https://github.com/cakephp/cakephp/issues/8060

**Comment by markstory** [comment]
Closing as a duplicate.
