### ISSUE TITLE
Content Bug @ Disabling Deprecation Warnings

### ISSUE THREAD

**Issue by nareshkumarreddy** [cakephp/cakephp#8981]
While reading cake documentation, i came across one statement in the below URL

http://book.cakephp.org/3.0/en/appendices/3-2-migration-guide.html

Disabling Deprecation Warnings

Upon upgrading you may encounter several deprecation warnings. These warnings are emitted by methods, options and functionality that will be removed in CakePHP 4.x, but will continue to exist throughout the lifetime of 3.x. While we recommend addressing deprecation issues as they are encountered, that is not always possible. If you’d like to defer fixing deprecation notices, you can disable them in your config/app.php:

'Error' => [
    'errorLevel' => E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED,
]
----------------------------------In the above content error handling location path is wrong--------

please double check weather it is core.php or app.php ?

**Comment by jhli** [comment]
It is app.php as vore.php does not exist anymore in 3.x.

However, now that there is Application.php maybe it should be config.php ;)

**Comment by markstory** [comment]
It is `config/app.php` as the doc mentions.
