### ISSUE TITLE
Unit tests: MissingViewException when POST to json page

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#8984]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4
* Platform and Target: Linux, MySQL, PHP 5.5.9.

### What you did
Stripped version of my unit test method:
```
    public function testAddPost() {
		$expected = '{... some json ...}';
		$url = Router::url(array(
			'controller' => 'my_controller',
			'action' => 'add',
			'ext' => 'json',
		));
		$options = array(
			'return' => 'contents',
			'method' => 'POST',
			'data' => array(... some parameters ...)
		);
		$result = $this->testAction($url, $options);
		$this->assertJsonStringEqualsJsonString($expected, $result);
	}
```

### Expected Behavior
Passed test.

### Actual Behavior
MissingViewException:
```
1) MyControllerTest::testAddPost
MissingViewException: View file "My/json/add.ctp" is missing.

/path-to-cake/Cake/View/View.php:1031
/path-to-cake/Cake/View/JsonView.php:107
/path-to-cake/Cake/Controller/Controller.php:963
/path-to-cake/Cake/Routing/Dispatcher.php:200
/path-to-cake/Cake/Routing/Dispatcher.php:167
/path-to-cake/Cake/TestSuite/ControllerTestCase.php:287
/path-to-cake/Cake/TestSuite/ControllerTestCase.php:199
/path-to-app/app/Test/Case/Controller/MyControllerTest.php:192
/path-to-app/app/Test/Case/Controller/MyControllerTest.php:192
/path-to-cake/Cake/TestSuite/CakeTestCase.php:82
/path-to-cake/Cake/TestSuite/CakeTestRunner.php:62
/path-to-cake/Cake/TestSuite/CakeTestSuiteCommand.php:98
/path-to-cake/Cake/Console/Command/TestShell.php:275
/path-to-cake/Cake/Console/Command/TestShell.php:318
/path-to-cake/Cake/Console/Command/TestShell.php:257
/path-to-cake/Cake/Console/Shell.php:461
/path-to-cake/Cake/Console/ShellDispatcher.php:212
/path-to-cake/Cake/Console/ShellDispatcher.php:66
```

Although the same test with `'method' => 'GET'` acts as expected, no exceptions. I do not have My/json/add.ctp file.

**Comment by markstory** [comment]
How can someone reproduce this situation? Are you using RequestHandlerComponent? Do you have any beforeFilter callbacks that contain relevant logic?

**Comment by bancer** [comment]
Yes, we use RequestHandlerComponent. JSON page is rendered properly in the browser. There is no logic related to JSON views in beforeFilter callback.

**Comment by markstory** [comment]
OK, I'll see if I can reproduce in a test app.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. I've [made a gist of the files I used](https://gist.github.com/markstory/009640880a13c71d9d27df1f4441ea39). The test does not fail with a missing view error as you described. I'm going to need some more help on how to reproduce the error you're seeing.

**Comment by dereuromark** [comment]
I also had this issue a few times in the past in 2.x, probably starting at 2.6 or sth around that.
Suddenly my production systems were failing after upgrading as it now required the json subfolder where it didnt before. So something in the requesthandler class must have changed.
And the weird thing locally was: There it was fine. So it must be related to what headers are being processed etc.

**Comment by markstory** [comment]
ping

**Comment by markstory** [comment]
Closing as I don't have a way to reproduce this issue. If someone can provide a way to reproduce this issue, or provide a patch and test that fixes the observed problems I'd be happy to reopen.

**Comment by MikeOtown** [comment]
I am getting the same issue, but it is also happening in the browser (GET).  For some reason it is looking for a "json" folder when my action ends with .json.

**Comment by markstory** [comment]
@MikeOtown If you could reproduce this issue would you be able to help with getting a fix created?

**Comment by MikeOtown** [comment]
Well, I think the issue can be resolved by using JsonView and by calling $this->ok(); in the action.  The search for the view in the "json" folder (in my case at least) only happened when an error occurred and my action didn't call ok().  Once I resolved the upstream error, the MissingViewException error went away.

**Comment by bancer** [comment]
> For some reason it is looking for a "json" folder when my action ends with .json.

I experienced this in GET requests when $_serialize was not set. The fix for that was:
```
$_serialize = array('someVariable');
$this->set(compact('someVariable', '_serialize'));
```
