### ISSUE TITLE
How to implement Queue in cakephp 1.3

### ISSUE THREAD

**Issue by sandyrewa** [cakephp/cakephp#8990]
I'm using cakephp 1.3, i have lots of corns and some times most of crons are break, now i want to use queue in place of cronjob. I have research many things and found some links, i'm using "https://github.com/davidpersson/queue" for queue i have installed this code but i don't know how can i implements this?

**Comment by dakota** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
