### ISSUE TITLE
Add existsIn rule with "errorField" option duplicates the error

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#8993]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10.

### What you did
In my table, if defined the following rule (in that `buildRules` method).

    $rules->add($rules->existsIn(['parent_source', 'parent_code'], 'ParentFacts'));

it generates the error:

    [
        'parent_source' => ['_existsIn' => 'This value does not exist']
    ]

That is correct.
But if it try to use that errorField option:

    $rules->add($rules->existsIn(['parent_source', 'parent_code'], 'ParentFacts'), '_existsIn',
        ['errorField' => 'parent_key', 'message' => 'This value does not exist']);

### Expected Behavior
    [
        'parent_key' => ['_existsIn' => 'This value does not exist']
    ]

### Actual Behavior
    [
        'parent_key' => ['_existsIn' => 'This value does not exist'],
        'parent_source' => ['_existsIn' => 'This value does not exist']
    ]

Reading the [source code](https://github.com/cakephp/cakephp/blob/master/src/ORM/RulesChecker.php#L91) we can see that this isn't really a bug, but i don't know, the actual behavior is strange, so i'm opening the issue so you guys can check it too.

**Comment by markstory** [comment]
I think you might also find that the rule is added/invoked twice. I ran across this once, but thought I must have done something wrong. In either case what you're expecting is what I think the behavior should be as well.

**Comment by alysson-azevedo** [comment]
Yeah, invoking it twice is really a problem. I not really sure how to fix it, but if it isn't, then it should not be used.

**Comment by markstory** [comment]
Pull request open now.
