### ISSUE TITLE
Add new method to table for findAndUpdate()

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8996]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: MySQL, PHP7

### What you did

Added a method that performs a find and update inside a transaction. Was wondering if anyone would like this added as a core feature for tables.

```
    /**
     * Finds a record and updates it using a transaction so that there are no collisions.
     *
     * @param array|callable $cond Array of conditions, or a function that takes the query.
     * @param array|callable $update Array of values to patch or a callback.
     * @return Entity
     */
    public function findAndUpdate($cond, $update)
    {
        return $this->connection()->transactional(function () use ($cond, $update) {
            $query = $this->find();
            if (is_callable($cond)) {
                call_user_func($cond, $query);
            } else {
                $query->where($cond);
            }
            $record = $query->first();
            if ($record) {
                if (is_array($update)) {
                    $this->patchEntity($record, $update);
                } else if(is_callable($update)) {
                    call_user_func($update, $record);
                }
                return $this->save($record);
            }
            return false;
        });
    }
```

If you google for `mysql select and update` there are a lot of hits of people asking how to do this as one transaction. So I think there would be a demand for this feature among Cake users.

**Comment by Xymanek** [comment]
Looks like a good idea to me, just today coded my own version of this :stuck_out_tongue_closed_eyes: . Some things that come to my mind: 

* No need to use `call_user_func($cond, $query);`, you can just do `$cond($query);`
* In my case (what I made today) I needed to persist a row to database but I don't know if it already exists or not. Therefore how about adding a third option `$create = false` which in case the row couldn't be found will create a new one and save it
* In most docblocks I've seen in cake, the type hint is `\Cake\Datasource\EntityInterface` (note that it's fully name spaced)
* The return type of ``Table::save()` is `\Cake\Datasource\EntityInterface|bool`, since you are returning results from there, it's it a good idea to keep the same type hint?

**Comment by ionas** [comment]
What happens if `patchEntity()` fails due to validation errors?

**Comment by thinkingmedia** [comment]
@ionas $this->save() will fail, and return false triggering the transaction to rollback.

This should be correct behavior.

**Comment by markstory** [comment]
How do people configure the additional options for `patchEntity()`?

**Comment by thinkingmedia** [comment]
@markstory use the callback variant for the update parameter.

Could add another options parameter, but then people would complain they can't configure the find. So I figure callables are the answer.

**Comment by chinpei215** [comment]
@thinkingmedia I think @ionas is talking about how to handle errors. Wouldn't the method return `false` in both cases of "record not found" and "validation error"? Do they need to handle errors like the following?
```php
$entity = $this->Articles->findAndUpdate($cond, $update);
if ($entity === false) {
    $entity = $this->Articles->find()->where($cond)->first();
    if ( $entity === false) {
        // Handles record not found
    } else {
        $this->Articles->patchEntity($entity, $code);
        // Handles validation errors
    }

    // No way to handle application errors?
}
```

Aside from that, `findFirstAndUpdate` would be a more suitable name for the method. Even if there are two ore more hits for the search conditions, only the first one will be updated.

**Comment by thinkingmedia** [comment]
I've been doing a lot of work on distributed cloud computing with CakePHP related, and want to warn that a `findAndUpdate` function would be very problematic.

Unless you issue a full table LOCK (for MySQL) there will be unexpected side effects, and once you go down the table locking route there are performance issues, and once you lock one table you have lock another table, and so on. It's a real pain.

Much of my problems are now avoid by not using a `findAndUpdate` function. To prevent issues with multiple DB connections. The preferred approach is to perform an `UPDATE` first, and then `SELECT` what was updated.

For example, if I was to have a PHP process that needed to process each record. Normally, you would `SELECT` the record to be worked on and then `UPDATE` with the changed. That is when you would use a `findAndUpdate`. This works fine for a single thread.

If you have multiple threads, you need to `UPDATE * LIMIT 1` to mark a record as busy, then `SELECT` and `UPDATE` to finalize the work on that record. This will prevent the need to do a table level lock.

I thought if I used the `SELECT FOR UPDATE` in my `findAndUpdate` function that this would fix that, but after much research it turns out that MySQL uses a write queue at a per record level, and when a transaction uses `SELECT FOR UPDATE` that record can be selected by multiple threads. Even if the update changes the record values once the write queue is made that record will be selected by the other threads (once the write is released) even if the conditions no longer match.

So what I do now is use a worker ID value, and perform a `UPDATE` to set that ID and then select that ID. This prevents multiple threads from working on the same record, and drops the need to table level locking.
