### ISSUE TITLE
Transactions not rolled back when fatal errors are thrown in PHP7

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#8997]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: MySQL, PHP7, Apache 2.4

### What you did

Used transactional so that errors would trigger a rollback.

### Expected Behavior

Callback function can throw an error that triggers the rollback.

### Actual Behavior

Callback throws an error, but transaction does not rollback. Execution block is escaped, and the transaction is not closed.

The following is a catchable error.

```
    try {
        $foo = array();
        $this->$foo(); // $foo is not a string.
   } catch(Error $er) {
         // catches error "Function name must be a string"
         Log::error($er->getMessage());
   }
```

What happen to me today.

```
      try {
           // bla bla bla...
           $this->connection()->transactional(function() use ($foo) {
                     $this->$foo(); // throws error
           });
     } finally {
           $this->LogTable->save($record);
           // the above is still inside a transaction. Transactional never rollback or commit.
     }
```

The issue exists here in the code for `Connection.php`

```
    public function transactional(callable $callback)
    {
        $this->begin();

        try {
            $result = $callback($this);
        } catch (Exception $e) {
            $this->rollback();
            throw $e;
        }

        if ($result === false) {
            $this->rollback();
            return false;
        }

        $this->commit();
        return $result;
    }
```

The problem is in the `catch(Exception $e)`, as it should be `catch(Throwable $e)`. The catch can be changed to fix the issue, but I don't like using `catch` unless it actually handles the error.

How about something like this?

```
    public function transactional(callable $callback)
    {
        $this->begin();

        $result = false;
        try {
            $result = $callback($this);
        } finally {
            if($result === false) {
                $this->rollback();
            } else {
                $this->commit();
            }
        }
        
        return $result;
    }
```

I think the above is easier to maintain and avoids the confusion between Exceptions and Throwables.

> note: catch(Exception $e) exists in a number of places in the code.

**Comment by thinkingmedia** [comment]
Can I make a PR to fix this?

**Comment by thinkingmedia** [comment]
I fixed my issue by adding a temp function to convert Error objects to Exception.

```
    public function transactional($callable)
    {
        return $this->connection()->transactional(function ($con) use ($callable) {
            try {
                return call_user_func($callable, $con);
            } catch (\Error $error) {
                throw new \Exception($error->getMessage());
            }
        });
    }
```

**Comment by markstory** [comment]
Yes PHP7 Errors would not be handled by the existing code. Using `Throwable` could work if we repeated the catch blocks. A `finally` sounds like a better option though.

**Comment by thinkingmedia** [comment]
@markstory I didn't know Errors were a new thing. I just assume it was always like that.

**Comment by markstory** [comment]
Yes, all the Error classes are new as of PHP7. Previously, those situations emitted a 'catchable fatal error'.

**Comment by lorenzo** [comment]
I was thinking a bit about this... is it actually a problem for you? PHP should close the connection when the fatal error occurs, which is the same as a rollback.

**Comment by thinkingmedia** [comment]
@lorenzo Not if you catch the fatal errors.

I was (and maybe I shouldn't be) do this

```
    try {
         // do work that starts a transaction...
   } catch( \Throwable $ex) {
       Log::error($ex->getMessage());
  }
  // continue with other work
```

I have CLI scripts that run CakePHP shells. Those shells call worker classes and I was wrapping that worker in the above safety catch. As a result, the transactions were left open when the next worker started.

Now that I better understand the new `Error` class in PHP 7. I'm not sure I should ever catch it. I might still catch it so that I can log it (my logs are in a database not the console IO), then the PHP thread should exit.

As for how this should work in a web server with PHP. I think a `try/finally` block would be better, but I've already tried to get a pull request for that working. It works find in PHP 7 but not in PHP 5.6

**Comment by lorenzo** [comment]
fair enough, I understand why it is important to always rollback
