### ISSUE TITLE
AuthComponent ajaxLogin element

### ISSUE THREAD

**Issue by ghlnv** [cakephp/cakephp#8999]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: Ubuntu/OSX, MySQL, jQuery.

### What you did
I tried to access an ajax url after my session expires. A Forbidden response was received even though I setting ajaxLogin to an Element file.

### Expected Behavior
I expected that Element file was rendered.

### Actual Behavior
A Forbidden response was received.
I suspect the line 380 of AuthComponent needs to be removed.
x [ $response->statusCode(403); ]

**Comment by markstory** [comment]
No that code needs to be there, the lines directly above that render the ajaxLogin element into the response.

**Comment by markstory** [comment]
How can someone reproduce the issue you're seeing? For me the forbidden response contains the rendered element.

**Comment by ghlnv** [comment]
App\Controller\AppController

```
$this->loadComponent('Auth', [
	'authorize' => 'Controller',
	...
	'ajaxLogin' => 'ajaxLogin',
]);
```


App\Template\Element\ajax_login.ctp

```
<?php
debug('hello');
```


I open an ajax sidepanel with following code:
```
$(document.body).on("click", ".data-sidepanel", function(ev){
	ev.preventDefault();
	...
	$.ajax({
		url: $(this).attr("href")
	})
	.done(function(data) {
		$("#js-sidepanel-contents").scrollTop(0).html(data);
	})
	.error(function(xhr, status, error) {
		// debug
		alert(error);
	});
});
```

If I open an sidepanel after logout in another browser tab, the server answer is Forbidden (403), and not rendered the 'hello' debug.

**Comment by markstory** [comment]
Yes `error` will be 'Forbidden' in that case. What you want is `xhr.responseText` which contains the contents of your rendered element.
