### ISSUE TITLE
Save hasMany association with association conditions using replace strategy

### ISSUE THREAD

**Issue by lbvnieuw** [cakephp/cakephp#9004]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10

### What you did
I'm using a single table for multiple entity translations (using the default cakephp TranslateBehavior).
BlogCategories:
```php
        $this->addBehavior('Translate', [
            'fields' => ['title', 'slug'],
            'translationTable' => 'BlogTranslations'
        ]);
```
BlogPosts:
```php
        $this->addBehavior('Translate', [
            'fields' => ['title', 'slug', 'body', 'summary'],
            'translationTable' => 'BlogTranslations'
        ]);
```

### Expected Behavior
The translate behavior makes a hasMany association between the source table and the translations table with an extra condition on the source model. When looking up a specific BlogPost, that extra condition make sure you'll get the translations of a BlogPost with foreign key 1 and not the translations of a BlogCategory with foreign key one. When saving that BlogPost with id 1 (using the default save strategy for the translation association: replace), all the BlogPost translations with foreign key 1 not in the supplied BlogPost data, should be deleted. 

### Actual Behavior
When saving the BlogPost all translations in the blog_translations table with foreign key 1 are deleted, also the translations of the BlogCategory with id 1. The protected method _unlinkAssociated in the hasMany association doesn't use the association conditions.

**Comment by markstory** [comment]
Does this issue happen if you use the default setting and don't customize the `translationTable`?

**Comment by lbvnieuw** [comment]
Yes using the default translationTable causes the same problem. Are you sure this is a translateBehavior problem en not an hasMany association problem?

**Comment by markstory** [comment]
@lbvnieuw Where is the replace strategy being set? That's not in any of the code you've provided so far, and the TranslateBehavior doesn't configure the `saveStrategy` to `replace` either.

**Comment by markstory** [comment]
ping

**Comment by markstory** [comment]
Closed for lack of activity. If you have time to provide more information, we'd be happy to look at this issue more.

**Comment by lbvnieuw** [comment]
Sorry I've not responded earlier. While making another HasMany association with conditions (normal, no behaviors used) I seem to have the same problem. 

**First association using the database table comments (an assoication for BlogPostsTable)**
`$this->hasMany('Comments', [
            'className' => App::className('Blog.BlogPostCommentsTable', 'Model/Table'),
            'foreignKey' => 'foreign_key',
            'conditions' => [
                'Comments.model' => 'BlogPosts'
            ],
            'saveStrategy' => 'replace',
            'dependent' => true
        ]);`

**Second association using the database table comments (an assoication for RealisationsTable)**
`$this->hasMany('Comments', [
            'className' => App::className('Realisations.RealisationCommentsTable', 'Model/Table'),
            'foreignKey' => 'foreign_key',
            'conditions' => [
                'Comments.model' => 'Realisations'
            ],
            'saveStrategy' => 'replace',
            'dependent' => true
        ]);`

So if you have a Realisatons with id 1 and a BlogPost with id 1, saving one of those 2 will cause a removal of the comments of the other one. So the ` 'conditions' => [
                'Comments.model' => 'Realisations'
            ],`
and ` 'conditions' => [
                'Comments.model' => 'BlogPosts'
            ],` of the association declaration are not used in the save method with replace strategy

**Comment by markstory** [comment]
Your associations will need to have unique aliases.

**Comment by lbvnieuw** [comment]
Sorry but using BlogPostComments or RealisationComments as aliases didn't help. I've been looking to the code of the hasMany association and in the _unlinkAssociated function, the passed condition is only the foreignKey (line 412 /ORM/Associations/HasMany.php). Nowhere the conditions of the associations are passed ($this->_conditions). Am I doing something wrong or could this be a bug?

**Comment by ndm2** [comment]
The association conditions are being applied when `$this->find()` is invoked

* **https://github.com/cakephp/cakephp/blob/3.3.2/src/ORM/Association/HasMany.php#L452**
* **https://github.com/cakephp/cakephp/blob/3.3.2/src/ORM/Association.php#L684**

However this will only happen when `dependent` as well as `cascadeCallbacks` are enabled (the latter is missing in your example). I'd say that this is a bug, the `deleteAll()` and `updateAll()` calls should merge in `$this->conditions()`

* **https://github.com/cakephp/cakephp/blob/3.3.2/src/ORM/Association/HasMany.php#L461**
* **https://github.com/cakephp/cakephp/blob/3.3.2/src/ORM/Association/HasMany.php#L467**

**Comment by guanchor** [comment]
Hello,

I have the same problem:

- CakePHP v3.3.2

**\App\Model\Table\InvoicesTable::initialize()**

```
...
$this->hasMany('ServiceConcepts', [
    'className' => 'Concepts',
    'foreignKey' => 'invoice_id',
    'conditions' => ['ServiceConcepts.service_id IS NOT NULL'],
    'saveStrategy' => \Cake\ORM\Association\HasMany::SAVE_REPLACE,
    //'dependent' => false, // nullable
]);
$this->hasMany('CustomConcepts', [
    'className' => 'Concepts',
    'foreignKey' => 'invoice_id',
    'conditions' => ['CustomConcepts.service_id IS NULL'],
    'saveStrategy' => \Cake\ORM\Association\HasMany::SAVE_REPLACE,
    'dependent' => true, // will be removed
]);
...
```

I update the relationship in the same form through this 2 associations. But when Cake updates the DB rows, actions over each one affects the other because the associations `conditions` are not checked in the saving process.

Then I have added this change and looks fine for me:

**\Cake\ORM\Association\HasMany::_unlink() [L444-454]**

```
$_conditions = (new Collection($this->conditions()))
    ->map( function($condition,$index) {
        if (strpos($condition,'.') !== FALSE) {
            return explode('.',$condition)[1];
        }
        return $condition;
    })
    ->toArray()
;
$conditions = array_merge($_conditions,$conditions);

```

What do you think? I've started on changes of the pull (https://github.com/cakephp/cakephp/pull/9404) request but with the alias name removing (ugly removing for now).

I think this will be happen in the same case when using BelongsToMany.
