### ISSUE TITLE
Table::findOrCreate should be done as a transaction

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9006]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: MySQL, PHP7, Windows

### Actual Behavior

The method `findOrCreate` should be transactional to ensure database state is represented correctly. Without a transaction it's possible under heavy load for this to create duplicates.

Proposed change:

```
    public function findOrCreate($search, callable $callback = null)
    {
        return $this->connection()->transactional(function() use($search, $callback) {
            $query = $this->find()->where($search);
            $row = $query->first();
            if ($row) {
                return $row;
            }
            $entity = $this->newEntity();
            $entity->set($search, ['guard' => false]);
            if ($callback) {
                $callback($entity);
            }
            return $this->save($entity) ?: $entity;
        });
    }
```

**Comment by jhli** [comment]
:+1:

**Comment by markstory** [comment]
Closing as there is a pull request open now.
