### ISSUE TITLE
Mute codecov commenting

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9013]
Highly annoying and without benefit (the failing or green icon should be enough).

Do we really need sth like https://github.com/briannesbitt/Carbon/pull/677/files ?
Or is there a setting of some sort to silence the comments?

**Comment by markstory** [comment]
I don't find the comments too noisy, but I'm well past the days of github emails being useful.

**Comment by ravage84** [comment]
:+1: agree, as commented before.

**Comment by jeremyharris** [comment]
I personally like the comment. It's a nice reinforcement and it's not too noisy for my taste.

**Comment by ADmad** [comment]
I too don't think one comment per PR from codecov is noisy.
