### ISSUE TITLE
DboSource: Logging of query time and numRows in tests

### ISSUE THREAD

**Issue by Mensler** [cakephp/cakephp#9014]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.11
* Platform and Target: Apache, MySQL, PHPUnit tests

### What you did
Running PHPUnit tests and debugging performance problems with MySQL/creating fixtures.

### Expected Behavior
When setting debug=2, I want to see the correct sum of query execution time in the query log at the end of the page.

### Actual Behavior
First: I know the logging is disabled for CREATE, DROP and TRUNCATE TABLE statements, so their execution times are not added. Changing this is not part of this issue, but it could be an idea to make this configurable.

The problem is that $this->took is not reset before BEGIN/COMMIT/ROLLBACK and in insertMulti(), so the last execution time is always summed up.

I fixed this in the attached patch:
[DboSource.patch.txt](https://github.com/cakephp/cakephp/files/325906/DboSource.patch.txt)

**Comment by markstory** [comment]
Thanks for the patch. Applied in 92a50d05dcd820434e0799d9c22beb823a590bf1
