### ISSUE TITLE
CakeFixtureManager: Truncate tables only if not dropped

### ISSUE THREAD

**Issue by Mensler** [cakephp/cakephp#9015]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.11
* Platform and Target: Apache, MySQL, PHPUnit tests

### What you did
Running PHPUnit tests and debugging performance problems with MySQL/creating fixtures.

### Expected Behavior
Either drop and create fixture tables before each test or create it once and truncate it afterwards.

### Actual Behavior
Many unnecessary TRUNCATE statements slow down tests. I think truncate is only needed if the tables are not dropped. Additionally I added an array_unique() to eliminate duplicate fixtures:
[CakeFixtureManager.patch.txt](https://github.com/cakephp/cakephp/files/325976/CakeFixtureManager.patch.txt)

### See also
#9014, #8652

**Comment by dereuromark** [comment]
Instead of patches, providing it as PR would really speed up discussion and merging of possible fixes.

**Comment by markstory** [comment]
Closing as the patch is now a pull request.
