### ISSUE TITLE
[3.1] plugin join tables not using custom datasource

### ISSUE THREAD

**Issue by vorien** [cakephp/cakephp#9016]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Apache/MySQL called via http from multiple browsers.

The long version can be found at: [http://stackoverflow.com/questions/37888018](http://stackoverflow.com/questions/37888018/cakephp-3-1-plugin-join-tables-not-using-custom-datasource
)
### What you did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

I set up a plugin based datasource:

plugins/Vorien/NPCData/config/app.php:
```
return [
    'Datasources' => [
        'npcdata' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => 'localhost',
            'username' => 'npcdata',
            'password' => '********',
            'database' => 'npcdata',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => true,
            'url' => env('DATABASE_URL', null),
        ],
    ],
];
```

plugins/Vorien/NPCData/config/bootstrap.php:
```
try {
    Configure::config('npcdata', new PhpConfig(Plugin::path('Vorien/NPCData') . 'config/'));
    Configure::load('app', 'npcdata');
    ConnectionManager::config(Configure::consume('Datasources'));
} catch (\Exception $e) {
    exit($e->getMessage() . "\n");
}
```

I used bake to create everything with the parameters:
```
-p Vorien/NPCData -c npcdata
```

My Table files have:
```
public static function defaultConnectionName()
{
    return 'npcdata';
}
```
### Expected Behavior

Running a hasOne or hasMany:
```
$persona = $this->Personas->get($id, [
    'contain' => ['People']
]);
```
Returns a result set.

When I try to run anything with a HABTM:
```
$persona = $this->Personas->get($id, [
    'contain' => ['Archetypes']
]);
```
I expect the same thing.

### Actual Behavior

When I run a get with a HABTM join I get an error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testcake3.archetypes_personas' doesn't exist.

testcake3 is the default database.

When I set the default database to npcdata (the table used by the plugin) it works properly.

**Comment by lorenzo** [comment]
Can you show the configuration for your associations?

Please keep in mind that cake 3.1 is not able to do cross database joins by default. Is this your case? Are you expecting cake to join tables from 2 different databases?

**Comment by vorien** [comment]
I've attached my Model/Table files.

I'm not doing any cross-database joins in this instance.  Everything is between those three tables in the same database.

The problem occurs if I use any HABTM joins, not just this specific instance.







[Table.zip](https://github.com/cakephp/cakephp/files/326671/Table.zip)

**Comment by vorien** [comment]
[DebugOutput.zip](https://github.com/cakephp/cakephp/files/326741/DebugOutput.zip)

Here's an exploded debug output.  I don't know if it will help, but I've been trying to backtrack to the point where the code starts using the default configuration instead of the plugin.

**Comment by markstory** [comment]
I suspect that the generated junctionTable Table instance is a generated instance and not using a concrete class defined in your plugin. You should try defining the `through` option with a concrete table class name.

As a more permanent fix, the generated junction table should probably use the connectionName of the current table object.

**Comment by markstory** [comment]
Pull request up #9018.

**Comment by vorien** [comment]
I've tried both using the 'through' option instead of 'joinTable' and manually applied your patch to _src/ORM/Association/BelongsToMany.php _ (#9018), but I still have the same error.  It's still trying to use the default connection and the DebugKit Sql Log has:

> Generated Models
> The following Table objects used Cake\ORM\Table instead of a concrete class:
> archetypes_personas

as before.

I'll keep digging myself, but I'd like to reopen this issue.

**Comment by markstory** [comment]
Do the modified lines of code get run on in your case? If so, is the source() table's connection correct? How did you define the 'through' option?

**Comment by vorien** [comment]
I did some debugging.  If I leave them as joinTables, they go through your code and it works.  But using 'through' doesn't work.  The problem is that $tableLocator doesn't include the join tables.  I'm thinking that's why I get the DebugKit Sql Log error.

**Comment by vorien** [comment]
Is there an equivalent of "TableLocator" for HABTM tables?  I couldn't find anything like that.  Without either an equivalent or adding those tables to TableLocator, there wouldn't be any way to get the proper settings for the HABTM join tables. I don't know the codebase, but it seems like you'd want to use the Table file configuration directly.

**Comment by lorenzo** [comment]
There is `TableRegistry::config('TheTableAlias', [list of configuration keys])`
For example `TableRegistry::config('PostsTags', ['connection' => $connectionObject])`

Closing as the related pull request was merged and there are several ways of configuring the junction table correctly.

If you have further questions please join us on IRC or the slack channel

**Comment by vorien** [comment]
That didn't fix the problem if the "through" option is used.  It only patched using the "joinTable" option.

**Comment by lorenzo** [comment]
You need to make sure your table in through has the defaultConnection configured correctly

**Comment by vorien** [comment]
It does.  I've traced the issue back to the fact that the join tables aren't initially loaded into tableLocator and that Cake\ORM\Association\BelongToMany:junction() isn't plugin aware.  I've opened a discussion on the forum to see if anyone has any more ideas.

**Comment by vorien** [comment]
Okay, I found the problem.  The 'through' table has to be prefixed with the plugin because it uses the object, but the joinTable uses the table, so it needs your patch.

However, by using the prefixed table object as the joinTable parameter, it works without the patch.

If that makes sense.

Is there a reason why the joinTable parameter shouldn't be the object?  If not, I'd like to override my bake to use the object instead so I only have to manually change the parameter and through will work properly.

**Comment by markstory** [comment]
> Is there a reason why the joinTable parameter shouldn't be the object?

Generally that should be safe, as the BelongsToMany association camelizes the table name into the class/alias name.

If a developer defines `through` we assume they have defined the concrete class, whereas `joinTable` indicates that the class might not exist and that a generated table is ok.

**Comment by vorien** [comment]
Okay, -that- makes perfect sense.  I'm used to just baking everything, but that does add a lot of unnecessary code.

Well, Lorenzo patched the issue with using only the table name as the joinTable, so that's good to go.  I'll update my stackoverflow question in case other people have the same issue.

Thanks to both of you for all your help and patience.  :)
