### ISSUE TITLE
Cache a boolean value

### ISSUE THREAD

**Issue by manhg** [cakephp/cakephp#9020]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.11
* Platform and Target: General

### What you did

I tried to cache a boolean value using `Cache::remember`
### Expected Behavior

It should cache despite of value.

### Actual Behavior

When value is `false`, it doesn't cache.

**Comment by lorenzo** [comment]
No, that's unfortunately a limitation. Since, the false value is used to indicate that there was no hit. I'm going to close this ticket because we cannot change that give the current API.

But whenever we adopt the PSR-6 recommendation, that will be possible.
