### ISSUE TITLE
Add validation features for validating non associative array

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#9023]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP version: 3.*

i found this issue in the following situation.
i have created a modeless form. the data from the form must have this schema.

```
[
 'tel' => '000000',
 'type' => [
    'foo',
   'lol',
    'asd'
 ]
]
```

the form is created dynamically and each type entry is a text field, so every input is created with the name = 'type.0' , 'type.1', ecc

i need that if the field for the type has been created by the user, validation force the user to fill it and check the maximum size.

validation now, cannot check every index of the array as a single field if i don't set a key.

validation should be allow to set a nested validator and set a rule like ->add('.', 'rulename', .....)
so the error message will be set for each different input

**Comment by markstory** [comment]
Couldn't you write a custom validator for the `type` field and validate each item in the list inside your function?

**Comment by doshu** [comment]
yes but if i write a custom validator, i cannot set a validation error for
each element of the erray and it will not work with the form helper
Il 23 Giu 2016 04:02, "Mark Story" <notifications@github.com> ha scritto:

**Comment by burzum** [comment]
@doshu I don't think this very specific use case belongs to the core but I can see the problem with the error messages per nested field.

Maybe you can use the nested validation functionality to get this done? See http://book.cakephp.org/3.0/en/core-libraries/validation.html#nesting-validators

**Comment by doshu** [comment]
nested validation cannot be setted for each element of an array. the nested
array must have a string key that identify the field.
a single array with elements with numeric keys must not nested validated

2016-06-30 12:02 GMT+02:00 Florian Krämer <notifications@github.com>:

**Comment by markstory** [comment]
The `isArray` validator proposed in #9057 seems related to this. We could look at having another rule to apply a rule to every element in a list value. Something like:

```php
$validator->allElementsMust(['lengthBetween', 1, 5], 'All things must be between 1-5', $options);
```

**Comment by thinkingmedia** [comment]
@markstory 

We will get stuck having to duplicate validation rules just for arrays.

What if we add support for `Hash::extract` as part of the fieldname, and then iterate the rule over what was extracted. This change only kicks in if `Validator` sees that a rule's field name looks like an extraction.

The usage would look like this.

```
  $validatior->integer('field.{n}.Foo.Bar');
  $validatior->requirePresence('field.{n}.Foo.Bar', 'create');
  $validatior->notEmpty('field.{n}.Foo.Bar');
```

I haven't looked at the impact of such a change, but I think it shouldn't be that hard to add. We also know that `Hash::extract` is stable so it should be risky to do this.

**Comment by markstory** [comment]
@thinkingmedia The method I proposed above would effectively do an array_map under the hood applying the provided validator to each element in the array. How does that create duplication?

**Comment by thinkingmedia** [comment]
I misread our issue. I thought you were adding lengthBetween support for arrays.

I think an array_map approach for validating is a good idea, but generally people want a schema validation. For example; 'field.{n}.name' should all be strings and not empty, and `'field.{n}.age' should be integer, etc.. etc..

**Comment by markstory** [comment]
@thinkingmedia But that *is* what nested validators are for. The original issue description mentioned

> i need that if the field for the type has been created by the user, validation force the user to fill it and check the maximum size.
> 
> validation now, cannot check every index of the array as a single field if i don't set a key.

And the example code made me think what was missing was the ability to map a validation across a list's elements.

**Comment by lyziane** [comment]
Is this going to happen? 
It happens every now and then that I need an array of values and would like to validate one (or more) values in my array. Instead of having to re-organise all my data, my form field could just use the right name. Example: A set of credit card info, I have to take the field "card_number" and then put it in my "card" array under the key "number" instead of just having the field called "card.number" which would do exactly that but I can't validate them...

**Comment by markstory** [comment]
@lyziane Have you looked at [nested validators](https://book.cakephp.org/3.0/en/core-libraries/validation.html#nesting-validators). The previous comments in this issue were for solving validation of multiple values in a list field. E.g ensuring that all elements in an array meet the required minimum length.
