### ISSUE TITLE
[2.8]  Trigger an event in CakeSessionHandlerInterface

### ISSUE THREAD

**Issue by rifton007** [cakephp/cakephp#9028]
Hi, 

Is it possible to trigger an event in CakeSessionHandlerInterface?
`

        App::uses('CakeEvent', 'Event');
        App::uses('DatabaseSession', 'Model/Datasource/Session');

        class CompositSession extends DatabaseSession implements CakeSessionHandlerInterface {
        public $cacheKey;

        public function write($id, $data) {
            Cache::write($id, $data, $this->cacheKey);
            $event = new CakeEvent('CompositSession.write', $this);
            $this->getEventManager()->dispatch($event);
            return parent::write($id, $data);
        }
    }
`

Thank you,

**Comment by markstory** [comment]
Yes, but you'd have to implement the necessary methods, as `DatabaseSession` doesn't provide `getEventManager` for you.

However, this is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
