### ISSUE TITLE
CakePHP 3 - read cookie problem

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#9029]
View element (test.ctp) calls the function "stepTwo":

```
<?php $test=$this->requestAction('/some_controller/stepTwo'); ?>
```

Function "stepTwo" looks like this:

>    public function stepTwo()
>    {
>    -----
>      echo $this->Cookie->read('testCookie');// This does not work. Value is always empty
>      echo $_COOKIE['testCookie']; //This works! Cookie is accessible.
>      $testCookie=$this->Cookie->read('testCookie');
> 
> 
>     if ($this->request->is('requested')){
>     $this->response->body($testCookie);
>     return $this->response;
>     }
> 
>    }
Unfortunately, the value of the $this->Cookie->read('testCookie') is always empty.  A cookie is readable only with $_COOKIE['testCookie']. WHY?

**Comment by markstory** [comment]
Because in your requestAction call you did not forward the cookies from the parent request. requestAction relies on you to create all of the request context.
