### ISSUE TITLE
Associated Delete in CakePHP 2.5.4

### ISSUE THREAD

**Issue by boxgames1** [cakephp/cakephp#9030]
Hi. 

I have 2 entities in the database Element and Section. 

1 section has 0-N elements so in the element table I have a foreign key 

    CONSTRAINT `elements_sections` FOREIGN KEY (`section_id`) REFERENCES `sections` (`id`) ON UPDATE CASCADE ON DELETE CASCADE

Element Model .php has this:

    public $belongsTo = array(
    		'Section' => array(
    			'className' => 'Section',
    			'foreignKey' => 'section_id',
    			'conditions' => '',
    			'fields' => '',
    			'order' => ''
    		)
    	);

In the Section model I have:

    public $hasMany = array(
    	'Element' => array(
    		'className' => 'Element',
    		'foreignKey' => 'section_id',
    		'dependent' => false,
    		'conditions' => '',
    		'fields' => '',
    		'order' => '',
    		'limit' => '',
    		'offset' => '',
    		'exclusive' => '',
    		'finderQuery' => '',
    		'counterQuery' => ''
    	)
    );

All this code looks good, however, when I delete an element of the section with ID=X, if there's an element (in any other section) with ID=X that element is deleted too. This is the code I am using in my whole aplication but only fails here. $this->data is the Element object.

    $this->Element->delete($this->data)

A detailed example:

Section 20 -> Element 400
Section 3 -> Element 20

If I delete the element 400, the Element 20 is deleted too.

I guess that I am missing a configuration parameter or some.

Thanks in advance.

**Comment by markstory** [comment]
Have you tried looking at the queries that are being generated and seeing if any of them are doing deletes that you don't expect? If there aren't any queries you should check your constraints/triggers.

**Comment by boxgames1** [comment]
Thanks for your response. I checked it, but there's not any trigger defined. The constraints/FKs are the usuals, well defined in 3rd Normal Form.


I am trying to get querieswith this:

` $this->Elemento->getDatasource()->getLog() `

But returned a void array with log:[], count 0 and time null.

Is there other method to get generated queries?


If I delete the element with the following query it runs well (only deletes the selected element):

`$this->Element->query("DELETE from elements where id=".$this->data["id"]);`

However, I'd like to find the problem because it could be in more sites.

Thanks for the help.

**Comment by chinpei215** [comment]
> $this->Element->delete($this->data)

@boxgames1 Are you passing `$this->data` to the `Model::delete()` method? But the signature of `Model::delete()` is: 

```php
public function delete($id = null, $cascade = true)
```

You should pass `$this->data['id']` instead:
```php
$this->Element->delete($this->data['id']);
```

**Comment by boxgames1** [comment]
Using that query it works well, but the question is the same: Why are the model deleteing other elements?

The JSON I passed to the delete function only had info about this Element and its parent (Section).

Thanks!

**Comment by chinpei215** [comment]
@boxgames1 `Model::delete()` can delete multiple records.
```php
[
    'id' => 1,
    'category_id' => 3,
    'price' => 10000,
]
```
Will generate `DELETE FROM elements WHERE id IN (1, 3, 10000)`.

**Comment by boxgames1** [comment]
Ok. I supposed something like that.

Many thanks for your help.

Have a nice day! :)
