### ISSUE TITLE
Sqlserver Driver on CakePHP 3.2.x

### ISSUE THREAD

**Issue by dhebonno** [cakephp/cakephp#9038]
Hi,

i have to try connect to database Sqlserver, but show 
Database driver Cake\Database\Driver\Sqlserver cannot be used due to a missing PHP extension or unmet dependency.

what to do for this problem.
whether there is in my code, I followed the documentation

**Comment by lorenzo** [comment]
Do you have the extension installed and loaded in your Windows machine?

**Comment by dhebonno** [comment]
I tried it on a Windows machine running normally.
but I tried it on CentOS 7 can not, how to use it on a Linux machine. Please advise.

what if using a DBLIB

thank you

**Comment by dakota** [comment]
The Microsoft Sqlserver extension only works on Windows currently. I believe Microsoft is working on a Linux version though. CakePHP only supports the official Microsoft extension.
