### ISSUE TITLE
Auth component redirects to last JSON ajax requested page

### ISSUE THREAD

**Issue by gestudio** [cakephp/cakephp#9040]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4
* Platform and Target: Centos 7, nginx..

### What you did
AngularJs $http ajax request.

### Expected Behavior
Json ajax requests should not be stored in Session Auth.redirect value.

### Actual Behavior
Auth component is storing JSON ajax requests in Auth.redirect session value causing login redirects to JSON response pages. 
RequestHandler will not recognize the JSON request as AJAX if the **X-Requested-With:XMLHttpRequest** header is not sent. 
The AuthComponent::_unauthenticated() function should include  **or $controller->request->is('json')** in addition to the **$controller->request->is('ajax')** check.

**Proposed change. Switch Line 362 AuthComponent to:**
`if (!$controller->request->is('ajax') or $controller->request->is('json')) {`

**Comment by lorenzo** [comment]
Would you mind submitting a pull request with the proposed change?

**Comment by gestudio** [comment]
sure! Pull request created.  #9042 
https://github.com/cakephp/cakephp/pull/9042
