### ISSUE TITLE
What are we going to do about PHP7 "throwable"

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9043]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.6.10
- Platform and Target: Apache 2.4, PHP 7.0
### What you did

Keep running into cases where CakePHP is not handling PHP 7's new "Error" and "Throwable" exceptions.
### Expected Behavior

Cells trigger a server 500 if there is a `Error` thrown during render.
Transactions not commit and leak if there is an `Error` class thrown.
Basically, anywhere there is a `catch(Exception $ex)` the code does not work as expected in PHP 7.
### Actual Behavior

PHP 7 introduced a new error type `Error`, and gave `Error` and `Exception` a common interface `Throwable`.

All `try/catch` methods that do a broad catch all `catch(Exception $e)` should be doing `catch(\Throwable $e)` in PHP 7.

I don't know how to address this issue in a backward compatible way.

Maybe use a global function that wraps a closure in the proper try/catch type for the current PHP version?

As this been discussed anywhere else by the Cake team?

**Comment by thinkingmedia** [comment]
Would something like this work without issues in PHP 5.x?

I found this while googling, but wouldn't Throwable be a undeclared type in PHP 5?

```
try {
    // Code that may throw an Exception or Error.
} catch (Throwable $t) {
    // Executed only in PHP 7, will not match in PHP 5.x
} catch (Exception $e) {
    // Executed only in PHP 5.x, will not be reached in PHP 7
}
```

**Comment by thinkingmedia** [comment]
I think I can make a PR to fix these. I found 27 try/catch pairs that need to be fixed.

**Comment by markstory** [comment]
> I found this while googling, but wouldn't Throwable be a undeclared type in PHP 5?

PHP is funny in that it won't complain about missing classes used in typehints/catch blocks. It will however try to autoload them.

Instead of duplicating all the `catch` blocks, could we conditionally define `Throwable`? Something like:

```php
if (!class_exists('Throwable', false)) {
  class Throwable extends Exception
  {
  }
}
```

That should enable us to use `\Throwable` throughout CakePHP in a transparent to PHP7 way.

**Comment by thinkingmedia** [comment]
It's an interface, but still. I think you're onto something. I might close this and try again.

**Comment by markstory** [comment]
I was thinking some more, and my suggestion won't work as `throw new \Exception()` isn't using `Throwable` :cry:.

**Comment by thinkingmedia** [comment]
I thinking of a closure fix.

```
   _try_catch_all(function() {
       // do stuff
   }, function($e) {
       // $e can be Exception or Error
   });
```

This won't work where there are multiple catches for known exceptions plus `\Exception`, but I think there is only 1 or 2 places like that.

Also, the above only applies to try/catch that are for any error. Maybe we need to revisit that code and review if such a broad catch is really needed.

Another point is that you can use "find usages" in an IDE and quickly see where this is being done.

**Comment by lorenzo** [comment]
500 errors are a good thing! How would you otherwise know that you have a syntax error, an uncommitted file, a type mismatch, etc?

If we catch the errors and deprive the users from things as basic as a stacktrace and some log output, those errors may go unnoticed and left unfixed.

This would be the equivalent of PHP 5.2 notices and using silencing the error output to make the problem go away.

There may be, though, cases where it is a good idea to catch the error, but I would like to take them case by base.

**Comment by chinpei215** [comment]
I am not in favor of the closure approach. Almost all exceptions shouldn't occur in normal case. Creating two closure and calling user defined functions everytime everywhere is not a good idea. Can't we catch Throwable after catching Exception?

```
try {

} catch (Exception $e) {
    
} catch (Throwable $t) { 
    // Never come here in PHP 5, as only instances of Exception can be thrown.
    // They should be caught the above catch block.
}
```

**Comment by thinkingmedia** [comment]
@lorenzo You make some very good points there.

There are some cases were these try/catch all exceptions need to be reviewed, but adding throwable to the group of catch all might not be a good idea.

**Comment by dereuromark** [comment]
> Would something like this work without issues in PHP 5.x?

Yes, that is the recommended strategy for PHP5 and PHP7 compatibility.
Whats the status here.

PS: Would using the shimming tool https://github.com/dstuecken/php7ify help here?

**Comment by thinkingmedia** [comment]
@dereuromark I've made at least 2 pull requests that attempted to close this issue. In those PRs the unit tests failed on travis for older versions of PHP. The failures were all fatal failures in phpunit (not the unit tests themselves). I tried for a few days to resolve and reproduce the problem, but I could not.

For some stupid reason, making the above changes to the code puts travis into a funky state where phpunit crashes (it fails to even finish all the tests).

I gave up after that. As a result of that experience. "if it an't broke, don't fix it" applies.

**Comment by thinkingmedia** [comment]
@dereuromark just to add.

I've had a lot of experience since this post with PHP 7, and I'm under the impression that a developer should not be catching the new Throwable interface. Only Exceptions, as catching these fatal PHP errors is a major change in behavior from PHP 5.6

I've since changed my project to allow the `Error` type to be uncaught, and as a result closing the transaction is no longer an issue since the app is going to crash anyway, and the DB connection should be closed (which is an auto rollback).

**Comment by lorenzo** [comment]
Closing then

**Comment by dereuromark** [comment]
It looks like we need this for at least the error handler and some low level logging etc, otherwise php7 errors (Throwable) happening in those will not be properly handled.

It should in those cases always look like this:

        try {
            ...
        } catch (Throwable $exception) {
            ...
        } catch (Exception $exception) {
            ...
        }

In case of PHP5.6 those will just be ignored and the fallback will be used.
We do not need to add this for high level exceptions where it is clear only "old" kind of exceptions are expected.

**Comment by chinpei215** [comment]
I think Exceptions should be caught earlier than Throwable, as we might want to rethrow Errors to keep existing behavior except bugs. So we might write different code in the two `catch` blocks.
(I left a similar comment above. Though I struck out my comment, from a different view point, now I think my suggestion itself is not wrong)

**Comment by dereuromark** [comment]
PR is open to further fine-tune.
