### ISSUE TITLE
SELECT * FROM information_schema Called in every query

### ISSUE THREAD

**Issue by ayoub-bousetta** [cakephp/cakephp#9049]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2

i'm trying to load multiple Model in 3rd ControllerAction but it sames that not working properly cuz every time i do that i ended up with alot o queries that's tooks more than 100s.

### My code inside the Action
```php
$users = $this->loadModel('Users');
$datas=$users->find('all')->select(['id','phone', 'first_name','last_name','birthday','email','website', 'address', 'resume', 'cv_url'])->where(['id' => 1])->bufferResults(false)->ToArray();


    $technologies = $this->loadModel('Technologies');
    $technologies=$technologies->find('all')->select(['id', 'name', 'slug', 'image', 'exp', 'exp_perc'])->bufferResults(false)->ToArray();

    $this->set(compact('datas','technologies'));
```

### Debug images

http://i.stack.imgur.com/85vBT.png
http://i.stack.imgur.com/xX6x6.png

as you can see i only have 2 queries but in debug it shows 10 and TABLE_SCHEMA took 35322ms and its called 2 time (35322*2)

PS : i have 'cacheMetadata' => true,

Any suggestion is welcome.

**Comment by markstory** [comment]
Looks like you're in debug mode. Metadata caching only lasts 10 seconds in development mode. You can tweak that by changing settings in your bootstrap.php.

**Comment by ayoub-bousetta** [comment]
Thank you for you fast answear.

i already change it to +1 years
if (!Configure::read('debug')) {
    Configure::write('Cache._cake_model_.duration', '+1 years');
    Configure::write('Cache._cake_core_.duration', '+1 years');
}

but it doesn't work i also tried debug =>false and still same for me , any other suggestions

**Comment by lorenzo** [comment]
you changed the config for when debug = false
