### ISSUE TITLE
Problems with I18n using translation functions

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#9053]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2.11.
* Default locale: pt_BR (but i don't think its relevant here)

Some of the examples on [i18n](http://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html#using-variables-in-translation-messages) don't work / throws exceptions, and i don't think it's just bad documentation (i may be wrong).

### Localize dates
```
>>> __(
    'Hi {0,string}, your balance on the {1,date} is {2,number,currency}',
    ['Charles', '2014-01-13 11:12:00', 1354.37]
);
Aura\Intl\Exception\CannotInstantiateFormatter with message 'msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR'
```
In this example, both `{0,string}` and `{1,date}` raises the error. Only `{2,number,currency}` works.
```
>>> __(
    'Hi {0}, your balance on the {1} is {2,number,currency}',
    ['Charles', '2014-01-13 11:12:00', 1354.37]
)
=> "Hi Charles, your balance on the 2014-01-13 11:12:00 is R$1.354,37"
```
### Localize numbers and currency
```
>>> __(
...     'You have traveled {0,number,decimal} kilometers in {1,number,integer} weeks',
...     [5423.344, 5.1]
... )
=> "You have traveled decimal5423 kilometers in 5 weeks"
```
The problem here is the `{0,number,decimal}`. Integer, currency and percent formats works fine.

**Comment by ADmad** [comment]
Looks like a documentation issue only. As per the table shown on http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html#patterns  `string` doesn't seems to be a valid `argType` nor is `decimal` an inbuilt `argStyle`.

**Comment by alysson-azevedo** [comment]
Ok, i'll reopen in the issue on the doc repo.
