### ISSUE TITLE
use hungarian notation

### ISSUE THREAD

**Issue by sliecer** [cakephp/cakephp#9055]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: future
* Platform and Target: all

Use the hungarian notation for the Framework. Debugging of web applications would be much easier for developers. (https://en.wikibooks.org/wiki/PHP_Programming/Alternative_Hungarian_Notation)

**Comment by ravage84** [comment]
:-1: Not really. This would be a step back.

Not sure what your professional background is, but I'm surprised you haven't heard that the industry have settled on the hungarian notation being **NOT useful**.

**Comment by markstory** [comment]
No thanks.
