### ISSUE TITLE
Can AssociationCollection::type() throw an exception for unknown types?

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9056]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10

### What you did

Tried to get all the belongsTo associations

```
        $this->belongsTo('Nodes');
        $this->belongsTo('Jobs');
        debug($this->associations()->type('belongsTo'));
```

### Expected Behavior

See a list of belongsTo assocation.

### Actual Behavior

Association type is case sensitive and I should have used "BelongsTo", but instead it returns an empty string. Which was very confusing and took me a while to spot my mistake.

What do you think about `type()` throwing an exception if the type is not supported, and how would the method know?

**Comment by markstory** [comment]
Instead of an exception could we make the comparison case-insensitive?

**Comment by thinkingmedia** [comment]
@markstory um, I hadn't thought of that. lol
