### ISSUE TITLE
Divide unit tests into suites

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9059]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Travis and Appveyor

### Enhancement

Currently the unit tests are all executed under one suite. Mapping all tests from `/tests/TestCase` into one suite.

I would like to change this so that the subfolders are each a suite, and phpunit is executed separately for each of those.

The objective is to make it a little easier to spot some of these seg faults and crashes we're experiencing on Travis/Appveyor. With this change we'll know which folder of tests triggered the event.

Running `vendor/bin/phpunit` should continue to default to all tests, but I want to change things (somehow) so that tests are run by subfolder and this is done automatically so developers do not need to change anything to add new tests.

**Comment by markstory** [comment]
How do more directories help with spotting failures/segfaults? PHPUnit has the idea of [Test Suites](https://phpunit.de/manual/current/en/organizing-tests.html) but I get the feeling this is something else.

**Comment by thinkingmedia** [comment]
I'm not looking to add any more directories or changing any of the existing tests. I want to execute phpunit multiple times on travis/appveyor grouping tests by the subfolder they are placed in.

Right now all tests are run in one long execution. When a seg fault happens you only know what percentage it reached before the failure. I would like to track if faults are happening during database testing, or ORM testing or what ever.

This does nothing to help with failing unit tests. It's a change to help localize which tests triggered a critical php failure during testing.

Picture running phpunit in a for/each loop for each subfolder of TestCase.

**Comment by ADmad** [comment]
You can already run for specific folders like `phpunit tests/TestCase/Folder`.

**Comment by thinkingmedia** [comment]
@ADmad yes, but then we have to add each folder to Travis. When a new folder is introduce the developer must remember to update Travis. Otherwise, the unit tests will pass but the new tests were not executed.

Understand what I mean? Divided by folder but handled automatically (somehow).

**Comment by ADmad** [comment]
Not really, you can dynamically list all subfolders of `TestCase` and run phpunit for each with a bash onliner `find tests/TestCase/* -maxdepth 0 -type d -exec phpunit {} \;`

**Comment by markstory** [comment]
You can also run `vendor/bin/phpunit --debug` to get more useful progress output.

**Comment by ADmad** [comment]
> You can also run vendor/bin/phpunit --debug to get more useful progress output.

Yup, I wasn't actually proposing using what I showed above. Just wanted to show you can dynamically run tests separately for each folder :)

**Comment by thinkingmedia** [comment]
I've found `--debug` and `--verbose` exceed travis's log size and you have to view the raw version (which is fine).

I was thinking if phpunit seg faults that travis should just go ahead and rerun it with --debug/--verbose in the next line of the script.

**Comment by thinkingmedia** [comment]
I'm closing as I've discovered that a unit test can be assigned to more than one group, and if we just give unit tests groups it achieves the same results that I was looking for. A way to run a part of the tests effectively.
