### ISSUE TITLE
Inconsistent `locale` ?

### ISSUE THREAD

**Issue by alex2690** [cakephp/cakephp#9064]
L10n::_l10nCatalog contains an array of languages. The value of 'locale' key seems to be inconsistent. Sometimes it is 3 letters code, in other cases it is 4 letters. 

Currently I'm using 4 letters locale and `'is' => array('language' => 'Icelandic', 'locale' => 'is_is', 'localeFallback' => 'isl', 'charset' => 'utf-8', 'direction' => 'ltr'),` doesn't apply to all cases. Fx that does not work with is_IS locale.
Is there a good reason why, for example it is 'locale' => 'dan', 'localeFallback' => 'dan' for example but not 'locale' => 'da_dk', 'localeFallback' => 'dan'?

can I make a PR to add is-is to the list ?

**Comment by lorenzo** [comment]
Sure, that would be appreciated :)
