### ISSUE TITLE
Upgrade from 3.2.10 to 3.2.11 Changed display of datetimes by 1 hour

### ISSUE THREAD

**Issue by birdy247** [cakephp/cakephp#9066]
Since upgrading from 3.2.10 to 3.2.11 my i18nFormat dates are one hour different.  I believe this to be something to do with the marshaling of date.

I have put together a gist to explain more:

https://gist.github.com/birdy247/9068ed2158ddc6ed20496f915c29055c

I reverted back to 3.2.10 without changing anything else and my datetimes were displaying as expected.

**Comment by markstory** [comment]
Not much changed in the database component between those releases. If you manually revert this diff, does your issue become fixed?

```diff
$ git diff 3.2.10..3.2.11 src/Database/Type
diff --git a/src/Database/Type/DateTimeType.php b/src/Database/Type/DateTimeType.php
index 8240aa8..e943a09 100644
--- a/src/Database/Type/DateTimeType.php
+++ b/src/Database/Type/DateTimeType.php
@@ -121,6 +121,10 @@ class DateTimeType extends Type
             list($value) = explode('.', $value);
         }

+        if ($this->_datetimeInstance === null) {
+            $this->_datetimeInstance = new $this->_className;
+        }
+
         $instance = clone $this->_datetimeInstance;
         return $instance->modify($value);
     }
@@ -251,7 +255,7 @@ class DateTimeType extends Type
             $class = $fallback;
         }
         $this->_className = $class;
-        $this->_datetimeInstance = new $this->_className;
+        $this->_datetimeInstance = null;
     }

     /**
```

**Comment by birdy247** [comment]
Yes it does, but it appears this is because I am using the Muffin/footprint plugin, which creates a newEntity.  This was resulting in things being converted i.e. my dateTime were coming back in the SOURCE timezone instead of the expected UTC timezone.  Upon further investigation, the "BUG" maybe with the footprint plugin.

**Comment by ADmad** [comment]
Does simply downgrading cakephp core resolve your issue?

**Comment by birdy247** [comment]
@ADmad yes that worked.

**Comment by ADmad** [comment]
Well then the issue does seem to be related to core rather than Footprint plugin.

**Comment by markstory** [comment]
The diff I posted earlier was intended to be a minor optimization to avoid loading `Cake\I18n\DateTime` and its parent classes until absolutely necessary. I think it might be simplest if we revert 2d153f080c16483c8a44346b5ddfce1673263c5e

**Comment by markstory** [comment]
Before reverting, it would be helpful to figure out *why* that change broke your custom type, as I don't see any uses of `_datetimeInstance` in the linked code. Does the Footprint plugin also use custom datetime types?

**Comment by ADmad** [comment]
`Footprint` doesn't use custom datetime types. Footprint maintains logged in user's record as entity by creating one from Auth's user array. That's the only place where marshaling of date could be involved.

But on IRC @birdy247 claimed that he has this problem even when reading a record for other models. So personally I have no idea what could be the source of issue could be.

**Comment by markstory** [comment]
@ADmad Interesting, I'm happy to revert the optimization if @birdy247 is confident it solves the issue he's having.

**Comment by ionas** [comment]
@birdy247 could you share an isolated issue repo (github link) or prep a Unit Test?

**Comment by birdy247** [comment]
@ADmad thats correct.  It seemed with the footprint trait any datetimes being returned had been converted into my source timezone.  When I reomve the footprint trait, any dates are returned in UTC.  Previous to 3.2.11, this was not the case, and things were always returned in UTC.

This is my timezoneAwareDateTimeType (originally by jose_zap)

```php

namespace App\Database\Type;

use Cake\Database\Type\DateTimeType;

/**
 * Datetime type converter.
 *
 * Use to convert datetime instances to strings & back.
 */
class TimezoneAwareDateTimeType extends DateTimeType {

    const SOURCE = 'Europe/London';
    const TARGET = 'UTC';

    /**
     * Returns the base type name that this class is inheriting.
     * This is useful when extending base type for adding extra functionality
     * but still want the rest of the framework to use the same assumptions it would
     * do about the base type it inherits from.
     *
     * @return string
     */
    public function getBaseType() {
        return 'datetime';
    }

    /**
     * Convert request data into a datetime object.
     *
     * @param mixed $value Request data
     * @return \Cake\I18n\Time
     */
    public function marshal($value) {
        date_default_timezone_set(self::SOURCE);
        if ($value instanceof \DateTime) {
            $value->setTimezone(new \DateTimeZone(self::TARGET));
            return $value;
        }
        //No need for this unless the footprint trait is being used
/*        if ($value instanceof \DateTimeImmutable) {
            $new = $value->setTimezone(new \DateTimeZone(self::TARGET));
            return $new;
        }*/
        $class = $this->_className;
        try {
            $compare = $date = false;
            if ($value === '' || $value === null || $value === false || $value === true) {
                return null;
            } elseif (is_numeric($value)) {
                $date = new $class('@' . $value);
                $date->timezone(new \DateTimeZone(self::TARGET));
            } elseif (is_string($value) && $this->_useLocaleParser) {
                return $this->_parseValue($value);
            } elseif (is_string($value)) {
                $date = new $class($value, new \DateTimeZone(self::TARGET));
                $compare = true;
            }
            if ($compare && $date && $date->format($this->_format) !== $value) {
                return $value;
            }
            if ($date) {
                return $date;
            }
        } catch (\Exception $e) {
            return $value;
        }
        if (is_array($value) && implode('', $value) === '') {
            return null;
        }
        $value += ['hour' => 0, 'minute' => 0, 'second' => 0];
        $format = '';
        if (isset($value['year'], $value['month'], $value['day']) &&
                (is_numeric($value['year']) && is_numeric($value['month']) && is_numeric($value['day']))
        ) {
            $format .= sprintf('%d-%02d-%02d', $value['year'], $value['month'], $value['day']);
        }
        if (isset($value['meridian'])) {
            $value['hour'] = strtolower($value['meridian']) === 'am' ? $value['hour'] : $value['hour'] + 12;
        }
        $format .= sprintf(
                '%s%02d:%02d:%02d', empty($format) ? '' : ' ', $value['hour'], $value['minute'], $value['second']
        );
        $date = new $class($format, new \DateTimeZone(self::SOURCE));
        $date->timezone(self::TARGET);
        return $date;
    }

    /**
     * Converts a string into a DateTime object after parseing it using the locale
     * aware parser with the specified format.
     *
     * @param string $value The value to parse and convert to an object.
     * @return \Cake\I18n\Time|null
     */
    protected function _parseValue($value) {
        date_default_timezone_set(self::SOURCE);
        $value = parent::_parseValue($value);
        date_default_timezone_set(self::TARGET);
        $value->timezone(self::TARGET);
        $new = $value->timezone(self::TARGET);
        return $new;
    }

}
```

**Comment by ADmad** [comment]
@birdy247 Yes we have understood the problem in general. The point is we need to narrow down the exact cause of the issue. Try the [patch](https://github.com/cakephp/cakephp/issues/9066#issuecomment-230050226) @markstory provided and let us know if it fixes your problem.

**Comment by birdy247** [comment]
Hey

Sorry this has taken so long to get back to you on.  I manually reverted the diff and it works as it did in 3.10

I also noticed that the times only changed with the Muffin/Footprint plugin when there was a user session (i.e. logged in).

Hope this helps

Thanks

Aaron

**Comment by markstory** [comment]
Thanks @birdy247 I'll revert the optimization then.
