### ISSUE TITLE
Add new method Table::update() for improved readability

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9068]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.11
* Platform and Target: Apache, MySQL, PHP7

### What you did

When reading the `Table::updateAll()` statements it can become ambiguous as to which array is the update and which is the condition.

```
            $this->Documents->updateAll([
                    'status' => 'create'
                ], [
                    'status' => 'publish'
                ]);
```

I get further confusion when `Table::findOrCreate()` is used in the same section of code.

```
             $this->Documents->findOrCreate([
                   'status'=>'review'
             ],[
                   'status'=>'process'
             ]);
```

The two APIs take the same type of parameters but in reverse order.

### Expected Behavior

There should be a way to write an update query that is easy to read and understand.

### Actual Behavior

If you write the update using the query builder. It's not as human readable as a SQL update statement.

```
          $this->Documents->find()->update([
                'status' => 'create'
          ])->where([
                'status' => 'publish'
          ])->execute();
```

Is it possible to make changes so that the above can be written as follows (which I think is easier to read).

```
          $this->Documents->update([
                'status' => 'create'
          ])->where([
                'status' => 'publish'
          ])->all();
```

It's not a big change, but there might be technical issues with it.

**Comment by Magellol** [comment]
I feel when you read the actual `updateAll` logic, it's not confusing at all since it takes `($fields, $conditions)` as signature and you'd clearly see that it does

```
->update()
->set($fields)
->where($conditions)
```

Not sure any of those changes is actually required, but it's only my two cents.

**Comment by htstudios** [comment]
I like the idea. ->count could get the fields the query WOULD update. Not sure if update where works with order and linit, though.

**Comment by dereuromark** [comment]
It already returns the Count as integer. Not sure a Count method is needed here then.

**Comment by markstory** [comment]
You find()->update() call can also be written as:

```php
  $this->Documents->query()->update([
                'status' => 'create'
          ])->where([
                'status' => 'publish'
          ])->execute();
```

Which makes a bit more sense when reading it back.

**Comment by thinkingmedia** [comment]
@markstory Yes, that's what I'm basically asking for. Except that I'm wanting to drop the call to `query()`.

This is basically a cosmetic change to the Table class.

```
    public function update($fields) {
           return $this->query()->update($fields);
    }
```

**Comment by markstory** [comment]
I worry that this method could potentially be confusing. At first glance, I would expect table classes to generally work with entities or provide queries to do other operations. I know that deleteAll() exists, but I wonder if that method is a mistake.

**Comment by htstudios** [comment]
I don't like the mix of query/entity with other things neither. You can see that from missing autoquotes to missing callbacks in 2.x's updateAll and deleteAll.

**Comment by thinkingmedia** [comment]
Close as I no longer think this change is a good idea.
