### ISSUE TITLE
[2.x] Stateless authentication data not available when route not protected by AuthComponent

### ISSUE THREAD

**Issue by biesbjerg** [cakephp/cakephp#9070]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.5

### What you did
I'm working on an API to retrieve a list of products. Based on the user (identified by a token, session disabled) I want to set a flag on each product letting me know if user already owns the product.

### Expected Behavior
When a token (which is expected by my TokenAuthenticate adapter) is present in the request, I would expect `AuthComponent::$_user` to be populated with data, even though it's a public/non-protected route.

### Actual Behavior
When accessing public/non-protected routes (`$this->Auth->allow('index')`) then `AuthComponent::_getUser()` is never run, Auth objects not queried which results in `AuthComponent::$_user` never being populated with data.

It does not seem it's possible to manually set AuthComponent::$_user in any way either, which would solve my problem, even though it would be an awful hack.

- Anyone else ran into this limitation?
- Does Cake3 have the same limitation?
- Can we do something about it?

**Comment by ionas** [comment]
In CakePHP3 I'd advice you to create a prefix and create an AppController for that prefix (e.g. SecuredAppController for instance). Then I'd use a ProductsTrait which I'd use in /products and /secured/products ... 

E.g. I'd keep routes that always HTTP AUTH and those that NEVER yield any HTTP AUTH info/try to HTTP AUTH.

**Comment by biesbjerg** [comment]
Not sure you missed it, but this ticket is for CakePHP 2.x. It's unfortunately not an option to upgrade to CakePHP 3 at this time.

Anyway, what you're saying doesn't solve the problem, if I understand correctly. 

Even when accessing public /products route, I want to have access to the user data (based on token) and that's not possible at without doing the change described in my diff.

**Comment by ionas** [comment]
I just think that you should either have HTTP AUTH as a requirement for a request, or have it not. But I can be wrong! It makes things simple. Maybe some guys on IRC/Slack can help you out on achieving what you want to do on CakePHP2 and/or help prepping a PR!

**Comment by markstory** [comment]
> Does Cake3 have the same limitation?

Presently yes.

> It shouldn't incur any performance penalty, I think.

It won't for the core provided authentication adapters. I'm not sure we can make the same assumptions about userland authentication adapters.

**Comment by ADmad** [comment]
In Cake 3 using `MemoryStorage` on can call `Auth->identify()` in `beforeFilter()` to get the authentication routine to always run.

**Comment by ADmad** [comment]
@biesbjerg You can just extend `AuthComponent` and override `startup()` method as you have shown.

I don't think any change needs to be done in core.

**Comment by biesbjerg** [comment]
I did go that route, but it is promoted to use AuthComponent::user() statically and I have a lot of these calls in my own code + plugins that does this, and it would not be able to access the user data, so I don't think that's a valid solution or even a solution at all.

**Comment by biesbjerg** [comment]
> In Cake 3 using MemoryStorage on can call Auth->identify() in beforeFilter() to get the authentication routine to always run.

Wouldn't that cause 2x user lookups, when performing a login? One for the manual `identify()` call and one in Login action?

**Comment by biesbjerg** [comment]
> In Cake 3 using MemoryStorage on can call Auth->identify() in beforeFilter() to get the authentication routine to always run.

By reading the code for AuthComponent in CakePHP 3 I can't see that's true. You can trigger `AuthComponent::identify()`, but the result is not written to storage. However, in CakePHP 3 there's a `AuthComponent::setUser()` method we can call manually after `AuthComponent::identify()` to persist the user.

This is not possible in CakePHP 2.x.

@markstory I understand your concerns about affecting userland authentication adapters, so here's what I propose:
Can we have a `AuthComponent::setUser()` method in CakePHP 2.x or change `AuthComponent::login()` to write to `AuthComponent::$_user`?

That would provide a way around the limitation at least.

**Comment by ADmad** [comment]
Right, in 3.x you would need to use `identify()` to get the record and then `setUser()` to set to storage.

**Comment by ADmad** [comment]
.. or change AuthComponent::login() to write to AuthComponent::$_user

Doing so won't prevent session from being started.

**Comment by biesbjerg** [comment]
> .. or change AuthComponent::login() to write to AuthComponent::$_user
> 
> Doing so won't prevent session from being started.

I set `AuthComponent::sessionKey = false` to prevent sessions from being started. The diff in previous commen makes it possible to actually set `AuthComponent::$_user` using `AuthComponent::login()` which is required to do the workaround you mentioned.

**Comment by ADmad** [comment]
You diff shows call to session->renew() and session->write(), that will cause session to be started :)  Unless you put those in a `if (!self::sessionKey)` check.

**Comment by biesbjerg** [comment]
That's the core code, not changes I made. If you look in CakeSession::write() you will see this:

```php
	public static function write($name, $value = null) {
		if (empty($name) || !static::start()) {
			return false;
		}
```

Session is not written to when $name is false. Anyway, I don't know why you suddenly started talking about sessions? :-)

**Comment by ADmad** [comment]
> Anyway, I don't know why you suddenly started talking about sessions? :-)

Because it's necessary to ensure session doesn't get started when using stateless authenticators. It took a decent amount of effort to ensure that in current 2.x code :)

The following change could work if it doesn't break existing tests.

```diff
diff --git a/lib/Cake/Controller/Component/AuthComponent.php b/lib/Cake/Controller/Component/AuthComponent.php
index 1b65fd9..3e62e2c 100644
--- a/lib/Cake/Controller/Component/AuthComponent.php
+++ b/lib/Cake/Controller/Component/AuthComponent.php
@@ -611,8 +611,12 @@ class AuthComponent extends Component {
 			$user = $this->identify($this->request, $this->response);
 		}
 		if ($user) {
-			$this->Session->renew();
-			$this->Session->write(static::$sessionKey, $user);
+			if (static::$sessionKey) {
+				$this->Session->renew();
+				$this->Session->write(static::$sessionKey, $user);
+			} else {
+				static::$_user = $user;
+			}
 			$event = new CakeEvent('Auth.afterIdentify', $this, array('user' => $user));
 			$this->_Collection->getController()->getEventManager()->dispatch($event);
 		}
```

**Comment by biesbjerg** [comment]
@ADmad Yeah, I remember some tickets a long time ago, but you do realize I didn't change the behavior around sessions in the diff I provided? 

Anyway, does not matter, we agree on the end goal, it seems :-)

**Comment by ADmad** [comment]
> you do realize I didn't change the behavior around sessions in the diff I provided

Yup which was actually a concern for me :)  It's better to ensure session methods are not called at all (as done in my diff) instead of relying on their internals to prevent a session start.

> Anyway, does not matter, we agree on the end goal, it seems :-)

Yup, a PR along the lines of what I showed is welcome.

**Comment by biesbjerg** [comment]
I agree it's much better not to call Session methods at all if sessionKey is false.

It's embarrassing really, but my PR game is pretty bad - I'll give it a shot! 

PR is up.

**Comment by markstory** [comment]
Closing as #9072 has been opened.
