### ISSUE TITLE
cakephp/i18n seems like error

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#9074]
It can not run independently  and require cakephp package too much，Even the constant like `APP` , 'CONFIG';  
![image](https://cloud.githubusercontent.com/assets/3785826/16609036/40971528-4383-11e6-88c1-5533ea9914ab.png)

**Comment by slince** [comment]
I think cakephp package should be developed separately。

**Comment by ADmad** [comment]
The `APP` constant is only used in fallback path. If you are using `i18n` package standalone you should set path to locale folder using `Configure::write('App.paths.locales', [..paths])`.  

I didn't find any use of `CONFIG` constant in the `i18n` package.

**Comment by slince** [comment]
@ADmad  ok, but I  think we had better pass locale path instead of get by itself

**Comment by ADmad** [comment]
Yes that could be an enhancement.

**Comment by markstory** [comment]
We could only use `APP` if it has been defined. Something like

```php
if (empty($localePaths) && defined('APP')) {
 ... use APP
}
```

**Comment by slince** [comment]
I suggest remove constant like `APP`,`CONFIG`, `ROOT`  from the  package, not only `i18n`；

**Comment by slince** [comment]
@markstory  @ADmad

**Comment by markstory** [comment]
@slince I'm fine with removing use of constants if we can keep the changes backwards compatible.

**Comment by markstory** [comment]
Closing as I think I got all the easily removable constant usages, or guarded the uses we can't remove without breaking compatibility.
