### ISSUE TITLE
TreeBehavior allows nodes to be their own parent

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#9080]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.11
* Platform and Target: PHP 7.0.6

### What you did
Step 1. Created a simple entity
Step 2. Updated the entity (changed the parent_id to itself)

### Expected Behavior
Thrown exception - Cannot set a node's parent as itself

### Actual Behavior
No exception gets thrown. The node's parent_id just changes to itself. My guess is that the problem is located in the code provided below.
```php
// TreeBehavior.php line 106
if ($isNew && $parent) {
  // Why we are comparing the entity PK with the parent_id if the entity is new?
  // New entity doesn't have a PK, therefore, 
  // maybe we should add an additional expression for existing entities?
    if ($entity->get($primaryKey[0]) == $parent) {
        throw new RuntimeException("Cannot set a node's parent as itself");
    }
```

**Comment by markstory** [comment]
Pull request up now.
