### ISSUE TITLE
Add unix timestamp support to Time::setJsonEncodeFormat

### ISSUE THREAD

**Issue by lilHermit** [cakephp/cakephp#9083]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Debian 8.5 (Jessie)

The `Time::setJsonEncodeFormat` method doesn't allow for unix timestamp format. I'm not 100% sure how it should be implemented. Maybe something like `Time::setJsonEncodeFormat(null)` as string|array|int are already used!?

Discuss ;-)

**Comment by lorenzo** [comment]
What's the purpose of having this format supported?

**Comment by lilHermit** [comment]
> What's the purpose of having this format supported?

Because my particular client requires unix timestamps for json serialised data not ISO/RFC datetimes

**Comment by markstory** [comment]
This might be tricky as [IntlDateFormatter](http://php.net/intldateformatter) doesn't support timestamp outputs. I'm also not sure that `setJsonEncodeFormat(null)` is the easiest to understand signature we could have. Perhaps there is a constant we can use to make the code people need to use easier to understand.

**Comment by lilHermit** [comment]
> Perhaps there is a constant we can use to make the code people need to use easier to understand.
Yeah I agree a constant might be best from a method understanding perspective.

**Comment by burzum** [comment]
@markstory something similar to this would do the trick?`

```php
    public function jsonSerialize()
    {
        if (static::$_jsonEncodeFormat === self::$UNIX_TIMESTAMP) {
            return (new Chronos(static::$_jsonEncodeFormat))->getTimestamp();
        }
        return $this->i18nFormat(static::$_jsonEncodeFormat);
    }
```

**Comment by markstory** [comment]
Something like that. I'm not sure why you need to create an instance of `Chronos` though.

**Comment by markstory** [comment]
Closing in favor of #9425
