### ISSUE TITLE
The check "$result instanceof ResultSet" in Cake\ORM\Query::_decorateResults always fails

### ISSUE THREAD

**Issue by proto-n** [cakephp/cakephp#9084]
This is a:
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3cafdd1
* Platform and Target: PHP 7.0.8-3+deb.sury.org~trusty+1 (cli)

This is quite minor, but possibly affects performace to some extent:

Cake\ORM\Query, after applying decorators, [checks if the decorated result is an instance of Cake\ORM\ResultSet](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/ORM/Query.php#L1160). Since the result returned from the called [Cake\Datasource\QueryTrait::_decorateResults](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/Datasource/QueryTrait.php#L478) (which is [imported as Cake\ORM\Query::_applyDecorators](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/ORM/Query.php#L77)) is always of type Cake\Datasource\ResultSetDecorator, the check always fails. This causes the $result to be transformed into an other Cake\Datasource\ResultSetDecorator ([see 1](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/ORM/Query.php#L1162), [see 2](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/Datasource/QueryTrait.php#L507)).

Note, that Cake\Datasource\QueryTrait::_decorateResults [explicitly checks](https://github.com/cakephp/cakephp/blob/3cafdd18fd2ef73afc6ac36a7bc2e6340149be20/src/Datasource/QueryTrait.php#L493) if $results is an instance of Cake\Datasource\ResultSetDecorator.

The solution would be maybe to check for `instanceof ResultSetInterface` instead of ResultSet, as ResultSetDecorator implements ResultSetInterface, however I'm not sure whether there are additional considerations to this.

This issue also prevents me from extending ResultSetDecorator and returning an instance of the child class from a formatResults function, as it is transformed into a ResultSetDecorator instance in _decorateResults, which is how I discovered it.

**Comment by lorenzo** [comment]
I'm really not following what the problem is. The decorators are only applied if there is anything to apply. Later on, it check if there was any decorator applied, otherwise if forces the decoration.... It seems to work as intender

**Comment by proto-n** [comment]
Ok, so the problem described more clearly: 

1. the code applies the decorators in `QueryTrait::_decorateResults`, returns an instance of `ResultSetDecorator`. (There is no problem here!)
2. `Query::_decorateResults` checks whether the returned value is an instance `ResultSet` (it isn't, since `ResultSetDecorator` only implements `ResultSetInterface`), and since it isn't, the code transforms the value into an other instance `ResultSetDecorator` (which it already is).

So basically we have:
```
$result = $this->_applyDecorators($result); 
//$result is now a ResultSetDecorator, thus is not an instance of ResultSet
if (!($result instanceof ResultSet) && $this->bufferResults()) {
            $class = $this->_decoratorClass(); 
            //$class == 'Cake\Datasource\ResultSetDecorator';
            $result = new $class($result->buffered());  
            //$result is now transformed into an other ResultSetDecorator
}
```

I don't see the point in calling `$result = new Cake\Datasource\ResultSetDecorator($result->buffered());` when `$result` is already a `Cake\Datasource\ResultSetDecorator` beforehand.
However there could be something I'm not understanding about buffered ResultSets. If the code is meant to work like this, feel free to mark this issue closed. Thank you!

**Comment by markstory** [comment]
The suggested changes don't seem to cause any major issues in the test suite. However, two tests for `ResultSet::__debugInfo()` are now failing

<details>
<summary>Failing tests</summary>
3) Cake\Test\TestCase\ORM\ResultSetTest::testDebugInfo
Failed asserting that Array &0 (
    'count' => 3
) is identical to Array &0 (
    'items' => Array &1 (
        0 => Cake\ORM\Entity Object &0000000012d6a9940000000023b5b1f1 (
            '_properties' => Array &2 (
                'id' => 1
                'author_id' => 1
                'title' => 'First Article'
                'body' => 'First Article Body'
                'published' => 'Y'
            )
            '_original' => Array &2
            '_hidden' => Array &2
            '_virtual' => Array &2
            '_className' => null
            '_dirty' => Array &2
            '_new' => false
            '_errors' => Array &2
            '_invalid' => Array &2
            '_accessible' => Array &2
            '_registryAlias' => 'articles'
        )
        1 => Cake\ORM\Entity Object &0000000012d6a9c40000000023b5b1f1 (
            '_properties' => Array &3 (
                'id' => 2
                'author_id' => 3
                'title' => 'Second Article'
                'body' => 'Second Article Body'
                'published' => 'Y'
            )
            '_original' => Array &3
            '_hidden' => Array &3
            '_virtual' => Array &3
            '_className' => null
            '_dirty' => Array &3
            '_new' => false
            '_errors' => Array &3
            '_invalid' => Array &3
            '_accessible' => Array &3
            '_registryAlias' => 'articles'
        )
        2 => Cake\ORM\Entity Object &0000000012d6a99a0000000023b5b1f1 (
            '_properties' => Array &4 (
                'id' => 3
                'author_id' => 1
                'title' => 'Third Article'
                'body' => 'Third Article Body'
                'published' => 'Y'
            )
            '_original' => Array &4
            '_hidden' => Array &4
            '_virtual' => Array &4
            '_className' => null
            '_dirty' => Array &4
            '_new' => false
            '_errors' => Array &4
            '_invalid' => Array &4
            '_accessible' => Array &4
            '_registryAlias' => 'articles'
        )
    )
).

/Users/markstory/Sites/cake3/tests/TestCase/ORM/ResultSetTest.php:264
/Users/markstory/Sites/cake3/tests/TestCase/DatabaseSuite.php:68

4) Cake\Test\TestCase\ORM\ResultSetTest::testDebugInfo
Failed asserting that Array &0 (
    'count' => 3
) is identical to Array &0 (
    'items' => Array &1 (
        0 => Cake\ORM\Entity Object &0000000012d68e320000000023b5b1f1 (
            '_properties' => Array &2 (
                'id' => 1
                'author_id' => 1
                'title' => 'First Article'
                'body' => 'First Article Body'
                'published' => 'Y'
            )
            '_original' => Array &2
            '_hidden' => Array &2
            '_virtual' => Array &2
            '_className' => null
            '_dirty' => Array &2
            '_new' => false
            '_errors' => Array &2
            '_invalid' => Array &2
            '_accessible' => Array &2
            '_registryAlias' => 'articles'
        )
        1 => Cake\ORM\Entity Object &0000000012d68e560000000023b5b1f1 (
            '_properties' => Array &3 (
                'id' => 2
                'author_id' => 3
                'title' => 'Second Article'
                'body' => 'Second Article Body'
                'published' => 'Y'
            )
            '_original' => Array &3
            '_hidden' => Array &3
            '_virtual' => Array &3
            '_className' => null
            '_dirty' => Array &3
            '_new' => false
            '_errors' => Array &3
            '_invalid' => Array &3
            '_accessible' => Array &3
            '_registryAlias' => 'articles'
        )
        2 => Cake\ORM\Entity Object &0000000012d697b70000000023b5b1f1 (
            '_properties' => Array &4 (
                'id' => 3
                'author_id' => 1
                'title' => 'Third Article'
                'body' => 'Third Article Body'
                'published' => 'Y'
            )
            '_original' => Array &4
            '_hidden' => Array &4
            '_virtual' => Array &4
            '_className' => null
            '_dirty' => Array &4
            '_new' => false
            '_errors' => Array &4
            '_invalid' => Array &4
            '_accessible' => Array &4
            '_registryAlias' => 'articles'
        )
    )
).

/Users/markstory/Sites/cake3/tests/TestCase/ORM/ResultSetTest.php:264
/Users/markstory/Sites/cake3/tests/TestCase/DatabaseSuite.php:68
</details>

**Comment by lorenzo** [comment]
The code works as expected. The reason for calling buffered() only when it has been decorated is to prevent the iterations from running their logic twice if the collection is iterated more than once.

The buffered collection will keep a cached result of all the previous decorators in memory, to avoid side effects.
