### ISSUE TITLE
Cannot convert value to string with validateUnique validator example

### ISSUE THREAD

**Issue by dvelguru** [cakephp/cakephp#9088]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: XAMP MYSQL PHP 5.4+

### What you did
Followed the directions for validating unique as explained here -> [HERE](http://book.cakephp.org/3.0/en/core-libraries/validation.html)

```php
// Use a rule from the table provider
    public function validationDefault(Validator $validator) {
        $validator->add('email', ['unique' => ['rule' => 'validateUnique', 'provider' => 'table']]);
        return $validator;
    }
```

### Expected Behavior
Return error for duplicate entry.

### Actual Behavior
InvalidArgumentException : Cannot convert value to string.

**Comment by markstory** [comment]
What is the stack trace on that error?

**Comment by dvelguru** [comment]
Hey mark,

⟩ Cake\Database\Type\StringType->toDatabase
CORE/src/Database/TypeConverterTrait.php, line 37
⟩ Cake\Database\Statement\StatementDecorator->cast
CORE/src/Database/Statement/PDOStatement.php, line 70
⟩ Cake\Database\Statement\PDOStatement->bindValue
CORE/src/Database/Statement/StatementDecorator.php, line 105
⟩ Cake\Database\Statement\StatementDecorator->bindValue
CORE/src/Database/Log/LoggingStatement.php, line 97
⟩ Cake\Database\Log\LoggingStatement->bindValue
CORE/src/Database/Statement/StatementDecorator.php, line 290
⟩ Cake\Database\Statement\StatementDecorator->bind
CORE/src/Database/ValueBinder.php, line 125
⟩ Cake\Database\ValueBinder->attachTo
CORE/src/Database/Connection.php, line 271
⟩ Cake\Database\Connection->run
CORE/src/Database/Query.php, line 188
⟩ Cake\Database\Query->execute
CORE/src/ORM/Query.php, line 805
⟩ Cake\ORM\Query->_performCount
CORE/src/ORM/Query.php, line 756
⟩ Cake\ORM\Query->count
APP/Model/Table/UsersTable.php, line 72
⟩ App\Model\Table\UsersTable->exists
CORE/src/ORM/Rule/IsUnique.php, line 66
⟩ Cake\ORM\Rule\IsUnique->__invoke
CORE/src/ORM/Table.php, line 2188
⟩ Cake\ORM\Table->validateUnique
CORE/src/Validation/ValidationRule.php, line 140
⟩ Cake\Validation\ValidationRule->process
CORE/src/Validation/Validator.php, line 1505
⟩ Cake\Validation\Validator->_processRules
CORE/src/Validation/Validator.php, line 137
⟩ Cake\Validation\Validator->errors
CORE/src/ORM/Marshaller.php, line 203
⟩ Cake\ORM\Marshaller->_validate
CORE/src/ORM/Marshaller.php, line 489
⟩ Cake\ORM\Marshaller->merge
CORE/src/ORM/Table.php, line 2099
⟩ Cake\ORM\Table->patchEntity
APP/Controller/UsersController.php, line 35
⟩ App\Controller\UsersController->register
[internal function]
⟩ call_user_func_array
CORE/src/Controller/Controller.php, line 429
⟩ Cake\Controller\Controller->invokeAction
CORE/src/Routing/Dispatcher.php, line 114
⟩ Cake\Routing\Dispatcher->_invoke
CORE/src/Routing/Dispatcher.php, line 87
⟩ Cake\Routing\Dispatcher->dispatch
ROOT/webroot/index.php, line 37

**Comment by markstory** [comment]
I'm assuming that the array is coming in request data then?

**Comment by dvelguru** [comment]
#UsersController.php
public function register() {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if (!$user->errors()) {
                $user->type = 'a';
                $this->Users->save($user);
                $this->Flash->success('Your account has been created.', ['clear' => true, 'key' => 'RegisterFormFlash']);
            }
        }
        $this->set('user', $user);
    }

**Comment by markstory** [comment]
I don't think we should automatically casting incorrect data into strings. Given that you've gotten effectively invalid data from the request, we could fail validation when arrays are found, silently accepting arrays will only cause issues downstream.

**Comment by dvelguru** [comment]
I believe this issue can be recreated. Here's the documentation for the method I used above.
[Modifying the ArticlesController](http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html#modifying-the-articlescontroller)

**Comment by markstory** [comment]
Pull request open now.
