### ISSUE TITLE
Pipelines : conditionally applying Middlewares

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/cakephp#9089]
This is a RFC ticket to draft an implementation to find a way to conditionally apply middlewares. After discussing this with @markstory, here is the idea.

Since `DispatcherFilters` (now replaced with `Middleware`) allow the developer to define a set of conditions to determine if they should be applied or not, the middleware stack should allow that as well.

The idea would be to implement a concept of `pipeline`. A `pipeline` would be a "sub-stack" of middleware that would have a set of conditions bound to it. When a pipeline is run:
- It evaluates the `scope` and `when` conditions if they exist.
- If the conditions pass, the pipeline will invoke the middleware it contains.
- Each of the contained middleware can augment the response, and short-circuit the remaining middleware.
- When complete, a pipeline may call `$next` which invokes the next middleware in the parent MiddlewareStack
- If the conditions do not match, the `$next` callable is invoked.

This means we would have a "root MiddlewareStack" that calls pipelines. Pipelines would then call their own child middleware.

As for the "concrete" implementation, we would have a new `pipe()` method in the `MiddlewareStack` :

`pipe($conditions) : Pipeline`

It would take a parameter that allows the developer to define the conditions that would trigger it.

``` php
// Use URL conditions
$middleware->pipe(['scope' => '/url/fragment'])
    ->push(new ThingMiddleware())
    ->push(new AssetsMiddleware());

// Use a callable conditions
$middleware->pipe(['when' => function ($req, $res) { return true; }])
    ->push(new ThingMiddleware())
    ->push(new AssetsMiddleware());
```

A Pipeline would be a hybrid of `MiddlewareStack` and `Middleware`:
- MiddlewareStack because it can registers multiple middlewares to be applied using the exact same methods
- Middleware because it will need to implement the method `public function __invoke($request, $response, $next)` as middlewares do. This method will be run to evaluate if it should be applied or not and go to the next pipeline in line.

If multiple pipelines are defined, they are run in the order they are added to the root MiddlewareStack.

Feedback is welcomed. If you would like to share a use case you have for conditionally applying middleware, please do. Having a more concrete vision of how you need to apply them conditionally could point us in the right direction and validate or not this idea.
##### Edits
- Added `when` condition.

**Comment by ionas** [comment]
Would scope work in conjunctions with the Router instead of bare URLs?
Could scope take a callable/anon-function (that takes $request?, $response?, $next?) and returns either void/false or a hash with 'request', 'response', 'next'?

I don't furthermore understand why the scope is defined by url-fragments?

**Comment by ADmad** [comment]
> I don't furthermore understand why the scope is defined by url-fragments?

The proposed `scope` option would be same as current `for` option for dispatcher filters.

**Comment by ADmad** [comment]
> If you would like to share a use case you have for conditionally applying middlewares, please do.

A practical e.g. is my current dispatcher filter [GlideFilter](https://github.com/ADmad/cakephp-glide#dispatcher) which is meant to be scoped to work only for URLs starting with `/images`.

So if the proposed pipeline feature is implemented (and I write a `GlideMiddleware`) one would modify app's [Application::middleware()](https://github.com/cakephp/app/blob/3.next/src/Application.php#L49) method and add

```php
$middleware->pipe(['scope' => '/images'])
    ->push(new GlideMiddleware());
```

above the statement pushing `AssetMiddleware` to the stack.

**Comment by ionas** [comment]
Just by looking at the docs: http://book.cakephp.org/3.0/en/development/dispatch-filters.html#conditionally-applying-filters
... `when` is the way I'd like things to work with pipelines too.

**Comment by ionas** [comment]
A use case off-of my head would be applying a certain filter if request-`content-type` is application/json, xml, etc.

**Comment by markstory** [comment]
> I don't furthermore understand why the scope is defined by url-fragments?

Because it is a simple way to divide up where specific pieces of middleware should apply.

I don't think having `scope` precludes us from also having a `when` callable. I'll update the issue description to outline that.

**Comment by HavokInspiration** [comment]
Yes, I forgot to add it.
Being able to stack the conditions should be done too :

```php
$middleware->pipe([
    'when' => function ($req, $res) { return true; },
    'scope' => '/api'
])
    ->push(new ThingMiddleware())
    ->push(new AssetsMiddleware());
```

This pipe would only be executed if the URL is from the `/api` scope and only if `when` returns true. This would give even more flexibility.

**Comment by Xymanek** [comment]
Didn't work with dispatch filters much, but how will this be handled by `requestAction()`?

**Comment by josegonzalez** [comment]
I'd very much love if we completely deleted any and all code related to `requestAction`.

**Comment by Xymanek** [comment]
@josegonzalez why? It is quite useful at times but a bit confusing to set up... Or are you suggesting to completely replace it with cells?

**Comment by josegonzalez** [comment]
Correct, there are better ways to do what requestAction lets people do, and weird bugs around how requestAction handles things.

**Comment by htstudios** [comment]
Dows scope allow to use Router::url()? What about regexp patterns? What does fragment mean specifically? Does this scope here has anything to do with Router scope? If not, should it be named differently (maybe for)?

**Comment by lorenzo** [comment]
Middleware is more often than not tied to a group of routes. My suggestion is that we go with the same implementation the phoenix framework goes:

http://www.phoenixframework.org/docs/routing#section-the-browser-and-api-pipelines


In PHP that would be:

```php
$pipelines->create('browser')->push(new ThingMiddleware())->push(...);
$pipelines->create('api')->push(new AnotherThing())->push(...);

...

Router::scope('/api', $routes)->through('browser')->through('anotherCustomPipeline');
```

The main problem I see with this is that Routing is already part of the middleware, so figuring out how everything fits together might be difficult. But I do believe that tying the pipelines to routes is the best way we can communicate their purpose.

**Comment by Xymanek** [comment]
@lorenzo Can middleware add middleware to stack?
If yes then after the router matches a scope it can add the scope's pipelines' middleware after itself (or before the next middleware).

So when the RouterMiddleware calls `$next()` it will call the configured pipeline.

P.S. It probably doesn't make sense :(

**Comment by markstory** [comment]
> Can middleware add middleware to stack?

No it cannot.

**Comment by markstory** [comment]
@Xymanek Middleware and pipelines do not interact at all with `requestAction()`. `requestAction()` will be removed in the future. It creates a bunch of complexity in the the framework, and with cells we generally have a better solution now.

@ionas 

> Dows scope allow to use Router::url()? What about regexp patterns? What does fragment mean specifically? 

It doesn't interact with Router::url() at all. We could support patterns, but I feel that URL patterns and URL prefixes should be separate options.

@lorenzo 
> Middleware is more often than not tied to a group of routes. My suggestion is that we go with the same implementation the phoenix framework goes:

Our current middleware implementation isn't built inside of routing. It wraps around routing, and routing is primarily used for controller location/routing.

**Comment by markstory** [comment]
Closing as I think #10308 is the successor to this idea.
