### ISSUE TITLE
query builder for year function doesnt work well

### ISSUE THREAD

**Issue by ijc-90** [cakephp/cakephp#9091]
I'm not sure if i understood something wrong, but it looks like its not working like the docs say it does.

Literally from the book:
```
$query = $articles->find();
$year = $query->func()->year([
    'created' => 'identifier'
]);
$time = $query->func()->date_format([
    'created' => 'identifier',
    "'%H:%i'" => 'literal'
]);
$query->select([
    'yearCreated' => $year,
    'timeCreated' => $time
]);
```

generates a wrong query:
```
(year(:c0)) AS `year`
'params' => [
		':c0' => [
			'value' => 'identifier',
			'type' => null,
			'placeholder' => 'c0'
		]
	],
```
What works for me:
```
['year' => $query->func()->year([
    'fecha_ingreso'` => 'literal']
)];
```
This generates correctly the sql query:
```
(year(fecha_ingreso)) AS `year`
```

**Comment by markstory** [comment]
While I agree that the generated query *looks* wrong if you dump it, it executes correctly. For example

```php
        $table = TableRegistry::get('users');
        $query = $table->find();
        $user = $query->select(['year' => $query->func()->year(['created' => 'identifier'])])
            ->where(['id' => 1])->first();
        debug($user);
```

Does what you would expect. Are you not getting the correct results when executing your query?

**Comment by ijc-90** [comment]
The query gives me the wrong answer.
if I do:
```
foreach($query as $solicitud){
            debug($solicitud);
            debug([$solicitud->year,$solicitud->count]);
        }
```
I get null in the year, but when using "literal" instead of "identifier" I get the wright year



Here is how the first debug looks like:
```
object(App\Model\Entity\ImpoSolicitude) {

	'count' => '1',
	'year' => null,
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'count' => true,
		'year' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => null

}
```

**Comment by markstory** [comment]
Interesting, what database server are you running against?

**Comment by ijc-90** [comment]
mysql

**Comment by markstory** [comment]
Ok, I was testing against mysql5.6 and PHP 7

**Comment by ijc-90** [comment]
And it works for you? I dont know exactly in wich version of mysql+php im working.

I'm running it inside a docker container brought from: [tutum/lamp](https://github.com/tutumcloud/lamp)


I didn't change anything.

I'll continue working on this the next weekend so I'll check the versions then.

**Comment by markstory** [comment]
Yes, The code snippet I pasted above ran fine against MySQL 5.6 & PHP7.

**Comment by raponiwalter** [comment]
Works as should on CakePHP 3.2.12, PHP 5.6.5 and MySQL 5.6.22 on Debian.

**Comment by ijc-90** [comment]
Mysql Version is: 5.5.47
Apache: Apache/2.4.7 (Ubuntu)
PHP Version 5.5.9

**Comment by lorenzo** [comment]
@ijc-90 you can just use literal instead of identifier until you update your cakephp version tote one that supports the identifier keyword.
