### ISSUE TITLE
Dynamic database connection

### ISSUE THREAD

**Issue by VivekSolankiPM** [cakephp/cakephp#9093]
Unable to change the connection dynamically with cakephp 3.
I want to change the connnection as i  pass the database name and the database connection change with that database .But cant find any code for this functionality in the cakephp 3.0

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
