### ISSUE TITLE
CakeTime::format return wrong date on windows

### ISSUE THREAD

**Issue by mlingureanu** [cakephp/cakephp#9100]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.8.5
- Platform and Target: windows , PHP Version 5.5.19

from unit test:

```
public function testCakeTimeVsDateTime() {
        $seconds = 1000;
        $interval = new DateInterval('PT' . $seconds . 'S');
        $nowObj = new DateTime('2099-06-18 09:01:23');
        $dateObj = date_add($nowObj, $interval);
        $expected = date_format($dateObj, "Y-m-d H:i:s");
        $result = CakeTime::format($dateObj, "%Y-%m-%d %H:%M:%S");
        $this->assertEquals($expected, $result);
    }
```

test fail:

```
1) OpeningsComponentTest::testCakeTimeVsDateTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2099-06-18 09:18:03'
+'2038-01-19 04:14:07'
```

another test:

```
public function testStrtotimeVsDateTime() {
        $seconds = 1000;
        $interval = new DateInterval('PT' . $seconds . 'S');
        $nowObj = new DateTime('2099-06-18 09:01:23');
        $expected = date_format(date_add($nowObj, $interval), "Y-m-d H:i:s");
        $result = date("Y-m-d H:i:s", strtotime("2099-06-18 09:01:23 +$seconds seconds"));
        $this->assertEquals($expected, $result);
    }
```

test fail:

```
2) OpeningsComponentTest::testStrtotimeVsDateTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2099-06-18 09:18:03'
+'1970-01-01 01:00:00'
```
### Expected Behavior

CakeTime::format returns wrong date
in second test function strtotime returns wrong time
### Actual Behavior

CakeTime::format accepts DateTime objects from CakePHP version 2.2 but it's returns wrong date.

**Comment by mlingureanu** [comment]
from unit test:
```
public function testCakeTimeVsDateTime() {
		$seconds = 1000;
		$interval = new DateInterval('PT' . $seconds . 'S');
		$nowObj = new DateTime('2099-06-18 09:01:23');
		$expected = date_format(date_add($nowObj, $interval), "Y-m-d H:i:s");
		$result = CakeTime::format(date_add($nowObj, $interval), "%Y-%m-%d %H:%M:%S");
		$this->assertEquals($expected, $result);
	}
```
test fail:
```
1) OpeningsComponentTest::testCakeTimeVsDateTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2099-06-18 09:18:03'
+'2038-01-19 04:14:07'
```
another test:
```
public function testStrtotimeVsDateTime() {
		$seconds = 1000;
		$interval = new DateInterval('PT' . $seconds . 'S');
		$nowObj = new DateTime('2099-06-18 09:01:23');
		$expected = date_format(date_add($nowObj, $interval), "Y-m-d H:i:s");
		$result = date("Y-m-d H:i:s", strtotime("2099-06-18 09:01:23 +$seconds seconds"));
		$this->assertEquals($expected, $result);
	}
```
test fail:
```
2) OpeningsComponentTest::testStrtotimeVsDateTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2099-06-18 09:18:03'
+'1970-01-01 01:00:00'
```

**Comment by markstory** [comment]
Are you using 32bit build of PHP on windows?

**Comment by mlingureanu** [comment]
Yes, but I tested on 64bit build of PHP and strtotime returns wrong date "1970-01-01" when tried to enter date greater than "2038-01-19".
Only on PHP 7 strtotime returns correct timestamps for date greater than "2038-01-19"
It's a PHP bug on windows.
That's why I'm trying to use DateTime object as parameter for CakeTime::format();
There is a note on PHP manual, that's says, strtotime should not be used for calculations and recommend to use DateTime objects instead.

**Comment by markstory** [comment]
Internally CakeTime converts all parameters into timestamps. If you already have a `DateTime` instance `CakeTime::format()` provides no additional value over using strftime() yourself.

**Comment by raponiwalter** [comment]
On Windows 10 64bit, 32bit PHP:
CakeTime uses (int) to cast timestamp. This result on a negative date for the first example. A work around might be cast it to (float) insted, works on the first example.

On the same platform strftime() returns wrong date (int limit as above).
I way might be patching `CakeTime::_strftime()` and use DateTime instead. A new method is necessary to parse strftime() formats to date() format to be keep compatibility with the current CakeTime version 
_(gist https://gist.github.com/mcaskill/02636e5970be1bb22270 by @mcaskill)_

```php
/**     
* Convert strftime() format to date() format
* from gist https://gist.github.com/mcaskill/02636e5970be1bb22270 from @mcaskill
*
* @param string $strfFormat  FormatString
* @return mixed
*/
    static function strftimeFormatToDateFormat($strfFormat)
    {
        // http://php.net/manual/en/function.strftime.php
        $strfSyntax = [
            // Day - no strf eq : S (created one called %O)
            '%O', '%d', '%a', '%e', '%A', '%u', '%w', '%j',
            // Week - no date eq : %U, %W
            '%V',
            // Month - no strf eq : n, t
            '%B', '%m', '%b', '%-m',
            // Year - no strf eq : L; no date eq : %C, %g
            '%G', '%Y', '%y',
            // Time - no strf eq : B, G, u; no date eq : %r, %R, %T, %X
            '%P', '%p', '%l', '%I', '%H', '%M', '%S',
            // Timezone - no strf eq : e, I, P, Z
            '%z', '%Z',
            // Full Date / Time - no strf eq : c, r; no date eq : %c, %D, %F, %x
            '%s'
        ];

        $dateSyntax = [
            'S', 'd', 'D', 'j', 'l', 'N', 'w', 'z',
            'W',
            'F', 'm', 'M', 'n',
            'o', 'Y', 'y',
            'a', 'A', 'g', 'h', 'H', 'i', 's',
            'O', 'T',
            'U'
        ];

        $pattern = array_map(
            function ( $s ) {
                return '/(?<!\\\\|\%)' . $s . '/';
            },
            $strfSyntax
        );

        return preg_replace($pattern, $dateSyntax, $strfFormat );
    }

/**
 * Multibyte wrapper for strftime.
 *
 * Handles utf8_encoding the result of strftime when necessary.
 *
 * @param string $format Format string.
 * @param int $date Timestamp to format.
 * @return string formatted string with correct encoding.
 */
	protected static function _strftime($format, $date) {
        $obj = new DateTime('@' . $date);
        $format = $obj->format(static::strftimeFormatToDateFormat($format));
		$encoding = Configure::read('App.encoding');

		if (!empty($encoding) && $encoding === 'UTF-8') {
			if (function_exists('mb_check_encoding')) {
				$valid = mb_check_encoding($format, $encoding);
			} else {
				$valid = Multibyte::checkMultibyte($format);
			}
			if (!$valid) {
				$format = utf8_encode($format);
			}
		}
        return $format;
	}
```

Might be `IntlDateFormatter::create()` ( [php.net docs](http://php.net/manual/en/intldateformatter.create.php)) a future Option?

**Comment by markstory** [comment]
We're already using IntlDateFormatter exclusively in 3.x. I don't have much interest in adding new dependencies for 2.x at this stage in its lifetime.

**Comment by raponiwalter** [comment]
@markstory A pr with a work around would be ok? Might spend some time on it, but don't wont to waiste time on no-usefull things

**Comment by markstory** [comment]
If the code came with thorough tests I would be opening to merging changes that fix this. Outside of that I will not fix this, as I feel you should use 64bit PHP if you want to bypass the end of 32bit ints.

**Comment by mlingureanu** [comment]
CakeTime should be rewritten, to use DateTime instead of timestamps, like PHP suggest.
Also because calculations are impossible before 1970.

**Comment by markstory** [comment]
@mlingureanu We did exactly that for 3.x.

**Comment by bancer** [comment]
> @mlingureanu We did exactly that for 3.x.

@markstory Can that be backported from 3.x to 2.x?

**Comment by markstory** [comment]
@bancer Not without breaking compatibility.

**Comment by jimgwhit** [comment]
I truly try hard not to get upset, I really do, but what is wrong with just formatting the date as needed like:
```
echo "<td style=\"width:40px;\">" . date_format($row->lastedit, 'Y-m-d H:i:s') . "</td>";
```
Or whatever format is needed.

**Comment by mlingureanu** [comment]
@jimgwhit your examle code should look like this:
echo "<td style=\"width:40px;\">" . date_format(date_create($row->lastedit), 'Y-m-d H:i:s') . "</td>";

**Comment by markstory** [comment]
Closing as this has been fixed in 3.x and is unlikely to be fixed in 2.x as the risk of breaking backwards compatibility it high and the number of impacted installations is relatively small.

**Comment by ravage84** [comment]
One could use [Chronos](https://book.cakephp.org/3.0/en/chronos.html), a CakePHP 3.x component. It has no conflicting dependencies, so it can be used in CakePHP 2.x applications, too.
