### ISSUE TITLE
eventManager() instead of getEventManager()

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#9104]
Hi,
I just found a typo here: http://book.cakephp.org/3.0/en/development/testing.html#testing-events

`getEventManager()` does not exists. Use `eventManager()` instead.

**Comment by dereuromark** [comment]
Yeah, getEventManager() is Cake4 ;)

**Comment by markstory** [comment]
This issue was moved to cakephp/docs#4172
