### ISSUE TITLE
CakeResponse::header(): when $value is NULL, it tries to parse the header from $header, even if it's not there

### ISSUE THREAD

**Issue by dvlprs** [cakephp/cakephp#9106]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.7.5

### What you did

        $this->response->header('Access-Control-Allow-Origin', env('HTTP_ORIGIN'));

### Expected Behavior
Issue a header with the value provided (if any) or otherwise do nothing.

### Actual Behavior
When `env('HTTP_ORIGIN')` is `NULL` it assumes the actual header value is in the first argument and [tries to parse it](https://github.com/cakephp/cakephp/blob/2.next/lib/Cake/Network/CakeResponse.php#L591), which results in the following error: 

> Notice (8): Undefined offset: 1 [CORE/Cake/Network/CakeResponse.php, line 581]

**Comment by markstory** [comment]
Closing as a pull request is open now. You should be aware that `2.7.*` is not a maintained branch, and that any fixes made will be applied to `2.8.*`
