### ISSUE TITLE
return true when roleback is execute

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9109]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
return incorrect  boolean value

### Expected Behavior

`replaceLinks()` should be return `false` when transaction run roleback
but return `true`

### Actual Behavior
sample:
```
//tags table
	    public function buildRules(RulesChecker $rules)
    {
    	$rules->add(function ($entity, $options) {return false;});
        return $rules;
    }
//controller
		$tag1 = $this->Tags->newEntity();
		$book = $this->Bookmarks->newEntity();
		$book->title="sample";
		$this->Bookmarks->save($book);
		debug($this->Bookmarks->Tags->replaceLinks($book,[$tag1])); //return true
```

**Comment by markstory** [comment]
Are you creating new linked tags in this situation? Based on the example you've provided its not clear. If you're linking to existing tags, the current behavior of  `replaceLinks()` is correct, as only new linked entities are saved.

**Comment by saeideng** [comment]
i removed line
`$rules->add(function ($entity, $options) {return false;});`
and move it into BookmarksTagsTable
and use existing tags 
but  `replaceLinks()` return true even if roleback is run
please see
```
// BookmarksTagsTable
    public function buildRules(RulesChecker $rules)
    {
    	$rules->add(function ($entity, $options) {return false;});
        $rules->add($rules->existsIn(['bookmark_id'], 'Bookmarks'));
        $rules->add($rules->existsIn(['tag_id'], 'Tags'));
        return $rules;
    }
// controller
		$tag2 = $this->Tags->get(10);
		$book = $this->Bookmarks->newEntity();
		$book->title="sample";
		if($this->Bookmarks->save($book)){
			debug($this->Bookmarks->Tags->replaceLinks($book,[$tag2]));//return true		
		}
```

**Comment by markstory** [comment]
Pull request up for the situation where saving a new linked entity fails.
