### ISSUE TITLE
associated=>false in default behavior saving in v3.3

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9110]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

hello
if possible
please make associated=>false for default behavior
`$this->table->save($entity);` default  just save on one table
and will no needed to set `associated=>false`

**Comment by htstudios** [comment]
* Isn't that the default behavior?
* if not this change is non-BC and thus could only go into 4.x

**Comment by saeideng** [comment]
> Isn't that the default behavior?

> 

no
default behavior : data saved on associated tables

**Comment by ADmad** [comment]
We can't break backwards compatibility in 3.x.

You can make an AppTable and override save()  to change defaults and all your tables extend AppTable.
