### ISSUE TITLE
email validation rule seems to reject correct emails

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/cakephp#9111]
This is a (multiple allowed):
* [x] bug ? maybe
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9.
* Platform and Target: MySQL 5.5, PHP 5.6, unknown apache version .

### What you did
EntitiesTable.php:

	public function validationDefault(Validator $validator) {
		$validator
			->add('email', 'valid', [
				'rule' => 'email', 'message' => __("This email is not valid.")
				])
			;

		return $validator;
	}

### Expected Behavior
don't reject email given below.

### Actual Behavior
Hello,

I currently have few emails, successfully verified by verify-email.org, which are rejected by the validation rule.

Between others:

tourisme.coeurmedoc@orange.fr
info@parc-landes-de-gascogne.fr
office-tourisme.soule@wanadoo.fr

Any idea?

**Comment by antograssiot** [comment]
@2ndGAB It's pretty strange because these tests passes as expected.
```
$this->assertTrue(Cake\Validation\Validation::email('tourisme.coeurmedoc@orange.fr'));
$this->assertTrue(Cake\Validation\Validation::email('info@parc-landes-de-gascogne.fr'));
$this->assertTrue(Cake\Validation\Validation::email('office-tourisme.soule@wanadoo.fr'));
```
Don't you have a whitespace or something ?

**Comment by 2ndGAB** [comment]
Thanks @antograssiot I'm going to verify it.

**Comment by 2ndGAB** [comment]
@antograssiot You were rigth but in fact the reported error didn't concerned the one displayed.
Sorry.

**Comment by antograssiot** [comment]
No problem.
