### ISSUE TITLE
4.x non-BC: Table::save(): 'associated' => false instead of associated => 'true'

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#9113]
This is a (multiple allowed):
* [x] enhancement
* [x] deprecation

* CakePHP Version: 4.x

### What you did
In current 3.x book it is said that first level associations, where entities are dirty, are being saved automagically. In the 3.x api it says all associations, where entities are dirty, are being saved automagically. 
I did fix the docs here: https://github.com/cakephp/docs/issues/4174

### Expected Behavior
Table::save() call has the option ```'associated' => true``` by default.

### Actual Behavior
Table::save() call should have the option ```'associated' => false``` by default.

### Compatibility
Can only be done for 4.0 release if desired. Non-BC.

Ref: https://github.com/cakephp/cakephp/issues/9110#issuecomment-232322199

**Comment by markstory** [comment]
Why?

**Comment by htstudios** [comment]
Out of the box security? Explicit interface?
The book has only examples that are explicit.

**Comment by markstory** [comment]
How is disabling association saving more secure? If you've marshalled data by hand, or by using the `newEntity()` or `patchEntity()` methods, you should have a very good idea of what associations could have been changed.

**Comment by ionas** [comment]
So to sum it up, is this correct?:
* `patchEntity()` / `newEntity()` are behaving strictly out of the box, e.g. if you don't specify associated then that data won't get marshaled.
* `save()` is behaving relaxed out of the box, e.g. whatever nested associations the entity comes along with will be saved by default.

> *When building forms that save nested associations, you need to define which associations should be marshaled:*
src: http://book.cakephp.org/3.0/en/orm/saving-data.html#converting-request-data-into-entities

If above list points are true (*please confirm*), then I will close this ticket and improve the docs to state where and how to be strict @ `save()`.

**Comment by markstory** [comment]
That all sounds correct to me.

**Comment by ionas** [comment]
But `save()` only saves first level out of the box, so its "semi-relaxed". 
So I **cannot** add an easy passage to the docs saying:
* patch/newEntity is strict: it requires you to specifically explain which associations to mashal along
* save() is relaxed (or strict as well) always (or never) saves any nested associations.

... because the feature behaves inconsistent and semi-magical.

I'll close this as @ADmad already closed the previous ticket:

### Note
I still feel for 4.x' `save()` should have `'associated => false'` as the default option and allow `'associated'` to be set to specific (nested) entities **or** set to `true` to save everything, **because the marshaler already requires you to be specific**. If someone of the of the core team agrees, feel free to re-open.

e.g it should behave EXACTLY like the API is currently (wrongly) saying it does - from the docblock of Cake\ORM\Table class:
>       If true it will save all associated entities as they are found
    *   in the passed `$entity` whenever the property defined for the association
    *   is marked as dirty. Associated records are saved recursively unless told
    *   otherwise. If an array, it will be interpreted as the list of associations
    *   to be saved. It is possible to provide different options for saving on associated
    *   table objects using this key by making the custom options the array value.
    *   If false no associated records will be saved. (default: true)
