### ISSUE TITLE
Add new method cartesianProduct to collection class 

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#9121]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.0

### What you did
Add an new method **cartesianProduct** to collection class, which will perform a cartesian product to the collection.

e.g.

 ```
      $items = [
            ['A', 'B', 'C', 'D'],
            [1, 2, 3, 4]
      ]
     
      $cartesianProduct = (new Collection($items))->cartesianProduct()->toList();
```
     
Returns results as shown below
```
        [
          ['A', 1],
          ['A', 2],
          ['A', 3],
          ['A', 4],
          ['B', 1],
          ['B', 2],
          ['B', 3],
          ['B', 4],
          ['C', 1],
          ['C', 2],
          ['C', 3],
          ['C', 4],
          ['D', 1],
          ['D', 2],
          ['D', 3],
          ['D', 4],
      ]
```

This is a very handy method for processing array data.

**Comment by ionas** [comment]
Maybe it would be cool to have it take an optional callable, if that that would specify what each element returns (like a multiplication of both, a list of both (this example) etc. etc).

**Comment by lorenzo** [comment]
Would you like to implement it?

**Comment by dilab** [comment]
Yes. I would like to implement it. 

If you think this is a valid feature.

**Comment by lorenzo** [comment]
@dilab I think it is a valid feature, it would probably make more sense if you can pass a $filter argument, being a closure you can use for filtering in the same loop the final result.

**Comment by dilab** [comment]
@lorenzo Sure.

**Comment by hakermania** [comment]
How should this work for multidimensional arrays?

**Comment by markstory** [comment]
Closing as there is a pull request open now.
