### ISSUE TITLE
Validation rule url() doesn't validate localhost

### ISSUE THREAD

**Issue by chey** [cakephp/cakephp#9123]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: PHP 5.6.23

### What you did
Created a model with a field that uses the **url()** validation rule.

### Expected Behavior
Expected this URL to be valid: **http://localhost**

### Actual Behavior
Validation invalidates the url: http://localhost

As a side note **http://127.0.0.1** does validate and is a temporary workaround.

**Comment by thinkingmedia** [comment]
Don't use localhost. That is not a valid domain identifier.  A domain has to have at least one top level domain (i.e. com, net, info, org).

Add a fake DNS entry for your workstation

- on linux, `/etc/hosts`
- on Windows, `/windows/system32/drivers/etc/hosts`

Add something like

```
127.0.0.1 cakephp.local
```

I use a top `.local` for all my localhost routed projects.

**Comment by ADmad** [comment]
As @thinkingmedia said "localhost" is not a valid domain identifier and hence it won't validate.
