### ISSUE TITLE
$paginate not respected on 2.8.5

### ISSUE THREAD

**Issue by nicolabeghin** [cakephp/cakephp#9131]
This is a:
* [x] bug

* CakePHP Version: 2.8.5
* Platform and Target: Mac OSX 10.11.5

### What you did
very basic controller
```php
<?php
App::uses('AppController', 'Controller');
/**
 * Brands Controller
 *
 * @property Brand $Brand
 * @property PaginatorComponent $Paginator
 */
class BrandsController extends AppController {

	public $paginate = array(
	    'Brand' => array(
	        'limit' => 100
	    )
	);
	
/**
 * Components
 *
 * @var array
 */
	public $components = array('Paginator');

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Brand->recursive = 0;
		$brands = $this->Paginator->paginate();
		$this->set(array('brands' => $brands, '_serialize' => array('brands')));
	}
}
?>
```

### Expected Behavior
It seems that in 2.8.5 `Controller->$paginate` variable is not respected anymore. 
```sql
SELECT `Brand`.`id`, `Brand`.`name`, `Brand`.`logo_path`, `Brand`.`created`, `Brand`.`modified` FROM `fashionable`.`brands` AS `Brand` WHERE 1 = 1 LIMIT 100
```

### Actual Behavior
```sql
SELECT `Brand`.`id`, `Brand`.`name`, `Brand`.`logo_path`, `Brand`.`created`, `Brand`.`modified` FROM `fashionable`.`brands` AS `Brand` WHERE 1 = 1 LIMIT 20
```

I was able to get `$paginate` respected by adding in all my controller methods:
```php
public function index() {
    $this->Paginator->settings = $this->paginate;
```

**Comment by markstory** [comment]
In order for that property to be used you need to use `$this->paginate()`

**Comment by nicolabeghin** [comment]
hi @markstory has this been fixed in 2.8.6? It doesn't seem to me..

```php
$this->Paginator->settings = $this->paginate;
```

is always needed

**Comment by dereuromark** [comment]
I think you are still confusing the two ways.
Either 

- you use Paginator->settings and $this->Paginator->paginate()
- you use $paginate and $this->paginate()

Never ever mix them and you will be fine.

**Comment by nicolabeghin** [comment]
Hi @dereuromark thanks a lot for your fast reply.
I made sure to use the `$this->paginate()` and `$this->paginate` variable, that's why I reopened the ticket. Hope I'm missing something.. 

```php
public $paginate = array(
    'Brand' => array(
        'limit' => 100
    )
);

public function index() {
	$this->Brand->recursive = 0;
	$brands = $this->paginate();
	$this->set(array('brands' => $brands, '_serialize' => array('brands')));
}
```

leads to
```sql
SELECT `Brand`.`id`, `Brand`.`name`, `Brand`.`logo_path`, `Brand`.`created`, `Brand`.`modified` FROM `fashionable`.`brands` AS `Brand` WHERE 1 = 1 LIMIT 20
```

**Comment by dereuromark** [comment]
Did you try
```
public $paginate = array(
    'limit' => 100
);
```

**Comment by nicolabeghin** [comment]
I tried that as well, in order to exclude any other stupid mistake of mine as before, but it didn't change the output (LIMIT 20, as per default cakephp pagination)
