### ISSUE TITLE
MySQL transactions do not work in a cluster

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9132]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: Apach2.4, MySQL 5.7, Ubuntu, PHP7

### What you did

Ran multiple nodes in a cluster with all nodes running the same CakePHP app, and same database configuration to one MySQL server.

Each node performed SQL updates using transactions.

### Expected Behavior

There should be no collisions between the nodes in the cluster. Transactions should prevent a database record from being updated before another transaction has finished.

### Actual Behavior

I've discovered this evening that MySQL transactions are not supported across multiple connections. A transaction on one node does not stop another node from updating the same record.

I'm actually shocked to discover this the hard way, and left kind of stuck on how to fix it.

I've found the following links to support the above.

http://stackoverflow.com/questions/2495628/mysql-transactions-across-multiple-threads

I found this in the MySQL manual

> MySQL supports local transactions (within a given client session) through statements such as SET autocommit, START TRANSACTION, COMMIT, and ROLLBACK. See Section 13.3.1, “START TRANSACTION, COMMIT, and ROLLBACK Syntax”

So it's clearly a documented limitation.

What I have found is something called "XA Transaction"

http://dev.mysql.com/doc/refman/5.7/en/xa.html

I search the CakePHP source code for the phrase but found nothing.

**Comment by htstudios** [comment]
Take a look at https://www.percona.com/live/mysql-conference-2013/sites/default/files/slides/mysql-multi-master-state-of-art-2013-04-24_0.pdf esp. Galera.

**Comment by lorenzo** [comment]
Not a CakePHP issue. Please refer to MySQL documentation.

The best piece of advice I can give you is to avoid save/delete operations that involve multiple different connections. For example, when you plan to save, do all the reads and inserts in the master server, instead of the replicas.

**Comment by thinkingmedia** [comment]
Just to clarify. I have only one MySQL server and one database (no clustering or replication), but I have several Ubuntu servers connecting to that server and performing work via CakePHP shells.

Each shell is inserting and updating data on that MySQL server. I had assumed that using transactions would prevent collisions in this scenario, but that's not the case.

I think at this stage my quickly fix would be to add my own ORM driver that uses XA transactions instead of regular transactions.

Is this kind of driver something that would make for a good pull request? or is this going to be one of those things that requires to many unit tests to get the PR accepted?

**Comment by thinkingmedia** [comment]
Does the ORM support locking of SELECT queries?

http://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html

Maybe this will resolve most of my issues if I could do something like this.

```
    $this->Model->transactional(function() {
                $record = $this->Model->find()->where(...)->lock()->first();
                /// do work
               $this->Model->save($record);
    });
```

According to the MySQL documentation. If a `SELECT` uses `LOCK IN SHARE MODE` it sets write locks on a per row bases, and prevents other transactions from updating that row.

I think this will fix my issues, but I don't think it's possible to append `LOCK IN SHARE MORE` to the query using the ORM the way that it is. 

Or am I wrong?

**Comment by lorenzo** [comment]
`$query->epilog('LOCK IN SHARED MODE')`

**Comment by thinkingmedia** [comment]
@lorenzo Thank you much!

**Comment by lorenzo** [comment]
No problem.... but please not that locking the rows inside a transaction has no effect! It will not help with the multiple connections problem

**Comment by thinkingmedia** [comment]
@lorenzo are you sure? :cry: 

What about `FOR UPDATE` which locks the row from reads and write.

Are you saying that the locking is only relative to the current connection?

**Comment by thinkingmedia** [comment]
I can connect to two different nodes on the network and manually test this locking via the command line. In one terminal I'll start a locked transaction, and another I'll try to write to the same row. If this works the second will be block.

**Comment by htstudios** [comment]
If you find a simple way to lock read and write via different connections (e.g web apps, 2 shell calls etc) then at least the docs/book could benefit from that. I am - possibly wrong though - also under tge assumption that transactions would block each other when fired say from the same app but via shell and via web once. That is wrong? If it is I'd live docs/book about it @lorenzo.

**Comment by thinkingmedia** [comment]
FYI:

I've decided to wrap my transaction with `LOCK TABLES` and `UNLOCK TABLES`. This appear to be the standard solution to my problem. It just adds more work for me as I have to track which tables need read or write access. So I'l be writing some helper functions and such.

With all the "rules" and "associations" that are used in the backend by the ORM. There are a lot of tables that get *touched* during queries automatically. A simple save can hit several tables to validate rules.

It would be nice to discuss how locking could be handled by the ORM. There would be a need to pre-process a save or update so that a list of tables can be locked. (i.e. all the event listeners need to report what they'll need).

MySQL requires that you lock all the tables in one `LOCK TABLES` call. So that's kind of a pain for an ORM that is so automated.
