### ISSUE TITLE
2.x - ClassRegistry::init() returning AppModel

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#9133]
I have found some unwanted behaviour - not sure if this is a bug or if I am doing something incorrectly.

I am trying to debug a problem and found that `$this->loadModel("SomeModel")` in a controller was setting an instance of `AppModel` rather than `SomeModel` as `$this->SomeModel`. After some debugging, I realized that this seems to happen due to the way that `ClassRegistry::init()` checks for duplicate instances before returning.

The duplicate of `SomeModel` was created by a find with a contain. In this instance, `SomeModel` is a join table for a HABTM relationship.

Specifically:
```php
$data = $this->Project->find("first", [
    "conditions" => $conditions,
    "contain" => ["User"],
]);

//access join table directly
$this->loadModel("ProjectsUser");

var_dump(get_class($this->ProjectsUser));
//AppModel
```

This only happens when done after a find with contain and as far as I can tell, only with join tables for HABTM.

**Comment by markstory** [comment]
This is not a bug. This happens when a filename or classname doesn't exist or is not in the expected/required location.

**Comment by garethellis36** [comment]
In the example above, the class `ProjectsUser` does exist and is in `app/Model/ProjectsUser.php`. It only happens if you call `loadModel()` after doing a find with a contain - it looks like the ORM loads `AppModel` for the join table.

**Comment by garethellis36** [comment]
Hopefully this repo demonstrates the bug:
https://github.com/garethellis36/cakephp-habtm-loadmodel-bug

**Comment by biesbjerg** [comment]
I think you need to use 'with' key to specify that ProjectsUser class should be used for join table.

If you don't cake will use a generic AppModel when doing a find and it will probably cache it in ClassRegistry, which is why you get AppModel after a find.

**Comment by biesbjerg** [comment]
Maybe AppModel instances shouldn't be cached in ClassRegistry though?

**Comment by garethellis36** [comment]
Either way, IMO the behaviour should be consistent, i.e. `ClassRegistry::init("SomeJoinTableModelClass")` should always return the same thing.

**Comment by ADmad** [comment]
There are many caveats like this one in the 2.x ORM which can't be changed as people might be relying on such behavior. This is why the ORM was rewritten in 3.x :)
