### ISSUE TITLE
httpoxy vulnerabilty in CakePHP 2.x

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#9136]
A new vulnerability has surfaced called **httpoxy**:

https://httpoxy.org

I want to use this issue here to discuss whether and to what extend CakePHP **2.x** is vulnerable.
If it vulnerable, what can be done against the vulnerabilty.

**Comment by dereuromark** [comment]
Wouldnt have one ticket sufficed? We can always backport the solution once fixed in master.

**Comment by ravage84** [comment]
The code for 2.x is quite different, especially now as CakePHP 3.x supports PSR-7, which could have an impact.
So, either one main version could be affected, while the other is not, or both are affected but the prevention could differ.

A ticket is closed fast, anyway :smirk_cat:

**Comment by ceeram** [comment]
Cake 2.x is not vulnerable for httpoxy

2016-07-19 12:04 GMT+02:00 Marc Würth <notifications@github.com>:
