### ISSUE TITLE
httpoxy vulnerabilty in CakePHP 3.x

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp#9137]
A new vulnerability has surfaced called **httpoxy**:

https://httpoxy.org

I want to use this issue here to discuss whether and to what extend CakePHP **3.x** is vulnerable.
If it vulnerable, what can be done against the vulnerabilty.

**Comment by lorenzo** [comment]
As you can read in the page, the solution is not in PHP, but in the web server

**Comment by ceeram** [comment]
cake 3.x is not vulnerable to httpoxy.

Ofcourse applications built on top of cakephp can be, but core code does
not require any changes.
As mentioned before and also on httpoxy, it would be best handled as soon
as possible in the request, eg HAProxy, Varnish, Webserver.
Guzzle client for instance did a fix for httpoxy, as they were reading the
HTTP_PROXY value. They now only do so when running as cli and no longer
when running in web. But better safe then sorry and ensure at earlier stage
that the header is either removed or the request is blocked entirely.

2016-07-19 12:13 GMT+02:00 José Lorenzo Rodríguez <notifications@github.com>
:

**Comment by thinkingmedia** [comment]
I just breezed over the page quickly, but can this be fixed by scripting `http_proxy` headers in the `.htaccess`.

Maybe that could be added to the app template project?

**Comment by ravage84** [comment]
@thinkingmedia I was also considering opening a PR to the app repo, which adds the following (commented out) to the ``.htaccess``:

````
# Uncomment to prevent the httpoxy vulnerabilty
# https://httpoxy.org/
#<IfModule mod_headers.c>
#   RequestHeader unset Proxy
#</IfModule>
````

**Comment by thinkingmedia** [comment]
@ravage84 yes, please make a PR for that. I can not see why anyone would not accept it and you deserve credit for finding this.

I do think there are Cake apps out there running behind proxies or at least on dev machines with proxies. I don't think these are at risk, but maybe more people who know about this issue and having it in the app template is a good way to inform people.
