### ISSUE TITLE
Cakephp 3 - limit () and contained model

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#9141]
I have two models, named Post and Comment, which are linked by Post hasMany Comment and Comment belongsTo Post.
I want to fetch all posts with the first five comments each. I would use this code:

> $this->Posts->find('all')
>      ->contain([
>         'Comments' => function($q) {
>             return $q
>                 ->order('created ASC')
>                 ->limit(5);
> }
> ]);

This works incorrectly with the limit(). Why?

**Comment by lorenzo** [comment]
Please read the answer to this question:

http://stackoverflow.com/questions/30241975/how-to-limit-contained-associations-per-record-group

**Comment by lupuswwww** [comment]
http://stackoverflow.com/questions/30241975/how-to-limit-contained-associations-per-record-group
This example is quite unclear.

**Comment by lupuswwww** [comment]
For a few days I am suffering with this problem and I can not solve it.
I saw the link you sent.
When I implemented any of the three offered solutions always get only ONE contained a record (because of relation 'hasOne'). 
Please tell me at least whether it is possible to have more than one contained record  (Yes or No)?
In my case required the first 5. Thanks.

**Comment by ADmad** [comment]
@lupuswwww This is not a help forum. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by lorenzo** [comment]
@lupuswwww yes, it is possible, as shown in the link I sent you. Please join us in the slack channel and we can guide you there
