### ISSUE TITLE
Cakephp3 Retrieving Data From DB with Emoji Utf-8 encoded doesn't get decoded properly

### ISSUE THREAD

**Issue by avneeshroks** [cakephp/cakephp#9142]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.1

### What you did
I Have a database (MySql) and with the collate utf8mb4_unicode_ci.
there is one 'about' column, data in that column can contain emoji.

### Expected Behavior
When i retrieve this data using CakePHP 3 the decoding of emojis should be done properly and in the view is i should be able to see emoji character.

### Actual Behavior
The problem is i'm not able to see the correct emoji drawn in view. instead some jibrish charecters are coming.
Also If, i try to retrieve it from CakePHP2 application it's getting drawn in correct format. Also i tried with core mysqli connection that too is working fine.

But while i try to retrieve this date from CakePHP 3 app i'ts not getting drawn. Maybe some internal decoding while cakephp receiving data from MySql. But I'm not able to fix it. 

The MySql Dump: 

```sql
`CREATE TABLE IF NOT EXISTS `users` (
`id` int(11) NOT NULL,
`username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
`password` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
`about` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
`created` datetime DEFAULT NULL,
`modified` datetime DEFAULT NULL,
`users_like_count` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=390 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`
```

```sql
`INSERT INTO `users` (
`id`,
`username`,
`first_name`,
`last_name`,
`email`,
`password`,
`about`,
`created`,
`modified`,
) VALUES(
32,
'Xyz',
'Abc',
'das',
'xyz@yopmail.com',
'affd7e60320f930a9e0a43434914746e184db9',
'level Ã¢Â¬âÃ ̄Â ̧Â Ã°Å ̧â   Ë  .        ',
'2016-03-29 13:49:22',
'2016-04-11 11:30:41'
);`
```

**Comment by lorenzo** [comment]
Did you set the `'charset'` configuration key to `utf8mb4` in the `Datasouces` config?

**Comment by avneeshroks** [comment]
@lorenzo : Yes i am currently using this Datasource - 

`'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => 'localhost',
            'username' => 'root',
            'password' => 'root',
            'database' => 'test',
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATABASE_URL', null),
        ],`

Also tried with `'encoding' => 'utf8',`

**Comment by dereuromark** [comment]
utf8 != utf8mb4

**Comment by avneeshroks** [comment]
@lorenzo : Yes i am currently using this Datasource -

'default' => [ 'className' => 'Cake\Database\Connection', 'driver' => 'Cake\Database\Driver\Mysql', 'persistent' => false, 'host' => 'localhost', 'username' => 'root', 'password' => 'root', 'database' => 'test', 'encoding' => 'utf8mb4', 'timezone' => 'UTC', 'flags' => [], 'cacheMetadata' => true, 'log' => false, 'quoteIdentifiers' => false, 'url' => env('DATABASE_URL', null), ],

Also tried with 'encoding' => 'utf8',

either of those doesn't work.

**Comment by lorenzo** [comment]
then that's all you need. Please verify that your data was saved correctly and that your tables are also in the right collation. I also use this configuration successfully with cake 3

**Comment by avneeshroks** [comment]
@lorenzo : Sorry but, I verified the data which is being saved into database. And the data looks fine. With the same data if i try to retrieve from CakePHP 2.x application it's getting retrieved correctly. not sure why it's not happening with CakePHP 3.x ..

**Comment by lorenzo** [comment]
Is it possible for you to create a small application with a SQL file that we can use to reproduce the issue? You could attach the zip file with this small application for us to test

**Comment by markstory** [comment]
I wasn't able to reproduce this in the demo bookmarker app. I did the following changes first:

1. Update datasource encoding to `utf8mb4`
2. Ensure table charset and column character sets were all utf8mb4.

![screen shot 2016-08-01 at 22 21 30](https://cloud.githubusercontent.com/assets/24086/17315014/777c95e6-5836-11e6-9810-113e319ecd03.png)
