### ISSUE TITLE
Fix CakePHP 2.8.5 Class Hash, Warning, not valid Argument passed is Array()

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#9144]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.5
* Platform and Target: PHP 5.6, Linux

### Description:
The problem that Hash Class and its methods, does not verify if the past is an array type; if it is other than a type Array (), it would have to return an Array () empty and not display the error warning.

### What you did:
Test code easy to  Hash::extract(), no valid only type Array, fix var type STRING, NULL, Int Object, etc,

```
class TestController extends AppController
{
........
   public function myTest()
   {

     debug(Hash::extract('', '{n}.user_id')); // Fix Warning
     debug(Hash::extract(null, '{n}.user_id')); // Fix Warning
     debug(Hash::extract(666, '{n}.user_id')); // Fix Warning
     // Return NULL $this->request->data('Model.testNotExistData');
     debug(Hash::extract($this->request->data('Model.testNotExistData'), '{n}.user_id')); // Fix Warning
     
     // Valid not show Warning
     debug(Hash::extract(array(), '{n}.user_id')); // OK not Warning
     debug(Hash::extract(array(1,2,3,4), '{n}.user_id')); // OK not Warning
     debug(Hash::extract(array(1,'',3,array()), '{n}.user_id')); // OK not Warning

     // Etc.. Ok only Argument 1 passed is Array()

     exit('End Test');
   }
.........
}
```

### Expected Behavior
Not show "Warning" only return array()

```
/app/Controller/TestController.php (line 327)
array()
```

### Actual Behavior
```
Warning (4096): Argument 1 passed to Hash::extract() must be of the type array, string given, called in /var/www/TestController.php on line 327 and defined [CORE/Cake/Utility/Hash.php, line 102]

/app/Controller/TestController.php (line 327)
array()
```

**Comment by EOM** [comment]
I understand that the solution is that I validate it before passing array.
But is not it better that can do hashing methods ..?
Because if you have what methods inside, I do not have to make repeated forever validate code if it is an array. Since this is very common to happen
Example:
```
// Return NULL  Get data by $this->request->data('Model.testNotExistData');
Hash::extract ($this->request->data('Model.testNotExistData'), '{n} .user_id'); // Fix Warning
```

**Comment by EOM** [comment]
Possible solution, which would have to be within each method of the Hash class.
Example:

        //$v = null;
        //$v = '';
        //$v = 124;
        $v = $this->request->data('');
        $test = (is_array($v)===true)?$v:array(); // <== Solution insert code in methods Hash, instead of making method (array $ data, ...){}
        exit(debug(Hash::extract($test, '{n}.senasa_pedidos_id')));


Example Change in Hash.php
Link: https://github.com/cakephp/cakephp/pull/9146

**Comment by markstory** [comment]
We're not going to remove the warnings. You'll need to check your arguments.
