### ISSUE TITLE
Unit testing post request with requireSecure

### ISSUE THREAD

**Issue by davo3** [cakephp/cakephp#9145]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: PHP 5.6.23, Apache/2.4.10, Debian 8.3

### What I did
I have standard articles controller - with this function (no real use - just for demo)
```
public function add()
{
    return $this->redirect('/Articles/index');
}
```

ArticlesControllerTest with this function (both Csrf and Security Components are enabled in my app)
```
    public function testAdd()
    {
        $this->enableCsrfToken();
        $this->enableSecurityToken();
        
        $data = [
            'title' => 'test title',
            'slug' => 'test slug'
        ];
        
        $this->post('/articles/add', $data);
        $this->assertRedirect('/Articles/index');
    }
```

### Expected Behavior
For the test do succeed.

### Actual Behavior
When I have this line in AppController `$this->Security->requireSecure();`, the test fails by `No location header set.`. If I comment the `requireSecure` line the test succeeds.

When I try giving the full path in `testAdd` line
```
$this->post('https://example.com/articles/add', $data);
```

Irrelevant from `requireSecure` is commented or not the test always fails with same error message as above.

**Comment by markstory** [comment]
You have to stub the `HTTPS` environment variable which the `requireSecure()` method relies on. See the [request configuration]http://book.cakephp.org/3.0/en/development/testing.html#setting-up-the-request) and [stubbing authentication](http://book.cakephp.org/3.0/en/development/testing.html#testing-stateless-authentication-and-apis) sections for how to setup the request to stub environment variables.

**Comment by davo3** [comment]
@markstory , thanks a lot, got it. I was stuck on this for a few hours, maybe it is worth adding at least one sentence into docs under the section concerting the security component ?
http://book.cakephp.org/3.0/en/development/testing.html#testing-actions-protected-by-csrfcomponent-or-securitycomponent - as because of the same thing I was getting the "black-holed" error as well.
