### ISSUE TITLE
cakephp 2 - ClassRegistry::init takes plugin syntax, ignores it for loading the model

### ISSUE THREAD

**Issue by AshleyPinner** [cakephp/cakephp#9147]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.5
* Platform and Target: N/A

### What you did
To isolate this issue, I installed a fresh cakephp 2.8 via composer, baked a skeleton project, then added in two plugins:

`Cat` & `Dog`

I gave each plugin a `Model` folder, gave them both their own `CatAppModel`/`DogAppModel` and then gave them both a `Pet` model which looked like this:

Cat:
```
<?php

class Pet extends CatAppModel {

    public function sound() {
        return 'meow';
    }
}

```

Dog:

```
<?php

class Pet extends DogAppModel {

    public function sound() {
        return 'woof';
    }
}

```

Then I did the following in the `PagesController`:

```
		debug('Starting test, dumping map');
		debug(ClassRegistry::keys());
		debug('Loading the cat model and meowing');
		debug(ClassRegistry::init('Cat.pet')->sound());
		debug('dumping the keys');
		debug(ClassRegistry::keys());
		debug('Removing Cat model');
//sidenote, I'm aware of the bug here, so I'm unloading what the bug loads
		ClassRegistry::removeObject('pet'); 
		debug(ClassRegistry::keys());
		debug('Loading the dog model and woofing');
		debug(ClassRegistry::init('Dog.pet')->sound());
		debug('dumping the keys');
		debug(ClassRegistry::keys());
		debug('Removing Dog model');
		ClassRegistry::removeObject('pet');
		debug(ClassRegistry::keys());
```

### Expected Behavior
I would expect the following output:

```
'Starting test, dumping map'
array()
'Loading the cat model and meowing'
'meow'
'dumping the keys'
array(
	(int) 0 => 'cat_pet'
)
'Removing Cat model'
array()
'Loading the dog model and woofing'
'woof'
'dumping the keys'
array(
	(int) 0 => 'dog_pet'
)
'Removing Dog model'
array()
```

### Actual Behavior

```
'Starting test, dumping map'
array()
'Loading the cat model and meowing'
'meow'
'dumping the keys'
array(
	(int) 0 => 'pet'
)
'Removing Cat model'
array()
'Loading the dog model and woofing'
'meow'
'dumping the keys'
array(
	(int) 0 => 'pet'
)
'Removing Dog model'
array()
```

I even tried it with aliases, using these two lines to instanciate Cat.pet and Dog.pet:

`debug(ClassRegistry::init(['class'=> 'Cat.pet', 'alias' => 'cat_pet'])->sound());`

`debug(ClassRegistry::init(['class' => 'Dog.pet', 'alias' => 'dog_pet'])->sound());`

(and call `cat_pet`/`dog_pet` in the `removeObject` calls)

The output isn't any different from the above.

The expectation given by ClassRegistry::init accepting plugin syntax is that it honours it and loads the one you logically expect. In this case it's loading the first one it can find, alphabetically, regardless of how you try to specify it.

**Comment by markstory** [comment]
This is not something that can/will be fixed in 2.x. Class names and registry aliases need to be globally unique. There are lots of issues where this is covered #4762 #5039 #8173 #4068

**Comment by AshleyPinner** [comment]
Mm, just for clarification then, the second part about using aliases but it still loading the first one it finds is as expected then? (the aliases get used in the table registry, but they both point to Cat.pet)

**Comment by markstory** [comment]
Yes that is 'expected' for the 2.x model layer.
