### ISSUE TITLE
bin/cake plugin load should support bootstrap_cli.php in addition to bootstrap.php

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/cakephp#9150]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- CakePHP Version: 3.2.12
- Platform and Target: Command line. I am using PHP 5.6.10 (cli) on OS X El Capitan.
### What you did

`$1` in the sample below is the project name passed into my bash script:

```
yes | composer create-project --prefer-dist cakephp/app $1
cd $1
composer require inboxdollars/bats-support dev-master
bin/cake plugin load 'InboxDollars/BatsSupport'
```

where InboxDollars/BatsSupport is the name of my plugin to be loaded via bootstrap.
### Expected Behavior

I am creating a command-line-only CakePHP 3.x project (a microservice). I therefore want the "plugin load" command to modify `config/bootstrap_cli.php` rather than `config/bootstrap.php`. 
### Actual Behavior

`bin/cake plugin load` is handled by cakephp/src/Shell/Task/UnloadTask.php. Its purpose is to add a `Plugin::load` line to your application's bootstrap file:

```
$this->bootstrap = ROOT . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'bootstrap.php';
```

However, your application has two bootstrap files, bootstrap.php and bootstrap_cli.php.

I would like to submit a pull request that
- Creates a command-line option --cli
- When the option is specified, bootstrap_cli.php is modified rather than bootstrap.php

Providing the command-line option makes this change backwards compatible. You need to specify the new command-line option to take advantage of this enhancement.

**Comment by dereuromark** [comment]
I think this is a valuable addition.
But it would also not be too difficult to copy it over manually, and it should work out of the box either way, because the normal one is and should always be loaded prior to the cli custom one.

**Comment by ewbarnard** [comment]
I did not realize that bootstrap.php is always called before bootstrap_cli.php. I think we can close this as unnecessary. I'll look at the CakePHP 3.x book and see if there's a place I can improve the documentation. (I just confirmed for myself that bootstrap.php gets called by bin/cake bake.)

**Comment by ewbarnard** [comment]
Can this be moved to an issue against [Loading Plugins](http://book.cakephp.org/3.0/en/console-and-shells/plugin-shell.html#loading-plugins) ?

I'll add a note to that section (as a pull request against this issue) of the documentation explaining that adding to config/bootstrap.php is sufficient for command-line usage, since the cli calls both bootstrap files. If I was confused, others may benefit from the note.

**Comment by dereuromark** [comment]
I find it quite clear from the code: https://github.com/cakephp/app/blob/master/config/bootstrap.php#L122-L125
cli is only an on top file to further configure etc

**Comment by ewbarnard** [comment]
Mark, you're right. It's also clearly stated at [Bootstrapping CakePHP](http://book.cakephp.org/3.0/en/development/configuration.html#bootstrapping-cakephp) now that I know to look. Do you think there would be value to adding a note under [Loading a Plugin](http://book.cakephp.org/3.0/en/plugins.html#loading-a-plugin), or should we just close this as a non-issue?

**Comment by ADmad** [comment]
Even if a plugin only contains shells I don't think there's any problem loading the plugin in `bootstrap.php`. So this should be closed as non-issue imo.

**Comment by sitedyno** [comment]
I think it's a good idea to allow plugin authors to decide where the load() call is written. If someone does something expensive in their plugin's bootstrap for CLI, you don't want that occurring on web requests. Sure they can check the environment before taking action, but it's still more code run on every request.

**Comment by dereuromark** [comment]
Yeah, --cli param would probably be very easy to add as argument. Feel free to PR it and we can discuss it more concretely then.

**Comment by ewbarnard** [comment]
I'll build a PR against 3.next. I'll include an accompanying enhancement to "Loading a Plugin" docs per this discussion.

**Comment by markstory** [comment]
I think having a `--cli` flag is reasonable. Lets people load the plugin in the CLI context *only* which can be useful.

**Comment by ewbarnard** [comment]
Thanks Mark. It's been years since I did a PR, feels good to get back in the habit! I'm covering both plugin load and plugin unload, and the unit tests, and a brief mention in the book. Expect the PR tomorrow or Monday-ish.

**Comment by markstory** [comment]
@ewbarnard Looking forward to it :smile:

**Comment by dereuromark** [comment]
Me too :)

**Comment by dereuromark** [comment]
@ewbarnard Ping

**Comment by markstory** [comment]
Closing as a pull request is open now.
