### ISSUE TITLE
Paginator page number / jump links don't work for aliased fields.

### ISSUE THREAD

**Issue by ah8r** [cakephp/cakephp#9152]
This is a (multiple allowed):
* [x] bug
* [x] enhancement

* CakePHP Version: 3.2.12
* Platform and Target: Nginx 1.10, MySQL 14.14

### What you did
I am using a find with aliased fields defined in the select() function. I pass this to the paginator directly within the controller, and I set the sortWhitelist array to contain the aliased fields.

```php
// UsersController.php
$users = $this->Users->find('all')->select([
        'name' => 'Users.name',
        'username' => 'Users.username',
        'birthday' => 'Users.birthday',
])
->autoFields(true);

$users = $this->Paginator->paginate($users, [
        'limit' => 10,
        'sortWhitelist' => [
                'name',
                'username',
                'birthday',
        ],
        'order' => [
                'name' => 'asc',
        ],
]);
```

The template outputs Paginator->sort() links for table headings, and number / jump links:

```php
// index.ctp
<th><?= $this->Paginator->sort('name') ?></th>
<th><?= $this->Paginator->sort('username') ?></th>
<th><?= $this->Paginator->sort('birthday') ?></th>
...
<?= $this->Paginator->first('&laquo; first', ['escape' => false]); ?>
<?= $this->Paginator->prev('&lsaquo; previous', ['escape' => false, 'disabledTitle' => '']); ?>
<?= $this->Paginator->numbers(['modulus' => 4]); ?>
<?= $this->Paginator->next('next &rsaquo;', ['escape' => false, 'disabledTitle' => '']); ?>
<?= $this->Paginator->last('last &raquo;', ['escape' => false]); ?>
```

### Expected Behavior
I would expect the sort links, and the page number / jump links to use the aliased field name as part of the URL.

### Actual Behavior
**What works:** The sort links all work correctly and generate URLs using the aliased fields (e.g. /users?sort=name&direction=asc). Sorting works (i.e. the data sorts according to the aliased field), as does the direction of sorting. If I manually add the page number to the URL, that works as well.

**What doesn't work:** The page number / jump links (first, next, prev, last) don't generate the correct URLs, as they all contain the non-aliased fields. For example, instead of sort=name, the URL has sort=Users.name. Due to this behavior, when you click one of these links, the data reverts back to the default sort.

I looked in the PaginatorHelper file, and as far as I can see, the sort() function is passed a value $key which is the aliased field, and this value is passed to the generateUrl() function as part of the $url array. When generating number / jump links, the Paginator doesn't use this value, and instead converts it to one based on the model.

I've written a Helper which extends the PaginatorHelper to fix this problem, and I've marked this as a bug and an enhancement because I'm not sure which one it is.

Given that the Paginator seems to work with aliased fields when URLs are manually generated (or generated as sort links), I would say that this is a bug. However, if the Paginator isn't supposed to be used this way, I think it would be a good enhancement.

**Comment by markstory** [comment]
The jump links should work like other pagination links. I'll see if I can reproduce.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. I've put together a [gist of what I tried](https://gist.github.com/markstory/d344cff70c1a8d21d2f0cf50fd9262ba). What am I missing to reproduce this issue?

> I looked in the PaginatorHelper file, and as far as I can see, the sort() function is passed a value $key which is the aliased field, and this value is passed to the generateUrl() function as part of the $url array. When generating number / jump links, the Paginator doesn't use this value, and instead converts it to one based on the model.

How is sort() related to the page/first/last functions? What does your PaginatorHelper extension look like?

**Comment by ah8r** [comment]
This is very strange. I created a bookmarks table in the database based off your gist and baked the model, etc, then used your controller and template. Everything seemed to work fine.

However when I copied the same code and modified it for my Users model, it reverts back to the behavior I originally reported. I'm not quite sure how that's possible.

>How is sort() related to the page/first/last functions? What does your PaginatorHelper extension look like?

It's related in that when you click a table header to sort, the page/first/last functions need to incorporate that sort into the URL.

My PaginatorHelper extension basically replaces the generateUrl() function and adds the following

```php
$key = isset($this->request->query['sort']) ? $this->request->query['sort'] : '';
```

This value is then merged into the $url array:

```php
$url = array_merge($url, ['sort' => $key], $options);
```

It's certainly not the best solution, but at the moment it works until I can figure out why on earth the page/next/prev links aren't being generated correctly.

**Comment by ah8r** [comment]
Hmm, actually on looking further into this, the Bookmarks example **isn't** working for me. It works only on the "name" sort, but if I try to sort by "created" (I had to change "create" to "created" to avoid a MySQL keyword), and then use the page/next/last links, I get URLs like the following:

/bookmarks?page=2&sort=Bookmarks.created&direction=asc

The code I'm using is identical to yours, except that for changing the "create" alias to "created".

```php
public function index()
    {
        $options = [
            'limit' => 5,
            'sortWhitelist' => ['name', 'created'],
            'order' => ['name' => 'asc']
        ];
        $query = $this->Bookmarks->find()
            ->select(['name' => 'Bookmarks.title', 'created' => 'Bookmarks.created'])
            ->autoFields(true);
        $this->set('bookmarks', $this->Paginator->paginate($query, $options));
        $this->set('_serialize', ['bookmarks']);
    }
```

**Comment by markstory** [comment]
Why are you aliasing fields to the same name as their normal name though?

**Comment by ah8r** [comment]
Honestly, it's more of an aesthetics thing. Rather than having something like "sort=Bookmarks.created" in the URL, you have "sort=created".

**Comment by markstory** [comment]
You are welcome to send a pull request to use the shorter aliased field. But given that aliases _work_ when the names are different from the existing model fields I'm closing this.
