### ISSUE TITLE
Access behavior's variable inside model and events

### ISSUE THREAD

**Issue by davo3** [cakephp/cakephp#9153]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: PHP 5.6.23, Apache/2.4.10, Debian 8.3

### What you did
I have a usual Behavior with following content
```
namespace App\Model\Behavior;

use Cake\ORM\Behavior;

class MyBehavior extends Behavior
{

    public $myVar = 'my var';
    
    public function myFunction()
    {
        return 'smth';
    }
}
```

Suppose this behavior is added into `Users` model. In the model's before find

```
public function beforeFind(Event $event, Query $query, \ArrayObject $options, $primary)
{
    ...
}
```

Putting `debug($this->myFunction());die;` it outputs the `smth` es expected. However putting `debug($this->myVar);die;` throws exception
```
 Table "App\Model\Table\UsersTable" is not associated with "myVar" 
```

So, it "treats" the behavior's variable as association. 

https://github.com/cakephp/cakephp/blob/3.2.12/src/ORM/Table.php#L1970

**Comment by saeideng** [comment]
this is expected behavior 
you can just access to Methods , and Define  Event and Finders

**Comment by markstory** [comment]
Properties are not proxied to behaviors, and more importantly shouldn't be. The code is working as it should.
