### ISSUE TITLE
installer.php setSecuritySalt() entropy

### ISSUE THREAD

**Issue by 68b32** [cakephp/cakephp#9155]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12

The installer script used by composer sets CakePHP's SECURITY_SALT using 

`hash('sha256', $dir . php_uname() . microtime(true));`

Since the comment in `config/app.php` says

`  * The salt value is also used as the encryption key.`
`  * You should treat it as extremely sensitive data.`

the input into the hash function should be more random than it is now. At least `$dir` and `php_uname()` are quite predictable. The range of `microtime()` isn't as wide either. Since I'm new to CakePHP I don't know if this can cause a security risk because I don't know where and how the salt is used inside the framework.

**Comment by markstory** [comment]
How the salt is used: It is used as the default key use for encrypting cookies, and data should no other key be provided.

Given that the salt is generated when the application is created. How do you see this generated value being vulnerable? vs another 256 bytes?

**Comment by thinkingmedia** [comment]
The installer is part of your app. You can modify it with something like this.

```
hash('sha256', openssl_random_pseudo_bytes(100,true));
```

I don't think this improves security in the least bit.

**Comment by 68b32** [comment]
> How the salt is used: It is used as the default key use for encrypting cookies, and data should no other key be provided.
> Given that the salt is generated when the application is created. How do you see this generated value being vulnerable? vs another 256 bytes?

In the sense that the range of salts (=keys in some usecases) generated is quite small. An attacker that gets an encrypted cookie (e.g. via XSS vulnerability) could easily generate a list of possible hashes to decrypt it by 
* knowing or guessing the value for `$dir`, which in lots of cases will be something like `/var/www/<appname>`,
* knowing or guessing the return value of `php_uname()`. This is a bit harder but still has not a very huge range. You could find out what OS the webserver runs on (e.g. by getting a version-string from a apache2 404 page, or connecting to a SSH daemon running on the same host and review the given version information (`telnet debianmachine.example.com` will show you `SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u2`). https://packages.debian.org/en/jessie/openssh-server shows you that this is a Debian jessie system. You can install such a system as a virtual machine, and check its `php -r "echo php_uname();"` output. You than might have to change the hostname included in the output. Or if you have access to another webspace on the same machine (shared hosting!) you can just call `php_uname()` to get the output.
* Estimating when the app was installed. If you can say between which points in time the app was installed, you know which values `microtime(true)` was able to return.

For example to generate all possible hashes for an app called `testapp` installed to the default apache2 path (`/var/www` or `/var/www/htdocs`) on a freshly installed Debian 8 with the hostname `example.com` or `localhost`, you could write something like this: https://gist.github.com/68b32/15099a7eb9b67976fb5d4556a0ea21a6

This will run about 4h on my laptop to generate all posible hashes. With decryption it will take a bit longer, but only in the range of another hour.

The solution of @thinkingmedia would force me to go to many many more options, since the range of possible keys is much wider and can not be reconstructed by collecting accessible information.

**Comment by thinkingmedia** [comment]
Don't use encrypted cookies and don't store sensitive information on the client side.

**Comment by thinkingmedia** [comment]
@68b32 that's a cool code sample you wrote.

Are you worried about an encrypted cookie?

**Comment by AD7six** [comment]
> You could find out what OS the webserver runs on

There's a somewhat huge assumption here that the app was _created_ and is still in the same path it is currently deployed to. That's almost never going to be true.

**Comment by markstory** [comment]
@AD7six its possible, but will be rare.

Given how easy it is to use a more secure source of random data, I'll update the code.

**Comment by markstory** [comment]
Pull request open now. Thanks for raising this @68b32

**Comment by 68b32** [comment]
@AD7six I think you are right that this scenario might be an edgecase. Still the possible input options for the hash function are quite limited, compared to a random value. I still think that it a very good idea to go for some random value which is independent from any predictable / guessable information. The sample code I provided is just a very limited version of a bruteforcer, but if you think in bigger dimensions (NSA computing centers etc.) you want the range of possible keys as wide as you can.

@markstory Thank you very much
