### ISSUE TITLE
3.3 - Rename `MiddlewareStack` to `MiddlewareDispatcher`

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#9158]
The name `MiddlewareStack` is misleading since it doesn't maintain middlewares as a stack but a list where additions can be done at any position. Also the `Runner` consumes it like a queue starting at first index. So for our implementation, `MiddlewareDispatcher` would be a more appropriate name. Also the method `push()` should be renamed to `add()`.

Looking at other examples of middleware stacks, they are implemented quite differently than what we have and for them the last pushed middleware runs first. Eg. [schnittstabil/psr7-middleware-stack](https://github.com/schnittstabil/psr7-middleware-stack), [stackphp/builder](https://github.com/stackphp/builder). Our implementation looks similar to [relayphp](http://relayphp.com/) which also follows first-in-first-out ordering.

**Comment by markstory** [comment]
`MiddlewareCollection` or  `MiddlewareList` perhaps? Or does that imply it implements the `CollectionInterface`? I'm not sure I want to go with 'Dispatcher' as it doesn't really dispatch anything.

**Comment by ADmad** [comment]
I prefer `MiddlewareCollection`. It's highly unlikely someone would try to use `CollectionInterface` methods for it.

I can make a PR once we settle on the name.

**Comment by htstudios** [comment]
If it behaves like a list, MiddlewareList or MiddkewareQueue?

I don't like Dispatcher or Collection over Stack.

**Comment by markstory** [comment]
Queue is another reasonable suffix.

**Comment by ADmad** [comment]
`MiddlewareQueue` works for me.

**Comment by markstory** [comment]
Closing as pull requests are open.
