### ISSUE TITLE
Log an error when headers have been sent.

### ISSUE THREAD

**Issue by DinoSane** [cakephp/cakephp#9159]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7.
* Platform and Target: Apache, mysql Windows, PHP 5.5.12

### What you did
Just use Cakephp in an Ajax scenario

### Expected Behavior
An error or alert about an header already sent

### Actual Behavior
Nothing is shown in any log (including php_error.log)

I was stuck at a problem that was easily fixed after I change this lines at Network\Response.php (line 448)

    if (headers_sent($file,$line)) { //I add headers_sent parameters
        error_log("Headers already sent: $file($line)");
        return;
    }

And this is a small improvement that I suggest.

**Comment by markstory** [comment]
I think logging an error is reasonable.

**Comment by ADmad** [comment]
Btw the [SapiStreamEmitter](https://github.com/zendframework/zend-diactoros/blob/1.3.5/src/Response/SapiStreamEmitter.php#L31) used by default to emit response in 3.3 throws an exception if headers are already sent.

**Comment by markstory** [comment]
Pull request up now.
