### ISSUE TITLE
DateTime::__construct(): Failed to parse time string (01/055551/2016) at position 9 (/): Unexpected character 

### ISSUE THREAD

**Issue by DonAndrey** [cakephp/cakephp#9161]
Hi,

I am using modernizr for my date, but while I was testing my app, I manually entered a bad date **(01/055551/2016)** (in Firefox), and something failed. The error message is that I used as a title. 

I also attatch an image of the error message. 

![captura](https://cloud.githubusercontent.com/assets/10506340/17091130/adb6667a-51f4-11e6-9930-b4cfa26cf841.PNG)

Thanks in advance.

**Comment by lorenzo** [comment]
Looks like something validation would be able to fix. Are you validating your date inputs?

**Comment by markstory** [comment]
This stack trace is coming from your `beforeMarshal` handler. It looks like you need to catch exceptions.
