### ISSUE TITLE
Exceptions doesn't keep http headers in ajax response

### ISSUE THREAD

**Issue by irongomme** [cakephp/cakephp#9163]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: nginx 1.9.6, Chrome 52, angularjs 1.5

### What you did
I'm doing a cross site request from an angularjs app frontend, using cake as a REST API.

### Expected Behavior
Have a response body with the error / exception as json

### Actual Behavior
Http headers are reseted in 401 and 403 responses, and probably all excptions codes, and the response body is empty. 
It works with a REST API tester like postman, but not with an angularjs call from chrome in my case.

**Comment by markstory** [comment]
How can someone reproduce the issue you're seeing? On a local test application, I see JSON response bodies for exception based responses.

What is different about the angular call vs. the postman call?

**Comment by markstory** [comment]
This could be related to #8969

**Comment by irongomme** [comment]
I think the difference is that postname is not a cross domain call. For my issue, i use a domain like mydomain.dev for the frontend, and another domain like api.mydomain.dev for api calls.
It can be reproduces in doing an api call from a domain to another, wich trigger an exception.

**Comment by irongomme** [comment]
If i force response header by adding at the end of bootstrap.php: 

```
header('Access-Control-Allow-Origin: *');
```

All is working, but this is not a clever solution, i'd prefer exceptions and errors to keep originals headers which are defined like this by nginx in my situation :

```
server {
    listen  80;
    root    /srv/www/mydomain.dev/api/webroot/;
    server_name     api.mydomain.dev;

    access_log      /var/log/nginx/mydomain_access.log;
    error_log       /var/log/nginx/mydomain_error.log;

    # serve static files
    location ~* \.(img|css|js|jpg|jpeg|gif|png|map|ico)$  {
            expires max;
            log_not_found off;
    }

    location / {
        index  index.php;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass   php7-dev:9000;
        fastcgi_index  index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_NAME $http_host;
        fastcgi_param APPLICATION_ENVIRONMENT DEV;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_ignore_client_abort on;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            #
            # Om nom nom cookies
            #
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            #
            # Custom headers and headers various browsers *should* be OK with but aren't
            #
            add_header 'Access-Control-Allow-Headers' 'Keep-Alive,User-Agent,X-Requested-With,Cache-Control,Content-Type,Authorization';
            #
            # Tell client that this pre-flight info is valid for 20 days
            #
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        if ($request_method = 'POST') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Keep-Alive,User-Agent,X-Requested-With,Cache-Control,Content-Type,Authorization';
        }

        if ($request_method = 'GET') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Keep-Alive,User-Agent,X-Requested-With,Cache-Control,Content-Type,Authorization';
        }
    }

    # git & svn repositories, etc
    location ~ /(\.ht|\.git|\.svn) {
        deny  all;
    }
}
```

**Comment by markstory** [comment]
Sounds you need to set CORS headers in your application. If you need CORS headers set in your error responses, you'll need to customize the `ErrorController`.

**Comment by irongomme** [comment]
Thanks @markstory, but if CORS headers works fine for responses OK (200), why are they disapear in exceptions/errors ? I don't understand the reason why i should override the framework ... In another term, why is this not a bug ?

**Comment by irongomme** [comment]
moreover, this afternoon i've someone with the same issue, but unfortunately this trick doesn't work for me (in french ... sorry) : 

http://www.flavienbeninca.fr/2016/07/12/cakephp-3-crosscomain-cors.html#le-cas-des-exceptions

**Comment by irongomme** [comment]
After some digging into this behavior, i've found that this is the use of the plugin friendsofcake/crud which cause this issue, i will search in this way.

**Comment by irongomme** [comment]
According to this blog : http://www.flavienbeninca.fr/2016/07/12/cakephp-3-crosscomain-cors.html#le-cas-des-exceptions , this works : 

in bootstrap.php, i've replaced 
```
use Cake\Error\ErrorHandler;
```
by
```
use App\Error\AppError;
```

And 
```
(new ErrorHandler(Configure::read('Error')))->register();
```
by
```
(new AppError(Configure::read('Error')))->register();
```

I've added the file src/Error/AppError.php : 
```
<?php
namespace App\Error;

use Cake\Error\ErrorHandler;

class AppError extends ErrorHandler
{
    protected function _sendResponse($response)
    {
        $response->header('Access-Control-Allow-Origin', '*');
        $response->header('Access-Control-Allow-Credentials', 'true');
        $response->header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
        $response->header(
            'Access-Control-Allow-Headers',
            'Keep-Alive,User-Agent,X-Requested-With,Cache-Control,Content-Type,Authorization'
        );

        parent::_sendResponse($response);
    }
}
```

And now i've got http responses with headers and body for excpetions !

**Comment by markstory** [comment]
That's a good way to do it for now. This gets much easier once 3.3.0 ships as you can put middleware around the error handling code and not need to replace the error handler :smile:
