### ISSUE TITLE
Wrong association silently fails

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#9166]
Say I use `patchEntity()` like this:

```php
$this->Materialtypes->patchEntity($data, $this->request->data, [
    'associated' => ['Fields']
]);
```

If `Materialtypes` is not associated with `Fields`, the patch will silently omit all entries that would belong to Fields.

I suggest that provided associations are checked to avoid this silent failure. I stumbled over this when changing an association's name.

**Comment by lorenzo** [comment]
Would you like to submit a pull request for this?

**Comment by burzum** [comment]
@lorenzo this will be fixed using the SaveOptionBuilder() from https://github.com/cakephp/cakephp/pull/9143. It validates the assocs.

**Comment by ypnos-web** [comment]
@burzum great work! Really like your approach and hope to see it soon merged (and maybe also done for other parts of Cake)

**Comment by markstory** [comment]
Pull request open now.
