### ISSUE TITLE
Cake Email localisation

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#9171]
I'm currently working on a notification plugin which sends out emails in a cli context.
I stumbled upon the localisation and I was wondering why the Cake Email class didn't has a property to set the locale for the email?

Is there any reason? If not, I'm glad to implement this.

**Comment by ADmad** [comment]
Localizing emails is no different localizing HTML page responses. Please read the Internalization and Location chapter on manual and if you need help post a question on the CakePHP forum, stackoverflow, slack or IRC channel.
