### ISSUE TITLE
Cakephp 2 compatible redirect in cake 3

### ISSUE THREAD

**Issue by davo3** [cakephp/cakephp#9172]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.12

From the docs and from this question about redirect in cake 3
http://book.cakephp.org/3.0/en/controllers.html#redirecting-to-other-pages
http://stackoverflow.com/questions/29481810/cakephp-3-0-possible-to-redirect-immediately
the return should be used to prevent rendering into view.

However this does not work if trying to make a redirect from AppController or Component's method. There are workarounds
http://stackoverflow.com/questions/32177050/cakephp-3-redirect-in-beforefilter-of-parent-class/32190873#32190873

Specifically the method 2 works both from AppController and from Component's method
```
$this->response = $this->redirect('/c/myMethod10') ;
$this->response->send () ;
die () ;
```

So, cant we just implement this into the core ? I know, one might say, create your function, paste the code above, and there you go, but would not it be better to have a native way of redirecting as we had in cake 2.

**Comment by ADmad** [comment]
Sending response directly from controller / component itself and existing the script is pretty ugly and won't implemented again in 3.x. Regardless of the response type the dispatch cycle should be completed and response send to client by dispatcher.

**Comment by davo3** [comment]
> Regardless of the response type the dispatch cycle should be completed 

what if there is a redirect necessary from appcontroller/component, e.g. we have some custom permissions functionality and it should be checked in app controller/component and the user to be redirected - so we can not allow for the controller's action to run. What is the suggested approach of handling this kind of redirect issues by cake native methods ? thanks

**Comment by ADmad** [comment]
Returning a response instance from controller's `AppController::beforeFilter()` will prevent the action from being executed. If `beforeFilter()` is extended in child controller check return value of `parent::beforeFilter()` and if it's reponse instance return it. Similarly check return type of component method and if it's reponse instance return it from the controller method.
