### ISSUE TITLE
Router REST extensions not working inside a plugin

### ISSUE THREAD

**Issue by miguelxt** [cakephp/cakephp#9173]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.11
* Platform and Target: XAMPP on Mac OS X, PHP/5.6.20, Apache/2.4.18

### What you did
I'm trying to set up extensions parsing on CakePHP3 inside a plugin and they are not working. They work correctly when setup in the main app.

I have this in config/routes.php:
```php
Plugin::load('Admin', ['bootstrap' => false, 'routes' => true]);
```

This in in plugins/Admin/config/routes.php:
```php
Router::plugin('Admin', ['path' => '/admin'],
    function (RouteBuilder $routes) {
        $routes->extensions('json');
        $routes->resources('Users');
        $routes->fallbacks('DashedRoute');
 });
```

And this in plugins/Admin/src/Controller/UsersController.php 
```php
    public function initialize() {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->Users = TableRegistry::get('Users');
    }
    public function index() {
        $query = $this->Users->find('all');
        $users = $this->paginate($query);
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }
```

### Expected Behavior
When I visit the route /admin/users/index.json I expect to receive a JSON array containing the users in the database.

### Actual Behavior
When I visit the route /admin/users/index.json I get this error:

```javascript
{
    "message": "Template file \u0022Users\/json\/index.ctp\u0022 is missing.",
    "url": "\/www\/admin\/users\/index.json",
    "code": 500
}
```

**Comment by markstory** [comment]
> I'm trying to set up extensions parsing on CakePHP3 inside a plugin and they are not working. They work correctly when setup in the main app.

Do you mean when the plugin routes are connected in the app the extensions work correctly?

**Comment by miguelxt** [comment]
@markstory Not exactly. If the routes are set in the app/config/routes.php they work but just for the app, not for the plugin.

**Comment by markstory** [comment]
@miguelxt I'll see if I can reproduce with a local test app.

**Comment by markstory** [comment]
I wasn't able to reproduce this in a local app. Are you sure your routes are being loaded? Can you try using the CLI tools to test routing?

```
# show connected routes
bin/cake routes

# check URL parsing
bin/cake routes check /admin/users/index.json
bin/cake routes check /admin/users.json
```

The `routes check` commands should output something like:

```
$ bin/cake routes check /contact_manager/contacts.json

Welcome to CakePHP v3.2.12 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 7.0.6
---------------------------------------------------------------
+----------------------------------+--------------------------------+----------------------------------------------------------------------------------------------+
| Route name                       | URI template                   | Defaults                                                                                     |
+----------------------------------+--------------------------------+----------------------------------------------------------------------------------------------+
| contactmanager._controller:index | /contact_manager/contacts.json | {"controller":"Contacts","pass":[],"action":"index","plugin":"ContactManager","_ext":"json"} |
+----------------------------------+--------------------------------+----------------------------------------------------------------------------------------------+
```

**Comment by miguelxt** [comment]
I thing I have pinpointed the issue. I have created a repo that you can clone to test it: https://github.com/miguelxt/cakejsonviewtest

The issue happens when you use the following in your controller:
```php
$this->viewBuilder()->className('App\View\AppView');
```

This is regardless of the line being in the main app or in a plugin. You could check App\Controller\UsersController to see this happening.

**Comment by ADmad** [comment]
So your issue has nothing to do with routing but rather the fact that you are explicitly setting a view class for the view builder too early and hence `RequestHandler` won't auto set the view to `JsonView` even though it's the url has `.json` extension.

**Comment by miguelxt** [comment]
@ADmad, is there any workaround? It's not possible to use a custom View class and the RequestHandler ?

**Comment by markstory** [comment]
@miguelxt You can, but by setting a viewClass that early in the request process you'll disable RequestHandler from overwriting it in its `beforeRender` callback. If you want to set a view class up, you'd need to do so in your `beforeRender`, after checking that the view class has not already been set, otherwise you'll overwrite the view class once again.

**Comment by miguelxt** [comment]
I was able to make it work following @markstory suggestion, by setting the view class in the beforeRender callback:

```php
public function beforeRender(\Cake\Event\Event $event) {
        parent::beforeRender($event);
        if ($this->viewBuilder()->className() == 'null') {
            $this->viewBuilder()->className('App\View\AppView');
        }
    }```
