### ISSUE TITLE
3.x FormHelper: Easy way to always render natural Primary Keys instead of type=hidden

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#9178]
This is a (multiple allowed):
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.12

### What you did

1.

```sql
CREATE TABLE `countries` (
  `code` char(2) CHARACTER SET ascii NOT NULL DEFAULT '',
  `label` varchar(100) NOT NULL DEFAULT '',
  `is_active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`code`),
  UNIQUE KEY `uniq_label` (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

2. *bake*...
3.

```php
<?= $this->Form->input('code') ?>
```

### Expected Behavior
A. `FormHelper` should not set `input` `type` = `hidden` for natural primary keys.
By convention we should only hide fields named `id` as those are most likely surrogate/non-natural primary keys.

B. I did also try setting the natural primary to accessible to true within the Entity to teach `FormHelper::input()` to render as `text` instead of `hidden` - without success.

### Actual Behavior
Renders as `type` = `hidden`.

* * *

Ref: http://hastebin.com/tozutoceci.php

**Comment by dakota** [comment]
I'd prefer to keep the current behaviour, where displaying of primary key fields is entirely opt-in.

**Comment by markstory** [comment]
Guessing whether or not a primary key is 'natural' is hard, and computers are dumb. I think its best if we don't try to guess and instead let developers be explicit `$this->Form->input('code', ['type' => 'text']);`
