### ISSUE TITLE
EntityTrait clean() method should clean _orginal as well

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#9182]
I wonder why the `clean()` method inside the `EntityTrait` doesn't clean `$this->_original` as well.   I could provide a PR if desired.

See: https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L694-L699

**Comment by markstory** [comment]
It seems reasonable to me, that when an entity has been cleaned we would want to reset the original state as it is likely that the entity has been persisted.

**Comment by steefaan** [comment]
@markstory Sorry I'm not sure if I understand you correctly. Do you want to keep the current behavior or a PR to clean `_original` as well?

**Comment by ADmad** [comment]
@steefaan Make a PR for the change you proposed :)

**Comment by ADmad** [comment]
Closing are related PR is opened.
