### ISSUE TITLE
FormHelper::input crash when setting type option to input

### ISSUE THREAD

**Issue by tobias-urdin** [cakephp/cakephp#9185]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: Debian 8 with Apache2 and PHP5

`$ apache2ctl -V`
Server version: Apache/2.4.10 (Debian)

`$ php5 -v`
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)

### What you did
It seems like FormHelper::input sanitizes the 'type' being passed in $options but when passing the 'type' as 'input' it crashes PHP and Apache and causes a seg fault on the Apache child process executing the request.

### Expected Behavior
Not crashing.

### Actual Behavior
Examples that does not cause a crash:
```php
<?= $this->Form->input('username', ['placeholder' => 'Username', 'type' => 'text', 'label' => false, 'class' => 'form-control', 'tabindex' => 1]) ?>
<?= $this->Form->input('username', ['placeholder' => 'Username', 'type' => 'ijustplacerandomstuffhere', 'label' => false, 'class' => 'form-control', 'tabindex' => 1]) ?>
```

Example that does cause a crash:
```php
<?= $this->Form->input('username', ['placeholder' => 'Username', 'type' => 'input', 'label' => false, 'class' => 'form-control', 'tabindex' => 1]) ?>
```

Apache2 log says child pid died with a seg fault
>[Thu Jul 28 16:51:02.631771 2016] [core:notice] [pid 986] AH00052: child pid 1659 exit signal Segmentation fault (11)
> [Thu Jul 28 16:51:03.632960 2016] [core:notice] [pid 986] AH00052: child pid 1310 exit signal Segmentation fault (11)

Shouldn't this be sanitized better to prevent such a crash?

I assume that 'input' shouldn't be an valid 'type' but why isn't it sanitized, it's very easy to make a typo there and then have to go through all code or debug a core dump from apache2 to find the issue.

Best regards

**Comment by ADmad** [comment]
Using `'type' => 'input'` would cause an infinite loop and on PHP 7 I get a fatal error. With xdebug enable I also get a stack trace which helps pinpoint the line causing the problem.

The fact that you get a segmentation fault on your environment is coincidental and there's nothing we can do about it. Maintaining a list of all valid input types to valid the `'type'` value isn't practical and would also be unnecessary overhead.

**Comment by markstory** [comment]
We could throw an exception specifically on `type => input` @ADmad. That's a pretty small list to maintain.

**Comment by ADmad** [comment]
But still an unnecessary overhead to check imo, for something that's gonna occur very rarely.

**Comment by markstory** [comment]
If @tobias-urdin is interested in submitting a pull request that updates the existing case switch I wouldn't be against merging it.
