### ISSUE TITLE
Refresh entity associations after patching

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#9186]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)

CakePHP Version: 3.x

Scenario: A user submits a form, the entity is patched, then instead of directly going to save, the user is redirected to a 'review' view where they can review the changes made. The 'review' is rendered using the patched entity.

Problem: For any belongsTo relationship, the patched entity will still hold the wrong data. Example:

``` php
    /* patch entity */
    $this->Materialtypes->patchEntity($type, $this->request->data);

    /* update type to reflect change in review */
    if ($type->dirty('parent_id'))  // ($type->parent->id != $type->parent_id) {
        $type->parent = $this->Materialtypes->get($type->parent_id);
    }

    /* render review */
    $this->set('data', $type);
    return $this->render('review');
```

As you can see, the parent needs to be refetched manually. As this requires an SQL roundtrip, we only do it when the id really changed. 

What **doesn't** work:

``` php
    $this->Materialtypes->loadInto($type, ['Parents']);
```

I didn't see it in the relevant code but I assume the association is not loaded as there is already an entity present, albeit the wrong one.

``` php
    $this->Materialtypes->patchEntity($type, $this->request->data, ['associated' => 'Parents']);
```

Actually I also think that the 'associated' option should not be intermingled with this.

From the example you can extrapolate how tedious it is to conditionally update all these relations. The controller is also not a good place for this, however one could move this into a patchEntity() override in the table.

I therefore propose to introduce an unsupervised mechanism that re-loads all belongsTo associations where the respective foreign key is dirty. This could be an option to patchEntity() or a standalone method of table (e.g. `refresh()`). Probably both (patchEntity() calls refresh() if option 'refresh' is set to true).

**Comment by markstory** [comment]
Refreshing from the DB is not as easy as it initially seems. For example, if you're updating any associated records with the root entity, what should happen on 'reload'? If you naively reload the associations, the patched changes would be lost.

I think making `loadInto()` simpler to operate might be a reasonable solution that won't have as many edge cases as trying to intelligently reload associated records.

**Comment by ypnos-web** [comment]
If associations are updated, these are dirty (not their key). In my scenario, I use 'associations' option of patchEntity() for the associations altered by the request.

**Comment by markstory** [comment]
And when the foreign key columns & associated record has been patched, would you leave the associated record alone, or refresh it?

**Comment by ypnos-web** [comment]
Sorry for not stating my thoughts more clearly in my previous reply. I consider everything "dirty" as being the most-recent version of the respective field or entity as local change > database state.

Which means that an entity being dirty forbids replacing it.
However any non-dirty entity with a respective dirty foreign key must be considered obsolete and therefore replaced.
If both entity and foreign key are dirty, the conclusion is to not change anything.

**Comment by markstory** [comment]
Ok. How does something like:

```php
$associations = ['Comments', 'User', 'Tags'];
$entity = $this->Articles->patchEntity($article, $data, ['associated' => $associations]);
$entity = $this->Articles->refreshAssociations($article, $associations);
```

feel to you? Is that kind of what you had in mind?

**Comment by ypnos-web** [comment]
It would already be a great help, however I have two comments:

1. By default, the first level of associations is both patched and saved. So `refreshAssociations()` is expected to behave the same way. The whole idea of the refresh is that the data looks exactly the way it will look after saving.

2. Thinking about this I took a step back to realize that I think `patchEntity()` itself needs change. In the current situation, it leaves behind an inconsistent entity. This is a really the worst case. To remedy the problem, I would suggest that `patchEntity()` strips all obsoleted associations (where the key/foreign key don't match anymore). This ensures that no false information can be propagated. In this scenario, `refreshAssocations()` can be substituted by the existing `loadInto()` functionality.

**Comment by markstory** [comment]
> By default, the first level of associations is both patched and saved. So refreshAssociations() is expected to behave the same way.

Yes we could do that in the new method too.

**Comment by markstory** [comment]
>  I think patchEntity() itself needs change. In the current situation, it leaves behind an inconsistent entity. This is a really the worst case. To remedy the problem, I would suggest that patchEntity() strips all obsoleted associations (where the key/foreign key don't match anymore).

I'm not sure this will be a backwards compatible behavior. I concur that in the context of this discussion it makes sense, but I worry that we could break expectations of existing applications.

**Comment by ypnos-web** [comment]
I am certain you and other core developers are more competent to determine if this is a backwards compatibility issue than me. 

My thoughts on this:
On the one hand, while it would only affect accessing the "wrong" associated entity after the patch, in this case PHP errors are a likely result  in some cases but not in others (when the id was untouched). On the other hand, I see the inconsistent entity being further processed the greater evil here (a silent failure).

In any case, I think having a `refreshAssocations()` as we discussed would already be a great solution by itself.

**Comment by thinkingmedia** [comment]
Don't call it `refreshAssocations` but just `getAssocations` as this could be used to load associations for new entities as well.

I have forms that show pre-loaded defaults for new records, and this would have been useful.

**Comment by markstory** [comment]
@thinkingmedia Isn't that `loadInto()`?  This method would *overwrite* existing associations only if the foreign keys were dirty.

**Comment by ypnos-web** [comment]
The use-case of @thinkingmedia makes sense in this context. Often, edit/create actions are combined in the code. It makes sense to do it like this:

For each foreign_key pointing to a belongsTo:

1. entity missing -> load
2. entity is clean -> load
3. entity is dirty -> ignore

There is two distinctions between this functionality in `loadInto()`:

1. the ability to overwrite
2. processing of all first-level associations plus any other associations provided in argument

**Comment by markstory** [comment]
@ypnos-web For 2. Would you only want to load the association if the related entity is clean, and the foreign key field(s) have changed? If entity is present and clean, I don't know if a reload is necessary.

**Comment by ypnos-web** [comment]
Sorry mate, I had left out a crucial word when reformatting my last comment, I meant to say "For each **dirty** foreign_key pointing to a belongsTo", in accordance to what we had discussed previously. I correct my last post.

**Comment by raul338** [comment]
What about of a flag/options in loadInto?, so that
`$this->Articles->loadInto($articles, ['Comments', 'Users'], true);` would **always** reload associations.

`$this->Articles->loadInto($articles, ['Comments', 'Users']);` would (re)load associations except when the related entity is dirty. (If the foreign_key and the related entity are both dirty, the entity should be replaced with the new one)

Instead of a boolean, it could be a enum
- Load only associations that currently are not loaded (current loadInto)
- reload associations even if the foreign_key is clean
- reload associations even if the associations is loaded and dirty (overwrite)

**Comment by ypnos-web** [comment]
I am all in for merging this functionality with `loadInto()`, however for me the second distinction I mentioned (processing of all first-level associations plus any other associations provided in argument) is also a very important functionality.

I am longing for a DRY way to have my entity being current and consistent.

**Comment by markstory** [comment]
I don't think overloading existing functions with boolean flags is a pattern I'd like to continue doing when we can easily add a new method that is easier to read and document the behavior of.

**Comment by kyleweishaupt** [comment]
Just came across this and I could benefit as well. It would help with adding new entities that come with optional parameters for associations.

Here's kind of what I'm thinking:
```php
$post = $this->Posts->newEntity([
	'type_id' => $this->request->getQuery('type_id') ?: null
]);

$this->Posts->loadInto($post, ['Types']);
```

After looking at `$post` I can see the `type_id` is set, but I can't load the Type as an association. I'm aware I could do something similar to `$post->type = $this->Posts->Types->get($type_id)`, but loading an association name into the entity might make for cleaner code. 

I'm also dealing with an unsaved entity so a method to update an existing entity based on the current state would be greatly appreciated.

**Comment by markstory** [comment]
> I'm also dealing with an unsaved entity so a method to update an existing entity based on the current state would be greatly appreciated.

How would that work for an unsaved entity? Where would the state be loaded from? Are you looking for a way to load the potentially connected associations that the entity would have if/when it is persisted?

**Comment by kyleweishaupt** [comment]
> Are you looking for a way to load the potentially connected associations that the entity would have if/when it is persisted?

That is correct.

> How would that work for an unsaved entity? Where would the state be loaded from?

I was thinking the state would be the current entity. Since the entity has a table class containing the associations, the foreign keys for any associations would already be known.

**Comment by berarma** [comment]
Currently, loadInto uses the persisted data, not the actual data in the entity. That's why it doesn't always work after newEntity or patchEntity. It would be useful to have some way to load associations based on the current foreign keys in the entity. It could be called after newEntity and patchEntity.

**Comment by berarma** [comment]
I've made a fast implementation of a probably incomplete and buggy ```refreshAssociations``` method in a trait. It's working for what I need but I may have missed some cases.

https://gist.github.com/berarma/5ea4ca9ff909df0a1017ef73250ef647

**Comment by Avsy** [comment]
fwefwe
