### ISSUE TITLE
About cakephp/routing

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#9188]
Hi guys,

I have created a route like this:
```
    $routes->connect('/thumbnail/:widthx:height/:image', ['controller' => 'Image', 'action' => 'thumb'], [
        'pass' => ['image', 'width', 'height'],
        'width' => '\d+',
        'height' => '\d+',
    ]);
```
and I want it match `/thumbnail/200x300/foo-bar.png`,however it doesn't work.
I think I need some help.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by slince** [comment]
I have reviewed documents, unfortunately there's  no good solution because  ‘`x`’ is a valid english character; I recommend using "`{placeholder}`"  replacement "`:placeholder`"

**Comment by slince** [comment]
@dereuromark

**Comment by htstudios** [comment]
Optional {} to clearly mark a varianle and \ for escaping sounds good. Would you setup a PR?

**Comment by slince** [comment]
I’m so sorry, I'm not familiar with the `cakephp/routing` source code @htstudios
