### ISSUE TITLE
Query::update() does not support LIMIT

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9195]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: Apache2, MySQL, PHP 7

### What you did

Trying to create a custom update query that has a LIMIT 1

```
    $query = $documents->query()->update()->set(['title'=>'foo'])->limit(1);
    Log::info((string)$query);
```

Output:

```
   UPDATE `documents` SET `title` = :c0
```

### Expected Behavior

MySQL supports LIMIT on UPDATE queries, but the ORM is not adding the LIMIT clause.

### Actual Behavior

All records are updated. :cry:

**Comment by thinkingmedia** [comment]
I traced the problem down to the `QueryCompiler`

It's ignore the limit clause on lines 59.

```
    /**
     * The list of query clauses to traverse for generating an UPDATE statement
     *
     * @var array
     */
    protected $_updateParts = ['update', 'set', 'where', 'epilog'];
```

Anyone know why it was excluded from the update clauses?

I saw `epilog` and was able to use that to append `LIMIT 1` but that feels more like a hack.

I also noticed that there is no `MysqlCompiler` but there are ones for `SqliteCompiler` and `SqlserverCompiler`.

Can I make a PR for adding a `MysqlCompiler` that supports the `LIMIT` clause on updates?

**Comment by markstory** [comment]
Given that both MySQL and [SQLite](https://www.sqlite.org/lang_update.html) support updates with limit, we could always compile that clause in. It will of course cause queries to fail in postgres and SQLServer, but those queries would have done the 'wrong' thing anyways on those vendors.

**Comment by thinkingmedia** [comment]
It would be more supportive if the compiler throws an exception when a feature is used that is not supported. 

I think it might be a simple to see if one of the compiler methods is called with a query part that is not set for that query type. If that happens the compiler knows the query is using an unsupported clause and it can throw an exception.

**Comment by stmeyer** [comment]
In Sqlserver is the `TOP`-parameter: https://stackoverflow.com/questions/1198364/how-can-i-update-top-100-records-in-sql-server and https://msdn.microsoft.com/de-de/library/ms177523.aspx

Additinally in sqlserver one can use the `TOP` for `DELETE`. I do not know if this is allready supporded by cakephp or if it's possible to use `TOP` or `LIMIT` in MySQL, but it would be a nice feature, too.

**Comment by saeideng** [comment]
> It would be more supportive if the compiler throws an exception when a feature is used that is not supported. 
> 
that is bad idea
By doing this, we can not easily move/change to other database

**Comment by markstory** [comment]
@saeideng If your application relies on `update ... limit` you can't easily move between databases anyways.

**Comment by markstory** [comment]
@thinkingmedia The underlying database will throw an exception when it encounters sql it can't run. Won't that be enough?

**Comment by thinkingmedia** [comment]
Take my example in the issue:

```
    $query = $documents->query()->update()->set(['title'=>'foo'])->limit(1);
```

No error is raised, and the database does not raise an error. In Cake 3.2.12 the above will update **all** records for all database drivers.

If the ORM had raised an example that `LIMIT` was not support for update the database would not have been corrupted.

**Comment by thinkingmedia** [comment]
> By doing this, we can not easily move/change to other database

@saeideng With out throwing exceptions you will not be able to find ORM queries that use clauses that are not supported by the driver.

The issue appears to be mainly limited to the update and delete queries. Those statements have convenience methods in the `Table` that build queries with just the few clauses supported by the `QueryCompiler`. When you need to build queries manually then you have no idea if the clauses you used will work.

The only reason I know why the above fail was because I know the Cake core source code. We need exceptions to assist Cake users in writing queries that work.

**Comment by markstory** [comment]
> If the ORM had raised an exception that LIMIT was not supported for update the database would not have been corrupted.

My previous comment was more directed at *if* we did emit `LIMIT` / `TOP` and the underlying database did not support that clause, the generated query would be invalid for that database, and generate an exception.

**Comment by lorenzo** [comment]
I'm going to close this issue as there would be no way of implementing this reliably in all databases. As a workaround for mysql, You can do

```php
$updateQuery->epilog('LIMIT 10');
```

**Comment by thinkingmedia** [comment]
@lorenzo I just discovered a huge bug in my app where an update was not using the order by clause.

The ORM silently executes the update without the order and you get completely different results.

There needs to be something in place to warn developers that the clauses do not work in a given driver.

**Comment by lorenzo** [comment]
I agree. I'll think about this and come up with a solution

**Comment by thinkingmedia** [comment]
I think a simple soft warning with `trigger_error` is there are clauses assigned to the query not supported by the compiler. Last time I looked at the core this didn't look difficult to implement.

I'd do a PR but I'm kind on a tough deadline right now.

**Comment by thinkingmedia** [comment]
@markstory @lorenzo 

I came up with a really simple fix that follows the ORM pattern.

I created my own Mysql driver that extended the ORM one, like this:

```
class MySql extends \Cake\Database\Driver\Mysql
{
    public function newCompiler()
    {
        return new MysqlCompiler();
    }
}
```

I then added my own `MysqlCompiler` class, like this:

```
class MysqlCompiler  extends QueryCompiler
{
    /**
     * @var array
     */
    protected $_updateParts = ['update', 'set', 'where', 'order', 'limit', 'epilog'];
}
```

That's all I did, and it works great as the update features now support `ORDER` and `LIMIT`.

Can this get added to the core?

**Comment by markstory** [comment]
I don't see why not. We support a few other non-standard sql dialect fetures in the same way.

**Comment by thinkingmedia** [comment]
FYI: I had to do this fix for the DELETE query as well.
