### ISSUE TITLE
RFC: Read/Write database splitting 

### ISSUE THREAD

**Issue by johanmeiring** [cakephp/cakephp#9197]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.x and/or 3.3
- Platform and Target: Specifically MySQL, but should be applicable to any datasource.
### RFC: Read/Write database splitting

It has become a common pattern to split an application's database activity into two basic categories (read and write), and to assign the actions related to these categories to different datastores.  For example, with MySQL, one could typically have a master database (where all the `write` operations are performed), and a replicated slave database (where all, or most, of the `read` operations are performed).  There are many advantages to following this pattern, which I don't necessarily believe need to be discussed here (unless you guys feel the discussion is necessary).

However, I could not find an easy way to currently apply this pattern to a CakePHP application.  Sure, it's possible, and very easy, to configure multiple datasources, and then use them wherever and for whatever purpose.  But if I wanted to apply the DB read/write split model to each of my tables, then I would be duplicating the same code and behaviour all over the show, which is obviously undesirable.

My proposal is that adjustments be made to Cake core in order to accommodate this pattern as part of all the behind-the-scenes magic that takes place.  My very early preliminary investigation pointed to changing the way `Table::defaultConnectionName()` works, and complementing it with e.g. `defaultReadConnectionName` and `defaultWriteConnectionName`.  This would mean adding `readConnection` and `writeConnection` method/config options as well.  The default fallback will always be the write connection.  The ORM then decides which connection to use based on operation (select, update, insert, delete, etc) when necessary.

Thoughts?

**Comment by htstudios** [comment]
Is it possible to set the db when calling newEntity/patchEntity/save? If not that should be the way and then overloading your tables?

**Comment by johanmeiring** [comment]
I would imagine that `find`s and `get`s would typically use the read DB, and everything else would go through the write connection by default.  Writing to a read slave is suicide anyway, so careful checks will need to be implemented.

**Comment by jippi** [comment]
To me personally these things should be solved outside of core - either as a plugin (doable) or not in php at all :) 

Projects like `maxscale`, `mysqlproxy`, `kingshard`, `mysql-router` and tons of other projects solving these kind of things

What we've done at Bownty though, is simple to have a 'master' and 'slave' connection, and depending on our `env` we tell tables to use one or the other - simply round-robin a list of master and slaves (based on consul or a simple csv-style list of host-names) 

Doing it in the core is hard, as it requires deep application knowledge to do it right, e.g. you can't start reading from a slave, and then based on that data update something on a master node.

Could be as simple as a behavior that implement a custom method `$this->users->on('slave')->do()->stuff();` 

Trying to solve it in a generic way, is stupid hard :)

**Comment by htstudios** [comment]
What about passing a config key of a db connection into the basic ORM nethods acced via the controller?

**Comment by markstory** [comment]
I don't think automatic read splitting is as simple as it initially sounds. @jippi touched on a few of the reasons that I believe complicate automagic read splitting. However, I could see the possibility of having a behavior that allows application developers to more simply split reads based on query options.

**Comment by ravage84** [comment]
@johanmeiring what you are describing, is called CQRS, Command Query Responsibility Segregation.

http://martinfowler.com/bliki/CQRS.html
https://en.wikipedia.org/wiki/Command%E2%80%93query_separation#Command_Query_Responsibility_Segregation

This should not be in the core, as very few will actually ever use it.
But if the core provides enough flexibilty, e.g. through events, callbacks or a behavior, it will be easy enough to implement the (potentially) very specific behavior needed.

**Comment by Xymanek** [comment]
During update transaction there are multiple read queries like application rules and things like CounterCache. How do you suggest to deal with those? Besides that I think @jippi's idea about using another software is much better to achieve these goals

@markstory I feel like a simple behavior that takes a map of `event => connection` (eg. `'beforeFind' => 'slave1'`) would be a nice addition to the core

**Comment by markstory** [comment]
@Xymanek I'm not sure its that simple. Wouldn't a beforeFind() interact poorly with CounterCache?

**Comment by Xymanek** [comment]
@markstory Good point, which further adds to what I said above :smile: 

~~However this can be overcome by adding an 'update' state to each table ()~~ No, even that is unreliable... So yeah, if someone really wants a connection switching done on PHP side then they should write their own behavior specific to their needs. That or a very complicated plugin which would keep track of transactions, saves, exceptions, etc, etc, ect

**Comment by dereuromark** [comment]
Closing as stale and too unspecific.
