### ISSUE TITLE
Cake 2.x: Memory Leak in Email Sending with SMTP Transport

### ISSUE THREAD

**Issue by Linnk** [cakephp/cakephp#9198]
There is a memory leak in Cake2.x when using an SMTP transport with CakeEmail.

Turns out this is a bug that was present in Cake3.x as well (see issue #6128) and is already solved by @lorenzo for that branch. The issue and the fix it's the same for Cake2.x.

Each email sent increases the memory foot-print, with or without attachments, until memory limit is reached and the process is killed. This makes impossible to create a deamon with CakeShell for sending emails.

You can replicate the bug with the following shell:

```php
<?php

App::uses('CakeEmail', 'Network/Email');

class EmailMemoryLeakShell extends Shell
{
	public function main()
	{
		$n = 1;
		while ($n < 100) {
			$email = new CakeEmail('smtp');
			$email->from(array('noreply@incrementacrm.com' => 'Ventas'));
			$email->to('your@email.com');
			$email->subject('Testing subject');
			// 3 Mb attachment to make it more obvious.
			$email->attachments(array('/Users/linnk/Desktop/calls.xlsx'));
			$email->send('This is a testing message for SMTP config.');

			$this->out('CakeEmail instance #'.$n);
			$n++;
		}
		while (true) {
			$this->out('Total CakeEmail instances: '.$n);
			sleep(1);
			// Continue so you can see if the garbage collector kicks in.
			continue;
		}
	}
}
```

I run the Cake Shell using PM2: `pm2 start app/Console/cake.php -- -working "app/" email_memory_leak`. This way I can keep an eye on the PM2 monitor (`pm2 monit`) and see if the actual memory foot-print decreases.

I forked the repository and fix the bug the same way is fixed in the previous issue. I will submit my pull request with the fix if that helps.

**Comment by markstory** [comment]
Closing as a pull request is open.
