### ISSUE TITLE
Cake 3 Hash transform object

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#9206]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0 beta 3
* Platform and Target: WAMP7

### What you did
`Hash:combine` parse my variable (object) from controller (`find('all', [...])->first();`)

### Expected Behavior
Works fine.

### Actual Behavior
Work fine, but show warning message like: "Argument 1 passed to Cake\Utility\Hash::combine() must be of the type array, object given"

Class `Hash` should be works with array and objects.

I do not want to use `toArray()` in controller.

**Comment by kicaj** [comment]
Simlar: https://github.com/cakephp/cakephp/issues/9144 but for Cake 2.x

**Comment by lorenzo** [comment]
Don't use `Hash` use the collection methods. For example:

```php
```

**Comment by lorenzo** [comment]
Closing as the purpose of `Collection` is to cover the cases where Hash is used, but for objects
