### ISSUE TITLE
Unlink() in class "BelongsToMany" should return bool

### ISSUE THREAD

**Issue by mo86** [cakephp/cakephp#9208]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Platform and Target: PHP, MySQL

### What you did
Tried to check if the unlink() Method in Class "BelongsToMany" has deleted the join data between two entities or not.

### Expected Behavior

if($this->Table->unlink($entity_a, [$entity_b])) {
//unlink wordked...
}

### Actual Behavior
unlink() doesnt return anything...

**Comment by markstory** [comment]
The documented return is `void`. Why does this need to return a boolean?

**Comment by mo86** [comment]
Yes I think returning "void" is not really helpful. The function above unlink() is link() and it also returns a boolean value. So unlink() should do this also.

**Comment by markstory** [comment]
Fair point.

**Comment by markstory** [comment]
Pull request up now.
