### ISSUE TITLE
FlashHelper render() escapes HTML - cake 3.2

### ISSUE THREAD

**Issue by ironbone** [cakephp/cakephp#9213]
In the book: 
http://book.cakephp.org/3.0/en/controllers/components/flash.html 
there is the info:

> By default, CakePHP does not escape the HTML in flash messages. If you are using any request or user data in your flash messages, you should escape it with h when formatting your messages.

What is not true. Just test
$this->Flash->success("\<strong\>Hello\</strong\> World");

**Comment by markstory** [comment]
The docs are accurate. The [default templates provided in the application skeleton](https://github.com/cakephp/app/blob/master/src/Template/Element/Flash/default.ctp#L7) does the escaping.
