### ISSUE TITLE
3.3 Configuration `Error.exceptionRenderer` doesn't work in middleware stack

### ISSUE THREAD

**Issue by batopa** [cakephp/cakephp#9214]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0-beta3 and 3.next branch.
* Platform and Target: apache, mysql, any request that throws an exception

### What you did
In `config/app.php` I have configured a custom exception renderer

```php
'Error' => [
        'errorLevel' => E_ALL & ~E_DEPRECATED,
        'exceptionRenderer' => 'App\Error\ExceptionRenderer',
        'skipLog' => [],
        'log' => true,
        'trace' => true,
    ],
```

### Expected Behavior
I expect that any exception was handled by `App\Error\ExceptionRenderer`

### Actual Behavior
Every exception is handled by `Cake\Error\ExceptionRenderer`.

I think that  `Cake\Error\Middleware\ErrorHandlerMiddleware` should read from configuration if custom exception renderer must be used instead of default.

The only way I found to use my custom renderer is pass it to `ErrorHandlerMiddleware` constructor in `Application.php`.

**Comment by ADmad** [comment]
The [Application::middlware()](https://github.com/cakephp/app/blob/3.next/src/Application.php#L41) can be updated to take into account Error config when setting up the middleware.

**Comment by ADmad** [comment]
Closing as related PR is opened.
