### ISSUE TITLE
[Feature] Add support for Helpers when rendering form widgets

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9219]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12

### What you did

Created a custom widget that renders a value as an HTML link.

### Expected Behavior

Be able to load the HTML helper and use the `HtmlHelper::link()` method.

### Actual Behavior

Can not load helpers from the `BasicWidget` base class. Unable to use the `HelperRegistry` because I don't have a reference to a `View`.

Had to render the HTML manually and use the static Router class.

**Comment by lorenzo** [comment]
You can actually get an instance of the view as indicated here:

https://github.com/cakephp/cakephp/blob/master/src/View/Widget/WidgetRegistry.php#L37

In an [array like this](https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L132-L143) make sure that you pass `_view` as one of the keys in the sub array.

**Comment by thinkingmedia** [comment]
@lorenzo Thank you!
