### ISSUE TITLE
validateUnique,basic validation on a date field, which is not scalar

### ISSUE THREAD

**Issue by cvl75** [cakephp/cakephp#9226]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.13
* Platform and Target: apache/mysql.

### What you did
In function validationDefault of a table a have a validateUnique for a date field like:
`$validator
            ->date('data')
            ->notEmpty( 'data' )
           ->add( 'data', 'unique', ['rule' => 'validateUnique', 'provider' => 'table', 'message' => '$validator says is not unique' ] )
		;`
In my application, before save, I learned in cookbook that is best practice to let newEntity analyze post data, then check for $record->errors();

### Expected Behavior
After 3.2.13, this basic validation fails because $field is  an object(Cake\I18n\Date), which is not scalar, therefore returns an early false on validateUnique.
@markstory suggested to transform from basic validation to application validation, which is done on save, so I commented $validator->add..., and I added in function buildRules() `$rules->add( $rules->isUnique( ['data' ] ) );` (am I right??)
But this means that after newEntity, $record->errors() is empty, so I tried  a try/catch:
`try { $id = $this->ExchangeRates->save( $record ); } 
catch (\Exception $e) { debug( $e );}`
But I didn't catch anything. $id is false, but no Exception.
After I removed $rules->add from buildRules, Mysql kick in, and I get an Exception for uniqueness.
So I end up with no validation, except that from Mysql ;).

That's what I could find(and understand) in cookbook/api about validating data, with my limited php knowledge. I am sure that there is at least one other smarter way of doing it, but basic validation was working for a date field until version 3.2.13.

**Comment by markstory** [comment]
Your `save()` call will have returned false, and `$entity->errors()` will contain the errors from the IsUnique rule.
