### ISSUE TITLE
multu timeout in session for keys

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9230]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did

hi,
we can not set time out for multi keys of session
with current behavior of session we cannot separate  them from each other,

for example we have user and admin session with separate session key
but we need users logout after x min and admin logout after y min 

we can not do it without manual code 

how can implement:
set time out in app.php like:
```
    'Session' => [
        'defaults' => 'cake',
        'timeout'=>20,
        'keysTimeout'=>[
            'Auth'=>15,
           'Auth.Admin'=>20,
           'User.Setting'=>60*24,
             
           ],
    ],
```

**Comment by dereuromark** [comment]
There is only one session here, having different keys inside still makes this the same storage and instance. As such your proposal does not really seem reasonable from a technical point of view IMO.
What you would need to do is to separate them as instances (different cookies then for example), which is usually done by using different TLDs or subdomains etc. But that is already possible as it stands.

**Comment by saeideng** [comment]
> There is only one session here as you describe it, having different keys inside still makes this the same storage and instance.

yes,but there is one timeout setting for that

> What you would need to do is to separate them as instances (different cookies then for example)

no,i need just able to expire keys of session separately
Cake\Network\Session::start() just check primary time out and destroy that
but `keysTimeout` just delete(no destroy) session's key if timeout of that key is expired 

for other example
1)maybe we need/interested story last visited pages view per user on session 
`key:User.lastVisited by 30 days until expire time`
2)save login information for user
`key:Auth.User by 1 days until expire time`

but just we can set one timeout for both of keys
we can override time out by Configure class but not good idea

**Comment by ADmad** [comment]
> no,i need just able to expire keys of session separately

Last I checked there's no feature in PHP to allow per session key expiration times.

**Comment by saeideng** [comment]
> Last I checked there's no feature in PHP to allow per session key expiration times.

php?
no need to php feature

i'm not sure ,just for a sample 
into Cake\Network\Session::start()
```
public function start()
...
        $this->_started = true;

        if ($this->_timedOut()) {
            $this->destroy();

            return $this->start();
        }
		foreach ($keysTimeOut as $key){
			if ($this->_KeystimedOut()) {
            	$this->detele($key);
			}
		}

        return $this->_started;

```

**Comment by dereuromark** [comment]
This is a very high level complexity on top of an an otherwise quite basic concept.
The overhead here does not necessarily justify the use, and thus this might not be suited as core functionality. Edge cases are usually best handled as plugin solution.

In this case you could easily write your own Session adapter as plugin extension and share that with everyone. I think this is the best approach here for this special use case.

**Comment by markstory** [comment]
I'm a :-1: for this. It is a lot of complexity that I don't see many people using.

**Comment by saeideng** [comment]
Ok,thanks @dereuromark , @ADmad  , @markstory 
i close it
