### ISSUE TITLE
Cake\Http\Client\Auth\Basic still uses Cake\Network\Http\Request

### ISSUE THREAD

**Issue by Cosmin-Ecom** [cakephp/cakephp#9233]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 84d3c04812a7b973d965ce84b65a9b8646201769 (3.3.0-RC1)
* Platform and Target: nginx, php-fpm, PHP 5.6.17

### What you did
use Cake\Http\Client;

$c = new Client(['auth' => ['username' => '...', 'password' => '...']]);
$c->get('http:/asdf.com');

### Expected Behavior
Request is made.

### Actual Behavior
Request is not made.
Error: Argument 1 passed to Cake\Http\Client\Auth\Basic::authentication() must be an instance of Cake\Network\Http\Request, instance of Cake\Http\Client\Request given, called in...

There is a class alias:
class_alias('Cake\Http\Client\Request', 'Cake\Network\Http\Request');
but seems it does not cover this case.

**Comment by markstory** [comment]
Pull request up now.
