### ISSUE TITLE
Bug validate equals

### ISSUE THREAD

**Issue by oanhnn** [cakephp/cakephp#9238]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12 , c318328d981cad94e223ec95c79fd0a2e98679bc

### What you did
```
<?php 
// a.php
require __DIR__ . '/config/bootstrap.php';
use Cake\Validation\Validator;

$validator = new Validator();
$validator->requirePresence('field')
            ->equals('field', 1);

debug($valudator->errors(['field'=>1]));
```

Run 
```
php a.php
```

### Expected Behavior
```
########## DEBUG ##########
[]
###########################
```

### Actual Behavior
```
########## DEBUG ##########
[
	'field' => [
		'equals' => 'The provided value is invalid'
	]
]
###########################
```

I found reason of this error:
**In method Cake\Validation\Validator::equals() , line 712**
https://github.com/cakephp/cakephp/blob/master/src/Validation/Validator.php#L732

```
        return $this->add($field, 'equals', $extra + [
            'rule' => ['comparison', '=', $value]
        ]);
```
I think It must be `==` .

**Comment by markstory** [comment]
You're totally right. I'll get that fixed up.

**Comment by markstory** [comment]
Pull request up now.
