### ISSUE TITLE
Question -> Computed Field along with fields from joining tables

### ISSUE THREAD

**Issue by haroonabbasi** [cakephp/cakephp#9239]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] Question

* CakePHP Version: 3.2 
* Platform and Target: Xamp

I have question, in cakephp 3 document [selecting-all-fields-from-a-table](http://book.cakephp.org/3.0/en/orm/query-builder.html#selecting-all-fields-from-a-table)

> // Only all fields from the articles table including
// a calculated slug field.
$query = $articlesTable->find();
$query
    ->select(['slug' => $query->func()->concat(['title', '-', 'id'])])
    ->select($articlesTable); // Select all fields from articles

i have query where i have 5-6 table in contain for joining to bring data along with computed field.

now from your document example passing table instance can bring all records along with computed field.

now my question is that for all the joining table how i can bring their data along with computed column.

I tried to pass joining table class instance within select but i am getting error.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Table2.id' in 'field list'

 to create table classes instance first then have to pass them in select to be able to be able to bring joined table data?

my query
>
        $table2 = TableRegistry::get('Table2');
		$query = $this->table1
                ->find('all')
                ->select(['computed_column' => 'A subquery here'])
                ->select($this->table1)
                ->select($table2)
                ->contain(['Table2','Table3','Table4','Table5'])
                ->where($conditions);

**Comment by markstory** [comment]
This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:
 
* [The CakePHP Manual](http://book.cakephp.org)
* [The CakePHP online API](http://api.cakephp.org)
* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than happy to help answer your questions.
 
Thanks!
