### ISSUE TITLE
Force to use application element with same name from inside plugin

### ISSUE THREAD

**Issue by hashmode** [cakephp/cakephp#9240]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.0-RC1

I have an element with same name `my_element.ctp` inside my `/src/Templates/Element/` and for the plugin `/plugins/MyPlugin/src/Templates/Element/`. I use the element of the main application in the layout: `$this->element('my_element')`. The problem is when accessing some controller/action of the plugin that uses the default layout of the application it tries to load the element of the plugin, which makes sense 
https://github.com/cakephp/cakephp/blob/master/src/View/View.php#L1147

So, if we add an option for `$options` array to disable checking the plugin, we might force to use the application's element requesting it from the plugin.
https://github.com/cakephp/cakephp/blob/master/src/View/View.php#L479

Something like this
https://github.com/cakephp/cakephp/compare/3.next...hashmode:patch-1#diff-cfb68b778e2105931c37743c65812a51
and we can use `<?php echo $this->element('my_element', [], ['plugin' => false]);?>`

**Comment by markstory** [comment]
Sounds like a reasonable change to me.

**Comment by hashmode** [comment]
@markstory  Should I update the methods' comments and create a PR or just leave it to be discussed/updated by the core team ?

**Comment by markstory** [comment]
Updating the comments to match the new behavior would be great.

**Comment by hashmode** [comment]
done, have committed to the same branch

**Comment by ADmad** [comment]
@hashmode You also need to open a pull request to get your changes merged.

**Comment by markstory** [comment]
Closing as a pull request is open now.
