### ISSUE TITLE
3.3 running Table::aliasField($field) multiple times should be idempotent

### ISSUE THREAD

**Issue by htstudios** [cakephp/cakephp#9244]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3 BETA 3

### What you did
Implicitly ran `Table::aliasField()` multiple times
Ref: https://github.com/FriendsOfCake/search/issues/111

### Expected Behavior
To only alias the field once - or at least have an option to do that.

### Actual Behavior
The fields where alias multiple times resulting in incorrect query-snipplets such as `Countries.Countries.code IN (:c0)`

**Comment by markstory** [comment]
Seems reasonable to me.

**Comment by htstudios** [comment]
Closing as PR is up, thanks to @ADmad
