### ISSUE TITLE
CakePHP 3 - how to call XMLWriter()

### ISSUE THREAD

**Issue by lupuswwww** [cakephp/cakephp#9250]
For the purposes of web application, I use an EXTERNAL php script (Library) written in plain PHP code. In class I call the following functions:

> $writer = new XMLWriter();

By calling these functions I get the error:

> Error: Class 'App\Lib\XMLWriter' not found
> File /root/src/Lib/Fiscalization.php
> Line: 201

I do not know what's wrong. This problem did not exist in CakePHP 2.

**Comment by ch4rl0tta** [comment]
Did u have corect path to app in composer.json?

```
  "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
```

**Comment by lupuswwww** [comment]
Problem solved:

> $writer = new \XMLWriter();

**Comment by ch4rl0tta** [comment]
Backslash is global namespace. If you dont using it then php will look in actualnamespace (diference betwen Cakephp3 and 2 which didn't use namespaces)

**Comment by antograssiot** [comment]
nothing related to CakePHP.
