### ISSUE TITLE
UNION used in a subquery context is broken with MySQL

### ISSUE THREAD

**Issue by Qrokqt** [cakephp/cakephp#9254]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.13
- Platform and Target: apache, mysql
### What you did

This is a contrived example

``` php
$q1 = $this->Companies->find()->select('id')->where(['name like' => '%test%']);
$q2 = $this->Companies->find()->select('id')->where(['name like' => '%test2%']);
$q = $this->Companies->find();
$q->where(['id in' => $q1->unionAll($q2)]);
```
### Expected Behavior

I would expect a query generated similar to

``` mysql
SELECT *
FROM companies
WHERE id in (
    SELECT id FROM companies WHERE name like '%test%'
    UNION ALL
    SELECT id FROM companies WHERE name like '%test2%'
)
```
### Actual Behavior

A query is generated with a bunch of extra parens that cause syntax errors, similar to

``` mysql
SELECT *
FROM companies
WHERE id in (
    (SELECT id FROM companies WHERE name like '%test%')
    UNION ALL
    (SELECT id FROM companies WHERE name like '%test2%')
)
```

**Comment by markstory** [comment]
Removing the `()` causes unions to fail in other contexts from what I remember.

**Comment by markstory** [comment]
Closing this as its been open a long time and there have been no additional reports. The lack of feedback on this makes me think this isn't something folks often do. I know that personally I don't often use unions let alone in subqueries.
