### ISSUE TITLE
TranslatorRegistry fallback loader

### ISSUE THREAD

**Issue by andrej-griniuk** [cakephp/cakephp#9257]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.13

### What you did
Is there any specific reason why there is no way to change `TranslatorRegistry` fallback loader?
Use case: want to use a custom loader. Currently can set it via `I18n::config()`, but have to register it manually for every domain. Want to set it as fallback loader instead.

**Comment by ADmad** [comment]
Ability to set your own fallback loader would be handy.

**Comment by andrej-griniuk** [comment]
Cool, I'll work on it. Just wanted to make sure I'm not missing something.
