### ISSUE TITLE
Migration snapshot for plugin, no schema dump default lock option

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/cakephp#9258]
This is a enhancement

* CakePHP Version: 3.2.13

### What you did
`bin/cake bake migration_snapshot -p Admin Init`

### Behavior
`config/Migrations/schema-dump-default.lock` in Admin plugin generated which is fine as I have been told it is used for [Generating a dump file for the diff baking feature](http://book.cakephp.org/3.0/en/migrations.html#dump-generating-a-dump-file-for-the-diff-baking-feature), but I think there should be option to not generate this file when you use it with plugin (same like you don't use composer.lock file)

I am happy to add option to the current list
![image](https://cloud.githubusercontent.com/assets/556169/17624052/4d0f63e0-60a3-11e6-915f-ba0f05fc5080.png)

I need to know if it's worth to add this option and what would be good naming?

Thanks

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#256
