### ISSUE TITLE
3.3.0: headers already sent

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9260]
After updating to cakephp to 3.3.0-RC1 and then to 3.3.0, in my logs I have something like this:

    2016-08-13 17:47:04 - Headers already sent in /home/mirko/Server/mirkopagliai/vendor/cakephp/cakephp/src/Routing/Filter/AssetFilter.php:148

I have hacked the core as it was recommended on StackOverflow ([here](I have modified the code as it was recommended on StackOverflow.)).

`src/Network/Response.php`, line `453`:

    $trace = \Cake\Error\Debugger::trace();
    Log::warning("Headers already sent in {$file}:{$line}\nStack Trace:\n{$trace}\n");

But all I can get is this log:

    2016-08-13 17:54:12 Warning: Headers already sent in          /home/mirko/Server/mirkopagliai/vendor/cakephp/cakephp/src/Routing/Filter/AssetFilter.php:148
    Stack Trace:
    Cake\Network\Response::sendHeaders() - CORE/src/Network/Response.php, line 452
    Cake\Network\Response::send() - CORE/src/Network/Response.php, line 429
    Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 70
    [main] - ROOT/webroot/index.php, line 37

This doesn't help me to figure out where is the problem and what is the problem. 
And I don't understand if the problem is the core or my app.

How to do?

**Comment by mirko-pagliai** [comment]
Perhaps the problem was simply due to the fact that I have not switch to the middleware objects, ok.

**Comment by markstory** [comment]
I'll look into fixing this. The `AssetFilter` should be compatible with a partially updated application.

**Comment by mirko-pagliai** [comment]
Thanks as always.

**Comment by markstory** [comment]
Pull request open now.
