### ISSUE TITLE
marshalProtocolVersion [UnexpectedValueException] Unrecognized protocol version (onclick= HTTP/1.1)

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#9264]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Apache, PHP 7

### What you did
Some program or user called a webpage (with CakePHP 3.3.0) of mine.

### Expected Behavior
I just think, this shouldn't happen - adapt parser or silently discard the exception. It is not necessary for running the/my application.

### Actual Behavior
[UnexpectedValueException] Unrecognized protocol version (onclick= HTTP/1.1)
IN: Zend\Diactoros\ServerRequestFactory::marshalProtocolVersion

**Comment by lorenzo** [comment]
What would silently discard mean for you?

**Comment by mdlouhy** [comment]
I don't know where this protocol version is used therefore I think a default value or NULL could be set in the globals if it couldn't be passed. Just to avoid an error/exception based on the wrong header.

**Comment by lorenzo** [comment]
Sending a wrong header is a valid error, I don't think it should be ignored.

**Comment by mdlouhy** [comment]
But it should be resolved. What can I do to handle it? I don't want to give the user an error page because of that - maybe he doesn't know why his browser sends this wrong header.

**Comment by markstory** [comment]
Your client is using an invalid HTTP version header though.

**Comment by mdlouhy** [comment]
I think if a visitor of my website sends some wrong headers, I should have the chance to give him a correct response but not an error message. I don't know which type of visitor it was I only got an error message in my logs.

**Comment by markstory** [comment]
> I think if a visitor of my website sends some wrong headers, I should have the chance to give him a correct response but not an error message

I don't disagree with you, how would you like to display a response to the user given we cannot build a request object out of their request?

**Comment by mdlouhy** [comment]
I really don't have an idea because it only happened once so far ...

**Comment by ADmad** [comment]
https://github.com/zendframework/zend-diactoros/issues/171

**Comment by markstory** [comment]
We could catch exceptions that come up during request building and emit a very simple 400 error. That would avoid the fatal error and give these naughty clients a proper HTTP response.

We can't really dispatch the request to the application allowing the developer to handle the error as there is no request to pass along.

**Comment by mdlouhy** [comment]
I'm fine with that ;)

**Comment by markstory** [comment]
@mdlouhy Ok.

**Comment by markstory** [comment]
Pull request open now.
