### ISSUE TITLE
locale not working

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#9265]
Hi,

I have create a plugin named "Default" and make a po file `/plugins/Default/src/Locale/zh_CN/default.po`
when I use `__d('default', 'foo')` at `/plugins/Default/src/Template/xxx.ctp`, it doesn't work；Is this a bug?
Later, I rename `default.po` to "foo.po" and use `__d('foo', 'foo')` , It does not get better.

Thanks!

**Comment by markstory** [comment]
How can someone reproduce this? Locale domains are working fine in the test suite and in debugkit.

**Comment by slince** [comment]
You can rename your plugin name to "Default" and try again @markstory

**Comment by markstory** [comment]
Default will overlap with the 'default' domain  which is used for the application. It won't be possible to have 'default' mean 2 different things.

I don't think there is a way for us to make plugin domains work for plugins called `Default` without breaking existing use cases. I'm also not sure `Default` will work well as a namespace name as `default` is a [reserved keyword](http://php.net/manual/en/reserved.keywords.php) in PHP.

**Comment by slince** [comment]
@markstory  Plugin `Default` is only a theme and don't have php code. It work well except locale.

**Comment by slince** [comment]
Why cakephp have so much reserved keyword ? Does `Default` means reserved keyword ? Any docs mention that I should not make a `Default` plugin?

**Comment by slince** [comment]
![image](https://cloud.githubusercontent.com/assets/3785826/17685879/87a9c4ec-639a-11e6-95ff-4fe4ad1a89ac.png)

**Comment by markstory** [comment]
@slimus We figured that using `default` was reasonable given that it cannot be used in a class name. We didn't consider the scenario where someone would build a theme that contains no classes.

You wouldn't be able to put `foo.po` inside your Default theme, you could however, put `foo.po` inside a `Foo` theme/plugin which will work.

**Comment by slince** [comment]
@markstory  Thanks,  I will do some try
