### ISSUE TITLE
Cake\Network\Request::$_detectorCache makes no sense

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9269]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

[This](http://api.cakephp.org/3.2/source-class-Cake.Network.Request.html#647) looks like a serious bug.
The result seems is cached only based on his "type."

Suppose that I am working with the `Posts` controller and I have this detector:

    Request::addDetector('controller', function($request, $controller) {
        return $request->param('controller') === $controller;
    });

So this

    $this->request->is('controller', 'Posts')
returns `TRUE` and this

    $this->request->is('controller', 'OtherController')
returns `FALSE`

But, always in the `Posts` controller, this

    $this->request->is('controller', 'Posts')
    $this->request->is('controller', 'OtherController')

returns `TRUE` and `TRUE` and this

    $this->request->is('controller', 'OtherController')
    $this->request->is('controller', 'Posts')

returns `FALSE` and `FALSE`.

Then one of these:
1) removing the cache;
2) the cache must also consider the **correspondence of the same arguments**.

Am I doing something wrong or have I understand correctly?

**Comment by mirko-pagliai** [comment]
To be clear, instead of this:

        if (!isset($this->_detectorCache[$type])) {
            $this->_detectorCache[$type] = $this->_is($type, $args);
        }

        return $this->_detectorCache[$type];

we need something like this:

        $cacheKey = serialize([$type, $args]);
        
        if (!isset($this->_detectorCache[$cacheKey])) {
            $this->_detectorCache[$cacheKey] = $this->_is($type, $args);
        }

        return $this->_detectorCache[$cacheKey];

(it's just an example to make it clear)

**Comment by markstory** [comment]
The detector cache predates detectors getting arguments, which is why it is not working correctly. The simplest solution might be to just remove the detector cache. Or not rely on the detector cache when there are additional arguments.

**Comment by mirko-pagliai** [comment]
> Or not rely on the detector cache when there are additional arguments.

For me, the cache can be useful just when I have a callable with a variety of args to be verified. Otherwise, it's not that there's all this savings using the cache.

@markstory you do not like the idea of using a cache key that also consider the arguments? (see my prev comment)

**Comment by lorenzo** [comment]
I did not know `is()` took more than one argument!

**Comment by mirko-pagliai** [comment]
@lorenzo see https://github.com/cakephp/cakephp/pull/8537 and https://github.com/cakephp/cakephp/pull/8550

**Comment by mirko-pagliai** [comment]
Ok, come to think we should just remove the cache.
I think for example if a detector checks the client IP...

**Comment by mirko-pagliai** [comment]
Created pull request https://github.com/cakephp/cakephp/pull/9271
