### ISSUE TITLE
Prefix when joining manually

### ISSUE THREAD

**Issue by mcp84** [cakephp/cakephp#9270]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.1
* Platform and Target: Windows 2012 R2 IIS 8, MySQL

### What you did
Tried to join another table without a prefix with a model which has a prefix in the database-config. 

config.hp: 
```
public $someConfig= array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'host',
		'port' => 3306,
		'login' => 'login',
		'password' => 'password',
		'database' => 'someotherdatabase',
		'prefix' => 'prefix_',
		'encoding' => 'utf8'
	);
```

Model:

```
class SomeModel extends AppModel {
	public $useDbConfig = 'someConfig';
```

Controller:
```
$findOptions = array(
...
'joins' => array(
    array(
        'table' => 'somedatabase.sometable',
        'alias' => 'someAlias',
        'conditions' => 'someConditions'
     )
)
...);
$this->SomeModel->find('all', $findoptions);
```

### Expected Behavior
It should join `somedatabase.sometable` without the prefix of `SomeModel`.

### Actual Behavior
The prefix is put in front of the joined tables database which creates an error: unknown table or database `prefix_somedatabase.sometable`

**Comment by markstory** [comment]
Prefixes should be applied to join tables. If we were to change the behavior existing applications would be broken.

**Comment by mcp84** [comment]
But what you could do is to add a parameter `prefix` to the `joins` of the find options so it can be changed.
