### ISSUE TITLE
date fields as string in contained belongsToMany entities 

### ISSUE THREAD

**Issue by arilia** [cakephp/cakephp#9278]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.0

### What you did
I have a model with a belongsToMany relationship with another model. Let's say `Users` belongsToMany `Tasks`

I did a simple query

    $this->Users->find('all')
            ->contain(['Tasks']);

### Expected Behavior

I expected datetime fields (as `created` or `modified`) in tasks beein displayed as Cake\I18n\Time objects

### Actual Behavior

datetime fields are beeing displayed as strings i.e.

`'created' => '2014-02-20 12:35:09',`
`					'modified' => '2015-03-06 10:05:29',`

did a research in the other issues and in the documentation and did not find anything about it.

**Comment by dereuromark** [comment]
Did you attach the Timestamp behavior to those tables?
What is your table setup here?

**Comment by arilia** [comment]
Yes, I did attach the Timestamp behavior to those tables.

Anyway it's not just about created and modified fields. 

I have other datetime fields and they all are displayed as string for that table. 

I did a couple of tests with other models and the same happens: with belongsTo and hasMany all the date and datetime fields are displayed as Time objects (as expected), instead with belongtTomany the time columns are shown as strings

**Comment by antograssiot** [comment]
Could you please try to use the master branch, it should already have been fixed in #9266

**Comment by lorenzo** [comment]
This is fixed in master, will release a new version soon as another issue needs to be fixed first. Thanks for your patience.

**Comment by arilia** [comment]
I think I can wait till the new version. 

Thanks you all.
