### ISSUE TITLE
Use &hellip; instead of three dots

### ISSUE THREAD

**Issue by aiphee** [cakephp/cakephp#9279]
- [x] Enhancement
- CakePHP Version: 3.3

I know this is rather silly, but in text helper, pagination and etc, there is `...` instead of sematically correct `…`

Hellip is used nowhere in CakePHP, so, i guess it might be a bug.

Similar ticket: https://www.drupal.org/node/847608

**Comment by dereuromark** [comment]
Some methods are actually context specific, and if HTML is the scope it uses the proper character:
https://github.com/cakephp/cakephp/blob/master/src/Utility/Text.php#L585-L587

This should just be ported to the other methods that support both plain-text and HTML context.

**Comment by aiphee** [comment]
Oh, that didnt occur to me to search for unicoded charachters, i thought i had to do this:
```PHP
$value = Text::truncate($setting->value, $max_len, ['ellipsis' => '&hellip;']);
```

but as you posted, this works fine too:
```PHP
$value = Text::truncate($setting->value, $max_len, ['html' => true]);
```

So my problem with this solved i guess.

**Comment by dereuromark** [comment]
I agree, you could make a PR to fix the default template here.

**Comment by inoas** [comment]
1. 👍 - Horizontal ellipsis has meaning. It also won't easily break into two lines, which is good (and <nobr>...</nobr> is a lot of surplus markup)
2. Could you please use `…` over `&hellip;` in the PR?
Latter is specific to HTML, while former (pure UTF-8) can be used within XML, JSON, Non-HTML-Emails and whatnot.

**Comment by aiphee** [comment]
OK, i created #9280 
Should i also make commit for `tail` and `excerpt`?

@inoas are you sure it is better to use `…` over `&hellip;` even in `<li></li>`?

**Comment by dereuromark** [comment]
I would use `&hellip;` here as I mentioned before. `...` is not a good default for HTML context.

**Comment by htstudios** [comment]
Why is that not? It is perfectly fine and named html-entities (aside a few like gt lt amp) are not supported when using html as xml. 

It also works across JSON without making assumptions how the text is rendered (in a PDF, in plaintex, in html...).

Because of that using the utf-8 notation is better.

Any good reason why not to use it?

**Comment by dereuromark** [comment]
Ah, you mean the utf8 version of it? Thats OK, I thought you meant three normal `.`^^

**Comment by inoas** [comment]
Yes I meant to always use real utf8 entities to improve interoperability. 

All good :) (p.s.: account jugglong comes to an end soon; sorry!)

**Comment by aiphee** [comment]
OK, i created another PR #9281
Hope this one is right.

**Comment by dereuromark** [comment]
Closing as PR is open.
