### ISSUE TITLE
Static table objects

### ISSUE THREAD

**Issue by fheider** [cakephp/cakephp#9282]
Is it possible (maybe in CakePHP 4) to use static table objects instead of autoloading or the use of the TableRegistry. The idea is inspired by the Yii Framework and I use it similarly in CakePHP3. I think it's more readable and reduce the code.

Example:

CP3 with autoloading

    $entity = $this->Users->newEntity();
    $entity = $this->Users->patchEntity($entity);
    if ($this->Users->save($entity)) { ... }

CP3 without autoloading

    $entity = TableRegistry::get('Users')->newEntity();
    $entity = TableRegistry::get('Users')->patchEntity($entity);
    if (TableRegistry::get('Users')->save($entity)) { ... }

Static table objects

    $entity = UsersTable::create();
    $entity = UsersTable::patch($entity);
    if (UsersTable::save($entity)) { ... }

What would you say?

**Comment by markstory** [comment]
I'm personally not a fan of static methods. They can complicate testing and mocking. There are ways around that - laravel's facades for example, but we've been trying to trend away from that kind of behavior.

**Comment by lorenzo** [comment]
That would require having static methods, which makes a lot of stuff very difficult to manage. You can do this yourself in your own app, though. I don't think there is a need for cake to go there

**Comment by josegonzalez** [comment]
We could provide the laravel "facade" pattern - though I'm 👎 on the look of it regardless - so that we can avoid statics. Though if we do so, lets call it what it is, since the facade pattern is actually a bit different from what laravel calls facades...

You can assign the retrieved table to a variable:

```php
$users = TableRegistry::get('Users');
$entity = $users->newEntity();
$entity = $users->patchEntity($entity);
if ($users->save($entity)) { ... }
```

**Comment by inoas** [comment]
I am not sure how laravel does it with its facades but if its real statics a big no from me. Statics are like globals in a way. Alone the `DateTime::` things being global statics made my life very uneasy.

I do however think that in case you like the look, why not look up how laravel does it and implement it as a plugin for CakePHP3 if possible. Then, if that gets a lot of traction, that's the way to change minds ;)

**Comment by dereuromark** [comment]
I agree, first try this as plugin solution, then we can see.
Shall we close then as works-for-me?

**Comment by markstory** [comment]
A plugin that implements this would be great! It helps prove out the ideas and find out corner cases.

**Comment by markstory** [comment]
A plugin that implements this would be a great way to test out the ideas and figure out an implementation that will work. I did that when I was working on the PSR7 implementation for 3.3.

**Comment by fheider** [comment]
https://github.com/fheider/cakephp-orm

I'm no professional, coded quick and dirty, but it works. :D
