### ISSUE TITLE
ORM should allow inserts with no data specified

### ISSUE THREAD

**Issue by ryantxr** [cakephp/cakephp#9285]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3 EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: Apache, MySQL, PHP7.

### What you did
I am attempting to insert into a table, specifying no data.  It throws a RunTimeException claiming that there must be at least 1 column when inserting rows.

    class Identity extends Table
    {
        public function generate() {
            $identity = $this->newEntity();
            if ( $this->save($identity) ) {
                // The $identity entity contains the id now
                \Cake\Log\Log::debug(__METHOD__. ' success');
                return $identity->id;
            }
            \Cake\Log\Log::debug(__METHOD__. ' failed');
            return false;
        }
    } 

### Expected Behavior
The insert should happen using default values specified when the database was created.  This is perfectly valid and works in 2.x and SQL.

### Actual Behavior
The ORM refuses to do the insert because no columns were passed to it.

I did an experiment and commented out the checking for at least 1 column to insert and it worked.

File: src/ORM/Table.php (line 1659)

        $success = false;
        // comment out the next 3 lines
        // if (empty($data)) {
        //     return $success;
        // }

File: src/Database/Query.php (line 1341)

        if (empty($columns)) {
            // comment out throw
            //throw new RuntimeException('At least 1 column is required to perform an insert.');
        }

**Comment by lorenzo** [comment]
I'm not sure allowing this on the Table class is a good idea, for the rare cases where you need this I'd suggest using a query instead of a Table save.

**Comment by dereuromark** [comment]
What is the downside of allowing this?
Seems like someone wants to just add empty rows with default values, which could be a legitimate case.
Could there be a flag/option added which when set bypasses this check?

**Comment by lorenzo** [comment]
To be honest, I think this is more a limitation in the Query object than in the Table. So, probably allowing it there would automatically allow the other

**Comment by dereuromark** [comment]
@ryantxr Are you able to provide a PR with the changes and a test? Then we can more easily discuss this and see if that is mergeable.

**Comment by ryantxr** [comment]
I will create a PR. As I pointed out in the original post that this requires changes to Table and Query.

**Comment by markstory** [comment]
You can create entities with the default table values by accessing the schema reflection.

```php
$defaults = $this->schema()->defaultValues();
$identity = $this->newEntity($defaults);
$this->save($identity);
```

I too would prefer to not have saving records with no columns.

**Comment by inoas** [comment]
Could you add this to the docs?

**Comment by ryantxr** [comment]
I tried changing the code to allow this and ran all the tests.  There are a number of tests that specifically test for this scenario and those tests now fail.  If this functionality were allowed, then those tests would either have to be deleted or modified.

It also seems like Postgres doesn't like inserting a row with no data.  MySQL is fine with it.

**Comment by markstory** [comment]
> It also seems like Postgres doesn't like inserting a row with no data. MySQL is fine with it.

This is one of the reasons we can't realistically support it.

**Comment by thinkingmedia** [comment]
I think `$this->save($this->newEntity([])) === false` is perfectly logical. 

The reason is not about the query builder, but about the state management of entities. We have to assume that the following assertion is true.

```
    $this->newEntity([])->isDirty() === false
```

That is why `save()` is failing, because nothing was set to mark the entity dirty. I can see many scenarios where that would be the expected result.

Keep in mind how many times this kind of code has been used in the wild.

```
     public function edit() {
          if($this->request->is('post')) {
               $table->save($table->newEntity($this->request->data));
          }
     }
```

I would not want an empty POST to be treated **differently** than one that had a body.

**Comment by ryantxr** [comment]
> > It also seems like Postgres doesn't like inserting a row with no data. MySQL is fine with it.
> 
> This is one of the reasons we can't realistically support it.

From the minimal checking I did, this **seems** to be the case.  Don't take my comment as a definitive statement.

And I think this functionality could be supported.

1. Cake 2 supported it and it did not seem to be a problem.
2. Programmers can easily check that there is data if that's the behavior they want.
3. The insert can still fail for many other reasons.
4. It is a valid use case.

If the functionality remains as is, a programmer must use SQL or directly modify the cake code.

**Comment by ADmad** [comment]
> If the functionality remains as is, a programmer must use SQL or directly modify the cake code.

No they don't. @markstory already showed how to create new record with defaults.

I too am in favor of not allowing to save empty entities.

**Comment by ryantxr** [comment]
@markstory 's solution does not work with a table that only has a primary key.  There are no other fields and get defaults will return no fields.  That being said, it seems obvious that this discussion isn't going to result in convincing this group contrary to its opinions and preferences.

Unless there is something more to add, I will close the issue.

Thank you all for the interaction.

**Comment by lorenzo** [comment]
@ryantxr is there a reason for you to use an entity? I can be done very easily with a single query, you may add this query as a method in your table if you wanted

**Comment by ryantxr** [comment]
Thanks @lorenzo. I already did that and the code is working.  

The question I would ask is should a framework require someone to do SQL in a case like this.  In my mind it should not. But that's just me.

Thanks again for all the input.
