### ISSUE TITLE
default transport in mail class

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9286]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
hi
in cake 2.x
we can use `deliver('you@example.com', 'Subject', 'Message', ['from' => 'me@example.com']);` form

Because CakeEmail::deliver() use default `trasport` in line
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/Email/CakeEmail.php#L962

but in cake 3.x
cake have not /not use default 'transport' when we not use transport in passed array arg 
and we should be use this form 
`deliver('you@example.com', 'Subject', 'Message', ['transport'=>'default','from' => 'me@example.com']);`

however we have not `fast` profile in cake v3.x  :stuck_out_tongue_winking_eye:
https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1389

**Comment by markstory** [comment]
Looks like we need to change the default value for deliver().

**Comment by markstory** [comment]
Pull request open now.
