### ISSUE TITLE
Passing an invalid email to Cake\Mailer\Email->to() causes an unrecoverable exception

### ISSUE THREAD

**Issue by davalb** [cakephp/cakephp#9288]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Linux / Apache

### What you did
Passed an email address with a space at the end like 'info@example.com ' to Cake\Mailer\Email->to()

### Expected Behavior
It should be possible to catch this error and resume the excecution of the script like:
```
try
{
    $email->to('info@example.com '); 
}
catch(InvalidArgumentException $ex)
{
   // error
}
```

### Actual Behavior
InvalidArgumentException is thrown and excecution is stopped

Somebody asked the same question here: https://groups.google.com/forum/#!topic/cake-php/3a8iNyZEC6w but no answer

I am willing to write and submit a PR, if you think this needs to change

**Comment by ADmad** [comment]
You need to catch `\InvalidArgumentException` instead of `InvalidArgumentException` (or add `use InvalidArgumentException` at top of your file.

**Comment by davalb** [comment]
You're right. Thanks a lot and sorry for posting this false alarm issue.
