### ISSUE TITLE
Marshaller Problem by saving BelongsToMany Association with TranslateBehavior attached

### ISSUE THREAD

**Issue by gillaho** [cakephp/cakephp#9289]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Apache, MySQL, PHP7.

### What you did
I have two languages (**EN** & **DE**) in my CakePHP app and **DE** is the **default language**. 
And also I have attribute and attribute value tables and these tables have BelongsToMany association. TranslateBehavior is attached to both tables  like so:

AttributesTable
```
$this->addBehavior('Translate', ['fields' => ['name'], 'translationTable' => 'translation_attributes']);
$this->belongsToMany('AttributeValues', [
      'foreignKey' => 'attribute_id',
      'targetForeignKey' => 'attribute_value_id',
      'joinTable' => 'attributes_attribute_values',
      'className' => 'AttributeValues'
]);
```

AttributeValuesTable
```
$this->addBehavior('Translate', ['fields' => ['name'], 'translationTable' => 'translation_attribute_values']);
$this->belongsToMany('Attributes', [
     'foreignKey' => 'attribute_value_id',
     'targetForeignKey' => '_attribute_id',
     'joinTable' => 'attributes_attribute_values',
     'className' => 'Attributes'
]);
```

Now with that setup I am trying to save BelongsToMany association data. The request data looks like following:
```
[
	'attribute_group_id' => '1',
	'parent_id' => '15',
	'code' => 'test_attribute',
	'name' => 'Test Attribute',
	'type' => 'select',
	'description' => 'This is a test attribute',
	'sort_order' => '1',
	'attribute_values' => [
		'_ids' => [
			(int) 0 => '1'
		]
	]
] 
```

With default language **(DE)** I can save that request data without problem. Attribute values will be correctly assigned to attributes (Data will be correctly saved in attributes_attribute_values table). But if I use another language **(EN)** those data cannot be saved in attributes_attribute_values table. 

I check how my entity looks like before save and I found this problem:

**DE** - All looks fine. Request data is correctly converted into object.
```
object(App\Model\Entity\Attribute) {
	'id' => (int) 16,
	'attribute_group_id' => (int) 1,
	'parent_id' => (int) 15,
	'code' => 'test_attribute',
	'name' => 'Test Attribute',
	'type' => 'select',
	'description' => 'This is a test attribute',
	'sort_order' => (int) 1,
	'created' => object(Cake\I18n\Time) {
		'time' => '2016-08-12T15:08:06+02:00',
		'timezone' => 'Europe/Berlin',
		'fixedNowTime' => false
	},
	'modified' => object(Cake\I18n\Time) {
		'time' => '2016-08-12T15:08:06+02:00',
		'timezone' => 'Europe/Berlin',
		'fixedNowTime' => false
	},
	'attribute_values' => [
		(int) 0 => object(App\Model\Entity\AttributeValue) {
			'id' => (int) 1,
			'name' => 'Test 1',
			'created' => object(Cake\I18n\Time) {
				'time' => '2016-08-08T10:38:18+02:00',
				'timezone' => 'Europe/Berlin',
				'fixedNowTime' => false
			},
			'modified' => object(Cake\I18n\Time) {
				'time' => '2016-08-17T12:30:08+02:00',
				'timezone' => 'Europe/Berlin',
				'fixedNowTime' => false
			},
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'AttributeValues'
		}
	],
	'[new]' => false,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'description' => true,
		'attribute_values' => true
	],
	'[original]' => [
		'description' => null,
		'attribute_values' => []
	],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Attributes'
}
```

**EN** - _ids is not converted into object(App\Model\Entity\AttributeValue)
```
object(Spabooking\Model\Entity\SpaHotelAttribute) {

	'id' => (int) 16,
	'attribute_group_id' => '1',
	'parent_id' => '15',
	'code' => 'test_attribute',
	'name' => 'Test Attribute',
	'type' => 'select',
	'description' => 'This is a test attribute',
	'sort_order' => '1',
	'created' => object(Cake\I18n\Time) {
		'time' => '2016-08-12T15:08:06+02:00',
		'timezone' => 'Europe/Berlin',
		'fixedNowTime' => false
	},
	'modified' => object(Cake\I18n\Time) {
		'time' => '2016-08-12T15:08:06+02:00',
		'timezone' => 'Europe/Berlin',
		'fixedNowTime' => false
	},
	'attribute_values' => [
		'_ids' => [
			(int) 0 => '1'
		]
	],
	'_locale' => 'en',
	'[new]' => false,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'attribute_group_id' => true,
		'parent_id' => true,
		'code' => true,
		'name' => true,
		'type' => true,
		'description' => true,
		'sort_order' => true,
		'attribute_values' => true
	],
	'[original]' => [
		'attribute_group_id' => (int) 1,
		'parent_id' => (int) 15,
		'description' => null,
		'sort_order' => (int) 1,
		'attribute_values' => []
	],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Attributes'
}
```

So I check **Marshaller.php** and this function **_buildPropertyMap($data, $options)**. There I found following codes:
```
     $map[$assoc->property()] = $callback;
}

$behaviors = $this->_table->behaviors();
foreach ($behaviors->loaded() as $name) {
    $behavior = $behaviors->get($name);
    if ($behavior instanceof PropertyMarshalInterface) {
        $map = $behavior->buildMarhshalMap($this, $map, $options);
    }
}
```

If I use TranslateBehavior, the map variable will be reseted, so I lose all the property map for the associations. So since **DE** is the default language, the TranslateBehavior is not loaded and I get the correct property map, but if I choose **EN** I only have property map for the translations like below:

**DE Property Map**
```
[
	'attribute_group_id' => object(Closure) {
		
	},
	'parent_id' => object(Closure) {
		
	},
	'code' => object(Closure) {
		
	},
	'name' => object(Closure) {
		
	},
	'type' => object(Closure) {
		
	},
	'description' => object(Closure) {
		
	},
	'sort_order' => object(Closure) {
		
	},
	'attribute_group' => object(Closure) {
		
	},
	'parent_attribute' => object(Closure) {
		
	},
	'child_attributes' => object(Closure) {
		
	},
	'attribute_values' => object(Closure) {
		
	},
	'attributes_attribute_values' => object(Closure) {
		
	}
]
```

**EN Property Map**
```
[
	'_translations' => object(Closure) {
	
	}
]
```

If I change this line in _buildPropertyMap function in Marshaller.php
`$map = $behavior->buildMarhshalMap($this, $map, $options);`
into
`$map += $behavior->buildMarhshalMap($this, $map, $options);`
I can save the BelongsToMany data correctly. The **_ids** will be correctly converted into **object(App\Model\Entity\AttributeValue)**

My question is:
- Is this a bug? or I didn't implement the TranslateBehavior correctly? 

But with above fix I can save the data without problem.

### Expected Behavior
No matter what language I select (DE or EN), attribute values and attributes pairing should be correctly saved in attributes_attribute_values table.

### Actual Behavior
Attribute values and attributes pairing  can only be saved in attributes_attribute_values table if I choose default language.

**Comment by markstory** [comment]
>  Is this a bug? or I didn't implement the TranslateBehavior correctly?

This is a problem in the marshaller. I'll get that fixed. Thank you for the detailed issue :smile:

**Comment by markstory** [comment]
Pull request up now.
