### ISSUE TITLE
CrossSchemaTableExpression (since 3.3) causing SQL generation issue

### ISSUE THREAD

**Issue by bijal** [cakephp/cakephp#9293]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: Apache,PHP7,MySQL

### What you did
We use multiple DBs with appropriate datasource configurations.

    'Datasources' => [
    	'db1' => [ //primarily used for generating baked models
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
               :
            'database' => 'db1',
               :
    	],
    	'db2' => [ //primarily used for generating baked models
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
               :
            'database' => 'db2',
               :
    	]

Our model classes use following syntax where it specifies fully qualified names of tables (schema.table). Without this specific syntax the SQL queries are not generated correctly (as it doesn't prepend the schema names in multi DB joins).

```PHP
class Model1Table extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->table('db1.model1');
    }
    public static function defaultConnectionName()
    {
        return 'db1';
    }
}

class Model2Table extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->table('db2.model2');
    }
    public static function defaultConnectionName()
    {
        return 'db2';
    }
}
```
### Expected Behavior
This was creating valid SQL queries (pre-3.3 CakePHP) similar to below:

```SQL
SELECT Model1.id                 AS `Model1__id`,
       Model2.id                 AS `Model2__id`
FROM db1.model1    Model1
     LEFT JOIN db2.model2 Model2 ON Model2.id = (Model1.id)
WHERE (   
       Model1.id = :c1
      )
```
### Actual Behavior
However, after the upgrade to 3.3, it creates invalid SQL queries like below:

```SQL
SELECT Model1.id                 AS `Model1__id`,
       Model2.id                 AS `Model2__id`
FROM db1.db1.model1    Model1
     LEFT JOIN db2.db2.model2 Model2 ON Model2.id = (Model1.id)
WHERE (   
       Model1.id = :c1
      )
```

Reason for this seems to be the following code in CrossSchemaTableExpression .php where it has started generating qualifying table names.

```PHP
    /**
     * Converts the Node into a SQL string fragment.
     *
     * @param \Cake\Database\ValueBinder $generator Placeholder generator object
     * @return string
     */
    public function sql(ValueBinder $generator)
    {
        $schema = $this->_schema;
        if ($schema instanceof ExpressionInterface) {
            $schema = $schema->sql($generator);
        }

        $table = $this->_table;
        if ($table instanceof ExpressionInterface) {
            $table = $table->sql($generator);
        }

        return sprintf('%s.%s', $schema, $table);
        //return sprintf('%s', $table); //temporary work around till the issue gets fixed
    }
```

As a work around for now, I have modified the code (see the commented line above).

We tried removing the qualified names from our models so that it looks like below:

```PHP
class Model1Table extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->table('model1');
    }
    public static function defaultConnectionName()
    {
        return 'db1';
    }
}
```

However, then it creates other problems. While it does generate properly qualified names in some places, it doesn't qualify them at all in other places creating ambiguous queries.

Ideal solution should be that Cake should generate fully qualified names in all circumstances so that developer doesn't need to change initialize method to modify table name (by manually putting schema.table qualified names).

**Comment by markstory** [comment]
We're considering removing the CrossSchemaTableExpression feature. It has created a number of problematic scenarios and we're not sure its worth keeping around, when there are other solutions like setting `table()` as you were before.

**Comment by markstory** [comment]
Closing as the CrossSchemaTableExpression was removed.
