### ISSUE TITLE
3.3 Dispatch filters are executed twice

### ISSUE THREAD

**Issue by Xymanek** [cakephp/cakephp#9296]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3
* Platform and Target: irrelevant

### What you did

1. Make a fresh install of `cakephp/app` (version 3.2.6)
2. In `composer.json` change `"cakephp/cakephp": "~3.2"` to `"~3.2.0"` in order to get Cake **3.2**
3. Create an [action](https://github.com/Xymanek/cake3.3-filters/blob/master/src/Controller/PagesController.php#L31-L35) and a [route](https://github.com/Xymanek/cake3.3-filters/blob/master/config/routes.php#L46) for it
4. Verify that browser gets `<p>Response body</p>` from server
5. Create a [filter](https://github.com/Xymanek/cake3.3-filters/blob/master/src/Routing/Filter/MyFilter.php) and [add](https://github.com/Xymanek/cake3.3-filters/blob/master/config/bootstrap.php#L207) it
6. Verify that browser gets `<p>Response body</p><p>Filter-appended content</p>` from server
7. In `composer.json` change `"cakephp/cakephp": "~3.2.0"` to `"~3.3.0"` in order to get Cake **3.3**
8. `composer update`
9. Open/reload the test page in browser

### Expected Behavior
One would expect the behavior to remain constant and receive `<p>Response body</p><p>Filter-appended content</p>` from server

### Actual Behavior
In reality the browser receives `<p>Response body</p><p>Filter-appended content</p><p>Filter-appended content</p>`. As you can see, the filter was run twice.

### Source of error
I've traced the problem to the new `\Cake\Http\ActionDispatcher` class. The problem itself is that all filters are added twice. Stuff goes as follows:

1. Filters are [`\Cake\Routing\DispatcherFactory::add`ed](https://github.com/Xymanek/cake3.3-filters/blob/master/config/bootstrap.php#L204-L207) in `config/bootstrap.php`
2. The dispatcher [is created](https://github.com/Xymanek/cake3.3-filters/blob/master/webroot/index.php#L33) **with** [the filters](https://github.com/cakephp/cakephp/blob/master/src/Routing/DispatcherFactory.php#L84-L86)
3. `\Cake\Routing\Dispatcher::dispatch` is [called](https://github.com/Xymanek/cake3.3-filters/blob/master/webroot/index.php#L34-L37) and it [creates a new instance](https://github.com/cakephp/cakephp/blob/master/src/Routing/Dispatcher.php#L61) of `\Cake\Http\ActionDispatcher`
4. `\Cake\Http\ActionDispatcher::__construct` [adds all filters](https://github.com/cakephp/cakephp/blob/master/src/Http/ActionDispatcher.php#L66-L68) from `\Cake\Routing\DispatcherFactory`
5. `\Cake\Routing\Dispatcher::dispatch` itself [adds the filters](https://github.com/cakephp/cakephp/blob/master/src/Routing/Dispatcher.php#L62-L64) (that were added to it in step 2) to `\Cake\Http\ActionDispatcher`

So the end result is that the whole filter stack is added twice during runtime which causes the double execution of all event handlers, etc. I know that 3.3 depreciates filters but it shouldn't mean that the code is broken just because the project is updated to 3.3 but didn't switch to middleware yet

P.S. The complete test project can be found [here](https://github.com/Xymanek/cake3.3-filters)
P.P.S. I discovered this while trying to understand why DebugKit records every request twice. It took me **very** long time to figure this out so I hope I didn't make any mistake while writing this :smile:

**Comment by davidyell** [comment]
Not sure if it's related but when I upgraded my application to `3.3.0` I found that my events were being triggered twice.

**Comment by Xymanek** [comment]
@davidyell What events are you talking about? Custom or built-in? Was the event dispatched twice or were listeners invoked twice for same dispatch (I hope that makes sense :smile:)?

**Comment by davidyell** [comment]
My own events were dispatched twice, so the event listener method was
executed twice.

**Comment by Xymanek** [comment]
@davidyell Then it's a different issue than what I described here

**Comment by davidyell** [comment]
If events are dispatched using the dispatcher, then it sounds similar, which is why I said "not sure if it's related". I was just hoping to add some extra background and other possible side effects.

**Comment by Xymanek** [comment]
@davidyell The **events** are dispatched using **event manager**. The **dispatcher** itself deals with **requests**.

However the **Dispatcher** also **uses** the **event system** and _dispatches events_ through **Event Manager**

I hope I cleared any confusion

**Comment by markstory** [comment]
Thanks for the detailed issue, I'll get this fixed up.

**Comment by markstory** [comment]
I think #9301 fixes this, and reduces our reliance on global state.
