### ISSUE TITLE
RFC:  Bump PHP version to 5.6 for CakePHP 3.4

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#9297]
Following new features of PHP 5.6 would pretty useful among others:

* variadic
* argument unpacking
* `use` for function

Also PHP 5.5 is EOL.

**Comment by markstory** [comment]
Variadics will make a bunch of internals a bit simpler to deal with.

**Comment by antograssiot** [comment]
That would also allow to use only one version of PHPUnit and simplify testing.

**Comment by dereuromark** [comment]
We can also use the new phpunit5.2+, which also introduces some new [best practice approaches](https://thephp.cc/news/2016/02/questioning-phpunit-best-practices):
- explicit ::class usage (less error prone with namespaces, especially when refactoring)
- explicit point in time when the expected exception is being thrown

**Comment by ADmad** [comment]
Closing as related PR has been opened.
