### ISSUE TITLE
The new PSR7 middleware doesn't work in combination with session login and setting up a cookie

### ISSUE THREAD

**Issue by highstrike** [cakephp/cakephp#9305]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Apache 2.4.12, PHP 5.6.11, MySQL 5.6.25

### What you did
Converted my application to the new PSR7 middleware stack by replacing my webroot/index.php, config/bootstrap.php and added src/Application.php (also bin/cake.php for the vendor autoload) Everything was taken from cakephp/app 3.3.0 and then I fine tunned the new bootstrap with my own settings, plugins, whatever.

Also worth mentioning is that I store my sessions in mysql (using the schema/sessions.sql code)

Anyway, everything seemed to work except for the login. I'm using Cookies for a "remember me" feature and when submitting the form it wouldn't log me in at all, it would just redirect me back to the login page like a refresh, no error message, nothing.

What actually happened was that a new CAKEPHP id was generated that was not logged in and the old one was actually updated and logged in, however my browser used the new regenerated id. With a Chrome addon called EditThisCookie, when editing my CAKEPHP session id with the old one that was before i was actually logged in (because it contained the Auth session key that the new session id didn't)

I don't know how to explain this better but it looks like if you're trying to setup a cookie after successfully logging in, cake will regenerate a new session id and use that instead of using the one that it had which was updated with the Auth key holding my user info.

Now code examples:
AppController
```
class AppController extends Controller
{
    // load components
    public function initialize() {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Cookie');
        $this->loadComponent('Auth', [
                'authenticate' => [
                        'Form' => [
                                'fields' => ['username' => 'email', 'password' => 'passwd']
                        ]
                ]
        ]);
...
```
Login action in a controller
```
    public function login() {
        // on post make the login
        if($this->request->is('post')) {
            // identify
            $user = $this->Auth->identify();
            if($user) {
                // login
                $this->Auth->setUser($user);
                $this->Flash->success('You have successfully logged in');

                // THIS IS THE CODE THAT BREAKS THE LOGIN
                $this->Cookie->configKey('RememberMe', ['expires' => '+1 month']);
                $this->Cookie->write('RememberMe', $user);

                // redirect when finished
                return $this->redirect($this->Auth->redirectUrl());

            // user could not be identified
            } else $this->Flash->error('Wrong username or password');
        }
    }
```
And then I have an autologin code in beforeFilter that basically checks the cookie and performs the login automatically which isn't important to show here because I never actually reach that point.

### Expected Behavior
The login to work, cookie to be written, the Auth key to exist in the current session

### Actual Behavior
Cookie is indeed written but the CAKEPHP id is renewed so the Auth session key doesn't exists in the current session and the login fails.

If I comment out the cookie code from `// THIS IS THE CODE THAT BREAKS THE LOGIN` the CAKEPHP session is also renewed but replaced and it contains the Auth session key needed.

The old session id is also deleted from the database where as when setting a cookie it is not deleted but merely left there and the sessions table gets filled up quickly. The table reached 50+ records from me alone trying to debug the damned thing, so there's clearly a problem somewhere.

### Conclusion
I've since switched back to the Dispatch Filters that are now deprecated but at least my application works as it should.

**Comment by ADmad** [comment]
Sounds related to #9263. Can you try using the `master` branch and check if that resolves your issue?

**Comment by highstrike** [comment]
I've tried the master branch 2 hours ago, issue was not fixed unfortunately.

**Comment by antograssiot** [comment]
@ADmad I had a similar issue that was still present after @jadb 's patch 
I've not found the root cause yet but didn't put much effort neither

**Comment by markstory** [comment]
@highstrike Are your cookies encrypted?

**Comment by highstrike** [comment]
@markstory As you can see in the example code I did not set any encryption therefore they should be  AES encrypted by default.

**Comment by markstory** [comment]
Thanks @highstrike I was able to reproduce this issue with out database sessions as well, I hope to have a fix together soon.

**Comment by markstory** [comment]
Looks like when CookieComponent is enabled, the session `Set-Cookie` header is dropped, which is why login is not working.

**Comment by highstrike** [comment]
Awesome :smiley:

**Comment by antograssiot** [comment]
PR is opened now
