### ISSUE TITLE
Unable to emit response; headers already sent

### ISSUE THREAD

**Issue by surjit** [cakephp/cakephp#9306]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I have CAKEPHP 3.3.0

In below method getting header error
I have $this->autoRender = false;
print_r( $data );

In previous version, I had no problem with same code

error.log

```
2016-08-19 11:39:03 Warning: Headers already sent in /home1/path/public_html/domain.com/src/Controller/YoutubeController.php:59
2016-08-19 11:39:03 Error: [RuntimeException] Unable to emit response; headers already sent
Request URL: /youtube/upload
Referer URL: http://domain.com/youtube/upload
Client IP: 117.214.220.86
Stack Trace:
#0 /home1/path/public_html/domain.com/vendor/cakephp/cakephp/src/Http/Server.php(107): Zend\Diactoros\Response\SapiStreamEmitter->emit(Object(Zend\Diactoros\Response))
#1 /home1/path/public_html/domain.com/webroot/index.php(37): Cake\Http\Server->emit(Object(Zend\Diactoros\Response))
#2 {main}
```

```
	public function upload() {
		$upload = new UploadForm();

		if( $this->request->is( 'post' ) ) {
			$data = $this->request->data;

			if( $upload->validate( $data ) ) {
				if( $upload->execute( $data ) ) {
					$this->autoRender = false;

					echo '<pre>';
					print_r( $data );
				} else {
					$this->Flash->error( 'There was a problem submitting your form.' );
				}
			}
		}

		$options = $this->getVideos();
		$this->set( 'options', $options );
		$this->set( 'upload', $upload );
	}
```

**Comment by dereuromark** [comment]
Try to not continue your request once you manually echo.
Instead you should stop execution here then:

    debug(); // This outputs stuff
    die(); // Important then

Or use a proper Debugging Tool / IDE and step through with breakpoints.

**Comment by markstory** [comment]
The error log is not incorrect, your response will not be correct as you've forced headers to be sent. Closing because the error is accurate.

**Comment by ADmad** [comment]
@surjit If you want the old behavior back you can create your own emitter class which extends [SapiStreamEmitter](https://github.com/zendframework/zend-diactoros/blob/master/src/Response/SapiEmitter.php) and override it's [emit](https://github.com/zendframework/zend-diactoros/blob/master/src/Response/SapiEmitter.php#L28) method and pass instance of your class as second param to `$server->emit()` [here](https://github.com/cakephp/app/blob/master/webroot/index.php#L37).

**Comment by surjit** [comment]
what's the right way to do ajax requests with buffering ob flush?

**Comment by markstory** [comment]
@surjit You can [use a callback in the response](http://book.cakephp.org/3.0/en/controllers/request-response.html#streaming-resources)
