### ISSUE TITLE
3.2 cookie from request != cookie from component

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#9309]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.14
* Platform and Target: php7 nginx

### What you did
split in 2 requests
1st one:
```
$this->Cookie->config('encryption', false);
$this->Cookie->write('test', 'foo, bar');
pr($this->request->cookie('test'));
pr($this->Cookie->read('test'));
```
gives `foo, bar` in second pr only (which is ok, just need a doc note)

on second request
```
$this->Cookie->config('encryption', false);
pr($this->request->cookie('test'));
pr($this->Cookie->read('test'));
```
gives `foo, bar` and `foo`

### Expected Behavior
both values to be same on 2nd request

### Actual Behavior
not the same values

**Comment by markstory** [comment]
What is in `$_COOKIE` ?

**Comment by Graziel** [comment]
`[test] => foo, bar`
the problem is probably in 
https://github.com/cakephp/cakephp/blob/master/src/Utility/CookieCryptTrait.php#L172

**Comment by markstory** [comment]
Looks like you've bumped into the backwards compatibility code for old serialized cookie data. Unfortunately we can't remove that without breaking existing applications.

**Comment by Graziel** [comment]
> Unfortunately we can't remove that without breaking existing applications

thats ok, i could leave a note on docs but not sure what to write there :)

**Comment by markstory** [comment]
Closing as documentation has been updated.
