### ISSUE TITLE
Paginator::generateUrl returns invalid URL for all query parameters

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9310]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: Apache 2.4, MySQL, PHP 7

### What you did

```
   echo $this->Paginator->generateUrl(['test'=>'thing']);
```

Generated a custom URL for use with pagination.

### Expected Behavior

Output a URL that contains the extra query parameters.

### Actual Behavior

Output URL contains escaped HTML entities so that `&` is formatted as `&amp;`

I traced this down to the `UrlHelper::build()` method which is a simple function:

```
    public function build($url = null, $full = false)
    {
        return h(Router::url($url, $full));
    }
```

Why is the resulting URL being passed to `h(....)` which will encode all the entities including the query parameter joiner `&`

**Comment by markstory** [comment]
Why are the encoded entities invalid? Helpers are generally used in an HTML context where `&` needs to be escaped.

**Comment by thinkingmedia** [comment]
```
  $url = $this->Paginator->generateUrl(['test'=>'thing']);
  echo $this->Html->link('title', $url);
```

@markstory The above will fail to render a valid URL.

Am I missing something? Seems like this is how it would normally be used.

**Comment by markstory** [comment]
I typically generate links with the various other PaginatorHelper methods. Why are you creating the URL and link separately?

**Comment by thinkingmedia** [comment]
@markstory I'm just adding links to change the limit.

```
echo $this->Html->link('Show 100', $this->Paginator->generateUrl(['limit'=>100]));
```

Is this the wrong approach?

**Comment by markstory** [comment]
I can see how that would be expected to work. We could add a more general purpose `Paginator->link()` method that lets you make customized link elements that include pagination context. We used to have a similar method in 2.x, and I've forgotten why it was removed.

**Comment by thinkingmedia** [comment]
That sounds good to me.

What I noticed is that the paginator helper is using `generateUrl` to create a string of the URL which has HTML entities encoded. This is then passed to the template format as a variable where it gets outputted into the rendered HTML still encoded.

Here's an example from a table heading with Cake 3.2.12

```
<a href="/admin/import-records?sort=ImportRecords.board_id&amp;direction=asc">Board</a>
```

I still think this is wrong. It's only works because modern browsers know enough to decode the `&amp;` before resolving the link.

**Comment by thinkingmedia** [comment]
If the google web crawler requested the above look **as is** the web server would give an unexpected response.

**Comment by dereuromark** [comment]
The above URL is absolutely correct and valid. The characters must be properly escaped when outputted in HTML context. Crawlers know how to treat them.

**Comment by thinkingmedia** [comment]
@markstory @dereuromark okay guys. My apologizes for wasting your time. I really thought this was wrong, but after googling it turns out you're completely correct.

https://perishablepress.com/how-to-write-valid-url-query-string-parameters/

Not encoding the `&` would produce invalid HTML.

Still much to learn. Thanks.

**Comment by ADmad** [comment]
@thinkingmedia No worries. You aren't the first one to bring this up and probably won't be the last :)

**Comment by markstory** [comment]
URL encoding aside, being able to generate links with the current pagination context is still something that isn't 'easy' to do with the current methods. Is that gap something someone wants to address?

**Comment by thinkingmedia** [comment]
@markstory I'll open a PR for this.

Didn't we use to have a method like this in the helper for Cake 2.x? Maybe I can use it as a guide.

I would like the link method to return an array and not a string. So that it can later be modified if required.

**Comment by markstory** [comment]
> Didn't we use to have a method like this in the helper for Cake 2.x? Maybe I can use it as a guide.

We did [Paginator::link](http://api.cakephp.org/2.8/class-PaginatorHelper.html#_link)

**Comment by thinkingmedia** [comment]
@markstory I'm looking at the generateUrl code now, and trying to understand how it would be different from the old link method. I can't see what the problem is?

When you say it's not easy to generate links. How so?

**Comment by markstory** [comment]
> When you say it's not easy to generate links. How so?

I mean that what you're trying to do -- create links that include the current pagination context -- should be easy and right now it is not. Based on what you were trying to do earlier, would a method like:

```php
echo $this->Paginator->link('Show 100', ['limit'=>100]);
```

Do what you needed?

**Comment by thinkingmedia** [comment]
@markstory oh okay, I understand  now. thanks.

**Comment by berarma** [comment]
So this should be written as:
```php
echo $this->Html->link('Show 100',
  htmlspecialchars_decode($this->Paginator->generateUrl(['limit' => 100]))
);
```

I think it's unfortunate that the URL helper (and by extension also the PaginatorHelper) thinks it knows how we're going to use URLs. I guess it would be a lot easier to always get raw URLs and let the dev or the other helpers (like the HtmlHelper already does when creating links) handle the encoding. Aren't we already explicitly using ```h()``` in our views?

Now we need to create more methods that duplicate functionality but without the encoding. Couldn't we revert the situation so that we had just one set of methods that we could wrap in ```h()``` when needed.

**Comment by dereuromark** [comment]
No, for security reasons there should be a flag or a custom method that would explicitly (and only then) return the raw URL. Otherwise it must behave like it always did so far.

Why can't you use `$this->Paginator->link()` as mentioned before?

**Comment by berarma** [comment]
Because it doesn't exists in 3.x, does it?

I don't probably understand the security implications so I'll just get used to how it works.

**Comment by dereuromark** [comment]
I just took a look into the source code (which should always be the first step before opening a ticket), as this tells a lot about what the class internally and externally provides and does.
And I see a `generateUrl()` method ( https://github.com/cakephp/cakephp/blob/master/src/View/Helper/PaginatorHelper.php#L477 ).

The doc block of it states:
> Merges passed URL options with current pagination state to generate a pagination URL.

**Comment by thinkingmedia** [comment]
@dereuromark I have a PR coming that does exactly this. Sorry, I've been so busy that I hadn't had time to finish it. This PR will also close another issue on this topic.

Why did you say a raw URL is a security issue? What are the risks?

**Comment by dereuromark** [comment]
Because people always forget to escape it then, leaving XSS possibilities as well as invalid DOM.

**Comment by inoas** [comment]
- Maybe the method should be named rawLink() then.
- Or generateUrl should have escape => false optin option.

**Comment by dereuromark** [comment]
Let's wait for the PR and then look into it. I don't think a rawLink() makes sense.

**Comment by berarma** [comment]
Now that ```UrlHelper::build()``` has a ```escape``` option wouldn't it make sense that ```PaginatorHelper::generateUrl()``` had the same too? They're both method helpers that return URLs that could be used in other helpers. Just asking?

**Comment by dereuromark** [comment]
Or it could internally use that new method then?

**Comment by markstory** [comment]
Closing as #9569 solves this with a very small API addition.
