### ISSUE TITLE
Rewrite route with name

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9312]
In fact, [this feature](https://github.com/cakephp/cakephp/pull/9237) has broken my app, because I rewrote routes written by a plugin, for example (but not only).

Example. A plugin writes this route:

    $routes->connect(
        '/post/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );

while my app writes this route:

    $routes->connect(
        '/articles/article/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );

How to do, now? Add a method (`$route->nameExists('mycustomname')`) to check if there is already a route with the same name?
Add an option (`$force`) that allows you to rewrite a route with the same name?

Other?

**Comment by markstory** [comment]
I suspect your code wasn't working before either as only the first named route would have been accessible in as a named route. The simplest solution would be to use unique names :smile:

**Comment by mirko-pagliai** [comment]
@markstory Maybe I didn't understand what you mean. 
Before my app works correctly: simply it used the first route found (this also applies to the routes with no name: the first coinciding is used).

**Comment by ADmad** [comment]
I also don't think anything needs to change in core. You should update your app to use unique names. The earlier behavior of the second route being silently ignored didn't help anybody and masked actual oversights.

**Comment by saeideng** [comment]
Can i know why you rewrite your route names?

**Comment by mirko-pagliai** [comment]
@saeideng see example in the first post.

My real case: I have a plugin that is a CMS.
The plugin is autonomous and makes it functional even an empty application. If I want a particular functioning, I work at the app level.

So, for example, let's assume that the plugin allows full management of posts: add, edit, delete, view, etc. and it has this route to view posts:

    $routes->connect(
        '/post/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );

But in one of my application I want to use a different url. Then I rewrite the route.

    $routes->connect(
        '/articles/article/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );

This works, because the routes of the application are read first (the plugins routes are loaded after the application).

Another example. In another application I want the posts to work differently than would the plugin (the action code is different). Then I act the same way and I override the route, using an action included in the application.

**Comment by mirko-pagliai** [comment]
Other example very very simple: I've a route called "homepage", setted in `routes.php`.

In `AppController::beforeFilter()` I want to rewrite the route only for the `PincoPallo` user, if he's logged.

It sounds so strange?

**Comment by mirko-pagliai** [comment]
But the point is that I don't understand why we need to add an exception if the two routes have the same name. The code works the same, just it uses the first route found.

So at this point, why not add an exception even if two routes have the same parameters?

    $routes->connect(
        '/post/*',
        ['controller' => 'Posts', 'action' => 'view']
    );
    $routes->connect(
        '/posts/post/*',
        ['controller' => 'Posts', 'action' => 'view']
    );

**Comment by saeideng** [comment]
I think we can not override routes in controllers or any action (even beforeFilter)

**Comment by saeideng** [comment]
Can you change your plugin?
For logged user you may chane your strategy
Use of routes for dynamic case is not good idea

**Comment by mirko-pagliai** [comment]
Maybe a new "nameExists()" method? Do you think is ok?

**Comment by saeideng** [comment]
For check
You can use routes():

**Comment by markstory** [comment]
@mirko-pagliai Interesting, I hadn't considered people would use explicit names as a way to overwrite earlier routes. I and @saeideng interpreted that as human error that would need to be corrected.

**Comment by mirko-pagliai** [comment]
My plugin has the route `/post/:slug`. Comes a new customer and want to migrate his old site to my CakePHP plugin.
But his old site uses url `/articoli/:slug` (`articoli` is `posts` in italian, plural).

What do I do?
Of course the solutions are many. It might make sense to create a permanent redirect. Or internationalize the routes of my plugins.

But the simplest and most sensible thing is to rewrite the route with the same name in the app. The routes of the plugin are read later, then it works, the first route that is found is used.

This is not a invented example ... is one of my app that broke :-D

Now what comes to mind is to check if there is already a route with the same name inside the plugin, when I'm setting up the second time.

App:

    $routes->connect(
        '/articoli/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );

Plugin:

    if (!$routes->nameExists('post')) {
        $routes->connect(
            '/post/:slug',
            ['controller' => 'Posts', 'action' => 'view'],
            ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
        );
    }

**Comment by mirko-pagliai** [comment]
However, what I want to point out is that we have added an exception (during a minimum version upgrade) to a behavior that for someone (I do not know if I'm the only one) was very normal.

Indeed, apart from the routes that have a name, the routes always work well: the first is always used.

Example:

    $routes->connect(
        '/post/search',
        ['controller' => 'Posts', 'action' => 'search']
    );
    $routes->connect(
        '/post/:slug',
        ['controller' => 'Posts', 'action' => 'view'],
        ['slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
    );
    $routes->connect(
        '/post/**',
        ['controller' => 'Posts', 'action' => 'other']
    );

This code will work well anyway, even if more routes may interpret the same request, simply because they are in the correct order.

I think it would be better to do the opposite: ie asking **optionally** CakePHP to check whether some routes are in conflict (for example, with an option such as `unique`).

**Comment by mirko-pagliai** [comment]
For now I have solved with this:

`app/plugins/MyPlugin/config/routes.php`

    use Cake\Routing\Router;

    // ... code ...

    $GLOBALS['existingRoutesNames'] = array_filter(
        array_map(function ($route) {
            return empty($route->options['_name']) ? false : $route->options['_name'];
        }, Router::routes())
    );

    function routeNameExists($name)
    {
        return in_array($name, $GLOBALS['existingRoutesNames']);
    }

    Router::scope('/', ['plugin' => 'MyPlugin'], function ($routes) {

        // ... code ...

        if (!routeNameExists('post')) {
            $routes->connect(
                '/post/:slug',
                ['controller' => 'Posts', 'action' => 'view'],
                ['_name' => 'post', 'slug' => '[a-z0-9\-]+', 'pass' => ['slug']]
            );
        }

        // ... code ...

    }

**Comment by saeideng** [comment]
you can use http://api.cakephp.org/3.3/class-Cake.Routing.Router.html#_routes
for check exist routes

> Indeed, apart from the routes that have a name, the routes always work well: the first is always used.
>

cake use first matched normal routes
but for named routes , cake used latest config (in past/before these change)
so you can not override that named routes in main app.php anyway

**Comment by mirko-pagliai** [comment]
@saeideng 
If you look hard enough, that's what I did :-) (see prev post)
But it's a really bad code and it does not consider successive routes added.
I remain convinced that we should add a `Router::nameExists()` method.
I can do, if you agree.

> but for named routes , cake used latest config (in past/before these change)

Sorry, you're right. In fact my app loads before the plugins routes.

Now I do the opposite: the routes of the plugins are loaded at the end, checking whether there is already a route with the same name.

**Comment by mirko-pagliai** [comment]
I would do two things:
1) `Router::nameExists()` method;
2) `force` or `ignoreDuplicates` option, which allows you to overwrite routes with the same name (that does not cause the exception).

**Comment by mirko-pagliai** [comment]
Use the method is absolutely bad: you have to cycle the results every time.

This gets the list of routes name that already exist:

        array_filter(
                array_map(function ($route) {
                    return empty($route->options['_name']) ? false : $route->options['_name'];
                }, Router::routes()
        )

It should be re-run every time. Very, very bad for me.

Instead, it would be enough to add the `Router::nameExists()` method:

    public static function nameExists($name)
    {
        return in_array($name, (array_keys(static::$_collection->named())));
    }

**Comment by markstory** [comment]
I'm not sure adding more options is a good idea. It adds more complexity to the framework. I would rather revert off the duplicate route name exceptions and restore the 'last named route wins' behavior we had before. Instead of an exception we could emit debug level log messages when duplicate named routes are connected.

**Comment by mirko-pagliai** [comment]
For me at this point we might as well leave the exception and offer a method (`nameExists()`) to check if a name already exists. Who's going to rewrite a route with a name (and he knows that he's doing it on purpose) will use the method before to re-declare.

**Comment by ADmad** [comment]
> Instead of an exception we could emit debug level log messages when duplicate named routes are connected.

Wouldn't that unnecessarily keep filling the logs for someone who intentionally has duplicate names as described in this ticket?

**Comment by mirko-pagliai** [comment]
I agree with @ADmad

**Comment by saeideng** [comment]
Match() methods in across app will check on runtime
That means if you forget some names and set again ,it your routs  probably make confilics in your app silently,
Means you may run total url and actions , until that  you ensure total of routes work well :)
this issue happend for me after 2 3 days after change routes(on a site on remote server) becouse cake no notif to me :)
And i know when checked specific url , if  not check that  maybe i never find it :d

**Comment by markstory** [comment]
@ADmad It would in development. I hope most folks disable debug logging in production, but I'm sure some done.

@mirko-pagliai I'm not a fan of the additional methods because it feels like a workaround for what should be a rare situation. I would prefer to not have the exception personally.

**Comment by mirko-pagliai** [comment]
then ok for me, although I remain convinced that the exception could stay. Do I do a PR?

**Comment by saeideng** [comment]
we can not override named routes anyway becouse
for example
we set some of routes
```
$routes->connect(
    '/post/:id',
    ['controller' => 'Articles', 'action' => 'view'],
    ['_name' => 'post', .....]
);

$routes->connect(
    '/post/:slug',
    ['controller' => 'Articles', 'action' => 'show'],
    ['_name' => 'post', .....]
);

$routes->connect(
    '/posts/:slug',
    ['controller' => 'Posts', 'action' => 'view'],
    ['_name' => 'post', .....]
);

$routes->connect(
    '/post/:id',
    ['controller' => 'Posts', 'action' => 'show'],
    ['_name' => 'post', .....]
);
```
we have 4 routes with some name
when we use `Build(['_name'=>'post'] ` cake will use latest routes template and Posts::show() action
but when someone call `example.com/post/3` URL ,cake use Articles::view() action for handle it

i prefer to have a method for just  return named routes
  ```
  public static function getNamedRoutes()
    {
        if (!static::$initialized) {
            static::_loadRoutes();
        }

        return static::$_collection->named();
    }
    public static function getRoutes()
    {
       return $this->routes()
    }
```

**Comment by mirko-pagliai** [comment]
Ok for me. A method for return named routes or to check if a name already exists.

**Comment by markstory** [comment]
@saeideng How does having a method to get all the connected named routes help with duplicate routes? Are you using it like the `nameExists` method @mirko-pagliai suggested?

**Comment by saeideng** [comment]
no
`named()` will return array with key/value ,that keys are name of `_name`
`routes()` not have index key

```
//named
[
  'post'=>'cart_add' => object(Cake\Routing\Route\DashedRoute) {
      //
   }
]
//routes
[
 0=> object(Cake\Routing\Route\DashedRoute) {
]

```
after that developers can check by
`in_array($name, (array_keys(getNamedRoutes())));` manually 
or use of that in other place if was necessary

**Comment by markstory** [comment]
Wouldn't having `nameExists()` on `RouteBuilder` make checking for existing named routes easier than `getNamedRoutes()` or `getRoutes()` would?

**Comment by saeideng** [comment]
RouteBuilder not use directly in core
that use within router class

**Comment by mirko-pagliai** [comment]
Look my comment: https://github.com/cakephp/cakephp/issues/9312#issuecomment-241252097
This work, tested.

**Comment by jadb** [comment]
Wouldn't it just be easier to load the plugin's `routes.php` after the application's routes? By either including the plugin later or by explicitly including it's routes from the `app/config/routes.php` and not setting `routes => true` when including the plugin?

I just find that wrapping every route with an `if (!Router::nameExists())` becomes too verbose at some point. Is it just me?

**Comment by mirko-pagliai** [comment]
> Wouldn't it just be easier to load the plugin's routes.php after the application's routes?

Someone might want to overwrite the routes of the plugin with the application.
Someone might want to overwrite the routes of the application with the plugin.

**Comment by jadb** [comment]
> > Wouldn't it just be easier to load the plugin's routes.php after the application's routes?

>Someone might want to overwrite the routes of the plugin with the application.
Someone might want to overwrite the routes of the application with the plugin.

I get that. That's why I said that in such a case (where both are needed), the `app/config/routes.php` gets littered with `if`s. 

**Concern:** wouldn't overwriting a plugin's named route break all of that named route's links defined in the plugin? In the initial case mentioned in this issue, all of the plugin's links using the `post` named route would now redirect to the application's articles and not to what the plugin is expecting. Which leads me to say:

**Side note:** I believe it's *safer* to namespace plugin routes; easier to find those routes in the codebase when plugin is deprecated or changed for something else.

All that been said, am not against adding a new method if others see a benefit to it.

/cc @ADmad @markstory

**Comment by ADmad** [comment]
I too don't buy this routes overriding argument. A plugin should surely not be overriding an app's routes and if you don't like the routes a plugin provides don't load it's routes file and add required routes to your app's routes.php instead.

**Comment by thinkingmedia** [comment]
I thought routes were serialized to the cache for faster loading later? If we add methods to enable business logic that makes routing uncachable (is that a word?) because the routes could keep changing.

**Comment by mirko-pagliai** [comment]
@jadb In fact I think we should not add an exception! It was a permissible behavior and some users used it ... (like me!)

**Comment by jadb** [comment]
@mirko-pagliai no exceptions would be raised if plugin used namespaced routes as suggested 😉 

From the book: 

```php
// Use namePrefix with plugin()
Router::plugin('Contacts', ['_namePrefix' => 'contacts:'], function ($routes) {
    // Connect routes.
});
```

http://book.cakephp.org/3.0/en/development/routing.html#using-named-routes

**Comment by markstory** [comment]
@thinkingmedia Routes are not serialized into a cache file. We would need to eliminate custom route classes to make that more doable.

**Comment by mirko-pagliai** [comment]
@jadb I know, but I don't want to use name prefix :-)

**Comment by jadb** [comment]
@mirko-pagliai great. So as long as there is a known solution to the problem, I think you can now close this issue and associated pull request :)

**Comment by mirko-pagliai** [comment]
@jadb it's no ok for me. Because (by intuition) the same problem would occur if I tried to overwrite named routes of a plugin that uses a prefix.

I see it: before I could do something (a behavior), which I thought was normal and that (mostly) it worked.
If I was to overwrite a named route, I could do. It worked and the app worked.
Now this behavior throws an exception and the application breaks.

Someone might have the same problem.
Because the exception has been added for those who were to **accidentally** overwrite routes.
Not having regard that someone could overwrite **voluntarily**.

I realized that probably my code will have many `if`s.
But what's the problem? It will do so only those who voluntarily want to overwrite the routes.

**Comment by jadb** [comment]
@mirko-pagliai you seem to forget that if if a plugin defines a named route that you overwrite (i.e. `post::index`), then all the links/redirects in said plugin will break as now they will point to your new *destination* which isn't the one expected by the plugin (for example redirecting to posts controller's index action after adding a new post using that named route).

**Comment by mirko-pagliai** [comment]
@jadb see https://github.com/cakephp/cakephp/issues/9312#issuecomment-241205562

**Comment by markstory** [comment]
@mirko-pagliai I think the `nameExists()` method is a reasonable compromise and allows both the 'stricter' route mode and the 'replace' mode that used to exist.

**Comment by mirko-pagliai** [comment]
Me too.

**Comment by jadb** [comment]
Closing as PR  #9361 is opened.
