### ISSUE TITLE
Add support for MySQL query index hints

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#9313]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.x

is there a function in database query like epilog or modifier to set the index to use. in mysql the use index should be write after the table name.

**Comment by markstory** [comment]
There isn't yet.

**Comment by doshu** [comment]
is this feature in planning? or will be ever created?

Il 20 Ago 2016 15:41, "Mark Story" <notifications@github.com> ha scritto:

**Comment by markstory** [comment]
@doshu This is the first issue that has been opened requesting support for MySQL's [index hints](http://dev.mysql.com/doc/refman/5.7/en/index-hints.html). #9195 was somewhat similar in that it was asking for different MySQL specific behavior.

**Comment by thinkingmedia** [comment]
@markstory I can resolve #9195 with a simple MysqlCompiler, but this issue would require a way to define which indexes to use. How would that be done with the Query build? Is it a type of expression or a new method on the Query object.

**Comment by lorenzo** [comment]
Can you try this?

```php
$query->from(['articles' => 'articles USE INDEX foo']);
```

**Comment by nachitox** [comment]
This hack works too:

```
->join([
	'%ALIAS FORCE INDEX (%INDEX)' => [
	       'table'		=> %TABLE,
	       'type'			=> %JOIN_TYPE,
	       'conditions'	=> %CONDITIONS
	]
])
```

**Comment by nebojsac** [comment]
I just had to add support for this to our CakePHP 2.x installation.
Are changes like this still welcome for the 2.x branch? If so, I'd clean it up and submit a PR.

**Comment by saeideng** [comment]
> Are changes like this still welcome for the 2.x branch? If so, I'd clean it up and submit a PR.

We have supported 2.x since October 2011 and have [clearly communicated](https://bakery.cakephp.org/2017/07/22/cakephp_2100_released.html) that it will receive only bug and security fixes from June 2017 going forward. We both cannot accept any pull requests or issues which:

- backport 3.x features to 2.x
- add/request new functionality for 2.x

Doing so will unfortunately increase our maintenance overhead. We appreciate your participation in the CakePHP project, but as a group of volunteers contributing their spare time for free there's only so much we can do, and at the moment we are focused on maintaining 3.x and moving towards 4.x.

**Comment by nebojsac** [comment]
Of course, makes total sense, thanks for the reply!
I wasn't sure because this wouldn't include BC breaks, but I can see how it can increase maintenance overhead.

**Comment by bancer** [comment]
@lorenzo I ended up with overriding Query class.
``` php
<?php
namespace App\ORM;

use Cake\ORM\Query as CakeQuery;

/**
 * Query extends Cake\ORM\Query.
 */
class Query extends CakeQuery {

	/**
	 * Adds index hints to the query.
	 *
	 * @param string $indexHint Index hint ('IGNORE', 'FORCE' or 'USE').
	 * @param string[] $indexes Index names.
	 * @return void
	 * @throws \InvalidArgumentException
	 */
	protected function _addIndexHint(string $indexHint, array $indexes) : void {
		$validHints = ['IGNORE', 'FORCE', 'USE'];
		if (!in_array($indexHint, $validHints)) {
			$message = "'$indexHint' is wrong index hint. Supported values are: '" . implode(", '", $validHints) . "'.";
			throw new \InvalidArgumentException($message);
		}
		$Connection = $this->getConnection();
		foreach ($indexes as &$index) {
			$index = $Connection->quoteIdentifier($index);
		}
		$values = implode(', ', $indexes);
		/** @var \Cake\ORM\Table $Table */
		$Table = $this->getRepository();
		$alias = $Connection->quoteIdentifier($Table->getAlias());
		$table = $Connection->quoteIdentifier($Table->getTable());
		$this->from("$table $alias $indexHint INDEX($values)");
	}

	/**
	 * Adds USE INDEX hint to the query.
	 *
	 * @param string[] $indexes Index names.
	 * @return \App\ORM\Query
	 */
	public function useIndexes(array $indexes) {
		$this->_addIndexHint('USE', $indexes);
		return $this;
	}

	/**
	 * Adds FORCE INDEX hint to the query.
	 *
	 * @param string[] $indexes Index names.
	 * @return \App\ORM\Query
	 */
	public function forceIndexes(array $indexes) {
		$this->_addIndexHint('FORCE', $indexes);
		return $this;
	}

	/**
	 * Adds IGNORE INDEX hint to the query.
	 *
	 * @param string[] $indexes Index names.
	 * @return \App\ORM\Query
	 */
	public function ignoreIndexes(array $indexes) {
		$this->_addIndexHint('IGNORE', $indexes);
		return $this;
	}

}
```
