### ISSUE TITLE
Cakephp 3.3, ResponseTransformer does not support charset

### ISSUE THREAD

**Issue by pmacko** [cakephp/cakephp#9315]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.1

### Expected Behavior
$this->RequestHandler->respondAs('text/html', ['charset'=>'utf-8']);

Output headers: Content-type: text/html; charset=utf-8

### Actual Behavior

Output headers: Content-type: text/html

<code php><pre>
// ResponseTransforer.php, toPsr method
if (!isset($headers['Content-Type'])) {
    $headers['Content-Type'] = $response->type();
}
</pre></code>

**Comment by pmacko** [comment]
Problem is in Network/Response object, method _setContentType is not calling becase sendHeaders is not used (psr7 & middleware)

**Comment by markstory** [comment]
Pull request open now.
