### ISSUE TITLE
3.3.x+ all Helper Singletons should be resettable

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9317]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.1

### What you did
Ref: https://github.com/cakephp/cakephp/pull/9127#issuecomment-241210746

### Expected Behavior
There should be a way to manage state of the helper singletons.

Once we get to setters over error prone hash-configuration, for Helper calls in Templates we will want to have methods that change the state and then others that return to the output buffer, say like `$this->Form->setValuesSources('query')->create()`.

### Actual Behavior

It is unclear if helpers should keep their state and/if/when they should drop it.

If we want to reset Singletons we could add a `::reset()` method. When the Singleton is being constructed it would - at the end of its constructor - write its state, as a clone, to `$_initialClone` - reset would then do something like `$this =  $this->_constructClone`. All Helpers could/should do that. It would be as easy as:

1. use singleton like `$this->Form->create()` ...
2. reset single singleton like `$this->Form->reset()` ...
3. use singleton in a original state again...

Does that make sense to you?

**Comment by markstory** [comment]
I'm confused by you use of 'singleton'. Helpers aren't really [singletons](https://en.wikipedia.org/wiki/Singleton_pattern) are you looking for a way to reset the potentially 'shared' state in FormHelper which crosses form boundaries?

**Comment by inoas** [comment]
Reading exactly that page to me what is not about them thats not Singleton?

Anyway, the shared state comes from creating multiple Forms on a single page. I will reset them via end() in the other PR.

If no one else can see a point in resetting Helpers to their original state then I will close this.

**Comment by ADmad** [comment]
Form->end() already resets state so I don't see the need for another method to do the same.

**Comment by inoas** [comment]
Okay. I think it should be in the base Helper class. Despite that I'll close this now and will fix the PR to reset valueSources to 'context' via FormHelper's end().
