### ISSUE TITLE
Error Composer require

### ISSUE THREAD

**Issue by 812311** [cakephp/cakephp#9320]
[InvalidArgumentException]                                  
  Could not find package cakephp/cake with stability stable. 

does anyone knows whats is going on?
i already tried to run on vagrant and my local apache and it didn't work.

**Comment by josegonzalez** [comment]
@812311 In order for us to diagnose your problem, you'll need to provide a bit more detail. Specifically, can you add the following information:

- Operating System
- `php -v` output
- `composer -V` output
- The command you ran that resulted in the error
- If running in an existing repository, your `composer.json`

Thanks :)

**Comment by 812311** [comment]
Mac OS X El Capitan


php -v
PHP Warning:  PHP Startup: intl: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0
PHP 5.5.36 (cli) (built: May 29 2016 01:07:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

composer -V
PHP Warning:  PHP Startup: intl: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.2.0 2016-07-19 01:28:52


Commands resulting the error:
composer create-project cakephp/cake
or 
composer require cakephp/cake@3.0.18

**Comment by josegonzalez** [comment]
You should fix your loaded intl extension. It seems like you are trying to load php5.6-intl under php5.5, which may be the source of your errors.

**Comment by 812311** [comment]
I ran this steps and installed the right version.. but the error persists.
https://asdqwe.net/blog/enabling-installing-intl-package-php-from-terminal/

here is how it is now.
![captura de tela 2016-08-21 as 08 30 59](https://cloud.githubusercontent.com/assets/21060240/17836910/a50b3772-6779-11e6-9605-0abbac2d930e.png)

**Comment by ADmad** [comment]
You need to figure out how to properly install intl extension for your environment.

Closing as your issue isn't directly related to CakePHP code and there isn't much more we can do to help you. You can make a post on stackoverflow to get help.
