### ISSUE TITLE
Find list is not working as the documentation suggest

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#9321]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3.0.
* Platform and Target: ubuntu 15.04, apache 2.4, php-7.0.8.

### What I did
Follow this example: http://book.cakephp.org/3.0/en/orm/query-builder.html#getting-a-list-of-values-from-a-column

```php
$sliders = TableRegistry::get('revslider_sliders')->find('list')->select(['alias', 'title']);
```

### Expected Behavior
Having a result set ready to use un a combo box, where the key of each result (to be the option value) is "alias" and the value (to be the option text) is "title". 

### Actual Behavior
Instead I have "id" field as key (which is the primary key of the table) and "title" as value field (which is the display field for that table).

I was researching a bit around this issue, and I don't see how this could work. The List finder searches in options for two keys: "keyField" and "valueField", and then it sets a "result formater" with them, at this point select() method was not called, and I can't find where select() method (or another method called after) is aware of this.

If I pass those keys as options this way:
```php
$sliders = TableRegistry::get('revslider_sliders')->find('list', ['keyField' => 'alias', 'valueField' => 'title']);
```
The it works as expected. So, or documentation is wrong or there is a bug.

**Comment by ADmad** [comment]
The documentation is incorrect and needs to be fixed.

**Comment by lorenzo** [comment]
Closing as there is a PR for the docs
