### ISSUE TITLE
Calling hasMany->unlink($entity, []) produces SQL syntax error query

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#9324]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2.13
* Platform and Target: Linux, MySql 5.7.14

### What you did
Called unlink($entity, []) with an empty array as a second parameter.

### Expected Behavior
Unlink should not do anything.

### Actual Behavior
The following SQL query was made and executed: `UPDATE articles SET author_id = NULL WHERE`

**Comment by markstory** [comment]
Closing as there is a pull request open with tests.
