### ISSUE TITLE
Table::get() should fast fail if primary key is null.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9327]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: Apache 2.4, MySQL, PHP 7

### What you did

```
   public function show($id = null) {
       $entity = $this->Model->get($id);
       $this->set(compact('entity'));
   }
```

When using the default dashed routes any actions can receive optional parameters. So in the above case the `$id` can be `null` but it will `404` as expected.

### Expected Behavior

`Table::get()` should not perform a SQL query on a `null` primary key.

### Actual Behavior

`Table::get()` doesn't check the value of `$primaryKey` except for arrays. Can't this method block the function by failing if primary key is `null`?

**Comment by lorenzo** [comment]
hmm, that would make sense for single column primary keys, but would not for composite primary keys.

As an aside. Why is your function `show($id = null)`? You clearly  don't want a null to get to that point.

**Comment by thinkingmedia** [comment]
@lorenzo I want to ensure that the server responds with a 404 error when the $id is not passed. If the default is not set it will trigger a 500 response. I know this can be fixed with routing, but it's easier to just use the default dashed routes.

**Comment by saeideng** [comment]
`$this->Model->get(null)//return  404`

**Comment by lorenzo** [comment]
@thinkingmedia I was thinking more of using the router to not dispatch to that function. That way you even save all the controller bootstrapping process.

**Comment by thinkingmedia** [comment]
@lorenzo it would awesome if routing or dispatch could inspect the function for number of parameters, and if the request does not match, then it does not call it.

And with PHP 7 primitive type hinting you could even enforce parameter types (i.e. numbers only).

Anything that reduces setup time and work for the developer is a good idea in my book.

**Comment by thinkingmedia** [comment]
Another idea would be to allow us to add a hook into the dispatcher just before the call to the action is made. So we can code our own special rules.

Anyway, I've gone off topic but all the above is kind of related. If I could do that I wouldn't care much about get null.

**Comment by thinkingmedia** [comment]
@saeideng yes, I know `$this->Model->get(null)` returns 404. My point is that a SQL query is still performed.

**Comment by dereuromark** [comment]
That is not a big deal IMO. If you don't want that, wrap it before hand to check for this use case.

**Comment by thinkingmedia** [comment]
@dereuromark sure that's fine. @lorenzo got me thinking and I added this to be base controller.

```
    /**
     * @param Event $event
     * @return \Cake\Network\Response|null
     */
    public function beforeFilter(Event $event)
    {
        $action = $this->request->param('action');
        $reflect = new \ReflectionClass($this);
        if ($reflect->hasMethod($action)) {
            $method = $reflect->getMethod($action);
            if ($method->isPublic()) {
                $args = count($method->getParameters());
                $pass = (array)$this->request->param('pass');
                if ($args !== count($pass)) {
                    throw new NotFoundException("Incorrect number of arguments");
                }
            }
        }

        return parent::beforeFilter($event);
    }
```

I think that does the trick. I could go further as to check the type hinting as well, or use a parameter naming convention. It's not as elegant as routing but it makes for faster coding of small controller actions.
