### ISSUE TITLE
3.x Time::setToStringFormat does nothing?

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9329]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3.1

### What you did
Within bootstrap.php:
```php
use Cake\I18n\I18n;
use Cake\I18n\Time;
I18n::defaultLocale('en-US');
Time::setDefaultLocale('en-US');
Time::setJsonEncodeFormat('yyyy-MM-dd HH:mm:ss');


Time::setToStringFormat(\IntlDateFormatter::SHORT);

// The same method exists on Date, FrozenDate and FrozenTime
Time::setToStringFormat(\IntlDateFormatter::SHORT);


Time::setToStringFormat([
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::SHORT
]);

Time::setToStringFormat('yyyy-MM-dd HH:mm:ss');


<?= h($user->created) ?>
```

### Expected Behavior
Datetimes to render "yyyy-MM-dd HH:mm:ss"

### Actual Behavior
Still shows dates like such: `8/22/16, 9:41 PM`

**Comment by markstory** [comment]
Do you have a `Time` instance or do you have a `FrozenTime` instance? I was not able to reproduce the issue as both `IntlDateFormatter` constants, and string formats worked as expected for me.

**Comment by inoas** [comment]
That was it. While I read the docs I overread the comment. Will PR the docs.
