### ISSUE TITLE
3.x FormHelper::input value option set to null is being ignored

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9330]
This is a:
* [x] bug

* CakePHP Version: 3.3.1

### What you did

```php
 <?= $this->Form->create($user) ?>
 <?= $this->Form->input('password', ['value' => null]) ?>
```

### Expected Behavior
Expected the password's value attribute and thus field to be empty.

### Actual Behavior
Hashed password value was output into the value attribute and thus the password was full with stars.

### Solution

```php
<?= $this->Form->input('password', ['value' => '']) ?>
```

### Question

Is this expected and correct behavior? If so, is it documented (couldn't find it)
My bet is that it checks via `empty()` but must check via `isset()`?

If you agree I can try to prep a small PR.

**Comment by markstory** [comment]
Yes, this is how it should work. Both `empty()` and `isset()` will return false on an array key of `null`.

**Comment by inoas** [comment]
I'll check the docs and possibly update.

**Comment by inoas** [comment]
Added instructions to the docs: https://github.com/cakephp/cakephp/issues/9330 left out the php-internal explanation above (thanks!). If you want me to add it (I am torn on knowledge vs too much information), let me know
