### ISSUE TITLE
AssetCompress needs routes to work

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#9331]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2

### What you did
I've just installed the app skeleton and added markstory/asset_compress. I've configured basic assets. Then I try to access them in the browser through /cache_js/libs.js and /cache_css/all.css.

### Expected Behavior
I expect to get an error from the AssetCompress plugin telling me I don't have these files, that would mean it's working. It does but only when I'm using the fallback routes.

### Actual Behavior
Commenting out the `$routes->fallbacks('DashedRoute');` changes the error to Missing Route. Thus AssetCompress doesn't get to see the request.

It's working with the fallback routes because the request matches the route "/:controller/:action/*". The routing middleware let's the request continue to AssetCompress only when it finds a matching route. So it seems I need to setup routes for the assets. I don't remember reading about this in the docs so I don't know if this is wanted behavior or an error.

**Comment by berarma** [comment]
Sorry, I thought this to be a regression since it worked for me with CakePHP 3.2 without the fallbacks. Now I see the behavior is the same on a clean install.

I didn't catch this behavior before because I always had some route that matched the assets URLs, but now I didn't and also the cache_js and cache_css where clean so the error triggered. I guess this is what happened.

It just felt odd that the AssetCompress plugin relied on the default controller actions route or some random 2-level path route to work.

**Comment by ADmad** [comment]
Your issue isn't directly related to AssetCompress. For any URL for file which doesn't exist under webroot the request will be forwarded to cakephp and that URL will be handled just like any other based on the routes you have configured.
