### ISSUE TITLE
Redirect routes not compatible with old dispatcher

### ISSUE THREAD

**Issue by jeremyharris** [cakephp/cakephp#9336]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2
* Platform and Target: Apache/2.4.18 

### What you did

- create new app `composer create-project cakephp/app test_routing`
- replace `webroot/index.php` with the old dispatcher
- add old dispatch factory filters to bootstrap
- add a redirect route to the main scope: `$routes->redirect('/test', '/pages/display/home');`

<details>
<summary>Old dispatcher</summary>
```
<?php
/**
 * The Front Controller for handling every request
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @since         0.2.9
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
// for built-in server
if (php_sapi_name() === 'cli-server') {
    $_SERVER['PHP_SELF'] = '/' . basename(__FILE__);
    $url = parse_url(urldecode($_SERVER['REQUEST_URI']));
    $file = __DIR__ . $url['path'];
    if (strpos($url['path'], '..') === false && strpos($url['path'], '.') !== false && is_file($file)) {
        return false;
    }
}
require dirname(__DIR__) . '/config/bootstrap.php';
use Cake\Network\Request;
use Cake\Network\Response;
use Cake\Routing\DispatcherFactory;
$dispatcher = DispatcherFactory::create();
$dispatcher->dispatch(
    Request::createFromGlobals(),
    new Response()
);

```
</details>

<details>
<summary>Old filters</summary>
```
DispatcherFactory::add('Asset');
DispatcherFactory::add('Routing');
DispatcherFactory::add('ControllerFactory');
```
</details>

### Expected Behavior

Visit `/test` in the browser and see the home template.

### Actual Behavior

I get a `\Cake\Routing\Exception\MissingControllerException` exception. I noticed this when upgrading our app from 3.2 but keeping the old dispatch process as we need to right now. (Am I missing something?)

I'll be happy to submit a PR but I can't quite figure out what's going on yet, but if you debug the exception and die in the `RoutingFilter` it's throwing the `RedirectException` but it carries on into the controller factory anyway.

<details>
<summary>Exception screenshot</summary>
![screen shot 2016-08-23 at 3 59 25 pm](https://cloud.githubusercontent.com/assets/184903/17909552/97b81784-694a-11e6-9b3b-4658c173b761.png)
</details>

**Comment by jeremyharris** [comment]
I think I've figured out why this is happening. The new `ControllerFactory` is the class that throws the `MissingControllerException` now whereas the [Dispatcher][1] itself was the one that threw the exception (the factory sort of silently failed, returning false).

[1]: https://github.com/cakephp/cakephp/blob/54fa6f3a9ae6f8dea120c2a7dd76406b35879f3a/src/Routing/Dispatcher.php#L79-L84

**Comment by markstory** [comment]
I'll take a look. The `RedirectException` should still cause a response to be returned. However, the event is not being stopped when it probably should be.
