### ISSUE TITLE
CakePHP has reached a milestone

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9339]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] Congratulations

CakePHP has exactly **6666** stars on GitHub.

![screenshot 1](https://cloud.githubusercontent.com/assets/551022/17935539/adf14986-69e9-11e6-82cf-8cbc6317c550.png)

This is both awesome, and means we're all doomed.

**Comment by jippi** [comment]
lol!

**Comment by ravage84** [comment]
We need some more watchers to get to 666 :smirk_cat:
