### ISSUE TITLE
Error after upgrade to 3.3.2.

### ISSUE THREAD

**Issue by giamma93** [cakephp/cakephp#9340]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2.
* Platform and Target: nginx/1.11.3, MySQL MariaDB 10.1.16 (MySQL 5.6), PHP 7.0.9.

### What you did
After upgrade from composer from 3.2.14 i've get this error:
Warning (4096): Object of class Cake\Database\Expression\FunctionExpression could not be converted to string in [/var/www/html/crm.iall.it/webroot/vendor/cakephp/cakephp/src/ORM/Association/SelectableAssociationTrait.php, line 137].

This is the code which give me the error:

        $ticketWorksSum = $this->find()
                        ->contain([
                            'TicketWorks' => function($q) use($worksIds,$excluded){
                                $q->select(['ticket_id','minuti_totali' => $q->func()->sum('minuti_complessivi')]);
                                if(count($worksIds) > 0){
                                    $q->where([function($exp) use ($worksIds){
                                        return $exp->notIn('TicketWorks.ticket_row_id',$worksIds);
                                    }]);
                                }
                                if (count($excluded) > 0) {
                                    $q->where([function($exp) use ($excluded){
                                        return $exp->notIn('TicketWorks.ticket_row_id',$excluded);
                                    }]);
                                }
                                return $q;
                            }
                        ])->select(['ticket_id'])
                    ->where(['ticket_id' => $ticket_id])->first();
I had to downgrade to 3.2.14 to fix the error.
Thanks for the help.

**Comment by raul338** [comment]
Try with master, a fix in #9337 was recently merged

**Comment by markstory** [comment]
Closing as this has already been fixed on master.
