### ISSUE TITLE
When many to many association is used the model implementation is overloaded

### ISSUE THREAD

**Issue by missqu** [cakephp/cakephp#9342]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.6.0-RC1 (but also checked with the latest 2.x).
* Platform and Target: YOUR WEB-SERVER - Chrome, DATABASE - MySQL, Linux Ubuntu 16.04.

### What you did
I have three models - Protocol, Competitor and CompetitorsProtocolsAss. Protocol has defined association to competitor (many to many)
`
public $hasAndBelongsToMany = array(
	'Competitor' => array(
		'className' => 'Competitor', 'joinTable' => 'competitors_protocols_ass', 'foreignKey' => 'protocol_id', 
		'associationForeignKey' => 'competitor_id', 'unique' => true, 'conditions' => '', 'fields' => '', 'order' => '', 
		'limit' => '', 'offset' => '', 'finderQuery' => ''
	) 
);
`

In my Controller I made two different calls:

`$this->CompetitorsProtocolsAss->myOwnMethod($id);`
`$protocol = $this->Protocol->findById($protocol_id);`

and

`$protocol = $this->Protocol->findById($protocol_id);`
`$this->CompetitorsProtocolsAss->myOwnMethod($id);`

The first one is working properly, and myOwnMethod from CompetitorsProtocolsAss class is called. The second one displays error, that I'm trying to call "myOwnMethod" query on the database:

> 2016-08-24 22:05:20 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'myOwnMethod' at line 1

### Expected Behavior
I expect, that I can always use the my implementation of the model class. So the myOwnMethod is always called, and the configured association should not impact, which implementation of model is loaded.

### Actual Behavior
After usage of Model where the many to many association is implemented, the implementation of associated class (in my fall it was implelemtation of CompetitorsProtocolsAss) is overriden with the default cakephp model implementation

I could not find any simillar issue and any information on Stack.. I tried to find sollution for this issue, but time presure is to big and I cannot invest more time.

As a workaround I moved myOwnMethod to the Protocol.

**Comment by markstory** [comment]
You need to explicitly define the `through` model if you want your concrete class used on the junction table consistently.

The second code path ends up with the registry alias being set to an automodel, which won't have your implemented methods.

Closing as this is a usage issue.
