### ISSUE TITLE
Html::script() with false block

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9350]
This only a stupid question, but it seems to me that it's incorrect/a bug that:

     $this->Html->script('my-file.js');

 returns

     <script src="/my-file.js"></script>

instead:

     $this->Html->script('my-file.js', ['block' => false]);

returns `NULL`.

**Comment by markstory** [comment]
I'm not seeing a `null` return on the third example locally. I get a script tag. Are you sure you're not including duplicate files? By default HtmlHelper prevents duplicate assets being included in a response render unless `once => false`.

**Comment by mirko-pagliai** [comment]
you're right, my mistake, sorry
