### ISSUE TITLE
3.x FormHelper::reset(__('Clear')) doesn't work

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9355]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3.2

### What you did
```php
    <?= $this->Form->reset(__('Clear')) ?>
```

### Expected Behavior
Should behave like:
```php
    <?= $this->Form->reset(__('Clear'), ['value' => __('Clear')]) ?>
```

### Actual Behavior
Prints "Reset"

**Comment by dereuromark** [comment]
I don't think the magic methods can be made to work like that.
For those it is always necessary to have options declared from the looks of the code:
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/FormHelper.php#L1537-L1539

**Comment by markstory** [comment]
There is no `reset()` method, and `__call()` requires the additional options to define attributes.

**Comment by dereuromark** [comment]
@ionas Extend the FormHelper and create those methods. This will allow you to leverage it the way you intend to.

**Comment by inoas** [comment]
Okay, if I can find some time I will add reset as a specific helper method?

**Comment by markstory** [comment]
We used to have one. I think I deleted it as reset inputs create some awkward user-experience and are so rarely used that I didn't think there was much value in keeping the method around with its tests.

**Comment by inoas** [comment]
I considered adding it to a sign-in form for a backend panel to reset the user input fields and password. It is a standard html feature but not used a lot nowadays, agreed. I don't even know if I will keep it.

It would only take an optional label as first argument. A few lines of code. If you want me to do it, let me know.

**Comment by markstory** [comment]
I'm not sure its worth having given how simple the 'raw' HTML is.

**Comment by inoas** [comment]
Okay leaving it be.
