### ISSUE TITLE
(question) assertHtml() with nested tags

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9364]
API for the `assertHtml()` is very thin and I can not very well understand the regex.

I've this code:

```
<blockquote>
  <p>First level</p>
  
  <blockquote>
    <p>Second level</p>
  </blockquote>
  
  <p>First level</p>
</blockquote>
```

How to properly write the `$expected` array, in this case?

I tried as well, but doesn't work:

```
$expected = [
    ['blockquote' => true],
    ['p' => true],
    'First level',
    '/p',
    ['blockquote' => true],
    ['p' => true],
    'Second level',
    '/p',
    '/blockquote',
    ['p' => true],
    'First level',
    '/p',
    '/blockquote',
];
```

Thanks.

**Comment by markstory** [comment]
`['blockquote' => []]` Is probably what you want.

**Comment by jadb** [comment]
Ah, beat me to it. So I'll just keep this link here if you need to look into more examples:

https://github.com/FriendsOfCake/bootstrap-ui/tree/master/tests/TestCase/View/Helper

**Comment by mirko-pagliai** [comment]
@markstory In which line of my example? And why?

**Comment by markstory** [comment]
In all the places where you are using `['blockquote' => true]`.

**Comment by mirko-pagliai** [comment]
@markstory @jadb I have seen examples carefully. But I still do not understand how to use the brackets, why some tags are nested and some not.

**Comment by markstory** [comment]
Tags are never nested. We often use indentation to make the code easier to read. Wrapping tags in arrays is necessary because arrays can't have duplicate keys. For simple tags, where there are no duplicates, you can do something like:

```php
$expected = [
  'p' => ['class' => 'red-box'],
   'text in the paragraph',
  '/p'
];
// Matches
<p class="red-box">
text in the paragraph
</p>
```

When you have duplicate tags you need to wrap the tag names in keys.

```php
$expected = [
  ['p' => ['id' => 'first-tag']],
  'first p text',
  '/p',
  ['p' => ['id' => 'second-tag']],
  'second p text',
  '/p',
];
// Matches
<p id="first-tag">
first p text
</p>
<p id="second-tag">
second p text
</p>
```

**Comment by mirko-pagliai** [comment]
Ok, very clear.
Last question (and then I stop to break!): what is the difference (returning to the first example) between `['blockquote' => true]` and `['blockquote' => []]`?

**Comment by markstory** [comment]
Does `['blockquote' => true]` work? I suspect `true` is shorthand for accept all attributes while `[]` means no attributes.
