### ISSUE TITLE
Array to string conversion when i try to access asset of my plugin.

### ISSUE THREAD

**Issue by NoczCore** [cakephp/cakephp#9366]
_This is a bug._
_CakePHP Version: 3.3.2_

**Hi,**
I have the error "Notice(8): Array to string conversion[CORE / src / Filesystem / File.php, line 579]" when i try to access asset of my plugin. The file exists and the url is valid.

Thanks you !

**Comment by jadb** [comment]
Sorry, but without a little more information, it's hard to help.

What's the code you have that is causing this error?

Also, please use the pre-populated templates when submitting an issue next time.

**Comment by NoczCore** [comment]
None of these codes is the problem, since I now have simply install version 3.3 and add a Media plugin that contains assets in its webroot.

**Here is the error:**
![Screenshot](https://i.gyazo.com/e4277a3fd7c970e28d4064958aa97e9b.png)

The app.min.js is in /plugins/Media/webroot/js/app.min.js.

**Comment by jadb** [comment]
Sorry, I meant your code. I can check cake's code referred to in the error (File.php line 579). But what's the code you have? 

This particular file (File.php) hasn't been changed really for 3.3.3 so any pointers (by showing your code) could help.

**Comment by NoczCore** [comment]
This is my code for the File.php, from line 572 to 592:

```php
public function mime()
    {
        if (!$this->exists()) {
            return false;
        }
        if (class_exists('finfo')) {
            $finfo = new finfo(FILEINFO_MIME);
            $type = $finfo->file($this->pwd()); // This is the line 579
            if (!$type) {
                return false;
            }
            list($type) = explode(';', $type);

            return $type;
        }
        if (function_exists('mime_content_type')) {
            return mime_content_type($this->pwd());
        }

        return false;
    }
```

**Comment by markstory** [comment]
What is the value of `$this->pwd()` it is not expected to be an array.

**Comment by NoczCore** [comment]
When i debug `$this->pwd()`, return `/var/www/CakeLab/plugins/Media/webroot/js/app.min.js`

**Comment by NoczCore** [comment]
Someone have any idea for solve this problem ?

**Comment by markstory** [comment]
No, because I don't think anyone knows how to reproduce the issue. That return from `pwd()` is not an array, which doesn't make sense with the error you're seeing.

**Comment by NoczCore** [comment]
Yes it's true. I try to fix this problem, but that doesn't make sense...

Now, i have this result:
![Screen](https://i.gyazo.com/75b37e353908ad1cce5f94533364d381.png)

**Comment by markstory** [comment]
@NoczCore That error is being displayed because the notice error is causing headers to be sent. I think you'll need to figure out why `pwd()` is returning an array before you'll get a working solution.

**Comment by NoczCore** [comment]
@markstory Okay, thanks you, i will try to resolve or get others informations for this problem.

**Comment by NoczCore** [comment]
I may have found something, when I modify the file contents ``app.min.js`` the problem disappears ! It's really strange..

**Comment by NoczCore** [comment]
I have solve this problem, but I do not know the real cause. It's really strange. Thank you for your help.
