### ISSUE TITLE
Using PSR-7 compatible request object in controller and tests

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#9369]
I don't get exactly how I can get a PSR-7 compatible request object in my controller and its tests.

I got the following in my controller:

```php
public function index() {
    $request = ServerRequestFactory::fromGlobals(); // Cake\Http\ServerRequestFactory
}
```

Via http://book.cakephp.org/3.0/en/development/testing.html#integration-testing-psr7-middleware I discovered I had to do the following in my controllers' integrationtest:

```php
public function setUp()
{
    $this->useHttpServer(true);
}
```
Next, I created the test like:

```php
public function testIndex() {
    $this->configRequest(['query' => [
        'test' => 'goingwell'
    ]]);

    $this->get('/controller/index');
}
```

When I debbugged the `$request` in the controllers action I got:

```php
object(Zend\Diactoros\ServerRequest) {
	[protected] headers => []
	[protected] headerNames => []
	[private] attributes => [
		'base' => 'vendor/bin',
		'webroot' => 'vendor/bin/',
		'session' => object(Cake\Network\Session) {
			[protected] _engine => null
			[protected] _started => null
			[protected] _lifetime => '1440'
			[protected] _isCLI => true
		}
	]
	[private] cookieParams => []
	[private] parsedBody => []
	[private] queryParams => []
	[private] serverParams => [
		'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
		'HOSTNAME' => '5344941f34f6',
		'TERM' => 'xterm',
		'PHPIZE_DEPS' => 'autoconf 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
		'PHP_INI_DIR' => '/usr/local/etc/php',
		'GPG_KEYS' => '1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763',
		'PHP_VERSION' => '7.0.8',
		'PHP_FILENAME' => 'php-7.0.8.tar.xz',
		'PHP_SHA256' => '0a2142c458b0846f556b16da1c927d74c101aa951bb840549abe5c58584fb394',
		'HOME' => '/home/bob',
		'PHP_SELF' => 'vendor/bin/phpunit',
		'SCRIPT_NAME' => 'vendor/bin/phpunit',
		'SCRIPT_FILENAME' => 'vendor/bin/phpunit',
		'PATH_TRANSLATED' => 'vendor/bin/phpunit',
		'DOCUMENT_ROOT' => '',
		'REQUEST_TIME_FLOAT' => (float) 1472475609.3676,
		'REQUEST_TIME' => (int) 1472475609,
		'argv' => [
			(int) 0 => 'vendor/bin/phpunit',
			(int) 1 => 'tests/TestCase/Controller',
			(int) 2 => '--filter',
			(int) 3 => 'testAuthCodeGrantSuccess'
		],
		'argc' => (int) 4
	]
	[private] uploadedFiles => []
	[private] protocol => '1.1'
	[private] stream => object(Zend\Diactoros\PhpInputStream) {
		[protected] resource => resource
		[protected] stream => 'php://input'
		[private] cache => ''
		[private] reachedEof => false
	}
	[private] method => 'GET'
	[private] requestTarget => null
	[private] uri => object(Zend\Diactoros\Uri) {
		[protected] allowedSchemes => [
			'http' => (int) 80,
			'https' => (int) 443
		]
		[private] scheme => 'http'
		[private] userInfo => ''
		[private] host => ''
		[private] port => null
		[private] path => '/'
		[private] query => ''
		[private] fragment => ''
		[private] uriString => null
	}
}
```
> I can't see the query parameter at all, a request object of the phpunit command is created.

Can anybody explain me how to use a PSR-7 compatible request object in my controller, and run tests on it?

Thank you very much!

**Comment by ADmad** [comment]
Why are you doing `$request = ServerRequestFactory::fromGlobals();` in your controller action instead of just using `$this->request`?

Even with psr7 middleware usage your controllers are still meant to use `$this->request` which is instance of `Cake\Network\Request`. The new middleware layer does not change anything in your controllers.

**Comment by bobmulder** [comment]
I did that to get an instance of a psr-7 request object. How else should I get one?

**Comment by ADmad** [comment]
Why do you want one? As I already said controllers continue to use `Cake\Network\Request` instance as before.

**Comment by ADmad** [comment]
If you need help getting a better understanding of the new middleware layer please ask on slack/IRC or post a question on the forum.

**Comment by bobmulder** [comment]
So PSR-7 requests are only supported by middlewares and not controllers?

I want a PSR-7 request object because a specific library requires one.

**Comment by markstory** [comment]
@bobmulder Controllers will be getting psr compatible request objects in 3.4.0. I wanted to gradually introduce and refactor the request/response objects, and couldn't do all the work in 3.3

**Comment by bobmulder** [comment]
Thank you for your kind explanation @markstory! Good luck with the new release! Looking forward!
