### ISSUE TITLE
User as entity inside the session

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#9370]
Each time when I start to develop a new application I would love to see a `User` entity inside the session instead of an array. I know that storing objects inside the session isn't a common practice so I started to google for pros and cons about this.

Maybe I overlooked something important but it seems that storing an object inside the session isn't a big issue since autoloading. Without an autoloader you need to make sure that the necessary classes are loaded before you get the object from the session so with composer not really an argument against it. Another issue people discussing about is the serialization of private properties. Cake's ORM or cake at all doesn't use any private properties.

I also found something about objects in session in doctrine's ORM documentation. It seems that they're suggest to use objects in sessions for specific use cases: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/entities-in-session.html

If I didn't overlooked something the two arguments above were the most common arguments against objects in session but I think these arguments are obsolete nowadays. What do you think?

**Comment by dereuromark** [comment]
I think storing objects in the session is never a good idea, especially for user experience.
Every time you upgrade your code and the object itself slightly changes, you will automatically cause quite some issues for the data in the user's session, effectively killing the content, maybe worse depending on the way you catch the error.
So IMO you should always toArray() and store that, and patch it back into afterwards, that is also quite BC even if you modify fields.

**Comment by steefaan** [comment]
Mhm... if you change the structure/fields of your database you need to "refresh" the stored user anyways, independent of an entity or an array. Yes I could convert it to an entity after receiving it from the session but it feels like an array has more disadvantages than an entity and the disadvantages an entity has, has an array as well.

**Comment by markstory** [comment]
Objects can sometimes end up with references to unserializable objects which can hamper storing them in the session. I'm not against storing entities in the session, as an opt-in feature. I think it will be useful for folks that need it. It needs to be an opt-in feature so we don't break applications.

**Comment by thinkingmedia** [comment]
What's wrong with doing this?

```
   class User extends Entity { ... }

   $user = new User($this->Auth->user());
```

**Comment by josegonzalez** [comment]
@thinkingmedia the idea is that it would be done "automagically" by the framework.

Personally what we do at work is something like so:

**Comment by ADmad** [comment]
You can already pass an entity to Authcomponent:setUser() in 3.3. So there's nothing more we need to do. The default behavior should stay of using arrays.

**Comment by burzum** [comment]
I think there is no reason to make it an entity by default for the reason Mark named. While we don't have a need for the data to be an entity so far I like @josegonzalez approach.

@steefaan I suggested you yesterday on Skype to simply implement a component that will do this automatically for you when you *read* the user from the session. You could extend Auth or the Session I wouldn't write it in the session as entity.

**Comment by steefaan** [comment]
@josegonzalez The example you provided is an override of `_getUser()` from cake's `AuthComponent` and moreover it's an incomplete example, right? Because if you would override it this way, stateless authentication will not longer function.

In general it would work to convert the session back to an entity inside a component but I still think it's reasonable to store the entity itself in the session. Mainly for two reasons:

1. Session is also accessible in middleware, converting it inside a component is too late because your session handling is inconsistent between middleware and the rest of your application.
2. The only valid reason is from @markstory even if I think it will almost never happen.
    - @dereuromark is concerned about changes in the database but you will have the same problems with an array
    - I don't want to compare symfony with cake here but symfony uses entities as well: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php#L29

**Comment by dereuromark** [comment]
No I am not concerned about DB changes.
As mentioned before by me and @markstory you will get fatal errors (object not found) if your entity class code changes even only a bit ("references to unserializable objects" - afaik could be an added line of code completely unrelated to the actual input/output of the entity data) once you upgrade your code on the server.
This make the customer lose all his data just because of this small change, and this will happen again and again for no real good reason.

**Comment by lorenzo** [comment]
I think there is an opportunity to pass an option to the Authenticate objects to store the entity instead of an array. That would probably be a step towards what @steefaan wants, without breaking BC and still making a statement that storing objects in session is probably not the best idea.

**Comment by ADmad** [comment]
Considering that you can already do the following in 3.3 why do we need anything more?

```php
// in login() action
$user = $this->Auth->identify();
if ($user) {
    $entity = new \App\Model\Entity\User($user);
    $this->Auth->setUser($entity);
    // redirect
}
```

**Comment by lorenzo** [comment]
@ADmad the user that is returned is the `->toArray()` of a user entity, given the existence of `hiddenProperties` there is a chance that those calls are not the reverse of each other

**Comment by lorenzo** [comment]
Of course, returning an entity in identify make things difficult, since identity could sometimes return array and sometimes return entity, depending on the authentication adapter that got the credentials right. That's not ideal.

**Comment by thinkingmedia** [comment]
```
class MyAuthComponent extends AuthComponent {
    public function user($key = null) {
        if($key === null && parent::user('id')) {
                 return TableRegistry::get('user')->get(parent::user('id'));
        }
        return parent::user($key);
    }
```

**Comment by dereuromark** [comment]
Closing as multiple solutions are pointed out which can already be applied to current 3.x code if one really wants to.

**Comment by andruhapx** [comment]
I also used component override. Created file src/Controller/Component/AuthComponent.php:

```
<?php
namespace App\Controller\Component;

use Cake\ORM\TableRegistry;

class AuthComponent extends \Cake\Controller\Component\AuthComponent {

	public function entity() {
		$id = $this->user('id');
		return $id ? TableRegistry::get('Users')->get($id) : null;
	}
}
```
