### ISSUE TITLE
Query::from() doesn't accept single expressions

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#9372]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2

The API documentation for Cake\Database\Query::from() has the following method signature:
```from( array|Cake\Database\ExpressionInterface|string $tables [] , boolean $overwrite false )```

Followed by this description:

> Adds a single or multiple tables to be used in the FROM clause for this query. Tables can be passed as an array of strings, array of expression objects, a single expression or a single string.

But the code for this method works only with strings and arrays, not single expressions. I guess this is a bug in the doc comments.

Link: http://api.cakephp.org/3.3/class-Cake.Database.Query.html#_from

**Comment by markstory** [comment]
Pull request up now.
