### ISSUE TITLE
Can't pass webroot parameter to the shell.

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9374]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 2.8.6.
- Platform and Target: Apache, MySQL, Linux.
### What you did
1. Tried to pass 'webroot' parameter to cake test: `cake test app --webroot='../'`
2. Tried to pass 'webroot' parameter to a shell script: `my_shell --webroot='../'`

```
public function getOptionParser() {
    $ConsoleOptionParser = parent::getOptionParser();
    $ConsoleOptionParser->addOption('webroot');
}
```
### Expected Behavior

The documentation of ShellDispatcher says that $params contains command switches parsed from the command line. So I would expect that the value of `$this->params['webroot']` would be the one I pass and WWW_ROOT constant would have the correct value.
### Actual Behavior
1. `cake test app --webroot='../'` - results in a message "unrecognized option --webroot".
2. `my_shell --webroot='../'` - Passing 'webroot' has no effect and the value of WWW_ROOT constant is wrong although `$this->param('webroot')` returns the value I pass.

**Comment by markstory** [comment]
The `webroot` option is a 'special' option that is parsed by the ShellDispatcher to conditionally set the `WWW_ROOT` constant.

While I don't like the behavior (it was removed in 3.x) I don't think we can remove it without breaking compatibility. The `app`, `root` and `working` parameter names have similar gotchas.

**Comment by markstory** [comment]
Closing as a pull request is up now.
