### ISSUE TITLE
validation bug preg_match failure case not supported

### ISSUE THREAD

**Issue by mlingureanu** [cakephp/cakephp#9375]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.8.6
- Platform and Target: windows 10
  PHP Version 5.5.19
  Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.19
### What you did

I changed ValidationTest.php method testUrl() like this:

```
/**
 * testUrl method
 *
 * @return void
 */
    public function testUrl() {
        $url = 'https://www.google.dk/maps?layer=c&amp;sll=55.673441999999994,12.582521&amp;cid=1904466832282534658&amp;panoid=e_bhIjBi0uMAAAQIt4--wg&amp;cbp=13,210.99,,0,0&amp;q=s%C3%B8ren+k&amp;ie=UTF8&amp;hq=s%C3%B8ren+k&amp;hnear=&amp;ll=55.673442,12.582521&amp;spn=0.006295,0.006295&amp;t=m&amp;cbll=55.67344,12.583107&amp;source=embed&amp;output=svembed';
        Debugger::log(Validation::url($url));
        $this->assertTrue(Validation::url($url));

    }

}
```

```
/**
 * Runs a regular expression match.
 *
 * @param string $check Value to check against the $regex expression
 * @param string $regex Regular expression
 * @return bool Success of match
 */
    protected static function _check($check, $regex) {
        Debugger::log(preg_match($regex, $check));
        if (is_string($regex) && is_scalar($check) && preg_match($regex, $check)) {
            return true;
        }
        return false;
    }
```
### Expected Behavior

if preg_match return 1 then function _check return true , if preg_match return 0 function _check return false 
### Actual Behavior

if preg_match return false function _check return false (it's should be trowing an exception)
### Documentation update

To add a warning in documentation to increase  Apache's default stack size to 8M
http://stackoverflow.com/questions/5058845/how-do-i-increase-the-stack-size-for-apache-running-under-windows-7

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by dereuromark** [comment]
Are you sure about this?

    preg_match($regex, $check)

can safely return false here which in turn will make the whole check return false.
Thus the result is "this URL is not valid" basically. A failure is basically the same case as an invalid input: Returning false.

**Comment by markstory** [comment]
I'm not sure validation methods should be throwing exceptions for anything other than programmer error. End-user supplied input should not trigger exceptions as the purpose of validation is to safeguard against exceptions elsewhere in the application.

**Comment by mlingureanu** [comment]
On windows with apache stack size set by default to 1M everything freeze.
Under Windows, the Apache webserver executable (httpd.exe) is built with a stacksize of 256KB. The PHP command line executable (php.exe) is built with a stacksize of 8MB. The safe value for pcre.recursion_limit should be set in accordance with the executable that the script is being run under (524 and 16777 respectively).
I changed in php.ini pcre.recursion_limit to 524 and let apache stack size to daefault(1M) in apache httpd.conf and I get response false, from preg_match.
http://stackoverflow.com/questions/7620910/regexp-in-preg-match-function-returning-browser-error
 
There are some bugs related to preg_match, thats why, I think it's better to trow exception, because it took me 2 days to debug this.
Preg_match depends to much on configs and should be a warning about this in CakePhp.

**Comment by ADmad** [comment]
We can log an error if `preg_match()` returns `false`, an exception is unacceptable for validators.

**Comment by ADmad** [comment]
Also in general to save yourself from such windows gotchas you should develop using a linux VM :)

**Comment by mlingureanu** [comment]
At least a warning to increase stack size to 8M in apache config, should be written in CakePhp cookbok.

**Comment by mlingureanu** [comment]
I don't think it's ok, if server stop responding, when it's reach to this validation and it's not logging any error.

**Comment by markstory** [comment]
Can we even do any logging when the server hits its stack size?

**Comment by ADmad** [comment]
> At least a warning to increase stack size to 8M in apache config, should be written in CakePhp cookbook.

I am fine with adding a note in the manual regarding stack size. We could even put a check on homepage of app skeleton.

**Comment by markstory** [comment]
Closing as no one seems interested in documenting this edge case.
