### ISSUE TITLE
CounterCache should ignore dirty fields

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#9380]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.3.2

I have a case where I'm populating a table and I don't need the CounterCache behavior since I already have the values in place. I could disable the behavior for this operation but I think it would be interesting to handle this case the same way the Timestamp behavior does. If this makes sense I can try to do a PR.

**Comment by ADmad** [comment]
Skipping countercache value calculation if field is dirty could be an opt-in feature. I have at times kept the counter cache field as hidden input in form as it's value is used for other things. So having this feature by default would break such usage.

**Comment by dereuromark** [comment]
+1 for opt-in then.
Anyone willing to provide a PR here?

**Comment by berarma** [comment]
It was more a heads-up on something that seemed contradictory since two very similar behaviors did it so differently. I can't work on this right now but if you don't mind having this issue around I could get to it sometime.

**Comment by cleptric** [comment]
I looked into this for a little bit. I guess, this should be enabled via the config, like

```       
$this->addBehavior('CounterCache', [
    'Articles' => [
        'comment_count' => [
            'ignore_if_dirty' => true
        ]
    ]
]);
```

I would then check in `CounterCacheBehavior::beforeSave()` if the field is dirty and ignore it.
If this is the way to go, I would try to implement it.
@ADmad @dereuromark

**Comment by markstory** [comment]
I think an `ignoreIfDirty` option makes sense.

**Comment by dereuromark** [comment]
PR now open.

**Comment by berarma** [comment]
I would call it ```ignoreDirty```, short for "ignore dirty fields".
