### ISSUE TITLE
Integers as column names dont work

### ISSUE THREAD

**Issue by mo86** [cakephp/cakephp#9382]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: XAMPP

### What you did
Trying to save form data into a database table which has numbers as column names. For example column '333'.

### Expected Behavior
Cake should wrap ALL column names in `column_name` (grave accents) like phpMyAdmin would do it to make the insert query work.

### Actual Behavior
Cake is not wrapping column names in grave accents so it returns an SQL error while saving if you have a number as column name.

**Comment by dereuromark** [comment]
Please see "quoteIdentifiers" at http://book.cakephp.org/3.0/en/orm/database-basics.html

**Comment by ADmad** [comment]
You need to turn on identifier quoting in database confug in config/app.php

**Comment by mo86** [comment]
Your are right! I didnt know about the option "quoteIdentifiers". But there is still a bug because it doesnt work for DB columns which have just an integer as name. All string column names get their quotes but the  "quoteIdentifiers" doesnt work for integers.

**Comment by markstory** [comment]
We don't support integer only column names.

**Comment by thinkingmedia** [comment]
@markstory does that include number prefix?

**Comment by markstory** [comment]
No those are fine.

**Comment by thinkingmedia** [comment]
@markstory `123_title` is not a valid PHP identifier. You can't `$entity->123_title` and you can't use `@property` to declare it for auto-complete either.

**Comment by mo86** [comment]
Okay so is there any reason why we dont support it? Imagine you get a project from a company and you can NOT define the database structure because someone else provides it for you. So in this situatuin Cake is automatically not an option anymore?

**Comment by ADmad** [comment]
@thinkingmedia Right so that's a good reason to avoid table column names starting with integer. You will habe to use Entity::get()/set() to deal with such properties.

**Comment by thinkingmedia** [comment]
@mo86 

![19vtuq](https://cloud.githubusercontent.com/assets/551022/18180683/f5bb677a-7055-11e6-8b01-08f6c2186eb3.jpg)

**Comment by mo86** [comment]
@thinkingmedia Don't waste your time for posting a dumb meme.

**Comment by dereuromark** [comment]
I think if we can get CakePHP to support at least the very basics here, we should do it.
It would help those migrating. And at least on the quoting part it should be a fix not too hard to do.

**Comment by thinkingmedia** [comment]
@mo86 oh come on. That was funny. Programmers have no sense of humor.

**Comment by ADmad** [comment]
@thinkingmedia He's probably just frustrated since he has to deal will someone else's bad decision.

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/cakephp/issues/9382 .

**Comment by raul338** [comment]
@dereuromark that is this issue

**Comment by josegonzalez** [comment]
@dereuromark I think you want https://github.com/cakephp/cakephp/issues/9391, which I'm in favor of us fixing. Bake would probably barf on it - as it should imo - but we can certainly make quoting work so that users can use integer column names.

**Comment by dereuromark** [comment]
Sry Dup of https://github.com/cakephp/cakephp/issues/9391 i meant.
Are you able to provide a PR, @raul338 

@josegonzalez 
Yes, bake does not need to work, but the ORM should at least in a basic way.
