### ISSUE TITLE
buildMiddlewareBefore & buildMiddlewareAfter events

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#9383]
To adding middleware from plugins there is an event `buildMiddleware` as you can see [here](https://github.com/cakephp/cakephp/blob/master/src/Http/Server.php#L80).

I think it would be nice to change`buildMiddleware` to `buildMiddlewareBefore` and add an additional event called `buildMiddlewareAfter`, which is triggered directly after `$middleware->add($this->app);`. Currently it's not possible to add middleware after app and this would fix it. For BC reasons `buildMiddleware` could be kept and an additional event `buildMiddlewareBefore` will be triggered.

Here is a good example from the javascript world what the target is: http://stackoverflow.com/questions/24258782/node-express-4-middleware-after-routes/29442079#29442079

**Comment by antograssiot** [comment]
I might be missing something but you could already load the Middleware wherever you want (before, in the middle or at the end) using:  

```php
use Cake\Event\EventManager;

EventManager::instance()->on(
    'Server.buildMiddleware',
    function ($event, $middleware) {
        $middleware->add(new Awesome1Middleware());
//or
        $middleware->insertBefore(\Cake\Routing\Middleware\RoutingMiddleware::class,new Awesome2Middleware());
});
```

**Comment by markstory** [comment]
Given that there are both append and prepend methods why is another event needed?
