### ISSUE TITLE
vendor/cakephp-plugins.php for plugins

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9384]
I have had this problem:
http://stackoverflow.com/questions/39254126/cakephp-loads-plugin-for-test/39256083#39256083

Briefly: the plugin `FirstPlugin` uses the plugin `SecondPlugin`, installed with composer.
No problem normally.

By writing the tests for plugin `FirstPlugin`, the plugin` SecondPlugin` was not found.

At the end I realized that the file `FirstPlugin/vendor/cakephp-plugins.php` was missing.

So I did a test. In an app I tried deleting the `vendor` directory and I saw that the file is re-created.

Then I deleted the `FirstPlugin/vendor` directory and the file is not re-created automatically.

Is it normal?

**Comment by markstory** [comment]
Composer dependencies shouldn't be recursively installed which is why there is no `vendor/cake-plugins.php` inside FirstPlugin. I'm not sure I completely understand what's going on though.

**Comment by mirko-pagliai** [comment]
The problem is here:
http://api.cakephp.org/3.2/source-class-Cake.Core.Plugin.html#134

For nested plugins:

    $config['path'] = Configure::read('plugins.' . $plugin);

returns `NULL`.

**Comment by lorenzo** [comment]
We don't support nested plugins

**Comment by mirko-pagliai** [comment]
@lorenzo ok, so if I need to test a plugin that loads and uses other plugins, I have to indicate the path manually for these?

**Comment by lorenzo** [comment]
Yeah, that is a way... I usually just manually include all the dependent plugins in the composer.json of the main repo until I publish the plugin.

**Comment by mirko-pagliai** [comment]
@lorenzo how to do with composer?

My `composer.json` (of `FirstPlugin`):

    "autoload-dev": {
        "psr-4": {
            "SecondPlugin\\": "vendor/SecondPlugin-path/src",
            "FirstPlugin\\Test\\": "tests",
        }
    },

My `tests/bootstrap.php`:

    Plugin::load('SecondPlugin', ['autoload' => true, 'bootstrap' => true]);

But, nothing to do, `MissingPluginException`.

**Comment by lorenzo** [comment]
You need to move the json you have in your plugin and inline it in your app's composer. Composer only cares about the top level json file

**Comment by mirko-pagliai** [comment]
@lorenzo, i'm testingmy plugin. The plugin path is the root path! So its composer.json is the top level!

**Comment by ADmad** [comment]
Did you run `composer install` in folder containing that composer.json?

**Comment by mirko-pagliai** [comment]
@ADmad yes and the `vendor/` directory (inside `FirstPlugin`) contains the plugin properly
