### ISSUE TITLE
Saving belongsToMany with _joinData using matrix data not working.

### ISSUE THREAD

**Issue by andrecavallari** [cakephp/cakephp#9386]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3 Red Velvet
* Platform and Target: MAMP PRO on OSX, PHP version 5.6.10, Postgresql 9.5.4

### What you did
I tryied to save a matrix of data using belongsToMany and _joinData, the data to save can be viewed here:
http://pastebin.com/pkbT9YCW

### Expected Behavior
It was expected to save the Main Entity and other 4 associated entities, assuming that first two entities have same id but with different _joinData values, and both last two entities have same id too with different _joinData values. So 4 entities should be saved.

### Actual Behavior
Four associated entities was created, but only 2 different associated entities was saved, it have assumed the different id's for vehicle_car_years associated data.

**Comment by markstory** [comment]
BelongsToMany associations require that the 'foreign keys' are unique. You can't save duplicate data into the junction table using a BelongsToMany.
