### ISSUE TITLE
allow values except some value in "ExistsIn" rule

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9387]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### Expected Behavior
"ExistsIn" check all values except some values
for example when we set a property to "0" this rule return true and not check for that
```
$rules->add($rules->existsIn(
    ['user_id',], 
    'Users',
    ['except'=>[0,....] ]//or ['allow'=>[0,....] ]
);
```

**Comment by markstory** [comment]
What situations do you have that require special values to not need to existIn an associated table?

**Comment by thinkingmedia** [comment]
Looks like you're trying to enforce user roles. You can do that with a behavior and it would be easier to maintain.

**Comment by lorenzo** [comment]
You can decorate the rule with your own logic

```php
$rule = function ($entity, $options) use ($builder) {
    if (in_array($entity->field, [... except values...])) {
        return false;
    }

    $rule = $builder->existsIn(...);
    return $rule($entity, $options);
};
```

I'm closing this since I don't think rules should focus on too many things at once, and they are also easy to enhance, either by inheritance or function decoration.
