### ISSUE TITLE
PaginatorHelper sort() method generates links without keeping the GET parameter: limit

### ISSUE THREAD

**Issue by KostasDaskal** [cakephp/cakephp#9390]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.3
- Platform and Target: Ubuntu 14.04, Apache Mysql 5.6.31 Php 5.5.9

My url is: 
`/users?advanced_search=1&username=Greg&limit=100`

I use the paginator helper to generate sort urls like so: 
`$headers[] = $this->Paginator->sort('username', 'Name');`

The resulting Url to click on for sorting at my table header is: `users?advanced_search=1&usrname=Greg&sort=usrname&direction=asc`

The limit parameter is gone, resulting to a default 25 users that I set if no limit is found instead of 100.

Diving into the framework, the magic happens at PaginatorHelper::generateUrl method:

```
$paging = $this->params($model);

$paging += ['page' => null, 'sort' => null, 'direction' => null, 'limit' => null];
$url = [
   'page' => $paging['page'],
   'limit' => $paging['limit'],
   'sort' => $paging['sort'],
   'direction' => $paging['direction'],
];
```

`$paging['limit']` is always null, this is the result of `debug($paging)`:

```
[
    'finder' => 'all',
    'page' => (int) 1,
    'current' => (int) 2,
    'count' => (int) 2,
    'perPage' => (int) 100,
    'prevPage' => false,
    'nextPage' => false,
    'pageCount' => (int) 1,
    'sort' => null,
    'direction' => false,
    'limit' => null,
    'sortDefault' => false,
    'directionDefault' => false
]
```

From what I understand, limit will always be overwritten to null no matter what limit I set or pass, unless I do something hacky in the framework like:

```
$url = [
            'page' => $paging['page'],
            'limit' => $this->request['query'] ? $this->request['query'] : $paging['limit'],
            'sort' => $paging['sort'],
            'direction' => $paging['direction'],
        ];
```

Does limit live on as the "perPage" parameter?
this is what the function generateUrl returns at the end:
`/2.0/users?advanced_search=1&amp;usrname=Greg&amp;sort=usrgroup&amp;direction=asc`

**Comment by thinkingmedia** [comment]
I'm working on a PR for the pagination helper. I can fix this as well.

**Comment by markstory** [comment]
Awesome thanks @thinkingmedia

**Comment by thinkingmedia** [comment]
I haven't forgot. PR will be up soon.

**Comment by jimgwhit** [comment]
You can write your own paginator or use one existing which is what I do, mine has a place for adding pagination links and appending to the links, similar to the one in laravel.  But really a paginator is probably the easiest thing in any language to write.

**Comment by dereuromark** [comment]
@jimgwhit What is your point? I do not find your comment constructive towards the issue at hand.

**Comment by thinkingmedia** [comment]
related #9310

**Comment by thinkingmedia** [comment]
related cakephp/doc#4318

**Comment by jimgwhit** [comment]
@dereuromark the point is there are better paginators, why even use the one in cakephp.  The one I use is similar to laravels, and is 100% better.  But really dude, writing of a paginator is php or java or asp or asp.net 101. Probably the easiest thing in the world for most people to do, of course newbees want everything these days built in. When I programmed in servlets and jsp, I learned to write my own paginator, maybe just maybe others could learn to do the same.  Even in laravel I don't use the built in paginator, I write my own, ditto for Auth.

**Comment by inoas** [comment]
@dereuromark You will hear this very very rarely out of my mouth: Probably troll alert. Trust me or dig into the comment history.

**Comment by thinkingmedia** [comment]
@jimgwhit this comment thread is for users working to resolve the issue. When you post comments they get broadcasted to all participants. So you're not likely to get a positive reaction when you go off topic. It just makes the comment thread longer and makes it difficult for the original user to get support.

**Comment by jimgwhit** [comment]
@inoas I was going to drop it, but after reading your comment I figure you can't walk and chew gum at the same time.

**Comment by jimgwhit** [comment]
> You will hear this very very rarely out of my mouth: Probably troll alert. Trust me or dig into the comment history.

But can you walk and chew gum at the same time. I didn't think so.

**Comment by dereuromark** [comment]
@thinkingmedia To go back to topic, what is the current status here?

**Comment by thinkingmedia** [comment]
@dereuromark I did a PR that was merged, but I did not test if this was resolved. I can look into it.

**Comment by 3811015** [comment]
@dereuromark @thinkingmedia 
Can you link the PR please.
I am not shure if I am falling over the same issue or if it is something else...

**Comment by thinkingmedia** [comment]
@3811015 I think this issue has not been fixed.

I'll try to get to it soon.

**Comment by 3811015** [comment]
Originalnachricht

Von: Mathew Foscarini
Gesendet: Freitag, 18. November 2016 05:21
An: cakephp/cakephp
Antwort an: cakephp/cakephp
Cc: Andreas Witte; Mention
Betreff: Re: [cakephp/cakephp] PaginatorHelper sort() method generates links without keeping the GET parameter: limit (#9390)



@3811015<https://github.com/3811015> I think this issue has not been fixed.

I'll try to get to it soon.

-

**Comment by cleptric** [comment]
I tried to reproduce it with 3.2.3 and it worked as expected. Clean cakephp-app setup tag 3.2.3 and version set to 3.2.3 inside the composer.json

**Comment by markstory** [comment]
Thanks for taking another look @cleptric
