### ISSUE TITLE
DB quoteIdentifiers => true doesnt work for integer column names

### ISSUE THREAD

**Issue by mo86** [cakephp/cakephp#9391]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: XAMPP

### What you did
Trying to save data to a table which has integers as column names  while setting  'quoteIdentifiers' => true

### Expected Behavior
  'quoteIdentifiers' => true should quote ALL column names. 

### Actual Behavior
  'quoteIdentifiers' => true wraps the column names only for string names.

**Comment by mo86** [comment]
Its because of this. Only string names are quoted:  

protected function _quoteInsert($query)
    {
        list($table, $columns) = $query->clause('insert');
        $table = $this->_driver->quoteIdentifier($table);
        foreach ($columns as &$column) {
            if (is_string($column)) {
                $column = $this->_driver->quoteIdentifier($column);
            }
        }
        $query->insert($columns)->into($table);
    }

**Comment by markstory** [comment]
Closing as a pull request is open now to fix this issue.
