### ISSUE TITLE
SecurityComponent blackholes delete requests

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9392]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.6
* Platform and Target: Linux, MySQL, Apache.

### What you did
In the controller:
```
    public $components = array(
		'Auth',
		'Flash',
		'Paginator',
		'Security',
		'Session',
	);
```
In the view:
```
echo $this->Form->postLink(
	__d('admin', 'Delete'),
	array(
		'action' => 'delete',
		1,
	),
	array(
		'confirm' => __d('admin', 'Are you sure you want to delete # %s?', 1)
	)
);
```
### Expected Behavior
I would expect that `delete()` action would delete the record.

### Actual Behavior
The request to delete action is blackholed.
> Stack Trace
/Cake/Controller/Component/SecurityComponent.php line 240 → SecurityComponent->blackHole(UserCardsController, string)
```
        if (!in_array($this->_action, (array)$this->unlockedActions) && $hasData && $isNotRequestAction) {
            if ($this->validatePost && $this->_validatePost($controller) === false) {
                return $this->blackHole($controller, 'auth');
            }
```
[internal function] → SecurityComponent->startup(UserCardsController)
/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(UserCardsController, CakeRequest)
/www/index.php line 107 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by markstory** [comment]
Is this emulating a `DELETE` request or is it just that the action is named `delete`?

**Comment by bancer** [comment]
It is just an action `delete()` that deletes a record (almost identical to what cake bake generates).

**Comment by markstory** [comment]
Interesting, does the form have a security component token?

**Comment by bancer** [comment]
```
<form action="/my_controller/delete/1" name="post_57c9230817e2f198958123" id="post_57c9230817e2f198958123" style="display:none;" method="post">
    <input type="hidden" name="_method" value="POST"/>
    <input type="hidden" name="data[_Token][key]" value="80d915cb21dbecc3f202e81243546abbc8056e61a964b3c51897116f598f018c1b52126abddc8fdecdb56440db0dcdf03aa25153fa75d604248f6465edb75960" id="Token1019088754"/>
    <div style="display:none;">
        <input type="hidden" name="data[_Token][fields]" value="dd5256785f30b5d0335562dee81710da9160b696%3A" id="TokenFields1028966523"/>
        <input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked1295288917"/>
    </div>
</form>
<a href="#" onclick="if (confirm(&quot;Are you sure you want to delete # 1?&quot;)) { document.post_57c9230817e2f198958123.submit(); } event.returnValue = false; return false;">Delete</a>

**Comment by markstory** [comment]
Thanks. I'll take a look this weekend.

**Comment by markstory** [comment]
I'm not able to reproduce this. I used bake to generate some new views (which use postLink() and a delete action name). I was able to delete records without any problems. Do you by any chance have nested form tags?
