### ISSUE TITLE
Numeric column names break baked templates

### ISSUE THREAD

**Issue by mo86** [cakephp/cakephp#9393]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: XAMPP

### What you did
Having  a few database columns which names are just numeric and "baked" all models/templates.

### Expected Behavior
A baked template should work with numeric column names.

### Actual Behavior
If you bake all templates for Model "Foo" and model Foo has a column named "123" than cake bakes for example an index.ctp with the following code:

`<?= h($foo->123) ?>`

but it should output this:

`<?= h($foo->{123}) ?>`

**Comment by dereuromark** [comment]
Sounds like an issue for https://github.com/cakephp/bake/issues

**Comment by mo86** [comment]
Thanks i will move it :)
