### ISSUE TITLE
Styling Output: only one tag

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9394]
I have noticed that the shell can only handle 1 tag for output.
Example:

        $this->_io->styles('bold', ['bold' => true]);
        $this->out('<bold>comment</bold>');
        $this->out('<error>error</error>');
        $this->out('<bold><error>comment</error></bold>');
        $this->out('<error><bold>error</bold></error>');

Result:

![Alt text](http://oi63.tinypic.com/5czx3n.jpg)

Is it normal?

**Comment by thinkingmedia** [comment]
Use the issue template please.

**Comment by markstory** [comment]
Yes this is normal. Make new tags if you want to combine styles together. Its a simple CLI formatter not CSS + HTML.

**Comment by mirko-pagliai** [comment]
Sorry if I reopen this topic.  
But look at this:

    mirko@debian-lenovo:~/Server/mirkopagliai$ bin/cake backup import
    <error>Error: Missing required arguments. filename is required.</error>
    Usage:
    cake mysql_backup.backup import [-h] [-q] [-v] <filename>

    Options:

    --help, -h     Display this help.
    --quiet, -q    Enable quiet output.
    --verbose, -v  Enable verbose output.

    Arguments:

    filename  Filename. It can be an absolute path


![Alt text](http://i68.tinypic.com/2598qr4.png)

Is it me or Cake?

**Comment by markstory** [comment]
@mirko-pagliai That looks like an issue in CakePHP. I'll get that fixed.

**Comment by mirko-pagliai** [comment]
Thanks as usual!
