### ISSUE TITLE
Detect HTTP method in route

### ISSUE THREAD

**Issue by JayPHP** [cakephp/cakephp#9397]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### What you did
```
if ($this->request->is(['post'])) {
    return $this->redirect(['controller' => 'Applications', 'action' => 'add']);
}
```

### Expected Behavior
To be able to detect the post method in the route, for example;
```
$routes->connect('/', 'GET', ['controller' => 'MyController', 'action' => 'index']);
$routes->connect('/', 'POST', ['controller' => 'MyController', 'action' => 'add']);
```
### Actual Behavior
AFAIK, this isn't currently possible in Cake.

I think this would be a great feature and allow for cleaner code, thoughts?

**Comment by JayPHP** [comment]
This already exists

**Comment by JayPHP** [comment]
@ADmad Actually, don't you think the current method of doing this is a bit hacky? Shouldn't the HTTP method be a separate parameter rather than in the array? 
Maybe I'm looking at it wrong but I see the second (array) parameter as the values used to specify what to do when this route is met. Seems like an odd place to then put the required route method?

**Comment by thinkingmedia** [comment]
The problem with using routing to map HTTP request types to an action is that it hides this logic. So when you have a controller action like `edit()` there is nothing in the controller to indicate it's a post only route.

So you have to then add `$this->request->is('post')` to block if necessary.

When you look at other frameworks in other languages the HTTP request time is defined at the action. I was thinking that phpdocs would be a nice way to enforce this.

```
     /**
      * @post
      */
     public function edit()
     {
         //....
     }
```

Now the router would check using reflection if the action allowed POST requests.

For REST style routing the action could be defined in the controllers class phpdoc.

```
/**
 * @post edit
 * @patch edit
 * @delete delete
 * @get index
 */
class Documents extends AppController {
    public function edit() { /* .. */ }
    public function delete() { /* .. */ }
    public function index() { /* .. */ }
}
```

This is just an idea I've been thinking about.

**Comment by thinkingmedia** [comment]
Never mind. Sorry, I think the above is a plugin idea.

**Comment by markstory** [comment]
> Actually, don't you think the current method of doing this is a bit hacky? Shouldn't the HTTP method be a separate parameter rather than in the array? 

Isn't it also part of how the route is matched? The 2nd argument are the fixed route parameters. I think the HTTP method is a reasonable inclusion there.

**Comment by JayPHP** [comment]
@thinkingmedia Logic in the routes isn't hidden. It should probably be the first place a developer should look when trying to understand the code of a project. I think logic in annotations is a lot more hidden than routes. Also, you wouldn't need to check against the request in the controller, because this is already done in routes.

@markstory I thought the second argument is just for action after the route is matched, am I mistaken? If I am, I would support separating these arguments so that there's a clear separation between match and action, but that's probably just a personal preference

**Comment by markstory** [comment]
@JayPHP The second parameter for a route defines any of the route defaults. You can include keys like 'controller', 'plugin', 'prefix', or any application specific routing data there as well, which is also why the `_method`  key is there.
