### ISSUE TITLE
Catching exceptions thrown by table methods in a controller does not work using PHP7

### ISSUE THREAD

**Issue by deanoj** [cakephp/cakephp#9398]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2
* Platform and Target: Apache 2.4. PHPv5.6.23 (windows 10) and PHPv7.0.8 (ubuntu 16)

### What you did
Running under PHP 5.6.x, I could catch an exception thrown from a table method in my controller code and handle it as expected. However, using PHP7, I cannot catch this exception anymore, and execution stops with an uncaught exception warning.

I refactored my code so the table method returned null, and created a private method in my controller like this:

    private function throwSomething()
    {
        $this->loadModel('Commons.CoreConfigs');
        $value = $this->CoreConfigs->getValue(WEBALIZER_URL_KEY_NAME);
        if (is_null($value)) {
            throw new CoreConfigKeyNotFoundException('not found');
        }
        return $value;
    }

Try/catch block:

        try {
            //$configs->getValue(WEBALIZER_URL_KEY_NAME); // if exception thrown from getValue method - I cannot catch it!!
            $this->throwSomething(); // exception thrown here is caught and handled by either the throwable catch (PHP7) or the exception catch (PHP5.6)
        } catch (\Throwable $e) {
            $this->log('Webalizer config key not found', LogLevel::WARNING);
            $this->Flash->error('Throwable caught');
        } catch (CoreConfigKeyNotFoundException $e) {
            $this->log('Webalizer config key not found', LogLevel::WARNING);
            $this->Flash->error('Exception caught');
        }

The above code worked exactly as expected, the exception was caught. So this issue only seems to occur when throwing the exception from the table method itself.

### Expected Behavior
Exception should be caught and handled as it is running under PHP 5.6

### Actual Behavior
Exception not caught and handled under PHP7. PHP5.6 works fine.

**Comment by lorenzo** [comment]
CakePHP cannot interfere with a language feature. I suggest you verify that you are trying to catch the right exception.

**Comment by ADmad** [comment]
Make sure you have proper `use` statements in all files which are using `CoreConfigKeyNotFoundException`.

**Comment by thinkingmedia** [comment]
Do not catch `Throwable` as that is an exception type in PHP7. It will catch both `Error` and `Exception` objects. So catching `CoreConfigKeyNotFoundException` will never happen.

Just remove the catch above it completely. Do not interfere with fatal errors. That will give you same behavior of PHP 5.6.

Leave catching of base `Error` types to the CakePHP framework.

**Comment by deanoj** [comment]
Thanks for the feedback.

I should have mentioned that I was using a VM to run my application under PHP7, and I'm starting to think that has something to do with the issue I am seeing... 

Having now setup the application on a physical machine running PHP7 - thing are now working as I expect! I'm going to dig into this more over the weekend, and I will update with my findings here.

**Comment by thinkingmedia** [comment]
I don't think a VM would matter.

I was trying to explain that the example would never catch `CoreConfigKeyNotFoundException` since `Throwable` was a greedy catch.

Here is an example of what I mean.

http://sandbox.onlinephpfunctions.com/code/90742a5c7543be3333537f4fd70b4b4485011a9f

**Comment by deanoj** [comment]
@thinkingmedia Yes I understand what you mean, and have removed the catch of throwable. I agree it should not matter whether I use a VM or not - but I am seeing what I am seeing.. I'll update here if I figure out what is going on. thanks.
