### ISSUE TITLE
JSON datetime ISO 8601 format in find ()

### ISSUE THREAD

**Issue by maxlio** [cakephp/cakephp#9402]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3 

### What you did
when I call find on a model and add an alias to created field as following:
```
$this->Photos->find('all', [
                            'conditions' => [
                                'related_id' => $brand['id'],
                                'type' => 'brand'
                            ],
                            'fields' => [
                                'title',
                                'text',
                                'imageUrl' => 'url',
                                "time"=> "created"
                            ]]);
```
time value is not formated as ISO 8601 in JSON serialization.
if I removed the alias "time" the created field is formatted correctly to ISO 8601 format by default.

### Expected Behavior
the create date/time field  with alies should return it in ISO 8601 datetime format.

**Comment by markstory** [comment]
As a workaround when you alias complex fields you need to declare the types you'd like returned into the type map.

```php
$query->selectTypeMap()->types(['time' => 'time'])
```

The ORM can infer type information for column names in the schema, but not for columns that are aliased/defined with custom functions.

I think inferring types for simple aliases should be doable.

**Comment by lorenzo** [comment]
@markstory given how simple it is to tell a query the type of a custom column, I'd rather not infer it magically

**Comment by markstory** [comment]
@lorenzo I don't think it is a significant effort to do type inference on simple aliased columns. I was only thinking of inferring types for columns that are defined in the table schema.

**Comment by lorenzo** [comment]
@markstory funny enough, I just realise I use the aliasing to avoid the casting in some cases!

**Comment by markstory** [comment]
@lorenzo Interesting, so we'd have another situation where fixing one problem would create another.

**Comment by lorenzo** [comment]
yeah, but admittedly, my usage is a hack.

**Comment by markstory** [comment]
Ok, I'll put together a pull request for the aliasing I had in mind. We can see how offensive it is.

**Comment by markstory** [comment]
Pull request up now.

**Comment by maxlio** [comment]
Thank you 💯
