### ISSUE TITLE
Add dot notation Validation rules errorField

### ISSUE THREAD

**Issue by martonmiklos** [cakephp/cakephp#9403]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.2
* Platform and Target: Ubuntu 14.04 MySQL

I have the following table configuration:

Items HasMany ItemsBom

ItemsBom BelongsTo Items (Items)
ItemsBom BelongsTo ChildItems (Items)

In the Items edit form I would like to also edit the ItemsBom too.

To do so I have generated the following form piece:

```php
echo $this->Form->Input('items_bom.0.id', ['type' => 'hidden']);
echo $this->Form->Input('items_bom.0.item_id', ['type' => 'hidden']);
echo $this->Form->Input('items_bom.0.child_item_id', ['type' => 'hidden']);
echo $this->Form->Input('items_bom.0.child_item.partnumber');
```

This is handy beacuse I pull the ChildItems in the controller and the items_bom.0.child_item.name input displays it's name well. 
(That input has an ajax completer which will set the 'items_bom.0.child_item_id', but it does not matter in my problem.)

I would like to avoid the creating of ItemsBom with the same item_id and child_item_id to avoid recursion.
I can do it by adding the following rule to my ItemsBom:

```php
$preventBoMRecursion = function($entity) {
    if ($entity->item_id == $entity->child_item_id) {
        return false;
    }
    return true;
};

$rules->add(
    $preventBoMRecursion,
    [
        'errorField' => 'child_item.partnumber',
        'message' => __("Cannot add the same part to the BoM")
    ]
);
```

As you can see from the 'errorField' I would like to display the error at the items_bom.0.child_item.partnumber, but currently this is not supported. 

I have added some code to the RuleInvoker::__invoke to travel through the ItemsBom entity to find the child_item, but that entity is an array not an Entity in my case.

I could make the child_item to be entity by adding the ItemsBom.ChildItems to the patchEntity in my Controller:
```php
$item = $this->Items->patchEntity($item, $this->request->data, ['associated' => ['ItemsBom', 'ItemsBom.ChildItems']]);
```
but in this case my rule on the ItemsBom will not run. 

The child_item appears as an Entity in between the original properties because I am pulling the ChildItems as an associated in the controller. 
I could add my error string in the RuleInvoker to there, but that would require some work on the EntityContext's error related methods.

Any help would be appericiated!

**Comment by markstory** [comment]
Why is `child_item` an array, and not an Entity? If you can get that association to be an Entity, one option might be to set the error in your nested entity from inside your rule.

```php
$preventBoMRecursion = function($entity) {
    if ($entity->item_id == $entity->child_item_id) {
        $entity->child_item->error(['partnumber', 'Error message');
        return false;
    }
    return true;
};
```

**Comment by martonmiklos** [comment]
I can get the child_item to be an Entity if I patch my $item in the following manner:
`$item = $this->Items->patchEntity($item, $this->request->data, ['associated' => ['ItemsBom', 'ItemsBom.ChildItems']]);`

But in this case the ItemsBom's rules did not get called.

**Comment by martonmiklos** [comment]
Ah nevermind, I am over too many trials. The rules got called as it should.

Here is the final solution:
`        $preventBoMRecursion = function($entity) {
            if ($entity->item_id == $entity->child_item_id) {
                $entity->child_item->errors('partnumber');
                return false;
            }
            return true;
        };
        
        $rules->add(
            $preventBoMRecursion,
            [
                'errorField' => 'child_item.partnumber',
                'message' => __("Nem lehet ugyanazt a cikket betenni a BoM-ba is!")
            ]
        );`
Thanks Mark again for your help! I deeply appericiate it!

**Comment by markstory** [comment]
Closing as you've found a solution.
