### ISSUE TITLE
RFC: Tab safe re-login with proper referrer passing

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9405]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: any

### What you did
Session invalidates (timeout, browser restart, ...) and all logged in windows redirect to login.
Afterwards the last one goes to the actual referrer of that tab, all others go back to the login redirect instead, losing the previous pages.

### Expected Behavior
All tabs should go back to the URL it was before being logged out for re-login.

### Possible fix
Usually frameworks handle this not with session (not tab safe!), but with query string.
So upon login the current URL should be passed into the query string as `redirect` or `referer` key:  `?referer=/...`.
Then, after successful redirect it will just use that query string if available.

The alternative would be to use a hidden input field to pass it through (because it also has to work with invalidating form, so direct usage of referrer is a no go), but I do not think that is necessary.

What do you think? Is the referer query string a viable option? It will also make it more transparent and state-less.

**Comment by dereuromark** [comment]
This is the branch I tested it with: https://github.com/cakephp/cakephp/compare/3.next-login-referer
It works so far.
Feel free to add commits.

**Comment by markstory** [comment]
Redirect URL in query strings are OK. However, you should not accept the host to be in the query string argument and the code as you have it now has an [unvalidated redirect](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet).

**Comment by dereuromark** [comment]
@markstory What kind of validation do you have in mind?
I added sth in https://github.com/cakephp/cakephp/compare/3.next...3.next-login-referer#diff-9f16e0a89d8fab0c6f686f0ca64ac94bR758

**Comment by markstory** [comment]
Moving discussion to the pull request.
