### ISSUE TITLE
Add option to findChildren() allowing user to include record of given $id

### ISSUE THREAD

**Issue by chey** [cakephp/cakephp#9406]
- [X] enhancement

Add option to findChildren() that allows user to keep the Entity of the requested $id instead of discarding it.

See discussion from today (Sep 4th from 15:48 to 17:19 EST) in #cakephp IRC or in Slack (I think it's there too). Talked with graziel and admad about it.

Discussion: http://irc.cakephp.org/logs/link/3926878#message3926888

Edit: Adding link to discussion.

**Comment by markstory** [comment]
Slack links are not a good way to preserve a requested feature. Our slack group has a very limited history window. Could you expand on what you want here?

**Comment by chey** [comment]
`
$id = 1;
$descendants = $categories->find('children', ['for' => $id]);
`

**Comment by chey** [comment]
I left the link to the IRC discussion only if you needed some context.
`
$id = 1;
$descendants = $categories->find('children', ['for' => $id, 'includeParent' => true]);
`
In this example, I would like to see an option to include Entity $id = 1 in the result set as well..stacked at the top. Which would be the parent. I made up an option name in the example.

Currently only the children of $id are in the result set.

I haven't tested it but I think it's simply a matter of adding a **>=** sign in the findChildren() method in place of the **>** sign.

**Comment by lorenzo** [comment]
Pro tip @chey 

```php
$nice = collection([$entity])->append($table->find('children', ['for' => $entity->id]));
```

**Comment by chey** [comment]
@lorenzo 
That is a decent enough work around for one case...but if I also stack the find('threaded') I would expect the first item in the result to have a 'children' property. If I supply an $id of 1 to the 'for' option like so:

    $entities = $table->find('children', ['for' => $entity->id, 'includeParent' => true])->find('threaded'); // again, includeParent is a made up option

...I'm expecting the output to be something like this. Note that the first $entity is that which has primaryKey of 1. The rest of the entities are under the 'children' property of itself.
```
{
    "entities": [
        {
            "id": 1,
            "children": [
                {
                    "id": 2,
                    "children": []
                },
                {
                    "id": 3,
                    "children": []
                },
                {
                    "id": 4,
                    "children": []
                },
                {
                    "id": 5,
                    "children": [
                        {
                            "id": 6
                        },
                        {
                            "id": 7
                        },
                        {
                            "id": 8
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by lorenzo** [comment]
Something like this?

```php
$nice = collection([$entity])
    ->append($table->find('children', ['for' => $entity->id]))
    ->nest('id', 'parent_id');
```

**Comment by chey** [comment]
@lorenzo 
Possibly. I don't see the find('threaded') there though.

**Comment by lorenzo** [comment]
@chey threaded is `nest()` that's what the finder calls internally

**Comment by ADmad** [comment]
Closing as the required result is achievable with explicit use of collections.
