### ISSUE TITLE
3.3 Regression: Streamed request bodys are broken

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#9408]
With 3.3.3 and the new middleware streamed bodys seems to be broken, throwing a `RuntimeException` with "**Callback streams cannot rewind position**"

Code:
```php
$this->response->type('png');
$this->response->body(function () use ($imageClipped) {
    imagepng($imageClipped);
});
/*ob_start();
imagepng($imageClipped);
$this->response->body(ob_get_clean());*/
return $this->response;
```
This code worked before 3.3 but is now broken. The commented code is a easy work-around, but for me this looks like a regression. My app was updated from 3.2 using the code from the app-template.

Backtrace:
⟩ Cake\Http\Server->emit ROOT/webroot/index.php, line 37
⟩ Zend\Diactoros\Response\SapiStreamEmitter->emit CORE/src/Http/Server.php, line 107
⟩ Zend\Diactoros\Response\SapiStreamEmitter->emitBody ROOT/vendor/zendframework/zend-diactoros/src/Response/SapiStreamEmitter.php, line 47
⟩ Zend\Diactoros\CallbackStream->rewind ROOT/vendor/zendframework/zend-diactoros/src/Response/SapiStreamEmitter.php, line 59

**Comment by markstory** [comment]
I'll take a look.

**Comment by markstory** [comment]
Closing as a pull request is open now to fix the issue via shims until I hear back from zend-framework.
