### ISSUE TITLE
Additional override parameter for hiddenProperties() and virtualProperties()

### ISSUE THREAD

**Issue by steefaan** [cakephp/cakephp#9416]
Sometimes it would be useful if `hiddenProperties()` and `virtualProperties()` would have an extra parameter `$override` like `contain()` for tables has.

**Comment by markstory** [comment]
Instead of boolean flags I would prefer separate methods.

**Comment by xaphalanx** [comment]
I believe this milestone was already reached went setVirtual() and setHidden() was added. They both except a merge argument -- by default overwrite. Am I missing something?
