### ISSUE TITLE
Multi-Checkbox Required Attribute Missing

### ISSUE THREAD

**Issue by kwentworth** [cakephp/cakephp#9417]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: LATEST

### What you did
Made a mutli-checkbox input required

### Expected Behavior
required="required" on each checkbox input

### Actual Behavior
no required="required"

### Proposed Fix
Line 159 in: src/View/Widgest/MultiCheckboxWidget.php

Add line for required:
$checkbox['required'] = $data['required'];

**Comment by kwentworth** [comment]
3.3.1

**Comment by markstory** [comment]
What code did you use to create your checkboxes?

**Comment by kwentworth** [comment]
Something like this:

$fieldOptions['multiple'] = 'checkbox';
$fieldOptions['type'] = 'multicheckbox';   // I had to put this here to get it to use the mutli templates

echo $this->Form->input('field'.$question->id, $fieldOptions);

**Comment by ADmad** [comment]
How is having all values required practically useful? You won't be able to submit the form without checking every checkbox.

**Comment by kwentworth** [comment]
I want the group of checkboxes required (at least one checked).  How is this achieved?

**Comment by markstory** [comment]
@kwentworth You need to use server side validation for that.

**Comment by kwentworth** [comment]
Ok. I get it.  I now see what I need to do.  I will add a class to the containing div and the js to validate client side and then do the server side stuff.  Thanks for everything.  I really love all the changes in 3.

**Comment by ADmad** [comment]
Closing as nothing requires to be done here.
