### ISSUE TITLE
Cache bug HasOne relation saved for diffrent table

### ISSUE THREAD

**Issue by LaaHudra** [cakephp/cakephp#9418]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3.
* Platform and Target: PHP 5.5.12 /MySQL / Windows / Wamp

### What you did
I am trying to save HasOne Relation.
CustomersTable.php

```php

    $this->hasOne( 'BillingAddresses', [ 
            'className' => 'CustomerContacts',
            'foreignKey' => 'customer_id',
            'conditions' => [ 
                'BillingAddresses.type' => 1 
            ],
            'dependent' => true 
        ] );
        
        $this->hasMany( 'ServiceAddresses', [ 
            'className' => 'CustomerContacts',
            'foreignKey' => 'customer_id',
            'conditions' => [ 
                'ServiceAddresses.type' => 2 
            ],
            'dependent' => true 
        ] );
```

MasterJobsTable.php

```php
    $this->hasOne( 'BillingAddresses', [ 
            'className' => 'MasterJobContacts',
            'foreignKey' => 'master_job_id',
            'conditions' => [ 
                'BillingAddresses.type' => 1 
            ],
            'dependent' => true 
        ] );
        
        $this->hasOne( 'ServiceAddresses', [ 
            'className' => 'MasterJobContacts',
            'foreignKey' => 'master_job_id',
            'conditions' => [ 
                'ServiceAddresses.type' => 2 
            ],
            'dependent' => true 
        ] );
```

### Expected Behavior
MasterJobs-> BillingAddresses and ServiceAddresses should be saved in "MasterJobContacts" table.

### Actual Behavior
MasterJobs -> ServiceAddresses  saved correctly but MasterJobs-> BillingAddresses saves in CustomerContacts table. When I change relation Key from BillingAddresses to JobBillingAddresses and I update save array then it works correctly. It looks like somehow it cached relation name from other model

**Comment by lorenzo** [comment]
It is not clear from the description how the issue can be reproduced. Can you add some code of what you are doing and the end result?

**Comment by lorenzo** [comment]
@LaaHudra ah, I think I see the problem. It is not allowed to repeat alias names with different configuration. We are working on having a exception being thrown for that case.

In particular, you cannot bind the name `BillingAddresses` to 2 different tables. Alias names must be unique in your application.

**Comment by markstory** [comment]
Once the associations are unique, if you want to have the same property populated on both entities you can use the `propertyName` configuration option to change the property name.

Closing as you'll need to update your association names.
