### ISSUE TITLE
Not all records in DB table listed or accessible

### ISSUE THREAD

**Issue by KieranYo** [cakephp/cakephp#9419]
This is a
* [x] bug
* CakePHP Version: 3.3.2
* Platform and Target: Ubuntu running inside vagrant instance, nginx, mysql

### What you did
Trying to list all records in database table by browsing to http://**host**/members

### Expected Behavior
List all records in database table.

### Actual Behavior
When I browse to the index page for the model it only returns only 194 records

Here is the code. You can see I've tried to increase the `maxLimit` to no avail.

```
    public function index()
    {
        $this->paginate = [
            'contain' => ['Addresses'],
            'maxLimit' => 100000,
            'limit' => 10
        ];
        $members = $this->paginate($this->Members);

        $this->set(compact('members'));
        $this->set('_serialize', ['members']);
    }
```

The view also returns a `Record not found in table "members"` error when the ID is higher than a certain ID even though the record clearly exists in the database.
```
    public function view($id = null)
    {
        $member = $this->Members->get($id, […
```

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by markstory** [comment]
Have you attempted to run the generated queries against MySQL? Do you get different results? Are you perhaps hitting transfer limits between MySQL and PHP, or timeouts in your webserver?

**Comment by KieranYo** [comment]
I'm not entirely sure how this could be reproduced to be honest.

Ok so your comment about generated queries clicked with me, I ran the generated queries against the DB and it turned out to be bad data and a rogue `joinType`.

![image](https://cloud.githubusercontent.com/assets/410142/18283273/57913b00-745c-11e6-8dbe-ff4e49d6fea6.png)

Plus the inner join it was performing on `Addresses` was on a column with `0` in instead of `null` thus not finding the record.

I should have got the rubber duck out! Thanks for your help @markstory as always.
