### ISSUE TITLE
Ajax request handling doesn't automatically change template sub directory

### ISSUE THREAD

**Issue by danielvy** [cakephp/cakephp#9422]
- [x] enhancement
- CakePHP Version:3.3.3
- Platform and Target: Apache, MySql, Ajax requests using jquery
### What you did
- Added RequestHandlerComponent
- Added 'ajax' extension to routes
- Created a template in path `.../Templates/<Controller>/ajax/<action>.ctp`
- Issued ajax request using jquery 
### Expected Behavior
- RequestHandlerComponent detects ajax request
- Layout should be changed to ajax.ctp
- Template subdirectory changed to include "ajax" sub directory (similar to json requests)
### Actual Behavior
- RequestHandlerComponent detected ajax request
- Layout was changed to ajax.ctp
- Template subdirectory was not modified, it still looks for the template in `.../Templates/<Controller>/<action>.ctp`

I think that Ajax request handling should behave consitently with other request types (e.g. json).

If this is the correct behavior (if possible, please say why) then the documentation should be modified to clarify that ajax requests behave differently because currently the docs imply that ajax templates adjusted automatically.

From [http://book.cakephp.org/3.0/en/controllers/components/request-handling.html](url):

> By default RequestHandler will automatically detect AJAX requests based on the HTTP-X-Requested-With header that many JavaScript libraries use. When used in conjunction with Cake\Routing\Router::extensions(), RequestHandler will automatically switch the layout and template files to those that match the requested type.

**Comment by dereuromark** [comment]
AJAX is not an extension type, AJAX is protocol type. JSON/XML/etc are the actual types here that would be used for the sub folder.
If you want the behavior you explained, you could look into my [Ajax](https://github.com/dereuromark/cakephp-ajax) plugin which does something like that.

**Comment by danielvy** [comment]
Yes, I understand that conceptually, ajax and json are different things. But practically, in CakePHP they are treated similarly and on the same level as json/xml:

- `is("ajax")/is("json")` return true respectively to the request type
- RequestHandlerComponent sets `RequestHandler->ext `to "ajax"
- The layout is automatically changed to `ajax.ctp`

Only the automatic template path behavior is different (contrary to the docs).

**Comment by markstory** [comment]
Requiring 'ajax' templates to be in a sub-directory will cause existing applications to break. This incompatibility means we can't realistically implement the suggested changes. While this behavior is inconsistent with other media types the current behavior has existed for many years and I feel like updating the documentation is the right choice here.

You can however, do what you want by extending/implementing an `AjaxView` in your application. A custom view class can change the `subDir` as necessary.

**Comment by ADmad** [comment]
Closing as this can be easily implemented at app level using using custom view class.
