### ISSUE TITLE
link from the docs to the api when using See [xxxx]

### ISSUE THREAD

**Issue by danielzzz** [cakephp/cakephp#9427]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
I am reading: http://book.cakephp.org/3.0/en/core-libraries/email.html
In the section Configuration Profiles for example there are lines like this one:

'from': Email or array of sender. See Email::from()

### Expected Behavior
I would like all instances of "See XXX" to link to the actual source or other section of the docs

### Actual Behavior
No link :(

thanks

**Comment by dereuromark** [comment]
If this is a doc issue only, it should be reported in https://github.com/cakephp/docs/issues
This is a bug tracker for the CakePHP framework source code.

**Comment by danielzzz** [comment]
ok, sorry about that
