### ISSUE TITLE
Add support for PHP Process Manager (PPM)

### ISSUE THREAD

**Issue by chey** [cakephp/cakephp#9430]
- [x] enhancement

More info here
https://github.com/php-pm/php-pm
- Performance boost up to 15x
- Integrated load balancer.
- Hot-Code reload (when PHP files change).
- Static file serving for easy development procedures.

Allows you to run application as standalone app without the need for a web server. It's faster running an app standalone than it is letting the web server load all the files each time.

I understand that this probably isn't something that can happen overnight but I would like to see this on the roadmap at least :+1:

**Comment by lorenzo** [comment]
Maybe when it is marked as production ready, it looks intersting

**Comment by dakota** [comment]
It shouldn't be too difficult to get it working with 3.3+ using the [PSR-7 bridge](https://github.com/php-pm/php-pm-psr7)

**Comment by markstory** [comment]
@dakota I'm hoping to have CakePHP completely PSR7 native by 3.5 which will help as well.

**Comment by dakota** [comment]
@markstory let me know how I can help 🙂

**Comment by ADmad** [comment]
There's a plugin now which provides PHPPM support https://github.com/CakeDC/cakephp-phppm. Adding support for it in core itself doesn't seem necessary right now.
