### ISSUE TITLE
Error: Cannot use 'String' as class name as it is reserved	

### ISSUE THREAD

**Issue by pchelailya** [cakephp/cakephp#9433]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.x
* Platform and Target: PHP 7.0.10 (cli) (built: Aug 31 2016 18:17:07) ( NTS )

### What you did
migrate 5.6->7.0

### Expected Behavior
Should I explain this?

### Actual Behavior
Error: Cannot use 'String' as class name as it is reserved	
File: /var/www/vendor/cakephp/cakephp/lib/Cake/Utility/String.php	
Line: 26

**Comment by dereuromark** [comment]
Please see http://book.cakephp.org/2.0/en/appendices/2-7-migration-guide.html#utility
You must use CakeText from here on if you want PHP7 compatability.
