### ISSUE TITLE
define getter and setter in entity save wrong data

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#9438]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x

as far as i know getter (or accessor) should be used to apply some transformation to the entity data when you need to show the data.
in cakephp the getter function is called when the entity is saved to the DB too, so the real data inside the entity will be formatted from the getter function.

i think that this behavior is wrong, and if i want to modify the data that will be saved when i patch an entity, i have to use setter and not the getter function.

the simplest example (probably not the better example, because in this situation data types are better) is when i want to save a json to db, and i patch the entity with an array. the setter function transform the array in a json, and the getter function transform the json in array.
now, instead, the setter function transform the array in json, but the getter function, called before saving in the db, re-transform the json in array, throwing an sql error.

**Comment by lorenzo** [comment]
This is the way it is supposed to work. The getters should return the data that is meaningful for the whole application, including to the database. If you want to convert a value from and to the database, I suggest you use the `Type` classes.

Please refer to the [JsonType example in the docs](http://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-types) for more information.

Keep in mind that `JsonType` is already included in the core, so if that is the case you are looking forward to implement, then you can just use that.
