### ISSUE TITLE
testAction vars and contents returns same content when view cache is enabled

### ISSUE THREAD

**Issue by gemal** [cakephp/cakephp#9439]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.6
* Platform and Target: 

### What you did
if I in my unit tests have the following:
```
$result1 = $this->testAction($url, array('return' => 'vars', 'method' => 'GET'));
$result2 = $this->testAction($url, array('return' => 'contents', 'method' => 'GET'));
```
and URL have view caching enabled
then `$result2 === $result1`
which should not be true

### Expected Behavior
since 2 different things are requestsed "vars" vs "contents" 2 different things should be returned

### Actual Behavior
same thing returned

**Comment by markstory** [comment]
Why not disable view caching in your tests?

**Comment by dereuromark** [comment]
Do we want to have TestSuite clean out the caching here?
Sounds like this is a side effect of View cache activation that one might have to manually resolve.

**Comment by markstory** [comment]
@dereuromark Couldn't applications using view caching disable it as necessary? The issue here is that view caching is doing what it should and that behavior is not wanted. Sounds like a situation where turning off view caching would be a good solution.

**Comment by dereuromark** [comment]
I agree

**Comment by ravage84** [comment]
I guess this should to be mentioned in the Testing section of the book, then.
