### ISSUE TITLE
Please Give Me A Nice Usermgmt Plugin for cakephp 3.x

### ISSUE THREAD

**Issue by itfamily2** [cakephp/cakephp#9440]
Please Give Me A Nice Usermgmt Plugin for cakephp 3.2.x
* [x] enhancement

**Comment by itfamily2** [comment]
Please Give Me A Nice Usermgmt Plugin for cakephp 3.x

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by inoas** [comment]
Maybe the default close message should include a link to awesome cakephp @admad
