### ISSUE TITLE
Core\Configure\FileConfigTrait.php

### ISSUE THREAD

**Issue by vttn** [cakephp/cakephp#9442]
* [x] enhancement

* CakePHP Version: 3.3
* Platform and Target: Apache2, Ubuntu.

### What you did
I have an application that is in directory /var/www/website.com/
In this directory I also have a file under folder common/config/app.php
app.php holds common configuration that I would like to be loaded by cake.

In config/bootsrap.php
I updated the code

`Configure::config ( 'default', new PhpConfig () );`
`Configure::load ( ROOT . DS . 'common/config/app', 'default', false );`
`Configure::load ( 'app', 'default', true );`

### Expected Behavior
I expect cakephp to load my config from /var/www/website.com/common/config/app.php

### Actual Behavior
Cake assumes that I want to load a plugin config since my path has a dot in it.
Please see Core\Configure\FileConfigTrait.php 

### Work-around
    if (strpos($key, '..') !== false) {
            throw new Exception('Cannot load/dump configuration files with ../ in them.');
        }
        
        $fileReal = $key . $this->_extension;
        if (is_file(realpath($fileReal))) {
            return realpath($fileReal);
        }

        list($plugin, $key) = pluginSplit($key);

        if ($plugin) {
            $file = Plugin::configPath($plugin) . $key;
        } else {
            $file = $this->_path . $key;
        }

        $file .= $this->_extension;

        if (!$checkExists || is_file($file)) {
            return $file;
        }

        if (is_file(realpath($file))) {
            return realpath($file);
        }

        throw new Exception(sprintf('Could not load configuration file: %s', $file));

**Comment by ADmad** [comment]
You should create a new custom config and use that to load files from non default folder.

```php
Configure::config('custom', new PhpConfg('path/to/common/folder');`
Configure::load('app', 'custom');
```
