### ISSUE TITLE
maxLimit is not working for pagination.

### ISSUE THREAD

**Issue by aavrug** [cakephp/cakephp#9446]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Apache, MySQL, Ubuntu.

### What you did
```
    public $paginate = [
        'limit' => 1,
        'maxLimit' => 2
    ];
```
Also tried with
``` $users = $this->paginate($this->Users, ['limit' => 1, 'maxLimit' => 2]); ```

### Expected Behavior
The expected behavior is per page there will be one row and maximum row that will be fetched is 2.

### Actual Behavior
I am getting 3 rows.

**Comment by chinpei215** [comment]
Couldn't reproduce. What SQL is executed?

**Comment by aavrug** [comment]
```
SELECT 
  Users.id AS `Users__id`, 
  Users.first_name AS `Users__first_name`, 
  Users.last_name AS `Users__last_name`, 
  Users.email AS `Users__email`, 
  Users.password AS `Users__password`, 
  Users.dob AS `Users__dob`, 
  Users.created AS `Users__created`, 
  Users.modified AS `Users__modified` 
FROM 
  users Users 
LIMIT 
  1 OFFSET 0
```

**Comment by chinpei215** [comment]
> LIMIT 1 OFFSET 0

So, it seems working as expected. If you call `debug($users)`, how many records do you see in the array? Also, please make sure that you are handling `$users` correctly in the loop.

**Comment by aavrug** [comment]
After debug I am getting single result in "items" keyword. But in the index.ctp just running the loop on the users and getting three pages each one having one result.

**Comment by chinpei215** [comment]
> getting three pages each one having one result.

Sounds like an expected behavior. If three users are stored in your database, you would get three pages, because you are limiting results to 1 per page. I think there has been a misunderstanding about the maxLimit option.

http://book.cakephp.org/3.0/en/controllers/components/pagination.html#limit-the-maximum-number-of-rows-that-can-be-fetched

> If the request’s limit param is greater than this value, it will be reduced to the maxLimit value.

![users](https://cloud.githubusercontent.com/assets/7399393/18426649/2cdde592-78fe-11e6-9e78-73151cf2cdbc.png)

![users2](https://cloud.githubusercontent.com/assets/7399393/18426651/318e34ca-78fe-11e6-80e9-31409a8375c7.png)

**Comment by aavrug** [comment]
As per my understanding the maxLimit is for fetching required number of rows. e.g If I have 20 rows in the DB and I just want to fetch only 10 rows then I have to use ```maxLimit => 10``` and the rest 10 result that will be never in the frontend.

**Comment by dereuromark** [comment]
No that is not what that Option does. It is a security Option for the Limit Option. So you can't manipulate Limit further then necessary to avoid ddos.

**Comment by aavrug** [comment]
@dereuromark ok thanks for the explanation. So, is there any parameter for fetching exact number of rows from DB like LIMIT in MySQL.

**Comment by dereuromark** [comment]
You could invent a maxPage Option if you want to. But other than that i don't think there is much room for improvement for Core here.

**Comment by aavrug** [comment]
Probably I am confused but as much I remember in CakePHP-2 there was the option Limit which was for fetching total number of rows from DB.

**Comment by dereuromark** [comment]
For normal queries yes. Always has been like this.
But for pagination there is no such need as the results are already cut into small pieces.

**Comment by aavrug** [comment]
So I think the alternate way is first query with find and put a limit with that then the fetched result can be sync with pagination.

**Comment by lorenzo** [comment]
Let's please continue the conversation in slack or IRC.
