### ISSUE TITLE
Bug in tests: duplicate keys

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9447]
We have a few tests where the data providers actually  less results, as the array keys overwrite each other:

            'limit = 0' => [
                ['limit' => 0, 'maxLimit' => 100],
                1,
            ],
            'limit = 0' => [
                ['limit' => 0, 'maxLimit' => 0],
                1,
            ],
            'limit = null' => [
                ['limit' => null, 'maxLimit' => 0],
                1,
            ],
            'bad input, results in 1' => [
                ['limit' => null, 'maxLimit' => null],
                1,
            ],
            'bad input, results in 1' => [
                ['limit' => false, 'maxLimit' => false],
                1,
            ],

PaginatorComponentTest

We should rewrite them, or remove the duplicates (which are dead code right now).

**Comment by markstory** [comment]
I quickly scanned the other data providers and didn't see any other effected tests.
