### ISSUE TITLE
Have FormHelper::unlockField call FormHelper::_secureFieldName

### ISSUE THREAD

**Issue by lilHermit** [cakephp/cakephp#9448]
I'm creating an Input tag without using `FormHelper::input` but need to use array naming convention so the data in correct when it gets to the controller. So I set `$name='field[something]';` then `name="<?= $name ?>"` and then call `$this->Form->unlockField($name);` whoever this doesn't convert to the dot notation used by `SecurityComponent`

Alternatively add a $options array where it can be enabled or make `FormHelper::_secureFieldName` public

**Comment by markstory** [comment]
You should call the methods with the correct parameters. The parameters are already normalized in the majority of scenarios so I don't think it is reasonable to add overhead for what is an infrequent use-case.

Is there a reason you're not using the standalone input methods like `checkbox()` `text()`, `radio()` and such?

**Comment by lilHermit** [comment]
Essentially templating reasons, if I knew it would have caused such an issue I would have changed templates either on FormHelper::create or FormHelper::input etc. You wouldn't consider adding

```$this->Form->unlockField($name, ['normaliseValue' => true])```

and default to false, so there is no extra overhead as standard?

I understand if not.

Regards

Scott

**Comment by josegonzalez** [comment]
I think we're going to close this. The proper way to handle custom templating issues is to use the built-in support on `FormHelper::create()`, `FormHelper::control()`, etc.

I believe if someone wants to subclass the FormHelper to add this sort of functionality, that would work as well.

Thanks for the initial issue though, and apologies on the long wait for a response.
