### ISSUE TITLE
#9368 is not backwards compatible

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#9452]
See #9015 and #9368.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.7
* Platform and Target: N/A

### What you did
Run all our tests using:
```
Console/cake test app All --stderr;
```

### Expected Behavior
All tests to pass as they did in `2.8.6`

### Actual Behavior
Lot's of:
```
Integrity constraint violation: 1062 Duplicate entry '<X>' for key 'PRIMARY'
```

Should #9368 be compatible? If not, how can we adjust our tests?

**Comment by dereuromark** [comment]
Do you have any special kind of test setup?
Some more details would be good here.

**Comment by tersmitten** [comment]
Not that we're aware of :-( Setting [$dropTables](https://github.com/cakephp/cakephp/blob/2.4.5/lib/Cake/TestSuite/CakeTestCase.php#L53) to `false` fixes the problem

**Comment by markstory** [comment]
I'll revert the problematic pull request.

**Comment by markstory** [comment]
Closing as a revert is open now.

**Comment by tersmitten** [comment]
Thanks @markstory
