### ISSUE TITLE
Session saving in endless loop when autoRegenerate = true

### ISSUE THREAD

**Issue by hekep** [cakephp/cakephp#9453]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Cakephp 2.8, and PHP 7.10, Apahce server, MysQL 5.X

This is related to https://github.com/cakephp/cakephp/issues/1964

I have in core.php

```php
Configure::write('Session', array(
    'timeout' => 60 * 24 * 30 * 12, 
    'cookieTimeout' =>60 * 24 * 30 * 12,year
    'cookie' => 'blaa',
    'defaults' => 'database',
    'autoRegenerate' => true
));
```

Apache died with Segment Fault.

After installing Xdebug, it displayed error message:

Fatal Error: Maximum function nesting level of 256 reached, aborting! in 
.... /lib/Cake/Model/Datasource/DbSource.php on line 2791

Xdebug also displays many other "Maximum function nesting level of 256 reached, aborting! in ..."  various places of Cakephp ..

Sample of loop:

	AuthComponent::user( )	.../AppController.php:189
       CakeSession::check( )	.../AuthComponent.php:668
	CakeSession::start( )	.../CakeSession.php:233
	CakeSession::_checkValid( )	.../CakeSession.php:206
	CakeSession::renew( )	.../CakeSession.php:731
        session_write_close ( )	.../CakeSession.php:771
	DatabaseSession->write( )	.../CakeSession.php:771
	Session->save( )	.../DatabaseSession.php:130
	AuthComponent::user( )	.../Session.php:51
	CakeSession::check( )	.../AuthComponent.php:668
	CakeSession::start( )	.../CakeSession.php:233
        CakeSession::_checkValid( )	.../CakeSession.php:206
        CakeSession::renew( )	.../CakeSession.php:731
        session_write_close ( )	.../CakeSession.php:771
        DatabaseSession->write( )	.../CakeSession.php:771
        Session->save( )	.../DatabaseSession.php:130
        AuthComponent::user( )	.../Session.php:51
        CakeSession::check( )	.../AuthComponent.php:668
        CakeSession::start( )	.../CakeSession.php:233
        CakeSession::_checkValid( )	.../CakeSession.php:206
        CakeSession::renew( )	.../CakeSession.php:731
        session_write_close ( )	.../CakeSession.php:771

Hoping to use  'autoRegenerate' as in old php5.x

No idea how fix it other than disable it,   'autoRegenerate' => false .

**Comment by hekep** [comment]
Xdebug screenshot
![cakephp_autorenegenrate](https://cloud.githubusercontent.com/assets/1901788/18473474/cce8c6c0-79c5-11e6-8cae-d9f996c578b8.png)

**Comment by markstory** [comment]
Why is AuthComponent being called from Session->save()?  Does your session model have callbacks?

**Comment by hekep** [comment]
Hi,

CakePHP version, 2.8.6

My session model save() is overrriden.

     function save($data = null, $validate = true, $fieldList = array()) {

        if (AuthComponent::user('id')) {
            $data['user_id'] = AuthComponent::user('id');
        } else {
            $data['user_id'] = null;
        }
        return parent::save($data, $validate, $fieldList);
    }

My Session table has user_id column.  Client model hasMany User enitities.  User hasMany Session entities.   If Client entity gets disabled, then User entities belonging to that Client get disabled and Sessions should get wiped out.

This save()  works in PHP 5.x. It ( save() ) works in PHP 7 until session id has to be regenerated. 

Is there something that can be done in framework level, or should I just search alternative? Disable session_regenerate_id()? 

Also PHP7 session_regenerate_id() works differently.

**Comment by hekep** [comment]
Never mind. I changed my code. How ever as for feedback it would be nice, if framework would handle session user id between abstraction layers for the developers, e.g. Model::$sessionUserID.

**Comment by hekep** [comment]
https://github.com/cakephp/cakephp/compare/2.next...hekep:patch-1

**Comment by markstory** [comment]
Your changes introduces an infinite loop, so its expected that one would occur.

I don't think your patch is something that we can accept. It introduces additional global variables, and relies on behavior that has been deprecated/removed in 3.x.

Closing this issue as the source of the issue (the infinite loop) is something you've introduced in your application code.
