### ISSUE TITLE
'associated'=>false in patchEntity/newEntity

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9457]
This is a (multiple allowed):
[ ] bug
[ ] enhancement
[x ] feature-discussion (RFC)
cake 3.3.x

### What you did
'associated'=>false in patchEntity/newEntity for ignore extra data in marshal time 
similar to 'associated'=>false option in `table::save()`

### Actual Behavior
`Cannot marshal data for "0" association. It is not associated with {table name}`

**Comment by lorenzo** [comment]
I think you can pass an empty array instead. Can you verify if that is possible?

**Comment by saeideng** [comment]
yes that is possible
but extra data will not ignore(not remove from entity)

**Comment by markstory** [comment]
I don't know if we need two ways to do the same thing.

**Comment by inoas** [comment]
Wouldn't it stop possible validation errors?

Do you want me to add '=> []' as an example on how to disable nested validations to the docs?

**Comment by markstory** [comment]
> Do you want me to add '=> []' as an example on how to disable nested validations to the docs?

Sure if you have the time.

**Comment by saeideng** [comment]
I think before this(3.2) we could use boolean instead of empty array
