### ISSUE TITLE
Marsaller/ORM loads associated data in reverse order

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#9460]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: PHP 5.6, PostgreSQL 9.4

### What you did
I have a model associated with the Users table through belongsToMany relation
I posted a request with that content:
```
team[_ids][0]=1
team[_ids][1]=2
```
Code in request handler:
```php
$entity = $this->Test->newEntity($this->request->data, [
    'associated' => [
        'Team' => ['onlyIds' => true]
    ]
]);

debug($entity);
```

### Expected Behavior
ORM loaded associated data in passed order:
```
object(App\Model\Entity\Test) {

	'team' => [
		(int) 0 => object(App\Model\Entity\User) {

			'id' => (int) 1,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Team'
		
		},
		(int) 1 => object(App\Model\Entity\User) {

			'id' => (int) 2,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Team'
		
		}
	],
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'team' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Test'

}
```

### Actual Behavior
ORM loaded associated data in reverse order:
```
object(App\Model\Entity\Test) {

	'team' => [
		(int) 0 => object(App\Model\Entity\User) {

			'id' => (int) 2,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Team'
		
		},
		(int) 1 => object(App\Model\Entity\User) {

			'id' => (int) 1,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Team'
		
		}
	],
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'team' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Test'

}
```

**Comment by lorenzo** [comment]
There is no guarantee about the order in the marshaller as you have realized, and this is unlikely to change given that insertion order does not mean much in SQL.

A better alternative is to insert with a sort property that you can rely on.

**Comment by markstory** [comment]
Why does the order matter?

**Comment by codercms** [comment]
@markstory because i use this to display validation errors for hasMany/belongsToMany associations in API which responds in JSON. So i need to know element index.

**Comment by markstory** [comment]
Ok. You will want to look at the belongs to many code in the marshaller, as that is likely where the issue is.

**Comment by ndm2** [comment]
I'm wondering, how would there be any validation errors for an `_ids` array? Do you patch the retrieved data afterwards? If so, even if the order was as in the given list of IDs, the data could have holes if not all of the given IDs exist.

**Comment by codercms** [comment]
@ndm2 hm, you're right i should to rewrite my errors generation mechanism.
I close this issue, because there is no more problem with Marshaller/ORM.
