### ISSUE TITLE
3.x Feature: Validation boolean() should allow to force checks against true xor false

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9463]
This is a (multiple allowed):
* [x] enhancement

* CakePHP Version: 3.3

### What you did
https://github.com/cakephp/cakephp/pull/9461

### Expected Behavior
Easy way to check booleans to be specifically true or false.

### Actual Behavior
inList is not really want one wants. [custom, '[1]'] may be to specific (not truthy but string '1').

### Suggestion
`boolean()` should take either true/false or an option flag as an additional argument to test not only if it is boolish but specifically if it is truthy/falsey (where truthy/falsey must be something our ORM understands, e.g. not "on" or "off").

@chinpei215 good?

Ref: https://github.com/cakephp/cakephp/pull/9461#r79122695

This is probably low priority, so if no one picks it up until then, once I find time I will implement it including unit tests. It should be a very small change.

**Comment by chinpei215** [comment]
I noticed that `Validator` has a shortcut method `boolean` for `Validation::boolean()`  in 3.x. The signature of `Validator::boolean()` is:
```php
public function boolean($field, $message = null, $when = null)
```
So it might be difficult to add a new option to validation method without breaking backward compatibility in 3.x :cry:

Though, it would be worth to discuss what we should do in such cases.

**Comment by inoas** [comment]
We can simple add `isTrue()` and `isFalse()`? As an option we could let the user specify if they only want a subset of 0/false/'0'?

**Comment by chinpei215** [comment]
I think we can do it.

**Comment by inoas** [comment]
Okay, as soon as I find some spare time on the weekend I can take care, in case no one is faster.

**Comment by inoas** [comment]
Closing as PR is open.
