### ISSUE TITLE
Datasource access in constructor of mocked model requires default datasource

### ISSUE THREAD

**Issue by mvdriel** [cakephp/cakephp#9466]
Datasource access in constructor of mocked model requires a (valid) default datasource

Example constructur:

``` php
class AppModel extends Model {

    public function __construct($id = false, $table = null, $ds = null) {
        parent::__construct($id, $table, $ds);
        $this->getDataSource()->cacheMethods = false;
    }
}
```

Example test:

``` php
$this->loadFixtures('User');
$this->getMockForModel('User');
```

Resulting error:

```
MissingDatasourceConfigException: The datasource configuration "default" was not found in database.php
```

Relates to #8225

**Comment by markstory** [comment]
How is this not the same as #8225?

**Comment by mvdriel** [comment]
The use case (and the error) is the same, but this time using CakePHP 2.8.8. @markstory Is it better to reopen the other issue?

**Comment by markstory** [comment]
I'm not sure this is fixable. At this point in the model's life it is still using the `'default'` data source. If that happens to be undefined it should rightly fail.

**Comment by mvdriel** [comment]
@markstory Is there a better place to disable cacheMethods (application-wide)?

**Comment by markstory** [comment]
@mvdriel You can do it as a dispatch filter.

**Comment by markstory** [comment]
Closing as this can be solved in application code.
