### ISSUE TITLE
expired session cookie after removing csrf token

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#9467]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cake 3.3.3

### What you did
expired cookie session after close/ re-open browser 
i first login in site then closed browser and see again site
after open that site ,see i still logged in site but in response header cake sent expire cookie header then i refresh page, and i see am logout from site
this is happend after upgrade from cake 3.2 to cake 3.3.3
also if i loggen again until i not closed browser ,my cookie not expire and work well
```
//
app.php
    'Session' => [
        'defaults' => 'cake',
        'timeout'=>60*24*365,
         'ini' => [
        'session.cookie_lifetime' => 60*60*24*365,
    	]
    ],
//app controller
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
		$this->loadComponent('Security');
		 $this->loadComponent('Csrf');
		 //$this->request->session()->renew();

		        $this->loadComponent('Auth', [
..
'storage'=>['className' => 'Session', 'key' => 'Auth.User']
]);

```

**Comment by saeideng** [comment]
I did a new test
replace webroot/index.php with Previous Version (dispatcher)
after replace,my  app working well

**Comment by markstory** [comment]
I'm still not really clear on how to reproduce the issue you're having. Your cookies appear to be valid for 1 year, how are you testing the expiration?

When session cookie is initially set, is the cookie timeout not set correctly?

**Comment by saeideng** [comment]
Cake returned expired time 1970/or 1971 (year) in response header just for first request (for this app) after re-open browser

**Comment by saeideng** [comment]
I check cookie from response header

**Comment by markstory** [comment]
Ok, I'm not clear on what sequence of steps/requests I should be taking when trying to reproduce this issue though.

**Comment by saeideng** [comment]
1)login in site //cake response make cookie with expire time=1 year
2)close all browser
3)enter site name (localhost/sitename)//in this time i can see 
  a)expire cookie via cake response header (trace by browser tools)
 b) i am "logged in" and session vars in debug_kit have "Auth.user" key by user info 
4)re-fresh page/or open another page // now i logged out and new cookie key generate (traced by cookie key in response header)

**Comment by markstory** [comment]
Thanks @saeideng I'll give that a try.

**Comment by saeideng** [comment]
@markstory
I did another test
but in this time, i removed csrfToken cookie from browser and got a test (without closing browser)

1)removed csrfToken cookie
and again 
```
//at this time i can see

a)expire cookie via cake response header (trace by browser tools)
CAKEPHP=key; Expires=Fri, 01 Jan 1971 00:00:00 GMT; Path=/sitename/; HttpOnly
b) i am "logged in" and session vars in debug_kit have "Auth.user" key include user info 
```
Happened just by new middleware (when using new webroot/index.php)

**Comment by markstory** [comment]
I'm not sure if I did this correctly. But I did the following

1. Visit http://cake3.localhost/bookmarks
2. After logging in, response contains:
```
Set-Cookie:CAKEPHP=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly
Set-Cookie:CAKEPHP=jcj8ghs9t0h3hjljrn5gdio063; expires=Sun, 24-Sep-2017 02:48:11 GMT; Max-Age=31536000; path=/; HttpOnly
```
3. Close browser
4. Reopen browser
5. Visit http://cake3.localhost/bookmarks
6. Still logged in as cookies last 1 year.

Did you delete the session storage upon closing the browser? If I delete the session files, I'm not able to reproduce your issue where the session stays active either.

**Comment by saeideng** [comment]
my session key exist even after closing browser
But when i visit the site after
1)open browser
Or
2)after remove csrfToken cookie (without closing browser)
i still still logged in but at this time, response header was just includes deleted cookie 
So,in next request it was contain new session and csrftoken cooke(in response header)

That means delete and regenerate cookie happent in seperate requests

**Comment by saeideng** [comment]
I think this is related to renew() session and csrf component

**Comment by markstory** [comment]
So the sequence is

1. Login
2. Delete CSRF token from browser.
3. Navigate to another page, and you get logged out?

**Comment by saeideng** [comment]
Yes

**Comment by saeideng** [comment]
I still logged in for first visit after deleting
But for 2th request i am logged out

**Comment by markstory** [comment]
Ok, I'll give that a try.

**Comment by saeideng** [comment]
thanks
i did another test
```
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
		$this->loadComponent('Security');
		 $this->loadComponent('Csrf');
		 //$this->request->session()->renew();

		        $this->loadComponent('Auth', [
...
]);
        $expiry = new Time(0);
        $this->response->cookie([
            'name' => 'name',
            'value' => 'samplevalue',
            'expire' => $expiry->format('U'),
            'path' => $this->request->webroot,
            'secure' => false,
            'httpOnly' => false,
        ]);

```
i see every time (without any removing or closing broswer)
```

name=samplevalue; Path=/sitename/
CAKEPHP=new-value-every-time; Expires=Fri, 01 Jan 1971 00:00:00 GMT; Path=/sitename/; HttpOnly

```
this is normally behavior?

**Comment by saeideng** [comment]
this behavior just happend in(with) new webroot/index.php

**Comment by markstory** [comment]
I don't think setting a cookie should rotate the session. I'll see if I can reproduce that issue.

**Comment by markstory** [comment]
I wasn't able to reproduce the session rotation when setting a cookie. Are you able to reproduce this issue in a fresh application? If so could you put the files changed from the default install into a gist so I can try them out?

**Comment by saeideng** [comment]
I will try to that

**Comment by markstory** [comment]
I was finally able to reproduce this issue. It has nothing to do with removing the CSRF cookie. Instead it requires:

1. A response cookie to be set.
2. The session id to be rotated.

When these 2 things are true, the new session id cookie is not set correctly, and has the incorrect expiry date that you saw. I was also able to confirm that #9517 will fix this issue.

**Comment by markstory** [comment]
You can try that branch out locally by using `composer require "cakephp/cakephp:dev-response-emitter as 3.3.5"`

**Comment by saeideng** [comment]
I will test it
thanks @markstory

**Comment by saeideng** [comment]
thanks @markstory 
i did some tests
reported problems resoled now
thanks
