### ISSUE TITLE
any_value() returns zero

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#9468]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: Apache, Mysql (all update to date)

### What you did
        $q = $this->Sessions->RunTimes->find();
        $q->select(['r_id','duration' => $q->func()->any_value(['duration'])])
            ->group(['r_id'])->toArray();

### Expected Behavior
The r_id, and duration values to be returned

### Actual Behavior
any_value returns zero instead of the value of duration. 

I've checked the query created by Cake in MySQL. It was correct. The result of any_value is appears to be the problem.

**Comment by lorenzo** [comment]
What's the generated query?

**Comment by notoriousturtle** [comment]
I'm not sure how to print the query in this case. When I do echo $q, it prints nothing. 

However, if I change the code to:
'duration'=>'any_value(duration)'

It returns the expected value and not zero.

**Comment by lorenzo** [comment]
You can look in debugkit after the query is executed

**Comment by lorenzo** [comment]
The problem is that function values are always treated as a value and not as a column name. You can do this instead:

    any_value(['duration' => 'identifier'])
