### ISSUE TITLE
Exceptions in production mode not logged (debug=0)

### ISSUE THREAD

**Issue by pmacko** [cakephp/cakephp#9469]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3.

### What you did
- debug = 0
- database exception in code
- error log is empty

### Expected Behavior
exception must be logged

Line:
https://github.com/cakephp/cakephp/blob/master/src/Error/Middleware/ErrorHandlerMiddleware.php#L71

insert Log::error($exception); ?

**Comment by markstory** [comment]
Looks like I totally missed logging. I'll get that fixed 😊

**Comment by markstory** [comment]
Pull request up now.

**Comment by pmacko** [comment]
👍 thanks
