### ISSUE TITLE
Redirecting outside subdirectory after upgrading to 3.3.3

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#9470]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3.
* Platform and Target: PHP5.5.12, MySQL 5.6.17, Apache/2.4.9.

### What you did
My app was running on CakePHP 3.2.13 in a subdirectory called cake, I have put a condition on routes.php file to check if the app installed or not and if not installed redirect to installation wizard using this code
```Router::redirect('/**', ['controller' => 'Install', 'action' => 'index'], ['status' => 307])```
and it was redircting to http://localhost/**cake**/install/index but after upgrading to CakePHP 3.3.3 it is redirecting outside the subdirectory like this http://localhost/install/index

### Expected Behavior
It should redirect within the subdirectory like this http://localhost/**cake**/install/index

**Comment by markstory** [comment]
Is that redirect route all that someone would need to reproduce this issue?

**Comment by BassemN** [comment]
To reproduce this issue, add the below code after the `use` statments into `routes.php` file
```php
if (!file_exists(CONFIG.'configuration.php')) {
    Router::connect('/install/:action', ['controller' => 'Install']);
    if (strpos(env('REQUEST_URI'), 'install') === false) {
        return Router::redirect('/**', ['controller' => 'Install', 'action' => 'index'], ['status' => 307]);
    }
}
```
The above code will check if `configuration.php` is not exsiting then redirect to install controller.

**Comment by markstory** [comment]
Thanks @BassemN I'll see what I can find.

**Comment by BassemN** [comment]
Also `Router::getRequest()` returns `null` when I use it into app `routes.php`

**Comment by markstory** [comment]
I was able to reproduce this and will get a fix together.

**Comment by markstory** [comment]
@BassemN Yes, that will continue to not return a request until later in the dispatch cycle. If you need rely on that timing behaviour you will need to continue using the `RoutingFilter` and `ControllerFactoryFilter` instead of the `RoutingMiddleware`.

**Comment by BassemN** [comment]
@markstory Thanks for your time.
Great and what about the redirect issue?

**Comment by markstory** [comment]
@BassemN I'll have a fix up for the redirect issue later today.

**Comment by markstory** [comment]
Pull request up now.
