### ISSUE TITLE
Implement a friendlier ResponseEmitter

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#9472]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Since the release of the PSR7 http stack there have been a few issues, and many support requests in the slack/irc channel about awkward issues when people use `debug()`, `var_dump()` or similar functions in their controllers/models. People either see warnings about 'headers sent', or truncated responses (#9435).

Because of these issues, I'm proposing we implement our own ResponseEmitter that has the following properties when in debug mode:

* Sent headers are logged, *and* an error is displayed.
* The Content-Length header is *never* sent, so truncation never occurs.

When in 'production mode' the following would be true:

* Sent headers are only logged.
* Content-Length header is never sent.

Once we have some consensus on these two changes I'll get a new Emitter implemented.

**Comment by ndm2** [comment]
Would the no `Content-Length` also affect file responses?

**Comment by markstory** [comment]
@ndm2 That's tricky, if we don't set it for files we'll run into client timeout issues. Perhaps we should be setting content-length for non-(html, json, css, xml) types?

**Comment by lorenzo** [comment]
Is it true that we need to send the content length for file?

**Comment by lorenzo** [comment]
The proposed changes seem reasonable to me, I'm not sure about the need to log the headers in production mode, though

**Comment by josegonzalez** [comment]
@lorenzo I would log the headers in production, as at least then anyone tailing the logs can be notified of when there is an error (and that they should fix it).

**Comment by markstory** [comment]
@lorenzo I wanted to log headers, as not sending headers can cause a suite of problems around sessions, cookies, and content-types.

**Comment by ndm2** [comment]
@lorenzo I'm not 100% sure, I was just wondering since the request class currently explicitly does that.  I don't really know how all the different web servers handle this in the various situations, if they all send the content length automatically, if their behavior maybe is affected by other headers like for example `Content-Range` being present, if they handle compression properly, etc...

**Comment by lorenzo** [comment]
I the great majority of setups, the webserver buffers the response from php. So there is little advantage in sending the content-length, as we learned in the transition form cake 2 form cake 3

**Comment by ndm2** [comment]
@lorenzo I see... guess it's probably fine then :)

**Comment by markstory** [comment]
@lorenzo I remember we had a ton of pain around Content-Length :cry:

**Comment by lorenzo** [comment]
I think it is fine leving it out, as long as we remeber to call http://php.net/manual/en/function.fastcgi-finish-request.php

**Comment by markstory** [comment]
Closing as a pull request is open now.
