### ISSUE TITLE
(Automatically) Convert empty association properties for `SAVE_REPLACE` compatibility?

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#9474]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)

---

Let's say we have a form that supports adding/removing `hasMany`/`belongsToMany` associated records that are using the `SAVE_REPLACE` save strategy.

``` php
$this->Form->input('parent_field');
$this->Form->input('association.0.field');
$this->Form->input('association.1.field');
$this->Form->input('association.2.field');
// ...
```

When removing for example `association.2.field`, the saving process would delete the record accordingly. When however removing all of them, so that we'd be left with only

``` php
$this->Form->input('parent_field');
```

then the association property wouldn't be affected anymore at all, and nothing would change, ie the records wouldn't be deleted.

To workaround that one have to do something like adding a hidden field with the name of the association property, and check that before marshalling and replace it with an empty array accordingly, like for example

``` php
$this->Form->input('parent_field');
$this->Form->hidden('association', ['value' => '']);
$this->Form->input('association.0.field');
$this->Form->input('association.1.field');
$this->Form->input('association.2.field');
// ...
```

``` php
public function beforeMarshal(Event $event, \ArrayObject $data, \ArrayObject $options)
{
    if (isset($data['association']) && $data['association'] === '') {
        $data['association'] = [];
    }
}
```

That way all records would be deleted properly when none of the `association.*.field` inputs would be submitted.

I'm wondering if this is something that may fit in the core? Maybe as an optional behavior that can be enabled via the `associated` option?

**Comment by markstory** [comment]
Making an empty string replace the association with an empty list sounds like a reasonable default behavior to me.

**Comment by lorenzo** [comment]
Could this be used in a malicious way? Or could it be a surprise for users to discover that there is a way to delete all associated records from a form?

**Comment by markstory** [comment]
@lorenzo Good point. It could be used for bad purposes.

**Comment by ndm2** [comment]
I was a little worried too at first, hence the suggestion to make this optional, but the more I think about it, the less concerned I am. By default users are currently able to delete all but one record, so I'd say that one record more doesn't really make a difference.

I'd think that if developers use the replace save strategy, then they usually want exactly that to be possible. If they don't want users to be able to remove associated records via a form depending on the current context, then they would have to implement additional measures anyways, like switching to the append strategy, or better yet the other way around, enable the replace strategy only where explicitly required.

**Comment by markstory** [comment]
@ndm2 It sounds like the kind of change that would have to go into `3.x.0` as to not surprise people.

**Comment by lorenzo** [comment]
You have a point in that today all records but one can be removed

**Comment by lorenzo** [comment]
If your were presented with an external API you need to use, and it required require sending an empty string instead of an array, like in every other case, what would you think of such API?

**Comment by inoas** [comment]
Can't this be fixed at the controller/table level with an option flag?

**Comment by markstory** [comment]
@lorenzo In an API context couldn't you push an empty list?

**Comment by ndm2** [comment]
@lorenzo I wouldn't like that, but as @markstory mentioned, an API may be be able to receive data in a different format that can properly represent empty list structures, like for example JSON. In a form data context there is no way to send an empty list, so I'd say an empty string is the next best thing.

**Comment by inoas** [comment]
... or maybe `'false'`?

**Comment by ndm2** [comment]
Looks a little akward as it's very different to how to usually pass empty values in a form context, and I could easily see people pass the value in an unquoted fashion by accident, but generally something like that would work too of course.

I don't think there's any perfect solution, so I'd personally tend to simply use whatever is the least error prone, most intuitive, and easiest to remember.

**Comment by inoas** [comment]
I bet ['value' => false] will render as "value = "0" (untested). If it renders like "value" => "false" then that's okay...

**Comment by markstory** [comment]
`['value' => false]` will turn into `value=''` in HTML.

**Comment by lorenzo** [comment]
@markstory can you put an empty list using form-data as a content type?

**Comment by markstory** [comment]
@lorenzo I don't think that is possible `article[comments]=` makes a string while `article[comments][]=` makes a list with 1 element of '' in it.

**Comment by lorenzo** [comment]
I see, then accepting the empty string makes sense

**Comment by ndm2** [comment]
Finally a little time to get some stuff off of my todo list... I had a a look into this again, and after [**implementing it in the marshaller**](https://github.com/ndm2/cakephp/commit/80d8a360cc2cb41498a7132bed61fd55a2ea2e38), I've noticed that `BelongsToMany` associations already have that behavior [**built in on association level**](https://github.com/cakephp/cakephp/blob/3.1.0/src/ORM/Association/BelongsToMany.php#L449-L455) :expressionless:

So I guess similar could simply go into `HasMany` as well (instead of doing this in the marshaller)?

@lorenzo @markstory (just in case, not sure if anyone's still subscribed after felt 12 1/2 years)

**Comment by markstory** [comment]
Making HasMany and BelongsToMany association classes work similarly sounds like a good idea to me.

**Comment by ndm2** [comment]
Closing as the enhancement has been merged.
