### ISSUE TITLE
Upload files with utf8 names

### ISSUE THREAD

**Issue by AliFarhoudi** [cakephp/cakephp#9476]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.6.0.
- Platform and Target: OS: Fedora 23, Web Server: Httpd (apache), DB: mysql  Ver 15.1 Distrib 10.0.25-MariaDB.
### What you did

Uploaded a file with Persian (utf-8) filename. I had set a validation rule for mimetype.
### Expected Behavior

To check mimetype and upload file.
### Actual Behavior

I got "Can not determine the mimetype" exception. I just traced the problem and figured out that Cake is using basename function to get filename and since this function has problem with utf8 filenames ([according to this](https://bugs.php.net/bug.php?id=62119)) and the filename is utf8 then the filename that this function returns is not correct.
I didn't find any issue related.

**Comment by markstory** [comment]
From the related PHP issue this looks like an issue in PHP itself. What methods are you calling that basename is being a problem? Taking a look at Validation::mimeType() and File::mime() the problem wasn't immediately apparent.

**Comment by AliFarhoudi** [comment]
I have uploaded a file with utf9 name (my filename: نام-فارسی.pdf). For this kind of filenames, the function ```basename``` returns wrong filename and it causes to raise mimetype exception. Wrong filename is being assigned in constructor method of File class (name attribute of File class).

**Comment by saeideng** [comment]
You set any validator?

**Comment by saeideng** [comment]
I personaly can upload image with persian name

**Comment by ADmad** [comment]
> Wrong filename is being assigned in constructor method of File class (name attribute of File class).

So it seems the problem has nothing to with mimetype validator but `File` class. Mimetype validator doesn't use `File` class, it's some other code in your app which does.

**Comment by AliFarhoudi** [comment]
@saeideng Yes i have put mimetype validation with some other validation rules. I'm getting mimetype error because the first validation rule that needs filename is mimetype validation.
@ADmad Yes, There is no problem with mimetype validator. Mimetype validator just needs filename and when tries to get filename, it has been set wrong, then mimetype validator can't validate mimetype and raises exception.

**Comment by AliFarhoudi** [comment]
@saeideng Try to check filenames with multiple words having spaces or dashes between words. And check if in your CakePHP version File class constructor is using basename function.

**Comment by ADmad** [comment]
> Mimetype validator just needs filename and when tries to get filename, it has been set wrong, then mimetype validator can't validate mimetype and raises exception.

Umm no, Validator::mimeType() doesn't need filename/basename. It just uses the full temp file path available in `tmp_name` key of file upload array. The use of `File` class isn't involved.

Please provided the exact error you are getting with stack trace.

**Comment by ADmad** [comment]
Sorry I just realized this issue is for 2.x not 3.x. I was checking `Validator::mimeType()` of 3.x.

**Comment by saeideng** [comment]
I am sorry, i checked it in 3.x version,like ADmad :)

**Comment by AliFarhoudi** [comment]
I have temporarily changed the code as below:
```php
public function __construct($path, $create = false, $mode = 0755) {
    $this->Folder = new Folder(dirname($path), $create, $mode);
    if (!is_dir($path)) {
-       $this->name = basename($path);
+       $tempPath = str_replace(array('/', '\\'), DS, $path);
+       $this->name = end(explode(DS, $tempPath));
    }
    $this->pwd();
    $create && !$this->exists() && $this->safe($path) && $this->create();
}
```

**Comment by markstory** [comment]
Closing as this doesn't seem to be an issue that anyone is interested in fixing.

**Comment by saeideng** [comment]
basename() has an issue by file name 
https://3v4l.org/mBeCM
used in cake 3.x https://github.com/cakephp/cakephp/blob/master/src/Filesystem/File.php#L87

**Comment by saeideng** [comment]
return true result when using http://php.net/manual/en/splfileinfo.getfilename.php instead of basename()
https://3v4l.org/nBtc9

**Comment by ndm2** [comment]
@saeideng It should be noted though that for paths that point to the the root, ie `/file.ext`, the `getFilename()` method includes the leading slash, ie it returns `/file.ext` instead of `file.ext`... you gotta love PHP :)

**Comment by saeideng** [comment]
because `getBasename()` and `basename()` returned invalid result 

i saying we can using another method like `getFilename()` or mix of methods 
> for paths that point to the the root, ie /file.ext, the getFilename() method includes the leading slash
> ie it returns /file.ext instead of file.ext

very simple :)
`str_replace(array('/', '\\'),"" , getFilename());`

>  you gotta love PHP :)

But it does not love me :smile:

**Comment by ndm2** [comment]
Sure, just wanted to mention it so that it doesn't get unnoticed, as it could easily turn into a security issue :)
