### ISSUE TITLE
3.x Feature: Add an initialize method to the email class

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#9477]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

It would be great if there were an `initialize()` method to the end of `Cake\Email\Email::__construct()`. Similar to other classes in the framework, this could be used to subclass the Email class in a more natural way.

Note: This is based on my previous subclassing of the Email class, which I continued to use as an alternative to Mailers.

**Comment by ADmad** [comment]
Before the introducing of `Mailer` class an `Email::initialize()` would have been helpful. Not to sure it's required now. Your mailer class methods can contain all initialization code.

**Comment by burzum** [comment]
Could you provide an example of an use case @josegonzalez? Because I think @ADmad is right.

**Comment by josegonzalez** [comment]
It's basically an alternative to the Mailer class. I personally don't like having to put all my emails into a mailer, so I subclass it and move on. To me, it's kind of like the old way where we had all the exceptions in an exceptions.php file. Just feels wrong.

**Comment by burzum** [comment]
I think this is pretty opinionated, I personally like the mailers. Feels like a better separation to me.

**Comment by lorenzo** [comment]
I don't think the Email class is really meant for extension, the less we encourage that the better for future us.

**Comment by dereuromark** [comment]
I also extend the Email class for many years now to have it customized, using the constructor so far always sufficed. I don't think an initialize method is needed here, as well.

**Comment by ravage84** [comment]
@dereuromark what kind of extension did you put in there? Could you do it differently now with the Mailer class? Just curious.

**Comment by dereuromark** [comment]
No, it is very low level stuff. But either way no such extra method is necessary here.
So closing as works-for-me then?

**Comment by josegonzalez** [comment]
Sounds like a bunch of no answers, so closing :)
