### ISSUE TITLE
SQL log does not contain binded values, only placeholders

### ISSUE THREAD

**Issue by mirorac** [cakephp/cakephp#9485]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: -

### What you did
Screenshot of SQL log from debug panel - one request. Screenshot _is not_ result of merging two different screenshots.
![screen shot 2016-09-19 at 17 58 05](https://cloud.githubusercontent.com/assets/8964866/18667931/ed085228-7f32-11e6-9a82-abc03743c343.png)

### Expected Behavior
I expect to see actual values (exact sql sent to DB) as it is inside green circle. 

### Actual Behavior
Some queries have unbound placeholders logged as it is inside red circle. I think only queries made by associations (contain clause in query builder) are logged with placeholders.

**Comment by lorenzo** [comment]
How can we reproduce this problem?

**Comment by mirorac** [comment]
I am sorry, I do not know what is the root of problem. I have tried to solve it but no results so far.

I have application which has been built on version 3.2.13 and I noticed this issue right after updating to 3.3.3.

So there are no placeholders in your sql logs in any applications?

**Comment by lorenzo** [comment]
No, problem... finding the root of the problem is not what I'm asking for, only a way I can test this myself. I have a couple cake 3 applications and haven't seen this so far, so I was hoping for some guidance on how to trigger this error.

**Comment by markstory** [comment]
This issue was moved to cakephp/debug_kit#445
