### ISSUE TITLE
 cakephp 3 auth not working

### ISSUE THREAD

**Issue by Gathuth** [cakephp/cakephp#9490]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3
* Platform and Target: wamp , windows 10 
### What you did
Try to auth login form 

### Expected Behavior
return redirect url 

### Actual Behavior
get error 

 1
down vote
favorite
1
	

i try to use Auth in cakephp3 but i got return error

i am sure that data correct

For note password field size is 255 char

sql log return only user_mail filed where

  phi_members.user_mail = 'gathuth@gmail.com' 

why it not include user_password !! and row result is 1

PhimembersController.php

```
<?PHP

namespace App\Controller;
use App\Controller\AppController;
use Cake\Event\Event;

Class PhimembersController  extends AppController {

    var $name="Phi_members";

    public $components = array('RequestHandler');


    public function index()
    {
echo'Hello World';
    }
    public function show() {

        $this->set('phi_members',$this->Phi_members->find('all'));
    }

public function initialize()
{   

    parent::initialize();
    $this->loadComponent('Flash');
    $this->loadComponent('Auth', [
                'loginRedirect' => [
                'action' => 'index'] , 'loginAction' => [
            'action' => 'login'
        ],
        'authenticate' => [
            'Form' => [
                'userModel' => 'phi_members',
                'fields' => ['username' => 'user_mail','password' => 'user_password']
            ]
        ]
    ]);
}

public function beforeFilter(Event $event)
    {
        $this->Auth->allow(['index', 'login']);
    }

        public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
   }
}

?>
 ```
login.ctp

```
<h1><?= $this->Flash->render('auth') ?></h1>
<?= $this->Form->create(); ?>
    <fieldset>
        <legend><?= __('Please enter your username and password') ?></legend>
        <?= $this->Form->input('user_mail') ?>
                <?= $this->Form->input('user_password') ?>

    </fieldset>
<?= $this->Form->button(__('login')); ?>
<?= $this->Form->end() ?>

```
Any Help

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
