### ISSUE TITLE
Controller Test with mocked component fails after update from 3.2 to 3.3

### ISSUE THREAD

**Issue by davalb** [cakephp/cakephp#9491]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: Apache, Mysql

### What you did
Updated from cakephp 3.2.x to cakephp 3.3.3 and on of my Tests which contained a mocked component stopped passing. Here is the shortened, simplified code of this ControllerTest::
```
class CartsControllerTest extends IntegrationTestCase
{
    public function testResponsePage()
    {
        $this->post('/this/request/will/use/my/mocked/paycomponent');
    }

    public function controllerSpy($event, $controller = NULL){
        parent::controllerSpy($event);
        if (isset($this->_controller)) {
            $pay = $this->getMockBuilder('App\Controller\Component\PayCommponent')
                ->setMethods(['execute'])
                ->getMock();
            $this->_controller->Pay = $pay;
        }
    }
}
```
### Expected Behavior
I expect the Controller to use the mocked component in the request I am triggering. In Cakephp 3.2 this is the case

### Actual Behavior
In 3.3 the controller uses the real component and not the mocked one, which causes a call to a remote server.

**Comment by markstory** [comment]
Did you also update to use the new PSR7 Application class? I ask because it will help in reproducing your issue.

**Comment by davalb** [comment]
No, I did not update with the intention to use the PSR7 Application class. To be honest I am just reading up on the psr-7 related changes in cakephp 3.3. I don't yet see, how this could have something to do with this problem.

**Comment by markstory** [comment]
@davalb The internals of the IntegrationTestCase differ based on which Dispatcher is being used.

**Comment by markstory** [comment]
I'm not able to reproduce this issue just yet. The following tests passes without issue in the cakephp test suite.

```php
<?php
namespace Cake\Test\TestSuite;

use Cake\Controller\Component;
use Cake\Core\Configure;
use Cake\Routing\DispatcherFactory;
use Cake\Routing\Router;
use Cake\TestSuite\IntegrationTestCase;

/**
 * Integration test for controllerSpy regression.
 */
class ControllerSpyIntegrationTest extends IntegrationTestCase
{
    public function setUp()
    {
        parent::setUp();

        Configure::write('App.namespace', 'TestApp');
        Router::connect('/:controller/:action/*', [], ['routeClass' => 'InflectedRoute']);

        DispatcherFactory::clear();
        DispatcherFactory::add('Routing');
        DispatcherFactory::add('ControllerFactory');
        $this->useHttpServer(false);
    }

    public function testResponse()
    {
        $this->get('/posts/index');
        $this->assertResponseOk();
    }

    public function controllerSpy($event, $controller = null){
        parent::controllerSpy($event, $controller);
        $mock = $this->getMockBuilder('Cake\Controller\Component\FlashComponent')
            ->setMethods(['error'])
            ->disableOriginalConstructor()
            ->getMock();

        $mock->expects($this->once())->method('error');

        $this->_controller->Flash = $mock;
    }
}
```

Based on what you've said here I would have expected that test to fail.

**Comment by davalb** [comment]
It turns out what broke the test was, that I did not pass the controller variable to the parent's controllerSpy method here: `parent::controllerSpy($event);`
For some reason this did not matter in 3.2, but it does in 3.3. I didn't see this mistake until I compared my code with the test you posted above.
Sorry for taking up your time with this, @markstory and thanks a lot for the help!
