### ISSUE TITLE
Find query - float values precision

### ISSUE THREAD

**Issue by davo3** [cakephp/cakephp#9492]
* [x] bug

* CakePHP Version: 3.3.3
* Platform and Target: Debian 8.5, PHP 5.6.24, Apache/2.4.10, MySQL 5.6.26

I think this has the same reason as https://github.com/cakephp/cakephp/issues/9424

```
CREATE TABLE `my_table` (
  `id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` DOUBLE DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;


INSERT INTO `my_table` (`id`, `value`) 
VALUES
  (1, '-3888888.8888888885'),
  (2, '2857497.0166960536'),
  (3, '680180.8995997418') ;
```
and
```
	    $result = TableRegistry::get('MyTable')->find()->select(['value'])->all();
	    debug($result);die;
```

actual result
```
object(Cake\ORM\ResultSet) {

	'items' => [
		(int) 0 => object(Cake\ORM\Entity) {

			'value' => (float) -3888888.8888889,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'MyTable'
		
		},
		(int) 1 => object(Cake\ORM\Entity) {

			'value' => (float) 2857497.0166961,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'MyTable'
		
		},
		(int) 2 => object(Cake\ORM\Entity) {

			'value' => (float) 680180.89959974,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'MyTable'
		
		}
	]
}
```

So, the values are truncated/rounded.

Expected behavior is the exact values from `my_table`

**Comment by lorenzo** [comment]
@davo3 do you plan to do any math operations on those numbers using php? like `$field * 1000`?

If that is the case, then I suggest not using a `DOUBLE` column down to that precision, but always store your numbers with a maximum of `15` digits. This is how floats work in PHP, and most languages.

If you are not planning to do math operations on those fields, then you can map them as `string` in php using the `Type` classes as described in the book

**Comment by markstory** [comment]
This isn't the same as #9424. That issue was for 'decimal' columns not `double`. Floats lose precision that's just how they work. Closing as you should either use different column types, or re-map them as @lorenzo described.

**Comment by davo3** [comment]
@lorenzo , @markstory  thanks for your comments, I am feeding those results to third party lib, which is doing some math operations, however I just migrated the app from cake 2.x and back then(with v2) all values from db were returned as strings and it all worked fine, so I assume mapping by string, as suggested, should do the trick. thanks
