### ISSUE TITLE
MSSQL Error HY010 - Entity foreach loop breaks after saving a record

### ISSUE THREAD

**Issue by jjjapj** [cakephp/cakephp#9494]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3, also 3.1.5
* Platform and Target: Windows Server 2008 R2 Enterprise, Microsoft SQL Server 2008 R2

### What you did
A find() is called on the table, presenting a result set of entities (`$priceRows`). The entities are looped through, and some modifications are made on an entity in the loop. The entity is then `save()`d to update the database.
```
$pricesTable = TableRegistry::get('Prices');

$priceRows = $pricesTable
    ->find()
    ->where(['event_id' => $eventsQuery->id]);

foreach($priceRows as $query) {
    $query->comment = 'new value';
    $pricesTable->save($query);
}
```

### Expected Behavior
All loops of the `foreach` should continue even after one of the looped elements is `save()`d back to the database. This occurs without issue on MySQL.

### Actual Behavior
When using Microsoft SQL Server, the result set fails to iterate on the next loop after performing a save() operation on one of the found entities. The first entity does save properly and update the database, but it is impossible to continue the `foreach` loop afterwards. CakePHP stops execution and presents the following error:

Error: SQLSTATE[HY010]: [Microsoft][ODBC Driver 11 for SQL Server]Function sequence error

This error [appears to be related to](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/2c904a8a-76d4-4851-8ca6-4ef38312efe4/unexpected-odbc-error-hy010-function-sequence-error?forum=sqldataaccess) calling `SQLEndTrans()`, presumably when updating the record with `save()`, when there are still more `SQLFetch()` statements needed.

**Comment by markstory** [comment]
This sounds like a limitation of the SQLServer driver API. I'm not sure what we can do in CakePHP.

**Comment by markstory** [comment]
As per the comments on #9509, PDO does not allow us to have 2 open database resultsets at once. You can work around this limitation by calling `$query->all()->toArray()` which will fetch all the results into memory and close the open read cursor. This will allow you to update records.
