### ISSUE TITLE
2.x find('count') with DISTINCT field in array

### ISSUE THREAD

**Issue by xhs345** [cakephp/cakephp#9495]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9
* Platform and Target: MariaDB 10.1.17

### What you did
I tried to execute the following query:
```
$this->User->Cost->find('count', array(
    'fields' => array('DISTINCT user_id')
)));
```
From my understanding reading the manual about [find('count')](http://book.cakephp.org/2.0/en/models/retrieving-your-data.html#find-count) this should be possible.

### Expected Behavior
Query should be: `SELECT COUNT(DISTINCT user_id) [...]`

### Actual Behavior
Query I got was  `SELECT COUNT(*) [...]`
Fields value was ignored

**Comment by xhs345** [comment]
UPDATE: I was looking through the unit-tests and was noticing that it included a test for the DISTINCT case which was working (see: [here)](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Test/Case/Model/ModelReadTest.php#L7107).

I looks like the fields parameter is only used when using a string, but not when using an array. So this find works for me:
```
$this->set('user_fee_users', $this->User->Cost->find('count', array(
    'fields' => 'DISTINCT user_id'
)));
```

**Comment by lorenzo** [comment]
Yeah, that's the only way in cake 2 for adding `DISTINCT`, glad you figured it out :)
