### ISSUE TITLE
3.x - `Dispatcher.afterDispatch` event not being invoked on error

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#9496]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3

refs #8667

---

With the introduction of the `ActionDispatcher`, dispatcher filters are not going to receive the `Dispatcher.afterDispatch` event anymore in case an error occurs in the application.

While `ExceptionRenderer::_shutdown()` does dispatch the event, the `Dispatcher` has been changed so that filters are only being registered as listeners anymore inside of the `ActionDispatcher` object, ie when `Dispatcher::dispatch()` is being invoked.

```php
public function testAfterDispatchOnError()
{
	$filter = $this
		->getMockBuilder('Cake\Routing\DispatcherFilter')
		->setMethods(['afterDispatch'])
		->getMock();

	$filter
		->expects($this->at(0))
		->method('afterDispatch');

	\Cake\Routing\DispatcherFactory::add($filter);

	$instance = new \Cake\Error\ExceptionRenderer(new \Cake\Network\Exception\NotFoundException());
	$instance->render();

	\Cake\Routing\DispatcherFactory::clear();
}
```

**Comment by markstory** [comment]
I'm not sure the ExceptionRenderer should be triggering the event. Perhaps the ErrorHanderMiddleware should do that?

**Comment by ndm2** [comment]
For applications that are using the new middleware stack that would probably be a good place.

But as long as the stack isn't mandatory and dispatcher filters are only deprecated, backwards compatibility would be nice to have, ie the exception renderer will probably have to be kept involved in one way or another for the time being.

**Comment by markstory** [comment]
The Middleware stack is optional. Looking at ExceptionRenderer::_shutdown() the event dispatch is still present and in use. So I'm a bit confused as to how the event is not working anymore.

**Comment by ndm2** [comment]
Correct, the problem isn't that the exception renderer wouldn't be dispatch the event anymore, it still is doing that, the problem is that the filters/listeners do not get subscribed until `Dispatcher::dispatch()` is being invoked, which the exception render will of course not invoke.

Previously the filters/listeners have been registered in `Dispatcher::addFilter()`, so whenever an instance of `Dispatcher` has been created via `DispatcherFactory::create()`, the filters where subscribed as listeners, since the factory adds all the statically registered filters:

* https://github.com/cakephp/cakephp/blob/3.2.14/src/Routing/DispatcherFactory.php#L85
* https://github.com/cakephp/cakephp/blob/3.2.14/src/Routing/Dispatcher.php#L146

So dispatching the event on `$dispatcher` in the exception renderer invoked the filters/listeners properly.

With the action dispatcher introduced, `Dispatcher::addFilter()` does not subscribe the filters/listeners anymore, instead they are being subscribed in `ActionDispatcher::addFilter()`, and while the `ActionDispatcher` instance used by the `Dispatcher` class gets the `Dispatcher` instances event manager passed to it to subscribe the filters on, all this only happens when `Dispatcher::dispatch()` is being invoked.

* https://github.com/cakephp/cakephp/blob/3.3.3/src/Routing/Dispatcher.php#L78
* https://github.com/cakephp/cakephp/blob/3.3.3/src/Http/ActionDispatcher.php#L64
* https://github.com/cakephp/cakephp/blob/3.3.3/src/Http/ActionDispatcher.php#L155
* https://github.com/cakephp/cakephp/blob/3.3.3/src/Routing/Dispatcher.php#L59

**Comment by markstory** [comment]
@ndm2 Thank you for the detailed explanation. I think I know what needs to be changed now.

**Comment by markstory** [comment]
Pull request open.
