### ISSUE TITLE
Bad docs in Cake/ORM/Query class

### ISSUE THREAD

**Issue by pedro-stanaka** [cakephp/cakephp#9497]
This is a:
* [x] enhancement

* CakePHP Version: After 3.3.3 - Commit hash 9a4258e
* Platform and Target: Linux.

### What you did & Expected behaviour & Actual behavior
When developing using IDE's (like PHPStorm) you can find situations where method calls will give you warnings or even errors. Some of them are:

| Current signature | Actual Signature (should be) | Behavior | Cause |
| ------------------------ | ------------ | ------- | ------------ | ---------------- |
| Query#isEmpty($size) | Query#isEmpty() | Will issue a warning in PHPStorm | The method comes from |CollectionTrait and the signature in the docs are wrong. |
| Query#zipWith(...$collections, callable $c) | Query#zipWith($items, callable $callable) | Will issue a error in PHPStorm | Variadics can only be declared as the last argument of function | 

### How to solve it

The methods documentation should match the declaration from the CollectionTrait (or even better, the CollectionInterface) and those tiny errors would go away.

### Final considerations

I'd be very happy to make the necessary changes to fix these issues and others that I find within the docs. Actually, I already have a patch :smile: . If some one gimme the green sign I can submit a PR.

Once more congratulation on the good work guys!!! 

Cheers!

**Comment by markstory** [comment]
Thanks for the issue. I am looking forward to the pull request.
