### ISSUE TITLE
Fix Query::count() problems

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#9501]
Currently there are a few problems when using the smart count strategy selection. These can probably be solved by having a more solid cloning strategy for queries.
- [ ] Prevent the cloning logic in `count()` from messing up with placeholder numbers and binding incorrect data. (refs #8831)
- [ ] Cloning logic in `count()` is messing up with the join conditions. (refs #8892)

**Comment by markstory** [comment]
Could we also solve this by always doing a subquery? In newer versions SQLAlchemy always does a subquery if there is any chance of complexity in the query.

**Comment by lorenzo** [comment]
@markstory That's pretty much what we do, the problem is that we try to optimise the subquery by removing maybe unneeded parts, that probably needs to go

**Comment by markstory** [comment]
I think it does need to go. It has been causing as many problems as it helps. I can take care of that as I made this mess.

**Comment by markstory** [comment]
@lorenzo I've not been able to reproduce the reported issue so far [this test passes right now](https://github.com/cakephp/cakephp/compare/3.next...issue-9501-query-count)

**Comment by lorenzo** [comment]
I'll take a look

**Comment by lorenzo** [comment]
I tested this as well and could not reproduce it either. Closing
