### ISSUE TITLE
Could not generate pagination links with passed parameters in route.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9503]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: Apache 2.4, PHP 7.0.10, MySQL

### What you did

Configured this route:

```
Router::scope('/:lang', [
    'lang' => '[a-z][a-z]'
    ], function (RouteBuilder $routes) {
    $routes->connect('/explore', [
        'controller' => 'Explore',
        'action' => 'index'
    ], [
        '_name' => 'explore',
        'pass' => ['lang']
    ]);
});
```

Tried to generate pagination numbers:

```
echo $this->Paginator->numbers(['url' => ['lang' => 'en']]);
```

Triggered this missing route error:

```
Error: A route matching "array ( 'page' => false, 0 => 'en', 'lang' => 'en', 'action' => 'index', 'plugin' => NULL, 'controller' => 'Explore', '_ext' => NULL, )" could not be found.
```

Notice that both the passed parameter `lang` is defined twice. Once as `0=>'en'` and `'lang'=>'en'`.

### Expected Behavior

It should not be inject named parameters as a numeric key.

### Actual Behavior

The source of the problem was in the PaginatorHelper constructor.

```
        $this->config(
            'options.url',
            array_merge($this->request->params['pass'], ['?' => $query])
        );
```
The above is attempting to persist the current route parameters. Which is a good feature, but I think injecting `params['pass']` is the wrong approach. Since those are numeric key/pair set.

This raises the question of where the bug is located. Should the `params['pass']` contain keys with the name of the parameter instead of numeric keys, or should the helper's constructor inject named parameter manually (some how).

The work around for the above problem was to erase the options URL before generating links.

```
        $this->Paginator->config('options.url',[], false);
```

**Comment by thinkingmedia** [comment]
related #9310

**Comment by markstory** [comment]
Not including the passed parameters will break other use cases. For example routes like `/articles/:action/*` would no longer support pagination. It sounds like Paginator or Router needs to be a bit more clever around how passed parameters are deduplicated.

**Comment by thinkingmedia** [comment]
I got some guidance from @ADmad on filtering routes to persist parameters, but that hasn't resolved this issue. I'm still having trouble with this.

I think this would be fixed if `request->params` persisted the key name for the parameter. I have no idea if that's possible for would break things.

**Comment by markstory** [comment]
@thinkingmedia That might break userland code as `$this->request->params['pass'][0]` will no longer exist. Could this perhaps be solved in the routes reverse matching? If a route detects 'pass' options it could de-duplicate its parameters.

**Comment by thinkingmedia** [comment]
After I stopped passing the language ID to the controller action it started working fine. Despite the fact that I'm passing other parameters.

For example the following works now:

```
Router::scope('/:lang', [
    'lang' => '[a-z][a-z]'
], function (RouteBuilder $routes) {

    $routes->connect('/explore/:type/tag/:tag', [
        'controller' => 'Search',
        'action' => 'queryByTag',
    ], [
        'type' => SLUG,
        'tag' => SLUG,
        'pass' => ['type', 'tag'],
        '_name' => 'board_tag'
    ]);

});
```

The `board_tag` route has no problems showing pagination controls. Which explains why we haven't seen this issue come up. I must of found a strange edge case.

I don't think this is a pagination helper issue, but maybe a bug in the router. I suspect that it happens when you define a route parameter in the outer scope and use `pass` in the child route.

If I change the above to this (it breaks):

```
    $routes->connect('/explore/:type/tag/:tag', [
        'controller' => 'Search',
        'action' => 'queryByTag',
    ], [
        'type' => SLUG,
        'tag' => SLUG,
        'pass' => ['lang', 'type', 'tag'],
        '_name' => 'board_tag'
    ]);
```

Will trigger: 

```
Error: A route matching "array ( 'page' => false, 0 => 'en', 1 => 'movies', 2 => 'action-adventure', 'lang' => 'en', 'action' => 'queryByTag', 'plugin' => NULL, 'controller' => 'Search', '_ext' => NULL, )" could not be found.
```

If I change the order of `pass` to `['type', 'tag', 'lang']` then I get this error:

```
Error: A route matching "array ( 'page' => false, 0 => 'movies', 1 => 'action-adventure', 2 => 'en', 'lang' => 'en', 'action' => 'queryByTag', 'plugin' => NULL, 'controller' => 'Search', '_ext' => NULL, )" could not be found.
```

Notice how the index of `en` changes and that change looks correct to me.

When I remove just the `lang` parameter routing works.

**Comment by thinkingmedia** [comment]
Closing as PR is up.
