### ISSUE TITLE
bufferResults with belongsToMany associations fails on MySQL

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#9509]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: MySQL

### What you did
With following example:

```php
$articles = TableRegistry::get('Articles');
$articles->belongsToMany('Tags', [
    'strategy' => 'subquery'
]);

$query = $articles->find()
    ->bufferResults(false)
    ->contain('Tags');

$query->all();
```

### Actual Behavior

I get:

`SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.`

First of all `BelongsToMany` seems not to be respecting `strategy` option on generated associations. Automatically generated `Tags belongsToMany Articles` gets `select` strategy in an example above. The same goes for junction table associations. I thought that may be a problem, but after correcting strategy on generated associations I still get an exception.

This is my query log:
```
2016-09-23 12:36:51 Debug: duration=0 rows=3 SELECT `Articles`.`id` AS `Articles__id`, `Articles`.`author_id` AS `Articles__author_id`, `Articles`.`title` AS `Articles__title`, `Articles`.`body` AS `Articles__body`, `Articles`.`published` AS `Articles__published` FROM `articles` `Articles`
2016-09-23 12:36:51 Debug: duration=0 rows=4 SELECT `ArticlesTags`.`article_id` AS `Tags_CJoin__article_id`, `ArticlesTags`.`tag_id` AS `Tags_CJoin__tag_id`, `Tags`.`id` AS `Tags__id`, `Tags`.`name` AS `Tags__name`, `Tags`.`description` AS `Tags__description`, `Tags`.`created` AS `Tags__created` FROM `tags` `Tags` INNER JOIN `articles_tags` `ArticlesTags` ON `Tags`.`id` = (`ArticlesTags`.`tag_id`) INNER JOIN (SELECT (`Articles`.`id`) FROM `articles` `Articles` GROUP BY `Articles`.`id` ) `Articles` ON `ArticlesTags`.`article_id` = (`Articles`.`id`)
```
And that seem suspicious - shouldn't it be only one single query since I'm using subqueries?

It works though on Sqlite, but I'm not sure Sqlite supports streaming?

**Comment by lorenzo** [comment]
Yes, I think it is documented as a limitation. Will close the ticket as it is not possible to fix.

**Comment by lorenzo** [comment]
Regarding belongsToMany: they always require a separate query

**Comment by inoas** [comment]
So could this throw an exception (in future, via assert?):
`php
$articles->belongsToMany('Tags', [
    'strategy' => 'subquery'
]);
`

**Comment by lorenzo** [comment]
@ionas no, that is valid code

**Comment by robertpustulka** [comment]
@lorenzo documentation states that:
> Buffering cannot be disabled for queries that eager load hasMany or belongsToMany associations, as these association types require eagerly loading all results so that dependent queries can be generated. **This limitation is not present when using the subquery strategy for those associations.**
http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#working-with-result-sets

And that's what I'm doing I suppose? Perhaps it's an issue with a doc?

**Comment by lorenzo** [comment]
I think it is an issue with the docs, we should fix them... the problem is that it is not possible to have two active result sets, it is a very sad limitation in the database drivers :(

**Comment by robertpustulka** [comment]
OK, so this line should be removed because it also won't work for HasMany association.
I'll handle a PR.
