### ISSUE TITLE
Hash::merge used in Configure::load could lead to some unwanted behaviors

### ISSUE THREAD

**Issue by maxmasetti** [cakephp/cakephp#9512]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* CakePHP Version: 3.3.3.
* Platform and Target: any.

### What you did
Configuring CakeDC/Users loading users.php file as documented in bootstrap:
```
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
debug(Configure::read('Auth'));
Configure::load('users', 'default');
debug(Configure::read('Auth'));
die;
```
where the users.php file contains something like this:
```
return [
    'Auth' => [
        'authenticate' => [
            'all' => [
                'finder' => 'active',
            ],
            'CakeDC/Users.RememberMe',
            'Form',
        ],
        'authorize' => [
            'CakeDC/Users.Superuser',
            'CakeDC/Users.SimpleRbac' => [
                'autoload_config' => 'permissions',
                'role_field' => 'role',
                'default_role' => 'user',
            ],
        ],
    ],
];
```

### Expected Behavior
Values are merged as a human would expect:
```
[
	'authenticate' => [
		'all' => [
			'finder' => 'auth',
			'userModel' => 'CakeDC/Users.Users'
		],
		(int) 0 => 'CakeDC/Users.RememberMe',
		(int) 1 => 'Form'
	],
	'authorize' => [
		(int) 0 => 'CakeDC/Users.Superuser',
		'CakeDC/Users.SimpleRbac' => [
			'autoload_config' => 'permissions',
			'role_field' => 'role',
			'default_role' => 'user'
		],
		(int) 1 => 'Controller'
	],
]
```

### Actual Behavior
But some inconsistency comes due to the magic (may be by design) of the Hash::merge used by the Configure::load method:
```
[
	'authenticate' => [
		'all' => [
			'finder' => 'active',
			'userModel' => 'CakeDC/Users.Users'
		],
		(int) 0 => 'CakeDC/Users.ApiKey',
		(int) 1 => 'CakeDC/Users.RememberMe',
		(int) 2 => 'Form',
		(int) 3 => 'CakeDC/Users.RememberMe',
		(int) 4 => 'Form'
	],
	'authorize' => [
		(int) 0 => 'CakeDC/Users.Superuser',
		(int) 1 => 'CakeDC/Users.SimpleRbac',
		(int) 2 => 'CakeDC/Users.Superuser',
		'CakeDC/Users.SimpleRbac' => [
			'autoload_config' => 'permissions',
			'role_field' => 'role',
			'default_role' => 'user'
		]
	]
]
```
I spent much time dealing with unbelivable behaviors and debugging before getting the point.
By the moment I can't load properties from file and have to inject them directly with Configure::write method.
May be a convenient solution could be formulated or this is a final choice?
thx

**Comment by dereuromark** [comment]
Yeah, the merge only really works with string based keys, with numeric indexes keys it can easily break.
The same is true for any config merge etc.

**Comment by markstory** [comment]
The merge behavior is of numeric based keys (lists) is consistent with `array_merge()` as well.

```php
php > $a = [1, 2, 3];
php > $b = [4, 5, 6];
php > var_dump(array_merge($a, $b));
php shell code:1:
array(6) {
  [0] =>
  int(1)
  [1] =>
  int(2)
  [2] =>
  int(3)
  [3] =>
  int(4)
  [4] =>
  int(5)
  [5] =>
  int(6)
}
```

Making `Hash::merge()` inconsistent with `array_merge()` would be surprising to more folks I think.

**Comment by maxmasetti** [comment]
yes, array_merge is dump. but there is no reason to not think of something better, may be a configuration merger just inside Configure that is not based on the behavior of Hash::merge but on something like Hash::union or so.
I will try to ask CakeDC/Users developers to consider that their configuration options are not mergeable whith Configure::load method.
thanks

**Comment by markstory** [comment]
> yes, array_merge is dump. but there is no reason to not think of something better

List merging behaves pretty consistently not only in PHP but in other languages as well.
