### ISSUE TITLE
Unauthorized user succesfully deletes objects

### ISSUE THREAD

**Issue by maxmasetti** [cakephp/cakephp#9513]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: apache 2.4, mysql, php 5.6.25, CakeDC/Users SimpleRbac

### What you did
Unauthorized user (verified) deletes an object, while Authcomponent::authCheck stops event propagation (verified) and returns the response with location to redirect to, but delete is invoked.

### Expected Behavior
Actually stop event propagation and delete isn't invoked.

### Actual Behavior
Row deleted.

Is about two days I deeply deal with this error and I'm getting fool. I think this is a bug: 
thx

**Comment by markstory** [comment]
How can someone reproduce this issue? How do you have AuthComponent setup?

**Comment by markstory** [comment]
Testing locally with a sample app based off the [bookmarker tutorial](http://book.cakephp.org/3.0/en/tutorials-and-examples/bookmarks/intro.html) I wasn't able to reproduce unauthenticated users being able to delete bookmarks.

**Comment by maxmasetti** [comment]
ok ok, my deal: I found the problem. After a two hour session with xdebug I found a forgot to return a value in the AppController::redirect override, so a simple yet powerfull and quite-always functioning code like this:
```
  public function redirect($url, $status = 302) {
    if (isset($this->request->data['backto'])) {
      $url = $this->request->data['backto'];
    }
    parent::redirect($url, $status);
  }
```
made me crazy. beg your pardon for the issue opened and hope this helps someone else, be more carefull and return the right value ;)
```
    return parent::redirect($url, $status);
```
the
