### ISSUE TITLE
RFC: insertMulti option for save and saveMany

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#9515]
Would't it be feasible to have an option in `save` and `saveMany` to use multi-row inserts while still calling the callbacks? Of course all the callbacks would have to be called when all the records would have been saved. The sequence would be:
- Trigger rule validation and events up to the `beforeSave` event for all entities going to be saved.
- Save all entities using multi-row inserts.
- Trigger `afterSave` and `afterSaveCommit` for all entities.

The same sequence could be used for associated entities but they would do an insert for each association in every entity.

I would be interested in such feature and would likely help to implement it in the future in case it's considered a good idea.

EDIT: Changed `insertMulti` references to `multi-row inserts` since that's a feature in CakePHP2 and this issue is meant to be for CakePHP3.

**Comment by markstory** [comment]
How would associations be handled in this case? You could also run into scenarios where save()/saveMany() need to handle a mix of `UPDATE` and `INSERT` which adds more complex scenarios.

**Comment by ADmad** [comment]
Running validations for all records beforehand has caused us unnecessary tickets in the past as people often set validations for foreignKey fields, values for which are not available until parent record is saved.

**Comment by ADmad** [comment]
Also how would you handle application rules like say unique email when using multi insert?

**Comment by lorenzo** [comment]
I would be possible only with a big number of limitations, like no automatic belongsTo saving.

Another possible limitation is that it would either only oupdste records or insert new ones, you cannot mix like it can be done with saveMany.

 If you want to start exploring this idea, com up with a possible API and the limitations it should have and we can evaluate from there.

A possible approach is to build a plugin that serves your own purpose. I'm personally a bit skeptic that it can be done in a way that does not suck.

**Comment by inoas** [comment]
My personal stance, as I ran against the limitations of `patchEntity()` / `newEntity()` + `save()` as well is still: To keep those as simple as possible while they work for like 95% of the use cases of most app developers.

What I'd love to see instead in 4.x or 5.x is utilising a query builder - like we do for reading data in CakePHP 3 - to create the insert and/or update and/or delete statements. The things I'd love to see is being able to do is atomic updates while callbacks also work.

Maybe having a builder kind of thing when you need more complex saving will also be sufficient to solve multiple inserts/upserts/updates/deletes?

**Comment by berarma** [comment]
Thanks for you input. Yes, there will have to be some limitations but the question is how reasonable those limitations would be, how hard would it be to implement it and the real final benefit.

 I'm working on a project that does a lot of inserts in bursts to a few related tables. Right now I'm using ```saveMany``` that executes a lot of single inserts slowing the process down. In the not so far future I'll have to optimize this. My best option right now is directly using ```insertMulti``` and forget about rules and callbacks. But I'd like to consider coming up with something more reusable.

Some limitations that seem necessary would be:
- Application rules should be resolvable in a way that they only need to be checked against the already existing entities. For a unique field rule it would mean that the set of entities being added should already fulfill that rule, that is, no duplicated values among the new entities. In case there's some rule that can't be successfully resolved checking only against the existing entities, rule checking should be explicitly disabled.
- Only inserts involved, all entities should be new. With this limitation I think all associations types could be made to work although this would be the hardest part.

I think this wouldn't be too limiting for the use cases where the entities being saved are highly related and can be seen as the decomposition of a higher-lever entity. Most rules could be written with these higher-level entities in mind or disabled if that's not the case.

@ADmad:
> Running validations for all records beforehand has caused us unnecessary tickets in the past as people often set validations for foreignKey fields, values for which are not available until parent record is saved.

Rules could be checked after saving parents just like we do now I guess. Rules should be checked just right before we're going to save the entities. We would check rules for belongsTo associations and save them, then check rules for the parent entities and save them too and so on.

I'm sure I'm overlooking some of the details but I wanted to read your opinions early.

By now I'm still trying to evaluate how meaningful would this be. Any other suggested ways to make switching from ```save/saveMany``` to ```insertMulti``` easier are welcomed (@ionas). In case my original idea proves to be too hard and/or limiting I'd explore other paths. This doesn't have to be a core feature, most probably a plugin, but I'd still like to make something that could be easily reused if possible. And if we could improve the core somehow why not.

I won't be able to work on this for some time, so don't expect a serious proposal and API soon. That way I'll also have time to read all comments collected here and better understand myself what would need to be done.

**Comment by markstory** [comment]
> What I'd love to see instead in 4.x or 5.x is utilising a query builder - like we do for reading data in CakePHP 3 - to create the insert and/or update and/or delete statements. 

This already exists @inoas, however lower level APIs like this don't interact well with higher level abstractions like an ORM.

**Comment by ADmad** [comment]
As mentioned above the feasibility and limitations of this should be first explored as a plugin, hence closing this issue.
