### ISSUE TITLE
Cannot send a custom status text

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9516]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: Windows 10 / Maria-DB 10.1.13 / Apache 2.4.17.

### What you did

Define custom status code in my ErrorController:
```php
$this->response->httpCodes([
   444 => 'No Response',
]);
```

And throw an HttpException with code 444 in my application:
```php
throw HttpException('No Response.', 444);
```

### Expected Behavior
A Status-Line header is sent with the status text.
```
HTTP/1.1 444 No Response
```

### Actual Behavior
A Status-Line header was sent without the status text as of 3.3.
#### CakePHP < 3.3
```
HTTP/1.1 444 No Response
```
#### CakePHP >= 3.3
```
HTTP/1.1 444
```
Therefore, my browser got 500 instead of 444.

### Reason

We have different status code settings in [Zend\Diactoros\Response](https://github.com/zendframework/zend-diactoros/blob/215f47a73fb2a7f2d33230a3e23658acae234035/src/Response.php#L32-L96) and [Cake\Network\Response](https://github.com/cakephp/cakephp/blob/6f7689b9675b28ea0aa434f1a1afb5db6d194d22/src/Network/Response.php#L39-L83), respectively.

As of 3.3, we must satisfy both request objects to send a custom status text. Unfortunately, `Zend\Diactoros\Response`  seems to not support define a custom status text, So we would need to composite or extend it to implement our `getReasonPhrase()`.

**Comment by markstory** [comment]
I'm not sure we should have ever allowed people to define their own status codes. With that said we should add the full list of standardized status codes to `Cake\Network\Response`.

**Comment by markstory** [comment]
[This list](https://httpstatuses.com/) looks fairly complete.

**Comment by chinpei215** [comment]
We could define our own status codes by using `Request::httpCodes()` method in the past. I created a patch to solve #8962 today, but it doesn't work on 3.3. So I noticed this issue.

`Zend\Diactoros\Response` doesn't contain 226, 308, 421, 444,  499, 510 and 599 in `$phrases` property. If we add the status codes to  our Response class, we would also need to add them to Zend response class. Otherwise we cannot emit the status text.

**Comment by inoas** [comment]
* I could not find sources in English, only in German that custom (so called proprietary or private) codes can be done in HTTP 900-999 range. I tried to find some official docs but found none.
German Google: https://www.google.de/#q=http+status+code+900-999
German Wikipedia: https://de.wikipedia.org/wiki/HTTP-Statuscode#9xx_.E2.80.93_Propriet.C3.A4re_Fehler
* I am pretty much against messing with HTTP status codes beyond standard ones. If you want that CakePHP should not help you. Instead I'd love to see Cake (and if required Diactoros\Response) to support those missing - or create our own version similar to the way you did it with ResponseEmitter.

**Comment by markstory** [comment]
> Zend\Diactoros\Response doesn't contain 226, 308, 421, 444, 499, 510 and 599 in $phrases property.

I'm happy to see if diactoros is open to adding the missing status codes. Its likely an oversight on their part (as it was with us missing status codes).

**Comment by chinpei215** [comment]
I noticed that we could send a custom status text by using [withStatus()](https://github.com/zendframework/zend-diactoros/blob/215f47a73fb2a7f2d33230a3e23658acae234035/src/Response.php#L148-L154) method. So it might be better to fix `Request::toPsr()` method.

**Comment by markstory** [comment]
@chinpei215 That works too.

**Comment by ravage84** [comment]
@chinpei215 & @markstory  have a look at #9523, please. :bow:

**Comment by markstory** [comment]
Closing as I think #9523 covers this issue. I don't think the `ResponseTransformer` needs to change as the diactoros status handling code looks for codes between 100 & 599.

**Comment by chinpei215** [comment]
@markstory I am not sure how users can send 444 with status text. Diactoros doesn't allow to send it. See [SapiEmitterTrait::emitStatusLine()](https://github.com/zendframework/zend-diactoros/blob/a8640c754a836ee7945a3b58060c7d3b1af0263a/src/Response/SapiEmitterTrait.php#L45), [Response::getReasonPhrase()](https://github.com/zendframework/zend-diactoros/blob/215f47a73fb2a7f2d33230a3e23658acae234035/src/Response.php#L137), and [Response::$phrases](https://github.com/zendframework/zend-diactoros/blob/215f47a73fb2a7f2d33230a3e23658acae234035/src/Response.php#L83-L84).

We would need to fix [ResponseTransformer::toPsr()](https://github.com/cakephp/cakephp/blob/39a83c8bc03dbd5ecbfded081e76d5de2f42a1af/src/Http/ResponseTransformer.php#L188) like the following:
```php
public static function toPsr(CakeResponse $response)
{
    $status = $response->statusCode();
    $reasonPhrase = current($response->httpCodes($status));

    // The above statements could be done more efficiently,
    // if our Response class has a method to fetch current status with text.
    // list($status, $reasonPhrase) = $reaponse->getStatusWithText();

    ...

    $psrResponse = new DiactorosResponse($stream, $status, $headers);
    if ($reasonPhrase !== $psrResponse->getReasonPhrase()) {
        $psrResponse = $psrResponse->withStatus($status, $reasonPhrase);
    }
    return $psrResponse;
}
```
Otherwise, 444 or other status codes included only in our Response class won't be sent correctly.

**Comment by ravage84** [comment]
@markstory  & @chinpei215 I created[ a PR against zend/diactoros](https://github.com/zendframework/zend-diactoros/pull/208) to add the missing status codes there, too.
