### ISSUE TITLE
Auto-generated associations in BelongsToMany ignore strategy option.

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#9520]
This is a (multiple allowed):
* [x] bug (possible?)
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.3

(Following #9509)

### What you did

In this example:

```php
$articles = TableRegistry::get('Articles');
$articles->belongsToMany('Tags', [
    'strategy' => 'subquery',
    'saveStrategy' => 'append'
]);
```

`BelongsToMany` will generate following associations:

- `Tags belongsToMany Articles`
- `Tags hasMany ArticlesTags`
- `Articles hasMany ArticlesTags`

None of them would use the *subquery* `strategy`. Also a target association would ignore the *append* `saveStrategy`. Is it a desired behavior or an oversight?

**Comment by lorenzo** [comment]
I'm not sure we should preserve the save strategy, but the find strategy makes sense to preserve

**Comment by robertpustulka** [comment]
PR is open #9544
