### ISSUE TITLE
Fixtures - float type wrong value

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9522]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9.
* Platform and Target: Linux, Apache, MySQL.

### What you did
I created a fixture with float type column:
```
		'my_column' => array(
			'type' => 'float',
			'length' => '8,6',
			'null' => true,
			'default' => null,
		),
```
One of $records values is 55.690082.

### Expected Behavior
The fixture should create a record containing my_column with 55.690082.

### Actual Behavior
The unit test fails:
```
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-        'my_column' => '55.690082'
+        'my_column' => '55.690083'
```

**Comment by ADmad** [comment]
> One of $records values is 55.690082.

Have you set the value as float or string?

**Comment by bancer** [comment]
It was set this way: `'my_column' => '55.690082',`.

**Comment by bancer** [comment]
Setting it this way `'my_column' => 55.690082,` does not change anything. The test fails anyway with the same message.

**Comment by ADmad** [comment]
Setting value as float is very likely to not work though I expected it to work when setting as string.

**Comment by chinpei215** [comment]
@bancer Can you insert `55.690082` into the field via mysql console?

**Comment by bancer** [comment]
@chinpei215 Yes, I can. The value has been taken from production database. The column is actually double in the database: `my_column double DEFAULT NULL,`.

**Comment by bancer** [comment]
Looks like MySQL inserts wrong value to FLOAT(8,6) column.

```
CREATE TABLE `test`(
	`col_float` FLOAT,
    `col_float_8_6` FLOAT(8,6),
    `col_double` DOUBLE,
    `col_double_8_6` DOUBLE(8,6),
    `col_decimal_8_6` DECIMAL(8,6)
);
INSERT INTO `test` values (1.2,1.2,1.2,1.2,1.2);
INSERT INTO `test` values (55.690082,55.690082,55.690082,55.690082,55.690082);
```

![screenshot from 2016-09-26 17 04 45](https://cloud.githubusercontent.com/assets/3830106/18839451/586fb7a4-840b-11e6-90ab-43cc50ac9ddf.png)

Why CakePHP does not support double data type?

**Comment by chinpei215** [comment]
> Why CakePHP does not support double data type?

@bancer I don't know. But it would be nice if CakePHP2 supports double types.

**Comment by markstory** [comment]
CakePHP _does_ support 'double' but it is converted/treated as 'float' by the [MySQL driver](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Datasource/Database/Mysql.php#L798-L800).

It sounds like you are losing precision which is something that float columns do. Have you considered using decimal columns?

**Comment by bancer** [comment]
> CakePHP does support 'double' but it is converted/treated as 'float' by the MySQL driver.

Well, I cannot do 
```
		'my_column' => array(
			'type' => 'double',
			'length' => '8,6',
			'null' => true,
			'default' => null,
		),
```
in a fixture: 
> PHP Warning:  Column type double does not exist in /Cake/Model/Datasource/DboSource.php on line 3366

 .
> Have you considered using decimal columns?

Yes, but that is not always possible in legacy databases.

**Comment by chinpei215** [comment]
@bancer I came up with a workaround:
```php
'my_column' => array(
    'type' => 'double',
    'length' => '53',
    'null' => true,
    'default' => null,
),
```

https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html
> MySQL also supports this optional precision specification, but the precision value is used only to determine storage size. A precision from 0 to 23 results in a 4-byte single-precision FLOAT column. A precision from 24 to 53 results in an 8-byte double-precision DOUBLE column.

**Comment by bancer** [comment]
@chinpei215 Thanks. Seems to work. I guess it would be nice to document that in the cookbook.

**Comment by markstory** [comment]
@bancer Could you take care of updating the documentation?

Closing this as there is a workaround for folks using MySQL.

**Comment by dereuromark** [comment]
With current plugin it also seems that instead of

    'limit' => '10,6',

the config

    'precision' => 10,
    'scale' => 6,

seems to work for decimal or float.

I still need to figure out what script baked the wrong one for me, so I just leave this here for reference.

A bit weird though is that fixtures are using

    'length' => 10, 
    'precision' => 6

it seems...
