### ISSUE TITLE
Wrong enum column length

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9526]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9.
* Platform and Target: Linux, Apache, MySQL.

### What you did
SQL:
```
CREATE TABLE `test`(
	`col_char` CHAR(21),
    `col_varchar` VARCHAR(21),
    `col_enum` ENUM('One Value','ANOTHER ... VALUE ...')
);
INSERT INTO `test` values ('One Value','One Value','One Value');
INSERT INTO `test` values ('ANOTHER ... VALUE ...','ANOTHER ... VALUE ...','ANOTHER ... VALUE ...');
```
In the controller:
```
		$db = ConnectionManager::getDataSource('default');
		$schema = $db->describe('test');
		debug($schema);
```

### Expected Behavior
```
array(
	'col_char' => array(
		'type' => 'string',
		'null' => true,
		'default' => null,
		'length' => (int) 21,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	),
	'col_varchar' => array(
		'type' => 'string',
		'null' => true,
		'default' => null,
		'length' => (int) 21,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	),
	'col_enum' => array(
		'type' => 'enum('One Value','ANOTHER ... VALUE ...')',
		'null' => true,
		'default' => null,
		'length' => (int) 21,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	)
)
```

### Actual Behavior
```
array(
	'col_char' => array(
		'type' => 'string',
		'null' => true,
		'default' => null,
		'length' => (int) 21,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	),
	'col_varchar' => array(
		'type' => 'string',
		'null' => true,
		'default' => null,
		'length' => (int) 21,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	),
	'col_enum' => array(
		'type' => 'enum('One Value','ANOTHER ... VALUE ...')',
		'null' => true,
		'default' => null,
		'length' => (int) 9,
		'collate' => 'utf8_unicode_ci',
		'charset' => 'utf8'
	)
)
```

The length of enum column is wrong. I would expect it to be 21 as the length of the longest string 'ANOTHER ... VALUE ...'.

**Comment by markstory** [comment]
We don't support reflection on enum columns. As you can see the type is completely wrong.

**Comment by chinpei215** [comment]
@markstory DboSource seems to be supporting enum.
https://github.com/cakephp/cakephp/blob/4b1be4467863b6430959faeafaa6ad70c7292f40/lib/Cake/Model/Datasource/DboSource.php#L3121-L3132

Probably, the regular expression would be incorrect.
https://github.com/cakephp/cakephp/blob/4b1be4467863b6430959faeafaa6ad70c7292f40/lib/Cake/Model/Datasource/DboSource.php#L3084

**Comment by markstory** [comment]
My previous statement was based off of [enum not being here](https://github.com/cakephp/cakephp/blob/4b1be4467863b6430959faeafaa6ad70c7292f40/lib/Cake/Model/Datasource/Database/Mysql.php#L114-L128) but looking more closely at [Mysql::column](https://github.com/cakephp/cakephp/blob/4b1be4467863b6430959faeafaa6ad70c7292f40/lib/Cake/Model/Datasource/Database/Mysql.php#L747) I'm clearly wrong.

**Comment by dereuromark** [comment]
Very basic support for enum should be part of the framework responsibility.
Refs https://github.com/cakephp/cakephp/issues/2637 and https://github.com/cakephp/cakephp/pull/7332 and especially https://github.com/cakephp/cakephp/pull/1011

**Comment by markstory** [comment]
Closing as a pull request is open now.
