### ISSUE TITLE
Check if an item belongs to a hasMany association before updating in CakePHP 3.3.4

### ISSUE THREAD

**Issue by rowanjordaan** [cakephp/cakephp#9527]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.4
* Platform and Target: 	‪Ubuntu 14.04.1 LTS‬, Plesk 12.5.30, PHP 7+, MySQL

### What you did
**What I am trying to do:**

I have Estimates and Estimates have items "EstimateItems". When updating a Estimate the EstimateItems changed should update. (using patchEntity)

This is working with my current code, my only problem is that other users can edit the Estimate Items of other users when changing the primary key of a EstimateItem in the edit form, because when patching the existing EstimateItems CakePHP only looks at the primary key of the EstimateItem and doesn't take the association in consideration. 

**_Also it's still possible to edit the estimate_id of a EstimateItem while $_accessible estimate_id is set to false._**

So what I need is CakePHP to validate that this EstimateItem belongs to the current association before updating or while trying to update.

**Current Query**
```
UPDATE 
  estimate_items 
SET 
  data = 'Test Query 1', 
  amount = 123456789, 
  tax_id = 3 
WHERE 
  id = 3
```

**Expected Query**
```
UPDATE 
  estimate_items 
SET 
  data = 'Test Query 1', 
  amount = 123456789, 
  tax_id = 3 
WHERE 
  id = 3 AND estimate_id = 1
```
**Current code:**

**Estimates -> Edit.ctp**
```
<?php $this->Form->templates($formTemplates['default']); ?>
<?= $this->Form->create($estimate, ['enctype' => 'multipart/form-data']) ?>
    <fieldset>
        <legend><?= __('Offerte') ?></legend>

        <?= $this->Form->input('reference', ['label' => __('#Referentie'), 'autocomplete' => 'off']) ?>
        <?= $this->Form->input('client_id',
            [
                'type' => 'select',
                'empty' => true,
                'label' => __('Klant'),
                'options' => $clients
            ]
        )
        ?>

        <?php

        foreach($estimate->estimate_items as $key => $item){
        ?>
        <div class="item">
            <legend>Item</legend>
            <?= $this->Form->hidden('estimate_items.'. $key .'.id') ?>
            <?= $this->Form->input('estimate_items.'. $key .'.data', ['type' => 'text', 'label' => __('Beschrijving')]) ?>
            <?= $this->Form->input('estimate_items.'. $key .'.amount', ['type' => 'text', 'label' => __('Bedrag'), 'class' => 'input-date']) ?>
            <?= $this->Form->input('estimate_items.'. $key .'.tax_id',
                [
                    'type' => 'select',
                    'empty' => true,
                    'label' => __('Belasting type'),
                    'options' => $taxes
                ]
            )
            ?>
        </div>
        <?php
        }

        ?>

        <legend>Informatie</legend>
        <?= $this->Form->input('date', ['type' => 'text', 'label' => __('Offerte datum'), 'autocomplete' => 'off']) ?>
        <?= $this->Form->input('expiration', ['type' => 'text', 'label' => __('Verloop datum'), 'autocomplete' => 'off']) ?>
   </fieldset>
<?= $this->Form->button(__('Save')); ?>
<?= $this->Form->end() ?>
```
**Estimates Controller**
```
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class EstimatesController extends AppController
{
public function edit($id){
        $associated = ['EstimateItems'];

        $estimate = $this->Estimates->get($id, ['contain' => $associated]);

        $this->log($estimate);
        if($this->request->is(['patch', 'post', 'put'])) {

            $estimate = $this->Estimates->patchEntity($estimate, $this->request->data, [
                'associated' => $associated
            ]);

            $estimate->total = '0';
            $this->log($estimate);
            $this->log($this->request->data);

            if($this->Estimates->save($estimate, ['associated' => $associated])){
                $this->Flash->success(__('De offerte is bijgewerkt'));
                return $this->redirect(['action' => 'index']);
            }
        }

        $this->set('taxes', $this->Estimates->Taxes->find('list', [ 'keyField' => 'id', 'valueField' => 'tax_name' ]));
        $this->set('clients', $this->Estimates->Clients->find('list', [ 'keyField' => 'id', 'valueField' => 'companyname' ]));
        $this->set('estimate', $estimate);
    }
}
```
**EstimatesTable**
```
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\ORM\RulesChecker;
use Cake\ORM\Rule\IsUnique;

class EstimatesTable extends Table
{
public function initialize(array $config)
    {
        $this->addAssociations([
            'hasOne' => ['Taxes'],
            'belongsTo' => ['Companies', 'Clients'],
            'hasMany' => ['EstimateItems' => [
                'foreignKey' => 'estimate_id'
            ]]
        ]);

    }

public function buildRules(RulesChecker $rules){

        // A Node however should in addition also always reference a Site.
       $rules->add($rules->existsIn(['estimate_id'], 'EstimateItems'));

        return $rules;
    }

}
```

**EstimateItem Entity**

```
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class EstimateItem extends Entity
{
    protected $_accessible = [
        '*' => false,
        'data' => true,
        'amount' => true,
        'tax_id' => true,
        'unit_id' => true
    ];
}
```

**EstimateItemsTable**

```
<?php
namespace App\Model\Table;

use Cake\ORM\Entity;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\ORM\RulesChecker;
use Cake\ORM\Rule\IsUnique;
use Cake\ORM\Query;


class EstimateItemsTable extends Table
{

    public function initialize(array $config)
    {
      $this->addAssociations([
            'belongsTo' => ['Estimates' => ['foreignKey' => 'estimate_id']],
            'hasOne' => ['Taxes' => ['foreignKey' => 'tax_id']]
        ]);
    }
}
```

**Estimate Entity**

```
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Estimate extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => false,
        'id' => false,
    ];
}
```

### Expected Behavior
When a belongsto entity gets updated by a hasmany association it should only update when the entity being updated actually belongsto the assocation which called the update.

### Actual Behavior
Entity that belongsto a hasmany association still gets updated while the update gets called by the belongsto association while it does not belong to the updated entity. What happens is that the association automaticly changes the "estimate_id" (foreign key) and makes it did not belong to the hasmany in the first place. As seen in the example code.

**Comment by markstory** [comment]
> When a belongsto entity gets updated by a hasmany association it should only update when the entity being updated actually belongsto the assocation which called the update.

I'm not sure that is possible for the ORM to constrain. It would prevent entities being re-parented. However, this kind of logic is the kind of logic/rules that could be implemented as an application rule.

```php
$rules->addUpdate(function($entity) {
  if (!$entity->dirty('estimate_id')) {
    return true;
  }
  return $entity->estimate_id == $entity->getOriginal('estimate_id');
}, 'ownership', ['errorField' => 'estimate_id']);
```

I think a rule that fails when the estimate_id values have changed is the kind of thing that you are looking to prevent.

**Comment by ndm2** [comment]
I still fail to see how `id` or `estimate_id` would make it from the request data into the entity in this specific example. That really shouldn't be possible, if it were, then that would be a bug.

Are you sure that the code is really using your concrete entity implementations, and not instances of `\Cake\ORM\Entity` where your accessible configuration is missing?

**Comment by rowanjordaan** [comment]
@markstory Thanks for commenting. I indeed need to prevent the update when the estimate_id has been changed, that would solve my issue. But wouldn't it be more secure if it was possible to do a extra and in the where clause and check if the parent id is correct?

The code you supplied does not work for me and I think this is because of what I explained below to ndm2. Maybe this is a problem? Because I think the rule thing only works when the estimate_id is set in the form and that is not the case.

@ndm2 The code is exactly as you see in my post. The estimate_id is indeed updating when changed in the form automaticly (it's not set in the form) to the "Estimate" which is updating the "EstimateItem". I indeed think this is a bug and should be fixed.

**Example**
_User 1_ has a estimate with id 1 and that estimate has 2 estimate items with id 1 & 2.

_User 2_ has a estimate with id 2 and that estimate has 2 estimate items with id 2 & 3.

**Item in form html:**
```
<div class="item">
            <legend>Item #1</legend>
            <div class="inputbox"><input type="hidden" name="estimate_items[1][id]" value="1"></div>            <div class="input text"><div class="inputbox"><input type="text" name="estimate_items[1][data]" id="estimate-items-1-data" value="Deze komt van Rowan -> ID 4"></div></div>           
 <div class="input text"><div class="inputbox"><input type="text" name="estimate_items[1][amount]" class="input-date" maxlength="11" id="estimate-items-1-amount" value="123"></div></div>           
 <div class="input select"><div class="inputbox"><select name="estimate_items[1][tax_id]" id="estimate-items-1-tax-id"><option value=""></option><option value="1">Nederland 21%</option><option value="2">Nederland 6%</option><option value="3" selected="selected">Geen 0%</option></select></div></div>        </div>

```
When user 1 logs in, goes to edit his estimate #1 and changes the item id  value of item 1 "estimate_items[1][id]" "value="#value" to id 3 (which is the id from a item of user 2 that belongsto estimate id 2) when the data gets patched the estimate_id of item 3 that belongs to estimate_id 2 gets automatically set to estimate_id = 1 because the parent of the estimateItem updating is estimate_id 1 in this case even tho the $_accessible estimate_id is set to false.

**Comment by markstory** [comment]
The estimate_id gets changed even when the field is not 'accessible' because it is not mass-assigned. Instead it is set individually by the ORM when the entity has its parentage changed.

The reason I suggested an application rule is that they are applied _after_ validation and allow you to assert/validate the state of objects before they are persisted, and are not contingent on data in forms.

**Comment by rowanjordaan** [comment]
@markstory Ah I see it's working indeed. Thanks! I understand it now. Thank you for your help man. What is exactly added to the 3.3.5 milestone if I might ask? :)

**Comment by markstory** [comment]
@rowanjordaan We assign milestones to issues based on when the fixes for them would typically ship. However, that isn't applicable for this issue as you can solve your problem with existing features.

**Comment by rowanjordaan** [comment]
> When a belongsto entity gets updated by a hasmany association it should only update when the entity being updated actually belongsto the assocation which called the update.

I don't see how this would prevent re-parenting since I was talking about the fact that some one changed the "id" field not the "estimate_id" field in a form. And it should check if that "id" belongsto the current association (with the old data) and after that update it with the new one. Maybe it's still something to look into.
