### ISSUE TITLE
Add GROUP_CONCAT to the function builder

### ISSUE THREAD

**Issue by nrother** [cakephp/cakephp#9529]
It would be nice to have the `group_concat`function in the query builder, as it implemeted a different in each dialect.

* MySQL http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_group-concat
* Sqlite https://www.sqlite.org/lang_aggfunc.html#groupconcat
* Oracle http://docs.oracle.com/cd/E11882_01/server.112/e41084/functions089.htm#SQLRF30030
* MSSQL https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f09d4166-2030-41fe-b86e-392fbc94db53/tsql-equivalent-for-groupconcat-function?forum=transactsql

The only problem seems to be MSSQL, but it looks possible (but I'm not an SQL expert)

**Comment by markstory** [comment]
Sounds reasonable to me. Did you want to put a pull request together?

**Comment by nrother** [comment]
I'll try implementing it. I just [saw](http://stackoverflow.com/a/16771200) that `listagg` is only available from 11g onwards in oracle. Should we check the version and throw an exception if not availabe or should we ignore this? (There seems to be no real fallback).

**Comment by markstory** [comment]
I think an exception/invalid SQL is reasonable.

**Comment by dakota** [comment]
I don't think we should worry about Oracle. It is not supported by core, only the [CakeDC Plugin](https://github.com/CakeDC/cakephp-oracle-driver) which is for 11g up anyways.

**Comment by nrother** [comment]
Oh I mixed up oracle and postgress...

Anyway, a PR is now open (#9536)
