### ISSUE TITLE
Bug - with caching Cell::render() returns the same results on multiple calls with different templates

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#9531]
While reading the code and planning how we might back-port view cells to 2.x (see #8569), my colleague @ascii-soup and I found what we think is a bug. Please confirm if this is indeed a bug.

```php
//where $cell is an instance of Cell with caching enabled
echo $cell->render("some_template");
echo $cell->render("some_other_template");
```

The expected result would be that the second echo would print something different to the first (unless the two templates were identical!). 

We have created a test to prove the bug and can add a fix for it if necessary. See:
https://github.com/cakephp/cakephp/compare/master...garethellis36:bugfix/cached-viewcells-return-the-same-results-with-different-templates-when-rendering?expand=1

**Comment by markstory** [comment]
The issue you found looks like a defect to me. A pull request would be excellent :smile:

**Comment by saeideng** [comment]
I think both of render() should be return/echo some value because you use some cache value

**Comment by markstory** [comment]
Closing as a pull request is open now.
