### ISSUE TITLE
Implement writeMany() method for Redis

### ISSUE THREAD

**Issue by ethanpooley** [cakephp/cakephp#9538]
Is there a reason why `RedisEngine::writeMany()` is not implemented? It seems it could be, using [MSET](http://redis.io/commands/MSET). I'd like to PR an implementation, unless I'm missing something.

**Comment by markstory** [comment]
No real reason, I suspect it was just forgotten about. A pull request would be great :+1:

**Comment by ADmad** [comment]
Closing as the issue has gone stale. A pull request is welcome if you are still interested in adding this feature.
