### ISSUE TITLE
Introducing a Breadcrumbs Helper

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/cakephp#9542]
This is a RFC to discuss a better implementation and management of breadcrumbs.

The current way of dealing with breadcrumbs is pretty limited for two reasons :

1. no easy way to customize it. It currently renders a simple list and using microdata in the markup is not really smooth nor easy.
2. because of how the various layers of the view are rendered in Cake (from « the inside out »), results can sometimes be… unexpected. For instance, adding a crumb in a layout file will add it at the end of the crumbs list, when one might expect it to be added at the beginning (I know I do everytime I start a new project). And if you are using the view extending mechanism by defining a crumb in the extended view, everything goes south : extended templates crumbs are rendered after extending templates one, which means that if you define a « global » crumb with the extended template, it will be displayed after in the trail.

In my opinion, both these issues can be addressed by creating a new BreadcrumbsHelper :

1. we can leverage the `StringTemplate` class to gives more control to the dev when rendering the crumbs trail, as FormHelper already does. They are simple to configure and easily extendable by devs in the Helper configuration
2. having a new `Helper` that more or less acts as a queue (exactly like how middlewares are stored : see the API draft below) would give more control and would allow devs to bypass the aforementioned issues.

We could imagine an API like this one :

```php
namespace Cake\View\Helper;

use Cake\View\Helper;
use Cake\View\StringTemplateTrait;

class BreadcrumbsHelper extends Helper
{
    use StringTemplateTrait;

    public function add($name, $link, $options = []);
    public function prepend($name, $link, $options = []);
    public function insertAt($index, $name, $link, $options = []);
    public function insertBefore($nameIndex, $name, $link, $options = []);
    public function insertAfter($nameIndex, $name, $link, $options = []);
    public function getCrumbs();
    public function render();
}
```

For the example mentioned above, one would use the `prepend()` method for the layout template file, the extended template file as well as for the extending template file. This would put each item on top of each other, leading to a well ordered crumbs trail.

The API would also allows a developer to get the list of crumbs (which is currently impossible unless you override the `HtmlHelper` with your own implementation) and would also expose a method for rendering it using the templates configured by the devs.

Keeping backward compatibility would also be easy. By instanciating a `BreadcrumbsHelper` in the `HtmlHelper`, we use it to take over the crumbs management (using the `add()` method) and rendering it by having the `BreadcrumbsHelper` have the current `ul` and `li` templates of the HtmlHelper. It should be fairly transparent and all tests should pass the way they are currently defined. We could then easily target 3.3.5 (or 3.3.6 depending on the timeline).

If the idea is accepted, I can start working on it and further discussion could take place once a first implementation is drafted.
I am of course opened to ideas.

**Comment by dereuromark** [comment]
I would very much like to extract that stuff out of the Html into its own helper. So 👍 from me.
To be fair, it could also be a completely stand alone opt-in plugin, of course. Either cakephp domain or friendsofcake etc.

**Comment by HavokInspiration** [comment]
@dereuromark At first I was going to implement it as a plugin. But I figured it can very well take place in the core since it would be an upgrade of a current behavior.

Either way, I'll implement it. It just depends on the community's opinion :)

**Comment by ADmad** [comment]
Normally I too would suggest having it as a community feature but since this would be improving upon existing feature :+1: to having `BreadCrumbsHelper` in core itself.

**Comment by markstory** [comment]
Sounds reasonable to me. Breadcrumbs are still pretty common on content heavy sites, we also have an existing implementation that could/should be replaced.

The API you've proposed looks good to me. I'm guessing the Helper would also implement the `StringTemplateTrait`

**Comment by HavokInspiration** [comment]
@markstory Yes, that is my intention. I'll update the API example in the original post to include it.

Since there seems to be an agreement, I'll start working on it.

**Comment by dakota** [comment]
Sounds like a fantastic idea to me!

**Comment by ADmad** [comment]
> By instanciating a BreadcrumbsHelper in the HtmlHelper...

Maybe I am misunderstanding what you are saying but the `BreadcrumsbHelper` should use the `HtmlHelper` not the other way round. `HtmlHelper` should only generate basic html tags IMO and not generate specialized lists like bread crumbs trial. Existing methods like `HtmlHelper:getCrumbs()` and any other methods related to bread crumbs generation should be deprecated.

**Comment by HavokInspiration** [comment]
@ADmad I meant what I said.

The idea was to have the current methods of the `HtmlHelper` generate breadcrumbs with the new `BreadcrumbsHelper` instead of the current way of doing things.

But deprecating the current methods and let them live and die until 4.0.0 might be a better idea and is good to me as well.

**Comment by HavokInspiration** [comment]
#9562 opened. Further discussions can go on there.
