### ISSUE TITLE
Request modifications in HTTP Client

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#9548]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.5

Currently `_addAuthentication`, `_addProxy` and other methods are protected, so you cannot inject pre-build `Request` object with auth/proxy. I'm working on a project where I need to allow requests to be decorated after they are built but before they are sent. Could we make these methods public? 

There's also the `_createRequest` factory method which also could be public. That would help a lot...
I'm afraid that changing methods visibility could break compatibility, but maybe we could just add some public wrapper methods for them?

**Comment by markstory** [comment]
What kind of problems with making _addAuthentication and _addProxy public help you solve?

**Comment by robertpustulka** [comment]
I've digged more into the code and I think my request is not that nessessary. I could easily build an auth adapter and modify request with that.
