### ISSUE TITLE
Cache::clear() with engine Memcached only clears part of cache

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#9549]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.3.2
- Platform and Target: memcached 1.4.17
### What you did

MemcachedEngine::clear() uses Memcached::getAllKeys() and iterates over them to clear entries for the configured prefix.  However, getAllKeys() is not guaranteed to return _all_ of the keys in the cache, and in fact seems to be limited by the configured slab size.  Thus, not all the keys are cleared.
### Expected Behavior

That Cache::clear() would in fact clear the whole contents.
### Actual Behavior

Part of the cache is cleared but not all.

No easy answer here - Because the implementation iterates over the keys looking for the cache config's prefix, it is always possible that the keys returned by getAllKeys() will not contain any of the ones with the prefix, but they are still floating around out there.  Expecting your cache to be cleared and having it be polluted with old data is bad - It affects production deployments.

**Comment by markstory** [comment]
Are there other features of the Memcached extension we can use to ensure we get all the keys?

**Comment by tharlinsmith** [comment]
Not that I'm aware of.  But I only have issues, not answers :).

**Comment by markstory** [comment]
Until we have answers, `clear()` might be a best-effort thing.

**Comment by tharlinsmith** [comment]
We've been doing some forensics, and it gets worse.  In many installations Memcached::getAllKeys() always fails and returns nothing.  There was a major rewrite of the memcached server core at 1.4.23.  This appears to be the point at which the function broke.  The current versions is 1.4.31.

Memcached is built around yet another open-source project for the C libmemcached library.  That has not had a release in 2.5 years, and perhaps has gone the way of the buffalo.  So use this package with caution.

**Comment by markstory** [comment]
Closing as there isn't much we can do given that the C extensions don't provide a reasonable way to do what is wanted here.

**Comment by inoas** [comment]
@tharlinsmith can you add a note to the [docs](https://github.com/cakephp/docs)?
