### ISSUE TITLE
CookieComponent writes bad cookie since 3.3.5

### ISSUE THREAD

**Issue by KingLoui** [cakephp/cakephp#9553]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5
* Platform and Target: NGINX, Mysql PHP-FPM.

### ISSUE

In my Application I use the CakeDC/Users plugin which provides the RememberMeComponent.
This component writes a bad cookie on login since cakephp 3.3.5. When I debug CakeDC\Users\Auth\RememberMeAuthenticate the cookie which is read is empty.

When I downgrade to cakephp 3.3.4 and do a login, the rememberme works fine, then I update to 3.3.5 and it successfully logs me in with the cookie written by 3.3.4.

**Comment by markstory** [comment]
What is wrong about the cookie? Are your cookies encrypted?

**Comment by KingLoui** [comment]
Yeah they get rsa encrypted with the app salt. I did not configure anything related to cookies, I just use cakedc users, I think the cookie encryption is default behavior. 
I checked the diff from 3.3.4 to 3.3.5 an there are some cookie related changes so I hope the bug is not on my end.

**Comment by markstory** [comment]
Are you both reading and writing cookies with the CookieComponent? The changes in 3.3.5 around cookies were specific to writes. Reading existing cookies should continue to work. I'll see if I can reproduce by reading/writing cookies via the CookieComponent in 3.3.5

**Comment by markstory** [comment]
I was able to reproduce this, and will have a fix up shortly.

**Comment by markstory** [comment]
Closing as a pull request is up.

**Comment by KingLoui** [comment]
nice, thank you for your effort! :)
