### ISSUE TITLE
timeAgoInWords locale bug?

### ISSUE THREAD

**Issue by Sensetivity** [cakephp/cakephp#9554]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.14
* Platform and Target:  Win 7x64; OpenServer (Apache 2.4 PHP: 5.6 Mysql: 5.6)

### What you did
I try to translate my site with different date format for different locales. I get problem with Ukrainian translation.

So I use next code:
`<?= (new \Cake\I18n\Time($user['created']))->timeAgoInWords(['format' => 'MMM d YYY', 'end' => '1 year', 'accuracy' => ['month' => "month"]]); ?>`

And get next text: 

> 7 місяць тому

instanceof 

> 7 місяців тому

In English locale I get normal;

> 7 months ago

Exaplaination:
Translation map from https://github.com/cakephp/localized/blob/master/src/Locale/ua/cake.po#L170:
1, 21, 31, 41 - місяць (month)
2, 3, 4, 22 -  місяці (months)
0, 5, 6, 7 - місяців (months)

### Expected Behavior
I expect recive a 

> 7 місяців тому

### Actual Behavior
See above.

**Comment by markstory** [comment]
Do pluralization rules work for other values outside of relative time formatting? For example does.

```php
echo __n('{0} month', '{0} months', $months, $months);
```

behave as you would expect given the Russian pluralization rules?

**Comment by Sensetivity** [comment]
`echo __n('{0} month', '{0} months', 7, 7);`

return 

> 7 month

**Comment by markstory** [comment]
`__n()` will only work correctly if your locale/po file have the right plural rules header. What version of libicu do you have installed? `php -i | grep ICU` will tell you which version of libicu php is linked against.

**Comment by Sensetivity** [comment]
> $ php -i | grep ICU
> ICU version => 49.1.2
> ICU Data version => 49.1.2
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by markstory** [comment]
Ok. I have libicu v 54. I'll see if I can reproduce the issue with `__n()` as a starting point.

**Comment by markstory** [comment]
I've opened a pull request with additional tests that cover the `__n()` call that the helper uses internally. All the tests pass for me locally, could you try running the updated tests locally?

**Comment by markstory** [comment]
ping

**Comment by DRuller** [comment]
$frozentime = new FrozenTime();
$frozentime = $frozentime->modify('- 59 minutes');
echo $frozentime->timeAgoInWords();
output: 159 minutes ago

**Comment by dereuromark** [comment]
Better to open a new ticket than adding this to a year old one.
