### ISSUE TITLE
TranslateBehavior - alter join type or make it configurable

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9558]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 2.8.9.
- Platform and Target: Linux, Apache, MySQL.
### What you did

When TranslateBehavior is attached to a model then INNER joins are used. This leads to empty results when the model record exists but the related translation is absent. 
### Expected Behavior

When there is no record in i18n table that is related to the current model record then the result from find() should contain the model fields without translatable column. So either INNER join should be changed to LEFT join or the join type should be configurable.
### Actual Behavior

The result is empty when there is no record in i18n table but there is a record in my_models table.

**Comment by dereuromark** [comment]
I am not sure why the INNER is the default. I agree, that in certain cases the LEFT appears to make more sense.
Let's wait on feedback from others - and maybe someone finds the time to draft a PR with the suggested improvements.

**Comment by markstory** [comment]
Closing as a pull request is open now.
