### ISSUE TITLE
PHP7 issue in 2.x branch, Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by TheSin-** [cakephp/cakephp#9559]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x (All including 2.9.0)
* Platform and Target: Apache 2

This was with 2.8.8 but tested with 2.9.0 as well, just 2.9.0 has other issues with the removal of 'Object' so I dropped back down.

```
2016-09-27 14:23:08 Error: Fatal Error (64): Cannot use 'String' as class name as it is reserved in [/var/www/cakephp-2.8.8/lib/Cake/Utility/String.php, line 26]
2016-09-27 14:23:08 Error: [InternalErrorException] Internal Server Error
Stack Trace:
#0 /var/www/cakephp-2.8.8/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Str...', '/var/www/cakeph...', 26)
#1 /var/www/cakephp-2.8.8/lib/Cake/Core/App.php(970): ErrorHandler::handleError(64, 'Cannot use 'Str...', '/var/www/cakeph...', 26, Array)
#2 /var/www/cakephp-2.8.8/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by ADmad** [comment]
The `String` class has already been deprecated and `CakeText` is provided instead to avoid error on PHP7.  There are no usages of `String` anymore in core itself, so update your app code to use `CakeText` instead of `String`.

**Comment by TheSin-** [comment]
Thanks I'll let the author know.
