### ISSUE TITLE
scaffold generated code uuid sql error

### ISSUE THREAD

**Issue by HumanG33k** [cakephp/cakephp#9576]
Not find similar bug in existing issues
 [x] bug
* CakePHP Version:  v3.3.4
* Platform and Target: 
Host :
Linux notsohuman 4.7.0-1-amd64 #1 SMP Debian 4.7.5-1 (2016-09-26) x86_64 GNU/Linux

Database : 
PostgreSQL 9.4.5

Apache 2 : 
Server version: Apache/2.4.23 (Debian)
Server built:   2016-08-12T19:44:31

PHP : 7.0.11-1

### What you did

I just want use bin/bin bake with uuid's 

I create the database :
The SQL create request for database is attach.
[create.sql.txt](https://github.com/cakephp/cakephp/files/513718/create.sql.txt)

I run following command
$path_to_project/bin/cake bake all users
$path_to_project/bin/cake bake all groups

### Expected Behavior
i expected i can use the generated code for add a user. 

### Actual Behavior
There is an sql error i found where the generation fail :

In users and groups tables :

public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('groups');
        $this->displayField('name');
        $this->primaryKey('uuid');

        $this->addBehavior('Timestamp');

        $this->belongsToMany('Users', [
            'foreignKey' => 'group_id',   ======> should be 'group_uuid'
            'targetForeignKey' => 'user_id', ======> should be 'user_uuid'
            'joinTable' => 'groups_users'
        ]);
    }

after this change everything looks work fine

**Comment by markstory** [comment]
bake uses naming conventions to infer foreign keys. Your columns do not follow the cakephp standard conventions. You'll need to edit your model definitions to be correct.

Bake does not yet support detecting column names on defined constraints. Hopefully we can add that in a future version.

**Comment by HumanG33k** [comment]
I try several options using cake name conventions ( id, uuid | uuid, varchar(36), fk_id fk_uuid ) i always have an error. maybe i'have done some mistakes but with uuid which is the good way/good standard conventions ? (sry for my en). the doc is not so clear about that (maybe just for me) : "In addition to use an auto-increment key as the primary key, you may also use UUID columns. CakePHP will create a unique 36 character UUID (CakeUtilityText::uuid()) whenever you save a new record using the Table::save() method."

**Comment by dereuromark** [comment]
char(36) is the only correct and documented one.

**Comment by markstory** [comment]
@dereuromark in 3.x we also support native uuid types when they are available.

@HumanG33k  `id` and `user_id` are convention based column names.

**Comment by HumanG33k** [comment]
So i really think there is a bug or something missing in cake bake code.
I try the convention with id, fk_id in cases with varchar(36), char(36) and uuid.

Each case have trouble : 
- id  field need to be manually enter.
- Pilots index is broken it try to find an uuid 

All screenshot show that. varchar and char have the same behavior.


![cake_erd_char_id](https://cloud.githubusercontent.com/assets/1794193/19264827/bc67f026-8fa2-11e6-9cfb-90f6f9516caf.png)
 ![cake_cars](https://cloud.githubusercontent.com/assets/1794193/19264669/f85230c0-8fa1-11e6-92e3-81e856dd4b66.png)
![cake_pilot](https://cloud.githubusercontent.com/assets/1794193/19264672/f856be60-8fa1-11e6-867a-fc584ec8e0ba.png)
![cake_pilots_index_var_id](https://cloud.githubusercontent.com/assets/1794193/19264670/f853b0e4-8fa1-11e6-9fa2-70ed3befc1ed.png)
![cake_cars_var_id](https://cloud.githubusercontent.com/assets/1794193/19264671/f8556f4c-8fa1-11e6-9df4-d474fba54666.png)
![cake_erd](https://cloud.githubusercontent.com/assets/1794193/19264668/f822f594-8fa1-11e6-8ec0-eb7934515bf8.png)
![cake_erd_var_id](https://cloud.githubusercontent.com/assets/1794193/19264673/f85b8a12-8fa1-11e6-9f87-75a31d10f751.png)


maybe i have done something wrong (again), in this case let me know.

**Comment by dereuromark** [comment]
Looks indeed like a bug, it now uses "uuid" as column name even though the actual name is "id".

**Comment by markstory** [comment]
@HumanG33k Could you provide the create table SQL you used to create those two tables with `uuid` primary columns? I'd like to try and reproduce the issue locally.

**Comment by dereuromark** [comment]
Also, was `$this->primaryKey('uuid');` also generated (from bake) or did you set this manually?
As it should be `id` from your above example SQL.

**Comment by HumanG33k** [comment]
@markstory files for you
[varchar.sql.txt](https://github.com/cakephp/cakephp/files/522385/varchar.sql.txt)
[char.sql.txt](https://github.com/cakephp/cakephp/files/522387/char.sql.txt)
[uuid.sql.txt](https://github.com/cakephp/cakephp/files/522386/uuid.sql.txt)

@dereuromark in my tests case i don't touch code i just create tables, bin/bake, try to add/view from browser. maybe some part of cache involve, i don't know.

**Comment by markstory** [comment]
I wasn't able to reproduce the problems you've been having when using the `varchar.sql.txt` file. Here is [a gist of the files bake created](https://gist.github.com/markstory/2e2f62d0ee66006ec0af32fad29edfef)

I didn't include the PilotsTable code as it was similar and also worked. One thing I didn't do was add

```sql
CREATE UNIQUE INDEX cars_id 
  ON cars (id);
CREATE UNIQUE INDEX pilots_id 
  ON pilots (id);
```

As those indexes are redundant because of the primary key which implicitly requires uniqueness.

**Comment by HumanG33k** [comment]
@markstory Ok i will retry with a fresh install and with varchar and id.

**Comment by HumanG33k** [comment]
Ok let's try @markstory 

In the first terminal
#su - postgres
postgres$ psql
CREATE USER cars WITH PASSWORD 'cars';
CREATE DATABASE cars OWNER cars;
\q
#psql -U cars -d cars
\i $path_to/varchar.sql
//NOTE the post file without the two unique indexes.
//A little verification 
\dt
          Liste des relations
 Schéma |  Nom   | Type  | Propriétaire 
--------+--------+-------+--------------
 public | cars   | table | cars
 public | pilots | table | cars

//Check car table
\d cars 
                 Table « public.cars »
 Colonne |            Type             | Modificateurs 
---------+-----------------------------+---------------
 id      | character varying(36)       | non NULL
 name    | character varying(255)      | 
 created | timestamp without time zone | 
 updated | timestamp without time zone | 
Index :
    "cars_pkey" PRIMARY KEY, btree (id)
Référencé par :
    TABLE "pilots" CONSTRAINT "fkpilots204913" FOREIGN KEY (car_id) REFERENCES cars(id)

//Now check pilots
\d pilots
                Table « public.pilots »
 Colonne |            Type             | Modificateurs 
---------+-----------------------------+---------------
 id      | character varying(36)       | non NULL
 name    | character varying(255)      | 
 created | timestamp without time zone | 
 updated | timestamp without time zone | 
 car_id  | character varying(36)       | non NULL
Index :
    "pilots_pkey" PRIMARY KEY, btree (id)
Contraintes de clés étrangères :
    "fkpilots204913" FOREIGN KEY (car_id) REFERENCES cars(id)

In second terminal 
$composer create-project --prefer-dist cakephp/app car_odb
//Note : i response Y to set folder permissions (odb for own database)


$chmod gu+w -R  tmp logs
//Note  :my user is in the www-data group
$nano -c config/app.php
//Note :  i only set up database connection (driver , username, password, database)

Now i go to check the home page --> all is green 
return in the second terminal --> let's bake

$bin/cake bake all cars -f
[..]
Bake All complete.
\\Note : no red light 

$bin/cake bake all pilots -f
[..]
Bake All complete.
\\Note : no red light 

Now i go test the app 
app/cars
look good 
![cake_car_index](https://cloud.githubusercontent.com/assets/1794193/19311390/79180968-908e-11e6-8a85-5d71bf2e648d.png)

app/car/add
One field in the form the name one. Now i click on the button
![cake_car_add](https://cloud.githubusercontent.com/assets/1794193/19311414/90acef26-908e-11e6-99d8-107931ccc5f8.png)

And :tada: 
![cake_car_add_fail](https://cloud.githubusercontent.com/assets/1794193/19311417/9653f8c0-908e-11e6-924d-2c48b82c8dbd.png)

So what now ? :smiling_imp:

**Comment by markstory** [comment]
Ok, I'll try again with Postgres. I tried the varchar(36) schema in MySQL which does not support `UUID` column types.

**Comment by HumanG33k** [comment]
@markstory i find one error in my sql script the updated field can't be null.
I will redo my test case.

**Comment by HumanG33k** [comment]
@markstory I redo my tests and for the moment for postgres the next conf work well.
name  | type
       id | uuid
FK_id  | uuid

I close and I will do some others tests case this week end. Maybe the doc need to be update. 

thx,

**Comment by markstory** [comment]
Ok.
