### ISSUE TITLE
2.x - app/View/Elements/Flash/default.ctp does not contain php delimiters

### ISSUE THREAD

**Issue by tribbie** [cakephp/cakephp#9579]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.0

When accessing an unauthorized page, the flash render method is called in my view.
Like this:
`<?= $this->Flash->render('auth') ?>`

This includes the app/View/Elements/Flash/default.ctp template.
This default.ctp template starts out with a php comment section.
However, this comment section lacks the php delimiters.
`<?php`
and
`?>`

It just starts with the  comment itself.

### What you did
Entered an url for which I am not authorized.

### Expected Behavior
I expect only the content of the flash error message.

### Actual Behavior
The php comment section is being displayed before the flash error message.

**Comment by dereuromark** [comment]
You might have an invalid PHP setup, make sure short open tags are enabled.

**Comment by tribbie** [comment]
Is use short open tags throughout my whole app. And they work perfectly.

But the **app/View/Elements/Flash/default.ctp** template in the 2.x repository (and the 2.next repository too) looks like this:

`/**`
`* CakePHP(tm) : Rapid Development Framework (http://cakephp.org)`
`* Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)`
`*`
`* Licensed under The MIT License`
`* For full copyright and license information, please see the LICENSE.txt`
`* Redistributions of files must retain the above copyright notice.`
`*`
`* @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)`
`* @link          http://cakephp.org CakePHP(tm) Project`
`* @package       app.View.Emails.html`
`* @since         CakePHP(tm) v 0.10.0.1076`
`* @license       http://www.opensource.org/licenses/mit-license.php MIT License`
`*/`
`<div id="<?php echo $key; ?>Message" class="<?php echo !empty($params['class']) ? $params['class'] : 'message'; ?>"><?php echo $message; ?></div>`


And I think it should look like this (like numerous other default.ctp templates):

**`<?php`**
`/**`
`* CakePHP(tm) : Rapid Development Framework (http://cakephp.org)`
`* Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)`
`*`
`* Licensed under The MIT License`
`* For full copyright and license information, please see the LICENSE.txt`
`* Redistributions of files must retain the above copyright notice.`
`*`
`* @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)`
`* @link          http://cakephp.org CakePHP(tm) Project`
`* @package       app.View.Emails.html`
`* @since         CakePHP(tm) v 0.10.0.1076`
`* @license       http://www.opensource.org/licenses/mit-license.php MIT License`
`*/`
**`?>`**
`<div id="<?php echo $key; ?>Message" class="<?php echo !empty($params['class']) ? $params['class'] : 'message'; ?>"><?php echo $message; ?></div>`

Sorry for the layout of the code snippets, but the "insert code" tag did not process the whole snippet well.

**Comment by dereuromark** [comment]
I see, https://github.com/cakephp/cakephp/blob/2.x/app/View/Elements/Flash/default.ctp looks inside broken.

**Comment by markstory** [comment]
Closing as the pull request has been merged.
