### ISSUE TITLE
CakePHP v2.8.9 AssertTags() doesn't work for a atached html file

### ISSUE THREAD

**Issue by bananea** [cakephp/cakephp#9582]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:  v2.8.9
* Platform and Target: Windows,apache,mysql,comand prompt tests 

### What you did
```
cake test app Controller\RestaurantProfilesController --filter=MetaDescription
```

```php
$html = $this->testAction($url, $options);
$pattern = array(
			'meta' => array(
				'name' => 'description',
				'content' => 'Lo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#039;s standard dummy text ever since the',
			)
 );
 $this->assertTags($html, $pattern);
```

### Expected Behavior
It should find the meta and assert.

### Actual Behavior
Item #1 / regex #0 failed: Open meta tag

The weird part is that if I extract the meta from html, it assert it and passes:

```
$parsed = $this->getStringBetween($html, '<meta name="description" content="', '"/>');
$metaHtml = '<meta name="description" content="' . $parsed . '"/>';
		$pattern = array(
			'meta' => array(
				'name' => 'description',
				'content' => 'Lo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#039;s standard dummy text ever since the',
		)
);
$this->assertTags($metaHtml, $pattern);
```

I seen that in Cake 3.0 it's deprecated but maybe there are some other 2.x users.
[_dk_daDK_r17_testrestappoe-57f75757d7288.txt](https://github.com/cakephp/cakephp/files/515968/_dk_daDK_r17_testrestappoe-57f75757d7288.txt)

**Comment by markstory** [comment]
assertTags() needs to assert the *entire* HTML fragment. Is your entire response a single meta tag?
