### ISSUE TITLE
Got error mkdir permission when use Folder class to create a new relative directory

### ISSUE THREAD

**Issue by sp1007** [cakephp/cakephp#9584]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest version (3.3.5).
* Platform and Target: web-server.

### What you did
I used simple code to create a new directory

```php
$fo = new Folder("mydir/", true, 0755);
var_dump($fo->errors());
```

and here is result:

```
Warning: mkdir(): Permission denied in ... Folder.php on line 637
array(1) { [0]=> string(18) "/mydir NOT created" }
```

### Expected Behavior

i need new sub directory in the current directory (php script directory).

### Actual Behavior

Got error when created sub directory.

###Should be fixed

i found that $path parameter was not checked empty value in function `addPathElement($path, $element)`. Therefore i suggest to fix this function as follows:

```php
public static function addPathElement($path, $element)
    {
        $element = (array)$element;
        if (!empty($path)) array_unshift($element, rtrim($path, DIRECTORY_SEPARATOR));
        return implode(DIRECTORY_SEPARATOR, $element);
    }
```

i hope this information is helpful for you.

**Comment by sp1007** [comment]
i've used CakePHP Version: latest version (3.3.5). :)

**Comment by markstory** [comment]
Where are you expecting that the new relative directory would be created? I'm not sure defaulting to `/` is a safe or wise choice.

**Comment by sp1007** [comment]
I supposed to create relative directory in web root.

**Comment by markstory** [comment]
Ok. I'm not entirely convinced that relative directories are something we should encourage by making them work. Is there a reason you don't want to provide an absolute path?

**Comment by sp1007** [comment]
I am trying to create uploader class for multi users which allows to create folders and files likes "webroot/files/user1/filename". The project is saved on dropbox and is synced between pc and latop. The absolute paths maybe different, so that is reason i used relative path while was testing class.

**Comment by ADmad** [comment]
The  WWW_ROOT constant  provides you the path to webroot folder for current installation so use that.

**Comment by ADmad** [comment]
I too am not in favour of supporting relative paths.

**Comment by markstory** [comment]
I too would recommend you create a constant to the 'root directory' of your upload paths, and use that to prefix your relative directories.
