### ISSUE TITLE
Extension + RequestHandlerComponent - layout subfolder is not used like expected

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#9598]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3.5

How to reproduce:
Follow the docs to create new project. Add following extension to routes:
`    $routes->addExtensions("ajax");`

Now lets invoke ````/pages/display.ajax````

### Expected Behavior
Excepton due to attempt of using view template \src\Template\Pages\ajax\display.ctp

### Actual Behavior
Excepton due to attempt of using view template \src\Template\Pages\display.ctp
notice missing **AJAX** subdirectory part

If you manually invoke ````$this->RequestHandler->renderAs($this,'ajax');```` in controller, it will work as expected.

**Comment by markstory** [comment]
The ajax 'extension' maps to the [AjaxView in the application template](https://github.com/cakephp/app/blob/master/src/View/AjaxView.php). By default this view class does not add subdirectory paths. If you want that behavior update the view class :smile:

**Comment by Antoniossss** [comment]
@markstory In general extensions make RequestHandler to invoke renderAs method with the extension as argument if viewclass for given extension is mapped. This happens in beforeRender event. Behavior changes (to desired one be me) if the exact same invocation is moved controller action execution. This looks like defect to me.

From docs 

> When used in conjunction with Cake\Routing\Router::extensions(), RequestHandler will automatically switch the layout and template files to those that match non-HTML media types.
> 
> So maybe docs are not clear enought.

**Comment by markstory** [comment]
In general the AjaxView is used for HTML based fragments, which is why the documentation is phrased that way. If you have an idea on how to better phrase that part I'm very open to changing the docs.
