### ISSUE TITLE
"fullBase" routes on tests

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9600]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5

### What you did
I'm testing routes for my plugin.  Normally, the routes work.  
The problem only occurs when I try to generate "fullBase" routes.

For example, when I do this, it works:

    Router::url($params);

and the route is resolved correctly.
But when I do this, it does not work:

    Router::url($params, true);

In that case, `phpunit` returns this:

    Cake\Routing\Exception\MissingRouteException: A route matching "/http://localhost/thumb/OWI5ODVmNjBiOTA1MjljOTJkMWQ0YWUyOTA5MzJiMGIucG5n" could not be found. in /home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:147

Where that slash appears?

The bootstrap for testing sets `App.fullBaseUrl` to `http://localhost`, as usual.

**Comment by markstory** [comment]
That exception is coming out of `Router::parse()`. I'm not sure it has anything to do with URL generation. What is the stacktrace on that error?

**Comment by dereuromark** [comment]
I had similar issues recently and it took me a while to realize that the middleware changes might require a

    DispatcherFactory::add('Routing');

in your tests/boostrap.php in order for the routing to be included.

**Comment by mirko-pagliai** [comment]
@dereuromark, [my bootstrap](https://github.com/mirko-pagliai/cakephp-thumber/blob/master/tests/bootstrap.php) already contains that.

Later I will post the complete stacktrace

**Comment by mirko-pagliai** [comment]
@markstory @dereuromark these are [my tests bootstrap](https://github.com/mirko-pagliai/cakephp-thumber/blob/master/tests/bootstrap.php), [plugin routes](https://github.com/mirko-pagliai/cakephp-thumber/blob/master/config/routes.php) and [routes for tests](https://github.com/mirko-pagliai/cakephp-thumber/blob/master/tests/test_app/config/routes.php) (the last one just loads the plugin routes).

Now a bit of code:

    
    public function testFullBase()
    {
        $thumb = (new ThumbCreator('400x400.gif'))->resize(200)->save();
        $thumb = base64_encode(basename($thumb));
        $params = ['_name' => 'thumb', $thumb];
        
        //Works
        $url = \Cake\Routing\Router::url($params);
        $this->assertEquals('/thumb/' . $thumb, $url);
        debug($url);
        $this->get($url);
        $this->assertResponseOk();
        
        //Fails
        $url = \Cake\Routing\Router::url($params, true);
        $this->assertEquals('http://localhost/thumb/' . $thumb, $url);
        debug($url);
        $this->get($url);
        $this->assertResponseOk();
    }

The first works, the second fails, but the url is the same.

Stack trace [here](http://pastebin.com/uFkcpQRh)

**Comment by dereuromark** [comment]
Why are you putting a full URL into `$this->get()`?
It should only be a relative URL, ideally even just an array of controller/action and alike.
I am pretty sure what you want to do is not part of the current test suite yet and how the integration test suite works.

**Comment by mirko-pagliai** [comment]
So that's the problem! I did not know it, sorry.  
It seems to me that the documentation does not clearly indicated.

So, thanks.

**Comment by ADmad** [comment]
> Why are you putting a full URL into $this->get()?

That's what's causing the error. Url generation is working just fine.
