### ISSUE TITLE
Login Redirect must not be set for non-GET

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9601]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:  3.3.5

### What you did
Click a postLink() and get a redirect to login (because session timed out or log out happened)

### Actual Behavior
An error screen "Method Not Allowed" after successful login because that method has a $this->allowMethod(post) set.

### Expected Behavior
Since it was a postLink() just redirecting to it afterwards is not possible, that current url should not be used to store where I was coming from. 
Either:
- We use the referrer url of where we clicked the post link (preferred)
- We discard it completely and then it will just redirect back to the login url defined (not ideal)

We should definitely only directly set the current URL for GET requests when redirecting to login.

**Comment by inoas** [comment]
The default should be a delete view action (or just delete with a template and HTTP GET) instead of the ugly popup TBH. Then one could always redirect to that.

**Comment by markstory** [comment]
> We use the referrer url of where we clicked the post link (preferred)

How are you planning on getting that? You almost need to find the last GET request which I don't think will be doable outside of tracking it in the session.

**Comment by dereuromark** [comment]
I think changing the defaults here and alike is out of scope, this should merely be a ticket to fix the annoying exception for getting re-logged in on post links.

**Comment by markstory** [comment]
How would we do that? Any route can apply and authorization or HTTP method restrictions it wants, I don't know how we would detect those things when deciding whether or not a URL can be used as a redirect target.

**Comment by dereuromark** [comment]
I would, inside the auth component, before the forced redirect to login happens, simply check on the current type of request

    if (!$this->request->is('get')) {
        // do not store this in session (or in 3.4 append as querystring)
    }

**Comment by markstory** [comment]
@dereuromark That sounds like a reasonable stop-gap solution to me.

**Comment by dereuromark** [comment]
For 3.next a PR is up.
Maybe someone has also time to patch it the session way for 3.current.

**Comment by thinkingmedia** [comment]
An action that can only receive POST requests should respond with status code 401 and not a 301.

I know that you want to have a good user experience, but that is what 401 responses are for.

You could have a 401 page render with a JavaScript code to redirect to the log in. This would solve the problem and ensure the server provides the correct response codes.

**Comment by markstory** [comment]
@thinkingmedia AuthComponent can do that through Authentication implementations. The fallback behavior is to do redirects.

**Comment by markstory** [comment]
Closing as this has been implemented for 3.4.0
