### ISSUE TITLE
[ORM] Using concat() with format()

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#9609]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: `3.3.5`
* Platform and Target: PHP `7.0.7` & MySQL `5.7.13`

### What you did
I am returning a list of data for an ajax auto-complete, which needs to be locale dependant.

```php
$fields = ['name', 'slug', 'rating', 'from_price', 'logo', 'logo_dir'];
if ($this->request->session()->read('locale') == 'GB') {
    $fields = ['name', 'slug', 'rating', 'from_price' => 'CONCAT(\'£\', FORMAT(gbp_price, 2))', 'logo', 'logo_dir'];
}

$list = $this->Hotels->find()
    ->select($fields)
    ->where(['name LIKE' => '%' . $term . '%']);
```

### Expected Behavior
My expectation is that the `from_price` field, when the locale is `GB` would be returned as `£49.99` or similar dependant on the row value.

### Actual Behavior
The `from_price` is returned as `0`

### Issue details
I have done some debugging on this issue, specifically logging the resulting entities, and also logging the queries sql. I can copy and paste the generated sql into Sequel Pro (replacing the bound value) and the query executes fine, and I get my expected results.

I have tried to poke into where the `Cake\ORM\Query` object is converted to a ResultSet to try and find out what is causing this combination to return 0, although I have struggled to figure it out. It seems to be between the sql generation and the returning of the results. 

I'll keep debugging as best I can and update this issue with anything I find.

**Comment by lorenzo** [comment]
Is `from_price` a numeric column in your database? If so I recommend using an alias for the result of that function call:

```php
'formatted_from_price' => 'CONCAT(\'£\', FORMAT(gbp_price, 2))'
```

That is the easiest way of preventing the automatic casting to number in the result

**Comment by davidyell** [comment]
Yes, it turns out after some debugging, that because the column type in the schema for the table is `float` any value will be cast to `float` in the `ResultSet`.

I've been trying to change the schema to force the field to string, so that I don't have to change my ajax success method, but I guess I have no choice here.

Thanks!
