### ISSUE TITLE
Translate behavior issue when model only contains the translated field

### ISSUE THREAD

**Issue by andrej-griniuk** [cakephp/cakephp#9610]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5
* Platform and Target: MySQL 5.6

### What you did
Create a table with only 2 fields. Let's say countries [id, name]. Bake everything. Add Translate behaviour `$this->addBehavior('Translate', ['fields' => ['name']]);` to the Table and `use TranslateTrait;` to the Entity. Go to `countries/add` and try to add a new Country with name "USA".

### Expected Behavior
New country created in countries table with "USA" name in the i18n table.

### Actual Behavior
"The country could not be saved. Please, try again.". If inspect $country in the controller - no errors there.

**Comment by markstory** [comment]
Does the original table contain both the `id` and `name` fields or only `id`?

**Comment by andrej-griniuk** [comment]
Both. 
As I understand this is what's happening: Translate behaviour marks translated fields as not dirty (https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TranslateBehavior.php#L315) then in `Table` `_insert` method $data is empty (id is null, no fields are dirty) and it returns `false`(https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1665)

**Comment by markstory** [comment]
Based on the referenced lines you're saving a model in a non-default locale as well?

**Comment by andrej-griniuk** [comment]
Nope, in the default locale.

**Comment by lorenzo** [comment]
If it's the default locale, how come there are no dirty fields? The default locale is meant to be saved in the main table

**Comment by andrej-griniuk** [comment]
Double checked, you're right, it's not the default locale. 
But this is still an issue I recon.

**Comment by lorenzo** [comment]
Do you mind writing a test case for the core? That would help greatly to investigate the issue

**Comment by andrej-griniuk** [comment]
https://github.com/cakephp/cakephp/compare/master...CakeDC:issues/9610

**Comment by markstory** [comment]
Thanks for the test @andrej-griniuk

**Comment by markstory** [comment]
Thanks for the test @andrej-griniuk. I've got a pull request up now.
