### ISSUE TITLE
RFC 3.4: Simplify Auth flash config

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9614]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5

### What you did
The Auth component flash message is not consistent with the other error flash messages.

Currently one has to either modify the Auth component:

    $this->loadComponent('Auth', ['flash' => ['key' => 'flash', 'element' => 'error']]);

or add

    echo $this->Flash->render('auth');

including a `default.ctp` flash layout here, as the normal `error.ctp` one of `$this->Flash->error()` triggered messages is not used.

### Expected Behavior
I don't quite see the need to keep this complicated. If someone wants to use a different template or key, he can do that, but the defaults should be simple and out of the box working for 80% use case - which would most likely be: Treating the auth error as a simple flash error just like any other.
The view template also doesn't have to be changed by default, and simply stay as

    echo $this->Flash->render();

**Comment by markstory** [comment]
I don't know why it was done this way, but as long as I can remember Auth has used a separate flash key. With that said I'm :+1: for making AuthComponent easier to operate.

**Comment by dereuromark** [comment]
PR is up.
