### ISSUE TITLE
Inflector not working correctly with irregular camel cased words

### ISSUE THREAD

**Issue by wilegenius** [cakephp/cakephp#9620]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.3.5
* Platform and Target: Apache, MySQL, macOS

### What you did
In bootstrap.php, I declared the following rule ('Mitglied' is the German word for a 'member' and its plural form is 'Mitglieder'):
`     Inflector::rules('irregular', [ 'mitglied' => 'mitglieder', ]); `

Then I tested the Inflector using this php script (put it in webroot/ for example):

```
<?php
require dirname ( __DIR__ ) . '/config/bootstrap.php';
use Cake\Utility\Inflector;
echo '<pre>';
echo 'singularize => ' . Inflector::singularize ( 'Mitglied' ) . "\n";
echo 'pluralize => ' . Inflector::pluralize ( 'Mitglied' ) . "\n";
echo 'singularize => ' . Inflector::singularize ( 'Mitglieder' ) . "\n";
echo 'pluralize => ' . Inflector::pluralize ( 'Mitglieder' ) . "\n";
echo 'singularize => ' . Inflector::singularize ( 'FooMitglied' ) . "\n";
echo 'pluralize => ' . Inflector::pluralize ( 'FooMitglied' ) . "\n";
echo 'singularize => ' . Inflector::singularize ( 'FooMitglieder' ) . "\n";
echo 'pluralize => ' . Inflector::pluralize ( 'FooMitglieder' ) . "\n";
echo '</pre>';
?>
```

### What happened

I get the following output:

```
singularize => Mitglied       # correct
pluralize => Mitglieder       # correct
singularize => Mitglied       # correct
pluralize => Mitglieders       # NOT correct
singularize => FooMitglied       # correct
pluralize => FooMitglieds       # NOT correct
singularize => FooMitglieder       # NOT correct
pluralize => FooMitglieders       # NOT correct
```

### Expected Behavior

In all cases, I except
```
singularize => ...Mitglied
pluralize => ...Mitglieder
```

**Comment by dereuromark** [comment]
The inflector is only able to work with English language. Please do not use it for others.
Also, you are highly adviced to also completely use English language for all code based names througout your system and rather use __() and custom routing to localize it afterwards.

**Comment by markstory** [comment]
@dereuromark He has loaded custom inflection rules though.

With that said pluralizing a plural form will always result in incorrect results as we don't check if a word is plural before pluralizing as it is generally not possible.

Lastly if you are defining custom rules and prefixing the irregular words you'll need to define an irregular for all prefixed forms you want inflected.
