### ISSUE TITLE
HtmlHelper method to make PHP variables available in JavaScript

### ISSUE THREAD

**Issue by cjquinn** [cakephp/cakephp#9627]
* [x] enhancement

* CakePHP Version: 3.x

### Problem to solve

I often find myself dumping PHP variables on the page to make them available to JavaScript, the most common example being needing access to the CSRF token. I know you can use `scriptBlock` but this feels a bit clunky.

### Suggested solution

Create a method that takes the intended JavaScript variable name and the PHP variable:

`$this->Html->addScriptVar('_csrfToken', $this->request->param('_csrfToken'))`

You could add multiple script vars and they would be collated and could be echoed  with something like:

```
<?= $this->Html->scriptVars() ?>
<!-- example output -->
<script type="text/javascript">
    var _csrfToken = 'value of $this->request->param('_csrfToken')';
</script>
```

Thoughts? It would be quite cool if the `CsrfComponent` added a script var automatically as well!

**Comment by inoas** [comment]
I think there is `pj()`?

**Comment by cjquinn** [comment]
Doesn't `pj()` just `json_encode` the variable and wrap it in `<pre>` tags? http://api.cakephp.org/3.0/function-pj.html

**Comment by inoas** [comment]
It does http://api.cakephp.org/3.0/source-function-pj.html#148-167
I am just not sure I would want this, there was some support for FirePHP and Firebug in 2.x where you could post variables to the browsers console.log that way.

**Comment by inoas** [comment]
As for the concrete csrf I think it could be something like <?= $this->Html->meta('csrf') ?> which yields a meta tag which you can then read. See how RoR does it.

**Comment by cjquinn** [comment]
Using a meta tag for CSRF makes sense but for other use cases like bootstrapping a JavaScript heavy application I feel this could be useful. I don't think I've had a single project where making a PHP variable available to JavaScript wasn't required either.

**Comment by inoas** [comment]
I am not sure about security, but it could in addition be send as a custom http header that matches the html head meta keyname

**Comment by thinkingmedia** [comment]
This is a good feature, but it needs a way to define the wrapping JS for the code block. Instead of just placing the vars into the global space. I also think this would go into a JS helper and we keep the Html helper related to just the DOM.

**Comment by cjquinn** [comment]
Keeping variables out of global scope was definitely something I thought of, it could be as simple as a base object (defined in `app.php`) that all variables are properties of.

```
// app.php
[
    'scriptVarsBase' => 'CakePHP'
]
```

```
<!-- example output -->
<script type="text/javascript">
    var CakePHP = {
        _csrfToken: 'value of $this->request->param('_csrfToken')'
    };
</script>
```

**Comment by thinkingmedia** [comment]
I think the key would be to provide support for a template wrapper. That way you could inject the variables into React, Angular, jQuery or what ever library you are using.

**Comment by cjquinn** [comment]
I haven't done much work with React or Angular, could you provide an example of how you inject PHP variables?

**Comment by thinkingmedia** [comment]
Well, it's just a chunk of JS that you run in the page to pass data to a JS app.

This is how I set the current user.

```
    (function (app) {
        app.run([
            'cgUserService',
            function(cgUserService) {
                cgUserService.setUser(<?=json_encode($js_user)?>);
            }
        ]);
    })(angular.module('App'));
```

It could be anything really. Like setting constants or other data. 

The point is that developers will want to inject the PHP variables into a JS function and not just assign them to the global space. So I think you would need to define a template or something for it.

Which can already be done easily with an element.

**Comment by cjquinn** [comment]
This is true, you could definitely accomplish the above using existing functionality. So I suppose the question is, is it a common enough problem that it merits implementing helpers/a framework?

**Comment by markstory** [comment]
Given the various ways that people need to bootstrap their client side apps, I don't think there is going to be a one-size fits all solution here.

**Comment by ADmad** [comment]
I agree with @markstory. This is best done through a community plugin.

**Comment by stmeyer** [comment]
Maybe you can use https://github.com/scherersoftware/cake-frontend-bridge

Add the component to your controllers and use function `setJson` https://github.com/scherersoftware/cake-frontend-bridge/blob/master/src/Controller/Component/FrontendBridgeComponent.php#L72`

Add the ViewHelper https://github.com/scherersoftware/cake-frontend-bridge/blob/master/src/View/Helper/FrontendBridgeHelper.php

In your layout add in HTML head
```php
if (isset($frontendData)) {
    $this->FrontendBridge->init($frontendData);
    echo $this->FrontendBridge->run();
}
```

**Comment by cjquinn** [comment]
Yeah the more I think about it the less likely I think it will be that there is a one-size fits all solution. I do feel like there might be some common ground utility though, but that might just be that every one uses `json_encode` to dump variables on the page!

**Comment by markstory** [comment]
Cool, I'm going to close this issue :smile:
