### ISSUE TITLE
Cakephp3 Controller Class namespace iteration

### ISSUE THREAD

**Issue by vttn** [cakephp/cakephp#9629]
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3+

Can it be possible to configure additional namespaces for Controllers.

I understand is it possible to add folders that Controllers might reside in via 
1. composer.json
2. plugins
3. fallback is cakephp core

What I would like to do is iterate through namespaces for a controller class. 

Lets say the application can not find MyController under App/Controller namespace, I would like to look for the controller class under App2/Controller namespace.

Thanks

**Comment by markstory** [comment]
That is not possible with out of the box components. You can support this scenario by implementing your own `ControllerFactory` and injecting it into the `ActionDispatcher` via the `getDispatcher()` method in your `Application` class. See [here for the default implementation you would need to replace](https://github.com/cakephp/cakephp/blob/master/src/Http/BaseApplication.php#L94-L97)
