### ISSUE TITLE
Make RouteBuilder prefix() accept $params

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#9631]
* [x] enhancement

* CakePHP Version: 3.3.6

### What happened
Actually the method [prefix()](http://api.cakephp.org/3.3/class-Cake.Routing.Router.html#_prefix) of class [Router](http://api.cakephp.org/3.3/class-Cake.Routing.Router.html) accepts *$params* while the [prefix()](http://api.cakephp.org/3.3/class-Cake.Routing.RouteBuilder.html#_prefix) method of class [RouteBuilder](http://api.cakephp.org/3.3/class-Cake.Routing.RouteBuilder.html) does not. Is this behavior intentional for any reason? Should we adopt it in RouteBuilder?

**Comment by thinkingmedia** [comment]
I think this is a valid issue.

To change the prefix signature would break backwards compatibility. So should this be done for Cake 4 or 3.next?

**Comment by andtxr** [comment]
Through the tests that I did I think it is possible to implement the new method signature without break backwards compatibility. The Router prefix method accepts $params as a optional choice replacing it by the callback argument.  Right now the absence of $prefix argument brings the impossibility of handle named routes for example. Let's see what others have to say.

**Comment by thinkingmedia** [comment]
You can open a PR for this if won't break backwards comp. I understand what you mean by it being optional. I took another look.

**Comment by dereuromark** [comment]
PR now open.
