### ISSUE TITLE
CakeSession::delete() unable to delete on empty string

### ISSUE THREAD

**Issue by mlingureanu** [cakephp/cakephp#9632]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9
* Platform and Target: windows / linux.

### What you did
unable to delete from session if key is empty string.

### What happened

```
array(
	'Config' => array(
		'userAgent' => '032f9a496490bfe57f2801bc442a0367',
		'time' => (int) 1476978059,
		'countdown' => (int) 10,
		'language' => 'da-dk'
	),
	'loc_ls' => array(
		'id' => '1',
		'name' => 'da-DK',
		'ccode' => 'dan',
		'iso' => 'da',
		'locale_win' => 'Danish_Denmark.1252'
	),
	'' => array(
		'calendarInfo' => array(
			'booking_date' => '2022-01-04',
			'booking_caldate' => '2022-01-04',
			'booking_time' => '20:15',
			'booking_type' => 'current',
			'booking_area' => '1',
			'booking_pax' => '2',
			'booking_length' => (int) 135
		),
		'restaurantId' => (int) 17,
		'partnerId' => (int) 8
	)
)
```
this is what CakeSession::read() returns

### Expected Behavior
The problem is CakeSession::delete('') it's not working

**Comment by dereuromark** [comment]
This problem also exists in current 3.x, the empty() thing again:
https://github.com/cakephp/cakephp/blob/master/src/Network/Session.php#L358

Better to use `strlen($x) > 0` or `=== null` etc.

**Comment by thinkingmedia** [comment]
True that it checks empty but it also will not write the value if it's empty.

https://github.com/cakephp/cakephp/blob/master/src/Network/Session.php#L430

**Comment by markstory** [comment]
I can get this fixed for 2.x, and then 3.x as it seems like an issue in both branches.

**Comment by dereuromark** [comment]
PR open for 2.x, will need 3.x porting then afterwards.
