### ISSUE TITLE
`formatResults` on belongsToMany doesn't apply to results

### ISSUE THREAD

**Issue by jeremyharris** [cakephp/cakephp#9634]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.6

### What you did

Added a callback to a belongsToMany query's `formatResults`.

### What happened

The callback never fires. I modified the test case that supposedly tests this feature to actually test it. The test case didn't actually test that the callback fires. Here's the failing test commit: https://github.com/jeremyharris/cakephp/commit/02f5af9ca7717a900e3011d05688ac40f0b3f6ca

You can place a `die` statement in that callback and see that it will never get called.

### Expected Behavior

`formatResults` to work on belongsToMany.

I'd submit a PR but I spent a few hours trying to figure out why and couldn't. Perhaps someone could point me in the right direction?

**Comment by markstory** [comment]
I would probably start looking in the `BelongsToMany::attachTo()` and `BelongsToMany::eagerLoader()` as that is where the queries for the association are created/joined.

**Comment by jeremyharris** [comment]
Thanks for giving me a starting point. This one took me a while to understand and figure out regardless 😄

**Comment by markstory** [comment]
Closing as a pull request is open now.
