### ISSUE TITLE
RFC - Make Response PSR7 compliant

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#9636]
Continuing the PSR7 request work started in #9325, we will also need to update the Response class to implement the `Psr\Http\Message\ResponseInterface`. In doing so, we can make CakePHP completely PSR7 compliant.

In the long term, being compatible with PSR7 will allow users of CakePPH to leverage middleware and HTTP related logic from outside CakePHP, and hopefully make CakePHP more appealing to developers experienced in other PSR7 compliant frameworks but who are looking for a more RAD experience.
### Interface Implementation

The bulk of the interface implementation has been completed in #9597. Beyond that pull request there is still work to be done around normalizing method names and deprecating existing features.
### Deprecations

Because the PSR7 interfaces define many of the low-level methods for dealing with HTTP messages we can deprecate many of our existing methods that overlap with the interface. The following methods will become deprecated in 3.4.0
- `send()` Responses no longer send themselves. Emitters deliver responses.
- `sendHeaders()` same reason as `send()`.
- `_sendHeader()` same reason as `send()`.
- `_sendContent()` same reason as `send()`.
- `_sendFiles()` same reason as `send()`.
- `_setCookies()` same reason as `send()`.
- `_setContent()` same reason as `send()`.
- `_setContentType()` New helper methods will be introduced to make setting the Content-Type header easier.
- `header()` It overlaps the PSR7 interface methods.
- `body()` It overlaps the PSR7 interface methods.
- `statusCode()` It overlaps the PSR7 interface methods.
- `httpCodes()` This method should no longer be needed now that we support all standards recommended status codes.
- `protocol()` It overlaps the PSR7 interface methods.
- `stop()` It would be obsolete.
### Immutable Helper Methods

We currently provide a number of 'helper' methods that make it simple to set related sets of headers in a single function call. For example `disableCache()` or `location()`. These methods should have immutable variants added and have their in-place mutation version deprecated.
- `location()` would become `withLocation()`
- `disableCache()` would become `withDisabledCache()`
- `type()` would become `withType()`
- `charset()` would become `withCharset()`
- `cache()` would become `withCache()`
- `modified()` would become `withModified()`
- `expires()` would become `withExpires()`
- `sharable()` would become `withSharable()`
- `maxAge()` would become `withMaxAge()`
- `vary()` would become `withVary()`
- `etag()` would become `withEtag()`
- `compress()` would become `withCompression()`
- `length()` would become `withLength()`
- `mustRevalidate()` would become `withMustRevalidate()`
- `notModified()` would become `withNotModified()`
- `cookie()` would become `withCookie()`
- `file()` would become `withFile()`
- `download()` would become `withDownload()`

### Removal of ResponseTransformer

Once the Response object implements the PSR7 interface, we can remove the `ResponseTransformer` saving both time and complexity as responses will no longer be transformed twice per request.
### Relocate Response

Once the development work on `Response` has mostly finished, the class will be moved to `Cake\Http\Response` and a backwards compatible alias will be included. We could also theoretically deprecate `Cake\Http\Client\Response` as we could use `Cake\Http\Response` in its place.

**Comment by lorenzo** [comment]
This looks like a great plan. When would the deprecated methods be removed?

**Comment by markstory** [comment]
@lorenzo Not until 4.x

**Comment by ADmad** [comment]
@markstory Apart from deprecating `Cake\Http\Client\Response` is anything else left for this RFC?

**Comment by markstory** [comment]
Nope!
