### ISSUE TITLE
Cakephp 3.x OR condition in join does not work

### ISSUE THREAD

**Issue by edvano** [cakephp/cakephp#9637]
CODE

    $query = $this->Client->find()
                ->hydrate(false)
                ->limit($limit)
                ->page($page)
                ->select(['Client.id','Client.achternaam','Client.Voornaam','clvsstatus.clientopnamestatus_id',
                    'clstatus.naam','afd.afdeling_naam','clsrtopn.naam'])
                ->join([
                    'clvsstatus' => [
                        'table' => 'client_vs_clientsoortstatus',
                        'type' => 'INNER',
                        'conditions' => [
                            'clvsstatus.client_id = client.id',
                            'clvsstatus.datum_van <='=>'2016-10-21',
                            'clvsstatus.datum_tot >='=>'2016-10-21',
                            'OR' => ['clvsstatus.datum_tot'=>'0000-00-00']                            
                        ],
                    ],
                    'clstatus' => [
                        'table' => 'clientsoortstatus',
                        'type' => 'INNER',
                        'conditions' => 'clstatus.id = clvsstatus.clientopnamestatus_id',
                    ],
                    'clvsafdeling' => [
                        'table' => 'client_vs_afdeling',
                        'type' => 'INNER',
                        'conditions' => [
                            'clvsafdeling.client_id = clvsstatus.client_id',
                            'clvsafdeling.client_id = clvsstatus.client_id '
                            ],
                    ],                    
                    'afd' => [
                        'table' => 'afdeling',
                        'type' => 'INNER',
                        'conditions' => 'afd.afdeling_afdelingid = clvsafdeling.afdeling_id',
                    ],                    
                    'clvssrtopn' => [
                        'table' => 'client_vs_clientsoortopname',
                        'type' => 'INNER',
                        'conditions' => 'clvssrtopn.client_id = client.id',
                    ],                    
                    'clsrtopn' => [
                        'table' => 'clientsoortopname',
                        'type' => 'INNER',
                        'conditions' => 'clsrtopn.id = clvssrtopn.clientopnamesoort_id',
                    ]                                                     
                    
                ]) ;

RESULTING SQL

```
SELECT 
  Client.id AS `Client__id`, 
  Client.achternaam AS `Client__achternaam`, 
  Client.Voornaam AS `Client__Voornaam`, 
  clvsstatus.clientopnamestatus_id AS `clvsstatus__clientopnamestatus_id`, 
  clstatus.naam AS `clstatus__naam`, 
  afd.afdeling_naam AS `afd__afdeling_naam`, 
  clsrtopn.naam AS `clsrtopn__naam` 
FROM 
  client Client 
  INNER JOIN client_vs_clientsoortstatus clvsstatus ON (
    clvsstatus.client_id = client.id 
    AND clvsstatus.datum_van <= '2016-10-21' 
    AND clvsstatus.datum_tot >= '2016-10-21' 
    **AND clvsstatus.datum_tot = '0000-00-00'**
  ) 
  INNER JOIN clientsoortstatus clstatus ON clstatus.id = clvsstatus.clientopnamestatus_id 
  INNER JOIN client_vs_afdeling clvsafdeling ON (
    clvsafdeling.client_id = clvsstatus.client_id 
    AND clvsafdeling.client_id = clvsstatus.client_id
  ) 
  INNER JOIN afdeling afd ON afd.afdeling_afdelingid = clvsafdeling.afdeling_id 
  INNER JOIN client_vs_clientsoortopname clvssrtopn ON clvssrtopn.client_id = client.id 
  INNER JOIN clientsoortopname clsrtopn ON clsrtopn.id = clvssrtopn.clientopnamesoort_id 
LIMIT 
  15 OFFSET 0 
````
Always get AND condition

**Comment by AD7six** [comment]
The error is in how that conditions array is being constructed,  the array key "OR" is effectively used to implode the array values it contains, [here's a reference](http://stackoverflow.com/a/18961237)

To get an OR query with what's in the question you'd write:

```
$conditions = [
    'OR' => [
        [
            'clvsstatus.client_id = client.id',
            'clvsstatus.datum_van <='=>'2016-10-21',
            'clvsstatus.datum_tot >='=>'2016-10-21'
        ],
       'clvsstatus.datum_tot'=>'0000-00-00'             
    ]           
];

Which would generate:

```
WHERE (
    clvsstatus.client_id = client.id 
    AND clvsstatus.datum_van <= '2016-10-21' 
    AND clvsstatus.datum_tot >= '2016-10-21' 
    ) 
    OR <-
    clvsstatus.datum_tot = '0000-00-00'
```

**Comment by edvano** [comment]
Thanks AD7six, works now. However not so good explained in de cake php 3.X docs (section querybuilder)

**Comment by AD7six** [comment]
@edvano can you please propose an edit to whatever part of the docs you did not find clear (or at the very least indicate what bit you're referring to). I don't think [that page in the docs](http://book.cakephp.org/3.0/en/orm/query-builder.html#advanced-conditions) is unclear, but it's also not the bit relevant to your question afaik.

**Comment by edvano** [comment]
Andy,
At the end I used you solution in the where condition. To answer your question about the cake 3.0 documentation **Advanced Conditions in the query builder section** the above example on how to implement AND & OR conditions are explaned using andWHere or orWhere or use functions , however your approach is not documented en far more effective to encode.
