### ISSUE TITLE
latitude/longitude validation disallows 0

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp#9648]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: not relevant.

### What you did
I found the equator is not allowed as latitude

### What happened
look here:
http://api.cakephp.org/3.3/source-class-Cake.Validation.Validation.html#48
https://regexper.com/#%5B-%2B%5D%3F(%5B1-8%5D%3F%5Cd(%5C.%5Cd%2B)%3F%7C90(%5C.0%2B)%3F)

### Expected Behavior
0 is the equator and should be allowed as a valid latitude.

Suggestion:
/^(\+|-)?(?:90(?:(?:\.0{1,10})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,10})?))$/
https://regexper.com/#%2F%5E(%5C%2B%7C-)%3F(%3F%3A90(%3F%3A(%3F%3A%5C.0%7B1%2C10%7D)%3F)%7C(%3F%3A%5B0-9%5D%7C%5B1-8%5D%5B0-9%5D)(%3F%3A(%3F%3A%5C.%5B0-9%5D%7B1%2C10%7D)%3F))%24%2F

**Comment by dereuromark** [comment]
Shouldn't it be float `0.0` technically? 0 would be integer which it can't be.
But I agree, float 0 should definity also be valid. And `null` would be the "not exists" value.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. I added tests in 2ca8fe142b96cbc6ceb7fafa9bb6bd0de300b730 and all the variants of `0` that I could imagine all passed validation. What specific value was causing you trouble?

**Comment by markstory** [comment]
Ok.
