### ISSUE TITLE
Docker, Cake 2.9 and PHPUnit 3.7: PHPUnit/Autoload.php not found

### ISSUE THREAD

**Issue by carstenbaumhoegger** [cakephp/cakephp#9651]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.0
* Platform and Target: Docker Image: php5 with installed PHPUnit 3.7.38

### What you did
I tried to setup unit tests using GitLab docker Runner with a Cake 2.9 application running in a Docker container that is based on the php5 image.

After reading [this](https://github.com/cakephp/cakephp/issues/3185) issue I made sure to install the latest PHPUnit 3.7 version (3.7.38).
By calling `phpunit --version` I make sure that exactly this version is installed before running the actual tests.

I call the tests like this `lib/Cake/Console/cake test app`

### What happened
```
Warning Error: include(): Failed opening 'PHPUnit/Autoload.php' for inclusion (include_path='.:/usr/local/lib/php') in [/builds/zb2/kswf/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 162]

Error: Please install PHPUnit framework v3.7 (http://www.phpunit.de)
#0 /builds/zb2/kswf/lib/Cake/Console/ShellDispatcher.php(211): TestShell->initialize()
#1 /builds/zb2/kswf/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 /builds/zb2/kswf/lib/Cake/Console/cake.php(54): ShellDispatcher::run(Array)
#3 {main}
```

CakePHP says that PHPUnit 3.7, that is already installed inside the container, should get installed to run the tests.

### Expected Behavior
Cake runs my defined unit tests through PHPUnit

**Comment by markstory** [comment]
Are you certain that PHPUnit is installed on the `include_path` of `include_path='.:/usr/local/lib/php'` or via composer?

**Comment by carstenbaumhoegger** [comment]
I installed PHPUnit by copying the .phar as documented in the Cake2 Cookbook [here](http://book.cakephp.org/2.0/en/development/testing.html)

This is the Dockerfile I'm using

```
FROM php:5

RUN apt-get update -y

RUN apt-get install -y wget

RUN sh -c 'wget -c https://phar.phpunit.de/phpunit-3.7.38.phar -O phpunit.phar && chmod +x phpunit.phar && mv phpunit.phar /usr/local/bin/phpunit'
```
So there's no usage of composer

**Comment by markstory** [comment]
The docs mention to

> Make sure /usr/local/bin is in your php.ini file’s include_path:

It doesn't look like that's been done. You should also consider putting the phar in one of your [application's vendor directories](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php#L154-L160)

**Comment by carstenbaumhoegger** [comment]
Looks like I've missed that line, sorry about that :(

Now everything runs as expected.

Thanks for the fast and great feedback!
