### ISSUE TITLE
columnType JSON > field is null

### ISSUE THREAD

**Issue by mamatopian** [cakephp/cakephp#9652]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.3.6
- Platform and Target: Apache2, MySql, PHP7.0.11
### What you did

I have 3 tables:

``` sql
CREATE TABLE `integrations` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
   /* fields... */
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `projects` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) DEFAULT NULL,
  /* fields... */
  PRIMARY KEY (`id`),
  KEY `company` (`company_id`),
  CONSTRAINT `company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project_integrations` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `integration_id` int(11) NOT NULL,
  `settings` text, /* <<<<<<< -------- JSON */
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

``` php
class ProjectsTable extends Table
{
    public function initialize(array $config)
    {
       ....
        $this->hasMany('ProjectIntegrations', [
            'foreignKey' => 'project_id'
        ]);
       ....
    }
}

class IntegrationsTable extends Table
{
    public function initialize(array $config)
    {
       ....
        $this->hasMany('ProjectIntegrations', [
            'foreignKey' => 'integration_id'
        ]);
       ....
    }
}
class ProjectIntegrationsTable extends Table
{
   protected function _initializeSchema(Schema $schema)
    {
        $schema->columnType('settings', 'json');
        return $schema;
    }
    public function initialize(array $config)
    {
       ....
        $this->belongsTo('Projects', [
            'foreignKey' => 'project_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Integrations', [
            'foreignKey' => 'integration_id',
            'joinType' => 'INNER'
        ]);
       ....
    }
}
```

Field `Integration.settings` contains JSON data in text format.
### What happened

when
`json_encode($this->integrations)`

Getting:

``` json
[{"id":1,"project_id":1,"integration_id":1,"settings":null,"enabled":1,"integration":{"id":1,"integration_category_id":1,"name":"Bitbucket","enabled":true}}]
```

When `columnType` not applied getting:

``` json
[{"id":1,"project_id":1,"integration_id":1,"settings":"{\"service\":\"Bitbucket\",\"settings\":\"username\":\"*****\",\"password\":\"*****\",\"repository\":\"test\",\"isFeatureField\":\"extra\"}}","enabled":1,"integration":{"id":1,"integration_category_id":1,"name":"Bitbucket","enabled":true}}]
```
### Expected Behavior

``` json
[{"id":1,"project_id":1,"integration_id":1,"settings": { "service":"Bitbucket","settings":{"username":"*****","password":"*****","repository":"test","isFeatureField":"extra"}},"enabled":1,"integration":{"id":1,"integration_category_id":1,"name":"Bitbucket","enabled":true}}]
```
### EDIT:

After a while I figured out that JSON in `settings` field is malformed and everything is working now. I would appreciate feature that would throw Exception when JSON is malformed.

**Comment by markstory** [comment]
So are you looking for an exception when the `JsonType` encounters an error when unpacking the data in a JSON column?

**Comment by thinkingmedia** [comment]
JSON has a requirement that it can only be of two types. An Array or an Object. Now, we can assign `false` to a JSON field if it could not be decoded.

You can't throw an exception when reading data unless it's a fatal error. Otherwise you block the reading of that read.

**Comment by ndm2** [comment]
@thinkingmedia `false` is valid JSON too. Valid values are numbers, strings, array structures, object structures, `null`, `true` and `false`.

Throwing an exception doesn't sound too bad IMHO, other types are doing it too. I'd neither want to be surprised with invalid data on read, nor on write.

**Comment by markstory** [comment]
Throwing an exception makes reading data pretty difficult though. For example you have a bug, bad data gets into the database and then you can't read records out anymore. I would be on-board with logging an error.

**Comment by thinkingmedia** [comment]
Guys, I know I'm right about this. JSON can only be an Array or Object. Yes, it can include other primitive types, but when JSON is used as storage it can only be an Array or Object.

http://www.json.org/

> JSON is built on two structures:
> A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
> An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.

Also, according to the RFC 4627 specs.

> A JSON text is a serialized object or array.

http://www.faqs.org/rfcs/rfc4627.html

Now you can encode a primitive like this `json_encode(false)` and get a string `false`, but that is not a valid JSON string. JSON validation requires that the first character be a `[` or `{`.

**Comment by ndm2** [comment]
@thinkingmedia Most major implementations out there today already follow https://tools.ietf.org/html/rfc7159 respectively http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf. Given that all major browsers (ie ECMA implementations), Node, jQuery, PHP, Python, .NET, Go, Swift, etc already support 7159/404s JSON Text definitions (some do even go further and support `NaN`, `Infinity`, etc), this has already become the quasi-standard.

While it would for sure be convenient to use `false` to indicate a failure in this case, I don't think it's good idea to ignore the widespread support of 7159/404s definition at this point in time.

**Comment by ADmad** [comment]
While the current JsonType implementation doesn't suite my needs either it's the correct one considering the references @ndm2 has provided and the implementations in other languages.

I just made my out type class class. Perhaps we too could have a separate class which only handles objects and arrays.

**Comment by thinkingmedia** [comment]
>   A JSON text is a serialized value.  Note that certain previous  specifications of JSON constrained a JSON text to be an object or an array.  Implementations that generate only objects or arrays where a   JSON text is called for will be interoperable in the sense that all implementations will accept these as conforming JSON texts.

Well, that sucks.

So who wants to do the PR?

**Comment by amirmamaghani** [comment]
What about throwing exception in form of JSON serialised Exception in place of column data? I think this is processable by javascript and also enough informative for developers. Something like
```column: { "_error": "JSONSerializationException", "message": "..." }``` . This would be pretty handy ..

**Comment by dereuromark** [comment]
Do we want to do sth here? Seems to become stale.

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
