### ISSUE TITLE
RFC 3.4: Allow strict save() call that throws exception.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9653]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
### What you did

This has come up a lot in the past, and I also happen to have been blind-sighted by it:

``` php
// void method
...
$this->ModelName->save($entity);
```

Now one would expect this to save, and it probably does.
But at any point in the future with modified validation and rules this might not.
And it will give no indication and just silently do nothing.
### Current fix

This is sure the OK case for validation inside forms. But if you have non-validation code, e.g. in CLI calls, in important business logic etc, you definitly do not want those silent no-ops.

So that is probably what most do, they wrap it everywhere:

``` php
// void method
if (!$this->ModelName->save($entity)) {
    throw new \Exception('Could not save ModelName: ' . print_r($entity->errors(), true));
}
```

So that at least in those cases where failing would at no point be acceptable it will notify the developer and user early on.
### Core solution?

So this can get a bit annoying to repeat all over again, can this maybe be wrapped as core functionality? I bet many others would also prefer sth like:

``` php
// void method
...
$this->ModelName->save($entity, ['strict' => true]);
```

We could also use `'exception' => true/false` (default false for BC) or some other speakable word.
Feedback?

//EDIT
Same issue for delete and the case of rules going bad:

``` php
if ($options['checkRules'] && !$this->checkRules($entity, RulesChecker::DELETE, $options)) {
    return false;
}
```

Can lead to a silent "It looks like it deleted something, actually nothing changed though" scenario.

**Comment by markstory** [comment]
I don't think validation failing is an 'exceptional' case though. Its 'normal' operation for both an application and an ORM. Are you wanting exceptions because it makes flow control simpler as you don't need to check return values?

**Comment by dereuromark** [comment]
Exactly. There are usually more flow control use cases in my experience than CRUD validation operation.
In in those, especially if nested, it is pretty much impossible to track the return values all the way of the chain of execution. Here we do need the exceptions, but we even more need them where you can't feasibly do returns and check everywhere for them (void methods or CLI scripts or alike). 

So even if this is a 50/50 use case for those two, I think it is worth adding a good way in the core here.
The "exception" or "strict" key is one option, maybe there is some other good one?

**Comment by markstory** [comment]
> Here we do need the exceptions, but we even more need them where you can't feasibly do returns and check everywhere for them

I don't buy that argument. There are entire languages with no exceptions, and people are pretty productive with those tool chains. I worry that adding more 'modes' into already complex code is going to exacerbate the issue.

**Comment by dereuromark** [comment]
So what would you propose here to avoid the many lines of glue code necessary to catch those exceptions and not just silently not saving (without any feedback usually then)?

**Comment by markstory** [comment]
I'm not sure. Internally we could convert to exceptions, and then return false if the new mode is disabled, or rethrow if it is on?

**Comment by inoas** [comment]
I don't think these changes should go into 3.4. I think when you want to rebuild "the under the hood code" to work on exceptions for flow control rather than return values, that is something that can be done for 4.0 (imho), if at all. I am also worried about consistency. If throwing exceptions is the common method for one part of the framework it should be consistently applied?

p.s.: I also came to like array/list returns where you send along a status and messages and data package having looked a bit into Elixir.

**Comment by dereuromark** [comment]
Why not 3.4? It would be fully BC for 3.x as addition.

**Comment by inoas** [comment]
Mainly because PSR-7 was enough disturbance in the force of the 3.x lifecycle IMHO.
However PSR-7 hopefully yields a lot of benefits, especially if 3.x lives long and prospers - e.g. being able to mix-and-match PSR-7-community-libs and CakePHP3. Also I'd love things to be consistent. You can always patch `save()` and `validate()` for yourself, if you just want "those" to throw exceptions but the rest of the core work almost only with return values.

**Comment by dereuromark** [comment]
That's All completely off the point :)

**Comment by dereuromark** [comment]
If there is no further feedback moving towards a more strict core approach as **opt-in** I will move this to a plugin solution then.

**Comment by dereuromark** [comment]
OK, I released this as plugin solution in Shim: https://github.com/dereuromark/cakephp-shim/releases/tag/1.4.0
Feel free to close then if there is no interest in moving it into the core.

**Comment by ADmad** [comment]
I am :-1: on adding it to core.

**Comment by ravage84** [comment]
:-1: I think it's a misuse of exceptions, though I see where you are coming from...

**Comment by dereuromark** [comment]
Misuse of exception? That is as wrong as it gets. That is proper use of exception. Not to be caught exceptions.

**Comment by thinkingmedia** [comment]
I have over the last year spent much time developing Shell tasks that perform long/complex database operations without human monitoring.

As it stands, the core is very soft in handling of DB errors/validation errors. So I wrote a class that I use to handle transactions/save/create for all DB operations on the Shell.

I hope you guys will see this as a living example of what people have to do in the wild to accommodate the way that the ORM softly fails in an environment where strict execution is required. 

Throwing of exceptions is the one way to capture this failure in the logs. It allows my worker classes to catch deep errors and output them to the logs.

Here is the code:

https://gist.github.com/thinkingmedia/8e0f39a72dfdea8ca51ced987c13764c

**Comment by dereuromark** [comment]
I am 100% with @thinkingmedia - people have to do some actual coding to know the issues involved here.
Seems like @ravage84 might not have yet, otherwise he would understand that "misuse" is absolutely the wrong conclusion drawn, as well as "data validation" not part of any of the above topic.
It is about sane and safe database operations outside of the normal validation cycle of CRUD - as I clearly pointed out before.

**Comment by lorenzo** [comment]
I do not think this is a good idea, but I could give it a more serious look if this issue described the interactions with the rest of the system. Like what about exceptions for automatic association saving? What about behaviors, do they lose their state one the exception is thrown?

Then comes the usability problem. What do we show the end user on a uncaugjt validation exception?

Would it maybe be better to have a code analyzer checking for unchecked save calls?

**Comment by dereuromark** [comment]
You wouldn't use it for any user scenario.
You would use it for backend and CLI operations that otherwise would need the mentioned "if (!save) abort manually" part all the time.
There and only there we would want to go stricter as wrapper for more data security.

And yeah, behaviors and everything would immediately abort, since this is a "fatal system fault" and aborts completely at this point - compared to "silently moving on" and potentially storing inconsistent data, or operating on half broken data.

**Comment by lorenzo** [comment]
In that case I think it is better to have a static analyzer telling you what you missed

**Comment by thinkingmedia** [comment]
Here are the problems that I ran into:

- You can not overload the `save` function in your abstract `AppTable` class, because you might be handling a web request or a CLI operation. So a *make save strict* always doesn't work.
- throwing an exception is correct when you need to exit a call stack and jump to a handler, but in a controller's action there is often very little code to worry about.
- Using a static method (as per my code sample) creates the problem of re-usable code. You can no longer have a general `saveDocument()` method used by both CLI and web requests in a model class.
- current events in the ORM are very optimistic. `beforeSave` and `afterSave` but no `failureSave`.

**Comment by dereuromark** [comment]
The same issues apply to

- delete()

by the way.
Here especially we usually do not check the return value and this is not part of CRUD validation procedure.
With delete() we also definitely expect it to return true and not just silently false.

Especially for
- all admin crud backend actions
- CLI operations

**Comment by ravage84** [comment]
@dereuromark wouldn't a callback like ``failedSave()`` and ``failedDelete()`` be an option for you?
Cause it seems to me to be a generally useful thing...

**Comment by inoas** [comment]
Love that idea.

**Comment by dereuromark** [comment]
I am fine either way as long as there aren't any hidden "didnt work" timebombs in the code where you don't respond with validation to the user, but silently just return afterwards.
Until then [this](https://github.com/dereuromark/cakephp-shim/blob/master/src/Model/Table/Table.php#L433-L463) for now quite well as interim solution for save() and delete().

**Comment by cleptric** [comment]
Can I give this a try? Implementing `failedSave()` and  `failedDelete()`

**Comment by robertpustulka** [comment]
Where are we on this?

@cleptric are you implementing these events?

**Comment by cleptric** [comment]
@robertpustulka Yes, I'm on it

**Comment by robertpustulka** [comment]
@cleptric is a PR open?

**Comment by cleptric** [comment]
@robertpustulka Not yet, aiming for Friday

**Comment by robertpustulka** [comment]
@cleptric Great! Turned out I need this feature and was thinking about implementing it myself :)

**Comment by cleptric** [comment]
Core PR was merged, doc PR cakephp/docs#4722 is open.
I guess we can close this :)

**Comment by dereuromark** [comment]
Thanks a lot!

**Comment by inoas** [comment]
Good work!
