### ISSUE TITLE
BLOB field as resource breaks serialization (JSON, etc)

### ISSUE THREAD

**Issue by mamchenkov** [cakephp/cakephp#9658]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.6
* Platform and Target: PHP 5.6.27

### What you did
* `composer create-project --prefer-dist cakephp/app cakephp`
* `mysql -u root -e 'CREATE DATABASE cakephp'`
* Adjust default data source settings in `config/app.php`
* `mysql -u root cakephp -e 'CREATE TABLE blobs(id CHAR(36) NOT NULL UNIQUE, content LONGBLOB, PRIMARY KEY(id))'`
* `bin/cake bake all blobs`
* `mysql -u root cakephp -e "INSERT INTO blobs SET id = '00000000-0000-0000-0000-000000000001', content = 'foobar'"`
* Add `$routes->extensions(['json', 'xml']);` on line 47 of `config/routes.php`.
* `bin/cake server`
* Regular view loads just fine: http://localhost:8765/blobs/view/00000000-0000-0000-0000-000000000001
* JSON view is broken: http://localhost:8765/blobs/view/00000000-0000-0000-0000-000000000001.json

### What happened

Error 500:
```
{
    "message": "Serialization of View data failed.",
    "url": "\/blobs\/view\/00000000-0000-0000-0000-000000000001.json",
    "code": 500
}
```

### Expected Behavior

The JSON object of the selected record should be returned instead.

### Notes

I think it breaks in `_serialize()` method of `src/View/JsonView.php` file, failing to do `json_encode()` on the data.  The reason for that is in `toPHP()` method of `src/Database/Type/BinaryType.php`, which returns BLOB data as a resource.  According to the [json_encode() documentation](http://php.net/manual/en/function.json-encode.php):

> value
>   The value being encoded. Can be any type except a resource.

**Comment by markstory** [comment]
Why are you JSON encoding blobs?

**Comment by markstory** [comment]
Also if you _need_ this in your entities you should be customizing the `jsonSerialize()` method of your entities to read the resources and generated the desired output. I don't think it is reasonable for CakePHP to try and hunt down resources recursively and try to encode them.

**Comment by mamchenkov** [comment]
@markstory BLOBs don't always contain binary data. :smile: .  I don't always control the database - just providing a simple API layer to somebody else's database.  I expected CakePHP to just work, and it did most of the way.  I didn't find this particular issue documented anywhere and it took quite a bit of time to figure out why things were breaking.

I think it should either be fixed or documented somewhere.

**Comment by mamchenkov** [comment]
@markstory not all databases return BLOBs as resources, so converting them into streams seems a bit weird.  Maybe that can be optional.

**Comment by markstory** [comment]
> I think it should either be fixed or documented somewhere.

What needs to be fixed? From looking at the `BinaryType` it consistently returns `null` or a `resource`. Not returning resources will break existing userland code.
