### ISSUE TITLE
Extend BaseErrorHandler - Not catched

### ISSUE THREAD

**Issue by xsyfrost** [cakephp/cakephp#9659]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.6.
* Platform and Target: Apache2, php7, mysql, https with ssl

### What you did
I would like to catch any error add them into database and eventually redirect by 301 error code 

### What happened
extending BaseErrorHandler (Error/AppError.php) works well on my localhost, but running it on the webserver is just not working. It seems that cakePhp is never using it as my print_r()/echo/debug inside is never outputing content

### Expected Behavior
I should be able to catch errors/exception trow the AppError class

The code:
### bootstrap
```
use App\Error\AppError;
$errorHandler = new AppError();
$errorHandler->register();
```

### Error/AppError.php

```
namespace App\Error;

use Cake\Error\BaseErrorHandler;
use Cake\Routing\Exception\MissingControllerException;
use Cake\Network\Exception\NotFoundException;
use Cake\ORM\TableRegistry;
use Exception;

class AppError extends BaseErrorHandler
{
    // Autre méthode.
    public function handleError($code, $description, $file = null, $line = null, $context = null)
    {
        debug($code);
    }

	public function handleFatalError($code, $description, $file, $line)
    {
        debug($code);
    }
	
    public function handleException(Exception $exception)
    {
    	echo "hello";
        debug($exception);
        if ($exception instanceof MissingControllerException || $exception instanceof  NotFoundException) {

            $url = parse_url($_SERVER['REQUEST_URI']);
//My code for managing exceptions here

        }

    }

    protected function _displayError($error, $debug)
    {
        debug($error);
    }
    protected function _displayException($exception)
    {
        debug($exception);
        
    }
}
```

**Comment by markstory** [comment]
If it works on one environment and not the other you should figure out why the two environments are different.

Given that it works on one host and not the other, I suspect this is not an issue with CakePHP but with your code or your environment. If you can provide a way to reproduce your issue I'm happy to take another look.
