### ISSUE TITLE
Add layout() method to Email class

### ISSUE THREAD

**Issue by djamesfar** [cakephp/cakephp#9661]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- [x] email
- CakePHP Version: 3.3.7.
- Platform and Target: all
### What you did

Would like to call Email::layout specifically rather than with template
### What happened

I am calling several instances of Email->template, but all with same layout
Have to repeat layout name in every call of template.
In the interest of DRY, a separate call to ->layout would allow calling it once, then
all subsequent calls to email->template() would not have to repeat 'layout' call.
### Expected Behavior

```
$email = new Email();
$email->layout('certain_layout')
  ->to($recipient)
  ->subject('Status Update')
  ->template('status_update');

if ($account_closed){
   $email->template('different_template'); // keep using layout above
}
...
$email->send();
```

I understand that I can call 

```
$email->viewBuilder()->layout('certain_layout');
```

but it doesn't chain like direct methods in the Class.

Suggested new function in Email class:

```
    /**
    * layout
    *
    * @param bool|string $layout Layout name or null to not use
    * @return array|$this
    */
     public function layout($layout = false)
     {
         if ($layout !== false) {
             $this->viewBuilder()->layout($layout ?: false);
         }
         return $this;
     }
```

**Comment by dereuromark** [comment]
:+1: 

I am carrying this manual addition (+ a few other methods) around in my custom [extension](https://github.com/dereuromark/cakephp-tools/blob/master/src/Mailer/Email.php#L58) for years.
Would be good to get this into the core method.

That said, the other useful methods (see the link) would be:
- wrapLength()
- priority()

**Comment by djamesfar** [comment]
I'm currently using this as an extension myself (not with wrapLength an priority), but it would be a useful addition to the core, I think.

**Comment by markstory** [comment]
Sounds like a good idea to me.

**Comment by ADmad** [comment]
I would rather deprecate direct view related methods on the view class instead of adding more :)  The view builder should be used for all view config. Also using mailer classes avoids any code reputation issues the OP mentions.

**Comment by markstory** [comment]
@ADmad I think having `layout()` gives people who don't want to use Mailers a more consistent interface. But I can see why you'd prefer to have fewer methods on `Email`.

**Comment by dereuromark** [comment]
After the https://github.com/cakephp/cakephp/pull/9921 is merged, the API is at least consistent in itself for 3.x going forward. Template and layout should either way already be separate, and not some dirty combination.

We can revisit the view builder only approach for 4.x then?

As mentioned above the other useful methods (see the link) would be:
- wrapLength()
- priority()

We can add them once the linked PR has been merged.

**Comment by dereuromark** [comment]
This is done with 3.4. The rest I can PR piece by piece.
