### ISSUE TITLE
Unexpected Behvior for beforeSave event. Saving data on middlewares. 

### ISSUE THREAD

**Issue by suhaboncukcu** [cakephp/cakephp#9665]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.3.6
* Platform and Target: PHP: 5.6.20-1+deb.sury.org~trusty+1

### What you did
I have a databaselogger in my plugin which I save data into database as:
```php
        $entity =  $Model->newEntity();
        $Model->patchEntity($entity, $data);
        $Model->save($entity);
```

I have my logger configured as:
```php
Log::config('story', [
    'className' => 'Stories.Database',
    'model' => 'Stories',
    'scopes' => ['registered_user'],
]);
```
I have a middleware as : 
```php
        Log::notice($message,[
        		'scope' => ['registered_user']
        ]);
```

And finally I add my middleware to main app as:
```php
EventManager::instance()->on(
	'Server.buildMiddleware',
	function ($event, $middleware) {
    	$middleware->add(new LoggerMiddleware());
	});
```

### What happened
Everything about logging works at it is supposed to work. However, the Timestamp behavior on my table didn't work. So I checked with another behavior on beforeSave event and I realised that beforeSave event is not fired at all. 

### Expected Behavior
Timestamp behavior should work as it is expected.

**Comment by ADmad** [comment]
Sounds like you used incorrect class or filename. Make sure that your model classs is actually used and your are not getting a `Table` class instance instead.

**Comment by suhaboncukcu** [comment]
@ADmad  I'm sure I used the correct class actually. I know that because it saves the logs. Also all other table functions work too. (As newEntity, patchEntity, etc.)  The only thing that does not work is the behaviors running on table events. 

You can check the example plugin here: https://github.com/suhaboncukcu/stories

(I've set the created field myself while saving data because Timestamp behavior doesn't work.)

**Comment by ADmad** [comment]
In your Log::config() call you need to specify your model along with plugin prefix as `Stories.Stories`.
