### ISSUE TITLE
error view header theme Bootstrap

### ISSUE THREAD

**Issue by arizzoke** [cakephp/cakephp#9666]
my name is Aris, I'm beginner on CakePHP 3,
I have some errors since create theme Bootstrap,
The errors on header can't view,

I give the message error

Deprecated (16384): Property $layout is deprecated. Use $this->viewBuilder()->layout() instead in beforeRender(). [CORE\src\View\ViewVarsTrait.php, line 103]

Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\budiprabowo\vendor\cakephp\cakephp\src\Error\Debugger.php line=753 [CORE\src\Http\ResponseEmitter.php, line 48]

Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\budiprabowo\vendor\cakephp\cakephp\src\Error\Debugger.php:753) [CORE\src\Http\ResponseEmitter.php, line 145]

Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\budiprabowo\vendor\cakephp\cakephp\src\Error\Debugger.php:753) [CORE\src\Http\ResponseEmitter.php, line 170]

Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\budiprabowo\vendor\cakephp\cakephp\src\Error\Debugger.php:753) [CORE\src\Http\ResponseEmitter.php, line 170]

and some code PHP on AppController

<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AppController extends Controller
{
	//bootstrap default
	public $layout = 'Bootstrap.default';
	
	//loading Bootstrao
	public $helpers = [
		'Less.Less',
		'Bootstrap.Form'
	];
    
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
		$this->loadComponent('Flash');
        $this->loadComponent('Bootstrap.Flash');
    }

       public function beforeRender(Event $event)
    {
		//panggil header Bootstrap
	 $this->viewBuilder->theme('Bootstrap');		
        if (!array_key_exists('_serialize', $this->viewVars) &&
            in_array($this->response->type(), ['application/json', 'application/xml'])
        ) {
            $this->set('_serialize', true);
        }
    }
}

some code PHP on ContentsController

<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Contents Controller
 *
 * @property \App\Model\Table\ContentsTable $Contents
 */
class ContentsController extends AppController
{

    public function index()
    {
        $contents = $this->paginate($this->Contents);

        $this->set(compact('contents'));
        $this->set('_serialize', ['contents']);
    }

        public function view($no = null)
    {
        $content = $this->Contents->get($no);

        $this->set('content', $content);
        $this->set('_serialize', ['content']);
    }

    
    public function add()
    {
        $content = $this->Contents->newEntity();
        if ($this->request->is('post')) {
            $content = $this->Contents->patchEntity($content, $this->request->data);
            if ($this->Contents->save($content)) {
                $this->Flash->success(__('The content has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The content could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('content'));
        $this->set('_serialize', ['content']);
    }

    
    public function edit($no = null)
    {
        $content = $this->Contents->get($no);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $content = $this->Contents->patchEntity($content, $this->request->data);
            if ($this->Contents->save($content)) {
                $this->Flash->success(__('The content has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The content could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('content'));
        $this->set('_serialize', ['content']);
    }

    
    public function delete($no = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $content = $this->Contents->get($no);
        if ($this->Contents->delete($content)) {
            $this->Flash->success(__('The content has been deleted.'));
        } else {
            $this->Flash->error(__('The content could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

and some code PHP on index.ctp

`<div class="actions columns col-lg-2 col-md-3">
    <h3><?= __('Aksi') ?></h3>
    <ul class="nav nav-stacked nav-pills">
        <li><?= $this->Html->link(__('Konten Baru'), ['action' => 'add']) ?></li>
        <li class="active disabled"><?= $this->Html->link(__('Daftar Konten'), ['action' => 'index']) ?></li>
    </ul>
</div>
<div class="contents index col-lg-10 col-md-9 columns">
    <div class="table-responsive">
        <table class="table table-striped">
        <thead>
            <tr>
                <th><?= $this->Paginator->sort('no') ?></th>
                <th><?= $this->Paginator->sort('menu') ?></th>
                <th><?= $this->Paginator->sort('tautan') ?></th>
                <th class="actions"><?= __('Aksi') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($contents as $content): ?>
            <tr>
                <td><?= $this->Number->format($content->no) ?></td>
                <td><?= h($content->menu) ?></td>
                <td><?= h($content->tautan) ?></td>
                    <td class="actions">
                    <?= $this->Html->link('<span class="glyphicon glyphicon-zoom-in"></span><span class="sr-only">' . __('View') . '</span>', ['action' => 'view', $content->no], ['escape' => false, 'class' => 'btn btn-xs btn-default', 'title' => __('Tampil')]) ?>
                    <?= $this->Html->link('<span class="glyphicon glyphicon-pencil"></span><span class="sr-only">' . __('Edit') . '</span>', ['action' => 'edit', $content->no], ['escape' => false, 'class' => 'btn btn-xs btn-default', 'title' => __('Perbarui')]) ?>
                    <?= $this->Form->postLink('<span class="glyphicon glyphicon-trash"></span><span class="sr-only">' . __('Delete') . '</span>', ['action' => 'delete', $content->no], ['confirm' => __('Yakin anda akan menghapus # {0}?', $content->no), 'escape' => false, 'class' => 'btn btn-xs btn-danger', 'title' => __('Hapus')]) ?>
                </td>
            </tr>

        <?php endforeach; ?>
        </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('sebelum')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('sesudah') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>
`

I hope it run, thanky very much for help....please

**Comment by ADmad** [comment]
The error message tells you exactly what tje problem is and how to fix it. If you still need help please make a post on the official cakephp forum or stackoverflow. This is not a help forum.
