### ISSUE TITLE
Digest Authentication doesn't actively use the nonce, so a replay attack is possible

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#9668]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.3.6
- Platform and Target: Vagrant bento/debian-8.6, PHP7.0, MySQL. Request tested via Postman and cURL.
### What I did

I have set up a simple Digest Authentication (the app I'm building is going to be the core of a simple API centerend architecture).

```
$this->loadComponent('Auth', [
    'authenticate' => [
        'Digest' => [
            'userModel' => 'ApiClients',
            'fields' => ['username' => 'client', 'password' => 'digest_hash'],
            'realm' => 'api'
        ]
    ],
    'storage' => 'Memory',
    'unauthorizedRedirect' => false,
]);
```

(The response="xxx" is of course a correct md5 hash)

When I make a request via Postman or cURL with the following header: `Authorization: Digest username="jelmer", realm="api", response="xxx"` it fails as expected, because as you can see at https://github.com/cakephp/cakephp/blob/master/src/Auth/DigestAuthenticate.php#L168 it returns false because not all required keys are provided.

So I add the missing keys, and thus sending the following header: `Authorization: Digest username="jelmer", realm="api", nonce="random", uri="/ping", qop=auth, nc=8, cnonce="random", response="xxx", opaque="random"`. And yes, I really provided `random` for the nonce, cnonce, opaque and nc keys.
### What happened

It authenticates me with truly random nonce, cnonce, opaque and nc keys.
### Expected Behavior

I expected it to block the request, since the nonce value wasn't requested from the server earlier on, so it wasn't provided to me via a 401 response.
- I expect the DigestAuthenticate to return a nonce and other keys when I do not provide them.
- I expect the DigestAuthenticate to block the request when I provide a wrong nonce or other keys.

Expectations based on http://www.webdav.org/specs/rfc2617.html#rfc.section.3.3

I'm not that well known with Digest authentication and I'm really trying to understand it all, but as far as I'm concerned the RFC's and other articles about Digest, I expect it to make a handshake first, before I'm authenticated to request data.

**Comment by markstory** [comment]
By handshake do you mean that you expected the server to send a `WWW-Authenticate` header when you failed to authenticate properly?

**Comment by JelmerD** [comment]
@markstory, I expect the following behaviour:
1. I send a request to the API with just the username, realm and response keys provided.
2. The server responds with a 401 and provides the nonce, cnonce, nc and opaque keys.
3. For every request following these two steps, I will supply the username, realm, reponse, nonce, cnonce, nc and opaque keys.
4. The server will now also check the nonce and other keys to check if I'm still the same person and to check I'm still part of that "secure connection".

What happens is:
1. I send a request to the API with just the username, realm and response keys
2. the server responds with a 401 and WWW-Authenticate header, as expected.

But what also happens:
1. I send a request to the API with the username, realm and response keys. But also with a random nonce, cnonce, nc and opaque key.
2. The server responds with a 200.

So, it never checks if the nonce provided is the same as the one that was provided by the server in the first place. With other words: there is no handshake.

I'm not 100% sure if that's the way Digest authentication works, but that is what I make of the RFC's and other source documents that explain the Digest authentication process.

**Comment by markstory** [comment]
@JelmerD Ok, One of the challenges we'll have around nonces is that DigestAuthentication is presently implemented as a fully stateless system, checking nonces in the way you describe would require adding state, and thus storage for that state.

I'll look at some other digest authentication implementations and see if there is a way to avoid replays without introducing the need to validate serverside state.

**Comment by markstory** [comment]
The [symfony implementation](https://github.com/symfony/security-http/blob/dcb83e337dfbcf3c861400ea98c696c30f9bbf09/EntryPoint/DigestAuthenticationEntryPoint.php#L45-L64) seems to avoid server side state by using check sums in the nonce value and expiring the nonce based on server clock.

**Comment by markstory** [comment]
Closing as 3.4.0 will have stricter nonce validation.

**Comment by JelmerD** [comment]
Put it to the test by pulling in the 3.next branch for now as it's not yet merged into a stable release.

While messing around with it I was still baffled by https://github.com/cakephp/cakephp/blob/a8fa835319494501003e1cd067c6ed5fb2db520a/src/Auth/DigestAuthenticate.php#L168

Can somebody explain why we only check if it is present, but don't do anything with these values later on?

I can still put in random values and it doesn't change the behaviour in any way.

I'm not quite sure if I should open a new issue for this. I will if I'm sure I'm not mistaken by something.

Ps. I know it wasn't patched as I checked the commits of Mark, but I'm still not sure why this is the case. So I wasn't expecting it to be solved, but didn't do anything with it.

**Comment by markstory** [comment]
That line is used to set defaults so there aren't key errors later on.

**Comment by JelmerD** [comment]
Okay. Maybe it's not that line, but I have to provide a value. It doesn't matter what I use, I just have to use something. See the screenshots below.

I'm not sure what these keys are for though, as I said I'm not that well known with Digest Auth, but as I understand the the [RFC2617](https://tools.ietf.org/html/rfc2617) they can be left blank. So when I don't send them, at least it shouldn't fail my request.

See the screenshots below. Made my requests with Postman.

# with a random nonce count value

![with nonce count](https://cloud.githubusercontent.com/assets/2372882/21108765/957d99d2-c096-11e6-9132-72b754145509.PNG)

# without a random nonce count value

![without nonce count](https://cloud.githubusercontent.com/assets/2372882/21108764/957c0676-c096-11e6-8d61-0312574425f9.PNG)

**Comment by markstory** [comment]
Have you run into clients that don't provide `nc` where requiring it is problematic?

**Comment by JelmerD** [comment]
Negative, but if it doesn't meet the spec of the RFC, we basically make up our own spec. Don't you agree? But as I said before, I'm not 100% convinced I'm on the right end here, but I'm not convinced by how it works right now.

 Which is why I want to ask everybody to comment if he/she knows something about this subject.

**Comment by JelmerD** [comment]
https://tools.ietf.org/html/rfc2617 page 12

> qop
     Indicates what "quality of protection" the client has applied to
     the message. **If present**, its value MUST be one of the alternatives
     the server indicated it supports in the WWW-Authenticate header.
     These values affect the computation of the request-digest. Note
     that this is a single token, not a quoted list of alternatives as
     in WWW- Authenticate.  This directive is optional in order to
     preserve backward compatibility with a minimal implementation of
     RFC 2069 [6], but SHOULD be used if the server indicated that qop
     is supported by providing a qop directive in the WWW-Authenticate
     header field.

   > cnonce
     **This MUST be specified if a qop directive is sent (see above), and
     MUST NOT be specified if the server did not send a qop directive in
     the WWW-Authenticate header field.**  The cnonce-value is an opaque
     quoted string value provided by the client and used by both client
     and server to avoid chosen plaintext attacks, to provide mutual
     authentication, and to provide some message integrity protection.
     See the descriptions below of the calculation of the response-
     digest and request-digest values.

  > nonce-count
     **This MUST be specified if a qop directive is sent (see above), and
     MUST NOT be specified if the server did not send a qop directive in
     the WWW-Authenticate header field.**  The nc-value is the hexadecimal
     count of the number of requests (including the current request)
     that the client has sent with the nonce value in this request.  For
     example, in the first request sent in response to a given nonce
     value, the client sends "nc=00000001".  The purpose of this
     directive is to allow the server to detect request replays by
     maintaining **its own copy of this count** - if the same nc-value is
     seen twice, then the request is a replay.   See the description
     below of the construction of the request-digest value.

I just came to some sort of a conclusion.

- Yes, we HAVE to provide the cnonce and nonce-count in the request, but only if the qop is sent as well. - The qop is sent in the request, because it was returned in the 401 response
- Therefore we have to use the provided value of qop
- and thus we have to provide a correct cnonce and nonce-count in our further requests.

So I guess you were right in some way.

But, CakePHP doesn't do anything with the nonce-count, or did I miss something? The server should keep track of it's own nonce count apparently.  But we can provide that in the nonce/opaque value, as stated at page 17

https://tools.ietf.org/html/rfc2617 page 17

> Because the client is required to return the value of the opaque
   directive given to it by the server for the duration of a session,
   the **opaque data may be used to transport authentication session state
   information**. (Note that any such use can also be accomplished more
   easily and safely by including the state in the nonce.)

Also, the RFC states I should return the provided opaque by the server. CakePHP does return an opaque value. So, If I understand correctly, it should fail my request if I don't return it correctly. But I can just provide a random value, so...

I think CakePHP could have some improvements regarding Digest Authentication. At least we should attempt to match the RFC as closely as possible in order for users of the API to understand what's happening.

Is this a new issue already? 😅

**Comment by markstory** [comment]
Given that we always send `qop=auth` in the 401 challenge, wouldn't requiring `cnonce` and `nonce-count` make sense? I agree we're not doing as much validation of those properties as described in the RFC. We could incorporate those additional values into the nonce data as you suggested though.
