### ISSUE TITLE
3.next - RFC - Improve Request getter methods

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#9670]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)

We currently have request methods for reading the `params`, `query`, and `data`. By adding new methods for reading this data we can solve a few different but related problems:
- Create method names that better match the PSR7 interfaces.
- Make deprecations simpler as entire methods can be deprecated instead of a modes in a method.
- Add the ability to provide default values.
- Add the ability to cast values read from the request.

While there are a few options for how we could implement the new methods, I'm proposing one and hope that we can reach some consensus on how to proceed.

``` php
// Read a query value, with a default
$request->getQuery('nested.value', 'default value');

// Apply a cast to a post data value to int.
$request->getData('Article.user_id', null, Request::INT);
```

To replace the existing partially deprecated methods we would need a few new methods `getQuery()`, `getData()`, and `getParam()` which would implement the interface shown above.
### Questions
- Is casting more frequently used than default values?
- Should we also include similar methods for reading cookie data, or uploaded files?

Related to:
- #7328
- #2223

**Comment by thinkingmedia** [comment]
I like the casting feature for `getData`, but that's very method specific. What about casting with `getQuery` or how about `getParam`?

I'd prefer a more generic approach.

```
   $user_id = Request::toInteger($request->getData('Article.user_id'));;
```

That would provide type hinting to IDEs.

Still, I'm not sure primitive casting is even needed. What's wrong with the following?

```
  $user_id = (int)$request->getData('Article.user_id');
```

**Comment by josegonzalez** [comment]
I almost never use casting, but I heavily rely on default values.

**Comment by jeremyharris** [comment]
I like the specific casting, and adding multiple casts would be nice like:

```
Request::cast([
  'user_id' => Request::int
  // 'comments' => Request::string (default of course)
  'is_active' => Request::bool
]);
```

If this persisted across all actions it could be pretty useful IMO. Default or not, casting it would mean a consistent result across the board.

**Comment by markstory** [comment]
> Still, I'm not sure primitive casting is even needed. What's wrong with the following?
> ```
>  $user_id = (int)$request->getData('Article.user_id');
> ```

Nothing is wrong with that. It is the simplest solution and requires no additional methods from us which I really like. I'm happy to leave casting out and let people use the casting features PHP provides.

**Comment by inoas** [comment]
I'd like to be able to convert the request data's datatypes *en bulk* and separate from the default values as @jeremyharris demonstrated (not sure about the static calls though).

**Comment by ravage84** [comment]
Totally agree with @josegonzalez 
Not sure we should put casting into this.
May be a separate class to cover cases like @ionas mentioned?

**Comment by inoas** [comment]
How would it be possible to bulk-set default values into request-data/query?

**Comment by markstory** [comment]
@inoas Right now bulk defaults are not in the scope of the proposed changes.

**Comment by markstory** [comment]
Closing as a pull request is up.
