### ISSUE TITLE
Model will not save Entity's associated data if Entity's properites is not dirty

### ISSUE THREAD

**Issue by ictgtvt** [cakephp/cakephp#9671]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.4
* Platform and Target: Ubuntu 16.04, Apache, PHP7.0, Mysql

### What you did
When i run code:
```php
$user_data = [
        'email'        => 'ictgtvt@gmail.com',  // Not changed
        'candidate' => [
               'first_name'  => 'Nguyen 1',     // Changed
               'last_name'  => 'Nguyen Trung 1', // Changed
        ]
]
$this->Users->patchEntity($userEntity, $user_data ,[
                'fieldList'     => ['email'],
                'associated'    => [
                    'Candidates' => [
                        'fieldList' => ['first_name', 'last_name']
                    ]
                ]
            ]);
$this->Users->save($userEntity);
```

### What happened
I need to save Candidate data, but when if `$userEntity->email` is not changed, `$userEntity->candidate->last_name` and `$userEntity->candidate->last_name` will not be saved.

### Expected Behavior
Save Candidate data whenever $userEntity->email changed or not

**Comment by ictgtvt** [comment]
I have to resolve by temporary solution:

```php
 if($userEntity->dirty() == false) {
       if($userEntity->candidate->dirty()) {       
             $userEntity->dirty('email');
      }
}
```

**Comment by ictgtvt** [comment]
My temporary solution is:
```php
if($userEntity->dirty() == false) {
        if($userEntity->candidate->dirty()) {
             $userEntity->dirty('candidate', true);
       }
}
```

**Comment by lorenzo** [comment]
Yes, this is how it is supposed to work when you provide a `fieldList`. The `fieldList` is used to prevent extra fields from being altered in forms where they should not be altered. To fix your problem,  add the `candidate` property to the `fieldList`

**Comment by antograssiot** [comment]
@lorenzo if true then the code sample in the api needs to be updated
http://api.cakephp.org/3.3/class-Cake.ORM.Table.html#_patchEntity

**Comment by ictgtvt** [comment]
@lorenzo 
@antograssiot 
Yes. it worked. Thanks. 
When I got problem, I just follow the code sample. I didn't think that I need to add `candidate` to `fieldList`. Now, it's work fine when `candidate` added.

From CakePHP Document:
```php
$article = $this->Articles->patchEntity($article, $this->request->data(), [
     'fieldList'       => ['title', 'body'],
      'associated' => ['Tags', 'Comments.Users' => ['fieldList' => 'username']]
 ]
);
```

**Comment by markstory** [comment]
Pull request up to correct API docs.
