### ISSUE TITLE
isUnique doesn't work properly with a list of fields

### ISSUE THREAD

**Issue by dvelguru** [cakephp/cakephp#9675]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.6
* Platform and Target: Localhost, MYSQL, PHP 5+

### What you did
```php
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->isUnique(['email', 'username']));
        return $rules;
    }
```
### What happened
The isUnique method ignored the other value in the array.
The workaround:
```php
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->isUnique(['username']));
        return $rules;
    }
```
### Expected Behavior
The rule is supposed to be applied to each value in the array as explained in the documentation.
http://book.cakephp.org/3.0/en/orm/validation.html#creating-unique-field-rules

**Comment by markstory** [comment]
Your workaround doesn't look like it would be equivalent. The first code snippet is creating a unique constraint on email + username. While the second creates two constraints, one on email and the other on username.

 Which constraints were you trying to create?

**Comment by dvelguru** [comment]
Sorry, ignore the workaround. The issue is that passing multiple fields, doesn't work as expected and as designed.

**Comment by dereuromark** [comment]
That is strange, there is specifically a test for this: testIsUniqueMultipleFields().

**Comment by josegonzalez** [comment]
@dereuromark the root issue here is that the user expected a new rule to be applied (one at a time) to each field in the passed list, not a single constraint (similar to composite primary keys) across the passed list.

I think our handling of the situation is correct, though the second form of usage (with a list) should be updated to have an error message like so:

```
$rules->add($rules->isUnique(
    ['username', 'account_id'],
    'This username & account_id combination has already been used.'
));
```

**Comment by dvelguru** [comment]
I misunderstood and I thought this rule would validate 2 fields separately. Sorry
