### ISSUE TITLE
Nested find/contain doesn't use JOIN, produces many additional queries instead

### ISSUE THREAD

**Issue by dvlprs** [cakephp/cakephp#9680]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.4
* Platform and Target: Linux/Apache

### What you did
I have the following models set up: `Office` belongsTo `ZipCode` belongsTo `City` belongsTo `State`. 

    $offices = $this->Office->find('all', array(
        'conditions' => array(
            'State.code' => 'NY',
        ),
        'contain' => array(
            'ZipCode' => array(
                'City' => array(
                    'State',
                ),
            ),
        ),
    ));

### What happened
Cake runs one joined query for Office and ZipCode, and then a number of queries for City and State. Also, when I add the *'State.code' => 'NY'* condition, it shows me the `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'State.code' in 'where clause'`, obviously because nothing *State*-related is included into the main query.

### Expected Behavior

    SELECT * FROM offices 
    LEFT JOIN zip_codes ON offices.zip_code_id=zip_codes.id 
    LEFT JOIN cities ON zip_codes.city_id=cities.id 
    LEFT JOIN states ON cities.state_id=states.id
    WHERE states.code='NY'

[Tried searching](https://github.com/cakephp/cakephp/issues?utf8=%E2%9C%93&q=is%3Aissue%20nested%20contain%20join)

**Comment by dvlprs** [comment]
I submitted the form accidentally. How do I delete this or remove the "On hold" label? 

@VarCI-bot

**Comment by dereuromark** [comment]
I think this is a known limitation of the 2.x contain behavior and is fixed in 3.x.
For 2.x there are either existing behaviors like "Linkable"to overcome this limitation, or you can manually join together the tables.

**Comment by dvlprs** [comment]
Thanks Mark!

**Comment by chinpei215** [comment]
@dvlprs I would like to suggest my plugin instead. Probably, it would work as you want.
https://github.com/chinpei215/cakephp-eager-loader
If you are afraid to enable my plugin globally, you can also use it on the fly, like the following:
```php
$this->Office->Behaviors->load('EagerLoader.EagerLoader');
$offices = $this->Office->find('all', array(
    'conditions' => array(
        'State.code' => 'NY',
    ),
    'contain' => array(
        'ZipCode' => array(
            'City' => array(
                'State',
            ),
        ),
    ),
));

```
