### ISSUE TITLE
Rename Schema/Table to Schema/Schema

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9683]
Refs or reopens non-merged PR https://github.com/cakephp/cakephp/pull/8718

    use Cake\Database\Schema\Table as Schema;

    $schema = new Schema($this->table(), $schema);

says everything already, same with

    protected function _initializeSchema(Schema $table) {}

Both clearly show, that the Table class here should be named something else, ideally `Schema`.

- People confuse it currently with the Table class in ORM
- It always has to be aliased
- Reading those aliases confuses everyone then reading the code.

So it is best if we clean this up in 3.next as class_alias etc.
Makes it easier and more understandable.

    use Cake\Database\Schema\Schema;

    $schema = new Schema($this->table(), $schema);

**Comment by markstory** [comment]
I don't think we can change the typehint without breaking backwards compatibility. At least the last pass at this would have resulted in `E_STRICT` errors in userland code which I don't think counts as 'backwards compatible'. If we can find an alternate solution that doesn't do this then 🌈

**Comment by inoas** [comment]
I am also :+1: if it is BC. I was stumbling across this yesterday.

**Comment by markstory** [comment]
Closing as there is a pull request up now.
