### ISSUE TITLE
Fixtures do not respect default values for nullable string columns

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9686]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.5

### What you did
https://github.com/dereuromark/cakephp-shim/pull/9/files#diff-3c0d2342496f58f7f2efaf7d07350539R21

Adding a default value to a nullable field:
```php
// Fixture content
    'string_optional' => ['type' => 'text', 'null' => true],
    'string_required' => ['type' => 'text', 'null' => false],
    'string_optional_notnull' => ['type' => 'text', 'null' => true, 'default' => ''],
```

### What happened
The schema when read does not contain the empty string, null is returned as default value:

```php
// schema() output:
		'string_optional' => [
			'type' => 'text',
			'length' => null,
			'null' => true,
			'default' => null,
			'comment' => '',
		],
		'string_required' => [
			'type' => 'text',
			'length' => null,
			'null' => false,
			'default' => null,
			'comment' => '',
		],
		'string_optional_notnull' => [
			'type' => 'text',
			'length' => null,
			'null' => true,
			'default' => null, // !!!
			'comment' => '',
		],
```

### Expected Behavior
The fixture concept should be as close to the actual DB schema as possible.
We moved towards respecting defaults more in general in the [past](https://github.com/cakephp/cakephp/pull/8735). And when trying the same thing with an actual (mysql) database, it worked all as expected:

```php
// Migration file
        $table->addColumn('string_optional', 'string', [
            'default' => null,
            'limit' => 255,
            'null' => true,
        ]);
        $table->addColumn('string_required', 'string', [
            'default' => null,
            'limit' => 255,
            'null' => false,
        ]);
        $table->addColumn('string_optional_notnull', 'string', [
            'default' => '',
            'limit' => 255,
            'null' => true,
        ]);
```
led to a real schema of

```php
// schema() output:
		'string_optional' => [
			'type' => 'string',
			'length' => (int) 255,
			'null' => true,
			'default' => null,
			'comment' => '',
		],
		'string_required' => [
			'type' => 'string',
			'length' => (int) 255,
			'null' => false,
			'default' => null,
			'comment' => '',
		],
		'string_optional_notnull' => [
			'type' => 'string',
			'length' => (int) 255,
			'null' => true,
			'default' => '', // OK
			'comment' => '',
		],
```

Without the fix one cannot make test cases that are close to the database setup and asserts would be false or misleading.

**Comment by dereuromark** [comment]
It looks like the fixture itself is fine, also loading the fixture.
But generating the DB table from it will drop the default here due to:
```
        if (isset($data['null']) && $data['null'] === true) {
            $out .= $data['type'] === 'timestamp' ? ' NULL' : ' DEFAULT NULL';
            unset($data['default']);
        }
```

I am wondering a bit more about how this would work and if it makes sense across different DB.
In MySQL for example it perfectly works to say `DEFAULT ''` and still storing NULL values.
So should the default value take precedence over the null one?
Or should it (as I once suggested) throw a logical exception as both together are not supported by the framework fixture/table concept?

**Comment by markstory** [comment]
Pull request up now.

**Comment by dereuromark** [comment]
I think with bool values there is a small bug left:

fixture row
```php
'active_optional_notnull' => ['type' => 'boolean', 'null' => true, 'default' => false],
```
and test
```php

		$data = [
			'string_optional_notnull' => '',
			'active_optional_notnull' => '',
		];
		$entity = $this->Table->newEntity($data);

		$expected = [
			'string_optional_notnull' => '',
			'active_optional_notnull' => false,
		];
		$this->assertSame($expected, $entity->toArray());
```
fails because it suddenly is "true" instead of "false here for the active_optional_notnull field.

**Comment by markstory** [comment]
Is this issue with MySQL? The schema generation and reflection tests already cover boolean fields and getting `0` back as a default value for the reflected schema.

**Comment by markstory** [comment]
Re-closing as `''` being converted to `false` makes sense to me. Whether the `'default'` is `false` or `0`, doesn't change the results of `newEntity()`.

**Comment by dereuromark** [comment]
As it happens with local tests this seems to be SQLite related.
