### ISSUE TITLE
Bug in deleteAll() ?

### ISSUE THREAD

**Issue by tom76dc** [cakephp/cakephp#9687]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.6
* Platform and Target: NGINX,MYSQL INNODB Tables

Hello,
In the documentation if find that
- delete : will delete associated data when HasMany associations are configured as dependent
- deleteAll : will delete all associated data

When i 
- Use delete() **with** 'dependent' => true in the model, the referenced data is deleted in the other table
- Use deleteAll(), the delete does not work

Is this because of the constraint i added ?
Did i misunderstand the documentation that deleteAll deletes associated data anyway ?  or is this a bug in deleteAll?

The Error message i receive is
`Argument 1 passed to Cake\Database\Expression\QueryExpression::_addConditions() must be of the type array, object given, called in /var/www/nginx.local/cakephp/vendor/cakephp/cakephp/src/Database/Expression/QueryExpression.php on line 140`

I setup 2 tables to test this. 
tables : clients, addresses . 

CREATE TABLE `clients` (
  `id` int(11) NOT NULL,
  `name` varchar(50) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `addresses` (
  `id` int(11) NOT NULL,
  `name` varchar(50) COLLATE utf8_bin NOT NULL,
  `client_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `addresses`
  ADD CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`);

regards,
Tom

**Comment by markstory** [comment]
`deleteAll` is a shortcut method to doing `DELETE FROM <table> WHERE <conditions>`. It does not trigger any ORM callbacks or dependent records. The [API docs](http://api.cakephp.org/3.3/class-Cake.Datasource.RepositoryInterface.html#_deleteAll) include this information.

**Comment by tom76dc** [comment]
Hi Markstory,
thank you for the fast reply! I have to admit, I was always looking into the cookbook. 

But maybee you agree  that the information in the cookbook can be interpreted wrong. On this [link ](http://book.cakephp.org/3.0/en/orm/deleting-data.html) just below the header cascading deletes it says :


# Cascading Deletes
When deleting entities, associated data can also be deleted. If your HasOne and HasMany associations are configured as dependent, delete operations will ‘cascade’ to those entities as well. **By default entities in associated tables are removed using Cake\ORM\Table::deleteAll()**

just my 2 cents, i think the cookbook can be more clear
regards,
Tom

**Comment by markstory** [comment]
Ah. That is trying to say that when an entity is deleted, and deletes are cascaded, the cascade is done via deleteAll(). Not that deleteAll() cascades.

**Comment by xebaxt** [comment]
Hi Markstory,

I also misunderstood the documentation because it was not clear to me that I needed to perform the deleteAll operation for all the associations. It was not obvious that deleteAll removes all the associated entities. I believe this part could be clarified further.

**Comment by othercorey** [comment]
> Hi Markstory,
> 
> I also misunderstood the documentation because it was not clear to me that I needed to perform the deleteAll operation for all the associations. It was not obvious that deleteAll removes all the associated entities. I believe this part could be clarified further.

Please open a new issue if you have a concern.
