### ISSUE TITLE
Call to undefined method Cake\Log\Log::warn()

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#9689]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.7

src/Http/ResponseEmitter.php, line 50

**Comment by chinpei215** [comment]
Confirmed. The correct method name is `warning()`, not `warn()`.

**Comment by markstory** [comment]
Thanks. I've pushed up a commit to fix this.
