### ISSUE TITLE
Transliterator requirements

### ISSUE THREAD

**Issue by glafarge** [cakephp/cakephp#9697]
This is a :
* [x] requirements thing
* CakePHP Version: 3.3.6
* Platform and Target: Linux + PHP 5.6.25
* intl version : 1.1.0
   * ICU version : 4.4.1
   * ICU Data version : 4.4.0.1

### What you did
```php
Text::slug('Économie & développement durable');
```
### What happened
PHP warning is thrown : 
```
transliterator_transliterate(): Could not create transliterator with ID "Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove" (transliterator_create: unable to open ICU transliterator with id "Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove": U_INVALID_ID) [CORE/src/Utility/Text.php, line 1065]
```
As the ICU version is outdated, the default transliterator id string is not found.

### Possible solutions
* Specify the minimum intl version `"ext-intl": ">=2.0"` in composer.json to meet the real requirements and update doc.
* Provide a polyfill/fallback in `\Cake\Utility\Text` like `Inflector::slug` did with search/replace when extension is not available or when transliterator id not found by testing against [registered transliterator IDs](http://php.net/manual/fr/transliterator.listids.php)... 
* Go for a run

**Comment by ADmad** [comment]
Specifying `"ext-intl": ">=2.0"` in `composer.json` would be incorrect as problem is not the `intl` version but rather outdated ICU libs. I have `intl` version `1.1.0` (on ubuntu 16.04 with PHP 7) and things work just fine.

**Comment by ADmad** [comment]
We need to add a version constraint for `lib-ICU` in `composer.json` though I am not not which min. version supports the default transliteration id.

**Comment by glafarge** [comment]
[**ICU 4.6**](http://site.icu-project.org/download/46) which implement for the first time CLDR 1.9 is the correct min. version that supports Latin-ASCII *

\* As I didn't find anything in changelog, I attempted to guess version by comparing the following two releases : [CLDR 1.8.1 core.zip](http://unicode.org/Public/cldr/1.8.1/core.zip) vs [CLDR 1.9.0 core.zip](http://unicode.org/Public/cldr/1.9.0/core.zip)

**Comment by glafarge** [comment]
Furthermore : aura/intl requires [ICU 4.8 or higher](https://github.com/auraphp/Aura.Intl/blob/576221a8b35624acf91c39cdf58c8d7f088eb996/src/IntlFormatter.php#L36:L41)

**Comment by ADmad** [comment]
4.8 it is then. Would you like to make a PR for it?

**Comment by markstory** [comment]
Closing as related pull request has been merged.
