### ISSUE TITLE
No support for nameless cookies in HttpSocketResponse

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#9698]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.1

### What you did
Consider following set-cookie header (real-life example):
```
SetCookie: 1271; domain=.example.com; expires=Fri, 04-Nov-2016 12:50:26 GMT; path=/
```

### What happened
There's a warning: `Undefined offset: 1`, line 322 `Cake/Network/Http/HttpSocketResponse.php`

### Expected Behavior
Cookies with no name should be handled without warnings.

**Comment by markstory** [comment]
Pull request open now.
