### ISSUE TITLE
3.4+ Configure components and helpers through setters

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9702]
This is a:
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3

### What you expected to happen
Could configuration of core components and helpers be done through chained setters?

Ref: https://github.com/cakephp/cakephp/pull/9701

**Comment by dereuromark** [comment]
I think as long as we deal with a config array everywhere it probably is not too helpful to try to create setters and getters here.
The overhead might be too much for those classes.

**Comment by markstory** [comment]
I'm not sure chained setters and concepts like `config()` interact. It feels like they would overlap quite a bit and be a bit awkward.

**Comment by inoas** [comment]
@dereuromark okay, I'd have loved to see public array interfaces die as much as possible as they are sadly error prone in PHP... this is especially true for Auth component and its deep nesting.

If you consider that in any way helpful re-open or open a new issue as the stance seems to be `no`.
