### ISSUE TITLE
Marking associations as dirty should not be required if associations to be saved are explicitly declared.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#9716]
* [X] enhancement

Taken from life.  Lets have `User` that can have many `UserActivations` entity relation.

Now I wanted to atomicly update `UserActivation` and activate `User` trought association
```

$activation->activated = true;
$activation->activated_at = new FrozenTime();
$activation->user->active = true;
$activation->user->password = (new DefaultPasswordHasher())->hash($this->request->data(['password']));
if (debug($this->UserActivations->save($activation, ["associated" => "Users"]))) {
```
What I was struggeling is that `User` has been not updating because I have missed (forgot that it has to be there) ````$activation->dirty("user", true);```` .
IMHO it would be good to relax the requirement of marking association dirty when association to be saved is explicitly declared in save $options like here  ````save($activation, ["associated" => "Users"])````. This suggest stat the dev is aware of changes to `User` and wants to persist them.

**Comment by markstory** [comment]
How would you implement the desired behavior? While I agree it would be nice to have, I don't know how we implement it in a way that doesn't introduce complex logic.

**Comment by Antoniossss** [comment]
First thought would be to mark as dirty all existing relations provided in `["associated"]` array. Maybe this could be added to `dirty` method to accept associations array? Or even separate this logic into helper method like dirtyAssociations(array $assoc). One could use it but doesnt have to, and this could be called is `_save` as well.
