### ISSUE TITLE
ORM: no correct query building on matching with associations having a 'select'-strategy

### ISSUE THREAD

**Issue by schrolli** [cakephp/cakephp#9719]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.4
* Platform and Target: apache 2.4.18, mariadb 10.0.27-MariaDB-0ubuntu0.16.04.1

### What you did
tables: `Posts hasMany Comments`

I have added another association to get the latest `Comment` of a `Post` named `LastComments`:

    class PostsTable extends Table {
        public function initialize(array $config) {
            parent::initialize($config);

            $this->table('posts');
            $this->displayField('name');
            $this->primaryKey('id');

            $this->hasMany('Comments', [
                'foreignKey' => 'post_id',
            ]);
            $this->hasOne('LastComments', [
                'className' => 'Comments',
                'foreignKey' => 'post_id',
                'strategy' => 'select',
                'conditions' => function ($e, $query) {
                    $query->where(['LastComments.date = (select max(c.`date`) from comments as c where c.post_id = LastComments.post_id)']);
                    return $e;
                }
            ]);
        }
    }

I wanted to make a List of Posts, where no comments where made for at least five days. The query is as following:

    $posts = $this->Posts->find('all');
    $posts->matching('LastComments');
    $posts->where([
        'DATE_ADD(LastComments.date, INTERVAL 5 DAY) < NOW()',
    ]);
    $this->set(compact('posts'));

### What happened
The result contains multiple rows of one and the same Post. The sql query doesn't contain the where-clause defined in the association. 

### What you expected to happen
simply use the defined where clause in the `inner join on` statement.

### What I found out
when copying the where call into the callback-function from `matching` all works well:

    $posts->matching('LastComments', function ($q){
        $q->where(['LastComments.date = (select max(c.`date`) from comments as c where c.post_id = LastComments.post_id)']);
        return $q;
    });

A query with `->contain('LastComments')` correctly only returns one item per Post:

    $posts = $this->Posts->find('all')->contain('LastComments');

So it has something to do with `matching()`, `innerJoinWith()` and `leftJoinWith()`. I tested all of them and all have the same defect.

From fast review, i couldn't find anything completely wrong in Cake\ORM\Query and Cake\ORM\EagerLoader...

**Comment by markstory** [comment]
What is the generated SQL in the scenario where the `INTERVAL` condition is added in the `where()` and when it is added in the `matching()` call?

**Comment by schrolli** [comment]
sorry,

i was to dumb to rtfm. the `conditions` option of `hasOne()` should be a simple array of where-clauses and no function (i think i grabbed the function syntax from an answer from stackoverflow)... so in this particular example, contain simply returned the correct value from the database without even using my `where` clause. Because of this, the `matching()` call couldn't know about it either... When defining the clause in the correct way in the Table, all works without redefining the condition in the `matching()` call.
