### ISSUE TITLE
Add CellView

### ISSUE THREAD

**Issue by ayman-alkom** [cakephp/cakephp#9721]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.7

### What you did
I just set the view layout in the initialize function as this:

````php
class AppView extends View
{
    public function initialize()
    {
        parent::initialize();
        $this->layout = 'default';
    }
}
````
and I have a none edited yet **cell** generated by bake, and displayed it as the following:

```php
<?= $this->cell('Branches') ?>
```

### What happened
The cell took the layout and made an infinity loop, then I get error about the allowed space memory.

**Comment by thinkingmedia** [comment]
Cells don't use a layout. It's more likely that you have a recursive error. Try adding an ErrorController as shown in the cake/app

**Comment by ayman-alkom** [comment]
you can reproduced the error by your self, I made it on a fresh cake, and empty cell

**Comment by thinkingmedia** [comment]
@ayman-alkom thanks, I'll investigate. If it's a problem then I'll re-open or fix it.

**Comment by ayman-alkom** [comment]
I fixed the problem in my cell as the following:
```php
    public function __construct($request, $response, $eventManager, array $cellOptions)
    {
        parent::__construct($request, $response, $eventManager, $cellOptions);
        $this->viewBuilder()->autoLayout(false);
    }
```
but this not official at all

**Comment by thinkingmedia** [comment]
That makes no sense. I'm baking the cake/app now to take a look.

**Comment by ADmad** [comment]
`Cell::render()` set layout to `false` using the view builder but since `View::initialize()` is called after builder options are applied the layout always gets sets to `default` for the given code.

While we can ensure cells always render without layout by using second param of `View::render()` setting layout in `AppView::initialize()` is a very bad practice and it will always override the layout setting done in view builder of your controllers.

**Comment by thinkingmedia** [comment]
I could not reproduce with Cake 3.3.8.

- php composer.phar create-project --prefer-dist cakephp/app bookmarker
- cd bookmarker
- composer install -n
- bin/cake bake cell Branches
- edit AppView.php

then tried adding cell output to pages and default without effect.

What version of PHP are you using?

**Comment by ayman-alkom** [comment]
composer.phar create-project --prefer-dist cakephp/app bookmarker
cd bookmarker
bin\cake bake cell Some

then go to Cake\View\View\AppView.php and add this:
```php
class AppView extends View
{
    public function initialize()
    {
        $this->layout = 'default';
    }
}
```
then go to Cake\Template\Pages\home.ctp and edit as this:
```php
<?= $this->Flash->render() ?>
<div class="container clearfix">
    <?= $this->cell('Some') ?>
    <?= $this->fetch('content') ?>
</div>
<footer></footer>
```

then go to Cake\Template\Pages\home.ctp and remove 
```php
$this->layout = false;
```
them bin\cake server

**Comment by thinkingmedia** [comment]
> The cell took the layout and made an infinity loop, then I get error about the allowed space memory.

This is a cascading error that means when cake renders the error view the error is reproduced. It implies something is wrong before the `beforeFilter` in dispatch is fired. Check your models, bootstrap, config and things like that.

Also, add a `die` statement in the error controller to stop propagation and see what the original error is.

**Comment by thinkingmedia** [comment]
> then go to Cake\Template\Pages\home.ctp and remove

that was the trick. I can reproduce now.

**Comment by thinkingmedia** [comment]
@ADmad I agree with what you said above.

This is not an error. It's a cascading render that runs until it runs out of memory. I need time to think about this and if we should change anything if at all.

**Comment by ayman-alkom** [comment]
>  I need time to think about this and if we should change anything if at all

Why not to just add CellView

**Comment by ADmad** [comment]
@ayman-alkom Did you read my comment and understand what I am saying? Regardless of your particular issue  Setting `$this->layout` in `AppView::initialize()` would mean you will never be able to switch the layout from your controller.

**Comment by thinkingmedia** [comment]
```
class AppView extends View
{
    public function initialize()
    {
        $this->layout = 'default';
    }
}
```

The above is the source of the problem. That is overriding the layout for the view.

To fix this. I would change the core to throw an exception if layout is modified outside of context. That's something I don't want to do.

**Comment by ayman-alkom** [comment]
@ADmad sorry I didn't noticed your comment, so I now understand
@thinkingmedia I suggest to not close the issue till it be solved, the solution is still under discussion I thought

**Comment by thinkingmedia** [comment]
@ayman-alkom sorry, didn't mean to jump the gun on closing it.

I can tell you that this won't be fixed in Cake 3.x, but take note that we are working on improving how properties are accessed in all of the core. This issue raises awareness about a vulnerability in the `View` class, and to fix that we need to make more properties use getter/setter functions instead.

If it's possible maybe we can make `View::$layout` readonly by having only a `View::getLayout()` method and `$layout` becomes private. The other option is to make `ViewBuilder` inject an options class that is read-only.
