### ISSUE TITLE
StringTemplate vsprintf error with %20 (URL encoded space)

### ISSUE THREAD

**Issue by spout** [cakephp/cakephp#9722]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8

### What you did
```php
<?php
use Cake\View\StringTemplate;

$stringTemplate = new StringTemplate();
$stringTemplate->add(['test' => '<img src="/img/foo%20bar.jpg"> {{text}}']);
echo $stringTemplate->format('test', ['text' => 'formatted text']);
```

### What happened
`Warning (2): vsprintf(): Too few arguments [CORE/src/View/StringTemplate.php, line 246]`

### What you expected to happen
`<img src="/img/foo%20bar.jpg"> formatted text`

It is caused by `%20`: http://ideone.com/90rryS

**Comment by thinkingmedia** [comment]
It's not a bug.

You have to escape using two `%%` characters.

    $stringTemplate->add(['test' => '<img src="/img/foo%%20bar.jpg"> {{text}}']);

**Comment by dereuromark** [comment]
That said, it should be noted that whitespace in URLs should always be avoided completely.
Use slugs or at least replace those whitespace characters with underscore/dash instead.

**Comment by spout** [comment]
I'm using StringTemplate for replacing part of HTML content produced by TinyMCE.
Like [bbcode] but with Cake built-in StringTemplate.
I hate spaces in URLs but the customer who use TinyMCE doesn't care.

**Comment by inoas** [comment]
Regexp run on the input to replace %20 with %%20?

**Comment by spout** [comment]
Fixed by not using StringTemplate for this. Perhaps this issue will help others facing this.

**Comment by markstory** [comment]
We could/should be replacing `%` in variables with `%%` where we know it is not a sprintf placeholder in my opinion. Allowing recursive variable replacements sounds like a feature I don't think we want.

**Comment by markstory** [comment]
Pull request up now.
