### ISSUE TITLE
underscore routing is not working after upgrading from 3.0.1 to 3.3.3

### ISSUE THREAD

**Issue by puneeth-bikeninja** [cakephp/cakephp#9723]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3.
* Platform and Target:  Upgrading CakePHP from 3.0.1 to 3.3.3 using composer update.

 Below is my controller file for which "My_Properties" DashedRouting using underscore was working in CakePHP 3.0.1.

```
<?php
namespace App\Controller;
use App\Controller\AppController;
/**
 * MyProperties Controller
 *
 * @property \App\Model\Table\MyPropertiesTable $MyProperties
 */
class MyPropertiesController extends AppController
{
    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Creator', 'Modifier']
        ];
        $this->set('myProperties', $this->paginate($this->MyProperties));
        $this->set('_serialize', ['myProperties']);
    }
}
```

After upgrading to 3.3.3 this routing is giving me Missing Controller "My_Properties" exception. But MyProperties and My-Properties is able to map to MyProperties controller.

It is expected no change in this routing to be happen when cakephp is upgraded.

Also observed this happens at only Controller level. If I had a method getProperties in side MyProperties controller accessing it like "domain/MyProperties/get_properties"  is also working.

**Comment by ADmad** [comment]
What does your `routes.php` look like?

**Comment by puneeth-bikeninja** [comment]
```
<?php

use Cake\Core\Plugin;
use Cake\Routing\Router;

Router::defaultRouteClass('DashedRoute');

Plugin::routes();
```

**Comment by ADmad** [comment]
Since your have set default route class as `DashedRoute` unless you use `InflectedRoute` when connecting a particular route, URLs with underscore are not supposed to work.

**Comment by ADmad** [comment]
If you want to keep using your old URLs with underscore change `Router::defaultRouteClass('DashedRoute');` to `Router::defaultRouteClass('InflectedRoute');`

**Comment by puneeth-777** [comment]
Changing `Router::defaultRouteClass('DashedRoute');` to `Router::defaultRouteClass('InflectedRoute');` solves issues with Controller Level but causing same problem with actions. As I mention in above regarding getProperties method, access to this is now failing (domain/MyProperties/get_properties) 

 **The action get_properties is not defined in MyPropertiesController** 
`
 Error: Create MyPropertiesController::get_properties() in file: src/Controller/MyPropertiesController.php.`

MyPopretiesController is 
```
<?php
namespace App\Controller;
use App\Controller\AppController;
/**
 * MyProperties Controller
 *
 * @property \App\Model\Table\MyPropertiesTable $MyProperties
 */
class MyPropertiesController extends AppController
{
    /**
     * Index method
     *
     * @return void
     */
    public function getProperties()
    {
        $this->paginate = [
            'contain' => ['Creator', 'Modifier']
        ];
        $this->set('myProperties', $this->paginate($this->MyProperties));
        $this->set('_serialize', ['myProperties']);
    }
}
```

**Comment by ADmad** [comment]
> The action get_properties is not defined in MyPropertiesController

So name your method as the error message tells you to. Camel backed methods names are used when using dashed route since you can't use dash in method names.

**Comment by inimist** [comment]
This is another problem, isn't it? CakePHP previously supported both types of actions, underscored and camel cased. Now dashed routes route to camel cased methods and underscored route to underscored. What i like is, having dashed urls such as `my-profile` in browser and `my_profile()` method in controller. This is no more possible?

**Comment by inimist** [comment]
I guess that it can be achieved with defining routes in a specific way though, I haven't tried it but I believe it could be. But you may have to define one route each for every controller method which may be thing you would avoid where there are hundreds of methods/urls

**Comment by markstory** [comment]
What i like is, having dashed urls such as my-profile in browser and my_profile() method in controller. This is no more possible?

This was never supported through action name inflection. You could add this convention by creating a custom route class for your application.

**Comment by inimist** [comment]
Got it. Yes I am looking forward to create a custom route class. Thanks for the explanation!

**Comment by ADmad** [comment]
> What i like is, having dashed urls such as my-profile in browser and my_profile() method in controller. This is no more possible?

When using `DashedRoute` your method name should be `myProfile()`. This is so because PSR2 recommends using camelCased methods names. `InflectedRouted` routes still used underscored methods name only due to legacy reasons.
