### ISSUE TITLE
Iterating an array change its content

### ISSUE THREAD

**Issue by Aerue** [cakephp/cakephp#9725]
* [x] bug

* CakePHP Version: 3.3.8 - 6ab9f76c5cba2190a721ff3bf242e8dec78a5016
* Platform and Target: nginx - ubuntu 14.04 LTS - PHP 7.0.11 - mysql  Ver 15.1 Distrib 10.1.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Call my Webservice with a get request
In my webservice i iterate around a Array of Entity result : 

    foreach ($this->_data->programs as $key => $program) {
        // ...
    }

debugging my array before iterate ouput somethings like : 

    [
        {
            'id' => 6,
            //...
        },
        {
            'id' => 7,
            //...
        }
    ]

debugging after my iterate result of value changed inside my array 0_o

    [
        {
            'id' => 6,
            //...
        },
        {
            'id' => 6,
            // same content as entry id key 6....
        }
    ]

### Temporary fixxed by passing my value as reference

    foreach ($this->_data->programs as $key => &$program) {
        // ...
    }

**Comment by markstory** [comment]
How is this an issue with CakePHP?

**Comment by Aerue** [comment]
May be an issue with php 7, but I just view this error when update to cake 3.3.8 from 3.2.x

**Comment by markstory** [comment]
Ok. Right now we don't have a way to reproduce this. We'll need that before anyone can look at this issue further.
