### ISSUE TITLE
Custom route class can't redirect using current query string arguments (Google Adwords)

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#9726]
Sometimes I need to to do redirects in a custom route class and keep the query string for tracking purposes. The reason is that some objects have changed their URL and we need to redirect the old one to the new one. When Google Adwords sends a user to the old URL the tracking info is lost when redirecting. The easiest way to solve it that I know would be to use the _GET variable, but I think there should be another way.

Putting the redirects in the Apache config isn't possible since the list is big and changing. I've thought about creating a middleware component that would do the redirects but I would be duplicating database queries, one checking for the redirect in the middleware and another one in the route class. Now one query gets me both.

It seems the routing component is deliberately ignoring query string arguments but there're cases where handling them as part of the URL would be needed.

This other issues are related: #2120 (similar problem for cake2), #8491 (same problem with Router::redirect).

**Comment by dereuromark** [comment]
I second that, we should at least provide some very basic query string support here.
