### ISSUE TITLE
Introduce a new deleteEach method for Table

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9727]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next
* Platform and Target: Apache, MySQL, PHP 7

### What you did

The classic example

```
     $table->addBehavior('Something');
     $table->deleteAll(['thing'=>true]);
```

### What happened

Records are deleted, but no behaviors/events are processed.

### What you expected to happen

There is a history of users opening issues about `deleteAll` failing to perform some kind of expected callback operation on records. It is a short hand method for running a single SQL statement.

Is there value in adding a `deleteEach` that would iterate over the results deleting each record individually? That would allow for the expected events to be processed.

Here's an example as a quick draft. I would add more options in the final PR.

```
     public function deleteEach($conditions)
     {
            $count = 0;
            while(true) {
                 $entity = $this->find()->where($conditions)->first();
                 if(!$entity || !$this->delete($entity)) {
                      break;
                 }
                 $count++;
            }
            return $count;
     }
```

**Comment by markstory** [comment]
I can see that being useful as an alternative to `deleteAll()` that includes all the ORM callback features. :+1: from me.

**Comment by inoas** [comment]
I'd love to see that you can set atomic => true (set to true by default) and everything being wrapped in a transaction, so that you can have "either everything is gone, or you get an error and the state is not touched".

**Comment by thinkingmedia** [comment]
@inoas wrapping a large multi-row operation in a transaction could be catastrophic when an error triggers a roll-back. MySQL will crash if it runs out of memory rolling back a transaction and will then enter recovery mode. Depending upon the size of the database the rebuild could take hours to finish. Leaving the database offline in read-only mode.

Performing each delete in a transaction, and stopping on failure would be the sensible thing to do. The developer could wrap the `deleteEach`  in a transaction if they want full coverage.

**Comment by inoas** [comment]
I don't think it is a problem for most cases.

It may be a problem for bulk deleting thousands of records, but not for bulk deleting small numbers. 
Maybe we can have atomic built in but set to false?

Alternatively when the docs PR comes in I'd like to see (or add myself) the info on how to make it transaction safe by wrapping in the docs.

**Comment by thinkingmedia** [comment]
Closing as PR is up now.
