### ISSUE TITLE
Loading Helpers in AppView

### ISSUE THREAD

**Issue by cleptric** [cakephp/cakephp#9729]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.3

It would be nice, if I can load Helpers in the AppView via the helpers property, similar to loading components in the AppController via the components property.

**Comment by thinkingmedia** [comment]
I think we're moving away from magic properties.

**Comment by inoas** [comment]
You can load those with loadHelper() afair, you can setup a look in initialize() if you want to walk arrays.

**Comment by dereuromark** [comment]
I agree, it is easily possible to provide this in user or plugin land code if desired.
The Shim plugin does similar bc approaches for other things like this.
