### ISSUE TITLE
Strengthen phpdoc type hinting in ORM/Database layers.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9735]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0

### What you did

The following methods define simple `string` parameter types.

```
ORM\Query::update();
ORM\Query::delete();
Database\Query::into();
Database\Query::update();
Database\Query::delete();
Database\Query::epilog();
```

### What happened

I passed wrong value type by mistake to one of the above methods (i.e. an array).

### What you expected to happen

PHP run-time array of incompatible types pointing me to the source of my mistake, but what actually happen is the query compiler generated unrelated run-time errors deep down in the `sprintf` functions. The call stack was showing when the query was execute, but that was far away from where the query was define.

To counter this problem, I added type checking to ensure above methods received only `string` values. This broke many unit tests that were passing a variant of argument types.

Thus, the phpdocs need to be updated with the correct range of possible argument types.

**Comment by dereuromark** [comment]
We will implement all these typehints now in 4.x piece by piece.
