### ISSUE TITLE
I have problem with databese's DSN

### ISSUE THREAD

**Issue by atkrad** [cakephp/cakephp#9738]
* [x] bug

* CakePHP Version: 3.3.8
* Platform and Target: Nginx, PHP 5.6.27, Postgresql 9.5.

I set this config `'Datasources.default.url' => 'postgres://username:password@localhost/database'` with `DATABASE_URL` env. 

I get follow notice message:
`Notice (8): Undefined index: className [CORE/src/Datasource/ConnectionManager.php, line 117]`

**Comment by thinkingmedia** [comment]
I think you are missing `'className' => 'Cake\Database\Connection' ` from your `Datasources` configuration.

**Comment by atkrad** [comment]
@thinkingmedia my `Datasource` config:
```
'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => 'localhost',
            //'port' => 'non_standard_port_number',
            'username' => 'my_app',
            'password' => 'secret',
            'database' => 'my_app',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATABASE_URL', null),
        ]
]
```

**Comment by thinkingmedia** [comment]
Why are you using a MySQL driver with a Postgres connection?

**Comment by atkrad** [comment]
Does `DATABASE_URL` config override on other configs (for example: `driver`, `username`, `password`, ...)?

**Comment by ADmad** [comment]
The key name needs to be ` Datasources.default.url`. Datasources is plural.

**Comment by atkrad** [comment]
@ADmad I've made a mistake on write issue.

**Comment by markstory** [comment]
@atkrad Ok, then we'll need a way to reproduce the issue you're having. I frequently use DSNs for mysql/postgres/sqlite. Furthermore our [travis CI builds do just that](https://github.com/cakephp/cakephp/blob/master/.travis.yml#L12-L15) as well. So I hope you can understand my skepticism around DSNs 'not working'.
