### ISSUE TITLE
Discrepancies patching HasMany and BelongsToMany

### ISSUE THREAD

**Issue by cjquinn** [cakephp/cakephp#9739]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.8

Looking at the documentation `HasMany` and `BelongsToMany` are lumped together when talking about patching entities. Both relationships can take request data like the following:

```
$newData = [
    'comments' => [
        ['body' => 'Changed comment', 'id' => 1],
        ['body' => 'A new comment'],
    ]
];

$articles->patchEntity($entity, $newData);
```

The discrepancy is that a `BelongsToMany` relationship will fetch entities from the database if the primary key is present. This is not the case with `HasMany` a new entity object is created and you are required to set its primary key as accessible is you are patching existing records.

Looking at the `Marshaller` class there are some times where the two associations patch the same:

* When using the `_ids` request data structure - https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php#L296
* When associations have been loaded prior to patching - https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php#L702

Feel free to shoot me down if this is very much intended, it just struck me as strange is all!

**Comment by markstory** [comment]
If I'm understanding you right, you'd like HasMany associations to load/patch existing entities when the primary key fields are present?

**Comment by cjquinn** [comment]
Yes or not bundle `HasMany` and `BelongsToMany` together in the documentation when talking about patching entities. I pretty much never make the `id` of an entity accessible so the difference in functionality here ended up quite drastic when it was intended for both associations to be updated.

**Comment by markstory** [comment]
Did you happen to have loaded your HasMany association records before patching? The [tests cover the behavior you want in that scenario](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/MarshallerTest.php#L1562-L1635)

**Comment by cjquinn** [comment]
Indeed, if the associations are loaded prior to patching both act the same. The issue is when you haven't loaded associations the functionality is different and that isn't clear in the docs. I feel either the docs needs a rewording/after word regarding this or a change to how the marshaller deals with `HasMany` associations.

**Comment by markstory** [comment]
Ok. I'll clarify the docs. We wanted to avoid loading data up in the Marshaller as much as possible.

**Comment by cjquinn** [comment]
Ace makes sense!
