### ISSUE TITLE
Cache does not expose (configured) engines

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#9741]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.9.2 (but also applies to other versions)

Is there a reason that `Cache` does not expose the instances it holds in `static::$_engines`? For our use-case, but probably also for others, it would be very helpful to have something like this:

```php
public static function getEngine($config = 'default') {
	$settings = static::settings($config);

	if (empty($settings)) {
		return false;
	}
	if (!static::isInitialized($config)) {
		return false;
	}
	return static::$_engines[$config];
}
```

This way I can call Engine specific methods, for instance `ping` on the `Redis` object:

```php
$pong = Cache::getEngine()->ping();
```

Or `add` (with four arguments) on the `Memcache` object:

```php
$success = Cache::getEngine(Configure::read('Session.handler.config'))->add($this->__lockKey, '1', null, $this->__lockMaxWait + 1);
```

I would love to implement this feature, but before I do so I would like to discuss the idea here.

Thanks in advance.

**Comment by markstory** [comment]
In 3.x we have an `engine()` method that lets you fetch a engine by name. I think having a similar method in 2.x is reasonable.

**Comment by tersmitten** [comment]
I'll give backporting that method a try, OK?

**Comment by tersmitten** [comment]
@markstory 

I've put something together, but this still does not make it possible to call methods on the `SplFileObject` (`$_File`), `Redis` (`$_Redis`), `Memcache` (`$_Memache`) or `Memcached` (`$_Memached`) objects directly.

How do you feel about exposing these to? And how would you implement this?

**Comment by markstory** [comment]
> How do you feel about exposing these to?

Do we need to? For engines that expose more features that the CacheInterface does, the Engine class could expose wrapper methods that enforce the engine settings where possible.

**Comment by tersmitten** [comment]
You are probably right. I'll just create an extended Engine class with more functionality, or are you interested in incorporating this in existing classes?

**Comment by markstory** [comment]
> I'll just create an extended Engine class with more functionality, or are you interested in incorporating this in existing classes?

Depends on how many methods you would like to add. If for example we'd be adding a wrapper for every method on Redis/Memcached I wouldn't be very interested as at that point you should probably just use a basic Redis/Memcached client.

**Comment by markstory** [comment]
Closing as 2.10 was the last feature release for 2.x and this wasn't ready for that release.
