### ISSUE TITLE
Cannot convert value to bool : InvalidArgumentException

### ISSUE THREAD

**Issue by sahdev0** [cakephp/cakephp#9751]
Hello,

I am using cakephp 3.3 for my vod application and i want to insert data using following query:

    $query=$notifications->query()->insert(['message' ,'status','user_id' ,'video_id' ,'notify_to' ,'notification_type'])
                            ->values([
                                'message'=>'Congratulations! your video '.$video_name.' has been approved to be uploaded on MM2View by admin.',
                                'status'=>$status,
                                'user_id'=>$user_id[0]['users_id'],
                                'video_id'=>$id,
                                'notify_to'=>1,
                                'notification_type'=>3
                            ])
                        ->execute();

But i am getting 

**Cannot convert value to bool : InvalidArgumentException** Error message. I have done some google related to this problem but did not find any correct solution.  Please help:

![nullerror](https://cloud.githubusercontent.com/assets/10597710/20236581/bb24ffdc-a8df-11e6-809d-27d09c7574cc.PNG)

**Comment by ADmad** [comment]
Looks like one of your fields is a boolean field (tinyint(1) in mysql) and you are passing it a string which can't be converted to boolean.

**Comment by thinkingmedia** [comment]
@sahdev0 

Have a look at this.

http://stackoverflow.com/questions/4775294/parsing-a-string-into-a-boolean-value-in-php

**Comment by sahdev0** [comment]
Thanks. I have converted tinyint to int and my problem has been solved.
