### ISSUE TITLE
Expand ViewCells to cover use cases affected by requestAction depreciation

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#9762]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8
* Platform and Target: apache, mysql

### Pretext
RequestAction is depreciated and superseded by ViewCells.  The RequestActionTrait can be attached to any object, where the CellTrait can only be attached to controllers and views.

### Issue
There are cases which some logic will wrap a viewcell call.  Limiting the CellTrait to the controller or view forces too much logic into the controller and view.  These limitations complicate making my app DRY and makes controllers/views heavier than I'd like.

### Proposal
Expand the CellTrait such that it could be used in more places.  If not *all* places like the RequestActionTrait, then perhaps just components and helpers?  With those being the DRY enablers of a controller/view, I'd imagine that would be acceptable?

**Comment by thinkingmedia** [comment]
It is not clear what you are asking for. Please provide example code of how the proposal might look.

**Comment by watermark** [comment]
Hopefully this helps.  https://gist.github.com/watermark/15153c30d03443071813f731699e812e

I'm proposing that the CellTrait be enhanced such that it can be attached and used from a component and helper.

**Comment by markstory** [comment]
If you really need RequestActionTrait, you'll always be able to move it into your application code in the future.

In both Components and Helpers you have access to the Controller/View that can then provide access to cells? Is there more that is required than that?

**Comment by watermark** [comment]
I've always considered it bad policy to use depreciated code when writing new code.  Plus, my IDE makes me feel really bad about using depreciated code :)

You're correct that cells are accessible by using the controller/view from the component/helper; however, the CellTrait is not attached to the core Cake\Controller\Controller, so then you have a component that can only be used on controllers that attach the CellTrait, which seems incorrect.

If "use the controller/view from the component/helper" is the recommended method, than I would argue that the CellTrait should be attached to the default core Cake\Controller\Controller.

**Comment by markstory** [comment]
If you application need cells that pervasively then you could use the CellTrait in AppContoller. I am not sure it needs to be in the base class as I am not confident that many people need to replace requestAction() calls inside gelpers and components.

**Comment by watermark** [comment]
That makes the component not as contained as I'd like.  If my use case is as rare as you suspect, then I suppose I'll use the mentioned workarounds.

**Comment by markstory** [comment]
@watermark It may or may not be rare. I've personally not used requestAction() extensively ever.
