### ISSUE TITLE
TranslateBehavior has collision problems when the table name is used twice

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#9764]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8
* Platform and Target: PHP 5.6, MySQL 5.6

### What you did
```
$record1 = TableRegistry::get('Vendor/Table1.TranslationKeys')
    ->find('all')
    ->where(['key' => 'One'])
    ->first();

$record2 = TableRegistry::get('Vendor/Table2.TranslationKeys')
    ->find('all')
    ->where(['key' => 'Two'])
    ->first();
```

### What happened
Translations for the second record are being taken from the first table.

### What you expected to happen
Translations for the second record should be taken from the second table.

This can be fixed by changing the `alias` used in `TranslateBehavior::setupFieldAssociations` and `TranslateBehavior::beforeFind` from

``
$alias = $this->_table->alias();
``

To
``
$alias = Inflector::slug($this->_table->registryAlias());
``

I'm pretty sure this came up in the past, so not sure when it broke.

**Comment by lorenzo** [comment]
This is not just a `TranslateBehavior` thing, it happens with all the tables, duplicate aliases are not allowed.

**Comment by patrickconroy** [comment]
It happens because the logic for determining which table to use in the `TableRegistry` is done in `TranslateBehavior` and it's wrong.

**Comment by lorenzo** [comment]
I don't think there is a real way of fixing this, probably your fix can take us far enough, but in general the framework assumes not duplicated table aliases, so it will most likely fail later on
