### ISSUE TITLE
RequestHandler json dots in pass parameter

### ISSUE THREAD

**Issue by gringlas** [cakephp/cakephp#9765]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8
* Platform and Target: MacOS 10.11.6, PHP 5.6.14

### What you did
I have a route scope api running with extension json, like:

```
Router::scope('/api', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Applications', [
            'actions' => ['view'],
            'pass' => ['id'],
            'id' => '[.a-zA-Z0-9_-]+'
        ]
    ); 
});

```

I have routes like _localhost/myapp/api/applications/com.mycompany.myapp.json_, which were working fine for nearly 2 years now (I'm not quite sure from version I updated, but I guess it has been in the 3.3. branch). 
It extracted _com.mycompany.myapp_ as $id, which i could you use in ApplicationsController::view(). 

 
### What happened
But today I recognized, that I recieve _com.mycompany.myapp.json_ . It seems like the RequestHandler won't cut away the .json anymore, when there are . (dots) in the pass part of the URI.
When i.e. I'm using _localhost/myapp/api/applications/wurstwasser.json_ I recieve wurstwasser (without trailing json).  

### What you expected to happen
I expect to get _com.mycompany.myapp_ from _localhost/myapp/api/applications/com.mycompany.myapp.json_

**Comment by AD7six** [comment]
This

    'id' => '[.a-zA-Z0-9_-]+'

Is the same as

    'id' => '.+'

Because `.` in a regex means any character. You probably need to escape it (`\.`).

**Comment by gringlas** [comment]
Whoops, you're right, thanks. 
But sadly that won't fix my issue. I still get the .json part in my passed $id variable. 
I changed the regex to _[\.a-zA-Z0-9_-]+_, which should only allow dots, and characters from a to z in target string with at least 1 to n appearances, but I still recieve the trailing _.json_ part. 
I have installed my app with cakePHP 3.3.5. on a rackspace server running PHP 5.6.27 and there it's working.  
I tried a bit more and when having a passed parameter like com.myapp.mycompany_andsomemore.json the .json part will be cut of in $id. But as soon as I add another dot afterwards the _ part i will geht whole string with .json again...

**Comment by markstory** [comment]
This might be related to the changes in #9647

**Comment by thinkingmedia** [comment]
@markstory this `preg_match('/\.([0-9a-z\.]*)$/', $url, $match);` is very greedy.

**Comment by markstory** [comment]
@thinkingmedia Now that you mention it, it does look very greedy. I'll see how to make it less greedy without reverting #9647

**Comment by thinkingmedia** [comment]
@markstory there are unit tests to verify greedy extensions.

`.xml` is support to match `.xml` and also `.xml.gz`

which I don't understand why.

**Comment by thinkingmedia** [comment]
sorry, we posted at the same time. lol

**Comment by thinkingmedia** [comment]
Wait, I might be wrong.

```
$route->extensions(['pdf', 'json', 'xml', 'xml.gz']);
```

That should not require a greedy extension match for each type.

**Comment by thinkingmedia** [comment]
oh I think I see what's happening. There is a generic regex to extract the extension, and then it's matched to a list of allowed extension types.

That sounds backwards to me. Shouldn't the regex be generated from the list of allowed extensions?

**Comment by markstory** [comment]
> That sounds backwards to me. Shouldn't the regex be generated from the list of allowed extensions?

That sounds better to me. Do you want to take a swing at fixing this?

**Comment by thinkingmedia** [comment]
Sure, I'll open a PR for this tonight.

I'll fix this problem by adding a regex. That way we'll have two problems.

**Comment by thinkingmedia** [comment]
closing as PR is up now.
