### ISSUE TITLE
2.8: ClassRegistry::init() an alias of a model

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#9766]
This is a:

* [x] bug

* CakePHP Version: 2.8.2

### What you did
```php
$Aco = ClassRegistry::init([
    'class' => 'Aco',
    'alias' => 'CurrentAco'
]);
```

### What happened
`Aco` model is returned with both `name` and `alias` properties set to `Aco`.

### What you expected to happen
A **new** `Aco` model instance, with alias set to `CurrentAco`.

**Comment by markstory** [comment]
When you do that call, does the registry already have the `CurrentAco` alias set?

**Comment by davidsteinsland** [comment]
No, it's brand new.

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce :smile:

**Comment by markstory** [comment]
I wasn't able to reproduce this in the test suite. Both a fresh instance, and an instance with a new alias were returned with the correct alias. See 66363e6

**Comment by davidsteinsland** [comment]
I'm betting it has something to do with the fact that `Aro`, `Aco`  and `Permission` does not inherit `AppModel`. Here's a test case:

```php
$tests = [
	'Permission' => 'CurrentPermission',
	'Aro' => 'CurrentAro',
	'Aco' => 'CurrentAco',
	'User' => 'Manager'
];
ClassRegistry::flush();
foreach ($tests as $model => $alias) {
	$obj = ClassRegistry::init([
		'class' => $model,
		'alias' => $alias
	]);

	printf("%s::alias === %s\n", $model, $alias);
	var_dump($obj->alias === $alias);
}
```

Output:
```
Permission::alias === CurrentPermission

/app/src/Controller/AppController.php:154:boolean false

Aro::alias === CurrentAro

/app/src/Controller/AppController.php:154:boolean false

Aco::alias === CurrentAco

/app/src/Controller/AppController.php:154:boolean false

User::alias === Manager

/app/src/Controller/AppController.php:154:boolean true
```

Only the `User` model gets a correct alias.

**Comment by markstory** [comment]
This sounds like it might be a problem with the `Aco`,  `Aro`, `AclNode` models instead of `ClassRegistry`. All those models share a constructor that [does not pass settings to the parent constructor](https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/AclNode.php#L43-L48).

**Comment by markstory** [comment]
Fix for the AclNode constructor is up now.
