### ISSUE TITLE
Reduce use of duplicate code for transactions

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9773]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4

### Transactions

This enhancement pertains to the `\Cake\ORM\Table` class. Which implements the following pattern for transactions in several methods.

```
     $process = function () {
              // do inner work here
     }

     $connection = $this->connection();
     if($atomic) {
          $result = $connection->transaction($process);
     } else {
          $result = $process();
     }
```

The above is a generalization, but often the `$process` is replaced with an extra `_privateProcess` function which results in the main function being split apart (just to handle transactions).

I propose a change where transaction support doesn't require duplication of code or the use of a private function.

Something like this for the above:

```
    // returns a new atomic object
    $atomic = $this->getAtomic($atomic, function() {
        // do work here
       return $result;
    });

    // handle edge-cases like this
    $atomic->afterNoneAtomic(function() {
            $this->dispatchEvent('......');
    });

   // executes above when calling getResult
   return $atomic->getResult();
```

The idea here is to reduce code duplication for atomic operations, and improve the readability of Table methods so that less `if` statements are used to handle common conditions (i.e. functions often check if inside a transactions and atomic is true).

**Comment by markstory** [comment]
In other libraries this is sometimes referred to as a 'Unit of work'.

**Comment by thinkingmedia** [comment]
closing as PR is up
