### ISSUE TITLE
Router doesn't allow single-character parameter names

### ISSUE THREAD

**Issue by francoischalifour** [cakephp/cakephp#9777]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.6
* Platform and Target: Apache 2.4.7 (Ubuntu), PHP 5.5.9, MySQL

### What you did

I created a route with 3 parameters containing an `id`, and two coordinates `x` and `y`:

```php
$routes->connect('/fighters/:id/move/:x/:y', ['controller' => 'Fighters', 'action' => 'move'], ['id' => '\d+', 'x' => '\d+', 'y' => '\d+', 'pass' => ['id', 'x', 'y']]);
```

I then created the appropriate method in the `FightersController`:

```php
class FightersController extends AppController {
    public function move($id, $x, $y) {
        // ...
    }
}
```

Finally, I tried to created a link to this route in the view:

```php
$this->Html->link('Move', ['plugin' => null, 'controller' => 'Fighters', 'action' => 'move', 'id' => $fighter->id, 'x' => $x, 'y' => $y]);
```

### What happened

This route is not recognized as such, apparently because the router **doesn't allow single-character parameter names**.

The problem was solved when I renamed `x` to `coordinate_x` and `y` to `coordinate_y`.

### What you expected to happen

This problem is not specified in the [documentation](http://book.cakephp.org/3.0/en/development/routing.html#passing-parameters-to-action). I therefore thought single-character parameter names would work.

Is there a reason for such a behavior?

**Comment by markstory** [comment]
Pull request open now.
