### ISSUE TITLE
CookieComponent throwing fatal errors on corrupted data

### ISSUE THREAD

**Issue by nebojsac** [cakephp/cakephp#9779]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9.
* Platform and Target: PHP 5.6.23, nginx, Ubuntu 14.04.3 LTS

### What you did
We had updated from CakePHP 2.7.x, and pushed the update to our server.

### What happened
Beyond the CakePHP update, the methods related to this issue haven't been updated for at least a year without issues. The failing code is:

```php
		if($this->Cookie->check('User.someKey')){
			$this->Cookie->delete('User.someKey');
		}
```

After the update some pages were failing because of Fatal Errors. Further investigating showed that it originates in `Hash->_simpleOp()` with the following error:

`Argument 1 passed to Hash::remove() must be of the type array, string given, called in /path/lib/Cake/Controller/Component/CookieComponent.php on line 340 and defined in [/path/lib/Cake/Utility/Hash.php, line 340]`

And this fatal error:

`"PHP message: PHP Fatal error:  Cannot unset string offsets in /path/lib/Cake/Utility/Hash.php on line 319"`

After adding some logging, this is what I get as the contents of `$_list`:
```
A���#�r�V�C�?t����^
```
So, gibberish. I assume this is a corrupted Cookie, based on the stack trace. Still I don't think it should be allowed to cause a Fatal error. For now I've added some extra checks as fallback, to keep the site running until we can pinpoint the cause. The updated method(includes logging) is now:

```php
	protected static function _simpleOp($op, $data, $path, $values = null) {
		$_list =& $data;

		$count = count($path);
		$last = $count - 1;
		foreach ($path as $i => $key) {
			if ((is_numeric($key) && intval($key) > 0 || $key === '0') && strpos($key, '0') !== 0) {
				$key = (int)$key;
			}
			if ($op === 'insert') {
				if ($i === $last) {
					if (is_string($key) AND is_array($_list)) {
						$_list[$key] = $values;
					} else {
						if (class_exists('CakeLog')) {
							CakeLog::write('debug', 'hash_insert: $_list:' . print_r($_list,true));
							CakeLog::write('debug', 'hash_insert: $key:' . $key);
						}
					}
					return $data;
				}
				if (!isset($_list[$key])) {
					$_list[$key] = array();
				}
				$_list =& $_list[$key];
				if (!is_array($_list)) {
					$_list = array();
				}
			} elseif ($op === 'remove') {
				if ($i === $last) {
					if (is_array($_list) AND isset($_list[$key])) {
						unset($_list[$key]);
					} elseif (class_exists('CakeLog')) { // debug for odd Cookie errors
						if ($key=='hideReferer') {
							CakeLog::write('debug', '$_list:' . print_r($_list,true));
							CakeLog::write('debug', '$key:' . $key);
						} else {
							CakeLog::write('debug', 'Hash error for $key:' . $key);
							CakeLog::write('debug', '$_list:' . print_r($_list,true));
						}
					}
					return $data;
				}
				if (!isset($_list[$key])) {
					return $data;
				}
				$_list =& $_list[$key];
			}
		}
	}
```

I'd like to know if it's worth adding similar checks to the Core. I would gladly create a PR with Unit Test coverage if you think it is the right approach to this problem. 

### What you expected to happen
Expectation would be that Cookies get unset correctly without issue, to fail gracefully or to throw an Exception.

**Comment by nebojsac** [comment]
Actually, after more digging, I guess the problem isn't with `Hash`. The check for valid data should happen in the `CookieComponent`, and it shouldn't pass parameters of the wrong type to the `Hash` methods. Is that correct?

**Comment by markstory** [comment]
> Actually, after more digging, I guess the problem isn't with Hash. The check for valid data should happen in the CookieComponent, and it shouldn't pass parameters of the wrong type to the Hash methods. Is that correct?

I think this sounds like a better plan.

**Comment by nebojsac** [comment]
Thanks! More debugging shows it happens in `Cookie->delete()` and in `Cookie->read()`. 

Neither of these return error information. What should happen in case of corrupted data? Just fail gracefully / return void?

**Comment by markstory** [comment]
> Neither of these return error information. What should happen in case of corrupted data? Just fail gracefully / return void?

I think so. Logging an error won't help clean up the corrupted cookie data.

**Comment by nebojsac** [comment]
Yea the logging was temporary, for debugging.
Will see about a PR during the week, thanks for taking a look!

**Comment by markstory** [comment]
Pull request up now.
