### ISSUE TITLE
Cookie->read() returns true for sub-keys that don't exist.

### ISSUE THREAD

**Issue by nebojsac** [cakephp/cakephp#9784]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9
* Platform and Target: PHP 5.6.23, nginx, Ubuntu 14.04 LTS

### What you did
Used `$this->Cookie->check('User.someKey')` on a key that does not exist. `User` does exist as a key though.

### What happened
It returned `true`.

### What you expected to happen
It should have returned `false` because `someKey` does not exist.

Here's a failing test for CookieComponentTest, to reproduce:

```php
 * Test checking for key that does not exist.
 * 
 * @return void
 */
	public function testCheckMissingKey() {
		$_COOKIE['CakeTestCookie'] = array(
			'User' => 'stringdata'
		);
		$result = $this->Cookie->check('User.notFound');
		$this->assertFalse($result, 'Key does not exist in Cookie.');

		$result = $this->Cookie->read('User.notFound');
		$this->assertNull($result, 'Key does not exist in Cookie.');
	}
```

This is the culprit code in `Cookie->read()`:
```php
		if (strpos($key, '.') !== false) {
			$names = explode('.', $key, 2);
			$key = $names[0];
		}
```
In cases where you check for `User.someKey` it overrides it with just `User` in the check. From my perspective this is not expected behaviour(it is also not documented as such in the docBlock). Found this while investigating #9779 further.

**Comment by nebojsac** [comment]
Actually, using dot notations and keys (ex. 'User.someKey') with the `CookieComponent` is somewhat broken in general. Reading, deleting, writing and checking for keys.

I assume the `CookieComponent` should work similar to `CakeSession` in terms of the dot notation. Should probably return useful info instead of `void` as well, so that we can check if a cookie write failed.

**Comment by markstory** [comment]
> I assume the CookieComponent should work similar to CakeSession in terms of the dot notation. Should probably return useful info instead of void as well, so that we can check if a cookie write failed.

I agree. We used to return void as the assumption was that writes would succeed. In the delete() case, returning void makes sense to me as the key is 'no longer there' which was the goal.

**Comment by nebojsac** [comment]
> I agree. We used to return void as the assumption was that writes would succeed. In the delete() case, returning void makes sense to me as the key is 'no longer there' which was the goal.

Sounds good for write() and delete(). Yea, delete() doesn't have to return anything, as long as it's only passing arrays to Hash::remove(). Will work on a PR.

**Comment by markstory** [comment]
@nebojsac Awesome!

**Comment by markstory** [comment]
Pull request up now.
