### ISSUE TITLE
Tests fixtures: Cannot create fixture when the table has an index on an enum field

### ISSUE THREAD

**Issue by scallacs** [cakephp/cakephp#9785]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: MySql database and Apache server

### What you did
Trying to load fixtures from a table that contains an enum field and an index on this enum field. Table definition is loaded from an existing db table: 
`public $import = ['table' => 'mytable', 'connection' => 'default'];`

### What happened
Apparently enum types are not supported in Cakephph and they are converted as TEXT. However MySql does not support field TEXT as index and show me a warning.
`Warning Error: Fixture creation for "mytable" failed "SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'myfield' used in key specification without a key length" in [...PROJECT...\vendor\cakephp\cakephp\src\TestSuite\Fixture\TestFixture.php, line 306]`

### What you expected to happen
It should work...

**Comment by markstory** [comment]
One potential solution we could do is to map unknown columns into `VARCHAR`. At least those columns can have indexes applied to them.

**Comment by dereuromark** [comment]
Isnt that done already in 3.3.x?

**Comment by markstory** [comment]
@derekperkins

**Comment by markstory** [comment]
@dereuromark Yes it is! I had forgotten about that. @scallacs Can you try upgrading to 3.3.8?

**Comment by scallacs** [comment]
@markstory I've upgraded to 3.3.9 and still have the same issue..

**Comment by markstory** [comment]
What does the schema of the problematic table look like?

**Comment by markstory** [comment]
@dereuromark The pull request you're thinking of is #9599 which was merged into 3.next. Given that this is fixed in an upcoming release I'm hesitant to do any changes now as the change made in #9599 will solve this and column detection issues for other unknown types as well.

Closing as a fix has already been merged into an upcoming release.
