### ISSUE TITLE
Is there possible to migrate many to many

### ISSUE THREAD

**Issue by levend18** [cakephp/cakephp#9789]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

I'm trying to use bin\cake bake migration CreateIsShowInstitutions user._ids:integer Institution._ids:integer
But this is not working.
Is this possible to work with like that. when i do that. This command create 2 tables automaticly and  works fine.

**Comment by markstory** [comment]
I don't think migrations supports the behavior you're trying to achieve. You would have to create all 3 tables individually right now.

**Comment by markstory** [comment]
This issue was moved to cakephp/migrations#277
