### ISSUE TITLE
CakePHP 3 how to create Multilanguage Site

### ISSUE THREAD

**Issue by Zero-jano** [cakephp/cakephp#9790]
Hi
I want to know how can be create Multilanguage Site for CakePHP 3 framework in fully steps.
and how can router to language when user selected. 
because i can't understand document for how can start step by step
thanks.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
