### ISSUE TITLE
Separating the IntegrationTestCase out into a Trait

### ISSUE THREAD

**Issue by ascii-soup** [cakephp/cakephp#9794]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.7

We are about to embark on some integration testing in a project we're working on. For unit testing we have our own base TestCase classes which we need to do the integration testing too. However, the IntegrationTestCase is a class that contains all its behaviour which means we can't re-use it very easily.

I wondered if it would be possible to move the functionality of IntegrationTestCase into a trait so that it can be easily shared amongst custom base TestCase classes. I imagine the IntegrationTestCase class remaining, but having its contents changed to something like the following:

```php
<?php

abstract class IntegrationTestCase extends TestCase
{
    use CookieCryptTrait;
    use SecureFieldTokenTrait;
    use IntegrationTestTrait; // the functionality would simply be moved here
}
```

I'm happy to do the work involved and submit a PR but I wanted to run it past you first to see if the idea is at least sound in theory. My limited initial testing seems to work but it would need more testing if it were to happen.

Any comments, suggestions, reasons it wouldn't work?

**Comment by markstory** [comment]
I think if we can extract a trait that doesn't have dependencies on other traits or inherited methods then this sounds pretty reasonable.

**Comment by swiffer** [comment]
@markstory 

Moving from `...extends IntegrationTestCase` to `use IntegrationTestTrait`

BREAKS:
```php
class SampleControllerTest extends TestCase
{
    use IntegrationTestTrait;

    public function setUp(){
        parent::setUp();
    }
}
```

POSSIBLE SOLUTION:
```php
class SampleControllerTest extends TestCase
{
    use IntegrationTestTrait {
        tearDown as traitTearDown;
        setUp as traitSetUp;
    };

    public function setUp(){
        self::traitSetUp();
    }
}
```

Should this be mentioned somewhere in the docs / migration guide?

I'm using setUp for additional preperation...

e.g.
```php
        // Fake out SSL connections.
        $this->configRequest([
            'environment' => ['HTTPS' => 'on']
        ]);
```

**Comment by markstory** [comment]
We could use the `before` and `after` annotations in the trait. That would remove the need for workarounds or documentation.

**Comment by swiffer** [comment]
what would it look like in my TestCase?

**Comment by markstory** [comment]
You would continue using setup/tear down as usual, and not need to do any method aliasing for the trait.
