### ISSUE TITLE
array_shift microoptimisation

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#9795]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

while i know most of these optimisations are not worth doing and maybe even this one isnt worth its time but at least i think its worth short discussion

the subject came on reddit: https://www.reddit.com/r/PHP/comments/5eqhwa/performance_of_array_shift_and_array_pop_in_php/
and look at those times! 
```
array_pop takes 0.00089 seconds
array_shift takes 15.15544 seconds
array_reverse + array_pop takes 0.03934 seconds
```

i did short test on my own with php7 and it gave me
```
array_pop takes 0.00107 seconds 
array_shift takes 0.82245 seconds 
array_reverse + array_pop takes 0.00685 seconds
```

while the numbers arent that impressive anymore its still 120x faster, i did quick search on array_shift on repo https://github.com/cakephp/cakephp/search?p=1&q=array_shift&utf8=%E2%9C%93 and there are some possible use case like loops, some traits

**Comment by markstory** [comment]
The usages in Routing, Hash::get(), and the ORM might be worth updating.

**Comment by JayPHP** [comment]
Considering the minuscule change this will make with _normal_ sized arrays (https://3v4l.org/ZU0O1#v5625) Is this really worth doing over readability? 
Just having `array_shift `is more readable than having to reverse the array + pop it imo

**Comment by thinkingmedia** [comment]
I'd rather bake routing to a serialized object in the cache and have the code that bakes it readable.

**Comment by dereuromark** [comment]
Closing then for now. If anyone wants to make a PR here for certain parts, this can be discussed for the concrete case.
