### ISSUE TITLE
Out view url no valid, change "_" to "-" in parant action url /users/password-change ;-(

### ISSUE THREAD

**Issue by EOM** [cakephp/cakephp#9797]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Platform and Target: MySQL 5.5, Windows 10 64Bit, PHP 5.6, Apache 2.2 

### What you did
In View echo Form to **'action' => 'password_change'**
`<?= $this->Form->create('Users', ['url' => ['controller' => 'Users', 'action' => 'password_change'], 'type' => 'post']) ?>`

In Controller **Users** action **password_change**
```
public function password_change()
{
   ....
}
```

### What happened
Out view url no valid, change "_" to "-" in parant action url /users/**password-change** ;-(
```
<form method="post" accept-charset="utf-8" action="/users/password-change">
.....
</form>
```

### What you expected to happen
Out view url /users/**password_change** as in old versions of cakephp ;-)

```
<form method="post" accept-charset="utf-8" action="/users/password_change">
.....
</form>
```

**Comment by josegonzalez** [comment]
If you are using the `DashedRoute` class as your default route class in `config/routes.php`, the url will be dashified as you see above. If you don't want that behavior, you'll need to change your default route class.

**Comment by dereuromark** [comment]
The route class you are looking for is "Inflected", see documentation.

**Comment by EOM** [comment]
My Set Inflected

```
// Set soporte models in spanish
Inflector::rules('plural', ['/^(.*)$/i' => '\1']);
//Inflector::rules('singular', ['/^(.*)$/i' => '\1']);
Inflector::rules('uninflected', []);
Inflector::rules('irregular', []);
```

**Comment by dereuromark** [comment]
It is not about the Inflections, it is about Routing, please see http://book.cakephp.org/3.0/en/development/routing.html#default-route-class

**Comment by EOM** [comment]
Ahh is correct @dereuromark , with the class "InflectedRoute" works well as the old version of Cake. / Controller / accion_name_bla /
Question I have some disadvantage of some kind. ?
In using the class "DashedRoute" that is default in CakePHP 3.3 against "InflectedRoute" that behaves like the previous version of Cake ..?
