### ISSUE TITLE
BreadcrumbsHelper::render() should return null

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9798]
I'm trying the new helper and I think that the `render()` method should return `null` (or a blank string) if empty (now it returns the string `<ul></ul>`), in other words if you have not added any crumb.

[Here](http://api.cakephp.org/3.3/source-class-Cake.View.Helper.BreadcrumbsHelper.html#242), it would just return `null` if the property is empty.

If all goes well, I will make the PR.

p.s.
[Here](http://book.cakephp.org/3.0/en/views/helpers/breadcrumbs.html#rendering-the-breadcrumbs-trail) typo in the example (`$this->BreadcrumbsHelper->render()` instead `$this->Breadcrumbs->render()`)

**Comment by dereuromark** [comment]
I agree, it should probably not render out anything for empty list.

That docs page has several typos indeed.

**Comment by mirko-pagliai** [comment]
Other notes: 
1) I think the `render()` method should be compatible with [getCrumbList()](http://api.cakephp.org/3.3/class-Cake.View.Helper.HtmlHelper.html#_getCrumbList). Options `firstClass` and `lastClass` are missing;
2) We could add an option to make the first crumb not clickable;
3) Having regard to the methods that we have, I would add the method `getCrumb($position)`.

**Comment by markstory** [comment]
Couldn't the first class and lastClass be set when the crumbs are added? Same with making crumbs not clickable.

**Comment by mirko-pagliai** [comment]
@markstory No, because it is not obvious that I know what the last crumb, while I add them.

**Comment by mirko-pagliai** [comment]
It is more likely that, before rendering the list, I pull out the last element and add a class, but it is much more complex as well.

**Comment by ADmad** [comment]
Why can't one just use `:first-child`, `:last-child`  pseudo selectors?

**Comment by mirko-pagliai** [comment]
Sure you can do it via css

**Comment by markstory** [comment]
If the styling can be done with pseudo selectors do we need more options?

**Comment by mirko-pagliai** [comment]
I said just for compatibility with the old method, but we can do without ;)
