### ISSUE TITLE
opcache as cacheengine

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp#9799]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

sometime ago ive stumbled upon [blog entry](https://blog.graphiq.com/500x-faster-caching-than-redis-memcache-apc-in-php-hhvm-dcd26e8447ad#.ij0hysdmu) about opcache to be used as cache engine and today ive given it a try im quite happy with first results:

saving:
```php
$data = array_fill(0, 1000000, 'hi');

Cache::write('test', $data, 'file');
Cache::write('test', $data, 'opcache');
```

reading:
```php
       $start = microtime(true);
        for ($i = 0; $i < 10000; $i++) {
           Cache::read('test', 'opcache');
        }
        $stop = microtime(true);
        printf("Opcache %f seconds\n", $stop - $start);

        $start = microtime(true);
        for ($i = 0; $i < 10; $i++) {
            Cache::read('test', 'file');
        }
        $stop = microtime(true);
        printf("File %f seconds\n", $stop - $start);
```

and the results on PHP7.11 are 
```
Opcache 0.023709 seconds 
File cache 1.898870 seconds
```

note that Opcache is read 10000 times and file only 10, so the difference is enormous, while opcache might not be perfect for many cases it might be great for some

heres quick hacky version just for onyone that want quick testing:
https://gist.github.com/Graziel/411ce1200d3affb172d0ee128bf602ff

**Comment by markstory** [comment]
Interesting, in what scenarios would this opcache engine not work?

**Comment by Graziel** [comment]
the obvious one is no opcache enabled :)

the other ones are related to var_export limitations http://php.net/manual/en/function.var-export.php but as i said for now its only small experiment to check the concept from that blog entry so i cannot tell anything else other than that

**Comment by lorenzo** [comment]
Does the file name change on each change? Otherwise it would not work when setting opcahe.stat =0

**Comment by Graziel** [comment]
i dont see any opcache.stat in http://php.net/manual/en/opcache.configuration.php

but on each change you should probably call opcache_invalidate

**Comment by ravage84** [comment]
@Graziel nice find! Do you see any reason why this can't be backported to 2.x? If not, I might do that 😼

**Comment by lorenzo** [comment]
@Graziel sorry, I meant `opcache.validate_timestamps`

**Comment by odan** [comment]
Looks like there's only an "issue" with var_export in combination with circular references.

```php
class Test {
    public $obj;
}
$obj = new Test();
$obj->obj = $obj;

var_export($obj, true);
```
Output:
```
Warning: var_export does not handle circular references
```
https://3v4l.org/p7h4h

This example causes an error:
https://3v4l.org/bnrWs

```
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 4096 bytes) in /in/Pj082 on line 10
```

Source:
http://stackoverflow.com/questions/6292164/using-print-r-and-var-dump-with-circular-reference

**Comment by mirko-pagliai** [comment]
this seems very attractive. why not a plugin?

**Comment by ADmad** [comment]
Is someone interested in pursuing these and coming up with a PR?  If not the issue can be closed. As suggested it's best to do this as a plugin first.

**Comment by mirko-pagliai** [comment]
I think it would be right if @Graziel did it. If he does not have time, I can try it

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
