### ISSUE TITLE
StringTemplateTrait and InstanceConfigTrait

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9808]
This is not a real problem. 

I was writing a trait that uses the `StringTemplateTrait` (but it's only an example).

But it failed because it was not found the `config()` method (called [here](http://api.cakephp.org/3.3/source-class-Cake.View.StringTemplateTrait.html#69)).
And, since this method is not there, I did not understand how the rest of CakePHP could work.

Only after a while I realized that all helpers extend `Cake\View\Helper`, which in turn uses `Cake\Core\InstanceConfigTrait` that provides the `config()` method.

In fact, now, making sure that my trait using `InstanceConfigTrait`, it works.

I'm not as good as you, but I wonder if all this has a logical linearity.

Besides, I could use `StringTemplateTrait` out by a helper. So I'm wondering if it should not be used directly `InstanceConfigTrait`.

Thanks guys :-)

**Comment by markstory** [comment]
I agree it would be better if each trait provided all of the methods it depended on or documented them as being required of implementing classes. Would you be willing to put together a pull request to fix `StringTemplateTrait` so that is included `InstanceConfigTrait`?

**Comment by mirko-pagliai** [comment]
Yes, okay, I can handle it.
Do you know if is it the only case? I'll have to do some tests to make sure to do not break anything.

**Comment by thinkingmedia** [comment]
I've been using `@mixin` to couple traits with another class/trait. Seems to work okay but it doesn't provide any run-time enforcement.
