### ISSUE TITLE
Create a CakePHP Project not work

### ISSUE THREAD

**Issue by tando** [cakephp/cakephp#9809]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: >= 2.9.1

### What you did
Installing CakePHP with Composer.
`Vendor/bin/cake bake project <path to project>`

### What happened
The following error occurs, create project does not work.
`
PHP Warning:  include(/xxx/Config/core.php): failed to open stream: No such file or directory in  xxx/vendors/cakephp/cakephp/lib/Cake/Core/Configure.php on line72
PHP Fatal error:  Can't find application core file. Please create /xxx/Config/core.php, and make sure it is readable by PHP. in /xxx/vendors/cakephp/cakephp/lib/Cake/Core/Configure.php on line 77
`

Probably #9577 is affecting. 
$boot refers to below.

CORE_PATH . 'Cake' . DS . 'bootstrap.php' line432
`
Configure::bootstrap(isset($boot) ? $boot : true);
`

CORE_PATH . 'Cake' . DS .  'Core' . 'Configure.php' line69
`
		if ($boot) {
			static::_appDefaults();
`

**Comment by tando** [comment]
Checked version 2.9.1

**Comment by markstory** [comment]
Closing as #9803 has been merged.
