### ISSUE TITLE
Session issues with facebook sdk in production

### ISSUE THREAD

**Issue by adhikarysunil1** [cakephp/cakephp#9811]
I am new in cakephp. Facebook PHP SDK with cakephp 2 is working with debug mode 1 or 2 but it is not working with debug mode 0. It seems session is not working properly in production. I search about it on the web many times but not get the right solution.

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
