### ISSUE TITLE
[2.next] Adding forUpdate and having for the Model::find() options.

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9812]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.10.0

I would like to use `SELECT FOR UPDATE` in CakePHP2. Without `SELECT FOR UPDATE`, applications would be easy to break. For example:
```php
// In transaction
$count = $this->Bookmark->findCountByUserId($this->Auth->user('id'));
if ($count < 10) {
    $this->Bookmark->save($this->request->data);
}
```
The above code doesn't prevent us from inserting more than 10 records actually.

I found [an old post about SELECT FOR UPDATE](http://bakery.cakephp.org/2012/04/14/SELECT-FOR-UPDATE-hack-kind-of-ugly-but-it-works-PostgreSQL-and-MySql.html)  in the Bakery, but it doesn't work in CakePHP2. If `Model::find()` supports for the `forUpdate` option, we can do it easy:
```php
// In transaction
$count = $this->Bookmark->find('count', [
    'conditions' => ['user_id' => $this->Auth->user('id')],
    'forUpdate' => true,
]);
if ($count < 10) {
    $this->Bookmark->save($this->request->data);
}
```
`forUpdate` will be mapped to a correct statement for each database drivers.

If people don't mind, I would like to also allow users to call it dynamically, like the first example:
```php
$count = $this->Bookmark->findCountByUserIdForUpdate($this->Auth->user('id));
```
The alternative option is to add `epilog`, like CakePHP3. Personally, I would like to add `forUpdate`, as it allows people to write non database-specific code. But if people prefer `epilog` over `forUpdate`, I take the opinion.

Adding `having` is not a main issue. But I can add it while I am implementing `forUpdate`.

**Comment by markstory** [comment]
Would you ever want `FOR SHARE`?

**Comment by chinpei215** [comment]
Personally, I don't need `LOCK IN SHARE MODE` (`FOR SHARE`), as we can do it implicitly by using `SERIALIZABLE` transaction isolation level for the purpose. But if people want it, I am fine with implementing it too.

**Comment by markstory** [comment]
If we wanted to support more modes perhaps the option name should be different? Perhaps a lock option that supports different 'modes'?

```php
// Lock for update
'lock' => 'update'

// Shared lock
'lock' => 'share'
```

**Comment by chinpei215** [comment]
Agree. I am fine with changing the option name to `lock`.

**Comment by chinpei215** [comment]
Pull request up now.
