### ISSUE TITLE
Getting "Missing View" when MyController::beforeFilter() doesn't return anything

### ISSUE THREAD

**Issue by dvlprs** [cakephp/cakephp#9816]
This is an:

* [x] enhancement

* CakePHP Version: 2.8.4
* Platform and Target: PHP 5.5.38, Linux, Apache, GoDaddy

### What you did

```
<?php 

class MyController extends AppController {
    
    public function beforeFilter() {
    }
    
    public function view() {
        // do stuff
    }
    
}
```

### What happened

> Missing View
> Error: The view for MyController::view() was not found.

### What you expected to happen
Ignore the `beforeFilter()`

I do realise having an empty beforeFilter was my mistake. Took me a while to figure out though. Is this the expected behaviour?

**Comment by ADmad** [comment]
An empty `beforeFilter()` would cause you problem only if you have some code in your `AppController::beforeFilter()` since you failed to call `parent::beforeFilter()`.
