### ISSUE TITLE
New Validation::maxByteLength() addition

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#9817]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.9.3

What's the reason that `Validation::maxLength` is in characters. When storing data in the database maximum lengths (e.g. `VARCHAR(255)`) are always in bytes right?

And are there any objections to adding a `$bytes` option (default `false`)?

**Comment by markstory** [comment]
> What's the reason that Validation::maxLength is in characters.

Because humans think in terms of characters, and when our validation methods were in bytes, there were a few issues opened by non-latin users that the methods were 'wrong'.

**Comment by tersmitten** [comment]
I understand, but are you open to adding the option?

**Comment by dereuromark** [comment]
What is the use case for you?
As mark said, 99% of all cases never care about bytes, it is about characters, with utf8mb4 even more so, an Emoji is 1 character, not 4 bytes.

**Comment by tersmitten** [comment]
What the recommended way to check that string of 200 characters fits in a varchar(255), utf encoding?

In mysql 5.6, but better in 5.7 you have more control of error messages in case of truncation, or out of range data, but before that it's just blindly discarded...

**Comment by dereuromark** [comment]
You should use uft8mb4 . Don't workaround the actual root issue.

**Comment by tersmitten** [comment]
And then you use `Validation::maxLength`, with length `255 / 4`?

**Comment by dereuromark** [comment]
No normal length and mb_strlen() etc. We just said twice that you should only care about characters not bytes.

**Comment by dereuromark** [comment]
You might find [this](http://www.dereuromark.de/2016/11/11/emoji-and-cakephp/) article useful.

**Comment by tersmitten** [comment]
I already read it :-) 

But I still don't understand what you mean...

> No - normal length validation and inside code always mb_strlen() etc. We just said twice that you should only care about characters not bytes.

Does that mean that if you want to save 255 characters, that you use a `text` field in mysql?

**Comment by chinpei215** [comment]
> When storing data in the database maximum lengths (e.g. VARCHAR(255)) are always in bytes right?

@tersmitten I think you have a misunderstanding about `VARCHAR`. The answer of the above your question is: No, it is always in characters. You can store `あ` (a 3-bytes character in utf8) into `VARCHAR(1)` field, if the character set of the field is utf8. However, I think it is reasonable to add `maxByteLength()` or something. I sometimes use `VARBINARY`, and probably, that is the field type you want.

**Comment by dereuromark** [comment]
I agree. A separate method is reasonable.

**Comment by tersmitten** [comment]
@chinpei215 Thanks for the explanation.

**Comment by chinpei215** [comment]
@tersmitten You are welcome.

**Comment by tersmitten** [comment]
Some more [background information](https://serversforhackers.com/mysql-utf8-and-indexing)

**Comment by chinpei215** [comment]
@tersmitten You might already know, but `255` is not a magic number. The author could declare his password field as `VARCHAR(750)` and could create index, if he used per-column collate. See my example in #7112.

**Comment by thinkingmedia** [comment]
@tersmitten is correct. I ran into this issue on my own project and it's an issue with MySQL.

By default, MySQL uses `utf-8` encoding but it's not true 4 byte support. It's only 3-byte and if you want to store strings with foreign languages it's not going to work. You're going to get byte range errors when writing to the table.

To fix this, you have to set the database to use collation `utf8mb4_unicode_ci` or whats also called `utf8mb4`.

So I did this but maxLength validation was not working. So I have to adjust the length as `255 / 4` just as @tersmitten said above.

We do need to take a closer look at this, and confirm it's working properly. I don't think it is.

**Comment by tersmitten** [comment]
http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html

**Comment by tersmitten** [comment]
> MySQL interprets length specifications in character column definitions in character units. This applies to `CHAR`, `VARCHAR`, and the `TEXT` types.

So I think it should work as @chinpei215 explained

**Comment by dereuromark** [comment]
I only had very few issues so far. 255-4 or sth at the most was the correction for some Fields when upgrading. And only for certain indexes. So no in general it works just fine with varchar255 and utf8mb4.

**Comment by chinpei215** [comment]
@thinkingmedia You can store 🂡 to a `VARCHAR(1)` if the character set of the field is `utf8mb4` in MySQL. And `mb_strlen('🂡')` also returns `1` in PHP. So you need not to divide max length by 4. I am guessing that you forget to set `encoding` to `utf8mb4` in the `Datasources` settings of your `app.php`, or forget to set the character set of the field to `utf8mb4` on your table. If you changed the default charset after creating your table, the character set of your fields would be still `latin1` or `utf8` or something.

**Comment by dereuromark** [comment]
True. My article above also contains a plugin shell tool to safely migrate a Database.

**Comment by thinkingmedia** [comment]
I can't go back and verify my code to see what my original issue was. I'm fine with what ever you all decide.

**Comment by markstory** [comment]
Closing as there are pull requests open now.
