### ISSUE TITLE
json_encode() changes timezone property to be the timezone name

### ISSUE THREAD

**Issue by ifunk** [cakephp/cakephp#9818]
This is a:

* [x] bug

* CakePHP Version: 3.3.9
* Platform and Target: macOS Sierra, PHP 5.6.14

```php
public function testDateTimezone()
{
    $date = new \Cake\I18n\FrozenTime('2016-11-29 09:00:00');
    $this->assertTrue($date->timezone instanceof \DateTimeZone);
    json_encode($date);
    $this->assertTrue($date->timezone instanceof \DateTimeZone);
}
```

The first test assertion works as expected, but the second assertion fails, as `$date->timezone` seems to be modified by the `json_encode()` and becomes the timezone name instead of an object.

**Comment by markstory** [comment]
Looks like this might be a problem caused by the native PHP `DateTime` object.

```php
$d = new \DateTime('2016-11-29 09:11:12');
debug(json_encode($d));
debug($d->timezone);
```

Outputs

```
########## DEBUG ##########
'{"date":"2016-11-29 09:11:12.000000","timezone_type":3,"timezone":"UTC"}'
###########################
/tests/TestCase/I18n/TimeTest.php (line 742)
########## DEBUG ##########
'UTC'
###########################
```

Given this, I'm not sure we'll be able to fix this as the property gets set onto the date object before the user land `jsonSerialize()` method we've implemented is even called. This doesn't seem to be [documented behavior](http://php.net/manual/en/class.datetime.php) from what I can see. Because the property gets set the magic `__get` method is no longer called.

**Comment by ifunk** [comment]
Fair call.

**Comment by markstory** [comment]
Not sure there is much we can do about this given the default PHP behavior.

**Comment by ravage84** [comment]
@markstory  we meight, though, document this subpar situation in the book where people could get burned when using CakePHP.
Not sure, in what cases this could be. @ifunk do you have any suggestions?

**Comment by ifunk** [comment]
@ravage84 I only came across this inconsistency in my tests and was not a real-life scenario. I can't think of a real-life scenario where I would json_encode an object and continue to call methods on the object. Even so, it's not a big deal because you're going to find the issue pretty quickly while developing.

**Comment by ravage84** [comment]
@ifunk thanks for the feedback. So I guess there is really nothing to do for us.
