### ISSUE TITLE
[2.x] Get a blank page after login if loginRedirect is empty and Auth.redirect is the login page.

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9819]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.3

### What you did

1. Setup AuthComponent without the `loginRedirect` option:
```php
public $components = array(
    'Auth' => array(
        'authenticate' => array(
            'Form' => array(
                'fields' => array(
                    'username' => 'email',
                    'password' => 'password',
                ),
                'passwordHasher' => 'Blowfish',
            ),
        ),
    ),
);
```

2. Access a page that contains a link to /users/login.
3. Click the link to the login page. Then `Auth.redirect` will be set to /users/login.
4. Enter email and password correctly, and submit the login n page.

### What happened

Logged in successfully. But I got a blank page.

### What you expected to happen

Logged in successfully. And I get the front page instead.

### Reason

In the above steps, the PHP excecutes the following code:
https://github.com/cakephp/cakephp/blob/f22129b9c73734b3c62dc5570d290f02d67c9bf1/lib/Cake/Controller/Component/AuthComponent.php#L743-L745

But we need to take NULL into account, as same as the following:
https://github.com/cakephp/cakephp/blob/f22129b9c73734b3c62dc5570d290f02d67c9bf1/lib/Cake/Controller/Component/AuthComponent.php#L746-L750

<del>3.x contains similar issue.</del>

**Comment by dereuromark** [comment]
3.4 should be ok though.

**Comment by chinpei215** [comment]
@dereuromark You are right. I didn't check 3.x apps actually. When I saw [this code](https://github.com/cakephp/cakephp/blob/2d5c1eeddeb7808a10c5d6477bda467bd2b8fc41/src/Controller/Component/AuthComponent.php#L757-L764), I thought 3.x contains similar issue. But actually, [another code](https://github.com/cakephp/cakephp/blob/2d5c1eeddeb7808a10c5d6477bda467bd2b8fc41/src/Controller/Component/AuthComponent.php#L296-L298) is blocking to set Auth.redirect to /users/login.

**Comment by chinpei215** [comment]
Pull request up now.
