### ISSUE TITLE
[2.x] Model throws an exception when using external hasOne associations with fields option

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9820]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.3

### What you did

It might not be well known (becase not documented), but we can define `hasOne` association with `limit`, `offset` and `order`, by setting `external` option to `true`:
```php
public $hasOne = array(
    'LatestBookmark' => array(
        'className' => 'Bookmark',
        'foreignKey' => 'user_id',
        'order' => array('LatestBookmark.id' => 'DESC'),
        'limit' => 1,
        'external' => true, // Set `external` to `true`
    ),
);
```

So If I have the association above,
```php
$users = $this->User->find('all', [
    'contain' => [
        'LatestBookmark',
    ]
]);
debug($users);
```
Will output:
```
array(
    (int) 0 => array(
        'User' => array(
            'id' => '1',
            ...
        ),
        'LatestBookmark' => array(
            'id' => '100',
            'user_id' => '1',
            ...
        )
    ),
    ...
)
```
It works as expected.

However, if I add `fields` options to the query, I get an exception:
```php
$users = $this->User->find('all', [
    'fields' => ['id'],
    'contain' => [
        'LatestBookmark' => [
            'fields' => ['id', 'user_id'],
        ],
    ]
]);
debug($users);
```
```
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'LatestBookmark.id' in 'field list'
SELECT `User`.`id`, `LatestBookmark`.`id`, `LatestBookmark`.`user_id` FROM `cakephp`.`users` AS `User`   WHERE 1 = 1
```

**Comment by markstory** [comment]
Interesting find. Not sure what's going on there as Containable is a bit of a black hole.

**Comment by chinpei215** [comment]
I'll take a look later. Since `hasOne` row is fetched by using LEFT JOIN normally, Containable would need to change the `fields` option of the primary query data.

**Comment by ADmad** [comment]
Closing as the issue has gone stale and hasn't had any follow up in over a year.
