### ISSUE TITLE
Prefix is falsely attached to joined table

### ISSUE THREAD

**Issue by mcp84** [cakephp/cakephp#9822]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.3
* Platform and Target: IIS, MySQL

### What you did
I am trying to join a model with a prefix with a table or model that does not have a prefix. Both tables are in the same database.

In this case I'm trying to check which tool has an assigned employee and who that employee is.
Controller:
```
$someThings= $this->Tool->find('all', array(
				'joins' => array(
					array(
						'table' => 'employees',
						'alias' => 'Employee',
						'conditions' => 'Employee.tool_id = Tool.id',
                                                'type' => 'LEFT'
					) 
				)
			));
```
Model:
```
class Tool extends AppModel {
	public $useDbConfig = 'employeedatabase_tools';
```
Config:
```
public $employeedatabase_tools = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'port' => 3306,
		'login' => 'login',
		'password' => 'pw123',
		'database' => 'employees',
		'prefix' => 'tools_',
		'encoding' => 'utf8'
	);
```

### What happened
The prefix is also assigned to the joined table: `LEFT JOIN tools_employees AS Employees ON (Employee.tool_id = Tool.id)`
I tried to add the database manually to the `table` option but the prefix just gets added in front of the database.

### What you expected to happen
A `prefix` option for the joins section would be great. So that you could change the prefix:
```
joins' => array(
			array(
				'table' => 'employees',
				'alias' => 'Employee',
				'conditions' => 'Employee.tool_id = Tool.id',
                                'type' => 'LEFT',
                                 'prefix' => '' // or false or 'someOtherPrefix'
			) 
		)
```

This would not change the behaviour of already existing programs.

**Comment by markstory** [comment]
Related to #9270. Adding option would be more backwards compatible though :+1:

**Comment by markstory** [comment]
Closing as 2.10 was the last feature release for 2.x and this wasn't ready for that release.

**Comment by fr0z3nfyr** [comment]
It's a shame that this enhancement could not make it into 2.10. I'd have loved to see this done in 2.x branch. 

Is there a workaround for such situations in 2.x?

Is this fixed in 3.x?

**Comment by markstory** [comment]
@fr0z3nfyr There is no table/database prefix support in 3.x as no one has contributed a working set of changes. I am not aware of a workaround other than to not use prefixes.
