### ISSUE TITLE
Tinyint fields uses strings as search

### ISSUE THREAD

**Issue by gemal** [cakephp/cakephp#9823]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.2
* Platform and Target: Windows

### What you did
I have a table with
```
user_id INT(10) UNSIGNED NOT NULL,
success TINYINT(1) NOT NULL,
```

### What happened
$this->Test->find("first", array("conditions" => array("user_id" => 0)));
$this->Test->find("first", array("conditions" => array("success" => 0)));

The queries executed are:
```
SELECT `Test`.`user_id`, `Test`.`success`, FROM `test`.`test` AS `Test`    WHERE `user_id` = 0     LIMIT 1
SELECT `Test`.`user_id`, `Test`.`success`, FROM `test`.`test` AS `Test`    WHERE `success` = '0'     LIMIT 1
```

### What you expected to happen
Please note the second query there the 0 is quoted. I would expect both to not be escaped to optimize performance

**Comment by dereuromark** [comment]
Does it work as you expect when you pass `false`?

**Comment by jippi** [comment]
Most / All databases will still use an index for `0` or `'0'` 

`explain select count(*) from users where users.`is_deactivated` = '1'; -- Using index`
`explain select count(*) from users where users.`is_deactivated` = 1; -- Using index`

I can't think of a modern database that won't just fix this on the fly when you do the comparison anyway, it will do one-off conversion before doing the query internally and that's it.

Chances are that the PHP casting would be slower than letting the DB do it. That said, for OCD-friendliness i would like to see the cast. But not for performance reasons.

**Comment by ADmad** [comment]
Given that this behavior has existed in 2.x since ages and doesn't cause any actual problem I don't see the need to change anything.

**Comment by dereuromark** [comment]
@gemal Feel free to provide a PR here for further discussion.
But the "enhancement" here would be rather small as discussed so far.

**Comment by ADmad** [comment]
Closing as there's no "real" issue here and no one seems to be interested in "fixing" it.
