### ISSUE TITLE
Enhancements to the breadcrumbs helper.

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#9829]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

```
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
cakephp/bake                1.2.8              Bake plugin for CakePHP 3.0
cakephp/cakephp             3.3.9              The CakePHP framework
cakephp/cakephp-codesniffer dev-master 631680d CakePHP CodeSniffer Standards
cakephp/chronos             1.0.1              A simple API extension for DateTime.
cakephp/debug_kit           3.4.1              CakePHP Debug Kit
cakephp/migrations          1.6.3              Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    0.0.15             A composer installer for CakePHP 3.0+ plugins.
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
sdustinh@sdustinh:~/github/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper
```

I've been using the `BreadcrumbsHelper` and I have some suggestions for you guys.

```php
$this->Breadcrumbs->add('View Record');
$this->Breadcrumbs->prepend('Records Index', ['action' => 'index']);
$this->Breadcrumbs->prepend('Records Dashboard', ['action' => 'dashboard']);
$this->Breadcrumbs->prepend('Home Page', '/');

if ($this->Breadcrumbs->isEmpty() === false) {
    $addClass = function ($text, $url, $options) {
        $options = $this->Breadcrumbs->addClass($options, 'breadcrumb-item');
    };
    $this->Breadcrumbs->map($addClass);

    $addActiveClass = function ($crumb) {
        if (isset($crumb['options']['active']) === true && $crumb['options']['active'] === true) {
            $crumb['options'] = $this->Breadcrumbs->addClass($crumb['options'], 'active');
        }

        unset($crumb['options']['active']);
    };

    $this->Breadcrumbs->map($addActiveClass);
}
```

or ...

```php
$crumbs = $this->Breadcrumbs->getCrumbs();

if (empty($crumbs) === false) {
    $crumbs = collection($crumbs)->map($addClass)->map($addActiveClass)->toArray();
}

$this->Breadcrumbs->setCrumbs($crumbs, false);
```

The assumed method signature for above was: `public function setCrumbs(array $crumbs, bool $merge = true)`.

It would be nice to have access to some of the methods that we've come to know and love from the rest of the application (specifically the collection trait) to treat the breadcrumbs as kind of a persistent collection object. I don't know if this has been discussed yet - I couldn't find an issue for it anywhere.

The goal I'm trying to reach here is that I'm hesitant to add classes to every `$this->Breadcrumbs->add()` call as that would make updating a big pain. If I could update the templates but then I lose the ability to add custom classes since `render()` doesn't support a `templates` option (though there is always a direct `templater()` call). As it is now it's difficult to modify crumbs that the helper tracks.

What do you guys think?

**Comment by markstory** [comment]
I am partial to the getCrumbs(), setCrumbs() approach personally. That lets us leverage not only the `Collection` class but any other application logic people may have.

**Comment by coryjthompson** [comment]
@sdustinh I've started to work on a setCrumbs. I'm curious in what behavior you would expect if merge was equal to true?

**Comment by sdustinh** [comment]
After reviewing this I think merge was probably a bad idea. I'd probably make it `$append` defaulting to `null`. Then you could call it with just the crumbs to override all crumbs or with a bool to append or prepend an array of crumbs. I know that the `append()` and `prepend()` methods already support an array format so it may just be best to drop the second key and have `setCrumbs()` simply overwrite whatever is currently in the stack.

**Comment by coryjthompson** [comment]
Thank you - I personally agree that it's probably better to leave second parameters off as prepend/append functionality already exists and the function name would be confusing.

**Comment by ADmad** [comment]
If the only problem is not being able to clear existing list before setting new crumbs then why not just add a `reset()` method to the helper?  Then you can then do `$this->BreadCrumbs->reset(); $this->BreadCrumbs->add($array)` to achieve what you want. A new method to set crumbs seems unnecessary and be unnecessary code reputation.

**Comment by coryjthompson** [comment]
I hadn't considered that. There is no reason I can think of and your solution is much more elegant. 
If you don't mind I will create a new pull request with these changes.

**Comment by sdustinh** [comment]
Six in one, I guess. Adding a reset method and then using add to repopulate achieves the same goal. Either way a new method is added so it sounds like it comes down to a uniform api. With the recent movement towards getters and setters it seems natural to have a getCrumbs and setCrumbs.

**Comment by ADmad** [comment]
@coryjthompson Go for it.

@sdustinh We could add a `setCrumbs()` which does the one liner `$this->BreadCrumbs->reset()->add($array);`  but I don't think it's necessary. `setFoo()` methods should be added where actually required, not just because other classes have it.

**Comment by sdustinh** [comment]
:+1: I'm happy either way. I already extended the helper myself so it's just a suggestion. I like the reset just as much as long as the stack itself can be better managed.

**Comment by markstory** [comment]
Closing a there is a pull request open to add reset().
