### ISSUE TITLE
ExceptionRenderer makes use of AppView, causing an infinite loop when missing a Helper.

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#9830]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Platform and Target: Vagrant bento/debian-8.6 with PHP7.0.13-1~dotdeb+8.1

### What I did
I created a new project, where I loaded a git submodule into the plugins in order to start updating my TableHelper plugin. The goal of this project was to setup a sandbox to develop plugins.
I loaded the plugin and then added `$this->loadHelper('TableHelper.Table');` to the `initialize()` method of the default `AppView`.

### What happened
My helper wasn't loaded with the following message on the screen:

> An Internal Server Error Occurred

I checked the error.log of Apache, tried to find an error log of PHP but nothing there. After a couple of hours debugging I found out that my php.ini didn't log php errors. So, changed that and went back into the code and tried to find the log file.

Nothing.

So after a tip on Stackoverflow I kept adding `die()` methods in the core of CakePHP and after another couple of hours, I think I found out what is wrong.

### What I think is wrong

I believe the default `ExceptionRenderer` is using the `AppView` as viewClass, right? Now, when I load a helper that doesn't exist, it will try to render an exception. But, that exception renderer is creating a new instance of `AppView` and thus trying to load the non existing helper again, and again, and again...

At first I thought I was wrong, and I still don't believe it actually, but after some more debugging I think I confirmed this.

### Howto reproduce

- Create a new project, make sure you see the default cake page.
- Add `debug($className);` at https://github.com/cakephp/cakephp/blob/master/src/View/ViewBuilder.php#L362
- Refresh the page, as expected you see `AppView` popup.
- Add an Exception somewhere in `AppController::initialize()`.
- Refresh the page, you'll see `AppView` two times, as expected

This confirms AppView is being used by the ExceptionRenderer.

- Remove the Exception from the AppController
- Add `$this->loadHelper('FooBar')` to `AppView::initialize()`.
- Refresh, your page, now you'll see `AppView` three times and then `An Internal Server Error Occurred`

### What you expected to happen
A 500 Exception with a 'Missing Helper' message of some sort.

### Proposed solution
A dedicated 'ExceptionView' which makes sure no programmer input is messing up the view. If I want the ExceptionRenderer to use my own `AppView` I will have to opt-in, instead of opt-out.

#### PS.
The error.log in the logs dir did log the missing Helper message, but I wasn't expecting this `internal server error` message and so I thought something else was wrong. Therefore I had to dig into it as I believed I was making a mistake.

It was also hard to debug as I tested it on another project (also Cake3) but that uses a custom viewClass (but not for the ExceptionRenderer). So when I loaded a non-existing helper there, it wasn't showing this error as the infinite loop wasn't present. Which caused even more of a headache as I wasn't expecting this simple bug.

**Comment by markstory** [comment]
The challenge with using a 'clean' view class is that people often want to customize the error pages and use their specific layout/helpers in. I don't know how we balance that requirement with this one, even in the opt-in scenario you described this issue can happen. Would you expect this 'clean' view to only be used in debug mode or in all cases?

**Comment by JelmerD** [comment]
You have a very fair point there.

Downside of the 'if debug' part is that you won't be able to debug you Exception views, which I think is what you want to do if creating a custom Error view... On the other hand, it might be the solution:

- if debug mode and exception thrown in View (maybe there are other classes where it might cause a loop?); then we are sure it's an error caused by the programmer; thus, force ErrorView class.

But I don't think it's the best solution. I'm eager to see the opinion of others on this one.

Just crossed my mind, great paradox 😎

What I think we can do already, is add a note in the Cookbook. At least at the Helper part of the book since I think that's the most common cause of this loop.

**Comment by ADmad** [comment]
> The error.log in the logs dir did log the missing Helper message

Given that the logs did don't the primary cause of the problem and there's no easy way to cater to all scenarios I don't think anything needs to be changed.

**Comment by AD7six** [comment]
> The error.log in the logs dir did log the missing Helper message

Kind of curious why this wasn't literally the first place checked

**Comment by JelmerD** [comment]
@AD7six, it was ineed the first place I checked. But I expected an error template, which also shows an example of the Helper I should have created in my Helper dir.

So, because it was a view I did not expect I thought I messed up my Cake installation, that files were corrupted. Causing me to reinstall Vagrant, reinstall Virtualbox, reinit my project, and last but not least, causing a great headache. Therefore, I think we should find a solution, as it is not the error you expect to see.

And @ADmad, if you think it shouldn't be changed, doesn't thst mean we can delete the missingHelper template as well? Since it will never be rendered, right? Correct me if I'm wrong.

Just thinking of this: we can detect if the error was thrown in the vuewClass. Maybe echo a small note before the internal server error message? But I'm not quite sure how to do this properly. It's just a thought.

**Comment by ADmad** [comment]
> Causing me to reinstall Vagrant, reinstall Virtualbox, reinit my project,..

Woah, that some over reaction to an error :)

> doesn't thst mean we can delete the missingHelper template as well? Since it will never be rendered, right?

No, helpers don't need to he explicitly loaded using `loadHelper()` in `AppView` always. You app's helpers can be auto loaded by simply using `$this->Foo` in your view in which case you should get an error page which uses the MissingHelper template.
