### ISSUE TITLE
[RFC] Refactoring the authorization system

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#9835]
This is a follow up of #6925 that deals with the monolithic AuthComponent. Authentication has already been dealt with now it's time for authorization.

This  ticket is a RFC to collect ideas and discuss an implementation on how to refactor the authorization functionality of the framework to provide better separation of concerns and make the code more modular and flexible to work with.

## Problems of the current implementation to solve:

* Authorization very close tied to controllers and components
* Can't handle more granular permissions out of the box like field access on entities
* There is no real base you can use to implement your customized authorization system on. Most people end up extending the AuthComponent or replacing it by using their own implementation.

## Requirements

* Should provide an interface to get and set permissions, accessors and actions
* Must not be tied to anything, the best would be a separate set of classes / services that can be used in any layer of the MVC stack and in other design patterns as well

**Comment by markstory** [comment]
> Must not be tied to anything, the best would be a separate set of classes / services that can be used in any layer of the MVC stack and in other design patterns as well

This is going to be hard to deliver on. Have you used other authorization libraries in the past that you would want to emulate? I've used [pundit](https://github.com/elabs/pundit) in rails, and it works quite well. It provides a framework/conventions for plugging in the required authorization logic. That is then easily used inside controller actions or other classes by including mixins. Laravel has a [similar policy system](https://laravel.com/docs/5.3/authorization#creating-policies).

**Comment by burzum** [comment]
> This is going to be hard to deliver on.

Yes, I'm aware of that. I'll take a look at pundit and the policy system of Laravel. Guess it's something more or less simple but Laravel likes to hide simple things behind pretty fancy sounding names. ;)

I've spent some time with RBAC, there is a nice pdf from the NIST about it. Also RBAC seems to be the favoured permission system for larger applications.

Whatever permission system you implement, it always comes down to asking the same question "Can X access Y?" and "A is allowed / denied to B". I'm not sure this can be abstracted to work with any kind of system but my idea was to have a fluid interface to build these "questions" and permissions. What the underlying question is doing with them is up to the system. I would abstract formulating the access request and executing it two different things. So the "question" could be passed to the actual implementation. Again, it's just an idea, I'm sure there are always edge cases and flaws to be discovered. But that's the purpose of the ticket, discussion and finding a good way to implement it.

**Comment by markstory** [comment]
> I'm not sure this can be abstracted to work with any kind of system but my idea was to have a fluid interface to build these "questions" and permissions. 

I believe it can. The interfaces that libraries like pundit provide afford an interface that is all about 'can user X do Y with resource Z'. RBAC is just an implementation detail at that point. I also think RBAC can be implemented in numerous ways and isn't the kind of thing we should be providing at the framework level.

**Comment by inoas** [comment]
What I'd like to see is a split up of authentication and authorization e.g. core Authorization classes and Authentication classes, if that is in any way reasonable to you.

**Comment by skie** [comment]
I woundn't consider rails solution mostly becasue of ruby mixins that does not work in case of php language. But  laravel Gates and Policies abstractions look reasonable to consider as candidate for new authorization layer. They are flxible enough, and Gates could cover  AuthComponent::allow in simple cases, and Policies suited in any complex case.

**Comment by skie** [comment]
@ionas, the separation of authentication layer already happen as cakephp/authentication middleware. This RFC is next step on separating authorization layer. With having both layers ready it should be easy to rewrite AuthComponent and have it really lightweight.

**Comment by burzum** [comment]
@skie I personally would like to ditch this monster called AuthComponent. There is already no need to for using it for authentication because authentication has already happened before the controller layer is even accessed. And that's the way it should be.

**Comment by markstory** [comment]
Closing as cakephp/authentication exists now.

**Comment by burzum** [comment]
@markstory the plugin just covers authentication, **not** authorization?

**Comment by markstory** [comment]
Derp. I still think this should be closed as we have plans for an authorization plugin as well in the 3.6 roadmap.
