### ISSUE TITLE
Exception "Call to a member function format() on array" when retrieving a db result set as an array

### ISSUE THREAD

**Issue by mongramosjr** [cakephp/cakephp#9839]
* CakePHP Version: 3.3.9
* Platform and Target: MySQL server 5.6.17, MySQL client 5.7.13, PHP 7.0.8 

Hi, 

I wanted to query from a database table with datetime field but it keeps getting me an exception error. See below stack trace. This is the same problem with https://github.com/cakephp/cakephp/issues/8001

Here is the stack trace:

Exception: Call to a member function format() on array in [/u01/vendor/cakephp/cakephp/src/Database/Type/DateTimeType.php, line 114]
2016-12-04 16:40:45 Error: [Error] Call to a member function format() on array
Stack Trace:
1. /u01/vendor/cakephp/cakephp/src/Database/TypeConverterTrait.php(37): Cake\Database\Type\DateTimeType->toDatabase(Array, Object(Cake\Database\Driver\Mysql))
2. /u01/cakephp/cakephp/src/Database/Statement/PDOStatement.php(70): Cake\Database\Statement\StatementDecorator->cast(Array, Object(Cake\Database\Type\DateTimeType))
3. /u01/vendor/cakephp/cakephp/src/Database/ValueBinder.php(148): Cake\Database\Statement\PDOStatement->bindValue('c0', Array, 'datetime')
4. /u01/vendor/cakephp/cakephp/src/Database/Connection.php(275): Cake\Database\ValueBinder->attachTo(Object(Cake\Database\Statement\MysqlStatement))
5. /u01/vendor/cakephp/cakephp/src/Database/Query.php(189): Cake\Database\Connection->run(Object(Cake\ORM\Query))
6. /u01/vendor/cakephp/cakephp/src/ORM/Query.php(958): Cake\Database\Query->execute()
7. /u01/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(276): Cake\ORM\Query->_execute()
8. /u01/vendor/cakephp/cakephp/src/ORM/Query.php(906): Cake\ORM\Query->_all()
9. /u01/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(293): Cake\ORM\Query->all()
10. /u01/src/Model/Table/InvoiceMlmPointsTable.php(125): Cake\ORM\Query->toArray()

**Comment by markstory** [comment]
Are the datetime values strings?

**Comment by mongramosjr** [comment]
You're right I have to marshal the query objects specifically for a datetime field. I found the cause of this problem, two arrays having the same keys was recursively merge into an array. Hence producing below array

```
[InvoiceMlmPoints.date_posted >=] => Array
        (
            [0] => 2016-12-04 00:00:00
            [1] => 2016-11-29 00:00:00
        )
```
It should be this way

```
[InvoiceMlmPoints.date_posted >=] => 2016-11-29 00:00:00
```


Thank you for your prompt response
