### ISSUE TITLE
Add support function time() to timestamp 

### ISSUE THREAD

**Issue by mehdi-fathi** [cakephp/cakephp#9846]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2

### What you did
I was going to save timestamp by itself Behavior.But i can't save function of php time() on my own field as such as created_at.

### What happened
we have no soultion for this issue right?I fixed this problem ?can i send pull request?

**Comment by markstory** [comment]
How can someone reproduce the issue you're having? I don't really understand it right now.

**Comment by dereuromark** [comment]
I think He wants to save int time() values directly instead of using object.

**Comment by markstory** [comment]
ok. That works as far as I know though.

**Comment by mehdi-fathi** [comment]
I want to save an integer containing the current time as a Unix timestamp on my own field by Behavior. @markstory I didn't find about this also document don't mention about it.

**Comment by markstory** [comment]
Ok, but it should work.
