### ISSUE TITLE
ErrorHandlerMiddleware::getRenderer($exception) needs interface

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9851]
There is currently no contract for what the getRenderer must return.
If it, however, does not contain a render() method it will fail. Currently that is not checked at all - or enforced.
The IDE hints this already as yellow - for a good reason.

So 

    protected function getRenderer($exception) {}

should typehint as

    /**
     * @return \Cake\Error\ErrorHandlerInterface
     */

And the handlers (custom or core) must implement this interface containing

- render() 

method

Refs https://github.com/cakephp/cakephp/pull/9806

**Comment by markstory** [comment]
Another interface sounds reasonable to me.

**Comment by dereuromark** [comment]
The name is more appropriately named ExceptionRendererInterface. PR open.
