### ISSUE TITLE
Cookbook section on TestSuites for 3.x has leftover bits from 2.x

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#9852]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] documentation issue

* CakePHP Version: 3.x Cookbook
* Platform and Target: 

### What you did
The 3.x section on creating test suites, http://book.cakephp.org/3.0/en/development/testing.html#creating-test-suites, refers to the CakeTestSuite class which is from 2.x.  The 3.x version is Cake\TestSuite\TestSuite.  It also uses an example of "TESTS" concatenated with "Case/Model", but that should be "TestCase/Model/Table" for the current platform.

**Comment by ravage84** [comment]
Please [open an issue in the correct repository](https://github.com/cakephp/docs/issues).
This is about the framework itself. [cakephp/docs](https://github.com/cakephp/docs/) is about the Cookbook.

**Comment by ADmad** [comment]
This issue was moved to cakephp/docs#4519
