### ISSUE TITLE
Make Table::findOrCreate null-safe

### ISSUE THREAD

**Issue by Code-Working** [cakephp/cakephp#9857]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x
* Platform and Target: 

### What you did
I tried to use the Table::findOrCreate method with properties that may contain null values.

### What happened
Since the properties ($search) are passed to the Query::where method directly, this is not null-safe. The where method translates this to ``property_name` = null`.

### What you expected to happen
It would be nice to have a null-safe function here.

Since CakePHP has the [Automatic IS NULL Creation](http://book.cakephp.org/3.0/en/orm/query-builder.html#automatic-is-null-creation), we simply could append an ' is' to all keys of the search array before passing it to the Query::where method.

If this enhancement is accepted, I could create a pull request for it.

**Comment by thinkingmedia** [comment]
findOrCreate also uses the search query to bootstrap the entity, but that might not be an issue.

I would rather loop the search key/value pairs and create query expressions. That opens the door to support `IN` if a value is an array.

**Comment by Code-Working** [comment]
Good Idea @thinkingmedia, I will create a pull request soon.

**Comment by markstory** [comment]
Closing as a pull request is open.
