### ISSUE TITLE
Paginating Multiple Queries should play better with scopes on view layer

### ISSUE THREAD

**Issue by suhaboncukcu** [cakephp/cakephp#9858]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.9

### What you did
I have an Articles model and I have different types of articles. 
I'm creating a search results page and I want to group my results according to these article types. 
And of course, I want to see separate paginations for each group. 
For instance;
```
TECHNOLOGY ARTICLES
result1 
result2
[[ page numbers for tech articles ]]

SPORTS ARTICLES
result1 
result2
result3
[[ page numbers for sports articles ]]
```

Using `pagination component` on my controller I can achieve different paginations for each group by using the `scope` option:
```php
$articles = $this->paginate($this->Articles, ['scope' => 'tech']);
```
So when I go to following url, I got the correct results:
```
mydomain.com?tech[page]=2
```

After this I try to print my pagination template by using `paginator helper`.  I set the same scope by using `model` option as written in the documentation. 

What I do:
```php
echo $this->Paginator->options(['model' => 'tech']);
echo $this->Paginator->numbers();
```

What I get:
```
By using the model option, PaginatorHelper will automatically use the scope defined in when the query was paginated.
```

### What happened
Instead of paginator numbers, I got this error:
```
Undefined index: pageCount [CORE/src/View/Helper/PaginatorHelper.php, line 731]
```

### What you expected to happen
I would like to see normal  paginator numbers when I don't actually use the Model names but scopes as I dynamically created instead. 

Unfortunately I don't have any proper ideas to implement this feature to suggest.

**Comment by markstory** [comment]
So are you unable to make number for your 'tech' scope?

**Comment by suhaboncukcu** [comment]
I am unable to create numbers for my 'tech' scope with paginator helper, yes.

**Comment by markstory** [comment]
What does the `$this->Paginator->request->params` contain? It should contain a `paging` key with data for both scopes.

**Comment by markstory** [comment]
I took a look and it looks like this issue is caused because you're paginating the same model twice. Paging request data is stored by Model alias. If you modify the alias of your model between `paginate()` calls you should be able to get the behavior you want.

**Comment by suhaboncukcu** [comment]
For future visitors, yes: "I am paginating the same model more than once".

And it seems to be working fine when I change the model alias. Thanks.

**Comment by JayWalker512** [comment]
@suhaboncukcu could you please provide a code example of how you paginated the same model multiple times on one page? I've not had any success with it.

**Comment by swiffer** [comment]
@JayWalker512 figured it out:

```php
    /**
     * @link http://www.ammann.info/cakephp-3-paginating-model-multiple-times-in-the-same-view/
     * @link https://github.com/cakephp/cakephp/issues/9858
     */

    $this->paginate = [
        'SamplesTable' => [
            'scope' => 'samples',
            'limit' => 10,
            'order' => [
                'id' => 'asc',
            ],
        ],
        'AliasedSamplesTable' => [
            'scope' => 'samples_alias',
            'limit' => 10,
            'order' => [
                'id' => 'asc',
            ],
        ],
    ];

    $samples = $this->paginate($this->Samples->find('all'), ['scope' => 'samples']);

    TableRegistry::config('AliasedSamples', [
        'className' => 'App\Model\Table\SampleTable',
        'table' => 'samples',
        'entityClass' => 'App\Model\Entity\Sample',
    ]);

    $aliased_samples = $this->paginate(TableRegistry::getTableLocator()->get('AliasedSamples')->find('all'), ['scope' => 'samples_alias']);
```

**Comment by ravage84** [comment]
I think we can close this issue but should take the example provided by @swiffer from http://www.ammann.info/cakephp-3-paginating-model-multiple-times-in-the-same-view/ and document it.

@swiffer would you be willing to put up a Pull Request that adds such an example on how to paginate the same model multiple times to https://book.cakephp.org/3.0/en/controllers/components/pagination.html ?
Would be a great [Hacktoberfest 2018 ](https://hacktoberfest.digitalocean.com/) contribution, by the way... :wink:

**Comment by swiffer** [comment]
ok! will do this evening :)

**Comment by swiffer** [comment]
@ravage84 https://github.com/cakephp/docs/pull/5873/files

**Comment by JayWalker512** [comment]
I haven't gotten to test this myself yet but THANK YOU @swiffer for looking into this and posting a solution!
