### ISSUE TITLE
Receiving the validation rules inside widget

### ISSUE THREAD

**Issue by blieb** [cakephp/cakephp#9864]
This is a (multiple allowed):

* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10
* Platform and Target: any

Discussed with @hmic on irc about this. At the moment it is not possible to get the validation rules or other configs in a widget (or a helper).

In a widget you get a ContextInterface / EntityInterface. But you can't get the validationrules with it. It is possible to check if a field is required but not the full set of validation rules. I think this should be added. I'm currently building an widget for file upload, and I need to know the filetype. I think the best way to do this is checking the validation rule. I've checked other ways to get some data I define inside a table object, but there is no way to do this. I was thinking about creating a PR for this. but don't know what the best way is to implement this.

**Comment by hmic** [comment]
👍

**Comment by ADmad** [comment]
`$entityContext->entity()->source()` gives you the model name. So you can use `TableRegistry::get()` to the table instance and validator from it.
