### ISSUE TITLE
Parsing numeric strings (FrozenTime)

### ISSUE THREAD

**Issue by jacricelli** [cakephp/cakephp#9866]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* PHP 7.0.14

### What you did
I tried to parse a numeric string using FrozenTime::parse().

### What happened
```php
// debug(Cake\I18n\FrozenTime::parse('20100909'));
object(Cake\I18n\FrozenTime) {
	'time' => '1970-08-21T15:35:09+00:00',
	'timezone' => '+00:00',
	'fixedNowTime' => false
}
```

### What you expected to happen

FrozenTime shouldn't treat numeric strings as timestamps and it should be compatible with DateTime. The second example shows DateTime can actually parse the above value.

See https://github.com/cakephp/cakephp/blob/master/src/I18n/FrozenTime.php#L118

```php
object(Cake\I18n\FrozenTime) {
	'time' => '2010-09-09T00:00:00-03:00',
	'timezone' => 'America/Argentina/Buenos_Aires',
	'fixedNowTime' => false
}

// debug(new DateTime('20100909'));
object(DateTime) {
    date => '2010-09-09 00:00:00.000000'
    timezone_type => (int) 3
    timezone => 'America/Argentina/Buenos_Aires'
}
```

**Comment by markstory** [comment]
I'm not sure we can change this behavior. We rely on that behavior to correctly convert string timestamp values into valid objects. Removing the mentioned block would likely break that use case.

**Comment by jacricelli** [comment]
I'll keep using DateTime.
Thanks.
