### ISSUE TITLE
Error when users logout

### ISSUE THREAD

**Issue by Cafnio** [cakephp/cakephp#9872]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Platform and Target: AWS, Mysql, MemcachedEngine, PHP 7

### What you did
Users login in and logging out on the platform

### What happened
Users are able to login & to logout properly, but it shows an error on logs.

`Warning: Warning (2): session_regenerate_id(): Session object destruction failed. ID: user (path: /tmp) in [/var/app/current/vendor/cakephp/cakephp/src/Network/Session.php, line 567]`

App_aws.php (config file of aws), where i set the sessions database

```
'sessions' => [
            'className' => 'Cake\Cache\Engine\MemcachedEngine',
            'compress' => false,
            'duration' => '+120 minutes',
            'groups' => [],
           'host' => 'xxxxxxx',
            'username' => null,
            'password' => null,
            'persistent' => false,
            'prefix' => 'cake_sessions_',
            'probability' => 100,
            'serialize' => 'php',
            'servers' => ['xxxxxxxx'],
            'options' => [],
             'lock' => true
        ],
```

```
'Session' => [
        'defaults' => 'cache',
        'handler'  => [
                        'config' => 'sessions'
                    ],
        'timeout' => 1440
    ],
```

### What you expected to happen
Appear no Error at all. This used to work properly back again, but updated to php7 and cakephp to latest version and now this starting to happen.

**Comment by markstory** [comment]
Does the issue happen if you don't use Cache backed Sessions?

**Comment by Cafnio** [comment]
Hi there.

Sorry for the late reply

Without using cache backed sessions, it doesn't show any errors

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce that issue with a cache backend.

**Comment by JoepRoebroek** [comment]
We are also experiencing this issue on our live environment, but having a hard time reproducing it on dev.

**Comment by Cafnio** [comment]
Yes, that's what happens. Sadly in local we can't reproduce it. We only discovered it because our AWS Logs are being flooded by it
