### ISSUE TITLE
Unauthorized Request with ajax returning 404 error and correct is 403

### ISSUE THREAD

**Issue by paulop** [cakephp/cakephp#9873]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.4.
* Platform and Target: Windows 7 + php 5.5.12.

### What you did
Request with ajax Authenticated But not authorized method
```
        $.get(url, null,
            function (data) {              
                $('#detalhe').html(data);
            }, 'html')
            .fail(function (xhr, status) {
                console.log(xhr, status);
        }).always(function () {

        });
```

### What happened
Is returning 404 error because 'unauthorizedRedirect' => true in Auth Component
set unauthorizedRedirect to false returned error is correct 403. 
but this way, non ajax call not redirect to previous page.

### What you expected to happen
In ajax cals only, return 403 error
_unauthorized function in
\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php
shoud be this
   ```
 protected function _unauthorized(Controller $controller)
    {
        //if ($this->_config['unauthorizedRedirect'] === false) {
        if ($this->_config['unauthorizedRedirect'] === false || $controller->request->is('ajax')) {
            throw new ForbiddenException($this->_config['authError']);
        }

        $this->flash($this->_config['authError']);
        if ($this->_config['unauthorizedRedirect'] === true) {
            $default = '/';
            if (!empty($this->_config['loginRedirect'])) {
                $default = $this->_config['loginRedirect'];
            }
            if (is_array($default)) {
                $default['_base'] = false;
            }
            $url = $controller->referer($default, true);
        } else {
            $url = $this->_config['unauthorizedRedirect'];
        }

        return $controller->redirect($url);
    }
```
Thank You

**Comment by markstory** [comment]
I think your change will break usage of the ajax login element. Instead you should consider updating AuthComponent's configuration when a request is ajax.

```php
public function initialize()
{
  // Other initialization logic
  if ($this->request->is('ajax')) {
    $this->Auth->config('unauthorizedRedirect', false);
  }
}
```

Given that what you want is already achievable, and the suggested change will break existing behavior, I'm going to close this.
