### ISSUE TITLE
How to deploy heroku server

### ISSUE THREAD

**Issue by poppo191** [cakephp/cakephp#9874]
Hi, I've tried to deploy Heroku. but It always shows missing plugin. If someone knows how to fix it, please told me Thank you 

<img width="1680" alt="screen shot 2559-12-14 at 9 52 16 pm" src="https://cloud.githubusercontent.com/assets/4536339/21186591/c67b9414-c247-11e6-81e0-004b194bdb6b.png">

**Comment by markstory** [comment]
Did you install the plugin? It looks like CakePHP can't find the path to DebugKit.

**Comment by dereuromark** [comment]
Don't put debug kit in require dev if you load it in the bootstrap without checks.
This is not a framework issue.

If you are looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by poppo191** [comment]
Thank you @derekperkins @markstory for your suggestion. 👍
