### ISSUE TITLE
belongsToMany with "through" definition and costum alias takes the alias as foreigntargetkey instead of the real tables name

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp#9877]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: nginx, php7.0, maria

### What you did
I defined an asssociation with following code:

```
        $this->belongsToMany('Visibletags', [
            'className' => 'Tags',
            'through' => 'ArticlesTags',
        ]);
```

Now this crashes beacause the field ```visibletag_id``` is not availible in arcticle_tags.

Defining a correct foreignKey for the ArticlesTagsTable didnt help anything.

```
       $this->belongsTo('Tags', [
            'foreignKey' => 'tag_id',
            'className' => 'Articles',
            'finder' => 'visible',
        ]);
```

So I tried to define it manually in the ArticlesTable:

```
       $this->belongsToMany('Visibletags', [
            'className' => 'Tags',
            'through' => 'ArticlesTags',
            'targetForeignKey' => 'tag_id',
        ]);
```

But now the finders in ArticleTags (actually the reason to use through) dont apply any more.

### What happened
see above

### What you expected to happen

First: I would expect that, given the className is defined and nothing in the pivotTable is defined, cake should recognize the class and its table and build a targetforeignkey from there

Second: I would expect, that if I have through and targetforeignkey, and one is overwiriting or replacing the other way of defining it, that there is a Notice or better a Warning for it. There is nothing more dangerous as improper defined table associations, who either go with through or a froerignKey and some automagic is choosing which one of them.

I think I spottet a bit of the problem here: http://api.cakephp.org/3.3/source-class-Cake.ORM.Association.BelongsToMany.html#165
I am not shure about $this->target()->alias() beeing the correct thing to use here.

But maybe I am wrong with my approach / expectation how this should work and some other way of solving this would be more approriate / commen - so please let me know.

**Comment by markstory** [comment]
We intentionally use the alias to generate foreign keys as it supports some use cases where model classes are reused for different aliases. We can't really change that behavior at this point as it will break existing applications.

 I am unclear as to how finders not working is connected to the definition of targetForeignKey? In the last code snippet your association doesn't define the finder option which would be a reason for it to not work.

**Comment by 3811015** [comment]
> I am unclear as to how finders not working is connected to the definition of targetForeignKey? In the last code snippet your association doesn't define the finder option which would be a reason for it to not work.

Well... The cookbook told me to use through and put the finder definition in the pivotTable. http://book.cakephp.org/3.0/en/orm/associations.html#using-the-through-option

How else would I apply a finder on the pivotTable?

**Comment by markstory** [comment]
Combining `through` and `finder` should work fine. My question was more about why/how are `targetForeignKey` being defined and the `finder` option not working connected?

**Comment by 3811015** [comment]
I just added targetForeignKey to the association definition to see if I can overwride manually the alias-derived assumption of targetForeignKey from the through-belognstomany. This didnt work out, as it stopped applying the finder. I saw this with the query beeing generated.

**Comment by markstory** [comment]
Interesting. Setting the targetForeignKey should not modify the finder usage. I'll see if I can reproduce that issue in the test suite.

**Comment by markstory** [comment]
The following test passes currently

```php
public function testTargetForeignKeyAndFinder()
{
    $joint = TableRegistry::get('SpecialTags');
    $articles = TableRegistry::get('Articles');
    $tags = TableRegistry::get('Tags');

    $assoc = $articles->belongsToMany('Tags', [
        'through' => 'SpecialTags',
        'targetForeignKey' => 'custom_tag_id',
        'finder' => 'highlighted',
    ]);
    $this->assertEquals('custom_tag_id', $assoc->targetForeignKey());
    $this->assertEquals('highlighted', $assoc->finder());
}
```

What does your association definition look like?

**Comment by 3811015** [comment]
@markstory the finder, which isn't applied would be defined in SpecialTagsTable in your example/test. Not in the belongstomany-Association, but in the belontsTo Association.

**Comment by markstory** [comment]
Are you sure your `finder` works at all? The `finder` option in a `BelongsToMany` association is never applied to any of the generated associations.

**Comment by 3811015** [comment]
@markstory maybe we should start more basic.
You were right, that the finders dont always apply.

I created a little gist with fixtures and tests so we can talk on the same:

PeopleTableTest::testInitializeExpiredRole() passes, PeopleTableTest::testInitializeExpiredTeam() doesnt pass. Actually I am testing 2 times the same thing.

After solving this miracle why things somethimes apply, I would like to move on to aliasing the whole thing.

**Comment by 3811015** [comment]
solved in chat. Thanks to hmic.
