### ISSUE TITLE
[RFC] Add an ability to get a full field name for translated fields

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#9879]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.10

I think there should be a convenient way to get a full field name for translated fields. It could be useful while creating find conditions. 

For example:
```php
//FooTable
$table->locale('pl_PL');
$table->find()
    ->where(['foo_bar_translation.content' => 'baz']);
```
This requires a knowledge of internal association naming convention used in `TranslateBehavior`.

Instead there could exist some helper method like this:
```php
//TranslateBehavior:
public function translationField($field, $useAlias = true)
{
    $table = $this->_table;
    $associationName = $table->alias() . "_{$field}_translation";

    if ($table->associations()->has($associationName)) {
        return "$associationName.content";
    } else {
        return $useAlias ? $table->aliasField($field) : $name;
    }
}

//FooTable
$table->locale('pl_PL');
$table->find()
    ->where([$table->translationField('bar') => 'baz']);
```

The method could return table aliased field by default if a association couldn't be found (like above) or throw an exception. 
This method is an actual helper method I use in my projects and I think it could be added to the core.

**Comment by markstory** [comment]
The `translationField` method sounds like a reasonable thing to me. Would you expose it as a 'mixin' method?

**Comment by robertpustulka** [comment]
@markstory It could go to 'TranslateBehavior'

**Comment by markstory** [comment]
Right. But would it be exposed on the implementing table [via the mixin methods](http://book.cakephp.org/3.0/en/orm/behaviors.html#defining-mixin-methods)?

**Comment by robertpustulka** [comment]
@markstory yes, why not.

**Comment by robertpustulka** [comment]
I'll start working on a PR if that's OK.

**Comment by robertpustulka** [comment]
PR #9999 (:smile:) is open
