### ISSUE TITLE
Bake, numeric can't be load, orm, database

### ISSUE THREAD

**Issue by HumanG33k** [cakephp/cakephp#9889]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10
* Platform and Target: 
Server version: Apache/2.4.23 (Debian)
Server built:   2016-11-19T23:33:13
Postgresql 9.6

### What you did
I try to display values from a table.
The code is generate by the command line.
I insert data from a method in other controller. (no error) 
I can't use the generated form to add data. Error Message : need a integer 

the code for save data
```php
            foreach ($json['urls'] as $url) { 
                $semanticCocoonUniformRessourceLocators = $this->SemanticCocoonUniformRessourceLocators->newEntity();

                $semanticCocoonUniformRessourceLocators->url = url['url'];
                $semanticCocoonUniformRessourceLocators->as_title =$url['as_titre'];
                $semanticCocoonUniformRessourceLocators->as_page = $url['as_page'];
                $semanticCocoonUniformRessourceLocators->title_semantic_rank = $url['sr_titre'];
                $semanticCocoonUniformRessourceLocators->page_semantic_rank = $url['sr_page'];
                $semanticCocoonUniformRessourceLocators->page_rank = $url['pr_page'];
                $semanticCocoonUniformRessourceLocators->semantic_cocoon_response_id = $result->id;
               $semanticCocoonUniformRessourceLocators->http_status_code_id = 'bfec5b49-7951-4195-af89-57bd53e0bbe4'; //static for testing 
               

               
               if ($semanticCocoonUniformRessourceLocators->errors()) {
    // Entity failed validation.
                   debug($semanticCocoonUniformRessourceLocators);
                   exit();
                }
```

This is the sql code.
semantic_cocoon_response has many semantic_cocoon_uniform_ressource_locators
http_status_code has many semantic_cocoon_uniform_ressource_locators

```sql
CREATE TABLE semantic_cocoon_uniform_ressource_locators (
  id                          uuid NOT NULL, 
  url                         text, 
  as_title                    numeric, 
  as_page                     numeric, 
  title_semantic_rank         numeric, 
  page_semantic_rank          numeric, 
  page_rank                   numeric, 
  http_status_code_id         uuid NOT NULL, 
  semantic_cocoon_response_id uuid NOT NULL, 
  created                     timestamp, 
  updated                     timestamp, 
  PRIMARY KEY (id));
ALTER TABLE semantic_cocoon_uniform_ressource_locators ADD CONSTRAINT FKsemantic_c624354 FOREIGN KEY (http_status_code_id) REFERENCES http_status_codes (id);
ALTER TABLE semantic_cocoon_uniform_ressource_locators ADD CONSTRAINT FKsemantic_c639501 FOREIGN KEY (semantic_cocoon_response_id) REFERENCES semantic_cocoon_responses (id);
```
The validator 

```php
public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('url');

        $validator
            ->decimal('as_title')
            ->allowEmpty('as_title');

        $validator
            ->decimal('as_page')
            ->allowEmpty('as_page');

        $validator
            ->decimal('title_semantic_rank')
            ->allowEmpty('title_semantic_rank');

        $validator
            ->decimal('page_semantic_rank')
            ->allowEmpty('page_semantic_rank');

        $validator
            ->decimal('page_rank')
            ->allowEmpty('page_rank');

        return $validator;
    }
  ```
In the entity :
 * @property float $as_title
 * @property float $as_page
 * @property float $title_semantic_rank
 * @property float $page_semantic_rank
 * @property float $page_rank

the index controller method
```php
    public function index()
    {
        $this->paginate = [
            'contain' => ['HttpStatusCodes', 'SemanticCocoonResponses']
        ];
        $semanticCocoonUniformRessourceLocators = $this->paginate($this->SemanticCocoonUniformRessourceLocators);

        $this->set(compact('semanticCocoonUniformRessourceLocators'));
        $this->set('_serialize', ['semanticCocoonUniformRessourceLocators']);
    }
```

### What happened
My data field are not load. Only the related object are. 
A warning is display 
Warning (2): array_combine(): Both parameters should have an equal number of elements [CORE/src/ORM/ResultSet.php, line 508]

The context
array_combine - [internal], line ??
Cake\ORM\ResultSet::_groupResult() - CORE/src/ORM/ResultSet.php, line 508
Cake\ORM\ResultSet::_fetchResult() - CORE/src/ORM/ResultSet.php, line 473
Cake\ORM\ResultSet::valid() - CORE/src/ORM/ResultSet.php, line 276
include - APP/Template/SemanticCocoonUniformRessourceLocators/index.ctp, line 31
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1016
Cake\View\View::_render() - CORE/src/View/View.php, line 975
Cake\View\View::render() - CORE/src/View/View.php, line 599
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65

### What you expected to happen
I hope i can see my data

**Comment by thinkingmedia** [comment]
Thanks for opening the issue. Hopefully someone will be able to see what the problem is.

**Comment by markstory** [comment]
If you remove the `contain` options on the pagination does the issue go away? From the stack trace, the issue looks like it is related to reading data not saving data.

After you save your data does the data look correct via queries made in `pgsql`?

**Comment by HumanG33k** [comment]
Data are present in the database.
For the paginator, how can i remove it (what do you want i use ? )

**Comment by thinkingmedia** [comment]
We want to know if the issue is from the contains.

Try commenting out the example below.

```
    public function index()
    {
        $this->paginate = [
//            'contain' => ['HttpStatusCodes', 'SemanticCocoonResponses']
        ];
        $semanticCocoonUniformRessourceLocators = $this->paginate($this->SemanticCocoonUniformRessourceLocators);

        $this->set(compact('semanticCocoonUniformRessourceLocators'));
        $this->set('_serialize', ['semanticCocoonUniformRessourceLocators']);
    }
```

**Comment by HumanG33k** [comment]
Ok , that was i try but at first look i think it was to easy :)
I already have an error :

Error: Uncaught TypeError: Argument 1 passed to Cake\ORM\Entity::__construct() must be of the type array, boolean given, called in [...]//vendor/cakephp/cakephp/src/ORM/ResultSet.php on line 575 and defined in[...]//vendor/cakephp/cakephp/src/ORM/Entity.php:48 Stack trace: #0[...]//vendor/cakephp/cakephp/src/ORM/ResultSet.php(575): Cake\ORM\Entity->__construct(false, Array) #1 [...]/vendor/cakephp/cakephp/src/ORM/ResultSet.php(473): Cake\ORM\ResultSet->_groupResult(Array) #2 [...]//vendor/cakephp/cakephp/src/ORM/ResultSet.php(276): Cake\ORM\ResultSet->_fetchResult() #3 [internal function]: Cake\ORM\ResultSet->valid() #4 [...]/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php(496): iterator_to_array(Object(Cake\ORM\ResultSet), true) #5 [...]/vendor/cakephp/cakephp
File [...]/vendor/cakephp/cakephp/src/ORM/Entity.php
Line: 48

**Comment by markstory** [comment]
Are you able to fetch any entities with the ORM, or does this happen any time you read data?

**Comment by HumanG33k** [comment]
It's not working only when table contain numeric/float.
In others tables there is no trouble.

**Comment by markstory** [comment]
Odd, I don't have the same issues locally with postgres and php7.

**Comment by HumanG33k** [comment]
Which operating system ?
My php version :
PHP 7.0.13-2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-2, Copyright (c) 1999-2016, by Zend Technologies
can you share your sql script, m,c,v in order to try on my side ? 

Where do you put your cake/app directory ? Do you use any virtual host ?

**Comment by HumanG33k** [comment]
I try with a fresh install and i always have the error. 
Maybe have done something wrong :
composer create-project --no-interaction --prefer-dist cakephp/app test
i configure/create my database.
Insert data.(with a sql insert into )
use bin/cake bake all for each table i need but doesn't work.

**Comment by markstory** [comment]
I've not had a chance to look into this yet unfortunately. Somethings you might be able to try are:

* Using basic `PDO` to read from your tables, and confirm that you get numeric values back. If you don't then there is likely an issue with postgres, or pdo-postgres
* Use `Cake\Database` to read from your table instead of the ORM. If you get data back then the issue is somewhere in the ORM.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. Here's what I tried:

```sql
cake_test_db=# CREATE TABLE semantic_cocoon_uniform_ressource_locators (
cake_test_db(#   id                          uuid NOT NULL,
cake_test_db(#   url                         text,
cake_test_db(#   as_title                    numeric,
cake_test_db(#   as_page                     numeric,
cake_test_db(#   title_semantic_rank         numeric,
cake_test_db(#   page_semantic_rank          numeric,
cake_test_db(#   page_rank                   numeric,
cake_test_db(#   http_status_code_id         uuid NOT NULL,
cake_test_db(#   semantic_cocoon_response_id uuid NOT NULL,
cake_test_db(#   created                     timestamp,
cake_test_db(#   updated                     timestamp,
cake_test_db(#   PRIMARY KEY (id));
CREATE TABLE

cake_test_db=# alter table semantic_cocoon_uniform_ressource_locators rename to resources
cake_test_db-# ;
ALTER TABLE

insert into resources (id, url, as_title, as_page, title_semantic_rank, page_semantic_rank, page_rank, http_status_code_id, semantic_cocoon_response_id) values (uuid_generate_v4(), 'http://example.com', 12.34, 23.45, 34,56, 45.67, uuid_generate_v4(), uuid_generate_v4());
```

I then created a Shell to test out loading the record I inserted into the database:

``php
<?php
namespace App\Shell;

use Cake\Console\Shell;
use Cake\ORM\TableRegistry;
use Cake\Network\Http\Client;
use Cake\Log\Log;

class BugShell extends Shell
{
    public function main()
    {
        $resources = TableRegistry::get('Resources');
        $record = $resources->find()->first();
        debug($record);
    }
}
```

Running this shell (`bin/cake bug`) did not any errors as described above. I tested with

* PHP 7.1.0
* Postgres 9.6.1
* PDO Postgres

**Comment by HumanG33k** [comment]
Hello sry for "being late" i have been busy.
I try your code @markstory .
The issue is strange, maybe i have done something wrong but when i try with the table i have a right error.
But i have this issue only with this table.

Welcome to CakePHP v3.3.10 Console
---------------------------------------------------------------
App : src
Path: PATH_TO_APP/src/
PHP : 7.0.14-2
---------------------------------------------------------------
Warning Error: SplFileInfo::openFile(PATH_TO_APP/tmp/cache/models/myapp_cake_model_default_semantic_cocoon_uniform_ressource_locators): failed to open stream: Permission denied in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 398]

2016-12-27 17:31:49 Warning: Warning (512): SplFileInfo::openFile(PATH_TO_APP/tmp/cache/models/myapp_cake_model_default_semantic_cocoon_uniform_ressource_locators): failed to open stream: Permission denied in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 398]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\Cache\Engine\FileEngine::_setKey() - CORE/src/Cache/Engine/FileEngine.php, line 398
Cake\Cache\Engine\FileEngine::read() - CORE/src/Cache/Engine/FileEngine.php, line 184
Cake\Cache\Cache::read() - CORE/src/Cache/Cache.php, line 320
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 57
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 440
Cake\ORM\Query::addDefaultTypes() - CORE/src/ORM/Query.php, line 211
Cake\ORM\Query::__construct() - CORE/src/ORM/Query.php, line 168
Cake\ORM\Table::query() - CORE/src/ORM/Table.php, line 1336
Cake\ORM\Table::find() - CORE/src/ORM/Table.php, line 964
App\Shell\BugShell::main() - APP/Shell/BugShell.php, line 14
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 466
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 227
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 182
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 128
[main] - ROOT/bin/cake.php, line 34



Warning Error: SplFileInfo::openFile(PATH_TO_APP/tmp/cache/models/myapp_cake_model_default_semantic_cocoon_uniform_ressource_locators): failed to open stream: Permission denied in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 398]

2016-12-27 17:31:49 Warning: Warning (512): SplFileInfo::openFile(PATH_TO_APP/tmp/cache/models/myapp_cake_model_default_semantic_cocoon_uniform_ressource_locators): failed to open stream: Permission denied in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 398]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\Cache\Engine\FileEngine::_setKey() - CORE/src/Cache/Engine/FileEngine.php, line 398
Cake\Cache\Engine\FileEngine::write() - CORE/src/Cache/Engine/FileEngine.php, line 134
Cake\Cache\Cache::write() - CORE/src/Cache/Cache.php, line 239
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 66
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 440
Cake\ORM\Query::addDefaultTypes() - CORE/src/ORM/Query.php, line 211
Cake\ORM\Query::__construct() - CORE/src/ORM/Query.php, line 168
Cake\ORM\Table::query() - CORE/src/ORM/Table.php, line 1336
Cake\ORM\Table::find() - CORE/src/ORM/Table.php, line 964
App\Shell\BugShell::main() - APP/Shell/BugShell.php, line 14
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 466
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 227
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 182
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 128
[main] - ROOT/bin/cake.php, line 34



Warning Error: _cake_model_ cache was unable to write 'default_semantic_cocoon_uniform_ressource_locators' to Cake\Cache\Engine\FileEngine cache in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Cache.php, line 248]

2016-12-27 17:31:49 Warning: Warning (512): _cake_model_ cache was unable to write 'default_semantic_cocoon_uniform_ressource_locators' to Cake\Cache\Engine\FileEngine cache in [PATH_TO_APP/vendor/cakephp/cakephp/src/Cache/Cache.php, line 248]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\Cache\Cache::write() - CORE/src/Cache/Cache.php, line 248
Cake\Database\Schema\CachedCollection::describe() - CORE/src/Database/Schema/CachedCollection.php, line 66
Cake\ORM\Table::schema() - CORE/src/ORM/Table.php, line 440
Cake\ORM\Query::addDefaultTypes() - CORE/src/ORM/Query.php, line 211
Cake\ORM\Query::__construct() - CORE/src/ORM/Query.php, line 168
Cake\ORM\Table::query() - CORE/src/ORM/Table.php, line 1336
Cake\ORM\Table::find() - CORE/src/ORM/Table.php, line 964
App\Shell\BugShell::main() - APP/Shell/BugShell.php, line 14
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 466
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 227
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 182
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 128
[main] - ROOT/bin/cake.php, line 34



Warning Error: array_combine(): Both parameters should have an equal number of elements in [PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php, line 508]

2016-12-27 17:31:49 Warning: Warning (2): array_combine(): Both parameters should have an equal number of elements in [PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php, line 508]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
array_combine - [internal], line ??
Cake\ORM\ResultSet::_groupResult() - CORE/src/ORM/ResultSet.php, line 508
Cake\ORM\ResultSet::_fetchResult() - CORE/src/ORM/ResultSet.php, line 473
Cake\ORM\ResultSet::valid() - CORE/src/ORM/ResultSet.php, line 276
Cake\ORM\ResultSet::first() - CORE/src/ORM/ResultSet.php, line 298
Cake\ORM\Query::first() - CORE/src/Datasource/QueryTrait.php, line 404
App\Shell\BugShell::main() - APP/Shell/BugShell.php, line 14
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 466
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 227
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 182
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 128
[main] - ROOT/bin/cake.php, line 34



Exception: Argument 1 passed to Cake\ORM\Entity::__construct() must be of the type array, boolean given, called in PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php on line 575 in [PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/Entity.php, line 48]
2016-12-27 17:31:49 Error: [TypeError] Argument 1 passed to Cake\ORM\Entity::__construct() must be of the type array, boolean given, called in PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php on line 575
Stack Trace:
#0 PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php(575): Cake\ORM\Entity->__construct(false, Array)
#1 PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php(473): Cake\ORM\ResultSet->_groupResult(Array)
#2 PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php(276): Cake\ORM\ResultSet->_fetchResult()
#3 PATH_TO_APP/vendor/cakephp/cakephp/src/ORM/ResultSet.php(298): Cake\ORM\ResultSet->valid()
#4 PATH_TO_APP/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(404): Cake\ORM\ResultSet->first()
#5 PATH_TO_APP/src/Shell/BugShell.php(14): Cake\ORM\Query->first()
#6 [internal function]: App\Shell\BugShell->main()
#7 PATH_TO_APP/vendor/cakephp/cakephp/src/Console/Shell.php(466): call_user_func_array(Array, Array)
#8 PATH_TO_APP/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(227): Cake\Console\Shell->runCommand(Array, true, Array)
#9 PATH_TO_APP/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#10 PATH_TO_APP/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#11 PATH_TO_APP/bin/cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#12 {main}

**Comment by markstory** [comment]
I'm at a loss on what's going wrong as I am not able to reproduce the issue for me.

**Comment by HumanG33k** [comment]
Do you test on linux or on windows  or both ?
Maybe there is an error in the way i use composer to install 
composer create-project --no-interaction --prefer-dist cakephp/app  project_name 
and 
composer update
for update

Maybe it's the name of the table : semantic_cocoon_uniform_ressource_locators.

When i use php for retrieve data there is no trouble.
The code :
```
<?php
// Connexion, sélection de la base de données
$dbconn = pg_connect("host=localhost dbname=visillu user=visillu password=visillu")
    or die('Connexion impossible : ' . pg_last_error());

$query = 'SELECT * FROM semantic_cocoon_uniform_ressource_locators';
$result = pg_query($query) or die('Échec de la requête : ' . pg_last_error());
echo "<table>\n";
while ($line = pg_fetch_array($result, null, PGSQL_ASSOC)) {
    echo "\t<tr>\n";
    foreach ($line as $col_value) {
        echo "\t\t<td>$col_value</td>\n";
    }
    echo "\t</tr>\n";
}
echo "</table>\n";

pg_free_result($result);

pg_close($dbconn);
?>
```

**Comment by markstory** [comment]
Is it possible that you're running into postgres's alias length limit? #6631 was opened a while back, but there isn't really a solution for it.

**Comment by HumanG33k** [comment]
I read the other issue, change the table name for a shortest one and it work. Maybe it's can be a good thing to add some info int the book, convention part maybe. 
Thx for everything.
