### ISSUE TITLE
Subtree split of Form

### ISSUE THREAD

**Issue by ceeram** [cakephp/cakephp#9890]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3

I would like to discuss the ability to subtree split Form namespace. It's very small, but it would be valuable for us to be able to use the Form and Schema classes in some not cakephp specific code that already requires cakephp/validation. Form would only have cakephp/validation as its dependency. No other subtree split packages use Form or Schema class.

**Comment by markstory** [comment]
Closing as there is a pull request open. Further discussion can take place there.
