### ISSUE TITLE
3.x AuthComponent ajaxLayout ?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9894]
The 3.x code seems to have some dead code:

```php
        if (!empty($this->_config['ajaxLogin'])) {
            $controller->viewBuilder()->templatePath('Element');
            $response = $controller->render(
                $this->_config['ajaxLogin'],
                $this->RequestHandler->ajaxLayout
            );

            return $response->withStatus(403);
        }
```

$this->RequestHandler->ajaxLayout does not seem to exist.

maybe we can safely remove it?

**Comment by markstory** [comment]
I guess the automatic usage of AjaxView is masking this issue.

**Comment by dereuromark** [comment]
Also FormHelper::_isRequiredField() seems to be a dead method.

**Comment by dereuromark** [comment]
As for 3.4: ServerRequestFactory::updatePath()

     * @param \Psr\Http\Message\UriInterface $uri The uri to update.
     * @return \Psr\Http\Message\ServerRequestInterface The modified Uri instance.

Seems to be a lie, not sure what is correct. Should be the same interface again?

**Comment by littleylv** [comment]
I have open #8854 about $this->RequestHandler->ajaxLayout  once before

**Comment by dereuromark** [comment]
Time to get rid of this dead code then :)

**Comment by markstory** [comment]
One concern I have with removing this 'dead' code is that it is possible that an application developer could be doing something like:

```php
public function beforeFilter($event)
{
   $this->RequestHandler->ajaxLayout = 'custom_ajax';
}
```

Us removing the cited line would 'break' this application code. I recognize that we don't have test coverage for this behavior, but it could break userland code.

**Comment by dereuromark** [comment]
With a minor 3.4 it could still be safe to communicate this as not supported.
But OK, maybe deprecating it and then cleaning it up for 4.0 is the safer option.

**Comment by markstory** [comment]
Pull request up to mark property as deprecated.

**Comment by dereuromark** [comment]
> Also FormHelper::_isRequiredField() seems to be a dead method.
At least in 3.4 then.

wasnt yet discussed, though
