### ISSUE TITLE
BelongsToMany through-table not allowed to share name with association

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/cakephp#9900]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.10

Given the association defined in `MaterialsTable` class initialize():
```php
        $this->belongsToMany('Sources', [
            'className' => 'Materials',
            'through' => 'Sources',
            'foreignKey' => 'product_id',
            'targetForeignKey' => 'source_id',
        ]);
```
In the controller:
```php
$material = $this->Materials->get($id, ['contain' => 'Sources']);
```

The following error is obtained:

> Unsupported operand types in /srv/http/LIMS/app/vendor/cakephp/cakephp/src/ORM/Association/BelongsToMany.php on line 349

The code works correctly when the association is named differently, e.g. 'Sourcess'.

**Comment by markstory** [comment]
As always, table aliases _must_ be unique and you've created duplicate aliases that make generating association conditions impossible.
