### ISSUE TITLE
Scoped routes with custom route class don't use custom route class and don't pass options

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#9904]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3

### What you did

Just check the code http://api.cakephp.org/3.3/source-class-Cake.Routing.Router.html#922 there is no way to pass options nor to change the route class except by changing the overall default route class. Even if I do so I can't pass options.

```
 922:     public static function scope($path, $params = [], $callback = null)
 923:     {
 924:         $builder = new RouteBuilder(static::$_collection, '/', [], [
 925:             'routeClass' => static::defaultRouteClass(),
 926:             'extensions' => static::$_defaultExtensions,
 927:         ]);
 928:         $builder->scope($path, $params, $callback);
 929:     }
```

I managed to get it done this way but I would not call this a proper solution. It looks to me like it was forgotten to pass the $options in the scope() methods signature.

```php
Router::defaultRouteClass('App\Routing\Route\SlugRoute');
Router::scope('/:userSlug', [], function($routes) {
	$options = [
		'pass' => ['userSlug'],
		'_table' => 'Users',
		'_slugField' => 'slug',
		'_routeParam' => 'userSlug',
		'_cache' => false,
		'_urlCallback' => function($url, $entity) {
			$url['pass'][0] = $entity->get('id');
			return $url;
		}
	];

	$routes->connect('/',
		['plugin' => null, 'controller' => 'Users', 'action' => 'view'],
		$options
	);
        /* more routes...*/
});
```

### What happened

My route class was not used at all and no options passed.

### What you expected to happen

The options being passed to my custom route class.

## Proposed Fix

Use func_get_args(), count the args, if three, old behavior, if four, pass the options. This way it's backward compatible but would allow the function to work as I expected it and it would match the other methods as well.

**Comment by ADmad** [comment]
I don't see a problem with having a local variable in the callback for `Router::scope()` which would contain  `routeClass` and any other options and then passing that variable to each `RouteBuilder::connect()`.

**Comment by burzum** [comment]
> So I don't see what an extra argument to Router::scope() is necessary.

It is simply not convenient and how I expected the API to work, nor do the docs mention that limitation. All the other methods take the options as well, why not scope? It just feels wrong and it's a trap. The fix is easy. I don't see a reason to *not* fix it. I don't mind fixing it myself as soon as I find the time to do so.

**Comment by markstory** [comment]
Isn't having both `$options` and `$params` a bit unwieldy? Could we add the builder specific options into `$params` and extract them out when creating the `RouteBuilder`? Including the builder options in `$params` allows `Router::prefix()` and `Router::plugin()` to inherit the same API improvements with no additional work.

**Comment by markstory** [comment]
Pull request open now.
