### ISSUE TITLE
Custom methods of ErrorRenderer are called only on debug mode

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9905]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.10

### What you did

1. Declare `AppExceptionRenderer`.
```php
namespace App\Error;

use Cake\Error\ExceptionRenderer;

class AppExceptionRenderer extends ExceptionRenderer
{
    public function missingController($error) {
        die;
    }
}
```

2. Configure `app.php` to use `AppExceptionRenderer` and set debug mode to false.

```php
// In app.php
'debug' => false,

// ...

'Error' => [
    'exceptionRenderer' => 'App\Error\AppExceptionRenderer'
    // ...
],
```

3. Access some non-existent page.

```
/some/non-existent/page
```

### What happened

The `AppExceptionRenderer::missingController()` method was not called.

### What you expected to happen

The `AppExceptionRenderer::missingController()` method should be called. In CakePHP 2, custom error rendering methods are called regardless of debug mode.

Is there any reason why debug mode is checked [here](https://github.com/cakephp/cakephp/blob/18e5d31a8a5bd6f875790a930e3ff6d2be106f93/src/Error/ExceptionRenderer.php#L161-L166)?

(Reported by **kino** in #japanese channel on Slack)

**Comment by markstory** [comment]
> Is there any reason why debug mode is checked here?

Yes, the reason is that in debug we show specific developer friendly errors - like 'Missing Controller' - while in a production mode we only show generic 40x or 50x error pages. If we called custom methods on the exception renderer all the time, we'd need to require developers to do debug checks in their custom methods as well.

Its worth noting that this is only an issue for exceptions that do not extend `Cake\Network\HttpException` as those should always have custom error handling methods invoked.

**Comment by chinpei215** [comment]
I think we don't use custom method to show developer friendly errors. Instead, we are using specific templates such as `missing_controller.ctp`. So I also think it is reasonable to disable such templates [here](https://github.com/cakephp/cakephp/blob/18e5d31a8a5bd6f875790a930e3ff6d2be106f93/src/Error/ExceptionRenderer.php#L273-L280) when debug on. But I don't think it is necessary to disable custom methods [here](https://github.com/cakephp/cakephp/blob/18e5d31a8a5bd6f875790a930e3ff6d2be106f93/src/Error/ExceptionRenderer.php#L161-L166). Currently, developers must override the `render()` method by copy&paste if they want some additional logic when a missing controller exception or something happens in the production mode.

**Comment by markstory** [comment]
Those are good points. I'm on-board with changing the behavior in a minor release (3.4.0, 3.5.0) if you want to change it.

**Comment by chinpei215** [comment]
OK. I'll do it in 3.5.

**Comment by josegonzalez** [comment]
@markstory I think splitting the two paths up is a pretty poor developer experience. If you are a new dev and only *sometimes* your code gets called, you'll come to hate the framework.

Maybe for 4.x we simply call `ExceptionRenderer::render()` and let the dev handle the rest in all cases?

**Comment by markstory** [comment]
@josegonzalez I agree its not great right now. I don't want to surprise people in a patch release when error handling starts working differently.
