### ISSUE TITLE
How to display relation data to json

### ISSUE THREAD

**Issue by Suparuch** [cakephp/cakephp#9908]
CakePHP Version: 3.3
<img width="467" alt="screen shot 2559-12-24 at 2 45 02 pm" src="https://cloud.githubusercontent.com/assets/4521904/21465919/a38ceedc-c9e8-11e6-9adc-6c446c80cab7.png">

I want to show roles.title but myosin respone roles_id 

My Code

  public function index()
    {
        $this->paginate = [
            'contain' => ['Users', 'Profiles', 'Nationalities']

        ];
        $this->loadModel('Roles');
        $query = $this->Roles->find();
        $query->where(['id' == 1]);

        $employees = $this->paginate($this->Employees);

        $this->set(compact('employees'));
        $this->set('_serialize', ['employees']);
    }

how to display it

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
