### ISSUE TITLE
[2.x] FlashHelper::render() cannot render flash messages from SessionComponent::setFlash()

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#9910]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4

### What you did

Install CakePHP without using bake project. Call `$this->Session->setFlash('Test');` in some controller.

### What happened

I got a notice instead of a flash message.
```
Notice (1024): Element Not Found: Elements\default.ctp [CORE\Cake\View\View.php, line 425]
```

### What you expected to happen

I get the flash message.

### Why this issue happens

Related to #9061. Maybe the same issue. But I think `Flash/default.ctp` was not related to this issue. The reason why this issue occurs is that `FlashHelper::redner()` cannot render flash messages from `SessionComponent::setFlash()`. Because the `default` key must be handled specially like [this](https://github.com/cakephp/cakephp/blob/9eafde13d220209f4e783ddde2dd82f6bb8499db/lib/Cake/View/Helper/SessionHelper.php#L145-L149) to render them.  `SessionHelper` does  that, but `FlashHelper` doesn't.

Therefore, currently, any existing applications/plugins must replace all `SessionComponent::setFlash()` calls with `FlashComponent::set()`. I would like to fix this issue.

**Comment by markstory** [comment]
Sounds like a reasonable thing to fix. Do you need a hand fixing this or do you have a patch in mind?

**Comment by chinpei215** [comment]
I have two ideas.

(A) Fallback to `Flash/default` if `$flash['element']` equals to `default`.

Or

(B) Hard-code the default HTML like SessionHelper.

Which idea do you like? Or any other ideas?

By the way, although I self-assigned myself (because it is an issue in 2.x), if someone is interested in fixing this issue, I don't block him/her. If no one does it, I'll send a patch next year.

**Comment by markstory** [comment]
I think option A sounds better to me.

**Comment by chinpei215** [comment]
Thanks. I prefer option A too.

**Comment by chinpei215** [comment]
Pull request up now.
