### ISSUE TITLE
find('list') with groupField as field from related model

### ISSUE THREAD

**Issue by pedro-stanaka** [cakephp/cakephp#9911]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10
* Platform and Target: NGINX, MySQL (Maria DB 10), PHP 7

### What I did
Created models like: 

```php

class CategoriesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('categories');
        $this->displayField('title');
        $this->primaryKey('id');

        $this->hasMany('SubCategories', [
            'foreignKey' => 'category_id'
        ]);
    }
}
```

```php
class SubCategoriesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('sub_categories');
        $this->displayField('title');
        $this->primaryKey('id');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
    }
```

Did a query like (in ProductsController):

```php
<?php

$subCategories = $this->Products->SubCategories
                ->find('list', ['groupField' => "Categories.title"])
                ->contain('Categories');

?>

```

### What happened

It is returning results like:

```
[
	'' => [
		(int) 1 => 'Dress',
		(int) 2 => 'Boots',
		(int) 3 => 'Pumps'
	]
]
```

### What you expected to happen

When it should be like: 
```
[
	'Clothes' => [
		(int) 1 => 'Dress'
	],
        'Shoes' => [
               	(int) 0 => 'Boots',
		(int) 1 => 'Pumps'
        ]
]
```

### Extra info
Here is a "dump" of the query that joins Categories and SubCategories:

<table border="1" style="border-collapse:collapse">
<tr><th>Categories__title</th><th>SubCategories__id</th><th>SubCategories__title</th></tr>
<tr><td>Clothing</td><td>1</td><td>Dress</td></tr>
<tr><td>Shoes</td><td>2</td><td>Boots</td></tr>
<tr><td>Shoes</td><td>3</td><td>Pumps</td></tr></table>

*Query* 

```sql
SELECT
  Categories.title AS `Categories__title`,
  SubCategories.id AS `SubCategories__id`,
  SubCategories.title AS `SubCategories__title`
FROM
  sub_categories SubCategories
  INNER JOIN categories Categories ON Categories.id = (SubCategories.category_id)
```

**Comment by ADmad** [comment]
You need to need you use the property name for `groupField`, so `categories.title` not `Categories.title`.

**Comment by pedro-stanaka** [comment]
Thanks @ADmad. I'll make a PR to improve the docs and make it explicit that the developer should use Entity properties. :smile:
