### ISSUE TITLE
Hi, Some question about routing subdomain

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#9912]
Hi
 I want "http://img.domain.com/image-file-path.jpg"  match action `ImageController::view`, Only for "img.domain.com";
```
    $routes->connect('/:imageFile', ['controller' => 'Image', 'action' => 'view'], [
        'pass' => ['imageFile'],
        'imageFile' => '.*',
        '_host' => 'img.domain.com'
    ]);
```
However  when i visited 'http://www.domain.com/image-file-path.jpg', It also be matched. And even all not found uri will macth this route.
![image](https://cloud.githubusercontent.com/assets/3785826/21471291/e34ef8f8-cae7-11e6-924a-6331ef10a671.png)
![image](https://cloud.githubusercontent.com/assets/3785826/21471287/bba4997a-cae7-11e6-926d-955a52aafcd1.png)
![image](https://cloud.githubusercontent.com/assets/3785826/21471288/c28b0f8a-cae7-11e6-8174-4657491b0a5c.png)

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by slince** [comment]
@ADmad  Hi, I have spent a long time for this。If i can get help I will be happy post my question to official forum.You must be aware that the forum is very deserted. Although I can understand you want to promote your forum. finally I'think this is a bug.  and cakephp document can be more rich and add some  tutorial。Now i feel i'm in a black hole. I feel a little regret for using cake

**Comment by markstory** [comment]
You cannot currently restrict routes to only match on a specific domain in the route definition. Instead you'd have to do this at the controller level.

**Comment by slince** [comment]
@markstory I know, this is ony a fallback route, apache rewrite rule will redirect to a real image file preferentially; it will only match when file does not exist. I just want record some thing if client request a non-existent image.  set host requirements for route is supported in symfony/routing , [example](http://symfony.com/doc/current/components/routing.html) ,I think this is very useful, I hope in later versions will support this feature.

**Comment by markstory** [comment]
@slince I agree. I have opened a new issue for the host matching feature.
