### ISSUE TITLE
TableHelper::output() on testing: the output changes

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9913]
I'm writing tests for the `TableHelper::output()` method.

Debug of my table:
```
########## DEBUG ##########
[
        (int) 0 => '+----+----------+---------+--------------+----------------+-------+---------+-------------------+',
        (int) 1 => '| <info>ID</info> | <info>Username</info> | <info>Group</info>   | <info>Name</info>         | <info>Email</info>          | <info>Posts</info> | <info>Status</info>  | <info>Date</info>              |',
        (int) 2 => '+----+----------+---------+--------------+----------------+-------+---------+-------------------+',
        (int) 3 => '| 1  | alfa     | Admin   | Alfa Beta    | alfa@test.com  | 3     | Active  | 12/24/16, 5:00 PM |',
        (int) 4 => '| 2  | gamma    | Manager | Gamma Delta  | gamma@test.com | 0     | Pending | 12/24/16, 5:01 PM |',
        (int) 5 => '| 3  | ypsilon  | User    | Ypsilon Zeta | ypsilon.com    | 1     | Banned  | 12/24/16, 5:02 PM |',
        (int) 6 => '+----+----------+---------+--------------+----------------+-------+---------+-------------------+'
]
###########################
```

On localhost, tests work. This is the assert:

        $this->assertEquals([
            '+----+----------+---------+--------------+----------------+-------+---------+-------------------+',
            '| <info>ID</info> | <info>Username</info> | <info>Group</info>   | <info>Name</info>         | <info>Email</info>          | <info>Posts</info> | <info>Status</info>  | <info>Date</info>              |',
            '+----+----------+---------+--------------+----------------+-------+---------+-------------------+',
            '| 1  | alfa     | Admin   | Alfa Beta    | alfa@test.com  | 3     | Active  | 12/24/16, 5:00 PM |',
            '| 2  | gamma    | Manager | Gamma Delta  | gamma@test.com | 0     | Pending | 12/24/16, 5:01 PM |',
            '| 3  | ypsilon  | User    | Ypsilon Zeta | ypsilon.com    | 1     | Banned  | 12/24/16, 5:02 PM |',
            '+----+----------+---------+--------------+----------------+-------+---------+-------------------+',
        ], $this->out->messages());

But the same tests fail on travis, see [here](https://travis-ci.org/mirko-pagliai/me-cms/jobs/186636232).

It seems there is one less space on [line 220](https://travis-ci.org/mirko-pagliai/me-cms/jobs/186636232#L220) of the log, before the last pipe.

Why does this happen? What could be your problem?

**Comment by dereuromark** [comment]
Isn't it just different line endings?
Did you try comparing with assertTextEquals() as that will compare with those line endings being ignored.

**Comment by mirko-pagliai** [comment]
> Did you try comparing with assertTextEquals() as that will compare with those line endings being ignored.

Yes, there are various ways in which I think I could pass the test.
But I wanted to point out that it seems to me that the output can be different on different environments (?).

p.s. Merry Christmas! :)

**Comment by mirko-pagliai** [comment]
[Same error](https://travis-ci.org/mirko-pagliai/me-cms/jobs/186678009) with `assertTextEquals()`

**Comment by chinpei215** [comment]
@mirko-pagliai I may know the reason. If you run the following script in your local environment,
```php
$df = new IntlDateFormatter('en_US', IntlDateFormatter::SHORT, IntlDateFormatter::SHORT);
echo $df->format(time());
```
the output will be like the following:
```php
12/26/16, 8:45 AM
```

But if ICU version is 49.1.2, for example, the output will be like the following:
```php
12/26/16 8:47 AM
```
It will not contain the comma between date and time. Check your ICU (intl extension) version.
```bash
php -i | grep ICU
```

**Comment by markstory** [comment]
Closing as @chinpei215 has solved the problem :smile:

**Comment by mirko-pagliai** [comment]
Yes, I confirm. Thanks @chinpei215

**Comment by chinpei215** [comment]
@mirko-pagliai You are  welcome.
