### ISSUE TITLE
Enable routes to match based on the current hostname

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#9917]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.x

It would be helpful in some scenarios if routes could only match on specific hostnames. For example a fallback URL for an image host. Ideally `_host` would be provided in the route options.

In addition it could be useful to limit route matching based on the scheme.

Originally reported in #9912

**Comment by slince** [comment]
Not only host, scheme、method can also be supported

**Comment by markstory** [comment]
Route matching based on HTTP methods is already supported, but scheme is not.

**Comment by markstory** [comment]
Closing as this will be in 3.4.0
