### ISSUE TITLE
Select DISTINCT and MySQL 5.7

### ISSUE THREAD

**Issue by be-mohand** [cakephp/cakephp#9918]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10
* Platform and Target: MAMP with PHP 7, Apache and Mysql 5.7.12

### What you did
```php
public function findCurrent(Query $query, array $options)
    {
        $query->where(['end_date >' => Time::now()]);
        $query->distinct(['Highlights.listing_id']);
        $query->contain(['Listings']);

        $query = $this->findAll($query, $options);

        return $query;
    }
```

### What happened
In error.log:
Warning: Warning (512): Could not render cell - SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'my_db.Highlights.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [/path-to-my-app/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 36] in [/path-to-my-app/vendor/cakephp/cakephp/src/View/Cell.php, line 271]

### What you expected to happen
My query works with MySql 5.5.42 but not with MySql 5.7.12.

I've fixed it with this:
`mysql> set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

mysql> set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

mysql> exit;`

**Comment by markstory** [comment]
Newer Mysql enables stricter SQL modes. This is not an issue with CakePHP, and you need to add a group by clause to your query, or change your server's SQL mode to reaolve this.
