### ISSUE TITLE
Self joined entity overwriting old records

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#9922]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10.
* Platform and Target: Windows 10, PHP 7.0.9 

### What you did
//Relations are words->words_words->words
// in words table
```
        $this->belongsToMany('Dwords', [
            'className' => 'Words',
            'foreignKey' => 'word_id',
            'targetForeignKey' => 'dword_id',
            'joinTable' => 'words_words'
        ]);
```
// in words_words table
```
        $this->belongsTo('Words', [
            'foreignKey' => 'word_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Dwords', [
            'className' => 'Words',
            'foreignKey' => 'dword_id',
            'joinType' => 'INNER'
        ]);
```
// In words controller
```
        $this->request->data['id'] = '18d03fc2-dbcb-4f2f-aa3b-7ae5e4b72321';
        $this->request->data['dwords'][0]['language_id'] = 9;
        $this->request->data['dwords'][0]['name'] = 'hhhh';
        $this->request->data['dwords'][0]['state_id'] = 3;
        $this->request->data['dwords'][0]['user_id'] = $this->Auth->user('id');
        $word = $this->Words->get($this->request->data['id'], ['contain' => ['Dwords']]);
        $word = $this->Words->patchEntity($word, $this->request->data);
        debug($this->Words->save($word), ['associated' => ['Dwords']]);
```
### What happened
When i save trying to save new entity it is always overwrite exciting records.
It looks like 
word_id | dword_id
     1       |    3
### What you expected to happen
I want
word_id | dword_id
     1       |    1
     1       |    2
     1       |    3

**Comment by chinpei215** [comment]
See http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-belongstomany-associations
The default save strategy of belongsToMany association is `replace`. Probalby, if you add the following statement, it would work as you expected.
```php
$this->Words->Dwords->saveStrategy('append');
```

**Comment by infokani** [comment]
You saved my day.
