### ISSUE TITLE
Add `BelongsToMany::through()`

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#9929]
I'm writing some tests for for a `belongsToMany` association:

        $this->belongsToMany('Tags', [
            'foreignKey' => 'post_id',
            'targetForeignKey' => 'tag_id',
            'joinTable' => 'posts_tags',
            'className' => 'MeCms.Tags',
            'through' => 'MeCms.PostsTags',
        ]);

I have noticed that, unlike all other options, there is  not a method to retrieve the value of the `through` option.

This is my test:

        $this->assertEquals('Cake\ORM\Association\BelongsToMany', get_class($this->Posts->Tags));
        $this->assertEquals('post_id', $this->Posts->Tags->foreignKey());
        $this->assertEquals('tag_id', $this->Posts->Tags->targetForeignKey());
        $this->assertEquals('posts_tags', $this->Posts->Tags->joinTable());
        $this->assertEquals('MeCms.Tags', $this->Posts->Tags->className());

Now, as a matter of code integrity, I believe that the `BelongsToMany::through()` method should also exist:

        $this->assertEquals('MeCms.PostsTags', $this->Posts->Tags->through());

Am I wrong? What do you think about?

**Comment by chinpei215** [comment]
This will be solved in 3.4. https://github.com/cakephp/cakephp/blob/2f0133bbbe87929aa021830baf9ea2d8d9e29d46/src/ORM/Association/BelongsToMany.php#L997-L1005

**Comment by markstory** [comment]
Closing as this has been implemented in 3.4.0 as @chinpei215 noted.

**Comment by mirko-pagliai** [comment]
You're too fast for me! :-)
