### ISSUE TITLE
Extending the error handler doesn't work for developer thrown exceptions

### ISSUE THREAD

**Issue by ebrigham1** [cakephp/cakephp#9931]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3.10

I'm new to cake but not new to programming. I'm trying to extend the cake error handler to add additional behaviors. I'm looking to do things like email the dev team with exception information, or contact an API to generate a ticket, ect.
```php
namespace App\Error;

use Cake\Error\ErrorHandler as CakeErrorHandler;
use Exception;

class ErrorHandler extends CakeErrorHandler
{
    public function handleException(Exception $exception)
    {
        // Add emailing exception functionality
        $this->_emailException($exception);
        // Use parent functionality to log/display exception ect
        parent::handleException($exception);
    }
    // Code to email exceptions, throttle emails,
    // skip emails by exception class, ect
}
```
The issue I'm running into is that this class extension will work for all fatal errors that get wrapped up into exceptions, however it doesn't work for exceptions that a developer might choose to throw in the application since they seem to be caught, logged and displayed via [Cake\Error\Middleware\ErrorHandlerMiddleware](https://github.com/cakephp/cakephp/blob/master/src/Error/Middleware/ErrorHandlerMiddleware.php) rather than [Cake\Error\ErrorHandler](https://github.com/cakephp/cakephp/blob/master/src/Error/ErrorHandler.php)

For instance:
```php
namespace App\Controller;

use App\Controller\AppController;

class PaymentController extends AppController
{
    public function fulfillOrder()
    {
        // Process payment was successful
        // Attempt to fulfill payment, requires API calls to external resources
        // that fail
        throw new App\Exception\FulfillmentFailed('Order failed');
    }
}
```
Why aren't these types of exceptions also caught and handled by Cake\Error\ErrorHandler? When removing Cake\Error\Middleware\ErrorHandlerMiddleware from my local application middleware stack defined in App/Application I notice no difference in logging or rendering of those types of exceptions. So it seems like its largely doing the same job Cake\Error\ErrorHandler already does. Yet it forces me to also extend and override the middleware if I want to be able to add my functionality to those types of exceptions. Is there a reason these types of exceptions are caught in this manner rather than being allowed to bubble through to Cake\Error\ErrorHandler?

**Comment by ebrigham1** [comment]
Thanks for the quick reply @markstory, so post 3.4.0 or even 4.0.0 if I want to add behavior that occurs when both fatal errors happen and thrown exceptions happen what would be the prescribed approach by cakephp? Currently the documentation suggests three approaches:

- Create and register your own custom error handlers.
- Extend the BaseErrorHandler provided by CakePHP.
- Set the exceptionRenderer option on the default error handler.

Of which I've currently chosen option 2, extending the BaseErrorHandler. Would that approach change to just also extend and override ErrorHandlerMiddleware and store the added behavior in a trait or helper class that can be used by both?

**Comment by markstory** [comment]
If you need to handle both fatal errors and caught ones, and are on PHP5, you'll have to either:

1. Implement both an error handler and middleware.
2. Remove the middleware and use only the custom error handler.
3. Use PHP7 and make a custom middleware that catches `\Throwable` allowing you to catch fatal errors and exceptions for everything except bootstrapping issues.

**Comment by dereuromark** [comment]
Solutions outlined. And the main problem will be solved with PHP 7+.
