### ISSUE TITLE
Class of single and multiple checkboxes

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#9933]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.3
* Platform and Target: WAMP

### What you did
1. Build checbox
`echo $this->Form->input('Car.0', array('value' => 1);`

2. Build checboxes
`echo $this->Form->input('Car', array('multiple' => 'checkbox', 'options' => $arr);`

### What happened
1. Generate input with wrapped div like this:
```
<div class="input checkbox"></div>
```
2. Generate inputs with wrapped div like these:
```
<div class="input select">
    <div class="checkbox"></div>
    <div class="checkbox"></div>
    <div class="checkbox"></div>
</div>
```

### What you expected to happen
I know, the parent div of multiple checboxes has class `.input` and .`select`, but when we build multiple checkboxes, it should be attach `.input` class to each divs.

I think should be look like these:
```
<div class="select">
    <div class="input checkbox"></div>
    <div class="input checkbox"></div>
    <div class="input checkbox"></div>
</div>
```

However we build checkbox, they should be the same classes.

**Comment by markstory** [comment]
I'm not sure we can change this without breaking existing applications. The existing CSS class names have been in place for a really long time, and I would gamble moving CSS class names around will break the layout of an existing app.

**Comment by markstory** [comment]
Closing because I'm not comfortable with the risk of breaking existing applications.
