### ISSUE TITLE
RFC: Rename FormHelper::input() to something less confusing.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#9935]
I have seen questions similar to http://discourse.cakephp.org/t/validation-and-select-fields-cake-2-5/1782 asked numerous times.

Due to it's name many newbies assume `FormHelper::input()` can only generate `<input>` tag (along with label, error message etc.). So to avoid confusion it would be better to rename this method.

Alternatives off top of my head are: `field()`, `element()`, though I don't really like either.

**Comment by markstory** [comment]
`control()` might be another option too.

**Comment by inoas** [comment]
Control could be inline with what people consider those to be:

WhatWGs HTML docs speak of controls all time:

> Any form starts with a form element, inside which are placed the controls.

https://developers.whatwg.org/forms.html#forms

>      accept — Hint for expected file type in file upload controls 

https://developers.whatwg.org/the-input-element.html#the-input-element

So does Bootstrap, Ref: https://v4-alpha.getbootstrap.com/components/forms/#form-controls

**Comment by ADmad** [comment]
`Form::control()` works for me too. If we have a consensus I can make the PR to try and get this into 3.4.

**Comment by dereuromark** [comment]
control() sounds good. But we could also just as well do this for 4.0.
There is no time rush for those changes as the confusion here is really minimal. There are way more important issues at hand right now.

We should rather fix the API regarding the getter/setter combination painpoints and have those deprecations now all in for a cleaner API from here on in 3.4+.
Those PRs are still all open and we should now finalize all that and start removing the internal deprecation usage etc. That has priority IMO.

**Comment by josegonzalez** [comment]
@dereuromark We could introduce the control alias now so that people have time to migrate :)

**Comment by dereuromark** [comment]
All right
