### ISSUE TITLE
debug and exit

### ISSUE THREAD

**Issue by elbakai** [cakephp/cakephp#9938]
Sometimes we need to exit after using pr() function, so i think it's a good idea to add a function for that purpose which we can name it prd : (pr and die) 

```
    function prd($var)
    {
        pr($var);
        die;
    }
```

**Comment by ADmad** [comment]
So just add that function in your `config/bootstrap.php` or an other location you see fit :)

**Comment by Oxicode** [comment]
+1

**Comment by markstory** [comment]
Is it better to use `pr()` or `debug()`? I'm not a fan of the debug & die approach of development, but I know its a pretty common way to do development :smile:

**Comment by dereuromark** [comment]
You can revive my dd() PR :) 
Problem solved for all.

**Comment by josegonzalez** [comment]
@markstory I normally add a `diebug` method.

**Comment by markstory** [comment]
@josegonzalez If lots of people are re-implementing that function in each of their apps, we could save them time/effort by including one.

**Comment by dereuromark** [comment]
My words back then ;) https://github.com/dereuromark/cakephp-setup/blob/master/config/bootstrap.php#L5
Is one possible implentation for core.
I suggest we do add it with function_exists() Check, though.

**Comment by josegonzalez** [comment]
@dereuromark mine is basically `debug()` with a die at the end, but either way, works for me.

**Comment by dereuromark** [comment]
I find the location info quite useful, as otherwise it sometimes it is annoying to try to find them again.

**Comment by dereuromark** [comment]
PR open for further fine-tuning.
