### ISSUE TITLE
Model save()

### ISSUE THREAD

**Issue by bblaette** [cakephp/cakephp#9939]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3
* Platform and Target: Apache/2.4.23,  MySQL 5.6.21

```
Cake\Database\Connection Object
(
    [config] => Array
        (
            [password] => *****
            [username] => *****
            [host] => *****
            [database] => *****
            [port] => *****
            [driver] => Cake\Database\Driver\Mysql
            [persistent] => 
            [encoding] => utf8
            [timezone] => UTC
            [flags] => Array
                (
                )

            [cacheMetadata] => 1
            [log] => 
            [quoteIdentifiers] => 
            [url] => 
            [name] => default
        )

    [driver] => Cake\Database\Driver\Mysql Object
        (
            [connected] => 1
        )
    ...
)
```

### What you did
Problem first: I forgot to set auto increment on the PK for the table in question

Code in ModelsTable:

```
public function saveNewData($data) {
    $entity = $this->newEntity();
    $this->patchEntity($entity, $data);
    $saved_entity = $this->save($entity);    // failed silently
    if ($saved_entity === false) { return false; }
    ...
}
```

### What happened
Code ran until save and never reached my check for success / if ($saved_entity === false) 
No errors in logs/error.log
Nothing in logs/debug.log  

-> started debugging myself and drilled down to 
vendor/cakephp/cakephp/src/ORM/Table.php
vendor/cakephp/cakephp/src/Database/Query.php

### What you expected to happen
Exception trown, e.g. "INSERT failed on table `bamboozles`"
  _or_ at least FALSE as the return code of $this->save($entity)

**Comment by markstory** [comment]
What does your table schema look like? If the primary key columns are not present and there is no way to fill the you should get an exception from [this code](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L1631-L1636). You should also check that `$entity->errors()` is empty as it may contain validation or rules errors.

**Comment by bblaette** [comment]
Thanks for the pointers. After further investigation auto increment was not the problem.

I believe that the reason for the problem was that I did this
```
$entity = $this->newEntity();
$this->patchEntity($entity, $data);
```
instead of 
```
$entity = $this->newEntity($data);
```
and not getting a valid `$entity->id` further down in my code. 

Can be closed, I guess... Sorry, still learning the ropes of Cake 3
