### ISSUE TITLE
underscore difference between CakePHP Coding Standards and PRS-2

### ISSUE THREAD

**Issue by littleylv** [cakephp/cakephp#9940]
In [Coding Standards](http://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#member-visibility) you say:

> Additionally, non-public method or variable names start with a single underscore (_).

In [PSR-2: Coding Style Guide](http://www.php-fig.org/psr/psr-2/#4-2-properties) and [PSR-2: Coding Style Guide](http://www.php-fig.org/psr/psr-2/#4-3-methods):

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

> Method names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

Also, some other composer vendors like symfony and zendframework haven't use a single underscore too:
``grep 'protected function _' vendor/symfony/* vendor/zendframework/* -rl``
``grep 'protected function _' vendor/cakephp/* -rl``

Are there any reasons CakePHP starts with a single underscore? :)

**Comment by antograssiot** [comment]
`SHOULD NOT` is distinct from `MUST NOT` so it is not really a conflict.
You can read one of the original issue if you're interested (here)[https://github.com/cakephp/cakephp/issues/4499]

**Comment by littleylv** [comment]
@antograssiot Thanks for that. I'll read it.

**Comment by markstory** [comment]
We should probably stop recommending the underscore prefixes. In some of the newer parts of the framework we've stopped using `_` prefixes.

**Comment by antograssiot** [comment]
That's why I didn't close the issue in the first place. I too think that this note somould be removed.

**Comment by ADmad** [comment]
Our phpcs ruleset no longer dictates use of underscore prefix. I have opened a PR to update the docs.
