### ISSUE TITLE
Bootsrap Integration and Searchable Grid

### ISSUE THREAD

**Issue by mdmamunhasan** [cakephp/cakephp#9948]
Please integrate bootstrap default theme like Zend and Yii. And also a searchable grid like Yii.

**Comment by ADmad** [comment]
Thanks for the suggestion but we are not going to integrate any css/js frameworks with CakePHP. 

There are community plugins like [Bootstrap UI](https://github.com/FriendsOfCake/bootstrap-ui) and [Crud View](https://github.com/FriendsOfCake/crud-view) which you can use.
