### ISSUE TITLE
[bug] $this->request->here() inside requestAction duplicates query params incorecly

### ISSUE THREAD

**Issue by Asgraf** [cakephp/cakephp#9962]
CakePHP Version: v2.9.4

### What you did
1) Create myapp/View/Pages/test1.ctp with following contents:
````php
echo $this->requestAction('/pages/test2?variable=value',['return']);
echo $this->requestAction(['controller'=>'pages','action'=>'display','test2','?'=>['variable'=>'value']],['return']);
````
2) Create myapp/View/Pages/test2.ctp with following contents:
````php
debug($this->request->here());
````
3) Navigate to /pages/test1 in your browser

### What happened
$this->request->here() returns following invalid url in both cases:
````
/pages/test2?variable=value?variable=value
````

### What you expected to happen
$this->request->here() should return following url in both cases:
````
/pages/test2?variable=value
````
This bug causes SecurityComponent to blackhole all forms created inside actions that were requested with query variables via requestAction()

**Comment by markstory** [comment]
Closing as a pull request is open now.
