### ISSUE TITLE
Unable to set additional DSN options for SQLServer

### ISSUE THREAD

**Issue by keomaborges** [cakephp/cakephp#9963]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: Apache 2 on Windows Server, SQL Server 2012, PHP 7.0.13.

### What you did
We just uploaded the project to server and set the database config.

### What happened
```
Error: Invalid handle returned. 
File C:\APP_FOLDER\vendor\cakephp\cakephp\src\Database\Driver\PDODriverTrait.php 
Line: 48
```

### What you expected to happen
Connect to database successfully.

### What you did to solve
Searching about this issue I saw that I should add "ConnectionPooling=0" to DSN. I did it on vendor\cakephp\cakephp\src\Database\Driver\PDODriverTrait.php.

```
protected function _connect($dsn, array $config)
{
    $dsn .= ';ConnectionPooling=0'; // I added this line
    $connection = new PDO(
        $dsn,
        $config['username'],
        $config['password'],
        $config['flags']
    );
    $this->connection($connection);

    return true;
}
```

But I think that's not the best solution at all. So, I'm reporting the issue to be solved in future versions.

Thanks.

**Comment by markstory** [comment]
Sounds like we need a better way to set DSN flags in the database configuration. Right now that's not easy to do outside of hacking around with the `database` option which isn't optimal.

**Comment by keomaborges** [comment]
My first try was adding `'ConnectionPooling' => 0` on `Datasources` in app.php, but it did not work. I think it should be a good idea if we could add any flag on Datasources, if it could be possible.

**Comment by markstory** [comment]
@keomaborges We already have support for a number of connection options for MySQL, we've just not implemented all the SQLServer options as there are fewer SQLServer users than there are MySQL and Postgres.

**Comment by keomaborges** [comment]
@markstory I see. This project had to be built with the SQL Server because of a client requirement. If we could choose, we'd use MySQL. Thank you for the answer.

**Comment by markstory** [comment]
@keomaborges Are there any other connection options you use?

**Comment by keomaborges** [comment]
@markstory What do you call a connection option? This project was built using SQL Server 2012 and will be launched in production using the same database version.

**Comment by markstory** [comment]
Well `ConnectionPooling` is an connection option. Are there others you are using?

**Comment by stmeyer** [comment]
https://secure.php.net/manual/de/ref.pdo-sqlsrv.connection.php documents several connection options that are interesting: APP, ConnectionPooling,  Failover_Partner, TransactionIsolation

**Comment by keomaborges** [comment]
@markstory Yes, just one other: `'encoding' => PDO::SQLSRV_ENCODING_UTF8`

**Comment by markstory** [comment]
Would anyone be interested in putting together a pull request to add support for these options? If not I'll eventually get to it.

**Comment by keomaborges** [comment]
@markstory I can give it a try.

**Comment by markstory** [comment]
Awesome! If you need help navigating the code or tests let me know.

**Comment by markstory** [comment]
Closing as there was a merged pull request for this.
