### ISSUE TITLE
Incorrect multiple translation save when "I18n::locale(...)" is called

### ISSUE THREAD

**Issue by HoLyVieR** [cakephp/cakephp#9968]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.*
* Platform and Target: Ubuntu, Apache + PHP, MySQL

### The problem

The code snippet below will perform 2 update query :  
`UPDATE Competitions SET name = 'nameFRA value here' WHERE idCompetition = 11` and `UPDATE i18n SET foreign_key = 11 , content = 'nameENG value here' WHERE id = 24`. The problem here is that the first update query doesn't update the i18n table even if the code explicitly tries to update the translated value.

```
I18n::locale('fra');
$competition = $this->Competition->find('all', array(
    'conditions' => array ('idCompetition' => $id),
    'locales' => ['fra', 'eng']
))->find('translations')->first();
$competition->translation('eng')->name = 'nameENG value here';
$competition->translation('fra')->name = 'nameFRA value here';
$this->Competition->save($competition);
```

The side effect of this is that when retrieving the "Competition" object again, the translated field for "fra" will be missing. The code below will fetch both translation from the i18n table.

```
I18n::locale('fra');
$competition = $this->Competition->find('all', array(
    'conditions' => array ('idCompetition' => $id),
    'locales' => ['fra', 'eng']
))->find('translations')->first();
$competition->translation('eng')->name; // This will have the correct updated value.
$competition->translation('fra')->name; // This value doesn't have the updated value.
```
Do note that the saving part is correctly done (updates the i18n table for both translation) when `I18n::locale` isn't invoked. So how do I get the correct behavior while keeping a global locale set ?

**Comment by markstory** [comment]
The first time that `I18n::locale()` is callled it sets the 'default' locale. TranslateBehavior stores the 'default' locale on the host table. If you always store one locale on the host table you should be setting the default locale in your application's bootstrapping via `I18n::locale()`

**Comment by HoLyVieR** [comment]
But how are we suppose to handle per session language settings ? I though that `I18n::locale()` was roughly the equivalent of `$this->Session->write('Config.language', 'fra');` from CakePHP version 2.x.

**Comment by markstory** [comment]
`I18n::locale()` is roughly equivalent. However, the _first_ time it is called it sets the *default* language for your application. This default locale is stored in the host table when TranslateBehavior is used.

**Comment by markstory** [comment]
Closing as  the code does the right thing when the default locale for the application is set, and then the user session locale is set.

**Comment by KeidyU** [comment]
HoLyVieR  did solve this issue? i want to put my app in Spanish. I pasted these lines in my AppController
  use Cake\I18n\I18n;
public function initialize()
    {
      I18n::locale('es');
     }
and my locate: /locale/es/default.po

nothing is happen. even if i replace it in config/app.php

'defaultLocale' => env('APP_DEFAULT_LOCALE', 'es'),

what i missing?

**Comment by KeidyU** [comment]
I will answer to myself : the .po files where readable (mod 644), but the directory which containt them was  So, PHP coundn't find them... 
Then the solution:
chmod -R 777 Locate

Just if someone is newbie like me!
:)
