### ISSUE TITLE
2.x PHPunit 3.7.38 doesn't play nicely with PHP 7

### ISSUE THREAD

**Issue by swordbeta** [cakephp/cakephp#9973]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4
* Platform and Target: Centos 7 PHP 7.1.0

### What you did
```php
class MyModel extends Model {
    public function doSomething(array $data): array {
        // ....
    }
}
```

### What happened
Mocking the model with `$this->getMockForModel('MyModel');` results in the following error:

```
Declaration of Mock_MyModel_bea013db::doSomething(array $data = Array) must be compatible with MyModel::doSomething(array $data = Array): array	
```

Not just `getMockForModel` of course, all mocking methods do this.

### What you expected to happen
Model is successfully mocked.

Are there any plans to update PHPunit?

**Comment by markstory** [comment]
> Are there any plans to update PHPunit?

Not currently. I tried updating PHPUnit in the past and ran into a bunch of compatibility issues with how CakePHP handles sessions. But that was with the core tests. You might have better luck updating your app though.

**Comment by swordbeta** [comment]
@markstory Sadly our codebase has the same issues as the CakePHP core. I sadly also noticed PHPunit 5.x requires PHP >= 5.6 whereas CakePHP 2.9.x still supports PHP >= 5.3.0. Are there plans to retire unsupported PHP versions for CakePHP 2.x? Until then it seems we can't upgrade to a newer PHPunit version.

**Comment by markstory** [comment]
> Are there plans to retire unsupported PHP versions for CakePHP 2.x? Until then it seems we can't upgrade to a newer PHPunit version (through a PR).

Not at this point in time. Due to time constraints, I don't think there is much capacity to take on a larger project like updating all the core tests to run on a newer version of PHPUnit. Until there is time/capacity for that we don't really have a reason to drop support for older version of PHP.

**Comment by bancer** [comment]
@swordbeta PHPUnit 4.8 will be supported in 2.10.0. See https://github.com/cakephp/cakephp/pull/10405.

**Comment by ravage84** [comment]
@bancer according to the PHPUnit website, this does not make the test suite compatible to PHP 7, though:

> PHPUnit 4.8 was supported on PHP 5.3 – 5.6.

https://phpunit.de/

**Comment by swordbeta** [comment]
The 2.next branch is now compatible with phpunit 7, see PR: https://github.com/cakephp/cakephp/pull/10497
Hopefully we'll see a 2.10.0 release soon

**Comment by ravage84** [comment]
@swordbeta 

> Due by June 25, 2017

https://github.com/cakephp/cakephp/milestone/104
