### ISSUE TITLE
3.4 Event / Migration Docs

### ISSUE THREAD

**Issue by inoas** [cakephp/cakephp#9974]
Question/Feedback about the 3.4 Migration Guide

Did `class Event` really gain `setData()` / `setResult()` and `data()` / `result()` instead of `getData()` / `getResult()` ?

Ref: https://book.cakephp.org/3.next/en/appendices/3-4-migration-guide.html#event

* `data()` was already there: https://github.com/cakephp/cakephp/blob/master/src/Event/Event.php#L139 and should alias-point to `getData()`
* `result()` should be `getResult()` ? https://github.com/cakephp/cakephp/blob/3.next/src/Event/Event.php#L169

**Comment by markstory** [comment]
Looks like the docs are wrong. I'll get that fixed.

**Comment by inoas** [comment]
It seems more like the getters are named wrong in the source. Shouldn't it be getResult and getData for
https://github.com/cakephp/cakephp/blob/3.next/src/Event/Event.php#L169
https://github.com/cakephp/cakephp/blob/3.next/src/Event/Event.php#L194
(data() would need to be aliased for BC)?

**Comment by markstory** [comment]
I see what you're getting at now. We should rename those functions then as they don't match the newer conventions.

**Comment by markstory** [comment]
Code updated now.
