### ISSUE TITLE
Template for a multiple checkbox

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/cakephp#9977]
Hi, I have tried to create a template for a multiple checkbox.

But I can not leave it any way I like it, Item 2 is how it is getting and Item 3 on the link is how it should look.

How do I make it equal to Item 3?

Code
[http://pastebin.com/buxp3MsS](url)

**Comment by markstory** [comment]
You need to replace the label template to prevent the [input from being placed inside the label](https://github.com/cakephp/cakephp/blob/master/src/View/Widget/MultiCheckboxWidget.php#L183). This is the default behaviour as having the checkbox inside the label improves usability of chekbox controls.
