### ISSUE TITLE
3.5: Replace multi-mode method with separate get set methods.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9978]
Before stabilizing the API for 3.4, the following methods are not yet split and still are `$this|...` combinations that need to be separate methods for setting and getting:

Prio:
- [x] ORM Query::contain()
- [x] ORM Query::hydrate()
- [x] ORM Query::autoFields()
- [x] Database Query::valueBinder()

Nice to have:
- [x] QueryTrait::mapReduce()
- [x] QueryTrait::formatResults()
- [ ] TranslateTrait::translation()
- [x] Message::body()
- [x] ValidatorAwareTrait::validator()
- [x] ModelAwareTrait::modelType()
- [x] EntityTrait::hiddenProperties()
- [x] EntityTrait::virtualProperties()
- [x] EntityTrait::errors()
- [x] EntityTrait::source()
- [x] EntityTrait::accessible()
- [x] QueryTrait::eagerLoaded()
- [x] ServerRequest::env()
- [x] LocatorAwareTrait::tableLocator()
- [x] TableRegistry::locator()
- [x] EventDispatcherTrait::eventManager()

Hard to do:
- [x] QueryInterface::repository() / QueryTrait::repository()
- [x] InvalidPropertyInterface::invalid() / EntityTrait::invalid()
- [x] TypedResultInterface::returnType() / TypedResultTrait::returnType()

Already PR opened ( https://github.com/cakephp/cakephp/pull/9769 ):
- InstanceConfigTrait
- StaticConfigTrait

Dangerous $this|null (!) when chaining:
- [x] Query::traverseExpressions()

**Comment by dereuromark** [comment]
- Query::contain() could stay as setter, and Query::getContained() could get?
- Query::valueBinder() into get and set? Or is there something behind the internal ValueBinder class?

**Comment by inoas** [comment]
I'd leave the magic setters/getters (until deprecated). As long as the old interface is there, it will work as expected/learned. So there should be `setContain()`?

**Comment by chinpei215** [comment]
@dereuromark I think you can also add `Database Query::from()` to the list. https://github.com/cakephp/cakephp/pull/10033#discussion_r96113162

**Comment by cleptric** [comment]
What about `EntityTrait ::dirty`?

**Comment by dereuromark** [comment]
Feel free to continue the list of things I might have missed as checklist here to cross of during the next 3.x releases.

**Comment by burzum** [comment]
I've added dirty and made more changes to the code. Need to add some tests to finish this.

**Comment by burzum** [comment]
What about these?

* Controller::getRequest()
* Controller::getResponse()
* Helper::getRequest()
* Helper::getView()

**Comment by dereuromark** [comment]
@burzum At this point in 3.x I would mainly focus on the combined ones that mix $this|...
All other "consistency renaming" I would postpone or not do at this point - because it is mainly then for naming consistency, whereas the above have priority regarding fluent inferface breaking and other issues with that kind of mix.

**Comment by robertpustulka** [comment]
Found another one: `LocatorAwareTrait::tableLocator()`.

**Comment by cleptric** [comment]
Found `Table::alias()`, `Table::registryAlias()`, `Table::schema()`

**Comment by robertpustulka** [comment]
What about `EventDispatcherTrait` and `EventDispatcherInterface` ?

**Comment by ypnos-web** [comment]
`ServerRequest::session()`:

>  * @param \Cake\Network\Session|null $session the session object to use
>  * @return \Cake\Network\Session

**Comment by saeideng** [comment]
That is object that you can set/get session with it

**Comment by ypnos-web** [comment]
Thanks saeding, my point is that this method should also be split into get/set.

**Comment by mirko-pagliai** [comment]
So: 
1) `BelongsToMany::getJoinTable()` and `BelongsToMany::setJoinTable()` (the `jointable()` method currently does not exist. There is only the `joinTable` option as setter and no getter)
2) `BelongsToMany::getJunction()` and `BelongsToMany::setJunction()`
3) `Association::getClassName()` and `Association:setClassName()` (now exists the `className` option as setter and the `className()` as getter, very bad);

**Comment by mirko-pagliai** [comment]
6) missing `Response::getType()`. Instead the `withType()` method is present. The old `type()` method has not been marked as deprecated

**Comment by mirko-pagliai** [comment]
7) as for 5), there are many methods (`theme()`, `template()`, etc) that in the `ViewBuilder` class are split into get/set methods, while in the `View` class they keep the old syntax.
This can generate a lot of confusion, it would be better that they coincide.

**Comment by saeideng** [comment]
> missing Response::getType(). Instead the withType() method is present.

that is true 

` withX()` is for immutable methods 
` getX()` is for mutable  methods

**Comment by mirko-pagliai** [comment]
@saeideng what follows is my personal opinion. And I know that my opinion comes a little late...

I would expect that `setX()` and `getX() are for mutable methods and `withX()` and `getX()` is for immutable methods. In short, the `getX()` method should allow to get in safety to a property, in any case.

But I gladly accept that you tell me that does not fit well or that has already been decided in the past how to proceed :-)

**Comment by inoas** [comment]
AFAIK:
- `$obj->getX()` mutable getter, returns $obj property
- `$obj->setX()` mutable setter, returns mutated $obj
- `$obj->withX()` immutable setter, returns cloned $obj

Correct?

**Comment by saeideng** [comment]
I means 
`withX()` is for  setting in **immutable** methods
`x()` is for **immutable** methods

`setX()` is for **mutable** methods
`getX()` is for **mutable** methods

**Comment by saeideng** [comment]
> the `getX()` method should allow to get in safety to a property, in any case.

when you using `withX()` , `x()` is safe for getting property because `x()` is just for getting and  you have  not `x()` for setting in cake 4.X ver IMO

**Comment by markstory** [comment]
@mirko-pagliai response has no getType() method on purpose. Instead you can use getHeaderLine() to access the content-type header.

Why wouldn't `getX()` be used to read properties on immutable objects?  That is a pattern we already use quite a bit. Having two conventions for property reading methods makes remembering how to use objects harder than if we had one convention for all methods.

Having two conventions for setter methods on mutable/immutable objects makes sense as the name of the method lets you know how the object behaves.

**Comment by dereuromark** [comment]
I will close this as we all are aware of it moving forward and can still reference this.
It is an ongoing task that will shape 4.x then when we can finally remove the deprecations.

**Comment by ndm2** [comment]
Has `TranslateBehavior::locale()` been overlooked, or is there maybe an exception for behaviors?

**Comment by dereuromark** [comment]
It sure has been overlooked at this point. There also others not yet fully done which could be added in 3.6 or 3.7.

**Comment by ndm2** [comment]
I see... I've got a few minutes, so I could at least take care of `TranslateBehavior::locale()`.

**Comment by dereuromark** [comment]
@ndm2 

For me the following important ones are not done yet either:

- Query::contain() getter or setter (`@return array|$this` smell)
- QueryInterface::repository() + QueryTrait::repository() (`\Cake\Datasource\RepositoryInterface|$this` smell)
- QueryTrait::mapReduce() (`$this|array`)
- QueryTrait::formatResults() (`$this|array`)
- Query::traverseExpressions() as mentioned above.

**Comment by robertpustulka** [comment]
Also this one I found recently: [`Validator::field()`](https://github.com/cakephp/cakephp/blob/1dac37a82b020e2cd933de930d00e0664f0eae7c/src/Validation/Validator.php#L163)

**Comment by dereuromark** [comment]
@robertpustulka I consider the chainable mixed ones more dramatic, yours just always returns an array, so not too big of a deal. But I agree, for consistency we can also tackle those at some point.
I do need help however regarding the last 2 remaining important ones.

**Comment by saeideng** [comment]
cake 3.6 > 
`Http/Session::engine()` =>`getEngine()` /`setEngine()`

**Comment by dereuromark** [comment]
We should finalize those last deprecations for the next release IMO.
So that we can have a final API moving forward with the 3.7+ releases then.

**Comment by chinpei215** [comment]
- [ ] Database\Query::from()
- [ ] Database\Query::join()

Since there is already a getter - clause(), we would not need to add additional getters for these methods.

**Comment by chinpei215** [comment]
I didn't know the above methods has been already fixed in #12229 few hours ago 😛

**Comment by dereuromark** [comment]
Also for a follow up PR: I can see 5+1 `$this|...` still in the code base, e.g.

     * @return $this|array
     */
    public function join($tables = null, $types = [], $overwrite = false)

and

     * @return $this|\Cake\Datasource\EntityInterface
     */
    public function translation($language)

etc
which we need to fix up into separate setter and getter calls etc.

The +1 is |$this:

     * @return array|$this
     */
    public function contain($associations, $override = false)

**Comment by saeideng** [comment]
`join()` and `contain` 
will be `@return $this` in 4.x

**Comment by dereuromark** [comment]
@saeideng Are you sure? my findings above refer to current 4.x master branch which do not yet contain any fixes for these 5+ issues. I also dont see a PR that contains this.

**Comment by saeideng** [comment]
maybe
- [ ]  Filesystem\File::offset();
https://github.com/cakephp/cakephp/blob/99b75f5b1e6c9215c1b13ad927601762709b1ebf/src/Filesystem/File.php#L183-L186

>@return int|bool True on success, false on failure (set mode), false on failure or integer offset on success (get mode)

**Comment by dereuromark** [comment]
We should make sure this list is finally complete for 3.7
Especially now that RCs are produced ( https://github.com/cakephp/cakephp/releases/tag/3.7.0-RC1 ).

What of the above list is still missing?
Only the dangerous $this|... one of Query::traverseExpressions()?

**Comment by markstory** [comment]
Which methods are not complete?

**Comment by dereuromark** [comment]
`TranslateTrait::translation($language)` is missing, but since this always returns "some" object of this interface, not too big of a deal at this time. Closing then as complete.
