### ISSUE TITLE
U_ILLEGAL_ARGUMENT_ERROR when using i18n/__x() context calls

### ISSUE THREAD

**Issue by micdobro** [cakephp/cakephp#9985]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: Ubuntu 14.04, Apache 2.4, PHP 5.5.9, MariaDB 5.5

### The problem
We are heavily using context support in i18n (plenty of ``__x()`` calls). 
``.po`` file for a text "Welcome" contains the following entries: 

```
msgctxt "onboarding"
msgid "Welcome"
msgstr "Velkommen"
```
and nothing else. 

When I add in the code the following: 

```php 
'header_text_placeholder' => __x('hub settings', "Welcome"),
```

then the following exception is thrown:  ``Aura\Intl\Exception\CannotInstantiateFormatter``

``msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR ``

And debug info: 

```
Notice (8): Undefined index: hub settings [CORE/src/I18n/Formatter/IcuFormatter.php, line 56]
Warning (2): end() expects parameter 1 to be array, null given [CORE/src/I18n/Formatter/IcuFormatter.php, line 69]
```

Generation of a new `.pot` file is not possible via the shell when this error is present. 

```shell
$ bin/cake i18n extract --extract-core=yes --merge=yes --app=/srv/src --paths=/srv/src --output=/srv/src/Locale --overwrite=yes
Notice Error: Undefined index: hub settings in [/srv/vendor/cakephp/cakephp/src/I18n/Formatter/IcuFormatter.php, line 56]

Warning Error: end() expects parameter 1 to be array, null given in [/srv/vendor/cakephp/cakephp/src/I18n/Formatter/IcuFormatter.php, line 69]

Exception: msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR in [/srv/vendor/cakephp/cakephp/src/I18n/Formatter/IcuFormatter.php, line 101]
```

When I add the missing context to the file (manually): 

```
msgctxt "onboarding"
msgid "Welcome"
msgstr "Velkommen"

msgctxt "hub settings"
msgid "Welcome"
msgstr "Velkommen"
```

Then everything works as expected (as the array key is then present).

### Expectation
I think instead of failing it should just return the original text (`msgid`). It is clear, that the `.po` file does not contain an entry for this particular context - and hence the error.

**Comment by markstory** [comment]
Pull request up now.
