### ISSUE TITLE
Modified files due to incomplete .gitattributes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#9986]
In CakePHP 3.x when doing composer update and using dev-3.next etc, you always get the following error/warning:

```
    The package has modified files:
    M .editorconfig
    M .gitattributes
    M .github/CONTRIBUTING.md
    M .github/ISSUE_TEMPLATE.md
    M .github/PULL_REQUEST_TEMPLATE.md
    M .gitignore
    M .mailmap
    M .scrutinizer.yml
    M .stickler.yml
    M .travis.yml
-10 more files modified, choose "v" to view the full list
```

I think we need to add those to the .gitattributes file (as non binary), and also make sure they have the line endings we expect them to have.

**Comment by ADmad** [comment]
Might be an issue on windows only. I have never got such an error.

**Comment by dereuromark** [comment]
It is actually on a Ubuntu Linux.

**Comment by dereuromark** [comment]
The default setting of that vagrant CakeBox is `core.autocrlf=input` by the way.
I can now check with `git config --global core.autocrlf true` and the resulting `core.autocrlf=true` set.

**Comment by markstory** [comment]
I don't get those errors ever on OSX. Might be vagrant related issue.

**Comment by dereuromark** [comment]
Must be, but it happens on both windows and ubuntu and CakeBox. I will try around with the autocrlf option a bit more.
Closing for now then.
