### ISSUE TITLE
Wrong return type hint in Controller::redirect

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/cakephp#9987]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4

### What happened
Phpdoc comment suggests that Controller::redirect method returns \Cake\Network\Response|null 

### What you expected to happen
It actually returns CakeResponse|null

I don't know if this is the place for this kind of issues or maybe it should be posted on documentation (?), anyway, I wanted to let you know about it.

**Comment by dereuromark** [comment]
This was probably a copy and paste error from 3.x.
You are right about CakeResponse for 2.x.

**Comment by xavier83ar** [comment]
Not right now, but I guess I'll be able tomorrow... If that's ok, I've no problem doing it.
