### ISSUE TITLE
Table::_processSave() calls EntitiyTrait::extract() that calls EntityTrait::get()

### ISSUE THREAD

**Issue by Kunimaru** [cakephp/cakephp#9991]
First of all, as I'm not so familiar with English, please don't be so angry and please advise me kindly if this issue isn't suitable for this place now.

This is a:
* [x] bug (maybe)

* CakePHP Version: 3.7.7
* Platform and Target: Apache, MySQL (Not related)

### What you did
Called Cake/ORM/Entity::newEntity() and Cake/ORM/Table::save() method

### What happened
I found that Entity::$created in SQL sentence was null.
I found that EntityTrait::get() was called in EntitiyTrait::extract() (was called in `Table::_processSave()` and it was printed in StackTrace) and value to be inserted was filtered by `_getPropertyName()` accessor.

Cake/ORM/Table.php
```
    protected function _processSave($entity, $options)
    {
        /* ommited */

        $data = $entity->extract($this->schema()->columns(), true);

        //
        // When printed $data here, value was null because value filtered by accessor was invalid
        //

        /* ommited */
    }
```

Cake/Datasource/EntityTrait.php
```
    public function extract(array $properties, $onlyDirty = false)
    {
        /* ommited */

        foreach ($properties as $property) {
            if (!$onlyDirty || $this->dirty($property)) {
                $result[$property] = $this->get($property);
            }
        }

        /* ommited */
    }

    public function &get($property)
    {
        /* ommited */

        $method = $this->_accessor($property, 'get');

        /* ommited */

        if ($method) {
            $result = $this->{$method}($value);

            return $result;
        }

        /* ommited */
    }
```

### What you expected to happen
`_get[PropertyName]()` accessor wasn't called when we create SQL sentence.

**Comment by markstory** [comment]
Why does the getter being called during create statements cause an issue? We cannot easily change this behavior because it will break existing applications.

**Comment by Kunimaru** [comment]
Thank you for answering.
Oh I see. It is a normal behavior. In that case that was not a problem.
