### ISSUE TITLE
Many regex in the Validation method miss a trailing newline

### ISSUE THREAD

**Issue by tenkoma** [cakephp/cakephp#9992]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11
* Platform and Target: macOS X Sierra + PHP 5.6.28

### What you did
Validation method using regular expression like `email()` verified string with a newline at the end.

```php
<?php

namespace App\Test\Model\Validation;

use Cake\TestSuite\TestCase;
use Cake\Validation\Validation;

class ValidationTest extends TestCase
{
    public function testEmail()
    {
        // This assertion will failed.
        self::assertFalse(Validation::email("user@example.com\n"));
    }
}
```

### What happened
return true.

### What you expected to happen
return false.

Similar problem fixed: #1177

**Comment by ADmad** [comment]
Closing as related PR is opened.
