### ISSUE TITLE
Accessing an existing route with an invalid method throws `MissingRouteException` instead of `MethodNotAllowedException`

### ISSUE THREAD

**Issue by mikeu** [cakephp/cakephp#9994]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.3.6
* Platform and Target: PHP : 7.0.8-0ubuntu0.16.04.3, Apache/2.4.18 (Ubuntu), requests made with Postman 4.9.2.

### What you did

1. Created an index route, accessible via GET:

        $routes->connect('/test', ['_method' => ['GET'], 'controller' => 'Test', 'action' => 'test_success']);

1. Submitted a POST request to the route, using [Postman](https://www.getpostman.com/).

### What happened

Received a Missing Route exception, stating:

> ## Error: A route matching "/test" could not be found.
> 
> None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php
>
> ### Connected Routes
>
> | Template	| Defaults	| Options |
> | ------------- | ------------- | ------------- |
> | /test	| [ '_method' => [ (int) 0 => 'GET' ], 'controller' => 'Test', 'action' => 'test_success', 'plugin' => null ]	| [ '_ext' => [], 'routeClass' => 'Route' ] |

The claim that the route was missing combined with its presence in the list of connected routes given by the error message, led me on a longer debugging session than would have been ideal. It's true that the connected route specifies GET, but the error message _doesn't_ specify that the attempted access was via POST, or that the problem is with the method rather than the path.

### What you expected to happen

When a route exists, but an unacceptable method is used to attempt to access it, I would have expected to see some sort of notification that the method was part of the problem, not just the route. One solution would be to have a different exception and introduce additional logic to detect this case. A much simpler approach would be to simply include the method in the error message, such as `Error: A "POST" route matching "/test" could not be found.`

**Comment by markstory** [comment]
I think updating the error message might be the simplest thing here. While you are right that the most appropriate HTTP error is a 405, each route only knows if it could match the request. Because each route is unaware of the other routes, we can't use an exception/error to signal that it was the method condition that failed, and not the URL being incorrect.

**Comment by markstory** [comment]
Closing as the error message was improved in #9995
