### ISSUE TITLE
maybe a issue  when set session.timeout = 0

### ISSUE THREAD

**Issue by visonforcoding** [cakephp/cakephp#9997]
This is a:

* [x] bug

* CakePHP Version: v3.3.6

First ,thank you all the member of cakephp . 
Maybe it`s my problem.
I am not sure  this is a bug. if not please forgive me.
I saw the souce code in Cakephp/Network/Session.php

the function 
```php
 protected function _timedOut()
    {
        $time = $this->read('Config.time');
        $result = false;

        $checkTime = $time !== null && $this->_lifetime > 0;
        if ($checkTime && (time() - $time > $this->_lifetime)) {
            $result = true;
        }

        $this->write('Config.time', time());

        return $result;
    }
```
when set  session.timeout = 0 .  _timeOut( ) will return false . Session start() function will not destory session. 

But the  built in php `s gc will work.
there are  session.gc_probability/session.gc_divisor  (default 1/100) probability destory the sesion,after gc.gc_maxlifetime seconds.

**Comment by visonforcoding** [comment]
v3.3.6

**Comment by markstory** [comment]
Does this result in all your sessions being timed out too early, or not at all?

**Comment by visonforcoding** [comment]
I did some test in this morning (BeiJing timezone) . It seems the result is not at all.   Just i think by  principle .beacuse  i saw the source code didn`t  disable  gc .  I think the gc will work to expire  the session.

**Comment by ADmad** [comment]
I don't think any change is required in code. At best we just need to document that developer should ensure gc_maxlifetime is greater than timeout value.

**Comment by visonforcoding** [comment]
Yes.maybe  I am wrong .thank you . I know why should ensure gc_maxlifetime is greater than timeout value.

Because
>Note: If different scripts have different values of session.gc_maxlifetime but share the same place for storing the session data then the script with the minimum value will be cleaning the data

But the gc `s work working mechanism is very mistiness and it`s hard to see the work result, so...
